### ISSUE TITLE
Support VFD

### ISSUE THREAD

**Issue by Zingisa1** [ophub/amlogic-s9xxx-armbian#1]
Hi 

Thank you for this amazing project amlogic-s9xxx-armbian.

Please add front led display support on your next release and also extend rootfs with free unallocated space from micro-sd card on first boot.

Thank you and kind regards

**Comment by ophub** [comment]
I use the default value of Lepotato, you can set the required functions when compiling Lepotato.

**Comment by Zingisa1** [comment]
Do you mind telling me steps of how to set it?

**Comment by ophub** [comment]
https://docs.armbian.com/Developer-Guide_Build-Preparation/

The armbian official website has very detailed personalized customization tutorials, and you can customize the build according to your needs.
