### ISSUE TITLE
How to support new S905x3 Tanix TX3 box

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#100]
I have a Tanix Tx3 box with the following configuration:
CPU S905X3
Ram 2G, eMMC 16GB
WIFI Sp6330.
https://androidpctv.com/review-tanix-tx3-s905x3-opinion/
https://www.youtube.com/watch?v=ssp1DC4KaNs

This devices is not in the supported list so I just wonder how to support this one.

Thank you.

**Comment by ophub** [comment]
You can try to use the firmware of s905x3
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_focal_02.03.1542#:~:text=Armbian_22.02.0_Aml_s905x3_focal_5.4.176_2022.02.03.1532.img.gz

**Comment by dinhchinh82** [comment]
I will try and give you the result. By the way, is there any advantages to use Armbian 5.10.x than 5.4.x?

**Comment by ophub** [comment]
Again, both are several years of long-term support for the kernel. 

First test the 5.4 kernel, this can be used only with dtb support. After confirming the dtb, use the 5.10 kernel to test whether u-boot supports it.

**Comment by dinhchinh82** [comment]
@ophub do we need to extract the u-boot file from original stock Android firmware?

**Comment by ophub** [comment]
No need, in the /boot directory of armbian there are

**Comment by EastWoodYang** [comment]
> You can try to use the firmware of s905x3
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_02.03.1542/Armbian_22.02.0_Aml_s905x3_focal_5.4.176_2022.02.03.1532.img.gz
这个固件支持WiFi和蓝牙吗？如果支持的话 我可以买一个tx3来测试下
