### ISSUE TITLE
Enable S2 and T2 DVB for Mecool KI Pro

### ISSUE THREAD

**Issue by intropedro** [ophub/amlogic-s9xxx-armbian#1001]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905D
 - Model Mecool KI Pro

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.91
 - Release: jammy

**Describe the bug | 问题描述**

I have download your image "Armbian_23.02.0_amlogic_s905d-ki_jammy_5.15.91_server_2023.02.02" for a tv box Mecool Ki Pro. The system boot ok but the tunners are not detected (/dev/dvb does not exist).

It would be possible to add support to the tuners of the device s2 and t2 dvb?

Thank you

详细描述问题，并在必要时附上屏幕截图。

![photo_5971838810759216295_y](https://user-images.githubusercontent.com/2871487/216406886-724b6295-0b80-408e-8aa8-4847973f3169.jpg)

**Comment by ophub** [comment]
armbian-update -k 5.10.166

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/341

https://github.com/ophub/amlogic-s9xxx-armbian/pull/930

Reference

**Comment by intropedro** [comment]
I've been reading everything and testing, but I haven't been able to get it to work. I put what I have tried so you can tell me if I have done something wrong.

I started from image "Armbian_23.02.0_amlogic_s905d-ki_bullseye_5.15.91_server_2023.02.05.img". This has the kernel version 5.15.91-flippy-81+o and from what I understand it shouldn't work and it doesn't work (Which is correct)

I have updated to version 5.10.166 (this has the kernel 5.10.166-ophub) which is supposed to work:

`>> sudo armbian-update -k 5.10.166`

But there is no dvb:

```
>>  ls -l /dev/dvb
>>  sudo dmesg | grep dvb
```

Then I tried with it 5.4.230 (this has the kernel 5.4.230-ophub)

`>> sudo armbian-update -k 5.4.230`

Same result without dvb

Putting your compiled kernel 6.1.9:

```
>>  wget https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/kernel_5.15.91_6.1.9/6.1.9.tar.gz
>>  tar -zxvf 6.1.9.tar.gz
>>  cd 6.1.9/
>>  sudo armbian-update
```
Same result without dvb

Putting your compiled kernel 5.15.91
```
>>  wget https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/kernel_5.15.91_6.1.9/5.15.91.tar.gz
>>  tar -zxvf 5.15.91.tar.gz 5.15.91/
>>  cd 5.15.91/
>>  sudo armbian-update
```
Same result without dvb

I understand that these last two kernels are compiled with the ".config" file in which the dvbs were added, so if my card doesn't work, it may be because it isn't among what was added. Then I would have to add something to that file indicating my card and compile the kernel. But I don't know what I should add, or if that would be supported.

Another option is that if the kernel doesn't integrate the drivers for my card, I compile the driver and install it. I have also been trying to do that without success. The driver is supposed to be in "media_build", but it seems that this is very outdated and trying in various ways (For example from https://github.com/tbsdtv/media_build) I have not been able to compile them, the same for newer versions of gcc or for things I don't know (I control a lot about compiling kernels and tools)

I'm right? Can you think of any other way I can try?

Many thanks for everything

**Comment by intropedro** [comment]
My tv box has an R848 Rev 1.3 board that I think has these two:

- avl6211 dvb-s2
- avl6862 dvb-t2

**Comment by ophub** [comment]
The update method of the kernel is correct. It is already supported at the kernel level.


I have never been in touch with the driver and usage, you can ask how other users in those few questions use it.

**Comment by intropedro** [comment]
I am trying compile media_build with this commands:

```
 >> mkdir /tmp/tbs
 >> cd /tmp/tbs
 >> git clone https://github.com/tbsdtv/media_build.git
 >> git clone --depth=1 https://github.com/tbsdtv/linux_media.git -b latest ./media
 >> cd media_build
 >> make dir DIR=../media
 >> make allyesconfig
 >> make -j4
```

But I have see this warning:

```
  ./scripts/make_kconfig.pl /lib/modules/5.4.230-ophub/build /lib/modules/5.4.230-ophub/build 1
  Preparing to compile for kernel version 5.4.230
  
  ***WARNING:*** You do not have the full kernel sources installed.
  This does not prevent you from building the v4l-dvb tree if you have the
  kernel headers, but the full kernel source may be required in order to use
  make menuconfig / xconfig / qconfig.
```

I installed headers with armbian-config, but I think thath they don't well installed. It is corrects this way?

**Comment by ophub** [comment]
/usr/src/linux-headers-$(uname -r)
