### ISSUE TITLE
请求帮忙编译一个USB WiFi驱动

### ISSUE THREAD

**Issue by muxi01** [ophub/amlogic-s9xxx-armbian#1002]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3] s905l3a
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]  5.15.90
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

请求大佬帮忙编译一个USB WIFI驱动，我编译的时候实在无法拉取内核代码，导致无法编译。
购买途径：拼多多 COMFAST旗舰店
USB WIFI 品牌： COMFAST 
USB WIFI 型号： CF-WU817N
所采用的芯片：ATBM603
源码路径：https://github.com/OpenIPC/atbm_60xx

感谢！！！

**Comment by ysuolmai** [comment]
请问你解决这个问题了么？
