### ISSUE TITLE
Can't boot on X96 MAX +

### ISSUE THREAD

**Issue by delta-whiplash** [ophub/amlogic-s9xxx-armbian#1005]
Hello I just downloaded the latest version of armbian jammy (23.02.0_amlogic_s905x3_jammy_5.15_91_server_2023.02.02)
I flashed the image on an USB stick an I tried both port (USB 3 and 2)
But when I try to start it with the AV button 
It stuck on this screen could you help me please
![IMG20230203172741.jpg](https://user-images.githubusercontent.com/39416418/216655452-e899dc41-fe7f-40f0-af20-969cb78379d4.jpg)

**Comment by d5stick** [comment]
Did you modify the /boot/uEnv file with the correct DTB file matching your box?

**Comment by delta-whiplash** [comment]
I have to do it ? For my x96-mini it was working without modifications what I have to do ?

Hanni, molabaccus
________________________________

**Comment by d5stick** [comment]
Yes, Verify your model and choose the correct dtb:
![afbeelding](https://user-images.githubusercontent.com/53115937/216658288-9d573364-9818-4909-9db9-e7160e1c9a89.png)

**Comment by delta-whiplash** [comment]
How can I know my x96 max + ?
![IMG20230203185505.jpg](https://user-images.githubusercontent.com/39416418/216673454-ebe3fb0d-7b75-4618-bf1e-ee83240503d7.jpg)

**Comment by StatixBolt** [comment]
Use this Armbian_23.02.0_amlogic_s905x3_jammy_6.1.9_server_2023.02.02.img.gz, it shoudl boot by deafualt on your box.

**Comment by delta-whiplash** [comment]
I will try this right now If it's helpful this is is my device name

**Comment by delta-whiplash** [comment]
I can now boot thank you Soo much 
But seem I have a small issue I can't use the gigabit speed 
And I picked at first time the 5.15 kernel because I wanted an LTS kernel 
![IMG20230203204646.jpg](https://user-images.githubusercontent.com/39416418/216694070-6bc4a066-cf8c-48bd-b7a2-6eda8e45ed58.jpg)

**Comment by delta-whiplash** [comment]
I can now boot thank you Soo much 
But seem I have a small issue I can't use the gigabit speed 
And I picked at first time the 5.15 kernel because I wanted an LTS kernel 
![IMG20230203204646.jpg](https://user-images.githubusercontent.com/39416418/216694070-6bc4a066-cf8c-48bd-b7a2-6eda8e45ed58.jpg)

**Comment by d5stick** [comment]
Try this ![afbeelding](https://user-images.githubusercontent.com/53115937/216698641-3863a985-43bc-4926-8556-63ef8ab98b17.png)
Update the uEnv file with that DTB. This should fix your network speed.

**Comment by StatixBolt** [comment]
Open your sdcard your pc
then open the boot folder and eddit your  uEnv to say 
![image](https://user-images.githubusercontent.com/108201239/216698988-519e996e-78da-44cf-8d3a-db76ba8d5cc8.png)

**Comment by delta-whiplash** [comment]
ok thank you,
On the 5.15 kernel or the 6.1.9

**Comment by StatixBolt** [comment]
6.1.9

**Comment by delta-whiplash** [comment]
Ok I see thank you am gonna try this 
Do you think the 6.1.9 is stable for something like kubernetes server (with k3s distribution) or proxmox I didn't choose for now

**Comment by delta-whiplash** [comment]
> Open your sdcard your pc then open the boot folder and eddit your uEnv to say ![image](https://user-images.githubusercontent.com/108201239/216698988-519e996e-78da-44cf-8d3a-db76ba8d5cc8.png)

Seem it's stuck again on the splash screen

**Comment by d5stick** [comment]
Try the other DTB files matching your box.

**Comment by delta-whiplash** [comment]
Ok I am on this thank you soo much for the help

**Comment by delta-whiplash** [comment]
KERNEL 6.1.9
meson-sm1-x96-max-plus.dtb => Boot OK, ethernet 1000mbps
meson-sm1-x96-max-plus-100m.dtb => Boot OK, ethernet 100mbps
meson-sm1-x96-max-plus-ip1001m.dtb => Boot OK, ethernet error raise network interface
meson-sm1-x96-max-plus-ip1001m-2.dtb => Boot OK, ethernet error raise network interface
meson-sm1-x96-max-plus-oc.dtb => Boot OK, ethernet 1Gps
meson-sm1-x96-max-plus-q1.dtb => Boot OK, ethernet error raise network interface
meson-sm1-x96-max-plus-q2.dtb => Boot OK, ethernet 1Gps, bluetooth errors


KERNEL 5.15.91
meson-sm1-x96-max-plus.dtb => Boot NOK
meson-sm1-x96-max-plus-100m.dtb => Boot NOK
meson-sm1-x96-max-plus-ip1001m.dtb => Boot NOK
meson-sm1-x96-max-plus-ip1001m-2.dtb => Boot NOK
meson-sm1-x96-max-plus-oc.dtb => Boot NOK
meson-sm1-x96-max-plus-q1.dtb => Boot NOK
meson-sm1-x96-max-plus-q2.dtb => Boot NOK

I did all of this test with an USB 2.0 pendrive with 16GB of storage pluged in the USB3 port 
My USB 3.0 pendrive didn't work at all 

Does the oc in meson-sm1-x96-max-plus-oc.dtb meens overclocked ? 
I checked freq in the armbian-config and it was as usual at 2.1ghz

**Comment by delta-whiplash** [comment]
I installed on emmc with the    
s905x3     X96-Max+(OverClock)            meson-sm1-x96-max-plus-oc.dtb

But now I have a black screen when I try to boot please help me
I can't boot again on my pendrive please help me

**Comment by ophub** [comment]
Choose the normal option without -oc

**Comment by delta-whiplash** [comment]
I can't do it anymore I don't have any sort of splash screen When I try to boot from my USB pendrive It's doing some sort of bootloop

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

12.13

**Comment by delta-whiplash** [comment]
Ok what I have to do with this ?

**Comment by ophub** [comment]
Now the system cannot be started, you need to restore the Android system first, then reinstall armbian, and test which Armbian system is suitable for you.

**Comment by yaleh** [comment]
> I installed on emmc with the s905x3 X96-Max+(OverClock) meson-sm1-x96-max-plus-oc.dtb
> 
> But now I have a black screen when I try to boot I can't boot again on my pendrive please help me

I got just the same problem yesterday. And this box is hard to flash. I have to short a pin with ground and then flash it.

There's also a issue with u-boot: there's no hdmi output until about 4s after Linux kernel was loaded. So, I can see no output from u-boot when it's restarting in loop.

**Comment by yaleh** [comment]
The DTB I'm using now is: meson-sm1-x96-max-plus-q2.dtb. Both gigabit ethernet and wifi works now. I just failed to install armbian to emmc.

**Comment by ophub** [comment]
What does the error log that cannot be installed indicate?

**Comment by yaleh** [comment]
There's no problem during the execution of armbian-install. It just failed to boot after the installation. The HDMI is blank and the box is looping in rebooting (since the monitor shows NO SIGNAL and a blank screen with signal with a cycle of about ten seconds).

**Comment by ophub** [comment]
Restore to the Android system first, do not add any parameters when installing, use the default command armbian-install, do not install the mainline u-boot

**Comment by yaleh** [comment]
It's already restored, which is quite tricky (https://forum.androidbg.com/showthread.php?tid=98880). :)

I didn't use any parameter when calling armbian-install. And armbian-install is expected to install Android bootload when called without the "-m" paramter. Am I right?

According to https://4pda.to/forum/index.php?showtopic=1013103&st=40#entry102780026, my box is [X96 Max Plus2](https://4pda.to/forum/index.php?showtopic=1002233) with RTL8211F and RTL8822CS (confirm when booting from TF). X96 Max is well-known for the huge numbers of modifications and tricky booting process. Will it be helpful to dump the original bootloader? Which sectors should I dump?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/acee19bdbe3ba5e8e21a32d17f9fd4c9d34216fc/build-armbian/armbian-files/common-files/etc/model_database.conf#L103

RTL8211F should be `armbian-install` select `502`: `meson-sm1-x96-max-plus.dtb`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

Q2 is qca9377 wifi and Bluetooth

**Comment by yaleh** [comment]
Cool. I will try it and see whether it will help HDMI output of u-boot.

BTW: meson-sm1-x96-max-plus-q2.dtb works well with RTL8211F and RTL8822CS. :)
