### ISSUE TITLE
VontarX3(s905x3, Gigabit Ethernet) Support writing emmc to use

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#1006]
Standard chat template, no routine, no chat.
**Device Information |
 - SOC: [S905x3]
 - Model [Vontar X3, RAM 4GB, EMMC 128GB]

**Armbian Version | 
 - Kernel Version: 6.1.9
 - Release: Bullseye
 - meson-sm1-hk1box-vontar-x3.dtb <- uEnv.txt

**Describe the bug |
Armbian-install completes but does not boot from EMMC.
reattaching the pendrive and reboot the device, it will boot from pendrive. 

Describe the problem in detail and attach screenshots if necessary.
- Flashed standard android Pie rom 
- Flashed USB pendrive
- Booted Armbian from USB 
- Ran armbian-install. No errors complete. Remove the pendrive, reboots. Device does not boot. 
Option 506 
Option EXT4

![afbeelding](https://user-images.githubusercontent.com/53115937/216656415-d9895fff-5b06-45b3-b424-3bf2a0316a5c.png)

![afbeelding](https://user-images.githubusercontent.com/53115937/216656732-d4b5ae40-b731-482e-987c-ff1735786320.png)

![afbeelding](https://user-images.githubusercontent.com/53115937/216657275-4f95dba9-1b13-4669-9442-16eb46140dd0.png)

**Comment by ophub** [comment]
What is the error log? Where did you stop?

You can change to 5.15 and try

**Comment by d5stick** [comment]
Can you help me out where to connect TX RX and ground? 
I have no error log, when booting the device, no output on HDMI when armbian is installed on the EMMC. 
It boots with USB, but not EMMC. 

Checking now with 5.15

![afbeelding](https://user-images.githubusercontent.com/53115937/216759421-df7099bd-40d7-4579-8f03-00e7dae6a8f5.png)
![afbeelding](https://user-images.githubusercontent.com/53115937/216759432-241f4f6a-8f99-4aac-ad6f-6cb3308a0d80.png)
![afbeelding](https://user-images.githubusercontent.com/53115937/216759436-ab1eef46-7260-4524-9da0-88865cf0938f.png)

**Comment by ophub** [comment]
Is there a TTL-tag on the back of the motherboard?


Are `VONTAR X3` and `HK1 Box` the same device? Can you flash the Android system of HK1 on X3 and use it?

You are using the hk1 option, adapt to hk1, if this is not a device, but the android system is common, you can flash the android system on the x3 first, and then test to write armbian into emmc

**Comment by d5stick** [comment]
Kernel 5.15.90 had the same issue. 
The Vontar X3 and H1 are the same as i can tell from photo's, they use the same DTB you provided in the amlogic folder. 
I am downloading the ROM for the HK1 box to install.  Update shortly.

Also the picture of the back of the board:
![afbeelding](https://user-images.githubusercontent.com/53115937/216761870-8cb45e23-2fad-4222-8eb4-3d759ea5efc0.png)

**Comment by ophub** [comment]
There are 4 holes in the lower left corner of the picture on the back of the motherboard, corresponding to the V R T G on the front is the acronym of ttl

**Comment by d5stick** [comment]
Making progress!  
Flashed several HK1 roms, finally found one that works with this box. (u219.HK1_BOX_1000M_9.0.2020.11.16.11.05) 
Started Armbian on the USB pendrive, started the armbian-install on the box. 
Armbian booted!

**Comment by ophub** [comment]
Share your download link for this Android system, I will transfer it to:

https://github.com/ophub/kernel/releases/tag/tools

Please share a photo of the shell of your device. The model code can be clearly seen in the bottom photo, which is convenient for everyone to compare and use.

**Comment by d5stick** [comment]
Just installed kernel 6.1.9, which boots.

The IMG file i used: https://www.filefactory.com/file/5db9u9cc2ucc/u219.HK1_BOX_1000M_9.0.2020.11.16.11.05.img.7z
The burner including license files i used: https://github.com/d5stick/amlogic-s9xxx-armbian/tree/main/VontarX3Files

![afbeelding](https://user-images.githubusercontent.com/53115937/216766030-e3f80fdd-41ca-49f7-8871-869f0226ca91.png)
![afbeelding](https://user-images.githubusercontent.com/53115937/216766041-d7642ed3-9ad6-4fce-b926-bf64a4123230.png)

**Comment by ophub** [comment]
Thanks for sharing, I will add it to the device list and share a configuration with hk1.

**Comment by alealexpro100** [comment]
For some reason, system boots from emmc only after using `armbian-install -m yes -a no`.

**Comment by kalarepa623** [comment]
I have this tv box and I only have sound via hdmi.
SPDIF output does not work.
What should I do to make SPDIF work because I really want it.
Please help.
