### ISSUE TITLE
我家云l1pro启动报错

### ISSUE THREAD

**Issue by satanxts** [ophub/amlogic-s9xxx-armbian#1007]
设备 我家云l1pro

系统 Armbian_23.02.0_rockchip_l1pro_bullseye_6.1.8_server_2023.01.30.img

现象 启动时报错
1.[FAILED] Failed to listen on Network Service Netlink Socket.
2.[FAILED] Failed to start Raise network interfaces.

错误1通过查询日志得知前置启动项 “unit systemd-networkd.service is masked”，systemctl unmask systemd-networkd.service 之后问题解决

错误2日志如图
![image](https://user-images.githubusercontent.com/61779271/216684636-f3481bbb-cf17-45c5-bfcc-7ea8dac443df.png)

再次感谢大大提供的固件

**Comment by ophub** [comment]
这个设备的配置是我请教了f大后，使用他的u-boot制作的，但这个设备一直没有找到测试者。
你的错误是系统错误，至少说明固件重置的u-boot和kernel等方法是正确的。
网络连接超时，是不是没插好网线？
你可以换另外一个jammy或者5.15测试一下。

**Comment by satanxts** [comment]
我换6.1.9试试哈

**Comment by Yxini** [comment]
同款设备，现在用的是6.1.9的jammy，启动正常。

**Comment by satanxts** [comment]
6.1.9这两个问题依然存在，不过不影响使用
1.systemd-networkd.service好像是新的网络管理系统，被人为禁用了，猜测一下是怕新旧同时工作冲突吧
2.应该是延时太短的问题，虽然报错但是不影响网络正常使用，把auto eth0 改成 allow-hotplug eth0报错就消失了

3.遇到一个新问题，在n1上 
系统Armbian_23.02.0_amlogic_s905d_bullseye_6.1.9_server_2023.02.03.img.gz
![image](https://user-images.githubusercontent.com/61779271/216806656-f8aeb65a-615f-4c4a-9ff4-b569d3b297f1.png)
以前的版本是否存在不太清楚，之前没有注意

**Comment by ophub** [comment]
我家云支持全部内核，你可以切换到5.15/5.10/5.4，哪个内核兼容性好用哪个。

这是使用 ttl 显示的调试信息。
ssh客户端使用不显示这些调试信息。

![Snip20230205_1](https://user-images.githubusercontent.com/68696949/216807041-8fc8dee3-0173-4ccd-8cf0-b8bd9eb51b24.png)

**Comment by aaa7260** [comment]
大佬，我家云刷了最新版的，连接屏幕没有输出，用wind大佬的omv固件有输出

**Comment by ophub** [comment]
发一个他的固件下载地址

**Comment by agustinchao** [comment]
> Try.. 6.1.9? https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_02.03.1021/Armbian_23.02.0_rockchip_l1pro_jammy_6.1.9_server_2023.02.03.img.gz

请问这固件如何下载？按上方鏈接显示file not found
