### ISSUE TITLE
Lack of storage on USB and no Desktop environment

### ISSUE THREAD

**Issue by StatixBolt** [ophub/amlogic-s9xxx-armbian#1008]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905x3]
 - Model [x10 Max]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.9]
 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

So, I cannot get this to install to emmc but I am able to boot into it from USB just fine, WiFi works, and that's what I mainly want. (Also its the only IMG file that has working WiFi for me)

File name: Armbian_23.02.0_amlogic_s905x3_jammy_6.1.9_server_2023.02.02.img.gz

However I have two issues,
The storage is limited on the USB drive, how can I fix this?

 Second, Is there a version with a desktop environment installed if so can i have a download link? And if not how can I install xfce?

Thanks in Advanced.

**Comment by d5stick** [comment]
You can install the desktop environment with command armbian-config or  armbian-software. 


Both ways will install a desktop environment.  If you do not want the Gnome interface perform the following:

```
Install desktop environment from Armbian-config
sudo apt-get remove --purge gnome* -y
sudo apt-get install xubuntu-desktop -y
sudo apt-get install xfce4 -y
sudo apt-get install xfce4-session xfce4-goodies -y

sudo nano /etc/lightdm/lightdm.conf

[Seat:*]
autologin-user=<username>
autologin-user-timeout=0

sudo nano /etc/X11/xorg.conf.d/02-Armbian-aml-s905-x3.conf
Section "OutputClass"
    Identifier "Amlogic"
    MatchDriver "meson"
    Driver "modesetting"
    Option "PrimaryGPU" "true"
EndSection
Section "Screen"
    Identifier "Default Screen"
    Device "Meson"
    Monitor "foo"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
    EndSubSection
EndSection

sudo apt-get -y install lightdm-gtk-greeter

sudo dpkg-reconfigure lightdm
```

**Comment by StatixBolt** [comment]
Thanks! but i figured it out in your fork!

**Comment by ophub** [comment]
To activate the remaining space of TF/SD/USB, please login in to armbian → input command:

`armbian-tf`

According to the prompt, enter `e` to expand the remaining space to the current system partition and file system, and enter `c` to create a new third partition.
