### ISSUE TITLE
求助，CM311-1a-YST U盘启动armbian系统，花屏后无显示，设备绿灯。

### ISSUE THREAD

**Issue by chengqdevil** [ophub/amlogic-s9xxx-armbian#1009]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: s905l3a
 - Model :CM311-1a-YST

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.91
 - Release: bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

安卓TV固件：android_tv_cm311-1a-yst_s905l3a.tar.xz
armbian系统镜像：Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.91_server_2023.02.02.img.gz
尝试过换U盘，尝试过修改uEnv.txt，将 FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb 修改为 FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb ，均是同样的现象：花屏后无显示，设备绿灯。
同样的U盘，N1可以进入armbian系统，并刷入emmc。

**Comment by ophub** [comment]
你的操作流程正确，没毛病。
你换jammy的5.15试一下，也是要改FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb

**Comment by chengqdevil** [comment]
问题解决了，只插U盘和网线，不插HDMI线，就可以进去系统了，最终刷入emmc。插着HDMI线，即使输入了emmc，也没办法进去系统。

**Comment by ophub** [comment]
这个盒子不支持hdmi显示，只能ssh连接管理。

**Comment by ysuolmai** [comment]
新版本和魔百盒有各种兼容性问题，最后一个能用的貌似是5.15.76，之后我测试过的全都有问题
