### ISSUE TITLE
U盘启动无法连接有线网络，EMM启动可以。

### ISSUE THREAD

**Issue by muxi01** [ophub/amlogic-s9xxx-armbian#1010]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3] s905l3a
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] 5.51.90
 - Release: [e.g. jammy] jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
系统安装到EMMC后，USB 和 有线网卡都可以使用。
在U盘中网卡不可用，EMMC和U盘使用相同的DTB

**Comment by ophub** [comment]
把固态硬盘当U盘用，直接写盘软件写上面

**Comment by muxi01** [comment]
这样操作，分区大小有问题，rootfs分区只有2.5G

**Comment by ophub** [comment]
armbian-tf
选e扩容

**Comment by muxi01** [comment]
谢谢

**Comment by muxi01** [comment]
系统启动后，必须要登陆后才会启动sshd服务吗？

**Comment by ophub** [comment]
自动启动

**Comment by muxi01** [comment]
我测试的结果是，登陆号ps -ef 看到sshd 是启动了的，再连就没有问题。
如果启动后直接连就异常，但是可以ping通

**Comment by muxi01** [comment]
需要把u-boot-e900v22c.bin 复制更名为什么？

**Comment by ophub** [comment]
在5.4/5.15内核的系统里是可选操作，默认没添加，如果不添加也正常使用，就不必复制；
在5.10/6.1里面是必须的，固件默认已经添加了，不必手工复制了。

**Comment by muxi01** [comment]
目前，不复制网卡不正常，之前emmc启动网卡也不正常，复制后就正常了。请问复制后的文件名是什么

**Comment by ophub** [comment]
你是什么盒子

**Comment by muxi01** [comment]
没有u-boot.ext 可以很确定系统是从 硬盘启动的，但是网卡异常。
有u-boot.ext 系统优是从emmc启动。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

查表格

u-boot-e900v22c.bin
