### ISSUE TITLE
提交主线未支持的设备的一些问题

### ISSUE THREAD

**Issue by 13584452567** [ophub/amlogic-s9xxx-armbian#1011]
如果我提交了主线未适配的设备，打包的时候是使用我上交的dtb嘛？
如果kernel主线支持了，但是又想用我自己提交的dtb该如何操作？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-files/platform-files/amlogic/bootfs/dtb/amlogic

无论是amlogic的这个dtb目录里面的文件，还是rockchip里面的dtb文件，打包时都会被内核那几个tar.gz包解压覆盖了。

这里存放了一份，目的仅仅为了方便大家查看有哪些文件，方便复制文件名改uEnv.txt

所以有新的dts要提交到 https://github.com/unifreq 的几个内核源码仓库里，这样才能在以后的版本里持续使用。

如果你非要用一个自己独有的dtb，也不向上游提交dts，那你可以fork仓库，在dtb目录里放一个不重名的dtb文件，自己改conf，打包，因为内核的tar.gz里面没有你的这个名字的文件，所以也不会给覆盖替换了。

**Comment by 13584452567** [comment]
十分感谢解答！

**Comment by 13584452567** [comment]
也就是说如果我上交了dts到unifreq的6.1.y仓库之后，6.2.y或者后续版本就会没有这个dts嘛？
如果我想让这个dts一直存在是否只能上交到linux的kernel仓库？或者上交到chewitt的仓库？

**Comment by ophub** [comment]
会有的，他在新的分支里会全部移动过来。

比如最近的6.1里，他把之前6.0的派生岀来的dts都添加了。

所以你添加到6.1里，之后的他在每个新内核仓库创建时会移植过来。

rockchip的一些设备如果当前只支持用6.x.y内核，你只提交到6.1.y即可。amlogic建议把5.4/5.10/5.15/6.1这4个都提交。

**Comment by 13584452567** [comment]
十分感谢解答！
