### ISSUE TITLE
armbian如何与CoreELEC共存

### ISSUE THREAD

**Issue by alanfans** [ophub/amlogic-s9xxx-armbian#1013]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095L3A]
 - Model [e.g. UNT403A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.91]
 - Release: [e.g. jammy]
 
**Describe the bug | 问题描述**
EMMC是armbian ，U盘刷armbian能从U盘启动，刷CoreELEC，无法从CoreELEC启动

**Comment by ophub** [comment]
不能，这2个系统不能同时使用。
盒子emmc是CoreELEC时Armbian无法启动。
盒子emmc是Armbian时CoreELEC无法启动。

emmc里必须是安卓系统，才能从U盘启动Armbian系统，不是安卓无法启动，因为Armbian的启动需要使用安卓的bootloader。

**Comment by alanfans** [comment]
大佬，我用LibreELEC-AMLGX.arm-10.95.0-box.img.gz + meson-g12a-s905l3a-e900v22c.dtb (Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.91_server_2023.02.02.img 这个镜像中来的)能运行了
EMMC依旧是Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.91_server_2023.02.02.img，U盘是LibreELEC

**Comment by ophub** [comment]
LibreELEC 可以，这个系统和armbian兼容，现在armbian里led屏的配置文件是从LibreELEC里找的。

**Comment by alanfans** [comment]
我过会再试openELEC和EmuELEC

**Comment by alanfans** [comment]
U盘刷 Lakka-AMLGX.aarch64-4.3-box.img.gz + meson-g12a-s905l3a-e900v22c.dtb能启动，但是我的三个鼠标都用不了，键盘能用

**Comment by ophub** [comment]
你会的真多，我没用过这个系统，GTK-PRO的SD卡带EmuELEC，我忘了保存这个系统了，SD卡都格式了。

**Comment by alanfans** [comment]
EmuELEC是由CoreELEC发展而来的，刚试了一下，不成功，发现一个HybridELEC 说可以共存，过会试一下

**Comment by alanfans** [comment]
HybridELEC写入不成功，包可能是得线刷包
又发现一个batocera，支持S905X 和 S905X3 但没说S905X2，奇怪，过会试一下
https://forum.batocera.org/d/6564-amlogic-s905x2-support/3
batocera是由recalbox发展而来，recalbox官网好像没说支持晶晨过会看一下

**Comment by alanfans** [comment]
retroarch也没发现说支持晶晨

**Comment by ophub** [comment]
你把晶晨压榨的瑟瑟发抖

**Comment by alanfans** [comment]
并不是，是中国人口基数大，运营商电视盒子量也大，用户比较多

**Comment by ophub** [comment]
知道可以这么玩的人少，电视盒子的各种玩法，得有像你这样会这么多系统的安装使用，并且愿意写博客、做视频等去教大家怎么用。

**Comment by alanfans** [comment]
我这只是换换文件，刷刷机，刷刷 U盘，高端玩法还得看大佬zanjie1999，郑姐，听说是个中学生，感叹现在长江后浪推前浪，前浪拍死在沙滩上，最主要还是得感谢像大佬这样的开源作者。

**Comment by 7Ji** [comment]
> HybridELEC写入不成功，包可能是得线刷包 又发现一个batocera，支持S905X 和 S905X3 但没说S905X2，奇怪，过会试一下 https://forum.batocera.org/d/6564-amlogic-s905x2-support/3 batocera是由recalbox发展而来，recalbox官网好像没说支持晶晨过会看一下

HybridELEC 这个名字下面我放了三个项目。
 - hybrid-1.0是给mibox3/3c的线刷镜像，里面带启动其他外部系统的脚本，启动非CE/EE系统没有问题；
 - hybrid-ng是给所有GXL到SC2之间的盒子用的写到U盘或者SD的镜像，和CE/EE用相同的启动逻辑所以共享启动兼容性，启动非CE/EE外部系统会有问题；
 - android-burning是单独给每个盒子适配的安卓+CE+EE线刷包，目前已经适配HK1Box，HK1 Rbox X4 和 R3300L。这个分支有专用的安卓下的重启工具：https://github.com/7Ji/HybridELEC_Rebooter ，也可以启动任意外置系统。

而且，不仅仅是三系统线刷，你想把更多主线的内核压到旁边也是可以的，关键的工具就是我去年写的ampart: https://github.com/7Ji/ampart 。 

这里面，两个线刷分支必然不能写到U盘或者SD，一个U盘/SD镜像也肯定不能线刷。项目里都有说明，每个发布也有说明。去年已经有人拿线刷刷U盘以后开issue，我都专门写明了。

另外CE/EE的启动脚本和**所有**其他主线内核项目都不兼容，这个老生常谈了，而且和部分设备本身也不兼容，比如N1。我在EE项目里和shanti讨论过是不是应该转向主线内核的启动脚本，讨论的最后是他不想放弃和CE的兼容性。这也是为什么我在EE里做的更新全都要向后兼容 https://github.com/EmuELEC/EmuELEC/commits?author=7Ji 。

启动CE/EE以后没法启动其他系统的问题，你用fw_setenv改下u-boot的bootcmd就行了。

以我个人的观点，用着GXL的盒子的，就不要跟着CE这艘船到船沉了，整个CE的支持都在往后挪，老盒子越来越难受。GXBB的支持前面年底在无后缀项目里扔掉了，GXL G12A G12B SM1的-ng项目在SC2 S2 T4的-ne成为宠儿以后被扔掉也是早晚的事。

**Comment by alanfans** [comment]
![3a76d71cd3d3f1321c0980874f21d62a](https://user-images.githubusercontent.com/8871739/217526830-46c3fd10-72c7-44b4-8b68-98d9798f2ff1.png)

**Comment by alanfans** [comment]
> > HybridELEC写入不成功，包可能是得线刷包 又发现一个batocera，支持S905X 和 S905X3 但没说S905X2，奇怪，过会试一下 https://forum.batocera.org/d/6564-amlogic-s905x2-support/3 batocera是由recalbox发展而来，recalbox官网好像没说支持晶晨过会看一下
> 
> HybridELEC 这个名字下面我放了三个项目。
> 
> * hybrid-1.0是给mibox3/3c的线刷镜像，里面带启动其他外部系统的脚本，启动非CE/EE系统没有问题；
> * hybrid-ng是给所有GXL到SC2之间的盒子用的写到U盘或者SD的镜像，和CE/EE用相同的启动逻辑所以共享启动兼容性，启动非CE/EE外部系统会有问题；
> * android-burning是单独给每个盒子适配的安卓+CE+EE线刷包，目前已经适配HK1Box，HK1 Rbox X4 和 R3300L。这个分支有专用的安卓下的重启工具：https://github.com/7Ji/HybridELEC_Rebooter ，也可以启动任意外置系统。
> 
> 而且，不仅仅是三系统线刷，你想把更多主线的内核压到旁边也是可以的，关键的工具就是我去年写的ampart: https://github.com/7Ji/ampart 。
> 
> 这里面，两个线刷分支必然不能写到U盘或者SD，一个U盘/SD镜像也肯定不能线刷。项目里都有说明，每个发布也有说明。去年已经有人拿线刷刷U盘以后开issue，我都专门写明了。
> 
> 另外CE/EE的启动脚本和**所有**其他主线内核项目都不兼容，这个老生常谈了，而且和部分设备本身也不兼容，比如N1。我在EE项目里和shanti讨论过是不是应该转向主线内核的启动脚本，讨论的最后是他不想放弃和CE的兼容性。这也是为什么我在EE里做的更新全都要向后兼容 https://github.com/EmuELEC/EmuELEC/commits?author=7Ji 。
> 
> 启动CE/EE以后没法启动其他系统的问题，你用fw_setenv改下u-boot的bootcmd就行了。
> 
> 以我个人的观点，用着GXL的盒子的，就不要跟着CE这艘船到船沉了，整个CE的支持都在往后挪，老盒子越来越难受。GXBB的支持前面年底在无后缀项目里扔掉了，GXL G12A G12B SM1的-ng项目在SC2 S2 T4的-ne成为宠儿以后被扔掉也是早晚的事。

非常感谢大佬，我试一下ng那个项目，我用一个ssd测试，非常快，之前用usb2.0慢成蜗牛。

**Comment by PaTTeeL** [comment]
> > HybridELEC写入不成功，包可能是得线刷包 又发现一个batocera，支持S905X 和 S905X3 但没说S905X2，奇怪，过会试一下 https://forum.batocera.org/d/6564-amlogic-s905x2-support/3 batocera是由recalbox发展而来，recalbox官网好像没说支持晶晨过会看一下
> 
> HybridELEC 这个名字下面我放了三个项目。
> 
> * hybrid-1.0是给mibox3/3c的线刷镜像，里面带启动其他外部系统的脚本，启动非CE/EE系统没有问题；
> * hybrid-ng是给所有GXL到SC2之间的盒子用的写到U盘或者SD的镜像，和CE/EE用相同的启动逻辑所以共享启动兼容性，启动非CE/EE外部系统会有问题；
> * android-burning是单独给每个盒子适配的安卓+CE+EE线刷包，目前已经适配HK1Box，HK1 Rbox X4 和 R3300L。这个分支有专用的安卓下的重启工具：https://github.com/7Ji/HybridELEC_Rebooter ，也可以启动任意外置系统。
> 
> 而且，不仅仅是三系统线刷，你想把更多主线的内核压到旁边也是可以的，关键的工具就是我去年写的ampart: https://github.com/7Ji/ampart 。
> 
> 这里面，两个线刷分支必然不能写到U盘或者SD，一个U盘/SD镜像也肯定不能线刷。项目里都有说明，每个发布也有说明。去年已经有人拿线刷刷U盘以后开issue，我都专门写明了。
> 
> 另外CE/EE的启动脚本和**所有**其他主线内核项目都不兼容，这个老生常谈了，而且和部分设备本身也不兼容，比如N1。我在EE项目里和shanti讨论过是不是应该转向主线内核的启动脚本，讨论的最后是他不想放弃和CE的兼容性。这也是为什么我在EE里做的更新全都要向后兼容 https://github.com/EmuELEC/EmuELEC/commits?author=7Ji 。
> 
> 启动CE/EE以后没法启动其他系统的问题，你用fw_setenv改下u-boot的bootcmd就行了。
> 
> 以我个人的观点，用着GXL的盒子的，就不要跟着CE这艘船到船沉了，整个CE的支持都在往后挪，老盒子越来越难受。GXBB的支持前面年底在无后缀项目里扔掉了，GXL G12A G12B SM1的-ng项目在SC2 S2 T4的-ne成为宠儿以后被扔掉也是早晚的事。

今天刚看到大佬的项目，现在手头两个盒子，gxl_p211_1g和gxlx2_p295_1g，都是高安(ADVCA)版本的，前者还能TTL并打开adb，后者adb和TTL都关了，请教一下能用hybrid-ng和android-burning吗？

**Comment by momokgb** [comment]
> 知道可以这么玩的人少，电视盒子的各种玩法，得有像你这样会这么多系统的安装使用，并且愿意写博客、做视频等去教大家怎么用。

致敬，致敬所有先驱者无私的奉献，家里送的那些盒子都放着吃灰呢

**Comment by CODPHISH** [comment]
不理解为什么一定要同时运行两套linux系统，armbian能干的coreelec也能干
