### ISSUE TITLE
本地更新内核报错，armbian-update

### ISSUE THREAD

**Issue by jjjyyyllll** [ophub/amlogic-s9xxx-armbian#1014]
5.15.91内核下载到本地 boot dtb header modules
运行armbian-update报错

[ STEPS ] Start downloading kernel...
[ INFO ] Use local kernel: [ 5.15.91 ]
[ INFO ] Move kernel files to temporary directory: [ /tmp/tmp.hZOA5dPJRJ ]
mv: cannot stat 'sha256sums': No such file or directory
[ ERROR ] Kernel file move failed, stop updating.

**Comment by d5stick** [comment]
- What kernel do you run now?
- Which device?
- How many space available on storage?
- Did you do an armbian-sync to have the latest scripts?

**Comment by ophub** [comment]
sha256sums 文件也下载下来放一起

**Comment by jjjyyyllll** [comment]
> armbian-sync

好的，感谢大佬

**Comment by jjjyyyllll** [comment]
> 一种办法是把 sha256sums 文件也下载下来放一起使用； 另一种办法是使用 armbian-sync 更新本地脚本至最新，这个验证文件我单独判断了，现在没有也可以。

好的，感谢大佬！
