### ISSUE TITLE
LED-Armbian - Failure to shutdown or reboot when enabled at boot

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#1015]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905x3
 - Model HK1

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.9
 - Release: Bullseye

**Describe the bug | 问题描述**
When the LED Display is enabled and the following code is executed it to have the led start at boot the Armbian will not shutdown when performing a second reboot or shutdown.  It stops random in the shutdown process, and seems to be waiting on something. It does not freeze the Armbian as i still see logs when disconnecting/connecting usb or network cables. 

Info from: https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/led_screen_display_control.md
```
# Execute the following command in the terminal to add the Armbian system
sed -i '/armbian-led/d' /etc/rc.local
sed -i '/exit 0/i\armbian-led 15' /etc/rc.local
```

I solved this to remove the 2 entries in /etc/rc,local that are created by above and manually add the entry in rc.local
 
```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

perl /usr/sbin/balethirq.pl
bash /etc/custom_service/start_service.sh
armbian-led 15
exit 0
```

Now i can reboot as much as i want and it is rebooting as it should. 
This is an FYI report that can be closed after taking note.

**Comment by fran6120** [comment]
Now on my HK1 X3 `reboot` works perfect, before the only way to reboot from the command line was `reboot -f`

**Comment by ophub** [comment]
These two sed commands are not to be copied and pasted into /etc/rc.local, they are executed in the terminal, and it will create the same result as you added manually.

The first is to delete the current one, and the second is to add a line before exit 0.

**Comment by d5stick** [comment]
When following is executed: 
```
# Execute the following command in the terminal to add the Armbian system
sed -i '/armbian-led/d' /etc/rc.local
sed -i '/exit 0/i\armbian-led 15' /etc/rc.local
```

This becomes the output of the rc.local:

```
#!/bin/sh -e
#
# rc.local
#
# This script is executed at the end of each multiuser runlevel.
armbian-led 15
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# By default this script does nothing.

perl /usr/sbin/balethirq.pl
bash /etc/custom_service/start_service.sh
armbian-led 15
exit 0
```

There is a double entry of the armbian-led 15. Causing the weird shutdown issue. 
When removing the first command from the file and reboot there is no issue. 

Executed commands: 
![afbeelding](https://user-images.githubusercontent.com/53115937/216812316-398d83e7-c41a-4721-a8f6-36a07478846d.png)

**Comment by ophub** [comment]
Copy the two lines of commands to the terminal and execute them separately. After executing the first line, execute the second line, and try again to see what the result is.

**Comment by d5stick** [comment]
Executed as single commands and checked the rc.local file in between: 
- This commando indeed removes the entry:    sed -i '/armbian-led/d' /etc/rc.local
- This command adds 2 entries: sed -i '/exit 0/i\armbian-led 15' /etc/rc.local

![afbeelding](https://user-images.githubusercontent.com/53115937/216814351-c7af664e-f8b5-4d2f-8b0b-17b9e6500c6b.png)

This has probably to do with the double value  "Exit 0" that is originally already in the document. 
![afbeelding](https://user-images.githubusercontent.com/53115937/216814391-f3f1e7a6-a940-41d5-a29a-a253ae94daf8.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/05dd48a0cd6f697c321c745ff5c87c250b00f46c

Thanks for your feedback, according to your screenshot, there are two `exit 0` texts in this `/etc/rc.local` file, so two `armbian-led 15` records were created, and I just corrected the document.
