### ISSUE TITLE
之前正常没有现在账密登不上？

### ISSUE THREAD

**Issue by grinxxoo** [ophub/amlogic-s9xxx-armbian#1016]
设备: mgv2000
系统:armbian 23.02.0,0-trunk bullseye tty1
错误:账号密码登录不上，默认未改，青龙面板及frp依然可以访问！

之前刷好系统进入配置好了重启几次 账号密码都是root 1234 默认未改，现在想连ssh提示密码错误，换几个客户端或连接键盘都是gin incorrect无法进入，我该重装吗？

**Comment by grinxxoo** [comment]
![IMG_20230205_124952.jpg](https://user-images.githubusercontent.com/59274108/216802675-cbbacb0b-e00a-4c80-b895-80af10da88be.jpg)

**Comment by ophub** [comment]
肯定改了，第一次启动时提示你必须修改密码，这个不改不让你下一步，想想你改什么了。

**Comment by grinxxoo** [comment]
> 肯定改了，第一次启动时提示你必须修改密码，这个不改不让你下一步，想想你改什么了。

可是我用的ssh客户端都登录不上呀  手机pc甚至sftp都记住密码的

**Comment by ophub** [comment]
root  1234
这对默认账号密码只能使用1次，初次启动系统就要求你必须修改，不能是1234，所以你不可能继续使用这个账号了。

**Comment by grinxxoo** [comment]
> root  1234
> 这对默认账号密码只能使用1次，初次启动系统就要求你必须修改，不能是1234，所以你不可能继续使用这个账号了。

能否保数据重装啊 常用密码试了个遍都不行？

**Comment by ophub** [comment]
u盘启动系统，挂载emmc里的系统到u盘，覆盖密码文件？
/etc/passwd和/etc/shadow

**Comment by xiaolei0125** [comment]
这个应该不是密码的问题，而是SSHD服务异常的问题，参考： #794

**Comment by zhuguoqing123** [comment]
> 这个应该不是密码的问题，而是SSHD服务异常的问题，参考： #794

  我和你一样的问题，也是默认1234密码，解决不了
