### ISSUE TITLE
E900V22C 6.1.3 更新到 6.1.9后不能启动

### ISSUE THREAD

**Issue by vip198926** [ophub/amlogic-s9xxx-armbian#1017]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model：E900V22C

**Armbian Version | 系统版本**
 - Kernel Version: Linux 6.1.3-flippy-81+ (armbian) 
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
6.1.3使用一切正常，用"armbian-update"更新6.1.9自动重启卡下面的界面。

![5ad001c4936f47d9ef7efe569b3fa586](https://user-images.githubusercontent.com/64185667/216809576-454d4ed9-2c53-4adb-be47-c13b3c1abb29.jpg)

[E900V22C/D](https://github.com/Calmact/e900v22c), https://github.com/ophub/amlogic-s9xxx-armbian/issues/517, https://github.com/ophub/amlogic-s9xxx-armbian/issues/732, [M411A](https://blog.csdn.net/fatiaozhang9527/article/details/126388479), https://github.com/ophub/amlogic-s9xxx-armbian/issues/970, [UNT413A](https://blog.csdn.net/fatiaozhang9527/article/details/122232733), https://github.com/ophub/amlogic-s9xxx-armbian/issues/741

**Comment by ophub** [comment]
魔百和建议你使用5.15内核吧。
下载5.15最新固件，在USB上设置好正常启动，然后使用`armbian-update -r`命令，将会把USB里的这个armbian的系统内核直接复制给emmc里的系统，这样不用重装了，直接替换好5.15内核后继续从emmc使用。

**Comment by vip198926** [comment]
应该早一点跟你请教，那样我就不用重装了，刚刚在各种方法尝试，mmcblk2p2已经不能挂载读取了，只能重装了。

**Comment by ophub** [comment]
在仓库的首页，内核更新，这个功能介绍里有[救援]方案介绍，`armbian-update`那个可选参数`-r`的说明。

**Comment by vip198926** [comment]
是的，已经看到了，因为不知道问题出在哪里，所以试了很多方法，结果只能重装。
不过又学到了新的东西，谢谢大佬！

**Comment by ophub** [comment]
这个救授功能是过年那几天新加的。为了解决重装系统的麻烦。

如果更新内核失败了造成emmc里的系统无法启动，咱就用个简单有效的方法给emmc里面的内核重新换一套。我想了想用U盘救授这种操作大家都能做到，也好理解，就这么加了一个救援功能。

为了满足更新后还想回退到之前用的内核，又加了一个自动备份到/ddbr/backup/目录的功能。备份文件不用的可以自己删了。

**Comment by vip198926** [comment]
可以用 armbian-update -r 替换一个USB里测试稳定的内核到emmc，也可以用ddbr恢复更新前备份的内核。
刚我重装好6.1.3后又把问题复现了一遍，出现了新的问题，mmcblk2p2不能挂载ddbr里的文件读取不了，armbian-update -r ，armbian-update -r -m yes 使用都报错。
![03d0d129c537d11c236adae241ed7b39](https://user-images.githubusercontent.com/64185667/216813639-821cd1ce-e214-4c32-afb2-1d11cadf872d.jpg)

**Comment by ophub** [comment]
日志里说明了：你的U盘空间不足，不能用armbian-ddbr命令和`armnian-update-r`命令，让你先使用armbian-tf命令把u盘的剩余空间扩容出来。

你扩容时要联网从armbian源服务器安装分区工具，结果你的网络不通无法安装，无法继续。

所以检查/设备网络，让你的盒子正带访问网络后再执行armbian-tf继续安装分区工具软件包。

**Comment by vip198926** [comment]
刚开始用的USB是4GB，出现上面的错误，之后换了32GB的，运行了armbian-sync>armbian-tf>armbian-update -r依然出现。
![7ff4068c7a213c0a991b4e3ba1abad9b](https://user-images.githubusercontent.com/64185667/216828608-66cea6ae-5c3b-4bbb-b347-ee81bb834a6b.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.16
给USB里的armbian做一个降低频率的dtb

**Comment by 392377870** [comment]
请问大神，有了个rk3399的dtb还要什么文件能提交给你适配机型？lean中源码已经有这机型的文件，能和你的armbian适配通用吗？


> 在仓库的首页，内核更新，这个功能介绍里有`[救援]`方案介绍，`armbian-update`那个可选参数`-r`的说明。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

添加新设备的方法在12.15里，文档最底下倒数第二个。

**Comment by ophub** [comment]
好的👌
