### ISSUE TITLE
新魔百盒M304A（2g+16g）无对应的DTB文件

### ISSUE THREAD

**Issue by elonelywolf** [ophub/amlogic-s9xxx-armbian#1018]
大佬，可否编译一下M304A（2g+16g）对应的DTB文件；机顶盒的dtb文件已提取并编译dts文件
[dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10610754/dtb.zip)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md
