### ISSUE TITLE
写入emmc后无法启动

### ISSUE THREAD

**Issue by 3136083906** [ophub/amlogic-s9xxx-armbian#102]
章鱼星球，经过两天的折腾后U盘终于能正常启动了，但是写入了EMMC之后无法启动，没有代码

**Comment by 3136083906** [comment]
> 章鱼星球，经过两天的折腾后U盘终于能正常启动了，但是写入了EMMC之后无法启动，没有代码

你的openwrt固件写入emmc后没问题正常启动，对了，op怎么安装openclash？我用文件传输安装失败

**Comment by ophub** [comment]
我没用过，但看到过这个插件的依赖挺多，你要找全了这些依赖，arm64的，上传到任意目录如/tmp/upload下，安装。
一般建议在编译时集成，你可以fork了自己添加需要的插件。到各个插件的仓库去看说明。
