### ISSUE TITLE
章鱼星球（FAKE）安装armbian5.15不能上网

### ISSUE THREAD

**Issue by picklefan** [ophub/amlogic-s9xxx-armbian#1020]
**Device Information | 设备信息**
 - SOC: s912
 - Model 黑色章鱼星球 AKA Octopus(FAKE)

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.91
 - Release: bullseye

**Describe the bug | 问题描述**
用的这个安装包 Armbian_23.02.0_amlogic_s912-m8s_bullseye_5.15.91_server_2023.02.05.img.gz 应该没用错吧。
无法联网所以只能拍照了。
![](https://raw.githubusercontent.com/picklefan/gh_img_store_for_my_own_use/main/photo_2023-02-06_01-09-44.jpg)

**Comment by ophub** [comment]
章鱼星球有2种，一种是原版的，一种是山寨的，从外壳看一模一样，得拆机看，山寨的比原版的主板少一圈，没散热片,TTL线序和原版的也不一样。写入emmc时要选择正确的。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/d0094501e0f4e6acd3005cc34df2a9198d93e95c/build-armbian/armbian-files/common-files/etc/model_database.conf#L56-L57



![201621lzb9i3zeqooti20x](https://user-images.githubusercontent.com/68696949/216861368-5f107f4d-50d3-4b68-92f0-cd36bccc0086.jpeg)

![201620ejd7a5bdqbka5a75](https://user-images.githubusercontent.com/68696949/216861386-21e79fc9-2997-44d5-a361-6731e6720764.jpeg)

**Comment by picklefan** [comment]
我的是山寨，我以前拆过。跟写进EMMC没关系，不写进去也上不了网，我现在想办法把日志导出来，稍等。
还有我固件没刷错把，我刷的s912-m8s，还有个固件是s912，我的是8核，应该是m8s吧

**Comment by ophub** [comment]
s912就是章鱼的默认固件，你刷m8s就错了

**Comment by picklefan** [comment]
这样阿，原来是我刷错了。我重新刷个固件看看。

**Comment by picklefan** [comment]
果然是用错镜像了。感谢这位老哥对这个repo的维护，提个issue秒回还回复特别认真👍

**Comment by lidaxuan12** [comment]
山寨版本刷那个固件？

**Comment by SilverXIV-14** [comment]
> 山寨版本刷那个固件？

山寨有个专门的版本，特别标注了是Octopus-FAKE的，写入的时候选择这个写入就好了

**Comment by gzlail** [comment]
> > 山寨版本刷固件？
> 
> 山寨有专门的版本，特别标注的是Octopus-FAKE的，书写的时候选择这个书写就好了
翻遍了Releases里面的，有T1的，有M8S的，有T95z的，就是没有Octopus的。请问移除了还是我找的地方不对，还是要自己编译？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

首页，表格下面有绿色✅，显著标明了model表，方便对照查找设备和对应的镜像名称，章鱼叫s912

**Comment by gzlail** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf
> 
> 首页，表格下面有绿色✅，显著标明了model表，方便对照查找设备和对应的镜像名称，章鱼叫s912

感谢您的回复，已经搞定了，盒子原来就有一个安卓，安装02.Reboot to LibreELEC.apk以后，用它重启系统就可以从TF卡启动了，用的最新Armbian_26.08.0_amlogic_s912_trixie_6.18.41_server_2026.08.01，然后安装到eemmc。目前ssh登录都正常，就是ttl目前只能接收，敲键盘没反应，还在排查中。
