### ISSUE TITLE
章鱼星球（盗版）刷6.19内核无法启动，可能是内核不支持了

### ISSUE THREAD

**Issue by picklefan** [ophub/amlogic-s9xxx-armbian#1021]
**Device Information | 设备信息**
 - SOC: s912
 - Model: 盗版章鱼星球

**Armbian Version | 系统版本**
 - Kernel Version: 6.19
 - Release: jammy&&bullseye

**Describe the bug | 问题描述**

插入U盘后无限重启,循环播放以下报告
```
Net: eth0: ethernet@c9410000
starting USB...
Bus usb@c9000000: dwc3_meson_gxl_get_phys: usb2 ports:3
Register 300140 NbrPorts3
Starting the controller
USB XHCI 1.00
scanning bus usb@c9000000 for devices... XHCI timeout on event type 33... cannot recover.
BUG at drivers/usb/host/xhci-ring.c:481/xhci_wait_for_event()!
BUG!
resetting ...
```
看不懂什么意思，好像是USB驱动有问题。我的bootloader是你的5.15内核armbian的bootloader
有空的话麻烦帮看一下，还有没有救，大概要去哪里设置，我可以自己编译来测试。
谢谢！

**Comment by ophub** [comment]
每个固件里都有bootloader ，你说的用5.15的是哪个？你是怎么操作使用的？

**Comment by picklefan** [comment]
我现在用的这个包Armbian_23.02.0_amlogic_s912_bullseye_5.15.91_server_2023.02.05.img.gz。在你的release里面
我把这个包刷进u盘，U盘启动之后刷进EMMC，选的202。之后可以在EMMC和盘正常启动。
我又刷了个Armbian_23.02.0_amlogic_s905_bullseye_6.1.9_server_2023.02.05.img.gz进U盘，然后一插进去通电就出现以上报告，一直重复，进不去6.1.9的系统。

目前5.15.91在U盘上正常使用。

按你这么说，是6.1只适配了，正版章鱼星球，盗版的还没适配吗？  

我只是报告一下，5.15也能用，不是说非要6.1

**Comment by ophub** [comment]
正版的章鱼星球和N1一样，很多用户使用，磨合的很稳定了。
你是第二个山寨版用户，现在用的那个bootloader就是1年前那个买到山寨盒子的用户，在网上查阅大量资料，做了很多次组合测试，得出的结果。详见：https://github.com/ophub/amlogic-s9xxx-armbian/issues/253
