### ISSUE TITLE
请问哪个版本的系统支持N1盒子的视频硬解码

### ISSUE THREAD

**Issue by koolwiki** [ophub/amlogic-s9xxx-armbian#1024]
想请问这些版本是否支持N1盒子的视频硬解码功能？想把N1当做轻量级上网视频电脑使用，之前安装过的其他版本不支持硬解码，3D加速也不大成熟。想试试你开发的系统，不知道是否支持？非常感谢！

**Comment by ophub** [comment]
不支持，没有GPU驱动。我看到有人在ROCK5B上做努力，以后可能在5B上可能可以用上硬解。

**Comment by koolwiki** [comment]
> 不支持，没有GPU驱动。我看到有人在ROCK5B上做努力，以后可能在5B上可能可以用上硬解。N1用服务器版挺稳定，但装桌面版就不一定流畅了。
> 
> 安卓系统可以，看视频为主用安卓装app也多。

谢谢你这么快就回复。有一个问题一直不大懂，还想再请教一下你。像安卓和CoreELEC也是基于linux的，为什么这些系统可以支持？是因为他们用的闭源驱动吗？非常感谢！

**Comment by ophub** [comment]
amlogic芯片的服务对象主要是安卓电视盒子，所以厂家向安卓系统提交了驱动和开发文档。但armbian使用的是主线内核，和安卓不同。安卓从主要线分支后做了较大改动，可以认为已经不是一个内核了。

主线内核缺驱动，而且amlogic走闭源路线，锁bootloader，所以支持很费劲，而且盒子市场太乱了，同名不同芯，在俄语社区里有一个贴子介绍了一个x96max有10几个不同芯片，型号和名称完全相同，但配置这么多。国内运营商送的魔百和也这样，相同的名字但却五花八门。这也是为什么问题区里前一个人说他的盒子运行良好，后一个人说无法启动。这也是之前很多armbian的开发者放弃支持amlogic的原因，他们评论这会耗尽开发者的热情，天天回答重复的问题，占用了比开发更多的时间，而且即便支持了用户又很分散，每个盒子的用户群都很少，所以大佬们都删库不干了，受不了这种折磨。

**Comment by koolwiki** [comment]
> amlogic芯片的服务对象主要是安卓电视盒子，所以厂家向安卓系统提交了驱动和开发文档，CoreELEC是安卓系统，所以可以驱动使用。但armbian使用的是主线内核，和安卓不同。安卓从主要线分支后做了较大改动，可以认为已经不是一个内核了。
> 
> 主线内核缺驱动，而且amlogic走闭源路线，锁bootloader，所以支持很费劲，而且盒子市场太乱了，同名不同芯，在俄语社区里有一个贴子介绍了一个x96max有10几个不同芯片，型号和名称完全相同，但配置这么多。国内运营商送的魔百和也这样，相同的名字但却五花八门。这也是为什么问题区里前一个人说他的盒子运行良好，后一个人说无法启动。这也是之前很多armbian的开发者放弃支持amlogic的原因，他们评论这会耗尽开发者的热情，天天回答重复的问题，占用了比开发更多的时间，而且即便支持了用户又很分散，每个盒子的用户群都很少，所以大佬们都删库不干了，受不了这种折磨。

感谢回复！

**Comment by a2112670147** [comment]
已经2026年了，这玩意的GPU能起来么😢😢😢
在互联网犄角旮旯似乎看到mainline内核，GPU加速，解码成功了，但是没有找到教程或者固件，大佬现在有什么办法嘛？感谢回复！

**Comment by wujianGit123** [comment]
Amlogic芯片不是有专门的视频硬件解码模块AVE-10么？看芯片手册有介绍，这块的驱动程序能集成到armbian上面么？

**Comment by a2112670147** [comment]
问题在于驱动和用户层之间的‘桥’断了

**Comment by wujianGit123** [comment]
> 问题在于驱动和用户层之间的‘桥’断了

不能开发适配么？

**Comment by a2112670147** [comment]
不知道）））






商参
***@***.***

shenjiu
