### ISSUE TITLE
删除无用网卡

### ISSUE THREAD

**Issue by alegoho** [ophub/amlogic-s9xxx-armbian#1026]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. Ugoos X3]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.91]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

root@armbian:~# nmcli device | grep -E "^[e].*|^[w].*|^[D].*|^[T].*" | awk '{printf "%-19s%-19s\n",$1,$2}'
DEVICE             TYPE               
eth1               ethernet           
eth0               ethernet           
wlan0              wifi 

盒子之前刷了OP，突然断网，WIFI进入查看，网卡没了，刷了N个版本还是这样，网卡可能坏了，我换了一个网卡芯片情况更坏，完全识别不了网卡！后来刷了ARMBIAN用，因为可以用无线，但无线速度百兆也达不到，所以买了一个USB的网卡，现在重新刷了ARMBIAN，刷入能启动，也能识别网卡，但每次重启都要扫一次坏的网卡，要扫1分42秒，太烦了，请问怎么把原来那个网卡（eth0）,在ARMBIAN上删除了？

**Comment by alegoho** [comment]
[微信图片_20230206205914](https://user-images.githubusercontent.com/37651329/216977740-4145614f-7dd7-4c52-8a1d-af04a7dbd575.jpg)

HDMI输出一直这样

**Comment by 7Ji** [comment]
找到你用的设备用的DTB，反编译为DTS，找到`ethernet@f*`节点，把其中的属性`status = "okay"` 改成 `status = "disabled"`，再重新编译起来
```
# 备份，可以跳过
cp 到你在用的DTB的路径 backup.dtb
# 反编译
dtc -I dtb -O dts 到你在用的DTB的路径 -o edit.dts
# 编辑，也可以用其他的编辑工具
vi edit.dts
# 重新打包
dtc edit.dts -o 到你在用的DTB的路径
```
这么做会完全禁用掉SoC上的MAC

也可以用DTBO，但是各人用的启动情况太乱了，不一定支持，就不写了

**Comment by alegoho** [comment]
> 

感谢回复，小白不太懂，这是要改完后重新编译刷机包吗？

**Comment by 7Ji** [comment]
[ugoos-x3-no-eth.dtb.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/10671001/ugoos-x3-no-eth.dtb.gz)
解压替换你在用的ugoos x3的DTB

**Comment by alegoho** [comment]
> [ugoos-x3-no-eth.dtb.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/10671001/ugoos-x3-no-eth.dtb.gz) 解压替换你在用的ugoos x3的DTB

感谢！将这个替换后原盒子的网卡就被屏蔽？可以直接用USB网卡？我今晚回去试试

**Comment by alegoho** [comment]
> [ugoos-x3-no-eth.dtb.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/10671001/ugoos-x3-no-eth.dtb.gz) 解压替换你在用的ugoos x3的DTB

感谢大佬，已经刷了，原来盒子上的网卡不见了！

**Comment by alegoho** [comment]
> [ugoos-x3-no-eth.dtb.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/10671001/ugoos-x3-no-eth.dtb.gz) 解压替换你在用的ugoos x3的DTB

大佬，有BUG！就是重启有时启动不了，有时启动了不能SSH

**Comment by 7Ji** [comment]
有日志吗？dmesg的日志发一下
你用的USB网卡的型号是什么？lsusb和lsusb -t的日志发一下
如果是螃蟹的2.5G网卡， 问题比较多，需要设置udev规则指定驱动才能稳定。

**Comment by alegoho** [comment]
> 

重启几次就有一次不行，大概是什么网络，AP失败，我忘记截图，现在重启了几次都没事，我是用8153B，F大推荐那个
