### ISSUE TITLE
新魔百盒 M304A 2g+16g 不挂载mmc

### ISSUE THREAD

**Issue by elonelywolf** [ophub/amlogic-s9xxx-armbian#1027]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model 新魔百盒 M304A

**Armbian Version | 系统版本**
 - Kernel Version: Linux 6.1.9-flippy-81+
 - Release: Armbian_23.02.0_amlogic_s905l2_bullseye_6.1.9_server_2023.02.05.img

**Describe the bug | 问题描述**
用u 盘启动armbian后，HDMI无显示，有线正常获取ip，SHH正常连接，kernel不挂载mmc！

root@armbian:/dev# lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    1   7.3G  0 disk
├─sda1   8:1    1   255M  0 part /boot
└─sda2   8:2    1   2.5G  0 part /
zram0  254:0    0 965.6M  0 disk [SWAP]
zram1  254:1    0    50M  0 disk /var/log

SOC: S905L3
eMMC：SCY snand E16GDH8D1ABE00
WiFiBluetooth：UNISOC UWE5621DS
DDR：Rayson RS512M16ZNDD-75DT
附主板芯片图片

![mainboard](https://user-images.githubusercontent.com/123385492/217021805-a6761bc2-f237-4c31-b2c0-545e5810c4ec.jpg)
![emmc](https://user-images.githubusercontent.com/123385492/217021855-9aad6172-44b3-4f49-90f0-e24ef83ef396.jpg)
![wifi](https://user-images.githubusercontent.com/123385492/217021925-b0e44255-1ce0-4663-abfc-1bef4cb589f2.jpg)

**Comment by ophub** [comment]
nand不支持写入使用，只能USB使用

**Comment by elonelywolf** [comment]
谢谢大佬，看来只能用usb了

**Comment by janko888** [comment]
刚改了一下，我南传版本的m304a可以写入了，可以试一下（附件dtb是6.1.x内核编译的）
![6E8 ~ HVH )U)P{Z $PM5JO](https://user-images.githubusercontent.com/103774532/220302478-9eac9d0c-0b62-4414-9b06-3d529215b470.png)
[meson-gxl-s905l3b-m302a.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10791876/meson-gxl-s905l3b-m302a.zip)

**Comment by elonelywolf** [comment]
谢谢大佬，终于可以摆脱u盘了

**Comment by hisong90** [comment]
> 刚改了一下，我南传版本的m304a可以写入了，可以试一下（附件dtb是6.1.x内核编译的） ![6E8 ~ HVH )U)P{Z $PM5JO](https://user-images.githubusercontent.com/103774532/220302478-9eac9d0c-0b62-4414-9b06-3d529215b470.png) [meson-gxl-s905l3b-m302a.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10791876/meson-gxl-s905l3b-m302a.zip)

可以用wifi吗？

**Comment by Maplestoryx** [comment]
不可以用wifi

**Comment by sun2378** [comment]
> 刚改了一下，我南传版本的m304a可以写入了，可以试一下（附件dtb是6.1.x内核编译的） ![6E8 ~ HVH )U)P{Z $PM5JO](https://user-images.githubusercontent.com/103774532/220302478-9eac9d0c-0b62-4414-9b06-3d529215b470.png) [meson-gxl-s905l3b-m302a.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10791876/meson-gxl-s905l3b-m302a.zip)

大佬，请问可以在6.12.*内核使用吗？我在6.12.*内核下替换了dtb文件发现不能启动，是否哪里需要做什么修改
