### ISSUE TITLE
model_database.conf信息有异常

### ISSUE THREAD

**Issue by alanfans** [ophub/amlogic-s9xxx-armbian#1028]
[[Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

82行，305 CM311-1a-YST/UNT403A FDTFILE 应该是e900v22c.dtb吧不应该是cm311.dtb

**Comment by ophub** [comment]
没错，专为cm311添加的
