### ISSUE TITLE
请问下关于A95XF3-Air盒子写入emmc错误的问题是否有更新

### ISSUE THREAD

**Issue by iDea2016su** [ophub/amlogic-s9xxx-armbian#103]
The same error is at the end of the picture below. So before we can find a way to solve the problem of emmc, you can only use it on the sd card.

When you have time, you can restore emmc to the original `Android` TV system, and then rewrite it to armbian.

_Originally posted by @ophub in https://github.com/ophub/amlogic-s9xxx-armbian/issues/68#issuecomment-1008789373_

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/d7aa63f9b03bb1fa8d11a680376b2177ec7005f3

This error is gone. But this error is just a hint and does not affect the result of writing.
Whether your box can be used in emmc mainly depends on whether u-boot supports it. You need to test it, first flash back to Android and then armbian, and report the results.
