### ISSUE TITLE
M302A如何才能正常输出HDMI信号？

### ISSUE THREAD

**Issue by shang-cheng** [ophub/amlogic-s9xxx-armbian#1031]
Device Information | 设备信息
mode:M302A
SOC:   S095l 3-B 
Model: M302A 

Armbian Version | 系统版本

Kernel Version:5.15.92 /  6.1.10
Release:  jammy 
Describe the bug | 问题描述

M302A如何才能正常输出HDMI信号？
M302A使用了，一下4个版本，没有HDMI输出，系统使用TTL安装都正常。
Armbian_23.02.0_amlogic_s905l2_jammy_5.15.92_server_2023.02.07.img.gz
Armbian_23.02.0_amlogic_s905l2_jammy_6.1.10_server_2023.02.07.img.gz
Armbian_23.02.0_amlogic_s905lb-r3300l_jammy_5.15.92_server_2023.02.07.img.gz 
Armbian_23.02.0_amlogic_s905lb-r3300l_jammy_6.1.10_server_2023.02.07.img.gz

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/pull/615

目前hdmi无显示。可以ssh连接访问。
