### ISSUE TITLE
出错 重启进入这个界面 minislmtv

### ISSUE THREAD

**Issue by Throokie** [ophub/amlogic-s9xxx-armbian#1032]
好像是5.15.7系列的版本，之前论坛随便找的
好像是debian分支的。

重启后就这样了，不知道是什么问题。
![QQ图片20230207225650](https://user-images.githubusercontent.com/58783886/217280765-53ec262b-f58e-42a3-b8bb-21c570812e9a.jpg)

**Comment by ophub** [comment]
下载最新版重刷

https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by Throokie** [comment]
是 cm311-1a YST 盒子，好的，我去试试
