### ISSUE TITLE
请问，m301a-ZN S905L2的包有吗

### ISSUE THREAD

**Issue by KangtingSir** [ophub/amlogic-s9xxx-armbian#1033]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095L2]
 - Model [e.g. 魔百盒m301a ZN代工]

**Describe the bug | 问题描述**
请问有魔百盒m301a-ZN代工，S905L2芯片的openwrt的包吗？
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
![IMG_20230201_204945](https://user-images.githubusercontent.com/48851791/217282108-5c82b972-5bd3-4509-b054-61718c577598.jpg)

![IMG_20230201_204920](https://user-images.githubusercontent.com/48851791/217282180-c9799dc8-cdfd-4a4a-bc58-064eda9681ff.jpg)

**Comment by CangWeiohh** [comment]
同求！！！！

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/02332adc8d7c2cdfb4a6d7e75928cbbc39dbe025/build-armbian/armbian-files/common-files/etc/model_database.conf#L31

下载s905x的5.15的固件试试
dtb使用：`meson-gxl-s905x-p212.dtb`

u-boot默认先不添加试试启动是否正常，网卡是否正常。u-boot可以选择下面的2个进行测试。
```
u-boot-s905x-s912.bin
u-boot-p212.bin
```

**Comment by KangtingSir** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/02332adc8d7c2cdfb4a6d7e75928cbbc39dbe025/build-armbian/armbian-files/common-files/etc/model_database.conf#L31
> 
> 下载`s905x`的`5.15`的固件试试 dtb使用：`meson-gxl-s905x-p212.dtb`
> 
> u-boot默认先不添加试试启动是否正常，网卡是否正常。u-boot可以选择下面的2个进行测试。
> 
> ```
> u-boot-s905x-s912.bin
> u-boot-p212.bin
> ```

好的，感谢！还有个问题需要请教，请问要什么步骤能够直接将固件刷到机顶盒上，而不是要插着U盘才能启动到openwrt呢？

**Comment by ophub** [comment]
仓库首页有写入emmc说明
