### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by Supded** [ophub/amlogic-s9xxx-armbian#1034]
No sound on x96 max plus 2101w, 
![изображение](https://user-images.githubusercontent.com/22551225/217287066-050339a8-1561-4260-98c9-d0a3628d3d22.png)
![изображение](https://user-images.githubusercontent.com/22551225/217287165-a718008d-f965-4fa4-9669-3ed1e7004e0a.png)
[   88.679220]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[   88.681838]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22
[  527.627956]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[  527.630713]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22
[  534.366648]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[  534.369356]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22

**Comment by Supded** [comment]
alsactl restore
alsa-lib parser.c:2783:(load_toplevel_config) Unable to find the top-level configuration file '/usr/share/alsa/ucm2/ucm.conf'.
alsa-lib main.c:1541:(snd_use_case_mgr_open) error: failed to import hw:0 use case configuration -2

**Comment by 7Ji** [comment]
Maybe the same issue as https://github.com/ophub/amlogic-s9xxx-armbian/issues/1000 under the hood?

**Comment by Supded** [comment]
> Maybe the same issue as #1000 under the hood?

I need to extract g12_sound.sh from package and run?
Already tried this https://github.com/chewitt/LibreELEC.tv/blob/amlogic/packages/audio/alsa-utils/scripts/soundconfig

**Comment by 7Ji** [comment]
> > Maybe the same issue as #1000 under the hood?
> 
> I need to extract g12_sound.sh from package and run? Already tried this https://github.com/chewitt/LibreELEC.tv/blob/amlogic/packages/audio/alsa-utils/scripts/soundconfig

That one in chwitt's LE repp is different from the one in ManjaroARM repo. The LE one is only gonna work on LE itself.

**Comment by Supded** [comment]
https://gitlab.manjaro.org/manjaro-arm/packages/community/khadas-utils/-/blob/master/g12_sound.sh
It works! Comment # Amlogic G12 HDMI to PCM0 - NEW CONF and uncomment # Amlogic G12 HDMI to PCM0 - OLD CONF
![изображение](https://user-images.githubusercontent.com/22551225/217555776-290921f8-26fb-4adc-a257-64d906534051.png)
![изображение](https://user-images.githubusercontent.com/22551225/217555867-95c751c0-c834-427a-82b9-96d859d9eab8.png)

**Comment by Supded** [comment]
Another question, how to get hw decoding in kodi?

**Comment by 7Ji** [comment]
That's something only chewitt from LibreELEC could answer correctly. LE is the only choice if you want out-of-box hw-decoding Kodi running on mainline kernel.

Also, this is getting out-of-topic. If you want to discuss this, at least close the current issue and re-open one.
