### ISSUE TITLE
求一份支持M302A-ZN-S905L2-B的Armbian

### ISSUE THREAD

**Issue by CangWeiohh** [ophub/amlogic-s9xxx-armbian#1037]
**Device Information | 设备信息**
 - SOC: S905L 2-B
 - Model: 河南移动新魔百和M302A-ZN(兆能代工)

**Describe the bug | 问题描述**
盒子自带WiFi蓝牙模块，求一个能刷Armbian的方法
网上找到刷安卓固件的博客
链接：https://blog.csdn.net/fatiaozhang9527/article/details/126967746
固件链接：https://pan.baidu.com/s/1AS03VBGSHfWxYjPiqRtVvg  提取码：1111

不清楚S905L 2-B和哪个芯片更接近，看到有人发固件包的时候在L2后面加了/B
链接：https://www.znds.com/tv-1185197-1-1.html
<img width="804" alt="image" src="https://user-images.githubusercontent.com/96470348/217479323-e1cee308-fc5d-4a3a-9fde-20b46bc4a85f.png">
![image](https://user-images.githubusercontent.com/96470348/217471521-709c6657-149e-41c2-92c7-1c577deb49f4.png)
![image](https://user-images.githubusercontent.com/96470348/217471591-7cc90884-f53a-40e1-bf1b-034aa1a2e134.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/02332adc8d7c2cdfb4a6d7e75928cbbc39dbe025/build-armbian/armbian-files/common-files/etc/model_database.conf#L31

下载`s905x`的`5.15`的固件试试
dtb使用：`meson-gxl-s905x-p212.dtb`

u-boot默认先不添加试试启动是否正常，网卡是否正常。u-boot可以选择下面的2个进行测试。
```
u-boot-s905x-s912.bin
u-boot-p212.bin
```

**Comment by CangWeiohh** [comment]
非常感谢您！！我试试




cangweiohh
***@***.***







                       
原始邮件
                       
                     

发件人："ophub"< ***@***.*** &gt;;

发件时间：2023/2/10 11:18

收件人："ophub/amlogic-s9xxx-armbian"< ***@***.*** &gt;;

抄送人："CangWei"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [ophub/amlogic-s9xxx-armbian] 求一份支持M302A-ZN-S905L2-B的Armbian (Issue #1037)




 
https://github.com/ophub/amlogic-s9xxx-armbian/blob/02332adc8d7c2cdfb4a6d7e75928cbbc39dbe025/build-armbian/armbian-files/common-files/etc/model_database.conf#L31
 
下载s905x的5.15的固件试试
 dtb使用：meson-gxl-s905x-p212.dtb
 
u-boot默认先不添加试试启动是否正常，网卡是否正常。u-boot可以选择下面的2个进行测试。
 u-boot-s905x-s912.bin u-boot-p212.bin  
&mdash;
