### ISSUE TITLE
添加GT king2的支持

### ISSUE THREAD

**Issue by fc777888** [ophub/amlogic-s9xxx-armbian#1038]
大佬你好 去年年底就出了gt king2 。大老师都有支持这款最新盒子的打算呢

**Comment by 7Ji** [comment]
主线内核不支持SC2（S905X4）以后所有的晶晨SoC，遑论S4 (S905Y4, S905W2) 和 T7 (A311D2)。GT King2用的就是A311D2。只有各厂家的BSP内核（比如Khadas给它家VIM4用的）以及CE的魔改内核才能支持这个SoC。哪怕恰赞助的Armbian官方（不是这个项目），对于Khadas VIM4的用BSP内核的支持状态也就是WIP。也许你可以从CE的5.4魔改内核入手尝试自己打包Armbian，他们有赞助，而且有Beelink给的源码，所以有GT king2的设备树。
