### ISSUE TITLE
It is possible to get hw decoding in kodi?

### ISSUE THREAD

**Issue by Supded** [ophub/amlogic-s9xxx-armbian#1039]
Kodi uses sw decoding by default, it is very laggy on x96 max plus.

**Comment by ophub** [comment]
Kodi is `Android`

**Comment by Supded** [comment]
> Kodi is `Android`

No, kodi is a program, not an os, like libreelec. https://packages.debian.org/en/bullseye/kodi

**Comment by ophub** [comment]
https://kodi.tv/

Kodi is not this?

**Comment by Supded** [comment]
This, of course.

**Comment by ophub** [comment]
Armian's hardware decoding video is not supported, and the gpu is not driven. I see rock5b trying hard.

**Comment by Supded** [comment]
GPU works fine, I use sid repo, firefox layers acceleration and webrender is on. There is lack of api for video decoding on VPU, like vaapi.

**Comment by Supded** [comment]
hw decoding works in le chroot!
