### ISSUE TITLE
N1 刷入后 无反应

### ISSUE THREAD

**Issue by Kevin-ox** [ophub/amlogic-s9xxx-armbian#1040]
您好！用 balenaEtcher刷入Armbian_23.02.0_amlogic_s905l2_bullseye_5.15.92_server_2023.02.07.img.gz后插入N1靠近HDMI的USB口后通电引导启动，显示器一直处于休眠状态。写入镜像后需要做什么修改吗

**Comment by ophub** [comment]
下`s905d`的固件
你刷错系统了。

**Comment by Kevin-ox** [comment]
sorry,我复制错了,我下载的就是Armbian_23.02.0_amlogic_s905d_bullseye_5.15.92_server_2023.02.07.img.gz

**Comment by Kevin-ox** [comment]
等了好久，半个小时了，现在还是一样的状态，不进原系统，也不进u盘系统

**Comment by ophub** [comment]
解压后再刷入，N1挑U盘，不行换一个U盘，使用[Rufus](https://rufus.ie/)刷U盘。

**Comment by Kevin-ox** [comment]
好的，我换Rufus试一下，我这个u盘刷Armbian_20.10_Arm-64_bullseye_current_5.9.0.img是正常的，我想换你这个试试

**Comment by ophub** [comment]
下载的是s905d，默认不用改就可以直接使用，注意看名字，还有个s905d-ki这个不是N1的

**Comment by Kevin-ox** [comment]
我下载的是 bullseye 不是 jammy，bullseye 要修改吗

**Comment by ophub** [comment]
都不用，使用方法一样

**Comment by Kevin-ox** [comment]
好的，我换Rufus试一下

**Comment by Kevin-ox** [comment]
用Rufus刷入也不行，表现就是 通电之后显示器被激活了，然后黑屏，然后又休眠了

**Comment by Kevin-ox** [comment]
是跟我我没插网线有关系吗？

**Comment by ophub** [comment]
不插网线只是启动时会卡住5分钟等网络，但hdmi接的显示器里有跑码。你换几个U盘试。

**Comment by Kevin-ox** [comment]
我换jammy试试

**Comment by Kevin-ox** [comment]
换了个u盘也不行

**Comment by Kevin-ox** [comment]
我用我找的一个旧版就没问题T_T

**Comment by Kevin-ox** [comment]
这样没问题吧
![uTools_1675921861519](https://user-images.githubusercontent.com/42051500/217731939-aab0ed6a-fa6c-478c-bb54-eb2a8dc62048.png)

**Comment by Kevin-ox** [comment]
我的显示器是4K的应该也没影响是吧

**Comment by ophub** [comment]
解压成img再使用Rufus刷

**Comment by lovemay3** [comment]
重刷安卓系统，然后
adb connect 斐讯 IP
adb shell reboot update
可解这个问题

**Comment by JerryWn12** [comment]
之前我也遇到了 4k 显示器无 HDMI 输出的问题，你试试 5.10 内核，或者用 SSH 登录
