### ISSUE TITLE
求一份魔百盒M401a 2G+16G 内核为5.9.0版本的armbian镜像文件

### ISSUE THREAD

**Issue by JustinTangChina** [ophub/amlogic-s9xxx-armbian#1041]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905l3a]
 - Model [e.g. M401a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.9.0]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

现在5.15内核版本的没有支持RTL8822CS 模块的驱动，可以帮忙弄一个5.9.0内核版本的镜像文件吗？我是新手不懂更换内核编译
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs

5.15也有8822cs驱动，但有人能用有人不能用。
5.9的上网搜，两年前的150b发布的最后版就是5.9，我没有这个内核。

**Comment by JustinTangChina** [comment]
试了 ophub老大提供的地址的驱动，编译的时候提示错误，那个驱动的内核貌似提示需要ubuntu 14的环境才能编译，我是在老大最新版的系统下编译失败，提示 当前系统内核为debian 10.2  所以编译失败，   如果我需要使用这个驱动，可以在ubuntu 14下编译好，再到armbin 23.2下面去安装？  这个应该怎么解决？
![481d307c464e6a8f](https://user-images.githubusercontent.com/117615710/218018453-c64f1e0b-11b2-4dfb-aa14-dacfad003294.jpg)
