### ISSUE TITLE
UNT413A刷入报错

### ISSUE THREAD

**Issue by LioDon** [ophub/amlogic-s9xxx-armbian#1042]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905L3A]
 - Model [e.g. UNT413A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

配置为S905L3A，2G+8G
U盘可引导，但在刷入Emmc的过程中报错，具体情况如图所示：

![微信图片_20230209121729](https://user-images.githubusercontent.com/52228201/217716689-3f2b8290-9c1d-4025-9f7b-706303256b35.jpg)

![微信图片_20230209121737](https://user-images.githubusercontent.com/52228201/217716722-37bc2c6a-5474-4bb6-9d89-aea1196744b2.jpg)

![微信图片_20230209121743](https://user-images.githubusercontent.com/52228201/217716731-140fd5fe-efd4-46b1-99e6-f4c42edc1689.jpg)

![微信图片_20230209122341](https://user-images.githubusercontent.com/52228201/217717455-2a49f7e8-feb4-448b-b25e-25e8c7c34990.jpg)

![微信图片_20230209122332](https://user-images.githubusercontent.com/52228201/217717475-04040fa8-42e0-4891-b37e-f8bd7c08aa9f.jpg)

![微信图片_20230209122345](https://user-images.githubusercontent.com/52228201/217717527-f956b60b-1041-4869-8b38-dd1ac7176a40.jpg)

![微信图片_20230209122328](https://user-images.githubusercontent.com/52228201/217717562-06426ea1-bb7c-4c6a-a8d8-dea2979f2021.jpg)

![微信图片_20230209122337](https://user-images.githubusercontent.com/52228201/217717582-eb904ce0-ee1b-4d35-bfa6-c94a07f7dbf3.jpg)

![微信图片_20230209122321](https://user-images.githubusercontent.com/52228201/217717503-3b26a6e8-8627-4ec0-9f9c-74a3bc133319.jpg)

**Comment by LioDon** [comment]
刷机命令为armbian-install时，最后报错为Failed write to bootloader using [dd]
刷机命令为nand-sata-install时，最后报错同上
刷机命令为armbian-install on 时，最后报错为Invalid option [no]

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

解决方法看12.16

仓库首页的说明里只有一个命令：`armbian-install`

其他命令适合其他固件，如果你是从哪里看到的贴子，就下载博主介绍的下载地址里面的固件，这样对应操作可行。但是这些方法不一定适合这里下载的最新固件，不看说明的操作可能有不确定的问题。

**Comment by LioDon** [comment]
哭了……小白看不懂说明…………完全不知道从哪下手……

**Comment by LioDon** [comment]
这是…要修改内核么……

**Comment by ophub** [comment]
哪句话看不懂，标一下，我看看怎么能写的更通俗易懂些，让你会操作了。

**Comment by LioDon** [comment]
可以直接写写具体对哪个路径下的哪个文件做修改之类的，也许就会了。

**Comment by LioDon** [comment]
大佬可以把我当成是只会复制粘贴的二傻子来对待………………

**Comment by ophub** [comment]
你在 `/boot/uEnv.txt` 里修改了UNT413A的dtb名字，例如
`FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb`

就是这个dtb，在这个路径里找到下载到本地，然后反编译，修改，覆盖源文件。

**Comment by LioDon** [comment]
好的，我试试，谢谢大佬~
（反编译也是第一次尝试，但愿能成功~~~）

**Comment by ysuolmai** [comment]
你要是成功了发一个dtb出来呀，我也有个413

**Comment by alegoho** [comment]
我也有一个413A，U盘启动后找不到网卡

**Comment by LioDon** [comment]
我找了程序员帮忙调试，刚才已经把速度调整为了1倍，目前看还是老样子，也不知道是不是还有其他地方的问题。晚些时候再试试其他参数。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/989

这个同学总结的好。


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.13，反编译就一条命令，1分钟的事，我看了看文档没有什么写的绕口的地方，你是哪里看不懂呢？我改文档。

**Comment by LioDon** [comment]
我不会编程…………

**Comment by ophub** [comment]
纯粹的复制粘贴，固定命令固定格式。

**Comment by LioDon** [comment]
不会是真不会，连怎么打开从哪下手都一头雾水……待会儿我那程序员朋友闲了让他多给我出几个版本，我挨个儿试试。

**Comment by ophub** [comment]
你U盘启动了，就去U盘中就可以反编译。你复制一个dtb，复制粘贴命令操作，包教包会：

**Comment by LioDon** [comment]
就是说，U盘里的系统登录之后，输代码就能直接改了呗？

**Comment by LioDon** [comment]
还是说是需要在Linux环境下操作？我倒是正在给一个老电脑装Ubuntu20.04.

**Comment by ophub** [comment]
# 安装依赖
sudo apt-get update
sudo apt-get install -y device-tree-compiler

# 进入某个目录，开始测试，比如进入~/
cd ~/
# 创建个目录进去玩，比如叫dtb_test
mkdir dtb_test
cd  dtb_test
# 把你用的dtb复制到当前目录下
cp -f /boot/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb .

# 反编译这个dtb获得dts文件（使用 dtb 文件生成 dts 源码）
dtc -I dtb -O dts -o meson-g12a-s905l3a-cm311.dts meson-g12a-s905l3a-cm311.dtb
# 反编译完得到的meson-g12a-s905l3a-cm311.dts可以拿文本编辑器打开，搜索关键字找到，改数值，改完保存。再反编译回dtb
dtc -I dts -O dtb -o meson-g12a-s905l3a-cm311.dtb.dtb meson-g12a-s905l3a-cm311.dtb.dts
# 把你编译好的文件覆盖回原路径
cp -f meson-g12a-s905l3a-cm311.dtb.dtb /boot/dtb/amlogic
# 保存，重启
sync && reboot

**Comment by LioDon** [comment]
我现在就试试

**Comment by LioDon** [comment]
![屏幕截图 2023-02-10 200942](https://user-images.githubusercontent.com/52228201/218089196-9de7690b-cfad-4c35-b1f2-e6b5d85bc7cc.png)
怎么感觉第一步就报错了……

**Comment by LioDon** [comment]
是不是我这盒子硬件上有啥问题……

**Comment by LioDon** [comment]
我继续试

**Comment by LioDon** [comment]
我哭了，都下降到0.1了，报错还是那个报错。Armbian的系统之前还真是被破坏了，目录下居然有个安卓的文件夹，重刷之后代码可以一步一步往下走，反编译都完成了。然而，我不解的是，还是老样子……我换个板子吧…………

另：上面的9条反编译操作的第6条的最后一行代码中，两个文件名是不是都多打了个“.dtb”，删掉之后代码正常运行了。

**Comment by LioDon** [comment]
实锤了，确实是板子的问题。同样都是UNT413A，前边说的那个是南传的，一直报错。
后来换了爱家TV的，可以刷了。
![微信图片_20230210233014](https://user-images.githubusercontent.com/52228201/218130755-c3c9af1a-6225-49fa-a889-e0faf6368148.jpg)
![微信图片_20230210233027](https://user-images.githubusercontent.com/52228201/218130787-9e046981-880f-4821-96d6-d994fd5ed94d.jpg)

另：附上我用的dtb文件（下载好之后删掉文件名后面的.md，网站不支持上传dtb格式文件），直接覆盖原文件即可。
[meson-g12a-s905l3a-cm311.dtb.md](https://github.com/ophub/amlogic-s9xxx-armbian/files/10708948/meson-g12a-s905l3a-cm311.dtb.md)

**Comment by LioDon** [comment]
接下来我要试试装上桌面了。

https://github.com/Scirese/alarm/blob/main/alarm.md
这个方案的实施需要在当前刷机成功的基础上才行，继续尝试。

另：感谢大佬的详细指导，感激涕零~~~

**Comment by ophub** [comment]
多写的.dtb已经更正了。

安装桌面：armbian-software 选项 201

**Comment by LioDon** [comment]
嗯嗯，凌晨鼓捣半天桌面装上了，感觉略卡，占用空间也上来了，是不是有部分类似安装包之类的东西还保留着，是不是可以清理？

慢慢地再试试Scirese的方案吧，不知道会不会流畅点儿。

对了，系统的显示分辨率目前最低仅能降到720P，有没什么方法可以进一步降低的？比如说我想让他能兼容老电视，分辨率就是720X576。

**Comment by ophub** [comment]
https://blog.51cto.com/u_15057807/4126233

**Comment by LioDon** [comment]
![屏幕截图 2023-02-11 191856](https://user-images.githubusercontent.com/52228201/218255200-f9dfb40c-bb2d-41b5-aaa1-8f6e0e96fea7.png)
指令不存在，是不是跟系统精简有关系？

**Comment by LioDon** [comment]
对了，还有个问题，无线网卡、蓝牙和声卡的驱动是不是需要单独配置？寻摸了一圈儿，网友们的方法试了试，没能成功……

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1044

添加无线和蓝牙大概就是这样操作，找到芯片，查看它的wifi和bluetooth代码，在对应的内核dts里添加，编译并测试，你自己有设备测试也方便。像这样今天一句明天一句的测试要好几天比较费时间。

**Comment by LioDon** [comment]
好的，我继续试试。声音也是一个道理么？

**Comment by LioDon** [comment]
找了一圈儿，uwe5621没驱动……？

**Comment by ysuolmai** [comment]
@ophub O大，我看了下新版的貌似代码不一样了，这下面三个是改mmc那个就行吗？


                sd@ffe03000 {
                        compatible = "amlogic,meson-axg-mmc";
                        reg = <0x00 0xffe03000 0x00 0x800>;
                        interrupts = <0x00 0xbd 0x04>;
                        status = "okay";
                        clocks = <0x02 0x21 0x02 0x3c 0x02 0x02>;
                        clock-names = "core\0clkin0\0clkin1";
                        resets = <0x05 0x2c>;
                        amlogic,dram-access-quirk;
                        pinctrl-0 = <0x32>;
                        pinctrl-1 = <0x33>;
                        pinctrl-names = "default\0clk-gate";
                        #address-cells = <0x01>;
                        #size-cells = <0x00>;
                        bus-width = <0x04>;
                        cap-sd-highspeed;
                        sd-uhs-sdr50;
                        max-frequency = <0x5f5e100>;
                        non-removable;
                        disable-wp;
                        keep-power-in-suspend;
                        mmc-pwrseq = <0x34>;
                        vmmc-supply = <0x35>;
                        vqmmc-supply = <0x36>;
                        phandle = <0x127>;

                        wifi@1 {
                                reg = <0x01>;
                                compatible = "sprd,unisoc-wifi";
                                phandle = <0x128>;
                        };
                };

                sd@ffe05000 {
                        compatible = "amlogic,meson-axg-mmc";
                        reg = <0x00 0xffe05000 0x00 0x800>;
                        interrupts = <0x00 0xbe 0x04>;
                        status = "okay";
                        clocks = <0x02 0x22 0x02 0x3d 0x02 0x02>;
                        clock-names = "core\0clkin0\0clkin1";
                        resets = <0x05 0x2d>;
                        pinctrl-0 = <0x37>;
                        pinctrl-1 = <0x38>;
                        pinctrl-names = "default\0clk-gate";
                        bus-width = <0x04>;
                        cap-sd-highspeed;
                        max-frequency = <0x2faf080>;
                        disable-wp;
                        cd-gpios = <0x39 0x2f 0x01>;
                        vmmc-supply = <0x35>;
                        vqmmc-supply = <0x35>;
                        phandle = <0x129>;
                };

                mmc@ffe07000 {
                        compatible = "amlogic,meson-axg-mmc";
                        reg = <0x00 0xffe07000 0x00 0x800>;
                        interrupts = <0x00 0xbf 0x04>;
                        status = "okay";
                        clocks = <0x02 0x23 0x02 0x3e 0x02 0x02>;
                        clock-names = "core\0clkin0\0clkin1";
                        resets = <0x05 0x2e>;
                        pinctrl-0 = <0x3a 0x3b 0x3c>;
                        pinctrl-1 = <0x3d>;
                        pinctrl-names = "default\0clk-gate";
                        bus-width = <0x08>;
                        cap-mmc-highspeed;
                        mmc-ddr-1_8v;
                        mmc-hs200-1_8v;
                        max-frequency = <0x17d7840>;
                        non-removable;
                        disable-wp;
                        mmc-pwrseq = <0x3e>;
                        vmmc-supply = <0x3f>;
                        vqmmc-supply = <0x40>;
                        phandle = <0x12a>;
                };

**Comment by ophub** [comment]
sd_emmc_a
sd_emmc_b
sd_emmc_c

分别对应3个

**Comment by lh2513** [comment]
我也有4个UNT401A盒子，只有一个能刷入emmc并且启动，其他三个刷入emmc都报错

Error: Input/output error during write on /dev/mmcblk2
Error: /dev/mmcblk2: unrecognised disk label
Error: /dev/mmcblk2: unrecognised disk label
[ ERROR ] Failed to create partition using [ parted ].

**Comment by LioDon** [comment]
> 我也有4个UNT401A盒子，只有一个能刷入emmc并且启动，其他三个刷入emmc都报错
> 
> Error: Input/output error during write on /dev/mmcblk2 Error: /dev/mmcblk2: unrecognised disk label Error: /dev/mmcblk2: unrecognised disk label [ ERROR ] Failed to create partition using [ parted ].

你看看报错的那仨的版本以及板子上内存和EMMc的信息，估计个别版本设计上有差异。

**Comment by LioDon** [comment]
https://www.bilibili.com/video/BV1eL411m78q/?vd_source=9d86603225d19f1b7ed921e767b73110

我把电视盒子装进了键盘里，改成了键盘电脑，谨以此片表达对o大的感谢。

**Comment by ophub** [comment]
你的视频真是杰作，看了几个特色鲜明，很有趣，看完让人愉悦，你的作品一般人模仿不了，你会火的。

**Comment by LioDon** [comment]
嘿嘿嘿，过奖过奖，没有前人铺路，我也玩不转的~~~

**Comment by LioDon** [comment]
哦，对了，盒子上原生的AV接口输出的时候，系统没有办法改成中文。即便是用HDMI输入改成中文，只要切换成AV输出，系统就会变成英语，在语言修改界面看，设置的明明还是Chinese。

**Comment by ophub** [comment]
可能是缺少某个字体
在openwrt系统刷机时，有人家里没有显示器，把盒子接在家里的电视上，刷机时脚本里的中文都是乱码，在浏览器ttyd或者ssh终端里看是正常的。

**Comment by lambs-c** [comment]
我的是e900v22c s905l3ab,也是报这个错误，参照这里的教程 成功写入emmc,学习了，多谢！

**Comment by LioDon** [comment]
https://github.com/CoreELEC/CoreELEC/releases/tag/19.5-Matrix

CoreELEC的19.5版本开始支持UWE5621，这个驱动有办法移植过来么？

**Comment by smanx** [comment]
> 实锤了，确实是板子的问题。同样都是UNT413A，前边说的那个是南传的，一直报错。 后来换了爱家TV的，可以刷了。 ![微信图片_20230210233014](https://user-images.githubusercontent.com/52228201/218130755-c3c9af1a-6225-49fa-a889-e0faf6368148.jpg) ![微信图片_20230210233027](https://user-images.githubusercontent.com/52228201/218130787-9e046981-880f-4821-96d6-d994fd5ed94d.jpg)
> 
> 另：附上我用的dtb文件（下载好之后删掉文件名后面的.md，网站不支持上传dtb格式文件），直接覆盖原文件即可。 [meson-g12a-s905l3a-cm311.dtb.md](https://github.com/ophub/amlogic-s9xxx-armbian/files/10708948/meson-g12a-s905l3a-cm311.dtb.md)

感谢分享文件，我的是南传的UNT413A，替换成附件的文件就成功了，感谢

**Comment by chen7393** [comment]
南传板子是没有救了吗

**Comment by chanxq** [comment]
> https://github.com/CoreELEC/CoreELEC/releases/tag/19.5-Matrix
> 
> CoreELEC的19.5版本开始支持UWE5621，这个驱动有办法移植过来么？

按理来说，都是linux的系统，很多都是相通的，完全有机会移植的。我大大小小装了整过很多个盒子，以S905L3A的最多，cm311-1a-yst和B863AV3.12-M2的，无线网卡芯片uwe5621和rtl8822cs，在coreelec都能驱动了，但是armbian还没有适用的。期待有大神能完善，这个盒子就圆满了。

**Comment by chanxq** [comment]
> https://github.com/CoreELEC/CoreELEC/releases/tag/19.5-Matrix
> 
> CoreELEC的19.5版本开始支持UWE5621，这个驱动有办法移植过来么？

按理来说，都是linux的系统，很多都是相通的，完全有机会移植的。我大大小小装了整过很多个盒子，以S905L3A的最多，cm311-1a-yst和B863AV3.12-M2的，无线网卡芯片uwe5621和rtl8822cs，在coreelec都能驱动了，但是armbian还没有适用的。期待有大神能完善，这个盒子就圆满了。

**Comment by ophub** [comment]
coreelec是安卓，armbian是主线内核，2个不同的内核。电视盒子是服务安卓系统的，驱动比较全，但厂家不一定给主线提交驱动。
