### ISSUE TITLE
FunTV/X96W(s905w) Wired/Wireless/Bluetooth are normal

### ISSUE THREAD

**Issue by daniyo27** [ophub/amlogic-s9xxx-armbian#1044]
**Device Information | 设备信息**
 - SOC: [S905W]
 - Model [FunTV (X96W)]

**Armbian Version | 系统版本**
jammy_5.15.91_server_2023.02.05

**Describe the bug | 问题描述**

Hi all, I have a FunTV box which seems to be a X96W S905W variant. [https://4pda.to/forum/index.php?showtopic=886489](url)

Mine has AP6255 wifi + H1621SR ethernet NIC

- The Wi-Fi doesn't seem to be detected. I think I need a dtb suitable for my device. Any help is appreciated!

Thank you!

![IMG_5315](https://user-images.githubusercontent.com/11026113/218044025-605acde6-6aa2-4584-8bb7-a8f050721f67.jpg)
![IMG_5314](https://user-images.githubusercontent.com/11026113/218044045-a9a3ec27-1307-4d3c-b7d0-b79b302deca0.jpg)
![IMG_5313](https://user-images.githubusercontent.com/11026113/218044049-984ab81a-70d7-4860-8edb-1451de7220d1.jpg)
![IMG_5312](https://user-images.githubusercontent.com/11026113/218044056-6616baba-15e9-4f48-9e7f-d34216ce3117.jpg)
![IMG_5311](https://user-images.githubusercontent.com/11026113/218044066-7d54d8c9-2b76-44a2-b6ab-26c7efeb67d3.jpg)
full board photo [https://4pda.to/forum/index.php?showtopic=886489&st=0#entry70149472](url)

**Comment by ophub** [comment]
WiFi & BT combo module AMPAK AP6255: try `bcm4329-fmac`

Which dtb are you using now, can it start normally, is the wired network normal?

**Comment by daniyo27** [comment]
I am using meson-gxl-s905w-x96-mini.dtb

wired network is normal (10/100mbps) and the box does start normally. 

I don't know how to add bcm4329-fmac to a dtb. Can you please help?

Thanks!

**Comment by ophub** [comment]
```
cd /boot
cp u-boot-s905x-s912.bin u-boot.ext
cp u-boot-s905x-s912.bin u-boot.emmc
chmod +x u-boot.emmc u-boot.ext
sync && reboot
```

Test whether this u-boot can be used.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/arch/arm64/boot/dts/amlogic

Add wireless support code in dts

**Comment by daniyo27** [comment]
> ```
> cd /boot
> cp u-boot-s905x-s912.bin u-boot.ext
> cp u-boot-s905x-s912.bin u-boot.emmc
> chmod +x u-boot.emmc u-boot.ext
> sync && reboot
> ```
> 
> Test whether this u-boot can be used.

I am stuck here now after running this ^^

![IMG_5316](https://user-images.githubusercontent.com/11026113/218051671-f309cb42-a235-439a-9e9c-f886ad65500c.jpg)

**Comment by ophub** [comment]
Insert the U disk into the computer, you can open the /boot partition, and delete the two files added by copying.

u-boot does not support, you can only use the 5.15/5.4 kernel in the future, do not update 6.1

**Comment by daniyo27** [comment]
@ophub I decompiled X96-Mini.dtb and added 

`wifi@1 {
	reg = <0x01>;
	compatible = "brcm,bcm4329-fmac";
};`

at the end of `mmc@70000` and was able to get Wi-Fi working. Can this be added as a dtb file to be built for future images? The box should be called FunTV3 or X96W

**Comment by ophub** [comment]
[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10712224/meson-gxl-s905w-x96w.dtb.zip)

Download, decompress into a `dtb` file, upload it to the `/boot/dtb/amlogic` directory, and modify the name of dtb in `/boot/uEnv.txt` to: `meson-gxl-s905w-x96w.dtb`

Save, restart, and test whether the `wired`, `wireless`, and `Bluetooth` are working properly. Bluetooth Go to `armbian-config` and add the Bluetooth support module.

**Comment by daniyo27** [comment]
Thank you! I tested `wired` and `wireless` and both are working.

`Bluetooth` is NOT working. I ran `bluetoothctl` with `list` command and it is not showing any available controllers. I did add the Bluetooth support module.

Almost there for getting everything working!

**Comment by ophub** [comment]
dmesg | grep Bluetooth

**Comment by daniyo27** [comment]
This is what I see!

![image](https://user-images.githubusercontent.com/11026113/218244841-96f36d2e-5822-4eac-9566-309530435b9c.png)

**Comment by ophub** [comment]
[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10712839/meson-gxl-s905w-x96w.dtb.zip)


try this dtb

**Comment by daniyo27** [comment]
Similar problem!
![image](https://user-images.githubusercontent.com/11026113/218245866-150e80df-980d-4b72-b1e3-2dd197c4b257.png)

**Comment by ophub** [comment]
[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10712871/meson-gxl-s905w-x96w.dtb.zip)

try again

**Comment by daniyo27** [comment]
No more errors, but still nothing in `bluetoothctl`.

![image](https://user-images.githubusercontent.com/11026113/218247271-1d124e6b-eb13-4ced-aaf4-c1151b69e58d.png)

**Comment by ophub** [comment]
[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10712916/meson-gxl-s905w-x96w.dtb.zip)

try again

**Comment by daniyo27** [comment]
Still not working

![image](https://user-images.githubusercontent.com/11026113/218247955-fa2dc38d-77bc-49e3-b876-8af009495c68.png)

**Comment by ophub** [comment]
```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2018 Martin Blumenstingl <martin.blumenstingl@googlemail.com>.
 * Based on meson-gxl-s905d-p231.dts:
 * - Copyright (c) 2016 Endless Computers, Inc.
 * - Copyright (c) unifreq
 */

/dts-v1/;

#include "meson-gxl-s905w-p281.dts"

/ {
	compatible = "amlogic,p281", "amlogic,s905w", "amlogic,meson-gxl";
	model = "X96W";

	aliases {
		serial0 = &uart_AO;   /* Console */
		serial1 = &uart_A;    /* Bluetooth */
		ethernet0 = &ethmac;
	};
};

/* SDIO wifi: AP6255 */
&sd_emmc_a {
	status = "okay";

	brcmf: wifi@1 {
		reg = <1>;
		compatible = "brcm,bcm4329-fmac";
	};
};

/* SD card */
&sd_emmc_b {
	status = "okay";
	bus-width = <4>;
	cap-sd-highspeed;
	max-frequency = <50000000>;
};

/* eMMC */
&sd_emmc_c {
	status = "okay";
	max-frequency = <50000000>;
};

/* Console UART */
&uart_AO {
	status = "okay";
	pinctrl-0 = <&uart_ao_a_pins>;
	pinctrl-names = "default";
};

/* S905W only has access to its internal PHY */
&ethmac {
	status = "okay";
	phy-mode = "rmii";
	phy-handle = <&internal_phy>;
};

&internal_phy {
	status = "okay";
	pinctrl-0 = <&eth_link_led_pins>, <&eth_act_led_pins>;
	pinctrl-names = "default";
	max-speed = <100>;
};

/* This is connected to the Bluetooth module: AP6255 */
&uart_A {
	status = "okay";
	pinctrl-0 = <&uart_a_pins>, <&uart_a_cts_rts_pins>;
	pinctrl-names = "default";
	uart-has-rtscts;

	bluetooth {
		compatible = "brcm,bcm4345c5";
		enable-gpios = <&gpio GPIOX_17 GPIO_ACTIVE_HIGH>;
		host-wake-gpios = <&gpio GPIOX_18 GPIO_ACTIVE_HIGH>;
	};
};

```

[meson-gxl-s905w-x96w.dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10712961/meson-gxl-s905w-x96w.dts.zip)
[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10712962/meson-gxl-s905w-x96w.dtb.zip)

This is the current test dts, you can continue to try

```
bluetooth: 
compatible = "brcm,bcm4345c5";
compatible = "bcm4329-fmac";
```

These two Bluetooth codes have cases in the current dts, but you can't use them for testing. Perhaps the bluetooth firmware is not working for you?

https://github.com/unifreq/linux-5.15.y/blob/main/Documentation/devicetree/bindings/net/wireless/brcm,bcm4329-fmac.yaml

https://github.com/ophub/firmware/tree/main/firmware/brcm

https://github.com/unifreq/linux-5.15.y/blob/02659e48f0ec17cb78a01846719812bf0f30536e/arch/arm64/boot/dts/allwinner/sun50i-h6-orangepi-lite2.dts#L77

**Comment by daniyo27** [comment]
I don't think we are doing this correctly. AP6255 should be using brcm,bcm4345c5 as bt binding.

I cannot compile dtb from source and so I cannot compile stuff with `&gpio` 

I believe I am missing the **interrupt** pins and using the right variables such as `shutdown-gpios` instead of `enable-gpios`.

Also, `host-wakeup-gpios` is deprecated and the message inside says `This is deprecated and replaced
      by interrupts and "host-wakeup" interrupt-names`

Can you try and help me compile this with the gpio/interrupt settings?

[link](https://github.com/unifreq/linux-5.15.y/blob/b8b6eae688966770ce6caea81d52635f50e3002b/Documentation/devicetree/bindings/net/broadcom-bluetooth.yaml)

**Comment by daniyo27** [comment]
Attached is current `dmesg` of `brcm` with `bluetooth {
					compatible = "brcm,bcm4345c5";
					brcm,bt-pcm-int-params = [01 02 00 01 01];
					shutdown-gpios = <0x15 0x60 0x00>;
					max-speed = <921600>;
					device-wakeup-gpios = <0x16 0x61 0x00>;
				};`

![image](https://user-images.githubusercontent.com/11026113/218286554-adbce3a8-183e-4807-b5f4-054bfa864f4a.png)

**Comment by ophub** [comment]
[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10715191/meson-gxl-s905w-x96w.dtb.zip)

try again

**Comment by daniyo27** [comment]
Bingo! It works!

<img width="775" alt="image" src="https://user-images.githubusercontent.com/11026113/218291793-46377c5b-ae04-43a1-b075-12cd84e86000.png">

**Comment by ophub** [comment]
```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2018 Martin Blumenstingl <martin.blumenstingl@googlemail.com>.
 * Based on meson-gxl-s905d-p231.dts:
 * - Copyright (c) 2016 Endless Computers, Inc.
 * - Copyright (c) unifreq
 */

/dts-v1/;

#include "meson-gxl-s905w-p281.dts"

/ {
	compatible = "amlogic,p281", "amlogic,s905w", "amlogic,meson-gxl";
	model = "X96W";

	aliases {
		serial0 = &uart_AO;   /* Console */
		serial1 = &uart_A;    /* Bluetooth */
		ethernet0 = &ethmac;
	};
};

/* SDIO wifi: AP6255 */
&sd_emmc_a {
	status = "okay";

	brcmf: wifi@1 {
		reg = <1>;
		compatible = "brcm,bcm4329-fmac";
	};
};

/* SD card */
&sd_emmc_b {
	status = "okay";
	bus-width = <4>;
	cap-sd-highspeed;
	max-frequency = <50000000>;
};

/* eMMC */
&sd_emmc_c {
	status = "okay";
	max-frequency = <50000000>;
};

/* Console UART */
&uart_AO {
	status = "okay";
	pinctrl-0 = <&uart_ao_a_pins>;
	pinctrl-names = "default";
};

/* S905W only has access to its internal PHY */
&ethmac {
	status = "okay";
	phy-mode = "rmii";
	phy-handle = <&internal_phy>;
};

&internal_phy {
	status = "okay";
	pinctrl-0 = <&eth_link_led_pins>, <&eth_act_led_pins>;
	pinctrl-names = "default";
	max-speed = <100>;
};

/* This is connected to the Bluetooth module: AP6255 */
&uart_A {
	status = "okay";
	pinctrl-0 = <&uart_a_pins>, <&uart_a_cts_rts_pins>;
	pinctrl-names = "default";
	uart-has-rtscts;

	bluetooth {
		compatible = "brcm,bcm4345c5";
		shutdown-gpios = <&gpio GPIOX_17 GPIO_ACTIVE_HIGH>;
		max-speed = <2000000>;
		clocks = <&wifi32k>;
		clock-names = "lpo";
	};
};

```
[meson-gxl-s905w-x96w.dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10715273/meson-gxl-s905w-x96w.dts.zip)

[meson-gxl-s905w-x96w.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10715272/meson-gxl-s905w-x96w.dtb.zip)

**Comment by ophub** [comment]
The s905w series of TV Boxes only support the use of the 5.4.y/5.15.y kernel.

I submit to the kernel source repository of unifreq.

**Comment by daniyo27** [comment]
Thank you for your time and persistence to get this device to work! Hopefully this is of use to other X96W / FunTV owners!

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/526646ff49f9311dc7f3799261696e12b8f5a00b/build-armbian/armbian-files/common-files/etc/model_database.conf#L52

Already added, the installation number is `119`

**Comment by ophub** [comment]
At present, several other devices of `s905w`, such as X96-Mini, TX3-Mini and W95, can use `u-boot-s905x-s912.bin` to start the `6.1.y` kernel.

You test again, use `USB` to start the firmware of 5.15.y of `s905w`, and modify the dtb in `/boot/uEnv.txt` to: `meson-gxl-s905w-x96w.dtb`

Copy `u-boot-s905x-s912.bin` to `u-boot.ext`

Then start USB to see if it can start to the welcome interface normally.

**Comment by daniyo27** [comment]
I am trying to boot from USB but it seems to keep booting off of eMMC. I have a reset button on the back, but it is not doing anything. Any ideas?

**Comment by ophub** [comment]
```
cd /boot
mv boot.cmd boot.cmd.bak
mv boot.src boot.src.bak
```

After you start from USB, you can mount emmc into USB, modify it back, and then you can restart from EMMC after unplugging USB.

```
cd /mnt
mkdir emmc_boot
mount /dev/mmcblk2p1 emmc_boot
cd emmc_boot
mv boot.cmd.bak boot.cmd
mv boot.src.bak boot.src
```

**Comment by daniyo27** [comment]
Very interesting... it is booting indeed with kernel 6.1!


> ```
> cd /boot
> cp u-boot-s905x-s912.bin u-boot.ext
> cp u-boot-s905x-s912.bin u-boot.emmc
> chmod +x u-boot.emmc u-boot.ext
> sync && reboot
> ```
> 
> Test whether this u-boot can be used.

I believe this earlier test did not work because I was booting off a SD card.

On another note, is there any reason why the kernel config build has CONFIG_WIREGUARD=m? Can we have this enabled by default so users can use Wireguard properly?

**Comment by ophub** [comment]
`vi /etc/ophub-releases`


```
FDTFILE='meson-gxl-s905w-x96w.dtb'
UBOOT_OVERLOAD='u-boot-s905x-s912.bin'
KERNEL_VERSION='stable'
```

**Comment by daniyo27** [comment]
I did the update but after rebooting and running `uname -r` it is still 5.15.91
I also had to change `KERNEL_BRANCH` to stable for it to do install

![image](https://user-images.githubusercontent.com/11026113/218983504-b424027f-6f71-437f-9c5f-ad9768d86a1f.png)

**Comment by daniyo27** [comment]
I tried again, this is the result now.

![IMG_5366](https://user-images.githubusercontent.com/11026113/218984888-ccbc3f32-bfe9-4078-9033-f945bb3311b2.jpg)

**Comment by ophub** [comment]
FDTFILE error

Are you on a USB? What did you do after you added U-BOOT to boot successfully? The command to execute?

**Comment by daniyo27** [comment]
Yes I am on USB. I did the modification on ophub-release and also changed current branch to stable.

then I ran
‘armbian-sync’
‘armbian-update -k 6.1.12’

And it auto rebooted to what you see above

**Comment by daniyo27** [comment]
Maybe it’s best to have a compile img of kernel 6.1 for our board for me to test?

**Comment by ophub** [comment]
I know the reason. Your dtb is not added to the 6.1.y source code. I only add your dtb to the upstream 5.4 and 5.15 kernel source code repository, because you have previously reported that u-boot cannot be used

**Comment by daniyo27** [comment]
I managed to boot kernel 6.1.12 with the new images. 
I had to rename the `FDTFILE` to my dtb and all is good except that the **SSH server is failing?**

![IMG_5368](https://user-images.githubusercontent.com/11026113/219120383-6419c87d-3899-4c84-8a72-11720a917fa6.jpg)

**Comment by ophub** [comment]
Thank you for your feedback. It seems that the s905w can also use the 6. x.y series kernel. I will cancel the restrictions on it.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/72082aea762aebce7e551398191a927ba2497b19/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L25-L27

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/commit/f91670fb790be80c6744cb9e4a982dce769ce9d3

6.1/5.10 also added this dtb.

**Comment by daniyo27** [comment]
@ophub sorry for the delay, I can confirm the latest image with kernel 6.1 do work on the s905w along with eMMC install

<img width="377" alt="image" src="https://user-images.githubusercontent.com/11026113/219936514-0a918db4-a2b9-42d5-86bb-31cba4555e5e.png">

**Comment by ophub** [comment]
ok

**Comment by zdaokimo** [comment]
Dear daniyo27,
I got the same device from my dad and have the issue with the firmware. May I have your modified firmware img file? I am sorry i don't have any background in editing the firmware but do know how to flash the amlogic firmware. Thx again.
