### ISSUE TITLE
Wojia-TV-IPBS9505 选择5.4内核 wifi可正常使用连接wifi不死机

### ISSUE THREAD

**Issue by swdshsn** [ophub/amlogic-s9xxx-armbian#1046]
浪潮IPBS9505
cpu S905L2,
wifi 8189ftv
装klipper尝试给内核配置can驱动
内核5.15.91  不定时死机、连接wifi死机
内核5.15.91  armbian-update更新内核5.15.92（加入全部can驱动）不定时死机、连接wifi死机
内核5.15.91 armbian-update更新内核5.10。167（加入全部can驱动）连不上
U盘系统6.1.10 连不上
内核5.15.91 armbian-update 更新内核5.4.231 wifi能够正常使用 不死机？（刚刚刷好不清楚）

**Comment by swdshsn** [comment]
内核5.4.231 配置文件为/amlogic-s9xxx-armbian/compile-kernel/tools/config/config-5.4

**Comment by ophub** [comment]
哪个内核用着稳定，就本地备份一下，仓库里滚动更新就删了

**Comment by swdshsn** [comment]
还是会不定时死机

**Comment by swdshsn** [comment]
SSH是Socket error Event: 32 Error: 10053. 后面wifi都会断掉 是休眠吗？

**Comment by swdshsn** [comment]
ssh挂着挂着就死机了

**Comment by ophub** [comment]
ssh断开就连不上了？就死机了？

**Comment by swdshsn** [comment]
死机后wifi和网线连不上 路由器显示网线先没了 过一会wifi掉了

**Comment by swdshsn** [comment]
我这里是盒子的wifi和网线都连着路由器

**Comment by swdshsn** [comment]
Feb 10 19:39:43 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:43 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:43 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:45 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 509.
Feb 10 19:39:45 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:45 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Feb 10 19:39:45 armbian hostapd[7849]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Feb 10 19:39:45 armbian hostapd[7849]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 10 19:39:45 armbian hostapd[7849]: Failed to initialize interface
Feb 10 19:39:45 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:45 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:45 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:47 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 510.
Feb 10 19:39:47 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:47 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Feb 10 19:39:47 armbian hostapd[7850]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Feb 10 19:39:47 armbian hostapd[7850]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 10 19:39:47 armbian hostapd[7850]: Failed to initialize interface
Feb 10 19:39:47 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:47 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:47 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:48 armbian kernel: [ 1166.008786] RTL871X: cfg80211_rtw_dump_station(wlan0)
Feb 10 19:39:48 armbian kernel: [ 1166.011304] RTL871X: Station is not found
Feb 10 19:39:50 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 511.
Feb 10 19:39:50 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:50 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Feb 10 19:39:50 armbian hostapd[7851]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Feb 10 19:39:50 armbian hostapd[7851]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 10 19:39:50 armbian hostapd[7851]: Failed to initialize interface
Feb 10 19:39:50 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:50 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:50 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:52 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 512.
Feb 10 19:39:52 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:52 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Feb 10 19:39:52 armbian hostapd[7854]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Feb 10 19:39:52 armbian hostapd[7854]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 10 19:39:52 armbian hostapd[7854]: Failed to initialize interface
Feb 10 19:39:52 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:52 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:52 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:52 armbian kernel: [ 1170.380504] RTL871X: rtl8188f_fill_default_txdesc(wlan0): SP Packet(0x0806) rate=0x0
Feb 10 19:39:54 armbian kernel: [ 1172.009570] RTL871X: cfg80211_rtw_dump_station(wlan0)
Feb 10 19:39:54 armbian kernel: [ 1172.012600] RTL871X: Station is not found
Feb 10 19:39:54 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 513.
Feb 10 19:39:54 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:54 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Feb 10 19:39:54 armbian hostapd[7855]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Feb 10 19:39:54 armbian hostapd[7855]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 10 19:39:54 armbian hostapd[7855]: Failed to initialize interface
Feb 10 19:39:54 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:54 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:54 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:56 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 514.
Feb 10 19:39:56 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Feb 10 19:39:56 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Feb 10 19:39:56 armbian hostapd[7856]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Feb 10 19:39:56 armbian hostapd[7856]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 10 19:39:56 armbian hostapd[7856]: Failed to initialize interface
Feb 10 19:39:56 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Feb 10 19:39:56 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Feb 10 19:39:56 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
log里面全是wifi相关的...

**Comment by swdshsn** [comment]
关了wifi就没这几条重复的信息了

**Comment by swdshsn** [comment]
ok 解决了

**Comment by swdshsn** [comment]
这样wifi还是不能用吗

**Comment by ophub** [comment]
wifi在大部分盒子都不能用，用有线吧。

**Comment by swdshsn** [comment]
好的谢谢
