### ISSUE TITLE
Armbian WIFI热点怎么开启

### ISSUE THREAD

**Issue by alegoho** [ophub/amlogic-s9xxx-armbian#1047]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. UGOOS X3]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.92]
 - Release: [e.g. jammy]

盒子已刷入Armbian，已稳定运行两三天，盒子上有WIFI模块，OP上是可以发射WIFI信号的，我觉得ARMBIAN应该也是可以的，我在armbian-config，上是看到有选项创建AP的，但我试过两次都不行，请问怎么在armbian上创建WIFI热点发射WIFI信号？

**Comment by ophub** [comment]
你是说docker里面装op?

**Comment by alegoho** [comment]
> 你是说docker里面装op?

不是，就是ARMBIAN上直接将WIFI做成热点发射WIFI信号，盒子不刷ARMBIAN刷OP的话是有WIFI信号发射出来的，ARMBIAN是一个操作系统，理论上应该是可以做热点发射WIFI信号

**Comment by ophub** [comment]
盒子是同一个盒子，刷op是路由器，刷ce是游戏机，刷armbian是服务器。

你的要求是不过分，毕竟这个盒子这些事情都干过了。

但是你得给armbian装点什么应用或者服务吧，这么为难armbian原生系统去干好路由器的活有点为难了。比如你可以docker装个openwrt，或者装个RaspAP应用等。

**Comment by ophub** [comment]
https://www.cnblogs.com/wxfy/p/10879858.html

**Comment by alegoho** [comment]
> https://www.cnblogs.com/wxfy/p/10879858.html

4年前的还适用吗？我周末试一下

**Comment by alegoho** [comment]
> https://www.cnblogs.com/wxfy/p/10879858.html

https://www.bilibili.com/read/cv17536257/

我找到一个这样的，不知道是不是我已经试过，最后不知道怎么搞，现在不见那个选项。。。晕了。。。

**Comment by alegoho** [comment]
> https://www.cnblogs.com/wxfy/p/10879858.html

Failed to start hostapd.service: Unit hostapd.service is masked.

这个提示是不是没安装hostapd?

**Comment by alegoho** [comment]
root@armbian:~# journalctl -xeu hostapd.service
░░ The job identifier is 17741.
Feb 11 16:29:34 armbian hostapd[7910]: Could not open configuration file '/etc/hostapd/hostapd.conf' for >
Feb 11 16:29:34 armbian hostapd[7910]: Failed to set up interface with /etc/hostapd/hostapd.conf
Feb 11 16:29:34 armbian hostapd[7910]: Failed to initialize interface
Feb 11 16:29:34 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ An ExecStart= process belonging to unit hostapd.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Feb 11 16:29:34 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ The unit hostapd.service has entered the 'failed' state with result 'exit-code'.
Feb 11 16:29:34 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and >
░░ Subject: A start job for unit hostapd.service has failed
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit hostapd.service has finished with a failure.
░░ 
░░ The job identifier is 17741 and the job result is failed.
lines 5302-5327/5327 (END)

**Comment by alegoho** [comment]
root@armbian:~# service hostapd restart
Job for hostapd.service failed because the control process exited with error code.
See "systemctl status hostapd.service" and "journalctl -xeu hostapd.service" for details.

**Comment by ysuolmai** [comment]
什么网卡？我刚搞定了网卡驱动，开ap妥妥的

**Comment by ysuolmai** [comment]
> > 什么网卡？我刚搞定了网卡驱动，开ap妥妥的
> 
> 是正基的AP6255，其实驱动应该已经有的，用装了ARMBIAN的盒子是可以连接我路由的WIFI，现在我是想开AP，发射WIFI信号，尝试了好几种方法都无法开启，请问你是怎么开启的？

驱动也是要看能不能支持开AP，你这个看起来是不支持的，得找到对应的驱动自己编译

**Comment by alegoho** [comment]
> > > 什么网卡？我刚搞定了网卡驱动，开ap妥妥的
> > 
> > 
> > 是正基的AP6255，其实驱动应该已经有的，用装了ARMBIAN的盒子是可以连接我路由的WIFI，现在我是想开AP，发射WIFI信号，尝试了好几种方法都无法开启，请问你是怎么开启的？
> 
> 驱动也是要看能不能支持开AP，你这个看起来是不支持的，得找到对应的驱动自己编译

这就麻烦了，这个真小白，那ARMBIAN有N1无线的驱动 吗？

**Comment by willsilicon** [comment]
> https://www.cnblogs.com/wxfy/p/10879858.html

你好，今天我就是这么搞的，但是提示找不到驱动nl80211，查了一下config.gz文件里确实编译的时候没有设置，我用的是Jammy的N1盒子，下载的镜像是6.1.118的，请问其他内核版本的哪个是编进去的？或者我自己可以找到这个适配的驱动文件吗？
