### ISSUE TITLE
X96Max_Plus2_AI either -19 error on ETH or no connection.

### ISSUE THREAD

**Issue by Dupp0** [ophub/amlogic-s9xxx-armbian#1054]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905X3
 - Model X96Max_Plus2_AI

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.92 & 6.1.10
 - Release: jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Hi, I'm facing issue with said X96Max AI board with IP1001M 1gbps eth. I tried to use 1001m.dtb and 1001m-2.dtb, with no luck. Either I'm getting -19 error and eth does not display at all, or eth is visible but never getting IP. I see that other users have had the same issue with same eth. Any ideas how to solve this?

**Comment by serrj-sv** [comment]
Use dtb which gives you no "-19 error" and set interface to 100Mbps (ethtool -s eth0 speed 100).
I have the same model and faces same issue. Looks like some issues with rgmii delay modes ( I tried all of them, non worked).
Also note, both 1001m.dtb and 1001m-2.dtb are heavily overclocked, that gives me kernel panic. I had to limit max cpu speed.

**Comment by Dupp0** [comment]
> Use dtb which gives you no "-19 error" and set interface to 100Mbps (ethtool -s eth0 speed 100).
> I have the same model and faces same issue. Looks like some issues with rgmii delay modes ( I tried all of them, non worked).
> Also note, both 1001m.dtb and 1001m-2.dtb are heavily overclocked, that gives me kernel panic. I had to limit max cpu speed.

Hey thanks! Setting interface speed to 100mbps indeed worked straight away. Have you experienced problems with booting from EMMC with said boards?

**Comment by serrj-sv** [comment]
> Have you experienced problems with booting from EMMC with said boards?

Yes, I had. I prefer using mainline u-boot instead of chainloaded one, but it would stuck on init stage. I compiled my own u-boot, using instructions provided by @ophub here:

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#1211-how-to-make-u-boot-file

For new u-boot to work with X96 Max Plus2 AI I modified dts file lines 109 and 111 of this file (replaces 0 to 1):
https://github.com/unifreq/u-boot/blob/master/arch/arm/dts/meson-sm1-x96-max-plus.dts

**Comment by Dupp0** [comment]
> > Have you experienced problems with booting from EMMC with said boards?
> 
> Yes, I had. I prefer using mainline u-boot instead of chainloaded one, but it would stuck on init stage. I compiled my own u-boot, using instructions provided by @ophub here:
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#1211-how-to-make-u-boot-file
> 
> For new u-boot to work with X96 Max Plus2 AI I modified dts file lines 109 and 111 of this file (replaces 0 to 1): https://github.com/unifreq/u-boot/blob/master/arch/arm/dts/meson-sm1-x96-max-plus.dts

Thank you for all the help. I'll look into this and hopefully get it running.
