### ISSUE TITLE
大神能编译创维E900V21C-905L3 L3B-EMMC板号5800-2AMBA02的固件吗？

### ISSUE THREAD

**Issue by 2536** [ophub/amlogic-s9xxx-armbian#1055]
大神能编译创维E900V21C-905L3 L3B-EMMC板号5800-2AMBA02的固件吗？
我分别下载了这两个固件，(Armbian_23.02.0_amlogic_s905l2_jammy_6.1.10_server_2023.02.12.img.gz和Armbian_23.02.0_amlogic_s905l3a_jammy_6.1.10_server_2023.02.12.img.gz)
烧写到U盘，然后插到盒子上面都无法启动。另外一个Armbian_23.02.0_amlogic_s905lb-r3300l_jammy_5.15.92_server_2023.02.12.img.gz，烧写到U盘插上盒子可以启动跑马，但是跑到一半就不动了

![AOVGZCA 3{% XTD_OV1IC5](https://user-images.githubusercontent.com/28776371/218482497-3b19719b-7409-4a3d-8d1e-dadb3deb1aec.png)
盒子型号为创维E900V21C创维
的主板号是5800-2AMBA02来自湖北移动，内存是1+8，一个网线口，两个USB口没有WiFi，一个2.5的AV口视频口，一个hdmi口
，没有蓝牙，有红外

![MVIMG_20230213_140633](https://user-images.githubusercontent.com/28776371/218483726-74d06bcc-e924-470d-ae23-ee9a1c054bd9.jpg)
![MVIMG_20230213_140537](https://user-images.githubusercontent.com/28776371/218483834-7de72e00-90e0-4b2c-a578-fd5794c87e60.jpg)

![MVIMG_20230213_140529](https://user-images.githubusercontent.com/28776371/218483875-b24393ca-ec9c-4a67-8f7f-f5a6f5351fc8.jpg)

**Comment by ophub** [comment]
下载5.15的s912的固件。
修改/boot/uEnv.txt和extlinux/extlinux.conf两个文件里的dtb的名字
dtb用meson-gxl-s905x-nexbox-a95x.dtb
u-boot用/boot/u-boot-p212.bin，复制为/boot/u-boot.ext

改好了USB启动测试

**Comment by DHinh** [comment]
我有同款。先用20191219-R3300L-Q7-6.0-root-twrp-Milton固件刷成安卓6.0再用Armbian_20.10_Arm-64_bullseye_current_5.9.0.img这个版本就能armbian了

**Comment by ophub** [comment]
分享一下你的安卓系统下载链接。
你在armbian里使用的哪个dtb和u-boot

**Comment by DHinh** [comment]
安卓6.0 链接: https://pan.baidu.com/s/1Q8nFHFpBW6-Qq5HsvnFNzQ 提取码: 4tez
E900v21c可用固件链接: https://pan.baidu.com/s/1qPih7h39CEsaIogqTgYHKg 提取码: ks9w

**Comment by DHinh** [comment]
> 分享一下你的安卓系统下载链接。 刷机短接点在主板图上标注下，方便其他人参照刷机 你在armbian里使用的哪个dtb和u-boot

我用的短接神器没有拆机短接。

**Comment by DHinh** [comment]
先把e900v21c的安卓4.4刷成我发的6.0
然后上传固件Armbian_20.10_Arm-64_bullseye_current_5.9.0.img
写盘完成后，U盘会被识别为一个名为BOOT的分区

进入/boot/extlinux目录
# aml s9xxx
#FDT /dtb/amlogic/meson-gxbb-p200.dtb
FDT /dtb/amlogic/meson-gxl-s905x-p212.dtb
#FDT /dtb/amlogic/meson-gxm-q200.dtb
#FDT /dtb/amlogic/meson-g12a-x96-max.dtb
#FDT /dtb/amlogic/meson-g12b-odroid-n2.dtb
APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0

然后重命名U盘根目录的u-boot-s905x-s912为u-boot.ext

**Comment by ophub** [comment]
你下载5.15的固件测试过没？
uEnv.txt和extlinux 里修改dtb用meson-gxl-s905x-p212.dtb
u-boot-s905x-s912.bin复制为u-boot.ext

**Comment by DHinh** [comment]
> 你下载5.15的固件测试过没？ uEnv.txt和extlinux 里修改dtb用meson-gxl-s905x-p212.dtb u-boot-s905x-s912.bin复制为u-boot.ext

我只在安卓4.4的时候试过一次，启动不起来。刷了安卓6.0以后就没试过了、不晓得能不能启动。我当时也是找的教程跟着刷的

**Comment by 2536** [comment]
> 
这个固件20191219-R3300L-Q7-6.0-root-twrp-Milton怎么刷？是用线刷还是？直接烧U盘，我线刷不成功失败，不管打不打勾，它都显示失败，
你确定你那个的机器主板与我这个一样吗？，虽然都是905l的，但是并不一定会通刷，创维代工的这一款机器太乱了，同样的型号，主板都细分六七种，好像不同的主板型号的包都不通刷（具体请参考https://www.szjytx.com/?id=12985）

**Comment by DHinh** [comment]
> > 
> 
> 这个固件20191219-R3300L-Q7-6.0-root-twrp-Milton怎么刷？是用线刷还是？直接烧U盘，我线刷不成功失败，不管打不打勾，它都显示失败， 你确定你那个的机器主板与我这个一样吗？，虽然都是905l的，但是并不一定会通刷，创维代工的这一款机器太乱了，同样的型号，主板都细分六七种，好像不同的主板型号的包都不通刷（具体请参考[https://www.szjytx.com/?id=12985）](https://www.szjytx.com/?id=12985%EF%BC%89)

需要先短接再通电。

**Comment by DHinh** [comment]
> > 
> 
> 这个固件20191219-R3300L-Q7-6.0-root-twrp-Milton怎么刷？是用线刷还是？直接烧U盘，我线刷不成功失败，不管打不打勾，它都显示失败， 你确定你那个的机器主板与我这个一样吗？，虽然都是905l的，但是并不一定会通刷，创维代工的这一款机器太乱了，同样的型号，主板都细分六七种，好像不同的主板型号的包都不通刷（具体请参考[https://www.szjytx.com/?id=12985）](https://www.szjytx.com/?id=12985%EF%BC%89)

我没拆机，不晓得主板一样不。但是我盒子上也是写的E900V21C也确实是905l和1+8的

**Comment by DHinh** [comment]
> > 
> 
> 这个固件20191219-R3300L-Q7-6.0-root-twrp-Milton怎么刷？是用线刷还是？直接烧U盘，我线刷不成功失败，不管打不打勾，它都显示失败， 你确定你那个的机器主板与我这个一样吗？，虽然都是905l的，但是并不一定会通刷，创维代工的这一款机器太乱了，同样的型号，主板都细分六七种，好像不同的主板型号的包都不通刷（具体请参考[https://www.szjytx.com/?id=12985）](https://www.szjytx.com/?id=12985%EF%BC%89)

固件来自于恩山https://www.right.com.cn/forum/thread-1761250-1-1.html

**Comment by 2536** [comment]
不行，短接也刷不进去，反正这个型号的主板分六七种，不同主板型号的包都不能通刷，你方便加个q吗214471918

**Comment by 2536** [comment]
> 分享一下你的安卓系统下载链接。 刷机短接口在主板上标记下，方方便其他人参与拍照 你在armbian里使用的哪个dtb和u-boot
创维E900V21C-905L3 L3B-EMMC板号5800-2AMBA02短接点其他主板型号未知
![image](https://user-images.githubusercontent.com/28776371/218664066-854a21eb-5c0f-41e2-ae42-fcf75110e00e.png)
![image](https://user-images.githubusercontent.com/28776371/218663422-022cb2fa-5439-47c1-9d6a-b08d1e2eaf03.png)
![MVIMG_20230214_150453](https://user-images.githubusercontent.com/28776371/218663651-5fd93828-555a-4dbd-b48c-7d46baf12e89.jpg)

**Comment by 2536** [comment]
> u-boot用/boot/u- boot-p212.bin，复制为/boot/u-boot.ext
u-boot用/boot/u- boot-p212.bin，复制为/boot/u-boot.ext
这句话是什么意思？u- boot-p212.bin是重命名为u-boot.ext这个名字吗？

**Comment by ophub** [comment]
复制一个，不是改名。如果你改名了就只在usb测试使用，不要往emmc写入，因为缺了这个写入会无法启动。

**Comment by 2536** [comment]
> 复制一个，不是改名。如果你改名了就只在usb测试使用，不要往emmc写入，因为缺了这个写入会无法启动。

是复制s912的固件中的u-boot.ext到Armbian_23.02.0_amlogic_s905l3a_jammy_6.1.10_server_2023.02.12.img.gz吗

**Comment by ophub** [comment]
不是，每个固件里都有，不用从其他地方搬运，在/boot里面。

我把armbian刷入U盘后，在电脑上拔出来U盘，再插上电脑就会显示出来U盘中的/boot分区了，双击进去就看到u-boot很多个，看准文件名复制一个

**Comment by 2536** [comment]
> 
你的意思是这个CPU s905l3b的，可以用s912的固件？

**Comment by ophub** [comment]
我没这个意思

**Comment by 2536** [comment]
> 我没有这个意思
![`)BSSYLJH~~PU7NMGBP)TCV](https://user-images.githubusercontent.com/28776371/219009822-481f9b7d-ccd7-429b-90d3-e8cc56ae76d1.png)
那是什么意思？还是用之前的包Armbian_23.02.0_amlogic_s905lb-r3300l_jammy_5.15.92_server_2023.02.12.img.gz修改是吗？

**Comment by ophub** [comment]
是这个意思

**Comment by 2536** [comment]
> 是这个意思
还是不行，跑马跑到这里就不行了
![X9H4B EU_Y1I9Z35ZKN2%D1](https://user-images.githubusercontent.com/28776371/219014135-c1518652-b0db-4eb9-b870-f27894835c70.png)

**Comment by 2536** [comment]
后面换成这个固件刷Armbian_23.02.0_amlogic_s905l2_jammy_5.15.94_server_2023.02.15.img.gz刷了，可以正常启动，
，但是检测不到网口，貌似不能联网，路由器也查不到这个设备的联网分配IP的信息
![`(4D{J2QKMI UP(E YZW5H4](https://user-images.githubusercontent.com/28776371/219024163-3260e23a-cceb-4196-a618-8c6048e4c54c.png)

**Comment by ophub** [comment]
只修改dtb，不添加u-boot（如果添加了，删除/boot/u-boot.ext）试试能不能正常启动。

**Comment by 2536** [comment]
> 只修改dtb，不添加u-boot（如果添加了，删除/boot/u-boot.ext）试试不能正常启动。
不能

**Comment by DHinh** [comment]
我把我的拆开看了下。 确实主板和你的不一样
![20230216150759](https://user-images.githubusercontent.com/105959047/219293044-0f32c807-8e4c-4df1-a35d-e3a859c03aca.jpg)

**Comment by 2536** [comment]
看一下你那个主板型号跟我那个都不一样，我说了这一款的创维E900V21C有好多个版本，怎么全是代工的，太乱了
