### ISSUE TITLE
这是什么问题？为什么编译失败了

### ISSUE THREAD

**Issue by JustinTangChina** [ophub/amlogic-s9xxx-armbian#1056]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. s905l3a]
 - Model [e.g. 新魔百和M401a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.4.231]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
看到大神的armbian编译源码，还有5.4.231的核心 想编译自己的 armbian版本  

  用的虚拟机安装的 ubuntu 22.04 LTS 系统
下面是图片说明
用  sudo ./rebuild -b s905l3a -k 5.4.231   编译失败

![1](https://user-images.githubusercontent.com/117615710/218515416-d0a7417e-df2e-4045-b4a2-2e6b2e6c5868.PNG)

![2](https://user-images.githubusercontent.com/117615710/218515466-d867b47f-6dd2-4c6d-8797-e218110259f3.PNG)

![3](https://user-images.githubusercontent.com/117615710/218515502-49af8e7b-eb3c-46a0-8be6-359477951074.PNG)

Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by OPMonday** [comment]
![image](https://user-images.githubusercontent.com/105340869/218518210-03714e38-eea4-4e45-9184-a170110907b5.png)
你应该用这个镜像打包

**Comment by JustinTangChina** [comment]
其实我想要5.9.0内核的包 可以他这个没5.9.0的内核可以选 选原版的又怕不适用

**Comment by OPMonday** [comment]
可以自己编译

**Comment by JustinTangChina** [comment]
我不会啊  我小白啊  刚解除armbian linux
最后这个不知道是啥

![4](https://user-images.githubusercontent.com/117615710/218521581-3df94c99-2697-4430-9b1a-848aec286497.PNG)
![5](https://user-images.githubusercontent.com/117615710/218521621-1ee8d1e6-c397-4182-b6e1-780d38e16646.PNG)

**Comment by JustinTangChina** [comment]
对 就是大神没优化  所以 自己又不会只能选有优化的了

**Comment by OPMonday** [comment]
你可以试试我打包的

**Comment by JustinTangChina** [comment]
不知道是不是我的错觉 刷了他们的包 我插上usb网卡 然后 更新软件，系统会直接蹦掉 然后死机了 不知道什么原因  我刷了 armbian 然后安装klipper 使用

**Comment by OPMonday** [comment]
m401a CPU好像体制不太好

**Comment by OPMonday** [comment]
我不知道是不是我运气好，我的UNT403A从来没出过问题，而且超频到2.2Ghz都很稳定
而且写入emmc 304 305 306都行，就很奇怪你们的盒子为什么有这么多问题

**Comment by JustinTangChina** [comment]
还没到这里 在安装klipper的时候 执行更新软件列表就挂了   不插上无线网卡 没事 插上就死机

**Comment by OPMonday** [comment]
这个可能涉及到供电

**Comment by ophub** [comment]
按照文档操作，第一步是给编译机上安装依赖。错误提示没curl、svn等就是没执行第一步的操作。

**Comment by JustinTangChina** [comment]
curl 和svn 后面已经安装了 现在 卡在编译了 其他的不是都下载好了吗

**Comment by ophub** [comment]
把根目录下多余的生成目录out, tmp删除，里面是上次失败的残存文件.
把挂载失败的删除lsblk看挂载失败的镜像卸载umount /dev/loopxpx
