### ISSUE TITLE
A95X-F2 4GB+64GB版本  无法安装到EMMC

### ISSUE THREAD

**Issue by xsunnydong** [ophub/amlogic-s9xxx-armbian#1058]
盒子xinghao型号
![微信图片_20230214114419](https://user-images.githubusercontent.com/40882045/218633918-761e001e-267c-427a-af40-863ce9fcf8bf.jpg)
盒子emmc的系统是厂家的安卓系统，armbian是从U盘启动的

![微信图片_20230214114329](https://user-images.githubusercontent.com/40882045/218633956-5abd5bae-fdda-4b32-9079-434dac5cdacd.jpg)
刷入emmc前还需要其他操作么？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看文档12.16

**Comment by xsunnydong** [comment]
**大佬好，现已经修改到 dts中 emmc 速度到50000000  U盘使用的是闪迪酷豆 usb2.0 16GB**
![B2D594E5-B072-4803-8D29-225FCE5ADA5D](https://user-images.githubusercontent.com/40882045/218736738-61674254-bb3c-441c-8a67-f5504c6cbbff.png)
 **仍旧写入emmc失败**
<img width="521" alt="D6899247-0F38-48d8-9AD1-43EAA452C44F" src="https://user-images.githubusercontent.com/40882045/218737665-8ac7e91b-3ae1-492c-9d3e-1046cfb892f8.png">
 **产生故障的原因是U盘速度过慢吗？ 和U盘体质关系大吗？**

**Comment by ophub** [comment]
更低的还有sd-uhs-sdr12， 对应emmc的25mhz频率。

USB和 emmc两处一起改底。

不是慢的问题，是快的问题。修改就是要降低它们的工作频率，解决体质弱的盒子频率高了无法识别或者无法写入的问题。

**Comment by xsunnydong** [comment]
**按照要求修改了最大的速度max-frequency = <0x5f5e100>;（重启，加载生效) ，已经能安装到emmc，且启动正常，感谢。**
<img width="663" alt="2023-02-14_215747" src="https://user-images.githubusercontent.com/40882045/218761513-ca3f9ac3-5e94-44cb-912a-e188991731dd.png">
<img width="458" alt="EC420B39-9894-4fba-8792-B3653082230D" src="https://user-images.githubusercontent.com/40882045/218761545-6eb91587-de88-4176-ab75-a8d9398b2ba4.png">

**Comment by ophub** [comment]
你以后更新内核时注意，内核仓库里存放的dtb是200hz的，我不确定你换成这个频率的是否可以正常从emmc启动。

修改为100-50-25hz写入emmc的盒子，我没跟踪到后续的使用反馈。也许不能使用200hz的，不然可能无法正常读写emmc，以后自己打包内核，或者自己手动移除了内核包里的同名dtb文件，这样更新内核就不会同名覆盖了。
