### ISSUE TITLE
Missing 6.1.11 release for tx3-mini(s905w) devides

### ISSUE THREAD

**Issue by piotrekcrash** [ophub/amlogic-s9xxx-armbian#1062]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095w]
 - Model [e.g. TX3 MINI]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.11]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Missing 6.1.11 release for S905W devides:
![image](https://user-images.githubusercontent.com/8939242/218741425-5c431b12-02e6-4c80-bb25-b93186d74bbe.png)

Is 6.1.11 release for S905W devices was removed for purpose?

**Comment by ophub** [comment]
The s905w series of TV Boxes only support the use of the 5.4.y/5.15.y kernel, Other types of TV Boxes can use optional kernel versions.

**Comment by piotrekcrash** [comment]
@ophub few releases before there was an image with 6.X kernel on releases that's why I was surprised it's missing now.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/730e7560c7ae92ba19f620d79e9dada67a811b0e

I missed the limitation of s905w before, and just added it to avoid using the wrong kernel version of firmware.

**Comment by piotrekcrash** [comment]
@ophub I have used image with Kernel 6.x from your previous releases and it worked fine on my Tanix TX3 Mini S905W. Is this limitation reason some instability od this Kernel on S905W devices or there's something else why 6.x Kernel is not allowed for this model?

**Comment by ophub** [comment]
cat /boot/uEnv.txt
ls-l /boot/u-boot*
cat /etc/ophub-release

For the above content, take a screenshot to see your usage in tx3-mini(s905w) 6.1.y kernel.

**Comment by ophub** [comment]
I read the feedback post on historical issues. At present, only the newly added `X96W` test u-boot is not available, and other devices support it. So I just restored some s905w devices to use u-boot, using 6.x.y and 5.10.y kernels.

**Comment by piotrekcrash** [comment]
@ophub 
![image](https://user-images.githubusercontent.com/8939242/219108269-6ecc85a6-a1e1-4f2b-93b0-32a21ac853aa.png)
![image](https://user-images.githubusercontent.com/8939242/219108355-674e1de7-e80a-4ef7-871d-e81a9bc90052.png)
![image](https://user-images.githubusercontent.com/8939242/219108519-3360036b-bb4d-47f4-90a9-e1d5ecca47e9.png)

**Comment by ophub** [comment]
Thank you for your feedback. It seems that the s905w can also use the 6.x.y series kernel. I will cancel the restrictions on it.

**Comment by donny2003** [comment]
Device Information | 设备信息

SOC: [e.g. S095w]
Model [e.g. TX3 MINI]
Armbian Version | 系统版本

Kernel Version: [e.g. 6.6.28] 安装emmc运行正常，HDMI正常，wifi没有
