### ISSUE TITLE
Armbian Debian Desktop HDMI没有声音

### ISSUE THREAD

**Issue by goooooouwa** [ophub/amlogic-s9xxx-armbian#1063]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S095l3a
 - Model CM311-1a YST

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.93
 - Release: bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

CM311安装Debian之后，armbian-software 201 安装xfce desktop，连接HDMI可以正常显示，但是没有音频。菜单栏的扬声器图标显示静音标志，点击后出现No Audio Mixer的字样。

**Comment by langyxxl** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1000
看上去和这个应该是一样的问题

**Comment by goooooouwa** [comment]
谢谢指引。

两个issue原因可能类似，但那个issue里的解决方案是安装Arch package，我是刷的Debian，用不了这个包。不知道有没有Debian对应的包可以解决问题。另外，我试过刷Jammy安装Gnome桌面，一样是没有音频输出（只有一个dummy output)，所以换固件恐怕也不解决问题。

**Comment by JFLim1** [comment]
> but there is no audio output (only one dummy output), so changing the firmware may not solve the problem.

Try run "g12_sound.sh" so far it works on Ophub's Armbian Bullseye.

**Comment by goooooouwa** [comment]
Thanks. I managed to find a 'g12_sound.sh' file [here](https://gitlab.manjaro.org/manjaro-arm/packages/community/oc4-post-install/-/blob/master/g12_sound.sh) and after run the script I now have sound (BTW, I'm using Jammy Gnome kernel 6.1.11).
