### ISSUE TITLE
杂牌S922x盒子无法驱动rtl8822cs 无线网卡和蓝牙

### ISSUE THREAD

**Issue by LondyGhost** [ophub/amlogic-s9xxx-armbian#1066]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S922x]
 - Model [e.g. cs922]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. Linux 5.15.94-flippy-82+o]
 - Release: [e.g. Armbian 23.02.0-trunk Jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

现有的外贸s922x电视盒都是搭配博通的AP6xxx 无线网卡，但是这个盒子搭配的是rtl8822cs，启动时一直检测BCM网卡失败。编译安装rtl8822又出现
make[1]: Entering directory ' /usr/s rc/L inux- headers-5.15.88 -happy- new-year'
warning: the compiler differs from the one used to build the kernel
The kernel was built by: Ubuntu clang version 14.0.6
You are using :gcc (Ubuntu 11.3.0- lubuntul~22.04) 11.3.0

现在很不知道如何解决

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1043

看这个
