### ISSUE TITLE
EAIDK610 上游DTB修复无线异常高负载和Typec不可用

### ISSUE THREAD

**Issue by lancoyan** [ophub/amlogic-s9xxx-armbian#1068]
![e46db683aadeb90a52998d3b0ff7d124](https://user-images.githubusercontent.com/52566904/219243822-a8124dd8-f937-41e6-a1e8-dcbedb361b54.jpeg)

[rk3399-eaidk-610.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10751107/rk3399-eaidk-610.dtb.zip)

![14a63ec58cd6316f5bd6aff5b6d1a815](https://user-images.githubusercontent.com/52566904/219244146-270e638f-caf3-4482-95da-97f3f514edb6.jpeg)

这是和当前s9xx项目的dtb md5对比，确实不同。

本来想pull request，不太清楚该放到哪，打扰了，我自己刷时用diskgenius替换的，已经用上啦很好用

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/rockchip/rk3399-eaidk-610.dts

上游内核源码在这里，你可以测试后提交pr

**Comment by 13584452567** [comment]
az，我已经把这个dts合并到上游了

**Comment by 13584452567** [comment]
typec的问题目前可以确定是内核内部的驱动源码有问题，但是不太清楚具体需要如何修改。目前在和kernel的这块板子的维护者讨论修改方案。

**Comment by 13584452567** [comment]
> EAIDK 610 的 Type C 不可用的问题依旧存在？我试了最近一次构建的镜像发现 Type C 仍然不可用的样子
> 
> ```
> $ uname -a
> Linux armbian 6.1.60-ophub #1 SMP Sun Oct 29 05:00:05 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux
> root@armbian:/sys/kernel/debug# lsusb
> Bus 006 Device 002: ID 05e3:0616 Genesys Logic, Inc. hub
> Bus 006 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
> Bus 005 Device 004: ID 04e2:1414 Exar Corp.
> Bus 005 Device 002: ID 05e3:0610 Genesys Logic, Inc. Hub
> Bus 005 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 002 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
> Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> Bus 004 Device 001: ID 1d6b:0001 Linux Foundation 1.1 root hub
> Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
> ```

在其他的系统上观察到fusb302正常运行，推测是仓库的固件有某些服务出现问题。
