### ISSUE TITLE
软件里面可以包含青龙面板吗？

### ISSUE THREAD

**Issue by BH9FPF** [ophub/amlogic-s9xxx-armbian#1069]
软件里面可以包含青龙面板吗？

**Comment by ophub** [comment]
网站发一下

**Comment by BH9FPF** [comment]
也是部署在docker里。我都是用“docker pull whyour/qinglong:latest”去拉这个镜像的。不知道我表述的对不对，其他老师要是有懂的，补充说明一下。

**Comment by ysuolmai** [comment]
青龙比较特别，要加的话，建议加一个版本选择，不同的人需要需要不同版本的青龙，有些人喜欢2.10.13, 有些人喜欢2.11.3，因为新版本有些库和三方外挂比如傻妞的兼容性问题。

话说O大，armbian-docker能不能做一个IP地址的判断，如果在海外不要默认加docker-accelerater(换国内源），海外用的话还得手动去改，或者给个选项要不要装加速器。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/bc3a22d82fd41a78996d9cdcb8b7b2f442cac81f

![Snip20230217_1](https://user-images.githubusercontent.com/68696949/219573277-56d29463-b8fb-41f9-aafa-f426521b073f.png)

安装完是v2.15.7

**Comment by ysuolmai** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-docker

O大佬，这不是你写的吗。。。。

![image](https://user-images.githubusercontent.com/12818757/219578539-50b732ab-2632-41c0-8f12-08383f9d1b0c.png)

**Comment by ysuolmai** [comment]
就是
```

  "registry-mirrors": [
     "https://mirror.baidubce.com/",
     "https://hub-mirror.c.163.com"
   ]
```

这段在海外是没有必要的，反而让docker pull变得很慢，但是默认就会加上

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/647a79b2c1c3a179b8a6096a8a4950b88dd2aef9

区分开了。前面选1是docker原站，选其他234是境内镜像。
