### ISSUE TITLE
X96Max_Plus2_T can not boot from usb flash

### ISSUE THREAD

**Issue by test012012** [ophub/amlogic-s9xxx-armbian#107]
Hello, I have X96Max_Plus2_T box (model name in adroid menu) with android firmware X96Max_Plus2_T_20210426-2030.

I downloaded file Armbian_22.02.0_Aml_s905x3_bullseye_5.10.98_2022.02.07.1955.img , ungziped (gzip -d) and copied to usb flash using dd if=Armbian_22.02.0_Aml_s905x3_bullseye_5.10.98_2022.02.07.1955.img  of=/dev/sdb bs=1m , then I connected usb flash drive to the STB, rebooted STB (power off, power on) and nothing happens. STB boots android, not armbian.

Can I use usb flash instead of usb hdd?

Shall I change something to use your armbian build on X96Max_Plus2_T?

Thank you in advance

**Comment by ophub** [comment]
Choose the corresponding firmware according to your box. Then write the IMG file to the USB hard disk through software such as [Rufus](https://rufus.ie/) or [balenaEtcher](https://www.balena.io/etcher/). Insert the USB hard disk into the box. Common for all Amlogic s9xxx tv box.

**Comment by test012012** [comment]
@ophub thank you for your reply. Can I use usb flash stick instead of usb hard disk?

**Comment by test012012** [comment]
@ophub 

I wrote the image Armbian_22.02.0_Aml_s905x3_bullseye_5.10.98_2022.02.07.1955.img via https://www.balena.io/etcher/ , but it didn't help. the same story, my STB boots android instead of armbian

How can I troubleshoot the issue?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-set-the-box-to-boot-from-usbtfsd

**Comment by test012012** [comment]
@ophub thanks for the link, now STB tries to boot from USB, but fails. After X96 logo I can see only black screen and then, no hdmi signal.

I've tries 4 images: openwrt 5.4,5.10; armbian (bullseye) 5.4,5.10. always the same story - black screen, then no signal from hdmi and no network traffic from LAN port

**Comment by ophub** [comment]
The black screen indicates that the usb is not recognized, please replace the usb or re-download the firmware and flash the usb

**Comment by test012012** [comment]
My usb flash is 4Gb only. Can it be the issue?

Can I use ophub images to boot from SD card? (Maybe I will find an SD card)

**Comment by ophub** [comment]
USB/TF/SD can be used, you can re-flash the usb, even if the firmware cannot be used, at least you can see the error message on the screen. There is no code on the black screen, indicating that the usb cannot be recognized for use. Or your adb in the previous step did not enable usb mode.

**Comment by test012012** [comment]
> USB/TF/SD can be used, you can re-flash the usb, even if the firmware cannot be used, at least you can see the error message on the screen. There is no code on the black screen, indicating that the usb cannot be recognized for use. Or your adb in the previous step did not enable usb mode.

Adb 'reboot update' definitely changed the behavior, because now STB tries to load from USB, but fails. Before 'reboot update' STB didn't try to load from USB and just started Android from internal rom.

**Comment by ophub** [comment]
You first try the 5.4 kernel, which is more general and does not require u-boot support.

**Comment by ophub** [comment]
Is your network card chip IP1001M? There is no driver for this card

**Comment by test012012** [comment]
> You first try the 5.4 kernel, which is more general and does not require u-boot support.

I've tried. The same story. X96 logo, then black screen, then no signal on hdmi output

Network card on my box is realtek, not ip1001m

**Comment by test012012** [comment]
Hi @ophub 

My amlogic board id is: sm1_ac213_4g.

```
franklin:/proc/device-tree $ cat amlogic-dt-id                                                                                              
sm1_ac213_4g
```

I have dumped dtb (from /deb/dtb) and splitted using this tool https://github.com/Wilhansen/aml-dtbtools.

Do you know if my board is supported by ophub images?

[dtb.tar.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/8054407/dtb.tar.gz)

**Comment by test012012** [comment]
Rufus didn't help.

I've soldered UART to the STB. Now I get boot logs (when android boots from ssd and when ophub image boots from sd card). Linux starts, but hangs after bluetooth init
[fromsd.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/8055500/fromsd.log)
[android1.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/8055501/android1.log)
[fromsd2.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/8055502/fromsd2.log)

@ophub do you have full bootlog from uart? I just want to compare what is the difference between my STB and working STB

**Comment by test012012** [comment]
![20220213_131209](https://user-images.githubusercontent.com/98887111/153752787-e0770668-f546-42bb-aaf6-a4a3ea2b66db.jpg)
![20220213_131216](https://user-images.githubusercontent.com/98887111/153752788-0264521e-6247-4d5d-9a3b-208e12cb6152.jpg)
![20220213_131224](https://user-images.githubusercontent.com/98887111/153752789-9d3c7837-393f-4f53-814b-679a072aeef3.jpg)
Photos of my stb

**Comment by test012012** [comment]
openwrt 5.4 boots up without UART normally and accessible by eth port (192.168.1.1) (hdmi output doesn't work, but it is not very important for openwrt use-cases)

**Comment by ophub** [comment]
The boot partition of OpenWrt is the same as armbian. So you can try armbian's 5.4 kernel firmware.

The firmware of 5.10 and above needs u-boot support. If you can use the 5.4 kernel, but cannot start the 5.10 kernel, it means that u-boot does not support it.

**Comment by ophub** [comment]
[meson-sm1-sei610.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-dtb/meson-sm1-sei610.dtb)

HDMI no signal is really confusing, you try another `/boot/uEnv.txt`

**Comment by ophub** [comment]
Your usb is plugged into the box to start. If the startup is successful,` you can find the ip of armbian in the connected router. `You use `ssh` to connect to the ip of armbian from the computer.

**Comment by test012012** [comment]
>The firmware of 5.10 and above needs u-boot support. If you can use the 5.4 kernel, but cannot start the 5.10 kernel, it means that u-boot does not support it.

I can start 5.10 (openwrt), but I face the issue described here https://github.com/ophub/amlogic-s9xxx-openwrt/blob/b7cb393231b8edb8ecd7375ed702d0131154baeb/router-config/README.md#109-if-you-cant-startup-after-using-the-mainline-u-boot . On my dev box I can add a resistor, but I don't want to add the resistor if it goes to production. So looks like the issue described in the page https://github.com/ophub/amlogic-s9xxx-openwrt/blob/b7cb393231b8edb8ecd7375ed702d0131154baeb/router-config/README.md#109-if-you-cant-startup-after-using-the-mainline-u-boot is also applicable for HW v4.1, not only v4.0.

armbian doesn't boot due to it hangs after bluetooth init (most probably it happens because of lack of firmware).

Sorry, but I ask you again: do you know, who compiled this u-boot to boot 5.10 kernel? Was it provided by amlogic or it was built by somebody else? If it has source code, I want to rebuild u-boot to disable 'Hit any key to stop autoboot' feature

**Comment by test012012** [comment]
> fromsd.log

armbian hangs on boot (both from usb and sd). the log is here https://github.com/ophub/amlogic-s9xxx-armbian/files/8055500/fromsd.log , it hangs after bluetooth init

**Comment by ophub** [comment]
[messages.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8055757/messages.txt)
