### ISSUE TITLE
希望能升级 uboot 版本，解决 usb3 接设备无限重启

### ISSUE THREAD

**Issue by SturdyCat** [ophub/amlogic-s9xxx-armbian#1074]
设备接 usb3 口无限重启，需要升级 uboot 版本

**Device Information | 设备信息**
 - SOC: S095x3
 - Model: tx3

**Armbian Version | 系统版本**
 - Kernel Version: Linux 6.1.12-flippy-82+
 - Release: Armbian 22.11.0-trunk Jammy

**Describe the bug | 问题描述**
![image](https://user-images.githubusercontent.com/16874676/219830325-572502cb-46e5-4fd8-ba53-7a2103f26ea9.png)
网上找到说升级 uboot 版本可以解决
https://github.com/home-assistant/operating-system/issues/1666

**Comment by ophub** [comment]
什么设备，设备上标注了多少功率，拍照

**Comment by SturdyCat** [comment]
TX3(QZ)
5V2A
u3 口外接的 RTL9210B-CG NVME 移动硬盘

**Comment by mcaptur** [comment]
I have same issue on x96air
