### ISSUE TITLE
刷完机器显示器一直提示代码

### ISSUE THREAD

**Issue by baolaimi** [ophub/amlogic-s9xxx-armbian#1075]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S09505 LB]
浪潮 ipbs9505

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]
 [bullseye]

**Describe the bug | 问题描述**
两个版本都测试了。都是这个问题。6的系统不能显示。只能黑屏
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图
![IMG_20230218_183004](https://user-images.githubusercontent.com/106135642/219856360-f28e3147-0d69-41b0-9656-35337e010211.jpg)
。

**Comment by ophub** [comment]
用5.15

**Comment by baolaimi** [comment]
两个版本都用过了。都是这个提示。有没有办法取消掉这个提示？？

**Comment by ophub** [comment]
什么提示？

**Comment by baolaimi** [comment]
系统是能进入。就是我上面这些代码一直跳出来

**Comment by ophub** [comment]
禁用无线/ap

**Comment by baolaimi** [comment]
我用rfkill block 禁用了无线跟蓝牙。依然一直跳。有没有办法可以取消掉这个跳出来的代码？？

**Comment by ophub** [comment]
armbian-config里禁用无线

**Comment by baolaimi** [comment]
刚才重新刷了6.1的问题解决了。多谢了。

**Comment by baolaimi** [comment]
> armbian-config里禁用无线
你有没有QQ或者微信啊。6.1安装后竟然第二次后就启动不起来了。不知道什么原因。5.1的这个禁用无线我也搞不定

**Comment by ophub** [comment]
你要我QQ和微信做什么？是想给我的QQ充个超级会员？我不需要赞助。

**Comment by baolaimi** [comment]
armbian-config禁用无线跟蓝牙的教程有没有？？蓝牙我看到的是安装选项。无线的看到的是连接无线点的选项。

**Comment by ophub** [comment]
#查看状态
nmcli device status

#禁用wifi
nmcli radio wifi off

#启用wifi
nmcli radio wifi on

**Comment by 13584452567** [comment]
在armbian的启动脚本里面改一下verbosity，改成0就完全不输出日志。或者改一下debug口的位置，改到别的uart上。后者的操作取决于不同设备，我没法给出具体操作方式。

**Comment by 13584452567** [comment]
如果你安装了桌面并且运行之后想在2同一个显示器切换到图形界面的话，按ctrl+alt+f2~9。具体取决于设备配置。

**Comment by baolaimi** [comment]
非常感谢。那禁用蓝牙设备用什么命令可以完成？？

**Comment by baolaimi** [comment]
6.1的这个。2.18有网络 。换成2.19的竟然没有网络。

**Comment by 13584452567** [comment]
> 非常感谢。那禁用蓝牙设备用什么命令可以完成？？

hciconfig -a可以打印蓝牙设备列表，然后使用hciconfig 你的设备名 down来关闭。

**Comment by shum-elli** [comment]
大佬您好 这个问题是由于上游内核问题引起的吗 我的r3300l也有类似问题

**Comment by 13584452567** [comment]
> 大佬您好 这个问题是由于上游内核问题引起的吗 我的r3300l也有类似问题

并不是。这个问题是boot的时候，日志输出定义和你目前链接的tty相同，同时日志参数设置的过高。
