### ISSUE TITLE
hk1box无法从emmc启动

### ISSUE THREAD

**Issue by yuanbing1010** [ophub/amlogic-s9xxx-armbian#1076]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information | 设备信息

SOC: [S095x3]
Model [hk1box]
Armbian Version | 系统版本

Kernel Version: [6.1.12 server]
Release: [Armbian_23.02.0_amlogic_s905x3_jammy_6.1.12_server_2023.02.17 ]
Describe the bug | 问题描述
可以从usb/tf卡启动armbian，并且执行armbian-install刷入emmc过程也没任何问题，但是拔掉usb/tf卡之后无法从emmc启动。

**Comment by ophub** [comment]
提示什么

**Comment by d5stick** [comment]
Burn the stock android firmware from this issue: https://github.com/ophub/amlogic-s9xxx-armbian/issues/1006
Try again after to install to EMMC.
