### ISSUE TITLE
How to use TX3-H (BZ)

### ISSUE THREAD

**Issue by irfanjunaid** [ophub/amlogic-s9xxx-armbian#1077]
**Device Information**
 - SOC: S905X3
 - Model: Tanix TX3-H
 - Config: 4GB RAM / 64GB Storage

**Armbian** 
 - Armbian Version: 23.02.0
 - Kernel Version: both - 5.15.94/6.1.12
 - Release: jammy

**Describe the bug**
Hi @ophub  First, Thank you so much for this amazing work! :+1:   🥇   I am facing an issue with my Tanix TX3-H box when booting from the USB Disk / Micro SD card. The HDMI screen is shaking/flickering while boot process. This is happening when I flash the latest armbian image to USB disk and boot from it. Is there any specific step I am missing in addition to flashing the USB disk? I tried both the kernels.

**Video:**
 - [Tanix TX3-H](https://drive.google.com/file/d/1KjOYRYG-3gor-9AwI1xYFLEzbdqp65uS/view?usp=share_link)

**Comment by ophub** [comment]
Adjust the resolution of the display and try different proportions. My tx3-h (s905x3) has been used on TV (70 inches) and computer monitor (1920 * 1080). I didn't intentionally modify the resolution. The display is normal and won't shake from side to side.

**Comment by irfanjunaid** [comment]
I tried tweaking every settings in my monitor and no change 😞  But, I have a Rock Pi 4B and noticed that its Armbian is running fine in the same monitor. Please see the video attached for reference.
Video: [Rock Pi 4B](https://drive.google.com/file/d/1Ko3KfmaDcrcmNle4gM0deocPZ0cppiOV/view?usp=share_link)
Is there any setting I can tweak in Armbian regarding this issue? The only thing I can notice is the left margin/border gap to which my monitor is trying to sync/adapt.

**Comment by irfanjunaid** [comment]
Hi @ophub After installing to EMMC, the box did not boot from it. I tried both kernels again. I made a shocking discovery! The board I have is **NOT** the **QZ** one but a different version - **TX3-H (BZ) 1B**

The network chip is **SP6330-X ZX210801**

Please advise on which dtb to use for this. The box is not booting after I install to EMMC. I tried both 512 and 514.

## Board images:

![board](https://drive.google.com/uc?export=view&id=1-NH1ibMHdEbIjPJMIq7gk9iHAiGqBv9H "Board version")

and 

![board](https://drive.google.com/uc?export=view&id=1F8jjwFVm8d94kBi8YcU-GG0mwN4sLEju "Board version")

**Comment by ophub** [comment]
What installation command options do you use, what version of the Armenian system is installed, what version of the kernel is installed, and what is the prompt of startup failure

**Comment by irfanjunaid** [comment]
> What installation command options do you use

Just gave `armbian-install` and gave 514 for bz version of my board.

> what version of the Armbian system is installed

23.02.0 on the USB disk

> what version of the kernel is installed

Tried both 5.15.94 / 6.1.12 on Jammy

> what is the prompt of startup failure

After installing to EMMC and reboot, I see just a dark blank screen. If I insert a armbian usb disk again and reboot the box, it is booting from the usb disk.

**Comment by irfanjunaid** [comment]
My wireless is working fine and I am able to run updates. I think I have erased the android when I did `armbian-install`?

If I give `armbian-install - m`  I get error
```
Invalid option [ - ]!
```

**Comment by ophub** [comment]
`armbian-install -m yes`

**Comment by irfanjunaid** [comment]
Hi @ophub Great news! After 7 attempts, finally succeeded in successfully installing the armbian. I don't know what messed up. But, I tried a combination of different USB disks, different kernels and versions. And the `armbian-install -m yes` definitely worked. So, to summarize:
 - I have to use BZ version of dtb
 - The shaky output in display is something related to my monitor 🤷‍♂️  I tried in a different monitor and it is fine
 - Install with mainline kernel with `-m` and option `514`

⚠️  **Note:** Wifi is not working in the Bullseye version but only in the Jammy version. In debian, it only shows the WiFi network name but cannot connect to it.

Other than that so far so good 👍  Thank you so much again for your help and this great work 👌  🏆 🏆 🏆

**Comment by ophub** [comment]
Thank you for sharing the use method. You are the first user of TX3 (BZ) box. Your test will help many people

**Comment by irfanjunaid** [comment]
Oh, wow! I am adding additional pics for reference:

**Armbian version:**

![](https://drive.google.com/uc?export=view&id=1prfQKEJGczqxI0Ufrn33xuVIoFMvOeNR "Armbian")

**Release:**

![](https://drive.google.com/uc?export=view&id=1KhzhZZyoaRG1x9DIKco2adt1M5yqgIfm "Armbian")

ℹ️ **Note:**
Only thing that annoys me is this network issue where a job is waiting for bring up the ethernet(eth0) interface up. It is not skipping the eth0 even though wlan0 is up. I am trying to fix this issue. The boot process can be much faster if this step is skipped. I am using Wifi and it is connected and working fine. 
![](https://drive.google.com/uc?export=view&id=1YglwCQDel_XgNDyyzjl64_nTLceolnfR "Armbian")

**Comment by EastWoodYang** [comment]
Hi @irfanjunaid , is ethernet work ?

**Comment by irfanjunaid** [comment]
Hi @EastWoodYang Yes, both WiFi and Ethernet are working.

![](https://drive.google.com/uc?export=view&id=1uZqF6ue7O6CInXVrAYiXGC0iQUEerT4R "Network")

To confirm, I even ran a ping test after disabling WiFi

![](https://drive.google.com/uc?export=view&id=1Dk1MvO5bx5BC8r3m0eCE48FdDGAqyyn4 "Network")

**Comment by h3ld3rkid** [comment]
someone can install the new luna in tanix? all tryies were fawless
i boot up armbian but cant install HA

**Comment by begimot79** [comment]
Please help, first of all, everything is working fine, thanks a lot for the work. Need help how to keep the LED display on after reboot?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/25a9cdbc049b38652791793f062c0c4e3ea9e8e2/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L45-L51
