### ISSUE TITLE
能让cm311-1盒子线刷的接口当otg接口使用么

### ISSUE THREAD

**Issue by wangtieying** [ophub/amlogic-s9xxx-armbian#1079]
我这面有otg接口这个使用需求，我看drb文件是有otg接口的，之后是不是内核没有开启这个功能，我要想开启这个功能该如何实现，在本地usr/src/这个目录下的内核源码编译的时候不行make menuconfig的时候就报错，编译环境也都安装了，或者说编译这个内核的源码可在哪下载

**Comment by ophub** [comment]
https://github.com/unifreq
