### ISSUE TITLE
PCIE SATA

### ISSUE THREAD

**Issue by dissipator** [ophub/amlogic-s9xxx-armbian#108]
我有个板子，带有PCIE的SATA接口，目前编译的armbian可以启动，但是找不到sata的ssd。请问大神，我要怎么做才能识别ssd呢？
目前在，action里做了如下修改：

 sudo ./compile.sh BOARD=${{ env.ARMBIAN_BOARD }} RELEASE=${{ env.ARMBIAN_RELEASE }} BRANCH=current \
                            BUILD_MINIMAL=no BUILD_DESKTOP=no HOST=armbian KERNEL_ONLY=no KERNEL_CONFIGURE=no \
                            CLEAN_LEVEL=make,debs COMPRESS_OUTPUTIMAGE=sha CONFIG_PCIEPORTBUS=y CONFIG_HOTPLUG_PCI_PCIE=y 

CONFIG_PCIEPORTBUS=y CONFIG_HOTPLUG_PCI_PCIE=y

**Comment by ophub** [comment]
make menuconfig 进去看看内核接口相关的选项，找到和你的匹配的启用。

**Comment by dissipator** [comment]
目前是连lspci都是空的。和硬盘的格式没关系哦

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config

这里是内核的配置，你使用make menuconfig 查看更方便点。我外接移动硬盘，SD/TF/USB都可以使用。盒子上都没PCIE插口，不确定是不是没集成。

**Comment by dissipator** [comment]
我看armbian上是写的默认PCIe 没启用。目前TF/USB都可以使用的。我在本地编译老是失败退出，目前是在git的action上编译的。

**Comment by ophub** [comment]
TF/USB/SD是可以的。
编译armbian的时候很多文件都是从github的其他用户的仓库里调用，不全在armbian的源码里。本地需要良好的网络环境，

**Comment by dissipator** [comment]
问个问题，我修改这个文件 https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config 后，编译是否就能使我修改的生效呢？

**Comment by ophub** [comment]
编译完的文件，使用更新命令可以安装到当前固件 armbian-update
把你编译好的内核放在任意目录如/opt/5.4.179，在这个目录里执行armbian-update即可使用当前目录下的内核更新。

**Comment by dissipator** [comment]
明白了。感谢。
