### ISSUE TITLE
每一次升级或者降级内核之后，就挂载不上USB了

### ISSUE THREAD

**Issue by ixxmu** [ophub/amlogic-s9xxx-armbian#1081]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

连着几个版本的内核升级或者降级之后，原本正常的外置USB就是无法自动挂载上了，导致开机失败！

恢复到原来内核，即可会恢复；同时拔掉USB之后晚几秒再插上，系统会正常开机和挂载，近半年来的版本都是如此！

**Comment by ophub** [comment]
使用blkid查看USB的uuid，在 /etc/fstab 里使用uuid挂载usb到固定路径。

**Comment by ixxmu** [comment]
> 使用blkid查看USB的uuid，在 /etc/fstab 里使用uuid挂载usb到固定路径。

谢谢大佬，换了挂载方式解决了。
