### ISSUE TITLE
s905l3a的设备写入emmc时如何使用MAINLINE_UBOOT

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#1085]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [b863av3.2-m]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.12]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

固件写入U盘能正常启动，但是写入emmc后启动时HDMI一直黑屏，想尝试使用主线UBoot试试，但是使用armbian-install -m yes 好像并没有使用主线UBoot
![image](https://user-images.githubusercontent.com/71207318/219993577-f892d1ab-b880-4207-91c8-d452d043c593.png)

**Comment by ophub** [comment]
没给他设置主线，使用了主线也没HDMI，这个盒子就这样，SSH访问管理。

**Comment by Haaooo** [comment]
> 没给他设置主线，使用了主线也没HDMI，这个盒子就这样，SSH访问管理。

O大 这个黑屏 是没有引导进系统 不是HDMI没信号。因为路由器后台没有设备，ssh自然也连不上

**Comment by ophub** [comment]
先刷安卓9，再写入emmc，搜索以前的帖子
https://github.com/ophub/kernel/releases/tag/tools

**Comment by Haaooo** [comment]
> 先刷安卓9，再写入emmc，搜索以前的帖子 https://github.com/ophub/kernel/releases/tag/tools
> 
> 按你之前的方法 #741

我都试过了，6.1的内核引导不进系统，5.15的内核会内核恐慌卡死 看来我是研究不明白了

**Comment by ophub** [comment]
换链接里提供的安卓系统了没？

**Comment by Haaooo** [comment]
> 换链接里提供的安卓系统了没？

换了  一样的状况

**Comment by ophub** [comment]
usb正常？写入emmc恐慌？

**Comment by Haaooo** [comment]
> usb正常？写入emmc恐慌？

在usb下使用6.1正常 15.5恐慌
在emmc时 6.1引导不进系统 15.5恐慌

**Comment by ophub** [comment]
内核可以更新，在线8个内核，你换其他版本的看哪个不恐慌用哪个。5.4、5.10都可以

**Comment by Haaooo** [comment]
> 内核可以更新，在线8个内核，你换其他版本的看哪个不恐慌用哪个。5.4、5.10都可以
> 
> https://github.com/ophub/kernel/tree/main/pub/stable

好的 o大  我试试

**Comment by ophub** [comment]
在USB更新，测试可以再写入
