### ISSUE TITLE
Bluetooth is not working on X96MaxPlus_2101

### ISSUE THREAD

**Issue by drafort** [ophub/amlogic-s9xxx-armbian#1086]
Model: X96MaxPlus_2101
WiFi & Bluetooth chip: FN-LINK 6222B (rtl88x2cs)

![IPC_2023-02-19 00 04 45 9580](https://user-images.githubusercontent.com/95050279/220073368-795aa650-680b-4326-b178-46756eebd368.jpg)
![IPC_2023-02-19 00 02 34 7300](https://user-images.githubusercontent.com/95050279/220073476-217d5c30-3ce6-4049-bef9-20a5e041fbcd.jpg)

![IMG_20230220_142009](https://user-images.githubusercontent.com/95050279/220093858-00c1de41-d621-41e7-95c1-e86978291a51.jpg)

Armbian: Armbian 23.02.0-trunk Jammy with Linux 6.1.12-flippy-82+
Booting from sdcard
Bluetooth already installed from armbian-config, but no Bluetooth devices found, however, on  installed ("from the box") at emmc Android 9, Bluetooth working perfectly.

![Screenshot_20230220_131451](https://user-images.githubusercontent.com/95050279/220077598-a1e3e768-16bf-461f-aaf6-c93879286c01.jpg)

![Screenshot_20230220_131507](https://user-images.githubusercontent.com/95050279/220077671-bc6d8ce8-9db7-4b9d-9280-db3bd641810f.jpg)
![Screenshot_20230220_132020](https://user-images.githubusercontent.com/95050279/220078338-9b0baac9-3397-458b-baaf-c43bdfa3e712.jpg)

**Comment by ophub** [comment]
/boot/uEnv.txt
change dtb: `meson-sm1-x96-max-plus.dtb`

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts#L185-L197

**Comment by drafort** [comment]
> /boot/uEnv.txt change dtb: `meson-sm1-x96-max-plus.dtb`
> 
> https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts#L185-L197

Thank you to reply!
Dtb changed as pointed.
Still no Bluetooth devices available
![Screenshot_20230220_154404](https://user-images.githubusercontent.com/95050279/220113144-88a22950-88d1-4e78-9a6e-574108f7ea98.jpg)
![Screenshot_20230220_154331](https://user-images.githubusercontent.com/95050279/220113235-0876f8d1-e8c0-4d89-957e-74d2821d5cfc.jpg)
![Screenshot_20230220_154419](https://user-images.githubusercontent.com/95050279/220113269-b47cd7fa-23a1-475a-bd1a-ab2fb7cc61b5.jpg)
![Uploading Screenshot_20230220_154507.jpg…]()

**Comment by ophub** [comment]
armbian-config > Network > Install Bluetooth

**Comment by drafort** [comment]
Or it's important to change Linux kernel to 5.15 from 6.1? And to use Jammy 5.15.94?

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/stable

This dtb is available in four series (5.4/5.10/5.15/6.1) kernels. You can switch freely

`armbian-update -k 5.x.y`

**Comment by drafort** [comment]
> armbian-config > Network > Install Bluetooth Support

already been installed
no devices found
![Screenshot_20230220_160014](https://user-images.githubusercontent.com/95050279/220115954-9e2994db-7cee-4b1a-9192-40a0fa04238e.jpg)
![Screenshot_20230220_154507](https://user-images.githubusercontent.com/95050279/220115993-414789d9-d0bd-46be-8400-481328b8d98b.jpg)

**Comment by ophub** [comment]
Update other series of kernels to see which can drive

**Comment by drafort** [comment]
> Update other series of kernels to see which can drive

Thanks!
I'm trying now and will give feedback here

**Comment by drafort** [comment]
> Update other series of kernels to see which can drive

Kernel was updated to 5.15.94 using armbian-update -k
Still no Bluetooth devices found.
Bluetooth support is installed from armbian-config.

![Screenshot_20230220_171411](https://user-images.githubusercontent.com/95050279/220130909-1b00549f-17cc-47d2-a115-44bca29d3c21.jpg)

**Comment by drafort** [comment]
Kernel downgraded to 5.10.168
But still no Bluetooth devices found
![Screenshot_20230220_181118_org connectbot](https://user-images.githubusercontent.com/95050279/220146507-5fe8fd8c-45e8-4574-9e91-f71c2b7f23c5.jpg)
![Screenshot_20230220_182618](https://user-images.githubusercontent.com/95050279/220146564-36bcdbc3-b1df-4939-a75b-fdcbda71c5cb.jpg)

**Comment by drafort** [comment]
Kernel was downgraded to 5.4.231
But result is the same: no Bluetooth devices found. What to do?
![Uploading Screenshot_20230220_192609.jpg…]()

**Comment by drafort** [comment]
upd:
Tried to use Debian bullseye 5.15.94 instead Ubuntu (usb flash drive and sd card)
System is not booting up with dtb "meson .... max_plus" and "meson .... max_plus_100".
Successfully started with "meson .... x96_air_1000", but still no Bluetooth devices found (Bluetooth support was installed from debian-config).
May be problem is in dtb?

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/d1a5aff412af28dc10787a76e2bcc432d39cc999

This driver is added by a third party, some people can use it, some people can't, it's unstable.
Give up if the test fails, there is no other way at present.

**Comment by drafort** [comment]
Found this:
https://forum.armbian.com/topic/25334-need-correct-dtb-for-rtl8822cs/
May be helpful

**Comment by salsabilng** [comment]
I have same tv box, im able to edit the dtb to activate the bluetooth. currently using 6.1.12 kernel

here is my dtb, extract, then replace meson-sm1-x96-max-plus.dtb in /boot/dtb/amlogic

[meson-sm1-x96-max-plus.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10801535/meson-sm1-x96-max-plus.zip)

**Comment by drafort** [comment]
Thank you!
It's more better, but errors occurred.
![Screenshot_20230222_121231](https://user-images.githubusercontent.com/95050279/220575031-d63a70ee-8597-4017-9e2b-3b9aeb5dc636.jpg)
May be I do something wrong?

**Comment by salsabilng** [comment]
maybe driver issue, not sure, try another kernel

**Comment by drafort** [comment]
> maybe driver issue, not sure, try another kernel. try to use it first, if it works, u can just ignore it

not working: no device
![Screenshot_20230222_122424](https://user-images.githubusercontent.com/95050279/220577896-effb5a7b-622b-4c7a-a1ba-244c3d4c19f7.jpg)

now I'm trying with Ubuntu 6.1 instead Debian 6.1

**Comment by salsabilng** [comment]
`sudo rfkill` , see if the bt device listed

**Comment by drafort** [comment]
> `sudo rfkill` , see if the bt device listed

yes, it listed
![Screenshot_20230222_123039](https://user-images.githubusercontent.com/95050279/220579437-8e189e3f-29ff-4e0b-bf06-1e95e04c66fe.jpg)

**Comment by salsabilng** [comment]
sorry, dont know much, try to change the kernel

**Comment by drafort** [comment]
> sorry, dont know much, try to change the kernel

Thank you! I'll try and leave feedback

**Comment by drafort** [comment]
Kernel was downgraded to 5.15.94
hci0 is disappeared from rfkill list(
Bluetooth support is installed from armbian-config
![Uploading Screenshot_20230222_135012.jpg…]()

**Comment by salsabilng** [comment]
you need to replace the dtb again.

**Comment by drafort** [comment]
> you need to replace the dtb again.

cannot start system (deb 5.15.94) with this dtb

**Comment by drafort** [comment]
I think that's driver problem. May be possible to inject to dtb this driver?https://codeberg.org/Hiyurigi/rtl88x2cs

**Comment by salsabilng** [comment]
hmm, try using bullseye 6.1.12

**Comment by salsabilng** [comment]
and use `sudo bluetoothctl`

**Comment by drafort** [comment]
> hmm, try using bullseye 6.1.12

Already tryed, used "bluetoothctl" from root.
(see upper).

![Screenshot_20230222_121231](https://user-images.githubusercontent.com/95050279/220654570-d16ffb90-680c-4039-820d-9c6689086004.jpg)
![Screenshot_20230222_123034_org connectbot](https://user-images.githubusercontent.com/95050279/220654719-e418bb4f-e169-4980-b6a6-a805543e2cac.jpg)

Or it's important to execute "bluetoothctl" from root with "sudo"?

**Comment by salsabilng** [comment]
'vei compiled new dtb, try this one 

https://github.com/salsabilng/amlogic-s9xxx-armbian/releases/download/kernel_5.15.94/5.15.94.tar.gz

**Comment by salsabilng** [comment]
then run these command

`sudo systemctl edit - - full bluetooth`
find and edit this line to 
`ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap`

then run command `sudo systemctl restart bluetooth`

check if it works, good luck

**Comment by drafort** [comment]
> 'vei compiled new dtb, try this one
> 
> https://github.com/salsabilng/amlogic-s9xxx-armbian/releases/download/kernel_5.15.94/5.15.94.tar.gz



> then run these command
> 
> `sudo systemctl edit --full bluetooth` find and edit this line to `ExecStart=/usr/lib/bluetooth/bluetoothd --noplugin=sap`
> 
> then run command `sudo systemctl restart bluetooth`
> 
> check if it works, good luck

Big thanks!!!
I'll try and leave feedback!

**Comment by drafort** [comment]
Tested with "fresh install" (from usb) armbian bullseye 5.15.94 and dtb "meson....x96_plus" from your archive above.
System cannot boot up.

**Comment by salsabilng** [comment]
use 6.1.12

**Comment by salsabilng** [comment]
by the way, ive tried many times using usb with 5.15.y kernel and older on this box, and never succeed to boot. so use 6.1.y kernel only for usb uses.

in my case, i installed the armbian into emmc, and using the mainline boot, then i can get any kernel version working,

**Comment by drafort** [comment]
> by the way, ive tried many times using usb with 5.15.y kernel and older on this box, and never succeed to boot. so use 6.1.y kernel only for usb uses.
> 
> in my case, i installed the armbian into emmc, and using the mainline boot, then i can get any kernel version working,

Thanks!
I tested 6.1.
![Screenshot_20230223_110337](https://user-images.githubusercontent.com/95050279/220851971-db3c27f8-e144-42aa-b7b2-7357dfac947f.jpg)
![Screenshot_20230223_110249](https://user-images.githubusercontent.com/95050279/220852320-bd6b7bb6-e437-4113-8394-e9ede610962e.jpg)
![Screenshot_20230223_110149](https://user-images.githubusercontent.com/95050279/220852384-fee616f7-8f96-4309-a191-921652018b72.jpg)

It's still no success.

ps. 
5.15. successfully started with dtb from X96-air-1000

**Comment by ophub** [comment]
Can Bluetooth of rtl8822cs be used? Which dtb are you using?
`cat /boot/uEnv.txt`

**Comment by salsabilng** [comment]
> > by the way, ive tried many times using usb with 5.15.y kernel and older on this box, and never succeed to boot. so use 6.1.y kernel only for usb uses.
> > in my case, i installed the armbian into emmc, and using the mainline boot, then i can get any kernel version working,
> 
> Thanks! I tested 6.1. ![Screenshot_20230223_110337](https://user-images.githubusercontent.com/95050279/220851971-db3c27f8-e144-42aa-b7b2-7357dfac947f.jpg) ![Screenshot_20230223_110249](https://user-images.githubusercontent.com/95050279/220852320-bd6b7bb6-e437-4113-8394-e9ede610962e.jpg) ![Screenshot_20230223_110149](https://user-images.githubusercontent.com/95050279/220852384-fee616f7-8f96-4309-a191-921652018b72.jpg)
> 
> It's still no success.
> 
> ps. 5.15. successfully started with dtb from X96-air-1000

i suspect because your not using mainline uboot, but eh i'm not sure

**Comment by salsabilng** [comment]
just a few hours ago, chewitt add new dts to support banana pi that has RTL8822CS, although it has different cpu, may be we can adopt the bluetooth part to the x96 max plus dts. currently i cant do it myself because i have many homework. 
@ophub @drafort 

https://github.com/chewitt/linux/commit/dc15871522d13d03268b1ab658f5e621da4f634b

**Comment by salsabilng** [comment]
i've done the changes if you still concern here is the step i through

1. i use dev 6.1.12 kernel, to get this run `armbian-update -k 6.1.12 -v dev` if you want you can try mainline boot, add `-m yes` in that command
2. replace dtb meson-sm1-x96-max-plus.dtb with this compiled dtb https://github.com/salsabilng/amlogic-s9xxx-armbian/releases/download/kernel_5.15.95/5.15.95.tar.gz
3. reboot and good luck

**Comment by salsabilng** [comment]
I've added new dtb called meson-sm1-x96-max-plus-2101.dts, this will enable the rtl8822cs bluetooth and the Wifi on 2101 box. The Wifi are stable and show no error. I have open PR on unifreq 6.1. hope it will accepted soon

https://github.com/unifreq/linux-6.1.y/pull/13

**Comment by ophub** [comment]
I left a message for him. You submitted this dts to 5.15 and the other three lts kernels

**Comment by drafort** [comment]
I'm sorry for the delay.
Thank you for help!
I'll make test today and will leave feedback

**Comment by drafort** [comment]
>Result for me:
(kernel was updated without adding  "-m yes", dtb was used as attached - for "max_plus" )
![Screenshot_20230227_185119](https://user-images.githubusercontent.com/95050279/221613332-f0f224ef-43f9-4183-939c-b23621016a5b.jpg)
As I see: no Bluetooth devices.

**Comment by salsabilng** [comment]
> I left a message for him. You submitted this dts to 5.15 and the other three lts kernels

thanks! will do,

**Comment by salsabilng** [comment]
im able to reproduce your error, it turns out only boot from emmc works. so you need to install it to emmc

**Comment by ophub** [comment]
Can bluetooth and wireless work normally?

**Comment by salsabilng** [comment]
havent tried bluetooth for transfer any files, but it can pair and discover any device. for wireless, i have decrease the max frequency, little slow but stable for couple days now

**Comment by salsabilng** [comment]
recall that i use 6.1.y kernel,

**Comment by salsabilng** [comment]
done. waiting for approval

**Comment by drafort** [comment]
As I understand it, Bluetooth will work only when system installed on EMMC. To install on emc, you must specify the type of device from "armbian-install" menu. Now 2101 is not specified in device list.
Now I tested to run 6.1 (ophub) form usb with 2101.dtb from salsabilng. In rfkill hci0 is listed, but in "hcitool dev" - no devices.

**Comment by salsabilng** [comment]
`armbian-install` , select x96-max-plus. then copy 2101 dtb to /boot/dtb/amlogic . edit uEnv.txt change line to `FDT=/dtb/amlogic/meson-sm1-x96-max-plus-2101.dtb`

**Comment by salsabilng** [comment]
i have question @ophub, whats the difference between usb and mmc boot process, why the bluetooth only works in mmc?

**Comment by ophub** [comment]
The u-boot boot sequence is different.
Generally, the situation encountered is the opposite of yours. It is normal to start and use it on the usb, but it cannot be used when writing to emmc. You have filled in the blank again.

**Comment by drafort** [comment]
Thank you!
However, is it possible to make Bluetooth work when booting from usb in the near future? Because now I need to have two systems: Android on emmc and armbian on usb.

**Comment by EmilGenov** [comment]
How to make the VDF work ? It seems that it doesn't see my VDF display? Any clue ? I would like to show the temperature)
