### ISSUE TITLE
魔百盒M411A s905l3b不知道用哪个固件，哪个大佬救救

### ISSUE THREAD

**Issue by jiucheng01** [ophub/amlogic-s9xxx-armbian#1087]
魔百盒M411A s905l3b不知道用哪个固件，哪个大佬救救

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

s905l3b 有几款，你USB里刷，改/boot/uEnv.txt看看哪个dtb可以，例如
meson-gxl-s905l3b-e900v22e.dtb
meson-gxl-s905l3b-m302a.dtb

**Comment by jiucheng01** [comment]
u盘换写过几个固件，但都不能进入跑代码阶段，卡在开机界面，过一会黑屏，不知道哪里出问题了。

**Comment by ophub** [comment]
用5.15的内核，参照上面的表，复制对应的u-boot

**Comment by ophub** [comment]
得刷安卓9以上的。

网上找你的盒子的安卓9，如果没有就下载s905l3b的其他盒子的
https://github.com/ophub/kernel/releases/tag/tools

**Comment by jiucheng01** [comment]
谢谢大佬，我试试

**Comment by worm128** [comment]
谢谢大佬，我也是m411a魔百和

**Comment by worm128** [comment]
测试了s905l3a和s905l3b的包都无法开机引导启动，都是黑屏，跪了
