### ISSUE TITLE
从root用户切换普通用户后，在明确清楚root密码的前提下(远程可直接登root) su root 输入密码不对

### ISSUE THREAD

**Issue by JiameWork** [ophub/amlogic-s9xxx-armbian#1088]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. s905l3a]

**Armbian Version | 系统版本**
 - Kernel Version: Armbian_23.02.0_amlogic__jammy_5.15.94_server_2023.02.19

**Describe the bug | 问题描述**
从root用户切换普通用户后，在明确清楚root密码的前提下(远程可直接登root) su root 输入密码不对，切换不回root，是另有什么门道吗

**Comment by JiameWork** [comment]
``` shell
root@armbian:~# su jia
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

bash: /home/jia/.bashrc: Permission denied
jia@armbian:/root$ sudo ls
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
jia@armbian:/root$ su 
Password: 
su: Authentication failure
jia@armbian:/root$ su root
Password: 
su: Authentication failure
jia@armbian:/root$ 

```

**Comment by ophub** [comment]
![Snip20230220_1](https://user-images.githubusercontent.com/68696949/220123479-89fed064-5b5f-44fe-a89c-6c6952ac3b0c.png)


你的系统权限错乱，不要在安卓系统下插入Armbian的系统盘，会被修改了权限。等adb shell reboot update执行完重启瞬间再插入，如果手慢可以拔了电源，插入U盘，再插入电源启动。如果提前把Armbian的U盘插入安卓，就会出现你这种权限被安卓修改的问题。
