### ISSUE TITLE
私家云2代，s905x支持吗

### ISSUE THREAD

**Issue by wenfer** [ophub/amlogic-s9xxx-armbian#1089]
目前刷进u盘启动进不去系统

**Comment by ophub** [comment]
刷5.15的s905x

**Comment by 7Ji** [comment]
CumeBox CM2-B 和这个盒子貌似互为克隆？我半个月前折腾过这个盒子的u-boot和bootloader：https://github.com/7Ji/u-boot/releases/tag/v2023.01-cm2-b 。这几个互为换皮的盒子基本是抄的Khadas VIM的方案所以DTB最好用`meson-gxl-s905x-khadas-vim.dtb`，用s905x-p212的其实也行。

**Comment by 7Ji** [comment]
> 目前刷进u盘启动进不去系统

应该是`boot.scr`里定义的加载点在1G以后的不合法内存的原因，这个盒子只有1G内存，用`extlinux/extlinux.conf`的话可以启动

**Comment by wenfer** [comment]
> 

万分感谢，一下就解决了我的问题

**Comment by ruleechen** [comment]
@ophub 求大佬看一下

安装armbian
- Armbian_23.11.0_amlogic_s905x_bullseye_5.15.137_server_2023.11.01.img.gz
- armbian-install 选 105

过程看起来一切正常，能从EMMC启动，只是运行一会儿之后死机，出现这些提示

![997E734A-3AC8-42B0-BDD1-E0E797E5076C_1_102_o](https://github.com/ophub/amlogic-s9xxx-armbian/assets/907369/0b55d593-6948-4c2a-9d7b-5cdf99f8f962)

**Comment by abedormancy** [comment]
@ruleechen 我也是，换了很多内核要么启不了 ，要么就跟你一样运行一段时间就报错。 😢😢

**Comment by ruleechen** [comment]
@abedormancy 我用了一个2019年的旧系统 ，终于是可以稳定跑起来（无线网卡貌似有点问题），我目前是外接了一个USB无线网卡在用
