### ISSUE TITLE
How to install Armbian to eMMC

### ISSUE THREAD

**Issue by finish475** [ophub/amlogic-s9xxx-armbian#109]
Hi !  I have an MXQ Pro 4K tvbox:
 CPU: s905W
 Wifi chip: SV6051P-TAB1741-1FM38
 Firmware on board: S905XQ4_V1.0 2017.11.23
 Nand: essencore I3T-8GQ8T2H5TARC
 I flashed Armbian_22.02.0_Alm_s905w_focal_5.4.177_2022.02.1957.img.gz to the memory card and booted successfully.
 Now, How can I install it into emmc.  I ran the command armbian-install but it gave me an error not found emmmc.
 I hope there is a method that can flash to the box's internal storage

**Comment by ophub** [comment]
This box cannot write emmc and can only be used in devices such as USB/TF/SD.

**Comment by finish475** [comment]
Thanks
