### ISSUE TITLE
求大佬适配的x96 max+ ultra S905X4 处理器的固件

### ISSUE THREAD

**Issue by 2536** [ophub/amlogic-s9xxx-armbian#1091]
求大佬适配的x96 max+ ultra S905X4 处理器的固件
![EE042A305BD1F28E8BE642FD7A6E7732](https://user-images.githubusercontent.com/28776371/220157848-73928b4a-1f36-4b8d-91e7-c92b3a029d57.jpg)
![6D09C052B2ABFF155755EC30F4D4288E](https://user-images.githubusercontent.com/28776371/220157896-1b526589-f2ed-4b8a-82d7-37d30a9d2528.jpg)
![85421A3C3DCBA0EF3230914B0485CE76](https://user-images.githubusercontent.com/28776371/220158267-3a5d7e48-e319-4839-9e8d-9879eec4643a.jpg)
![5046FD4DF15825BF08E767037A17054F](https://user-images.githubusercontent.com/28776371/220158835-b24e1dd6-a213-47c9-a57e-1a198e4c0f1e.jpg)
![57EAD3E1F6E86F704A1C502B8684B649](https://user-images.githubusercontent.com/28776371/220158873-bce3f6e4-e8be-4b74-9828-607e7b9de644.jpg)

**Comment by ophub** [comment]
主线目前还不支持s905x4
