### ISSUE TITLE
扩容相关问题

### ISSUE THREAD

**Issue by grinxxoo** [ophub/amlogic-s9xxx-armbian#1092]
armbian-tf遇到如下问题我该如何解决？
![Screenshot_2023-02-21-15-34-46-042_com.sonelli.juicessh.jpg](https://user-images.githubusercontent.com/59274108/220278495-c896c00d-fda4-4368-aa5c-ce03b3b3a2af.jpg)

!!!
[ STEPS ] Expansion Partition ...
NOCHANGE: partition 2 could only be grown by -33 [fudge=2048]
[ ERROR ] [ growpart ] operation failed.

**Comment by ophub** [comment]
`df / | tail -n1`

**Comment by ophub** [comment]
我当前启动在mmcblk2p2，无法使用。这个只支持sd/tf/usb

**Comment by grinxxoo** [comment]
> 我当前启动在mmcblk2p2，无法使用。这个只支持sd/tf/usb

原来如此 理解错意思了，我因为是用外部存储扩容系统空间呢，那就只能挂载+软路由了

**Comment by ophub** [comment]
外接设备长期使用的话，blkid查看USB的值，在/etc/fstab里面用uuid挂载

**Comment by grinxxoo** [comment]
> 外接设备长期使用的话，blkid查看USB的值，在/etc/fstab里面用uuid挂载

好的 感谢大佬解答

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/2d21ca1d5b4a12eae8d52952d1a49b8dd65ee8ae

扩容脚本我升级了下，在eMMC执行会给出禁止操作的提示。
