### ISSUE TITLE
X96 Max plus wifi driver 

### ISSUE THREAD

**Issue by SajjadSabzkar** [ophub/amlogic-s9xxx-armbian#1093]
**Device Information | 设备信息**
 - SOC: S095x3
 - Model: X96Max Plus

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Hi , i installed the app 'Device info Hw ' and i notice My wifi driver in android tv original's installed in my tvbox is `rtl8189fs`.
when i opened the tvbox i see wifi chip my device is `8189ftv` . 
On the other hand, the rtl8189fs driver is supported and developed in the unifreq kernel, so I should be able to detect wifi correctly in armbian.
is correct?

![Screenshot from 2023-02-21 17-58-07](https://user-images.githubusercontent.com/33274732/220372381-55295c12-6e96-4eb9-98d6-f38a9394fe05.png)

**Comment by ophub** [comment]
Only the third-party rtl8189fs driver is added in the 5.15 kernel. Not in 6.1.

There are 10 kinds of boxes in x96. Which one are you? Which dtb is used. Send an Android DTB.

**Comment by SajjadSabzkar** [comment]
> Only the third-party rtl8189fs driver is added in the 5.15 kernel. Not in 6.1.
> 
> There are 10 kinds of boxes in x96. Which one are you? Which dtb is used. Send an Android DTB.

[X96MAx+](https://androidtvbox.eu/x96-max-plus2-firmware-for-tv-box-with-s905x3-soc-20200901/)
X96 Max+ (2G Ram /16G Rom ; cpu : amlogic S905x3 ; sm1_ac213_2g in android used )
[dtb_x96maxplus.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10799802/dtb_x96maxplus.zip)
i use [extract-dtb](https://github.com/PabloCastellano/extract-dtb) for extract dtbs from dtb.img , and i send all file of related to dtb

**Comment by ophub** [comment]
Which dtb do you use in Armian?

**Comment by SajjadSabzkar** [comment]
> Which dtb do you use in Armian?
`meson-sm1-x96-max-plus-100m.dtb`

**Comment by ophub** [comment]
Why this? Are you a 100M wired network?

**Comment by SajjadSabzkar** [comment]
> Why this? Are you a 100M wired network?

i'm not sure , how can i sure ?
and your command output is : `config_RTL8189fs=m`

**Comment by ophub** [comment]
```
find /usr/lib/modules/$(uname -r)/kernel/drivers/net/wireless/realtek -name *8189fs*

modprobe 8189fs

dmesg | grep 8189
```

**Comment by ophub** [comment]
Are you not sure if your box is Gigabit or 100M? The dtb you use is mandatory 100M.

**Comment by SajjadSabzkar** [comment]
> ```
> find /usr/lib/modules/$(uname -r)/kernel/drivers/net/wireless/realtek -name *8189fs*
> 
> modprobe 8189fs
> 
> dmesg | grep 8189
> ```

```Feb 19 12:58:10 armbian kernel: [  108.991602] RTL871X: ERROR Dump MAC Page0 register:
Feb 19 12:58:11 armbian kernel: [  109.515059] RTL871X: Failed to init Power On!
Feb 19 12:58:11 armbian kernel: [  109.515062] RTL871X: rtw_hal_init: hal__init fail
Feb 19 12:58:11 armbian kernel: [  109.515067] RTL871X: -871x_drv - drv_open fail, bup=0
Feb 19 12:59:54 armbian kernel: [  212.670341] RTL871X: +871x_drv - drv_open, bup=0
Feb 19 12:59:54 armbian kernel: [  212.673802] RTL871X: FW does not exist before power on!!
Feb 19 12:59:54 armbian kernel: [  212.678192] RTL871X: PowerOnCheck: val_mix:0x0000063f, res:0x0000063f
Feb 19 12:59:54 armbian kernel: [  212.684347] RTL871X: PowerOnCheck: 0x100 the result of cmd52 and cmd53 is the same.
Feb 19 12:59:54 armbian kernel: [  212.691954] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 1).
Feb 19 12:59:54 armbian kernel: [  212.697651] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 2).
Feb 19 12:59:54 armbian kernel: [  212.703362] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 3).
Feb 19 12:59:54 armbian kernel: [  212.709022] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 4).
Feb 19 12:59:54 armbian kernel: [  212.714711] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 5).
Feb 19 12:59:54 armbian kernel: [  212.720411] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 6).
Feb 19 12:59:54 armbian kernel: [  212.726099] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 7).
Feb 19 12:59:54 armbian kernel: [  212.731788] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 8).
Feb 19 12:59:54 armbian kernel: [  212.737484] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 9).
Feb 19 12:59:54 armbian kernel: [  212.743180] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 10).
Feb 19 12:59:54 armbian kernel: [  212.748957] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 11).
Feb 19 12:59:54 armbian kernel: [  212.754730] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 12).
Feb 19 12:59:54 armbian kernel: [  212.760517] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 13).
Feb 19 12:59:54 armbian kernel: [  212.766294] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 14).
Feb 19 12:59:54 armbian kernel: [  212.772066] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 15).
Feb 19 12:59:54 armbian kernel: [  212.777855] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 16).
Feb 19 12:59:54 armbian kernel: [  212.783636] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 17).
Feb 19 12:59:54 armbian kernel: [  212.789402] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 18).
Feb 19 12:59:54 armbian kernel: [  212.795176] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 19).
Feb 19 12:59:54 armbian kernel: [  212.800958] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 20).
Feb 19 12:59:54 armbian kernel: [  212.806743] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 21).
Feb 19 12:59:54 armbian kernel: [  212.812529] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 22).
Feb 19 12:59:54 armbian kernel: [  212.818296] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 23).
Feb 19 12:59:54 armbian kernel: [  212.824073] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 24).
Feb 19 12:59:54 armbian kernel: [  212.829845] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 25).
Feb 19 12:59:54 armbian kernel: [  212.835619] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 26).
```

it's seems to start automatically rtl8189fs module but fails to load

**Comment by ophub** [comment]
Looks unavailable, disable wifi

**Comment by SajjadSabzkar** [comment]
> Are you not sure if your box is Gigabit or 100M? The dtb you use is mandatory 100M.

when i run `cat` sys/class/net/eth0/speed` in android  response is `10`

**Comment by SajjadSabzkar** [comment]
> Looks unavailable, disable wifi

Ok but what is solution to wifi work fine?

**Comment by ophub** [comment]
At present, there is no such driver in the kernel source code. You have tested the driver introduced from a third party and it cannot be used. Do you have any suggestions?

**Comment by SajjadSabzkar** [comment]
> At present, there is no such driver in the kernel source code. You have tested the driver introduced from a third party and it cannot be used. Do you have any suggestions?

No, actually i use this [driver](https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl8189fs) that  exist in the kernel. 
i trying to build [rtl8189fs](https://github.com/jwrdegoede/rtl8189ES_linux) from his repositories.

**Comment by ophub** [comment]
The Armian you use is compiled using this kernel repository.

**Comment by SajjadSabzkar** [comment]
Hi , i installed the [rtl8189fs](https://github.com/jwrdegoede/rtl8189ES_linux) driver and it successfully loaded. but the wifi name not in `ifconfig` command.
It seems that dtb must have a problem that it cannot list Wi-Fi.
and my dtb extract from android not able to be boot!!!

**Comment by ophub** [comment]
Android's dtb cannot be used in armbian
