### ISSUE TITLE
添加CM311-1A魔改8822cs无线网卡支持

### ISSUE THREAD

**Issue by zyd306** [ophub/amlogic-s9xxx-armbian#1098]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - Model [e.g. CM311-1A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
盒子本身不带无线，买了魔改8822cs网卡的版本，系统自带驱动，但是dtb文件没有适配，导致无线网卡不能被识别到和调用，能否添加支持，谢谢！

**Comment by ophub** [comment]
8822cs的驱动已经在内核里带了，可以自动加载，你如果已经测试了不可用用，就放弃吧。

**Comment by EvilCY** [comment]
你的解决了么，能加载网卡了么

**Comment by zyd306** [comment]
只能等dtb文件支持吧，如果dtb文件不支持，肯定解决不了。无线网卡驱动是有的，就是没有被加载。


我暂时的解决办法是用老版本的镜像启动，使用其他的USB外置双频无线网卡













在 2023-06-13 10:28:38，"EvilCY" ***@***.***> 写道：

你的解决了么，能加载网卡了么
