### ISSUE TITLE
HK1刷写Armbian到eMMC后无法启动

### ISSUE THREAD

**Issue by ghost** [ophub/amlogic-s9xxx-armbian#11]
**尝试刷写的设备**：
HK1 BOX

**尝试刷写的固件**：
`Armbian_21.11.0_Aml_s905x3_buster_5.10.75_2021.10.23.1327.img.gz`
`Armbian_21.11.0_Aml_s905x3_buster_5.4.155_2021.10.23.1329.img.gz`

**刷写步骤**：
1. 使用Etcher将固件写入优盘，
2. 优盘启动，命令行输入 `armbian-install` ，参照提示完成写入eMMC。 

**出现问题**：
先后尝试将上述两个固件写入设备的eMMC成功后，拔出优盘，重新拔出、插入电源线，启动失败。长时间等待后，显示器仍无信号输入。

更换其他作者的固件，成功写入，成功启动。
`Armbian_20.10_Aml-s9xxx_buster_5.4.108-flippy-56+o.img.xz`
[固件页面](https://www.right.com.cn/forum/thread-4076037-1-1.html)

**Comment by ophub** [comment]
Try command: `armbian-install yes`

**Comment by wangjing71** [comment]
最新的固定HK box 刷入eMMC后还是无法启动、提示成功 盒子重新插电源黑屏 logo都没有
