### ISSUE TITLE
Beelink GT1 S912 2G/32G RLT8211F no ethernet connection

### ISSUE THREAD

**Issue by tomasz-drgas** [ophub/amlogic-s9xxx-armbian#1101]
Hello,
I'm having problems getting the ethernet port on my GT1 to work. Surpassingly the WiFi (AP6255) works fine after enabling it through serial connection.
Ethernet functions properly when I boot into Android stored on the internal memory and I do get an IP address.
I suspect there's something wrong with the .dtb file, but I lack the knowledge to solve this issue on my own.

The error I'm getting (this will be displayed every few minutes on the screen):
```
meson8b-dwmac c9410000.ethernet eth0: no phy found
meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Cannot attach to PHY (error: -19)
```

So far I tried these .dtb files:
```
meson-gxm-beelink-gt1.dtb
meson-gxm-q200.dtb
meson-gxm-q201.dtb (error was different)
meson-gxm-octopus-planet.dtb
```

When I re-named `u-boot-s905x-s912.bin` or `u-boot-zyxq.bin` to `u-boot.ext` the device would get stuck during booting, so the only change I made was updating the .dtb path inside the `uEnv.txt` file.

Here's some more info that might be useful:
Release used: Armbian_23.02.0_amlogic_s912_bullseye_5.15.94_server_2023.02.22.img.gz
PCB version: GT-T_V30_20160831
Eth chip: RLT8211F

I've attached full boot log when booting with `meson-gxm-beelink-gt1.dtb`.
[bootlog-meson-gxm-beelink-gt1.dtb.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/10818661/bootlog-meson-gxm-beelink-gt1.dtb.log)

Any guidance or feedback will be appreciated.

**Comment by andarezta** [comment]
same as t96 pro,ethernet only detect after reboot update from android.if loss power tan u must reboot update again from android to detect eth0 to be working.
i set static ip from /etc/network to reduce bug like this.

**Comment by tomasz-drgas** [comment]
> same as t96 pro,ethernet only detect after reboot update from android.if loss power tan u must reboot update again from android to detect eth0 to be working. i set static ip from /etc/network to reduce bug like this.

To my surprise this actually works. I'm not sure how to `reboot update from android`, so what worked for me is as follows: load into Android (no SD card inserted), shutdown Android and wait till it's powered off, insert the Armbian SD card and power cycle the TV box. The device should load into Armbian with eth0 interface working correctly
