### ISSUE TITLE
可否添加rockchip第二种启动流程的写入方式？

### ISSUE THREAD

**Issue by 13584452567** [ophub/amlogic-s9xxx-armbian#1102]
rockchip官方有两种启动流程：
一种，就是仓库现在正在使用的，是0x40写入idbloader.img,0x4000写入u-boot.itb
另一种是0x40写入idbloader.bin,0x4000写入u-boot.img,0x6000写入trust.img
可以在编译脚本里面加一行用于写入0x6000地址的命令嘛？我发现king3399和tn3399这两个设备不使用第二种写入方法而使用第一种会导致uboot在debug口不输出日志，十分的奇怪。
或者我可以直接把0x4000和0x6000的地址打包到一起变成一个u-boot.itb，但是这样出来的文件体积会膨胀到10mb往上，可能会影响仓库自动release的速度（不过大概也就慢那么几s吧）

**Comment by ophub** [comment]
trust.img放UBOOT_OVERLOAD那列吧。你改rebuild和model_database.conf

**Comment by 13584452567** [comment]
pr已经提交。rk预留的空间是0x8000之前，可能需要跳过32MB？主要是trust.bin需要写在0x6000处。这三个文件总体积大概在8~9mb之间。

**Comment by 13584452567** [comment]
0x8000是16mb吧，这样应该就好了。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/4863bf9a6fb8948be16f71fd45c7882dbdde28c2

我调整了一下命名，第5列在Amlogic系列叫UBOOT_OVERLOAD，在Rockchip叫TRUST_IMG，这样方便大家阅读代码，避免歧义。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/4863bf9a6fb8948be16f71fd45c7882dbdde28c2/rebuild#L516

目前Rockchip跳过的是16M，如果不够用了你修改这个地方吧。
