### ISSUE TITLE
no hdmi sound begin 5.15.86

### ISSUE THREAD

**Issue by fredqian** [ophub/amlogic-s9xxx-armbian#1104]
test device: tanix tx3
software: bullseys speak-test

Armbian_22.11.0_Aml_s905x3_bullseye_5.15.71_server_2022.10.04.img 这个固件是有声音的，桌面也可以有
当前是Armbian_23.02.0_amlogic_s905x3_bullseye_5.15.94_server_2023.02.22.img，没有声音了，86版本就没有了，可以辛苦检查下。

**Comment by ophub** [comment]
看这个 https://github.com/ophub/amlogic-s9xxx-armbian/issues/1000
