### ISSUE TITLE
求一份/etc/update-motd.d里面的文件

### ISSUE THREAD

**Issue by wukibaka** [ophub/amlogic-s9xxx-armbian#1105]
如题 我不小心删掉了 导致欢迎信息系统状态显示没了

**Comment by ophub** [comment]
根据你使用的jammy或者bullseye，下载最新的armbian，刷入u盘，启动后从u盘复制

**Comment by wukibaka** [comment]
> 根据你使用的jammy或者bullseye，下载最新的armbian，刷入u盘，启动后从u盘复制

机子不在身边啊

**Comment by ophub** [comment]
什么系统？

**Comment by wukibaka** [comment]
> 什么系统？

bullseye

**Comment by ophub** [comment]
[update-motd.d.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10830652/update-motd.d.zip)
