### ISSUE TITLE
Support Amlogic's proprietary partition's natively / 原生支持晶晨私有分区格式

### ISSUE THREAD

**Issue by 7Ji** [ophub/amlogic-s9xxx-armbian#1109]
I've managed to add support of Amlogic's proprietary partitions to mainline kernel's block subsystem, it is now possible to use these partitions natively on a mainline kernel:
_dmesg_:
```
[    1.392239] mmc2: new DDR MMC card at address 0001
[    1.395820] mmcblk2: mmc2:0001 008G30 7.28 GiB 
[    1.402019]  mmcblk2: p1(bootloader) p2(reserved) p3(cache) p4(env) p5(logo) p6(recovery) p7(rsv) p8(tee) p9(crypt) p10(misc) p11(instaboot) p12(boot) p13(system) p14(params) p15(data)
[    1.418000] mmcblk2boot0: mmc2:0001 008G30 4.00 MiB 
[    1.422305] mmcblk2boot1: mmc2:0001 008G30 4.00 MiB 
[    1.426812] mmcblk2rpmb: mmc2:0001 008G30 4.00 MiB, chardev (244:0)
```
_lsblk_:
```
mmcblk2      179:32   0   7.3G  0 disk
├─mmcblk2p1  179:33   0     4M  0 part 
├─mmcblk2p2  179:34   0    64M  0 part 
├─mmcblk2p3  179:35   0   512M  0 part 
├─mmcblk2p4  179:36   0     8M  0 part 
├─mmcblk2p5  179:37   0    32M  0 part 
├─mmcblk2p6  179:38   0    32M  0 part 
├─mmcblk2p7  179:39   0     8M  0 part 
├─mmcblk2p8  179:40   0     8M  0 part 
├─mmcblk2p9  179:41   0    32M  0 part 
├─mmcblk2p10 179:42   0    32M  0 part 
├─mmcblk2p11 179:43   0   512M  0 part 
├─mmcblk2p12 179:44   0    32M  0 part 
├─mmcblk2p13 179:45   0     1G  0 part 
├─mmcblk2p14 179:46   0    64M  0 part 
└─mmcblk2p15 179:47   0   4.8G  0 part
```

The work is done on the latest kernel tree (i.e. Torvard's master branch) : https://github.com/7Ji/linux/commit/049bddc86d7e2d1a7727bbc6d268be9cf5e779d2

I don't expect this to be merged upstream so I didn't bother to follow some Linux kernel guidelines and didn't send the patch to LKML. (Will probably clean it up and send upstream latter)

At least backporting it to flippy's 6.1.13 does not need to solve any conflict, PR opend on flippy's linux-6.1.y repo but it's not merged yet: https://github.com/unifreq/linux-6.1.y/pull/12

My [linux-aarch64-flippy](https://aur.archlinux.org/packages/linux-aarch64-flippy) AUR package (mainly used for my [amlogic-s9xxx-archlinuxarm](https://github.com/7Ji/amlogic-s9xxx-archlinuxarm) project) already contains this patch, the patch could be just dropped in, at least for 6.1.13, and testing of it on various devices in my hand are all successful.

My project [ampart](https://github.com/7Ji/ampart) could be used as the user-space program to modify such partitions. You will need to call `blockdev --rereadpt -v /dev/mmcblk2` manually to reflash the layout after adjusting it, though, as ampart's current implementation does not expect the kernel could support such partitions.

If anyone wants to use this:
 - Add [the patch](https://github.com/7Ji/linux/commit/049bddc86d7e2d1a7727bbc6d268be9cf5e779d2.patch) to your kernel source, solve conflicts if there's any
 - Enable the support with `CONFIG_AMLOGIC_PARTITION=y`
 - Add `apt_blkdevs=mmcblk2` or `apt_blkdevs=all` to your kernel command line (either `/boot/extlinux/extlinux.conf` or `/boot/uEnv.txt`), it's a comma seperated list of block device names, where a special value `all`  means all block devices should be parsed

**Comment by 7Ji** [comment]
A udev rules could also be used if you want to access these partitions by their name:
https://github.com/7Ji/ampart/blob/ampart/udev/ept-links-mainline.rules

Save the above rules under `/etc/udev/rules.d`, and udev will create the symbol links under `/dev/block` automatically:
```
total 0
lrwxrwxrwx  1 root root   13 Feb 18 08:41 boot -> ../mmcblk2p12
lrwxrwxrwx  1 root root   13 Feb 18 08:41 bootloader -> ../mmcblk2p1
lrwxrwxrwx  1 root root   12 Feb 18 08:41 cache -> ../mmcblk2p3
lrwxrwxrwx  1 root root   12 Feb 18 08:41 crypt -> ../mmcblk2p9
lrwxrwxrwx  1 root root   13 Feb 18 08:41 data -> ../mmcblk2p15
lrwxrwxrwx  1 root root   12 Feb 18 08:41 env -> ../mmcblk2p4
lrwxrwxrwx  1 root root   13 Feb 18 08:41 instaboot -> ../mmcblk2p11
lrwxrwxrwx  1 root root   12 Feb 18 08:41 logo -> ../mmcblk2p5
lrwxrwxrwx  1 root root   12 Feb 18 08:41 misc -> ../mmcblk2p10
lrwxrwxrwx  1 root root   13 Feb 18 08:41 params -> ../mmcblk2p14
lrwxrwxrwx  1 root root   12 Feb 18 08:41 recovery -> ../mmcblk2p6
lrwxrwxrwx  1 root root   12 Feb 18 08:41 reserved -> ../mmcblk2p2
lrwxrwxrwx  1 root root   12 Feb 18 08:41 rsv -> ../mmcblk2p7
lrwxrwxrwx  1 root root   13 Feb 18 08:41 system -> ../mmcblk2p13
lrwxrwxrwx  1 root root   12 Feb 18 08:41 tee -> ../mmcblk2p8
```

**Comment by ophub** [comment]
原来使用ampart工具是117MB后可以使用，如果内核里添加了，是可以不用ampart支持直接使用常规方法分区？从几M后可以使用？

**Comment by 7Ji** [comment]
这种分区格式仍然是只有ampart才支持，其他分区工具不能调整。

N1等盒子的加密DTB导致的ampart不能调整dtb而拒绝工作的问题，和这个补丁无关，需要用 https://7ji.github.io/crack/2023/01/08/decrypt-aml-dtb.html 里的方法从安卓系统内提取解密的dtb再覆盖。

使用空间的问题，这个本质上没有直接解放更多的空间可以使用，只是直接把原厂的分区表暴露了出来。要用更多的话需要配合ampart调整分区。但是现在可以直接用ampart分出来的data等，不需要再手动换算mbr里的位置。

这个直接说的话有几点用途：
1. 让主线系统在eMMC上和安卓等晶晨内核的系统（包括CE/EE)并存。因为可以不建立mbr分区表。有mbr时晶晨自有的分区表会不可用，所以之前两种系统是互斥的。
2. 备份/审查eMMC上数据的时候能以分区为单位，对于扒安卓的数据来说更方便
3. 可以直接losetup -fP把eMMC的dump给设置成回环，直接识别分区表，从而直接提取对应分区的数据

**Comment by 7Ji** [comment]
另外一个是这个可以让不能建MBR的GXBB设备不需要折腾cmdline partitions

但是，即使有这个支持，普通设备安装到eMMC时，还是建议在eMMC上建立MBR。eMMC上的这个私有分区表主要是在只能以U盘启动外部系统的时候，看安卓的分区和数据更方便了。

**Comment by ophub** [comment]
armbian-install 默认优先使用 ampart 进行分区调整，几个月来使用很稳定。

**Comment by 7Ji** [comment]
这个分区支持我不建议用于安装。固有安装方案也不需要因为它做调整。建立MBR以后这个分区表就不会被内核识别了。
它最大的作用是在因为安装而建立MBR分区表之前，让用户能和安卓的数据互动。对于进阶用户可以用来折腾安卓与主线内核的共存。

**Comment by ophub** [comment]
打包固件时都会给镜像创建MBR分区表，建立MBR以后这个分区表就不会被内核识别了，那内核添加它什么时候使用呢？

**Comment by 7Ji** [comment]
比如 当前系统在外置驱动器，eMMC上是安卓时，读取安卓；或者当前系统在任意，读取设置为loop的dump里的分区信息。

这个支持是在块设备子系统上添加的，而不是限定于某个设备。

> 建立MBR以后这个分区表就不会被内核识别

是同一个块设备上GPT优先于MBR优先于APT，系统盘为MBR不影响识别其他块设备上的此分区格式

**Comment by ophub** [comment]
用于在U盘里刷armbian系统，识别emmc里安卓系统的分区情况？

**Comment by 7Ji** [comment]
其中一种用途

**Comment by ophub** [comment]
你提交的pr支持f大已经合并了

**Comment by 7Ji** [comment]
https://github.com/7Ji/ampart/commit/f05484d64f447a27b6ae11859a5efe328eaec05f

现在ampart会自动让内核重新读取分区表了，我可能在其他小更新以后打标1.3版本，这个commit构建的静态链接二进制可以在相应页面下到：

https://github.com/7Ji/ampart/actions/runs/4282070816

**Comment by hgl0110** [comment]
我安装在u盘里面的系统，之前是8G，现在变成100%使用率 2.4G了，请问如何解决啊？我用windows系统查看U盘，多出一个空闲的5.3G的分区

**Comment by 7Ji** [comment]
你的问题和这个支持有关吗？没有关系的话不要bump已经关闭的旧issue，去开一个新的

**Comment by LeeSSXX** [comment]
我移植到了5.15.y上面，也可以使用
