### ISSUE TITLE
添加对于allwinner H6的支持

### ISSUE THREAD

**Issue by 13584452567** [ophub/amlogic-s9xxx-armbian#1110]
我想为仓库添加泰奇猫的支持，但是它的uboot写入方式和现有的貌似不太兼容？下面是uboot的烧写命令
sudo dd if=u-boot-sunxi-with-spl.bin of=/dev/mmcblkX bs=8k seek=1
和rebuild里面的不太一样。

**Comment by ophub** [comment]
你知道的allwinner系列有几种常用的dd设置安排呢？

常用的u-boot方案有几个文件组合？一个spi这种是带用的方案？

现在的3列，可不可以放不同列代表不同dd方法？给allwinner的这3个列名改一下？

**Comment by 13584452567** [comment]
我知道的有两种文件排列，一种就是现在的u-boot-sunxi-with-spl.bin，另一种是sunxi-spl.bin和u-boot.itb（也可能是u-boot.bin）两个文件。
但是第一种我目前看到了好几种dd命令，有
dd if=u-boot-sunxi-with-spl.bin of=/dev/mmvblkX bs=1024 seek=8(香橙派，H3主控)
dd if=u-boot-sunxi-with-spl.bin of=/dev/mmcblkX bs=8k seek=1(泰奇猫，H6主控）
第二种文件搭配方式有
dd if=sunxi-spl.bin of=/dev/mmcblkX bs=1024 seek=8
dd if=u-boot.bin of=/dev/mmcblkX bs=1024 seek=32（A13主控）

**Comment by 13584452567** [comment]
感觉很难单靠文件名来执行，可能还需要在脚本内添加一个对于主控的判断来进行uboot的写入。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/198e31b3d8cf68d60f9d905fb65913910d12280d

我把model_database.conf里的第5项改名为：BOOTABLE，由这个来区分使用哪个dd方法
seek8 ： bs=1024 seek=8
seek1 ： bs=1024 seek=1

如果 BOOTLOADER_IMG 和 MAINLINE_UBOOT 都添加了文件走2个dd的方法

**Comment by 13584452567** [comment]
bs=8k和bs=1024一样吗？我不是很清楚

**Comment by 13584452567** [comment]
哦，是我没反应过来。实际上H3和H6都是跳过8k，所以其实就和原先一样，用文件数量区分即可。

**Comment by ophub** [comment]
真抱歉，我刚找你的文件没了，又被覆盖了，晕倒，而且我把服务器的资源拉到本地，把我一上午修改的都覆盖了。
我的意思是设置一个参数如BOOTABLE，用他的值来区分走哪条dd语句。
你更正一下这个名字叫个什么好。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/040be07eb3f3c38414cb99a8c7ac5b1f32d96cb0/rebuild#L582-L597

就是为了区分使用哪个方法。

**Comment by ophub** [comment]
稍等我再更新一个错误，然后你再提交吧，我一会提交了回复你一下。

**Comment by 13584452567** [comment]
好的

**Comment by ophub** [comment]
我更新完了，你重新拉取提交下吧

**Comment by ophub** [comment]
model_database.conf里BOOTABLE 的 seek8和seek1是我暂时起的名字和赋予的值，是为了区分dd用哪个方法。
这个名字起的不好，你更新一下名称和赋值

**Comment by ophub** [comment]
```
:MODEL          :SPL_LOCATION    :MAINLINE_UBOOT   :BOOTLOADER_IMG
:Vplus-Cloud    :early           :                 :u-boot-sunxi-with-spl.bin
:TQC-A01        :latest          :                 :u-boot-sunxi-with-spl.bin
:xxx            :NA              :u-boot.bin       :sunxi-spl.bin
```

结合你的命名，你看看这么修改如何，这个参数叫 `SPL_LOCATION` ，目前的2个盒子分别是 early 和 latest，如果有2个的可以不赋值直接走2个dd命令。如果将来有 A64 使用单u-boot文件的时候，使用这个备用选项。

**Comment by 13584452567** [comment]
很棒！
不过两个盒子虽然dd命令不一样，但是实际写入都是从8K开始写的，所以两个应该都是latest。
和官方文档里面一样写成SPL_LOAD_ADRESS吧

**Comment by ophub** [comment]
```
bs=8k seek=1    #读写8k，跳过1块
bs=1024 seek=8  #读写1k，跳过8块
```
这2个等价，那有什么区别？我晕了

**Comment by 13584452567** [comment]
应该没什么区别，我一开始也没反应过来。就结果来说都是把uboot写入到8KB处

**Comment by ophub** [comment]
```
dd --help
Usage: dd [OPERAND]...
  or:  dd OPTION
Copy a file, converting and formatting according to the operands.

  bs=BYTES        read and write up to BYTES bytes at a time (default: 512);
                  overrides ibs and obs
  cbs=BYTES       convert BYTES bytes at a time
  conv=CONVS      convert the file as per the comma separated symbol list
  count=N         copy only N input blocks
  ibs=BYTES       read up to BYTES bytes at a time (default: 512)
  if=FILE         read from FILE instead of stdin
  iflag=FLAGS     read as per the comma separated symbol list
  obs=BYTES       write BYTES bytes at a time (default: 512)
  of=FILE         write to FILE instead of stdout
  oflag=FLAGS     write as per the comma separated symbol list
  seek=N          skip N obs-sized blocks at start of output
  skip=N          skip N ibs-sized blocks at start of input
  status=LEVEL    The LEVEL of information to print to stderr;
                  'none' suppresses everything but error messages,
                  'noxfer' suppresses the final transfer statistics,
                  'progress' shows periodic transfer statistics

N and BYTES may be followed by the following multiplicative suffixes:
c=1, w=2, b=512, kB=1000, K=1024, MB=1000*1000, M=1024*1024, xM=M,
GB=1000*1000*1000, G=1024*1024*1024, and so on for T, P, E, Z, Y.
Binary prefixes can be used, too: KiB=K, MiB=M, and so on.
```
