### ISSUE TITLE
Bootloop on HK1 Box 100Mbit

### ISSUE THREAD

**Issue by jenshenk** [ophub/amlogic-s9xxx-armbian#1113]
Looking at the issues from everyone else I'm a bit jealous as I'm stuck at a more basic problem :)

I've made armbian work on other devices but after spending hours on trying to use armbian on the HK1 Box I really don't know what to do anymore and would be thankful for any ideas what I can still try or what I potentially do wrong. I tried  the 5.15 and 6.1 versions in this repository with the fitting dtb and u-boot, then started to experiment with different dtb und u-boot bins and tried all on as well SD card as USB stick. I also tried the armbian generic image with the fitting dtb and u-boot bins but whatever I try I always end up with the same experience: The box starts up, I see the HK1 logo on the screen, the blue LED lights up for a moment and then the box resets again.

**Comment by jenshenk** [comment]
Alright, so I started from scratch and gave it one last try with the dtb for sm1 tx3 bz... seems nevertheless there is a dtb labled with hk1box there might be different hk1boxes. Now together with the sm1 tx3 bz uboot the device is booting and I can ssh into it, which is all that I wanted. The display isn't working yet which would be nice to fix, but since I plan on using this box headless I do not care too much about this atm. 
I wanted to post this update for other users of hk1boxes - if there are any leads how to also get the display working, happy to hear about that :)

**Comment by ophub** [comment]
It is recommended that you use a question template to feed back the most critical question parameters, which is more critical than writing your experience with your own literary talent.

You can't find useful information from your article, such as what your soc is, which branch system you use, what your chip is, the log or screenshot of your problem, what dtb you use, and so on.
