### ISSUE TITLE
一段时间后，ssh就无法连接，网络和其他服务正常

### ISSUE THREAD

**Issue by xiaolei0125** [ophub/amlogic-s9xxx-armbian#1114]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [M401a]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.78]
 - Release: [Armbian 22.11.0-trunk Jammy] 

**Describe the bug | 问题描述**
测试多台M401, 发现每隔几天用ssh就无法连接M401A了，但M401A上的网络和其他服务都正常。
目前设备不在本地，只能让人断电重启后解决。

相关issue： 
#794 
#1016

**Comment by ophub** [comment]
/etc/init.d/ssh restart 2>/dev/null

自己添加一个计划任务，定时重启一下服务

**Comment by GD2021** [comment]
对 我的E900V22D也是
刷的最新固件[Armbian_23.05.0_amlogic_s905l3a_bullseye_5.15.104_server_2023.03.24.img.gz]
我的网络配置是：

# 设置 eth0 硬件接口
allow-hotplug eth0
auto eth0
iface eth0 inet manual

# 创建 macvlan 虚拟接口，并将其绑定到 eth0 上
allow-hotplug macvlan0
auto macvlan0
iface macvlan0 inet dhcp
        mode bridge
        mtu 1500
        hwaddress ether 42:90:a6:45:d1:2b
        parent eth0
        pre-up ip link add macvlan0 link eth0 type macvlan mode bridge address 42:90:a6:45:d1:2b
        post-down ip link del macvlan0 link eth0 type macvlan mode bridge

# 设置 loopback 接口
auto lo
iface lo inet loopback

**Comment by iJayscn** [comment]
一样有这个问题， 什么原因导致的呢？

是因为  macvlan 和 eth0 使用了相的IP？
