### ISSUE TITLE
wifi没有驱动，mirrors里面是空白的

### ISSUE THREAD

**Issue by hgl0110** [ophub/amlogic-s9xxx-armbian#1115]
**Device Information | 设备信息**
 - SOC: [e.g. s905l3a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.95]
 - Release: [e.g. jammy]
 -
amlogic_s905l3a_jammy_5.15.9和6.1.13都测试过

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
armbian安装到中兴B863AV3.1后，wifi没有驱动，mirrors里面是空的，没法换源；请教一下如何解决啊
<img width="536" alt="WechatIMG449" src="https://user-images.githubusercontent.com/126386634/221750365-10ade515-e29e-4c60-a370-6a46cdd75f69.png">
![WX20230228-120123@2x](https://user-images.githubusercontent.com/126386634/221750474-17685804-7491-41ca-9fd8-565e011092a2.png)

**Comment by ophub** [comment]
wifi没有驱动
源： /etc/apt

**Comment by hgl0110** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hgl0110** [comment]
O大，如何安装wifi驱动，驱动去哪里下载啊，有相关教程分享一下吗？还有源如何添加进去啊，我自己安装网上教程添加源，提示没有验证

**Comment by ophub** [comment]
没有驱动，无处下载。

**Comment by hgl0110** [comment]
https://github.com/CoreELEC/uwe5631-aml

请教一下o大，这个wifi驱动如何安装啊

**Comment by ophub** [comment]
安卓系统的不可用。

**Comment by hgl0110** [comment]
相同的固件，相同的方法，目前写入emmc之后，提示成功，但是重启之后要么一直都是黑屏，要么卡在一个地方不动，请问可能是那里出现了问题啊

**Comment by hgl0110** [comment]
相同的固件，相同的方法，目前写入emmc之后，提示成功，但是重启之后要么一直都是黑屏，要么卡在一个地方不动，请问可能是那里出现了问题啊，已经测试了8次了

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/741

https://github.com/ophub/kernel/releases/tag/tools

看之前的帖子测试报告，下载对应的安卓系统刷这个底包。

**Comment by hgl0110** [comment]
U盘里面的系统使用率是100% 2.4G；正常应该是7.6G多，我用windows系统查看，发现多出了一个5G多的空闲分区，请问是什么原因导致的啊，如果删除这个空闲分区，让2.4G扩容

**Comment by ophub** [comment]
armbian-tf

在U盘里使用和扩容的方法在首页就有介绍，看文档
