### ISSUE TITLE
H96pro 执行 armbian-install命令后设备直接关机

### ISSUE THREAD

**Issue by kva159** [ophub/amlogic-s9xxx-armbian#1116]
首先感谢做出这么好的镜像

 问题描述如图
![无标题](https://user-images.githubusercontent.com/33386548/221789842-f2feca01-9c2e-47dd-8c4a-f42e705f9324.png)
按选项选择完毕后执行输出
然后设备就直接关机 没有任何反应了 ，希望能解答 谢谢！
设备参数 
H96 PRO+
3（DDR4）+16G

**Comment by kva159** [comment]
首先感谢做出这么好的镜像
问题描述如图

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

参照12.16反编译一个低频的

**Comment by kva159** [comment]
你好 根据参考文档 我将max-frequency值全部改到了最低 但仍然没有变化
执行到
[ STEPS ] Start processing the BOOTFS partition...
[ INFO ] Start formatting BOOTFS partition...
mkfs.fat 4.2 (2021-01-31)
[ INFO ] Start copy BOOTFS partition data.
[ INFO ] Generate the new [ uEnv.txt ] file.
以后 设备就直接熄火

修改的内容如下   好像跟参考文档中的有点出入，为了保险起见 我将所有的max-frequency值全部改到了最低  这样应该没问题把
![无标题](https://user-images.githubusercontent.com/33386548/222136953-c7488d5f-8440-4de7-a180-81ddb4e6f695.png)

 附件是我修改的文件 我把后缀改成了txt

**Comment by kva159** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
> 
> 参照12.16反编译一个低频的

补充了一下问题 望大佬解答谢谢！！

**Comment by kva159** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
> 
> 参照12.16反编译一个低频的

大佬😂求助，折腾好几天啦，没进展

**Comment by ophub** [comment]
你把他都调整成了最高，整反了吧。让你调低，十进制的 100000000 对应的十六进制为 `0x5f5e100`

**Comment by kva159** [comment]
> 你把他都调整成了最高，整反了吧。让你调低，十进制的 100000000 对应的十六进制为 `0x5f5e100`

25000000 对应的十六进制为 0x17d7840
100000000 对应的十六进制为 0x5f5e100
它们相差一个0  0x5f5e100这个值我也试过了，没有啥变化

**Comment by ophub** [comment]
都试了如果还是写入不成，就只能在USB上使用了。

**Comment by kva159** [comment]
> 都试了如果还是写入不成，就只能在USB上使用了。

好吧，谢谢大佬！

**Comment by sxx1314** [comment]
估计是你的设备emmc有坏块吧。同设备我用23.02.0可以无压力写入，但是以前测试时就发现只能前几次可以成功启动，后面再重启就会失败，估计是这批设备通病emmc质量一般。

**Comment by PCardoso7** [comment]
> > 都试了如果还是写入不成，就只能在USB上使用了。
> 
> 好吧，谢谢大佬！

Did you manage to install? I'm having exactly the same problem... The box turns off at "Start copy BOOTFS partition data."

Tks

**Comment by kva159** [comment]
I give up

**Comment by kva159** [comment]
> > > 都试了如果还是写入不成，就只能在USB上使用了。
> > 
> > 好吧，谢谢大佬！
> 
> Did you manage to install? I'm having exactly the same problem... The box turns off at "Start copy BOOTFS partition data."
> 
> Tks
> 

I  give up

**Comment by ophub** [comment]
H96-PRO 有s912版，还有s905x3版，选择正常的系统镜像

**Comment by kriegsmarine** [comment]
Has this problem been fixed yet? I have this problem too.
same device
H96 PRO+ (blue board)

**Comment by PCardoso7** [comment]
I also gave up
