### ISSUE TITLE
微加云最新的版本都无法启动大佬解决一下

### ISSUE THREAD

**Issue by hanhavb12** [ophub/amlogic-s9xxx-armbian#1117]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. h6]
 - Model [e.g. v-plus]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
无法u盘启动

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_bullseye_02.28.0839

我修复了一下，你下载这个链接里的USB试试

**Comment by hanhavb12** [comment]
大佬还是有问题

**Comment by hanhavb12** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases
> 
> 我修复了一下，你下载最新的试试

大佬还是一样
