### ISSUE TITLE
hk1 box变种问题

### ISSUE THREAD

**Issue by fengyuanluo** [ophub/amlogic-s9xxx-armbian#1118]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1 box]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

我的hk1 box网卡是rtl8211,并且正常hk1点dtb文件无法驱动此网卡，请问是否能添加适配或我该如何修改dtb文件？

**Comment by ophub** [comment]
rtl8211f就是默认的盒子配置，这个网卡可以驱动。
cat /boot/uEnv.txt
cat /boot/u-boot*
cat /etc/ophub-release

**Comment by fengyuanluo** [comment]
好的，我试试，谢谢

**Comment by fengyuanluo** [comment]
在执行第二步后显示了满屏的@

**Comment by ophub** [comment]
第一步，把U盘插入电脑
第二步，打开刷机软件给U盘写Armbian镜像

然后电脑就满屏幕@@@@@@@@@@@@@@@@@@@@@@@@@@@？

**Comment by fengyuanluo** [comment]
不是，我已经写入了emmc，然后在armbian下执行cat /boot/u-boot*满屏@

**Comment by ophub** [comment]
`ls -l /boot/u-boot*`

**Comment by fengyuanluo** [comment]
![Screenshot_20230302_125054_com tencent mm](https://user-images.githubusercontent.com/109848252/222334175-1c348d52-5c51-4d57-b9fc-8f11bb692771.jpg)
![Uploading Screenshot_20230302_125045_com.tencent.mm.jpg…]()
![Uploading Screenshot_20230302_125041_com.tencent.mm.jpg…]()
![Uploading Screenshot_20230302_125029_com.tencent.mm.jpg…]()

**Comment by fengyuanluo** [comment]
![Screenshot_20230302_125054_com tencent mm](https://user-images.githubusercontent.com/109848252/222335628-f334264a-5985-4644-98e5-0ae916053ae9.jpg)
![Screenshot_20230302_125045_com tencent mm](https://user-images.githubusercontent.com/109848252/222335637-1941f80e-4cdd-48c8-895e-bba8b75aaf9d.jpg)
![Screenshot_20230302_125041_com tencent mm](https://user-images.githubusercontent.com/109848252/222335654-a5c39a92-6749-416c-8385-fa4416031f0b.jpg)
![Screenshot_20230302_125029_com tencent mm](https://user-images.githubusercontent.com/109848252/222335665-be3f2f86-e014-452e-9583-f12a43af9bd2.jpg)

**Comment by ophub** [comment]
你的截图显示有IP
`ifconfig`

**Comment by fengyuanluo** [comment]
ip是通过WiFi获取到的，就是WiFi能用，有线用不了

**Comment by ophub** [comment]
```
dmesg | grep -in eth

ifconfig
```

**Comment by fengyuanluo** [comment]
![Uploading Screenshot_20230302_132843_com.tencent.mm.jpg…]()
![Uploading Screenshot_20230302_132843_com.tencent.mm.jpg…]()

**Comment by fengyuanluo** [comment]
![Uploading Screenshot_20230302_132843_com.tencent.mm.jpg…]()

**Comment by fengyuanluo** [comment]
![Uploading Screenshot_20230302_132843_com.tencent.mm.jpg…]()

**Comment by ophub** [comment]
图片没上传成功吧

**Comment by fengyuanluo** [comment]
![Screenshot_20230302_223242_com tencent mm](https://user-images.githubusercontent.com/109848252/222457789-d4b983b2-0908-4ed2-af3b-ff6c68d3acb3.jpg)
![Screenshot_20230302_223218_com tencent mm](https://user-images.githubusercontent.com/109848252/222457815-5312f0db-80d8-4ac2-b135-000bf5cff288.jpg)
![Screenshot_20230302_223209_com tencent mm](https://user-images.githubusercontent.com/109848252/222457842-aa68ecf1-beb3-458c-9c70-5d6cfdafdb27.jpg)
![Screenshot_20230302_223203_com tencent mm](https://user-images.githubusercontent.com/109848252/222457861-13f06a00-760c-4a03-adef-565c01aa519b.jpg)
![Screenshot_20230302_223154_com tencent mm](https://user-images.githubusercontent.com/109848252/222457903-d64c289f-3328-419f-9c07-257b1a1d1894.jpg)
![Uploading Screenshot_20230302_132843_com.tencent.mm.jpg…]()

**Comment by fengyuanluo** [comment]
不好意思，已重新上传，不过由于docker0的部分太多，此处只上传了部分

**Comment by fengyuanluo** [comment]
???
