### ISSUE TITLE
Add LED Support on HK1 Box (S905x3)

### ISSUE THREAD

**Issue by osering** [ophub/amlogic-s9xxx-armbian#1119]
Hello!

Could you please add LED module support on HK1 Box (S905x3).

Originally it has 2 leds (blue&red) next to VFD display, but they are not active and there is no even a mentioning of 'gpio-leds' in respective dtb (for instance, older meson-gxbb-mxq-pro-plus.dtb contains it) .
When running, folder /sys/class/leds/ is empty (description of this class here https://docs.kernel.org/leds/leds-class.html).
In Armbian forum there has been discussion on "how to add leds" [https://forum.armbian.com/topic/112-dtb-howto-add-leds/]. 

In another bug report ([https://github.com/unifreq/linux-5.15.y/issues/18]) this problem is highlighted and contains even code which is allegedly missing (have not checked):

```

leds {
    compatible = "gpio-leds";
    status = "okay";
    sys_led {
        label = "sys_led";
        gpios = <0x75 0x0b 0x00>; //0x75是bank@14的phandle，注意修改自己的
        default-state = "on";
        linux,default-trigger = "default-on";
    };
};

zvfd {
    compatible = "z,vfd";
    dev_name = "zvfd";
    status = "okay";
};

```
LEDs could be used (blink, pulse/heartbeat, brightness) to indicate network/storage/cpu activity, eth speed 10/100/1000, excessive temperature (none kbd-scrolllock kbd-numlock kbd-capslock kbd-kanalock kbd-shiftlock kbd-altgrlock kbd-ctrllock kbd-altlock kbd-shiftllock kbd-shiftrlock kbd-ctrlllock kbd-ctrlrlock usbport usb-gadget usb-host disk-activity disk-read disk-write ide-disk mtd nand-disk) etc. 

P.S. Moreover it should be reassessed if commands **armbian-led** (openwrt-led) is the most appropriate and shouldn't be renamed to **armbian-vfd** or **armbian-display** and armbian-led used for led control.

Thanks for your great job on "tvbox linux"!

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/pull/38

https://github.com/ophub/amlogic-s9xxx-armbian/issues/414

This was discussed and submitted by users before, but it was not merged because the code was not standardized.

`armbian-led` can be renamed `armbian-openvfd`

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/119a734ac1069cbd76a94fbe3ce80ceb896736b2

renamed
