### ISSUE TITLE
u盘启动可用内存2G。烧录到emmc后启动，可用内存只有1G了

### ISSUE THREAD

**Issue by szliucm** [ophub/amlogic-s9xxx-armbian#112]
烧录后从emmc启动会陷入死循环：
Device 0: unknown device
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
unable to select a mode : -110
DMA reset timeout
missing environment variable: pxeuuid
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/01-fa-0f-8a-80-c6-1c
DMA reset timeout
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000000
DMA reset timeout
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000000
DMA reset timeout
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/000000
DMA reset timeout
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000

将/boot/u-boot.emmc删除后，能启动，但是内存就只有1G了。请问是什么原因，该怎么处理呢？

**Comment by ophub** [comment]
什么盒子，什么内核

**Comment by szliucm** [comment]
905x3，盒子没品牌，应该是定制的。Linux 5.4.160， u-boot-x96maxplus.bin

**Comment by ophub** [comment]
没牌子的盒子，不建议写入emmc，有的盒子不支持写入emmc使用

**Comment by xcray** [comment]
这种情况，和我之前碰到的一样：u-boot不认emmc。得找一个正确的u-boot换上，可以先用U盘测试（一定要把要测试的u-boot改名为u-boot.ext），没问题了再写入emmc，先不要写bootloader（命令行加no），写入后确保emmc的boot分区里有u-boot.emmc文件（u-boot拷过来改名）。

这样应该没问题。

至于能写入bootloader的完整版主线u-boot，属于可遇而不可求的珍品，并且每次测试写bootloader都要先做好救砖的准备。
