### ISSUE TITLE
Do not boot on Tx6 (Allwinner H6)

### ISSUE THREAD

**Issue by ngocdungvn** [ophub/amlogic-s9xxx-armbian#1120]
Please guide boot

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases

try

**Comment by ngocdungvn** [comment]
Thank you very much

**Comment by myallten** [comment]
老大  这款pendoo x6pro 刷H6的Tx6包 成功 但是网口不工作，无法获取到IP地址

**Comment by myallten** [comment]
![Uploading 微信图片_20240130215050.jpg…]()

**Comment by chanxq** [comment]
O大好！啥时候能加入tx66的外贸盒子呢？4g+32g，双频wifi，商家宣传CPU是rk3566，用瑞芯微开发工具查询chip显示是rk3568。详细信息见下图。
![读取chip](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105896395/2f3c6954-e123-4145-ac21-9a2837d33dcf)
![设备分区表](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105896395/b35ef1c5-437d-4591-8a46-7a00d0d355ac)
![读取capble](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105896395/1adb3b4b-bbc1-4860-bd8d-2e56e6c5b2f5)
![FlashInfo](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105896395/e316ceeb-1e36-4063-ad13-a2e75848628b)

**Comment by chanxq** [comment]
![tanix TX66](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105896395/80e91ef0-96e3-4f97-8d7e-18e72a6123d7)
![O1CN01oWzwp52D9HaUDTTBm_!!2216667018566-0-cib](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105896395/55581f0d-8f08-4cef-bc20-04f8324e8d26)

外贸盒子TX66的外观主要配置如图示

**Comment by mengfy3311** [comment]
大神，手上个h6的3g+128G的盒子安装Armbian_26.02.0_allwinner_tanix-tx6_trixie_6.1.159_server，系统可以跑起来，但是网卡驱动应该是没加载上，查了一下盒子网卡型号是rtl8150.麻烦大神帮忙把网卡驱动编译进去

**Comment by mengfy3311** [comment]
有人在么？

**Comment by Likob** [comment]
请问这款T95 max，也是全志H6，刷入这个T6的fnos后，网卡没有驱动，怎么解决？

<img width="527" height="492" alt="Image" src="https://github.com/user-attachments/assets/16cfd28c-3801-497d-9aae-991513510886" />

**Comment by Likob** [comment]
> 请问这款T95 max，也是全志H6，刷入这个T6的fnos后，网卡没有驱动，怎么解决？
> 
> <img alt="Image" width="527" height="492" src="https://private-user-images.githubusercontent.com/117997862/590976253-16cfd28c-3801-497d-9aae-991513510886.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Nzg3MjYzMjksIm5iZiI6MTc3ODcyNjAyOSwicGF0aCI6Ii8xMTc5OTc4NjIvNTkwOTc2MjUzLTE2Y2ZkMjhjLTM4MDEtNDk3ZC05YWFlLTk5MTUxMzUxMDg4Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDUxNFQwMjMzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTNlYmJjYjcyZGRjNWI4MmQ5ODEwNDNjZWYzMzAzZTk1ODhkMTlmMDk4OWVkMjNmYTljYTc4ODQzMzdjNmEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.cuwSsfvgu-mVq6cWRXiYqj6hZ5-iJSjU_YoRIgWS86E">

@ophub 我已经了解到这个网卡驱动是： dwmac-sun8i：全志（Allwinner）Sun8i 系列 SoC 内部集成的 MAC 控制器专用驱动，求求帮帮，我需要dwmac-sun8i

**Comment by ophub** [comment]
```
CONFIG_DWMAC_GENERIC=y
CONFIG_DWMAC_MESON=y
CONFIG_DWMAC_ROCKCHIP=y
CONFIG_DWMAC_SUNXI=y
CONFIG_DWMAC_SUN8I=y
```

https://github.com/ophub/kernel/blob/main/kernel-config/release/stable/config-6.18

https://github.com/ophub/kernel/blob/main/kernel-config/release/stable/config-6.12

这个一直都有选择。
你不能用不是config缺少，你拿别的设备的dts用在自己的设备上，不能使用是正常的，能使用是意外惊喜。需要的是适配你的设备，而不是怀疑别的设备的dts

**Comment by ophub** [comment]
6.18.y 测试正常，反馈贴：https://github.com/ophub/fnnas/issues/546#issuecomment-4449015339
