### ISSUE TITLE
r66s的网卡收包统计有bug

### ISSUE THREAD

**Issue by Xpootato** [ophub/amlogic-s9xxx-armbian#1122]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [rk3568]
 - Model [r66s]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.14]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

通过ifconfig显示的网卡rx packets是远超实际值的。
![屏幕截图 2023-03-01 160110](https://user-images.githubusercontent.com/69030034/222079300-4ea46608-54d0-46c6-92f6-4039e812c904.png)
然后这是实时网速的截图，下载速度是异常的。
![Screenshot_2023-03-01-15-56-12-837_com deskangel daremote](https://user-images.githubusercontent.com/69030034/222080557-94ce8fcc-256a-4822-95b8-365f355a7b44.jpg)
![Screenshot_2023-03-01-16-04-17-853_com deskangel daremote](https://user-images.githubusercontent.com/69030034/222080575-3cdd531a-d0e8-4a30-b6e1-92e83b58b833.jpg)
我个人的推测是r66s的内核的问题，因为我的N1盒子在同样的系统下没有出现以上问题。

**Comment by ophub** [comment]
你这是干啥活呢，有292T的流量？还是统计严重失真呢？

**Comment by Xpootato** [comment]
应该是统计失真。我的带宽是300M，下载速度最多就50MB/s，但是我看r66s网卡的网速经常会飙到几十上百G/s。

**Comment by ophub** [comment]
你觉的是ifconfig骗人了，还是你的这个漂亮的软件骗人了？你相信哪个？

**Comment by Xpootato** [comment]
我在armbian上装了nload，然后用qb随便下载个东西来测试网速，发现系统统计的流量确实有问题。
![屏幕截图 2023-03-01 191938](https://user-images.githubusercontent.com/69030034/222125909-e1de94fa-dc22-460a-8217-c50a4bc4baf9.png)

**Comment by ophub** [comment]
明显不对，不可能每秒200G

**Comment by Xpootato** [comment]
问题解决了，我把内核换成6.1.8就不会出现网速显示不正常的问题了。
