### ISSUE TITLE
安装docker出现错误

### ISSUE THREAD

**Issue by 1520316653** [ophub/amlogic-s9xxx-armbian#1124]
b863av3.2-m刷的jammy的armbian写入了emmc。armbian-update命令无法使用，安装docker也出错了
![屏幕截图 2023-03-02 131914](https://user-images.githubusercontent.com/57703347/222343527-56dbffbc-7a95-411c-8d97-bf861b2a6dfb.png)
![屏幕截图 2023-03-02 131938](https://user-images.githubusercontent.com/57703347/222343564-4e93ef34-7245-40c2-97d6-b07b3439c37b.png)
而且b863av3.2的线刷包没有开启adb和root。
大佬能不能改一下安卓的线刷包打开adb和root。要不然每次要先线刷再卡刷开启adb的卡刷包。再刷armbian

**Comment by ophub** [comment]
armbian的U盘不要插入安卓系统，会被篡改了权限。
安卓reboot后再插入，或者断电插入。
重新刷机吧，系统权限错误。
