### ISSUE TITLE
请问有何办法可以重置或查看root密码

### ISSUE THREAD

**Issue by zhiyu0215** [ophub/amlogic-s9xxx-armbian#1126]
设备信息：魔百盒cm311-1a，debian最新系统。
问题详细：这款盒子从装入系统后ssh经常隔一会就自动断开，今天连接ssh装个docker容器，频繁断开，一断开我就利用宝塔写入shell脚本重启ssh服务，连续重启几次后报错连接不上ssh，重启系统后还是连接不上，最后链接查看显示ssh密码不正确，想请问下大佬是什么原因导致它自动修改密码？可以肯定密码绝对正确，设置的纯数字。一直使用root账号未创建普通账户，装的程序确实有些多，想问下有什么办法可以保数据查看/修改root密码，或者创建公钥登录？

下边是重启ssh服务日志：
● ssh.service - LSB: OpenBSD Secure Shell server
     Loaded: loaded (/etc/init.d/ssh; generated)
     Active: active (exited) since Thu 2023-03-02 15:10:16 CST; 2h 17min ago
       Docs: man:systemd-sysv-generator(8)
    Process: 6672 ExecStart=/etc/init.d/ssh start (code=exited, status=0/SUCCESS)
    Process: 39357 ExecReload=/etc/init.d/ssh reload (code=exited, status=1/FAILURE)
        CPU: 105ms

Mar 02 17:04:01 armbian sshd[32890]: fatal: Missing privilege separation directory: /run/sshd
Mar 02 17:11:43 armbian sshd[35023]: fatal: Missing privilege separation directory: /run/sshd
Mar 02 17:28:02 armbian systemd[1]: Reloading LSB: OpenBSD Secure Shell server.
Mar 02 17:28:02 armbian ssh[39342]: Missing privilege separation directory: /run/sshd
Mar 02 17:28:02 armbian systemd[1]: ssh.service: Control process exited, code=exited, status=1/FAILURE
Mar 02 17:28:02 armbian systemd[1]: Reload failed for LSB: OpenBSD Secure Shell server.
Mar 02 17:28:03 armbian systemd[1]: Reloading LSB: OpenBSD Secure Shell server.
Mar 02 17:28:03 armbian ssh[39366]: Missing privilege separation directory: /run/sshd
Mar 02 17:28:03 armbian systemd[1]: ssh.service: Control process exited, code=exited, status=1/FAILURE
Mar 02 17:28:03 armbian systemd[1]: Reload failed for LSB: OpenBSD Secure Shell server.
● ssh.service - LSB: OpenBSD Secure Shell server
     Loaded: loaded (/etc/init.d/ssh; generated)
     Active: active (running) since Thu 2023-03-02 17:28:15 CST; 10s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 39414 ExecStart=/etc/init.d/ssh start (code=exited, status=0/SUCCESS)
      Tasks: 3 (limit: 2025)
     Memory: 3.0M
        CPU: 424ms
     CGroup: /system.slice/ssh.service
             ├─39426 sshd: /usr/sbin/sshd [listener] 1 of 10-100 startups
             ├─39430 sshd: root [priv]
             └─39431 sshd: root [net]

Mar 02 17:28:15 armbian systemd[1]: Starting LSB: OpenBSD Secure Shell server...
Mar 02 17:28:15 armbian sshd[39426]: Server listening on 0.0.0.0 port 22.
Mar 02 17:28:15 armbian sshd[39426]: Server listening on :: port 22.
Mar 02 17:28:15 armbian ssh[39414]: Starting OpenBSD Secure Shell server: sshd.
Mar 02 17:28:15 armbian systemd[1]: Started LSB: OpenBSD Secure Shell server.
Mar 02 17:28:22 armbian sshd[39430]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=222.108.73.15  user=root
Mar 02 17:28:24 armbian sshd[39430]: Failed password for root from 222.108.73.15 port 40653 ssh2
----------------------------------------------------------------------------
★[2023-03-02 17:28:25] Successful
----------------------------------------------------------------------------
● ssh.service - LSB: OpenBSD Secure Shell server
     Loaded: loaded (/etc/init.d/ssh; generated)
     Active: active (exited) since Thu 2023-03-02 17:28:15 CST; 24min ago
       Docs: man:systemd-sysv-generator(8)
        CPU: 4.782s

Mar 02 17:42:22 armbian sshd[51046]: error: Received disconnect from 192.168.1.6 port 49288:3: java.lang.NullPointerException [preauth]
Mar 02 17:42:22 armbian sshd[51046]: Disconnected from authenticating user root 192.168.1.6 port 49288 [preauth]
Mar 02 17:42:24 armbian sshd[51095]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.1.6  user=root
Mar 02 17:42:25 armbian sshd[51095]: Failed password for root from 192.168.1.6 port 49289 ssh2
Mar 02 17:42:26 armbian sshd[51095]: error: Received disconnect from 192.168.1.6 port 49289:3: java.lang.NullPointerException [preauth]
Mar 02 17:42:26 armbian sshd[51095]: Disconnected from authenticating user root 192.168.1.6 port 49289 [preauth]
Mar 02 17:42:31 armbian sshd[51176]: pam_unix(sshd:auth): authentication failure; logname= uid=0 euid=0 tty=ssh ruser= rhost=192.168.1.6  user=root
Mar 02 17:42:33 armbian sshd[51176]: Failed password for root from 192.168.1.6 port 49291 ssh2
Mar 02 17:42:35 armbian sshd[51176]: error: Received disconnect from 192.168.1.6 port 49291:3: java.lang.NullPointerException [preauth]
Mar 02 17:42:35 armbian sshd[51176]: Disconnected from authenticating user root 192.168.1.6 port 49291 [preauth]
● ssh.service - LSB: OpenBSD Secure Shell server
     Loaded: loaded (/etc/init.d/ssh; generated)
     Active: active (running) since Thu 2023-03-02 17:52:56 CST; 10s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 60031 ExecStart=/etc/init.d/ssh start (code=exited, status=0/SUCCESS)
      Tasks: 1 (limit: 2025)
     Memory: 1.0M
        CPU: 108ms
     CGroup: /system.slice/ssh.service
             └─60041 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups

Mar 02 17:52:56 armbian systemd[1]: Starting LSB: OpenBSD Secure Shell server...
Mar 02 17:52:56 armbian sshd[60041]: Server listening on 0.0.0.0 port 22.
Mar 02 17:52:56 armbian sshd[60041]: Server listening on :: port 22.
Mar 02 17:52:56 armbian ssh[60031]: Starting OpenBSD Secure Shell server: sshd.
Mar 02 17:52:56 armbian systemd[1]: Started LSB: OpenBSD Secure Shell server.
----------------------------------------------------------------------------
★[2023-03-02 17:53:06] Successful
----------------------------------------------------------------------------
● ssh.service - LSB: OpenBSD Secure Shell server
     Loaded: loaded (/etc/init.d/ssh; generated)
     Active: inactive (dead)
       Docs: man:systemd-sysv-generator(8)
● ssh.service - LSB: OpenBSD Secure Shell server
     Loaded: loaded (/etc/init.d/ssh; generated)
     Active: active (running) since Thu 2023-03-02 18:20:47 CST; 10s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 11871 ExecStart=/etc/init.d/ssh start (code=exited, status=0/SUCCESS)
      Tasks: 1 (limit: 2025)
     Memory: 2.0M
        CPU: 112ms
     CGroup: /system.slice/ssh.service
             └─11883 sshd: /usr/sbin/sshd [listener] 0 of 10-100 startups

Mar 02 18:20:47 armbian systemd[1]: Starting LSB: OpenBSD Secure Shell server...
Mar 02 18:20:47 armbian ssh[11871]: Starting OpenBSD Secure Shell server: sshd.
Mar 02 18:20:47 armbian sshd[11883]: Server listening on 0.0.0.0 port 22.
Mar 02 18:20:47 armbian sshd[11883]: Server listening on :: port 22.
Mar 02 18:20:47 armbian systemd[1]: Started LSB: OpenBSD Secure Shell server.
----------------------------------------------------------------------------
★[2023-03-02 18:20:57] Successful

**Comment by zhiyu0215** [comment]
除去u盘重装有什么别的办法可以解决吗？刚u盘烧录了最新debian系统，插入盒子各种报错进不去debian界面

**Comment by Doboo** [comment]
用U盘启动盒子
挂载
mkdir /123456
mount /dev/mmcblk2p2 /123456
修改密码
nano /123456/etc/shadow1234的密码
root:$y$j9T$zdbDJyCv.61hxVdVkDGvi.$GC/EmtJxdR6nPTM9/HN5QbcyVoCHCe8B2sOT1ZKJZ27:19278:0:99999:7:::sync
再 sync 同步写入磁盘
再 加电启动到emmc里的系统，登录root，密码是1234

**Comment by chen-jia-hao** [comment]
> 用U盘启动盒子 挂载 mkdir /123456 mount /dev/mmcblk2p2 /123456 修改密码 nano /123456/etc/shadow 1234的密码如下 root:$y$j9T$zdbDJyCv.61hxVdVkDGvi.$GC/EmtJxdR6nPTM9/HN5QbcyVoCHCe8B2sOT1ZKJZ27:19278:0:99999:7:::sync 再 sync 同步写入磁盘 再 加电启动到emmc里的系统，登录root，密码是1234

没密码进不去armbian了怎么用u盘启动，我试了用adb连不上，没法用adb去改u盘启动。

**Comment by ailisha163** [comment]
> 用U盘启动盒子 挂载 mkdir /123456 mount /dev/mmcblk2p2 /123456 修改密码 nano /123456/etc/shadow 1234的密码如下 root:$y$j9T$zdbDJyCv.61hxVdVkDGvi.$GC/EmtJxdR6nPTM9/HN5QbcyVoCHCe8B2sOT1ZKJZ27:19278:0:99999:7:::sync 再 sync 同步写入磁盘 再 加电启动到emmc里的系统，登录root，密码是1234

请问如何延长root登录的时效呢，看sshd_config也都是正常设置的永不失效，但固件ssh一段时间不登录，密码就自动失效了，就得按上边方法重新设置一下，想请教下如何固化密码做到永久有效呢？求教，谢谢。
