### ISSUE TITLE
魔百盒M401A声卡异常

### ISSUE THREAD

**Issue by VillagerTom** [ophub/amlogic-s9xxx-armbian#1129]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095l3a]
 - Model [魔百盒 M401A 江苏版]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.96]
 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
hardinfo显示声卡型号为 axg-sound-card - U200
![截图_2023-03-03_22-08-10.png](https://user-images.githubusercontent.com/89803422/222746933-99c6cd0e-2a22-4ac0-8815-7b2edfaacac2.png)

pavucontrol显示 没有可用来配置的声卡
![截图_2023-03-03_22-23-39.png](https://user-images.githubusercontent.com/89803422/222747541-56540513-6dc1-47ec-8cc2-7a9cf0865e03.png)

切换tty不停报错
```
fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
fe.dai-link-0: ASoC: dpcm_fe_dai_prepare() failed (-22)
```

**Comment by VillagerTom** [comment]
我该怎么进一步排查问题？

**Comment by langyxxl** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1000

**Comment by VillagerTom** [comment]
> #1000

感谢，我去刷 archlinux arm （

**Comment by VillagerTom** [comment]
#1063

**Comment by VillagerTom** [comment]
Archlinux 太难刷了，又滚回来了我😭

**Comment by ophub** [comment]
Armbian 欢迎你回家，哈哈
