### ISSUE TITLE
MXQ 4K driver installation problem

### ISSUE THREAD

**Issue by Shtopor89** [ophub/amlogic-s9xxx-armbian#1133]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905]
 - Model [e.g. MXQ 4K, 1GB]
 - USED meson-gxbb-beelink-mini-mx.dtb
 - meson-gxbb-mxq-pro-plus.dtb - doesn't work.

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.92 upgraded to 5.15.96]
 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Good day!

Sorry, I'm a novice in Ubuntu, but I need it for 3d Printer Klipper, so I have to spend a lot of time to find the issue with no luck to solve it.

So, when installing Realtek WiFi drivers for:

rtl8821cu (https://media.dlink.eu/support/products/dwa/dwa-171/driver_software/dwa-171_fw_revc1_3-03_eu_multi_20200916.zip) 
or
rtl8189es (https://github.com/jwrdegoede/rtl8189ES_linux),

 I used put this prompt to install it:

root@armbian:/home/shtopor/build/rtl8821CU# sudo make -j4 ARCH=arm64 CC=clang LD=ld.lld KSRC=/usr/src/linux-headers-5.15.96-flippy-82+o/

Without ARCH=arm64 CC=clang the process doesn't strart at all (no directory found) or says that core is made with clang and not gcc.
Without LD=ld.lld command gives error that unknown compile with LLVM.
So above lines seemed to me +/- correct.

But after long compilation, this gives the next error in the end (Libc.co.6 file not found):

![image](https://user-images.githubusercontent.com/126978628/222921909-3e20c8fc-890a-4f65-a74a-c95165dcc306.png)

Libc.co.6 file is present in /usr/lib/aarch64-linux-gnu

Next versions of Libc are installed:
![image](https://user-images.githubusercontent.com/126978628/222922064-e0f7cc31-2387-43f1-ba0d-1bf9c43a1dcb.png)

Ldconfig:

![image](https://user-images.githubusercontent.com/126978628/222922179-4eed44bf-30d2-4777-b4a7-0592ba9aa2a7.png)

Location of files:
![image](https://user-images.githubusercontent.com/126978628/222922306-a3e792c3-70c6-48bf-b572-2bef36b31a3b.png)

Links seems fine:
![image](https://user-images.githubusercontent.com/126978628/222922419-442b4825-0a26-46fb-a5b2-4be4ba00265c.png)

I also copied Libc.co.6 from 
/usr/lib/aarch64-linux-gnu 
to 
/usr/lib
as file and also tried to copy as link.

The error remains.

I tried to copy another file to 
/usr/lib
from 
/usr/arm-linux-gnueabihf/lib - but this is likely to be 32-bit file, and this results in error: wrong ELF class: ELFCLASS32.

So actually there is a reaction on file located in /usr/lib. 
But when I locate proper file from /usr/lib/aarch64-linux-gnu, modpost results in error.

The same error happens with different versions of drivers. Please help!

**Comment by ophub** [comment]
Tip: The s905 TV Boxes can only be used in TF/SD/USB, other types of TV Boxes also support writing to EMMC.

**Comment by ophub** [comment]
see: https://github.com/ophub/amlogic-s9xxx-armbian/issues/1043
