### ISSUE TITLE
CM311-1A，armbian无法正常启动，总是各种问题

### ISSUE THREAD

**Issue by qkl9527** [ophub/amlogic-s9xxx-armbian#1135]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S095l3a
 - Model: CM311-1A YS(S)  2G+16G
 - 安卓rom：CM311-1a_ss_new.img

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.96
 - Release: Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.96_server_2023.03.03.img

**Describe the bug | 问题描述**

1，尝试过多个N盘和多个不同版本的都有各种问题
2，截图的是以上填写的版本的错误截图
![image](https://user-images.githubusercontent.com/35894136/222962459-9a8216de-a9f9-413e-a18a-9f83e9c52a62.png)
![8927e312484c9b1349768f6ea01d6e6](https://user-images.githubusercontent.com/35894136/222962468-7d8df93d-41a4-46c9-910f-3962acf14144.jpg)

3，以下是其他版本系统的错误截图
![1e5c0e64a830a87464bafa852bde3e6](https://user-images.githubusercontent.com/35894136/222962415-975cc32e-224e-4137-a125-fbd617d9f589.jpg)
![06e63a91742c799fb10e4914e4d95cd](https://user-images.githubusercontent.com/35894136/222962496-a8b83ea6-272f-4be5-bcde-118c93b23073.jpg)
![75ec4b6cb08966ff82756b3ed1d59b5](https://user-images.githubusercontent.com/35894136/222962504-e29b1d27-7dd3-4374-8e6a-3aaf97456c8a.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

把安卓系统先刷成这里下载的

**Comment by qkl9527** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 把安卓系统先刷成这里下载的

是按下面操作方式吗？

1，先刷这个安卓rom
2，然后插U盘启动

**Comment by ophub** [comment]
对，U盘不要插入安卓系统下，会被安卓篡改了系统权限无法正常运行。
拔电，插U盘启动。或者安卓里执行`adb reboot update`命令后，盒子重启时再插入。

**Comment by qkl9527** [comment]
> 对，刷有Armbian系统的U盘不要插在安卓系统下，会被安卓篡改了系统权限无法正常运行。 拔电，插U盘启动。或者安卓里执行`adb reboot update`命令后，盒子重启时再插入。

我看下载的包里教程说，不要勾选【擦除flash】和【擦除bootloader】 刷机吗？

**Comment by ophub** [comment]
断电，插U盘，插电开机

**Comment by qkl9527** [comment]
> 断电，插U盘，插电开机

好的，感谢老大，我重新来尝试下

**Comment by qkl9527** [comment]
刚重新刷了rom，然后断电，拔电源，插U盘（新写的armbian），没有引导U盘，进入了安卓系统

**Comment by qkl9527** [comment]
> 刚重新刷了rom，然后断电，拔电源，插U盘（新写的armbian），没有引导U盘，进入了安卓系统

我按老大的意思，多尝试几次试试，再来咨询，反正就是不能U盘插在安卓启动后的系统下这个原则来尝试

**Comment by ophub** [comment]
你没插网线吧

**Comment by ophub** [comment]
内存错误添加u-boot即可。看文档里有说明
