### ISSUE TITLE
斐讯t1开机时间过长，显示failed to start Raise network interfaces

### ISSUE THREAD

**Issue by SVIPNB** [ophub/amlogic-s9xxx-armbian#1137]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: s912
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.98
 - Release: Armbian_23.02.0_amlogic_s912-m8s_jammy_5.15.98_server_2023.03.05.img.gz

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
斐讯t1刷了s912–m8s内核5.15.98的固件，并把uExt.txt改成t1.dtb。开机时间过长，好像是每次开机验证引导程序时间过长，显示failed to start Raise network interfaces
![IMG_20230306_014913](https://user-images.githubusercontent.com/105286806/223041457-f3767e3c-15e1-485e-85e7-ab17a974c323.jpg)
![IMG_20230306_014914](https://user-images.githubusercontent.com/105286806/223041509-d46be914-4686-4571-8971-0a6b95f0a449.jpg)

**Comment by ophub** [comment]
wifi不用就禁用了，省去等待时间

**Comment by ophub** [comment]
这是显示没插网线，等待你插入

**Comment by SVIPNB** [comment]
好的好的，多谢
