### ISSUE TITLE
百视通R3300L从tf卡启动不正常

### ISSUE THREAD

**Issue by JersonWu** [ophub/amlogic-s9xxx-armbian#1138]
3月2日23.02.0版本，写入tf卡后不做任何调整可以启动系统，但会出现大量mmc erase error （-110），如果有读取或写入操作，则系统失去响应，输入任何命令包括reboot都返回找不到命令。但将tf卡插入usb读卡器接入usb口则启动、使用一切正常。奇怪的问题。
另外，新的4.x以后的内核似乎对tf读卡器支持不是很理想，有一个8G（Nokia）tf卡使用armbian 5.44系统一切正常，但新的系统均无法启动，多数情况下直接提示找不到引导文件，少数时候会去读取kernel文件，然后出错。不过使用USB读卡器转换到usb口启动都没有问题。

**Comment by JersonWu** [comment]
问题补充：如果将u-boot-r3300l.bin文件重命名为u-boot.ext文件（使用extlinux.conf），则无法从tf卡启动，显示输出一直停留在android标志界面。此时将tf卡装入usb读卡器插入usb接口仍然可以正常启动运行

**Comment by wuxs** [comment]
我也碰到类似情况，将系统写入emmc后，开机过一会就会特别卡，很多命令无响应，reboot 命令无效，内核是 5.15.98

**Comment by JersonWu** [comment]
5.10、5.15内核都使用过。5.10内核直接无法从tf卡启动，5.15内核就是上边的问题。使用usb接口则一切正常。

**Comment by JersonWu** [comment]
Armbian_23.05.0_amlogic_s905lb-r3300l_bullseye_5.15.105_server_2023.04.02.img 这个版本可以正常从TF卡启动了，ext方式也可以，只是相比USB方式android启动界面停留的时间略长两秒钟。是否usb启动优先级要高一些？另外挑卡的问题似乎无解，所有4.x内核以后的版本均无法使用老的Nokia卡启动，东芝卡正常。
