### ISSUE TITLE
R68S刷入armbian无法启动，观察TTL出现Unknown command '����' - try 'help'报错

### ISSUE THREAD

**Issue by elfinyuki** [ophub/amlogic-s9xxx-armbian#1139]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: RK3568
 - Model: R68S

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: Armbian_23.02.0_rockchip_r68s_bullseye_6.1.15_server_2023.03.05.img

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

刷入Armbian后无反应，拆机连接TTL后观察输出发现U-Boot报错
报错日志如下

```

U-Boot 2017.09 (Apr 29 2022 - 16:12:03 +0800)

Model: Rockchip RK3568 Evaluation Board
PreSerial: 2, raw, 0xfe660000
DRAM:  4 GiB
Sysmem: init
Relocation Offset: ed34b000
Relocation fdt: eb9f87c8 - eb9fece8
CR: M/C/I
Using default environment

dwmmc@fe2b0000: 1, dwmmc@fe2c0000: 2, sdhci@fe310000: 0
Bootdev(atags): mmc 0
MMC0: HS200, 200Mhz
PartType: EFI
DM: v1
No misc partition
boot mode: None
FIT: No boot partition
No resource partition
No resource partition
Failed to load DTB, ret=-19
Failed to get kernel dtb, ret=-19
io-domain: OK
Failed to get scmi clk dev
Model: Rockchip RK3568 Evaluation Board
rockchip_set_serialno: could not find efuse/otp device
CLK: (sync kernel. arm: enter 816000 KHz, init 816000 KHz, kernel 0N/A)
  apll 816000 KHz
  dpll 780000 KHz
  gpll 1188000 KHz
  cpll 1000000 KHz
  npll 24000 KHz
  vpll 24000 KHz
  hpll 24000 KHz
  ppll 200000 KHz
  armclk 816000 KHz
  aclk_bus 150000 KHz
  pclk_bus 50000 KHz
  aclk_top_high 300000 KHz
  aclk_top_low 200000 KHz
  hclk_top 150000 KHz
  pclk_top 50000 KHz
  aclk_perimid 300000 KHz
  hclk_perimid 150000 KHz
  pclk_pmu 100000 KHz
No misc partition
Net:   No ethernet found.
Hit key to stop autoboot('CTRL+C'):  0 
Could not find misc partition
ANDROID: reboot reason: "(none)"
optee api revision: 2.0
TEEC: Waring: Could not find security partition
Not AVB images, AVB skip
android_image_load_by_partname: Can't find part: boot
Android image load failed
Android boot failed, error -1.
## Booting FIT Image FIT: No boot partition
FIT: No FIT image
Could not find misc partition
Could not find primary part
MMC error: The cmd index is 1, ret is -110.....
Card did not respond to voltage select!
mmc_init: -95, time 13
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
3252 bytes read in 51 ms (61.5 KiB/s)
## Executing script at 00c00000
Unknown command '����' - try 'help'
SCRIPT FAILED: continuing...
starting USB...
Bus dwc3@fcc00000: usb maximum-speed not found
Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
Bus dwc3@fd000000: usb maximum-speed not found
Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
scanning bus dwc3@fcc00000 for devices... 1 USB Device(s) found
scanning bus dwc3@fd000000 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device
No ethernet found.
missing environment variable: pxeuuid
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/000000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-rockchip
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default
No ethernet found.
Config file not found
No ethernet found.
=> 

```

已经严格按照wiki内的刷机方法操作

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看8.2.3，如过现在emmc里有别的系统，先擦除再写入armbian

**Comment by elfinyuki** [comment]
我是严格按照8.2.3操作的，已经在高级选项里擦除过，而且其他能找到的工具也都试过了

**Comment by 13584452567** [comment]
在v2017-uboot命令行下尝试mmc erase 0x40 2和mmc erase 0x4000 10 
这两个命令会破坏现有的uboot，然后重新卡启，即可正常进入系统。

**Comment by elfinyuki** [comment]
> mmc erase 0x4000 10

尝试过了，依旧无效

**Comment by elfinyuki** [comment]
> 在v2017-uboot命令行下尝试mmc erase 0x40 2和mmc erase 0x4000 10 这两个命令会破坏现有的uboot，然后重新卡启，即可正常进入系统。

刚才尝试过了，报错依旧

**Comment by 13584452567** [comment]
断电了吗？还是用的reboot命令。
不行就按住loader键开机，会进maskrom模式，然后再断电重新上电。

**Comment by elfinyuki** [comment]
> 断电了吗？还是用的reboot命令。 不行就按住loader键开机，会进maskrom模式，然后再断电重新上电。

两者都试过，以及进去的依旧是原先的uboot

**Comment by 13584452567** [comment]
下载这个文件[update.7z](https://t.wss.ink/f/aoabuzdrsla)，解压出一个img，在AndroidTools里面的升级固件标签页，点击固件按钮然后加载解压出来的img，之后会识别出loader版本，然后点击擦除flash，然后再按照正常流程进行卡启。

**Comment by elfinyuki** [comment]
> 下载这个文件[update.7z](https://t.wss.ink/f/aoabuzdrsla)，解压出一个img，在AndroidTools里面的升级固件标签页，点击固件按钮然后加载解压出来的img，之后会识别出loader版本，然后点击擦除flash，然后再按照正常流程进行卡启。

依旧不能启动，不过报错有变化

=> boot
Could not find misc partition
ANDROID: reboot reason: "(none)"
Not AVB images, AVB skip
android_image_load_by_partname: Can't find part: boot
Android image load failed
Android boot failed, error -1.
## Booting FIT Image FIT: No boot partition
FIT: No FIT image
Could not find misc partition
Could not find primary part
MMC error: The cmd index is 1, ret is -110.....
Card did not respond to voltage select!
mmc_init: -95, time 12
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
3180 bytes read in 52 ms (59.6 KiB/s)
## Executing script at 00c00000
Wrong image format for "source" command
SCRIPT FAILED: continuing...

Device 0: unknown device
No ethernet found.

**Comment by 13584452567** [comment]
现在再按照此仓库的方法进行刷入img，那个update只是为了清空emmc随意找的一个安卓固件。

**Comment by elfinyuki** [comment]
> 现在再按照此仓库的方法进行刷入img，那个update只是为了清空emmc随意找的一个安卓固件。

现在的log就是刷update清空重新刷img的

**Comment by 13584452567** [comment]
https://wweo.lanzouy.com/i3Zlb0pmxqif
密码:8orv
下载这个，然后短接进入maskrom模式，直接执行。

emmm，如果这个方法也不行，那我想不到什么其他办法来更新你的uboot了。按道理这几种方法都会破坏原有的u-boot，不知为何你这几次都没法刷掉。

**Comment by elfinyuki** [comment]
> https://wweo.lanzouy.com/i3Zlb0pmxqif 密码:8orv 下载这个，然后短接进入maskrom模式，直接执行。
> 
> emmm，如果这个方法也不行，那我想不到什么其他办法来更新你的uboot了。按道理这几种方法都会破坏原有的u-boot，不知为何你这几次都没法刷掉。

依旧

**Comment by elfinyuki** [comment]
我很难确定到底是不是uboot没更上，理论上来说各种抹emmc的方法都试过了，应该不会留原先固件的uboot才对

试了一下移植排除，把[flippy仓库内的boot.scr](https://github.com/unifreq/openwrt_packit/tree/master/files/bootfiles/rockchip/rk3568/r68s)移到armbian里测试了下，不报错，但卡在引导内核
<img width="1121" alt="image" src="https://user-images.githubusercontent.com/35169838/224092577-af8b90a4-377d-4809-8d39-a37eb65aacbc.png">
反过来的，把armbian的boot.scr移到flippy，报同样错误

用ubootimage内的mkimage重做boot.scr也报同样错误，用flippy仓库的mkimage重做的在加载后直接panic
```
Found U-Boot script /boot.scr
3153 bytes read in 53 ms (57.6 KiB/s)
## Executing script at 00c00000
Boot script loaded from mmc 0
"Error" handler, esr 0xbe000011

* Reason:        Exception from SError interrupt
* PC         =   0000000000ab8e64
* LR         =   0000000000a9b494
* SP         =   00000000eb9f5e50
* ESR_EL2    =   00000000be000011
* Reloc Off  =   00000000ed34b000

x0 : 0000000009000000 x1 : 00000000eb9f6040
x2 : 0000000000000107 x3 : 0000000000000040
x4 : 0000000000000100 x5 : 0000000000000020
x6 : 6f720a6274642e73 x7 : 0000000000001000
x8 : 00000000ebd75640 x9 : 0000000000000008
x10: 00000000ffffffd8 x11: 00000000ebd70fbd
x12: 0000000000000002 x13: 0000000000000004
x14: 00000000eb9f87c8 x15: 0000000000000002
x16: 000000000000000c x17: 0000000000000001
x18: 00000000eb9ffcf0 x19: 0000000000000107
x20: 00000000ebd4cf20 x21: 0000000000008430
x22: 0000000009000000 x23: 00000000eb9f6040
x24: 00000000eb9f6270 x25: 00000000edecb4c8
x26: 0000000000008430 x27: 0000000000000000
x28: 0000000000000009 x29: 00000000eb9f64b0


Call trace:
  PC:   [< 00ab8e64 >]
  LR:   [< 00a9b494 >]

Stack:
        [< 00ab8e64 >]
        [< 00a97620 >]
        [< 00a977c4 >]
        [< 00a96b78 >]
        [< 00a9700c >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a188e8 >]
        [< 00a18034 >]
        [< 00a18504 >]
        [< 00a183c0 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ea24 >]
        [< 00a08130 >]
        [< 00a08238 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a188e8 >]
        [< 00a18034 >]
        [< 00a18504 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a183c0 >]
        [< 00a183c0 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a183c0 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a183c0 >]
        [< 00a183c0 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a183c0 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a188e8 >]
        [< 00a18034 >]
        [< 00a18504 >]
        [< 00a183c0 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ead4 >]
        [< 00a2f520 >]
        [< 00a18748 >]
        [< 00a188e8 >]
        [< 00a17fec >]
        [< 00a2ea24 >]
        [< 00a18f98 >]
        [< 00a16a60 >]
        [< 00a19654 >]
        [< 00aa021c >]
        [< 00a19880 >]
        [< 00a01e38 >]

Copy info from "Call trace..." to a file(eg. dump.txt), and run
command in your U-Boot project: ./scripts/stacktrace.sh dump.txt 

Resetting CPU ...

### ERROR ### Please RESET the board ###
```

**Comment by ophub** [comment]
你清空后，刷个别人的系统看看能不能正常启动

**Comment by elfinyuki** [comment]
> 你清空后，刷个别人的系统看看能不能正常启动

flippy能正常启动，只有这个armbian和另一个openwrt不能启动

**Comment by ophub** [comment]
这说明我做错了什么，我同步一下他的u-boot，再好好比较下写入命令。我找到问题后及时修复的。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_03.10.0257

我仔细比较了 bootloader.bin 是一个相同的文件，dd写入到镜像里的方法也一样。
唯一的区别是 /boot/boot.src 不同，我做了个例外设备管理管理，你试试最新生成的镜像能不能正常启动。

https://github.com/ophub/amlogic-s9xxx-armbian/commit/570c7ae5086938f3d76beee9f5cc00ad6cd8d7c0

**Comment by elfinyuki** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_03.10.0257
> 
> 我仔细比较了 bootloader.bin 是一个相同的文件，dd写入到镜像里的方法也一样。 唯一的区别是 /boot/boot.src 不同，我做了个例外设备管理管理，你试试最新生成的镜像能不能正常启动。
> 
> [570c7ae](https://github.com/ophub/amlogic-s9xxx-armbian/commit/570c7ae5086938f3d76beee9f5cc00ad6cd8d7c0)

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/35169838/224298946-0f4db0af-dfae-4078-9e25-aeb6ec3162f6.png">
可以启动了

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/different-files/r68s/bootfs/boot.cmd

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/rockchip/bootfs/boot.cmd

这个通用文件和r68s的文件，比起来就一行不同。好吧，总算解决了。多谢你的测试反馈。

**Comment by elfinyuki** [comment]
稍微提醒一下，打包脚本可能没更新，前面更错东西搞炸了重新刷机后发现又出现老问题，挂了下镜像看了一眼，现在新的包里面用的还是之前boot.cmd load_addr是0x9000000的老文件。。。
