### ISSUE TITLE
Install packages using APT, got older version; Request support for MXQ Pro 4K

### ISSUE THREAD

**Issue by Choomai** [ophub/amlogic-s9xxx-armbian#1140]
**Device Information**
 - SOC: S905W
 - Model: MXQ Pro 4K 5G 2GB/16GB

**Armbian Version**
 - Kernel Version: 6.1.15-flippy-82+
 - Release: jammy

**Describe the bug**
I have tried `sudo apt update` but it still report to me that nginx is the lastest version `1.18.0`.
Installed using `X96W/FunTV` model (can't find MXQ so I choose the most relevant spec, also can you add support for my model ?).
Installing in Termux I got version `1.23.3`
![image](https://user-images.githubusercontent.com/89532534/223324918-8d273ac3-9555-48b3-8fc6-ec95d24d66d4.png)
![Screenshot_20230307-120408](https://user-images.githubusercontent.com/89532534/223325659-0ae249d1-8e0c-4503-85f8-2faa8557a1ca.jpg)

**Comment by ophub** [comment]
The apt upgrade depends on the management of the upstream ubuntu/debian arm64 software package, which is not controlled.


There is no test feedback for your device at present. You can send a picture of the appearance of your box and the picture of the bottom (including the device model code). If it is convenient to disassemble, share the front and back photos of the motherboard. Pat the soc logo on the motherboard.

**Comment by Choomai** [comment]
Oh that's true, when installing Ubuntu using proot-distro I also got version `1.18.0`

Here is the image you asked me (about the heatsink, I can't really take it off, I need to use a lot of force to pull it out, and it may ripoff the chip too 🥴 so sorry about that)
![IMG_20230308_130044](https://user-images.githubusercontent.com/89532534/223632713-66dc68d6-886e-4c68-8ebe-39adc6e73fef.jpg)
![IMG_20230308_130223](https://user-images.githubusercontent.com/89532534/223632724-bbd572bf-5b5f-40b3-a058-9254eb03e47c.jpg)
![IMG_20230308_130028](https://user-images.githubusercontent.com/89532534/223632728-9cd6734b-d9ff-42c7-9dbe-aa2073efbbdf.jpg)

Here is the output of these 2 commands `cat /boot/uEnv.txt` and `ls -l /boot/u-boot*`
![image](https://user-images.githubusercontent.com/89532534/223631030-2e415dd6-3438-483c-b3a8-102e63463978.png)

**Comment by ophub** [comment]
Ok thanks for sharing. This is the same configuration as 119, and I will add it to the support list option tomorrow.

**Comment by 6ell** [comment]
There is another one MXQ Pro 4K. It has Rockchip RK3228A. I don't know if it supports Armbian, cause when i tried to boot holding reset button, it just gave me *no signal*.

**Comment by Choomai** [comment]
Did you plug the USB cable to your PC ?

**Comment by 6ell** [comment]
I tried to use usb flash, but I've learned that I had to use SD without holding the button. So neither.
