### ISSUE TITLE
添加对于风扇控制的工具

### ISSUE THREAD

**Issue by 13584452567** [ophub/amlogic-s9xxx-armbian#1141]
king3399自带一个散热风扇，目前是高于特定温度自动启动，低于则自动关闭。这个温度是写在dts里面的。
能够提供一种工具将用户输入的温度转换为16进制然后反编译目前的dtb并修改dts内特定字符嘛？

具体的温度值为cpu_hot子项内的temperature的数值。该数值为(10进制摄氏度值)*1000然后转换为16进制得出。

**Comment by ophub** [comment]
脚本： https://github.com/unifreq/openwrt_packit/blob/master/files/rk3588/rock5b/pwm-fan.pl

https://github.com/unifreq/openwrt_packit/blob/ae5b36a1eac52a2345dbd26de4e1130e0117eb99/public_funcs#L1060-L1064

**Comment by 13584452567** [comment]
本来想着整个一键脚本方便点的。不过这个东西貌似也不会经常调？
就这样吧，我到时候把方法写进使用文档里面。
