### ISSUE TITLE
Checking Wheterh Beelink GT King Pro (Rev A) Is Still Being Supported?

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#1142]
Hi @ophub,

Noticed that in the https://github.com/ophub/amlogic-s9xxx-armbian/releases there is NO longer any image for s922x_rev_a anymore.  Does this mean GT King Pro (Rev A) is not longer supported?

**Comment by ophub** [comment]
Long-term support.
Because the compilation space of github is insufficient, some default compilation devices are reduced.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/3b06f03aa9bd95031eb8e1754784b4800c1c0155

I tweaked the default build device list, added build s922x-reva firmware

**Comment by JFLim1** [comment]
> Long-term support. Because the compilation space of github is insufficient, some default compilation devices are reduced.

Hi @ophub 

Thank you.
