### ISSUE TITLE
安装firefox打不开

### ISSUE THREAD

**Issue by GuangzhanZuo** [ophub/amlogic-s9xxx-armbian#1143]
开发者，你好，我在盒子（Armbian_23.02.0_amlogicXXX.img，cm311-1a）上安装了图形桌面，并尝试安装火狐浏览器，安装成功后点击火狐的图标，鼠标会变成转圈圈的样子，并且打不开。请问是否是火狐不兼容s905l3a这类芯片？谢谢

**Comment by ophub** [comment]
这soc适合服务器版，桌面版建议使用更好的cpu，至少使用s905x3
