### ISSUE TITLE
armbian-sync error 

### ISSUE THREAD

**Issue by majorcheng** [ophub/amlogic-s9xxx-armbian#1145]
root@N1:~# armbian-sync 
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ STEPS ] Start syncing all service scripts...
[ STEPS ] Start syncing operation instruction and service script...
A    /usr/sbin
A    /usr/sbin/armbian-ddbr
A    /usr/sbin/armbian-docker
A    /usr/sbin/armbian-fix
A    /usr/sbin/armbian-kernel
A    /usr/sbin/armbian-software
A    /usr/sbin/armbian-swap
A    /usr/sbin/armbian-sync
A    /usr/sbin/armbian-tf
A    /usr/sbin/armbian-update
A    /usr/sbin/balethirq.pl
Exported revision 11036.
[ STEPS ] Start syncing software service script...
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/common-files/usr/share/ophub'
svn: E120108: Error running context: The server unexpectedly closed the connection.
[ ERROR ] Sync [ https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/common-files/usr/share/ophub ] scripts failed.

**Comment by ophub** [comment]
网络不好，调整一下访问github.com要通畅
