### ISSUE TITLE
软件中心可否加入typecho的安装脚本

### ISSUE THREAD

**Issue by molun** [ophub/amlogic-s9xxx-armbian#1148]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by Cp0204** [comment]
建议自行docker

**Comment by ophub** [comment]
https://github.com/typecho/Dockerfile

我看了他的服务器安装版和docker安装版的介绍。这个博客程序有多款数据库支持，需要在安装中需要多次交互去问用户设置数据库密码帐号、域名、内存限制等，有十几项个性化定制设置。

如果不交互式问答，只能用默认安装设置一个。但是我想要安装博客程序建立自己站点的用户，大概率是个懂得基础网站设置的人员。他选择这个博客程序应该从文档中看过了网站说明的介绍。所以默认安装的唯一方案应该无法满足他。

就像 Cp0204 的意见那样，这类面向程序员、面向专业领域用户的程序，不如让用户使用官方的 docker 模板或者 install.php 一键安装文件来进行个性化安装设置。
