### ISSUE TITLE
Support Ugoos AM6B Plus?

### ISSUE THREAD

**Issue by UMU618** [ophub/amlogic-s9xxx-armbian#115]
CPU: S922X-J
WiFi6: AP6398S

**Comment by ophub** [comment]
Can support the use of wired network.

**Comment by UMU618** [comment]
khadas vim3 uses the same AP6398S, and [CoreELEC](https://github.com/CoreELEC) supports vim3.

**Comment by ophub** [comment]
I asked the flippy boss, `AP6398S belongs to brcmfmac`, and the chip is `brcm4359-sdio`. The driver path is `drivers/net/wireless/broadcom/mac80211/brcmfmac`

![2022-02-21 16 06 41](https://user-images.githubusercontent.com/68696949/154913375-971866a8-c9f0-4556-91c3-04ece7b85825.jpg)


`The fourth from the bottom` on the picture is `brcm4359-sdio`, so it is theoretically supported, but requires real device testing.

**Comment by ophub** [comment]
I asked the flippy boss, `AP6398S belongs to brcmfmac`, and the chip is `brcm4359-sdio`. The driver path is `drivers/net/wireless/broadcom/mac80211/brcmfmac`

![2022-02-21 16 06 41](https://user-images.githubusercontent.com/68696949/154913375-971866a8-c9f0-4556-91c3-04ece7b85825.jpg)


`The fourth from the bottom` on the picture is `brcm4359-sdio`, so it is theoretically supported, but requires real device testing.
