### ISSUE TITLE
阿里CT2000(s922x)支持使用5.15.y/5.4.y内核写入emmc使用

### ISSUE THREAD

**Issue by ophub** [ophub/amlogic-s9xxx-armbian#1150]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. s922x]
 - Model [e.g. Ali-CT2000]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.98]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

目前阿里CT2000(s922x)的盒子bootloader有锁，无法定制专用的u-boot，所以只能先使用5.15/5.4的内核。以后有u-boot后才能使用5.10/6.1等内核。

可以使用gtking-pro的固件，但是无论Armbian还是OpenWrt，写入emmc时千万别使用主线u-boot，目前写入必须砖，且没有救砖的安卓刷机包。

经测试可以写入emmc使用，有线和蓝牙工作正常，无线没驱动。

由于 meson-g12b-ali-ct2000.dtb 是在 5.15.98/5.4.234 之后新添加的，所以别更新到之前版本的内核，会因为缺少这个 dtb 文件无法使用（手动添加可以）。

有什么问题欢迎随时反馈。

![Snip20230309_3](https://user-images.githubusercontent.com/68696949/223933303-725c81f9-261c-4ba1-8ea4-db831dbedc3e.png)
![Snip20230309_4](https://user-images.githubusercontent.com/68696949/223933323-1dd39423-7497-44cd-8b74-9f93814fe2f8.png)
![Snip20230309_7](https://user-images.githubusercontent.com/68696949/223933328-2296dd94-ca60-4869-a9e1-c59f346e06ce.png)
![Snip20230309_8](https://user-images.githubusercontent.com/68696949/223933331-2cadab85-1984-4ded-b155-d0770e46026a.png)

**Comment by ophub** [comment]
![Snip20230309_9](https://user-images.githubusercontent.com/68696949/223945550-f4780d7f-bd8c-4983-a1a5-48498e9c1c8e.png)
![Snip20230309_10](https://user-images.githubusercontent.com/68696949/223945563-ba973f14-ecf5-4c78-b1ec-9a4776beb417.png)
![Snip20230309_11](https://user-images.githubusercontent.com/68696949/223945567-c06b4fa4-1269-466c-a54a-d3a405387474.png)
![Snip20230309_13](https://user-images.githubusercontent.com/68696949/223945572-b17b749d-6b7e-4b55-9ce6-d04ce3362f25.png)
![Snip20230309_14](https://user-images.githubusercontent.com/68696949/223945578-2a742371-b7f7-4740-b779-662873c90a0b.png)

**Comment by alegoho** [comment]
请问不刷QQ群那个FASTBOOT那个刷机包能直接刷这个ARMBIAN不？

**Comment by ophub** [comment]
不刷那个，应该无法U盘启动。
刷了那个开启adb的安卓系统你才能 `adb shell reboot update` 进入U盘的系统

**Comment by alegoho** [comment]
> 不刷那个，应该无法U盘启动。 刷了那个开启adb的安卓系统你才能 `adb shell reboot update` 进入U盘的系统

可以U盘启动，因为之前已经有人在U盘启动了OP

**Comment by ophub** [comment]
可以就是不用刷了

**Comment by a393310872** [comment]
有QQ群不.想下载那个安卓系统,刚下单了CT2000

**Comment by ophub** [comment]
QQ群：2979254

**Comment by anysoft** [comment]
> 

首先理论上晶晨的机器都可以通过按住reset后通电等10秒强制从USB启动。(这种方式每次开机必须重复捅菊花才能进入U盘系统，当然你可以直接启动armbian后做备份后直接写入emmc，放弃Android。就可以跳过刷android修改包。如果想插入U盘都自动进入U盘系统，那么必须fastboot解锁后刷入root权限，然后adb下 reboot update，这里用几位大佬做好的Android包(原投屏/当贝)刷入后直接执行命令最省事 )。

一般流程是：
1. U盘烧录OP或者ARMBIAN
2. 捅菊花通电进入ARMBIAN
3. ARMBIAN下通过dd 备份原系统(dd if=/dev/mmcblk2 |gzip -6 > /root/ct2000.img.gz) ，这里可以多备份几次，然后 md5sum 校验下几次文件的md5是否一致，避免备份失败。
4. 可以自行刷入Android修改包或者把op/armbian 写入emmc(注意编号别选错，参考ophub大佬说明)

ps：第三步主要为了以后能op/armbian下恢复Android系统。 不清楚现在是否有救砖线刷包。

**Comment by huanyusb** [comment]
您好，我在u盘中写入了Armbian_24.8.0_amlogic_s922x-reva_jammy_6.6.43_server_2024.08.01.img.gz ，插在ct2000usb口上按reset开机，这部分都很正常，到了登录界面，但此时由于ct2000只有一个usb口，我无法再外接键盘，没法设置密码。而使用ssh链接时，使用root 密码1234显示permission denied。 请问这时应该怎么办呢？

**Comment by anysoft** [comment]
用扩展坞，hub。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月14日 21:02 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ophub/amlogic-s9xxx-armbian] 阿里CT2000(s922x)支持写入emmc使用 (Issue #1150) |

您好，我在u盘中写入了Armbian_24.8.0_amlogic_s922x-reva_jammy_6.6.43_server_2024.08.01.img.gz ，插在ct2000usb口上按reset开机，这部分都很正常，到了登录界面，但此时由于ct2000只有一个usb口，我无法再外接键盘，没法设置密码。而使用ssh链接时，使用root 密码1234显示permission denied。 请问这时应该怎么办呢？

**Comment by cola77777** [comment]
不需要usb hub，cmd命令行输入ssh root@192.168.1.*** -p 22   需改ip，就可以了

**Comment by zch1234qq** [comment]
> 不需要usb hub，cmd命令行输入ssh root@192.168.1.*** -p 22 需改ip，就可以了
没错  U盘启动后就可以ssh了

**Comment by Chaones** [comment]
GPU可以正常加载吗？

**Comment by sfwsky** [comment]
coreelec支持写入emmc吗
