### ISSUE TITLE
海信IP103H S905L3B 支持写入EMMC

### ISSUE THREAD

**Issue by gbsadmin** [ophub/amlogic-s9xxx-armbian#1154]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905L3B
 - Model 海信IP103H (移动)

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.98
 - Release: jammy、bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
折腾了两天，IP103H盒子 芯片是S905L3B，测试支持写入EMMC，USB可用，有线网络可用。部分6.1的核心也可用

已知问题是无线/蓝牙不可用(芯片是UWE5621DS)，HDMI不可用，音频没试(估计也不行)。
刷入armbian前先刷了HG680-LC ATV线刷包，用了一阵子，还可以 有谷歌套件
在刷入armbian后，如再想刷回盒子通过双公头线和短接可能无法回去，短接后电脑没反应USB_Burning没有显示设备，可能是uboot问题或是操作不对。需提前armbian-ddbr备份
下面是IP103H，S905L3B能用的镜像固件包及芯片信息，感谢 ophub 编译镜像
![QQ截图20230310125917](https://user-images.githubusercontent.com/26536782/224314041-5a5d5bfc-0017-4ad4-880e-06f7ce536464.png)
![QQ截图20230310125420](https://user-images.githubusercontent.com/26536782/224315518-6a51314e-5648-4050-b637-8b905f3a9489.png)
![IMG_20230301_192758_edit_1093665914046662](https://user-images.githubusercontent.com/26536782/224316110-9adcba9f-3ad0-4234-9ad7-55b963f5b97f.jpg)
![IMG_20230302_123455_edit_109301223890613](https://user-images.githubusercontent.com/26536782/224315788-6e283852-5907-4491-bc91-8b9ac42e179d.jpg)
![IMG_20230310_140542_edit_116091423371869](https://user-images.githubusercontent.com/26536782/224315794-c5bc4331-36ac-4030-8833-c4171e446398.jpg)

**Comment by ophub** [comment]
你用的配置是哪个，支持6.1.y系列USB和emmc启动的。我把这个设备添加到安装列表的选项里。
s905l3_6.1.15的这个，我看你支持emmc和usb启动，他的选项是`116`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/4cd2b0da823332020807487cdc1e6fbd03086a84/build-armbian/armbian-files/common-files/etc/model_database.conf#L52

你再确认下 116 的这个信息：
```
cat /boot/uEnv.txt
ls -l /boot/u-boot*
```

**Comment by gbsadmin** [comment]
![QQ截图20230311002051](https://user-images.githubusercontent.com/26536782/224380567-f2a68a48-b125-4091-867e-0f12900a3647.png)

root@armbian:~ cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-gxl-s905l3b-m302a.dtb
APPEND=root=UUID=375df762-7413-4235-a1c5-1a62e4fd5545 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty  0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memo  ry swapaccount=1
root@armbian:~ ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 Mar 11 00:11 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 606670 Mar 11 00:11 /boot/u-boot.emmc
-rwxr-xr-x 1 root root 606670 Mar 11 00:11 /boot/u-boot.ext
-rwxr-xr-x 1 root root 757153 Mar 11 00:11 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 Mar 11 00:11 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 Mar 11 00:11 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 Mar 11 00:11 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 Mar 11 00:11 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 Mar 11 00:11 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 Mar 11 00:11 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 633376 Mar 11 00:11 /boot/u-boot-r3300l.bin
-rwxr-xr-x 1 root root 609247 Mar 11 00:11 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 Mar 11 00:11 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 Mar 11 00:11 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 Mar 11 00:11 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 Mar 11 00:11 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 Mar 11 00:11 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 Mar 11 00:11 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 Mar 11 00:11 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 Mar 11 00:11 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 Mar 11 00:11 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 Mar 11 00:11 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 Mar 11 00:11 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 Mar 11 00:11 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 Mar 11 00:11 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 Mar 11 00:11 /boot/u-boot-zyxq.bin

Armbian_23.02.0_amlogic_s905l3_jammy_6.1.15_server
Armbian_23.02.0_amlogic_s905l3_bullseye_6.1.15_server
uboot可选：u-boot-s905x-s912.bin、u-boot-p212.bin
dtb可选：meson-gxl-s905l2-x7-5g.dtb、meson-gxl-s905l3b-e900v22e.dtb、meson-gxl-s905l3b-m302a.dtb

另外s905l3a_5.15镜像将u-boot-s905x-s912.bin 重命名为u-boot-e900v22c.bin，使用meson-gxl-s905l2-x7-5g.dtb或meson-gxl-s905l3b-*.dtb也可以U盘启动，emmc没试 应该也可以。貌似很多都可以改一改能启动，都有有线网络；但无线BT一个也没有。还有6.1.x的启动日志开头显示没有mac，之后又给了个跟原厂不同mac，但启动后不影响使用。话说大佬能不能把这个无线bt加上。感觉jammy比bullseye运行快，不知道是不是幻觉。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/2648b6dc873355b87d8adf6142fa2c6f98d2546c/build-armbian/armbian-files/common-files/etc/model_database.conf#L47

感谢详细的反馈，现在他添加到`112`选项里了。

**Comment by gbsadmin** [comment]
` 112     :M302A,M304A,IP103H          :s905l3b  :meson-gxl-s905l3b-m302a.dtb            :u-boot-s905x-s912.bin `

echo 507 > /sys/class/gpio/export 		#绿灯
echo out > /sys/class/gpio/gpio507/direction
echo 1 > /sys/class/gpio/gpio507/value		#亮
echo 0 > /sys/class/gpio/gpio507/value		#灭

echo 474 > /sys/class/gpio/export		#红灯
echo out > /sys/class/gpio/gpio474/direction	#亮
echo 1 > /sys/class/gpio/gpio474/value		#亮
echo 0 > /sys/class/gpio/gpio474/value		#灭

**Comment by KaMuMom** [comment]
How to boot with a USB flash drive
如何使用U盘启动

**Comment by danghaivu** [comment]
我按照你的指导和在谷歌上找到的各种方法都试过了，但电脑还是无法识别。你能详细教我一下怎么做才能让盒子识别到闪存吗？
