### ISSUE TITLE
How to solve this problem? (software-list.conf  file is empty)

### ISSUE THREAD

**Issue by Ruky-lyc** [ophub/amlogic-s9xxx-armbian#1157]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095l2]
 - Model [e.g. mgv2000]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.86]
 - Release: [e.g. jammy 23.02.0]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

无法进行armbian-software安装软件，如图所示，已经写入emmc
无法更新内核，apt update命令不正常

<img width="944" alt="屏幕截图 2023-03-10 220547" src="https://user-images.githubusercontent.com/98870179/224336917-7be53489-7872-4386-9523-df8b099c61c7.png">

**Comment by ophub** [comment]
`armbian-sync`
