### ISSUE TITLE
斐讯T1 apt update 提示Some index files failed to download. They have been ignored, or old ones used instead.

### ISSUE THREAD

**Issue by fvlw** [ophub/amlogic-s9xxx-armbian#1158]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. s912]
 - Model [e.g. phicomm T1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.98]
 - Release: [e.g. m8s_jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

已更换 国内镜像源 apt update 提示
![图片](https://user-images.githubusercontent.com/71577616/224344338-ffa97668-b983-4ad0-bc44-4beb7bca0d11.png)

![图片](https://user-images.githubusercontent.com/71577616/224344447-52068b9b-89bc-4eb5-958d-864e034a3c8d.png)

请问这是什么问题，是镜像源的问题，还是img的问题。

**Comment by ophub** [comment]
404网络错误，把ipv6关了

**Comment by fvlw** [comment]
![图片](https://user-images.githubusercontent.com/71577616/224520338-df0b1514-8e84-4e50-b1b4-bfafbe082c3d.png)

ipv6关了还是错误，应该不是V6的问题。

**Comment by ophub** [comment]
都是404错误，之前IPV6地址不通，现在IPV4地址不同，说明你的网络正常无法访问这些镜像服务器。解决网络，或者使用其他你能访问的镜像服务器。

**Comment by fvlw** [comment]
这是国内的镜像源应该是可以访问的，会不会是国内镜像源没有同步armhf架构的文件，导致没有存在该目录文件，更新获取失败。

**Comment by ophub** [comment]
我用的是官方源，不了解这个。去年我也用过几天，一些软件包更新不了，就一直使用官方了。

**Comment by fvlw** [comment]
https://mirrors.ustc.edu.cn/ubuntu/dists/jammy/restricted/binary-arm64/Packages  404  Not Found
我去看了下ubuntu的官方源，发现在这个路径下也是没有binary-arm64这个架构的文件
![图片](https://user-images.githubusercontent.com/71577616/224520972-a4901112-63f1-4abd-b9ee-1f6d53ce457a.png)
怪不得提示 Not Found
