### ISSUE TITLE
2023.03.10版本 R66s bullseye/jammy无法启动

### ISSUE THREAD

**Issue by PP88PP** [ophub/amlogic-s9xxx-armbian#1159]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: RK3568
 - Model: fastrhino-r66s

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.x
 - Release: Jammy && Bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

https://pastebin.ubuntu.com/p/PY7PDTkSbt/

**Comment by PP88PP** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_03.10.2242/Armbian_23.02.0_rockchip_r66s_jammy_6.1.16_server_2023.03.10.img.gz 问题依旧，换卡无效，日志可参考上文

**Comment by ophub** [comment]
明天我测试一下，现在r66s不在手边

**Comment by ophub** [comment]
你下载现在的最新的，我测试可以了。

![Snip20230312_1](https://user-images.githubusercontent.com/68696949/224519609-02b41986-a49b-48c9-94f2-813486ed03bb.png)

**Comment by PP88PP** [comment]
> 你下载现在的最新的，我测试可以了。
> 
> ![Snip20230312_1](https://user-images.githubusercontent.com/68696949/224519609-02b41986-a49b-48c9-94f2-813486ed03bb.png)

确认正常启动，感谢。
