### ISSUE TITLE
Could you build with linux-image-edge-arm64

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#116]
I use with beelink gtking-pro (S/N : SA9H...) on sd-card
I can boot with linux-image-edge-arm64 kernel 5.15.y and 5.16.y but i can't boot flippy kernel 5.15.y (boot only flashed on usb stick..)
Can you try a new build with linux-image-edge-arm64

[config-5.16.10-arm64.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104695/config-5.16.10-arm64.zip)
[System.map-5.16.10-arm64.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104710/System.map-5.16.10-arm64.zip)
[vmlinuz-5.16.10-arm64.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104711/vmlinuz-5.16.10-arm64.zip)

[uInitrd-5.16.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104728/uInitrd-5.16.zip) It's a .zip splitted into 3 with winrar first download and rename the 2 other files before unzip..
[uInitrd-5.16.z01.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104730/uInitrd-5.16.z01.zip) just rename without ".zip"
[uInitrd-5.16.z02.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104735/uInitrd-5.16.z02.zip) just rename without ".zip"
 [dtb-linux-image-edge-arm64-amlogic.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8104627/dtb-linux-image-edge-arm64-amlogic.zip)

![Capture d’écran (30)](https://user-images.githubusercontent.com/62643837/154857341-cba43f68-6d97-47f4-8ae2-ad57e94287c1.png)

**Comment by ophub** [comment]
A set of kernels has 4 files, and it is impossible for you to manually change several of them.

use: armbian-update 5.16.10

![Snip20220221_1](https://user-images.githubusercontent.com/68696949/154869958-38d6cbe8-e3f2-4c3b-8ffe-4951f61cb293.png)

![Snip20220221_3](https://user-images.githubusercontent.com/68696949/154869960-569cec3e-fa1f-4dbb-91c6-1b57f8a5ed46.png)

![Snip20220221_4](https://user-images.githubusercontent.com/68696949/154870002-6b1c9071-31ca-45ce-95ee-b47732e10ecc.png)

![Snip20220221_5](https://user-images.githubusercontent.com/68696949/154870063-34d19dff-0bec-4d7d-ab52-a94f204eef4c.png)

**Comment by MX10-AC2N** [comment]
When I do `armbian-update 5.15.24` the reboot failed so I delete all files of 5.15.24 in /BOOT and copy all files of 5.4.166-flippy-68+0 that I've a copy on my pc and reboot is ok without hdmi but ssh connection work so I update with `sudo apt install linux-image-arm64` and adjust /boot (problem with symlink impossible on fat)..
Can boot with linux-image-arm64 5.15.0-0.bpo.3-arm64 #1 SMP Debian 5.15.15-2~bpo11+1 (2022-02-03) aarch64 GNU/Linux
`cat /etc/ophub-release` return kernel 5.15.24 but I can't boot this release on my sd-card..
![Capture d’écran (31)](https://user-images.githubusercontent.com/62643837/154980291-d6dbb5ce-bbc1-4124-a6a6-fc8f19a4f26d.png)
Nice !

**Comment by ophub** [comment]
There is no need to install linux-image-edge-arm64, nor to manually change the files under boot.

You manually changed the integrity and consistency of the system kernel. It is also not possible to update with armbian-update later. I don't understand the point of your so confusing use, there is a proper way to update the kernel.

**Comment by MX10-AC2N** [comment]
Hello @ophub  and thank you again for everything you do..

Indeed this I only tested to see if I can run armbian under kernel 5.15.y which is LTS because with my A2 sd card when I try an armbian-update to 5.15.y (flippy) my box gtking_pro bug on reboot, (I wonder if this is not due to the A2 of my sd card) anyway with an `apt remove linux-image-edge-meson64` followed by an `àpt install linux-image- edge-arm64` some adjustments in the boot partition because the armbian update process creates symbolic links which is not possible under FAT so I just recreate the uInitrd and zImage files from the new Initrd-5.15.y- arm64 and vmlinuz-5.15.y-arm64 newly present in /BOOT and /boot/dtb from /usr/lib/linux-image-edge-arm64/

During my tests I noticed that if I install linux-image-edge-arm64 (armbian) during the installation the FAT partition (/BOOT) is dismounted and therefore the installation of the new files is found under the folder /boot present on the ROOTFS partition (ext4) I had to transfer the new img files to the BOOT partition (fat) there is also a new boot.ini file boot.cmd boot.scr but they are not usable bug au startup. I also copied the dtb folder from /usr/lib/linux-image-edge-arm64/amlogic/ in order to use the correct .dtb (that of the kernel 5.15.y flippy not working.
On the other hand, if linux-image-arm64 (debian) is installed, the installation proceeds correctly on the FAT /BOOT partition, only the symbolic link problem is reported.
With these 2 images I managed to start from my 5.15 sd card but if I understand what you are telling me by doing this I break a lot of things.

 So which command "armbian-update" launched to have an update to kernel 5.15.y other than flippy for example linux-image-arm64 and it would be best for me because the updates will not unmount the partition /BOOT (fat)

Thank you again for everything, hoping not to bother too much, there are not many people who can answer my questions.
Oops in fact all that is to be able to install yunohost over armbian which is supposed to work correctly however I have some problems with the releases that you provide because when installing yunohost there is a full update system is therefore a problem with the /boot (fat) partition which is unmounted during the upgrade, I had to do my little manipulation of files between the 2 partitions to restart yunohost then during the update made under yunohost I have always this concern kernel updates are done despite that I freeze the updates under armbian-config..

Have a nice day ;-)

**Comment by ophub** [comment]
The official armbian supports a lot of boxes. This project is an attempt at some officially unsupported boxes. Because some devices lock the bootloader, the latest official boot settings cannot be used.

The content of the boot partition currently used is to take into account the purpose of reloading u-boot to achieve the purpose of using kernels above 5.10. If you change to the official extlinux and other settings, there is still no good way to help these special amlogic boxes to use armbian.

This is a compromise. Maybe many years later, all kinds of boxes will not lock the bootloader, and they will be devices with an open spirit, allowing everyone to freely modify their system, then this project can be deleted.

Your method of updating the kernel will work on your device, because the current gtking is open, allowing you to remove his system. If you are familiar with the operation of armbian, this use is appropriate.

**Comment by MX10-AC2N** [comment]
Thank again @ophub 
Is it possible to adjust the installation procedure during apt upgrades in order to take care of the fact that /boot is a (fat) partition and therefore make copies of the image files rather than wanting to make symbolic links?

**Comment by ophub** [comment]
I don't have a good way, you search the Internet more
