### ISSUE TITLE
Mecool-M8S-PRO-L(s912) available only 2.4 GB of 29GB storage

### ISSUE THREAD

**Issue by hro-ict** [ophub/amlogic-s9xxx-armbian#1161]
SD Card: 29 GB
Internal storage: 16 GB
DTB= meson-gxm-q201

![issue](https://user-images.githubusercontent.com/57659697/224487891-e328a768-bd27-4576-8620-a5ac33866361.PNG)

**Comment by ophub** [comment]
```
armbian-sync
armbian-tf
```
