### ISSUE TITLE
Enable `CONFIG_KPROBES` for Kernel

### ISSUE THREAD

**Issue by Scirese** [ophub/amlogic-s9xxx-armbian#1162]
Kprobes is a kernel debugging interface allows us to break into kernel routines.

"Kprobes enables you to dynamically break into any kernel routine and collect debugging and performance information non-disruptively. You can trap at almost any kernel code address [1](https://docs.kernel.org/trace/kprobes.html#id2), specifying a handler routine to be invoked when the breakpoint is hit."

 Not only it's useful for development, some desktop apps may need to install a additional kernel module with dkms (like Waydroid, a Android container under Linux, requires a additional binderfs module), which many of them rely on this kernel feature.

Enabling this feature won't interfere other daily usages, but if we need it, we don't have to recompile the kernel anymore, reducing unnecessary work.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/5e799015a89a3812c095e5ea48cb733c07daca0b

enable
