### ISSUE TITLE
Can't boot after install full firmware package.

### ISSUE THREAD

**Issue by Choomai** [ophub/amlogic-s9xxx-armbian#1163]
**Device Information**
 - SOC: S905W
 - Model: MXQ Pro 4K 5G 2GB/16GB

**Armbian Version**
 - Kernel Version: 6.1.16
 - Release: jammy

**Describe the bug**
As the title says, I can't boot from eMMC anymore but if I insert a USB with installer then it boot.
How do I fix it ? Reinstalling without data loss ?
I noticed that when installing full firmware package it show some error. Also it tell me to do an `sudo apt upgrade` because of some security fix 🤔 (most of the package name is armbian)

https://user-images.githubusercontent.com/89532534/224517441-81b69529-7746-42bc-85f1-a296bdccf8e9.mp4

**Comment by Choomai** [comment]
Tried `armbian-update -r` but it detected that I'm running on eMMC (usb actually)
[Video](https://drive.google.com/file/d/1vqaLlXgv0ImjUhdi5bHAZ9LT8LileK0i/view?usp=share_link)
I can't upload here (19MB)

**Comment by ophub** [comment]
`armbian-update -r` can only repair the kernel, not the firmware. Reload it.

**Comment by Choomai** [comment]
What do you mean **reload** ? Reinstalling it or what?

**Comment by ophub** [comment]
Reinstalling

**Comment by Choomai** [comment]
Is there data loss?

**Comment by ophub** [comment]
will loss

**Comment by Choomai** [comment]
Ok then. I think the issue is done now. Maybe if I do an `sudo apt upgrade` it will download offical armbian stuff instead of this repo.
