### ISSUE TITLE
Installation to NEO U9-H

### ISSUE THREAD

**Issue by fachos** [ophub/amlogic-s9xxx-armbian#1164]
HI...

How to get boot to minix u9-h? i try hold reset button while sdcard boot but not successful
any other way around? thank you

**Device Information
 - SOC: [e.g. S912]
 - Model [e.g. U9-H]

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

**Comment by fachos** [comment]
i successfully boot to s905x device.... even flash to eMMc... but this minix u9-h (s912) cant get boot...  i wonder why maybe someone can share experience or how to do some tricks... i try bulleyes/jammy change their dtb to u9-h.dtb before insert the sdcard... but still cant... thank you

**Comment by ophub** [comment]
The file name you changed exists? Or imagined?

**Comment by fachos** [comment]
meson-gxm-minix-neo-u9h.dtb

**Comment by fachos** [comment]
file available in /boot/dtb/amlogic..... then i update the the name in /boot/uEnv.txt

**Comment by ophub** [comment]
What was the dtb before you modified it? Select the firmware test of the 6.1.y kernel, do not modify it if it can be started.

**Comment by fachos** [comment]
before is meson-gxm-octopus-planet.dtb...  it cannot boot anyway.... double checked the router no lan show up...

**Comment by ophub** [comment]
You said above that you can boot from USB, what are you using, don't modify it.

**Comment by fachos** [comment]
i try all meson-gxm*.dtb cannot boot for this U9-H.... i tyr all meson-glx.*dtb for s905x device can normal boot...

**Comment by ophub** [comment]
Firmware test of s912 using 5.15 kernel

**Comment by fachos** [comment]
ok i download now..... will let you know... thank you

**Comment by fachos** [comment]
Flash **Armbian_23.02.0_amlogic_s912_jammy_5.15.100_server_2023.03.12.img.gz** with untouched uEnv.txt.. It boot with 2 IP... 1st IP attemp it jump to new IP.... can login normal..... thank you.... gonna change to u9-h dtb coz seem too many red line in dmesg... let u know.... thank you

**Comment by ophub** [comment]
u-boot-s905x-s912.bin
u-boot-p212.bin
u-boot-zyxq.bin


run on usb:
cd /boot
cp -f u-boot-s905x-s912.bin u-boot.ext
sync && reboot

**Comment by fachos** [comment]
cp -f u-boot-s905x-s912.bin u-boot.ext && sync && reboot....
cannot boot... the led from blue change to green... now i have to flash back the sdcard...

**Comment by samorez1** [comment]
Hello, could you please tell which image of armbian you use for MINIX NEO U9-H? And where can I get it?

Sorry for stupid question - Im new on yhis)
