### ISSUE TITLE
阿里CT2000(s922x)的WiFi为什么无法使用，如果我手动安装驱动，是否可以？

### ISSUE THREAD

**Issue by Jack-bin183** [ophub/amlogic-s9xxx-armbian#1165]

**Comment by ophub** [comment]
没驱动

**Comment by a393310872** [comment]
> 没驱动

大佬.我安装最新版然后armbian-update后在nmtui里是可以扫描到信号的.说明其实有驱动并且能工作?但问题是在链接的时候,输入完密码他会继续提示需要密码验证[https://i.328888.xyz/2023/03/16/K2BHU.png](url)[https://i.328888.xyz/2023/03/16/K2gT3.png](url)

**Comment by Jack-bin183** [comment]
用 armbian-config 图形化连接  一次就好    你是不是昨天在群里问我那个

**Comment by a393310872** [comment]
> 

config里的图形化就是nmtui啊.我链接了N遍..都是提示要输入密码....

**Comment by ophub** [comment]
稍等下一个内核试试，最近的这5版内核的无线都是只能看不能连。看kernel.org的更新日志，这个问题在最新的6.2.6, 6.1.19, 5.15.102上修复了。这几天f大忙的没空更新内核，等发了新内核再试一试。
