### ISSUE TITLE
斐讯T1用最近几天的版本wifi连不上

### ISSUE THREAD

**Issue by shobalpeng** [ophub/amlogic-s9xxx-armbian#1168]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information | 设备信息

SOC: [e.g. s912]
Model [e.g. phicomm T1]
Armbian Version | 系统版本

Kernel Version: [e.g. 5.15.98]
Release: [e.g. m8s_bullseye]
Describe the bug | 问题描述
Describe the problem in detail and attach screenshots if necessary

最近两三天的版本都试过，无法连接带密码的wifi，确认输入的密码正确，提示secret are required,but not provide，但是无密码的wifi是可以正常连接的，请问下这个是什么问题？
原本以为是自己的问题，今天在恩山看到N1也有相同的问题，附上链接:
https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=8280280&highlight=armbian&mobile=2

**Comment by ophub** [comment]
下一个版本就可以了，最近的几个内核wifi不可用。
