### ISSUE TITLE
x96 max+ 蓝牙无法工作

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#117]
这几天重新刷了下发现wifi能正常工作了，蓝牙还是不行，是还未兼容嘛？

非常感谢这个开源项目:-)

**Comment by EastWoodYang** [comment]
当前使用 5.1内核版本，需要切到5.4吗？好像当前 bullseye image 无法下载，只有focal，是没触发打包？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/75

有用户反馈蓝牙应该是可以使用的，我的这个设备放了一个月没开机，不知道为无法开机了，给你测试不了。
这个设备支持全内核系列，你可以从任意一个内核系列直接更换到其他，比如现在是5.4.180，你armbian-update 5.16.10就切换更新到5.16系列了，在 5.4 / 5.10 / 5.15 / 5.16 的内核里可以通过 `armbian-update x.xx.xxx` 任意切换，当前可选内核可查阅https://github.com/ophub/kernel/tree/main/pub/stable

**Comment by JFLim1** [comment]
Hi @ophub,
Can I make a suggestion.  May be alternate build focal one day and another day build bullseye.  The users can download Focal or Bullseye or Jammy (in near future). 

I tried using GT King Pro (running Ubuntu Impish) to build Bullseye image following your instructions above but I don't seem to have the option to select "Bullseye" or "Board" as you have.

Did I miss some steps?

![image](https://user-images.githubusercontent.com/75384411/155080493-f11d9609-b38d-4b4f-b013-a61a64b1cd5b.png)

**Comment by ophub** [comment]
You do not have execution authority to operate directly in my warehouse. The first step is to fork, and then the warehouse will be copied directly to your account. If you operate under your own warehouse, you will have full management authority.

**Comment by JFLim1** [comment]
> You do not have execution authority to operate directly in my repo. The first step is to `fork`, and then the repo will be copied directly to your account. If you operate under your own repo, you will have full management authority.

Thanks for your quick response.  I am new to github and have not set up and projects before.  
Will stick with downloading your pre-build Armbian images, hopefully you can also alternate to build "Bullseye" and "Focal" images and in near future "Jammy" alternatively so that users can easily download Bullseye or Focal.

Thank you.

**Comment by ophub** [comment]
already added

**Comment by EastWoodYang** [comment]
![image](https://user-images.githubusercontent.com/9335046/155162278-7f1ae621-17ff-4465-896d-d3e25123f8a4.png)
![1645543021(1)](https://user-images.githubusercontent.com/9335046/155162376-4c06ee24-ca3d-4421-acb7-2651f07c8b87.png)

设备内的蓝牙模块是没识别出来，但插上一个usb蓝牙是可以输出对应信息

**Comment by JFLim1** [comment]
> already added

Thank you.

**Comment by ophub** [comment]
> 设备内的蓝牙模块是没识别出来，但插上一个usb蓝牙是可以输出对应信息

你查查你的设备的蓝牙模块需要什么驱动，在kernel的配置里搜一下看看有没有，如果内核里有驱动，可以自定义编译一个包含你蓝牙的内核测试下。

内核编译的方法：
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md

内核配置文件，你搜下型号：
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.4.180

**Comment by EastWoodYang** [comment]
> > 设备内的蓝牙模块是没识别出来，但插上一个usb蓝牙是可以输出对应信息
> 
> 你查查你的设备的蓝牙模块需要什么驱动，在kernel的配置里搜一下看看有没有，如果内核里有驱动，可以自定义编译一个包含你蓝牙的内核测试下。
> 
> 内核编译的方法： https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md
> 
> 内核配置文件，你搜下型号： https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.4.180

 好的，有空把设备拆开看下，另外问下  USB蓝牙用的芯片是 Realtek 8761BUV，这个内核目前是不是不支持？目前插上能识别但实际无法使用。

**Comment by ophub** [comment]
支持的列表可以在内核的源码中查看：https://github.com/unifreq/linux-5.10.y/blob/main/drivers/bluetooth/btmrvl_sdio.c

你的应该不支持

**Comment by EastWoodYang** [comment]
我看了下 [linux-5.16.y](https://github.com/unifreq/linux-5.16.y)内核，有相应蓝牙驱动支持，我请教下如何使用[linux-5.16.y](https://github.com/unifreq/linux-5.16.y)内核来编译出armbian，编译方面小白，Action相应文档没看明白，问下有没有操作图解:-)

**Comment by ophub** [comment]
sudo ./recompile -d -k 5.16.10
