### ISSUE TITLE
armbian-update command erases all data on the boot disk (Команда armbian-update стирает все данные на загрузочном диске)

### ISSUE THREAD

**Issue by Gluk41** [ophub/amlogic-s9xxx-armbian#1170]
**Device Information**
 - SOC: S095x3
 - Model: X96 Max+ 2

**Armbian Version**
 - 23.02.0
 - Kernel Version: 5.15.92, 5.15.100, 6.1.18
 - Release: Armbian_jammy_03.13.0533

The armbian-update command is executed, automatically overloads the system and that's it, the system no longer works. Gparted shows an empty disk with no partitions.
I got on the old build from 5.15.92, just tried to update, then checked both the latest builds.

Команда armbian-update выполняется, автоматически перегружает систему и всё, система больше не работает.  Gparted показывает пустой диск без разделов.
Попал на старой сборке с 5.15.92, просто пытался обновить, затем проверил обе последние сборки.

**Comment by ophub** [comment]
In your box, if you flash any version of armbian, once you update the kernel, all system data will be gone?

**Comment by Gluk41** [comment]
Yes
The media is completely clean, without partitions

**Comment by ophub** [comment]
```
cat /etc/ophub-release
cat /boot/uEnv.txt
ls -l /boot/u-boot*
```

**Comment by Gluk41** [comment]
From the current system:
makc@armbian:~$ cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905x3'
FDTFILE='meson-sm1-x96-max-plus-100m.dtb'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='5.15.92'
KERNEL_BRANCH='stable'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='usb'
MLUBOOT_STATUS='no'
AMPART_STATUS='no'
PACKAGED_DATE='2023-02-10'
makc@armbian:~$ cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-x96-max-plus-100m.dtb
APPEND=root=UUID=1bf778cf-0f73-4736-a4f7-ae11db3ef421 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
makc@armbian:~$ ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 фев 10 06:22 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 757153 фев 10 06:22 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 фев 10 06:22 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 фев 10 06:22 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 фев 10 06:22 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 фев 10 06:22 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 фев 10 06:22 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 фев 10 06:22 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 633376 фев 10 06:22 /boot/u-boot-r3300l.bin
-rwxr-xr-x 1 root root 609247 фев 10 06:22 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 фев 10 06:22 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 фев 10 06:22 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 фев 10 06:22 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 фев 10 06:22 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 фев 10 06:22 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 фев 10 06:22 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 фев 10 06:22 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 фев 10 06:22 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 фев 10 06:22 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 фев 10 06:22 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 фев 10 06:22 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 фев 10 06:22 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 фев 10 06:22 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 фев 10 06:22 /boot/u-boot-zyxq.bin
makc@armbian:~$ lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0          7:0    0     4K  1 loop /snap/bare/5
loop1          7:1    0  59,1M  1 loop /snap/core20/1826
loop2          7:2    0  59,1M  1 loop /snap/core20/1832
loop3          7:3    0  53,5M  1 loop /snap/cups/873
loop4          7:4    0 213,9M  1 loop /snap/firefox/2390
loop5          7:5    0 330,6M  1 loop /snap/gnome-3-38-2004/122
loop6          7:6    0  91,7M  1 loop /snap/gtk-common-themes/1535
loop7          7:7    0  43,2M  1 loop /snap/snapd/17954
loop8          7:8    0  43,2M  1 loop /snap/snapd/18363
sda            8:0    0  57,6G  0 disk 
├─sda1         8:1    0   255M  0 part /boot
└─sda2         8:2    0  57,4G  0 part /var/log.hdd
                                       /var/snap/firefox/common/host-hunspell
                                       /
mmcblk2      179:0    0  29,1G  0 disk 
mmcblk2boot0 179:32   0     8M  1 disk 
mmcblk2boot1 179:64   0     8M  1 disk 
zram0        254:0    0   1,6G  0 disk [SWAP]
zram1        254:1    0    50M  0 disk /var/log
zram2        254:2    0     0B  0 disk 
armbian-update I will try to take a picture in time, the process before restarting is very fast.
Now I'll make a backup and try.

**Comment by Gluk41** [comment]
_              _   ____  ___   ___  ____      _____ 
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|_  _|___ / 
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \ \/ / |_ \ 
 / ___ \| | | | | | |  ___) \__, | |_| |___) >  < ___) |
/_/   \_\_| |_| |_|_| |____/  /_/ \___/|____/_/\_\____/ 
                                                        
Welcome to Armbian 23.02.0-trunk Jammy with Linux 5.15.92-flippy-81+o

System load:   42%              Up time:       1 min
Memory usage:  19% of 3.26G     IP:            10.42.0.97 10.42.0.162
CPU temp:      46°C             Usage of /:    53% of 11G    
storage/:      46% of 252M   


 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro

Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status

Last login: Fri Feb 10 16:36:16 2023
makc@armbian:~$ sudo -i
[sudo] пароль для makc: 
root@armbian:~# armbian-update
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Start installing the necessary dependencies.
Сущ:1 http://ports.ubuntu.com jammy InRelease
Пол:2 http://ports.ubuntu.com jammy-security InRelease [110 kB]
Пол:3 http://ports.ubuntu.com jammy-updates InRelease [119 kB]
Сущ:4 http://ports.ubuntu.com jammy-backports InRelease
Сущ:5 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Пол:6 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease [110 kB]
Пол:7 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease [119 kB]
Пол:8 http://ports.ubuntu.com jammy-updates/main arm64 Packages [1 071 kB]
Пол:9 http://ports.ubuntu.com jammy-updates/main armhf Packages [778 kB]
Пол:10 http://ports.ubuntu.com jammy-updates/universe armhf Packages [818 kB]
Пол:11 http://ports.ubuntu.com jammy-updates/universe arm64 Packages [991 kB]
Пол:12 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe arm64 Packages [991 kB]
Пол:13 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe armhf Packages [818 kB]
Пол:14 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main arm64 Packages [1 071 kB]
Пол:15 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main armhf Packages [778 kB]
Получено 7 777 kB за 4с (2 102 kB/s)                         
Чтение списков пакетов… Готово
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Уже установлен пакет coreutils самой новой версии (8.32-4.1ubuntu1).
Уже установлен пакет tar самой новой версии (1.34+dfsg-1ubuntu0.1.22.04.1).
Будут установлены следующие дополнительные пакеты:
  libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2
Предлагаемые пакеты:
  db5.3-util libapache2-mod-svn subversion-tools
Следующие НОВЫЕ пакеты будут установлены:
  libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2 subversion
Обновлено 0 пакетов, установлено 6 новых пакетов, для удаления отмечено 0 пакетов, и 0 пакетов не обновлено.
Необходимо скачать 2 624 kB архивов.
После данной операции объём занятого дискового пространства возрастёт на 10,2 MB.
Пол:1 http://ports.ubuntu.com jammy-security/main arm64 libapr1 arm64 1.7.0-8ubuntu0.22.04.1 [106 kB]
Пол:2 http://ports.ubuntu.com jammy-security/main arm64 libaprutil1 arm64 1.6.1-5ubuntu4.22.04.1 [93,5 kB]
Пол:3 http://ports.ubuntu.com jammy/universe arm64 libserf-1-1 arm64 1.3.9-10ubuntu2 [49,5 kB]
Пол:4 http://ports.ubuntu.com jammy/universe arm64 libutf8proc2 arm64 2.7.0-3 [73,6 kB]
Пол:5 http://ports.ubuntu.com jammy-security/universe arm64 libsvn1 arm64 1.14.1-3ubuntu0.22.04.1 [1 346 kB]
Пол:6 http://ports.ubuntu.com jammy-security/universe arm64 subversion arm64 1.14.1-3ubuntu0.22.04.1 [955 kB]
Получено 2 624 kB за 1с (3 438 kB/s)  
Выбор ранее не выбранного пакета libapr1:arm64.
(Чтение базы данных … на данный момент установлено 91188 файлов и каталогов.)
Подготовка к распаковке …/0-libapr1_1.7.0-8ubuntu0.22.04.1_arm64.deb …
Распаковывается libapr1:arm64 (1.7.0-8ubuntu0.22.04.1) …
Выбор ранее не выбранного пакета libaprutil1:arm64.
Подготовка к распаковке …/1-libaprutil1_1.6.1-5ubuntu4.22.04.1_arm64.deb …
Распаковывается libaprutil1:arm64 (1.6.1-5ubuntu4.22.04.1) …
Выбор ранее не выбранного пакета libserf-1-1:arm64.
Подготовка к распаковке …/2-libserf-1-1_1.3.9-10ubuntu2_arm64.deb …
Распаковывается libserf-1-1:arm64 (1.3.9-10ubuntu2) …
Выбор ранее не выбранного пакета libutf8proc2:arm64.
Подготовка к распаковке …/3-libutf8proc2_2.7.0-3_arm64.deb …
Распаковывается libutf8proc2:arm64 (2.7.0-3) …
Выбор ранее не выбранного пакета libsvn1:arm64.
Подготовка к распаковке …/4-libsvn1_1.14.1-3ubuntu0.22.04.1_arm64.deb …
Распаковывается libsvn1:arm64 (1.14.1-3ubuntu0.22.04.1) …
Выбор ранее не выбранного пакета subversion.
Подготовка к распаковке …/5-subversion_1.14.1-3ubuntu0.22.04.1_arm64.deb …
Распаковывается subversion (1.14.1-3ubuntu0.22.04.1) …
Настраивается пакет libutf8proc2:arm64 (2.7.0-3) …
Настраивается пакет libapr1:arm64 (1.7.0-8ubuntu0.22.04.1) …
Настраивается пакет libaprutil1:arm64 (1.6.1-5ubuntu4.22.04.1) …
Настраивается пакет libserf-1-1:arm64 (1.3.9-10ubuntu2) …
Настраивается пакет libsvn1:arm64 (1.14.1-3ubuntu0.22.04.1) …
Настраивается пакет subversion (1.14.1-3ubuntu0.22.04.1) …
Обрабатываются триггеры для libc-bin (2.35-0ubuntu3.1) …
Обрабатываются триггеры для man-db (2.10.2-1) …

[ STEPS ] Start initializing the environment...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ INFO ] Set the kernel name: [  ]
[ INFO ] Set the kernel directory: [ stable ]

[ STEPS ] Start downloading kernel...
[ INFO ] Current version: [ 5.15.92 ], Latest version: [ 5.15.100 ].
[ INFO ] Start downloading the kernel from [ https://github.com/ophub/kernel/tree/main/pub/stable/5.15.100 ]
[ INFO ] Download the kernel files to the temporary directory: [ /tmp/tmp.2hsFkUMNwU ]
A    /tmp/tmp.2hsFkUMNwU
A    /tmp/tmp.2hsFkUMNwU/boot-5.15.100-flippy-82+o.tar.gz
A    /tmp/tmp.2hsFkUMNwU/dtb-allwinner-5.15.100-flippy-82+o.tar.gz
A    /tmp/tmp.2hsFkUMNwU/dtb-amlogic-5.15.100-flippy-82+o.tar.gz
A    /tmp/tmp.2hsFkUMNwU/dtb-rockchip-5.15.100-flippy-82+o.tar.gz
A    /tmp/tmp.2hsFkUMNwU/header-5.15.100-flippy-82+o.tar.gz
A    /tmp/tmp.2hsFkUMNwU/modules-5.15.100-flippy-82+o.tar.gz
A    /tmp/tmp.2hsFkUMNwU/sha256sums
Exported revision 809.

[ STEPS ] Start checking the kernel...
[ INFO ] Kernel name: [ 5.15.100-flippy-82+o ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ INFO ] Enable sha256sum checking...
[ INFO ] (1/4) [ boot-5.15.100-flippy-82+o.tar.gz ] file sha256sum check same.
[ INFO ] (2/4) [ dtb-amlogic-5.15.100-flippy-82+o.tar.gz ] file sha256sum check same.
[ INFO ] (3/4) [ header-5.15.100-flippy-82+o.tar.gz ] file sha256sum check same.
[ INFO ] (4/4) [ modules-5.15.100-flippy-82+o.tar.gz ] file sha256sum check same.

[ STEPS ] Start backing up the current kernel...
[ INFO ] (1/4) The [ boot-5.15.92-flippy-81+o.tar.gz ] backup successful.
[ INFO ] (2/4) The [ dtb-amlogic-5.15.92-flippy-81+o.tar.gz ] backup successful.
[ INFO ] (3/4) The [ header-5.15.92-flippy-81+o.tar.gz ] backup successful.
[ INFO ] (4/4) The [ modules-5.15.92-flippy-81+o.tar.gz ] backup successful.
[ INFO ] The [ sha256sums ] file has been generated
[ INFO ] The current kernel backup path: [ /ddbr/backup/5.15.92 ]. It can be deleted if it is not needed.

[ STEPS ] Start unpacking the kernel...
[ INFO ] (1/4) Unpacking [ boot-5.15.100-flippy-82+o.tar.gz ] done.
[ INFO ] (2/4) Unpacking [ dtb-amlogic-5.15.100-flippy-82+o.tar.gz ] done.
[ INFO ] (3/4) Unpacking [ header-5.15.100-flippy-82+o.tar.gz ] done.
[ INFO ] (4/4) Unpacking [ modules-5.15.100-flippy-82+o.tar.gz ] done.

[ STEPS ] Start updating the uboot...
[ INFO ] Write bootloader: [ /usr/lib/u-boot/hk1box-bootloader.img ]

[ SUCCESS ] Successfully updated, automatic restarting...
Connection to 10.42.0.97 closed by remote host.
Connection to 10.42.0.97 closed.

**Comment by Gluk41** [comment]
Dead :(

**Comment by Gluk41** [comment]
Before executing the command:
![Screenshot_20230314_170226](https://user-images.githubusercontent.com/17955884/225028478-4376c9c7-f119-495f-aeb1-e12879baa752.png)
After executing the command:
![Screenshot_20230314_171053](https://user-images.githubusercontent.com/17955884/225028863-2ed71933-3017-4b62-a977-bba9b046ad0a.png)
![Screenshot_20230314_171205](https://user-images.githubusercontent.com/17955884/225028884-7fb949fe-fdae-4b1d-a457-580c7fdc616c.png)
There are no partitions left on a clean, freshly written disk at all.

**Comment by ophub** [comment]
Isn't this where both partitions are? The directory of rootfs is also there. This partition is in ext4 format and can only be recognized under linux. It cannot be recognized under mac and windows.

**Comment by Gluk41** [comment]
This is not normal, without the boot partition, the system does not boot

**Comment by ophub** [comment]
You download today's system for testing, don't use the old system. Write today's system into usb and start again, and send a complete log.

**Comment by Gluk41** [comment]
I did it yesterday, with both cores. It's cooler there, in general, all sections are deleted. I'll show you now

**Comment by ophub** [comment]
Your system information shows that it is one month ago. you download the system today

**Comment by Gluk41** [comment]
Welcome to Armbian 23.02.0-trunk Jammy with Linux 5.15.100-flippy-82+o

System load:   6%               Up time:       1 min
Memory usage:  4% of 3.26G      IP:            10.42.0.51
CPU temp:      48°C             Usage of /:    70% of 2.4G   
storage/:      41% of 252M   

[ General system configuration (beta): armbian-config ]

Last login: Tue Mar 14 18:02:09 2023
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

makc@armbian:~$ cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905x3'
FDTFILE='meson-sm1-x96-max-plus-100m.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='5.15.100'
KERNEL_BRANCH='stable'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='usb'
MLUBOOT_STATUS='no'
AMPART_STATUS='no'
PACKAGED_DATE='2023-03-13'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
makc@armbian:~$ cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-x96-max-plus-100m.dtb
APPEND=root=UUID=cc8c3063-4b77-49f2-b861-cc053dbb67ac rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
makc@armbian:~$ ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 мар 13 07:56 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 757153 мар 13 07:56 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 мар 13 07:56 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 мар 13 07:56 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 мар 13 07:56 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 мар 13 07:56 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 мар 13 07:56 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 мар 13 07:56 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 633376 мар 13 07:56 /boot/u-boot-r3300l.bin
-rwxr-xr-x 1 root root 609247 мар 13 07:56 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 мар 13 07:56 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 мар 13 07:56 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 мар 13 07:56 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 мар 13 07:56 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 мар 13 07:56 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 мар 13 07:56 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 мар 13 07:56 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 мар 13 07:56 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 мар 13 07:56 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 мар 13 07:56 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 мар 13 07:56 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 мар 13 07:56 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 мар 13 07:56 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 мар 13 07:56 /boot/u-boot-zyxq.bin
makc@armbian:~$ lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
sda            8:0    0 57,6G  0 disk 
├─sda1         8:1    0  255M  0 part /boot
└─sda2         8:2    0  2,5G  0 part /var/log.hdd
                                      /
mmcblk2      179:0    0 29,1G  0 disk 
mmcblk2boot0 179:32   0    8M  1 disk 
mmcblk2boot1 179:64   0    8M  1 disk 
zram0        254:0    0  1,6G  0 disk [SWAP]
zram1        254:1    0   50M  0 disk /var/log
zram2        254:2    0    0B  0 disk 
makc@armbian:~$ sudo -i
[sudo] password for makc: 
root@armbian:~# armbian-update
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Start installing the necessary dependencies.
Пол:2 http://ports.ubuntu.com jammy InRelease [270 kB]                            
Пол:3 http://ports.ubuntu.com jammy-security InRelease [110 kB]             
Пол:4 http://ports.ubuntu.com jammy-updates InRelease [119 kB]              
Пол:5 http://ports.ubuntu.com jammy-backports InRelease [107 kB]            
Пол:6 http://ports.ubuntu.com jammy/multiverse armhf Packages [199 kB]      
Пол:7 http://ports.ubuntu.com jammy/restricted arm64 Packages [24,2 kB]           
Пол:8 http://ports.ubuntu.com jammy/multiverse arm64 Packages [224 kB]            
Пол:9 http://ports.ubuntu.com jammy/restricted armhf Packages [13,3 kB]           
Пол:10 http://ports.ubuntu.com jammy/universe armhf Packages [16,8 MB]            
Пол:11 http://ports.ubuntu.com jammy/main armhf Packages [1 701 kB]               
Пол:12 http://ports.ubuntu.com jammy/main arm64 Packages [1 758 kB]               
Пол:13 http://ports.ubuntu.com jammy/universe arm64 Packages [17,2 MB]            
Пол:14 http://ports.ubuntu.com jammy-security/main armhf Packages [485 kB]        
Пол:15 http://ports.ubuntu.com jammy-security/universe arm64 Packages [753 kB]    
Пол:16 http://ports.ubuntu.com jammy-security/main arm64 Packages [751 kB]        
Пол:17 http://ports.ubuntu.com jammy-security/multiverse armhf Packages [594 B]   
Пол:18 http://ports.ubuntu.com jammy-security/restricted armhf Packages [9 804 B] 
Пол:19 http://ports.ubuntu.com jammy-security/universe armhf Packages [589 kB]    
Пол:20 http://ports.ubuntu.com jammy-security/restricted arm64 Packages [371 kB]  
Пол:21 http://ports.ubuntu.com jammy-security/multiverse arm64 Packages [1 421 B] 
Пол:22 http://ports.ubuntu.com jammy-updates/multiverse armhf Packages [3 270 B]  
Пол:23 http://ports.ubuntu.com jammy-updates/main arm64 Packages [1 071 kB]       
Пол:24 http://ports.ubuntu.com jammy-updates/restricted armhf Packages [11,0 kB]  
Пол:25 http://ports.ubuntu.com jammy-updates/universe armhf Packages [818 kB]     
Пол:26 http://ports.ubuntu.com jammy-updates/universe arm64 Packages [991 kB]     
Пол:27 http://ports.ubuntu.com jammy-updates/multiverse arm64 Packages [5 391 B]  
Пол:28 http://ports.ubuntu.com jammy-updates/restricted arm64 Packages [384 kB]   
Пол:29 http://ports.ubuntu.com jammy-updates/main armhf Packages [778 kB]         
Пол:30 http://ports.ubuntu.com jammy-backports/main arm64 Packages [49,0 kB]      
Пол:31 http://ports.ubuntu.com jammy-backports/universe armhf Packages [22,4 kB]  
Пол:32 http://ports.ubuntu.com jammy-backports/main armhf Packages [48,9 kB]      
Пол:33 http://ports.ubuntu.com jammy-backports/universe arm64 Packages [22,4 kB]  
Пол:1 http://mirror.yandex.ru/mirrors/armbian/apt jammy InRelease [52,4 kB]       
Пол:34 http://mirror.yandex.ru/mirrors/armbian/apt jammy/jammy-desktop arm64 Packages [179 kB]
Пол:35 http://mirror.yandex.ru/mirrors/armbian/apt jammy/jammy-desktop armhf Packages [129 kB]
Пол:36 http://mirror.yandex.ru/mirrors/armbian/apt jammy/jammy-utils armhf Packages [43,2 kB]
Пол:37 http://mirror.yandex.ru/mirrors/armbian/apt jammy/jammy-utils arm64 Packages [49,6 kB]
Пол:38 http://mirror.yandex.ru/mirrors/armbian/apt jammy/main armhf Packages [462 kB]
Пол:39 http://mirror.yandex.ru/mirrors/armbian/apt jammy/jammy-utils all Packages [32,1 kB]
Пол:40 http://mirror.yandex.ru/mirrors/armbian/apt jammy/main all Packages [88,6 kB]
Пол:41 http://mirror.yandex.ru/mirrors/armbian/apt jammy/jammy-desktop all Packages [23,1 kB]
Пол:42 http://mirror.yandex.ru/mirrors/armbian/apt jammy/main arm64 Packages [808 kB]
Получено 47,5 MB за 26с (1 802 kB/s)                       
Чтение списков пакетов… Готово
Чтение списков пакетов… Готово
Построение дерева зависимостей… Готово
Чтение информации о состоянии… Готово         
Уже установлен пакет bsdextrautils самой новой версии (2.37.2-4ubuntu3).
Уже установлен пакет coreutils самой новой версии (8.32-4.1ubuntu1).
Будут установлены следующие дополнительные пакеты:
  libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2
Предлагаемые пакеты:
  db5.3-util libapache2-mod-svn subversion-tools ncompress tar-scripts tar-doc
Следующие НОВЫЕ пакеты будут установлены:
  libapr1 libaprutil1 libserf-1-1 libsvn1 libutf8proc2 subversion
Следующие пакеты будут обновлены:
  tar
Обновлено 1 пакетов, установлено 6 новых пакетов, для удаления отмечено 0 пакетов, и 34 пакетов не обновлено.
Необходимо скачать 2 911 kB архивов.
После данной операции объём занятого дискового пространства возрастёт на 10,2 MB.
Пол:1 http://ports.ubuntu.com jammy-security/main arm64 tar arm64 1.34+dfsg-1ubuntu0.1.22.04.1 [287 kB]
Пол:2 http://ports.ubuntu.com jammy-security/main arm64 libapr1 arm64 1.7.0-8ubuntu0.22.04.1 [106 kB]
Пол:3 http://ports.ubuntu.com jammy-security/main arm64 libaprutil1 arm64 1.6.1-5ubuntu4.22.04.1 [93,5 kB]
Пол:4 http://ports.ubuntu.com jammy/universe arm64 libserf-1-1 arm64 1.3.9-10ubuntu2 [49,5 kB]
Пол:5 http://ports.ubuntu.com jammy/universe arm64 libutf8proc2 arm64 2.7.0-3 [73,6 kB]
Пол:6 http://ports.ubuntu.com jammy-security/universe arm64 libsvn1 arm64 1.14.1-3ubuntu0.22.04.1 [1 346 kB]
Пол:7 http://ports.ubuntu.com jammy-security/universe arm64 subversion arm64 1.14.1-3ubuntu0.22.04.1 [955 kB]
Получено 2 911 kB за 1с (3 087 kB/s)  
(Чтение базы данных … на данный момент установлено 37442 файла и каталога.)
Подготовка к распаковке …/tar_1.34+dfsg-1ubuntu0.1.22.04.1_arm64.deb …
Распаковывается tar (1.34+dfsg-1ubuntu0.1.22.04.1) на замену (1.34+dfsg-1build3) …
Настраивается пакет tar (1.34+dfsg-1ubuntu0.1.22.04.1) …
Выбор ранее не выбранного пакета libapr1:arm64.
(Чтение базы данных … на данный момент установлено 37442 файла и каталога.)
Подготовка к распаковке …/0-libapr1_1.7.0-8ubuntu0.22.04.1_arm64.deb …
Распаковывается libapr1:arm64 (1.7.0-8ubuntu0.22.04.1) …
Выбор ранее не выбранного пакета libaprutil1:arm64.
Подготовка к распаковке …/1-libaprutil1_1.6.1-5ubuntu4.22.04.1_arm64.deb …
Распаковывается libaprutil1:arm64 (1.6.1-5ubuntu4.22.04.1) …
Выбор ранее не выбранного пакета libserf-1-1:arm64.
Подготовка к распаковке …/2-libserf-1-1_1.3.9-10ubuntu2_arm64.deb …
Распаковывается libserf-1-1:arm64 (1.3.9-10ubuntu2) …
Выбор ранее не выбранного пакета libutf8proc2:arm64.
Подготовка к распаковке …/3-libutf8proc2_2.7.0-3_arm64.deb …
Распаковывается libutf8proc2:arm64 (2.7.0-3) …
Выбор ранее не выбранного пакета libsvn1:arm64.
Подготовка к распаковке …/4-libsvn1_1.14.1-3ubuntu0.22.04.1_arm64.deb …
Распаковывается libsvn1:arm64 (1.14.1-3ubuntu0.22.04.1) …
Выбор ранее не выбранного пакета subversion.
Подготовка к распаковке …/5-subversion_1.14.1-3ubuntu0.22.04.1_arm64.deb …
Распаковывается subversion (1.14.1-3ubuntu0.22.04.1) …
Настраивается пакет libutf8proc2:arm64 (2.7.0-3) …
Настраивается пакет libapr1:arm64 (1.7.0-8ubuntu0.22.04.1) …
Настраивается пакет libaprutil1:arm64 (1.6.1-5ubuntu4.22.04.1) …
Настраивается пакет libserf-1-1:arm64 (1.3.9-10ubuntu2) …
Настраивается пакет libsvn1:arm64 (1.14.1-3ubuntu0.22.04.1) …
Настраивается пакет subversion (1.14.1-3ubuntu0.22.04.1) …
Обрабатываются триггеры для libc-bin (2.35-0ubuntu3.1) …
Обрабатываются триггеры для man-db (2.10.2-1) …

[ STEPS ] Start initializing the environment...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ INFO ] Kernel branch: [ stable ]
[ INFO ] Kernel download directory: [ stable ]
[ INFO ] Kernel name: [  ]
[ INFO ] Armbian running: [ /dev/sda ].

[ STEPS ] Start downloading kernel...
[ INFO ] Current version: [ 5.15.100 ], Latest version: [ 5.15.100 ].
[ FINISH ] Already the latest version, no need to update.
root@armbian:~# 

Strange. Why is everything working today?

**Comment by Gluk41** [comment]
Good. I'll wait for the kernel update and try again.
