### ISSUE TITLE
RTL8189FTV可以驱动但无法连接WiFi

### ISSUE THREAD

**Issue by taotao108** [ophub/amlogic-s9xxx-armbian#1171]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: 905l
 - Model 数码视讯Q7

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.100
 - Release:Armbian_23.02.0_amlogic_s905lb-r3300l_bullseye_5.15.100_server_2023.03.14

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

在系统中无法使用systemctl start NetworkManager打开网络管理器在使用armbian-config连接WiFi就会出现报错，然后系统无法启动。

![image](https://user-images.githubusercontent.com/69961983/225083304-59e66334-7b09-4ca7-9739-176a8d6ab702.png)

**Comment by ophub** [comment]
等新版内核发布，上游的日志显示修复了这个问题

**Comment by taotao108** [comment]
感谢flippy大佬回复，是否有老版是没有这个问题的？

**Comment by ophub** [comment]
我不是flippy，往后退5个版本的内核支持无线。下一版上游修复了。

**Comment by taotao108** [comment]
谢谢大佬，刚更新的版本支持了吗？

**Comment by ophub** [comment]
等内核更新，f大最近比较忙，没升级内核到最新版。5.15.102，6.1.19内核更新后就可以了。

**Comment by taotao108** [comment]
使用这个命令armbian-update -k 5.15.95就可以了吗？

**Comment by ophub** [comment]
95改102，但是现在还没有内核文件，等更新了内核才能用
