### ISSUE TITLE
STB hg680-fj support

### ISSUE THREAD

**Issue by tblankid** [ophub/amlogic-s9xxx-armbian#1172]
what i need to build armbian for my hg680fj?any tutorial i can use?thanks

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

**Comment by tblankid** [comment]
which dtb i use for hg680fj?

**Comment by ophub** [comment]
I don't know what configuration it is, you can use the firmware similar to his configuration to test according to the supported devices.
