### ISSUE TITLE
所有的S905都不能写入emmc吗？

### ISSUE THREAD

**Issue by God-JohnDiamond** [ophub/amlogic-s9xxx-armbian#1173]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905l]貌似是3b
 - Model [CM211-1]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100]
 - Release: [[bullseye]

**Describe the bug | 问题描述**
所有的S905都不能写入emmc吗？？ U盘使用不太得劲

**Comment by God-JohnDiamond** [comment]
如果真的需要写入，请教下我该怎么弄，有s905l读取emmc地址之类的信息吗

**Comment by ophub** [comment]
已知的都不能

**Comment by God-JohnDiamond** [comment]
是缺什么数据吗 关于emmc的dtb还是什么的

**Comment by ophub** [comment]
7Ji大佬的每个回复都是经典。资深报告。解释的明明白白，并且还给出解决办法。

**Comment by God-JohnDiamond** [comment]
感谢大佬的耐心解答，从根上把我的困惑解决了

**Comment by cc66** [comment]
这个问题是可以解决的，第一扇区大部分都是0，没有意义。分区后，只要重新计算一下校验和即可。

> 晶晨搞GXBB（S905, S905-H）这代的时候把bootloader的位置定死在了eMMC用户区域（主线内核看到的`mmcblk2`）的第一个扇区起，这个位置和主流的分区格式（MBR和GPT）均冲突了。只要写MBR/GPT分区表，就会把bootloader损坏，砖机且无法启动。这么搞，是因为晶晨觉得自己搞出来的专有格式分区表（我的项目[ampart](https://github.com/7Ji/ampart)可以读写这种分区表）给自己的原厂内核用就够了，完全没考虑到非安卓和非原厂内核的使用情景。
> 
> GXBB之后，GXM (S912) 和 GXL(S905X/L/D/W) 起， 他们把bootloader的位置改成了用户区域和启动区域均可以存放（主线内核看到的`mmcblk2`, `mmcblk2boot0`和`mmcblk2boot1`），且是从第二个扇区开始存放，所以可以在eMMC上建立MBR分区表和GPT分区表了，这个仓库里的安装脚本就是在eMMC上创建MBR分区表来安装的，也因此只能在GXM/GXL之后的平台上安装。
> 
> 但是，在GXBB上，安装到eMMC并非不可能（下面信息来自使用S905的小米盒子3C (MDZ-16-AA)）：
> 
> ```
> [root@mi3 ~]# lsblk
> NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
> mmcblk2      179:0    0  3.7G  0 disk 
> └─mmcblk2p1  179:1    0  3.7G  0 part /
> mmcblk2boot0 179:32   0    2M  1 disk 
> mmcblk2boot1 179:64   0    2M  1 disk 
> zram0        254:0    0  932M  0 disk [SWAP]
> [root@mi3 ~]# cat /boot/extlinux/extlinux.conf 
> LABEL   Arch Linux
> LINUX   /boot/vmlinuz-linux-aarch64-flippy
> INITRD  /boot/initramfs-linux-aarch64-flippy.img
> FDT     /boot/dtbs/linux-aarch64-flippy/amlogic/meson-gxbb-p201.dtb
> FDTOVERLAYS /boot/dtbs/overlays/meson-disable-ethernet-mac.dtbo /boot/dtbs/overlays/meson-gxbb-disable-usb1.dtbo
> APPEND  blkdevparts=mmcblk2:-@1M(root) root=/dev/mmcblk2p1 rw audit=0
> ```
> 
> 如你所见，内核可以通过命令行参数`blkdevparts`来直接声明分区，该参数的文档见[kernel.org](https://www.kernel.org/doc/html/latest/block/cmdline-partition.html)
> 
> 然后，启动前环境，有几个不同的方案可以考虑：
> 
> * 使用[我的u-boot fork](https://github.com/7Ji/u-boot)仓库源码，启用配置`CONFIG_ENV_PARTITION`，可以通过在u-boot的环境中这样声明一个与`blkdevparts`格式类似的变量，来规定分区：
>   ```
>   envparts_mmc1=-@1M(root)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   这个是我今天刚搞出来的u-boot分区支持，没有提交主线。上面信息来源的盒子就是这样启动的。
> * 在blkdevparts里多声明几个分区，存储内核等，启动前环境（主线u-boot也好，原厂u-boot也罢）直接从eMMC指定偏移读取内核等，可以参考[我的博文](https://7ji.github.io/embedded/2023/02/20/gxbb-emmc.html)
> * 用原厂u-boot。不使用`blkdevparts`，而是用打了我的[这个patch](https://github.com/7Ji/linux/commit/049bddc86d7e2d1a7727bbc6d268be9cf5e779d2)，启用配置`CONFIG_AMLOGIC_PARTITION`的内核（这边的6.1.某个版本后就打了patch且启用了），设置内核命令行`apt_blkdevs=mmcblk2`来读取晶晨的私有分区表，再配合`ampart`来修改这个分区表。
> * 用主线u-boot，利用otg的USB gadget，或者直接原生网卡，从远程tftp服务器（可以是openwrt路由器）加载内核和dtb，然后直接挂载eMMC上的root
> 
> 当然，上面所有的安装路线，都需要手操。我在这里只给出思路。
> 
> 实际手操安装前，我建议你确定自己能在UEFI启动的x86-84设备上，使用`efibootmgr`手写启动项，不经安装向导，完成一次ArchLinux或者Debian的安装。我不希望被追问分区格式化之类的基础事项，如果你琢磨不透，直接放弃吧。。

**Comment by 7Ji** [comment]
@cc66 

> 这个问题是可以解决的，第一扇区大部分都是0，没有意义。分区后，只要重新计算一下校验和即可。

更新header内，0x50起的，0x10长的对header的sha256sum，可行，但这么搞，没有现成工具很容易算错，多次分区间如果忘记更新也很容易造成惨痛结果。所以我直接没写。

**Comment by fanybook** [comment]
> 已知的都不能

是 s905x3 也不能写入 emmc 么，我写完启动不了

**Comment by 7Ji** [comment]
> > 已知的都不能
> 
> 是 s905x3 也不能写入 emmc 么，我写完启动不了

无关问题，开个新issue吧。这里说的是严格的无后缀S905

**Comment by luodaoyi** [comment]
N1 也刷不了么

**Comment by 7Ji** [comment]
> N1 也刷不了么

N1 是 GXL family 的 S905D

这里说的有问题的是 GXBB family 的 S905

**Comment by luodaoyi** [comment]
我写了好几次 拔掉u盘重启都是进入盒子的recovery 证明没有写入到emmc里面

**Comment by cnteddybear** [comment]
大佬好，我的盒子是BestTV R330L, s905l.已用burning tool刷安卓6.0。现在的问题是无法通过av孔复位启动TF卡或U盘， 也就是无法使用Armbian系统了（目前 s905只能在 TF/SD/USB 中使用）， 目前burning tool能通过usb链接到盒子，并能烧写，有没有一个可以通过burning tool 烧写的镜像文件或者有什么方法能让盒子从U盘、TF卡启动？
谢谢！

**Comment by ophub** [comment]
看文档里写的

**Comment by longfei12k** [comment]
> N1 也刷不了么

怎么样了，到底能不能刷入EMMC N1

**Comment by zhaoxp-xyz** [comment]
我是顺着DM4036搞盒子进来的。
说一下我的感受：
1、hexdump  -s 0 -C -n 4194336 ~/Armbian_24.2.0_amlogic_s905_jammy_5.15.145_server_2024.01.01.img 可以看到至少4M多的空间。
2、盒子里面直接ls /dev/block，可以看到有单独的bootloader设备，除此还有很多别的设备。
3、之前我的bootloader搞坏了，我又想从emmc能进linux系统，于是我按照dd我的tf卡的方式dd了emmc设备，发现还是启动不起来，所以尝试了dd到botloader设备内，就可以从emmc进入了。
7Ji大应该是发现了这个特点，于是有了armpart这个项目。所以理论上有了armpart是一定可以从emmc启动的。

摆在眼前的两个问题就是怎么从tf启动烧录emmc。以及把7Ji大的armpart项目搞到armbian内。

**Comment by 3nyaww** [comment]
> > N1 也刷不了么
> 
> 怎么样了，到底能不能刷入EMMC N1

都不仔细看文的吗？上面说了这里讨论的是不带后缀的S905，N1 是S905**D**，可以刷入EMMC。

**Comment by liangxiwei** [comment]
写入不了emmc那就u盘启动也能用，但文档似乎并没有提及如何使用u盘启动，直接刷系统到u盘就行了，不用安装吗？

**Comment by ophub** [comment]
拿写镜像软件把img写入U盘即可，首页有工具说明

**Comment by gbm777** [comment]
玩客云（ws1608）就是不行的了？（非玩客云pro）

**Comment by uuedxz** [comment]
> 晶晨搞GXBB（S905, S905-H）这代的时候把bootloader的位置定死在了eMMC用户区域（主线内核看到的`mmcblk2`）的第一个扇区起，这个位置和主流的分区格式（MBR和GPT）均冲突了。只要写MBR/GPT分区表，就会把bootloader损坏，砖机且无法启动。这么搞，是因为晶晨觉得自己搞出来的专有格式分区表（我的项目[ampart](https://github.com/7Ji/ampart)可以读写这种分区表）给自己的原厂内核用就够了，完全没考虑到非安卓和非原厂内核的使用情景。
> 
> GXBB之后，GXM (S912) 和 GXL(S905X/L/D/W) 起， 他们把bootloader的位置改成了用户区域和启动区域均可以存放（主线内核看到的`mmcblk2`, `mmcblk2boot0`和`mmcblk2boot1`），且是从第二个扇区开始存放，所以可以在eMMC上建立MBR分区表和GPT分区表了，这个仓库里的安装脚本就是在eMMC上创建MBR分区表来安装的，也因此只能在GXM/GXL之后的平台上安装。
> 
> 但是，在GXBB上，安装到eMMC并非不可能（下面信息来自使用S905的小米盒子3C (MDZ-16-AA)）：
> 
> ```
> [root@mi3 ~]# lsblk
> NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
> mmcblk2      179:0    0  3.7G  0 disk 
> └─mmcblk2p1  179:1    0  3.7G  0 part /
> mmcblk2boot0 179:32   0    2M  1 disk 
> mmcblk2boot1 179:64   0    2M  1 disk 
> zram0        254:0    0  932M  0 disk [SWAP]
> [root@mi3 ~]# cat /boot/extlinux/extlinux.conf 
> LABEL   Arch Linux
> LINUX   /boot/vmlinuz-linux-aarch64-flippy
> INITRD  /boot/initramfs-linux-aarch64-flippy.img
> FDT     /boot/dtbs/linux-aarch64-flippy/amlogic/meson-gxbb-p201.dtb
> FDTOVERLAYS /boot/dtbs/overlays/meson-disable-ethernet-mac.dtbo /boot/dtbs/overlays/meson-gxbb-disable-usb1.dtbo
> APPEND  blkdevparts=mmcblk2:-@1M(root) root=/dev/mmcblk2p1 rw audit=0
> ```
> 
> 如你所见，内核可以通过命令行参数`blkdevparts`来直接声明分区，该参数的文档见[kernel.org](https://www.kernel.org/doc/html/latest/block/cmdline-partition.html)
> 
> 然后，启动前环境，有几个不同的方案可以考虑：
> 
> * 使用[我的u-boot fork](https://github.com/7Ji/u-boot)仓库源码，启用配置`CONFIG_ENV_PARTITION`，可以通过在u-boot的环境中这样声明一个与`blkdevparts`格式类似的变量，来规定分区：
>   ```
>   envparts_mmc1=-@1M(root)
>   ```
>   
>   
>       
>         
>       
>   
>         
>       
>   
>       
>     
>   这个是我今天刚搞出来的u-boot分区支持，没有提交主线。上面信息来源的盒子就是这样启动的。
> * 在blkdevparts里多声明几个分区，存储内核等，启动前环境（主线u-boot也好，原厂u-boot也罢）直接从eMMC指定偏移读取内核等，可以参考[我的博文](https://7ji.github.io/embedded/2023/02/20/gxbb-emmc.html)
> * 用原厂u-boot。不使用`blkdevparts`，而是用打了我的[这个patch](https://github.com/7Ji/linux/commit/049bddc86d7e2d1a7727bbc6d268be9cf5e779d2)，启用配置`CONFIG_AMLOGIC_PARTITION`的内核（这边的6.1.某个版本后就打了patch且启用了），设置内核命令行`apt_blkdevs=mmcblk2`来读取晶晨的私有分区表，再配合`ampart`来修改这个分区表。
> * 用主线u-boot，利用otg的USB gadget，或者直接原生网卡，从远程tftp服务器（可以是openwrt路由器）加载内核和dtb，然后直接挂载eMMC上的root
> 
> 当然，上面所有的安装路线，都需要手操。我在这里只给出思路。
> 
> 实际手操安装前，我建议你确定自己能在UEFI启动的x86-84设备上，使用`efibootmgr`手写启动项，不经安装向导，完成一次ArchLinux或者Debian的安装。我不希望被追问分区格式化之类的基础事项，如果你琢磨不透，直接放弃吧。。

I use Arch, btw (^///^)

**Comment by OneTian1211** [comment]
@ophub @7Ji 两位大佬，能否在安装脚本 fnnas-install 中内置对  S905  设备的支持

**Comment by ophub** [comment]
s905不支持emmc使用，只能在usb使用

**Comment by KawaiiHachimi** [comment]
s905貌似可以不碰原厂bootloader把armbian 内核,initrd,dtb,rootfs写入emmc的cache和userdata分区，设置uboot参数实现无usb纯emmc启动，让ai整理了一下实现文档，我找了个s905b的大麦DM4036盒子试了下成了

https://gist.github.com/KawaiiHachimi/2cc18d11f8a11d10c0b14d4850006813

**Comment by ophub** [comment]
伟大的探索，又开启了一扇门。

**Comment by KawaiiHachimi** [comment]
实现思路来自7Ji大佬的回复消息，也非常依赖7Ji的ampart和ophub大佬的内核，非常感谢！

**Comment by haohao3001** [comment]
自己按着思路搞了个[u-boot](https://github.com/haohao3001/u-boot_p201)，可以读写Amlogic的私有分区，并可以把USB0作为设备模式用(能用fastboot了说是)
