### ISSUE TITLE
大佬你好 我有个全志A33的安卓设备 有木有固件可以刷的？

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#1174]
大佬你好 我有个全志A33的安卓设备 有木有固件可以刷的？

![~47M1%{XCND5_J{30_I} AB](https://user-images.githubusercontent.com/104506675/225229319-17d437dd-2c8a-42bc-bd9c-68f14fb85fc9.jpg)

**Comment by ophub** [comment]
没有这个盒子的系统
