### ISSUE TITLE
能否支持数码视讯 Q5

### ISSUE THREAD

**Issue by qianbinbin** [ophub/amlogic-s9xxx-armbian#1175]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905M
 - Model: 数码视讯 Q5

这个盒子用的人应该挺多的，dtb 是 meson-gxbb-p201.dtb，希望能支持

用过一些老版本 armbian，会出现一些[奇怪的 bug](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1100#issuecomment-1469506688)，概率性无法从 TF 卡启动

谢谢大佬

**Comment by ophub** [comment]
数码视讯Q7 s905L用的meson-gxl-s905x-p212.dtb
数码视讯Q5 s905L 用的meson-gxbb-p201.dtb
或者
meson-gxbb-nexbox-a95x.dtb

u-boot：u-boot-p212.bin

你下载s905x的固件，改下/boot/uEnv.txt里的dtb名称试试

**Comment by qianbinbin** [comment]
谢谢大佬，S905M 和 S905L 是一样的吗？我之前用的就是 meson-gxbb-p201.dtb

另外，大佬对我提到的那个概率性无法从 TF 卡启动有什么看法吗，有排查的方法也行

一旦碰上了就要找显示器，遥控器，恢复出厂，十分难受，我本来以为是 TF 卡文件损坏什么的，但是把安卓恢复出厂就可以了。。

**Comment by ophub** [comment]
安卓改了armbian权限: 你把写有armbian的卡插入正在运行中的安卓系统，安卓系统会给/boot里写一些数据，也会改rootfs下的文件权限，导致armbian无法正带运行。


armbian破坏了安卓分区表：在tf卡使用armbian，由emmc里面的安卓系统分区的bootloader 引导起动，只要不损坏emmc前4 M分区的内容，一般都不会影响到起动。在使用armbian时使用dd命令时注意点，别把/dev/mmcblk前4 M写入数据。
其他位置也有一些保护，具体用https://github.com/7Ji/ampart看一下。

偶尔某个版本的内核可能会不能用tf/sd启动，但可以用usb启动。现在没有关闭的问题里，反馈gtk-pro不用连无线的这个朋友就反馈过两次这个问题，过几版上游又修复好了。

原因有多种，凭空不好猜你是什么情况。

**Comment by qianbinbin** [comment]
> 数码视讯Q7 s905L用的meson-gxl-s905x-p212.dtb 数码视讯Q5 s905L 用的meson-gxbb-p201.dtb 或者 meson-gxbb-nexbox-a95x.dtb
> 
> u-boot：u-boot-p212.bin
> 
> 你下载s905x的固件，改下/boot/uEnv.txt里的dtb名称试试

使用 u-boot-p212.bin 后无限重启

去掉后可以启动，但无论 meson-gxbb-p201.dtb 还是 meson-gxbb-nexbox-a95x.dtb 都无法使用有线网

**Comment by qianbinbin** [comment]
> meson-gxbb-p201.dtb u-boot-s905.bin
> 
> 你复制这个u-boot试试，在USB里刷个armbian，`/boot/uEnv.txt`里的dtb改成：`meson-gxbb-p201.dtb`
> 
> u-boot在usb启动后，再复制：
> 
> ```
> cd /boot
> cp -f u-boot-s905.bin u-boot.ext
> chmod +x u-boot.ext
> sync
> reboot
> ```

这个应该是对的，我之后又下载了[官方社区版](https://redirect.armbian.com/aml-s9xx-box/archive/)碰碰运气，没想到可以了，用的就是这两个文件，除了无线网 log 跳脸以外一切正常，loglevel=4 就清净了

**Comment by ophub** [comment]
好的，我加到可用列表里。
启用extlinux.conf时，uEnv.txt也要一起改，都会用到的

**Comment by qianbinbin** [comment]
社区版的镜像只有 extlinux.conf，没有 uEnv.txt，我只改了 extlinux.conf 是可以使用的

安卓我用的是人中日月分享的卡刷包，ROM 作者是胡莱先生：https://www.bilibili.com/read/cv2970639

Q5 北京联通版线刷包+刷机工具（也是胡莱的 ROM）：https://pan.baidu.com/s/1747VhPp-b6t4FbTtGE3hiA?pwd=sm14 ，因为 Q5 有很多版本，我不确定是不是所有版本能用，但救砖应该没啥问题

**Comment by ophub** [comment]
好的👌

**Comment by fly-high2016** [comment]
Q5北京移动版S905M 1G RAM 8G EMMC实测可以刷[qianbinbin]提到的两个包，另外还可以刷ATV 5.1.1参考http://www.zndstec.com/?p=152

**Comment by qianbinbin** [comment]
ok，多谢

________________________________

**Comment by ophub** [comment]
多谢分享，安卓固件我转存到了这里：
https://github.com/ophub/kernel/releases/tag/tools

**Comment by Saintlord77** [comment]
能否支持8189es wif驱动
我试图用https://www.right.com.cn/forum/thread-5428012-1-1.html这里面的方法编译驱动，但失败了。

root@armbian:~/rtl8189ES_linux# make -j4 ARCH=arm64 KSRC=/usr/lib/modules/$(uname -r)/build
make ARCH=arm64 CROSS_COMPILE= -C /usr/lib/modules/6.1.26-ophub/build M=/root/rtl8189ES_linux  modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.26-ophub'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  CC [M]  /root/rtl8189ES_linux/core/rtw_cmd.o
  CC [M]  /root/rtl8189ES_linux/core/rtw_security.o
  CC [M]  /root/rtl8189ES_linux/core/rtw_debug.o
  CC [M]  /root/rtl8189ES_linux/core/rtw_io.o
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_io.o] Error 126
make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_io.o'
make[2]: *** Waiting for unfinished jobs....
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_security.o] Error 126
make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_security.o'
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_cmd.o] Error 126
make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_cmd.o'
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_debug.o] Error 126
make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_debug.o'
make[1]: *** [Makefile:2012: /root/rtl8189ES_linux] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.26-ophub'
make: *** [Makefile:2292: modules] Error 2

是内核不支持吧，官方会修好这个驱动吗？

**Comment by leeyinghui1107** [comment]
> 能否支持8189es wif驱动 我试图用[https://www.right.com.cn/forum/thread-5428012-1-1.html这里面的方法编译驱动，但失败了。](https://www.right.com.cn/forum/thread-5428012-1-1.html%E8%BF%99%E9%87%8C%E9%9D%A2%E7%9A%84%E6%96%B9%E6%B3%95%E7%BC%96%E8%AF%91%E9%A9%B1%E5%8A%A8%EF%BC%8C%E4%BD%86%E5%A4%B1%E8%B4%A5%E4%BA%86%E3%80%82)
> 
> root@armbian:~/rtl8189ES_linux# make -j4 ARCH=arm64 KSRC=/usr/lib/modules/$(uname -r)/build make ARCH=arm64 CROSS_COMPILE= -C /usr/lib/modules/6.1.26-ophub/build M=/root/rtl8189ES_linux modules make[1]: Entering directory '/usr/src/linux-headers-6.1.26-ophub' warning: the compiler differs from the one used to build the kernel The kernel was built by: aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205 You are using: gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0 CC [M] /root/rtl8189ES_linux/core/rtw_cmd.o CC [M] /root/rtl8189ES_linux/core/rtw_security.o CC [M] /root/rtl8189ES_linux/core/rtw_debug.o CC [M] /root/rtl8189ES_linux/core/rtw_io.o /bin/sh: 1: scripts/basic/fixdep: Exec format error make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_io.o] Error 126 make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_io.o' make[2]: *** Waiting for unfinished jobs.... /bin/sh: 1: scripts/basic/fixdep: Exec format error make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_security.o] Error 126 make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_security.o' /bin/sh: 1: scripts/basic/fixdep: Exec format error make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_cmd.o] Error 126 make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_cmd.o' /bin/sh: 1: scripts/basic/fixdep: Exec format error make[2]: *** [scripts/Makefile.build:250: /root/rtl8189ES_linux/core/rtw_debug.o] Error 126 make[2]: *** Deleting file '/root/rtl8189ES_linux/core/rtw_debug.o' make[1]: *** [Makefile:2012: /root/rtl8189ES_linux] Error 2 make[1]: Leaving directory '/usr/src/linux-headers-6.1.26-ophub' make: *** [Makefile:2292: modules] Error 2
> 
> 是内核不支持吧，官方会修好这个驱动吗？

这个是我编译好的驱动，
链接: https://pan.baidu.com/s/1yFdm7J_wvRj-pg-WArnNiQ?pwd=cwz6 提取码: cwz6

编译方法看我的帖子：https://www.right.com.cn/forum/thread-8257102-1-1.html
https://www.right.com.cn/forum/thread-8257102-1-1.html

**Comment by alanfans** [comment]
数据视讯Q5刷高版本内核5 15写入emmc
https://www.youtube.com/watch?v=xDNllDqoRiQ

**Comment by Saintlord77** [comment]
> cwz6
谢谢回复，我现在的Q5就是参考您的帖子，使用的您的驱动。但是5.15始终没有可用的驱动，参考帖子的方法也没有编译成功。

**Comment by leeyinghui1107** [comment]
> > cwz6
> > 谢谢回复，我现在的Q5就是参考您的帖子，使用的您的驱动。但是5.15始终没有可用的驱动，参考帖子的方法也没有编译成功。

您的q5是什么版本？这个驱动我自己用在q5、q7上，包括6.x的内核都可以的啊；写完armbian镜像，直接复制到/root，然后系统启动起来，执行两条命令就可以了。

**Comment by Saintlord77** [comment]
> 

这两天我再试一试，上次试了试不行，可能我的方法不对

**Comment by Saintlord77** [comment]
> 
cp 8189es.ko /usr/lib/modules/6.1.35-ophub/kernel/drivers/net/wireless/realtek/rtl8189es
depmod -a
modprobe 8189es

返回错误值：modprobe: ERROR: could not insert '8189es': Exec format error

版本是Armbian 23.08.0-trunk Jammy with Linux 6.1.35-ophub

**Comment by ShuChang1983** [comment]
q5我用s905x能进u盘能跑马，就是后面安装到里面的时候型号没有这个怎么高，求大神指教，用的也是meson-gxbb-p201.dtb改了才能进后台

**Comment by ophub** [comment]
根据自己使用的dtb，选择和你相同的安装

**Comment by xiaoji235** [comment]
> 数码视讯Q7 s905L用的meson-gxl-s905x-p212.dtb 数码视讯Q5 s905L 用的meson-gxbb-p201.dtb 或者 meson-gxbb-nexbox-a95x.dtb
> 
> u-boot：u-boot-p212.bin
> 
> 你下载s905x的固件，改下/boot/uEnv.txt里的dtb名称试试

北京视讯Q5有两款，处理器不同，一款用的是 amlogic s905L，另一款是amlogic s905m2，在搭载amlogic s905m2的Q5设备上使用以上boot和dtb卡在开机界面不断重启，我也更换了s905x和s905x2镜像仍旧无法通过u盘进入armbian

**Comment by rmoyulong** [comment]
> > 数码视讯Q7 s905L用的meson-gxl-s905x-p212.dtb 数码视讯Q5 s905L 用的meson-gxbb-p201.dtb 或者 meson-gxbb-nexbox-a95x.dtb
> > u-boot：u-boot-p212.bin
> > 你下载s905x的固件，改下/boot/uEnv.txt里的dtb名称试试
> 
> 北京视讯Q5有两款，处理器不同，一款用的是 amlogic s905L，另一款是amlogic s905m2，在搭载amlogic s905m2的Q5设备上使用以上boot和dtb卡在开机界面不断重启，我也更换了s905x和s905x2镜像仍旧无法通过u盘进入armbian

请问您的amlogic s905m2的安卓刷机包能共享一下吗？

**Comment by lingchen-jiager** [comment]
感谢各位的讨论，我也把我成功的经验分享在这，方便后来人检索到。
# 设备：
河北联通utstarcom iptv机顶盒
型号：mc8638s
芯片：s905m
P/N号2706结尾。
内存1G+4G
---
# 过程
先将原版系统刷机成第三方系统，步骤参考如下链接：
- https://blog.csdn.net/fatiaozhang9527/article/details/133285366
刷好后，找一个8g的u盘，使用rufus将armbian的镜像img文件刷写到u盘里，img文件我在这个仓库找到的s905的倒也能用，但是太大，所以使用的是armbian社区镜像：https://www.armbian.com/amlogic-s9xx-tv-box/

使用这个镜像需要将boot里的extlinux.conf文件中的fdt /dtb/amlogic/meson-gxl-s905x-p212.dtb更改为fdt /dtb/amlogic/*meson-gxbb-p201*.dtb。将u-boot-s905文件重命名为u-boot.ext（不重命名的话进不了系统）。


然后拔出u盘，插到机顶盒的usb口，注意需要插入远离hdmi接口的usb。然后在机顶盒系统中，恢复出厂设置，机顶盒就会重启，从u盘启动了。我并未尝试将系统写入emmc，只是尝试了在u盘运行。

这个版本的社区镜像还不错，装上之后wifi网卡自动识别出来了，不像有的镜像缺少网卡驱动。我之前也尝试过没有网卡驱动的镜像，有些使用modprobe 8189es加载驱动后就正常了，但有些没有8189es驱动，就很麻烦。

相同设备可以尝试此镜像，也欢迎相同设备的朋友推荐其它镜像。
