### ISSUE TITLE
m401a操作失误黑屏，如何解救

### ISSUE THREAD

**Issue by roseybear098765** [ophub/amlogic-s9xxx-armbian#1177]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [m401a]

**Armbian Version | 系统版本**
Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.100_server_2023.03.12.img

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
因为内存识别不足，2g的才识别974m，已安装到emmc
u-boot-e900v22c.bin复制改名u-boot.emmc放到boot下，进不去emmc系统了。

现在想用u盘进入系统，删除boot/u-boot.emmc文件，至少还能用，

![image](https://user-images.githubusercontent.com/126083712/225662081-4f15ab97-9000-40dd-8f89-378153e0d4a1.png)
![image](https://user-images.githubusercontent.com/126083712/225662269-0a8c1b35-2bf6-4ff6-b721-28251dac0cda.png)

请o大及各位不吝指点，
1，如何删除emmc里boot/u-boot.emmc文件
2，如何识别2g ram
谢谢

**Comment by roseybear098765** [comment]
u盘系统也将u-boot-e900v22c.bin复制改名为u-boot.ext，放到boot下，ram也没完整识别，但是不会黑屏，还能正常使用

**Comment by roseybear098765** [comment]
12.12 内存大小识别错误
如果内存大小识别不正确（4G内存识别为1-2G是不正常，识别为3.7G是正常），可以尝试手动复制一份 /boot/UBOOT_OVERLOAD 文件（注意是复制一份，不要改名，改名后安装与更新等操作后将无法启动），在 USB 中使用时另存为 /boot/u-boot.ext，在 eMMC 中使用时另存为 /boot/u-boot.emmc。

除了想尝试解决内存的问题外，不要手动复制 u-boot 文件，添加不正确会导致无法启动以及出现各种问题。

UBOOT_OVERLOAD 没找到呢！不要手动复制，是要用命令吗，

**Comment by roseybear098765** [comment]
ophub commented on Nov 26, 2022 • 
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

内存看12.12
先在usb测试：

cd /boot
cp u-boot-e900v22c.bin u-boot.ext
sync && reboot
重启内存对了（正常是1.7g左右）
重新按命令操作，重启后，没有变化呢！如下，不知道哪里姿势不对呢！
![image](https://user-images.githubusercontent.com/126083712/225680370-d05a0a41-2579-4040-a3e8-f6da24a33c93.png)


再处理emmc里面的，如果你已经写入了emmc就不用再写入了，拔了USB，重新拔电重启，进入系统后这样复制：

cd /boot
cp u-boot-e900v22c.bin u-boot.emmc
sync && reboot


原来o大已经说过了呢!谢谢

**Comment by ophub** [comment]
别两个分区同时挂载到一个目录，这会混改了数据。你boot文件要处理，就只挂载这个目录，等删了文件，卸载了boot。想看看rootfs再挂载它。或者你在mnt下创建两个目录，同时分别挂载不同分区

**Comment by roseybear098765** [comment]
用emmc系统登录，命令行输入（一次一行）
cd /boot
cp u-boot-e900v22c.bin u-boot.emmc
sync && reboot
还是黑屏进不去emmc系统，

又只能进u盘系统了，
mkdir /mnt/1/ 
mount /dev/mmcblk2p1 /mnt/1/
找到/mnt/1u-boot.emmc，删除，重启就可以进入emmc系统

**Comment by roseybear098765** [comment]
用emmc系统登录，命令行输入（一次一行）
cd /boot
cp u-boot-e900v22c.bin u-boot.emmc
sync && reboot
还是黑屏进不去emmc系统，

又只能进u盘系统了，
mkdir /mnt/1/ 
mount /dev/mmcblk2p1 /mnt/1/
找到/mnt/1u-boot.emmc，删除，重启就可以进入emmc系统

**Comment by roseybear098765** [comment]
目前内存识别不足问题，还无法解决

**Comment by ophub** [comment]
安装armbian前刷过安卓9的系统吗？

**Comment by roseybear098765** [comment]
没留意过呢，刷android是为了刷armbian的，
线刷的是1-b863av3.2-m-线刷包，创维界面的
