### ISSUE TITLE
自编译出错

### ISSUE THREAD

**Issue by God-JohnDiamond** [ophub/amlogic-s9xxx-armbian#1178]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3b]
 - Model [cm211-1]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.18]
 - Release: [bullseye]

**Describe the bug | 问题描述**
fork 后编译出错 貌似是内核部分出错了？地址尝试换过 也是一样的错误

![b076b3442c5992723eecf4d1b8f2435](https://user-images.githubusercontent.com/23442889/225856230-8f86ea86-1f17-4c52-a832-cfe09b35d317.png)

下面是设置以及修改过的地方

![d21c5c360676cfe10edbffc4ec17c5a](https://user-images.githubusercontent.com/23442889/225856291-364dd913-ae1b-4111-9cf2-ee4690aa504d.png)

![a1d5424cbf6c7dafe7eab94ff82d4af](https://user-images.githubusercontent.com/23442889/225856327-092c4c96-b818-400d-b6bd-aaf228cfc53d.png)

修改过这几个repo地址
![5e6c18c2a829c74e207e13a49592af8](https://user-images.githubusercontent.com/23442889/225856347-bf53a047-6abf-4393-9aeb-cbfaee84cdba.png)

**Comment by ophub** [comment]
上游armbian最近更新炸了，有一周不能编译了，等修复吧。

**Comment by God-JohnDiamond** [comment]
TE: 61572

BL2 Built : 13:36:55, Jun 22 2020. 
gxl g85d6ad1 - longyong.chen@droid02-sz

Board ID = 4, adc=301
set vcck to 1070 mv
set vddee to 1070 mv
CARD_3 high, old board
CPU clk: 1200MHz

DDR3 chl: Rank0+1 @ 792MHz - FAIL
DDR3 chl: Rank0 @ 792MHz
bist_test rank: 0 21 01 41 37 16 59 1f 00 3f 38 17 59 22 01 44 37 16 59 22 00 45 38 13 5d 612   - PASS

Rank0: 2048MB(auto)-2T-11
AddrBus test pass!
-s
Load fip header from eMMC, src: 0x0000c200, des: 0x01400000, size: 0x00004000
New fip structure!
Load bl30 from eMMC, src: 0x00010200, des: 0x013c0000, size: 0x00007600
Load bl301 from eMMC, src: 0x00018200, des: 0x01380000, size: 0x00002400
Load bl31 from eMMC, src: 0x0001c200, des: 0x10100000, size: 0x00019600
Load bl33 from eMMC, src: 0x00038200, des: 0x01000000, size: 0x0007b000
NOTICE:  BL3-1: v1.0(debug):361f8a7
NOTICE:  BL3-1: Built : 16:43:26, Dec 19 2018
NOTICE:  BL31: GXL normal boot!
NOTICE:  BL31: BL33 decompress pass
[Image: gxl_v1.1.3103-9234004 2018-12-27 10:43:23 yao.zhang@droid07]
efuse init ops = c5
efuse init hdcp = c, cf9=7
x2_hp_e = 0
bl30: check_permit, count is 1
bl30: check_permit: ok!
chipid: 0 0 3 c c 0 14 b3 78 a0 0 c5 not ES chip
[0.614099 Inits done]
INFO:    BL3-1: Initializing runtime services
WARNING: No OPTEE provided by BL2 boot loader
ERROR:   Error initializing runtime service opteed_fast
INFO:    BL3-1: Preparing for EL3 exit to normal world
INFO:    BL3-1: Next image address = 0x1000000
INFO:    BL3-1: Next image spsr = 0x3c9
DRAM:  
MMC:    In:    Out:   Err:   wipe_data=successfulSecd
wipe_cache=successful
store init flag
store read name addr off|partition size
    read 'size' bytes starting at offset 'off'
    to/from memory address 'addr', skipping bad blocks.
store write name addr off|partition size
    write 'size' bytes starting at offset 'off'
    to/from memory address 'addr', skipping bad blocks.
store rom_write add off size.
        write uboot to the boot device
store erase boot/data: 
        erase the area which is uboot or data 
store erase partition <partition_name>: 
        erase the area which partition in u-boot 
store erase dtb 
store erase key 
store disprotect key 
store rom_protect on/off 
store scrub off|partition size
        scrub the area from offset and size 
store dtb iread/read/write addr <size>
        read/write dtb, size is optional 
store key read/write addr <size>
        read/write key, size is optional 
store mbr addr
   update mbr/partition table by dtb

upgrade_step=2
[BL31]: tee size: 0
rebootmode=cold_boot


Starting the controller
 ()
 ()
[BL31]: tee size: 0
[BL31]: tee size: 0
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 6.1.18-flippy-82+ (root@vm25) (Ubuntu clang version 14.0.0-1ubuntu1, Ubuntu LLD 14.0.0) #50 SMP Sat Mar 11 22:59:20 CST 2023
[    0.000000] Machine model: Amlogic Meson GXL (S905L2) X7 5G Tv Box
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000006b400000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000007fffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000000ffffff]
[    0.000000]   node   0: [mem 0x0000000001000000-0x0000000004ffffff]
[    0.000000]   node   0: [mem 0x0000000005000000-0x00000000072fffff]
[    0.000000]   node   0: [mem 0x0000000007300000-0x000000000fffffff]
[    0.000000]   node   0: [mem 0x0000000010000000-0x00000000101fffff]
[    0.000000]   node   0: [mem 0x0000000010200000-0x000000007fffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x000000007fffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv0.2 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: Trusted OS migration not required
[    0.000000] percpu: Embedded 19 pages/cpu s37992 r8192 d31640 u77824
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: ARM erratum 845719
[    0.000000] alternatives: applying boot alternatives
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 516096
[    0.000000] Kernel command line: root=UUID=b67dd11d-7c3d-49de-a922-96ceeb464adf rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_ena8
[    0.000000] The swapaccount= commandline option is deprecated. Please report your usecase to linux-mm@kvack.org if you depend on this functionality.
[    0.000000] Unknown kernel command line parameters "cgroup_enable=memory cgroup_memory=1 mac=ee:14:da:ac:d7:98", will be passed to user space.
[    0.000000] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 1705040K/2097152K available (17024K kernel code, 2908K rwdata, 7728K rodata, 2240K init, 888K bss, 129968K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000000] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000567] Console: colour dummy device 80x25
[    0.000869] printk: console [tty0] enabled
[    0.000925] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=96000)
[    0.000946] pid_max: default: 32768 minimum: 301
[    0.001139] LSM: Security Framework initializing
[    0.001250] SELinux:  Initializing.
[    0.001510] Mount-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.001533] Mountpoint-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.003241] cblist_init_generic: Setting adjustable number of callback queues.
[    0.003280] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.003430] rcu: Hierarchical SRCU implementation.
[    0.003443] rcu:     Max phase no-delay instances is 1000.
[    0.004774] EFI services will not be available.
[    0.005174] smp: Bringing up secondary CPUs ...
[    0.005714] Detected VIPT I-cache on CPU1
[    0.005856] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.006470] Detected VIPT I-cache on CPU2
[    0.006594] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.007167] Detected VIPT I-cache on CPU3
[    0.007283] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.007355] smp: Brought up 1 node, 4 CPUs
[    0.007414] SMP: Total of 4 processors activated.
[    0.007424] CPU features: detected: 32-bit EL0 Support
[    0.007433] CPU features: detected: 32-bit EL1 Support
[    0.007443] CPU features: detected: CRC32 instructions
[    0.007507] CPU: All CPU(s) started at EL2
[    0.007524] alternatives: applying system-wide alternatives
[    0.009995] devtmpfs: initialized
[    0.017232] Registered cp15_barrier emulation handler
[    0.017270] Registered setend emulation handler
[    0.017430] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.017461] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.023836] prandom: seed boundary self test passed
[    0.025062] prandom: 100 self tests passed
[    0.025118] pinctrl core: initialized pinctrl subsystem
[    0.025647] DMI not present or invalid.
[    0.026071] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.027249] DMA: preallocated 2048 KiB GFP_KERNEL pool for atomic allocations
[    0.027785] DMA: preallocated 2048 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.028114] DMA: preallocated 2048 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.028196] audit: initializing netlink subsys (disabled)
[    0.028453] audit: type=2000 audit(0.024:1): state=initialized audit_enabled=0 res=1
[    0.029555] thermal_sys: Registered thermal governor 'step_wise'
[    0.029638] cpuidle: using governor ladder
[    0.029857] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.029965] ASID allocator initialised with 65536 entries
[    0.030123] Serial: AMBA PL011 UART driver
[    0.040938] platform d0100000.vpu: Fixed dependency cycle(s) with /soc/hdmi-tx@c883a000
[    0.043831] platform d0100000.vpu: Fixed dependency cycle(s) with /cvbs-connector
[    0.044073] platform c883a000.hdmi-tx: Fixed dependency cycle(s) with /hdmi-connector
[    0.052595] HugeTLB: registered 1.00 GiB page size, pre-allocated 0 pages
[    0.052627] HugeTLB: 0 KiB vmemmap can be freed for a 1.00 GiB page
[    0.052640] HugeTLB: registered 32.0 MiB page size, pre-allocated 0 pages
[    0.052649] HugeTLB: 0 KiB vmemmap can be freed for a 32.0 MiB page
[    0.052660] HugeTLB: registered 2.00 MiB page size, pre-allocated 0 pages
[    0.052669] HugeTLB: 0 KiB vmemmap can be freed for a 2.00 MiB page
[    0.052680] HugeTLB: registered 64.0 KiB page size, pre-allocated 0 pages
[    0.052689] HugeTLB: 0 KiB vmemmap can be freed for a 64.0 KiB page
[    0.053651] cryptd: max_cpu_qlen set to 1000
[    0.121466] raid6: neonx8   gen()  2292 MB/s
[    0.189532] raid6: neonx4   gen()  2273 MB/s
[    0.257605] raid6: neonx2   gen()  2118 MB/s
[    0.325667] raid6: neonx1   gen()  1719 MB/s
[    0.393729] raid6: int64x8  gen()  1502 MB/s
[    0.461801] raid6: int64x4  gen()  1620 MB/s
[    0.529867] raid6: int64x2  gen()  1384 MB/s
[    0.597943] raid6: int64x1  gen()  1162 MB/s
[    0.597953] raid6: using algorithm neonx8 gen() 2292 MB/s
[    0.665977] raid6: .... xor() 1684 MB/s, rmw enabled
[    0.665987] raid6: using neon recovery algorithm
[    0.666253] fbcon: Taking over console
[    0.666295] ACPI: Interpreter disabled.
[    0.668149] iommu: Default domain type: Translated 
[    0.668180] iommu: DMA domain TLB invalidation policy: strict mode 
[    0.668649] SCSI subsystem initialized
[    0.669155] usbcore: registered new interface driver usbfs
[    0.669201] usbcore: registered new interface driver hub
[    0.669238] usbcore: registered new device driver usb
[    0.669710] mc: Linux media interface: v0.10
[    0.669740] videodev: Linux video capture interface: v2.00
[    0.669933] EDAC MC: Ver: 3.0.0
[    0.671069] Advanced Linux Sound Architecture Driver Initialized.
[    0.671962] vgaarb: loaded
[    0.672436] clocksource: Switched to clocksource arch_sys_counter
[    0.672756] VFS: Disk quotas dquot_6.6.0
[    0.672817] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.672959] FS-Cache: Loaded
[    0.673155] pnp: PnP ACPI: disabled
[    0.679539] NET: Registered PF_INET protocol family
[    0.679747] IP idents hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.681396] tcp_listen_portaddr_hash hash table entries: 1024 (order: 2, 16384 bytes, linear)
[    0.681449] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.681482] TCP established hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.681670] TCP bind hash table entries: 16384 (order: 7, 524288 bytes, linear)
[    0.682121] TCP: Hash tables configured (established 16384 bind 16384)
[    0.682418] MPTCP token hash table entries: 2048 (order: 3, 49152 bytes, linear)
[    0.682524] UDP hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.682576] UDP-Lite hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    0.682750] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.682782] NET: Registered PF_XDP protocol family
[    0.682802] PCI: CLS 0 bytes, default 64
[    0.683305] Trying to unpack rootfs image as initramfs...
[    0.692732] hw perfevents: enabled with armv8_cortex_a53 PMU driver, 7 counters available
[    0.693374] kvm [1]: IPA Size Limit: 40 bits
[    0.696064] kvm [1]: vgic interrupt IRQ9
[    0.696213] kvm [1]: Hyp mode initialized successfully
[    0.698361] Initialise system trusted keyrings
[    0.698664] workingset: timestamp_bits=46 max_order=19 bucket_order=0
[    0.705077] zbud: loaded
[    0.706843] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    0.707391] fuse: init (API version 7.37)
[    0.708101] SGI XFS with ACLs, security attributes, quota, no debug enabled
[    0.747995] NET: Registered PF_ALG protocol family
[    0.748091] xor: measuring software checksum speed
[    0.751381]    8regs           :  3022 MB/sec
[    0.754567]    32regs          :  3148 MB/sec
[    0.758416]    arm64_neon      :  2589 MB/sec
[    0.758442] xor: using function: 32regs (3148 MB/sec)
[    0.758463] Key type asymmetric registered
[    0.758483] Asymmetric key parser 'x509' registered
[    0.758615] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 245)
[    0.758828] io scheduler mq-deadline registered
[    0.758845] io scheduler kyber registered
[    0.759026] io scheduler bfq registered
[    0.803633] irq_meson_gpio: 110 to 8 gpio interrupt mux initialized
[    0.822742] soc soc0: Amlogic Meson Unknown (Unknown) Revision 2a:e (c5:2) Detected
[    0.825410] Serial: 8250/16550 driver, 5 ports, IRQ sharing enabled
[    0.827711] Serial: AMBA driver
[    0.828211] c81004c0.serial: ttyAML0 at MMIO 0xc81004c0 (irq = 18, base_baud = 1500000) is a meson_uart
[    1.322968] Freeing initrd memory: 8260K
[    1.325792] printk: console [ttyAML0] enabled
[    1.863181] brd: module loaded
[    1.867585] loop: module loaded
[    1.874409] usbcore: registered new interface driver cdc_wdm
[    1.874499] usbcore: registered new interface driver usb-storage
[    1.880548] usbcore: registered new interface driver usbserial_generic
[    1.886917] usbserial: USB Serial support registered for generic
[    1.892854] usbcore: registered new interface driver ch341
[    1.898276] usbserial: USB Serial support registered for ch341-uart
[    1.904494] usbcore: registered new interface driver cp210x
[    1.910005] usbserial: USB Serial support registered for cp210x
[    1.915878] usbcore: registered new interface driver ftdi_sio
[    1.921574] usbserial: USB Serial support registered for FTDI USB Serial Device
[    1.928818] usbcore: registered new interface driver garmin_gps
[    1.934673] usbserial: USB Serial support registered for Garmin GPS usb/tty
[    1.941589] usbcore: registered new interface driver ipw
[    1.946835] usbserial: USB Serial support registered for IPWireless converter
[    1.953917] usbcore: registered new interface driver opticon
[    1.959514] usbserial: USB Serial support registered for opticon
[    1.965472] usbcore: registered new interface driver pl2303
[    1.970984] usbserial: USB Serial support registered for pl2303
[    1.976867] usbcore: registered new interface driver qcaux
[    1.982283] usbserial: USB Serial support registered for qcaux
[    1.988071] usbcore: registered new interface driver qcserial
[    1.993771] usbserial: USB Serial support registered for Qualcomm USB modem
[    2.000664] usbcore: registered new interface driver symbolserial
[    2.006693] usbserial: USB Serial support registered for symbol
[    2.013170] mousedev: PS/2 mouse device common for all mice
[    2.019070] SPI driver rmi4_spi has no spi_device_id for syna,rmi4-spi
[    2.025365] meson-vrtc c81000a8.rtc: registered as rtc0
[    2.029738] meson-vrtc c81000a8.rtc: setting system clock to 1970-01-01T00:00:02 UTC (2)
[    2.038233] i2c_dev: i2c /dev entries driver
[    2.043740] Registered IR keymap rc-cec
[    2.045897] rc rc0: meson_ao_cec as /devices/platform/soc/c8100000.bus/c8100100.cec/rc/rc0
[    2.054097] input: meson_ao_cec as /devices/platform/soc/c8100000.bus/c8100100.cec/rc/rc0/input0
[    2.065550] sdhci: Secure Digital Host Controller Interface driver
[    2.068810] sdhci: Copyright(c) Pierre Ossman
[    2.073093] Synopsys Designware Multimedia Card Interface Driver
[    2.079934] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.080530] meson-gx-mmc d0072000.mmc: Got CD GPIO
[    2.081026] meson-gx-mmc d0074000.mmc: allocated mmc-pwrseq
[    2.094955] ledtrig-cpu: registered to indicate activity on CPUs
[    2.102093] meson-sm: secure-monitor enabled
[    2.106586] gxl-crypto c883e000.crypto: will run requests pump with realtime priority
[    2.113026] gxl-crypto c883e000.crypto: will run requests pump with realtime priority
[    2.121044] hid: raw HID events driver (C) Jiri Kosina
[    2.125844] usbcore: registered new interface driver usbhid
[    2.131227] usbhid: USB HID core driver
[    2.135733] platform-mhu c883c404.mailbox: Platform MHU Mailbox registered
[BL31]: tee size: 0
[    2.151681] Initializing XFRM netlink socket
[    2.152245] NET: Registered PF_INET6 protocol family
[    2.193347] Segment Routing with IPv6
[    2.193395] RPL Segment Routing with IPv6
[    2.195440] In-situ OAM (IOAM) with IPv6
[    2.199433] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    2.208047] bpfilter: Loaded bpfilter_umh pid 97
[    2.209802] NET: Registered PF_PACKET protocol family
[    2.214748] NET: Registered PF_KEY protocol family
[    2.219621] 8021q: 802.1Q VLAN Support v1.8
[    2.224097] registered taskstats version 1
[    2.227696] Loading compiled-in X.509 certificates
[    2.236658] mmc2: tuning execution failed: -5
[    2.236720] mmc2: error -5 whilst initialising MMC card
[    2.237629] zswap: loaded using pool zstd/zbud
[    2.246852] Key type .fscrypt registered
[    2.250162] Key type fscrypt-provisioning registered
[    2.256204] Btrfs loaded, crc32c=crc32c-generic, zoned=no, fsverity=no
[    2.482136] alg: No test for 842 (842-scomp)
[    2.482302] alg: No test for 842 (842-generic)
[    3.238495] meson-drm d0100000.vpu: Queued 2 outputs on vpu
[    3.268507] meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d)
[    3.270938] meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops meson_dw_hdmi_ops): -19
[    3.279354] meson-drm d0100000.vpu: Couldn't bind all components
[    3.285543] meson-drm d0100000.vpu: adev bind failed: -19
[    3.292804] meson8b-dwmac c9410000.ethernet: IRQ eth_wake_irq not found
[    3.297210] meson8b-dwmac c9410000.ethernet: IRQ eth_lpi not found
[    3.303441] meson8b-dwmac c9410000.ethernet: PTP uses main clock
[    3.310109] meson8b-dwmac c9410000.ethernet: User ID: 0x11, Synopsys ID: 0x37
[    3.316371] meson8b-dwmac c9410000.ethernet:         DWMAC1000
[    3.321522] meson8b-dwmac c9410000.ethernet: DMA HW capability register supported
[    3.328936] meson8b-dwmac c9410000.ethernet: RX Checksum Offload Engine supported
[    3.336352] meson8b-dwmac c9410000.ethernet: COE Type 2
[    3.341528] meson8b-dwmac c9410000.ethernet: TX Checksum insertion supported
[    3.348518] meson8b-dwmac c9410000.ethernet: Wake-Up On Lan supported
[    3.354897] meson8b-dwmac c9410000.ethernet: Normal descriptors
[    3.360761] meson8b-dwmac c9410000.ethernet: Ring mode enabled
[    3.366540] meson8b-dwmac c9410000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    3.377407] dwc3-meson-g12a d0078080.usb: USB2 ports: 2
[    3.379646] dwc3-meson-g12a d0078080.usb: USB3 ports: 0
[    3.909452] dwc2 c9100000.usb: supply vusb_d not found, using dummy regulator
[    3.911134] dwc2 c9100000.usb: supply vusb_a not found, using dummy regulator
[    3.918372] dwc2 c9100000.usb: EPs: 7, dedicated fifos, 712 entries in SPRAM
[    3.926847] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    3.930707] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 1
[    3.938185] xhci-hcd xhci-hcd.1.auto: USB3 root hub has no ports
[    3.944005] xhci-hcd xhci-hcd.1.auto: hcc params 0x0228f664 hci version 0x100 quirks 0x0000000002010010
[    3.953359] xhci-hcd xhci-hcd.1.auto: irq 32, io mem 0xc9000000
[    3.959470] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 6.01
[    3.967376] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.974534] usb usb1: Product: xHCI Host Controller
[    3.979362] usb usb1: Manufacturer: Linux 6.1.18-flippy-82+ xhci-hcd
[    3.985659] usb usb1: SerialNumber: xhci-hcd.1.auto
[    3.991014] hub 1-0:1.0: USB hub found
[    3.994230] hub 1-0:1.0: 2 ports detected
[    4.001775] meson-gx-mmc d0070000.mmc: allocated mmc-pwrseq
[    4.002456] scpi_protocol scpi: SCP Protocol legacy pre-1.0 firmware
get_dvfs_info 0004
[    4.039603] ALSA device list:
[    4.039647]   No soundcards found.
[    4.041155] Freeing unused kernel memory: 2240K
[    4.056579] Run /init as init process
[    4.077140] mmc0: new ultra high speed SDR104 SDIO card at address 8800

**Comment by God-JohnDiamond** [comment]
直接用meson-gxl-s905l3b-m302a.dtb这个写入了emmc 然后启动到这里就卡住了，串口不能输入，但是往设备上插拔U盘还是有反应

`[  213.612581] usb 1-2: new high-speed USB device number 2 using xhci-hcd
[  213.761337] usb 1-2: New USB device found, idVendor=ffee, idProduct=0100, bcdDevice= 1.00
[  213.764098] usb 1-2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[  213.776654] usb-storage 1-2:1.0: USB Mass Storage device detected
[  213.777757] scsi host0: usb-storage 1-2:1.0
[  214.789881] scsi 0:0:0:0: Direct-Access     FNK TECH                  1.30 PQ: 0 ANSI: 2
[  214.795139] sd 0:0:0:0: [sda] 15523840 512-byte logical blocks: (7.95 GB/7.40 GiB)
[  214.800301] sd 0:0:0:0: [sda] Write Protect is off
[  214.804961] sd 0:0:0:0: [sda] No Caching mode page found
[  214.809957] sd 0:0:0:0: [sda] Assuming drive cache: write through
[  214.828743]  sda: sda1 sda2
[  214.829403] sd 0:0:0:0: [sda] Attached SCSI removable disk
[  226.216608] random: crng init done
`

**Comment by God-JohnDiamond** [comment]
[  213.612581] usb 1-2: new high-speed USB device number 2 using xhci-hcd
[  213.761337] usb 1-2: New USB device found, idVendor=ffee, idProduct=0100, bcdDevice= 1.00
[  213.764098] usb 1-2: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[  213.776654] usb-storage 1-2:1.0: USB Mass Storage device detected
[  213.777757] scsi host0: usb-storage 1-2:1.0
[  214.789881] scsi 0:0:0:0: Direct-Access     FNK TECH                  1.30 PQ: 0 ANSI: 2
[  214.795139] sd 0:0:0:0: [sda] 15523840 512-byte logical blocks: (7.95 GB/7.40 GiB)
[  214.800301] sd 0:0:0:0: [sda] Write Protect is off
[  214.804961] sd 0:0:0:0: [sda] No Caching mode page found
[  214.809957] sd 0:0:0:0: [sda] Assuming drive cache: write through
[  214.828743]  sda: sda1 sda2
[  214.829403] sd 0:0:0:0: [sda] Attached SCSI removable disk
[  226.216608] random: crng init done

直接用meson-gxl-s905l3b-m302a.dtb这个写入了emmc 然后启动到这里就卡住了，串口不能输入，但是往设备上插拔U盘还是有反应

**Comment by ophub** [comment]
同步最新源码，切换官方源到main就可以了，原来的master官方已经弃更了
