### ISSUE TITLE
S905W,X96mini Stuck during booting

### ISSUE THREAD

**Issue by nandhuks** [ophub/amlogic-s9xxx-armbian#1179]
I'm Using X96 Mini ,S905w,
Its stuck during the booting...
I'm using FDT /dtb/amlogic/meson-gxl-s905w-p281.dtb
![IMG_20230317_164544](https://user-images.githubusercontent.com/59502288/225891172-38e3c9c8-e622-473d-92ee-0577947054af.jpg)
Kernel started but showing this point "Memory Limit : None" screen will be freeze.

**Comment by ophub** [comment]
meson-gxl-s905w-x96-mini.dtb

**Comment by nandhuks** [comment]
I 'have checked the dtb, but same situation occurred.
