### ISSUE TITLE
CM211-1刷入emmc成功，记录一下

### ISSUE THREAD

**Issue by God-JohnDiamond** [ophub/amlogic-s9xxx-armbian#1180]
**Device Information | 设备信息**
 - SOC: S905L3B
 - Model [CM211-1]
**Armbian Version | 系统版本**
 - Kernel Version: [6.1.18]
 - Release: [bullseye]

**Describe the bug | 问题描述**

[ OPTIONS ] Please Input ID: 112
[ INFO ] Input Box ID: [ 112 ]
[ INFO ] FDTFILE: [ meson-gxl-s905l3b-m302a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-s905x-s912.bin ]
[ INFO ] NEED_OVERLOAD: [ yes ]

![image](https://user-images.githubusercontent.com/23442889/225975654-94a951c9-8a8e-4dd6-9a34-6a90123466c1.png)

终于成了，并且有线网络可用，感谢大佬慷慨相助@ophub @7Ji

**Comment by ophub** [comment]
感谢分享。我记录一下，添加到安装列表选择里。

你换过其他的安卓系统吗？发个安卓下载链接。
拍个你的盒子的照片，正面，底部看清型号的标签。
如果方便拆机的话把主板正反两面也拍个照，如果知道短接点的位置在主板上标注一下。

**Comment by God-JohnDiamond** [comment]
![IMG_20230317_173601](https://user-images.githubusercontent.com/23442889/226071125-68f7adae-97a6-42fc-8998-e1d1fc7cb9a9.jpg)
![IMG_20230317_173542](https://user-images.githubusercontent.com/23442889/226071137-06c3e6c7-f44f-4964-957c-4f189e3c9110.jpg)
![IMG_20230317_173535](https://user-images.githubusercontent.com/23442889/226071147-662a4449-f0de-43e5-865c-5a19a28d61ab.jpg)
![IMG_20230317_173530](https://user-images.githubusercontent.com/23442889/226071157-b0343cfe-51c5-4eb1-898c-af85e80ae2cf.jpg)

**Comment by God-JohnDiamond** [comment]
![IMG_20230318_075707](https://user-images.githubusercontent.com/23442889/226071302-e3ba9d01-07ea-4a50-a35e-03918d09c17f.jpg)

**Comment by God-JohnDiamond** [comment]
![IMG_20230318_080001](https://user-images.githubusercontent.com/23442889/226071463-93353525-63e8-4f66-916f-0775ae613319.jpg)
短接点5 6脚

**Comment by ophub** [comment]
你换过其他的安卓系统吗？还是用的盒子自带的安卓系统？

有适用的救砖线刷安卓系统发个下载链接。

**Comment by gbsadmin** [comment]
你的无线蓝牙能用吗？

**Comment by God-JohnDiamond** [comment]
https://pan.baidu.com/s/1GwTWX39q4wKEAC3Cdb42MA
iupy
用的这里的cm211-1 YS 线刷包
171-辽宁移动魔百盒CM211-1-YS-S905L3B-RTL8822C线刷包CJZM.zip

**Comment by God-JohnDiamond** [comment]
> 你的无线蓝牙能用吗？

![image](https://user-images.githubusercontent.com/23442889/226096444-ab660350-2521-4a1d-b103-c3a1be502275.png)

没有无线设备，有线工作就已经很知足了

**Comment by ophub** [comment]
安卓系统我转存了一份到：https://github.com/ophub/kernel/releases/tag/tools

**Comment by zailaib** [comment]
安装armbian的时候有需要短接么？

**Comment by God-JohnDiamond** [comment]
> 安装armbian的时候有需要短接么？

U盘启动armbian，在里边执行armbian-install 就可以了，没有额外操作

**Comment by zailaib** [comment]
erase the area which partition in u-boot
store erase dtb
store erase key
store disprotect key
store rom_protect on/off
store scrub off|partition size
        scrub the area from offset and size
store dtb iread/read/write addr <size>
        read/write dtb, size is optional
store key read/write addr <size>
        read/write key, size is optional
store mbr addr
   update mbr/partition table by dtb

upgrade_step=2
[BL31]: tee size: 0
rebootmode=cold_boot

Starting the controller
 ()
 ()
[BL31]: tee size: 0
[BL31]: tee size: 0


拔掉U盘重启电源
卡在这里不动了

**Comment by zailaib** [comment]
[  348.943978] EXT4-fs (mmcblk2p2): unmounting filesystem.
[ SUCCESS ] Successful installed, please unplug the USB, re-insert the power supply to start the Armbian.
armbian:~:#

**Comment by God-JohnDiamond** [comment]
> [ 348.943978] EXT4-fs (mmcblk2p2): unmounting filesystem. [ SUCCESS ] Successful installed, please unplug the USB, re-insert the power supply to start the Armbian. armbian:~:#
> 
> 拔掉后 重新插入电源 就卡了在上面那个地方了 ，连接的显示器也是 全黑色的

线刷救砖，重新弄就好了，我也遇到过

**Comment by zailaib** [comment]
线刷救砖 是指 用串口线链接  然后重新 armbian-install是么
不是要刷回去电视盒子的固件吧

**Comment by God-JohnDiamond** [comment]
> 线刷救砖 是指 用串口线链接 然后重新 armbian-install是么 这个我重新试了一次 还是一样 难道是刷安卓固件回去？ 这个我没有试

是的，刷个带命令行的 有adb的 安卓固件 然后重新U盘启动 刷机

**Comment by huangc205** [comment]
没用的。。。

**Comment by God-JohnDiamond** [comment]
> 没用的。。。

刷入emmc时候选这个dtb没问题 但首先要确保硬件和我这个完全一致

**Comment by airs777** [comment]
能出一份教程么？打算刷一下试试。准备把CM211-1刷入openwrt。刷openwrt之前需要先刷armbian,么？

**Comment by God-JohnDiamond** [comment]
> 能出一份教程么？打算刷一下试试。准备把CM211-1刷入openwrt。刷openwrt之前需要先刷armbian,么？

https://zhuanlan.zhihu.com/p/580498460 大体按这个步骤刷的，当个参考。 直接刷openwrt就行

**Comment by God-JohnDiamond** [comment]
> 能出一份教程么？打算刷一下试试。准备把CM211-1刷入openwrt。刷openwrt之前需要先刷armbian,么？

对了，得先刷一个带adb的安卓系统，然后才能U盘启动

**Comment by lyc59621** [comment]
u盘启动不了，咋回事，系统root了，cm211-1 安卓4.4的，reboot  update 卡死在主界面

**Comment by bo13808830343** [comment]
CM211-1  主板MC022     2+8G  其中蓝牙 wifi 都不能启动。
用Armbian_23.08.0_amlogic_s905l3b_jammy_6.1.52_server_2023.09.12.img.gz 这个有网卡，无wifi，无蓝牙
测试了好几个其他镜像，没有网卡，而且所有的镜像都不能hdmi显示。

**Comment by 493505110** [comment]
CM211-1 MC022 2+8G同上
`Armbian_23.11.0_amlogic_s905l3b_lunar_6.1.59_server_2023.10.20.img.gz`
正常启动 HDMI无显示，USB WIFI网卡可用

**Comment by skygunner** [comment]
建议楼主把标题和model改为CM211-1 YS

**Comment by bo138088** [comment]
CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ，  5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img  也试过
Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过
无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。

![b8da3491f447143b6b50e35cc354890](https://github.com/ophub/amlogic-s9xxx-armbian/assets/140767369/6dadfd73-4f34-450e-b47b-d5f4dae95842)
![4f23e2004038efa52f6ff24d3c406db](https://github.com/ophub/amlogic-s9xxx-armbian/assets/140767369/03bf3662-6757-4fe0-a3fa-573d29263562)

**Comment by ophub** [comment]
先换安卓系统，在kernel仓库里下载： https://github.com/ophub/kernel/releases/tag/tools

**Comment by bo138088** [comment]
> 先换安卓系统，在kernel仓库里下载： https://github.com/ophub/kernel/releases/tag/tools

换过了，仓库里的。还是老样子，装不上op和armbian，装上OP后，TTL连接后键盘断断续续无法输入。也打开不页面。

**Comment by a92126** [comment]
> ![微信图片_20240408082253](https://private-user-images.githubusercontent.com/140767369/320323851-a39cb5cf-8256-4926-8e06-821ab0f689a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTc2OTQsIm5iZiI6MTcxMjk5NzM5NCwicGF0aCI6Ii8xNDA3NjczNjkvMzIwMzIzODUxLWEzOWNiNWNmLTgyNTYtNDkyNi04ZTA2LTgyMWFiMGY2ODlhNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwODM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTlmMmMwZDAwODNmMjNmNDQzMWI5MjVmZDg0NTllMDQ4ZGVhNmRhZDYyZjkwMzZhYjA1NzIxODJmMDQyMDYzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xKPZd2wFMATMkVjg9BOYawDvZE6q2PW6tacAZ0dDePc) CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。
> 
> ![b8da3491f447143b6b50e35cc354890](https://private-user-images.githubusercontent.com/140767369/320323004-6dadfd73-4f34-450e-b47b-d5f4dae95842.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTc2OTQsIm5iZiI6MTcxMjk5NzM5NCwicGF0aCI6Ii8xNDA3NjczNjkvMzIwMzIzMDA0LTZkYWRmZDczLTRmMzQtNDUwZS1iNDdiLWQ1ZjRkYWU5NTg0Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwODM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjVmOGUxOWUwM2EwMjNjNmNjY2NjY2EwMGI1M2YwYjY0MjhiZDZlNzFjYjM2NDJkYzllZWFlNjQ4YzQwZTg3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.uPEtgXJgdxqOtaRh8-Zu0wrZFWFAtME1m6ZZpgwRtm8) ![4f23e2004038efa52f6ff24d3c406db](https://private-user-images.githubusercontent.com/140767369/320323010-03bf3662-6757-4fe0-a3fa-573d29263562.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI5OTc2OTQsIm5iZiI6MTcxMjk5NzM5NCwicGF0aCI6Ii8xNDA3NjczNjkvMzIwMzIzMDEwLTAzYmYzNjYyLTY3NTctNGZlMC1hM2ZhLTU3M2QyOTI2MzU2Mi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxM1QwODM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NjU3NzEyYjc1ZGJmOGU2Y2M1NzU5YWE3MWEzNTViNmVjZTYyZWI5MzJkZTc2MjA2M2RkZmJiYTljYjk5N2U4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QBJ2eiWUUL0DBOndn6TWD-VOF5Ly86dUKX1b9dRAjug)

你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！

**Comment by bo138088** [comment]
我发给你  你邮箱



发自139邮箱






------------------ 原始邮件 ------------------




 
 发件人: a92126  ***@***.***>
 

 
 发送时间: 2024-04-13 16:43:03
 

 
 收件人: ophub/amlogic-s9xxx-armbian  ***@***.***> 
 

 
 抄送: bo  ***@***.***>,Comment  ***@***.***> 
 

 
 主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180)
 





 CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。

 

 你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！

**Comment by a92126** [comment]
> 我发给你 你邮箱 发自139邮箱
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: a92126 ***@***.***> 发送时间: 2024-04-13 16:43:03 收件人: ophub/amlogic-s9xxx-armbian ***@***.***> 抄送: bo ***@***.***>,Comment ***@***.***> 主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180) CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。 你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

那你发我试试：182859762@qq.com

**Comment by a92126** [comment]
收到，谢谢，我试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月13日(周六) 下午5:45
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180)




 
 
 我发给你  你邮箱 
 
 
 
 发自139邮箱 
 
 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 
 
 
 
   
  发件人: a92126  ***@***.***&gt; 
   
 
   
  发送时间: 2024-04-13 16:43:03 
   
 
   
  收件人: ophub/amlogic-s9xxx-armbian  ***@***.***&gt;  
   
 
   
  抄送: bo  ***@***.***&gt;,Comment  ***@***.***&gt;  
   
 
   
  主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180) 
   
 
 
 
 
 
  CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。 
 
   
 
  你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！

**Comment by yyh9488** [comment]
蓝牙和wifi是否能用和刷安卓的底包有关闭吗还是

**Comment by Ansen** [comment]
请问一下  2.4G和 5G WIFI 在Armbian上 能正常工作吗?

**Comment by losefrank** [comment]
> 我发给你 你邮箱 发自139邮箱
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: a92126 ***@***.***> 发送时间: 2024-04-13 16:43:03 收件人: ophub/amlogic-s9xxx-armbian ***@***.***> 抄送: bo ***@***.***>,Comment ***@***.***> 主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180) CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。 你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我的盒子也是这个型号，刷了root的Android TV，但只要USB启动其它镜像就直接黑屏，无法启动。前辈可以也发一份可行的配置给我吗。感谢

**Comment by losefrank** [comment]
@a92126

**Comment by a92126** [comment]
> > 我发给你 你邮箱 发自139邮箱
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: a92126 _**@**_._**> 发送时间: 2024-04-13 16:43:03 收件人: ophub/amlogic-s9xxx-armbian _**@**_.**_> 抄送: bo _**@**_._**>,Comment _**@**_.**_> 主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180) CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。 你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 我的盒子也是这个型号，刷了root的Android TV，但只要USB启动其它镜像就直接黑屏，无法启动。前辈可以也发一份可行的配置给我吗。感谢。邮箱 [banmo@163.com](mailto:banmo@163.com) @a92126

附件过期了，我找找下载记录看看

**Comment by a92126** [comment]
> > 我发给你 你邮箱 发自139邮箱
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: a92126 _**@**_._**> 发送时间: 2024-04-13 16:43:03 收件人: ophub/amlogic-s9xxx-armbian _**@**_.**_> 抄送: bo _**@**_._**>,Comment _**@**_.**_> 主题: Re: [ophub/amlogic-s9xxx-armbian] CM211-1刷入emmc成功，记录一下 (Issue #1180) CM211-1 CH 版本，无法驱动网卡，Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.83_server_2024.04.01 ， 5.15也试过了。openwrt_official_amlogic_s905l3b_k5.15.153_2024.04.06.img 也试过 Armbian_23.11.0_amlogic_s905l3-cm211_lunar_6.1.60_server_2023.11.01.img.gz 也试过 无法驱动hdmi，网卡，哪位刷成了的, 用的哪个包，非常感谢。 你这个机器跟我的一样，我还找不到可以启动u盘的配置呢！ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 我的盒子也是这个型号，刷了root的Android TV，但只要USB启动其它镜像就直接黑屏，无法启动。前辈可以也发一份可行的配置给我吗。感谢。邮箱 [banmo@163.com](mailto:banmo@163.com) @a92126

发你了

**Comment by tzy202625** [comment]
> > 安装armbian的时候有需要短接么？
> 
> U盘启动armbian，在里边执行armbian-install就可以了，没有额外操作
大佬我怎么启动不了U盘的armbian系统 主板型号魔百盒cm211-1

**Comment by a92126** [comment]
这台设备搞了10个月才好，记录一下，顺便 @b9885004  ，因为同款机型

### Device Information | 设备信息

- SOC 不知道，没拆盖子，盲猜S905L3B，因为和 [这层楼](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1180#issuecomment-2041659076)的图片一样的
- Model CM211-1 CH 2+8 二手盒子不知道哪个省的，只有未来电视-分省模式字样，套装编号125
- Android 探测Model gxlx2_p291_2g

### Armbian Version | Armbian_25.02.0

- Kernel Version: [6.6.68]
- Release: Armbian_25.02.0_amlogic_s905l3b_bookworm_6.6.68_server_2025.01.01

### Describe the bug | 问题描述

1.   刷机，不过这个是我的问题，用了晶晨**刷机神器**搞定。试刷了许多包，发现安卓4可以正常用，安卓9基本都卡加载动画
2.   插上U盘没一次能在路由器得到IP，这个真无语。放置了7个月，后来回家拿出焊台，把TTL的排针焊上去了， 接上**串口调试**，发现其实已经从U盘启动了Armbian系统
3.   使用`armbian-install`，安装失败，提示没有emmc……查芯片是kowin KAS03111，属于正宗emmc，然后issue查`KAS03111`，得到 #986 ，需要修改dtb，把**HS200删掉**，U盘重进系统，`lsblk`确认识别emmc成功。`armbian-install`安装成功
4.  emmc启动Armbian成功，但是没法使用网络，`nmcli d`显示连接断开，我用U盘启动仔细看，发现也没有网络。只能继续在issue搜索`网络`，发现 #2539 有两种方案，一种是用dhcpd替换NetworkManager，另一种是用安卓9底包。我的情况和@tinytinycn佬的一样，所以用了他制作的**安卓9底包**，因为我看到大佬是用安卓4的数据替换安卓9的数据后打的包。这个底包确实神，虽然第一次和第二次开机卡加载动画了，第三次居然进去了。然后用遥控器开启开发者模式，接上U盘，adb shell连进去安卓9使用`reboot update`进入U盘启动，发现网络通了。重新`armbian-install`，拔掉U盘启动，自此可以正常使用

>    总结：遇上的都是别人遇到过的问题了，没事就在issue一篇篇看，总有想不到的收获……

**Comment by HYYH010** [comment]
> CM211-1 刷armbian后，路由器已经获取IP地址，ssh进不去系统，显示Remote side unexpectedly closed network connection，连接显示器无法显示，哪位大神有没有解决方案？求。

S905L3B

**Comment by Sephdex** [comment]
小白想搭车问一下，给大佬们递茶：
这个debain的大版本升级，需要整个重新安装么？比如想从bookworm到trixie……
目前内核是6.6.100，每次armbian-update都会升最后的小版本号，并不会从6.6.X到6.12.X…，
也就是安装后想升级debian大版本或者内核的大版本都需要重新刷机是吧

**Comment by a92126** [comment]
> 小白想搭车问一下，给大佬们递茶： 这个debain的大版本升级，需要整个重新安装么？比如想从bookworm到trixie…… 目前内核是6.6.100，每次armbian-update都会升最后的小版本号，并不会从6.6.X到6.12.X…， 也就是安装后想升级debian大版本或者内核的大版本都需要重新刷机是吧

今天用斐讯N1进行了测试，将5.15的版本升级到了6.1，没有什么问题，不用刷机。命令
```bash
sudo armbian-update -k 6.1.xxx
```
要留意xxx对应的版本必须是ophub大佬发布的那些

**Comment by airs777** [comment]
你好，邮件已收到。感谢支持

**Comment by getr00t** [comment]
> > 安装armbian的时候有需要短接么？
> 
> U盘启动armbian，在里边执行armbian-install 就可以了，没有额外操作

我的机器也是CM211-1，soc是S905L3B，我刷了Armbian_25.11.0_amlogic_s905l3b_trixie_6.1.152_server_2025.09.15.img.gz固件写入到usb，但是我发现无法进入armbian系统啊，所以压根都进不去ssh进去执行命令等，为什么？你确定不需要短接吗？

**Comment by fhx4315** [comment]
刷完之后 dtb 选的创维 e 开头的，U盘启动不了

**Comment by fhx4315** [comment]
刷完之后 dtb 选的创维 e 开头的，U盘启动不了

**Comment by uuedxz** [comment]
> > > 安装armbian的时候有需要短接么？
> > 
> > 
> > U盘启动armbian，在里边执行armbian-install 就可以了，没有额外操作
> 
> 我的机器也是CM211-1，soc是S905L3B，我刷了Armbian_25.11.0_amlogic_s905l3b_trixie_6.1.152_server_2025.09.15.img.gz固件写入到usb，但是我发现无法进入armbian系统啊，所以压根都进不去ssh进去执行命令等，为什么？你确定不需要短接吗？

那你就没从U盘启动成功，短接是短接emmc引脚迫使uboot从USB/SD卡启动。最方便的就是在安卓系统下adb让设备从U盘启动，插入U盘重启后就正常进armbian（U盘），然后armbian-install写入emmc。短接只用来刷机（刷安卓底包方便进adb从U盘启动），和armbian的安装没有关系的。

**Comment by Tziyue** [comment]
我的盒子是s905l3b的，型号cm211-1，我折腾了3天，几乎我能想到的办法都尝试过了，刷进去hdmi不能用，无线网卡不能用。
hdmi我根本没来得及解决因为无所谓，wifi的问题，我尝试了3天。
最开始是安卓4.4的底包，刷好armbian后，无限网卡因为不是usb总线的设备，完全检测不到。
后来刷了安卓9的底包，还是不行，然后从6.18内核降到5.15内核。终于能看到无限网卡了，还是报错-84。
我翻遍了各种armbian包，都没有完全对应我这个型号的dtb，s905l3b 里面cm201 cm211 m302a  都用的是m302a的dtb
然后这个型号的盒子还有一个问题，就是刷入armbian的时候，如果不带参数，不写住主线u-boot的话，hdmi接显示器就是全程黑屏，没任何反应，如果带参数armbian-install -m yes的话 ，写入主线u-boot开机能显示logo，然后花屏。
也没来得及折腾，网卡不好使我就放弃了。
