### ISSUE TITLE
Infinity B32 support.

### ISSUE THREAD

**Issue by ketaksaan** [ophub/amlogic-s9xxx-armbian#1181]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [Infinity B32]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.18]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Hey, I have Infinity B32 and I was able to boot with meson-sm1-h96-max-x3-oc.dtb ( I use the OC because previously it can booted with normal dtb, so free performance right? ) The device was able to boot with another dtb, HK1box. It booted with Gigabit ethernet and wifi working. But I would like all features on the device working, like BT, the LED display, and able to boot via emmc, though I was not planning to boot to emmc because I dont have any android backup but having that feature is highly appreciate it.

I will attach some photos of the device below. 

![20230309_234716](https://user-images.githubusercontent.com/97231188/226088618-a7ea7f5b-1f34-4798-bacd-9a948803fd3d.jpg)

![20230309_235201](https://user-images.githubusercontent.com/97231188/226088630-410729ad-0062-4831-8817-9333f32237eb.jpg)

![20230309_235244](https://user-images.githubusercontent.com/97231188/226088680-8d3ad4b7-fde9-40a8-bc60-85ae82474cd9.jpg)

![20230309_235522](https://user-images.githubusercontent.com/97231188/226088689-5c2aff37-4241-4f53-88ef-fcb9c5963e9e.jpg)

**Comment by ophub** [comment]
If you are using the 6.1.18 kernel firmware, you can start it on usb, indicating that it also supports writing to emmc

Bluetooth installation, in armbian-config

To turn on the led, execute `armbian-openvfd 14` to see the displayed results
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/led_screen_display_control.md

Post the results of the following three commands, and I record them in the list

```
cat /boot/uEnv.txt
cat /etc/ophub-release
ls -l /boot/u-boot*
```

**Comment by ketaksaan** [comment]
Right now I'm using microsd to boot, it can booted from USB also. So, it is able to write to emmc?

About bluetooth, I was able to install and when I checked using 'bluetoothctl' to gather some info about the BT using "list" it shows blank. 

![image](https://user-images.githubusercontent.com/97231188/226095194-b9ad0da6-3784-416c-a560-560fcbb5e132.png)

About LED, it shows the display correctly. Thanks.

And this is the last information you asked.

![image](https://user-images.githubusercontent.com/97231188/226095324-9b752337-e7c0-4ea2-8a10-fa2c5a0c2789.png)

![image](https://user-images.githubusercontent.com/97231188/226095343-0ced8f06-92fc-44c9-a4c6-a2e6149f82c0.png)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y
I didn't find any bluetooth instructions for `WP6330` in the kernel source code.

Take a picture of the front and bottom of the box. You can see the specific name or model of the device.

Do you have Android for this device? Share a download address.

**Comment by ketaksaan** [comment]
Last week I was discussing the wifi on facebook group, and he give me this link of the chip. https://wikidevi.wi-cat.ru/AMPAK_AP6330, wifi BCM4330, BT BCM40183.

This this the detail model displayed on android.

![FB_IMG_1679136280483.jpg](https://user-images.githubusercontent.com/97231188/226100842-d762d1d9-10bf-4a20-b4f9-f2f8dcf7565f.jpg)

I am unable to take picts the bottom of the device because it got ripped off when I played around with it, but I will ask someone who has the same device.

![20230318_171451.jpg](https://user-images.githubusercontent.com/97231188/226100996-c9029e2e-59be-452c-97dc-89934d6ff28f.jpg)


![20230318_171353.jpg](https://user-images.githubusercontent.com/97231188/226101037-ede050e8-9902-494c-b2a8-b962d447be99.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/firmware/tree/main/firmware/brcm

There is no firmware for this Bluetooth at present, if you find it, you can add it. The Android driver cannot be used.

**Comment by ketaksaan** [comment]
I think the chip is detected and initialized, but it just can't show the chip and use it via 'hcitool dev' or previously with 'bluetoothctl' command.

![image](https://user-images.githubusercontent.com/97231188/226122540-f86acf30-1e75-4c2e-baa1-8535e16190e8.png)

**Comment by ophub** [comment]
This is not the driver of your chip

**Comment by ketaksaan** [comment]
Well, that's so unfortunate then. Oh yeah, 1 more question. A while back ago I was doing a backup of the emmc using openwrt-ddbr command while I was using OpenWRT. The backup went successfully. I was wondering if somehow I softbrick the device when I play around to install armbian/openwrt and then using that android backup to restore it, will it fully restore the android firmware?

**Comment by ophub** [comment]
```
openwrt-ddbr
r

armbian-ddbr
r
```

**Comment by ketaksaan** [comment]
Hey, I got the android firmware from my group. I have not tested it but my folks say that my device has the share the same with H96 Max X3. Well if I reference it with your model database IT IS h96 max x3. I want you to archive this firmware to preserve the file.

[AML_user_X3_9_20220516.1821.img](https://1drv.ms/u/s!AvtH2bREo2A5gehnk2oPbt-O-AY9Rg?e=AhsiYm)

**Comment by Xpriencias** [comment]
> I think the chip is detected and initialized, but it just can't show the chip and use it via 'hcitool dev' or previously with 'bluetoothctl' command.
> 
> ![image](https://user-images.githubusercontent.com/97231188/226122540-f86acf30-1e75-4c2e-baa1-8535e16190e8.png)
I have the same problem on my TX3-H ((QZ)4/64) same ap6330 i tell you off you can find 5.9 kernel version will run everything from the start, but the moment i do apt update it will not work anymore. I tested it like 40 Times i even broker 2 old de sdcards trying different distros, but I'm starting at Linux so i accept that my knowledge is rather limited but i also want to make the bluetooth work, can anyone help?
