### ISSUE TITLE
unt402a不能正常从u盘启动

### ISSUE THREAD

**Issue by yang-yang-NO-1** [ophub/amlogic-s9xxx-armbian#1183]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: s905l3
 - Model unt402a

**Armbian Version | 系统版本**
 - Kernel Version:5.15.100 
 - Release: bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
浙江广东甘肃UNT402A.exe https://www.aliyundrive.com/s/6JWYH9m7hLv 提取码: 09ys 点击链接保存，或者复制本段内容，打开「阿里云盘」APP ，无需下载极速在线查看，视频原画倍速播放。
烧写如上的安卓4.4.2系统，按照操作步骤，没有在网线直连的路由器中发现armbian的设备，去掉u盘，正常进入安卓系统。
以下是设备硬件信息
![IMG_20230319_151145_edit_989444792603182](https://user-images.githubusercontent.com/97171864/226161769-4e45c49b-7505-4d73-90bc-8a9757300658.jpg)
![IMG_20230315_152454_edit_991215540323745](https://user-images.githubusercontent.com/97171864/226161955-a2ec89a5-2532-4703-b3e1-7a56a6f35f56.jpg)

![IMG_20230307_185716_edit_989228028097486](https://user-images.githubusercontent.com/97171864/226160530-00adbe24-ed54-4abf-91ea-44609177ad3a.jpg)
![IMG_20230307_185740_edit_989215358832904](https://user-images.githubusercontent.com/97171864/226160543-5d413322-4a24-4fc0-8ebe-e45be0f72a64.jpg)

**Comment by ophub** [comment]
安卓建议使用安卓9及以上的系统
USB不能启动的问题看帮助文档里有说明怎么操作
介绍你用的armbian配置信息

**Comment by yang-yang-NO-1** [comment]
cpu

**Comment by yang-yang-NO-1** [comment]
好的，目前我这个盒子只找到安卓4的

**Comment by openvpn-go** [comment]
请教下这个盒子可以了吗，用哪个DTB呢
