### ISSUE TITLE
hope you can help!!

### ISSUE THREAD

**Issue by vuong07** [ophub/amlogic-s9xxx-armbian#1184]
Hope you can help me create a custom u-boot file for ugoos AM6b Plus (Amlogic-S922x-j)
i have the extracted files on the original android device ugoos AM6b plus 4G Ram. 
https://drive.google.com/drive/folders/12ZJQRYAilPHHicw0Sh12dOQP0__N2wH7
Thank you!!

**Comment by ophub** [comment]
https://github.com/7Ji/u-boot

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#1211-how-to-make-u-boot-file

It is not a development board, and there is no officially supported fixed configuration. You need to debug it yourself. See the documentation for the compilation method. Different warehouse compilation methods may be a little different.

**Comment by vuong07** [comment]
i have followed and not very much hope you can share how to create bl2, bl31,bl301 , bin, img and .fw files i have the original bootloader file.  Thank you
