### ISSUE TITLE
Beelink GT1 s912 no network and wifi 

### ISSUE THREAD

**Issue by tux-vador** [ophub/amlogic-s9xxx-armbian#1185]
Hello everyone,

First thanks a lot for your work and all these release. i need your help please

**Device Information | 设备信息**
 - SOC: S912
 - Model: Beelink GT1 

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.100 and 6.1.18
 - Release: bullseye

**Describe the bug | 问题描述**
my box crashed yesterday and when a tried to install the armbian released here by you I have a problem with network (eth0 and wifi cannot connect) 

i tried with both : 
Armbian_23.05.0_amlogic_s912_bullseye_5.15.100_server_2023.03.19.img

Armbian_23.05.0_amlogic_s912_bullseye_6.1.18_server_2023.03.19.img.

I saw in another issue that there is a bug with the current kernel 

my box was working fine with Armbian 22.11.0-trunk Bullseye with Linux 5.15.79-flippy-78+o. 

 if someone have the img file for s912 and can upload it or if you have a date to the new kernel with network issue fix 

![A1D6DD61-7FCA-419B-916C-12B921D8E080](https://user-images.githubusercontent.com/19595887/226173462-8afff0ba-b8d4-4047-aaf1-4297dce0446b.jpeg)

**Comment by tux-vador** [comment]
also i tried both meson-gxm-gt1.dtb and meson-gxm-q201.dtb and with u-boot-s905x-s912.bin

i also follow this article https://www.sigmdel.ca/michel/ha/aml912/linux_on_aml912_en.html

**Comment by ophub** [comment]
Did you not plug in the wired network cable?

**Comment by tux-vador** [comment]
the network cable is plugued of course and nothing happen

**Comment by tux-vador** [comment]
here some new tests : 

with FDT=/dtb/amlogic/meson-gxm-beelink-gt1.dtb 
and u-boot-zyxq.bin renamed as u-boot.ext 

i have this issue

**Comment by ophub** [comment]
download: s912-m8s-pro
donot change

**Comment by tux-vador** [comment]
ok i download s912-m8s-pro
which firmware you recommand please : 6.1.18 or 5.15.100

**Comment by ophub** [comment]
5.15.100

**Comment by ophub** [comment]
I just tested the latest bullseye, the system is fine, you continue to test which one is suitable for your dtb.

![Snip20230319_1](https://user-images.githubusercontent.com/68696949/226177636-d38f10bd-6ffb-4273-9787-f2aa7ddd8c7a.png)
![Snip20230319_2](https://user-images.githubusercontent.com/68696949/226177637-def4b736-7330-4383-ba35-c0aaf5c8c4d5.png)
![Snip20230319_3](https://user-images.githubusercontent.com/68696949/226177638-6ad09381-027a-4a8f-9c67-91f914b43fbd.png)
![Snip20230319_4](https://user-images.githubusercontent.com/68696949/226177641-bdd9968c-a50e-4ec1-b069-b49f55fe704e.png)
