### ISSUE TITLE
unt 403A armbian-install写入emmc报错

### ISSUE THREAD

**Issue by 783545134** [ophub/amlogic-s9xxx-armbian#1186]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905L3A
 - Model : unt 403A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.100
 - Release: bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

unt 403A armbian-install写入emmc报错
报错信息
![image](https://user-images.githubusercontent.com/56526941/226182819-fd8b86db-1d0e-4bf8-83c0-a3900bec3a38.png)

麻烦大佬了

**Comment by ophub** [comment]
再试一遍

**Comment by 783545134** [comment]
![image](https://user-images.githubusercontent.com/56526941/226182988-9b9d88ac-e2bd-4c85-ba63-934d6f6b9fbb.png)
还是一样的

**Comment by ophub** [comment]
lsblk

**Comment by 783545134** [comment]
![image](https://user-images.githubusercontent.com/56526941/226183060-101155a0-6dee-46c0-8305-bb0e7b2be115.png)

**Comment by ophub** [comment]
emmc里面现在是什么系统

**Comment by 783545134** [comment]
Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.68

**Comment by 783545134** [comment]
这个版本可以写入emmc，但是重启之后有几率启动不了

**Comment by ophub** [comment]
```
parted -s /dev/mmcblk2 rm 1
parted -s /dev/mmcblk2 rm 2
sync
```

**Comment by 783545134** [comment]
![image](https://user-images.githubusercontent.com/56526941/226183658-eddfe718-bfcf-4016-b8bc-cf1bae506fb5.png)

**Comment by ophub** [comment]
emmc不让操作，不能删除已经分不区

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.16调一下dtb的频率

**Comment by chen7393** [comment]
> [https://github . com/op hub/amlogic-s9xxx-arm bian/blob/main/build-arm bian/documents/readme . cn . MD](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md)
> 
> 看12.16调一下dtb的频率

链接失效了
