### ISSUE TITLE
大佬 阿里ct2000有办法在armbian下驱动led灯吗？就像刷了当贝系统那种呼吸灯

### ISSUE THREAD

**Issue by Jack-bin183** [ophub/amlogic-s9xxx-armbian#1188]
我想如果可以的话用来指示硬盘读写啥的应该是个good idea

**Comment by ophub** [comment]
https://github.com/7Ji/YAopenvfD

试试这个灯的控制

**Comment by Jack-bin183** [comment]
谢谢大佬回复  另外还有个问题就是我发现阿里ct2000刷了armbian之后内存RAM显示总容量是3.3G  而刷了安卓则显示3.8G  这是什么原因导致的呢？

**Comment by ophub** [comment]
锁bootloader了，没法给他做专门适配的u-boot

**Comment by Jack-bin183** [comment]
我看群里面  好像可以解锁bl刷其他系统了   我昨天就刷了群里大佬定制的当贝系统
AMLBootloaderConsole fastboot
不知道我说的这个解锁对armbian有效吗

**Comment by Jack-bin183** [comment]
另外有没有可能我可以提取现在emmc中当贝系统的u-boot给armbian用
感觉有点异想天开

**Comment by ophub** [comment]
这个当贝应该也是跳过bootloader 了，没有覆盖原来的

**Comment by Jack-bin183** [comment]
明白了  谢谢大佬百忙之中回复我
