### ISSUE TITLE
O大能不能再编译一份minima版供大家下载

### ISSUE THREAD

**Issue by Dannypod** [ophub/amlogic-s9xxx-armbian#1189]
armbian 23.x版本增大明显，fork了一份O大的，编译minima版本后，大小可以控制在400多M。想做伸手党，O大能否再编译一份minima版供大家下载，省去自己编译的麻烦。

**Comment by ophub** [comment]
勾选就是minimal版，默认不勾选就是完整版。
现在Armbian的编译改了，全新编译一个镜像只要10分钟就可以完成，打包1个也仅几分钟。你用哪个board自己编译吧。我编译一次Releases全board是40G，没几个人用minimal，放着浪费github空间。

![image](https://user-images.githubusercontent.com/68696949/226234974-8ccb4e9f-7e14-4389-a14b-d15a80a364dd.png)

**Comment by Dannypod** [comment]
感谢O大，刚才编译了bullseye kernel 6.1.18，使用了minima参数，比之前修改配置文件要方便。最后生成的包大小409M，比armbian 23.03的要小了几十M，最重要的是生成时间只要15分钟，比之前的快太多了。
