### ISSUE TITLE
 数码视讯Q7 nand版使用5.10.y有线无线均正常

### ISSUE THREAD

**Issue by taotao108** [ophub/amlogic-s9xxx-armbian#1190]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905L
 - Model: 数码视讯Q7 nand版，TF卡启动。

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.100
 - Release: bullseye
**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

请问大佬，最近看您刷机包每天都在更新，我使用19日的刷机包看到RTL8189ftv WiFi已经可以驱动，但依旧无法使用networkmanagger，不知道20日更新有解决吗？主要是一直没有看到内核有更新5.15.102。
刷了20日更新后，启动会卡住，无法登录。
![QQ截图20230320161933](https://user-images.githubusercontent.com/69961983/226283923-294b415d-4016-40da-98f3-51714f70b414.jpg)
![QQ截图20230320161920](https://user-images.githubusercontent.com/69961983/226283931-6570860d-9baa-455a-ae7c-977a41bc3a12.jpg)

**Comment by ophub** [comment]
之前使用的是armbian的master分支，这个分支2周前官方停更了，切换到了main分支，官方说最近服务器搬迁，版本冻结中，不大更，最近的2周可能会不稳定。
之前的master已经无法编译了，无线驱动的仓库删除了commit导致编译报错过不去。切换到main我在tx3-pro上测试了正常。建议你继续使用盒子里原来的系统吧，新的等上游就绪了再更。
内核也因为f大最近忙碌，可能要停更一段时间，他没时间维护升级内核。

**Comment by taotao108** [comment]
使用Armbian_23.02.0_amlogic_s905lb-r3300l_bullseye_5.15.100_server_2023.03.17正常使用有线网络，我armbian-update -k 5.10.174后无线也正常了。
dtb和u-boot未修改，刷写固件到TF卡后默认。dtb应该是：meson-gxl-s905x-p212.dtb
由于我的Q7是nand版无法刷入闪存，是TF卡启动的。

**Comment by ophub** [comment]
好的，我把这个加到r3300l列表里，方便大家参考

**Comment by gingwn** [comment]
为什么我下载的固件烧录时显示源镜像曾压缩过 让检查是否损坏

**Comment by ophub** [comment]
先解压成img再写入u盘

**Comment by taotao108** [comment]
下载镜像快要梯子，用7Z解压软件解压。使用ImageWriter写入TF卡。

**Comment by gingwn** [comment]
解压后总是显示映像文件已损坏

**Comment by ophub** [comment]
什么镜像？

**Comment by gingwn** [comment]
S905lb k5.15.106

**Comment by gingwn** [comment]
有没有其他渠道下载地址

**Comment by siqisqw** [comment]
我的也是无法驱动wifi，再试试最新版本

**Comment by 281162545** [comment]
请问RTL871X的跑码不停刷新是怎么造成的，是网卡驱动不对造成的吗？怎么处理

**Comment by 281162545** [comment]
有知道什么原因的吗？

**Comment by dongbubu** [comment]
用什么软件解压，我解压出来的有有几个压缩文件
