### ISSUE TITLE
X96Max+ PHY (IP1001M) no ETH

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#1193]
**Device Information | 设备信息**
 - SOC: S095x3
 - Model X96Max+ PHY (IP1001M) 

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100]
 - Release: [bullseye]
 
 
hello @ophub 
I have an X96 Max+ PHY (IP 1001M) but I can't get the ETH to work,
the dtb i am using is **meson-sm1-x96-max-plus-ip1001m-2.dtb**

The pin voltage is:

48--3.35
49--3.35
50--0.17
51--0.17
7---0.17
8---3.35

but i get this error and i don't get ip

if you want log by Uart for a better debug say

![photo_2023-03-20_20-57-42](https://user-images.githubusercontent.com/83761813/226464326-44f60a4d-bdcc-4cc2-a659-2fe73097e2c3.jpg)

**Comment by serrj-sv** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1054#issuecomment-1427802069

**Comment by ophub** [comment]
Now that you download the latest version, this issue should be resolved.

**Comment by ophub** [comment]
big change today

**Comment by serrj-sv** [comment]
> Now that you download the latest version, this issue should be resolved.

It is not. Some boxes with IP1001M phy has an issue that it works only on 100Mbps. I spent a lot of time troubleshooting this, it seems have something to do with rgmii configuration, but I tried all possible combinations of internal tx and rx delays: none are working. Physicallly link goes up,  but no Rx or Tx packets. So the only fix for now is to set interface to 100Mbps FD mode.

**Comment by tv4you2016** [comment]
@ophub  @serrj-sv 

the only way to have ip for eth0 is to run the command ethtool -s eth0 speed 100
but every time I turn off the box and turn it back on I have to run that same command
does the Armbian_bullseye_03.20.2344 build already have the correction made for this box?

**Comment by ophub** [comment]
try meson-sm1-x96-max-plus-ip1001m.dtb

**Comment by tv4you2016** [comment]
my dtb is meson-sm1-x96-max-plus-ip1001m-2.dtb

if i use my dtb is meson-sm1-x96-max-plus-ip1001m.dtb i get this error
![photo_2023-03-22_09-12-35](https://user-images.githubusercontent.com/83761813/226855265-73e771aa-df0b-4487-9a5e-8639339a1ee9.jpg)

**Comment by ophub** [comment]
Have you tried updating to another series of kernels, such as 5.4/6.1 and so on. Did you use it before? Problems with recent kernels?

**Comment by tv4you2016** [comment]
@ophub 
Have you used it before?

- no.. i received this version of the box recently

Problems with recent kernels?

- at least with kernel 6.1.20 and 5.15.103 the error remains. Just running the command and that solves it


it recognizes the network card.. and detects 1GB but does not pick up the ip.
when I put 100mb (ethtool -s eth0 speed 100 )it works right away

**Comment by ophub** [comment]
Is your wired network card 100 megabytes?

**Comment by serrj-sv** [comment]
@tv4you2016 
pin 36 on this board is pulled down (0v) to set phy in rgmii mode, no sense to measure it.

 As I already mentioned earlier this is specific case for this particular model of X96 (Max Plus2 AI with IP1001M phy): it **fails to transmit and receive packets** in **gigabit** mode. 100MBps works fine.

There are couple of options that control RGMII phy mode in kernel: 
https://www.kernel.org/doc/Documentation/devicetree/bindings/net/amlogic%2Cmeson-dwmac.yaml

For RGMII to work properly you need to configure a tx and rx delays. They can be configured on MAC side (s905x3 SoC) or PHY side (IP1001M) or both (very rarely: only if physicals distance between MAC and PHY very long). 
In our case, delays configured on PHY side (pins 48 and 49 pulled high), it means that SoC should be configured as following:

```
phy-mode: rgmii-id
amlogic,tx-delay-ns: 0
rx-internal-delay-ps: 0
```

This is how it configured on Android firmware, where gigabit interface is working properly. But for some reasons it's not working on armbian. Eventually I gave up and use it in 100Mbps mode all the time.

You can use attached DTB for this. It forces interface to 100MBits, so you don't have to run ethtool everytime. 
[meson-sm1-x96-max-plus-ip1001m-2-100m-no_oc.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11052934/meson-sm1-x96-max-plus-ip1001m-2-100m-no_oc.zip)

**Comment by tv4you2016** [comment]
@serrj-sv 
this dtb works now i don't need to run the command every time the box turns off but now i only have 2gb instead of 4gb
@ophub

**Comment by serrj-sv** [comment]
> now i only have 2gb instead of 4gb

do you have this issue only with my dtb or with original (meson-sm1-x96-max-plus-ip1001m-2.dtb) as well? you should probably check this:
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#1212-memory-size-recognition-error

**Comment by tv4you2016** [comment]
@serrj-sv  
In the original dtb I have 4gb of ram on the street and that only looks like 2gb

**Comment by ophub** [comment]
View the document and copy the u-boot
