### ISSUE TITLE
 hk1box4+64千兆     armbianjammy5.1老是死机无论是那个版本都会麻烦大佬帮忙看看

### ISSUE THREAD

**Issue by Deemo119** [ophub/amlogic-s9xxx-armbian#1198]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
![QQ图片20230322113330](https://user-images.githubusercontent.com/121919298/226801491-a8fc619c-e3de-4626-a0d4-94389b3a8daa.jpg)

**Comment by ophub** [comment]
换hk1的dtb

**Comment by Deemo119** [comment]
大佬具体是如何操作，我搜索了一下看见这篇20年的帖子请问是这样吗
![capture_20230322133642482](https://user-images.githubusercontent.com/121919298/226812785-d6ebef1e-5959-41c5-983e-a6705a635248.jpg)

**Comment by ophub** [comment]
你看网上的帖子，就下载帖子里的固件，这样你按照他的介绍操作是没错的。

如果你下载的是我这个仓库下载的，就要看我仓库的说明。用其他作者的说明操作也许不对。如果你不是很忙，不如先看看我仓库里的文档。

![Snip20230322_1](https://user-images.githubusercontent.com/68696949/226815919-c2abab3f-2a2d-4af9-a744-176ba16ca390.png)
![Snip20230322_3](https://user-images.githubusercontent.com/68696949/226815958-78fa5095-0cde-4d72-ac20-f844bbc7261b.png)
![Snip20230322_4](https://user-images.githubusercontent.com/68696949/226816051-14b686a8-5def-4f31-a8ba-26f5ac740682.png)

**Comment by ophub** [comment]
只需要改/boot/uEnv.txt里面dtb的值。当前系统的内核恐愰，你更新到别的系列的内核试试。

**Comment by Deemo119** [comment]
谢谢大佬暂时解决了

**Comment by ophub** [comment]
你换到哪个内核可以了？

**Comment by Deemo119** [comment]
我换个Armbian_23.05.0_amlogic_s905x3_jammy_6.1.20_server_2023.03.21.img的包然后吧dtb换了hk1的就好了，已经运行了2h不知道会不会等会掉

**Comment by JFLim1** [comment]
Hi @ophub,

Just an input, if I boot up kernel-5.15.103-flippy-82+o using "u-boot.ext" it will kernel panic.  The easiest to trigger it is to stream Youtube video on Chromium and also run "glmark2-es2-wayland".  This usually will trigger the kernel panic after awhile.  Similar experience with earlier kernel-5.15 when boot with "u-boot.ext"

So far if boot up kernel-5.15.103-flippy-82+o **without "u-boot.ext"** seems stable just like 5.15.88-happy-new-year.

**Comment by ophub** [comment]
The kernels of 5.4 and 5.15 do not require u-boot.ext

**Comment by JFLim1** [comment]
> The kernels of 5.4 and 5.15 do not require u-boot.ext

Hi @ophub,

Thanks.  Do know that kernels 5.4 and 5.15 with "Text Offset" do not need u-boot.ext.  Wanted to test whether kernel 5.15 is stable with u-boot.ext as on my GT King Pro if I boot with u-boot.ext it have significantly more RAM 3.68GB-3.70GB instead of 3.24-3.26GB.

If I remember correctly kernel-5.15.80 was stable with u-boot.ext the last I tested it.

Thanks for great support and works.

**Comment by BobDLA** [comment]
> 我换个Armbian_23.05.0_amlogic_s905x3_jammy_6.1.20_server_2023.03.21.img的包然后吧dtb换了hk1的就好了，已经运行了2h不知道会不会等会掉

您这个换了这个版本后稳吗，最长待机多长时间没问题啊
