### ISSUE TITLE
Support DB z1pro?

### ISSUE THREAD

**Issue by UMU618** [ophub/amlogic-s9xxx-armbian#120]
It's just like khadas vim3 Pro, with an extra camera.

Detail: https://shop.dangbei.com/parameterZ1PRO.html

**Comment by ophub** [comment]
There is currently no user feedback for this box. If you have a device, you can use the same soc firmware to start the test on the usb.

**Comment by UMU618** [comment]
Hi 大佬们，我买了 z1pro，刚用 khadas vim3 Pro 的镜像，无法启动。

具体是：断电，插 U 盘，用针按住 reset 孔，上电，但是直接就进入 Android9 了……看样子是要上 TTL？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.cn.md#1010-%E8%AE%BE%E7%BD%AE%E7%9B%92%E5%AD%90%E4%BB%8E-usbtfsd-%E4%B8%AD%E5%90%AF%E5%8A%A8

设置盒子从 USB/TF/SD 中启动

**Comment by ophub** [comment]
用5.4内核的固件测试

**Comment by UMU618** [comment]
5.4 成功到登陆界面，但有线网卡都没驱动起来，所以 USB 接口就一个，所以啥都干不了。

**Comment by skefy** [comment]
@UMU618 请问你的Z1 Pro搞定了吗？ 求固件和dtb
