### ISSUE TITLE
5.x 最新版里没有 vi 和 vim 么？

### ISSUE THREAD

**Issue by fanybook** [ophub/amlogic-s9xxx-armbian#1201]
如题：我用的是 bullseye 3.21号版的

**Comment by ophub** [comment]
有nano，无vi

**Comment by fanybook** [comment]
@ophub 6.x就有 vim，不能默认同时提供么，

**Comment by ophub** [comment]
上游默认去掉了，我没有改动默认设置，你apt安装

**Comment by fanybook** [comment]
@ophub 好吧，感谢 O 大回复

我找到一个简易教程
> https://www.bbsmax.com/A/rV57oGw95P/
> 笔者自己常用的是vim。这里nano的使用场景就是刚安装好Ubuntu系统，想要替换更新源，这时候还没装上vim。所以，学一下如何用nano查找和替换，可以解决这个小问题。

首先sudo nano /etc/apt/source.list进入nano编辑器。

先按Ctrl+\，系统提示输入要查找（被替换）的内容，输入之后按回车；这时候系统提示输入要用来替换的内容，输入之后再按回车。之后根据的提示按A，就完全全部替换了。

Ctrl
Enter your search term [press return]
Enter your replacement term [press return]
A [to replace all instances]

That's is!

**Comment by ophub** [comment]
```
sudo apt-get update
sudo apt-get install -y vim
```
