### ISSUE TITLE
安装headers失败

### ISSUE THREAD

**Issue by JustinTangChina** [ophub/amlogic-s9xxx-armbian#1203]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905l3a]
 - Model [e.g. 新魔百m401a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.104]
 - Release: [e.g. jammy]

写入MMC后 想在armbian系统下编译wifi驱动，前提需要安装headers，现在安装失败，提示自定义的后缀名不对

ophub老大 这个需要怎么安装？
执行以下这句会报错，找不到文件
sudo apt-get install linux-headers-$(uname -r)

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by JustinTangChina** [comment]
内核编译库里面也没有看到有  deb文件

**Comment by ophub** [comment]
header路径在/usr/src
已经安装了，每次armbian-update更新内核都会自动安装内核对应的header，不允许安装其他u-boot, image, header等，因为上游armbian不支持你的盒子，安装的包不匹配会无法使用。


https://github.com/ophub/amlogic-s9xxx-armbian/blob/a0992b4983194f3ff30d9144f5b6cba42809ad19/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L55-L63

**Comment by ophub** [comment]
搜以前的贴子里有方法
