### ISSUE TITLE
M411A写入emmc失败

### ISSUE THREAD

**Issue by Childlove** [ophub/amlogic-s9xxx-armbian#1204]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 - Model [e.g. M411A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
armbian-install 

```
[ STEPS ] Start creating eMMC partition... 
[ INFO ] Start backing up the default bootloader. 
dd: error reading '/dev/mmcblk2': Input/output error 0+0 records in 0+0 records out 0 bytes copied, 1.11677 s, 0.0 kB/s 
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader .img ] failed. 
```

**Comment by prioner1** [comment]
主板图上一下吧，我最近也在研究，试试看USB２.０的U盘

**Comment by ophub** [comment]
看帮助文档里，降低emmc频率试试

**Comment by Childlove** [comment]
armbian:~:# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda            8:0    1   7.8G  0 disk 
├─sda1         8:1    1   255M  0 part /boot
└─sda2         8:2    1   2.5G  0 part /
mmcblk2      179:0    0   7.1G  0 disk 
mmcblk2boot0 179:32   0     4M  1 disk 
mmcblk2boot1 179:64   0     4M  1 disk 
zram0        254:0    0 968.1M  0 disk [SWAP]
zram1        254:1    0    50M  0 disk /var/log

**Comment by Childlove** [comment]
emmc 为scy      内存sec 137   芯片s905l3    无线uwe5621ds

**Comment by Childlove** [comment]
![微信图片_20230326163738](https://user-images.githubusercontent.com/42514617/227764730-542d8a26-8d99-4377-8b36-6e7c43841b0b.jpg)
![微信图片_20230326163743](https://user-images.githubusercontent.com/42514617/227764736-3ae2b94a-cd16-4171-87e8-153c2630a10e.jpg)
![s905l3](https://user-images.githubusercontent.com/42514617/227764739-d4cf8a43-b11e-4d67-bb2b-940c17b4230c.jpg)
![uwe5621ds](https://user-images.githubusercontent.com/42514617/227764741-e4e628c5-3402-4e8f-943d-676fab2cd3bf.jpg)

**Comment by prioner1** [comment]
换个U盘吧，试试，我就是换了个慢速U盘就好了

**Comment by t9080** [comment]
M411a你们用的是什么atv？我刷了n个都不能引导armbian

**Comment by zqx654033799** [comment]
刷成功了吗？
