### ISSUE TITLE
这个uwe5621的驱动可以用么

### ISSUE THREAD

**Issue by prioner1** [ophub/amlogic-s9xxx-armbian#1205]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information | 设备信息

SOC: [e.g. S0905l3a]
Model [e.g. M411A黑龙江版本]
Armbian Version | 系统版本

Kernel Version: [e.g. 5.15.100-flippy-82+o]
Release: [eArmbian 23.05.0-trunk Jammy]
Describe the bug | 问题描述
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
uwe5621 这个驱动可以用么，大神帮忙看看

https://github.com/CoreELEC/uwe5631-aml

**Comment by ophub** [comment]
安卓的在armbian不能用
