### ISSUE TITLE
如何查找到n1基于debian buster的镜像？

### ISSUE THREAD

**Issue by hansid** [ophub/amlogic-s9xxx-armbian#1210]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905D
 - Model :N1
**Armbian Version | 系统版本**
 - Kernel Version: Armbian 23.02.0-trunk Bullseye with Linux 5.15.104-flippy-82+o
 - Release: Bullseye

**Describe the bug | 问题描述**

  升级到基于bullseye的armbian后，ssh会出现无法连接的问题，但armbian上的web服务却正常运行，定时重启ssh可以解决ssh无法连接。
  尝试下载过buster的内核，本地化打包后刷入emmc，问题依旧。判断问题出在软件包上。
  请问大佬，哪里可以找回之前基于debian buster的armbian镜像。

**Comment by ophub** [comment]
我没有，你在f大的度盘里有buster的下载。

**Comment by hansid** [comment]
多谢大佬指路。

**Comment by yuban10703** [comment]
请问哪里能找到基于Focal的版本....release里只有最新版本,有旧版本的存档么

**Comment by ophub** [comment]
没有存档

**Comment by yuban10703** [comment]
> 没有存档Focal

阿哲,有办法自己编译么
