### ISSUE TITLE
重启无法进系统/Cannot load system after reboot

### ISSUE THREAD

**Issue by jinwei91** [ophub/amlogic-s9xxx-armbian#1212]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905d
 - Model: Phicomm N1

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.12/5.15
 - Release: bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

N1插上移动硬盘/u盘重启后无法进系统：
1）6.x和5.1x内核的版本都试过；
2）系统是通过rufus写镜像到sandisk的u盘，然后安装到emmc；
3）现象：armbian中配置好samba环境不能断电或重启，硬盘通过uuid在fstab中挂载，一旦重启或者断电无法进系统，需要断电，拔掉硬盘/u盘，插电，等10秒以上load系统了再插上硬盘/u盘；
4）移动硬盘/u盘中无任何armbian镜像，非安装armbian时使用的u盘；

**Comment by cnmyn** [comment]
emmc装好系统好后，用[casaos.io](casaos.io)试试，自动配置samba；我以前用过，没有问题。

**Comment by jinwei91** [comment]
> emmc装好系统好后，用[casaos.io](casaos.io)试试，自动配置samba；我以前用过，没有问题。

samba是正常的，我现在配置了samba/aria2/docker，都是正常active，但是一重启就卡住，即使是全新安装不配置任何额外的软件也会有这问题。

**Comment by cnmyn** [comment]
> > emmc装好系统好后，用[casaos.io](casaos.io)试试，自动配置samba；我以前用过，没有问题。
> 
> samba是正常的，我现在配置了samba/aria2/docker，都是正常active，但是一重启就卡住，即使是全新安装不配置任何额外的软件也会有这问题。
检测一下，EMMC是否有坏块。

**Comment by jinwei91** [comment]
> > emmc装好系统好后，用[casaos.io](casaos.io)试试，自动配置samba；我以前用过，没有问题。
> 
> samba是正常的，我现在配置了samba/aria2/docker，都是正常active，但是一重启就卡住，即使是全新安装不配置任何额外的软件也会有这问题。 检测一下，EMMC是否有坏块。

扫了下没看到异常
