### ISSUE TITLE
自己编译个小马m68s的armbian 问题咨询

### ISSUE THREAD

**Issue by altmangood** [ophub/amlogic-s9xxx-armbian#1214]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information | 设备信息

SOC: RK3568
Model:  小马 Xiaoma M68S =[ rk3568-mrkaio-m68s.dts ](https://github.com/coolsnowwolf/lede/blob/7f8e3bf68c9eb592092871912bd497c62df4cfbf/target/linux/rockchip/files-5.15/arch/arm64/boot/dts/rockchip/rk3568-mrkaio-m68s.dts)
Armbian Version | 系统版本

Kernel Version: 5.15

coolsnowwolf/lede 有官方支持一个设备**小马m68s**
 是RK3568的soc，在那边有dts源码。

我想用 [amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian) 编译出m68s的armbian固件

我看文档有个 Local build instructions，里面有一步是要下载 Armbian_21.11.0-trunk_Odroidn2_current_5.15.50.img 

问题1：是否Odroidn2需要替换一个和我设备信息差不多的设备？

问题2：如果armbian那边没有合适的设备，我是否可以搞一个soc一样的固件，然后自己用lede那边的dts来编译内核呢？
我理解这个地方选odroidn2其实也是找个dtb差不多的固件复用内核然后换自己真实设备的dtb，那我都有dts了，理论上是不是可以自己编译内核和dtb来用

**Comment by ophub** [comment]
固件没特别喜欢，这里用一个固件生成全部。原固件的内核被替换了。专用的img, uboot等都删了。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/bc42b65101d16ea0fad04fead9235850d8c80197/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L55-L63

引导（/boot）也被整个换了。u-boot也换了。

扒拉完剩下的和rootfs几乎一模一样了。

你说的小马盒子我不了解。有u-boot和dtb一般来说就可以了。

**Comment by altmangood** [comment]
好的，非常感谢，我先研究下。
