### ISSUE TITLE
nand

### ISSUE THREAD

**Issue by Childlove** [ophub/amlogic-s9xxx-armbian#1218]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 - Model [e.g. 广东M411A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

非emmc   scy的nand   无线芯片
无法写入nand

meson-gxl-s905l2-x7-5g.dtb
Armbian_23.05.0_amlogic_s905l3_bullseye_5.15.104_server_2023.03.24.img

![uwe5621ds](https://user-images.githubusercontent.com/42514617/227770344-f0796a38-2df8-44a1-ac60-60afa788b6aa.jpg)
![s905l3](https://user-images.githubusercontent.com/42514617/227770353-b55be833-bf90-407e-b8ea-842f7e0b5e60.jpg)
![微信图片_20230326163738](https://user-images.githubusercontent.com/42514617/227770359-4175ff6c-6bad-45e4-8bb3-a4ab41a4fcdd.jpg)
![微信图片_20230326163743](https://user-images.githubusercontent.com/42514617/227770364-0bbd9a71-39f4-4d7d-9780-714c41b38cfa.jpg)

**Comment by janko888** [comment]
试一下U盘用meson-gxl-s905l3b-m302a.dtb启动后，用112写入emmc\nand.

l3b和l3基本通用

**Comment by Childlove** [comment]
> 试一下U盘用meson-gxl-s905l3b-m302a.dtb启动后，用112写入emmc\nand.
> 
> l3b和l3基本通用

uEnv.txt改成meson-gxl-s905l3b-m302a.dtb，没法联网，hdmi也没有反应，不清楚系统有没有启动

**Comment by Childlove** [comment]
拆开主板发现预留有ttl接口，直接利用ttl接口来观察？

**Comment by janko888** [comment]
你盒子的固件是安卓4还是安卓9？之前用的dtb可以正常联网？

**Comment by Childlove** [comment]
安卓4.4.2。
dtb： meson-gxl-s905l2-x7-5g.dtb
固件：Armbian_23.05.0_amlogic_s905l3_bullseye_5.15.104_server_2023.03.24.img
u-boot：u-boot-p212.bin改ext

**Comment by Childlove** [comment]
正常联网

**Comment by janko888** [comment]
找个安卓9的固件重新线刷后再试，应该可以了。这个板子安卓9+5.15内核有线网卡比较稳

**Comment by ophub** [comment]
nand无法写入，只能写入emmc的存储。
nand在命令行中看不到，目前没找到写入的方法。
有些盒子hdmi不可以使用，你在USB中可以ssh正常使用吧。

**Comment by janko888** [comment]
板子上面存储的"snand"字样，和m304a一样，我之前也是认为nand写不了，有次偶尔看到一个m304a原版固件的dtb，emmc频率只有26 000 000，修改后可以写入了
