### ISSUE TITLE
Software Suggestion：Aria2 , Samba .

### ISSUE THREAD

**Issue by lisen9065** [ophub/amlogic-s9xxx-armbian#1219]
希望整合软件（docker）：Aria2、aliyun-webdav、Samba 等等下载、局域网共享软件，谢谢。
ophub/amlogic-s9xxx-armbian越来越完善了，赞~

https://github.com/messense/aliyundrive-webdav

**Comment by SoraKasvgano** [comment]
每个人的使用用途使用环境不同，这些服务可以自己装

docker一键安装脚本没有什么难度
