### ISSUE TITLE
A start job is running for Raise network interfaces.

### ISSUE THREAD

**Issue by marohinmark** [ophub/amlogic-s9xxx-armbian#122]
I am trying to run latest Armbian_22.02.0_Aml_s905x3_focal_5.15.25_2022.02.24.1819.img.gz, dtb: meson-sm1-h96-max-x3-oc.dtb on h96 max x3, and it hangs 5 mins on "A start job is running for Raise networks interfaces before booting"

**Comment by marohinmark** [comment]
I do not have any wifi adapters plugged in

**Comment by marohinmark** [comment]
Tried dtb without oc, also does not work.

**Comment by ophub** [comment]
There are too many variants of the box, what is your SoC? What chip is the network card?
You try the firmware of 5.4 kernel

**Comment by marohinmark** [comment]
Blue board, it6334.

**Comment by marohinmark** [comment]
Did a build on my fork of repository, it actually booted faster and didn't hang for so long.

**Comment by marohinmark** [comment]
Network works with usb adapter.

**Comment by ophub** [comment]
In the kernel, the common drivers of the amlogic box, the USB external network card, and the wifi are compiled by default.
If you can't use it, it may be a newly revised motherboard. You can check its serial number and search in the kernel source code. If there is, you can compile a custom kernel test.

**Comment by marohinmark** [comment]
everything is fine, wifi is not supported on any revision of the box I think

**Comment by marohinmark** [comment]
> In the kernel, the common drivers of the amlogic box, the USB external network card, and the wifi are compiled by default. If you can't use it, it may be a newly revised motherboard. You can check its serial number and search in the kernel source code. If there is, you can compile a custom kernel test.

I cant understand why do my CI builds (from same source with no mods) boot, but builds from here do nott
