### ISSUE TITLE
#REQUEST: Build with Desktop Environment. Failed to Install Desktop Environment Using armbian-software 201

### ISSUE THREAD

**Issue by batoceragaming** [ophub/amlogic-s9xxx-armbian#1221]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [x96 Max+ 2101]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.21]
 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

after successfully installing Armbian Jammy kernel 6.1.21 in my X96 Max + 2101. I amazed with the DTB that works out of the box. However when I tried to install desktop environment it fails and I got bootloop with text failed "No Backend DAIS enabled..."

1st attempt, manual installing
sudo apt install kubuntu-desktop kscreen konsole dolphin

2nd attempt, automatic install via armbian-software no. 201

Both I made a clean install on my SD Card. Both have the same bootloop issue after entering the username and password.

Is there any plan to support Desktop Environment in the Future?

Many Thanks.

![20230327_205422x](https://user-images.githubusercontent.com/119865621/227962687-d7caa880-9f86-4a16-a8ee-b3fe0578bbf5.jpg)

**Comment by batoceragaming** [comment]
I got those error when installing using 201 method. Do you know what's wrong?

**Comment by Supded** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1034

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#1217-how-to-fix-the-bullseye-version-with-no-sound
