### ISSUE TITLE
king3399的USBhub无法使用

### ISSUE THREAD

**Issue by tdleiyao** [ophub/amlogic-s9xxx-armbian#1225]
**Device Information | 设备信息**
 - SOC: rk3399
 - Model king3399

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.21
 - Release: jammy

**Describe the bug | 问题描述**
king3399在上电后没有将USBhub的复位脚（gpio1_d0）拉高，导致hub拓展出来的三个USB无法使用

**Comment by 13584452567** [comment]
pr已交

**Comment by 392377870** [comment]
> 添

确实，中间三个usb口无法使用

**Comment by mizegit** [comment]
拉高io口，就能识别usb hub了。

最快的办法是写到开机脚本。

```
cat << EOF >> /etc/custom_service/start_service.sh

echo 56 > /sys/class/gpio/export
echo out > /sys/class/gpio/gpio56/direction
echo 1 > /sys/class/gpio/gpio56/value
EOF
```

**Comment by TheRainstorm** [comment]
> 拉高io口，就能识别usb hub了。
> 
> 最快的办法是写到开机脚本。
> 
> ```
> cat << EOF >> /etc/custom_service/start_service.sh
> 
> echo 56 > /sys/class/gpio/export
> echo out > /sys/class/gpio/gpio56/direction
> echo 1 > /sys/class/gpio/gpio56/value
> EOF
> ```

Hello, I used this script and it worked! Thank you very much.

However, after running these commands, my two USB 3.0 ports (one USB-A and one Type-C) stopped working. Do you know any possible reasons for this issue?

**Comment by mizegit** [comment]
> > 拉高io口，就能识别usb hub了。
> > 最快的办法是写到开机脚本。
> > ```
> > cat << EOF >> /etc/custom_service/start_service.sh
> > 
> > echo 56 > /sys/class/gpio/export
> > echo out > /sys/class/gpio/gpio56/direction
> > echo 1 > /sys/class/gpio/gpio56/value
> > EOF
> > ```
> 
> Hello, I used this script and it worked! Thank you very much.
> 
> However, after running these commands, my two USB 3.0 ports (one USB-A and one Type-C) stopped working. Do you know any possible reasons for this issue?

是拉高gpio56后usb3.0的接口就不能用了吗？

**Comment by mizegit** [comment]
> > 拉高io口，就能识别usb hub了。
> > 最快的办法是写到开机脚本。
> > ```
> > cat << EOF >> /etc/custom_service/start_service.sh
> > 
> > echo 56 > /sys/class/gpio/export
> > echo out > /sys/class/gpio/gpio56/direction
> > echo 1 > /sys/class/gpio/gpio56/value
> > EOF
> > ```
> 
> Hello, I used this script and it worked! Thank you very much.
> 
> However, after running these commands, my two USB 3.0 ports (one USB-A and one Type-C) stopped working. Do you know any possible reasons for this issue?

不太清楚，之前没有注意过3.0口是否能用，拉高io口是使能usb hub芯片，您可以看看原理图
