### ISSUE TITLE
特别卡特别卡，不知道是什么原因导致的，求大神指导

### ISSUE THREAD

**Issue by hgl0110** [ophub/amlogic-s9xxx-armbian#1226]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S05la]
 - Model [e.g.[ 中兴B863AV3.1-M]

**Armbian Version | 系统版本**
 [- Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_03.28.0540/Armbian_23.05.0_amlogic_s905l3a_bullseye_6.1.21_server_2023.03.28.img.gz)

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

ambian安装玩了之后，系统负载76%，特别卡，HA安装好了之后，负载会从132%达到220%，几乎卡爆了
请问可能是什么原因导致的
![WX20230328-230238@2x](https://user-images.githubusercontent.com/126386634/228281494-94b63cd0-e981-4197-9500-7fa2c91fdd7f.png)

**Comment by ophub** [comment]
htop看看进程

**Comment by hgl0110** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by hgl0110** [comment]
是因为这个dockerd -h影响的吗？我主要是用来安装HA的，麻烦大神帮我看看，该如何解决啊
![WX20230329-084954@2x](https://user-images.githubusercontent.com/126386634/228398428-73b55a5d-412f-41f4-bf6d-baef071ff76a.png)

**Comment by ophub** [comment]
开机后10分钟内负载高可以忽略，安装的服务多的情况下需要逐步启动初始化，等10分钟负载就下来了。正常情况下没什么任务执行时CPU的负载不超过5%
停止了docker看不卡，启用了就卡，说明就是docker压力比较大，你只能这样了，我也不能让你删除docker。
如果你跑的任务很多，等玩的好了可以逐渐升级设备。
