### ISSUE TITLE
开机提示failled to start disk manager

### ISSUE THREAD

**Issue by hgl0110** [ophub/amlogic-s9xxx-armbian#1228]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905la]
 - Model [e.g. 中兴B863AV3.1-M]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g.(https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_03.28.0540/Armbian_23.05.0_amlogic_s905l3a_bullseye_5.15.104_server_2023.03.28.img.gz)]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

开机提示failled to start disk manager，请问大神，可能是哪里的问题啊
![WechatIMG538](https://user-images.githubusercontent.com/126386634/228449104-7625ee3b-0845-4c8c-9066-6da3dfd5850b.jpeg)

**Comment by ophub** [comment]
启动了没？这是USB还是emmc？

**Comment by hgl0110** [comment]
u盘启动的

**Comment by ophub** [comment]
魔百和用2.0的u盘，用高速的可能会不稳定。

**Comment by hgl0110** [comment]
明白了，我刚好是USB 3.2的，有没有办法解决啊
