### ISSUE TITLE
e900v22d刷了armbian后，时常来一个meson_clk_pll_set_rate

### ISSUE THREAD

**Issue by screek-workshop** [ophub/amlogic-s9xxx-armbian#1229]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905l3a
 - Model E900V22D

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.21
 - Release:flippy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

这里归纳问题核心：
在`dmesg`日志里能时不时看到一些pll错误，叫人觉得armbian应该很完美，怎么这里不够完美？
```bash
[Thu Mar 30 12:46:22 2023] hassio: port 2(veth716b863) entered blocking state
[Thu Mar 30 12:46:23 2023] hassio: port 2(veth716b863) entered forwarding state
[Thu Mar 30 12:46:25 2023] audit: type=1400 audit(1680151586.936:20): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="hassio-supervisor" pid=44641 comm="apparmor_parser"
[Thu Mar 30 12:46:25 2023] audit: type=1400 audit(1680151586.956:21): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="hassio-supervisor///usr/bin/gdbus" pid=44641 comm="apparmor_parser"
[Thu Mar 30 12:46:25 2023] audit: type=1400 audit(1680151586.956:22): apparmor="STATUS" operation="profile_replace" profile="unconfined" name="hassio-supervisor///usr/bin/git" pid=44641 comm="apparmor_parser"
[Thu Mar 30 18:51:47 2023] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[Thu Mar 30 19:02:20 2023] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
```
在另一台机器里也出现了
```bash
[Wed Mar 29 14:59:11 2023] device veth37ca7b5 left promiscuous mode
[Wed Mar 29 14:59:11 2023] hassio: port 10(veth37ca7b5) entered disabled state
[Wed Mar 29 16:58:37 2023] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
```

下面是早期反馈：

刷了armbian，目前挺稳定，没有遭遇别的坑，温度也挺适合。但是就是时常来点这个，似乎都是来自音频部分？？
如果不需要使用声音输出，是不是可以在dtb里禁止掉这东西？
![image](https://user-images.githubusercontent.com/126383355/228494649-486936bb-8d95-46de-acc8-f2954f74f29b.png)

在dmesg能常常看到这一类信息：
```bash

[   40.843314]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22
[   40.851385]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[   40.857860]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22
[   40.865984]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[   40.872418]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22
[   40.880579]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[   40.886991]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22
[   40.895273]  fe.dai-link-0: ASoC: no backend DAIs enabled for fe.dai-link-0
[   40.901632]  fe.dai-link-0: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-0: -22

[ 7273.856727] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
```

**Comment by ophub** [comment]
亲，刚给你量身定做了操作说明，看最近的更新文档。

**Comment by screek-workshop** [comment]
收到！声音的迷解开了，那么pll那个也是和声音关联吗？From Sen在 2023年3月29日，18:16，ophub ***@***.***> 写道：﻿
亲，刚给你量身定做了操作说明，看最近的更新文档。

**Comment by ophub** [comment]
https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2423920.html

另一个要求打补丁

**Comment by screek-workshop** [comment]
> https://www.mail-archive.com/linux-kernel@vger.kernel.org/msg2423920.html
> 
> 另一个要求打补丁

打补丁的一般流程应该如何出发？完全没有做过这样的事情。

**Comment by ophub** [comment]
需要f大在内核源码里打补丁。f大最近比较忙，一般的事我不好意思老去打扰他，等他忙完了我发给他看看。

**Comment by ophub** [comment]
这个使用armbian官方源码实时编译出的最新固件，替换了/boot和内核，支持了官方不支持的一些盒子。

amlogic盒子变种很多，比如在一个俄文论坛里，一个贴子列出了在他们市场上可以买到的x96max就有10几种。包括amlogic的闭源锁bootloader等操作，让这些盒子的支持很困难，单品用户量不大，花样百出，耗费了很多开发者的精力，大佬们都陆续删库远离烦扰了。

coreelec支持会容易一点，都是安卓系统，盒子原来支持的无线和蓝牙在ce上驱动好支持，armbian使用主线内核，驱动和安卓不通用。

这里没有蓝图，只有一个一个的坑，一天一天的填，刚填了几个，又来了几个，满眼都是洞洞，没有诗和远方。

**Comment by screek-workshop** [comment]
> 这个使用armbian官方源码实时编译出的最新固件，替换了/boot和内核，支持了官方不支持的一些盒子。
> 
> amlogic盒子变种很多，比如在一个俄文论坛里，一个贴子列出了在他们市场上可以买到的x96max就有10几种。包括amlogic的闭源锁bootloader等操作，让这些盒子的支持很困难，单品用户量不大，花样百出，耗费了很多开发者的精力，大佬们都陆续删库远离烦扰了。
> 
> coreelec支持会容易一点，都是安卓系统，盒子原来支持的无线和蓝牙在ce上驱动好支持，armbian使用主线内核，驱动和安卓不通用。
> 
> 这里没有蓝图，只有一个一个的坑，一天一天的填，刚填了几个，又来了几个，满眼都是洞洞，没有诗和远方。

哈哈，这真是一条刺激而又充满了挑战的道路。  
你们的工作很了不起！目前一个cm311-1a的盒子跑HomeAssistant一直挺稳定，是你们让这个魔法发生的！感谢！
这个问题应该可以关闭了。  

晶晨应该开窍点提供更多的开放文件，毕竟这也是一个市场啊。跑跑小主机，多方便的机器啊。

**Comment by ophub** [comment]
晶晨只想让盒子好好地演电视，他们很想不明白为什么我们要刷armbian，剧本不是这么设计的，我们纯属不务正业的捣乱分子。
