### ISSUE TITLE
Package 'ifupdown2' has no installation candidate

### ISSUE THREAD

**Issue by molun** [ophub/amlogic-s9xxx-armbian#1230]
armbian:~:# armbian-software
[ STEPS ] Start installing the necessary dependencies...
Hit:1 https://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy InRelease
Hit:3 http://ports.ubuntu.com jammy InRelease                                                  
Hit:4 https://downloads.plex.tv/repo/deb public InRelease                           
Hit:5 http://ports.ubuntu.com jammy-security InRelease                              
Hit:6 http://ports.ubuntu.com jammy-updates InRelease         
Hit:7 http://ports.ubuntu.com jammy-backports InRelease       
Get:2 http://armbian.hosthatch.com/apt jammy InRelease [52.4 kB]
Get:8 http://armbian.hosthatch.com/apt jammy/jammy-utils armhf Packages [44.9 kB]                                                                                                              
Get:9 http://armbian.hosthatch.com/apt jammy/jammy-utils arm64 Packages [52.3 kB]                                                                                                              
Fetched 150 kB in 15s (10.2 kB/s)                                                                                                                                                              
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package ifupdown2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ifupdown2' has no installation candidate
[ ERROR ] Dependency installation failed, stop install.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/4f1ee419163150defd8dd1ea3969454ce1be46a9

Thanks for the bug feedback, I have adjusted his installation, you can synchronize the latest script:

`armbian-sync`
