### ISSUE TITLE
更新最新脚本后，青龙消失，默明奇妙出现了Thunderbird

### ISSUE THREAD

**Issue by molun** [ophub/amlogic-s9xxx-armbian#1234]
![Uploading image.png…]()
![Uploading image.png…]()

**Comment by molun** [comment]
![Snipaste_2023-03-30_21-02-47](https://user-images.githubusercontent.com/23138506/228844581-cd24d9a6-b282-437f-b12c-c3f89ee34dbc.png)
![Snipaste_2023-03-30_21-02-55](https://user-images.githubusercontent.com/23138506/228844596-02dc61a4-d715-4e37-a9cf-6a2b63ab2100.png)

**Comment by molun** [comment]
![Uploading image.png…]()
之前安装的hassio也消失了

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/228845929-6312569d-9d04-47ad-855e-7c1734764cbf.png)

**Comment by ophub** [comment]
怎么更新的脚本

**Comment by molun** [comment]
[ OPTIONS ] Please Input Software ID: 108
[ INFO ] Software ID: [ 108 ]
[ INFO ] Software Name: [ HomeAssistant ]
[ STEPS ] Start processing software: [ command-docker.sh install HomeAssistant ]...
[ INFO ] Software Manage: [ 108 / install ]
[ STEPS ] Start installing the docker image: [ homeassistant ]...
docker: Error response from daemon: Conflict. The container name "/homeassistant" is already in use by container "bb3b4358e94abb1c9596ae46bf84cd040058d3a977237eb75fef6d8b32169164". You have to remove (or rename) that container to be able to reuse that name.
See 'docker run --help'.
[ NOTE ] The homeassistant app [ Home Assistant ]
[ NOTE ] The homeassistant address [ http://ip:8123 ]
[ SUCCESS ] homeassistant installed successfully.

没有主动安装过Thunderbird，今天白天青龙运行还是正常的，晚上看到你恢复修复了更新问题，armbian-sync之后执行armbian-software便发现homeassistant、qinglong显示未安装状态，莫名多出了Thunderbird
重新安装homeassistant、qinglong提示以上错误

**Comment by molun** [comment]
问题解决了 不知什么原因这两个容器未启动 手动启动也打不开  删除容器重建后可以使用了

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/228869282-398e0f8c-f551-4a19-a338-429fbec24968.png)
