### ISSUE TITLE
关于S905L3A盒子3.5mm音频接口的一些信息。

### ISSUE THREAD

**Issue by stonegitt** [ophub/amlogic-s9xxx-armbian#1235]
拆了几个料板，量了一下音频驱动芯片直通CPU的脚位
得到的信息如下：
A.音频驱动芯片有一个使能引脚，高电平使能。目前为低电平。
B.左右声道输入目前没有信号。
使能引脚输出个高电平不知道能不能驱动板载的耳机孔。

**Comment by uncle-wong** [comment]
可以试试吧，这个引脚是几号？
