### ISSUE TITLE
armbian-update stopped working

### ISSUE THREAD

**Issue by sharicov** [ophub/amlogic-s9xxx-armbian#1236]
armbian-update stopped working.
Used guidance in closed tickets to update script 
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync ; armbian-sync; armbian-update
and added KERNEL _BRANCH='stable' to  /etc/ophub-release
 Now getting following error, when running armbian-update:

[ STEPS ] Start backing up the current kernel...
[ INFO ] (1/4) The [ boot-5.15.103-flippy-82+o.tar.gz ] backup successful.
[ INFO ] (2/4) The [ dtb-amlogic-5.15.103-flippy-82+o.tar.gz ] backup successful.
cp: cannot stat '/usr/src/linux-headers-5.15.103-flippy-82+o/*': No such file or directory
[ ERROR ] (3/4) Failed to copy [ /usr/src/linux-headers-5.15.103-flippy-82+o/* ] files.

Please help.

**Comment by ophub** [comment]
`armbian-update -b no`

If the kernel of your current system is incomplete (no header), you don't need to back it up.

**Comment by sharicov** [comment]
Thanks a lot! worked lake a charm!
