### ISSUE TITLE
armbian-software  安装的pve无法启动

### ISSUE THREAD

**Issue by hanhavb12** [ophub/amlogic-s9xxx-armbian#1238]
![Screenshot_20230331_210139_com deskangel daremote](https://user-images.githubusercontent.com/61574461/229158672-de5ba385-055f-4fe7-87c3-287f97ffd06c.jpg)
安装重启也无法启动

**Comment by ophub** [comment]
使用`armbian-sync`同步最新脚本就可以了。我调整了`ifupdown2`放在最后安装就可以了，和PVE一起安装时中间会断开网络。

![Snip20230402_1](https://user-images.githubusercontent.com/68696949/229347015-ac1a00fa-18e1-414c-a843-8eabd23b3cfb.png)
![Snip20230402_2](https://user-images.githubusercontent.com/68696949/229347021-336aa474-dae0-404a-b329-425c616c231c.png)
![Snip20230402_3](https://user-images.githubusercontent.com/68696949/229347023-2b7b5499-0926-40c3-9361-d5403e041dbf.png)
![Snip20230402_6](https://user-images.githubusercontent.com/68696949/229347025-2d58e2c8-f240-4145-896f-e5609764f11e.png)

**Comment by hanhavb12** [comment]
![Screenshot_20230402_214850_com deskangel daremote](https://user-images.githubusercontent.com/61574461/229357436-b269a672-a5ea-4f41-8cef-2009367a5248.jpg)
脚本无法启动，网址404

**Comment by ophub** [comment]
你这会访问不了github.com吧

**Comment by hanhavb12** [comment]
> 你这个会问没有github.com吧

![Uploading Screenshot_20230403_101332_com.baidu.input_huawei.jpg…]()

**Comment by hanhavb12** [comment]
![Uploading Screenshot_20230403_101332_com.baidu.input_huawei.jpg…]()

**Comment by ophub** [comment]
你发的图还没上传完成你就提交了，别人看不到图片

**Comment by hanhavb12** [comment]
![Screenshot_20230403_101332_com baidu input_huawei](https://user-images.githubusercontent.com/61574461/229403481-b92266b7-4a2e-4388-855c-806841b92c4b.jpg)

**Comment by hanhavb12** [comment]
> 你发的图还没上传完成你就提交了，别人看不到图片

![Screenshot_20230403_101332_com baidu input_huawei](https://user-images.githubusercontent.com/61574461/229420279-7d25718c-3193-40e1-9369-c12f21ecac00.jpg)

**Comment by zhzih** [comment]
这个问题最后怎么解决的?
我一开始装的好几次都是安装pve后，重启系统就没有ip地址了，看了这个帖子后，发现是无法访问git，，挂上梯子重装装一次后，看着像是一切成功了，重启系统后也还有ip地址，但是armbian-software里pve那一行还是显示的未安装。。而且安装完pve时也没有弹出那个画面。

**Comment by ophub** [comment]
如果是之前的系统，安装前先同步最新脚本。
```
armbian-sync
armbian-software
```

**Comment by zhzih** [comment]
开机后我就设置了下静态ip
更改源
然后armbian-sync
armbian-software还是行，是不是少什么步骤了

**Comment by ophub** [comment]
pve我日常也在使用，我的rock5b和ali-ct2000上都可以正常识别。

![Snip20230530_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/ea032e2d-4e75-4bef-966a-ceed6a9e2a33)
![Snip20230530_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/4cb3b5ee-8a85-47ab-9d66-4601cb97e85a)
![Snip20230530_3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/80325e12-2e05-438b-a36f-4106770b930f)
![Snip20230530_4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/3ca78f72-7be3-4930-84fa-8a4c8579e38c)

**Comment by Angel0726** [comment]
> 这个问题最后怎么解决的? 我一开始装的好几次都是安装pve后，重启系统就没有ip地址了，看了这个帖子后，发现是无法访问git，，挂上梯子重装装一次后，看着像是一切成功了，重启系统后也还有ip地址，但是armbian-software里pve那一行还是显示的未安装。。而且安装完pve时也没有弹出那个画面。

无法获取ip地址，那么只能重装吗？

**Comment by nanosunny** [comment]
Configuration file '/etc/apt/sources.list.d/pveport.list'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** pveport.list (Y/I/N/O/D/Z) [default=N] ? 

选哪个啊？

**Comment by nanosunny** [comment]
Configuration file '/etc/apt/sources.list.d/pveport.list'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** pveport.list (Y/I/N/O/D/Z) [default=N] ? 

选哪个啊？
