### ISSUE TITLE
Vontar X4: unsupported

### ISSUE THREAD

**Issue by lcapriotti** [ophub/amlogic-s9xxx-armbian#1239]
**Device Information | 设备信息**
 - SOC: S095x4
 - Model : Vontar X4, RAM 4GB, EMMC 64GB

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.22
 - Release: s905x3_jammy_6.1.22_server_2023.03.31

**Describe the bug | 问题描述**
Device does not boot from USB: USB is accessed (LED flashes), andVontar logo stays on the screen, then USB stops flashing and Vontar logo stays forever.

meson-sm1-hk1box-vontar-x3.dtb <- uEnv.txt
FDT=/dtb/amlogic/meson-sm1-hk1box-vontar-x3.dtb

**Comment by ophub** [comment]
The current kernel does not support s905x4

**Comment by lcapriotti** [comment]
given emulelec stable supports this box perfectly, is there anything I can do to contribute and have this chipset supported?
