### ISSUE TITLE
hk1 box有线

### ISSUE THREAD

**Issue by fengyuanluo** [ophub/amlogic-s9xxx-armbian#1241]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1 box]

**Armbian Version | 系统版本**
 - Kernel Version: [ 5.15.95]
 - Release: [bully什么什么的Debian11]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
之前反馈过一次没解决的hk1box 网卡无法正常驱动问题，尝试使用教程方法连接无线网络出现以下报错
另coreelec的dtb可正常驱动，能不能反编译其dtb文件并对其进行修改，使其适应armbian？
![Screenshot_20230402_155525_com sonelli juicessh](https://user-images.githubusercontent.com/109848252/229342644-c3117a38-4b38-427b-b8e3-93f0f76a44a3.jpg)
麻烦大佬了

**Comment by ophub** [comment]
更新到最新内核

**Comment by fengyuanluo** [comment]
![Uploading Screenshot_20230402_172302_com.sonelli.juicessh.jpg…]()

**Comment by fengyuanluo** [comment]
无线能连上

**Comment by fengyuanluo** [comment]
![Screenshot_20230402_172302_com sonelli juicessh](https://user-images.githubusercontent.com/109848252/229344216-b6f14d54-9f98-42c1-86d1-40a349833868.jpg)
![Uploading Screenshot_20230402_172302_com.sonelli.juicessh.jpg…]()

**Comment by ophub** [comment]
你不是说无线报错吗？你问的什么问题？

**Comment by fengyuanluo** [comment]
有线保存，不好意思，那一段笔误

**Comment by fengyuanluo** [comment]
报错

**Comment by ophub** [comment]
内核不能更新是仓库变了，先 `armbian-sync` 升级脚本到最新，再更新就可以了。
有线如果不能用无解，coreelec是安卓，armbian是主线内核，无法使用安卓的驱动。

**Comment by fengyuanluo** [comment]
行吧，感谢大佬，再多问一嘴晶晨免拆机神器在刷入主线uboot后能用吗？

**Comment by ophub** [comment]
这个神器等于短接，所以理论上能用
