### ISSUE TITLE
请求添加对EAIDK-310开发板的支持

### ISSUE THREAD

**Issue by qinghua907** [ophub/amlogic-s9xxx-armbian#1243]
EAIDK-310是和EAIDK-610同一个公司出的，现在公司官网已经上不去了。我看到这里适配和EAIDK-610的固件，能否添加对EAIDK-310的固件支持？
EAIDK-310主控SOC是RK3228H，据说和RK3328一样，下面是EAIDK-310的一个简单介绍网页：
https://aijishu.com/a/1060000000113075

下面是一个人分享的固件：
https://aijishu.com/a/1060000000009642

**Comment by lawpdas** [comment]
同求

**Comment by 13584452567** [comment]
很遗憾，eaidk-310没有主线内核的支持，而且我也没有310这块板子，并不能适配。后面我会尝试添加官方4.4内核到仓库内，不过希望不大。

**Comment by qinghua907** [comment]
谢谢，至少有希望了

**Comment by lawpdas** [comment]
我找到了官方资料，不知道有无帮助
链接: https://pan.baidu.com/s/1yjBwm1bm8jfZI7um6sp19w?pwd=gd6p 提取码: gd6p

**Comment by wwdnumone** [comment]
> 

你好，链接失效了能重新分享一次吗

**Comment by wwdnumone** [comment]
同求

**Comment by allonmymind** [comment]
> 很遗憾，eaidk-310没有主线内核的支持，而且我也没有310这块板子，并不能适配。后面我会尝试添加官方4.4内核到仓库内，不过希望不大。
> 
> 看起来4.4内核无法在目前的armbian上面运行。在得到主线支持之前我无能为力。

事实上，rk3318的固件能在310上运行，包括5.1x内核的固件

**Comment by yjdwbj** [comment]
我这边编译了一个镜像是支持主线内核的, [rockchip-eaidk-310](https://github.com/yjdwbj/rockchip-eaidk-310). @allonmymind @qinghua907 @wwdnumone @13584452567

**Comment by zuoyi001** [comment]
> 我这边编译了一个镜像是支持主线内核的, [rockchip-eaidk-310](https://github.com/yjdwbj/rockchip-eaidk-310). @allonmymind @qinghua907 @wwdnumone @13584452567

Can you share the compilation process?
