### ISSUE TITLE
山东移动魔百盒 UNT403A CPU是S905L3 U盘启动卡在REC界面，显示刷机失败

### ISSUE THREAD

**Issue by song3470** [ophub/amlogic-s9xxx-armbian#1244]
UNT403A ，CPU是S905L3，后面没有A或B。安卓版本是4.4，armbian刷了两个Armbian_23.05.0_amlogic_s905l3_jammy_5.15.105_server_2023.04.03.img.gz 和 Armbian_23.05.0_amlogic_s905l3a_jammy_5.15.105_server_2023.04.03.img.gz 均无法从U盘启动。
请问是安卓版本太低了？还是其他原因？

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

换9.0的安卓系统

**Comment by song3470** [comment]
如果想保留盒子的IPTV功能的话，有什么办法吗？
毕竟IPTV看电视直播稳定，而且不卡，还高清。

**Comment by ophub** [comment]
在USB上用，不写入emmc

**Comment by song3470** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 换9.0的安卓系统

1.目前盒子的安卓版本是4.4.2，先刷成9.0的话IPTV是否还存在？
2.如果IPTV还存在的话，那么应该刷你给的链接中的哪个包升到安卓9.0？
![QQ浏览器截图20230404150717](https://user-images.githubusercontent.com/129815279/229715567-6f84399a-0211-4d45-aca6-9a3126cef596.png)

**Comment by ophub** [comment]
不知道，为了iptv还是别换了。

**Comment by LondyGhost** [comment]
> > https://github.com/ophub/kernel/releases/tag/tools
> > 换9.0的安卓系统
> 
> 1.目前盒子的安卓版本是4.4.2，先刷成9.0的话IPTV是否还存在？ 2.如果IPTV还存在的话，那么应该刷你给的链接中的哪个包升到安卓9.0？ ![QQ浏览器截图20230404150717](https://user-images.githubusercontent.com/129815279/229715567-6f84399a-0211-4d45-aca6-9a3126cef596.png)

刷机肯定无法保留iptv的

**Comment by song3470** [comment]
最后再问一嘴：
山东移动魔百盒 UNT403A CPU是S905L3 后面没有A也没有B，应该刷哪个版本的armbian?
![image](https://user-images.githubusercontent.com/129815279/230386982-cf4b5fd1-faa4-41a8-a979-6cdfa7bbed5e.png)

**Comment by ophub** [comment]
第三个，选择一样的。
不过不一样的有些也可以混用。你可以比较一下model表看哪个瞅着顺眼。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

**Comment by song3470** [comment]
鉴定完毕，安卓4.4的这个盒子，直接刷不了armbian。
升级安卓版本能不能刷没有测试。

**Comment by LondyGhost** [comment]
> 同型号unt403a，cpu是s905l3，我先刷了一个安卓 [android_tv_m401a_s905l3.tar.xz]，这个可以进安卓桌面，都是root后的，除了分辨率其他都正常，然后把s905l3的armbian都试了一遍，全部都是黑屏启动不起来，现在刷的有点郁闷了，求指教，谢谢

黑屏不一定是启动失败。s905l3的hdmi大部分没输出

**Comment by maxiaoyuzdz** [comment]
可是我看路由器dhcp也没有对应的新ip，怎么试也没有出来个新ip，感觉好像卡在什么地方了，因为第一次不是要进系统进行一下设置么，就这么卡住了，莫非我遗漏了什么

**Comment by maxiaoyuzdz** [comment]
> > 同型号unt403a，cpu是s905l3，我先刷了一个安卓 [android_tv_m401a_s905l3.tar.xz]，这个可以进安卓桌面，都是root后的，除了分辨率其他都正常，然后把s905l3的armbian都试了一遍，全部都是黑屏启动不起来，现在刷的有点郁闷了，求指教，谢谢
> 
> 黑屏不一定是启动失败。s905l3的hdmi大部分没输出
可是我看路由器dhcp也没有对应的新ip，怎么试也没有出来个新ip，感觉好像卡在什么地方了，因为第一次不是要进系统进行一下设置么，就这么卡住了，莫非我遗漏了什么

**Comment by maxiaoyuzdz** [comment]
> > 同型号unt403a，cpu是s905l3，我先刷了一个安卓 [android_tv_m401a_s905l3.tar.xz]，这个可以进安卓桌面，都是root后的，除了分辨率其他都正常，然后把s905l3的armbian都试了一遍，全部都是黑屏启动不起来，现在刷的有点郁闷了，求指教，谢谢
> 
> 黑屏不一定是启动失败。s905l3的hdmi大部分没输出

不行，最后换到 Armbian_23.05.0_amlogic_s905l3_jammy_5.15.112_server_2023.05.18.img， 还是黑屏，显示器不亮，路由器没有ip，就这么卡住了，我买了一个同型号刷好的，不知道那店家是怎么刷进去的，郁闷呐

**Comment by maxiaoyuzdz** [comment]
用线刷了android_tv_m401a_s905l3.tar.xz之后，就基本没法再线刷了，一连就断，挺无奈的

**Comment by maxiaoyuzdz** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 换9.0的安卓系统

你好，刷了android_tv_m401a_s905l3.tar.xz ，线刷工具就没法连接了，然后试了所有的armbian s905l3的版本都不行
