### ISSUE TITLE
MGV3000使用5.15内核有什么办法能够进行HDMI输出？

### ISSUE THREAD

**Issue by setun-ogas** [ophub/amlogic-s9xxx-armbian#1245]
我现在给MGV3000的盒子刷了5.15的内核想使用HDMI显示输出，有什么办法吗？

**Comment by ophub** [comment]
没法用。

**Comment by setun-ogas** [comment]
一点办法都没有吗？

**Comment by ophub** [comment]
魔百盒系列可能都这样。另外如果用桌面的话，建议用更强一点的soc，比如s905x3。或者是用kvm装远程桌面。

**Comment by setun-ogas** [comment]
@ophub 倒不是说想用桌面就是想命令行界面能有HDMI的输出，有啥能自己实现的办法也可以说一说我试试

**Comment by ophub** [comment]
如果显示器只是看终端命令，ssh里面不一样？

**Comment by setun-ogas** [comment]
@ophub 确实一样，但是我只是单纯想折腾一下HDMI

**Comment by setun-ogas** [comment]
@alanfans 那我想问一下为啥原来的安卓系统就有HDMI输出

**Comment by alanfans** [comment]
> @alanfans 那我想问一下为啥原来的安卓系统就有HDMI输出

因为安卓定制的，有驱动和适配hdmi接口
你这个问题是显示器不显示，还是显示器只显示命令行界面？？

**Comment by setun-ogas** [comment]
@alanfans 显示器没有输出。你既然说原来的安卓有适配的驱动那我去原来的安卓系统里是不是能找到HDMI的相关驱动？

**Comment by alanfans** [comment]
> @alanfans 显示器没有输出。你既然说原来的安卓有适配的驱动那我去原来的安卓系统里是不是能找到HDMI的相关驱动？

有驱动，安卓系统和armbian配置也不能完全套改，还得适配，有文档啥的专业开发人员都要调试很久。
你有这时间这还不如盒子出闲鱼，买个s905l3a的盒子还快些。

**Comment by setun-ogas** [comment]
@alanfans 生命在于折腾233

**Comment by setun-ogas** [comment]
@alanfans @ophub 暂时没啥办法的话我就先把这个issue关了吧。

**Comment by LondyGhost** [comment]
S905L2可以HDMI输出

**Comment by setun-ogas** [comment]
@LondyGhost 我用的就是S905L2

**Comment by LondyGhost** [comment]
> @LondyGhost 我用的就是S905L2

mgv3000没有s905l2都是l3

**Comment by setun-ogas** [comment]
@LondyGhost 我装的时候选的就是s905l2

**Comment by LondyGhost** [comment]
> @LondyGhost 我装的时候选的就是s905l2

我的意思是，CPU是s905l2才有输出，我手头两个l2能HDMI   几个l3都没法hdmi

**Comment by setun-ogas** [comment]
@LondyGhost 那没事了，我还以为你说的系统型号呢。

**Comment by setun-ogas** [comment]
@LondyGhost 这事我觉得也不是没办法，也许有办法可以把原来安卓系统的HDMI整出来移植到armbian里面呢？虽然约等于做梦。

**Comment by LondyGhost** [comment]
> @LondyGhost 这事我觉得也不是没办法，也许有办法可以把原来安卓系统的HDMI整出来移植到armbian里面呢？虽然约等于做梦。

不太可能

**Comment by alanfans** [comment]
> @LondyGhost 这事我觉得也不是没办法，也许有办法可以把原来安卓系统的HDMI整出来移植到armbian里面呢？虽然约等于做梦。

我看了这篇文章 感觉不是做梦，只是我自己没这个能力
https://blog.csdn.net/github_38345754/article/details/121462292

**Comment by zengfr** [comment]
@setun-ogas 咱俩 需求差不多  强烈需要HDMI输出　主要做低功耗显示终端

**Comment by adoyle-h** [comment]
> 如果显示器只是看终端命令，ssh里面不一样？

@ophub 我现在遇到开机后 ssh 启动不起来的问题。没有显示输出，我连登录账户都没法操作了。

**Comment by setun-ogas** [comment]
@adoyle-h 只能看着光猫里机器是不是上线了然后盲操，没有别的办法

**Comment by adoyle-h** [comment]
我找到一个比较硬核的方法。买一个 ttl 转 usb 的模块，我买的是 CP2102。把机顶盒拆了连接上对应端口。电脑上装好对应驱动。用 putty 或者 mobaxterm 设置好串口和波特率就能看到输出了。
![12291709641848_ pic](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1998490/111faff9-71fb-44c9-9fc1-86e79774cc81)
![12301709641849_ pic](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1998490/61ec03fb-4e8b-4406-b9fd-af9f15f5a89c)

**Comment by setun-ogas** [comment]
@adoyle-h 确实硬核，佩服老哥的动手能力
