### ISSUE TITLE
1000mbit link not working but 100mbit okay

### ISSUE THREAD

**Issue by EgorChadov** [ophub/amlogic-s9xxx-armbian#1246]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: s905x3
 - Model Vontar X3

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.22 & 5.15.105
 - Release: jammy & bullseye

Hello!
I got Vontar X3. Recently I tried to use armbian and got problem with LAN connection. When I connect the box to 1 gbps port I see that box got IP address and in terminal (via hdmi) see message that 1 gbps link is up, but it's not working. I can't connect via ssh. I can't use apt-install (with keyboard and hdmi). If I try to ping the box, then ping is working but with big losses (20-50%). 

But If I change port to 100 mpbs, then everything great. I can connect via ssh, I can use apt-install, I have fully functional Internet connection. 

I don't understand what can cause this problem. I tried a bunch of different cables - nothing. I checked Lan chip - it is RTL8211F and chip support 1 gbps. I tried different kernels and different version of armbian. 

I use meson-sm1-hk1box-vontar-x3.dtb and as far I understand it also support that chip with 1 gbps link.

What can I do to fix that problem? Maybe somebody has ideas how to deal with that?

**Comment by ophub** [comment]
```
cat /boot/uEnv.txt
cat /etc/ophub-release
ls -l /boot/u-boot*
```

**Comment by EgorChadov** [comment]
Thanks for answer!

Here:

`root@armbian:~# cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-hk1box-vontar-x3.dtb
APPEND=root=UUID=33a27505-eee7-46f8-ba0f-55677d18cb39 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905x3'
FDTFILE='meson-sm1-hk1box-vontar-x3.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='6.1.22'
KERNEL_BRANCH='stable'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.conf'
DISK_TYPE='emmc'
MLUBOOT_STATUS='yes'
AMPART_STATUS='no'
PACKAGED_DATE='2023-03-29'
MAINLINE_UBOOT='/usr/lib/u-boot/hk1box-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
root@armbian:~# ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 Apr  1 03:04 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot.emmc
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot.ext
-rwxr-xr-x 1 root root 757153 Apr  1 03:04 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 Apr  1 03:04 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 Apr  1 03:04 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 Apr  1 03:04 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 Apr  1 03:04 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 Apr  1 03:04 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 Apr  1 03:04 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 633376 Apr  1 03:04 /boot/u-boot-r3300l.bin
-rwxr-xr-x 1 root root 609247 Apr  1 03:04 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 Apr  1 03:04 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 Apr  1 03:04 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 Apr  1 03:04 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 Apr  1 03:04 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 Apr  1 03:04 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 Apr  1 03:04 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 Apr  1 03:04 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 Apr  1 03:04 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 Apr  1 03:04 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 Apr  1 03:04 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 Apr  1 03:04 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 Apr  1 03:04 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 Apr  1 03:04 /boot/u-boot-zyxq.bin`

**Comment by EgorChadov** [comment]
Thanks for answer!

Here:

> root@armbian:~# cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-hk1box-vontar-x3.dtb
APPEND=root=UUID=33a27505-eee7-46f8-ba0f-55677d18cb39 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905x3'
FDTFILE='meson-sm1-hk1box-vontar-x3.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='6.1.22'
KERNEL_BRANCH='stable'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.conf'
DISK_TYPE='emmc'
MLUBOOT_STATUS='yes'
AMPART_STATUS='no'
PACKAGED_DATE='2023-03-29'
MAINLINE_UBOOT='/usr/lib/u-boot/hk1box-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
root@armbian:~# ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 Apr  1 03:04 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot.emmc
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot.ext
-rwxr-xr-x 1 root root 757153 Apr  1 03:04 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 Apr  1 03:04 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 Apr  1 03:04 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 Apr  1 03:04 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 Apr  1 03:04 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 Apr  1 03:04 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 Apr  1 03:04 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 633376 Apr  1 03:04 /boot/u-boot-r3300l.bin
-rwxr-xr-x 1 root root 609247 Apr  1 03:04 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 Apr  1 03:04 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 Apr  1 03:04 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 Apr  1 03:04 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 Apr  1 03:04 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 Apr  1 03:04 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 Apr  1 03:04 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 Apr  1 03:04 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 Apr  1 03:04 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 Apr  1 03:04 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 Apr  1 03:04 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 Apr  1 03:04 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 Apr  1 03:04 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 Apr  1 03:04 /boot/u-boot-zyxq.bin

**Comment by EgorChadov** [comment]
Thanks for answer!



```
root@armbian:~# cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-hk1box-vontar-x3.dtb
APPEND=root=UUID=33a27505-eee7-46f8-ba0f-55677d18cb39 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905x3'
FDTFILE='meson-sm1-hk1box-vontar-x3.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='6.1.22'
KERNEL_BRANCH='stable'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.conf'
DISK_TYPE='emmc'
MLUBOOT_STATUS='yes'
AMPART_STATUS='no'
PACKAGED_DATE='2023-03-29'
MAINLINE_UBOOT='/usr/lib/u-boot/hk1box-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
root@armbian:~# ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 Apr  1 03:04 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot.emmc
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot.ext
-rwxr-xr-x 1 root root 757153 Apr  1 03:04 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 Apr  1 03:04 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 Apr  1 03:04 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 Apr  1 03:04 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 Apr  1 03:04 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 Apr  1 03:04 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 Apr  1 03:04 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 633376 Apr  1 03:04 /boot/u-boot-r3300l.bin
-rwxr-xr-x 1 root root 609247 Apr  1 03:04 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 Apr  1 03:04 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 Apr  1 03:04 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 Apr  1 03:04 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 Apr  1 03:04 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 Apr  1 03:04 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 Apr  1 03:04 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 Apr  1 03:04 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 Apr  1 03:04 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 Apr  1 03:04 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 Apr  1 03:04 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 Apr  1 03:04 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 Apr  1 03:04 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 Apr  1 03:04 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 Apr  1 03:04 /boot/u-boot-zyxq.bin
```

**Comment by ophub** [comment]
If the device is gigabit, your above settings are fine.

There are many variants of HK1, including 100M and 1000M. When you use the TV system under the original Android system, does it show Gigabit?

**Comment by HelferP** [comment]
> Maybe somebody has ideas how to deal with that?
Try this DTB file with version 5.15.105
[meson-sm1-hk1box-vontar-x3.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11171265/meson-sm1-hk1box-vontar-x3.zip)

**Comment by EgorChadov** [comment]
> If the device is gigabit, your above settings are fine.
> 
> There are many variants of HK1, including 100M and 1000M. When you use the TV system under the original Android system, does it show Gigabit?

I checked the board, and it has Realtek chip (RTL8211F), so as far I understand it's support 1000m.  But I don't test it on original Android, I installed Armbian right away...



> > Maybe somebody has ideas how to deal with that?
> 
> Try this DTB file with version 5.15.105 [meson-sm1-hk1box-vontar-x3.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11171265/meson-sm1-hk1box-vontar-x3.zip)


Thanks, but this is not helped :(

Here is a photo from the TV screen. Link is up and it's 1Gbps. But ping has a lot of losses, and I can't connect through ssh. Also, when I run 'armbian-config' it's says that no internet connection. 

![185407](https://user-images.githubusercontent.com/30244506/230432782-534c02d0-084a-4619-a6b4-290578f31970.png)
![18-49-15](https://user-images.githubusercontent.com/30244506/230432793-b3c9de57-8392-41c0-8ca8-cfafd1ec92d1.jpg)
![2023-04-06_18-58-03](https://user-images.githubusercontent.com/30244506/230433528-877b4c71-dd0a-4f77-8f52-9f05679b7dcf.png)

**Comment by HelferP** [comment]
Try installing older kernels, like 5.4.240 for example, and check. Before that, do armbian-sync and then armbian-update -k 5.4.240

**Comment by EgorChadov** [comment]
Today I bought a factory new ethernet cable (cat6). Try it and nothing changed. 

Then I tried connecting the box and my laptop directly with this cable (with static ip). And I could connect to the box through ssh. Then I tried to check the speed with iperf3. When the box receives packages - speed is 500mbit. When box send packages - speed around zero. 
![internal_card](https://user-images.githubusercontent.com/30244506/230698800-1088e33e-a0cc-4bc3-8d86-b4540b98f8a4.jpg)

Then I tried connecting box with laptop through usb network card. Box receives packages - 850mbit, box send packages - 350 mbit.
![usb_card](https://user-images.githubusercontent.com/30244506/230698803-8099a9d2-dc35-4385-a808-9ac64393efaf.jpg)


Next step was that:
> Is Wi-Fi connection working? Try installing older kernels, like 5.4.240 for example, and check. Before that, do armbian-sync and then armbian-update -k 5.4.240

After I install 5.4.240 kernel, I can connect to box through ssh. But with iperf3 I got a different situation. When the box receives packages, I got zero speed. When box send packages, I got 900 mbit. 
When I tried to reach the internet through box (for example install anything), it said that I haven't internet connection.
![kernel](https://user-images.githubusercontent.com/30244506/230698802-3d5eb9ad-50bd-45d1-80f4-cb927d25028b.png)


How it can be possible? I'm stuck.

**Comment by ophub** [comment]
If you have an Android system with this box and know how to restore it, you can try installing the mainline u-boot

`armbian-install -m yes`

**Comment by EgorChadov** [comment]
I flashed original Android firmware through UBT today. And finds out that 1000m also does not work. Link is up, on the router devices online and speed is 1000m. But I can't reach the Internet. Is it possible that my box broke in some way?

**Comment by ophub** [comment]
Change the network cable, and try another router to connect to the network port. Maybe it's a problem with the network card of the box, maybe it's a problem with the external network cable.

**Comment by ophub** [comment]
Change the network cable, and try another router to connect to the network port. Maybe it's a problem with the network card of the box, maybe it's a problem with the external network cable.
