### ISSUE TITLE
Armbian 23.02.2升级到Armbian 23.05.0

### ISSUE THREAD

**Issue by yssylq** [ophub/amlogic-s9xxx-armbian#1249]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information | 设备信息

    SOC: s905x3
    H96 Max X3

Armbian Version | 系统版本

    Kernel Version: Armbian_23.02.2 & 5.15.106
    Release: jammy & bullseye

Armbian 23.02.2怎么升级到Armbian 23.05.0

**Comment by ophub** [comment]
apt-get update
apt-get upgrade

**Comment by yssylq** [comment]
> 易于得到更新 易于得到升级

我改了阿里的源，更新没有升级到Armbian23.05.0 ，请问原来的源是什么，我没有备份，能发下吗？谢谢

**Comment by yssylq** [comment]
> apt-get update apt-get upgrade

我改了阿里的源，更新没有升级到Armbian23.05.0 ，请问原来的源是什么，我没有备份，能发下吗？谢谢

**Comment by aliyy2021** [comment]
> apt-get upgrade
 
用这命令更新了，还是23.02

**Comment by yssylq** [comment]
> > apt-get upgrade
> 
> 用这命令更新了，还是23.02

跟你一样，没有变，我也是，更新了还是一样

**Comment by ophub** [comment]
启用 armbian-bsp-cli-odroidn2-current 这个包的更新很危险，他包含u-boot，boot.cmd等，可能会写入错误的u-boot导致无法开机，你做好备份后逐条执行下面的命令

```
sudo apt-mark unhold armbian-bsp-cli-odroidn2-current
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-mark hold armbian-bsp-cli-odroidn2-current
```

**Comment by ysuolmai** [comment]
慎用啊慎用, 刚升级直接启动不了了
