### ISSUE TITLE
s905 ，使用usb3.0 大容量U盘无法引导

### ISSUE THREAD

**Issue by GuanJiayao** [ophub/amlogic-s9xxx-armbian#1251]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095]

**Armbian Version | 系统版本**
 - Kernel Version: [ 6.1.22]
 - Release: [bullseye]

root@armbian:/etc/ssh# cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=odroidn2
BOARD_NAME="Aml-S905"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
BUILD_REPOSITORY_COMMIT=7ab8245
VERSION=23.05.0-trunk--1-PC7446-Vc4b5-H02fb-Be6c1
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=stable
FORCE_BOOTSCRIPT_UPDATE=yes
VENDOR=Armbian
REVISION=23.05.0-trunk
BOOTSCRIPT_FORCE_UPDATE="yes"
BOOTSCRIPT_DST="boot.cmd"
BRANCH=current

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

由于 s905 不支持刷入到EMMC， 所以刷到了U盘中，使用金士顿 32GB USB3.0  刷入后，可以正常引导。
尝试换了一个USB3.2 的 256GB  U盘后，无法引导。

写入U盘时， rufus 提示非标准扇区
![image](https://user-images.githubusercontent.com/13850499/230428754-0a34e828-1782-4b22-9a8e-e00e31d44811.png)

请问有没有办法解决？ 多谢！

**Comment by ophub** [comment]
换2.0小U盘

**Comment by GuanJiayao** [comment]
> 这U盘看起来有点不正经呢？怎么还不让刷写了呢？换个好U盘，比如2.0小U盘

这个是固态U盘，扇区4096 ， 昨天调整了一下扇区大小，U盘从256G变32G， 而且不能用了 ；
查了很多资料，大概意思就是 /boot 分区扇区不能是4096的大小，目测这个U盘是用不了， 多谢！
