### ISSUE TITLE
UNT403A安装armbian进入emmc时出现了错误无法使用[parted]创建分区

### ISSUE THREAD

**Issue by ningxianglong** [ophub/amlogic-s9xxx-armbian#1252]
**Device Information | 设备信息**
 - SOC: [e.g. S095L3A]
 - Model [e.g. UNT403A]

**Armbian Version | 系统版本Armbian_23.05.0_amlogic_s905l3a_jammy_5.15.106**
 - Kernel Version: [e.g. 5.15.106]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
这是我的第一个提问，在安装armbian进入emmc时出现了错误无法使用[parted]创建分区，是否为不支持安装到emmc。请帮助解决问题谢谢

**下面为操作过程**
```
root@armbian:~# armbian-install
[ STEPS ] Start install Armbian to eMMC...
[ STEPS ] Start checking dependencies...
[ INFO ] Dependency check completes, Start installing Armbian.
[ STEPS ] Start initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Using the Ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ INFO ] The device eMMC name: [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------------
ID    SOC        MODEL                          DTB                             
--------------------------------------------------------------------------------------
301   s905x2     X96-Max-4GB,Tx5-Max            meson-g12a-x96-max.dtb          
302   s905x2     X96-Max-2GB,A95X-F2            meson-g12a-x96-max-rmii.dtb     
303   s905x2     MECOOL-KM3-4G                  meson-g12a-sei510.dtb           
304   s905l3a    E900V22C-D                     meson-g12a-s905l3a-e900v22c.dtb 
305   s905l3a    CM311-1a-YST                   meson-g12a-s905l3a-cm311.dtb    
306   s905l3a    M401A,UNT403A,B863AV3.2-M      meson-g12a-s905l3a-m401a.dtb    
0     Other      Customize                      Enter-custom-dtb-name           
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 306
[ INFO ] Input Box ID: [ 306 ]
[ INFO ] FDTFILE: [ meson-g12a-s905l3a-m401a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-e900v22c.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Start selecting file system type...
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] The type of file system: [ ext4 ]
[ STEPS ] Start creating eMMC partition...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 1.7432 s, 2.4 MB/s
[ INFO ] Start create MBR and partittion.
Error: Input/output error during write on /dev/mmcblk2
Error: /dev/mmcblk2: unrecognised disk label
Error: /dev/mmcblk2: unrecognised disk label
[ ERROR ] Failed to create partition using [ parted ].

``` 

**这段为dtb 和 u-boot 对应关系表**
[表格链接](https://7ji.github.io/ampart-web-reporter/?dsnapshot=logo::8388608:1%20recovery::25165824:1%20misc::8388608:1%20dtbo::8388608:1%20cri_data::8388608:2%20param::16777216:2%20boot::16777216:1%20rsv::16777216:1%20metadata::16777216:1%20vbmeta::2097152:1%20tee::33554432:1%20vendor::335544320:1%20odm::134217728:1%20system::1342177280:1%20product::134217728:1%20cache::1073741824:2%20backup::1073741824:2%20data::-1:4&esnapshot=bootloader:0:4194304:0%20reserved:37748736:67108864:0%20cache:113246208:1073741824:2%20env:1195376640:8388608:0%20logo:1212153856:8388608:1%20recovery:1228931072:25165824:1%20misc:1262485504:8388608:1%20dtbo:1279262720:8388608:1%20cri_data:1296039936:8388608:2%20param:1312817152:16777216:2%20boot:1337982976:16777216:1%20rsv:1363148800:16777216:1%20metadata:1388314624:16777216:1%20vbmeta:1413480448:2097152:1%20tee:1423966208:33554432:1%20vendor:1465909248:335544320:1%20odm:1809842176:134217728:1%20system:1952448512:1342177280:1%20product:3303014400:134217728:1%20backup:3445620736:1073741824:2%20data:4527751168:3227516928:4)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.16

**Comment by ningxianglong** [comment]
好的，谢谢
