### ISSUE TITLE
Amlogic S905w2

### ISSUE THREAD

**Issue by redr00t** [ophub/amlogic-s9xxx-armbian#1253]
Hello!!, Is any of the published versions compatible with Amlogic S905w2?

**Comment by ophub** [comment]
not support

**Comment by goldsoft8888** [comment]
https://github.com/devmfc/debian-on-amlogic/releases

**Comment by garret1973** [comment]
> https://github.com/devmfc/debian-on-amlogic/releases

Doesn't solve the problem, this Debian only works from a memory card, Armbian doesn't install either. You can only install your own firmware from the factory and this Debian on the device. You can also take a dump... and that’s it.

**Comment by shirou93** [comment]
This Debian works also from emmc memory.
