### ISSUE TITLE
尝试增加一个新的卡在Rebuild Armbian!这一步 还要改什么才能编译？

### ISSUE THREAD

**Issue by kemp-zz** [ophub/amlogic-s9xxx-armbian#1254]
Standard chat template, no routine, no chat.
配置文件 /common-files/etc/model_database.conf 已增加
配置 build-armbian/armbian-files/different-files    已增加
添加 u-boot 文件                                                      已增加            
build-armbian.yml                                                     已增加   

**Device Information | 设备信息**
 - SOC: [e.g. rk3399]
 - Model []

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.23]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
Run ophub/amlogic-s9xxx-armbian@main
Run cd ${GITHUB_ACTION_PATH}
Current running path: [ /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main ]
Start rebuilding Armbian...
Get armbian file input parameters: [ build/output/images/*.img.gz ]
Copy files: [ build/output/images/*.img.gz ]
'/home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/output/images/Armbian_23.05.0-trunk_6.1.23.img.gz' -> 'build/output/images/Armbian_23.05.0-trunk_6.1.23.img.gz'
About the build/output/images directory: 
total 666424
-rw-r--r-- 1 runner docker 682413924 Apr  7 01:03 Armbian_23.05.0-trunk_6.1.23.img.gz
Check the armbian file format...
Armbian file: 
-rw-r--r-- 1 runner docker 2134900736 Apr  7 01:03 Armbian_23.05.0-trunk_6.1.23.img
Start to rebuild armbian...
[ STEPS ] Welcome to Rebuild Armbian!
[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x86_64 ] 

[ STEPS ] Start Initializing Variables...
[ ERROR ] Missing [ KERNEL_TAGS ] settings, stop building.
Error: Process completed with exit code 1.

**Comment by ophub** [comment]
加的啥，把 model_database.conf 加的代码贴下。

**Comment by kemp-zz** [comment]
> kemp-zz

r306    :hd9901                      :rk3399   :hd9901.dtb                             :trust.bin                    :u-boot.img                          :idbloader.bin                   :stable        :rockchip   :rk3399       :armbianEnv.txt  :hd9901              :yes
杂版rk3399 (广告机拆）配置跟tn3399 一样 ,区别只有2g 用tn3399刷机，有线和无线都可以用 不过有线只能100M 不知道是不否dtb 的问题

**Comment by kemp-zz** [comment]
r306 :hd9901 :rk3399 :hd9901.dtb :trust.bin :u-boot.img :idbloader.bin :stable :rockchip :rk3399 :armbianEnv.txt :hd9901 :yes
杂版rk3399 (广告机拆）配置跟tn3399 一样 ,区别只有2g 用tn3399刷机，有线和无线都可以用 不过有线只能100M 不知道是不否dtb 的问题

**Comment by kemp-zz** [comment]
[ STEPS ] Welcome to Rebuild Armbian!
[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x86_64 ] 

[ STEPS ] Start Initializing Variables...
[ STEPS ] Start searching for Armbian file...
[ INFO ] Armbian rebuild file: [ Armbian_23.05.0-trunk_6.1.23.img ], Version: [ 23.05.0 ]
[ STEPS ] Start downloading dependency files...
[ STEPS ] Start querying the latest kernel version for [ stable ]...
[ INFO ] (1.1) Auto query the latest kernel version of the same series for [ stable - 6.1.2.2 ]
[ INFO ] (1.1) [ stable - 6.1.22 ] is latest kernel (Authenticated user request). 

[ STEPS ] Start downloading the kernel files for [ stable ]...
[ INFO ] (1.1) [ stable - 6.1.22 ] Kernel download from [ https://github.com/kemp-zz/kernel/releases/download/kernel_stable/6.1.22.tar.gz ]
[ ERROR ] [ dtb-allwinner-6.1.22-[kemp-zz].tar.gz ]: sha256sum verification failed.
Error: Process completed with exit code 1.

这次提示
This script requires root privileges; Docker is unavailable trying to use sudo

Build: PREFER_DOCKER=no BUILD_MINIMAL=no COMPRESS_OUTPUTIMAGE=sha CLEAN_LEVEL=make,cache,alldebs,sources BUILD_DESKTOP=no EXPERT=yes ARMBIAN_RELAUNCHED=yes HOST=armbian BRANCH=current BOARD=odroidn2 SET_OWNER_TO_UID=1001 BUILD_ONLY=default RELEASE=jammy KERNEL_CONFIGURE=no build
我自己建一个docker容器吗？

**Comment by ophub** [comment]
你的 https://github.com/kemp-zz/kernel 内核不完整，正常应该70M+，你的才2M

**Comment by kemp-zz** [comment]
能编译成功了 但刷进入不能启动（刷tn3399会自动重启正常开机）而我编译的会重复进刷机模式  是我dtb的问题还是其它要再配置一下？

**Comment by ophub** [comment]
你说tn3399可以用，用这个不正好？你改了一个什么？

**Comment by kemp-zz** [comment]
网卡只能100M
要改那里？

**Comment by baolaimi** [comment]
> 网卡只能100M 要改那里？

有没有改好的HD9901的固件可以刷？？我这HD9901-HD-MB-V2.6的都找不到固件可以刷

**Comment by lishx8888** [comment]
> 网卡只能100M 要改那里？

网卡百兆可能是硬件问题，测试了好几台都是100M，几块4.0的板子都这样，用断头网线测试，灰线不通，就一块3.0的板子是正常1000M网，之前还有一台2.6的板子也只有百兆。。。看有没有大神能查出问题并修改成功，外接一个千兆网卡也将就用了。老家网络100M也能对付。。。。

**Comment by lishx8888** [comment]
> > 网卡只能100M 要改那里？
> 
> 有没有改好的HD9901的固件可以刷？？我这HD9901-HD-MB-V2.6的都找不到固件可以刷

https://github.com/HD9901-Rockchip/docs/releases/download/Debian_12_20250121/debian_bootworm_hd9901_20251221.7z

**Comment by lishx8888** [comment]
> 网卡只能100M 要改那里？

经测试，网口左1接到下方网变上边左3针脚，就有千兆网了
