### ISSUE TITLE
系统默认不带vi命令了吗？

### ISSUE THREAD

**Issue by SSSSoiphon** [ophub/amlogic-s9xxx-armbian#1257]
很久没有刷机了，今天我家云刷入[Armbian_23.05.0_rockchip_l1pro_bullseye_5.15.106_server_2023.04.06.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_04.06.0940/Armbian_23.05.0_rockchip_l1pro_bullseye_5.15.106_server_2023.04.06.img.gz)，发现默认没有vi，想确认一下现在的版本默认都不带vi了吗？

![image](https://user-images.githubusercontent.com/121757154/230618900-9a7e155d-6ea7-4bb2-9fa6-3e56150a0d71.png)

**Comment by ophub** [comment]
```
sudo apt-get update
sudo apt-get install -y vim
```

**Comment by SSSSoiphon** [comment]
OK了。默认不带vim真不习惯。
