### ISSUE TITLE
RTL8192FU驱动编译安装后 无法挂载到内核   求大佬解答疑惑

### ISSUE THREAD

**Issue by KKDAChou** [ophub/amlogic-s9xxx-armbian#1258]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095L3a]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.18-flippy-82+]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
驱动编译安装后 输入挂载命令  提示无法挂载
modprobe: ERROR: could not insert '8192fu': Exec format error
![@KKUQZS53518J4YKM2A6BOE](https://user-images.githubusercontent.com/126685754/230707868-20d70ce5-7b3e-48be-a6cc-158b36d33fcb.png)
查看日志dmesg,提示驱动版本号和内核版本号不一致
[   10.179291] 8192fu: version magic '6.1.18-flippy-82+ SMP mod_unload modversions aarch64' should be '6.1.18-flippy-82+ SMP mod_unload aarch64'
![DIZ%V9WV_`QYMMYC }NPBI](https://user-images.githubusercontent.com/126685754/230707973-add6041b-f28a-4c79-8152-9c3b280a4c7a.png)
已知本机内核版本号
Linux armbian 6.1.18-flippy-82+ #50 SMP Sat Mar 11 22:59:20 CST 2023 aarch64 GNU/Linux
驱动版本号
vermagic:       6.1.18-flippy-82+ SMP mod_unload modversions aarch64

经查看是多了modversions模块控制这个选项，请问一下大佬有办法在不重新编译内核的情况下，解决该问题嘛  十分感谢大佬指点迷津

**Comment by KKDAChou** [comment]
或者是别的原因？

**Comment by KKDAChou** [comment]
已解决 更改编译模块选项就可以了 或者内核中vermagic.h把该选项注释掉！

**Comment by ophub** [comment]
你是怎么调整的编译选项？

**Comment by KKDAChou** [comment]
内核文件/include/Linux中有个vermagic.h文件，我把这里的modversions选项删掉了，然后就可以了，原理不清楚
