### ISSUE TITLE
apt更新导致的引导失败

### ISSUE THREAD

**Issue by Xarth-Mai** [ophub/amlogic-s9xxx-armbian#1261]
我添加了armbian的apt源 在运行apt upgrade后部分组件被更换 armbian-config以及ssh连接界面 设备被识别为香蕉派 同时boot分区被修改 如果重启就会导致引导错误
我的解决方案是取消boot分区的开机挂载防止被修改 在更新内核时手动挂载
执行了armbian-update和armbian-sync后 armbian-config和ssh连接后显示的机型成功恢复为s905
所以请问在s905设备上添加armbian的apt源是不合理的吗？我是否应该删除他？

**Comment by ophub** [comment]
可以更换，只要更换的对就可以，换错分支就乱了。
