### ISSUE TITLE
章鱼星球写入EMMC后插硬盘，EMMC无法启动

### ISSUE THREAD

**Issue by lovl88** [ophub/amlogic-s9xxx-armbian#1264]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095912]
 - Model [e.g. octopus-planet]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.23]
 - Release: [e.g.[bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

章鱼星球写入EMMC后插硬盘，EMMC无法启动   引导处无限重启 拨掉硬盘，马上EMMC就启动啦  ，把硬盘挂载好后，在重启，问题依旧   硬盘是合租ETX4格式   联系QQ71715641

**Comment by ophub** [comment]
你试试换个格式化为空数据的u盘看看能不能启动

**Comment by lovl88** [comment]
好的，我发现有好几个盒子都有这样的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 上午10:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] 章鱼星球写入EMMC后插硬盘，EMMC无法启动 (Issue #1264)





 
你试试换个格式化为空数据的u盘看看能不能启动

**Comment by lovl88** [comment]
感觉 是引导优先级的问题，不知道引导要改那个文件

**Comment by lovl88** [comment]
晚上加来试了，插了个FAT32的空U盘，只要插上USB  emmc就启动不了

**Comment by lovl88** [comment]
我是很多盒子遇到这样的问题，你可以加QQ交流下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 中午1:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] 章鱼星球写入EMMC后插硬盘，EMMC无法启动 (Issue #1264)





 
我的黑色章鱼星球盒子刷了bullseye 6.1.23内核的固件也遇到了同样的问题

**Comment by Matrix-Chen** [comment]
目前是这样解决的，usb不插任何设备，等系统从emmc启动过程中再插入外接硬盘，fstab也能自动挂载。

**Comment by ophub** [comment]
传说中NTFS格式的硬盘挂载上是不影响启动的

**Comment by Matrix-Chen** [comment]
外接硬盘使用NTFS格式的确不影响重启，但又出现了关于docker的一个问题。若docker使用了overlay2，并将容器路径改到了外接硬盘，那么NTFS格式的硬盘会导致docker无法正常启动。
