### ISSUE TITLE
无法执行时间同步

### ISSUE THREAD

**Issue by shum-elli** [ophub/amlogic-s9xxx-armbian#1265]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905lb]
 - Model [r3300l]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100-ophub]
 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

选择时区更新时间失败，上游路由器为软路由，使用ntpdate 192.168.1.1命令可以正常获取时间然后死机
使用date -s命令设置时间，不加sudo无法执行，加了sudo也是直接死机，无法ping通，没有插hdmi看，大概也是死机
不知道为何，时间貌似之前应该更新过，现在时间一直在4.8，导致无法正常更新软件包等

**Comment by ophub** [comment]
你一sudo就死机，重装吧，权限问题。不要把U盘插入安卓系统。

**Comment by shum-elli** [comment]
> 你一sudo就死机，重装吧，权限问题。不要把U盘插入安卓系统。

这我倒是不清楚之前有没有 但是貌似之前是正常的，这个系统已经刷了半个月了，已经写入emmc了，也和u盘有关吗
