### ISSUE TITLE
CM311-1 CH版本，目前HDMI无显示，网络可用，可写入EMMC

### ISSUE THREAD

**Issue by peagsus** [ophub/amlogic-s9xxx-armbian#1268]
Device Information | 设备信息
SOC: 魔百盒
Model: CM311-1 CH版本

Armbian Version | 系统版本
Armbian_23.05.0_amlogic_s905l3b_jammy_5.15.106_server_2023.04.06.img

Describe the bug | 问题描述
CPU型号为S905-L3(B)    安卓刷机包选用湖北CM311-1s-CH-S905L3B线刷包，盒子助手选U盘启动，启动后无HDMI输出，但是根据IP可以远程SSH 
使用M302A的DTB可以正常安装的EMMC，但是HDMI无输出，安装RDP和桌面无法启动，无法远程

**Comment by peagsus** [comment]
905 L2		不启动
905X2		不启动
905 L3		黑屏	可以开机     可以联网
905 L3B		黑屏	可以开机     可以联网
905D		不开机
905 L3A	不开机
905LB		不开机
继续测试中

**Comment by peagsus** [comment]
905X3-B	不开机

**Comment by ophub** [comment]
s905L3B 黑屏 可以开机 可以联网

用这个即可，魔百和很多都不能hdmi

**Comment by peagsus** [comment]
> s905L3B 黑屏 可以开机 可以联网
> 
> 用这个即可，魔百和很多都不能hdmi。发一下盒子正反两面的照片，主板照片有的话也发一个

![1](https://user-images.githubusercontent.com/130391749/231653595-5fc2ddaf-20bf-4eea-9b4c-993c6a9e9dc8.jpg)
![2](https://user-images.githubusercontent.com/130391749/231653601-98506d47-882d-49f7-8389-8dc3c13ae37a.jpg)
![3](https://user-images.githubusercontent.com/130391749/231653604-dfc2c38e-449c-4ea3-9d5e-310858974a0e.jpg)
![4](https://user-images.githubusercontent.com/130391749/231653609-d46b8deb-b9c7-4d3e-a7c5-ae0c9fb778db.jpg)


老大你看下，前几天研究怎么提取DTB没搞成，不过找到了这个盒子使用的DTB文件
gxlx2_p291_2g

这个包不支持HDMI的安装桌面启动不了，安装RDP也无法远程，不知道为啥

**Comment by ophub** [comment]
这个盒子适合服务器版。不能使用HDMI。但是这和安装桌面就无法启动无关。你是怎么安装的桌面？

**Comment by peagsus** [comment]
> 这个盒子适合服务器版。不能使用HDMI。但是这和安装桌面就无法启动无关。你是怎么安装的桌面？

armbian-software 里面安装那个桌面安装后成功了，重启后安装rdp远程链接后无桌面
armbian-confige   里面查看桌面是没启动的，点启动桌面一直启动不了

之前弄玩客云倒是也遇到过 后来换个包就好了，我也想这个问题，按说这个桌面跟hdmi应该没关系才对

是不是我用server的包的问题 老大

**Comment by ophub** [comment]
你说的不启动，是armbian系统无法启动，还是说桌面没有启动远程？

**Comment by peagsus** [comment]
> 你说的不启动，是armbian系统无法启动，还是说桌面没有启动远程？

桌面无法启动
![image](https://user-images.githubusercontent.com/130391749/231721965-221ffbdd-3761-408e-8bd0-e8f5b609a261.png)
这个是玩客云的，CM311的包这里选择启动一直启动不了

**Comment by peagsus** [comment]
> 我就是用的server包，armbian-software安装的桌面。桌面可以正常使用。 你想用桌面可以换个n1等有hdmi输出的，魔百和大部分没有hdmi. 这是一个新的设备，我随后把他加到S905-L3B列表里。

需要我提供什么给您吗？

**Comment by ophub** [comment]
jammy和bulleye都试试安装桌面，两个不同的系列，看看哪个的桌面可以远程。

**Comment by peagsus** [comment]
好的，老大，我晚上试一下

**Comment by ophub** [comment]
你是要用远程桌面管理什么呢？
KVM具有远程桌面类似的功能
PVE管理用浏览器管理。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/armbian_software.md

https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md

**Comment by peagsus** [comment]
> 你是要用远程桌面管理什么吗？ KVM具备远程桌面类的功能 PVE管理使用浏览器管理。
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/armbian_software.md
> 
> https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md

对的，我要在上面安装一个firefox的浏览器，偶尔要上去操作一些东西，KVM和PVE的话可能不太一样如果能RDP就完美了，现在用的玩客云，但是性能不好，并且如果不限制CPU频率就会频繁死机 所以才开始找盒子研究的

**Comment by peagsus** [comment]
> 你是要用远程桌面管理什么吗？ KVM装备远程桌面类的功能 PVE管理使用浏览器管理。
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/armbian_software.md
> 
> https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md

谢谢老大，我先试试您说的 jammy和bulleye 这两个我都试试看看能不能成功

**Comment by peagsus** [comment]
> jammy和bulleye都试试安装桌面，两个不同的系列，看看哪个的桌面可以远程。

/usr/bin/startxfce4: Starting X server


X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux armbian 5.15.106-ophub #1 SMP PREEMPT Wed Apr 5 07:08:52 EDT 2023 aarch64
Kernel command line: root=UUID=e9eb2013-e4c0-4ba0-8f7b-d65ed6d1f980 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 mac=5a:14:43:0a:e0:d3
Build Date: 23 March 2023  10:25:56AM
xorg-server 2:1.20.11-1+deb11u6 (https://www.debian.org/support) 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Thu Apr 13 22:46:39 2023
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) no screens found(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.


xinit: giving up
xinit: unable to connect to X server: Connection refused
xinit: server error


他好像是提示我没有屏幕。

**Comment by peagsus** [comment]
提示的是没有 /dev/fb0

**Comment by peagsus** [comment]
6.1.23  U盘启动正常有网络，写入EMMC后无网络，应该还是DTB没有选对
目前情况桌面不启动应该是显卡驱动问题，提示找不到设备/dev/fb0

**Comment by ophub** [comment]
写入看u-boot，你先在U盘中，把别的改u-boot.ext能正常U盘启动，再写入emmc

**Comment by peagsus** [comment]
> 写入看u-boot，你先在U盘中，把别的改u-boot.ext能正常U盘启动，再写入emmc

好的，我一会试试

**Comment by peagsus** [comment]
使用armbian-software安装桌面可以正常rdp进入了，不过自带的这个桌面比较卡，我手动安装lxde和xfce成功后都进不去，不知道为啥

**Comment by printelife123** [comment]
> 

兄弟，我也是这款，一直以为是U盘启动不了。。。 没有任何的HDMI输出

**Comment by printelife123** [comment]
请问O大，可以让LED指示灯在网络正常的时候亮绿灯吗。

**Comment by shanlanCoding** [comment]
能发下你的刷机包地址吗？我一开始刷入你同名的：`CM311-1s-CH-S905L3B-5621DS无线-2+8-当贝纯净桌面线刷固件包.img`，但是到开机界面进度条走一半就重启。好不容进了一次桌面，结果又开始重启。重启后有两种屏幕。1.华为鸿蒙TV。2.华为智慧屏，切底部有进度条。

**Comment by peagsus** [comment]
> 能发下你的刷机包地址吗？我一开始刷入你同名的：`CM311-1s-CH-S905L3B-5621DS无线-2+8-当贝纯净桌面线刷固件包.img`，但是到开机界面进度条走一半就重启。好不容进了一次桌面，结果又开始重启。重启后有两种屏幕。1.华为鸿蒙TV。2.华为智慧屏，切底部有进度条。

https://www.123pan.com/s/qaZUVv-fQWph.html提取码:Kkg4
这两个我目前是可以用的，你可以试试

**Comment by shanlanCoding** [comment]
> > 能发下你的刷机包地址吗？我一开始刷入你同名的：`CM311-1s-CH-S905L3B-5621DS无线-2+8-当贝纯净桌面线刷固件包.img`，但是到开机界面进度条走一半就重启。好不容进了一次桌面，结果又开始重启。重启后有两种屏幕。1.华为鸿蒙TV。2.华为智慧屏，切底部有进度条。
> 
> [https://www.123pan.com/s/qaZUVv-fQWph.html提取码:Kkg4](https://www.123pan.com/s/qaZUVv-fQWph.html%E6%8F%90%E5%8F%96%E7%A0%81:Kkg4) 这两个我目前是可以用的，你可以试试

请问刷入的时候是否勾选flash和bootloader？

**Comment by shanlanCoding** [comment]
请教下楼主，我现在开心盒子 U盘启动后黑屏，能看见U盘读写灯闪烁一会儿就停了，是不是也代表着已经SSH启动了。

但是我则呢么输入命令安装呢？SSH安装阶段应该没有联网吧。

我的盒子型号是：湖北移动魔百盒 CM311-1S CH

**Comment by ophub** [comment]
盒子通电1分钟就启动好了，去盒子接入的路由器里看ip，设备名称armbian，ssh访问这个ip，端口22

**Comment by shanlanCoding** [comment]
> > 
> 
> 兄弟，我也是这款，一直以为是U盘启动不了。。。 没有任何的HDMI输出

看看楼主的回复。解决我的问题了。HDMI不显示，虽然黑屏，但是实际上开机后已经联网了，去路由器里看IP。

**Comment by sea158** [comment]
> > 能发下你的刷机包地址吗？我一开始刷入你同名的：`CM311-1s-CH-S905L3B-5621DS无线-2+8-当贝纯净桌面线刷固件包.img`，但是到开机界面进度条走一半就重启。好不容进了一次桌面，结果又开始重启。重启后有两种屏幕。1.华为鸿蒙TV。2.华为智慧屏，切底部有进度条。
> 
> [https://www.123pan.com/s/qaZUVv-fQWph.html提取码:Kkg4](https://www.123pan.com/s/qaZUVv-fQWph.html%E6%8F%90%E5%8F%96%E7%A0%81:Kkg4) 这两个我目前是可以用的，你可以试试

可以给我发一下你的刷机包地址吗，之前的过期了

**Comment by jionecc** [comment]
从u盘启动就是黑屏,路由器后台也没有ip 咋回事啊

**Comment by Han-GK** [comment]
CM311-1S ZG
CPU: S905L3B
WIFI:UWE5621DS
WIFI无法正常使用
刷的版本是Armbian_24.11.0_amlogic_s905l3b_noble_6.1.109_server_2024.09.10
有大佬指点一下吗
