### ISSUE TITLE
编译出的kernel很小，

### ISSUE THREAD

**Issue by prioner1** [ophub/amlogic-s9xxx-armbian#1269]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

/usr/local/toolchain/arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu-ld.bfd: drivers/net/wireless/realtek/rtl88x2cs/core/crypto/aes-internal-enc.o: in function `aes_encrypt':
aes-internal-enc.c:(.text+0x6c): multiple definition of `aes_encrypt'; lib/crypto/aes.o:aes.c:(.text+0x750): first defined here
make[1]: *** [scripts/Makefile.vmlinux_o:61: vmlinux.o] Error 1
make: *** [Makefile:1236: vmlinux_o] Error 2
[ STEPS ] Install modules...
cp: cannot stat 'modules.builtin': No such file or directory
make: *** [Makefile:1577: __modinst_pre] Error 1
[ STEPS ] Install headers...
find: ‘Module.symvers’: No such file or directory
[ SUCCESS ] The headers is installed successfully.
[ STEPS ] Create chroot...
[ INFO ] Armbian PLATFORM: [ amlogic ]
cp: cannot stat '/home/runner/work/_actions/prioner1/amlogic-s9xxx-armbian/main/compile-kernel/kernel/linux-6.1.y/System.map': No such file or directory
cp: cannot stat '/home/runner/work/_actions/prioner1/amlogic-s9xxx-armbian/main/compile-kernel/kernel/linux-6.1.y/arch/arm64/boot/Image': No such file or directory
cp: cannot stat '/home/runner/work/_actions/prioner1/amlogic-s9xxx-armbian/main/compile-kernel/output/chroot/root/boot/vmlinuz-6.1.23-ophub': No such file or directory
[ INFO ] Enter the chroot armbian system...
[ INFO ] Current system: [ aarch64 ]
[ INFO ] Current path: [ / ]
[ INFO ] Compile the kernel version: [ 6.1.23-ophub ]
[ STEPS ] Generate uInitrd file...
update-initramfs: Generating /boot/initrd.img-6.1.23-ophub
[ SUCCESS ] The initrd.img and uInitrd file is Successfully generated.
[ INFO ] File situation in the /boot directory after update: 
-rwxr-xr-x 1 root root   235377 Apr 10 12:28 config-6.1.23-ophub
-rwxr-xr-x 1 root root 13123268 Apr 10 12:30 initrd.img-6.1.23-ophub
-rwxr-xr-x 1 root root 13123332 Apr 10 12:30 uInitrd-6.1.23-ophub
[ INFO ] Copy the generated files from [ /home/runner/work/_actions/prioner1/amlogic-s9xxx-armbian/main/compile-kernel/output/chroot/root/boot ]
[ STEPS ] Packing the [ 6.1.23-ophub ] dtbs packages...

能否出一个带6.01.23 8822CS的内核。。。

**Comment by ophub** [comment]
你这一堆错误，没编译成功。
8822cs在有驱动的内核里已经带了，但是能不能用看机器。

**Comment by prioner1** [comment]
> 你这一堆错误，没编译成功。 8822cs在有驱动的内核里已经带了，但是能不能用看机器。

谢谢大佬，能不能用是不是看 armbian-config里面 有没有wifi选项。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.73

**Comment by prioner1** [comment]
> 谢谢，识别不了，有推荐“芯片”的usb无线网卡嘛~谢谢
