### ISSUE TITLE
在线升级版本出错

### ISSUE THREAD

**Issue by aliyy2021** [ophub/amlogic-s9xxx-armbian#1270]
![image](https://user-images.githubusercontent.com/77948441/231035894-81d8b1f8-9a73-45e0-b0c0-b9a79cc6d2d9.png)

**Comment by ophub** [comment]
```
armbian-sync
armbian-update
```
很早的版本？先更新下脚本。

**Comment by aliyy2021** [comment]
> ```
> armbian-sync
> armbian-update
> ```
> 
> 很早的版本？先更新下脚本。



> ```
> armbian-sync
> armbian-update
> ```
> 
> 很早的版本？先更新下脚本。

谢大佬，按你指点的方法可以了

**Comment by zanjie1999** [comment]
因为大佬把https://github.com/ophub/kernel 这个仓里的pub目录给删了，armbian-sync和armbian-update都废了

**Comment by ophub** [comment]
```
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync


chmod +x /usr/sbin/armbian-sync
armbian-sync
armbian-update
```

**Comment by zanjie1999** [comment]
> ```
> wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync
> 
> 
> chmod +x /usr/sbin/armbian-sync
> armbian-sync
> armbian-update
> ```

试了，正常了
