### ISSUE TITLE
R3300L使用s905l应该使用哪一个镜像？

### ISSUE THREAD

**Issue by CartmanChen167** [ophub/amlogic-s9xxx-armbian#1272]
我使用的R3300l经过拆机后发现使用的是905l而非905lb，目前有很多不同版本的r3300l。
看到其他人有使用905x的镜像，请问一下应该使用哪一个？

**Comment by ophub** [comment]
其他人测试可用，你就试试。这个不严格，相近通用

**Comment by JersonWu** [comment]
R3300L的安装镜像发布才几周时间吧，以前都是用905x的镜像。看说明似乎特别做了调整，但目前使用没有明显差异，传感器显示的cpu温度仍然是错误的（显示仅为3°），另外fw_printenv，fw_setenv命令使用仍不正常

**Comment by ophub** [comment]
```
sudo apt-get update
sudo apt-get install lm-sensors
sensors
```

安装温度软件包看看，结果截图发一下，包括你bannner上的3度

**Comment by JersonWu** [comment]
Banner
![屏幕截图 2023-04-14 215440](https://user-images.githubusercontent.com/96780778/232067301-fa7b7cca-ee9d-42d4-adf6-a7f2a80b9bb5.jpg)
安装lm-sensors之后结果一样（但使用Armbian5.44版本正常，3.14内核）
![屏幕截图 2023-04-14 220042](https://user-images.githubusercontent.com/96780778/232067593-52c43b0c-5d16-45d0-bb60-b231b4e822e5.jpg)
使用tf卡启动后有几个错误提示，但使用正常
![屏幕截图 2023-04-14 220252](https://user-images.githubusercontent.com/96780778/232067803-5ff628c1-50e4-4c8f-830d-44ab808278dd.jpg)

**Comment by JersonWu** [comment]
启动是发生的错误可能与我禁用了某些系统服务和驱动有关：禁用了无线网卡驱动，卸载了nfs服务，卸载了openssh-server服务

**Comment by JersonWu** [comment]
补充：tf卡使用仍然存在问题。安装avahi, cups, hplip软件时发生写入错误，然后所有命令失效。
![屏幕截图 2023-04-14 222422](https://user-images.githubusercontent.com/96780778/232072406-d52157a9-3eec-4fec-91f2-fbbb12338b75.jpg)

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=4197390550584854066 skey=@crypt_32f190ed_41631f1ccfb71b4f8f9afa49a3c730d9 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/96780778/232073679-755a35e0-550a-4cf1-b552-81a09b5403bf.jpg)

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=1023177342407425322 skey=@crypt_32f190ed_41631f1ccfb71b4f8f9afa49a3c730d9 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/96780778/232073799-f2e9053e-6fcf-439d-8f50-b5dd68f5e1c5.jpg)

![_cgi-bin_mmwebwx-bin_webwxgetmsgimg__ MsgID=539645101840773047 skey=@crypt_32f190ed_41631f1ccfb71b4f8f9afa49a3c730d9 mmweb_appid=wx_webfilehelper](https://user-images.githubusercontent.com/96780778/232074229-75bc5e3c-fbf8-47a3-b3f6-d3ae04f77487.jpg)

**Comment by CartmanChen167** [comment]
使用Armbian_23.05.0_amlogic_s905lb-r3300l_jammy_6.1.24_server_2023.04.14.img.gz可以正常启动，Armbian_23.05.0_amlogic_s905x_jammy_6.1.24_server_2023.04.14.img.gz在删除extlinux-config的bak后也可以启动，但是无法使用无线网络。

**Comment by CartmanChen167** [comment]
Armbian_23.05.0_amlogic_s905lb-r3300l_bullseye_5.15.107_server_2023.04.14.img.gz使用这个镜像后可以正常使用了，但是接显示器配置的时候非常折磨。会时不时刷新rtl871x的状态。但是ssh进去是正常的，没有刷屏。

**Comment by ophub** [comment]
这是无线报错，禁用无线

**Comment by IOsetting** [comment]
> 这是无线报错，禁用无线

这是debug输出吧, 看看能不能把日志级别降低

**Comment by IOsetting** [comment]
Armbian_23.08.0_amlogic_s905lb-r3300l_jammy_5.15.127_server_2023.08.19.img.gz 
这个版本的 sensors 命令显示的温度正常了
```bash
root@armbian:~# sensors
scpi_sensors-isa-0000
Adapter: ISA adapter
aml_thermal:  +53.0°C  
```
但是 fw_printenv 还是不能用
```bash
root@armbian:~# fw_printenv 
Configuration file wrong or corrupted
```

**Comment by bird202301** [comment]
汇报下我的R3300L小红盒运行状况：
 Armbian OS 24.2.0 Bullseye with Linux 5.15.145-ophub
安装lm-sensors之后，温度依然不正常 2°
主机hdmi输出依然会时不时刷新rtl871x的状态。但是ssh进去是正常的，没有刷屏。

**Comment by LiteCoder** [comment]
> Armbian_23.08.0_amlogic_s905lb-r3300l_jammy_5.15.127_server_2023.08.19.img.gz 这个版本的 sensors 命令显示的温度正常了
> 
> ```shell
> root@armbian:~# sensors
> scpi_sensors-isa-0000
> Adapter: ISA adapter
> aml_thermal:  +53.0°C  
> ```
> 
> 但是 fw_printenv 还是不能用
> 
> ```shell
> root@armbian:~# fw_printenv 
> Configuration file wrong or corrupted
> ```

你好，能分享一个Armbian_23.08.0_amlogic_s905lb-r3300l_jammy_5.15.127_server_2023.08.19.img.gz固件包吗，换了好多个温度都不正常，目前6.1的内核无线网卡不能用了
