### ISSUE TITLE
E900V22E    s905l3

### ISSUE THREAD

**Issue by Kloping** [ophub/amlogic-s9xxx-armbian#1273]
![)O09M)F)%Z2(PS%5H54%H}7](https://user-images.githubusercontent.com/87743020/231316732-834271d5-6e09-41cc-8a63-b6925920ef61.jpg)

型号是 移动定制 创维E900V22E

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_04.11.0456/Armbian_23.05.0_amlogic_s905l3_bullseye_5.15.106_server_2023.04.11.img.gz

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_04.11.0456/Armbian_23.05.0_amlogic_s905l3b_bullseye_5.15.106_server_2023.04.11.img.gz

都尝试过 路由器未出现相关设备 且无HDMI信号

**Comment by CrBoom** [comment]
试一下接个usb网卡?我这21e 905l3b hdmi和内置网卡都不工作

**Comment by lovl88** [comment]
12.6 启动引导文件的选择
目前已知的设备中，只有 T95(s905x) / T95Z-Plus(s912) / BesTV-R3300L(s905l-b) 等少数设备需要使用 /bootfs/extlinux/extlinux.conf 文件，已经在系统里默认添加了。其他设备如果需要，可以将系统写入 USB 后，双击打开 boot 分区，将系统自带的 /boot/extlinux/extlinux.conf.bak 文件名称中的 .bak 删除即可使用。当写入 eMMC 时 armbian-install 会自动检查，如果存在 extlinux.conf 文件，会自动创建。

其他设备只需要 /boot/uEnv.txt 即可启动，不要修改 extlinux.conf.bak 文件。

**Comment by ophub** [comment]
修改 /boot/uEnv.txt 里dtb的名字为：meson-gxl-s905l3b-e900v22e.dtb
重启

**Comment by Kloping** [comment]
> 使用s905l3b的镜像文件，刷入U盘后，重新在电脑上拔插一下，修改 /boot/uEnv.txt 里dtb的名字为：meson-gxl-s905l3b-e900v22e.dtb

仍然无效果/路由器中也为出现设备

**Comment by MikeYao0513** [comment]
> ![)O09M)F)%Z2(PS%5H54%H}7](https://user-images.githubusercontent.com/87743020/231316732-834271d5-6e09-41cc-8a63-b6925920ef61.jpg)
> 
> 型号是 移动定制 创维E900V22E
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_04.11.0456/Armbian_23.05.0_amlogic_s905l3_bullseye_5.15.106_server_2023.04.11.img.gz
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_04.11.0456/Armbian_23.05.0_amlogic_s905l3b_bullseye_5.15.106_server_2023.04.11.img.gz
> 
> 都尝试过 路由器未出现相关设备 且无HDMI信号

我的CM311-1也是这个问题（不是1Y，另一个帖子中有求教解决方法，但也是无解），目前看来是没有这个晶片的DTB文件，刚才翻到一篇文章：https://t.cj.sina.com.cn/articles/view/1823348853/6cae187502000wbee
本人的基础知识不行，所以请会的人是否能提炼一个S905L3的DTB文件，看看是否会有改善。
（希望DTB文件可共享，谢谢！）
