### ISSUE TITLE
魔百和m411a(s905L3)u盘启动刷机黑屏

### ISSUE THREAD

**Issue by worm128** [ophub/amlogic-s9xxx-armbian#1274]
魔百盒M411a测试了s905l3a和s905l3b的包都无法开机引导启动，都是黑屏，跪了,大家有遇到这样的情况吗

**Comment by worm128** [comment]
我的是安卓9.0系统，已root

**Comment by Childlove** [comment]
广东M411A？

**Comment by Childlove** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1218#issue-1640857429

**Comment by worm128** [comment]
怎么查看自己的芯片是哪一款？我用
aida64查的信息也对不上

**Comment by lovl88** [comment]
参考下如下内容吧   我的e900v21E   s905L2   也是这样解决的
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
12.6 启动引导文件的选择
目前已知的设备中，只有 T95(s905x) / T95Z-Plus(s912) / BesTV-R3300L(s905l-b) 等少数设备需要使用 /bootfs/extlinux/extlinux.conf 文件，已经在系统里默认添加了。其他设备如果需要，可以将系统写入 USB 后，双击打开 boot 分区，将系统自带的 /boot/extlinux/extlinux.conf.bak 文件名称中的 .bak 删除即可使用。当写入 eMMC 时 armbian-install 会自动检查，如果存在 extlinux.conf 文件，会自动创建。

其他设备只需要 /boot/uEnv.txt 即可启动，不要修改 extlinux.conf.bak 文件。

**Comment by ophub** [comment]
@lovl88 e900v21E s905L2用的什dtb和u-boot?
cat /boot/extlinux/extlinux.conf
ls -l /boot/u-boot*

**Comment by lovl88** [comment]
就直接下载你的固件，没做其它修改。 启动不了，，把BAK去掉就可以启动了

**Comment by lovl88** [comment]
@ophub    meson-gxl-s905l2-x7-5g.dtb   这个自带的DTB

**Comment by ophub** [comment]
你的盒子是e900v21E(s905L2)?

刷过其他安卓系统没有？如果换过发一下链接。

拍个照片发一个，正面样子、反面能看到型号。如果有主板的也发一个，没有就不用拆了。

**Comment by lovl88** [comment]
@没有涮过安卓还是原版系统， 

![IMG_20230412_185816](https://user-images.githubusercontent.com/130325319/231438960-d783fd88-ec2b-4584-b1f9-374ca645df8b.jpg)
![IMG_20230412_185823](https://user-images.githubusercontent.com/130325319/231438961-05226de5-1524-4c33-92f5-c582fef5ece5.jpg)
![IMG_20230412_190030](https://user-images.githubusercontent.com/130325319/231438982-16977adb-09a4-4e8c-89bb-65747f8197b9.jpg)

**Comment by ophub** [comment]
写入emmc后有线网卡工作正常吧。

**Comment by lovl88** [comment]
这个型号无法写入EMMC

**Comment by lovl88** [comment]
![IMG_20230412_190118](https://user-images.githubusercontent.com/130325319/231442743-3f8abb76-b8e5-40ba-91f2-3eee7380b447.jpg)

**Comment by ophub** [comment]
好的👌我记录一下增加到列表里。

**Comment by worm128** [comment]
Armbian_23.05.0_amlogic_s905l2_bullseye_5.15.106_server_2023.04.12.img.gz
Armbian_23.05.0_amlogic_s905l3a_bullseye_5.15.106_server_2023.04.09.img.gz
Armbian_23.05.0_amlogic_s905l3b_bullseye_5.15.106_server_2023.04.12.img.gz
这些包我都用usb引导试过了，开机启动都是黑屏，我盒子是M411a魔和盒，商家说是s905l的晶晨芯片，我也不知道怎样查到底cpu是哪一款，一个一个包刷，aida64查的信息也对不上
![图片](https://user-images.githubusercontent.com/29749635/231447178-ea1b9423-e809-461f-b6ab-65e5fed52104.png)
我是这样u盘启动的
![图片](https://user-images.githubusercontent.com/29749635/231447401-16ec75eb-919f-4780-a2cb-e573cf99731d.png)
以下我电视盒的设备参数
![图片](https://user-images.githubusercontent.com/29749635/231447794-ece7c2d7-4b29-49c0-832a-52d0a3913a89.png)
![图片](https://user-images.githubusercontent.com/29749635/231447825-27cb8b7d-e67c-43a1-903f-f3adf66cdf75.png)
![图片](https://user-images.githubusercontent.com/29749635/231447851-371df829-576c-42ba-a5ff-6005be7c5b56.png)
![图片](https://user-images.githubusercontent.com/29749635/231447875-bfe1b1b8-652e-4f3f-b285-072bf41bdb78.png)

**Comment by worm128** [comment]
最终试了各种包和dtb，都是无法引导安装代码界面o(╥﹏╥)o

**Comment by lovl88** [comment]
加我QQ沟通71715641



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月12日(星期三) 晚上7:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] 魔百和E900v21E(s905L2)使用方法 (Issue #1274)





 
最终试了各种包和dtb，都是无法引导安装代码界面o(╥﹏╥)o

**Comment by worm128** [comment]
附个m411a盒子的图
![图片](https://user-images.githubusercontent.com/29749635/231450569-0232babe-0c31-4424-8b8b-66ca0ff2f3c9.png)
![图片](https://user-images.githubusercontent.com/29749635/231450609-17f2e48e-d6a7-4172-a254-084bb6b65ab4.png)

**Comment by worm128** [comment]
> 你的盒子是e900v21E(s905L2)?
> 
> 刷过其他安卓系统没有？如果换过发一下链接。
> 
> 拍个照片发一个，正面样子、反面能看到型号。如果有主板的也发一个，没有就不用拆了。
> 
> 你开个新贴子发一下你的这个盒子的测试结果吧，介绍一下型号，图片，选择，怎么用等等，这个目前没有记录。

我的盒子是M411a(S905L3)

**Comment by ryanInf** [comment]
使用meson-g12a-s905l3a-m401a.dtb可以启动armbian，但无法识别wifi

**Comment by t9080** [comment]
请问楼主m411a用那个安卓包？

**Comment by t9080** [comment]
黑屏你可以看下路由有没分配到ip ？如果有直接登陆就好

**Comment by t9080** [comment]
> > 你的盒子是e900v21E(s905L2)?
> 
> > 
> 
> > 刷过其他安卓系统没有？如果换过发一下链接。
> 
> > 
> 
> > 拍个照片发一个，正面样子、反面能看到型号。如果有主板的也发一个，没有就不用拆了。
> 
> > 
> 
> > 你开个新贴子发一下你的这个盒子的测试结果吧，介绍一下型号，图片，选择，怎么用等等，这个目前没有记录。
> 
> 
> 
> 我的盒子是M411a(S905L3)

我的也是m411a，你解决了吗？

**Comment by simonchan6688** [comment]
同样此型号，目前无法U盘启动

> 附个m411a盒子的图 ![图片](https://user-images.githubusercontent.com/29749635/231450569-0232babe-0c31-4424-8b8b-66ca0ff2f3c9.png) ![图片](https://user-images.githubusercontent.com/29749635/231450609-17f2e48e-d6a7-4172-a254-084bb6b65ab4.png)
