### ISSUE TITLE
运行armbian-update显示Failed to get the version on the server

### ISSUE THREAD

**Issue by LiuXueStyle** [ophub/amlogic-s9xxx-armbian#1275]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905L3A
 - Model: CM311-1A-YST

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.15/5.15.94
 - Release: jammy

**Describe the bug | 问题描述**
armbian-update显示Failed to get the version on the server
起初怀疑自己的问题，分别用5.15.94和6.1.15两个版本的盒子尝试了一下，均不能升级；尝试了一下依然不行；说明文档中更改仓库地址和现在系统提供的脚本已经对不上了，挂任何参数都不好用

**Comment by LiuXueStyle** [comment]
看了一下armbian-update脚本文件，应该是https://github.com/ophub/kernel/tree/main/pub这个仓库地址失效了

**Comment by ophub** [comment]
armbian-sync
armbian-update

先同步下最新的脚步，再更新即可。

**Comment by shawze** [comment]
运行armbian-sync报错时，可手动编辑更新“ /usr/sbin/armbian-update  ”脚本，可解决。

**Comment by Evansy** [comment]
> 运行armbian-sync报错时，可手动编辑更新“ /usr/sbin/armbian-update ”脚本，可解决。

请问修改了哪些内容呀
