### ISSUE TITLE
请求加入支持 九联UNT400G1(S905L3) 电视盒子

### ISSUE THREAD

**Issue by signigelchan** [ophub/amlogic-s9xxx-armbian#1277]
**Device Information | 设备信息**
 - SOC: [S905L3]
 - Model [九联UNT400G1]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.xxx | 6.1.xxx]
 - Release: [jammy | bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
自测试，尝试写入 "s905l3 | CM311-1, HG680-LC, M401A" 对应的镜像写入U盘，发现无法引导，联通开机画面会显示，但无限重启 (**过几秒黑屏然后重新显示联通画面**)。

设备详情如下：

![1](https://user-images.githubusercontent.com/20301894/231449837-0c9bf053-62c5-447a-afac-45000b15baad.jpeg)
![2](https://user-images.githubusercontent.com/20301894/231449850-41a9f3c9-5f9b-483f-a9be-e9c251bb4e5c.jpeg)
![3](https://user-images.githubusercontent.com/20301894/231449854-9bc0a0e6-866f-4874-81b8-bb40df53b3e2.jpeg)
![4](https://user-images.githubusercontent.com/20301894/231449859-ea85457c-238a-4aa5-8d60-136a81cd5711.jpeg)
![5](https://user-images.githubusercontent.com/20301894/231449868-c2b12190-3646-46e1-b808-2260282553b6.jpeg)
![6](https://user-images.githubusercontent.com/20301894/231450026-845225b8-a2bb-4287-b4ee-425922d90513.png)

**Comment by LondyGhost** [comment]
S905L3  去找HG680-LC当贝移植包，那个大概率可以用

**Comment by signigelchan** [comment]
> S905L3 去找HG680-LC当贝移植包，那个大概率可以用

---

`https://github.com/ophub/kernel/releases/tag/tools` 下面有两个相同芯片的机型：

> android_tv_hg680-lc_s905l3.tar.xz
> android_tv_m401a_s905l3.tar.xz

使用 `Amlogic_USB_Burning_Tool` 刷入提示 `[0x32030201]Uboot/Get result/DiskInitial error`，自测无法刷入。

**Comment by ophub** [comment]
我根据你的测试结果添加了`121`选项，和s905l3的区别是多了extlinux.conf

**Comment by ophub** [comment]
你使用的多少频率？

**Comment by signigelchan** [comment]
> 你使用的多少频率？ 把你修改好的dtb使用压缩格式上传到这个帖子里吧，以后的用户直接下载使用。

---

`50000000` 和 `52000000` 都可以。

原来是 `200000000`，降为 `100000000` 仍找不到 `mmcblk`。

之后反编译参考 `meson-gxl-s905l3b-m302a.dtb` 的 `mmc@74000` 中的 `max-frequency`，目前用的是 `52000000` 。

```
mmc@74000 {
	compatible = "amlogic,meson-gx-mmc\0amlogic,meson-gxbb-mmc";
	reg = <0x00 0x74000 0x00 0x800>;
	interrupts = <0x00 0xda 0x04>;
	status = "okay";
	clocks = <0x03 0x60 0x03 0x7d 0x03 0x04>;
	clock-names = "core\0clkin0\0clkin1";
	resets = <0x11 0x2e>;
	pinctrl-0 = <0x29 0x2a>;
	pinctrl-1 = <0x2b>;
	pinctrl-names = "default\0clk-gate";
	bus-width = <0x08>;
	cap-mmc-highspeed;
	max-frequency = <0x3197500>;    ## 修改为 0x3197500 (52000000)， 原值 0xbebc200 (200000000)
	non-removable;
	disable-wp;
	mmc-ddr-1_8v;
	mmc-hs200-1_8v;
	mmc-pwrseq = <0x2c>;
	vmmc-supply = <0x2d>;
	vqmmc-supply = <0x25>;
	phandle = <0x9d>;
};
```


已修改的 `dtb` 工作频率：`52000000`
[dtb-decompile.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11221740/dtb-decompile.zip)

**Comment by ophub** [comment]
好的，谢谢分享

**Comment by signigelchan** [comment]
附：镜像写入 `EMMC` 过程：
---
![1](https://user-images.githubusercontent.com/20301894/231778901-2cfdfee9-b6dd-4b80-89a6-44414536af86.png)
![2](https://user-images.githubusercontent.com/20301894/231778913-ffd1699a-1230-4d37-bfb9-1701c68944a5.png)
![3](https://user-images.githubusercontent.com/20301894/231778918-e323836c-8101-4d46-93e3-51ea129ef8f3.png)
![4](https://user-images.githubusercontent.com/20301894/231778921-ffd2258c-7b47-4093-905a-a263aac420cd.png)
![5](https://user-images.githubusercontent.com/20301894/231778930-40637669-4eb9-4e02-a2d9-c69c54b293c3.png)
![6](https://user-images.githubusercontent.com/20301894/231778933-4f5d50d3-5a9c-4d66-b377-cd160d3355c1.png)
![7](https://user-images.githubusercontent.com/20301894/231778942-2d039333-ee2c-496d-9b77-d5435f073f95.png)
![8](https://user-images.githubusercontent.com/20301894/231778949-b13b6afd-b11a-416c-9ade-40d3a468a5fb.png)

**Comment by ophub** [comment]
好的，恭喜你

**Comment by yangchaohong** [comment]
请问大家用的是什么刷机包啊，烽火的我刷不进

**Comment by yangchaohong** [comment]
我刷的官改包，结果不会开adb

**Comment by LondyGhost** [comment]
> 请问大家用的是什么刷机包啊，烽火的我刷不进

都是网上找的刷机包

**Comment by ophub** [comment]
@signigelchan 
你这个盒子刷过其他安卓系统吗？如果使用了其他安卓系统，分享一下你的下载链接。

**Comment by signigelchan** [comment]
> @signigelchan 你这个盒子刷过其他安卓系统吗？如果使用了其他安卓系统，分享一下你的下载链接。

---

没有刷过，在搞 `armbian` 之前就是原厂安卓系统，在网上也找到了对应芯片版本 [江苏联通UNT400G1-S905L3-5621DS线刷包](https://pan.quark.cn/s/2161cd68f410) 的安卓固件 (应该是原厂系统，刷不进去，无法确认)，但是我这边自测无法正常刷入 (拆机短接也不行)。

> 使用 [tools](https://github.com/ophub/kernel/releases/tag/tools) 里面提供的相同芯片的也不行，同样报错。

![firmware_flash](https://user-images.githubusercontent.com/20301894/232207589-0028afa7-d663-4218-a99e-1052db8420a2.png)

![flash_err](https://user-images.githubusercontent.com/20301894/232207625-a41f2b35-def2-477f-9ec4-d93751205069.png)

**Comment by signigelchan** [comment]
> 我刷的官改包，结果不会开adb

---

是我这款盒子么，`UNT400G1-S905L3+5621DS`， 官改包是安卓系统哪个版本的，可以提供一下刷机包下载链接么？

**Comment by signigelchan** [comment]
附：此款电视盒子 **安装三方 APK** 及 **开启 ADB 调试** 方法：

---

## 安装三方 APK

![1](https://user-images.githubusercontent.com/20301894/232210840-39807846-a493-4209-8177-c5ed6f0cba89.png)
![2](https://user-images.githubusercontent.com/20301894/232210842-d557caaf-23d9-469f-815b-101542ab19d0.png)
![3](https://user-images.githubusercontent.com/20301894/232210844-bee6dbaf-2a35-48fc-87a2-05a9791bffe4.png)
![4](https://user-images.githubusercontent.com/20301894/232210845-fc6eed10-745b-4e14-a323-a3adb6f01b3e.png)
![5](https://user-images.githubusercontent.com/20301894/232210847-6eb966cb-315f-425c-9608-d2fe9c21327c.png)
![6](https://user-images.githubusercontent.com/20301894/232210848-dc3709f0-a453-4c51-8222-e97f944f8990.png)
![7](https://user-images.githubusercontent.com/20301894/232210851-933cedb8-60f1-4d86-b921-123db6341d13.png)

---

## 开启 ADB 调试

![8](https://user-images.githubusercontent.com/20301894/232211037-05c3824b-91b4-4e0a-a40f-6624f6255dc7.png)
![9](https://user-images.githubusercontent.com/20301894/232211047-57172034-578b-4ab6-89ba-4bb74bae3670.png)
![10](https://user-images.githubusercontent.com/20301894/232211053-84bb50e1-37ed-4541-a41a-ba7fb74112f2.png)
![11](https://user-images.githubusercontent.com/20301894/232211062-97f5e13e-2c8c-4016-aa4c-8bf864e08cfe.png)
![12](https://user-images.githubusercontent.com/20301894/232211068-ba033e3e-4e42-44ec-b737-a5633d42f180.png)
![13](https://user-images.githubusercontent.com/20301894/232211073-e76daf14-acf1-43ea-b082-afbb570ac09c.png)
![14](https://user-images.githubusercontent.com/20301894/232211078-b52a4abd-6e2d-4823-b7ab-659fa731fef1.png)

**Comment by yangchaohong** [comment]
我搞错了，我的刷机包是可以直接在设置里面开adb的，是刷6.1的内核的固件对吗，还有就是l3、l3b的dtb逆向工程什么时候能够支持HDMI？

**Comment by yangchaohong** [comment]
[dtb dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11241672/dtb.dts.zip)

**Comment by yangchaohong** [comment]
这就是原机的dtb希望有大佬能够适配HDMI输出

**Comment by signigelchan** [comment]
> 我搞错了，我的刷机包是可以直接在设置里面开adb的，是刷6.1的内核的固件对吗，还有就是l3、l3b的dtb逆向工程什么时候能够支持HDMI？

---

> 是刷6.1的内核的固件对吗

详见上方 [该盒子使用不同镜像简单总结](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1277#issuecomment-1505347194)


> 还有就是l3、l3b的dtb逆向工程什么时候能够支持HDMI？

我也是小白，提取安卓原生 `dtb` 以适配 `armbian` 的相关问题，我有开另外一个 `Issue` ，详见 #1285 ，目前没怎么研究，暂时无解。

**Comment by KongGuoguang** [comment]
怎样才能从U盘或者TF卡引导启动呢

**Comment by yangchaohong** [comment]
![image](https://user-images.githubusercontent.com/45483831/235350978-a4eca91a-58d9-42ca-ada6-1e7b867be234.png)
无法启动！kernel卡死
6.1内核
Armbian_23.05.0_amlogic_s905l3-unt400g1_bullseye_6.1.24_server_2023.04.14.img.gz

**Comment by yangchaohong** [comment]
还有就是这货ttl rx被阉割了，调试不方便

**Comment by KongGuoguang** [comment]
遇到一个奇怪的问题，系统已经写入emmc，USB口外接储存硬盘，重启之后进不去系统，必须拔掉USB口的硬盘才能进去，反复验证了多次都是这样

**Comment by xiaodiao216** [comment]
> > 参考下如下内容吧 我的e900v21E s905L2 也是这样解决的 https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md 12.6 启动引导文件的选择 目前已知的设备中，只有 T95(s905x) / T95Z-Plus(s912) / BesTV-R3300L(s905l-b) 等少数设备需要使用 /bootfs/extlinux/extlinux.conf 文件，已经在系统里默认添加了。其他设备如果需要，可以将系统写入 USB 后，双击打开 boot 分区，将系统自带的 /boot/extlinux/extlinux.conf.bak 文件名称中的 .bak 删除即可使用。当写入 eMMC 时 armbian-install 会自动检查，如果存在 extlinux.conf 文件，会自动创建。
> 
> ### 使用或忽略 `extlinux.conf` 测试结果如下：
> > Armbian_23.05.0_amlogic_s905l3_bullseye_5.15.106_server_2023.04.12.img.gz
> 
> * `extlinux.conf.bak` (忽略)
>   插电开机长时间停留联通画面，过一段时间黑屏，等待几分钟后查看路由器DHCP，没有分配到IP
> * `extlinux.conf` (使用)
>   同 "忽略" 结果一致
> 
> > Armbian_23.05.0_amlogic_s905l3_bullseye_6.1.23_server_2023.04.12.img.gz
> 
> * `extlinux.conf.bak` (忽略)
>   插电开机停留联通画面一段时间后黑屏，然后重新显示联通画面，一段时间后再次黑屏，如此反复 (无限重启)
> * `extlinux.conf` (使用)
>   插电开机停留联通画面一段时间后花屏闪过变黑屏，等待几分钟后查看路由器DHCP，分配到了IP，**SSH成功进入系统**
> 
> ### 该盒子使用不同镜像简单总结
> #### 使用 `5.15.x` 镜像
> * 去掉 `/boot/extlinux/extlinux.conf.bak` 文件的 `.bak` 后缀
> * 复制一份 `/boot/u-boot-p212.bin` 文件，重命名为 `/boot/u-boot.ext` 即可
> 
> #### 使用 `6.1.x` 镜像
> * 只需去掉 `/boot/extlinux/extlinux.conf.bak` 文件的 `.bak` 后缀即可
> 
> 另：需要反编译修改 `dtb` 来 **调整 EMMC 的工作频率**，否则会找不到 `EMMC` 闪存，自测支持的工作频率为 `50000000` 和 `52000000` 均可。

请问e900v21e的盒子，hdmi无输出怎么解决的？

**Comment by hailong6713** [comment]
部分九联UNT400G1(S905L3) 电视盒子的无线网卡是mt7661rsn，请问怎样加入MT7661无线网卡驱动?
dmesg输出的错误信息
root@armbian:~# dmesg | grep -i mt76
[   13.726256] mt7663s mmc0:0001:1: Failed to get patch semaphore
[   13.726476] mt7663s mmc0:0001:1: mediatek/mt7663pr2h.bin not found, switching to mediatek/mt7663pr2h_rebb.bin
[   13.808288] mt7663s mmc0:0001:1: Failed to get patch semaphore
[   13.808545] mt7663s mmc0:0001:1: failed to load mediatek/mt7663pr2h_rebb.bin

**Comment by hailong6713** [comment]
![armbian](https://github.com/ophub/amlogic-s9xxx-armbian/assets/156279555/d728d69b-7c1c-47fe-b80f-7b8de82d68fe)

**Comment by sjn33** [comment]
已修改的 dtb 工作频率：52000000。但TF卡不能正常识别使用，有办法吗

**Comment by hsycc** [comment]
> 部分九联UNT400G1(S905L3) 电视盒子的无线网卡是mt7661rsn，请问怎样加入MT7661无线网卡驱动? dmesg输出的错误信息 root@armbian:~# dmesg | grep -i mt76 [ 13.726256] mt7663s mmc0:0001:1: Failed to get patch semaphore [ 13.726476] mt7663s mmc0:0001:1: mediatek/mt7663pr2h.bin not found, switching to mediatek/mt7663pr2h_rebb.bin [ 13.808288] mt7663s mmc0:0001:1: Failed to get patch semaphore [ 13.808545] mt7663s mmc0:0001:1: failed to load mediatek/mt7663pr2h_rebb.bin

同样的问题， 请教下后面有解决吗

**Comment by hsycc** [comment]
> 部分九联UNT400G1(S905L3) 电视盒子的无线网卡是mt7661rsn，请问怎样加入MT7661无线网卡驱动? dmesg输出的错误信息 root@armbian:~# dmesg | grep -i mt76 [ 13.726256] mt7663s mmc0:0001:1: Failed to get patch semaphore [ 13.726476] mt7663s mmc0:0001:1: mediatek/mt7663pr2h.bin not found, switching to mediatek/mt7663pr2h_rebb.bin [ 13.808288] mt7663s mmc0:0001:1: Failed to get patch semaphore [ 13.808545] mt7663s mmc0:0001:1: failed to load mediatek/mt7663pr2h_rebb.bin

@hailong6713 同样的问题，请教下后面有解决吗？
