### ISSUE TITLE
Mecool BB2 (S912, 2GB RAM, 16GM) not working with meson-gxm-beelink-gt1.dtb

### ISSUE THREAD

**Issue by ilanzel** [ophub/amlogic-s9xxx-armbian#128]
I was able to run focal 5.15.25 on Mecool BB2 Pro (S912, 3GB, 16GB), using the meson-gxm-beelink-gt1.dtb file.
However, it does not run on Mecool BB2.
Any clues?
Thanks

**Comment by ophub** [comment]
try other

[meson-gxm-q200.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-dtb/meson-gxm-q200.dtb)
[meson-gxm-q201.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-dtb/meson-gxm-q201.dtb)

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/amlogic-dtb

**Comment by ilanzel** [comment]
Thanks again for your support.
Tried both .dtb files, no luck. Ethernet not recognized.
