### ISSUE TITLE
麻烦老大添加下中车的RK3399开发板

### ISSUE THREAD

**Issue by GD2021** [ophub/amlogic-s9xxx-armbian#1280]
设备名称：
CRRC中国中车 RK3399开发板
版型：
![image](https://user-images.githubusercontent.com/81171294/231515746-fc253a04-bea7-46f2-882e-2d67b2b574ae.png)
配置如下：
2+16g
usb3.0 X2
usb2.0 x1
tf卡槽 x1
HDMI x1
3.5耳机口 x1
千兆网口 x1
带WiFi
带蓝牙
1000M网口

dtb链接：
https://musetransfer.com/s/r3tu9egcd 
我从固件中提取了dtb，如果还需要别的我再去提取

**Comment by ophub** [comment]
还要u-boot文件。你是从什么固件里复制的文件？这个固件发一下

**Comment by GD2021** [comment]
https://musetransfer.com/s/oa7uwgmnf 
《Armbian_crrc_ubuntu20.04》

**Comment by ophub** [comment]
rk3399-orangepi用这个

**Comment by GD2021** [comment]
gpt 回复

这个错误提示是因为 OpenSSH 服务启动失败导致的。可能的原因包括：

1. 端口被占用：OpenSSH 默认监听 22 端口，如果该端口已被占用，OpenSSH 就无法启动。您可以尝试修改配置文件中的端口号，如 /etc/ssh/sshd_config。

2. 配置文件错误：如果配置文件中存在语法错误或不兼容的配置项，OpenSSH 也可能无法启动。您可以检查配置文件中是否存在错误，或者尝试还原默认配置文件。

3. 依赖项缺失：OpenSSH 启动需要依赖一些库文件或者其他服务，如果这些依赖项缺失或者未正确安装，OpenSSH 也会启动失败。

针对这个问题，您可以尝试以下解决方案：

1. 确认端口是否被占用：可以使用 lsof 命令查看当前系统中哪些进程正在使用 22 端口。

2. 检查 /etc/ssh/sshd_config 文件是否存在语法错误或不兼容的配置项。

3. 检查系统中是否安装了必要的依赖项，如 openssl 和 libpam。可以使用 apt-get 或者 yum 安装缺失的依赖项。

4. 尝试重新安装 OpenSSH，可以使用 apt-get 或者 yum 安装最新版本的 OpenSSH。

5. 如果以上方法都无法解决问题，您可以尝试重启系统，或者重装 armbian 操作系统。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/80fda01655240f2865f656c3019b1e05cb20bafc/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L32-L37

这个ssh问题几个月前出现过，我这样加了个重启，再最后一步时重启这个服务。

**Comment by GD2021** [comment]
收到 好的

**Comment by GD2021** [comment]
◆固件反馈
◆固件包：[Armbian_23.05.0_rockchip_crrc_jammy_6.1.23_server_2023.04.13.img.gz]

◆更改为：
![image](https://user-images.githubusercontent.com/81171294/231796806-36b9ea43-b367-4342-816b-85a6bd446484.png)

◆结论效果：无法启动

◆固件包：[rmbian_23.05.0_rockchip_crrc_bullseye_6.1.23_server_2023.04.13.img.gz]

◆结论效果：可以正常启动，启动时有三处报错

![image](https://user-images.githubusercontent.com/81171294/231797463-c4b0a351-5100-448e-a877-2a06047d5331.png)
![image](https://user-images.githubusercontent.com/81171294/231797507-abe493ba-edb9-49ab-a7a6-8237213c70b4.png)

**Comment by GD2021** [comment]
https://toi.teracloud.jp/share/11c148fb24fe2441
这是原版的安卓固件链接，麻烦各位商界的名流、业界的精英提取一下dts

**Comment by ophub** [comment]
这个云不让下载。你前面用的发ubuntu那个云可以直接下载。
那个ubuntu在哪下载的呢？他网站里有源码没？

**Comment by GD2021** [comment]
您试试这个
https://g.itemz.cn/rW9bku

**Comment by GD2021** [comment]
原地址：
https://g.itemz.cn/mh0HPV

**Comment by gogogo668** [comment]
补充安卓反编dts
[crrc安卓.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11237980/crrc.zip)

**Comment by planxx** [comment]
@GD2021 我有块板子测试了包里所有的dtb文件，只有中车这个是最完美的，除了无线，其他都正常，麻烦问问大佬，您这个板子的无线芯片是啥？我的板子的是ap6356s

**Comment by planxx** [comment]
@ophub 大佬，请求适配AMY_A2_V0.3，测试下来发现，Armbian_25.11.0_rockchip_firefly-rk3399_bullseye_6.1.115_server_2025.10.24.img 这个固件可以启动，然后替换成rk3399-crrc.dtb这个dtb文件后，近乎完美，除了无线(ap6356s)无法驱动，其他一切正常，也没有任何报错，但是奇怪的是，如果我用Armbian_25.11.0_rockchip_crrc_bullseye_6.1.157_server_2025.10.24.img 这个直接刷写，就不能正常启动，板子直接进入maskroom，怀疑firefly的uboot能启动我的板子，而crrc的uboot无法启动我的板子。

**Comment by planxx** [comment]
<img width="2700" height="1830" alt="Image" src="https://github.com/user-attachments/assets/882ad2e8-ac89-4c17-a744-3130a1f87d30" />

@ophub 大佬，适配一下吧，还有个很有意思的现象是，用rk3399-crrc.dtb这个DTB，如果改armbianEnv.txt文件中的dtb文件名称到rk3399-crrc.dtb，则USB不工作，但是如果不动armbianEnv.txt文件，把rk3399-crrc.dtb文件更名为rk3399-firefly.dtb，然后上传替换，则USB工作正常。

**Comment by planxx** [comment]
最新更新：下载了Armbian_25.11.0_rockchip_firefly-rk3399_bullseye_6.1.115_server_2025.10.24.img和Armbian_25.11.0_rockchip_crrc_bullseye_6.1.158_server_2025.11.02.img，然后真合成了firefly的uboot+crrc的boot+Rootfs的缝合怪，直接刷机，正常使用，近乎完美了。
