### ISSUE TITLE
按照教程提取Android dtb文件，设备上 /dev/block/bootloader 不存在

### ISSUE THREAD

**Issue by altmangood** [ophub/amlogic-s9xxx-armbian#1281]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [RK3399]
 - OS[Android 7.1]

**Describe the bug | 问题描述**
我在按教程 https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md#12111-%E6%8F%90%E5%8F%96-bootloader-%E5%92%8C-dtb-%E6%96%87%E4%BB%B6 提取DTB

![image](https://user-images.githubusercontent.com/128894448/231611925-0de1a668-b08c-4b45-895e-c1462fcdda6b.png)

请问教程里面是Android几的版本，有 /dev/block/bootloader

**Comment by 13584452567** [comment]
教程内的设备为aml系列芯片。rk的安卓提取dtb要解包boot文件

**Comment by altmangood** [comment]
@13584452567 你好，感谢回复。

请问你说的boot文件是需要通过RKDevTool导出对应的分区产生的 xxx.img 文件吗？

**Comment by 13584452567** [comment]
> @13584452567 你好，感谢回复。
> 
> 请问你说的boot文件是需要通过RKDevTool导出对应的分区产生的 xxx.img 文件吗？

是的。导出boot分区

**Comment by Childlove** [comment]
error：devices offline报错

**Comment by worm128** [comment]
导出dtb命令：
cat /dev/dtb >/data/local/mybox.dtb

我的可以导出dtb，盒子M411a

**Comment by alanfans** [comment]
> > @13584452567 你好，感谢回复。
> > 请问你说的boot文件是需要通过RKDevTool导出对应的分区产生的 xxx.img 文件吗？
> 
> 是的。导出boot分区

大佬，全志h6 导出boot后，解包并没有发现在dtb, 有其他方法吗？

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/231914875-f8c96f2c-c32f-409c-984d-c95536d7f434.png)
![image](https://user-images.githubusercontent.com/8871739/231914902-585c680a-c3e6-4c31-9771-0c3e14001e5a.png)
 
人工智障的感觉

**Comment by 13584452567** [comment]
> > > @13584452567 你好，感谢回复。
> > > 请问你说的boot文件是需要通过RKDevTool导出对应的分区产生的 xxx.img 文件吗？
> > 
> > 是的。导出boot分区
> 
> 大佬，全志h6 导出boot后，解包并没有发现在dtb, 有其他方法吗？
> ![image](https://user-images.githubusercontent.com/8871739/231911517-727bc36e-0080-4a9e-8614-918952232147.png)
> 

关于全志h6安卓下的dtb，我也不清楚具体在哪里。我是通过dd备份，然后用16进制检索D00DFEED的dtb文件头来获取dtb文件的。一般只需要dd256MB就可以覆盖到dtb了。

**Comment by 13584452567** [comment]
> ![image](https://user-images.githubusercontent.com/8871739/231914875-f8c96f2c-c32f-409c-984d-c95536d7f434.png)
> ![image](https://user-images.githubusercontent.com/8871739/231914902-585c680a-c3e6-4c31-9771-0c3e14001e5a.png)
>  
> 人工智障的感觉

目前的各类模型还不能很好的处理这些技术性问题。大概率一本正经的胡说八道

**Comment by alanfans** [comment]
> > > > @13584452567 你好，感谢回复。
> > > > 请问你说的boot文件是需要通过RKDevTool导出对应的分区产生的 xxx.img 文件吗？
> > > 
> > > 
> > > 是的。导出boot分区
> > 
> > 
> > 大佬，全志h6 导出boot后，解包并没有发现在dtb, 有其他方法吗？
> > ![image](https://user-images.githubusercontent.com/8871739/231911517-727bc36e-0080-4a9e-8614-918952232147.png)
> 
> 关于全志h6安卓下的dtb，我也不清楚具体在哪里。我是通过dd备份，然后用16进制检索D00DFEED的dtb文件头来获取dtb文件的。一般只需要dd256MB就可以覆盖到dtb了
get

**Comment by altmangood** [comment]
@13584452567 一般只需要dd256MB就可以覆盖到dtb了
————————

这个原理是前256MB的磁盘空间，大概率包括了uboot（或者叫boot分区，这个不太懂区别)。然后里面包括了设备dtb文件 是吧？

**Comment by 13584452567** [comment]
> @13584452567 一般只需要dd256MB就可以覆盖到dtb了
> ————————
> 
> 这个原理是前256MB的磁盘空间，大概率包括了uboot（或者叫boot分区，这个不太懂区别)。然后里面包括了设备dtb文件 是吧？

是的。

uboot是一个bootloader。而boot分区是安卓的东西。安卓8以前dtb是被和kernel一起打包成image.gz-dtb，然后与其他的组件一起封进boot。安卓8之后dtb就被独立出来为单独的一个分区。

**Comment by altmangood** [comment]
@13584452567 请问按上面你索引到dtb头位置之后，怎么确定尾巴位置。也是有专门的字符串可以作为结尾吗？

**Comment by 13584452567** [comment]
> @13584452567 请问按上面你索引到dtb头位置之后，怎么确定尾巴位置。也是有专门的字符串可以作为结尾吗？

一般来说，dtb文件尾部与其他数据会有相当数量的0。

如果从头往后超出1mb都没看到大量0，就说明可能没有空0，需要自己分析dtb头的文件大小和内存偏移来猜测结尾的位置。

**Comment by ophub** [comment]
@13584452567 
你看看这个帖子，你试试他的源码能编译下去吗
https://github.com/ophub/amlogic-s9xxx-openwrt/issues/415

**Comment by 13584452567** [comment]
> @13584452567 
> 你看看这个帖子，你试试他的源码能编译下去吗
> https://github.com/ophub/amlogic-s9xxx-openwrt/issues/415

不行，各种报错。可能是我的环境有些问题？

话说这个内核用的什么啊，为什么还混着安卓在里面……

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/u-boot/rockchip/ipc-r
我刚编译完了，有一处报错按他说的改下过去了。
f大的5.10也是安卓

**Comment by Childlove** [comment]
我的M411A提取的bin是乱码的，应该是被卡了
