### ISSUE TITLE
 HK1BOX 4GB 32GB 100M ONLY 2GB RAM

### ISSUE THREAD

**Issue by rhenku** [ophub/amlogic-s9xxx-armbian#1282]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [HK1BOX 4GB 32GB]

**Armbian Version | 系统版本**
 - Kernel Version: [Linux version 5.15.103-ophub]
 - Release: [bulleye]

**Describe the bug | 问题描述**
I have HK1BOX 4GB 32GB 100M, but only 2GB ram not 4GB RAM, i use FDT, 
- meson-sm1-x96-air.dtb
- meson-sm1-tx3-bz.dtb

everything all work, in android system RAM is 4GB how to get 4GB RAM to this model, please help.. :)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

look at 501

**Comment by rhenku** [comment]
I was use before, but not display blank screen..

**Comment by ophub** [comment]
You are using 100M dtb, of course the network is 100M, you test Gigabit dtb

**Comment by rhenku** [comment]
How get FDT 100M? Can you help me

**Comment by ophub** [comment]
Your box itself is a 100M network card, right?
Your problem is that the memory 4G only shows 2G?

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

look at: 12.12

**Comment by nizarelhaque** [comment]
I have trouble with the LAN not being able to gigabit,please help me

**Comment by nizarelhaque** [comment]
> Standard chat template, no routine, no chat. 标准聊天模板，无套路不聊天。
> 
> **Device Information | 设备信息**
> 
> * SOC: [S095x3]
> * Model [HK1BOX 4GB 32GB]
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version: [Linux version 5.15.103-ophub]
> * Release: [bulleye]
> 
> **Describe the bug | 问题描述** I have HK1BOX 4GB 32GB 100M, but only 2GB ram not 4GB RAM, i use FDT,
> 
> * meson-sm1-x96-air.dtb
> * meson-sm1-tx3-bz.dtb
> 
> everything all work, in android system RAM is 4GB how to get 4GB RAM to this model, please help.. :)

im sorry my brother ,i,ve no problem about this try using fw from helmi in kernel 6.1
