### ISSUE TITLE
咨询本地化打包问题

### ISSUE THREAD

**Issue by vxbmtu94516** [ophub/amlogic-s9xxx-armbian#1283]
请问本地化打包是不是可以用任何设备的任何版本(包括armbian官方已经eos的历史版本)的armbian镜像去重新打包?

**Comment by ophub** [comment]
不一定。
我选择的是2分区的，如果你使用的固件是单一分区的，挂载时会失败，你要改脚本。
另外我对官方的一些进行了修改和限制，不如原镜像里的u-boot禁用，自动分区禁用，广告禁用等，可能在你说的那个任意历史版本里无法匹配到会报错。
我只在jammy，focal，bullseye里测试过，再往前我还不知道什么是armbian，我是从f大的openwrt里了解到的armbian
