### ISSUE TITLE
/etc/fstab 自动挂载设置后启动失败

### ISSUE THREAD

**Issue by LondyGhost** [ophub/amlogic-s9xxx-armbian#1284]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905L3]
 - Model [HG680-LC]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100]
 - Release: [ jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

在fstab文件设置 UUID 自动华挂载移动硬盘，系统不能正常启动。因为设备没有HDMI输出，手头也没TTL焊接工具，不知道什么原因造成的。

硬盘盒有外接供电，应该不会供电问题。

文移动硬盘文件系统为NTFS

百度相关fstab自动挂载问题，没有相对应的例子，均教人删除挂载命令再恢复系统启动。

**Comment by ophub** [comment]
`blkid` 看看设备UUID
`UUID=06020c01-371a-4034-a529-976dcb0f7d11   /mnt/hdd    ntfs    defaults    0 0`
UUID和挂载路径改成你的

**Comment by LondyGhost** [comment]
> `blkid` 看看NTFS硬盘的UUID
> 
> ```
> vi /etc/fstab
> UUID=06020c01-371a-4034-a529-976dcb0f7d11   /mnt/hdd    ntfs    defaults    0 0
> ```
> 
> UUID和挂载路径改成你的

好的  我再试试
