### ISSUE TITLE
请问大佬，什么时候能支持一下mstar芯片的

### ISSUE THREAD

**Issue by Sailiy** [ophub/amlogic-s9xxx-armbian#1286]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. ms09385]
 - Model [e.g. 创维e900v21c盒子]

**Describe the bug | 问题描述**
     我这运营商给的盒子是e900v21c的，今年的新盒子，刚开始折腾，网上关于这个盒子的信息还挺多的还挺高兴的，感觉有玩头。
     后来发现按照网上的方法都不行，拆开盒子发现用的mstar的芯片，好多其他地方的运营商都是晨星s905芯片方案。折腾3天无果。
     对这个盒子已经失去信心了，如果大佬愿意折腾，我可以免费送给大佬，希望大佬能搞一搞mstar的盒子

**Comment by zhansihua** [comment]
刷  ip202H，680h的 包试试 ，网上有资料 ，开串口 进 mboot ，
