### ISSUE TITLE
Add Support for RK3318

### ISSUE THREAD

**Issue by webepg** [ophub/amlogic-s9xxx-armbian#1288]
Hi,

could you add support for RK3318 devices?

**Comment by webepg** [comment]
Never mind. I found [this](https://forum.armbian.com/topic/26978-csc-armbian-for-rk3318rk3328-tv-box-boards/) which works. The only important this is that you have to use a micro SD card. USB Drives do not work with this. Maybe you could link this tutorial for all the people who are searching for it

**Comment by osnipezzini** [comment]
Open again: Please make official support for RK3318
