### ISSUE TITLE
How to upgrade to newest release

### ISSUE THREAD

**Issue by webepg** [ophub/amlogic-s9xxx-armbian#1289]
Hi,

im on Armbian 22.11.0-trunk Bullseye with Linux 5.15.107-ophub and I would like to upgrade to the newest bullseye release. How can I do that? When I do armbian-update it only updates the kernel. sudo apt-get update && sudo apt-get dist-upgrade -y doesn't do anything. Do I need to create a new bootable drive and install the system onto eMMC? I would like to keep my settings and my files.

**Comment by ophub** [comment]
armbian-sync
armbian-fix

sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y

**Comment by webepg** [comment]
This is not working every command is successful but nothing gets done. Always 0 Updated Packages

**Comment by webepg** [comment]
root@armbian:~# cat /etc/ophub-release
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
FDTFILE='meson-sm1-x96-air-gbit.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT=''
BOOTLOADER_IMG=''
KERNEL_VERSION='5.15.107'
SOC='s905x3'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
PACKAGED_DATE='2022-09-26'
PLATFORM='amlogic'
PLATFORM='amlogic'
KERNEL_TAGS='stable'
GITHUB_CDN=''
KERNEL_REPO='ophub/kernel'
KERNEL_BACKUP='yes'

**Comment by webepg** [comment]
Why are you closing this issue? It's still an issue!

**Comment by webepg** [comment]
Is it possible to boot from usb and upgrade it from there? Without loosing my data?

**Comment by ophub** [comment]
No. I have been using the above method to upgrade to the latest.

**Comment by Unicorn9x** [comment]
> Hi,
> 
> im on Armbian 22.11.0-trunk Bullseye with Linux 5.15.107-ophub and I would like to upgrade to the newest bullseye release. How can I do that? When I do armbian-update it only updates the kernel. sudo apt-get update && sudo apt-get dist-upgrade -y doesn't do anything. Do I need to create a new bootable drive and install the system onto eMMC? I would like to keep my settings and my files.

copy from another support thread

`wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync


chmod +x /usr/sbin/armbian-sync
armbian-sync
armbian-update`

**Comment by fireblade83** [comment]
Hi,

I'm on Armbian 23.08 bookworm, and I would like to upgrade to the latest version.

After run the commands
armbian-update
armbian-sync
armbian-fix
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y

It gives me a message
The following packages have been kept back:
  armbian-bsp-cli-odroidn2-current
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

What I have read here, is if I unlock the file, there would be great changes that the file get corrupted/damage and the system doesn't start.

Is it possible to upgrade to the latest version (24.2.0) without losing data, or do I have to wipe all and do a fresh install?

Thanks
