### ISSUE TITLE
移动魔百盒UNT403A执行armbian-install写入EMMC还是失败

### ISSUE THREAD

**Issue by wangzhongwen** [ophub/amlogic-s9xxx-armbian#1290]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S095l3a
 - Model: UNT403A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.106
 - Release: jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
UNT403A 写入emmc报错

![image](https://user-images.githubusercontent.com/16794348/232242580-9fde0b0c-28d7-4b2c-8a39-f3ff77a92767.png)
![image](https://user-images.githubusercontent.com/16794348/232242585-09bd261b-1f62-4fe3-af05-3b7d368722bd.png)
![image](https://user-images.githubusercontent.com/16794348/232242608-5cead62c-4219-43ff-868e-f2b896904261.png)
以上是远程执行

在盒子上直接执行显示的错误更详细点
![image](https://user-images.githubusercontent.com/16794348/232242905-f9af8e84-8543-473e-9520-20a703429712.png)

**Comment by ophub** [comment]
看文档里有修改说明

**Comment by janko888** [comment]
more /boot/uEnv.txt

more /sys/kernel/debug/mmc2/ios

执行这两个命令看看当前作业系统的情况

**Comment by gdscwh** [comment]
我的改到文档里最低50000000都不行，感觉就是2+16的unt403盒子不行

**Comment by wangzhongwen** [comment]
> 看文档里有修改说明

&sd_emmc_b {
	status = "disabled";
	bus-width = <4>;
	cap-sd-highspeed;
	max-frequency = <50000000>;
};
这里改成50000000没有效果

**Comment by wangzhongwen** [comment]
> 

![image](https://user-images.githubusercontent.com/16794348/232312968-29c0dfe7-a598-4685-8154-9debf3e32771.png)

**Comment by gdscwh** [comment]
按文档说明填16进制的，不是直接填10进制的数据



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月16日 20:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ophub/amlogic-s9xxx-armbian] 移动魔百盒UNT403A执行armbian-install写入EMMC还是失败 (Issue #1290) |

看文档里有修改说明

&sd_emmc_b {
status = "disabled";
bus-width = <4>;
cap-sd-highspeed;
max-frequency = <50000000>;
};
这里改成50000000没有效果

**Comment by janko888** [comment]
你这改了个寂寞啊。。。
刷回原版镜像，修改这个/boot/uEnv.txt文件
把FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb
改成FDT=/dtb/amlogic/meson-g12a-s905l3a-m401a.dtb

插入盒子上电，然后再写入吧。

**Comment by gdscwh** [comment]
这个试过了，不行才用文档里修改的方法，结果还是不行，现在没方法了，等刷回安卓的再试了



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月16日 21:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ophub/amlogic-s9xxx-armbian] 移动魔百盒UNT403A执行armbian-install写入EMMC还是失败 (Issue #1290) |

你这改了个寂寞啊。。。
刷回原版镜像，修改这个/boot/uEnv.txt文件
把FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb
改成FDT=/dtb/amlogic/meson-g12a-s905l3a-m401a.dtb

插入盒子上电，然后再写入吧。

**Comment by wangzhongwen** [comment]
> 你这改了个寂寞啊。。。 刷回原版镜像，修改这个/boot/uEnv.txt文件 把FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb 改成FDT=/dtb/amlogic/meson-g12a-s905l3a-m401a.dtb
> 
> 插入盒子上电，然后再写入吧。
> 
> 参考 #1276

上面截图是我用Rufus重新做的U盘
以前修改过，没效果
![image](https://user-images.githubusercontent.com/16794348/232322965-4a6964fb-2dee-4463-918f-032556da663e.png)

**Comment by janko888** [comment]
我不认为你真的正确按我说的步骤做过了

**Comment by wangzhongwen** [comment]
> 
0x2faf080 就是 50000000
![image](https://user-images.githubusercontent.com/16794348/232325862-b08d7fba-bd02-44b6-8bdf-805d9fa4f1f7.png)

**Comment by wangzhongwen** [comment]
> 

![image](https://user-images.githubusercontent.com/16794348/232326010-d4de9f35-211b-4dba-8c82-5af645d86cec.png)

**Comment by janko888** [comment]
现在写入EMMC看看

**Comment by wangzhongwen** [comment]
> 现在写入EMMC看看

![image](https://user-images.githubusercontent.com/16794348/232326497-2411f98e-d01f-453f-9d8e-c1a517068227.png)

**Comment by janko888** [comment]
现在的确是在10000000频率下操作的了，你分区格式试过用ext4没有？

**Comment by wangzhongwen** [comment]
我试过不止10次了，ext4一样报错

之所以选btrfs,是发现盒子对ext4的存储写久了会有几率出现错误，需要e2fsck以下才能正常

**Comment by wangzhongwen** [comment]
> 我试过不止10次了，ext4一样报错
> 
> 之所以选btrfs,是发现其他盒子对ext4的存储写久了会有几率出现错误，需要e2fsck一下才能正常

**Comment by janko888** [comment]
因为不知道你对系统了解程度，有些人会犯些低级错误，例如编译了“修改”了很多个版本的dtb.但事实上没有在当前作业环境下引用生效，改了等于没改。这里也不清楚你之前测试ext4是在那个环境下，只能建议你在我刚才了解的状态下测试一下再测试这个格式类型

**Comment by wangzhongwen** [comment]
这个是ext4
![image](https://user-images.githubusercontent.com/16794348/232361857-152fdcb2-2361-4754-9181-723bf15eaa6a.png)

**Comment by janko888** [comment]
从作业系统当前的emmc的clock和actual clock值看来，设定值和实际值没有明显背离，这里频率导致的可能性不太大。可能得考虑一下是否原固件的文件格式\分区是否有特殊，或者是否高安板等不太常见的问题的可能性。。

**Comment by wangzhongwen** [comment]
安卓固件刷了论坛里常见的以及 [https://github.com/ophub/kernel/releases/tag/tools](url)里的[android_tv_unt403a_s905l3a.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_unt403a_s905l3a.tar.xz) ,反复尝试十余次都不成功。
怀疑硬件问题，现在刷回安卓当电视盒用
谢谢[janko888](https://github.com/janko888)热心解答。

**Comment by guugg** [comment]
我是`E900V22C` `S905L3AB` ；以前直接`armbian-install -m yes`写入emmc是没有任何问题。 今天在角落重新拿出来忘记密码重刷一遍。 发现死活刷不进emmc，查issues发现最近都有这个问题。 `把频率由 max-frequency = <200000000>; 下调为 max-frequency = <100000000>; 即可解决问题`        以前200000000可以怎么现在不可以了 ？

**Comment by ophub** [comment]
那是他还年轻，现在衰老了，得降低点频率才能跟上节奏。

**Comment by guugg** [comment]
👍

**Comment by wangzhongwen** [comment]
UNT403A当安卓盒子用了一年了，性能总是不足，看油管也不能4K，今天再次尝试刷armbian，终于找到规律了，不仅仅是需要降clock问题，还挑固件版本。
Armbian_25.05.0_amlogic_s905l3a_noble_6.12.19_server_2025.03.15 搞了几遍都不行，Armbian_25.05.0_amlogic_s905l3a_noble_6.6.80_server_2025.03.02 一遍就成功了。

默认信息：
<pre>
root@armbian:~# more /sys/kernel/debug/mmc2/ios
clock:          200000000 Hz
actual clock:   199999997 Hz
vdd:            21 (3.3 ~ 3.4 V)
bus mode:       2 (push-pull)
chip select:    0 (don't care)
power mode:     2 (on)
bus width:      3 (8 bits)
timing spec:    9 (mmc HS200)
signal voltage: 1 (1.80 V)
driver type:    0 (driver type B)
root@armbian:~# more /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb
APPEND=root=UUID=76140f7a-d5d3-4a0f-9da8-3761cbc0fbe7 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_consol
e_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapac
count=1
 </pre>

 安装vim
 <pre>
apt update
apt install -y vim
 </pre>

修改 /boot/uEnv.txt ，把FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb改成FDT=/dtb/amlogic/meson-g12a-s905l3a-m401a.dtb
 <pre>
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-g12a-s905l3a-m401a.dtb
APPEND=root=UUID=76140f7a-d5d3-4a0f-9da8-3761cbc0fbe7 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_consol
e_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapac
count=1
 </pre>

反编译 meson-g12a-s905l3a-m401a.dtb
<pre>
cd /boot/dtb/amlogic/
 
dtc -I dtb -O dts -o meson-g12a-s905l3a-m401a.dts meson-g12a-s905l3a-m401a.dtb
</pre>

vim meson-g12a-s905l3a-m401a.dts
修改 max-frequency = 100000000 为 50000000
即 max-frequency = <0x5f5e100> => max-frequency = <0x2faf080> 
 
重新编译 
<pre>
dtc -I dts -O dtb -o meson-g12a-s905l3a-m401a.dtb meson-g12a-s905l3a-m401a.dts
</pre>

 保存数据并重启
<pre>
sync && reboot
</pre>

再次安装，除了报一个小错误Error: Input/output error during write on /dev/mmcblk2 外，一切正常
<pre>
root@armbian:/boot/dtb/amlogic# 
root@armbian:/boot/dtb/amlogic# reboot
root@armbian:/boot/dtb/amlogic# 
    _             _    _              ___  ___ 
   /_\  _ _ _ __ | |__(_)__ _ _ _    / _ \/ __|
  / _ \| '_| '  \| '_ \ / _` | ' \  | (_) \__ \
 /_/ \_\_| |_|_|_|_.__/_\__,_|_||_|  \___/|___/
                                               
 v25.05.0 for Aml.S905l3a running Armbian Linux 6.6.80-ophub

 Packages:     Ubuntu stable (noble)
 Updates:      Kernel upgrade enabled and 30 packages available for upgrade 
 IP addresses: (LAN) IPv4: 192.168.110.203  (WAN) 113.66.***.***

 Performance:  

 Load:         36%              Up time:       0 min
 Memory usage: 8% of 1.89G  
 CPU temp:     51°C              Usage of /:   30% of 6.6G   
storage/:      31% of 510M   
 RX today:     248 MiB        
 Commands: 

 Configuration : armbian-config
 Upgrade       : armbian-upgrade
 Monitoring    : htop

Last login: Fri Mar 28 13:54:29 2025 from 192.168.110.252
root@armbian:~# more /sys/kernel/debug/mmc2/ios
clock:          50000000 Hz
actual clock:   50000000 Hz
vdd:            21 (3.3 ~ 3.4 V)
bus mode:       2 (push-pull)
chip select:    0 (don't care)
power mode:     2 (on)
bus width:      3 (8 bits)
timing spec:    9 (mmc HS200)
signal voltage: 1 (1.80 V)
driver type:    0 (driver type B)
root@armbian:~# 
root@armbian:~# 
root@armbian:~# armbian-install 
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Use ampart tool: [ yes ]
[ INFO ] Show all devices: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
-----------------------------------------------------------------------------------------------------
ID    SOC        MODEL                                         DTB                                               
-----------------------------------------------------------------------------------------------------
301   s905x2     X96-Max-4GB,Tx5-Max                           meson-g12a-x96-max.dtb                            
302   s905x2     X96-Max-2GB,A95X-F2                           meson-g12a-x96-max-rmii.dtb                       
303   s905x2     MECOOL-KM3-4G                                 meson-g12a-sei510.dtb                             
304   s905l3a    ♥,E900V22C-D,CM311-1a-CH,IP112H,B863AV3.1   meson-g12a-s905l3a-e900v22c.dtb                   
305   s905l3a    ♥,CM311-1a-YST                              meson-g12a-s905l3a-cm311.dtb                      
306   s905l3a    M401A,UNT403A,B863AV3.2-M                     meson-g12a-s905l3a-m401a.dtb                      
0     Other      Customize                                     Enter-custom-dtb-name                             
-----------------------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 306
[ INFO ] Input Box ID: [ 306 ]
[ INFO ] Model Name: [ M401A,UNT403A,B863AV3.2-M ]
[ INFO ] FDTFILE: [ meson-g12a-s905l3a-m401a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-e900v22c.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root? 
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 1.66257 s, 2.5 MB/s
[ STEPS ] Successfully partitioned internal eMMC with amaprt.
[ INFO ] Start create MBR and partittion.
Error: Input/output error during write on /dev/mmcblk2
[ INFO ] 03. Write the mybox bootloader: [ /usr/lib/u-boot/mybox-bootloader.img ]
444+0 records in
444+0 records out
444 bytes copied, 0.00309177 s, 144 kB/s
8191+0 records in
8191+0 records out
4193792 bytes (4.2 MB, 4.0 MiB) copied, 0.575025 s, 7.3 MB/s
[ STEPS ] Processing BOOTFS partition...
[ INFO ] Formatting BOOTFS partition...
mkfs.fat 4.2 (2021-01-31)
[ INFO ] Copying BOOTFS ...
[ INFO ] Update the [ uEnv.txt ] file.
[ STEPS ] Start processing the rootfs partition...
[ INFO ] Formatting ROOTFS ...
/dev/mmcblk2p2 contains a ext4 file system labelled 'ROOTFS_EMMC'
        last mounted on /root on Thu Jan  1 08:00:09 1970
[ INFO ] Copying ROOTFS ...
[ INFO ] Copying [ etc ] ...
[ INFO ] Copying [ home ] ...
[ INFO ] Copying [ opt ] ...
[ INFO ] Copying [ root ] ...
[ INFO ] Copying [ selinux ] ...
[ INFO ] Copying [ srv ] ...
[ INFO ] Copying [ usr ] ...
[ INFO ] Copying [ var ] ...
[ INFO ] Generate the new fstab file.
[ INFO ] Update parameters related to the releases file.
[ INFO ] Update the MAC address for the wireless network card.
[ SUCCESS ] Installation successful. Run [ poweroff ], remove the installation media then re-insert the power supply to boot new system.
root@armbian:~# 
root@armbian:~# 
root@armbian:~# 
root@armbian:~# 
root@armbian:~# 
root@armbian:~# 
root@armbian:~# 
root@armbian:~# 
root@armbian:~# halt
</pre>

![Image](https://github.com/user-attachments/assets/3f3f654e-6ba4-4fa9-a119-01c696ee2fe7)
