### ISSUE TITLE
扩容128g后写入emmc成功后拔掉U盘无法进入系统。

### ISSUE THREAD

**Issue by Alvin1986** [ophub/amlogic-s9xxx-armbian#1291]
![mmexport1681589246540.jpg](https://user-images.githubusercontent.com/125835237/232251182-59f27bfe-d80a-41ed-960c-fefba883bfe2.jpg)

![mmexport1681589249671.jpg](https://user-images.githubusercontent.com/125835237/232251194-b6aa2ff2-2e74-47e8-a1aa-0836c80bde86.jpg)

![mmexport1681589254212.jpg](https://user-images.githubusercontent.com/125835237/232251199-1b7ff5c1-90da-4f12-b7ba-396e32fc9140.jpg)

以上未拔U盘
![mmexport1681589256809.jpg](https://user-images.githubusercontent.com/125835237/232251213-11723c3b-0f3d-4aed-85fe-052a414e66b4.jpg)

![mmexport1681589260999.jpg](https://user-images.githubusercontent.com/125835237/232251214-71567b8a-9704-40d0-b4e6-f5eb7aa6b796.jpg)

![mmexport1681589267434.jpg](https://user-images.githubusercontent.com/125835237/232251219-47c37dd4-4aea-4627-beff-c506fbbaa223.jpg)

以上为拔掉U盘后进入不了系统，又插回U盘

**Comment by ophub** [comment]
像vplus最高只能认出来2+32g，所以原来的1+8g升高了用不了。
你查过资料这个盒子支持128g？

**Comment by Alvin1986** [comment]
> 像vplus最高只能认出来3+32g，所以原来的1+8g升高了用不了。
> 你查过资料这个盒子支持128g？

可以了，把U盘和盒子速度调到50   写入了。。。可是更新后network里面文件是空的。只有一个IP和一个Mac。没有发生变化。。

**Comment by Alvin1986** [comment]
> 像vplus最高只能认出来3+32g，所以原来的1+8g升高了用不了。
> 你查过资料这个盒子支持128g？

TV系统认到256g😅

**Comment by Alvin1986** [comment]
> 像vplus最高只能认出来3+32g，所以原来的1+8g升高了用不了。
> 你查过资料这个盒子支持128g？

![IMG_20230417_011350.jpg](https://user-images.githubusercontent.com/125835237/232329153-c43d7adc-fc0c-44ab-9c71-d097594c1fc9.jpg)

![IMG_20230417_011404.jpg](https://user-images.githubusercontent.com/125835237/232329158-81227df0-972c-439e-a857-4b857943ce90.jpg)

又不可以了。。。。昨天写入了。。拔插很多次都可以。今天晚上回来就又变这样了

**Comment by Alvin1986** [comment]
> 像vplus最高只能认出来3+32g，所以原来的1+8g升高了用不了。
> 你查过资料这个盒子支持128g？

![IMG_20230417_153739.jpg](https://user-images.githubusercontent.com/125835237/232417191-bc5b9a0e-4e2d-48b2-8eae-84cc7e0ecfec.jpg)

可以认到128g的emmc

**Comment by ophub** [comment]
rk3328的vplus不行，我不知道s905l3a行不行
你使用5.15内核的系统，这个不要u-boot，更好引导

**Comment by Alvin1986** [comment]
> rk3328的vplus不行，我不知道s905l3a行不行
> 你使用5.15内核的系统，这个不要u-boot，更好引导

我换一下5.15的内核看看，不要U-boot 怎么做?直接删除u-boot吗？大佬教一下

**Comment by Alvin1986** [comment]
> > rk3328的vplus不行，我不知道s905l3a行不行
> > 你使用5.15内核的系统，这个不要u-boot，更好引导
> 
> 我换一下5.15的内核看看，不要U-boot 怎么做?直接删除u-boot吗？大佬教一下

我是用 s905l3b 和 s905l3a 的芯片

**Comment by ophub** [comment]
下载5.15的固件

**Comment by Alvin1986** [comment]
> 下载5.15的固件，默认安装

收到，我试一下。。。。谢谢大佬的耐心指导

**Comment by Alvin1986** [comment]
> 下载5.15的固件，默认安装

也有可能是U盘问题。经常刷机，U盘很多没有清理干净。大佬认同这个观点吗？

**Comment by ophub** [comment]
u盘表示，我辛辛苦苦帮你刷机，你还怀疑我，下次插入u盘我不帮你启动了

**Comment by Alvin1986** [comment]
> u盘表示，我辛辛苦苦帮你刷机，你还怀疑我，下次插入u盘我不帮你启动了

哈哈哈，因为我记得会认U盘。U盘的质量等都会影响到一些。只是我个人的想法。。

**Comment by ophub** [comment]
U盘说，我都被拔掉了，不能启动还怪我，这不科学。

**Comment by Alvin1986** [comment]
> > 下载5.15的固件，默认安装
> 
> 收到，我试一下。。。。谢谢大佬的耐心指导

![IMG_20230417_164400.jpg](https://user-images.githubusercontent.com/125835237/232435587-5afa4b77-b3cb-4a2e-8fde-c9460ef02653.jpg)

5.15.50的内核  一样不行

**Comment by ophub** [comment]
5.15.107比50还多50，你在哪下的怀旧版？

**Comment by Alvin1986** [comment]
> 5.15.107比50还多50，你在哪下的怀旧版？

以前下载包，保存的。。。就一个6.18的好像 。我现在碰到的问题更好玩。就是写入emmc可以reboot了 不插U盘 。可是不能断电。。。断电后，再插电源。就认不到盒子了。

**Comment by Alvin1986** [comment]
> 5.15.107比50还多50，你在哪下的怀旧版？

![wx_camera_1681722637549.jpg](https://user-images.githubusercontent.com/125835237/232445591-3e738332-d99b-418a-b418-ff4b49baa05a.jpg)

![wx_camera_1681722682556.jpg](https://user-images.githubusercontent.com/125835237/232445616-4cb4be38-2dde-49d9-8e28-87ac1cc61f75.jpg)

![IMG_20230417_164934.jpg](https://user-images.githubusercontent.com/125835237/232445663-33cdcb21-bc80-4b9e-a14b-2d563fb0a55e.jpg)

写入后，我改了静态IP。

**Comment by Alvin1986** [comment]
> U盘说，我都被拔掉了，不能启动还怪我，这不科学。

我现在写入顺序是，U盘启动先不写入emmc，先升级固件，然后改dtc改U盘和盒子mmc速率。最后写入emmc让reboot，reboot成功再次开启后识别到128g的emmc后在reboot马上拔U盘，然后等待5分钟左右看路由器后台是否认到盒子IP。认到后登入系统修改etc的network的IP地址。然后再reboot。再次观察是否认到。认到了就是不能断电，断电再次就认不到了。
目前的结果就是只能reboot不能断电

**Comment by Alvin1986** [comment]
> 5.15.107比50还多50，你在哪下的怀旧版？

我所有的都是在您论坛这边下载的呀😂

**Comment by ophub** [comment]
这是2个月前的版本了，我releases里下载都没超过1周的。
你不想用最新版？我觉得2个月来，修复了不少已知问题。
https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by Alvin1986** [comment]
> 6.1.18是2个月前的版本了，我releases里下载都没超过1周的。
> 你不想用最新版？我觉得2个月来，修复了不少已知问题。
> https://github.com/ophub/amlogic-s9xxx-armbian/releases
> 
> 5.15.50大概是1年前的版本，很多命令都变了。

我开始都是用最新版的。。就是最新版无法写入。我才找以前我下载的。
![IMG_20230417_174945.jpg](https://user-images.githubusercontent.com/125835237/232450318-32880084-c03c-4e50-ad6a-8bef2bcfdb64.jpg)

- [ ]![IMG_20230417_175034.jpg](https://user-images.githubusercontent.com/125835237/232450350-a203e75c-3217-4f8a-bd2d-cf0751c18c68.jpg)

您看，又不行了😂。不知道什么问题。。我有三个都扩容128g 都是同一个情况

**Comment by ophub** [comment]
无法写入emmc是emmc频率较高的问题。

**Comment by Alvin1986** [comment]
> 无法写入emmc是emmc频率较高的问题。

现在是写入了，reboot后有时可以认到，有时认不得。。。很奇怪。。mmc那个速率我改了。。。。改100-50-25都试过了。结果都一样😂只能求助大佬您了

**Comment by Alvin1986** [comment]
> 无法写入emmc是emmc频率较高的问题。

![IMG_20230418_011144.jpg](https://user-images.githubusercontent.com/125835237/232563017-21f229c3-8c30-420b-a1bc-1ee78f8a81e7.jpg)

![IMG_20230418_011359.jpg](https://user-images.githubusercontent.com/125835237/232563037-2cebb3fb-85f8-4032-82ac-ba99a50bd0d5.jpg)

![IMG_20230418_011820.jpg](https://user-images.githubusercontent.com/125835237/232563057-38f50417-19e9-4b8d-8a73-39369bca3289.jpg)

![IMG_20230418_011844.jpg](https://user-images.githubusercontent.com/125835237/232563064-0d5c1ae7-2e7f-4717-b7bb-bf8553eb7e6f.jpg)

![IMG_20230418_011853.jpg](https://user-images.githubusercontent.com/125835237/232563074-8f34ffbe-a34d-4e51-b847-2aac80256246.jpg)

s905l3a 盒子是b863-3.2m最新固件无法更新，无法修改dts后保存，大佬您看看

**Comment by Alvin1986** [comment]
> > 无法写入emmc是emmc频率较高的问题。
> 
> 现在是写入了，reboot后有时可以认到，有时认不得。。。很奇怪。。mmc那个速率我改了。。。。改100-50-25都试过了。结果都一样😂只能求助大佬您了

s905l3b 现在就是可以写入emmc了。可以不能长时间断电。超过1个小时断电就也进不去系统了。已经改了速率  0x5f5e100

**Comment by Alvin1986** [comment]
s905l3b 使用5.15.107 U盘无法引导进入系统

**Comment by Alvin1986** [comment]
> s905l3b 使用5.15.107 U盘无法引导进入系统

只能使用6.1.18或者6.1.24的   可是用这两个就写不进去emmc

**Comment by Alvin1986** [comment]
> 无法写入emmc是emmc频率较高的问题。

b863av3.2m芯片s905l3a 使用5.15.107固件，解决写入emmc和断电后重新上电进入系统。

**Comment by ophub** [comment]
给5.15手动复制一下u-boot后引导启动效果等同6.12

**Comment by Alvin1986** [comment]
> 给5.15手动复制一下u-boot后引导启动效果等同6.1

s905l3a的 已经可以了😂，还有两个型号的盒子都是s905l3b的 一个型号是b860av2.1a 就是写入emmc后 长时间断电 再次通电就无法进入系统。 一个型号为ty1608的盒子，尝试您发的安卓TV包无法刷入，所以也没办法进行armbian的写入。

**Comment by ophub** [comment]
安卓系统可以网上找别人分享的适合你的盒子的root了的系统，可以adb

**Comment by Alvin1986** [comment]
> 安卓系统可以网上找别人分享的适合你的盒子的root了的系统，可以adb

ty1608找了很久没有😂

**Comment by ophub** [comment]
都可以吧。你试试5.15

**Comment by Alvin1986** [comment]
> 都可以吧。你试试5.15

您方便的话，开个仓库，我整理一下。看看怎么把包放上去。方便您开源和粉丝的学习

**Comment by Alvin1986** [comment]
> 都可以吧。你试试5.15

大佬你这个里面的刷机包都是带adb和root的吗？https://github.com/ophub/kernel/releases/tag/tools

**Comment by ophub** [comment]
这里转存的都是之前的贴子里，不同盒子的首位贡献者测试时使用的安卓系统，他们分享的我转存的，我不知道是不是都root了

**Comment by Alvin1986** [comment]
> 这里转存的都是之前的贴子里，不同盒子的首位贡献者测试时使用的安卓系统，他们分享的我转存的，我不知道是不是都root了

好的，我晚上试一下。看看我整理一下，我手里的root带adb的包上去。很多我也都删除了。

**Comment by ophub** [comment]
你整理好了放某度盘或者阿某盘，分享一个下载

**Comment by Alvin1986** [comment]
> 你整理好了放某度盘或者阿某盘，分享一个下载
好的。我整理一下。就像b860av2.1a这个盒子的芯片是s905l3b的 很多人都没办法刷armbian 我就刷成功了。可是扩容后。这几天写入了断电就连接不上reboot有时候也连接不上。还只能刷6.1的内核。大佬您有时间也可以看看能否优化一下。

**Comment by ophub** [comment]
断电放几天就不能开机的问题我想不明白为什么

**Comment by Alvin1986** [comment]
> 断电放几天就不能开机的问题我想不明白为什么

不用放几天😂一个钟头不到就不行了

**Comment by ophub** [comment]
断电一个小时，你能想到armbian在没电的情况下怎么变身的呢？太阳能？还是外星人给了它超能力，让它在无电关机状态下发生了变化，然后过了一个小时就不能启动了，难道是cpu有点凉感冒了？

**Comment by Alvin1986** [comment]
> 断电一个小时，你能想到armbian在没电的情况下怎么变身的呢？太阳能？还是外星人给了它超能力，让它在无电关机状态下发生了变化，然后过了一个小时就不能启动了，难道是cpu有点凉感冒了？
断电一个钟头后，再次插电源就无法再次进入系统了。
