### ISSUE TITLE
无法从u盘启动

### ISSUE THREAD

**Issue by bgsnwhh** [ophub/amlogic-s9xxx-armbian#1293]
**Device Information | 设备信息**
 - SOC: Allwinner H6
 - Model:腾讯极光1v

**Armbian Version | 系统版本**
 - Kernel Version: 04.14.1028
 - Release: Armbian_jammy_04.14.1028/Armbian_23.05.0_allwinner_tanix-tx6_jammy_5.15.107_server_2023.04.14.img.gz

**Describe the bug | 问题描述**
全志H6的u无法从U盘启动，请问全志的u支持从u盘启动吗？

**Comment by bgsnwhh** [comment]
这个可以正常刷tanix tx6的安卓系统使用。

**Comment by ophub** [comment]
开启adb调试，adb shell reboot update

**Comment by bgsnwhh** [comment]
> 开启adb调试，adb shell reboot update

感谢，晚上我测试一下

**Comment by bgsnwhh** [comment]
测试失败,adb shell reboot update 之后，进的仍是安卓系统。这个盒子已经刷了tx6的安卓7系统了。
盒子的标签和主板如下
![A4D54635-B554-494F-ABDE-2F79157FA649](https://user-images.githubusercontent.com/106364125/232487598-612ba62b-42f2-43fb-b6e2-16a6a793aada.jpeg)
盒子，只有usb接口，没有sd 卡槽，也没有有线网口。
![B9237C24-ADDB-4981-BFE6-A80FF54A99EB](https://user-images.githubusercontent.com/106364125/232487652-98904f8a-7a19-4f5e-babc-53f9a557bace.jpeg)
![7483CEC8-5941-4ECF-B858-5421CE6143F7](https://user-images.githubusercontent.com/106364125/232487672-0948af70-c41d-4239-8af0-52672e0a4f86.jpeg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

12.4

**Comment by jiaotiliu** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
> 
> 12.4

page not find 404 error

**Comment by jiaotiliu** [comment]
全志CPU的盒子，是不是只能从SD卡启动，而内核不支持从U盘启动呢

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents
