### ISSUE TITLE
Video quality 

### ISSUE THREAD

**Issue by NandiniAjay** [ophub/amlogic-s9xxx-armbian#1294]
**Device Information**
 - SOC: S095x3
 - Model: ARMv8
 - Kernel Version: 5.15.25-flippy
 - Release: Jammy

Hii,
The video quality of the device is not that smooth and gets blurred in between, Is there any way we can do any changes to it to have a better quality of video.

Thanks Regards,
Nandini

**Comment by Supded** [comment]
Lags or judder effect?
