### ISSUE TITLE
能否增加青龙 debian 版本

### ISSUE THREAD

**Issue by GD2021** [ophub/amlogic-s9xxx-armbian#1297]
青龙debian版

伴随着 青龙 项目 github 突破 10000 star，本次推出 debian 版本
主要功能与最新版青龙相同，与正式版本的区别如下：

1. debian 版本底层镜像使用 debian-slim 系统，正式版使用的是 alpine 系统
2. debian 版本定时服务使用独立服务，不依赖系统自有服务，latest 五位定时任务使用的是系统内置 cron 服务，六位使用独立服务
3. debian 版本可安装某些不支持 alpine 系统的依赖

使用方法:

-> 使用镜像由 whyour/qinglong:latest 切换为 whyour/qinglong:debian
-> 拉取镜像 docker pull whyour/qinglong:debian
-> 使用 debian 镜像运行容器
-> debian 版本目前计划是跟随正式版同步更新，感谢有你

**Comment by ophub** [comment]
docker安装的区别是latest/debian不同，其他参数相同？
