### ISSUE TITLE
ZXV10 B860AV3.1-M2无法从U盘启动，HDMI黑屏

### ISSUE THREAD

**Issue by wengfch** [ophub/amlogic-s9xxx-armbian#1299]
![image](https://user-images.githubusercontent.com/41176018/232716631-a4b8026f-08f8-4c66-a808-4ddebe03614e.png)
这两个镜像都刷过，adb reboot update后插入U盘，之后出现开机界面，然后黑屏（这过程看U盘有闪灯，应该是有从U盘启动）。插上网线也没看到有自动获取到IP。

![e69680590679fa3117ec7242ef0dfff](https://user-images.githubusercontent.com/41176018/232717130-1026b1c3-549c-4a03-935f-f2ef9d950bee.jpg)

**Comment by wengfch** [comment]
能告知下为什么没回复就关了哦。

**Comment by ophub** [comment]
关了先放一放，等我毕业了挣钱了，我攒点钱买一个，我拆开看看是什么soc，芯片主板我看看，我再选个同型号的试验。目前我还没钱买，用肉眼横屏竖屏看了看，盒子上好像没找到个洞，看不到不敢瞎说，改你的宝贝整砖了不好。

**Comment by wengfch** [comment]
给个地址，我寄个给你折腾。成功与否都没关系。
