### ISSUE TITLE
Kernel headers

### ISSUE THREAD

**Issue by Omer1970** [ophub/amlogic-s9xxx-armbian#13]
Hi,

Is it possible to install the kernel headers?

regards,

**Comment by ophub** [comment]
sudo apt-get update
sudo apt-get install -y build-essential linux-headers-$(uname -r)

**Comment by Omer1970** [comment]
Yes I did this :
***@***.***:~# uname -r
5.10.77-flippy-66+
***@***.***:~# sudo apt-get update
apt-get install -y build-essential linux-headers-$(uname -r)
Hit:1 http://mirrors.aliyun.com/debian buster InRelease
Hit:2 http://mirrors.aliyun.com/debian-security buster/updates InRelease
Hit:3 http://mirrors.aliyun.com/debian buster-updates InRelease
Hit:4 http://mirrors.aliyun.com/debian buster-backports InRelease
Hit:5 http://mirrors.aliyun.com/armbian buster InRelease
Reading package lists... Done
***@***.***:~# sudo apt-get install -y build-essential linux-headers-$(uname -r)
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package linux-headers-5.10.77-flippy-66
E: Couldn't find any package by glob 'linux-headers-5.10.77-flippy-66'
E: Couldn't find any package by regex 'linux-headers-5.10.77-flippy-66'

I also did:
Command: armbian-config
         -> Software
              -> Kernel headers
But didn’t help.
Is this because of the kernel 5.10.77?

Regards

**Comment by ophub** [comment]
Download the latest [armbian-update](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-update) script: 

In the latest 4 kernels (`5.10.80` / `5.14.20` / `5.15.3` / `5.4.160`), flippy shared the header files, I updated the script to support direct installation of the header files.
```
wget -O /usr/sbin/armbian-update https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/files/usr/sbin/armbian-update && chmod +x /usr/sbin/armbian-update

armbian-update 5.4.160
```
