### ISSUE TITLE
Alfawise H96 pro + 3/32 PLC Blue problem power off mid-installation

### ISSUE THREAD

**Issue by PCardoso7** [ophub/amlogic-s9xxx-armbian#1300]
Hi,
I am trying to put armbian on Alfawise H96 Pro + (3/32).
I've already used Armbian_23.05.0_amlogic_s912_jammy_5.15.107_server_2023.04.17.img.gz and also bullseye but when it gets to the part of "Start copy BOOTFS partition data" the box automatically turns off and doesn't install Armbian. 
Is there a way to resolve this?
Thanks

**Comment by ophub** [comment]
try again

**Comment by PCardoso7** [comment]
I've tried 4x and it always happens at the same point of installation (I already used pendrive and micro sdcard)

**Comment by PCardoso7** [comment]
This still not resolved.
Any additional solution?
Tks

**Comment by shadowd47** [comment]
![IMG20240103193459](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1446857/c83ca73b-8065-4527-ad8d-979ac6a60210)
Hello, I thing get the same issue.
I have installed on Armbian on H96 pro plus green PCB (DDR4) easily but on my other device (blue PCB (DDR3)) they doesn't work.

Maybe the same issue as [#1058](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1058) ? 
If so, could you help me/us to fix it ?
