### ISSUE TITLE
[ASK] Rebuilding from existing rootfs

### ISSUE THREAD

**Issue by Manssizz** [ophub/amlogic-s9xxx-armbian#1302]
Hello...
How to rebuilding armbian system with existing rootfs? i want to create kali custom arm for amlogic soc

**Comment by ophub** [comment]
I don’t know

**Comment by SajjadSabzkar** [comment]
> Hello... How to rebuilding armbian system with existing rootfs? i want to create kali custom arm for amlogic soc
Hi ,
@7Ji maybe help to you.  it made [amlogic-s9xxx-archlinuxarm ](https://github.com/7Ji/amlogic-s9xxx-archlinuxarm) for amlogic soc
