### ISSUE TITLE
Difference between s905x3 and s905x3-b images?

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#1303]
Hi @ophub !

I have noticed that the latest Armbian images see to have 2 sets of images for s905x3 boxes now.

I have checked the latest README but it doesn't seem to explain the difference. For example, what is the difference between:

Armbian_23.05.0_amlogic_s905x3_bullseye_5.15.107_server_2023.04.17.img.gz

and

Armbian_23.05.0_amlogic_s905x3-b_bullseye_5.15.107_server_2023.04.17.img.gz

Thanks!

Dan

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

**Comment by danboid** [comment]
Yes I looked on that page. Is this the line that explains it

When [ -b all             ], it will look for [ <BUILD> value is yes ]

What does that mean?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

look at 5.3

**Comment by danboid** [comment]
Hi @ophub 

I have read 5.3 but unfortuately it doesn't make sense. I realise English isn't your first language.

I THINK what 5.3 might be saying is that -b is only a build option, and that -b is used to select the bulding of optional boards? Thats my best guess, but if thats what it is, it makes no sense that there should be separate images like s905x3-b.

I had a quick look at the two images I mentioned above and I could see they were using different dtbs but I didn't recognise the model of the dtb used in the s905x3-b image.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf
