### ISSUE TITLE
为armbian目前推荐买哪一个盒子？

### ISSUE THREAD

**Issue by alcatraz-zz** [ophub/amlogic-s9xxx-armbian#1304]
1. 不带wifi
2. 带wifi
3. 可写emmc的
4. 带千兆有线网口+USB3

现在哪一个盒子性价比很高的？

2+8/2+16都行，功能比较好运行的

**Comment by ophub** [comment]
rock5b

**Comment by alcatraz-zz** [comment]
谢谢回复。明白。有不同芯的。

便宜盒子带wifi呢？cm311-1s好像不支持啊。

armbian+s905l写emmc成功我看到了。现在好像可以写啊。

买贵之前想试试标准盒。

**Comment by ophub** [comment]
n1也不会多变。魔百和几十种

**Comment by ophub** [comment]
只听名字可能不准确，x96max+有10几个外壳一样的。hk1, tx3等盒子都有很多变种。

魔百和各省运营商独立订制。你问好店家，或者买了看电视也是极好的。

**Comment by alcatraz-zz** [comment]
嗯嗯

"CH"好像是长虹的，比其他的更高配有的人说

**Comment by ophub** [comment]
列表里的魔百和都是大家测试分享的，我只是个记录员，拿本本都记下来了大家的测试成员，听说这种记录工作叫＂书记＂？

书记说，你啥时候测测CH怎么样，记得反馈哦

**Comment by altmangood** [comment]
NanoPC T4 这个机器也不错，固件很多，接口很全，资料很多
