### ISSUE TITLE
这两个版本有什么区别吗？都是基于debian的

### ISSUE THREAD

**Issue by xxx854** [ophub/amlogic-s9xxx-armbian#1305]
![image](https://user-images.githubusercontent.com/77531464/232948110-6ef4ca8d-e330-4031-b991-bc14d369f1a3.png)

**Comment by ophub** [comment]
内核不同

**Comment by xxx854** [comment]
> 内核不同

推荐哪个呢，e900v22d s905l3b ,准备U盘做系统盘，emmc写入后会有问题

**Comment by ophub** [comment]
都一样

**Comment by xxx854** [comment]
> 都一样，男女平等

好像没毛病
