### ISSUE TITLE
点心云好像用了你的固件做商业用途

### ISSUE THREAD

**Issue by Linmihg** [ophub/amlogic-s9xxx-armbian#1306]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905L3A
 - Model : 中兴B863av3.2-M

**Armbian Version | 系统版本**
 - Kernel Version: KERNEL_VERSION='5.15.82'
 - Release: jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
点心云，一个做PCDN业务的，最近出了一批盒子来卖189元一台，他们把emmc换成了128g的了，用的硬件是中兴B863av3.2-M，固件是armbian。系统文件里看到了Flippy和ophub的名字。不知道你们知不知情，允不允许他们这么用。
![image](https://user-images.githubusercontent.com/113785874/233053646-19333b0a-69e6-46a3-bcdc-423b98e41459.png)
[](url)

**Comment by ophub** [comment]
我不了解点心云，也不了解pcdn业务是什么。这不是政府禁止的黑色产业吧。

免费用可以，我不想哪天打击黑产时，把我划成黑产支持者。armbian系统没有特殊用途，做为一个轻量级的linux系统，在上面跑什么业务都是用户自己的事，我不建议也不支持做任何不合规的事情。

我rebuild的系统遵循上游armbian官方系统的GPL-2.0协议，我继承并保持该协议下的使用方式不变。

**Comment by Linmihg** [comment]
> 我不了解点心云，也不了解pcdn业务是什么。这不是政府禁止的黑色产业吧。
> 
> 免费用可以，我不想哪天打击黑产时，把我划成黑产支持者。armbian系统没有特殊用途，做为一个轻量级的linux系统，在上面跑什么业务都是用户自己的事，我不建议也不支持做任何不合规的事情。
> 
> 我rebuild的系统遵循上游armbian官方系统的GPL-2.0协议，我继承并保持该协议下的使用方式不变。

点心云有官网如果想了解的话可以查一下。就是点心云作为服务商收集家庭宽带的上传资源为相关上游比如抖音 b站 爱奇艺等做内容分发，类似的还有网心云啥的。目前应该还不算黑产，不过肯定属于违规使用宽带，具体我也不大了解，只是发现点心云出的产品用的是你的固件。
