### ISSUE TITLE
armbian emmc引导问题

### ISSUE THREAD

**Issue by xxx854** [ophub/amlogic-s9xxx-armbian#1307]
写入emmc后，第一次启动是正常的，当断电在启动时，有概率出现ssh无反应，疑似变砖。
硬件配置s905l3 armbian6.1.4基于debian的

**Comment by gametta** [comment]
什么型号的盒子。大家有个参考的地方

**Comment by ophub** [comment]
6.1.4是去年冬天的版本，至今有半年了。到releases里下载最新版

**Comment by xxx854** [comment]
> 什么型号的盒子。大家有个参考的地方

烽火680lc
