### ISSUE TITLE
stable内核和flippy内核具体有啥区别

### ISSUE THREAD

**Issue by wukibaka** [ophub/amlogic-s9xxx-armbian#1308]
如题

**Comment by ophub** [comment]
看说明
https://github.com/ophub/kernel/blob/main/README.cn.md

**Comment by wukibaka** [comment]
> 看说明 https://github.com/ophub/kernel/blob/main/README.cn.md

stable启用了更多支持选项 具体是启用了什么

**Comment by ophub** [comment]
过去1年里，大家在这里的帖子里提出的启用选项需求，可以翻帖子找。

**Comment by wukibaka** [comment]
> 过去1年里，大家在这里的帖子里提出的启用选项需求，可以翻帖子找。

行 谢谢大佬

**Comment by ophub** [comment]
积累增加，没有写记录。简单的方法是diff命令比较这个config和f大的config就看到多出的选项了
