### ISSUE TITLE
可以适配一个新板子吗：LIVA M300-W

### ISSUE THREAD

**Issue by LioDon** [ophub/amlogic-s9xxx-armbian#1309]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC:RK399
 - Model LIVA M300-W
 - 官网：https://www.ecs.com.tw/tw/news-detail/20210316-1
 

尝试刷TN3399的包凑合着能刷上，但进入图形界面一分钟左右就卡死了。没法用，大概是不适配。

我手头的这个是2+32G的版本，
RAM：金士顿的D2516ECMDXGJD1
EMMC：BiWIN的BWCTASC11P32G
无线网卡：AP6236

**Comment by LioDon** [comment]
![20230420_165755](https://user-images.githubusercontent.com/52228201/233318652-0fc4d476-2f23-4d11-afae-884981c78a43.jpg)
![20230420_170015](https://user-images.githubusercontent.com/52228201/233318667-c3cb86cb-56a9-4b4d-a3e2-e137e0bd6930.jpg)
![20230420_170052](https://user-images.githubusercontent.com/52228201/233318682-ea815ac0-6943-401e-b000-c6beabdcb594.jpg)
![20230420_170151](https://user-images.githubusercontent.com/52228201/233318688-2424a234-eef6-4e1c-ae9a-869c0f3a3d54.jpg)
![20230420_170213](https://user-images.githubusercontent.com/52228201/233318703-8f2b2442-4261-4e26-a836-4a6ddce0020d.jpg)
![20230420_170232](https://user-images.githubusercontent.com/52228201/233318707-a49fd66d-222f-48e2-a526-7f8030d8ecb3.jpg)
![20230420_170253](https://user-images.githubusercontent.com/52228201/233318717-899d9c46-531d-4583-9f82-5037c3434ec2.jpg)
![20230420_170302](https://user-images.githubusercontent.com/52228201/233318728-374beb62-a3ef-4084-afec-abdef3f707a8.jpg)
![20230420_170413](https://user-images.githubusercontent.com/52228201/233318737-a9cbfaf9-6a4f-4dde-ae80-4b62f02de0cd.jpg)
![20230420_170428](https://user-images.githubusercontent.com/52228201/233318747-4013166f-f932-4aa1-9a9f-3962a319d93b.jpg)

**Comment by LioDon** [comment]
> 板子不错，还带m.2

那个是4G模块专用的接口……估计接不了硬盘了…………

**Comment by ophub** [comment]
能正常启动，说明u-boot可用。
卡死时日志是什么？启动有什么错误日志？

**Comment by LioDon** [comment]
重新插上内存卡想起来上边的数据被格了，重新来一遍吧，路径刚刚刚才搜到了，不确定对不对，我先试试。

**Comment by LioDon** [comment]
[auth.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298593/auth.log)
[bootstrap.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298594/bootstrap.log)
[dpkg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298595/dpkg.log)
[kern.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298596/kern.log)
[fontconfig.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298597/fontconfig.log)
[boot.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298598/boot.log)
[alternatives.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298600/alternatives.log)
[armbian-hardware-monitor.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298602/armbian-hardware-monitor.log)
[armbian-ramlog.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11298603/armbian-ramlog.log)
![飞书20230422-030641](https://user-images.githubusercontent.com/52228201/233715437-98811d60-4f68-42e2-9d31-6d192dff9733.jpg)
这是所有的日志，照片显示是卡死的地方。这一次连图形界面都没加载出来，我有点儿怀疑昨儿晚上进到图形界面的那个版本是不是TN3399了，凌晨三点多也能是记错了，难道刷的是King3399？……

**Comment by LioDon** [comment]
确定过了，就是TN3399.King3399走不了那么远。

**Comment by LioDon** [comment]
> Standard chat template, no routine, no chat. 标准聊天模板，无套路不聊天。
> 
> **Device Information | 设备信息**
> 
> * SOC:RK399
> * Model LIVA M300-W
> * 官网：https://www.ecs.com.tw/tw/news-detail/20210316-1
> 
> 尝试刷TN3399的包凑合着能刷上，但进入图形界面一分钟左右就卡死了。没法用，大概是不适配。
> 
> 我手头的这个是2+32G的版本， RAM：金士顿的D2516ECMDXGJD1 EMMC：BiWIN的BWCTASC11P32G 无线网卡：AP6236

才发现，写错了，是3399K

**Comment by ophub** [comment]
![Snip20230423_1](https://user-images.githubusercontent.com/68696949/233828202-cfa3f904-0017-42db-8e0f-1ada3e588704.png)
这个网站上不了，搜索引擎也没找到他的开发资料，你有可以使用的ubuntu/debian等其他系统固件没？

**Comment by LioDon** [comment]
没有别的固件，板子自带的安卓昨儿都分区备份了。
这个网站看样子是台湾的，我的软路由得把梯子关掉才能上去，不太清楚还配置了啥。我截了张图：
![精英電腦全新寬溫迷你電腦LIVA M300-W 打造工業級解決方案｜ECS 精英電腦](https://user-images.githubusercontent.com/52228201/233851996-227e3743-8c73-4f74-a896-57b1413116a4.png)


瑞芯微读出的分区表看下面的图：
![设备分区表](https://user-images.githubusercontent.com/52228201/233852082-0a96d3f3-0978-4228-a45e-119e5e541a52.png)
除了userdata，其他都备份了，5个G，需要的话可以发你。

**Comment by inoeud** [comment]
你可能需要手搓dts了

**Comment by LioDon** [comment]
> 你可能需要手搓dts了

你太看得起我了……我哪有那水平…………

**Comment by duxingkei33** [comment]
> > 你可能需要手搓dts了
> 
> 
> 
> 你太看得起我了……我哪有那水平…………

我用dd 命令备份了这块板子的编程器固件，提取了安卓的dtb,反汇编了源码，但是不知道怎么手搓Ubuntu 或者op的dtb,编译了firefly烧录到板子的emmc，内核启动后卡死，感觉是电源配置不对，需要的话我把dts 发上来。

**Comment by LioDon** [comment]
> 



> > > 你可能需要手搓dts了
> > 
> > 
> > 你太看得起我了……我哪有那水平…………
> 
> 我用dd 命令备份了这块板子的编程器固件，提取了安卓的dtb,反汇编了源码，但是不知道怎么手搓Ubuntu 或者op的dtb,编译了firefly烧录到板子的emmc，内核启动后卡死，感觉是电源配置不对，需要的话我把dts 发上来。

刷TN3399的包刷上去了，正常启动。“附加驱动”和“软件和更新”这俩程序没反应，打不开。

**Comment by LioDon** [comment]
> > 
> 
> > > > 你可能需要手搓dts了
> > > 
> > > 
> > > 你太看得起我了……我哪有那水平…………
> > 
> > 
> > 我用dd 命令备份了这块板子的编程器固件，提取了安卓的dtb,反汇编了源码，但是不知道怎么手搓Ubuntu 或者op的dtb,编译了firefly烧录到板子的emmc，内核启动后卡死，感觉是电源配置不对，需要的话我把dts 发上来。
> 
> 刷TN3399的包刷上去了，正常启动。“附加驱动”和“软件和更新”这俩程序没反应，打不开。

发现一个新问题：板载的USB3.0接口无法使用，具体表现为USB3.0接口的U盘插上之后没反应，不识别，换到USB2.0的接口就能正常识别。这个怎么破？

**Comment by duxingkei33** [comment]
哈哈，本来准备手搓的，结果太热，不想玩，下班回来就躲空调房穿上躺平了，暂时不折腾了，有空再玩，几款3399都凑齐了，3288也有板子，就是懒，……这折腾







发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LioDon ***@***.***&gt;
发送时间: 2023年7月26日 21:47
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: duxingkei33 ***@***.***&gt;, Manual ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] 可以适配一个新板子吗：LIVA M300-W (Issue #1309)





       
你可能需要手搓dts了
  
你太看得起我了……我哪有那水平…………
  
我用dd 命令备份了这块板子的编程器固件，提取了安卓的dtb,反汇编了源码，但是不知道怎么手搓Ubuntu 或者op的dtb,编译了firefly烧录到板子的emmc，内核启动后卡死，感觉是电源配置不对，需要的话我把dts 发上来。
  
刷TN3399的包刷上去了，正常启动。“附加驱动”和“软件和更新”这俩程序没反应，打不开。
  
发现一个新问题：板载的USB3.0接口无法使用，具体表现为USB3.0接口的U盘插上之后没反应，不识别，换到USB2.0的接口就能正常识别。这个怎么破？

**Comment by LioDon** [comment]
> 哈哈，本来准备手搓的，结果太热，不想玩，下班回来就躲空调房穿上躺平了，暂时不折腾了，有空再玩，几款3399都凑齐了，3288也有板子，就是懒，……这折腾 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: LioDon ***@***.***&gt; 发送时间: 2023年7月26日 21:47 收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt; 抄送: duxingkei33 ***@***.***&gt;, Manual ***@***.***&gt; 主题: Re: [ophub/amlogic-s9xxx-armbian] 可以适配一个新板子吗：LIVA M300-W (Issue #1309) 你可能需要手搓dts了 你太看得起我了……我哪有那水平………… 我用dd 命令备份了这块板子的编程器固件，提取了安卓的dtb,反汇编了源码，但是不知道怎么手搓Ubuntu 或者op的dtb,编译了firefly烧录到板子的emmc，内核启动后卡死，感觉是电源配置不对，需要的话我把dts 发上来。 刷TN3399的包刷上去了，正常启动。“附加驱动”和“软件和更新”这俩程序没反应，打不开。 发现一个新问题：板载的USB3.0接口无法使用，具体表现为USB3.0接口的U盘插上之后没反应，不识别，换到USB2.0的接口就能正常识别。这个怎么破？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

看来是会玩的那种的，鼓捣出来能分享一下就太好了。

**Comment by LioDon** [comment]
> > > 
> > 
> > 
> > > > > 你可能需要手搓dts了
> > > > 
> > > > 
> > > > 你太看得起我了......我哪有那水平............
> > > 
> > > 
> > > 我用dd 命令备份了这块板子的编程器固件，提取了安卓的dtb，反汇编了源码，但是不知道怎么手搓Ubuntu 或者op的dtb，编译了Firefly烧录到板子的emmc，内核启动后卡死，感觉是电源配置不对，需要的话我把dts 发上来。
> > 
> > 
> > 刷TN3399的包刷上去了，正常启动。"附加驱动"和"软件和更新"这俩程序没反应，打不开。
> 
> 发现一个新问题：板载的USB3.0接口无法使用，具体表现为USB3.0接口的U盘插上之后没反应，不识别，换到USB2.0的接口就能正常识别。这个怎么破？

硬件本身有问题，USB3.0在安卓下就不能用。还找商家确认过，他手里的剩余板子都是这副德行……这就有点儿坑了……

**Comment by yao-weijie** [comment]
@duxingkei33 @LioDon 两位手上有板子可以试试x99的固件，armbian的在ophub仓库里了，还有[LibreELEC](https://libreelec.tv/downloads/rockchip/)和[android tv9](http://files.kos.org.cn/rockchip/x99_t9/)，有个网友的3399电视盒子说是通刷x99固件，两位可以试一下

**Comment by jzhou404** [comment]
update-king3399-linux-ubuntu-hdmi-20211222-204849.img
硬解码可以去驱动起来， Jellyfin 可用

**Comment by alexzylcd** [comment]
![屏幕截图 2024-10-24 110535](https://github.com/user-attachments/assets/bc1d5876-6815-4b49-9200-30ea1e237952)
wifi ipex接口在这里，确定不是1代，和笔记本不通用，倒是和很多老手机适配。手机同点测试手机的天线模组比pcb天线好用，35-40db和50-60db差别。BT天线没找到，有可能和WiFi共用。

sim无反应，确定联通移动都不行，不知是不是电信的。usb3.0 V+没电压，不确定是不是坏的

![屏幕截图 2024-10-24 110646](https://github.com/user-attachments/assets/b3a334a4-7b59-40f3-8da7-e31d736c0e9b)
没搞懂j1602是啥接口，电压4v+,  5v power out 又不太像，求教

自带Android8貌似工程版，好像缺啥组件，很多app闪退或者用不了，字符编码识别、输入有bug，目测是os有问题

无高版安卓驱动，官网无支持，网上资料少。当个tv盒子用还凑合，其他就想多了
