### ISSUE TITLE
无法从u盘启动6.1系统

### ISSUE THREAD

**Issue by guanke1000** [ophub/amlogic-s9xxx-armbian#1310]
cm311-1a的盒子，目前为5.15，可以正常从U盘启动5.15但是6.1不行

**Comment by xxx854** [comment]
> cm311-1a的盒子，目前为5.15，可以正常从U盘启动5.15但是6.1不行

两个版本的内核时不一样的

**Comment by yanllllk** [comment]
同样无法U盘引导

**Comment by huangc205** [comment]
我的cm211-1好像也这样。修改些文件u盘启动，但装入emmc后还是无法启动。问题是5.15自带联网无法使用，6.1可以

**Comment by gametta** [comment]
CM211-1的可以试试这个  Armbian_23.05.0_amlogic_s905l2-e900v21e_bullseye_5.15.108_server_2023.04.23.img.gz
或者6.1核心的，我用的是6.1核心，选择122，一切正常，唯一的问题就是MAC一样，刷好几个都是同样的MAC。

**Comment by ophub** [comment]
5.15和6.1的区别是少了u-boot文件，如果6.1无法启动，说明u-boot不对，在/boot下有全部的u-boot，
在USB里测试，复制其他u-boot文件命名为u-boot.ext。重启测试
```
cd /boot
cp -f u-boot-xxxx.bin u-boot.ext
chmod +x u-boot.ext
sync
reboot
```
用5.15复制，只要有u-boot.ext就会启动时执行，添加错了就无法启动，把USB插在电脑上删除了u-boot.ext重新启动，继续复制其他的测试。

**Comment by huangc205** [comment]
Dear 大佬们
 我的盒子CM201-1 CH版，6.15 U盘无法启动，我复制一份extlinux.conf.bak，把。bak删除就可以启动了。
但安装armbian-install的时候报错：112 123 124都试过。


109   s905w      W95                            meson-gxl-s905w-p281.dtb        
110   s905w      X96-Mini                       meson-gxl-s905w-x96-mini.dtb    
--------------------------------------------------------------------------------------
111   s905x      TX9                            meson-gxl-s905x-tx9.dtb         
112   s905l3b    M302A,M304A,CM211-1,CM311-1    meson-gxl-s905l3b-m302a.dtb     
113   s905l2     MGV2000,MGV3000,M301A          meson-gxl-s905l2-x7-5g.dtb      
114   s905l2     Wojia-TV-IPBS9505              meson-gxl-s905l2-ipbs9505.dtb   
115   s905lb     Q96-mini                       meson-gxl-s905x-p212.dtb        
116   s905l3     CM311-1,HG680-LC,M401A         meson-gxl-s905l2-x7-5g.dtb      
117   s905l3b    E900V22E                       meson-gxl-s905l3b-e900v22e.dtb  
118   s905lb     BesTV-R3300L,SumaVision-Q7     meson-gxl-s905x-p212.dtb        
119   s905w      X96W,FunTV,MXQ-Pro-4K          meson-gxl-s905w-x96w.dtb        
120   s905l3b    E900V22D                       meson-gxl-s905l2-x7-5g.dtb      
--------------------------------------------------------------------------------------
121   s905l3     UNT400G1                       meson-gxl-s905l2-x7-5g.dtb      
122   s905l2     E900v21E                       meson-gxl-s905l2-x7-5g.dtb      
123   s905l3b    IP103H                         meson-gxl-s905l3b-m302a.dtb     
124   s905l3     CM211-1                        meson-gxl-s905l3b-m302a.dtb     
0     Other      Customize                      Enter-custom-dtb-name           
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 124
[ INFO ] Input Box ID: [ 124 ]
[ INFO ] FDTFILE: [ meson-gxl-s905l3b-m302a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-p212.bin ]
[ INFO ] NEED_OVERLOAD: [ yes ]
[ STEPS ] Start selecting file system type...
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] The type of file system: [ ext4 ]
[ STEPS ] Start creating eMMC partition...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.356289 s, 11.8 MB/s
[  156.230776]  mmcblk2: p1 p2
[ INFO ] Delete the existing [ 2 ] partitions.
[  156.438173]  mmcblk2: p2
[  156.589780]  mmcblk2:
[ INFO ] Start create MBR and partittion.
[  156.691773]  mmcblk2:
[  156.845243]  mmcblk2: p1
[  157.060407]  mmcblk2: p1 p2
[ INFO ] 03. Write the mybox bootloader: [ /usr/lib/u-boot/mybox-bootloader.img ]
444+0 records in
444+0 records out
444 bytes copied, 0.0043109 s, 103 kB/s
[  157.085878]  mmcblk2: p1 p2
8191+0 records in
8191+0 records out
4193792 bytes (4.2 MB, 4.0 [  157.516033]  mmcblk2: p1 p2
MiB) copied, 0.442588 s, 9.5 MB/s
[ STEPS ] Start processing the BOOTFS partition...
[ INFO ] Start formatting BOOTFS partition...
mkfs.fat 4.2 (2021-01-31)
[ INFO ] Start copy BOOTFS partition data.
[ INFO ] Update the [ uEnv.txt ] file.
[ INFO ] Update the [ extlinux.conf ] file.
[ INFO ] Copy [ u-boot-p212.bin ] to u-boot.emmc
[ STEPS ] Start processing the rootfs partition...
[ INFO ] Start formatting ROOTFS partition...
[  176.194774] EXT4-fs (mmcblk2p2): mounted filesystem with ordered data mode. Quota mode: none.
[ INFO ] Start copy ROOTFS partition data.
[ INFO ] Copy the [ etc ] directory.
[ INFO ] Copy the [ home ] directory.
[ INFO ] Copy the [ lib64 ] directory.
[ INFO ] Copy the [ opt ] directory.
[ INFO ] Copy the [ root ] directory.
[ INFO ] Copy the [ selinux ] directory.
[ INFO ] Copy the [ srv ] directory.
[ INFO ] Copy the [ usr ] directory.
[ INFO ] Copy the [ var ] directory.
[ INFO ] Generate the new fstab file.
[ INFO ] Update the relevant parameters.
[  337.512509] EXT4-fs (mmcblk2p2): unmounting filesystem.
[  359.011942] systemd-shutdown[1]: Syncing filesystems and block devices.
[  364.712518] systemd-shutdown[1]: Sending SIGTERM to remaining processes...
[  364.727071] systemd-journald[684]: Received SIGTERM from PID 1 (systemd-shutdow).
[  364.751751] EXT4-fs (zram1): unmounting filesystem.
[  364.763469] systemd-shutdown[1]: Sending SIGKILL to remaining processes...
[  364.779987] systemd-shutdown[1]: Unmounting file systems.
[  364.782745] [2110]: Remounting '/' read-only in with options 'errors=remount-ro,commit=600,data=writeback'.
[  364.866159] EXT4-fs (sda2): re-mounted. Quota mode: none.
[  364.899894] systemd-shutdown[1]: All filesystems unmounted.
[  364.899962] systemd-shutdown[1]: Deactivating swaps.
[  364.904997] systemd-shutdown[1]: All swaps deactivated.
[  364.910034] systemd-shutdown[1]: Detaching loop devices.
[  364.974852] systemd-shutdown[1]: All loop devices detached.
[  364.974913] systemd-shutdown[1]: Stopping MD devices.
[  364.980975] systemd-shutdown[1]: All MD devices stopped.
[  364.985100] systemd-shutdown[1]: Detaching DM devices.
[  364.990998] systemd-shutdown[1]: All DM devices detached.
[  364.995542] systemd-shutdown[1]: All filesystems, swaps, loop devices, MD devices and DM devices detached.
[  365.012661] systemd-shutdown[1]: Syncing filesystems and block devices.
[  365.014259] systemd-shutdown[1]: Powering off.
[  365.018097] kvm: exiting hardware virtualization
[  365.089368] reboot: Power down
INFO:    PSCI Affinity Map:
INFO:      AffInst: Level 0, MPID 0x0, State ON
INFO:      AffInst: Level 0, MPID 0x1, State ON
INFO:      AffInst: Level 0, MPID 0x2, State ON
INFO:      AffInst: Level 0, MPID 0x3, State ON
bl31 reboot reason: 0x1
bl31 reboot reason: 0x1
ECEC cfg:0x0000
set vddee to 0x0352mv
set vddee to 0x0352mv
power_off_at_24M
this uboot is for hw_1_8, update GPIODV_24 to 0
08915d0000000000detect_key4000

















在 2023-04-24 14:37:54，"ophub" ***@***.***> 写道：

5.15和6.1的区别是少了u-boot文件，如果6.1无法启动，说明u-boot不对，在/boot下有全部的u-boot，
在USB里测试，复制其他u-boot文件命名为u-boot.ext。重启测试

cd /boot
cp -f u-boot-xxxx.bin u-boot.ext
chmod +x u-boot.ext
sync
reboot


用5.15复制，只要有u-boot.ext就会启动时执行，添加错了就无法启动，把USB插在电脑上删除了u-boot.ext重新启动，继续复制其他的测试。

**Comment by yiqihongchen** [comment]
头大的很呀，不会U盘引导

**Comment by jamesbondjava** [comment]
> 5.15和6.1的区别是少了u-boot文件，如果6.1无法启动，说明u-boot不对，在/boot下有全部的u-boot， 在USB里测试，复制其他u-boot文件命名为u-boot.ext。重启测试
> 
> ```
> cd /boot
> cp -f u-boot-xxxx.bin u-boot.ext
> chmod +x u-boot.ext
> sync
> reboot
> ```
> 
> 用5.15复制，只要有u-boot.ext就会启动时执行，添加错了就无法启动，把USB插在电脑上删除了u-boot.ext重新启动，继续复制其他的测试。

大佬，修改名字后必须重新在armbian下给权限吗？我现在忘记原来的armbian密码了。
