### ISSUE TITLE
4K display output broken for X96 Max+ with both 5.x and 6.x kernels

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#1311]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC:  S905x3

 - Model: X96 Max+ (4GB RAM, 32 GB eMMC, Gbe)

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.107 and 6.1.24
 - Release:  jammy and bullseye

**Describe the bug | 问题描述**
If I boot the latest s905x3 images for jammy or bullseye with either the 5.15.107 or the 6.1.24 kernel on my X96 Max+, I do not get any picture when it is connected to my 4K TV but both latest kernels boot fine and output a display if I connect my X96 Max+ to an older, non 4K,monitor (using a HDMI -> DVI cable).

I have still got some older Armbian s9xxx images that use a 5.10 series kernel that DO work with my 4K TV so something broke in the Armbian s9xxx kernel config since then.

**Comment by ophub** [comment]
armbian-update -k 5.10.107

**Comment by danboid** [comment]
Thanks @ophub !

Yes, installing the latest 5.10 kernel (5.10.177) does fix 4K HDMI output on my X96 Max+, at least under bullseye so I presume it works under jammy too.

The problem here is that the user is required to have access to a non 4k display so that they can then install Armbian then revert to a 5.10 series kernel to get 4k working. 

Could you please provide S905X3 images that use the latest 5.10 kernel by default so that S905X3 users who only have a 4K display can still use Armbian without buying or borrowing a second display?

Thanks!

**Comment by ophub** [comment]
There are 4 kernels, each with different needs. armbian-update can be completed in just 1 minute without using any additional GitHub resources.

**Comment by danboid** [comment]
> There are 4 kernels, each with different needs. armbian-update can be completed in just 1 minute without using any additional GitHub resources.

Yes but its difficult to use armbian-update if you have no working HDMI.

**Comment by danboid** [comment]
OK thanks @ophub
