### ISSUE TITLE
Add support for: Bqeel MVR9

### ISSUE THREAD

**Issue by giovEra** [ophub/amlogic-s9xxx-armbian#1313]
Hi,
could you please add the support for Bqeel MVR9?
   
![MVR9](https://www.cnx-software.com/wp-content/uploads/2017/07/MVR9-TV-Box-Large.jpg)
   
It is a rockchip 3328 TV box and has been supported by [150balbes](https://github.com/150balbes).
150balbes has deleted the sources, but a fairly reccent fork is available here: [repo](https://github.com/SLAzurin/Build-Armbian-TV)

Info about MVR9: [infos](https://www.cnx-software.com/2017/07/14/bqeel-mvr9-tv-box-review-part-1-specifications-unboxing-and-teardown/)

If you need additional information I am available, please do not hesitate to ask.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

look at 12.15

need u-boot, dts
such as: https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/u-boot/rockchip/r66s

https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/rockchip/rk3568-opc-h66k.dts

**Comment by giovEra** [comment]
Hi @ophub, 
thank you for your response.

---

On [this mega.nz folder](https://mega.nz/folder/XT4nnISK#60UY65bDx4Ab1hdMPrV1TA) i've uploaded the files.
In detail:

- "Armbian_21.11.0-trunk_Station-m1_focal_current_5.10.62.img.xz": is the latest 150balbes firmware I have.
- "rk3328-box-trn9.dtb": is used for MVR9 in `etlinux.conf`:
```
LABEL Armbian
  LINUX /boot/Image
  INITRD /boot/uInitrd
  FDT /boot/dtb/rk3328-box-trn9.dtb
  APPEND root=UUID=96df9e27-d265-4cfe-bd03-f2c63f48f04f console=uart8250,mmio32,0xff130000 console=tty0 rootflags=data=writeback rw no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 bootsplash.bootfile=bootsplash.armbian
```
- "u-boot" folder: extracted from firmware, should be contain the bootloader according to [wiki](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#12153-add-u-boot-files)

---

I could not find the dts file, so I converted the rk3328-box-trn9.dtb file to dts, getting this [dts file](https://mega.nz/file/6LYgUJIB#5LiZlsy_rLtPLjKjzcz1Zs3QsBx2wfafyRzvAMbd3nk), please note that the conversion generated the following warnings:
```
rk3328-box-trn9.dts: Warning (unit_address_vs_reg): /usb@ff600000: node has a unit name, but no reg or ranges property
rk3328-box-trn9.dts: Warning (interrupt_provider): /pinctrl/gpio0@ff210000: Missing #address-cells in interrupt provider
rk3328-box-trn9.dts: Warning (interrupt_provider): /pinctrl/gpio1@ff220000: Missing #address-cells in interrupt provider
rk3328-box-trn9.dts: Warning (interrupt_provider): /pinctrl/gpio2@ff230000: Missing #address-cells in interrupt provider
rk3328-box-trn9.dts: Warning (interrupt_provider): /pinctrl/gpio3@ff240000: Missing #address-cells in interrupt provider
rk3328-box-trn9.dts: Warning (graph_child_address): /vop@ff370000/port: graph node has single child node 'endpoint@0', #address-cells/#size-cells are not necessary
```

The sources used by 150balbes to compile armbian for MVR9 are available [here](https://github.com/SLAzurin/Build-Armbian-TV), I think you can find more information about the dts.

---

I hope I have provided you with all the information you need. In case I have not, please do not hesitate to write to me

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_04.22.0119

try this

**Comment by giovEra** [comment]
Hi, and thank you.

I tried jammy and it seems to work.
Please give me a few days to do more thorough testing.

During startup dmesg prints some errors/warnings. If you want to take a look at it, you can get the log from [here](https://mega.nz/file/GLhT3AYT#fWETx-r-Az5cNSFn4K6mAQz01Msuw-vqjTom68Q1x78). The log is in html format to be easier to read as it keeps the syntax highlighting.

**Comment by ophub** [comment]
@giovEra 
I found the dts of this device in the kernel source code, you can test it, change the name of dtb in `/boot/armbianEnv.txt` to `rk3328-roc-pc.dtb`, then restart and try, if it can be used normally, use this in the future Easy to maintain and update.

**Comment by giovEra** [comment]
Hi @ophub,
I have tried dtb, but it does not work. At startup I get the following error:

[![photo-2023-05-02-16-56-08.jpg](https://i.postimg.cc/s2RpVdXd/photo-2023-05-02-16-56-08.jpg)](https://postimg.cc/TKCy9sgC)

Note: I checked and UUID of the partition and it is correct, I reset the name of dtb in /boot/armbianEnv.txt to rk3328-box-trn9.dtb and it boot correctly.

---

> I found the dts of this device in the kernel source code

Can you give me the link to the dts file you found?
Thanks

**Comment by ophub** [comment]
https://github.com/armbian/build/blob/main/config/boards/station-m1.conf

https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/rockchip/rk3328-roc-pc.dts

**Comment by giovEra** [comment]
Hey @ophub,
thanks for the hint.

Have a look here: [rk3328-box-trn9.dts](https://github.com/150balbes/rockchip-kernel/blob/master/arch/arm64/boot/dts/rockchip/rk3328-box-trn9.dts), can it help you?

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.10.y/blob/cefea81a9bba7599d0c7f13174b48b903c54ae7f/arch/arm64/boot/dts/rockchip/Makefile#L20

https://github.com/unifreq/linux-5.4.y/blob/15482dc43a91653aff69b8cea62353bf0d0083da/arch/arm64/boot/dts/rockchip/Makefile#L7

rk3328-box-trn9.dtb cannot be compiled normally in 5.10.y, and it is currently commented. I see that it can be compiled normally in 5.4.y
