### ISSUE TITLE
X96 Mini Plus

### ISSUE THREAD

**Issue by ngowuys** [ophub/amlogic-s9xxx-armbian#132]
Hi I got X96 Mini Plus, which using S905W4, 2GB of RAM, I tried some dtb files but all of them only recognize 1GB of RAM. I tried balbes150 images too, they all works fine but this repo is not. So is there anyway to fix that? Thank you for this project.

**Comment by ophub** [comment]
Which kernel version are you testing with? Is it correct in 5.15.

**Comment by ngowuys** [comment]
> Which kernel version are you testing with? Is it correct in 5.15？

I tested both 5.15 and 5.4, but they still not recognize 2GB of RAM, weird

**Comment by ophub** [comment]
Did you test on usb? Or write emmc test? Provide what configuration you are using. dtb and u-boot

**Comment by ngowuys** [comment]
> Did you test on usb? Or write emmc test? Provide what configuration you are using. dtb and u-boot
> 

I tested on both usb/sd card and emmc. About dtb I tried with 
- meson-glx-s905w-p281.dtb
- meson-glx_p281_2g.dtb // this cant boot
- meson-glx-s905w-tx3-mini.dtb
With uboot, tried default uboot and uboot-s905-s912

**Comment by ophub** [comment]
Which version of the firmware of balbes150 are you using, and which dtb and u-boot are you using?

**Comment by ophub** [comment]
meson-gxl-s905w-p281.dtb

**Comment by ngowuys** [comment]
> Which version of the firmware of balbes150 are you using, and which dtb and u-boot are you using?

I used meson-glx-p281.dtb and uboot-s905-s912 with armbian-20.10 bullseye. Tried to use them with your firmware but not work, I think they cant work with 5.4 kernel

**Comment by ophub** [comment]
`/boot/dtb/amlogic/meson-glx-p281.dtb`
You can test it, copy balbes150‘s this dtb, replace my file with the same name, and try again.

**Comment by ngowuys** [comment]
> `/boot/dtb/amlogic/meson-glx-p281.dtb` You can test it, copy the balbes150‘s dtb, replace my file with the same name, and try again.

Okay I'll try all files then let you know

**Comment by ngowuys** [comment]
> `/boot/dtb/amlogic/meson-glx-p281.dtb` You can test it, copy the balbes150‘s dtb, replace my file with the same name, and try again.

This one cant boot

> meson-gxl-s905w-p281.dtb meson-gxl-s905l2-p281.dtb meson-gxl-s905w-tx3-mini.dtb

These can boot but still 1GB of RAM instead of 2GB of RAM

**Comment by ophub** [comment]
You copied his dtb under 5.15 is also 1G?

**Comment by ngowuys** [comment]
> You copied his dtb under 5.15 is also 1G?

I tried with both 5.4 and 5.15 and cant boot with that dtb, I think I should try to modify dtb file memory node :/

**Comment by ngowuys** [comment]
> You copied his dtb under 5.15 is also 1G?

Hi, I think I found the problem. So armbian using nearly 1GB of RAM for zram0,1,2. So is there anyway to reduce zram usage? Thank you for create this project.
![IMG20220306095541](https://user-images.githubusercontent.com/42114171/156907259-f9f614b4-5a76-41ca-98db-e6c75355cb5b.jpg)

**Comment by ophub** [comment]
swap can be adjusted freely：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-swap
