### ISSUE TITLE
N1通过USB启动时提示XHCI timeout on event type 33，反复重启

### ISSUE THREAD

**Issue by zwillhill** [ophub/amlogic-s9xxx-armbian#1320]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905D]
 - Model [ 斐讯N1]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.108、6.1.24、6.1.25]
 - Release: [bullseye]

**Describe the bug | 问题描述**
最近刚入手N1，今天下载的几个版本包括bullseye5和6，以及jammy6（附图），通过usb启动时提示xhci time out on event type33，然后就反复重启循环（附截图）。
网上目前搜到的教程大多比较老，以个人搜到的结果而言，目前的新版针对n1似乎不需要替换**dtd**文件或修改**uEnv.txt**，看了下相应文件似乎也没有需要修改的。
机器原本是官方2.25固件，已降级，测试通过usb安装网友修改的旧版本armbian可以成功（版本号附图）。
![1](https://user-images.githubusercontent.com/18493504/233836201-6db2f74c-9378-4518-b58c-a41fb80fca6c.jpg)
![2](https://user-images.githubusercontent.com/18493504/233836210-c82ab49c-09b2-4258-97a7-71432511e8b4.jpg)
![3](https://user-images.githubusercontent.com/18493504/233836211-9fe7f76f-4a00-4a5d-919d-63d431c6d968.jpg)
![4](https://user-images.githubusercontent.com/18493504/233836214-4d41ca7b-4107-4cf2-ad6c-7cb7b5d2bf02.jpg)

**Comment by ophub** [comment]
传说中N1是调U盘的，但是很少有人反馈这个现象，难道你又发现了？换个U盘。

https://www.right.com.cn/forum/thread-901586-1-1.html

**Comment by zwillhill** [comment]
> 传说中N1是调U盘的，但是很少有人反馈这个现象，难道你又发现了？换个U盘。
> 
> https://www.right.com.cn/forum/thread-901586-1-1.html

听说过挑u盘，今天用的还是个杂牌，但能装旧版就没往u盘兼容上想。
没试过加电容，但尝试过有个帖子提到的插usb公对公线辅助供电。
明天换几个u盘试试。

**Comment by gametta** [comment]
我也有几个N1，刷的没什么问题，建议用5.15核心的，如果不追求新功能，稳定就好，两年前有人做了一个dtb文件，说可以减少负载什么的，也可以。

**Comment by SoraKasvgano** [comment]
接个USB2.0 HUB转EHCI

**Comment by zwillhill** [comment]
> USB2.0 HUB转EHCI



> 我也有几个N1，刷的没什么问题，建议用5.15核心的，如果不追求新功能，稳定就好，两年前有人做了一个dtb文件，说可以减少负载什么的，也可以。

第一次入手n1安装armbian，不折腾追新怎么行。

**Comment by zwillhill** [comment]
> 接个USB2.0 HUB转EHCI

看网上帖子有说接个带供电的hub是为了解决供电问题。
至于usb协议，出问题的u盘是杂牌2.0的，n1自带的usb接口好像也是2.0？出问题的xhci协议应该主要是usb3.0外加兼容2.0吧

**Comment by zwillhill** [comment]
测试结果：Sandisk Cruzer 8G可以正常启动，杂牌u盘加无电源的usb hub也可以正常启动。
另外发现usb键盘也会影响u盘启动，造成循环重启；
将armbian安装到emmc时，完成必要的输入后需要拔掉usb键盘，否则n1会黑屏关机，logo灯也灭了。

**Comment by ophub** [comment]
看来这还是个富贵病呢，像我这种没钱买键盘的就碰不到这种问题。看起来富人也有富人的烦恼啊。

**Comment by zwillhill** [comment]
> 看来这还是个富贵病呢，像我这种没钱买键盘的就碰不到这种问题。看起来富人也有富人的烦恼啊。

o大别开玩笑了，没键盘咋安装系统、选择型号和分区格式？咋设置密码？
不是机械键盘，单位里用的十几块的清华同方贴牌键盘，没想键盘也能出现兼容问题，想替换试试吧其它电脑用的基本是ps2口的，反正及时拔掉就行。

**Comment by shangjiyu** [comment]
我换个 5.15.133 内核版本的起来了，， 金士顿 (DT101 G2) 8G 的U盘，，， 还是我起来时候没插 键盘的原因？ 🤣
