### ISSUE TITLE
最近6.1核心MAC相同的问题。

### ISSUE THREAD

**Issue by gametta** [ophub/amlogic-s9xxx-armbian#1323]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: 905l3a  905L3B
 - Model ：B863AV-3.2M     B860-AV2.1-A2

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.25]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
最近一周使用6.1核心刷机的几台盒子B863AV-3.2M     B860-AV2.1-A2总是莫名的第二个找不到，反复刷，刷机过程一切正常，刷完后开机找不到，直到昨天我把在线的第一台机器拿到别的地方，中午再去刷第二台的时候也正常了，我仔细看了一下原来MAC一样冲突了，我以前刷863的时候用的是5.15核心，mac都是随机的，后来也用过6.1核心的，也没啥问题，直到最近一周的6.1（因为U盘被安卓设置文件属性了，重新下载新版6.1）出现问题了。
我也尝试修改/etc/netwok里面的文件，也不起作用。
如果哪位朋友有两台以上的机器可以刷一下试试。

**Comment by ophub** [comment]
以前我给每个机器生成一个随机mac地址，有些人不喜欢，就要原生的，所以删了。
按说原生的也不可能重了。
mac地址自定义的方法在文档里有。

**Comment by gametta** [comment]
我看到设备列表中没有 B860-AV2.1-A2，我用的是这个包
 Armbian_23.05.0_amlogic_s905l2-e900v21e_bullseye_6.1.25_server_2023.04.23.img.gz 。
选择122，暂时除了MAC相同之外，别的一切正常，网络正常，HDMI无输出。建议增加上去为更多的朋友提供帮助。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/23fe2e7a703d7bd1b7f3ffdcd7d6ebb1cd0da3bc
自己添加个差异化的MAC地址

**Comment by gametta** [comment]
source /etc/network/interfaces.d/*
# Network is managed by Network manager
auto lo
iface lo inet loopback
MYCON=eth0  
MYTYPE=ethernet
MYMAC=12:34:56:78:9A:BC

**Comment by ophub** [comment]
你这不是我发的

**Comment by gametta** [comment]
在/etc/network/interfaces.d建立interfaces 内容为自定义
auto eth0
allow-hotplug eth0
iface eth0 inet dhcp
hwaddress ether 12:34:56:78:9A:DA
成功。
另：刚才下载4月23号的两个文件刷，MAC仍然不会随机，好在上面解决了。

**Comment by ophub** [comment]
mac随机的功能已经删除了，这个众口难调，有要原生的有要自定义的
