### ISSUE TITLE
安装不上WireGuard

### ISSUE THREAD

**Issue by 68cs** [ophub/amlogic-s9xxx-armbian#1324]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905D]
 - Model [e.g. N1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.108]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Installing WireGuard, please wait...
+ apt-get -yqq update
+ apt-get -yqq install wireguard qrencode
E: Unable to correct problems, you have held broken packages.
Error: 'apt-get install' failed.

**Comment by ophub** [comment]
![Snip20230424_7](https://user-images.githubusercontent.com/68696949/233898889-e6771649-1b33-4eee-b975-6a54b6d3b4eb.png)
![Snip20230424_8](https://user-images.githubusercontent.com/68696949/233898899-6b4d959f-d170-4673-b4e1-cad8a90cc2b6.png)

**Comment by 68cs** [comment]
![Xnip2023-04-24_15-18-39](https://user-images.githubusercontent.com/25496213/233925892-a918f78d-18a4-4ebc-97a5-101b6f7a036d.png)

**Comment by ophub** [comment]
/etc/apt/sources.list
```
deb http://deb.debian.org/debian bullseye main contrib non-free
#deb-src http://deb.debian.org/debian bullseye main contrib non-free

deb http://deb.debian.org/debian bullseye-updates main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

deb http://deb.debian.org/debian bullseye-backports main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free

deb http://security.debian.org/ bullseye-security main contrib non-free
#deb-src http://security.debian.org/ bullseye-security main contrib non-free
```
