### ISSUE TITLE
请求适配SW799

### ISSUE THREAD

**Issue by inoeud** [ophub/amlogic-s9xxx-armbian#1326]
配置：
处理器 | RK3399， 双核 A72+四核 A53， 64 位， 1.8GHz
记忆 | 4 GB DDR3L 内存
存储 | 16 GB eMMC 5.1
无线技术 | 无线模块（AP6181/ BCM43362/1 wl0） 4G模块（YUGA CLM920）
捕获选项 | 与支持的移动设备建立蓝牙无线连接
连接 | USB 2.0 A 型 （×2） Type-C（usb3.0） RJ45 千兆以太网（RTL8211E） 音频接口（耳麦二合一）

OpenWrt、乌班图固件下载地址：
http://files.kos.org.cn/%E7%91%9E%E8%8A%AF%E5%BE%AE/sw799/?C=M&O=D

安卓固件反编译提取
[boot.dtb.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11319433/boot.dtb.txt)
[boot.dts.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11319416/boot.dts.txt)

**Comment by ophub** [comment]
rk3399-orangepi.dtb
用的这个dtb？

**Comment by inoeud** [comment]
> rk3399-sapphire-excavator.dtb rk3399-bozz.dtb 用的哪个dtb？

不清楚（抱歉），我用的默认固件（小媳妇那个），

**Comment by inoeud** [comment]
推测应该是rk3399-bozz.dtb

**Comment by inoeud** [comment]
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-rk3399
Could not get PHY for ethernet@fe300000: addr -1
Could not get PHY for ethernet@fe300000: addr -1
Could not get PHY for ethernet@fe300000: addr -1
Could not get PHY for ethernet@fe300000: addr -1
No ethernet found.

**Comment by ophub** [comment]
现在你刷的这个固件可以正常使用吧

**Comment by inoeud** [comment]
> 现在你刷的这个固件可以正常使用吧
可以，但是在更新后会报错，无法启动
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/default-arm-rk3399
Could not get PHY for ethernet@fe300000: addr -1
Could not get PHY for ethernet@fe300000: addr -1
Could not get PHY for ethernet@fe300000: addr -1
Could not get PHY for ethernet@fe300000: addr -1
No ethernet found.
可是我已经在armbian-config里面冻结内核了？
wifi似乎也无法使用（ap6236）

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_04.24.0239

下载试试

**Comment by inoeud** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_04.24.0239
> 
> 下载试试

搞错了，无线模块是ap6181

**Comment by inoeud** [comment]
RK3399大小核心似乎正确识别了，但A72的最高频只有1.8G这是啥原因？loader吗

Architecture:           aarch64
  CPU op-mode(s):       32-bit, 64-bit
  Byte Order:           Little Endian
CPU(s):                 6
  On-line CPU(s) list:  0-5
Vendor ID:              ARM
  Model name:           Cortex-A53
    Model:              4
    Thread(s) per core: 1
    Core(s) per socket: 4
    Socket(s):          1
    Stepping:           r0p4
    CPU max MHz:        1416.0000
    CPU min MHz:        408.0000
    BogoMIPS:           48.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
  Model name:           Cortex-A72
    Model:              2
    Thread(s) per core: 1
    Core(s) per socket: 2
    Socket(s):          1
    Stepping:           r0p2
    CPU max MHz:        1800.0000
    CPU min MHz:        408.0000
    BogoMIPS:           48.00
    Flags:              fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
Vulnerabilities:        
  Itlb multihit:        Not affected
  L1tf:                 Not affected
  Mds:                  Not affected
  Meltdown:             Not affected
  Mmio stale data:      Not affected
  Retbleed:             Not affected
  Spec store bypass:    Vulnerable
  Spectre v1:           Mitigation; __user pointer sanitization
  Spectre v2:           Vulnerable
  Srbds:                Not affected
  Tsx async abort:      Not affected

**Comment by inoeud** [comment]
wifi正常使用，没问题

**Comment by ophub** [comment]
没dts源码，你反编译dtb改改吧，但是超频了会不稳定。

**Comment by inoeud** [comment]
开机有一些关于usb和网卡的报错，这些能修复的吗？

[    1.049754] rk_gmac-dwmac fe300000.ethernet: cannot get clock clk_mac_speed

[   14.088250] OF: graph: no port node found in /i2c@ff3d0000/fusb302@22
[   14.092934] rkvdec ff660000.video-codec: Adding to iommu group 1
[   14.103373] brcmfmac: F1 signature read @0x18000000=0x1591a962
[   14.125972] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43362-sdio for chip BCM43362/1
[   14.1278

[   14.255160] usb 1-1: can't set config #1, error -71
[   14.257756] usb usb1-port1: disabled by hub (EMI?), re-enabling...
[   14.258419] usb 1-1: USB disconnect, device number 23
[   14.263405] systemd[1]: Finished Armbian leds state.
[   14.388218] zram: Added device: zram0
[   14.391027] zram: Added device: zram1
[   14.392083] zram: Added device: zram2
[   14.432736] brcmfmac: brcmf_c_process_clm_blob: no clm_blob available (err=-2), device may have limited channels available
[   14.434245] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43362/1 wl0: Sep 18 2018 23:59:04 version 5.90.247 FWID 01-0

[   14.691987] usb 1-1: device descriptor read/64, error -71
[   14.703635] EXT4-fs (zram1): mounted filesystem without journal. Quota mode: none.
[   14.947958] usb 1-1: device descriptor read/64, error -71
[   15.184069] usb 1-1: new high-speed USB device number 25 using ehci-platform
[   15.744170] usb 1-1: device not accepting address 25, error -71
[   15.744861] usb usb1-port1: attempt power cycle
[   16.156182] usb 1-1: new high-speed USB device number 26 using ehci-platform
[   16.186740] usb 1-1: New USB device found, idVendor=1a40, idProduct=0101, bcdDevice= 1.11
[   16.187554] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[   16.188280] usb 1-1: Product: USB 2.0 Hub
[   16.190226] hub 1-1:1.0: USB hub found
[   16.191044] hub 1-1:1.0: 4 ports detected
[   16.296249] usb usb1-port1: disabled by hub (EMI?), re-enabling...
[   16.296858] usb 1-1: USB disconnect, device number 26
[   16.301492] hub 1-1:1.0: hub_ext_port_status failed (err = -71)
[   16.503208] systemd[1]: Finished Armbian memory supported logging.
[   16.529199] systemd[1]: Starting Journal Service...
[   16.576014] usb 1-1: new high-speed USB device number 27 using ehci-platform
[   16.674078] systemd[1]: Started Journal Service.
[   16.712307] systemd-journald[768]: Received client request to flush runtime journal.
[   16.824159] RPC: Registered named UNIX socket transport module.
[   16.824709] RPC: Registered udp transport module.
[   16.825135] RPC: Registered tcp transport module.
[   16.825549] RPC: Registered tcp NFSv4.1 backchannel transport module.
[   17.127973] usb 1-1: device not accepting address 27, error -71
[   17.258491] usb 1-1: new high-speed USB device number 28 using ehci-platform
[   17.412095] rd 0-5: Disabling EAS, schedutil is mandatory
[   17.425318] usb 1-1: unable to read config index 0 descriptor/all
[   17.425370] usb 1-1: can't read configurations, error -71
[   17.425511] usb usb1-port1: attempt power cycle
[   17.829023] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[   17.831620] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [RTL8211E Gigabit Ethernet] (irq=POLL)
[   17.836003] usb 1-1: new high-speed USB device number 29 using ehci-platform
[   17.876842] usb 1-1: device descriptor read/8, error -71
[   18.017757] usb 1-1: device descriptor read/8, error -71
[   18.252150] usb 1-1: new high-speed USB device number 30 using ehci-platform
[   18.292700] usb 1-1: device descriptor read/8, error -71
[   18.444075] usb 1-1: device descriptor read/8, error -71
[   18.552180] usb usb1-port1: unable to enumerate USB device

**Comment by ophub** [comment]
这个板子是不是2.0的usb

**Comment by inoeud** [comment]
> 这个板子是不是2.0的usb

usb2.0 俩个，usb3.0 一个，还有一个usb3.0四户没有引出来，或者是那个micro-b形状？

**Comment by inoeud** [comment]
> u-boot使用的是其他开发版的，dtb是怎么来的呢？固件是哪个大佬分享的，问他要个dts源文件方便随时修改。

看一下上边的回复呀~
dts一开始就上传啦
（https://github.com/ophub/amlogic-s9xxx-armbian/files/11306642/default.zip）

**Comment by 1Mirros** [comment]
> > 这个板子是不是2.0的usb
> 
> usb2.0 俩个，usb3.0 一个，还有一个usb3.0似乎没有引出来，或者是那个micro-b形状？
> 
> dts我已经上传了。在最上边。
> https://github.com/ophub/amlogic-s9xxx-armbian/files/11306642/default.zip
> 
> ![d89f02999ac2bfbfecb6aab84c8d275](https://user-images.githubusercontent.com/37056214/233932469-2eb24179-e6c9-4288-91c1-4e637b6c1873.jpg)
> ![c1eda50e3f60723c74fbf4a3cd54d44](https://user-images.githubusercontent.com/37056214/233932483-dbca4af6-f2b4-497e-985c-76c9ff1779f6.jpg)
> ![babf607af2b431acd047ded1ca675e8](https://user-images.githubusercontent.com/37056214/233932490-a95ad2b7-2067-4824-ba0b-c9e9bdb85395.jpg)
> mlogic-s9xxx-armbian/files/11306642/default.zip
> [图片]

啥ttl？好用么？

**Comment by inoeud** [comment]
> 你那是个dtb反编译的文件，不是源码。 小改下局部可以，调整设置看着费劲。

w我想办法找找吧

**Comment by ophub** [comment]
这个是安卓系统的解包

**Comment by Bixan** [comment]
您好 这个固件在4G+8G的配置上下载失败 是什么原因呀

**Comment by inoeud** [comment]
> 这个是安卓系统的解包

[boot.dts.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11316116/boot.dts.txt)
这是我从boot.img里面提取的dts，能力有限，只能做到这一步了。

**Comment by inoeud** [comment]
> 您好 这个固件在4G+8G的配置上下载失败 是什么原因呀

应该不至于吧？建议检查烧录姿势。

**Comment by inoeud** [comment]
有线网这块似乎有问题？不知道为啥，有时候会无故重启，已经遇到两次？不知道要如何查看重启原因。

**Comment by Bixan** [comment]
大佬 可以加入 AP6236无线模块的驱动吗

**Comment by ophub** [comment]
没有dts不好改，如果内核里有驱动，手动加载模块试试，可以在启动里加一个默认加载

**Comment by Bixan** [comment]
> 没有dts不好改，如果内核里有驱动，手动加载模块试试，可以在启动里加一个默认加载

好的

**Comment by starskyzheng** [comment]
sw799a 无hdmi的版本。系统烧录在sd卡，开机后有线网联不通，用 http://files.kos.org.cn/rockchip/sw799/Armbian_21.08.1_sw799_focal_current_5.10.60-linge.7z 是正常的。
板子没有hdmi，也看不出为啥会这样。

大佬，这儿有个dts，请问可以试试这个嘛？
http://files.kos.org.cn/rockchip/sw799/%E5%8E%9F%E7%89%88%E5%8F%8D%E7%BC%96%E8%AF%91.dts

**Comment by ophub** [comment]
用你发的这个固件里的dtb更新了，你试试刚打包的这个：

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.06/Armbian_23.08.0_rockchip_sw799_jammy_6.1.35_2023.06.25.img.gz

**Comment by starskyzheng** [comment]
很奇怪，还是一样不行
ping的时候，笔记本网口和板子网口的灯都在闪，就是ping不通，nmap也不通

**Comment by chamoyo** [comment]
这块核心板马上就出新的双网口底板，有HDMI，有USB3，到时候再研究吧

**Comment by sters-for-watching** [comment]
AP6236可以运行吗？我有一个二号主板，上面是AP6236

**Comment by 67113513** [comment]
大佬还有AP6236能用的img包吗？好像不论那种ap6xxx，dts中都是配置ap6354，是brcm自动识别的吗？

**Comment by whirly-eagle** [comment]
> 大佬还有AP6236能用的img包吗？好像不论那种ap6xxx，dts中都是配置ap6354，是brcm自动识别的吗？
> 
> PS：6236问题解决了，一开始根据树莓派的链接拷贝brcm43436，web上有无线菜单但是没有信号。后来看到armbian上配置的是brcm43436b0，把firmware拷贝过来就可以用了。但是网速太慢

具体怎么做，我复制firmware以后依然没有wifi

**Comment by 67113513** [comment]
> > 大佬还有AP6236能用的img包吗？好像不论那种ap6xxx，dts中都是配置ap6354，是brcm自动识别的吗？
> > PS：6236问题解决了，一开始根据树莓派的链接拷贝brcm43436，web上有无线菜单但是没有信号。后来看到armbian上配置的是brcm43436b0，把firmware拷贝过来就可以用了。但是网速太慢
> 
> 大佬，具体怎么做，我复制了firmware以后依然没有wifi

好像是在/lib/firmware/brcm 目录下面创建链接，链接名称是根据dmesg中记录的系统需要的文件名称。

**Comment by shiguangyilao** [comment]
SW799原版（非提取）固件+烧录软件+烧录方法
链接：https://pan.baidu.com/s/1hMptnVWtDfAKirZsfUqTDw 
提取码：g2m1

**Comment by 67113513** [comment]
> SW799原版（非提取）固件+烧录软件+烧录方法 链接：https://pan.baidu.com/s/1hMptnVWtDfAKirZsfUqTDw 提取码：g2m1

大佬有没有源码可以分享，方便自己做定制。

**Comment by shiguangyilao** [comment]
> > SW799原版（非提取）固件+烧录软件+烧录方法 链接：https://pan.baidu.com/s/1hMptnVWtDfAKirZsfUqTDw 提取码：g2m1
> 
> 大佬有没有源码可以分享，方便自己做定制。

目前搞不来，不过我知道这个板都是深圳博时特出的。

**Comment by shiguangyilao** [comment]
> > SW799原版（非提取）固件+烧录软件+烧录方法 链接：https://pan.baidu.com/s/1hMptnVWtDfAKirZsfUqTDw 提取码：g2m1
> 
> 大佬有没有源码可以分享，方便自己做定制。



> > SW799原版（非提取）固件+烧录软件+烧录方法 链接：https://pan.baidu.com/s/1hMptnVWtDfAKirZsfUqTDw 提取码：g2m1
> 
> 大佬有没有源码可以分享，方便自己做定制。

源码太难搞了。

**Comment by pewee-live** [comment]
烧录了以后有报错,然后就卡在这了进不去 命令行
<img width="1556" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/22680266/a69d74f7-92e1-421b-9177-f5576080b739">

**Comment by dutong0321** [comment]
我来做个反馈，我的板子是SW7990K VER1.4(带核心板SW799A VER1.2)
模型：SW7990K VER1.4(带核心板SW799A VER1.2)，之前烧6.X内核无法启动，今天烧写了Armbian_23.11.0_rockchip_sw799_bookworm_5.15.140_server_2023.12.01.img版本，已经成功了，非常感谢大佬的开源

**Comment by ophub** [comment]
好的，感谢反馈

**Comment by ophub** [comment]
armbian-config 选项蓝牙，安装，重启

**Comment by heruigit** [comment]
> armbian-config 选项蓝牙，安装，重启

试过了，重启之后用hciconfig -a 打印蓝牙信息为空😭

**Comment by 67113513** [comment]
拷贝对应的firmware到/lib/firmware/brcm目录下了吗

**Comment by heruigit** [comment]
反馈一下，修改了dtb中的serial@ff180000节点
	serial@ff180000 {
		compatible = "rockchip,rk3399-uart\0snps,dw-apb-uart";
		reg = <0x00 0xff180000 0x00 0x100>;
		clocks = <0x08 0x51 0x08 0x160>;
		clock-names = "baudclk\0apb_pclk";
		interrupts = <0x00 0x63 0x04 0x00>;
		reg-shift = <0x02>;
		reg-io-width = <0x04>;
		pinctrl-names = "default";
		pinctrl-0 = <0x3f 0x40 0x41>;
		status = "okay";
		bluetooth {
			compatible = "brcm,bcm43438-bt";
			clocks = <0xba 0x01>;
			clock-names = "lpo";
			device-wakeup-gpios = <0x87 0x1a 0x00>;
			host-wakeup-gpios = <0x22 0x04 0x00>;
			shutdown-gpios = <0x22 0x09 0x00>;
			max-speed = <4000000>;
			pinctrl-names = "default";
			pinctrl-0 = <0xc7 0xc8 0xc9>;
			vbat-supply = <0x16>;
			vddio-supply = <0x77>;
		};
	};
在pinctrl中增加
		bt {
			bt_host_wake_l: bt-host-wake-l {
				rockchip,pins = <0x00 0x04 0x00 0xb3>;
				phandle = <0xc7>;
			};

			bt_reg_on_h: bt-reg-on-h {
				rockchip,pins = <0x00 0x09 0x00 0xb3>;
				phandle = <0xc8>;
			};

			bt_wake_l: bt-wake-l {
				rockchip,pins = <0x02 0x1a 0x00 0xb3>;
				phandle = <0xc9>;
			};
		};
可以成功驱动蓝牙了。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/10793006/68ae9dcc-6e40-4b91-88d2-972fea16e917)

**Comment by ophub** [comment]
@heruigit 测试好了，上传分享一个你修改的dtb文件。

**Comment by DenisDangt** [comment]
> > 很奇怪，还是一样 打不通的时候，笔记本网口和板子网口的灯都闪，就是ping不通，nmap也不通
> 
> 需禁用USB网卡（它那个4G模块是挂在USB下的）

大佬，怎么禁用usb网卡？

**Comment by heruigit** [comment]
> @heruigit 测试好了，上传分享一个你修改的dtb文件。

@ophub 

修改的diff:
```
root@armbian:~# diff new.txt origin.txt
681,693d680
<               bluetooth {
<                       compatible = "brcm,bcm43438-bt";
<                       clocks = <0xba 0x01>;
<                       clock-names = "ext_clock";
<                       device-wakeup-gpios = <0x87 0x1a 0x00>;
<                       host-wakeup-gpios = <0x22 0x04 0x00>;
<                       shutdown-gpios = <0x22 0x09 0x00>;
<                       max-speed = <4000000>;
<                       pinctrl-names = "default";
<                       pinctrl-0 = <0xc7 0xc9>;
<                       vbat-supply = <0x16>;
<                       vddio-supply = <0x77>;
<               };
2351,2362d2337
<
<               bt {
<                       bt_host_wake_l: bt-host-wake-l {
<                               rockchip,pins = <0x00 0x04 0x00 0xb3>;
<                               phandle = <0xc7>;
<                       };
<
<                       bt_wake_l: bt-wake-l {
<                               rockchip,pins = <0x02 0x1a 0x00 0xb3>;
<                               phandle = <0xc9>;
<                       };
<               };
```
修改之后的dts：
[new.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/14100443/new.txt)
修改之后的dtb：
[new.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14100452/new.zip)

**Comment by ophub** [comment]
感谢分享，已经更新到仓库了。

**Comment by EXIA18** [comment]
Armbian_23.11.0_rockchip_sw799_bookworm_5.15.140_server_2023.12.01.img 谁提供一下这个包

**Comment by EXIA18** [comment]
> 我来做个反馈，我的板子是SW7990K VER1.4(带核心板SW799A VER1.2) 模型：SW7990K VER1.4(带核心板SW799A VER1.2)，之前烧6.X内核无法启动，今天烧写了Armbian_23.11.0_rockchip_sw799_bookworm_5.15.140_server_2023.12.01.img版本，已经成功了，非常感谢大佬的开源

求这个包

**Comment by gdanmac** [comment]
能更新的最新的6 内核吗 5.15内核老是断流。。。。

**Comment by thiesymon** [comment]
> 配置： 处理器 | RK3399， 双核 A72+四核 A53， 64 位， 1.8GHz 记忆 | 4 GB DDR3L 内存 存储 | 16 GB eMMC 5.1 无线技术 | 无线模块（AP6181/ BCM43362/1 wl0） 4G模块（YUGA CLM920） 捕获选项 | 与支持的移动设备建立蓝牙无线连接 连接 | USB 2.0 A 型 （×2） Type-C（usb3.0） RJ45 千兆以太网（RTL8211E） 音频接口（耳麦二合一）
> 
> OpenWrt、乌班图固件下载地址： http://files.kos.org.cn/%E7%91%9E%E8%8A%AF%E5%BE%AE/sw799/?C=M&O=D
> 
> 安卓固件反编译提取 [boot.dtb.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11319433/boot.dtb.txt) [boot.dts.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11319416/boot.dts.txt)

你好！ 固件下载地址已不可用可以再分享一份吗

**Comment by bi9bi9bee** [comment]
大佬，在固件里面打包屏幕和触摸的驱动不，wifi啥都是正常的，就是不亮屏。
触摸芯片是goodix GT928，屏幕芯片就不知道了，就是sw779底板上的排线接口。
![6104072ce2a34c5347f94660e79628e](https://github.com/ophub/amlogic-s9xxx-armbian/assets/41161225/1d43dfcd-b302-4da3-b076-5c1edb43470a)
![805d0c16527a87969cf039675db3f16](https://github.com/ophub/amlogic-s9xxx-armbian/assets/41161225/908ca86c-8d06-48ee-b32d-db315b9a5e48)

**Comment by 217heidai** [comment]
大佬，网卡启动不了，帮忙看下。  
核心板：SW3399-CB-V10-TY-A2  
底板：SW7990K Ver1.2  
启动报错日志：  
```bash
[   22.935363] rk_gmac-dwmac fe300000.ethernet: Failed to reset the dma
[   22.935967] rk_gmac-dwmac fe300000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   22.936778] rk_gmac-dwmac fe300000.ethernet eth0: __stmmac_open: Hw setup failed
[   22.982927] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[   22.990298] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [YT8521 Gigabit Ethernet] (irq=POLL)
````

**Comment by YangYangyou-Zhang** [comment]
老师你好，是这样的，我烧录固件后发现开发板已经自行连接到有线路由器，但不知道ssh的默认账户名与密码，这个是只能通过串口调试嘛？RK3399的4+64G版本的

**Comment by ophub** [comment]
默认账号：
root
1234

**Comment by gdanmac** [comment]
可以升级到最新的6.6.55的内核吗 之前的F内核出现UDP 断流？

**Comment by nkciam** [comment]
Hi guys, Do you have any guide install Ubuntu or Android on product above SW799 RK3399

**Comment by pewee-live** [comment]
> Hi guys, Do you have any guide install Ubuntu or Android on product above SW799 RK3399?
 
you can install android by this video;i tested orangePI4B android image work.

https://www.bilibili.com/video/BV16u4y1375d/?spm_id_from=333.337.search-card.all.click&vd_source=2db9856c46055c0a0259da9d9aff0583

**Comment by DenisDangt** [comment]
> > 很奇怪，还是一样 打不通的时候，笔记本网口和板子网口的灯都闪，就是ping不通，nmap也不通
> 
> 需禁用USB网卡（它那个4G模块是挂在USB下的）
@hhhfsj 大佬，怎么禁用USB网卡？

**Comment by EXIA18** [comment]
***@***.***
            
        
     
        
  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2024年11月6日 14:08
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ophub/amlogic-s9xxx-armbian] 请求适配SW799 (Issue #1326)
        
      
    
  



很奇怪，还是一样 打不通的时候，笔记本网口和板子网口的灯都闪，就是ping不通，nmap也不通

需禁用USB网卡（它那个4G模块是挂在USB下的）
@hhhfsj 大佬，怎么禁用USB网卡？

**Comment by shabby2333** [comment]
> 大佬，网卡启动不了，帮忙看下。 核心板：SW3399-CB-V10-TY-A2 底板：SW7990K Ver1.2 启动报错日志：
> 
> ```shell
> [   22.935363] rk_gmac-dwmac fe300000.ethernet: Failed to reset the dma
> [   22.935967] rk_gmac-dwmac fe300000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
> [   22.936778] rk_gmac-dwmac fe300000.ethernet eth0: __stmmac_open: Hw setup failed
> [   22.982927] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
> [   22.990298] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [YT8521 Gigabit Ethernet] (irq=POLL)
> ```

我也是同样的网卡，启动不了，大佬有方案了么

**Comment by tan73123** [comment]
sw799我下载了好几个版本 都无法启动

**Comment by EXIA18** [comment]
你那下的，是固件不启动还是网卡不启动




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2026年1月2日(星期五) 上午9:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] 请求适配SW799 (Issue #1326)



tan73123 left a comment (ophub/amlogic-s9xxx-armbian#1326)
 
sw799我下载了好几个版本 都无法启动

**Comment by EXIA18** [comment]
那不就行了，这个里面都是精华




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2026年1月2日(星期五) 上午9:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] 请求适配SW799 (Issue #1326)



tan73123 left a comment (ophub/amlogic-s9xxx-armbian#1326)
 
刷入https://files.kos.org.cn/rockchip/sw799/里面的版本都是可以正常 启动的

**Comment by tan73123** [comment]
板子背面的
tf卡无法识别

**Comment by EXIA18** [comment]
什么地板，原装的？




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2026年1月2日(星期五) 晚上6:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] 请求适配SW799 (Issue #1326)



tan73123 left a comment (ophub/amlogic-s9xxx-armbian#1326)
 
板子背面的
 tf卡无法识别

**Comment by shabby2333** [comment]
> 大佬，网卡启动不了，帮忙看下。 核心板：SW3399-CB-V10-TY-A2 底板：SW7990K Ver1.2 启动报错日志：
> 
> [   22.935363] rk_gmac-dwmac fe300000.ethernet: Failed to reset the dma
> [   22.935967] rk_gmac-dwmac fe300000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
> [   22.936778] rk_gmac-dwmac fe300000.ethernet eth0: __stmmac_open: Hw setup failed
> [   22.982927] rk_gmac-dwmac fe300000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
> [   22.990298] rk_gmac-dwmac fe300000.ethernet eth0: PHY [stmmac-0:00] driver [YT8521 Gigabit Ethernet] (irq=POLL)

AI修改的patch在 YT8521网卡上可用，不确定是否会对其他网卡的sw799产生影响
上传patch与dtb文件

[0001-arm64-dts-rockchip-rk3399-sw799-fix-GMAC-DMA-reset-f.patch](https://github.com/user-attachments/files/25708150/0001-arm64-dts-rockchip-rk3399-sw799-fix-GMAC-DMA-reset-f.patch)

[rk3399-bozz-sw799.zip](https://github.com/user-attachments/files/25708162/rk3399-bozz-sw799.zip) #
