### ISSUE TITLE
创维skyworth E900V21E 卡在get_defs_info 0001

### ISSUE THREAD

**Issue by tongsuh** [ophub/amlogic-s9xxx-armbian#1327]
**Device Information | 设备信息**
 - SOC: 大概率是S905L3B （由于被散热片紧密覆盖，无法拆开确定，不过之前刷写过一个SOC要求是S905L3B的盒子系统，是可以正常使用的，故判断为该型号
 - Model：四川电信，创维skyworth E900V21E
 - 内存：9FP75D9SHD   硬盘：SEC 913B041 kLM8G1GETF     WIFI: MTK MT7668
 -  - 附上主板照片：
![842d58是7b3d5db525e3ea012f128c89b](https://user-images.githubusercontent.com/45163974/233926437-1dc142f3-f802-407b-b065-78afbb6fa141.jpg)
![34a9db0f7be6011a48aece880788b00](https://user-images.githubusercontent.com/45163974/233926521-6eb8d152-f612-4d83-926e-d4844e5659e6.jpg)

**Armbian Version | 系统版本**

 - Release: Armbian_23.05.0_amlogic_s905l3b_jammy_6.1.25_server_2023.04.22.img

**Describe the bug | 问题描述**

卡在get_defs_info 0001

某次成功进入系统：
去掉extlinx.conf.bak的bak后最，修改uEnv和extlinux中的FDT为meson-gxl-s905l3b-e900v22e.dtb后，显示BUFFER I/O error
不过重启后又卡在了get_defs_info 0001

请教一下，是我固件选择的有问题还是什么可能的原因？

**操作流程**

通过ttl连接电脑putty

下载上述release后烧录进sd卡，插进机顶盒重启会卡在下图 get_defs_info 0001
![Untitled](https://s3-us-west-2.amazonaws.com/secure.notion-static.com/b967ea57-42ee-4e45-92ce-d8b9f17ec394/Untitled.png)

接着我修改了烧录u盘中uEnv.txt和extlinux.conf.bak:
1.把uEnv.txt的FDT改为FDT=/dtb/amlogic/meson-gxl-s905l3b-e900v22e.dtb
2.把extlinux.conf.bak 改为 extlinux.conf 然后将其中的FDT信息同样改为/dtb/amlogic/meson-gxl-s905l3b-e900v22e.dtb

重新插入机顶盒，并重启，能够进入ARMbian了
显示buffer IO error，如下图
![image](https://user-images.githubusercontent.com/45163974/233924710-5d7b8ce7-cc45-4682-a844-6bbd3dd8fc71.png)

但是在我输入reboot命令重启后，又卡在了get_defs_info 0001

已经换过meson-gxl-s905l2-e900v21e.dtb以及Armbian_23.05.0_amlogic_s905l2-e900v21e_bullseye_6.1.25_server_2023.04.23.img
都是一样卡在get_defs_info 0001或者[BL31] : tee size: 0

纯纯小白，如果有些问题问的很低级的话，多担待，感谢感谢。

**Comment by tongsuh** [comment]
有张图片上传错误，补一下
![image](https://user-images.githubusercontent.com/45163974/233939590-df3c3c0a-14d3-4493-ac87-5f57a30b6a58.png)

**Comment by ophub** [comment]
这可能是需要降频，看文档12.16
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

**Comment by tongsuh** [comment]
以及一个愚蠢的问题想要请教一下，我不想把armbian写入emmc，因为听说后面刷回来会比较难。所以请问下，是不是在内存卡中进入armbian的系统后就已经安装完成，可以直接使用了？如下图是否已经成功的安装了armbian？
![image](https://user-images.githubusercontent.com/45163974/233973973-efe69b85-fbc9-491d-af9e-75c685c3e80f.png)

**Comment by tongsuh** [comment]
> 谢谢回复，目前能够进入armbian系统了。 1.更换了一个新的sd卡 2.使用Armbian_23.05.0_amlogic_s905l3b_jammy_6.1.25_server_2023.04.22.img镜像 3.并将uEnv和extlinus.conf中的FDT更改为meson-gxl-s905l3b-e900v22e.dtb
> 
> 不过在系统中使用nmcli连接wifi时发现并没有wifi的设备，不知道是否是因为固件中没有MT7668对应的驱动？
> 
> 想请教一下，有没有什么办法让wifi运行起来，感谢
