### ISSUE TITLE
关于cm311 1a yst 刷机问题，求助。

### ISSUE THREAD

**Issue by mutuyihao** [ophub/amlogic-s9xxx-armbian#1328]
**Device Information | 设备信息**
 - SOC:S095x2，S095x3
 - Model cm311-1a-yst 

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.107]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
我是cm311 1a yst。
一开始是直接u盘刷armbian到emmc，从emmc正常启动armbian没问题。
然后因为没法驱动wifi，所以去安装了coreelec。
因为安装了armbian就没办法从u盘启动安装，所以我就在emmc armbian上输入命令df，然后把/boot 给unmont 并且给格式化了具体命令是 umount /dev/mmcblk2p1 mkfs.ext4 /dev/mmcblk2p1，然后插入coreelec的u盘可以启动了，但是用命令写到emmc上，也没法从emmc启动。
现在盒子就只可以进u盘的coreelec系统，或者进安卓的recovery模式（忘记从哪找到个recovery.img，扔u盘里就能进去。画面是有个安卓机器人在那，然后有双清选项，但是点双清全都是错误，提示找不到路径。选择从u盘 update.zip升级 也是报错，找不到什么路径。如果需要，还可以进去，拍照。）。
后边不知道怎么搞了。感觉应该先想办法刷回安卓系统。但是短接连接电脑，设备管理器里有显示，但是usb burning tool里不显示。

**Comment by ophub** [comment]
你可以U盘启动cl，用它重新安装armbian，或者dd别的系统

**Comment by mutuyihao** [comment]
> 你可以U盘启动cl说明没有砖了，重新U盘安装armbian，或者dd别的系统

我试过重新用rufus写armbian img到u盘，黑屏。进不去安装。 但是用coreelec改完dtb.img 可以引导。dd系统时候能安装到emmc上吗？主要感觉自己把引导（/boot）给unmount，还给格式化了，是不是因为这个导致的，有啥修复的方法吗？我用u盘启动coreelec进去df，不显示mmcblk2p1这个空间了。

**Comment by mutuyihao** [comment]
> 你可以U盘启动cl说明没有砖了，重新U盘安装armbian，或者dd别的系统

u盘启动core，然后用ceemmc -x 安装到emmc上，不报错，但是拔掉u盘重启，也是黑屏进不去系统。必须插着u盘才能进。找了个脚本dd系统，但是因为core系统是只读的，卡住了。O佬推荐下能用的脚本可以吗？

**Comment by mutuyihao** [comment]
> 你可以U盘启动cl说明没有砖了，重新U盘安装armbian，或者dd别的系统

大佬，我怀疑是这个原因。

https://www.znds.com/tv-1194265-1-1.html

但是我按照他的修改了aml好像也没用。估计要用那个恢复默认env的。

**Comment by mutuyihao** [comment]
> 你可以U盘启动cl说明没有砖了，重新U盘安装armbian，或者dd别的系统

大佬解决了。虽然不是u盘装或者dd。我把双公头线插到机箱后边的主板接口软件就读到了。之前刷n1时候，前置面板的usb能读到，我就一直用的前置。现在直接线刷了个安卓tv固件过去覆盖。又恢复刚买来的样子了。可以u盘启动armbian。完美。谢谢大佬了！
