### ISSUE TITLE
HK1box usb3.0 is unstable

### ISSUE THREAD

**Issue by zvzl** [ophub/amlogic-s9xxx-armbian#133]
用易驱线或者带独立供电的硬盘盒连接hk1box usb3.0接口时，连接不稳定，都会报错报错usb 2-1: reset SuperSpeed Gen 1 USB device number 8 using xhci-hcd。易驱线有时几秒钟有时几分钟就断开连接（表现为需要重新mount，并且设备号也会改变，比如sdb变为sdc）了，然后会自动重连；硬盘盒不会断连，会不断报错，并且偶尔系统的iowait会升到100%，持续大概三十秒。然后同样的硬盘同样的易驱线和硬盘盒，同样的usb3.0接口，如果使用usb2.0的线连接，就没有任何问题和报错。和这个链接的遇到的问题差不多:https://www.right.com.cn/forum/thread-6592311-1-1.html
你们的hk1box有这个问题吗？

machine translation:
When connecting the hk1box usb3.0 interface with an easy drive cable or a hard drive caddy with independent power supply, the connection is unstable and will report the error usb 2-1: reset SuperSpeed Gen 1 USB device number 8 using xhci-hcd. The easy drive cable will sometimes disconnect in a few seconds or sometimes a few minutes (as shown by the need to re The hard drive cable sometimes disconnects for a few seconds or sometimes a few minutes (as shown by the need to re-mount, and the device number also changes, such as sdb to sdc), and then automatically reconnects; the hard drive case does not disconnect, but keeps reporting errors, and occasionally the system iowait rises to 100% for about 30 seconds. Then the same hard drive the same easy drive cable and hard drive caddy, the same usb3.0 interface, if you use the usb2.0 cable to connect, there is no problem and no error reported. Pretty much the same problem encountered with this link. https://www.right.com.cn/forum/thread-6592311-1-1.html

Do you have this problem with your hk1box?

**Comment by ophub** [comment]
问了一下f大你的情况。

2.0的电流小速度慢，3.0电流大速度快。

加外接电源，或者内部加固态电容降低电源纹波，或采用质量更好的电源适配器。还有就是usb连接电缆也有关系，要无氧铜线，还要有屏蔽层。

**Comment by zvzl** [comment]
我用的是自行购买的5v5a的电源，用的是绿联的带外置供电的硬盘盒，usb连接线也是绿联原装的，质量看起来还不错，这套配置的话硬盘不会断开，但是使用dmesg命令会看见持续的（大概一分钟一次）“usb 2-1: reset SuperSpeed Gen 1 USB device number 8 using xhci-hcd”报错，然后跑pcdn持续读写会偶尔iowait上100%，不跑pcdn不会出问题但是dmesg的报错依然存在。

**Comment by ophub** [comment]
你检测一下波纹，恩山有加电容的示意图你找一下。有n1挑u盘，x96max掉硬盘等现象的，加了就好了。
