### ISSUE TITLE
Ethernet port not working.

### ISSUE THREAD

**Issue by 786-xvr** [ophub/amlogic-s9xxx-armbian#1331]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [AW-H6]
 - Model [e.g. Tanix-TX6]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.25]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Ethernet eth0 not detected on new install.

![photo1682356503](https://user-images.githubusercontent.com/41391151/234070644-81675fcd-e7be-4276-b237-92ea049c95ab.jpeg)

**Comment by wangyunsi** [comment]
这个机器可以u盘启动吗

**Comment by piotr-zemla** [comment]
> 这个机器可以u盘启动吗

Yes, but it's very difficult: [It requires connecting the TV Box to the PC using a USB cable](https://linux-sunxi.org/FEL/USBBoot)
Everyone uses SD cards anyway.

**Comment by piotr-zemla** [comment]
Your chip is rated for 100 Mbit/s? I'm not sure as TX6's come with all sort of different chips and configurations. No device is truly the same.

There are a few repos which contain H6 Armbian images with the Ethernet working properly:
- [smlinux's tanix-tx6](https://github.com/smlinux/armbian-tanix-tx6) repo has images which use kernel 6.1.5, and the drivers seem to be quite all right.
- [Inovato Quadra's Armbian builds](https://www.inovato.net/Armbian/) use kernel version 5.15.105 - the drivers are perfect as well. Their newer versions don't work anymore.

I believe copying Ethernet drivers from the first repo could work as a temporary solution, but I'm neither sure, or capable of testing it myself.

**Comment by 786-xvr** [comment]
> Is your chip is rated for 100 Mbit/s? I'm not sure as TX6's come with all sort of different chips and configurations. No device is truly the same.
> 
> There are a few repos which contain H6 Armbian images with the Ethernet working properly:
> - [smlinux's tanix-tx6](https://github.com/smlinux/armbian-tanix-tx6) repo has images which use kernel 6.1.5, and the drivers seem to be quite all right.
> - [Inovato Quadra's Armbian builds](https://www.inovato.net/Armbian/) use kernel version 5.15.105 - the drivers are perfect as well. Their newer versions don't work anymore.
> 
> I believe copying Ethernet drivers from the first repo could work as a temporary solution, but I'm neither sure, or capable of testing it myself.

I tried rebuild options using smlinux images, but eth0  didnt detected.

**Comment by 786-xvr** [comment]
> Can this machine be booted from USB?

Boot from usb only works in awawa dev images, other dont work.

**Comment by wangyunsi** [comment]
> 

where can I find this images?

**Comment by piotr-zemla** [comment]
> > Is your chip is rated for 100 Mbit/s? I'm not sure as TX6's come with all sort of different chips and configurations. No device is truly the same.
> > There are a few repos which contain H6 Armbian images with the Ethernet working properly:
> > 
> > * [smlinux's tanix-tx6](https://github.com/smlinux/armbian-tanix-tx6) repo has images which use kernel 6.1.5, and the drivers seem to be quite all right.
> > * [Inovato Quadra's Armbian builds](https://www.inovato.net/Armbian/) use kernel version 5.15.105 - the drivers are perfect as well. Their newer versions don't work anymore.
> > 
> > I believe copying Ethernet drivers from the first repo could work as a temporary solution, but I'm neither sure, or capable of testing it myself.
> 
> I tried rebuild options using smlinux images, but eth0 didnt detected.

After switching the kernel, modules, firmware, and few other files on ophub's img, with those from Inovato Quadra 5.15.105, Eth0 worked.
I tested both Armbian and OpenWrt images, there were some issues with firmware on OpenWrt but eth0 worked.

May I ask, why did you close the issue?

**Comment by W5x** [comment]
> After switching the kernel, modules, firmware, and few other files on ophub's img, with those from Inovato Quadra 5.15.105, Eth0 worked. I tested both Armbian and OpenWrt images, they both work very well.

@piotr-zemla can you share working image of modded openwrt you make ?, thanks in advance
