### ISSUE TITLE
TY1608 HDMI无显示，有线网可用，可写入EMMC，无WIFI蓝牙

### ISSUE THREAD

**Issue by Jeagarm** [ophub/amlogic-s9xxx-armbian#1332]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905L3B
 - Model: TY1608

**Armbian Version | 系统版本**
 - Kernel Version:  Linux 5.15.104-flippy-82+o
 - Release: Armbian 23.05.0-trunk Bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
浙江电信盒子 型号：TY1608 芯片是S905L3B，先刷安卓9.0TV系统线刷包，制作s905l3b对应的armbian启动盘，adb连盒子U盘启动，HDMI无输出，有线网口正常。使用M302A的DTB可以正常安装到EMMC，但是HDMI还是无输出，蓝牙无线型号是RTL8822cs没驱动也用不了，不知道有没有办法解决。我的机子刷安卓4.4的包貌似网口也会用不了。

![25150929](https://user-images.githubusercontent.com/131421730/234200960-87e7abc6-81e4-43ee-9ace-a622477bf4c9.png)

![1608](https://user-images.githubusercontent.com/131421730/234199431-9eec82c4-cb6e-4ba6-b188-ba82f600bb14.jpg)

![1608q](https://user-images.githubusercontent.com/131421730/234198446-c1a6e890-dd49-45c8-ad26-8c34288c7c4f.jpg)

![1608b](https://user-images.githubusercontent.com/131421730/234198476-3ea5dcc9-dd98-42e2-a0b3-e4aa66fe5035.jpg)

![e598cb85182ef7866f42df9f7793e15](https://user-images.githubusercontent.com/131421730/234199604-4b1c8cf6-597e-482f-abe4-8000cfd368c6.jpg)

![71a1c57b2ef2c989446ae0b31c1df72](https://user-images.githubusercontent.com/131421730/234199641-70da3803-dd14-45a1-8f91-55aa5db4da97.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/7c59e7b45a91d5ccfaba84dd9c131184eeaf8b13/build-armbian/armbian-files/common-files/etc/model_database.conf#L65

112和123配置完全一样，一行放不下写成两行，你选的是这个吧

**Comment by AlanLeeIsGood** [comment]
可以麻烦上传下安卓9系统的ddbr备份吗，我是云南电信的TY1608，S905L3B CPU Sandisk的EMMC，线刷包始终卡5%，在armbian下网口能识别但是不能联网，我试试安卓9正常不

**Comment by Triment** [comment]
> 可以麻烦上传下安卓9系统的ddbr备份吗，我是云南电信的TY1608，S905L3B CPU Sandisk的EMMC，线刷包始终卡5%，在armbian下网口能识别但是不能联网，我试试安卓9正常不

同机器同卡5%是不是背面有4k dolby标志

**Comment by pathpass2** [comment]
> > 可以麻烦上传下安卓9系统的ddbr备份吗，我是云南电信的TY1608，S905L3B CPU Sandisk的EMMC，线刷包始终卡5%，在armbian下网口能识别但是不能联网，我试试安卓9正常不
> 
> 同机器同卡5%是不是背面有4k dolby标志

同云南电信1608，刚开始不知道是高安版刷砖了，废了老大劲救回来，实测不用安卓9，安卓4.4.2也能启动armbian.但是一样没有hdmi，没有WiFi，mt7668的WiFi模块。网线连接正常，没有写入emmc。卡百分之5是刷机工具版本太旧了(2.2.4版本)，换新的(3.1.0版本)。但是一样会刷机失败，再重新换回旧版本刷就好了。不会再卡百分之五。如果卡百分之一就是固件问题。

**Comment by niceqwer55555** [comment]
https://github.com/w2xg2022/actions4ty1608/releases/download/Armbian_bullseye_save_2023.06/Armbian_23.08.0_amlogic_s905l3b-ip103h_bullseye_5.15.116_server_2023.06.10.img.gz

**Comment by cccc393** [comment]
盒子ty1608刷飞牛时候，可以找到debian的路由器地址，但是浏览器里无法打开IP:5666网址，也就无法建立账号。。ssh端试过root账号root密码，都被拒绝，换了设备也这样。是盒子s905l3b本身造成的吗？之前两包都试失败

**Comment by xiaoweiboos** [comment]
盒子太拉跨  出现地址需要多等一会儿  你在浏览器一直刷新就行了 并不是包的问题   只要路由器能看到地址就是正确的。 多等待一会儿 就会出现飞牛的界面 然后创建账户后用ssh  命令写入emmc     显示器是不会显示的  @cccc393 

<img width="1670" height="1118" alt="Image" src="https://github.com/user-attachments/assets/c76497e0-7821-4dbb-b700-187b3402c479" />

**Comment by chinastation** [comment]
> 盒子ty1608刷飞牛时候，可以找到debian的路由器地址，但是浏览器里无法打开IP：5666网址，也就无法建立账号。。ssh端试过root账号root密码，都被拒绝，换了设备也这样。是盒子s905l3b本身造成的吗？之前两包都试失败

我也是这样，不知道包的用户名和密码是多少。

**Comment by xiaoweiboos** [comment]
有地址。你要等很久。一直刷新就行了。我感觉要等5到10分钟左右。我也只是花几十块钱买来玩的。用起来体验不怎么好。我有另外的设备装飞牛。



---原始邮件---
发件人: "HUAWEI ***@***.***&gt;
发送时间: 2026年5月16日(周六) 下午5:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] TY1608 HDMI无显示，有线网可用，可写入EMMC，无WIFI蓝牙 (Issue #1332)


huaweio3 left a comment (ophub/amlogic-s9xxx-armbian#1332)
  
盒子ty1608刷飞牛时候，可以找到debian的路由器地址，但是浏览器里无法打开IP：5666网址，也就无法建立账号。。ssh端试过root账号root密码，都被拒绝，换了设备也这样。是盒子s905l3b本身造成的吗？之前两包都试失败
  
我也是这样，不知道包的用户名和密码是多少。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
