### ISSUE TITLE
B860H install to emmc disconnect..

### ISSUE THREAD

**Issue by Megabitsz** [ophub/amlogic-s9xxx-armbian#1336]
**Device Information
 - SOC: [S905x]
 - Model [B860H]

**Armbian Version
 - Kernel Version: [5.15.108]
 - Release: [jammy]

armbian-install
install to emmc disconnect..

![Screenshot (11)](https://user-images.githubusercontent.com/131801200/234356498-e9d58ee8-719c-4e42-ae48-ce0b4a58d3fb.png)

**Comment by ophub** [comment]
If SSH disconnects during installation, please reconnect and resume the installation process

**Comment by Megabitsz** [comment]
How?
