### ISSUE TITLE
章鱼星球（原版）Arambian 刷入报错 EXT4-fs error，不知如何解决。

### ISSUE THREAD

**Issue by iCheNty** [ophub/amlogic-s9xxx-armbian#1337]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S912]
 - Model [章鱼星球]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [bullseye]

**Describe the bug | 问题描述**

章鱼星球（原版）Arambian 刷入报错 EXT4-fs error，有解决办法吗？

![Uploading 1682478007379.jpg…]()

**Comment by iCheNty** [comment]
![1682478007379](https://user-images.githubusercontent.com/68026770/234456497-c01e5ab8-6e7d-40d2-9673-23910fb9cb3e.jpg)

**Comment by iCheNty** [comment]
![9d9f6224c9dfe19a1295ac9a10aebb0](https://user-images.githubusercontent.com/68026770/234464436-64bfd7c7-9177-4973-ad75-b58a1588a324.jpg)

章鱼星球才买的，是硬件有问题吗？还是系统问题？有人说换u盘试试，但是我换了一个，状况依旧。麻烦指导一下。

**Comment by ophub** [comment]
I/O错误，不能正常读写emmc
有2条章鱼，外壳一模一样，一条是真鱼一条是山寨鱼，拆机可以看出主板不同。不想拆机就换山寨的选项安装试试。

**Comment by iCheNty** [comment]
感谢大神解答，机器银色的，看机器侧面编号是XQ2345-1，应该是原版的章鱼，不是fake的。
我这机器原来买到手是minixfreak_os
我现在线刷成S912精简安卓版了

armbian系统有线刷包吗？直接用线刷不用U盘，能解决这个问题吗？

**Comment by ophub** [comment]
无论是线刷还是卡刷的结果都是一样的。

山寨从外壳看无差别

**Comment by iCheNty** [comment]
目前解决了。其实就是刷机U盘问题。
又换了几个后终于跑完，刷入EMMC….
感谢大神解答。
