### ISSUE TITLE
Difference between "b" and no "b" image?

### ISSUE THREAD

**Issue by trohnjavolta** [ophub/amlogic-s9xxx-armbian#1338]
Hi, I couldn't find an explanation for it in the docs, what's the difference between these two images?

Armbian_23.05.0_amlogic_s905x3-b_bullseye_6.1.25_server_2023.04.25.img.gz

and
Armbian_23.05.0_amlogic_s905x3_bullseye_6.1.25_server_2023.04.25.img.gz

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

look at 513

**Comment by danboid** [comment]
I was asking this same question recently and I didn't understand @ophub's answer. It seems to use a different dtb ie not the X96 Max Plus .dtb like the regular S905X3 images.

**Comment by trohnjavolta** [comment]
I think it's a different mainboard.

**Comment by ophub** [comment]
different mainboard

![Snip20230426_3](https://user-images.githubusercontent.com/68696949/234590037-5248d914-86f5-4666-b460-5892cd784fc5.png)
