### ISSUE TITLE
X96 max + [2+16G, 100M, RTL8189ftv ]  No LAN, WIFI error: Kernal panic - not syncing Oops: Fatal exception in interrupt 

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#134]
I just tried to run the latest build (Armbian_22.05.0_Aml_s905x3_bullseye_5.15.26_2022.03.05.1324) from USB and got several errors related to the LAN & WIFI.

1.Unable to recogniz the ETH0: Error message "meson8b-dwmac ff3f0000. ethernet eth0: no phy at addr -1"
"Failed to start Raise network interfaces"
![IMG_5852](https://user-images.githubusercontent.com/22479095/156907981-777cfc1a-13c0-442c-8657-f5813539cb14.JPG)

"A start job is running for Raise Network interfaces 5min3s"
![IMG_5851](https://user-images.githubusercontent.com/22479095/156908436-5413c719-ee6a-4515-a7e1-8c027f8defe7.JPG)

It takes several minutes to start.

2. Kernal Panic once connect to wifi network

![IMG_5856](https://user-images.githubusercontent.com/22479095/156908508-7c7eeec2-0e23-436a-a2ed-6a74241a688f.JPG)

**Comment by luoluo888** [comment]
![Uploading IMG_20220303_211147.jpg…]()

**Comment by dinhchinh82** [comment]
This issue already resolved by the following solution:
1. Flash Armbian_22.05.0_Aml_s905x3_bullseye_5.4.182_2022.03.05.1326 image to USB
2. Unplug & plug the usb to the PC again, Open "Boot" partition then change the uEnv.txt to the code below:
`LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-x96-air-100.dtb
APPEND=root=UUID=167aa722-e1e0-4745-a3ba-53505e2bc140 rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1`

3. Unplug the USB and plug to the USB3.0 port (green) of X96 max+, plug the ethernet.
4. Using toothpick to hold the reset button inside the AV port, plug the power of the box, keep holding the reset button about 10 seconds then release finger.
5. Waiting for Armbian to start (quite fast, about 1-2 minutes)
6. Login to Armbian and change default password
7.  Create the install-to-emmc.sh script with the content from this link:
https://github.com/ophub/amlogic-s9xxx-armbian/issues/105#issuecomment-1058050442
8. Run the install-to-emmc.sh, select Option 2 (X96max+), waiting for installing to eMMC successfully
9. Unplug the power, USB then plug the power again.
10. Then you should see the armbian boot normally from eMMC (under 1minutes to start the fresh armbian).

@ophub thank you so much for your support.

I will keep checking the stability of this box and report any problem if any.

**Comment by ophub** [comment]
congratulations
