### ISSUE TITLE
无法使用U盘启动

### ISSUE THREAD

**Issue by G543-hub** [ophub/amlogic-s9xxx-armbian#1340]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息新魔百和M401A

**Armbian Version | 系统版本**sl9503a的版本
没办法用U盘引导
卡在这个界面
![a4a157124954092347a3a8a9d758d109b2de4935](https://user-images.githubusercontent.com/131681550/234596451-f704592a-97cd-418e-a612-9d49117936e9.jpg)

**Comment by ophub** [comment]
说明里有如何从USB启动的教程

**Comment by G543-hub** [comment]
谢谢

**Comment by G543-hub** [comment]
能把USB启动教程发给我吗？我找不到😓

**Comment by gqxk** [comment]
> 说明里有如何从USB启动的教程

按教程试了，还是不能进，大佬有没有办法
