### ISSUE TITLE
编译内核出错

### ISSUE THREAD

**Issue by LondyGhost** [ophub/amlogic-s9xxx-armbian#1342]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S922x
 - Model CS922x

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.108]
 - Release: [Armbian 23.05.0-trunk Bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

因为找到一个新的8822cs驱动，打算编译驱动，用gcc报错，源码示例用的是clang，遂打算clang 编译一个内核再尝试进行编译驱动
编译内核参考的是   #1043   

armbian-kernel -u
armbian-kernel -k 5.15.108 -t clang

然后出现以下错误。尝试x86平台交叉编译，环境也是debian 11，也是出现错误，但是由于正好windows蓝屏，虚拟机直接被重置，重启后找不到log文件。

ERROR: modpost: "is_zero_mac_addr" [drivers/net/wireless/realtek/rtl8189fs/8189fs.ko] undefined!
ERROR: modpost: "is_multicast_mac_addr" [drivers/net/wireless/realtek/rtl8189fs/8189fs.ko] undefined!
ERROR: modpost: "is_broadcast_mac_addr" [drivers/net/wireless/realtek/rtl8189fs/8189fs.ko] undefined!
ERROR: modpost: "is_zero_mac_addr" [drivers/net/wireless/realtek/rtl8188fu/rtl8188fu.ko] undefined!
ERROR: modpost: "is_multicast_mac_addr" [drivers/net/wireless/realtek/rtl8188fu/rtl8188fu.ko] undefined!
ERROR: modpost: "is_broadcast_mac_addr" [drivers/net/wireless/realtek/rtl8188fu/rtl8188fu.ko] undefined!
make[1]: *** [scripts/Makefile.modpost:133：modules-only.symvers] 错误 1
make[1]: *** 正在删除文件“modules-only.symvers”
make: *** [Makefile:1828：modules] 错误 2
[ STEPS ] Install modules ...
make[1]: *** 没有规则可制作目标“/opt/kernel/compile-kernel/output/modules/lib/modules/5.15.108-ophub/kernel/crypto/asymmetric_keys/pkcs7_test_key.ko”，由“__modinst” 需求。 停止。
make: *** [Makefile:1839：modules_install] 错误 2
[ STEPS ] Install headers ...
find: ‘Module.symvers’: 没有那个文件或目录
[ SUCCESS ] The headers is installed successfully.
[ STEPS ] Generate uInitrd environment initialization...
[ INFO ] Backup the files in the [ /boot ] directory.
[ INFO ] Backup the files in the [ /usr/lib/modules ] directory.
[ STEPS ] Generate uInitrd file...
update-initramfs: Generating /boot/initrd.img-5.15.108-ophub
[ SUCCESS ] The initrd.img and uInitrd file is Successfully generated.
[ INFO ] File situation in the /boot directory after update: 
-rwxr-xr-x 1 root root   221100  4月 26 19:57 config-5.15.108-ophub
-rwxr-xr-x 1 root root 12203628  4月 26 19:58 initrd.img-5.15.108-ophub
-rwxr-xr-x 1 root root  5608401  4月 26 19:57 System.map-5.15.108-ophub
-rwxr-xr-x 1 root root 12203692  4月 26 19:58 uInitrd-5.15.108-ophub
-rwxr-xr-x 1 root root 24777216  4月 26 19:57 vmlinuz-5.15.108-ophub
[ STEPS ] Packing the [ 5.15.108-ophub ] dtbs packages...
[ SUCCESS ] The [ dtb-allwinner-5.15.108-ophub.tar.gz ] file is packaged.
[ SUCCESS ] The [ dtb-amlogic-5.15.108-ophub.tar.gz ] file is packaged.
[ SUCCESS ] The [ dtb-rockchip-5.15.108-ophub.tar.gz ] file is packaged.
[ STEPS ] Packing the [ 5.15.108-ophub ] boot, modules and header packages...
[ SUCCESS ] The [ boot-5.15.108-ophub.tar.gz ] file is packaged.
[ SUCCESS ] The [ modules-5.15.108-ophub.tar.gz ] file is packaged.
[ SUCCESS ] The [ header-5.15.108-ophub.tar.gz ] file is packaged.
[ SUCCESS ] The [ sha256sums ] file has been generated
[ INFO ] Kernel series files are stored in [ /opt/kernel/compile-kernel/output ].
[ STEPS ] Clear the space...
[ SUCCESS ] All processes have been completed.
[ STEPS ] Server space usage after compilation: 
文件系统       类型  容量  已用  可用 已用% 挂载点
/dev/mmcblk1p2 ext4   58G  6.1G   52G   11% / 

[ SUCCESS ] All process completed successfully.

**Comment by ophub** [comment]
armbian-kernel 只能在 armbian 里使用。
在 X86 里使用 ./recompile

**Comment by ophub** [comment]
源码有错无法编译。你编个正常的

https://github.com/unifreq/linux-6.1.y
