### ISSUE TITLE
desktop无法启动

### ISSUE THREAD

**Issue by MikeYao0513** [ophub/amlogic-s9xxx-armbian#1343]
311-1 905L3 安装好armbian后armbian-software里安装了desktop，但重启后还是命令符，没有进入桌面，请问怎么解决？

**Comment by ophub** [comment]
显示器里看

**Comment by MikeYao0513** [comment]
> 显示器里看
浏览器输入IP地址加端口号？

**Comment by HeroPoter** [comment]
连接到电视机或显示器就会自动出桌面图像
