### ISSUE TITLE
写入emmc开机使用半个小时以后显示错误死机

### ISSUE THREAD

**Issue by 2020355** [ophub/amlogic-s9xxx-armbian#1344]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095l3-b]
 - Model [e.g. 311-1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.108
![230427093314](https://user-images.githubusercontent.com/78094623/234737269-0dcc2c0f-86a0-4517-a498-c6e461994864.png)
]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Message from syslogd@armbian at Apr 27 09:26:49 ...
 kernel:[ 1189.592020] Internal error: Oops: 96000044 [#1] PREEMPT SMP

Message from syslogd@armbian at Apr 27 09:26:49 ...
 kernel:[ 1189.780998] Code: f8207b01 f9400661 f9400262 f9000441 (f9000022)

**Comment by xxx854** [comment]
> 

你写入emmc了吗
