### ISSUE TITLE
Armbian_23.05.0_amlogic_s922x-reva_jammy_5.15.109_server_2023.04.27.img.gz 蓝牙和wifi无法使用？

### ISSUE THREAD

**Issue by Panjir** [ophub/amlogic-s9xxx-armbian#1347]
刚刷了Armbian_23.05.0_amlogic_s922x-reva_jammy_5.15.109_server_2023.04.27.img.gz的镜像 启动正常，网口正常，wifi和蓝牙不可用。有什么办法可以启动wifi和蓝牙吗?

**Comment by ophub** [comment]
文档里写了
