### ISSUE TITLE
S905x T95 boot crash

### ISSUE THREAD

**Issue by chris4git** [ophub/amlogic-s9xxx-armbian#135]
Hi, thanks for your work and sharing !

I try to run Armbian_22.05.0_Aml_s905x_bullseye_5.15.26_2022.03.05.1403.img on a S905x tv box (called T95) which runs Balbes bullseye 20.10 last image for now.
As is, the boot cycles between splash screen and black screen.
If I change u-boot.ext content to u-boot-s905x-s912.bin the boot goes further but crash and reset immediately :

![vlcsnap-2022-03-06-09h53m11s986](https://user-images.githubusercontent.com/23280864/156917220-95d9a97c-e64b-4cf8-86eb-ed5c4cb35d89.png)

Any advice ?

**Comment by ophub** [comment]
try 5.4

**Comment by ophub** [comment]
Use usb to test the firmware of s905x with 5.4 kernel.

**Comment by chris4git** [comment]
5.4 boots but the wifi driver don't work (rtl8xxxu) : the module loads but wlan0 as no wireless extensions!
In Balbes image (5.9) it works almost (crash 1/day).
So I hoped in 5.15...

**Comment by ophub** [comment]
You are the first to report using the s905x-t95, there is currently no configuration in the firmware for your box. You can refer to your configuration in 150Balbes, modify uEnv.txt and u-boot, and use the same file for testing.
Tested with 5.4 firmware. Don't test others. The kernel after 5.10 needs an additional u-boot boot file, you must first confirm the dtb and then try u-boot.

**Comment by ophub** [comment]
In the past, the n1 box chose usb disks, and the problem can be solved by adding capacitors.


The 5.4 kernel can be used without u-boot.

After you select the dtb (meson-gxl-s905x-p212.dtb). that can be used by testing in the firmware of the 5.4 kernel. You can test whether the 5.15 kernel can be used by selecting a different u-boot.
