### ISSUE TITLE
小米盒子3无法从u盘启动armbian

### ISSUE THREAD

**Issue by hionwi** [ophub/amlogic-s9xxx-armbian#1350]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.26]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
小米盒子3 使用balenaEtcher将Armbian_23.05.0_amlogic_s905_jammy_6.1.26_server_2023.04.27.img写入u盘，插入盒子，并使用adb shell reboot update后 还是进入小米盒子的原系统 无法进入armbian

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1359

看这个7Ji大佬的方案
