### ISSUE TITLE
UNT403A  6.1内核无法启动

### ISSUE THREAD

**Issue by uniartisan** [ophub/amlogic-s9xxx-armbian#1353]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [UNT403A]

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_04.27.0149/Armbian_23.05.0_amlogic_s905l3a_jammy_6.1.26_server_2023.04.27.img.gz

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.26]
 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

刷入u盘后无法从u盘启动，卡在黑屏界面。如果是用5.15内核升级到6.1内核也会无法开机，如果刷机到5.15内核就不会有问题。

**Comment by Scirese** [comment]
如果这里没有提供你盒子的主线uboot, 你可能需要给内核打补丁, 然后自己编译, 才能用 5.4/5.15 以外的内核.
参考 #859

**Comment by ophub** [comment]
用dev里面的内核，5.10和6.1的都打了offsets补丁

armbian-update -u dev -k 6.1.26
