### ISSUE TITLE
盒子安装图形化桌面会卡桌面，怎么回事

### ISSUE THREAD

**Issue by dhz110** [ophub/amlogic-s9xxx-armbian#1354]
图像化桌面中会很卡，会闪屏幕，播放视屏是一帧一帧的，有办法解决吗

**Comment by inoeud** [comment]
安装开源mail驱动

**Comment by dhz110** [comment]
> 



> 安装开源邮件驱动

这和邮件驱动有什么关系

**Comment by altmangood** [comment]
提issue有标准模板。什么Soc 什么型号。

前面回答没问题。 注意，不是mail。 是 mali 。 Open Source Mali Bifrost GPU Kernel Drivers

**Comment by dhz110** [comment]
> 提issue有标准模板。什么Soc 什么型号。
> 
> 前面回答没问题。 注意，不是mail。 是 mali 。 Open Source Mali Bifrost GPU Kernel Drivers

905l3a,unt403A，怎么安装mali驱动

**Comment by dhz110** [comment]
> 

怎么安装啊
