### ISSUE TITLE
s905-B有适配的包吗

### ISSUE THREAD

**Issue by y52047** [ophub/amlogic-s9xxx-armbian#1356]
![微信图片_20230429234105](https://user-images.githubusercontent.com/126791076/235311804-6d718014-d33c-4280-950c-baf5f1f6e675.jpg)
![微信图片_20230429234111](https://user-images.githubusercontent.com/126791076/235311818-d8a2abdd-946e-4275-9488-a9c6e62b1d7d.jpg)
![微信图片_20230429234132](https://user-images.githubusercontent.com/126791076/235311834-3ab4d267-5cb1-4d19-a8e6-cfda2840d016.jpg)

**Comment by ophub** [comment]
没有
