### ISSUE TITLE
Can't enable wifi interface HG-680-p s905x

### ISSUE THREAD

**Issue by mbohben** [ophub/amlogic-s9xxx-armbian#1360]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905x]
 - Model [hg-680p]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.26 server]
 - Release: [Armbian_bullseye_04.27.0148]

**Describe the bug | 问题描述**
wifi menu not showing, things tried:
apt update -> apt upgrade
downloading the driver manualy and placed it on the kernel directory -> depmod -a

**Comment by ophub** [comment]
There is an introduction on how to enable wireless in the documentation
