### ISSUE TITLE
大佬好，6.1 内核缺少驱动 CONFIG_RTL8189FS ，请问能否添加一下，十分感谢

### ISSUE THREAD

**Issue by FanchangWang** [ophub/amlogic-s9xxx-armbian#1362]
5.15 版本中可以看到
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.15#L3096

6.1 版本中没有 CONFIG_RTL8189FS，如果可以的话请大佬添加一下，十分感谢

**Comment by ophub** [comment]
以前f大给6.1添加过，但是不兼容无法编译，所以去掉了。
