### ISSUE TITLE
一键更新服务不可用

### ISSUE THREAD

**Issue by GD2021** [ophub/amlogic-s9xxx-armbian#1364]
12.9 如何更新系统中的服务脚本
使用 armbian-sync 命令可以一键将本地系统中的全部服务脚本更新到最新版本。

![image](https://user-images.githubusercontent.com/81171294/235555248-2ef210ec-4c29-4bd8-9eb2-31ca8b2ae9c3.png)

**Comment by ophub** [comment]
你的设备无法访问github.com

用你会设置的方法给他加个油
