### ISSUE TITLE
U盘刷armbian，在多个盒子上安装系统，盒子联网后Ip相同，mac相同。设置固定ip后，开机启动慢，但是可以获取盒子的正常ip和mac

### ISSUE THREAD

**Issue by shaoyinci** [ophub/amlogic-s9xxx-armbian#1365]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S095l3a
 - Model :m401

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.109
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
U盘刷armbian，在多个盒子上安装系统，盒子联网后Ip相同，mac相同。设置固定ip后，开机启动卡在联网步骤，等待一段时间后，可以获取盒子的正常ip和mac

**Comment by shaoyinci** [comment]
就是在这里下载的，之前使用的版本是5.15.86，是可以直接使用盒子自己的mac。然后我重新下载的109就不行，我在M401上复现了这个问题，测试过好多次了。

**Comment by shaoyinci** [comment]
过程是这样的，我用u盘下载镜像然后安装到第一个m401A上，ip和mac是正常的，然后我拔下这个U盘插到第二个m401a上开机运行，然后这个盒子上ip和Mac依然是第一个盒子的配置。

**Comment by gametta** [comment]
B863 AV 3.2M上面用最新的6.1.27也是统一的MAC，五一的时候我就反应过这个问题，另外我的还出现断电后不开机的现象，我现在退回到5.15.108，还是有MAC重复的现象，86版本左右那时候是没有问题的。

**Comment by xcc360** [comment]
测试了一下，盒子型号CM311-1a YST以及UNT403A，均为S905L3A的芯片，优盘全新刷的Armbian_23.05.0_amlogic_s905l3a_bullseye_5.15.110_server_2023.05.09.img.gz
CM311-1a原厂mac在，unt403a原厂mac丢失
测试结果：
1、CM311-1a，全新制作的优盘启动，第一次启动，Mac正确为CM311-1a，后续再插到403A上启动，Mac还是显示CM311-1a的；
2、unt403a，因为安卓刷机的缘故，Mac丢失，重新制作优盘，第一次启动，Mac为3A:38:5D:D7:E3:98，后续再插到403A上启动，Mac还是显示3A:38:5D:D7:E3:98，而不是CM311-1a的Mac
两次均为全新制作armbian优盘，感觉是第一次启动会自动读取emmc上的mac，如果没有mac就自己生成一个，然后后续再换机器mac就不会变了，原理不明，特此汇报！
