### ISSUE TITLE
请求适配华北工控EMB-3531

### ISSUE THREAD

**Issue by phcl1998** [ophub/amlogic-s9xxx-armbian#1366]
配置：
CPU：Rcokchip RK3399(双核A72 2GHz+四核 A53 1.5GHz)
GPU：Mali-T864
DDR3 RAM：最大4GB
Ethernet: 10/100/1000M 以太网口, 采用RTL8211F
Wireless/蓝牙：RTL8188ETV（可选蓝牙WIFI一体模块）
4G：1 x MINI PCIe
Audio：板载ES8316+NS4258T（1 x HeadPhone(支持4节),2 x Mic,板载5W双输出功放)
Storage：最大64G Flash
MicroSD Slot：x1
USB Host： 4x USB3.0，3x USB2.0，1x USB OTG
COM： 6x COM（4x RS232/TTL，2x COM485/232/TTL）,1x DB9调试接口
Display：1 x HDMI ,1 x LVDS ，1 x DP
Other I/O：3x Camera(24 pin FPC)，30PIN GPIO 接口[可配置SPI,I2S,MIPI,I2C]，1x PCIE X4
System Control：Reset switch, Power switch
Temperature：Work -20 ~ 65, Storage -40 ~ 85
Humidity：5% ~ 95%相对湿度，无冷凝
PCB Size: 146 x 102 mm
Power Supply: DC 12V
OS: Android , Linux
Other：Watchdog, RTC

官网固件下载地址：http://android1.norco.com.cn:7070/index.php/EMB-3531

**Comment by phcl1998** [comment]
感谢[http://android1.norco.com.cn:7070/index.php/%E6%96%87%E4%BB%B6:EMB-3531%E6%8E%A5%E5%8F%A3%E5%B8%83%E5%B1%80.jpg](url)

**Comment by phcl1998** [comment]
现在有一个2+16的板子可以测试

**Comment by ophub** [comment]
http://norcord.com:8070/d/34131f775091442d9fdc/
官方提供的ubuntu或者debian系统，你安装可以正常使用吗？如果你刷入了，截图下这个路径的文件
`ls -l /usr/lib`

**Comment by phcl1998** [comment]
> http://norcord.com:8070/d/34131f775091442d9fdc/ 官方提供的ubuntu或者debian系统，你安装可以正常使用吗？如果你刷进去了，截图下这条路沿的文件目录：
> 
> ```
> ls /usr/lib
> ls /usr/lib/u-boot
> ```
我刷了官方的ubuntu16.04可以正常启动，但是在/usr/lib下没有找到u-boot
[https://github.com/phcl1998/Temporary/blob/main/images/HU8FUYSQ9K%60MFZ1D%25HVR3_8.png](url)

**Comment by phcl1998** [comment]
> http://norcord.com:8070/d/34131f775091442d9fdc/ 官方提供的ubuntu或者debian系统，你安装可以正常使用吗？如果你刷进去了，截图下这条路沿的文件目录：
> 
> ```
> ls /usr/lib
> ls /usr/lib/u-boot
> ```

我刷了官方的ubuntu16.04可以正常启动，但是在/usr/lib下没有找到u-boot
https://raw.githubusercontent.com/phcl1998/Temporary/main/images/HU8FUYSQ9K%60MFZ1D%25HVR3_8.png

**Comment by ophub** [comment]
官网里没找到编译源码，如果他的镜像文件里带了就好了。
ubuntu18和debian都刷下找找有没有。
这个镜像很奇怪，无法losetup挂载。

**Comment by phcl1998** [comment]
> ls /usr/lib/u-boot

现在试了ubuntu18.04和debian都没有u-boot
https://github.com/phcl1998/Temporary/blob/main/images/CGQG)~4GU3%7B9%5B2DX%40P2A(48.png

**Comment by phcl1998** [comment]
大佬我从恩山上找到了相关的dts，不知对编译是否有帮助
https://github.com/phcl1998/Temporary/blob/main/images/emb-3531(%E5%8F%8D%E7%BC%96%E8%AF%91%E6%9C%AA%E4%BF%AE%E6%94%B9).dts

**Comment by ophub** [comment]
这种反编译文件只能看看，简单修改下参数，不能编译。

**Comment by phcl1998** [comment]
> 这种反编译文件只能看看，简单修改下参数，不能编译。

那这板子还能搞吗？

**Comment by ophub** [comment]
有u-boot源码或者编译好的u-boot文件才行，找不到不好搞

**Comment by bbggoo** [comment]
[dmesg-serialout.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11406924/dmesg-serialout.log)
[startup-serialout.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/11406928/startup-serialout.log)
这两个文件有没有用，一个是启动串口日志，一个是dmesg 输出

**Comment by chsdzczp** [comment]
> 有u-boot源码或者编译好的u-boot文件才行，找不到不好搞

AndroidTool.exe 可以解包，不知能不能用，如下图
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37919180/2afc40da-4bbd-4426-bcb4-9ea00616eb16)

输出文件：
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37919180/ca96201b-4362-4b46-8432-bc84a0513c1d)

**Comment by ophub** [comment]
这是一种打包的方式，文件不是单一文件，是有几个分区部分组成，这个文件直接替换rootfs.img即可得到新的固件。
但是他的u-boot大小和常见的不一样，我不了解这个u-boot应该怎么写入使用。

**Comment by rongchuan17** [comment]
> 官网里没找到编译源码，如果他的镜像文件里带了就好了。 ubuntu18和debian都刷下找找有没有。 这个镜像很奇怪，无法losetup挂载。

大佬，提取了这个板子别人适配的uboot,你看看能搞吗
[u-boot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12063069/u-boot.zip)

**Comment by qiushui007007** [comment]
请教下, 原厂debain系统的root密码是多少? 好像原厂debain系统是32位?

**Comment by lihao-744** [comment]
大佬们还有固件吗，官方wiki里面的固件链接失效了
