### ISSUE TITLE
s905x 随机重启问题

### ISSUE THREAD

**Issue by fly-high2016** [ophub/amlogic-s9xxx-armbian#1368]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information
SOC: CPU S905x，RAM H5TQ4G63EFR-RDC 1GB，ROM KLM8G1GETF-B041 8GB
Model: 	LonBon NLV-DC丝印型号，盒子外壳型号无法搜到。
参考介绍：https://www.lonbon.com/Uploads/word/NLV-DC.pdf
Release: Armbian_23.05.0_amlogic_s905x_jammy_5.15.108_server_2023.04.22.img.gz

Describe the bug | 问题描述
Describe the problem in detail and attach screenshots if necessary.

背景信息：1、可用meson-gxl-s905x-libretech-cc-v2.dtb启动，启动后可稳定运行（电源指示灯红蓝交替闪烁，闪烁规律基本符合“红-红-红-蓝-红-蓝”循环）。其他dtb如可以启动，则会随机重启（首次可运行约5分钟左右随机重启，一但随机重启则运行时长随机，可能无法完成跑码，也可能正常登录）。meson-gxl-s905x-hwacom-amazetv.dtb、meson-gxl-s905x-nexbox-a95x.dtb无法启动，meson-gxl-s905x-tbee.dtb启动报错后hdmi输出卡住。2、可以刷入TX5pro-6255-20161206.img、hx_s905x_Nougat_256x4_528m_20171030_1134_ZNT_2017110107.img、Aidan's rom (Android7.1.2、9.0)、slimbox9.0但是启动后随机重启。现象与armbian随机重启类似，刷机后首次启动可运行约5分钟，一但自动重启，后续可能进入桌面也可能未进入桌面即自动重启。
问题：想了解下meson-gxl-s905x-libretech-cc-v2.dtb这个dtb与其他dtb如meson-gxl-s905x-p212.dtb的区别。

![1](https://user-images.githubusercontent.com/25540990/235838878-4badd9c4-5f75-48c2-86b8-dd4564636725.jpg)
![3](https://user-images.githubusercontent.com/25540990/235838930-da58d798-8b34-49a2-bcf9-f615ee9bf06a.jpg)
![4](https://user-images.githubusercontent.com/25540990/235838954-bce313a7-88d2-4659-9da7-f83a614df463.jpg)
![5](https://user-images.githubusercontent.com/25540990/235838935-69e4c44a-3aa2-4dfd-aac9-5a008defcb36.jpg)

**Comment by ophub** [comment]
区别可以看源码 https://github.com/unifreq/linux-6.1.y/tree/main/arch/arm64/boot/dts/amlogic

**Comment by fly-high2016** [comment]
看了一下，猜测是缺失regulator-always-on引发供电不足导致随机重启
