### ISSUE TITLE
How to boot armbian on tx3 mini s905W2 plus 2022

### ISSUE THREAD

**Issue by anhkhang2304** [ophub/amlogic-s9xxx-armbian#137]
Hi ! I have an Tx3 mini Plus 2022 tvbox:
CPU: s905W2
I use Armbian_22.05.0_Aml_s905w_focal_5.15.26_2022.03.05.1409.img.gz to flash to the memory card but currently can't boot it on tx3 mini. How can I boot it? Please help (bow)

**Comment by anhkhang2304** [comment]
![image](https://user-images.githubusercontent.com/20942189/156963465-eed02499-c298-49f9-9bbc-66dd87fc27bd.png)
It just stops at this screen!

**Comment by ophub** [comment]
Set the box to boot from USB/TF/SD

https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#1010-set-the-box-to-boot-from-usbtfsd

**Comment by anhkhang2304** [comment]
@ophub I tried but it doesn't seem to appear on adb devices -> syntax ```adb devices -l```

**Comment by ophub** [comment]
Does your device have a reset button? Long press for 5 seconds can also boot from usb.
`Adb` or `reset key`, these two ways, you try more.

**Comment by anhkhang2304** [comment]
@ophub I use Armbian_22.05.0_Aml_s905w_focal_5.15.26_2022.03.05.1409.img.gz to flash But It just stops at the screen like above.  I think the version I am using is not suitable for the chip s905w2. Can you suggest me a more suitable version?

**Comment by anhkhang2304** [comment]
This is a new chip manufactured in 2022. I think it needs tweaking to be able to boot with armbiam!
