### ISSUE TITLE
如何刷，还需要修改什么配置吗

### ISSUE THREAD

**Issue by i7s7x** [ophub/amlogic-s9xxx-armbian#1370]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095l3b]
 - Model [e900v21e]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
我是浙江电信，创维e900v21e,S095l3b，无线是mt7668，也有蓝牙，我无论刷哪个版本，安装u盘插在离电源进的usb口，遥控器右键按住刷，都是卡在启动花屏界面，然后就循环重启，

**Comment by ophub** [comment]
在首页的支持设备列表里，点对应的设备，进入贡献者分享测试的帖子，看他的操作过程和注意事项。
很多魔百盒都需要先把盒子自带的安卓4更换为安卓9系统，在对应的帖子里有安卓固件下载链接。
