### ISSUE TITLE
如何修改图形界面为中文？

### ISSUE THREAD

**Issue by G543-hub** [ophub/amlogic-s9xxx-armbian#1371]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息 魔百和M401A

**Armbian Version | 系统版本**

s905l3a_Bullseye_5.15.108_server
**Describe the bug | 问题描述**
安装的图形界面全是英文压根看不懂
详细描述问题，并在必要时附上屏幕截图。
╯▂╰
![IMG_20230503_210022](https://user-images.githubusercontent.com/131681550/235923443-743be585-1e37-4d12-b8a1-4d1c8a3957d1.jpg)

**Comment by ophub** [comment]
安装桌面时有选项提示你是否安装中文，后期你可以在 armbian-config 里安装中文支持。
