### ISSUE TITLE
魔百和M401A无声音

### ISSUE THREAD

**Issue by G543-hub** [ophub/amlogic-s9xxx-armbian#1372]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 魔百和M401A
**Armbian Version | 系统
s905l3a_Bullseye_5.15.108_server
**Describe the bug | 问题描述**
图形化界面显示声音不可用

**Comment by ophub** [comment]
不支持
