### ISSUE TITLE
armbian安装PVE时有处报错，请教

### ISSUE THREAD

**Issue by GD2021** [ophub/amlogic-s9xxx-armbian#1373]
**Device Information | 设备信息**
 - SOC: [e.g. RK3566]
 - Model [e.g. https://github.com/ophub/amlogic-s9xxx-armbian/issues/1319]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]
![image](https://user-images.githubusercontent.com/81171294/235973042-fe6c9927-af2c-4cdb-a05f-9a21b337f0b0.png)

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

问：刷完系统，我设置了静态IP，armbian安装pve时有处报错
![image](https://user-images.githubusercontent.com/81171294/235972525-2d57671e-a3cd-4350-9d5b-cb9446849ca9.png)

ping可以通
![image](https://user-images.githubusercontent.com/81171294/235969476-737f7885-63a8-42dc-a79e-a8bb7ca45a5e.png)

请问这会影响我后期使用吗？

**Comment by GD2021** [comment]
二。还有几处error反馈
1. #ceph模块构建过程出现错误,请参考/var/lib/dkms/ceph-dkms/0.0.2/build/make.log获取详细错误信息
![image](https://user-images.githubusercontent.com/81171294/235975559-c6124fb0-5cb7-4111-955f-bed9adfcf76c.png)

2.#Ceph模块构建过程出现错误,构建状态异常
![image](https://user-images.githubusercontent.com/81171294/235975886-8317b233-0675-43e1-8cd1-192712eb2f92.png)

3.#proxmox-ve软件包的安装也依赖于ceph-dkms。由于ceph-dkms安装错误,导致proxmox-ve equally也无法配置。
![image](https://user-images.githubusercontent.com/81171294/235976675-91948901-27c6-4740-8f44-c88426e8fbf3.png)

4.从这个输出可以看出,ZFS文件系统模块加载过程中出现了错误。导致zfs-load-module.service单元启动失败,进而影响zfs-import-cache.service的启动
![image](https://user-images.githubusercontent.com/81171294/235977740-6363310b-3843-4324-80e1-f68683c9a1a9.png)

5.处理ceph-dkms与proxmox-ve软件包时出现错误
![image](https://user-images.githubusercontent.com/81171294/235978160-05c666a9-c890-40bf-aef9-356da23cde79.png)

**Comment by ophub** [comment]
你从流览器可以正常进入pve吧。这几个错误可以忽略

**Comment by GD2021** [comment]
好的，可以正常进入
