### ISSUE TITLE
root用户授予不了权限及用户所属的问题。

### ISSUE THREAD

**Issue by Jay-9527** [ophub/amlogic-s9xxx-armbian#1374]
root用户授权不了权限和文件夹的所属问题。

**Device Information | 设备信息**
 - SOC: [ S095W ]
 - Model [ X96 mini ]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100-ophub]
 - Release: [ Bullseye ]

**Describe the bug | 问题描述**

在进行配置Samba服务期间发现

在授权和授予文件夹所属的时，却授予不了

![截屏2023-05-05 下午12 21 13](https://user-images.githubusercontent.com/30925620/236377086-0b57b630-fb5a-40f0-8e1b-ba4a95aedf1f.png)

![截屏2023-05-05 下午12 19 03](https://user-images.githubusercontent.com/30925620/236376899-ad084af5-1f2f-458c-92e0-df9060c106de.png)

并且在普通用户下也使用不了sudo命令。

![截屏2023-05-05 下午12 23 56](https://user-images.githubusercontent.com/30925620/236377340-b06a738b-6f68-4c9d-aeac-9d20c197bedb.png)

【这个结果是参照这个文章所描述的解决方法来配置的：[CentOS7 进入root是报错...](https://blog.csdn.net/dddgggd/article/details/124506093)】

但更大还是因为root用户本身就是0的权限情况下，授予不了相应的权限和所属。

希望能够解决一下。

**Comment by ophub** [comment]
你看错教程了，不要看CentOS，看debian或者ubuntu如何给用户添加sudo权限。
例如： https://www.jianshu.com/p/f8dacdb62e7c

**Comment by Jay-9527** [comment]
另外，在使用armbian-software命令时，同样也是没有权限导致下载不了。
![截屏2023-05-05 下午12 43 32](https://user-images.githubusercontent.com/30925620/236379185-ec9518d1-2ce8-41ce-b1fa-872974578136.png)

**Comment by ophub** [comment]
我猜测你是把U盘插在正在运行的安卓系统了。被安卓把文件系统的权限改了。
必须是断电情况下插入U盘，然后插入电源从USB启动。或者你在安卓系统下执行完了`adb shell reboot update`命令后，看到重启时再插入U盘，你提前插在安卓里，就会被安卓把权限改的无法正常使用了。

**Comment by Jay-9527** [comment]
但在Linux环境中，都是同样的原理。区别是他们是不同的路径和文件而已。

而且我也都是试过了。还是这个问题。

**Comment by Jay-9527** [comment]
不是吧，我这是将armbian 通过install 命令将其写入到eMMCe里面了。

**Comment by Jay-9527** [comment]
按理说，是将其中的安卓系统给覆盖掉了。

**Comment by Jay-9527** [comment]
![截屏2023-05-05 下午12 48 31](https://user-images.githubusercontent.com/30925620/236379641-bacb6c87-bf93-48ac-bfb5-a68c4525d3d2.png)

**Comment by Jay-9527** [comment]
诺。这是我将armbian 写入到eMMce 中的结果。其中，mmcblk1p1是我自己所挂载的SD卡。

**Comment by ophub** [comment]
![Snip20230505_8](https://user-images.githubusercontent.com/68696949/236379709-57fe6740-9c85-4b35-a1a4-40d0d22829fd.png)

不要按理说，你把ARMBIAN的U盘插入安卓系统里，已经被安卓修改了权限了，这个USB里的armbian已经废了，你安装到emmc页是废的系统。即便你没写入emmc，此时从USB/SD/TF卡启动的armbian都是被安卓篡改了权限的系统，如果你看觉得看centos的sudo教程能修复，你可以再试试，我一般都建议重新写U盘，不要浪费时间了，安卓修改了多少目录你是无法列举修复的。

**Comment by Jay-9527** [comment]
![截屏2023-05-05 下午12 52 13](https://user-images.githubusercontent.com/30925620/236380012-adcb3366-fe1c-47f6-b660-303e702649fe.png)

**Comment by Jay-9527** [comment]
OK。行我再重新写入一下armbian.

**Comment by ophub** [comment]
重新写U盘，拔出电源，插入U盘，插入电源启动。
不要把USB/SD/TF插在安卓系统里，一插权限就废了。

**Comment by Jay-9527** [comment]
OK

**Comment by Jay-9527** [comment]
我试试。不行再来问您。

**Comment by Jay-9527** [comment]
搞定了。谢谢

**Comment by Jay-9527** [comment]
搞定了

**Comment by ophub** [comment]
好的

**Comment by bird202301** [comment]
能否把安卓系统改造下，不改外接系统的权限呢？我也是遇到这个问题几天了，没有解决，确实是ophub大神说的那样，我的905L3A盒子系统也是那样被安卓污染的！导致服务启动异常，莫名其妙出现1023用户。
不过我有个905L的R3300L小红盒，运行的是安卓4.4.2老版本，似乎污染不了插入的TF卡，不知原因。
armbian写入EMMC我又怕没把握，怕失败，还得在储备下知识再操作吧。

**Comment by bird202301** [comment]
所以把系统写在外置存储装置很容易头一天还运行好好的，某一天一旦盒子内置安卓系统启动了，并且移动存储还被安卓读到了，会被添加其它用户，权限就混乱了，服务启动异常。

**Comment by Jay-9527** [comment]
> 所以把系统写在外置存储装置很容易头一天还运行好好的，某一天一旦盒子内置安卓系统启动了，并且移动存储还被安卓读到了，将添加其他用户，就权限混乱了，服务启动异常。

解决了。我的是直接写入到EMMC 中来使用的。对于软件的更新也解决了。

**Comment by cgangit** [comment]
我也遇到相同的问题，重刷armbian是把新烧录好的优盘插上开机就能从U盘启动吗，还是需要刷回安卓，重新走一遍所有流程？

**Comment by bird202301** [comment]
> 我也遇到相同的问题，重刷armbian是把新烧录好的优盘插上开机就能从U盘启动吗，还是需要刷回安卓，重新走一遍所有
最好是刷入emmc，否则某一次意外还会导致权限错乱，U盘系统报废，从刷img到U盘即可，盒子自带的安卓不会受到影响

**Comment by cgangit** [comment]
> > 最好是刷入emmc，否则某一次意外还会导致权限错乱，U盘系统报废，从刷img到U盘即可，盒子自带的安卓不会受到影响
就是已经刷入emmc，这种情况需要重新刷入安卓吗？
