### ISSUE TITLE
no dtb for new X96 mini

### ISSUE THREAD

**Issue by ThierryBourbon** [ophub/amlogic-s9xxx-armbian#1376]
Standard chat template, no routine, no chat.
I bought a new X96 mini and I cant start it with armbian

**Device Information | 设备信息**
 - SOC: S905W
 - Model X96 Mini  B00-M96-EMCP-REV1.4
![20230505_134011](https://user-images.githubusercontent.com/65720627/236448944-7aca3305-7469-4126-a6e0-961ce9875fa7.jpg)
![20230505_123910](https://user-images.githubusercontent.com/65720627/236449942-db5446e1-36a2-458f-a5c4-f2991abad69a.jpg)

**Armbian Version | 系统版本**
 Armbian_23.05.0_amlogic_s905w_bullseye_5.15.110_server_2023.05.04
 - Release: Bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

I can't start Armbian with none of the dtbs
meson-gxl-s905w-p281.dtb
meson-gxl-s905w-tx3-mini.dtb
meson-gxl-s905w-x96-mini.dtb
meson-gxl-s905w-x96w.dtb
meson-gxl-s905w-jethome-jethub-j80

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/9c35dd2726f9fab3b6f643677b9f09230d227294/build-armbian/armbian-files/common-files/etc/model_database.conf#L47

**Comment by ThierryBourbon** [comment]
I don't know if this helps:
Following your instructions 
```
cat /dev/dtb >/data/local/mybox.dtb
```
I got this file
[mybox.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11415545/mybox.zip)

**Comment by ThierryBourbon** [comment]
Good morning,
I was happy to receive this box because it is the first where I can easily solder the UART

![20230509_102918](https://user-images.githubusercontent.com/65720627/237040981-61836d25-712f-4d01-a16f-32f7492336a4.jpg)

Unfortunately, I believe that its design has changed and that the usual X96 mini DTB cannot be used.

I note that it is very recent.
-Android 11
- Kernel 4.9.113 #87 SMP PREEMPT Thu Feb 9 20:08:30 CST 2023

Maybe that's why there is no DTB yet
I tried without success to root it to extract the DTB
The only thing I managed to do:
```
adb connect 192.168.1.199
adb root
adb-shell
cat /dev/dtb >/storage/emulated/0/Download/mybox.dtb
```
then download the file in my PC

I got the file from the previous post but it doesn't look like a dtb. Is it encrypted?

Does anyone have this B00-M96-EMCP-REV1.4 box and was able to do something with it?

**Comment by ThierryBourbon** [comment]
I add bootloader.bin and gpio
[dtb-bootloader-gpio.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11429482/dtb-bootloader-gpio.zip)

**Comment by ThierryBourbon** [comment]
I dump starting log with uart. Is this of any use?

[X96_mini_Rev1.4.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11457193/X96_mini_Rev1.4.zip)

**Comment by giovEra** [comment]
Hi, I have a problem with "GTMedia G1" a clone of old x96 mini.

I would like to know if armbian in your old x96 mini when you run the comnado ``sudo poweroff`` it shuts down correctly instead of restarting.

In case it works correctly for you, could you tell me the version of the stock Android build installed on your TV box?

Thanks

**Comment by scara78** [comment]
Hi,just received x96 mini, with android 11. Same story, i cannot boot armbian from sd,or usb (tried various sd cards, stil wont boot)
Is there any way to make it work? 
Please help!

**Comment by giovEra** [comment]
I invite you to check if it is a fake s905w.

I heard other people, who like me, bought this box with Amlogic s905x and android 11, and in truth it has Rockchip rk3228a SoC.

Try starting "[Multitool](https://users.armbian.com/jock/rk322x/multitool/multitool.img.xz)".
If it starts it means you have a rockchip rk322x and not a s905w.
Guide for Multitool is avaiable [here](https://forum.armbian.com/topic/12656-csc-armbian-for-rk322x-tv-boxes/page/45/#comment-135407).
All credits for Multitool go to [jock](https://forum.armbian.com/profile/1002-jock/) at [armbian forum](https://forum.armbian.com/topic/12656-csc-armbian-for-rk322x-tv-boxes/)

**Comment by Snoopbest12** [comment]
> Je vide le journal de départ avec uart. Est-ce utile?
> 
> [X96_mini_Rev1.4.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11457193/X96_mini_Rev1.4.zip)
> 
> ( la console fonctionne )

Hello, I too have the same SOC as Thierry Bourbon do you have a compatible firmware and a tutorial please

**Comment by 0x2f0713** [comment]
Did you boot this? I have same board

**Comment by B0mberManFanky** [comment]
hello guys i need a full dump or firmware for this model X96 Mini B00-M96-EMCP-REV1.4 can any one share

**Comment by livedevlab** [comment]
[s_22-02-24-17_X69_MINI_S905W_800-M96-EMCP-REV1.ZIP](https://tgstat.ru/channel/@an9999989/4071)

**Comment by B0mberManFanky** [comment]
thanks friend

Le dim. 21 avr. 2024 à 13:11, livedevlab ***@***.***> a
écrit :

**Comment by livedevlab** [comment]
Drop the dump from TWRP

**Comment by Spothz** [comment]
> Дамп из eMMC: [s_22-02-24-17_X69_MINI_S905W_800-M96-EMCP-REV1.4.ZIP](https://tgstat.ru/channel/@an9999989/4071)

what application was used to extract this dump?

**Comment by drno88** [comment]
did you manage to find dtb? I have the same console and I really need any Linux for it...

**Comment by Mykola2** [comment]
I managed to boot Armbian manually by interrupting uboot. I did this by connecting the UART to the PC's serial port, which is the same method that @ThierryBourbon used. I pressed keys repeatedly while the device was booting, until the console appeared. First, it seems that we have an S905L3 SoC based on the U-Boot logs. You can see this line in the attached logs above: 
`"U-Boot 2015.01-g0d95d91cc4-dirty (Feb 09, 2023, 20:00:18), Build: jenkins-S905L3."` 
I'm not sure if this is indicative.

Then, I booted Armbian by executing the following in the console:
`fatload mmc 0 0x1000000 aml_autoscript`
`autoscr 0x1000000`

with a disabled GPU driver in extlinux:
`APPEND root=UUID=... rootflags=data=writeback modprobe.blacklist=lima`

It booted with no HDMI detected, and the eMMC is not accessible.
