### ISSUE TITLE
如何重新U盘安装armbian

### ISSUE THREAD

**Issue by qtxie** [ophub/amlogic-s9xxx-armbian#1378]
**Device Information | 设备信息**
- CM311-1a-yst

**Armbian Version | 系统版本**
 - Armbian_23.05.0_amlogic_s905l3a_bullseye_6.1.27_server_2023.05.07.img

**Describe the bug | 问题描述**

已安装armbian到eMMC上，启动正常。但是没法sudo，所有文件uid都是1023，而不是 0 (root)。估计是U盘插在了android系统上，权限被改写了。打算重新用U盘安装，但是插入U盘开机，系统不会从U盘启动。请问如何解决？

```
root@armbian:~# armbian-install
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ ERROR ] Current system is already installed to eMMC!
```

**Comment by yangchaohong** [comment]
https://www.cnblogs.com/sylvia-/p/13673087.html

**Comment by qtxie** [comment]
@yangchaohong 谢谢！试过了。一两个文件还行，问题是所有的文件不是root权限。重装会比较好。

**Comment by yangchaohong** [comment]
线刷吧

**Comment by qtxie** [comment]
@yangchaohong 不知道怎么刷😓，有文档吗？

**Comment by OliverYN** [comment]
https://github.com/ophub/kernel/releases/download/tools/android_tv_cm311-1a-yst_s905l3a.tar.xz
下载这个，里边有刷机方法和固件

**Comment by ophub** [comment]
这个是U盘提前插入安卓系统导致的，u盘里的armbian系统的权限被安卓给篡改了。
正确的刷armbian的方法：
（必须重新写，现在U盘里的armbian已经是被安卓污染的系统，不重新写U盘的系统，再安装至emmc也没有）

一、盒子已经从U盘安装过，就不用刷回安卓了，直接重新写一下U盘
1.拔出盒子的电源
2.插入USB
3.插入盒子的电源开机
4.等1分钟后到路由器看armbian的IP
5.ssh访问armbian的IP，进行armbian-install安装。

二、如果是第一次从安卓启动
1.adb连接盒子的ip，如：adb connect 192.168.1.xxx
2.开启adb更新: adb shell reboot update
3.屏幕看盒子重启了（没有屏幕的默数3秒），再把U盘插入盒子的USB口
4.等1分钟后到路由器看armbian的IP
5.ssh访问armbian的IP，进行armbian-install安装。

**Comment by qtxie** [comment]
@OliverYN 谢谢！
@ophub 我昨天重写了U盘，但是盒子没从U盘启动。我今天再试试。

**Comment by janko888** [comment]
> 一、盒子已经从U盘安装过，直接重新写一下U盘

这个soc是s905l3a,用内核6.x的镜像写入emmc后，常规的流程是无法再次从usb启动的，即使重新写入usb镜像；可以试一下我这个临时流程：
1，重新写入6.x镜像到usb里；
2，删除U盘里面的u-boot.ext,同时复制u-boot-u200.bin文件为u-boot.ext；
3，插入U盘，盒子通电，lsblk一下看看是否正常从u盘加载系统正常了；
4，在当前的系统中进入/boot/目录，把u-boot.ext删除，同时复制u-boot-e900v22c.bin文件为u-boot.ext(这点很重要，不改的话写入后EMMC启动不了)
5，使用armbian-install写入emmc;

**Comment by Scirese** [comment]
其实如果想避免被安卓改权限，只需要把镜像根目录的默认文件系统换成btrfs就行。

~~但是我没见过有任何其他项目默认用了btrfs，所以我也不确定这样是否合适？~~

**Comment by ophub** [comment]
btrfs也是支持的格式，使用这个没问题

**Comment by heyeshuang** [comment]
> 这个soc是s905l3a,用内核6.x的镜像写入emmc后，常规的流程是无法再次从usb启动的，即使重新写入usb镜像

可以按照[这里](https://forum.armbian.com/topic/19431-booting-armbian-from-usb-when-its-already-installed-on-emmc/#comment-132545)的步骤：

1. 插入优盘并开机；
2. 开机时按下任意键停止自动启动；
3. 输入命令
```bash
setenv boot_targets "romusb usb0 usb1 usb2 usb3 mmc0 mmc1 mmc2 pxe dhcp"
boot
```
应该就可以从usb启动了。

**Comment by janko888** [comment]
> ```shell
> setenv boot_targets "romusb usb0 usb1 usb2 usb3 mmc0 mmc1 mmc2 pxe dhcp"
> boot
> ```

这种需要拆接TTL线的了吧

**Comment by heyeshuang** [comment]
不用，在屏幕显示stop autoboot的时候敲键盘就行。
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1888231/2b895811-0854-4580-81b2-e54f26eb2da4)

**Comment by janko888** [comment]
SSH党几乎没接过USB键盘,还真不知道有这个玩法。

**Comment by qq471847975** [comment]
那么麻烦的嘛？，删除/boot/目录就行了

**Comment by ThisisSupervip** [comment]
把u盘的boot分区的uEnv.txt 复制到/boot/uEnv.txt 记得备份 重启失败进入initframfs 挂载/mmcblk2p1还能恢复过来

**Comment by bo6907367** [comment]
1插u盘并启动，用lsblk  -f      查看u盘UUID
2修改uEnv.txt
3改APPEND=root=UUID=xxxxxxxxxxxxxxxxxxxxxx 为u盘的UUID
4重启一定是U盘引导
