### ISSUE TITLE
不插U盘不启动，

### ISSUE THREAD

**Issue by gametta** [ophub/amlogic-s9xxx-armbian#1379]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]
B863 AV 3.2-M
**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]
6.1.27  bullseye
**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
B863 AV 3.2M     
选 306          2-btrfs
正常刷机后启动正常  断电后十分钟再开机，有一定几率黄灯不开机，如果随便插入一个U盘就能正常开机，期间随便重启，只要不断电超过十分钟，就一切正常，貌似问题在开机检测U盘，检测不到卡死了。
请问修改那里可以直接让它从内部的存储启动。因为以后有问题了直接刷机了，从U盘再启动的意义不大了。另外即便是插入启动U盘它也不会从U盘启动，仅仅检测了一下还是从内部存储启动了。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by gametta** [comment]
#1291 这个上面就是我说的类似的问题，断电后不开机，但是只要插个U盘就能开始，希望大佬看一下那里的问题。应该比较简单的地方，我现在回到5.15.108  就是4月14那天的版本都没啥问题。

**Comment by ophub** [comment]
你的问题我想不到原因，正常的机器如果随便插个U盘是不会启动，U盘里面啥也没有凭啥他能启动了EMMC里的系统呢？这只会造成无法启动。
所以你不插U盘不行，随便插个其他U盘就可以，这不符合启动要求，我想不清楚为什么。

**Comment by sesame-foxes** [comment]
遇到了同样的情况，机型m401a。一段时间断电后就必须插入U盘才能启动

**Comment by gametta** [comment]
方法1   用5.15.108     6.1.24   就是4月14日的版本或者之前的。
方法2  等，十来分钟应该会好。

**Comment by sesame-foxes** [comment]
> 方法1 用5.15.108 6.1.24 就是4月14日的版本或者之前的。 方法2 等，十来分钟应该会好。

如何下到以前的版本呢？
