### ISSUE TITLE
apt update报错 

### ISSUE THREAD

**Issue by hjc757** [ophub/amlogic-s9xxx-armbian#138]
apt update报错

**Comment by ophub** [comment]
什么设备，什么错？我猜不到你发生的错误。

**Comment by EastWoodYang** [comment]
x96 max+，昨天重新刷的时候也出现了
![WechatIMG158](https://user-images.githubusercontent.com/9335046/157167292-eaf4db6d-5ef6-469f-a134-52189a7e5e58.jpeg)

**Comment by ophub** [comment]
如果你访问不了阿里，可以自己更换源。
/etc/apt/sources.list.bak 这个文件是原来的。
你可以把现在阿里的改名，把原来源恢复：
```
mv /etc/apt/sources.list  /etc/apt/sources.list.aliyun
mv /etc/apt/sources.list.bak  /etc/apt/sources.list
```
你也可以自己编辑/etc/apt/sources.list更换成你能访问的服务器。

**Comment by ophub** [comment]
![Snip20220308_2](https://user-images.githubusercontent.com/68696949/157168490-39b13422-29c6-4dd5-acbb-b184158ba8e5.png)

刚才我测试了下阿里的bullseye是可以使用的。你的网络如果访问不了就更换其他源吧。

**Comment by EastWoodYang** [comment]
更换到其他源，遇到这个问题，早上是刷的5.16的包

**Comment by ophub** [comment]
和5.15或5.4无关，是你的盒子访问阿里这个镜像的域名有问题。
你可以考虑下你的路由器的dns是否合适。尝试更换114.114.114.114等dns。

**Comment by EastWoodYang** [comment]
嗯嗯，刚替换到官方源  正常了

**Comment by ophub** [comment]
好的，恭喜你

**Comment by hjc757** [comment]
> 嗯嗯，刚替换到官方源 正常了

官方源是什么？

**Comment by ophub** [comment]
```
mv /etc/apt/sources.list /etc/apt/sources.list.aliyun
mv /etc/apt/sources.list.bak  /etc/apt/sources.list
```
