### ISSUE TITLE
众云世纪 ZYSJ（RK3399）新机型适配反馈

### ISSUE THREAD

**Issue by GD2021** [ophub/amlogic-s9xxx-armbian#1380]
型号：众云世纪ZYSJ-RK3399安卓解码驱动一体板
存储：2+8g（自用）
板型图：http://oss.html-5.me/view.php/06a059f75bf0a14ad82a28d6dfdde3ce.jpg

![image](https://user-images.githubusercontent.com/81171294/236763850-250a050b-266d-4907-b4a8-f3a4b43f51a9.png)
![image](https://user-images.githubusercontent.com/81171294/236763945-4b816d4a-e08c-4f8e-a17e-606edfcfa365.png)

UBOOT
https://github.com/cm9vdA/build-linux/blob/master/u-boot/rockchip/u-boot-2023.01/zysj-rk3399_defconfig

dtsi
https://github.com/cm9vdA/build-linux/blob/master/boot/dts/rockchip/mainline/rk3399-zysj-u-boot.dtsi

dts
https://github.com/cm9vdA/build-linux/blob/master/boot/dts/rockchip/mainline/rk3399-zysj.dts

dtb
https://github.com/cm9vdA/build-linux/tree/master/boot/dts/rockchip/bsp

env
https://github.com/cm9vdA/build-linux/tree/master/env

官网：http://www.zysj-sz.com/productshow.asp?id=805

**Comment by GD2021** [comment]
http://www.zysj-sz.com/product/20210618144551403.jpg

**Comment by ophub** [comment]
添加情况：
https://github.com/ophub/amlogic-s9xxx-armbian/commit/c8c4d17f434a975f1d3140fae4e07952f02495fb


DTS和U-BOOT文件： https://github.com/cm9vdA/build-linux
内核使用源码：     https://github.com/unifreq/linux-6.1.y
U-BOOT使用源码：  https://github.com/u-boot/u-boot
rkbin使用源码：   https://github.com/rockchip-linux/rkbin

内核和U-BOOT编译都很顺利，没报错，你试试能不能用用吧：
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_05.08.2308

**Comment by GD2021** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81171294/daf1f2a9-d26d-4871-b1c3-58ffc37ef7ec)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81171294/a9b0b6d6-020c-48ce-8a77-ce24a201efa3)

固件：https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_05.08.2308
反馈：就只有这一处报错，其余正常

**Comment by GD2021** [comment]
固件反馈：系统启动一切正常，没有报错，只是USB2.0插入键盘不可用，3.0正常，tpyec正常。

**Comment by GD2021** [comment]
请更新bullseye版

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_bullseye_05.09.0944

bullseye

**Comment by GD2021** [comment]
线刷时的bin我用的这个没问题吧？
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81171294/8dc71890-d9f7-4dbd-949b-562ef67ca46e)

**Comment by ophub** [comment]
ttl你没接所以错误可以忽略了

**Comment by GD2021** [comment]
用的这个
http://oss.html-5.me/down.php/19bfaa61a143d6218ddea068f6307dff.bin

**Comment by ophub** [comment]
好的。

**Comment by inoeud** [comment]
反馈，usb3.0 *2 (typec usb A)都不正常，速率跑在2.0，usb2.0用不了。

**Comment by inoeud** [comment]
> 我看到有人反馈USB问题，原因我也不清楚，我这边用docker编译的Armbian是正常的，截图从上到下三个依次是USB3.0，Type-C和USB2.0插入外设以后的识别情况。
> 
> ![zysj](https://user-images.githubusercontent.com/11437228/239158536-3fef9feb-8140-4b85-9649-35f8df5bbb8a.png)

是的，我用这个固件也正常，但是dmesg多了很多报错，具体原因不明白。linux苦手。

固件链接：http://files.kos.org.cn/%E7%91%9E%E8%8A%AF%E5%BE%AE/ZYSJ-rk3399%26ZYSJ1739A/Armbian_23.02.0-trunk_Zysj_bullseye_current_6.1.27.img.gz

**Comment by inoeud** [comment]
![G9JDUSOK6E@AO% }X3ZH2EY](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37056214/49a5dcb5-3711-4271-82df-ed6b5b839bcc)
![7}8AZ3F 3DFCIFJB ZY@SL9](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37056214/94ebe865-dd4d-4db3-b1e0-d7ad3c5b8504)
![KG2PF0(8U{TD~0I 8%))$}G](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37056214/b59d1f09-c95f-4de0-a353-77d52318dc0c)
![RGK9AJ(7L55VN4`6EKB}P01](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37056214/a74b2a00-1b74-40b7-887b-61c810804866)

[dmesg.log.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11505147/dmesg.log.txt)

**Comment by inoeud** [comment]
usb设备
![0)Q2%Z%C38(9VD0{8`KD435](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37056214/f08409f1-23c8-489c-b3e9-74771ce991f1)

**Comment by inoeud** [comment]
root@LittleBusters:~# dmesg -lerr
[    4.011758] rk_gmac-dwmac fe300000.ethernet: cannot get clock clk_mac_speed
[    4.241916] dw-apb-uart ff180000.serial: Failed to create device link (0x180) with 0-001b
[    4.279982] dw-apb-uart ff180000.serial: Failed to create device link (0x180) with 0-001b
[   17.358073] systemd[273]: /usr/lib/systemd/system-generators/netplan failed with exit status 1.
[   22.775505] systemd[1]: systemd-networkd.socket: Socket service systemd-networkd.service not loaded, refusing.
[   22.775595] systemd[1]: Failed to listen on Network Service Netlink Socket.
[   30.417055] OF: graph: no port node found in /i2c@ff3d0000/fusb302@22
[   30.540978] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   30.701248] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Aug 25 2015 18:58:57 version 7.45.69 (r581703) FWID 01-24037f6e
[   31.103235] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[   31.103243] Bluetooth: hci0: BCM: 'brcm/BCM4345C0.rockchip,rk3399.hcd'
[   31.103247] Bluetooth: hci0: BCM: 'brcm/BCM4345C0.hcd'
[   31.103251] Bluetooth: hci0: BCM: 'brcm/BCM.rockchip,rk3399.hcd'
[   31.103255] Bluetooth: hci0: BCM: 'brcm/BCM.hcd'

**Comment by zqs2020git** [comment]
4+32能直接拿来用吗

**Comment by zqs2020git** [comment]
4+32能拿来直接用吗  还是说要修改

**Comment by Lemon1151** [comment]
不能tf卡启动，uboot应该有点问题

**Comment by Lemon1151** [comment]
> 我看到有人反馈USB问题，原因我也不清楚，我这边用docker编译的Armbian是正常的，截图从上到下三个依次是USB3.0，Type-C和USB2.0插入外设以后的识别情况。
> 
> ![zysj](https://private-user-images.githubusercontent.com/11437228/239158536-3fef9feb-8140-4b85-9649-35f8df5bbb8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjY0NjMsIm5iZiI6MTcxNzEyNjE2MywicGF0aCI6Ii8xMTQzNzIyOC8yMzkxNTg1MzYtM2ZlZjlmZWItODE0MC00Yjg1LTk2NDktMzVmOGRmNWJiYjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAzMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZWYxMTA0NTUwYzY5MjdmYjg1NzQzZTdmMmRhYWJjNmY3NjUyMjIwODEyNDE2OTg5NjNkYTRhYTRhOGY4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uBvNIEW972JWrGXxGsJIQRG1xpfSfO1jfqNYtFxWvQM)

群里有人反馈不能tf卡启动，是不是defconfig配置有问题？

**Comment by Lemon1151** [comment]
> > > 我看到有人反馈USB问题，原因我也不清楚，我这边用docker编译的Armbian是正常的，截图从上到下三个依次是USB3.0，Type-C和USB2.0插入外设以后的识别情况。
> > > ![zysj](https://private-user-images.githubusercontent.com/11437228/239158536-3fef9feb-8140-4b85-9649-35f8df5bbb8a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcxMjY0NjMsIm5iZiI6MTcxNzEyNjE2MywicGF0aCI6Ii8xMTQzNzIyOC8yMzkxNTg1MzYtM2ZlZjlmZWItODE0MC00Yjg1LTk2NDktMzVmOGRmNWJiYjhhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMxVDAzMjkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxZWYxMTA0NTUwYzY5MjdmYjg1NzQzZTdmMmRhYWJjNmY3NjUyMjIwODEyNDE2OTg5NjNkYTRhYTRhOGY4YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uBvNIEW972JWrGXxGsJIQRG1xpfSfO1jfqNYtFxWvQM)
> > 
> > 
> > 群里有人反馈不能tf卡启动，是不是defconfig配置有问题？
> 
> 能否tf启动和defconfig没啥关系，从我之前编译原版Armbian的经验来看，和boards里板子配置文件中的`BOOT_SCENARIO`参数有关，配置为`only-blobs`以后生成的固件是支持tf启动，改成其他的就可能不支持了，具体的原理我没有去深入了解过。

那就是ophub编译的那个.conf里的BOOT_SCENARIO参数没对？
