### ISSUE TITLE
unt403a不能写入emmc

### ISSUE THREAD

**Issue by fwfmeimei** [ophub/amlogic-s9xxx-armbian#1381]
unt403a
芯片：S905L3ab.

用u盘烧录armbian的版本S905L3a可以正常刷入，但是写入emmc错误。
怀疑是因为芯片是S905L3ab的原因，请问大佬有匹配S905L3ab的armbian固件吗？

**Comment by fwfmeimei** [comment]
![屏幕截图 2023-05-08 213441](https://user-images.githubusercontent.com/132913593/236838254-2ec34375-8198-4d79-b140-bcb5c576b962.jpg)

**Comment by janko888** [comment]
more /boot/uEnv.txt
more /sys/kernel/debug/mmc2/ios

执行这两条命令看看你当前系统的信息

**Comment by janko888** [comment]
more /boot/uEnv.txt
more /sys/kernel/debug/mmc2/ios

执行这两条命令看看你当前系统的信息

**Comment by fwfmeimei** [comment]
> more /boot/uEnv.txt more /sys/kernel/debug/mmc2/ios
> 
> 执行这两条命令看看你当前系统的信息

![屏幕截图 2023-05-08 225120](https://user-images.githubusercontent.com/132913593/236856848-7a452bb9-3629-4955-91d6-74d6071bafe0.jpg)

**Comment by janko888** [comment]
修改/boot/uEnv.txt里面的dtb为meson-g12a-s905l3a-m401a.dtb，重启后\重启后\重启后
再用306写入试试
armbian-install 和 armbian-install -m yes，先后测试一下

不过这里你EMMC的实际运行频率也不低，不知道这个降频有没用

**Comment by fwfmeimei** [comment]
> 修改/boot/uEnv.txt里面的dtb为meson-g12a-s905l3a-m401a.dtb，重启后\重启后\重启后 再用306写入试试 armbian-install 和 armbian-install -m yes，先后测试一下
> 
> 不过这里你EMMC的实际运行频率也不低，不知道这个降频有没用

可以了谢谢大佬
