### ISSUE TITLE
E900v22D写入emmc

### ISSUE THREAD

**Issue by tianchaopow** [ophub/amlogic-s9xxx-armbian#1384]
需要对/boot/dtb/amlogic下编译
（1）首先执行
dtc -I dtb -O dts -o meson-g12a-s905l3a-e900v22c.dts meson-g12a-s905l3a-e900v22c.dtb
（2）其次，根据如下参数调整meson-g12a-s905l3a-e900v22c.dts文件的emmc最大频率值
/* SD card */
&sd_emmc_b {
	status = "okay";

	bus-width = <4>;
	cap-sd-highspeed;
	sd-uhs-sdr12;
	sd-uhs-sdr25;
	sd-uhs-sdr50;
	max-frequency = <100000000>;
};

/* eMMC */
&sd_emmc_c {
	status = "okay";

	bus-width = <8>;
	cap-mmc-highspeed;
	max-frequency = <100000000>;
};
（3）最后执行如下命令
meson-g12a-s905l3a-e900v22c.dtb meson-g12a-s905l3a-e900v22c.dts
（4）最后需要重启在进行armbian-install落盘到emmc，写入完毕无误后，poweroff，拔掉U盘然后在启动，就可以了。
<img width="957" alt="3" src="https://user-images.githubusercontent.com/74761971/236877379-4cbd4fcd-c29c-424b-bec3-c353b3e8d688.png">
<img width="957" alt="2" src="https://user-images.githubusercontent.com/74761971/236877387-83a7070f-7ea4-4145-b4ee-cc65a19d0253.png">
<img width="957" alt="1" src="https://user-images.githubusercontent.com/74761971/236877389-99144a9b-bde6-4737-9187-129b1fc24fb2.png">
<img width="960" alt="4" src="https://user-images.githubusercontent.com/74761971/236877504-e4504e59-1021-4b8f-b640-09c74e4cde1b.png">

**Comment by ophub** [comment]
好建议

**Comment by tianchaopow** [comment]
> 好建议

大佬的指导文档很给力！

**Comment by ottoskyer** [comment]
第三步少了dtc -I dts -O dtb -o，参考12.13

**Comment by ottoskyer** [comment]
关于sd_emmc_b，sd_emmc_c有个疑问，我的e900v22c使用的Armbian_23.08.0_amlogic_s905l3a_bullseye_6.1.42_server_2023.08.01.img包，反编译为dts后没有找到sd_emmc_b，sd_emmc_c，却是如下格式的
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/40727785/18568d75-7ea9-4eb4-af17-47cd35124e67)
，这是版本的原因吗？我mmc1的max-frequency为0x2faf080，mmc1的max-frequency为0xbebc200，我就改了mmc2的节点与mmc1相同，最后安装到emmc成功了。我看12.16的教程是重大到小的改，我这样改是否会影响性能？
