### ISSUE TITLE
N1写入EMMC后拨掉U盘可以正常启动，插上U盘或移动硬盘后通电就不能启动

### ISSUE THREAD

**Issue by dushez** [ophub/amlogic-s9xxx-armbian#1386]
**Device Information | 设备信息**
 - SOC: S905D
 - Model N1

**Armbian Version | 系统版本**
 - Kernel Version: 5.1.110  6.1.27两个都试过
 - Release: bullseye

**Describe the bug | 问题描述**
5月8号和5月9号发布的固件都试过，用U盘启动后armbian-install写入EMMC
拨掉U盘后启动正常，插上U盘或移动硬盘后再通电就无法启动，一直反复加载引导程序

拨掉U盘或移动硬盘正常启动画面
Bus usbtcss0
Register 2000140 NbrPorts 2
Starting thecontroller
USB XHC1 1.00
scanning bus usbec9000000 for devices... 2 USB Device(s) found
scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot: 0
Device 0:unknown device
Card did not respond to voltage select?:-110
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mc 1:1...
Found U-Boot script /boot.scr
1025 bytes read in 1 ms (1001 KiB/s)
##Executing script at 08000000
Start AMLOGIC mainline U-boot
##Error: "bootfromsd" not defined
Couldn't find partition mmc 2
376 bytes read in 1ms (367.2 KiB/s)
##Error:"mac"not defined
##Error:"eth mac"not defined
ethaddr=22:07:ff:f7:91:ef
33321472 bytes read in 752 ms(423MiB/s)
17992385 bytes read in 407 ms(42.2 MiB/s)
41556 bytes read in 3ms(13.2 MiB/s)
Moving Inage from 0x8080000 to 0x8200000，end=a2b0000
##Loading init Ramdisk from Legacy Image at 13000000 ...
Image Name:uInitrd
Image Type:AArch64 Linux RAMDisk Image (gzip compressed)
Data Size:17992321 Bytes =17.2 MiB
Load Address:00000000
Entry Point:00000000
Verifying Checksum ... OK
##Flattened Device Tree blob at 08008000
Booting using the fdt blob at 0x8008000
Loading Randisk to 7ae0c000,end 7bf34a81 OK
Loading Device Tree to 000000007adfe000,end 000000007ae0b253
Starting kernel ...
到这里就可以正常启动

插上U盘或移动硬盘后启动画面
`Card did not respond to valtage select! -110
Scaming disk mmc070000blk..
Disk mmc070000.blk not ready
Scanning disk mmc74000blk...
Scaming disk usb_mass_storage.luno...
Found 6 disks
No EFI system partition
BootOrder not defined
EFI boot manager: Cannot load any image
Card did not respond to voltage select?:-110
switch to partitions #0, OK
mmc1(part 0) is current device
Scaming mmc 1:1..
Found U-Boot script/boot.scr
1025 bytes read in 1 ms(1001 KiB/s)
##Executing script at 08000000
Start AMLOGIC mainline U-boot
##Error: "bootfromsd" not defined
Couldn't find partition mmc 2
376 bytes read in 1 ms(367.2 kiB/s)
##Error:"nac"not defined
##Error: "eth mac" not defined
ethaddr=22:07:ff:f7:91:ef
33321472 bytes read in 754 ms(42.1 MiB/s)
17992385 bytes read in 406 ms(42.3 MiB/s)
41556 bytes read in 2ms(19.8MiB/s)
Moving Inage from 0x8080000 to 0x8200000，end=a2b0000
#Loading init Randisk from Legacy Image at 13000000
Image Name:uInitrd
Image Type:AArch64 Linux RAMDisk Image(gzip compressed)
Data Size:17992321 Bytes=17.2 MiB
Load Address:00000000
Entry Point:00000000
Verifying Checksum... OK
##Flattened Device Tree blob at 08008000
Booting using the fdt blob at 0x8008000
Loading Randisk to 7ae0c000,end 7bf34a81...OK
Loading Device Tree to 000000007adfe000,end000000007a0b253
"Synchronous Abort" handler, esr0x96000004
elr:6000000001063248 lr:00000000010533e4(reloc)
eir: 000000007dfb6248 lr :000000007dfa63e4
x0:719e59007db0ecf2 x1:000000007dfbde08
x2:0000000000000010 x3:000000007df81f80
x4:0000000000000000 x5:719e59007db0ecf2
x6:0000000001000000 x7:000000000000000
x8:0000000000000007 x9:000000000000000
x10:000000000000178 x11:000000007bf3685c
x12:0000000000000a4 x13:000000007bf36818
x14:00000007adfe000 x15:0000000000000020
x16:00000007df805a4 x17:0000000000000000
x18:00000007bf42dd0 x19:000000007af37040
x20:0000000074f53fc8 x21:000000007dfbde08
x22:000000000000100 x23:600000007bf4a700
x24:00000007dfdc1do x25:0000000001000000
x26:000000000000000 x27:0000000001000000
x28:000000000001000 x29:000000007bf36810

Code:eb02089f 54000061 52800000 14000006(386468a3)
Resetting cPu`
然后断电重新出现开机画面运行到这段，并一直重复

试过在uboot里面将boot_targets启动顺序将usb0调整到mmc1后面，插上U盘时可以正常启动，但uboot下不支持saveenv命令，所以断电后也会不能启动

尝试修改/boot/boot.scr文件，但做任何修改都会导致不能引导

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by CinFree** [comment]
这种情况得刷回安卓(webpad yyf 原厂固件都行) 然后再用u盘启动，在写入emmc

**Comment by dushez** [comment]
刚才换了另一种方式试过可行
找一个以前插U盘可以正常从EMMC启动的固件，写入到U盘，然后从U盘启动，再把EMMC的boot分区挂载上，把/boot（U盘系统里的）下的u-boot.ext文件复制到EMMC的boot分区，然后修改EMMC的boot/extlinux/extlinux.conf文件里的root路径到EMMC的ROOTFS
简单点说就是换回以前的u-boot.ext文件，并修改修改EMMC的boot/extlinux/extlinux.conf文件。
现在的uboot使用的是uEnv.txt文件配置

**Comment by Matrix-Chen** [comment]
外接硬盘使用NTFS格式就不影响重启（见“章鱼星球写入EMMC后插硬盘，EMMC无法启动#1264”），但又出现了关于docker的一个问题。若docker使用了overlay2，并将容器路径改到了外接硬盘，那么NTFS格式的硬盘会导致docker无法正常启动。

**Comment by 837468220** [comment]
> 刚才换了另一种方式试过可行 找一个以前插U盘可以正常从EMMC启动的固件，写入到U盘，然后从U盘启动，再把EMMC的boot分区挂载上，把/boot（U盘系统里的）下的u-boot.ext文件复制到EMMC的boot分区为u-boot.emmc文件，然后修改EMMC的boot/extlinux/extlinux.conf文件里的root路径到EMMC的ROOTFS路径或UUID
> 
> 简单点说就是换回以前的u-boot.ext文件，并修改修改EMMC的boot/extlinux/extlinux.conf文件。
> 
> 现在的uboot使用的是uEnv.txt文件配置
这样改了以后 ， 还能从U盘启动不？

**Comment by 837468220** [comment]
找到了一个可用的方法
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1220#issuecomment-1788326917
