### ISSUE TITLE
请教一下创维v22e的盒子S905L 2-B    该怎么选择安装包和dtb文件

### ISSUE THREAD

**Issue by smerckzak** [ophub/amlogic-s9xxx-armbian#1387]
弄了个v22e到手才发现这个和网上搜到的大部分机子的 cpu都不一样。。。巨坑啊

**Comment by ophub** [comment]
l2可以先试试，这几个盒子有些通用

**Comment by smerckzak** [comment]
> l2可以先试试，这几个盒子有些通用

请问这个安装包有没镜像？18k19k的要命了

**Comment by ophub** [comment]
搜github下载加速，有cdn服务的网站。

**Comment by smerckzak** [comment]
> 搜github下载加速，有cdn服务的网站。

找了一个可以下的，谢谢大佬啊~~

**Comment by ophub** [comment]
从U盘启动系统不会对你的盒子里的安卓系统有任何影响，所以你可以反复测试相近的几个镜像，看看哪个可以使用。

**Comment by uitcis** [comment]
一样![IMG_20230511_190905](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42439330/93cc5108-fe0a-4fc6-ab2a-9f0401ae8b62)

**Comment by smerckzak** [comment]
> 从U盘启动系统不会对你的盒子里的安卓系统有任何影响，所以你可以反复测试相近的几个镜像，看看哪个可以使用
谢谢大佬，还要先解决u盘启动的问题，买的裸机没遥控

**Comment by smerckzak** [comment]
> 一样![IMG_20230511_190905](https://user-images.githubusercontent.com/42439330/237668479-93cc5108-fe0a-4fc6-ab2a-9f0401ae8b62.jpg)

兄弟你這臺機器比我的好，正面清一色金士頓標識。我的存儲是金士頓正面，邊上兩個小的給焊接到背面了，這部機器偷工減料，cpu就貼個小鐵皮，e900-s有一個散熱矽膠塊，後蓋上4個螺絲固定一塊大鐵片壓著散熱膠塊。回頭去修電腦那裡找一塊純銅散熱片給粘上去

**Comment by smerckzak** [comment]
> 一样!
兄弟你刷了这台机器没？如果看到消息麻烦留个q，我想要一下这台机器安卓的原始备份或者有权限的系统备份，，，，我刷了个系统，目测是移植过来的，表面是当贝桌面，内里设置全是移动的设置，系统密码没有，，还没有办法开启adb。

**Comment by uitcis** [comment]
我是通过下载了一个第三方的设置程序打开adb的

**Comment by uitcis** [comment]
> > 一样!
> > 兄弟你刷了这台机器没？如果看到消息麻烦留个q，我想要一下这台机器安卓的原始备份或者有权限的系统备份，，，，我刷了个系统，目测是移植过来的，表面是当贝桌面，内里设置全是移动的设置，系统密码没有，，还没有办法开启adb。

**Comment by uitcis** [comment]
> > 一样!
> > 兄弟你刷了这台机器没？如果看到消息麻烦留个q，我想要一下这台机器安卓的原始备份或者有权限的系统备份，，，，我刷了个系统，目测是移植过来的，表面是当贝桌面，内里设置全是移动的设置，系统密码没有，，还没有办法开启adb。

QQID BLUITCIS
