### ISSUE TITLE
MDA-16-AA first_run.txt脚本中的网络配置不起作用

### ISSUE THREAD

**Issue by lochuan** [ophub/amlogic-s9xxx-armbian#1388]
**Device Information | 设备信息**
 - SOC: s905L
 - Model 小米盒子3(MDZ-16-AA)

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.27
 - Release: jammy

**Describe the bug | 问题描述**

first_run.txt脚本中配置了Wi-Fi连接，但booting后无线网络并没有连接，由于小米盒子3只有一个USB连接口，没有网线接口，想通过这种方式连接无线然后ssh进去管理小米盒子3

通过HUB+键盘的方式应该行得通，这个问题询问过7JI，由于手头的HUB是USB3.0，但u-boot不支持boot via USB3.0

**Comment by ophub** [comment]
无线驱动可用的情况下，初次启动时在没有线网络的情况下，会提问是否链接无线。
如果没提示，可能是无线驱动无法使用。
你可以接个usb转网卡使用。
