### ISSUE TITLE
X96 max + [2+16G, 100M, RTL8189ftv ] "No space left on device" after running several hours from eMMC (kernel 5.4)

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#139]
I got success to run my X96 max + [2+16G, 100M, RTL8189ftv ] on eMMC.
By the way, after several hours running, there is error message on the log "No space left on device".
![IMG_5873](https://user-images.githubusercontent.com/22479095/157147181-317e8499-bfa0-4668-bebb-59fc3268e849.JPG)

But when I check the available space, there are still 12GB available on /dev/mmcblk2p2
<img width="602" alt="Screen Shot 2022-03-08 at 08 15 34" src="https://user-images.githubusercontent.com/22479095/157147317-a864e3f8-3cad-4381-9d55-e112d050dabc.png">

**Comment by ophub** [comment]
You can check the space in use with:
```
sudo du -h /var/log/
```

In my case I'm using 4.5 GB with 4.1GB in /var/log/journal. So if you want to limit the size of your log journal to 100MB you can do:
```
sudo journalctl --vacuum-size=100M
```

If you installed applications and later you uninstalled them, common libraries no longer in use may be using space in your disk. You can clean that space with:
```
sudo apt autoremove
```

**Comment by dinhchinh82** [comment]
> In my case I'm using 4.5 GB with 4.1GB in /var/log/journal. So if you want to limit the size of your log journal to 100MB you can do:

`sudo du -h /var/log/
`
<img width="476" alt="image" src="https://user-images.githubusercontent.com/22479095/157168931-207d0814-16c1-4bc8-874e-48182e9a37a6.png">

`sudo journalctl --vacuum-size=100M
`
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/22479095/157169035-2e777ff0-073a-4490-a8cc-37f8f62c432b.png">

`sudo apt autoremove
`
<img width="502" alt="image" src="https://user-images.githubusercontent.com/22479095/157169088-ad5ce1f9-471b-464d-a435-58cafa9f4efd.png">

I understand your point but as I reported above, but when I check the available space by "df -h" command, there is still 12GB flash available but still showing the "No space left on device" in the log. Sometimes this error message happens, not every time.

**Comment by ophub** [comment]
No hard disk space is full.
This is a reminder that the system log is full and limits the size of the system log.

**Comment by EastWoodYang** [comment]
问下如何给/var/log扩容？目前只分配了48M，我安装了桌面服务后，启动的时候因为空间不足导致systemd-update-utmp.service没法正常启动，影响关机重启

**Comment by ophub** [comment]
按上面的操作

**Comment by EastWoodYang** [comment]
不行，断电重启后 df -h 显示 /var/log 已用还是 100%

**Comment by ophub** [comment]
`vi /etc/fstab`

```
temp        /tmp        tmpfs   rw,mode=1777    0   0
vartmp      /var/tmp    tmpfs   rw,mode=1777    0   0
varlog      /var/log    tmpfs   rw,mode=1777    0   0
```

如果日志对你没什么用，你可以挂载成临时目录，每次重启自动释放掉。如果你想收集每天的日志分析，自己挂载个固定目录。

**Comment by jizusun** [comment]
我发现 `df` 和 `du` 的结果不一样


```
armbian:~:# du -h --max-depth=1 /var/log
4.0K    /var/log/apt
16K     /var/log/lost+found
4.0K    /var/log/chrony
4.0K    /var/log/unattended-upgrades
4.0K    /var/log/private
4.0K    /var/log/openvpn
6.0M    /var/log/sysstat
6.1M    /var/log

armbian:~:# df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           182M   20M  162M  11% /run
/dev/mmcblk2p2  6.4G  2.5G  3.8G  40% /
tmpfs           906M     0  906M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/zram2      889M  172K  828M   1% /var/tmp
/dev/mmcblk2p1  511M  100M  412M  20% /boot
/dev/zram1       47M   45M     0 100% /var/log
tmpfs           182M     0  182M   0% /run/user/0
```

然后搜到这篇文章 
https://sudoedit.com/df-and-du-report-different-usage/

根据里面讲的发现是 `syslog` 导致的，于是重启该服务即可
```
armbian:~:# sudo lsof | grep -i deleted
bpfilter_   297                          root    2w      REG                0,2       20        132 /dev/kmsg (deleted)
rsyslogd   1407                        syslog    7w      REG              254,1 34021376         29 /var/log/syslog (deleted)
rsyslogd   1407                        syslog    8w      REG              254,1  6574080         27 /var/log/kern.log (deleted)
rsyslogd   1407  1431 in:imuxso        syslog    7w      REG              254,1 34021376         29 /var/log/syslog (deleted)
rsyslogd   1407  1431 in:imuxso        syslog    8w      REG              254,1  6574080         27 /var/log/kern.log (deleted)
rsyslogd   1407  1432 in:imklog        syslog    7w      REG              254,1 34021376         29 /var/log/syslog (deleted)
rsyslogd   1407  1432 in:imklog        syslog    8w      REG              254,1  6574080         27 /var/log/kern.log (deleted)
rsyslogd   1407  1433 rs:main          syslog    7w      REG              254,1 34021376         29 /var/log/syslog (deleted)
rsyslogd   1407  1433 rs:main          syslog    8w      REG              254,1  6574080         27 /var/log/kern.log (deleted)
armbian:~:# sudo service rsyslog restart
armbian:~:# df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           182M   20M  162M  11% /run
/dev/mmcblk2p2  6.4G  2.5G  3.8G  40% /
tmpfs           906M     0  906M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/zram2      889M  172K  828M   1% /var/tmp
/dev/mmcblk2p1  511M  100M  412M  20% /boot
/dev/zram1       47M  6.1M   38M  14% /var/log
tmpfs           182M     0  182M   0% /run/user/0
```

**Comment by xcray** [comment]
> 我发现 `df` 和 `du` 的结果不一样
> 然后搜到这篇文章 https://sudoedit.com/df-and-du-report-different-usage/
> 
> 根据里面讲的，可以发现我这边是 `syslog` 导致的，于是重启该服务即可
> ```
> armbian:~:# sudo lsof | grep -i deleted
> ```

这是正解！
