### ISSUE TITLE
Can't enable multi-boot on M401A 中文回答也行

### ISSUE THREAD

**Issue by alcatraz-zz** [ophub/amlogic-s9xxx-armbian#1390]
Hey fellas

I got myself a 魔百盒M401 2+8GB and I'm trying to boot 6.x from usb. I tried Rufus and Balenaetcher but I can't initiate the boot from USB. 

I tried with default settings and with uEnv.txt edited with the M401A dtb file.

When I press and hold the "hidden button" (on M401A it's a tiny hole next to the back label) and turn it on, I can only see the Android boot logo from the onboard system (Android9 chinese system).

Any idea how to proceed?

I have opened my box and I can confirm that it's an S905L3A chipset. 

Thanks for reading and helping.

**Comment by ophub** [comment]
The help document introduced how to boot the Armbian system from USB in section 12.14. Typically, "Magic Box" requires a new Android 9.0 or higher system to be installed before Armbian can be installed properly, and the relevant installation package can be found in the releases of the kernel repository.

**Comment by alcatraz-zz** [comment]
> The help document introduced how to boot the Armbian system from USB in section 12.14. Typically, "Magic Box" requires a new Android 9.0 or higher system to be installed before Armbian can be installed properly, and the relevant installation package can be found in the releases of the kernel repository.

Thanks for the reply!

Is it a certain system or any Android 9? The box came with Android 9 on it.

**Comment by alcatraz-zz** [comment]
"12.14 How to modify cmdline settings" does not sound relevant to enabling multi-boot. Are you sure it's 12.14?

**Comment by alcatraz-zz** [comment]
12.4 Is about booting from USB, by the use of ADB. Is that the only option?

**Comment by ophub** [comment]
There are many ways among experts in the field. You can check the history of similar problems and find a method that suits your preference.

**Comment by smerckzak** [comment]
路過。。。確定自己的步驟沒錯就找找其他原因吧，U盘可以的話換個試試，usb2.0接口的。。。。盒子應該是刷過安卓系統的，瞭解下是否有root權限 如果沒有權限，那就進系統把usb調試打開。然後電腦下載一個“開心電視助手”通過ip連接盒子，找到從u盤啟動。不過我還沒開始刷呢，這是我瞭解到的一些步驟，希望對你有用吧

**Comment by alcatraz-zz** [comment]
I tried both USB ports. I tried Rufus and Balenaetcher. No go by pressing the button. No, I don't think I have root. 

The good news is that it worked over adb. The android 9 system the box came with was easy to get the adb bridge to work.

I ran the adb reboot update command and it booted from usb. I was even able to do armbian-install and now it boots without a usb plugged in. HDMI is working. I tried installing XFCE and that went well with apt. Got Firefox-esr to work on the user account but not admin. Don't know why. I remember when installing there were tons of "Operation not permitted" in the log.

Before installing I took a backup using ddbr. 

So far so good. I tried connecting a WirelessLAN usb stick but nothing happens. Don't know how to get support.

Also audio over hdmi isn't working.

Cheers for the help so far! I really appreciate it. 很高兴

**Comment by alcatraz-zz** [comment]
Hi again!

I want to try the jammy release. I'm on bullseye now. 

Is there a command I can run (in armbian) to boot from USB? (Does the bootloader do that automatically or?)

It feels like a waste to reinstall android just to boot from USB again. 

Thanks

**Comment by alcatraz-zz** [comment]
> There are many ways among experts in the field. You can check the history of similar problems and find a method that suits your preference.

I take the silence means it will (probably) boot from usb automatically, when armbian is already installed on emmc. Right? 😁
