### ISSUE TITLE
905l3显卡不工作

### ISSUE THREAD

**Issue by yangchaohong** [ophub/amlogic-s9xxx-armbian#1391]
**Device Information | 设备信息**
 - SOC: Amlogic S905L3
 - Model UNT400G1-江苏联通紫光无线模块

**Armbian Version | 系统版本**
 - Kernel Version: 5.15
 - Release: bullseye

**Describe the bug | 问题描述**
没有显示，/dev中也没有fb0
是否所以mali400系的显卡工作都不正常？
还是l3不能直接使用l2点dtb？
或者有没有可能kernel中根本没有启用lima？（mali G/T系列使用panforst驱动，400系使用lima）
我想要暑假设计一个905x系列的开发板，会用到905l3的拆机料，所以我想知道armbian的显卡是否可用

还有就是哪些盒子显卡不工作？

**Comment by ophub** [comment]
其他设备如n1, hk1, x96, tx3, gtk等都支持。但魔百盒不是全部支持，具体哪个支持我记不得了，正好适合你研究研究。
