### ISSUE TITLE
显示器持续输出RTL871X: ......

### ISSUE THREAD

**Issue by hoyzhang** [ophub/amlogic-s9xxx-armbian#1392]
IMG: Armbian_23.05.0_amlogic_s905lb-r3300l_jammy_5.15.110_server_2023.05.12.img
CPU: S905L-B
dtb: meson-gxl-s905x-p212.dtb
uboot.ext: u-boot-s905x-s912.bin

已经成功启动并安装到U盘，能正常登录，HDMI和网卡也是可以的，WIFI也能看到。
但是HDMI输出，持续看到如下图所示的字幕，SSH终端则没有出现。看样子是WIFI芯片的问题，能怎么解决吗？

![bb](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6406376/8a354fb3-e841-41d4-b097-5490bc14dc44)

**Comment by ophub** [comment]
禁用你不用的无线

**Comment by hoyzhang** [comment]
> 禁用你不用的无线

有什么命令禁用呢？
如果WIFI还想使用呢？

**Comment by ophub** [comment]
看仓库的文档

**Comment by hoyzhang** [comment]
> 看仓库的文档

禁用有办法做到。但是WIFI还想使用的情况下，怎么处理才能去掉这些提示呢？
我在armbian-config中连接了wifi，能动态获取到ip，能ping通外网。

**Comment by ophub** [comment]
sudo systemctl disable serial-getty@ttyFIQ0 2>/dev/null
sudo systemctl disable serial-getty@ttyAML0 2>/dev/null

**Comment by hoyzhang** [comment]
> 

试了一下，似乎仍然有输出

**Comment by hoyzhang** [comment]
可能在rc.local中禁止dmesg继续输出能解决这个问题。回头再测试一下

**Comment by LiteCoder** [comment]
> 可能在rc.local中禁止dmesg继续输出能解决这个问题。回头再测试一下

你好，请问这个问题解决了吗

**Comment by bh4578** [comment]
在Debian或其他基于Systemd的Linux系统中，您可以通过创建一个Systemd服务单元来设置开机自动运行命令 `dmesg -D`。
以下是设置开机自动运行命令 `dmesg -D` 的步骤：
1. 创建一个新的Systemd服务单元文件，例如 `disable_dmesg.service`。使用文本编辑器（例如`nano`或`vim`）创建一个新文件：

```bash
sudo nano /etc/systemd/system/disable_dmesg.service
```

2. 在编辑器中输入以下内容，描述服务单元的设置：

```plaintext
[Unit]
Description=Disable dmesg at boot

[Service]
Type=oneshot
ExecStart=/bin/dmesg -D

[Install]
WantedBy=multi-user.target
```

3. 保存并关闭文件。在`nano`编辑器中，按 `Ctrl + X`，然后输入`y`并按下 `Enter` 来保存。

4. 激活新的Systemd服务单元并设置开机自动运行：

```bash
sudo systemctl daemon-reload
sudo systemctl enable disable_dmesg.service
```

5. 重新启动系统，让更改生效：

```bash
sudo reboot
```

现在，命令 `dmesg -D` 将在系统启动时自动运行，禁用内核消息（kern.log）的输出到控制台。

请注意，禁用内核消息输出可能会影响系统故障排除和日志记录。在某些情况下，这可能会隐藏重要的系统信息。确保在了解可能的后果后再执行这个操作。如果不确定是否需要禁用 `dmesg` 的输出，请先测试并验证该设置是否适合您的系统。

**Comment by IOsetting** [comment]
我也遇到了这个问题. 
禁用dmesg输出只是眼不见为净, 但是要用到dmesg信息的时候, 还是要面对这一大堆日志垃圾.
是不是这个驱动在编译时设置了错误的日志级别? 能否给上游提一个issue修复这个问题?

**Comment by vinbor** [comment]
我也遇到了这个问题，关闭WIFI功能sudo ifconfig wlan0 down可以解决。
