### ISSUE TITLE
HDMI输出画面发绿

### ISSUE THREAD

**Issue by ZekeJi** [ophub/amlogic-s9xxx-armbian#1393]
**Device Information | 设备信息**
 - SOC: [S922X]
 - Model [CT2000]

**Armbian Version | 系统版本**
 - Kernel Version: [ 5.15.110]
 - Release: [trunk Jammy]

**Describe the bug | 问题描述**
HDMI输出画面发绿，系统已经写入EMMC中。

**Comment by ophub** [comment]
有主线的可以使用主线解决HDMI绿色的问题：`armbian-install -m yes`
但是这个盒子没主线。
不过我有2个，使用显示器也没见绿过，正常显示，你是接的电视？

**Comment by ZekeJi** [comment]
接的是戴尔的显示器
