### ISSUE TITLE
X96 max plus (2101) Cannot boot from SD card

### ISSUE THREAD

**Issue by ingvardm** [ophub/amlogic-s9xxx-armbian#1394]
**Device Information | 设备信息**
 - SOC: S095x3
 - Model X96 max plus (2101)

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.110/6.1.27
 - Release: jammy

Does not boot from SD card.
Tried to copy u-boot-x96maxplus.bin to u-boot.ext/.sd and with original u-boot files

emuelec/coreelec do boot from same SD card
![IMG_1903](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4587825/57080dc8-a4c5-4106-b9cd-db1cb9dca928)
![IMG_1904](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4587825/a62ee39a-7a2c-4bd9-ad1f-7506710e8a73)

**Comment by ophub** [comment]
don't copy u-boot
The emmc must be an Android system or an Armbian system. Other systems do not work.

**Comment by ingvardm** [comment]
> don't copy u-boot The emmc must be an Android system or an Armbian system. Other systems do not work.

The device is brand new, boots to original Android.
And i also tried without copying the u-boot files.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/2f6151e7e23e8c579af8ecd23586b69a072a1dbe/build-armbian/armbian-files/common-files/etc/model_database.conf#L131

**Comment by ingvardm** [comment]
yes thats the dtb i use

**Comment by ophub** [comment]
try usb

**Comment by ingvardm** [comment]
same, tried both usb ports.
if i go to "update from EXT" i see the contents of usb drive, so it's mounted.

**Comment by yangchaohong** [comment]
unt400g1也不行……

**Comment by ingvardm** [comment]
Closing an issue doesn't make it disappear.

**Comment by navigos** [comment]
Same problem here.
@ingvardm , did you somehow manage to solve it?

**Comment by ingvardm** [comment]
@navigos, no i didn't. But if it helps, batocerra boots just fine, so maybe you can use it to fix this issue. If you have any progress, please let me know, i'm kinda still interested in this project.

**Comment by navigos** [comment]
@ingvardm  #2317 solved my problem.

**Comment by ingvardm** [comment]
@navigos Thanks, i'll give it a try!
