### ISSUE TITLE
armbian-software命令308选项消失了

### ISSUE THREAD

**Issue by boboiougogo** [ophub/amlogic-s9xxx-armbian#1395]
**Device Information | 设备信息**
 - SOC: [e.g. S905l3a]
 - Model [e.g. cm311-1a yst]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.111]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
armbian-software -u 更新命令后，在/usr/share/ophub/armbian-software/software-list.conf 文件中能看到 “308” “pve” 选项，但是执行armbian-software命令，却看不到这个选项。

**Comment by ophub** [comment]
只有bullseye的可以用308
