### ISSUE TITLE
no eMMC boot on kernel 6.1.27 with both s905x and s912 boxes

### ISSUE THREAD

**Issue by Black6spdZ** [ophub/amlogic-s9xxx-armbian#1398]
**Device Information | T95x / M8S Pro**
 - SOC: [s905x / s912]
 - Model [T95x / M8S Pro]

**Armbian Version | 23.05.0 **
 - Kernel Version: [5.15.110 / 6.1.27]
 - Release: [bullseye]

**Describe the bug **
both boxes will only boot from eMMC with kernel 5.15.100, 6.1.27 will not

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
same issue with both SoCs and kernels

**Comment by ophub** [comment]
Why are you using these two firmwares? What kind of device do you have? If this is not your firmware, it is normal for it not to start.

**Comment by Black6spdZ** [comment]
> 

I was saying that with two different boxes, neither one will run the 6.x kernel but run perfect with the older 5.x kernel

**Comment by ophub** [comment]
`armbian-update -u dev -k 6.1.28`
