### ISSUE TITLE
M401A盒子/etc/fstab 使用uuid挂载硬盘无法正常启动，加一个USB2.0的HUB就正常。怎么在系统中禁用USB3.0呢

### ISSUE THREAD

**Issue by R6400** [ophub/amlogic-s9xxx-armbian#1399]
**Device Information | 设备信息**
 - SOC: [M401A. S095L3a]
 - Model [M401A]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.111-ophub]
 - Release: [jammy]
**Describe the bug | 问题描述**

M401A盒子在/etc/fstab 使用uuid挂载硬盘会导致系统不能正常启动，但是在移动硬盘盒前面加一个USB2.0的HUB转接器就正常启动。而且不在开机挂载外置硬盘，等进入系统后手动挂载移动硬盘还会出现掉盘问题，sda1会变成sdb1、sdc1等等。我想应该是USB3.0的问题。请问怎么在系统中禁用USB3.0呢，只使用USB2.0，具体怎么操作呢？

**Comment by ophub** [comment]
给USB3.0口贴个胶布禁用了。

**Comment by R6400** [comment]
可能是我没描述清楚，M401A盒子的两个USB接口都是2.0的接口，是我的移动硬盘的接口是USB3.0的。现在的问题是直接把移动硬盘插到M401A盒子上不能正常启动进入系统一直提示错误，然后提示按Ctrl+D继续。必须要在电视盒子上加一个USB2.0的HUB转接器，移动硬盘插在这个USB2.0的HUB转接器上就能正常进入系统。我百度查了一下说的就是把系统里面的USB3.0驱动禁用了，强制使用USB2.0驱动就可以正常启动了，但是具体怎么禁用USB3.0驱动呢？

**Comment by ophub** [comment]
在  Armbian 系统将禁用所有 USB 3.0 设备的方法：

```
# 在 rockchip 和 allwinner 里使用
/boot/armbianEnv.txt
extraargs=usbcore.usb3_disable=1


# 在 amlogic 里使用
/boot/uEnv.txt
usbcore.usb3_disable=1

# 使用 /extlinux/extlinux.conf 的在这里添加
usbcore.usb3_disable=1
```

**Comment by R6400** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38423539/3b418353-0c0c-489f-b44a-19573914956e)
![10a1af59a6eca268534fc7598230f78](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38423539/70819dce-276b-4b77-88cc-09554c281b59)
![433403228d375d3b69cd0f581cb5999](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38423539/0f684e7d-2661-4c66-97d4-da612d03db10)
第一张图是按照说明在/boot/uEnv.txt里面添加了usbcore.usb3_disable=1参数，第二张和第三张图是添加参数重启两次报错的照片，请帮忙分析一下是什么问题导致无法正常启动的，谢谢了。（盒子是M401A，S905L3a的主控，系统版本是Armbian_23.05.0_amlogic_s905l3a_jammy_5.15.111_server_2023.05.14）
