### ISSUE TITLE
running wayland and gnome with latest drivers

### ISSUE THREAD

**Issue by pulpoff** [ophub/amlogic-s9xxx-armbian#14]
I could update this build to latest ubuntu impish and run the gnome much faster with acceleratad drivers.
The openwrt build even runs from usb flash !
to upgrade to ubuntu i updated apt sources.list
and installed missing keys.
![Screenshot from 2021-11-07 04-23-47](https://user-images.githubusercontent.com/40654959/140633317-9074be3e-067d-4c6f-ad40-f4802bb15fa0.png)
![Screenshot from 2021-11-07 04-34-52](https://user-images.githubusercontent.com/40654959/140633319-17a9fd9d-1482-4ab5-910c-82ffc0d013ab.png)
![Screenshot from 2021-11-07 04-39-40](https://user-images.githubusercontent.com/40654959/140633320-666b6f3e-34f6-4a63-88ae-5ca39eeb2622.png)
![Screenshot from 2021-11-07 04-52-40](https://user-images.githubusercontent.com/40654959/140633323-08582fbb-4c3a-4acf-bd09-aee16498add6.png)

**Comment by pulpoff** [comment]
deb http://ports.ubuntu.com/ubuntu-ports/ impish main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish main restricted

deb http://ports.ubuntu.com/ubuntu-ports/ impish-updates main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-updates main restricted

deb http://ports.ubuntu.com/ubuntu-ports/ impish universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish universe
deb http://ports.ubuntu.com/ubuntu-ports/ impish-updates universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-updates universe

deb http://ports.ubuntu.com/ubuntu-ports/ impish multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish multiverse
deb http://ports.ubuntu.com/ubuntu-ports/ impish-updates multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-updates multiverse

deb http://ports.ubuntu.com/ubuntu-ports/ impish-backports main restricted universe multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-backports main restricted universe multiverse

deb http://archive.canonical.com/ubuntu impish partner
deb-src http://archive.canonical.com/ubuntu impish partner

deb http://ports.ubuntu.com/ubuntu-ports/ impish-security main restricted
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-security main restricted
deb http://ports.ubuntu.com/ubuntu-ports/ impish-security universe
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-security universe
deb http://ports.ubuntu.com/ubuntu-ports/ impish-security multiverse
deb-src http://ports.ubuntu.com/ubuntu-ports/ impish-security multiverse

**Comment by ophub** [comment]
Awesome, give you a thumbs up.

You can share your approach and give an upgraded tutorial.

**Comment by pulpoff** [comment]
It would be nice to have a USB drive based desktop with all the drivers.
Can you please tell me what is different in your openwrt image that allows
it to boot from USB drive?
Thanks

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt

openwrt can be used in USB, check the description of the repo for details.

**Comment by pulpoff** [comment]
I know, i tested it.
But what is the difference? Do you know how to make armbian boot from usb?
Also, I tested 5.15.1 kernel, and its is great! but it crashes after
some time.. do u know which one is latest and stable ?
Or did u test this kernel?
Best regards, and thanks for great build!

**Comment by ophub** [comment]
The boot file is u-boot.ext

The startup method of openwrt and armbian is the same.

My armbian uses 5.15.1 on x96max+ and it works normally. In theory, the newer the version, the better the performance.

**Comment by pulpoff** [comment]
there seem to be some problems (crashes) with all kernels beside this one : 5.12.19
With -oc dtb, the 5.12 kernel runs stable at 2.02Ghz!!!
Please can u share the diff ?
any kernel before 5.14 do NOT support my 2560x1440 monitor native res..

**Comment by pulpoff** [comment]
![Screenshot from 2021-11-09 04-44-09](https://user-images.githubusercontent.com/40654959/140858714-a03c5db5-8546-45c1-a933-c9e391dcb7b7.png)

**Comment by ophub** [comment]
I use flippy to compile the kernel package for OpenWrt. See his source code: https://github.com/unifreq

You can compile your own personalized kernel, he is more clear about the kernel issues.
