### ISSUE TITLE
Mecool K5 s905x3

### ISSUE THREAD

**Issue by dnmnhat** [ophub/amlogic-s9xxx-armbian#140]
Does armbian for s905x3 support DVB ? ( specifically Mecool K5 )
I can't find dtb file for Mecool K5 + DVB.

**Comment by ophub** [comment]
Use s905x3 kernel is 5.4 firmware test, dtb try meson-sm1-sei610.dtb

**Comment by dnmnhat** [comment]
It can't boot , I will try again as soon as I have time :(
