### ISSUE TITLE
老大能适配下yf-078w（rk3399）吗？

### ISSUE THREAD

**Issue by pegguo** [ophub/amlogic-s9xxx-armbian#1400]
板子小巧，接口也全，目前有的版本wifi驱动和type驱动有问题，感谢感谢！

**Comment by ophub** [comment]
我在B站上看卖家秀里，他使用没问题啊。他使用的type刷机。

**Comment by pegguo** [comment]
> 我在B站上看卖家秀里，他使用没问题啊。他使用的type刷机。

wifi不好用，有时候连上一会就断开了，有时候连不上，加了外置天线也是不行
