### ISSUE TITLE
TY1608 armbian-kernel -k 5.15.110 -t gcc 失败

### ISSUE THREAD

**Issue by w2xg2022** [ophub/amlogic-s9xxx-armbian#1401]
**Device Information | 设备信息**
 - SOC: S905L3B
 - Model: 浙江电信TY1608

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.110
 - Release: bullseye

**Describe the bug | 问题描述**
刷入Armbian_23.05.0_amlogic_s905l3b_bullseye_5.15.110_server_2023.05.09.img，U盘启动，准备学习编译驱动（包括板载8822CS无线和外置USB网卡）。确定可以访问github，麻烦大佬帮忙解惑，谢谢。

armbian-kernel -u 运行正常
armbian-kernel -k 5.15.110 -t gcc 报错，信息如下：

root@armbian:~# armbian-kernel -k 5.15.110 -t gcc
[ STEPS ] Welcome to compile kernel!

[ INFO ] Server running on Armbian: [ Release: bullseye / Host: aarch64 ]

[ STEPS ] Start Initializing Variables...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ STEPS ] Start checking the toolchain for compiling the kernel...
[ INFO ] Start downloading the ARM GNU toolchain [ arm-gnu-toolchain-12.2.rel1-aarch64-aarch64-none-elf.tar.xz ]...
[ STEPS ] Start querying the latest kernel version...
[ INFO ] (1) Auto query the latest kernel version of the same series for [ 5.15.110 ]
 [ ERROR ] Failed to query the kernel version in [ github.com/unifreq/linux-5.15.y/main ]

**Comment by ophub** [comment]
这是网络问题，不稳定

**Comment by w2xg2022** [comment]
试过armbian-kernel -k 5.15.110 -t gcc -r chewitt/linux@amlogic-5.15.y
或在/etc/ophub-release加GITHUB_CDN都没有用。（Failed to query the kernel version in ......）

请问如果git clone https://github.com/unifreq/linux-5.15.y 到gitee，不知道是否可行？如果可行要如何修改以指向gitee？谢谢。

**Comment by ophub** [comment]
在armbian系统中使用armbian-kernel时，路径是固定的，比如5.15.y系列的源码路径如下：

/opt/kernel/compile-kernel/kernel/linux-5.15.y

你可以想想办法把源码下载解压到本地。
编译是使用-a false告诉脚本不要查询服务器版本了，直接编译：`armbian-kernel -a false -k 5.15.111 -t gcc`

**Comment by w2xg2022** [comment]
顺利下载linux-5.15.y-main.zip，也解压缩和调整目录名称为/opt/kernel/compile-kernel/kernel/linux-5.15.y
git clone https://github.com/lwfinger/rtw88，花了一个晚上（不知道是不是系统在TF卡上没有写入EMMC，特别慢）编译成功也 make install（查看到uInitrd等文档有被修改），但无法驱动TY1608板载的8822CS无线。

请问大佬，有没有直接可用的github源可用顺利驱动和使用8822CS无线，谢谢。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.4.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs

5.4里有，更新内核测试

**Comment by w2xg2022** [comment]
谢谢大佬指导。

armbian之中，lsmod可以看到88x2cs是有加载的，但ifconfig -a看不到wlanx。

这次目标是让TY1608板载的8822CS无线可以使用，在5.15.110（当初下载是这个版本就一直用了）make modules编译了好几个代码库，基本在编译过程就失败，也不想看错误信息解决了。最接近成功的是https://github.com/jethome-ru/rtl88x2cs，已经编译完成但是modprobe加载报格式错误什么的（具体没复制下来）。

既然目标是让无线可以用而不是编译，所以就试着更新（降级）内核，5.15.110升到5.15.112、降级到5.4.243都没用，lsmod可以看到但ifconfig -a看不到wlanx。升级6.1.29直接不开机了（因为HDMI无法使用，从无法找到IP判断的）。

因为已经费（废）了好多业余时间，暂时放弃了这个盒子使用板载无线的想法。

顺便请教大佬，为什么有些安卓固件可以引导armbian开机，有些又不行，类似的，同一个安卓固件可以引导某个armbain版本却无法引导另一个。感觉和安卓固件的DDR.USB、UBOOT.USB有关，不知道是不是，有什么编辑或修改的工具可以处理吗？谢谢。

**Comment by ophub** [comment]
kernel_dev 里的都可以。
kernel_stable, kernel_flippy 里的 5.4/5.15 也都可以。但 5.10/6.1 就不一定了，没有使用主线u-boot的情况下有个别机型无法使用，我能知道的是h96-pro（s905x3）和一个魔百盒（忘了哪个了）。
使用`armbian-install -m yes`的情况下，这2个也可以。

**Comment by w2xg2022** [comment]
armbian-update -k 5.15.112 -u dev
![搜狗截图20230524150554](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/432d1c96-2bf0-40c4-a6af-6dc112c7e04c)

重开机后ifconfig -a看不到wlanx。

试着armbian-install -m yes写入emmc，选123、ext4，无法开机（因为HDMI无法使用，一方面无法找到IP一方面灯号和正常开机不同）。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
看12.7.3

**Comment by w2xg2022** [comment]
估计真没戏了？sudo nmcli dev看不到wlanx，sudo nmcli dev wifi也扫描不到任何无线。

![搜狗截图20230524154719](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/d1f79ad3-264c-4ba1-93b0-32517f702e67)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs
https://github.com/unifreq/linux-5.4.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs
https://github.com/unifreq/linux-5.10.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs
https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs
5.4， 5.10， 5.15，6.1里都有88x2cs的驱动，都挨着更新一圈看看哪个能驱动。

**Comment by w2xg2022** [comment]
团灭了：
armbian-update -k 5.15.112 -u dev 可开机，lsmod有看到88x2cs，但nmcli dev看不到wlanx
armbian-update -k 5.10.180 -u dev 无法开机（找不到IP），替换5.15.110的dtb后可开机，lsmod有看到88x2cs，但nmcli dev看不到wlanx
armbian-update -k 5.4.243 -u dev 可开机，lsmod有看到88x2cs，但nmcli dev看不到wlanx
armbian-update -k 6.1.29 -u dev 可开机，lsmod有看到88x2cs，但nmcli dev看不到wlanx

**Comment by hgyh-12** [comment]
TY1608 的HDMI不显示有木有办法解决？
