### ISSUE TITLE
RK3568-Hummingbird，新机型适配反馈

### ISSUE THREAD

**Issue by GD2021** [ophub/amlogic-s9xxx-armbian#1403]
型号：通过读取主板内置系统，得知是一款蜂鸟的什么网关组网设备
处理器：RK3568B2
存储：4G 内存 32G emmc
网口：千兆网口（带POE）、板载WIFI
接口：1个TypeC+2个USB2.0

主板如图：
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81171294/fb6e2153-3b42-4a15-83f8-7aa745d7d2ff)

原机备份的dtb文件：
https://tt.vg/BYsjQ

刷机引导文件：
https://fast.uc.cn/s/41fd70a8815d4 

第三方Ubuntu2004 Server
https://tt.vg/qjMaX

**Comment by ophub** [comment]
你分享的这个ubuntu，直接下载armbian的rootfs替换即可使用，其他分区文件可以保留不变。这种开发版结构的固件可以自由diy。

**Comment by GD2021** [comment]
好的

**Comment by GD2021** [comment]
这个Ubuntu是别人做的，已经可以正常使用了，他了替换了原版dtb，但我想用你的Armbian_bullseye

**Comment by ophub** [comment]
在你的设备里把这几个文件复制一下。
他开放dts和u-boot源码没？

**Comment by GD2021** [comment]
这个设备我查到型号为：Hummingbird H500
官网：https://www.xdt.com/
核心板：http://www.industio.cn/product-item-20.html，http://www.industio.cn/product-item-22.html
资料：http://www.industio.cn/product-item-22.html
LINUX:
链接：https://pan.baidu.com/s/1PGoN5J-f-XE9vic6drgScQ 
提取码：3oq5 
Android：
链接：https://pan.baidu.com/s/1JhZfJhmXdGzeGE602fAP2w 
提取码：1234 
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81171294/f1b0cc8d-cad1-4263-9d39-bb1a7ce2d9bd)

**Comment by GD2021** [comment]
DTS UBOOT文件等：
https://fast.uc.cn/s/78240031738c4
