### ISSUE TITLE
小米3s（s905x）可以使用 T95（s905x）的镜像

### ISSUE THREAD

**Issue by ophub** [ophub/amlogic-s9xxx-armbian#1405]
根据 [shuye1728](https://github.com/shuye1728) 反馈，小米3s（s905x）可以使用 T95（s905x）的镜像，序号107。这个盒子没有有线网口，可以使用无线。

![582c1296N83eea7b8](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/47c350b6-767b-4992-9cf9-cb446ebcf151)

![photo_2023-05-18_22-00-16](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/679ba9ab-746b-48d4-aeba-1f49b6c5bb50)

![photo_2023-05-18_22-00-23](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/db948668-5850-4cd9-bfbb-cfc23f803da9)

**Comment by hyyczz** [comment]
但是最新的好几个分支版本都刷了，没有WIFI啊 = =、、
