### ISSUE TITLE
UWE5621DS WiFi

### ISSUE THREAD

**Issue by ryanInf** [ophub/amlogic-s9xxx-armbian#1406]
Device Information | 设备信息

SOC: [e.g. S0905l3a]
Model [e.g. M411A黑龙江版本]
Armbian Version | 系统版本

Kernel Version: [6.1.27]
Release: [Armbian 23.05.0-trunk Jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
UWE5621DS这个WiFi模块我发现coreelec可以驱动，有没有可能移植到armbian呢？

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
使用下面版本的CoreELEC各项功能都正常，蓝牙、WiFi等，希望ophub大佬看看有无可能移植。
https://github.com/KryptonLee/e900v22c-CoreELEC
尝试过复制dtb到此armbian系统中无法启动。

**Comment by ophub** [comment]
安卓驱动不能用

**Comment by Maplestoryx** [comment]
同样求助，openwrt 也无法使用UWE5621DSWiFi模块！

**Comment by cam350** [comment]
同样求助，openwrt 也无法使用UWE5621DSWiFi模块！

**Comment by caitouwh** [comment]
armbian 官方账号下 好像提供了 UWE5621SD 的配置文件  。链接如下 https://github.com/armbian/firmware/tree/master/uwe5621ds  

是否可以借来一用 ？

**Comment by ophub** [comment]
可以复制到firmware目录下重启试试

**Comment by xiaodiao216** [comment]
> 可以复制到firmware目录下重启试试

好像没用 我的usr/lib/firmware下面有这个包，但是却没用
