### ISSUE TITLE
x96 max+  reboot

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#141]
x96 max+ 执行reboot后，设备关机后有时候不会重启

**Comment by ophub** [comment]
你的显示器输出了什么，卡哪步了

**Comment by EastWoodYang** [comment]
在执行reboot命令后，屏幕日志较多来不及看，好像没看到错误信息，大部分情况下能正常重启，十次里面大概有1-2次会关机后不会自动开机。
都是在emmc中使用，在内核5.15、5.16都会发现，其他不清楚
reboot前执行什么好像关系不大，看着比较随机？下午再重新安装执行armbian-config、apt-update，reboot遇到过一次
大致这么一个情况，看着不大好定位问题，哈哈哈

**Comment by ophub** [comment]
哈哈，那就在精神上支持你，祝你重启顺利，万事如意
