### ISSUE TITLE
无法安装wine32

### ISSUE THREAD

**Issue by 2536** [ophub/amlogic-s9xxx-armbian#1410]
```
   / \   _ __ ___ | |    / ___|/ _ \ / _ \| ___|  __| |
  / _ \ | '_ ` _ \| |____\___ \ (_) | | | |___ \ / _` |
 / ___ \| | | | | | |_____|__) \__, | |_| |___) | (_| |
/_/   \_\_| |_| |_|_|    |____/  /_/ \___/|____/ \__,_|

Welcome to Armbian 23.05.0-trunk Jammy with Linux 5.15.112-ophub

System load:   2%               Up time:       1:26     Local users:   6
Memory usage:  28% of 1.77G     IP:            192.168.3.9
CPU temp:      50°C             Usage of /:    9% of 57G
RX today:      1.8 GiB

[ 8 security updates available, 8 updates total: apt upgrade ]
Last check: 2023-05-20 16:15

[ General system configuration (beta): armbian-config ]


Expanded Security Maintenance for Applications is not enabled.

0 updates can be applied immediately.

Enable ESM Apps to receive additional future security updates.
See https://ubuntu.com/esm or run: sudo pro status

Last login: Sat May 20 15:58:56 2023 from 192.168.3.101
root@armbian:~# sudo dpkg --add-architecture i386
root@armbian:~# sudo mkdir -pm755 /etc/apt/keyrings
root@armbian:~# sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
--2023-05-20 16:41:06--  https://dl.winehq.org/wine-builds/winehq.key
Resolving dl.winehq.org (dl.winehq.org)... 151.101.110.217
Connecting to dl.winehq.org (dl.winehq.org)|151.101.110.217|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3220 (3.1K) [application/pgp-keys]
Saving to: ‘/etc/apt/keyrings/winehq-archive.key’

/etc/apt/keyrings/wineh 100%[===============================>]   3.14K  --.-KB/s    in 0.001s

2023-05-20 16:41:06 (4.86 MB/s) - ‘/etc/apt/keyrings/winehq-archive.key’ saved [3220/3220]

root@armbian:~# sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
--2023-05-20 16:41:20--  https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
Resolving dl.winehq.org (dl.winehq.org)... 151.101.110.217
Connecting to dl.winehq.org (dl.winehq.org)|151.101.110.217|:443... connected.
HTTP request sent, awaiting response... 304 Not Modified
File ‘/etc/apt/sources.list.d/winehq-jammy.sources’ not modified on server. Omitting download.

root@armbian:~# sudo apt update
Hit:1 https://dl.winehq.org/wine-builds/ubuntu jammy InRelease
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
root@armbian:~# sudo apt install --install-recommends winehq-stable
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine-stable:i386 : Depends: libc6:i386 (>= 2.34) but it is not installable
                    Depends: wine-stable-i386:i386 (= 8.0.1~jammy-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
root@armbian:~#
root@armbian:~# apt-get install  wine-stable-i386:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine-stable-i386:i386 : Depends: libasound2:i386 (>= 1.0.16) but it is not installable
                         Depends: libc6:i386 (>= 2.35) but it is not installable
                         Depends: libglib2.0-0:i386 (>= 2.37.3) but it is not installable
                         Depends: libgphoto2-6:i386 (>= 2.5.10) but it is not installable
                         Depends: libgphoto2-port12:i386 (>= 2.5.10) but it is not installable
                         Depends: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) but it is not installable
                         Depends: libgstreamer1.0-0:i386 (>= 1.4.0) but it is not installable
                         Depends: libpcap0.8:i386 (>= 1.5.1) but it is not installable
                         Depends: libpulse0:i386 (>= 0.99.1) but it is not installable
                         Depends: libsane1:i386 (>= 1.0.27) but it is not installable
                         Depends: libudev1:i386 (>= 183) but it is not installable
                         Depends: libusb-1.0-0:i386 (>= 2:1.0.21) but it is not installable
                         Depends: libx11-6:i386 but it is not installable
                         Depends: libxext6:i386 but it is not installable
                         Depends: ocl-icd-libopencl1:i386 but it is not installable or
                                  libopencl1:i386 but it is not installable
                         Depends: ocl-icd-libopencl1:i386 (>= 1.0) but it is not installable or
                                  libopencl-1.2-1:i386 but it is not installable
                         Depends: libasound2-plugins:i386 but it is not installable
                         Depends: libncurses6:i386 but it is not installable or
                                  libncurses5:i386 but it is not installable or
                                  libncurses:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@armbian:~#
```

是按照wine官网 https://wiki.winehq.org/Ubuntu_zhcn 的教程安装的是，还是失败缺少过程依赖，各种依赖的安装不上

**Comment by ophub** [comment]
错误的原因上面系统已经告诉你了，缺少前置的一些依赖，让你先安装这些依赖。

**Comment by 2536** [comment]
> 错误的原因表面系统已经告诉你了，之前设置的一些依赖，让你先安装这些依赖。

那些依赖安装不上啊

**Comment by 2536** [comment]
> 错误的原因上面系统已经告诉你了，缺少前置的一些依赖，让你先安装这些依赖。
要不大神指点一下，具体安装哪几个依赖我安装，截图给你一看，反正就是失败

![MS4)0`IPZ0M~$P8% CVEVFT](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28776371/ec029f76-1927-4a84-88f4-318aadf47be5)

**Comment by ophub** [comment]
Depends：xxxxxx就是缺少的

**Comment by 2536** [comment]
> root@armbian:~# apt-get install  wine-stable-i386:i386
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> Some packages could not be installed. This may mean that you have
> requested an impossible situation or if you are using the unstable
> distribution that some required packages have not yet been created
> or been moved out of Incoming.
> The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies:
>  wine-stable-i386:i386 : Depends: libasound2:i386 (>= 1.0.16) but it is not installable
>                          Depends: libc6:i386 (>= 2.35) but it is not installable
>                          Depends: libglib2.0-0:i386 (>= 2.37.3) but it is not installable
>                          Depends: libgphoto2-6:i386 (>= 2.5.10) but it is not installable
>                          Depends: libgphoto2-port12:i386 (>= 2.5.10) but it is not installable
>                          Depends: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) but it is not installable
>                          Depends: libgstreamer1.0-0:i386 (>= 1.4.0) but it is not installable
>                          Depends: libpcap0.8:i386 (>= 1.5.1) but it is not installable
>                          Depends: libpulse0:i386 (>= 0.99.1) but it is not installable
>                          Depends: libsane1:i386 (>= 1.0.27) but it is not installable
>                          Depends: libudev1:i386 (>= 183) but it is not installable
>                          Depends: libusb-1.0-0:i386 (>= 2:1.0.21) but it is not installable
>                          Depends: libx11-6:i386 but it is not installable
>                          Depends: libxext6:i386 but it is not installable
>                          Depends: ocl-icd-libopencl1:i386 but it is not installable or
>                                   libopencl1:i386 but it is not installable
>                          Depends: ocl-icd-libopencl1:i386 (>= 1.0) but it is not installable or
>                                   libopencl-1.2-1:i386 but it is not installable
>                          Depends: libasound2-plugins:i386 but it is not installable
>                          Depends: libncurses6:i386 but it is not installable or
>                                   libncurses5:i386 but it is not installable or
>                                   libncurses:i386 but it is not installable
> E: Unable to correct problems, you have held broken packages.
root@armbian:~# apt-get install  wine-stable-i386:i386
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 wine-stable-i386:i386 : Depends: libasound2:i386 (>= 1.0.16) but it is not installable
                         Depends: libc6:i386 (>= 2.35) but it is not installable
                         Depends: libglib2.0-0:i386 (>= 2.37.3) but it is not installable
                         Depends: libgphoto2-6:i386 (>= 2.5.10) but it is not installable
                         Depends: libgphoto2-port12:i386 (>= 2.5.10) but it is not installable
                         Depends: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) but it is not installable
                         Depends: libgstreamer1.0-0:i386 (>= 1.4.0) but it is not installable
                         Depends: libpcap0.8:i386 (>= 1.5.1) but it is not installable
                         Depends: libpulse0:i386 (>= 0.99.1) but it is not installable
                         Depends: libsane1:i386 (>= 1.0.27) but it is not installable
                         Depends: libudev1:i386 (>= 183) but it is not installable
                         Depends: libusb-1.0-0:i386 (>= 2:1.0.21) but it is not installable
                         Depends: libx11-6:i386 but it is not installable
                         Depends: libxext6:i386 but it is not installable
                         Depends: ocl-icd-libopencl1:i386 but it is not installable or
                                  libopencl1:i386 but it is not installable
                         Depends: ocl-icd-libopencl1:i386 (>= 1.0) but it is not installable or
                                  libopencl-1.2-1:i386 but it is not installable
                         Depends: libasound2-plugins:i386 but it is not installable
                         Depends: libncurses6:i386 but it is not installable or
                                  libncurses5:i386 but it is not installable or
                                  libncurses:i386 but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by ophub** [comment]
根据提示，安装列出的需要的前置依赖，如
sudo apt-get install libasound2:i386 libc6:i386 ...
你再仔细看看wine官方文档，他们介绍说在64位的jammy上可以安装32位的软件包？一般应该给64位系统的软件包列表。

**Comment by 2536** [comment]
> 根据提示，安装列出的需要的前置依赖，如 sudo apt-get install libasound2:i386 libc6:i386 ... 你再仔细看看wine官方文档，他们介绍说在64位的jammy上可以安装32位的软件包？一般应该给64位系统的软件包列表。
![R)VIJU`)WXOWNL1Z5RFGJK3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28776371/79e54753-22c4-4acd-82f5-8c28fbde0d40)

**Comment by ophub** [comment]
那你就把上面提示缺少的一个个安装全

**Comment by 2536** [comment]
> > apt-get install  wine-stable-i386:i386
> > Reading package lists... Done
> > Building dependency tree... Done
> > Reading state information... Done
> > Some packages could not be installed. This may mean that you have
> > requested an impossible situation or if you are using the unstable
> > distribution that some required packages have not yet been created
> > or been moved out of Incoming.
> > The following information may help to resolve the situation:
> > The following packages have unmet dependencies:
> > wine-stable-i386:i386 : Depends: libasound2:i386 (>= 1.0.16) but it is not installable
> > Depends: libc6:i386 (>= 2.35) but it is not installable
> > Depends: libglib2.0-0:i386 (>= 2.37.3) but it is not installable
> > Depends: libgphoto2-6:i386 (>= 2.5.10) but it is not installable
> > Depends: libgphoto2-port12:i386 (>= 2.5.10) but it is not installable
> > Depends: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) but it is not installable
> > Depends: libgstreamer1.0-0:i386 (>= 1.4.0) but it is not installable
> > Depends: libpcap0.8:i386 (>= 1.5.1) but it is not installable
> > Depends: libpulse0:i386 (>= 0.99.1) but it is not installable
> > Depends: libsane1:i386 (>= 1.0.27) but it is not installable
> > Depends: libudev1:i386 (>= 183) but it is not installable
> > Depends: libusb-1.0-0:i386 (>= 2:1.0.21) but it is not installable
> > Depends: libx11-6:i386 but it is not installable
> > Depends: libxext6:i386 but it is not installable
> > Depends: ocl-icd-libopencl1:i386 but it is not installable or
> > libopencl1:i386 but it is not installable
> > Depends: ocl-icd-libopencl1:i386 (>= 1.0) but it is not installable or
> > libopencl-1.2-1:i386 but it is not installable
> > Depends: libasound2-plugins:i386 but it is not installable
> > Depends: libncurses6:i386 but it is not installable or
> > libncurses5:i386 but it is not installable or
> > libncurses:i386 but it is not installable
> > E: Unable to correct problems, you have held broken packages.
> > root@armbian:~# apt-get install  wine-stable-i386:i386
> > Reading package lists... Done
> > Building dependency tree... Done
> > Reading state information... Done
> > Some packages could not be installed. This may mean that you have
> > requested an impossible situation or if you are using the unstable
> > distribution that some required packages have not yet been created
> > or been moved out of Incoming.
> > The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies: wine-stable-i386:i386 : Depends: libasound2:i386 (>= 1.0.16) but it is not installable Depends: libc6:i386 (>= 2.35) but it is not installable Depends: libglib2.0-0:i386 (>= 2.37.3) but it is not installable Depends: libgphoto2-6:i386 (>= 2.5.10) but it is not installable Depends: libgphoto2-port12:i386 (>= 2.5.10) but it is not installable Depends: libgstreamer-plugins-base1.0-0:i386 (>= 1.0.0) but it is not installable Depends: libgstreamer1.0-0:i386 (>= 1.4.0) but it is not installable Depends: libpcap0.8:i386 (>= 1.5.1) but it is not installable Depends: libpulse0:i386 (>= 0.99.1) but it is not installable Depends: libsane1:i386 (>= 1.0.27) but it is not installable Depends: libudev1:i386 (>= 183) but it is not installable Depends: libusb-1.0-0:i386 (>= 2:1.0.21) but it is not installable Depends: libx11-6:i386 but it is not installable Depends: libxext6:i386 but it is not installable Depends: ocl-icd-libopencl1:i386 but it is not installable or libopencl1:i386 but it is not installable Depends: ocl-icd-libopencl1:i386 (>= 1.0) but it is not installable or libopencl-1.2-1:i386 but it is not installable Depends: libasound2-plugins:i386 but it is not installable Depends: libncurses6:i386 but it is not installable or libncurses5:i386 but it is not installable or libncurses:i386 but it is not installable E: Unable to correct problems, you have held broken packages.
以下程序包具有未满足的依赖项：

wine-table-i386:i386:依赖于：libasound2:i386（>=1.016），但不可安装

依赖于：libc6:i386（>=2.35），但无法安装

依赖于：libglib2.0-0:i386（>=2.37.3），但无法安装

依赖于：libgphoto2-6:i386（>=22.5.10），但无法安装

依赖于：libgphoto2-port12:i386（>=22.5.10），但无法安装

依赖于：libgstreamer-plugins-base1.0-0:i386（>=1.0.0），但无法安装

依赖于：libgstreamer1.0-0:i386（>=1.4.0），但无法安装

取决于：libpcap0.8:i386（>=1.5.1），但无法安装

取决于：libpulse0:i386（>=0.99.1），但无法安装

依赖于：libsane1:i386（>=1.0.27），但不可安装

依赖于：libudev1:i386（>=183），但无法安装

依赖于：libusb-1.0-0:i386（>=2:1.0.21），但无法安装

依赖于：libx11-6:i386，但无法安装

依赖于：libxext6:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386，但它不可安装或

libopencl1:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386（>=1.0），但它不可安装或

libopencl-1.2-1:i386，但无法安装

依赖于：libasound2插件：i386，但无法安装

依赖于：libncurses6:i386，但它不可安装或

libncurses5:i386，但它不可安装或

libncurses:i386，但无法安装

E： 无法更正问题，您持有损坏的包裹。

root@armbian：~#apt-get安装win-stable-i386:i386

正在读取程序包列表。。。多恩

正在生成依赖关系树。。。多恩

正在读取状态信息。。。多恩

某些程序包无法安装。这可能意味着你

请求一个不可能的情况，或者如果你正在使用不稳定的

尚未创建某些必需包的分发

或已移出“传入”。

以下信息可能有助于解决此问题：



以下程序包具有未满足的依赖项：

wine-table-i386:i386:依赖于：libasound2:i386（>=1.016），但不可安装

依赖于：libc6:i386（>=2.35），但无法安装

依赖于：libglib2.0-0:i386（>=2.37.3），但无法安装

依赖于：libgphoto2-6:i386（>=22.5.10），但无法安装

依赖于：libgphoto2-port12:i386（>=22.5.10），但无法安装

依赖于：libgstreamer-plugins-base1.0-0:i386（>=1.0.0），但无法安装

依赖于：libgstreamer1.0-0:i386（>=1.4.0），但无法安装

取决于：libpcap0.8:i386（>=1.5.1），但无法安装

取决于：libpulse0:i386（>=0.99.1），但无法安装

依赖于：libsane1:i386（>=1.0.27），但不可安装

依赖于：libudev1:i386（>=183），但无法安装

依赖于：libusb-1.0-0:i386（>=2:1.0.21），但无法安装

依赖于：libx11-6:i386，但无法安装

依赖于：libxext6:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386，但它不可安装或

libopencl1:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386（>=1.0），但它不可安装或

libopencl-1.2-1:i386，但无法安装

依赖于：libasound2插件：i386，但无法安装

依赖于：libncurses6:i386，但它不可安装或

libncurses5:i386，但它不可安装或

libncurses:i386，但无法安装

**Comment by 2536** [comment]
> 那你就把上面提示缺少的一个个安装全
以下程序包具有未满足的依赖项：

wine-table-i386:i386:依赖于：libasound2:i386（>=1.016），但不可安装

依赖于：libc6:i386（>=2.35），但无法安装

依赖于：libglib2.0-0:i386（>=2.37.3），但无法安装

依赖于：libgphoto2-6:i386（>=22.5.10），但无法安装

依赖于：libgphoto2-port12:i386（>=22.5.10），但无法安装

依赖于：libgstreamer-plugins-base1.0-0:i386（>=1.0.0），但无法安装

依赖于：libgstreamer1.0-0:i386（>=1.4.0），但无法安装

取决于：libpcap0.8:i386（>=1.5.1），但无法安装

取决于：libpulse0:i386（>=0.99.1），但无法安装

依赖于：libsane1:i386（>=1.0.27），但不可安装

依赖于：libudev1:i386（>=183），但无法安装

依赖于：libusb-1.0-0:i386（>=2:1.0.21），但无法安装

依赖于：libx11-6:i386，但无法安装

依赖于：libxext6:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386，但它不可安装或

libopencl1:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386（>=1.0），但它不可安装或

libopencl-1.2-1:i386，但无法安装

依赖于：libasound2插件：i386，但无法安装

依赖于：libncurses6:i386，但它不可安装或

libncurses5:i386，但它不可安装或

libncurses:i386，但无法安装

E： 无法更正问题，您持有损坏的包裹。

root@armbian：~#apt-get安装win-stable-i386:i386

正在读取程序包列表。。。多恩

正在生成依赖关系树。。。多恩

正在读取状态信息。。。多恩

某些程序包无法安装。这可能意味着你

请求一个不可能的情况，或者如果你正在使用不稳定的

尚未创建某些必需包的分发

或已移出“传入”。

以下信息可能有助于解决此问题：



以下程序包具有未满足的依赖项：

wine-table-i386:i386:依赖于：libasound2:i386（>=1.016），但不可安装

依赖于：libc6:i386（>=2.35），但无法安装

依赖于：libglib2.0-0:i386（>=2.37.3），但无法安装

依赖于：libgphoto2-6:i386（>=22.5.10），但无法安装

依赖于：libgphoto2-port12:i386（>=22.5.10），但无法安装

依赖于：libgstreamer-plugins-base1.0-0:i386（>=1.0.0），但无法安装

依赖于：libgstreamer1.0-0:i386（>=1.4.0），但无法安装

取决于：libpcap0.8:i386（>=1.5.1），但无法安装

取决于：libpulse0:i386（>=0.99.1），但无法安装

依赖于：libsane1:i386（>=1.0.27），但不可安装

依赖于：libudev1:i386（>=183），但无法安装

依赖于：libusb-1.0-0:i386（>=2:1.0.21），但无法安装

依赖于：libx11-6:i386，但无法安装

依赖于：libxext6:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386，但它不可安装或

libopencl1:i386，但无法安装

依赖于：ocl-cd-libopencl1:i386（>=1.0），但它不可安装或

libopencl-1.2-1:i386，但无法安装

依赖于：libasound2插件：i386，但无法安装

依赖于：libncurses6:i386，但它不可安装或

libncurses5:i386，但它不可安装或

libncurses:i386，但无法安装

**Comment by 2536** [comment]
> 那你就把上面提示缺少的一个个安装全

没有i386软件源，哪里有能用的 i386的软件源
![BX304FD`Y_P05P@OSW 06CA](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28776371/a009de0c-167c-409f-8b62-707d1cb15ab5)

**Comment by heyeshuang** [comment]
电视盒子是ARM芯片，i386是英特尔CPU的代号，不是能兼容的。我怀疑Wine是否能够安装在ARM系列芯片上，于是我去查了一下：https://zhuanlan.zhihu.com/p/377436448。

这种方法本质上是在ARM下模拟x86芯片，所以应该会非常慢……

**Comment by Scirese** [comment]
这issue就没啥意义, arm上装x86的包我也是第一次见

请去谷歌 `box86 wine`

Box86的效率已经相当可以了，只是盒子的性能都不是很强，能跑个老游戏或gal就不错了
