### ISSUE TITLE
老大，能适配一下EAIS-750E（a311d）吗

### ISSUE THREAD

**Issue by boboiougogo** [ophub/amlogic-s9xxx-armbian#1412]
这板子看起来接口挺多的，但是卖家只给我一些老版本的系统，还有其他一些功能说明，还是没有你做的好用。
这个链接是那个板子的说明文档，https://www.yuque.com/william-apmjq/vob7gl

**Comment by whmzsu** [comment]
这个搞定了吗？  release 中的a311d能通用吗？

**Comment by Mokou-Mokou** [comment]
现在能使用了吗
