### ISSUE TITLE
X96Max _Plus_5 WiFi Amlogic W150S1

### ISSUE THREAD

**Issue by dvborzov** [ophub/amlogic-s9xxx-armbian#142]
Hi. i have X96Max _Plus_5 with WiFi Amlogic W150S1
Thank you very much for the work you have done. dtb from your assembly Armbian_22.05.0_Aml_s905x3_focal_5.15.26_2022.03.05.1325.img.gz,
the only ones that managed to run Linux on the console. but the built-in wifi does not work
I pulled out a dtb([X96Max_Plus_5_20220110-1202.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8210282/X96Max_Plus_5_20220110-1202.zip)) file from Android. unpacked them in dts. and tried to compare, but there the structure is very different. do not tell me where to look how to add support for the WiFi Amlogic W150S1. in coreelec it works.

**Comment by ophub** [comment]
Android and armbian's dtb is not universal.

Send a link to the product introduction page of your device. You can find the source code of this wireless driver on github. Can be used in the mainline kernel. Android cannot be used.

**Comment by dvborzov** [comment]
bought here
https://aliexpress.ru/item/32933194456.html
version
2 ГБ + 16 ГБ + 2,4G Wifi + 100mb
photo
https://dl.dropboxusercontent.com/s/o7ukhod7zo8x9i3/shot_220309_123744.png
https://dl.dropboxusercontent.com/s/uthn61enylnfkpo/shot_220309_123754.png
https://dl.dropboxusercontent.com/s/axs3243eqgm29m9/shot_220309_123814.png

found only this
https://github.com/CoreELEC/w1-aml

**Comment by ophub** [comment]
The Android driver cannot be used, and the mainline kernel can be used.

**Comment by dvborzov** [comment]
Oh. I'm not very good at such things. I can't find another driver.

**Comment by ophub** [comment]
The x96 is really blooming, all kinds of hybrids. Not only the wired network card has changed, but even the wireless has changed. First time seeing this chip.

There is no way to do it without a driver. I will add it later when I find it.

**Comment by maskedeken** [comment]
@dvborzov Did WiFi Amlogic W150S1 work in CoreELEC? How to do that?

**Comment by achaoge** [comment]
> Hi. i have X96Max _Plus_5 with WiFi Amlogic W150S1 Thank you very much for the work you have done. dtb from your assembly Armbian_22.05.0_Aml_s905x3_focal_5.15.26_2022.03.05.1325.img.gz, the only ones that managed to run Linux on the console. but the built-in wifi does not work I pulled out a dtb([X96Max_Plus_5_20220110-1202.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8210282/X96Max_Plus_5_20220110-1202.zip)) file from Android. unpacked them in dts. and tried to compare, but there the structure is very different. do not tell me where to look how to add support for the WiFi Amlogic W150S1. in coreelec it works.

The same box with yours.
what the  u-boot and dtb file do you use?

**Comment by qinghua907** [comment]
我也有一个这种主板，不知道楼主的armbian wifi驱动搞定了吗？
