### ISSUE TITLE
BOX Bricked after Armbian-install to eMMC

### ISSUE THREAD

**Issue by hitesh83** [ophub/amlogic-s9xxx-armbian#1422]
**Device Information | 设备信息**
 - SOC: [eS095x3]
 - Model [x96 Max+]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.25]
 - Release: [jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

booted with USB, the Image used is (Armbian_23.05.0_amlogic_s905x3_jammy_6.1.25_server_2023.04.25.img)

With AV pin pressed, booted from USB, did initial setup like password time zone etc.

to install on eMMC did armbian-install, and selected the correct model with LAN port.
All scripts ran without any error, at the end BOX did shut down.

From there did not power ON at all, also USB Flash not working as the hardware is not able to detect the serial port.

I had flashed this box via USB 4-5 times till now, whatever the bootloader it was on, it always get flashed by USB tool.

Any way to get it detected in USB Flash or boot from SD/USB/eMMC etc. ??

**Comment by ophub** [comment]
There are more than a dozen variants of the X96 box, with more than a dozen branches in the installation options to choose from based on your device.

**Comment by hitesh83** [comment]
> There are more than a dozen variants of the X96 box, with more than a dozen branches in the installation options to choose from based on your device.

 Had tested a bunch of S9xx images in the past, so I know which one to use.
but now It is already bricked, nothing with USB to USB cable too.
Looks like I will have to short eMMC pins now. Any other way out?

**Comment by ophub** [comment]
have to short eMMC pins now
