### ISSUE TITLE
V22E已写入，想重新装。。。无从下手

### ISSUE THREAD

**Issue by smerckzak** [ophub/amlogic-s9xxx-armbian#1424]
**Device Information | 设备信息**
 - SOC: [S095L2B]
 - Model [e900v22e]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100]
 - Release: [jammy/s905l2-e900v21e] 选择的dbt是meson-gxl-s905l2-x7-5g
手贱写入emmc了。。。其他看着都正常。。
但是有线无线都没反应，找来一个无线网卡可以识别，可以看到设备上线。没有看到跑任何流量，也没办法ssh连接.不知是什么原因？
想重新刷，
.1看有些帖子说启动时按任意键，可以暂停系统启动，同时选择usb启动。。。我试了没有用，不知有没有系统命令直接reboot from usb？？
2.系统设置第一项--更换dbt。。。。我没敢试
请问大佬有没有啥好办法。
刷回安卓暂时没办法了，，，试了一圈刷机包都是无法识别ddr，卡在百分2那里。
就算刷回去，没看到有v22e安卓9的刷机包。

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

**Comment by smerckzak** [comment]
> https://github.com/ophub/kernel/releases/tag/tools

大佬，只有刷回安卓再刷arm的办法吗？这armbian不能直接设置U盘启动吗？

**Comment by ophub** [comment]
你问我的问题是找不到合适的安卓包，所以我给你个合适的。
你第二问能U盘重刷吗？能

**Comment by smerckzak** [comment]
> 你问我的问题是找不到合适的安卓包，所以我给你个合适的。 你第二问能U盘重刷吗？能
合适的安卓包我得尝试一下，但是我想要目前armbian系统下直接u盘启动新的armbian版本，有什么方法？
状况在一楼有所描述。。。希望大佬帮我参详一下。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

**Comment by a520ass** [comment]
原系统是安卓9？那配置应该是2+8吧，我有同款盒子，1+8的，自己做的ubuntu没有任何问题

**Comment by smerckzak** [comment]
> 原系统是安卓9？那配置应该是2+8吧，我有同款盒子，1+8的，自己做的ubuntu没有任何问题
是2+8的额。。你的1+8的应该是v21e吧。我用的就是v21e-5.15的那个包。。。我这个盒子原系统4.4的好像，不可能是9，我安装armbian的时候，机子没有root的。。。现在整个存储占了6.6g，都要满了
现在问题挺多，网线无线不能用,中文界面乱码，桌面安装了不能启动，ssh密码不对。就想重装,重新配置一下

**Comment by a520ass** [comment]
都是S905L2B ，没什么区别，我用的Ubuntu，有线，无线都是能用的。我21E都能刷22E的安卓线刷包

**Comment by smerckzak** [comment]
> 都是S905L2B ，没什么区别，我用的Ubuntu，有线，无线都是能用的。我21E都能刷22E的安卓线刷包

我试的安卓包确实都是l2b通刷，但是都刷不进去。换了三部电脑都不行。有XP系统也有win7系统。最多卡在4%加载uboot那步。。这两天有时间再试一下别的l2b看看了。。或者再装个win10试试。。
