### ISSUE TITLE
cm311-1a yst 莫名其妙的死机这个问题目前解决了吗，如果解决的话，推荐哪个内核呢？

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#1427]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
没听过有这种说法

**Comment by ysuolmai** [comment]
这种没头没尾的问题建议直接关掉。

**Comment by univerioiln233** [comment]
@ophub @ysuolmai 好像不是没头没尾（？CM311-1a 低负载依然会出现死机https://github.com/ophub/amlogic-s9xxx-armbian/issues/625  主要是对小盒子感兴趣时，读过同期issue（。 稍微感觉到第二位的傲慢了。

**Comment by univerioiln233** [comment]
巧了，最近在另一个项目也感到过，https://github.com/ihciah/shadow-tls/issues/30  二楼大哥

**Comment by ysuolmai** [comment]
傲慢？尊重是相互的，上来就问某某机型死机问题解决了么，从描述来看自己连试都没试过，指望着别人来告诉他，用了提问模版一个字不改就发上来，这尊重人吗？

另外，你贴的另外那个issue明显提问者是懂技术的，问题的描述也很清晰，压根不是一回事好吗？

另外我有10几个311-1a yst, 除了当年启动掉ip问题（后来在o大和xcray两位大佬合力下解决了），从来没碰到过会死机的问题。如果确实有个别机型版本有那问题，那也请把问题描述清楚，用了哪一版，什么内核，机器的照片，用的原来的安卓系统之类的。先学习下怎么提问在说话。
