### ISSUE TITLE
断电后系统随机无法启动

### ISSUE THREAD

**Issue by Lynn7758** [ophub/amlogic-s9xxx-armbian#1428]
**Device Information | 设备信息**
 - SOC: S950L3
 - Model SK-M74 创维二合一融合终端

**Armbian Version | 系统版本**
 - Kernel Version: Armbian_23.05.0_amlogic_s905l2-e900v21e_bullseye_5.15.112_server_2023.05.18
 - Release: 使用 Armbian_23.05.0_amlogic_s905l2-e900v21e_bullseye_5.15.112_server_2023.05.18img.gz烧录在U盘启动 然后armbian-install 刷入emmc emmc启动系统

**Describe the bug | 问题描述**
重复断电启动系统，系统卡在[    5.132640] meson-drm d0100000.vpu: Queued 3 outputs on vpu  这一步后无法进入系统，出现频率随机，一般操作20次内必出现。系统原硬盘改为三星128G 硬盘。
uboot time: 6017540 us
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.15.111-ophub (root@fv-az408-230) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205, GNU ld (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 2.39.0.20221210) #1 SMP PREEMPT Sat May 13 05:40:17 EDT 2023
[    0.000000] Machine model: Amlogic Meson GXL (S905L2) X7 5G Tv Box
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x0000000062c00000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x0000000077ffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000000ffffff]
[    0.000000]   node   0: [mem 0x0000000001000000-0x0000000004ffffff]
[    0.000000]   node   0: [mem 0x0000000005000000-0x00000000072fffff]
[    0.000000]   node   0: [mem 0x0000000007300000-0x000000000fffffff]
[    0.000000]   node   0: [mem 0x0000000010000000-0x00000000101fffff]
[    0.000000]   node   0: [mem 0x0000000010200000-0x0000000077ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000077ffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv0.2 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: Trusted OS migration not required
[    0.000000] percpu: Embedded 19 pages/cpu s37784 r8192 d31848 u77824
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: ARM erratum 845719
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 483840
[    0.000000] Kernel command line: root=UUID=4f0944e3-d627-4cbf-a7c4-aa82647e93f8 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 systemd.unified_cgroup_hierarchy=0 mac=ea:db:6a:ca:de:9f
[    0.000000] Unknown kernel command line parameters "mac=ea:db:6a:ca:de:9f", will be passed to user space.
[    0.000000] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 1570376K/1966080K available (15232K kernel code, 2724K rwdata, 4828K rodata, 3776K init, 891K bss, 133560K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu: 	RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000] 	Trampoline variant of Tasks RCU enabled.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 30 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] irq_meson_gpio: 110 to 8 gpio interrupt mux initialized
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000000] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000579] Console: colour dummy device 80x25
[    0.000963] printk: console [tty0] enabled
[    0.001003] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=80000)
[    0.001026] pid_max: default: 32768 minimum: 301
[    0.001237] LSM: Security Framework initializing
[    0.001356] SELinux:  Initializing.
[    0.001632] Mount-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.001657] Mountpoint-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.003850] rcu: Hierarchical SRCU implementation.
[    0.005216] EFI services will not be available.
[    0.005681] smp: Bringing up secondary CPUs ...
[    0.006349] Detected VIPT I-cache on CPU1
[    0.006411] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.007165] Detected VIPT I-cache on CPU2
[    0.007219] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.007908] Detected VIPT I-cache on CPU3
[    0.007955] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.008041] smp: Brought up 1 node, 4 CPUs
[    0.008108] SMP: Total of 4 processors activated.
[    0.008120] CPU features: detected: 32-bit EL0 Support
[    0.008129] CPU features: detected: 32-bit EL1 Support
[    0.008141] CPU features: detected: CRC32 instructions
[    0.008820] CPU: All CPU(s) started at EL2
[    0.008850] alternatives: patching kernel code
[    0.010317] devtmpfs: initialized
[    0.018094] Registered cp15_barrier emulation handler
[    0.018135] Registered setend emulation handler
[    0.018294] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6370867519511994 ns
[    0.018325] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.024870] prandom: seed boundary self test passed
[    0.026384] prandom: 100 self tests passed
[    0.049320] prandom32: self test passed (less than 6 bits correlated)
[    0.049373] pinctrl core: initialized pinctrl subsystem
[    0.049966] DMI not present or invalid.
[    0.050508] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.052484] DMA: preallocated 256 KiB GFP_KERNEL pool for atomic allocations
[    0.052721] DMA: preallocated 256 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.052905] DMA: preallocated 256 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.053005] audit: initializing netlink subsys (disabled)
[    0.053249] audit: type=2000 audit(0.049:1): state=initialized audit_enabled=0 res=1
[    0.054341] thermal_sys: Registered thermal governor 'step_wise'
[    0.054651] cpuidle: using governor ladder
[    0.054843] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.054962] ASID allocator initialised with 65536 entries
[    0.055148] Serial: AMBA PL011 UART driver
[    0.073124] platform c883a000.hdmi-tx: Fixing up cyclic dependency with d0100000.vpu
[    0.077571] platform cvbs-connector: Fixing up cyclic dependency with d0100000.vpu
[    0.077859] platform hdmi-connector: Fixing up cyclic dependency with c883a000.hdmi-tx
[    0.086922] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    0.086959] HugeTLB registered 32.0 MiB page size, pre-allocated 0 pages
[    0.086972] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.086985] HugeTLB registered 64.0 KiB page size, pre-allocated 0 pages
[    1.583978] cryptd: max_cpu_qlen set to 1000
[    1.587658] "cryptomgr_test" (91) uses obsolete ecb(arc4) skcipher
[    1.599222] alg: No test for 842 (842-generic)
[    1.599361] alg: No test for 842 (842-scomp)
[    1.695102] DRBG: Continuing without Jitter RNG
[    1.786109] raid6: neonx8   gen()  2215 MB/s
[    1.842842] raid6: neonx8   xor()  1600 MB/s
[    1.899577] raid6: neonx4   gen()  2166 MB/s
[    1.956307] raid6: neonx4   xor()  1524 MB/s
[    2.013038] raid6: neonx2   gen()  2064 MB/s
[    2.069765] raid6: neonx2   xor()  1416 MB/s
[    2.126494] raid6: neonx1   gen()  1770 MB/s
[    2.183217] raid6: neonx1   xor()  1214 MB/s
[    2.239952] raid6: int64x8  gen()  1415 MB/s
[    2.296674] raid6: int64x8  xor()   740 MB/s
[    2.353413] raid6: int64x4  gen()  1570 MB/s
[    2.410133] raid6: int64x4  xor()   809 MB/s
[    2.466854] raid6: int64x2  gen()  1398 MB/s
[    2.523587] raid6: int64x2  xor()   749 MB/s
[    2.580301] raid6: int64x1  gen()  1036 MB/s
[    2.637043] raid6: int64x1  xor()   517 MB/s
[    2.637054] raid6: using algorithm neonx8 gen() 2215 MB/s
[    2.637065] raid6: .... xor() 1600 MB/s, rmw enabled
[    2.637076] raid6: using neon recovery algorithm
[    2.637363] fbcon: Taking over console
[    2.637406] ACPI: Interpreter disabled.
[    2.639473] iommu: Default domain type: Translated 
[    2.639504] iommu: DMA domain TLB invalidation policy: strict mode 
[    2.639860] vgaarb: loaded
[    2.640457] SCSI subsystem initialized
[    2.640683] usbcore: registered new interface driver usbfs
[    2.640739] usbcore: registered new interface driver hub
[    2.640784] usbcore: registered new device driver usb
[    2.641285] mc: Linux media interface: v0.10
[    2.641317] videodev: Linux video capture interface: v2.00
[    2.641581] EDAC MC: Ver: 3.0.0
[    2.642686] Advanced Linux Sound Architecture Driver Initialized.
[    2.643850] clocksource: Switched to clocksource arch_sys_counter
[    2.644202] VFS: Disk quotas dquot_6.6.0
[    2.644298] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    2.644474] FS-Cache: Loaded
[    2.644971] pnp: PnP ACPI: disabled
[    2.651585] NET: Registered PF_INET protocol family
[    2.651786] IP idents hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    2.653035] tcp_listen_portaddr_hash hash table entries: 1024 (order: 2, 16384 bytes, linear)
[    2.653087] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    2.653108] TCP established hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    2.653282] TCP bind hash table entries: 16384 (order: 6, 262144 bytes, linear)
[    2.653491] TCP: Hash tables configured (established 16384 bind 16384)
[    2.653781] MPTCP token hash table entries: 2048 (order: 3, 49152 bytes, linear)
[    2.653924] UDP hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    2.653977] UDP-Lite hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    2.654165] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    2.654202] NET: Registered PF_XDP protocol family
[    2.654224] PCI: CLS 0 bytes, default 64
[    2.654496] Trying to unpack rootfs image as initramfs...
[    2.661408] hw perfevents: enabled with armv8_cortex_a53 PMU driver, 7 counters available
[    2.661944] kvm [1]: IPA Size Limit: 40 bits
[    2.662817] kvm [1]: vgic interrupt IRQ9
[    2.662975] kvm [1]: Hyp mode initialized successfully
[    3.399606] Freeing initrd memory: 17300K
[    3.583992] Initialise system trusted keyrings
[    3.584272] workingset: timestamp_bits=46 max_order=19 bucket_order=0
[    3.590741] zbud: loaded
[    3.592364] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.592909] fuse: init (API version 7.34)
[    3.593387] SGI XFS with ACLs, security attributes, quota, no debug enabled
[    3.633434] NET: Registered PF_ALG protocol family
[    3.687399] xor: measuring software checksum speed
[    3.691592]    8regs           :  2366 MB/sec
[    3.695123]    32regs          :  2802 MB/sec
[    3.699915]    arm64_neon      :  2064 MB/sec
[    3.699926] xor: using function: 32regs (2802 MB/sec)
[    3.699943] Key type asymmetric registered
[    3.699954] Asymmetric key parser 'x509' registered
[    3.700097] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 245)
[    3.700281] io scheduler mq-deadline registered
[    3.700295] io scheduler kyber registered
[    3.700472] io scheduler bfq registered
[    3.725945] soc soc0: Amlogic Meson Unknown (Unknown) Revision 2a:e (c5:2) Detected
[    3.728415] Serial: 8250/16550 driver, 5 ports, IRQ sharing enabled
[    3.730435] Serial: AMBA driver
[    3.730879] c81004c0.serial: ttyAML0 at MMIO 0xc81004c0 (irq = 22, base_baud = 1500000) is a meson_uart
[    4.758890] printk: console [ttyAML0] enabled
[    4.772984] brd: module loaded
[    4.839581] loop: module loaded
[    4.846580] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.847525] ehci-pci: EHCI PCI platform driver
[    4.851964] ehci-platform: EHCI generic platform driver
[    4.857676] usbcore: registered new interface driver cdc_wdm
[    4.862741] usbcore: registered new interface driver usb-storage
[    4.869195] mousedev: PS/2 mouse device common for all mice
[    4.875337] SPI driver rmi4_spi has no spi_device_id for syna,rmi4-spi
[    4.881503] meson-vrtc c81000a8.rtc: registered as rtc0
[    4.885814] meson-vrtc c81000a8.rtc: setting system clock to 1970-01-01T00:00:04 UTC (4)
[    4.894398] i2c_dev: i2c /dev entries driver
[    4.900365] Registered IR keymap rc-cec
[    4.901961] rc rc0: meson_ao_cec as /devices/platform/soc/c8100000.bus/c8100100.cec/rc/rc0
[    4.910168] input: meson_ao_cec as /devices/platform/soc/c8100000.bus/c8100100.cec/rc/rc0/input0
[    4.922408] sdhci: Secure Digital Host Controller Interface driver
[    4.924880] sdhci: Copyright(c) Pierre Ossman
[    4.929171] Synopsys Designware Multimedia Card Interface Driver
[    4.935976] sdhci-pltfm: SDHCI platform and OF driver helper
[    4.936503] meson-gx-mmc d0072000.mmc: Got CD GPIO
[    4.937636] meson-gx-mmc d0074000.mmc: allocated mmc-pwrseq
[    4.943260] meson-sm: secure-monitor enabled
[    4.957576] gxl-crypto c883e000.crypto: will run requests pump with realtime priority
[    4.963109] gxl-crypto c883e000.crypto: will run requests pump with realtime priority
[    4.974407] hid: raw HID events driver (C) Jiri Kosina
[    4.975947] usbcore: registered new interface driver usbhid
[    4.979986] gpio irq setup: hwirq: 0x3A irqfirst: 0x34 irqlast: 0x3A pin[48]
[    4.981399] usbhid: USB HID core driver
[    4.981981] platform-mhu c883c404.mailbox: Platform MHU Mailbox registered
[    4.988741] genirq: Setting trigger mode 3 for irq 46 failed (meson_gpio_irq_set_type+0x0/0x100)
[BL31]: tee size: 0
[    5.012669] Initializing XFRM netlink socket
[    5.014498] NET: Registered PF_INET6 protocol family
[    5.049333] Segment Routing with IPv6
[    5.049378] RPL Segment Routing with IPv6
[    5.051433] In-situ OAM (IOAM) with IPv6
[    5.055417] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    5.062238] NET: Registered PF_PACKET protocol family
[    5.066157] NET: Registered PF_KEY protocol family
[    5.071042] 8021q: 802.1Q VLAN Support v1.8
[    5.075512] registered taskstats version 1
[    5.079068] Loading compiled-in X.509 certificates
[    5.086166] zswap: loaded using pool zstd/zbud
[    5.088820] Key type .fscrypt registered
[    5.092082] Key type fscrypt-provisioning registered
[    5.098040] Btrfs loaded, crc32c=crc32c-generic, zoned=no, fsverity=no
[    5.132640] meson-drm d0100000.vpu: Queued 3 outputs on vpu

**Comment by Lynn7758** [comment]
![微信图片_20230525220730](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131445998/3d733b07-3b7b-4538-8ab6-b1aa0dabe32d)
![Uploading 微信图片_20230525220722.jpg…]()
![微信图片_20230525220712](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131445998/b7438cb1-0951-4551-907c-f4f537c7c4f9)

**Comment by yiqihongchen** [comment]
谁有正确的DTB

**Comment by aolin2000** [comment]
我的cm211-1增强版也是碰到了这个问题，偶发无法启动，也是卡在同一个地方，楼主解决了没有？

**Comment by Lynn7758** [comment]
没有完全解决，改成三星emmc后出现的概率就低了！你的更换过emmc没有呢！

**Comment by Lynn7758** [comment]
这个问题一直没有解决，我就加了个定时重启的物理硬件来解决的这个问题

**Comment by aolin2000** [comment]
除了这个问题，我的还有一个网卡的问题，有线网卡接我自己的小米路由器的网口，经常不工作，接别的路由器比如华为的路由器则基本没有问题

**Comment by aolin2000** [comment]
无法启动不是emmc的问题，是软件的问题
说一下你是怎么解决的，用什么硬件解决?
