### ISSUE TITLE
compile-kernel 中的 -a 参数疑似无法按预期工作

### ISSUE THREAD

**Issue by ghost** [ophub/amlogic-s9xxx-armbian#1429]
问题：
首次编译内核，使用默认 unifreq 仓库，并指定低于最新版的内核，即使设置 -a false，仍会编译同系列最新版。

例如：
sudo ./recompile -k 5.10.176 -a false
生成的内核文件名显示 5.10.176，但实际打包内核为 5.10.180（仓库的最新commit），导致内核无法正常使用。

**Comment by ophub** [comment]
`-a false` 的意思是不去服务器查询和下载源码了。直接使用本地的源码和传入的版本号进行编译。所以你传入的版本号要和本地的一致。

**Comment by ophub** [comment]
我见过的都带一个版本签名，包括亚马逊云、甲骨文云等云主机的Ubuntu里的内核。我没试过不要行不行。
