### ISSUE TITLE
希望帮忙适配一个机器[MPC1903] 有dts

### ISSUE THREAD

**Issue by altmangood** [ophub/amlogic-s9xxx-armbian#1432]
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [MPC1903]

规格参数
https://www.rockemb.com/armgongkongji/PK3399pingtai/26.html#link3

OP项目dts文件（OP进了主干并且全部功能可以用）
https://github.com/coolsnowwolf/lede/blob/master/target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3399-mpc1903.dts

找到个同机器的armbian提交，但是没进主干，作者说自己没测试过。
https://github.com/Lollipop907/armbian-build/blob/0ecc9cef7e3776ede10763db4d30643f01e9b850/patch/u-boot/u-boot-rockchip64/add-board-mpc1903.patch

希望大佬可以帮忙适配一个包，我这边测试一下。

**Comment by ophub** [comment]
编译使用的u-boot和dts都使用了lede的源码：

u-boot:
https://github.com/coolsnowwolf/lede/blob/master/package/boot/uboot-rockchip/patches/307-rockchip-rk3399-Add-support-for-Rocktech-MPC1903.patch

dts:
https://github.com/coolsnowwolf/lede/blob/master/target/linux/rockchip/files/arch/arm64/boot/dts/rockchip/rk3399-mpc1903.dts

**Comment by altmangood** [comment]
试了卡启无法点亮HDMI，可能lede本身不用HDMI有关。我今天晚上试试TTL看下日志情况。

**Comment by ophub** [comment]
路由器里有IP吧，ssh连接下看看启动成功没。

**Comment by altmangood** [comment]
IP没分配到，我RS232的线还在买，先关闭issue，后续我看下日志

**Comment by ophub** [comment]
设备测试的怎么样了，能正常使用吗

**Comment by 67113513** [comment]
@altmangood，我试了也是hdmi没亮，这个232线是接那个口看ttl的？
