### ISSUE TITLE
Armbian_23.05.0_amlogic_s905l3a_bullseye_5.15.112_server_2023.05.18.img.gz

### ISSUE THREAD

**Issue by zhy667911** [ophub/amlogic-s9xxx-armbian#1433]
以上这个版本安装啥都提示  can't chmod /var/cache/man/cat1: Operation not permitted
还有这个系统经常下载到90%要求认证 很奇特 有别的下载地址吗？

**Comment by ophub** [comment]
不要把armbian的系统盘插在运行的安卓系统里，这样会被修改了权限。
重装。拔了电源，插入u盘，插电开机，安装armbian。

你说的认证截图看看是什么

**Comment by gametta** [comment]
我已经将5月的版本全部下载下来了，截止到5.18.总的不到300G不知道O大是否允许发布到网盘分发。

**Comment by ophub** [comment]
这是开源项目，包括源代码和所有镜像文件都可以自由使用和分发。
