### ISSUE TITLE
armbian如何设置走代理ip

### ISSUE THREAD

**Issue by kaige348** [ophub/amlogic-s9xxx-armbian#1434]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by altmangood** [comment]
这种简单问题交给GPT


要在Armbian上设置代理IP，您可以按照以下步骤使用NetworkManager进行配置：

1. 确保您的Armbian系统上已安装NetworkManager。如果未安装，请使用以下命令安装：
   ```
   sudo apt-get update
   sudo apt-get install network-manager
   ```

2. 打开NetworkManager的配置文件：
   ```
   sudo nano /etc/NetworkManager/NetworkManager.conf
   ```

3. 在配置文件中找到并取消注释以下行，以便允许使用代理：
   ```
   [main]
   plugins=keyfile
   
   [keyfile]
   unmanaged-devices=none
   ```

4. 保存并关闭文件（按Ctrl+X，然后按Y保存）。

5. 重新启动NetworkManager服务：
   ```
   sudo systemctl restart NetworkManager
   ```

6. 现在您可以通过编辑网络连接配置文件来设置代理。假设您使用的是以太网接口（例如eth0），请执行以下步骤：
   - 打开以太网接口的配置文件：
     ```
     sudo nano /etc/NetworkManager/system-connections/eth0.nmconnection
     ```

   - 在文件的`[ipv4]`或`[ipv6]`部分下添加以下行，根据您使用的代理类型进行调整：
     - 对于HTTP代理：
       ```
       method=auto
       proxy.method=manual
       proxy.pac-url=
       proxy.type=http
       proxy.url=http://proxy_ip:proxy_port/
       ```

     - 对于SOCKS代理：
       ```
       method=auto
       proxy.method=manual
       proxy.pac-url=
       proxy.type=socks
       proxy.socks=proxy_ip
       proxy.port=proxy_port
       ```

     将`proxy_ip`和`proxy_port`替换为您的代理服务器的IP地址和端口。

   - 保存并关闭文件。

7. 重启网络连接以使更改生效。您可以使用以下命令重启以太网连接（eth0）：
   ```
   sudo nmcli connection down eth0 && sudo nmcli connection up eth0
   ```

现在，您的Armbian系统应该会使用设置的代理IP进行网络连接。请根据您的实际情况进行相应的调整和配置。

**Comment by kaige348** [comment]
非常感谢

**Comment by l1991l** [comment]
你也可以试试弄个旁路由，让后把网关指向旁路由的IP，并在旁路由的OPENWRT系统上设置PASSWALL这样就可以不用在Armbian中设置那么多。并且如果有其他设备需要走代理，只要改一下网关IP就行了。
祝你好运٩(๑•ㅂ•)۶
