### ISSUE TITLE
Failed to restore

### ISSUE THREAD

**Issue by nehilo** [ophub/amlogic-s9xxx-armbian#144]
After install armbian on emmc, try to restore on Android fw. Reset button not working. Failed to startup boot

**Comment by dinhchinh82** [comment]
You may need to short clock pin to bring the box into flash firmware mode. Please give more detail about your android box.

**Comment by ophub** [comment]
How to recover：

https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#108-how-to-recover-if-the-install-fails-and-cannot-be-started

**Comment by nehilo** [comment]
> You may need to short clock pin to bring the box into flash firmware mode. Please give more detail about your android box.

X96Max plus

**Comment by ophub** [comment]
The tutorial is exactly this device, just follow it

**Comment by nehilo** [comment]
> The tutorial is exactly this device, just follow it

Thanks! Restore complete!

**Comment by ophub** [comment]
Congratulations
