### ISSUE TITLE
h96pro+刷入armbian后自动关机

### ISSUE THREAD

**Issue by hisong90** [ophub/amlogic-s9xxx-armbian#1440]
h96pro+刷入armbian后自动关机，s912几个版本都试了，可以刷，问题是要么输入armbian install就关机，或者刷入后一段时间比如10分钟后就自动关机。希望能指点一下，谢谢

**Comment by ophub** [comment]
下载最新的固件: https://github.com/ophub/amlogic-s9xxx-armbian/releases
h96pro安装时使用主线：`armbian-install -m yes`

**Comment by hisong90** [comment]
> 下载最新的固件: https://github.com/ophub/amlogic-s9xxx-armbian/releases h96pro安装时使用主线：`armbian-install -m yes`

谢谢。写入emmc后安装软件关机了一下，重启后运行一个小时没有关机。还想咨询一下，在arbmian-config和nmtui都找不到WIFI，是h96pro+这个设备无法使用wifi还是我没安驱动？
安装的版本是Armbian_ _23.05.0_ amlogic_ s912_ jammy_ 6.1.30. _server. 2023.05.26.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

看12.7.3

**Comment by hisong90** [comment]
![2~`A0 S{VM97J~GWDJM27UF](https://github.com/ophub/amlogic-s9xxx-armbian/assets/126738140/61726da3-79e2-4b45-8e67-4fd52e580407)
没有wifi选项呢。

**Comment by ophub** [comment]
看来驱动不了，用有线吧
