### ISSUE TITLE
cm311-1a 已成功刷入emmc，修改密码后无法登录

### ISSUE THREAD

**Issue by lijiebo** [ophub/amlogic-s9xxx-armbian#1441]
cm311-1a ，cpu s905l3a，固件Armbian_23.05.0_amlogic_s905l3a_jammy_5.15.110_server_2023.05.13.img.gz，已成功刷入emmc，其它操作一切正常，也可以更新系统，安装软件，但修改密码后无法登录，密码又明明是正确的。只能再次重新写入emmc，再次修改密码，提示修改成功后，但登录又不行。不知道问题在哪，求教下老大。

**Comment by ophub** [comment]
举例：你的用户叫：zhangsanfeng
`sudo passwd zhangsanfeng`

**Comment by lijiebo** [comment]
刷emmc之前并没有创建新帐号的，所以登录的时候是root登录的，那么passwd 应该修改的也是root的密码吧。修改完后，再登录就提示密码错误了。

**Comment by ophub** [comment]
注意大小写
