### ISSUE TITLE
下载分流，BAIDU cloud。

### ISSUE THREAD

**Issue by gametta** [ophub/amlogic-s9xxx-armbian#1442]
截止到5.18日版本。

链接：https://pan.baidu.com/s/1KtMpx_4JjdBrl55IJpGW1g 
提取码：kh6a 
--来自百度网盘超级会员V7的分享

**Comment by ophub** [comment]
感谢热心支持，内核和armbian系统可以分2个目录存放，这样方便文件多了查找。
