### ISSUE TITLE
How to  install desktop

### ISSUE THREAD

**Issue by DoroteoArango** [ophub/amlogic-s9xxx-armbian#1443]
**Device Information |
 - SOC: S095x3
 - Model x96 máx plus 

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]
*** I tryed to install, but only get error, thanks a lot and thanks for allí tour work.

**Comment by ophub** [comment]
armbian-software
201
