### ISSUE TITLE
无法通过github action编译，提示磁盘空间不足

### ISSUE THREAD

**Issue by ysuolmai** [ophub/amlogic-s9xxx-armbian#1445]
之前都编译很成功，最近试了各种组合都无法编译了，仔细看了下build的log，发现提示空间不够?

[🌱] Checking [ basic host setup ]
  [🌱] Build host OS release [ jammy ]
  [🌱] Build host architecture [ amd[64](https://github.com/ysuolmai/amlogic-s9xxx-armbian/actions/runs/5128409397/jobs/9225061988#step:6:72) ]
  [🚸] Low free space left [ /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/cache: 0GiB free, 10 GiB required ]
  Warning:  Low free space left /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/cache: 0GiB free, 10 GiB required
  [💥] error! [ Exiting due to 'Low free disk space left in '/home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/cache'' - not interactive, exiting immediately.  ]
  Error:  error! Exiting due to 'Low free disk space left in '/home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/cache'' - not interactive, exiting immediately. 
  [💥] Exiting with error 43 [ at /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/lib/functions/logging/traps.sh:1
                  exit_with_error() --> lib/functions/logging/traps.sh:1
     exit_if_countdown_not_aborted() --> lib/functions/general/countdown.sh:21
     check_host_has_enough_disk_space() --> lib/functions/host/prepare-host.sh:380
                 check_basic_host() --> lib/functions/host/prepare-host.sh:34
                  do_with_logging() --> lib/functions/logging/section-logging.sh:81
      prep_conf_main_build_single() --> lib/functions/main/config-prepare.sh:40
           cli_standard_build_run() --> lib/functions/cli/cli-build.sh:22
          armbian_cli_run_command() --> lib/functions/cli/utils-cli.sh:136
                   cli_entrypoint() --> lib/functions/cli/entrypoint.sh:176
                             main() --> compile.sh:50
   ]
  Error:  Exiting with error 43 at /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/lib/functions/logging/traps.sh:1

我只是改了默认bullseye/bookworm，以及默认s905l3a-cm311,不至于直接影响虚拟机空间吧？各位有遇到类似的问题么

**Comment by ophub** [comment]
在上游armbian/build仓库的问题区里第二个问题可以看到解决办法。这是上游的一个bug，还没合并修复。

**Comment by ysuolmai** [comment]
> 在上游armbian/build仓库的问题区里第二个问题可以看到解决办法。这是上游的一个bug，还没合并修复。这个问题有10来天了，等上游修复吧。

感谢O大。

根据Issue里说的，自己在action脚本里加了一行，编译就正常了。

具体就是在Download source code部分的git clone之后加一行
mkdir -p /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/cache

编译就正常了。

**Comment by ophub** [comment]
是的，这个bug就是合并的回复者的一个pr后产生的bug，这个大佬在armbian仓库代码贡献者里排名第三，是个优秀的贡献者。我一天看几遍等他修复这个bug，等了10来天了，他们怎么不修复呢，真是奇怪。
