### ISSUE TITLE
请问写入 EMMC 后（u-boot 也写入了），不能引导 TF 卡中的 EmuELEC 怎么办？

### ISSUE THREAD

**Issue by FanchangWang** [ophub/amlogic-s9xxx-armbian#1446]
机器  百事通 R3300L  s905lb
镜像  Armbian_23.05.0_amlogic_s905lb-r3300l_jammy_6.1.30_server_2023.05.26.img

系统已经写入 EMMC ，使用命令 `armbian-install -m yes -a no` 将 u-boot 也写入了，不插入 TF 卡的时候 EMMC 中的 armbian 能正常启动。

TF 卡中写入 EmuELEC ，插入机器开机，EmuELEC 无法引导，包括 EMMC 中的 armbian 也不会引导。之前 EMMC 是 android 的时候可以正常引导 TF 卡中的 EmuELEC 。

请问这种是什么原因？是 u-boot 不支持引导 EmuELEC 吗？

**Comment by FanchangWang** [comment]
刚才在 [Calmact/e900v22c](https://github.com/Calmact/e900v22c) 这个库的 [在线文档](https://docs.qq.com/doc/DWFprWWxZa290VXNk) 里面看到了关于 `u-boot` 的一些说明，好像我不应该把 `u-boot` 也写入 EMMC 的。。。

> ### Armbian系统引导

> Linux内核在从5.9版本到5.10版本更新时进行了一次内核偏移地址的变更，导致旧版的u-boot无法直接引导5.10+的内核。由于目前安卓系统使用的内核版本依旧停留在老旧的4.9甚至是3.14版本，因而原厂配置的u-boot版本也基本都是旧版，不能直接支持引导5.10+的内核。
> 因此，要想引导5.10+的内核，必须使用额外的手段。目前，有以下三种方法可以引导新版本内核：

> 1.使用完整版的主线u-boot（包含了初始化设备内存代码，可开机后直接由CPU加载运行）来直接替换原厂u-boot。该方法的好处是完全没有了原厂u-boot的限制，整个emmc除了开头存储u-boot的4MB空间，都可以随意使用。缺点是必须提取得到初始化设备内存的代码（acs.bin）后才能制作完整版的主线u-boot，而这部分代码通常是设备间不通用的，此外主线u-boot仅能引导启动Linux 4.16+的内核，因此使用该方法后无法引导停留在4.9内核安卓/CoreELEC/EmuELEC系统。

**Comment by ophub** [comment]
我支持同时在tf使用EmuELEC

**Comment by FanchangWang** [comment]
> 我支持同时在tf使用EmuELEC

是通过主线 u-boot 引导的 tf 卡 Emuelec 吗？

**Comment by ophub** [comment]
不支持Emuelec

**Comment by FanchangWang** [comment]
> 不支持Emuelec

我不该写入 u-boot 的，失策了 囧rz
