### ISSUE TITLE
X96 max+ 2gb,show bootup strange

### ISSUE THREAD

**Issue by andarezta** [ophub/amlogic-s9xxx-armbian#1447]
**Device Information | 设备信息**
 - SOC: S095x3
 - Model x96 max + 2gb ram

**Armbian Version 23.05
 - Kernel Version: 5.15
 - Release: jammy & bulseye

the bootup show load ethernet driver very strange & didn't stop.login promp not show.but ssj work.
I try every x96 max dtb's,nome of them detect ethernet,only sei610 dtb ethernet working.
And all dtb not detect wifi device

**Comment by ophub** [comment]
does not support wifi

**Comment by andarezta** [comment]
![20230601_013540](https://github.com/ophub/amlogic-s9xxx-armbian/assets/96639750/5178d22b-52a4-40e6-bf5c-e24b44a62fd3)

**Comment by ophub** [comment]
Disable the wireless module
