### ISSUE TITLE
armbian-update -c 参数失效？

### ISSUE THREAD

**Issue by shanlanCoding** [ophub/amlogic-s9xxx-armbian#1448]
**Device Information | 设备信息**
 - SOC: s905l3b
 - Model cm311-1s ch

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]
 - 后面补充，暂时不知道查看命令。
 `root@armbian:~# uname -a`
`Linux armbian 6.1.30-ophub #1 SMP Fri May 26 17:27:58 CST 2023 aarch64 GNU/Linux`

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

使用-c参数指定加速的域名ip，发现不能正常下载，导致更新失败。可以观察设备的输出信息，只是拼接在下载链接的前面。

```
root@armbian:~# armbian-update -c 20.205.243.166
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Dependency check completed.

[ STEPS ] Start checking network status...
[ INFO ] Network status is normal.

[ STEPS ] Start initializing parameters...
[ INFO ] Armbian platform: [ amlogic ]
[ INFO ] Kernel download repository: [ ophub/kernel ]
[ INFO ] Kernel download cdn: [ 20.205.243.166/ ]
[ INFO ] Kernel tags: [ dev ]
[ INFO ] Kernel version: [  ]
[ INFO ] Armbian is running on: [ /dev/sda ]

[ STEPS ] Start querying kernel version...
[ INFO ] Current version: [ 6.1.30 ], Latest version: [ 6.1.31 ].

[ STEPS ] Start downloading kernel package...
[ INFO ] Download kernel from: [ 20.205.243.166/https://github.com/ophub/kernel/releases/download/kernel_dev/6.1.31.tar.gz ]
[ INFO ] Download kernel to:   [ /tmp/tmp.0UY1qGpj4z ]
[ ERROR ] Failed to download kernel.

```
Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/44717382/8ccfed8d-ff14-4a2f-91c3-dfc233527e64)

**Comment by ophub** [comment]
armbian-update -c https://xxxxx/
这种格式，需要是真的cdn网站

**Comment by shanlanCoding** [comment]
再比如输入命令`ip a  输出：command not found`

**Comment by shanlanCoding** [comment]
> armbian-update -c https://xxxxx/ 这种格式，需要是真的cdn网站

你好，在线等，挺急的。

**Comment by ophub** [comment]
缺啥装啥，apt里应有尽有

**Comment by shanlanCoding** [comment]
> 缺啥装啥，apt里应有尽有

不是。不接USB硬盘的时候一切都好。一旦接上，就连`ls`命令都会失效。试过U盘正常，还能挂载。
