### ISSUE TITLE
s912还是启动不了

### ISSUE THREAD

**Issue by 3136083906** [ophub/amlogic-s9xxx-armbian#145]
u盘可以启动，写入emmc后就启动不了，章鱼星球

**Comment by ophub** [comment]
屏幕显示什么错误？

**Comment by 3136083906** [comment]
> 屏幕显示什么错误？原来是什么系统？装了ce等系统，要先还原成原来的安卓TV再安装。

黑屏，但不是无信号的那种，已经刷了第三方bl，可以u盘直接启动，你的op固件没问题，我以前刷过安卓再启动安装的，但也一样，u盘启动没问题，写入emmc启动就不行

**Comment by ophub** [comment]
你的意思是OpenWrt刷入emmc没问题，但是Armbian刷入emmc无法启动？

**Comment by ophub** [comment]
```
21:Octopus Planet:s912:meson-gxm-octopus-planet.dtb:u-boot-zyxq.bin:NA:NA:4C@1512Mhz+4C@1000Mhz,2GB Mem,1Gb Nic
```
Armbian:
https://github.com/ophub/amlogic-s9xxx-armbian/blob/db7112719cbc7c0895f426b8a897613661d6d1a9/build-armbian/common-files/files/usr/sbin/armbian-install#L87

OpenWrt:
https://github.com/ophub/luci-app-amlogic/blob/37d18ec7d528ba5bdd432546a7a8aa833798ca12/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic#L118

**Comment by 3136083906** [comment]
> 你的意思是OpenWrt刷入emmc没问题，但是Armbian刷入emmc无法启动？

是啊，我的章鱼星球黑色的

**Comment by ophub** [comment]
试试今天编译的固件
