### ISSUE TITLE
Armbian_23.08.0_amlogic_s905l3a_lunar_6.1.31 安装桌面时出错

### ISSUE THREAD

**Issue by yhbas** [ophub/amlogic-s9xxx-armbian#1451]
**Device Information | 设备信息**
 - SOC: [S095l3a]
 - Model [CM311-1a YST]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.31]
 - Release: [Armbian_23.08.0_amlogic_s905l3a_lunar_6.1.31_server_2023.06.01.img.gz]

**Describe the bug | 问题描述**
无法安装桌面。
armbian-software 选201，无法安装桌面。
开机时有这个提示 ： no end-user support : unsupported(lunar) userspace 
安装桌面时有这个提示： [ERROR] unsupported system [lunar]

是因为现在版本已经升级到lunar了？桌面配套的安装脚本没更新？

**Comment by ophub** [comment]
你说的对，lunar和bookworm第一次编译，没详细测试，可能存在未知bug比较多。
用jammy和bullsyee吧

**Comment by yhbas** [comment]
6.1.30 jammy安装桌面如果选lightdm管理器，会无法启动，需要安装lightdm-gtk-greeter才可以正常进入桌面
apt install lightdm-gtk-greeter

希望O大在今后版本中能把这个也修改下。

**Comment by ophub** [comment]
好的，新添加的两个镜像我都安装一遍试试有什么变动

**Comment by ophub** [comment]
刚才更新了下armbian-software，适配了 lunar 系统：https://github.com/ophub/amlogic-s9xxx-armbian/commit/a7288edc9312f48a8ac635f39efefbeb142955ca

我在 n1（USB） 上把 lunar 的全部桌面软件都安装测试了一遍，安装桌面时我选择的 `gdm3` 选项，经测试桌面使用正常，中文显示正常，有线网络正常，无线正常，蓝牙正常，目前测试没发现问题。

![Snip20230605_5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/9c100bcd-ff18-42ba-b278-ed81b774199f)
![Snip20230605_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/271a82ac-f1ec-446d-bbfc-54c2746fe96d)
![Snip20230605_4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/b5c8f3cc-0398-4ecf-9af1-bc4071a62f14)
![Snip20230605_3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/b60b4f92-1e5a-4d45-a0ea-888e6a13cead)
![Snip20230605_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/cddecd27-c19d-4d4e-8545-5a62c269beae)

**Comment by yhbas** [comment]
O大辛苦！CM311-1a YST测试通过，桌面安装顺利！非常完美！

另外反馈下，新版本进桌面时，有下面重复信息，应该问题不大吧。
fe.dai-lin-2: ASoC: error at dpcm_fe_dai_prepare on fe.dai-lin-2: -22
fe.dai-lin-2: ASoC: no backend DAIs enabled for fe.dai-lin-2:

**Comment by ophub** [comment]
/boot/uEnv.txt 加 
`dtoverlay=disable-dwc2 dtoverlay=disable-bt`
试试，这可能是音频驱动错误引起的

**Comment by lamhui** [comment]
> 

O大，刚接触armbian，请教一下我也是N1的机子下了网页最新的那个584M的固件刷U盘启动后全部按照操作更新内核也获取权限（sudo -i）了然后armbian-software要安装桌面系统（Desktop 201项）经过漫长的跑码之后貌似机器自动重启然后依旧还是在第一次为登录系统的画面下遂继续以上操作然后armbian-software列表中看到desktop选项中是显示non-install，请问这是什么原因呢？我已经折腾了好几天了，麻烦看到给解惑指点一下。感谢！
