### ISSUE TITLE
关于 lunar 标识为 lts 的问题

### ISSUE THREAD

**Issue by wordlesswind** [ophub/amlogic-s9xxx-armbian#1453]
由于 [Ubuntu 23.04](https://ubuntu.com/about/release-cycle 不是一个长期支持版本，那么作为下游的 Armbian 没道理独立将其维护成长期支持版本吧，我没有找到与之有关的信息。

是否应当移除 Releases 中 lunar 标题的 lts 标识？

**Comment by ophub** [comment]
我的lts是`长期存储（Long-term storage ）`的英文缩写`lts`

从5.13号开始，releases不再每周构建新的后删档旧的，开始进行长期保留（预计保留3个月）

你是不是理解成了长期支持呢？Long-term support缩写lts?


这个关键词的真实用途是给actions用的，让删除releases时见到我指定保留的不要删除，除lts外还有kernel和v0.1.0的tags都不要删了：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/fda8b04a3c206daf7c4df46f49a523ea8c72fc49/.github/workflows/delete-older-releases-workflows.yml#L41-L44

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/05364860cccbf8b6571fee0920d5c98777c88c69

tags关键词更换了
