### ISSUE TITLE
不能安装宝塔吗？

### ISSUE THREAD

**Issue by AAhandsome** [ophub/amlogic-s9xxx-armbian#1454]
: 无法定位软件包 libcurl4-openssl-dev
E: 无法定位软件包 libxml2-dev
E: 无法定位软件包 zlib1g-dev
E: 无法定位软件包 libjpeg-dev
E: 无法定位软件包 libpng-dev
E: 软件包 libpcre3-dev 没有可安装候选
E: 无法定位软件包 swig
E: 无法定位软件包 libffi-dev
E: 无法定位软件包 libbz2-dev
E: 无法定位软件包 libncurses-dev
E: 无法定位软件包 libsqlite3-dev
E: 无法定位软件包 libreadline-dev
E: 无法定位软件包 tk-dev
E: 无法定位软件包 libgdbm-dev
E: 无法定位软件包 libdb-dev
E: 无法定位软件包 libdb++-dev
E: 无法按照正则表达式 libdb++-dev 找到任何软件包
E: 无法定位软件包 libpcap-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libcurl4-openssl-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libxml2-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 zlib1g-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libjpeg-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libpng-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
没有可用的软件包 libpcre3-dev，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

E: 软件包 libpcre3-dev 没有可安装候选
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 swig
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libffi-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libbz2-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libncurses-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libsqlite3-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libreadline-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 tk-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libgdbm-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libdb-dev
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libdb++-dev
E: 无法按照正则表达式 libdb++-dev 找到任何软件包
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
E: 无法定位软件包 libpcap-dev

**Comment by ophub** [comment]
更新源
