### ISSUE TITLE
CM311-1S CH第二个USB口接移动硬盘后导致所有命令失效并报错：Input/output error

### ISSUE THREAD

**Issue by shanlanCoding** [ophub/amlogic-s9xxx-armbian#1455]
**Device Information | 设备信息**
 - SOC: S905L3B
 - Model: CM311-1S CH 湖北移动

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.31
 - Release: Armbian 23.05.0-trunk Jammy with Linux 6.1.31-ophub

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

靠近网卡的USB口是U盘安装的armbian系统。第二个USB用来接外置移动硬盘，一旦连接上，bash控制台所有的命令就会报错`Input/output error`
但是部分U盘不会，且能挂载。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/44717382/831bd977-47fe-4071-81db-de47dbe81ffb)

像上面的`df -h`命令，在没有插入移动硬盘时候都是正常，插入后就报错了，`reboot`也都无法使用。Linux系统中一切都是文件，我个人判断是不是系统从新的存储设备来执行命令了？但是新系统又没有系统文件，所以导致`Input/output error `。U盘能识别是我U盘里写入了文件。

**Comment by shanlanCoding** [comment]
这个问题为啥关闭了呀？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年6月4日(周日) 晚上6:47
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1S CH第二个USB口接移动硬盘后导致所有命令失效并报错：Input/output error (Issue #1455)




 
Closed #1455 as completed.

**Comment by ophub** [comment]
给魔百和的2个USB口插了2个外接硬盘，一会就冒烟了，盒子都报废了回答也没啥用了。

USB口插着设备时，系统会从USB启动，没有插设备时从EMMC启动，你插了2个外接设备，让他怎么启动，系统怎么工作？
