### ISSUE TITLE
TY1608 stable写入emmc无法找到IP，要换成flippy内核

### ISSUE THREAD

**Issue by w2xg2022** [ophub/amlogic-s9xxx-armbian#1457]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3] s905l3b
 - Model [e.g. HK1] TY1608

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] 5.15.112/5.15.114 stable
 - Release: [e.g. jammy/bullseye] bullseye

算是issue，但更多想表达如何避坑。
#1332 明明写到TY1608可以写入emmc，但测试了5.15.112/5.15.114 stable都无法成功，认真一看原来是flippy的内核。按照下面步骤操作后确定写入emmc可以正常运行：
1、下载bullseye_5.15.113版，https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.05/Armbian_23.05.0_amlogic_s905l3b_bullseye_5.15.113_server_2023.05.26.img.gz
2、Rufus写入U盘，U盘开机（用#1332的安卓9固件可以引导U盘开机）
3、armbian-update -u flippy -k 5.15.114
4、armbian-install，box id选122、filesystem选ext4

![搜狗截图20230603162651](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/bfd0303c-4b61-403a-8549-eec90118d6ec)

**Comment by ophub** [comment]
理论上stable/flippy/dev这3个都可以，你不能写入提示的什么？

**Comment by w2xg2022** [comment]
应该说stable可以写入emmc，但是因为没有HDMI输出，而且始终找不到对应的IP。
但flippy写入emmc后可以顺利找到IP。

**Comment by ophub** [comment]
ip 可以到接入的路由器里找到名称叫 armbian 的设备，这是他的ip，可以ssh连接。

你的意思是 flippy 内核有 hdmi 显示？

**Comment by w2xg2022** [comment]
1、stable可以写入emmc，路由器找不到设备IP；HDMI无法显示。
2、flippy可以写入emmc，路由器可以找到设备IP，可以SSH连接；HDMI无法显示。

**Comment by ophub** [comment]
好的

**Comment by dushoufoxin** [comment]
大佬能不能给小弟们详细写一份关于TY1608刷openwrt的教程。看着你们的评论感觉丈二和尚摸不着头脑。

**Comment by w2xg2022** [comment]
编译了flippy内核的固件，方便直接写入emmc能正常运行。可以参考：https://github.com/w2xg2022/actions4ty1608
