### ISSUE TITLE
s905l2-e900v21e如何从u盘启动啊

### ISSUE THREAD

**Issue by 1984admin** [ophub/amlogic-s9xxx-armbian#1467]
系统密码不是0，0000 9999 8888 1234 123123 10086这些都试过了，也不对。
av口里面是空的，无法捅。
插入开机，无法从u盘启动。
有用这个机器的吗？
如何从u盘启动啊？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

12.4
