### ISSUE TITLE
H618 allwinner chipset supported

### ISSUE THREAD

**Issue by sunilsankar** [ophub/amlogic-s9xxx-armbian#1469]
**Device Information | 设备信息**
 - SOC: [H618]
 - Model [Allwinner]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
Is allwinner H618 supported I see only H616 here can I try this 
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
not support

**Comment by Victorhtf** [comment]
Still not support? I'm needing.

**Comment by Gabrielxzx** [comment]
> Still not support? I'm needing.

Still not support?

**Comment by Blue-Mink** [comment]
我找到了这个https://github.com/warpme/miniarch，不知道对你的适配有没有帮助？ @ophub

**Comment by Blue-Mink** [comment]
@ophub 我找到了这个https://github.com/warpme/miniarch
不知道对你的适配有没有帮助？
