### ISSUE TITLE
Build buster

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#147]
Hello.
I could also compile the buster version to
amlogic armbian?

**Comment by ophub** [comment]
![Snip20220311_1](https://user-images.githubusercontent.com/68696949/157708540-7da8ba8e-28b5-4a62-9bb3-b4dfb932a68f.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_buster_03.11.0352
