### ISSUE TITLE
23.02.0一直升不上去

### ISSUE THREAD

**Issue by aliyy2021** [ophub/amlogic-s9xxx-armbian#1470]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/77948441/eeae0bce-8673-4e5c-b810-0a0cb5533b27)
大佬，这个版本怎么一直是23.02，最新不是23.08了？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/65dda18f2b33f8b50e65510b2429bd4e92b44caa/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L68-L76

这里我有说明，锁定了。这个执行是在系统初次启动时完成的初始化操作中的一个操作。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/65dda18f2b33f8b50e65510b2429bd4e92b44caa/rebuild#L994-L996

你解锁了升级

**Comment by aliyy2021** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/65dda18f2b33f8b50e65510b2429bd4e92b44caa/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L57-L76
> 
> 这里我有说明，锁定了。这个执行是在系统初次启动时完成的初始化操作中的一个操作。
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/65dda18f2b33f8b50e65510b2429bd4e92b44caa/rebuild#L994-L996
> 
> 你解锁了升级。由于会生成和写入新的u-boot，可能会砖了。 其实你可以忽略这个数字，因为除了数字没变，其他的包都是最新的。 我hold住的这几个包都是不适合的
> 
> ```
> dpkg --get-selections | grep 'hold'
> 
> armbian-bsp-cli-odroidn2                        hold
> initramfs-tools                                 hold
> initramfs-tools-core                            hold
> u-boot-tools                                    hold
> ```

谢大佬，明白了
