### ISSUE TITLE
在armbian基础上寻找centos-aarch64版本
可是最后引导失败，严重翻车😂😂😂😂

### ISSUE THREAD

**Issue by Alvin1986** [ophub/amlogic-s9xxx-armbian#1472]
请求大佬研究一番
链接：https://pan.baidu.com/s/1Bv1pkaO0iTQD1rvY3VU9uQ?pwd=hmzz 
提取码：hmzz

**Comment by a520ass** [comment]
内核能跑，rootfs都差不多，我这个alma linux就是红帽系的
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8427401/c2c3b7b0-9b44-49eb-8623-7bb38600a7ff)

**Comment by Alvin1986** [comment]
没有成功过。。。。你是帷幕还是直接刷进去的

**Comment by a520ass** [comment]
> 没有成功过。。。。你是qemu还是直接刷进去的

肯定是直接刷啊，qemu有什么意义

**Comment by Alvin1986** [comment]
> > 没有成功过。。。。你是qemu还是直接刷进去的
> 
> 肯定是直接刷啊，qemu有什么意义

有教程和包吗？发个链接，我研究一下。s905l3a的芯片

**Comment by Alvin1986** [comment]
> > > 没有成功过。。。。你是qemu还是直接刷进去的
> > 
> > 肯定是直接刷啊，qemu有什么意义
> 
> 有教程和包吗？发个链接，我研究一下。s905l3a的芯片
 有成品包直接能刷就更好了。。。。

**Comment by a520ass** [comment]
没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了

**Comment by Alvin1986** [comment]
> 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了

就是不会。。。。会弄我早弄好了😭

**Comment by Alvin1986** [comment]
> 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了

安装成功了，neofetch这个装不上去。这个要怎么装在盒子里。。。

**Comment by a520ass** [comment]
> > 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了
> 
> 安装成功了，neofetch这个装不上去。这个要怎么装在盒子里。。。

直接下载再运行就可以了
![QQ截图20230417094916](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8427401/431a5dc6-54a5-492f-9cc0-ffbddc3e6286)

**Comment by Alvin1986** [comment]
> > > 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了
> > 
> > 安装成功了，neofetch这个装不上去。这个要怎么装在盒子里。。。
> 
> 直接下载再运行就可以了
> ![QQ截图20230417094916](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8427401/431a5dc6-54a5-492f-9cc0-ffbddc3e6286)
> 

![mmexport1686805259398.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/125835237/8c7f8eea-1361-42cf-a1ea-7f2891261952)

搞定了，centos，双网卡，第二张网卡静态IP既然不成功？新建的配置都不行。这是什么鬼

**Comment by Alvin1986** [comment]
> > > 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了
> > 
> > 安装成功了，neofetch这个装不上去。这个要怎么装在盒子里。。。
> 
> 直接下载再运行就可以了
> ![QQ截图20230417094916](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8427401/431a5dc6-54a5-492f-9cc0-ffbddc3e6286)
> 

有偿求购一款官版的centos系统 你能搞不大佬？

**Comment by Alvin1986** [comment]
> 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了

有偿求购一款官版的centos系统刷机包能搞吗？

**Comment by a520ass** [comment]
> > 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了
> 
> 有偿求购一款官版的centos系统刷机包能搞吗？

不做技术支持，可以告诉你思路，先说下你的设备是什么

**Comment by Alvin1986** [comment]
> > > 没教程，弄这个都差不多。最重要的，你需要先弄好主线u-boot，就不会有各种奇奇怪怪的问题了
> > 
> > 有偿求购一款官版的centos系统刷机包能搞吗？
> 
> 不做技术支持，可以告诉你思路，先说下你的设备是什么

已经弄好了，谢谢

**Comment by Alvin1986** [comment]
大佬能否把宝塔的www的相关文件在刷写的时候可以一共刷过去。每一次装宝塔环境要5-6个小时。相当可怕。或者您可以教一下如何可以改armbian-install相关把新建文件夹同步过去的方法吗？
