### ISSUE TITLE
大佬armbian镜像文件名里面这些是啥意思

### ISSUE THREAD

**Issue by sehczaa** [ophub/amlogic-s9xxx-armbian#1473]
新手小白，不太明白这些有啥区别，希望大佬解答一下   jammy  bullseye  luna  bookworm

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by ophub** [comment]
镜像的代号。armbian有2个系列，一个是ubuntu系列的，一个是debian系列的。
ubuntu系列有2个，jammy是2022年发布的，lunar是2023年发布的。
debian系列有2个，bullseye是2021年发布的，bookworm预报是本月的明天发布的。
ubuntu系列的特点是软件包更新速度快，求新。
debian系列的特点是软件包要千锤百炼，求稳。

**Comment by sehczaa** [comment]
> 镜像的代号。armbian有2个系列，一个是ubuntu系列的，一个是debian系列的。
> ubuntu系列有2个，jammy是2022年发布的，lunar是2023年发布的。
> debian系列有2个，bullseye是2021年发布的，bookworm预报是本月的明天发布正式版（现在属于beta版）。
> ubuntu系列的特点是软件包更新速度快，求新。
> debian系列的特点是软件包要千锤百炼，求稳。

好的，多谢大佬指点

**Comment by lengz0** [comment]
我也有一个问题，比如[amlogic-s9xxx-armbian的固件，会有一个6.1.32和5.15.115 这两个有什么区别呢？

**Comment by sehczaa** [comment]
> 我也有一个问题，比如[amlogic-s9xxx-armbian的固件，会有一个6.1.32和5.15.115 这两个有什么区别呢？
> 
> 

内核版本不同

**Comment by lengz0** [comment]
> > 我也有一个问题，比如[amlogic-s9xxx-armbian的固件，会有一个6.1.32和5.15.115 这两个有什么区别呢？
> 
> 内核版本不同

感谢回复，我刚接触这个不久，打算用CM311盒子做homeassistant使用
请教下这两个版本的内核，哪一个更适合一些呢？

**Comment by sehczaa** [comment]
> > > 我也有一个问题，比如[amlogic-s9xxx-armbian的固件，会有一个6.1.32和5.15.115 这两个有什么区别呢？
> 
> > 
> 
> > 内核版本不同
> 
> 
> 
> 感谢回复，我刚接触这个不久，打算用CM311盒子做homeassistant使用
> 
> 请教下这两个版本的内核，哪一个更适合一些呢？

都行吧应该  我用的6.x版本的也挺稳定的

**Comment by lengz0** [comment]
> > > > 我也有一个问题，比如[amlogic-s9xxx-armbian的固件，会有一个6.1.32和5.15.115 这两个有什么区别呢？
> > 
> > 
> > > 
> > 
> > 
> > > 内核版本不同
> > 
> > 
> > 感谢回复，我刚接触这个不久，打算用CM311盒子做homeassistant使用
> > 请教下这两个版本的内核，哪一个更适合一些呢？
> 
> 都行吧应该 我用的6.x版本的也挺稳定的

那我也用6.x的试试，万分感谢

**Comment by qq410252889** [comment]
不同的版本名称
Debian 11        Bullseye
Debian 12        Bookworm       
Ubuntu 22.04 LTS Jammy Jellyfish
Ubuntu 24.04 LTS Noble Numbat
