### ISSUE TITLE
Feature request upgrade to bookworm

### ISSUE THREAD

**Issue by sharicov** [ophub/amlogic-s9xxx-armbian#1477]
How can I upgrade bullseye to bookworm without reinstalling from scratch?

**Comment by ophub** [comment]
https://www.cyberciti.biz/faq/update-upgrade-debian-11-to-debian-12-bookworm/

You can try upgrading according to the version upgrade instructions for Debian, and first backup using ddbr.
I haven't tested this upgrade process yet.

**Comment by sej7278** [comment]
yes i've got it in my notes that i had previously upgraded from buster to bullseye using the regular debian method:

https://www.debian.org/releases/bookworm/amd64/release-notes/ch-upgrading.en.html

had to check config changes of course, and cloned the sdcard using DD beforehand.

**Comment by ophub** [comment]
> Is kernel update to 6.1 is planned anytime soon?

`armbian-update -k 6.1.33`

**Comment by sharicov** [comment]
Huge thanks, worked like a charm, from now and on can I use `armbian-update -b no` without specifying kernel version, just as I did before?

**Comment by ophub** [comment]
yes, you can

**Comment by sharicov** [comment]
Thanks

**Comment by ophub** [comment]
I also upgraded just now, I refer to the above article, the method used is as follows:

```
# 01. Backup the current system
armbian-ddbr
select: b

# 02. Update existing packages and reboot the Debian 11 system
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get --purge  autoremove -y
sudo apt-get autoclean -y
sync
reboot

# 03. Replace Debian 12 source list
cp /etc/apt/sources.list /etc/apt/sources.list.bak
sed -i s'|bullseye|bookworm|'g /etc/apt/sources.list

# 04. Upgrade Debian 11 to Debian 12 Bookworm
sudo apt update
sudo apt upgrade -y --without-new-pkgs
sudo apt full-upgrade -y
sync
reboot
```

**Comment by sharicov** [comment]
Based on the manual you shared previously there was` sudo apt upgrade --without-new-pkgs `and `sudo apt full-upgrade`
Also in between somehow my dns setting got lost so I had to add it manually in the /etc/resolv.conf
And then, finally after reboot I had to add non-free-firmware to /etc/apt/sources.list , since this is a new component in the booksworm

**Comment by sharicov** [comment]
You right, probably did a wrong choise
