### ISSUE TITLE
Feature Request: minimal image

### ISSUE THREAD

**Issue by irfanjunaid** [ophub/amlogic-s9xxx-armbian#1478]
Hello @ophub ! It would be great if there is minimal image version like from the official releases. For example: https://redirect.armbian.com/bananapim5/archive 

Right now the image size is about 750 MB compressed and expands to 2.75 GB after extracting. The Jammy minimal image is only 212 MB in size and easy to download. This way users can start fresh and can install only what they need. Please consider this option.

**Comment by ophub** [comment]
One month ago, there was this option, but I checked the API and hardly anyone was downloading this image, so I deleted it. If you need it, you can set: `BUILD_MINIMAL=yes`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/0deeb71dd16e48eefc90be2ee5e2eef55edbcdbf/.github/workflows/build-armbian.yml#LL225C92-L225C108

**Comment by irfanjunaid** [comment]
Wow, didn't know of this but very nice! 🙂  

> hardly anyone was downloading this image

I guess folks don't know of this yet. Thanks @ophub  👍

**Comment by muava12** [comment]
i very noob on building the image. can anyone help to upload built minimal image armbian jammy for s950x ?
