### ISSUE TITLE
更新请求:在armbian-software中添加软件

### ISSUE THREAD

**Issue by l1991l** [ophub/amlogic-s9xxx-armbian#1479]
中文:
希望O大可以添加以下软件
1.AdguardHome
https://github.com/AdguardTeam/AdGuardHome
不要用docker安装，可以用官方安装脚本，谢谢！！
2.AI-Bing 
(Example :https://bing.vcanbb.top/)
https://github.com/adams549659584/go-proxy-bingai
这个推荐用docker,Release要自己写脚本。(ง •̀_•́)ง加油

English:
Hope O big can add the following software
1.AdguardHome
https://github.com/AdguardTeam/AdGuardHome
Do not install with docker, you can use the official installation script, thank you!!
2.AI-Bing
(Example :https://bing-vercel.vcanbb.top/)
https://github.com/adams549659584/go-proxy-bingai
This recommendation is to use docker,Release and write your own script. (ง •̀_•́)งCome on

**Comment by ophub** [comment]
测试了一上午，一个也没搞定。
new bing是安装完了，一直转圈圈没有进入使用界面。
adg是一直和53端口占用，按照官方的教程折腾了半天没搞定。我日常使用这个是在docker里跑的，只用了广告过滤功能，dhcp我不会使用，没整明白

**Comment by l1991l** [comment]
adg53占用是因为systemd-resolved占用了53端口
可以用以下命令来关闭
```
systemctl stop    systemd-resolved
systemctl disable systemd-resolved
systemctl mask    systemd-resolved
```
