### ISSUE TITLE
dtb  meson-sm1-sei610.dtb

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#148]
For my box, the dtb is "meson-sm1-sei610.dtb" how can I select it because it doesn't appear in the list when I install

**Comment by ophub** [comment]
/usr/sbin/armbian-install

https://github.com/ophub/amlogic-s9xxx-armbian/blob/12e44996072f6a2facd8eff8dca2be1ba4ba5db1/build-armbian/common-files/files/usr/sbin/armbian-install#L120

You can copy a line and modify it yourself.
Learn about system recovery scenarios before trying different scenarios to avoid writing unusable.


https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#108-how-to-recover-if-the-install-fails-and-cannot-be-started
