### ISSUE TITLE
X96 (1+8GB) Works

### ISSUE THREAD

**Issue by Drafteed** [ophub/amlogic-s9xxx-armbian#1480]
Hello!
Huge thanks for your work!

Just a report of that my old box X96 works well on `5.15.116` kernel with `meson-gxl-s905x-p212.dtb`. The system was successfully installed in eMMC just by `armbian-install`.

Used [local build](https://github.com/ophub/amlogic-s9xxx-armbian#local-build-instructions):
```sh
./rebuild -b s905x -k 5.15.116
```
[Public builds](https://github.com/ophub/amlogic-s9xxx-armbian/releases) have not been tested.

WiFi seems is not work, BT is not provided by box, LAN 100mb is ok.

Kernel versions `5.10.183` and `6.1.33` do not start and the box goes into the bootloop.

**Some details:**

Amlogic S905X
Board: Q5X V2.1 16483
RAM: 1 GB
ROM: 8 GB
Wireless: RTL8189ETV
BT: N/A
LAN: 100mb

<img width="400" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/11841379/db0e2eff-04c2-493f-8a0d-a96157d89b58"><img  width="400" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/11841379/de6c6176-8a5f-4fc4-ac95-d15f3fbfb163">

**Comment by ophub** [comment]
`sudo ./rebuild -b s905x-t95 -k 5.15.116_6.1.33`

You can try the result of s905x-t95 again, the dtb of this one is the same, but it uses a different u-boot, maybe you can use the 6.1.y kernel

**Comment by Drafteed** [comment]
> `sudo ./rebuild -b s905x-t95 -k 5.15.116_6.1.33`
> 
> You can try the result of s905x-t95 again, the dtb of this one is the same, but it uses a different u-boot, maybe you can use the 6.1.y kernel

Yes, succefully running `6.1.33` 👍.

**Comment by ophub** [comment]
Ok, thank you for sharing, I will add this device to the support list

**Comment by bt4ibwem8** [comment]
I have the same box, but 2+16GB version. Should i use `Armbian_24.11.0_amlogic_s905x-t95_bookworm_6.6.48_server_2024.09.01.img.gz` or `Armbian_24.11.0_amlogic_s905x_bookworm_6.6.48_server_2024.09.01.img.gz` ?

**Comment by ophub** [comment]
use s905x-t95

**Comment by Hx0531** [comment]
> use s905x-t95

o大 有没有s905x的 安卓底包。

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools
大家分享的可以安卓系统，我都在这里转存了一份。

**Comment by Hx0531** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 大家分享的可以安卓系统，我都在这里转存了一份。

收到，O大！

**Comment by h946116782** [comment]
WiFi does not work, how to solve it, the chip is RTL8189ETV

**Comment by tarasian666** [comment]
I have same looking box but 2+16 version. With regular s905x latest image bootloader doesn't work from emmc but from usb/sd does. With s905x-t95 latest image bootloader works from emmc but cannot see mmc device on slot 2.

**Comment by ChouaibKhamallah** [comment]
Hello,

I want to share my successful experience compiling and loading the driver from this repo for the built-in Wi-Fi card (RTL8189ETV/FS) on an Amlogic S905X (X96 TV Box, Q5X v2.1).
This may help others with similar hardware!

armbian image
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2025.06/Armbian_25.08.0_amlogic_s905x-t95_jammy_6.12.31_server_2025.06.01.img.gz

---

### **1. Toolchain**

I used the latest ARM GNU toolchain (14.2.rel1, aarch64):

```sh
wget https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-aarch64-aarch64-none-linux-gnu.tar.xz
sudo tar -xvf arm-gnu-toolchain-14.2.rel1-aarch64-aarch64-none-linux-gnu.tar.xz -C /opt

export PATH=/opt/arm-gnu-toolchain-14.2.rel1-aarch64-aarch64-none-linux-gnu/bin:$PATH
export CROSS_COMPILE=aarch64-none-linux-gnu-
export CC=${CROSS_COMPILE}gcc
```

---

### **2. Source repository**

Driver sources were downloaded from
```sh
git clone https://github.com/jwrdegoede/rtl8189ES_linux
cd rtl8189ES_linux
```

---


### **3. Compilation**

Make sure your kernel headers are installed at `/lib/modules/$(uname -r)/build`:

```sh
make ARCH=arm64 KSRC=/lib/modules/$(uname -r)/build
```

---

### **4. Installation**

Copy the generated module to the appropriate directory:

```sh
sudo cp 8189es.ko /lib/modules/$(uname -r)/kernel/drivers/net/wireless/
sudo depmod -a
sudo modprobe 8189es
```

---

### **5. Result**

* The module loads and detects the Wi-Fi interface (wlan0).
* Works perfectly on my S905X-based X96 TV box, Wi-Fi connection stable after reboot.

---

Thank you for maintaining this repo.
If anyone has trouble on S905X/8189ETV boards, this workflow worked for me!

**— Chouaïb**

**Comment by ophub** [comment]
Thanks for sharing, very detailed.

**Comment by PipingCode** [comment]
请问O大，比特米盒CumeBox2可以选择参照哪个型号？
