### ISSUE TITLE
求魔百盒M411A刷机包？能成功U盘启动armbian的朋友请指教一下谢谢

### ISSUE THREAD

**Issue by t9080** [ophub/amlogic-s9xxx-armbian#1482]
配置是2+8的，刷了好多个都不能启动U盘

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49359882/1e3b638d-0c50-4bea-907b-1789b2a65820)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49359882/43c49f5a-f440-44d1-ba4c-470ddd0f3ed0)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49359882/c7633343-4147-4a0d-8629-6a1e184c91d6)

**Comment by ophub** [comment]
试试 s905l3
[android_tv_m401a_s905l3.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_s905l3.tar.xz)

**Comment by t9080** [comment]
谢谢，这个能刷进去，现在做个armbian盘试试能不能启动先

**Comment by t9080** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49359882/43708a0f-af8a-4a4a-b1ab-b29cf1ade426)

U盘启动后黑屏，插网线路由灯也不亮，也不知道是不是启动成功

**Comment by t9080** [comment]
> 刷成功了吗？

还没功成，换了好几个dtb也不行

**Comment by t9080** [comment]
> 试试 s905l3
> 
> [android_tv_m401a_s905l3.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_s905l3.tar.xz)

这个安卓包可以，但是U盘启动Armbian不行

**Comment by gqxk** [comment]
> > 试试 s905l3
> > [android_tv_m401a_s905l3.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_s905l3.tar.xz)
> 
> 这个安卓包可以，但是U盘启动Armbian不行

最后成功没

**Comment by kKXAXG7Ryx1** [comment]
同问

**Comment by robot-bear** [comment]
启动应该是成功了，是网卡没有加载获取不到  ip，我也有这个问题。我是接ttl看到的。hdmi是黑屏的，单串口显示系统正常起来了只是获取不到ip

**Comment by AQR0124** [comment]
成功了吗？经过尝试，我新魔百盒m411a，s905l3刷s905l3和s905l3-cm211这两个都无法进入系统

**Comment by AQR0124** [comment]
经过尝试，刷入5.15.100与5.15.110均可以正常U盘启动，但没有wifi功能，尝试使用5.15.155以上的内核则无法启动
