### ISSUE TITLE
L1-PRO 我家云6.1内核的固件都刷不进去，求助！

### ISSUE THREAD

**Issue by Yxini** [ophub/amlogic-s9xxx-armbian#1484]
**Device Information | 设备信息:L1-PRO 我家云
 - SOC: RK3328
 - Model ：L1-PRO

**Armbian Version | 系统版本**：23.08.0
 - Kernel Version: 6.1系列内核
 - Release:  jammy/bullseye 

**Describe the bug | 问题描述**
发现没法刷入6.1内核的固件，尝试了好几次。刷入后不会开机引导。

**Comment by Yxini** [comment]
确定了，确实是最新的内核没法启动，我用找了一下以前的固件。现在可以启动了。
可以开机的固件：Armbian_23.02.0_rockchip_l1pro_bullseye_6.1.14_server_2023.02.28.img

**Comment by Yxini** [comment]
好的，我来尝试一下

**Comment by Yxini** [comment]
我家云是rk系列的，不能USB只能刷入到emmc

**Comment by ophub** [comment]
![Snip20230616_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/8eac0c16-fcd8-4404-824f-ad27bf78f812)

我在vplus上刚才测试也是无法启动最新的固件，我下载了5月的，启动后更新到最新内核可以启动。

**Comment by ophub** [comment]
现在releases里最新是6.1.33的，你下载6.1.32或者31等前面一个版本看看。我刚才更新29-30-31-34都没问题，我现在把32-33也测试下

**Comment by Yxini** [comment]
6.1.33、32、31 这几个我都试了。均无法启动。
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/984e44c8-3ea2-4621-b1c5-68744bc5b2b5)

**Comment by Yxini** [comment]
armbian-sync
armbian-update -u stable -k 6.1.34

等我测试一下这个，我现在路由器在开科学，要等一下。

**Comment by ophub** [comment]
我从6.1.34更新到6.1.32挂了

**Comment by Yxini** [comment]
如何免科学更新呀，我平时都是用Windows上科学

**Comment by ophub** [comment]
你手动下载，解压出6个内核文件: https://github.com/ophub/kernel/releases/tag/kernel_stable

然后放在某个目录下，例如
```
cd /root
mkdir kernel
cd kernel
tar -xzf 6.1.34.tar.gz
cd 6.1.34
armbian-update
```

**Comment by Yxini** [comment]
好，我尝试一下

**Comment by ophub** [comment]
我挨着更新了一遍，都能用，如果不是内核的问题，难道是最新的镜像发生什么改变了？

![Snip20230616_4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/5db208bc-4cbb-4327-9b56-dead8579826e)
![Snip20230616_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/9176a24c-4bab-4078-839f-61e233cefa88)
![Snip20230616_5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/dfe25281-b14f-4d20-acad-a22cd3c5aaa3)
![Snip20230616_6](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/11f56d49-df15-49a4-916c-59323b76b5b9)

**Comment by Yxini** [comment]
一开始，我尝试了33、32、31的固件。连续的固件都刷不进去，我当时的判断就是内核有问题。后面我找了我2月份成功刷入的固件，重新刷入发现能刷入。现在看来应该不是内核的问题，应该是固件的问题。
现在我刷入了6.1.34内核，确实没问题。
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/51f8294c-863c-49d5-8403-05acae406ab3)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/5285741276

我刚才用之前的底包，打包了6.1.34测试了下vplus也可以正常启动。
我今天都重新打包一版最新的吧。
![Snip20230616_7](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/1e32ebb3-cef6-4a28-a123-c685fba1d771)

**Comment by Yxini** [comment]
好，等出来了。我试一下能不能启动

**Comment by ophub** [comment]
好的，编译一次要2个小时，等1点半以后再试试最新版看看能不能正常启动。

**Comment by Yxini** [comment]
好的，到时候我反馈

**Comment by Yxini** [comment]
看到固件了，现在开始下载，等刷入开机反馈。

**Comment by Yxini** [comment]
刷入成功！
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/2ed05e7e-33f3-4fa1-ab9b-2b3b73b73cfd)

**Comment by ophub** [comment]
好的

**Comment by Yxini** [comment]
感谢O大！

**Comment by ophub** [comment]
我测试了也没问题

![Snip20230616_8](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/1f50bad7-ea9e-4dbd-9831-5e587ca42dfc)

**Comment by Yxini** [comment]
很NICE！

**Comment by aladingg** [comment]
这个问题似乎又出现了，我的是联想粒子云SS1，我刷了23.0的6.1.42/6.1.44的buster/jammy共4个release，都无法启动。

**Comment by maxmib** [comment]
@ophub bookworm 6.1.46同样问题

**Comment by ophub** [comment]
测试了vplus没问题

**Comment by liubin7913** [comment]
我刷了6.1.46的四个不同版本都开不了机，历史版本在哪里下载？谢谢！

**Comment by ophub** [comment]
没有历史版本，只有这个月的

**Comment by liubin7913** [comment]
请教，是固件问题还是我刷机的问题？我电脑里保存的Armbian_22.05.0-trunk_Chainedbox-wind_buster_current_5.15.32.img，我按正常流程刷机，可以启动。我可以在这个版本的基础上升级吗？谢谢！

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年8月24日 19:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] L1-PRO 我家云6.1内核的固件都刷不进去，求助！ (Issue #1484)


没有历史版本，只有这个月的

―

**Comment by ophub** [comment]
软件包正常apt即可更新到最新

**Comment by liubin7913** [comment]
强制更新后就不能正常启动了，我需要修改什么？谢谢

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年8月24日 19:23
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] L1-PRO 我家云6.1内核的固件都刷不进去，求助！ (Issue #1484)


软件包正常apt即可更新到最新

―

**Comment by ophub** [comment]
不了解你的固件，去下载的地方看看使用说明

**Comment by liubin7913** [comment]
刷Armbian_23.08.0_rockchip_l1pro_bullseye_6.1.42_server_2023.08.01.img后，前置面板灯不亮，电源键无反应，网卡只有黄灯闪烁，主板上一只蓝灯常亮，一只慢闪，拆壳接HDMI无输出

**Comment by liubin7913** [comment]
刷F大的openwrt_rk3328_l1pro_R23.08.18_k6.1.46-flippy-84+成功了，求可用的armbian

**Comment by liubin7913** [comment]
我家云以后直接可以用rufus刷u盘测试了，能刷机正常启动的固件，刷u盘插usb2.0接口也能正常引导进系统，目前测试Armbian_22.05.0-trunk_Chainedbox-wind_buster_current_5.15.32.img和openwrt_rk3328_l1pro_R23.08.18_k6.1.46-flippy-84+.img都可以

**Comment by maxmib** [comment]
> 我家云以后直接可以用rufus刷u盘测试了，能刷机正常启动的固件，刷u盘插usb2.0接口也能正常引导进系统，目前测试Armbian_22.05.0-trunk_Chainedbox-wind_buster_current_5.15.32.img和openwrt_rk3328_l1pro_R23.08.18_k6.1.46-flippy-84+.img都可以

你刷的时候机子里有没有接硬盘，看其他issue有人说接了硬盘启动不了

**Comment by liubin7913** [comment]
接了，希捷2T的硬盘。我没硬改过，U盘引导开机要等几十秒后才有反应

**Comment by maxmib** [comment]
> 接了，希捷2T的硬盘。我没硬改过，U盘引导开机要等几十秒后才有反应

我刷最新的Bookworm的镜像，机子反复重启，感觉是没有从emmc启动，有可能从sata口接的硬盘启动了

**Comment by maxmib** [comment]
> 你的硬改过没？我刷四位大大的最新版都不能进系统，用U盘引导，路由里能查到分配IP了，但无法连接。直接刷机从emmc根本无法启动

没改过，可以断开内置硬盘，刷到emmc启动试试

**Comment by liubin7913** [comment]
已经刷好了，我上去断开硬盘试试

**Comment by liubin7913** [comment]
接硬盘和不接硬盘反应相同，网卡只是黄灯闪，绿灯不亮，没有获取到IP

**Comment by maxmib** [comment]
> 接硬盘和不接硬盘反应相同，网卡只是黄灯闪，绿灯不亮，没有获取到IP

我的也是这样，只能刷其他固件了

**Comment by LIUBANGJIAN** [comment]
有6.1.82内核的版本吗？
