### ISSUE TITLE
一段时间后，ssh就无法连接

### ISSUE THREAD

**Issue by iJayscn** [ophub/amlogic-s9xxx-armbian#1489]
**Device Information | 设备信息**
 - SOC: S905D
 - Model：N1

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.115
 - Release: Armbian_23.08.0_amlogic_s905d_bullseye_5.15.115_server_2023.06.05.img

**Describe the bug | 问题描述**

ssh服务经常过1-2天就无法连接
ping 正常
docker 服务正常，ha+mqtt+nodered
docker op 正常，op的ssh也正常。

就是armbian 的ssh，不能连接，只能重启才行

请问这个问题是什么原因导致的？如何解决，或者如何配合排查

是不是只有定时重启？谢谢

> /etc/init.d/ssh restart 2>/dev/null

Issue搜了下有几位朋友也有这个问题。

https://github.com/ophub/amlogic-s9xxx-armbian/issues/1114
https://github.com/ophub/amlogic-s9xxx-armbian/issues/794

**Comment by golden777** [comment]
同样问题, CT2000
在有键盘和显示器的情况下,登陆进去后
service ssh restart
重新启动ssh服务就能连接ssh
但是通常不方便用显示器和键盘

**Comment by ophub** [comment]
```
armbian-sync
armbian-fix
```

**Comment by iJayscn** [comment]
> ```
> armbian-sync
> armbian-fix
> ```
怀疑可能与权限相关
两台N1都发现了这个情况
先修复权限，观察一下！

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/discussions/1476

新版空闲时间会挂起，你用上面的两个命令可以调回原方案

**Comment by iJayscn** [comment]
> #1476
> 
> 新版空闲时间会挂起，你用上面的两个命令可以调回原方案

好的
