### ISSUE TITLE
is it possible to use Amlogic USB Burning Tool

### ISSUE THREAD

**Issue by psittaciform** [ophub/amlogic-s9xxx-armbian#149]
Is there a way to compile this code into an image that usb burning tool can recognize and burn?

**Comment by ophub** [comment]
Choose the corresponding firmware according to your box. Then write the IMG file to the USB hard disk through software such as [Rufus](https://rufus.ie/) or [balenaEtcher](https://www.balena.io/etcher/). Insert the USB hard disk into the box. Common for all Amlogic s9xxx tv box.

**Comment by psittaciform** [comment]
Yes, I've been able to install via that method.  My question is about Amlogic USB burning tool and if there is a way to compile an image for that tool instead.  I would like to order x96 max+ devices from a manufacturer preloaded with armbian and they need an image that can be loaded from USB burning tool.
