### ISSUE TITLE
[S905D] Geniatech ATV598Max does not boot from SD or USB

### ISSUE THREAD

**Issue by dzastsed** [ophub/amlogic-s9xxx-armbian#1490]
like title says, cannot get it to boot armbian whatsoever, i hold reset button and plug in power, but it just boots ATV. tried all dtb files for 905d but no dice
device here: https://www.geniatech.com/product/atv598max/
i can hook up UART to read the boot log and control uboot. tried using usbboot but couldnt get it working
is there maybe some kind of alternative reset button or whatever? i could provide board pictures too if needed

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

look at 12.14

**Comment by dzastsed** [comment]
thanks this helped, but another issue rose: cannot get past this point 
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63074962/a5be49da-9afc-41f7-8c55-fb1b6ff8c860)
is this a dtb issue or something else?

**Comment by dzastsed** [comment]
ignore that, it was. booted up with meson-gxl-s905d-libretech-pc.dtb

**Comment by ophub** [comment]
Can the 6.1.y kernel be started? You can copy `/boot/u-boot-p201.bin` as u-boot.ext and u-boot.emmc test.

Share your welcome screen and configuration information

```
cat /boot/uEnv.txt
ls -l /boot/u-boot*
```

**Comment by dzastsed** [comment]
yeah, kernel 6.1.32 works, heres the welcome screen 
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63074962/a9b67011-e67c-43d2-b976-e5ab9d91f85a)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63074962/aeffa2fb-d706-49a8-90ff-dae963ce4754)
here is uenv - had to use mecool dtb as internet didnt work with libretech
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63074962/d9e9dc8c-4f96-48fb-ba91-3288dfa6ba63)
heres uboot dir
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63074962/af4d4697-7603-43f1-a96f-e5083f2357e0)

**Comment by ophub** [comment]
Are you using a `dev` series kernel? Please check your configuration file:
`cat /etc/ophub-release`

Are you currently using it in `USB` mode or has it been written into the `eMMC`?

Please perform a test on the USB:
```
cd /boot
cp -f u-boot-p201.bin u-boot.ext
chmod +x u-boot.ext
sync
reboot
```

If you can successfully boot from USB, then update the kernel as follows:
`armbian-update -u stable -k 5.10.117`

**Comment by dzastsed** [comment]
hi, sorry for late reply.
yes, it seems that this is dev series kernel: 
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63074962/1f065d41-1919-46b1-b939-9b850ca1b8d3)
and yes, using USB mode, eMMC installation is not supported on amlogic devices, right? 


anyway, the uboot swap thing bricks the installation. black screen when booting
