### ISSUE TITLE
N1 Armbian 5.77升级系统是否需要重刷？

### ISSUE THREAD

**Issue by Java2Boy** [ophub/amlogic-s9xxx-armbian#1491]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. N1]

**Armbian Version | 系统版本**
 - Kernel Version: Linux aml 5.0.2-aml-s905 #5.77
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**

系统为论坛推荐版 5.77,一直Armbian+Docker+OP使用，现在想升级最新版，是否需要重刷，或有无简单方法升级。

armbian-update命令无法使用，config 正常

**Comment by ophub** [comment]
重刷最简单

**Comment by Java2Boy** [comment]
感谢OP大佬的回复
试了下刷入新版Armbian_23.08.0_amlogic_s905d_bullseye_6.1.33_server_2023.06.12，无法启动系统，提示Missing modules (cat /proc/modules; ls /dev)
ALERT! UUID=******* does not exit . Dropping tu a shell ! (initramfs)

**Comment by ophub** [comment]
`armbian-install -m yes`

使用bootloader写入

**Comment by Java2Boy** [comment]
> 

我试试其他几个版本，现在6.1.33系统无法进入

**Comment by Java2Boy** [comment]
> armbian-install -m yes

rm: cannot remove '/root/.not_logged_in_yet': Read-only file system
root@armbian:~# armbian-install -m yes
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ yes ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
mkdir: cannot create directory ‘/ddbr’: Read-only file system
rm: cannot remove '/etc/machine-id': Read-only file system
rm: cannot remove '/var/lib/dbus/machine-id': Read-only file system
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------------
ID    SOC        MODEL                          DTB                                               
--------------------------------------------------------------------------------------
101   s905d      Phicomm-N1                     meson-gxl-s905d-phicomm-n1.dtb                    
102   s905d      Phicomm-N1(DMA-thresh)         meson-gxl-s905d-phicomm-n1-thresh.dtb             
103   s905d      MECOOL-KI-Pro                  meson-gxl-s905d-mecool-ki-pro.dtb                 
104   s905x      HG680P                         meson-gxl-s905x-p212.dtb                          
105   s905x      B860H                          meson-gxl-s905x-b860h.dtb                         
106   s905x      TX9                            meson-gxl-s905x-tx9.dtb                           
107   s905x      T95,XiaoMI-3S                  meson-gxl-s905x-p212.dtb                          
108   s905x      TBee                           meson-gxl-s905x-tbee.dtb                          
109   s905w      TX3-Mini                       meson-gxl-s905w-tx3-mini.dtb                      
110   s905w      W95                            meson-gxl-s905w-p281.dtb                          
--------------------------------------------------------------------------------------
111   s905w      X96-Mini                       meson-gxl-s905w-x96-mini.dtb                      
112   s905w      X96W,FunTV,MXQ-Pro-4K          meson-gxl-s905w-x96w.dtb                          
113   s905l2     MGV2000,MGV3000,M301A          meson-gxl-s905l2-x7-5g.dtb                        
114   s905l2     E900v21E                       meson-gxl-s905l2-x7-5g.dtb                        
115   s905l2     Wojia-TV-IPBS9505              meson-gxl-s905l2-ipbs9505.dtb                     
116   s905l3     CM311-1,HG680-LC,M401A         meson-gxl-s905l2-x7-5g.dtb                        
117   s905l3     UNT400G1                       meson-gxl-s905l2-x7-5g.dtb                        
118   s905l3     CM211-1                        meson-gxl-s905l3b-m302a.dtb                       
119   s905l3b    M302A,M304A,CM211-1,CM311-1    meson-gxl-s905l3b-m302a.dtb                       
120   s905l3b    E900V22E                       meson-gxl-s905l3b-e900v22e.dtb                    
--------------------------------------------------------------------------------------
121   s905l3b    E900V22D                       meson-gxl-s905l2-x7-5g.dtb                        
122   s905l3b    IP103H,TY1608                  meson-gxl-s905l3b-m302a.dtb                       
123   s905lb     BesTV-R3300L,SumaVision-Q7     meson-gxl-s905x-p212.dtb                          
124   s905lb     Q96-mini                       meson-gxl-s905x-p212.dtb                          
0     Other      Customize                      Enter-custom-dtb-name                             
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 101
[ INFO ] Input Box ID: [ 101 ]
[ INFO ] FDTFILE: [ meson-gxl-s905d-phicomm-n1.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [ u-boot-2015-phicomm-n1.bin ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-n1.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root? 
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
dd: failed to open '/usr/lib/u-boot/mybox-bootloader.img': Read-only file system
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader.img ] failed.

**Comment by Java2Boy** [comment]
> `armbian-install -m yes`
> 
> 使用bootloader写入

USB_Burning_Tool再来一遍？

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

下载： [android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz)

**Comment by Java2Boy** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 下载： [android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz)

需要还原成ANDROID TV再用USB_Burning_Tool再来一次？以为已经是Armbian 直接SSH Armbian-install 就好了，看来是我想简单了

**Comment by ophub** [comment]
我不知道你使用的这个5.77写入了安卓分区的哪些区域，最好的办法是恢复安卓系统，修复分区。然后重新写入armbian

**Comment by Java2Boy** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 下载： [android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz)

USB Burning Tools 刷入[android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_phicomm_n1_mod_by_webpad_v2.2.tar.xz), Adb U盘启动后，依然提示

[ OPTIONS ] Please Input ID: 101
[ INFO ] Input Box ID: [ 101 ]
[ INFO ] FDTFILE: [ meson-gxl-s905d-phicomm-n1.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [ u-boot-2015-phicomm-n1.bin ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-n1.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root? 
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
dd: failed to open '/usr/lib/u-boot/mybox-bootloader.img': Read-only file system
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader.img ] failed.

**Comment by Java2Boy** [comment]
> 我不知道你使用的这个5.77写入了安卓分区的哪些区域，最好的办法是恢复安卓系统，修复分区。然后重新写入armbian

感谢OP大佬的耐心指导，发现是我U盘接口太新的问题，换了个2.0U盘正在安装中。。。再次感谢

**Comment by LiteCoder** [comment]
> > 我不知道你使用的这个5.77写入了安卓分区的哪些区域，最好的办法是恢复安卓系统，修复分区。然后重新写入armbian
> 
> 感谢OP大佬的耐心指导，发现是我U盘接口太新的问题，换了个2.0U盘正在安装中。。。再次感谢

你好，请问一下不恢复Android，可以在5.77版本上直接刷armbian吗

**Comment by zangliu2077** [comment]
> > > 我不知道你使用的这个5.77写入了安卓分区的哪些区域，最好的办法是恢复安卓系统，修复分区。然后重新写入armbian
> > 
> > 
> > 感谢OP大佬的耐心指导，发现是我U盘接口太新的问题，换了个2.0U盘正在安装中。。。再次感谢
> 
> 你好，请问一下不恢复Android，可以在5.77版本上直接刷armbian吗
可以尝试开机的时候，N1插上显示器，接上键盘，hit any key5秒内，随便按键盘让跑码停下来，然后输入run usb_boot
U盘启动，再用刷入EMMC命令armbian-install
没测试过，自行测试吧
