### ISSUE TITLE
请求添加dg3399下附dts与dtb

### ISSUE THREAD

**Issue by lauren12133** [ophub/amlogic-s9xxx-armbian#1492]
请求添加  dg3399
规格书：
[8802C_DG-3399多媒体控制板规格书.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/11785106/8802C_DG-3399.pdf)

dtb: https://github.com/cm9vdA/build-linux/blob/2088d95d03aee1dcf60599deb0e218f7f3083623/boot/dts/rockchip/bsp/rk3399-dg3399.dtb

dts:https://github.com/cm9vdA/build-linux/blob/2088d95d03aee1dcf60599deb0e218f7f3083623/boot/dts/rockchip/bsp/rk3399-dg3399.dts

**Comment by ophub** [comment]
dg3399 有专用的 u-boot 文件没？或者适用哪个的？

**Comment by lauren12133** [comment]
> dg3399 有专用的u-boot文件或者源码没有？或者适合哪个的？
通刷rockpro64的所有固件 理论上适用rockpro64的uboot

**Comment by lauren12133** [comment]
[u-boot-rockchip.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11785667/u-boot-rockchip.zip)

**Comment by ophub** [comment]
我解压时有错误，你的压缩包里是不是只有1个 u-boot-rockchip.bin 文件？
我解压得到的这个文件9m大小，看大小是不正确的。单个文件一般是16m大小的bootloader.bin

**Comment by lauren12133** [comment]
> 我解压时有错误，你的压缩包里是不是只有1个 u-boot-rockchip.bin 文件？ 我解压得到的这个文件9m大小，看大小是不正确的。单个文件一般是16m大小的bootloader.bin 或者是2个或者3个u-boot文件的组合

没有 但是目前手里有两个固件  一个armbian 一个openwrt  是否可以提取出来

**Comment by ophub** [comment]
armbian 的 /usr/lib 目录下一般会带 linux-u-boot-**** 的目录

**Comment by lauren12133** [comment]
> armbian 的 /usr/lib 目录下一般会带 linux-u-boot-**** 的目录

提取到了 用的式king3399的uboot
[linux-u-boot-current-king3399_23.02.0-trunk_arm64.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11786746/linux-u-boot-current-king3399_23.02.0-trunk_arm64.zip)

**Comment by ophub** [comment]
那你可以直接拿king3399的固件测试一下。你到当前任意一个armbian系统，或者openwrt系统，或者其他linux系统，下载king3399并解压，例如重命名为 armbian.img

```
mkdir -p bootfs
sudo loseup -Pf --show armbian.img
# 挂载完看到返回的挂载点，例如 /dev/loop8
sudo mount /dev/loop8p1 bootfs
cd bootfs
vi armbianEnv.txt
# 修改里面dtb的文件名
# 把你上面的 rk3399-dg3399.dtb 上传到 dtb/rockchip 目录下
sudo umount bootfs
sudo losetup -D
```

这个armbian.img就是你可以使用的了。你写入usb插入dg3399试试

**Comment by ophub** [comment]
添加好了： https://github.com/ophub/amlogic-s9xxx-armbian/commit/f5cd79dc8791f908be4be418dc5a60209f9ff305
Actions: https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/5310486020
等10分钟后你到 https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2023.06 里下载试试吧

**Comment by lauren12133** [comment]
> 添加好了： [f5cd79d](https://github.com/ophub/amlogic-s9xxx-armbian/commit/f5cd79dc8791f908be4be418dc5a60209f9ff305) Actions: https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/5310534947
> 
> 等10分钟后你到 https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2023.06 里下载试试吧。反馈一下能否正常启动。

经测试 发现是dtb的问题  然后找到了新的dtb 并且已经测试可以正常启动  请更新 谢谢
[dg3399.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11789865/dg3399.zip)

**Comment by ophub** [comment]
你新找的这个dtb有源文件没，我添加到F大的内核库里，方便持续更新使用

**Comment by lauren12133** [comment]
> 你新找的这个dtb有源文件没，我添加到F大的内核库里，方便持续更新使用

我在armbian里提得 暂时没有源文件 我会时刻关注 并提交

**Comment by ophub** [comment]
好的

**Comment by lauren12133** [comment]
劳烦触发下 jammy  bullseye openwrt

**Comment by ophub** [comment]
dg3399都启动了，10分钟后好

**Comment by lauren12133** [comment]
[rk3399-dg3399.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12404091/rk3399-dg3399.zip)
更新dtb  添加支持红外遥控，修复TF卡速度跑不满 （作者：Q群長風掠影） 请求更新dtb 并触发actions jammy bullseye openwrt

**Comment by ophub** [comment]
已经更新并启动编译，你随后到releases里下载测试下。
这个文件的dts源文件有没有？

**Comment by lauren12133** [comment]
> 已经更新并启动编译，你随后到releases里下载测试下。 这个文件的dts源文件有没有？

没有 群里群友私人在搞  没开放
