### ISSUE TITLE
SV6051p wifi chip driver

### ISSUE THREAD

**Issue by evanferrao** [ophub/amlogic-s9xxx-armbian#1494]
```
              At present, there is no driver for the SV6051p wifi chip in the mainline kernel, so wireless cannot be used.
```

https://forum.armbian.com/topic/16299-armbian-on-s905w-tvbox-a95x-f1-wifi-chip-sv6051p/

_Originally posted by @ophub in https://github.com/ophub/amlogic-s9xxx-armbian/issues/395#issuecomment-1165289704_
            
            
           
I've been going through this topic for a while. I have 2 x96 mini, both with sv6051p wifi chip in them.
After going through some posts at https://forum.libreelec.tv/thread/25151-mecool-m8s-pro-w/?postID=165965#post165965 , I found out that there is a patch adding support for sv6051 drivers in 5.10 and 5.15. The patch can be found at https://github.com/armbian/build/commit/f3388b9aee0d1564a28fbc661c6e7b0415a6dfd0#diff-c5ac85cff49b3e2a32a31e7a2042a3ceca45859cb90e5e45ba3f19fc04681d56
 
would it be possible for wifi to work with this? I'm willing to test

**Comment by ophub** [comment]
When I compiled and tested locally, the patches could be added successfully and the compilation could be completed without any issues. I have placed these two [beta](https://github.com/ophub/kernel/tree/main/kernel-patch/beta) patches in the kernel compilation repository and started the beta compilation process, which will take approximately one hour. You can keep track of the compilation details at any time and download the test version from the [kernel_beta](https://github.com/ophub/kernel/releases/tag/kernel_beta).

5.10: https://github.com/ophub/kernel/actions/runs/5341054696/jobs/9681505001

5.10: https://github.com/ophub/kernel/actions/runs/5340996704

download: https://github.com/ophub/kernel/releases/tag/kernel_beta

**Comment by Scirese** [comment]
Sorry, but this patch doesn't seems to work properly.

Device: Oranth TX3 Mini (s905w), wifi chip sv6051p
Kernel: Self compiled Linux 6.3.9, source is [here](https://github.com/Scirese/linux/tree/6.3)
Logs here: https://pastebin.com/G6cwzsP8

WLAN adapter didn't show up too.
Patch for 6.3 is grabbed from https://github.com/armbian/build/blob/main/patch/kernel/archive/rk322x-6.3/wifi-4003-ssv-6051-driver.patch

**Comment by Megabitsz** [comment]
after reboot:
wifi connect but cannot access ssh or ping ip
