### ISSUE TITLE
e900v22c 安装完 armbian 默认没有wifi，请问如何正确开启wifi?

### ISSUE THREAD

**Issue by yushizhi** [ophub/amlogic-s9xxx-armbian#1496]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
没有wifi

**Comment by caitouwh** [comment]
https://github.com/armbian/firmware/tree/master/uwe5621ds    这个有用吗 ？
