### ISSUE TITLE
Can't boot ZTE b860h S905x

### ISSUE THREAD

**Issue by phreakaz** [ophub/amlogic-s9xxx-armbian#15]
i have burned it on sd card but it won't boot, what should i edit?
I have try dd if uboot.bin hg680p but same isue

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_buster_2021.11.08.0444/Armbian_21.11.0_Aml_s905x_buster_5.4.158_2021.11.08.0437.img.gz

Use s905x

**Comment by phreakaz** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_buster_2021.11.08.0444/Armbian_21.11.0_Aml_s905x_buster_5.4.158_2021.11.08.0437.img.gz
> 
> Use s905x Use https://rufus.ie/ to write the .img file to `USB` to start.

Yes I use this `
![Uploading 1636362421517401777482204137129.jpg…]()
`

**Comment by phreakaz** [comment]
![IMG_20211108_160928](https://user-images.githubusercontent.com/21380142/140714558-a1b720ae-8c6d-40bf-abfb-c12880231c13.jpg)

I try burn to USB HDD and SDcard but some issue can't boot, other image armbian s905s just dd if uboot hg680p via android and work fine

**Comment by ophub** [comment]
Enter your unzipped folder and burn the final img file.
The suffix of the folder on your picture is img, that is not a file, enter the folder.

Can't dd

**Comment by phreakaz** [comment]
I know bro, burn with rufus or balenaetcher, the problem after burn can't boot
-burn .img to sdcard
-plugin sdcard to devices ( ZTE b860h rooted)
-turn on or plug power supply.
-can't boot to armbian

![IMG_20211108_164522](https://user-images.githubusercontent.com/21380142/140719701-0e059d8e-ef21-41c5-a294-e727315e7dc9.jpg)

**Comment by ophub** [comment]
What system is in your box now? Did you turn on the USB flash drive and start it?

Can you try to start with openwrt?

https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/openwrt_s9xxx_lede_2021.11.08.0354/openwrt_s905x2_k5.4.158_2021.11.08.0343.img.gz

**Comment by phreakaz** [comment]
![Screenshot_20211108_174440](https://user-images.githubusercontent.com/21380142/140728531-9b8bc8b2-3ca4-4104-bcf1-606ba3947272.jpg)
I use android box rooted, i try boot openwrt via sdcard work fine, but ned replace u-boot.bin hg680p

**Comment by phreakaz** [comment]
![memilih-openwrt-18 06-untuk-stb-b860h](https://user-images.githubusercontent.com/21380142/140730080-268de99c-c4d0-4886-befb-13cf15324532.png)
Tested os can boot on b860h

**Comment by ophub** [comment]
In the openwrt system, which u-boot did you replace?

It is the same in armbian, they are the same.

After you replace it, try it, and remember to give the replaced file permissions
chmod +x *.bin

**Comment by ophub** [comment]
Or
 /boot/uExt.txt
replace to
meson-gxl-s905x-zte-b860h.dtb

**Comment by xNabak** [comment]
didn't work with B860H (s905x)

problem: bootloop

common linux installation for B860H (but with firmware in this project cause bootloop)
1. from android OS, change B860H bootloader with bootloader from HG680P (with terminal emulator app)
2. then reboot (with bootable sdcard of course)
3. done

NOTE:
- B860H original bootloader doesn't allow boot from external disk. that's why the bootloader needs to be replaced
- I've tried all you suggested, sadly nothing works
- [B860H & HG680P bootloader](https://bit.ly/3wRLnnr)
- [working armbian firmware](https://bit.ly/3Cpozwu)

btw HG680P working great with this firmware, except the wifi doesn't work

**Comment by xNabak** [comment]
UPDATE:

add this config to `/boot/extlinux/extlinux.conf` to make it work
```
LABEL Armbian
LINUX /zImage
INITRD /uInitrd
FDT /dtb/amlogic/meson-gxl-s905x-p212.dtb
APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
```
![photo_2021-11-16_18-02-54](https://user-images.githubusercontent.com/29066277/141974075-21437c82-4a9e-4d44-b177-8d4a547f2ba5.jpg)
* but monitor shows that zebra on boot

**Comment by tugoes** [comment]
> UPDATE:
> 
> add this config to `/boot/extlinux/extlinux.conf` to make it work
> 
> ```
> LABEL Armbian
> LINUX /zImage
> INITRD /uInitrd
> FDT /dtb/amlogic/meson-gxl-s905x-p212.dtb
> APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
> ```
> 
> ![photo_2021-11-16_18-02-54](https://user-images.githubusercontent.com/29066277/141974075-21437c82-4a9e-4d44-b177-8d4a547f2ba5.jpg)
> 
> * but monitor shows that zebra on boot

Can booting?

**Comment by phreakaz** [comment]
> > UPDATE:
> > add this config to `/boot/extlinux/extlinux.conf` to make it work
> > ```
> > LABEL Armbian
> > LINUX /zImage
> > INITRD /uInitrd
> > FDT /dtb/amlogic/meson-gxl-s905x-p212.dtb
> > APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![photo_2021-11-16_18-02-54](https://user-images.githubusercontent.com/29066277/141974075-21437c82-4a9e-4d44-b177-8d4a547f2ba5.jpg)
> > 
> > * but monitor shows that zebra on boot
> 
> Can booting?

Just look the monitor broh

**Comment by tugoes** [comment]
Berarti g bisa booting msk ke dlm linux nya y?

**Comment by xNabak** [comment]
bisa booting, tapi waktu awal stb nyala muncul zebra kek gitu. cuman beberapa detik lalu lanjut booting

**Comment by xNabak** [comment]
> UPDATE:
> 
> add this config to `/boot/extlinux/extlinux.conf` to make it work
> 
> ```
> LABEL Armbian
> LINUX /zImage
> INITRD /uInitrd
> FDT /dtb/amlogic/meson-gxl-s905x-p212.dtb
> APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
> ```
> 
> ![photo_2021-11-16_18-02-54](https://user-images.githubusercontent.com/29066277/141974075-21437c82-4a9e-4d44-b177-8d4a547f2ba5.jpg)
> 
>     * but monitor shows that zebra on boot

kalo install ke emmc jalankan command ini, setelah `armbian-install`. pakai user __root__
```
export EB=/mnt/bootfs
mkdir -p $EB
mount /dev/$(lsblk -l -o NAME | grep -oE '(mmcblk[0-9]?boot0)' | sed "s/boot0//g")p1 $EB
sed -i "s|ROOTFS|ROOTFS_EMMC|g" $EB/extlinux/extlinux.conf
umount $EB
```

**Comment by hidasw** [comment]
@nabakdev 
Mending pake armbian-install atau install-aml.sh?
aku belum pernah coba armbian-install.

**Comment by nabakdev** [comment]
> @nabakdev Mending pake armbian-install atau install-aml.sh? aku belum pernah coba armbian-install.

armbian-install

**Comment by mosoksehbro** [comment]
<img width="1085" height="1226" alt="Image" src="https://github.com/user-attachments/assets/e5e80005-afe4-4d7d-9fe9-2f574408dc6d" />



need help for thiis if i reboot and spam enter or space didnt anytyhing but if i spam ctrl+z the boot already show like that and freeze 
my stb firmware rn use puplstone 3.8 and my type b860h v1

**Comment by nabakdev** [comment]
> <img alt="Image" width="1085" height="1226" src="https://private-user-images.githubusercontent.com/80755821/497473799-e5e80005-afe4-4d7d-9fe9-2f574408dc6d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk5MjAzNzksIm5iZiI6MTc1OTkyMDA3OSwicGF0aCI6Ii84MDc1NTgyMS80OTc0NzM3OTktZTVlODAwMDUtYWZlNC00ZDdkLTlmZTktMmY1NzQ0MDhkYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA4VDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYWQ1ZDU2ZmM3ZWYyYTk0MDI0YTdiY2JiMjAzMjZmMWNlMTRmZjhlOGEyYTUwNGRiZTMxMjAxZmRlZTg1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PeAptllzAPUDLRJ56SVwpTbFMPxsBG5M2PQhuu6zCmY">
> 
> need help for thiis if i reboot and spam enter or space didnt anytyhing but if i spam ctrl+z the boot already show like that and freeze my stb firmware rn use puplstone 3.8 and my type b860h v1

jelas2 gae pulpstone lha nyapo open issue ng kene

**Comment by mosoksehbro** [comment]
> > <img alt="Image" width="1085" height="1226" src="https://private-user-images.githubusercontent.com/80755821/497473799-e5e80005-afe4-4d7d-9fe9-2f574408dc6d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk5MjAzNzksIm5iZiI6MTc1OTkyMDA3OSwicGF0aCI6Ii84MDc1NTgyMS80OTc0NzM3OTktZTVlODAwMDUtYWZlNC00ZDdkLTlmZTktMmY1NzQ0MDhkYzZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA4VDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiYWQ1ZDU2ZmM3ZWYyYTk0MDI0YTdiY2JiMjAzMjZmMWNlMTRmZjhlOGEyYTUwNGRiZTMxMjAxZmRlZTg1MzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.PeAptllzAPUDLRJ56SVwpTbFMPxsBG5M2PQhuu6zCmY">
> > 
> > need help for thiis if i reboot and spam enter or space didnt anytyhing but if i spam ctrl+z the boot already show like that and freeze my stb firmware rn use puplstone 3.8 and my type b860h v1
> 
> jelas2 gae pulpstone lha nyapo open issue ng kene


> ohh sorry bang rencana mau install armbian tapi ada issue itu posisi dapet unit pulpstone gitu di utas saya bilang keadaannya right now di pulpstone

**Comment by nabakdev** [comment]
ealah kirain mau install pulpstone, aku udah lupa bootlognya gimana tapi coba cek di dts, kernel atau ubootnya. pasti ga jauh2 dari itu. kalo tetep gabisa pake yg versi dbai itu dah enak kernelnya. udah dipatch

**Comment by nabakdev** [comment]
oiya extlinux.conf nya dipake

**Comment by mosoksehbro** [comment]
okee siap nanti saya coba bang, thanks infonya
