### ISSUE TITLE
Local kernel compilation failure on WSL2

### ISSUE THREAD

**Issue by sajati** [ophub/amlogic-s9xxx-armbian#1500]
Fail on chroot, is WSL2 unsupported ? im using ubuntu jammy under windows 10
```
[ SUCCESS ] The modules is installed successfully.
[ STEPS ] Install headers...
[ SUCCESS ] The headers is installed successfully.
[ STEPS ] Create chroot...
[ INFO ] Armbian PLATFORM: [ rockchip ]
[ INFO ] Enter the chroot armbian system...
chroot: failed to run command ‘/bin/bash’: Exec format error
[ ERROR ] Create chroot uInitrd-6.1.35-stb file failed.
```

**Comment by sajati** [comment]
my command is `sudo ./recompile -r unifreq -k 6.1.35 -a false -m all -p false -n -stb -t gcc`

**Comment by ophub** [comment]
如果你使用 WSL/WSL2 进行编译

由于 WSL 的 PATH 中包含带有空格的 Windows 路径，有可能会导致编译失败，请在 `chroot` 加上：


`PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin`

**Comment by sajati** [comment]
i set WSL2 to not include windows path by default, here's my current PATH :
```
~$ echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/snap/bin
```
do you mean tweaks chroot command specifically ?
like adding some line in `recompile` script ?
if so how to do it ?
