### ISSUE TITLE
cm311备份bootloader失败

### ISSUE THREAD

**Issue by ss8688** [ophub/amlogic-s9xxx-armbian#1501]
**Device Information |设备信息**
 - SOC: [S095l3a]
 - Model [cm311-1a]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1]
 - Release: [jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

这个盒子收来的时候就刷了armbian了，不过我想刷jammy,但是备份bootloader失败

![Screenshot 2023-06-24 09-17-31](https://github.com/ophub/amlogic-s9xxx-armbian/assets/59367202/dedd97d2-9b87-4740-86d7-c7129bb86c38)

**Comment by ophub** [comment]
从图上看多处显示系统只读。
这个U盘中的系统被修改权限了，简单一点重新刷U盘。先拔了电源，插上U盘，再插入电源。必须这样断电操作

**Comment by ss8688** [comment]
@ophub 已解决，换了一个u盘，这个u盘不知怎么用不了
