### ISSUE TITLE
usb 网卡rtl8811cu 不工作

### ISSUE THREAD

**Issue by ss8688** [ophub/amlogic-s9xxx-armbian#1503]
**Device Information | 设备信息**
 - SOC: [S095l3a]
 - Model [cm311]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15/6.1]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

armbian应该自带rtl8811cu驱动啊，lsusb 也识别到了无线网卡，nmcli 里却没有，是不是驱动损坏或者我进行了错误的操作？
![Screenshot 2023-06-24 14-09-42](https://github.com/ophub/amlogic-s9xxx-armbian/assets/59367202/72be254a-d71c-4087-a2aa-48fe6bb50ecd)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek

无驱动
