### ISSUE TITLE
S905L2安装pve问题

### ISSUE THREAD

**Issue by qiebu3509** [ophub/amlogic-s9xxx-armbian#1504]
**Device Information | 设备信息**
 - SOC: [S095L2]
 - Model [MGV200]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.115/6.1.32]
 - Release: [bullseye]

**Describe the bug | 问题描述**
processing rtiggers for pve-ha-manager (3.3-4) 停止不动
已经是一个小时左右了
但重新开机之后他有显示pve的ip地址，但很卡，无法进行操作，已经试过重新来一遍了，还是如此

![photo_2023-06-24_16-41-21](https://github.com/ophub/amlogic-s9xxx-armbian/assets/70996502/dd8b655b-1d20-4bcc-b9c9-83ba33d99e1f)

**Comment by ophub** [comment]
你是在USB里？日志最后一行，设备断开了

**Comment by qiebu3509** [comment]
> 你在USB里？日志最后一行，设备断开了

这个是键盘。要写emmc才行？

**Comment by ophub** [comment]
你的USB稳定就可以用。我今天刚重装了bullsyse并安装了pve,我使用armbian-software安装挺顺利的

**Comment by qiebu3509** [comment]
> 你的USB稳定就可以用。我今天刚重装了bullsyse并安装了pve,我使用armbian-software安装挺顺利的

正常使用是没什么问题，也许是我的设备配置低，我在试试看吧

**Comment by qiebu3509** [comment]
> 你的USB稳定就可以用。我今天刚重装了bullsyse并安装了pve,我使用armbian-software安装挺顺利的

用ssh可以过这步了，现在出现另外一个问题

------------------------------
Deleting module version: 0.0.2
completely from the DKMS tree.
------------------------------
Done.
Building for 6.1.35-ophub
This package appears to be a binaries-only package
 you will not be able to build against kernel 6.1.35-ophub
 since the package source was not provided
Setting up pve-ha-manager (3.3-4) ...
watchdog-mux.service is a disabled or a static unit, not starting it.
Job for pve-ha-lrm.service failed because a timeout was exceeded.
See "systemctl status pve-ha-lrm.service" and "journalctl -xe" for details.
Setting up pve-manager (7.2-7) ...
Job for pveproxy.service failed because a timeout was exceeded.
See "systemctl status pveproxy.service" and "journalctl -xe" for details.
dpkg: error processing package pve-manager (--configure):
 installed pve-manager package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of proxmox-ve:
 proxmox-ve depends on pve-manager; however:
  Package pve-manager is not configured yet.

dpkg: error processing package proxmox-ve (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 pve-manager
 proxmox-ve
[ STEPS ] Start installing packages: [ ifupdown2 ]...
Hit:1 http://security.debian.org bullseye-security InRelease
Hit:2 http://deb.debian.org/debian bullseye InRelease
Hit:3 http://deb.debian.org/debian bullseye-updates InRelease
Hit:4 http://deb.debian.org/debian bullseye-backports InRelease
Get:5 https://raw.githubusercontent.com/pimox/pimox7/master dev/ InRelease [2,186 B]
Get:6 http://mirror.ossplanet.net/armbian/apt bullseye InRelease [53.3 kB]
Fetched 55.5 kB in 5s (10.4 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
ifupdown2 is already the newest version (3.1.0-1+pmx3).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up pve-manager (7.2-7) ...
Job for pveproxy.service failed because a timeout was exceeded.
See "systemctl status pveproxy.service" and "journalctl -xe" for details.
dpkg: error processing package pve-manager (--configure):
 installed pve-manager package post-installation script subprocess returned error exit status 1
dpkg: dependency problems prevent configuration of proxmox-ve:
 proxmox-ve depends on pve-manager; however:
  Package pve-manager is not configured yet.

dpkg: error processing package proxmox-ve (--configure):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 pve-manager
 proxmox-ve

E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ophub** [comment]
忽略

**Comment by qiebu3509** [comment]
> 忽略

不行，放弃了，install也用不了，我还是直接docker吧。
