### ISSUE TITLE
8822cs一连wifi就提示错误 大佬这个是怎么回事  这么修复

### ISSUE THREAD

**Issue by 67389906** [ophub/amlogic-s9xxx-armbian#1507]
[新建文本文档 (3).txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/11868591/3.txt)

**Comment by 67389906** [comment]
大哥你看有没有修复的可能 我可以发给你一个试试 送你一个折腾一下

**Comment by ophub** [comment]
折腾不了，这个驱动f大换过好几个版本了，x90max（s905x3）用的就是，hg680p等很多盒子都使用的这个无线。有很多反馈能使用的，但也有不能用的，无解。
