### ISSUE TITLE
新增 魔百和CM311-1a-CH s905l3a 2+16

### ISSUE THREAD

**Issue by yu6zhou** [ophub/amlogic-s9xxx-armbian#1508]
设备：CM311-1a CH
SOC：s905l3a
内存版本：2GB内存+16GB闪存
目前刷了[Armbian_23.08.0_amlogic_s905l3a_jammy_6.1.35_server_2023.06.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.06/Armbian_23.08.0_amlogic_s905l3a_jammy_6.1.35_server_2023.06.21.img.gz)，装了CasaOS，内装青龙面板，暂时没发现问题。

**Comment by ophub** [comment]
你使用的这个默认固件写入emmc使用的？
你有这个设备的安卓固件没？分享一个下载链接我转存一份。
把你的设备拍几个照片分享一下，正面，反面（能看到型号标识），如果有主板照片的话正面反面来两张。

分享一下这几个地方的记录信息：
```
cat /etc/ophub-release
cat /boot/uEnv.txt
ls -l /boot/u-boot*
```

**Comment by yu6zhou** [comment]
对，写入emmc了，青龙面板暂时只拉了京东的库在跑，能成功跑起来，其他暂时还没测试。
自带的安卓固件我得问问海鲜市场老板有没有保存。
照片如何上传？

**Comment by ophub** [comment]
把照片拖到这个回复的文本框里，等几秒看变成上传成功的代码即可。不要马上提交，刚拖进来等一等

**Comment by yu6zhou** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/6ec29930-8357-41d8-a562-27bfd0389f2b)

**Comment by yu6zhou** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/9ca04e7f-dcc1-4937-b4e5-d4698bfb1a69)

**Comment by yu6zhou** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/70f407ae-00e9-4b71-9f08-4a109c35eb45)

**Comment by yu6zhou** [comment]
我买的是已经刷好的，卖家没保存原厂备份。拆机晚点看看，动手能力不行。🤣

**Comment by ophub** [comment]
好的，谢谢分享，回家了把系统里的信息也分享一下。我记录一下使用的配置，添加到支持列表里。

```
cat /etc/ophub-release
cat /boot/uEnv.txt
ls -l /boot/u-boot*
```

**Comment by yu6zhou** [comment]
今天测试了下，这个版本的两个usb口都无法正常识别u盘。
<img width="409" alt="截圖 2023-06-27 21 44 09" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/80c3187e-964f-4a24-839d-e85f91cf4e32">

**Comment by yu6zhou** [comment]
<img width="410" alt="截圖 2023-06-27 21 48 56" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/629fb2d5-d53b-4422-915d-ae13b61e977e">
<img width="694" alt="截圖 2023-06-27 21 50 28" src="https://github.com/ophub/amlogic-s9xxx
<img width="694" alt="截圖 2023-06-27 21 50 46" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/231f6368-f1bd-403d-9d2f-e24922b53fc0">
-armbian/assets/93600821/3c809f61-0e3e-44ec-9a73-5474fb5eddf3">

**Comment by yu6zhou** [comment]
<img width="542" alt="截圖 2023-06-27 22 27 07" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/5dd8833c-4254-4e5e-a1d9-6c6dcede5d23">

**Comment by ophub** [comment]
这是正常的，内存和硬盘都比标的小一点

**Comment by yu6zhou** [comment]
挂载U盘没成功，是什么原因？

**Comment by ophub** [comment]
lsblk看一下

**Comment by yu6zhou** [comment]
上面发了

**Comment by ophub** [comment]
lsblk看不到有接入的设备

**Comment by yu6zhou** [comment]
是啊，我两个usb口都试了，没见有接入的设备。

**Comment by ophub** [comment]
你不是拿U盘启动然后写入emmc的？

**Comment by yu6zhou** [comment]
是啊，我拿U盘启动写入emmc的，用开心电视助手。所以很奇怪！

**Comment by yu6zhou** [comment]
重刷armbian有什么好方法？

**Comment by yu6zhou** [comment]
重刷armbian有什么好方法，不用回退安卓tv系统的？@ophub

**Comment by ophub** [comment]
直接U盘重刷安装就可以，不用再刷回安卓

**Comment by yu6zhou** [comment]
今天重刷了一下，选了304（话说咋cm311-1a-ch和e900v22归到一起，主板配置一样？反倒和305 cm311-1a-yst不一样？）
5.x内核的可以识别U盘，sda的就是；可用闪存和内存多了一点。
<img width="424" alt="截圖 2023-07-02 17 38 10" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/f06853fd-0d9b-4542-b75e-7971ebda5d13">
<img width="528" alt="截圖 2023-07-02 17 39 15" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/f8fccec1-9c43-4405-8741-183ee4719ee4">

**Comment by ophub** [comment]
根据你的测试结果，和E900V22C-D的dtb及u-boot相同，所以它们几个可以通用一个固件

**Comment by haiji1981** [comment]
老师好，移动魔百盒cm311-1sa-ZG刷armbian需要使用哪个镜像，我在页面没有找到呢

**Comment by thiesymon** [comment]
> 老师好，移动魔百盒cm311-1sa-ZG刷armbian需要使用哪个镜像，我在页面没有找到呢

我也是cm311-1sa，请问你是怎么刷机的，我就买了单机，还不知道使用U盘刷还是用烧录工具刷

**Comment by HeroPoter** [comment]
> > 老师好，移动魔百盒cm311-1sa-ZG刷armbian需要使用哪个镜像，我在页面没有找到呢
> 
> 我也是cm311-1sa，请问你是怎么刷机的，我就买了单机，还不知道使用U盘刷还是用烧录工具刷

同型号，cm311-1sa CH，使用304和22D/C一样

**Comment by elementchen** [comment]
@ophub O大，请教您一下，CM311-1SA 2+8G的这个型号，它本身是有无线网卡的，有什么办法可以在armbian里面激活并使用它自带的无线网卡吗？

**Comment by ophub** [comment]
看无线芯片，到内核仓库看看有没对应的驱动。
https://github.com/unifreq/linux-6.1.y

**Comment by elementchen** [comment]
> 看无线芯片，到内核仓库看看有没对应的驱动。 https://github.com/unifreq/linux-6.1.y
我网上查了一下，发现是UWE5621DS这款芯片的，具有蓝牙和wifi功能，但是我不知道如何安装驱动，如何整合到固件里面，O大能帮忙弄一个吗

**Comment by elementchen** [comment]
我网上查了一下，发现CM311-1SA的无线模块是UWE5621DS这款芯片的，具有蓝牙和wifi功能，但是我不知道如何安装驱动，如何整合到固件里面，O大能帮忙弄一个吗

**Comment by ophub** [comment]
安卓系统有驱动，但主线内核没有驱动

**Comment by await777** [comment]
@ophub 老大，311-1sa-zg用了304，为啥运行后指示灯不亮

**Comment by qq664636016** [comment]
已经在盒子上刷了armbian系统，想重刷一遍固件恢复出厂设置可以吗？用armbian-install

**Comment by ophub** [comment]
可以，usb启动，重写就覆盖了

**Comment by amazing0575** [comment]
有openwrt旁路由固件吗

**Comment by thiesymon** [comment]
博主主页有 你找一下

**Comment by wanganfu** [comment]
楼主，我跟你的一样的型号，为什么我从U盘启动一直黑屏呀
