### ISSUE TITLE
Linux headers install through armbian-config installs Armbian 5.10 headers instead of 5.4.183

### ISSUE THREAD

**Issue by Jeebus678** [ophub/amlogic-s9xxx-armbian#151]
Not sure where to download the proper headers- they're critical for my display driver.

**Comment by ophub** [comment]
Update with armbian-update

https://github.com/ophub/amlogic-s9xxx-armbian#update-armbian-kernel

The headers files in the kernel is installed in the /use/local/include directory. When compiling the application, add -I /usr/local/include to the CFLAG parameter of GCC to find the headers files.

**Comment by Jeebus678** [comment]
Im not sure what you mean. When compiling what application? Im using armbian s9xx bullseye 5.4 and i'm looking to get the proper headers for my build.

**Comment by ophub** [comment]
The headers files are in the `/usr/local/include` directory.

**Comment by Jeebus678** [comment]
Under `/usr/local/include`

```
asm  asm-generic  drm  linux  misc  mtd  rdma  scsi  sound  video  xen
```

Not sure how this pertains to headers.

As for `armbian-update`

```
Ready to update, please wait...
current version: 5.4.183, Latest version: 5.4.183
Already the latest version, no need to update.
```

I'm using a tx3 mini and I don't think armbian 5.10. So it seems like the options here are either try to get the 5.4 headers that'll create a `/lib/modules/(uname -sr)/build` directory, or use an older version like 5.9.

**Comment by ophub** [comment]
I don't understand what are you looking for? Need the directory where the kernel was compiled? You can use the kernel compilation script to automatically generate a kernel, which has a complete structure, from which you can check what you want

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

**Comment by Jeebus678** [comment]
I needed just the headers. 

Found them [here](https://users.armbian.com/balbes150/arm-64/deb/)

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/stable/5.10.104
`header-5.10.104-flippy-70+.tar.gz`
I use the method of decompression and installation, not the deb file format

**Comment by Jeebus678** [comment]
The 5.10 headers weren't working for me. I read there was a compatibility issue after they stopped support for the tx3 mini after 5.9. I just did `wget` and `dpkg -i`

**Comment by ophub** [comment]
My firmware can use the 5.4/5.10/5.15/5.16 kernel, just sent your kernel directory, including headers

**Comment by Jeebus678** [comment]
So you verified the tx3 mini s905w processor supports kernels later than 5.9?

**Comment by ophub** [comment]
The current LTS kernel of s905w only supports version 5.4

The 5.9 kernel has been EOL.

**Comment by Jeebus678** [comment]
Thank you. 

Finally, I am looking to edit the save-to-emmc script. It's usually in the form of `install-aml.sh` on other images, and I know I can use `armbian-install`. However, I am looking to make edits.
