### ISSUE TITLE
我想知道这个盒子怎么进入U盘的系统，一直是安卓系统无法进入armbian安卓，是要短接些什么吗？

### ISSUE THREAD

**Issue by sters-for-watching** [ophub/amlogic-s9xxx-armbian#1510]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by sters-for-watching** [comment]
我的盒子是mgv2000，芯片是s905l2b，代工是kl 04

**Comment by ophub** [comment]
看文档

**Comment by sters-for-watching** [comment]
我的盒子进入usb系统可以正常运行，但是无法写入emmc，显示找不到emmc，该如何处理？

**Comment by ophub** [comment]
也是看文档，最后部分
