### ISSUE TITLE
魔百和cm311-1a ch 刷完armbian 安装CasaOS（可视化），再内装青龙面板

### ISSUE THREAD

**Issue by yu6zhou** [ophub/amlogic-s9xxx-armbian#1511]
在armbian-software列表里没看到有CasaOS，得自己手工搓码，挺不方便的。
另外，大佬也可以考虑把海纳思系统做下适配，对轻nas有需求，万分感谢🙏。
https://dl.ecoo.top
https://bbs.histb.com/t/stb-flash

**Comment by ophub** [comment]
CasaOS 添加到armbian-software了，序号309

**Comment by yu6zhou** [comment]
armbian什么版本的？jammy_6.x内核版本有吗？没看到![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/93600821/d8ebd829-144e-4451-9d09-fcafcf51a89e)

**Comment by ophub** [comment]
先同步脚本就有了

```
armbian-sync
armbian-software
```

**Comment by yu6zhou** [comment]
指令搓完309有了，但少了308，308是啥？

**Comment by ophub** [comment]
308只有bulleye支持使用，别的不能用，所以不显示
