### ISSUE TITLE
ZXV10 BV310 HDMI正常输出、100M有线网卡正常，可以写入EMMC

### ISSUE THREAD

**Issue by w2xg2022** [ophub/amlogic-s9xxx-armbian#1512]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3] S905L3
 - Model [e.g. HK1] ZXV10 BV310

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] 5.15.116-flippy
 - Release: [e.g. jammy/bullseye] bullseye

ZXV10 BV310是S905L3芯片，使用自编译的S905L3B固件，HDMI正常输出、100M有线网卡正常，可以写入EMMC。请O大查看下面信息，看看是不是能列到支持清单中。

1、刷入安卓4.4.2，安卓固件已经root可以远程adb管理。链接：https://github.com/ophub/kernel/releases/download/tools/android_tv_mgv2000-s905l2-android4.4.2-root.tar.xz
2、rufus-4.1将armbian固件写入U盘，adb reboot update从U盘启动，HDMI有显示。链接：https://github.com/w2xg2022/actions4ty1608/releases/tag/Armbian_bullseye_save_2023.06
3、不开心设备名称显示问题，自己改了meson-gxl-s905l3b-m302a.dtb（转成dts）的第8行。更新到U盘中。
4、armbian-install 写入 emmc，选122（TY1608）。
5、拔掉U盘重启，HDMI正常输出、100M有线网卡正常。

相关信息可以直接看图，不带网址的是自己拍的或截屏的，带网址的就是参考网上的。

![搜狗截图20230627135459](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/1466c1b9-90f8-484d-a31a-6f97b25d16c8)

![d0ea4de3024c85e9bbb705bbd8e2c26](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/8d962226-c68e-40dc-9d75-2d4c33981148)

![搜狗截图20230627141644](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/e218d386-fd97-4c01-84f5-27d7756104a1)

![搜狗截图20230627135857](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/09d78b2a-2fc3-4510-9a9e-9252f4ed23e9)

![搜狗截图20230627140013](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/d8f1deb2-ca2a-4456-8925-2b0cb4a19435)

![搜狗截图20230625145527](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/735b5f88-a40d-4d85-91f0-0c202fbf4e19)

![搜狗截图20230627140401](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/6d37d510-3d0b-4924-b142-9da3f9eadb69)

![搜狗截图20230626113108](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/191bf419-0e7b-4310-8f80-23465e46e4b0)

**Comment by w2xg2022** [comment]
5.15.117-ophub U盘运行没问题（HDMI输出正常、100M有线网卡运行正常）【Armbian_23.08.0_amlogic_s905l3b_bullseye_5.15.117_server_2023.06.16.img.gz】

没有写入emmc，因为盒子准备要出售了。

![搜狗截图20230627144924](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/1f39e9f2-def9-432d-8307-30aae5703477)

**Comment by ophub** [comment]
你测试下6.1.y内核的能不能正常启动

**Comment by w2xg2022** [comment]
6.1.35-ophub U盘运行没问题（HDMI输出正常、100M有线网卡运行正常）
【Armbian_23.08.0_amlogic_s905l3b_bullseye_6.1.35_server_2023.06.21.img.gz】

补充2点：
1、短接点没实际测过，我用的是免拆神器。
2、**5.15.116-flippy可以写入emmc且运行正常【选122】**。但是O大不好意思啊，5.15.117-ophub、6.1.35-ophub没条件测试，现在emmc已经安装好klipper还有一些有的没的，暂时无法折腾它。我下次再买一个这个型号的时候会帮忙测试，但估计能写入成功的概率大。

![搜狗截图20230627150155](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/d29ef900-c14d-44eb-aa8c-7bebb2b199bf)

**Comment by ophub** [comment]
好的，U盘能正常启动，写入一般都没问题，感谢你的分享，这个设备我加入支持列表里。
你是第100个贡献者，感谢你的分享。

**Comment by ophub** [comment]
你现在的测试使用的是s905l3b的固件，我看你发的soc是s905l3的，你有没试过s905l3的默认固件能否正常启动呢？

**Comment by w2xg2022** [comment]
主要是懒，之前刚好在捣鼓TY1608，硬盘有固件就直接拿来用了。

已经测试了5.15.118-ophub、6.1.35-ophub，U盘运行没问题（HDMI输出正常、100M有线网卡运行正常）

![搜狗截图20230627155602](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/015a614c-2564-4879-9315-08a056736642)

![搜狗截图20230627161600](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/c4e8f975-5ee4-48be-8dc2-93e483fcf3b6)

**Comment by ophub** [comment]
最后这个使用的s905l3-cm211这个测试的？

**Comment by w2xg2022** [comment]
Armbian_23.08.0_amlogic_s905l3_bullseye_5.15.118_server_2023.06.21.img.gz
Armbian_23.08.0_amlogic_s905l3_bullseye_6.1.35_server_2023.06.21.img.gz
没有改uEnv.txt（FDT=/dtb/amlogic/meson-gxl-s905l2-x7-5g.dtb）

**Comment by ophub** [comment]
好的，这个设备真不错，通用性挺好，那我把他合并到s905l3默认配置里吧，可以共用，感谢你的分享。

**Comment by csgtli** [comment]
PCB编号：254667 S能不能刷，我看了下主板上的元件布局，丝印编号好像都一样。

**Comment by csgtli** [comment]
Armbian_23.08.0_amlogic_s905l3_bullseye_5.15.118_server_2023.06.21.img.gz
Armbian_23.08.0_amlogic_s905l3_bullseye_6.1.35_server_2023.06.21.img.gz
这两个怎么没有？

**Comment by ophub** [comment]
到bullseye里找s905l3

**Comment by w2xg2022** [comment]
@ophub  O大：

趁盒子还没卖掉抽空测试了一下，现在状况很诡异。

Armbian_23.08.0_amlogic_**s905l3**_bullseye_5.15.119_server_2023.07.01（包括ophub标准版、flippy版本）
Armbian_23.08.0_amlogic_**s905l3**_bullseye_6.1.36_server_2023.07.01（包括ophub标准版、flippy版本）

这2*2=4个固件可以U盘开机，但armbian-install写入emmc时出现错误：
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ ERROR ] Internal eMMC storage was't found in this device!


Armbian_23.08.0_amlogic_**s905l3b**_bullseye_5.15.119_server_2023.07.01
**ophub**标准版，U盘开机后到登录画面但一直找不到IP

Armbian_23.08.0_amlogic_**s905l3b**_bullseye_6.1.36_server_2023.07.01（ophub标准版）
**ophub**标准版，U盘开机时一直重启

Armbian_23.08.0_amlogic_**s905l3b**_bullseye_5.15.119_server_2023.07.01
**flippy**内核，就是之前正常的版本，可以U盘开机，可以写入emmc正常运行（包括网卡、HDMI都正常）

Armbian_23.08.0_amlogic_**s905l3b**_bullseye_6.1.36_server_2023.07.01（ophub标准版）
**flippy**内核，U盘开机时一直重启

**结论，BV310使用s905l3b（meson-gxl-s905l3b-m302a.dtb）的5.15.x版、flippy内核最正常（包括U盘、emmc）。**

**Comment by ophub** [comment]
好的👌感谢分享你的使用方案

**Comment by w2xg2022** [comment]
https://github.com/w2xg2022/actions4ztebv310
写了简单的刷机流程，提供flippy内核5.15.x下载。

**Comment by SoraKasvgano** [comment]
又出新盒子了
4g+32g的4K超高清盒子6PRO                                          中兴ZXV10 B860AV3.2-M                                         运行内存4g+机顶内存32g，安卓9.0系统，蓝牙BT5.0，语音遥控器，支持语音换台，杜比音效，无WIFI。                 
应该是s905l3

**Comment by z969140717** [comment]
> https://github.com/w2xg2022/actions4ztebv310 写了简单的刷机流程，提供flippy内核5.15.x下载。

大佬，刷你的这个底包DDR2%报错，别的包正常开机但是不能U盘启动，可以知指导一下吗

**Comment by cuixing168** [comment]
> > https://github.com/w2xg2022/actions4ztebv310 写了简单的刷机流程，提供flippy内核5.15.x下载。
> 
> 
> 
> 大佬，刷你的这个底包DDR2%报错，别的包正常开机但是不能U盘启动，可以知指导一下吗

我也遇到了相同的问题，找了别的9.0的Root底包，现在用W大佬分享的镜像可以刷入Emmc，但是我的HDMI一直没输出，不管是U盘启动还是安装好重启后，都没信号，不知道为什么，我猜测我的盒子可能和W大佬的主板布局有点不一样

**Comment by zccrs** [comment]
> > > https://github.com/w2xg2022/actions4ztebv310 写了简单的刷机流程，提供flippy内核5.15.x下载。
> > 
> > 
> > 大佬，刷你的这个底包DDR2%报错，别的包正常开机但是不能U盘启动，可以知指导一下吗
> 
> 我也遇到了相同的问题，找了别的9.0的Root底包，现在用W大佬分享的镜像可以刷入Emmc，但是我的HDMI一直没输出，不管是U盘启动还是安装好重启后，都没信号，不知道为什么，我猜测我的盒子可能和W大佬的主板布局或cpu还是有点不一样

遇到了同样的问题，你用的哪个9.0的底包呀，能分享下吗

**Comment by zccrs** [comment]
> 6.1.35-ophub U盘运行没问题（HDMI输出正常、100M有线网卡运行正常） 【Armbian_23.08.0_amlogic_s905l3b_bullseye_6.1.35_server_2023.06.21.img.gz】
> 
> 补充2点： 1、短接点没实际测过，我用的是免拆神器。 2、**5.15.116-flippy可以写入emmc且运行正常【选122】**。但是O大不好意思啊，5.15.117-ophub、6.1.35-ophub没条件测试，现在emmc已经安装好klipper还有一些有的没的，暂时无法折腾它。我下次再买一个这个型号的时候会帮忙测试，但估计能写入成功的概率大。
> 
> ![搜狗截图20230627150155](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/d29ef900-c14d-44eb-aa8c-7bebb2b199bf)

测试过短接点C122可用

**Comment by zccrs** [comment]
> https://github.com/w2xg2022/actions4ztebv310 写了简单的刷机流程，提供flippy内核5.15.x下载。

试了下这个固件刷入后无hdmi显示

**Comment by OYlili** [comment]
安卓root包无法刷入

**Comment by ABNOTF** [comment]
写给后人：如果你买到的盒子是21年7月之后的河南联通那么应该是E254667版型的，这个里面应该是l3b。为什么是应该？因为我拿不下来该死的散热片。我在这里是为了告诉你们这个版型的操作方法。
**首先**，下载并刷入https://github.com/ophub/kernel/releases/download/tools/android_tv_cm201-1-6-ys_s905l3.tar.xz
**之后**刷入https://github.com/w2xg2022/actions4ztebv310/releases/download/Armbian_bullseye_save_2023.07/Armbian_23.08.0_amlogic_s905l3b-ip103h_bullseye_5.15.119_server_2023.07.03.img.gz**并安装到EMMC**
**最后**再使用最新的ophub所编译的包如“Armbian_26.02.0_amlogic_s905l3_trixie_6.12.69_server_2026.02.10”再安装即可使用最新系统。
**Q&A**
**Q1**：为什么不能直接一步到位使用最新的？
**_A1_**：会有未知问题无法安装至emmc
**Q2**：我用其他安卓包是否可行？
**_A2_**：自己尝试，我所使用的4.4.2的包均不能执行adb reboot update
附安装最新系统的图片
希望我的踩坑能帮到您
<img width="1112" height="625" alt="Image" src="https://github.com/user-attachments/assets/04f1435d-752e-4dff-92f8-ef0a8317db6b" />

<img width="1113" height="626" alt="Image" src="https://github.com/user-attachments/assets/5e6bfabb-2a74-4ad1-a474-5721e854bc62" />
