### ISSUE TITLE
魔百和401A开启蓝牙

### ISSUE THREAD

**Issue by Chuhan1112** [ophub/amlogic-s9xxx-armbian#1513]
**Device Information | 设备信息**
 - SOC:M401A
 - Model M401A

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.80-flippy-79+o]
 - Release: [bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

我的信息信息：
```
BOARD=odroidn2
BOARD_NAME="Aml S905l3a"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
BUILD_REPOSITORY_COMMIT=7304af6
VERSION=22.11.0-trunk
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=stable
BRANCH=current
```

这个魔百和 401A 是我在咸鱼上买的，已经刷好了上面的系统，但是蓝牙功能无法使用，
我看了这篇文章 [CM311-1A M401A变身超级智能家居中枢homeassistant，还要什么小米蓝牙中枢网关](https://post.smzdm.com/p/a8xm0rkq/)
发现作者提到可以通过  rtl8761b_config 、 rtk_hciattach 的文件激活CM311-1A、401A设备上的蓝牙功能。奈何距离文章有一段时间且系统有些微差异，作为小白实在有心无力，害怕变砖后无法自救。

只能希望向 ophub 大大寻求帮助，请问这两步骤对于我bullseye release的401A 是否适用

**Comment by Chuhan1112** [comment]
目前`/lib/firmware/rtlbt` 路径下有如下文件
<img width="954" alt="截屏2023-06-28 22 16 43" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/35064712/069477b5-3f32-41bb-98f7-72a502da0149">

**Comment by Chuhan1112** [comment]
感谢ophub 大大这么快就回复，我已经找到了文中所提到的rtl8761b_config文件，但是 rtk_hciattach 工具搜索了一圈不知道要怎么获得。

另外：我之前有经历过安装驱动程序后开机无法通过ssh连接到armbian的情况， 如果测试中出现这种情况，能够怎样恢复呢？ 是否有什么办法可以对系统进行备份并恢复？

**Comment by ophub** [comment]
从U盘启动armbian，armbian-ddbr，选b备份，选r恢复

**Comment by Chuhan1112** [comment]
ophub 大大，请问蓝牙驱动只需要 rtl8761b_config文件吗？是否需要rtl8761b_fw 文件？
我是在这个网站找到的文件，靠谱吗？https://github.com/Realtek-OpenSource/android_hardware_realtek/tree/rtk1395/bt/rtkbt/Firmware/BT

**Comment by ophub** [comment]
都需要

**Comment by Chuhan1112** [comment]
完蛋了，我把这里的dtb换成了https://bbs.hassbian.com/thread-18366-1-1.html 这个帖子中提供的 dtb 之后，直接开不了机了😭 开机指示灯是红色的
<img width="682" alt="截屏2023-06-29 21 58 17" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/35064712/b198bb1f-a81b-454a-a15d-d98d28ede725">

ophub 大大，还有拯救的机会吗，我纯小白😭

**Comment by ophub** [comment]
https://github.com/armbian/build/blob/173ed85da36c66b58ddc97acf74e661d9c79f573/config/sources/families/rk322x.conf#L156-L158

https://github.com/armbian/build/tree/main/packages/bsp/rk322x

在armbian的官方仓库里有这个文件。这个蓝牙驱动在我之前的固件里有，添加软连接即可测试。

https://github.com/ophub/firmware/commit/352e08648d3bdd39feaaba68064cf7629986b847

**Comment by Chuhan1112** [comment]
谢谢 o大 的耐心回复

**Comment by ophub** [comment]
你就下载今天（6.30）的s905l3a-m401a固件，写入U盘启动，然后修改 /etc/custom_service/start_service.sh文件，重启即可。正常情况下蓝牙就可以使用了。

**Comment by Chuhan1112** [comment]
> ，直接开不了机了😭 开机指示灯是红色的

o大，我现在的状况是修改 dtb 后开不了机，u盘启动后还是得手动挂载emmc吧？

**Comment by ophub** [comment]
U盘启动直接重写入emmc也可以。如果不想重新配置那些应用，就挂载emmc覆盖个dtb回去。

**Comment by Chuhan1112** [comment]
w fen4感谢  o 大 已经从u盘启动6月30日的`s905l3a-m401a`固件,成功并刷入 emmc，
<img width="907" alt="截屏2023-06-30 23 12 11" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/35064712/0dbcca4b-16fb-44e6-bb4a-1af9e54a499c">

不过 按照您的指导 将`/etc/custom_service/start_service.sh`改为： `rtk_bluetooth="yes"` 然后重启蓝牙似乎仍然未启动:

<img width="771" alt="截屏2023-06-30 23 14 16" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/35064712/5ad38e34-b00f-443c-b596-85f10746ff0c">

我是否有哪些步骤做错了？

**Comment by ophub** [comment]
armbian-config
安装蓝牙

**Comment by Chuhan1112** [comment]
似乎有奇怪的问题，明明系统有您添加的这个文件却报错：
<img width="564" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/35064712/cae9cd89-03f0-461f-87c9-8b2473e78d08">

**Comment by xcray** [comment]
> 完蛋了，我把这里的dtb换成了https://bbs.hassbian.com/thread-18366-1-1.html 这个帖子中提供的 dtb 之后，直接开不了机了😭 开机指示灯是红色的...
> ophub 大大，还有拯救的机会吗，我纯小白😭

哈哈哈，我是那个帖子的作者。
毫不谦虚的说，全网首先在armbian里把m401a/cm311盒子蓝牙用起来的就是我！这中间涉及到很多思考和试错。
值得买上那篇文章就是一个抄+拼的结果，对别人的劳动丝毫不尊重，鄙视。

dtb文件是和内核一起编译的，和内核版本、系统配置等都紧密相关，直接用很容易踩雷。
针对近期的镜像我已经更新了帖子，建议再去看看。
