### ISSUE TITLE
新增 e900v21e 型号 s905l3b mt7661rsn

### ISSUE THREAD

**Issue by jietech17** [ophub/amlogic-s9xxx-armbian#1514]
**Device Information | 设备信息**
 - SOC: [ S905L3B ]
 - Model [ E900V21E ]

**Armbian Version | 系统版本**
 - Kernel Version: [ 5.15.119 和 6.1.36 ]
 - Release: [ bullseye ]
 - 固件: [ 无语，随缘固件，自己随缘刷吧 ]
 
![2000](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/a7708a70-43f4-4ff6-b094-631007d57dcd)

**Describe the bug | 问题描述**

通过老哥的建议，

https://github.com/ophub/amlogic-s9xxx-armbian/issues/1277#issuecomment-1505347194

修改如下：

1. 使用 extlinux.conf 文件，
2. 复制一份 /boot/u-boot-s905x-s912.bin 文件，重命名为 /boot/u-boot.ext
3. 需要反编译修改 dtb 来 调整 EMMC 的工作频率，否则会找不到 EMMC 闪存，自测支持的工作频率为 50000000 和 52000000 均可。

[meson-gxl-s905l3b-e900v21e.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11905648/meson-gxl-s905l3b-e900v21e.dtb.zip)

![v225](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/a7dffe84-09b6-4856-8f8b-dff5197a9c14)

![v226](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/14fc8923-820a-4a63-a84c-69786bb41650)

![v224](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/1f29889e-54ae-417e-aae9-a9a35237e434)

![v223](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/c3302796-4940-4aa4-aea4-c658e61e6f79)

![v222](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/0160f094-2cfe-464f-b506-697e1400ad6f)

![v211](https://github.com/ophub/amlogic-s9xxx-armbian/assets/91363063/8458f3c4-0c22-47a8-9b40-cca1c89c1a96)

**Comment by jietech17** [comment]
去掉U盘后，有分配 ip 但是不在线 ？ping 不通

**Comment by ophub** [comment]
你使用的哪个dtb修改的频率？

**Comment by jietech17** [comment]
> 你使用的哪个dtb修改的频率？ meson-gxl-s905l3b-e900v22e.dtb 这个？

是的，再说了，就标题不一样，内容都是一致的，

**Comment by jietech17** [comment]
> mt7661rsn这个编号是在哪里查看呢？我看你的盒子照片上没有找到标识。
> 
> 你使用的是原𠂆安卓系统，还是先刷了一个第三方的安卓系统。
> 
> 你有这个设备的安卓系统文件吗？分享一个它的下载地址，我转存一份。

1. mt7661rsn 是设备无线芯片的型号
2. 刷的是第三方包
3. 没有原厂备份
4. 固件包链接：https://pan.quark.cn/s/97a7b5041622

**Comment by jietech17** [comment]
> 

我现在遇到点问题，去掉U盘以后，无法正常引导启动，有什么建议操作方案吗？

**Comment by ophub** [comment]
插着U盘，重启一次，再关机去掉U盘，启动测试

**Comment by jietech17** [comment]
> 我看你安装时选择的121，但是你的列表里dtb还是老的，所以你安装到emmc后使用的不是你修改过的吧，这会导致启动故障。

1. 我选121 是为了省事，直接替换了 121 dtb 文件，
2. 插着 U盘 随缘启动到 U盘，或者 emmc，不插U盘，是完全无法正常启动

**Comment by jietech17** [comment]
暂时无法解决，但是可以修改 U盘 里的
u-boot-p212.bin 或 u-boot-s905x-s912.bin 来改变引导启动

```
u-boot-p212.bin 改为 u-boot.ext 是启动到 U盘
u-boot-s905x-s912.bin 改为 u-boot.ext 是启动到 eMMC
```

U盘 就当个引导盘，

测试 flippy 内核时，出现
```
 [ ERROR ] Failed to delete partition [ 1 ]. Please try again.
```
解决方案 https://github.com/ophub/amlogic-s9xxx-armbian/issues/1375#issuecomment-1536062353
```
dd if=/dev/zero of=/dev/mmcblk2 bs=512 count=1 conv=fsync
armbian-install
```

**Comment by hailong6713** [comment]
请问：刷armbianr后无线网卡mt7661rsn可以使用吗?

**Comment by tj123** [comment]
我的为啥没有 hdmi 显示 eth0 连不上呢

**Comment by AKUYA-XYL** [comment]
通过使用 extlinux.conf 文件，修改uboot文件成功从u盘启动【Armbian_24.11.0_amlogic_s905l3b-e900v22e_noble_6.6.58_server_2024.11.01.img.gz】并成功获取到ip，但选择126安装到emmc后获取不到ip地址了，hdmi输出画面显示armbian成功启动了。请问要如何解决

**Comment by ZHJ787** [comment]
萌新，想问一下，咋刷进去，按照教程刷入了三方的安卓，当贝桌面，但是无法连接ADB也找不到办法从U盘启动，一样的型号

**Comment by cuicanmx** [comment]
成功了总结一下
##主要一定要用快点的U盘，慢U盘会卡在花屏无限重启
先制作启动u盘按照上面的
再刷这个固件

<img width="1184" height="50" alt="Image" src="https://github.com/user-attachments/assets/69c12253-3a5a-42ca-a270-a2e0fcb93142" />

然后直接用开心助手启动到U盘

<img width="1205" height="380" alt="Image" src="https://github.com/user-attachments/assets/8eb2388a-1ea8-40c9-b0e3-c57cc5112426" />

我这里总结了一个包
里面有开心助手和启动镜像
请用7-zip
飞牛分享有效期15天【e900v21e-armbian启动包.7z】，点击链接下载文件，App打开可转存到NAS：https://s.fnnas.net/s/ad7ae2cd81984cd994

密码:3912
通过网盘分享的文件：e900v21e-armbian启动包.7z
链接: https://pan.baidu.com/s/10WnWcrYmLHotGYgBXLDS9g?pwd=adzy 提取码: adzy

**Comment by hi-cui** [comment]
@cuicanmx 你这个去掉U盘，可以启动么

**Comment by mengshanab** [comment]
你们创维e900v21e   型号s905l3-b的刷成功的有没有视频教程啊，捣鼓了半天就是不行

**Comment by Satellite18111** [comment]
@mengshanab 我的e900v21e配置同Lmzaxx老哥一样，不过我是高安的。刷写的系统是四川电信创维e900v21E_高安版S905L3_安卓4.42兼容多wifi_线刷固件。我下载@cuicanmx 的提供的dtb文件，放在"G:\dtb\amlogic\meson-gxl-s905l3b-e900v21e.dtb"，然后修改了"G:\extlinux\extlinux.conf"里面的内容
label Armbian
    kernel /zImage
    initrd /uInitrd
    FDT /dtb/amlogic/meson-gxl-s905l3b-e900v21e.dtb
    append root=UUID=07dd92b8-d41d-4cc6-823b-72fb57b72b7f rootflags=data=writeback rw rootwait rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 loglevel=1 voutmode=hdmi disablehpd=false overscan=100 sdrmode=auto video=HDMI-A-1:1920x1080@60e plymouth.enable=0
开机进入安卓系统后，利用开心电视助手tf卡启动。hdmi屏幕花了一下就黑屏了，不过路由器确实出现了armbian的设备，我用putty64成功ssh登录。

**Comment by JiaHeWG** [comment]
> 成功了总结一下 ##主要一定要用快点的U盘，慢U盘会卡在花屏无限重启 先制作启动u盘按照上面的 再刷这个固件
> 
> <img alt="Image" width="1184" height="50" src="https://private-user-images.githubusercontent.com/184726727/497636657-69c12253-3a5a-42ca-a270-a2e0fcb93142.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcwNjA4MDYsIm5iZiI6MTc4NzA2MDUwNiwicGF0aCI6Ii8xODQ3MjY3MjcvNDk3NjM2NjU3LTY5YzEyMjUzLTNhNWEtNDJjYS1hMjcwLWEyZTBmY2I5MzE0Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgxOFQxMzQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mNDIzOTc0ZTFmZWNlYzg1YTg0NzliMDNkM2MzNWNmYThjZmM3MDE4YmE5MWU2NWIwODgzODE5Y2E2Njc4YjI2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.KzTB10siafyepfnPAJ97sj97gGl37kwIUKWFMYulRpY">
> 然后直接用开心助手启动到U盘
> 
> <img alt="Image" width="1205" height="380" src="https://private-user-images.githubusercontent.com/184726727/497636690-8eb2388a-1ea8-40c9-b0e3-c57cc5112426.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODcwNjA4MDYsIm5iZiI6MTc4NzA2MDUwNiwicGF0aCI6Ii8xODQ3MjY3MjcvNDk3NjM2NjkwLThlYjIzODhhLTFlYTgtNDBjOS1iMGUzLWM1N2NjNTExMjQyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwODE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDgxOFQxMzQxNDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjgwZGYzY2Q2MjIwYzY3YjEzZGFmYjZmYzg5OWRhM2JkYjIwNjdkYmFhZWIzNjQ2ZDVkYjRlYTU4ZDE0ZWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.DJrKtaKoIguNaHHBvm-2o7_61lMdBTTpZyGCO7Lrngw">
> 我这里总结了一个包 里面有开心助手和启动镜像 请用7-zip 飞牛分享有效期15天【e900v21e-armbian启动包.7z】，点击链接下载文件，App打开可转存到NAS：https://s.fnnas.net/s/ad7ae2cd81984cd994
> 
> 密码:3912 通过网盘分享的文件：e900v21e-armbian启动包.7z 链接: https://pan.baidu.com/s/10WnWcrYmLHotGYgBXLDS9g?pwd=adzy 提取码: adzy

手上有一台湖北电信版e900v21e，没看到生产日期，不是高安版，拆开发现WIFI/蓝牙位置只有空焊盘，插入u盘开机发现能够正常驱动HDMI，查询uEnv.txt发现默认dtb为m302a，于是在刷入前尝试手动切换u盘启动为e900v22e版dtb测试功能，随后发现在这个版本的dtb下读写内置eMMC会产生I/O Error错误，遂切换回m302a版并刷入时选择127选项，拔掉u盘重启正常，HDMI正常，USB无线网卡识别正常。

重启了几次发现每次重启有线网卡的MAC地址会改变，检查发现efuse里没有正确写入MAC地址，通过https://github.com/ophub/amlogic-s9xxx-armbian/issues/3076
中提到的
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#12724-%E4%BF%AE%E6%94%B9%E7%BD%91%E7%BB%9C%E8%BF%9E%E6%8E%A5-mac-%E5%9C%B0%E5%9D%80
中的方式二解决，仅供参考。
