### ISSUE TITLE
Terminal screen flickering over HDMI

### ISSUE THREAD

**Issue by sharicov** [ophub/amlogic-s9xxx-armbian#152]
Installed latest release: [Armbian_22.05.0_Aml_s905x3_focal_5.15.27_2022.03.11.0309.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_03.11.0406/Armbian_22.05.0_Aml_s905x3_focal_5.15.27_2022.03.11.0309.img.gz)
Booting from MicroSD with HDMI connected causes flickering screen (looks like wrong refresh rate).
Once again, only using terminal screen (not GUI)
Please advise

**Comment by sharicov** [comment]
![-5192737635959944728_121](https://user-images.githubusercontent.com/1933626/157825376-5e16534f-65e4-4d3e-9955-2cf87a50d223.jpg)

**Comment by sharicov** [comment]
![IMG_20220311_095103](https://user-images.githubusercontent.com/1933626/157825460-ec571428-e4ef-421d-b4e6-3b4eed9a8f4c.jpg)

**Comment by ophub** [comment]
Just lower the resolution of the monitor.

**Comment by ophub** [comment]
Reduce your monitor's resolution to fit your box's maximum resolution

**Comment by sharicov** [comment]
Do you mean in the monitor itself? I am not aware of any possibility to do
it in the linux terminal.
