### ISSUE TITLE
IP112H 启动过程提示ssh openBSD&网络问题多处

### ISSUE THREAD

**Issue by orientzane** [ophub/amlogic-s9xxx-armbian#1520]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [IP112H]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.119]
 - Release: [Armbian_23.08.0_amlogic_s905l3a_lunar_5.15.119_server_2023.07.01.img.gz]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

HDMI输出到屏幕，armbian第二次重新启动过程可观察，发现几处红色报警都是关于ssh openBSD。第一次启动时，有大量关于网络相关的红色警报，请参考我提交的UNT402A，参考其中网络错误的修复。我喜欢买大家还没提交过的产品。

root@armbian:~# service ssh status
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; preset: enabled)
    Drop-In: /etc/systemd/system/ssh.service.d
             └─00-socket.conf
     Active: active (running) since Sat 2023-07-01 13:07:50 CST; 3 days ago
TriggeredBy: ● ssh.socket
       Docs: man:sshd(8)
             man:sshd_config(5)
    Process: 1604 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
   Main PID: 1605 (sshd)
      Tasks: 1 (limit: 2013)
     Memory: 1.9M
        CPU: 327ms
     CGroup: /system.slice/ssh.service
             └─1605 "sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups"

Jul 01 13:07:50 armbian systemd[1]: Starting ssh.service - OpenBSD Secure Shell>
Jul 01 13:07:50 armbian sshd[1605]: Server listening on :: port 22.
Jul 01 13:07:50 armbian systemd[1]: Started ssh.service - OpenBSD Secure Shell >
Jul 04 20:34:30 armbian sshd[1907]: Accepted password for root from 192.168.5.2>
Jul 04 20:34:30 armbian sshd[1907]: pam_unix(sshd:session): session opened for >
Jul 04 20:34:30 armbian sshd[1907]: pam_env(sshd:session): deprecated reading o>
lines 1-22/22 (END)

我认为这一定会影响通过openSSH公钥私钥的远程访问，请O大解决

我透过iPhone蓝牙发现了一个叫MOCUTE-052Fa-AUTO的蓝牙设备，如果O大Armbian_23.08.0_amlogic_s905l3a_lunar_5.15.119_server_2023.07.01.img集成了蓝牙驱动，那大概率是驱动起来了

拍下显示器部分边框，证明HDMI输出正常
![IMG_6345](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38416895/f2d5c222-0611-455b-9ec2-4b0077afcd22)
产品底部标签：
![IMG_6346](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38416895/a6f29863-c767-4ea7-ad8b-5bbc2970d473)

root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='lunar'
MODEL_ID='304'
MODEL_NAME='E900V22C-D,CM311-1a-CH'
SOC='s905l3a'
FDTFILE='meson-g12a-s905l3a-e900v22c.dtb'
FAMILY='meson-g12a'
BOARD='s905l3a'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='5.15.119'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='uEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-e900v22c.bin'
BUILD_REPOSITORY='https://github.com/armbian/build'
REBUILD_REPOSITORY='https://github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='Calmact,KryptonLee,yu6zhou'
BUILDER_NAME='angel'
PACKAGED_DATE='2023-07-01'

现阶段，不具备写入EMMC条件，安卓9.0尚未备份固件。且此机型属于新品冷门，救砖经验欠缺。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/2656c027af0895dc5dd9d017a5ac81e174c9e443/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L32-L37

启动结束时，ssh会再重启一次，解决过程中偶尔在个别USB里无法创建sshd目录的问题，目前没有发现ssh不能使用的。

**Comment by orientzane** [comment]
O大你好：帮我解决一下蓝牙驱动问题好吗？
卖家与其他一些信息源表明该机无Wi-Fi有蓝牙。我未拆机但发现遥控器上有麦克风按钮，如图
该盒子开机，我在iPhone中发现新蓝牙硬件，前文介绍过，测试发现关机这个新蓝牙设备即消失
我安装了201，可视化界面设置中蓝牙未空。进入安卓9.0系统也没发现蓝牙设置路径
![IMG_6351](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38416895/3720c1b6-b7d4-4ffb-8fd1-cbcbd65800d9)

**Comment by ophub** [comment]
armbian-config   安装蓝牙。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

12.7.4 看看

**Comment by orientzane** [comment]
> armbian-config 安装蓝牙。
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
> 
> 12.7.4 看看

已经成功，不好意思，O大文档很完善了。让我的AirPods连接上了

**Comment by ophub** [comment]
你使用的是s905l3a的默认固件？这个设备你是第一个反馈者，我把他添加到列表里。

**Comment by orientzane** [comment]
> Armbian_23.08.0_amlogic_s905l3a_lunar_5.15.119_server_2023.07.01.img

我使用的是你这个固件。

root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='lunar'
MODEL_ID='304'
MODEL_NAME='E900V22C-D,CM311-1a-CH'
SOC='s905l3a'
FDTFILE='meson-g12a-s905l3a-e900v22c.dtb'
FAMILY='meson-g12a'
BOARD='s905l3a'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='5.15.119'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='uEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-e900v22c.bin'
BUILD_REPOSITORY='https://github.com/armbian/build'
REBUILD_REPOSITORY='https://github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='Calmact,KryptonLee,yu6zhou'
BUILDER_NAME='angel'
PACKAGED_DATE='2023-07-01'

**Comment by ophub** [comment]
好的，我把IP112H也添加到这个列表里了。

**Comment by orientzane** [comment]
> 好的，我把IP112H也添加到这个列表里了。

O大你好：你编译的固件是否默认支持采用中国产蓝牙芯片BR8041的USB适配器？

**Comment by ophub** [comment]
我网上搜了下说BR8041系列芯片兼容CSR8510和BCM20702，内核里有但是dtb里没设置，不代表可以用。

https://github.com/unifreq/linux-6.1.y/blob/8d2debd97b329928fe1f161cc7bebb66b782a1fa/drivers/bluetooth/btbcm.c#L23-L24

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/357f5cc8d01b880b95497dea41b6db3c47cf31e9/build-armbian/armbian-files/common-files/etc/model_database.conf#L62

你手动输入0，写入的是119的配置，就是cm211-1默认配置，你直接输119即可。

**Comment by orientzane** [comment]
> 我网上搜了下说BR8041系列芯片兼容CSR8510和BCM20702，内核里有但是dtb里没设置，不代表可以用。没找到firmware
> 
> https://github.com/unifreq/linux-6.1.y/blob/8d2debd97b329928fe1f161cc7bebb66b782a1fa/drivers/bluetooth/btbcm.c#L23-L24
> 
> https://github.com/armbian/firmware/tree/master/brcm

你好O大：是否我按照你文档中关于如何基于安卓.dtb，来编译有针对性的Uboot，是可以驱动板载蓝牙模块的。我前文插入USB博通蓝牙适配器成功，缺点是占用USB接口，不得已使用USB扩展坞。导致不简洁有点凌乱
经验丰富的O大，对正确基于安卓.dtb，来编译有针对性的Uboot，有什么提示吗？

**Comment by ophub** [comment]
你如果在armbian下测试，你的蓝牙可以正常识别，那就不用添加也可以，brcm正常是可以自动识别的，可以不添加。

关于编译u-boot和dts的方法我没有原创的，我使用的都是其他大佬们分享的教程，仓库里的方法是f大教我的，我也使用radxa的，也使用cm9vdA的方法。我有时会把自己使用的过程记录下来，在一些帖子里有相关的记录。你可以看看这几个。

https://github.com/ophub/amlogic-s9xxx-armbian/issues/1522

https://github.com/ophub/amlogic-s9xxx-armbian/issues/1380

https://github.com/ophub/amlogic-s9xxx-openwrt/issues/415

**Comment by BdQingSan54** [comment]
同款设备请问大佬使用的是什么安卓固件开启U盘启动的，是不是需要遥控按键或者其他操作，我怎么都不能进跑码页，求解答谢谢啦 @orientzane
