### ISSUE TITLE
晶晨 S905M-B 对应的版本是哪个

### ISSUE THREAD

**Issue by changchengyan** [ophub/amlogic-s9xxx-armbian#1524]
**Device Information | 设备信息**
 - SOC: S905M-B
 - Model  外贸盒子 GAME BOX

**Describe the bug | 问题描述**

针对上诉 cpu的 盒子 系统有单独分出来吗，我我刷了一个  网上找的  
Armbian_5.99_Aml-g12_Ubuntu_bionic_default_5.3.0_rtl8189ftv.tar.gz    且  修改uEnv.txt文件引用meson-gxbb-p201.dtb  系统引导不进来   ，也就是 安卓界面重复闪现 ，是不是 （之前 系统卡刷包有运行的游戏系统的 缘故，安卓TV系统已boot） , 看到麻烦 回复下 ，谢谢

**Comment by ophub** [comment]
没有

**Comment by changchengyan** [comment]
后期 会添加吗

**Comment by ophub** [comment]
有人反馈可以使用的配置方案就会添加

**Comment by amoslutherguo** [comment]
S905M-B 你试试s905d-p212，或者p230的dtb应该可以启动
