### ISSUE TITLE
Add wifi support to CM311-1sa ZG

### ISSUE THREAD

**Issue by tianzhuang55** [ophub/amlogic-s9xxx-armbian#1526]
**Device Information | 设备信息**
 - SOC: S905l3a
 - Model: CM311-1sa ZG

**Armbian Version | 系统版本**
 - Kernel Version: both tried
 - Release: both tried

**Describe the bug | 问题描述**
After USB boot successfully, no wlan found, and unable to configure wifi connection. I have tried both kennel and system version.

**Comment by ophub** [comment]
no driver
