### ISSUE TITLE
armbian不能挂载两块硬盘？

### ISSUE THREAD

**Issue by xiao14116** [ophub/amlogic-s9xxx-armbian#1527]
O大你好，我的盒子是cm311-1,CPU是s905l3,最近发现一个很奇怪的问题，盒子似乎不能同时通过usb接口挂载两块硬盘，只挂载一块硬盘的时候系统一点问题都不会有，但是再挂载第二块的时候就会出问题。
具体表现就是，挂载第二块硬盘以后，第一块硬盘就会自动找不到盘，然后系统就会出现一定程度的崩溃，之所以说是一定程度，是因为如果不重启系统，那还能继续使用，但是一旦重启系统，那网卡驱动就会出问题，无法连接网络。
因为我一直都拿盒子当服务器用，目前身边也没有电视，无法看到到底有没有什么错误提示。
不知道这算不算是个BUG？
有没有什么办法解决？

**Comment by ophub** [comment]
再挂就烧主板了

**Comment by xiao14116** [comment]
啊？这么严重？
我加的这块硬盘是一块3.5寸机械硬盘，独立供电，并不会使用盒子的电

**Comment by ophub** [comment]
blkid查看uuid
/etc/fstab里用uuid挂载

**Comment by xiao14116** [comment]
第一块硬盘是一个固态硬盘，用的是UUID方式挂载的，第二块硬盘是一块机械硬盘，手动命令方式挂载，

**Comment by baymax55** [comment]
我挂载了一块1t的3.5寸机械硬盘，没有独立供电，不稳定，会出现磁盘挂载后找不到现象

**Comment by xiao14116** [comment]
> 我挂载了一块1t的2.5寸机械硬盘，没有独立供电，不稳定，会出现磁盘挂载后找不到现象

机械硬盘需要的是12V供电，而usb口只有5V的电压，带不动机械硬盘
