### ISSUE TITLE
e900v22c无线驱动

### ISSUE THREAD

**Issue by Svenmax** [ophub/amlogic-s9xxx-armbian#1528]
**Device Information | 设备信息**
 - SOC: S095l3a-b
 - Model：e900v22c

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
大佬好，我看隔壁ce已经可以驱动紫光的无线网卡了，请问armbian或者openwrt什么时候有机会驱动，感谢

**Comment by ophub** [comment]
ce是安卓系统，理论上所有安卓电视盒子的都可以驱动。armbian使用主线内核，盒子厂家不开源驱动的也许都支持不了。

如果必须使用无线，建议使用支持armbian的开发版，例如瑞莎5b，香蕉派等，可以自己加装受支持的无线网卡。

**Comment by Svenmax** [comment]
原来如此，感谢大佬。
