### ISSUE TITLE
[feature request]功能：根据已有dtb或者安卓固件，生成u-boot

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-armbian#1529]
希望有这个功能的原因：1.  https://github.com/ophub/amlogic-s9xxx-armbian/issues/732#issuecomment-1328064847
2.  我认为，出现多种毛病的原因是：存在多种安卓底包、多种安卓bootloader。https://github.com/ophub/amlogic-s9xxx-armbian/issues/610#issuecomment-1275446502

BTW，作者老哥，我看到有些安卓系统包标有【已root】【可远程adb】，在这种安卓上刷linux会不会有后门？

**Comment by univerioiln233** [comment]
@ophub

**Comment by univerioiln233** [comment]
@R6400
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1399
我很早就反馈过这样一种情况：无法引导进入系统，同时，若插上键盘，再断电重启，变得可以进系统。
https://github.com/ophub/amlogic-s9xxx-armbian/issues/612#issue-1401861331
现在看来，改成：无法引导进入系统，同时，若插上usb2.0规格的键盘，再断电重启，变得可以进系统。

**Comment by univerioiln233** [comment]
看到一个issue 安装了红帽系linux。我也希望用红帽系，苦于没教程 哈哈哈。https://github.com/ophub/amlogic-s9xxx-armbian/issues/1472 @Alvin1986 @a520ass

**Comment by univerioiln233** [comment]
我看最近还有人问刷入emmc后，怎么再从u盘启动？https://github.com/ophub/amlogic-s9xxx-armbian/issues/606#issue-1401789051之前也问过，请问各位，现在解决了吗

**Comment by ophub** [comment]
如果不能从USB启动，把EMMC里的/boot/boot.src 改个名字，再启动就无法从emmc启动了，插入usb就从usb启动了。如果想恢复emmc的系统，从usb挂载emmc的boot后，恢复这个文件的名字，拔了usb再重启即可。

**Comment by Yxini** [comment]
> 如果不能从USB启动，把EMMC里的/boot/boot.src 改个名字，再启动就无法从emmc启动了，插入usb就从usb启动了。 如果想恢复emmc的系统，从usb挂载emmc的boot后，恢复这个文件的名字，拔了usb再重启即可。

终于找到解决方法了，我也是M410A，我最近发现就是写入EMMC后，就没法U盘启动。
