### ISSUE TITLE
Support for Cdtech 4761743 WiFi/BT

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#153]
My X96 Air has a Cdtech 4761743 WiFi chip that isn't recognised by s9xxx armbian

Don't quote me but I think it might be a clone of the Qualcomm QCA6174A-3.

CoreElec has working support for this chip but I've not been able to find the patches in their repo yet but the code is out there.

https://github.com/CoreELEC/CoreELEC

This article might help

https://blog.csdn.net/u012851408/article/details/86605778

**Comment by ophub** [comment]
Need to support the driver used by the mainline kernel, the Android driver cannot be used in the mainline kernel.

**Comment by danboid** [comment]
Yes, my mistake! I thought coreelec was using a mainline kernel but its using the amlogic kernel.

https://discourse.coreelec.org/t/linux-kernel-faq-and-discussion/14870/8

**Comment by ophub** [comment]
The main market of the box is Android TV, so the drivers in the Android system are relatively complete. But these Android-specific drivers are not available in the mainline kernel.
