### ISSUE TITLE
N1刷后死活装不了桌面系统，请O大帮忙解惑

### ISSUE THREAD

**Issue by lamhui** [ophub/amlogic-s9xxx-armbian#1530]
O大，刚接触armbian，请教一下我也是N1的机子下了网页**Armbian_23.08.0_amlogic_s905d_lunar_6.1.36_server_2023.07.01.img.gz**固件刷U盘启动后全部按照操作更新内核也获取权限（sudo -i）了然后armbian-software要安装桌面系统（Desktop 201项）经过漫长的跑码之后貌似机器自动重启然后依旧还是在第一次未登录系统的画面下遂登录系统继续以上操作然后armbian-software列表中看到desktop 201选项中STATE是not-installed然后我又试了**Armbian_23.08.0_amlogic_s905d_lunar_5.15.119_server_2023.07.01.img.gz**固件也是一样情况。请问这是什么原因呢？我已经折腾了好几天了，麻烦看到给解惑指点一下。感谢！

**Comment by ophub** [comment]
安装过程中选择了哪个选项？选gdm3

lunar我一个月前测试过桌面可以正常安装

**Comment by lamhui** [comment]
> 安装过程中选择了哪个选项？选gdm3
> 
> lunar我一个月前测试过桌面可以正常安装

小白不懂你指的是哪个？我把我整个过程说一下吧。
写完U盘启动后，配置基本参数创建用户名和密码。然后就armbian-update(过程中有时候能顺利更新有时候不能顺利更新)，然后更新完后机器自动重启到未登录命令操作界面然后继续账户名密码登录然后就是sudo -i取得权限然后就是armbian-software跑完一堆代码后让我选选项，选了201(desktop)然后就是漫长的跑代码中间停顿一次提示是否安装中文桌面之类的选Y然后就是继续漫长跑代码完事之后就是像之前一样又是重启到未登录命令操作的那个界面下，而我再用armbian-software桌面201项(desktop)那个state还是显示not-installed。我不懂这中间哪里出错了还是漏了什么，因为是小白第一次接触这个所以懂的就这么多而已了，见谅！

**Comment by ophub** [comment]
如果armbian-update不能正常使用，说明你访问github.com不稳定，这在安装桌面及其他软件时都会有概率失败。
hdmi显示器也没看到桌面？

**Comment by ophub** [comment]
所有的资源都不在国内

**Comment by OortNebula** [comment]
> O大，刚接触armbian，请教一下我也是N1的机子下了网页**Armbian_23.08.0_amlogic_s905d_lunar_6.1.36_server_2023.07.01.img.gz**固件刷U盘启动后全部按照操作更新内核也获取权限（sudo -i）了然后armbian-software要安装桌面系统（Desktop 201项）经过漫长的跑码之后貌似机器自动重启然后依旧还是在第一次未登录系统的画面下遂登录系统继续以上操作然后armbian-software列表中看到desktop 201选项中STATE是not-install然后我又试了**Armbian_23.08.0_amlogic_s905d_lunar_5.15.119_server_2023.07.01.img.gz**固件也是一样的情况。请问这是什么原因呢？我已经折腾了好几天了，麻烦看到给解惑指点一下。感谢！

看下lightdm服务是不是报错了没起来？可以执行下这个重启看看
cat << '_EOF_' > /etc/X11/xorg.conf.d/02-dietpi-aml-s905.conf
Section "OutputClass"
    Identifier "Amlogic"
    MatchDriver "meson"
    Driver "modesetting"
    Option "PrimaryGPU" "true"
EndSection
Section "Screen"
    Identifier "Default Screen"
    Device "Meson"
    Monitor "foo"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
    EndSubSection
EndSection
_EOF_

**Comment by rqi14** [comment]
> 所有的资源都不在国内

你好，请问我第一次安装这个201 desktop的时候选错成lightdm，卸载后重新安装不出这个lightdm和gdm3的选项了怎么办？😂
