### ISSUE TITLE
s905l3启动异常

### ISSUE THREAD

**Issue by knbnaz** [ophub/amlogic-s9xxx-armbian#1531]
在命令行输入reboot后，能启动但无法识别网络，这个盒子也没有hdmi输出
Armbian_23.08.0_amlogic_s905l3a-m401a_jammy_5.15.119_server_2023.07.01为系统版本

**Comment by ophub** [comment]
标题说无法启动。
正文说reboot能启动但无法识别网络。

没有hdmi的情况下，你怎么判断是能启动但无法识别网络呢？

你是想反馈说s905l3a这个固件在所有的相关设备里都无法使用？

你用的什么设备？选择的固件是否正确？

你是USB测试的还是写入emmc测试的？

你是初次选择固件找合适的？还是用了一段时间后reboot了有问题？

reboot前做的什么事？更新内核后自动reboot的还是闲着没事重启了一下想测试什么呢？

你提问时有没有看到提问模版让你填写机器、内核版本、系统版本、祥细描述问题并在无法文字表达清楚时把截图或者日志发一下？

你这么问，大家怎么猜呢？

**Comment by knbnaz** [comment]
> 标题说无法启动。 正文说reboot能启动但无法识别网络。
> 
> 没有hdmi的情况下，你怎么判断是能启动但无法识别网络呢？
> 
> 你是想反馈说s905l3a这个固件在所有的相关设备里都无法使用？
> 
> 你用的什么设备？选择的固件是否正确？
> 
> 你是USB测试的还是写入emmc测试的？
> 
> 你是初次选择固件找合适的？还是用了一段时间后reboot了有问题？
> 
> reboot前做的什么事？更新内核后自动reboot的还是闲着没事重启了一下想测试什么呢？
> 
> 你提问时有没有看到提问模版让你填写机器、内核版本、系统版本、祥细描述问题并在无法文字表达清楚时把截图或者日志发一下？
> 
> 你这么问，大家怎么猜呢？

我部署的docker应用我为了确保成功，我输入了reboot，然后我尝试插拔电源，机顶盒灯亮了，说明启动成功，但是路由器并不显示设备，换网线换网口都试过了。
然后我尝试重新在emmc安装armbian，我尝试使用的最新的S905L3a版本，然后我核对后发现，这个机器为S905L3，我之前安装的也是S905L3固件，我及时更正u盘烧录的版本后，但还是很遗憾
但u盘启动失败，由于没有hdmi输出，我无法看到任何报错

**Comment by ophub** [comment]
用晶晨线刷工具，把你盒子的安卓系统线刷回去可以恢复系统

**Comment by xiao14116** [comment]
我这里也有过这种问题，如果使用reboot或者shutdown -r这样的命令重启盒子，就会出现系统获取不到IP情况，连接在交换机上的灯不亮，同样也是cm311-1的盒子。
但是用poweroff关机，然后断电，再重新加电就能正常获取IP。
反复试验过多次，都是这种情况，很神奇的BUG。
另外求教一下老大，安装了6.x的系统以后想要降级到5.x该怎么做？
也需要先线刷会安卓系统吗？

**Comment by xiao14116** [comment]
> 装docker时修改过网络设置没？用晶晨线刷工具，把你盒子的安卓系统线刷回去可以恢复系统

我这里也有过这种问题，如果使用reboot或者shutdown -r这样的命令重启盒子，就会出现系统获取不到IP情况，连接在交换机上的灯不亮，同样也是cm311-1的盒子。
但是用poweroff关机，然后断电，再重新加电就能正常获取IP。
反复试验过多次，都是这种情况，很神奇的BUG。
另外求教一下老大，安装了6.x的系统以后想要降级到5.x该怎么做？
也需要先线刷会安卓系统吗？

**Comment by ophub** [comment]
armbian-update -k 5.4

支持的内核系列可以互换使用，版本可以任意更换

**Comment by xdogrun** [comment]
X96MAX+也是这样，最新固件
