### ISSUE TITLE
请问amlogic 8726-MX-D会被支持吗？或者有人尝试移植到这个平台上吗？

### ISSUE THREAD

**Issue by lvxingye** [ophub/amlogic-s9xxx-armbian#1532]

**Comment by lvxingye** [comment]
我这个是小米盒子1s，cpu8726mxd，网卡是ap6330的

**Comment by rikka0w0** [comment]
类似的机器有LeTV C1S，拆解可见http://bbs.mydigit.cn/read.php?tid=845037

这款SoC好像很少有被支持的

这是我唯一能找到的OpenElec支持这款SoC的固件https://forum.libreelec.tv/thread/4858-9-0-0-libreelec-builds-for-mx2-g18/
