### ISSUE TITLE
请问怎么获取Ubuntu 20.04的img，用于本地编译固件

### ISSUE THREAD

**Issue by hoyzhang** [ophub/amlogic-s9xxx-armbian#1534]
O大，您好！现在的releases里面，img都是最新的，例如Armbian_23.08.0-trunk_6.1.36.img
我想找一个之前版本的img，用于本地编译ubuntu 20.04(focal)的固件，名称应该类似于Armbian_21.02.1-trunk_5.15.50.img，
请问哪里可以下载到旧版的img呢？
谢谢！

**Comment by ophub** [comment]
https://armbian.tnahosting.net/dl/

这是官方下载站，我看了一下也没旧版了。

**Comment by hoyzhang** [comment]
> https://armbian.tnahosting.net/dl/
> 
> 这是官方下载站，我看了一下也没旧版了。

这里好像有一些，例如Armbian_21.05.1_Kvim1_focal_current_5.10.34.img.xz
但是没有trunk的。不知能不能用？
https://armbian.tnahosting.net/archive/khadas-vim1/archive/

**Comment by hoyzhang** [comment]
下载了改成trunk，执行rebuild，最后提示如下：

```
[ STEPS ] Start building Armbian...
(1.1) Start building Armbian [ s905lb-r3300l - flippy/5.10.180 ]. Remaining space is 355G.
 [🌿] (1/7) Extract armbian files.
 [🌿] (2/7) Make new armbian image.
 [🌿] (3/7) Copy the Armbian files.
 [🌿] (4/7) Replace kernel files.
 [💔] The 4 kernel missing.

```

**Comment by ophub** [comment]
缺内核，看前面点的日志，内核没从github下载下来吧。

**Comment by hoyzhang** [comment]
> 缺内核，看前面点的日志，内核没从github下载下来吧。

我看到rebuild脚本里面，有检查header，这个文件的确不存在。
但是，我手动从github/kernel里面下载/kernel_flippy/5.10.180.tar.gz
里面也没有header文件。

而这个header，在5.15.120的文件夹里面是有的。

**Comment by ophub** [comment]
kernel_flippy 里的5.15和6.1是flippy编译并分享的。
另外的5.4和5.10是从 https://github.com/breakings/OpenWrt/releases/tag/kernel_stable 这下载转存的。这个仓库的管理员是flippy社区的管理员，他使用flippy的源码自己编译的。

我以前没测试这个，感谢你的提示，我删除5.4和5.10的内核吧，省的大家引用编译时因为缺少header而报错。
