### ISSUE TITLE
Error starting userland proxy: listen udp4 0.0.0.0:1900: bind: address already in use

### ISSUE THREAD

**Issue by baymax55** [ophub/amlogic-s9xxx-armbian#1535]
**Device Information | 设备信息**
 - cm311-la

**Armbian Version | 系统版本**
 - Kernel-Version:  5.15.120
 - Release: jammy
 

**Describe the bug | 问题描述**

在使用内置的安装软件homeassistant 和jellyfin时,使用docker先启动homeassistant ,会占用udp 1900端口,再启动jellyfin会报端口占用,请问如何解决,或者是否支持端口自定义.

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/35788491/fa27892e-f0fa-48f7-8bb1-c96c1d2f0ff3)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/35788491/89905cb5-d618-4425-8bcd-76da9178db85)

**Comment by ophub** [comment]
docker都支持自定义端口，你把docker命令冒号左侧的端口自定义一个不冲突的。

docker run -d -p 9999:1900 --restart=always

**Comment by baymax55** [comment]
> docker都支持自定义端口，你把docker命令冒号左侧的端口自定义一个不冲突的。
> 
> docker run -d -p 9999:1900 --restart=always

好的
