### ISSUE TITLE
章鱼星球刷ARMBIAN后再刷OP不能启动

### ISSUE THREAD

**Issue by alegoho** [ophub/amlogic-s9xxx-armbian#1536]
**Device Information | 设备信息**
 - SOC: [e.g. S912]
 - Model [e.g. 章鱼星球 XQ2345-1 银色]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.38]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
你好！我这个应该是原版的章鱼星球，一年前刷了F大的OP固件版本忘记了，大概68+左右吧，是给朋友用的，最近朋友换了设备我拿回来，然后刷了你的ARMBIAN bullseye_6.1.38 以为安装PVE的，但无论如何PVE最后还是出错，搞了一个下午，无耐放弃，刷回F大的OP，然后问题就出现了，无论是你的，还是F大的，还是老哥的OP都能U盘启动，但刷到EMMC后所有OP都不能启动，接HDMI黑屏，什么也没有显示，SSH上去用命令和晶晨宝盒我都试过了！最后我刷了68+的版本还是一样！但刷你的ARMBIAN到EMMC是能启动的，我从中午搞到现在实在没办法才上来求助！

**Comment by ophub** [comment]
山寨章鱼从外壳看不出来，仿的一模一样。如果不想拆机，可以刷山寨的固件试试。

也可以线刷安卓系统，再刷op

**Comment by ophub** [comment]
armbian和op的/boot完全相同，共用的源码，两个仓库都是开源的，bl相同，如果是bl的问题就armbian也启动不了。

**Comment by alegoho** [comment]
> armbian和op的/boot完全相同，共用的源码，两个仓库都是开源的，bl相同，如果是bl的问题就armbian也启动不了。

我也奇怪，刷了个ARMBIAN就不能刷OP了

刚才我去恩山搜了一下，有个贴有介绍他刷机，然后我刷了那个S912安卓精简线刷，再进安卓里面启动到U盘，然后刷F大的固件，成功从EMMC启动了，OP问题解决了，PVE问题不想在章鱼上搞了

**Comment by ophub** [comment]
把你刷的这个章鱼的安卓系统分享一下下载链接，我转存一个

**Comment by alegoho** [comment]
> 把你刷的这个章鱼的安卓系统分享一下下载链接，我转存一个

找了好久，后面找到了，但忘记在那个论坛找到的，只有百度网盘连接，没有提取码，还好我保存到我的网盘

链接: https://pan.baidu.com/s/1KR14YrSkTzrESshF4DJLPg 提取码: a9ci 复制这段内容后打开百度网盘手机App，操作更方便哦


说明一下，这个是线刷的S912精简安卓，我在章鱼星球上可以用，其他的S912我没有测试过！

**Comment by ophub** [comment]
我转存到了 https://github.com/ophub/kernel/releases/tag/tools

**Comment by pkl173** [comment]
我也遇到了这个问题，从Armbian转OP，能从U盘启动，但是刷入EMMC后启动黑屏，网卡灯亮百兆，没正常启动。之后我通过先线刷安卓TV固件，https://www.znds.com/tv-1204967-1-1.html。然后安装APP，从U盘启动，再刷入EMMC，就能正常启动OP了

**Comment by ophub** [comment]
多谢分享，我转到了： https://github.com/ophub/kernel/releases/tag/tools

[android_tv_s912.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_s912.tar.xz)
