### ISSUE TITLE
How to enable multi color of terminal color scheme with the kernel 5.4

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#154]
I'm using X96max+ (2+16G, 100Mb) with kernel 5.4. There is a strange point that the terminal color scheme is only mono color.
<img width="452" alt="Screen Shot 2022-03-11 at 22 06 37" src="https://user-images.githubusercontent.com/22479095/157894105-35b5ca0b-b41c-41a3-896f-61e64b50b699.png">
Note: I select bash after the first time login.

As I checked with kernel 5.15 before, the color scheme also supports multi colors. For example, the executable file should be green color etc.

Is there a way to enable multi color of terminal color scheme?

Thank you.

**Comment by ophub** [comment]
```
echo '[[ "${SHELL}" == *bash && -f "${HOME}/.bashrc" ]] && . ${HOME}/.bashrc' >>/etc/profile
sync && reboot
```

**Comment by dinhchinh82** [comment]
> ```
> echo '[[ "${SHELL}" == *bash && -f "${HOME}/.bashrc" ]] && . ${HOME}/.bashrc' >>/etc/profile
> sync && reboot
> ```

It works well. Thank you very much.
