### ISSUE TITLE
魔百盒M301A,JL代工,刷入E900v21e bullseye_5.15.119_server_2023.07.01成功，然而有线网络连接失败

### ISSUE THREAD

**Issue by Lunar24601** [ophub/amlogic-s9xxx-armbian#1541]
设备信息
 - SOC: [S095  l2]
 - Model [M301A JL代工]

**Armbian Version | 系统版本
 - Kernel Version: [5.15.119]
![IMG_20230713_171434](https://github.com/ophub/amlogic-s9xxx-armbian/assets/139452490/2f376b1d-678a-4b42-8d5d-65144e9b999f)

 - Release: [bullseye]

**Describe the bug | 问题描述**
您好，魔百盒m301a刷上armbian系统，网关有ip地址，然而armbian-software命令上不去，提示没有网，怀疑是nmtui没有输入mac地址再试然而无果，还一直在弹出错误
我该怎么办，谢谢！

**Comment by ophub** [comment]
试试先刷个安卓9，再刷armbian

**Comment by Lunar24601** [comment]
成功解决，然而不是盒子问题，先把我设置的mac删掉，然后插上一个刷好的armbian优盘，然后重点：插上我的可联网电脑网线，然后可以用了！奇怪的是我插到光猫另一个端口却不能用，然后反复尝试换端口终于找到两个可用的网线端口，判断是光猫坏了

**Comment by Lunar24601** [comment]
成功解决，然而不是盒子问题，先把我设置的mac删掉，然后插上一个刷好的armbian优盘，然后重点：插上我的可联网电脑网线，然后可以用了！奇怪的是我插到光猫另一个端口却不能用，然后反复尝试换端口终于找到两个可用的网线端口，判断是光猫坏了

**Comment by qq2107287671** [comment]
> 试试先刷个安卓9，再刷armbian

请问一下用u盘启动 原系统也对U盘启动有影响吗

**Comment by ophub** [comment]
emmc里面的系统对USB启动有直接影响，用到他的bootloader 引导

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools
