### ISSUE TITLE
N1刷armbian，密码设置的1234，过几天发现登录不上了，提示密码错误，难道armbian密码会自动变化吗？

### ISSUE THREAD

**Issue by zjcolvin** [ophub/amlogic-s9xxx-armbian#1548]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by zjcolvin** [comment]
https://www.right.com.cn/forum/thread-8272987-1-1.html
恩山无线有人和我一样的问题，说明不是偶然，不知道问题出在哪里

**Comment by ophub** [comment]
默认密码是1234，首次登陆要求你修改，且必须是混合型密码，如果是1234会提示不合格重新输入，所以你安装好的密码不会是1234

**Comment by zjcolvin** [comment]
但是我一直输入的就是1234，我很肯定

**Comment by imzlh** [comment]
我有同感，之前初次使用s905l3a的固件包时安装只开了一个root用户，然后过几天(大概重启很多次了)就出现了root始终登不上。
之后有了教训安装时添加了一个普通账户。当时是u盘启动修改/etc/shadow增加账户才登上的，大概是系统自动封锁root?
的确root账户很危险，比如`rm -rf .*`看起来没问题...

**Comment by zhuguoqing123** [comment]
> 我有同感，之前初次使用s905l3a的固件包时安装只开了一个root用户，然后过几天(大概重启很多次了)就出现了root始终登不上。 之后有了教训安装时添加了一个普通账户。当时是u盘启动修改/etc/shadow增加账户才登上的，大概是系统自动封锁root? 的确root账户很危险，比如`rm -rf .*`看起来没问题...

你好，那么我如何才能登上我的账户呢，密码变了

**Comment by imzlh** [comment]
> > 我有同感，之前初次使用s905l3a的固件包时安装只开了一个root用户，然后过几天(大概重启很多次了)就出现了root始终登不上。 之后有了教训安装时添加了一个普通账户。当时是u盘启动修改/etc/shadow增加账户才登上的，大概是系统自动封锁root? 的确root账户很危险，比如`rm -rf .*`看起来没问题...
> 
> 你好，那么我如何才能登上我的账户呢，密码变了

那只能尝试U盘启动，chroot增加用户和添加sudo权限，网上应该有教程
我是这么干的
