### ISSUE TITLE
请求适配华北工控emb 3531 有uboot dts

### ISSUE THREAD

**Issue by rongchuan17** [ophub/amlogic-s9xxx-armbian#1549]
**Device Information | 设备信息**
 - SOC:rk3399
 - Model emb3531

[ 官方wiki](http://android1.norco.com.cn:7070/index.php/EMB-3531)
已有第三方armbian: https://pan.baidu.com/s/1BF4HaJpLcQ83BZPh8V2Tig 提取码: 84fp 
在 /usr/lib 中提取了uboot 
[uboot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12063110/uboot.zip)

dtb文件：
[Uploading rk3399-emb3531.zip…]()

**Comment by rongchuan17** [comment]
自己fork，编译通过，可以用了

**Comment by ophub** [comment]
感谢分享，你的pull已经合并。

**Comment by rongchuan17** [comment]
感谢诸位开源大佬们的无私奉献！

**Comment by fan0312** [comment]
这个还是同样的问题，不能reboot，估计是提取的uboot问题

> **设备信息| 设备信息**
> 
> * 芯片：rk3399
> * 型号 emb3531
> 
> [官方wiki](http://android1.norco.com.cn:7070/index.php/EMB-3531) 已有第三方armbian：https://pan.baidu.com/s/1BF4HaJpLcQ83BZPh8V2Tig提取码：84fp 在/usr/lib中提取了uboot [uboot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12063110/uboot.zip)
> 
> dtb文件： 正在上传rk3399-emb3531.zip…

这个第三方的armbian，也是不可以reboot的。

**Comment by bbggoo** [comment]
这个dts出错很少，目前刷完后有问题，kernel启动阶段后会随机启动失败
U-Boot 2022.04-armbian (Jun 22 2022 - 07:16:35 +0000)

SoC: Rockchip rk3399
Reset cause: POR
Model: FriendlyElec NanoPC-T4
DRAM:  2 GiB
PMIC:  RK808 
Core:  280 devices, 26 uclasses, devicetree: separate
MMC:   mmc@fe310000: 3, mmc@fe320000: 1, mmc@fe330000: 0
Loading Environment from MMC... *** Warning - bad CRC, using default environment

In:    serial
Out:   serial
Err:   serial
Model: FriendlyElec NanoPC-T4
Net:   eth0: ethernet@fe300000
Hit any key to stop autoboot:  0 
starting USB...
Bus usb@fe380000: USB EHCI 1.00
Bus usb@fe3c0000: USB EHCI 1.00
Bus usb@fe900000: Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
scanning bus usb@fe380000 for devices... 1 USB Device(s) found
scanning bus usb@fe3c0000 for devices... 1 USB Device(s) found
scanning bus usb@fe900000 for devices... 3 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device
Card did not respond to voltage select! : -110
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
3252 bytes read in 12 ms (264.6 KiB/s)
## Executing script at 00500000
Boot script loaded from mmc 0
268 bytes read in 8 ms (32.2 KiB/s)
16849991 bytes read in 1611 ms (10 MiB/s)
33325568 bytes read in 3165 ms (10 MiB/s)
79248 bytes read in 25 ms (3 MiB/s)
Failed to load '/dtb/rockchip/overlay/rk3399-fixup.scr'
Unknown command 'kaslrseed' - try 'help'
Moving Image from 0x2080000 to 0x2200000, end=42b0000
## Loading init Ramdisk from Legacy Image at 06000000 ...
   Image Name:   uInitrd
   Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
   Data Size:    16849927 Bytes = 16.1 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Ramdisk to 78efb000, end 79f0cc07 ... OK
   Loading Device Tree to 0000000078e7f000, end 0000000078efafff ... OK

Starting kernel ...

**Comment by gzx7301** [comment]
您好 我想询问在内核6.1.11版本中 解决了RKMPP的问题吗 我在内核6.1.92版本中没有相关驱动 也没有发现相关设备

**Comment by WlphM** [comment]
> 您好 我想询问在内核6.1.11版本中 解决了RKMPP的问题吗 我在内核6.1.92版本中没有相关驱动 也没有发现相关设备

解决了吗

**Comment by gzx7301** [comment]
> > 您好 我想询问在内核6.1.11版本中 解决了RKMPP的问题吗 我在内核6.1.92版本中没有相关驱动 也没有发现相关设备
> 
> 解决了吗
我替换了一个朋友给我的DTB文件 然后编译了rockschips/mpp后 似乎解决了 我目前只测试了jellyfin是可以正常硬解
[rk3399-emb3531.zip](https://github.com/user-attachments/files/17246616/rk3399-emb3531.zip)

**Comment by WlphM** [comment]
> > > 您好 我想询问在内核6.1.11版本中 解决了RKMPP的问题吗 我在内核6.1.92版本中没有相关驱动 也没有发现相关设备
> > 
> > 
> > 解决了吗
> 
> 我替换了一个朋友给我的DTB文件 然后编译并安装 rockschips/mpp 后 似乎解决了 我目前只测试了 jellyfin 是可以正常硬解 [rk3399-emb3531.zip](https://github.com/user-attachments/files/17246616/rk3399-emb3531.zip)

好的非常感谢，麻烦再问一下，我看rockschips/mpp 4月份已经更新了介绍说是支持h.265，所以想问下在jellyfin上试过可以支持h.265吗

**Comment by bailiang27** [comment]
这个板子不支持SD卡启动，我想知道下，各位大佬是怎么启动这个镜像的啊？

**Comment by lpfxh** [comment]
4G模块可以驱动吗，有驱动成功的记录吗

**Comment by kitkit210** [comment]
有成功啟用過GUI 的嗎?

**Comment by whmzsu** [comment]
> 这个板子不支持SD卡启动，我想知道下，各位大佬是怎么启动这个镜像的啊？

maskrom或者loader模式烧录

**Comment by bk3a12** [comment]
> 这个板子不支持SD卡启动，我想知道下，各位大佬是怎么启动这个镜像的啊？

https://github.com/ophub/amlogic-s9xxx-armbian/issues/3198#issuecomment-3568810371

**Comment by bk3a12** [comment]
https://github.com/bk3a12/emb3531

**Comment by yifengyou** [comment]
请问，各位的pcie支持正常么？

测试了
Armbian_26.02.0_rockchip_emb3531_trixie_6.1.160_server_2026.01.15.img


```shell
root@armbian:~# dmesg |grep -i pci
[    0.009392] PCI/MSI: /interrupt-controller@fee00000/interrupt-controller@fee20000 domain created
[    0.733425] PCI: CLS 0 bytes, default 64
[    0.925843] rockchip-pcie f8000000.pcie: host bridge /pcie@f8000000 ranges:
[    0.925886] rockchip-pcie f8000000.pcie:      MEM 0x00fa000000..0x00fbdfffff -> 0x00fa000000
[    0.925907] rockchip-pcie f8000000.pcie:       IO 0x00fbe00000..0x00fbefffff -> 0x00fbe00000
[    0.926469] rockchip-pcie f8000000.pcie: no vpcie12v regulator found
[    0.926488] rockchip-pcie f8000000.pcie: no vpcie3v3 regulator found
[    0.926505] rockchip-pcie f8000000.pcie: supply vpcie1v8 not found, using dummy regulator
[    0.926657] rockchip-pcie f8000000.pcie: supply vpcie0v9 not found, using dummy regulator
[    1.713799] rockchip-pcie f8000000.pcie: PCIe link training gen1 timeout!
[    1.713838] rockchip-pcie: probe of f8000000.pcie failed with error -110
root@armbian:~#
```

**Comment by zhangbin0026** [comment]
在飞牛下
1.**SD卡热拔插，不识别**，重启识别后不能操作（新增存储空间，挂载存储空间操作都是失败）；
2.**pcie仅能识别m2硬盘**，功能正常。测试pcie转8口sata不识别（asm1061芯片），查看log
```
root@EMB3531:~# sudo dmesg | grep -i pci
[    0.174898] /pcie@f8000000: Fixed dependency cycle(s) with /pcie@f8000000/interrupt-controller
[    0.955131] PCI: CLS 0 bytes, default 64
[    1.231915] rockchip-pcie f8000000.pcie: host bridge /pcie@f8000000 ranges:
[    1.232198] rockchip-pcie f8000000.pcie:      MEM 0x00fa000000..0x00fbdfffff -> 0x00fa000000
[    1.232259] rockchip-pcie f8000000.pcie:       IO 0x00fbe00000..0x00fbefffff -> 0x00fbe00000
[    1.233695] rockchip-pcie f8000000.pcie: no vpcie12v regulator found
[    1.233747] rockchip-pcie f8000000.pcie: no vpcie3v3 regulator found
[    1.233787] rockchip-pcie f8000000.pcie: supply vpcie1v8 not found, using dummy regulator
[    1.234101] rockchip-pcie f8000000.pcie: supply vpcie0v9 not found, using dummy regulator
[    1.986599] rockchip-pcie f8000000.pcie: PCIe link training gen1 timeout!
[    1.986758] rockchip-pcie f8000000.pcie: probe with driver rockchip-pcie failed with error -110
root@EMB3531:~#
``` 
AI说是：1. 电源问题（最最常见）
从日志看，系统没有找到关键的 PCIe 电源稳压器
另外测试pcie转m2，再m2转5sata扩展也不成功
烦请大佬帮忙修改dts，感谢！

**Comment by ybsong** [comment]
sd卡识别为 mmcblk1 内置emmc为mmcblk2，是不是刷armbian，卡里放飞牛，就自动启动tf卡里的飞牛呢？  另外飞牛默认不能用装应用到16g的内置里，能不能分8g左右装应用用？ 或者把应用装到sd卡？
