### ISSUE TITLE
[ Error ] s905x3 have no the 5.10 kernel u-boot file: [  ]

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#155]
Run sudo chmod +x rebuild
  sudo chmod +x rebuild
  sudo ./rebuild -d 
  cd build/output/images/ && sudo gzip *.img && sync
  echo "FILEPATH=$PWD" >> $GITHUB_ENV
  echo "FILE_DATE=$(date +"%m.%d.%H%M")" >> $GITHUB_ENV
  echo "::set-output name=status::success"
  shell: /usr/bin/bash -e {0}
  env:
    TZ: Europe/Lisbon
    COMPILE_STARTINGTIME: 03.11.[2](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:2)117
    ARMBIAN_RELEASE: focal
    ARMBIAN_BOARD: lepotato
Welcome to Rebuild Armbian for Amlogic s9xxx tv box!
Server CPU configuration information: 
      2  Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz 

Server memory usage: 
              total        used        free      shared  buff/cache   available
Mem:          6.8Gi       640Mi       2.2Gi       9.0Mi       4.0Gi       5.8Gi
Swap:         4.0Gi       0.0Ki       4.0Gi 

Server space usage before starting to compile: 
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/root      ext4   84G   5[3](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:3)G   31G  6[4](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:4)% / 

Armbian rebuild file: [ Armbian_22.0[5](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:5).0-trunk_Lepotato_focal_current_5.10.105_minimal.img ], Version: [ 22.05.0 ]
(1) Auto query the latest kernel version of the same series for [ 5.15.25 ]
(1) [ 5.15.28 ] is latest kernel. 

(1) [ 5.15.28 ] Kernel loading from [ https://github.com/ophub/kernel/trunk/pub/stable/5.15.28 ]
A    build-armbian/amlogic-kernel/5.15.28
A    build-armbian/amlogic-kernel/5.15.28/boot-5.15.28-flippy-70+.tar.gz
A    build-armbian/amlogic-kernel/5.15.28/dtb-allwinner-5.15.28-flippy-70+.tar.gz
A    build-armbian/amlogic-kernel/5.15.28/dtb-amlogic-5.15.28-flippy-70+.tar.gz
A    build-armbian/amlogic-kernel/5.15.28/dtb-rockchip-5.15.28-flippy-70+.tar.gz
A    build-armbian/amlogic-kernel/5.15.28/header-5.15.28-flippy-70+.tar.gz
A    build-armbian/amlogic-kernel/5.15.28/modules-5.15.28-flippy-70+.tar.gz
Exported revision 14[6](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:6).
Armbian SoC List: [ s905x3  ]
Kernel List: [ 5.15.2[8](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:8)  ] 

(1.1) Start building Armbian [ s[9](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:9)05x3 - 5.15.28 ]. Remaining space is 31G.
 [ s905x3 - 5.15.28 ]  (1/6) Confirm version type.
 [ s905x3 - 5.15.28 ]  (2/6) Extract old armbian files.
 [ s905x3 - 5.15.28 ]  (3/6) Refactor related files.
 [ Error ] s905x3 have no the 5.[10](https://github.com/tv4you2016/amlogic-s9xxx-armbian/runs/5517052062?check_suite_focus=true#step:6:10) kernel u-boot file: [  ]
Error: Process completed with exit code 1.

**Comment by ophub** [comment]
Synchronize the latest source code, the u-boot directory changed its location a month ago.
