### ISSUE TITLE
HDMI Output Loss After Unplug HDMI Cable from Monitor  and Connect HDMI Cable to A TV -- Jammy-Gnome with Kernel-5.15.118-ophub

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#1551]
Hi @ophub,

Am facing Loss of HDMI Signal/Output when HDMI Cable is Unplug from the Monitor (1080/60) and Connect to TV (1080/60) On Ubuntu Jammy-Gnome with kernel 5.15.118-ophub.  The connection to the TV just a Blank Desktop Screen and "No Signal".  Ctrl+Alt+F3 get into TTY3, HDMI Signal is available, login and reboot to regain Desktop Screen.

Found this out today, when I Unplug the HDMI Cable from the Monitor and Replug the HDMI Cable to TV. This is repeatable.

The interesting part is, Unplug HDMI Cable from Monitor and Replug-In HDMI Cable to the same Monitor, NO issue, HDMI Signal is avalable and Gnome Desktop works.

```
jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FDTFILE='meson-g12b-gtking-pro.dtb'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
SOC='s922x-reva'
PACKAGED_DATE='2022-07-15'
KERNEL_VERSION='5.15.118'
K510='0'
PLATFORM='amlogic'
KERNEL_TAGS='stable'
jfl@armbian:~$ 
```

Upgrade to kernel-5.15.120-ophub:

```
sudo armbian-update
jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FDTFILE='meson-g12b-gtking-pro.dtb'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
SOC='s922x-reva'
PACKAGED_DATE='2022-07-15'
KERNEL_VERSION='5.15.120'
K510='0'
PLATFORM='amlogic'
KERNEL_TAGS='stable'
jfl@armbian:
```
Still the same issue after upgrading to kernel-5.15.120-ophub.

**Comment by ophub** [comment]
When someone hot-plugged an HDMI cable in the group chat, they ended up frying the motherboard. If you're going to do something like that, be extra cautious. You can test the tolerance of the motherboard with unimportant devices, but don't perform such tests with a valuable device.

**Comment by JFLim1** [comment]
> When someone hot-plugged an HDMI cable in the group chat, they ended up frying the motherboard. If you're going to do something like that, be extra cautious. You can test the tolerance of the motherboard with unimportant devices, but don't perform such tests with a valuable device.

Thank you for the caution.  I usually Turn-Off the Monitor then Unplug HDMI Cable but suppose this is still Hot-Plug.  Must now try NOT to perform Hot-Plug HDMI cable.

Hot-Plug usually when wanted to stream video onto TV.  Unknowingly had been doing it quite often on Androd (switch from Monitor to TV to watch movies). As mentioned above unplug HDMI cable only when the Monitor is Turn-Off and the receiving TV is either OFF or the receiving TV HDMI Input is NOT active eventhough the TV is ON another HDMI Source.

**Comment by JFLim1** [comment]
Hi @ophub,

Is the kernel-6.1.38-ophub from Stable Branch is also with Text-Offset?

**Comment by ophub** [comment]
Text-Offse： There is no Stable version, only Dev and Beta versions have been added
