### ISSUE TITLE
UNT402A无论通过101默认安装.ce版本，还是手动安装.io版本，均提示错误

### ISSUE THREAD

**Issue by orientzane** [ophub/amlogic-s9xxx-armbian#1554]
**Device Information | 设备信息**
 - SOC: [S095l3]
 - Model [UNT402A]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.34]
 - Release: [Armbian_23.08.0_amlogic_s905l3b_jammy_6.1.34_server_2023.06.16]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
前方省略很多正确的提示，然后，接续
1~22.04.3 [3721 kB]
Get:2 http://ports.ubuntu.com jammy-security/main arm64 containerd arm64 1.6.12-0ubuntu1~22.04.3 [24.9 MB]
Get:3 http://ports.ubuntu.com jammy-security/universe arm64 docker.io arm64 20.10.21-0ubuntu1~22.04.3 [24.3 MB]
Fetched 53.0 MB in 4min 52s (181 kB/s)                                         
Preconfiguring packages ...
Setting up libc-bin (2.35-0ubuntu3.1) ...
Segmentation fault
Segmentation fault
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)

无论通过101默认安装.ce版本，还是手动安装.io版本，均提示相同错误
导致的结果是执行安装Home Assistant总是提示：
sudo: docker: command not found

我现在使用的是Armbian_23.08.0_amlogic_s905l3b_jammy_6.1.34_server_2023.06.16，这个优点是安装完内存大些，缺点是日志错误多，而且，我的unt402a SOC实际为905l3，不是905l3b

我是不是该重新用回我最初使用的版本？

**Comment by ophub** [comment]
你访问不了docker.com，解决网络问题

**Comment by orientzane** [comment]
> armbian-software里的软件，使用的是docker.com的仓库。

你好O大：我可以ping通8.8.8.8，下面的复制也说明可以从docker.com下载，但更新armbian-software时，还是101安装docker，都是提示与libc-bin有关的错误提示，我努力了，无法解决，只好来源头问你了。谢谢

有 1 个软件包没有被完全安装或卸载。
需要下载 56.5 MB 的归档。
解压缩后会消耗 259 MB 的额外空间。
获取:1 https://download.docker.com/linux/ubuntu jammy/stable arm64 containerd.io arm64 1.6.21-1 [20.3 MB]
获取:2 https://download.docker.com/linux/ubuntu jammy/stable arm64 docker-ce-cli arm64 5:24.0.4-1~ubuntu.22.04~jammy [12.0 MB]
获取:3 https://download.docker.com/linux/ubuntu jammy/stable arm64 docker-ce arm64 5:24.0.4-1~ubuntu.22.04~jammy [14.0 MB]
获取:4 https://download.docker.com/linux/ubuntu jammy/stable arm64 docker-compose-plugin arm64 2.19.1-1~ubuntu.22.04~jammy [10.2 MB]
已下载 56.5 MB，耗时 4分 31秒 (209 kB/s)                                       
正在设置 libc-bin (2.35-0ubuntu3.1) ...
Segmentation fault
Segmentation fault
dpkg: 处理软件包 libc-bin (--configure)时出错：
 已安装 libc-bin 软件包 post-installation 脚本 子进程返回错误状态 139
在处理时有错误发生：
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
[ STEPS ] Install docker accelerator...
Failed to restart docker.service: Unit docker.service not found.
[ SUCCESS ] Docker installed successfully.

**Comment by orientzane** [comment]
o大：你好，甚至是执行 sudo apt upgrade 提示错误：获取:21 http://ports.ubuntu.com jammy-security/main arm64 sysstat arm64 12.5.2-2ubuntu0.2 [478 kB]
已下载 19.6 MB，耗时 3分 5秒 (106 kB/s)                                        
Preconfiguring packages ...
正在设置 libc-bin (2.35-0ubuntu3.1) ...
Segmentation fault
Segmentation fault
dpkg: 处理软件包 libc-bin (--configure)时出错：
 已安装 libc-bin 软件包 post-installation 脚本 子进程返回错误状态 139
在处理时有错误发生：
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1) 

我发现依然还是libc-bin，这家伙癌症了

**Comment by ophub** [comment]
`sudo dpkg --configure -a`

**Comment by ophub** [comment]
```

sudo apt update
sudo apt clean
sudo apt install -f
sudo apt-get --reinstall install libc-bin


```
