### ISSUE TITLE
系统装进emmc后，怎么禁止从U盘启动

### ISSUE THREAD

**Issue by antjzone** [ophub/amlogic-s9xxx-armbian#1555]
**Device Information | 设备信息**
 - SOC：S905L3A
 - Model： M401A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.120
 - Release: jammy

**Describe the bug | 问题描述**
系统安装进emmc后插着u盘还是会从u盘引导系统，导致插着移动硬盘没法进系统

**Comment by ophub** [comment]
U盘优先，无法修改
