### ISSUE TITLE
bullseye，6.1.36版本，安装后发现很多目录权限很奇怪

### ISSUE THREAD

**Issue by Qiming0912** [ophub/amlogic-s9xxx-armbian#1558]
**Device Information | 设备信息**
 - SOC: [S095d]
 - Model [N1]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.36]
 - Release: [bullseye]

**Describe the bug | 问题描述**
系统安装到emmc都正常，系统运行也正常，但是发现系统很多目录的owner不是root，而是一个uid1001，gid123的状态，并且是Read-only file system，造成很多命令无法执行，比如armbian-update，
见图所示
![屏幕截图 2023-07-20 195606](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6431003/64c41b1b-a84d-4f81-b252-5aad1e83af13)

**Comment by ophub** [comment]
不要把U盘插入安卓系统下，权限被改了。先断电，插入U盘，插电启动，写入emmc

重刷

**Comment by Qiming0912** [comment]
好的，谢谢提醒，这个已经解决。又有新问题了，用armbian-software，选201安装桌面后，启动不能进入，提示“Failed to start lightdm.service - Light Display Manager”。
用systemctl status查看如下：
![屏幕截图 2023-07-20 203807](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6431003/8f53a0b9-6f1a-4b36-8354-0559b886cc97)

查看/var/log/lightdm/lightdm.log
![屏幕截图 2023-07-20 203831](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6431003/ad4aa41b-c7e1-41cc-8ad7-d3c20b60a02c)

手动创建/var/lib/lightdm/data后
restart
![屏幕截图 2023-07-20 204221](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6431003/ca51f2cd-ef95-4e96-9173-b51ebaeb75d2)
提示 WARNING: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
还是不行。不知道用啥思路解决好。

**Comment by Qiming0912** [comment]
#1530 
原来已经有人遇到了
，已解决问题。麻烦O大了

**Comment by daifiyum** [comment]
我刚还提了一个，没想到已经有人遇到了
