### ISSUE TITLE
系统文件所属用户混乱

### ISSUE THREAD

**Issue by daifiyum** [ophub/amlogic-s9xxx-armbian#1560]
**Device Information | 设备信息**
 - SOC: amlogic_s905d
 - Model: 斐讯N1

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.39
 - Release: bullseye

**Describe the bug | 问题描述**
根目录部分目录所属用户混乱，比如/etc目录所属用户是1001，类似还有/usr、/lib64...，其他目录则是正常的root:root

**Comment by daifiyum** [comment]
断电，插入u盘，插电安装，部分目录还是1001
![屏幕截图 2023-07-21 214205](https://github.com/ophub/amlogic-s9xxx-armbian/assets/39544944/3d9a58ef-cdf6-483a-9eca-0588c284c683)

**Comment by ophub** [comment]
U盘插入安卓系统就会被改了

**Comment by daifiyum** [comment]
> 

我没有插入安卓系统，在电脑上制作好安装盘后就插入到断电的N1上，然后插电刷入就这样
