### ISSUE TITLE
关于S905L3替换CPU的测试

### ISSUE THREAD

**Issue by stonegitt** [ophub/amlogic-s9xxx-armbian#1561]
看到之前issue里有人反馈S905L3的盒子声卡和HDMI无法驱动，手头正好有几个S905L3的盒子，拿来测试了一下：
S905L3的盒子声卡和HDMI确实无法驱动，S905L3和S905L2和S905L脚位一样，我就从别的盒子拆了一颗S905L2的CPU，
替换掉了原来的S905L3的CPU
![IMG_3473](https://github.com/ophub/amlogic-s9xxx-armbian/assets/88572144/fb07d23f-c1ce-473b-baf2-3b53e2c24959)
意料之中的可以正常启动，安卓正常，armbian也一切正常。
用905L2和905L3的dtb都可以正常启动，hdmi有输出，声卡也可以正常驱动。
需要用到声卡和HDMI输出的同学建议入手S905L S905L2 S905L3A系列的盒子。
S905L3的声卡和显卡驱动不正常，我的技术有限，实在看不懂S905L2和S905L3安卓dtb的区别
S905L2的安卓dtb名字为gxlx-p261
S905L3的安卓dtb名字为gxlx2-p291
[gxlx安卓dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12135849/gxlx.dts.zip)
附上L2和L3的安卓反编译dts文件
有能力的大佬可以研究研究。

**Comment by stonegitt** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/88572144/4cd85b57-8424-4a46-93fd-f3f9f16f193c)

**Comment by wxalriss** [comment]
当前Linux内核暂不支持S905L3/S905L3B的HDMI控制器，期待大佬们的补丁吧。
By now, the HDMI controller PHY of S905L3/S905L3B is not supported by Linux kernel 6.1.11 source. May somebody contribute meson-dw-hdmi patch to kernel source, thx!
![meson-gxl-vpu-03](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1576440/862a1201-f58b-44bd-9e2c-fe2476e42e79)
![2023-07-23 10-24-36 的屏幕截图](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1576440/3ae4ba9c-18b3-4509-ae8f-25b803143c60)

**Comment by godfather1969** [comment]
armbian-openvfd是干什么用的

**Comment by ophub** [comment]
开启led屏幕显示

**Comment by godfather1969** [comment]
我这个CM311-1S  S905L3B的盒子没有LED显示屏幕。只有个HDMI电视还能不能显示了

**Comment by stonegitt** [comment]
> 我这个CM311-1S S905L3B的盒子没有LED显示屏幕。只有个HDMI电视还能不能显示了

目前不行，S905L3的vpu不知道有什么大的变动，和之前的芯片都不一样。换cpu吧，或者换盒子。

**Comment by godfather1969** [comment]
> > 我这个CM311-1S S905L3B的盒子没有LED显示屏幕。只有个HDMI电视还能不能显示了
> 
> 目前不行，S905L3的vpu不知道有什么大的变动，和之前的芯片都不一样。换cpu吧，或者换盒子。

没显示可以当服务器用，写入emmc又启动不了，目前刷安卓养老

**Comment by stonegitt** [comment]
> 当前Linux内核暂不支持S905L3/S905L3B的HDMI控制器，期待大佬们的补丁吧。 By now, the HDMI controller PHY of S905L3/S905L3B is not supported by Linux kernel 6.1.11 source. May somebody contribute meson-dw-hdmi patch to kernel source, thx! ![meson-gxl-vpu-03](https://user-images.githubusercontent.com/1576440/255370396-862a1201-f58b-44bd-9e2c-fe2476e42e79.png) ![2023-07-23 10-24-36 的屏幕截图](https://user-images.githubusercontent.com/1576440/255370655-3ae4ba9c-18b3-4509-ae8f-25b803143c60.png)

奇怪的是，我对比了S905L2和S905L3的安卓dts，除了名字外，几乎没什么大的差异。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/88572144/a0b76cc7-0d3c-4caa-a288-a36ea6795a27)

**Comment by wxalriss** [comment]
某位机友的S905L3可以启用HDMI显示输出了，请参考https://github.com/ophub/amlogic-s9xxx-armbian/issues/1512

**Comment by stonegitt** [comment]
那个机器应该是L2的，那个安卓包我在L3的机器上刷不进去，L2的机器上可以。



Stone
***@***.***







                       
Original Email
                       
                     

Sender:"wxalriss"< ***@***.*** &gt;;

Sent Time:2023/8/14 23:19

To:"ophub/amlogic-s9xxx-armbian"< ***@***.*** &gt;;

Cc recipient:"stonegitt"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

Subject:Re: [ophub/amlogic-s9xxx-armbian] 关于S905L3替换CPU的测试 (Issue #1561)




 
某位机友的S905L3可以启用HDMI显示输出了，请参考#1512

**Comment by Shrinft** [comment]
我认为那位机友的SoC芯片与我们的S905L3不同，网上有s905L3特殊芯片版本的刷机包，那个可能是特殊芯片版本的(刷机包见znds)
