### ISSUE TITLE
瑞芯微开发工具加载固件失败

### ISSUE THREAD

**Issue by TheRainstorm** [ophub/amlogic-s9xxx-armbian#1562]
**Device Information | 设备信息**
 - SOC: rk3399
 - Model: king3399/容品rk3399

**Armbian Version | 系统版本**
 - Release: 试了2023.07的lunar和jammy都不行

**Describe the bug | 问题描述**
可能是一个基础的问题，但是确实搜索了很久都没有找到解答。板子为king3399，使用瑞芯微开发工具（windows客户端，应用程序为AndroidTool.exe）尝试将本项目的镜像写入eMMC。在第一步选择armbian镜像时就会报错（还没有点击升级），而使用原厂的debian, ubuntu镜像不会出现这个问题，截图如下。也尝试过先擦除，仍然不行。
加载armbian报错
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/c728845d-e1b8-4f3d-b4bf-c50335d9b5fc)
成功加载固件，显示了固件信息
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/ae321893-4b5a-4216-88dc-b4104a3c2758)

查阅容品电子科技附带的手册，只看到以下说明：
> 2.1.1 固件加载失败
> 若是网盘下载的镜像要确保镜像没有损坏
> 自己编译的需要按我们提供的命令进行编译
> 防止打包失败可以重新编译打包

测试过了下载的镜像sha256校验和release里的一致，所以镜像应该没损坏。所以问题是打包的格式和官方工具的要求不一致导致的？**是不是本项目不支持这种方式安装镜像？**如果是我哪里理解有误，还请见谅。

我看到文档里**8. Install Armbian to eMMC**章节介绍了几种Rockchip的开发板刷Armbian进入eMMC的方式。几种均提到了使用RKDevTool直接根据地址空间写入eMMC。但是教程中给的例子除了armbian镜像均放在0x00000000相同外，Radxa-Rock5B额外需要rk3588_spl_loader_v1.08.111.bin文件，并且放在0x0，而FastRhino R68S, Beikeyun, Chainedbox-L1-Pro则是需要将MiniLoaderAll.bin放在0xCCCCCCCC。我想问一下：
- 上面为什么还需要额外指定loader，作用是什么？以我的简单理解，armbian.img应该是包含uboot的？
- king3399可不可以将armbian.img映射到地址0x0，然后直接刷入eMMC？
我尝试了一下是不行的，刷的过程中会提示测试设备失败。是不是也像其它Rockchip板子需要指定额外的loader文件？那么地址应该填多少呢？
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/b35b7db7-89cb-4532-a748-5e33c7118992)
这是尝试使用原厂镜像解包出来的MiniLoaderAll.bin，两个地址均失败
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/e8c1d69a-1628-4a21-a4d1-f00c394446c9)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/bb3b26ad-0f02-4ca3-b933-96d9d006950c)

因为我没有tf卡，看项目的文档，意思好像是先将armbian写入tf卡，启动系统后再通过armbian-install安装到其它存储设备中。但是能不能使用RKDevTool直接写入镜像呢，希望有大佬能解答我以上的疑惑，十分感谢。

**Comment by ophub** [comment]
SD/TF可以用[balenaEtcher](https://www.balena.io/etcher/)把armbian.img直接写入SD/TF即可使用。从SD/TF启动后，上传armbian.img到tf，可以dd写入emmc。

使用RKDevTool时需要loader




armbian-install是amlogic/allwinner用的，rockchip用不了

**Comment by TheRainstorm** [comment]
> SD/TF可以用[balenaEtcher](https://www.balena.io/etcher/)把armbian.img直接写入SD/TF即可使用。从SD/TF启动后，上传armbian.img到tf，可以dd写入emmc。
> 
> 使用RKDevTool时需要loader
> 
> armbian-install是amlogic/allwinner用的，rockchip用不了

是的！我从一篇别人的博客中找到了一个rk3399_loader_v1.24.126.bin文件，然后按照以下的地址确实成功写入armbian了。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/2756f4d9-d8d9-4d44-9a99-83ec180ba4f6)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/aab21929-1b27-4d21-9673-0ccdcc1b1ea3)

感谢，我才发现u-boot/king3399下提供了该文件 :)
不过我好奇这个文件的作用是对应这里的蓝色的idbloader.img吗？不过为什么地址是0xCCCCCCCC呢，图中不是0x40吗？
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33221728/761e112e-ac3d-4b62-a873-594855e16cd2)

**Comment by ophub** [comment]
不是

**Comment by Manssizz** [comment]
> > SD/TF can use [ balenaEtcher ](https://www.balena.io/etcher/) to write armbian.img directly to SD/TF for use.  After booting from SD/TF, upload armbian.img to tf, and you can dd write it to emmc. 
> > Loader is required when using RKDevTool 
> > armbian-install is used by amlogic/allwinner, not rockchip.
> 
> Yes! I found a rk3399_loader_v1.24.126.bin file from someone else's blog, and then successfully wrote it to armbian according to the following address. ![image](https://user-images.githubusercontent.com/33221728/255336413-2756f4d9-d8d9-4d44-9a99-83ec180ba4f6.png) ![image](https://user-images.githubusercontent.com/33221728/255336438-aab21929-1b27-4d21-9673-0ccdcc1b1ea3.png)
> 
> Thanks, I just discovered that this file is provided under u-boot/king3399:) But I'm curious. Does this file correspond to the blue idbloader.img here? But why is the address 0xCCCCCCCC? Isn’t it 0x40 in the picture? ![image](https://user-images.githubusercontent.com/33221728/255336647-761e112e-ac3d-4b62-a873-594855e16cd2.png)

hello. do you have image copy of armbian? because i've try installing king with ophub repo, but can't installing on emmc.

**Comment by TheRainstorm** [comment]
> hello. do you have image copy of armbian? because i've try installing king with ophub repo, but can't installing on emmc.

No, I deleted it. I actually used 2023.07 release in this repo. So I think it's not the image problem?

**Comment by molodye** [comment]
> > SD/TF可以用[balenaEtcher](https://www.balena.io/etcher/)把armbian.img直接写入SD/TF即可使用。从SD/TF启动后，上传armbian.img到tf，可以dd写入emmc。
> > 使用RKDevTool时需要loader
> > armbian-install是amlogic/allwinner用的，rockchip用不了
> 
> 是的！我从一篇别人的博客中找到了一个rk3399_loader_v1.24.126.bin文件，然后按照以下的地址确实成功写入armbian了。 ![image](https://user-images.githubusercontent.com/33221728/255336413-2756f4d9-d8d9-4d44-9a99-83ec180ba4f6.png) ![image](https://user-images.githubusercontent.com/33221728/255336438-aab21929-1b27-4d21-9673-0ccdcc1b1ea3.png)
> 
> 感谢，我才发现u-boot/king3399下提供了该文件 :) 不过我好奇这个文件的作用是对应这里的蓝色的idbloader.img吗？不过为什么地址是0xCCCCCCCC呢，图中不是0x40吗？ ![image](https://user-images.githubusercontent.com/33221728/255336647-761e112e-ac3d-4b62-a873-594855e16cd2.png)

u-boot/king3399下提供了该文件     u-boot/king3399在哪里找

**Comment by TheRainstorm** [comment]
> boot/king3399在哪里找
https://github.com/ophub/u-boot

**Comment by molodye** [comment]
> > boot/king3399在哪里找
> > https://github.com/ophub/u-boot

我想问一下friendlyelec的nanopc T4的uboot这里面没有，可以拿官网的替代吗

**Comment by xumouren5033** [comment]
同上
