### ISSUE TITLE
Tanix TX9 Pro no wifi

### ISSUE THREAD

**Issue by pete-akl-nz** [ophub/amlogic-s9xxx-armbian#1566]
**Device Information | 设备信息**
 - SOC: S912
 - Model Tanix TX9 Pro

**Armbian Version | 系统版本**
 - Kernel Version: 5.9.0
 - Release: 20.10
 - Image from Armbian_20.10_Arm-64_bullseye_current_5.9.0_desktop.img.xz

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

Here is a photo of the device internals:
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/140354996/c6338dbe-f34f-42b2-b75c-cd8a933b137c)

Here is info of what I purchased:
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/140354996/61eb3a1b-bc57-4e0f-8b14-4b1de7acd111)

I followed this advice:
https://github.com/ophub/amlogic-s9xxx-armbian/issues/315

The u-boot.ext is a copy of u-boot-s905x-s912

The extlinux.conf file points to meson-gxm-tx9-pro.dtb

Everything else works ok, just no wifi

**Comment by ophub** [comment]
You are using firmware that is several years old. Try the latest.

https://github.com/ophub/amlogic-s9xxx-armbian/issues/315

**Comment by pete-akl-nz** [comment]
Thank you very much for your response. Regretfully I am a novice and I have no idea how to update the firmware. Please could you point me to a location where I can download firmware, and also a novice's guide on how to do it?

One thing I did not say, but I am booting from an sd card, with the emmc still holding the original android system.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian

**Comment by pete-akl-nz** [comment]
Thank you once again for your feedback. As a novice, I am not sure what you mean by 'firmware', and I can find no reference to that word in the link you have provided. However, my intuition leads me to suppose that updating the 'kernel ' is analogous to what you suggest. This leads me further to this link https://github.com/marketplace/actions/rebuild-armbian-and-kernel, and within that the use of 'armbian-update'. Could you please confirm that I am on the right path?
