### ISSUE TITLE
从 2023.06.21 切换到 2023.07.24 无法从U盘启动

### ISSUE THREAD

**Issue by aaftio** [ophub/amlogic-s9xxx-armbian#1567]
**Device Information | 设备信息**
 - SOC: [S905l3b]
 - Model [天邑 TY1608]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.40]
 - Release: [jammy]

**Describe the bug | 问题描述**

最初从 Android 刷到 armbian 的时候U盘启动使用的是 `Armbian_23.08.0_amlogic_s905l3b_jammy_6.1.35_server_2023.06.21.img.gz`，正常启动（只是 HDMI 不能显示）。由于使用 `meson-gxl-s905l3b-m302a.dtb` 会出现 eMMC IO 错误，在看了所有的通过查看 issues，发现eMMC芯片和 [E900V22D](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1256) 很像，所以切换成 `meson-gxl-s905l2-x7-5g.dtb` ，但是由于发现根目录下 `usr` `lib64` 等目录的权限不正常，所以想安装 `Armbian_23.08.0_amlogic_s905l3b_jammy_6.1.40_server_2023.07.24.img.gz` ，便发现无法从 U盘启动了，重新尝试 `Armbian_23.08.0_amlogic_s905l3b_jammy_6.1.35_server_2023.06.21.img.gz` 却还是可以从 U盘启动的。不知这两个版本之间改动了什么，影响到启动了么？

补充：刚刚测试了下 `Armbian_23.08.0_amlogic_s905l3b_jammy_5.15.121_server_2023.07.24.img.gz ` 可以从U盘启动了，难道是内核的问题？由于没有办法使用 HDMI 查看输出，只要是启动不了无法 ssh，就无法看到错误信息，很是不方便……

![815552199](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/a29f137a-4c46-4799-841a-b95fd4baad4b)

**Comment by ophub** [comment]
没实质性改动。正常的维护修复。
那个权限 `sudo chown root:root /etc /usr` 类似这样几条命令，把添加了脚本的几个地方修改下即可，过去的几个月里我一直使用也没因为这个权限影响了什么。

**Comment by aaftio** [comment]
> 没实质性改动。正常的维护修复。 那个权限 `sudo chown root:root /etc /usr` 类似这样几条命令，把添加了脚本的几个地方修改下即可，过去的几个月里我一直使用也没因为这个权限影响了什么。

我是出现了断电再启动，无法自动连网，需要重新拔插网线才能恢复。试了把 NetworkManager 的网口自动协商关掉，直接写成 100M 速率，也无法解决。然后发现目录权限问题，想先解决这个问题。看看是否目录权限问题引起。

现在把系统刷到 `Armbian_23.08.0_amlogic_s905l3b_jammy_5.15.121_server_2023.07.24.img.gz` ，网络需要拔插网线才能连接的问题已经解决了。由于同时 `更换内核` 和 `修正目录权限` ，有两个变量，无法得知是哪个操作解决了这个问题。
