### ISSUE TITLE
分享四川天邑 TY1608 成功刷入 eMMC

### ISSUE THREAD

**Issue by aaftio** [ophub/amlogic-s9xxx-armbian#1568]
**Device Information | 设备信息**
 - SOC: [S905L3B]
 - Model [TY1608]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.121]
 - Release: [jammy]

**Describe the bug | 问题描述**

之前已经[有人成功刷入](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1332)这个型号的机器，这里使用了与他相同的 Android 系统来从 U盘 启动 armbian。但是他使用的M302A的DTB `meson-gxl-s905l3b-m302a.dtb`，而我的盒子使用这个 DTB 无法识别 eMMC，经过查看他的机器的 eMMC 芯片与我的不相同，他的为 SiliconGo，而我的是 SEC （三星）。经过测试，相同 SoC 的机型中有一个 [E900V22D](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1256) 使用的 SEC 品牌的 eMMC，所以切换 DTB 为 `meson-gxl-s905l2-x7-5g.dtb` 正常启动并且刷入 eMMC。

下面是我的机器图片：

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/55863ebb-d221-46bb-9416-2bf0199f9063)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/9cf3ff6e-1ff3-40f6-a961-9b37509f0980)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/00c97625-1b6d-4579-8766-e121b93a1c48)

**Comment by aaftio** [comment]
> 感谢分享，试试6.1内核的固件，看看哪个u-boot适合这个设备。

感觉应该是 5.15 更适合，我在这个 [issue](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1567) 里有反馈使用最新构建的 6.1 的内核无法启动。并且我想请教下，因为 ubuntu 的  jammy 官方使用的是 5.15 内核，armbian 把内核切换到 6.1 是否会出现测试不充分，不稳定之类的问题？

**Comment by aaftio** [comment]
> 

谢谢解答！6.1 是有两个 u-boot 可以选择？也就是和 dtb 一样可以切换尝试？请问的无文档可以指点，我试试。

**Comment by aaftio** [comment]
> 没这种说法，现在6.5都有人使用，正解是新内核更好，难不成全球内核开发人员在集体开倒车？每个内核都有维护周期，结束就弃用了，难不成内核弃用的时候设备也要弃用了吗？新内核是在旧内核的基础上滚动更新的，每个新内核都是旧内核的升级版。
> 
> 常见的现象是新出的芯片，新上市的设备，最新的内核也还没支持了。而不是内核性能过剩，要使用个N年前的老内核和设备进行匹配。积极拥抱新内核。
> 
> 5.15/6.1区别是多了一个u-boot，选对了就可以使用6.1。

谢谢解答！6.1 是有两个 u-boot 可以选择？也就是和 dtb 一样可以切换尝试？请问的无文档可以指点，我试试。

**Comment by ophub** [comment]
只有1个u-boot。在/boot/u-boot*里选1个，复制为u-boot.ext

**Comment by v587xpt** [comment]
你好大佬，我的盒子和你的一模一样，也想刷jammy呢；
现在已经将镜像写入了U盘，制作好了U盘启动，但是不知道如何让盒子进入U盘启动，非常尴尬，希望大佬能教一下我；
联系不及时，请大佬见谅；
email：v587xpt@163.com

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
看12.4

https://github.com/ophub/amlogic-s9xxx-armbian/issues/2165
