### ISSUE TITLE
A95XF3-Air 网络问题

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#157]
我看A95XF3-Air长的好看就买了一个来看看，4g+64g
USB启动发现网络有问题
![IMG_20220312_185241](https://user-images.githubusercontent.com/9335046/158015798-8b9f9ed2-8d66-4fee-8b8e-394df936fdeb.jpg)

**Comment by ophub** [comment]
错误显示网卡不支持，应该是没驱动或者选择的dtb不正确，你看看你的网卡什么芯片。
千兆网卡用：meson-sm1-a95xf3-air-gbit.dtb
百兆网卡用：meson-sm1-a95xf3-air.dtb
修改文件/boot/uEnv.txt里面的dtb名称

**Comment by EastWoodYang** [comment]
嗯嗯，网卡可以了！
另外，能帮我看下wifi和蓝牙是否支持？

![9e3164816e7d206261597b88b0afcab](https://user-images.githubusercontent.com/9335046/158019662-fc52aa34-dc68-4679-a3d1-6275d61d69aa.jpg)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/mediatek

支持的驱动己经集成到固件里了。

**Comment by EastWoodYang** [comment]
目前WiFi和蓝牙不可用，这个芯片的驱动没有在固件里面，后续会支持不？

**Comment by ophub** [comment]
你试着找找支持主线内核使用的驱动。安卓的驱动不可用。

**Comment by EastWoodYang** [comment]
帮忙看下这个，我看里面文档好像有提到Android和Linux两个方面的编译，看下是否能支持
[Mt76x8(7668+7638+7663)driver.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8239550/Mt76x8.7668%2B7638%2B7663.driver.zip)

**Comment by ophub** [comment]
root@armbian:/lib/firmware/mediatek# ls /lib/firmware/mediatek/mt7668*
`/lib/firmware/mediatek/mt7668pr2h.bin`

固件里有一个7668不知道是不是。

**Comment by EastWoodYang** [comment]
我可以怎么试？linux内核方面我知识盲区

**Comment by ophub** [comment]
固件里面有。你试一下能不能启用
armbian-config
里面找无线网络，启用

**Comment by EastWoodYang** [comment]
不可以，之前试过，没有无线网络的选项

**Comment by EastWoodYang** [comment]
![35782ee54c2f4c80494857693fd2be9](https://user-images.githubusercontent.com/9335046/158084396-1bd34f83-688f-4058-8335-d60797b928d3.png)

**Comment by ophub** [comment]
![Snip20220314_1](https://user-images.githubusercontent.com/68696949/158102847-89919fa2-f45b-44af-b6ba-8d887012f158.png)

没有就是没驱动起来，不支持

**Comment by EastWoodYang** [comment]
唉，我看了下MT7668这块芯片驱动不好找，这个 TX3 wifi用的是哪个芯片？

**Comment by ophub** [comment]
bcm4330
有线千兆，wifu和蓝牙都可以使用，我现在就在用无线和蓝牙。
但是这个盒子变异体挺多，有百兆的。买的时候要问店家，是不是8211f千兆网卡。

**Comment by ophub** [comment]
```
  | |                          [*]   MediaTek devices  
  | |                          <M>     MediaTek MT7601U (USB) support  
  | |                          <M>     MediaTek MT76x0U (USB) support  
  | |                          < >     MediaTek MT76x0E (PCIe) support 
  | |                          < >     MediaTek MT76x2E (PCIe) support 
  | |                          <M>     MediaTek MT76x2U (USB) support  
  | |                          < >     MediaTek MT7603E (PCIe) and MT76x8 WLAN support  
  | |                          < >     MediaTek MT7615E and MT7663E (PCIe) support 
  | |                          <M>     MediaTek MT7663U (USB) support  
  | |                          <M>     MediaTek MT7663S (SDIO) support 
  | |                          < >     MediaTek MT7915E (PCIe) support
  | |                          < >     MediaTek MT7921E (PCIe) support
  | |                          <M>     MediaTek MT7921S (SDIO) support
```

sdio接口只有mt7663s和mt7921s两种。
你试着手动载入下：`modprobe mt76-sdio`

**Comment by EastWoodYang** [comment]
> bcm4330 有线千兆，wifu和蓝牙都可以使用，我现在就在用无线和蓝牙。 但是这个盒子变异体挺多，有百兆的。买的时候要问店家，是不是8211f千兆网卡。

TX3这个盒子的wifi和蓝牙芯片，现在大部分采用的是SP6330，目前应该也是不支持吧？

**Comment by ophub** [comment]
![Snip20220314_3](https://user-images.githubusercontent.com/68696949/158120711-f1f1286c-73b8-42d7-952f-9a3c71b4fb50.png)

TX3 s905x3 4+64

**Comment by ophub** [comment]
![Snip20220314_8](https://user-images.githubusercontent.com/68696949/158121195-af906e94-b870-4903-93fa-053f5c815ca6.png)

**Comment by EastWoodYang** [comment]
我问下的是SP6330这块芯片，应该是不支持，我看内核里面没检索到相关信息

**Comment by ophub** [comment]
SP6330是brcm4330-sdio，驱动是brcmfmac

**Comment by ophub** [comment]
https://forum.armbian.com/topic/16696-armbian-for-tanix-tx3-amlogic-s905x3-with-sp6330-wifibluetooth-module/

**Comment by EastWoodYang** [comment]
原来如此，那就买买买！

**Comment by EastWoodYang** [comment]
> ![Snip20220314_3](https://user-images.githubusercontent.com/68696949/158120711-f1f1286c-73b8-42d7-952f-9a3c71b4fb50.png)
> 
> TX3 s905x3 4+64

新买了个TX3，刷了你最新打包的固件，蓝牙相关日志和你这个截图一样，但是armbian-config进入BT discover发现不了其他蓝牙设备，bluetoothctl scan on 也扫描不到其他蓝牙设备，问下是什么问题，你那边能连上蓝牙设备？

**Comment by EastWoodYang** [comment]
![image](https://user-images.githubusercontent.com/9335046/160365654-da332ab7-5a27-46c6-bc47-419a887b6b75.png)

**Comment by ophub** [comment]
![Snip20220328_3](https://user-images.githubusercontent.com/68696949/160369827-f5de7cac-ddb4-46d0-8207-7bac2aa169a2.png)

看日志没错误，都正常识别了，不能用？

**Comment by EastWoodYang** [comment]
嗯嗯，你刷的是哪个固件？

**Comment by ophub** [comment]
我也是这个

**Comment by EastWoodYang** [comment]
你那边能scan到蓝牙设备？

**Comment by ophub** [comment]
我没蓝牙耳机，我明天找个试试

**Comment by EastWoodYang** [comment]
你打开手机蓝牙，看看能不能scan到手机的蓝牙

**Comment by EastWoodYang** [comment]
另外问下，目前哪个设备能完美支持蓝牙和wifi的？:-)

**Comment by 1014807920** [comment]
https://download.csdn.net/download/liushengdi110/87890662

**Comment by PhamTz7** [comment]
@1014807920 can you upload this driver in another link? i cant understand the page contents.
im trying to install the wifi drivers on my A95XF3-Air but without success. if any of you write the instructions in english, would be great! 😊

**Comment by boza111** [comment]
> @1014807920 can you upload this driver in another link? i cant understand the page contents. im trying to install the wifi drivers on my A95XF3-Air but without success. if any of you write the instructions in english, would be great! 😊

Have you figured it out? I am trying to do the same thing.

**Comment by boza111** [comment]
Which kernel version and dtb file should I use?

**Comment by boza111** [comment]
My a95x f3 air also uses the RTL8821CU driver. Which image should I use?

**Comment by ophub** [comment]
mt7668 wifi和蓝牙测试内核及使用方法： https://github.com/ophub/amlogic-s9xxx-armbian/issues/3610#issuecomment-5091652991
