### ISSUE TITLE
分享移动咪咕 MG101(康佳代工) 成功刷入 eMMC

### ISSUE THREAD

**Issue by aaftio** [ophub/amlogic-s9xxx-armbian#1570]
**Device Information | 设备信息**
 - SOC: [S905LB]
 - Model [咪咕 MG101]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.121 或者 6.1.40]
 - Release: [jammy]

**Describe the bug | 问题描述**

要从 U盘启动 首先线刷刷入 可以执行 `adb shell reboot update`  命令的 Android 包，[百度网盘](https://pan.baidu.com/s/1WL4g_O8gZmPpVnrP3C_-UQ?pwd=femg)。

使用 `Armbian_23.08.0_amlogic_s905lb-r3300l_jammy_*.img.gz` ，默认 dtb 和 u-boot 即可。HDMI 正常输出，有线网络正常。

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/97d0ca65-4374-474d-8270-eebf341f684f)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/54e7273e-08b2-4e6a-a089-3792f327e4f6)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1856880/5da90534-30bc-4b83-b947-c0099de83b18)

**Comment by ophub** [comment]
多谢分享，我把这个设备添加到支持列表里。

**Comment by aaftio** [comment]
> 多谢分享，我把这个设备添加到支持列表里。

也感谢你维护的这个项目，非常棒！

**Comment by aaftio** [comment]
> 多谢分享，我把这个设备添加到支持列表里。

你添加的 mg101 错误了，SoC应该是 S905lb，而不是 S905l3b。

**Comment by ophub** [comment]
好的，我更正一下

**Comment by 1273294133** [comment]
mg101这个型号真神奇，你的和我的mg101也不一样，我的是s905l。
刷完安卓9后，用的s905x的dtb，可以正常启动。
咦好久没看，现在有了专门的s905l的dtb了回头有空刷了看看~
![1693208481140](https://github.com/ophub/amlogic-s9xxx-armbian/assets/66990324/8b9b7264-23b8-4161-b0c0-c24285700224)
![1693208603896](https://github.com/ophub/amlogic-s9xxx-armbian/assets/66990324/cfec6a99-a0ff-498f-81e4-e8fa8c3714ec)

**Comment by windyin** [comment]
> mg101这个型号真神奇，你是有杜比认证的，带b。我的mg101和你不一样，我的是s905l。 刷完安卓9后，用的s905x的dtb，可以正常启动。 咦好久没看，现在有了专门的s905l的dtb了回头有空刷了看看~ ![1693208481140](https://github.com/ophub/amlogic-s9xxx-armbian/assets/66990324/8b9b7264-23b8-4161-b0c0-c24285700224) ![1693208603896](https://github.com/ophub/amlogic-s9xxx-armbian/assets/66990324/cfec6a99-a0ff-498f-81e4-e8fa8c3714ec)

安卓9 怎么刷
