### ISSUE TITLE
failure to use dkms

### ISSUE THREAD

**Issue by ncisoft** [ophub/amlogic-s9xxx-armbian#1571]
**Device Information | 设备信息**
 - SOC: [S095L3a]
 - Model [UNT403A]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.42]
 - Release: [ jammy]

**Describe the bug | 问题描述**

I upgraded the armbian kernel to 6.1.42 by using `sudo armbian-kernel -k 6.1.42`.

I want to build kernel module according to [redroid-modules]( https://github.com/remote-android/redroid-modules), but run `dkms` fail, it report the kernel scripts has x86_64 elf

cat /var/lib/dkms/redroid-ashmem/1/build/make.log

DKMS make.log for redroid-ashmem-1 for kernel 6.1.42-ophub (aarch64)
Thu Jul 27 11:51:43 PM CST 2023
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-6.1.42-ophub'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.2.Rel1 (Build arm-12.24)) 12.2.1 20221205
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
  CC [M]  /var/lib/dkms/redroid-ashmem/1/build/ashmem.o
  CC [M]  /var/lib/dkms/redroid-ashmem/1/build/deps.o
**/bin/sh: 1: scripts/basic/fixdep: Exec format error**
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/redroid-ashmem/1/build/deps.o] Error 126
make[2]: *** Deleting file '/var/lib/dkms/redroid-ashmem/1/build/deps.o'
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/redroid-ashmem/1/build/ashmem.c: In function ‘ashmem_init’:
/var/lib/dkms/redroid-ashmem/1/build/ashmem.c:950:15: error: too few arguments to function ‘register_shrinker’
  950 |         ret = register_shrinker(&ashmem_shrinker);
      |               ^~~~~~~~~~~~~~~~~
In file included from ./include/linux/list_lru.h:13,
                 from ./include/linux/fs.h:13,
                 from ./arch/arm64/include/asm/elf.h:141,
                 from ./include/linux/elf.h:6,
                 from ./include/linux/module.h:19,
                 from /var/lib/dkms/redroid-ashmem/1/build/ashmem.c:13:
./include/linux/shrinker.h:99:27: note: declared here
   99 | extern int __printf(2, 3) register_shrinker(struct shrinker *shrinker,
      |                           ^~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/redroid-ashmem/1/build/ashmem.o] Error 1
make[1]: *** [Makefile:2012: /var/lib/dkms/redroid-ashmem/1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.42-ophub'
make: *** [Makefile:8: all] Error 2
``` bash
 $ file  /bin/bash
/bin/bash: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, BuildID[sha1]=4dadac332a3aaef2b0eca910734ed6f8834d0b9b, for GNU/Linux 3.7.0, stripped
$ echo it's ARM aarch64 elf

$ file /usr/src/linux-headers-6.1.42-ophub/scripts/mod/mk_elfconfig
/usr/src/linux-headers-6.1.42-ophub/scripts/mod/mk_elfconfig: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=4ef11c78ca90f3b66a92d103c42ed84606531413, for GNU/Linux 3.2.0, not stripped
$echo it's x86-64 elf 
```

obviously the Linux header's scripts  have not build correctly

**Comment by ophub** [comment]
armbian-update -u dev -k k.x.y

**Comment by ncisoft** [comment]
> use dev kernel armbian-update -u dev -k k.x.y

It works, thank you

**Comment by ncisoft** [comment]
> use dev kernel armbian-update -u dev -k k.x.y

It works, thank you

**Comment by w12563789** [comment]
> > use dev kernel armbian-update -u dev -k k.x.y
> 
> It works, thank you
请问你成功运行redroid了，可否说下部署流程？

**Comment by rhwong** [comment]
same issue
let me try
