### ISSUE TITLE
Question: Can I Restore The Emmc Storage Flashing The Android Stock Rom On Armbian?

### ISSUE THREAD

**Issue by SuperWeegeeGameplays2401** [ophub/amlogic-s9xxx-armbian#1572]
I Didn't Know That You Could Make A Backup In Armbian, So Now I Want To Restore My Box Flashing The Android Stock Rom That I Found In Google Via DDBR Command And I Wonder If Is This Really Possible?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

look at 12.13

**Comment by SuperWeegeeGameplays2401** [comment]
No My Question Is: Can I Restore The Android OS Of My Tv Box Using A Stock Rom That I Found In Google?(Using Armbian DDBR Command)

**Comment by ophub** [comment]
you can
