### ISSUE TITLE
创维E900V21E刷入emmc后系统无法启动

### ISSUE THREAD

**Issue by cubelightt** [ophub/amlogic-s9xxx-armbian#1574]
**Device Information | 设备信息**
 - SOC: [e.g. S905l2]
 - Model [e.g. E900V21E]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.121]
 - Kernel Version: [e.g. 6.1.40]
 - 
**Describe the bug | 问题描述**
使用固件：
Armbian_23.08.0_amlogic_s905l2-e900v21e_lunar_5.15.121_server_2023.07.24
Armbian_23.08.0_amlogic_s905l2-e900v21e_lunar_6.1.40_server_2023.07.24

目前状况：
两个固件都能从u盘启动
使用6.1.40固件在u盘启动时有线网卡可以使用，无线不能。使用armbian-install -m yes安装后显示安装成功，重启后显示器有信号但一直黑屏，键盘大小写无法切换，但是有ip且可以ping通，ssh无法使用(armbian-install不加参数状况相同）

使用5.15.121固件在u盘启动时有线网卡无法使用，无线网卡可以使用，尝试过ifconfig eth0 up无效。使用armbian-install不加参数安装至emmc可以正常启动，但是无线网卡和有线网卡又都不能使用。加-m yes后同样无法启动。

莫非只能6.1.40外挂u盘用了？

**Comment by ophub** [comment]
先刷一下第三方的高版本安卓9.0+系统

**Comment by cubelightt** [comment]
使用过armbian-install后机顶盒开机的logo没了，也进不去工厂模式，现在不知道怎么刷安卓，而且好像也没找到这款的安卓9的包。不过我找的了别人分享的dtb
https://tieba.baidu.com/p/7438115971
请问这个有用吗

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

看12.13

**Comment by cubelightt** [comment]
谢谢回复，我再折腾下

**Comment by yiqihongchen** [comment]
> 先刷一下第三方的高版本安卓9.0+系统

你好，这个9.0安卓去哪里下载呢

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/dev
