### ISSUE TITLE
开启或重启后自动运行指定指令碰到的问题

### ISSUE THREAD

**Issue by Mitchell08** [ophub/amlogic-s9xxx-armbian#1575]
想要开机或者重启后自动运行指定的一些指令，参考了【1】中所用的方法，写了一个sh脚本【2】，在x86 vps 上或者本地x86小主机上可以正常开机自动执行，但是在armbian中无法开机自动执行，开机后如果手动输入这些命令，是可以正常执行的，Google了一下，找到了这篇文献【3】，按【3】中所使用的方法设置后，还是不行。请求大家的帮助，谢谢啦！

参考文献：

【1】https://blog.csdn.net/tuzixini/article/details/95616333

【2】创建/etc/init.d/mystart.sh，写入这些命令，

```
#!/bin/bash
### BEGIN INIT INFO
# Provides:          tuzixini
# Required-Start:    $local_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: self define auto start
# Description:       self define auto start
### END INIT INFO
# 上面的部分也必须写上，后面放上你需要开机执行的命令，这里是挂载一个硬盘
sleep 150 && \  //需要延时执行命令

rclone mount gd_****hoto: /home/share/drive/gd_****hoto \
 --copy-links --allow-other --allow-non-empty --umask 000 --daemon && \

rclone mount gd_****boro: /home/share/drive/gd_****boro \
 --copy-links --allow-other --allow-non-empty --umask 000 --daemon
```

【3】https://blog.csdn.net/xiaotuwai8/article/details/115477206

**Comment by Mitchell08** [comment]
问题已解决，谢谢大家

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh

可以统一放这
