### ISSUE TITLE
unt403a无法使用u盘引导5.15内核版本

### ISSUE THREAD

**Issue by dzefone-stu** [ophub/amlogic-s9xxx-armbian#1578]
Device Information | 设备信息

SOC: [S905l3]
Model [UNT403A]
Armbian Version | 系统版本

Kernel Version: [6.1.40]
Release: [lunar_6.1.40_server_2023.07.24]
Describe the bug | 问题描述
盒子刷入的安卓底包是[android_tv_m401a_s905l3.tar.xz]
首先刷入的armbian是Armbian_23.08.0_amlogic_s905l3_lunar_6.1.40_server_2023.07.24.img
配置代码117~121都试过，分区配置1
可以u盘启动，无HDMI信号，armbian-install刷入emmc显示成功
去掉u盘开机状态灯红灯变绿灯能获取ip，能ping通，但是无法ssh登入
u盘换Armbian_23.08.0_amlogic_s905l3_lunar_5.15.121_server_2023.07.24
无法获取ip，无法ssh登入
无法进入线刷模式，刷机神器刚买，在路上

**Comment by ophub** [comment]
试试jammy, bullseye

**Comment by dzefone-stu** [comment]
试了Armbian_23.08.0_amlogic_s905l3_jammy_5.15.121_server_2023.07.24
以及Armbian_23.08.0_amlogic_s905l3_bullseye_5.15.121_server_2023.07.24
同样无法获取ip，无法ssh登入

**Comment by viphanf** [comment]
下错了吧，应该下载s905l3a的

**Comment by dzefone-stu** [comment]
> 下错了吧，应该下载s905l3a的

拆机看了，是905L3 版本的

**Comment by ophub** [comment]
把你用到的 **湖北移动UNT403A_UM-S905L3-2+8G-安卓9-当贝纯净桌面-线刷固件**  分享一个下载地址，我转存一份到备用地址： https://github.com/ophub/kernel/releases/tag/tools

**Comment by ophub** [comment]
我网上找到了，已经转存了。

**Comment by whmzsu** [comment]
我也有一台，试试安装

**Comment by whmzsu** [comment]
这个需要修改uEnv.txt中的dtb配置吗？需要改哪个？

**Comment by hu-min** [comment]
> Armbian_23.08.0_amlogic_s905l3_lunar_5.15.121_server_2023.07.24

这个版本release中好像没找到了，不知道是否可以再分享下？

**Comment by whmzsu** [comment]
> 对照model表找对应的固件直接可以使用，用其他的需要改。

感谢，已经Ok了，用的905l3的固件，复制对应u-boot文件为u-boot.ext，同手头的e900v22e一样处理，当然hdmi是不行的。
