### ISSUE TITLE
章鱼星球s912刷入armbian到emmc，插入u盘无法开机启动

### ISSUE THREAD

**Issue by WGE10086** [ophub/amlogic-s9xxx-armbian#1581]
**Device Information | 设备信息**
 - SOC: [s912]
 - Model [章鱼星球]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.40]
 - Release: [bookworm]

**Describe the bug | 问题描述**
jammy和bullseye以及bookworm用U盘启动后armbian-install写入EMMC
拨掉U盘后启动正常，插上U盘或移动硬盘后再通电就无法启动，一直反复加载引导程序

拨掉U盘或移动硬盘正常启动画面
Bus usbtcss0
Register 2000140 NbrPorts 2
Starting thecontroller
USB XHC1 1.00
scanning bus usbec9000000 for devices... 2 USB Device(s) found
scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot: 0
Device 0:unknown device
Card did not respond to voltage select?:-110
switch to partitions #0, OK
mmc1(part 0) is current device
Scanning mc 1:1...
Found U-Boot script /boot.scr
1025 bytes read in 1 ms (1001 KiB/s)
##Executing script at 08000000
Start AMLOGIC mainline U-boot
##Error: "bootfromsd" not defined
Couldn't find partition mmc 2
376 bytes read in 1ms (367.2 KiB/s)
##Error:"mac"not defined
##Error:"eth mac"not defined
ethaddr=22:07:ff:f7:91:ef
33321472 bytes read in 752 ms(423MiB/s)
17992385 bytes read in 407 ms(42.2 MiB/s)
41556 bytes read in 3ms(13.2 MiB/s)
Moving Inage from 0x8080000 to 0x8200000，end=a2b0000
##Loading init Ramdisk from Legacy Image at 13000000 ...
Image Name:uInitrd
Image Type:AArch64 Linux RAMDisk Image (gzip compressed)
Data Size:17992321 Bytes =17.2 MiB
Load Address:00000000
Entry Point:00000000
Verifying Checksum ... OK
##Flattened Device Tree blob at 08008000
Booting using the fdt blob at 0x8008000
Loading Randisk to 7ae0c000,end 7bf34a81 OK
Loading Device Tree to 000000007adfe000,end 000000007ae0b253
Starting kernel ...
到这里就可以正常启动

插上U盘或移动硬盘后启动画面
`Card did not respond to valtage select! -110
Scaming disk mmc070000blk..
Disk mmc070000.blk not ready
Scanning disk mmc74000blk...
Scaming disk usb_mass_storage.luno...
Found 6 disks
No EFI system partition
BootOrder not defined
EFI boot manager: Cannot load any image
Card did not respond to voltage select?:-110
switch to partitions #0, OK
mmc1(part 0) is current device
Scaming mmc 1:1..
Found U-Boot script/boot.scr
1025 bytes read in 1 ms(1001 KiB/s)
##Executing script at 08000000
Start AMLOGIC mainline U-boot
##Error: "bootfromsd" not defined
Couldn't find partition mmc 2
376 bytes read in 1 ms(367.2 kiB/s)
##Error:"nac"not defined
##Error: "eth mac" not defined
ethaddr=22:07:ff:f7:91:ef
33321472 bytes read in 754 ms(42.1 MiB/s)
17992385 bytes read in 406 ms(42.3 MiB/s)
41556 bytes read in 2ms(19.8MiB/s)
Moving Inage from 0x8080000 to 0x8200000，end=a2b0000
#Loading init Randisk from Legacy Image at 13000000
Image Name:uInitrd
Image Type:AArch64 Linux RAMDisk Image(gzip compressed)
Data Size:17992321 Bytes=17.2 MiB
Load Address:00000000
Entry Point:00000000
Verifying Checksum... OK
##Flattened Device Tree blob at 08008000
Booting using the fdt blob at 0x8008000
Loading Randisk to 7ae0c000,end 7bf34a81...OK
Loading Device Tree to 000000007adfe000,end000000007a0b253
"Synchronous Abort" handler, esr0x96000004
elr:6000000001063248 lr:00000000010533e4(reloc)
eir: 000000007dfb6248 lr :000000007dfa63e4
x0:719e59007db0ecf2 x1:000000007dfbde08
x2:0000000000000010 x3:000000007df81f80
x4:0000000000000000 x5:719e59007db0ecf2
x6:0000000001000000 x7:000000000000000
x8:0000000000000007 x9:000000000000000
x10:000000000000178 x11:000000007bf3685c
x12:0000000000000a4 x13:000000007bf36818
x14:00000007adfe000 x15:0000000000000020
x16:00000007df805a4 x17:0000000000000000
x18:00000007bf42dd0 x19:000000007af37040
x20:0000000074f53fc8 x21:000000007dfbde08
x22:000000000000100 x23:600000007bf4a700
x24:00000007dfdc1do x25:0000000001000000
x26:000000000000000 x27:0000000001000000
x28:000000000001000 x29:000000007bf36810

Code:eb02089f 54000061 52800000 14000006(386468a3)
Resetting cPu`
然后断电重新出现开机画面运行到这段，并一直重复

**Comment by ophub** [comment]
插着U盘就会优先从U盘启动，如果U盘没可以运行的系统，就会死循环。

**Comment by WGE10086** [comment]
什么时候修复这个bug

**Comment by WGE10086** [comment]
> 插着U盘就优先从U盘启动，如果U盘不能运行的系统，就会死循环。

什么时候修复这个bug

**Comment by ophub** [comment]
这是设定，不是bug

**Comment by WGE10086** [comment]
> 这是设定，不是bug

请问这种怎么修改，因为中途停电了，就无法远程使用

**Comment by ophub** [comment]
如果U盘不能优先启动，怎么刷机呢？怎么把安卓系统从U盘启动刷armbian呢？

改的方法有几种，改bootloader的启动顺序，改u-boot.src等，也有用hub的，方法搜issues

**Comment by antjzone** [comment]
不能改成usb驱动失败直接从emmc启动吗
