### ISSUE TITLE
Hk1 Box lan 100 instead 1000

### ISSUE THREAD

**Issue by HokaDipe** [ophub/amlogic-s9xxx-armbian#1582]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye's 
![Screenshot_2023-07-31-18-23-21-226_com server auditor ssh client](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137959211/f7f35c64-2adb-458d-b0d3-d670c355adb3)

Hi guys, i just install armbian in hk1box, so this device have lan 100 instead 1000. Plz help me

**Comment by ophub** [comment]
cat /boot/uEnv.txt

**Comment by HokaDipe** [comment]
> cat /boot/uEnv.txt

ohh thanks you sir, i just fix it
