### ISSUE TITLE
求大佬们推荐个性价比高，能完美适配的盒子

### ISSUE THREAD

**Issue by 20140706** [ophub/amlogic-s9xxx-armbian#1584]
求大佬们推荐个性价比高，能完美适配的盒子
不用蓝牙 不用wifi 不用千兆口，百兆口就行，USB也不挑 有没有3.0无所谓，因为数量比较多，求大佬们推荐个能完美兼容armbian的盒子

**Comment by myallten** [comment]
就用千里通智能AI盒子就可以

**Comment by phcl1998** [comment]
n1没有性价比，你要性价比就玩客云

**Comment by dinhchinh82** [comment]
> 就用千里通智能AI盒子就可以

@myallten 你能给我购买这个盒子的链接吗？谢谢.

**Comment by bbggoo** [comment]
移动魔百盒吧，便宜四核，

**Comment by antjzone** [comment]
cm311-1a

**Comment by mengzai-c** [comment]
玩客云架构不咋地，用hk1 box吧，4G+64G 1000M网卡，2.1GHZ主频,USB3.0，拼多多上有魔改版，才300不到，我就用的这个，
如果觉得太贵可以买CM311-1A，UNT403A，CPU体制好的可以超2.0Ghz我手上有一台UNT403A，一台N1，一台HK1 BOX，感觉最好的就是HK1 BOX,我试过UNT403A超频，高负载跑了一天没任何问题
不建议买N1，太贵，性能也不咋地，那个1000M网卡，也没啥用，如果做NAS，usb只有2.0

**Comment by LoongArum** [comment]
同求，我跟你相反，我需要一个支持蓝牙，无线的盒子，用途是躺在床上用投影仪写代码🤣。

**Comment by Vinke2** [comment]
> 玩客云架构不咋地，用hk1 box吧，4G+64G 1000M网卡，2.1GHZ主频,USB3.0，拼多多上有魔改版，才300不到，我就用的这个， 如果觉得太贵可以买CM311-1A，UNT403A，CPU体制好的可以超2.0Ghz我手上有一台UNT403A，一台N1，一台HK1 BOX，感觉最好的就是HK1 BOX,我试过UNT403A超频，高负载跑了一天没任何问题 不建议买N1，太贵，性能也不咋地

usb3.0速度能跑到多少?
