### ISSUE TITLE
Getting mandb errors on each package installtaion

### ISSUE THREAD

**Issue by sharicov** [ophub/amlogic-s9xxx-armbian#159]
Getting a lot of error messages when using apt install (running as root).
Example:

/usr/bin/mandb: fopen /var/cache/man/fr.UTF-8/18622: Permission denied
/usr/bin/mandb: can't chmod /var/cache/man/cs/CACHEDIR.TAG: Operation not permitted
/usr/bin/mandb: can't remove /var/cache/man/cs/CACHEDIR.TAG: Permission denied
/usr/bin/mandb: fopen /var/cache/man/cs/18622: Permission denied
/usr/bin/mandb: can't chmod /var/cache/man/zh_CN/CACHEDIR.TAG: Operation not permitted
/usr/bin/mandb: can't remove /var/cache/man/zh_CN/CACHEDIR.TAG: Permission denied
/usr/bin/mandb: fopen /var/cache/man/zh_CN/18622: Permission denied

**Comment by ophub** [comment]
```
chown man:root /var/cache/man -R
chmod g+s /var/cache/man -R
```

**Comment by sharicov** [comment]
Thanks a lot, that fixed the issue, is it because of the installation
script, or Ubuntu specific? (wasn't there in you previous build)
