### ISSUE TITLE
MGV3000试了一下8月份的4个包，刷了emmc后都无法启动

### ISSUE THREAD

**Issue by wangwen6666** [ophub/amlogic-s9xxx-armbian#1592]
MGV3000试了一下8月份的4个包（jammy、lunar、bullseye、bookworm的6.1.42），刷了emmc后都无法启动。没办法又回退到Armbian_23.08.0_amlogic_s905l2_jammy_6.1.35_server_2023.06.21.img了

**Comment by ophub** [comment]
用5.15的
