### ISSUE TITLE
创维代工mgv2000 s905l2 没有WIFi无线（7668网卡）

### ISSUE THREAD

**Issue by a65101855** [ophub/amlogic-s9xxx-armbian#1593]
创维代工mgv2000 s905l2 7668无线 版本，刷的TOOL里的MGV2000包，发现不能使用无线，且刷armbian也是没有无线

**Comment by ophub** [comment]
mt7668 wifi和蓝牙测试内核及使用方法： https://github.com/ophub/amlogic-s9xxx-armbian/issues/3610#issuecomment-5091652991
