### ISSUE TITLE
does not start on the box TOX1 (S905X3)

### ISSUE THREAD

**Issue by serj-47** [ophub/amlogic-s9xxx-armbian#1596]
**Device Information | 设备信息**
 - SOC: [ S905x3]
 - Model [TOX1]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.42)
 - Release: [bullseye]
(Armbian_bullseye_save_2023.08/Armbian_23.08.0_amlogic_s905x3_bullseye_6.1.42_server_2023.08.01.img.gz)

I installed the image on a USB flash using balenaetcher. After that, I insert the flash drive into the box, but the armbian does not load. Just a stock android is loaded and that's it. I also tried using microsd, but it also load android instead of armbian. I want to note that I already have a ready-made microsd card with a different Core elec image, and TOX1 loads from it without any problems right away! I remember that when I created coreelec image, then I had problems with the dtb file couldn't find the right file for a long time.
Maybe now I have a similar problem on armbian, hence the question,
How exactly do correctly specify the path to the dtb file and do I need to do it at all?

When connecting to the box via ssh with coreelec installed, I get this message..
_CoreELEC (official): 20.2-Nexus (Amlogic-ng.arm)
      Machine model: Amlogic
     CoreELEC dt-id: **sm1_s905x3_4g_1gbit**_

**Comment by serj-47** [comment]
When connecting to the box via ssh with coreelec installed, I get this message..
_CoreELEC (official): 20.2-Nexus (Amlogic-ng.arm)
      Machine model: Amlogic
     CoreELEC dt-id: **sm1_s905x3_4g_1gbit**_

**Comment by ophub** [comment]
look at documents

**Comment by serj-47** [comment]
I looked at the instructions for amlogic, it says simply, write the image to a usb flash drive, insert it into the box and the download will begin). I didn't find any more detailed information. I tried to turn on the box with the reset button clamped, tried usb/microusb, but it didn't help. But still I managed to solve the problem. In Android, I installed a terminal emulator and performed a 'reboot update' there, after that the tvbox rebooted in stock android recovery, and there I selected the reboot item, and now armbian normally loads both usb-flash and microsd. You can add the TOX1 box to the list of supported..)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/amlogic/bootfs/dtb/amlogic/meson-sm1-sei610.dtb

What is the difference between your file and this one? What was modified?

**Comment by serj-47** [comment]
[sei-2_ethtool.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/12317547/sei-2_ethtool.txt)
[sei-2_lsmod.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/12317548/sei-2_lsmod.txt)
[sei_ethtool.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/12317549/sei_ethtool.txt)
[sei_lsmod.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/12317550/sei_lsmod.txt)

**Comment by ophub** [comment]
/boot/uEnv.txt
更改其中的dtb文件名为 meson-sm1-sei610.dtb，保存，重启洲试
