### ISSUE TITLE
中国移动B860AV-2.1M可以启动armbian了，但串口有些问题

### ISSUE THREAD

**Issue by aolin2000** [ophub/amlogic-s9xxx-armbian#1598]
1，魔百盒B860AV-2.1M，SoC为S905L3B，原装固件不支持U盘启动，需要先刷一个安卓9.0的固件，我随便找了一个S905L3B的固件，刷机后，安卓无法启动到桌面系统，但支持u盘启动，无所谓了
2，下载armbian Armbian_23.08.0_amlogic_s905l3b_bullseye_5.15.123_server_2023.08.01.img.gz，试过6.x的版本都无法启动
3，将armbian镜像写入U盘
4，U盘插入盒子，开机，在开机过程中不断按回车键，以中断uboot，在uboot命令行运行
run update
执行后，uboot会重启，并从u盘启动系统，之后，每次上电都会自动从U盘启动armbian

5，armbian启动后，实测有线网络工作正常，但无线网络没有驱动(wifi为MT7688)

串口输出：

```
Armbian 23.08.0-trunk Bullseye ttyAML0 

armbian login: root
Password: 
    _              _      ____  ___   ___  ____  _ _____ _     
   / \   _ __ ___ | |    / ___|/ _ \ / _ \| ___|| |___ /| |__  
  / _ \ | '_ ` _ \| |____\___ \ (_) | | | |___ \| | |_ \| '_ \ 
 / ___ \| | | | | | |_____|__) \__, | |_| |___) | |___) | |_) |
/_/   \_\_| |_| |_|_|    |____/  /_/ \___/|____/|_|____/|_.__/ 
                                                               
Welcome to Armbian 23.08.0-trunk Bullseye with Linux 5.15.123-ophub

System load:   55%              Up time:       1 min
Memory usage:  14% of 803M      IP:            192.168.35.86
CPU temp:      57掳C            Usage of /:    37% of 3.3G   
storage/:      52% of 252M   
RX today:      n/a        

Last login: Tue Aug  1 12:48:49 CST 2023 on tty1
root@armbian:~# ip route del default
Error: any valid prefix is expected rather than "default".
root@armbian:~# ip routedel default
Object "routedel" is unknown, try "ip help".
```

串口console有点问题，输入命令时，有时会带入一些多余的非法字符，比如上面我输入ip route del default
却会变成ip route del de  fault，导致经常需要重输命令
已经确认串口的物理连接是正常的，因为在uboot与安卓系统下都是正常的，只是在armbian下有这个问题

请问大佬，这个会是什么原因引起的，怎么解决?
谢谢！

**Comment by antjzone** [comment]
我也有这个盒子，请问用的哪个android固件

**Comment by aolin2000** [comment]
> 我也有这个盒子，请问用的哪个android固件
刷一个CM211-1安卓9.0的固件，我不记得是哪里下载的了，刷完进不了安卓桌面，卡在启动画面了，但它的bootloader支持从U盘启动，所以可以启动armbian

**Comment by ophub** [comment]
感谢分享，B860AV-2.1M（s905l3b）设备已经加入支持列表了。
https://github.com/ophub/amlogic-s9xxx-armbian/commit/c8dfbba2effc6fa4f278901d98cfa98527f30db7

https://github.com/ophub/amlogic-s9xxx-armbian/commit/85e1680ed0b99bf1b432778144891d6be0ca249d

**Comment by LouisFonda** [comment]
> 我也有这个盒子，请问用的哪个android固件

链接：https://pan.baidu.com/s/18fnWxVpGiLHJnwFKmPRtLw 
提取码：qswl
应该只要不是高安版的盒子都是可以的，我也是这个盒子不过我的是电信的B860AV-2.1T高安版，根本就刷不进，不是高安版的可以试一下，应该B860AV-2.1T(非高安)也能按这个方法U盘启动armbian

**Comment by xiaodiao216** [comment]
> 1，魔百盒B860AV-2.1M，SoC为S905L3B，原装固件不支持U盘启动，需要先刷一个安卓9.0的固件，我随便找了一个S905L3B的固件，刷机后，安卓无法启动到桌面系统，但支持u盘启动，无所谓了 2，下载armbian Armbian_23.08.0_amlogic_s905l3b_bullseye_5.15.123_server_2023.08.01.img.gz，试过6.x的版本都无法启动 3，将armbian镜像写入U盘 4，U盘插入盒子，开机，在开机过程中不断按回车键，以中断uboot，在uboot命令行运行 run update 执行后，uboot会重启，并从u盘启动系统，之后，每次上电都会自动从U盘启动armbian
> 
> 5，armbian启动后，实测有线网络工作正常，但无线网络没有驱动(wifi为MT7688)
> 
> 串口输出：
> 
> ```
> Armbian 23.08.0-trunk Bullseye ttyAML0 
> 
> armbian login: root
> Password: 
>     _              _      ____  ___   ___  ____  _ _____ _     
>    / \   _ __ ___ | |    / ___|/ _ \ / _ \| ___|| |___ /| |__  
>   / _ \ | '_ ` _ \| |____\___ \ (_) | | | |___ \| | |_ \| '_ \ 
>  / ___ \| | | | | | |_____|__) \__, | |_| |___) | |___) | |_) |
> /_/   \_\_| |_| |_|_|    |____/  /_/ \___/|____/|_|____/|_.__/ 
>                                                                
> Welcome to Armbian 23.08.0-trunk Bullseye with Linux 5.15.123-ophub
> 
> System load:   55%              Up time:       1 min
> Memory usage:  14% of 803M      IP:            192.168.35.86
> CPU temp:      57掳C            Usage of /:    37% of 3.3G   
> storage/:      52% of 252M   
> RX today:      n/a        
> 
> Last login: Tue Aug  1 12:48:49 CST 2023 on tty1
> root@armbian:~# ip route del default
> Error: any valid prefix is expected rather than "default".
> root@armbian:~# ip routedel default
> Object "routedel" is unknown, try "ip help".
> ```
> 
> 串口console有点问题，输入命令时，有时会带入一些多余的非法字符，比如上面我输入ip route del default 却会变成ip route del de fault，导致经常需要重输命令 已经确认串口的物理连接是正常的，因为在uboot与安卓系统下都是正常的，只是在armbian下有这个问题
> 
> 请问大佬，这个会是什么原因引起的，怎么解决? 谢谢！

我想问下：
1、用的是哪个dtb文件启动的armbian？
2、hdmi是否有输出？

**Comment by zhangbo-1989** [comment]
@aolin2000   @ophub 你好，用u盘启动后，连接盒子的屏幕有显示跑码么？我这边什么都不显示，也不知道是否启动成功

**Comment by ophub** [comment]
有些盒子的hdmi不显示，到接入的陆游器里找armbian的ip

**Comment by zhangbo-1989** [comment]
> 有些盒子的hdmi不显示，到接入的陆游器里找armbian的ip

如果路由器中没有找到armbian设备就说明U盘没有启动成功？

**Comment by zhangbo-1989** [comment]
@ophub 我的设备是 中国移动 ZXV10 B860AV-2.1A2（芯片是s905l3）该用哪个固件，只能一个个试了么？

**Comment by antjzone** [comment]
一个网口刷openwrt，网口不是lan吗，得连电脑登进去

**Comment by zhangbo-1989** [comment]
> 一个网口刷openwrt，网口不是lan吗，得连电脑登进去

谢谢，是用ssl登录吗？

**Comment by wjw010224** [comment]
b860av2.1 使用哪个dtb

**Comment by gundamken** [comment]
请问我搞了台联通的TV盒子，ZXV10 B860AV2.2 这个能刷吗？

**Comment by hn-liuzuen** [comment]
中国电信盒子，ZXV10 B860AV2.1-T 这一款应该怎么处理？

**Comment by WalkingDead-Chen** [comment]
这个跟中国移动B860AV-2.1A是固件通用吗？

**Comment by daolaof** [comment]
中兴B860AV-2.1 南传 能用吗？数字后面没有任何字母，如果不能用，选哪个呢？

**Comment by benknam** [comment]
> 中兴B860AV-2.1 南传 能用吗？数字后面没有任何字母，如果不能用，选哪个呢？

我的也是南传的移动盒子，ZXV10 B860AV2.1，目前用Armbian官网给TV盒子的包是没问题的，HDMI和有线网是工作的。WIFI蓝牙不工作，EMMC认不了，估计就是NAND的。当旁漏油还是不错的。

**Comment by liyiranlab** [comment]
ZXV10 B860AV2.1-M 搞了一晚上，最后用 https://www.right.com.cn/forum/thread-8297312-1-1.html 原生系统，安装终端工具apk，用命令 reboot update 成功引导 TF卡，ophub固件 Armbian_24.5.0_amlogic_s905l3b_bookworm_6.6.28_server_2024.05.02.img 。

**Comment by liyiranlab** [comment]
这个dtb，不支持tf卡槽。浪费了

**Comment by cameronyq** [comment]
> 有些盒子的hdmi不显示，到接入的陆游器里找armbian的ip

嗯 遇到了hdmi不显示 ttl看码就是卡住显示检测

是否可以参考使用 https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/led_screen_display_control.md
来修改参数达到显示的目的？

**Comment by zhelunofficial** [comment]
> Armbian

老哥,我终端工具能分享一下吗

**Comment by cameronyq** [comment]
感谢 已经解决 好帖 赞一个

**Comment by Chaones** [comment]
b860av3.1-U可以刷入开机，但没有声卡3.5mm不能正常使用。
有什么方法能修复吗？

**Comment by mrsoshining** [comment]
> [@ophub](https://github.com/ophub) 我的设备是 中国移动 ZXV10 B860AV-2.1A2（芯片是s905l3）该用哪个固件，只能一个个试了么？

我还翻出个这么个盒子，找到对应的固件了吗？我已经试了好多了都不行
