### ISSUE TITLE
在使用armbian-install时找不到emmc

### ISSUE THREAD

**Issue by LongC-CN** [ophub/amlogic-s9xxx-armbian#1599]
**Device Information | 设备信息**
 - SOC: S905L2
 - Model MGV2000-K

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.123-ophub
 - Release: Armbian 23.08.0-trunk Jammy

**Describe the bug | 问题描述**
在使用armbian-install时找不到emmc
我已经尝试过更换内核，更换#946中的dtb文件,但是都没有作用,似乎需要修改dtb文件改变频率，但是我没有找到教程，请问有没有大佬可以提供一下
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/61483728/ff7f70bb-3ccc-4040-9ec1-e26d5eed0dd1)

**Comment by ophub** [comment]
看仓库里的文档
