### ISSUE TITLE
可以尝试修复斐讯n1蓝牙吗

### ISSUE THREAD

**Issue by louliangsheng** [ophub/amlogic-s9xxx-armbian#16]
可以尝试修复斐讯n1蓝牙吗
![image](https://user-images.githubusercontent.com/37586254/140754140-85f2af41-5fce-4652-b625-51686427a45e.png)

**Comment by ophub** [comment]
Try: armbian-config > Network > BT install (Install Bluetooth support)

**Comment by louliangsheng** [comment]
I have installed it. I can turn on Bluetooth but can't scan.

**Comment by ophub** [comment]
```
rfkill unblock all
bluetoothctl power on
```

**Comment by louliangsheng** [comment]
I haven't tried the command rfkill unblock all yet. My Bluetooth can be turned on but can't be scanned, and I can't turn it on through power on after I try to turn it off. I'll try the command rfkill unblock all after work.

**Comment by louliangsheng** [comment]
And it's strange that Bluetooth in 5.10 kernel can't be turned on, and 5.4 kernel can be turned on.

https://www.right.com.cn/forum/thread-517710-1-1.html

**Comment by ophub** [comment]
`armbian-update 5.4.158`
You can update to 5.4 by switching the kernel.

**Comment by louliangsheng** [comment]
Have you tested the N1 firmware? Can Bluetooth work normally? 
I think it can work normally for a short period of time after it is started up, and then it won't work

**Comment by louliangsheng** [comment]
I have installed homebridge and want to use the homebridge-mi-hyperthermograph plug-in. The plug-in address is: https://github.com/hannseman/homebridge-mi-hygrothermograph

**Comment by ophub** [comment]
I don't use bluetooth.

I use flippy to compile the kernel package for OpenWrt. See his source code: https://github.com/unifreq

You can compile your own personalized kernel, he is more clear about the kernel issues.

**Comment by fooy** [comment]
> And it's strange that Bluetooth in 5.10 kernel can't be turned on, and 5.4 kernel can be turned on.
> 
> https://www.right.com.cn/forum/thread-517710-1-1.html

thanks for pointing it out , i think i have managed to make this work in 5.10.y by following this lead .

just diff the difference between flippy code 5.4.xx and 5.10.y , the BT fix made by https://github.com/yangxuan8282/ ... ogic/bt-btbcm.patch hasn't merged to 5.10.y . so i just copy and paste it .

detail: 
~/amlogic-s9xxx-armbian/compile-kernel/kernel/linux-5.10.y$ git diff --stat
 arch/arm64/boot/dts/amlogic/meson-gx-p23x-q20x.dtsi | 16 ++++++++++++++++
 drivers/bluetooth/btbcm.c                           |  2 +-
 2 files changed, 17 insertions(+), 1 deletion(-)

~/amlogic-s9xxx-armbian/compile-kernel/kernel/linux-5.10.y$ git diff 
diff --git a/arch/arm64/boot/dts/amlogic/meson-gx-p23x-q20x.dtsi b/arch/arm64/boot/dts/amlogic/meson-gx-p23x-q20x.dtsi
index 6b57e15aa..1078508a5 100644
--- a/arch/arm64/boot/dts/amlogic/meson-gx-p23x-q20x.dtsi
+++ b/arch/arm64/boot/dts/amlogic/meson-gx-p23x-q20x.dtsi
@@ -311,6 +311,22 @@ &sd_emmc_c {
        vqmmc-supply = <&vddio_boot>;
 };
 
+/* This UART is connected to the Bluetooth module */
+&uart_A {
+       status = "okay";
+       pinctrl-0 = <&uart_a_pins>, <&uart_a_cts_rts_pins>;
+       pinctrl-names = "default";
+       uart-has-rtscts;
+
+       bluetooth {
+               compatible = "brcm,bcm43438-bt";
+               shutdown-gpios = <&gpio GPIOX_17 GPIO_ACTIVE_HIGH>;
+               max-speed = <2000000>;
+               clocks = <&wifi32k>;
+               clock-names = "lpo";
+       };
+};
+
 /* This UART is brought out to the DB9 connector */
 &uart_AO {
        status = "okay";
diff --git a/drivers/bluetooth/btbcm.c b/drivers/bluetooth/btbcm.c
index 1b9743b7f..5cd74dd2a 100644
--- a/drivers/bluetooth/btbcm.c
+++ b/drivers/bluetooth/btbcm.c
@@ -396,7 +396,7 @@ static const struct bcm_subver_table bcm_uart_subver_table[] = {
        { 0x6109, "BCM4335C0"   },      /* 003.001.009 */
        { 0x610c, "BCM4354"     },      /* 003.001.012 */
        { 0x2122, "BCM4343A0"   },      /* 001.001.034 */
-       { 0x2209, "BCM43430A1"  },      /* 001.002.009 */
+       { 0x2209, "BCM43438A1"  },      /* 001.002.009 */
        { 0x6119, "BCM4345C0"   },      /* 003.001.025 */
        { 0x6606, "BCM4345C5"   },      /* 003.006.006 */
