### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#160]
hello, i have this version
Armbian_20.10_Arm-64_buster_current_5.9.0.img  im x96 Max Plus running perfectly on my box, the only thing I changed was extlinux.conf to boot with a dtb meson-sm1-sei160.dtb, I'm trying to get this in the Armbian_22 version. 02.1_Aml_s905x3 could you help me??

note: installation script
[install-aml.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8238322/install-aml.txt)

**Comment by ophub** [comment]
The meson-sm1-sei610.dtb file is in the firmware, you can use it by changing Armbian_22 version. 02.1_Aml_s905x3 /boot/uEnv.txt.

**Comment by tv4you2016** [comment]
ok I flashed the pen and edited the uEnv.txt file to meson-sm1-sei610.dtb looking like this:

[uEnv.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8239261/uEnv.txt)

I booted and in:
set model list
I put the following settings:
s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:NA:NA:

I waited until it appeared:
"Successful installed, please unplug the USB, re-insert the power supply to start the armbian."

 I did what is described only then it is in loop on the screen where it says X96 max+

**Comment by ophub** [comment]
You can add a line of installation information in /usr/sbin/armbian-install yourself, and choose your own serial number to install.
Selecting 0 can only fill in dtb, so custom dtb is only supported in 5.4.

**Comment by ophub** [comment]
What device are you using meson-sm1-sei610.dtb? What combination have you tested for other u-boot and other information?

**Comment by tv4you2016** [comment]
Armbian_20.10_Arm-64_buster_current_5.9.0.img
UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
FDTFILE="meson-sm1-sei610.dtb"

what more information do you need?

with version version 5.4. it doesn't even boot to the pen ( uEnv.txt is equal to version 5.9.0 )

**Comment by tv4you2016** [comment]
i think the problem is when i run armbian-install,

can you buy with this version that is working?
[install-aml.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8239499/install-aml.txt)

**Comment by ophub** [comment]
meson-sm1-sei610.dtb is a general public version. Are you x96max plus? s905x3? Gigabit wired?

**Comment by ophub** [comment]
You can add a line of installation information in /usr/sbin/armbian-install yourself

**Comment by tv4you2016** [comment]
X96 Max PlusQ1. Without chip 1000Mb. LAN 100, Cdtech 4761743 radio module and two antennas. 
![IMG_20210109_154247](https://user-images.githubusercontent.com/83761813/158059525-f0c6e3ca-2768-404e-98f5-f8157506ffd7.jpg)

**Comment by tv4you2016** [comment]
> You can add a line of installation information in `/usr/sbin/armbian-install` yourself

what command should I add to have more information that is needed?

**Comment by ophub** [comment]
You can choose `51` to install on your device

**Comment by tv4you2016** [comment]
![Capturar](https://user-images.githubusercontent.com/83761813/158060384-d9df5f33-fbf9-4692-8da9-a467dfdf9577.PNG)

I rebooted
now I don't have eth
![IMG_20220313_125540](https://user-images.githubusercontent.com/83761813/158060433-f7cbc6f6-6415-415b-8dea-e6b3cc78ffdd.jpg)

**Comment by ophub** [comment]
Didn't you say you tested this meson-sm1-sei610.dtb to work, so you want to modify it like this? Now your modified method is correct.

**Comment by tv4you2016** [comment]
Yes it works, but correctly before running armbian-install, make me understand?

Steps:

1- I create a pen with the img Armbian_20.10_Arm-64_buster_current_5.9.0.img and wait for it to finish.

2-> Then I go to the uEnv.txt file and edit:
FDTFILE="meson-sm1-sei610.dtb"
 
3-> I boot with the pen in the box and everything works with show (eth0),

4-> I run armbian-install and wait for it to end, I reboot the box and I no longer have eth

**Comment by ophub** [comment]
Armbian_20.10_Arm-64_buster_current_5.9.0.img is not my firmware and I don't understand his settings.

The modification method of the installation file of my firmware is the above method.

**Comment by tv4you2016** [comment]
sorry Armbian_20.10_Arm-64_buster_current_5.9.0.img I was not what I meant Armbian_22. 02.1_Aml_s905x3

**Comment by ophub** [comment]
Before writing emmc, the default dtb file of s905x3 in usb is `meson-sm1-x96-max-plus-100m.dtb`

**Comment by tv4you2016** [comment]
Yes I know but I edited the file to this:

51:X96 Max+:s905x3:meson-sm1-x96-max-plus.dtb:u-boot-x96maxplus.bin:/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin:/usr /lib/u-boot/hk1box-bootloader.img:4C@2100Mhz,4GB Mem,1Gb Nic,rtl8822cs wifi

**Comment by ophub** [comment]
71:X96 Max:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:NA:NA:4C@2100Mhz

**Comment by tv4you2016** [comment]
I'll test it, I'll give you feedback

**Comment by tv4you2016** [comment]
> 


> 71:X96 Max:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:NA:NA:4C@2100Mhz

does not work is always on img X96 max +

**Comment by tv4you2016** [comment]
how can i backup the original files and working:

UBOOT_OVERLOAD 
MAINLINE_UBOOT 
ANDROID_UBOOT

**Comment by ophub** [comment]
Unknown devices cannot be arbitrarily filled with mainline-uboot and other write files, and they will not work.

**Comment by tv4you2016** [comment]
> Unknown devices cannot be arbitrarily filled with mainline-uboot and other write files, and they will not work.
> 
> only use 5.4 kernel to try

I'll test it only use 5.4 kernel to try, I'll give you feedback

**Comment by tv4you2016** [comment]
Files (\usr\lib\u-boot\) used in kernel 5.9.0 

[odroid.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8239889/odroid.txt)
[platform_install.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8239890/platform_install.txt)

**Comment by tv4you2016** [comment]
> Unknown devices cannot be arbitrarily filled with mainline-uboot and other write files, and they will not work.
> 
> only use 5.4 kernel to try

with this version it works 

Armbian_22.05.0_Aml_s905x3_focal_5.4.184_2022.03.12.2318.img

71:X96 Max:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:NA:NA:4C@2100Mhz

**Comment by tv4you2016** [comment]
![image](https://user-images.githubusercontent.com/83761813/158065707-74a775af-6ee9-4480-becb-b99965018086.png)

**Comment by ophub** [comment]
\usr\lib\u-boot The files here are limited to 5.10 and later kernels, not needed for 5.4

**Comment by tv4you2016** [comment]
![IMG_20220313_150101](https://user-images.githubusercontent.com/83761813/158065901-28ff7d9e-fca1-4fcd-87d2-e94bb08a8122.jpg)
 WARNING

**Comment by tv4you2016** [comment]
What debug (files , etc ) do you think I should check to get it working in kernel version 5.10 and later ??

**Comment by ophub** [comment]
71:X96 Max:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:u-boot-x96maxplus.bin:NA:4C@2100Mhz

try for 5.15 kernel

**Comment by tv4you2016** [comment]
> 71:X96 Max:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:u-boot-x96maxplus.bin:NA:4C@2100Mhz
> 
> try for 5.15 kernel

I'll test it only use  5.15.27 and 5.15.28 kernel to try, I'll give you feedback

**Comment by tv4you2016** [comment]
kernel 5.15.28

71:X96 Max:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:u-boot-x96maxplus.bin:NA:4C@2100Mhz

not  working
