### ISSUE TITLE
ssh分时间频繁随机断开并conn-refuse一段时间

### ISSUE THREAD

**Issue by zhangjing-GitHub-Code** [ophub/amlogic-s9xxx-armbian#1600]
### *刚刚执行armbian-fix，先做一下备份*
**Device Information | 设备信息**
 - SOC: [S905l3a]
 - Model [E900V22C]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.123]
 - Release: [jammy]

**Describe the bug | 问题描述**
当我用手机上的termux ssh( android 12, wifi )(盒子是原装网线) 连接盒子时，它会随机的断开连接:`client_loop: send disconnect: Broken pipe`，我甚至还是把termux在手机前台看着它断的。如果我立马重新连接，ssh报错
```
ssh: connect to host -ip- port 22: Connection refused
```
，该现象通常持续10~30秒，或者几分钟，然后可以连接。
但是，在我连上的几秒后，它又断开了，与上面一样。
刷入的是近一个月前ophub actions编译的.123 jammy版本，为Kingston Exodia 64G。
我刚刚两天貌似是11/12点前十几分钟有这样情况
登陆后抓紧看systemctl status sshd和dmesg没看出什么问题，机器和ssh uptime都很长。
就是前几天有一次长达2分多钟(没注意计)，登录进去发现机器uptime重启。
[这次dmesg](https://pastebin.com/3TGpi2Ra)
刚刚运行`armbian-fix`，先等一下下一次触发

这个u盘经历:
购买
用windows10写入50MB测速文件
用另一个u盘 armbian在盒子上:
 ~ 写入~200MB测速文件
 ~ 用dd+hexdump查看分区数据(尝逝摸索FAT32结构.gif)
win10:
 ~ DG:
    ~  备份原FAT32数据扇区
 ~ Rufus 4.12(?) 写入img
 ~ DG:
    ~ 调整分区大小 2G->20G
armbian:
 ~ ssh登录，发现dmesg resize rootfs失败
 ~ fsck.ext4，重启 (若干次)
 ~ 发现不行
 ~ 去另一个armbian
原armbian:
 ~ resize2fs成功
 ~ 查看分区表，发现rootfs成了60多G(谢谢你DG)
armbian:
 ~ 之后就这么用了，开始出现断开问题

**Comment by ophub** [comment]
U盘写入img后，就不要用dg等工具去改分区了。
armbian初次启动时会自动检查分区，自动把U盘剩余空间扩容到系统rootfs分区。

**Comment by zhangjing-GitHub-Code** [comment]
ooo
我以为不会，还想着系统内调整麻烦(
有进一步问题我在汇报

**Comment by zhangjing-GitHub-Code** [comment]
嗯mmmm
还观察到一些问题，
就可能是5.15.123这个kernel
机器uptime超过18(?)小时后，执行一些命令会segmentation fault，包括`apt`,`ip a`，具体错误的命令比较随机，dmesg因为我装了docker所以有一堆网卡切换，而且被logrotate了。
（甚至我想拿gdb调试core dump（不会），然后gdb segmentation fault）
这个情况在`Kingston Datatraveler Exodia 128G`(不确定是不是杂牌生产)出现，同品牌64G那个之前刷的系统现在开机（就上面提到的）会直接kernel panic。
重启后基本正常
这个新盘DG备份了下分区（几乎空的）就直接rufus了。
`armbian-fix`貌似执行过。
难道5.15.123有毒？
我之前一个杂牌卡IO U盘，内核（固件）比这个早几月，没出现过这情况。
尝试刷写6.x.x内核。。。
需要进一步分析我可以提供core/dmesg

**Comment by zhangjing-GitHub-Code** [comment]
很怪，刚刚apt任何命令无法使用，file无法使用，ip a能用，dpkg能用，直接gdb无错误
