### ISSUE TITLE
bullseye 6.1.42 无法启动，5.15.123可以

### ISSUE THREAD

**Issue by trigsoft** [ophub/amlogic-s9xxx-armbian#1601]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model 魔百和m401

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.42
 - Release: bullseye

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

5.15.123u盘启动没问题，6.1.42u盘无法启动，就是黑屏。

**Comment by ophub** [comment]
差异是多了个u-boot，不能启动说明u-boot不匹配，不想尝试更换安卓或测试哪个u-boot，就使用5.15也是极好的，

**Comment by trigsoft** [comment]
> 差异是多了个u-boot，不能启动说明u-boot不匹配，不想尝试更换安卓或测试哪个u-boot，就使用5.15也是极好的，

我想装homeassistant supervised. 安装os agent得时候好多包在5.15都不匹配。5.15是不也可以u-boot启动？这两个不一样吗？

**Comment by ophub** [comment]
有HA的时候还没6.1，之前4.x的时候都可以用，所有和内核无关

**Comment by trigsoft** [comment]
> 有HA的时候还没6.1，之前4.x的时候都可以用，所有和内核无关

你说的是supervised的版本吗？

**Comment by ophub** [comment]
https://github.com/home-assistant/supervised-installer

**Comment by trigsoft** [comment]
> https://github.com/home-assistant/supervised-installer

在安装systemd-resolved就失败了，后面还有很多包的版本不匹配的情况。你说的4.x安装的ha是supervised吗？

**Comment by ophub** [comment]
https://blog.csdn.net/lky213/article/details/121280969


2021年别人就在bullseye上安装Home Assistant Supervised & HACS，而6.1.y是2022年底发布的最后一个版本才发布出来的，所以不可能要求使用6.1.y。而且bullsyse发布的时候3年前，那时连5.15也没发布。

**Comment by luckywaa** [comment]
> > https://github.com/home-assistant/supervised-installer
> 
> 在安装systemd-resolved就失败了，后面还有很多包的版本不匹配的情况。你说的4.x安装的ha是supervised吗？

我也是一样的问题，最新版installer不能用，但是1.4.3可以用
