### ISSUE TITLE
E900V22E (s905l3b) 无法写入emmc

### ISSUE THREAD

**Issue by ok805** [ophub/amlogic-s9xxx-armbian#1603]
****Device Information | 设备信息**
 - SOC: S905L3B
 - Model e900v22e

**Armbian Version | 系统版本**    Armbian 23.08.0-trunk
 - Kernel Version:  6.1.42
 - Release: [e.g. jammy/bullseye]  Bullseye 

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但任然可以长期继续跟帖讨论。

armbian-install 提示 
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ yes ]
[ INFO ] Using ampart tool: [ no ]
[ INFO ] Show all lists: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
ID    SOC        MODEL                               DTB
121   s905l3b    E900V21E,E900V22E                   meson-gxl-s905l3b-e900v22e.dtb
0     Other      Customize                           Enter-custom-dtb-name

[ OPTIONS ] Please Input ID: 121
[ INFO ] Input Box ID: [ 121 ]
[ INFO ] Model Name: [ E900V21E,E900V22E ]
[ INFO ] FDTFILE: [ meson-gxl-s905l3b-e900v22e.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-s905x-s912.bin ]
[ INFO ] NEED_OVERLOAD: [ yes ]
[ STEPS ] Which type of filesystem do you want for your root?

  1    ext4
  2    btrfs

[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
dd: error reading '/dev/mmcblk2': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 0.026964 s, 0.0 kB/s
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader.img ] failed.

root@armbian:~# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda            8:0    1  58.2G  0 disk
├─sda1         8:1    1   255M  0 part /boot
└─sda2         8:2    1    58G  0 part /
mmcblk2      179:0    0   7.3G  0 disk
mmcblk2boot0 179:32   0     4M  1 disk
mmcblk2boot1 179:64   0     4M  1 disk
zram0        254:0    0 965.5M  0 disk [SWAP]
zram1        254:1    0    50M  0 disk /var/log

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
无法写入 emmc
金士顿 D2516ECMDXGJD
三星  KLM8G1GETF
![13a1bd3aad7ab023ab7e201706364b0](https://github.com/ophub/amlogic-s9xxx-armbian/assets/23020845/3dda5fd8-4848-415d-ab92-c6f92346ffb6)**

**Comment by ophub** [comment]
看文档，试试降低频率能不能正常读写

**Comment by ok805** [comment]
降低到 320000  可以了
[ INFO ] Generate the new fstab file.
[ INFO ] Update the relevant parameters.
[ SUCCESS ] Installation successful. Run [ poweroff ], remove the installation media then re-insert the power supply to boot new system.
root@armbian:~#

😱 
断电重启  ip找不到了 

hdmi 不能正常显示
有什么解决办法吗？

**Comment by ophub** [comment]
ip到接入的路由器里找。

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

下载安卓，先刷下这个安卓再刷armbian试试。

**Comment by ok805** [comment]
明天尝试下，先能不能键盘盲操作试试

**Comment by ok805** [comment]
已解决,换了个路由器他就又找得到IP了
感谢

**Comment by ok805** [comment]
记录下 降低emmc频率的方法
sudo apt-get install -y device-tree-compiler
# 1. 反编译命令（使用 dtb 文件生成 dts 源码）
dtc -I dtb -O dts -o xxx.dts xxx.dtb
生成的dts文件用文本编辑打开
修改里面的 
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/23020845/4c1ab2ec-c4f2-4a73-946d-03fadcd2f9be)

这几个频率
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/23020845/b0fc6d8f-44d9-4eb5-81e5-1538c69d6d1d)

# 2. 编译命令（使用 dts 编译生成 dtb 文件）
dtc -I dts -O dtb -o xxx.dtb xxx.dts

生成了 dtb 文件 替换 /boot/dtb/amlogic/
uEnv.txt 文件中的 FDT=/dtb/amlogic/xxxxx.dtb
重启 
armbian-install
