### ISSUE TITLE
Lenovo Leez P710 申请添加

### ISSUE THREAD

**Issue by inoeud** [ophub/amlogic-s9xxx-armbian#1609]
1、硬件配置
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37056214/cedae109-6e6c-4ff3-8a8b-d281f92c80eb)

Type-C PD 供电，紧贴近当前的主流设计，使用方便。（_这玩意是pd？不清楚_）
带有 RJ45 以太网口，这个传统嵌入式玩家一定非常喜欢，在 u-boot 下可以通过以太网做 tftp升级，在做高版本内核移植的时候，Wifi  的功能如果暂时不可用，以太网       也是很方便的接口，目前以太网功能基本在各个版本的内核中都可以很方便的用起来。
USB 接口丰富，可以接键盘[鼠标](https://www.smzdm.com/fenlei/shubiao/)。

4 GB 内存，16GB Emmc这和 RK3399 强悍的性能很配，用来跑重型任务也不怕内存不够用了。
（复制自https://post.smzdm.com/p/akm7dwr9/）

官方仓库：
https://github.com/leezsbc/resources

第三方Armbian固件：
卡启 debian 10桌面, wayland驱动，3D加速正常
链接：https://pan.baidu.com/s/12KJJ5YPulNNd00yZYj6Fdw 
提取码：6y0x

据说可以uefi的uboot：
[lenovo_leez_p710资料 - 副本.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12327347/lenovo_leez_p710.-.zip)
"按地址写入emmc，支持efi启动，支持system ready认证里列出的系统
不知道和官方uboot有啥区别，总之能用"
(引自网友)

**Comment by inoeud** [comment]
https://cloud.tencent.com/developer/article/1571935

**Comment by ophub** [comment]
我根据你提供的镜像文件，复制了其中的u-boot文件。
你到releases里下载测试下是否可以使用，试试6.1.y系列的这个镜像，我看到kernel里从5.4到6.1都自带了这个rk3399-leez-p710.dtb文件，所以理论上各版本都默认支持使用。

**Comment by inoeud** [comment]
change freq to 856MHz 1,0
ch 0 ddrconfig = 0x101, ddrsize = 0x40
ch 1 ddrconfig = 0x101, ddrsize = 0x40
pmugrf_os_reg[2] = 0x32C1F2C1, stride = 0xD
OUT
Boot1 Release Time: Jun  2 2020 15:02:17, version: 1.26
CPUId = 0x0
SdmmcInit=2 0
BootCapSize=100000
UserCapSize=14910MB
FwPartOffset=2000 , 100000
##############serialno_str = DHXH1PQW7T
UsbBoot ...73349
powerOn 85620

U-Boot TPL 2020.01-rc4-armbian (Dec 04 2019 - 18:46:41)
Channel 0: LPDDR4, 50MHz
BW=32 Col=10 Bk=8 CS0 Row=16/15 CS=1 Die BW=16 Size=2048MB
Channel 1: LPDDR4, 50MHz
BW=32 Col=10 Bk=8 CS0 Row=16/15 CS=1 Die BW=16 Size=2048MB
256B stride
256B stride
lpddr4_set_rate: change freq to 400000000 mhz 0, 1
lpddr4_set_rate: change freq to 800000000 mhz 1, 0
Trying to boot from BOOTROM
Returning to boot ROM...

U-Boot SPL 2020.01-rc4-armbian (Dec 04 2019 - 18:46:41 +0800)
Trying to boot from MMC2


U-Boot 2020.01-rc4-armbian (Dec 04 2019 - 18:46:41 +0800)

Model: Leez RK3399 P710
DRAM:  3.9 GiB
PMIC:  RK808 
Cannot find regulator pwm init_voltage
MMC:   dwmmc@fe310000: 2, dwmmc@fe320000: 1, sdhci@fe330000: 0
Loading Environment from MMC... *** Warning - bad CRC, using default environment

In:    serial@ff1a0000
Out:   serial@ff1a0000
Err:   serial@ff1a0000
Model: Leez RK3399 P710
rockchip_dnl_key_pressed: adc_channel_single_shot fail!
Net:   
Error: ethernet@fe300000 address not set.
eth-1: ethernet@fe300000
Hit any key to stop autoboot:  0 
switch to partitions #0, OK
mmc0(part 0) is current device
Scanning mmc 0:1...
Found U-Boot script /boot.scr
3252 bytes read in 15 ms (210.9 KiB/s)
## Executing script at 00500000
Boot script loaded from mmc 0
270 bytes read in 12 ms (21.5 KiB/s)
16850812 bytes read in 1615 ms (9.9 MiB/s)
33853952 bytes read in 3221 ms (10 MiB/s)
76947 bytes read in 29 ms (2.5 MiB/s)
Unknown command 'kaslrseed' - try 'help'
Wrong Ramdisk Image Format
Ramdisk image is corrupt or invalid
SCRIPT FAILED: continuing...
76947 bytes read in 28 ms (2.6 MiB/s)
Card did not respond to voltage select!
starting USB...
Bus usb@fe380000: USB EHCI 1.00
Bus usb@fe3c0000: USB EHCI 1.00
Bus dwc3: Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
Bus dwc3: Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.10
scanning bus usb@fe380000 for devices... 1 USB Device(s) found
scanning bus usb@fe3c0000 for devices... 2 USB Device(s) found
scanning bus dwc3 for devices... 1 USB Device(s) found
scanning bus dwc3 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device
No ethernet found.
missing environment variable: pxeuuid
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/000000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/00000
No ethernet found.
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0000
@ophub

**Comment by inoeud** [comment]
直接写入emmc，提示这个，我好像不能sd卡启动，会提示电压错误。

**Comment by ophub** [comment]
你写入时要使用loader

**Comment by inoeud** [comment]
请问写入sd要咋使用loader？

**Comment by ophub** [comment]
你上面说的意思是你写入emmc不能启动，写rk写盘软件写入时，选择一个loader试试

**Comment by inoeud** [comment]
可能我表述不完整，在写入emmc时我附带写入了loader的（基操还是知道的），然后ttl跑的信息就是我上边贴的。

**Comment by ophub** [comment]
由于作者把leez-p710的u-boot和dts源码都在2020年提交到了u-boot和kernel的上游仓库，所以之后的源码里都包含了这些源码，随时可以编译最新的文件，下面是我使用 https://github.com/cm9vdA/build-linux 的过程，记录一下。

## 第一部分：u-boot的源文件来源及编译过程


编译脚本使用的 https://github.com/cm9vdA/build-linux
U-BOOT使用源码： https://github.com/u-boot/u-boot （branch: v2023.01）
rkbin使用源码： https://github.com/rockchip-linux/rkbin




- ### 创建编译目录
`cd ~/xxx`

 进入编译目录
```
mkdir leez
cd leez
```




- ### clone rkbin
`https://github.com/rockchip-linux/rkbin`



- ### clone u-boot 源码
`git clone https://github.com/u-boot/u-boot`

 检出指定版本的 tags（v2023.01）
```
cd u-boot
git checkout -b v2023.01 v2023.01
```

 查看检出结果正确
`git branch -a`



 返回上级目录继续添加其他
`cd ../`




- ### clone u-boot 编译仓库
```
git clone https://github.com/cm9vdA/build-linux
cd build-linux
```

 根据 build-linux 仓库的使用方法，把u-boot源码库里带着的leez编译文件复制到这个仓库指定目录里
```
cp -f ../u-boot/arch/arm/dts/rk3399-leez-p710.dts  boot/dts/rockchip/mainline/
cp -f ../u-boot/arch/arm/dts/rk3399-leez-p710-u-boot.dtsi  boot/dts/rockchip/mainline/
cp -f ../u-boot/configs/leez-rk3399_defconfig   u-boot/rockchip/u-boot-2023.01/
```

- ### 按仓库说明编辑 u-boot 参数设置
`vi env/common/build_uboot_aarch64`

 我的环境：ubuntu22.04 x86_64。如果是在armbian里编译时，因为需要先编译ATF，所以两个工具链都下载
 下载需要的工具链，解压缩到你指定的存放路径
 修改配置文件，根据自己工具链的路径和名称修改，我修改后的内容如下：
```
TOOLCHAIN_PATH=/usr/local/toolchain
TOOLCHAIN_NAME=arm-gnu-toolchain-12.2.rel1-x86_64-aarch64-none-elf
ARM_TOOLCHAIN_NAME=arm-gnu-toolchain-12.2.rel1-aarch64-arm-none-eabi

export ARCH=arm
export CROSS_COMPILE=aarch64-none-elf-
```

 添加u-boot编译模版build_uboot_leez
`vi env/build_uboot_leez`
 内容根据上述u-boot的文件名，填写如下

```
# Common Config
source ${SCRIPT_PATH}/env/common/build_uboot_aarch64

# Board Info
BOARD_NAME="Leez RK3399"
CPU_INFO="Rockchip RK3399"
DEFCONFIG="leez-rk3399_defconfig"
VENDOR="rockchip"
DT_FILE="rk3399-leez-p710"

# ATF
# git clone https://github.com/ARM-software/arm-trusted-firmware.git
# make CROSS_COMPILE=aarch64-linux-gnu- PLAT=rk3399
ATF_PLAT="rk3399"
export BL31=${SCRIPT_PATH}/u-boot/rockchip/common/rk3399_bl31.elf
```




- ### 创建 u-boot 编译目录
```
mkdir mkuboot
cd mkuboot
```

- ### 按仓库说明创建编译脚本软连接
```
ln -sf ../u-boot uboot
ln -sf ../build-linux/mk_uboot.sh build_uboot_leez
```




- ### 编译 u-boot
`./build_uboot_leez`
 选`1`生成配置，再次运行选`3`开始编译
（如果在armbian里编译，先使用0变异ATM，我在x86_64下编译，直接1,3即可。过程中可能报错，看错误提示缺少什么，安装对应的编译依赖包后重试）




- ### 查看编译好的 u-boot：
```
cd .build_uboot
ls -l
```

![Snip20230817_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/f51b8695-e58f-41ea-a54f-b3ae8bbef239)

- ### 复制出 u-boot 备用
```
mkdir ../leez-uboot
cp  -f  idbloader.img  ../leez-uboot
cp  -f  u-boot.itb  ../leez-uboot
```






## 第二部分：dtb文件的编译过程

https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/rockchip/rk3399-leez-p710.dts

- ### 编译dtb
根据自己的环境编译得到 rk3399-leez-p710.dtb 文件。
这个dts文件在5.4.y, 5.10.y, 5.15.y, 6.1.y 内核源码库里都自带了，正常编译即可，方法可以参考：
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

由于之前的各版内核都自带了，我就没再编译。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/bd8ac01faa6c930e7b91108d8eb7cb5685b3b6d9

u-boot 已经更新，并重新打包了个测试固件，你下载下面的这个测试下：

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.08/Armbian_23.08.0_rockchip_leez_jammy_6.1.45_server_2023.08.16.img.gz

**Comment by inoeud** [comment]
dtb是有点问题的需要稍微修改一下。
&usbdrd_dwc3_0 {
	status = "okay";
	dr_mode = "otg";
};

typec被配置成otg模式了，我看你给的教程（第二部分：dtb文件的编译）里面没有提到dtb的编译方法。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/rockchip/rk3399-leez-p710.dts

这是源文件，我看到4个usb设备，其中一个已经允许otg。这个主板有几个变种？你确认一下修改方案，我给你编个试试

**Comment by inoeud** [comment]
主板就一个版型，没有变种。
&usbdrd_dwc3_0 {
	status = "okay";
	dr_mode = "otg";
};
改成
&usbdrd_dwc3_0 {
	status = "okay";
	**dr_mode = "host";**
};
即可

**Comment by ophub** [comment]
你现在的固件可以正常启动？只是usb口有问题？我直接给你个编译好的dtb替换下就可以吧？不用完整编一个固件了吧？

**Comment by inoeud** [comment]
好的，可以正常启动

**Comment by ophub** [comment]
[rk3399-leez-p710.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12368967/rk3399-leez-p710.dtb.zip)

下载解压得到rk3399-leez-p710.dtb，替换/boot/dtb/rockchip目录下的同名文件，重启测试下。

**Comment by inoeud** [comment]
寄，一个都识别不到了（usb3.0）

**Comment by ophub** [comment]
我更新了上面的编译方法，把dtb的部分补充了下，你根据教程试试怎么调整，第一次编译看你的网速，一般5分钟内完成。以后每次1分钟不到就编译好dtb了，你调试好了反馈下。

**Comment by ophub** [comment]
[rk3399-leez-p710.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12370590/rk3399-leez-p710.dtb.zip)

试试这个

**Comment by inoeud** [comment]
难过，依然不可以识别

**Comment by ophub** [comment]
内核默认的dtb有什么问题？

**Comment by inoeud** [comment]
typec无法识别，一直没有改。除了官方系统，第三方的typec都不能用

**Comment by inoeud** [comment]
我目前也没什么解决思路，按照既往经验，改otg为host也不管用

**Comment by future1114** [comment]
大佬，能详细介绍一下如何将这个img文件写入到eMMC中，或者如何将tf卡中的系统安装到eMMC中吗？

**Comment by zycode667** [comment]
我的P710 leez刷成砖头了，有没有大佬能帮忙救一下的！
