### ISSUE TITLE
Feedback linux-image-current-meson64

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#161]
Hi @ophub 

Just a feedback.
Device: Beelink GT King Pro Revision A
Kernel: 5.16.13-flipply-70+
dtb: meson-g12b-gtking-pro.dtb
OS: Bullseye
Boot Storage: USB 3.0
Desktop Environment: Gnome 41+ (from Debian Unstable/Sid)

Just ran "sudo apt update"  and the following are available for update/upgrade:

```
jfl@armbian:~$ apt list --upgradable
Listing... Done
armbian-bsp-cli-lepotato/bullseye 22.02.1 arm64 [upgradable from: 22.02.0-trunk]
armbian-zsh/bullseye,bullseye 22.02.1 all [upgradable from: 22.02.0-trunk]
libdeflate0/unstable 1.10-2 arm64 [upgradable from: 1.10-1]
libprotobuf23/unstable 3.12.4-1+b3 arm64 [upgradable from: 3.12.4-1+b2]
libsrt1.4-gnutls/unstable 1.4.4-3 arm64 [upgradable from: 1.4.4-2]
libwebp7/unstable 1.2.2-1 arm64 [upgradable from: 1.2.1-7.2]
linux-dtb-current-meson64/bullseye 22.02.1 arm64 [upgradable from: 22.02.0-trunk]
linux-image-current-meson64/bullseye 22.02.1 arm64 [upgradable from: 22.02.0-trunk]
linux-libc-dev/bullseye 22.02.1 arm64 [upgradable from: 21.08.6]
linux-u-boot-lepotato-current/bullseye 22.02.1 arm64 [upgradable from: 22.02.0-trunk]
```
After "sudo apt upgrade":
New linitrd.img-5.10.102-meson64, zImage, Image, uInitrd, uImage (0 byte), new dtb from kernel-5.10.102-meson64. hdmi.rules and hdmi-hotplug are created.

The meson-g12b-gtking-pro.dtb (from kernel-5.10.102-meson64) obviously is different from the kernel-5.16.13-flippy-70+. Fortunately, zImage and newly created uInitrd is still from kernel-5.16.13-flippy-70+.

Restart without changing any files, it still boot into/with kernel 5.16.13-flippy-70+ but dtb used is from kernel-5.10.102-meson64.  It restarted successfull but after a minute or so Just Black Screen!  This as i remember is the issue of hdmi.rules and hdmi-plug.  Will disable hdmi.rules and hdmi-hotplug shortly.

Question, should we "Hold" the following:?

```
linux-image-current-meson64
linux-dtb-current-meson64
armbian-bsp-clis
armbian-bsp-cli-lepotato
linux-u-boot-lepotato-current
```
Any suggestions?

Where can I find the /dtb/amlogic for kernel-5.16.13-flippy-70+? Since the /boot/dtb was replaced to linux-dtb-current-meson64 after the "sudo apt upgrade".

**Edit:**
After disable theese two files: hdmi.rules and hdmi-plug but use meson-g12b-gtking-pro.dtb (from kernel-5.15.25-meson64) and Restart.

```
jfl@armbian:~$ cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=lepotato
BOARD_NAME="Le potato"
BOARDFAMILY=meson-gxl
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=92a1c729d-dirty
VERSION=22.02.1
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
BRANCH=current

jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODENAME='bullseye'
FDTFILE='meson-g12b-gtking-pro.dtb'
U_BOOT_EXT='1'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/lib/u-boot/gtkingpro-u-boot.bin.sd.bin'
ANDROID_UBOOT=''
SOC='s922x'
PACKAGED_DATE='2022-01-16'
KERNEL_VERSION='5.16.13'
K510='1'
jfl@armbian:~$ 

jfl@armbian:~$ dmesg
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.16.13-flippy-70+ (root@univm25) (Ubuntu clang version 13.0.1-2ubuntu1, Ubuntu LLD 13.0.1) #57 SMP PREEMPT Thu Mar 10 10:52:27 CST 2022
[    0.000000] Machine model: Beelink GT-King Pro
[    0.000000] efi: UEFI not found.
[    0.000000] OF: fdt: Reserved memory: failed to reserve memory for node 'secmon@5000000': base 0x0000000005000000, size 3 MiB
[    0.000000] OF: fdt: Reserved memory: failed to reserve memory for node 'secmon@5300000': base 0x0000000005300000, size 32 MiB
[    0.000000] Reserved memory: created CMA memory pool at 0x00000000b8400000, size 896 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
```
Restart successfully and NO more "Black Screen" issue.  Will check (test) to see whether the dtb from kernel-5.15.25-meson64 is stable with kernel-5.16.13-flippy-70+.

**Comment by ophub** [comment]
`sudo apt-get -qq purge -y linux-image-current-meson64`

When the firmware was first started, I set up automatic deletion, and I tested today's firmware to delete normally. You removed it manually, use the `armbian-update` command to upgrade directly to the latest kernel or the kernel you specified.

**Comment by JFLim1** [comment]
> When the firmware was first started, I set up automatic deletion, and I tested today's firmware to delete normally.

Thanks for the info, how to remove and purge linux-image-current-meson64.

With linux-image-current-meson64 or linux-image-edge-meson64 is NOT an issue actually.  Since linux-image-current-meson64 generates "Image" and your flippy-kernel generates "zImage", this gives users an option boot meson64-kernel or flippy-kernel.



> https://github.com/ophub/amlogic-s9xxx-armbian/blob/ae338df1e3a31afd1eaef6715f2da75aa711d45b/rebuild#L535

By the way, what is this command for?  You mean, open terminal and enter this command: 

`sed -i '/armbian-release/i\[ -f "/usr/sbin/armbian-fix" ] && . /usr/sbin/armbian-fix' ${armbian_firstrun} 2>/dev/null`

I don't think "armbian-fix" is available in /usr/sbin/ on my older firmware/image.

**Comment by ophub** [comment]
sudo apt-get -qq purge -y linux-image-current-meson64

**Comment by JFLim1** [comment]
> sudo apt-get -qq purge -y linux-image-current-meson64

This command is to remove and purge "linux-image-current-meson64"?

**Comment by ophub** [comment]
yes

**Comment by JFLim1** [comment]
Thanks.

**Comment by JFLim1** [comment]
Hi @ophub 

The usual "apt list linux-image* --installed" does not list any reference to flippy-kernel being installed. It only listed linux-image-current-meson64 being installed (as I have not remove linux-image-current-meson64 yet).

uname -a does reflect flippy-kernel being installed/used.
`Linux armbian 5.16.13-flippy-70+ #57 SMP PREEMPT Thu Mar 10 10:52:27 CST 2022 aarch64 GNU/Linux`

Just trying to understand, why the usual command "apt list linux-image* --installed" does not return/list flippy-kernel being installed?

**Comment by ophub** [comment]
flippy is not installed from a mirror server, it is a custom kernel.
