### ISSUE TITLE
armbian有支持HDMI输出吗

### ISSUE THREAD

**Issue by God-JohnDiamond** [ophub/amlogic-s9xxx-armbian#1611]
Device Information | 设备信息

SOC: S905L3B
Model [CM211-1]
Armbian Version | 系统版本
Kernel Version: [6.1.18]
Release: [bullseye]
Describe the bug | 问题描述
想用屏幕

**Comment by ophub** [comment]
在支持列表里的设备90%+都支持hdmi，目前只见部分魔百和不支持。

**Comment by xiaodiao216** [comment]
同问，我的u盘启动armbian直接黑屏，但是系统确实跑起来了，因为我看到ip了，可以ssh上
SOC: S905L3B
Model [创维 e900v21e]

**Comment by God-JohnDiamond** [comment]
> 在支持列表里的设备90%+都支持hdmi，主要集中在部分魔百和不支持。

我的也是 一直黑屏

**Comment by ophub** [comment]
我不会改dtb，搞不定这个问题。

**Comment by tiantian117** [comment]
中兴ZXV10 B860AV3.2-M 也是可以进入系统，可以ssh上，但是黑屏，HDMI没有输出，一开始是花屏，花瓶之后就没有输出了。
有解决方法踢我哈哈哈
Soc：S905L3
release里面所有s905l3的包都试过了，都是这样子。

**Comment by zengfr** [comment]
> 中兴ZXV10 B860AV3.2-M 也是可以进入系统，可以ssh上，但是黑屏，HDMI没有输出，一开始是花屏，花瓶之后就没有输出了。 有解决方法踢我哈哈哈 Soc：S905L3 release里面所有s905l3的包都试过了，都是这样子。

你什么版本配置的 我刚进货一批 别吓我啊 没办法hdmi吗 知道刷过的老铁出来轰一声

**Comment by yiqihongchen** [comment]
我刷的固件，只要引导就黑屏，屏幕灯闪烁，U盘摸着也不烫呀

**Comment by moon-umbrella** [comment]
> > 中兴ZXV10 B860AV3.2-M 也是可以进入系统，可以ssh上，但是黑屏，HDMI没有输出，一开始是花屏，花瓶之后就没有输出了。 有解决方法踢我哈哈哈 Soc：S905L3 release里面所有s905l3的包都试过了，都是这样子。
> 
> 你什么版本配置的 我刚进货一批 别吓我啊 没办法hdmi吗 知道刷过的老铁出来轰一声

 中兴ZXV10 B860AV3.2-M  S905L3B 黑屏无视频输出

**Comment by itlaohuo** [comment]
> > > 中兴ZXV10 B860AV3.2-M 也是可以进入系统，可以ssh上，但是黑屏，HDMI没有输出，一开始是花屏，花瓶之后就没有输出了。 有解决方法踢我哈哈哈 Soc：S905L3 release里面所有s905l3的包都试过了，都是这样子。
> > 
> > 
> > 你什么版本配置的 我刚进货一批 别吓我啊 没办法hdmi吗 知道刷过的老铁出来轰一声
> 
> 中兴ZXV10 B860AV3.2-M S905L3B 黑屏无视频输出

但不影响正常作为服务器使用，比如home assistant吧

**Comment by moon-umbrella** [comment]
你好，中兴ZXV10 B860AV3.2-M，4+32G版本2023年生产的，内存识别2.87G，无图像输出，只能ssh网络连接或使用TTL连接线，其他的都正常，作为服务器使用，比如home assistant都可以。




***@***.***
 
发件人： itlaohuo
发送时间： 2024-01-05 22:53
收件人： ophub/amlogic-s9xxx-armbian
抄送： moon-umbrella; Comment
主题： Re: [ophub/amlogic-s9xxx-armbian] armbian有支持HDMI输出吗 (Issue #1611)
中兴ZXV10 B860AV3.2-M 也是可以进入系统，可以ssh上，但是黑屏，HDMI没有输出，一开始是花屏，花瓶之后就没有输出了。 有解决方法踢我哈哈哈 Soc：S905L3 release里面所有s905l3的包都试过了，都是这样子。
你什么版本配置的 我刚进货一批 别吓我啊 没办法hdmi吗 知道刷过的老铁出来轰一声
中兴ZXV10 B860AV3.2-M S905L3B 黑屏无视频输出
但不影响正常作为服务器使用，比如home assistant吧

**Comment by HAHA114514-sourc** [comment]
@ophub 怎解决IPBS9506 HDMI
