### ISSUE TITLE
Requesting to add support for Tanix TX6-A

### ISSUE THREAD

**Issue by ni554n** [ophub/amlogic-s9xxx-armbian#1612]
**Device Information | 设备信息**
 - SOC: h6
 - Model Tanix TX6-A

> TX6-A is a cheaper variant of TX6 with 4/32GB, 100MB ethernet and no 5 GHz Wi-Fi or BT (XRadio XR819).
TX-6A's firmwares are tagged as `8822` whereas normal TX6 firmwares are tagged as `8822bs`. 
>
> Here's the only device review I found: https://androidpctv.com/review-tanix-tx6a-opinion/

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.125
 - Release: all

**Describe the bug | 问题描述**
After booting your TX6 image from SD card, it doesn't get any ethernet / Wi-Fi support and addresses only 2GB of the RAM.
`armbian-install` gets stuck at creating emmc partition no matter what `-a -m` switches are set.

![2023-08-13-22-23-09-194](https://github.com/ophub/amlogic-s9xxx-armbian/assets/2310552/38b44d17-aae6-46ba-8f8b-c7fc882e59d4)

### Stock Firmwares
Here's the stock firmware of TX6-A: https://drive.google.com/file/d/112dqSGCeV_E84XDUcErwZ1v_Ej4ST7jl/view

And this one is newer and has support for both variants: https://mega.nz/file/BgR0EbaL#YZUlG6LmDtTPx2cnc4t9jLf7kCWHfcMX_JkveXeElko

### Working Armbian Build
I'm currently running this old armbian build from SD card. And everything seems to be working.
https://4pda.to/forum/index.php?showtopic=929205&view=findpost&p=97197782

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/c8aac02485d26b7bd356c35c9f3f92243f471def

https://github.com/ophub/amlogic-s9xxx-armbian/commit/9c2ecd2ba027221120e95144ffed3cfd6924ef57

According to your introduction, I used the firmware in the 4pda.to you are using and extracted the u-boot file. I think his dtb should be the same file as TX6 (`sun50i-h6-tanix-tx6.dtb`) , you can test whether it can be used normally.

If it is not normal, you may need to modify the name of dtb in `/boot/armbianEnv.txt` to `sun50i-h6-tanix-tx6-a.dtb`

**Comment by ni554n** [comment]
Wow. Thank you for considering it.

I just tried your build from an SD card, but it didn't boot at all. No response on the display. 😔

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.08/Armbian_23.08.0_allwinner_tanix-tx6-a_bullseye_5.15.127_server_2023.08.17.img.gz

I made adjustments, you re-download this test.

**Comment by ni554n** [comment]
It did boot this time but Wi-Fi / Ethernet is not getting detected. And the RAM is still showing up as 2 GB.

By the way, ethernet is also broken on the 4pda build. I didn't realized at first because I was connected to the Wi-Fi.

**Comment by ophub** [comment]
Please search again for a functional Armbian system for the TX6A. Once you find a suitable one, please send me the firmware for testing purposes.

**Comment by ni554n** [comment]
I just thoroughly tested the 4PDA build. Ethernet works fine. Sorry of providing wrong information there.

![2023-08-18-14-45-41-055 (1)](https://github.com/ophub/amlogic-s9xxx-armbian/assets/2310552/578243a2-44ef-46a5-909d-4bf2719c4221)

The only problem I've found so far is video playback. On Chromium and mpv, they are playing at around 5-10 FPS. I'm assuming video acceleration (or GPU?) is not working properly.

I completely understand if you do not want to go forward. But can you please point me to a direction to pin-point this video playback issue?

**Comment by ophub** [comment]
Based on the information you provided, the first firmware that was created used u-boot and dtb from 4pda.to. Normally, this combination should work, but your tests yielded no response.

Afterward, I thought about it some more. Since your original TX6 can boot but has issues with wired networking, the second firmware was created using the u-boot from TX6 and the dtb from 4pda.to. However, you still don't have network connectivity.

When it comes to testing by combining precompiled binary files, if they don't work, there might not be much else to try. I can't think of any other testing approaches.

There is a method in the repository to decompile the dtb. If you find information about the differences in their network chipsets, you could modify the dtb from the current TX6 and replace it for testing purposes.

**Comment by ni554n** [comment]
Understood. Thanks again for looking into it.

**Comment by j-a-sunny** [comment]
Did you try this 
[Image](https://github.com/awawa-dev/build/releases/tag/v2022.03.08)

**Comment by ni554n** [comment]
> Did you try this [Image](https://github.com/awawa-dev/build/releases/tag/v2022.03.08)

Yes, that and a build from 4pda/Armbian worked. However, I recall having issues with hardware acceleration not functioning properly, so I reverted to the stock Android firmware.

**Comment by TahlilJunaid** [comment]
Hey guys, i also want to firmware my Android tv box the same model u guys did. But having trouble to find correct firmware for that model. I'm doing firmware because my box has become so slow. 
If u guys know any solution. Please kindly let me know. Would appreciate.

**Comment by ni554n** [comment]
I didn't find anything that supports video acceleration, so I just shelved it. Here's my note from that time... maybe it will help with your exploration. Let me know if you find anything.

---

# Tanix TX-6A

- Connect the HDMI before plug-in the power cable. Otherwise it won't show up on the monitor.

## Config

- Rating: 5V/2A
- Power consumption:
	- Off: 0.7W
	- Standby: 3.5W
	- Regular: 6.1W
	- Maximum: 7.2W

## Resources

- [REVIEW: Tanix TX6-A with Allwinner H6 SoC and Android 9](https://androidpctv.com/review-tanix-tx6a-opinion/)
- [Tanix TX6 - 4PDA](https://4pda.to/forum/index.php?showtopic=929205)
- Distro upgrade: [armbian upgrade from buster to bullseye - Beginners - Armbian Community Forums](https://forum.armbian.com/topic/19237-armbian-upgrade-from-buster-to-bullseye/)
- [Requesting to add support for Tanix TX6-A · Issue #1612 · ophub/amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1612)

## Firmwares

### Official

- TX6:   `8822bs`
- TX6-A: `8822`

#### Flashing

1. Format SD card as non bootable MBR using Rufus
2. Extract [PheonixCard](https://androidmtk.com/download-phoenixcard-tool) > Select image in "Product" mode > Burn
3. Boot from SD card and wait for `[Card Ok]` then restart.


### Custom

- Lakka (RetroArch) - Booted with 2 GB RAM and LAN. Kinda lame.
- ophub/armbian - Jammy / Bookworm both stuck at `Start creating eMMC partition`
- LibreELEC (Kodi) - Slow and boring. There's also reported random hangings.
- smlinux/armbian - No Wi-Fi because it is for TX-6H. Kernel panics during installation of any package.
- [TV-box mania: II part. Tanix TX6 (Allwinner H6)](https://www.hyperhdr.eu/2022/02/tv-box-mania-ii-part-tanix-tx6.html) - [awawa-dev/build](https://github.com/awawa-dev/build) - Can be run from SD Card (2 GB usable).
- 4pda/armbian - Seems everything is working from SD card except for VIDEO ACCELERATION.
  - Flash the img directly with Rufus
	- EMMC flash using `dd if=Armbian_20.02.1_Allwinnerth6vbox_buster_current_5.7-rc5_desktop.img of=/dev/mmcblk2 bs=32M status=progress`
