### ISSUE TITLE
我来报告一款S905L3B的盒子 咪咕MGV2000(kl代工)

### ISSUE THREAD

**Issue by locAtt** [ophub/amlogic-s9xxx-armbian#1613]
**Device Information | 设备信息**
 - SOC: [s905l3b]
 - Model [四川移动]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.123]
 - Release: [lunar]

**Describe the bug | 问题描述**
偶然得到这款MGV2000的盒子，主页上有这一款，但是被划归到s905l2，我拆机打开看到确是s905l3b，刷机ty1608安卓4.4的包u盘启动armbian无法获取ip，刷烽火HG680-LC 安卓9 S905L3 沙发语音线刷包，使用m302dtb无法获取ip，改由e900v22e的dtb成功，使用121成功刷入emmc 蓝牙无法使用 无hdmi输出
![IMG_3273](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28192806/4ad64eb0-dd20-47be-9cf0-42e6f98596cd)
![IMG_3274](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28192806/c2e7ae25-2631-4a50-adf8-5c31623bbb68)
![IMG_3275](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28192806/bb7cae4c-9b4a-480a-bbd0-b8593cd14147)
![IMG_3291](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28192806/22f423db-8bae-435a-ba8b-d36088cdf850)
![IMG_3293](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28192806/66adccac-5e6d-4f01-a030-36bb6d2aad05)

**Comment by ophub** [comment]
感谢分享，你试一下6.1.y内核，使用哪个u-boot可以启动。
/boot/u-boot-xxxx 复制成 u-boot.ext ，U盘中启动先试试

**Comment by locAtt** [comment]
> 感谢分享，你试一下6.1.y内核，使用哪个u-boot可以启动。 /boot/u-boot-xxxx 复制成 u-boot.ext ，U盘中启动先试试

下载好lunar的6.1.42写入U盘 只是更改了e900v22e的dtb 就成功启动 网口正常 hdmi无显示 好像这个主板没蓝牙芯片

**Comment by ophub** [comment]
下的哪个固件，发下文件名我确认一下u-boot，我添加到列表里

**Comment by locAtt** [comment]
> 下的哪个固件，s905l3b的？发下文件名我确认一下u-boot，我添加到列表里

Armbian_23.08.0_amlogic_s905l3b_lunar_6.1.42_server_2023.08.01.img.gz 现在的问题是U盘可以启动 写入EMMC启动不了啦

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

你看看这有没有对应的安卓系统，线刷安卓，再刷armbian，救砖也可以用这里的安卓

**Comment by locAtt** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 你看看这有没有对应的安卓系统，线刷安卓，再刷armbian，救砖也可以用这里的安卓

这里面的刷过 安卓9的刷不成功 要么刷完启动不了 下一次试试还是先刷以前hg680lc的刷机包再写入6.1.x的试试

**Comment by aolin2000** [comment]
我的905L3B盒子用6.x的未能成功过，都是调用armbian的uboot就死掉了，请问6.x为何要多一层uboot?

**Comment by locAtt** [comment]
> 我的905L3B盒子用6.x的未能成功过，都是调用armbian的uboot就死掉了，请问6.x为何要多一层uboot?

有没有试过不用uboot文件

**Comment by locAtt** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 你看看这有没有对应的安卓系统，线刷安卓，再刷armbian，救砖也可以用这里的安卓

先刷安卓9再刷emmc 6.1.42依然无法启动 u盘启动6.1.42正常

**Comment by aolin2000** [comment]
> 

5.x的不用uboot可以引导启动armbian

**Comment by ophub** [comment]
对照配置表，试试6.1用哪个dtb + u-boot组合是可以用的，相近的那几个都试试，U盘测试可以启动再试emmc

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf


从5.10开始，内核调整了偏移量，不打补丁的默认内核都要u-boot。

https://github.com/ophub/kernel/releases

在内核仓库里的dev和beta都是打了补丁的，4个系列的都可以不用u-boot启动。另外的flippy和stable里面，5.4和5.15(打了补丁)不要，但是5.10和6.1这两个都需要u-boot.

**Comment by ophub** [comment]
还有一种方法，就是参照文档里降低频率的做法，把dtb反编译下调低频率试试，很多魔百盒usb使用正常，但是无法写入emmc或者写入后内核恐慌，都是这样解决的。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

看12.13 和 12.16

**Comment by aolin2000** [comment]
> > 感谢分享，你试一下6.1.y内核，使用哪个u-boot可以启动。 /boot/u-boot-xxxx 复制成 u-boot.ext ，U盘中启动先试试
> 
> 下载好lunar的6.1.42写入U盘 只是更改了e900v22e的dtb 就成功启动 网口正常 hdmi无显示 好像这个主板没蓝牙芯片


请问你这个盒子是多大内存的，1G+8G吗？
我的S905L3B盒子是1G+8G的，6.1.42的版本始终启动不了，都是在u-boot阶段就挂掉了

**Comment by aolin2000** [comment]
> > 
> 
> 是2g+8g组合 无wifi无蓝牙

貌似1G的无法启动armbian uboot，我的另外一个CM211-1是2G的，也是可以启动6.1.42的

**Comment by locAtt** [comment]
> > 是2g+8g组合 无wifi无蓝牙
> 
> 貌似1G的无法启动armbian uboot，我的另外一个CM211-1是2G的，也是可以启动6.1.42的

现在能u盘启动 写入emmc启动不了 还需要调试下

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/1f34b0f733aed3a50dfe34b9d87f96385122799f

https://github.com/ophub/amlogic-s9xxx-armbian/commit/05f481a49ff41ef9987dc4f3e6b59568b01a5460

感谢分享，mgv2000(s905l3b)根据你的测试结果，我添加到设备支持列表了（121序号），等你测试好6.1.y组合，如果有变化再更新。

**Comment by whc6869** [comment]
> 1G+8G
我的盒是也是1G+8GMGV2000KL南传_S905L3B_cdtech47822BS，安卓4.4、9.0r的包无法获取ip

**Comment by locAtt** [comment]
> 1G+8G
> 我的盒是也是1G+8GMGV2000KL南传_S905L3B_cdtech47822BS，安卓4.4、9.0r的包无法获取ip

你用的哪个dtb 我用的是e900v22e的 m302的外接网卡才行

**Comment by whc6869** [comment]
我刷了https://pan.baidu.com/s/1s34TmIR_DyD_XmzWA48Tvw     fdjf 
里面开放ADB的固件
e900v22e和m302dtb都试过了,没有显示也没有IP

**Comment by whc6869** [comment]
> 
请把你的固件发一下

**Comment by locAtt** [comment]
> > 
> 
> 请把你的固件发一下

TV盒子固件包刷的是这个 下载链接：https://pan.baidu.com/s/1fb2kXW5VwFr5yrOP1kV2_Q
提取码：n3ag

**Comment by ophub** [comment]
写入emmc无法启动，有2个可能，1个是dtb的频率需要下调，另外一个原因是写入了不正确的分区。
刷完安卓系统后，使用文档里12.10的方法查看下，7Ji大佬的方法查看很方便。
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

**Comment by Aqr-K** [comment]
> > > 
> > 
> > 
> > 请把你的固件发一下
> 
> TV盒子固件包刷的是这个 下载链接：https://pan.baidu.com/s/1fb2kXW5VwFr5yrOP1kV2_Q 提取码：n3ag

我的盒子是`移动`的`mgv2000`，芯片是`S905l3b`的，配置是1G+8G，`南传``JL`代工，查了一下，`KL`和`JL`好像是通用的，网上很多`KL`和`JL`互刷的情况sd卡烧录的是`Armbian_23.08.0_amlogic_s905l3b_bullseye_6.1.46_server_2023.08.19`
刷了这个安卓固件后，可以正常使用安卓系统，然后使用开心电视助手远程连接，获取adb的root权限后，点了一下`从u盘/sd卡启动`，始终进不去armbian一直处于黑屏状态，ping盒子在开安卓系统时获取的ip地址却一直通的
断电重启不拔u盘的情况下，还是会一直处于无法开机的状态，会一直循环`SMARTTV`的logo的动画阶段，在这个情况下，是完全没有ip的，是不通的，请问一下该怎么解决呢？

**Comment by locAtt** [comment]
> > > 请把你的固件发一下
> > 
> > 
> > TV盒子固件包刷的是这个 下载链接：https://pan.baidu.com/s/1fb2kXW5VwFr5yrOP1kV2_Q 提取码：n3ag
> 
> 我的盒子是`移动`的`mgv2000`，芯片是`S905l3b`的，配置是1G+8G，`南传` `JL`代工，查了一下，`KL`和`JL`好像是通用的，网上很多`KL`和`JL`互刷的情况，sd卡烧录的是`Armbian_23.08.0_amlogic_s905l3b_bullseye_6.1.46_server_2023.08.19` 刷了这个安卓固件后，可以正常使用安卓系统，然后使用开心电视助手远程连接，获取adb的root权限后，点了一下`从u盘/sd卡启动`，始终进不去armbian一直处于黑屏状态，ping盒子在开安卓系统时获取的ip地址却一直通的 断电重启不拔u盘的情况下，还是会一直处于无法开机的状态，会一直循环`SMARTTV`的logo的动画阶段，在这个情况下，是完全没有ip的，是不通的，请问一下该怎么解决呢？

看你这个情况 应该一直没有启动armbian 下载好armbian的固件之后 写入u盘 插机顶盒上 步骤做对了吗

**Comment by Aqr-K** [comment]
> > > > 请把你的固件发一下
> > > 
> > > 
> > > TV盒子固件包刷的是这个 下载链接：https://pan.baidu.com/s/1fb2kXW5VwFr5yrOP1kV2_Q 提取码：n3ag
> > 
> > 
> > 我的盒子是`移动`的`mgv2000`，芯片是`S905l3b`的，配置是1G+8G，`南传` `JL`代工，查了一下，`KL`和`JL`好像是通用的，网上很多`KL`和`JL`互刷的情况，sd卡烧录的是`Armbian_23.08.0_amlogic_s905l3b_bullseye_6.1.46_server_2023.08.19` 刷了这个安卓固件后，可以正常使用安卓系统，然后使用开心电视助手远程连接，获取adb的root权限后，点了一下`从u盘/sd卡启动`，始终进不去armbian一直处于黑屏状态，ping盒子在开安卓系统时获取的ip地址却一直通的 断电重启不拔u盘的情况下，还是会一直处于无法开机的状态，会一直循环`SMARTTV`的logo的动画阶段，在这个情况下，是完全没有ip的，是不通的，请问一下该怎么解决呢？
> 
> 看你这个情况 应该一直没有启动armbian 下载好armbian的固件之后 写入u盘 插机顶盒上 步骤做对了吗

应该是没错，但是我用BalenaEtcher烧录的话，最后好像是会出现校验失败，然后我用树莓派官方烧录器倒是校验成功了，同一个包，没解压，烧录结束就直接退出来，插盒子上了，两个烧录都是一样的情况，打不开

**Comment by Aqr-K** [comment]
我自己也找了一下，有人说虽然BalenaEtcher会出现因为校验产生的失败，但不影响正常使用，这就很迷了
还有，我试过教程文档里的把.bak去掉的方法也是无法启动

**Comment by locAtt** [comment]
> 

把dtb设置成e900v22e的试一下呢

**Comment by locAtt** [comment]
> > 把dtb设置成e900v22e的试一下呢
> 
> 大致怎么操作？能不能教一下

写入u盘后 打开u盘 里面有个叫uenv.ini的文件 记事本打开 修改为dtb_name=/dtb/meson-gxl-s905l3b-e900v22e.dtb

**Comment by Aqr-K** [comment]
> > > 把dtb设置成e900v22e的试一下呢
> > 
> > 
> > 大致怎么操作？能不能教一下
> 
> 写入u盘后 打开u盘 里面有个叫uenv.ini的文件 记事本打开 修改为dtb_name=/dtb/meson-gxl-s905l3b-e900v22e.dtb

还是不行，我甚至重刷了一次烽火安卓和armbian了，
正常进入安卓系统后，运行完文档[12.4](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#124-%E8%AE%BE%E7%BD%AE%E7%9B%92%E5%AD%90%E4%BB%8E-usbtfsd-%E4%B8%AD%E5%90%AF%E5%8A%A8)里提到的 `adb connect 192.168.x.x` `adb shell reboot update` 命令，依旧进不去，现在是绿灯、黑屏、无网络的状态，
而且，如果先运行 `adb shell reboot update` 再插上读卡器，会出现卡死在安卓桌面无法运行，也无法使用安卓桌面的情况（非黑屏，就卡死不动）
如果先插上读卡器，再运行 `adb shell reboot update` ，会出现led先红马上变绿，桌面出现一次 `SMARTTV` logo，然后马上进入黑屏状态，一直保持黑屏不变，且在插着读卡器的情况下直接开机重启，也会进入这个状态
重刷armbian的时候，我注意到uenv文件的格式不知道啥时候变成了`.txt`格式，我手动改回去`.ini`了
我尝试过让下面四种方式参数，以先插读卡器后运行和先运行再查读卡器的方式都运行了一次
第一次，使用默认的`dtb`
第二次，尝试用你教的方法，改过 `uenv.ini` 文件里的参数，修改为 `dtb_name=/dtb/meson-gxl-s905l3b-e900v22e.dtb` 
第三次，尝试用文档[12.6](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#126-%E5%90%AF%E5%8A%A8%E5%BC%95%E5%AF%BC%E6%96%87%E4%BB%B6%E7%9A%84%E9%80%89%E6%8B%A9)提到的方法，去掉了 `/extlinux/extlinux.conf.bak` 里的 `.bak后缀` ，并修改里面的参数为 `dtb_name=/dtb/meson-gxl-s905l3b-e900v22e.dtb` ，使其与第二次的 `uenv.ini` 的`dtb`相同
第四次，还原了 `/extlinux/extlinux.conf` 与 `uenv.ini` 里的 `dtb` 为默认的 `m302dtb`
最后的结果都是黑屏和卡死

**Comment by ophub** [comment]
uEnv.txt是正确的。不是ini

**Comment by Aqr-K** [comment]
> uEnv.txt是正确的。不是ini

6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态

**Comment by Aqr-K** [comment]
这是5.15的报错内容
armbian-install
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------------
ID    SOC        MODEL                               DTB                                               
--------------------------------------------------------------------------------------
101   s905d      Phicomm-N1                          meson-gxl-s905d-phicomm-n1.dtb                    
102   s905d      Phicomm-N1(DMA-thresh)              meson-gxl-s905d-phicomm-n1-thresh.dtb             
103   s905d      MECOOL-KI-Pro                       meson-gxl-s905d-mecool-ki-pro.dtb                 
104   s905d      SML-5442TW                          meson-gxl-s905d-sml5442tw.dtb                     
105   s905x      HG680P                              meson-gxl-s905x-p212.dtb                          
106   s905x      B860H                               meson-gxl-s905x-b860h.dtb                         
107   s905x      TX9                                 meson-gxl-s905x-tx9.dtb                           
108   s905x      T95,XiaoMI-3S,X96                   meson-gxl-s905x-p212.dtb                          
109   s905x      TBee                                meson-gxl-s905x-tbee.dtb                          
110   s905w      TX3-Mini                            meson-gxl-s905w-tx3-mini.dtb                      
--------------------------------------------------------------------------------------
111   s905w      W95                                 meson-gxl-s905w-p281.dtb                          
112   s905w      X96-Mini                            meson-gxl-s905w-x96-mini.dtb                      
113   s905w      X96W,FunTV,MXQ-Pro-4K               meson-gxl-s905w-x96w.dtb                          
114   s905l2     MGV2000,MGV3000,M301A               meson-gxl-s905l2-x7-5g.dtb                        
115   s905l2     E900v21E                            meson-gxl-s905l2-x7-5g.dtb                        
116   s905l2     Wojia-TV-IPBS9505                   meson-gxl-s905l2-ipbs9505.dtb                     
117   s905l3     CM311-1,HG680-LC,M401A,UNT402A      meson-gxl-s905l2-x7-5g.dtb                        
118   s905l3     UNT400G1                            meson-gxl-s905l2-x7-5g.dtb                        
119   s905l3     CM211-1                             meson-gxl-s905l3b-m302a.dtb                       
120   s905l3b    E900V22D,TY1608                     meson-gxl-s905l2-x7-5g.dtb                        
--------------------------------------------------------------------------------------
121   s905l3b    E900V21E,E900V22E,MGV2000           meson-gxl-s905l3b-e900v22e.dtb                    
122   s905l3b    M302A,M304A,CM211-1,CM311-1         meson-gxl-s905l3b-m302a.dtb                       
123   s905l3b    IP103H,TY1608,BV310,B860AV-2.1M     meson-gxl-s905l3b-m302a.dtb                       
124   s905lb     BesTV-R3300L,SumaVision-Q7,MG101    meson-gxl-s905x-p212.dtb                          
125   s905lb     Q96-mini                            meson-gxl-s905x-p212.dtb                          
126   s905l      UNT402A,M201-S                      meson-gxl-s905l3b-m302a.dtb                       
127   s905mb     S65                                 meson-gxl-s905x-p212.dtb                          
0     Other      Customize                           Enter-custom-dtb-name                             
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 123
[ INFO ] Input Box ID: [ 123 ]
[ INFO ] Model Name: [ IP103H,TY1608,BV310,B860AV-2.1M ]
[ INFO ] FDTFILE: [ meson-gxl-s905l3b-m302a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-s905x-s912.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root? 
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 2
[ INFO ] Input Type ID: [ 2 ]
[ INFO ] Type of filesystem: [ btrfs ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
dd: error reading '/dev/mmcblk2': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 0.0405778 s, 0.0 kB/s
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader.img ] failed.

**Comment by locAtt** [comment]
> > uEnv.txt是正确的。不是ini
> 
> 6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态

ssh能连就已经正常了我也没有hdmi输出 应该还没适配好 我的另一个s905l3a-b的就有显示

**Comment by Aqr-K** [comment]
> > > uEnv.txt是正确的。不是ini
> > 
> > 
> > 6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态
> 
> ssh能连就已经正常了我也没有hdmi输出 应该还没适配好 我的另一个s905l3a-b的就有显示

问一下，你是用哪个内核的呢？能写入emmc吗？

**Comment by ophub** [comment]
hdmi就是没有，ssh访问管理
没法写入emmc看文档，降低dtb频率

**Comment by Aqr-K** [comment]
> hdmi就是没有，ssh访问管理 没法写入emmc看文档，降低dtb频率
我看了一下文档，里面说`I/O`错误的时候需要降频率，可我没有报`I/O`错误
好像不是频率问题，我是卡在了备份原安卓系统的阶段了，主要报错是这个

[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
dd: error reading '/dev/mmcblk2': Input/output error
0+0 records in
0+0 records out
0 bytes copied, 0.0304465 s, 0.0 kB/s
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader.img ] failed.

**Comment by Aqr-K** [comment]
[在issues里找到同样的问题了[#1603](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1603)，我尝试一下先

**Comment by Aqr-K** [comment]
> > > uEnv.txt是正确的。不是ini
> > 
> > 
> > 6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态
> 
> ssh能连就已经正常了我也没有hdmi输出 应该还没适配好 我的另一个s905l3a-b的就有显示

问一下，有没有保留移动官方原系统的img包啊？我没存，我想试试能不能通过提取官方的dtb

**Comment by locAtt** [comment]
> > > > uEnv.txt是正确的。不是ini
> > > 
> > > 
> > > 6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态
> > 
> > 
> > ssh能连就已经正常了我也没有hdmi输出 应该还没适配好 我的另一个s905l3a-b的就有显示
> 
> 问一下，你是用哪个内核的呢？能写入emmc吗？

现在暂时用的5.15正常写入emmc，写入序号选的121正常使用 6.1.x优盘能启动 写入emmc不正常 最近没时间弄 5.15先用着

**Comment by cjd6568358** [comment]
> > > 
> > 
> > 
> > 请把你的固件发一下
> 
> TV盒子固件包刷的是这个 下载链接：https://pan.baidu.com/s/1fb2kXW5VwFr5yrOP1kV2_Q 提取码：n3ag

如果刷完安卓系统后盒子一直进入紧急恢复模式，需要重新线刷，勾选 擦除flash+BootLoader

**Comment by gxbrave** [comment]
> > > > uEnv.txt是正确的。不是ini
> > > 
> > > 
> > > 6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态
> > 
> > 
> > ssh能连就已经正常了我也没有hdmi输出 应该还没适配好 我的另一个s905l3a-b的就有显示
> 
> 问一下，有没有保留移动官方原系统的img包啊？我没存，我想试试能不能通过提取官方的dtb

我跟你的情况一模一样，但是我现在还没能从u盘启动成功，连不上ssh也ping不到

**Comment by su-yihong** [comment]
内核5.15.162，可以支持写入emmc,设备序号选124能正常启动，无线网卡识别不到只能连有线，hdmi无输出，但是蓝牙好像识别到了。

**Comment by cjd6568358** [comment]
> > > > > uEnv.txt是正确的。不是ini
> > > > 
> > > > 
> > > > 6.1.46内核的版本，暂时没去尝试了，等一下我试试，现在刷了个5.15，改回了 `txt`，去掉了 `.bak` ，使用 `e900v22e` 的 `dtb` ，ssh可以连，但是没有 `hdmi` 显示，处于黑屏状态
> > > 
> > > 
> > > ssh能连就已经正常了我也没有hdmi输出 应该还没适配好 我的另一个s905l3a-b的就有显示
> > 
> > 
> > 问一下，你是用哪个内核的呢？能写入emmc吗？
> 
> 现在暂时用的5.15正常写入emmc，写入序号选的121正常使用 6.1.x优盘能启动 写入emmc不正常 最近没时间弄 5.15先用着

老哥，不能用6.1的内核问题能帮忙解决下吗？不然老是停留在5.15也挺烦的

**Comment by cjd6568358** [comment]
> hdmi就是没有，ssh访问管理 没法写入emmc看文档，降低dtb频率

大佬 这个型号emmc不支持6.1内核的问题还存在吗？能帮忙解决一下吗？想用最新内核了

**Comment by cjd6568358** [comment]
> hdmi就是没有，ssh访问管理 没法写入emmc看文档，降低dtb频率

大佬 这个型号emmc不支持6.1内核的问题还存在吗？能帮忙解决一下吗？想用最新内核了

**Comment by su-yihong** [comment]
在使用了这个机型几个月后，发现它没有什么问题，我总结了刷机的以下几点:
1:下载最新的镜像，刷入u盘，将u盘插入盒子并在安卓系统中重启进入rec模式（root底包），在盒子启动时，它会引导u盘。
2:由于芯片不同，所以没有HDMI输出和WiFi，将盒子插入网线，找到它的IP，并用ssh连接，

**Comment by su-yihong** [comment]
在使用了这个机型几个月后，发现它没有什么问题，我总结了刷机的以下几点:
1:下载最新的镜像，刷入u盘，将u盘插入盒子并在安卓系统中重启进入rec模式（root底包），在盒子启动时，它会引导u盘。
2:由于芯片不同，所以没有HDMI输出和WiFi，将盒子插入网线，找到它的IP，并用ssh连接，设置好密码，然后输入 armbian-update 5.15.162 切换到内核5.15.162（不要使用6代内核！刷入以后也不要换，小心变砖🧱）
3:输入 armbian-install 选择序号124，等待刷机完成。
4:重启盒子，拔出u盘。
然后就可以开始盒子的使用了，接入硬盘并安装samba开启影音体验！

**Comment by su-yihong** [comment]
我也不知道为什么这个没法刷入6代内核，第五代能稳定使用已经很不错了。

**Comment by su-yihong** [comment]
安卓底包可以看看上面的链接
自己去CSDN或者恩山无线论坛去找

**Comment by su-yihong** [comment]
在使用了这个机型几个月后，发现它没有什么问题，我总结了刷机的以下几点:
1:下载最新的镜像，刷入u盘，将u盘插入盒子并在安卓系统中重启进入rec模式（root底包），在盒子启动时，它会引导u盘。
2:由于芯片不同，所以没有HDMI输出和WiFi，将网线插入盒子，找到它的IP，并用ssh连接，设置好密码，然后输入 armbian-update -k 5.15.162 切换到内核5.15.162（不要使用6代内核！刷入以后也不要换，小心变砖🧱）
3:输入 armbian-install 选择序号124，等待刷机完成。
4:重启盒子，拔出u盘。
然后就可以开始盒子的使用了，接入硬盘并安装samba开启影音体验！
由于机型储存较小，不建议使用docker

**Comment by su-yihong** [comment]
如果用这个盒子当nas还行，ffmpeg转码也可以，可以胜任一些轻视频转码，挂机下载，轻网站，但要是搞其他的比如用box64和wine我看来是不行。

**Comment by cjd6568358** [comment]
> 在使用了这个机型几个月后，发现它没有什么问题，我总结了刷机的以下几点: 1:下载最新的镜像，刷入u盘，将u盘插入盒子并在安卓系统中重启进入rec模式（root底包），在盒子启动时，它会引导u盘。 2:由于芯片不同，所以没有HDMI输出和WiFi，将网线插入盒子，找到它的IP，并用ssh连接，设置好密码，然后输入 armbian-update -k 5.15.162 切换到内核5.15.162（不要使用6代内核！刷入以后也不要换，小心变砖🧱） 3:输入 armbian-install 选择序号124，等待刷机完成。 4:重启盒子，拔出u盘。 然后就可以开始盒子的使用了，接入硬盘并安装samba开启影音体验！ 由于机型储存较小，不建议使用docker

我看上面的解释是6.x内核需要打补丁，截止作者回复的时候内核只有5.10/5.15的stable和dev/beta/flippy是打了补丁的。而这个盒子是所有内核都通用的，所以可以尝试更新内核到这些版本.期待反馈
https://github.com/ophub/kernel/releases

**Comment by su-yihong** [comment]
![Screenshot_20241019_134743_com microsoft emmx_edit_45473976676915](https://github.com/user-attachments/assets/b428ebc8-6422-41d6-9619-034bb7fd4ca6)
请问您说的补丁是这个吗

**Comment by su-yihong** [comment]
🙃有人知道补丁的用法吗

**Comment by su-yihong** [comment]
不能用6代内核是因为u-boot版本太老，无法引导内核。有关u-boot的升级网上的文章比较少，也不知道具体怎么弄🙃
（这到底怎么个说法🙃）

**Comment by cjd6568358** [comment]
汇报一下最新情况，目前该设备已经全部支持5.x.y/6.1.y/6.12.y内核，也就是通刷了。
镜像选以下两种都可以正常启动并刷入emmc.
Armbian_26.02.0_amlogic_s905l3b_*
Armbian_26.02.0_amlogic_s905l3b-e900v22e_*
armbian-install 选择126

**Comment by gdjdkid** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 你看看这有没有对应的安卓系统，线刷安卓，再刷armbian，救砖也可以用这里的安卓

不用线刷安卓，可以试试直接刷底包，链接为https://s.help.ikongji.com/smallbox/smallboxhelp/smallbox-arm-AmLogic-install.html#%E5%88%B7%E5%BA%95%E5%8C%85   这个目的是改写bootloader，让盒子允许从U盘启动。

**Comment by HeroPoter** [comment]
> 汇报一下最新情况，目前该设备已经全部支持5.x.y/6.1.y/6.12.y内核，也就是通刷了。 镜像选以下两种都可以正常启动并刷入emmc。 Armbian_26.02.0_amlogic_s905l3b_* Armbian_26.02.0_amlogic_s905l3b-e900v22e_* armbian-install 选择126

安卓刷机包用哪个

**Comment by XuPen9** [comment]
> 汇报一下最新情况，目前该设备已经全部支持5.x.y/6.1.y/6.12.y内核，也就是通刷了。 镜像选以下两种都可以正常启动并刷入emmc. Armbian_26.02.0_amlogic_s905l3b_* Armbian_26.02.0_amlogic_s905l3b-e900v22e_* armbian-install 选择126

佬，同求安卓刷机包！我尝试了很多 都无法正常写入emmc！要么就是其他错误！

**Comment by cjd6568358** [comment]
> 汇报一下最新情况，目前该设备已经全部支持5.x.y/6.1.y/6.12.y内核，也就是通刷了。 镜像选以下两种都可以正常启动并刷入emmc. Armbian_26.02.0_amlogic_s905l3b_* Armbian_26.02.0_amlogic_s905l3b-e900v22e_* armbian-install 选择126

再更新一版备注，
1. 6.18内核目前也正常。
2. 这个盒子挑U盘，如果插上没反应就换一个U盘试试。
3. 如果U盘刷fnos镜像第一次进系统打不开5666网页卡顿是正常的。一般放半天以后再尝试就能正常进了，写入EMMC后一切正常

**Comment by SuyihQwQ** [comment]
https://osfile-v2.ootaiwaevufe.com/image/Sparrow-aml-1.0.1-S905L3B-E900V22E-2510201618.img.xz?sign=4919a5933767cf7de19c70c450659c69&t=6ab3ad8f
试一下这个底包
