### ISSUE TITLE
docker跑ubuntu编译内核，chroot failed, no /bin/bash

### ISSUE THREAD

**Issue by SweetPine1** [ophub/amlogic-s9xxx-armbian#1615]
**软件信息**
docker version: Docker version 19.03.15, build 99e3ed8919
host env:  debian 9+5.10.103内核

**other info**
docker build -t ubuntu:v1 .
docker run -v ~/amlogic-s9xxx-armbian:/root -v /dev:/dev --privileged  -it ubuntu:v1 bash

**Describe the bug | 问题描述**
docker跑ubuntu编译内核，会报chroot failed, no /bin/bash，或者exec format error
```bash
[ INFO ] Enter the chroot armbian system...
+ chroot /root/compile-kernel/output/chroot/root /bin/bash -c '/root/ubuntu_chroot_armbian.sh 5.10.190-ophub'
chroot: failed to run command '/bin/bash': No such file or directory
```
请问这个有办法解决吖？

**Comment by ophub** [comment]
在Docker中，chroot 命令的使用是有一些限制的，因为 Docker 隔离了容器的文件系统和进程空间，所以并不像在传统的虚拟机或本地系统中使用 chroot 那样直接操作宿主文件系统。
所以用docker无解。

**Comment by arthur819** [comment]
> 在Docker中，chroot 命令的使用是有一些限制的，因为 Docker 隔离了容器的文件系统和进程空间，所以并不像在传统的虚拟机或本地系统中使用 chroot 那样直接操作宿主文件系统。 所以用docker无解。

我也遇到了与楼主类似的问题，是在kvm虚拟机环境上，

**Comment by arthur819** [comment]
> 在Docker中，chroot 命令的使用是有一些限制的，因为 Docker 隔离了容器的文件系统和进程空间，所以并不像在传统的虚拟机或本地系统中使用 chroot 那样直接操作宿主文件系统。 所以用docker无解。

我也遇到了与楼主类似的问题，不过现象有些差异，kvm虚拟机环境上可以用以下命令复现

root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian# ls
armbian.img
root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian# mkdir tst
root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian# losetup -P -f --show armbian.img
/dev/loop4
root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian# mount /dev/loop4p2 tst
root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian# cd tst/
root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian/tst# ls
bin  boot  dev  etc  home  initrd.img  initrd.img.old  lib  lib64  lost+found  media  mnt  opt  proc  root  run  sbin  selinux  srv  sys  tmp  usr  var  vmlinuz  vmlinuz.old
root@ubuntu:/usr/tmp/amlogic-s9xxx-armbian/compile-kernel/tools/armbian/tst# chroot .
chroot: failed to run command ‘/bin/bash’: Exec format error

**Comment by arthur819** [comment]
楼主你好，这个问题已经解决了，在宿主机中安装一个包可解，

apt install qemu-user-static

目前可以在docker里面内核编译。
