### ISSUE TITLE
am40 RK3399 需要更新下dtb文件，使用基本完美

### ISSUE THREAD

**Issue by yhbas** [ophub/amlogic-s9xxx-armbian#1617]
1、屏幕字符不断闪烁的问题更新dtb文件可以解决
现在rockchip_smart-am40设备的各个发行版在am40工控机上都有屏幕字符不断闪烁的问题。
我测试了网上很多版本，（...这个网址刚才记错了，上传到网盘了，见四楼链接） ， 用里面的dtb文件替代就可以了。HDMI（尾插的）就可以正常显示，字符不再闪烁了。

2、测试结果基本完美
替代.dtb文件后，O大制作发布的各个rockchip_smart-am40版本都可以使用。
经过测试，千兆网卡、Wifi、蓝牙、2个USB3.0、4个USB2.0都正常。
设备可以从TF卡启动，也可以从eMMC启动。
还有点不足的就是：HDMI不支持2K分辨率，最大1920x1080，另外HDMI音频不能驱动。期待有大侠能解决这个不足。

**Comment by ophub** [comment]
感谢分享，我更新一下

**Comment by yhbas** [comment]
> ```
> a90bcc30055ddc21ad783515c774e1025ff709ad6d53b51ee999946ea70fe8a4  rk3399-smart-am40.dtb
> a90bcc30055ddc21ad783515c774e1025ff709ad6d53b51ee999946ea70fe8a4  am40.dtb
> ```
> 
> 我仓库里的文件就是从这里下载拷贝的。我对比了下完全一样。
> 
> ```
> 83779a9abc377871703070bccc12f107cba7be1fab85dc4b1549a016814da5f7  idbloader.bin
> 3bcb05faeae92f42614dc39ae52cfe570973bb92a6bfcdaa23f95e41084e1356  trust.bin
> a00daab22743da853ca068463be7ea521cb1a7b4fd22d6a2265fc1bd28cd67cb  uboot.img
> ```
> 
> u-boot我也比较了下，完全一样

不是am40.dtb (73,169 字节）
记得好像是从 Armbian_21.08.9_am40_focal_current_5.10.63.img.7z 这个文件中提取出来的
rk3399-smart-am40.dtb大小应该是 78,848 字节
有什么办法可以直接发给你？

**Comment by yhbas** [comment]
> ```
> a90bcc30055ddc21ad783515c774e1025ff709ad6d53b51ee999946ea70fe8a4  rk3399-smart-am40.dtb
> a90bcc30055ddc21ad783515c774e1025ff709ad6d53b51ee999946ea70fe8a4  am40.dtb
> ```
> 
> 我仓库里的文件就是从这里下载拷贝的。我对比了下完全一样。
> 
> ```
> 83779a9abc377871703070bccc12f107cba7be1fab85dc4b1549a016814da5f7  idbloader.bin
> 3bcb05faeae92f42614dc39ae52cfe570973bb92a6bfcdaa23f95e41084e1356  trust.bin
> a00daab22743da853ca068463be7ea521cb1a7b4fd22d6a2265fc1bd28cd67cb  uboot.img
> ```
> 
> u-boot我也比较了下，完全一样

我记错了。不是am40.dtb (73,169 字节）
刚刚上传到百度网盘了
链接：https://pan.baidu.com/s/1orT78CXxyv9EI6ARpi9gmg?pwd=1234 
提取码：1234

这两个dtb是在kernel-5.15.111-by-Leoslion.tar中的。原文件名是rk3399-smart-am40-no_dp.dtb和rk3399-smart-am40-no_dp-oc.dtb

**Comment by ophub** [comment]
好的，谢谢分享，已经更新。https://github.com/ophub/amlogic-s9xxx-armbian/commit/346a41a4323aa8228bcc7a2c12f740d929fc3634

以后的固件将使用这个新版dtb。

**Comment by yhbas** [comment]
> 好的，谢谢分享，已经更新。[346a41a](https://github.com/ophub/amlogic-s9xxx-armbian/commit/346a41a4323aa8228bcc7a2c12f740d929fc3634)
> 
> 以后的固件将使用这个新版dtb。

那就方便了。谢谢O大！

**Comment by mlw221** [comment]
不知这个dtb 挂载 usb3.0硬盘盒的读写速度如何？ 我现在用的通过ftp传文件上去，最快也只有11兆。

**Comment by ckkjaafar** [comment]
> 不知这个dtb 挂载 usb3.0硬盘盒的读写速度如何？ 我现在用的通过ftp传文件上去，最快也只有11兆。

am40 前置usb3.0 接jms578易驱线3.5硬盘（DC供电） 没显示 没日志 仅仅是硬盘转动。接am40尾插usb2.0速度20M/s（SMB速度7M/s-20M/s开始30M/s，ext4）。电脑ntfs 100M/s。 
apt upgrade报
The following packages have been kept back:
armbian-bsp-cli-odroidn2-current
绿联硬盘盒2.5正常使用，50M/s 内核6.1.52，6.1.55
内核6.1.59 绿联2.5也不识别了
linux需要格式化ext4。 而ntfs在linux普遍10M/s内

**Comment by 1qingfeng-1** [comment]
am40.dtb 缺少VPU支持，导致无法使用MPP硬解

**Comment by 1qingfeng-1** [comment]
[hevc_rkmpp_decoder @ 0xaaaac21e11d0] Failed to initialize MPP context (code = -1).
[hevc_rkmpp_decoder @ 0xaaaac21e11d0] Failed to initialize RKMPP Codec.

**Comment by 0xRK3399** [comment]
终于找到能驱动前置HDMI的补丁下载
https://am40.cache.cloudns.org

**Comment by WlphM** [comment]
> [hevc_rkmpp_decoder @ 0xaaaac21e11d0] Failed to initialize MPP context (code = -1). [hevc_rkmpp_decoder @ 0xaaaac21e11d0] Failed to initialize RKMPP Codec.

这个·现在解决了吗

**Comment by xiaobao1980** [comment]
大佬们，哪个版本支持本机hdmi输出？没有ops扩展板

**Comment by tiancaiamao** [comment]
大哥，我发现你打过补丁的这个内核，没有把 uas 模块带进去
导致外接移动硬盘盒的时候，走的较慢的协议
移动硬盘盒，用 usb3 接到 am40 上，ssd 硬盘读写速度只有 170MB/s
@yhbas
