### ISSUE TITLE
 Bluetooth is not working on X96MaxPlus

### ISSUE THREAD

**Issue by tux-vador** [ophub/amlogic-s9xxx-armbian#1618]
**Device Information **
 - SOC: S095x3
 - Model : X96MaxPlus 

**Armbian Version**
 - Kernel Version: 6.1.42
 - Release: bookworm
 - **armbien installed on emmc**

**Describe the bug**
Hi
i have an issue with my X96Max Plus box. i success to install armbian and wifi and Ethernet are working good but not bluetooth.

i tried all DTB file and also different kernel version (6.1.42 ; 5.4.252 ; 5.15.123 and 5.10.189) but same issue.

i readed these issue
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1086
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1144

 and see on this reponse https://github.com/ophub/amlogic-s9xxx-armbian/issues/1144#issuecomment-1463197524 that [drafort](https://github.com/drafort) successed 

i did the same steps but still don't work. no device on rfkill

```
root@armbian:~# rfkill
ID TYPE DEVICE      SOFT      HARD
 0 wlan phy0   unblocked unblocked
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='502'
MODEL_NAME='X96-Max+_1GB'
SOC='s905x3'
FDTFILE='meson-sm1-x96-max-plus.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.1.25'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='extlinux.conf'
ROOTFS_TYPE='ext4'
DISK_TYPE='emmc'
AMPART_STATUS='yes'
MLUBOOT_STATUS='yes'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='unifreq'
BUILDER_NAME='angel'
PACKAGED_DATE='2023-08-01'
root@armbian:~#
```

how can i downgrade to kernel 6.1.15 as it's not available on github
```
root@armbian:~# armbian-update -k 6.1.15 -m yes
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Dependency check completed.

[ STEPS ] Start checking network status...
[ INFO ] You can access [ github.com ] normally.

[ STEPS ] Start initializing parameters...
[ INFO ] Armbian platform: [ amlogic ]
[ INFO ] Kernel download repository: [ ophub/kernel ]
[ INFO ] Kernel download cdn: [  ]
[ INFO ] Kernel tags: [ stable ]
[ INFO ] Kernel version: [ 6.1.15 ]
[ INFO ] Armbian is running on: [ /dev/mmcblk2 ]

[ STEPS ] Start querying kernel version...
[ INFO ] Current version: [ 6.1.25 ], Latest version: [ 6.1.15 ].

[ STEPS ] Start downloading kernel package...
[ INFO ] Download kernel from: [ https://github.com/ophub/kernel/releases/download/kernel_stable/6.1.15.tar.gz ]
[ INFO ] Download kernel to:   [ /tmp/tmp.JSTWlZyqDc ]
[ ERROR ] Failed to download kernel.
```

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/19595887/3c749873-8a7e-412c-87b2-9faf9111e104)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/19595887/35dbc62c-d712-4551-9d48-a1cbc17fd06f)

if you can help me please to choose the good kernet and DTB file and provide the step to do

regards

**Comment by ophub** [comment]
6.1.15 has been deleted and is no longer available

**Comment by tux-vador** [comment]
thanks @ophub but do you think that i can find a solution with recent kernel like 6.1.45

**Comment by ophub** [comment]
you can

**Comment by ophub** [comment]
下载地址：
链接：https://pan.baidu.com/s/15b1OWLXcmpJjqdaYFKvIlg?pwd=6nc4 
提取码：6nc4 
链接：https://pan.baidu.com/s/14WCQid4GHB76RLFZKb3VQA?pwd=3jwb 
提取码：3jwb 
链接：https://pan.baidu.com/s/1j7OTusExLii53ganNHHO0Q?pwd=zq3y 
提取码：zq3y

**Comment by tux-vador** [comment]
after using meson-sm1-x96-max-plus-2101.dtb
```
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='506'
MODEL_NAME='X96-Max+_2101'
SOC='s905x3'
FDTFILE='meson-sm1-x96-max-plus-2101.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.1.42'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='extlinux.conf'
ROOTFS_TYPE='ext4'
DISK_TYPE='emmc'
AMPART_STATUS='yes'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='unifreq'
BUILDER_NAME='angel'
PACKAGED_DATE='2023-08-01'
```
i can now see the bluetooth device with rfkill
root@armbian:~# rfkill
```
ID TYPE      DEVICE      SOFT      HARD
 0 wlan      phy0   unblocked unblocked
 1 bluetooth hci0   unblocked unblocked
```
but nothing with blluetoothctl 
```
root@armbian:~# bluetoothctl
Agent registered
[bluetooth]# show
No default controller available
[bluetooth]# scan on
No default controller available
```
also i can see some error on the dmseg : 
```
root@armbian:~# dmesg | grep -i bluetooth
[    6.445405] Bluetooth: Core ver 2.22
[    6.447946] Bluetooth: Starting self testing
[    6.771944] Bluetooth: ECDH test passed in 313555 usecs
[    6.880050] Bluetooth: SMP test passed in 3255 usecs
[    6.940648] Bluetooth: Finished self testing
[    6.943350] NET: Registered PF_BLUETOOTH protocol family
[    6.947055] Bluetooth: HCI device and connection manager initialized
[    7.084772] Bluetooth: HCI socket layer initialized
[    7.087343] Bluetooth: L2CAP socket layer initialized
[    7.124676] Bluetooth: SCO socket layer initialized
[    7.173655] Bluetooth: HCI UART driver ver 2.3
[    7.176164] Bluetooth: HCI UART protocol H4 registered
[    7.180045] Bluetooth: HCI UART protocol BCSP registered
[    7.240912] Bluetooth: HCI UART protocol LL registered
[    7.243410] Bluetooth: HCI UART protocol ATH3K registered
[    7.296940] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    7.300896] Bluetooth: HCI UART protocol Intel registered
[    7.373027] Bluetooth: HCI UART protocol Broadcom registered
[    7.375646] Bluetooth: HCI UART protocol QCA registered
[    7.380696] Bluetooth: HCI UART protocol AG6XX registered
[    7.456754] Bluetooth: HCI UART protocol Marvell registered
[    8.056774] Bluetooth: hci0: RTL: examining hci_ver=0a hci_rev=000c lmp_ver=0a lmp_subver=8822
[    8.065626] Bluetooth: hci0: RTL: rom_version status=0 version=3
[    8.068370] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cs_fw.bin
[    8.076924] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cs_config.bin
[    8.104753] Bluetooth: hci0: RTL: cfg_sz 33, total sz 36285
[    9.740391] systemd[1]: Reached target bluetooth.target - Bluetooth Support.
[   10.120603] Bluetooth: hci0: command 0xfc20 tx timeout
[   18.148510] Bluetooth: hci0: RTL: download fw command failed (-110)
[   20.192498] Bluetooth: hci0: command 0xfcf0 tx timeout
[   20.192499] Bluetooth: hci0: Failed to read MSFT supported features (-110)
[  118.378807] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[  118.381080] Bluetooth: BNEP filters: protocol multicast
[  118.385918] Bluetooth: BNEP socket layer initialized
```

any idea how i can resolve this please ?

**Comment by ophub** [comment]
The driver for rtl8822cs is from a third party. According to user feedback, some individuals have reported that it works, while others have experienced issues with its functionality. Currently, there is no solution available for those who are unable to use it.

**Comment by avigrinberg** [comment]
@tux-vador - can you please share with me the img and the dtb that you use?
this is my x96 max plus
![20230831_110502](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74825241/4cde9769-b137-4c20-9370-a509cad64af6)
![20230831_110446](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74825241/8597f1e3-6b56-4d04-9f09-e03c658c3a72)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by tux-vador** [comment]
> @tux-vador - can you please share with me the img and the dtb that you use?
> this is my x96 max plus
> ![20230831_110502](https://user-images.githubusercontent.com/74825241/264717534-4cde9769-b137-4c20-9370-a509cad64af6.jpg)
> ![20230831_110446](https://user-images.githubusercontent.com/74825241/264717545-8597f1e3-6b56-4d04-9f09-e03c658c3a72.jpg)

Hello 

i use this image https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2023.08/Armbian_23.08.0_amlogic_s905x3_bookworm_6.1.49_server_2023.08.28.img.gz

and I use the dtb meson-sm1-x96-max-plus-2101.dtb

you have just to modify the file to use this dtb

**Comment by avigrinberg** [comment]
i download the img and use the meson-sm1-x96-max-plus-2101.dtb but the network card isn't detected only wifi works.
this command armbian-install -m yes finished successful but after trying to load without the usb DOK i get this error message   
![WhatsApp Image 2023-09-01 at 23 05 33](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74825241/f23c054b-d9aa-4b4f-97fc-070df3596d97)

also when i run this command i don't see the meson-sm1-x96-max-plus-2101.dtb
armbian:~:# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='501'
MODEL_NAME='X96-Max+_100Mb'
SOC='s905x3'
FDTFILE='meson-sm1-x96-max-plus-100m.dtb'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='dev'
KERNEL_VERSION='6.1.49'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='uEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='unifreq'
BUILDER_NAME='angel'
PACKAGED_DATE='2023-08-28'

why i've all this problems with my x96max+?

**Comment by tux-vador** [comment]
Yes it’s look like you use another dtb 

try with using armbian-install (don’t use -y) and when you reply to first question use the correct  dtb number

if I remember well for dtb sm1-x96-max-plus-2101.dtb. It’s 506
