### ISSUE TITLE
Can MediaTek processor support be supported?

### ISSUE THREAD

**Issue by yibaoby** [ophub/amlogic-s9xxx-armbian#1619]
**Device Information | 设备信息**
 - SOC: [MT8685]
 - Model [M11]

**Describe the bug | 问题描述**
Can MediaTek processor support be supported? If I can, I would like to sponsor USD

![微信截图_20230817004135](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131518836/ceba8bb6-5fcc-4e04-9d75-b8b1e11abbbd)

**Comment by ophub** [comment]
This chip is currently not supported
