### ISSUE TITLE
The meson-sm1-sei610.dtb file is in the firmware, you can use it by changing Armbian_22 version. 02.1_Aml_s905x3 `/boot/uEnv.txt`. Change the name of the dtb file inside.

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#162]
The meson-sm1-sei610.dtb file is in the firmware, you can use it by changing Armbian_22 version. 02.1_Aml_s905x3 `/boot/uEnv.txt`. Change the name of the dtb file inside.

_Originally posted by @ophub in https://github.com/ophub/amlogic-s9xxx-armbian/issues/160#issuecomment-1065985952_

ok I flashed the pen and edited the uEnv.txt file to meson-sm1-sei610.dtb looking like this:

[uEnv.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8239261/uEnv.txt)

the first boot is ok,I have an IP, so much so that I'm accessing it by putty
but it gives me this when i try to install:

![IMG_20220313_105647](https://user-images.githubusercontent.com/83761813/158056312-d6a44601-48d8-4f79-91c1-6b573607f326.jpg)

**Comment by ophub** [comment]
Do not use the title as the main text in the future, the title should be short

Select 0 to only support the use of 5.4 firmware, not to support the use of 5.10 and above firmware, and it cannot be used without u-boot support.

**Comment by ddams2000** [comment]
I don't understand, how install 5.10 and above then please?
cordially

**Comment by ophub** [comment]
armbian-update 5.10.106

**Comment by ddams2000** [comment]
how install 5.10 and above on emmc ?

**Comment by ophub** [comment]
Did you test in usb that the 5.10 kernel works?

**Comment by ddams2000** [comment]
yes it s my post : https://github.com/ophub/amlogic-s9xxx-armbian/issues/175

**Comment by ophub** [comment]
If you have tested it, use armbian-update 5.10.106 to change the kernel
