### ISSUE TITLE
X88 Pro Pro X3 / X99 Max Plus / Transpeed X3 Plus - Status

### ISSUE THREAD

**Issue by araczkowski** [ophub/amlogic-s9xxx-armbian#1621]
**Device Information | 设备信息**
 - SOC: [eS095x3]
 - Model [X88 Pro Pro X3]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.42]
 - Release: [lunar]

**Describe the bug | 问题描述**

How can I share my dts/dtb to add this box to the supported devices?
Any help how to fix reported problems below will be appreciated.

----------------------------
Please provide a detailed description of the issue and, if necessary, attach a screenshot.

I was able to run the lunar on mainline kernel 6.1.42 on X88 Pro Pro X3 4/128GB using my dtb file. 
I can share this file and we can add this box to supported devices list.

Almost all works correctly except the LED Screen Display, Bluetooth and eMMC Installation, but I can work on this. 

### LED Screen Display -> NOK
I tried to control the display according to the instruction  [led_screen_display_control.md](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/led_screen_display_control.md) but it doesn't work, the error is:

```
/usr/sbin/armbian-openvfd: line 106: /sys/class/leds/openvfd/led_on: No such file or directory
```

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/ac50bf0c-ef03-4592-aeff-bc6696981b9a)

### Bluetooth -> NOK
It partly works but the pairing is not possible.
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/b0357f3b-fb7b-40c9-bf23-64c42dfb2e31)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/dee3f3dd-85ee-4d1a-a3b8-7c3e389cadbd)

### eMMC Installation -> NOK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/b7d41868-5560-4b32-b312-276146868f4d)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/c9f4a9c2-004e-408a-a2a9-244bf87d8ebf)

after this, the box is not starting from eMMC

### SSH -> OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/3243fd38-35eb-4bb2-aa19-0b400aa644a8)

### WiFi -> OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/18eb4362-190f-4846-b18d-c290e5a48409)

### Ethernet -> OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/34e81769-b3b3-4568-ba11-49e7812af7b8)

### USB -> OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/b67d701f-3a2c-4fbe-b5f2-2c884c2e677e)

### Home Assistant Supervisor -> OK

to support docker cgroup v1 I added ``systemd.unified_cgroup_hierarchy=0`` parameter setting in cmdline
thanks for the description [How to Modify cmdline Settings](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents#1214-how-to-modify-cmdline-settings) :+1: 

aditonally to solve this

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/67eb67cc-6307-4ccf-93dd-7849e87b1b6a)

I added this to the Linux kernel boot parameters ``apparmor=1 security=apparmor ``

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/73d17276-51b8-4ae0-b9da-7f5e46707d22)

and now it is OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/9d824066-6695-4007-81af-dd33f6ae1dc3)

----------------------------------------------

## The pictures of the board

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/6cf8eb23-b836-499a-ac55-c2ab6a16feef)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/19ac872e-05e2-4dd4-86f6-970b4264b0ba)

-----------------------------------------------

## Thanks :heart: 
@ophub you are my hero :) 

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/cdfa91e7-c3b7-46c2-acd3-d89544c8ce5f)

Any tips how to fix problems (installation on eMMC, LED Screen Display and BT) will be appreciated :+1:

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/tree/main/arch/arm64/boot/dts/amlogic

Thank you for your sharing.

The above is the source code of the kernel's Device Tree Source (DTS). What modifications have you made to the original version in your Device Tree Binary (DTB) file? It might be better to create a new dedicated DTS file, which would make maintenance and updates easier compared to using a fixed DTB file.

**Comment by araczkowski** [comment]
1. I took the dts file from here:
https://github.com/danboid/meson-sm1-sei610-qca9377-bt/blob/main/meson-sm1-sei610-qca9377-bt.dts

2. the only change I did was to change the bluetooth section:

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/e5686ecb-f859-4dcf-8b43-3127d3eb035d)

3. I named the file  ``meson-sm1-x88pro-x3.dts`` 

4. and I compiled it to dtb via:
```
dtc -I dts -O dtb -f meson-sm1-x88pro-x3.dts -o meson-sm1-x88pro-x3.dtb
```

the ziped dts and dtb files are attached

[meson-sm1-x88pro-x3.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12368569/meson-sm1-x88pro-x3.zip)

**Comment by ophub** [comment]
`meson-sm1-x96-max-plus-q2.dtb`

Based on the information you provided, there is no need to add a new DTB (Device Tree Blob). The original DTB file included in the kernel, `meson-sm1-x96-max-plus-q2.dtb` is the one you need. This applies to device number `508`, which is the same as X96-Max+Q2 and X96-Air-Q1000.

You can modify the name of the DTB in `/boot/uEnv.txt` and then restart to test the changes.

**Comment by araczkowski** [comment]
unfortunatelly no boot on the meson-sm1-x96-max-plus-q2.dtb

Please see the screen with log errors (sory I do not have working uart/debug connection to this board)

![2023-08-17-14-21-40-539](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/ed826cf0-0ead-46e3-8803-221e59299b09)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus-q2.dts

This is the source code of q2, he just made the same modification as the bluetooth chip. According to the post you posted above, danboid also introduced in his warehouse, you can use my q2 directly, no need to use his modified files anymore.

danboid has already reported this q2 device here, These are 2 identical files.

https://github.com/ophub/amlogic-s9xxx-armbian/issues/366

**Comment by araczkowski** [comment]
## lunar_6.1.42

1. I red the https://github.com/ophub/amlogic-s9xxx-armbian/issues/366 according to this the ``meson-sm1-x96-max-plus-q2.dtb``  is almost identical to the ``meson-sm1-h96-max.dtb``. To check this, I decompiled thes dtb-s, and it is true:
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/5131aa61-1c02-4bec-bf26-f79bafe4e31d)

2. I compare the dtb-s ``meson-sm1-x96-max-plus-q2.dts`` with ``meson-sm1-x88pro-x3.dts`` the files has some parts in comon but there is a lot of diferences
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/f0136f50-cc71-415d-be83-1595a826cc78)

3. I run a box on  ``meson-sm1-x96-max-plus-q2.dtb ``
Boot -> with problems reported on the picture above
ethernet NOK
wifi NOK  
HDMI OK 

4. I run a box on ``meson-sm1-x88pro-x3.dtb`` dtb from [danboid](https://github.com/danboid/meson-sm1-sei610-qca9377-bt/blob/main/meson-sm1-sei610-qca9377-bt.dts)
Boot OK
ethernet OK
wifi OK
BT almost OK
hdmi OK


## lunar_5.15.123

1. I run a box on  ``meson-sm1-x96-max-plus-q2.dtb ``
Boot -> with problems reported on the picture above
ethernet NOK
wifi NOK  
hdmi OK 

2. I run a box on ``meson-sm1-x88pro-x3.dtb`` dtb from [danboid](https://github.com/danboid/meson-sm1-sei610-qca9377-bt/blob/main/meson-sm1-sei610-qca9377-bt.dts)
Boot OK
ethernet OK 
wifi OK
BT almost OK 
hdmi OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/a4f30201-ac6f-49ab-8f00-d62158e54586)


## lunar_5.10.189

1. I run a box on  ``meson-sm1-x96-max-plus-q2.dtb ``
Boot OK
ethernet NOK 
wifi OK 
BT NOK 
hdim OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/5e771c28-0ba7-4722-8b17-2f445fd0cad3)


2.  I run a box on ``meson-sm1-x88pro-x3.dtb`` dtb from [danboid](https://github.com/danboid/meson-sm1-sei610-qca9377-bt/blob/main/meson-sm1-sei610-qca9377-bt.dts)
Boot OK
ethernet OK 
wifi OK 
BT almost OK 
hdim OK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/fcedef53-b32d-4e5a-9108-a4e886d539cd)

## lunar_5.4.252
1. I run a box on ``meson-sm1-x96-max-plus-q2.dtb`` 
Boot OK
ethernet NOK 
wifi OK 
BT NOK 
hdim OK
Memory 3.24G NOK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/bad88f7e-8dcf-4e6a-9b25-80ce61d52b6f)


2. I run a box on ``meson-sm1-x88pro-x3.dtb`` dtb from [danboid](https://github.com/danboid/meson-sm1-sei610-qca9377-bt/blob/main/meson-sm1-sei610-qca9377-bt.dts)
Boot OK
ethernet OK 
wifi OK 
BT almost OK 
hdim OK
Memory 3.24G NOK

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/7880ee6d-d722-4452-8af6-d856b7154fb8)


## different dtb for  S905x in lunar_6.1.42
I checked each dtb for s905x in ``/boot/dtb/amlogic``
for many the boot works, and for some there was a wifi connection, but there was no dtb on which I had the ethernet


## Conclusions
 1. ``meson-sm1-x88pro-x3.dtb`` dtb from [danboid](https://github.com/danboid/meson-sm1-sei610-qca9377-bt/blob/main/meson-sm1-sei610-qca9377-bt.dts) works with each kernel
2. only on this dtb I have ethernet
3. meson-sm1-x88pro-x3.dts has some parts in comon with meson-sm1-x96-max-plus-q2.dts but there is a lot of diferences


@ophub what do think about this ?

**Comment by ophub** [comment]
Your DTS file is not the source file; it's a decompiled file. It cannot be compiled within the kernel. It can only be adjusted at specific points through decompilation. This kind of Device Tree Blob (DTB) has been tested in the current version, but there is no guarantee it will work correctly in future kernel versions. It's advisable to identify the differences, follow the kernel's DTS writing conventions, and create a dedicated DTS file. You can refer to the writing style in 'q2.dts'. Incorporate the existing DTS, reconfiguring only the differing nodes. This way, you'll inherit the existing file while retaining only the differences.

I've placed 'meson-sm1-x88-pro-x3.dtb' in the repository. I compiled one for you to download and test. In the installation options, it's listed as '524', named 's905x3-x88-pro-x3'.


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

https://github.com/unifreq/linux-6.1.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus-q2.dts

**Comment by araczkowski** [comment]
## DTS
@ophub Thanks for explanation concerning DTS, I will try to learn more about DT, if I will be able I will prepare real DTS based on existing dts in kernel and orginal dts from android.

## Test of the attached compilation
I tested the build that you attached - everything works OK (Boot, HDMI, Ethernet. WiFi, BT)

## Installation on eMMC
Before I tried the installation I noticed that my DTBs on device is encrypted ``DTB read partitions and report: Unrecognizable DTB, magic 9d8c8056`` I followed this description https://7ji.github.io/crack/2023/01/08/decrypt-aml-dtb.html and I was able to decrypt it,
See the partition Information on this link -> [partition Information from ampart-web-reporter](https://7ji.github.io/ampart-web-reporter/?dsnapshot=logo::8388608:1%20recovery::25165824:1%20misc::8388608:1%20dtbo::8388608:1%20cri_data::8388608:2%20param::16777216:2%20boot::16777216:1%20rsv::16777216:1%20metadata::16777216:1%20vbmeta::2097152:1%20tee::33554432:1%20vendor::335544320:1%20odm::134217728:1%20system::2147483648:1%20product::134217728:1%20cache::1174405120:2%20data::-1:4&esnapshot=bootloader:0:4194304:0%20reserved:37748736:67108864:0%20cache:113246208:1174405120:2%20env:1296039936:8388608:0%20logo:1312817152:8388608:1%20recovery:1329594368:25165824:1%20misc:1363148800:8388608:1%20dtbo:1379926016:8388608:1%20cri_data:1396703232:8388608:2%20param:1413480448:16777216:2%20boot:1438646272:16777216:1%20rsv:1463812096:16777216:1%20metadata:1488977920:16777216:1%20vbmeta:1514143744:2097152:1%20tee:1524629504:33554432:1%20vendor:1566572544:335544320:1%20odm:1910505472:134217728:1%20system:2053111808:2147483648:1%20product:4208984064:134217728:1%20data:4351590400:120718360576:4)

after decryption I run the ``armbian-install`` then I select id ``524``:

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/b4b1123f-f494-4d80-932d-ee85ca81c382)

The installation was successful:
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/2d916e25-596b-4ab9-b7d2-2553c0e342b7)

But the box is not butting from eMMC, black screen without even start logo(this time), 
sorry I could not provide boot logs because on my board there are no paths from RX TX to SoC: https://github.com/Raxone/amlogic-usbdl_s905x3/issues/2

Do you have any idea how to improve the installation script based on information from the link -> [partition Information from ampart-web-reporter](https://7ji.github.io/ampart-web-reporter/?dsnapshot=logo::8388608:1%20recovery::25165824:1%20misc::8388608:1%20dtbo::8388608:1%20cri_data::8388608:2%20param::16777216:2%20boot::16777216:1%20rsv::16777216:1%20metadata::16777216:1%20vbmeta::2097152:1%20tee::33554432:1%20vendor::335544320:1%20odm::134217728:1%20system::2147483648:1%20product::134217728:1%20cache::1174405120:2%20data::-1:4&esnapshot=bootloader:0:4194304:0%20reserved:37748736:67108864:0%20cache:113246208:1174405120:2%20env:1296039936:8388608:0%20logo:1312817152:8388608:1%20recovery:1329594368:25165824:1%20misc:1363148800:8388608:1%20dtbo:1379926016:8388608:1%20cri_data:1396703232:8388608:2%20param:1413480448:16777216:2%20boot:1438646272:16777216:1%20rsv:1463812096:16777216:1%20metadata:1488977920:16777216:1%20vbmeta:1514143744:2097152:1%20tee:1524629504:33554432:1%20vendor:1566572544:335544320:1%20odm:1910505472:134217728:1%20system:2053111808:2147483648:1%20product:4208984064:134217728:1%20data:4351590400:120718360576:4)

let me know please then I will do an installation test. 
Thanks :+1:

**Comment by ophub** [comment]
armbian-install -m yes

**Comment by araczkowski** [comment]
> armbian-install -m yes

no boot, logs from installation below:
```
root@armbian:~# armbian-install -m yes

[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ yes ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------------
ID    SOC        MODEL                               DTB                                               
--------------------------------------------------------------------------------------
501   s905x3     X96-Max+_100Mb                      meson-sm1-x96-max-plus-100m.dtb                   
502   s905x3     X96-Max+_1GB                        meson-sm1-x96-max-plus.dtb                        
503   s905x3     X96-Max+(OverClock)                 meson-sm1-x96-max-plus-oc.dtb                     
504   s905x3     X96-Max+(IP1001M)                   meson-sm1-x96-max-plus-ip1001m.dtb                
505   s905x3     X96-Max+_A100                       meson-sm1-sei610.dtb                              
506   s905x3     X96-Max+_2101                       meson-sm1-x96-max-plus-2101.dtb                   
507   s905x3     X96-Max+Q1                          meson-sm1-x96-max-plus-q1.dtb                     
508   s905x3     X96-Max+Q2,X96-Air-Q1000            meson-sm1-x96-max-plus-q2.dtb                     
509   s905x3     X96-Air-1Gb                         meson-sm1-x96-air-gbit.dtb                        
510   s905x3     X96-Air,X96-Max+100W,100Mb          meson-sm1-x96-air.dtb                             
--------------------------------------------------------------------------------------
511   s905x3     Tencent-Aurora-3Pro                 meson-sm1-skyworth-lb2004-a4091.dtb               
512   s905x3     HK1-Box,Vontar-X3                   meson-sm1-hk1box-vontar-x3.dtb                    
513   s905x3     HK1-Box(OverClock)                  meson-sm1-hk1box-vontar-x3-oc.dtb                 
514   s905x3     H96-Max-X3,Infinity-B32             meson-sm1-h96-max-x3.dtb                          
515   s905x3     H96-Max-X3(OverClock),B32           meson-sm1-h96-max-x3-oc.dtb                       
516   s905x3     Ugoos-X3                            meson-sm1-ugoos-x3.dtb                            
517   s905x3     Ugoos-X3(OverClock)                 meson-sm1-ugoos-x3-oc.dtb                         
518   s905x3     TX3-1Gb                             meson-sm1-tx3-qz.dtb                              
519   s905x3     TX3-1Gb(OverClock)                  meson-sm1-tx3-qz-oc.dtb                           
520   s905x3     TX3-100Mb                           meson-sm1-tx3-bz.dtb                              
--------------------------------------------------------------------------------------
521   s905x3     TX3-100Mb(OverClock)                meson-sm1-tx3-bz-oc.dtb                           
522   s905x3     A95XF3-Air-1Gb                      meson-sm1-a95xf3-air-gbit.dtb                     
523   s905x3     A95XF3-Air-100Mb                    meson-sm1-a95xf3-air.dtb                          
524   s905x3     X88-Pro-X3,X99-Max+,Transpeed-X3+   meson-sm1-x88-pro-x3.dtb                          
525   s905x3     Whale                               meson-sm1-x96-max-plus.dtb                        
0     Other      Customize                           Enter-custom-dtb-name                             
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 524
[ INFO ] Input Box ID: [ 524 ]
[ INFO ] Model Name: [ X88-Pro-X3,X99-Max+,Transpeed-X3+ ]
[ INFO ] FDTFILE: [ meson-sm1-x88-pro-x3.dtb ]
[ INFO ] MAINLINE_UBOOT: [ x96maxplus-u-boot.bin.sd.bin ]
[ INFO ] BOOTLOADER_IMG:  [ hk1box-bootloader.img ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-x96maxplus.bin ]
[ INFO ] NEED_OVERLOAD: [ yes ]
[ STEPS ] Which type of filesystem do you want for your root? 
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 3.92158 s, 1.1 MB/s
[ INFO ] Delete the existing [ 2 ] partitions.
[ STEPS ] Successfully partitioned internal eMMC with amaprt.
[ INFO ] Start create MBR and partittion.
[ INFO ] 01. Write Mainline bootloader: [ x96maxplus-u-boot.bin.sd.bin ]
444+0 records in
444+0 records out
444 bytes copied, 0.00513928 s, 86.4 kB/s
2170+1 records in
2170+1 records out
1111408 bytes (1.1 MB, 1.1 MiB) copied, 0.133986 s, 8.3 MB/s
[ STEPS ] Processing BOOTFS partition...
[ INFO ] Formatting BOOTFS partition...
mkfs.fat 4.2 (2021-01-31)
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
[ INFO ] Copying BOOTFS ...
[ INFO ] Update the [ uEnv.txt ] file.
[ INFO ] Copy [ u-boot-x96maxplus.bin ] to u-boot.emmc
[ STEPS ] Start processing the rootfs partition...
[ INFO ] Formatting ROOTFS ...
/dev/mmcblk2p2 contains a ext4 file system labelled 'ROOTFS_EMMC'
	last mounted on /ddbr/install on Fri Aug 18 13:34:26 2023
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
[ INFO ] Copying ROOTFS ...
[ INFO ] Copying [ etc ] ...
[ INFO ] Copying [ home ] ...
[ INFO ] Copying [ lib64 ] ...
[ INFO ] Copying [ opt ] ...
[ INFO ] Copying [ root ] ...
[ INFO ] Copying [ selinux ] ...
[ INFO ] Copying [ srv ] ...
[ INFO ] Copying [ usr ] ...
[ INFO ] Copying [ var ] ...
[ INFO ] Generate the new fstab file.
[ INFO ] Update the relevant parameters.
[ SUCCESS ] Installation successful. Run [ poweroff ], remove the installation media then re-insert the power supply to boot new system.
root@armbian:~# poweroff 
```

what else can we try?

**Comment by araczkowski** [comment]
I just tried to flash it back using Amlogic USB Burning Tool, I tried 4 times, the same error in the same address
The box has 128GB of eMMC @ophub do you there is a way to recover it?

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/2591d886-7d29-40ba-a976-e6384b8667a2)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.08/Armbian_23.08.0_amlogic_s905x3-x88-pro-x3_jammy_5.15.127_server_2023.08.18.img.gz

tried to flash it back using Amlogic USB Burning Tool, then try 5.15.y

**Comment by araczkowski** [comment]
Hi @ophub I'm back :) 

I flashed the box via Amlogic USB Bourning tool, with unchecked erase checkboxes and it was successful, then I flashed again with checked erase checkboxes it was successful too. 

Now I'm on 5.15.127-ophub, as you can see memory is wrong
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/43b618a1-d30a-4b05-a0a7-d5bf6b875fa2)

the DTB is again encrypted
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/1b93e125-2c7a-4633-ba40-d1f8aafd6c9b)

What we are doing now - standard installation? Or I should I firs make DTB non-encrypted to use ampart?

**Comment by ophub** [comment]
In the absence of mainline u-boot support, armbian can only recognize more than 3G, not the perfect 3.7G, which is normal.

If you want to recognize 3.7 G, you can see how to compile amlogic u-boot in the document

It seems that the current bootloader of the Android system can only boot from the usb, but cannot boot from the emmc. Before solving u-boot and dtb, use it in usb first.

**Comment by ophub** [comment]
Another potential reason for the failure to boot from eMMC is writing to an insecure partition location. Firstly, restore your device to the Android system. Then, following the partition identification method outlined in the repository, verify the location and modify the armbian-install script to include the dedicated partition.


https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

look at 12.10

**Comment by araczkowski** [comment]
Hi @ophub  thanks for the tip

according to this report -> [ampart-web-reporter](https://7ji.github.io/ampart-web-reporter/?dsnapshot=logo::8388608:1%20recovery::25165824:1%20misc::8388608:1%20dtbo::8388608:1%20cri_data::8388608:2%20param::16777216:2%20boot::16777216:1%20rsv::16777216:1%20metadata::16777216:1%20vbmeta::2097152:1%20tee::33554432:1%20vendor::335544320:1%20odm::134217728:1%20system::2147483648:1%20product::134217728:1%20cache::1174405120:2%20data::-1:4&esnapshot=bootloader:0:4194304:0%20reserved:37748736:67108864:0%20cache:113246208:1174405120:2%20env:1296039936:8388608:0%20logo:1312817152:8388608:1%20recovery:1329594368:25165824:1%20misc:1363148800:8388608:1%20dtbo:1379926016:8388608:1%20cri_data:1396703232:8388608:2%20param:1413480448:16777216:2%20boot:1438646272:16777216:1%20rsv:1463812096:16777216:1%20metadata:1488977920:16777216:1%20vbmeta:1514143744:2097152:1%20tee:1524629504:33554432:1%20vendor:1566572544:335544320:1%20odm:1910505472:134217728:1%20system:2053111808:2147483648:1%20product:4208984064:134217728:1%20data:4351590400:120718360576:4)

I tried wit these settings

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/0681cd3c-71d5-45d0-97c7-8ce877518a29)

I assumed that 1.09375GB is 1120MB

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/277597a3-8496-4e17-bd8d-d3ef10a2fda2)

Unfortunately there is no boot, only logo appears...

I will test this more
Have a good day! :+1:

**Comment by araczkowski** [comment]
Hi @ophub I made it :) my "hello world" dts:

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/e836b358-ab28-4d75-89e7-19263c4475b7)


### Ethernet -> OK

### LED Screen Display -> OK

I will test this dts more then I will put it to the https://github.com/unifreq/linux-6.1.y/tree/main/arch/arm64/boot/dts/amlogic

**Comment by ophub** [comment]
ok, thanks

**Comment by araczkowski** [comment]
Hi @ophub  I created u-boot for box x88-pro-x3 - I did all according to the instruction -> [How to build the u-boot file](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.md#1211-how-to-build-the-u-boot-file)

Now I have files in the u-boot root directory and  in the fip directory.
I would like to write the u-boot to eMMC for testing, could you please advice me what files I should write to eMMC?

**Comment by araczkowski** [comment]
OK I made it :) 

I did:
1. cp
```
cp u-boot/fip/u-boot.bin.sd.bin  /media/andrzej/ROOTFS/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin
```
2. run box from SD card
3. install to eMMC
```
armbian-install -m yes -a no
```
4. poweroff, remove SD card and poweron

it works! 

@ophub let me know what files should I send you to add it to the repo?

**Comment by ophub** [comment]
Thank you for sharing. Please send me the file: u-boot/fip/u-boot.bin.sd.bin.
It may not be possible to directly upload the bin file, so please compress it into a zip format before uploading it to a folder.

**Comment by araczkowski** [comment]
Thanks @ophub ! 2 pull requests added:
https://github.com/ophub/u-boot/pull/8
https://github.com/ophub/amlogic-s9xxx-armbian/pull/1822

I will test the build after these pull requests merge

**Comment by araczkowski** [comment]
Hi @ophub I checked the builds and it works but only on X88 Pro Pro X3 box with 100MB Ethernet 
I have a second X88 Pro Pro X3 with a 1GB Ethernet and on this box booting from eMMC does not work

To be 100% sure I created u-boot again taking the ``bootloader.bin`` from the box with 1GB Ethernet and I tried many times unfortunately no success.

Is there any way to make it works, do you have any advice how I can start the Armbian from eMMC?
How it is possible that box is starting from SD card and pendrive but it is not able to start from eMMC, maybe there is a way do do this?

Thanks in advance for your comments!

**Comment by ophub** [comment]
When booting from an SD card, it uses the bootloader from the eMMC. However, when you write to the eMMC, using the "-m yes" parameter overwrites the Android bootloader with the mainline u-boot. Therefore, when booting from the eMMC again, it requires the correct mainline u-boot.

Can your box with the Gigabit Ethernet card boot using the unmodified original u-boot? If it can, you can modify the configuration to have two lines, one for the 100MB and one for the Gigabit Ethernet, making it easier to differentiate. Please provide photos of the appearance and bottom model codes of your two boxes to help distinguish them. If you have photos of the motherboard, including the short-circuit rescue point, please provide those as well. If you have the Android system firmware, please provide a download link for others to test.

**Comment by araczkowski** [comment]
Hi @ophub !

> When booting from an SD card, it uses the bootloader from the eMMC. However, when you write to the eMMC, using the "-m yes" parameter overwrites the Android bootloader with the mainline u-boot. Therefore, when booting from the eMMC again, it requires the correct mainline u-boot.

Thank you for the explanation - now it is clear :) 

> Can your box with the Gigabit Ethernet card boot using the unmodified original u-boot? 

No, unfortunately I can not boot from eMMC on 1GB Ethernet version, I tried all the possibilities - no success :(

> Please provide photos of the appearance and bottom model codes of your two boxes to help distinguish them. 

Please see the photos below, the only difference I can see is in the Ethernet part:

![100MB_vs_1GB](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/e90dada7-4d6a-4a84-af5d-1e9fb3491cdc)

### 1GB Top
![1G_top](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/9f4428d4-71a7-44ed-89da-7ad55f00a256)

### 1GB Bottom
![1G_bottom](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/9c5ad20f-3b08-4816-9beb-dd8a59bd1fb7)

### 100MB Top
![100MB_top](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/1382bd44-59d5-4af1-81ad-3c4ee0d95070)

### 100MB Bottom
![100MB_bottom](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1263968/6765337a-8269-46c8-b2fc-ea5d40f62c6c)


> If you have the Android system firmware, please provide a download link for others to test.
Below is the link to Android system for 1GB version

https://drive.google.com/file/d/1H-bRELInEf1hTpEEKZr0Bc55-h3GiLJF/view?usp=drive_link



@ophub please let me know if you have any idea how we can boot this 1GB from eMMC. Thanks!

**Comment by ophub** [comment]
The kernel of version 6.1.y requires a correct u-boot bootloader. If the emmc is not working, further testing and adjustment of the u-boot are necessary.

**Comment by nmocruz** [comment]
I have one of this but it seems like has fake ram and after playing around with this a bit I got it stuck on boot.
I still trying to understand if I can "unbrick", using android or any linux based distro.
I was able to boot from the usb (not the sd card port)
I am not sure how find the issue, but seems like something wrong with the emmc
![IMG20240122234319](https://github.com/ophub/amlogic-s9xxx-armbian/assets/944357/dd2611f7-8ab7-44bf-9116-227f34600228)

**Comment by nmocruz** [comment]
I am wondering if this is not caused by different hardware I think mine has a different label

![IMG20240123003900](https://github.com/ophub/amlogic-s9xxx-armbian/assets/944357/2a7cc249-81e0-4537-8357-11a00c90f256)

**Comment by nmocruz** [comment]
Is a bit a bit strange because there no bad sectors but low level format reports errors

**Comment by adamkoa** [comment]
Hi Guys,

I've got a similar board, where the labels are the same on the main PCB, but this DTB did not have a good ethernet&BLE driver or memory size for me. All the other parts are OK.

However, when I tried the sei610.dtb version, it started perfectly for eth0 and BLE as well, but the memory size is still just half of the total.
So I have remained on that dtb since I've spent a whole day playing with dts editing to get a working one based on this x88 version.
I think my eth chip is only a 100M version and not a 1Gb one ... sadly.

I've checked the memory chips as well, there are 8 pieces from K4B4G0446D HYH9 which seems real for the 4GB RAM.
I cannot figure out how to maximize the usage of all the mem chips. I have searched for ways to find config problems or anything limiting the RAM size but without any success.

When this issue is cleared I wish to move the system to the internal eMMC.
Have you got any idea for this RAM mismatch?

**Comment by neht-net** [comment]
> Hi Guys,
> 
> I've got a similar board, where the labels are the same on the main PCB, but this DTB did not have a good ethernet&BLE driver or memory size for me. All the other parts are OK.
> 
> However, when I tried the sei610.dtb version, it started perfectly for eth0 and BLE as well, but the memory size is still just half of the total. So I have remained on that dtb since I've spent a whole day playing with dts editing to get a working one based on this x88 version. I think my eth chip is only a 100M version and not a 1Gb one ... sadly.
> 
> I've checked the memory chips as well, there are 8 pieces from K4B4G0446D HYH9 which seems real for the 4GB RAM. I cannot figure out how to maximize the usage of all the mem chips. I have searched for ways to find config problems or anything limiting the RAM size but without any success.
> 
> When this issue is cleared I wish to move the system to the internal eMMC. Have you got any idea for this RAM mismatch?

Hi, did you find a solution for the RAM problem?

My box is a Transpeed X3 Plus, supposed 4GB+32GB as showed in Android. I have tried many DTBs in Armbian but it always shows 2GB. 
![Uploading IMG_0951.jpeg…]()
![IMG_0952](https://github.com/user-attachments/assets/ae783ad7-f4c9-40cf-95d0-a271aae00a7d)
![IMG_0953](https://github.com/user-attachments/assets/369e476c-4381-464c-8885-e47a69976ac7)
