### ISSUE TITLE
关于hdmi黑屏，修改dtb文件的建议

### ISSUE THREAD

**Issue by xiaodiao216** [ophub/amlogic-s9xxx-armbian#1622]
- SOC: [S095l3b]
 - Model [e900v21e]
 期待解决hdmi问题，请能者制作对应的dtb文件，或者提出修改dtb文件的方法步骤，更新至本项目readme文件中，毕竟机型太多，不好适配，授人以鱼不如授人以渔。
#1620

**Comment by xiaodiao216** [comment]
我自己来提供几个有帮助的信息好了
1.据说有用的e900v21e的dtb，对应的是p291那个包，我没下，没有测试，[这里](https://www.mydigit.cn/forum.php?mod=viewthread&tid=363509&highlight=p291)
2.大神教的提取dts的办法，[这里](https://www.znds.com/forum.php?mod=viewthread&tid=1199323&page=1)

**Comment by xiaodiao216** [comment]
我自己查了资料，解包出来两个dts文件，却不知道怎么修改，哪位大哥能修改的看下吧
一个是可用卡刷包中针对e900v21e的dts，此包是安卓刷机包中解析出来的
另一个是本项目中5.*版本的armbian中的s905l3b-e900v22e(此包可以成功引导u盘启动armbian，但是引导后黑屏，hdmi无输出)
1、安卓盒子卡刷包中的dts（可正常显示）
2、本armbian系统中的s905l3b-e900v22e.dts（属于本盒子在linux下的dts）

**Comment by xiaodiao216** [comment]
晚上又干了一会，用e900v22e的dtb启动armbian，黑屏，只能去看系统日志，找到/var/log/armbian-hardware-monitor.log
发现可疑行第260-263行.....
260 [    2.519819] meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d)
261 [    2.520187] meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops meson_dw_hdmi_ops): -19
262 [    2.520212] meson-drm d0100000.vpu: Couldn't bind all components
263 [    2.520445] meson-drm d0100000.vpu: adev bind failed: -19
869 [    0.000000] Unknown kernel command line parameters "voutmode=hdmi disablehpd=false overscan=100 sdrmode=auto", will be passed to user space.
1089 [    2.515892] meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d)
1090 [    2.516261] meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops meson_dw_hdmi_ops): -19
1091 [    2.516288] meson-drm d0100000.vpu: Couldn't bind all components
1092 [    2.516525] meson-drm d0100000.vpu: adev bind failed: -19
大神们快来搞下吧 我这外行都查到这份上了

**Comment by taskmemz** [comment]
应该是系统还未识别到HDMI适配器的原因
（只是根据错误提示来看的，我也是刚接触这个东西）


> 晚上又干了一会，用e900v22e的dtb启动armbian，黑屏，只能去看系统日志，找到/var/log/armbian-hardware-monitor.log 发现可疑行第260-263行..... 260 [ 2.519819] meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d) 261 [ 2.520187] meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops meson_dw_hdmi_ops): -19 262 [ 2.520212] meson-drm d0100000.vpu: Couldn't bind all components 263 [ 2.520445] meson-drm d0100000.vpu: adev bind failed: -19 869 [ 0.000000] Unknown kernel command line parameters "voutmode=hdmi disablehpd=false overscan=100 sdrmode=auto", will be passed to user space. 1089 [ 2.515892] meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d) 1090 [ 2.516261] meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops meson_dw_hdmi_ops): -19 1091 [ 2.516288] meson-drm d0100000.vpu: Couldn't bind all components 1092 [ 2.516525] meson-drm d0100000.vpu: adev bind failed: -19 大神们快来搞下吧 我这外行都查到这份上了

**Comment by Shrinft** [comment]
有没有可能是GPU Mali 450驱动的问题
