### ISSUE TITLE
Help！救命

### ISSUE THREAD

**Issue by hnewcity** [ophub/amlogic-s9xxx-armbian#163]
救命！章鱼星球，s912x，用的5.15内核版本。今天apt upgrade的时候好像升级了内核，重启打不开了，亮白灯。
Help, my Octopus Planet cannot boot after upgrade linux kernel by excuting apt upgrade. Kernel version is 5.15.
谢谢谢谢！ Thanks a lot！

**Comment by ophub** [comment]
```
sudo apt-get update
sudo apt-get -qq purge -y linux-image-current-meson64
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get --purge  autoremove -y
sudo apt-get autoclean -y
```

**Comment by hnewcity** [comment]
已经开不了机了🥹
