### ISSUE TITLE
能否出一个适配于rk3318处理器的armbian镜像

### ISSUE THREAD

**Issue by xiyang12345** [ophub/amlogic-s9xxx-armbian#1630]
我有一个外贸盒子h96max rk3318 想刷成armbian国内关于这个盒子的教程几乎找不到,在armbian官方论坛上倒有一个https://forum.armbian.com/topic/26978-csc-armbian-for-rk3318rk3328-tv-box-boards/
但是他的镜像有问题,会出现WiFi可以识别到但连接不上,虽然上面给出了解决办法,但他没说明具体怎么做，我弄了很久都没有弄好。
所以大佬能不能编译一个适用于这个盒子的armbian镜像
![IMG_20230819_171350](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89056379/ef0e4abb-e765-4597-9cd7-3736cc6b6cc8)
![IMG_20230819_171408](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89056379/a21ec2ad-e7a4-4ad7-9ca4-692b35f6eed9)
![IMG_20230818_072900](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89056379/240fae35-0782-4aea-962e-1d8be54708d2)
![IMG_20230819_172623](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89056379/9ed0f895-51cb-43f5-aa42-0c39eb60a6dc)
![IMG_20230819_172607](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89056379/e333bd71-2e7a-4356-98f5-ed3dee08ce09)

**Comment by ophub** [comment]
我添加的多是官方不支持的设备。官方有了你去问题区追问即可。
