### ISSUE TITLE
B860AV1.1T(nand)U盘/sd卡成功启动Armbian，但须手动配置RTL8189FTV

### ISSUE THREAD

**Issue by KewenCode** [ophub/amlogic-s9xxx-armbian#1631]
- 注意事项
```
1.  CPU:S905M2-B (CPU-Z下查看)
2. Mdel:B860AV2.1-A(B860AV2.1) (CPU-Z下查看)
3. 江苏电信定制版
4. NAND（EMMC应该不会烧录的这么麻烦＞﹏＜）
5. 使用[Armbian_x_amlogic_s905lb-r3300l_(你想要的系统)_5.x_server_(日期).img.gz] (不要使用6.1内核，后续说明)
```
- 烧录说明
 早期找的ROM都是1.1T同型号刷机包，但是即使有Root也无法从U盘/sd启动。后查阅资料发现S905M与S905L几乎近似，于是从魔百盒那边成功找到一个**已root**&**能刷进NAND**&**能U盘启动**刷机包(前后烧了二十几个包＞︿＜，这个包唯一缺点是缺少RTL8189FTV驱动)
找ROM建议先看看有没有支持网卡驱动
- Android说明
烧录好U盘/sd，进入安卓（因缺少RTL8189FTV驱动而无法上网的砖头）后安装SU&卡载，按相关教程插U盘/sd重启，成功读取U盘/sd即可进入Armbian，按相关教程进行后续设置
**！！注意！！** 如果拔掉U盘/sd就**无法进入**Android系统，Android爱好者慎入
- Armbian说明
如标题所述，Armbian的RTL8189FTV须手动配置，所以初次进入系统看到无WIFI不要惊讶，且RTL8189FTV驱动只在5.4/10/15内核中存在（非常奇特，上游只有[unifreq/linux-6.1.y](https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek)不存在8189驱动，我是刷入6.1后才发现）  更多说明可以看 #640 这个issue
关于手动加载8189FTV就很简单，输入`modprobe 8189fs`，
要开机启动的话可以参考[S905/S905X Armbian安装WiFi驱动8189ETV的解决方法](https://www.cnblogs.com/jzgw/p/S905_8189ETV_8189ES_wifi-config.html)，要注意[本项目开机启动文件位置不同](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#128-%E5%A6%82%E4%BD%95%E6%B7%BB%E5%8A%A0%E5%BC%80%E6%9C%BA%E5%90%AF%E5%8A%A8%E4%BB%BB%E5%8A%A1)

**Comment by ophub** [comment]
/etc/custom_service/start_service.sh


`modprobe 8189fs`

加到上面的文件里，开机自动执行

**Comment by taozi0001** [comment]
楼主你好，我需要远程技术服务，有偿，我的需要刷linux系统，如果无法恢复请邮件联系我：taozi141200@gmail.com

**Comment by haitian138** [comment]
楼主有[Armbian_x_amlogic_s905lb-r3300l_(你想要的系统)_5.x_server_(日期).img.gz] 的包吗？    我只看到ophub的6内核的包

**Comment by KewenCode** [comment]
不用太纠结内核版本是5还是6，除非新版本用不了才去找旧的内核版本

**Comment by haitian138** [comment]
但6内核的不是没有RTL8189FTV的驱动吗，我盒子的WiFi用不了哦，在网上也好像没发现有5内核的
