### ISSUE TITLE
Phicomm N1 斐讯N1 Armbian kernel 5.15.123 无法ssh连接

### ISSUE THREAD

**Issue by xie007** [ophub/amlogic-s9xxx-armbian#1632]
镜像文件是：Armbian_23.08.0_amlogic_s905d_bullseye_5.15.123_server_2023.08.01

在u盘启动可以ssh连接，安装至emmc时则无法连接，我本地连接机器后，连接网络重新安装ssh服务即可正常使用。应该是安装的那部分代码有bug，下面的图片可以做相关排查。

错误信息为：

```
ssh.service failed with result 'signal'
```

```
ssh segmentation fault
```

```
ssh.service code=killed signal=SEGV
```

![n1_ssh_01](https://github.com/ophub/amlogic-s9xxx-armbian/assets/945776/f65927d3-4124-43a1-8a93-d5f24e4dfe10)
![n1_ssh_02](https://github.com/ophub/amlogic-s9xxx-armbian/assets/945776/1de2aac4-21b2-4741-b245-0a2a164d6433)
![n1_ssh_03](https://github.com/ophub/amlogic-s9xxx-armbian/assets/945776/52049358-200f-48de-81c0-4cec6c658b14)

**Comment by ophub** [comment]
开机自检可忽略

**Comment by ophub** [comment]
我试了正常，可能是个例。在开机脚本里已经有重启ssh，我再测试下其他的

**Comment by hjc757** [comment]
22端口N个版本前就不行了，换个端口试试

**Comment by b111110110** [comment]
我的N1也是出现这个错误
刷的版本是 Armbian_23.08.0_amlogic_s905d_jammy_5.15.123_server_2023.08.01
