### ISSUE TITLE
why there is no documentation for how to install into microsd card and run? Can you pls add it?

### ISSUE THREAD

**Issue by audynamo** [ophub/amlogic-s9xxx-armbian#1633]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. X96 max plus]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
why there is no documentation for how to install into microsd card and run? Can you pls add it?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

look at 8

**Comment by audynamo** [comment]
I check both 8 and 12 section of the document, with no success, like this guy mentioned https://github.com/ophub/amlogic-s9xxx-armbian/issues/909#issuecomment-1653361601,  I can't boot into armbian

But I can flash coreElec image to microsd card and boot from it.

**Comment by 7Ji** [comment]
If you've booted CoreELEC or any distro based on it (e.g. EmuELEC), then you're locked to only able to boot any distro using CE's Android-like non-mainline booting scheme, and locked from booting any mainline distro (e.g. LibreELEC, Armbian, OpenWrt, etc).

You need to either reset the uboot env with the help of a UART connector within uboot itself, or reflash the stock Android image to do that.
