### ISSUE TITLE
> >实际验证 不一定要刷Android9.0  只是底包的问题

### ISSUE THREAD

**Issue by bailiangjin** [ophub/amlogic-s9xxx-armbian#1635]
> > 如题，实际验证 不一定要刷Android9.0  只是底包的问题，用这个链接里的Android底包 刷机后，再装armbian就可以连接有线网了
放上链接：https://cloud.189.cn/web/share?code=beuuQzyuQRru%EF%BC%88%E8%AE%BF%E9%97%AE%E7%A0%81%EF%BC%9Agih0%EF%BC%89 这链接中的 晶晨S905L-R3300L-V21C-创维Logo和动画-修正以往bug-线刷包-202008版(20200918190203).rar 线刷之后，再U盘启动 使用最新的armbian包，就可以正常连接有线网了，由于机器内部存储只有8g 所以没有写入EMMC，只是用的U盘启动模式，不过理论上写入EMMC应该也可以联网，用之前的Android底包，就是无论写入EMMC还是U盘启动都无法联网。
备注:
我的设备：天津联通的 创维E900V21D  晶晨S905L 芯片
Android底包：晶晨S905L-R3300L-V21C-创维Logo和动画-修正以往bug-线刷包-202008版(20200918190203).rar 
armbian 包：Armbian_23.08.0_amlogic_s905l_jammy_5.15.119_server_2023.07.01.img.gz（理论上最新的s905l对应的armbian包应该可以，可以自行试试）
> 
> 这个需要是先刷Android9的固件再刷ambian才能成功吗，我的创维E900V21C，芯片S905L，也是，U盘启动相应的armbian之后能正常运行，但就是连不了网，盒子本身的系统是Android4.4.2

按照@janko888的意思是的，我准备找Android9的固件试试，看可不可以成功

_Originally posted by @harck24 in https://github.com/ophub/amlogic-s9xxx-armbian/issues/1519#issuecomment-1620952548_

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/download/tools/android_tv_r3300l-v21c-s905l.tar.xz

多谢分享，我转载到了这里。
