### ISSUE TITLE
Kernel 5.15.x - USB not working with the bundled meson-gxl-s905l2-p281.dtb

### ISSUE THREAD

**Issue by deonvdw** [ophub/amlogic-s9xxx-armbian#164]
Tested with Armbian_22.05.0_Aml_s905w_focal_5.15.28_2022.03.13.0009.img and included DTBs:
* meson-gxl-s905l2-p281.dtb - no USB devices detected
* meson-gxl-s905w-p281.dtb - properly detects USB devices

I see meson-gxl-s905l2-p281.dtb remained the same between kernel 5.4x and 5.15.x images; however it seems there were some USB related kernel changes which requires a new DTB. (See changes to meson-gxl.dtsi)

**Comment by ophub** [comment]
The s905w boxs currently only support 5.4 kernels, Cannot use kernel version 5.10 and above
![Snip20220314_7](https://user-images.githubusercontent.com/68696949/158109462-a47ad034-838e-4bf3-a8dc-596bb2a2c609.png)
