### ISSUE TITLE
启动顺序问题

### ISSUE THREAD

**Issue by Metaphorme** [ophub/amlogic-s9xxx-armbian#1640]
**Device Information | 设备信息**
 - SOC: amlogic s905d
 - Model Phicomm-N1

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.36
 - Release: Lunar

**Describe the bug | 问题描述**
将系统安装进 emmc 后一切正常。
如果将移动硬盘接入任意一个 USB 口后重启，则 N1 会反复启动（可能在尝试从移动硬盘启动），只有将硬盘拔掉后才能正常启动。

请问大佬是否有解决方法？很担心突然断电又恢复后反复重启导致硬盘损坏。

辛苦您啦！

**Comment by ophub** [comment]
有U盘就从U盘启动，这是默认设置。我拔了就从会从emmc启动。

**Comment by ophub** [comment]
有U盘就从U盘启动，这是默认设置。我拔了就从会从emmc启动。

**Comment by Metaphorme** [comment]
请问大佬是否可以设置其中一个usb口有启动的功能，而另一个usb口仅作为外置存储使用呢？目前的情况不太敢让n1做nas，有一些不方便。

谢谢您的回复！

**Comment by ophub** [comment]
我不会弄。你想想怎么弄

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/amlogic/bootfs/boot.cmd


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/amlogic/bootfs/boot-emmc.cmd

**Comment by Metaphorme** [comment]
好的！谢谢您指明了方向。我仔细了解一下。
