### ISSUE TITLE
软件库请求添加shairport-sync

### ISSUE THREAD

**Issue by vikeylam** [ophub/amlogic-s9xxx-armbian#1645]
shairport-sync是一款能让armbian拥有苹果airplay2功能的软件。
软件在git上开源，请求添加至软件库。

**Comment by vikeylam** [comment]
https://github.com/mikebrady/shairport-sync

**Comment by ophub** [comment]
好的，我看了一下他们的快速入门教程，有docker版，我学习一下如何使用，调试好了添加到软件中心

**Comment by vikeylam** [comment]
恩山有大佬用armbian调试过程，链接如下：https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=8266097&highlight=shairport

> 好的，我看了一下他们的快速入门教程，有docker版，我学习一下如何使用，调试好了添加到软件中心

**Comment by vikeylam** [comment]
好像不需要docker版本，直接有ubuntu/linux

**Comment by vikeylam** [comment]
> 好的，我看了一下他们的快速入门教程，有docker版，我学习一下如何使用，调试好了添加到软件中心

我的问题现在是安装完成后，魔百和的机顶盒 av线 输出没声音。

**Comment by vikeylam** [comment]
> 好的，我看了一下他们的快速入门教程，有docker版，我学习一下如何使用，调试好了添加到软件中心

等待大佬调试，我的s905l3a盒子，怎么设置都没声音。 调试2天了555555

**Comment by ophub** [comment]
你使用的哪个内核版本，哪个发行版分支的系统？

**Comment by vikeylam** [comment]
> 你使用的哪个内核版本，哪个发行版分支的系统？

我用的是s905l3a - jammy - 5.4.252 ，应该是声卡的问题。 

ps：unt403a 无法安装6.x的系统

**Comment by vikeylam** [comment]
> 你使用的哪个内核版本，哪个发行版分支的系统？

要不大佬研究一下，找个喇叭。用s905的盒子的自带av线可以给音箱直接播放airplay音乐

**Comment by vikeylam** [comment]
> 你使用的哪个内核版本，哪个发行版分支的系统？

o大，s905魔百盒刷armbian后av线似乎没有有音频输出呀。
