### ISSUE TITLE
写入系统内存后apt update报错

### ISSUE THREAD

**Issue by hjc757** [ophub/amlogic-s9xxx-armbian#165]
用U盘启动更新不报错，写入机身内存apt update更新就报错，写入姿势不对吗？N1盒子905d

**Comment by ophub** [comment]
发下你的固件信息：`cat /etc/ophub-release`
发下你的错误信息

**Comment by hjc757** [comment]
> 发下你的固件信息：`cat /etc/ophub-release` 发下你的错误信息

前几天刷3号的固件也是我反馈apt update报错，今天专门测试了，U盘启动up正常写入就不行，反复几次都这样后恢复到以前的版本

**Comment by ophub** [comment]
好的
