### ISSUE TITLE
ALLWINNER H6无法从U盘启动

### ISSUE THREAD

**Issue by jiaotiliu** [ophub/amlogic-s9xxx-armbian#1651]
**Device Information | 设备信息**
 - SOC: [ALLWINNER H6]
 - Model [腾讯极光TV 1V]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.127]
 - Release:Armbian_23.08.0_allwinner_tanix-tx6_lunar_5.15.127_server_2023.08.19.img.gz

**Describe the bug | 问题描述**
这个电视盒子已经刷了Tanix-TX6的系统，将Tanix-TX6的armbian镜像刷入U盘后，无法从U盘启动，请知道如何从U盘启动。十分感谢。

**Comment by 13584452567** [comment]
H6 V200并不支持直接从U盘启动系统。
