### ISSUE TITLE
Deleting Network interfaces

### ISSUE THREAD

**Issue by wildy658** [ophub/amlogic-s9xxx-armbian#1657]
**Device Information | 设备信息**
 - SOC: s509x
 - Model: HG680P
 
**Armbian Version | 系统版本**
 - Kernel Version: 5.15.x
 - Release: bookworm

How do I delete network interfaces on s509x?
I only need eth0 and lo.
I've tried using 'ip link del' but it didn't work.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents
