### ISSUE TITLE
求教，CM311-1网卡重启或者时间长了就无法联网

### ISSUE THREAD

**Issue by xiao14116** [ophub/amlogic-s9xxx-armbian#1662]
Device Information | cm311-1
 - SOC: [e.g. S095l3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.123]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
O大，我记得之前就有坛友询问过关于CM311-1网卡出问题的事，还是这个问题。
具体表现就是，盒子刷了armbian以后，刚开始一段时间没有任何问题，但是不能关机，不能重启，一旦关机或者重启以后网卡就无法启动了，也无法联网，在路由器中根本看不到盒子的IP。
现在又有另外一个问题，那就是系统不关机运行时间长了以后，也会出现网卡卡死的现象，具体表现就是有IP，但是ssh不能连接，ping不通、面板打不开，总之就是网卡没有任何反应了。
关机重启以后就获取不到IP了。
我想办法把系统的日志导了出来，

[   20.168887] kernel: meson8b-dwmac c9410000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[   20.233661] kernel: meson8b-dwmac c9410000.ethernet eth0: PHY [0.e40908ff:08] driver [Meson GXL Internal PHY] (irq=49)
[   21.770474] kernel: meson8b-dwmac c9410000.ethernet eth0: No Safety Features support found
[   21.772447] kernel: meson8b-dwmac c9410000.ethernet eth0: PTP not supported by HW
[   21.779920] kernel: meson8b-dwmac c9410000.ethernet eth0: configuring for phy/rmii link mode

这就是关于网卡的部分，但是我是个小白，只能看出有一个not safety，一个PTP not supported by HW，百度了一圈也没弄明白是什么问题，请老大分析一下，看看到底是什么问题
ps:不管刷5.几的系统还是6.几的系统，这个问题一直都存在，实在是没办法了。

**Comment by linyecheng** [comment]
同问，我n1也是这个情况
