### ISSUE TITLE
M301A-ZN 兆能代工 无法使用有线网络 双USB+HDMI正常

### ISSUE THREAD

**Issue by coldpig6** [ophub/amlogic-s9xxx-armbian#1663]
**Device Information | 设备信息**
 - SOC: [S905L2]
 - Model [M301A-ZN]

**Armbian Version | 系统版本**
 - Kernel Version: [Armbian_23.08.0_amlogic_s905l2_bookworm_6.1.49_server_2023.08.28]
 - Release: [bookworm]

**Describe the bug | 问题描述**
无法使用有线网络
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

下面是我从ABD工具包里备份的dbt文件 
使用过meson-gxl-s905l2-ipbs9505.dtb和meson-gxl-s905l2-x7-5g.dtb都不能正常上网
[dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/12468617/dtb.zip)

**Comment by coldpig6** [comment]
![IMG_20230830_015734](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105619398/8b74d29c-0568-423a-9dc5-90b690d60a77)
![IMG_20230830_015801](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105619398/b6f7dc5f-485f-40f9-ba36-9f51d8a852ba)
![IMG_20230830_015809](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105619398/5103033c-2638-45cb-bffb-39d9d14dc7ad)
![IMG_20230830_015711](https://github.com/ophub/amlogic-s9xxx-armbian/assets/105619398/4ac592a1-dac7-4f70-a657-df5745ba70dc)

**Comment by coldpig6** [comment]
另外没有找到可用的安卓9刷机包 这是我目前在用的刷机包
https://pan.baidu.com/s/1RThbu-n2DI8yYdfTH39h7w 提取码：uqq6

**Comment by coldpig6** [comment]
刷了大佬的mgv2000固件 已经正常使用网络 果然和安卓的系统有关系

**Comment by coldpig6** [comment]
不过还是无法写入emmc

**Comment by ophub** [comment]
降频

**Comment by coldpig6** [comment]
> 降频

 我看主板上标识nand 是否本来就不可刷入emmc使用只能U盘使用？

**Comment by ophub** [comment]
nand不能写入
