### ISSUE TITLE
About using kernel 6.1 and Home Assistant

### ISSUE THREAD

**Issue by ngocdungvn** [ophub/amlogic-s9xxx-armbian#1664]
**Device Information | 设备信息**
 - SOC: S905x3
 - Model N5 Max
 - Armbian_bookworm_save_2023.08

I use N5 Max X3 and have 2 problems:
1. I cannot install any version other than kernel version 5.15
2. I installed Home Assistant Supervised but the system only supports the original Debian 12. Is there a way to make the system Debian 12 (no derivatives) and not Armbian 23.08.0-trunk.
----------------------
Thanks dev team

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_bookworm_save_2023.08

**Comment by ngocdungvn** [comment]
> * Armbian_bookworm_save_2023.08

I'm using Armbian_bookworm_save_2023.08 kernel 5.15 and can't install kernel 6.1. Furthermore, I can't install Home Assistant Supervised. Help me.
https://community.home-assistant.io/t/installing-home-assistant-supervised-using-debian-12/200253

**Comment by ophub** [comment]
With the last version of bookworm, 6.1.y can be installed

**Comment by ngocdungvn** [comment]
> With the last version of bookworm, 6.1.y can be installed

How to handle the problem of the system being identified as Debian 12 (no derivatives)?

**Comment by ophub** [comment]
bookworm is debian12

**Comment by araczkowski** [comment]
rin this in console:


sed -i 's#PRETTY_NAME=.*#PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"#'  /etc/os-release

**Comment by ngocdungvn** [comment]
> run this in console:
> 
> sed -i 's#PRETTY_NAME=.*#PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"#' /etc/os-release

Thank you, my problem 2 has been solved

**Comment by ngocdungvn** [comment]
> With the last version of bookworm, 6.1.y can be installed

Thank you, Armbian_23.08.0_amlogic_s905x3_bookworm_6.1.49_server_2023.08.28.img has been installed successfully

**Comment by thevinhnbvn35** [comment]
> > With the last version of bookworm, 6.1.y can be installed
> 
> Thank you, Armbian_23.08.0_amlogic_s905x3_bookworm_6.1.49_server_2023.08.28.img has been installed successfully

Bác cho e hỏi bác dùng cấu hình nào để install vào emmc thế. E boot bằng usb được rồi mà muốn cài vào emmc không biết là chọn thiết bị nào trong armbian-install
