### ISSUE TITLE
can i change boot splash screen??

### ISSUE THREAD

**Issue by BBUBBA** [ophub/amlogic-s9xxx-armbian#1668]
Device Information | 设备信息
 - SOC: S905w
 - Model [ x96w ]

Armbian Version | 系统版本
 - Kernel Version: 5.15.127
 - Release: Lurnar

Hello!! Thanks, ophub team !!

i hope change boot splash screen on my device..

I think the android device logo was left when armbian was installed in the previous version.
At some point, the logo seems to be deleted when armbian is installed.

https://github.com/ophub/amlogic-s9xxx-armbian/issues/404

Can i Keep the Android boot splash screen or Can I change Ambian's boot screen?

i tryied change by plymouth theme. but.. not work.. T_T

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/17864839/9dcf6cab-860d-450b-a9bc-65b8c5030677)

I tried changing plymouth after seeing this document, but it didn't work.
https://github.com/adi1090x/plymouth-themes

"sudo update-intramfs -u" command tell me "Not updating intramfs"

Thank you very much for your reply.

**Comment by ophub** [comment]
I don't understand the software you mentioned
