### ISSUE TITLE
ROOTFS分区如何改称ext4的？

### ISSUE THREAD

**Issue by zyworkshop** [ophub/amlogic-s9xxx-armbian#167]
刷在u盘上，数码视讯Q7开机启动时，报错，fail to mount /dev/sda2。我估计是btrfsw文件系统的原因，我把ROOTFS分区格式化成ext4,再把文件拷贝回来，能启动了。我想问问，在代码中改动那些内容，让它编译时ROOTFS生成ext4格式的？本人小白，见笑了。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/c5108a9e08a221ee0d2bbf57aad975c1ace0132e
