### ISSUE TITLE
江苏M401A不能u盘启动

### ISSUE THREAD

**Issue by l666l** [ophub/amlogic-s9xxx-armbian#1670]
**Device Information | 设备信息**江苏M401A
 - SOC: [e.g. S095l3a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.127]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
m401a不能u盘启动，每次都是跳转Recovery界面

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by l666l** [comment]
各位大佬，这个该咋办

**Comment by ophub** [comment]
看文档的方法

**Comment by l666l** [comment]
> 看文档的方法

Armbian Build and Usage Guide
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents
这个文档嘛

**Comment by Doboo** [comment]
1、改默认的dtb为m401a
2、换U盘
两种方法配合着试试

**Comment by l666l** [comment]
> 1、改默认的dtb为m401a 2、换U盘 两种方法配合着试试

这两种方法都单独试过，也结合起来试过，不知道为啥就是不能u盘启动，要说盒子本来就不能刷armbian的话，它刚拿回来又能刷armbian，刷了之后连有线不能发现ip，后面线刷回电视盒子系统(已root)，但是就是不能从u盘启动，要不就是到那个恢复界面，要不就是进入了tv界面，我人麻了

**Comment by l666l** [comment]
> 1、改默认的dtb为m401a 2、换U盘 两种方法配合着试试

这两种方法都单独试过，也结合起来试过，不知道为啥就是不能u盘启动，要说盒子本来就不能刷armbian的话，它刚拿回来又能刷armbian，刷了之后连有线不能发现ip，后面线刷回电视盒子系统(已root)，但是就是不能从u盘启动，要不就是到那个恢复界面，要不就是进入了tv界面，我人麻了

**Comment by klcb2010** [comment]
> > 1、改默认的dtb为m401a 2、换U盘 两种方法配合着试试
> 
> 这两种方法都单独试过，也结合起来试过，不知道为啥就是不能u盘启动，要说盒子本来就不能刷armbian的话，它刚拿回来又能刷armbian，刷了之后连有线不能发现ip，后面线刷回电视盒子系统(已root)，但是就是不能从u盘启动，要不就是到那个恢复界面，要不就是进入了tv界面，我人麻了
用远离网口那个USB接口U盘往下压这开机

**Comment by l666l** [comment]
> > > 1、改默认的dtb为m401a 2、换U盘 两种方法配合着试试
> > 
> > 
> > 这两种方法都单独试过，也结合起来试过，不知道为啥就是不能u盘启动，要说盒子本来就不能刷armbian的话，它刚拿回来又能刷armbian，刷了之后连有线不能发现ip，后面线刷回电视盒子系统(已root)，但是就是不能从u盘启动，要不就是到那个恢复界面，要不就是进入了tv界面，我人麻了
> > 用远离网口那个USB接口U盘往下压这开机

那个口也插过，但是也不太行，麻了麻了

**Comment by SoraKasvgano** [comment]
重刷安卓固件，换bootloader，具体哪个固件找不到了，你去搜一下多试试吧。

**Comment by janko888** [comment]
> > 1、改默认的dtb为m401a 2、换U盘 两种方法配合着试试
> 
> 这两种方法都单独试过，也结合起来试过，不知道为啥就是不能u盘启动，要说盒子本来就不能刷armbian的话，它刚拿回来又能刷armbian，刷了之后连有线不能发现ip，后面线刷回电视盒子系统(已root)，但是就是不能从u盘启动，要不就是到那个恢复界面，要不就是进入了tv界面，我人麻了

看看你root的安卓系统里面识别的内存是1G还是2G?

**Comment by l666l** [comment]
> > > 1、改默认的dtb为m401a 2、换U盘 两种方法配合着试试
> > 
> > 
> > 这两种方法都单独试过，也结合起来试过，不知道为啥就是不能u盘启动，要说盒子本来就不能刷armbian的话，它刚拿回来又能刷armbian，刷了之后连有线不能发现ip，后面线刷回电视盒子系统(已root)，但是就是不能从u盘启动，要不就是到那个恢复界面，要不就是进入了tv界面，我人麻了
> 
> 看看你root的安卓系统里面识别的内存是1G还是2G?

显示2G

**Comment by l666l** [comment]
> 重刷安卓固件，换bootloader，具体哪个固件找不到了，你去搜一下多试试吧。

安卓固件换过多个了，然后那个bt的话，那个armbian带的那些基本都试过，还是不太行，大佬们，指条明路

**Comment by sitaoo** [comment]
**使用下面的方法，实测可用**
1. 电脑安装 adb（chocolatey：`choco install adb -y`）
2. adb connect 192. ×. ×. ×: 5555
3. adb shell
4. ls /dev/block/env #非必要步骤
5. cat /dev/block/env #非必须步骤
6. dd if=/dev/zero of=/dev/block/env #清空变量
7. reboot update
8. 然后接入 USB 镜像就可以正常启动

来源：https://www.bilibili.com/video/BV1LG411L7Us

**补充：**
如果无法开启 adb 调试，建议重新线刷一个开启 adb 的包，下载地址
链接: https://pan.baidu.com/s/1I38L8c5hKFN28JvKA3Vy3g
提取码: tph5 

我使用的是：/刷机固件ROM大全/A《当贝纯净桌面--固件大全》（固件更全）/1《魔百盒(CM／M)固件合集》/《M401A》/【江苏版M401A-注意事项】
另，不要将镜像安装到 emmc 中，实测会无法开机。直接使用 usb 启动就可以了（也可能是我机器问题，魔百盒M401A 2+8 GB）

**Comment by sitaoo** [comment]
> **使用下面的方法，实测可用**
> 
> 1. 电脑安装 adb（chocolatey：`choco install adb -y`）
> 2. adb connect 192. ×. ×. ×: 5555
> 3. adb shell
> 4. ls /dev/block/env #非必要步骤
> 5. cat /dev/block/env #非必须步骤
> 6. dd if=/dev/zero of=/dev/block/env #清空变量
> 7. reboot update
> 8. 然后接入 USB 镜像就可以正常启动
> 
> 来源：https://www.bilibili.com/video/BV1LG411L7Us
> 
> **补充：** 如果无法开启 adb 调试，建议重新线刷一个开启 adb 的包，下载地址 链接: https://pan.baidu.com/s/1I38L8c5hKFN28JvKA3Vy3g 提取码: tph5
> 
> 我使用的是：/刷机固件ROM大全/A《当贝纯净桌面--固件大全》（固件更全）/1《魔百盒(CM／M)固件合集》/《M401A》/【江苏版M401A-注意事项】 另，不要将镜像安装到 emmc 中，实测会无法开机。直接使用 usb 启动就可以了（也可能是我机器问题，魔百盒M401A 2+8 GB）
