### ISSUE TITLE
Armbian_jammy_save_2023.09使用pppoe无法获取IPV6，运营商支持ipv6

### ISSUE THREAD

**Issue by mengzai-c** [ophub/amlogic-s9xxx-armbian#1672]
前面第一次获取时成功了，但是重启后再也没有IPV6地址了，这是怎么回事，是配置的不对吗
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/140877268/3e1de6b1-5455-492d-bd5f-13ce92f8ce87)

**Comment by mengzai-c** [comment]
还有路由器使用有状态IPv6时也存在此问题，只有一次以后都没有IPv6,但无状态是可以的

**Comment by mengzai-c** [comment]
用了这个https://www.cnblogs.com/dereen/p/ubuntu_ipv6.html成功了

**Comment by youcanfind** [comment]
> 我遇到了PPPoE无法获取IPv6的问题，现在把解决方法给大家讲一下

请问你在armbian是如何通过PPPoE拨号的？我将机顶盒桥接光猫，使用pppoeconf命令无法拨号成功，而相同的命令在x86的ubuntu中是没有问题的。
