### ISSUE TITLE
Naming convention (enhancement)

### ISSUE THREAD

**Issue by osering** [ophub/amlogic-s9xxx-armbian#1673]
Hello!
There is a suggestion for changing naming convention of files.
Instead of using debian/ubuntu version names like bullseye/jammy, use version numbers like debian11 / ubuntu2204.
for example:
Armbian_23.08.0_amlogic_s905x3_debian11_6.1.50_server_2023.09.02.img.gz
Armbian_23.08.0_amlogic_s905x3_ubuntu2204_6.1.50_server_2023.09.02.img.gz

P.S. Thanks for great initiative to revive armbian on amlogic tvboxes!

**Comment by ophub** [comment]
We generally use version codes to represent
