### ISSUE TITLE
申请添加支持小宝NAS(RK3399)

### ISSUE THREAD

**Issue by ErixWong** [ophub/amlogic-s9xxx-armbian#1674]
**官网：**
https://www.codinge.cn/

**参考：**
https://github.com/Lollipop907/XiaoBaoNASv1_Firmware

**硬件：**
CPU: RK3399
RAM: 4G
EMMC: 16G

**其他：**
5 X SATA
1 X USB 2.0
1 X USB 3.0
1 X Type-C
1 X TF

谢谢

**Comment by ErixWong** [comment]
![e441b5af31c63d6353812911cd3b83f](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/6635a9f0-a1df-48bd-a247-603d34862622)
![a2fc038c351743e3c7566e03a8907b5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/d8a9dee2-1bee-45f2-aecf-da5d6b480cd6)

**Comment by ErixWong** [comment]
目前能用的armbian镜像如下：
https://file.erix.vip/f/76ff3f32b89941f78482/?dl=1
密码：xiaobaoNas

谢谢。

**Comment by ophub** [comment]
13584452567 已经添加了，反馈一下测试情况。

**Comment by ErixWong** [comment]
Release里还没有看到，是要等编译吗？

**Comment by ErixWong** [comment]
感谢各位的努力，系统运行良好。
目前发现的问题：
SATA-PCIe Bridge Controller JMB585没驱动起来，硬盘没挂上来。

附上demsg一份。
[dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12568400/dmesg.log)

**Comment by 13584452567** [comment]
> 感谢各位的努力，系统运行良好。
> 目前发现的问题：
> SATA-PCIe Bridge Controller JMB585没驱动起来，硬盘没挂上来。
> 
> 附上dmesg一份。
> [dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12568400/dmesg.log)
> 
> 
> 

你发我的那份armbian固件，jmb585工作正常吗

**Comment by ErixWong** [comment]
> 

之前提供的固件，硬盘工作正常的，应该用的是nano pc4的吧

**Comment by 13584452567** [comment]
可以卡启你发的那份固件，然后运行lsmod和dmesg看一下吗？
我上传仓库的用的就是你那份镜像的dtb文件。

**Comment by ErixWong** [comment]
> 可以卡启你发的那份固件，然后运行lsmod和dmesg看一下吗？ 我上传仓库的用的就是你那份镜像的dtb文件。
[dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12575597/dmesg.log)
[lsmod.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12575598/lsmod.log)

麻烦再看看，谢谢。

**Comment by 13584452567** [comment]
> > 可以卡启你发的那份固件，然后运行lsmod和dmesg看一下吗？ 我上传仓库的用的就是你那份镜像的dtb文件。
> 
> [dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12575597/dmesg.log)
> [lsmod.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12575598/lsmod.log)
> 
> 麻烦再看看，谢谢。

看日志，pcie正常驱动了，但是没能链接到jmb585。可以在ophub的镜像下运行一次modprobe ahci看下dmesg日志吗？最好再运行一次lspci。

**Comment by ErixWong** [comment]
两条命令运行了没有输出。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/2b248107-85f3-48a0-a920-c7cd5d4be478)
dmesg
[dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12587240/dmesg.log)

**Comment by ErixWong** [comment]
这是正常的：
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/d89f1172-f838-4f17-9b9a-6d0162a0294d)

**Comment by 13584452567** [comment]
试一试更换5.15内核？

**Comment by cj1324** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/22e8a318-5eb7-4fd7-b7c8-6a2656b132e3)

情况类似，无法驱动 jmb585 设备。

**Comment by 13584452567** [comment]
尝试使用这个内核https://github.com/13584452567/amlogic-s9xxx-armbian/releases/download/kernel_stable/6.1.53.tar.gz

**Comment by cj1324** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/2c614db1-accc-4a20-b9ba-4005f64b67e7)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/cab6f8b3-690a-429d-82f0-3138ee5ee7cc)

看样子，应该是可以得。

**Comment by akwangl** [comment]
hisense hs530r这个有大佬做适配么目前只有安卓系统

**Comment by 13584452567** [comment]
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/2c614db1-accc-4a20-b9ba-4005f64b67e7)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/cab6f8b3-690a-429d-82f0-3138ee5ee7cc)
> 
> 
> 
> 看样子，应该是可以得。

我这就推送新的内核配置

**Comment by ErixWong** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/0b4b6354-6629-4659-bba2-ba6e13ab30f0)
我刷了最新的内核，也换到了5.15，但是都不行。需要重新下载固件刷吗？

**Comment by ophub** [comment]
仓库的固件10天更新一个版本，现在还是之前的，你手动更新内核，先更新上一个版本，再更新最新版本就替换成最新内核了。

**Comment by ErixWong** [comment]
谢谢回复。

是的我知道如何更新内核，但还是无法驱动sata。
我刚刚重新更新到6.1.53，一样的结果。

**Comment by ErixWong** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/b3e2f4ce-4e03-4187-899e-a8506be70405)

**Comment by ophub** [comment]
你装楼上的试试

**Comment by phcl1998** [comment]
> 你装楼上的试试

![屏幕截图 2023-09-20 171453](https://github.com/ophub/amlogic-s9xxx-armbian/assets/125857645/b41afad8-94eb-4e7f-ad09-7334097df615)
我试了，还是不行

**Comment by gzxief** [comment]
我下载新固件，也不行，SATA不起来

**Comment by phcl1998** [comment]
> 我下载新固件，也不行，SATA不起来

放弃吧！用上面内核6.1.11的可以

**Comment by gzxief** [comment]
> ![图像](https://user-images.githubusercontent.com/489649/268455248-2c614db1-accc-4a20-b9ba-4005f64b67e7.png) ![图像](https://user-images.githubusercontent.com/489649/268455301-cab6f8b3-690a-429d-82f0-3138ee5ee7cc.png)
> 
> 看样子，应该是可以得。

你好，你分享一下你这个固件img文件吗，谢谢

**Comment by HaleyLou** [comment]
> 可以卡启你发的那份固件，然后运行lsmod和dmesg看一下吗？ 我上传仓库的用的就是你那份镜像的dtb文件。

我也是同样无法连接到JMB585,小宝官方有自己dtb文件，可以参考官方的DTB测试下吗？

**Comment by cj1324** [comment]
> > ![图像](https://user-images.githubusercontent.com/489649/268455248-2c614db1-accc-4a20-b9ba-4005f64b67e7.png) ![图像](https://user-images.githubusercontent.com/489649/268455301-cab6f8b3-690a-429d-82f0-3138ee5ee7cc.png)
> > 看样子，应该是可以得。
> 
> 你好，你分享一下你这个固件img文件吗，谢谢

提供您的邮箱或者联系我的邮箱 chen1324@gmail.com

**Comment by HaleyLou** [comment]
经测试，使用5.4.258的内核可以识别到pci通道，但依然有问题，caso的 本地存储服务启动不了

**Comment by phcl1998** [comment]
> 经测试，使用5.4.258的内核可以识别到pci通道，但依然有问题，caso的 本地存储服务启动不了
5.4内核手动挂载硬盘可以不？

**Comment by HaleyLou** [comment]
经过测试是可以手动挂载硬盘的。
重新说明下现在发现的问题，使用poweroff 命令会直接退出终端的访问，但设备并不会关机。
CasaOS 重新安装，会提示“Job for casaos-local-storage.service failed because a timeout was exceeded.”
相关日志中会有“/dev/zram0: Unable to detect d 等反馈

**Comment by HaleyLou** [comment]
CasaOS详细的错误日志如图
![屏幕截图 2023-10-19 222707](https://github.com/ophub/amlogic-s9xxx-armbian/assets/108428253/1653bf56-2ae9-44c8-b9d5-0b527e715c70)

**Comment by gzxief** [comment]
大神们，你们加油，小宝NAS就靠你们了
