### ISSUE TITLE
申请添加支持mecool BB2盒子

### ISSUE THREAD

**Issue by cardcaptor2003** [ophub/amlogic-s9xxx-armbian#1676]
CPU Amlogic S912 64 bit Octa core ARM Cortex-A53
RAM 2G   eMMC 16G
GPU:ARM Mali-T820MP3 GPU up to 750MHz (DVFS)
LAN:1000M   WIFI:802.11ac

**Comment by ErixWong** [comment]
![a2fc038c351743e3c7566e03a8907b5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/0293b5d2-4b04-452b-8b54-304b929254e8)
![e441b5af31c63d6353812911cd3b83f](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6867853/b5636a55-7714-4b55-b6b3-179095fe73d9)
