### ISSUE TITLE
Armbian-install script I think I found a BUG

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#168]
**My box tv x96 max +**

I've been analyzing your armbian-install script I think I found a BUG.

echo "Formatting ROOTFS partition..."
mkfs.btrfs -f -U ${ROOTFS_UUID} -L "ROOTFS_EMMC" -m single ${PART_ROOT}

this partition is not being created
see the img
![Sem Título](https://user-images.githubusercontent.com/83761813/158268992-32a729f3-d90a-44ec-a27d-e107fdb1bd53.png)

**where is the ROOTFS_EMMC partition?? with the ROOTFS_UUID created????**

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/2a80924b4d119b0b7c96a419e7416d2528f99ecb/build-armbian/common-files/files/usr/sbin/armbian-install#L371


When writing to emmc, the mount will be unmounted after the file has been copied. You remove the usb, plug it back in, and the system will boot from emmc.
