### ISSUE TITLE
我家云可以引导启动了

### ISSUE THREAD

**Issue by liubin7913** [ophub/amlogic-s9xxx-armbian#1680]
最新的Armbian_23.08.0_rockchip_l1pro_bookworm_6.1.50_server_2023.09.02.img或Armbian_23.08.0_rockchip_l1pro_bullseye_6.1.50_server_2023.09.02.img，刷u盘还是写emmc，还是不能引导

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.09/Armbian_23.08.0_rockchip_l1pro_jammy_6.1.51_server_2023.09.05.img.gz


你下载我刚刚弄的这个试试

**Comment by liubin7913** [comment]
刚刚测试依旧无法引导启动

**Comment by aaa7260** [comment]
同样的问题，屏幕不显示，换loader也不行

**Comment by ophub** [comment]
路由器里能找到启动的IP吗？ssh能访问吗？

**Comment by aaa7260** [comment]
路由器可以看到ip，ssh连接不上，wind网盘：https://cloud.189.cn/web/share?code=vA736bn2EfEb，密码3997

**Comment by ophub** [comment]
Armbian_22.05.0-trunk_Chainedbox-wind_buster_current_5.15.32
你是说这个文件可以正常使用？网络和HDMI都正常？

**Comment by aaa7260** [comment]
是的，大佬

**Comment by ophub** [comment]
好的，10分钟后给你出一个试试，使用这个固件的u-boot和dtb

**Comment by aaa7260** [comment]
谢谢大佬，我觉得你的dtb好些

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.09/Armbian_23.08.0_rockchip_chainedbox_bullseye_5.15.131_server_2023.09.08.img.gz

你下载这个测试下，看看能不能正常使用，这个的dtb和u-boot都是复制的你发的固件的。
如果可以，你再试试改dtb为之前的，修改/boot/armbianEnv.txt 文件，修改里面dtb的文件名为：rk3328-l1pro-1296mhz.dtb。保存重启看看能不能用：

**Comment by aaa7260** [comment]
感谢大佬，你太敬业了，这个版本可以上了

**Comment by ophub** [comment]
你替换了dtb试了没？默认这个是没法维护的dtb，原来固件里的，你修改 /boot/armbianEnv.txt 文件，修改里面dtb的文件名为：rk3328-l1pro-1296mhz.dtb。保存重启看看能不能用。

把ssh进去的界面接个图，把这个命令(`cat /etc/ophub-release`)看到的结果也截个图，很久没看到这个设备能上线了

**Comment by aaa7260** [comment]
<img width="490" alt="截屏2023-09-09 下午12 55 39" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/62923926/22295545-e0e6-4557-b5a4-8738898a19d6">

**Comment by ophub** [comment]
https://bbs.nas66.com/thread-5554-1-1.html

我网上搜下了，上面固件使用的wind可能是这个帖子的作者（如果错了请随时更正）。我把他也添加到贡献者名单里了，感谢这些大佬们的分享。

**Comment by s2031215** [comment]
感謝大佬，吃灰了很久的我家云終於可以用了
原本rk3328-chainedbox.dtb風扇是不會轉和燈是保持紅色
修改rk3328-l1pro-1296mhz.dtb之後風扇會自己轉和燈會轉紫色
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/9303647/433e5da8-ccf7-407d-b965-8e321f4681be)

**Comment by ophub** [comment]
好的，多谢反馈，我改一下dtb

**Comment by liubin7913** [comment]
刷最新Armbian_23.08.0_rockchip_chainedbox_bullseye_6.1.52_server_2023.09.12.img，前面板电源按钮能关机，不能开机，需要拔电源重插

**Comment by ophub** [comment]
![Snip20231028_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/13aab016-1b93-4ff1-b1ef-c202bd357068)
![20231028163141](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/a6d2d8c0-35c5-44ba-be35-fd2e2758729b)
![Snip20231028_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/453c3665-4ef6-4afc-ad17-c6b8b6434a1d)

**Comment by laoskido** [comment]
> Thanks to the boss, my cloud that has been in the dust for a long time can finally be used. Originally, the fan of rk3328-chainedbox.dtb would not turn and the light would remain red. After modifying rk3328-l1pro-1296mhz.dtb, the fan will turn on its own and the light will turn purple. ![image](https://user-images.githubusercontent.com/9303647/267064745-433e5da8-ccf7-407d-b965-8e321f4681be.png)

What is the Write speed of your device ? mine, when start copying from PC to NAS, from 56MB/s and then it fluctuates down to 36-4X MB/s . Both LAN and Router are 1G ethernet speed. 

I bought the USB to Sata cable ( JSM578) , plugged into the back Usb 3.0 port, speed still the same. around 40-50MB/s

I have 2 L1 to test. One of them messed up preety bad when i tried to mod the usb sata. 
The other L1  is still in its original shape.

**Comment by laoskido** [comment]
> Okay, thanks for the feedback, I will change the dtb

Thanks for the great work , boss.

I have a question, when i use the rk3328_v1.14.249.bin , the L1 wont boot.

If i use the old rk3328_loader.bin , it boots and works fine with your imgage.

Rockchip tooltox i use the newest version, same as yours.

**Comment by ophub** [comment]
Use what you can launch

**Comment by gu952324924** [comment]
大佬您有相关学习群吗

**Comment by iamchenghao** [comment]
镜像不能下载了，在哪里可以下载

**Comment by CoolLeiVip** [comment]
现在我家云刷飞牛后会掉盘么

**Comment by maysucn** [comment]
> 现在我家云刷飞牛后会掉盘么

哎。还是会掉盘。。。

**Comment by 19952180218** [comment]
大佬，这个我家云的fnos去哪里下载？

**Comment by maysucn** [comment]
https://github.com/ophub/fnnas/releases

这里

**Comment by 2818456988-lab** [comment]
大佬有没有openwrt的包

**Comment by 2818456988-lab** [comment]
我家云l1pro的

**Comment by sunshunkai** [comment]
我家云不是应该刷瑞芯微的镜像吗？我刷了之后没反应，网口指示灯也不了亮，不知道咋回事
