### ISSUE TITLE
关于T95Z max无法识别eMMC

### ISSUE THREAD

**Issue by mipf2009** [ophub/amlogic-s9xxx-armbian#1682]
**Device Information | 设备信息**
 - SOC:  S912
 - Model : T95Z max
**Armbian Version | 系统版本**
 - Kernel Version: 2023-08发布的5.15  5.4  6.4
 - Release: jammy/bullseye

**Describe the bug | 问题描述**
T95Z max 与 T95Z-Plus 硬件配置类似，我的是3g+32g版本，千兆网口，支持双频wifi，安卓固件max可以完美使用Plus固件，但在armbian系统，使用T95Z-Plus.dtb或gxm-q201.dtb 时，U盘、TF卡均能正常启动，且wifi等运行完美，但使用armbian-install安装到eMMC时提示“ Internal eMMC storage was't found in this device!” 找不到eMMC，使用  echo "https://7ji.github.io/ampart-web-reporter/?dsnapshot=$(ampart /dev/mmcblk2 --mode dsnapshot 2>/dev/null | head -n 1)&esnapshot=$(ampart /dev/mmcblk2 --mode esnapshot 2>/dev/null | head -n 1)"  返回“ https://7ji.github.io/ampart-web-reporter/?dsnapshot=&esnapshot=”，空值无结果。肯请大佬帮助。
<img width="925" alt="014b8cdf1f2e73ea6697e4e0edede49" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/62308153/0eb1612e-d4c0-4a40-98e5-5ae19672585b">
![4c56a1a2861b351474988c26ab1e797](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62308153/50b3929c-6b4f-4e0c-b98a-0c1249a92d24)
![79e3f0948fd7cb9b5cec44fa88df3a4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62308153/68a14141-b058-406e-8470-6559d45bdc0d)

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ShadowWangsj** [comment]
> **Device Information | 设备信息**
> 
> * SOC:  S912
> * Model : T95Z max
>   **Armbian Version | 系统版本**
> * Kernel Version: 2023-08发布的5.15  5.4  6.4
> * Release: jammy/bullseye
> 
> **Describe the bug | 问题描述** T95Z max 与 T95Z-Plus 硬件配置类似，我的是3g+32g版本，千兆网口，支持双频wifi，安卓固件max可以完美使用Plus固件，但在armbian系统，使用T95Z-Plus.dtb或gxm-q201.dtb 时，U盘、TF卡均能正常启动，且wifi等运行完美，但使用armbian-install安装到eMMC时提示“ Internal eMMC storage was't found in this device!” 找不到eMMC，使用 echo "https://7ji.github.io/ampart-web-reporter/?dsnapshot=$(ampart /dev/mmcblk2 --mode dsnapshot 2>/dev/null | head -n 1)&esnapshot=$(ampart /dev/mmcblk2 --mode esnapshot 2>/dev/null | head -n 1)" 返回“ [https://7ji.github.io/ampart-web-reporter/?dsnapshot=&esnapshot=”，空值无结果。肯请大佬帮助。](https://7ji.github.io/ampart-web-reporter/?dsnapshot=&esnapshot=%E2%80%9D%EF%BC%8C%E7%A9%BA%E5%80%BC%E6%97%A0%E7%BB%93%E6%9E%9C%E3%80%82%E8%82%AF%E8%AF%B7%E5%A4%A7%E4%BD%AC%E5%B8%AE%E5%8A%A9%E3%80%82) <img alt="014b8cdf1f2e73ea6697e4e0edede49" width="925" src="https://private-user-images.githubusercontent.com/62308153/265696355-0eb1612e-d4c0-4a40-98e5-5ae19672585b.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NzU5MjE3MzYsIm5iZiI6MTc3NTkyMTQzNiwicGF0aCI6Ii82MjMwODE1My8yNjU2OTYzNTUtMGViMTYxMmUtZDRjMC00YTQwLTk4ZTUtNWFlMTk2NzI1ODViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNjA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjYwNDExVDE1MzAzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5MzViYjE4YTU1M2EwOTIzNzBiODNmZGFhNTI1NDM1MjU4YjMwNDVlMTlkM2EzOTdiYTgzM2Q2OTRjYWE4ZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JnJlc3BvbnNlLWNvbnRlbnQtdHlwZT1pbWFnZSUyRnBuZyJ9.1pERJ4Lq_lWsZGjZPkfIMq0g0_kgZIrUpzNmoBaBKvA"> ![4c56a1a2861b351474988c26ab1e797](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62308153/50b3929c-6b4f-4e0c-b98a-0c1249a92d24) ![79e3f0948fd7cb9b5cec44fa88df3a4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62308153/68a14141-b058-406e-8470-6559d45bdc0d)
> 
> Please provide a detailed description of the issue and, if necessary, attach a screenshot. 详细描述问题，并在必要时附上屏幕截图。

我的t95z plus使用 Armbian_26.05.0_amlogic_s912-t95z-plus_noble_6.18.20_server_2026.04.01.img 也有一样的问题，请问是如何解决的
