### ISSUE TITLE
Armbian 23.8.1 Aml-s9xx do not boot (Box: x96 mini / S905w)

### ISSUE THREAD

**Issue by deenbee** [ophub/amlogic-s9xxx-armbian#1683]
**Device Information |
 - SOC:  Amlogic S905w
 - Model x96 mini

**Armbian Version | 22.8.1
 - Kernel Version: 6.1.50
 - Release: bookworm / xfce_desktop

Mirror links:
https://mirror-us-phx1.armbian.airframes.io/dl/aml-s9xx-box/archive/?sort=time&order=asc

Hardware:

![265304877-483efedf-424e-4921-8ad0-d9f575942123](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/3ac443b3-9474-4608-bc8b-e5cfc1ee5ac8)
![265302564-7deb9c63-587e-4da6-8638-12a4bc512b3c](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/1059685d-6cfd-4c42-aae2-00d6a81fd659)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/4cb34a33-020c-4094-96cf-481f3a2616be)

s912 duplicated and renamed to u-boot.ext
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/d3892974-04a6-4167-9ef4-af80966c3619)

**Describe the bug 

Do not boot

![photo_5170224409531755297_y](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/5155c9a9-69ba-4c5d-9ed7-b4e68f42879c)

**Comment by ophub** [comment]
Your system does not belong to this repo. You can download it from the release and try it.
