### ISSUE TITLE
libc-bin报错

### ISSUE THREAD

**Issue by gym405043** [ophub/amlogic-s9xxx-armbian#1685]
Device Information | 设备信息

SOC: amlogic s905d
Model: Phicomm-N1
Armbian Version | 系统版本

Kernel Version: 6.1.5
Release: Jammy

**Describe the bug | 问题描述**
在安装casaos时遇到报错：
Sub-process /usr/bin/dpkg returned an error code
用https://www.cnblogs.com/huojing/articles/15821485.html处理后成功安装casaos，但是在安装宝塔面板是报了同样的错误信息

**Comment by 13584452567** [comment]
你的错误日志或者详细的问题描述呢

**Comment by gym405043** [comment]
> 你的错误日志或者详细的问题描述呢

更新了描述，请大佬看下

**Comment by 13584452567** [comment]
> > 你的错误日志或者详细的问题描述呢
> 
> 更新了描述，请大佬看下

没有报错日志吗？

你这看起来是libc-bin的版本问题。如果没有什么重要数据的话，下载release里面最新的镜像重新刷一下吧。libc-bin是很多软件的依赖，它出问题处理起来相当的麻烦。

**Comment by gym405043** [comment]
> > > 你的错误日志或者详细的问题描述呢
> > 
> > 
> > 更新了描述，请大佬看下
> 
> 没有报错日志吗？
> 
> 你这看起来是libc-bin的版本问题。如果没有什么重要数据的话，下载release里面最新的镜像重新刷一下吧。libc-bin是很多软件的依赖，它出问题处理起来相当的

> > > 你的错误日志或者详细的问题描述呢
> > 
> > 
> > 更新了描述，请大佬看下
> 
> 没有报错日志吗？
> 
> 你这看起来是libc-bin的版本问题。如果没有什么重要数据的话，下载release里面最新的镜像重新刷一下吧。libc-bin是很多软件的依赖，它出问题处理起来相当的麻烦。

好的，感谢

**Comment by gym405043** [comment]
> > > 你的错误日志或者详细的问题描述呢
> > 
> > 
> > 更新了描述，请大佬看下
> 
> 没有报错日志吗？
> 
> 你这看起来是libc-bin的版本问题。如果没有什么重要数据的话，下载release里面最新的镜像重新刷一下吧。libc-bin是很多软件的依赖，它出问题处理起来相当的麻烦。

换了最新的luner和jmmy都不行，报相同的错误

**Comment by HeroPoter** [comment]
目前解决方案是删除或mv掉 /var/lib/dpkg/info 目录，最好是在安装软件前
