### ISSUE TITLE
重新编译内核不能指定内核版本号

### ISSUE THREAD

**Issue by sniperpr** [ophub/amlogic-s9xxx-armbian#1686]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.82]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
一开始我指定了 5.15.82 版本，但是运行 recompile后，就自动编译5.15.130了。。。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1270268/1c2f078e-715e-470f-ae20-0dd5be96be69)

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
现在不能编指定版本，只能编最新版本。
之前使用kernel.org的时候可以指定版本，我不想维护多个内核来源给删除了。

**Comment by sniperpr** [comment]
> 现在不能编指定版本，只能编最新版本。 之前使用kernel.org的时候可以指定版本，我不想维护多个内核来源给删除了。

我使用 命令，看起来可以编译出来指定版本号。按照你的说法，应该是错误的，其实还是 最新版本内核，对吧？

**Comment by ophub** [comment]
-a false 现在只有1个作用了，就是不在查询和拉去github的最新源码，直接使用本地内核源码进行编译。这个用于本地调试，修改内核的文件后，避免再拉去仓库把本地覆盖了。

在早期的时候，这个-a false还支持使用kernel.org的固定版本的内核，在kernel的官方，每个版本的源码是独立的tar文件： https://cdn.kernel.org/pub/linux/kernel/v6.x/ 所以可以下载指定版本的源码进行编译。但是后来我取消了对从kernel.org直接下载编译的支持了，原因是考虑到盒子的特殊性，可能还是必须要一些补丁，直接使用kernel.org的内核，可能没几个盒子能愉快地跑，基于谨慎考虑还是不要闹着玩了，严肃点使用f大灯大佬们维护的仓库是比较稳妥的方案。

**Comment by sniperpr** [comment]
> `-a false` 现在只有1个作用了，就是不在查询和拉取github内核仓库的最新源码，直接使用本地内核源码进行编译。这个用于本地调试，修改内核的文件后，避免再拉取仓库把本地覆盖了。
> 
> 在早期的时候，这个`-a false`还支持使用kernel.org的固定版本的内核，在kernel的官方，每个版本的源码是独立的tar文件： https://cdn.kernel.org/pub/linux/kernel/v6.x/ 所以可以下载指定版本的源码进行编译。但是后来我取消了对从kernel.org直接下载编译的支持了，原因是考虑到盒子的特殊性，可能还是必须要一些补丁，直接使用kernel.org的内核，可能没几个盒子能愉快地跑，基于谨慎考虑还是不要闹着玩了，严肃点使用f大灯大佬们维护的仓库是比较稳妥的方案。
> 
> 如果你使用 https://github.com/ophub/kernel 里介绍的打补丁方法的话，`-a false` 对kernel.org是可以使用的，把你的单个盒子的dtb等缺少的文件和驱动等patch放到指定目录里，然后编译就好了。

您好，讲解的非常详细了。
我主要是要build 一个helloword.ko，插入。
有版本依赖。
