### ISSUE TITLE
寻求Lunar下的lxde或xfce4轻量级桌面安装方法

### ISSUE THREAD

**Issue by YanCastle** [ophub/amlogic-s9xxx-armbian#1688]
目前盒子型号是MG101 s905x p212 
系统版本lunar，其它几个版本也测试了下lxde都失败了
通过armbin-software 选择201安装桌面默认是gnome+gdm方案，资源占用较大，桌面操作卡顿明显，
希望能够安装lxde来降低资源占用，让盒子启动后自动运行自己编写的一个UI程序，用于播放视频和集中控制使用。

**Comment by zengfr** [comment]
https://github.com/zengfr/armbian-ubuntu-scripts/blob/main/install-gui-mini.sh
