### ISSUE TITLE
写入emmc卡在第一步，dtb的频率直接缩一个0，还是不行

### ISSUE THREAD

**Issue by Du22** [ophub/amlogic-s9xxx-armbian#1689]
![QQ图片20230906203131](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74237508/f297ae80-6507-4df2-b1c5-13a4864fa95c)
很奇怪哦，网上都没有和我一样的

**Comment by ophub** [comment]
什么设备

**Comment by Du22** [comment]
> 什么设备

m401a

**Comment by ophub** [comment]
看文档，降低dtb频率

**Comment by Du22** [comment]
> 看文档，降低dtb频率

只是盲区。。

**Comment by Du22** [comment]
> 看文档，降低dtb频率

在文档没有看到dtb编译方法，大佬

**Comment by ophub** [comment]
看12.16的方法

**Comment by Du22** [comment]
> 看12.16的方法

嗯。。。。修改克隆到自己仓库之后不会编译了

**Comment by Du22** [comment]
> 看文档，降低dtb频率

降到了50000000，依旧卡在这里

**Comment by Du22** [comment]
> 看12.16的方法

已经降到2开头了，刚发现我的m401a是单电感，是不是这个原因
