### ISSUE TITLE
x96 max+ Bluetooth: hci0: command 0x0xxxx tx timeout

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#169]
```
root@armbian:~# uname -a
Linux armbian 5.16.14-flippy-70+ #60 SMP PREEMPT Fri Mar 11 21:52:35 CST 2022 aarch64 GNU/Linux
root@armbian:~# dmesg | grep Blue
[    9.606488] Bluetooth: Core ver 2.22
[    9.611082] Bluetooth: Starting self testing
[    9.625273] Bluetooth: ECDH test passed in 10626 usecs
[    9.631449] Bluetooth: SMP test passed in 2772 usecs
[    9.634727] Bluetooth: Finished self testing
[    9.643461] Bluetooth: HCI device and connection manager initialized
[    9.649853] Bluetooth: HCI socket layer initialized
[    9.658023] Bluetooth: L2CAP socket layer initialized
[    9.661260] Bluetooth: SCO socket layer initialized
[    9.795433] Bluetooth: HCI UART driver ver 2.3
[    9.798791] Bluetooth: HCI UART protocol H4 registered
[    9.802415] Bluetooth: HCI UART protocol BCSP registered
[    9.802544] Bluetooth: HCI UART protocol LL registered
[    9.802550] Bluetooth: HCI UART protocol ATH3K registered
[    9.802602] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    9.802883] Bluetooth: HCI UART protocol Intel registered
[    9.803192] Bluetooth: HCI UART protocol Broadcom registered
[    9.803232] Bluetooth: HCI UART protocol QCA registered
[    9.803235] Bluetooth: HCI UART protocol AG6XX registered
[    9.803269] Bluetooth: HCI UART protocol Marvell registered
[   10.560143] Bluetooth: hci0: RTL: examining hci_ver=08 hci_rev=000c lmp_ver=08 lmp_subver=8822
[   10.582374] Bluetooth: hci0: RTL: rom_version status=0 version=3
[   10.593283] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cs_fw.bin
[   10.658664] Bluetooth: hci0: RTL: loading rtl_bt/rtl8822cs_config.bin
[   10.686276] Bluetooth: hci0: RTL: cfg_sz 73, total sz 40777
[   11.046513] Bluetooth: hci0: RTL: fw version 0x05a91a4a
[   15.995658] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.998276] Bluetooth: BNEP filters: protocol multicast
[   16.003101] Bluetooth: BNEP socket layer initialized
[  118.897942] Bluetooth: hci0: command 0x0c14 tx timeout
[  124.657944] Bluetooth: hci0: command 0x0c14 tx timeout
[  131.697939] Bluetooth: hci0: command 0x0c14 tx timeout
[  138.311281] Bluetooth: hci0: command 0x0c14 tx timeout
root@armbian:~# hciconfig -a
hci0:	Type: Primary  Bus: UART
	BD Address: 44:EF:BF:F8:31:0B  ACL MTU: 1021:5  SCO MTU: 255:11
	UP RUNNING 
	RX bytes:5701 acl:0 sco:0 events:254 errors:0
	TX bytes:79820 acl:0 sco:0 commands:3823 errors:0
	Features: 0xff 0xff 0xff 0xfe 0xdb 0xfd 0x7b 0x87
	Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
	Link policy: RSWITCH HOLD SNIFF PARK 
	Link mode: SLAVE ACCEPT 
Can't read local name on hci0: Connection timed out (110)
```
![image](https://user-images.githubusercontent.com/9335046/158284762-be69e500-22c6-444c-9f48-82093cd75ee5.png)

**Comment by ophub** [comment]
`modprobe 88x2cs`
Try loading it manually.

**Comment by EastWoodYang** [comment]
Still not working...

![image](https://user-images.githubusercontent.com/9335046/158351251-a8e76474-de0d-4971-b7c5-87642048115a.png)
![image](https://user-images.githubusercontent.com/9335046/158351341-e728d138-8fba-45bc-b457-bbcc302e5e7a.png)

**Comment by ophub** [comment]
Add bluetooth for x96/h96max x3/hk1box/ugoos x3

https://github.com/unifreq/linux-5.15.y/commit/9457cd188a55c90096cff36b6d4fd1c934f90d87

Add realtek rtl8822cs driver (module name: 88x2cs)
https://github.com/unifreq/linux-5.15.y/commit/d1a5aff412af28dc10787a76e2bcc432d39cc999

This driver is not available in the mainline kernel by default. If a third-party driver is added, it may not be perfect. If you can't use it, turn off Bluetooth.

**Comment by EastWoodYang** [comment]
目前使用的内核版本是5.16.y
之前在5.15.y上测试过，蓝牙无法识别出来
早上关注到f大前天做了调整
https://github.com/unifreq/linux-5.16.y/commit/cb29e133831ed8c6067ac44513819f9b9d1a0aaa
后面我再看下

**Comment by ophub** [comment]
You can try to update to the latest kernel

**Comment by EastWoodYang** [comment]
我等你这边内核升级上去之后，我再打包看看 :-)

**Comment by fooy** [comment]
> hk1 box的蓝牙一直不行，不断看到有人提issue ，感觉离解决不远了，持续关注中

我用armbian-update 5.16.15升级了最新版，可以证实蓝牙可以用了，抢先在这里报告下，我再随便放点音乐测试下稳定性

**Comment by EastWoodYang** [comment]
> 

确定嘛？你盒子里面的模块型号是啥？为啥我的还是不行，我的是rtl8822cs

**Comment by fooy** [comment]
蓝牙键盘都连上了很好用 
看起来是BCMXXXX 之类的芯片

y@armbian:~$ dmesg |grep -i blue
[    7.766660] Bluetooth: Core ver 2.22
[    7.770446] Bluetooth: Starting self testing
[    7.782112] Bluetooth: ECDH test passed in 7949 usecs
[    7.788538] Bluetooth: SMP test passed in 2621 usecs
[    7.792025] Bluetooth: Finished self testing
[    7.794509] NET: Registered PF_BLUETOOTH protocol family
[    7.801695] Bluetooth: HCI device and connection manager initialized
[    7.818305] Bluetooth: HCI socket layer initialized
[    7.823189] Bluetooth: L2CAP socket layer initialized
[    7.828259] Bluetooth: SCO socket layer initialized
[    7.961417] Bluetooth: HCI UART driver ver 2.3
[    7.965141] Bluetooth: HCI UART protocol H4 registered
[    7.985529] Bluetooth: HCI UART protocol BCSP registered
[    7.994574] Bluetooth: HCI UART protocol LL registered
[    8.013751] Bluetooth: HCI UART protocol ATH3K registered
[    8.058461] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.063207] Bluetooth: HCI UART protocol Intel registered
[    8.068615] Bluetooth: HCI UART protocol Broadcom registered
[    8.097339] Bluetooth: HCI UART protocol QCA registered
[    8.126236] Bluetooth: HCI UART protocol AG6XX registered
[    8.126347] Bluetooth: HCI UART protocol Marvell registered
[    8.495879] Bluetooth: hci0: BCM: chip id 86
[    8.496670] Bluetooth: hci0: BCM: features 0x2f
[    8.498441] Bluetooth: hci0: BCM4335C0
[    8.498453] Bluetooth: hci0: BCM4335C0 (003.001.009) build 0000
[    8.508400] Bluetooth: hci0: BCM4335C0 'brcm/BCM4335C0.hcd' Patch
[    9.293821] Bluetooth: hci0: AMPAK AP6335i BCM4339 37.4M CL1 BT4.0 CSP743120-0055
[    9.299530] Bluetooth: hci0: BCM4335C0 (003.001.009) build 0268
[   15.444137] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.447120] Bluetooth: BNEP filters: protocol multicast
[   15.452712] Bluetooth: BNEP socket layer initialized
[  128.352717] Bluetooth: HIDP (Human Interface Emulation) ver 1.2
[  128.353033] Bluetooth: HIDP socket layer initialized
[  128.365409] input: B.O.W Keyboard as /devices/platform/soc/ffd00000.bus/ffd24000.serial/serial0/serial0-0/bluetooth/hci0/hci0:11/0005:04E8:7021.0003/input/input3

**Comment by EastWoodYang** [comment]
嗯...我已经着手准备把rtl8822cs拆掉换成AP6330看看行不行的通

**Comment by LondyGhost** [comment]
> 嗯...我已经着手准备把rtl8822cs拆掉换成AP6330看看行不行的通

冒昧问一句，更换成功了吗？

**Comment by EastWoodYang** [comment]
没，不大行
