### ISSUE TITLE
CM401a求教各位大佬，openwrt写入了emmc以后如何优先启动U盘的岸边系统？

### ISSUE THREAD

**Issue by klcb2010** [ophub/amlogic-s9xxx-armbian#1690]
openwrt弱爆了，安装何种软件都提示不兼容，另外启动某些容器居然提示错误，岸边系统写入了U盘，如何让它优先启动？

**Comment by ophub** [comment]
什么盒子

**Comment by klcb2010** [comment]
> 什么盒子

我自己傻逼了，下错了固件，回家再试一下正确固件，现在有个疑问，emmc已经有了openwrt系统，它如何能优先启动U盘的岸边系统？

**Comment by ophub** [comment]
默认即可，不用改什么
