### ISSUE TITLE
Home Assistant安装脚本增加/media目录映射

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#1692]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3] all
 - Model [e.g. HK1] all

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] all
 - Release: [e.g. jammy/bullseye] all

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

容器运行的HA，需要把本地媒体目录映射出来，参考：
https://www.home-assistant.io/integrations/media_source/#local-media

方法：在文件 /usr/share/ophub/armbian-software/command-docker.sh第344行附近增加：
`-v ${install_path}/media:/media \`

建议o大在源头上修改

**Comment by ophub** [comment]
已经更新
