### ISSUE TITLE
M401a的EMMC启动失败代码12

### ISSUE THREAD

**Issue by klcb2010** [ophub/amlogic-s9xxx-armbian#1696]
写入结果：Installation successful. Run [ poweroff ], remove the installation media then re-insert the power supply to boot new system.
启动结果：
![IMG_20230907_181202](https://github.com/ophub/amlogic-s9xxx-armbian/assets/32628414/d2240580-68ee-49ea-ac25-bddc63b56aac)

**Comment by ophub** [comment]
降低dtb频率，重写一下

**Comment by klcb2010** [comment]
> 降低dtb频率，重写一下

看了文档  没看懂

**Comment by hungpr0** [comment]
I also have the same issue with [Armbian_bookworm_save_2023.08]
Before installing to EMMC, boot to USB run `armbian-update -k 6.1.52`, then reboot
You then can install to EMMC, `armbian-install`

**Comment by klcb2010** [comment]
> I also have the same issue with [Armbian_bookworm_save_2023.09] Before installing to EMMC, boot to USB run `armbian-update -k 6.1.52`, then reboot You then can install to EMMC, `armbian-install`

对这个系统失去了兴趣。已经刷回安卓系统了，谢谢。
