### ISSUE TITLE
cm311-1a，ssh提示Remote side unexpectedly closed network connection

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#1697]
**Device Information | 设备信息**
 cm311-1a-yst，s905la

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
cm311-1a，ssh提示Remote side unexpectedly closed network connection。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.

/
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/96900868/21f992b9-e356-4d0c-93a3-a3db060d62c6)

**Comment by Doboo** [comment]
换个工具试试  我一直用mobaxterm
