### ISSUE TITLE
Wifi and bluetooth

### ISSUE THREAD

**Issue by pulpoff** [ophub/amlogic-s9xxx-armbian#17]
Neither wifi or bt working on gt king 
Also only kernel 5.12.19 supports 2.2Ghz smooth operation while other kernels run much slower.
Is it possible to build 5.15 kernel with 2.2 and 2.4ghz support? 
I installed armbian-firmware-full but that didn't fix wifi and bt 
Any help?

**Comment by pulpoff** [comment]
As u suggested I built my ubuntu 21.10 gnome 4.0 image based on armbian with usb boot from openwrt.
Image is available here: https://vp5.net/king/

**Comment by ophub** [comment]
https://www.kernel.org/
Please compile and debug the kernel yourself according to your needs.
`make menuconfig`
![Snip20211111_1](https://user-images.githubusercontent.com/68696949/141260779-09c7404e-1e4a-45d6-a116-791d169ad835.png)
![Snip20211111_2](https://user-images.githubusercontent.com/68696949/141260797-4fba8f03-201f-447b-912e-4ebae1553e0b.png)
![Snip20211111_4](https://user-images.githubusercontent.com/68696949/141260799-73366c4c-331e-4174-aa93-e7d242016d74.png)

![Snip20211111_5](https://user-images.githubusercontent.com/68696949/141260807-a684016e-9665-4c4a-b076-6b09916c9128.png)
![Snip20211111_6](https://user-images.githubusercontent.com/68696949/141260815-016d9d61-0550-4fbd-88d6-711470ce206c.png)

**Comment by pulpoff** [comment]
ok thanks
