### ISSUE TITLE
S905x T95 kernel 5.15.28 u-boot fail

### ISSUE THREAD

**Issue by chris4git** [ophub/amlogic-s9xxx-armbian#170]
Hi,
I try to boot Armbian_22.05.0_Aml_s905x_focal_5.15.28_2022.03.13.2241.img on my S905x box called T95 (5.4 kernel has a buggy wifi driver).
dtb used :  /dtb/amlogic/meson-gxl-s905x-p212.dtb
u-boot.ext : u-boot-s905x-s912
but u-boot fails like that :

![vlcsnap-2022-03-06-09h53m11s986](https://user-images.githubusercontent.com/23280864/158345586-893b159c-4b4b-4727-ba8f-ad67ca7e21f1.png)

if I replace uEnv.txt with a directory extlinux/ with a file extlinux.conf containing

```
LABEL Armbian
LINUX /zImage
INITRD /uInitrd
FDT /dtb/amlogic/meson-gxl-s905x-p212.dtb
APPEND root=UUID=39d5b9f6-78cb-4c09-b6d2-6fdf757c4ff2 rootfstype=btrfs rootflags=compress=zstd:6 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
```
the kernel boots fine !
what is wrong with original uEnv.txt ?

Chris

**Comment by ophub** [comment]
`extlinux/extlinux.conf`

You test on 5.4, 5.15 are normal?

**Comment by chris4git** [comment]
extlinux.conf is useful for 5.15. No need for 5.4.

**Comment by ophub** [comment]
I understand that in the case of using extlinux/extlinux.conf in the 5.15 kernel, it is not possible to reload u-boot, but uEnv.txt can be used.

Both methods can be used in the 5.4 kernel

**Comment by ophub** [comment]
If you test it and it works, use it.
