### ISSUE TITLE
m401a拆出来主板发现是单电感，能刷armbian吗

### ISSUE THREAD

**Issue by Du22** [ophub/amlogic-s9xxx-armbian#1700]
u盘启动正常，就是无法写入emmc，
![QQ图片20230906203131](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74237508/66790eec-25ee-40b8-b6fd-cbecaabd1e28)
 已经把dtb频率缩了一个0了，还是这样

**Comment by ophub** [comment]
有的存储可能是nand的，不能写入

**Comment by Du22** [comment]
> 有的存储可能是nand的，不能写入

怎么看啊，唉，好不容易买一个还踩坑了

**Comment by ophub** [comment]
lsblk

**Comment by Du22** [comment]
> lsblk

![QQ图片20230909141339](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74237508/2cfe0ba3-40d7-449a-a1c8-a8fe861ed345)
貌似没有大佬你说的那个

**Comment by ophub** [comment]
mmcblk2这个是emmc
如果是nand的话，lsblk看不到盒子自带的存储

**Comment by Du22** [comment]
> mmcblk2这个是emmc 如果是nand的话，lsblk看不到盒子自带的存储

所以说不是储存问题，我也降频了啊，重启也写不进去，我的脑子啊

**Comment by ophub** [comment]
降低到50hz

**Comment by Du22** [comment]
> 降低到50hz，复制文档里的值

我都试了，一点一点降的，已经降成10了，还是不行，我再看看

**Comment by ophub** [comment]
以往大家降到50就可以了。有人降到100也行。

**Comment by klcb2010** [comment]
用这个文件试试  https://github.com/janko888/MagicBox/tree/main/M401A/firmware

**Comment by Du22** [comment]
> 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware

还是不行，换了之后，U盘不能启动了

**Comment by klcb2010** [comment]
> > 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware
> 
> 还是不行，换了之后，U盘不能启动了

uEnv改成m401a了吗？

**Comment by Du22** [comment]
> > > 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware
> > 
> > 
> > 还是不行，换了之后，U盘不能启动了
> 
> uEnv改成m401a了吗？

改了，之前写入不了但是能u盘，换了之后，现在U盘都不行了，重写U盘都不行

**Comment by Du22** [comment]
> > > 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware
> > 
> > 
> > 还是不行，换了之后，U盘不能启动了
> 
> uEnv改成m401a了吗？

我现在彻底要疯了，下午试了一下，现在U盘也死活进不去了

**Comment by ophub** [comment]
你要不换个安卓系统吧，也许一下就好了。
https://github.com/ophub/kernel/releases/tag/tools

**Comment by klcb2010** [comment]
> > > > 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware
> > > 
> > > 
> > > 还是不行，换了之后，U盘不能启动了
> > 
> > 
> > uEnv改成m401a了吗？
> 
> 我现在彻底要疯了，下午试了一下，现在U盘也死活进不去了

usb接口问题  远离网口那个接口 往下用一小点力压着U盘开机试试 。我现在倒是没用岸边系统了   感觉没有啥玩的，昨晚捣鼓到今早，终于把安卓系统刷进去了，很确定是U盘接口问题。

**Comment by Du22** [comment]
> 你要不换个安卓系统吧，也许一下就好了。 https://github.com/ophub/kernel/releases/tag/tools

看网上说，单电感包不好找

**Comment by Du22** [comment]
> > > > > 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware
> > > > 
> > > > 
> > > > 还是不行，换了之后，U盘不能启动了
> > > 
> > > 
> > > uEnv改成m401a了吗？
> > 
> > 
> > 我现在彻底要疯了，下午试了一下，现在U盘也死活进不去了
> 
> usb接口问题 远离网口那个接口 往下用一小点力压着U盘开机试试 。我现在倒是没用岸边系统了 感觉没有啥玩的，昨晚捣鼓到今早，终于把安卓系统刷进去了，很确定是U盘接口问题。

难受

**Comment by Du22** [comment]
> > > > > 用这个文件试试 https://github.com/janko888/MagicBox/tree/main/M401A/firmware
> > > > 
> > > > 
> > > > 还是不行，换了之后，U盘不能启动了
> > > 
> > > 
> > > uEnv改成m401a了吗？
> > 
> > 
> > 我现在彻底要疯了，下午试了一下，现在U盘也死活进不去了
> 
> usb接口问题 远离网口那个接口 往下用一小点力压着U盘开机试试 。我现在倒是没用岸边系统了 感觉没有啥玩的，昨晚捣鼓到今早，终于把安卓系统刷进去了，很确定是U盘接口问题。

不是接口问题，我插还能识别，只是进不去armbian，重写U盘也没用

**Comment by Du22** [comment]
> 你要不换个安卓系统吧，也许一下就好了。 https://github.com/ophub/kernel/releases/tag/tools

试了，我还试了单电感的311-1a的包，都卡1%

**Comment by Du22** [comment]
> 你要不换个安卓系统吧，也许一下就好了。 https://github.com/ophub/kernel/releases/tag/tools

大佬，卡在
![IMG_20230909_212612](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74237508/ec9ac334-a8ec-44dd-ba3d-6d8e902893a3)
这里循环

**Comment by ophub** [comment]
试试USB启动armbian

**Comment by Du22** [comment]
> https://github.com/janko888/MagicBox/tree/main/M401A/firmware

https://github.com/janko888/MagicBox/tree/main/M401A/firmware
试了那个大哥发的这个dtb之后，usb就启动不了了，就是开机之后，粉红屏，然后黑屏

**Comment by ophub** [comment]
你再改回去，覆盖一下

**Comment by Du22** [comment]
> 你再改回去，覆盖一下

我格式化，重新写都没用

**Comment by ophub** [comment]
只是换了一个dtb文件吧？又没写入emmc什么文件，应该是无损的呀

**Comment by Du22** [comment]
> 只是换了一个dtb文件吧？又没写入emmc什么文件，应该是无损的呀

现在一脸迷茫，u盘进不去，系统还进不去
