### ISSUE TITLE
MT7668RSN Wifi驱动编译安装参考/蓝牙不能用

### ISSUE THREAD

**Issue by A-nemon-e** [ophub/amlogic-s9xxx-armbian#1701]
纯小白，花了两天时间试验，终于编译安装成功了。简单记录下过程，大神请勿见笑。

参考：
- https://github.com/noob404yt/mt7668-wifi-bt
- https://ps4linux.com/mt7668-wifi-bluetooth-drivers-linux-compile/
- https://github.com/yHpgi/MT7668/tree/k5.10 （我没试6.1的）
- https://github.com/ophub/amlogic-s9xxx-armbian/issues/1043
- https://github.com/ulli-kroll/rtl8814au/issues/15
- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1906131
- https://github.com/Mange/rtl8192eu-linux-driver/issues/205#issuecomment-736366347
- ChatGPT

kernel 5.10.183 dev（理论上任意5.10内核都行）
### 一、如果不是5.10，换至5.10内核。
```
armbian-update -k 5.10.183 -u dev
```

### 二、根据https://github.com/ophub/amlogic-s9xxx-armbian/issues/1043 安装和编译内核相同版本的gcc（这一步可能可以不用做，用自带的gcc貌似也可以。没验证）
我之前就改成了gcc version 12.3.1 20230626 (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) ，具体需要改成什么版本用cat /proc/version看，其它参照#1043，已经很详细了

### 三、
```
git clone -b k5.10 https://github.com/yHpgi/MT7668
cd MT7668
nano Makefile.x86
#第3行第28行的x86改成arm64（可能能不用改，我也不知道。。）
#20行的usb改成sdio
#24行改成MODULES_NAME := wlan_mt76x8

make  EXTRA_CFLAGS="-w" CROSS_COMPILE= -f Makefile.x86 -j4

cd drv_wlan/MT6632/wlan
#如果编译没有问题，应该能看到一个wlan_mt76x8.ko
```

### 四、加载
先cd到7668_firmware文件夹，
```
cp * /usr/lib/firmware/
```
如果只要本次系统运行时加载驱动：
```
modprobe cfg80211
insmod wlan_mt76x8.ko
```
如果要每次启时自动加载：
```
nano /etc/modules
```
加入两行
cfg80211
wlan_mt76x8

然后
```
depmod -a
```
重启后，`nmcli dev`，能看到出现了WiFi
wlan0        wifi     disconnected  --
ap0          wifi      disconnected  --                 
ap1          wifi      disconnected  --                 
p2p-dev-ap0  wifi-p2p  disconnected  --                 
p2p-dev-ap1  wifi-p2p  disconnected  -- 

如果在加载时出现问题，查看内核日志
`dmesg | grep wlan`

**Comment by A-nemon-e** [comment]
忘了说了，我这个盒子只有5.10有不拔插网线没ip的问题，5.4和5.15都没，解决方啊参考了之前的issue（一时半会找不到连接。。）nano /etc/NetworkManager/system-connections/'Wired connection 1.nmconnection'
[ethernet]添加duplex=full和speed=100


至于MT7668的蓝牙不知道为什么用不了自带的btmtksdio，盒子不在身边，不好远程连接试着换dtb，万一换了个dtb不开机就扯淡了

**Comment by A-nemon-e** [comment]
蓝牙目前是这么个状况，内核日志grep Bluetooth和hci0没报错，但是hciconfig hci0 up不行，（只能看到Mac地址，）显示资源暂时不可用，armbian-config里也没bluetooth discover，一副没驱动上的样子。
问题是看了5.10.y的driver里，btmtkuart里（btmtksdio基于uart写的）有7662 7668u的compatible，于是反编译dtb，找了几个写了蓝牙的dtb参考，又看到之前xcray大佬捣鼓蓝牙的一系列issue，依葫芦画瓢改了dts，但怎样改都没用

**Comment by A-nemon-e** [comment]
蓝牙目前是这么个状况，内核日志grep Bluetooth和hci0没报错，但是hciconfig hci0 up不行，（只能看到Mac地址，）显示资源暂时不可用，armbian-config里也没bluetooth discover，一副没驱动上的样子。
问题是看了5.10.y的driver里，btmtkuart里有7663u 7668u的compatible，于是反编译dtb，找了几个写了蓝牙的dtb参考，又看到之前xcray大佬捣鼓蓝牙的一系列issue，依葫芦画瓢改了dts（用的x7-5g那个改的），开了个serial但怎样改都没用，内核日志也没有新东西出现。（似乎他那个是uart的蓝牙但我这个是sdio的）
另一个同型号盒子是mt7661rsn，dtb啥都没动（没额外去打开某个串口）的情况下就能驱动蓝牙（他在mmc控制器显示7663），用加载和卸载模块的方式确定了就是被btmtksdio驱动的。
那么问题来了，这个7668的蓝牙到底啥原因不能用呢

**Comment by ophub** [comment]
https://github.com/chewitt/MT7668

**Comment by A-nemon-e** [comment]
> https://github.com/chewitt/MT7668
> 
> https://github.com/yHpgi/MT7668
> 
> 试试这个驱动

我试的就是下面一个，他只有WiFi不能蓝牙

**Comment by A-nemon-e** [comment]
https://github.com/noob404yt/mt7668-wifi-bt
编译了这个的蓝牙部分，但安装后还是用不了
我5.10编译的，作者说是5.4才能用，但我wifi驱动是5.10下编译的所以只能用5.4（他的WiFi驱动5.4也编译不了不知道为什么）

```
root@armbian:~# dmesg | grep Blue

[   11.664820] Bluetooth: Core ver 2.22
[   11.664830] Bluetooth: Starting self testing
[   11.692340] Bluetooth: ECDH test passed in 26844 usecs
[   11.698732] Bluetooth: SMP test passed in 6143 usecs
[   11.698775] Bluetooth: Finished self testing
[   11.698874] Bluetooth: HCI device and connection manager initialized
[   11.698892] Bluetooth: HCI socket layer initialized
[   11.698902] Bluetooth: L2CAP socket layer initialized
[   11.698930] Bluetooth: SCO socket layer initialized
[   11.753544] btmtk_sdio_probe Mediatek Bluetooth driver Version=v0.0.0.53_2018072701_YOCTO
[   12.391369] Bluetooth: hci0: unexpected event for opcode 0xfcd1   👈不知道是不是这个报错
[   21.043820] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.046259] Bluetooth: BNEP filters: protocol multicast
[   21.053012] Bluetooth: BNEP socket layer initialized

```
```
root@armbian:~# dmesg | grep btmtk

[   11.753544] btmtk_sdio_probe Mediatek Bluetooth driver Version=v0.0.0.53_2018072701_YOCTO
[   11.753564] btmtk_sdio_probe chip_id is 7668
[   11.753949] btmtk_sdio_enable_host_int read CSDIOCSR is 0x1
[   11.754009] btmtk_sdio_enable_host_int write CSDIOCSR is 0x5
[   11.754014] btmtk_sdio_download_fw begin
[   11.754128] btmtk_sdio_send_wohci retrun  0x0
[   11.757341] btmtk_sdio_bt_memRegister_read: read cr 80000000
[   11.770597] btmtk_sdio_bt_memRegister_read: retrytime 299
[   11.770609] btmtk_sdio_bt_memRegister_read: ger cr 0x80000000 value 0x8b10
[   11.770613] btmtk_sdio_download_rom_patch uhwversion 0x8b10
[   11.770618] btmtk_sdio_download_rom_patch request_firmware(firmware name mt7668_patch_e2_hdr.bin)
[   11.771020] btmtk_sdio_download_rom_patch patch is ready no need load patch again
[   11.771146] btmtk_sdio_download_rom_patch read chipid =  f07668
[   11.771215] btmtk_sdio_bt_set_power: onoff 1
[   11.877545] btmtk_eeprom_bin_file: 7668 series
[   12.010662] btmtk_set_eeprom2ctrler: set BDAddress(72-76-68-48-3F-07) OK
[   12.117258] btmtk_set_eeprom2ctrler: set radio(BT/BLE default power: 0/0 MAX power: 0) OK
[   12.224073] btmtk_set_eeprom2ctrler: set power offset(00 00 00 00 00 00) OK
[   12.330581] btmtk_set_eeprom2ctrler: set XTAL(0xAE 00) OK
[   12.330614] btmtk_sdio_set_sleep begin
[   12.342083] btmtk_sdio_set_write_clear write CHCR 0x00000002
[   12.342662] btmtk_sdio_set_write_clear read CHCR 0x00000002
[   12.342671] btmtk_sdio_set_write_clear write clear
[   12.342724] btmtk_sdio_set_i2s_slave
[   12.346057] btmtk_sdio_read_pin_mux_setting
[   12.349595] btmtk_sdio_write_pin_mux_setting begin
[   12.352827] btmtk_sdio_read_pin_mux_setting
[   12.358886] btmtk_add_card begin
[   12.372608] btmtk_service_main_thread probe_ready 0 delay 10ms~15ms
[   12.376064] btmtk_sdio_probe normal end
```
```
root@armbian:~# hciconfig 

hci0:	Type: Primary  Bus: SDIO
	BD Address: 72:76:68:48:3F:07  ACL MTU: 1021:8  SCO MTU: 244:4
	DOWN 
	RX bytes:0 acl:0 sco:0 events:40 errors:0
	TX bytes:0 acl:0 sco:0 commands:0 errors:0
```
```
root@armbian:~# hciconfig hci0 up
Can't init device hci0: Invalid request code (56)
```
能力有限，能抄作业的都试过了，等大佬移植驱动到新内核了。

**Comment by ophub** [comment]
有没有别的设备使用这个芯片的，比如lede的openwrt系列里，可以找找他们使用的哪个驱动仓库。

**Comment by A-nemon-e** [comment]
有空我再来找找，先关闭了

**Comment by A-nemon-e** [comment]
这个方法的热点能打开但是别的设备全连不上。没查出原因，只能怀疑驱动

**Comment by sleepwalkera** [comment]
https://github.com/TSKangetsu/mt7668u/
这儿还有个驱动，可以试试

**Comment by boza111** [comment]
NI Hao

I am also looking for a driver to compile on my android TV box. Has anyone had any success?

**Comment by ophub** [comment]
mt7668 wifi和蓝牙测试内核及使用方法： https://github.com/ophub/amlogic-s9xxx-armbian/issues/3610#issuecomment-5091652991
