### ISSUE TITLE
UNT402A 有线网络无法使用

### ISSUE THREAD

**Issue by taskmemz** [ophub/amlogic-s9xxx-armbian#1703]
**Device Information | 设备信息**
 - SOC: [e.g. S095L]
 - Model [e.g. UNT402A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。
 我的UNT402A 广东移动，在刷入armbian以后启动无HDMI输出，UART端口被我焊废了，暂无法使用。浏览器未看到armbian设备，网络交换机上连接盒子的端口指示灯没有亮起。求O大能看到这个issue并解决
Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by klcb2010** [comment]
你这个应该是看不到IP地址吧？进路由器去看

**Comment by luohong1** [comment]
我也是 ，还专门买了个USB网卡  结果也需要驱动   还是不行

**Comment by mA520** [comment]
我也是unt402a,刷armbian后有线网络没有网
