### ISSUE TITLE
armbian-update更新，最近一直卡在这，没有进度

### ISSUE THREAD

**Issue by molun** [ophub/amlogic-s9xxx-armbian#1706]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/23138506/ac175301-ba2a-485c-9e21-16b2dd91e7ac)

**Comment by molun** [comment]
armbian:~:# armbian-update
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Dependency check completed.

[ STEPS ] Start checking network status...
[ INFO ] You can access [ github.com ] normally.

[ STEPS ] Start initializing parameters...
[ INFO ] Armbian platform: [ amlogic ]
[ INFO ] Kernel download repository: [ ophub/kernel ]
[ INFO ] Kernel download cdn: [  ]
[ INFO ] Kernel tags: [ stable ]
[ INFO ] Kernel version: [  ]
[ INFO ] Armbian is running on: [ /dev/mmcblk2 ]

[ STEPS ] Start querying kernel version...
[ INFO ] Query the latest kernel version of the [ 6.1 ] series within [ kernel_stable ]...
[ INFO ] Current version: [ 6.1.44 ], Latest version: [ 6.1.52 ].

[ STEPS ] Start downloading kernel package...
[ INFO ] Download kernel from: [ https://github.com/ophub/kernel/releases/download/kernel_stable/6.1.52.tar.gz ]
[ INFO ] Download kernel to:   [ /tmp/tmp.kGGeWnwbmz ]

**Comment by A-nemon-e** [comment]
你的网络下github太慢，要指定proxy

**Comment by ophub** [comment]
楼上正解
你也可以手动下载内核，解压进入内核4文件目录，本地armbian-update更新
