### ISSUE TITLE
请问有什么办法可以直接线刷镜像包吗？

### ISSUE THREAD

**Issue by caiyesd** [ophub/amlogic-s9xxx-armbian#1711]
如题，请问有什么办法可以直接线刷镜像包吗？

也就是直接通过 burning tool 来刷 img 文件，而目前的方式是先刷 Android 包，然后 adb reboot bootloader 从 u 盘启动，在从 u 盘 armbian-install 一下。
这个流程虽然能走通，但是有些繁琐，想咨询一下有没有直接通过 burning tool 工具一次性刷入 armbian 系统到 emmc 的方法。

谢谢！

**Comment by 13584452567** [comment]
https://7ji.github.io/embedded/2022/11/11/amlogic-booting.html
这个链接详细的介绍了aml的引导组成。你仔细阅读完，应该就会理解直接刷的困难在哪里。如果你能想出并实现直接刷入镜像的方法，那将是armbian项目的一大飞跃。

**Comment by caiyesd** [comment]
感谢您的回复，终于明白这里面的难度的。有时看似简单的需求，背后的复杂度难以想象。
