### ISSUE TITLE
UNT403A（s905l3b）支持写入emmc使用

### ISSUE THREAD

**Issue by yycvip** [ophub/amlogic-s9xxx-armbian#1712]
**Device Information | 智能机顶盒**
产品型号：UNT403A
![QQ图片20230911143536](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/a7c41c74-e452-4a39-910b-df03d3d15eda)

![QQ图片20230911143637](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/8faec78d-8755-4909-b88d-664259f5ebe3)

下载了Armbian_23.08.0_amlogic_s905l3b_bullseye_5.15.129_server_2023.09.02.img，用开心助手使盒子U盘重启。重启后HDMI不显示怎么办？不跑码
![QQ图片20230911143921](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/23b1d9d6-c2e9-485b-938c-02b7c694dfaf)

我把armbian写进U盘后什么都操作，直接插U盘重启盒子。是不是我哪里操作有问题？

**Comment by yycvip** [comment]
还有个问题，国内的请教的方式还有什么地方？我上github有点困难

**Comment by ophub** [comment]
有的魔百盒没有HDMI输出，去接入的路由器里看armbian上线的ip，ssh连接管理
默认安卓是无法u盘启动的，用adb，或者开心助手，短接神器等都可以让系统从u盘启动。

**Comment by yycvip** [comment]
路由器里没有ip，估计就是没成功

**Comment by yycvip** [comment]
我这个就有点冲突。
![1QQ图片20230911185810](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/4c23fbf2-5d80-4063-9474-896b0321df17)

**Comment by ophub** [comment]
soc可忽略，这几个都可以测试。
大部分人需要换个root的安卓系统。

**Comment by yycvip** [comment]
好的，那我就试试UNT403A的
安卓系统我现在只能刷进两个版本的

我写入U盘后需要再修改什么吗？

**Comment by ophub** [comment]
如果对版的话可以直接用，测试的话就修改/boot/uEnv.txt里面dtb的名字，照着model表改相近的那几个，看看哪个可以使用。
拿5.15的测试，dtb对了就可以用

**Comment by yycvip** [comment]
我刷成功了
![无标题](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/46414656-25e7-492c-b5b2-cf6046fe2f69)

**Comment by ophub** [comment]
你用的哪个组合？
cat /boot/armbianEnv.txt
ls -l /boot/u-boot*

**Comment by yycvip** [comment]
下载了好多，忘记在哪里下载了，我可以发给你。你看我怎么样发给你？
![无标题](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/ecf9f39d-0dba-472b-965a-add2703b3b49)

**Comment by yycvip** [comment]
你是不是要看的这个命令？
![无标题](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110331334/dc84d686-f201-4ead-889d-db7d4e3baaf0)

**Comment by ophub** [comment]
对，我看看现在的配置里是否包含，要不要添加新配置项。

安卓系统可以上传百度网盘等，你上传到某个地方发个下载链接。

**Comment by ophub** [comment]
s905l（115）, s905l3-cm211（121） 这2个固件默认编译，和你的配置完全相同，只是soc名字不同，这3个soc可以共用1个

**Comment by yycvip** [comment]
这个盒子不支持hdmi，我是无意间在路由器里看到盒子的地址了。然后ssh访问进入的。
盒子不跑码，在网上看到所有的视频都是HDMI会跑码。

**Comment by yycvip** [comment]
> s905l（115）, s905l3-cm211（121） 这2个固件默认编译，和你的配置完全相同，只是soc名字不同，这3个soc可以共用1个

但是芯片打印的是S905L3-B,我刷了好多安卓固件，最后有人告诉我不行换个思路，那就按能刷进安卓的型号刷armbian，期初也不显示跑码，后来我无意去路由器看了一眼，看到有ip，然后我用ssh就连接上了，剩下的就直接安装就可以了

**Comment by ophub** [comment]
我知道的仅有个别魔百盒是这样的，除了魔百盒外没有发现哪个hdmi不能用的。

**Comment by yycvip** [comment]
魔百和太坑了，芯片写的是S905L3-B.结果居然S905L刷进去的。

**Comment by ophub** [comment]
通用还不好吗，固件可选的多了

**Comment by yycvip** [comment]
之前不知道它能通用啊，完全按照型号进行。刷这个盒子我研究了一个多月

**Comment by ophub** [comment]
https://cowtransfer.com/

你如果没有百度网盘发安卓系统的话，奶牛快传也可以，免费支持大文件上传分享。

**Comment by yycvip** [comment]
链接：https://pan.baidu.com/s/1G3DPlL4-8EL9NQfCP3X-RQ?pwd=gg9m 
提取码：gg9m

**Comment by ophub** [comment]
我下载好了，一会我转存到这里，方便和你一个设备的使用：
https://github.com/ophub/kernel/releases/tag/tools

**Comment by yycvip** [comment]
你真的很负责啊，不知道这些文件在国内有存储的地址吗？我现在访问github都是买的代理，不然都访问不了。要是能在国内能下载就好了

**Comment by ophub** [comment]
国内哪有快的，百度没会员52k，下载老了。
github的releases是无限容量，国内有的地方访问github比较慢，我看有一些免费的中转加速网站，把github的文件下载地址贴到中转网站里面再下载就快了。

**Comment by yycvip** [comment]
主要没找到中转站，没办法花钱买的。

**Comment by yycvip** [comment]
盒子原来的源地址能再发一下吗？我换阿里云的和其他的都是https的，没有http的了

**Comment by ophub** [comment]
bullseye 的默认源：
```
deb http://deb.debian.org/debian bullseye main contrib non-free
#deb-src http://deb.debian.org/debian bullseye main contrib non-free

deb http://deb.debian.org/debian bullseye-updates main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

deb http://deb.debian.org/debian bullseye-backports main contrib non-free
#deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free

deb http://security.debian.org/ bullseye-security main contrib non-free
#deb-src http://security.debian.org/ bullseye-security main contrib non-free
```

**Comment by yycvip** [comment]
不用了，是我搞错了，设置固定ip，没设置dns地址。感谢

**Comment by tchain11** [comment]
请教大神，用u盘启动armbian一切正常，但是要刷入到emmc时，报错提示无法删除分区，请问这是啥原因呢？

[ OPTIONS ] Please Input ID (1/2): 2
[ INFO ] Input Type ID: [ 2 ]
[ INFO ] Type of filesystem: [ btrfs ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.228679 s, 18.3 MB/s
[ INFO ] Delete the existing [ 2 ] partitions.
Error: Input/output error during write on /dev/mmcblk2
[ ERROR ] Failed to delete partition [ 1 ]. Please try again.
root@armbian:~# ls -alh /dev/ | grep mmc
brw-rw----  1 root disk    179,   0 Jun  6 08:53 mmcblk2
brw-rw----  1 root disk    179,  32 Jun  6 07:42 mmcblk2boot0
brw-rw----  1 root disk    179,  64 Jun  6 07:42 mmcblk2boot1
brw-rw----  1 root disk    179,   1 Jun  6 08:53 mmcblk2p1
brw-rw----  1 root disk    179,   2 Jun  6 08:53 mmcblk2p2
crw-------  1 root root    236,   0 Jun  6 07:42 mmcblk2rpmb

**Comment by libiaolibiaolibiaobjca** [comment]
> 请教大神，用u盘启动armbian一切正常，但是要刷入到emmc时，报错提示无法删除分区，请问这是啥原因呢？
> 
> [ OPTIONS ] Please Input ID (1/2): 2 [ INFO ] Input Type ID: [ 2 ] [ INFO ] Type of filesystem: [ btrfs ] [ STEPS ] Partitioning eMMC... [ INFO ] Start backing up the default bootloader. 4+0 records in 4+0 records out 4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.228679 s, 18.3 MB/s [ INFO ] Delete the existing [ 2 ] partitions. Error: Input/output error during write on /dev/mmcblk2 [ ERROR ] Failed to delete partition [ 1 ]. Please try again. root@armbian:~# ls -alh /dev/ | grep mmc brw-rw---- 1 root disk 179, 0 Jun 6 08:53 mmcblk2 brw-rw---- 1 root disk 179, 32 Jun 6 07:42 mmcblk2boot0 brw-rw---- 1 root disk 179, 64 Jun 6 07:42 mmcblk2boot1 brw-rw---- 1 root disk 179, 1 Jun 6 08:53 mmcblk2p1 brw-rw---- 1 root disk 179, 2 Jun 6 08:53 mmcblk2p2 crw------- 1 root root 236, 0 Jun 6 07:42 mmcblk2rpmb

2024-08-11
遇到相同的问题 M401A
