### ISSUE TITLE
系统只能手动插入外挂硬盘，不然无限重启

### ISSUE THREAD

**Issue by Java2Boy** [ophub/amlogic-s9xxx-armbian#1715]
**Device Information | 设备信息**
 - SOC: [S905D]
 - Model [斐讯]

**Armbian Version | 系统版本**
 - Armbian 23.08.0-trunk Bullseye with Linux 6.1.52-ophub

**Describe the bug | 问题描述**
        昨天从SSH里apt upgrade了一下，看有fireware升级，就一路回来，后来直接无响应。
        
        之前系统用fstab外挂了块SSD硬盘，外接USB键盘也无法输入，只能用U盘重刷。
        下好Armbian_23.08.0_amlogic_s905d_lunar_6.1.52_server_2023.09.08.img 做了启动盘，依然无法启动。
        又不想刷回原系统，
        偷了下懒，只好使用原系统Armbian_22.08.0_Aml_s905d_bullseye_5.15.62_server_2022.08.27，直接apt升级了内核，到6.15.2。
        
        设置到EMMC系统启动了
        
        _配置好相关，外接好硬盘，使用rc-local.service设置好硬盘开机启动，随后系统重启，无限重启ing._
        
        目前只能开机后手动插入硬盘再挂载，求解决方法

详细描述问题，并在必要时附上屏幕截图。

重启截图：

https://www.right.com.cn/forum/data/attachment/forum/202309/12/133526g225yzryr1wwytw1.jpg

  外挂硬盘分区信息
  Device         Boot   Start      End  Sectors  Size Id Type
  /dev/mmcblk2p1       139264  1185791  1046528  511M  c W95 FAT32 (LBA)
  /dev/mmcblk2p2      1638400 15269887 13631488  6.5G 83 Linux

           rc-local.service 文件：
          
          Copy
          [Unit]
          Description=/etc/rc.local Compatibility
          ConditionPathExists=/etc/rc.local
          
          [Service]
          Type=forking
          ExecStart=/etc/rc.local start
          TimeoutSec=0
          StandardOutput=tty
          RemainAfterExit=yes
          SysVStartPriority=99
          
          [Install]
          WantedBy=multi-user.target

**Comment by Java2Boy** [comment]
突然用fdisk发现 外挂硬盘上一个分区有Boot标识，服了。取消中。。。应该就OK了

**Comment by Java2Boy** [comment]
问题依旧，只能暂时不手殘，不armbian-update,只要刷入EMMC系统输入这个命令，成功升级后EMMC必崩，无限重启。。。

**Comment by ophub** [comment]
和armbian-update有什么关系呢？把外接硬盘拔了
armbian-update -k 5.15
armbian-update -k 6.1
交替更新一个小时试验上几十次，你看能不能更新。
你外接硬盘的问题不要解释成不能armbian-update

**Comment by Java2Boy** [comment]
服了，看来是硬盘的问题了，有大佬建议换电容或换电源 
离了大谱

**Comment by Java2Boy** [comment]
终结此issue,看来得换硬件了
