### ISSUE TITLE
unt402a的启动与写入emmc

### ISSUE THREAD

**Issue by 88484396** [ophub/amlogic-s9xxx-armbian#1716]
**Device Information | 设备信息**
 - SOC: [e.g. S905l3]
 - Model [e.g. unt402a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

设备是unt402a 2+8，S905L3，emmc。直接用s905l3的固件不能启动，需要我手动把u-boot-p212.bin复制改名成u-boot.ext才能启动，我对照了别人的例子发现别人的是不用这一步操作的，不知道是什么原因？这种启动方式下我尝试写入emmc，这时就无法启动了。尝试了5.15和6.1都是一样的情况。不知这两个问题有没有解决的办法？感谢

**Comment by ophub** [comment]
你在usb时就复制2个，一个.ext,一个.emmc，再写试试

魔百盒花样多，同名不同芯的很多，自己测一下

**Comment by 88484396** [comment]
> 

试完了，还是不行。复制了两个u-boot-p212.bin改名成u-boot.ext和u-boot.emmc，然后在系统写入，关闭再启动就进不去了。
要手动改名uboot是什么原因啊？不知道这跟写入emmc不启动有没有关系？

**Comment by ophub** [comment]
要复制，不要改名。原名u-boot不能没有了。

**Comment by 88484396** [comment]
> 要复制，不要改名。原名u-boot不能没有了。安装/更新等都要用原名的文件

原文件还在的，那个u-boot-p212.bin还在那里，我是复制出来改名然后发现不行的。

**Comment by bwangs** [comment]
我遇到的问题不知道和这个问题是否一样。
刷入EMMC显示是成功的，但启动后在路由器里IP只能出现几秒钟，然后就消失了。不知道哪里出了问题。

**Comment by rodren-lion** [comment]
为什么你门的 402A是 emmc的 我的全是 NAND的。。。

**Comment by GhostLee** [comment]
寄了  我armbian-install之后启动，IP查不到，屏幕不显示，接U盘也不启动了，还没TTL，这咋整
