### ISSUE TITLE
关于X96max+刷入Homeassistant后Armbian 23.8.1 bullseye is not supported!

### ISSUE THREAD

**Issue by c20231015** [ophub/amlogic-s9xxx-armbian#1721]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. x96max+]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.52]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**

Armbian 23.8.1 bullseye 不支持supported
大佬有低于23.8.1版本的Armbian吗？
========================================
root@armbian:~# dpkg -i homeassistant-supervised.deb
Selecting previously unselected package homeassistant-supervised.
(Reading database ... 41997 files and directories currently installed.)
Preparing to unpack homeassistant-supervised.deb ...
[warn] 
[warn] If you want more control over your own system, run
[warn] Home Assistant as a VM or run Home Assistant Core
[warn] via a Docker container.
[warn] 
[error] Armbian 23.8.1 bullseye is not supported!
dpkg: error processing archive homeassistant-supervised.deb (--install):
 new homeassistant-supervised package pre-installation script subprocess returned error exit status 1
[info] Undo divert on abort-install
No diversion 'diversion of /etc/NetworkManager/NetworkManager.conf to /etc/NetworkManager/NetworkManager.conf.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/NetworkManager/system-connections/default to /etc/NetworkManager/system-connections/default.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/docker/daemon.json to /etc/docker/daemon.json.real by homeassistant-supervised', none removed.
No diversion 'diversion of /etc/network/interfaces to /etc/network/interfaces.real by homeassistant-supervised', none removed.
[info] Resetting debconf selections
[info] Removal complete, due to the complexity of this installation method,
[info] you will need to manually remove the containers created by the supervisor
Errors were encountered while processing:
 homeassistant-supervised.deb
=======================================

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
没有
