### ISSUE TITLE
m401a蓝牙启动，无法搜索配对

### ISSUE THREAD

**Issue by SXMB** [ophub/amlogic-s9xxx-armbian#1722]
我使用的是m401a今早刷入最新的镜像，进入armbian-config安装蓝牙，输入systemctl status bluetooth查看蓝牙已经启动，但是输入scan on 却提示上图所示，无法搜索和配对蓝牙设备

**Comment by SXMB** [comment]
![Uploading 9C6AD64D-B2DE-42CA-9B59-4890D67E39F1.png…]()

**Comment by SXMB** [comment]
![71CDF416-04A5-426C-B4B8-807A092A582A](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137496645/fee30fc1-08f6-4c9f-9231-d9794ef29309)
![6378E767-B5B7-44A2-9690-B51F4C89E8F9](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137496645/6579b7c6-3ba0-4ef8-8694-b80b3ce29ac6)

**Comment by SXMB** [comment]
![9AA2D9D4-0D4B-40DC-9478-6F4706666A21](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137496645/31a3f02f-5fcf-41f9-a434-d13b66e08827)
![2C065C06-42C6-4B62-AA1F-0948660AC456](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137496645/11486331-58cc-4042-b9c8-7f3a443444fa)

**Comment by l666l** [comment]
好巧，刚配置出来也是这样，怎么解决，大佬

**Comment by l666l** [comment]
没其他办法了嘛，都配置差不多，不想退回了，G了

**Comment by SXMB** [comment]
我也试过好多次。 你看看这个吧
![Uploading CA65B581-C623-4234-B432-6BEABD0F2335.png…]()

**Comment by SXMB** [comment]
![D2B0734D-02E2-48FF-84AA-6D5084BA3E06](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137496645/c65f738e-709c-4a59-8cc7-ee5e6a08e46d)
你看看这个

**Comment by SXMB** [comment]
https://bbs.hassbian.com/thread-18366-1-1.html
这个是上面的帖子，你研究一下吧。

**Comment by l666l** [comment]
刚找到了这个帖子。主要时间久了，怕对不上

**Comment by l666l** [comment]
话说是不是得在docker中映射蓝牙才能用呀，大佬
