### ISSUE TITLE
Mecool KM9

### ISSUE THREAD

**Issue by citral23** [ophub/amlogic-s9xxx-armbian#1725]
Hello, here is a dts for the mecool KM9 4G/64G/100M

I edited the x96 max dts that has everything working but an error on gigabit ethernet (because there's none) so I just removed it and adjusted the 100M ethernet to point to the correct phy

hdmi works (including sound)
wifi works
eth works
BT works
SD card reader works
usb works

not tested: audio jack

https://pastebin.com/NB2Gt3xh

**Comment by HokaDipe** [comment]
hi sir, I have a hk1 box (1000M ethernet), but it lose connection IP with modem after short time, if I use ethtool to change the lan port to 100 everything works normally. Can you help me fix it
