### ISSUE TITLE
rk3568 (Linkstar H68K) - RTL8211F phy_poll_reset failed

### ISSUE THREAD

**Issue by DrNoCDN** [ophub/amlogic-s9xxx-armbian#1726]
**Device Information | 设备信息**
 - SOC: rk3568
 - Model Linkstar H68K

**Armbian Version | 系统版本**
 - Kernel Version: Linux armbian 6.1.52-ophub #1 SMP Thu Sep  7 03:11:29 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux
 - Release: jammy

**Describe the bug | 问题描述**
dmesg repeatedly logs a phy_poll_reset for the RTL8211F (snippet below).. also provided a couple of other outputs I've seen asked for on other issues.. let me know if there's anything more I need to provide for assistance.. thanks in advance!

[525126.092595] rk_gmac-dwmac fe010000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -110)
[525426.515655] rk_gmac-dwmac fe010000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[525427.143335] RTL8211F Gigabit Ethernet stmmac-1:00: phy_poll_reset failed: -110
[525427.144145] rk_gmac-dwmac fe010000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -110)
[525427.160633] rk_gmac-dwmac fe010000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[525427.787333] RTL8211F Gigabit Ethernet stmmac-1:00: phy_poll_reset failed: -110
[525427.788148] rk_gmac-dwmac fe010000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -110)
[525427.805246] rk_gmac-dwmac fe010000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[525428.439328] RTL8211F Gigabit Ethernet stmmac-1:00: phy_poll_reset failed: -110
[525428.440135] rk_gmac-dwmac fe010000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -110)
[525428.456470] rk_gmac-dwmac fe010000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[525429.091315] RTL8211F Gigabit Ethernet stmmac-1:00: phy_poll_reset failed: -110
[525429.092126] rk_gmac-dwmac fe010000.ethernet eth0: __stmmac_open: Cannot attach to PHY (error: -110)

cat /boot/armbianEnv.txt
verbosity=1
bootlogo=false
fdtfile=rockchip/rk3568-opc-h68k.dtb
rootdev=UUID=0261a2ae-8cfb-4981-b5d6-6278f6f23c2c
rootfstype=ext4
rootflags=rw,errors=remount-ro
overlay_prefix=rk3568
overlays=
extraargs=
extraboardargs=net.ifnames=0 max_loop=128
docker_optimizations=on
usbstoragequirks=0x2537:0x1066:u,0x2537:0x1068:u

cat /etc/ophub-release
PLATFORM='rockchip'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FAMILY='rk3568'
BOARD='h68k'
SOC='rk3568'
FDTFILE='rk3568-opc-h68k.dtb'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='6.1.y'
KERNEL_VERSION='6.1.52'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='armbianEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/bootloader.bin'
TRUST_IMG='/usr/lib/'
PACKAGED_DATE='2023-06-05'

**Comment by ophub** [comment]
Is this a multi-port device? Is it showing this error no matter which port you plug it into? Or is it specific to a particular port? Try installing the latest firmware.

**Comment by DrNoCDN** [comment]
> Is this a multi-port device? Is it showing this error no matter which port you plug it into? Or is it specific to a particular port? Try installing the latest firmware.

Yes, it is multi-port (2x 1g, 2x 2.5g) but I'm currently using the WLAN, so not even plugged into ethernet presently.  Also note that eth1-3 show up correctly in ifconfig, but eth0 is not present (snippet below)... lspci also does not seem to show the RTL8211F at all, just the 2.5g RTL8125's (snippet below)

When you say 'install the latest firmware' can you be more specific?

Thanks for the help!

ifconfig
docker0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 172.31.0.1  netmask 255.255.255.0  broadcast 172.31.0.255
        inet6 fe80::42:14ff:feba:8ed6  prefixlen 64  scopeid 0x20<link>
        ether 02:42:14:ba:8e:d6  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 7  bytes 826 (826.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth1: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether f2:42:2e:22:6f:58  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 71

eth2: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 02:86:9d:b5:ee:58  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 110

eth3: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 0a:ac:b7:cd:cf:27  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 144

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 88  bytes 5896 (5.8 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 88  bytes 5896 (5.8 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

veth23f42f3: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet6 fe80::5c00:83ff:fe71:81b6  prefixlen 64  scopeid 0x20<link>
        ether 5e:00:83:71:81:b6  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 14  bytes 1572 (1.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.193  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::afa1:48f5:6e64:a548  prefixlen 64  scopeid 0x20<link>
        ether 18:ef:3a:cf:6d:37  txqueuelen 1000  (Ethernet)
        RX packets 298985  bytes 87896470 (87.8 MB)
        RX errors 0  dropped 10847  overruns 0  frame 0
        TX packets 2142  bytes 540526 (540.5 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lspci
0000:00:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0000:01:00.0 Network controller: MEDIATEK Corp. MT7921 802.11ax PCI Express Wireless Network Adapter
0001:10:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0001:11:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)
0002:20:00.0 PCI bridge: Rockchip Electronics Co., Ltd RK3568 Remote Signal Processor (rev 01)
0002:21:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8125 2.5GbE Controller (rev 05)

**Comment by DrNoCDN** [comment]
(bump)

Any additional help here?

**Comment by ddscentral** [comment]
What is the reason support for these boxes was removed ?

**Comment by DrNoCDN** [comment]
+1 Would also like to know why the H68K has been dropped from the builds

**Comment by DrNoCDN** [comment]
@ddscentral
> What is the reason support for these boxes was removed ?

FYI - I see that Hinlink support was officially dropped in this commit https://github.com/ophub/amlogic-s9xxx-armbian/commit/2e665a152103a84450a815588729afd69191804f.  I have asked there for a reason for them being dropped (hoping for a reply).

**Comment by ddscentral** [comment]
https://github.com/unifreq/linux-6.1.y/commit/cbd2888a080c9c91fe10d235b8df60358ca5b329
Dropped from kernel as well.

**Comment by ophub** [comment]
The hlink series devices have been re-added.

**Comment by okpapt** [comment]
Hello,

Today, is it possible armbian work very well inside theese Smart TV Box Android 13 RK3528 (aliexpress links):
* [LEMFO HK1RBOX K8S : Dual Wifi BT4.0 4Go+64Go ](https://aliexpress.com/item/1005006422324954.html)
* [Transpeed MX10 : Dual Wifi BT5.0 4Go+128Go ](https://aliexpress.com/item/1005005979031456.html)
* [DQ08 : Dual Wifi BT4.0 4Go+64Go ](https://aliexpress.com/item/1005005875769738.html)
* [ X88 Pro 13 : Dual Wifi BT5.0 4Go+64Go ](https://aliexpress.com/item/1005005992844981.html)
 * [H96 Max : Dual Wifi BT5.0 4Go+64Go ](https://aliexpress.com/item/1005006585157549.html)
* and many others

about RAM : some vendors say 4Go DDR3 and other 4Go DDR4
about memory : some vendors say emmc and other nothing
about BlueTooth : some vendors say 4.0 and other 5.0
about USB : some vendors say 2 x USB 2 and other 1 x UBS 2 + 1 x USB3
about TF : some vendors say 64Go and other 128Go
about clock : some have display and other no display
about ethernet : generaly 100 and few 1000

What change between **5.10.160-rk35xx-flippy-2403b.tar.gz** 79.6MB 08 Mars 2024 and **5.10.160.tar.gz** 90.7MB 13 April 2024 ?

If you need buy one, what is your choice and why ?
Thank you.

**Comment by fari2000** [comment]
Hello
I have got this box [LEMFO HK1RBOX K8S : Dual Wifi BT4.0 4Go+64Go]
Which image should I use and what does work (e.g. ethernet, wifi, emmc boot etc)?
Thanks for  your reply

**Comment by fari2000** [comment]
Hi Okpapt!

Thansk for your reply!

I could flash an img, which could boot, but I had no ethernet or wifi working.

> Hello Farid, Because nobody answer me, I do not bought tv box having rk3568 cpu. Install AIDA64 on your android tv box and collect technicals informations. This can help you to find solution. I cannot help you more. Sorry. If you want try something, be carefull, make backup of original firmware. Take many notes about what you do... Good luck.

**Comment by RopoTrop** [comment]
Hello, 

This is a very interesting question you ask, and I think there are many of us that want to buy a box with ready image. Unfortunately most of us are not linux savvy, and we can't contribute much to building such image and help the author of this development effort. Knowledge and time is needed for extracting stuff like DTB, compiling drivers, trying and debugging kernels, etc. etc. What I am saying if one needs funcional box, one needs to chose box from the supported list. There are not many such boxes with RK3528, only the H96-Max-M2. It's a RK3528 box that is more expensive than the ones from your list below, but as far as it's thread states - it should work right out of box so to say (and I guess it's more expensive specifically for that same reason). Of course, you still need to know how to work with the right software to put the image in there.

Sorry for the offtopic post, I guess separate thread would be more appropriate.

Best Regards to everybody


> Hello,
> 
> Today, is it possible armbian work very well inside theese Smart TV Box Android 13 RK3528 (aliexpress links):
> 
> * [LEMFO HK1RBOX K8S : Dual Wifi BT4.0 4Go+64Go ](https://aliexpress.com/item/1005006422324954.html)
> * [Transpeed MX10 : Dual Wifi BT5.0 4Go+128Go ](https://aliexpress.com/item/1005005979031456.html)
> * [DQ08 : Dual Wifi BT4.0 4Go+64Go ](https://aliexpress.com/item/1005005875769738.html)
> * [ X88 Pro 13 : Dual Wifi BT5.0 4Go+64Go ](https://aliexpress.com/item/1005005992844981.html)
> * [H96 Max : Dual Wifi BT5.0 4Go+64Go ](https://aliexpress.com/item/1005006585157549.html)
> * and many others
> 
> What change between **5.10.160-rk35xx-flippy-2403b.tar.gz** 79.6MB 08 Mars 2024 and **5.10.160.tar.gz** 90.7MB 13 April 2024 ?
> 
> **If you need buy one, what is your choice and why** ? Thank you.

**Comment by ophub** [comment]
<img width="609" height="861" alt="Image" src="https://github.com/user-attachments/assets/e8ac616f-c54b-49f8-863c-56d5ee119926" />

**Comment by VanHerckArnaud** [comment]
> <img alt="Image" width="609" height="861" src="https://private-user-images.githubusercontent.com/68696949/513753191-e8ac616f-c54b-49f8-863c-56d5ee119926.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjMzNzcyOTQsIm5iZiI6MTc2MzM3Njk5NCwicGF0aCI6Ii82ODY5Njk0OS81MTM3NTMxOTEtZThhYzYxNmYtYzU0Yi00OWY4LTg2M2MtNTZkNWVlMTE5OTI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTExMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMTE3VDEwNTYzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmOTUyOGM0NGZhNzVkZGYxOGEzZGVlNTU5NDFlNDRmMDMxZTExN2JhYzg4MzMzNDBiYTJiYTUwMWJjMDg4ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pPvhnLKdgSVG2XbcNP1ODM1m5TE9-5drHMhytHCYAbg">

Hi, I was wondering what steps you took and what images you used to get armbian installed on your device? I've been trying to flash Armbian, e.g. `Armbian_25.5.1_Rock64_bookworm_current_6.12.28_minimal` but I am always getting an error: Firmware loading failed. Invalid tag of firmware. please check firmware.
