### ISSUE TITLE
写入eMMC变砖

### ISSUE THREAD

**Issue by lvmoe** [ophub/amlogic-s9xxx-armbian#173]
章鱼星球
Armbian_22.05.0_Aml_s912_focal_5.15.28_2022.03.15.1315.img.gz
u盘启动成功，使用armbian-install写入eMMC，选择201章鱼星球
刷入成功，按提示1.拔掉usb 2.重插电源
变砖，无法进入系统，也无法重刷armbian（用img重新制作了usb）

**Comment by ophub** [comment]
章鱼没有主线u-boot，应该不会砖吧。重新插U盘应该可以从U盘启动。
你之前里面是什么系统？如果是ce，le等系统，建议先刷回安卓原TV系统，恢复分区信息后再刷armbian

**Comment by lvmoe** [comment]
之前装的openwrt，通过u盘启动的，没有写入eMMC

**Comment by ophub** [comment]
显示器输出什么，卡哪步了

**Comment by lvmoe** [comment]
1080的显示器，完全黑屏

**Comment by lvmoe** [comment]
> 1080的显示器，完全黑屏

现在的情况是，无法进入系统，也无法按照首次刷armbian的方式重刷（用img重新制作了usb）

**Comment by ophub** [comment]
那只能短接救砖了

**Comment by lvmoe** [comment]
是的，我准备这么做，但在此之前我准备尝试一下线刷

**Comment by lvmoe** [comment]
> 是的，我准备这么做，但在此之前我准备尝试一下线刷

我做完各种尝试后，找到解决方案后，再关issue吧

**Comment by lvmoe** [comment]
线刷了atv进去，可以正常开机了，后续继续尝试刷armbian

**Comment by ophub** [comment]
下载今天的固件刷入试试

**Comment by hnewcity** [comment]
> 线刷了atv进去，可以正常开机了，后续继续尝试刷armbian

同变砖，想请教一下不短接怎么线刷呀

**Comment by lvmoe** [comment]
> > 线刷了atv进去，可以正常开机了，后续继续尝试刷armbian
> 
> 同变砖，想请教一下不短接怎么线刷呀
> 

1.我的章鱼星球和现在在网上广泛流传的章鱼星球短接教程的板子不是一样，所以我没有进行短接操作
2.使用usb burning tool(version 2.x.x)直接进行了线刷
3.线刷无法直接刷armbian，先刷一个安卓系统（atv）开启u盘启动
4.u盘启动armbian，armbian-install刷入eMMC

**Comment by lvmoe** [comment]
> 下载今天的固件刷入试试

一次成功了，3.17的版本

**Comment by ophub** [comment]
你这次安装的是哪个内核版本的armbian系统？支持5.15的内核吧？

**Comment by lvmoe** [comment]
> 你这次安装的是哪个内核版本的armbian系统？支持5.15的内核吧？

Welcome to Armbian 22.05.0-trunk Focal with Linux 5.15.29-flippy-71+
