### ISSUE TITLE
E900V22C写入emmc报错

### ISSUE THREAD

**Issue by Pulset** [ophub/amlogic-s9xxx-armbian#1730]
**Device Information | 设备信息**
 - SOC: [S905L3A]
 - Model [E900V22C]

**Armbian Version | 系统版本**
 - Kernel Version: [lunar_6.1.52]
 - Release: [Armbian_23.08.0_amlogic_s905l3a_lunar_6.1.52_server_2023.09.12]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
E900V22C写入emmc报错。
<img width="780" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/21022593/8e3e38f4-bbcd-4d12-bbac-d42e5ac5c1ab">

**Comment by ophub** [comment]
nand的不支持写入emmc
但是我看你可以dd备份bootloader，所以应该是emmc，一些魔百和的设备不降低频率不能正常读写，反编译调整dtb的方法在文档里。

**Comment by Pulset** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1070
我参考这个已经解决，不过之前的文档没找到
