### ISSUE TITLE
请求适配机器[rocktech-mpc1911]有fdt

### ISSUE THREAD

**Issue by 1qingfeng-1** [ophub/amlogic-s9xxx-armbian#1733]
设备信息 
SOC： [RK3399]
型号： [MPC1911]

规格参数
https://www.rockemb.com/armgongkongji/PK3399pingtai/15.html

dtb文件：有原始的/sys/firmware/fdt， 不过可以通过Linux源码带的dtc反编译出dtb，dts
https://github.com/1qingfeng-1/mpc1911-fdt/blob/main/mpc-1911.fdt

uboot可以沿用MPC1903的
https://github.com/Lollipop907/armbian-build/blob/0ecc9cef7e3776ede10763db4d30643f01e9b850/patch/u-boot/u-boot-rockchip64/add-board-mpc1903.patch

希望大佬帮忙适配一个包，这边全力配合测试。

**Comment by ophub** [comment]
https://github.com/coolsnowwolf/lede/blob/master/package/boot/uboot-rockchip/patches/307-rockchip-rk3399-Add-support-for-Rocktech-MPC1903.patch

你发的u-boot无法编辑，我使用的大雕的这个。
jammy里编译了一个测试版，你试试。

**Comment by 1qingfeng-1** [comment]
晚上我回去试试，感谢OP

**Comment by 1qingfeng-1** [comment]
固件升级-->选择固件，无法打开
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33478786/5b9fc384-6c25-4ddf-bc6f-b1c0372debbd)
如果使用下载镜像，请教一下OP，`uboot.bim`，`spi_load.bin` ，和`armbian*.img`的烧写地址如何确认，我是第一次接触MPC1911，不熟悉。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33478786/bc523da2-9e17-438a-b045-761ec7f083c1)

**Comment by ophub** [comment]
没有发现设备

**Comment by 1qingfeng-1** [comment]
短接HDMI附近的暴露的金属触点，RkDev提示发现了一个`MaskRom`设备，我疑惑的是如何烧写OP提供的 `jammy里编译了一个测试版` [link](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.09/Armbian_23.08.0_rockchip_mpc1903_jammy_6.1.53_server_2023.09.18.img.gz) 的img文件。在RkDev中固件升级提示 **无法加载固件**，需要帮助。

**Comment by 1qingfeng-1** [comment]
短接HDMI附近的暴露的金属触点，RkDev提示发现了一个`MaskRom`设备，我疑惑的是如何烧写OP提供的 `jammy里编译了一个测试版` [link](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.09/Armbian_23.08.0_rockchip_mpc1903_jammy_6.1.53_server_2023.09.18.img.gz) 的img文件。在RkDev中固件升级提示 **无法加载固件**，需要帮助。

**Comment by ophub** [comment]
下载镜像，选择loader和img，写入即可

**Comment by 67113513** [comment]
我下载了这个img文件：Armbian_23.5.0-trunk.194_Orangepi-rk3399_bookworm_edge_6.4.11_xfce_desktop.img，刷到1911后hdmi能进桌面，给大佬参考。

**Comment by 67113513** [comment]
> https://github.com/coolsnowwolf/lede/blob/master/package/boot/uboot-rockchip/patches/307-rockchip-rk3399-Add-support-for-Rocktech-MPC1903.patch
> 
> 你发的u-boot无法编辑，我使用的大雕的这个。 jammy里编译了一个测试版，你试试。
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.09/Armbian_23.08.0_rockchip_mpc1903_jammy_6.1.53_server_2023.09.18.img.gz

测试过这个img，下载成功之后重新插电、hdmi黑屏没有输出，插上usb键盘num lock灯不亮。
我用的oraclepi的镜像有hdmi输出，在这里可下载，链接：https://pan.baidu.com/s/1JWCqosnOwDhAT-42oLhZWQ 
提取码：2lye
分享的目录里还有原厂的ubuntu16提取的dmesg启动信息和gpio等。能否参考做个armbian和op的版本

**Comment by ophub** [comment]
@67113513 我更新了u-boot，使用的你测试过的 Armbian_2022.11-ZXIE_Orangepi-rk3399_lunar_edge_6.5.4_minimal.img 的u-boot。
dtb使用的是哪个文件呢？

**Comment by 67113513** [comment]
> @67113513 我更新了u-boot，使用的你测试过的 Armbian_2022.11-ZXIE_Orangepi-rk3399_lunar_edge_6.5.4_minimal.img 的u-boot。 dtb使用的是哪个文件呢？ `cat /proc/device-tree/compatible`
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.09/Armbian_23.08.0_rockchip_mpc1903_jammy_6.1.54_server_2023.09.22.img.gz
> 
> 下载这个测试下，换了u-boot但是没换dtb，看看能不能启动。

好的，1911丢在单位了，周一去测试一下。
