### ISSUE TITLE
HK1 BOX lose IP connection with lan 1000 after short time

### ISSUE THREAD

**Issue by HokaDiep** [ophub/amlogic-s9xxx-armbian#1736]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.52]
 - Release: [e.g. Bookworm]

**Describe the bug | 问题描述**

Hi guys, i have a hk1 box with 1Gb Lan. I installed armbian (bookworm + kernel 6.1.52) in emmc. My box will lose IP connection to the modem after a short time if it works with lan port 1000, if I use ethtool to change the lan port to 100 everything works normally.

**Comment by ophub** [comment]
cat /boot/uEnv.txt
cat /etc/ophub-release

**Comment by HokaDipe** [comment]
> cat /boot/uEnv.txt cat /etc/ophub-release

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137959211/0ebf7d9d-8285-4a51-8cd9-f564ff4cd921)

**Comment by HokaDiep** [comment]
bullseye + kernel 5.4 fixed
