### ISSUE TITLE
Create a bootable SDcard from Armbian-DDBR backup image

### ISSUE THREAD

**Issue by grndis** [ophub/amlogic-s9xxx-armbian#1737]
Hello, I have a question. I installed Armbian on eMMC and backed it up to a bootable SD card using the `armbian-ddbr` command. The resulting image is called `BACKUP-arm-64-emmc.img.gz`.

I seamlessly restored this image to another machine using `armbian-ddbr` so the new machine now has the same configuration as the other one.

Now, my question is: how can I create a bootable SD card from `BACKUP-arm-64-emmc.img.gz`? I've tried burning it to an SD card, but it failed to boot. It seems that the boot file is different. Is there any modification I can make to enable it to boot from the SD card using `BACKUP-arm-64-emmc.img.gz`? 

Thank you.

**Comment by ophub** [comment]
The backup is the emmc partition and can only be used in emmc.

**Comment by grndis** [comment]
ok, thank you 👍
