### ISSUE TITLE
[求助] EMMC有坏块

### ISSUE THREAD

**Issue by jackcctse** [ophub/amlogic-s9xxx-armbian#1738]
盒子是MGV3000, 但应该不重要。刷了armbian在做服务器, 稳定运行4个月, 之后开始随机死机。有时是几天一次, 有时十多天, 必然死掉一次, 需要重开机。

重新查看设定, 发现不小心将iptables的log写入到EMMC了。虽然是先填满内存再rotate写入EMMC, 但还是很频密。估计EMMC有坏块了。

请问有什么检测EMMC坏块吗? 怎样屏蔽这些坏块?

目前已停止iptables那个log, 十多天了似乎没事。

**Comment by ophub** [comment]
```
sudo apt update
sudo apt install smartmontools
sudo smartctl -a /dev/mmcblkX
```

这会显示与 eMMC 相关的 SMART 属性和统计信息。你可以检查 Reallocated_Sector_Ct 和 Uncorrectable_Sector_Ct 这两个值来了解有关重新分配和无法纠正的扇区数量。
Reallocated_Sector_Ct 表示已经重新分配的坏块数。
Uncorrectable_Sector_Ct 表示无法被纠正的坏块数。
如果这些值不为零，那么可能存在坏块。

**Comment by sstutu** [comment]
docker  /var/lib/docker  软连到u盘 ，这两天一直会过会出现文件系统只读
怎么解决，好像跑题了。

**Comment by jackcctse** [comment]
smartctl好像不支持emmc

sudo smartctl -a /dev/mmcblk2
```smartctl 7.2 2020-12-30 r5155 [aarch64-linux-5.15.118-ophub] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

/dev/mmcblk2: Unable to detect device type
Please specify device type with the -d option.

Use smartctl -h to get a usage summary
```
sudo smartctl -d
```smartctl 7.2 2020-12-30 r5155 [aarch64-linux-5.15.118-ophub] (local build)
Copyright (C) 2002-20, Bruce Allen, Christian Franke, www.smartmontools.org

=======> ARGUMENT REQUIRED FOR OPTION: d
=======> VALID ARGUMENTS ARE: ata, scsi[+TYPE], nvme[,NSID], sat[,auto][,N][+TYPE], usbcypress[,X], usbjmicron[,p][,x][,N], usbprolific, usbsunplus, sntjmicron[,NSID], sntrealtek, intelliprop,N[+TYPE], jmb39x[-q],N[,sLBA][,force][+TYPE], jms56x,N[,sLBA][,force][+TYPE], marvell, areca,N/E, 3ware,N, hpt,L/M/N, megaraid,N, aacraid,H,L,ID, cciss,N, auto, test <=======```

**Comment by jackcctse** [comment]
另外我也试了mmc-utils，但没有很有用的信息。
`eMMC Life Time Estimation A [EXT_CSD_DEVICE_LIFE_TIME_EST_TYP_A]: 0x01`
`eMMC Life Time Estimation B [EXT_CSD_DEVICE_LIFE_TIME_EST_TYP_B]: 0x01`

**Comment by changxiangzhong** [comment]
有没有以下寄存器？
···
   cat /sys/class/mmc_host/mmc0/mmc0\:0001/pre_eol_info
   cat /sys/class/mmc_host/mmc0/mmc0\:0001/life_time
···
我在一些android firmware上试过，是可以读出emmc health的。参考https://wiki.friendlyelec.com/wiki/index.php/EMMC

P.S.我是新手armbian玩家。

**Comment by jackcctse** [comment]
沒有呢。mmc0下面只有这些。

`$ ls /sys/class/mmc_host/mmc0`
`device  power  subsystem  uevent`
