### ISSUE TITLE
Problem booting armbian x96_max_plus_ai.

### ISSUE THREAD

**Issue by viperultra** [ophub/amlogic-s9xxx-armbian#1739]
Hello everyone and wanna say firstly thank so much for ur amazing job.So i have x96_max_plus_ai with wifi module am7256 and with Ethernet controller IP1001M.I flashed sd card with  Armbian_23.08.0_amlogic_s905x3_bullseye_5.15.132_server_2023.09.21.img and tried meson-sm1-x96-max-plus-ip1001m.dtb and meson-sm1-sei610.dtb and it didn't work.I inserted sd card to sd slot power on then it's just booting to android if use toothpick it's just loading to recovery but as i understand after insterting sd card and just power on it should load armbian.
![Screenshot_20230922-192558](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33460694/4c41218c-d1d4-46ba-b3f4-04cc82dd50d8)

![IMG_20230922_220237_618](https://github.com/ophub/amlogic-s9xxx-armbian/assets/33460694/4f158689-7d33-47ed-8e6d-d1c4b56a1662)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

**Comment by viperultra** [comment]
so i need manually create new dtb file

**Comment by ophub** [comment]
Reading 12.4

**Comment by viperultra** [comment]
tested,just loading to recovery and don't do anything

**Comment by viperultra** [comment]
Okay i did all from scratch without changin manually any DTB files and used USB sd card reader and it's booted.Finally.
