### ISSUE TITLE
X96 Max PlusQ1 eth0 not working

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#174]
My board  

-CPU: Amlogic S905X3 quad-core ARM Cortex A55; -GPU: ARM Mali-G31MP; - OS: Android 9.0; - Memory: DDR3 4GB, FLASH 32/64GB/128GB;

Without chip 1000Mb. LAN 100, Cdtech 4761743 radio module and two antennas

hello friends I'm using this build of armbian https://github.com/ophub/amlogic-s9xxx-armbian using kernel 5.15.28, put the dtb meson-sm1-sei610.dtb (FDT /dtb/amlogic/meson-sm1 - sei610.dtb which corresponds to my box because this build Armbian_20.10_Arm-64_buster_current_5.9.0.img works), I boot from Pen everything works (it boots and I have eth0) but when I transfer to emc using script (https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build -armbian/ common-files/files/usr/sbin/armbian-install) Then I restart the box and the error eth0 appears and I no longer have IP What will my problem be?

**Please do not close the topic until it is resolved.**

![21842142](https://user-images.githubusercontent.com/83761813/158602901-19ddc7d1-05ea-4fa6-9c72-08db99e0d844.jpg)
![IMG_20210109_154247](https://user-images.githubusercontent.com/83761813/158602905-419853b1-a240-4de9-b556-47d5be7bdc5c.jpg)
![IMG_20220315_221213-min](https://user-images.githubusercontent.com/83761813/158602908-a565fb3a-099b-4fb9-bc88-0722ead6c01b.jpg)
![IMG_20220315_222351-min](https://user-images.githubusercontent.com/83761813/158602919-2ee1d73c-a281-4028-80f8-0cdb80d09fb0.jpg)

**Comment by ophub** [comment]
The kernel version of 5.9.0 is quite different from that of 5.15.28, and the dtb file is not necessarily universal. The dtb of meson-sm1-sei610.dtb is available in all versions of the kernel. Can you use the dtb of the current kernel directly?

**Comment by tv4you2016** [comment]
with this one it works. (https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_03.17.1008/Armbian_22.05.0_Aml_s905x3_focal_5.4.185_2022.03.17.0917.img.gz)

I don't understand one thing.

The reason why this error only happens when after switching to emmc..
it's when I create the img the first time and put the setting everything works correctly

**Comment by tv4you2016** [comment]
kernel setting export (zcat /proc/config.gz > running.config)
[running.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8289608/running.txt)

**Comment by ophub** [comment]
> with this one it works. (https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_03.17.1008/Armbian_22.05.0_Aml_s905x3_focal_5.4.185_2022.03.17.0917.img.gz)

```
999:X96 Max Plus Q1:s905x3:meson-sm1-x96-max-plus-100m.dtb:u-boot-x96maxplus.bin:NA:NA:4C@2100Mhz,2GB Mem,100Mb Nic,Wifi
```

**Comment by tv4you2016** [comment]
I think there's something I'm not getting.
The installation pen works fine (with this dtb meson-sm1-sei610.dtb) until the moment of installing in emmc.
when I pass the emmc and the eth0 error appears

this img is already when booted by emmc

![158602908-a565fb3a-099b-4fb9-bc88-0722ead6c01b](https://user-images.githubusercontent.com/83761813/158973250-db0c5fd7-53cc-4ef7-94b6-382e5cd6f7cc.jpg)

**Comment by ophub** [comment]
You said earlier that using the default firmware works fine on USB, the DTB that works fine is meson-sm1-x96-max-plus-100m.dtb, not the meson-sm1-sei610.dtb you have been clinging to.
Since you have used the default firmware on USB and it can be used normally, then use meson-sm1-x96-max-plus-100m.dtb, no matter what dtb you have used in other firmware before, your current test results shall prevail.

**Comment by tv4you2016** [comment]
my x96 box only works when I select the dtb meson-sm1-sei610.dtb.
all other dtb's always give eth0 error.

**Comment by ophub** [comment]
Add your own personalized installation configuration in `/usr/sbin/armbian-install`
```
999:X96 Max Plus Q1:s905x3: meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:NA:NA:4C@2100Mhz,2GB Mem,100Mb Nic,Wifi
```
