### ISSUE TITLE
Installing Armbian on X96 (s905x) on emmc

### ISSUE THREAD

**Issue by egorm2005** [ophub/amlogic-s9xxx-armbian#1742]
**Device Information | 设备信息**
 - SOC: [s905x]
 - Model [X96 TV box with 2GB of memory and 16GB of storage]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.132]
 - Release: [Armbian_23.08.0_amlogic_s905x-t95_lunar_5.15.132_server_2023.09.21]

**Describe the bug | 问题描述**
Hi, please help me install Armbian.
I downloaded the image, wrote it to the SD card and successfully booted using the toothpick method.

Booting from the SD card is successful, everything works fine. When I try to install Armbian on emmc the installation just stops. If you cancel the installation (ctrl + c), the system continues to work normally.
I also tried using the image Armbian_23.08.0_amlogic_s905x-t95_lunar_6.1.52_server_2023.09.12.
To install, I used the commands 
`armbian-install` 
and 
`armbian-install -m yes -a no`
I chose all possible DTB options for the s905x.
It's always the same. The installation just stops (in the picture).
Android boots successfully without an SD card.

![IMG_20230925_203041](https://github.com/ophub/amlogic-s9xxx-armbian/assets/146020047/fa968645-8e76-422d-8021-75e215f5a502)

**Comment by ophub** [comment]
lsblk

**Comment by egorm2005** [comment]
Sorry for the wait.
```
root@armbian:~# lsblk
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
mmcblk1      179:0    0  7.5G  0 disk
├─mmcblk1p1  179:1    0  255M  0 part /boot
└─mmcblk1p2  179:2    0  7.3G  0 part /var/log.hdd
                                      /
mmcblk2      179:32   0 14.6G  0 disk
├─mmcblk2p1  179:33   0    4M  0 part
├─mmcblk2p2  179:34   0   64M  0 part
├─mmcblk2p3  179:35   0  512M  0 part
├─mmcblk2p4  179:36   0    1K  0 part
├─mmcblk2p5  179:37   0    8M  0 part
├─mmcblk2p6  179:38   0   32M  0 part
├─mmcblk2p7  179:39   0   32M  0 part
├─mmcblk2p8  179:40   0    8M  0 part
├─mmcblk2p9  179:41   0    8M  0 part
├─mmcblk2p10 179:42   0   32M  0 part
├─mmcblk2p11 179:43   0   32M  0 part
├─mmcblk2p12 179:44   0  512M  0 part
├─mmcblk2p13 179:45   0   32M  0 part
├─mmcblk2p14 179:46   0  1.5G  0 part
└─mmcblk2p15 179:47   0 11.7G  0 part
mmcblk2boot0 179:64   0    4M  1 disk
mmcblk2boot1 179:96   0    4M  1 disk
zram0        254:0    0  905M  0 disk [SWAP]
zram1        254:1    0   50M  0 disk /var/log
zram2        254:2    0    0B  0 disk
```

**Comment by egorm2005** [comment]
The problem is still relevant.

**Comment by doublebstyle** [comment]
exactly same here
