### ISSUE TITLE
插入 ext4 移动硬盘后，设备在启动阶段循环重启

### ISSUE THREAD

**Issue by cherinyy** [ophub/amlogic-s9xxx-armbian#1745]
为了方便权限管理，我在斐讯 N1（Armbian 23.08.0 Bookworm）上使用 `fdisk` 和 `mkfs.ext4` 将希捷 1D6AP1-500 移动硬盘格式化为单个 ext4 分区。

但是重启后设备无法正常启动，我注意到移动硬盘似乎会隔一段时间重启，怀疑斐讯 N1 在启动阶段循环重启，而没有成功进入系统。

这种情况应该怎么解决呢？修改 `uEnv.txt` 的启动参数吗？

**Comment by cherinyy** [comment]
算了放弃了，在 Windows 上格式化为 NTFS 分区将就用着。

**Comment by 837468220** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1220#issuecomment-1788326917
试试这个呢
不知道还有么有什么好办法
