### ISSUE TITLE
No boot on beelink GTking S922

### ISSUE THREAD

**Issue by gorotman** [ophub/amlogic-s9xxx-armbian#1747]
**Device Information | 设备信息**
 - SOC: S922X
 - Model: Beelink GT King

Hi all.
This is first installation of armbian, and I'm tryng to install armbian on a beelink gtking that use a S922 chip.
I followed these steps:
1- flash Armbian_23.08.0_amlogic_s922x_lunar_6.1.54_server_2023.09.21.img.gz on my usb pendrive using BalenaEtcher
2- rename u-boot-gtking.bin to u-boot.ext on root folder
3- edit uEnv.txt as follow
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-g12b-gtking.dtb
APPEND root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0

I try to reboot with toothpick.
The android box starts but it shows the beelink initial logo and no more...no startup script...no errors....nothing....waited minutes but nothing.
Tried different tdbs, tried u-boot-s905x2-s922, renamed u-boot.usb also. Always got the beelink screenshot only.
When I remove the usb pendrive, it starts with original android and works properly.

Any help please? what's wrong?

thanks

**Comment by ophub** [comment]
Use the 5.15 default firmware and do not modify it.

**Comment by gorotman** [comment]
Do you mean  Armbian_23.08.0_amlogic_s922x_lunar_5.15.132_server_2023.09.21.img.gz ?
there are much versions for every chip,  named ..._lunar_ ... and ..._reva_lunar_ ... and ..._ct2000_lunar_ ... what are differences?

thanks

**Comment by ophub** [comment]
amlogic_s922x_lunar_5.15.132

**Comment by gorotman** [comment]
done, but unsuccessfully.
Burned on usb pendrive, any files edited. Rebooted the tvbox then: beelink logo for 4-5s, black screen 1-2s, device halted.
No messages, no errors on the screen.
Tried many times, same behavior. Without the pendrive, device start vendor firmware correctly.
