### ISSUE TITLE
Got error:  [ ERROR ] Internal eMMC storage was't found in this device!

### ISSUE THREAD

**Issue by brotherblackdog** [ophub/amlogic-s9xxx-armbian#1748]
**Device Information | 设备信息**
 - SOC:  S905L3
 - Model: M411A

**Armbian Version | 系统版本**
 - Kernel Version: Armbian_23.08.0_amlogic_s905l3_lunar_6.1.54_server_2023.09.20

**Describe the bug | 问题描述**
拆外壳确认是 S905L3，线刷 android_tv_m411a_s905L3.tar.xz 成功后，正常进入HarmonyOS，进入安卓设置，安全设置，开启 ADB。ADB连入后，下命令 reboot update，插入Armbian_23.08.0_amlogic_s905l3_lunar_6.1.54_server_2023.09.20 U盘。HDMI 黑屏无信号，约90秒后，可 SSH 登入。
设置了密码、语言时区之后，下命令 armbian-install 或 -m yes -a yes 都一样

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/12568379/24897caf-3b04-4981-96f1-823c73a32754)
试了3次，都会得到 [ ERROR ] Internal eMMC storage was't found in this device!

**Comment by ophub** [comment]
nand不支持写入

**Comment by any35** [comment]
是kernel版本的问题，有的版本会有这个问题，换个内核版本就好了

**Comment by cjz9032** [comment]
> 是kernel版本的问题，有的版本会有这个问题，换个内核版本就好了

这么神奇
