### ISSUE TITLE
找不到与盒子对应的系统包

### ISSUE THREAD

**Issue by liedou** [ophub/amlogic-s9xxx-armbian#1749]
**Device Information | 设备信息**
 - SoC: 晶晨 S905L3
 - 型号: UNT403A
![IMG_20230930_150416](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75432864/c76f6986-d42d-46f5-b101-a7f0c47a972e)
![IMG_20230930_150448](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75432864/1596b454-a1f7-4a0a-b65f-b7988317be62)

**Describe the bug | 问题描述**
我下载了**[Armbian_23.08.0_amlogic_s905l3_bullseye_6.1.54_server_2023.09.20.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.09/Armbian_23.08.0_amlogic_s905l3_bullseye_6.1.54_server_2023.09.20.img.gz)**，然后用rufus刻录到U盘。让盒子通过U盘启动，HDMI黑屏，但是可以连上ssh，简单配置完用户密码之后运行`armbian-install`，但不知道选哪一个。。README中的和我的好像不太一样。。列表中UNT403A对应的是S905l3a，但我的是s905l3
![Snipaste_2023-09-30_15-19-41](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75432864/f7b4c15d-71f6-44cf-ab22-bda409614c46)

**Comment by ophub** [comment]
参照表，找到同一个通用的。

**Comment by liedou** [comment]
成功了，感谢！![Screenshot_2023-09-30-21-37-15-080_com.termux.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75432864/03de3d6f-eb66-4916-b27e-494e32ab93c8)

**Comment by liedou** [comment]
成功了，感谢！![IMG_20230930_214311.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75432864/8cb1f797-832c-4d1c-849e-0b4a383f8026)
