### ISSUE TITLE
Am6b plus

### ISSUE THREAD

**Issue by ddams2000** [ophub/amlogic-s9xxx-armbian#175]
Hello, I'm trying to install armbian on emmc, but it's difficult :) . when i launch armbian-install i have several .dtb to choose from, but the one i need am6B is not in this list. when I put 0 to import my dtb file I don't know what to put (I tried "meson-g12b-ugoos-am6B-plus.dtb" but it didn't work) ? if someone could help me? thank you

**Comment by tv4you2016** [comment]
This is the list of available dtb:
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/amlogic-dtb,
Is your dtb available here?

**Comment by ddams2000** [comment]
no, but in lastest bulleyes image there is ugoos-am6b-plus-oc.dtb in dtb drawer. unfortunately the sound is not recognized, and I can't install it. When I use the script/program(?) armbian-install, I have a choice among about twenty dtb files but I don't know how to put mine? if I choose the only ugoos-am6.dtb proposed, the installation goes well but on reboot I have a boot loop with lots of errors.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/9783b937c0dc55cc77fac3d01d55039486819066/build-armbian/common-files/files/usr/sbin/armbian-install#L106

Does this not apply to your device? Send specific information about your device:
soc, wired network card chip code, wireless network card chip code

**Comment by ddams2000** [comment]
Hello, thank you for taking your time to help me.
Ugoos am6b plus
soc: s922-xj (4 x a73@2.2Ghz + 2 x a53@1.8Ghz)
wired network: RTL8211F_gigabit_ethernet
wireless network card: brcm43752 (chipset ampack 6275s)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_03.18.1606/Armbian_22.05.0_Aml_s922x-reva_focal_5.4.185_2022.03.18.1452.img.gz

**Comment by ddams2000** [comment]
I wanted to ask you what is the difference between the normal version and the reva_ version?

**Comment by ophub** [comment]
There are quite a few variants, using different chips. If there is no driver in the mainline kernel, it cannot be used (Android drivers cannot be used in the mainline kernel)

**Comment by ddams2000** [comment]
can i test lastest reva_debian instead focal_reva it s same ?

**Comment by ophub** [comment]
Different branches can be tested on the usb with the firmware of the 5.4 kernel

**Comment by ophub** [comment]
What configuration did your device test work with?
dtb, u-boot, kernel?

**Comment by ddams2000** [comment]
actually i'am running Armbian_22.05.0_Aml_s922x_focal_5.15.29_2022.03.18.1438.img.gz 
dtb: meson-g12b-ugoos-am6b-plus-oc.dtb
u-boot: gtking-pro.bin
kernel. 5.15.29-flippy-71+
compare to the manjaro arm version, here I have the 2560x1440p (manjaro its 1080p max), the correct processor frequencies (manjaro not) but the audio does not work (with manjaro it works) and impossible to install on emmc (with manjaro it works well)

**Comment by ophub** [comment]
![Snip20220318_1](https://user-images.githubusercontent.com/68696949/159013373-b59aa3ea-a9a1-4014-8c6e-464fc98c0f94.png)

**Comment by ddams2000** [comment]
sorry but what should i understand ?

**Comment by ophub** [comment]
These are the am6b devices supported by the mainline kernel, you can test which one suits you better

**Comment by ddams2000** [comment]
once again thanks for the help, so if i want install Armbian_22.05.0_Aml_s922x-reva_bullseye_5.15.29_2022.03.18.1449.img.gz on emmc how should i do please ?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#install-armbian-to-emmc

**Comment by ophub** [comment]
/usr/sbin/armbian-install
add your info

**Comment by ddams2000** [comment]
hi, sorry but once installed it looks like this:
![IMG_20220318_153810](https://user-images.githubusercontent.com/101818343/159120020-987e6ddd-d616-47c6-b1e5-525406faec02.jpg)

**Comment by ophub** [comment]
Did you test it on USB and it works fine?

**Comment by ddams2000** [comment]
Yes, work on µsd

**Comment by ophub** [comment]
/usr/sbin/armbian-install
add your info

https://github.com/ophub/amlogic-s9xxx-armbian/blob/96280261b0e3726574eff8939e00b0e7eb9afaa0/build-armbian/common-files/files/usr/sbin/armbian-install#L106

```
999:UGOOS AM6 Plus:s922x:meson-g12b-ugoos-am6.dtb:u-boot-gtkingpro.bin:NA:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Nic,brcm4398 wifi
```

Delete the main-line U-BOOT, and modify the DTB to the file you use in the USB.

**Comment by ddams2000** [comment]
sorry, but what did you mean by erase main-line U-BOOT ?
![IMG_20220319_143608](https://user-images.githubusercontent.com/101818343/159123580-f038e2ba-690e-4c44-90e2-37c8b36eb226.jpg)

**Comment by ophub** [comment]
add your info, such as:

`vi /usr/sbin/armbian-install`

```
999:UGOOS AM6 Plus:s922x:meson-g12b-ugoos-am6.dtb:u-boot-gtkingpro.bin:NA:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Nic,brcm4398 wifi
```

**Comment by ddams2000** [comment]
like that ?
![Capture d’écran_2022-03-19_16-54-04](https://user-images.githubusercontent.com/101818343/159128413-f6eee791-f7fb-409e-bb4b-583870a9945f.png)

**Comment by ophub** [comment]
Add new line

**Comment by ddams2000** [comment]
yes i already add line, 407: UGOOS AM6b Plus

**Comment by ophub** [comment]
Don't use the mainline u-boot, didn't I see the one I sent you? What's the difference in what you added? Writing emmc will fail to start.

**Comment by ddams2000** [comment]
oops, sorry I didn't understand that I had to remove the mainline u-boot line in the armbian-install script lol but I just did it and it still doesn't work, same errors

**Comment by ophub** [comment]
```
999:UGOOS AM6 Plus:s922x:meson-g12b-gtking-pro.dtb:u-boot-gtkingpro.bin:NA:NA:2C@1800Mhz(A53)+4C@1908Mhz(A73),4GB Mem,1Gb Nic,brcm4398 wifi
```

**Comment by ddams2000** [comment]
hello, no it doesn't work either. in the photo of the emmc error message, it says device 0: unknow device
card did not respond to voltage select! : -110
i have the same message when i boot on sd. do you have any idea what it could be?

**Comment by ophub** [comment]
Download today's latest firmware and try again

**Comment by ddams2000** [comment]
unfortunately still the same problem

**Comment by ddams2000** [comment]
Hi, i've try with the lastest .img and many u-boot, dtb files configuration. Now the screen goes blank and nothing happens.

**Comment by ophub** [comment]
You use `USB` for testing, don't use SD card.
Use it in USB first, don't write EMMC, maybe this mainline u-boot is not suitable for your device.

**Comment by ddams2000** [comment]
yes i tested the lastest img just after a fresh android reflash, with usb stick . 
but it's the same problem.

**Comment by ddams2000** [comment]
there must be a solution because it works with the manjaro image(kernel : 5.16.9.3),
What do you think ?
