### ISSUE TITLE
Buy recommandations 

### ISSUE THREAD

**Issue by delta-whiplash** [ophub/amlogic-s9xxx-armbian#1754]
Hello, can someone recommend me the best IPTV box I can buy for some docker containers.

I need a decent CPU with good emmc
and at least 4GB or even better 8GB of ram

**Comment by ophub** [comment]
s905x3-tx3

**Comment by delta-whiplash** [comment]
This the best box in your opinion?
It is easy to flash from USB drive (I only get successful with an x96 mini 😅)

**Comment by delta-whiplash** [comment]
I see thanks 😊
