### ISSUE TITLE
ext4和btrfs占用磁盘空间的巨大差别

### ISSUE THREAD

**Issue by Doboo** [ophub/amlogic-s9xxx-armbian#1757]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]  s905l3a
 - Model [e.g. HK1]  unt403a  2+8

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]  5.15  
 - Release: [e.g. jammy/bullseye] bookworm

使用armbian-install写入emmc存储时，分区格式选择btrfs时磁盘占用2.42G  占用率36%
但是使用ext4格式，磁盘占用5.77G  占用率87%
不是纯净的armbian系统，已经装了一些软件。
不知大家有没有遇到过这种情况？

**Comment by ophub** [comment]
btrfs比ext4压缩率高，性能上更好。ext4是更早一点的格式，兼容性更好。

**Comment by Doboo** [comment]
> btrfs比ext4压缩率高，性能上更好。ext4是更早一点的格式，兼容性更好。

只是没想到差别那么大。我试过另外一个16G的存储，占用3.86G 和8.87G 同样是两倍的关系。。。。
