### ISSUE TITLE
what about s905w2?

### ISSUE THREAD

**Issue by OM-3kChcBjgFR2COfP** [ophub/amlogic-s9xxx-armbian#1759]
**Device Information | 设备信息**
 - SOC: s905w2
 - Model: H96 Max

What about support my tv box on s905w2 chip? Can i run armbian\ubuntu on it? thanks

**Comment by Nitro56** [comment]
Closed as completed ? 
Is it now possible to install the firmware on an S905w2 based TV box ?

**Comment by OM-3kChcBjgFR2COfP** [comment]
> Closed as completed ? Is it now possible to install the firmware on an S905w2 based TV box ?

I’m also interested, I’m waiting for support, the console is lying and waiting too

**Comment by denisidoro** [comment]
Any ETAs on supporting it?

**Comment by markosc** [comment]
The driver for USB 3.0 is missing, it only recognizes USB 2.0 on both ports

**Comment by denisidoro** [comment]
@markosc were you able to boot Armbian on it, despite the lack of support for USB 3.0?

**Comment by denisidoro** [comment]
Not sure if it helps, but I'm able to run CoreELEC on it

**Comment by Eksol** [comment]
I didn't understand. Will there be any support?
