### ISSUE TITLE
H96 pro + board  cz32-v6 LPDDR3 i can't boot

### ISSUE THREAD

**Issue by agat81** [ophub/amlogic-s9xxx-armbian#176]

**Comment by agat81** [comment]
There are many versions of the H96 pro+ https://www.lupa.cz/clanky/dvojice-televiznich-boxu-h-96-pro-a-h-96-max-se-systemem-android/?forceSwitch=

My H96 pro + is still in a different version cz32-v6 with LPDDR3. I can't choose file.dtb this meson-gxm-octopus-planet.dtb did not work.
I have also tried others. I suspect it's because of the different versions of the device.
Armbian version Armbian_22.05.0_Aml_s912_focal_5.4.185_2022.03.17.0934.img (and I tried others too)
These are photos of my H96pro + version.
![IMG_2296](https://user-images.githubusercontent.com/97855835/158919781-efc45bdc-70b5-476f-ab52-0a9e144fc4f5.JPG)
![IMG_2297](https://user-images.githubusercontent.com/97855835/158919817-ce21688e-ea0d-4047-89d2-8af5dffd6e6c.JPG)
![IMG_2298](https://user-images.githubusercontent.com/97855835/158919829-38edea1e-f7d0-4ffd-bf67-b66ea3ea586b.JPG)
![IMG_2299](https://user-images.githubusercontent.com/97855835/158919843-6c795932-857d-4920-86d1-d6e9a7ac7bb0.JPG)
![IMG_2300](https://user-images.githubusercontent.com/97855835/158919859-eab1a7d0-2246-4951-af7a-d5db81926e85.JPG)
![IMG_2301](https://user-images.githubusercontent.com/97855835/158919864-57719a0d-2d13-4814-83c1-9dd5c9a95a3f.JPG)
![IMG_2302](https://user-images.githubusercontent.com/97855835/158919879-d16731ba-bbce-467a-a733-5395ee979c97.JPG)
![IMG_2304](https://user-images.githubusercontent.com/97855835/158919975-0fb6a662-af2e-417d-b280-ba7023813227.JPG)
![IMG_2305](https://user-images.githubusercontent.com/97855835/158919987-e6b7af49-f1d9-46d6-9ca4-0da788f04367.JPG)
![IMG_2306](https://user-images.githubusercontent.com/97855835/158919990-d5ae4ef4-dffc-4677-8ffa-5ba5dc957734.JPG)
![IMG_2307](https://user-images.githubusercontent.com/97855835/158919996-efc8a0b8-a49f-4591-be85-36b5a2d78824.JPG)
![IMG_2308](https://user-images.githubusercontent.com/97855835/158920013-743f491b-8c83-4d60-9cba-3cda1fd4df7b.JPG)
![IMG_2309](https://user-images.githubusercontent.com/97855835/158920019-c8879306-ddcf-4040-912c-799208d71b7a.JPG)
![IMG_2310](https://user-images.githubusercontent.com/97855835/158920032-52f69677-be04-4b69-b1b1-eb8325da73bf.JPG)
![IMG_2312](https://user-images.githubusercontent.com/97855835/158920039-f1438dfc-c3b0-477d-b0db-c8521bdac1cc.JPG)
![IMG_2313](https://user-images.githubusercontent.com/97855835/158920041-6b4e3e4c-9710-40f9-8a07-a67d0f3ef9e0.JPG)
![IMG_2314](https://user-images.githubusercontent.com/97855835/158920052-851051d0-5223-4d6d-90ca-07b42ea62e1b.JPG)
![IMG_2315](https://user-images.githubusercontent.com/97855835/158920061-3323d987-d303-4192-bb08-5b34ad7fae48.JPG)

**Comment by agat81** [comment]
Is there a correct .dtb file or not for my version of the H96 pro + device. Please help.

**Comment by ophub** [comment]
What does the display output at startup?

**Comment by agat81** [comment]
My box is H96 pro + with S912 3gb ram 32gb memory not H96 max. The article presents two types of H96 pro+ and H96 max boxes. The first part of the article shows 6 versions of H96 pro + and I have a different seventh version is cz32-v6 LPDDR3 it is not in the article my cz32-v6 LPDDR3 looks a bit similar to cz32-v5 (the last 6 version of H96 pr + in the article but  components are not the same, so I posted photos of the chipsers of individual components.

**Comment by agat81** [comment]
[ophub] Ask :"What soc? What does the display output at startup? What function cannot be used?"

My answer:
Arbmian doesn't boot at all. Only android 7.1 boot from the internal memory of the box (of course, the box has been reset to boot from the sd card)

**Comment by ophub** [comment]
Set the box to boot from USB/TF/SD



https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#1010-set-the-box-to-boot-from-usbtfsd
