### ISSUE TITLE
串口TTL 登陆 Armbian 时提示Login incorrect无法进入系统

### ISSUE THREAD

**Issue by hixiaolu** [ophub/amlogic-s9xxx-armbian#1760]
**Device Information | 设备信息**
 - SOC: [e.g. S905L]
 - Model [e.g. B860AV2.1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.55
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
在尝试了大佬的晶晨S905L和S905LB相关的固件包后，都能成功进入系统，但是却无法登录，输入完密码回车后都提示Login incorrect
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/99473752/93b08a99-dd3b-4a9a-bb5a-a5f240bad39e)
在尝试了换电脑和ch340串口板以及开关键盘小数字键盘相关操作后依然该问题

于是我根据网上教程开始用dg分区软件修改u盘的etc/securetty或etc/pam.d/login等文件，却依然无法解决，这个问题已经困扰了我一个周左右，现恳请大佬指点一二。

PS：因为网卡好像未驱动成功，所以ssh也无法登录

**Comment by ophub** [comment]
默认的用户名root，密码是1234

给盒子用网线接入路由器，可以在启动后看到分配的ip，有显示器的在屏幕上可以看见，没hdmi或者没有显示器的，到路由器里可以看到上线的设备名为armbian的设备ip，使用ssh工具访问管理。
