### ISSUE TITLE
unt403A s905l3a 最后安装无法格式化

### ISSUE THREAD

**Issue by lsf343634352** [ophub/amlogic-s9xxx-armbian#1761]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
可以用U盘启动,但是安装就提示最后的无法格式化,试过304.305.306

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/b5948e33-fa32-406d-b491-8a6d6d107efe)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/7c1a0f00-ea0f-4394-8109-35d0724bf4a1)

**Comment by ophub** [comment]
看文档12.16的方法
