### ISSUE TITLE
Armbian_23.08.0_amlogic_s912_lunar_6.1.55_server_2023.10.02.img.gz--------无法使用root&&1234登陆

### ISSUE THREAD

**Issue by jamesbondjava** [ophub/amlogic-s9xxx-armbian#1764]
**Device Information | 设备信息**
 - SOC: [e.g. S912]
 - Model [e.g. phicomm-t1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.55 && 5.15.133]
 - Release: [e.g. ophub/amlogic-s9xxx-armbian]

**Describe the bug | 问题描述**
我尝试了两个版本的armbian，使用Rufus将固件刷入U盘后，更改了uEnv.txt内容（适配dtb文件），在斐讯T1上顺利启动，但是系统启动后会自动进入桌面环境，默认用户名为James，密码不得而知。切换用户后，使用root登陆，密码输入为1234（确保Num打开），还是无法登陆，一直提示“login incorrect”

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
请大佬确认一下这两个版本队的root密码，非常感谢。。

**Comment by jamesbondjava** [comment]
需要补充一点，使用putty，通过IP登陆也不行，显示：Access denied

**Comment by seamt** [comment]
> **Describe the bug | 问题描述** 我尝试了两个版本的armbian，使用Rufus将固件刷入U盘后，更改了uEnv.txt内容（适配dtb文件），在斐讯T1上顺利启动，但是系统启动后会自动进入桌面环境，默认用户名为James，密码不得而知。切换用户后，使用root登陆，密码输入为1234（确保Num打开），还是无法登陆，一直提示“login incorrect”
> 

有些奇怪，ophub开始提供桌面版的系统。请问是什么桌面环境？

**Comment by ophub** [comment]
我编译的只有server版本，没有桌面，需要选择安装。

**Comment by seamt** [comment]
> 我编译的只有server版本，没有桌面，需要选择安装。

请问什么时候会用到root: 1234的初始密码登录？
是在新刷系统首次启动时，在远程主机使用ssh登录电视盒的时候吗？

**Comment by jamesbondjava** [comment]
实在抱歉，忘记了，这个盒子之前已经刷过系统了，也是armbian，但是不记得密码了。但是不知道何时安装了桌面环境，右下角显示一个是Ubuntu，另一个是Ubuntu.org。各位大佬，在不知道密码的情况下，armbian有办法可以重置吗？想了一下午了，没想起来密码。实在抱歉。

**Comment by jamesbondjava** [comment]
巨尴尬……

**Comment by seamt** [comment]
> 实在抱歉，忘记了，这个盒子之前已经刷过系统了，也是armbian，但是不记得密码了。但是不知道何时安装了桌面环境，右下角显示一个是Ubuntu，另一个是Ubuntu.org。各位大佬，在不知道密码的情况下，armbian有办法可以重置吗？想了一下午了，没想起来密码。实在抱歉。

我感觉你现在的主要问题是U盘新刷的系统无法引导。如果成功从U盘引导，可能的操作就多了。
但是想把EMMC上的系统回滚到Armbian的初始安装状态（类似Android的恢复出厂状态），这个Armbian肯定做不到。
据说Fedora Silverblue使用快照文件系统可以实现类似功能，但是我没有实测过。
在我自己的s905l3a设备上面，U盘引导失败是常事。我使用了一个USB2.0的hub连接盒子的U口和U盘，可以显著提高U盘引导的成功率到大约80%。
你这个标题误导性太强，建议删贴重新发贴再新问题吧。
再提问的时候，建议你把“重置”是个什么意思讲清楚。

**Comment by jamesbondjava** [comment]
> > 实在抱歉，忘记了，这个盒子之前已经刷过系统了，也是armbian，但是不记得密码了。但是不知道何时安装了桌面环境，右下角显示一个是Ubuntu，另一个是Ubuntu.org。各位大佬，在不知道密码的情况下，armbian有办法可以重置吗？想了一下午了，没想起来密码。实在抱歉。
> 
> 我感觉你现在的主要问题是U盘新刷的系统无法引导。如果成功从U盘引导，可选的操作就多了。 但是如果你说的“重置”，是把EMMC上的系统回滚到Armbian的初始安装状态（类似Android的恢复出厂状态），这个Armbian肯定做不到。据说Fedora Silverblue可以实现类似功能，我没有实测过。 在我自己的s905l3a设备上面，U盘引导失败是常事。我使用了一个USB2.0的hub连接盒子的U口和U盘，可以显著提高U盘引导的成功率到大约80%。 你这个标题误导性太强，建议删贴重新发贴再新问题吧。 再提问的时候，可以把“重置”换成通俗的讲法。

大佬，就是需要重新从U盘启动的问题。T1只有一个USB口，我已经使用了USB-hub，但是无法引导，我搜了好久了，也没找到正确的方法，能否指导一下？

**Comment by seamt** [comment]
> 大佬，就是需要重新从U盘启动的问题。T1只有一个USB口，我已经使用了USB-hub，但是无法引导，我搜了好久了，也没找到正确的方法，能否指导一下？

就说我自己的设备上，即使连接了USB2.0的HUB，uboot引导仍然挑盘。举例：
好用的设备：川宇C308 USB3.0 TF读卡器、雷克沙S47 USB3.0 U盘
这两款引导成功率能达到80%。

不好用的设备：川宇C292 USB2.0 TF读卡器，凯侠U301 USB3.0 U盘
这两款引导成功率大约20%，即使引导成功也会经常发生数据读写错误。

读卡器对TF卡型号没要求。可以买写入速度快一点的TF卡，但是超过30MiB/s就没必要了，毕竟USB2.0接口是瓶颈。

**Comment by jamesbondjava** [comment]
非常感谢，换了一个U盘，成功了，但是过程好像不好溯源。主要有以下操作：
1.更换了一个宇瞻的32G，USB3.0U盘；
2.使用最新的6.1.55镜像；
3.也使用了USB-hub（因为T1只有1个USB口，我想接USB键盘调试设备）。

目前正在将系统写入emmc中……

非常感谢大佬们。 @ophub @seamt 感谢你们的无私奉献。
最后，请教一下，想比较系统地学习一下嵌入式Linux，有没有比较好的课程推荐？
