### ISSUE TITLE
联想的粒子云，使用9月份的版本（bookworm和lunar）都正常，10月份的刷机后均无反应。

### ISSUE THREAD

**Issue by DongBH** [ophub/amlogic-s9xxx-armbian#1768]
感谢您辛勤的付出，让老设备有更新可以用。我测试了一下，联想的粒子云，使用9月份的版本（bookworm和lunar）都正常，10月份的刷机后均无任何反应。

**Comment by seamt** [comment]
> 感谢您辛勤的付出，让老设备有更新可以用。我测试了一下，联想的粒子云，使用9月份的版本（bookworm和lunar）都正常，10月份的刷机后均无任何反应。

两个内核版本都试过？

**Comment by DongBH** [comment]
以下两个不可以：
rockchip_chainedbox_lunar_6.1.55_server_2023.10.02.img.gz
23.08.0_rockchip_chainedbox_bookworm_6.1.55_server_2023.10.02.img.gz
以下两个可以：
rockchip_chainedbox_bookworm_6.1.52_server_2023.09.12
rockchip_chainedbox_lunar_6.1.54_server_2023.09.20
其他没有试（当时没有注意到还有多个内核）

**Comment by seamt** [comment]
> 以下两个不可以： rockchip_chainedbox_lunar_6.1.55_server_2023.10.02.img.gz 23.08.0_rockchip_chainedbox_bookworm_6.1.55_server_2023.10.02.img.gz 以下两个可以： rockchip_chainedbox_bookworm_6.1.52_server_2023.09.12 rockchip_chainedbox_lunar_6.1.54_server_2023.09.20 其他没有试（当时没有注意到还有多个内核）

那你再试一下5.15版的内核可以吗？

**Comment by DongBH** [comment]
Chainedbox 没有 5.15 的。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年10月9日 21:49
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] 联想的粒子云，使用9月份的版本（bookworm和lunar）都正常，10月份的刷机后均无反应。 (Issue #1768)


以下两个不可以： rockchip_chainedbox_lunar_6.1.55_server_2023.10.02.img.gz 23.08.0_rockchip_chainedbox_bookworm_6.1.55_server_2023.10.02.img.gz 以下两个可以： rockchip_chainedbox_bookworm_6.1.52_server_2023.09.12 rockchip_chainedbox_lunar_6.1.54_server_2023.09.20 其他没有试（当时没有注意到还有多个内核）

那你再试一下5.15版的内核可以吗？

―

**Comment by seamt** [comment]
> Chainedbox 没有 5.15 的。 
那我的经验基本帮不上。只是从缩小故障范围的角度，你可以试试：
一、检查 /boot/uEnv.txt文件中的“FDT=”行的指向是不是和以前版本一样。
二、文件比较，检查新旧版本的dtb文件是不是一样。
三、如果不一样，用旧版dtb替换新版的系统中的dtb，再试。
四、连接网线后开机，你在路由器或其他同网段的主机内能否检察到粒子云的IP。
希望高手能更容易帮到你。

**Comment by DongBH** [comment]
谢谢，我去学习一下dtb，看能不能解决

**Comment by gzxief** [comment]
你可以自己编译啊一下啊，https://github.com/LaiQE/Chainedbox-build，在linux下，改一下固件的地址，运行一下5.15.sh，不用管他是6.1还是6.2都可以用

**Comment by DongBH** [comment]
谢谢，我去试了下，这个脚本是直接替换dtb等。但其img的分区和脚本不一致，我看能不能改得出来。非常感谢！

**Comment by DongBH** [comment]
采用 https://github.com/LaiQE/Chainedbox-build](https://github.com/LaiQE/Chainedbox-build 的脚本展开10月和9月的img文件，发现其 dtb 文件名和大小完全相同，日期不同。

**Comment by gzxief** [comment]
一般我家云，粒子云，我都用官方编译出最小版本armbian，只有230M，再用https://github.com/LaiQE/Chainedbox-build，打补丁就可以用，一开始编译是5.15，后面变成6.1了，但打补丁后一样可以用

**Comment by gzxief** [comment]
https://www.123pan.com/s/doe8Vv-JuBw3.html   我用官方编译出23.11.0-6.1.57的版本，已打补丁

**Comment by ophub** [comment]
试试今天编译的，我调整了下内核

**Comment by DongBH** [comment]
谢谢支持，反馈一下测试结果：

> 试试今天编译的，我调整了下内核
还是不行，感觉能启动，有蜂鸣声，网卡有闪，但没有地址。

> https://www.123pan.com/s/doe8Vv-JuBw3.html 我用官方编译出23.11.0-6.1.57的版本，已打补丁
这个可以用。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz

我调整了下，你下载这个测试下，反馈下情况。

**Comment by DongBH** [comment]
谢谢，周末去测试。

**Comment by Yxini** [comment]
> [https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz ](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz)
> 
> 我调整了下，你下载这个测试下，反馈下情况。

能启动，但是不能连接SHH，在路由器里面有IP但是拒绝SHH连接

**Comment by Yxini** [comment]
> https://www.123pan.com/s/doe8Vv-JuBw3.html 我用官方编译出23.11.0-6.1.57的版本，已打补丁

这个可以启动

**Comment by DongBH** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz
> 
> 我调整了下，你下载这个测试下，反馈下情况。

刷机正常，前面板蓝灯常亮。网卡指示灯正常，但没有ip地址（我在路由器上将这个mac作为静态地址）。

**Comment by gzxief** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz
> > 我调整了下，你下载这个测试下，反馈下情况。
> 
> 我家云刷机正常，前面板蓝灯常亮。网卡指示灯正常，但没有ip地址（我在路由器上将这个mac作为静态地址）。

你可以用ophub大神的armbian，解压出img，要linux下用 https://github.com/LaiQE/Chainedbox-build ，打补丁就可以用了

**Comment by DongBH** [comment]
> > > https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz
> > > 我调整了下，你下载这个测试下，反馈下情况。
> > 
> > 
> > 我家云刷机正常，前面板蓝灯常亮。网卡指示灯正常，但没有ip地址（我在路由器上将这个mac作为静态地址）。
> 
> 你可以用ophub大神的armbian，解压出img，要linux下用 https://github.com/LaiQE/Chainedbox-build ，打补丁就可以用了
谢谢，是的，已经试了。

**Comment by Yxini** [comment]
> > > https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz
> > > 我调整了下，你下载这个测试下，反馈下情况。
> > 
> > 
> > 我家云刷机正常，前面板蓝灯常亮。网卡指示灯正常，但没有ip地址（我在路由器上将这个mac作为静态地址）。
> 
> 你可以用ophub大神的armbian，解压出img，要linux下用 https://github.com/LaiQE/Chainedbox-build ，打补丁就可以用了

请问这个如何操作

**Comment by Yxini** [comment]
刷了6.1.59 bullseye 依然无法启动SHH，O大尝试了很多天，依然无法解决。

**Comment by Yxini** [comment]
> https://www.123pan.com/s/doe8Vv-JuBw3.html 我用官方编译出23.11.0-6.1.57的版本，已打补丁

你好，我可以加你QQ了解一下这个吗

**Comment by gzxief** [comment]
> > https://www.123pan.com/s/doe8Vv-JuBw3.html 我用官方编译出23.11.0-6.1.57的版本，已打补丁
> 
> 你好，我可以加你QQ了解一下这个吗
81218116，暗号：github

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_jammy_6.1.60_server_2023.10.27.img.gz

今天的最新版应该没问题了，你试试

**Comment by ophub** [comment]
![Snip20231028_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/13aab016-1b93-4ff1-b1ef-c202bd357068)
![20231028163141](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/a6d2d8c0-35c5-44ba-be35-fd2e2758729b)
![Snip20231028_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/453c3665-4ef6-4afc-ad17-c6b8b6434a1d)

**Comment by DongBH** [comment]
非常感谢，jammy,bookworm 都试过了，均OK!
