### ISSUE TITLE
Fork 后针对新板子编译镜像无法启动

### ISSUE THREAD

**Issue by east4ming** [ophub/amlogic-s9xxx-armbian#1769]
**Device Information | 设备信息**
 - SOC: rk3399
 - Model: [firefly cluster server r1](https://wiki.t-firefly.com/zh_CN/Cluster-Server-R1/Firefly_Cluster_server_product_documentation.html) - 是一个 由: 1个底板 + 1 个主核心板 + 10个子核心板(sub) 组成的服务器. 
    - 子核心板(sub) 使用的是 [firefly core-3399jd4 ](https://wiki.t-firefly.com/zh_CN/Core-3399-JD4/preface.html)
    - 我想基于firefly core-3399jd4 编译 firefly cluster server r1 sub的固件. 官方有详细文档: [链接](https://wiki.t-firefly.com/zh_CN/Cluster-Server-R1/Firefly_Cluster_server_product_documentation.html#ubuntu-18-04)

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.y] 当前编译后的为6.1.56
 - Release: [ jammy]

**Describe the bug | 问题描述**
Fork 后针对新板子编译镜像无法启动. 具体见:

- 编译成功并发布的release: https://github.com/east4ming/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2023.10
- 添加的dtb: https://github.com/east4ming/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/rockchip/bootfs/dtb/rockchip/rk3399-firefly-CS-R1-jd4-sub.dtb
- 添加的model: https://github.com/east4ming/amlogic-s9xxx-armbian/blob/d8d72cfbd1eb3ae5d60bceb6c5e02c5a69dbe886/build-armbian/armbian-files/common-files/etc/model_database.conf#L235
- 添加的u-boot: https://github.com/east4ming/u-boot/tree/main/u-boot/rockchip/fireflycsr1jd4-sub

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

我缺乏编译固件的相关专业知识. 但是在阅读了ophub 文档和firefly官方文档后, 我发现firefly cluster server r1 sub的u-boot固件和king3399非常类似, 都包括:

- idbloader
- rk3399_loader_vxxxx.bin
- trust
- uboot

firefly的官方文档也提到了上面的4个, 如下:
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/13358726/9dcec46b-e17b-4eef-a5d3-093ebf515f92)

所以 model_database.conf 的写法是和 king3399的类似的.

u-boot/dtb/model_database.conf/构建脚本及github action 我都有做相应调整. 但是下载构建好的镜像尝试刷机后, 却无法启动, 毫无反应.

请问可能是什么原因? 如何调整?

谢谢!

**Comment by east4ming** [comment]
#1753

**Comment by ophub** [comment]
你的操作步骤正常，但是其他设备的u-boot编译通过并不代表这个u-boot适合你的设备，需要根据设备的原理图适配。
