### ISSUE TITLE
X96 Mini Ram 2G / Rom 16 - won't Boot

### ISSUE THREAD

**Issue by SajjadSabzkar** [ophub/amlogic-s9xxx-armbian#177]
Hi , Thanks for developing this Project . 
I follow all step in your documention and other documention in web , but i Can't boot this device Not at all . 
Please help me

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_focal_03.18.1606#:~:text=Armbian_22.05.0_Aml_s905w_focal_5.4.185_2022.03.18.1557.img.gz

**Comment by SajjadSabzkar** [comment]
Hi , This link won't available and github says Page not found

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_03.18.2242/Armbian_22.05.0_Aml_s905w_focal_5.4.185_2022.03.18.2233.img.gz

**Comment by SajjadSabzkar** [comment]
I tested this image but won't boot

**Comment by ophub** [comment]
you look at what dtb you are using in "Armbian_5.44_S9xxx_Debian_stretch_3.14.29_xfce_20180601.img.xz"
`cat /boot/uEnv.txt`

**Comment by SajjadSabzkar** [comment]
this image automatically detected dtb and i don't need determine dtb . 
when i run 'cat /boot/uEnv.txt' : 
`
bootargs=root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyS0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 mac=${mac}
`

**Comment by ophub** [comment]
`cat /boot/extlinux/extlinux.conf`

**Comment by SajjadSabzkar** [comment]
/boot does not have extlinux folder . i take screenshot the directory /boot contents
![ls_content](https://user-images.githubusercontent.com/33274732/159123941-61318ca6-688d-494a-9f6d-d6273fd4daf3.png)
when i run `cat /boot/s905_autoscript` seems it find and convert device dtb to dtb.img file . i upload s905_autoscript for you .
[s905_autoscript.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8309363/s905_autoscript.zip)

**Comment by SajjadSabzkar** [comment]
Is it possible to change the source Code where define dtb  , dtb format was dtb.img?

**Comment by ophub** [comment]
I don't understand the previous practice, and I'm not familiar with the original settings. You can check the relevant introduction yourself.
