### ISSUE TITLE
Ubuntu构建中的两个重大缺陷

### ISSUE THREAD

**Issue by seamt** [ophub/amlogic-s9xxx-armbian#1770]
此问题与主机硬件型号无关。

Ubuntu版本的两个重大缺陷：
一、无法编译Realtek的无线网卡驱动程序。
（凭印象）受影响的是O大提供的所有Ubuntu版本。
我买过4个不同芯片型号的Realtek USB无线网卡，只有一款可以免驱在Ubuntu上面使用，其它三款在Ubuntu上用不了。
（在Debian上，不能免驱的无线网卡，都很容易编译驱动一次成功。）
可能原因是，Ubuntu内核使用Clang/LLVM工具链，Realtek驱动则要求GCC工具链，二者冲突。
举一例，rtl88x2bu的编译错误日志：
`
DKMS make.log for rtl88x2bu-5.13.1 for kernel 5.15.92-flippy-81+o (aarch64)
Mon Oct  9 11:08:36 PM CST 2023
make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/5.15.92-flippy-81+o/build M=/var/lib/dkms/rtl88x2bu/5.13.1/build  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.92-flippy-81+o'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: Ubuntu clang version 14.0.0-1ubuntu1
  You are using:           gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_cmd.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_security.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_debug.o
  CC [M]  /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_io.o
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_cmd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_security.o] Error 1
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_debug.o] Error 1
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/rtl88x2bu/5.13.1/build/core/rtw_io.o] Error 1
make[1]: *** [Makefile:1905: /var/lib/dkms/rtl88x2bu/5.13.1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.92-flippy-81+o'
make: *** [Makefile:2523: modules] Error 2
`

Realtek的有线网卡驱动或者其他厂牌外设的驱动（如果系统没有内置而需要自己编译），我因为暂未接触所以未做测试，但是估计情况类似。
不知道这个bug是不是只发生在Armbian，或只在O大的构建中存在。

二、firefox和chromium安装困难
受影响的是Ubuntu 22.04及以后版本。
正常apt安装firefox或chromium，会被强行引导到SNAP下载。由于大陆访问SNAP的速度极慢，下载很容易超时中断。
这个原因比较确定，Ubuntu官方在22.04LTS开始强推SNAP。除firefox/chromium，其他桌面软件安装受此影响未知。

以上两个bug，导致Ubuntu构建不论作为服务器还是桌面都很麻烦。
幸好这两个bug在Debian构建中没有出现。

**Comment by ophub** [comment]
要自定义编译驱动，把内核更新成dev系列的。翻看之前的帖子里有很详细的讨论。

**Comment by seamt** [comment]
> 要自定义编译驱动，把内核更新成dev系列的。翻看之前的帖子里有很详细的讨论。
> 
> 我的重构只是修改了/boot支持了更多设备的启动，并没改变armbian的apt

  明白了，谢谢。
