### ISSUE TITLE
正常跑着已经有大半年了，重启后进不了系统

### ISSUE THREAD

**Issue by vip198926** [ophub/amlogic-s9xxx-armbian#1774]
Device Information | 设备信息

SOC: s905l3a
Model：E900V22C
Armbian Version | 系统版本

Kernel Version: Linux 5.15.91-flippy-81+o (armbian)
Release: [e.g. jammy]
Describe the bug | 问题描述
正常跑着已经有大半年了，基本上没有去查看，最近发现Docker挂掉了在月初时已经挂掉了，重启后进不了系统
情况如图
![0ca95c594547ccbe2ac30c8c63e77c50](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64185667/a85afe00-8596-4833-aeea-fe406d6b6b9f)

**Comment by ophub** [comment]
/boot/uEnv.txt
/etc/fstab

blkid命令查看uuid，把上面两个文件里面的uuid检查一下哪个被改了。有可能是第二个的被什么软件修改了挂载点的uuid

**Comment by ophub** [comment]
U盘刷个新系统进去挂载emmc，比较一下，少啥复制啥。复制好文件后，blkid看emmc的uuid，把这两处的值更正对。

**Comment by vip198926** [comment]
以前做作过ddbr全盘备份的，恢复备份还是一样的错误启动不了，装重装了是能正常启动的，再次恢复后还是一样的错误不能启动。emmc里boot目标是空的，已经从U盘系统里复制过去并且改了uEnv.txt里的UUID。
/boot/uEnv.txt 
/etc/fstab
里的UUID都为blkid读出来的值，但还是一样启动不了。


![微信截图_20231013234457](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64185667/8161d75a-485e-4634-9520-a8d6c587010a)

**Comment by vip198926** [comment]
> U盘刷个新系统进去挂载emmc，比较一下，少啥复制啥。复制好文件后，blkid看emmc的uuid，把这两处的值更正对。

**Comment by ophub** [comment]
正常的系统里有/boot目录，下面有系列启动文件。

**Comment by vip198926** [comment]
那请问像这种情况，重装能启动，恢复后不能启动是哪方面的原因呢？

**Comment by ophub** [comment]
你恢复的系统也是没/boot的，说明之前ddbr备份的就是一个不完整的系统。

**Comment by vip198926** [comment]
mmcblk2p1里的文件是不是/boot里的文件呢，mmcblk2p2里的boot在没有启动时是空的吧！ 我改了sda1/uEnv.txt  里的UUID为mmcblk2p2的，能启动起来，系统是备份恢复后不能启动的系统。在里面挂载了sda2看U盘里的系统/boot目标也是空的。
我也把sda1里的文件cp到mmcblk2p1里(也cp到了mmcblk2p2/boot/，/etc/fstab和uEnv.txt都改了)把uEnv.txt改为mmcblk2p2的UUID还是不能启动起来。

**Comment by ophub** [comment]
p2/p3/p4 里都没 /boot
/boot 只存在于 mmcblk2p1 里，p1 里就是 /boot 的全部

**Comment by vip198926** [comment]
mmcblk2p1里面是有文件的，但是启动不了，cp了能启动的U盘里的过去也是启动不了。不知道是什么原因。

**Comment by ophub** [comment]
你的错误提示的是uuid值不对，只要上面说的2处都改对了，就可以启动了。

**Comment by vip198926** [comment]
blkid 读出来的值，和p1里的/uEnv.txt ，p2里面的/etc/fstab 值已经是一样的，然尔还是启动不了呢。



`# blkid
/dev/mmcblk2p2: LABEL="ROOTFS_EMMC" UUID="29f6260e-b551-4993-82b2-332132b27c87" BLOCK_SIZE="4096" TYPE="ext4"
/dev/mmcblk2p1: LABEL_FATBOOT="BOOT_EMMC" LABEL="BOOT_EMMC" UUID="B187-DEB1" BLOCK_SIZE="512" TYPE="vfat"
/dev/sda2: LABEL="ROOTFS" UUID="9b2369c6-09bd-4495-876e-81f90bdecb9b" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="d2790244-02"
/dev/zram0: UUID="a935e5ba-82c9-49d9-a861-6edf4664533b" TYPE="swap"
/dev/zram1: LABEL="log2ram" UUID="8f32cfcc-2ce0-4978-a47c-da5f739a29f8" BLOCK_SIZE="4096" TYPE="ext4"
/dev/sda1: LABEL_FATBOOT="BOOT" LABEL="BOOT" UUID="7618-BF04" BLOCK_SIZE="512" TYPE="vfat" PARTUUID="d2790244-01"
# cat p2/etc/fstab
UUID=29f6260e-b551-4993-82b2-332132b27c87  /        ext4     defaults,noatime,errors=remount-ro     0 1
LABEL=BOOT_EMMC      /boot    vfat                    defaults                  0 2
tmpfs                /tmp     tmpfs                   defaults,nosuid           0 0

# cat p1/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb
APPEND=root=UUID=29f6260e-b551-4993-82b2-332132b27c87 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
#
#`



![微信截图_20231014233534](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64185667/4ec8157e-99b8-422c-bae6-bc1aa91a09e0)

**Comment by ophub** [comment]
/etc/config/fstab
这还有一个

**Comment by vip198926** [comment]
/etc/config/fstab 有这一个目标吗？

**Comment by ophub** [comment]
op系统有这个，armbian没有

**Comment by vip198926** [comment]
不纠结了，重装吧
