### ISSUE TITLE
AIC8800驱动编译失败

### ISSUE THREAD

**Issue by opbopb** [ophub/amlogic-s9xxx-armbian#1777]
**Device Information | 设备信息**
 - SOC: [S905L3A]
 - Model [E900V22D]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.55]
 - Release: [bookworm]

**Describe the bug | 问题描述**
编译usb无线网卡（AIC8800芯片）驱动时出现如下错误，请大佬空时指点一下

![3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/145092173/6ab8da83-e98a-4354-b63e-d6a8e6e70fa6)

make -C /lib/modules/6.1.55-ophub/build M=/root/complier/linux_driver_sourcecode/aic8800_linux_drvier/drivers/aic8800 ARCH=arm CROSS_COMPILE= modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.55-ophub'
Makefile:775: arch/arm/Makefile: No such file or directory
make[1]: *** No rule to make target 'arch/arm/Makefile'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-6.1.55-ophub'
make: *** [Makefile:55: modules] Error 2

**Comment by ophub** [comment]
换dev系列的内核，搜之前的帖子里有介绍编译驱动的方法

**Comment by opbopb** [comment]
感谢大佬，我去找找

**Comment by opbopb** [comment]
大佬，按你的提示，我换了dev内核，出现了新的错误
![2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/145092173/239a7d7e-bad8-48b5-a4db-3c7c0cab4253)


make -C /lib/modules/6.1.52-ophub/build M=/root/complier/linux_driver_sourcecode/aic8800_linux_drvier/drivers/aic8800 ARCH=arm CROSS_COMPILE= modules
make[1]: Entering directory '/usr/src'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/src'
make: *** [Makefile:55: modules] Error 2

根据提示Makefile:55如下

![13](https://github.com/ophub/amlogic-s9xxx-armbian/assets/145092173/1fe5d7f8-d0d5-4abe-acef-aa38ee8bd52a)


我看不明白。。。。
厚着脸皮继续来问下。。

**Comment by ophub** [comment]
armbian使用的是主线内核。你找主线内核的驱动，安卓的不支持。

**Comment by opbopb** [comment]
好的，再次感谢!
