### ISSUE TITLE
E900V22D安装失败，卡在resizing filesystem。强制重启后会乱码。

### ISSUE THREAD

**Issue by KannaNyaa** [ophub/amlogic-s9xxx-armbian#1779]
**Device Information | 设备信息**
 - SOC: S905L3b
 - Model E900V22D

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.133
 - Release: jammy/bullseye

**Describe the bug | 问题描述**

刷了`android_tv_e900v22e_e900v22d_s905l3b.tar.xz`这个固件后，用U盘安装。没有插网线，只有`TTL`
首次安装会需要创建密码，无论输不输新密码。都会卡在以下两句：
```bash
[   54.628337] EXT4-fs (sda2): resizing filesystem from 655360 to 3687424 blocks
[   55.190588] EXT4-fs (sda2): resized filesystem to 3687424
```
然后此时无论输什么都是`*`，并且输入到一定长度后会出现：
`[  109.653745] sysrq: HELP : loglevel(0-9) reboot(b) crash(c) terminate-all-tasks(e) memory-full-oom-kill(f) kill-all-tasks(i) thaw-filesystems(j) sak(k) show-backtrace-all-active-cpus(l) show-memory-usage(m) nice-all-RT-tasks(n) poweroff(o) show-registers(p) show-all-timers(q) unraw(r) sync(s) show-task-states(t) unmount(u) show-blocked-tasks(w)`

此时只有强制断电重启，重启后会卡在输入密码的界面，并且输入任何数据均乱码：

已将两次上电时的完整日志记为`首次上电.log`和`重启后上电.log`

![错误截图](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49608135/b9567329-c6df-4722-80f9-26ecf4e986c7)

[首次上电.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12878075/default.log)
[重启后上电.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/12878077/default.log)

**Comment by ophub** [comment]
首次从usb启动时，会自动分区扩容到整个U盘的剩余空间全部分配为可用空间。你上面的日志显示扩容中，多等会，一般不超过一分钟。如果U盘总是扩容失败就换个好用的U盘。

**Comment by KannaNyaa** [comment]
您好大佬，这个分区扩容行为可以禁止吗？在京东上新买的16G的闪迪U盘也会卡在这里，之前16G的金士顿也会卡，还试了我的固态硬盘盒，也会卡在这里。但是这个系统用原版安卓底包的时候就不会卡在这个过程。我现在再尝试刷一下其他的版本的安卓系统。

**Comment by ophub** [comment]
删除/usr/sbin/armbian-tf

**Comment by KannaNyaa** [comment]
我换了一个安卓包，没有卡在`[  54.628337] EXT4-fs (sda2): resizing filesystem from 655360 to 3687424 blocks`,但还是会出现无法输入密码这个问题。同时还是还会出现`sysrq`这个工具的提示.

**Comment by ophub** [comment]
远程ssh访问

**Comment by KannaNyaa** [comment]
用U盘启动后Armbian自动获取不了IP，但是安卓底包是能获取IP的 😭

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

**Comment by KannaNyaa** [comment]
我用的是[android_tv_e900v22e_e900v22d_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22e_e900v22d_s905l3b.tar.xz)这个安卓包

**Comment by ophub** [comment]
这个是之前测试可以用的

**Comment by KannaNyaa** [comment]
安卓底包刷的就是这个，在安卓上能获取到IP，但是刷armbian的镜像就是有问题，总是会卡住或者进不去系统。好的谢谢大佬，我再看看有没有其他办法。
