### ISSUE TITLE
Error in choosing the firmware version to update and the X96 Max Plus device does not come up

### ISSUE THREAD

**Issue by amin233** [ophub/amlogic-s9xxx-armbian#1781]
Hello, unfortunately, I was not careful in choosing the update version, and after the update with the USB_Burning_Tool program, I don't have any display on the 7segmant or the screen, has the BIOS of the device been deleted? Please guide me how to fix or troubleshoot this problem?
My device model:
X96 Max Plus Q1（s905x3）4G+32G

**Comment by ophub** [comment]
Download the original Android and use this USB_Burning_Tool tool to restore the system.

**Comment by amin233** [comment]
Unfortunately, the usb3 port is not detected in this program.
