### ISSUE TITLE
小宝nas xiaobao 依旧没办法识别sata

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#1783]
小宝nas 刷了6.1.57或6.1.52的内核，都没办法正常驱动sata，求大神，原来6.1.11的版本能用但还是有点问题

**Comment by phcl1998** [comment]
原来的6.1.11有什么问题啊？我用了大半年了

**Comment by gzxief** [comment]
> 原来的6.1.11有什么问题啊？我用了大半年了

在ipv6远程访问时，100-10000的端口访问不了

**Comment by Mango1151** [comment]
> 小宝nas 刷了6.1.57或6.1.52的内核，都没办法正常驱动sata，求大神，原来6.1.11的版本能用但还是有点问题

求能驱动sata的小宝NAS armbian版本

**Comment by Mango1151** [comment]
> > 原来的6.1.11有什么问题啊？我用了大半年了
> 
> 在ipv6远程访问时，100-10000的端口访问不了

求能驱动sata的小宝NAS armbian版本
