### ISSUE TITLE
R3300L写入emmc后插U盘不能启动问题

### ISSUE THREAD

**Issue by rczhuqing** [ophub/amlogic-s9xxx-armbian#1784]
**Device Information | 设备信息**
 - SOC: [e.g. S905LB]
 - Model [e.g. R3300L]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.57]
 - Release: [e.g. bullseye]
 - IMG: Armbian_23.11.0_amlogic_s905lb-r3300l_bullseye_6.1.57_server_2023.10.12.img
**Describe the bug | 问题描述**
写入emmc后，默认还是从U盘启动，导致开机时黑屏不能进入系统。请问需要如何设置？

**Comment by ophub** [comment]
u盘里没有boot的话不会从u盘启动

**Comment by rczhuqing** [comment]
> u盘里没有boot的话不会从u盘启动

我插了一个ext4格式的U盘，打算作为数据盘使用，先插U盘再开机，就启动不了emmc里的系统了。先开机再插U盘，识别倒是没问题。
