### ISSUE TITLE
请求ophub大佬适配dusun 东森网关DSGW-210B RK3328 芯片

### ISSUE THREAD

**Issue by mysmartha** [ophub/amlogic-s9xxx-armbian#1785]
dusun 东森网关DSGW-210B 基本配置如下
SOC: RK3328
Quad-core ARM Cortex-A53 Mali-450MP2 GPU 
Power Supply: DC-5V
LTE module: BG96 (LET CAT-1)
Wi-Fi module: 6221A (Wi-Fi chip: RTL8821CS) Zigbee: EFR32MG1B232F256GM32 
Z-wave: ZGM130S037HGN Bluetooth: EFR32BG21A020F768IM32 eMMC: 8GB 
SDRAM: 2GB

官网介绍链接如下
https://www.dusuniot.com/product-specification/dsgw-210b-lorawan-ethernet-wifi-ttn-gateway/

官方有debian 内核是4.4的 ，比较老旧，官方有完整的Linux SDK 里面应该有适配需要的uboot和DTS等资料，资料链接如下
https://www.dusuniot.com/product/dsgw-210-rk3328-iot-gateway-hub-controller-bridge-hardware/
linux SDK下载链接
https://drive.google.com/file/d/1i_vDZ-LLWvsb8IMXVAE1BYTFEv45zVBv/view

希望大佬能适配最新的armbian固件，谢谢。

**Comment by speeedturtle** [comment]
现在是否有适配的系统了？ 官方的系统太老， buggy
