### ISSUE TITLE
r3300l_bookworm_5.15.13 eth0 不能ping通连不上ssh wlan0不插网线能ssh

### ISSUE THREAD

**Issue by rmoyulong** [ophub/amlogic-s9xxx-armbian#1787]
Armbian_23.11.0_amlogic_s905lb-r3300l_bookworm_5.15.135_server_2023.10.13.img.gz

设置了netplan
eth0 不能ping通连不上ssh
可以使用wifi 连上ssh
 
只要插上网线，etho wlan0 都ping不通

**Comment by ophub** [comment]
网络设置的方法看文档里有写

**Comment by rmoyulong** [comment]
已经设置好了 ，谢谢
