### ISSUE TITLE
还请提供历史版本的下载吧，最近9月份和10月份的build，刷上开机启动很慢，还不一定能启动成功

### ISSUE THREAD

**Issue by domytest** [ophub/amlogic-s9xxx-armbian#1789]
n1 盒子，  用balenaEtcher制作镜像时，最后校验都有一个error，说是校验码不一致？
u盘启动，刷上开机启动很慢，还不一定能启动成功，得重启1-2次

对于n1盒子，这样得老盒子，并不需要最新得build，只需要提供历史稳定版本，无毒无木马即可

**Comment by ophub** [comment]
每月都会删掉之前月份的，没旧版
