### ISSUE TITLE
Unable to use the led command on lastest build (kernel 5.15.29)

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#179]
I've just built the latest source code to try the new LED function but unable to run any related commands:

> armbian-led
> armbian-led: command not found

> cd /usr/share/openvfd 
> -bash: cd: /usr/share/openvfd: No such file or directory

Here is OS info:

> cat /etc/ophub-release 
> VERSION_CODEID='debian'
> VERSION_CODENAME='bullseye'
> FDTFILE='meson-sm1-x96-max-plus-100m.dtb'
> UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
> MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
> ANDROID_UBOOT='/usr/lib/u-boot/hk1box-bootloader.img'
> KERNEL_VERSION='5.15.29'
> SOC='s905x3'
> K510='1'
> PACKAGED_DATE='2022-03-19'

My box: X96max+ ((S905X3, 4+32G, 1Gbps).
I just confused that I missed any steps?

Thank you.

**Comment by ophub** [comment]
Only in yesterday's firmware, it can be flashed to the usb test, or manually uploaded into the current firmware.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led.md

**Comment by dinhchinh82** [comment]
> Only in yesterday's firmware, it can be flashed to the usb test, or manually uploaded into the current firmware.
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led.md

I will try to upload manually and test again. Thank you.

**Comment by dinhchinh82** [comment]
@ophub I confirm the led works on X96max + (5.15.x kernel).

**Comment by ophub** [comment]
ok, thanks for the feedback

**Comment by dinhchinh82** [comment]
> ok, thanks for the feedback

Can I customize the led display?
For example, if there is no ethernet network then show the E1 on the led. if network is OK, show "OK". 

Of course, there is some shell script to check the status network.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/0f7d28558fff209874fc00d1ac0b319bc63c75e4/build-armbian/common-files/files/usr/share/openvfd/conf/x96maxplus.conf#L38
