### ISSUE TITLE
求助：我家云刷bullseye无法ssh

### ISSUE THREAD

**Issue by yepisu** [ophub/amlogic-s9xxx-armbian#1791]
我家云刷了10月和9月的bullseye，启动后可以ping通，但无法ssh：ssh: connect to host 192.168.123.35 port 22: Connection timed out。
是少了操作步骤么

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_bullseye_6.1.58_server_2023.10.18.img.gz

我调整了下，你下载这个测试下

**Comment by yepisu** [comment]
上午下载了一份，准备晚上回家试，到家发现下午5点多又发了一版，就刷的下午这版，依然是可以ping通但无法ssh。然后尝试了下午的jammy，同样的问题

**Comment by yepisu** [comment]
> 上午下载了一份，准备晚上回家试，到家发现下午5点多又发了一版，就刷的下午这版，依然是可以ping通但无法ssh。然后尝试了下午的jammy，同样的问题

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/25145769/022e3704-7b0b-4924-9cbb-13bcaccd8520)

**Comment by rmoyulong** [comment]
我遇到同样ping通但是ssh失效的情况：网线是买路由器送的，插笔记本接路由器可以用，路由器接armbian小盒子没法用，后来换了一根买的6类屏蔽网线，神奇的事情发生了，能SSH了！所有建议换一根网线试试。

**Comment by Yxini** [comment]
刷了6.1.59 bullseye 依然无法启动SHH，O大尝试了很多天，依然无法解决。

**Comment by ophub** [comment]
![Snip20231028_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/ba22c8c8-7486-4b6d-9a95-2e92ce3f2c4e)
![Snip20231028_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/30b277dc-1517-4bba-acd1-70e3296009e4)
![20231028163141](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/15870880-d887-4bff-8997-855042fd2fb0)
