### ISSUE TITLE
X96Q ( Allwinner H313) unable to boot img

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [ophub/amlogic-s9xxx-armbian#1792]
**Device Information | 设备信息**
 - SOC: X96Q ( Allwinner H313 Quad Core ARM Cortex A53) 4 / 64 GB

**Armbian Version | 系统版本**
 - Kernel Version:  6.1.57 or 5.15.135
 - Release: bullseye

**Describe the bug | 问题描述**
Unable to boot any img:
- Armbian_23.11.0_allwinner_tanix-tx6_bullseye_5.15.135_server_2023.10.13.img
- Armbian_23.11.0_amlogic_s905x_bullseye_6.1.57_server_2023.10.13.img
for models: Tanix-TX6, X96-Mini
I can't find any more suitable ones. Do you have any idea which image will run on the device?

**Comment by ophub** [comment]
There is currently no support image for H313

**Comment by letsplaysfax** [comment]
Is there still no way h313 ?

**Comment by sonteo** [comment]
希望大佬早日成功，H313/armbian
