### ISSUE TITLE
Armbian系统上传文件速度非常慢

### ISSUE THREAD

**Issue by Arfarr** [ophub/amlogic-s9xxx-armbian#1796]
**Device Information | 设备信息**
 - SOC: RK3399
 - Model :JWS-3399

**Armbian Version | 系统版本**
 - Kernel Version: Linux 6.1.59-ophub
 - Release: Armbian 23.11.0-trunk Jammy

尝试过Armbian 9 月10月编译的TN3399和xiaobao两个板子的镜像，可以正常启动，网卡，usb识别正常，HDMI画面正常输出。
问题：1、通过SFTP类软件（Winscp、MobaXterm）上传文件至板子，速度非常低，随后速度归零，开始报错。
     2、docker pull镜像时刚开始有拉取速度，后停滞 直到报错拉取失败
请问大佬是否有遇到过？是系统不适配导致还是防火墙设置的原因？
![2023-10-20_225346](https://github.com/ophub/amlogic-s9xxx-armbian/assets/143853164/8a19aed6-ecff-4f68-afe8-a93c90f8f98d)

**Comment by dahai0401** [comment]
能不能分享下此编译后的固件测试下
