### ISSUE TITLE
我家云chainedbox最新的bullseye固件无法使用SHH，但是能PING通

### ISSUE THREAD

**Issue by Yxini** [ophub/amlogic-s9xxx-armbian#1798]
我家云chainedbox
 - SOC: RK3228
 - Model: chainedbox

**Armbian Version | 系统版本**
 - Kernel Version:6.1.59
 - Release: bullseye

**Describe the bug | 问题描述**
我家云chainedbox最新的bullseye固件无法使用SHH，但是能PING通。
O大尝试了很多天，依然无法解决。
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1768 在这个问题里面，有人反馈可以打补丁就能修复这个问题，因为只是小白，不知道怎么操作，所以只能发问题出来。
补丁链接：https://github.com/LaiQE/Chainedbox-build
Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/efd29b43-c0ae-4ad1-a2e5-bb601bdfa7f8)
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/83ce0edd-d56b-480b-8e7b-3912276bcd51)
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/6c5fe336-88a4-4852-b75c-33f08c36245e)

**Comment by Yxini** [comment]
以及网上流传的不掉盘补丁 
https://github.com/iam7cn/wojiayun/tree/master

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.10/Armbian_23.11.0_rockchip_chainedbox_jammy_6.1.60_server_2023.10.27.img.gz

今天的最新版应该没问题了，你试试

**Comment by ophub** [comment]
![Snip20231028_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/13aab016-1b93-4ff1-b1ef-c202bd357068)
![20231028163141](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/a6d2d8c0-35c5-44ba-be35-fd2e2758729b)
![Snip20231028_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/453c3665-4ef6-4afc-ad17-c6b8b6434a1d)

**Comment by Yxini** [comment]
成功启动，SHH也正常
