### ISSUE TITLE
King S22 (S922X) support?

### ISSUE THREAD

**Issue by mrbluecoat** [ophub/amlogic-s9xxx-armbian#18]
Would this work for the [King S22](https://zoomtaktvbox.en.made-in-china.com/product/qXuEPQcKgdra/China-Smart-4K-Android-9-4GB-RAM-64GB-ROM-S922X-TV-Box-From-Zoomtak-China.html)?

**Comment by mrbluecoat** [comment]
Or the [S78](https://www.aliexpress.com/item/1005002692802211.html)?

**Comment by ophub** [comment]
It has not been tested on devices of this brand. If you have a device, you can try to use the firmware of Beelink GT-King Pro to test whether you can boot from the USB device.

**Comment by mrbluecoat** [comment]
I'll order the S78 and let you know.

**Comment by pulpoff** [comment]
It works on x88king, but only boots from SDCARD, no USB boot possible on X88king, also dtb needs to be changed of course.

**Comment by mrbluecoat** [comment]
@pulpoff can you indicate the dtb and bin file you used? I downloaded the [latest image](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2021.12.17.1328/Armbian_21.11.0_Aml_s922x_focal_5.10.86_2021.12.17.1256.img.gz), loaded it onto a micro-SD card with Etcher, edited **uEnv.txt** to read `FDT=/dtb/amlogic/meson-g12b-gtking-pro.dtb`, and overwrote **u-boot.ext** and **u-boot.sd** with **u-boot-gtkingpro.bin**

No luck.

**Comment by pulpoff** [comment]
u should put x88king.dtb as dtb.img in root folder
