### ISSUE TITLE
Could you support "More parameter settings" for "Rebuild Armbian" action

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#180]
At current, it's convenient to use the custom parameter settings when selecting "build armbian" from Github action. 
By the way, this build take much time (more than 3 hours).
<img width="1370" alt="Screen Shot 2022-03-19 at 15 49 37" src="https://user-images.githubusercontent.com/22479095/159114509-1594b930-a35c-4821-95fb-80e8f532033e.png">

When using the "Rebuild Armbian" from Github acion, there is no custom parameter settings.
<img width="1376" alt="Screen Shot 2022-03-19 at 15 49 52" src="https://user-images.githubusercontent.com/22479095/159114549-de64dca1-d303-4a50-a80c-f573ceb2bc6b.png">

So could you support the "More parameter settings" option for "Rebuild Armbian" same as "build armbian"?

It will save much time for building armbian and resue your build.

Thank you so much.

**Comment by ophub** [comment]
Added customization options: https://github.com/ophub/amlogic-s9xxx-armbian/commit/0f7d28558fff209874fc00d1ac0b319bc63c75e4

![Snip20220319_1](https://user-images.githubusercontent.com/68696949/159117412-b0fc1205-4685-47c8-94c6-7eef2c4da300.png)

**Comment by dinhchinh82** [comment]
Great !! You are genius 🥇

**Comment by dinhchinh82** [comment]
@ophub I've tried to rebuild but unable to build bulleye, only focal available.

**Comment by ophub** [comment]
https://armbian.tnahosting.net/dl/lepotato/archive/

Select bulleye firmware, such as:

https://armbian.tnahosting.net/dl/lepotato/archive/Armbian_22.02.1_Lepotato_bullseye_current_5.10.102.img.xz

https://github.com/ophub/amlogic-s9xxx-armbian#only-import-github-actions-for-armbian-rebuild
