### ISSUE TITLE
Having two Amlogic boxes on same network causes network collision type issues

### ISSUE THREAD

**Issue by Black6spdZ** [ophub/amlogic-s9xxx-armbian#1800]
have an existing S912 Amlogic box running Armbian and when I start up a second S905x box both have sporadic network connectivity issues similar to an IP conflict even though that is not the issue here. As soon as I unplug the s905x box the network is restored.

**Comment by ophub** [comment]
Turn off the dhcp allocation function of one of them. If there are multiple devices in a LAN competing for IP allocation, there will be conflicts.

**Comment by Black6spdZ** [comment]
I thought the network interfaces were client by default? It gets an IP just fine from my DHCP server

**Comment by ophub** [comment]
run: armbian-fix

**Comment by Black6spdZ** [comment]
doesn't help.. I forgot that I do have a third amlogic s912 box on my network, but it is running LibreElec and doesn't cause any issues.. only when I bring up two running Armbian at a time

**Comment by Black6spdZ** [comment]
problem is simple.. all armbian flashed amlogic devices are sharing the same MAC.. how is this even possible?

**Comment by Black6spdZ** [comment]
attempting to set new u-boot env MAC but:

root@Armbian:~# apt-get reinstall u-boot-tools
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 171 kB of archives.
After this operation, 0 B of additional disk space will be used.
Get:1 https://deb.debian.org/debian bullseye/main arm64 u-boot-tools arm64 2021.01+dfsg-5 [171 kB]
Fetched 171 kB in 0s (543 kB/s)     
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 16082 files and directories currently installed.)
Preparing to unpack .../u-boot-tools_2021.01+dfsg-5_arm64.deb ...
Unpacking u-boot-tools (2021.01+dfsg-5) over (2021.01+dfsg-5) ...
Setting up u-boot-tools (2021.01+dfsg-5) ...
root@Armbian:~# fw_printenv
-bash: fw_printenv: command not found

**Comment by Black6spdZ** [comment]
so will we need to manually change the MAC in the future?
