### ISSUE TITLE
TX3 Mini (S912) wifi doesn't work

### ISSUE THREAD

**Issue by tuanpn2910** [ophub/amlogic-s9xxx-armbian#1805]
**Device Information | 设备信息**
 - SOC: S912
 - Model TX3 Mini

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.135
 - Release: 2023.10.13

**Describe the bug | 问题描述**
 have a Tanix TX3 Mini (S912) I update the FDT line =/dtb/amlogic/meson-gxm-q201.dtb and the installation went very well. But unfortunately WiFi doesn't work. Could you tell me what your entries in the /etc/config/wireless file look like?

Thanks!

**Comment by phuonganh2601** [comment]
**Device Information | 设备信息**

- SOC: S912
- Model TX3 Mini

**Armbian Version | 系统版本**

- Kernel Version: 5.15.135
- Release: 2023.10.13

**Describe the bug | 问题描述**
I have a Tanix TX3 Mini (S912)
Using FDT meson-gxm-q201.dtb
Wifi working very well but Ethernet not working.
What do I need to do?

Thank you!
