### ISSUE TITLE
PCAN驱动编译报错

### ISSUE THREAD

**Issue by nicktf-developer** [ophub/amlogic-s9xxx-armbian#1810]
恳请大佬指点，使用了https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads 里的GCC 12.3.1，编译时执行了scripts/basic/fixdep提示缺少libc.so.6，但实际上该文件存在于/usr/lib/aarch64-linux-gnu目录下
查看历史的ISSUE，需要先进行内核编译，执行了
armbian-kernel -u
armbian-kernel -k 5.15.136
，编译报错如下：
root@armbian:~/peak-linux-driver-8.16.0# make PCC=NO PCI=NO ISA=NO DNG=NO
make[1]: Entering directory '/root/peak-linux-driver-8.16.0/driver'
***
*** Making pcan driver in chardev mode
***
*** Host OS Release=Ubuntu v22.04
*** Host machine kernel version=5.15.136-ophub
*** Driver kernel version=5.15.136-ophub (5.15.136)
*** Path to kernel sources=/usr/src/linux-headers-5.15.136-ophub
*** use KBUILD=yes
*** use DKMS=
*** gcc version=12.3.1
***
make -C /usr/src/linux-headers-5.15.136-ophub  EXTRA_CFLAGS="-I/root/peak-linux-driver-8.16.0/driver -DNO_DEBUG -DMODVERSIONS -DNO_PARPORT_SUBSYSTEM -DUSB_SUPPORT -DNO -DNO_PCIEC_SUPPORT -DNO -DNO -DNO -DNO_NETDEV_SUPPORT -DNO_RT   -Wno-date-time" V=0 modules M=/root/peak-linux-driver-8.16.0/driver
make[2]: Entering directory '/usr/src/linux-headers-5.15.136-ophub'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626
  You are using:           gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626
  CC [M]  /root/peak-linux-driver-8.16.0/driver/src/pcan_main.o
scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
make[3]: *** [scripts/Makefile.build:289: /root/peak-linux-driver-8.16.0/driver/src/pcan_main.o] Error 127
make[3]: *** Deleting file '/root/peak-linux-driver-8.16.0/driver/src/pcan_main.o'
make[2]: *** [Makefile:1909: /root/peak-linux-driver-8.16.0/driver] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.15.136-ophub'
make[1]: *** [Makefile:523: all] Error 2
make[1]: Leaving directory '/root/peak-linux-driver-8.16.0/driver'
make: *** [Makefile:84: all] Error 2

**Comment by nicktf-developer** [comment]
解决了，替换开发版内核，必须先替换其他版本，再换回来
提个建议 固件打包的时候能否直接集成开发版内核，默认header是交叉编译的打包，armbian里无法执行，查看了很久的issue才知道，并且同版本不会替换开发版内核，踩坑时间有点长

**Comment by ophub** [comment]
dev的太稳定，而且打了补丁可以不用u-boot启动，这样太容易使用了，不方便测试折腾，用stable等内核可以踩坑，方便找到最适合的组合。

**Comment by nicktf-developer** [comment]
估计是交叉编译的原因，打包自带的header，如果编译驱动就需要调用header里的script，但是armbian里无法执行，想重新编译script的部分工具，源码又不全，重新拉取dev内核或者全部重新内核编译又太费时了，这个大佬考虑吧。
