### ISSUE TITLE
E900v22d刷armbian，启动后usb口插入移动硬盘正常挂载，重启后无法发现移动硬盘

### ISSUE THREAD

**Issue by UnknowSelf** [ophub/amlogic-s9xxx-armbian#1811]
**Device Information | 设备信息**
 - SOC:S905L3A
 - Model [E900v22d]

**Armbian Version | 系统版本**
 - Kernel Version:5.15.135
 - Release: jammy

**Describe the bug | 问题描述**
E900v22d刷armbian，启动后usb口插入移动硬盘正常挂载，重启后无法识别/发现移动硬盘
1.正常启动后，usb口接入移动硬盘，可正常发现
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11157598/1168f815-c083-422b-b3ab-2ac0a828915c)
2.重启系统，reboot启动后，usb口接的移动硬盘无法正常识别/发现
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11157598/204b40aa-7250-400f-90be-37d067ddcb06)
3.启动后重新插拔移动硬盘，可以正常识别

**Comment by UnknowSelf** [comment]
一开始以为是硬盘盒的问题，换了个硬盘盒还是一样的现象
求助 @ophub

**Comment by UnknowSelf** [comment]
![Uploading image.png…]()
补充重启的dmesg信息

**Comment by rodren-lion** [comment]
是不能挂载 还是挂载不了。。

**Comment by UnknowSelf** [comment]
> 是不能挂载 还是挂载不了。。

准确的说是，重启后发现不了硬盘

**Comment by ophub** [comment]
/etc/custom_service)
/start_service.sh

添加一条挂载命令，让设备启动后再挂载一次。

正常应该是在/etc/fstab里添加一条挂载信息。

两处都使用uuid挂载，不要使用sda这个lablr

**Comment by UnknowSelf** [comment]
> /etc/custom_service) /start_service.sh 添加一条挂载命令，让设备启动后再挂载一次。
> 
> 正常应该是在/etc/fstab里添加一条挂载信息。
> 
> 两处都使用uuid(blkid查看)挂载，不要使用sda这个lable
> 
> 大硬盘建议使用有独立供电的

抱歉，我可能没描述清楚，我的问题是重启后发现不了sda这个设备
硬盘盒是有独立供电

**Comment by ophub** [comment]
用uuid

**Comment by seamt** [comment]
我瞎猜：
启动时挂载usb存储，是uboot的驱动在作用；
启动后挂载usb存储，是内核的驱动在作用；
uboot的驱动不稳定。如果存储用usb3.0接口，则挂载失败的概率增大。如果存储用usb2.0接口，仍然有一定挂载失败的概率。使用usb2.0hub连接盒子和存储，可以提高挂载成功率，但是也不能彻底排除挂载失败问题。
这个仓库以前有一篇issue，分析过uboot的usb存储驱动缺陷。
不知道你的硬盘接口是USB2.0还是3.0，如果是3.0（可能2.0的硬盘已经少见了），建议你连接一个USB2.0hub再试。
如果你手中有多个存储设备、读卡器、hub、u盘，建议你在盒子上充分测试与uboot的兼容。哪个型号的设备成功率高，你自己记住，以后尽量使用成功率高的设备。这点对每个玩家非常重要，至少是在uboot的usb驱动完善之前。

**Comment by UnknowSelf** [comment]
找到问题了，原因是**给硬盘盒供电的功率太小了**，换了一个更大功率的适配器就好了
感谢大家的回复
@rodren-lion @ophub @seamt

**Comment by seamt** [comment]
> 找到问题了，原因是**给硬盘盒供电的功率太小了**，换了一个更大功率的适配器就好了 感谢大家的回复 @rodren-lion @ophub @seamt

不能用的电源功率是多少？能用的电源功率是多少？硬盘盒要求的功率是多少？
希望分享给大家参考。

**Comment by UnknowSelf** [comment]
我用盒子自带的usb接口(5V/2A)给硬盘盒供电，电流不够导致重启盒子后硬盘盒不能被识别。因为盒子启动后即使给硬盘盒不供电也能正常使用，所以忽视了硬盘盒的电源规格。后来我手机充电器(10V/6.5A)给硬盘盒供电，盒子重启后能正常识别，咨询商家后，商家说硬盘盒需要的电源是**5V/4A**，重新购买5V/4A的电源适配器给硬盘盒供电，一切正常

**Comment by ophub** [comment]
谢谢分享
