### ISSUE TITLE
armbian从6.1改到5.4,一直失败

### ISSUE THREAD

**Issue by lsf343634352** [ophub/amlogic-s9xxx-armbian#1812]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
我把5.4的文件都放到正确位置,但是刷出来还是6.1的版本
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/50e7fb00-e8cb-43dc-b2c6-05258227b453)

**Comment by ophub** [comment]
放哪了？怎么刷的？

**Comment by lsf343634352** [comment]
主BOOT盘里的文件和rootfs/usr/src,rootfs/usr/lib

**Comment by ophub** [comment]
放那没用，看文档

**Comment by lsf343634352** [comment]
我记得以前openwrt可以改哪个文件里的内核数字,然后再刷就会选择和数字一样的内核了

**Comment by lsf343634352** [comment]
> 放那没用，看文档

O大有没有群或者电报

**Comment by ophub** [comment]
armbian和OpenWrt都有专用的内核更新脚本，使用脚本更新。手动不知道你操作的什么。
armbian: armbian-update
openwrt: openwrt-kernel

**Comment by lsf343634352** [comment]
> armbian和OpenWrt都有专用的内核更新脚本，使用脚本更新。手动不知道你操作的什么。 armbian: armbian-update openwrt: openwrt-kernel

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/65b9b630-85c9-46a8-9560-cf9646bc7a2a)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/4364ccdc-7ab9-44fa-9908-074ac4674f77)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/43579b67-c30e-49d2-8aa3-265903db503d)
这是我放的,我以为放进去再刷就会变成5.几的了

**Comment by ophub** [comment]
放可以，再刷就多余了。

**Comment by lsf343634352** [comment]
> 放可以，再刷就多余了。

O大,有没有办法可以,我不需要烧录U盘,只要把这些放进去再刷就可以直接改版本

**Comment by ophub** [comment]
armbian-update

**Comment by lsf343634352** [comment]
> armbian-update

O大的意思是把U盘的系统直接给更成想要的版本,对吧

**Comment by ophub** [comment]
对
看第10节：
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
