### ISSUE TITLE
小宝NAS无法驱动sata

### ISSUE THREAD

**Issue by Mango1151** [ophub/amlogic-s9xxx-armbian#1813]
小宝NAS的armbian 6.1.52 57 59都无法驱动sata，希望能解决下。求能驱动小宝NAS能驱动SATA的版本，谢谢

**Comment by gzxief** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1674

目前能用的armbian镜像如下：
https://file.erix.vip/f/76ff3f32b89941f78482/?dl=1
密码：xiaobaoNas

**Comment by Mango1151** [comment]
收到，谢谢！！






&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-armbian"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月30日(星期一) 上午8:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-armbian] 小宝NAS无法驱动sata (Issue #1813)





 
#1674
 
目前能用的armbian镜像如下：
 https://file.erix.vip/f/76ff3f32b89941f78482/?dl=1
 密码：xiaobaoNas

**Comment by gzxief** [comment]
某大神提供了28.03+6.1.53的包，正常sata，昨天突发奇想，下载了ophub的23.11.0的包移植进去rootfs里（需要chroot 再修改root密码，还需要修改清华源），能成功运行sata，也能更新到6.1.60内核，再下载ophub包，烧录到TF卡，启动小宝，无法识别sata，然后我把备份的6.1.53内核包刷入，依旧无法识别sata，目测应该是boot文件夹控制sata，今晚测试移植boot包看看能不能启动sata
![20231102093103](https://github.com/ophub/amlogic-s9xxx-armbian/assets/82856050/67217ff1-0bdc-4a72-b0e1-40b85e5c15cc)

**Comment by gzxief** [comment]
还需要修改ssh_config让root登录

**Comment by gzxief** [comment]
移植boot测试失败，移植后 可以启动但还不是识别sata

**Comment by yshtz** [comment]
> 某大神提供了28.03+6.1.53的包，正常sata，昨天突发奇想，下载了ophub的23.11.0的包移植进去rootfs里（需要chroot 再修改root密码，还需要修改清华源），能成功运行sata，也能更新到6.1.60内核，再下载ophub包，烧录到TF卡，启动小宝，无法识别sata，然后我把备份的6.1.53内核包刷入，依旧无法识别sata，目测应该是boot文件夹控制sata，今晚测试移植boot包看看能不能启动sata ![20231102093103](https://private-user-images.githubusercontent.com/82856050/279839911-67217ff1-0bdc-4a72-b0e1-40b85e5c15cc.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNDcxMzgsIm5iZiI6MTcwODI0NjgzOCwicGF0aCI6Ii84Mjg1NjA1MC8yNzk4Mzk5MTEtNjcyMTdmZjEtMGJkYy00YTcyLWIwZTEtNDBiODVlNWMxNWNjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE4VDA5MDAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2ZTM5N2EwYTZlY2Y2YjZiZDc5ZmExMGMyNWViN2M1ZDNjODg1ZTQ3MTBiZWFlMjRiM2U2NWRiZWQ0ZTVjNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gNHQfeMK5anq9SepA550C9yheeu8uTv_dSt_HknfXEg)
大神的28.03+6.1.53的包能够分享一下吗？非常感谢！
