### ISSUE TITLE
借这里问个问题

### ISSUE THREAD

**Issue by o5rhaxzc** [ophub/amlogic-s9xxx-armbian#1818]
在咸鱼收了一台矿渣，芯片是瑞芯微的px30，自带了64g的emmc，只要20块钱包邮，但是没有原系统
在google找到了一个挖矿的系统，写进sd卡插上能正常启动，但是系统里缺很多东西
我用7z打开挖矿系统的img发现里面有一个dtb文件，想知道这个dtb能用来打包armbian或者其它系统吗

矿渣官网
https://shop.bobber.com/products/bobcat-miner-300

挖矿系统
https://crankk.io/downloads/
https://crkk1.fra1.digitaloceanspaces.com/crankkos/crankkos-bobcatpx30-1.0.0-beta.9.img.xz

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149476903/b049eeb7-5d74-4ffd-9b0f-a5f116684cf9)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149476903/de5b92ec-5a92-4304-9c30-7c123391a324)

**Comment by ophub** [comment]
安卓系统的不行。
ubuntu/debian的可以。

**Comment by o5rhaxzc** [comment]
这个固件里还有一个分区是这样的内容
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149476903/e42baa65-ed8c-4b13-8937-0e69e81713fb)

**Comment by ophub** [comment]
/usr/lib 这目录下有没有 u-boot-xx

**Comment by ophub** [comment]
有u-boot的话简单一点，理论上可以直接使用在armbian

**Comment by o5rhaxzc** [comment]
那可以直接用dtb在本地打包吗

**Comment by ophub** [comment]
linux的可以试试

**Comment by o5rhaxzc** [comment]
本地打包可以用自定义的img文件吗
