### ISSUE TITLE
sudo ./recompile => [ERROR] Please run this script on ubuntu-20.04

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#182]
Hi @ophub 
the ./recompile command cannot be launched under armbian..
Would it be possible to adjust the script so that we can use it under armbian too
```
:/mnt/Git/amlogic-s9xxx-armbian$ sudo ./recompile -d -k 5.15.30 -n -ac2n -r kernel.org
Welcome to compile kernel!

[ERROR] Please run this script on ubuntu-20.04
```

**Comment by ophub** [comment]
The current installation packages, etc. only consider Ubuntu, which is different from armbian. The previous version was completely used under armbian, but I deleted it.

**Comment by MX10-AC2N** [comment]
it seems to me that it would be useful for all to be able to do the constructions on the armbian system. Since we can install armbian thanks to your releases, we might as well make the constructions directly with your releases..
Maybe create 2 different scripts one for ubuntu and another for armbian..
Thanks again..

**Comment by ophub** [comment]
The compilation speed in github actions is faster than the armbian compilation using s922x's gtk-pro, do not plan to go back to using armbian compilation
