### ISSUE TITLE
请教大佬关于安卓分区表导致的No partition table - mmc 2问题

### ISSUE THREAD

**Issue by Eric-168** [ophub/amlogic-s9xxx-armbian#1821]
看了一些反馈，我发现我的问题可能是由于安卓分区表的原因导致的No partition table - mmc 2
写入emmc后，无法启动，tll查看是因为没有bootloader没有找到emmc的分区表

**Comment by Eric-168** [comment]
![微信截图_20231031203750](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34979606/75311067-039a-4c1b-9b4b-a351e9a985ed)

**Comment by Eric-168** [comment]
@ophub 应该是bootloader引导的时候，boot分区偏移量的问题，大佬能给看下吗

**Comment by ophub** [comment]
不按模版提问，看不懂你在做什么。
我猜你是在自己改写入脚本？你改了什么？设置成什么值了？
通常大家都是直接刷第三方的root版9.0+安卓。

**Comment by Eric-168** [comment]
> 不按模版提问，看不懂你在做什么。 我猜你是在自己改写入脚本？你改了什么？设置成什么值了？ 通常大家都是直接刷第三方的root版9.0+安卓。

不好意思github用的不太熟，我给你个我遇到的情况的连接
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1519
类似这个连接里的情况，刷完之后提示No partition table - mmc 2
![1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34979606/7d8d1172-065b-4ac8-932b-f1175e68ee23)
![2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34979606/9dd870bd-3e05-447a-866d-b614e33e5a9e)

**Comment by Eric-168** [comment]
由于找不到分区，会自动查找tftp
