### ISSUE TITLE
cm311-1扩容128G EMMC U盘启动成功,写入成功,启动失败

### ISSUE THREAD

**Issue by lsf343634352** [ophub/amlogic-s9xxx-armbian#1823]
S905l3 
CM311-1

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
今天换了个128G的EMMC,然后用U盘启动成功,使用armbian安装命令代码117,也安装成功
拔掉U盘后单独启动,启动不了

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/197d6bd4-19e2-403b-a7e7-3007d1ce2e38)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/3c6114b6-ec7c-41d7-9261-cedc73fd48a1)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/b62eb1f2-a32c-4d30-a90d-3883add70be9)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/1855e718-234f-467a-8089-9f05764aa221)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/ccfabddc-a722-45a6-8f0c-a2c33d426774)

uboot time: 7535555 us
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.15.128-ophub (root@armbian-rock5b) (aarch64-none-elf-gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626, GNU ld (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 2.40.0.20230627) #1 SMP PREEMPT Sun Aug 27 10:47:10 CST 2023
[    0.000000] Machine model: Amlogic Meson GXL (S905L2) X7 5G Tv Box
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x0000000062800000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x0000000077ffffff]
[    0.000000]   DMA32    empty
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000000ffffff]
[    0.000000]   node   0: [mem 0x0000000001000000-0x0000000004ffffff]
[    0.000000]   node   0: [mem 0x0000000005000000-0x00000000072fffff]
[    0.000000]   node   0: [mem 0x0000000007300000-0x000000000fffffff]
[    0.000000]   node   0: [mem 0x0000000010000000-0x00000000101fffff]
[    0.000000]   node   0: [mem 0x0000000010200000-0x0000000077ffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000077ffffff]
[    0.000000] psci: probing for conduit method from DT.
[    0.000000] psci: PSCIv0.2 detected in firmware.
[    0.000000] psci: Using standard PSCI v0.2 function IDs
[    0.000000] psci: Trusted OS migration not required
[    0.000000] percpu: Embedded 19 pages/cpu s37784 r8192 d31848 u77824
[    0.000000] Detected VIPT I-cache on CPU0
[    0.000000] CPU features: detected: ARM erratum 845719
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 483840
[    0.000000] Kernel command line: root=UUID=a17e0c54-72e2-4c9c-ab6b-62015175797d rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 mac=f6:4d:9c:dd:58:2c
[    0.000000] Unknown kernel command line parameters "cgroup_enable=memory cgroup_memory=1 mac=f6:4d:9c:dd:58:2c", will be passed to user space.
[    0.000000] Dentry cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] Inode-cache hash table entries: 131072 (order: 8, 1048576 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 1567984K/1966080K available (15296K kernel code, 2730K rwdata, 4836K rodata, 3776K init, 891K bss, 135952K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=8 to nr_cpu_ids=4.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 30 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] Root IRQ handler: gic_handle_irq
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] irq_meson_gpio: 110 to 8 gpio interrupt mux initialized
[    0.000000] arch_timer: cp15 timer(s) running at 24.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x588fe9dc0, max_idle_ns: 440795202592 ns
[    0.000001] sched_clock: 56 bits at 24MHz, resolution 41ns, wraps every 4398046511097ns
[    0.000577] Console: colour dummy device 80x25
[    0.000958] printk: console [tty0] enabled
[    0.000999] Calibrating delay loop (skipped), value calculated using timer frequency.. 48.00 BogoMIPS (lpj=80000)
[    0.001022] pid_max: default: 32768 minimum: 301
[    0.001214] LSM: Security Framework initializing
[    0.001329] SELinux:  Initializing.
[    0.001602] Mount-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.001628] Mountpoint-cache hash table entries: 4096 (order: 3, 32768 bytes, linear)
[    0.003826] rcu: Hierarchical SRCU implementation.
[    0.005184] EFI services will not be available.
[    0.005640] smp: Bringing up secondary CPUs ...
[    0.006309] Detected VIPT I-cache on CPU1
[    0.006374] CPU1: Booted secondary processor 0x0000000001 [0x410fd034]
[    0.007127] Detected VIPT I-cache on CPU2
[    0.007184] CPU2: Booted secondary processor 0x0000000002 [0x410fd034]
[    0.007878] Detected VIPT I-cache on CPU3
[    0.007928] CPU3: Booted secondary processor 0x0000000003 [0x410fd034]
[    0.008012] smp: Brought up 1 node, 4 CPUs
[    0.008079] SMP: Total of 4 processors activated.
[    0.008090] CPU features: detected: 32-bit EL0 Support
[    0.008100] CPU features: detected: 32-bit EL1 Support
[    0.008113] CPU features: detected: CRC32 instructions
[    0.008795] CPU: All CPU(s) started at EL2
[    0.008826] alternatives: patching kernel code
[    0.010306] devtmpfs: initialized
[    0.018175] Registered cp15_barrier emulation handler
[    0.018216] Registered setend emulation handler
[    0.018378] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 6370867519511994 ns
[    0.018409] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.024933] prandom: seed boundary self test passed
[    0.026448] prandom: 100 self tests passed
[    0.049387] prandom32: self test passed (less than 6 bits correlated)
[    0.049441] pinctrl core: initialized pinctrl subsystem
[    0.050073] DMI not present or invalid.
[    0.050624] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.052666] DMA: preallocated 256 KiB GFP_KERNEL pool for atomic allocations
[    0.052902] DMA: preallocated 256 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.053107] DMA: preallocated 256 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.053205] audit: initializing netlink subsys (disabled)
[    0.053448] audit: type=2000 audit(0.049:1): state=initialized audit_enabled=0 res=1
[    0.054548] thermal_sys: Registered thermal governor 'step_wise'
[    0.054860] cpuidle: using governor ladder
[    0.055070] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.055189] ASID allocator initialised with 65536 entries
[    0.055377] Serial: AMBA PL011 UART driver
[    0.073490] platform c883a000.hdmi-tx: Fixing up cyclic dependency with d0100000.vpu
[    0.077968] platform cvbs-connector: Fixing up cyclic dependency with d0100000.vpu
[    0.078257] platform hdmi-connector: Fixing up cyclic dependency with c883a000.hdmi-tx
[    0.087406] HugeTLB registered 1.00 GiB page size, pre-allocated 0 pages
[    0.087442] HugeTLB registered 32.0 MiB page size, pre-allocated 0 pages
[    0.087456] HugeTLB registered 2.00 MiB page size, pre-allocated 0 pages
[    0.087469] HugeTLB registered 64.0 KiB page size, pre-allocated 0 pages
[    1.583277] cryptd: max_cpu_qlen set to 1000
[    1.586902] "cryptomgr_test" (91) uses obsolete ecb(arc4) skcipher
[    1.598557] alg: No test for 842 (842-generic)
[    1.598696] alg: No test for 842 (842-scomp)
[    1.693348] DRBG: Continuing without Jitter RNG
[    1.785919] raid6: neonx8   gen()  2215 MB/s
[    1.842661] raid6: neonx8   xor()  1600 MB/s
[    1.899414] raid6: neonx4   gen()  2170 MB/s
[    1.956153] raid6: neonx4   xor()  1523 MB/s
[    2.012903] raid6: neonx2   gen()  2064 MB/s
[    2.069651] raid6: neonx2   xor()  1413 MB/s
[    2.126408] raid6: neonx1   gen()  1772 MB/s
[    2.183145] raid6: neonx1   xor()  1214 MB/s
[    2.239901] raid6: int64x8  gen()  1389 MB/s
[    2.296626] raid6: int64x8  xor()   740 MB/s
[    2.353387] raid6: int64x4  gen()  1571 MB/s
[    2.410154] raid6: int64x4  xor()   807 MB/s
[    2.466857] raid6: int64x2  gen()  1398 MB/s
[    2.523576] raid6: int64x2  xor()   749 MB/s
[    2.580304] raid6: int64x1  gen()  1035 MB/s
[    2.637025] raid6: int64x1  xor()   517 MB/s
[    2.637037] raid6: using algorithm neonx8 gen() 2215 MB/s
[    2.637048] raid6: .... xor() 1600 MB/s, rmw enabled
[    2.637059] raid6: using neon recovery algorithm
[    2.637382] fbcon: Taking over console
[    2.637428] ACPI: Interpreter disabled.
[    2.639552] iommu: Default domain type: Translated
[    2.639583] iommu: DMA domain TLB invalidation policy: strict mode
[    2.639981] vgaarb: loaded
[    2.640534] SCSI subsystem initialized
[    2.640789] usbcore: registered new interface driver usbfs
[    2.640836] usbcore: registered new interface driver hub
[    2.640880] usbcore: registered new device driver usb
[    2.641371] mc: Linux media interface: v0.10
[    2.641403] videodev: Linux video capture interface: v2.00
[    2.641700] EDAC MC: Ver: 3.0.0
[    2.642779] Advanced Linux Sound Architecture Driver Initialized.
[    2.643989] clocksource: Switched to clocksource arch_sys_counter
[    2.644354] VFS: Disk quotas dquot_6.6.0
[    2.644439] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    2.644616] FS-Cache: Loaded
[    2.645111] pnp: PnP ACPI: disabled
[    2.651864] NET: Registered PF_INET protocol family
[    2.652073] IP idents hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    2.653319] tcp_listen_portaddr_hash hash table entries: 1024 (order: 2, 16384 bytes, linear)
[    2.653372] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    2.653450] TCP established hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    2.653571] TCP bind hash table entries: 16384 (order: 6, 262144 bytes, linear)
[    2.653779] TCP: Hash tables configured (established 16384 bind 16384)
[    2.654092] MPTCP token hash table entries: 2048 (order: 3, 49152 bytes, linear)
[    2.654211] UDP hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    2.654264] UDP-Lite hash table entries: 1024 (order: 3, 32768 bytes, linear)
[    2.654463] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    2.654499] NET: Registered PF_XDP protocol family
[    2.654521] PCI: CLS 0 bytes, default 64
[    2.654807] Trying to unpack rootfs image as initramfs...
[    2.661457] hw perfevents: enabled with armv8_cortex_a53 PMU driver, 7 counters available
[    2.661994] kvm [1]: IPA Size Limit: 40 bits
[    2.662894] kvm [1]: vgic interrupt IRQ9
[    2.663070] kvm [1]: Hyp mode initialized successfully
[    3.500491] Freeing initrd memory: 19628K
[    3.722598] Initialise system trusted keyrings
[    3.722891] workingset: timestamp_bits=46 max_order=19 bucket_order=0
[    3.729389] zbud: loaded
[    3.731088] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.731630] fuse: init (API version 7.34)
[    3.732140] SGI XFS with ACLs, security attributes, quota, no debug enabled
[    3.772687] NET: Registered PF_ALG protocol family
[    3.826554] xor: measuring software checksum speed
[    3.830756]    8regs           :  2365 MB/sec
[    3.834290]    32regs          :  2802 MB/sec
[    3.839085]    arm64_neon      :  2063 MB/sec
[    3.839097] xor: using function: 32regs (2802 MB/sec)
[    3.839113] Key type asymmetric registered
[    3.839125] Asymmetric key parser 'x509' registered
[    3.839285] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 245)
[    3.839475] io scheduler mq-deadline registered
[    3.839491] io scheduler kyber registered
[    3.839657] io scheduler bfq registered
[    3.865155] soc soc0: Amlogic Meson Unknown (Unknown) Revision 2a:e (c5:2) Detected
[    3.867641] Serial: 8250/16550 driver, 5 ports, IRQ sharing enabled
[    3.869657] Serial: AMBA driver
[    3.870055] c81004c0.serial: ttyAML0 at MMIO 0xc81004c0 (irq = 22, base_baud = 1500000) is a meson_uart
[    4.904008] printk: console [ttyAML0] enabled
[    4.918088] brd: module loaded
[    4.984844] loop: module loaded
[    4.991994] ehci_hcd: USB 2.0 'Enhanced' Host Controller (EHCI) Driver
[    4.992911] ehci-pci: EHCI PCI platform driver
[    4.997408] ehci-platform: EHCI generic platform driver
[    5.003100] usbcore: registered new interface driver cdc_wdm
[    5.008134] usbcore: registered new interface driver usb-storage
[    5.014581] mousedev: PS/2 mouse device common for all mice
[    5.020784] SPI driver rmi4_spi has no spi_device_id for syna,rmi4-spi
[    5.026890] meson-vrtc c81000a8.rtc: registered as rtc0
[    5.031235] meson-vrtc c81000a8.rtc: setting system clock to 1970-01-01T00:00:05 UTC (5)
[    5.039788] i2c_dev: i2c /dev entries driver
[    5.045813] Registered IR keymap rc-cec
[    5.047400] rc rc0: meson_ao_cec as /devices/platform/soc/c8100000.bus/c8100100.cec/rc/rc0
[    5.055582] input: meson_ao_cec as /devices/platform/soc/c8100000.bus/c8100100.cec/rc/rc0/input0
[    5.067825] sdhci: Secure Digital Host Controller Interface driver
[    5.070264] sdhci: Copyright(c) Pierre Ossman
[    5.074599] Synopsys Designware Multimedia Card Interface Driver
[    5.081381] sdhci-pltfm: SDHCI platform and OF driver helper
[    5.081984] meson-gx-mmc d0072000.mmc: Got CD GPIO
[    5.083025] meson-gx-mmc d0074000.mmc: allocated mmc-pwrseq
[    5.088834] meson-sm: secure-monitor enabled
[    5.103052] gxl-crypto c883e000.crypto: will run requests pump with realtime priority
[    5.108549] gxl-crypto c883e000.crypto: will run requests pump with realtime priority
[    5.119864] hid: raw HID events driver (C) Jiri Kosina
[    5.121423] usbcore: registered new interface driver usbhid
[    5.126661] gpio irq setup: hwirq: 0x3A irqfirst: 0x34 irqlast: 0x3A pin[48]
[    5.126907] usbhid: USB HID core driver
[    5.134130] genirq: Setting trigger mode 3 for irq 46 failed (meson_gpio_irq_set_type+0x0/0x100)
[    5.138136] platform-mhu c883c404.mailbox: Platform MHU Mailbox registered
[BL31]: tee size: 0
[    5.161139] Initializing XFRM netlink socket
[    5.162020] NET: Registered PF_INET6 protocol family
[    5.202166] Segment Routing with IPv6
[    5.202213] RPL Segment Routing with IPv6
[    5.204398] In-situ OAM (IOAM) with IPv6
[    5.208251] sit: IPv6, IPv4 and MPLS over IPv4 tunneling driver
[    5.214951] NET: Registered PF_PACKET protocol family
[    5.219096] NET: Registered PF_KEY protocol family
[    5.223878] 8021q: 802.1Q VLAN Support v1.8
[    5.228396] registered taskstats version 1
[    5.232015] Loading compiled-in X.509 certificates
[    5.239003] zswap: loaded using pool zstd/zbud
[    5.241643] Key type .fscrypt registered
[    5.245021] Key type fscrypt-provisioning registered
[    5.250943] Btrfs loaded, crc32c=crc32c-generic, zoned=no, fsverity=no
[    5.285888] meson-drm d0100000.vpu: Queued 3 outputs on vpu
[    5.314056] meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d)
[    5.316559] meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops 0xffffffc00a0dfdb8): -19
[    5.324986] meson-drm d0100000.vpu: Couldn't bind all components
[    5.331308] meson-drm d0100000.vpu: master bind failed: -19
[    5.338748] meson8b-dwmac c9410000.ethernet: IRQ eth_wake_irq not found
[    5.343016] meson8b-dwmac c9410000.ethernet: IRQ eth_lpi not found
[    5.349261] meson8b-dwmac c9410000.ethernet: PTP uses main clock
[    5.356089] meson8b-dwmac c9410000.ethernet: User ID: 0x11, Synopsys ID: 0x37
[    5.362170] meson8b-dwmac c9410000.ethernet:         DWMAC1000
[    5.367421] meson8b-dwmac c9410000.ethernet: DMA HW capability register supported
[    5.374748] meson8b-dwmac c9410000.ethernet: RX Checksum Offload Engine supported
[    5.382159] meson8b-dwmac c9410000.ethernet: COE Type 2
[    5.383542] mmc2: new HS200 MMC card at address 0001
[    5.387332] meson8b-dwmac c9410000.ethernet: TX Checksum insertion supported
[    5.387338] meson8b-dwmac c9410000.ethernet: Wake-Up On Lan supported
[    5.393329] mmcblk2: mmc2:0001 DA4128 116 GiB
[    5.399242] meson8b-dwmac c9410000.ethernet: Normal descriptors
[    5.407760]  mmcblk2: p1 p2
[    5.410020] meson8b-dwmac c9410000.ethernet: Ring mode enabled
[    5.416963] mmcblk2boot0: mmc2:0001 DA4128 4.00 MiB
[    5.418646] meson8b-dwmac c9410000.ethernet: Enable RX Mitigation via HW Watchdog Timer
[    5.422219] dwc3-meson-g12a d0078080.usb: USB2 ports: 2
[    5.426120] mmcblk2boot1: mmc2:0001 DA4128 4.00 MiB
[    5.429343] dwc3-meson-g12a d0078080.usb: USB3 ports: 0
[    5.453721] mmcblk2rpmb: mmc2:0001 DA4128 16.0 MiB, chardev (240:0)
[    5.948578] dwc2 c9100000.usb: supply vusb_d not found, using dummy regulator
[    5.950242] dwc2 c9100000.usb: supply vusb_a not found, using dummy regulator
[    5.957484] dwc2 c9100000.usb: EPs: 7, dedicated fifos, 712 entries in SPRAM
[    5.966347] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    5.969875] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 1
[    5.977349] xhci-hcd xhci-hcd.1.auto: hcc params 0x0228f664 hci version 0x100 quirks 0x0000000002010010
[    5.986559] xhci-hcd xhci-hcd.1.auto: irq 48, io mem 0xc9000000
[    5.992557] xhci-hcd xhci-hcd.1.auto: xHCI Host Controller
[    5.998004] xhci-hcd xhci-hcd.1.auto: new USB bus registered, assigned bus number 2
[    6.005400] xhci-hcd xhci-hcd.1.auto: Host supports USB 3.0 SuperSpeed
[    6.012008] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.15
[    6.020048] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.027206] usb usb1: Product: xHCI Host Controller
[    6.032035] usb usb1: Manufacturer: Linux 5.15.128-ophub xhci-hcd
[    6.038073] usb usb1: SerialNumber: xhci-hcd.1.auto
[    6.043417] hub 1-0:1.0: USB hub found
[    6.046653] hub 1-0:1.0: 2 ports detected
[    6.051031] usb usb2: We don't know the algorithms for LPM for this host, disabling LPM.
[    6.058712] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.15
[    6.066796] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    6.073953] usb usb2: Product: xHCI Host Controller
[    6.078946] usb usb2: Manufacturer: Linux 5.15.128-ophub xhci-hcd
[    6.084829] usb usb2: SerialNumber: xhci-hcd.1.auto
[    6.090168] hub 2-0:1.0: USB hub found
[    6.093588] hub 2-0:1.0: config failed, hub doesn't have any ports! (err -19)
[    6.104434] meson-gx-mmc d0070000.mmc: allocated mmc-pwrseq
[    6.104878] scpi_protocol scpi: SCP Protocol legacy pre-1.0 firmware
get_dvfs_info 0003
[    6.142394] ALSA device list:
[    6.142438]   No soundcards found.
[    6.144794] Freeing unused kernel memory: 3776K
[    6.154069] Run /init as init process
[    6.763513] lima d00c0000.gpu: gp - mali450 version major 0 minor 0
[    6.764292] lima d00c0000.gpu: pp0 - mali450 version major 0 minor 0
[    6.772286] lima d00c0000.gpu: pp1 - mali450 version major 0 minor 0
[    6.777905] lima d00c0000.gpu: l2 cache 8K, 4-way, 64byte cache line, 128bit external bus
[    6.786145] lima d00c0000.gpu: l2 cache 64K, 4-way, 64byte cache line, 128bit external bus
[    6.794564] lima d00c0000.gpu: bus rate = 166666667
[    6.797944] lima d00c0000.gpu: mod rate = 24000000
[    6.802793] lima d00c0000.gpu: dev_pm_opp_set_regulators: no regulator (mali) found: -19
[    6.815265] [drm] Initialized lima 1.1.0 20191231 for d00c0000.gpu on minor 0
[    6.960344] blk_update_request: I/O error, dev mmcblk2, sector 8 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[    6.967878] blk_update_request: I/O error, dev mmcblk2, sector 8 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    6.975374] Buffer I/O error on dev mmcblk2, logical block 1, async page read
[    7.158026] mmc2: tuning execution failed: -5
[    7.158169] mmc2: tried to HW reset card, got error -5
[    7.162522] blk_update_request: I/O error, dev mmcblk2, sector 239648 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
[    7.173427] blk_update_request: I/O error, dev mmcblk2, sector 239648 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
[    7.183355] Buffer I/O error on dev mmcblk2p1, logical block 4, async page read
done.

**Comment by lsf343634352** [comment]
又写入了一次,又出现问题
![Uploading image.png…]()
到这就定身不动了

**Comment by ophub** [comment]
![Snip20231102_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/18c75e4a-83a5-4a75-bbdc-9abef69301e9)

短接线刷安卓修复，重新刷，降低dtb频率使用。

**Comment by lsf343634352** [comment]
![3457a1fc42fae7812c7e2435a5e7446](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/92e8c49b-7106-441d-8d8e-710fdb540c2e)
刷了这个包,识别EMMC没问题,然后再刷armbian的时候出现下面的
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/9ea6920b-01c9-4f5f-abe2-f8b766132f3f)

**Comment by ophub** [comment]
I/O错误，频率高的问题，降低dtb频繁。看仓库的文档。

**Comment by lsf343634352** [comment]
> I/O 错误，频率高的问题，降低 dtb 密度。查看仓库的文档。

已解决,请O大关帖吧,先重刷安卓9固件,然后改安装数字代码所需的DTB的频率,然后可以正常使用,谢谢O大

**Comment by liang-x-j** [comment]
> > I/O 错误，频率高的问题，降低 dtb 密度。查看仓库的文档。
> 
> 已解决,请O大关帖吧,先重刷安卓9固件,然后改安装数字代码所需的DTB的频率,然后可以正常使用,谢谢O大

请问你改的多少。可以告诉我不。
