### ISSUE TITLE
自移植小宝nas的armbian23.11+6.1.61

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#1827]
感谢寒晨（CJ1324）,感谢ophub，花了2小时移植打包，移植出来Armbian_23.11.0_rockchip_xiaobao_bullseye_6.1.61,烧录到TF卡上，能启动，也能驱动sata，有个小瑕疵，第一次启动时，提示waiting for system to booting，等待2-3分钟后，就可以运行，之后启动都正常，也可以armbian-update最新内核，下载地址如下：请大神再修改或提取
https://www.123pan.com/s/doe8Vv-izIw3.html

**Comment by ophub** [comment]
支持
对sata的支持与否是哪里影响了？不是内核部分？

**Comment by gzxief** [comment]
> 支持 对sata的支持与否是哪里影响了？不是内核部分？

我再用你打包的img做为主体，一个一个尝试，再看看是什么文件控制

**Comment by gzxief** [comment]
> 支持 对sata的支持与否是哪里影响了？不是内核部分？

我下载了你编译的文件（所有版本），烧录到TF启动，获取的IP是192.168.3.4（所有你编译的包），然后我在ubuntu下，编辑你的包，替换了寒晨提供的boot里所有文件，能启动，不识别sata，和你编译的IMG文件一样无法使用sata，我把寒晨给我的包，烧录到TF启动，获取的IP是192.168.3.8，在ubuntu下，编辑寒晨的包，清空寒晨的包中所有文件包括boot和rootfs，再把你编译的包，用rsync同步boot和rootfs进去，修改boot文件夹中armbianEnv和/etc/fstab的ID，烧录到TF卡上，能启动，也能驱动sata，获取的IP是192.168.3.8，现在正常启动所用的所有文件都是你编译的，只是用了寒晨的包做为分区框架，我个人认为是img分区的问题，具体是什么，我也说不清楚，涉及到底层的知识，就不会了，只会简单的移植，所以麻烦大神们看看，谢谢

**Comment by ophub** [comment]
根据你的描述，是寒晨这个IMG文件的u-boot不同。在制作IMG镜像时，烧录进去一个主线u-boot。

**Comment by gzxief** [comment]
> 根据你的描述，是寒晨这个IMG文件的u-boot不同。在制作IMG镜像时，烧录进去一个u-boot。
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/6336bbb3cf89198696bd6da452ed37a1385c5b44/rebuild#L626-L645
> 
> u-boot在这：https://github.com/ophub/u-boot/tree/main/u-boot/rockchip/xiaobao 替换这个试试。

我昨晚用你主线本地化打包了，打包出来的img烧录到TF卡，能启动，但一样没有sata，所以想着移植一个包测试

**Comment by ophub** [comment]
你看看他使用的u-boot，替换这个试试，这个u-boot有几种组合，有1个文件的，2个文件的和3个文件的，不同文件数组合的看model表里现在的例子，根据他的数量修改model表制作试试。

**Comment by gzxief** [comment]
本人纯小白，经寒晨指点，我用armbian主线编译出RK3399的img包（6.1内核和6.2内核两个包），用ophub本地化打包，6.1内核打包后，和ophub所打包的一样，都无法识别sata，用6.2内核打包后，可以正常使用sata

**Comment by Mango1151** [comment]
> 感谢寒晨（CJ1324）,感谢ophub，花了2小时移植打包，移植出来Armbian_23.11.0_rockchip_xiaobao_bullseye_6.1.61,烧录到TF卡上，能启动，也能驱动sata，有个小瑕疵，第一次启动时，提示waiting for system to booting，等待2-3分钟后，就可以运行，之后启动都正常，也可以armbian-update最新内核，下载地址如下：请大神再修改或提取 https://www.123pan.com/s/doe8Vv-izIw3.html

风扇能PVM调速吗？这些固件都不支持风扇PVM调速

**Comment by cj1324** [comment]
下载 Release 中的镜像，刷入后，确实无法启动PCI ，
根据日志提示，搜索一轮下来，似乎遇到一个比较常见的超时问题。

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/7e0187bf-2267-4dea-9de0-18f0e45baf22)

类似讨论
https://forum.armbian.com/topic/18440-invalid-partially-fixed-pcie-training-problem/

这两个内核版本也不同~
失败： Linux armbian 6.1.52-ophub  （Release 中的镜像）
成功： Linux firefly-rk3399 6.1.53-ophub  
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/489649/08280b50-b11e-48a5-b23e-3654fd215d80)

差异：看 patch 修改了 相关网卡驱动，需要进一步论证~

**Comment by ophub** [comment]
sata的问题，试试更新最新版的内核，添加了sata选项

**Comment by phcl1998** [comment]
> sata的问题，试试更新最新版的内核，添加了sata选项
Welcome to Armbian 23.11.0-trunk Bullseye with Linux 6.1.62-ophub
用了6.1.62还是无法识别硬盘

**Comment by phcl1998** [comment]
> > sata的问题，试试更新最新版的内核，添加了sata选项
> > Welcome to Armbian 23.11.0-trunk Bullseye with Linux 6.1.62-ophub
> > 用了6.1.62还是无法识别硬盘

root@armbian:~# dmesg | grep PCIe
[    1.494614] rockchip-pcie f8000000.pcie: PCIe link training gen1 timeout!
root@armbian:~#

**Comment by HaleyLou** [comment]
使用了最新的6.1.63内核，依然无法识别sata，lspci指令无任何答复

**Comment by HaleyLou** [comment]
> sata的问题，试试更新最新版的内核，添加了sata选项

使用了最新的6.1.63内核，依然无法识别sata，lspci指令无任何答复

**Comment by HaleyLou** [comment]
补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/108428253/97f87c1a-ac8a-466c-8128-a9514cc83c22)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/108428253/92836964-2153-40a4-92e2-5aa9d71d73cd)

> sata的问题，试试更新最新版的内核，添加了sata选项

**Comment by 13584452567** [comment]
> 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/108428253/97f87c1a-ac8a-466c-8128-a9514cc83c22)
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/108428253/92836964-2153-40a4-92e2-5aa9d71d73cd)
> 
> > sata的问题，试试更新最新版的内核，添加了sata选项
> 
> 

这样看的话，是上游源码有问题。

暂时先用5.10内核吧，我去发个邮件问一下这件事。

**Comment by gzxief** [comment]
> > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > sata的问题，试试更新最新版的内核，添加了sata选项
> 
> 这样看的话，是上游源码有问题。
> 
> 暂时先用5.10内核吧，我去发个邮件问一下这件事。

但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html

**Comment by HaleyLou** [comment]
> > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > 
> > 这样看的话，是上游源码有问题。
> > 
> > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> 
> 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html

你用的firefly的包刷小宝nas？

**Comment by 13584452567** [comment]
> > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > 
> > 这样看的话，是上游源码有问题。
> > 
> > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> 
> 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html

前后两次打包命令一致吗？
体积差距不应该如此明显的

**Comment by gzxief** [comment]
> > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > 
> > > 
> > > 这样看的话，是上游源码有问题。
> > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > 
> > 
> > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> 
> 你用的firefly的包刷小宝nas？

本地化打包要提供img文件，我没用ophub的img，我用firefly的edge6.2内核的文件打包后，6.1.61时可以，到了6.1.62时再打包就不行了

**Comment by gzxief** [comment]
> > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > 
> > > 
> > > 这样看的话，是上游源码有问题。
> > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > 
> > 
> > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> 
> 前后两次打包命令一致吗？ 体积差距不应该如此明显的

都是一个命令./rebuild -b xiaobao

**Comment by 13584452567** [comment]
> > > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > > 
> > > > 
> > > > 这样看的话，是上游源码有问题。
> > > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > > 
> > > 
> > > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> > 
> > 你用的firefly的包刷小宝nas？
> 
> 本地化打包要提供img文件，我没用ophub的img，我用firefly的edge6.2内核的文件打包后，6.1.61时可以，到了6.1.62时再打包就不行了

kernel在6.1.61到6.1.62之间几乎没有对于pci功能上的修改，原因恐怕要去其他地方找。

**Comment by 13584452567** [comment]
> > > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > > 
> > > > 
> > > > 这样看的话，是上游源码有问题。
> > > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > > 
> > > 
> > > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> > 
> > 你用的firefly的包刷小宝nas？
> 
> 本地化打包要提供img文件，我没用ophub的img，我用firefly的edge6.2内核的文件打包后，6.1.61时可以，到了6.1.62时再打包就不行了

如果可以的话，可否在pcie不可用的系统下运行
modprobe pcie_rockchip_host 
随后运行dmesg | grep pcie，然后截取后一条命令的输出并把它发到这里？

**Comment by 13584452567** [comment]
> > > > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > > > 
> > > > > 
> > > > > 这样看的话，是上游源码有问题。
> > > > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > > > 
> > > > 
> > > > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> > > 
> > > 你用的firefly的包刷小宝nas？
> > 
> > 本地化打包要提供img文件，我没用ophub的img，我用firefly的edge6.2内核的文件打包后，6.1.61时可以，到了6.1.62时再打包就不行了
> 
> 如果可以的话，可否在pcie不可用的系统下运行
> modprobe pcie_rockchip_host 
> 随后运行dmesg | grep pcie，然后截取后一条命令的输出并把它发到这里？

从github上的讨论来看，这个问题恐怕不是一个部分造成的。
向上游推送了几个修补，不清楚效果如何

**Comment by phcl1998** [comment]
> > > > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > > > 
> > > > > 
> > > > > 这样看的话，是上游源码有问题。
> > > > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > > > 
> > > > 
> > > > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> > > 
> > > 
> > > 你用的firefly的包刷小宝nas？
> > 
> > 
> > 本地化打包要提供img文件，我没用ophub的img，我用firefly的edge6.2内核的文件打包后，6.1.61时可以，到了6.1.62时再打包就不行了
> 
> 如果可以的话，可否在pcie不可用的系统下运行 modprobe pcie_rockchip_host 随后运行dmesg | grep pcie，然后截取后一条命令的输出并把它发到这里？
![3YF%@MT}T NHY_0SS%D(E8B](https://github.com/ophub/amlogic-s9xxx-armbian/assets/125857645/c066ff35-2b40-41f5-9958-17633c0ddb97)

**Comment by HaleyLou** [comment]
> > > > > > 补充说明，使用5.10的内核是sata可以正常识别，5.15和6.1内核均不可以
> > > > > > ![image](https://user-images.githubusercontent.com/108428253/284695780-97f87c1a-ac8a-466c-8128-a9514cc83c22.png)
> > > > > > ![image](https://user-images.githubusercontent.com/108428253/284695852-92836964-2153-40a4-92e2-5aa9d71d73cd.png)
> > > > > > > sata的问题，试试更新最新版的内核，添加了sata选项
> > > > > 
> > > > > 
> > > > > 这样看的话，是上游源码有问题。
> > > > > 暂时先用5.10内核吧，我去发个邮件问一下这件事。
> > > > 
> > > > 
> > > > 但是，11月6日用本地打包，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这一个星期用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html
> > > 
> > > 
> > > 你用的firefly的包刷小宝nas？
> > 
> > 
> > 本地化打包要提供img文件，我没用ophub的img，我用firefly的edge6.2内核的文件打包后，6.1.61时可以，到了6.1.62时再打包就不行了
> 
> 如果可以的话，可否在pcie不可用的系统下运行 modprobe pcie_rockchip_host 随后运行dmesg | grep pcie，然后截取后一条命令的输出并把它发到这里？

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/108428253/a08cded6-fc67-4296-b663-900d4ed60376)

**Comment by 13584452567** [comment]
向上游推送可能修复该问题的patch，等待合并。

**Comment by 13584452567** [comment]
补丁已合并，等待下次内核编译就能看到效果了。

**Comment by HaleyLou** [comment]
> 补丁已合并，等待下次内核编译就能看到效果了。
> 
> 6.1.y分支

经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏

**Comment by 13584452567** [comment]
> > 补丁已合并，等待下次内核编译就能看到效果了。
> > 6.1.y分支
> 
> 经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏

[patch](https://github.com/unifreq/linux-6.1.y/commit/1af06450985bc4674dc0cde2b3042a0b60f71475)

只修改了pcie-host部分，不应该会出现无法启动或者黑屏的状况啊。

另一个patch改的是eaidk的设备树，和小宝毫无关联。

**Comment by HaleyLou** [comment]
> > > 补丁已合并，等待下次内核编译就能看到效果了。
> > > 6.1.y分支
> > 
> > 
> > 经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏
> 
> [patch](https://github.com/unifreq/linux-6.1.y/commit/1af06450985bc4674dc0cde2b3042a0b60f71475)
> 
> 只修改了pcie-host部分，不应该会出现无法启动或者黑屏的状况啊。
> 
> 另一个patch改的是eaidk的设备树，和小宝毫无关联。

无论是重新编译新内核的固件，还是旧版固件升级内核，启动后，屏幕无显示，路由器未发现设备，期待其他网友的测试结果

**Comment by 13584452567** [comment]
> > > > 补丁已合并，等待下次内核编译就能看到效果了。
> > > > 6.1.y分支
> > > 
> > > 
> > > 经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏
> > 
> > 
> > [patch](https://github.com/unifreq/linux-6.1.y/commit/1af06450985bc4674dc0cde2b3042a0b60f71475)
> > 只修改了pcie-host部分，不应该会出现无法启动或者黑屏的状况啊。
> > 另一个patch改的是eaidk的设备树，和小宝毫无关联。
> 
> 无论是重新编译新内核的固件，还是旧版固件升级内核，启动后，屏幕无显示，路由器未发现设备，期待其他网友的测试结果

能够获取到ttl日志吗

**Comment by HaleyLou** [comment]
> > > > > 补丁已合并，等待下次内核编译就能看到效果了。
> > > > > 6.1.y分支
> > > > 
> > > > 
> > > > 经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏
> > > 
> > > 
> > > [patch](https://github.com/unifreq/linux-6.1.y/commit/1af06450985bc4674dc0cde2b3042a0b60f71475)
> > > 只修改了pcie-host部分，不应该会出现无法启动或者黑屏的状况啊。
> > > 另一个patch改的是eaidk的设备树，和小宝毫无关联。
> > 
> > 
> > 无论是重新编译新内核的固件，还是旧版固件升级内核，启动后，屏幕无显示，路由器未发现设备，期待其他网友的测试结果
> 
> 能够获取到ttl日志吗

这方面不是很会，希望别的玩家测试下

**Comment by Mango1151** [comment]
6.1.63版本烧录进tf卡启动不了，无任何显示，连硬盘灯都不亮。

**Comment by cj1324** [comment]
> > > > > 补丁已合并，等待下次内核编译就能看到效果了。
> > > > > 6.1.y分支
> > > > 
> > > > 
> > > > 经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏
> > > 
> > > 
> > > [patch](https://github.com/unifreq/linux-6.1.y/commit/1af06450985bc4674dc0cde2b3042a0b60f71475)
> > > 只修改了pcie-host部分，不应该会出现无法启动或者黑屏的状况啊。
> > > 另一个patch改的是eaidk的设备树，和小宝毫无关联。
> > 
> > 
> > 无论是重新编译新内核的固件，还是旧版固件升级内核，启动后，屏幕无显示，路由器未发现设备，期待其他网友的测试结果
> 
> 能够获取到ttl日志吗
确实无法启动，看起来是 uboot 脚本问题。

日志如下：
```
Found U-Boot script /boot.scr
3252 bytes read in 5 ms (634.8 KiB/s)
## Executing script at 00500000
Boot script loaded from mmc 1
268 bytes read in 3 ms (86.9 KiB/s)
16864098 bytes read in 719 ms (22.4 MiB/s)
33858048 bytes read in 1437 ms (22.5 MiB/s)
77675 bytes read in 9 ms (8.2 MiB/s)
Failed to load '/dtb/rockchip/overlay/rk3399-fixup.scr'
Unknown command 'kaslrseed' - try 'help'
Moving Image from 0x2080000 to 0x2200000, end=4330000
## Loading init Ramdisk from Legacy Image at 06000000 ...
   Image Name:   uInitrd
   Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
   Data Size:    16864034 Bytes = 16.1 MiB
   Load Address: 00000000
   Entry Point:  00000000
   Verifying Checksum ... OK
## Flattened Device Tree blob at 01f00000
   Booting using the fdt blob at 0x1f00000
   Loading Ramdisk to f0ef7000, end f1f0c322 ... OK
   Loading Device Tree to 00000000f0e7b000, end 00000000f0ef6fff ... OK

Starting kernel ...
```

**Comment by 13584452567** [comment]
> > > > > > 补丁已合并，等待下次内核编译就能看到效果了。
> 
> > > > > > 6.1.y分支
> 
> > > > > 
> 
> > > > > 
> 
> > > > > 经测试，新版本的6.1.63内核，导致系统直接无法启动，显示黑屏
> 
> > > > 
> 
> > > > 
> 
> > > > [patch](https://github.com/unifreq/linux-6.1.y/commit/1af06450985bc4674dc0cde2b3042a0b60f71475)
> 
> > > > 只修改了pcie-host部分，不应该会出现无法启动或者黑屏的状况啊。
> 
> > > > 另一个patch改的是eaidk的设备树，和小宝毫无关联。
> 
> > > 
> 
> > > 
> 
> > > 无论是重新编译新内核的固件，还是旧版固件升级内核，启动后，屏幕无显示，路由器未发现设备，期待其他网友的测试结果
> 
> > 
> 
> > 能够获取到ttl日志吗
> 
> 
> 
> ### 
> 
> 
> 
> 确实无法启动，看起来是 uboot 脚本问题。
> 
> 
> 
> 日志如下：
> 
> ```
> 
> Found U-Boot script /boot.scr
> 
> 3252 bytes read in 5 ms (634.8 KiB/s)
> 
> ## Executing script at 00500000
> 
> Boot script loaded from mmc 1
> 
> 268 bytes read in 3 ms (86.9 KiB/s)
> 
> 16864098 bytes read in 719 ms (22.4 MiB/s)
> 
> 33858048 bytes read in 1437 ms (22.5 MiB/s)
> 
> 77675 bytes read in 9 ms (8.2 MiB/s)
> 
> Failed to load '/dtb/rockchip/overlay/rk3399-fixup.scr'
> 
> Unknown command 'kaslrseed' - try 'help'
> 
> Moving Image from 0x2080000 to 0x2200000, end=4330000
> 
> ## Loading init Ramdisk from Legacy Image at 06000000 ...
> 
>    Image Name:   uInitrd
> 
>    Image Type:   AArch64 Linux RAMDisk Image (gzip compressed)
> 
>    Data Size:    16864034 Bytes = 16.1 MiB
> 
>    Load Address: 00000000
> 
>    Entry Point:  00000000
> 
>    Verifying Checksum ... OK
> 
> ## Flattened Device Tree blob at 01f00000
> 
>    Booting using the fdt blob at 0x1f00000
> 
>    Loading Ramdisk to f0ef7000, end f1f0c322 ... OK
> 
>    Loading Device Tree to 00000000f0e7b000, end 00000000f0ef6fff ... OK
> 
> 
> 
> Starting kernel ...
> 
> ```
> 
> 
> 
> 
> 
> 

替换之前的内核试一下？

**Comment by cj1324** [comment]
测试 6.1.62 正常启动 （6.1.63 / 6.1.64 均启动失败） @113584452567

日志如下：

```
armbian login: root (automatic login)

      _             _
__  _(_) __ _  ___ | |__   __ _  ___
\ \/ / |/ _` |/ _ \| '_ \ / _` |/ _ \
 >  <| | (_| | (_) | |_) | (_| | (_) |
/_/\_\_|\__,_|\___/|_.__/ \__,_|\___/

Welcome to Armbian-unofficial 23.11.0-trunk Trixie with Linux 6.1.62-ophub

No end-user support: unsupported (trixie) userspace!

System load:   36%              Up time:       0 min
Memory usage:  4% of 3.78G      IP:
CPU temp:      31°C             Usage of /:    64% of 2.4G


Waiting for system to finish booting ...






[   44.658270] EXT4-fs (mmcblk1p2): resizing filesystem from 655104 to 7564027 blocks
[   45.621081] EXT4-fs (mmcblk1p2): resized filesystem to 7564027

```
