### ISSUE TITLE
Armbian-install command takes much time to copy data (x96 max+, kernel 5.15.x)

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#183]
My box: X96 max + (4+32G, kernet 5.15.29)

After install some applications such as Docker, Hassio..etc to TF card (32GB sandisk A1, good speed), I run the command armbian-install and select 501 to copy all the data to eMMC.

The total data size is only about 3.7GB but it takes very long (more than 1 hour) to finish armbian-install command.
As I check, the most waiting time and resource is for "tar -xf -" and "tar -cf - var" command.
<img width="746" alt="Screen Shot 2022-03-20 at 10 33 28" src="https://user-images.githubusercontent.com/22479095/159147520-75d252fc-8282-4a00-bf26-0ef42edd0b2a.png">

It's also quite strange that during running armbian-install, the temporary folder's size for /ddbr/install is increased so much (more than 11GB).

<img width="429" alt="Screen Shot 2022-03-20 at 10 40 58" src="https://user-images.githubusercontent.com/22479095/159147434-6c5c2d8e-8cf4-49cd-b19e-b5e998685bae.png">

Normally, if using TF card 16G and kernel 5.4, it takes only around 15-20 minuts to finish copy the same amount of data using armbian-install to eMMC.

Please give me any suggestion to improve the speed of copy data if any.

Thank you.

**Comment by ophub** [comment]
The original system copy should be completed in about three minutes. If you install other software in the usb and then install it, it will vary from person to person. It is recommended that you write emmc before installing the package.

**Comment by dinhchinh82** [comment]
> The original system copy should be completed in about three minutes. If you install other software in the usb and then install it, it will vary from person to person. It is recommended that you write emmc before installing the package.

@ophub I understand that if installed some other apps and libs, it will take more time. By the way, I found the strange point that if I installed same other apps on Armbianl kernel 5.4, Armbian 5.15 still takes much longer time than 5.4.

So is there any difference ponint of the armbian-install script betwee kernel 5.4 and 5.15?

Thank you.

**Comment by ophub** [comment]
the same file

**Comment by dinhchinh82** [comment]
@ophub there is very strange point that total data is only 3.4GB (on TF flash) but when running the armbian-install, the allocated temporary data is more than 9GB as photo below:
<img width="397" alt="Screen Shot 2022-03-24 at 16 26 06" src="https://user-images.githubusercontent.com/22479095/159885726-cdf779a5-afca-4f6a-81c7-788c5f5a046b.png">

**Comment by dinhchinh82** [comment]
<img width="377" alt="Screen Shot 2022-03-24 at 16 55 43" src="https://user-images.githubusercontent.com/22479095/159890679-ba273f8a-5999-4a08-8a65-5768ef6abf9e.png">
After installing to eMMC, the used data is 15 GB while it only allocated 3.1GB on TF card.
I guess there is something strange in the armbian-script.

**Comment by ophub** [comment]
After you install a large number of programs in the docker of the tf card, can you use it normally after writing emmc?
It is rare to write emmc later like you, you can use your data to study it: `Feasibility Analysis Report on Later Migration of Big Data`

**Comment by dinhchinh82** [comment]
> After you install a large number of programs in the docker of the tf card, can you use it normally after writing emmc? It is rare to write emmc later like you, you can use your data to study it:
> 
> * `Feasibility Analysis Report on Later Migration of Big Data`
> * `Migration solutions for data in docker`

I install docker and some open source applications. Total all data size is about 3GB. 

My objective is installling all needed app to the TF then clone it to some similar boxes to save the time.

After installing to eMMC, for kernel 5.4 everything works well but for kernel 5.15, the docker services takes much resource and some containers unable to start correctly, only dead state or "remove in progress" state for a long time.
It seems there are some conflict points related to docker but if running 5.15 on TF, everything still well.

That's an other strange point.

**Comment by ophub** [comment]
Install emmc on one device, and then use `armbisn-ddbr` to backup/restore to other devices of the same brand.

**Comment by dinhchinh82** [comment]
> Install emmc on one device, and then use `armbisn-ddbr` to backup/restore to other devices of the same brand.

I will try this solution. Thank you.

**Comment by ophub** [comment]
In order to take care of friends in ext4 plots, you can now customize the partition format when installing to EMMC
