### ISSUE TITLE
panther-x2 没有 armbian-software命令

### ISSUE THREAD

**Issue by daemonsgiants** [ophub/amlogic-s9xxx-armbian#1834]
**Device Information | 设备信息**
 - SOC: RK3566
 - Model：panther-x2

**Armbian Version | 系统版本**
 - Kernel Version:  Linux panther-x2 6.1.50-current-rockchip64 
 - Release: Armbian 23.8.3 jammy 

**Describe the bug | 问题描述**
panther-x2 没有 armbian-software命令
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/150017102/5d3702d5-22b2-4ffc-8ece-c0d964df0978)

**Comment by ophub** [comment]
Only those downloaded here have it. You must be using firmware downloaded from elsewhere.

https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by daemonsgiants** [comment]
是需要重新刷固件吗

**Comment by ophub** [comment]
可以把/usr/sbin/armbian-sync和/etc/ophub-release文件上传，并且给armbian-sync文件执行权限，然后运行拉取其他的脚本，即可使用，不用重刷。

**Comment by daemonsgiants** [comment]
/usr/sbin/armbian-sync和/etc/ophub-release可以从哪里获取

**Comment by wnpllrzodiac** [comment]
> /usr/sbin/armbian-sync和/etc/ophub-release可以从哪里获取

git repo

**Comment by longtianhgg** [comment]
> ophub-release

没有找到啊
