### ISSUE TITLE
请求适配友善的NanoPC-T4  rk3399

### ISSUE THREAD

**Issue by sehczaa** [ophub/amlogic-s9xxx-armbian#1835]
官方给的armbian有点老了
希望大佬可以适配下新的armbian
官方给的资料网盘里有老版本的armbian
文档地址：
https://wiki.friendlyelec.com/wiki/index.php/NanoPC-T4/zh#.E5.9C.A8Debian.E7.B3.BB.E7.BB.9F.E4.B8.8A.E5.AE.89.E8.A3.85Docker

**Comment by Mango1151** [comment]
Armbian官网不是有23.8版本吗？

**Comment by Mango1151** [comment]
> 官方给的armbian有点老了 希望大佬可以适配下新的armbian 官方给的资料网盘里有老版本的armbian 文档地址： https://wiki.friendlyelec.com/wiki/index.php/NanoPC-T4/zh#.E5.9C.A8Debian.E7.B3.BB.E7.BB.9F.E4.B8.8A.E5.AE.89.E8.A3.85Docker

Armbian官网不是有23.8版本吗？

**Comment by sehczaa** [comment]
> Armbian官网不是有23.8版本吗？

找到了，感谢告知
