### ISSUE TITLE
S9503L3a最新版本更换网络环境后无法自动获取到IP

### ISSUE THREAD

**Issue by diyjack0326** [ophub/amlogic-s9xxx-armbian#1836]
S9503L3a最新版本更换网络环境后无法自动获取到IP，在原网络环境中没问题，换了网络环境后eth0网口都无法识别到，进行清除后会显示lo网口，设置了固定ip也识别不到，这是我操作问题还是有bug？

**Comment by ophub** [comment]
如果设备设置的是自动获得IP，就应该直接可以在新的网络里使用。
如果设备设置的是手动指定的IP，就修改自己的网络配置文件，把dhcp和dns，ip等根据新网络填写。
如果设备没问题，就检查网线等新网络环境里的网络设备
