### ISSUE TITLE
MGV2000-K 康佳代工 S905L2 1+8G MT7668 安装记录

### ISSUE THREAD

**Issue by sleepwalkera** [ophub/amlogic-s9xxx-armbian#1839]
结论：
`Armbian_23.11.0_amlogic_s905l2_lunar_5.15.136_server_2023.10.20.img`，写入mmc正常，hdmi输出正常，板载有线网卡正常，wifi芯片为MT7668RSN，无驱动，但蓝牙可识别，内存803M，存储6.8G

要点：
1、刷[安卓固件](https://pan.baidu.com/s/1yF-ONWxePnt62yUFw_wYBQ?pwd=lp4k)
2、dtb使用`meson-gxl-s905l2-x7-5g.dtb`，mmc的`max-frequency`使用`0x2faf080`，否则不识别

以上供参考
另外想问下大佬，这款wifi有希望驱动吗？

**Comment by ophub** [comment]
谢谢分享，我把这个设备添加到列表里，你分享的安卓我转存到：https://github.com/ophub/kernel/releases/tag/tools

https://github.com/search?q=repo%3Aunifreq%2Flinux-6.1.y%20MT7668&type=code

我在内核仓库里搜了下，有蓝牙驱动，但是没有wifi驱动。

**Comment by sleepwalkera** [comment]
> 你分享的安卓固件下载里，解压缩后没有安卓系统
> 
> 我在内核仓库里搜了下，有蓝牙驱动，但是没有wifi驱动。 https://github.com/search?q=repo%3Aunifreq%2Flinux-6.1.y%20MT7668&type=code

解压缩后，`db-咪咕mgv2000-android4.42-qlzy-201812.img`这个文件就是安卓系统线刷固件，用usb burning tool刷入，短接下图黑色电阻
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1573639/8fdf6633-e2bb-4598-9b04-e78a8b4a4bcb)

**Comment by ophub** [comment]
我解压了没有这个文件。你重新压一个img分享一下

**Comment by sleepwalkera** [comment]
> 我解压了没有这个文件。你重新压一个img分享一下

重新压缩了一下[这里](https://pan.baidu.com/s/1mx1lb83ge88E4uKvEiqHIA?pwd=e3dm)

**Comment by sleepwalkera** [comment]
[这个驱动](https://github.com/noob404yt/mt7668-wifi-bt)可以用吗

**Comment by ophub** [comment]
你按照他的步骤试试

**Comment by ZASGithub** [comment]
安卓固件方便再分享一下吗
