### ISSUE TITLE
如何不拔U盘方式启动EMMC里面的系统？

### ISSUE THREAD

**Issue by twfjcn** [ophub/amlogic-s9xxx-armbian#1840]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
如何不拔U盘方式启动EMMC里面的系统？

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
O大，在coreelec里面有个功能就是Reboot from EMMC，在不拨U盘情况就可以从EMMC启动？我觉得这样很方便，比如EMMC里面有安卓或者获取另一个Linux，通过一行命令就可以从EMMC启动，不用频繁拨插U盘。

**Comment by seamt** [comment]
如果你最终找不到软件的解决办法，可以试试我的办法。
买一只带开关的USB hub。U盘系统关机后，关闭hub上面U口的开关，然后盒子开机就会进入EMMC系统。

引申一个问题：
有的盒子，比如我这CM311-1a-YS，原厂Android系统有严重bug，会自动且强制的改写U盘上EXT4分区内全部目录和文件的权限。导致U盘失去系统盘功能。

**Comment by Just2co** [comment]
你这跟我的需求完全相反了，我是想要拔掉U盘能启动就行，你是要插着才能启动才满意
