### ISSUE TITLE
黑豹X2 ssh链接是否默认允许root用户登陆

### ISSUE THREAD

**Issue by hobbyzhu** [ophub/amlogic-s9xxx-armbian#1841]
**Device Information | 设备信息**
 - SOC: [e.g. RK3566]
 - Model [e.g. 黑豹X2]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g.6.1.10]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截
黑豹X2没有显示接口，使用ssh连接，使用root，密码1234无法登陆，返回错误Permission denied, please try again.，因为没有HDMI接口，无法使用终端，请问ssh是否默认允许root登陆

**Comment by Doboo** [comment]
没问题啊  一直用root  1234登录的。不知你刷的armbian是什么版本？

**Comment by hobbyzhu** [comment]
问题已经解决，谢谢，是我的问题，全新的刷机其实并没有boot，参考了https://blog.csdn.net/qq_45279139/article/details/132831894
