### ISSUE TITLE
M302A YS (S905L3) 缺少 u-boot 无法从 emmc 启动 6.1 内核

### ISSUE THREAD

**Issue by lvqier** [ophub/amlogic-s9xxx-armbian#1843]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model: M302A YS
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4608517/b6762d3c-4aad-4d8d-a4ed-07e82ec516c2)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4608517/145634ce-3e4e-4aa2-aeb1-7146dd8c1b22)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4608517/b85becc6-1216-4993-9991-5133f55d7953)
<img width="1437" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/4608517/74e84624-c48e-4507-bdf7-2331f99dc741">
<img width="512" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/4608517/8fd8308a-5c0e-4d47-8223-ebe86deee9af">

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.60
 - Release: bookworm

**Describe the bug | 问题描述**
折腾步骤如下：

下载  Armbian_23.11.0_amlogic_s905l3a_bookworm_6.1.60_server_2023.11.01.img.gz 写入 U 盘可以正常启动，但是不认 emmc。

修改 meson-gxl-s905l3b-m302a.dtb 中的 mmc@74000 的 max-frequence，降到 0x17d7840 之后可以认 emmc，并且可以成功写入。

写入之后发现启动 logo 不正常，恢复 Android 系统，然后修改分区：BLANK1=108, BOOT=1120, BLANK2=40 再写入，logo 正常。

但是无法从 emmc 正常启动，使用 u-boot-s905x-s912.bin 极小概率可以从 emmc 启动，但是大多数时候都不行，无法启动时卡 BL31，如下：
<img width="623" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/4608517/b758c576-afe8-42e5-a351-51dc25314a31">

尝试更换其它 u-boot ，比如 u-boot-p212.bin 均无法正常启动，看起来是不认 emmc：p212 uboot 下 mmc dev 2 会提示异常。

然后根据文档尝试自制 u-boot，提到 acs.bin 时发现属于 “如果是锁了 bootloader 的话这个区域的代码是是乱码就没用了。” 这种情况。

至此卡住了。

想请教社区大佬，有没有可能解锁 bootloader 得到正确的 acs.bin 呢？求指引

**Comment by lvqier** [comment]
Update: 5.15 的 kernel 可以正常从 emmc 启动（跳过了 chainload u-boot 直接由 android u-boot 加载内核启动了）

所以问题还是在于要启动 6.1 的 kernel 需要正确的 chainload u-boot。

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/kernel_dev

使用dev系列内核，不用u-boot

**Comment by lvqier** [comment]
> https://github.com/ophub/kernel/releases/tag/kernel_dev
> 
> 使用dev系列内核，不用u-boot

感谢 O 大，切成 dev 6.1.62 之后顺利启动。

**Comment by lizeyou0203** [comment]
> > https://github.com/ophub/kernel/releases/tag/kernel_dev
> > 使用dev系列内核，不用u-boot
> 
> 感谢O大，紧张的dev 6.1.62之后顺利启动。

我是直接下载img镜像包的,内核6.0可以u盘运行,但是写入到emmc后,开机就直接黑屏,无法启动系统.使用内核5.0写入emmc后,系统启动正常.
请问你是如何操作的,内核和u-boot不熟,你们说的也是看不明白,麻烦告知一下操作方法.
多谢!

**Comment by lvqier** [comment]
> > > https://github.com/ophub/kernel/releases/tag/kernel_dev
> > > 使用dev系列内核，不用u-boot
> > 
> > 
> > 感谢O大，紧张的dev 6.1.62之后顺利启动。
> 
> 我是直接下载img镜像包的,内核6.0可以u盘运行,但是写入到emmc后,开机就直接黑屏,无法启动系统.使用内核5.0写入emmc后,系统启动正常. 请问你是如何操作的,内核和u-boot不熟,你们说的也是看不明白,麻烦告知一下操作方法. 多谢!

提供的信息太少了，建议先搞定 uart，对着启动日志来分析问题。
同时这篇文章讲得非常全面了，基本把我踩到的问题都讲到了，可以参考下：https://bbs.hassbian.com/thread-17485-1-1.html

**Comment by lizeyou0203** [comment]
> > > > https://github.com/ophub/kernel/releases/tag/kernel_dev
> > > > 使用dev系列内核，不用u-boot
> > > 
> > > 
> > > 感谢O大，紧张的dev 6.1.62之后顺利启动。
> > 
> > 
> > 我是直接下载img镜像包的,内核6.0可以u盘运行,但是写入到emmc后,开机就直接黑屏,无法启动系统.使用内核5.0写入emmc后,系统启动正常. 请问你是如何操作的,内核和u-boot不熟,你们说的也是看不明白,麻烦告知一下操作方法. 多谢!
> 
> 提供的信息太少了，建议先搞定 uart，对着启动日志来分析问题。 同时这篇文章讲得非常全面了，基本把我踩到的问题都讲到了，可以参考下：https://bbs.hassbian.com/thread-17485-1-1.html

我是从U盘写入到emmc后,开机直接黑屏,不打印任何信息......

**Comment by lizeyou0203** [comment]
> > > > https://github.com/ophub/kernel/releases/tag/kernel_dev
> > > > 使用dev系列内核，不用u-boot
> > > 
> > > 
> > > 感谢O大，紧张的dev 6.1.62之后顺利启动。
> > 
> > 
> > 我是直接下载img镜像包的,内核6.0可以u盘运行,但是写入到emmc后,开机就直接黑屏,无法启动系统.使用内核5.0写入emmc后,系统启动正常. 请问你是如何操作的,内核和u-boot不熟,你们说的也是看不明白,麻烦告知一下操作方法. 多谢!
> 
> 提供的信息太少了，建议先搞定 uart，对着启动日志来分析问题。 同时这篇文章讲得非常全面了，基本把我踩到的问题都讲到了，可以参考下：https://bbs.hassbian.com/thread-17485-1-1.html

已解决,多谢!
