### ISSUE TITLE
Workaround for 48 times repeated error prompt "no backend DAIs"

### ISSUE THREAD

**Issue by seamt** [ophub/amlogic-s9xxx-armbian#1844]
**Device Information | 设备信息**
 - SOC: Amlogic S905L3A
 - Model: CM311-1a-YST

**Armbian Version | 系统版本**
 - Kernel Version: 6.1
 - Release: Debian 12/Gnome/Wayland

**Describe the bug | 问题描述**
Error prompt repeated 48 times on bootup if Gnome desktop installed.
...
fe.dai-link-2: ASoC: no backend DAIs enabled for fe.dai-link-2
fe.dai-link-2: ASoC: error at dpcm_fe_dai_prepare on fe.dai-link-2: -22
...
This error donnot actually do any harm to system, but looks quite astonishing and insulting.

Reason: pkg and service "wireplumber" invoke ioctl/kernel

workaround:
After logging into Gnome desktop (soundcard activated hence), replace wireplumber with pulseaudio.

```
# apt install pulseaudio
# apt autoremove --purge pipewire-pulse wireplumber
```

**Comment by ophub** [comment]
多谢分享解决方案
