### ISSUE TITLE
Is s905x4 supported?

### ISSUE THREAD

**Issue by JavierCervilla** [ophub/amlogic-s9xxx-armbian#1845]
Hello all and first of all thank you. Im looking for information on how to install armbian in my hk1 rbox x4 with s905x4 soc, in the list i dont see support for this but idk if is bc it is not supported or if is bc it is not tested. i have tried lot of imgs and dtb but dont achieve to make it work, any help is really apreciate it. Again thanks for your help

**Comment by JavierCervilla** [comment]
We found a DtB that is able to run with Emuelec but we are not able to load with it any armbian rom from the extlinux.cnf

**Comment by ophub** [comment]
The kernel does not support

**Comment by goldsoft8888** [comment]
https://github.com/armarchindo/ULO-Builder
https://github.com/sib0ndt/linux-6.6.6

**Comment by petesimon** [comment]
will the code at https://github.com/sib0ndt/linux-6.6.6 be merged with ophub-armbian sometime soon to support s905x4?

**Comment by bragasrc** [comment]
Anything new about the support for the S905X4 SOC?

**Comment by 6LWa6ZKx** [comment]
> 关于S905X4 SoC的支持方面有什么新进展吗？

似乎后续都不支持了，包括S905X5

**Comment by NNdroid** [comment]
Linux主线目前不支持这个soc
