### ISSUE TITLE
Docker openwrt 无法打开

### ISSUE THREAD

**Issue by zhuzf88** [ophub/amlogic-s9xxx-armbian#1846]
**Device Information | 设备信息**
 - SOC: S905d
 - Model N1

**Armbian Version | 系统版本**
 - Kernel Version: 6.1
 - Release: lunar

**Describe the bug | 问题描述**
安装docker openwrt无法打开luci界面配置

**Comment by ophub** [comment]
lede源有点问题，我切换成官方源，测试可以了。

![Snip20231201_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/232b947d-33a4-4860-8f2e-cc30a841db55)
![Snip20231201_2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/94347937-5bff-4dee-b669-f162b2ff42b6)
![Snip20231201_3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/76bb6a9c-c4ce-4386-9f15-135aa94515e8)

**Comment by sohow** [comment]
+1无法打开
