### ISSUE TITLE
E900V22D S905L3B 2+8G 安装记录

### ISSUE THREAD

**Issue by sleepwalkera** [ophub/amlogic-s9xxx-armbian#1849]
结论：
`Armbian_23.11.0_amlogic_s905l3b_lunar_5.15.135_server_2023.10.13.img`，写入mmc正常，hdmi无输出，板载有线网卡正常，内存1.77G，存储6.8G

要点：
1、刷[安卓固件](https://pan.baidu.com/s/1wksDAcicnNrPrcFq1lucPQ?pwd=7jir)，之前测试了`android_tv_e900v22e_e900v22d_s905l3b.tar.xz` `android_tv_e900v22e_cm211-1_201-1_s905l3b.tar.xz`等均无法成功启动板载有线网卡。
2、`meson-gxl-s905l3b-e900v22e.dtb`，mmc的`max-frequency`使用`0x5f5e100`，否则不识别

以上供参考

**Comment by ophub** [comment]
多谢分享测试结果。

**Comment by sdpyhzj** [comment]
[sleepwalkera](https://github.com/sleepwalkera)老大，网盘已过期能否再提供一下固件
