### ISSUE TITLE
how to disable verbosity of logs

### ISSUE THREAD

**Issue by ewwink** [ophub/amlogic-s9xxx-armbian#185]
how to disable the logs on screen after logged in?

**Comment by ophub** [comment]
I don't understand what you mean, screenshot description

**Comment by ewwink** [comment]
The logs continues to appear after logged in

![image](https://user-images.githubusercontent.com/760764/159163390-1ac3e45f-1acf-40b4-a9d7-8d943f4c895e.png)

**Comment by ophub** [comment]
![Snip20220320_1](https://user-images.githubusercontent.com/68696949/159163947-845ae236-13f7-4878-be33-e00ab2a91311.png)

Did you enter the login screen like this? What device are you on? Which firmware version did you download?

`cat /etc/ophub-release`

**Comment by ewwink** [comment]
I see that screen and successfully logged in but it continues appear

I use `Armbian_22.05.0_Aml_s905x_focal_5.15.30_2022.03.20.1653.img.gz`

```
root@armbian:# cat /etc/ophub-release
VERSION_CODEID='ubuntu'
VERSION_CODENAME='focal'
KERNEL_VERSION='5.15.29'
K510='1'
PACKAGED_DATE='2022-03-18'
FDTFILE='meson-gxl-s905x-p212.dtb'
UBOOT_OVERLOAD='u-boot-p212.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT=''
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905x'
```

**Comment by ewwink** [comment]
it happen only in physical machine, if use remote ssh client the logs is not appear

**Comment by ophub** [comment]
Seems to be a log not supported by the `wireless` driver? You can disable it in `armbian-config`.
You can try the firmware generated today if there is such a problem.

**Comment by ewwink** [comment]
here a full log http://ix.io/3SXM

I cannot disabling wireless using `ambian-config`, temporary I use `ifconfig wlan0 down` and it solve the problem, how to disable it permanently?

yes the logs appear only on device that connected to the monitor, if I connect using SSH there is no log.

**Comment by mazdel** [comment]
> edit: to disable wlan0 permanently edit `/etc/rc.local` and append
> 
> ```
> /bin/sleep 15 && rfkill block wifi
> 
> exit 0
> ```
> 
> here a full log http://ix.io/3SXM
> 
> I cannot disabling wireless using `ambian-config`, temporary I use `ifconfig wlan0 down` and it solve the problem, how to disable it permanently?
> 
> yes the logs appear only on device that connected to the monitor, if I connect using SSH there is no log.

thanks, this issue happens to me too
