### ISSUE TITLE
这个软件有没有利用上多核 的性能，还有显卡硬件加速性能？

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#1850]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
我在网上看到多核是这样的，
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11472472/34c668fc-0897-4024-bed4-0379fd49bc67)
我的是下面这样的
![0J5EFYACF22J{L{C4%X2QLB](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11472472/495c41cc-1934-462b-b024-592b54d2eead)

**Comment by githubfat** [comment]
同问
