### ISSUE TITLE
Tanix TX3 4/64 100Mb

### ISSUE THREAD

**Issue by eonegin83** [ophub/amlogic-s9xxx-armbian#1852]
Tanix TX3
 - SOC: S095x3]l
 - Model TX3

**Armbian Version | 2023.11
 - Kernel Version: 6.1.60
 - Release: bullseye

Установка з SD карти, armbian запускається armbian-install, пробував armbian-install -m yes, але з приставка не запускається з Emmc, чорний екран 

![Screenshot_20231111_052122_Mobile SSH](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85644681/98fc7da3-8f59-4f35-bf92-2d6a80784d41)

**Comment by eonegin83** [comment]
Id 520 and 521

**Comment by ophub** [comment]
try 5.15.y

**Comment by eonegin83** [comment]
5.15 завантажується, але не підключається до мережі

**Comment by eonegin83** [comment]
518 - ok
