### ISSUE TITLE
求助，本地打包指定内核的问题

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#1853]
求助，本地打包指定内核的问题，我想指定使用6.1.61，加-k了，总是是提示下载6.1.1

root@ubuntu:~/amlogic-s9xxx-armbian# ./rebuild -b xiaobao -a false -k 6.1.61
[ STEPS ] Welcome to Rebuild Armbian!
[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x86_64 ] 

[ STEPS ] Start Initializing Variables...
[ STEPS ] Start searching for Armbian file...
[ INFO ] Armbian rebuild file: [ Armbian_23.11.0-trunk_Helios64_bookworm_edge_6.6.0_minimal.img ], Version: [ 23.11.0 ]
[ STEPS ] Start downloading dependency files...
[ INFO ] u-boot download completed.
[ INFO ] firmware download completed.
[ STEPS ] Start downloading the kernel files...
[ INFO ] (1.1) [ specific - 6.1.1 ] Kernel download from [ https://github.com/ophub/kernel/releases/download/kernel_stable/6.1.1.tar.gz ]
 [💔] Failed to download the kernel files from the server.

**Comment by ophub** [comment]
拉取最新源码，修好了。

![Snip20231111_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/f46aa26b-9012-4a51-b149-e5382f5a5b17)

**Comment by gzxief** [comment]
> 拉取最新源码，修好了。
> 
> ![Snip20231111_1](https://user-images.githubusercontent.com/68696949/282240007-f46aa26b-9012-4a51-b149-e5382f5a5b17.png)

咨询一个问题，11月6日用本地打包，小宝nas，用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16（11月5日编译的）做为img，当时内核为6.1.61,打包后固件为643M左右，刷入小宝nas正常使用sata，这两天用新代码打包后（用Armbian_23.11.0-trunk_Firefly-rk3399_bookworm_edge_6.2.16，11月5日编译的做为img），固件只有450M左右，内核为6.1.62，但无法使用sata，指定6.1.61或6.1.52的内核也没办法使用sata，麻烦ophub大神看看，谢谢
       网盘是11月6日用本地化打包的，正常使用sata，可以用armbian-update升级到最新，https://www.123pan.com/s/doe8Vv-xyIw3.html

**Comment by t9097** [comment]
bookworm 6.1.61, 启动短时间后画面全黑没反应, 你的bullseye 6.1.61 算可用, 昨晚安裝了omv6 使用中
