### ISSUE TITLE
cm311-1sa CH 2＋8 刷入emmc后，再次U盘刷入不能启动

### ISSUE THREAD

**Issue by HeroPoter** [ophub/amlogic-s9xxx-armbian#1854]
**Device Information | 设备信息**
 - SOC: [e.g. S905l2a]
 - Model [e.g. cm311-1sa_CH_2＋8]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.60]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

cm311-1sa CH 2＋8 刷入emmc后，关机，拔下U盘能启动，过几天U盘又再一次刷写进emmc还原系统，但不能启动，蓝屏，插上U盘启动U盘里armbian

**Comment by HeroPoter** [comment]
![Screenshot_2023-11-11-19-35-35-090_com sonelli juicessh](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68175960/564f18c4-cb17-4750-9308-30bb14296893)
这是我挂接emmc分区，怎么修改哪个启动文件能从emmc启动？

**Comment by ophub** [comment]
/boot/armbianEnv.txt里的uuid要和/etc/fatab里的uuid一样，通过blkid看emmc上的uuid
