### ISSUE TITLE
mpp hw codec support failed

### ISSUE THREAD

**Issue by wnpllrzodiac** [ophub/amlogic-s9xxx-armbian#1856]
**Device Information | 设备信息**
 - SOC: [e.g. rk3566]
 - Model [e.g. panther X2]

**Armbian Version | 系统版本**
Armbian 23.11.0-trunk Lunar
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_lunar_save_2023.11/Armbian_23.11.0_rockchip_panther-x2_lunar_6.1.60_server_2023.11.01.img.gz

**Describe the bug | 问题描述**
ret = mpp_init(ctx, MPP_CTX_DEC, MppCodingType::MPP_VIDEO_CodingAVC);

if (MPP_OK != ret) 

mpp_err("mpp_init failed\\n");

mpp解码器初始化失败，是因为stb文件有问题吗？

**Comment by seamt** [comment]
我没有rockchip设备，也不知道mpp和stb。
你看看和这个有没有关系。
[https://github.com/ophub/amlogic-s9xxx-armbian/issues/1804#event-10864042329](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1804#event-10864042329)
