### ISSUE TITLE
Tanix Tx9 Pro (3G) missing wireless

### ISSUE THREAD

**Issue by Smim0** [ophub/amlogic-s9xxx-armbian#1857]
**Device Information | 设备信息**
 - SOC: S912
 - Model Tanix TX9 Pro (3G)

**Armbian Version | Armbian 23.11.0-trunk
 - Kernel Version:  6.1.59
 - Release: Lunar

**Describe the bug | 问题描述**
I have the same issue raised [here](https://github.com/ophub/amlogic-s9xxx-armbian/issues/315) with exactly the same device, I did a fresh install of Armbian 23.11.0-trunk Lunar and used the dtb meson-gxm-tx9-pro.dtb but wireless is not available.

`root@armbian:~# ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/tunnel6 :: brd :: permaddr 
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether e2:16:da:xx:xx:xx brd ff:ff:ff:ff:ff:ff
    altname end0`

Can you please let me know if I missed something?

Thanks

**Comment by wnpllrzodiac** [comment]
Havw you tried armbian-config to setup network？
