### ISSUE TITLE
请教下这个 repo 的 镜像和 arbian官方的有什么区别？

### ISSUE THREAD

**Issue by wnpllrzodiac** [ophub/amlogic-s9xxx-armbian#1859]
Panther x2 mpp 硬件编解码遇到问题，猜测是 vpu 内核没有开启。看到 armbian 官网上也有 panther x2适配的镜像，不知道两者的区别。安装官方的是否能修复 vpu的问题

**Comment by ophub** [comment]
官方是正版，这是社区分享版。
