### ISSUE TITLE
希望能够编译支持firefly rk3328开发板的openwrt

### ISSUE THREAD

**Issue by sehczaa** [ophub/amlogic-s9xxx-armbian#1861]
官方资料地址: https://www.t-firefly.com/doc/download/34.html
官方Armbian地址: https://www.armbian.com/renegade/

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/92673198/9c6b87f3-787e-4b8d-bedf-676411b1b881)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.11/Armbian_23.11.0_rockchip_renegade-rk3328_jammy_6.1.62_server_2023.11.15.img.gz


https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/OpenWrt_official_save_2023.11/openwrt_official_rockchip_renegade-rk3328_k6.1.62_2023.11.15.img.gz


这2个都测试下是否能正常启动。

启动后，修改下`/boot/armbianEnv.txt` 里的dtb名字改为`rk3328-roc-cc.dtb`试试能不能启动，这个是内核自带的，我不确定是否需要打补丁，如果rk3328-roc-cc.dtb可以启动就简单了。

固件默认使用的`rk3328-renegade.dtb`是armbian里带的dtb：`rk3328-roc-cc.dtb`改名的，我不确定要不要补丁，你试试反馈下结果。

**Comment by a393310872** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2023.11/Armbian_23.11.0_rockchip_renegade-rk3328_jammy_6.1.62_server_2023.11.15.img.gz
> 
> https://github.com/ophub/amlogic-s9xxx-openwrt/releases/download/OpenWrt_official_save_2023.11/openwrt_official_rockchip_renegade-rk3328_k6.1.62_2023.11.15.img.gz
> 
> 这2个都测试下是否能正常启动。
> 
> 启动后，修改下`/boot/armbianEnv.txt` 里的dtb名字改为`rk3328-roc-cc.dtb`试试能不能启动，这个是内核自带的，我不确定是否需要打补丁，如果rk3328-roc-cc.dtb可以启动就简单了。
> 
> 固件默认使用的`rk3328-renegade.dtb`是armbian里带的dtb：`rk3328-roc-cc.dtb`改名的，我不确定要不要补丁，你试试反馈下结果。

大佬,最近的荐片盒子,3566 8+32的盒子用X2的包换F大的DTB,SATA无法使用,能否添加下支持

**Comment by sehczaa** [comment]
> rk3328-roc-cc.dtb
刚尝试过了，Armbian和OpenWrt正常可以启动  修改dtb为rk3328-roc-cc.dtb后也可以启动
![2ede80116bce4811092da7a54ccc75e](https://github.com/ophub/amlogic-s9xxx-armbian/assets/92673198/bc6bfd20-859c-4d09-a93f-43407391fb58)

**Comment by ophub** [comment]
好的，那就添加成rk3328-roc-cc.dtb吧，这个是内核自带的
