### ISSUE TITLE
libc-bin报错

### ISSUE THREAD

**Issue by HeroPoter** [ophub/amlogic-s9xxx-armbian#1866]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

镜像写入硬盘，执行软件更新和armbian-software，和安装软件时均libc-bin报错，下面付截图

**Comment by HeroPoter** [comment]
盒子是cm311-1sa CH    btd用的是22C-D的
### 
![Uploading Screenshot_2023-11-13-15-11-01-789_com.sonelli.juicessh.jpg…]()

**Comment by HeroPoter** [comment]
盒子是cm311-1sa CH btd用的是22C-D的
固件：Armbian 23.11.0-trunk Jammy with Linux 6.1.60-ophub
### 报错代码
0 upgraded, 144 newly installed, 0 to remove and 7 not upgraded.
1 not fully installed or removed.
Need to get 0 B/87.1 MB of archives.
After this operation, 275 MB of additional disk space will be used.Do you want to continue? [Y/n] y
Extracting templates from packages: 100%
Setting up libc-bin (2.35-0ubuntu3.4) ...
Segmentation fault
Segmentation fault
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by HeroPoter** [comment]
![IMG_20231115_154615](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68175960/8527d09e-270c-454a-af00-2b3c48e47600)
![IMG_20231115_154435](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68175960/432286c6-73b8-4a60-b02a-f357d8f6e90a)

**Comment by HeroPoter** [comment]
目前解决方案是删除或mv掉 /var/lib/dpkg/info 目录

**Comment by seamt** [comment]
如果你说的“硬盘”是USB接口外置硬盘，这个问题像是UBOOT和外置USB设备兼容性的老问题。
你尝试在硬盘和电视盒之间连接USB Hub试试看。

**Comment by sif3992** [comment]
well done!
