### ISSUE TITLE
希望支持 荐片TVBOX

### ISSUE THREAD

**Issue by iJayscn** [ophub/amlogic-s9xxx-armbian#1867]
RK 3566

F大已经搞好了  dtb

不知是否已满足适配条件?

**Comment by Fiber-Five** [comment]
哈哈，前来支持

**Comment by ophub** [comment]
已经添加jp-tvbox

**Comment by doyoman** [comment]
sata可用了么

**Comment by a393310872** [comment]
> 已经添加jp-tvbox

大佬,依然是老问题,系统能用,但是无法使用SATA,

**Comment by ophub** [comment]
f大说最新的这个dtb支持sata

**Comment by a393310872** [comment]
> sata可用了么



> f大说最新的这个dtb支持sata

看到新版了,现在测试

**Comment by doyoman** [comment]
dtb是支持的   昨天把你的x2的镜像换dtb后sata还不行，qq群那个armbian换dtb可以sata

**Comment by yuxudong** [comment]
> 你试试今天我打包的armbian

在哪里下载？release里没有，只有2个星期前的

**Comment by doyoman** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/63859866/a30b7cf7-7ed1-41d4-928d-66aa5edb8c44)
还不行

**Comment by a393310872** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_lunar_save_2023.11/Armbian_23.11.0_rockchip_jp-tvbox_lunar_6.1.62_server_2023.11.16.img.gz
> 
> 11月的4个版本里都有，搜jp-tvbox

测试下来,依然是一样,无法使用SATA,能正常使用的包我传到网盘了

**Comment by ophub** [comment]
你更新到f大的内核试试，armbian-update -u flippy -k 6.1.61

**Comment by a393310872** [comment]
> 你更新到f大的内核试试 `armbian-update -u flippy -k 6.1.61`

果然,问题解决

**Comment by ophub** [comment]
我更新了内核配置，重新打包了armbian，使用最新下载的应该也支持sata了。

**Comment by iJayscn** [comment]
> 我更新了内核配置，重新打包了armbian，使用最新下载的应该也支持sata了。

经测试，可以了！ 感谢

**Comment by iJayscn** [comment]
> 我更新了内核配置，重新打包了armbian，使用最新下载的应该也支持sata了。

1、2023118 dtb更新了，修复了一些问题 -  F大。 https://github.com/iJayscn/N1-Backup/blob/master/rk3566-jp-tvbox.dtb

2、20231119 如果加过限流芯片的，需要换这个dtb -  F大，https://github.com/iJayscn/N1-Backup/blob/master/rk3566-jp-tvbox-2.dtb

**Comment by dinhchinh82** [comment]
@iJayscn could you help me the way you already did to extract the dtb for this TV box?

**Comment by iJayscn** [comment]
> @iJayscn could you help me the way you already did to extract the dtb for this TV box?

At the bottom of this post, there is an extracted DTB.

**Comment by dinhchinh82** [comment]
> > @iJayscncould you help me the way you already did to extract the dtb for this TV box?
> 
> At the bottom of this post, there is an extracted DTB.

have you extracted it from Android firmware file?

**Comment by Angel0726** [comment]
hdmi、键盘支持吗

**Comment by iJayscn** [comment]
> hdmi、键盘支持吗

这些指定是都支持的

**Comment by vpei** [comment]
这个盒子怎么刷机呀？

**Comment by vpei** [comment]
WiFi能搞定吗？

**Comment by rodren-lion** [comment]
> 谁能搞定这个HCY6355的无线网卡驱动呀，要不感觉这东西还是有些鸡肋。N1盒子是能WiFI不能内置硬盘，JP-Tvbox是能内置硬盘，不过现在WiFi搞不定。😥

直接更换 内置硬盘扩容就好了....

**Comment by yesterday666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by vpei** [comment]
> > 谁能搞定这个HCY6355的无线网卡驱动呀，要不感觉这东西还是有些鸡肋。N1盒子是能WiFI不能内置硬盘，JP-Tvbox是能内置硬盘，不过现在WiFi搞不定。😥
> 
> 直接更换 内置硬盘扩容就好了....

现在无线支持了，把N1换成这个盒子了。

**Comment by ophub** [comment]
参考f大的图给主板上几处供电的地方换一下电容，容量没有明确要求，体积合适就行，200-500范围都可以。6.3v 330uf的尺码是5*8，实际上有6*8的6.3v 470uf也是可以的，看起来会大一点。

总结：加6颗电容：16v 200-500uf一颗; 6.3v 200-500uf 5颗；加一颗sy6280aac限流芯片，并去掉限流芯片旁边的0欧电阻。

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/94754e52-717f-46f0-9361-c1f2251765c6)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/f86e865f-93e1-46ae-a2a3-d40ff85352f5)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/61b5549a-1c44-4749-b2ae-9b45f9ac6aac)

如果加过限流芯片的，需要换另外一个dtb。

**Comment by yesterday666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by Nice199** [comment]
oect有适配的固件和教程吗？最近降价厉害，是不是可以刷了。

**Comment by yesterday666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by myallten** [comment]
这款这个镜像能用NPU吗？

**Comment by yesterday666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yesterday666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by vpei** [comment]
内置的硬盘现在不能识别了？

**Comment by cikezlf** [comment]
> 参考f大的图给主板上几处供电的地方换一下电容，容量没有明确要求，体积合适就行，200-500范围都可以。6.3v 330uf的尺码是5_8，实际上有6_8的6.3v 470uf也是可以的，看起来会大一点。
> 
> 总结：加6颗电容：16v 200-500uf一颗; 6.3v 200-500uf 5颗；加一颗sy6280aac限流芯片，并去掉限流芯片旁边的0欧电阻。
> 
> 如果加过限流芯片的，需要换另外一个dtb: [rk3566-jp-tvbox_dtb.tar.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/14943374/rk3566-jp-tvbox_dtb.tar.gz)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/94754e52-717f-46f0-9361-c1f2251765c6)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/f86e865f-93e1-46ae-a2a3-d40ff85352f5)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/61b5549a-1c44-4749-b2ae-9b45f9ac6aac)



> 参考f大的图给主板上几处供电的地方换一下电容，容量没有明确要求，体积合适就行，200-500范围都可以。6.3v 330uf的尺码是5_8，实际上有6_8的6.3v 470uf也是可以的，看起来会大一点。
> 
> 总结：加6颗电容：16v 200-500uf一颗; 6.3v 200-500uf 5颗；加一颗sy6280aac限流芯片，并去掉限流芯片旁边的0欧电阻。
> 
> 如果加过限流芯片的，需要换另外一个dtb: [rk3566-jp-tvbox_dtb.tar.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/14943374/rk3566-jp-tvbox_dtb.tar.gz)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/94754e52-717f-46f0-9361-c1f2251765c6)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/f86e865f-93e1-46ae-a2a3-d40ff85352f5)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/61b5549a-1c44-4749-b2ae-9b45f9ac6aac)

我的JPTVBOX刷了其他的包变成砖头，求短接点位置救砖

**Comment by yesterday666** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by zzyzzyhong** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_lunar_save_2023.11/Armbian_23.11.0_rockchip_jp-tvbox_lunar_6.1.62_server_2023.11.16.img.gz
> > 11月的4个版本里都有，搜jp-tvbox
> 
> 测试下来,依然是一样,无法使用SATA,能正常使用的包我传到网盘了 https://cowtransfer.com/s/4941d6a735d04d 点击链接查看 [ Armbian_23.11.0-trunk_Jp-tvbox-3566_bookworm_current_6.1.62_minimal.img.zip ] ，或访问奶牛快传 cowtransfer.com 输入传输口令 cw91u8 查看；

网盘文件没了，老哥能再传下么？
