### ISSUE TITLE
咨询 pantherx2 可以使用 5.10的内核吗？

### ISSUE THREAD

**Issue by wnpllrzodiac** [ophub/amlogic-s9xxx-armbian#1870]
如题，说明文档写了支持6.x
问一下 5.x 不支持的原因。如果自己想支持，哪里需要修改
Rockchip支持 mpp驱动的内核只有5.10，想问一下，能不能安装 release下的6.x版本后，替换内核到5的版本。获得硬件编解码驱动

**Comment by ophub** [comment]
rockchip的dtb都添加到6.1.y了，其他内核里少dtb文件。
/etc/ophub-release 文件里把kernel_tags名字改成stable就可以更新其他系列了。
在使用中的armbian里更新内核应该可用

**Comment by wnpllrzodiac** [comment]
我试了修改 /etc/ophub-release 改成stable，然后执行 armbian-update 
就成功更新成砖了。。。上电后灯不亮，也ping不通了。

我的理解是5.10里面还没有pantherx2的dtb所以不认设备不能启动了？如果我自己fork你的kernel，然后手动打个包含pantherx2的dtb文件的5.10的内核包，是不是就可以正常工作了？还有个疑问，我看到镜像里面有很多个dtb文件，系统启动的时候是怎么知道要调用哪个dtb文件的？光看名字也不合逻辑啊。不知道kernel在编译的时候，是不是有个字段定义了启动的时候使用哪个dtb？

还有个问题，https://github.com/istoreos/istoreos/tree/istoreos-22.03/target/linux/rockchip/rk35xx/files/drivers 这个istoreos的代码里有rockchip的一些vpu的驱动代码。这个在linux内核6.x里是没有的。我验证过使用istoreos确实能正常调用到vpu的功能，armbian中没有办法正常使用。我有个不确定的猜测，能把istoreos的内核+dtb直接拿过来用在armbian上吗？我想使用armbian系统，但是又希望能支持硬件编解码。实在是想把这个折腾出来。

**Comment by ophub** [comment]
rockchip的内核和主线的不一样，使用5.10自己维护的，但是这个5.10不是你说的主线内核的版本，是rockchip的版本，rk35xx：https://github.com/unifreq/linux-5.10.y-rk35xx

**Comment by wnpllrzodiac** [comment]
好的，谢谢。
看起来下一步是研究如何把这个库的 pantherx2 的dtb反编译到 dts 合并到上述 repo 中，生成正确的内核5.10

比较尴尬的是每次刷有问题的内核就变砖，有点难搞，只能重新刷机。
