### ISSUE TITLE
s905x3,卡uboot time,换DTB无用

### ISSUE THREAD

**Issue by lsf343634352** [ophub/amlogic-s9xxx-armbian#1873]
**Device Information | 设备信息**
 - SOC: [S905x3]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
s905x3的盒子,朋友只给了我一个主板,我用的是Armbian_23.11.0_amlogic_s905x3_jammy_5.15.137_server_2023.11.01.img
U盘启动都卡在uboot time那里
model_database.conf查看了一下,DTB基本都换完了,结果都是一样.
东西是朋友买的云盒子,想刷个armbian当小电脑用
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/18700232-e5f1-4a42-b3ca-bf17831b72f2)
![4d247461e87d8cef5be215f76de08b3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/52167622-7c79-4c67-85cb-31d84ab0ccf8)

**Comment by by-JohnChen** [comment]
是不是u-boot.ext不对呢
