### ISSUE TITLE
PVE安装错误卸载后， armbin-software 一直显示已安装

### ISSUE THREAD

**Issue by iJayscn** [ophub/amlogic-s9xxx-armbian#1874]
**Device Information | 设备信息**
 - SOC: RK3566
 - Model JPBOX

**Armbian Version | 系统版本**

Armbian 23.11.0-trunk Bookworm with Linux 6.1.62-ophub

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/7768188/322e86f0-059a-4b93-a975-0b15e71fca0a)

PVE安装错误卸载后， armbin-software 一直显示已安装

没办法通过脚本重新安装。

**Comment by ophub** [comment]
试试选择u重新安装。

这个地方是检查软件包是否安装，影响的地方是这里：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/9a5bb0ba269290ce329b1abfb372b6cc1613d1bd/build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software/software-list.conf#L89


可能是pve-manager这个包没有卸载了

**Comment by iJayscn** [comment]
> 试试选择u重新安装。
> 
> 这个地方是检查软件包是否安装，影响的地方是这里：
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/9a5bb0ba269290ce329b1abfb372b6cc1613d1bd/build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software/software-list.conf#L89
> 
> 可能是pve-manager这个包没有卸载了

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/7768188/4e8161da-2dfb-4d68-8dca-bd4bcd760686)


果真如此，问题解决！
