### ISSUE TITLE
armbian怎么U盘启动，我想重新刷入armbian，试了几次都不行

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#1876]
armbian怎么U盘启动，我想重新刷入armbian，试了几次都不行，qi启动后发现还是盒子的老系统
![b46af412d4bff96a30dbab771394143](https://github.com/ophub/amlogic-s9xxx-armbian/assets/96900868/8796b688-379a-488e-8991-3cd393b9dc6d)

![ca041b0d4c3ac129843998df03477a0](https://github.com/ophub/amlogic-s9xxx-armbian/assets/96900868/4e83eadc-186d-4b38-9316-46c76f5ffe30)

**Comment by ophub** [comment]
进emmc。把/boot下的boot.src、armbianEnv.txt改个名字或者删除了就无法从emmc启动了。

**Comment by zhuguoqing123** [comment]
![1700360443992](https://github.com/ophub/amlogic-s9xxx-armbian/assets/96900868/29085976-f12c-4782-a96e-ac421fc6b457)


> 进emmc。把/boot下的boot.src、armbianEnv.txt改个名字或者删除了就无法从emmc启动了。只有魔百盒这样，其他盒子都可以usb优先启动。

我是这个，是是不是直接这两个删除就行

**Comment by ophub** [comment]
extlinux 目录和boot.scr

**Comment by zhuguoqing123** [comment]
> extlinux 目录和boot.scr

好的谢谢

**Comment by hzjppkk** [comment]
教程非常好用，可否写入帮助文档

**Comment by dubaisui** [comment]
请问刷入emmc后，在外接硬盘时如何优先从emmc启动，硬盘无系统挂着硬盘就启动不了

**Comment by ysuolmai** [comment]
之前的版本没有这个问题,是不是某一次更新后带来的.之前只要是armbian系统,插usb肯定是usb启动.
