### ISSUE TITLE
S905X　bookworm6.1.59可以正常使用，6.1.57的和最新的6.15.62都是加载黑屏

### ISSUE THREAD

**Issue by jinglei-dot** [ophub/amlogic-s9xxx-armbian#1877]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]　S905X
 - Model [e.g. HK1]　cumebox

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]　6.1.59
 - Release: [e.g. jammy/bullseye]　bookworm
 
版本：Linux armbian 6.1.59-ophub #1 SMP Fri Oct 20 12:48:37 CST 2023 aarch64 GNU/Linux**
DTB：-rwxr-xr-x 1 root root 39792 Oct 20 14:16 meson-gxl-s905x-p212.dtb

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

问题：使用20号版本6.1.59可以正常使用，基本功能wifi、eth和BT都正常，**但是加载13号6.1.57的和最新的6.15.62都是加载黑屏进入不了系统**，根本无法启动(使用5.15的bullseye版本是可以的启动的），请问是在这期间系统引导修改了什么东西吗？
几个版本没有做任何改动，包括dtb。

正常加载的版本链接：
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2023.10/Armbian_23.11.0_amlogic_s905x_bookworm_6.1.59_server_2023.10.20.img.gz

**Comment by ophub** [comment]
能启动的`cat /etc/ophub-release`

**Comment by jinglei-dot** [comment]
![Uploading release.PNG…]()

**Comment by jinglei-dot** [comment]
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='105'
MODEL_NAME='HG680P'
SOC='s905x'
FDTFILE='meson-gxl-s905x-p212.dtb'
FAMILY='meson-gxl'
BOARD='s905x'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.1.59'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='uEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-p212.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='rapdodge'
BUILDER_NAME='ophub'
PACKAGED_DATE='2023-10-20'
root@armbian:~#

**Comment by jinglei-dot** [comment]
> 能启动的`cat /etc/ophub-release`
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='105'
MODEL_NAME='HG680P'
SOC='s905x'
FDTFILE='meson-gxl-s905x-p212.dtb'
FAMILY='meson-gxl'
BOARD='s905x'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.1.59'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='uEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-p212.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='rapdodge'
BUILDER_NAME='ophub'
PACKAGED_DATE='2023-10-20'
root@armbian:~#

**Comment by jinglei-dot** [comment]
***@***.***:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='105'
MODEL_NAME='HG680P'
SOC='s905x'
FDTFILE='meson-gxl-s905x-p212.dtb'
FAMILY='meson-gxl'
BOARD='s905x'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.1.59'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='uEnv.txt'
ROOTFS_TYPE='ext4'
DISK_TYPE='usb'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-p212.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='rapdodge'
BUILDER_NAME='ophub'
PACKAGED_DATE='2023-10-20'
***@***.***:~#

邮件回复，网络不太好

________________________________
发件人: ophub ***@***.***>
发送时间: 2023年11月18日 23:24
收件人: ophub/amlogic-s9xxx-armbian ***@***.***>
抄送: jinglei ***@***.***>; Author ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] S905X　bookworm6.1.59可以正常使用，6.1.57的和最新的6.15.62都是加载黑屏 (Issue #1877)


能启动的cat /etc/ophub-release

―

**Comment by ophub** [comment]
这个什么也没改过，看不出有差异，可以是内核的事

**Comment by jinglei-dot** [comment]
好的，我有时间单把内核退回20号做个包试试
________________________________
发件人: ophub ***@***.***>
发送时间: 2023年11月18日 23:36
收件人: ophub/amlogic-s9xxx-armbian ***@***.***>
抄送: jinglei ***@***.***>; Author ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] S905X　bookworm6.1.59可以正常使用，6.1.57的和最新的6.15.62都是加载黑屏 (Issue #1877)


这个什么也没改过，看不出有差异，可以是内核的事

―
