### ISSUE TITLE
请问用同一个u盘刷多个盒子，刷完后，连在同一个路由器下，只会出现一个盒子。是否修改mac地址就能同时在线？

### ISSUE THREAD

**Issue by amesss** [ophub/amlogic-s9xxx-armbian#1879]
**Device Information | 设备信息**
 - SOC: S905L2
 - Model :HG680 LC

**Armbian Version | 系统版本23.11.0
 - Kernel Version: 6.1.62
 - Release:lunar

**Describe the bug | 问题描述**
请问用同一个u盘刷多个盒子，刷完后，连在同一个路由器下，只会出现一个盒子。是否修改mac地址就能同时在线？

**Comment by ophub** [comment]
你检查是mac地址一样？

**Comment by shijifeizhai** [comment]
可以的，我就是这么做的，改mac地址就分配不同IP了

**Comment by by-JohnChen** [comment]
> **Device Information | 设备信息**
>  - SOC: S905L2
>  - Model :HG680 LC
> 
> **Armbian Version | 系统版本23.11.0
>  - Kernel Version: 6.1.62
>  - Release:lunar
> 
> **Describe the bug | 问题描述**
> 请问用同一个u盘刷多个盒子，刷完后，连在同一个路由器下，只会出现一个盒子。是否修改mac地址就能同时在线？
> 
> 
首次运行会将mac地址写入u盘中，A盒子刷入后用当前u盘再去刷B盒子得到的mac地址是相同的。
我想知道Uboot 将生成的mac地址保存在哪里。我用魔百合做了集群每个都要手动修改mac地址比较麻烦@ophub
