### ISSUE TITLE
E900V22E正常启动，无法识别网卡，提供图片和DTB，希望能看看问题。

### ISSUE THREAD

**Issue by aminggoodboy** [ophub/amlogic-s9xxx-armbian#1881]
**Device Information | 设备信息**
 - 型号 E900V22E
 - SOC: [S905L2B]
 - Model [gxlx_p261_2g]

**Armbian Version | 系统版本**
 - Kernel Version: [Armbian_23.08.0_amlogic_s905l2_jammy_5.15.131_server_2023.09.12.img]
 - Release: [jammy]

**Describe the bug | 问题描述**
大佬，我是S905L2B芯片（gxlx_p261_2g），目前刷入Armbian_23.08.0_amlogic_s905l2_jammy_5.15.131_server_2023.09.12.img版本，可以启动，但不显示IP，不要求无线网，有线网卡能用就行。具体主板和部分参数如下图，帮忙看看。安卓DTB我放到网盘里了。https://aming.lanzouj.com/iGNde1ezh2pa
![Uploading 微信图片_20231120001304.jpg…]()

**Comment by aminggoodboy** [comment]
![71BsTCPKE4.jpg](https://picshack.net/ib/71BsTCPKE4.jpg)

**Comment by ophub** [comment]
在首页的设备列表里，点对应的设备进去对应的帖子，看原来大家是怎么使用的。一般情况下魔百盒的第一步都是先换安卓系统。

**Comment by aminggoodboy** [comment]
我现在已经是有root的安卓4.42系统了，也已经按照大家的经验操作了，使用了905l2-x7-5g.dtb，现在就是识别不到网卡，进入armbian没有显示IP，用命令重启网卡，显示错误。

**Comment by aminggoodboy** [comment]
> 在首页的设备列表里，点对应的设备进去对应的帖子，看原来大家是怎么使用的。一般情况下魔百盒的第一步都是先换安卓系统。

我现在已经是有root的安卓4.42系统了，也已经按照大家的经验操作了，用了905l2-x7-5g.dtb，现在就是识别不到闹钟，进入armbian没有显示IP，用命令重启闹钟，显示错误。
目前测试了
5.15可以启动 但是没网卡
5.10一直logo界面重启
6.X也是一直logo界面重启

**Comment by ophub** [comment]
刷tool里下载的安卓试试

**Comment by by-JohnChen** [comment]
内核问题刷6.x内核就能识别了

**Comment by by-JohnChen** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/06fcc61c-0e14-4aa9-b3e1-68ed23423d1d)

**Comment by by-JohnChen** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/18685c1b-d546-4d91-abdd-9e81bb9ea50a)

**Comment by aminggoodboy** [comment]
> 内核问题刷6.x内核就可以识别了
我用6.x内核无限重启logo界面，这个ext要选吗？

**Comment by aminggoodboy** [comment]
> 内核问题刷6.x内核就可以识别了

Armbian_23.08.0_amlogic_s905l2_jammy_6.1.52_server_2023.09.12.img 我用得这个镜像，然后修改ext，用得官方推荐得u-boot-s905x-s912.bin ，现在还是无限logo界面重启

**Comment by aminggoodboy** [comment]
> 刷工具里下载的安卓尝试

尝试了tool里面收录得刷机包，正常开机了，功能也是正常得，还是不得行

**Comment by by-JohnChen** [comment]
ttl看看输出日志

**Comment by aminggoodboy** [comment]
> ttl查看输出日志或者先刷5.1然后再系统内升级内核
直接在img镜像里面能升级内核不，现在问题是没网络，所以没法升级内核。。。ttl我刚才链接测试了，不跑码。。

**Comment by by-JohnChen** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/00456a6c-a006-4ac6-84e3-7b29d01349b3)
重新建立链接就好了啊

**Comment by aminggoodboy** [comment]
> [![image](https://user-images.githubusercontent.com/11454456/284622707-00456a6c-a006-4ac6-84e3-7b29d01349b3.png)](javascript:void(0)) 重新建立链接就好了啊 [目前最新6.1.63内核](https://github.com/ophub/kernel/releases/download/kernel_stable/6.1.63.tar.gz) 下好丢到U盘里然后插到盒子上 新内核的boot解压 丢到`/boot`里面 然后重新建立链接 新内核的headers解压丢到`/usr/src/`里面 新内核的modules解压丢到`/usr/lib/modules/`里面

这个。。。太深奥了，不会操作

**Comment by aminggoodboy** [comment]
> 刷工具里下载的安卓尝试

o大有什么好的办法吗？

**Comment by wnpllrzodiac** [comment]
> > ![image](https://user-images.githubusercontent.com/11454456/284622707-00456a6c-a006-4ac6-84e3-7b29d01349b3.png) 重新建立链接就好了啊 [目前最新6.1.63内核](https://github.com/ophub/kernel/releases/download/kernel_stable/6.1.63.tar.gz) 下好丢到U盘里然后插到盒子上 新内核的boot解压 丢到`/boot`里面 然后重新建立链接 新内核的headers解压丢到`/usr/src/`里面 新内核的modules解压丢到`/usr/lib/modules/`里面
> 
> 这个。。。太深奥了，不会操作

ln -s [target] [newlinkfile]

cd /boot
mv zImage zImage.bak
ln -s vmlinuz-6.1.55-Devsoft zImage
mv uInitrd uInitrd.bak
ln -s uInitrd-6.1.55-Devsoft zImage uInitrd

**Comment by wnpllrzodiac** [comment]
我的问题也是装官方包6.1.y内核没问题。换到5.10.x 支持mpp的内核，网卡不工作。我的pantherx2还没有显示接口。没法调试。
@aminggoodboy 你知道怎么ttl或者串口调试吗？

**Comment by aminggoodboy** [comment]
> 我的问题也是装官方包6.1.y内核没问题。换到5.10.x支持mpp的内核，中断不工作。我的pantherx2还没有显示接口。无法调试。 @aminggoodboy你知道怎么ttl或者串口调试吗？

串口调试我知道怎么弄，我也有设备，但是我没成功过。。。

**Comment by aminggoodboy** [comment]
> > > [![图像](https://user-images.githubusercontent.com/11454456/284622707-00456a6c-a006-4ac6-84e3-7b29d01349b3.png)](javascript:void(0))重新建立链接就好了啊[目前最新的6.1.63内核](https://github.com/ophub/kernel/releases/download/kernel_stable/6.1.63.tar.gz)下好丢到U盘里然后插到盒子上新内核的boot解压丢到`/boot`里面然后重新建立链接新内核的标头解压丢到`/usr/src/`新内核的模块解压里面丢到`/usr/lib/modules/`里面
> > 
> > 
> > 这个。。。太深奥了，不会操作
> 
> ln -s [目标] [新链接文件]
> 
> cd /boot mv zImage zImage.bak ln -s vmlinuz-6.1.55-Devsoft zImage mv uInitd uInitrd.bak ln -s uInitrd-6.1.55-Devsoft zImage uInitd

辜负了你对我的指导，我还是没弄好，准备放弃了，已经折腾了一个月了。。

**Comment by by-JohnChen** [comment]
> ![71BsTCPKE4.jpg](https://camo.githubusercontent.com/2dd703ee1bd7d162ce9dc6b39a2238ec66558b8a186466d83844657b7166555a/68747470733a2f2f706963736861636b2e6e65742f69622f373142735443504b45342e6a7067)

其实你拍这个网变并没有什么卵用

**Comment by aminggoodboy** [comment]
> > ![71BsTCPKE4.jpg](https://camo.githubusercontent.com/2dd703ee1bd7d162ce9dc6b39a2238ec66558b8a186466d83844657b7166555a/68747470733a2f2f706963736861636b2e6e65742f69622f373142735443504b45342e6a7067)
> 
> 其实你拍这个网变并没有什么卵用

hahaha，到现在我也没搞明白应该拍什么图上来。

**Comment by by-JohnChen** [comment]
试试 u-boot-p212.bin + meson-gxl-s905l2-e900v21e.dtb

**Comment by by-JohnChen** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/02678312-8176-4356-a0c1-52cedb3614f3)
这个是从哪里读取到的@ophub
