### ISSUE TITLE
怎么修改MAC地址，实现一次写入多次刷机而不重mac

### ISSUE THREAD

**Issue by by-JohnChen** [ophub/amlogic-s9xxx-armbian#1885]
原厂uboot传入的mac不生效，ttl中观察到mac参数由载入的uboot传入，而载入的uboot ENV是只读的不可更改

**Comment by by-JohnChen** [comment]
@ophub mac写在boot.ext中吗

**Comment by ophub** [comment]
不是，默认读取盒子原生ip，如果读取不到u-boot会生成一个

**Comment by by-JohnChen** [comment]
> 不是，默认读取盒子原生ip，如果读取不到u-boot会生成一个，理论上不存在重复mac地址的情况。
> 
> 很早前我在网络设置里添加了自定义mac地址的设置，有些用户喜欢盒子自己的mac地址，我就移除了，你可以自定义mac地址。/etc/network/interfaces，设置方法看仓库文档

生成之后会写死在U盘里，刷第二个盒子时会出现mac重复的情况，我想知道的载入的uboot的mac变量是从哪里读取的。

**Comment by by-JohnChen** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/48f88364-d426-4df0-9e8d-e1443cdbd54c)

**Comment by by-JohnChen** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/d79ba28e-90a5-491a-9d40-7c2b1060a918)
原厂uboot带有mac参数，但是会内核恐慌，载入的mac变量不可更改

**Comment by by-JohnChen** [comment]
@ophub

**Comment by by-JohnChen** [comment]
0x9D048F5

**Comment by seamt** [comment]
Amlogic原厂的Android刷机工具，理论上是支持批量刷机不重mac的。
原理就是，每次刷机的时候，都给boot分区一个新的mac参数。
只是我试了试，没有成功。
我的盒子刷Android之后，因为选择了“全部擦除”，三码弄丢了。从此一直想再把原厂的mac地址刷回来。
希望有懂行的朋友提供线索。

**Comment by by-JohnChen** [comment]
> Amlogic原厂的Android刷机工具，理论上是支持批量刷机不重mac的。 原理就是，每次刷机的时候，都给boot分区一个新的mac参数。 只是我试了试，没有成功。 我的盒子刷Android之后，因为选择了“全部擦除”，三码弄丢了。从此一直想再把原厂的mac地址刷回来。 希望有懂行的朋友提供线索。

三码是存在uboot里面的
setenv mac xx:xx:xx:xx:xx:xx
setenv sn xxxxxxxxxxxx
setenv imei xxxxxxxxxxxx
然后saveenv

**Comment by by-JohnChen** [comment]
> Amlogic原厂的Android刷机工具，理论上是支持批量刷机不重mac的。 原理就是，每次刷机的时候，都给boot分区一个新的mac参数。 只是我试了试，没有成功。 我的盒子刷Android之后，因为选择了“全部擦除”，三码弄丢了。从此一直想再把原厂的mac地址刷回来。 希望有懂行的朋友提供线索。
你可以用这个脚本来读取uboot的env数据
```#!/bin/bash

binary_file="/dev/mmcblk2"  # 替换为你的二进制文件名
offset=113246212          # 替换为你想要开始读取的十进制偏移位置

# 从指定偏移位置读取4K的数据并转换为十六进制字符串
hex_string=$(dd if="$binary_file" bs=1 skip="$offset" count=32768 2>/dev/null | xxd -p)

# 将0x20替换为空格，将0x00替换为换行
formatted_string=$(echo -n "$hex_string" | sed 's/00/0a/; s/a0/0a/g')

# 将剩余的十六进制转换为ASCII
ascii_data=$(echo -n "$formatted_string" | xxd -r -p)

echo  "$ascii_data"```

**Comment by seamt** [comment]
> 你可以用这个脚本来读取uboot的env数据

非常感谢。
我的电视盒子是CM311-1a。盒子里是改刷的Android，用U盘里的Armbian启动。
分别试用Android系统的三个分区bootloader, boot, env启始位置作偏移量，只有env分区能读到有用的信息。另外两个分区读到都是乱码。
机背贴纸与env分区信息对照：（左值为机背贴纸，右值为env分区读取到的变量）
```
STBID = androidboot.serialno, usid
MAC = ethaddr (lower case), mac (2 times), androidboot.mac
SN = androidboot.deviceid, deviceid
YSN = <undefined>
<undefined> = androidboot.oem.key1 (2 times)
```
这个env分区是的刷机时写入的，还是Android开机时自动生成的，就不清楚。
举例来说，我有一台EMMC写入Armbian的盒子（我有多台同型盒子），Armbian启动后仍然可以看到原厂Android的mac地址。
env分区的偏移是1GB+，理论上讲已经被Armbian覆盖了（Armbian的第一个分区起始偏移是在100MB+）。
那么本机mac地址（或者还包括usid, deviceid, oem.key, etc)难道是保存在原厂的bootloader分区？
回到你首贴的问题，只要本机原厂Android的mac还在（肯定是每台机器不同），就不用担心批量刷Armbian导致mac冲突。
但是，如果原厂Android的mac被清除了（我有一台丢三码的机器，env分区里的mac参数是 mac=${mac} ），Armbian每次运行会随机生成一个新的mac地址（我印象）。

**Comment by seamt** [comment]
今天测试清除盒子Android的env分区之后，向盒子的EMMC刷写Armbian系统。
Armbian启动后，发现网卡的mac是之前用你的脚本测到的"ethaddr"值，而不是mac值。说明mac值随env分区被清除，ethaddr却没有被清除。
再把盒子刷回Android。进入Android，这时网卡mac是随机生成的（每次开机不同），但是用你的脚本仍然测到一直不变的“ethaddr”值。

使用同一个Armbian系统的U盘，分别刷相同型号（CM311-1a）不同的盒子，每台盒子上生成的ethaddr值是不同的。每台盒子的ethaddr可以永久保存，即使刷回Andriod时使用了“Erase all”选项。

推测Android的env分区里ethaddr值，是由U盘Armbian启动后生成的，而非盒子自带的。因为Android系统并不理会这个值。

回应你首贴的问题，同一个U盘批量刷机，我的测试结论是：不会发生mac地址重复的问题。我的Armbian版本是ophub构建的debian12/kernel6.1。使用默认的networking和NetworkManger设置，没有设置mac地址。

ethaddr的生成机制和保存位置，仍然不清楚。o大之前的贴子里推荐了uboot的源码，有能力的朋友可以分板。
[https://github.com/ophub/amlogic-s9xxx-armbian/issues/617](https://github.com/ophub/amlogic-s9xxx-armbian/issues/617)
[https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/board-common.c#L78](https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/board-common.c#L78)
[https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/sm.c#L92](https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/sm.c#L92)

下面之篇，理论上讲了一下mac存放的可能位置。
[https://tuxengineering.com/blog/2020/09/16/U-Boot-handling-MAC-address.html](https://tuxengineering.com/blog/2020/09/16/U-Boot-handling-MAC-address.html)
