### ISSUE TITLE
[ Error ] The [ etc/os-release: ID ] is invalid

### ISSUE THREAD

**Issue by rossbcan** [ophub/amlogic-s9xxx-armbian#189]
Used new 20.04.04 Ubuntu virtual machine (Vmware)

Followed instructions:
sudo apt-get update -y
sudo apt-get full-upgrade -y
sudo apt-get install -y $(curl -fsSL git.io/ubuntu-2004-server)
git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-armbian.git
ls build/output/images: Armbian_22.05.0_Aml_s912_focal_5.15.29_2022.03.18.2159.img

sudo ./rebuild -d -b s905x3 -k 5.15.30

![image](https://user-images.githubusercontent.com/13289915/159308016-21c9e8c0-4461-497f-9ae7-516b3edcb607.png)

What have I missed / done wrong?
Thanks; Bill

**Comment by rossbcan** [comment]
my error.

place Armbian_22.05.0-trunk_Lepotato_focal_current_5.10.107.img in build/output/images
I used incorrect image (above)
built successfully

**Comment by ophub** [comment]
ok
