### ISSUE TITLE
firefly-rk3399 armbian poweroff 关机以后 等待几秒 什么也不操作 会自动开机 您好 这个是BUG吗？

### ISSUE THREAD

**Issue by xxlive** [ophub/amlogic-s9xxx-armbian#1892]
firefly-rk3399 armbian 使用固件以后，
使用 poweroff 命令关机以后  等待几秒中会自动开机 ,
你好 这个是因为DTB的原因吗？ 就是执行关机命令下 什么不操作 过几秒钟就自动开机了 。

armbian官方的固件也是这样。

但是用萤火虫官方的debian系统是可以正常关机，关机以后不会自动开机的。

**Comment by ophub** [comment]
某些开发板具有电源管理功能，可以设置在关机后自动开机。
Advanced Configuration and Power Interface (ACPI) 是一种用于管理电源和其他系统设备的标准。在一些情况下，可能会配置ACPI事件，使得在关机后发生某个特定事件时自动开机。
对这个盒子的配置不了解，你可以看一下厂商官网的资料

**Comment by xxlive** [comment]
嗯 好的 谢谢

**Comment by alegoho** [comment]
> firefly-rk3399 armbian 使用固件以后， 使用 poweroff 命令关机以后 等待几秒中会自动开机 , 你好 这个是因为DTB的原因吗？ 就是执行关机命令下 什么不操作 过几秒钟就自动开机了 。
> 
> armbian官方的固件也是这样。
> 
> 但是用萤火虫官方的debian系统是可以正常关机，关机以后不会自动开机的。

你好，请问你用瑞芯微刷机工具那个版本刷的？我换了几个版本都不行，在firefly官方上下的那个可以刷入，但启动不了，一直卡在开机画面，还有loader用的那个版本？

**Comment by magicGina** [comment]
解决了吗？有没有方法绕过？
