### ISSUE TITLE
[建议]取消/boot的默认挂载并Armbian-update

### ISSUE THREAD

**Issue by Xarth-Mai** [ophub/amlogic-s9xxx-armbian#1893]
之前遇到过apt upgrade的时候有软件包修改了/boot下的文件导致机器重启后无法引导，从此之后我取消了/boot的默认挂载并且在Armbian-update之前手动修改
也许应该取消/boot的默认挂载并在Armbian-update中加入自动挂载机制
这可以避免/boot下的文件被错误修改毕竟这些设备不具有x86设备那样的高兼容性

**Comment by ophub** [comment]
不存在你说的问题
