### ISSUE TITLE
scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by w12563789** [ophub/amlogic-s9xxx-armbian#1895]
Device Information | 设备信息

SOC: [S095L3a]
Model [cm311-1a]
Armbian Version | 系统版本

Kernel Version: [5.15.137]
Release: [ jammy]
Describe the bug | 问题描述
I want to build kernel module according to [redroid-modules](https://github.com/remote-android/redroid-modules), but run dkms fail.
root@armbian:/tmp/redroid-modules# dkms install redroid-ashmem/1
Kernel preparation unnecessary for this kernel. Skipping...

Building module:
cleaning build area...
make -j4 KERNELRELEASE=5.15.137-ophub all KERNEL_SRC=/lib/modules/5.15.137-ophub/build....(bad exit status: 2)
Error! Bad return status for module build on kernel: 5.15.137-ophub (aarch64)
Consult /var/lib/dkms/redroid-ashmem/1/build/make.log for more information.
root@armbian:/tmp/redroid-modules# cat /var/lib/dkms/redroid-ashmem/1/build/make.log DKMS make.log for redroid-ashmem-1 for kernel 5.15.137-ophub (aarch64)
Mon Nov 27 04:00:58 PM CST 2023
make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Entering directory '/usr/src/linux-headers-5.15.137-ophub'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 12.3.Rel1 (Build arm-12.35)) 12.3.1 20230626
  You are using:           gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  CC [M]  /var/lib/dkms/redroid-ashmem/1/build/ashmem.o
  CC [M]  /var/lib/dkms/redroid-ashmem/1/build/deps.o
scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/redroid-ashmem/1/build/deps.o] Error 127
make[2]: *** Deleting file '/var/lib/dkms/redroid-ashmem/1/build/deps.o'
make[2]: *** Waiting for unfinished jobs....
scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/redroid-ashmem/1/build/ashmem.o] Error 127
make[2]: *** Deleting file '/var/lib/dkms/redroid-ashmem/1/build/ashmem.o'
make[1]: *** [Makefile:1909: /var/lib/dkms/redroid-ashmem/1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.137-ophub'
make: *** [Makefile:8: all] Error 2
做了如下尝试：
1：cp /usr/lib/aarch64-linux-gnu/libc.so.6 /lib64/ 和 cp /usr/lib/aarch64-linux-gnu/libc.so.6 /lib/
将文件复制进去后重新执行“dkms install redroid-ashmem/1”，失败，报错同上。
请问要如何才能解决这个错误呢？

**Comment by ophub** [comment]
试试更换为dev系列的内核

**Comment by w12563789** [comment]
用了dev后，> scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory 这个报错没了，但是出现了下面的报错

/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/redroid-ashmem/1/build/deps.o] Error 126
make[2]: *** Deleting file '/var/lib/dkms/redroid-ashmem/1/build/deps.o'
make[2]: *** Waiting for unfinished jobs....
/var/lib/dkms/redroid-ashmem/1/build/ashmem.c: In function ‘ashmem_init’:
/var/lib/dkms/redroid-ashmem/1/build/ashmem.c:950:15: error: too few arguments to function ‘register_shrinker’
950 | ret = register_shrinker(&ashmem_shrinker);
| ^~~~~~~~~~~~~~~~~
In file included from ./include/linux/list_lru.h:13,
from ./include/linux/fs.h:13,
from ./arch/arm64/include/asm/elf.h:141,
from ./include/linux/elf.h:6,
from ./include/linux/module.h:19,
from /var/lib/dkms/redroid-ashmem/1/build/ashmem.c:13:
./include/linux/shrinker.h:99:27: note: declared here
99 | extern int __printf(2, 3) register_shrinker(struct shrinker *shrinker,
| ^~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:250: /var/lib/dkms/redroid-ashmem/1/build/ashmem.o] Error 1
make[1]: *** [Makefile:2012: /var/lib/dkms/redroid-ashmem/1/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.42-ophub'
make: *** [Makefile:8: all] Error 2
