### ISSUE TITLE
armbian-install 报错 failed umount [/ddbr/install]

### ISSUE THREAD

**Issue by farquer** [ophub/amlogic-s9xxx-armbian#1897]
设备：
魔百和 cm311-1a-yst（s905l3a）

镜像:
Armbian_23.11.0_amlogic_s905l3a_jammy_6.1.63_server_2023.11.24.img.gz

固件：
[android_tv_cm311-1a-yst_s905l3a.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_cm311-1a-yst_s905l3a.tar.xz)

错误描述：
执行 armbian-install 后，在 copying /usr 之后报错
类似 [failed] umount [/ddbr/install]

**Comment by farquer** [comment]
烧录后  修改 uEnv.txt   FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb  进行 U启 没问题，  armbian-install  报错

**Comment by ophub** [comment]
魔百和，降低频率使用

**Comment by farquer** [comment]
已经是2.0的U盘了

**Comment by farquer** [comment]
找到了 参考 https://github.com/ophub/amlogic-s9xxx-armbian/issues/1070 对吧
