### ISSUE TITLE
cm311-1a yst armbian系统，ssh连接不上，ha等其他docker容器都在跑，唯独ssh连接不上，密码也是确定对的

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#1898]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]
cm311-1a yst
**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/96900868/e5e4e10e-4226-4439-b2ed-d647cb3f1ead)

**Comment by w12563789** [comment]
你这ip不对吧，要使用内网ip，内网ip一般都是192.168.xxx.xxx。在路由器中查看你这个机顶盒的ip地址，用查到的ip地址进行连接。

**Comment by qkl9527** [comment]
是不是系统出错了，我也有遇到过，就是docker进程无法连接ipv6，会一直报错，然后好像是系统crash了吧，正确密码也进不去

**Comment by ginitaimeiyty** [comment]
这是docker不兼容，我是B类地址，安装docker机顶盒正常上网都不行，禁用掉docker就恢复正常了

> 你这ip不对吧，要使用内网ip，内网ip一般都是192.168.xxx.xxx。在路由器中查看你这个机顶盒的ip地址，用查到的ip地址进行连接。
