### ISSUE TITLE
cm211-1 emmc写入提示成功，重启拔出U盘后无法进入emmc系统

### ISSUE THREAD

**Issue by zhengzhengju** [ophub/amlogic-s9xxx-armbian#1899]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
Armbian_23.11.0_amlogic_s905l3-cm211_bullseye_6.1.63_server_2023.11.24.img
 - Kernel Version: [e.g. 6.1.63]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**

cm211-1 emmc写入提示成功，重启拔出U盘后无法进入emmc系统

尝试过：Armbian_23.11.0_amlogic_s905l3b-bullseye_6.1.63_server_2023.11.24.img
dtb也尝试过124
结果都是一样
盒子也刷的仓库里的cm211-1安卓镜像

**Comment by zhengzhengju** [comment]
![屏幕截图 2023-11-28 192510](https://github.com/ophub/amlogic-s9xxx-armbian/assets/10026466/8f9585c9-69b7-455e-bee1-297bd80ba004)

**Comment by zhengzhengju** [comment]
使用Armbian_23.11.0_amlogic_s905l3-cm211_jammy_5.15.139_server_2023.11.24.img，经过十几次的重启以及关闭开机测试，一切正常

**Comment by zhengzhengju** [comment]
但是Armbian_23.11.0_amlogic_s905l3-cm211_jammy_5.15.139_server_2023.11.24.img，有线插上无法驱动。无线正常

**Comment by zhengzhengju** [comment]
仅仅5.15.*内核写入emmc后可以正常启动。6.*内核的都是写入成功，但无法启动。帮忙处理下。谢谢

**Comment by ophub** [comment]
参考model表，自己测试哪个组合合适

**Comment by zhengzhengju** [comment]
方便提供下model表链接吗？还是所指的是执行armbian-install后选择的序号？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

**Comment by zhengzhengju** [comment]
很遗憾我没能力处理好该事情。但依然感谢ophub大神的回复！
总之现在的问题就是：
**使用内核5.15.***的，**无法使用有线网络**，无线网络正常。可以写入emmc并从**emmc启动正常**
**使用内核6.*.***的，**有线、无线网络都正常**，可以写入emmc但**emmc无法启动
我有过思路，就是将两个内核的配置文件互换。但奈何我只是一个普通用户！

**Comment by zhengzhengju** [comment]
你好大神，是SSH进去进行内核更新吗？

**Comment by zhengzhengju** [comment]
尝试将内核更新到6.1.63成功。有线依然无法使用。还是谢谢大神了
