### ISSUE TITLE
Bagaimana cara untuk menghidupkan wifi internal di s905x?

### ISSUE THREAD

**Issue by KuNcHrOoT** [ophub/amlogic-s9xxx-armbian#19]
halo kak, saya mau bertanya tentang cara menghidupkan wifi internal di device s905x (HG680P) kebutuhan saya buat remote si stb kak. topologi HG680P -> hotspot -> Laptop akses ssh. terimkasih kak.

**Comment by KuNcHrOoT** [comment]
saya juga menggunkan tutorial buid fw nya pakai link https://free.facebook.com/groups/447949046027700/permalink/676612343161368/?refid=18&_ft_=qid.-7429927420893098120%3Amf_story_key.676612343161368%3Atop_level_post_id.676612343161368%3Atl_objid.676612343161368%3Acontent_owner_id_new.100000470471993%3Apage_id.447949046027700%3Asrc.22%3Astory_location.6%3Astory_attachment_style.file_upload%3Afilter.GroupStoriesByActivityEntQuery%3Aott.AX_yEudpRisu89gA%3Atds_flgs.3%3Aactrs.100000470471993%3Apage_insights.%7B%22447949046027700%22%3A%7B%22page_id%22%3A447949046027700%2C%22page_id_type%22%3A%22group%22%2C%22actor_id%22%3A100000470471993%2C%22dm%22%3A%7B%22isShare%22%3A0%2C%22originalPostOwnerID%22%3A0%7D%2C%22psn%22%3A%22EntGroupFileRevisionCreationStory%22%2C%22post_context%22%3A%7B%22object_fbtype%22%3A657%2C%22publish_time%22%3A1584157393%2C%22story_name%22%3A%22EntGroupFileRevisionCreationStory%22%2C%22story_fbid%22%3A%5B676612343161368%5D%7D%2C%22role%22%3A1%2C%22sl%22%3A6%7D%7D&__tn__=%2As-R&_rdc=1&_rdr namun sudah lama grup ini tidak membahas armbian lagi kak

**Comment by ophub** [comment]
`armbian-config` > `Network`

The available wifi is enabled by default. If your box’s wifi is available, you can activate it here.

**Comment by shevdodo** [comment]
the hg680p internal wifi driver is rtl8189fs and rtl8188fu ( 2 variant internal wifi ).
this release not include that driver, so internal wifi can't active from armbian-config -> Network.
please include both wifi driver in the next release.
Thank you.

**Comment by ophub** [comment]
These two drivers in the kernel are not yet.

Officially released the first version of the driver (rtw88) in 2019. At that time, it only supported PCIE RTL88xxXE, but it also stated that it will support it in the future. RTL88xxXU of USB and RTL88xxXS of SDIO, but until 2021, no follow-up drivers have been seen.

https://www.phoronix.com/scan.php?page=news_item&px=Realtek-RTW88-WiFi-Linux-Driver

**Comment by ophub** [comment]
fork repo.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/966bb3bbf7fe43aea5722fb59cfe1dbcfcb00cc6/.github/workflows/build-armbian.yml#L79

change to: sudo ./make -d -b s905x -k 5.7.2 -v beta
