### ISSUE TITLE
分享一个创维e900v22d-2的设备树文件

### ISSUE THREAD

**Issue by by-JohnChen** [ophub/amlogic-s9xxx-armbian#1903]
**Device Information | 设备信息**
 - SOC: ［s905l3］
 - Model | 型号: ［e900v22d-2］

**Armbian Version | 系统版本**
 - Kernel Version | 内核版本: [6.1.62]
 - Release | 发行版: [ jammy]

**Board Info | 主板信息**
 - memory | 内存 「2G」
 - storage | 存储 「8G」
 - Board ID | 板号 「5800-2AMBA02」
 - ```u-boot-p212.bin```
 - ```meson-gxl-s905l3-e900v22d-2.dtb```
[meson-gxl-s905l3-e900v22d-2.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/13503166/meson-gxl-s905l3-e900v22d-2.zip)

**Comment by by-JohnChen** [comment]
附图
晶晨 S905L3
长鑫存储 CXDQ3BFAM (1G DDR4)
硅格 SMG8000C-S27B8G(8G EMMC)
![IMG_20231130_003453.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/d2136427-9bf0-423e-bc45-d8aee857da5a)

![IMG_20231130_003441.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/fb0856cb-2a5c-4520-9bc1-2a8c92bfc52a)
![正在上传 IMG_20231130_003703.jpg…]()

**Comment by by-JohnChen** [comment]
原厂dts
[e900v22d-2.dts](https://github.com/ophub/amlogic-s9xxx-armbian/files/13503371/e900v22d-2.txt)

**Comment by lishiren-admin** [comment]
这个现在有能刷的armbian固件么

**Comment by Cp0204** [comment]
> 这个现在有能刷的armbian固件么

Armbian_24.2.0_amlogic_s905l3_bookworm_5.15.145

我测试可以刷，但是HDMI不显示，可以SSH上去

**Comment by EberYubo** [comment]
armbian蓝牙能用吗
