### ISSUE TITLE
我有一个HG680-L的盒子，SOC是s905lb，请问一下可以刷amlogic_s905lb.img的固件吗，看设备支持列表里没有这款盒子

### ISSUE THREAD

**Issue by hysunstar** [ophub/amlogic-s9xxx-armbian#1907]
盒子主板照片如下：
![微信图片_20231201091555](https://github.com/ophub/amlogic-s9xxx-armbian/assets/3232547/2cc43e21-ed3b-4dbd-af0f-5a85b9da06bd)

**Comment by ophub** [comment]
相近的都可以试试，USB试试能顺利启动即可使用，先测试5.15的

**Comment by hysunstar** [comment]
好的，我试试，谢谢！

**Comment by xmbhjQAQ** [comment]
请问结果怎么样

**Comment by hysunstar** [comment]
> 请问结果怎么样

可以用
