### ISSUE TITLE
SW799 6.X内核无法正常启动

### ISSUE THREAD

**Issue by MoorCorPa** [ophub/amlogic-s9xxx-armbian#1908]
**Device Information | 设备信息**
 - SOC: RockChip RK3399
 - Model SW799 Ver2.4 2020-02-21

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.63
 - Release: trixie

**Describe the bug | 问题描述**
Armbian_23.11.0_rockchip_sw799_trixie_6.1.63_server_2023.11.24

测试了好几个6.x的版本都不能正常启动，会卡在有个，自编译5.15.x内核系统正常运行
描述与[issues/1608](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1608)一致
附上log，能力不足不能排查原因抱歉
[terminal-log.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/13521052/terminal-log.txt)

**Comment by ophub** [comment]
我改成5.15了
