### ISSUE TITLE
x96 max+  bullseye desktop 鼠标移动问题

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#191]
通过armbian-config安装desktop后，鼠标可以移动和点击，但是箭头光标不能跟随鼠标一起移动，没法操作。
在桌面服务还未完成启动前，光标能短暂跟随鼠标一起移动，表现正常，等完全启动完后，光标就停在原地不动了
请问下 这个该如何解决？

**Comment by ophub** [comment]
https://adatiya.com/post/23203.html

我一直使用ssh访问服务器版，没安装过桌面。鼠标的速度问题应该和windows等系统类似吧，找到鼠标设置的地方根据自己的手感设置下。

**Comment by EastWoodYang** [comment]
对这块比较陌生，我刚刚安装了5.16.y内核的，光标能正常跟随鼠标移动了，之前5.15.y内核的不行

**Comment by ophub** [comment]
好的，我没安装过桌面呢，小盒子不能当电脑使唤，我感觉跑服务器模式还行，跑跑docker和服务不错，不知道跑图形桌面会不会有点吃力。

**Comment by EastWoodYang** [comment]
没多少软件可用，我主要的诉求是跑rdp来远程Windows用，浏览器安装了Firefox，一般的网页没啥问题，视频不大行

**Comment by ophub** [comment]
openwrt不用gpu渲染，跑的时候50多度。跑armbian桌面版可能温度会高，夏天的时候加个风扇。

**Comment by EastWoodYang** [comment]
好的，静静等待夏日...

**Comment by JFLim1** [comment]
@ophub @EastWoodYang 

Just to share, I use GT King Pro as a lightweight desktop pc daily. Chromium, Firefox and LibreOffice works well so far and with Panfrost enabled.

Firefox video performance can be improved with:

On Wayland Session:
QT_QPA_PLATFORM=wayland GDK_BACKEND=wayland MOZ_ACCELERATED=1 MOZ_ENABLE_WAYLAND=1 MOZ_WEBRENDER=1 firefox

On Xorg Session
MOZ_X11_EGL=1 MOZ_ACCELERATED=1 MOZ_WEBRENDER=1 firefox

**Comment by ophub** [comment]
Thank you for sharing

**Comment by JFLim1** [comment]
> Have you try UT8 Pro? It has higher hardware, but rockchip CPU, and nearly the same price.

It uses RK3568 Quad-Core A55 CPU, most likely not as powerful but have the option for more RAM.

**Comment by UMU618** [comment]
Yes, you are right. I just need more RAM. RK3568 is weaker.
https://gadgetversus.com/processor/amlogic-s922x-h-vs-rockchip-rk3568/

**Comment by JFLim1** [comment]
> @JFLim1 Have you tried running Manjaro-ARM on GT King Pro?
> https://wiki.manjaro.org/index.php/Amlogic_TV_boxes

Hi @UMU618 
Yes. Using Manjaro-Arm-Gnome for GT King Pro by @spikerguy (Manjaro Team) using linux-khadas kernel 5.16.17-1.  It uses bootscrpt method to boot (i.e. does NOT require u-boot.ext).  It is stable and you have the flexibility to boot up on any of the USB 3.0 Port.  Great firmware and good support from Manjaro Arm Team.

With linux-khadas-5.16.y kernel so far on USB Drive it does NOT Shutdown cleanly (Power LED Still On after Shutdown/Power Off from Menu).  Need to power cycle to Reboot/Restart.

**Comment by UMU618** [comment]
@JFLim1 Thanks a million. In the last few days, I've considered buying a GT King Pro or a RPi400. And I bought a RPi400 yesterday. But I would advise my colleagues to buy a GT King Pro. uh-huh!

**Comment by JFLim1** [comment]
> In the last few days, I've considered buying a GT King Pro or a RPi400. And I bought a RPi400 yesterday. But I would advise my colleagues to buy a GT King Pro. uh-huh!

Oops. Sorry did not respond to you earlier.  I did not notice your message earlier.

Rasberry Pi 400 had much better software support as far I know.  You will have a wide range of Linux distro to choose from including Rasberry Pi OS.

**Comment by ophub** [comment]
目前在5.10/5.15/5.16/5.17内核里我测试鼠标都可以正常使用了。

**Comment by JFLim1** [comment]
> At present, in the 5.10/5.15/5.16/5.17 kernel, the mouse can be used normally.

Confirmed.  I have tried all the these kernels and mouse pointer/cursor works.

**Comment by huapox** [comment]
> 没多少软件可用，我主要的诉求是跑rdp来远程Windows用，浏览器安装了Firefox，一般的网页没啥问题，视频不大行

已入hk1box装了O大的armbian， 我远程用这个， 跑在docker里, 支持rdp及noVNC, 带音频（core是fluxbox latest是xfce4）：

docker run -it --rm --shm-size 1g --net=host infrastlabs/docker-headless:core

noVnc 	http://192.168.0.x:10081 	pw: headless
