### ISSUE TITLE
分享咪咕 MG101(S905L) 成功刷入 eMMC

### ISSUE THREAD

**Issue by dz515704201** [ophub/amlogic-s9xxx-armbian#1912]
**Device Information | 设备信息**
 - SOC: [S095L]
 - Model [咪咕 MG101]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.140]
 - Release: [jammy]

**Describe the bug | 问题描述**
要从 U盘启动 首先线刷刷入 可以执行 adb shell reboot update 命令的 Android 包，[天翼云盘](https://cloud.189.cn/t/uaiyE3ZRBZZz （访问码：riu4）)。
刷机包有两个，有先后刷机顺序

使用 Armbian_24.2.0_amlogic_s905l_jammy_5.15.140*.img.gz ，使用的是meson-gxl-s905l-venz-v10.dtb 和默认的 u-boot 。HDMI 正常输出，有线网络正常。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
![Uploading 微信图片_20231203011213.jpg…]()

**Comment by dz515704201** [comment]
![Uploading 微信图片_20231203011143.jpg…]()
![Uploading 微信图片_20231203011155.jpg…]()
![Uploading 微信图片_20231203011202.jpg…]()
![Uploading 微信图片_20231203011213.jpg…]()

**Comment by dz515704201** [comment]
![微信图片_20231203011213](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62528724/4265e432-fc3d-4a87-9015-6a65f0c9daa8)
![微信图片_20231203011202](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62528724/f00c14cc-3731-48a4-ad08-d6149b961ff7)
![微信图片_20231203011155](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62528724/b89e054c-2644-476b-8acf-f8d737c3ff10)
![微信图片_20231203011143](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62528724/ca8ec8b5-b95b-454c-afd2-4a1e1a2ec308)
大佬，不好意思啊。我这是第一次提交

**Comment by ophub** [comment]
谢谢分享，这次的图片可以正常看到了。

**Comment by HeroPoter** [comment]
MG101可有4种型号啊，能拍个外观背面看看嘛

**Comment by rootber** [comment]
mg101短接点是哪个？

**Comment by thiesymon** [comment]
请问下该型号的短接点在哪呀

**Comment by thiesymon** [comment]
你好我的是mg101 S905L，我在 刷后刷的那个包时出现了错误(先刷的那个包已经成功）
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49362220/d9901a34-cb65-4aea-86f4-9fa3ca6e2efe)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49362220/108d513b-3859-4687-bdd1-1894aef4ad5b)
日志显示如图：
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/49362220/cc247362-9b41-4a8c-8369-062c6efe17b8)
请问下能看出来是什么问题吗

**Comment by dz515704201** [comment]
> 你好我的是mg101 S905L，我在 刷后刷的那个包时出现了错误（先刷的那个包已经成功） ![图像](https://private-user-images.githubusercontent.com/49362220/322379922-d9901a34-cb65-4aea-86f4-9fa3ca6e2efe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDk0NTMsIm5iZiI6MTcxNjEwOTE1MywicGF0aCI6Ii80OTM2MjIyMC8zMjIzNzk5MjItZDk5MDFhMzQtY2I2NS00YWVhLTg2ZjQtOWZhM2NhNmUyZWZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0MzE1MDU0MGI2N2E0ZjgwNjlkNTEyMjU3MDcxOWIyYzRjNjkzMjg0ZTExOWE0ZWFhNzNhMDk3NTkzOTdkODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6AJceC7mBJU1G66jDfQ19Z4yNdvGTQ2SpE4ZJOvhNuU) ![图像](https://private-user-images.githubusercontent.com/49362220/322378824-108d513b-3859-4687-bdd1-1894aef4ad5b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDk0NTMsIm5iZiI6MTcxNjEwOTE1MywicGF0aCI6Ii80OTM2MjIyMC8zMjIzNzg4MjQtMTA4ZDUxM2ItMzg1OS00Njg3LWJkZDEtMTg5NGFlZjRhZDViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4ZjBkODA4Njk5NTAzODc5OWZmNDllMTRmNmE0ZmM0Zjg0MDgzODliZDdiODYyODkyNGYxNzFhMmM1NTM3MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mEHY3oc2GTG3Z2e-JcTmSH89WDX_HFBVqkJ_9mwIP-4) 日志显示如图： ![image](https://private-user-images.githubusercontent.com/49362220/322379382-cc247362-9b41-4a8c-8369-062c6efe17b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMDk0NTMsIm5iZiI6MTcxNjEwOTE1MywicGF0aCI6Ii80OTM2MjIyMC8zMjIzNzkzODItY2MyNDczNjItOWI0MS00YThjLTgzNjktMDYyYzZlZmUxN2I4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDA4NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YmIyNzg1NmY3OTViMzI1MjVjNmFjYmJiMmI4MGM1ODI0YjllNmMxMjY2NDdmNDY5NTk2YmMzNTEzNDgzNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Ua096-LZeHPkqExWPjD3jGKwz4nHdfhhzdvihn_IsM) 请问下能看出来是什么问题吗

这个我还真没遇到，或者你到网上找找别的刷机包试试

**Comment by dz515704201** [comment]
> MG101可有4种型号啊，能拍个外观背面看看嘛

![IMG_20240519_170507](https://github.com/ophub/amlogic-s9xxx-armbian/assets/62528724/0c0d20ac-3096-4019-a2c7-d93752b76996)

**Comment by dz515704201** [comment]
> mg101短接点是哪个？

短接CPU的1，2脚，只需要一根缝衣针。包上一些防止短路

**Comment by dz515704201** [comment]
> 请问下该型号的短接点在哪呀

短接CPU的1，2脚，只需要一根缝衣针。包上一些防止短路

**Comment by my-sea** [comment]
@thiesymon 
我盒子的主板与你的一样，不用刷入第二个包。镜像使用Armbian_24.8.0_amlogic_s905l-mg101_jammy_6.6.46_server_2024.08.15.img.gz，配置使用默认。

第一个Android包刷入后，开启adb模式，然后从电脑连接执行 adb shell reboot update，盒子可以从U盘启动，并进入Armbian系统。

**Comment by walkmanyy** [comment]
adb shell reboot update是可以进入armbian系统了， 请问如何回到机顶盒电视系统呢
