### ISSUE TITLE
小宝NAS设备6.1系列内核无法正常开机启动

### ISSUE THREAD

**Issue by HaleyLou** [ophub/amlogic-s9xxx-armbian#1914]
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [xiaobao]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.64]
 - Release: [trixie/bullseye]

**Describe the bug | 问题描述**
小宝NAS设备前期为解决6系列内核无法启动SATA接口的问题，在内核中增加了补丁，但增加补丁之后的内核版本6.1.63版本起，小宝NAS均无法正常启动。相关反馈详见https://github.com/ophub/amlogic-s9xxx-armbian/issues/1827#issuecomment-1832056869
，还请大佬们排查修复

**Comment by yshtz** [comment]
<img width="537" alt="20231209_11_42_01" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/88421077/eff3ebcd-184c-4dce-8e4a-b55806dc7efe">
刷Armbian_24.2.0_rockchip_xiaobao_bullseye_6.1.65_server_2023.12.07，一样的，卡在在这

**Comment by yshtz** [comment]
> **Device Information | 设备信息**
> 
> * SOC: [RK3399]
> * Model [xiaobao]
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version: [6.1.64]
> * Release: [trixie/bullseye]
> 
> **Describe the bug | 问题描述** 小宝NAS设备前期为解决6系列内核无法启动SATA接口的问题，在内核中增加了补丁，但增加补丁之后的内核版本6.1.63版本起，小宝NAS均无法正常启动。相关反馈详见[#1827 (comment)](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1827#issuecomment-1832056869) ，还请大佬们排查修复

大佬，你那边有xiaobao可以使用的bullseye 固件吗(5.1内核)？有的话可以分享下吗？谢谢

**Comment by HaleyLou** [comment]
还是希望官方能解决6.1核心的问题。
5.10核心可以fork这个项目，自己改一点点地方就可以让github编译出来

**Comment by moehz** [comment]
解决了吗

**Comment by yshtz** [comment]
> 还是希望官方能解决6.1核心的问题。 5.10核心可以fork这个项目，自己改一点点地方就可以让github编译出来

fork了，选择5.10.1内核，编译出错，仓库里没有5.10.1的内核供下载，不知道怎么了修改。望大神指导。
<img width="634" alt="1233" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/88421077/a332fee3-8878-4a51-92d3-e47665a56302">

<img width="234" alt="20231218_22_02_39" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/88421077/d72acb22-29e2-4181-b731-1a9ebb9ccf63">

**Comment by HaleyLou** [comment]
> > 还是希望官方能解决6.1核心的问题。 5.10核心可以fork这个项目，自己改一点点地方就可以让github编译出来
> 
> fork了，选择5.10.1内核，编译出错，仓库里没有5.10.1的内核供下载，不知道怎么了修改。望大神指导。 <img alt="1233" width="634" src="https://private-user-images.githubusercontent.com/88421077/291306786-a332fee3-8878-4a51-92d3-e47665a56302.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTE1MDUsIm5iZiI6MTcwMjkxMTIwNSwicGF0aCI6Ii84ODQyMTA3Ny8yOTEzMDY3ODYtYTMzMmZlZTMtODg3OC00YTUxLTkyZDMtZTQ3NjY1YTU2MzAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0MDZmNjFlMDQ3ZWU0YjlkODMwZjdmZWQyYTQxMDgzN2MzMThlYzYwNDlmNTI0OWZiMDQyNDRkODEwMDBhNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.By-_Lp9f0TLEhjJJA_YJvdl3gKhU0Sf1R7N_MTUXF4I">
> 
> <img alt="20231218_22_02_39" width="234" src="https://private-user-images.githubusercontent.com/88421077/291306860-d72acb22-29e2-4181-b731-1a9ebb9ccf63.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTE1MDUsIm5iZiI6MTcwMjkxMTIwNSwicGF0aCI6Ii84ODQyMTA3Ny8yOTEzMDY4NjAtZDcyYWNiMjItMjllMi00MTgxLWI3MzEtMWE5ZWJiOWNjZjYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE0NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZlZTlhNDk2OWM5ZjMwNGNjMTllMmI4YWY5ODU5MGY5YTZlMzJkZmY2NTdhNjNlMWZiMDM4NGI0ZmM4YzVhMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-sPzuy2H0bRefVj-uxh0PFzRrzdXN1vAB20Zv19glJw">

1、编译界面可以勾上 auto use the lastest kernel
2、build-armbian.yml文件，修改里面ophub/amlogic-s9xxx-armbianophub/的文字，替换为你自己的库，比如我替换成HaleyLou/amlogic-s9xxx-armbian,保存；
3、修改build-armbian/armbian-files/common-files/etc/model_database.conf文件，找到xiaobao那一行,将后面:6.1.y的文字，修改为:stable，保存；
然后你在运行build ，祝你成功

**Comment by ophub** [comment]
楼上说的对

**Comment by HaleyLou** [comment]
> 楼上说的对

还是求维护下6.1.y核心的兼容问题吧，之前只是识别不到sata,现在直接无法启动设备了

**Comment by yshtz** [comment]
> 还是求维护下6.1.y核心的兼容问题吧

还是求维护下6.1.y核心的兼容问题吧

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2023.12/Armbian_24.2.0_rockchip_xiaobao_bookworm_6.1.68_server_2023.12.18.img.gz

下载这个试试，我本地取消了内核里的补丁编译了一个，试试是不是这个补丁的问题，反馈下是否可以正常启动。

**Comment by yshtz** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2023.12/Armbian_24.2.0_rockchip_xiaobao_bookworm_6.1.68_server_2023.12.18.img.gz
> 
> 下载这个试试，我本地取消了内核里的补丁编译了一个，试试是不是这个补丁的问题，反馈下是否可以正常启动。
> 
> 补丁现在也从f大的内核仓库去掉了。之后的内核可以再测试下。
问题依旧

<img width="470" alt="20231219_20_28_34" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/88421077/2a75df81-52e7-43b8-a6e1-d4055cda8af9">

**Comment by gzxief** [comment]
https://www.123pan.com/s/doe8Vv-INMw3.html
最新编译的，不要apt upgrade
Armbian_24.2.0_rockchip_xiaobao_trixie_6.1.69_server_2023.12.29.img.xz

**Comment by Mango1151** [comment]
> 还是希望官方能解决6.1核心的问题。 5.10核心可以fork这个项目，自己改一点点地方就可以让github编译出来

求一个5.1内核的固件

**Comment by Mango1151** [comment]
> > 还是求维护下6.1.y核心的兼容问题吧
> 
> 还是求维护下6.1.y核心的兼容问题吧

求一个5.1内核的固件

**Comment by gzxief** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/2009
看看这个，用自己本地编译出一个5.10的

**Comment by Mango1151** [comment]
![QQ图片20240113222400](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/5dfff703-b07b-4234-a670-d069ede21d3e)
大佬们编译到这里出错是什么原因

**Comment by Mango1151** [comment]
为什么我选择的5.10内核编译出来的不是5.10版本的？

**Comment by Mango1151** [comment]
![QQ图片20240115142220](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/e5cbc054-c3e2-45f9-bc9d-1aa6eda088a0)
如图，选择的5.10内核，编译出来的是最新的6.1.71

**Comment by Mango1151** [comment]
> > 为什么我选择的5.10内核编译出来的不是5.10版本的？
> > 修改这个文件，找到xiaobao  把后面的6.1.Y改为5.10
> > /root/amlogic-s9xxx-armbian/build-armbian/armbian-files/common-files/etc/model_database.conf
> > ![20240115154235](https://private-user-images.githubusercontent.com/82856050/296685541-130ef82a-82f4-439a-ace0-e2f61c67966e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NDEtMTMwZWY4MmEtODJmNC00MzlhLWFjZTAtZTJmNjFjNjc5NjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmE3ZTBmZjdkYzkyNDg3NDQzOWYzMGM0OGM2NDRlN2JjODU5ODFmYmRlYTlkYmJkNDQ5NjYwY2VjMmM2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RnN-L6FOnj_OdyrZAv9amwtSfJjh4qGqQBMzTaR9ZQ)
> > ![20240115154205](https://private-user-images.githubusercontent.com/82856050/296685564-e2e4198e-3838-4ace-b3a1-40bf4dc8239a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NjQtZTJlNDE5OGUtMzgzOC00YWNlLWIzYTEtNDBiZjRkYzgyMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTMxZjI0YTkxYzVjMDQyZDVlNDE0NmQ4ZGVmYTA0MTNiZDlkY2UwMTBhMjRlYTk1Yzc3ODI3NzY5NzVmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nuaHAPX4FfJ9YQWfqedDEGSJ-KXEpn8-54N6wv-XLZU)

这里改成5.10.y了，但是编译出来的还是5.1.71

**Comment by gzxief** [comment]
> > > 为什么我选择的5.10内核编译出来的不是5.10版本的？
> > > 修改这个文件，找到xiaobao  把后面的6.1.Y改为5.10
> > > /root/amlogic-s9xxx-armbian/build-armbian/armbian-files/common-files/etc/model_database.conf
> > > ![20240115154235](https://private-user-images.githubusercontent.com/82856050/296685541-130ef82a-82f4-439a-ace0-e2f61c67966e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NDEtMTMwZWY4MmEtODJmNC00MzlhLWFjZTAtZTJmNjFjNjc5NjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmE3ZTBmZjdkYzkyNDg3NDQzOWYzMGM0OGM2NDRlN2JjODU5ODFmYmRlYTlkYmJkNDQ5NjYwY2VjMmM2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RnN-L6FOnj_OdyrZAv9amwtSfJjh4qGqQBMzTaR9ZQ)
> > > ![20240115154205](https://private-user-images.githubusercontent.com/82856050/296685564-e2e4198e-3838-4ace-b3a1-40bf4dc8239a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NjQtZTJlNDE5OGUtMzgzOC00YWNlLWIzYTEtNDBiZjRkYzgyMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTMxZjI0YTkxYzVjMDQyZDVlNDE0NmQ4ZGVmYTA0MTNiZDlkY2UwMTBhMjRlYTk1Yzc3ODI3NzY5NzVmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nuaHAPX4FfJ9YQWfqedDEGSJ-KXEpn8-54N6wv-XLZU)
> 
> 这里改成5.10.y了，但是编译出来的还是5.1.71

编译文件里也要改，rebuild文件和recompile文件，增加5.10或把6.1改为5.10

**Comment by Mango1151** [comment]
> > > > 为什么我选择的5.10内核编译出来的不是5.10版本的？
> 
> > > > 修改这个文件，找到xiaobao  把后面的6.1.Y改为5.10
> 
> > > > /root/amlogic-s9xxx-armbian/build-armbian/armbian-files/common-files/etc/model_database.conf
> 
> > > > ![20240115154235](https://private-user-images.githubusercontent.com/82856050/296685541-130ef82a-82f4-439a-ace0-e2f61c67966e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NDEtMTMwZWY4MmEtODJmNC00MzlhLWFjZTAtZTJmNjFjNjc5NjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmE3ZTBmZjdkYzkyNDg3NDQzOWYzMGM0OGM2NDRlN2JjODU5ODFmYmRlYTlkYmJkNDQ5NjYwY2VjMmM2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RnN-L6FOnj_OdyrZAv9amwtSfJjh4qGqQBMzTaR9ZQ)
> 
> > > > ![20240115154205](https://private-user-images.githubusercontent.com/82856050/296685564-e2e4198e-3838-4ace-b3a1-40bf4dc8239a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NjQtZTJlNDE5OGUtMzgzOC00YWNlLWIzYTEtNDBiZjRkYzgyMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTMxZjI0YTkxYzVjMDQyZDVlNDE0NmQ4ZGVmYTA0MTNiZDlkY2UwMTBhMjRlYTk1Yzc3ODI3NzY5NzVmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nuaHAPX4FfJ9YQWfqedDEGSJ-KXEpn8-54N6wv-XLZU)
> 
> > 
> 
> > 这里改成5.10.y了，但是编译出来的还是5.1.71
> 
> 
> 
> 编译文件里也要改，rebuild文件和recompile文件，增加5.10或把6.1改为5.10

我把这两个里面的6.1.1都改成5.10.1了，编译出来的还是6.1.71

**Comment by Mango1151** [comment]
> > > > 为什么我选择的5.10内核编译出来的不是5.10版本的？
> > > > 修改这个文件，找到xiaobao  把后面的6.1.Y改为5.10
> > > > /root/amlogic-s9xxx-armbian/build-armbian/armbian-files/common-files/etc/model_database.conf
> > > > ![20240115154235](https://private-user-images.githubusercontent.com/82856050/296685541-130ef82a-82f4-439a-ace0-e2f61c67966e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NDEtMTMwZWY4MmEtODJmNC00MzlhLWFjZTAtZTJmNjFjNjc5NjZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhMmE3ZTBmZjdkYzkyNDg3NDQzOWYzMGM0OGM2NDRlN2JjODU5ODFmYmRlYTlkYmJkNDQ5NjYwY2VjMmM2ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7RnN-L6FOnj_OdyrZAv9amwtSfJjh4qGqQBMzTaR9ZQ)
> > > > ![20240115154205](https://private-user-images.githubusercontent.com/82856050/296685564-e2e4198e-3838-4ace-b3a1-40bf4dc8239a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMDUxNjgsIm5iZiI6MTcwNTMwNDg2OCwicGF0aCI6Ii84Mjg1NjA1MC8yOTY2ODU1NjQtZTJlNDE5OGUtMzgzOC00YWNlLWIzYTEtNDBiZjRkYzgyMzlhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE1VDA3NDc0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NTMxZjI0YTkxYzVjMDQyZDVlNDE0NmQ4ZGVmYTA0MTNiZDlkY2UwMTBhMjRlYTk1Yzc3ODI3NzY5NzVmMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nuaHAPX4FfJ9YQWfqedDEGSJ-KXEpn8-54N6wv-XLZU)
> > 
> > 
> > 这里改成5.10.y了，但是编译出来的还是5.1.71
> 
> 编译文件里也要改，rebuild文件和recompile文件，增加5.10或把6.1改为5.10

我吧6.1.和6.1.y的全部都改成5.10了，甚至把Auto use the latest kernel改成false了编译出来还是6.1.71.。。。。。。。。。。。。。。。。。

**Comment by gzxief** [comment]
我是在ubuntu22.04，命令行下编译，我可以编译出5.10的，修改三个文件，把6.1改为5.10，我的小宝nas今晚20点就卖了，赶着寄快递，就没测试5.10内核的，你再试试吧

**Comment by Mango1151** [comment]
> 我是在ubuntu22.04，命令行下编译，我可以编译出5.10的，修改三个文件，把6.1改为5.10，我的小宝nas今晚20点就卖了，赶着寄快递，就没测试5.10内核的，你再试试吧

我直接forkz这个项目在线编译的，无论怎么修改编译出来的就是6.1.71
