### ISSUE TITLE
机型B860AV3.2-M 芯片s905l3b  刷入多个固件只有2.75G运存，请适配，谢谢

### ISSUE THREAD

**Issue by dandzk** [ophub/amlogic-s9xxx-armbian#1915]
**Device Information | 设备信息**
 - SOC: [s905l3b]
 - Model [B860AV3.2-M]
 - Memory: 4G
 - Emmc: 32G
 - GPU: MALI450

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.140/6.1.64]
 - Release: [Bookworm/jammy/trixie/lunar/mantic]

**Describe the bug | 问题描述**
I test 6h，
刷入Bookworm/jammy/trixie/lunar/mantic的s905l3版和s905l3b版，近十个固件都可以使用armbian，但是有一些硬件适配的问题：
Kernel Version:5.15.140 Memory: 只有2.75G可用
Kernel Version:6.1.64 Memory: 只有2.87G可用
Hdmi: 无画面显示, 我只能通过IP连接它

请适配，谢谢
如有需要原版安卓固件，便于提取dtb：https://pan.baidu.com/s/1RGhco5NPkcWZlH7G9CdTAQ?pwd=qd7j
In the future, this device will become popular because of its large memory and EMMC, making it very suitable for Armbian. We hope you will take it seriously!

**Comment by dandzk** [comment]
我已提取出原版安卓的dtb文件，增加文件后修改uEnv.txt路径，依然无法进入armbian，卡开机第一屏，o大需要文件可以问我要，看看怎么适配和修改

**Comment by dandzk** [comment]
o大有空就看看咯，这个盒子的配置，比你库里90%的配置都高，还是挺有必要加入的，刚好这两天我可以积极配合测试，两天后，我出远门，这个盒子放在家挂着了，就用着2.87G内存算了，到时候你测试就难了

**Comment by ophub** [comment]
选择对了u-boot就可以正常识别，4g一般能识别3.7g。
测试哪个u-boot合适只能自己完成，根据model里相近的机器配置，更换u盘中的/boot/u-boot.ext，重启测试，直到找到合适的组合。

**Comment by dandzk** [comment]
> 我已提取出原版安卓的4G内存的dts文件，编译成dtb增加文件后修改uEnv.txt路径，依然无法进入armbian，卡开机第一屏，o大需要文件可以问我要，看看怎么适配和修改。。其实上述问题最想解决的是内存问题，其次是emmc的容量问题，其它没所谓

原版安卓解包后的所有文件下载https://www.123pan.com/s/9EJbVv-Jonj.html提取码:WKv6
此链接不能设置3天有效，只能设置7天有效，如果这两天没人回复，我删帖算了，以后自己适配好版本后自己发布GitHub算了。因为好的建议没人理睬（我看咪咕那个帖子跟我同一天发布，但ophub却回复，无法就是发帖的角度是分享了一个新机型的适配，那我这个帖子又何尝不是一种分享新机型呢？只是我发现了不完善的地方罢了）

**Comment by dandzk** [comment]
> 选择对了u-boot就可以正常识别，4g一般能识别3.7g。 测试哪个u-boot合适只能自己完成，根据model里相近的机器配置，更换u盘中的/boot/u-boot.ext，重启测试，直到找到合适的组合。

测试多个u-boot，均无法识别4G内存，估计还是得重新编译一个新的u-boot

**Comment by ophub** [comment]
自定义编译专用u-boot的方法在教材里有，看12.11

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

别人没这设备也搞不了，你根据教程自己编译替换测试，在USB里测试好了再写emmc。

**Comment by dandzk** [comment]
> 自定义编译专用u-boot的方法在教材里有，看12.11
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
> 
> 别人没这设备也搞不了，你根据教程自己编译替换测试，在USB里测试好了再写emmc。

好的，感谢指引

**Comment by dandzk** [comment]
> 自定义编译专用u-boot的方法在教材里有，看12.11
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
> 
> 别人没这设备也搞不了，你根据教程自己编译替换测试，在USB里测试好了再写emmc。

好的，感谢指引。。o大可以买一个玩玩，这个配置挺高的，虽然显卡不咋地，但胜在内存和emmc，非常适合armbian使用，且不贵，黄鱼80左右能买到，比曾经火的E900V22C更适合armbian

**Comment by w12563789** [comment]
兄弟，搞定了吗？这个盒子我也想搞个玩玩！

**Comment by w12563789** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

兄弟，搞定了吗？听了你说的 我也搞了一个这个盒子。

**Comment by w12563789** [comment]
> o大有空就看看咯，这个盒子的配置，比你库里90%的配置都高，还是挺有必要加入的，刚好这两天我可以积极配合测试，两天后，我出远门，这个盒子放在家挂着了，就用着2.87G内存算了，到时候你测试就难了

兄弟，搞定了吗？听了你说的 我也搞了一个这个盒子。

**Comment by yczxhcq1** [comment]
这个型号的soc有大佬刷好了吗？我刷了很多版本，都是hdmi无输出。

**Comment by dandzk** [comment]
> 这个型号的soc有大佬刷好了吗？我刷了很多版本，都是hdmi无输出。

你搞定识别4G内存问题没？

**Comment by Jawf** [comment]
想问下是用了哪个dtb文件配置到u-boot.txt？

> > 选择对了u-boot就可以正常识别，4g一般能识别3.7g。 测试哪个u-boot合适只能自己完成，根据model里相近的机器配置，更换u盘中的/boot/u-boot.ext，重启测试，直到找到合适的组合。
> 
> 测试多个u-boot，均无法识别4G内存，估计还是得重新编译一个新的u-boot。。另外把系统写入到emmc后是能识别全部容量的，现已更正。

**Comment by Jawf** [comment]
![IMG_20240119_124129](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/efd01301-f1b0-4af7-8a1d-f69d9ce03144)
我的也只能识别2.75G运存

**Comment by itlaohuo** [comment]
同样是2.75G+30G

**Comment by r81892489** [comment]
同型号，但是拆机芯片看了是905L3，测试了wormbook能启动都正常，但也是进armbian无hdmi输出。只能ssh链接，机器配置不同好像是2G+8G的版本

**Comment by mia0x75** [comment]
+1

**Comment by fudadds** [comment]
+1

**Comment by Amychan67899123** [comment]
你好，同型号盒子，同样问题。等待大佬解决吞了1G内存……
<img width="477" alt="_20240421234225" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/111632440/8b54fc6a-5195-43b7-bcd0-bdcf64cd5176">
![_20240421234240](https://github.com/ophub/amlogic-s9xxx-armbian/assets/111632440/fdcdb877-8462-4fc3-9de3-91bec626d324)

**Comment by ophub** [comment]
复制u-boot测试一下，看仓库的文挡

**Comment by sylvbin** [comment]
人家都是有利益关联的，现在哪有纯粹的爱好者或无私的分享者。

**Comment by lijsjust2** [comment]
关注中
