### ISSUE TITLE
使用armbian-software安装桌面环境无法启动

### ISSUE THREAD

**Issue by wangxue415** [ophub/amlogic-s9xxx-armbian#1917]
**Device Information | 设备信息**
 - SOC: S905w
 - Model  TX3-mini

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.139
 - Release: Armbian-unofficial 23.11.0-trunk Trixie

**Describe the bug | 问题描述**
使用armbian-software安装桌面环境后，无法登录桌面，留意到lightdm无法启动，不知道怎么解决

root@armbian:~# systemctl status lightdm
× lightdm.service - Light Display Manager
     Loaded: loaded (/lib/systemd/system/lightdm.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Sun 2023-12-03 20:08:34 CST; 2min 32s ago
   Duration: 174ms
       Docs: man:lightdm(1)
    Process: 1601 ExecStart=/usr/sbin/lightdm (code=exited, status=1/FAILURE)
   Main PID: 1601 (code=exited, status=1/FAILURE)
        CPU: 175ms

Dec 03 20:08:34 armbian systemd[1]: lightdm.service: Scheduled restart job, restart counter is at 5.
Dec 03 20:08:34 armbian systemd[1]: lightdm.service: Start request repeated too quickly.
Dec 03 20:08:34 armbian systemd[1]: lightdm.service: Failed with result 'exit-code'.
Dec 03 20:08:34 armbian systemd[1]: Failed to start lightdm.service - Light Display Manager.
Dec 03 20:08:34 armbian systemd[1]: lightdm.service: Triggering OnFailure= dependencies.

**Comment by ophub** [comment]
今天更换了桌面，armbian-sync拉取最新脚本
