### ISSUE TITLE
Wipe and Start Over?

### ISSUE THREAD

**Issue by loyukfai** [ophub/amlogic-s9xxx-armbian#1918]
I have a UNT403A which is already running armbian, I want to "reset" it, erase all user content, is there anyway to do it simply instead of flashing rooted Android and then armbian all over again?

Thanks a lot in advance.

**Comment by ophub** [comment]
Start the new armbian from the USB disk and write to emmc.

**Comment by loyukfai** [comment]
How to restart armbian from USB disk? 😅

**Comment by wnpllrzodiac** [comment]
some device has boot seq: tf->emmc
maybe usb disk cannot be as boot device

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents
