### ISSUE TITLE
希望增加E900V21E, 905L3-B的适配，倒腾了半个月。

### ISSUE THREAD

**Issue by rdgjiose** [ophub/amlogic-s9xxx-armbian#1921]
感觉U盘启动起作用了， 启动画面底部花屏，3秒后就过去了进入TV系统了， 感觉没有对应型号芯片的img，希望大佬增加适配。
![IMG_6042](https://github.com/ophub/amlogic-s9xxx-armbian/assets/133824897/cd6a126e-97b8-45c0-aa86-238aec2efede)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1514

从首页的设备列表，点对应的设备进去看曾经的贡献者们是怎么使用的，阅读之前的帖子。

**Comment by by-JohnChen** [comment]
50包邮解君愁

**Comment by ophub** [comment]
修改的方法在文档里
