### ISSUE TITLE
e900v22d写入emmc后，插好网线，网口灯不亮

### ISSUE THREAD

**Issue by Eric-168** [ophub/amlogic-s9xxx-armbian#1922]
相同的uboot和dtb，U盘引导就没问题，但是写入emmc后，插入网线灯不亮，插USB网卡SSH发现系统已经启动，就是自带网卡不行，emmc频率25、50、100、200都测试了

**Comment by Eric-168** [comment]
启动日志没有网卡相关报错

**Comment by Eric-168** [comment]
刷了安卓9底包还是一样

**Comment by by-JohnChen** [comment]
根据原厂的去改啊
