### ISSUE TITLE
能不能支持下T95Z MAX？谢谢

### ISSUE THREAD

**Issue by fxmirnet** [ophub/amlogic-s9xxx-armbian#1926]
可以用T95Z PLUS的镜像从U盘启动，但是不能写入到EMMC，配置应该和T95Z PLUS差不多 S912芯片 内存3G 存储32G

**Comment by ophub** [comment]
不能写入的现象是什么

**Comment by fxmirnet** [comment]
提示找不到分区

**Comment by fxmirnet** [comment]
[acs.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/13626935/acs.zip)
这是我提取出来的安卓的bootloader还有DTB文件，不知道怎么修改

**Comment by ophub** [comment]
nand无法识别，只能识别emmc
