### ISSUE TITLE
昨天发布的多个包sha码都对不上

### ISSUE THREAD

**Issue by dandzk** [ophub/amlogic-s9xxx-armbian#1928]
比如：Armbian_24.2.0_amlogic_s905l3b_bookworm_6.1.65_server_2023.12.06.img.gz

可以自行下载包和码验证，不知道是包的问题还是效验的问题。反正不敢用。
其实昨天发布后2个小时我就下载发现了，只是懒得多说

**Comment by ophub** [comment]
我下载比较了下也不一样，真是个有趣的发现。打包Actions在线，可以看看哪里出现了问题。每个releases里分5次打包完成，[build-armbian.yml](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/.github/workflows/build-armbian.yml)第一次打包因为空间不足，打包结束后启动了另外4次[use-releases-file-to-build.yml](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/.github/workflows/use-releases-file-to-build.yml)


sha256sum验证文件是在打包结束后一次生成的，然后上传releases。
https://github.com/ophub/amlogic-s9xxx-armbian/blob/e026958526b3ba93570e1fb31dfc7391213e54f8/action.yml#L155-L156

我猜可能是后面的4次打包和第一次生成的文件覆盖上传导致的？

欢迎大家fork仓库测试，第一次选择build-armbian全部打包，然后再使用use-releases-file-to-build把选项里的几个都打包一次，然后自行比较下文件的验证码是否也不一致。找找错误发生的原因。

**Comment by ophub** [comment]
感谢反馈，发现问题就要反馈，有疑问就要说出来。如果没人反馈，可能很多问题无法得到解决。如果不是你提醒，我可能还是习惯性地并发更新继续造成失败。以后我一个一个任务执行，一个tags更新完再启动下一个任务，避免同时对一个tags进行更新。

**Comment by dandzk** [comment]
> 感谢反馈，发现问题就要反馈，有疑问就要说出来。如果没人反馈，可能很多问题无法得到解决。如果不是你提醒，我可能还是习惯性地并发更新继续造成失败。以后我一个一个任务执行，一个tags更新完再启动下一个任务，避免同时对一个tags进行更新。

是的，你说得对。。我前几天反馈的中兴B860能不能帮忙看看内存怎么适配4G嘛，感激不尽

**Comment by dandzk** [comment]
> 内存需要u-boot匹配识别，有些设备的4G只能识别3.3G左右，类如Ugoos-AM6-Plus（s922x），CT2000（s922x）等。只有u-boot定制匹配的能识别到3.7G左右。
> 
> 教程里有u-boot编译的方法，可以自己根据教材编译试试。

好的，感谢指引
