### ISSUE TITLE
t95z更新和写入emmc出问题了

### ISSUE THREAD

**Issue by 392377870** [ophub/amlogic-s9xxx-armbian#193]
![IMG_20220322_181838](https://user-images.githubusercontent.com/23136114/159458804-78c50eb7-f319-4a99-984b-e256efd9eddf.jpg)

**Comment by ophub** [comment]
Ensure that your network can access github.com normally.

**Comment by 392377870** [comment]
> 更新时需要访问github.com下载内核。确保您的网络可以正常访问github.com。

写入emmc会出现No emmc can be found to install the openwrt system!

**Comment by ophub** [comment]
`lsblk`

**Comment by ophub** [comment]
刚看到你是t95，目前不支持这个设备，没有他的安装选项。

**Comment by 392377870** [comment]
> 刚看到你是t95，目前不支持这个，没有他的选项。 之前[NewbieOrange](https://github.com/NewbieOrange)分享了一个，没有dts，近期有多个用户反馈不能安装使用，我删除了。

话说dtb和dts文件能从安卓中提取不？

**Comment by ophub** [comment]
armbian用的是主线的，和安卓TV的dtb不同

**Comment by 392377870** [comment]
> 

谢谢解答，我这个t95z max盒子刷你的armbian网卡，蓝牙，无线都能驱动，就差写入emmc了

**Comment by ophub** [comment]
你是用的extlinux.conf吧，改一下安装脚本。默认的没处理这个配置文件

**Comment by 392377870** [comment]
大神有空能帮我看下这个是不是dts文件？我从安卓中提取的，有没有可能编译成dtb文件？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-armbian"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月27日(星期天) 晚上9:31
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-armbian] t95z更新和写入emmc出问题了 (Issue #193)





 
你是用的extlinux.conf吧，改一下安装脚本。默认的没处理这个配置文件

**Comment by ophub** [comment]
安卓和主线内核不一样，不能使用。
得要主线内核的dts源码，或者别人生成这个文件时，基于哪个文件进行修改的patch。

**Comment by 392377870** [comment]
> 安卓和主线内核不一样，不能使用。 得要主线内核的dts源码，或者别人生成这个文件时，基于哪个文件进行修改的patch。

coreelec里面有个dtb很完美，能适配到armbian中不？

**Comment by ophub** [comment]
coreelec是安卓，用不了
