### ISSUE TITLE
在config中添加配置，单编译成功后仍无对应模块

### ISSUE THREAD

**Issue by w12563789** [ophub/amlogic-s9xxx-armbian#1930]
Device Information | 设备信息

SOC: [S095L3a]
Model [CM311-1A]
Armbian Version | 系统版本

Kernel Version: [5.15.137]
Release: [ jammy]
Describe the bug | 问题描述
我在config-5.15中添加了如下配置

CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"

CONFIG_MEMFD=y

我的compile-kernel.yml代码如下：

name: Compile the kernel
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      kernel_source:
        description: "Select the kernel source"
        required: false
        default: "unifreq"
        type: choice
        options:
          - unifreq
      kernel_version:
        description: "Select kernel version"
        required: false
        default: "5.15.1"
        type: choice
        options:
          - 5.4.1_5.10.1
          - 5.15.1_6.1.1
          - 5.4.1
          - 5.10.1
          - 5.15.1
          - 6.1.1
      kernel_auto:
        description: "Auto use the latest kernel"
        required: false
        default: true
        type: boolean
      kernel_package:
        description: "Select compile package list"
        required: false
        default: "all"
        type: choice
        options:
          - all
          - dtbs
      kernel_toolchain:
        description: "Select the compilation toolchain"
        required: false
        default: "gcc"
        type: choice
        options:
          - clang
          - gcc
      kernel_sign:
        description: "Set the kernel custom signature"
        required: false
        default: "-loser"
        type: choice
        options:
          - -ophub
          - -loser

env:
  TZ: America/New_York
jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Initialization environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /etc/apt/sources.list.d /usr/local/lib/android 2>/dev/null
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://is.gd/depend_ubuntu2204_armbian)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone "${TZ}"
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Compile the kernel [ ${{ inputs.kernel_version }} ]
        uses: w12563789/amlogic-s9xxx-armbian@main
        if: ${{ steps.init.outputs.status }} == 'success' && !cancelled()
        with:
          build_target: kernel
          kernel_source: ${{ inputs.kernel_source }}
          kernel_version: ${{ inputs.kernel_version }}
          kernel_auto: ${{ inputs.kernel_auto }}
          kernel_package: ${{ inputs.kernel_package }}
          kernel_sign: ${{ inputs.kernel_sign }}
          kernel_toolchain: ${{ inputs.kernel_toolchain }}

      - name: Upload Kernel to Release
        uses: ncipollo/release-action@main
        if: ${{ env.PACKAGED_STATUS }} == 'success' && !cancelled()
        with:
          tag: kernel_stable
          artifacts: ${{ env.PACKAGED_OUTPUTPATH }}/*
          allowUpdates: true
          removeArtifacts: false
          replacesArtifacts: true
          token: ${{ secrets.GH_TOKEN }}
          body: |
            The kernel can be used to compile Armbian and OpenWrt.
            The kernel source code comes from: ${{ inputs.kernel_source }}
            The kernel compilation toolchain: ${{ inputs.kernel_toolchain }}

用git action编译后仍然没有binder和memfd的ko文件，通过find只显示出这些：
root@armbian:~# find / -name binder*
        /usr/include/c++/11/backward/binders.h
        /usr/include/linux/android/binder.h
        /usr/include/linux/android/binderfs.h
        /usr/src/linux-headers-5.15.141-loser/include/uapi/linux/android/binder.h
        /usr/src/linux-headers-5.15.141-loser/include/uapi/linux/android/binderfs.h
        /sys/kernel/debug/binder
        /sys/module/binder
        /sys/module/binder_alloc
root@armbian:~# find / -name memfd*
      /usr/include/linux/memfd.h
      /usr/src/linux-headers-5.15.141-loser/include/uapi/linux/memfd.h
      /usr/src/linux-headers-5.15.141-loser/include/linux/memfd.h

我通过这个帖子：https://github.com/ophub/amlogic-s9xxx-armbian/issues/1833
进行 make menuconfig 配置config，将得到的.config覆盖amlogic-s9xxx-armbian/compile-kernel/tools/config/config-5.15，然后本地编译和用git action编译都不行，仍然没有得到binder和memfd模块，为了能得到这两个模块，已经搞了一个月了，希望O大有空帮忙解惑一下，谢谢！

**Comment by w12563789** [comment]
> binder_linux.ko和ashmem_linux.ko是Android内核中的模块，用于实现Android系统中的进程间通信和共享内存功能。这些模块通常不包含在主线Linux内核中。如果你在主线内核里编译是无用的。如果是在安卓系的内核里，选择下面的选项：
> 
> ```
> CONFIG_ANDROID_BINDER_DEVICES=y
> CONFIG_ANDROID_BINDER_IPC=y
> ```
> 
> linux-rockchip是安卓系的，如果你是在rockchip盒子上使用，要选这个仓库的源码。

我不是rockchip盒子，我是普通的电视机顶盒cm311-1a，我的目的是想在盒子的docker中运行redroid，但是根据他们的官方文档，需要用到binder_linux和ashmem_linux（或memfd）这两个模块（这是他们的官方文档：https://github.com/remote-android/redroid-doc）。请问O大，还有其他的解决方案吗？

**Comment by w12563789** [comment]
> amlogic用不了linux-rockchip的内核

从 [Armbian](https://github.com/armbian/build) 和 [OpenWrt](https://github.com/openwrt/openwrt) 等仓库中获得：例如 [armbian/patch/kernel](https://github.com/armbian/build/tree/main/patch/kernel/archive) 和 [openwrt/rockchip/patches-6.1](https://github.com/openwrt/openwrt/tree/main/target/linux/rockchip/patches-6.1)，[lede/rockchip/patches-5.15](https://github.com/coolsnowwolf/lede/tree/master/target/linux/rockchip/patches-5.15) 等等，这些使用主线内核的仓库中的补丁一般可以直接使用。我在这个仓库中[Armbian](https://github.com/armbian/build) 找到关于支持redroid支持的commit记录 https://github.com/armbian/build/commit/be3a656ec088489ecc7daeca855baf05449dd0ca ，我可以把这个记录的地址后面添加.patch获取到补丁，然后把补丁放在common-kernel-patches中进行git action编译吗？

**Comment by ophub** [comment]
不建议放通用补丁目录，放专用目录 kernel/kernel-patch/beta
/linux-5.15.y 里，从5.4到6.1跨的有点大，一般来说不是哪个版本都能用

**Comment by rhwong** [comment]
请问成功跑起来redroid了吗？

**Comment by rhwong** [comment]
我也尝试了修改config后编译内核，生效后盒子直接起不来了
（卖家刷好的原armbian似乎不是这个仓库的，我太笨了，可能搞错了什么）
尝试救一下，但是新的armbian不知道为什么写入不了emmc了，只能u盘运行。
但是还是想挣扎一下redroid，XD

**Comment by w12563789** [comment]
> 我也尝试了修改config后编译内核，生效后盒子直接起不来了 （卖家刷好的原armbian似乎不是这个仓库的，我太笨了，可能搞错了什么） 尝试救一下，但是新的armbian不知道为什么写入不了emmc了，只能u盘运行。 但是还是想挣扎一下redroid，XD

redroid可以启动起来，但是运行安装的软件就不行了，查看了下运行内存，不运行redroid容器还有1.5G-1.6G左右，一运行redroid中的微信，运行内存就剩100M了，而且微信出现月亮界面后就闪退了，怀疑是运行内存不够。

**Comment by chouex** [comment]
> > 我也尝试了修改config后编译内核，生效后盒子直接起不来了 （卖家刷好的原armbian似乎不是这个仓库的，我太笨了，可能搞错了什么） 尝试救一下，但是新的armbian不知道为什么写入不了emmc了，只能u盘运行。 但是还是想挣扎一下redroid，XD
> 
> redroid可以启动起来，但是运行安装的软件就不行了，查看了下运行内存，不运行redroid容器还有1.5G-1.6G左右，一运行redroid中的微信，运行内存就剩100M了，而且微信出现月亮界面后就闪退了，怀疑是运行内存不够。

请问大大是如何编译binder_linux.ko和ashmem_linux.ko, 有编译步骤吗?

**Comment by xxlovex** [comment]
一开始的思路就错了，无需安装redroid提供的两个模块，直接开启armbian中的内核模块就行。按照这个帖子中我说的步骤执行就可以了！

**Comment by xxlovex** [comment]
swap我也没弄，一开始我觉得是内存不够，现在感觉也有可能是其他原因。比如gpu没成功驱动，导致软件全部靠cpu软解。cpu负载过高导致的闪退！

**Comment by chouex** [comment]
> 一开始的思路就错了，无需安装redroid提供的两个模块，直接开启armbian中的内核模块就行。按照这个帖子中我说的步骤执行就可以了！

我也是刚刚才发现修改config后编译的内核就直接可运行redroid，我还一直在找.ko文件...
