### ISSUE TITLE
DG3399设备 12月7/8日的Jammy Bookroom均无法启动

### ISSUE THREAD

**Issue by HoshinoDesu** [ophub/amlogic-s9xxx-armbian#1936]
**Device Information | 设备信息**
 - SOC: RK3399
 - Model DG-3399

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.65
 - Release: Armbian_24.2.0_rockchip_dg3399_bookworm_6.1.65_server_2023.12.06

**Describe the bug | 问题描述**
uboot界面输出显示Failed to load '/dtb/rockchip/overlay/rk3399-fixup.scr'
然后系统HDMI输出全黑

附上显示输出全黑之前的截图

![fa76663f68fcca299d6c961ceeac22b8](https://github.com/ophub/amlogic-s9xxx-armbian/assets/118837925/2a4d2f57-ab4d-437e-bdfb-675680a13110)

**Comment by linwei5d** [comment]
我也遇到一样的情况了，6.1.69会闪红灯，其它版本会启动不了，看了下网口灯没闪，可能系统都没启动成功
