### ISSUE TITLE
jp-tvbox 升级到 6.1.66内核后无法启动

### ISSUE THREAD

**Issue by iJayscn** [ophub/amlogic-s9xxx-armbian#1938]
**Device Information | 设备信息**
 - SOC: rk3566
 - Model jp-tvbox

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.66
 - Release:bookwarm

**Describe the bug | 问题描述**

内核 6.1.65 ，使用 armbian-update升级到最新内核后
无反应

重新插电源后，红色指示灯闪烁5秒后，灯灭

HDMI无输出

网络无反应

**Comment by ophub** [comment]
usb刷一个最新的armbian，从U盘启动，执行：`armbian-update -s`即可把USB上的内核恢复到emmc里，实现内核更新失败后的救援。

**Comment by iJayscn** [comment]
> usb刷一个最新的armbian，从U盘启动，执行：`armbian-update -s`即可把USB上的内核恢复到emmc里，实现内核更新失败后的救援。

试了 USB3.0 和USB 2.0的接口 都无法启动

**Comment by wnpllrzodiac** [comment]
试试 tf卡。
我测试下来 tf卡优先级高于内置emmc。usb不会作为boot设备

**Comment by iJayscn** [comment]
> 试试 tf卡。 我测试下来 tf卡优先级高于内置emmc。usb不会作为boot设备

荐片没有 TF 卡插口

**Comment by iJayscn** [comment]
无解，只能重刷！
