### ISSUE TITLE
CM211-1 MC022 刷入EMMC无法启动

### ISSUE THREAD

**Issue by islandsys** [ophub/amlogic-s9xxx-armbian#1940]
**Device Information | 设备信息**
 - SOC: [905L3B]
 - Model [CM211-1]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.64-6.1.66]
 - Release: [jammy]

**Describe the bug | 问题描述**
USB启动OK，写入EMMC后大概率无法启动，偶尔断电一段时间再开机可以启动，TTL查看错误是MMC问题，翻以前的issue，改了BLANK，重新编译换了内核，121-125均尝试过都无法启动，启动日志如下：

`Starting the controller
USB XHCI 1.00
scanning bus 0 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
** Bad device usb 0 **
** Bad device usb 1 **
** Bad device usb 2 **
** Bad device usb 3 **
reading emmc_autoscript
831 bytes read in 3 ms (270.5 KiB/s)
## Executing script at 01020000
reading u-boot.emmc
606670 bytes read in 21 ms (27.6 MiB/s)
## Starting application at 0x01000000 ...

U-Boot 2021.04-00056-g13ac02db31-dirty (Apr 28 2021 - 22:52:02 +0800) p212

Model: Amlogic Meson GXL (S905X) P212 Development Board
SoC:   Amlogic Meson Unknown (Unknown) Revision 2a:e (c5:2)
DRAM:  2 GiB
MMC:   mmc@70000: 0, mmc@72000: 1, mmc@74000: 2
Loading Environment from nowhere... OK
In:    serial
Out:   serial
Err:   serial
[BL31]: tee size: 0
[BL31]: tee size: 0
Net:   eth0: ethernet@c9410000
Hit any key to stop autoboot:  0
starting USB...
Bus usb@c9000000: dwc3_meson_gxl_get_phys: usb2 ports: 2
Register 2000140 NbrPorts 2
Starting the controller
USB XHCI 1.00
scanning bus usb@c9000000 for devices... 1 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found

Device 0: unknown device
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
switch to partitions #0, OK
mmc2(part 0) is current device
Scanning mmc 2:1...
Found U-Boot script /boot.scr
1025 bytes read in 0 ms
## Executing script at 08000000
Start AMLOGIC mainline U-boot
## Error: "bootfromsd" not defined
373 bytes read in 4 ms (90.8 KiB/s)
## Error: "eth_mac" not defined
ethaddr=76:87:f2:**:**:*e
mmc fail to send stop cmd
Error reading cluster
** Unable to read file /zImage **
Failed to load '/zImage'
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
SCRIPT FAILED: continuing...
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
Card did not respond to voltage select! : -110
libfdt fdt_check_header(): FDT_ERR_BADMAGIC
Card did not respond to voltage select! : -110
Scanning disk mmc@70000.blk...
Disk mmc@70000.blk not ready
Card did not respond to voltage select! : -110
Scanning disk mmc@72000.blk...
Disk mmc@72000.blk not ready
Scanning disk mmc@74000.blk...
** Can't read partition table on 2:0 **
Found 2 disks
No EFI system partition
BootOrder not defined
EFI boot manager: Cannot load any image
Card did not respond to voltage select! : -110
Speed: 100, full duplex
BOOTP broadcast 1
BOOTP broadcast 2
DHCP client bound to address 10.0.1.215 (252 ms)
*** ERROR: `serverip' not set
Cannot autoload with TFTPGET
missing environment variable: pxeuuid
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/01-76-87-f2-97-90-7e
Speed: 100, full duplex
*** ERROR: `serverip' not set
missing environment variable: bootfile
Retrieving file: pxelinux.cfg/0A0001D7
Speed: 100, full duplex`

**Comment by by-JohnChen** [comment]
dtb里面的的emmc 频率不对认不到emmc

**Comment by by-JohnChen** [comment]
> > dtb里面的的emmc 频率不对认不到emmc
> 
> 所以需要刷到安卓看下安卓系统dtb里边的emmc参数然后改到armbian里吗
you can do it
