### ISSUE TITLE
插入刷好系统的U盘adb shell reboot update重启之后没反应

### ISSUE THREAD

**Issue by thiesymon** [ophub/amlogic-s9xxx-armbian#1942]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model UNT402A

**Armbian Version | 系统版本**
 - Kernel Version: 6.16.66
 - Release:  jammy

402A的是Android 10，将6.16.66的包刷入U盘后插上远程使用adb shell reboot update能重启 之后没有反应hdmi没有输出，ssh ip 也没有主机 ，没有进入armbian系统安装。请问是该型号刷不了还是什么问题呀？（已经试过5.15的系统 换过U盘了）

**Comment by ophub** [comment]
首页点设备连接，点击之前的帖子进去，先刷贡献者分享的安卓系统。

**Comment by thiesymon** [comment]
> 首页点设备连接，点击之前的帖子进去，先刷贡献者分享的安卓系统。

谢谢O大！！！我成功了！！！！！！！阿里嘎多！！！！！！！！！！！！！！！！！！！！！
