### ISSUE TITLE
rk3588适配

### ISSUE THREAD

**Issue by liuzhe1947** [ophub/amlogic-s9xxx-armbian#1943]
Device Information | 设备信息
    SOC: rk3588
    Model:k20p-main-rk3588
**OpenWrt Version | armbian
    Kernel Version:5.10.160
    Release:jammy
Describe the bug | 问题描述
HI ophub
我有一个rk3588的主版麻烦给适配一下armbian系统在此感谢。
uboot,dtb,dts，
下载地址：
1.https://wwmh.lanzoul.com/iQH471hew1fg 密码:5rd8
2.https://github.com/liuzhe1947/Rk3588-Information
我使用了Beelink-IPC-R，替换了我反编译的dtb，现在系统可以启动，usb正常，网口正常。wifi芯片是rtl8821cs 异常，hdmi，异常。劳烦给适配一下谢谢您。

**Comment by ARC-MX** [comment]
Who can write a u-boot, to the kernel and then to armbian complete compilation tutorial ah, I am a fan, know a little compilation but not much, there is no related complete tutorial online, I now have an `ASUS` `Tinker Edge R` `rk3399pro` board want to do adaptation, But I just don't know the whole process. Or the brother can help adapt it? The official version is too old. The official u-boot and kernel source code is here:
https://github.com/TinkerEdgeR/debian-u-boot
https://github.com/TinkerEdgeR/debian-kernel
It contains the full board defconfig file and the device tree dts file

**Comment by liuzhe1947** [comment]
ophub大佬?可以帮帮忙吗?
