### ISSUE TITLE
Tvbox X3 Mini - finding short-circuit point - Amlogic S905x3

### ISSUE THREAD

**Issue by shenglong209** [ophub/amlogic-s9xxx-armbian#1949]
Hi friend,
Device Information
SOC: [s905x3]
Memory: 4G
Wifi: Cdtech - 208821G
eMMC model: KLMBG2JENB B041 32GB

Anyone can help to find the short-circuit point on this board.
My box unable to boot to USB or eMMC anymore due to install the incorrect image.

I need the short-circuit point to flash the Android system by Usb burning tool :(
Thanks 

![IMG_9594](https://github.com/ophub/amlogic-s9xxx-armbian/assets/12762395/7aedb625-4fd5-48e1-a87b-9e65776ce43e)
![IMG_9592](https://github.com/ophub/amlogic-s9xxx-armbian/assets/12762395/eff6d05d-ad48-423b-9408-891d2fe295ce)
![IMG_9595](https://github.com/ophub/amlogic-s9xxx-armbian/assets/12762395/df09a017-4d38-40ee-a248-b58c8d2dd1b0)

**Comment by w12563789** [comment]
没有那么麻烦，买个晨晶短接神器就行了。usb双公头+短接神器10块钱就搞定了。
