### ISSUE TITLE
x96 max+ s905x3 5.15 no network interface

### ISSUE THREAD

**Issue by psittaciform** [ophub/amlogic-s9xxx-armbian#195]
When booting up x96 max+ with s905x3 5.15 version, I get an error that the ethernet cannot be brought up. I tried 5.4 but that will not boot (see #194 )

from dmesg:

ethernet eth0: PHY [0.0:00] driver [Generic PHY] (irq=POLL)
ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
ethernet: Failed to reset the dma
ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
ethernet eth0: stmmac_open: Hw setup failed

Let me know what other information I can provide.

**Comment by ophub** [comment]
There are many different motherboards for x96max. The RTL8211F network card chip of X96 Max with V5.1 version has been replaced with IP1001M, which cannot be used without drivers.
1. Take a picture of the front and back of your motherboard, and take a clearer picture of the CPU and network card chip.
2. Provide the startup log.

**Comment by psittaciform** [comment]
![X96MaxPlusBack](https://user-images.githubusercontent.com/90155287/159743385-14b6ae92-781a-432b-ad5a-9f0d9d792b9d.jpg)
![X96MaxPlusFront](https://user-images.githubusercontent.com/90155287/159743386-1cb0654d-4494-4949-996f-744ca2f6cccb.jpg)
![X96MaxPlusNetwork](https://user-images.githubusercontent.com/90155287/159743390-876d5541-561f-49df-a124-6450cbbd37fa.jpg)
![X96MaxPlusSOC](https://user-images.githubusercontent.com/90155287/159743392-d624c6a0-cb9e-4c3a-8a46-188679bebdb5.jpg)

Here are the pictures, I'm not certain which chip is for the network but I took a picture of the chip closest to the network port.  Let me know if that is not the right one.

**Comment by psittaciform** [comment]
Here is the full output of dmesg
[dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8334637/dmesg.txt)

**Comment by ophub** [comment]
```
# try
vi /boot/uEnv.txt
meson-sm1-x96-air.dtb
```

**Comment by psittaciform** [comment]
@ophub meson-sm1-x96-air.dtb worked, thanks for your help!

**Comment by ophub** [comment]
ok

**Comment by dinhchinh82** [comment]
@psittaciform have you tried to boot your X96max + from eMMC yet? 

I have same device as your but only can boot from eMMC if using kernet 5.4. If I used kernel 5.10/5.15 from eMMC, the box is unable to boot (hang on the Logo screen).

**Comment by psittaciform** [comment]
@dinhchinh82 No, I have not tried it yet, but was planning on trying soon with the updated wifi code that just got added.  I will let you know what I find out.

**Comment by mat20099** [comment]
I have the same problem.. 
![IMG_20220724_204322](https://user-images.githubusercontent.com/96350082/180663345-2a005201-b534-48d2-95c8-311aa2fe17fb.jpg)
![IMG_20220724_184244](https://user-images.githubusercontent.com/96350082/180663360-4cc359e8-0ac9-448f-8ac5-6c4b07532ff4.jpg)
