### ISSUE TITLE
UNT403A安装是出现的错误[ ERROR ] Failed to delete partition [ 1 ]. Please try again.

### ISSUE THREAD

**Issue by chen7393** [ophub/amlogic-s9xxx-armbian#1950]
/ \   _ __ ___ | |    / ___|/ _ \ / _ \| ___|| |___ /  __ _
  / _ \ | '_ ` _ \| |____\___ \ (_) | | | |___ \| | |_ \ / _` |
 / ___ \| | | | | | |_____|__) \__, | |_| |___) | |___) | (_| |
/_/   \_\_| |_| |_|_|    |____/  /_/ \___/|____/|_|____/ \__,_|

Welcome to Armbian-unofficial 24.2.0-trunk Bullseye with Linux 5.15.141-ophub

System load:   2%               Up time:       5 min
Memory usage:  8% of 1.91G      IP:            192.168.101.103
CPU temp:      30°C            Usage of /:    3% of 58G
storage/:      52% of 252M
RX today:      84.6 KiB

Last login: Fri Dec 22 20:57:37 2023
root@armbian:~# armbian-install
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------------
ID    SOC        MODEL                               DTB
--------------------------------------------------------------------------------------
301   s905x2     X96-Max-4GB,Tx5-Max                 meson-g12a-x96-max.dtb
302   s905x2     X96-Max-2GB,A95X-F2                 meson-g12a-x96-max-rmii.dtb
303   s905x2     MECOOL-KM3-4G                       meson-g12a-sei510.dtb
304   s905l3a    E900V22C-D,CM311-1a-CH,IP112H       meson-g12a-s905l3a-e900v22c.dtb
305   s905l3a    CM311-1a-YST                        meson-g12a-s905l3a-cm311.dtb
306   s905l3a    M401A,UNT403A,B863AV3.2-M           meson-g12a-s905l3a-m401a.dtb
0     Other      Customize                           Enter-custom-dtb-name
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 305
[ INFO ] Input Box ID: [ 305 ]
[ INFO ] Model Name: [ CM311-1a-YST ]
[ INFO ] FDTFILE: [ meson-g12a-s905l3a-cm311.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-e900v22c.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root?
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.467091 s, 9.0 MB/s
[ INFO ] Delete the existing [ 1 ] partitions.
Error: Partition doesn't exist.
[ ERROR ] Failed to delete partition [ 1 ]. Please try again.

**Comment by chen7393** [comment]
有没有大佬帮忙解决一下~谢谢

**Comment by bzlzm** [comment]
同样是403A，S905L3A
uEnv.txt文件为 FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb
安装成功了，我这个机顶盒比较怪，原生系统插上U盘重启就直接用U盘引导了，并没有刷成第三方曲线救国式的刷机。

**Comment by chen7393** [comment]
> 同样是403A，S905L3A uEnv.txt文件为 FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb 安装成功了，我这个机顶盒比较怪，原生系统插上U盘重启就直接用U盘引导了，并没有刷成第三方曲线救国式的刷机。

唉，太难搞了 我的是unt413A 不是403，写错了，网上找遍方法都不行
