### ISSUE TITLE
e900v21e装armbian jammy写不了emmc

### ISSUE THREAD

**Issue by Beiguo001** [ophub/amlogic-s9xxx-armbian#1954]
主控是s905l2,u盘能引导但是写不了emmc
提示[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
dd: 读取 '/dev/mmcblk2' 时出错: 输入/输出错误
记录了0+0 的读入
记录了0+0 的写出
0字节已复制，0.0854716 s，0.0 kB/s
[ ERROR ] Using dd to backup [ /usr/lib/u-boot/mybox-bootloader.img ] failed.

**Comment by Beiguo001** [comment]
6.1内核不能写emmc,5.15可以

**Comment by ophub** [comment]
魔百和要降低dtb的频率使用，每个设备使用时间不同，体质有差异，没有固定的，根据文档的教程自己改频率。

包括5.15的，你使用默认的虽然写入了，但频率较高可能不稳定，或许会重启失败。不降频出问题的可能性较大。

**Comment by Beiguo001** [comment]
okok
