### ISSUE TITLE
Wifi Realtek RTL8189FTV not working

### ISSUE THREAD

**Issue by lnrddev** [ophub/amlogic-s9xxx-armbian#1955]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3] S905X2
 - Model [e.g. HK1] BTV Express 10 

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] 6.1.66 
 - Release: [e.g. jammy/bullseye] bookworm

**Describe the bug | 问题描述**

The Realtek RTL8189FTV wifi card is not detected during installation and does not work. The wired network card works normally.

DTB file: meson-g12a-sei510.dtb

Is this card not in the kernel?

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek

There is no such driver in the mainline kernel source code

**Comment by andarezta** [comment]
build manually,or u can try search gogle/yt fw x96max+ xkn 2gb version.its same wireless type
