### ISSUE TITLE
usb recognization failure

### ISSUE THREAD

**Issue by profawk** [ophub/amlogic-s9xxx-armbian#1956]
**Device Information | 设备信息**
 - SOC: S905X3
 - Model Vontar X3

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.66-ophub
 - Release: jammy

**Describe the bug | 问题描述**
I'm having trouble with a usb device,
I had a S905X with amolgic armbian up until a few weeks ago but it died so I bought this machine.
It's job was to control my 3d printer over usb-serial.
However, the new box does not see it over USB.
things I've tired:
`udevadm monitor` - does not see a connection or disconnection events.
`dmesg` - also empty
connecting other usb devices - works as expected - tested usb mass storage and camera
connecting the printer to another linux machine with the same cable, works.

Hope you could help me :)

**Comment by ophub** [comment]
Devices like USB external hard drives that do not require drivers can be used normally. Your 3D printer should require drivers. Please search for drivers that are compatible with Linux and can be used on Ubuntu/Debian.

**Comment by profawk** [comment]
the USB serial driver is CH341, it seems to be loaded from the dmesg on boot, but no udev kernel messge is seen. my other machine is debian and it works OOTB
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/drivers/usb/serial/ch341.c

**Comment by profawk** [comment]
weird thing is, if I connect another uart adapter with the same driver it does work

other adapter, vontar box:
```
[105729.142760] usb 1-1: new full-speed USB device number 5 using xhci-hcd
[105729.299564] usb 1-1: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.54
[105729.303260] usb 1-1: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[105729.310421] usb 1-1: Product: USB2.0-Serial
[105729.321421] ch341 1-1:1.0: ch341-uart converter detected
```

other PC, 3d printer:
```
[   41.252640] usb 1-4: new full-speed USB device number 5 using xhci_hcd
[   41.394329] usb 1-4: New USB device found, idVendor=1a86, idProduct=7523, bcdDevice= 2.64
[   41.394349] usb 1-4: New USB device strings: Mfr=0, Product=2, SerialNumber=0
[   41.394356] usb 1-4: Product: USB Serial
[   41.452364] usbcore: registered new interface driver ch341
[   41.452390] usbserial: USB Serial support registered for ch341-uart
[   41.452419] ch341 1-4:1.0: ch341-uart converter detected
```

any idea where I could look for answers?

**Comment by ophub** [comment]
You mentioned that you can use drivers normally when using Debian. In that case, you can try `Bookworm`, which is a Debian-based distribution. The one you tested before, Jammy, is based on Ubuntu.

**Comment by profawk** [comment]
I was able to bypass the issue with a usb splitter :)
