### ISSUE TITLE
有没有大佬知道怎么驱动条形屏幕

### ISSUE THREAD

**Issue by shom** [ophub/amlogic-s9xxx-armbian#1957]
斐讯N1，内核5.15.142-ophub
这里是屏幕信息，现在开机会闪烁一下就不显示了
https://www.waveshare.net/wiki/8.8inch_Side_Monitor#.E4.BA.A7.E5.93.81.E6.A6.82.E8.BF.B0 
xorg.conf里添加如下配置，日志提示(EE) modeset(0): failed to set mode: Invalid argument

Section "Monitor"
    Identifier     "HDMI-1"
#    Option         "DPMS"
#    Option      "Monitor-HDMI1" "HDMI-1"
    Modeline    "480x1920_59.439" 60.000362  480 510 540 570  1920 1926 1932 1938 +hsync +vsync
    Option      "PreferredMode" "480x1920_59.439"
EndSection

**Comment by shom** [comment]
@ophub 能不能应用这个补丁https://github.com/steev/linux/commit/bac4e2dc8d140b6425327f6ec2c23f739d67a18b

**Comment by ophub** [comment]
5.15.y的补丁放在这了： https://github.com/ophub/kernel/tree/main/kernel-patch/beta/linux-5.15.y

使用了这个补丁的内核在这里： https://github.com/ophub/kernel/releases/tag/kernel_beta

更新这个内核的方法： `armbian-update -u beta -k 5.15`

我启动了内核编译（ https://github.com/ophub/kernel/actions/runs/7243795604 ），下午2点能编完。等编译完了最新的5.15.143里使用了这个补丁。你反馈下使用情况，如果可以，就保留下来，以后的5.15都使用这个补丁。

**Comment by shom** [comment]
> 5.15.y的补丁放在这了： https://github.com/ophub/kernel/tree/main/kernel-patch/beta/linux-5.15.y
> 
> 使用了这个补丁的内核在这里： https://github.com/ophub/kernel/releases/tag/kernel_beta
> 
> 更新这个内核的方法： `armbian-update -u beta -k 5.15`
> 
> 我启动了内核编译（ https://github.com/ophub/kernel/actions/runs/7243795604 ），下午2点能编完。等编译完了最新的5.15.143里使用了这个补丁。你反馈下使用情况，如果可以，就保留下来，以后的5.15都使用这个补丁。

好的，谢谢o大大

**Comment by shom** [comment]
多谢o大，经过几天的摸索，终于成功了。内核补丁有效。
[
![微信图片_20231222123441](https://github.com/ophub/amlogic-s9xxx-armbian/assets/144610/912c3f93-80f9-4452-a4c7-0cb9d76f6ab2)
](url)

**Comment by ophub** [comment]
好的
