### ISSUE TITLE
申请添加支持RK3399Pro Tinker Edge R

### ISSUE THREAD

**Issue by ARC-MX** [ophub/amlogic-s9xxx-armbian#1958]
**Device Information | 设备信息**
 - SOC: RK3399pro
 - Model Tinker Edge R  https://tinker-board.asus.com/series/tinker-edge-r.html
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34829404/5da81979-849b-4059-8bd4-66da39bee8b8)

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [bullseye]

**Describe the bug | 问题描述**
我没找到对应的rk3399pro芯片的设备，Tinker Edge R这个板子是ASUS官方退出的包含NPU的板子，由于我的个人能力有限，编译完了u-boot，dtb，但是没搞懂`armbianEnv.txt`文件要怎么个性化编写，不知道那位大哥能帮忙适配一下
这个 板子的外设还是挺多的，市场保有量也还行，如果能添加必能做很多事情。

板子官网u-boot，和4.4的内核源码附上地址：
https://github.com/TinkerEdgeR/debian-u-boot
https://github.com/TinkerEdgeR/debian-kernel
里面有完整的设备树描述文件和板子U-boot配置文件

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

这个设备使用的dtb和u-boot名字是哪个？文件写在model里，新增一行写你的。相关文件的放置路径看12.15
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

**Comment by ARC-MX** [comment]
我这边从上述的源码中编译了dtb文件，但是一直编译失败错误提示是
编译log https://[pipelinesghubeus5.actions.githubusercontent.com/SRINFdx3m3UGLFKFO50gIlpjqrmLumQee9xd1uGIxEcNng1uJ9/_apis/pipelines/1/runs/7/signedlogcontent/2?urlExpires=2023-12-24T14%3A13%3A32.1280425Z&urlSigningMethod=HMACV1&urlSignature=Dn%2FlwJh8epjf%2BVVLb1duz8hCR1tm%2Bd2u4%2F%2BLoV6%2FhgU%3D](https://pipelinesghubeus5.actions.githubusercontent.com/SRINFdx3m3UGLFKFO50gIlpjqrmLumQee9xd1uGIxEcNng1uJ9/_apis/pipelines/1/runs/7/signedlogcontent/2?urlExpires=2023-12-24T14%3A13%3A32.1280425Z&urlSigningMethod=HMACV1&urlSignature=Dn%2FlwJh8epjf%2BVVLb1duz8hCR1tm%2Bd2u4%2F%2BLoV6%2FhgU%3D)

可以这个kernel_tag我全部设置成5.15.y，但是还是报错，不知道是咋回事

**Comment by ophub** [comment]
怎么改的，什么编译命令

**Comment by ARC-MX** [comment]
`r418    :TinkerEdgeR                        :rk3399   :rk3399-tinker-edge-r.dtb               :trust.bin                    :uboot.img                           :idbloader.bin                   :4GB-LPDDR4,16G-eMMC,TF,1Gb-Nic             :5.15.y        :rockchip    :rk3399       :armbianEnv.txt  :ARC-MX                                :tinker-edge-r       :yes  `
编译时候配置Build armbian   开发板选择的是tinker-edge-r，系统版本选择bullseye kernel版本5.15.y 之后的几个都是这么配置的

**Comment by ophub** [comment]
`sudo ./rebuild -b tinker-edge-r`

这样编译

**Comment by ARC-MX** [comment]
还是报错了
```
[ STEPS ] Start building Armbian...
(1.1) Start building Armbian [ tinker-edge-r - stable/6.1.69 ]. ./rebuild: line 1107: / 1024 / 1024: syntax error: operand expected (error token is "/ 1024 / 1024")
```

**Comment by ophub** [comment]
不是一个

**Comment by ARC-MX** [comment]
还是没太整明白，用armbian编译完成了，启动啥也没有
