### ISSUE TITLE
SSH connection on first boot

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#196]
Hello, i just want to ask, why on the first boot SSH connection is refusing to connect?

![image](https://user-images.githubusercontent.com/33513626/159699892-2eff1de9-57dd-4703-9ff7-3bd7944de265.png)

Is there any to make ssh is automatically up on first boot? Because i didnt have any keyboard at the moment

Device: Fiberhome HG680P
Image: Armbian_22.05.0_Aml_s905x_focal_5.4.186_2022.03.22.2302

Thank you

**Comment by ophub** [comment]
root
1234

**Comment by rapdodge** [comment]
> buy a keyboard Or log in via ssh from another computer on the LAN root 1234

but, i already try it, its refused... Maybe i will wait my keyboard arrive...

**Comment by ophub** [comment]
I have this device, all kernels can be used, try again

**Comment by rapdodge** [comment]
> I have this device, all kernels can be used, try again


https://user-images.githubusercontent.com/33513626/159722137-099abb47-8a6b-41f0-a394-5485ec7cfb64.mp4

Here the proof using 5.15, i don't know why... It's keeps looping...
