### ISSUE TITLE
panther x2 使用 unifreq/linux-5.10.y-rk35xx 仓库编译的kernel时 eth不工作

### ISSUE THREAD

**Issue by nerimoe** [ophub/amlogic-s9xxx-armbian#1960]
**Device Information | 设备信息**
 - SOC: rk3566
 - Model Panther X2

**Armbian Version | 系统版本**
 - Kernel Version: 5.10.160-rk35xx
 - Release: bookworm

**Describe the bug | 问题描述**

#1880 最后也有提到相同问题，wlan可用，eth不可用，目前eth挂了，连不进ssh，晚些再附log..

**Comment by wnpllrzodiac** [comment]
known issue.
@nerimoe 你编译出来的5.x内核有 mpp service吗？没有的话，还是和6.x没有本质的区别。

**Comment by wnpllrzodiac** [comment]
pantherx2好在可以用tf卡启动，然后把emmc的内核回退到老版本，恢复回来。

**Comment by nerimoe** [comment]
> known issue. @nerimoe 你编译出来的5.x内核有 mpp service吗？没有的话，还是和6.x没有本质的区别。

mpp的话内核编译好应该还要安装用户空间驱动吧

**Comment by nerimoe** [comment]
> known issue. @nerimoe 你编译出来的5.x内核有 mpp service吗？没有的话，还是和6.x没有本质的区别。

/dev里没有mpp， 但是eth今天突然就工作了，非常奇怪

**Comment by wnpllrzodiac** [comment]
> > known issue. @nerimoe 你编译出来的5.x内核有 mpp service吗？没有的话，还是和6.x没有本质的区别。
> 
> /dev里没有mpp， 但是eth今天突然就工作了，非常奇怪

你怎么摸黑操作的？

**Comment by wnpllrzodiac** [comment]
> > known issue. @nerimoe 你编译出来的5.x内核有 mpp service吗？没有的话，还是和6.x没有本质的区别。
> 
> mpp的话内核编译好应该还要安装用户空间驱动吧

你意思还要编译mpp的代码然后安装，才能看到/dev/mpp_service？
我的理解内核编译了，直接就能看到了。istoreos里面是系统启动就能看到的

**Comment by HelloTheAsia** [comment]
我今天也编译了黑豹的rk35xx内核的固件,刷完后网卡不工作.但我又尝试了jpbox的固件.直接刷入x2.惊喜的是mpp_service正常显示.可惜今天有事,明天试一下硬件解码是否可以<img width="857" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/0ca99765-1c43-4a1a-9279-0643a8ccfe1a">

**Comment by nerimoe** [comment]
> 我今天也编译了黑豹的rk35xx内核的固件,刷完后网卡不工作.但我又尝试了jpbox的固件.直接刷入x2.惊喜的是mpp_service正常显示.<img alt="image" width="857" src="https://private-user-images.githubusercontent.com/26612794/295966094-0ca99765-1c43-4a1a-9279-0643a8ccfe1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzQwNDgsIm5iZiI6MTcwNTA3Mzc0OCwicGF0aCI6Ii8yNjYxMjc5NC8yOTU5NjYwOTQtMGNhOTk3NjUtMWM0My00YTFhLTkyNzktMDY0M2E4Y2NmZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNWYzMGI1NjNjODNhYTg1ZWQ4NDJlYjk3MDkwM2NmZjI4YmY5YTQ2MDhlMTFhNjM2YzEyMmY1ODkzMTVmZTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RtovO6h22bDDNhcy0o5CBR2JaxK8ZpQ34dtWuju9Lp8"> 我对比了两个机器的dts发现,x2的mpp-srv是status = "disabled"的,而jpbox的是status = "okay"不知道是否有影响 <img alt="image" width="1227" src="https://private-user-images.githubusercontent.com/26612794/296107379-6c2311c0-a649-49d2-b249-ca38c96f0880.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzQwNDgsIm5iZiI6MTcwNTA3Mzc0OCwicGF0aCI6Ii8yNjYxMjc5NC8yOTYxMDczNzktNmMyMzExYzAtYTY0OS00OWQyLWIyNDktY2EzOGM5NmYwODgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE1MzU0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0Mjg3NDIwM2E5YWE1NTk3OGQ3NWMxNjA1MTEwMTYzNWE3NGU4YTk0NzI5ZTk3NzAzOTI2NWNjNTFkYmZkNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kzGcU4eIOSjB6T6mOu8kRfg0lptlIOZXmiDXr_GzmD4">

那应该就是dts的问题了吧（？
我回去把dts这里改成okay编译一次试试

**Comment by nerimoe** [comment]
不过网卡不工作还是没解

**Comment by HelloTheAsia** [comment]
> 不过网卡不工作还是没解

是的,我也修改了对应的dts并接上ttl查看日志.显示mmc,循环报错.
![log](https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/e663efdd-a808-4550-a278-31788e00c7d6)
我继续参考官方文档和jp的dts解决了这个问题.但是网卡依旧没有工作.ttl里可以看到/dev/mpp_service已经正常显示.我这里禁用了dwmmc@fe2b0000,并为dwmmc@fe2c0000添加了
<img width="965" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/b6ff7966-a3d2-4ec2-9a18-4305cec2dbd8">
