### ISSUE TITLE
unt413a [ ERROR ] Failed to delete partition [ 1 ]. Please try again.

### ISSUE THREAD

**Issue by chen7393** [ophub/amlogic-s9xxx-armbian#1963]
**Device Information | 设备信息**
 - SOC: [e.g. s905l3a]
 - Model [e.g. unt413a]

**Armbian Version | 系统版本**
 - Kernel Version: bullseye_5.15.141   bullseye_5.15.142  bullseye_6.1.66 jammy_6.1.66(都试过也不行)
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

每次安装都安装不了，跟着帖子做也不行换dtb，看到有帖子说南传板子不行，不知道是不是。我只有这个。想试试来着。还有救吗

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

【以下是安装过程（已经换过dtb）】
`Welcome to Armbian-unofficial 24.2.0-trunk Bullseye with Linux 5.15.141-ophub

System load:   2%               Up time:       5 min
Memory usage:  8% of 1.91G      IP:            192.168.101.103
CPU temp:      30°C            Usage of /:    3% of 58G
storage/:      52% of 252M
RX today:      84.6 KiB

Last login: Fri Dec 22 20:57:37 2023
root@armbian:~# armbian-install
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Using ampart tool: [ yes ]
[ INFO ] Show all lists: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------------
ID    SOC        MODEL                               DTB
--------------------------------------------------------------------------------------
301   s905x2     X96-Max-4GB,Tx5-Max                 meson-g12a-x96-max.dtb
302   s905x2     X96-Max-2GB,A95X-F2                 meson-g12a-x96-max-rmii.dtb
303   s905x2     MECOOL-KM3-4G                       meson-g12a-sei510.dtb
304   s905l3a    E900V22C-D,CM311-1a-CH,IP112H       meson-g12a-s905l3a-e900v22c.dtb
305   s905l3a    CM311-1a-YST                        meson-g12a-s905l3a-cm311.dtb
306   s905l3a    M401A,UNT403A,B863AV3.2-M           meson-g12a-s905l3a-m401a.dtb
0     Other      Customize                           Enter-custom-dtb-name
--------------------------------------------------------------------------------------
[ OPTIONS ] Please Input ID: 305
[ INFO ] Input Box ID: [ 305 ]
[ INFO ] Model Name: [ CM311-1a-YST ]
[ INFO ] FDTFILE: [ meson-g12a-s905l3a-cm311.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-e900v22c.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root?
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 0.467091 s, 9.0 MB/s
[ INFO ] Delete the existing [ 1 ] partitions.
Error: Partition doesn't exist.
[ ERROR ] Failed to delete partition [ 1 ]. Please try again.
`

**Comment by ophub** [comment]
试试降低dtb的频率，看文档里有方法
