### ISSUE TITLE
大佬麻烦问下，rk3399如何开启gpu/vpu硬件加速

### ISSUE THREAD

**Issue by YouDianWeiLing** [ophub/amlogic-s9xxx-armbian#1965]
大佬我浏览恩山时发现rk3399使用jellyfin可以开启硬件转码，但是需要开启gpu/vpu硬件加速，麻烦问下大佬知道怎么开启吗。
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8309161&highlight=rk3399

**Comment by cj1324** [comment]
参考这部分讨论：

https://github.com/unifreq/linux-6.1.y/issues/7

**Comment by YouDianWeiLing** [comment]
> 参考这部分讨论：
> 
> [unifreq/linux-6.1.y#7](https://github.com/unifreq/linux-6.1.y/issues/7)

感谢分享，我都找到个教程奈何是小白，https://www.cnblogs.com/zyly/p/17459196.html感觉这个挺详细的，等放假尝试下
