### ISSUE TITLE
b860av3.2-M s905l3  刷了很多版本的armbian都是HDMI无输出

### ISSUE THREAD

**Issue by yczxhcq1** [ophub/amlogic-s9xxx-armbian#1966]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 有别的大佬也是用这个盒子的吗？求指点一下

**Comment by rodren-lion** [comment]
目前 除了S905L3a  S905l2 和S905D 输出 其他的少 貌似没见有...

**Comment by Jawf** [comment]
我的也是中兴的zxv10 860AV3.2-M, 也碰到这个问题，u盘启动后黑屏。大神是否需要盒子，我可以寄

**Comment by Jawf** [comment]
[](url)
![IMG_20231227_093126](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/1fd617d0-e8aa-4ccc-a833-306c410793c7)
![IMG_20231231_151856](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/854e1c9a-b667-4dbc-bd3f-16300cb343e0)

**Comment by w12563789** [comment]
> ![IMG_20231227_093126](https://private-user-images.githubusercontent.com/85547/293495547-1fd617d0-e8aa-4ccc-a833-306c410793c7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODgzMzcsIm5iZiI6MTcwNDA4ODAzNywicGF0aCI6Ii84NTU0Ny8yOTM0OTU1NDctMWZkNjE3ZDAtZThhYS00Y2NjLWE4MzMtMzA2YzQxMDc5M2M3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA1NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2YzU4ZjY5NGMyZmRkYjVmOTZkMzdkM2RlM2UyNDQ3ZDI5ZDU3YjQ0MDMxYTk0ZDUwYTI2MGI3YjRmMGYyZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VGj5a_wMf-JyfOo5OgQfzEjbbZEQbFMvV1dRTOqOy0Q) ![IMG_20231231_151856](https://private-user-images.githubusercontent.com/85547/293495548-854e1c9a-b667-4dbc-bd3f-16300cb343e0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQwODgzMzcsIm5iZiI6MTcwNDA4ODAzNywicGF0aCI6Ii84NTU0Ny8yOTM0OTU1NDgtODU0ZTFjOWEtYjY2Ny00ZGJjLWJkM2YtMTYzMDBjYjM0M2UwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAxVDA1NDcxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0ZDIxMDI5Yzk5YmVlMjIwZGVjMjBlOGY5M2IwNTc0YTU3N2RmMWJiOTNkZDhhNWQ1OGFlMDhjMWMzZjBkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WRKbuDfefutkblBgffeh4PZKR6jvNXWlsHGVPhBgUJw)

hdmi会输出什么？一定要hdmi输出吗？这款盒子现在最主要的问题不是4G运行内存无法全部识别出来吗？

**Comment by Jawf** [comment]
andriod底包已经root，有hdmi输出，能当盒子看电视，但没法刷armbian

**Comment by xxlovex** [comment]
> andriod底包已经root，有hdmi输出，能当盒子看电视，但没法刷armbian

android底包的bootloader是锁着的吗？如果是解锁的，求一份，我想尝试编写下uboot，看看能否把4G内存全部读取出来。

**Comment by xxlovex** [comment]
> andriod底包已经root，有hdmi输出，能当盒子看电视，但没法刷armbian

这款盒子是可以刷armbian的，但是有些安卓底包执行 adb shell reboot update 时没有反应或报错，需要更换安卓底包

**Comment by itlaohuo** [comment]
> > andriod底包已经root，有hdmi输出，能当盒子看电视，但没法刷armbian
> 
> android底包的bootloader是锁着的吗？如果是解锁的，求一份，我想尝试编写下uboot，看看能否把4G内存全部读取出来。

我刚刚入了一个新的，无法从usb启动。我自己没刷机，老板说是已root了，应该是：新版河南中兴B860AV3.2-M（原机4+16G）S905L3(B)_原版官改超级UI线刷固件包【亲测】。bootloader很可能锁着的，怎么提取出来，我可以尝试提供。

**Comment by ophub** [comment]
怎么从usb启动，怎么提取都看文挡里有。

**Comment by itlaohuo** [comment]
从U盘启动问题，最终是安装了me-thomastv-rebootupdate-2-39557059-08859c7d54e544147bfef09e9c28f306.apk解决。（因为刷的安卓底包无法找到打开usb调试等入口）

**Comment by xxlovex** [comment]
> 从U盘启动问题，最终是安装了me-thomastv-rebootupdate-2-39557059-08859c7d54e544147bfef09e9c28f306.apk解决。（因为刷的安卓底包无法找到打开usb调试等入口）



> > > andriod底包已经root，有hdmi输出，能当盒子看电视，但没法刷armbian
> > 
> > 
> > android底包的bootloader是锁着的吗？如果是解锁的，求一份，我想尝试编写下uboot，看看能否把4G内存全部读取出来。
> 
> 我刚刚入了一个新的，无法从usb启动。我自己没刷机，老板说是已root了，应该是：新版河南中兴B860AV3.2-M（原机4+16G）S905L3(B)_原版官改超级UI线刷固件包【亲测】。bootloader很可能锁着的，怎么提取出来，我可以尝试提供。

那估计是锁着的，我刷的这个包，但是bootloader是锁着的

**Comment by mia0x75** [comment]
识别28.7G存储
```
Number of devices:  1
Devices:
   ID        SIZE  PATH
    1    28.70GiB  /dev/mmcblk2p2
```

内存只有2.7G，这个少了
```
# free -h
               total        used        free      shared  buff/cache   available
Mem:           2.7Gi       230Mi       2.4Gi       4.7Mi       174Mi       2.5Gi
Swap:          1.4Gi          0B       1.4Gi
```

root过的bootloader
@itlaohuo
[mybox-bootloader.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14885553/mybox-bootloader.zip)

**Comment by ophub** [comment]
内存少的，可以复制一下UBOUT重启试试

**Comment by mia0x75** [comment]
日志有这个错误：

```
Apr 13 16:32:40 HomeSvr kernel: meson-drm d0100000.vpu: Queued 2 outputs on vpu
Apr 13 16:32:40 HomeSvr kernel: meson-dw-hdmi c883a000.hdmi-tx: Unsupported HDMI controller (0d0d:0d:0d)
Apr 13 16:32:40 HomeSvr kernel: meson-drm d0100000.vpu: failed to bind c883a000.hdmi-tx (ops meson_dw_hdmi_ops): -19
Apr 13 16:32:40 HomeSvr kernel: meson-drm d0100000.vpu: Couldn't bind all components
Apr 13 16:32:40 HomeSvr kernel: meson-drm d0100000.vpu: adev bind failed: -19
Apr 13 16:32:40 HomeSvr kernel: meson8b-dwmac c9410000.ethernet: IRQ eth_wake_irq not found
```
