### ISSUE TITLE
Armbian镜像损坏

### ISSUE THREAD

**Issue by fuyijia-yi** [ophub/amlogic-s9xxx-armbian#1971]
![Snipaste_2023-12-29_23-12-18](https://github.com/ophub/amlogic-s9xxx-armbian/assets/142585822/a4d10dcc-f1a8-45a0-a62c-790d131242c4)
为什么我下载的Armbian镜像打开显示已损坏？
Armbian_24.2.0_amlogic_s905l3-cm211_bullseye_6.1.69_server_2023.12.23.img.gz

**Comment by fuyijia-yi** [comment]
@ophub 你能尽快解决这个问题吗？

**Comment by ophub** [comment]
看文档使用，你双击打开的操作不正确

**Comment by fuyijia-yi** [comment]
哦，谢谢。已解决。
