### ISSUE TITLE
关于安装“redroid”的内核报错

### ISSUE THREAD

**Issue by Yxini** [ophub/amlogic-s9xxx-armbian#1979]
Device Information | 设备信息
SOC: 魔百盒
Model: CM311-1 CH版本
Armbian Version | 系统版本：Armbian 23.11.0-trunk Bullseye,6.1.69 DEV内核

你好，O大！
我想根据安装[redroid](https://github.com/remote-android/redroid-doc)，但是在安装依赖的时候报错了。
然后我去看了issue的回答，有个回答您回复用DEV内核可以解决。
然后我就使用了DEV内核，但是发现依然报错。
各处寻求无果后，想问一下这种问题如何解决。
以下是我安装依赖报错的截图：
![1704181134408](https://github.com/ophub/amlogic-s9xxx-armbian/assets/47093205/ff54cfbb-01c0-4d53-8d8a-850bd06ea11d)

**Comment by ophub** [comment]
modules已经安装了：/usr/lib/modules 目录下

**Comment by Yxini** [comment]
好的，我看一下

**Comment by Yxini** [comment]
sudo find / -name "binder_linux.ko" -or -name "binder_linux.c"
我用find 命令还是没有找到binder_linux这个文件，在这个目录下也没有找到需要加载的内核模块。

**Comment by ophub** [comment]
在 `make menuconfig` 中，您可以通过以下步骤选择并编译这些驱动到内核中：

1. 打开终端并导航到内核源代码的根目录。
2. 运行 `make menuconfig` 命令以打开内核配置菜单。

在内核配置菜单中，您可以使用箭头键和回车键进行导航和选择。以下是选择并编译这些驱动的大致步骤：

3. 使用箭头键导航到 "Device Drivers"（设备驱动程序）选项，并按回车键进入子菜单。
4. 在 "Device Drivers" 子菜单中，使用箭头键导航到 "Staging drivers"（暂存驱动程序）选项，并按回车键进入子菜单。
5. 在 "Staging drivers" 子菜单中，使用箭头键导航到 "Binder and ashmem"（Binder 和 ashmem）选项，并按回车键进入子菜单。
6. 在 "Binder and ashmem" 子菜单中，您可以选择 "Binder"、"Hardware Binder" 和 "Virtual Binder" 选项，然后按空格键进行选择。选择后，相应的选项会被标记为 "M"（模块）或 "Y"（编译进内核）。
7. 完成选择后，按下 "Esc" 键退出当前子菜单。
8. 重复步骤 6 和步骤 7，以选择和配置其他相关的驱动选项。
9. 退出内核配置菜单，选择 "Exit"（退出）并保存您的配置更改。

生成包含你需要驱动的config文件，编译内核

**Comment by Yxini** [comment]
我的水平太低，理解起来太有难度。
我的理解是“克隆仓库到本地 git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-armbian.git”
然后在这个文件里面，使用以上步骤，然后进行编制。
但是我尝试后，发现不对，可能我还需要再学习学习。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel
看如何编译内核，kernel内置的驱动选项可以直接编译，把你新添加驱动的config放这里编译即可。

**Comment by Yxini** [comment]
好的，我看一下
