### ISSUE TITLE
Tanix-X4-Amlogic-S905X4-DDR-4GB-RAM-eMMC-32GB-ROM

### ISSUE THREAD

**Issue by MiAutomations** [ophub/amlogic-s9xxx-armbian#198]
I have the new Tanix-X4-Amlogic-S905X4-DDR-4GB-RAM-eMMC-32GB-ROM.
I’m trying to install the ARMBIAN for Amlogic S905 image Armbian_20.10_Arm-64_buster_current_5.9.0.img.xz for now, I try to use 2 DBT files meson-sm1-sei610.dtb and meson-sm1-sei610-ethfix.dtb, without success booting the box …

Is there any way to boot this box ? Or a new DBT file to test?

Thank you for your support and help in advance

**Comment by ophub** [comment]
Where did you download this system, the kernel version is a long time ago, you can go to his website to check how he uses it.

**Comment by MiAutomations** [comment]
> Where did you download this system, the kernel version is a long time ago, you can go to his website to check how he uses it.

I downloaded from the internet, and yes is old but I think that is working because this one is used in the tanix x3... 
Where I can check the new ones ? 

Thank you

**Comment by ophub** [comment]
I heard from people in the group that s905x4 can use the firmware of s905x3.

**Comment by MiAutomations** [comment]
> I heard from people in the group that s905x4 can use the firmware of s905x3.

Great news! Can you please point me this discussion once I'm searching for this information?

Thank you

**Comment by ophub** [comment]
dl.armbian.com

**Comment by JFLim1** [comment]
> but I don't see any related to the s95x3

If not mistaken Odroid C4 uses S905X3 SOC.

**Comment by JFLim1** [comment]
> but I don't see any related to the s95x3

If not mistaken Odroid C4 uses S905X3 SOC.

**Comment by MiAutomations** [comment]
I try this one Armbian_22.11.0_Aml_s905x3_bullseye_5.10.146_server_2022.10.04.img but no luck. 
The boot screen stay freeze after a small flash on a tanix logo ...
