### ISSUE TITLE
求一份B860AV3.2-M（4+16/32版本）盒子的bootloader.bin或者安卓固件包

### ISSUE THREAD

**Issue by xxlovex** [ophub/amlogic-s9xxx-armbian#1982]
Device Information | 设备信息

SOC: [s905l3b]
Model [B860AV3.2-M]
Memory: 4G
Emmc: 32G(盒子上写的是16G)
GPU: MALI450
根据O大文档：https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#1211-%E5%A6%82%E4%BD%95%E5%88%B6%E4%BD%9C-u-boot-%E6%96%87%E4%BB%B6
我本人刷的安卓固件包提取出来的bootloader.bin是锁着的。
![捕获](https://github.com/ophub/amlogic-s9xxx-armbian/assets/32612100/9edc476d-7a72-4a88-b871-cf89c2966e74)

所以求一份可以用的bootloader.bin或者安卓固件包。我准备重写一份u-boot，修复4G运行内存无法全部识别的问题。望有资源的朋友给一份。
ps：我目前刷的固件包名是这个：512-新版河南中兴B860AV3.2-M（原机4+16G）S905L3(B)_原版官改超级UI线刷固件包【亲测】

**Comment by Jawf** [comment]
同求，同款B860AV3.2-M（写的4+16G版），6Pro盒子， 内存只能识别3G+存储8G，看只有2个s905l3b 的启动dtb文件，都试过也不行

**Comment by itlaohuo** [comment]
> 同求，同款B860AV3.2-M（写的4+16G版），6Pro盒子， 内存只能识别3G+存储8G，看只有2个s905l3b 的启动dtb文件，都试过也不行，@大o

请问你刷的是哪个安卓底包？也是这个吗: 新版河南中兴B860AV3.2-M（原机4+16G）S905L3(B)_原版官改超级UI线刷固件包【亲测】

**Comment by Jawf** [comment]
> > 同求，同款B860AV3.2-M（写的4+16G版），6Pro盒子， 内存只能识别3G+存储8G，看只有2个s905l3b 的启动dtb文件，都试过也不行，@大o
> 
> 请问你刷的是哪个安卓底包？也是这个吗: 新版河南中兴B860AV3.2-M（原机4+16G）S905L3(B)_原版官改超级UI线刷固件包【亲测】。这个不支持从usb启动？

我的低包不清楚，买来已经刷好了，可以usb启动，我已经刷成armbian bullseys 5.15.145的系统了，现在问题是没有hdmi输出，ssh可以进系统，但是只能识别3+32g

**Comment by Jawf** [comment]
![IMG_20240119_124129](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/4053cba4-7242-4179-87af-d7e386246236)

**Comment by itlaohuo** [comment]
不能从U盘启，更换U盘重新启动然后再安装一个adb_update_reboot的apk就ok

**Comment by itlaohuo** [comment]
估计要重做启动盘了，安装软件失败：
![Uploading image.png…]()

**Comment by itlaohuo** [comment]
重装成功，识别了2.8G的内存（实际应该是4G）。仍然无hdmi输出，问题不大。
下一步考虑启用usb无线网卡。600M的双频（应该是rtl8811的）
root@armbian:~# free -m
               total        used        free      shared  buff/cache   available
Mem:            2814         204        1609           4        1000        2519
Swap:           1407           0        1407
root@armbian:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            1.3G     0  1.3G   0% /dev
tmpfs           282M  8.3M  274M   3% /run
/dev/mmcblk2p2   29G  2.2G   27G   8% /
tmpfs           1.4G     0  1.4G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           1.4G   24K  1.4G   1% /tmp
/dev/mmcblk2p1  252M  131M  121M  52% /boot
/dev/zram1       49M  1.6M   44M   4% /var/log
tmpfs           282M     0  282M   0% /run/user/0
root@armbian:~#

**Comment by xxlovex** [comment]
> 估计要重做启动盘了，安装软件失败：
> 
> root@armbian:~# apt install net-tools Reading package lists... Done Building dependency tree... Done Reading state information... Done The following NEW packages will be installed: net-tools 0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded. Need to get 248 kB of archives. After this operation, 982 kB of additional disk space will be used. Get:1 http://deb.debian.org/debian bullseye/main arm64 net-tools arm64 1.60+git20181103.0eebece-1 [248 kB] Fetched 248 kB in 12s (20.5 kB/s) Selecting previously unselected package net-tools. dpkg: warning: files list file for package 'linux-image-current-meson64' missing; assuming package has no files currently installed (Reading database ... 35445 files and directories currently installed.) Preparing to unpack .../net-tools_1.60+git20181103.0eebece-1_arm64.deb ... Unpacking net-tools (1.60+git20181103.0eebece-1) ... Setting up net-tools (1.60+git20181103.0eebece-1) ... Processing triggers for man-db (2.9.4-2) ... /usr/bin/mandb: can't chmod /var/cache/man/pl/CACHEDIR.TAG: Operation not permitted /usr/bin/mandb: can't remove /var/cache/man/pl/CACHEDIR.TAG: Permission denied /usr/bin/mandb: fopen /var/cache/man/pl/2199: Permission denied /usr/bin/mandb: can't chmod /var/cache/man/pl: Operation not permitted /usr/bin/mandb: can't chmod /var/cache/man/de/CACHEDIR.TAG: Operation not permitted /usr/bin/mandb: can't remove /var/cache/man/de/CACHEDIR.TAG: Permission denied /usr/bin/mandb: fopen /var/cache/man/de/2199: Permission denied /usr/bin/mandb: can't chmod /var/cache/man/de: Operation not permitted /usr/bin/mandb: can't chmod /var/cache/man/fr/CACHEDIR.TAG: Operation not permitted /usr/bin/mandb: can't remove /var/cache/man/fr/CACHEDIR.TAG: Permission denied /usr/bin/mandb: fopen /var/cache/man/fr/2199: Permission denied /usr/bin/mandb: can't chmod /var/cache/man/fr: Operation not permitted

好多软件都报错，但是并不影响使用

**Comment by itlaohuo** [comment]
> > 估计要重做启动盘了，安装软件失败：
> > root@armbian:~# apt install net-tools Reading package lists... Done Building dependency tree... Done Reading state information... Done The following NEW packages will be installed: net-tools 0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded. Need to get 248 kB of archives. After this operation, 982 kB of additional disk space will be used. Get:1 http://deb.debian.org/debian bullseye/main arm64 net-tools arm64 1.60+git20181103.0eebece-1 [248 kB] Fetched 248 kB in 12s (20.5 kB/s) Selecting previously unselected package net-tools. dpkg: warning: files list file for package 'linux-image-current-meson64' missing; assuming package has no files currently installed (Reading database ... 35445 files and directories currently installed.) Preparing to unpack .../net-tools_1.60+git20181103.0eebece-1_arm64.deb ... Unpacking net-tools (1.60+git20181103.0eebece-1) ... Setting up net-tools (1.60+git20181103.0eebece-1) ... Processing triggers for man-db (2.9.4-2) ... /usr/bin/mandb: can't chmod /var/cache/man/pl/CACHEDIR.TAG: Operation not permitted /usr/bin/mandb: can't remove /var/cache/man/pl/CACHEDIR.TAG: Permission denied /usr/bin/mandb: fopen /var/cache/man/pl/2199: Permission denied /usr/bin/mandb: can't chmod /var/cache/man/pl: Operation not permitted /usr/bin/mandb: can't chmod /var/cache/man/de/CACHEDIR.TAG: Operation not permitted /usr/bin/mandb: can't remove /var/cache/man/de/CACHEDIR.TAG: Permission denied /usr/bin/mandb: fopen /var/cache/man/de/2199: Permission denied /usr/bin/mandb: can't chmod /var/cache/man/de: Operation not permitted /usr/bin/mandb: can't chmod /var/cache/man/fr/CACHEDIR.TAG: Operation not permitted /usr/bin/mandb: can't remove /var/cache/man/fr/CACHEDIR.TAG: Permission denied /usr/bin/mandb: fopen /var/cache/man/fr/2199: Permission denied /usr/bin/mandb: can't chmod /var/cache/man/fr: Operation not permitted
> 
> 好多软件都报错，但是并不影响使用

安装软件失败肯定影响使用，这个是因为启动U盘插入过盒子，当时盒子是安卓环境下开机，权限被安卓修改了，所以固化到emmc时也有问题，重做启动盘安装问题就解决了。

**Comment by xuzhijvn** [comment]
> 不能从U盘启，更换U盘重新启动然后再安装一个adb_update_reboot的apk就ok

没懂你啥意思，adb_update_reboot是一个安装安装包？为啥我搜不到？

**Comment by xuzhijvn** [comment]
> 不能从U盘启，更换U盘重新启动然后再安装一个adb_update_reboot的apk就ok

没懂你啥意思，adb_update_reboot是一个安卓安装包？为啥我搜不到？

**Comment by xxlovex** [comment]
看来大家都没资源或解决办法！

**Comment by wyx1300379707** [comment]
等大佬修复，好了踢一下

**Comment by yy1319hua** [comment]
修好了吗

**Comment by anluwei** [comment]
目前刷了fn，现在不识别gpu，用不了硬解，hdmi无输出，哪位大神有解决办法
