### ISSUE TITLE
为什么无法使用docker，各种报错，，，，也无法写入额emmc

### ISSUE THREAD

**Issue by ZhengchaoCao** [ophub/amlogic-s9xxx-armbian#1984]
**Device Information | 设备信息**
 - SOC: [e.g. S095m]
 - Model [Q5]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.69]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**

无论重启docker，，，还是安装容器都报错！

docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.

**Comment by gzxief** [comment]
刷完6.1.69后，改清华源。apt update，记住不要apt upgrade，然后apt install docker.io

**Comment by gzxief** [comment]
jammy的源https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu-ports/  
bullseye的源 https://mirrors.tuna.tsinghua.edu.cn/help/debian/
