### ISSUE TITLE
麻烦问下，在线编译的话，怎样在dts文件下增加节点。

### ISSUE THREAD

**Issue by YouDianWeiLing** [ophub/amlogic-s9xxx-armbian#1986]
o大，最近看了rk3399开启视频硬件解码（https://www.cnblogs.com/zyly/p/17459196.html）

想开启试试jellyfin能否开启硬件
（这个使用友善带硬解的固件成功运行，我是tvi3315a，刷入这个固件后后点不亮
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8309161&highlight=rk3399）
我看完启视频硬件解码文件觉得就需要修改两点：

1：内核开启（我看默认是以模块方式）
![G9 7$BU4VM~8A1ZZE1L@UYB](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76544557/d3cf40cf-018f-4564-8f2c-6225aff7c121)
以我的理解应该是可以修改compile-kernel/tools/config对应的config修改

2：加增加dts节点，然后就完成内核开启
![EP9JRE1 ATD5UR_}40`APFC](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76544557/8b4df374-664e-4f6c-a287-bc8bd3a5b0e4)
没找到在线编译怎么哪增加dts节点

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.10.y-rk35xx/tree/main/arch/arm64/boot/dts/rockchip

dts源码在这，config自己修改配置即可生成。内核编译方法在仓库里有。

**Comment by YouDianWeiLing** [comment]
好的谢谢，我去试试

**Comment by moehz** [comment]
我之前也想过这个，不过3399的编解码是vpu处理的，光驱动gpu恐怕不够

**Comment by YouDianWeiLing** [comment]
> > 好的谢谢，我去试试
> 
> 搞定了吗？

没搞定，因为我发现tvi3315a dts里有我需要添加的代码，我就更改内核gpu驱动m为y，编译出来还是没用，gpu没工作没生效，就算生效了也像楼上老哥说的jellyfin也不能硬解的，是我理解错了以为装了gpu
驱动就行。

**Comment by YouDianWeiLing** [comment]
> 我之前也想过这个，不过3399的编解码是vpu处理的，光驱动gpu恐怕不够

麻烦问下你试过使用友善的4.19内核的debian rom吗？那个集成好驱动的，jellyfin直接可以硬解。我直接刷启动不了，不知道怎么移植使用啊
