### ISSUE TITLE
Kernel Panic TR99TV Box s905x2_2*16Gb

### ISSUE THREAD

**Issue by danilpetrovich** [ophub/amlogic-s9xxx-armbian#199]
When i try first boot 
**Armbian_22.05.0_Aml_s905x2_focal_5.15.30_2022.03.22.2227.img**
or 
**Armbian_22.05.0_Aml_s905x2_focal_5.4.186_2022.03.20.2202.img**
from sdcard or usb, system stuck.
![photo_2022-03-24_17-55-47](https://user-images.githubusercontent.com/11448507/159957768-c2e1d4c8-8986-4906-890c-14a1044e17cf.jpg)
I try almost all .dtb file.
Also 
**CoreELEC-Amlogic-ng.arm-19.5-Matrix_nightly_20220315-Generic.img**
runs good.

Cheers,
Daniel C.

**Comment by ophub** [comment]
What is a network card chip? Photograph

**Comment by ophub** [comment]
meson-g12a-x96-max-rmii.dtb
`vi /boot/uEnv.txt`

**Comment by danilpetrovich** [comment]
Yes, i try this .dtb
All the same kernel panic

**Comment by danilpetrovich** [comment]
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/meson-g12a-x96-max-rmii.dtb
APPEND=root=UUID=dab72905-cf57-4ed9-8231-ffe85562e121 rootfstype=btrfs rootflags=compress=zstd:6 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

**Comment by ophub** [comment]
meson-g12a-sei510.dtb
meson-g12a-u200.dtb

Try these 2 again, use the firmware of the `5.4` kernel of s905x2

**Comment by danilpetrovich** [comment]
Now the system won't boot at all.
Loading Android
Even meson-g12a-x96-max-rmii.dtb don`t boot

**Comment by ophub** [comment]
Then there's no way

**Comment by danilpetrovich** [comment]
Ok. Thanks.

Cheers,
Daniel C.
