### ISSUE TITLE
Kernel Panic - Error inserting "stdin" variable in TX3-Mini

### ISSUE THREAD

**Issue by Victorhtf** [ophub/amlogic-s9xxx-armbian#1991]
**Device Information | 设备信息**
 - SOC: S905w
 - Model : Tanix TX3 Mini

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: Armbian_24.2.0_amlogic_s905w_bullseye_6.1.69_server_2024.01.01

**Describe the bug | 问题描述**
First of all I'm a new doing this and following the documentation and some forums and I'm trying to avoid open this issue but I'm experiencing this issue for last week and I dont know if I'm doing the right process. 

I burned .img in a SDcard with balenaEtcher, then checked the uEnv to see if the dtb matches with my device. 

Well, after trying to boot I'm getting stuck in the following error: **'Error inserting "stdin" variable , errno=22 '**, followed by **'unable to select a mode'** and **'Waiting for PHY auto negotiation to complete'**, then I insert my Ethernet cable and get some 'serverip' not set. I was also experiencing **'missing environment variable bootfile'**, and then the login prompt never appear, it stops in 'Cannot autoload with TFTPGET'.

Well, now I'm stucked in this, I have read something about the kernel version, I also saw an simillar issue (#470) but honestly, I didnt understood too much about this. 
Here are some pictures about my issues.

![IMG_20240104_204912](https://github.com/ophub/amlogic-s9xxx-armbian/assets/126508458/12673dab-9297-48e4-bc7d-368cd5de585b)
![IMG_20240104_210915](https://github.com/ophub/amlogic-s9xxx-armbian/assets/126508458/8e1ffc90-b4ad-418d-bf8a-442464be3b21)

**Comment by Algozx** [comment]
Same here, cant boot with new versions.

**Comment by Victorhtf** [comment]
Guilherme, have your already installed another previously version? I'm not sure, but possibly its some incompatibility with some new TX3 hardware??  When did you bought your TX3 mini? I thought that if the CPU was the same it would work, but apparently there's something more to it.

**Comment by Algozx** [comment]
@Victorhtf So, I had managed to upload a very old version, but it couldn't be updated. I bought mine in 2020 if I'm not mistaken, so it's been a while. 

But I managed to solve the problem. 

I downloaded this version: Armbian_24.2.0_amlogic_s905w_jammy_5.15.145_server_2024.01.01.img and burn with balenaEtcher-Portable-1.18.11.

After that, I renamed the file inside the 'extlinux' folder, removing the .bak and leaving only conf. There was no need to modify the dtb.

I hope it works out for you, let me know.

**Comment by Victorhtf** [comment]
@Algozx Thanks for your tip. Unfortunatelly it doesnt worked for me . I have tried to boot with **jammy** version and with **bulllseye** (ubuntu and debian). Both of them I got an error that says Kernel panic.

I burn using a snapd version of balenaEtcher for Debian12 (probably the version of balenaEtcher doesnt make difference), and the only thing that I did after burn is rename 'extlinux.conf.back' to extlinux.conf, just that. Is that right? 

I recently bought my tx3 mini, then I opened and checked, the CPU really is S905w, I not sure why isn't working.

**Comment by Algozx** [comment]
@Victorhtf  Victor, mine booted up with version 5.15, not 6.1, maybe that's it? But I had a problem, when I asked it to install on the emmc, it lost the image on the hdmi. 

I'm not sure what's going on, but it doesn't seem to be reaaal compatible with our box. So far I haven't been able to generate another bootable pendrive or sd, only black screen ;(

**Comment by Victorhtf** [comment]
@Algozx Sorry, I didnt notice the version. Now I've tested with 5.15.145 and I'm getting the same error: Kernel panic.

I have tried with other images and got a black screen as well. I dont know even If there something happening after the black screen.

By the way I wish you lucky trying to recover your image...any changes I come here to update.
