### ISSUE TITLE
项目对我很有帮助，在介绍中，没有找到捐款链接，想尽绵薄之力，麻烦给个捐款渠道

### ISSUE THREAD

**Issue by LeeSSXX** [ophub/amlogic-s9xxx-armbian#1992]
**Describe the bug | 问题描述**
@ophub 

前段时间，录了关于ARM固件编译的课，大楖20多节，上架B站和抖音课堂了，

多少有一些用户购买，课程中也用到了大佬的项目，感觉帮助很大，所以想把收入的一部分拿出来，捐出去，表示对开源事业的热爱。

麻烦提供个支持宝，或者微信二维码都可以。

[抖音课堂](https://student-api.iyincaishijiao.com/t/i8oHW3xN/)
[B站链接](https://www.bilibili.com/cheese/play/ss9452)

**Comment by ophub** [comment]
自由使用，不用赞助。

**Comment by LeeSSXX** [comment]
先生大义
