### ISSUE TITLE
Alfawise H96 pro plus DDR3 (PLC Blue) cannot install - Error Reading mmc

### ISSUE THREAD

**Issue by shadowd47** [ophub/amlogic-s9xxx-armbian#1997]
**Device Information | 设备信息**
 - SOC : S912
 - Model : Alfawise H96 pro plus  DDR3 (PLC Blue)

**Armbian Version | 系统版本**
 - Release: Armbian_24.2.0_amlogic_s912_jammy_5.15.145_server_2024.01.01.img

**Describe the bug | 问题描述**
Hello,
I have installed on Armbian on H96 pro plus green PCB (DDR4) easily but on my other device (blue PCB (DDR3)) they doesn't work.

The système cannot Read Emmc but the lsblk return information about mmcblk2.

Maybe the same issue as [#1300](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1300) and [#1058](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1058) ? 
If so, could you help me/us to fix it ? 

I join screenshot of error
![IMG20240103193459](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1446857/c83ca73b-8065-4527-ad8d-979ac6a60210)

**Comment by shadowd47** [comment]
I up my message :-)
Anybody have an idea ? :-)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents#1216-how-to-resolve-the-issue-of-io-errors-while-writing-to-emmc

**Comment by shadowd47** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents#1216-how-to-resolve-the-issue-of-io-errors-while-writing-to-emmc

Thanks a lot ! I missing this part of documentation.

I decompile meson-gxm-octopus-planet.dtb, modify `max-frequency` of `mmc@70000,` `mmc@72000,` `mmc@74000` from `200000000` to `25000000` and it's works ! :-D
![IMG_20240113_235551](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1446857/1ddc9cee-ee76-4d96-8ca2-19c1dbdf1352)
