### ISSUE TITLE
关于腾达U2驱动编译的问题。求指导

### ISSUE THREAD

**Issue by Anywherexu** [ophub/amlogic-s9xxx-armbian#1998]
**Device Information | 设备信息**
 - SOC: [e.g. S905l3a
 - Model cm311-1a

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.142]
 - Release: [bullseye]

**Describe the bug | 问题描述**
在腾达官网下载的驱动。arm版。编译时提示错误。求指导，该如何解决一下。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
andyxu@Voron:~$ sudo dpkg -i AX300-WiFi-Adapter-Linux-Driver-arm.deb 
[sudo] andyxu 的密码：
正在选中未选择的软件包 ax300-wifi-adapter-linux-driver。
(正在读取数据库 ... 系统当前共安装有 45290 个文件和目录。)
准备解压 AX300-WiFi-Adapter-Linux-Driver-arm.deb  ...
Install aic8800 wifi driver!!!!!
正在解压 ax300-wifi-adapter-linux-driver (1.0.2) ...
正在设置 ax300-wifi-adapter-linux-driver (1.0.2) ...
udev done
device not exist
cp fw done
make -C /lib/modules/5.15.142-ophub/build M=/AIC8800/drivers/aic8800 ARCH=arm64 CROSS_COMPILE= modules
make[1]: 进入目录“/usr/src/linux-headers-5.15.142-ophub”
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /AIC8800/drivers/aic8800/aic_load_fw/aic_bluetooth_main.o
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[3]: *** [scripts/Makefile.build:289：/AIC8800/drivers/aic8800/aic_load_fw/aic_bluetooth_main.o] 错误 126
make[3]: *** 正在删除文件“/AIC8800/drivers/aic8800/aic_load_fw/aic_bluetooth_main.o”
make[2]: *** [scripts/Makefile.build:552：/AIC8800/drivers/aic8800/aic_load_fw] 错误 2
make[1]: *** [Makefile:1909：/AIC8800/drivers/aic8800] 错误 2
make[1]: 离开目录“/usr/src/linux-headers-5.15.142-ophub”
make: *** [Makefile:55：modules] 错误 2
make failed, install aic8800 wifi drvier failed
dpkg: 处理软件包 ax300-wifi-adapter-linux-driver (--install)时出错：
 已安装 ax300-wifi-adapter-linux-driver 软件包 post-installation 脚本 子进程返回错误状态 1
在处理时有错误发生：
 ax300-wifi-adapter-linux-driver

**Comment by ophub** [comment]
先更新成dev的内核，再试一下编译自定义驱动

armbian-update -v dev -k 5.15.146
