### ISSUE TITLE
Desktop environments

### ISSUE THREAD

**Issue by marohinmark** [ophub/amlogic-s9xxx-armbian#2]
Hi, I wanted to install armbian on my s905x3 tv box, but NetworkManager does not have wifi plugin. The only way to set up wifi is DE. How to build armbian for s905x3 with DE from this repo?

**Comment by marohinmark** [comment]
I need xfce4

**Comment by marohinmark** [comment]
Also did not find anything about DEs in forks of this repo.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/512a46e87c7149d812aa6fab01a54205d87c84fe/.github/workflows/build-armbian.yml#L70

What is needed to build a personalized armbian is to add.

**Comment by marohinmark** [comment]
Seems like I need to add BUILD_DESKTOP=yes, right?

**Comment by ophub** [comment]
https://docs.armbian.com/Developer-Guide_Build-Preparation/

The armbian official website has very detailed personalized customization tutorials, and you can customize the build according to your needs.

**Comment by pulpoff** [comment]
XFCE works fine, added it from apt repo

**Comment by huapox** [comment]
try this with docker:

`docker run -it --rm --shm-size 1g --net=host infrastlabs/docker-headless`

noVnc 	http://192.168.0.x:10081 	pw:headless

**Comment by ophub** [comment]
@huapox 这是你开发的docker应用吗？在armbian的jammy和bullseye里都可以使用吧？

**Comment by huapox** [comment]
> @huapox 这是你开发的docker应用吗？在armbian的jammy和bullseye里都可以使用吧？

可以的，自己试了bullseye

**Comment by ophub** [comment]
```
docker  run -it --rm -p 10081:10081 -p 10089:10089 \
  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
  --cap-add SYS_BOOT --cap-add SYS_ADMIN \
  -v /sys/fs/cgroup:/sys/fs/cgroup \
  infrastlabs/docker-headless:latest
```

@huapox 那我把你的这个加到armbian-software里吧，你的有网站主页吗？我在介绍里链接过去。

https://github.com/infrastlabs/docker-headless
这是对应的github仓库吗？

**Comment by huapox** [comment]
@ophub 好呀~ 感谢， 没有网站 就github吧。

```bash
# supvervisor启动: core, latest, sogou (--privileged: 如rdp远程挂盘)
docker  run -it --rm -p 10081:10081 -p 10089:10089 --shm-size 1g \
  infrastlabs/docker-headless:latest

# systemd启动: gnome, plas  (当前gnome只能在systemd下跑)
docker  run -it --rm -p 10081:10081 -p 10089:10089 --shm-size 1g \
  --tmpfs /run --tmpfs /run/lock --tmpfs /tmp \
  --cap-add SYS_BOOT --cap-add SYS_ADMIN \
  -v /sys/fs/cgroup:/sys/fs/cgroup \
  infrastlabs/docker-headless:gnome
```

注：sogou arm64版暂未支持

**Comment by ophub** [comment]
![Snip20221010_1](https://user-images.githubusercontent.com/68696949/194821070-c35e8552-3d52-4660-b28c-b0d01a546b4d.png)

网络浏览器默认不能使用？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/d8967b6e8b0bea5462229d547ed65773e6ffe5b4

我添加到软件中心了，这是挺有创意的项目。
