### ISSUE TITLE
支持 armbian bullseye 吗？

### ISSUE THREAD

**Issue by whiler** [ophub/amlogic-s9xxx-armbian#20]
armbian/build 支持 bullseye 有一段时间了，这个项目有支持 bullseye 的计划吗？

**Comment by ophub** [comment]
fork and change:

https://github.com/ophub/amlogic-s9xxx-armbian/blob/850e2fdcde4d16022723aebf77d3147cbf1b3164/.github/workflows/build-armbian.yml#L69


`RELEASE= bullseye`

RELEASE ( stretch | buster | bullseye | bionic | focal | hirsute ): set OS release manually to skip dialog prompt; use this option with KERNEL_ONLY=yes to create board support package

https://docs.armbian.com/Developer-Guide_Build-Options/
