### ISSUE TITLE
Kernel panic

### ISSUE THREAD

**Issue by 4tomson** [ophub/amlogic-s9xxx-armbian#2000]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [X96Max+ 2101]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.69]
 - Release: [bookworm]

Constant kernel panic. Every 8 hours. Reinstalled from scratch, got the same thing immediately after installation and first launch

**Comment by 4tomson** [comment]
![1703879023458](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75882358/4bd552ac-d09f-4c00-be4a-be31bc6b6f7d)
![2023-12-29 22-40-08](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75882358/b967085c-678d-4952-aad5-ced708268f07)
![2024-01-07 18-25-48](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75882358/3f7684a5-ff8a-4c57-b061-a0457de800f8)

**Comment by ophub** [comment]
Change the test of other kernel versions

**Comment by 4tomson** [comment]
Cannot boot another kernel. 5.15 doesn't boot from flash.
It's i change kennel in armbian-config, box doesn't boot

**Comment by Victorhtf** [comment]
I'm also facing this issue, but with TX3 s905w...I tried v5 and v6, doesnt working here

**Comment by Victorhtf** [comment]
@4tomson did you make any progress?

**Comment by 4tomson** [comment]
No.... Reboot every ~10 hours....

**Comment by 4tomson** [comment]
How can i collect needed logs?
