### ISSUE TITLE
O大您好，如果想定制armbian镜像的话，应该如何操作

### ISSUE THREAD

**Issue by faint32** [ophub/amlogic-s9xxx-armbian#2001]
O大您好，我想定制armbian镜像，比如把指定的A程序提前写入到arm镜像中，应该如何操作？
rk3328的镜像我操作成功了，用armbian-build里的armbian-build/userpatches/customize-image.sh修改脚本，可以实现。
但是s905l3a如何实现，请您抽空指点一下，谢谢O大！

**Comment by ophub** [comment]
方法一样的，你这样添加即可

**Comment by faint32** [comment]
谢谢O大！
