### ISSUE TITLE
UNT400G hdmi没有显示信号输出

### ISSUE THREAD

**Issue by hzjnet** [ophub/amlogic-s9xxx-armbian#2003]
**Device Information | 设备信息**
 - SOC:  S905l3
 - Model :UNT400G

**Armbian Version | 系统版本**
 - Kernel Version: Linux 5.15.145-ophub
 - Release: bookworm/jammy/bullseye三个版本

**Describe the bug | 问题描述**
三个版本hdmi都没有显示信号输出，而相同版本下盒子换成MG301有显示信号输出。

请教如何处理才有hdmi显示信号输出，谢谢！

**Comment by ophub** [comment]
目前有部分魔百和没有hdmi输出
