### ISSUE TITLE
Armbian not work on GT-King

### ISSUE THREAD

**Issue by T-Shilov** [ophub/amlogic-s9xxx-armbian#2004]
**Beelink**
 - SOC: **S922X**
 - Model: GT-King

**Armbian Version:  Armbian_24.2.0_amlogic_s922x_bookworm_6.1.69_server_2024.01.01.img.gz**
 - Kernel Version: **6.1.6**
 - Release: **bookworm**

**Describe the bug**
Hello friends,
Thank you all for the great work  done on adaptation Armbian to many devices! :-)

I have a Manjaro ARM (aarch64) running on Gt-KIng. Manjaro works fine, but I need an Armbian.
I have followed the instructions for installing Arabian on Gt-king:
**Installation and Upgrade Instructions for Armbian**
https://github.com/ophub/amlogic-s9xxx-armbian#installation-and-upgrade-instructions-for-armbian

All actions were performed without errors until the very end.
Then I performed a power off, removed the SD card, and turned on the  box.

However, instead of downloading Armbian, I got a lot of errors 
(sorry for the poor quality of the pictures).
May be did I do something wrong?
Please help a beginner install Armbian on Gt-King.

![Gt-King-1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/61428202/ce9ca27c-8a7b-4e44-b027-6c5471087997) ![Gt-King-2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/61428202/a1dc5c1e-4372-455a-ba01-4ed5c19a8fee)
![Gt-King-3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/61428202/4976610f-9f26-4cf0-9991-8ac4901dc59a)
![Gt-King-4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/61428202/acfacf3b-a458-4edd-b855-3af41436a3ef)
![Gt-King-5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/61428202/81bc42f0-4c6c-4ec4-8e95-7f280f122f46)

**Comment by b14ckw1d0w** [comment]
Why don't you take this to the correct place? I won't help you find it though, you're a piece of work and really need to stop speaking to the people who develop these apps for free in the way you do. You don't deserve anything, you are not special. Like you have been told before, take your problems to the Manjaro ARM forum!

**Comment by T-Shilov** [comment]
I didn't understand you. It's not about Manjaro (it works). 
The problem is with Armbian, which refuses to work. 
Why should I contact the Manjaro forum? This has nothing to do with Armbian.
My issue is the place I need.
