### ISSUE TITLE
12.16 如何解决写入 eMMC 时 I/O 错误的问题 文档的新增步骤

### ISSUE THREAD

**Issue by fangweilong** [ophub/amlogic-s9xxx-armbian#2007]
Device Information | 设备信息
 - SOC: S095l3a
 - Model：E900V22D

Armbian Version | 系统版本
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

Describe the bug | 问题描述
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

使用armbian-install命令时产生报错信息：Faild to partiton internal eMMC using [parted]
我在iss中找到解决办法是根据12.16的做法降低频率到“0x2faf080”，仍一直无法成功写入eMMC。
后在其他iss中找到一个帖子，让尝试输出一些信息，看到频率还是"200000000"。（翻了一下iss列表没找到，如果可以的话希望在文章中也加入输出环境的语句，方便新手对照）
我尝试了一下发现输出信息为“200000000”。但是我很确定是使用了mv覆盖了原文件，考虑是不是缓存没加载的问题。
在文档中找到了加载+重启命令：
~~~shell
# 重启测试
sync
reboot
~~~
再次进入，armbian-install一次成功。

建议可以在12.13部分添加同步+重启命令，使文档更清晰
~~~ shell
# 安装依赖
sudo apt-get update
sudo apt-get install -y device-tree-compiler

# 1. 反编译命令（使用 dtb 文件生成 dts 源码）
dtc -I dtb -O dts -o xxx.dts xxx.dtb

# 2. 编译命令（使用 dts 编译生成 dtb 文件）
dtc -I dts -O dtb -o xxx.dtb xxx.dts
~~~
修改为
~~~ shell
# 安装依赖
sudo apt-get update
sudo apt-get install -y device-tree-compiler

# 1. 反编译命令（使用 dtb 文件生成 dts 源码）
dtc -I dtb -O dts -o xxx.dts xxx.dtb

# 2. 编译命令（使用 dts 编译生成 dtb 文件）
dtc -I dts -O dtb -o xxx.dtb xxx.dts

# 3.同步
sync

# 4.重启
reboot
~~~

**Comment by ophub** [comment]
说的对，我更新下
