### ISSUE TITLE
电信e900v21e s905l3b 怎么能启动到emmc

### ISSUE THREAD

**Issue by caoyuanwai** [ophub/amlogic-s9xxx-armbian#2008]
**Device Information | 设备信息**
 - SOC: [s905l3b]
 - Model e900v21e]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
我先刷了安卓9之后按照#1514 的方法进行安装，里面说 “可以修改 U盘 里的 u-boot-p212.bin 或 u-boot-s905x-s912.bin 来改变引导启动”，但是好像每次启动都是U盘里面的，能否给个详细一点的教程，谢谢

我的安装步骤：
把extlinux.conf.bak 复制并重命名extlinux.conf
复制一份 /boot/u-boot-s905x-s912.bin 文件，重命名为 /boot/u-boot.ext
把#1514提供的[meson-gxl-s905l3b-e900v21e.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/11905648/meson-gxl-s905l3b-e900v21e.dtb.zip) 解压复制替换原来的dtb
以下是安装过程图
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76550331/ce849aa8-d7ed-4b79-985a-08895e757c28)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76550331/f5f0d809-930d-47a7-8b48-e83ac866aeec)

以下是设置信息图
![IMG_20240110_230409](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76550331/2c00730b-fac0-4d78-9325-84993d87eb36)
![IMG20240110225225](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76550331/4398bc80-66ac-4f8a-99ad-a199f3048760)
![IMG_20240110_230325](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76550331/15a6621d-39a9-4cd8-9bb7-138ced9eb40e)
![IMG_20240110_230240](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76550331/59a38679-bc14-4e1f-a4bc-d82e6cdbf2bd)

**Comment by ophub** [comment]
你使用的是5.15内核，什么也不用改直接使用即可

**Comment by jimoyinzi** [comment]
刷入EMMC？不可能，绝对不可能！
修改版的dtb，没原版好用，概率性启动不了，要多次插拔电源。我这台机器是这样。

**Comment by caoyuanwai** [comment]
> 你使用的是5.15内核，什么也不用改直接使用即可

好的，谢谢

**Comment by caoyuanwai** [comment]
> 刷入EMMC？可以刷，但是启动不了。 修改版的dtb，没原版好用，概率性启动不了，要多次插拔电源。我这台机器是这样。

明白了，我说怎么有时候没有启动，

**Comment by caoyuanwai** [comment]
> 刷入EMMC？可以刷，但是启动不了。 修改版的dtb，没原版好用，概率性启动不了，要多次插拔电源。我这台机器是这样。

还有一个问题，我apt安装软件和docker安装容器时，下载速度还可以就是最后处理特别慢，是这台机器的性能就这样吗还是和U盘有关

**Comment by ophub** [comment]
u盘换个读写速度快的。emmc比U盘快

**Comment by caoyuanwai** [comment]
> u盘换个读写速度快的。emmc比U盘快

如果不能从emmc启动的话，那还有必要执行armbian-install吗。

**Comment by ophub** [comment]
不写入emmc不用执行这个写入操作
