### ISSUE TITLE
求助，编译指定内核心的问题

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#2009]
求助，git本地编译，指定内核心的问题.  /rebuild -b XXXX -k 5.10.180   这里的XXXX是一个RK3399的设备，在编译时想指定5.10的内核，自动变成6.1.71，代码里按照格式，增加5.10.1或删除6.1.1，编译打包还是一样变成6.1.71，求大神们指点一下，谢谢

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf


配置文件里指定了只能使用6.1.y内核，你如果确定你用的内核源码可以支持你的设备，就改对应board的kernel_tag
