### ISSUE TITLE
Could you support the fixed size of the eMMC partition using armbian-install command?

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#201]
At current, after installing to eMMC, all the remaining space of eMMC is allocated.

For example, the total partition size of USB is only 2748MB, the data size is 1200 MB. After installing to eMMC, the total partition size is around 28GB (for X96 max+ 4+32), the data size is still 1200MB.

By the way, is there a way to keep the total size of eMMC still 2748MB after installing 'armbian-install' then user can expand it to any bigger size such as 6500MB?

The objective of this idea is to make the snapshot of eMMC more quickly using armbian-ddbr after installing some 3rd apps to eMMC then clone to other similar boxes. Taking or restoring snapshot of small size like 6500MB is much more faster than 28GB.

Thank you.

**Comment by ophub** [comment]
If the user has a good concept of partition usage, this kind of operation is possible, but if the default root partition is as large as the USB, it will soon be impossible to update the system and the software package. In particular, some software such as docker will be installed to the root system by default. If you need multiple partitions, you can change the installation script. The code can be copied in the OpenWrt [installation](https://github.com/ophub/luci-app-amlogic/blob/main/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic) script.
