### ISSUE TITLE
ZXV10 B860AV3.2-M使用armbian-software命令报错

### ISSUE THREAD

**Issue by chiqianjiqi** [ophub/amlogic-s9xxx-armbian#2010]
Device Information | 设备信息

    SOC: S095l3
    Model：ZXV10 B860AV3.2-M

Armbian Version | 系统版本

    Kernel Version: 5.15.145
    Release: bullseye

Describe the bug | 问题描述

通过U盘启动Armbian_24.2.0_amlogic_s905l3_bullseye_5.15.145_server_2024.01.01.img镜像，使用armbian-software命令，报错

[ STEPS ] Start installing the necessary dependencies...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudoers is owned by uid 1023, should be 0
sudo: no valid sudoers sources found, quitting
sudo: error initializing audit plugin sudoers_audit
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudoers is owned by uid 1023, should be 0
sudo: no valid sudoers sources found, quitting
sudo: error initializing audit plugin sudoers_audit
[ ERROR ] Dependency installation failed, stop install.

**Comment by ophub** [comment]
不要把armbian的u盘插入安卓系统，断电后再插u盘，接电启动。
插入安卓会被改了系统权限。
重新刷写u盘的系统，这个废了，系统权限乱了。

**Comment by gsjz20** [comment]
> 设备信息 |设备信息
> 
> ```
> SOC: S095l3
> Model：ZXV10 B860AV3.2-M
> ```
> 
> Armbian 版本 |系统版本
> 
> ```
> Kernel Version: 5.15.145
> Release: bullseye
> ```
> 
> 描述错误 |问题描述
> 
> 通过U盘启动Armbian_24.2.0_amlogic_s905l3_bullseye_5.15.145_server_2024.01.01.img镜像，使用armbian-software命令，报错
> 
> [ 步骤 ]开始安装必要的依赖项... sudo： /etc/sudo.conf 归 uid 1023 所有，应为 0 sudo： /etc/sudo.conf 归 uid 1023 所有，应为 0 sudo： /etc/sudoers 归 uid 1023 所有， 应为 0 sudo： 未找到有效的 sudoers 源， 退出 sudo： 初始化审计插件时出错 sudoers_audit sudo： /etc/sudo.conf 归 uid 1023 所有， 应为 0 sudo： /etc/sudo.conf 归 uid 1023 所有，应为 0 sudo： /etc/sudoers 归 uid 1023 所有，应为 0 sudo：未找到有效的 sudoers 源，退出 sudo：初始化审核插件时出错 sudoers_audit [ ERROR ] 依赖安装失败，停止安装。

我也是这样 不知道怎么解决
