### ISSUE TITLE
Add support for Minix u9h Amlogic S912 box

### ISSUE THREAD

**Issue by dmist** [ophub/amlogic-s9xxx-armbian#2011]
**Device Information | 设备信息**
 - SOC: S912
 - Model: Minix Neo U9-H

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.71
 - Release: jammy

**Describe the bug | 问题描述**
The Minix Neo U9-H box is not part for the database file, at such it is difficult to properly use the tools for installation (in particular u-boot).
If it was part of it, many things could work/install easily.

Notes:
- DTB file: meson-gxm-minix-neo-u9h.dtb
- U-Boot: (I don't know what works for this model, u-boot-s905x-s912.bin ?)

**Comment by ophub** [comment]
You can test it by copying the u-boot to a USB drive, restarting, and running the test. If it boots up successfully after the addition, then it is the correct u-boot.
