### ISSUE TITLE
ZXV10 B860AV3.2-M写入EMMC正常

### ISSUE THREAD

**Issue by chiqianjiqi** [ophub/amlogic-s9xxx-armbian#2012]
Device Information | 设备信息

    SOC: S905L3
    Model: ZXV10 B860AV3.2-M 

    Kernel Version: 5.15.145
    Release: bullseye

Describe the bug | 问题描述

使用镜像Armbian_24.2.0_amlogic_s905l3_bullseye_5.15.145_server_2024.01.01.img，U盘启动正常，HDMI没有输出，通过SSH连接，执行armbian-install命令，dtb选择121号CM211-1,M411A的dtb，meson-gxl-s905l3b-m302a.dtb，文件系统选择EXT4。写入emmc后正常启动，HDMI还是没有输出，其他功能正常。

![64ebbae94716bcf8faff2b1a2da53b6](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22270173/051b0d46-b873-4a45-a351-77f0ea4a60a9)

![d8f53020f265cb9c6f5702b22209851](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22270173/5bba2ec9-2e58-4865-8f70-ee869110ed64)

**Comment by ophub** [comment]
感谢分享，根据你的反馈，添加到了121序号里。可以直接使用名字里带`s905l3-cm211`的固件安装使用

**Comment by itlaohuo** [comment]
我的ZXV10B860AV3.2-M盒子（移动高清盒子6PRO，4G+16G版本，刷TV系统后识别2.95G内存和32G存储）拆开看了，芯片是s905l3b。

**Comment by Jawf** [comment]
> 我的ZXV10B860AV3.2-M盒子（移动高清盒子6PRO，4G+16G版本，刷TV系统后识别2.95G内存和32G存储）拆开看了，芯片是s905l3b。暂时无法从U盘启动。 盒子同网友的另外一个issue 求一份B860AV3.2-M（4+16/32版本）盒子的bootloader.bin或者安卓固件包 #1982

+1， 我的也是 ZXV10B860AV3.2-M盒子（移动高清盒子6PRO，4G+16G版本，刷TV系统后识别2.95G内存和32G存储）
刷过多个镜像，有成功识别4G内存的朋友谢谢分享下bootloader或u-boot.ext：
Armbian_24.2.0_amlogic_s905l3b_bullseye_5.15.145_server_2024.01.01.img.gz；
Armbian_24.2.0_amlogic_s905l3b_bullseye_6.6.11_server_2024.01.13.img.gz 

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/58920aca-9318-49ff-81f8-83d6a06d8b8b)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/d9d75dc3-3dd3-450b-8b8b-db3a10a70563)

试过124-128，都从u盘刷入过emmc，都能成功的，但都是2.8G内存：
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/85547/49bcff8b-afad-4018-b29a-bccbff0e6540)
u盘改过u-boot-x96max.bin和u-boot-e900v22c.bin为u-boot.ext后，u盘无法启动；

 有成功识别4G内存的朋友谢谢分享下bootloader或u-boot.ext！

**Comment by itlaohuo** [comment]
我也先将就着用着，识别2.75G（5.15的内核），安装时选的121，且无hdmi输出。

**Comment by mikeljhon82** [comment]
我想请问，如果没有HDMI输出，我们怎么看系统或者进行下一步操作？

**Comment by ophub** [comment]
可以ssh连接，在终端里可以正常管理，没hdmi只是不能通过显示器查看。

**Comment by mikeljhon82** [comment]
> 感谢分享，根据你的反馈，添加到了121序号里。可以直接使用名字里带`s905l3-cm211`的固件安装使用

大佬，请问固件用带`s905l3-cm211`的还需要修改里面的其他配置文件吗？

**Comment by mikeljhon82** [comment]
> Device Information | 设备信息
> 
> ```
> SOC: S905L3
> Model: ZXV10 B860AV3.2-M 
> 
> 
> Kernel Version: 5.15.145
> Release: bullseye
> ```
> 
> Describe the bug | 问题描述
> 
> 使用镜像Armbian_24.2.0_amlogic_s905l3_bullseye_5.15.145_server_2024.01.01.img，U盘启动正常，HDMI没有输出，通过SSH连接，执行armbian-install命令，dtb选择121号CM211-1,M411A的dtb，meson-gxl-s905l3b-m302a.dtb，文件系统选择EXT4。写入emmc后正常启动，HDMI还是没有输出，其他功能正常。
> 
> ![64ebbae94716bcf8faff2b1a2da53b6](https://private-user-images.githubusercontent.com/22270173/295874000-051b0d46-b873-4a45-a351-77f0ea4a60a9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzQ5MzAsIm5iZiI6MTcwNjA3NDYzMCwicGF0aCI6Ii8yMjI3MDE3My8yOTU4NzQwMDAtMDUxYjBkNDYtYjg3My00YTQ1LWEzNTEtNzdmMGVhNGE2MGE5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NGQ5YzQ2MzM3YjE1Y2ZkOTVmZjNlNWI1ZjA3YzdmZTMyZjI2YWY4OGM0YjNjZDZhMTM1YzQ5YzIyNWQ0MjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TyFX8lA8sdBwsX3al2CP6sj60AYHwUBkgUF1hgmBK3E)
> 
> ![d8f53020f265cb9c6f5702b22209851](https://private-user-images.githubusercontent.com/22270173/295874167-5bba2ec9-2e58-4865-8f70-ee869110ed64.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwNzQ5MzAsIm5iZiI6MTcwNjA3NDYzMCwicGF0aCI6Ii8yMjI3MDE3My8yOTU4NzQxNjctNWJiYTJlYzktMmU1OC00ODY1LThmNzAtZWU4NjkxMTBlZDY0LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI0VDA1MzcxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMDBlNjBhYWE1NGNmMDIyNGM0MmJmNWJjMWM4YTM3YTFhM2E5YTJlZTI3MWE1YWQzMTNlM2Y5NTdhZDI3NzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wZP0khi_JwDAvGGtxoKIfDYojxi_Z7_vg6tdpItsT5I)

您好，请问你刷的Android底包是哪个版本的，可以分享一下啊？我的是2+32G的

**Comment by ophub** [comment]
固件用带s905l3-cm211的不需要修改

**Comment by mikeljhon82** [comment]
root@armbian:~#  armbian-software
[ STEPS ] Start installing the necessary dependencies...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ ERROR ] Dependency installation failed, stop install.
root@armbian:~#
这个怎么办、

**Comment by xuzhijvn** [comment]
thanks, ophub bro, is success
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/20964259/c954f0c7-7bd0-4a9e-8175-46812828f74a)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/20964259/87e9d9f6-25a7-415e-b974-6ae6ed3f2016)

**Comment by itlaohuo** [comment]
我前几天再armbian上安装pve后就和盒子失联了，昨天又刷回当贝桌面看电视了。
我想问问又大佬通过armbian安装pve后再虚拟一个电视机系统出来的吗？

**Comment by yicijiandan** [comment]
zxv10 B860AV3.2-T和这个不是一个东西吧

**Comment by mikeljhon82** [comment]
博主，我已经按这个方案刷好机了。也正常配置jellyfin。目前遇到一个问题是：只要1个小时不到的时间不去访问armbian盒子，盒子就会自动掉线，在路由上看不到IP。然后只能关机重启

**Comment by flyice-juin** [comment]
> 固件用带s905l3-cm211的不需要修改

大佬，使用这个固件可以使用。不过，请问蓝牙是否可以驱动呢？目前是识别不到

**Comment by asdasdasdaf** [comment]
中兴ZXV10 B860AV3.2-M蓝牙问题：
我也是这款机顶盒有没有大佬可以解决一下蓝牙reboot重启后无法使用的问题
这是我测试的过程https://blog.csdn.net/weixin_45437211/article/details/140451196

**Comment by asdasdasdaf** [comment]
这是机顶盒安卓系统的dts文件
[安卓系统dts.zip](https://github.com/user-attachments/files/16512794/dts.zip)
这是我armbian系统编译的dts文件
[meson-gxl-s905l3b-m302a.zip](https://github.com/user-attachments/files/16512798/meson-gxl-s905l3b-m302a.zip)
@ophub 大佬目前蓝牙断电重启后可以正常使用，通过reboot命令重启后蓝牙使用不了，麻烦有时间的话帮我解决一下。
这是断电重启后正常的截图
![image](https://github.com/user-attachments/assets/0a78256e-bcbc-43a9-9cc0-db78d567e175)
![image](https://github.com/user-attachments/assets/f0fb990a-abe6-4e31-9e4c-03c9358b268a)
通过reboot命令重启后蓝牙就无法正常工作了！
![image](https://github.com/user-attachments/assets/a424acc2-69a5-421a-9b55-63f7d1d1dce4)

**Comment by asdasdasdaf** [comment]
摸索不出正确的reset-gpios值，这个reset-gpios = <0x28 0x1e 0x00>;是我测试的感觉是错的

**Comment by itlaohuo** [comment]
> > 固件用带s905l3-cm211的不需要修改
> 
> 大佬，使用这个固件可以使用。不过，请问蓝牙是否可以驱动呢？目前是识别不到

蓝牙驱动要自己去装，是没有问题的

**Comment by 414090628** [comment]
大佬, 怎么使用外置网卡, lsusb 发现是 RTL8188GU 的, 找了一些教程, 结果都卡在 找不到 8188gu.ko, 不知道去哪找这文件

**Comment by chenag** [comment]
> ![QQ图片20240124132525](https://private-user-images.githubusercontent.com/129525075/299194223-b796b0fb-d682-4a9b-93f3-1de20555c263.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM4MTk5NzgsIm5iZiI6MTczMzgxOTY3OCwicGF0aCI6Ii8xMjk1MjUwNzUvMjk5MTk0MjIzLWI3OTZiMGZiLWQ2ODItNGE5Yi05M2YzLTFkZTIwNTU1YzI2My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMFQwODM0MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMTAzNWZjM2FiMDA0MzNjYThmZGMzYmQ0ZGI2MjIwZTA2N2M5ZDc3ZGJmMGM4NDY4ZmQ1YzgzODMwNmFhMTFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.CPdofoHurV99FV06Gneoy2sgeImVCTFw4DbsCnOTxN8)
> 
> > 感谢分享，根据你的反馈，添加到了121序号里。可以直接使用名字里带`s905l3-cm211`的固件安装使用
> 
> 大佬，请问固件用带`s905l3-cm211`的还需要修改里面的其他配置文件吗？

请问你这个固件是啥啊，为什么找不到2G内存版本的固件，能分享一下吗？

**Comment by darongshu1977** [comment]
ZXV10 B860AV3.1-M2的盒子能刷ARMBIAN吗？试了几次启动黑屏，路由器也找不到盒子，有哪个大师教一下，看支持列表里面没有这个型号，不知道能刷不，芯片是S905L3.

**Comment by goneyes** [comment]
> ZXV10 B860AV3.1-M2的盒子能刷ARMBIAN吗？试了几次启动黑屏，路由器也找不到盒子，有哪个大师教一下，看支持列表里面没有这个型号，不知道能刷不，芯片是S905L3.

可以，我的就是。引导U盘插到离网口最近USB口，用开心助手的“从U盘/SD卡启动”就可以引导。HDMI驱动问题，都是黑屏的，但实际已经引导成功，要用PUTTY进入。

**Comment by lubo19802006** [comment]
> 我的ZXV10B860AV3.2-M盒子（移动高清盒子6PRO，4G+16G版本，刷TV系统后识别2.95G内存和32G存储）拆开看了，芯片是s905l3b。暂时无法从U盘启动。 盒子同网友的另外一个issue 求一份B860AV3.2-M（4+16/32版本）盒子的bootloader.bin或者安卓固件包 [#1982](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1982)

不能u盘启动大概率是包不对，我今天也是这个情况，U盘启动不了，更换包就可以

**Comment by zacklee111** [comment]
还没搞懂在哪里可以下载...我也是这个盒子

**Comment by lubo19802006** [comment]
> 还没搞懂在哪里可以下载...我也是这个盒子

更换包就可以了

**Comment by ngsxmb9609260** [comment]
请问这个下载文件应该有多大，我下了都是几十mb

**Comment by chulong6** [comment]
我也是无显示驱动，但是ssh可以连上，之后查ai改了下设备的ip，然后就彻底失联了，这种情况怎么处理啊大佬们

[00-default-use-network-manager.yaml](https://github.com/user-attachments/files/21853109/00-default-use-network-manager.yaml)

**Comment by wang260904546** [comment]
从新刷机就可以了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年8月19日(星期二) 下午5:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)












chulong6 left a comment (ophub/amlogic-s9xxx-armbian#2012)
 
我也是无显示驱动，但是ssh可以连上，之后查ai改了下设备的ip，然后就彻底失联了，这种情况怎么处理啊大佬们
 
00-default-use-network-manager.yaml

**Comment by chulong6** [comment]
咋刷啊😂，我连不上这个设备，也没有显示输出

**Comment by chulong6** [comment]
我查百度说这个设备还锁了ttl

**Comment by wang260904546** [comment]
不需要拆开




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年8月20日(星期三) 上午8:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)












chulong6 left a comment (ophub/amlogic-s9xxx-armbian#2012)
 
我查百度说这个设备还锁了ttl

**Comment by chulong6** [comment]
大佬，给个思路，我现在的状况是已经刷成功了，但是没有显示输出，然后我ip又改失败连不上了

**Comment by ngsxmb9609260** [comment]
重新刷机就可以了发自我的荣耀手机-------- 原始邮件 --------发件人： chulong6 ***@***.***>日期： 2025年8月20日周三 08:43收件人： ophub/amlogic-s9xxx-armbian ***@***.***>抄送： ngsxmb9609260 ***@***.***>, Comment ***@***.***>主    题： Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)chulong6 left a comment (ophub/amlogic-s9xxx-armbian#2012)
大佬，给个思路，我现在的状况是已经刷成功了，但是没有显示输出，然后我ip又改失败连不上了

**Comment by chulong6** [comment]
咋刷啊，求求给个具体的方法啊😭

**Comment by wang260904546** [comment]
https://www.runyf.cn/archives/364/




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年8月20日(星期三) 上午9:50
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)












chulong6 left a comment (ophub/amlogic-s9xxx-armbian#2012)
 
咋刷啊，求求给个具体的方法啊😭

**Comment by chulong6** [comment]
好的，我晚上回去之后试试，多谢大佬

**Comment by chulong6** [comment]
大佬们牛逼，安卓9刷上了，但是一直进不去u盘刷armbian。老是跳在这个页面，选u盘更新提示失败

![Image](https://github.com/user-attachments/assets/8efb64ee-f389-44d3-af92-db5402707b59)

**Comment by wang260904546** [comment]
安卓9打开ADB&nbsp; &nbsp;然后使用开心助手&nbsp; 直接进入armbian&nbsp; &nbsp; 然后写入emmc




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年8月21日(星期四) 下午5:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)












chulong6 left a comment (ophub/amlogic-s9xxx-armbian#2012)
 
大佬们牛逼，安卓9刷上了，但是一直进不去u盘刷armbian。老是跳在这个页面，选u盘更新提示失败
 
IMG_20250820_230345.jpg (view on web)

**Comment by chulong6** [comment]
好的，谢谢大佬，有思路了，

**Comment by llg329** [comment]
已经刷了armbian,如何重新刷呢?

**Comment by shaohua540** [comment]
U盘启动正常，HDMI没有输出，通过SSH连接，执行armbian-install命令，卡在这里我的到u盘启动后ip上线了网页打不开[捂脸]ssh连接用户名密码不对，默认多少？机顶盒芯片905 L3固件是最新的https://github.com/ophub/fnnas/releases/download/fnnas_v300/fnnas_amlogic_s905l3-cm211_k6.12.41_2026.01.10.img.gz

**Comment by ngsxmb9609260** [comment]
用户名是admin,&nbsp;密码是1234,试试
&nbsp;


中庸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2026年1月14日(星期三) 凌晨4:25
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)



shaohua540 left a comment (ophub/amlogic-s9xxx-armbian#2012)
 
U盘启动正常，HDMI没有输出，通过SSH连接，执行armbian-install命令，卡在这里我的到u盘启动后ip上线了网页打不开[捂脸]ssh连接用户名密码不对，默认多少？机顶盒芯片905 L3固件是最新的

**Comment by silence5525** [comment]
> 大佬们牛逼，安卓9刷上了，但是一直进不去u盘刷armbian。老是跳在这个页面，选u盘更新提示失败
> 
> ![Image](https://github.com/user-attachments/assets/8efb64ee-f389-44d3-af92-db5402707b59)

大佬们，我U盘制作飞牛启动盘，机顶盒系统刷的是slimBoxTV，但是想装飞牛OS，我也是每次都提示这个页面，从U盘启动，提示更新失败，有没有啥好办法呢

**Comment by shaohua540** [comment]
> 用户名是admin,&nbsp;密码是1234,试试
> &nbsp;
> 
> 
> 中庸
> ***@***.***
> 
> 
> 
> &nbsp;
> […](#)

提示认证失败，Armbian_24.2.0_amlogic_s905l3_bullseye_5.15.145_server_2024.01.01.img你这个固件哪里下载?能发个链接吗？我找不到你这个固件，最新的固件不行！我的机顶盒和你的一样2+8配置 S905L3

**Comment by shaohua540** [comment]
> 用户名是admin,&nbsp;密码是1234,试试
> &nbsp;
> 
> 
> 中庸
> ***@***.***
> 
> 
> 
> &nbsp;
> […](#)
admin密码1234也不对

**Comment by ngsxmb9609260** [comment]
试试root，1234




中庸
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-armbian"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2026年1月15日(星期四) 中午11:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-armbian] ZXV10 B860AV3.2-M写入EMMC正常 (Issue #2012)



shaohua540 left a comment (ophub/amlogic-s9xxx-armbian#2012)
  
用户名是admin,&nbsp;密码是1234,试试
 &nbsp;
 
中庸
 @.***
 
&nbsp;
 …
 admin密码1234也不对

**Comment by shaohua540** [comment]
> 试试root，1234
> 
> 
> 
> 
> 中庸
> ***@***.***
> 
> 
> 
> &nbsp;
> […](#)

也不对，提示错误

**Comment by shaohua540** [comment]
解决了U盘兼容性问题换U盘就好了能打开网页了

**Comment by xxj737** [comment]
ZXV10 B862AV3.1-U  有用这个型号的盒子吗
可以刷哪个固件的
帮忙分享下
感谢！

**Comment by flowerstores** [comment]
我有一个B860av3.2-t s 四川电信高安版的 晶晨s905L3b的 刷机之后每个五分钟重启 刷上重启卡刷包 死机进不了桌面  又刷了一次 刷入成功连接电视 有信号但电视黑屏

**Comment by bvrkvt** [comment]
> 我有一个B860av3.2-t s 四川电信高安版的 晶晨s905L3b的 刷机之后每个五分钟重启 刷上重启卡刷包 死机进不了桌面 又刷了一次 刷入成功连接电视 有信号但电视黑屏

请问刷的哪个镜像
