### ISSUE TITLE
能否增加 h339pc 板子的支持？

### ISSUE THREAD

**Issue by paomian** [ophub/amlogic-s9xxx-armbian#2013]
搜了一圈没看到此型号相关的说明，从厂家给的 android 和 ubuntu 镜像看，似乎是基于 firefly 做的。
相关的信息在这里 http://files.kos.org.cn/rockchip/H3399PC/

**Comment by paomian** [comment]
被厂家搞懵了，感觉他有些地方没有写全，网上能找到的资料也有叫 h3399pc 的 https://pmod6b30a-pic29.websiteonline.cn/upload/mpc-339902.pdf 这基本上和我的这款看起来一摸一样
https://www.bilibili.com/video/BV1xb4y1K7fd/?vd_source=54b5bd8b89d7b1cde2e5e2671f098fdc 但是板子背面却是 339pc

**Comment by nahco365** [comment]
这个板子刷Armbian_rockchip_firefly-rk3399可以使用，但是重启会卡死，不知道什么原因。
