### ISSUE TITLE
Firmware packages not keep on hold

### ISSUE THREAD

**Issue by Choomai** [ophub/amlogic-s9xxx-armbian#2020]
**Device Information**
 - SOC: S905W
 - Model MXQ Pro 4K

**Armbian Version**
 - Kernel Version: 6.1.69
 - Release: jammy

**Describe the bug**
After updating from 6.1.67 to 6.1.69, I can't boot anymore. You can see the video for what happen.
I remember before updating, I do an `sudo apt upgrade` and there is only 1 package named `armbian-*-current`. The asterisk is something that I can't remember. Some other packages have updated but have been kept back, and it also have that same package, just without the suffix `-current`. I have backup of 6.1.65 and 6.1.67 (after `sudo apt upgrade`). Tried flash the newest version to USB and `armbian-update -s` but doesn't work.

Maybe that package got update with official armbian packages, not the modified one you made.

https://github.com/ophub/amlogic-s9xxx-armbian/assets/89532534/dbbaeb07-bdf5-4992-8598-5734db5844a2

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/be9070d016d3f8b475b4a6c02eaaebca0300f724/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L64

By default, I have already locked this package. Please do not unlock the packages I have locked.

**Comment by Choomai** [comment]
I don't lock that package, that is the default. Maybe you forgot to add one, but now I'm really need my server to working, so do you have any solution?

**Comment by ophub** [comment]
The lock has already been executed automatically when the Armbian system is first started, so there is no need for manual operation. 
If you do not usually unlock these software packages for updates, there will be no errors.

**Comment by Choomai** [comment]
Mistake could happen, and that package have not been locked (there is a lot of armbian and firmware package got locked by that command), maybe you forgot or Armbian APT repo got something new that you haven't covered it yet.

But yeah, I also make a mistake when not checking what package will update, kept back, or not needed. Now I'm just want to know how to solve this problem, as I need to get my server running real quick.

**Comment by Choomai** [comment]
@ophub Can you please give me a solution? Like restore from backup or just re-install the firmware without data loss?

**Comment by Choomai** [comment]
Nevermind, I re-installed.

**Comment by Choomai** [comment]
@ophub After a while, I learn from my mistake that to read packages carefully and I see this. Do I need to keep any packages? Or just upgrade these?
```
choomai@mxq-s905w:~$ sudo apt upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Calculating upgrade... Done
The following packages have been kept back:
  armbian-bsp-cli-odroidn2-current libnode-dev libnode72 libudev1 nodejs udev
The following packages will be upgraded:
  armbian-config armbian-firmware armbian-plymouth-theme armbian-zsh base-files binutils binutils-aarch64-linux-gnu binutils-common coreutils
  dns-root-data fake-ubuntu-advantage-tools libbinutils libctf-nobfd0 libctf0 libgnutls30 libldap-2.5-0 libmm-glib0 libmysqlclient21
  libnss-myhostname libpam-systemd libpq5 libssh-4 libssl-dev libssl3 libsystemd0 libunbound8 libuv1 libuv1-dev libxml2 login mysql-client-8.0
  mysql-client-core-8.0 mysql-server-8.0 mysql-server-core-8.0 postfix smartmontools systemd systemd-sysv tzdata
39 upgraded, 0 newly installed, 0 to remove and 6 not upgraded.
Need to get 124 MB/130 MB of archives.
After this operation, 306 kB disk space will be freed.
Do you want to continue? [Y/n]
```
