### ISSUE TITLE
部分m401a启动困难

### ISSUE THREAD

**Issue by sesame-foxes** [ophub/amlogic-s9xxx-armbian#2021]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [m401a]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.69]
 - Release: [bullseye]

**Describe the bug | 问题描述**
少量m401a会出现启动困难的情况，直接卡在黑屏阶段（具体表现为：插显示器的情况下，屏幕是黑色，没有任何显示，没有logo和跑码，且盒子状态灯为红色）。多次开关后有一定几率能进入系统，或者卡在开机界面等待一段时间后重新启动也能提高启动成功的几率。如果机器运行状态重启，暂未发生卡黑屏的情况。
该问题多次发生，各种来源的m401a盒子都出现过这个问题，但是安卓却可以正常启动。

该情况无论是U盘启动还是emmc启动都会发生，无法获取错误代码，请问可能是什么问题？还是说盒子体质不行。

**Comment by congming543** [comment]
我的也是M401a的盒子，建议你先刷一下ophub提供的安卓TV包，这个包默认带root，默认usb启动是第一优先级，然后再刷debian，不建议ubuntu个人感觉卡，刷debian首次需要按住reset然后开机，3秒后会花屏，花屏3秒后开始刷屏，注意hdmi一定要接hdmi显示器，不要带转换的线，最好1920*1080分辨率的屏幕，开机后屏幕文字会比较小，说明正常，设置完root密码，区域语言后，再：sudo armbian-install，

**Comment by jjjyyyllll** [comment]
> 我的也是M401a的盒子，建议你先刷一下ophub提供的安卓TV包，这个包默认带root，默认usb启动是第一优先级，然后再刷debian，不建议ubuntu个人感觉卡，刷debian首次需要按住reset然后开机，3秒后会花屏，花屏3秒后开始刷屏，注意hdmi一定要接hdmi显示器，不要带转换的线，最好1920*1080分辨率的屏幕，开机后屏幕文字会比较小，说明正常，设置完root密码，区域语言后，再：sudo armbian-install，
ophub提供的安卓TV包， m401a是哪一个啊？？

**Comment by Haaooo** [comment]
> > 我的也是M401a的盒子，建议你先刷一下ophub提供的安卓TV包，这个包默认带root，默认usb启动是第一优先级，然后再刷debian，不建议ubuntu个人感觉卡，刷debian首次需要按住reset然后开机，3秒后会花屏，花屏3秒后开始刷屏，注意hdmi一定要接hdmi显示器，不要带转换的线，最好1920*1080分辨率的屏幕，开机后屏幕文字会比较小，说明正常，设置完root密码，区域语言后，再：sudo armbian-install，
> > ophub提供的安卓TV包， m401a是哪一个啊？？

请问为什么不能用带转换的线？我的是接的转HDMI的线，然后开机花屏，重新通电就开不了机了

**Comment by haoqi366** [comment]
有可能是买到江苏单电感版本的m401a了，这种情况下把cpu主频限制到1.5Ghz能正常用
