### ISSUE TITLE
如何使1G内存的中兴B863AV3.2M适配armbian？

### ISSUE THREAD

**Issue by caseybase** [ophub/amlogic-s9xxx-armbian#2025]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [B863AV3.2M] 1G RAM

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.69] server
 - Release: [jammy]

**Describe the bug | 问题描述**
我拿到一个1G内存的中兴B863AV3.2M盒子，获取root权限，但并能运行armbian，请问如何修改armbian并适配。
该盒子的安卓dtb在附件中。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

[g12a_u212_1g.dts.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/13933805/g12a_u212_1g.dts.gz)
![1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89326547/a1a9ffe7-79eb-413a-8688-730f1d2f22aa)
![2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89326547/1f363562-9f8a-4e0d-9f11-a8f6aec86b09)
![3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/89326547/2f95a47a-583d-4c56-9022-f627ef5cd027)

**Comment by ophub** [comment]
根据首页的列表使用对应的固件测试

**Comment by caseybase** [comment]
> 根据首页的列表使用对应的固件测试

O大，列表中适配s905l3a的dtb，我反编译成dts是2G的memory，而我的盒子偏偏是1G的，我把dtb的内存直接改成1G，有可能成功吗？

**Comment by ophub** [comment]
只要执腾的手不停止，希望就有无限可能。你放弃了才会没有希望。

**Comment by caseybase** [comment]
> 你放弃了才会没有希望。

好的。我再试试。
