### ISSUE TITLE
大佬能求帮忙适配LX-R3S openwrt

### ISSUE THREAD

**Issue by kuuer** [ophub/amlogic-s9xxx-armbian#2026]
![端口](https://github.com/ophub/amlogic-s9xxx-armbian/assets/78456431/bd6844e8-294a-42c1-8557-fdaf610264de)
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [LX-R3S] 4+32G

**Armbian Version | 系统版本21.08.1
下载链接：http://files.kos.org.cn/rockchip/lx-r3s/
**Describe the bug | 问题描述**
找不到dtb，能帮忙适配下openwrt固件和DTB吗？
目前用xiaobao的dtb， 网卡和usb3.0正常，TF卡和usb2.0以及wifi（RTL8723DS）不能用。

**Comment by ophub** [comment]
我添加了，你到对接的releases里下载测试下，反馈下结果。

**Comment by ophub** [comment]
转载LX-R3S的maskrom短接点：

![maskrom短接点](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/d1666278-2372-4526-a1ea-c76c630e081c)

**Comment by kuuer** [comment]
> 我添加了，你到对接的releases里下载测试下，反馈下结果。

经测试TFUSB接口正常了，除了无线，这个大佬能解决吗？

**Comment by ophub** [comment]
https://github.com/cm9vdA/build-linux/blob/master/boot/dts/rockchip/mainline/rk3399-lx-r3s.dts

我用的这个仓库的dts，你查看你板子的无线芯片，看内核6.1.y有没有驱动

**Comment by ophub** [comment]
我不会用istoreos ，之前试过用这个编启动了没有网，删除了

**Comment by kuuer** [comment]
> 我不会用istoreos ，之前试过用这个编启动了没有网，删除了

那可以帮忙编译一个内核5.10.201的dtb文件吗？我来测试一下看看。谢谢!

**Comment by ophub** [comment]
armbian-update -k 5.10

**Comment by kuuer** [comment]
> armbian-update -k 5.10

大佬，没找到在哪~

**Comment by ophub** [comment]
终端里更新内核

**Comment by kuuer** [comment]
> 终端里更新内核
更新5.10内核，起不来了。是没有dtb文件吗？

**Comment by ophub** [comment]
你复制一个

**Comment by 90999** [comment]
> ![端口](https://private-user-images.githubusercontent.com/78456431/296726249-bd6844e8-294a-42c1-8557-fdaf610264de.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIxMTk4NzMsIm5iZiI6MTczMjExOTU3MywicGF0aCI6Ii83ODQ1NjQzMS8yOTY3MjYyNDktYmQ2ODQ0ZTgtMjk0YS00MmMxLTg1NTctZmRhZjYxMDI2NGRlLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIwVDE2MTkzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NzZhYTI4M2U1M2FjNTBiNWI2MWFjNDdkNjIxOGRhZGMwODA5ZjhiOGJkMTRmMmQ2ZDc0ZjllYWE2OTRlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.uNky-HRI9FogQRbgNjwGo4X2aHQXZZz4y1gF3Ez2g8c) **Device Information | 设备信息**
> 
> * SOC: [RK3399]
> * Model [LX-R3S] 4+32G
> 
> **Armbian Version | 系统版本21.08.1 下载链接：http://files.kos.org.cn/rockchip/lx-r3s/ **Describe the bug | 问题描述** 找不到dtb，能帮忙适配下openwrt固件和DTB吗？ 目前用xiaobao的dtb， 网卡和usb3.0正常，TF卡和usb2.0以及wifi（RTL8723DS）不能用。

HDMI能用么？

**Comment by Ricoheyuqiang** [comment]
有openwrt了吗？
