### ISSUE TITLE
Panther X2 升级rk内核后eth0网口不可用，需要使用JP-Box的u-boot

### ISSUE THREAD

**Issue by HelloTheAsia** [ophub/amlogic-s9xxx-armbian#2027]
**Device Information | 设备信息**
 - SOC: [3566]
 - Model [Panther X2]

**Armbian Version | 系统版本**
 - Kernel Version: [5.10.160]
 - Release: [jammy/bullseye]

**Describe the bug | 问题描述**
#1960 #1880 
同上面两个问题,x2在使用rk内核eth0网卡不可用.x2使用jp-box的armbian固件eth0是正常可用.刚开始以为是dtb的问题,改了很久dtb依旧没有用,后续我直接将dtb换成jp-box的进行编译.依旧无效.
开始怀疑u-boot的问题,将u-boot的换成jp-box,dtb没有改动.rk35xx内核成功识别eth0网卡.不知道两者的差异.但是看起来jp的u-boot在x2上运行是没有问题的.

**Comment by ophub** [comment]
你测试一下，不换内核，默认的u-boot使用默认的6.1.y内核可以吧

**Comment by HelloTheAsia** [comment]
是的,默认的u-boot使用默认的6.1.y的内核 是没有问题的.只有默认的u-boot使用rk的内核eth0才不工作.

**Comment by ophub** [comment]
好的，感谢分享，给大家使用提供了指导

**Comment by LSP0123** [comment]
> 是的,默认的u-boot使用默认的6.1.y的内核 是没有问题的.只有默认的u-boot使用rk的内核eth0才不工作.

您好，请问当前要Panther X2使用mpp只能刷jp盒子的5.X内核吗

**Comment by HelloTheAsia** [comment]
> > 是的，默认的u-boot使用默认的6.1.y的内核 是没有问题的.只有默认的u-boot使用rk的内核eth0才不工作.
> 
> 您好，请问当前要Panther X2使用mpp只能刷jp盒子的5.X内核吗

如果你想要jellyfin硬件解码.可以看一下我折腾过程中整理的文章.
https://hiasia.gitee.io/2024/01/14/%E6%8A%98%E8%85%BE/Panther%20X2%20rk3566%E4%BD%BF%E7%94%A8Jellyfin%E5%BC%80%E5%90%AF%E7%A1%AC%E4%BB%B6%E8%A7%A3%E7%A0%81/
主要的思路是dts开启vpu的支持,换rk内核,rk35xx内核参数要改一下较新的驱动.就可以了

**Comment by LSP0123** [comment]
> > > 是的，默认的u-boot使用默认的6.1.y的内核 是没有问题的.只有默认的u-boot使用rk的内核eth0才不工作.
> > 
> > 
> > 您好，请问当前要Panther X2使用mpp只能刷jp盒子的5.X内核吗
> 
> 是的,或者你自己会改dts的话,应该配置对应的vpu.和使用rk内核就行,如果你想要jellyfin硬件解码.可以看一下我折腾过程中整理的文章. https://hiasia.gitee.io/2024/01/14/%E6%8A%98%E8%85%BE/Panther%20X2%20rk3566%E4%BD%BF%E7%94%A8Jellyfin%E5%BC%80%E5%90%AF%E7%A1%AC%E4%BB%B6%E8%A7%A3%E7%A0%81/ 主要的思路是dts开启vpu的支持,换rk内核,rk35xx内核参数要改一下较新的驱动.就可以了

好的，麻烦您了，虽然我对修改这些一窍不通，但是您的文章我大概理解了。

**Comment by LSP0123** [comment]
> > > 是的，默认的u-boot使用默认的6.1.y的内核 是没有问题的.只有默认的u-boot使用rk的内核eth0才不工作.
> > 
> > 
> > 您好，请问当前要Panther X2使用mpp只能刷jp盒子的5.X内核吗
> 
> 是的,或者你自己会改dts的话,应该配置对应的vpu.和使用rk内核就行,如果你想要jellyfin硬件解码.可以看一下我折腾过程中整理的文章. https://hiasia.gitee.io/2024/01/14/%E6%8A%98%E8%85%BE/Panther%20X2%20rk3566%E4%BD%BF%E7%94%A8Jellyfin%E5%BC%80%E5%90%AF%E7%A1%AC%E4%BB%B6%E8%A7%A3%E7%A0%81/ 主要的思路是dts开启vpu的支持,换rk内核,rk35xx内核参数要改一下较新的驱动.就可以了

我对比了下jp和x2的dts，是不是因为x2的dts里的reserved-memory这一段没有rknpu导致npu没开起来？jp的reserved-memory是有rhnpu的

**Comment by chouex** [comment]
我補充下換uboot過程, (只有Panther X2, 其他盒子不要試, 沒條件線刷也不要試)

https://github.com/ophub/u-boot/tree/main/u-boot/rockchip/jp-tvbox
下載`idbloader.img` `u-boot.itb`
```
# dd if=idbloader.img of=/dev/mmcblk1 seek=64
# dd if=u-boot.itb of=/dev/mmcblk1 seek=16384
```
關機再開機

另外uboot開始有dtb的header(`d0 0d fe ed`), 我覺得是`/boot`中的dtb沒有效

**Comment by FusionPlmH** [comment]
这边找到了一份同款机器的另外一个包，国外有人把原装系统开ssh和root了，看看有没有帮租继续优化下。

参考视频：
https://youtu.be/bkl76iK-WAo?si=ySDhOBx4B_eoGiXt

修改过后的固件下载：
https://drive.google.com/drive/folders/1xxxJP7udmXkyyLGqBmzz7l15Ing898cl?usp=sharing

以及下面简单原理图：
![Screenshot_20240211_033612_Samsung Notes](https://github.com/ophub/amlogic-s9xxx-armbian/assets/16817768/50d371fc-66b1-41a2-8f2e-da710d96fa36)

**Comment by LSP0123** [comment]
> 这边找到了一份同款机器的另外一个包，国外有人把原装系统开ssh和root了，看看有没有帮租继续优化下。另外确实是标准minipcie是和52pin接口，不过模块走的spi协议。
> 
> 参考视频： https://youtu.be/bkl76iK-WAo?si=ySDhOBx4B_eoGiXt
> 
> 修改过后的固件下载： https://drive.google.com/drive/folders/1xxxJP7udmXkyyLGqBmzz7l15Ing898cl?usp=sharing
> 
> 以及下面简单原理图和minipcie定义： ![Screenshot_20240211_033612_Samsung Notes](https://private-user-images.githubusercontent.com/16817768/303861675-50d371fc-66b1-41a2-8f2e-da710d96fa36.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTE5NzksIm5iZiI6MTcwNzYxMTY3OSwicGF0aCI6Ii8xNjgxNzc2OC8zMDM4NjE2NzUtNTBkMzcxZmMtNjZiMS00MWEyLThmMmUtZGE3MTBkOTZmYTM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDAwMzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzMwZDFmY2E1NjQzOWIzMjBiYzZmN2E4MzI1ZGE1NDQ3MjYzODdiYTQxMTE3ODZiNzJmMzU3MDU2MDFlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPfdP0yvossJuXMP5y14sJrJ3pNF-Ut-ULLfv_H2m6o)
> 
> ![Screenshot_20240211_040818](https://private-user-images.githubusercontent.com/16817768/303862479-088f270f-98b7-498f-9307-0b6b6f8bc59d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTE5NzksIm5iZiI6MTcwNzYxMTY3OSwicGF0aCI6Ii8xNjgxNzc2OC8zMDM4NjI0NzktMDg4ZjI3MGYtOThiNy00OThmLTkzMDctMGI2YjZmOGJjNTlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDAwMzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NjZmN2VjYTkwMzU0OTZmZWMxYjJhZWQwMjA5ZjI2ZTViOTk1YTZlNDRkNzA5NzUzNmViNjUzOTQ1ZjM0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pD1VcTR-nQivkaQ7pUNgR_hZRJXyEmmwZej7Y1yekMI)

麻烦传份度盘？我这边上不了googledriver

@HelloTheAsia 试一下？

**Comment by FusionPlmH** [comment]
> > 这边找到了一份同款机器的另外一个包，国外有人把原装系统开ssh和root了，看看有没有帮租继续优化下。另外确实是标准minipcie是和52pin接口，不过模块走的spi协议。
> > 参考视频： https://youtu.be/bkl76iK-WAo?si=ySDhOBx4B_eoGiXt
> > 修改过后的固件下载： https://drive.google.com/drive/folders/1xxxJP7udmXkyyLGqBmzz7l15Ing898cl?usp=sharing
> > 以及下面简单原理图和minipcie定义： ![Screenshot_20240211_033612_Samsung Notes](https://private-user-images.githubusercontent.com/16817768/303861675-50d371fc-66b1-41a2-8f2e-da710d96fa36.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTE5NzksIm5iZiI6MTcwNzYxMTY3OSwicGF0aCI6Ii8xNjgxNzc2OC8zMDM4NjE2NzUtNTBkMzcxZmMtNjZiMS00MWEyLThmMmUtZGE3MTBkOTZmYTM2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDAwMzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkYzMwZDFmY2E1NjQzOWIzMjBiYzZmN2E4MzI1ZGE1NDQ3MjYzODdiYTQxMTE3ODZiNzJmMzU3MDU2MDFlZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QPfdP0yvossJuXMP5y14sJrJ3pNF-Ut-ULLfv_H2m6o)
> > ![Screenshot_20240211_040818](https://private-user-images.githubusercontent.com/16817768/303862479-088f270f-98b7-498f-9307-0b6b6f8bc59d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2MTE5NzksIm5iZiI6MTcwNzYxMTY3OSwicGF0aCI6Ii8xNjgxNzc2OC8zMDM4NjI0NzktMDg4ZjI3MGYtOThiNy00OThmLTkzMDctMGI2YjZmOGJjNTlkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDAwMzQzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NjZmN2VjYTkwMzU0OTZmZWMxYjJhZWQwMjA5ZjI2ZTViOTk1YTZlNDRkNzA5NzUzNmViNjUzOTQ1ZjM0NWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pD1VcTR-nQivkaQ7pUNgR_hZRJXyEmmwZej7Y1yekMI)
> 
> 麻烦传份度盘？我这边上不了googledriver
> 
> @HelloTheAsia 试一下？

这边暂时上传去奶牛了，下载后把删除我的字删掉解压有4个文件，一个镜像，一个写入工具，两个说明文件：https://cowtransfer.com/s/73b4dd4cd1e34b

**Comment by LSP0123** [comment]
等@HelloTheAsia 看看吧，虽然我也不知道他搞不，不过硬解码他倒是做了的

**Comment by LSP0123** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31061624/b655a430-da3b-4a4b-96c0-28eca0e3c239)
这个dtb里pcie也是关闭的，你真的确认这个板子是有把rk3566的pcie针脚都引出来了么

**Comment by FusionPlmH** [comment]
> ![image](https://private-user-images.githubusercontent.com/31061624/303905186-b655a430-da3b-4a4b-96c0-28eca0e3c239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDA4NzYsIm5iZiI6MTcwNzY0MDU3NiwicGF0aCI6Ii8zMTA2MTYyNC8zMDM5MDUxODYtYjY1NWE0MzAtZGEzYi00YTRiLTk2YzAtMjhlY2EwZTNjMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjExVDA4MzYxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YjRiNzY4Y2IyYTg5MGE0ZTJhODI2YThiOWExOTFiZTRkMzk0OWE2M2Y3YjUzMjg0YmMzMTA2NDUyNDc4NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LmkJqf9OSSlmERJ3P3mzd0KeKVP6Ms4LHS1CmQqsy_M) 这个dtb里pcie也是关闭的，你真的确认这个板子是有把rk3566的pcie针脚都引出来了么

我在意的是usb协议就好了，本来不打算是pcie的

**Comment by LSP0123** [comment]
/* mini pcie */
&pcie2x1 {
    reset-gpios = <&gpio3 RK_PC1 GPIO_ACTIVE_HIGH>;
    disable-gpios = <&gpio3 RK_PC2 GPIO_ACTIVE_HIGH>;
    vpcie3v3-supply = <0x22>;

};



找不到gpio3的RK_PC1 GPIO_ACTIVE_HIGH定义啊

**Comment by succesor** [comment]
[PS_WMDS-183-SX1302_BQW_01_0010.002.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/14327381/PS_WMDS-183-SX1302_BQW_01_0010.002.pdf)
该LoraWan的参考图

**Comment by caigooo** [comment]
> ![image](https://private-user-images.githubusercontent.com/31061624/303905186-b655a430-da3b-4a4b-96c0-28eca0e3c239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDk0NjQsIm5iZiI6MTcwOTMwOTE2NCwicGF0aCI6Ii8zMTA2MTYyNC8zMDM5MDUxODYtYjY1NWE0MzAtZGEzYi00YTRiLTk2YzAtMjhlY2EwZTNjMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE2MDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMDFkNWM2OTVkZDZjNTllNzFlODI4OWJkODgwMDQxNjcyODE4MzJlMmVhYTAwY2EyMDY0ZGI5MTc4YjJhODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._n3gxpz_yatj0PUQT6MJN4FYZkZmeijhRlLlXUz_p-c) 这个dtb里pcie也是关闭的，你真的确认这个板子是有把rk3566的pcie针脚都引出来了么

大部分的引脚都是直通CPU的，USB+-也是有的，1、2、5、7、11、13、15针脚还没确定下来，PCB板上看不到。

**Comment by caigooo** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/31061624/303905186-b655a430-da3b-4a4b-96c0-28eca0e3c239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDk0NjQsIm5iZiI6MTcwOTMwOTE2NCwicGF0aCI6Ii8zMTA2MTYyNC8zMDM5MDUxODYtYjY1NWE0MzAtZGEzYi00YTRiLTk2YzAtMjhlY2EwZTNjMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE2MDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMDFkNWM2OTVkZDZjNTllNzFlODI4OWJkODgwMDQxNjcyODE4MzJlMmVhYTAwY2EyMDY0ZGI5MTc4YjJhODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._n3gxpz_yatj0PUQT6MJN4FYZkZmeijhRlLlXUz_p-c) 这个dtb里pcie也是关闭的，你真的确认这个板子是有把rk3566的pcie针脚都引出来了么
> > 
> > 
> > 大部分的引脚都是直通CPU的，USB+-也是有的，1、2、5、7、11、13、15针脚还没确定下来，PCB板上看不到。
> 
> 重点是2的来源，这个定义我算的数值很奇怪，感觉超出gpio的界限了，RK_PC1 GPIO_ACTIVE_HIGH

我写错了，2脚是3.3V 常电。

**Comment by caigooo** [comment]
> > > ![image](https://private-user-images.githubusercontent.com/31061624/303905186-b655a430-da3b-4a4b-96c0-28eca0e3c239.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzMDk0NjQsIm5iZiI6MTcwOTMwOTE2NCwicGF0aCI6Ii8zMTA2MTYyNC8zMDM5MDUxODYtYjY1NWE0MzAtZGEzYi00YTRiLTk2YzAtMjhlY2EwZTNjMjM5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAxVDE2MDYwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMDFkNWM2OTVkZDZjNTllNzFlODI4OWJkODgwMDQxNjcyODE4MzJlMmVhYTAwY2EyMDY0ZGI5MTc4YjJhODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._n3gxpz_yatj0PUQT6MJN4FYZkZmeijhRlLlXUz_p-c) 这个dtb里pcie也是关闭的，你真的确认这个板子是有把rk3566的pcie针脚都引出来了么
> > 
> > 
> > 大部分的引脚都是直通CPU的，USB+-也是有的，1、2、5、7、11、13、15针脚还没确定下来，PCB板上看不到。
> 
> 重点是2的来源，这个定义我算的数值很奇怪，感觉超出gpio的界限了，RK_PC1 GPIO_ACTIVE_HIGH

![X2的mPCIE](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/4d9f491a-80a2-40f8-86da-9ef4730fc9e9)

**Comment by caigooo** [comment]
我把pcie图片都发上来
![X2的mPCIE](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/4db9a04e-f40f-4c24-aeb9-ed4a8684e220)
![X2miniPCIE1-51](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/5aeb19f2-cd77-4527-9d02-9eb85f2e6476)
![X2miniPCIE2-52](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/6afd93e5-c889-4800-9efe-b9dc302738a0)
![X2miniPCIE背面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/341b545a-285c-424a-9fde-d74d0f6b1dd3)

**Comment by caigooo** [comment]
SX1302的金手指，还有 miniPCIE转M.2 mkey的转接板 金手指。具体针脚看上面的对比图
![SX1302 正面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/18acd63b-ff98-44f3-9e78-f041d5c677cf)

![SX1302 背面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/e1052da9-65b3-4037-af31-f38760bf1ea2)
![miniPCIe转M2mkey 正面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/094f58d6-6018-4db4-ad6c-32e541e9f920)
![miniPCIe转M2mkey 背面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/8e1e20ac-258c-4909-aa7b-fb233fa05fdb)

**Comment by CraKeyBoy** [comment]
之前看过minipcie 转 USB3.0 的接口卡，6 以上的 kernel 应该已经支持。
资料：
[r19uh0078ej0710-usb.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/14565960/r19uh0078ej0710-usb.pdf)
![21201710206085_ pic](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1518543/c7fb4389-000a-4528-b5bb-83b2ee48c864)

**Comment by caigooo** [comment]
> 之前看过minipcie 转 USB3.0 的接口卡，6 以上的 kernel 应该已经支持。 资料： [r19uh0078ej0710-usb.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/14565960/r19uh0078ej0710-usb.pdf) ![21201710206085_ pic](https://private-user-images.githubusercontent.com/1518543/311907923-c7fb4389-000a-4528-b5bb-83b2ee48c864.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTUzMDUsIm5iZiI6MTcxMDIxNTAwNSwicGF0aCI6Ii8xNTE4NTQzLzMxMTkwNzkyMy1jN2ZiNDM4OS0wMDBhLTQ1MjgtYjViYi04M2IyZWU0OGM4NjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDM0MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgwMzQ0NWE0Njc0NGQ2MzM4NzFkYWVmM2Q3ZjA5OGExZjk4ZWRkNWRlNmMxYmFhZTMxODllZjNlNjZlZWFkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Uss418ehTJJ9c6qAJQz_HkukYjb_iVCA7UMJblgV35s)

现在的问题是，minipcie 有缺引脚，不是完整的PCIE接口，如果是完整的PCIE接口，这个就能转换成比较多的设备了。
不过话说回来，这个minipcie转USB3.0的，估计一个转换模块都顶得上X2这个主机了 T_T

**Comment by CraKeyBoy** [comment]
> > 之前看过minipcie 转 USB3.0 的接口卡，6 以上的 kernel 应该已经支持。 资料： [r19uh0078ej0710-usb.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/14565960/r19uh0078ej0710-usb.pdf) ![21201710206085_ pic](https://private-user-images.githubusercontent.com/1518543/311907923-c7fb4389-000a-4528-b5bb-83b2ee48c864.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMTUzMDUsIm5iZiI6MTcxMDIxNTAwNSwicGF0aCI6Ii8xNTE4NTQzLzMxMTkwNzkyMy1jN2ZiNDM4OS0wMDBhLTQ1MjgtYjViYi04M2IyZWU0OGM4NjQuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDM0MzI1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODgwMzQ0NWE0Njc0NGQ2MzM4NzFkYWVmM2Q3ZjA5OGExZjk4ZWRkNWRlNmMxYmFhZTMxODllZjNlNjZlZWFkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.Uss418ehTJJ9c6qAJQz_HkukYjb_iVCA7UMJblgV35s)
> 
> 现在的问题是，minipcie 有缺引脚，不是完整的PCIE接口，如果是完整的PCIE接口，这个就能转换成比较多的设备了。 不过话说回来，这个minipcie转USB3.0的，估计一个转换模块都顶得上X2这个主机了 T_T

淘宝上有，不到这个机器的一半价格可以搞定。
