### ISSUE TITLE
M401a armbian系统怎么安装xface桌面

### ISSUE THREAD

**Issue by congming543** [ophub/amlogic-s9xxx-armbian#2032]
新刷的5.1的包发现桌面已经成gnome桌面，鼠标闪烁、区域闪烁严重，求个其他桌面的安装方法，我测试安装了几个都无法进系统

**Comment by zengfr** [comment]
https://github.com/zengfr/armbian-ubuntu-scripts/blob/main/install-gui-mini.sh
