### ISSUE TITLE
cm311-1aYST(s905l3a)刷不进去

### ISSUE THREAD

**Issue by zqs2020git** [ophub/amlogic-s9xxx-armbian#2033]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - Model [e.g. CM311-1a YST]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.69]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
rufus写入u盘后，u盘插入盒子上电，显示器背光量，然后一直卡住，没有跑马，重复多次，偶尔有直接进入机器系统的，没有启动u盘系统，内核5.15.145的镜像是可以进入u盘系统然后刷入的，看了下6.1.69 boot目录下多了个u-boot.ext文件，删除了这个问题依旧，不知道是什么原因

**Comment by ophub** [comment]
看文档，如何从U盘启动的说明
