### ISSUE TITLE
Please help with X96MAX plus T support 

### ISSUE THREAD

**Issue by 4tomson** [ophub/amlogic-s9xxx-armbian#2034]
**Device Information | 设备信息**
 - SOC: [S905x3]
 - Model [X96Max+ T]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1]
 - Release: [bookworm]

It's a version of x96maxplusT with 1000М Ethernet RTL8211F, AM7256  - WiFi 2.4 + 5, BT
I'm using meson-sm1-x96-air-gbit.dtb and almost all  working , but BT dont work
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac4354-sdio for chip BCM4354/1[    9.681714] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac4354-sdio.amediatech,x96-air-gbit.bin failed with error -2

**Comment by 4tomson** [comment]
![IMG_20210607_191247](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75882358/21fd6f4c-6d97-425d-82c7-7aedb99023f0)

**Comment by ophub** [comment]
armbian-config install BT

**Comment by 4tomson** [comment]
Yes, i know, i'm already using your firmware on another box with working Bluetooth
Hci0 present in system, but doesn't work.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/blob/7becee7783dabd9d68eafb7920c653ecbb222a8e/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus-ip1001m.dts#L39

https://github.com/unifreq/linux-6.1.y/blob/7becee7783dabd9d68eafb7920c653ecbb222a8e/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus-ip1001m-2.dts#L39

AM7256 is added to these two dtbs. You change the dtb in armbianEnv.txt and restart the test.
Or refer to this to modify your dtb. The kernel compilation method is in the repo.

**Comment by 4tomson** [comment]
please tell me in more detail how can I create a dtd by taking RTL8211F support from one file and AM7256 from another? I understand in general terms, but I don't have enough experience

**Comment by ophub** [comment]
1. You change the dtb in armbianEnv.txt and restart the test.

2. Modify the current DTS to include the code for sending the Bluetooth driver to you, and then compile it. Refer to the repository documentation for the compilation method.

**Comment by 4tomson** [comment]
Pleaser check my files and may be add to official support?
[meson-sm1-x96-max-plus-t.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/13978614/meson-sm1-x96-max-plus-t.zip)

**Comment by 4tomson** [comment]
10.549213] Bluetooth: hci0: BCM: chip id 92
[   10.552363] Bluetooth: hci0: BCM: features 0x2f
[   10.556645] Bluetooth: hci0: BCM4350C0
[   10.559102] Bluetooth: hci0: BCM4354 (003.001.012) build 0000
[   10.564693] Bluetooth: hci0: BCM: firmware Patch file not found, tried:
[   10.570805] Bluetooth: hci0: BCM: 'brcm/BCM4354.x96-max-plus-q2,x96-air-q1000.hcd'
[   10.578284] Bluetooth: hci0: BCM: 'brcm/BCM4354.hcd'
[   10.583179] Bluetooth: hci0: BCM: 'brcm/BCM.x96-max-plus-q2,x96-air-q1000.hcd'
[   10.590358] Bluetooth: hci0: BCM: 'brcm/BCM.hcd'

But bluetooth is works fine!

**Comment by 4tomson** [comment]
armbian:d:# rfkill
ID TYPE      DEVICE      SOFT      HARD
 0 wlan      phy0   unblocked unblocked
 1 bluetooth hci0   unblocked unblocked
 2 bluetooth hci1   unblocked unblocked

What is hci1? How can i delete hci1?

**Comment by 4tomson** [comment]
hciconfig
hci1:   Type: Primary  Bus: SDIO
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:0 acl:0 sco:0 commands:0 errors:0

hci0:   Type: Primary  Bus: UART
        BD Address: 49:32:55:9B:8A:D5  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:1793 acl:0 sco:0 events:95 errors:0
        TX bytes:3935 acl:0 sco:0 commands:95 errors:0
