### ISSUE TITLE
DG3399无法使用ttyS4串口

### ISSUE THREAD

**Issue by Leo2442926161** [ophub/amlogic-s9xxx-armbian#2038]
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [DG3399]

**Armbian Version | 系统版本**
Armbian 23.08.0-trunk Lunar with Linux 6.1.52-ophub

**Describe the bug | 问题描述**
使用ttyS4时会提示写IO错误，目前需要用到这个串口；
PS: 我试过在ubuntu的系统下可以使用该串口

```
root@armbian:~# echo "hello" >> /dev/ttyS4
-bash: echo: write error: Input/output error
```

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/30258768/de7813eb-d6c6-4ad5-ade0-e17d8ae92e1d)

**Comment by 13584452567** [comment]
使用statserial命令检查串口状态。这个报错普遍出现于串口离线，例如路径写错。

**Comment by Leo2442926161** [comment]
@13584452567  感谢回复

**Comment by 13584452567** [comment]
> @13584452567  感谢回复，statserial也无法使用
> 
> 
> root@armbian:~# statserial
> statserial: TIOCMGET failed: Input/output error
> root@armbian:~# statserial
> statserial: TIOCMGET failed: Input/output error

statserial后面需要设备路径，你没有指定设备。

**Comment by Leo2442926161** [comment]
@13584452567  提示也是一样的

root@armbian:~# statserial /dev/tty
tty      tty12    tty17    tty21    tty26    tty30    tty35    tty4     tty44    tty49    tty53    tty58    tty62    ttyS1
tty0     tty13    tty18    tty22    tty27    tty31    tty36    tty40    tty45    tty5     tty54    tty59    tty63    ttyS2
tty1     tty14    tty19    tty23    tty28    tty32    tty37    tty41    tty46    tty50    tty55    tty6     tty7     ttyS3
tty10    tty15    tty2     tty24    tty29    tty33    tty38    tty42    tty47    tty51    tty56    tty60    tty8     ttyS4
tty11    tty16    tty20    tty25    tty3     tty34    tty39    tty43    tty48    tty52    tty57    tty61    tty9     ttyUSB0
root@armbian:~# statserial /dev/ttyS
ttyS1  ttyS2  ttyS3  ttyS4
root@armbian:~# statserial /dev/ttyS4
statserial: TIOCMGET failed: Input/output error

**Comment by 13584452567** [comment]
setserial -g /dev/ttyS*
看下输出

**Comment by Leo2442926161** [comment]
root@armbian:~# setserial -g /dev/ttyS*
/dev/ttyS1, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS2, UART: 16550A, Port: 0x0000, IRQ: 38
/dev/ttyS3, UART: unknown, Port: 0x0000, IRQ: 0
/dev/ttyS4, UART: unknown, Port: 0x0000, IRQ: 0

**Comment by 13584452567** [comment]
dmesg | egrep -i 'serial|ttys'
ls -l /dev/tty*  
tail -f /var/log/syslog  
lsmod | grep serial
看看输出，我预感是用户空间驱动的问题

**Comment by Leo2442926161** [comment]
> dmesg | egrep -i 'serial|ttys' ls -l /dev/tty* tail -f /var/log/syslog lsmod | grep serial 看看输出，我预感是用户空间驱动的问题

```
root@armbian:~# dmesg | egrep -i 'serial|ttys'
root@armbian:~# ls -l /dev/tty*
crw-rw-rw- 1 root tty       5,  0 Jan 20 15:17 /dev/tty
crw--w---- 1 root tty       4,  0 Jan 20 15:17 /dev/tty0
crw--w---- 1 root tty       4,  1 Jan 20 15:17 /dev/tty1
crw--w---- 1 root tty       4, 10 Jan 20 15:17 /dev/tty10
crw--w---- 1 root tty       4, 11 Jan 20 15:17 /dev/tty11
crw--w---- 1 root tty       4, 12 Jan 20 15:17 /dev/tty12
crw--w---- 1 root tty       4, 13 Jan 20 15:17 /dev/tty13
crw--w---- 1 root tty       4, 14 Jan 20 15:17 /dev/tty14
crw--w---- 1 root tty       4, 15 Jan 20 15:17 /dev/tty15
crw--w---- 1 root tty       4, 16 Jan 20 15:17 /dev/tty16
crw--w---- 1 root tty       4, 17 Jan 20 15:17 /dev/tty17
crw--w---- 1 root tty       4, 18 Jan 20 15:17 /dev/tty18
crw--w---- 1 root tty       4, 19 Jan 20 15:17 /dev/tty19
crw--w---- 1 root tty       4,  2 Jan 20 15:17 /dev/tty2
crw--w---- 1 root tty       4, 20 Jan 20 15:17 /dev/tty20
crw--w---- 1 root tty       4, 21 Jan 20 15:17 /dev/tty21
crw--w---- 1 root tty       4, 22 Jan 20 15:17 /dev/tty22
crw--w---- 1 root tty       4, 23 Jan 20 15:17 /dev/tty23
crw--w---- 1 root tty       4, 24 Jan 20 15:17 /dev/tty24
crw--w---- 1 root tty       4, 25 Jan 20 15:17 /dev/tty25
crw--w---- 1 root tty       4, 26 Jan 20 15:17 /dev/tty26
crw--w---- 1 root tty       4, 27 Jan 20 15:17 /dev/tty27
crw--w---- 1 root tty       4, 28 Jan 20 15:17 /dev/tty28
crw--w---- 1 root tty       4, 29 Jan 20 15:17 /dev/tty29
crw--w---- 1 root tty       4,  3 Jan 20 15:17 /dev/tty3
crw--w---- 1 root tty       4, 30 Jan 20 15:17 /dev/tty30
crw--w---- 1 root tty       4, 31 Jan 20 15:17 /dev/tty31
crw--w---- 1 root tty       4, 32 Jan 20 15:17 /dev/tty32
crw--w---- 1 root tty       4, 33 Jan 20 15:17 /dev/tty33
crw--w---- 1 root tty       4, 34 Jan 20 15:17 /dev/tty34
crw--w---- 1 root tty       4, 35 Jan 20 15:17 /dev/tty35
crw--w---- 1 root tty       4, 36 Jan 20 15:17 /dev/tty36
crw--w---- 1 root tty       4, 37 Jan 20 15:17 /dev/tty37
crw--w---- 1 root tty       4, 38 Jan 20 15:17 /dev/tty38
crw--w---- 1 root tty       4, 39 Jan 20 15:17 /dev/tty39
crw--w---- 1 root tty       4,  4 Jan 20 15:17 /dev/tty4
crw--w---- 1 root tty       4, 40 Jan 20 15:17 /dev/tty40
crw--w---- 1 root tty       4, 41 Jan 20 15:17 /dev/tty41
crw--w---- 1 root tty       4, 42 Jan 20 15:17 /dev/tty42
crw--w---- 1 root tty       4, 43 Jan 20 15:17 /dev/tty43
crw--w---- 1 root tty       4, 44 Jan 20 15:17 /dev/tty44
crw--w---- 1 root tty       4, 45 Jan 20 15:17 /dev/tty45
crw--w---- 1 root tty       4, 46 Jan 20 15:17 /dev/tty46
crw--w---- 1 root tty       4, 47 Jan 20 15:17 /dev/tty47
crw--w---- 1 root tty       4, 48 Jan 20 15:17 /dev/tty48
crw--w---- 1 root tty       4, 49 Jan 20 15:17 /dev/tty49
crw--w---- 1 root tty       4,  5 Jan 20 15:17 /dev/tty5
crw--w---- 1 root tty       4, 50 Jan 20 15:17 /dev/tty50
crw--w---- 1 root tty       4, 51 Jan 20 15:17 /dev/tty51
crw--w---- 1 root tty       4, 52 Jan 20 15:17 /dev/tty52
crw--w---- 1 root tty       4, 53 Jan 20 15:17 /dev/tty53
crw--w---- 1 root tty       4, 54 Jan 20 15:17 /dev/tty54
crw--w---- 1 root tty       4, 55 Jan 20 15:17 /dev/tty55
crw--w---- 1 root tty       4, 56 Jan 20 15:17 /dev/tty56
crw--w---- 1 root tty       4, 57 Jan 20 15:17 /dev/tty57
crw--w---- 1 root tty       4, 58 Jan 20 15:17 /dev/tty58
crw--w---- 1 root tty       4, 59 Jan 20 15:17 /dev/tty59
crw--w---- 1 root tty       4,  6 Jan 20 15:17 /dev/tty6
crw--w---- 1 root tty       4, 60 Jan 20 15:17 /dev/tty60
crw--w---- 1 root tty       4, 61 Jan 20 15:17 /dev/tty61
crw--w---- 1 root tty       4, 62 Jan 20 15:17 /dev/tty62
crw--w---- 1 root tty       4, 63 Jan 20 15:17 /dev/tty63
crw--w---- 1 root tty       4,  7 Jan 20 15:17 /dev/tty7
crw--w---- 1 root tty       4,  8 Jan 20 15:17 /dev/tty8
crw--w---- 1 root tty       4,  9 Jan 20 15:17 /dev/tty9
crw-rw---- 1 root dialout   4, 65 Jan 20 15:17 /dev/ttyS1
crw-rw---- 1 root dialout   4, 66 Jan 25 15:35 /dev/ttyS2
crw-rw---- 1 root dialout   4, 67 Jan 20 15:17 /dev/ttyS3
crw-rw---- 1 root dialout   4, 68 Jan 20 15:17 /dev/ttyS4
crw-rw---- 1 root dialout 188,  0 Jan 25  2024 /dev/ttyUSB0
root@armbian:~# lsmod | grep serial

```


我装了些其他应用在里面，syslog 信息有点多，但是没有serial相关的信息在里面。

**Comment by 13584452567** [comment]
你对于这个ttyUSB0有什么头绪吗？它可能就是你想找的S4？

**Comment by 13584452567** [comment]
> ttyUSB0 是我插在USB上的USB2TTL，目前我还需要一个串口，所以想用ttyS4, 但是armbian不支持，我用烧录其他镜像S4是可以用的

如果本仓库的ubuntu下可以使用ttyS4的话，可能是debian的软件包有缺失。这需要对比两个系统对应的软件包列表了。
不是非要debian系统的话，先ubuntu凑活一下？
你后面空了可以再去研究这个问题。

**Comment by Leo2442926161** [comment]
目前需求是使用armbian, 我有其他rk3399在跑ubuntu，使用S4是正常的；

对于丢失的包，是需要重新编译Armbian吗？有没有可能驱动本身就没有支持。

**Comment by 13584452567** [comment]
你说的ubuntu是板子的官方镜像吗？armbian是项目名称，具体到发行版有debian和ubuntu两种。

**Comment by Leo2442926161** [comment]
> 你说的ubuntu是板子的官方镜像吗？armbian是项目名称，具体到发行版有debian和ubuntu两种。

是的，我烧录的是官方板子的ubuntu固件。

目前有些应用需要依赖armbian的debian，ubuntu版本没有试。

USB tty跟本身串口设备树不关联的，有可能可能设备树中禁止了ttyS4

**Comment by 13584452567** [comment]
> > 你说的ubuntu是板子的官方镜像吗？armbian是项目名称，具体到发行版有debian和ubuntu两种。
> 
> 是的，我烧录的是官方板子的ubuntu固件。
> 
> 目前有些应用需要依赖armbian的debian，ubuntu版本没有试。
> 
> USB tty跟本身串口设备树不关联的，有可能可能设备树中禁止了ttyS4

这样的话，应该是主线内核驱动有缺失。如果是这个问题的话，要么自己动手，要么指望上游了。国内厂商好像都不喜欢把自己的设备支持推送到上游，估计等的希望渺茫。我手头并没有DG3399，你只能自己想办法研究串口的支持了。


依赖什么呢？ubuntu固件是可以不更新内核更新系统版本的，我之前测试的4.19内核可以更新到ubuntu22.04，如果依赖不是内核而是文件系统的某一个部分可以考虑一下升级ubuntu版本。


该仓库所使用的设备树内并未发现有关禁止tty的代码

**Comment by Leo2442926161** [comment]
好的，谢谢！我再研究下

方便加个微信交流吗？xiebin2442926161

**Comment by 13584452567** [comment]
> 好的，谢谢！我再研究下
> 
> 方便加个微信交流吗？xiebin2442926161

抱歉，我没有微信。

你要是跟仓库有关的不清楚的发issues或者discussions吧，rockchip相关的问题我要是看到了会回答的。

**Comment by Leo2442926161** [comment]
@13584452567  Thanks.

再请问下：
1. armbian如何只编译ubuntu并生成烧录固件？是不是也可以用类似 rockchip提供的build.sh只编译kernel这些，自己添加相关驱动进去？ 因为对armbian还不是很熟，不知道如何去编译。
2. 通常像ttyS*无法使用的问题，有没有可能对应的ttyS*被占用导致？
3.  通常像ttyS*无法使用，如果驱动已经支持，一般可能需要更新什么包？
4. 您指的discussions是本仓库的discussions吗？

**Comment by 13584452567** [comment]
> @13584452567  Thanks.
> 
> 再请问下：
> 1. armbian如何只编译ubuntu并生成烧录固件？是不是也可以用类似 rockchip提供的build.sh只编译kernel这些，自己添加相关驱动进去？ 因为对armbian还不是很熟，不知道如何去编译。
> 2. 通常像ttyS*无法使用的问题，有没有可能对应的ttyS*被占用导致？
> 3.  通常像ttyS*无法使用，如果驱动已经支持，一般可能需要更新什么包？
> 4. 您指的discussions是本仓库的discussions吗？
> 

1.参考仓库的文档
2.有可能，但是如果是占用，报错应该是设备繁忙而不是io错误
3.可能是对应设备的固件包，也可能是设备配置。具体要看ttl硬件的驱动组织形式
4.是的
