### ISSUE TITLE
斐讯N1刷入后无法启动

### ISSUE THREAD

**Issue by panana** [ophub/amlogic-s9xxx-armbian#204]
您好，我从U盘刷入EMMC后，显示成功，但重启后无法启动，只会进入Recovery界面，尝试了5.15与5.4两个内核版本（包名为：XXX_s905d_XXX），选项101与102都试过了，还是不行，请问是什么问题？

**Comment by ophub** [comment]
先刷回安卓系统，再刷armbian。
刷入时有两步选择都选了吗？

**Comment by panana** [comment]
刷回安卓后再刷就可以了，没注意这点，感谢。

**Comment by ophub** [comment]
好的
