### ISSUE TITLE
能否实现通过复位键，恢复预制的安装环境？

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2042]
能否实现通过复位键，恢复预制的安装环境？

主要是给别人用的，
把应用环境配好，软件装好，参数都设好，
如果系统乱了，或者IP设错了，
像家用路由器那样，恢复初始设定。

**Comment by ophub** [comment]
不能

**Comment by goldsoft8888** [comment]
谢谢老大回复， 还有个问题，我觉得T95 PLUS 还可以抢救下，国外出新版本的，6.1内核，提取引导文件应该就可以了

**Comment by ophub** [comment]
你可以USB试试

**Comment by goldsoft8888** [comment]
> 你可以USB试试

T95 PLUS 盒子只支持TF卡启动

**Comment by ophub** [comment]
那就tf试，不写入emmc对设备没有影响

**Comment by goldsoft8888** [comment]
> 那就tf试，不写入emmc对设备没有影响
国外那个固件是可以正常启动、运行的，我测试过了。但是它写EMMC与老大的不一样，也不知以后何时会升级，用老大的版本习惯了，更新也快

**Comment by LSP0123** [comment]
你可以写入tf卡，然后一切东西都在tf卡上配置，配置好了之后，把TF卡打包成img（dd命令），把img包给朋友就可以了，坏了就写一遍tf
