### ISSUE TITLE
表哥赚3pro该怎么刷，找了好久都没教程

### ISSUE THREAD

**Issue by Philae994** [ophub/amlogic-s9xxx-armbian#2043]
s912的通刷吗，这东西基本找不到教程，短接点也没找到，看人说复位键好像可以

**Comment by YouDianWeiLing** [comment]
你说的是玩客云pro吗，我看见好多刷点心云的了（咸鱼上面），估计快出来了

**Comment by chuixifeng** [comment]
已经出了 https://github.com/ophub/amlogic-s9xxx-armbian/pull/2241
