### ISSUE TITLE
可否匹配国科微处理器？

### ISSUE THREAD

**Issue by woshichenghaibo** [ophub/amlogic-s9xxx-armbian#2045]
北京移动等等很多处理器都是gk6323这种，内存还比较可以，都有2GB，但是找不到固件，好适配吗？

感谢！

**Comment by 13584452567** [comment]
需要你自行研究，包括uboot编译，主线dtb移植，刷机流程这三大块。

**Comment by cameronyq** [comment]
gk6323v100c的uboot自行编译后，开机并不起作用。

**Comment by MingTechpro** [comment]
> gk6323v100c的uboot自行编译后，开机并不起作用。

大佬，现在弄好了了么？我也想刷
