### ISSUE TITLE
UNT403A U盘启动跑码页面频繁报错

### ISSUE THREAD

**Issue by KevinLiu1995** [ophub/amlogic-s9xxx-armbian#2046]
**Device Information | 设备信息**
 - SOC: [S095L3A-B]

**Describe the bug | 问题描述**
U盘启动后尝试了两个USB3.0的U盘，一个U盘黑屏无限重启，另外一个U盘跑码循环报错如图，请问这个是什么原因？

**Comment by KevinLiu1995** [comment]
![图片_20240123002504](https://github.com/ophub/amlogic-s9xxx-armbian/assets/18683637/4bbb94c8-15bc-433c-82cc-170ba0b47c37)

**Comment by KevinLiu1995** [comment]
镜像搞错了

**Comment by KevinLiu1995** [comment]
![图片_20240123001806](https://github.com/ophub/amlogic-s9xxx-armbian/assets/18683637/594d69bb-5f02-4f4f-a17b-6fda51a194a3)

**Comment by KevinLiu1995** [comment]
更换5.15和USB口后解决

**Comment by buer23333** [comment]
> 交换5.15和USB口后解决

怎么解决，出现同样的问题

**Comment by KevinLiu1995** [comment]
> > 交换5.15和USB口后解决
> 
> 怎么解决，出现同样的问题

更换了5.15的镜像，然后把U盘换到了另外的USB口上解决了。

**Comment by buer23333** [comment]
> > > 交换5.15和USB口后解决
> > 
> > 
> > 怎么解决，出现同样的问题
> 
> 更换了5.15的镜像，然后把U盘换到另外的USB口上就解决了。

好的我试一下谢谢了

**Comment by KevinLiu1995** [comment]
图片没传上来，或者换一个U盘试试呢
