### ISSUE TITLE
cm311-1s yst 无法从u盘启动

### ISSUE THREAD

**Issue by m512106824** [ophub/amlogic-s9xxx-armbian#2051]
![1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/119643229/c913bff7-87d8-4542-b183-d4b4aef72824)
请问这个型号是否已经支持

**Comment by ophub** [comment]
支持，设备支持情况可以查看仓库首页的设备列表和model列表。

**Comment by m512106824** [comment]
> 支持，设备支持情况可以查看仓库首页的设备列表和model列表。

amlogic_s905l3.img这个盒子用这个吗

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/cf24d5d35a9282c36bf73673fb55c73855cd543c/build-armbian/armbian-files/common-files/etc/model_database.conf#L116

没有的可以拿现在的改/boot/uEnv.txt里的dtb名字，或者自己fork编译一个。

**Comment by m512106824** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/cf24d5d35a9282c36bf73673fb55c73855cd543c/build-armbian/armbian-files/common-files/etc/model_database.conf#L116
> 
> 没有的可以拿现在的改/boot/uEnv.txt里的dtb名字，或者自己fork编译一个。

那你高看我了，我只会用现成的...

**Comment by ophub** [comment]
有中文版文档，一看就会，动动你的金手指点点就有了。

**Comment by m512106824** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian/blob/cf24d5d35a9282c36bf73673fb55c73855cd543c/build-armbian/armbian-files/common-files/etc/model_database.conf#L116
> > 
> > 没有的可以拿现在的改/boot/uEnv.txt里的dtb名字，或者自己fork编译一个。
> 
> 那你高看我了，我只会用现成的...

这一行改成什么样啊？meson-g12a-s905l3a-cm311-1s.dtb？

**Comment by itlaohuo** [comment]
我的经验是：
1 我128G的优盘写启动盘后校验过程中失败（不是rufus工具，rufus工具不提示，是文档中的另外一款刷的时候才提示的），换了一个8G的才OK
2 安卓底包没办法开启adb等调式模式，安装了一个 reboot_update_xxxx.apk包，然后运行才能从U盘启动。

**Comment by m512106824** [comment]
> 我的经验是： 1 我128G的优盘写启动盘后校验过程中失败（不是rufus工具，rufus工具不提示，是文档中的另外一款刷的时候才提示的），换了一个8G的才OK 2 安卓底包没办法开启adb等调式模式，安装了一个 reboot_update_xxxx.apk包，然后运行才能从U盘启动。
> 
> 备注： 我的是ZXB860AV-3.2M

我用了俩U盘，我听大佬的意思是我的设备虽然支持，但是还没到拿来就用的地步，需要稍微操作一下

**Comment by LSP0123** [comment]
> > > https://github.com/ophub/amlogic-s9xxx-armbian/blob/cf24d5d35a9282c36bf73673fb55c73855cd543c/build-armbian/armbian-files/common-files/etc/model_database.conf#L116
> > > 
> > > 没有的可以拿现在的改/boot/uEnv.txt里的dtb名字，或者自己fork编译一个。
> > 
> > 
> > 那你高看我了，我只会用现成的...
> 
> 这一行改成什么样啊？meson-g12a-s905l3a-cm311-1s.dtb？

提取你这个机子的DTB文件，然后拿你提取的DTB替换镜像里的，再去写盘安装

**Comment by m512106824** [comment]
> > > > https://github.com/ophub/amlogic-s9xxx-armbian/blob/cf24d5d35a9282c36bf73673fb55c73855cd543c/build-armbian/armbian-files/common-files/etc/model_database.conf#L116
> > > > 
> > > > 没有的可以拿现在的改/boot/uEnv.txt里的dtb名字，或者自己fork编译一个。
> > > 
> > > 
> > > 那你高看我了，我只会用现成的...
> > 
> > 
> > 这一行改成什么样啊？meson-g12a-s905l3a-cm311-1s.dtb？
> 
> 提取你这个机子的DTB文件，然后拿你提取的DTB替换镜像里的，再去写盘安装

具体路径能大概说一下？机子文件？需要到机子提取？原img打不开，替换的文件名是哪个

**Comment by ophub** [comment]
直接用，不用改。
你先把仓库的文档看一遍再玩，省的折腾弯路。

**Comment by m512106824** [comment]
> 直接用，不用改。 你先把仓库的文档看一遍再玩，省的折腾弯路。

收到，我去学习

**Comment by m512106824** [comment]
> > 直接用，不用改。 你先把仓库的文档看一遍再玩，省的折腾弯路。
> 
> 收到，我去学习

没找到无法u盘启动原因

**Comment by ophub** [comment]
看12.4

**Comment by m512106824** [comment]
> 看12.4

看了，connet可以连接成功，但是update命令后重启盒子有启动画面然后黑屏，大佬我这个盒子对应的是哪个img啊？后续我该怎么办

**Comment by ophub** [comment]
启动黑屏就对了，这个盒子没HDMI，去设备接入的路由器里找设备名字是armbian的ip，使用ssh连接，默认账号密码root，1234
