### ISSUE TITLE
请求一个可用的USB-WiFi网卡

### ISSUE THREAD

**Issue by tianxiaodu** [ophub/amlogic-s9xxx-armbian#2054]
**Device Information | 设备信息**
 - SOC: [Amlogic-s905L3a]
 - Model [cm311-1sa-yst]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.145]
 - Release: [ jammy]

**Describe the bug | 问题描述**
板载网卡为5621ds不识别，想在网上买一个USB-WiFi网卡
不知道买哪个，担心花钱买回来不支持，请求提供一个支持的可用的USB-WiFi网卡型号
能携带蓝牙更好，一并请求该型号的安装命令

**Comment by ophub** [comment]
mtk或ralink的，mt7601u既便宜也稳定，不过只是单频2.4g的，如果要双频的话可以选mt7610u

选择范围可以在内核里查看，有驱动的就可以。
https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless
