### ISSUE TITLE
E900V22D-2（S905L3）刷入成功，+TF卡槽成功

### ISSUE THREAD

**Issue by Cp0204** [ophub/amlogic-s9xxx-armbian#2058]
## 设备信息
 - SOC: S905L3
 - Model: E900V22D-2
 - 2+8 GB

已知该设备是陕西地区的E900V22D，但使用的是S905L3（并非A-B类型，目前不在README列表中），该设备 @by-JohnChen 曾经分享过 https://github.com/ophub/amlogic-s9xxx-armbian/issues/1903 但是言简意赅，信息较少，本次做补充完善。

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/20c2ff7a-ec92-4554-8325-d17a4131233b)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/49f4ac5c-7d10-44c4-ba9f-0d619caf902f)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/f150af78-c6cb-4810-8540-7fcf22f35d03)

## 测试情况

可以正确识别 2+8G ，**HDMI无信号。具体表现为开机引导时有输出，花屏一下，启动 armbian 后 HDMI 无输出。**

使用 by-JohnChen 的 dtb 也未能有 HDMI 输出。

实测以下镜像均成功，推测和 s905l3 的可以通刷：

- Armbian_24.2.0_amlogic_s905l3_bookworm_5.15.145_server_2024.01.01.img.gz
- Armbian_24.2.0_amlogic_s905l3_bookworm_6.6.13_server_2024.01.25.img.gz

未改 uEnv.txt ，用默认 meson-gxl-s905l2-x7-5g.dtb 可启动并刷入 EMMC 。

[加TF卡槽，64G SanDisk卡识别成功](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2058#issuecomment-1914784618)

## 刷入步骤

1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。

    ![短接点](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/2078e6d2-3f68-428b-a99d-e651337ab3a0)

2. 镜像写入U盘，插离开关最近的USB口；

3. **E900V22D-2插网线**，上电同时按遥控右键，**去路由器找到设备IP，用SSH登录**。

4. 刷入EMMC选择123，E900V22D机型

### 相关信息

- https://github.com/ophub/amlogic-s9xxx-armbian/issues/1903
- https://github.com/ophub/amlogic-s9xxx-armbian/issues/2003
- https://github.com/ophub/amlogic-s9xxx-armbian/issues/1561#issuecomment-1646731537

**Comment by ophub** [comment]
多谢分享，我今天添加到设备列表里

**Comment by Cp0204** [comment]
> 多谢分享，我今天添加到设备列表里

嗯嗯，谢谢大佬！更新了高清的主板图

**Comment by ophub** [comment]
120，122和123应该都可以，你USB启动用的是120

**Comment by Cp0204** [comment]
加TF卡槽，64G SanDisk卡识别成功

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/43424168-075e-4f7e-b09a-be72968882ac)

我的接法，属于参考普通版猜的，瞎猫碰上死耗子；

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/3c4e7b1d-5404-4aa8-b8cf-d9adc2969d2a)

**Comment by yuantao313** [comment]
> 1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。

请问经此步骤后无法进入U盘，那么第三步中如何引导进U盘系统呢？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

看12.14，如何从usb启动

**Comment by Cp0204** [comment]
> > 1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。
> 
> 请问经此步骤后无法进入U盘，那么第三步中如何引导进U盘系统呢？

没有有效信息，无法帮你判断问题。
进行了什么操作，无法进入是什么表现，例如：HDMI有无显示？显示什么？路由器有无IP？

我当时曾经一度以为启动失败，反复换包，后来发现原来 armbian 已经启动 只是 HDMI 不显示。

**Comment by by-JohnChen** [comment]
> > > 1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。
> > 
> > 
> > 请问经此步骤后无法进入U盘，那么第三步中如何引导进U盘系统呢？
> 
> 没有有效信息，无法帮你判断问题。（描述） 进行了什么操作，无法进入是什么表现，例如：HDMI有无显示？显示什么？路由器有无IP？
> 
> 我的操作是刷安卓成功后，插U盘开机不断按遥控右键，就进入了U盘系统。 我当时曾经一度以为启动失败，反复换包，后来发现原来 armbian 已经启动 只是 HDMI 不显示。

设备树关于hdmi的部分配置可能不对，由于我搞机顶盒集群用的所以不需要图形化界面。那部分设备树代码没有修改U.U

**Comment by by-JohnChen** [comment]
把设备树中所有的c883a000
替换为d0042000试试
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/11454456/b93bc901-c43c-4822-a504-1c3cd64f7faa)

**Comment by yuantao313** [comment]
> > > > 1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。
> > > 
> > > 
> > > 请问经此步骤后无法进入U盘，那么第三步中如何引导进U盘系统呢？
> > 
> > 
> > 没有有效信息，无法帮你判断问题。（描述） 进行了什么操作，无法进入是什么表现，例如：HDMI有无显示？显示什么？路由器有无IP？
> > 我的操作是刷安卓成功后，插U盘开机不断按遥控右键，就进入了U盘系统。 我当时曾经一度以为启动失败，反复换包，后来发现原来 armbian 已经启动 只是 HDMI 不显示。
> 
> 设备树关于hdmi的部分配置可能不对，由于我搞机顶盒集群用的所以不需要图形化界面。那部分设备树代码没有修改U.U emmc，led部分是可以正常使用的方便我找设备

抱歉，之前没有阅读文档，通过apt进入安卓shell重启后就进入armbian了。
也希望能适配HDMI，对调试有一定帮助😀

**Comment by T1-ong** [comment]
还是进不去U盘里rambian系统，按了右键后，hdmi无信号，路由器也找不到盒子的IP

**Comment by NemoX0042** [comment]
> > > > > 1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。
> > > > 
> > > > 
> > > > 请问经此步骤后无法进入U盘，那么第三步中如何引导进U盘系统呢？
> > > 
> > > 
> > > 没有有效信息，无法帮你判断问题。（描述） 进行了什么操作，无法进入是什么表现，例如：HDMI有无显示？显示什么？路由器有无IP？
> > > 我的操作是刷安卓成功后，插U盘开机不断按遥控右键，就进入了U盘系统。 我当时曾经一度以为启动失败，反复换包，后来发现原来 armbian 已经启动 只是 HDMI 不显示。
> > 
> > 
> > 设备树关于hdmi的部分配置可能不对，由于我搞机顶盒集群用的所以不需要图形化界面。那部分设备树代码没有修改U.U emmc，led部分是可以正常使用的方便我找设备
> 
> 抱歉，之前没有阅读文档，通过apt进入安卓shell重启后就进入armbian了。 也希望能适配HDMI，对调试有一定帮助😀

我的也是创维E900V22D，soc是s905l-3，2+8版本。 刷了这个底包后可以进安卓系统 adb正常，U盘写入的是Armbian_24.5.0_amlogic_s905l3_jammy_6.1.87_server_2024.05.02.img，但是用`adb shell reboot update`后没办法进入armbian。

**Comment by 77160860** [comment]
> ## 设备信息
> * SOC: S905L3
> * Model: E900V22D-2
> * 2+8 GB
> 
> 已知该设备是陕西地区的E900V22D，但使用的是S905L3（并非A-B类型，目前不在README列表中），该设备 [@by-JohnChen](https://github.com/by-JohnChen) 曾经分享过 [#1903](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1903) 但是言简意赅，信息较少，本次做补充完善。
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/20c2ff7a-ec92-4554-8325-d17a4131233b) ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/49f4ac5c-7d10-44c4-ba9f-0d619caf902f) ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/f150af78-c6cb-4810-8540-7fcf22f35d03)
> 
> ## 测试情况
> 可以正确识别 2+8G ，**HDMI无信号。具体表现为开机引导时有输出，花屏一下，启动 armbian 后 HDMI 无输出。**
> 
> 使用 by-JohnChen 的 dtb 也未能有 HDMI 输出。
> 
> 实测以下镜像均成功，推测和 s905l3 的可以通刷：
> 
> * Armbian_24.2.0_amlogic_s905l3_bookworm_5.15.145_server_2024.01.01.img.gz
> * Armbian_24.2.0_amlogic_s905l3_bookworm_6.6.13_server_2024.01.25.img.gz
> 
> 未改 uEnv.txt ，用默认 meson-gxl-s905l2-x7-5g.dtb 可启动并刷入 EMMC 。
> 
> [加TF卡槽，64G SanDisk卡识别成功](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2058#issuecomment-1914784618)
> 
> ## 刷入步骤
> 1. 短接，USB_Burning_Tool 线刷安卓底包 [android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz)，不经过此步骤无法遥控右键进入U盘，反复启动一二屏，也可自测。
>    ![短接点](https://github.com/ophub/amlogic-s9xxx-armbian/assets/5239753/2078e6d2-3f68-428b-a99d-e651337ab3a0)
> 2. 镜像写入U盘，插离开关最近的USB口；
> 3. **E900V22D-2插网线**，上电同时按遥控右键，**去路由器找到设备IP，用SSH登录**。
> 4. 刷入EMMC选择123，E900V22D机型
> 
> ### 相关信息
> * [分享一个创维e900v22d-2的设备树文件 #1903](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1903)
> * [UNT400G hdmi没有显示信号输出 #2003](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2003)
> * [关于S905L3替换CPU的测试 #1561 (comment)](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1561#issuecomment-1646731537)

同款盒子 刷入你这个安卓底包按右键进不去u盘系统 开机卡屏  过一会就丢失hdmi的信号了

**Comment by cuicanmx** [comment]
e900v22d s905l3成功

**Comment by Dancergh** [comment]
将armbian系统刷入EMMC，没有显示信号输出，我该用哪个IP地址访问系统呢？使用u盘启动的ip不能访问，求大佬解答

**Comment by fancyzxz** [comment]
在宽带后台查看一下 aimbian 的 ip，用这个 ip 试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Dancergh ***@***.***&gt;
发送时间: 2025年3月8日 18:08
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: fancyzxz ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] E900V22D-2（S905L3）刷入成功，+TF卡槽成功 (Issue #2058)



   
将armbian系统刷入EMMC，没有显示信号输出，我该用哪个IP地址访问系统呢？使用u盘启动的ip不能访问，求大佬解答

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you commented.Message ID: ***@***.***&gt;
  Dancergh left a comment (ophub/amlogic-s9xxx-armbian#2058)
 
将armbian系统刷入EMMC，没有显示信号输出，我该用哪个IP地址访问系统呢？使用u盘启动的ip不能访问，求大佬解答

**Comment by Dancergh** [comment]
> 在宽带后台查看一下 aimbian 的 ip，用这个 ip 试试
> 
> 
> 
> 发自我的iPhone
> […](#)

那个IP地址，从U盘启动可以访问，拔出U盘，从机顶盒启动，访问不了，进不去

**Comment by NemoX0042** [comment]
> > 在宽带后台查看一下 aimbian 的 ip，用这个 ip 试试
> > 发自我的iPhone
> > […](#)
> 
> 那个IP地址，从U盘启动可以访问，拔出U盘，从机顶盒启动，访问不了，进不去

你已经在设备中运行`armbian-install`了么？https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#81-amlogic-%E7%B3%BB%E5%88%97%E5%AE%89%E8%A3%85%E6%96%B9%E6%B3%95
