### ISSUE TITLE
cryptography依赖安装不上

### ISSUE THREAD

**Issue by m512106824** [ophub/amlogic-s9xxx-armbian#2059]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/119643229/bcdc4230-8ae4-4eaa-ad90-4b096298d88e)
明明安装上了 为什么就是不能用呢
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/119643229/d4889471-3d67-4e94-ae47-4f01fd5f8060)
这是armbian的问题还是什么 ？请大佬们解惑
开始安装依赖 cryptography，开始时间 2024-01-29 16:45:02

Collecting cryptography
  Obtaining dependency information for cryptography from https://files.pythonhosted.org/packages/d8/41/1e2cfc14cdae6ad0b5c6677e2cb03af2a6e01c05a72d5b3fddf693b26f3d/cryptography-42.0.1-cp39-abi3-musllinux_1_2_aarch64.whl.metadata
  Using cached cryptography-42.0.1-cp39-abi3-musllinux_1_2_aarch64.whl.metadata (5.3 kB)
Collecting cffi>=1.12 (from cryptography)
  Using cached cffi-1.16.0.tar.gz (512 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Collecting pycparser (from cffi>=1.12->cryptography)
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Using cached cryptography-42.0.1-cp39-abi3-musllinux_1_2_aarch64.whl (4.5 MB)
Building wheels for collected packages: cffi
  Building wheel for cffi (pyproject.toml): started
  Building wheel for cffi (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [48 lines of output]
      
          No working compiler found, or bogus compiler options passed to
          the compiler from Python's standard "distutils" module.  See
          the error messages above.  Likely, the problem is not related
          to CFFI but generic to the setup.py of any Python package that
          tries to compile C code.  (Hints: on OS/X 10.8, for errors about
          -mno-fused-madd see http://stackoverflow.com/questions/22313407/
          Otherwise, see https://wiki.python.org/moin/CompLangPython or
          the IRC channel #python on irc.libera.chat.)
      
          Trying to continue anyway.  If you are trying to install CFFI from
          a build done in a different context, you can ignore this warning.
      
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/__init__.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/pkgconfig.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/_shimmed_dist_utils.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/ffiplatform.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/_imp_emulation.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/error.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/api.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/recompiler.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/vengine_cpy.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/cffi_opcode.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/lock.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/cparser.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/verifier.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/setuptools_ext.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/backend_ctypes.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/model.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/commontypes.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/vengine_gen.py -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/_cffi_include.h -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/parse_c_type.h -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/_embedding.h -> build/lib.linux-aarch64-cpython-311/cffi
      copying src/cffi/_cffi_errors.h -> build/lib.linux-aarch64-cpython-311/cffi
      running build_ext
      building '_cffi_backend' extension
      creating build/temp.linux-aarch64-cpython-311
      creating build/temp.linux-aarch64-cpython-311/src
      creating build/temp.linux-aarch64-cpython-311/src/c
      gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DFFI_BUILDING=1 -I/usr/include/ffi -I/usr/include/libffi -I/usr/local/include/python3.11 -c src/c/_cffi_backend.c -o build/temp.linux-aarch64-cpython-311/src/c/_cffi_backend.o
      error: command 'gcc' failed: No such file or directory
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for cffi
Failed to build cffi
ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects

依赖安装失败，结束时间 2024-01-29 16:45:41，耗时 39 秒

**Comment by 13584452567** [comment]
这个包是编译安装的，你的设备上没有找到gcc编译器。
使用这两条命令来安装GNU编译器合集。
sudo apt update
sudo apt install build-essential

**Comment by m512106824** [comment]
> 这个包是编译安装的，你的设备上没有找到gcc编译器。 使用这两条命令来安装GNU编译器合集。 sudo apt update sudo apt install build-essential

谢谢，我搞定了docker exec -it qinglong bash

apk add gcc g++ libffi-dev
留给需要的同志们
