### ISSUE TITLE
这个跟中国移动B860AV2.1-A是固件通用吗？

### ISSUE THREAD

**Issue by WalkingDead-Chen** [ophub/amlogic-s9xxx-armbian#2064]
这个跟中国移动B860AV-2.1A是固件通用吗？

_Originally posted by @WalkingDead-Chen in https://github.com/ophub/amlogic-s9xxx-armbian/issues/1598#issuecomment-1919019294_

**Comment by ophub** [comment]
usb测试一下，应该可以

**Comment by veltlion** [comment]
我最近也在弄这个盒子，B860AV2.1-A 的 SOC 是 S905L2B，用 e900v22e 的 dtb。写入 emmc 要把 max-frequency 改成 100000000 。

**Comment by hanguofu** [comment]
> 我最近也在弄这个盒子，B860AV2.1-A 的 SOC 是 S905L2B，用 e900v22e 的 dtb。写入 emmc 要把 max-frequency 改成 100000000 。

 请问楼上的老哥刷的是哪个版本啊 ？播放本地视频流畅吗 ？
