### ISSUE TITLE
从jammy升级到noble后，ssh登录仍提示为系统为jammy

### ISSUE THREAD

**Issue by LSP0123** [ophub/amlogic-s9xxx-armbian#2066]
**Device Information | 设备信息**
 - SOC: S905D
 - Model N1

**Armbian Version | 系统版本**
 - Kernel Version: 6.6.15
 - Release: jammy to noble

**Describe the bug | 问题描述**
通过修改source.list、apt dist-upgrade，将系统从jammy升级到noble
ssh登陆后仍提示如下：
`Welcome to Armbian OS 24.2.0 Jammy with Linux 6.6.15-happy-new-year`

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31061624/ec83e721-4b9e-4720-ad11-b334fe312bf9)

尝试armbian-fix修复无效

**Comment by LSP0123** [comment]
如果修改了codename的话，会提示
```
Welcome to Armbian OS 24.2.0 Noble with Linux 6.6.15-happy-new-year

No end-user support: unsupported (noble) userspace!
```
去掉下面的提示需要修改`/etc/armbian-distribution-status`里的`noble=csc`，将csc改为supported，就可以去掉了。

这个问题应该是armbian官方的，应该是还不是官方支持24.04。

**Comment by IYanHua** [comment]
apt包有jammy包没有更新到noble
