### ISSUE TITLE
tx3 mini 5.15.148 从哪里下载啊，6.的内核都是不断的重启

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2068]
tx3 mini 5.15.148 从哪里下载啊，6.的内核都是不断的重启

**Comment by goldsoft8888** [comment]
或者让6以上内核的固件能用也行啊

**Comment by LSP0123** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/kernel_stable
内核在这里，自己对着教程改一下
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#10-%E6%9B%B4%E6%96%B0-armbian-%E5%86%85%E6%A0%B8

TX3mini有两个版本的，提问的时候给出详细的信息

**Comment by goldsoft8888** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/kernel_stable 内核在这里，自己对着教程改一下 https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#10-%E6%9B%B4%E6%96%B0-armbian-%E5%86%85%E6%A0%B8
> 
> TX3mini有两个版本的，提问的时候给出详细的信息

所有6以上的版本启动时，都会自动重启

**Comment by LSP0123** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31061624/acf26ede-d0ae-4c2d-966c-95ed209de1e1)
都说了tx3mini有两个版本，你说的哪一个？soc不一样用的镜像当然不一样
为什么你不按照issue给的示例写上你的soc？描述清楚你的问题可以吗
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31061624/28d403c4-4b36-44d6-93f4-829937483962)
这个模板照着填很难么？

**Comment by goldsoft8888** [comment]
> ![image](https://private-user-images.githubusercontent.com/31061624/303958275-acf26ede-d0ae-4c2d-966c-95ed209de1e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzM3MjUsIm5iZiI6MTcwNzczMzQyNSwicGF0aCI6Ii8zMTA2MTYyNC8zMDM5NTgyNzUtYWNmMjZlZGUtZDBhZS00YzJkLTk2NmMtOTVlZDIwOWRlMWUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjODIyODk4MmJhZDNiZjBlYzgyOTkyNDRjM2JhM2RhZjAyZjU2NjQxODEwZDI3OGRhNTdhYmNjZmQyZGJlOGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.C9ecJ3BjbeFYtlowh7n1WfoNUXJED1Y91DoF5Y8YcVI)都说了tx3mini有两个版本，你说的哪一个？soc不一样用的镜像当然不一样 为什么你不按照issue给的示例写上你的soc？描述清楚你的问题可以吗 ![image](https://private-user-images.githubusercontent.com/31061624/303958355-28d403c4-4b36-44d6-93f4-829937483962.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3MzM3MjUsIm5iZiI6MTcwNzczMzQyNSwicGF0aCI6Ii8zMTA2MTYyNC8zMDM5NTgzNTUtMjhkNDAzYzQtNGIzNi00NGQ2LTkzZjQtODI5OTM3NDgzOTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEyVDEwMjM0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk3Y2M3OGRjYTlhOWMxMjVjMTI5ZmExNmU0Mzg0YTY0ZTVkMWQzYWRkNDI4Zjc0ZGNlZmIxOTVkYmUwMzUzZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JWxUDJHLQLScx0iyDXdO9lDGFPl-PoN0t9MtL6TylYs) 这个模板照着填很难么？


s905w    指的是SOC吗？

**Comment by goldsoft8888** [comment]
Armbian_24.2.0_amlogic_s912-t95z-plus_bookworm_6.1.76_server_2024.02.01.img   选择meson-gxl-s905w-tx3-mini.dtb就正常了。Armbian_24.2.0_amlogic_s912-t95z-plus_bookworm_6.6.15_server_2024.02.01.img 按这个方法不行，
