### ISSUE TITLE
N1 安装系统到emmc后无法从U盘启动

### ISSUE THREAD

**Issue by LSP0123** [ophub/amlogic-s9xxx-armbian#2069]
N1 安装系统到emmc后无法从U盘启动

直接从emmc启动了，u盘检查过，换读卡器+tf卡也不行

**Comment by ophub** [comment]
这个现象少见，你进emmc里面把/boot/u—boot.scr改个别的名字，就可以了

**Comment by LSP0123** [comment]
好的 谢谢O大

**Comment by LIUBANGJIAN** [comment]
O大，我的是刚刚相反，我按照教程安装到emmc里，提示是成功的。关机把掉u盘后，n1只能启动到安卓机器人画面，请问是什么原因呢？
