### ISSUE TITLE
 Beelink GT1(S912, 2GB RAM, 16GM , QCA9377-wifi )  working with meson-gxm-beelink-gt1.dtb(150balbes)

### ISSUE THREAD

**Issue by danuzz** [ophub/amlogic-s9xxx-armbian#207]
Excellent work!
You can include it in yours branch-main, meson-gxm-beelink-gt1.dtb (it work wifi+bluetooth ). I used u-boot-zyxq.bin.
Thank you!
![Beelink Armbian_22 05 0_Aml_s912_focal_5 15 31 ](https://user-images.githubusercontent.com/17131274/160379108-2c2c3c4f-b41d-409e-8e39-78c46bfbb6ab.jpg)

**Comment by ophub** [comment]
Try which of the following dtb can be used：
```
meson-gxm-octopus-planet.dtb
meson-gxm-q200.dtb
meson-gxm-q201.dtb
```

**Comment by danuzz** [comment]
For the first time i used meson-gxm-octopus-planet.dtb but it does not work  wifi+bluetooth.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.10.y/blob/main/arch/arm64/boot/dts/amlogic/meson-gxm-beelink-gt1.dts

There is your dtb file in the 5.10 kernel, are you convenient to update the kernel and test it?

`armbian-update 5.10.109`

**Comment by danuzz** [comment]
Ok thanks for the great work.

**Comment by ophub** [comment]
You test and report the results to see if this configuration can be used.

`armbian-update 5.10.109`

**Comment by danuzz** [comment]
`armbian-update 5.10.109 `   not work wifi+bluetooth.

**Comment by danuzz** [comment]
I tried  `meson-gxm-q200.dtb`  not boot
            `meson-gxm-q201.dtb`  boot without connection network (LAN)
             `meson-gxm-q201.dtb`  boot with connection network (LAN)  but it does not work wifi+bluetooth

**Comment by ophub** [comment]
Do you have the dts source code for meson-gxm-beelink-gt1.dtb?

**Comment by danuzz** [comment]
[meson-gxm-beelink-gt1.dtb.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/8362828/meson-gxm-beelink-gt1.dtb.gz)

**Comment by ophub** [comment]
OK, you save this file and use it in the firmware later.
