### ISSUE TITLE
请教，x96max+ 这两处怎么选

### ISSUE THREAD

**Issue by binge8** [ophub/amlogic-s9xxx-armbian#2070]
![photo_2024-02-05_19-02-54](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53508344/08471ec4-28d1-4348-bc27-c0da6b3182b4)
![photo_2024-02-05_19-02-43](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53508344/e2128b61-91b6-4f3c-9b5b-430436d86de4)
![屏幕截图 2024-02-05 182225](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53508344/1ef03379-83bb-4ddd-8f43-6220fb7f2364)
![屏幕截图 2024-02-05 190047](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53508344/ce5019a8-4215-4e75-9d28-e28cda12483a)

**Comment by ophub** [comment]
看外壳不知道芯片，502可以试一下
