### ISSUE TITLE
中车 CRRC 板子  RK3399 刷入Armbian_24.2.0_rockchip_crrc_noble_6.1.76后无法使用

### ISSUE THREAD

**Issue by AllGetHub** [ophub/amlogic-s9xxx-armbian#2071]
**中车 CRRC 板子  RK3399 刷入后无法自动获取ip**
 - SOC: [RK3399]
 - Model [CRRC]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.76]
 - Release: Armbian_24.2.0_rockchip_crrc_noble_6.1.76_server_2024.02.01.img.gz

**Describe the bug | 问题描述**
使用瑞芯微刷机工具MASKROM模式成功刷入24.2.0版本CRRC固件后，接入网线断电重启，等待3min，三颗LED常亮（红红绿）路由器设备列表中未看到新设备接入
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64944169/334bad5f-11e8-416c-9490-fa2ec2c3c542)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64944169/a43b2f8a-5ccb-4979-94cc-837a25d60190)

刷入旧版固件Armbian_crrc_ubuntu20.04.img，功能正常。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64944169/6b5ab404-0811-47db-b598-76cce2c40f01)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64944169/333d1e4f-1b72-4972-a710-9e01724488ed)
```
user@CRRC:~# uname -a
Linux CRRC 5.10.60-rockchip64 #21.08.1 SMP PREEMPT Wed Aug 25 18:56:55 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
旧版固件：
链接：https://pan.baidu.com/s/15ADV7WUzhMVS7wg6mAneUg?pwd=xrtl 
提取码：xrtl

**Comment by AllGetHub** [comment]
补充一点现象，重启后瑞芯微工具检测板子仍旧处于MASKROM模式。处于刷砖状态。

**Comment by akwangl** [comment]
我想知道他旧版的内核文件咋编译的，我想降版本了
