### ISSUE TITLE
我来做个反馈，我的板子是SW7990K VER1.4(带核心板SW799A VER1.2)

### ISSUE THREAD

**Issue by EXIA18** [ophub/amlogic-s9xxx-armbian#2073]
我来做个反馈，我的板子是SW7990K VER1.4(带核心板SW799A VER1.2)
模型：SW7990K VER1.4(带核心板SW799A VER1.2)，之前烧6.X内核无法启动，今天烧写了Armbian_23.11.0_rockchip_sw799_bookworm_5.15.140_server_2023.12.01.img版本，已经成功了，非常感谢大佬的开源

_Originally posted by @dutong0321 in https://github.com/ophub/amlogic-s9xxx-armbian/issues/1326#issuecomment-1846680846_

**Comment by gdanmac** [comment]
5.15 断流严重
