### ISSUE TITLE
无法安装docker

### ISSUE THREAD

**Issue by suibian12562** [ophub/amlogic-s9xxx-armbian#2074]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [cm311-1a-YST]

**Armbian Version | 系统版本**
 - Kernel Version: [6.6.16]
 - Release: [noble]

**Describe the bug | 问题描述**
在试图安装docker时出现错误
![2024-02-07 131021](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68977741/3168f752-102a-439e-ae2b-4457c817ab3f)
似乎没有支持Ubuntu 24 的docker源

**Comment by LSP0123** [comment]
docker使用jammy的源就可以了，这是docker还没放出支持noble导致的，不是O大问题
我是jammy升级到noble的，docker仍可以用
修改/etc/apt/sources.list.d/docker.list
内容如下：

`deb [arch=arm64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://mirrors.aliyun.com/docker-ce/linux/ubuntu jammy stable
`

等docker支持了noble，再修改这个文件里的jammy为noble就可以了

**Comment by suibian12562** [comment]
在我的机器上有效,谢谢
