### ISSUE TITLE
Hardware Decoding & Encoding Support for S905x3 (or any other Amlogic device that support it)

### ISSUE THREAD

**Issue by SenyxLois** [ophub/amlogic-s9xxx-armbian#2075]
`v4l2-ctl --list-devices` only show Amlogic Video Decoder (platform:meson-vdec) and not any encoding.
`sudo modprobe meson-venc` report that Module meson-venc not found in directory /lib/modules/5.15.145-ophub

Is there any method to have Decode & Encode support for This version of armbian? (AVE & AVD support)

**Comment by Supded** [comment]
You need to use android or gnu/linux with vendor kernel. Codecs works bad in mainline.

**Comment by SenyxLois** [comment]
I can't get hardware accelerated encoding to work on android. Is there any application i have to install to use it?

**Comment by Supded** [comment]
I don't know, khadas uses gstreamer plugin.
