### ISSUE TITLE
22C盒子无法TF卡启动armbian 6.x

### ISSUE THREAD

**Issue by amoslutherguo** [ophub/amlogic-s9xxx-armbian#2077]
**Device Information | 设备信息**
 - SOC: Amlogic S905L3A-B
 - Model: E900V22C

**Armbian Version | 系统版本**
 - Kernel Version: 6.6.15
 - Release: Armbian_24.2.0_amlogic_s905l3a_noble_6.6.15_server_2024.02.01.img

**Describe the bug | 问题描述**
E900V22C 盒子已加TF卡槽和换8822CS芯片， 把Armbian_24.2.0_amlogic_s905l3a_noble_6.6.15_server_2024.02.01.img镜像写入TF卡后，因为DTB默认就是22c.dtb,所以没有做任何改动，插入TF卡槽，开机无法启动，没反应
注:5.15 jammy版本的镜像可以成功启动，排除是盒子或TF卡槽，TF卡的问题
好像很多6.x版本的镜像都是同一个问题

**Comment by amoslutherguo** [comment]
左思右想不明白到底是为什么？于是又试了另一个镜像
Armbian_23.05.0_amlogic_s905l3a_jammy_6.1.28_server_2023.05.14
也是一样的问题无法启动，翻看前面的issues发现有人提到u-boot, 可是用二进制比对u-boot.ext和u-boot-e900v22c.bin这两个文件并没有任何差异啊

**Comment by amoslutherguo** [comment]
已解决！把exlinux.conf.bak去掉.bak复制到/boot/下面即可
5.x的版本好像也有这个文件，但是都没用到，不懂为什么5.x不需要，6.x需要

**Comment by ophub** [comment]
一般用不到，解决了就好
