### ISSUE TITLE
SV6051P wireless

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#208]
Hello! Is there any chance to make my x96 mini can use wireless?
The wifi chip is SV6051P

![image](https://user-images.githubusercontent.com/33513626/160548483-ac953df2-d546-4264-b2f1-5e7ad823016a.png)

Thanks

**Comment by danuzz** [comment]
You put  `install  full firmware package` ?

![Immagine 2022-03-29 100351](https://user-images.githubusercontent.com/17131274/160563757-4aec16e7-277e-494a-805a-80fa3a9ba8e0.jpg)

**Comment by ophub** [comment]
I have not installed this, I usually install the specified package as needed when using it.

**Comment by moarmarmalade** [comment]
The (driver/module for the) SV6051p chip is well known to be "impossible" to get to work with newer kernels, see the discussions over at Armbian e.g. [this one](https://forum.armbian.com/topic/16299-armbian-on-s905w-tvbox-a95x-f1-wifi-chip-sv6051p/). (The SV6051P chip is also on the earlier s905w versions of Tanix TX3-mini. I have one of these boxes and I ended up buying a simple USB dongle with a well supported chip that works out-of-the box (using the rtl8188 driver).)

**Comment by saurabhjn** [comment]
I've been meaning to test @ilmich's driver from https://github.com/armbian/build/commit/f3388b9aee0d1564a28fbc661c6e7b0415a6dfd0 for a long time now. The only holdup is that I want to compile it is an our of tree module, against one of the kernels released by ophub. Perhaps I'll find my S905W board today and do this.
