### ISSUE TITLE
M401A启动时HDMI为花屏状态

### ISSUE THREAD

**Issue by 18677386630** [ophub/amlogic-s9xxx-armbian#2080]
U盘启动后通过HDMI查看是花屏状态，ssh无链接，IP未分配，不知道什么原因，用的Armbian_24.2.0_amlogic_s905l3a_jammy_6.1.76_server_2024.02.01.img.gz，在已经运行armbian系统的cm311-1a-yst上面可以正常运行此U盘
![江苏版M401A卡开机画面，单电感，实(1)](https://github.com/ophub/amlogic-s9xxx-armbian/assets/130483453/aaef9da4-107d-48e6-831f-45a252035e49)
![图片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/130483453/86724f4b-e896-4ec7-9f09-eb0903c2084f)
![IMG_20240211_160124](https://github.com/ophub/amlogic-s9xxx-armbian/assets/130483453/2f39b58a-1a5a-4168-918a-486fedaa7a87)

![江苏版M401A卡开机画面，单电感，实(2)](https://github.com/ophub/amlogic-s9xxx-armbian/assets/130483453/c4f44c45-411f-4ab7-bfd6-51c85c5657b9)

**Comment by sdpyhzj** [comment]
l3a的板子用bullseyes比较稳定

**Comment by 18677386630** [comment]
> l3a的板子用bullseyes比较稳定

好的，谢谢，我多试试

**Comment by 18677386630** [comment]
后来更换dtb正常了，关闭
