### ISSUE TITLE
sshd 100%, 下载速度异常

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2081]
我试过多个版本的ARMBIAN,都存在这个问题。

我用WINSCP软件连接盒子，选择SFTP协议时，上传、下载速度都能达到30兆上以，
但是用SCP（ssH)协议时，上传可以达到30兆以上，下载到电脑时，速度只有1兆多，
用top命令查看，sshd进程占用100%，怀疑是加密方式导致的，有没有好办法？

**Comment by ophub** [comment]
协议占这么高不正常，重启试试

**Comment by goldsoft8888** [comment]
> 协议占这么高不正常，重启试试
各种方法都试了，不行，你们也测试下吧，看谁有相同的问题
