### ISSUE TITLE
X96 Max 安装armbian的踩坑记录 | Cookbook to install armbian to X96 Max

### ISSUE THREAD

**Issue by Patrick-Ze** [ophub/amlogic-s9xxx-armbian#2083]
~这是一个踩坑记录，放在这里是供有类似情况的人参考，并不是一个issue ticket，所以没有按照issue模板来~

按照我看到的信息，实际上有不同的厂家使用了X96 Max的名字，做出了五花八门的变体，为了借用一个知名度较高的设备名（蹭热度）都命名为了X96 Max。由于这些变体共用了X96 Max的名字，而很多刷机包或者教程并没有区分不同的变体（可能教程编写时还没有那么多变体），导致一个教程&刷机包可能在TA的设备上可用，刷到我的设备上就变砖。折腾这个X96 Max花了远超预期的时间，所以简单写个踩坑记录供后来的人参考：

1. 首先需要确认你的X96 Max硬件版本。
我使用的是 [Device Info](https://play.google.com/store/apps/details?id=com.ytheekshana.deviceinfo&hl=en_US) 这个App。它显示我的X96变体是`X96Max_Plus2`。为了实际确认，我也拆开后盖看了芯片型号，经过对比确认与App检测的一致（千兆以太网`RTL8211F`，WiFi `RTL8822CS`）
更进一步地说，这个踩坑记录里，我的X96 Max的PCB版本是`Q5X3_141 v4.0 20112`
![pic](https://xdaforums.com/proxy.php?image=https%3A%2F%2Fi.postimg.cc%2FnV2SWHXw%2FIMG-20200825-174256.jpg&hash=b85571db4c1494c1637b5f9509b19c0d)
（这只是个参考，应该还不至于严格要求PCB版本）
X96 Max的后盖还算好拆。可以根据[这个文章](https://travis90x.altervista.org/x96-max-plus-anlogic-s905x3-armbian/?doing_wp_cron=1707549897.7846369743347167968750)对照自己的硬件确认版本

2. 刷机前记得先进行`armbian-ddbr`备份你当前的系统并保存好备份文件，这样的话即使变砖，你也还可以通过从U盘启动并恢复原有系统。

3. `armbian-install`后，如果无法启动（我的设备表现为持续黑屏、无任何文字滚动，无法连接SSH），建议使用`armbian-install -m yes`进行安装，以指定使用main-line的u-boot。或者建议优先使用`armbian-install -m yes`进行安装。
忘了在哪里看到 ophub 大佬说大多数的设备不需要这个选项，经过我的测试（至少在我的这个设备变体上），X96 Max是需要指定这个选项的少数设备之一。

最后，我的这个变体里，尝试使用501、502、525三个选项安装了S905X3的镜像(`Armbian_24.2.0_amlogic_s905x3_jammy_6.6.15_server_2024.02.01.img.gz`)，使用`-m yes`安装编号为502的`X96-Max+_1GB`时匹配最佳，安装后实际测试，网速是千兆网卡水平

**Comment by danielkucera** [comment]
I have the same device and I also bricked it :grinning: 
I managed recover it using this file [X96Max_Plus_S905x3_2GB_20191101-AndroidPC.zip](https://drive.google.com/file/d/1xG078sY7M9cGO4wx7j3vCw9QtuGlF3hj/view) 
@Patrick-Ze , how did you run Armbian? From microSD or USB?

**Comment by Patrick-Ze** [comment]
> @Patrick-Ze , how did you run Armbian? From microSD or USB?

I burned img.gz to USB disk, then booted from the USB and installed the armbian system to X96's EMMC

**Comment by danielkucera** [comment]
Thanks, I got it working. I forgot I need to press the button during boot.

**Comment by navigos** [comment]
Thanks for sharing @danielkucera, it solved some problems #2317 #1394

**Comment by ophub** [comment]
> I have the same device and I also bricked it 😀 I managed recover it using this file [X96Max_Plus_S905x3_2GB_20191101-AndroidPC.zip](https://drive.google.com/file/d/1xG078sY7M9cGO4wx7j3vCw9QtuGlF3hj/view) @Patrick-Ze , how did you run Armbian? From microSD or USB?


I transferred a copy of this Android system
https://github.com/ophub/kernel/releases/tag/tools
android_tv_x96max_plus_2101_s905x3.tar.xz
