### ISSUE TITLE
如何把emmc的系统迁移到U盘或者SD 卡作为系统启动

### ISSUE THREAD

**Issue by 18677386630** [ophub/amlogic-s9xxx-armbian#2085]
因为盒子基本都是2+8或者2+16，随着服务器系统越来越庞大，16G明显不太够用了，想把emmc已部署的服务的系统迁移到更大存储的U盘，请问怎么实现？
我尝试过用ddbr备份的文件再反烧录到U盘，但是失败了。
谢谢

**Comment by xxlovex** [comment]
你把数据挂载在u盘或者sd卡内就行了吧

**Comment by 18677386630** [comment]
内存占用主要是Docker比较多，我更改Docker默认存储路径到硬盘
