### ISSUE TITLE
有没有办法修改安卓电视盒子MAC地址？

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2089]
我的设想是这样，先用U盘启动armbian，修改MAC后，再启动盒子内的安卓系统。但是我不知道怎么修改，能否实现？

**Comment by ophub** [comment]
文档里面有自定义网络设置的方法，可以在这个配置文件里自己编一个mac地址。

**Comment by goldsoft8888** [comment]
> 文档里面有自定义网络设置的方法，可以在这个配置文件里自己编一个mac地址。

有一个安卓软件要验证MAC地址，改完MAC后，需要运行安卓，

**Comment by hanguofu** [comment]
@ophub  : 请问这个配置文件是指  /etc/network/interfaces  吗？

**Comment by ophub** [comment]
是的
