### ISSUE TITLE
Compilation Error 

### ISSUE THREAD

**Issue by SajjadSabzkar** [ophub/amlogic-s9xxx-armbian#209]
Hi  , When i run `sudo ./rebuild -d -b s905x3 -k 5.4.188` in step 5/6 i give multi cp error .
e.g error message : `cp: error writing '/home/hi/armbian-build/amlogic-s9xxx-armbian/tmp_dir/tmp_out/rootfs/usr/lib/firmware/rkwifi/fw_RK903b2.bin': No space left on device`

**Comment by ophub** [comment]
Did you change the firmware settings? The default is recommended.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/f62c03a7b0bff397d4ede479428dfc247db81877/rebuild#L83

**Comment by ophub** [comment]
The desktop version contains more packages, you make this bigger to fit.
try `4000`

**Comment by SajjadSabzkar** [comment]
> The desktop version contains more packages, you make this bigger to fit. try `4000`

with `ROOT_MB=4000` also gives the error

**Comment by ophub** [comment]
The device firmware is larger than the file size of your desktop firmware.

I haven't tested the difference between the desktop and server versions. I installed the server version first, and then installed the desktop through armbian-config.

**Comment by SajjadSabzkar** [comment]
> Set the rebuild firmware is larger than the file size of your desktop firmware.
> 
> I haven't tested the difference between the desktop and server versions. I installed the server version first, and then installed the desktop through armbian-config.

Ok thanks.
i changed `ROOT_MB=6000` and it build successfully

**Comment by ophub** [comment]
ok
