### ISSUE TITLE
24.2.0 s912无法完成u盘系统启动

### ISSUE THREAD

**Issue by sstutu** [ophub/amlogic-s9xxx-armbian#2091]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]
 - 设备:斐讯 T1

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]
 - 当前YYF固件，u盘启动24.2版本

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

<img width="971" alt="67cf5de3a0daa233aead979ab1bb3e0" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/2777867/ccd8be70-07bf-41c2-8d74-0c36cc5acddb">

这几个版本都会有如下的日志，无法完成在u盘系统启动。
![fd17ca4c552ec29be37540dc88e0855](https://github.com/ophub/amlogic-s9xxx-armbian/assets/2777867/eb89a517-bef2-4ca5-8e85-7b80e061a98f)
![563304c001d40c660cef1a0062f1ac3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/2777867/b547dacd-7fec-4a52-bb24-76d6dbbfb2c7)

但是底下这个旧版本可以正常完成u盘系统启动：
 Armbian_22.11.0_Aml_s912_bullseye_5.15.79_server_2022.11.26.img.gz

**Comment by ophub** [comment]
那你编译个5.15.y内核的试试
