### ISSUE TITLE
 L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)

### ISSUE THREAD

**Issue by zzreador** [ophub/amlogic-s9xxx-armbian#2092]
**Device Information | 设备信息**
 - SOC: RK3566
 - Model:  Panther X2

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.76
 - Release: Armbian_bullseye_save_2024.02

**Describe the bug | 问题描述**
想在盒子上安装 VPN服务，启动时提示下面的错误信息：
xl2tpd: L2TP kernel support not detected (try modprobing l2tp_ppp and pppol2tp)。
尝试 modprobe l2tp_ppp，提示模块不存在。
检查了一下内核目录  /lib/modules/6.1.76-happy-new-year/kernel/net/l2tp/ 下 没有  l2tp_ppp.ko 文件。

问题：
1.新版kernel  可以包含 l2tp_ppp模块吗？
2.如果自己安装的话，应该如何操作？

**Comment by ophub** [comment]
https://github.com/ophub/kernel/blob/cfa753fa8d3593ccc12bafa08a9b64885e175a3a/kernel-config/release/general/config-6.1#L1545-L1549

我查看了 6.1.y 的内核配置文件，l2tp的已经选择了，下面这个是不是，你可以自己选择编译内核：

https://github.com/ophub/kernel/blob/cfa753fa8d3593ccc12bafa08a9b64885e175a3a/kernel-config/release/general/config-6.1#L2894-L2895

**Comment by zzreador** [comment]
谢谢。
2895行把改为  CONFIG_PPPOL2TP=m
重新编译内核就可以了。

**Comment by zzreador** [comment]
6.1.y 的内核配置文件中CONFIG_PPPOL2TP默认不打开的原因是什么？
