### ISSUE TITLE
创维E900V22D/s905l3芯片版本u盘引导问题

### ISSUE THREAD

**Issue by ruohai** [ophub/amlogic-s9xxx-armbian#2095]
**Device Information | 设备信息**
 - SOC: s905l-3
 - Model : e900v22d

创维E900V22D，soc是s905l-3，2+8版本。

一开始拿到手以后用的cm211-1的armbian固件，遥控器右方向键进入U盘引导，成功输入emmc。

但最近想重刷，armbian下红外模块已经无效不再支持遥控器，所以重刷了[这个帖子](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2058)中的安卓底包。

![无标题](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8485978/96288798-7500-4147-90c0-a9501becca5a)

底包输入成功以后可以正常开机进入安卓电视系统，但是开机按遥控器右方向键无法进入u盘引导，无法再刷入armbian。

有没有支持E900V22D/s905l3这版硬件，而且可以用遥控器右方向键进入U盘引导的底包？

**Comment by ruohai** [comment]
通过adb shell reboot update解决了。😄

**Comment by hanguofu** [comment]
请问老哥用的是哪个 armbian固件 ？有HDMI 输出吗 ?

**Comment by ruohai** [comment]
> 请问老哥用的是哪个 armbian固件 ？有HDMI 输出吗 ?

这次用的这个版本，debian-bookworm。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8485978/ee898c4d-f67d-4354-b56a-21a25f25bf99)


上一次用的是cm211的固件。

两个版本hdmi都没有输出。

**Comment by ophub** [comment]
魔百和系列大部分都没HDMI，通过局域网ssh管理

**Comment by lpfxh** [comment]
> 魔百和系列大部分都没HDMI，通过局域网ssh管理

你好，请问一下是不是我可以通过修改dtb文件，让魔百盒设备可以实现HDMI输出。请问这样可行吗，还是有许多问题需要进行适配。我手里有多个S905l3与S905l3b的设备，这个适配需要拆机吗。我可以拆机

**Comment by 77160860** [comment]
> 通过adb shell reboot update解决了。😄

同样的情况 进不去u盘系统  这个adb端口是多少  再哪里开？
