### ISSUE TITLE
mg101桌面安装失败

### ISSUE THREAD

**Issue by linbnn** [ophub/amlogic-s9xxx-armbian#2097]
包是r905lb jiammy 6.1.76 server 2024.02.1
安装桌面显示失败![IMG_20240220_180655.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/146666939/83b0c526-2b58-43d9-adc2-df00a8b6355d)

**Comment by linbnn** [comment]
我刷了一个TV包可以连接WiFi，方式刷入armbian 显示ip 不知道是不是我包弄错了![wx_camera_1708006957435.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/146666939/dc555802-d601-4a97-9681-3f7ae86f390f)

**Comment by ophub** [comment]
你的系统盘被安卓污染了，系统权限错误。
拔掉电源再插入USB，不要在运行状态下的安卓系统里插入armbian的u盘，插入就会被修改权限，重写u盘重新刷吧。

**Comment by linbnn** [comment]
我在armbian下重新刷入还是一样，同时更换源的时候也不能获取IP，自己查看了网上的解决方案还是没解决

**Comment by thiesymon** [comment]
请问下MG101的短接点在哪呢

**Comment by linbnn** [comment]
> 请问下MG101的短接点在哪呢

看型号我这个就插上USB就行了 你可以去买短接神器
