### ISSUE TITLE
大佬你好 S905L2-B 应该选择哪个包

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#2098]
大佬你好 S905L2-B 应该选择哪个包
盒子是M301A

**Comment by ophub** [comment]
试试117

查看model表，相近的可以尝试U盘启动。
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf
