### ISSUE TITLE
22C盒子无法找到8822cs网卡，是否忘记打开mmc0?

### ISSUE THREAD

**Issue by amoslutherguo** [ophub/amlogic-s9xxx-armbian#2099]
Device Information | 设备信息
 - SOC: Amlogic S905L3A-B
 - Model: E900V22C

Armbian Version | 系统版本

Kernel Version: 6.6.15
Release: Armbian_24.2.0_amlogic_s905l3a_noble_6.6.15_server_2024.02.01.img

Describe the bug | 问题描述

E900V22C 盒子已加TF卡槽和换8822CS芯片， 把Armbian_24.2.0_amlogic_s905l3a_noble_6.6.15_server_2024.02.01.img镜像写入TF卡成功启动Armbian，因为该版本是有内置8822cs.ko的，所以
modprobe rtw88_8822cs 后nmtui里面找不到无线网卡
dmesg | grep 8822 发现8822cs已经加载，但是
dmesg | mmc 找不到mmc0
所以想问问O大，是不是这个版本的mmc0忘记打开了？

**Comment by ophub** [comment]
8822这个驱动是f大从第三方移植的，换过几个版本，有的人可以用有的不行。
