### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by pulpoff** [ophub/amlogic-s9xxx-armbian#21]
root@mac:/usr/src/amlogic-s9xxx-armbian-main# ./make -d -b s922x -k 5.15.2
Welcome to build armbian for amlogic s9xxx STB! 

Server space usage before starting to compile: 
Filesystem                Type  Size  Used Avail Use% Mounted on
/dev/mapper/vgubuntu-root ext4  915G  852G   17G  99% / 

(1) Auto query the latest kernel version of the same series for [ 5.15.2 ]
(1) [ 5.15.2 ] is latest kernel. 

(1) [ 5.15.2 ] Kernel is in the local directory.
Armbian SoC List: [ s922x  ]
Kernel List: [ 5.15.2  ]
Ready, start build armbian... 

(1.1) Start build armbian [ s922x - 5.15.2 ]. Remaining space is 17G.
 [ s922x - 5.15.2 ]  (1/5) make new armbian image.
 [ Error ] Invalid file: /usr/src/amlogic-s9xxx-armbian-main/build/output/images/*-trunk_*.img
root@mac:/usr/src/amlogic-s9xxx-armbian-main# 

How can I compile the kernel from this ??

**Comment by pulpoff** [comment]
i tried to fix it, but its still like this : 
`root@mac:/usr/src/amlogic-s9xxx-armbian-main# ./make -d -b s922x -v beta -k 5.12.19
Welcome to build armbian for amlogic s9xxx STB! 

Server space usage before starting to compile: 
Filesystem                Type  Size  Used Avail Use% Mounted on
/dev/mapper/vgubuntu-root ext4  915G  853G   16G  99% / 

(1) Auto query the latest kernel version of the same series for [ 5.12.19 ]
(1) [ 5.12.19 ] is latest kernel. 

(1) [ 5.12.19 ] Kernel is in the local directory.
Armbian SoC List: [ s922x  ]
Kernel List: [ 5.12.19  ]
Ready, start build armbian... 

(1.1) Start build armbian [ s922x - 5.12.19 ]. Remaining space is 16G.
 [ s922x - 5.12.19 ]  (1/5) make new armbian image.
 [ s922x - 5.12.19 ]  (2/5) extract old armbian files.
cp: missing destination file operand after '/usr/src/amlogic-s9xxx-armbian-main/tmp_aml_image/armbian_s922x_5.12.19.img'
Try 'cp --help' for more information.
losetup: /usr/src/amlogic-s9xxx-armbian-main/tmp_aml_image/armbian_s922x_5.12.19.img: failed to set up loop device: No such file or directory
 [ Error ] losetup /usr/src/amlogic-s9xxx-armbian-main/tmp_aml_image/armbian_s922x_5.12.19.img failed.
`

**Comment by pulpoff** [comment]
0     512
/dev/loop12
             0      0         0  0 /usr/src/amlogic-s9xxx-armbian-main/tmp_out/Armbian__Aml_s922x_buster_5.12.19_2021.11.13.2341.img (deleted)
                                                                                                                                      0     512
/dev/loop3
             0      0         1  1 /var/lib/snapd/snaps/qt513_24.snap                                                                 0     512
/dev/loop10
             0      0         0  0 /usr/src/amlogic-s9xxx-armbian-main/tmp_out/Armbian__Aml_s922x_buster_5.12.19_2021.11.13.2338.img (deleted)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#local-make-instructions


Create the build/output/images folder, and upload the Armbian image of the lepotato board ( Eg: Armbian_21.11.0-trunk_Lepotato_buster_current_5.10.67.img ) to this ~/amlogic-s9xxx-armbian/build/output/images directory.

**Comment by ophub** [comment]
Are you a mac computer?

Use the ubuntu system and install the local environment according to the instructions.

Or directly use github online compilation

**Comment by pulpoff** [comment]
i am on ubuntu, and i can build armbian from their src and kernel from flippy.
question is how to package kernel from flippy for your armbian-update tool
i have changed armbian-update tool to install from local files, now need to create those files ..

**Comment by pulpoff** [comment]
Now managed to build armbian with your script, next to make sure kernel is compiled with new config ..
![Screenshot from 2021-11-14 00-31-47](https://user-images.githubusercontent.com/40654959/141661978-56898d5e-e5e1-4e3e-9989-26c56d8ef1f0.png)

**Comment by pulpoff** [comment]
Can you tell me how to compile the required kernel files for armbian-update please?
I mean these files :+1: 
boot-5.15.2-flippy-67+.tar.gz
Add new kernel
22 hours ago
dtb-allwinner-5.15.2-flippy-67+.tar.gz
Add new kernel
22 hours ago
dtb-amlogic-5.15.2-flippy-67+.tar.gz
Add new kernel
22 hours ago
dtb-rockchip-5.15.2-flippy-67+.tar.gz
Add new kernel
22 hours ago
modules-5.15.2-flippy-67+.tar.gz
Add new kernel
22 hours ago

**Comment by ophub** [comment]
You first build armbian with my script. After installation, directly compile the kernel on armbian and install it to use.

No need to make a kernel package, and use armbian-config.

**Comment by pulpoff** [comment]
i built armbian with your script .. but it uses kernel from binary from your website .. how to compile custom kernel and package it ?

**Comment by pulpoff** [comment]
kernel 5.12.19 works at 2.2Ghz , i also see that odroid n2+  runs with same cpu at 2.4 ghz.
I would like to add those overclock speeds to 5.15.2 .. 
can u help me ?
thanks

**Comment by pulpoff** [comment]
the raw speed difference is quite a game changer
see my benchmark with 5.12.19 here
![Screenshot from 2021-11-14 01-36-24](https://user-images.githubusercontent.com/40654959/141663199-9e4ccf45-6f2f-405c-a7fa-42b999b1e5cf.jpg)
:

**Comment by ophub** [comment]
Download the source code from `kernel.org`, `make menuconfig` custom configuration. `make -j4` compile...For related operations, please refer to the official documentation.
After completion, `make modules_install` && `make install`

**Comment by ophub** [comment]
flippy provides optimized source code, you can customize the configuration to compile.

https://github.com/unifreq/linux-5.12.y

**Comment by pulpoff** [comment]
but make modules_install and make install won't generate the files for armbian-update
how can i generate files and use armbian-update?

**Comment by pulpoff** [comment]
i have compiled unifreq kernel 5.15.2, but it does not produce files for armbian-update that i want to use ..

these : 
boot-5.12.19-flippy-62+.tar.gz dtb-amlogic-5.12.19-flippy-62+.tar.gz modules-5.12.19-flippy-62+.tar.gz
dtb-allwinner-5.12.19-flippy-62+.tar.gz dtb-rockchip-5.12.19-flippy-62+.tar.gz

how do u create them ??

**Comment by pulpoff** [comment]
see this link please to understand the issue 

[normal s922x vs overclocked](https://browser.geekbench.com/v5/cpu/compare/9393979?baseline=10932656)

**Comment by ophub** [comment]
After completion, `make modules_install && make install`

In this way, the kernel compiled by yourself has been installed. No need to use armbian-update.

**Comment by pulpoff** [comment]
but i want to use armbian-update .. why not just tell me how to create those files ?
please, it will help me a lot ..

**Comment by ophub** [comment]
https://github.com/ophub/script/blob/main/sh/extract-kernel.sh

This is a method of extracting the kernel file from the official compiled armbian and generating several kernel files according to the flippy kernel package organization.

Corresponding file:

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_buster_2021.11.14.0114/Armbian_21.11.0-trunk_Lepotato_buster_current_5.10.79.img.gz

**Comment by pulpoff** [comment]
would it be possible for u to make 5.15.2 custom kernel with overclocking freqs from 5.12.19 ?
even 2.2ghz would make a big difference

**Comment by pulpoff** [comment]
root@mac:/usr/src/amlogic-s9xxx-armbian-main# ./make
Welcome to build armbian for amlogic s9xxx STB! 

Server space usage before starting to compile: 
Filesystem                Type  Size  Used Avail Use% Mounted on
/dev/mapper/vgubuntu-root ext4  915G  858G   11G  99% / 

(1) Auto query the latest kernel version of the same series for [ default ]
(1) [ default ] is latest kernel. 

(1) [ default ] Kernel loading from [ https://github.com/ophub/kernel/trunk/pub/stable/default ]
svn: E170000: URL 'https://github.com/ophub/kernel/trunk/pub/stable/default' doesn't exist
Armbian SoC List: [ s922x s922x-n2 s905x3 s905x2 s912 s905d s905x s905w  ]
Kernel List: [ default  ]
Ready, start build armbian... 

(1.1) Start build armbian [ s922x - default ]. Remaining space is 11G.
 [ s922x ]  (1/5) make new armbian image.
 [ s922x ]  (2/5) extract old armbian files.
 [ s922x ]  (3/5) replace kernel for armbian.
 [ s922x ]  (4/5) copy files to new image.
 [ s922x ]  (5/5) clear temp files.
(1.1) Build successfully. 

(2.1) Start build armbian [ s922x-n2 - default ]. Remaining space is 11G.
 [ s922x-n2 ]  (1/5) make new armbian image.
 [ s922x-n2 ]  (2/5) extract old armbian files.
 [ s922x-n2 ]  (3/5) replace kernel for armbian.
 [ s922x-n2 ]  (4/5) copy files to new image.
 [ s922x-n2 ]  (5/5) clear temp files.
(2.1) Build successfully. 

(3.1) Start build armbian [ s905x3 - default ]. Remaining space is 9,5G.
 [ s905x3 ]  (1/5) make new armbian image.
 [ s905x3 ]  (2/5) extract old armbian files.
 [ s905x3 ]  (3/5) replace kernel for armbian.
 [ s905x3 ]  (4/5) copy files to new image.
 [ s905x3 ]  (5/5) clear temp files.
(3.1) Build successfully. 

(4.1) Start build armbian [ s905x2 - default ]. Remaining space is 8,9G.
 [ s905x2 ]  (1/5) make new armbian image.
 [ s905x2 ]  (2/5) extract old armbian files.
 [ s905x2 ]  (3/5) replace kernel for armbian.
 [ s905x2 ]  (4/5) copy files to new image.
 [ s905x2 ]  (5/5) clear temp files.
(4.1) Build successfully. 

(5.1) Start build armbian [ s912 - default ]. Remaining space is less than 2G, exit this packaging. \n
(6.1) Start build armbian [ s905d - default ]. Remaining space is less than 2G, exit this packaging. \n
(7.1) Start build armbian [ s905x - default ]. Remaining space is less than 2G, exit this packaging. \n
(8.1) Start build armbian [ s905w - default ]. Remaining space is less than 2G, exit this packaging. \n
Server space usage after compilation: 
Filesystem                Type  Size  Used Avail Use% Mounted on
/dev/mapper/vgubuntu-root ext4  915G  861G  8,2G 100% / 

root@mac:/usr/src/amlogic-s9xxx-armbian-main# wget https://github.com/ophub/script/blob/main/sh/extract-kernel.sh
--2021-11-14 03:39:41--  https://github.com/ophub/script/blob/main/sh/extract-kernel.sh
Resolving github.com (github.com)... 140.82.121.3
Connecting to github.com (github.com)|140.82.121.3|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘extract-kernel.sh’

extract-kernel.sh             [ <=>                                 ] 191,87K  1,11MB/s    in 0,2s    

2021-11-14 03:39:42 (1,11 MB/s) - ‘extract-kernel.sh’ saved [196475]

root@mac:/usr/src/amlogic-s9xxx-armbian-main# chmod +x extract-kernel.sh 
root@mac:/usr/src/amlogic-s9xxx-armbian-main# ./extract-kernel.sh 
./extract-kernel.sh: line 7: syntax error near unexpected token `newline'
./extract-kernel.sh: line 7: `<!DOCTYPE html>'
root@mac:/usr/src/amlogic-s9xxx-armbian-main#

**Comment by pulpoff** [comment]
./extract-kernel.sh 
Start build kernel for amlogic-s9xxx-openwrt ...
copy armbian to tmp folder ...
armbian: Armbian_21.11.0-trunk_Lepotato_buster_current_5.10.79.img
mount armbian ...
Copy modules files
armbian_version: 5.10.79-meson64
kernel_version: 5.10.79
Copy five boo kernel files
supplement .dtb file from github.com ...
Copy .dtb files
Package modules-5.10.79-meson64.tar.gz
Package dtb-amlogic-5.10.79-meson64.tar.gz
Package boot-5.10.79-meson64.tar.gz
umount old armbian ...
mv 5.10.79 folder to /usr/src/amlogic-s9xxx-armbian-main/build/output/images
kernel save path: /usr/src/amlogic-s9xxx-armbian-main/build/output/images/5.10.79.tar.gz
delete tmp folders ...
build kernel complete ...
root@mac:/usr/src/amlogic-s9xxx-armbian-main#

**Comment by ophub** [comment]
https://github.com/ophub/script/blob/41c6a2b8847083569fa49ba9e3e2a05bce57be5b/sh/extract-kernel.sh#L40-L42

change to:

```
    if ! mount ${loop_old}p2 ${armbian_tmp}; then
        die "mount ${loop_old}p2 failed!"
    fi
    if ! mount ${loop_old}p1 ${armbian_tmp}/boot; then
        die "mount ${loop_old}p1 failed!"
    fi
```

**Comment by pulpoff** [comment]
i just did, still the same : 
#!/bin/bash
#==================================================================================================
# Description: Extract the kernel from armbian
# Armbian source: https://github.com/ophub/amlogic-s9xxx-armbian
# Copyright (C) 2021 https://github.com/ophub/script
#==================================================================================================

#===== Do not modify the following parameter settings, Start =====
make_path=${PWD}
tmp_path=${make_path}/tmp_kernel
armbian_tmp=${tmp_path}/armbian_tmp
kernel_tmp=${tmp_path}/kernel_tmp
dtb_tmp=${tmp_path}/dtb_tmp
modules_tmp=${tmp_path}/modules_tmp
armbian_outputpath=${make_path}/build/output/images
armbian_dtbpath=https://github.com/ophub/amlogic-s9xxx-openwrt/trunk/amlogic-s9xxx/amlogic-dtb
#===== Do not modify the following parameter settings, End =======

die() {
    echo -e " [ \033[1;31m Error \033[0m ] ${1}"
    exit 1
}

[ $(id -u) = 0 ] || die "please run this script as root: [ sudo ./extract-kernel.sh ]"

echo "Start build kernel for amlogic-s9xxx-openwrt ..."

    mkdir -p ${armbian_tmp} ${kernel_tmp} ${dtb_tmp} ${modules_tmp}

cd  ${tmp_path}
    echo "copy armbian to tmp folder ..."
    cp -f $( ls ${armbian_outputpath}/*.img 2>/dev/null | head -n 1 ) . && sync
    armbian_old=$( ls *.img 2>/dev/null | head -n 1 )
    echo "armbian: ${armbian_old}"

    echo "mount armbian ..."
    loop_old=$(losetup -P -f --show "${armbian_old}")
    [ ${loop_old} ] || die "losetup ${armbian_old} failed."

    if ! mount ${loop_old}p1 ${armbian_tmp}; then
        die "mount ${loop_old}p1 failed!"
    fi
    sync && sleep 3

    echo "Copy modules files"
    cp -rf ${armbian_tmp}/lib/modules/* ${modules_tmp} && sync
    if [ $( ls ${modules_tmp}/ -l 2>/dev/null | grep "^d" | wc -l ) -eq 0 ]; then
       die "The modules files is Missing!"
    fi
    armbian_version=$(ls ${modules_tmp}/)
    echo "armbian_version: ${armbian_version}"
    kernel_version=$(echo ${armbian_version} | grep -oE '[1-9].[0-9]{1,2}.[0-9]+')
    mkdir -p ${kernel_version}
    echo "kernel_version: ${kernel_version}"

    echo "Copy five boo kernel files"
    cp -f ${armbian_tmp}/boot/{config-*,initrd.img-*,System.map-*,uInitrd-*,vmlinuz-*} ${kernel_tmp} && sync
    if [ ! -f ${kernel_tmp}/config-* -o ! -f ${kernel_tmp}/initrd.img-* -o ! -f ${kernel_tmp}/System.map-* -o ! -f ${kernel_tmp}/uInitrd-* -o ! -f ${kernel_tmp}/vmlinuz-* ]; then
       die "The five boot kernel files is Missing!"
    fi

    echo "supplement .dtb file from github.com ..."
    svn checkout ${armbian_dtbpath} ${dtb_tmp} >/dev/null 2>&1
    echo "Copy .dtb files"
    cp -f ${armbian_tmp}/boot/dtb-*/amlogic/*.dtb ${dtb_tmp} && sync
    sync

cd  ${modules_tmp}
    echo "Package modules-${armbian_version}.tar.gz"
    tar -czf modules-${armbian_version}.tar.gz *
    mv -f modules-${armbian_version}.tar.gz ../${kernel_version} && sync

cd  ${dtb_tmp}
    echo "Package dtb-amlogic-${armbian_version}.tar.gz"
    rm -rf $(find . -type d) 2>/dev/null && sync
    rm -rf .svn && sync
    tar -czf dtb-amlogic-${armbian_version}.tar.gz *
    mv -f dtb-amlogic-${armbian_version}.tar.gz ../${kernel_version} && sync

cd  ${kernel_tmp}
    echo "Package boot-${armbian_version}.tar.gz"
    tar -czf boot-${armbian_version}.tar.gz *
    mv -f boot-${armbian_version}.tar.gz ../${kernel_version} && sync

cd  ${tmp_path}
    echo "umount old armbian ..."
    umount -f ${armbian_tmp} 2>/dev/null
    losetup -d ${loop_old} 2>/dev/null
    echo "mv ${kernel_version} folder to ${armbian_outputpath}"
    mv -f ${kernel_version} ${armbian_outputpath}/ && sync

cd ${armbian_outputpath}
    echo "kernel save path: ${armbian_outputpath}/${kernel_version}.tar.gz"
    tar -czf amlogic-s9xxx-kernel-${kernel_version}.tar.gz ${kernel_version} && sync
    rm -rf ${kernel_version} && sync

cd  ${make_path}
    echo "delete tmp folders ..."
    rm -rf ${tmp_path} && sync

echo "build kernel complete ..."

**Comment by ophub** [comment]
https://github.com/ophub/script/blob/41c6a2b8847083569fa49ba9e3e2a05bce57be5b/sh/extract-kernel.sh#L65

change to:

`cp -f ${armbian_tmp}/boot/dtb/amlogic/*.dtb ${dtb_tmp} && sync`

**Comment by pulpoff** [comment]
now it works fine !
THANKS!!!
./extract-kernel.sh 
Start build kernel for amlogic-s9xxx-openwrt ...
copy armbian to tmp folder ...
armbian: Armbian_21.11.0_Aml_s922x_buster_5.12.19_2021.11.14.0033.img
mount armbian ...
Copy modules files
armbian_version: 5.12.19-flippy-62+
kernel_version: 5.12.19
Copy five boo kernel files
supplement .dtb file from github.com ...
Copy .dtb files
Package modules-5.12.19-flippy-62+.tar.gz
Package dtb-amlogic-5.12.19-flippy-62+.tar.gz
Package boot-5.12.19-flippy-62+.tar.gz
umount old armbian ...
mv 5.12.19 folder to /usr/src/amlogic-s9xxx-armbian-main/build/output/images
kernel save path: /usr/src/amlogic-s9xxx-armbian-main/build/output/images/5.12.19.tar.gz
delete tmp folders ...
rm: cannot remove '/usr/src/amlogic-s9xxx-armbian-main/tmp_kernel/armbian_tmp/boot': Device or resource busy
build kernel complete ...
root@mac:/usr/src/amlogic-s9xxx-armbian-main#

**Comment by pulpoff** [comment]
please update the file in github, it is much improved!

**Comment by ophub** [comment]
We all use the kernel shared by flippy. He is familiar with these boxes and knows how to adapt.

Do you have any special needs for custom kernels? What research is used? Who are the specific groups for use?

**Comment by pulpoff** [comment]
this extracts the kernel from armbian image .. but to put it in armbian image from flippy 5.15.y tree, after compile, what do u use ?

**Comment by pulpoff** [comment]
also i don't see anywhere the src files for 5.12.19 kernel to check how overclocking is done ..

**Comment by ophub** [comment]
https://github.com/ophub/script/blob/41c6a2b8847083569fa49ba9e3e2a05bce57be5b/sh/extract-kernel.sh#L87-L88

change to:

```
umount -f ${armbian_tmp}/boot 2>/dev/null
umount -f ${armbian_tmp} 2>/dev/null
losetup -d ${loop_old} 2>/dev/null
```

**Comment by ophub** [comment]
Put these three kernel files in any directory of the armbian system (such as `/root`), and execute `armbian-update 5.12.19` in the `current directory` to use the local kernel file update (the script first checks the local current directory, if there are files Will not download from github.com

**Comment by pulpoff** [comment]
![Screenshot from 2021-11-14 04-33-21](https://user-images.githubusercontent.com/40654959/141666341-35162f17-1741-446e-8fed-1a7063232181.png)

**Comment by pulpoff** [comment]
works

**Comment by ophub** [comment]
I don’t understand how the kernel is overclocked. I am a user and have not compiled a personalized kernel.

**Comment by pulpoff** [comment]
look , the mission is simple 
1. look at 5.12.19 sources and find the proper overclock freqs
2. put those freqs in 5.15.2, recompile
3. use armbian-update to install

**Comment by pulpoff** [comment]
for GT King there're 2 different dtb files in /BOOT : normal and -oc (overclock), that allows 2.2Ghz freq.
The kernel should support this freq, as there're are no other places that limit freq. 
Only 5.12.19 supports 2.2, rest of kernels i tried all work at 1.8Ghz

**Comment by ophub** [comment]
Before doing this, find out how to rescue if you fail to install a custom kernel, and make sure that your continuous testing has a way to recover. (Saving bricks is the guarantee of persistence)

**Comment by ophub** [comment]
I don't understand the setting of kernel parameters, you can explore it yourself.

**Comment by pulpoff** [comment]
i cannot install the kernel with make install after building from flippy sources, thats why i need to use armbian-update ..

**Comment by pulpoff** [comment]
to rescue i will just rewrite /BOOT partition from your armbian image )))

**Comment by ophub** [comment]
The path and packaging method of the kernel file have been clearly written in the script just now.

You compile the kernel under the armbian system, install it, extract it from the corresponding location, and package it. This is the method of compiling the kernel locally.

**Comment by pulpoff** [comment]
why i can't extract with this tool kernel from another armbian image?
root@mac:/usr/src/amlogic-s9xxx-armbian-main# ./extract-kernel.sh 
Start build kernel for amlogic-s9xxx-openwrt ...
copy armbian to tmp folder ...
armbian: Armbian_21.08.1_Odroidn2_hirsute_edge_5.13.12_xfce_desktop.img
mount armbian ...
mount: /usr/src/amlogic-s9xxx-armbian-main/tmp_kernel/armbian_tmp: special device /dev/loop11p2 does not exist.
 [  Error  ] mount /dev/loop11p2 failed!
root@mac:/usr/src/amlogic-s9xxx-armbian-main#

**Comment by ophub** [comment]
Officially compiled firmware with only one partition uses the unmodified script.

The above modifications are suitable for the dual-partition firmware that I packaged.

Do your own research for other people.

**Comment by pulpoff** [comment]
ok, makes sense, thanks !

up to now i can't anyhow test my new kernel .. no way to install it ..

**Comment by pulpoff** [comment]
once i built new kernel with flippy, how to put it into armbian image or install it ?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/21#issuecomment-968199362

**Comment by pulpoff** [comment]
there seems to be a way to integrate ZEN kernel patches and run with ZEN scheduler : 
[here](https://forum.odroid.com/viewtopic.php?f=209&t=41917)
