### ISSUE TITLE
能否分离boot和root分区

### ISSUE THREAD

**Issue by zvzl** [ophub/amlogic-s9xxx-armbian#210]
请问能否实现boot分区在emmc上而root分区在U盘上？如果可以，需要如何修改呢？

**Comment by ophub** [comment]
都在USB多好，把boot放emmc是最麻烦的，还需要适配emmc的分区。
有一些设备只能用于usb使用，例如S905的固件。

**Comment by zvzl** [comment]
> 

我也想都放在usb上，但是U盘插在usb口供电不稳定（我已经加电容了，电源也换了），所以我把U盘插在usb扩展线上（usb扩展线有独立供电），用了扩展线后系统好像就不从U盘启动了。

我已经把boot分区放入emmc了，实际上我的emmc上既有boot又有root分区，可以正常启动，但我不想消耗闪存的寿命。

所以我想问问可不可以通过修改boot里的文件，实现挂载U盘上的root分区。

盒子是hk1box，芯片是s905x3.

**Comment by ophub** [comment]
放心用，能用够闪存寿命的可能性不大。

改/etc/fstab把根分区的uuid改为u盘的值试试

**Comment by zvzl** [comment]
> 

谢谢，我把emmc boot分区的内容全换位U盘boot分区的内容，就成功了

**Comment by ophub** [comment]
好的，恭喜你，天才
