### ISSUE TITLE
当贝B3 pro ,s922x使用了u盘启动，但是一直进不去armbian系统。

### ISSUE THREAD

**Issue by 00Recycle00** [ophub/amlogic-s9xxx-armbian#2102]
之前安装CoreELEC的时候使用的u22-xj max的dtb文件可以成功的进入u盘系统，并安装。
但是我尝试过把u22-xj max的dtb文件复制进boot/dtb/amlogic/里面并且修改了uEnv.txt文件。但还是不能进入u盘启动。
我应该要怎么做？请帮帮我。

这个是CoreELEC使用的dtb文件
[g12b_s922x_minix_u22xj.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14367596/g12b_s922x_minix_u22xj.zip)

**Comment by yicheng42** [comment]
我也遇到过这样的问题，只不过我是小米盒子4，我也有一个当贝盒子，但是从来没试过，你可以换个U盘试试
照说不修改dtb文件也能启动，只不过无法安装到闪存eMMc，所以通过你的描述，我认为是U盘损坏了（我换U盘后好了）

**Comment by ophub** [comment]
安卓系统的dtb不能用，试armbian自带的目录里的

**Comment by itlaohuo** [comment]
手中U盘多的话，多尝试几个试试。我手里旧U盘试了5个（zxv10B860的4+32的盒子）只有2个可以。（8和16G的旧U盘可以）

**Comment by yicheng42** [comment]
> 感谢回复。 我昨天有循环尝试使用armbian的dtb做u盘启动 （当贝b3有reset按钮可以进入u盘启动，我尝试过CoreELEC的安装包再写入到u盘，按下reset按钮后一次就进入coreelec系统了） 因为我手头没有多余的u盘所以我还没有尝试更换u盘。 我用的是Armbian_24.5.0_amlogic_s922x_jammy_5.15.148_server_2024.02.21.img镜像 我从【meson-g12b-ali-ct2000.dtb】开始到【meson-g12b-ugoos-am6-plus.dtb】都尝试过一次，进不去系统。
> 
> 我想问一下 1，我现在的设备情况是，我在emmc里同时安装了CoreELEC系统和安卓系统。会有影响吗？是否需要把CoreELEC系统先删除？ 2，我不知道要如何修改更换u-boot文件，我只单纯的更换了dtb的文件地址，然后进行尝试。 3，是否使用更低版本的内核会比较容易成功？比如【5.4.239.tar.gz】内核（不知道应该如何映射到u盘boot目录下）
> 
> 另外，我再尝试换个u盘试试能否进入u盘启动。

至于u-boot，我还懂一小点点
目录中有两个u-boot.sxxx-sxxx.bin这种文件，找到适合你的，然后把里面原有的u-boot.ext移出去（推荐备份），然后把我说的那个文件改成和他同名的就OK了，亲测有效，可以写入闪存

**Comment by 00Recycle00** [comment]
> > 感谢回复。 我昨天有循环尝试使用armbian的dtb做u盘启动 （当贝b3有reset按钮可以进入u盘启动，我尝试过CoreELEC的安装包再写入到u盘，按下reset按钮后一次就进入coreelec系统了） 因为我手头没有多余的u盘所以我还没有尝试更换u盘。 我用的是Armbian_24.5.0_amlogic_s922x_jammy_5.15.148_server_2024.02.21.img镜像 我从【meson-g12b-ali-ct2000.dtb】开始到【meson-g12b-ugoos-am6-plus.dtb】都尝试过一次，进不去系统。
> > 我想问一下 1，我现在的设备情况是，我在emmc里同时安装了CoreELEC系统和安卓系统。会有影响吗？是否需要把CoreELEC系统先删除？ 2，我不知道要如何修改更换u-boot文件，我只单纯的更换了dtb的文件地址，然后进行尝试。 3，是否使用更低版本的内核会比较容易成功？比如【5.4.239.tar.gz】内核（不知道应该如何映射到u盘boot目录下）
> > 另外，我再尝试换个u盘试试能否进入u盘启动。
> 
> 至于u-boot，我还懂一小点点 目录中有两个u-boot.sxxx-sxxx.bin这种文件，找到适合你的，然后把里面原有的u-boot.ext移出去（推荐备份），然后把我说的那个文件改成和他同名的就OK了，亲测有效，可以写入闪存

感谢你的回答，我试试！
我新购入了2个u盘今天能到了。明天再试试看能不能进入armbian系统。

**Comment by txlos** [comment]
@00Recycle00  最后怎么样了？我也想在当贝B3上运行armbian

**Comment by Leon905873832** [comment]
请问最终解决了没有，怎么操作的？我也是当贝b3 pro，也是进不了系统。可惜了这么好的盒子啊。
