### ISSUE TITLE
xfce和lxde桌面怎么安装？默认桌面占用太高了(已写入eMMC)

### ISSUE THREAD

**Issue by yicheng42** [ophub/amlogic-s9xxx-armbian#2105]
**Device Information | 设备信息**
 - SOC: [s905l]
 - Model [mibox4(mdz-21-aa)]

**Armbian Version | 24.1
 - Kernel Version: [e.g. 6.1.73]
 - Release: [e.g. jammy]

  DTB：meson-gxl-s905l-venz-v10

**Comment by duzhuoshanwai** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#1219-%E5%A6%82%E4%BD%95%E5%BC%80%E5%90%AF%E8%BF%9C%E7%A8%8B%E6%A1%8C%E9%9D%A2%E5%92%8C%E4%BF%AE%E6%94%B9%E9%BB%98%E8%AE%A4%E7%AB%AF%E5%8F%A3
