### ISSUE TITLE
[Help] How to "properly" mount EMMC partitions from Amlogic "partition table"

### ISSUE THREAD

**Issue by AndNovAtor** [ophub/amlogic-s9xxx-armbian#2108]
Sorry if it's wrong place, or duplicate.

I have tv box with `S095x3`, _Vontar X3_. It has "stock" Android 9 on EMMC.

I use this Armbian from SD card (for example, Jammy version).

So, my question - how to "properly" mount Android partitions? Want to use internal storage (and not install Armbian to it - for minimum "changes").

As it's Amlogic "partition table", `parted` can't "detect" it. With help of [armpart](https://github.com/7Ji/ampart) I can see partitions sizes and offsets, using it with EMMC dump file (created with `armbian-ddbr`, and than converted to VDI on my PC).

Knowing offsets and sizes, I can manualy "create" loop devices (with `losetup`) and mount partitons.
For example, for _sysytem_ partition, _losetup_ looks like (executed as `root`, else - with `sudo`):
`losetup -o 2187329536 --sizelimit 1946157056 /dev/loop12 /dev/sdb`

And for _data_ partition (that also contains data for `/sdcard` "mount point"), as it last partition, _losetup_ looks like:
`losetup -o 4284481536 /dev/loop11 /dev/sdb`

(As I wrote above, I converted EMMC dump file to VDI and connected it to my virtual Ubuntu 22.04, so `/dev/sdb` - that disk; as for mount - it was something like `mount /dev/loop11 /mnt`)

Still, I wonder - is there another, "proper" way to do all of the above? Something "automatically"?
Maybe I missed some documentation pages....

(Again, I created dump file with `armbian-ddbr`, so it looks like I have no danger to "brick" my tv box. ...or have I?)

**Comment by ophub** [comment]
Your method of use is already very good.

When you boot Armbian from an external device using TF/USB, you utilize the storage space of this external device. There's no need to worry about the remaining space inside the TV box anymore.

**Comment by AndNovAtor** [comment]
Ok, thank you.

So, still my questions.

1. Can my code be used in some sort of "help" in another place? Or simply here...

2. Again - there are no scripts/auto-"tools" to "auto" mount that partitions, am I right?

3. If 2 is correct, do we needed that "scripts"? Looks like not so much....

**Comment by MrBryan** [comment]
@AndNovAtor did you find a way to mount this more efficiently? Or everyone : is there now a better way?

It would be amazing if you can mount the android drive directly from armbian and modify files as the title of this issue suggests, rather than needing to make a dump image

**Comment by AndNovAtor** [comment]
@MrBryan , as I wrote, all command args from my commands come from [armpart](https://github.com/7Ji/ampart) output. So, I was thinking of just writing a script (sh) that would automate mounting partitions on boot.

But I still don't need it (I use my Vontar X3 as a SMB/HTTP share from USB 3.5 HDD [and with VNC for some emergency browsing] 😅), So I didn't do it. =)

However, that's why I asked the last questions.

Still, again:

> do we needed that "scripts"? Looks like not so much....

P.s. - Maybe I didn't write it very explicitly, but by manually mounting, I successfully put files, for example, on the `/data` partition (and then saw them in Android ~without taking into account files permissions~) [my armbian is loaded with microSD, without "touching" stock Vontar Android]
P.s.s - I used a disk image just for convenience in a virtual machine, and as a backup.

**Comment by MrBryan** [comment]
Wow ok I misread / misunderstood I thought you only mounted the resulting dump/image file — thank you for clarifying 

I will try to read more on the usage of armpart so I can repeat whatever commands you used to get the losetup command parameter you used above I guess ?

Why did you cross out “without taking into account file permissions” ? Were you prevented from modifying some files ?

**Comment by AndNovAtor** [comment]
> I will try to read more on the usage of armpart so I can repeat whatever commands you used to get the losetup command parameter you used above I guess ?

Well, not as ctrl+c ctrl+v 😅 As devices have different partition size, and also android partitions is NOT `sdb` (as I wrote, for simplify, I wrote it from disk image)

> Why did you cross out “without taking into account file permissions” ? Were you prevented from modifying some files ?

Because Android is not like "simple Linux", it has own file permissions for user files, own "virtual" "filesystem" for mounting, `/sdcard`, for example (you can read about overlayfs, etc). But of course, if you know what to do, then it's possible. ~Or have rooted custom Android XD~

**Comment by AndNovAtor** [comment]
> I will try to read more on the usage of armpart

You can also, as I, try practicing on the disk image to understand and not to mess up. =)
As they say, backups, backups, and more backups. 😅

**Comment by MrBryan** [comment]
> and also android partitions is NOT sdb (as I wrote, for simplify, I wrote it from disk image)

Haha yes i knew that much. But to be clear, after practice you were ultimately able to mount the drive directly rw mode (not the image file) and make changes and you could see them in android with no issues?

**Comment by MrBryan** [comment]
Or did you only ever write to the disk image?

**Comment by AndNovAtor** [comment]
@MrBryan, it's closed issue about general questions. Let's stop bumping this issue and use discussion or temporary your duplicate issue
