### ISSUE TITLE
x88pro x3 failed to start Raise network interface

### ISSUE THREAD

**Issue by araczkowski** [ophub/amlogic-s9xxx-armbian#211]
Any chance to have working ethernet in x88pro x3  (s905x3)  box ?
This box has 1Gb ethernet, Armbian is starting fine, but unfortunately the network doesn't work. Any advices how to achieve working ethernet are welcome.

**Comment by ophub** [comment]
What wired NIC chip?

**Comment by araczkowski** [comment]
RTL8211F Gigabit ethernet 
![ethernet](https://user-images.githubusercontent.com/1263968/160621729-51d8cfb3-2dca-4ee3-b36d-2740e6376d57.jpg)

**Comment by danuzz** [comment]
Try with` meson-sm1-sei610.dtb` of  150balbes

[meson-sm1-sei610.dtb.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/8373097/meson-sm1-sei610.dtb.gz)

**Comment by araczkowski** [comment]
> Try with meson-sm1-sei610.dtb of 150balbes

Thanks, I tried, the same problem ->  ``failed to start Raise network interfaces``
I'm serching for meson-sm1-sei610-ethfix.dtb

**Comment by dinhchinh82** [comment]
@araczkowski you can try this file which I downloaded from armbian forum before.
[meson-sm1-sei610-ethfix.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8381547/meson-sm1-sei610-ethfix.dtb.zip)

**Comment by araczkowski** [comment]
@dinhchinh82 thx 

finally this attached dtb is working ok for me 
[meson-sm1-sei610-2.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8388767/meson-sm1-sei610-2.dtb.zip)
