### ISSUE TITLE
反馈新机型之Tanix-TX66，希望适配 #1432

### ISSUE THREAD

**Issue by EricHu0307** [ophub/amlogic-s9xxx-armbian#2111]
**Device Information | 设备信息**
 - SOC: [rk3566]
 - Model [TX66]

![O1CN01piPnCt2HGO9YlzTks_!!2973829123-0-cib](https://github.com/ophub/amlogic-s9xxx-armbian/assets/60762206/39530c4b-d57e-4248-b1ca-e6e3dee92167)

![Screenshot 2024-02-25 at 2 25 16 PM](https://github.com/ophub/amlogic-s9xxx-armbian/assets/60762206/5c09094a-c24f-4808-ac34-50c7684729f4)

**Comment by tenacity0** [comment]
wait

**Comment by ymBoss** [comment]
同求 或者适配openwrt也可以啊，多谢
