### ISSUE TITLE
No end-user support: unsupported (bullseye) userspace!

### ISSUE THREAD

**Issue by akwangl** [ophub/amlogic-s9xxx-armbian#2112]
**Device Information | 设备信息**
 - SOC: [e.g. RK3399]
 - Model [e.g. hisense-hs530r]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.149-ophub]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
开机提示No end-user support: unsupported (bullseye) userspace!用6.1.x的内核也会有这样的提示

<img width="1041" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/39325175/87700880-3ae9-4ea1-b974-e6c1ea0fd50f">

**Comment by ophub** [comment]
Bullseye已经不是lts版了，官方的提示，和内核无关。

**Comment by akwangl** [comment]
好的，我替换上一个版本了。暂时就这样吧，还有一个问题rk3399 这个板子网口老是运行一段时间直接掉网。大佬有遇到过吗

**Comment by ophub** [comment]
```
armbian-sync
armbian-fix
```
即可去掉这个unsupported显示

**Comment by akwangl** [comment]
确实可以，不过既然官方支持都结束了还是换新版了
