### ISSUE TITLE
请教下，版本区别！

### ISSUE THREAD

**Issue by lg-yyds** [ophub/amlogic-s9xxx-armbian#2113]
[Armbian_noble_save_2024.02]
[Armbian_jammy_save_2024.02]
[Armbian_bullseye_save_2024.02]
[Armbian_bookworm_save_2024.02]
请教下各位大佬，这个几个版本的区别！谢谢！
N1盒子用那个版本好点。

**Comment by ophub** [comment]
前2个是Ubuntu系列，后两个是Debian系列，都好。

**Comment by manhuaxian** [comment]
大佬，更换清华源和中科大源后，更新不成功怎么办啊？E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/jammy/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:400::2 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/jammy-updates/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:400::2 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/jammy-backports/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:400::2 443]
E: Failed to fetch https://mirrors.tuna.tsinghua.edu.cn/ubuntu/dists/jammy-proposed/main/binary-arm64/Packages  404  Not Found [IP: 2402:f000:1:400::2 443]
E: Failed to fetch http://security.ubuntu.com/ubuntu/dists/jammy-security/main/binary-arm64/Packages  404  Not Found [IP: 2620:2d:4002:1::101 80]
E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by lg-yyds** [comment]
> 前2个是Ubuntu系列，后两个是Debian系列，都好。 第二个第四个目前是LTS版。

谢谢大佬解答！

**Comment by shijifeizhai** [comment]
> 前2个是Ubuntu系列，后两个是Debian系列，都好。 第二个第四个目前是LTS版。

我说为什么我这么喜欢jammy，几乎没出过问题。原来是LTS版
