### ISSUE TITLE
Fake Tanix TX3 Mini 2/16 GB has a new variant with S905L2-B

### ISSUE THREAD

**Issue by 833M0L3** [ophub/amlogic-s9xxx-armbian#2117]
**Device Information | 设备信息**
 - SOC: S905L2-B
 - Model Tanix TX3 Mini

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.76
 - Release:  jammy/bullseye

**Description**

It seems like there is a fake Tanix TX3 Mini variant out in the market claiming that it has S905W. What's surprising is that, upon opening the box, on the board, you can see the chip with S905W written on the top. But none of the S905W dtb succeeded in booting. So, we tried running it with S905L2 dtbs, both meson-gxl-s905l2-x7-5g.dtb & meson-gxl-s905l2-ipbs9505.dtb. And both managed to boot perfectly. So for those who are having problems with their newly bought TX3 Mini, try these dtb, it should boot. 

But I suggest that you return it, and try to find the genuine one with the S905W chip. It seems this S905L2 variant has some issues regarding the RAM capacity showing less than the actual.

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/59522309/4641526d-048e-4a80-8a13-0bc94120e420)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/59522309/fab0208a-4b01-43f4-bdd9-d92e424f81c3)

**Comment by 833M0L3** [comment]
More info of this box in here https://discourse.coreelec.org/t/tx3-mini-not-booting-new-board-b00-mx3mini-rev1-6/29458

**Comment by 833M0L3** [comment]
Firmware here if it's bricked https://discourse.coreelec.org/t/b00-mx3mini-ver1-7/50863

**Comment by ophub** [comment]
Thank you for sharing your method of usage.
