### ISSUE TITLE
中国升级内核下载速度慢解决方法

### ISSUE THREAD

**Issue by yicheng42** [ophub/amlogic-s9xxx-armbian#2119]
**Device Information | 设备信息**
 - SOC: [e.g. S905l]
 - Model [e.g. Mibox-4]

**Armbian Version | 24.2
 - Kernel Version: [e.g. 6.6.18]
 - Release: [e.g. noble]

升级内核
armbian-update
zh-CN下载如果速度慢，可以用下面方法下载后安装
wget https://hub.nuaa.cf/ophub/kernel/releases/download/kernel_stable/6.1.xx.tar.gz
tar -xvf 6.6.xx.tar.gz
cd 6.6.xx
armbian-update
​亲测好用

**Comment by ophub** [comment]
https://hub.nuaa.cf/ophub/kernel/releases/download/kernel_stable/6.1.79.tar.gz

类似这样的地址，我打不开。这个网站我访问不了。

**Comment by yicheng42** [comment]
> https://hub.nuaa.cf/ophub/kernel/releases/download/kernel_stable/6.1.79.tar.gz
> 
> 类似这样的地址，我打不开。这个网站我访问不了。

我上github也不行，我就挂梯子(vpn)

**Comment by yicheng42** [comment]
> https://hub.nuaa.cf/ophub/kernel/releases/download/kernel_stable/6.1.79.tar.gz
> 
> 类似这样的地址，我打不开。这个网站我访问不了。

毕竟跨国嘛

**Comment by laneydawf** [comment]
https://github.com/ophub/kernel/releases在这个页面下载内核然后上传到armbian随便一个目录，然后在上传内核的目录里armbian-update就好了。

**Comment by ophub** [comment]
armbian和OpenWrt，内核等编译的时候，需要从github及国外网站下载源码和软件包，一些国外网站在国内不能正常访问，这些编译在github上能正常运行。
