### ISSUE TITLE
TX3 Bluetooth not working

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#212]
TX3 with sp6330,
Bluetooth seems to work, but can't discover other device, Can anyone help me ?

```
root@lepotato:~# uname -a
Linux lepotato 5.16.18-flippy-71+ #65 SMP PREEMPT Mon Mar 28 16:24:49 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
root@lepotato:~# clear
root@lepotato:~# uname -a
Linux lepotato 5.16.18-flippy-71+ #65 SMP PREEMPT Mon Mar 28 16:24:49 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
root@lepotato:~# dmesg | grep -i blue
[    7.462244] Bluetooth: Core ver 2.22
[    7.469636] Bluetooth: Starting self testing
[    7.486091] Bluetooth: ECDH test passed in 9083 usecs
[    7.496353] Bluetooth: SMP test passed in 2852 usecs
[    7.503536] Bluetooth: Finished self testing
[    7.513492] NET: Registered PF_BLUETOOTH protocol family
[    7.521028] Bluetooth: HCI device and connection manager initialized
[    7.528994] Bluetooth: HCI socket layer initialized
[    7.536214] Bluetooth: L2CAP socket layer initialized
[    7.549743] Bluetooth: SCO socket layer initialized
[    7.974386] Bluetooth: HCI UART driver ver 2.3
[    7.984862] Bluetooth: HCI UART protocol H4 registered
[    7.984880] Bluetooth: HCI UART protocol BCSP registered
[    7.984992] Bluetooth: HCI UART protocol LL registered
[    7.984996] Bluetooth: HCI UART protocol ATH3K registered
[    8.009998] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    8.049337] Bluetooth: HCI UART protocol Intel registered
[    8.049761] Bluetooth: HCI UART protocol Broadcom registered
[    8.049812] Bluetooth: HCI UART protocol QCA registered
[    8.049816] Bluetooth: HCI UART protocol AG6XX registered
[    8.049854] Bluetooth: HCI UART protocol Marvell registered
[    8.429703] Bluetooth: hci0: BCM: chip id 62
[    8.430198] Bluetooth: hci0: BCM: features 0x0f
[    8.431903] Bluetooth: hci0: BCM4330B1
[    8.468578] Bluetooth: hci0: BCM4330B1 (002.001.003) build 0000
[    8.469997] Bluetooth: hci0: BCM4330B1 'brcm/BCM4330B1.hcd' Patch
[    9.341342] Bluetooth: hci0: Win8 Tablet Semco SWB-B42G - BCM4330B1 37.4 MHz Class 2 NoExtLNA
[    9.341375] Bluetooth: hci0: BCM4330B1 (002.001.003) build 1316
[   13.603814] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   13.603837] Bluetooth: BNEP filters: protocol multicast
[   13.603861] Bluetooth: BNEP socket layer initialized
root@lepotato:~# hciconfig -a
hci0:	Type: Primary  Bus: UART
	BD Address: 43:30:A0:00:1F:AC  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:7213 acl:0 sco:0 events:657 errors:0
	TX bytes:57477 acl:0 sco:0 commands:656 errors:0
	Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
	Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3 
	Link policy: RSWITCH SNIFF 
	Link mode: SLAVE ACCEPT 
	Name: 'lepotato'
	Class: 0x000000
	Service Classes: Unspecified
	Device Class: Miscellaneous, 
	HCI Version: 4.0 (0x6)  Revision: 0x1524
	LMP Version: 4.0 (0x6)  Subversion: 0x4103
	Manufacturer: Broadcom Corporation (15)

```

![image](https://user-images.githubusercontent.com/9335046/160639080-0ca8f316-da00-4fb1-9855-4f75ea44332d.png)
![image](https://user-images.githubusercontent.com/9335046/160639271-c36b6899-baf3-4287-9cff-594319310b99.png)

**Comment by danuzz** [comment]
To get wifi working:

`sudo mv /lib/firmware/brcm/brcmfmac4330-sdio.txt /lib/firmware/brcm/brcmfmac4330-sdio.txt.old`
`sudo ln -s  /lib/firmware/brcm/brcmfmac-ap6330-sdio.txt /lib/firmware/brcm/brcmfmac4330-sdio.txt`
reboot...

**Comment by EastWoodYang** [comment]
> To get wifi working:
> 
> ```
> sudo mv /lib/firmware/brcm/brcmfmac4330-sdio.txt /lib/firmware/brcm/brcmfmac4330-sdio.txt.old
> sudo ln -s  /lib/firmware/brcm/brcmfmac-ap6330-sdio.txt /lib/firmware/brcm/brcmfmac4330-sdio.txt
> ```
> 
> reboot...

Thank you so much :-)  wifi working again, but bluetooth still can't discover other  bluetooth device.

**Comment by ophub** [comment]
1. 使用`dmesg | grep Blue*`确认下蓝牙驱动正常
![Snip20220330_3](https://user-images.githubusercontent.com/68696949/160759302-5e052025-b23f-4546-acd4-78517806431a.png)

2. 执行`sudo armbian-config`，进去后选择`Network`，接着选择`BT Install`
3. 执行`sudo apt install pulseaudio-module-bluetooth` 安装`pulseaudio`组件
4. 执行`sudo killall pulseaudio && pulseaudio --start` 启动`pulseaudio`服务
5. 执行`sudo hciconfig -a`查看蓝牙控制器信息
6. 执行`sudo hciconfig hci0 up`打开蓝牙控制器
7. 执行`sudo bluetoothctl`打开蓝牙管理器
8. 执行`power on`
9. 执行`discoverable on`
10. 执行`agent on`
11. 执行`scan on`搜集周围的蓝牙设备，记录下要连接的`设备地址`
12. 执行`trust <设备地址>`添加信任设备
13. 执行`pair <设备地址>`进行配对，此时要配对的设备上可能会弹出提示，点确认
14. 执行`connect <设备地址>`即可顺利连接蓝牙
15. 执行`info <设备地址>`可以确认状态

**Comment by EastWoodYang** [comment]
> 1. 使用`dmesg | grep Blue*`确认下蓝牙驱动正常
>    ![Snip20220330_3](https://user-images.githubusercontent.com/68696949/160759302-5e052025-b23f-4546-acd4-78517806431a.png)
> 2. 执行`sudo armbian-config`，进去后选择`Network`，接着选择`BT Install`
> 3. 执行`sudo apt install pulseaudio-module-bluetooth` 安装`pulseaudio`组件
> 4. 执行`sudo killall pulseaudio`结束当前`pulseaudio`服务
> 5. 执行`pulseaudio --start` 启动`pulseaudio`服务
> 6. 执行`sudo hciconfig -a`查看蓝牙控制器信息
> 7. 执行`sudo hciconfig hci0 up`打开蓝牙控制器
> 8. 执行`sudo bluetoothctl`打开蓝牙管理器
> 9. 执行`power on`
> 10. 执行`discoverable on`
> 11. 执行`agent on`
> 12. 执行`scan on`搜集周围的蓝牙设备，记录下要连接的`设备地址`
> 13. 执行`trust <设备地址>`添加信任设备
> 14. 执行`pair <设备地址>`进行配对，此时要配对的设备上可能会弹出提示，点确认
> 15. 执行`connect <设备地址>`即可顺利连接蓝牙
> 16. 执行`info <设备地址>`可以确认状态

我刚刚替换了 BCM4330B1.hcd，找的是这个 http://jwrdegoede.danny.cz/brcm-firmware/BCM4330B1.hcd，蓝牙能搜索到其他蓝牙设备，也能被其他设备搜索到了

**Comment by EastWoodYang** [comment]
唉、还是有问题。。。
跟换了[BCM4330B1.hcd](http://jwrdegoede.danny.cz/brcm-firmware/BCM4330B1.hcd)，蓝牙能搜索到其他蓝牙设备，也能被其他设备搜索到了，但是还是不能匹配，头大。

**Comment by ophub** [comment]
https://zhuanlan.zhihu.com/p/426857066

我可以使用
