### ISSUE TITLE
请求增加对RK3228H的支持

### ISSUE THREAD

**Issue by allonmymind** [ophub/amlogic-s9xxx-armbian#2123]
Eaidk310使用的是RK3228H，jock的RK3318的固件均能使用，链接如下https://users.armbian.com/jock/rk3318/
习惯用ophub的固件了，稳定功能齐全，能否添加支持，对大佬来说应该不难

**Comment by 13584452567** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/pull/2129

**Comment by allonmymind** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian/pull/2129

Rk3228H表示刷完没有任何反应……
