### ISSUE TITLE
所有images的/etc/armbian-release内部分内容均一致

### ISSUE THREAD

**Issue by LSP0123** [ophub/amlogic-s9xxx-armbian#2125]
N1的/etc/armbian-release内容
```
# PLEASE DO NOT EDIT THIS FILE
BOARD=odroidn2
BOARD_NAME="Aml.S905d"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
BUILD_REPOSITORY_COMMIT=6cd3981
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=rebuild
BOARD_TYPE=diy
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
FORCE_BOOTSCRIPT_UPDATE=no
VENDOR="Armbian-unofficial"
VENDORDOCS="https://docs.armbian.com/"
VENDORURL="https://duckduckgo.com/"
VENDORSUPPORT="https://community.armbian.com/"
VENDORBUGS="https://armbian.atlassian.net/"
```
pantherx2
```
# PLEASE DO NOT EDIT THIS FILE
BOARD=odroidn2
BOARD_NAME="panther-x2"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
BUILD_REPOSITORY_COMMIT=6cd3981
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=rebuild
BOARD_TYPE=diy
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
FORCE_BOOTSCRIPT_UPDATE=no
VENDOR="Armbian-unofficial"
VENDORDOCS="https://docs.armbian.com/"
VENDORURL="https://duckduckgo.com/"
VENDORSUPPORT="https://community.armbian.com/"
VENDORBUGS="https://armbian.atlassian.net/"
FORCE_BOOTSCRIPT_UPDATE="no"
BOOTSCRIPT_DST="boot.cmd"
VERSION=24.2.0-trunk
REVISION=24.2.0-trunk

```
相同的字段有：BOARD、BOARDFAMILY、LINUXFAMILY
hold的几个包应该是因为board不一样导致的，生成的images都使用了odroidn2这个板子的，实际上应该是针对不同板子使用不同的deb

```
casaos@n1 ~ % apt search aml-s9xx-box           
正在排序... 完成
全文搜索... 完成  
armbian-bsp-cli-aml-s9xx-box/jammy 23.11.1 arm64
  Armbian CLI BSP for board 'aml-s9xx-box' - transitional package

armbian-bsp-cli-aml-s9xx-box-current/jammy 23.11.1 arm64
  Armbian CLI BSP for board 'aml-s9xx-box' branch 'current'

armbian-bsp-cli-aml-s9xx-box-edge/jammy 23.8.1 arm64
  Armbian CLI BSP for board 'aml-s9xx-box' branch 'edge'

armbian-bsp-desktop-aml-s9xx-box-current/jammy 23.11.1 arm64
  Armbian bsp-desktop for release jammy, common for all desktop environments on arm64 aml-s9xx-box machines on current branch

armbian-bsp-desktop-aml-s9xx-box-edge/jammy 23.8.1 arm64
  Armbian bsp-desktop for release jammy, common for all desktop environments on arm64 aml-s9xx-box machines on edge branch

linux-u-boot-aml-s9xx-box-current/jammy 23.11.1 arm64
  Das U-Boot for aml-s9xx-box

linux-u-boot-aml-s9xx-box-edge/jammy 23.8.1 arm64
  Das U-Boot for aml-s9xx-box

casaos@n1 ~ % apt search panther-x2  
正在排序... 完成
全文搜索... 完成  
armbian-bsp-cli-panther-x2/jammy 23.11.1 arm64
  Armbian CLI BSP for board 'panther-x2' - transitional package

armbian-bsp-cli-panther-x2-current/jammy 23.11.1 arm64
  Armbian CLI BSP for board 'panther-x2' branch 'current'

armbian-bsp-cli-panther-x2-edge/jammy 23.8.1 arm64
  Armbian CLI BSP for board 'panther-x2' branch 'edge'

armbian-bsp-desktop-panther-x2-current/jammy 23.11.1 arm64
  Armbian bsp-desktop for release jammy, common for all desktop environments on arm64 panther-x2 machines on current branch

armbian-bsp-desktop-panther-x2-edge/jammy 23.8.1 arm64
  Armbian bsp-desktop for release jammy, common for all desktop environments on arm64 panther-x2 machines on edge branch

linux-u-boot-panther-x2-current/jammy 23.11.1 arm64
  Das U-Boot for panther-x2

linux-u-boot-panther-x2-edge/jammy 23.8.1 arm64
  Das U-Boot for panther-x2

```

#1470 
#1249 

BOARDFAMILY字段应该就是控制#1249里的那个“危险的包”
按照[armbian的说法](https://github.com/armbian/build/blob/master/config/boards/README.md)，BOARDFAMILY对于每个板子应该是不一样的
RK的soc生成的images里，LINUXFAMILY应该是rockchip-rk3588/rk35xx等
在armbian里，这些参数（armbian-release里的并不是参数，而似乎是由上游配置文件生成的？）似乎会影响到images的编译生成
model_database.conf里的配置并未传递到buildimage流程里

**Comment by ophub** [comment]
BOARD_NAME="panther-x2"

只用到了这一个值，在重构时会更新，其他没用到的没更新

**Comment by ophub** [comment]
包名不同，而且我在重构时已经删除了这个包了。
重构的盒子大部分都是上游armbian不支持的，安装可能会导致使用了错误的u-boot而变砖。
panther-x2设备上游也有，但是我不确定是否可以在我重构的系统里安装，理论上上游的u-boot是可以使用的。

**Comment by greatofdream** [comment]
> BOARD_NAME="panther-x2"
> 
> 只用到了这一个值，在重构时会更新，其他没用到的没更新

我发现编译Armbian时workflow调用`compile.sh`使用的Board参数始终是`odroidn2`（S922X ），rebuild时并没有重新编译Armbian，而是替换了一些文件，包括uboot.bin与dtb文件（可能还有其它的文件）。如果Amlogic使用了新的不是arm64指令集，是不是就无法用`odroidn2`这个默认参数编译armbian了？ @ophub

**Comment by ophub** [comment]
这个仓库的Actions构建有日志，从日志可以看到过程，第一步是使用arbian的官方设置进行一个指定armbian系统的构建，我默认使用了odroidn2，你也可以选用官方board支持的其他选项，我在仓库的首页文档里也说明了使用其他任意board或者官方已经构建好的img的方法，在actions里也有专门的独立工作流文件。

这对我来说只是想获得最新的rootfs而已，忽略他安装的差异化的包，例如楼上的linux-u-boot-*或者armbian-bsp-cli-*等等针对专门的设备有差异的包。这些包在我rebuild的时候，在我使用的这个armbian.img里已知的有不适宜的包都被我禁用或移除了（千万别启用或者强制安装更新这些我禁用的包，安装和替换了不适用的u-boot就无法启动系统了，千万不要尝试安装楼主提到的armbian-bsp-cli-xxx.deb和linux-u-boot-xxx.deb），包括原始系统里的boot,firmware、u-boot、modules等。我把这些替换为了我其他几个仓库里保存的相关文件。

官方的构建也是这么个过程，你看actions里官方构建的过程，从构建armbian.img的运行的日志看，也是下载并解包已经预构建好的rootfs.tar.gz包，然后制作img，安装相关设备的差异化deb软件包。不同设备的armbian系统，95%以上的内容是相同的，差异的主要是 build/output/debs/ 目录下的几个包，例如 armbian-bsp-cli-xxx.deb, linux-u-boot-xxx.deb, linux-image-xxx.deb, linux-headers-xxx.deb, linux-dtb-xxx.deb, 这些包是针对不同设备构建的专用软件包，而我在重构不同设备使用的armbian的时候，把官方系统里这些针对专门设备专用的软件包都删除或者禁用了，然后替换为为不同设备使用的对应的文件。

我这里的固件大部分是官方不支持的，少量设备在官方也有。为了让这些设备也能使用armbian，在这里进行了重构，替换了我上面说的相关部分，使用适配不同设备的组装件进行重新组配，只是官方使用的是deb包安装方法，我使用的是下载文件复制粘帖到指定目录，操作命令不同但结果相同，都是根据设备的差异进行不同软件/文件的预设。我移除了官方差异化的deb后替换的对应文件有 dtb-xxx.tar.gz, boot-xxx.tar.gz, header-xxx.tar.gz, modules-xxx.tar.gz, 以及 u-boot和firmware仓库里对应的文件等。

我没有编译适配不同armbian设备的deb包，因为编译后安装的结果和我直接下载复制粘帖这些文件的结果是相同的，而且这些文件和我的另外一个仓库的openwrt也是通用的，如果我编译armbian专用的deb那么在openwrt里无法使用，为了不同系统的通用，使用原文件复制粘帖是很好的方法。这些方法也同时适配了flippy大佬在早期进行盒子圈适配armbian/openwrt时制作和使用相关文件的标准。一套文件，多系统复用，这是很好的解决方案。

这些相关文件在这些仓库都是支持的，盒子圈也习惯了这种安装和更新系统及内核的方法：
https://github.com/ophub/amlogic-s9xxx-armbian
https://github.com/ophub/amlogic-s9xxx-openwrt
https://github.com/ophub/flippy-openwrt-actions
https://github.com/unifreq/openwrt_packit
https://github.com/unifreq/rk-ubuntu-build

如果只考虑armbian使用的话，把我们制作的boot-xxx.tar.gz等文件打包成deb格式，就使用了和armbian官方一样的安装软件包的方法，但是这样armbian就孤立于openwrt独立使用了，这看起来没有意义，目的都是更新相关文件，使用多系统通用的维护起来更简单。有的人喜欢armbian，当给这个设备适配好了，那么意味着openwrt也可以使用，反之亦然。

**Comment by Vector-Cross** [comment]
> 这个仓库的Actions构建有日志，从日志可以看到过程，第一步是使用arbian的官方设置进行一个指定armbian系统的构建，我默认使用了odroidn2，你也可以选用官方board支持的其他选项，我在仓库的首页文档里也说明了使用其他任意board或者官方已经构建好的img的方法，在actions里也有专门的独立工作流文件。
> 
> 这对我来说只是想获得最新的rootfs而已，忽略他安装的差异化的包，例如楼上的linux-u-boot-*或者armbian-bsp-cli-*等等针对专门的设备有差异的包。这些包在我rebuild的时候，在我使用的这个armbian.img里已知的有不适宜的包都被我禁用或移除了（千万别启用或者强制安装更新这些我禁用的包，安装和替换了不适用的u-boot就无法启动系统了，千万不要尝试安装楼主提到的armbian-bsp-cli-xxx.deb和linux-u-boot-xxx.deb），包括原始系统里的boot,firmware、u-boot、modules等。我把这些替换为了我其他几个仓库里保存的相关文件。
> 
> 官方的构建也是这么个过程，你看actions里官方构建的过程，从构建armbian.img的运行的日志看，也是下载并解包已经预构建好的rootfs.tar.gz包，然后制作img，安装相关设备的差异化deb软件包。不同设备的armbian系统，95%以上的内容是相同的，差异的主要是 build/output/debs/ 目录下的几个包，例如 armbian-bsp-cli-xxx.deb, linux-u-boot-xxx.deb, linux-image-xxx.deb, linux-headers-xxx.deb, linux-dtb-xxx.deb, 这些包是针对不同设备构建的专用软件包，而我在重构不同设备使用的armbian的时候，把官方系统里这些针对专门设备专用的软件包都删除或者禁用了，然后替换为为不同设备使用的对应的文件。
> 
> 我这里的固件大部分是官方不支持的，少量设备在官方也有。为了让这些设备也能使用armbian，在这里进行了重构，替换了我上面说的相关部分，使用适配不同设备的组装件进行重新组配，只是官方使用的是deb包安装方法，我使用的是下载文件复制粘帖到指定目录，操作命令不同但结果相同，都是根据设备的差异进行不同软件/文件的预设。我移除了官方差异化的deb后替换的对应文件有 dtb-xxx.tar.gz, boot-xxx.tar.gz, header-xxx.tar.gz, modules-xxx.tar.gz, 以及 u-boot和firmware仓库里对应的文件等。
> 
> 我没有编译适配不同armbian设备的deb包，因为编译后安装的结果和我直接下载复制粘帖这些文件的结果是相同的，而且这些文件和我的另外一个仓库的openwrt也是通用的，如果我编译armbian专用的deb那么在openwrt里无法使用，为了不同系统的通用，使用原文件复制粘帖是很好的方法。这些方法也同时适配了flippy大佬在早期进行盒子圈适配armbian/openwrt时制作和使用相关文件的标准。一套文件，多系统复用，这是很好的解决方案。
> 
> 这些相关文件在这些仓库都是支持的，盒子圈也习惯了这种安装和更新系统及内核的方法： https://github.com/ophub/amlogic-s9xxx-armbian https://github.com/ophub/amlogic-s9xxx-openwrt https://github.com/ophub/flippy-openwrt-actions https://github.com/unifreq/openwrt_packit https://github.com/unifreq/rk-ubuntu-build
> 
> 如果只考虑armbian使用的话，把我们制作的boot-xxx.tar.gz等文件打包成deb格式，就使用了和armbian官方一样的安装软件包的方法，但是这样armbian就孤立于openwrt独立使用了，这看起来没有意义，目的都是更新相关文件，使用多系统通用的维护起来更简单。有的人喜欢armbian，当给这个设备适配好了，那么意味着openwrt也可以使用，反之亦然。

这段话是作者在解释其 Armbian 构建系统的设计哲学、工作原理以及为何要采用与官方不同的方法。我来为您总结核心思想：

核心观点总结
作者的核心目标是：“一套核心文件，适配多种设备，并在 Armbian 和 OpenWrt 系统之间通用”。

为了实现这个目标，他摒弃了 Armbian 官方的部分做法，采用了一套自创的、更灵活的“组装”方案。

详细分解
1. 对官方 Armbian 构建过程的剖析
官方流程：下载通用 rootfs -> 制作镜像 -> 通过安装专用的 .deb 包来为不同设备注入差异化内容（如 U-Boot、内核、设备树等）。

关键差异点：这些专用的 .deb 包（如 armbian-bsp-cli-*.deb, linux-u-boot-*.deb）是官方区分不同设备支持的关键。

2. 作者的重构方法：替换而非安装
移除官方包：作者在重构时，主动禁用或移除了上述那些设备专用的 .deb 包。因为他认为这些包对于他适配的许多“非官方”设备是不兼容的，强行安装会导致系统无法启动。

文件替换：他采用了一种更底层、更直接的方法：直接下载并替换文件。这些文件包括：

dtb-*.tar.gz（设备树）

boot-*.tar.gz（内核和启动文件）

modules-*.tar.gz（内核模块）

以及其他仓库中的 U-Boot 和固件文件。

3. 根本原因：追求多系统通用性
这是作者最核心的论点：为什么不打包成 .deb？

.deb 的局限性：如果将他替换的文件打包成 Armbian 专用的 .deb 包，那么这些组件就被“锁死”在 Armbian 系统里了。

通用性的优势：他使用的 *.tar.gz 文件格式是通用的，同一套 boot-*.tar.gz、dtb-*.tar.gz 等文件，既可以用于组装 Armbian，也可以用于组装 OpenWrt。这极大地简化了维护工作。

生态继承：这种方法继承并兼容了社区前辈（如 flippy）为电视盒子圈建立的标准，形成了统一的文件规范。

4. 给用户的强烈警告
不要安装官方差异化包：作者反复强调，千万不要在他已经重构好的系统上尝试安装或更新官方的 armbian-bsp-cli-*.deb 或 linux-u-boot-*.deb 等包，这会覆盖他精心配置的专用文件，导致设备无法启动。

一个生动的比喻
官方 Armbian：像一家品牌电脑商。他们生产通用的主板和机箱（rootfs），然后为不同型号的电脑安装特定的官方驱动和软件（专用的 .deb 包）。

作者的 Armbian：像一个DIY 组装机玩家。他购买通用的主板和机箱（rootfs），但他不用品牌商的驱动光盘，而是自己去网上找各个硬件（CPU、显卡、主板）最兼容、性能最好的第三方驱动（boot-*.tar.gz, dtb-*.tar.gz 等），然后手动安装上去。

结论
作者表达了一套完整的技术选型和设计哲学：
他为了最大化兼容非官方设备和实现 Armbian/OpenWrt 两大系统的文件共享与统一维护，选择了一条与官方分道扬镳但符合社区实践的道路。他的系统是一个“精心组装的混合体”，其稳定性依赖于他提供的特定文件组合，一旦被官方的标准化安装流程干扰，这个平衡就会被打破。
