### ISSUE TITLE
how to build wifi module for s905(shumashixun Q5)

### ISSUE THREAD

**Issue by Jasonbroker** [ophub/amlogic-s9xxx-armbian#2126]
Hi！
I used a recomplied ko file on BBS but failed
`could not insert '8189es': Exec format error`
the main reason is wrong kernel version.
So I tried to compile the driver by myself，it said
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/7604558/b9fe837c-3b31-4e75-9a62-89d3ab10973f)

How could I install linux-headers？
thanks for help

**Comment by ophub** [comment]
```
armbian-sync
armbian-update -u dev
```
