### ISSUE TITLE
Panther-X2 对docker Android的支持问题

### ISSUE THREAD

**Issue by ASTWY** [ophub/amlogic-s9xxx-armbian#2130]
使用docker部署[remote-android/redroid-doc](https://github.com/remote-android/redroid-doc)时，遇到了binder_linux 无法使用的问题，根据文档尝试启用CONFIG_ANDROID_BINDER_IPC等相关设置重编译内核后，binder_linux 依然处于不可用的状态。 
问题可能出在哪里？应该如何解决呢？

**Comment by ophub** [comment]
如果想在当前armbian系统里自定义编译内核，建议第一步是更新到dev系列内核：
https://github.com/ophub/kernel/releases/tag/kernel_dev

使用类似下面的命令切换到dev
`armbian-update -u dev -k 5.15`

**Comment by ASTWY** [comment]
我已经先将内核更新至5.15 dev版本，但依然无法成功编译一份带binder_linux的内核，是因为我使用了wsl的Ubuntu20.04交叉编译的原因嘛？

**Comment by ophub** [comment]
armbian-ke rne l

**Comment by Alpinee** [comment]
大佬解决了吗，我也遇到这个问题了，没有binder_linux

**Comment by akwangl** [comment]
好家伙我也在搞这个，发现就是编译不进去。而且内核还没有ashmem_linux这个

**Comment by akwangl** [comment]
https://foxi.buduanwang.vip/linux/docker/2699.html/可以试试这个帖子的内核
