### ISSUE TITLE
Armbian在第二次启动出现Read Only System问题，O大3月的6.1.79bookworm和F大的5.15bullseye均发现此问题，确认无插入Android，执行mount -o remount, rw /命令返回错误提示

### ISSUE THREAD

**Issue by Shrinft** [ophub/amlogic-s9xxx-armbian#2131]
**Device Information | 设备信息**
 - SOC: [e.g. S905L3]
 - Model [e.g. CM211-1(MC022)]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100，6.1.79 F大/O大]
 - Release: [e.g. bullseye/bookworm]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

Armbian在第二次启动出现Read Only System问题，O大3月的6.1.79bookworm和F大的5.15bullseye均发现此问题，确认无插入Android，执行mount -o remount, rw /命令返回错误提示，第一次启动完全没有问题。

root@armbian:~# mount -o remount, rw /
mount: /: cannot remount rw read-write, is write-protected.
       dmesg(1) may have more information after failed mount system call.
mount: (hint) your fstab has been modified, but systemd still uses
       the old version; use 'systemctl daemon-reload' to reload.
root@armbian:~#

root@armbian:~# armbian-software
[ STEPS ] Start installing the necessary dependencies...
Reading package lists... Done
E: List directory /var/lib/apt/lists/partial is missing. - Acquire (30: Read-only file system)
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (30: Read-only file system)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (30: Read-only file system)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'apt' instead of 'apt-transport-https'
Package net-tools is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package dnsmasq-base is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

W: Not using locking for read only lock file /var/lib/dpkg/lock-frontend

**Comment by Shrinft** [comment]
root@armbian:~# systemctl daemon-reload
root@armbian:~# 'systemctl daemon-reload'
systemctl daemon-reload: command not found
root@armbian:~# mount -o remount, rw /
mount: /: cannot remount rw read-write, is write-protected.
       dmesg(1) may have more information after failed mount system call.
root@armbian:~#

**Comment by Shrinft** [comment]
似乎仅仅只有EXT4有此问题，我查阅过别人的错误报告，他们用mount -o remount, rw /解决了

**Comment by Shrinft** [comment]
顺带问一下安装桌面后怎么SHH连接

**Comment by Shrinft** [comment]
我说的是第二次启动，不是第二次重启。第一次启动后输入命令reboot，后没有获得ip(十分钟以内)，正常的情况下，两三分钟就已经获得IP了。所以我推断reboot然后没有启成功启动。我是拨电又关机在启动才获得ip

**Comment by jjjyyyllll** [comment]
m401a也遇到了，以为emmc坏了，短接重刷了一遍安卓发现正常，又重头刷一遍才解决

**Comment by sohow** [comment]
+1
mount: /: cannot remount rw read-write, is write-protected

**Comment by Shrinft** [comment]
解决了，修改/etc/fstab中的errors=remount-ro改为rw即可，并用Diskgenius激活ROOTFS分区
