### ISSUE TITLE
如何打开armbian的rga驱动

### ISSUE THREAD

**Issue by 610449424** [ophub/amlogic-s9xxx-armbian#2133]
萌新小白，网上找到一个jellyfin-mpp的版本，硬件解码需要/dev/rga接口才能用，查看设备树发现有节点rga@ff680000，但dev文件夹下没有rga这个接口，用armbian-config命令没找到驱动的选项，看网上教程在内核目录下用make-menuconfig命令，但是操作后出现如下报错，网上查了很久，安装了各种依赖，libc6也安装了还是同样的报错不知道还缺少什么，还是用别的什么方法
root@armbian:/usr/src/linux-headers-6.1.76-happy-new-year# make menuconfig
HOSTCC  scripts/kconfig/confdata.o
scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory
make[1]: *** [scripts/Makefile.host:128: scripts/kconfig/confdata.o] Error 127
make[1]: *** Deleting file 'scripts/kconfig/confdata.o'
make: *** [Makefile:701: config] Error 2

**Comment by 610449424** [comment]
哦，我查资料知道了，有两套rga驱动，开源的走的v4l所以我找不到，但是不知道我下的jellyfin支不支持

**Comment by GoldenHuskyDog** [comment]
> 萌新小白，网上找到一个jellyfin-mpp的版本，硬件解码需要/dev/rga接口才能用，查看设备树发现有节点rga@ff680000，但dev文件夹下没有rga这个接口，用armbian-config命令没找到驱动的选项，看网上教程在内核目录下用make-menuconfig命令，但是操作后出现如下报错，网上查了很久，安装了各种依赖，libc6也安装了还是同样的报错不知道还缺少什么，还是用别的什么方法 root@armbian:/usr/src/linux-headers-6.1.76-happy-new-year# make menuconfig HOSTCC scripts/kconfig/confdata.o scripts/basic/fixdep: error while loading shared libraries: libc.so.6: cannot open shared object file: No such file or directory make[1]: *** [scripts/Makefile.host:128: scripts/kconfig/confdata.o] Error 127 make[1]: *** Deleting file 'scripts/kconfig/confdata.o' make: *** [Makefile:701: config] Error 2

大佬，jellyfin能硬件解码吗
