### ISSUE TITLE
 kernel:[   96.715845] Disabling IRQ #59

### ISSUE THREAD

**Issue by QINZY8** [ophub/amlogic-s9xxx-armbian#2139]
**Device Information | 设备信息**
 - SOC: [e.g. rk3399]
 - Model [e.g. tvi3315a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.79]
 - Release: [e.g. Bookworm]

**Describe the bug | 问题描述**
过一会就会出现这条 kernel:[   96.715845] Disabling IRQ #59

**Comment by QINZY8** [comment]
![屏幕截图 2024-03-06 214835](https://github.com/ophub/amlogic-s9xxx-armbian/assets/126463346/5eec6a89-5b82-4687-9d6a-267512ad8043)

**Comment by Zane-E** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/files/14632500/rk3399-tvi3315a.zip
