### ISSUE TITLE
3月30号版s905d写入emmc后使用中报如下错误：

### ISSUE THREAD

**Issue by afeiy** [ophub/amlogic-s9xxx-armbian#214]
RROR: ld.so: object '/usr/lib/aarch64-linux-gnu/libjemalloc.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.

**Comment by ophub** [comment]
![Snip20220331_2](https://user-images.githubusercontent.com/68696949/161010608-c54a667d-47cd-49c6-853c-185ea5cbf673.png)
![Snip20220331_3](https://user-images.githubusercontent.com/68696949/161010620-b46f0e81-768c-4329-9cf3-1357e56d1f96.png)
![Snip20220331_5](https://user-images.githubusercontent.com/68696949/161010624-bd4ef8f1-dd66-4993-950b-62ceaf727a83.png)
![Snip20220331_6](https://user-images.githubusercontent.com/68696949/161010627-f9edd0d1-28a8-4e78-8b9d-2548da301d90.png)

**Comment by dinhchinh82** [comment]
@ophub which filesystem should select, ext4 or btrfs?

**Comment by ophub** [comment]
Both file systems have their own characteristics and can be used normally
