### ISSUE TITLE
N1 启动过程的中的几个错误信息

### ISSUE THREAD

**Issue by 3nyaww** [ophub/amlogic-s9xxx-armbian#2143]
**Device Information | 设备信息**
 - SOC: S905D
 - Model N1

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.151
 - Release: jammy

**Describe the bug | 问题描述**

启动中的几个错误信息：
1：
wwayne@armbian:~$ sudo dmesg | grep hub
[    0.000000] Linux version 5.15.151-ophub (root@fv-az714-549) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009, GNU ld (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 2.41.0.20231009) #1 SMP PREEMPT Wed Mar 6 22:46:40 EST 2024
[    2.644921] usbcore: registered new interface driver hub
[    5.872714] usb usb1: Manufacturer: Linux 5.15.151-ophub xhci-hcd
[    5.884049] hub 1-0:1.0: USB hub found
[    5.887336] hub 1-0:1.0: 2 ports detected
[    5.919606] usb usb2: Manufacturer: Linux 5.15.151-ophub xhci-hcd
[    5.930806] hub 2-0:1.0: USB hub found
**[    5.934288] hub 2-0:1.0: config failed, hub doesn't have any ports! (err -19)**

2:
wwayne@armbian:~$ sudo dmesg | grep debugfs
**[   10.241286] debugfs: Directory 'c1105400.audio-controller' with parent 'P230-Q200' already present!**
**[   10.244837] debugfs: Directory 'c1105400.audio-controller' with parent 'P230-Q200' already present!**

3:
wwayne@armbian:~$ sudo dmesg | grep brcmfmac
[   10.641597] brcmfmac: F1 signature read @0x18000000=0x15264345
[   10.649438] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
**[   10.653744] brcmfmac mmc0:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.phicomm,n1.bin failed with error -2**
[   10.861783] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[   10.905096] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
[   11.175858] usbcore: registered new interface driver brcmfmac

请问何解？

**Comment by ophub** [comment]
禁用无线服务，或者连接上一个无线网络，或者忽略不管

**Comment by 3nyaww** [comment]
> 禁用无线服务，或者连接上一个无线网络，或者忽略不管

是for第一个error吗？
