### ISSUE TITLE
请求搞个极简纯Debian或Ubuntu

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#2144]
比如像 https://github.com/devmfc/debian-on-amlogic  这样的，才100兆左右 :-)

比如它的内核https://github.com/devmfc/linux/tree/meson64-6.8

**Comment by ophub** [comment]
构建选择mini即可，之前有，我观察了一段时间下载量发现很少人下载就移除了，你有需求自己改一下actions即可

**Comment by EastWoodYang** [comment]
是什么时候移除的？我看看，是debian或Ubuntu嘛？不是armbian哦

**Comment by ophub** [comment]
Armbian有Ubuntu和Debian两个分支的镜像。这个仓库没纯血Ubuntu/debian，你去他们的官网可以找到多种版本。

**Comment by EastWoodYang** [comment]
有计划搞个纯血debian和Ubuntu构建仓库不？

**Comment by ophub** [comment]
没有

**Comment by EastWoodYang** [comment]
dada , 能指导下 怎么构建mini 镜像不，多提示下 :-)

**Comment by ophub** [comment]
mini: BUILD_MINIMAL=yes

https://github.com/ophub/amlogic-s9xxx-armbian/blob/8f56cad67753f94b614b4a8d21116d1308c7ca82/.github/workflows/build-armbian.yml#L287

**Comment by EastWoodYang** [comment]
感谢感谢

**Comment by EastWoodYang** [comment]
改了下，构建出来的包大小感觉还是有点大，能搞到100-200兆不，追求极致 :-)

![1710082380887](https://github.com/ophub/amlogic-s9xxx-armbian/assets/9335046/9e26b189-b4fe-422c-9486-7a9870e946b2)

**Comment by mia0x75** [comment]
这个需要标记以下，现在包里面的确有很多自己的东西，感觉还是尽量接近原生版本尽量精简比较好。

**Comment by ophub** [comment]
原生版本可以到armbian官方下载里找到。

这是社区版，为了支持官方没有的其他盒子的使用，需要添加必要的补充u-boot文件，内核也换成了flippy维护的内核，我为了让使用更方便还添加了10几个armbian-xxx的命令。
