### ISSUE TITLE
请求增加对tb-ls339的支持

### ISSUE THREAD

**Issue by chute8427** [ophub/amlogic-s9xxx-armbian#2146]
SOC: RK3399
Model: tb-ls339
2+16 GB
 https://github.com/liwei19920307/armbian/commit/d14c70ed2f8f857413c2c7fb9f2485a1c7088505
已编译好的armbian和原厂android8固件以及原机dts文件：https://pan.baidu.com/s/1S5w8zho8PFTtfqR9O32Jhg?pwd=6dl3

**Comment by chute8427** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/125569974/011790a4-2227-45cf-b0d0-8882ed49e59c)
测试 一切正常

**Comment by ophub** [comment]
谢谢你的分享，我添加到了支持列表里了。

**Comment by z-storm666** [comment]
> SOC: RK3399 Model: tb-ls339 2+16 GB [liwei19920307/armbian@d14c70e](https://github.com/liwei19920307/armbian/commit/d14c70ed2f8f857413c2c7fb9f2485a1c7088505) 已编译好的armbian和原厂android8固件以及原机dts文件：https://pan.baidu.com/s/1S5w8zho8PFTtfqR9O32Jhg?pwd=6dl3

您好，这个网盘链接过期了，能否麻烦再发一次链接呢？

**Comment by zhangjing-GitHub-Code** [comment]
@chute8427 您好！！

**Comment by zhangjing-GitHub-Code** [comment]
@chute8427 您好？？

**Comment by zhangjing-GitHub-Code** [comment]
@chute8427 麻烦补下链接，谢谢！请问这个板子有什么公开资料吗

**Comment by zhangjing-GitHub-Code** [comment]
@chute8427
