### ISSUE TITLE
关于黑豹X2（[Panther X2）的miniPCIe接口，已经拆下来供大家分析了。

### ISSUE THREAD

**Issue by caigooo** [ophub/amlogic-s9xxx-armbian#2154]
**Device Information | 设备信息**
 - SOC: [rk3566]
 - Model [Panther X2]

**Armbian Version | 系统版本**
 - Kernel Version: [ 5.15.100]
 - Release: [jammy/bullseye]

**Describe the bug | 问题描述**
这几天折腾黑豹X2的miniPCIE接口，实在是搞不下去了，把资料汇总一下，看看哪位大侠能有新思路。

> 1、这个miniPCIE 没有USB2.0的引线（36、38脚），无法增加USB！

> 2、miniPCIE转nvme固态，缺了1、7、11、13、33脚，这有点难搞了！

> 3、miniPCIE转msata接口/sata，我是小白，大概看了一下rk3566的手册，pcie和sata好像是复用的，是不是说用的是同一组线路，如果是，那还是缺33脚。有没有一种方法重新定义CPU这个脚，借用其他线路，再改物理改动一下引线。又或者屏蔽这个脚，依然能交换数据？

> 4、理论上缺失的引脚从CPU这边重新飞线过来，应该是可行的，但是难度非常非常大，有引出点还好，没有的话需要重焊CPU，这就是厕所点灯了...

> 5、我只是一个工地搬砖的，没有太多电子知识储备，编程那些更是一窍不通。。尽力了。

![X2缺针脚2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/0860e9ff-8d6c-4e15-9d7a-0a83c9579a9b)

![转NVME缺脚](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/ac5f445b-b58a-419f-a29f-9d16466bb50d)

![转msata缺脚](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/40414ad9-cad3-4ab0-81bd-2ea19d1583e5)

更多接口图片看看这个链接 https://github.com/ophub/amlogic-s9xxx-armbian/issues/2027#issuecomment-1975244272

@ophub @LSP0123 @HelloTheAsia @FusionPlmH @hxp-vip @akwangl ...

**Comment by caigooo** [comment]
今天再认证核对了一下，这个miniPCIE接口确实是残废的，装假狗的。
最重要的四条线路，都不是对应的。

> PCIE20_TXn/SATA2_TXp   23脚
> PCIE20_TXn/SATA2_TXn  25脚
这两组线是往CPU的AE1附近走的，跟pcie的AA37、AA38相差太远了！

> PCIE20_RXn/SATA2_RXp   31脚
> PCIE20_RXn/SATA2_RXn   33脚
31脚往前面空白的芯片走的，这个应该是GPS芯片。33脚空。。。


![没戏了](https://github.com/ophub/amlogic-s9xxx-armbian/assets/160527438/d0d3e8f3-d727-4ec3-b9ff-890e694df6a8)

**Comment by devinzhang91** [comment]
很强，想请问一下板上的i2c是device:0吗?

**Comment by caigooo** [comment]
> 很强，想请问一下板上的i2c是device:0吗?

你是指主板上留空的i2c接口吗？

**Comment by HelloTheAsia** [comment]
i2c1就在板子的角落,这个可以确定是可用的
<img width="561" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/b69f03ca-1675-496b-a782-e9069adb3733">

**Comment by caigooo** [comment]
> i2c1就在板子的角落,这个可以确定是可用的 <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/26612794/312930392-b69f03ca-1675-496b-a782-e9069adb3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MzkzNDEsIm5iZiI6MTcxMDQzOTA0MSwicGF0aCI6Ii8yNjYxMjc5NC8zMTI5MzAzOTItYjY5ZjAzY2EtMTY3NS00OTZiLWE3ODItZTkwNjlhZGIzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDE3NTcyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUzMmIyMDYwNTM3MDY5ODQ5YTE1NTNhYTRjYTg2MDMwNmNhZmQyYmUzYmJiNmI3NzEyODY5NTNkOGEwZTRkOWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.azsYdk8OrN7MTVonExrwubGwxJg1gZzMu9wELnu6hco">

都是高手啊～～

**Comment by jgpgtg** [comment]
补充下PCIE的Pin定义图
![mmexport1711939996715.png](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55088438/972a9d0b-024d-42c8-ac53-dc0f0bb9315d)

![mmexport1711939998788.png](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55088438/7c5304c8-fd1e-43ee-9db8-0bd164fb85ef)

![mmexport1711940001375.png](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55088438/8c757f1f-b389-4d84-8b59-a32448a06403)

![mmexport1711940009419.png](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55088438/abdd81b8-655f-46d7-bff1-2029247e6fa8)

**Comment by jgpgtg** [comment]
> i2c1就在板子的角落,这个可以确定是可用的
> <img width="561" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/b69f03ca-1675-496b-a782-e9069adb3733">

你的固件中，spi启动了吗

**Comment by HelloTheAsia** [comment]
> > i2c1就在板子的角落,这个可以确定是可用的
> > <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/26612794/312930392-b69f03ca-1675-496b-a782-e9069adb3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjMwODcsIm5iZiI6MTcxMTk2Mjc4NywicGF0aCI6Ii8yNjYxMjc5NC8zMTI5MzAzOTItYjY5ZjAzY2EtMTY3NS00OTZiLWE3ODItZTkwNjlhZGIzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTcwYmY1ZjIwZTUzZjkyYzcwZjAzYzU1MzEzNmIyMGY5ZjY1OTIwNzcyYTg2YzMxMzM2MDkzNjVkOTExMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFmCCKu5E7gr1LYg1rayrcPD4Q2BB6idSi1zdMNa9hE">
> 
> 你的固件中，spi启动了吗

你是说这个lora网卡吗,我测试是可用的
<img width="691" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/ee107b97-0c81-4feb-b982-085b10820130">

**Comment by jgpgtg** [comment]
> > > i2c1就在板子的角落,这个可以确定是可用的
> > > <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/26612794/312930392-b69f03ca-1675-496b-a782-e9069adb3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjMwODcsIm5iZiI6MTcxMTk2Mjc4NywicGF0aCI6Ii8yNjYxMjc5NC8zMTI5MzAzOTItYjY5ZjAzY2EtMTY3NS00OTZiLWE3ODItZTkwNjlhZGIzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTcwYmY1ZjIwZTUzZjkyYzcwZjAzYzU1MzEzNmIyMGY5ZjY1OTIwNzcyYTg2YzMxMzM2MDkzNjVkOTExMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFmCCKu5E7gr1LYg1rayrcPD4Q2BB6idSi1zdMNa9hE">
> > 
> > 你的固件中，spi启动了吗
> 
> 你是说这个lora网卡吗,我测试是可用的
> <img width="691" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/ee107b97-0c81-4feb-b982-085b10820130">
> 

是的，能启动的话做点什么有意思的东西呢

**Comment by jgpgtg** [comment]
> > > i2c1就在板子的角落,这个可以确定是可用的
> > > <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/26612794/312930392-b69f03ca-1675-496b-a782-e9069adb3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjMwODcsIm5iZiI6MTcxMTk2Mjc4NywicGF0aCI6Ii8yNjYxMjc5NC8zMTI5MzAzOTItYjY5ZjAzY2EtMTY3NS00OTZiLWE3ODItZTkwNjlhZGIzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTcwYmY1ZjIwZTUzZjkyYzcwZjAzYzU1MzEzNmIyMGY5ZjY1OTIwNzcyYTg2YzMxMzM2MDkzNjVkOTExMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFmCCKu5E7gr1LYg1rayrcPD4Q2BB6idSi1zdMNa9hE">
> > 
> > 你的固件中，spi启动了吗
> 
> 你是说这个lora网卡吗,我测试是可用的
> <img width="691" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/26612794/ee107b97-0c81-4feb-b982-085b10820130">
> 

你刷的是哪个固件，需要换uboot或者其他东西吗，我的找不到spi

**Comment by HelloTheAsia** [comment]
> > > > i2c1就在板子的角落,这个可以确定是可用的
> > > > <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/26612794/312930392-b69f03ca-1675-496b-a782-e9069adb3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjMwODcsIm5iZiI6MTcxMTk2Mjc4NywicGF0aCI6Ii8yNjYxMjc5NC8zMTI5MzAzOTItYjY5ZjAzY2EtMTY3NS00OTZiLWE3ODItZTkwNjlhZGIzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTcwYmY1ZjIwZTUzZjkyYzcwZjAzYzU1MzEzNmIyMGY5ZjY1OTIwNzcyYTg2YzMxMzM2MDkzNjVkOTExMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFmCCKu5E7gr1LYg1rayrcPD4Q2BB6idSi1zdMNa9hE">
> > > 
> > > 
> > > 你的固件中，spi启动了吗
> > 
> > 
> > 你是说这个lora网卡吗,我测试是可用的
> > <img alt="image" width="691" src="https://private-user-images.githubusercontent.com/26612794/318392612-ee107b97-0c81-4feb-b982-085b10820130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjkxMDQsIm5iZiI6MTcxMzM2ODgwNCwicGF0aCI6Ii8yNjYxMjc5NC8zMTgzOTI2MTItZWUxMDdiOTctMGM4MS00ZmViLWI5ODItMDg1YjEwODIwMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1NDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzgxOWM1ZGY0Yjk5NDBkYTg1ODJhNWNjNjVjYWVmZWNiYzI0MWFkYzAzZjRiODBiNTc2YThiNzAyMWUyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRZE4JApDQpdLi2mGdR_ovxtajLxV43s2-vBzFKI4_A">
> 
> 你刷的是哪个固件，需要换uboot或者其他东西吗，我的找不到spi

我用fork了一份,自己编译的.你可以试试spi3.0,我简单的测试了一下 是可以驱动的, POWER_EN_PIN=129,RESET_PIN=120

**Comment by yjdwbj** [comment]
下面信息，是从panther-x2原版系统dump出来的。
```sh
i2c@fe5a0000 {
		#address-cells = < 0x01 >;
		#size-cells = < 0x00 >;
		clock-frequency = < 0x186a0 >;
		clock-names = "i2c\0pclk";
		clocks = < 0x1f 0x148 0x1f 0x147 >;
		compatible = "rockchip,rk3399-i2c";
		interrupts = < 0x00 0x2f 0x04 >;
		phandle = < 0x1a2 >;
		pinctrl-0 = < 0xcc >;
		pinctrl-names = "default";
		reg = < 0x00 0xfe5a0000 0x00 0x1000 >;
		status = "okay";

		gt1x@14 {
			compatible = "goodix,gt1x";
			goodix,irq-gpio = < 0x36 0x0d 0x08 >;
			goodix,rst-gpio = < 0x36 0x0e 0x00 >;
			phandle = < 0x1a3 >;
			pinctrl-0 = < 0xcd >;
			pinctrl-names = "default";
			power-supply = < 0x91 >;
			reg = < 0x14 >;
			status = "disabled";
		};
	};
```
* i2c-detect
```sh
root@Panther-X2:~# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: 60 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
root@Panther-X2:~# i2cdetect -y 2
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: 40 -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
root@Panther-X2:~# i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- UU -- -- -- 
20: UU -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --                         
root@Panther-X2:~# i2cdetect -y 3

```

**Comment by maxmib** [comment]
> > > > > i2c1就在板子的角落,这个可以确定是可用的
> > > > > <img alt="image" width="561" src="https://private-user-images.githubusercontent.com/26612794/312930392-b69f03ca-1675-496b-a782-e9069adb3733.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NjMwODcsIm5iZiI6MTcxMTk2Mjc4NywicGF0aCI6Ii8yNjYxMjc5NC8zMTI5MzAzOTItYjY5ZjAzY2EtMTY3NS00OTZiLWE3ODItZTkwNjlhZGIzNzMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA5MTMwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYTcwYmY1ZjIwZTUzZjkyYzcwZjAzYzU1MzEzNmIyMGY5ZjY1OTIwNzcyYTg2YzMxMzM2MDkzNjVkOTExMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pFmCCKu5E7gr1LYg1rayrcPD4Q2BB6idSi1zdMNa9hE">
> > > > 
> > > > 
> > > > 你的固件中，spi启动了吗
> > > 
> > > 
> > > 你是说这个lora网卡吗,我测试是可用的
> > > <img alt="image" width="691" src="https://private-user-images.githubusercontent.com/26612794/318392612-ee107b97-0c81-4feb-b982-085b10820130.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjkxMDQsIm5iZiI6MTcxMzM2ODgwNCwicGF0aCI6Ii8yNjYxMjc5NC8zMTgzOTI2MTItZWUxMDdiOTctMGM4MS00ZmViLWI5ODItMDg1YjEwODIwMTMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE1NDY0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NzgxOWM1ZGY0Yjk5NDBkYTg1ODJhNWNjNjVjYWVmZWNiYzI0MWFkYzAzZjRiODBiNTc2YThiNzAyMWUyZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iRZE4JApDQpdLi2mGdR_ovxtajLxV43s2-vBzFKI4_A">
> > 
> > 
> > 你刷的是哪个固件，需要换uboot或者其他东西吗，我的找不到spi
> 
> 我fork了一份,自己编译的.你可以试试spi3.0,我简单的测试了一下 是可以驱动的, POWER_EN_PIN=129,RESET_PIN=120

请教一下具体怎么操作，需不需要修改dtb，谢谢

**Comment by imi415** [comment]
模块上SHT20 overlay (SCL: PB4, SDA: PB5):
```
/dts-v1/;
/plugin/;
/ {
	fragment@0 {
		target = <&i2c2>;
		__overlay__ {
			status = "okay";
			pinctrl-0 = <&i2c2m1_xfer>;
		};
	};
};
```

**Comment by liudianwei** [comment]
各位大神 麻烦问下那个温度传感器对应的gpio引脚是多少呢

<img width="762" height="234" alt="Image" src="https://github.com/user-attachments/assets/112b890a-e087-42e3-83ca-27425c37c356" />

**Comment by liudianwei** [comment]
麻烦问下各位大神 SHT2x咋驱动 对应复位的gpio都是多少

**Comment by imi415** [comment]
> 麻烦问下各位大神 SHT2x咋驱动 对应复位的gpio都是多少

https://github.com/ophub/amlogic-s9xxx-armbian/issues/2154#issuecomment-2130728204

**Comment by liudianwei** [comment]
> > 麻烦问下各位大神 SHT2x咋驱动 对应复位的gpio都是多少
> 
> [#2154 (comment)](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2154#issuecomment-2130728204)

i2c2报超时 感觉像是引脚不对 i2c1 i2c0 调用i2cdetact很快返回的

**Comment by liudianwei** [comment]
> > > 麻烦问下各位大神 SHT2x咋驱动 对应复位的gpio都是多少
> > 
> > 
> > [#2154 (comment)](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2154#issuecomment-2130728204)
> 
> i2c2报超时 感觉像是引脚不对 i2c1 i2c0 调用i2cdetact很快返回的
原版系统查到的 i2c2引脚 如下

pin 140 (gpio4-12): fe5b0000.i2c (GPIO UNCLAIMED) function i2c2 group i2c2m1-xfer
pin 141 (gpio4-13): fe5b0000.i2c (GPIO UNCLAIMED) function i2c2 group i2c2m1-xfer
