### ISSUE TITLE
请求增加对mrkaio-m68s的支持

### ISSUE THREAD

**Issue by bnaand** [ophub/amlogic-s9xxx-armbian#2155]
请求增加对mrkaio-m68s的支持
SOC: RK3568
4+32 GB
已有厂家提供的文件：https://pan.baidu.com/s/1gsZB3r5RA-yUsa91dSA13A?pwd=mrpg 提取码: mrpg
mrkaio-m68s-rk3568-idbloader.img
mrkaio-m68s-rk3568-u-boot.itb
rk3568_bl31_v1.43.elf
rk3568_ddr_1560MHz_v1.18.bin
从[immortalwrt](https://github.com/immortalwrt/immortalwrt)中git的文件：
rk3568-mrkaio-m68s-u-boot.dtsi
mrkaio-m68s-rk3568_defconfig
rk3568-mrkaio-m68s.dts
rk3568-mrkaio-m68s.dtsi

**Comment by ophub** [comment]
谢谢分享，根据你提供的资料我添加了支持，你到releases里下载测试下是否正常。

https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by bnaand** [comment]
谢谢编译。写入SD卡后，hdmi接显示器，有以下报错。
![微信图片_20240312224546](https://github.com/ophub/amlogic-s9xxx-armbian/assets/106130584/c7a1c353-b370-421e-a537-e31e9bd33f09)
不知能否解决？

**Comment by ophub** [comment]
镜像文件有4个，你下载别的分支的试一下，错误显示uuid指向的rootfs分区没挂载上

**Comment by bnaand** [comment]
厂家提供的固件包有ubuntu。openwrt。和安卓11。不知道这个u-boot是不是ubuntu上的。晚上我再用其他的试试。

**Comment by bnaand** [comment]
测试了四个包，都是卡在刚才的界面了。请求帮助～～

**Comment by ophub** [comment]
我调整了下，你再试试今晚打包的最新版

**Comment by bnaand** [comment]
刷了03.13的，还是一样的报错，估计是uboot不匹配。能不能麻烦，用immortalwrt的dts新编译一份u-boot，再构建一次。immortalwrt有这个机器的固件，可以正常使用。

**Comment by ophub** [comment]
最新的这个就是使用imm的u-boot源码编译的

**Comment by bnaand** [comment]
换了新SD卡，用03.13的成功启动，谢谢您的帮助。
![IMG_20240314_211721](https://github.com/ophub/amlogic-s9xxx-armbian/assets/106130584/b40ec29d-6d32-4fb4-bd07-796808f055c8)
没联网，只用显示器。希望能把这个机器加入构建版本型号，以后也能用上新版本的。

**Comment by ophub** [comment]
我以为不行呢，下午刚移除了，明天我再加回来。

**Comment by bnaand** [comment]
👌感谢了，晚上下班回来才测试～晚了点，不好意思。
