### ISSUE TITLE
小米盒子4 链接usbhub则无法进入系统

### ISSUE THREAD

**Issue by Zhuwenxue2002** [ophub/amlogic-s9xxx-armbian#2157]
**Device Information | 设备信息MDZ-21-AA

SOC: [e.g. s905l]
Model [e.g. Mibox-4]
**Armbian Version | 系统版本24.5.0

Kernel Version: [e.g. 6.6.21]
Release: [e.g. jammy]
Describe the bug | 问题描述
小米盒子4 U盘启动成功，但是这个盒子没有网线插口和多余的usb口，需要连接usbhub进行配置，但是链接上usbhub之后就无法启动系统了，反之直接将u盘插到盒子上 即可正常启动

镜像名称Armbian_24.5.0_amlogic_s905l_noble_6.6.21_server_2024.03.12.img

使用的是那个小米盒子4issue提交刷机成功的
label Armbian
    kernel /zImage
    initrd /uInitrd
    fdt /dtb/amlogic/meson-gxl-s905l-venz-v10.dtb
    append root=UUID=d81a9344-84f7-426f-b5a8-1b6d12184904 rootflags=compress=zstd:6 rootfstype=btrfs console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 max_loop=128 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

**Comment by Zhuwenxue2002** [comment]
![Uploading IMG_20240313_181511.jpg…]()

**Comment by Zhuwenxue2002** [comment]
![IMG_20240313_181511](https://github.com/ophub/amlogic-s9xxx-armbian/assets/56246634/aabacdb0-ea5c-4ad2-a0cc-241568c226cd)

**Comment by Zhuwenxue2002** [comment]
![IMG_20240313_181631](https://github.com/ophub/amlogic-s9xxx-armbian/assets/56246634/14edd52d-00ce-480d-b8d6-e90ed6ed7f4d)

**Comment by Zhuwenxue2002** [comment]
![IMG_20240313_181928](https://github.com/ophub/amlogic-s9xxx-armbian/assets/56246634/16d3bcc1-68ca-4346-b581-9c1250cce48f)
![IMG_20240313_181923](https://github.com/ophub/amlogic-s9xxx-armbian/assets/56246634/940a5886-763d-4f60-b325-91745e812394)

**Comment by Zhuwenxue2002** [comment]
usbhub是两个绿联的  3.0 2.0 都试过了 都不能正常启动系统  有没有什么好的解决方法呢

**Comment by ginitaimeiyty** [comment]
？我的也是这样，最新版的固件依旧没有解决，为什么要关闭议题？
