### ISSUE TITLE
Wifi interface is not detected for HG680P using kernel 6.6.21

### ISSUE THREAD

**Issue by daruadi** [ophub/amlogic-s9xxx-armbian#2161]
**Device Information | 设备信息**
 - SOC: s905x
 - Model HG680P

**Armbian Version | 系统版本**
 - Kernel Version:  6.6.21
 - Release: bookworm

**Describe the bug | 问题描述**
i used to use `Armbian_20.10_Arm-64_bullseye_current_5.9.0_desktop.img` (i got that image from other sources), the wifi was detected and working well.
but when i want to upgrade and use image `Armbian_24.5.0_amlogic_s905x_bookworm_6.6.21_server_2024.03.12.img` the wifi interface is not showing when i run `iwconfig`.

could you help to resolve the issue?

**Comment by emavgl** [comment]
Same issue here, why was this closed?
