### ISSUE TITLE
6.6.y内核，小宝nas依旧无法使用SATA，pcie还是报错

### ISSUE THREAD

**Issue by Mango1151** [ophub/amlogic-s9xxx-armbian#2162]
root@armbian:~# dmesg | grep pci
[    0.936806] rockchip-pcie f8000000.pcie: host bridge /pcie@f8000000 ranges:
[    0.936840] OF: /pcie@f8000000: Missing device_type
[    0.936865] rockchip-pcie f8000000.pcie:      MEM 0x00fa000000..0x00fbdfffff -> 0x00fa000000
[    0.936888] rockchip-pcie f8000000.pcie:       IO 0x00fbe00000..0x00fbefffff -> 0x00fbe00000
[    0.937468] rockchip-pcie f8000000.pcie: no vpcie12v regulator found
[    0.937490] rockchip-pcie f8000000.pcie: no vpcie3v3 regulator found
[    0.937508] rockchip-pcie f8000000.pcie: supply vpcie1v8 not found, using dummy regulator
[    0.937647] rockchip-pcie f8000000.pcie: supply vpcie0v9 not found, using dummy regulator
[    1.498780] rockchip-pcie f8000000.pcie: PCIe link training gen1 timeout!
[    1.498819] rockchip-pcie: probe of f8000000.pcie failed with error -110

**Comment by yshtz** [comment]
你的小宝nas有能够识别SATA的固件吗？

**Comment by Mango1151** [comment]
> 你的小宝nas有能够识别SATA的固件吗？

有的https://www.alipan.com/t/rDq8rDK8zNjs1Pcz8Gxv

**Comment by yshtz** [comment]
> > 你的小宝nas有能够识别SATA的固件吗？
> 
> 有的https://www.alipan.com/t/rDq8rDK8zNjs1Pcz8Gxv

已经失效了，麻烦重新发一下

**Comment by Mango1151** [comment]
> > > 你的小宝nas有能够识别SATA的固件吗？
> > 
> > 
> > 有的https://www.alipan.com/t/rDq8rDK8zNjs1Pcz8Gxv
> 
> 已经失效了，麻烦重新发一下

「链接：https://pan.xunlei.com/s/VNto7S_5gf9EjdmFjSJSH6UjA1?pwd=3ce9# 提取码：3ce9”复制这段内容后打开手机迅雷App，查看更方便」

**Comment by Mango1151** [comment]
> > > 你的小宝nas有能够识别SATA的固件吗？
> > 
> > 
> > 有的https://www.alipan.com/t/rDq8rDK8zNjs1Pcz8Gxv
> 
> 已经失效了，麻烦重新发一下

「链接：https://pan.xunlei.com/s/VNto7vHTe2b7WrGcBt1bxtsVA1?pwd=8yay# 提取码：8yay”复制这段内容后打开手机迅雷App，查看更方便」

**Comment by ophub** [comment]
你做了什么修改让识别了SATA吗？我看你使用的5.10内核，是这个主线内核可以支持？

**Comment by Mango1151** [comment]
> 你做了什么修改让识别了SATA吗？我看你使用的5.10内核，是这个主线内核可以支持？

5.10内核可以识别的，5.15 6.y就不行了

**Comment by ophub** [comment]
好的，多谢反馈
