### ISSUE TITLE
N1升级最新6.1.81 后，docker无法启用

### ISSUE THREAD

**Issue by molun** [ophub/amlogic-s9xxx-armbian#2163]
斐讯N1，更新到最新版本6.1.81 后，docker无法启用，armbian-software命令下查看docker是已经安装的，但是之前安装的Alist、Qinglong等未显示已安装。docker无法正常启用，提示docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.

![Uploading image.png…]()

**Comment by ophub** [comment]
如果是内核的原因，就换个内核，5个系列换着玩。

**Comment by molun** [comment]
> 如果是内核的原因，就换个内核，5个系列换着玩。

可能是内核原因，也可能是更新时出了什么问题。恢复到6.1.69可以使用了，6.1.78文件夹中没有发现备份文件。
