### ISSUE TITLE
e900v22d (s905l3B) 线刷入安卓9 无法开启adb

### ISSUE THREAD

**Issue by NathanDai** [ophub/amlogic-s9xxx-armbian#2165]
**Device Information | 设备信息**
 - SOC: S905l3B
 - Model: e900v22d
 - 内存: 4G
 - 存储: 16G
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28701315/37b874e5-7e64-4429-8390-6bb5cb03ed92)

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22e_cm211-1_201-1_s905l3b.tar.xz 安卓9
可以短接后线刷入安卓9这个版本无法打开adb也无法用遥控器进入u盘启动

**Comment by ophub** [comment]
adb要先打开调试模式，在关于版本号上7连击打开调试模式，到usb选项里打开允许调试，重启，adb

**Comment by NathanDai** [comment]
在设置 本机信息 版本信息 操作系统版本点击7次没反应

**Comment by ophub** [comment]
bia,bia,bia,bia,bia,bia,bia...迅速的连击

**Comment by NathanDai** [comment]
adb连上了 太开心了

**Comment by NathanDai** [comment]
输入了reboot update盒子重启了
![46e3c1a3f321c009765a2f803de820c](https://github.com/ophub/amlogic-s9xxx-armbian/assets/28701315/310deaaa-f8a5-4c0f-8362-b2a1609b6cd6)
进入这个界面 插入u盘 点从u盘更新系统提示失败

**Comment by ophub** [comment]
这个是更新安卓，你阅读下仓库的文档，如何从安卓盒子启动armbian

断电，插armbian的u盘，插电

**Comment by NathanDai** [comment]
刷入了 但是内存只识别了部分
OS: Armbian (24.5.0) aarch64
 Host: Amlogic Meson GXL (S905L2) X7 5G Tv Box
 Kernel: 6.1.81-ophub
CPU: ARMv8 rev 4 (v8l) (4) @ 2.016GHz
Memory: 169MiB / 2800MiB

**Comment by NathanDai** [comment]
使用了
123   s905l3b    E900V22D,TY1608                     meson-gxl-s905l2-x7-5g.dtb

**Comment by NathanDai** [comment]
Health summary: OK

Performance summary:
Sequential reading speed: 98.89 MB/s
 4K random reading speed:  20397 KB/s
Sequential writing speed:  35.43 MB/s
 4K random writing speed:  32475 KB/s

To interpret the results above correctly or search for better storage
alternatives please refer to http://oss.digirati.com.br/f3/ and also
http://www.jeffgeerling.com/blogs/jeff-geerling/raspberry-pi-microsd-card
and http://thewirecutter.com/reviews/best-microsd-card/

**Comment by ophub** [comment]
内存的问题可以试一下添加u-boot，方法去文档里看，对照model.conf表复制

**Comment by NathanDai** [comment]
但是使用安卓也是3g 包装盒上写了4g

**Comment by ophub** [comment]
我懂你，你是不是想说今天是315，有点怀疑消费者权益有点打折了。

**Comment by NathanDai** [comment]
如何刷两台机器，我现在用一个u盘刷了两个机器，但是Mac地址一样
