### ISSUE TITLE
黑豹x2  armbian换源无法更新

### ISSUE THREAD

**Issue by 2049320070KXYX** [ophub/amlogic-s9xxx-armbian#2167]
你们好，我遇到了一个问题。黑豹 X2 换源  然后更新报错 是怎么回事  怎么弄
![Screenshot_2024-03-15-11-10-32-48_3d419158bad5872c40592a6c9956e692](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161995786/aa5d10b5-57f1-45c9-b262-08a0a5abb2e2)

**Comment by 2049320070KXYX** [comment]
@ophub 大佬请问我这个问题怎么弄

**Comment by ophub** [comment]
根据自己的releases换，别换成别的。
你图上是国外的，如果你不能正常访问，就换国内的。

**Comment by 2049320070KXYX** [comment]
> 根据自己的releases换，别换成别的。 你图上是国外的，如果你不能正常访问，就换国内的。

**Comment by 2049320070KXYX** [comment]
@ophub 我是用的是Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.78_server_2024.02.20.img这个版本  我已经换国内的源了  换了好几个都不行  o大佬  给个源呗

**Comment by ophub** [comment]
```
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main non-free non-free-firmware contrib
deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm main non-free non-free-firmware contrib
deb https://mirrors.tuna.tsinghua.edu.cn/debian-security/ bookworm-security main
deb-src https://mirrors.tuna.tsinghua.edu.cn/debian-security/ bookworm-security main
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main non-free non-free-firmware contrib
deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-updates main non-free non-free-firmware contrib
deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main non-free non-free-firmware contrib
deb-src https://mirrors.tuna.tsinghua.edu.cn/debian/ bookworm-backports main non-free non-free-firmware contrib
```

```
deb https://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib
deb-src https://mirrors.aliyun.com/debian/ bookworm main non-free non-free-firmware contrib
deb https://mirrors.aliyun.com/debian-security/ bookworm-security main
deb-src https://mirrors.aliyun.com/debian-security/ bookworm-security main
deb https://mirrors.aliyun.com/debian/ bookworm-updates main non-free non-free-firmware contrib
deb-src https://mirrors.aliyun.com/debian/ bookworm-updates main non-free non-free-firmware contrib
deb https://mirrors.aliyun.com/debian/ bookworm-backports main non-free non-free-firmware contrib
deb-src https://mirrors.aliyun.com/debian/ bookworm-backports main non-free non-free-firmware contrib
```

**Comment by 2049320070KXYX** [comment]
![Screenshot_2024-03-15-18-41-58-11_3d419158bad5872c40592a6c9956e692](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161995786/eda4db54-7c21-4c71-a53a-7ca0e452e7df)


现在变成这样了  怎么办

**Comment by ophub** [comment]
去电脑上把文件格式写好了

**Comment by 2049320070KXYX** [comment]
啥文件&nbsp;&nbsp;改啥格式&nbsp;&nbsp;在哪


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月15日(周五) 晚上6:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] 黑豹x2  armbian换源无法更新 (Issue #2167)




 
去电脑上把文件格式写好了
 
&mdash;

**Comment by 2049320070KXYX** [comment]
@ophub 改啥文件啊？

**Comment by ophub** [comment]
/etc/apt/sources.list

**Comment by 2049320070KXYX** [comment]
@ophub 还是不行  依然是报错   对了更新后内存越来越大  怎么清理
![Screenshot_2024-03-16-13-47-47-57_3d419158bad5872c40592a6c9956e692](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161995786/a34420e6-3cb8-40d9-92d3-49c2a2936e39)

**Comment by ophub** [comment]
已经都get了，这就是可以了，docke是国外的，你也一样换个国内的源

**Comment by 2049320070KXYX** [comment]
@ophub 换了源 更新了后 内存变大了 怎么清理啊  我本人有强迫症  看着不舒服

**Comment by ophub** [comment]
你要觉得是源的问题，就再换回去。

**Comment by yingqiangyu** [comment]
> @ophub 换了源 更新了后 内存变大了 怎么清理啊 我本人有强迫症 看着不舒服

建议出掉设备，换一个有厂商支持的设备，先去学习下ubuntu的apt的，问题网上都有现成的

**Comment by 2049320070KXYX** [comment]
@ophub 大佬请问一下上传这是啥意思不是直接用 TF 卡里的系统写入吗 ？需要上传固件到根目录再写入吗？我有点没理解明白
![Image_1711097689148](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161995786/d9dedde4-1424-4046-ad22-1b23206140e4)

**Comment by ophub** [comment]
rockchip系列的写法有dd的，也有用rk工具的，但没写入脚本。

amlogic和allwinner有armbian-install脚本。

**Comment by 2049320070KXYX** [comment]
@ophub 那这个上传镜像是啥意思 上传到哪里

**Comment by ophub** [comment]
任意位置

**Comment by 2049320070KXYX** [comment]
@ophub 大佬请问我把系统写入emmc了 然后第一次换源报错 更新失败如何解决  换了好几个源都不行   ；还有就是  更新软件源产生的数据在哪文件夹里面 。
![Screenshot_2024-03-24-11-37-18-36_3d419158bad5872c40592a6c9956e692](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161995786/2c04ac1b-9fbd-4ddb-a595-8f2474cc87ba)

**Comment by ophub** [comment]
你安装的是bookwarm，你换buster的源干嘛呢？要返回2018年的怀旧版？
我上面的贴子里已经给你发了很多你安装版本的国内的源了。

**Comment by yingqiangyu** [comment]
@ophub 建议关掉这个issue， 纯属伸手党，所有答案搜索均能找到不止一个正确答案

**Comment by 2049320070KXYX** [comment]
为什么关闭呢&nbsp;我早就解决了&nbsp;&nbsp;是公钥的问题&nbsp;&nbsp;&nbsp;只不过没给o大回复而已&nbsp;


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月31日(周日) 上午10:04
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] 黑豹x2  armbian换源无法更新 (Issue #2167)




 
@ophub 建议关掉这个issue， 纯属伸手党，所有答案搜索均能找到不止一个正确答案
 
&mdash;

**Comment by 2049320070KXYX** [comment]
忘记了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月31日(周日) 中午1:05
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] 黑豹x2  armbian换源无法更新 (Issue #2167)




  
为什么关闭呢 我早就解决了  是公钥的问题   只不过没给o大回复而已 
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2024年3月31日(周日) 上午10:04 收件人: @.&gt;; 抄送: @.&gt;;"State @.&gt;; 主题: Re: [ophub/amlogic-s9xxx-armbian] 黑豹x2 armbian换源无法更新 (Issue #2167) @ophub 建议关掉这个issue， 纯属伸手党，所有答案搜索均能找到不止一个正确答案 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.***&gt;
  
解决了为什么不关闭issue？
 
&mdash;

**Comment by ophub** [comment]
为了解决更新软件源镜像的问题，我添加了一个命令`armbian-apt`，可以一键换源或恢复默认源，可以使用`armbian-sync`命令一键拉取此命令到当前的armbian系统里，就可以使用了。

**Comment by 2049320070KXYX** [comment]
好的谢谢&nbsp;&nbsp;请教一下一个问题docker安装了访问不了openwrtUI界面&nbsp;镜像已经正常启动了&nbsp;&nbsp;IP地址也修改了&nbsp;&nbsp;访问的时候提示连接超时&nbsp;&nbsp;我在网上搜了下没找着教程


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月1日(周一) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] 黑豹x2  armbian换源无法更新 (Issue #2167)




 
为了解决更新软件源镜像的问题，我添加了一个命令armbian-apt，可以一键换源或恢复默认源，可以使用armbian-sync命令一键拉取此命令到当前的armbian系统里，就可以使用了。
 
&mdash;

**Comment by 2049320070KXYX** [comment]
谢谢大佬我已经解决了


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月1日(周一) 下午2:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;&quot;State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] 黑豹x2  armbian换源无法更新 (Issue #2167)




 
为了解决更新软件源镜像的问题，我添加了一个命令armbian-apt，可以一键换源或恢复默认源，可以使用armbian-sync命令一键拉取此命令到当前的armbian系统里，就可以使用了。
 
&mdash;

**Comment by 2049320070KXYX** [comment]
@ophub 大佬你好  docker openwrt插件在哪找啊 我从网上没找着  下载链接都过期了  op模板能不能加插件安装模板啊？

**Comment by 2049320070KXYX** [comment]
@ophub 我找着了 谢谢大佬
