### ISSUE TITLE
Unt413a能u盘启动但无法写入emmc

### ISSUE THREAD

**Issue by WangYuanhao404** [ophub/amlogic-s9xxx-armbian#2170]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [unt413a]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100]
 - Release: [noble]

**Describe the bug | 问题描述**
在刚买的unt413a上刷入了kernel项目里的安卓包，并且成功启动了刷入u盘里的armbian，可是我尝试了不同的armbian包，在写入emmc时都是同样的报错：![2024-03-16-19-05-39-627.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/117190900/a2f70a4a-4498-4a4a-ac66-c7d1f2f7f61b)

我怀疑是emmc的问题：![2024-03-16-22-14-46-402.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/117190900/c7ca9c99-919a-4d47-938d-27e1e547306f)

请问我改如何解决？

**Comment by ophub** [comment]
看仓库的文档，降频使用

**Comment by WangYuanhao404** [comment]
> 看仓库的文档，降频使用

找到了，谢谢大佬，过会试试

**Comment by Boofeifan** [comment]
**### 我也遇到了这个问题，有人解决了吗**

**Comment by WangYuanhao404** [comment]
> **### 我也遇到了这个问题，有人解决了吗**

https://github.com/ophub/amlogic-s9xxx-armbian/discussions/1911
看看这个讨论，我没能搞明白但估计是同一个问题
