### ISSUE TITLE
小宝nas更新到6.6.y内核无法启动，提示uuid分区不存在

### ISSUE THREAD

**Issue by Mango1151** [ophub/amlogic-s9xxx-armbian#2171]
![FDB6304A-1D98-48D7-99DB-DC63E4B4E27E](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/e8738fab-1f2c-45b1-9369-d84e46b4b18f)
![8014C37A-C0C2-4A6E-9DDD-6AEC38CE796E](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/8299411e-ad03-4adb-a2de-3f5fd4444945)

**Comment by ophub** [comment]
换个TF卡试试
