### ISSUE TITLE
安装好以后SUDO命令无法执行

### ISSUE THREAD

**Issue by jesson1971** [ophub/amlogic-s9xxx-armbian#2172]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [魔百和401A]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.82]
 - Release: [bullseye]

U盘启动，源的更新啥的都很顺利，就是一执行SUDO命令就提示：
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudoers is owned by uid 1023, should be 0
sudo: no valid sudoers sources found, quitting
sudo: error initializing audit plugin sudoers_audit

按照网上的说法修改权限也无济于事。有个人说是先是安卓启动，然后U盘启动被安卓系统改了权限导致的。但是我把ARMBIAN刷入EMMC以后启动还是一摸一样的状况，搞了两天无计可施，救救啊，感谢。

**Comment by ophub** [comment]
U盘重刷系统。现在的系统被安卓系统改了。
拔电源，插U盘，插电源。

**Comment by jesson1971** [comment]
> U盘重刷系统。现在的系统被安卓系统改了。 拔电源，插U盘，插电源。

感谢，回去就试。

**Comment by jesson1971** [comment]
感谢，全部搞定！
