### ISSUE TITLE
如何开启登录欢迎信息界面

### ISSUE THREAD

**Issue by guosgao** [ophub/amlogic-s9xxx-armbian#2173]
N1 盒子刷上Armbian_24.5.0_amlogic_s905d_noble_6.1.82_server_2024.03.16版本，并安装EMMC里面，登录后发现没有欢迎信息界面，找到这个文件/etc/update-motd.d，文件里面对比另外一个盒子X96MaxPlus，内容大小是一样的，登录后会有登录欢迎信息界面，请问开启登录欢迎信息界面？
N1盒子没有欢迎信息界面
![image_248](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131568916/d44c8fc7-bbcf-446f-b983-e879c45430cc)
X96MaxPlus有欢迎信息界面
![image_247](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131568916/46a0496e-dabb-4d49-98b8-8f25bae3d9ad)

**Comment by ophub** [comment]
重新ssh连接试试

**Comment by guosgao** [comment]
重新刷机，N1盒子插键盘设置，解决好。
![image_249](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131568916/6873b112-808b-43e4-bd34-6e851c54822b)
