### ISSUE TITLE
M401A s905lsb安装和问题

### ISSUE THREAD

**Issue by goodnull** [ophub/amlogic-s9xxx-armbian#2174]
**Device Information | 设备信息**
 - SOC: s905l3b
 - Model M401A
2G+8G

先刷入 `android_tv_e900v22e_e900v22d_s905l3b`
再使用
`Armbian_24.5.0_amlogic_s905l3_bullseye_5.15.151_server_2024.03.07`

U盘启动和刷入使用dtb
`125     :M302A,M304A,CM211-1,CM311-1        :s905l3b  :meson-gxl-s905l3b-m302a.dtb            :u-boot-s905x-s912.bin`

使用命令安装在emmc
`armbian-install -m yes `

安装成功后ssh登录能看到 内存和存储大小识别正常

现在遇到的问题
hdmi无输出  ---搜issues 很多人遇到相同的问题

### 另一个网络问题，会导致我内网故障

开机一个小时后 左右，我正连ssh操作，ssh突然断开，路由器后台无法进入，其他设备也断网，整个网络断了
拔掉盒子的网线，路由器后台恢复正常，其他设备网络也恢复正常
再把网线接入盒子，一会儿（1min左右），路由器后台又进不去，其他设备也没网
把盒子按电源键重新开关，概率性网络能恢复，也概率性会导致路由器卡死

这个状况可以判断是盒子导致我连这个路由器的所有设备断网
导致我现在都不敢接这盒子

盒子开始是默认的网络设置，每次获取的ip是同一个，这种情况也会出现上面的情况
后面按照文档改成
12.7.1.1 由 DHCP 动态分配 IP 地址
```
source /etc/network/interfaces.d/*

auto eth0
iface eth0 inet dhcp
```
路由器后台DHCP绑定盒子mac地址为固定ip，同样出现上面的情况

**Comment by ophub** [comment]
你的盒子里有没有安装通过docker/kvm/pve等容器安装openwrt/adguard/xxxdns等接管网络的服务，造成局域网内2个dhcp同时工作

**Comment by goodnull** [comment]
> 魔百和没有hdmi驱动
> 
> 你的盒子里有没有安装通过docker/kvm/pve等容器安装openwrt/adguard/xxxdns等接管网络的服务，造成局域网内2个dhcp同时工作。你刷一个纯净的armbian试试。

我安装了docker，运行了nginx、memos、bitwarden并没有安装dns和网络相关的软件。
当网络出现问题时，在路由器发现了这条日志，不知道是否跟这个有关系
`时间  kernel: nvram: consolidating space!`

-----
我想尝试U盘启动重装系统，修改了boot.scr文件名
`mv /boot/boot.scr /boot/boot.scr.bak`
插入U盘重启，还是进入了EMMC的系统，执行安装 提示系统已经在emmc中运行
试过几次，确认boot.scr改成了boot.scr.bak
