### ISSUE TITLE
把固件刷入TF卡，插入机器卡槽，重启，无法从TF卡启动系统。

### ISSUE THREAD

**Issue by xiebangrong** [ophub/amlogic-s9xxx-armbian#2175]
**Device Information | 设备信息**
 - 黑豹 X2 64G卡

**Armbian Version | 系统版本**
 - 最新发布的Armbian_noble_save_2024.03

**Describe the bug | 问题描述**
把固件刷入TF卡，插入机器卡槽，重启，无法从TF卡启动系统。

**Comment by yi0332us** [comment]
你是不是把鏡像燒到TF卡的時候發生了情況？我是燒了３次才成功

**Comment by xiebangrong** [comment]
没有发生什么异常。都是正常刷入，不报错。插入机器，就是不启动。连灯都不亮。

**Comment by EndBoy520** [comment]
你刷的6.6的内核么？试试6.1的能行？

**Comment by xiebangrong** [comment]
> 你刷的6.6的内核么？试试6.1的能行？
TF刷了下面这个，终于可以了。
Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.81_server_2024.03.12.img.gz
