### ISSUE TITLE
TVI3315A－RK3399－藍芽無法正常使用

### ISSUE THREAD

**Issue by yi0332us** [ophub/amlogic-s9xxx-armbian#2176]
**Device Information | 设备信息**
 - SOC: RK3399
 - Model TVI3315A

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.82-ophub
 - Release: noble

**Describe the bug | 问题描述**

使用Armbian_24.5.0_rockchip_tvi3315a_noble_6.1.82_server_2024.03.16.img.gz這個鏡像

機載藍牙打開了還是沒法找到其他的藍牙設備

我另外去買了一個USB藍芽裝上使用是能找到設備,但未播放完４分鐘的youtube/musice藍芽就會找不到設備／突然畫面凍結無法使用

terminal 以root權限執行bluetoothctl
不停出現

[bluetooth]# hci0 type 7 discovering on
[bluetooth]# hci0 type 7 discovering off

目前應對是先把藍牙關掉防止再突然卡死

請問這是我設定錯了沒做啟用藍牙的相關設定嗎？

**Comment by ophub** [comment]
armbian-config 安装蓝牙

**Comment by yi0332us** [comment]
> armbian-config 安装蓝牙

已經安裝了、但沒插上買的usb藍牙adapter
![Screenshot from 2024-03-18 14-50-43](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163818895/c9b3d597-5b45-4e87-b3d8-eb3f6bfbab36)
時是找不到任何設備、我還以為是機載藍芽故障

**Comment by yi0332us** [comment]
另外我在https://www.bilibili.com/video/BV1hr4y1o7hg中

看到有人說Linux下的dtb 藍牙GPIO和Android下的dtb 藍牙GPIO是不相同

Android 為04 09 1a

Linux 為04 09 1b

不知道有沒有幫助

另外在付上２個別人給我的DTB、希望有幫助

https://www.mediafire.com/file/7wsa5abic8qjl4o/tvi3315a-v11.dtb/file

https://www.mediafire.com/file/o20n2fg7nxot5ee/tvi3315a-v11-android.dtb/file

**Comment by Zane-E** [comment]
自己尝试下：
![Snipaste_2024-03-18_15-35-58](https://github.com/ophub/amlogic-s9xxx-armbian/assets/72865351/1ac0f5e1-56b5-4441-b6bb-fd9a40a56d07)

[rk3399-tvi3315a.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14632500/rk3399-tvi3315a.zip)

**Comment by yi0332us** [comment]
> 自己尝试下： ![Snipaste_2024-03-18_15-35-58](https://private-user-images.githubusercontent.com/72865351/313587269-1ac0f5e1-56b5-4441-b6bb-fd9a40a56d07.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NDgwMjgsIm5iZiI6MTcxMDc0NzcyOCwicGF0aCI6Ii83Mjg2NTM1MS8zMTM1ODcyNjktMWFjMGY1ZTEtNTZiNS00NDQxLWI2YmItZmQ5YTQwYTU2ZDA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA3NDIwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhZDVmZDJmNTYwNTUxYWE5ZjNkZjMwOGZmYTQ5OGFlMjAxZTJhNGExNmJmNzAxNjVmNzRjYWNjYTljZDg0MDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3h7llItIzrkQ7G_6pPB98H5nxrNfaxrIeG2MGJXXgkc)
> 
> [rk3399-tvi3315a.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14632500/rk3399-tvi3315a.zip)

root@armbian:~# dmesg | grep Blue
[   12.258293] Bluetooth: Core ver 2.22
[   12.260785] Bluetooth: Starting self testing
[   12.271141] Bluetooth: ECDH test passed in 7692 usecs
[   12.282200] Bluetooth: SMP test passed in 2290 usecs
[   12.282246] Bluetooth: Finished self testing
[   12.287124] Bluetooth: HCI device and connection manager initialized
[   12.287137] Bluetooth: HCI socket layer initialized
[   12.287141] Bluetooth: L2CAP socket layer initialized
[   12.287160] Bluetooth: SCO socket layer initialized
[   12.479329] Bluetooth: HCI UART driver ver 2.3
[   12.486100] Bluetooth: HCI UART protocol H4 registered
[   12.492700] Bluetooth: HCI UART protocol BCSP registered
[   12.531332] Bluetooth: HCI UART protocol LL registered
[   12.537834] Bluetooth: HCI UART protocol ATH3K registered
[   12.553857] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   12.647279] Bluetooth: HCI UART protocol Intel registered
[   12.690049] Bluetooth: HCI UART protocol Broadcom registered
[   12.697532] Bluetooth: HCI UART protocol QCA registered
[   12.703132] Bluetooth: HCI UART protocol AG6XX registered
[   12.716665] Bluetooth: HCI UART protocol Marvell registered
[   13.061033] Bluetooth: hci0: BCM: chip id 107
[   13.082027] Bluetooth: hci0: BCM: features 0x2f
[   13.120898] Bluetooth: hci0: BCM4345C0
[   13.126702] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
[   13.135359] Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.hcd' Patch
[   16.823619] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   16.828641] Bluetooth: BNEP filters: protocol multicast
[   16.828727] Bluetooth: BNEP socket layer initialized
[   20.405424] Bluetooth: hci0: BCM: features 0x2f
[   20.433557] Bluetooth: hci0: BCM43455 37.4MHz Raspberry Pi 3+-0190
[   20.438489] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0382
[   20.658306] Bluetooth: MGMT ver 1.22
[   27.598691] Bluetooth: RFCOMM TTY layer initialized
[   27.599167] Bluetooth: RFCOMM socket layer initialized
[   27.599645] Bluetooth: RFCOMM ver 1.11
[ 4141.336182] Bluetooth: hci1: CSR: Setting up dongle with HCI ver=9 rev=0001; LMP ver=9 subver=0001; manufacturer=2279
[ 4141.337145] Bluetooth: hci1: CSR: Unbranded CSR clone detected; adding workarounds and force-suspending once...
[ 4141.338109] Bluetooth: hci1: CSR: Couldn't suspend the device for our Barrot 8041a02 receive-issue workaround
[ 4141.339026] Bluetooth: hci1: HCI Delete Stored Link Key command is advertised, but not supported.
[ 4141.339840] Bluetooth: hci1: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[ 4141.340750] Bluetooth: hci1: HCI Set Event Filter command not supported.
[ 4141.900118] Bluetooth: MGMT ver 1.22
[ 4298.797304] Bluetooth: hci1: CSR: Setting up dongle with HCI ver=9 rev=0001; LMP ver=9 subver=0001; manufacturer=2279
[ 4298.798314] Bluetooth: hci1: CSR: Unbranded CSR clone detected; adding workarounds and force-suspending once...
[ 4298.799217] Bluetooth: hci1: CSR: Couldn't suspend the device for our Barrot 8041a02 receive-issue workaround
[ 4298.800150] Bluetooth: hci1: HCI Delete Stored Link Key command is advertised, but not supported.
[ 4298.800935] Bluetooth: hci1: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[ 4298.801830] Bluetooth: hci1: HCI Set Event Filter command not supported.
[ 4299.386093] Bluetooth: MGMT ver 1.22
[ 4365.019190] Bluetooth: hci1: sending frame failed (-19)
[ 4365.032455] Bluetooth: hci1: sending frame failed (-19)
[ 4365.045758] Bluetooth: hci1: sending frame failed (-19)
[ 4365.059207] Bluetooth: hci1: sending frame failed (-19)
[ 4365.072400] Bluetooth: hci1: sending frame failed (-19)
[ 4365.085847] Bluetooth: hci1: sending frame failed (-19)
[ 4365.099121] Bluetooth: hci1: sending frame failed (-19)
[ 4365.112437] Bluetooth: hci1: sending frame failed (-19)
[ 4731.154659] Bluetooth: hci1: CSR: Setting up dongle with HCI ver=9 rev=0001; LMP ver=9 subver=0001; manufacturer=2279
[ 4731.155620] Bluetooth: hci1: CSR: Unbranded CSR clone detected; adding workarounds and force-suspending once...
[ 4731.156566] Bluetooth: hci1: CSR: Couldn't suspend the device for our Barrot 8041a02 receive-issue workaround
[ 4731.157453] Bluetooth: hci1: HCI Delete Stored Link Key command is advertised, but not supported.
[ 4731.158234] Bluetooth: hci1: HCI Read Default Erroneous Data Reporting command is advertised, but not supported.
[ 4731.159124] Bluetooth: hci1: HCI Set Event Filter command not supported.
[ 4731.753295] Bluetooth: MGMT ver 1.22
root@armbian:~#

**Comment by yi0332us** [comment]
> 接天线，armbian-config 能够找到蓝牙设备 ![photo_2024-01-30_18-44-30](https://private-user-images.githubusercontent.com/72865351/313602632-96547174-9620-44d6-b72a-7c5d5dac7dd8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4MDM0ODUsIm5iZiI6MTcxMDgwMzE4NSwicGF0aCI6Ii83Mjg2NTM1MS8zMTM2MDI2MzItOTY1NDcxNzQtOTYyMC00NGQ2LWI3MmEtN2M1ZDVkYWM3ZGQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDIzMDYyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxYTU2OTI3NDI1ODdmZTkxMGE5NDJhZWFhNWJmZWMyMDJlZTU3N2E3ZjRmNTgwMzIzM2Q2MjE0NGY4NDhhYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7fmbLMpETxYqIu093tiOFETkN-eQumctKNADvOdv4wQ)

請問要買甚麼天線、因為手上沒主板的資料、不清楚那些接口能用

另外rk3399 gui用是不是有過熱問題要上風扇

謝謝

**Comment by Zane-E** [comment]
提供的dtb是超频的(大核2.2g 小核1.8g)，温度高建议加风扇。主板有个ipex 1代(有wifi标识)接口用于接天线，天线样式有多种选择，自行搜索。

**Comment by yi0332us** [comment]
發生了點情況沒法進入系統

我打算重裝系統,事源是系統掛著點應用然後過了10小時回頭看死機無反應,有冷氣的情況應該不會過熱死機

拔了電源重開就卡在這裡了

大佬們有沒有建議能給我

![IMG_20240319_170154](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163818895/63911941-6fc3-4679-99fb-99df9dbecdc5)

**Comment by yi0332us** [comment]
root@armbian:~# mmc extcsd read /dev/mmcblk2 | grep Life
eMMC Life Time Estimation A [EXT_CSD_DEVICE_LIFE_TIME_EST_TYP_A]: 0x01
eMMC Life Time Estimation B [EXT_CSD_DEVICE_LIFE_TIME_EST_TYP_B]: 0x01

[log.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/14657307/log.log)

**Comment by Zane-E** [comment]
测试蓝牙 wifi  hdmi声音 都是正常的
![Screenshot from 2024-04-13 00-29-39](https://github.com/ophub/amlogic-s9xxx-armbian/assets/72865351/1373ece7-bc54-46e2-bd8e-fb05f55be234)

**Comment by ophub** [comment]
你用的哪个系列的armbian，哪个版本的内核？

**Comment by Zane-E** [comment]
https://github.com/armbian/build  自己打包的6.6.26内核桌面版，小白表示用不习惯。大佬的固件有空尝试下，应该也是没问题的

**Comment by linux-aarch64** [comment]
> https://github.com/armbian/build 自己打包的6.6.26内核桌面版，小白表示用不会使用Linux。大佬的固件有空尝试下，应该也是没问题的 ![截图 2024-04-13 12-22-27](https://github.com/ophub/amlogic-s9xxx-armbian/assets/72865351/5f0b1adb-f965-4173-9bf6-994b80f718d2)

wa,ap6255 zai ni na ke yi yong?

**Comment by Zane-E** [comment]
> > https://github.com/armbian/build 自己打包的6.6.26内核桌面版，小白表示用不会使用Linux。大佬的固件有空尝试下，应该也是没问题的 ![截图 2024-04-13 12-22-27](https://github.com/ophub/amlogic-s9xxx-armbian/assets/72865351/5f0b1adb-f965-4173-9bf6-994b80f718d2)
> 
> wa,ap6255 zai ni na ke yi yong?
可尝试换下dtb
https://github.com/Zane-E/openwrt_packit/tree/master/files/rk3399/tvi3315a

**Comment by linux-aarch64** [comment]
> > > https://github.com/armbian/build 自己打包的6.6.26内核桌面版，小白表示用不会使用Linux。大佬的固件有空尝试下，应该也是没问题的 ![截图 2024-04-13 12-22-27](https://github.com/ophub/amlogic-s9xxx-armbian/assets/72865351/5f0b1adb-f965-4173-9bf6-994b80f718d2)
> > 
> > 
> > wa,ap6255 zai ni na ke yi yong?
> > 可尝试换下dtb
> > https://github.com/Zane-E/openwrt_packit/tree/master/files/rk3399/tvi3315a

shi le,dan shi ka ji shi ka zhu le :(,zhi hao chong shua,kan lai si hu bu xing a....(mei you zhuang shu ru fa,qing jian liang)
