### ISSUE TITLE
Dont write to emmc vontar x92 

### ISSUE THREAD

**Issue by jonasmorais** [ophub/amlogic-s9xxx-armbian#2178]
Hello, I can run the armbian from the SD card and the usd, but I can't write to emmc, the command "armbian-install" starts but crashes during execution and nothing happens. My box is a vontar x92 3/32 S912.  I've tried several versions, all with the same problem.

![IMG_20240317_125423](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22718663/ee051e59-b668-42c2-816e-1211dc240821)
![IMG_20240317_125434](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22718663/ec1f0e7f-fdf4-4f6e-b99f-dfc3468adcd9)
![IMG_20240317_141901](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22718663/ce780e51-2e5b-4345-8d81-88afd14b3ba3)
Control+C

**Comment by d5stick** [comment]
You could try to flash another version/build of the x92 android and see if it than works. 
What is the output of lsblk?

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/dc9b4392-3d56-4c47-a3eb-b8a3d4a2ea75)
