### ISSUE TITLE
build img can not not on ws1710 board

### ISSUE THREAD

**Issue by darth-j** [ophub/amlogic-s9xxx-armbian#2179]
玩客云pro ws1710自己编译了一个镜像，并且写入emmc成功，但是移除sd卡和优盘后重启uboot还是会去找原来的安卓，应该是uboot没有更新，uboot如何更新，还是需要重新编译一个uboot写入
I have a wky  ws1710 board ,i build a img ,that img can use sd and usb boot,and can wirte emmc,but when remove sd and usb, it can not boot . ttl out display original Android system,i think it because u-boot uenv not update，how to update
![c26f2bfe399f79d8bf67c29736c6be0](https://github.com/ophub/amlogic-s9xxx-armbian/assets/25424615/f4f3cfe2-46e8-4712-ad22-6eda5ef5cb6e)
![a54cd2917486326971bb71a977f26e5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/25424615/b2cf03c9-c18e-4b9f-87df-883a9f27ea93)

**Comment by ophub** [comment]
暂不支持玩客云
