### ISSUE TITLE
n1 桌面版没有鼠标光标

### ISSUE THREAD

**Issue by YoKv** [ophub/amlogic-s9xxx-armbian#218]
1. 使用armbian-config安装desktop
2. apt update && apt upgrade
3. 按照[armbian论坛](https://forum.armbian.com/topic/10526-using-different-desktop-environments-on-armbian/)修改`/usr/share/xsessions/xfce.desktop`
4. 重启能进入桌面，没有鼠标光标，鼠标左键右键功能正常

**Comment by ophub** [comment]
`armbian-update 5.16.18`
我测试了5.10和5.16的可以使用桌面鼠标，5.15的内核指针不移动，可能少选了点什么

**Comment by YoKv** [comment]
> `armbian-update 5.16.18` 我测试了5.10和5.16的可以使用桌面鼠标，5.15的内核指针不移动，可能少选了点什么

我测试了5.4 和5.15的都不行 armbian-update 5.10 会报下载失败

**Comment by YoKv** [comment]
5.15的指针反而是能移动的，我想办法测试下5.10和5.16的

**Comment by ophub** [comment]
目前的4今我刚测过，5.10和5.16的可以

**Comment by ophub** [comment]
armbian-update 5.16.18
或者
armbian-update 5.10.109
换个内核使用

**Comment by YoKv** [comment]
> 到内核库里查看当前可用版本号：https://github.com/ophub/kernel/tree/main/pub/stable
> 
> `armbian-update 5.16.18` 或者 `armbian-update 5.10.109` 换个内核使用

👌

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config

各系列内核的配置在这，你可以diff比较一下，看看5.10少选了什么，加上编一个试试

**Comment by UMU618** [comment]
我之前用过 5.15，确实鼠标的光标不显示，而且装到 MMC 里的话 reboot 有几率卡死，5.4 最近的版本不会卡死。

**Comment by ophub** [comment]
5.15内核的鼠标也可以正常使用了

**Comment by YoKv** [comment]
> 5.15内核的鼠标也可以正常使用了

感谢大佬 👍
