### ISSUE TITLE
Panther x2 PVE 安装虚拟机 启动提示 display output is not active

### ISSUE THREAD

**Issue by FikaCode** [ophub/amlogic-s9xxx-armbian#2180]
**Device Information | 设备信息**
 - SOC: rk3566
 - Model Panther x2

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.81-ophub
 - Release: Armbian-unofficial 24.5.0-trunk bookworm

**Describe the bug | 问题描述**
308 已经成功安装PVE，PVE 使用lxc 没问题，但是安装虚拟机设置完毕以后启动 总是提示  display output is not active 。目前已经尝试 更改 linux 安装版本，安装的所有选项都尝试了一遍，都不行，都不会显示安装界面。是不是这个盒子就不能使用 PVE 安装虚拟机？这个盒子没有hdmi 接口。

**Comment by FikaCode** [comment]
破案了。BIOS 必须选择 UEFI，SeaBIOS 不行。

**Comment by kavmors** [comment]
> EFI base image '/usr/share/pve-edk2-firmware//AAVMF_CODE.ms.fd' not found (500)

UEFI必须要加个EFI磁盘，添加EFI磁盘又报找不到firmware。你是怎么解决的？

**Comment by FikaCode** [comment]
> > EFI base image '/usr/share/pve-edk2-firmware//AAVMF_CODE.ms.fd' not found (500)
> 
> UEFI必须要加个EFI磁盘，添加EFI磁盘又报找不到firmware。你是怎么解决的？

你的这个文件我也没有。
<img width="848" alt="1711291132664" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/42266215/83149ba3-9f08-48b7-b385-701867180be6">
我的这个改为bios 以后，添加UEFI就正常了。你安装的系统是不是不是arm的？arm的主机貌似模拟不了x86_64。我用这个方法装 的 arm64 的 rocky linux 没任何问题。

**Comment by gdtv** [comment]
我遇到同样的问题。
按楼上的方法设置为uefi，然后添加efi，然后用 debian-10.11.0-arm64-netinst.iso 光盘启动，能看到启动画面，但是一开始安装，就又显示“display output is not active”了。
然后我直接将 debian-10-nocloud-arm64.qcow2 镜像添加到虚拟机，用qm disk rescan, 不是用 qm importdisk。启动虚拟机后，也是显示“display output is not active”，但是过一会儿，就能显示画面了，直接就是debian的登录界面了，没有安装过程。
