### ISSUE TITLE
e900v22d (s905l3B)4g+16g刷机后reboot后会失去连接

### ISSUE THREAD

**Issue by NathanDai** [ophub/amlogic-s9xxx-armbian#2181]
**Device Information | 设备信息**
 - SOC: S905l3B
 - Model: e900v22d

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.81-ophub
 - Release: bullseye
 - FDTFILE: 123 s905l3b E900V22D,TY1608 meson-gxl-s905l2-x7-5g.dtb

**Describe the bug | 问题描述**
使用教程刷入系统运行正常，但使用reboot重启机器有可能无法连上网(电源和网络灯亮)

**Comment by hanxuelong321** [comment]
我的根本都刷不进去emmc

**Comment by NathanDai** [comment]
放弃了，手动重启吧

**Comment by shuqian2017** [comment]
你的内存识别正常吗？  我这边4G只能识别出2.75G

**Comment by NathanDai** [comment]
一样 我也是2800MiB

**Comment by shuqian2017** [comment]
试了重命名u-boot.ext ，没用

**Comment by FoxHyj** [comment]
> **Device Information | 设备信息**
> 
> * SOC: S905l3B
> * Model: e900v22d
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version: 6.1.81-ophub
> * Release: bullseye
> * FDTFILE: 123 s905l3b E900V22D,TY1608 meson-gxl-s905l2-x7-5g.dtb
> 
> **Describe the bug | 问题描述** 使用教程刷入系统运行正常，但使用reboot重启机器有可能无法连上网(电源和网络灯亮)

我也是楼主这个e900v22d (s905l3B)4g+16g。我从安卓9无法从U盘启动呢？安装呢外置启动APK，也从adb启动试过，都不行。现在怀疑是ArmBain的启动U盘没有做对，楼主选的是U大的哪个镜像呢？

**Comment by FoxHyj** [comment]
![Uploading 2024-05-05_132808.jpg…]()

**Comment by NathanDai** [comment]
> > **Device Information | 设备信息**
> > 
> > * SOC: S905l3B
> > * Model: e900v22d
> > 
> > **Armbian Version | 系统版本**
> > 
> > * Kernel Version: 6.1.81-ophub
> > * Release: bullseye
> > * FDTFILE: 123 s905l3b E900V22D,TY1608 meson-gxl-s905l2-x7-5g.dtb
> > 
> > **Describe the bug | 问题描述** 使用教程刷入系统运行正常，但使用reboot重启机器有可能无法连上网(电源和网络灯亮)
> 
> 我也是楼主这个e900v22d (s905l3B)4g+16g。我从安卓9无法从U盘启动呢？安装了外置启动APK，也从adb启动试过，都不行。现在怀疑是ArmBain的启动U盘没有做对，楼主选的是U大的哪个镜像呢？ ---------------------------------------------------2024.5.5------------------------------ 今天用amlogic_usb_burning_tool重新刷了android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz的安卓9底包，就可以从U盘启动了，已经成功安装好了Armbian_24.5.0_amlogic_s905l3b_bullseye_6.1.87_server_2024.04.25.img。 系统启动内存2.73G，存储14G，不知道正常不？

正常的，我也是这么大，你手动重启正常吗

**Comment by shuqian2017** [comment]
我的reboot是正常的；

目前存在的问题：
1. 网线的指示灯显示不正确，有限网络连通的情况下，指示灯显示为红色
2. armbian的内存识别不正常，盒子的物理内存是4G，目前armbian里面只能识别出来3G

**Comment by shuqian2017** [comment]
图1为5.15内核下的内存情况
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31362005/bd0701e7-cc62-47ae-8baa-1453befd78fe)

图2为6.6内核下使用u-boot.emmc的内存情况
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31362005/fe0b3c56-fa8c-4b80-8f47-69781cbdf9e1)

图3为5.15内核下使用u-boot.emmc的内存情况
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/31362005/2d00078a-d5b1-4dbb-be26-70b51787ff8d)

综上测试结果为，想要内存利用率最大建议使用图3的组合

**Comment by NathanDai** [comment]
这个内存已经够用了，但我的重启还是有问题，重启一次正常，第二次reboot就会挂

**Comment by shuqian2017** [comment]
> 这个内存已经够用了，但我的重启还是有问题，重启一次正常，第二次reboot就会挂

刚刚尝试了6遍，  每次重启都是正常的

**Comment by wangwen6666** [comment]
如果要能充分利用4G就好了，感觉很遗憾
