### ISSUE TITLE
Armbian - OpenVFD does not start at boot

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#2182]
**Device Information | 设备信息**
 - SOC: s905x3
 - Model [HK1/VontarX3]

**Armbian Version | 系统版本**
 Armbian OS 24.2.0 Bookworm with Linux 6.1.82-ophub

**Describe the bug | 问题描述**
OpenVFD will not start automatically and turn the LED on. 

Is this script run at every boot?
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh

I had to create a service to do so.

```
# Armbian led state save and restore
# Stores the current led state at shutdown and restores
# it during bootstrap

[Unit]
Description=Armbian leds state
After=network.target

[Service]
Type=oneshot
RemainAfterExit=true
ReadWritePaths=/sys/class/leds
ExecStart=armbian-openvfd 15
ExecStop=armbian-openvfd 0

[Install]
WantedBy=default.target
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/587a65cd1083e4881c33999661efe3847b44eb56/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L45-L51

change:
`openvfd_enable="yes"`
