### ISSUE TITLE
请求做下Firefly-AIO-3399J的适配

### ISSUE THREAD

**Issue by HagiwaraMiona** [ophub/amlogic-s9xxx-armbian#2183]
**Device Information | 设备信息**
 - SOC: RK3399
 - Model Firefly-AIO-3399J

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.82
 - Release: Bookworm

**Describe the bug | 问题描述**
本来看着没有AIO-3399J的适配寻思想自己搞一下，但是不太会做，于是把原来系统里的dtb复制出来然后刷上了firefly399的镜像，改了启动的dtb试试，能启动也能进系统，但是一直在提示

[  365.379471] rk3x-i2c ff160000.i2c: timeout, ipd: 0x00, state: 1

自行搜索了下是i2c超时
而且发现extlinux的dtb没改，改了之后发现hdmi无信号，怀疑是dtb有问题，反编译了一下提示了很多警告

我参照下rk3399-firefly的dtb改下试试看吧......

**Comment by HagiwaraMiona** [comment]
补充了截图
![屏幕截图 2024-03-21 190637](https://github.com/ophub/amlogic-s9xxx-armbian/assets/124038780/2a5337db-cec2-458f-89c1-6cf99566981c)

**Comment by HagiwaraMiona** [comment]
2024.3.24更新状况，将dtb对应i2c的对应设备信息删掉之后，不再报错能启动，但是指示灯依旧不亮，大概是还有哪里没改好，先挂着吧，学校每天晚上熄灯没法做持久挂机实验.......

**Comment by ophub** [comment]
你是使用的firefly3399的固件修改dtb测试的？如果是真他的，把你用的系统里
/usr/lib/u-boot-xxx 这个目录下的uboot打个包发一份

**Comment by HagiwaraMiona** [comment]
原来的系统还是firefly-3399的固件，原来的系统没有这个目录

**Comment by HagiwaraMiona** [comment]
[u-boot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14735594/u-boot.zip)
firefly-3399的armbian固件里的uboot



[firefly-Image.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/14735596/firefly-Image.zip)
firefly官方的Ubuntu的uboot

**Comment by HagiwaraMiona** [comment]
> 请问如何解决的

没解决，放弃了，转去玩树莓派了
