### ISSUE TITLE
M401A由2+16扩容到4+128后运行内存无法识别到4G

### ISSUE THREAD

**Issue by LTLD123** [ophub/amlogic-s9xxx-armbian#2184]
**Device Information | 设备信息**
 - SOC: [S905l3a]
 - Model [中国移动魔百和M401A]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.152]
 - Release: [24.5.0 Bullseye]

**Describe the bug | 问题描述**
        M401A由2+16扩容到4+128后，使用meson-g12a-s905l3a-m401a.dtb可以正常启动和写入emmc，也可以识别到128G闪存。但是不论是在安卓下还是在armbian下RAM都只能识别到2G。
        经查询得知可能需要修改dtb文件才能正常识别，但是本人纯小白，不知道应该修改dtb中的那些内容，请各位大佬指教。
![屏幕截图 2024-03-21 203410](https://github.com/ophub/amlogic-s9xxx-armbian/assets/118700228/150204f7-e576-4bdb-8030-eab5aaebb3e2)

**Comment by ophub** [comment]
添加u-boot试试，对照model.conf添加

**Comment by yyehdjdbejxbskd** [comment]
我把M401A的 闪存换到64G。线刷死活卡在1%，麻烦问下你刷的什么包？

**Comment by yingwanchao** [comment]
> 添加u-boot试试，对照model.conf添加

能详细说一下吗，是需要自己重新编译u-boot吗？我修改了dtb文件里的
memory@0 {
		device_type = "memory";
		reg = <0x00 0x00 0x00 0x80000000>;
