### ISSUE TITLE
黑豹X2 最新镜像6.6.2.2内核，无法使用

### ISSUE THREAD

**Issue by EndBoy520** [ophub/amlogic-s9xxx-armbian#2187]
**Device Information | 设备信息**
Panther-X2

**Describe the bug | 问题描述**
之前使用RKDevTool2.84工具刷入Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.81（大概20240307的镜像），那时还没有6.6的内核。今天尝试使用armbian-update成功升级了6.1.82内核，正常启动。便又尝试升级6.6.2.2内核，结果升级过程成功，自动重启后再也没起来。便开始了重新刷机。

1，首先我尝试了balenaEtcher工具写入SD卡，想导出一些数据。第一个尝试的是Armbian_24.5.0_rockchip_panther-x2_bookworm_6.6.22_server_2024.03.16.img，提示写入成功，但是没有成功启动，没有任何网络设备接入情况。
2，尝试RKDevTool2.84工具刷入Armbian_24.5.0_rockchip_panther-x2_bookworm_6.6.22_server_2024.03.16.img包，依然没有成功启动，没任何新设备接入。
3，于是尝试刷入Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.82_server_2024.03.16.img，两种工具都成功启动。
（所有情况灯都正常亮，没啥差别）

**Comment by ophub** [comment]
好的，谢谢反馈。
内核更新后无法启动，不用重刷系统，使用tf卡刷一个新的系统，然后`armbian-update -s`可以救援emmc里面的系统，恢复正常使用。

**Comment by xiebangrong** [comment]
Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.82_server_2024.03.16.img这些老版本哪里下载？

**Comment by EndBoy520** [comment]
> Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.82_server_2024.03.16.img这些老版本哪里下载？

额，这不是最新版本么？有两个内核版本啊

**Comment by 0123guoxiao** [comment]
> 好的，谢谢反馈。 内核更新后无法启动，不用重刷系统，使用tf卡刷一个新的系统，然后`armbian-update -s`可以救援emmc里面的系统，恢复正常使用。

我tf卡启动后使用armbian-update -s提示[ ERROR ] (1/3) The [ /ddbr/rescue/bootfs ] folder does not exist, stop rescuing.

**Comment by yingqiangyu** [comment]
> Armbian_24.5.0_rockchip_panther-x2_bookworm_6.1.82_server_2024.03.16.img这些老版本哪里下载？

release里有下载链接

**Comment by rdgjiose** [comment]
今天看到这个问题反馈在Mar 23， 当时我也是直接RK工具直接刷入EMMC的6.6.X版本就无法发启动，刷入6.1.X的版本就没问题，不知现在怎么样了？

**Comment by ZZ250-zZ** [comment]
> 好的，谢谢反馈。 内核更新后无法启动，不用重刷系统，使用tf卡刷一个新的系统，然后`armbian-update -s`可以救援emmc里面的系统，恢复正常使用。

我也遇到了这样的问题：
E900V22C nodle-6.1-93 升级**F大**的 kernel-filppy 内核到 6.6.36 启动失败。
failed to mount /dev/mmcblk2p2 as root file system

![10e0b1b1694497e4902e283cfbd1fbf](https://github.com/ophub/amlogic-s9xxx-armbian/assets/26135265/1aaceb79-7d3c-456f-82a5-b26750cb1c7a)


按照这个方式卡刷之后，报下列错：
root@armbian:~# armbian-update -s
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start rescuing kernel...
[ INFO ] The device name of the target disk: [ mmcblk2 ]
[ INFO ] The current Armbian is running on [ /dev/sda ], and the target disk for restoration is [ /dev/mmcblk2 ].
[ INFO ] (1/3) [ boot ] kernel files rescue succeeded.
[ ERROR ] (1/3) The [ /ddbr/rescue/bootfs ] folder does not exist, stop rescuing.

请问这种要如何排查？另外另外，我需要单开一个 issues 吗？
