### ISSUE TITLE
CM201-1 YS emmc启动正常，有线网络正常

### ISSUE THREAD

**Issue by haochn** [ophub/amlogic-s9xxx-armbian#2188]
CM201-1 YS 版本
 - SOC: [S905l2]

**Armbian Version | 系统版本**
Armbian_24.5.0_amlogic_s905l2_jammy_5.15.152_server_2024.03.16.img
`meson-gxl-s905l2-x7-5g.dtb`
`u-boot-s905x-s912.bin`
且需要`extlinux.conf`

原厂安卓分区信息：
https://7ji.github.io/ampart-web-reporter/?dsnapshot=logo::33554432:1%20recovery::33554432:1%20rsv::8388608:1%20tee::8388608:1%20crypt::33554432:1%20misc::33554432:1%20instaboot::536870912:1%20boot::33554432:1%20system::1073741824:1%20cache::536870912:2%20params::67108864:2%20ctc::314572800:2%20bootfiles::536870912:2%20data::-1:4&esnapshot=bootloader:0:4194304:0%20reserved:37748736:67108864:0%20cache:113246208:1073741824:2%20env:1195376640:8388608:0%20logo:1212153856:33554432:1%20recovery:1254096896:33554432:1%20rsv:1296039936:8388608:1%20tee:1312817152:8388608:1%20crypt:1329594368:33554432:1%20misc:1371537408:33554432:1%20instaboot:1413480448:536870912:1%20boot:1958739968:33554432:1%20system:2000683008:1073741824:1%20params:3082813440:67108864:2%20bootfiles:3158310912:536870912:2%20ysteninfo:3703570432:10485760:2%20ctc:3722444800:314572800:2%20data:4045406208:3772776448:4

**Comment by ophub** [comment]
感谢分享，我把这个设备加到支持的列表里。

你有root的安卓系统吗，分享一个下载地址。这个盒子的正面、反面的照片发一个。如果有主板图片，知道短接救砖点的位置的话标注一下。

**Comment by haochn** [comment]
> 感谢分享，我把这个设备加到支持的列表里。
> 
> 你有root的安卓系统吗，分享一个下载地址。这个盒子的正面、反面的照片发一个。如果有主板图片，知道短接救砖点的位置的话标注一下。

因为是从原厂系统直接U盘启动的，所以没有安卓系统可以分享。按住图上的按键就可以从U盘启动
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/36954660/1e8530db-5fb5-4add-8e39-250b045a6650)

**Comment by wgbingo** [comment]
我也是这个型号，但是soc是S905l3b，你的无线是RLT8822CS吗？无线能不能启动。

**Comment by XeeJove** [comment]
### CM201-1-CW / S905L2 test report

I would like to share my test result for **CM201-1-CW**.

#### Device / image

* Device: **CM201-1-CW**
* SoC: **Amlogic S905L2**
* Image: `Armbian_26.08.0_amlogic_s905l2_resolute_6.12.93_server_2026.06.16.img.gz`
* Kernel: `Linux 6.12.93-ophub`
* System: `Ubuntu stable (resolute)`

#### Boot / eMMC installation

USB boot works correctly.

Although the device is CM201-1-CW, the DTB that worked for my box was:

```text
meson-gxl-s905l2-ipbs9505.dtb
```

The running device-tree information is:

```text
model: Wojia TV IPBS9505
compatible:
  amlogic,ipbs9505
  amlogic,s905l2
  amlogic,meson-gxl
```

For eMMC installation, I selected:

```text
121   s905l2   Wojia-TV-IPBS9505   meson-gxl-s905l2-ipbs9505.dtb
```

Filesystem: `ext4`

Installation completed successfully, and the box can boot from eMMC after removing the USB drive.

#### eMMC information

The eMMC was detected as:

```text
/dev/mmcblk2       7.3G
/dev/mmcblk2boot0  4M
/dev/mmcblk2boot1  4M
```

eMMC model:

```text
DG4008
```

A simple read test completed without I/O errors:

```text
dd if=/dev/mmcblk2 of=/dev/null bs=4M count=256 status=progress

1073741824 bytes copied, 174.052 s, 6.2 MB/s
```

There are some speed-mode fallback messages during boot:

```text
mmc2: mmc_select_hs200 failed, error -74
mmc2: switch to bus width 8 failed
mmc2: switch to bus width 4 failed
mmc2: new high speed MMC card at address 0001
```

But I did not see `timeout`, `I/O error`, or `Buffer I/O error` after the read test.

#### Network status

Wired Ethernet works correctly.

After booting from eMMC, the box obtained a LAN IP address successfully:

```text
IPv4: 192.168.2.122
```

`nmcli device` output:

```text
DEVICE   TYPE      STATE                   CONNECTION
eth0     ethernet  connected               Wired connection 1
lo       loopback  connected (externally)  lo
ip6tnl0  iptunnel  unmanaged               --
sit0     iptunnel  unmanaged               --
```

However, Wi-Fi is not detected. There is no `wlan0` or wireless device shown in `nmcli device`.

So for my CM201-1-CW box:

* USB boot: works
* eMMC installation: works
* Wired Ethernet: works
* Wi-Fi: not detected
* Working DTB: `meson-gxl-s905l2-ipbs9505.dtb`
* Recommended install ID for this specific box/batch: `121`

**Comment by XeeJove** [comment]
CM201-1-CW / S905L2: Fixed wifi and Bluetooth via GPT
