### ISSUE TITLE
MGV2000 emmc启动正常，有线网络正常，WiFi不可用

### ISSUE THREAD

**Issue by haochn** [ophub/amlogic-s9xxx-armbian#2189]
**Device Information | 设备信息**
MGV2000 jz版
 - SOC: [s905l2]
 - WiFi: [mt7668rsn]

**Armbian Version | 系统版本**
`Armbian_24.5.0_amlogic_s905l2_jammy_5.15.152_server_2024.03.16.img`
`meson-gxl-s905l2-x7-5g.dtb`
`u-boot-s905x-s912.bin`
且需要`extlinux.conf`

**Describe the bug | 问题描述**
WiFi不可用，其余正常

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/36954660/64efefb1-c962-4884-adcd-95abd10259c6)

**第三方安卓分区信息：**
https://7ji.github.io/ampart-web-reporter/?dsnapshot=logo::33554432:1%20recovery::33554432:1%20rsv::8388608:1%20tee::8388608:1%20crypt::33554432:1%20misc::33554432:1%20instaboot::536870912:1%20boot::33554432:1%20system::1073741824:1%20cache::536870912:2%20params::67108864:2%20bootfiles::536870912:2%20flashdata::67108864:2%20data::-1:4&esnapshot=bootloader:0:4194304:0%20reserved:37748736:67108864:0%20cache:113246208:536870912:2%20env:658505728:8388608:0%20logo:675282944:33554432:1%20recovery:717225984:33554432:1%20rsv:759169024:8388608:1%20tee:775946240:8388608:1%20crypt:792723456:33554432:1%20misc:834666496:33554432:1%20instaboot:876609536:536870912:1%20boot:1421869056:33554432:1%20system:1463812096:1073741824:1%20params:2545942528:67108864:2%20bootfiles:2621440000:536870912:2%20flashdata:3166699520:67108864:2%20data:3242196992:4577886208:4

**Comment by ophub** [comment]
你刷过安卓系统吗？分享一个安卓系统下载地址。

**Comment by haochn** [comment]
> 你刷过安卓系统吗？分享一个安卓系统下载地址。

很久很久以前刷的卡刷包，实在找不到了。U盘插上，自动从U盘启动了。
![ab6acf6729f9e7060f48734291be9b1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/36954660/d531c25c-35fe-4669-9a55-dcfceb68ea06)

![ca9e50f4f017d5d901ddbb5bf7bbd37](https://github.com/ophub/amlogic-s9xxx-armbian/assets/36954660/afec1577-da90-4af3-b40c-28ef223d9210)

**Comment by hanguofu** [comment]
有意思：） 这个有 HDMI 输出吗 ?

**Comment by haochn** [comment]
> 有意思：） 这个有 HDMI 输出吗 ?

有的

**Comment by LondyGhost** [comment]
> 有意思：） 这个有 HDMI 输出吗 ?

s905l2基本都可以HDMI输出
