### ISSUE TITLE
How to check the system log to find out the reason armbian stop working

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#219]
I have an X96 max +  (4+32, wifi 8822) using kernel 5.15.29. It seems to work fine after 2-4 days then stop working without any reason. There is no power outtage or heavy running service. The CPU temperature is around 55-60 degrees. 

This one has been running about 2 weeks and 3 times stop working. Each time the box stopped working, there is needed to unplug the adapter and plug again to make it work.

So I just confused how to check the root cause of this issue to find out exactly reason why the box stopped working suddenly.

Thank you.

**Comment by ophub** [comment]
You can set it up to save the log for a month and point to a directory with enough space. There are a variety of methods, you can search the Internet for the specific method, and compare and compare.
