### ISSUE TITLE
Update sourcelist from old build to update the firmware ?

### ISSUE THREAD

**Issue by 666diabolus** [ophub/amlogic-s9xxx-armbian#2190]
Hi, I'm still on **_Armbian_20.10_L1-Pro_buster_5.10.26-flippy-56+.img.xz_** and at the time, I put a hold in the firmware update because of the fan issues. Now everything is ok and I try to update the firmware but it said that 

_**The repository 'http://mirrors.tuna.tsinghua.edu.cn/armbian buster Release' no longer has a Release file.**_

Where can I get the repo/sourcelist so that I can update to the latest firmware ? 

I'm on the Chainedbox L1 Pro

I'm still new to linux so please dont mind if I ask something so stupid :D

**Comment by ophub** [comment]
You can change the source and upgrade to the new version. The procedure is the same as upgrading Ubuntu, just look up some information online, it's quite easy.

**Comment by 666diabolus** [comment]
> You can change the source and upgrade to the new version. The procedure is the same as upgrading Ubuntu, just look up some information online, it's quite easy.

so the repo are the same with Ubuntu? I do find a solution but it said for the Ubuntu, that's why I try to ask for the repo :D

**Comment by ophub** [comment]
yes
