### ISSUE TITLE
安装PVE，重启后一段时间断网

### ISSUE THREAD

**Issue by kavmors** [ophub/amlogic-s9xxx-armbian#2191]
**Device Information | 设备信息**
 - SOC: rk3566
 - Model Panther x2

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.82-ophub
 - Release: Armbian OS 24.5.0 Bookworm

**Describe the bug | 问题描述**
先后安装了Docker、PVE、hostapd + dnsmasq。重启后1分钟左右必现断网
连接热点后登录ssh看，发现是vmbr0和eth0都获取了同一个IP，导致IP冲突断网了。执行`ifup vmbr0 eth0`后恢复正常

network/interfaces已经指定eth0 manual了，为什么启动后eth0还会取到IP？
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/6360460/5b47d687-3672-4c02-873b-5ef34c5bb165)

**Comment by kavmors** [comment]
> https://wiki.debian.org/zh_CN/NetworkConfiguration#Bringing_up_an_interface_without_an_IP_address
> 
> ```
> Bringing up an interface without an IP address
> To create a network interface without an IP address at all use the manual method and use pre-up and post-down commands to bring the interface up and down.
> 
> 
>    iface eth0 inet manual
>       pre-up ifconfig $IFACE up
>       post-down ifconfig $IFACE down
> ```

仍然不行。。开机1分钟内eth0就会拿到IP

**Comment by Zane-E** [comment]
尝试禁用NetworkManager
systemctl stop NetworkManager
systemctl disable NetworkManager

**Comment by kavmors** [comment]
> 尝试禁用NetworkManager systemctl stop NetworkManager systemctl disable NetworkManager

确实，NetworkManager禁用后没问题了。估计是配置Hostapd把NetworkManger启用了
