### ISSUE TITLE
高安b860av2.1可以启动armbian了，但是无法写入env，每次启动都需要TTL线辅助

### ISSUE THREAD

**Issue by oceanzhang860411** [ophub/amlogic-s9xxx-armbian#2192]
**Device Information | 设备信息**
 - SOC: S905l
 - Model B860AV2.1（高安）

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.151
 - Release: bullseye

**Describe the bug | 问题描述**
高安版本可以启动armbian了，但是无法写入env，每次启动都需要TTL线辅助
尝试过用非高安机的env备份出来覆盖高安的盒子，但无效，直接进入安卓系统

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
请问有没有什么办法可以脱离开机需要用TTL线辅助？谢谢

**Comment by twallpasser** [comment]
我也是这个盒子，怎么刷机求教程，感谢！
