### ISSUE TITLE
N1 安装系统到emmc后无法从emcc盘启动

### ISSUE THREAD

**Issue by LIUBANGJIAN** [ophub/amlogic-s9xxx-armbian#2194]
O大，我按照教程安装到emmc里，提示是成功的。关机把掉u盘后，n1只能启动到安卓机器人画面，无法启动emcc里面的armbian，请问是什么原因呢？

**Comment by LIUBANGJIAN** [comment]
刷的是Armbian_24.5.0_amlogic_s905d_noble_6.1.82_server_2024.03.16.img固件

**Comment by LIUBANGJIAN** [comment]
大佬麻烦指导一下。

**Comment by ophub** [comment]
你换个固件再试一下，比如jammy

**Comment by LIUBANGJIAN** [comment]
可是有的驱动只支持6.1.82内核。

**Comment by ophub** [comment]
n1都支持

**Comment by LIUBANGJIAN** [comment]
> n1都支持

先刷其他固件，再手动切回6.1.82内核？

**Comment by ophub** [comment]
4个系列的固件jammy/bullseye等

**Comment by LIUBANGJIAN** [comment]
好的 ，我试试。

**Comment by LIUBANGJIAN** [comment]
O大，我更换国内源，ubuntu和debian源armbian可以通用吗？
