### ISSUE TITLE
O大求教

### ISSUE THREAD

**Issue by kesry** [ophub/amlogic-s9xxx-armbian#2195]
o大，你好，我有块带NVME的板子，cpu是rk3399的，刷的ophub下面的Armbian_24.5.0_rockchip_sw799_jammy_5.15.152_server_2024.03.16.img.gz
这个包，这个内核看起来是5.15.152，为什么我没有在unifreq/linux-5.15.y 中找到sw799的相关dts？这个包刷完，typec和nvme不可用。
然后，我在unifreq/linux-6.6.y中找到了rk3399-sw799-bozz.dts，这个里面有typec的节点但没有nvme的节点信息，我不确定Armbian_24.5.0_rockchip_sw799_jammy_5.15.152_server_2024.03.16.img.gz这个包是否用的是rk3399-sw799-bozz.dts。
这块板子原系统用的debian9.9，内核4.4.179，貌似内核缺失netfilter相关的模块，导致iptables -Lvn无法正常启用，尝试换到过iptable-legacy，提示没有filter，nat等表。
原dtb反编译的dts中，是开启了type和nvme的，但是我估计内核没有开启这些模块，导致nvme不可用。我尝试过自己编译4.4.179的kernel，然后直接使用原dtb，但是不开机。所以我想想根据sw799这个板子的dts，来加上nvme的节点，尝试适配下开启nvme.

**Comment by ophub** [comment]
你可以安装6.1.y内核，修改测试。
目前的dts主要都提交到6.1.y和6.6.y了。

**Comment by kesry** [comment]
那我估计没戏了，如果说5.15用的dts和6.x的那边的是同一份，那么typec应该是开启的，我看反编译出来的dts和sw799的dts，寄存器地址和大小都是相同的，应该用的都是是rk3399.dtsi中的默认配置

**Comment by ophub** [comment]
5.15.y使用的dts和6.1.y是一个

**Comment by kesry** [comment]
是的，他们是同一份，而且，从rk3399.dts中来的两个typec的节点定义status都是okay，看来我的另外找方法了
