### ISSUE TITLE
OEC还不能支持吗？

### ISSUE THREAD

**Issue by wang25669** [ophub/amlogic-s9xxx-armbian#2199]
**Device Information | 设备信息**
 - SOC: [RK3566]
 - Model [oec]

应该批量下机了，RK3566的SOC，很有潜力啊，可惜没有能用的

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
不支持
