### ISSUE TITLE
荐片盒子刷入armbian系统后安装不了casaOS和armbian-software

### ISSUE THREAD

**Issue by colinwong92** [ophub/amlogic-s9xxx-armbian#2201]
提示缺少合并的/use目录，使用命令apt install usemerge安装发现默认源中没有该包。

**Comment by colinwong92** [comment]
> 刷ubuntu jammy

成功了！感谢！想问一下两个版本的区别怎么了解？

**Comment by hahayong888** [comment]
大神，请教一下，我的电视盒子是创维e900v22e，芯片是s905l3，刷了s905l3b的那个版本，没有hdmi输出，Wi-Fi也不能用，有啥办法吗？

**Comment by hahayong888** [comment]
> noble是ubuntu 24.04，是ubuntu的下一个lts版本，要等到四月才会正式发布，当前还是测试阶段
> jammy是ubuntu 22.04，当前的lts版本，22年4月发布的

大神，请教一下，我的电视盒子是创维e900v22e，芯片是s905l3，刷了s905l3b的那个版本，没有hdmi输出，Wi-Fi也不能用，有啥办法吗？

**Comment by yingqiangyu** [comment]
> noble是ubuntu 24.04，是ubuntu的下一个lts版本，要等到四月才会正式发布，当前还是测试阶段 jammy是ubuntu 22.04，当前的lts版本，22年4月发布的

noble，安装casaos现阶段可以的，panther x2正在用，lts发布了，应该陆陆续续缺的包，都会更新支持到noble了，现阶段lib ncurses5的库倒是没有

**Comment by yingqiangyu** [comment]
> > > noble是ubuntu 24.04，是ubuntu的下一个lts版本，要等到四月才会正式发布，当前还是测试阶段
> > > jammy是ubuntu 22.04，当前的lts版本，22年4月发布的
> > 
> > 
> > 大神，请教一下，我的电视盒子是创维e900v22e，芯片是s905l3，刷了s905l3b的那个版本，没有hdmi输出，Wi-Fi也不能用，有啥办法吗？
> 
> 不知道，你搜下issue吧
> 
> > > noble是ubuntu 24.04，是ubuntu的下一个lts版本，要等到四月才会正式发布，当前还是测试阶段 jammy是ubuntu 22.04，当前的lts版本，22年4月发布的
> > 
> > 
> > noble，安装casaos现阶段可以的，panther x2正在用，lts发布了，应该陆陆续续缺的包，都会更新支持到noble了，现阶段lib ncurses5的库倒是没有
> 
> 24.04正式发布之前我都不打算用，之前就有个哥们用noble不会装docker的（因为docker还没出noble的，当时得用jammy源），所以非正式发布前尝鲜归尝鲜，日用真是告辞

docker可以用的，一条命令就安装好了，用国内的docker ce源，官方的源速度太慢了，docker只看依赖的组件有没有，有就可以安装
