### ISSUE TITLE
CM311-3和CM311-5可以刷吗？有包吗？

### ISSUE THREAD

**Issue by JustinTangChina** [ophub/amlogic-s9xxx-armbian#2202]
**Device Information | 设备信息**
 - SOC: [e.g. 晶晨9385]
 - Model [e.g. CM311-3]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

大佬们，晶晨9385的包有了吗？CM311-3 的盒子

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by yeaze** [comment]
cm311是晨星的芯片，并不是晶晨的，我也有一台，目前应该不行

**Comment by ophub** [comment]
没有固件
