### ISSUE TITLE
[HK1 BOX]  USB2.0 可以识别 TF 卡， USB3.0 识别不到

### ISSUE THREAD

**Issue by VincentYangFan** [ophub/amlogic-s9xxx-armbian#2203]
**Device Information | 设备信息**
 - SOC: S905X3
 - Model: HK1 BOX

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.82
 - Release: jammy

**Describe the bug | 问题描述**
usb3.0 的读卡器接入 NTFS TF卡，在电脑上的 USB3.0 口，读卡器指示灯亮，可以识别到设备，读取正常
usb3.0 的读卡器接入 NTFS TF卡，在HK1 BOX的 USB2.0 口，读卡器指示灯亮，可以识别到设备，读取正常
usb3.0 的读卡器接入 NTFS TF卡，在HK1 BOX的 USB3.0 口，读卡器指示灯不亮，识别不到设备
usb2.0 的读卡器接入 NTFS TF卡，在HK1 BOX的 USB3.0 口，读卡器指示灯亮，可以识别到设备，读取正常

HK1 BOX 的 USB3.0 口是有物理限制还是软件限制，怎么识别不到 USB3.0 的存储设备

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by VincentYangFan** [comment]
anyone can help？

**Comment by scxs175** [comment]
贝壳云也是 四个usb3.0的接口全部只能识别成2.0模式  无法使用3.0

**Comment by VincentYangFan** [comment]
> 贝壳云也是 四个usb3.0的接口全部只能识别成2.0模式 无法使用3.0

是硬件物理连接的问题，还是系统软件限制，我看内核 usb3.0 驱动有加载
我插入 usb3.0 的读卡器，连 usb2.0 模式都识别不出来，指示灯也不亮，感觉设备没有枚举到

**Comment by VincentYangFan** [comment]
@ophub 大佬能帮忙 support 下吗，如果是硬件的问题，我就不折腾了，只用 usb2.0 的口

**Comment by scxs175** [comment]
> > 贝壳云也是 四个usb3.0的接口全部只能识别成2.0模式 无法使用3.0
> 
> 是硬件物理连接的问题，还是系统软件限制，我看内核 usb3.0 驱动有加载 我插入 usb3.0 的读卡器，连 usb2.0 模式都识别不出来，指示灯也不亮，感觉设备没有枚举到

应该是系统问题 贝壳云电路板上自带usb3.0 hub的芯片的  拓展出4个usb3.0接口  我看了 这个hub芯片也工作在2.0模式

**Comment by VincentYangFan** [comment]
> > > 贝壳云也是 四个usb3.0的接口全部只能识别成2.0模式 无法使用3.0
> > 
> > 
> > 是硬件物理连接的问题，还是系统软件限制，我看内核 usb3.0 驱动有加载 我插入 usb3.0 的读卡器，连 usb2.0 模式都识别不出来，指示灯也不亮，感觉设备没有枚举到
> 
> 我有刷其他4.x内核和5.x内核的openwrt和armbian系统 usb3.0都能正常工作 但是刷6.x内核系统的usb3.0都无法正常工作

专业，对了兄弟，你还有 armbian 5.x 内核的 hk1box jammy 镜像包吗，我看 release 里面没有了

**Comment by VincentYangFan** [comment]
> > > 贝壳云也是 四个usb3.0的接口全部只能识别成2.0模式 无法使用3.0
> > 
> > 
> > 是硬件物理连接的问题，还是系统软件限制，我看内核 usb3.0 驱动有加载 我插入 usb3.0 的读卡器，连 usb2.0 模式都识别不出来，指示灯也不亮，感觉设备没有枚举到
> 
> 我有刷其他4.x内核和5.x内核的openwrt和armbian系统 usb3.0都能正常工作 但是刷6.x内核系统的usb3.0都无法正常工作

太专业了，我等下刷下 5.x 内核试试

**Comment by VincentYangFan** [comment]
> > > 贝壳云也是 四个usb3.0的接口全部只能识别成2.0模式 无法使用3.0
> > 
> > 
> > 是硬件物理连接的问题，还是系统软件限制，我看内核 usb3.0 驱动有加载 我插入 usb3.0 的读卡器，连 usb2.0 模式都识别不出来，指示灯也不亮，感觉设备没有枚举到
> 
> 我有刷其他4.x内核和5.x内核的openwrt和armbian系统 usb3.0都能正常工作 但是刷6.x内核系统的usb3.0都无法正常工作

我试了 202403 release 里面的 [Armbian_24.5.0_amlogic_s905x3_jammy_5.15.153_server_2024.04.01.img.gz] 镜像包
依旧和 6.x 内核一样的现象，我感觉像是设备物理硬件出了问题，毕竟 usb供电和 usb2.0 枚举都没有成功

**Comment by VincentYangFan** [comment]
BTW，我刷了安卓系统，也是识别不到 USB3.0 存储，应该是硬件有问题，但是这个口又可以识别到 USB2.0 的读卡器(必须带指示灯的USB2.0读卡器，不带识别不出来），USB2.0 的 U 盘也识别不出来，情况太复杂了
