### ISSUE TITLE
为什么fixdep是x86-64架构的二进制格式，而不是aarch64

### ISSUE THREAD

**Issue by twallpasser** [ophub/amlogic-s9xxx-armbian#2205]
尝试编译USB无线网卡驱动报错，发现原来是这个程序二进制格式不兼容。
```
zsh: exec format error: ./fixdep
```
![1712040597641](https://github.com/ophub/amlogic-s9xxx-armbian/assets/20509040/e2c1299e-5434-4ec3-92c8-2d1d477a0ea0)

**Comment by ophub** [comment]
With the help of [flippy](https://github.com/unifreq), the fixdep file in the header has been correctly modified to the arm64 format, and installing the latest version of the kernel should resolve the issue.

在[flippy](https://github.com/unifreq)大佬的帮助下，header里fixdep文件已经正确修正为了arm64格式了，安装最新版本的内核可以解决问题。
