### ISSUE TITLE
申请适配CMCC TCN200（RK3588）

### ISSUE THREAD

**Issue by darkwanderer517** [ophub/amlogic-s9xxx-armbian#2208]
3.5双盘位NAS，RK3588，4GB LPDDR4，16GB eMMc
原系统为Android，鄙人菜鸟不会导出dtb，用RKDevtools把uboot、misc、boot、recovery分区导出来了。申请做适配
链接：https://pan.baidu.com/s/1PuIqoYeAn9aXux6v3BhdyA?pwd=j682

**Comment by Xianleewu** [comment]
我可以适配，问题是小黄鱼上搜不到这设备

**Comment by stevenliuit** [comment]
你可以尝试一下 把3588市面的固件都刷一遍 看看哪个可以用 没准有惊喜啊

**Comment by Arthur97172** [comment]
> 3.5双盘位NAS，RK3588，4GB LPDDR4，16GB eMMc 原系统为Android，鄙人菜鸟不会导出dtb，用RKDevtools把uboot、misc、boot、recovery分区导出来了。申请做适配 链接：https://pan.baidu.com/s/1PuIqoYeAn9aXux6v3BhdyA?pwd=j682

下载链接已经失效，能再分享一下吗？

**Comment by hchyhchyxh** [comment]
> > 3.5双盘位NAS，RK3588，4GB LPDDR4，16GB eMMc 原系统为Android，鄙人菜鸟不会导出dtb，用RKDevtools把uboot、misc、boot、recovery分区导出来了。申请做适配 链接：https://pan.baidu.com/s/1PuIqoYeAn9aXux6v3BhdyA?pwd=j682
> 
> 下载链接已经失效，能再分享一下吗？

https://pan.baidu.com/s/1ap4G0jm3kcWEqZhrEAEs1g?pwd=heeg 提取码: heeg 刚提取的。

**Comment by zwm102** [comment]
楼主，能否将整个系统都备份一下，我这有一台固件搞坏了，网上找不到原始固件

**Comment by bennykcb** [comment]
楼主你好，想请问一下，这机子怎么进RKDevtools模式？连接电脑要特定哪个usb口吗？直接用C to C线连接电脑可以吗？
