### ISSUE TITLE
CM201-1-YS刷入成功，有线无线都连接成功

### ISSUE THREAD

**Issue by wgbingo** [ophub/amlogic-s9xxx-armbian#2209]
**Device Information | 设备信息**
 - SOC: [S095l3b]
 - Model [CM201-1-YS]
 - 无线网卡[RTL8822CS]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.152]
 - Release: [bullseye]
 - Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img

**过程描述**
先刷入安卓9带root的固件，成功启动桌面后进入设置恢复出厂设置（密码通常是10086），在重启的时候插入写好的U盘，这时可以插入TLL跑码，无须短接即可启动armbian，此时如果没意外有线网卡是能够自动获取ip了，然后登陆终端，用ip add查看有线和无线网卡的mac地址，在/etc/network/interfaces后面添加几行代码：
auto eth0
allow-hotplug eth0
pre-up ifconfig eth0 hw ether [eth0的mac，去掉前后中括号]
auto wlan0
pre-up ifconfig wlan0 hw ether [wlan0的mac，去掉前后中括号]

第二行是允许有线网口热拔插
第三五行是固定有线无线的mac地址
保存完后reboot，然后nmcli device status会显示wlan0的状态disconnecte，这就表示无线网卡也成功使能了，输入nmcli dev wifi list可以显示出附近的wifi信号，然后进入nmtui连接wifi。重新进入终端后会显示2个ip。

**Comment by wgbingo** [comment]
![585149ef75f28fbfb039966972b681a](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42059802/77253a58-fd23-43a3-913e-6ad46f355b25)
![2474b3e2a6c6d8a0acc9687b308d8f6](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42059802/c1aed0a4-15d3-432a-be39-25a0c0c36356)
![243f6777ab0c96603ca69b507336727](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42059802/bcf02a8b-9c46-4a97-b832-cfe417c4fc35)

**Comment by ophub** [comment]
感谢分享，你使用的安卓9的系统分享个下载地址，我转存到一份到 https://github.com/ophub/kernel/releases/tag/tools

**Comment by wgbingo** [comment]
> 感谢分享，你使用的安卓9的系统分享个下载地址，我转存到一份到 https://github.com/ophub/kernel/releases/tag/tools
> 
> 
> 你使用的是这个固件的默认配置吧，我把他加到这个组里：Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img

是的，直接使用默认配置，写入emmc的时候选了905l3b的cm211

**Comment by ophub** [comment]
好的，你使用的哪个安卓系统呢？有下载链接没？
如果方便的话把设备的正面，反面拍个照片，方便参考。
如果你有主板的照片，指定短接救砖点在哪的话标记下发个主板的照片。

**Comment by wgbingo** [comment]
> 好的，你使用的哪个安卓系统呢？有下载链接没？ 如果方便的话把设备的正面，反面拍个照片，方便参考。 如果你有主板的照片，指定短接救砖点在哪的话标记下发个主板的照片。

用这个包https://pan.baidu.com/s/15M9ZdZURTGdN5V17peoaqQ?pwd=6666
短接点背面R12
![1712201331999](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42059802/967fe83c-0c39-4932-86ad-2999f180c31f)
正面（红黑线为5V输出，接了风扇散热），散热片下面是确认905l3b
![6c427ec4a0d62e1172db24f621f80a2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42059802/7eaf970d-04ad-4505-a6ae-c6e6545dd8f2)
背面
![655494b82f21dcf9bb23b6e513c90ea](https://github.com/ophub/amlogic-s9xxx-armbian/assets/42059802/21ce2eb5-293b-47b5-bfda-acc730d2caff)

**Comment by ophub** [comment]
多谢分享
你分享的安卓系统我转存到了：https://github.com/ophub/kernel/releases/tag/tools
盒子也添加到支持列表里了：https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

**Comment by send-97** [comment]
需要ttl跳线才可进入吗

**Comment by wgbingo** [comment]
> 需要ttl跳线才可进入armbian吗

不用的，插入U盘后恢复出厂设置就启动，用网线ip登录就好啦。

**Comment by send-97** [comment]
> > 需要ttl跳线才可以进入armbian吗
> 
> 不用的，插入U盘后恢复出厂设置就启动，用网线ip登录就好啦。

我现在情况为  恢复出厂重启后也进入u盘系统 但是进不去 只在开启画面停留一下之后  显示器就熄屏了

**Comment by wgbingo** [comment]
> > > 需要ttl跳线才可以进入armbian吗
> > 
> > 不用的，插入U盘后恢复出厂设置就启动，用网线ip登录就好啦。
> 
> 我现在情况为  恢复出厂重启后也进入u盘系统 但是进不去 只在开启画面停留一下之后  显示器就熄屏了
那就连TTL进去安装咯

**Comment by wgbingo** [comment]
> > > 需要ttl跳线才可以进入armbian吗
> > 
> > 不用的，插入U盘后恢复出厂设置就启动，用网线ip登录就好啦。
> 
> 我现在情况为  恢复出厂重启后也进入u盘系统 但是进不去 只在开启画面停留一下之后  显示器就熄屏了

重启息屏就应该成功启动了，那就用TTL登录安装咯。

**Comment by hanguofu** [comment]
@wgbingo  :  楼主的手工挺好的哈~~请问用什么工具在外壳上开这么大的方孔啊 ？

**Comment by wgbingo** [comment]
> @wgbingo  :  楼主的手工挺好的哈~~请问用什么工具在外壳上开这么大的方孔啊 ？

先对好位置划线，再用烙铁开孔，矫正打磨。

**Comment by suzitao** [comment]
进入U盘后屏幕不输出吗

**Comment by wgbingo** [comment]
> 用电视盒子玩armbian和openwrt的都是人才啊

还得感谢大佬的无私奉献。

**Comment by yesfxm** [comment]
一模一样的机子我的WIFI打不开，换了版本都不行，大佬有没有你现在用的版本的下载地址

**Comment by nano-oss** [comment]
日期：2024-04-22
设备：cm201-1-ys
cpu:    s905l-3-B
网卡：RTL8822BS
跟楼主一摸一样的设备和板子，一样先刷的android9（是楼主的黑马出品的刷机包）然后尝试了ophub大佬的所有Armbian_24.5.0_amlogic_s905l3b的包，启动系统都是有线网络可以获取ip和上网，无线网卡却识别不到，使用ip add查看没有显示无线网卡，没法驱动无线网卡，有什么解决思路吗？还是说楼主用的armbian包是5.15.152内核和现在最新的内核不一样？
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64580813/f1de144b-2193-4cf6-939e-b71d24a8b2db)

**Comment by nano-oss** [comment]
@wgbingo 大佬有空的话可以帮忙看看吗？感谢

**Comment by wgbingo** [comment]
> 日期：2024-04-22
> 设备：cm201-1-ys
> cpu:    s905l-3-B
> 网卡：RTL8822BS
> 跟楼主一摸一样的设备和板子，一样先刷的android9（是楼主的黑马出品的刷机包）然后尝试了ophub大佬的所有Armbian_24.5.0_amlogic_s905l3b的包，启动系统都是有线网络可以获取ip和上网，无线网卡却识别不到，使用ip add查看没有显示无线网卡，没法驱动无线网卡，有什么解决思路吗？还是说楼主用的armbian包是5.15.152内核和现在最新的内核不一样？
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64580813/f1de144b-2193-4cf6-939e-b71d24a8b2db)
> 

进去安卓9恢复出厂设置的时候插入U盘启动armbian，这个操作很重要。

**Comment by nano-oss** [comment]
> > 日期：2024-04-22
> > 设备：cm201-1-ys
> > cpu:    s905l-3-B
> > 网卡：RTL8822BS
> > 跟楼主一摸一样的设备和板子，一样先刷的android9（是楼主的黑马出品的刷机包）然后尝试了ophub大佬的所有Armbian_24.5.0_amlogic_s905l3b的包，启动系统都是有线网络可以获取ip和上网，无线网卡却识别不到，使用ip add查看没有显示无线网卡，没法驱动无线网卡，有什么解决思路吗？还是说楼主用的armbian包是5.15.152内核和现在最新的内核不一样？
> > ![image](https://private-user-images.githubusercontent.com/64580813/324382719-f1de144b-2193-4cf6-939e-b71d24a8b2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzYwOTUsIm5iZiI6MTcxMzc3NTc5NSwicGF0aCI6Ii82NDU4MDgxMy8zMjQzODI3MTktZjFkZTE0NGItMjE5My00Y2Y2LTkzOWUtYjcxZDI0YThiMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYWZhMTQwZmE5ZThkNWY4NTllM2NjMzk4ODFhMDE4MTRlM2E4YWMwYjlhZTYyMWM5NjIwNzkwYTc1ZGE5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hBa_TWotECa8B38FJKTn-N-4Eki7-GsSUpjOmM_iGNQ)
> 
> 进去安卓9恢复出厂设置的时候插入U盘启动armbian，这个操作很重要。

我的疑惑是，安卓9开机先插上U盘然后点恢复出厂设置，还是点了恢复出厂设置屏幕黑了再马上插上U盘，我都是点了恢复出厂黑屏之后马上插上U盘

**Comment by wgbingo** [comment]
> > > 日期：2024-04-22
> > > 设备：cm201-1-ys
> > > cpu:    s905l-3-B
> > > 网卡：RTL8822BS
> > > 跟楼主一摸一样的设备和板子，一样先刷的android9（是楼主的黑马出品的刷机包）然后尝试了ophub大佬的所有Armbian_24.5.0_amlogic_s905l3b的包，启动系统都是有线网络可以获取ip和上网，无线网卡却识别不到，使用ip add查看没有显示无线网卡，没法驱动无线网卡，有什么解决思路吗？还是说楼主用的armbian包是5.15.152内核和现在最新的内核不一样？
> > > ![image](https://private-user-images.githubusercontent.com/64580813/324382719-f1de144b-2193-4cf6-939e-b71d24a8b2db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzYwOTUsIm5iZiI6MTcxMzc3NTc5NSwicGF0aCI6Ii82NDU4MDgxMy8zMjQzODI3MTktZjFkZTE0NGItMjE5My00Y2Y2LTkzOWUtYjcxZDI0YThiMmRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NDk1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwYWZhMTQwZmE5ZThkNWY4NTllM2NjMzk4ODFhMDE4MTRlM2E4YWMwYjlhZTYyMWM5NjIwNzkwYTc1ZGE5YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hBa_TWotECa8B38FJKTn-N-4Eki7-GsSUpjOmM_iGNQ)
> > 
> > 进去安卓9恢复出厂设置的时候插入U盘启动armbian，这个操作很重要。
> 
> 我的疑惑是，安卓9开机先插上U盘然后点恢复出厂设置，还是点了恢复出厂设置屏幕黑了再马上插上U盘，我都是点了恢复出厂黑屏之后马上插上U盘

把U盘全部分区删除重做一次，先插U盘再点恢复出厂设置，启动完试下我的方式添加eth0和wlan口的mac，然后重启网络服务应该就有了。

**Comment by Cxy-2008** [comment]
cm201-1ys还有另一个版本 不知道能不能刷
soc也是s905l3b 网卡8822cs
主板图片
![IMG_20240502_142014.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/5e92e985-26dc-4005-abb6-56d426c3c5fa)
网卡图片
![IMG_20240502_142054.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/72d3648d-f728-44fc-917e-a1064416df6b)
盒子底部信息
![IMG_20240502_142437.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/425f7d12-ef49-46fc-a9b2-554e1926e835)

**Comment by wgbingo** [comment]
> cm201-1ys还有另一个版本 不知道能不能刷
> soc也是s905l3b 网卡8822cs
> 主板图片
> ![IMG_20240502_142014.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/5e92e985-26dc-4005-abb6-56d426c3c5fa)
> 网卡图片
> ![IMG_20240502_142054.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/72d3648d-f728-44fc-917e-a1064416df6b)
> 盒子底部信息
> ![IMG_20240502_142437.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/425f7d12-ef49-46fc-a9b2-554e1926e835)
> 
> 
> 

跟我的板子一样的，肯定没问题。

**Comment by Cxy-2008** [comment]
> > cm201-1ys还有另一个版本 不知道能不能刷
> > soc也是s905l3b 网卡8822cs
> > 主板图片
> > ![IMG_20240502_142014.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/5e92e985-26dc-4005-abb6-56d426c3c5fa)
> > 网卡图片
> > ![IMG_20240502_142054.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/72d3648d-f728-44fc-917e-a1064416df6b)
> > 盒子底部信息
> > ![IMG_20240502_142437.jpg](https://github.com/ophub/amlogic-s9xxx-armbian/assets/127767886/425f7d12-ef49-46fc-a9b2-554e1926e835)
> > 
> > 
> > 
> 
> 跟我的板子一样的，肯定没问题。

好像咱emmc不一样诶

**Comment by gccysh** [comment]
cm201-2行不行啊？
我没看到这个型号

**Comment by gccysh** [comment]
大佬你好！cm201-2ys行不行啊？我没看到这个型号

**Comment by tinytinycn** [comment]
# CM201-1-YS S905L3B 无WI-FI网卡 成功刷入armbian
- CPU型号：S905L3B
- 双EMMC颗粒（特别注意：CM201-1-YS 存在单EMMC颗粒版本，请自行检查的主板EMMC颗粒）
- 晶晨刷机工具线刷android 9.0底包：[android_tv_cm201-1-ys_s905l3b.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_cm201-1-ys_s905l3b.tar.xz)
- U盘刷入armbian版本：[Armbian_24.11.0_amlogic_s905l3b_bookworm_6.1.107_server_2024.09.01.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.09/Armbian_24.11.0_amlogic_s905l3b_bookworm_6.1.107_server_2024.09.01.img.gz)
- 选项：122 , 同（CM211-1,M411A,B860AV3.2M,B860AV2.1U）
- DTB文件：meson-gxl-s905l3b-m302a.dtb
- U-BOOT文件：u-boot-p212.bin

线刷A方式的步骤与注意事项：
1. 插上电源线，保证刷机过程中的供电（暂时先不上电）
2. 长按reset按键，不放开（一般在AV音频口里面）
3. 插上USB双公头线，等待电脑侧-晶晨刷机工具识别出端口或设备，此时 **不要放开** reset按键
4. 若识别到端口或设备，则选择事先准备的android 9.0 底包img镜像文件，等待刷入镜像，刷入过程中电脑侧会反复识别到端口或设备，请不要放开reset按键，等待刷入到system分区时，差不多可以松开按键，等待刷入结束。烧录成功，点击暂停，拔下USB，重启设备。
5. 入识别不到端口或设备，请尝试线刷B方式。

线刷B方式的步骤与注意事项：
1.  插上电源线，保证刷机过程中的供电（暂时先不上电）
2. 插上USB双公头线
3. 用金属镊子短接一下 4R12 电阻（注意是短接一下即可），等待电脑侧-晶晨刷机工具识别出端口或设备
4. 选择事先准备的android 9.0 底包img镜像文件，等待刷入镜像，刷入过程中电脑侧会反复识别到端口或设备，请不要放开reset按键，等待刷入到system分区时，差不多可以松开按键，等待刷入结束。烧录成功，点击暂停，拔下USB，重启设备。（注意，仍然需要长按reset按键）

![WechatIMG525](https://github.com/user-attachments/assets/3e62b5bb-86ee-4e32-a8f0-2b92e284ca0e)
![WechatIMG526](https://github.com/user-attachments/assets/970d8ad1-ca03-4a53-b39f-3d624a7dabba)
![WechatIMG527](https://github.com/user-attachments/assets/af64713a-cac8-4cd3-9062-f1d26fa886e7)
![WechatIMG528](https://github.com/user-attachments/assets/e4488398-088c-4ebc-bf41-ebd8f98f730c)

**Comment by tinytinycn** [comment]
# CM201-1-YS S905L3 单EMMC颗粒 刷入android4.4.2 底包后，无法U盘启动 armbian
- CPU型号：S905L3
- 单EMMC颗粒（特别注意：CM201-1-6 YS 版本是 **单EMMC颗粒** 版本，请自行检查的主板EMMC颗粒）
- 晶晨刷机工具线刷android 4.4.2底包（已root，并开启adb 5114 端口）
- armbian 版本：[Armbian_24.11.0_amlogic_s905l3_bookworm_6.1.107_server_2024.09.01.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.09/Armbian_24.11.0_amlogic_s905l3_bookworm_6.1.107_server_2024.09.01.img.gz)
- DTB文件：meson-gxl-s905l3b-m302a.dtb
- U-BOOT文件：u-boot-p212.bin
使用adb shell reboot update，U盘启动 armbian 系统失败。卡开机第一屏画面后，反复重启。

![WechatIMG529](https://github.com/user-attachments/assets/e4cfe85c-8287-4ef7-bb1a-f506f999c97b)
![WechatIMG530](https://github.com/user-attachments/assets/743cd6bb-40e2-4aea-a825-977ffc8c701e)
![WechatIMG531](https://github.com/user-attachments/assets/429198b2-9b1b-4937-a3f2-5b7ccdd6e22a)

原因分析：可能是没有刷 android 9.0 底包的原因？如有此单EMMC版本的CM201-1-6 YS android 9.0 底包，望有心人提供 :)

**Comment by seeyoyoa** [comment]
> * Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img
这个版本的系统你还有吗？ 我和你一样的主板 cpu  rtl8822cs 怎么都出不来wifi

**Comment by kymf5898** [comment]
我也没有完全搞好，插u盘就是armbian,拔掉u盘就是电视系统



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月17日 21:33 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ophub/amlogic-s9xxx-armbian] CM201-1-YS刷入成功，有线无线都连接成功 (Issue #2209) |

Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img
这个版本的系统你还有吗？ 我和你一样的主板 cpu rtl8822cs 怎么都出不来wifi

**Comment by seeyoyoa** [comment]
> 我也没有完全搞好，插u盘就是armbian,拔掉u盘就是电视系统
> […](#)
> ---- 回复的原邮件 ---- | 发件人 | ***@***.***> | | 日期 | 2024年11月17日 21:33 | | 收件人 | ***@***.***> | | 抄送至 | ***@***.***>***@***.***> | | 主题 | Re: [ophub/amlogic-s9xxx-armbian] CM201-1-YS刷入成功，有线无线都连接成功 (Issue #2209) | Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img 这个版本的系统你还有吗？ 我和你一样的主板 cpu rtl8822cs 怎么都出不来wifi — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

不过我看你wifi读出来了，我wifi的影子都没看到

**Comment by seeyoyoa** [comment]
> **Device Information | 设备信息**
> 
> * SOC: [S095l3b]
> * Model [CM201-1-YS]
> * 无线网卡[RTL8822CS]
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version: [5.15.152]
> * Release: [bullseye]
> * Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img
> 
> **过程描述** 先刷入安卓9带root的固件，成功启动桌面后进入设置恢复出厂设置（密码通常是10086），在重启的时候插入写好的U盘，这时可以插入TLL跑码，无须短接即可启动armbian，此时如果没意外有线网卡是能够自动获取ip了，然后登陆终端，用ip add查看有线和无线网卡的mac地址，在/etc/network/interfaces后面添加几行代码： auto eth0 allow-hotplug eth0 pre-up ifconfig eth0 hw ether [eth0的mac，去掉前后中括号] auto wlan0 pre-up ifconfig wlan0 hw ether [wlan0的mac，去掉前后中括号]
> 
> 第二行是允许有线网口热拔插 第三五行是固定有线无线的mac地址 保存完后reboot，然后nmcli device status会显示wlan0的状态disconnecte，这就表示无线网卡也成功使能了，输入nmcli dev wifi list可以显示出附近的wifi信号，然后进入nmtui连接wifi。重新进入终端后会显示2个ip。

你好，Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img 这个版本的系统你有吗 可以分享一下吗？czhze@163.com

**Comment by kitten-UX** [comment]
你好，我的是CH代工版，可以正常从优盘启动系统，但是写入EMMC之后从EMMC启动就获取不到IP，有没有CM201-1-CH的DTB文件分享一下

**Comment by sielun88** [comment]
有个bug的地方，CM201-1-YS刷入[android_tv_cm201-1-ys_s905l3b.tar.xz]后，蓝牙无法连接，设置那里，无法点击打开蓝牙功能。不能能否修正？谢谢

**Comment by jbpop1** [comment]
> 还是不行，放弃了，应该是内核不支持我这个网卡型号：RTL8822BS

最后又解决无线网卡吗？我跟你的情况一样一样的

**Comment by jbpop1** [comment]
这个盒子的wifi有朋友安装上驱动了吗？盒子跟楼主的是一样的，现在无法使用WiFi

**Comment by hixin** [comment]
请问这版固件还有吗Armbian_24.5.0_amlogic_s905l3b_bullseye_5.15.152_server_2024.03.16.img

**Comment by dumplingwrapper** [comment]
@wgbingo 你好，dtb可以提取一份么，我像看看，改一下S905L3a的dts，用来支持RTL8822CS

**Comment by niceqwer55555** [comment]
一定要先用安卓9连wifi，再安装armbian,才会有wifi
