### ISSUE TITLE
Hk1box LED 屏显示控制vfdservice文件报错

### ISSUE THREAD

**Issue by szcare** [ophub/amlogic-s9xxx-armbian#221]
HK1BOX,内核5.15，执行armbian-led,vfdservice文件提示出错
/usr/share/openvfd/vfdservice: line 1: syntax error near unexpected token `newline'
/usr/share/openvfd/vfdservice: line 1: `<!DOCTYPE html>'

**Comment by ophub** [comment]
内核版本是哪个
操作报错截图

**Comment by szcare** [comment]
已经解决。应该是网络下载导致文件丢失导致的，后面核对文件大小，发现下载的文件比网站上的文件小，重新下载后就没有报错了。

**Comment by ophub** [comment]
好的
