### ISSUE TITLE
CM311-1a ch 想重新刷机

### ISSUE THREAD

**Issue by xlmyd** [ophub/amlogic-s9xxx-armbian#2210]
大佬，我的CM311-1a ch 想重新刷机，早上已经刷过armbian，如何重新刷过呢？又要重新刷安卓底包再来一次吗？还有我这个型号的机顶盒是选择304还是其它的？里面没有显示有CM311-1a ch，所以我只刷了CM311-1a YST的那个。

**Comment by ophub** [comment]
再次刷机不用刷回安卓，直接USB启动再次写入新的系统就可以。

你刷了的那个可以正常使用吧，那就刷这个即可，你这个还是第一次有人反馈，如果你可以正常使用我添加到列表里，把你刷机选择的固件名字，刷入时选择的序号分享一下，把你的盒子正面和地下拍个外观照片发一个。

你有安卓系统的话分享一下你刷机用的安卓系统的下载链接，我转载备份个。
如果知道主板的刷机短接救砖点的话在主板图片上标记下。

**Comment by xlmyd** [comment]
因为系统被我搞崩了，所以只能重新来。等下我整理完成后会全部发送过来。感谢回复。

**Comment by xlmyd** [comment]
我刚才重新选择了304，是我没注意，其实是有标注的，刷机包我选择Armbian_24.5.0_amlogic_s905l3a_noble_6.1.83_server_2024.04.01.img这个，安卓包选择https://pan.baidu.com/s/1P6B91TWKUplMRhqChlXrpA 
提取码：65K1，里面有短接点，和我的一模一样，没区别。
