### ISSUE TITLE
CasaOS无法安装。

### ISSUE THREAD

**Issue by xlmyd** [ophub/amlogic-s9xxx-armbian#2212]
我使用armbian-software命令进行安装casaos，也提示成功了，但是打开给出的网址就无法打开，且再次输入armbian-software命令却显示没有安装过，这是为什么？安装docker就成功了。
![图片1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166010679/8b505a6f-66ad-4dba-9a57-8489be7b817c)
![图片2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166010679/8bb26b68-e209-4956-bff7-6a77f890ba49)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/7175fe6c7109a1ea853bfd1632370bd72bc346d2/build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software/command-service.sh#L485-L486

选择309安装就是使用官方的脚本进行安装。

**Comment by ophub** [comment]
你在哪个版本下安装失败的，我测试下发生了什么问题

**Comment by xlmyd** [comment]
我就是noble版本的，我换一个刷机吧

**Comment by mia0x75** [comment]
端口不是81，是80，脚本需要改一下。

**Comment by ophub** [comment]
我之前是写死了81，看上面的信息，我早上测试之前的脚本官方是用了80。

现在己经更正了。

**Comment by kokle2023** [comment]
小白弱弱问下，安装报错：curl: (7) Failed to connect to get.casaos.io port 443 after 5315 ms: Couldn't connect to server
grep: /etc/casaos/gateway.ini: No such file or directory
这是啥问题呢？

**Comment by ophub** [comment]
你的网络问题，没有下载安装成功。

**Comment by kokle2023** [comment]
> 你的网络问题，没有下载安装成功。

谢谢大佬回复。别的应用都正常安装，就是casaos不行。用您的脚本还是官方脚本都不行。需要在哪里设置？

**Comment by kokle2023** [comment]
另外弱弱的问下，dtb 和 u-boot部分没有修改。armbian是U盘启动的，网络问题会不会和机顶盒的安卓系统有关系？

**Comment by ophub** [comment]
有关
我的脚本就是调用官方脚本，安装结果一样，有错误你上网搜索下相关问题。

**Comment by kokle2023** [comment]
> 有关 我的脚本就是调用官方脚本，安装结果一样，有错误你上网搜索下相关问题。

好的~谢谢大佬

**Comment by xlmyd** [comment]
我重新刷jammy之后成功安装了，多谢提醒。

**Comment by zhouwei336** [comment]
curl: (7) Failed to connect to get.casaos.io port 443 after 16 mS: coulan't connect to server

**Comment by zhouwei336** [comment]
换了网络也不行呀！问题出在哪里呢？
