### ISSUE TITLE
E900V22D主板为S905L3-B通过U盘启动进入openwrt或Armbian卡在卡机画面然后黑屏

### ISSUE THREAD

**Issue by send-97** [ophub/amlogic-s9xxx-armbian#2213]
**Device Information | 设备信息**
 - SOC: [S905L3-B]
 - Model [ E900V22D湖南电信版]

**Armbian Version | 系统版本**
 - Kernel Version: [看下面已测试]
 - Release: [ jammy]

**Describe the bug | 问题描述**
记录一下目前已进入细节(成功)

刷入的Android底包为：

android_tv_e900v22e_e900v22d_s905l3b.tar.xzAndroid4.4

目前以测试包为：
(Armbian)
Armbian_24.5.0_amlogic_s905l2_jammy_5.15.153_server_2024.04.01.img.gz （卡在卡机画面然后黑屏）

Armbian_24.5.0_amlogic_s905l3b_jammy_5.15.153_server_2024.04.01.img.gz（卡在卡机画面然后黑屏）

[Armbian_24.5.0_amlogic_s905l3b_noble_5.15.153_server_2024.04.01.img.gz] （卡在卡机画面然后黑屏）

(openWrt)

[openwrt_amlogic_s905l3b_k5.15.153_2024.04.03.img.gz] (卡在卡机画面然后黑屏）
[openwrt_amlogic_s905l3b_k6.1.83_2024.04.03.img.gz] (卡在卡机画面然后黑屏）
[openwrt_amlogic_s905l3b-e900 v22e_k5.15.153_2024。 04.03.img.gz]（同上）
[openwrt_amlogic_s905l3b-e900v22e_k6.1.83_2024.04.03.img.gz]（同上）
[openwrt_amlogic_s905l2_k5.15.153_2024.04.03.img.gz]（同上）

以上都是已测试的包

机顶盒型号为E900V22D
运营商为湖南电信   cpu 为s905L3-B

2024.4.10补充回复:
其实一直是刷进去了的 不过不知道 刷进去后 插入hdmi屏幕不会显示 根据O大指示   取查看了局域网地址  进入后  就成功啦  刷的是openwrt系统   建议如果想用openwrt装插件的  不要刷带lede的

**Comment by ophub** [comment]
设备接入网络去路由器看IP，魔百盒多半没HDMI

**Comment by v587xpt** [comment]
我也遇到了相同的问题，请问你解决了吗？
我通过U盘的方式安装了不同的安卓系统，但是 abd shell reboot update 重启之后也一直是黑屏。太想刷一个armbian了，可惜我是个linux运维，电子这方面的不是太懂（试过短接，但是短接一直没成功），菜鸡一只，希望有大佬帮我
![253bffe64076397c946dea033cae968](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37898515/02824be6-0f75-48e7-a25e-37bdfe2f8a3d)
![3f828eb9396bbddd4325fce3d41492a](https://github.com/ophub/amlogic-s9xxx-armbian/assets/37898515/78d8caa3-c996-4aba-9a73-3bbebb9fc018)

**Comment by send-97** [comment]
> 我也遇到了同样的问题，请问你解决了吗？ 我通过U盘的方式安装了不同的Android系统，但是abd shell restart update重启之后也一直是黑屏。太想刷一个armbian了，可惜我是个linux运维，电子这方面的不太懂（试过短接，但是短接一直没成功），菜鸡一只，希望有大佬帮我 ![253bffe64076397c946dea033cae968](https://private-user-images.githubusercontent.com/37898515/320345440-02824be6-0f75-48e7-a25e-37bdfe2f8a3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NDAtMDI4MjRiZTYtMGY3NS00OGU3LWEyNWUtMzdiZGZlMmY4YTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWEzOGNlZjk1ZjA5MDZhNDA5Nzg4ZmZlNGMwYWExYjZlODhkODBmMTFjZjU1MzgwNjRjOWMyYTBmYWJlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-HaiT2xiqvdKpXqDK7VWqzhF0C5ePyJn8URBJOVaD8) ![3f828eb9396bbddd4325fce3d41492a](https://private-user-images.githubusercontent.com/37898515/320345459-78d8caa3-c996-4aba-9a73-3bbebb9fc018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NTktNzhkOGNhYTMtYzk5Ni00YWJhLTlhNzMtM2JiZWJiOWZjMDE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZmVkNTlhY2Q5N2ZjZmVhMzNiMDgxZTQ5ZGQxYTc3ZDEwNGYwYjhjMjU5NTViZjA1MWIwODY2YzE1MjE2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZoX-123E160UZOG_BKt3c1hsun4asczFArnGwxsD5w)

根据o大的指示  我在黑屏后  登录路由器查看了一下 盒子的局域网ip  然后用电脑 访问这个ip  进行了连接

**Comment by v587xpt** [comment]
> > 我也遇到了同样的问题，请问你解决了吗？ 我通过U盘的方式安装了不同的Android系统，但是abd shell restart update重启之后也一直是黑屏。太想刷一个armbian了，可惜我是个linux运维，电子这方面的不太懂（试过短接，但是短接一直没成功），菜鸡一只，希望有大佬帮我 ![253bffe64076397c946dea033cae968](https://private-user-images.githubusercontent.com/37898515/320345440-02824be6-0f75-48e7-a25e-37bdfe2f8a3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NDAtMDI4MjRiZTYtMGY3NS00OGU3LWEyNWUtMzdiZGZlMmY4YTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWEzOGNlZjk1ZjA5MDZhNDA5Nzg4ZmZlNGMwYWExYjZlODhkODBmMTFjZjU1MzgwNjRjOWMyYTBmYWJlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-HaiT2xiqvdKpXqDK7VWqzhF0C5ePyJn8URBJOVaD8) ![3f828eb9396bbddd4325fce3d41492a](https://private-user-images.githubusercontent.com/37898515/320345459-78d8caa3-c996-4aba-9a73-3bbebb9fc018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NTktNzhkOGNhYTMtYzk5Ni00YWJhLTlhNzMtM2JiZWJiOWZjMDE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZmVkNTlhY2Q5N2ZjZmVhMzNiMDgxZTQ5ZGQxYTc3ZDEwNGYwYjhjMjU5NTViZjA1MWIwODY2YzE1MjE2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZoX-123E160UZOG_BKt3c1hsun4asczFArnGwxsD5w)
> 
> 根据o大的指示 我在黑屏后 登录路由器查看了一下 盒子的局域网ip 然后用电脑 访问这个ip 进行了连接 而且多个包都是可用的 我的建议是你在黑屏的情况局域网看看 盒子的ip然后用电脑访问ip进行连接操作

就在昨天，我已经学会了通过短接的方式刷机了，已经成功的将它刷成了砖，现在正在想办法补救，奈何没有合适的镜像，试过一些安卓镜像，刷进去之后开机卡屏，也获取不到IP地址；

**Comment by send-97** [comment]
> > > 我也遇到了同样的问题，请问你解决了吗？ 我通过U盘的方式安装了不同的Android系统，但是abd shell restart update重启之后也一直是黑屏。太想刷一个armbian了，可惜我是个linux运维，电子这方面的不太懂（试过短接，但是短接一直没成功），菜鸡一只，希望有大佬帮我![253bffe64076397c946dea033cae968](https://private-user-images.githubusercontent.com/37898515/320345440-02824be6-0f75-48e7-a25e-37bdfe2f8a3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NDAtMDI4MjRiZTYtMGY3NS00OGU3LWEyNWUtMzdiZGZlMmY4YTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWEzOGNlZjk1ZjA5MDZhNDA5Nzg4ZmZlNGMwYWExYjZlODhkODBmMTFjZjU1MzgwNjRjOWMyYTBmYWJlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-HaiT2xiqvdKpXqDK7VWqzhF0C5ePyJn8URBJOVaD8) ![3f828eb9396bbddd4325fce3d41492a](https://private-user-images.githubusercontent.com/37898515/320345459-78d8caa3-c996-4aba-9a73-3bbebb9fc018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NTktNzhkOGNhYTMtYzk5Ni00YWJhLTlhNzMtM2JiZWJiOWZjMDE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZmVkNTlhY2Q5N2ZjZmVhMzNiMDgxZTQ5ZGQxYTc3ZDEwNGYwYjhjMjU5NTViZjA1MWIwODY2YzE1MjE2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZoX-123E160UZOG_BKt3c1hsun4asczFArnGwxsD5w)
> > 
> > 
> > 根据o大的指示我建议在黑屏后登录路由器查看盒子的局域网ip然后用电脑访问这个ip进行了连接而且多个包都是可用的我的是你在黑屏的情况盒子的ip然后用电脑访问ip进行连接操作
> 
> 就在昨天，我已经学会了通过短接的方式刷机了，已经成功的将其刷成砖了，现在正在想办法成功，奈何没有合适的图片，看了一些安卓的图片，进去之后开机卡屏，也获取不到IP地址；

s905l3-B的包很多的  你竟然可以线刷  拿救砖也是很简单的  建议看看我上面的那个原生4.4.2的安卓包 android_tv_e900v22e_e900v22d_s905l3b.tar.xzAndroid4.4

**Comment by zhouxuanlang** [comment]
logo反复跳是怎么回事😂

**Comment by v587xpt** [comment]
> > > > 我也遇到了同样的问题，请问你解决了吗？ 我通过U盘的方式安装了不同的Android系统，但是abd shell restart update重启之后也一直是黑屏。太想刷一个armbian了，可惜我是个linux运维，电子这方面的不太懂（试过短接，但是短接一直没成功），菜鸡一只，希望有大佬帮我![253bffe64076397c946dea033cae968](https://private-user-images.githubusercontent.com/37898515/320345440-02824be6-0f75-48e7-a25e-37bdfe2f8a3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NDAtMDI4MjRiZTYtMGY3NS00OGU3LWEyNWUtMzdiZGZlMmY4YTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWEzOGNlZjk1ZjA5MDZhNDA5Nzg4ZmZlNGMwYWExYjZlODhkODBmMTFjZjU1MzgwNjRjOWMyYTBmYWJlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-HaiT2xiqvdKpXqDK7VWqzhF0C5ePyJn8URBJOVaD8) ![3f828eb9396bbddd4325fce3d41492a](https://private-user-images.githubusercontent.com/37898515/320345459-78d8caa3-c996-4aba-9a73-3bbebb9fc018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NTktNzhkOGNhYTMtYzk5Ni00YWJhLTlhNzMtM2JiZWJiOWZjMDE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZmVkNTlhY2Q5N2ZjZmVhMzNiMDgxZTQ5ZGQxYTc3ZDEwNGYwYjhjMjU5NTViZjA1MWIwODY2YzE1MjE2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZoX-123E160UZOG_BKt3c1hsun4asczFArnGwxsD5w)
> > > 
> > > 
> > > 根据o大的指示我建议在黑屏后登录路由器查看盒子的局域网ip然后用电脑访问这个ip进行了连接而且多个包都是可用的我的是你在黑屏的情况盒子的ip然后用电脑访问ip进行连接操作
> > 
> > 
> > 就在昨天，我已经学会了通过短接的方式刷机了，已经成功的将其刷成砖了，现在正在想办法成功，奈何没有合适的图片，看了一些安卓的图片，进去之后开机卡屏，也获取不到IP地址；
> 
> s905l3-B的包很多的 你竟然可以线刷 拿救砖也是很简单的 建议看看我上面的那个原生4.4.2的安卓包 android_tv_e900v22e_e900v22d_s905l3b.tar.xzAndroid4.4

请问有 android_tv_e900v22e_e900v22d_s905l3b.tar.xzAndroid4.4 这个线刷包的下载地址吗，我试了很多线刷包都不行，刷出来的多数是黑屏，也有出现了logo的，但是一直卡在那里；求助

**Comment by zhouxuanlang** [comment]
https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v22d_hg680-lc_hg680-ly_hg680-lv_s905l3b.tar.xz   我用的是这个底包，然后用开心助手adbroot，调试选项有个重启U盘启动之类的选项，然后就是用U盘armbian启动，，，，这个盒子使用armbian他hdmi不输出的，你要自己去路由器看ip地址，然后ssh连上去操作

**Comment by zhouxuanlang** [comment]
使用ubt2.1版本的烧录，线刷，，，不行就关掉软件多刷几次

**Comment by zhouxuanlang** [comment]
> > > > > 我也遇到了同样的问题，请问你解决了吗？ 我通过U盘的方式安装了不同的Android系统，但是abd shell restart update重启之后也一直是黑屏。太想刷一个armbian了，可惜我是个linux运维，电子这方面的不太懂（试过短接，但是短接一直没成功），菜鸡一只，希望有大佬帮我![253bffe64076397c946dea033cae968](https://private-user-images.githubusercontent.com/37898515/320345440-02824be6-0f75-48e7-a25e-37bdfe2f8a3d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NDAtMDI4MjRiZTYtMGY3NS00OGU3LWEyNWUtMzdiZGZlMmY4YTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MWEzOGNlZjk1ZjA5MDZhNDA5Nzg4ZmZlNGMwYWExYjZlODhkODBmMTFjZjU1MzgwNjRjOWMyYTBmYWJlNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5-HaiT2xiqvdKpXqDK7VWqzhF0C5ePyJn8URBJOVaD8) ![3f828eb9396bbddd4325fce3d41492a](https://private-user-images.githubusercontent.com/37898515/320345459-78d8caa3-c996-4aba-9a73-3bbebb9fc018.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI3MDEsIm5iZiI6MTcxMjY5MjQwMSwicGF0aCI6Ii8zNzg5ODUxNS8zMjAzNDU0NTktNzhkOGNhYTMtYzk5Ni00YWJhLTlhNzMtM2JiZWJiOWZjMDE4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA5VDE5NTMyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1ZmVkNTlhY2Q5N2ZjZmVhMzNiMDgxZTQ5ZGQxYTc3ZDEwNGYwYjhjMjU5NTViZjA1MWIwODY2YzE1MjE2NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TZoX-123E160UZOG_BKt3c1hsun4asczFArnGwxsD5w)
> > > > 
> > > > 
> > > > 根据o大的指示我建议在黑屏后登录路由器查看盒子的局域网ip然后用电脑访问这个ip进行了连接而且多个包都是可用的我的是你在黑屏的情况盒子的ip然后用电脑访问ip进行连接操作
> > > 
> > > 
> > > 就在昨天，我已经学会了通过短接的方式刷机了，已经成功的将其刷成砖了，现在正在想办法成功，奈何没有合适的图片，看了一些安卓的图片，进去之后开机卡屏，也获取不到IP地址；
> > 
> > 
> > s905l3-B的包很多的 你竟然可以线刷 拿救砖也是很简单的 建议看看我上面的那个原生4.4.2的安卓包 android_tv_e900v22e_e900v22d_s905l3b.tar.xzAndroid4.4
> 
> 请问有 android_tv_e900v22e_e900v22d_s905l3b.tar.xzAndroid4.4 这个线刷包的下载地址吗，我试了很多线刷包都不行，刷出来的多数是黑屏，也有出现了logo的，但是一直卡在那里；求助
已回复，在评论区里
