### ISSUE TITLE
鲸鱼盒子(905x3)使用问题求助

### ISSUE THREAD

**Issue by Richardleeeeeee** [ophub/amlogic-s9xxx-armbian#2217]
O大,求助,先行谢过.
是这样的,我手上有一个鲸鱼盒子,是之前你们讨论过的.
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1166
具体issue在这里.
我这边主要问题是想找到这个机器的原厂系统,因为在我刷机时不小心直接把bootloader给勾选上了.现在刷完机后无HDMI显示输出.
然后我看您有把该原厂系统备份,我下载后解压是一个60G左右的镜像,但是通过USB_Burning_Tool这个工具确无法刷入,具体显示载入镜像时报错.
想问问这个镜像您是如何进行刷入或者还有别的方法救活吗?
另外在这里@ysuolmai @9runner 两位大佬,麻烦您通过一下我的QQ群申请.
谢谢您们.

**Comment by ophub** [comment]
U盘启动armbian，把这个压缩包放在/ddbr指定目录下，使用armbian-ddbr选项r恢复

**Comment by Richardleeeeeee** [comment]
@ophub 非常感谢您 o大,我会自己查阅一下资料试试.

**Comment by Richardleeeeeee** [comment]
使用了U盘启动armbian,还是没有HDMI输出,估计成砖了..
哎..
谢谢Q大帮助..

**Comment by 9runner** [comment]
鲸鱼盒子本身就有存在 HDMI 输出黑屏的毛病，关键在于选取适配的 armbian 镜像。具体爬楼更早的 issue 吧，比如：(小鲸鱼盒子(905x3)使用方法介绍 #1166)

**Comment by Richardleeeeeee** [comment]
> 鲸鱼盒子本身就有存在 HDMI 输出黑屏的毛病，关键在于选取适配的 armbian 镜像。具体爬楼更早的 issue 吧，比如：(小鲸鱼盒子(905x3)使用方法介绍 #1166)

您好，我这边已经尝试刷了别人修改的安卓系统，能启动，而且前面的小led屏也是能亮的。接入网线也能拿的到IP，也是能驱动千兆的网卡，依旧也是没有HDMI的输出。

然后我试了用U盘刷了O大的两个系统，分别是5.1和6.1的Armenian。通过按着刷机键上电启动U盘系统（我应该没有做错？是这样启动吧。），依旧没有HDMI输出。而且同时前面的小屏没有显示，但是在我的路由器日志看到有一个设备只有100兆速率的设备上线，没有获取IP，导致我想SSH也没有IP进入。

能麻烦你看看，还有什么思路给我一下吗？
谢谢您。

不知道自己表述清楚没有，如果我还有没表述清楚的，请见谅。

**Comment by Richardleeeeeee** [comment]
> 鲸鱼盒子本身就有存在 HDMI 输出黑屏的毛病，关键在于选取适配的 armbian 镜像。具体爬楼更早的 issue 吧，比如：(小鲸鱼盒子(905x3)使用方法介绍 #1166)

对了 能请问您一下您手上又https://github.com/ophub/amlogic-s9xxx-armbian/issues/1166#issuecomment-1547143202
这位大佬的QQ群嘛?能不能让他通过我一下 我看能不能进去下载个安卓系统刷一下

THX...

**Comment by ysuolmai** [comment]
> O大,求助,先行谢过. 是这样的,我手上有一个鲸鱼盒子,是之前你们讨论过的. #1166 具体issue在这里. 我这边主要问题是想找到这个机器的原厂系统,因为在我刷机时不小心直接把bootloader给勾选上了.现在刷完机后无HDMI显示输出. 然后我看您有把该原厂系统备份,我下载后解压是一个60G左右的镜像,但是通过USB_Burning_Tool这个工具确无法刷入,具体显示载入镜像时报错. 想问问这个镜像您是如何进行刷入或者还有别的方法救活吗? 另外在这里@ysuolmai @9runner 两位大佬,麻烦您通过一下我的QQ群申请. 谢谢您们.

我没有那个群的管理权限，没法帮你。安卓镜像你直接用slimbox tox1 42版本那个就行了
