### ISSUE TITLE
O大  求助 将系统写入EMMC后  盒子以外断电容易导致无法启动

### ISSUE THREAD

**Issue by miaofeifu** [ophub/amlogic-s9xxx-armbian#2218]
**Device Information | 设备信息**
 - SOC: [e.g. S905]
 - Model [e.g. E900S]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
系统写入EMMC后正常使用中，如果突然意外断电后有概率系统无法启动，黑屏不跑码。使用外置TF卡可以启动到Armbian系统，然后关机拔出TF卡，系统又能正常启动，经过我多次实验，我发现大概率是BOOT分区是FAT32格式在意外断电的情况下出现磁盘错误，外置TF启动系统的时候又把这个分区的错误修复了所以可以通过外置系统重新修复引导，我想求助O大的是，可不可以将BOOT分区改为EXT4格式，改了以后UUID改为和FAT32一样的情况下，是否还能引导系统？

**Comment by ophub** [comment]
amlogic系列的盒子太多，经常需要拿一个img更改`/boot/uEnv.txt`的dtb值，如果是fat32的话，usb插在电脑上直接双击就可以打开boot更改这个文件了，如果是ext4就不能这么操作了，需要自己找个linux挂载img，映射boot目录进去改，这一下就把很多初入门的同学挡在了门外，换成ext4后感觉有一定比例的同学不能完成这个修改工作，直接进不去armbian/openwrt的大门了。

**Comment by miaofeifu** [comment]
> amlogic系列的盒子太多，经常需要拿一个img更改`/boot/uEnv.txt`的dtb值，如果是fat32的话，usb插在电脑上直接双击就可以打开boot更改这个文件了，如果是ext4就不能这么操作了，需要自己找个linux挂载img，映射boot目录进去改，这一下就把很多初入门的同学挡在了门外，换成ext4后感觉有一定比例的同学不能完成这个修改工作，直接进不去armbian/openwrt的大门了。
> 
> 有些外贸盒子需要自己换几颗电容，增加供电的稳定性，可以解决你的问题。

O大 不是外贸盒子 就是创维的E900ST  S905芯片那个  1G内存  8G EMMC  换电容换那个电容呢  主供电电容 还是EMMC供电的电容？

**Comment by ophub** [comment]
我不会换，f大经常指导大家换，有些主板他做了祥细的标注和拍照示范。你参考这些资料可以对usb/供电等多处进行更换。思路是通用的。

**Comment by allonmymind** [comment]
> 我不会换，f大经常指导大家换，有些主板他做了祥细的标注和拍照示范。你参考这些资料可以对usb/供电等多处进行更换。思路是通用的。

能否在armbian-install脚本里增加选择boot分区格式选择fat32或ext4的功能，和rootfs分区一样，刷机过程自主选择。

**Comment by mdogwoop** [comment]
同样问题，有什么解决方案吗
