### ISSUE TITLE
Panther X2（黑豹x2）wifi无线网络问题

### ISSUE THREAD

**Issue by tonywang1201** [ophub/amlogic-s9xxx-armbian#2221]
**Device Information | 设备信息**
SOC: [rk3566]
Model [Panther X2]
Armbian Version | 系统版本

Kernel Version: [ 5.15.100]
Release: [jammy/bullseye]

**Describe the bug | 问题描述**
在恩山看到[帖子](https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8297972&highlight=黑豹)，已知黑豹x2在istoreos环境下可以添加驱动启用无线网络，`wget -O brcmfmac43430-sdio-panther-x2.sh https://qsth520.gitee.io/files/brcmfmac43430-sdio-panther-x2.sh && bash brcmfmac43430-sdio-panther-x2.sh`，脚本内容：[gitee](https://qsth520.gitee.io/files/brcmfmac43430-sdio-panther-x2.sh)，请问黑豹x2能否在armbian系统下驱动wifi

**Comment by ophub** [comment]
```
cd /lib/firmware/brcm
ln -sf brcmfmac43430-sdio.bin brcmfmac43430-sdio.panther,x2.bin
ln -sf brcmfmac43430-sdio.clm_blob brcmfmac43430-sdio.panther,x2.clm_blob
ln -sf brcmfmac43430-sdio.txt brcmfmac43430-sdio.panther,x2.txt
```

在你的Panther X2里，按上面的方法，你操作下重启。这个操作和你上面的脚本要做的事情一样，这些文件系统带了，缺少的补充方法就是上面的这3个ln -sf。
