### ISSUE TITLE
创维e900V22C设置中文环境不成功

### ISSUE THREAD

**Issue by Motology** [ophub/amlogic-s9xxx-armbian#2222]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model [SKYWORTH E900V22C]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.153&6.1.84]
 - Release: [bullseye]

**Describe the bug | 问题描述**
SERVER版的BASH终端下，网上各种设置方式，包括locale的设置，/etc/default/locale的设置，profile的设置，下载wyq字体等等都试过了，但是就是不能成功得到中文界面。如果LC_MESSAGES设置为zh_CN.UTF-8，则命令行反馈提示和nano界面下面的快捷键提示都显示为菱形块，用telnet进入北大侠客行这样的中文环境也全是菱形块。如果LC_MESSAGES设置为en_US.UTF-8，则命令行反馈提示和nano界面都能正常，但进入telnet界面的中文依然还是菱形块。从windows传过来的中文文件名也都显示不了。
到底是哪里的问题？

**Comment by ophub** [comment]
armbian-config里安装语言

**Comment by Motology** [comment]
在armbian-config里面选择了en和zh的语言，并且设zh为默认语言，退出后重启回来还是全英文，而且命令行反馈和nano快捷键提示都变菱形，在export LANGUAGE=en_US.UTF8之后，才恢复正常显示英文，其他locale设置项都还是zh_CN.UTF-8，但系统仍然显示全英文。
