### ISSUE TITLE
荐片tvbox使用6.6内核，hdmi无输出

### ISSUE THREAD

**Issue by rehiy** [ophub/amlogic-s9xxx-armbian#2223]
**Device Information | 设备信息**
 - SOC: rockchip
 - Model: jp-tvbo

**Armbian Version | 系统版本**
 - Kernel Version: 6.6.25
 - Release: bookworm_6.6.25_server_2024.04.08

**Describe the bug | 问题描述**
荐片tvbox使用6.6内核，hdmi无输出，使用6.1内核正常。

**Comment by rehiy** [comment]
这是使用 6.1 内核时的正常输出截图

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8297757/efa23c5a-78f8-4c9f-9dce-83dcb7c0007c)

**Comment by uljjmhn520** [comment]
你好，请教下是怎么刷的。

我按照文档刷了几次，试了几个固件，都不能开机。然后文档里也没有荐片的专用的示例

**Comment by rehiy** [comment]
> 你好，请教下是怎么刷的。
> 
> 我按照文档刷了几次，试了几个固件，都不能开机。然后文档里也没有荐片的专用的示例

就是直接选img刷进去

**Comment by rehiy** [comment]
好的，我再试试

**Comment by mtdxc** [comment]
你们的荐片有线网卡是千兆的么？
我怎么买了个百兆网卡的，又遇到我这情况的没？

**Comment by rehiy** [comment]
> 你们的荐片有线网卡是千兆的么？ 我怎么买了个百兆网卡的，又遇到我这情况的没？

是千兆的

**Comment by mtdxc** [comment]
ethtool输出，支持千兆的，就是握手到百兆，网线和对端端口都是没问题的呀。
root@armbian:~# ethtool eth0
Settings for eth0:
        Supported ports: [ TP    MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
                                1000baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  10baseT/Half 10baseT/Full
                                             100baseT/Half 100baseT/Full
        Link partner advertised pause frame use: Symmetric Receive-only
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 100Mb/s
        Duplex: Full
        Auto-negotiation: on
        master-slave cfg: preferred slave
        master-slave status: slave
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: external
        MDI-X: Unknown
        Supports Wake-on: ug
        Wake-on: d
        Current message level: 0x0000003f (63)
                               drv probe link timer ifdown ifup
        Link detected: yes

**Comment by ophub** [comment]
参考f大的图给主板上几处供电的地方换一下电容

**Comment by rehiy** [comment]
这是干啥的？

**Comment by ophub** [comment]
上面网卡的问题的解决方案。你测试f大的6.6内核了没，hdmi可以了吧

**Comment by mtdxc** [comment]
> 上面网卡的问题的解决方案。你测试f大的6.6内核了没，hdmi可以了吧
谢谢了。

**Comment by rehiy** [comment]
> 上面网卡的问题的解决方案。你测试f大的6.6内核了没，hdmi可以了吧

f大的内核可以输出

**Comment by ophub** [comment]
`armbian-update -u stable -k 6.6.25`

现在默认的stable也采用了和f大相同的配置了，你更新到stable试试hdmi可以正常显示吧。

**Comment by colinwong92** [comment]
> 你好，请教下是怎么刷的。
> 
> 
> 
> 我按照文档刷了几次，试了几个固件，都不能开机。然后文档里也没有荐片的专用的示例

我的也是不能开机，请问你的解决了吗？只有安卓是正常的
