### ISSUE TITLE
x96mini+ P181 Amlogic S905W4  AIP1628

### ISSUE THREAD

**Issue by okpapt** [ophub/amlogic-s9xxx-armbian#2226]
Hello,

Sorry for my poor english and mistake.

I discover how to transform an Android tvbox into a mini Linux box for Home Assistant.
I don't know anything about linux, android, tvbox.

Model : X96mini+
Mother board  p281 by Droidlogic.
Driver led  AIP1628
CPU: Amlogic S905W4 , Quad Core ARM Cortex-A53
GPU: Mali-450 penta-core, up to 750MHz (DVFS)
RAM: 2GB DDRIII
ROM: 16GB eMMC
OS: Android 9.0
Built-in WiFi: 802.1.1b/g/n/ac,2.4G/5G WIFI
Lan: 10 / 100M
Working fine with android.

https://github.com/ophub/amlogic-s9xxx-armbian/issues/432 says I can use firmware for s905x3.

I downloaded [Armbian_24.5.0_amlogic_s905x3_bullseye_5.15.153_server_2024.04.08.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2024.04/Armbian_24.5.0_amlogic_s905x3_bullseye_5.15.153_server_2024.04.08.img.gz)
Is this the right choice?

With rufus I created a usb boot key from donwloaded file.
But, to modify uEnv.txt with FDT=/dtb/amlogic/... , as I can't find a meson-*s905x3-*.dtb file, I don't know which .dtb file to choose between:
- meson-gxl-s905w-tx3-mini.dtb
- meson-gxl-s905w-p281.dtb
- meson-gxl-s905w-x96-mini.dtb
- maybe one that I need create (it seems complicated)

Having tried several possibilties, there are configurations that seem to work, but I still have few red messages displayed by dmesg.

With armbian-openvfd, none of the suggestions (11 to 24) work to activate the LEDs.
Is it because I don't have the correct meson-*.dtb file?
I understood [led screen display control](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/led_screen_display_control.md)
I don't know what settings are needed in the diy.conf file.

Is it possible to display the time on the tvbox by booting from the usb key or do I need to install armbian on the tvbox?

Thank you for reading, hoping to have answers to go further.

**Comment by ophub** [comment]
try s905w

**Comment by okpapt** [comment]
Thanks for your ansewer.

Is it possible to display the time on the led display tvbox by booting from the usb key or do I need to install armbian on the tvbox?

Having tried several possibilties, mixing img and file.dtb having s905 or s905x or p281 in name and  some configurations that seem to work fine, but I still have few red messages displayed by dmesg.
None can light led display.
Maybe I miis some possibilities.

**Comment by okpapt** [comment]
I tested 21 files.conf :
 files.conf with (vfd_gpio_clock | vfd_gpio_dat)  :
- ( '0,75,0' | '0,74,0') or ('0,76,0' | '0,75,0') or ('1,4,0' | '1,3,0')   give an error
- ( '0,64,0' | '0,63,0') give FD6551 or FD628 controller
- ( '0,71,0' | '0,72,0') or ( '0,14,0' | '0,15,0') give FD628 controller
files.conf with vfd_display_type last value = '0x06'  give FD6551 controller

I thing if I have not good_file.img with good_file.dtb, I can't have a led segment on. 
If I can have just one, after I think I can light all segments and give right order.

**Comment by ophub** [comment]
I don't quite understand. You can log in to your armbian normally, the wired network works fine, but the LED screen is not lit?
This device is now an unknown device. If the armbian system can boot normally, please send me the configuration information you are using, and I will record it:
```
cat /boot/uEnv.txt
cat /etc/ophub-release
ls -al /boot/u-boot*
```

LED light test method, see the document: https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/led_screen_display_control.md

**Comment by okpapt** [comment]
Having tried several possibilties, mixing img and file.dtb having s905 or s905x or p281 in name and some configurations that seem to work fine, **but I have few red messages during boot and displayed by dmesg**.

Is it possible test led display by openvfd only booting from usb key ?

**Comment by okpapt** [comment]
let's be careful.

When I said **I discover** in my first post, I think the translation was bad.
I meant I'm trying to put armbian on an android tvbox.

When the x96mini+ box starts, I always get messages in red indicating that there are some errors.
Several **Armbian_24.5.0_amlogic_xxxx_bullseye_5.15.153_server_2024.04.08.img.gz** run armbian with several **meson-xxxx.dtb** files inside x96mini+.
I think that the meson-xxxx.dtb files that I am testing are not really suitable. I opened them, but I don't understand anything that's written inside.

Yes Internet works, I don't know how fast.
I don't know if wifi and bluetooth work and I don't know how to test them.

The LED display does not work at all, how to activate it?
Is it possible to display the time on the tvbox by booting from the usb key or do I need to install armbian on the tvbox?

**I know nothing about linux, android, tvbox.** I read and try to understand.

I can do anything you want for you to add a new box to the list, just tell me what to try in detail.

**Comment by ophub** [comment]
Your question has been answered in the reply above.

**Comment by okpapt** [comment]
Maybe but I do not understand what you mean...
