### ISSUE TITLE
安装桌面插件后无法打开armbian

### ISSUE THREAD

**Issue by qiang-007** [ophub/amlogic-s9xxx-armbian#2228]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [cm311-1 ys]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.100]
 - Release: [ jammy]

**Describe the bug | 问题描述**
打算给ambian安装桌面，通过ambian -software命令安装的，结束后ambian打不开了，重启也不行，路由器里没有它的IP地址。是不是变砖了？？怎么重装啊~~~

**Comment by ophub** [comment]
这个盒子有hdmi输出显示吗？

装桌面不会砖。砖只有在写入错误的主线u-boot时会遇到，这个没有配你也没写，所以没有砖的机会。重新插上USB即可重刷系统。想刷回安卓系统时，从仓库首页点对应的盒子的链接，进入贡献者发布的贴子里，有系统下载链接，顺便也看一下之前大家踩过的坑。
