### ISSUE TITLE
Unable to enable the led on X96 air, kernel 5.4

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#223]
Hardware: X96 air (2+16G, 100Mb)
Armbian info:

> root@armbian:~# cat /etc/ophub-release 
> VERSION_CODEID='debian'
> VERSION_CODENAME='bullseye'
> PACKAGED_DATE='2022-03-06'
> FDTFILE='meson-sm1-x96-air-100.dtb'
> UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
> MAINLINE_UBOOT=''
> ANDROID_UBOOT=''
> MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
> SOC='s905x3'
> KERNEL_VERSION='5.4.188'
> K510='0'

Here are the log when I run armbian-led command and select profile:
<img width="650" alt="image" src="https://user-images.githubusercontent.com/22479095/161531597-f17a6f19-c1d6-49f9-8adf-028e62d149cd.png">

**Comment by ophub** [comment]
Modify uEnv.txt and modify dtb to: `meson-sm1-x96-air.dtb`

**Comment by dinhchinh82** [comment]
> The dtb you choose does not support the use of openvfd, Modify `/boot/uEnv.txt` and modify dtb to: `meson-sm1-x96-air.dtb` `reboot`

does this dtb support x96 air LAN 100mb?

**Comment by ophub** [comment]
This is the renamed dtb. It will be called this in the future. The previous one has been abolished.

**Comment by dinhchinh82** [comment]
> This is the renamed dtb. It will be called this in the future. The previous one has been abolished.

so you mean the content of dtb is same but openvfd only supports the fixed "eson-sm1-x96-air.dtb" file name, right?

**Comment by ophub** [comment]
There is no meson-sm1-x96-air-100.dtb file in the current kernel, it has been renamed meson-sm1-x96-air.dtb
