### ISSUE TITLE
Panther X2 黑豹的网络不能访问的问题

### ISSUE THREAD

**Issue by romeo1978** [ophub/amlogic-s9xxx-armbian#2234]
**Device Information | 设备信息**
 - SOC: [RK3566]
 - Model [Panther X2]

**Armbian Version | 系统版本**
 - Kernel Version: [Linux 6.1.82-ophub]
 - Release: [Jammy/Jellyfish]

**Describe the bug | 问题描述**
最近panther x2遇到一个奇怪的网络问题；
panther x2通过网线连接到家里路由器，几天前突然家里宽带不能上网了，开始以为是光猫或运营商那边出了问题，但经过运营商工程师定位光猫上网正常；用手机或电脑连路由器的wifi信号都有感叹号，无法上网；开始以为是路由器有问题，经过多次重启和反复定位故障依旧，但偶然拔掉pantherx2盒子的网线后发现上网恢复正常，插上pantherx2网线又都不能上网。 

因此基本定位到是pantherx2的问题，拔电重启pantherx2后网络正常，也可以ssh登录进armbian；用nmcli查看网卡、状态、ping等都正常，查看/var/log下syslog等也没发现什么异常。
但过了2天，家里宽度网络又出现不能上网问题，拔pantherx2网线后恢复正常！然后又是重启pantherx2。。。看来问题还是存在的。
持续ping pantherx2有时候会报网络超时错误，如图：
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/8639556/376b8a74-f9f1-4d7f-9889-b9c12e13bde5)
希望高手指点这个问题接下来要如何解决？
对了,pantherx2上安装了docker 和一些镜像，1panel这几个软件，比较简单。

**Comment by firesxp** [comment]
Armbian Version | 系统版本
Kernel Version: [Linux 6.1.78-ophub]
Release: [Jammy]

一模一样，也是这两天出现的

**Comment by romeo1978** [comment]
> Armbian Version | 系统版本 Kernel Version: [Linux 6.1.78-ophub] Release: [Jammy]
> 
> 一模一样，也是这两天出现的

有解决问题思路么？我现在是pantherx2不敢插路由器网线了

**Comment by firesxp** [comment]
拔线重启好了，准备上监控，看看
