### ISSUE TITLE
创维E900V21E有线网卡无法工作

### ISSUE THREAD

**Issue by startpenghubingzhou** [ophub/amlogic-s9xxx-armbian#2237]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]S905L2
 - Model [e.g. HK1]创维E900V21E

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]6.1.84
 - Release: [e.g. jammy/bullseye]noble

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

我的E900V21E有线网卡为S160B1，不管使用哪种S905L2的dtb，都无法正常加载有线网卡，有线网卡虽然显示eth0，但无法使用`nmtui`命令完成网络激活。

![WechatIMG11](https://github.com/ophub/amlogic-s9xxx-armbian/assets/57178266/01920ca8-92b9-4a00-9c92-6b848fdd0732)

这是使用`ip addr`后显示的界面（因为没网，所以没有`ifconfig`，只好使用`ip addr`代替）：

![WechatIMG15](https://github.com/ophub/amlogic-s9xxx-armbian/assets/57178266/de99f96e-a6b6-4414-a0e8-e40108d57604)

这是使用`nmtui`企图激活网络之后的界面：

![WechatIMG13](https://github.com/ophub/amlogic-s9xxx-armbian/assets/57178266/aba508c3-3906-4755-b73b-cedc64a97caf)

我同时也注意到，在我的盒子上`mt7668`无线网卡也是无法工作的状态，不过我尚未尝试[#1701](https://github.com/ophub/amlogic-s9xxx-armbian/issues/1701)中提出的方案。

就目前而言，我只想解决有线网卡方面的问题，有没有什么可行性办法呢？
@ophub

**Comment by startpenghubingzhou** [comment]
目前问题已经解决，通过刷入仓库下提供的`MGV2000-S905L-android4.42-root-qlzy-20180813.img`固件（下载链接），然后重新安装armbian解决问题。目前网卡运行正常，猜测之前的固件bootloader与armbian存在兼容性问题，导致有线网卡irq无法正常工作。

**Comment by Triment** [comment]
> MGV2000-S905L-android4.42-root-qlzy-20180813.img

很棒的工作，这个固件不在了，能提供一下吗

**Comment by startpenghubingzhou** [comment]
> #2127

固件是在的，我刚才还看了一眼。

**Comment by startpenghubingzhou** [comment]
> > MGV2000-S905L-android4.42-root-qlzy-20180813.img
> 
> 很棒的工作，这个固件不在了，能提供一下吗

固件还在，我刚才还看了一眼。
