### ISSUE TITLE
HK1BOX LCD能否显示CPU温度？

### ISSUE THREAD

**Issue by szcare** [ophub/amlogic-s9xxx-armbian#224]
![image](https://user-images.githubusercontent.com/34106940/161542884-12f58dae-2999-4443-bcbf-7d37321b3b6b.png)
HK1BOX LCD上能否交替显示时间和CPU温度，或者单独显示CPU温度？

**Comment by ophub** [comment]
没有温度的接口。
内核功能一共支持11种状态，具体能使用哪个由设备决定，可以参考原安卓TV系统可以显示的图标进行选择。

alarm wifi eth pause play usb apps setup sd hdmi cvbs
