### ISSUE TITLE
linux-headers-6.1.84-spring-plowing

### ISSUE THREAD

**Issue by MR0000001** [ophub/amlogic-s9xxx-armbian#2244]
**Device Information | 设备信息**
 - SOC: S095x
 - Model M16

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.84-spring-plowing
 - Release: bookworm

I need the headers to compile usb wifi realtek drivers.
Thanks

**Comment by ophub** [comment]
`cd /usr/src`

**Comment by MR0000001** [comment]
Thanks for the reply, how should i compile them to get .deb??

**Comment by ophub** [comment]
no .deb file

**Comment by p-Nugroho** [comment]
no linux headers then?
