### ISSUE TITLE
unt02a使用24.5.0_amlogic_s905l3_jammy_6.1.84可以写入EMMC但是没有有线网，之前用的别的版本有线网可以使用

### ISSUE THREAD

**Issue by NBL1330** [ophub/amlogic-s9xxx-armbian#2245]
**Device Information | 设备信息**
 - SOC: [S905L3]
 - Model [UNT402A]

**Armbian Version | 系统版本**
 - Release: [Armbian_24.5.0_amlogic_s905l3_jammy_6.1.84_server_2024.04.08.img]

**Describe the bug | 问题描述**
你好，之前我的unt402a九联有wifi版用Armbian_23.05.0_amlogic_s905l3-unt400g1_jammy_6.1.27_server_2023.05.09.img，使用meson-gxl-s905l3b-m302a.dtb文件wifi不能用但是有线网可以，不能写入EMMC，写入EMMC没有报错但是卡在第一步不动。这两天换了Armbian_24.5.0_amlogic_s905l3_jammy_6.1.84_server_2024.04.08.img，也使用meson-gxl-s905l3b-m302a.dtb文件有线网和WiFi都不可以用，但是可以写入EMMC。是不是既然23.05.0_amlogic_s905l3-unt400g1_jammy_6.1.27可以正常驱动有线网那24.5.0_amlogic_s905l3_jammy_6.1.84理论上也可以做到呢，另外我之前用23.05.0_amlogic_s905l3-unt400g1_jammy_6.1.27有线网可以但是最近新版24.5.0_amlogic_s905l3-unt400g1_jammy_6.1.84反而也不可以使用有线网了不知道为什么。

**Comment by ophub** [comment]
armbian-install -m yes

**Comment by NBL1330** [comment]
> armbian-install -m yes

感谢，今天我用23.05.0_amlogic_s905l3-unt400g1_jammy_6.1.27试了一下这个命令还是不行，虽然ssh端没有报错但是我连上显示器发现是报了io错的，我跟着说明调低频率还是不行，不知道操作的对不对，不过写不进去就算了。我用新版Armbian_24.5.0_amlogic_s905l3_jammy_6.1.84_server_2024.04.08.img能写入但是有线网无法驱动，之前以前有个提问说是复制u-boot.ext，没想到旧版有这个6.1.84反而没有，我复制了这两个文件有线网卡问题已经解决了。非常感谢。
