### ISSUE TITLE
希望能够支持 海信 hs530r

### ISSUE THREAD

**Issue by hunter24099** [ophub/amlogic-s9xxx-armbian#2246]
**Device Information | 设备信息**
 - SOC: [rk3399]
 - Model [海信 hs530r]
 - 4g 运存 
 - 16Gemmc
 - fn-link 6222d-ubb wifi
 - rtl8211
 - usb 2.0 *2
 - usb 3.0 *2
 - hdmi *1

uboot、dtb、以及好用的Armbian_23.08.0-trunk_Hisense-hs530r_jammy_edge_6.5.5_xfce_desktop
链接：https://pan.baidu.com/s/1MNEwM_sln754olAontfrYQ 
提取码：xfjd

感谢老大！
![1](https://github.com/ophub/amlogic-s9xxx-openwrt/assets/76616820/4d4eba79-9fc7-4070-8689-91db0ba38ac2)

**Comment by ophub** [comment]
根据你提供的资料，我添加了，正在Actions里打包，10分钟后你到releases里下载测试下。

**Comment by hunter24099** [comment]
反馈一下，一切正常！！
![ophub_bookworm](https://github.com/ophub/amlogic-s9xxx-armbian/assets/76616820/599615ab-5380-43df-ab83-72badd981292)

**Comment by ophub** [comment]
好的，我添加到列表里。
