### ISSUE TITLE
TB_LS339 硬盘盒插USB3.0上只有10Mb/s的速度

### ISSUE THREAD

**Issue by huan987** [ophub/amlogic-s9xxx-armbian#2247]
**Device Information | 设备信息**
 - SOC: RK3399
 - Model: TB_LS339

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.84
 - Release: Armbian_noble_save_2024.04

**Describe the bug | 问题描述**
我把usb3.0的硬盘盒插到板子上通过‘time dd’指令来测试读写速度，结果非常的慢，通过‘lsusb’查看usb信息，返回如下信息：
SuperSpeed USB Device Capability:
  wSpeedsSupported   0x000e
    Device can operate at Full Speed (12Mbps)
    Device can operate at High Speed (480Mbps)
    Device can operate at SuperSpeed (5Gbps)
  Lowest fully-functional device speed is Full Speed (12Mbps)

**Comment by wenzhongyi** [comment]
刷了最新版的s905l3a，发现上传文件到盒子里超慢 下载文件也是

**Comment by huan987** [comment]
是硬盘格式的问题，NTFS就会这样，刷成exFAT就好了
