### ISSUE TITLE
请求添加适配亮钻K4-RK3399主板

### ISSUE THREAD

**Issue by qq123000qq** [ophub/amlogic-s9xxx-armbian#2248]
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [K4]
 - 2G
 - 32Gemmc
 - Wifi: AP6212
 - LAN: MotorComm YT8511C
 - USB: FE1.1 USB 2.0 HUB
 - 原系统7.1
 - 
 
![K4](https://github.com/ophub/amlogic-s9xxx-armbian/assets/164750782/5046713f-9d6f-434e-bce4-d4096df82dad)
![微信图片_20240418211824](https://github.com/ophub/amlogic-s9xxx-armbian/assets/164750782/fd164310-3a60-4f4b-b3ea-1757285b925b)
![微信截图_20240418212037](https://github.com/ophub/amlogic-s9xxx-armbian/assets/164750782/ff2ed496-1bfb-4035-a6a7-32196cfefa7d)

[rk-kernel.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/15025531/rk-kernel.dtb.zip)
[boot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/15025535/boot.zip)

**Comment by ophub** [comment]
armbian/openwrt使用的是主线内核，安卓的这个用不了。你知道哪里有u-boot和dts的源码没？

**Comment by qq123000qq** [comment]
抱歉，我也没有源码，目前我手上有7.1和9.0的固件，您看下这些用的上吗？
![Uploading IMG_20240418_233450.jpg…]()

**Comment by qq123000qq** [comment]
O大，我获取了一些资料和固件，想让你帮忙看看，资料比较多，以什么方法发给你看一下，具体需要哪些东西？

**Comment by qq123000qq** [comment]
![IMG_20240419_144045](https://github.com/ophub/amlogic-s9xxx-armbian/assets/164750782/ccd6e007-3cfa-4844-8d72-b6bf99c055f1)

**Comment by qq123000qq** [comment]
![IMG_20240419_144710](https://github.com/ophub/amlogic-s9xxx-armbian/assets/164750782/c168058e-a30f-4a7c-b31d-11a4a078ff8b)

**Comment by ophub** [comment]
百度网盘有的话，分享一下

**Comment by qq123000qq** [comment]
通过百度网盘分享的文件：11.K4C4F…
链接:https://pan.baidu.com/s/1TON3j8k07s8BsvYisNFbJQ 
提取码:ekvu
复制这段内容打开「百度网盘APP 即可获取」

**Comment by qq123000qq** [comment]
测试发现以上linux及资料中的安卓7、8、9都无法驱动有线网络，可能存在网卡不一致的情况。

**Comment by weixr18** [comment]
> 测试发现以上linux及资料中的安卓7、8、9都无法驱动有线网络，可能存在网卡不一致的情况。刷回自带系统7.1，有线网络正常。

Hi你好！想问一下这块板子MASKROM刷机的引脚在哪里呢？我刚拿了一块准备刷Armbian，非常感谢

**Comment by garryforreg** [comment]
> > 测试发现以上linux及资料中的安卓7、8、9都无法驱动有线网络，可能存在网卡不一致的情况。刷回自带系统7.1，有线网络正常。
> 
> Hi你好！想问一下这块板子MASKROM刷机的引脚在哪里呢？我刚拿了一块准备刷Armbian，非常感谢

见楼主图上的烧录键，先用烧录键进入烧录模式，再通过刷机工具界面可以一键切到MASKROM.|

这块板子我已经成功在最新的armbian系统和内核下适配了HDMI显示和有线网卡，现在还有无线网卡问题没解决。这块板子不同的时期换了好多次无线芯片，连它自带的系统都无法驱动无线网卡。

**Comment by bluesky755** [comment]
> 通过百度网盘分享的文件：11.K4C4F… 链接:[https://pan.baidu.com/s/1TON3j8k07s8BsvYisNFbJQ ](https://pan.baidu.com/s/1TON3j8k07s8BsvYisNFbJQ%C2%A0) 提取码:ekvu 复制这段内容打开「百度网盘APP 即可获取」

@qq123000qq ，这个还可以再分享一次吗，我也有块k4板子，找linux sdk资源很久了，感谢
