### ISSUE TITLE
关于旧版6.1.82下载

### ISSUE THREAD

**Issue by LIUBANGJIAN** [ophub/amlogic-s9xxx-armbian#2249]
大佬，你好请问我要下载6.1.82内核版本的img，要在什么地方下载呢？

**Comment by ophub** [comment]
没有了

**Comment by LIUBANGJIAN** [comment]
驱动只支持6.1.82这有其他办法解决吗？

**Comment by ophub** [comment]
支持82，就应该支持后续版本。任意内核的固件你可以更新内核到指定版本。

**Comment by LIUBANGJIAN** [comment]
卖家提供的ko驱动，已经绝版了，请问如何更换指定的内核版本呢？
我看o大这里https://github.com/ophub/kernel/releases/tag/kernel_stable有现成内核，要怎么操作呢？请指导一下。

**Comment by ophub** [comment]
仓库首页看更新内核的方法

**Comment by LIUBANGJIAN** [comment]
好的，感谢。

**Comment by gametta** [comment]
我这里保存的有晶晨的芯片近两年的版本。

**Comment by LIUBANGJIAN** [comment]
> 我这里保存的有晶晨的芯片近两年的版本。

什么地方？

**Comment by LIUBANGJIAN** [comment]
大佬，6.1.82内核文件也没有了。要怎么切换换6.1.82的内核呢？

> 卖家提供的ko驱动，已经绝版了，请问如何更换指定的内核版本呢？ 我看o大这里[https://github.com/ophub/kernel/releases/tag/kernel_stable有现成内核，要怎么操作呢？请指导一下。](https://github.com/ophub/kernel/releases/tag/kernel_stable%E6%9C%89%E7%8E%B0%E6%88%90%E5%86%85%E6%A0%B8%EF%BC%8C%E8%A6%81%E6%80%8E%E4%B9%88%E6%93%8D%E4%BD%9C%E5%91%A2%EF%BC%9F%E8%AF%B7%E6%8C%87%E5%AF%BC%E4%B8%80%E4%B8%8B%E3%80%82)
