### ISSUE TITLE
固化ko驱动到内核

### ISSUE THREAD

**Issue by LIUBANGJIAN** [ophub/amlogic-s9xxx-armbian#2251]
**Device Information | 设备信息**
我家云

**Armbian Version | 系统版本**
Armbian_24.5.0_rockchip_renegade-rk3328_noble_6.1.82_server_2024.03.16

**Describe the bug | 问题描述**
有对应该内核版本的ko驱动文件，每次开机都输入sudo modprobe dvb-usb、sudo insmod /root/dvb-usb-smit.ko。虽然可以在rc.local里配置开机启动，但是我想把驱动固化到内核里面，请问有办法操作的吗？

**Comment by ophub** [comment]
放内核目录。源码放内核源文件里编译内核的时候=y

**Comment by LIUBANGJIAN** [comment]
没有源码，只有商家提供的ko文件。

**Comment by 13584452567** [comment]
那没有办法。ko就是作为模块被编译的，没有源码只有二进制文件没法把它嵌入内核。

**Comment by LIUBANGJIAN** [comment]
好的

**Comment by whmzsu** [comment]
我记得可以写到modprobe的配置文件里面，启动的时候加载对应模块

**Comment by LIUBANGJIAN** [comment]
> 我记得可以写到modprobe的配置文件里面，启动的时候加载对应模块

是可以的，或者有没有办法把ko文件固化到img固件里，再加上启动加载的命令，做到这个img固件像是自带该设备驱动一样？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh


这是个独立添加的自定义脚本，可以集中在这添加个性化命令

**Comment by LIUBANGJIAN** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh
> 
> 这是个独立添加的自定义脚本，可以集中在这添加个性化命令

o大，请问ko的驱动文件，怎么放进去呢，浪费再编译成img固件呢？

**Comment by 13584452567** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh
> > 
> > 这是个独立添加的自定义脚本，可以集中在这添加个性化命令
> 
> o大，请问ko的驱动文件，怎么放进去呢，浪费再编译成img固件呢？

armbian-files/different-files目录下新建编译选项作为名称的文件夹，再在该文件夹内新建rootfs文件夹，在rootfs文件夹内按照根文件系统目录来添加你的驱动文件，然后再在上文的sh内添加驱动加载命令。这样actions就会自动处理打包了。

**Comment by LIUBANGJIAN** [comment]
> > > https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh
> > > 这是个独立添加的自定义脚本，可以集中在这添加个性化命令
> > 
> > 
> > o大，请问ko的驱动文件，怎么放进去呢，浪费再编译成img固件呢？
> 
> armbian-files/different-files目录下新建编译选项作为名称的文件夹，再在该文件夹内新建rootfs文件夹，在rootfs文件夹内按照根文件系统目录来添加你的驱动文件，然后再在上文的sh内添加驱动加载命令。这样actions就会自动处理打包了。

好的，谢谢，我试试。

**Comment by ophub** [comment]
楼上的135赵兄的方法挺好，个性化添加自己盒子对应board的文件
