### ISSUE TITLE
添加第三方软件，安装软件后，upgrade报错。

### ISSUE THREAD

**Issue by LIUBANGJIAN** [ophub/amlogic-s9xxx-armbian#2252]
**Device Information | 设备信息**
我家云

**Armbian Version | 系统版本**
Linux armbian 6.1.82-ophub #1 SMP Fri Mar 15 22:39:04 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux

**Describe the bug | 问题描述**
1、切换阿里源
2、添加sudo add-apt-repository ppa:mamarley/tvheadend-git
3、update和upgrade后，安装apt install tvheadend
4、tvheadend
5、再次update和upgrade后报错
root@armbian:/etc/apt/sources.list.d# apt-get update
Hit:1 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports noble InRelease
Hit:2 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports noble-security InRelease
Hit:3 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports noble-updates InRelease
Hit:4 http://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports noble-backports InRelease
Hit:5 http://mirrors.ustc.edu.cn/armbian noble InRelease
Reading package lists... Done
N: Ignoring file 'mamarley-ubuntu-tvheadend-git-noble.sources.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
root@armbian:/etc/apt/sources.list.d# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libpam-systemd : Depends: systemd (= 255.4-1ubuntu7) but 255.2-3ubuntu2 is installed
 systemd : Depends: libsystemd-shared (= 255.2-3ubuntu2) but 255.4-1ubuntu7 is installed
           Depends: libsystemd0 (= 255.2-3ubuntu2) but 255.4-1ubuntu7 is installed
 systemd-resolved : Depends: systemd (= 255.4-1ubuntu7) but 255.2-3ubuntu2 is installed
 systemd-sysv : Depends: systemd (= 255.4-1ubuntu7) but 255.2-3ubuntu2 is installed
 udev : Depends: libudev1 (= 255.2-3ubuntu2) but 255.4-1ubuntu7 is installed
N: Ignoring file 'mamarley-ubuntu-tvheadend-git-noble.sources.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

6、使用apt --fix-broken install报错
dpkg: error processing archive /var/cache/apt/archives/udev_255.4-1ubuntu7_arm64.deb (--unpack):
 new udev package pre-installation script subprocess returned error exit status 1
Setting file flags is only supported on regular files and directories, cannot set on '/var/log/journal'.
Setting file flags is only supported on regular files and directories, cannot set on '/var/log/journal'.
Errors were encountered while processing:
 /var/cache/apt/archives/systemd_255.4-1ubuntu7_arm64.deb
 /var/cache/apt/archives/udev_255.4-1ubuntu7_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

7、请大佬们指点一下。

**Comment by ophub** [comment]
删除了你添加的无效的第三方源。

系统常用操作可以问gpt，armbian使用方法和ubuntu/debian完全一样

**Comment by admin1155** [comment]
> 删除了你添加的无效的第三方源。
> 
> 系统常用操作可以问gpt，armbian使用方法和ubuntu/debian完全一样

你好，请问APT源需要换哪个版本的？我发现armbian源更换后update依旧使用默认源

**Comment by admin1155** [comment]
> 删除了你添加的无效的第三方源。
> 
> 系统常用操作可以问gpt，armbian使用方法和ubuntu/debian完全一样

我的显示版本号为noble但是我并未从清华等软件源发现有版本号为noble的

**Comment by ophub** [comment]
https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/

怎么会没有呢，使用`armbian-apt`换源。

**Comment by LIUBANGJIAN** [comment]
> 当前尽量不要使用noble版本，还没正式发布呢
> 
> 麻烦贴一下你的/etc/apt/source.list文件以及/etc/apt/source.list.d/目录下的全部文件内容
> 
> `N: Ignoring file 'mamarley-ubuntu-tvheadend-git-noble.sources.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension` 这个是说你的文件扩展名不对，所以忽略掉了这个源
> 
> ```
> root@armbian:/etc/apt/sources.list.d# apt-get upgrade
> Reading package lists... Done
> Building dependency tree... Done
> Reading state information... Done
> You might want to run 'apt --fix-broken install' to correct these.
> The following packages have unmet dependencies:
> libpam-systemd : Depends: systemd (= 255.4-1ubuntu7) but 255.2-3ubuntu2 is installed
> systemd : Depends: libsystemd-shared (= 255.2-3ubuntu2) but 255.4-1ubuntu7 is installed
> Depends: libsystemd0 (= 255.2-3ubuntu2) but 255.4-1ubuntu7 is installed
> systemd-resolved : Depends: systemd (= 255.4-1ubuntu7) but 255.2-3ubuntu2 is installed
> systemd-sysv : Depends: systemd (= 255.4-1ubuntu7) but 255.2-3ubuntu2 is installed
> udev : Depends: libudev1 (= 255.2-3ubuntu2) but 255.4-1ubuntu7 is installed
> N: Ignoring file 'mamarley-ubuntu-tvheadend-git-noble.sources.1' in directory '/etc/apt/sources.list.d/' as it has an invalid filename extension
> E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
> ```
> 
> 依赖地狱了，会搞的话就一个个单独下强行装去fix，不会就直接重刷jammy版吧




root@N1:/etc/apt# ll
total 44
drwxr-xr-x   8 root root  4096 Apr 12 09:54 ./
drwxr-xr-x 105 root root 12288 Apr 22 15:11 ../
drwxr-xr-x   2 root root  4096 Apr 12 09:29 apt.conf.d/
drwxr-xr-x   2 root root  4096 Apr 12 09:29 auth.conf.d/
drwxr-xr-x   2 root root  4096 Apr 12 09:29 keyrings/
drwxr-xr-x   2 root root  4096 Apr 12 09:29 preferences.d/
-rw-r--r--   1 root root   761 Apr 19 10:18 sources.list
drwxr-xr-x   2 root root  4096 Apr 19 10:18 sources.list.d/
drwxr-xr-x   2 root root  4096 Apr 12 09:29 trusted.gpg.d/
root@N1:/etc/apt# cat sources.list
deb http://mirrors.aliyun.com/ubuntu-ports noble main restricted universe multiverse
# deb-src http://mirrors.aliyun.com/ubuntu-ports noble main restricted universe multiverse

deb http://mirrors.aliyun.com/ubuntu-ports noble-security main restricted universe multiverse
# deb-src http://mirrors.aliyun.com/ubuntu-ports noble-security main restricted universe multiverse

deb http://mirrors.aliyun.com/ubuntu-ports noble-updates main restricted universe multiverse
# deb-src http://mirrors.aliyun.com/ubuntu-ports noble-updates main restricted universe multiverse

deb http://mirrors.aliyun.com/ubuntu-ports noble-backports main restricted universe multiverse
# deb-src http://mirrors.aliyun.com/ubuntu-ports noble-backports main restricted universe multiverse


root@N1:/etc/apt# cd sources.list.d/
root@N1:/etc/apt/sources.list.d# ll
total 20
drwxr-xr-x 2 root root 4096 Apr 19 10:18 ./
drwxr-xr-x 8 root root 4096 Apr 12 09:54 ../
-rw-rw-r-- 1 root root  108 Apr 19 10:18 armbian.list
-rw-r--r-- 1 root root  808 Apr 19 10:18 mamarley-ubuntu-tvheadend-git-noble.sources
-rw-r--r-- 1 root root  645 Apr 12 09:54 sources.list.bak
root@N1:/etc/apt/sources.list.d# cat mamarley-ubuntu-tvheadend-git-noble.sources 
Types: deb
URIs: https://ppa.launchpadcontent.net/mamarley/tvheadend-git/ubuntu/
Suites: noble
Components: main
Signed-By: 
 -----BEGIN PGP PUBLIC KEY BLOCK-----
 .
 mI0ESXjr0gEEAOCUH3ClvaUI5v3UNKDQKIi9ES+K9VpodLo4MDf5rNcmkOeuEI8s
 L6SDfYoziMw9stuSfDg5S4WyGnnIeoyL4l42KfLu6T6yFck14r7BCcCuPqjNadmc
 JZOJ8ynhTkPQz6VqcojMCqnB9g7a1faDNbBA5SEmSa/cQVh7ZR87EqAbABEBAAG0
 IExhdW5jaHBhZCBQUEEgZm9yIE1pY2hhZWwgTWFybGV5iLYEEwECACAFAkl469IC
 GwMGCwkIBwMCBBUCCAMEFgIDAQIeAQIXgAAKCRAm9O+EQGGLZgDjA/9evxBW0ZED
 SgClCfgo6FUiO/gJQiBMllD38gIzOHm18ieSaHpUw72mZCVsElZv1qGl9BidVOu0
 7G7q83gwvDT46Qyq6M7Z6dO+iEtiUOcfQZIuljFVzTFMmk7pC62RFDWGo/r4oOJ0
 zPWNQwgdqdbNKIYPak2B+9xEm1jGHyXeV4hGBBARAgAGBQJJ82OtAAoJEEyYywXG
 zl/ed0UAoLMzByTEmFtc8AoXtjyJ0lHVhXi3AJ9RHJOEXJI3SvompZJNA8l2PnaK
 9g==
 =jLpR
 -----END PGP PUBLIC KEY BLOCK-----
root@N1:/etc/apt/sources.list.d# cat armbian.list 
deb [signed-by=/usr/share/keyrings/armbian.gpg] http://apt.armbian.com noble main noble-utils noble-desktop
root@N1:/etc/apt/sources.list.d#

**Comment by LIUBANGJIAN** [comment]
删除第三方源，没有作用。
root@N1:/etc/apt/sources.list.d# ll
total 20
drwxr-xr-x 2 root root 4096 Apr 19 10:18 ./
drwxr-xr-x 8 root root 4096 Apr 12 09:54 ../
-rw-rw-r-- 1 root root  108 Apr 19 10:18 armbian.list
-rw-r--r-- 1 root root  808 Apr 19 10:18 mamarley-ubuntu-tvheadend-git-noble.sources
-rw-r--r-- 1 root root  645 Apr 12 09:54 sources.list.bak
root@N1:/etc/apt/sources.list.d# rm mamarley-ubuntu-tvheadend-git-noble.sources 
root@N1:/etc/apt/sources.list.d# 
root@N1:/etc/apt/sources.list.d# 
root@N1:/etc/apt/sources.list.d# apt-get update
Hit:1 http://mirrors.aliyun.com/ubuntu-ports noble InRelease
Hit:2 http://mirrors.aliyun.com/ubuntu-ports noble-security InRelease
Hit:4 http://mirrors.aliyun.com/ubuntu-ports noble-updates InRelease
Hit:5 http://mirrors.aliyun.com/ubuntu-ports noble-backports InRelease
Hit:3 http://mirrors.ustc.edu.cn/armbian noble InRelease
Reading package lists... Done
root@N1:/etc/apt/sources.list.d# apt-get upgrade
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 libpam-systemd : Depends: systemd (= 255.4-1ubuntu8) but 255.4-1ubuntu7 is installed
 systemd : Depends: libsystemd-shared (= 255.4-1ubuntu7) but 255.4-1ubuntu8 is installed
           Depends: libsystemd0 (= 255.4-1ubuntu7) but 255.4-1ubuntu8 is installed
 systemd-resolved : Depends: systemd (= 255.4-1ubuntu8) but 255.4-1ubuntu7 is installed
 systemd-sysv : Depends: systemd (= 255.4-1ubuntu8) but 255.4-1ubuntu7 is installed
 udev : Depends: libudev1 (= 255.4-1ubuntu7) but 255.4-1ubuntu8 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
root@N1:/etc/apt/sources.list.d#

**Comment by ophub** [comment]
`apt --fix-broken install`

**Comment by ophub** [comment]
先别用noble，这个还是测试版。
换另外3个lts的，jammy/bullseye/bookworm是正式版。

**Comment by ophub** [comment]
最新版解决了这个问题了
