### ISSUE TITLE
请问6.6内核的安装包去哪里下载

### ISSUE THREAD

**Issue by emgxdxd** [ophub/amlogic-s9xxx-armbian#2254]
设备是e900v22e 安卓4.4
之前用6.6内核的时候网卡可以识别，没保留安装包。现在重新写了个6.1的不识别网卡了

**Comment by ophub** [comment]
fork仓库，编译6.6的固件

**Comment by emgxdxd** [comment]
> fork仓库，编译6.6的固件

感谢

**Comment by LIUBANGJIAN** [comment]
> fork仓库，编译6.6的固件
大佬，我要想指定6.1.82版本的内核这个怎么选择呢?手动直接在work文档里面加吗？

**Comment by LIUBANGJIAN** [comment]
我在build-armbian.yml文件里添加了6.1.82的选项，但是编译失败，
     armbian_kernel:
        description: "Select kernel version."
        required: false
        default: "6.1.y"
        type: choice
        options:
          - 5.4.y
          - 5.10.y
          - 5.15.y
          - 6.1.y
          - 6.1.82
          - 6.6.y        
          - 6.1.y_6.6.y
          - 6.1.y_5.15.y
          - 5.4.y_5.10.y


报错信息
-rw-r--r-- 1 root   root   317368956 Apr 22 00:04 Armbian_24.5.0-jammy_rootfs.tar.gz
-rw-r--r-- 1 runner docker       101 Apr 22 00:05 Armbian_24.5.0-jammy_rootfs.tar.gz.sha
-rw-rw-r-- 1 runner docker 976687810 Apr 22 00:03 Armbian_24.5.0-trunk_6.6.28.img.gz
-rw-r--r-- 1 runner docker       101 Apr 22 00:05 Armbian_24.5.0-trunk_6.6.28.img.gz.sha
Check the Armbian file format...
Selected Armbian file: [ Armbian_24.5.0-trunk_6.6.28.img.gz ]
Armbian file: 
-rw-rw-r-- 1 runner docker 2566914048 Apr 22 00:03 Armbian_24.5.0-trunk_6.6.28.img
Check the armbian file name (-trunk_)...
The armbian file name is correct.
Start to rebuild armbian...
[ STEPS ] Welcome to Rebuild Armbian!
[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x86_64 ] 
[ STEPS ] Start Initializing Variables...
[ INFO ] The kernel tags list: [ 6.x.y h6 rk3588 rk35xx stable specific ]
[ STEPS ] Start searching for Armbian file...
[ INFO ] Armbian rebuild file: [ Armbian_24.5.0-trunk_6.6.28.img ], Version: [ 24.5.0 ]
[ STEPS ] Start downloading dependency files...
[ INFO ] u-boot download completed.
[ INFO ] firmware download completed.
[ STEPS ] Start downloading the kernel files...
[ INFO ] (1.1) [ 6.x.y - 6.6.y ] Kernel download from [ https://github.com/ophub/kernel/releases/download/kernel_stable/6.6.y.tar.gz ]
curl: (22) The requested URL returned error: 404
 [💔] Failed to download the kernel files from the server.
Error: Process completed with exit code 1.

**Comment by ophub** [comment]
~/build-armbian/armbian-files/common-files/etc/model_database.conf
`KERNEL_TAGS`改`stable`

build-armbian.yml 的 armbian_kernel 里添加个 6.1.82，
auto_kernel 不选择（false）

**Comment by LIUBANGJIAN** [comment]
> ~/build-armbian/armbian-files/common-files/etc/model_database.conf `KERNEL_TAGS`改`stable`
> 
> build-armbian.yml 的 armbian_kernel 里添加个 6.1.82， auto_kernel 不选择（false）

改了后，还是同样的报错

**Comment by LIUBANGJIAN** [comment]
> KERNEL_TAGS

大佬，“~/build-armbian/armbian-files/common-files/etc/model_database.conf KERNEL_TAGS改stable", 是什么位置的KERNEL_TAGS？

**Comment by ophub** [comment]
![Snip20240423_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/7e354151-d6de-45c2-8e93-b907c6e67160)

**Comment by ophub** [comment]
model_database.conf是基础，设置了允许使用的内核范围。
yml流程控制文件是提供了参数选择，内核版本和是否自动选择最新。


不过我奇怪你为啥死磕这个6.1.82呢，更新的版本不是更好吗？而且内核是可以自由切换更新的，任意内核版本的固件都可以通过`armbian-update -k 6.1.82`更新到指定内核版本。

**Comment by LIUBANGJIAN** [comment]
有点懂了，多谢大佬。因为卖家只提供了6.1.82版本的ko驱动，其他内核用不了。他不提供其他内核的ko文件，更加不提供驱动源码。
例如，我要添加这开源项目（https://github.com/tvheadend/tvheadend）编译到固件里，有相应的接口吗？如果没有要怎么操作呢？
