### ISSUE TITLE
[ NOTE ] The [ xiaobao ] device cannot use [ stable/6.6.28 ] kernel, skip?xiaobao不能编译6.6内核的系统了吗？

### ISSUE THREAD

**Issue by Lemon1151** [ophub/amlogic-s9xxx-armbian#2256]
[ NOTE ] The [ xiaobao ] device cannot use [ stable/6.6.28 ] kernel, skip?
xiaobao不能编译6.6内核的系统了吗？

**Comment by Mango1151** [comment]
![657894](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/a766d544-b854-4a2c-8d92-3ece895eb627)
![657894](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/3d8497ea-9920-4926-9988-e3b035b18ba8)

**Comment by Mango1151** [comment]
6.x.y不能用SATA应该是第一次编译打包出了问题，创建一个空白boot和rootfs分区的img镜像，然后把6.x.y不能用SATA的镜像里的boot和rootfs复制到空白img镜像，然后烧录到存储卡里可以正常开机也可以用SATA，也能update

**Comment by ophub** [comment]
能用6.1.y的设备，应该都可以使用6.6.y，但是github的服务器空间不够用，我在model.conf里设置的减少了一点编译量

**Comment by Mango1151** [comment]
> 能用6.1.y的设备，应该都可以使用6.6.y，但是github的服务器空间不够用，我在model.conf里设置的减少了一点编译量

6.1.y也提示这个，小宝不能使用6.1.y的内核

**Comment by ophub** [comment]
你通过更新内核测试确定能用的话，可以在model.conf里修改适用内核，如stable，我没有这个设备，之前有人反馈说5.10.y可以使用。你测试下哪个能用，我改下。
