### ISSUE TITLE
安装在 cm311-1a 的emmc 上的 Armbian_24.5.0_amlogic_s905l3a_jammy_6.1.84_server_2024.04.08  无法启动

### ISSUE THREAD

**Issue by hanguofu** [ophub/amlogic-s9xxx-armbian#2257]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model CM311-1A

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.84
 - Release: Armbian_24.5.0_amlogic_s905l3a_jammy_6.1.84_server_2024.04.08

**Describe the bug | 问题描述**
我有一个带有 WIFI 芯片 uwe5621ds 的 CM311-1A （ 确认主控芯片是 s905l3a ) ， 此前在 该盒子上是能正常使用U 盘（ 也是刷了这个OS ) 启动的，于是我就想把  Armbian  安装 到 盒子的EMMC 上，结果第一次就无法启动了。不知道是什么原因？

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
最后几句的内核启动信息： 
[    5.846383] usb 1-2: new high-speed USB device number 2 using xhci-hcd
[    6.001576] usb 1-2: New USB device found, idVendor=0951, idProduct=1666, bcdDevice= 2.00
[    6.007297] usb 1-2: New USB device strings: Mfr=2, Product=3, SerialNumber=4
[    6.014373] usb 1-2: Product: DataTraveler 3.0
[    6.018767] usb 1-2: Manufacturer: Kingston
[    6.022907] usb 1-2: SerialNumber: 20CF30E1189017807C50003B
[    6.031019] usb-storage 1-2:1.0: USB Mass Storage device detected
[    6.034775] scsi host0: usb-storage 1-2:1.0
[    7.071159] scsi 0:0:0:0: Direct-Access     Kingston DataTraveler 3.0 0000 PQ: 0 ANSI: 4
[    7.078206] sd 0:0:0:0: [sda] 60538881 512-byte logical blocks: (31.0 GB/28.9 GiB)
[    7.084775] sd 0:0:0:0: [sda] Write Protect is off
[    7.089249] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[    7.102101]  sda: sda1 sda2
[    7.105256] sd 0:0:0:0: [sda] Attached SCSI removable disk
[   14.304116] platform sdio-pwrseq: deferred probe pending
[   14.307502] platform wifi32k: deferred probe pending
[  263.710483] random: crng init done

===================================
顺便趁此机会感谢 ophub ,  unifreq 等各位大神的无私贡献~

**Comment by ophub** [comment]
`admbian-install -m yes`
