### ISSUE TITLE
H96 Max X3

### ISSUE THREAD

**Issue by PetrovicGoran** [ophub/amlogic-s9xxx-armbian#2259]
**Device Information | 设备信息**
 - SOC: Amlogic S905X3
 - Model H96 Max X3
 - RAM: 4GB DDR3
 - ROM: 32GB eMMC
 - Built-in WiFi: 802.1.1 a/b/g/n, 2.4G+5G WIFI
 - Ethernet: 10 / 100 / 1000M
 - BT: 4.0
 - OS: Android 9.0

Hello,

I tried booting/installing Armbian on my H96 Max X3 android TV box following a tutorial posted by [@833MOL3](https://github.com/833M0L3/H96MaxX3). I tried installing/booting Armbian on my TV box using the following images:

- [Armbian_24.5.0_amlogic_s905x3_noble_5.15.153_server_2024.04.08.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.04/Armbian_24.5.0_amlogic_s905x3_noble_5.15.153_server_2024.04.08.img.gz)
- [Armbian_24.5.0_amlogic_s905x3_noble_5.15.156_server_2024.04.20.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.04/Armbian_24.5.0_amlogic_s905x3_noble_5.15.156_server_2024.04.20.img.gz)
- [Armbian_24.5.0_amlogic_s905x3_noble_6.1.84_server_2024.04.08.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.04/Armbian_24.5.0_amlogic_s905x3_noble_6.1.84_server_2024.04.08.img.gz) 
- [Armbian_24.5.0_amlogic_s905x3_noble_6.1.87_server_2024.04.20.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.04/Armbian_24.5.0_amlogic_s905x3_noble_6.1.87_server_2024.04.20.img.gz)

After downloading the image, I created a bootable SD card (I tried creating it with Balena Etcher and Rufus, both on Windows and Ubuntu OS), copied `u-boot-x96maxplus.bin` to `u-boot.ext` (I have also tried copying `u-boot-x96max.bin`, `u-boot-s905x3.bin` and `u-boot-sei610.bin`) + tried copying selected file to `u-boot.sd` and `u-boot.usb`. I also edited `uEnv.txt` file and set `FDT` parameter to one of the following values at a time: 
- `meson-sm1-h96-max-x3.dtb`
- `meson-sm1-h96-max-x3-oc.dtb`
- `meson-sm1-h96-max.dtb`
- `meson-sm1-sei610.dtb`
- and all 8 X96 max plus dtb files

However, whichever combination I used, I would never be able to boot into Armbian. I have used "toothpick" method (plugged in SD card, pressed reset button inside AV port, and kept pressing it while plugging in power for 1-15 seconds). The result was always the same. TV box would display stock boot image with TV box's logo, it would be displayed for a few seconds and then the TV box would restart. The process of restarting and displaying TV box stock image would continue infinitely until TV box's power would get unplugged.

My TV Box is using stock Android firmware. When I unplugged SD card from TV box, it would boot to Android OS.

Any help would be kindly appreciated.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents

12.4

**Comment by PetrovicGoran** [comment]
@ophub unfortunately, using adb didn't solve the problem. TV box still infinitely restarts, just like as described in my question.

**Comment by bigboo3000** [comment]
I had the same problem,
I downgraded the internal firmware to the 20220516 version with amlogic burning tool, the toothpick method then worked to install armbian
https://drive.google.com/drive/folders/1Rn7uFZ3SuR9OhMPrFkYMKU4sV1MXcBej

**Comment by bigboo3000** [comment]
I wrote a recent official armbian community image on a usb drive, it now boots from USB but I didn't try to write/install armbian to internal emmc, so android is still there.

**Comment by ophub** [comment]
Thanks for sharing, I have saved a copy of the Android system for h96max-x3

https://github.com/ophub/kernel/releases/tag/tools

**Comment by PetrovicGoran** [comment]
@bigboo3000 I can confirm that flashing the TV box firmware to version 20220516 and then installing Armbian works. Thank you for your help. I even managed to install Armbian to emmc storage with command `armbian-install`.

**Comment by 833M0L3** [comment]
@PetrovicGoran Hi , what kernel version image did you use to install on emmc? Mine shows black screen whenever I try to install it on emmc

**Comment by PetrovicGoran** [comment]
@833M0L3 I before using armbian, I have flashed my tv box to the following kernel version: AML_user_H96MaxX3_9_20220516.1821.img (I downloaded it from Google drive link provided by @bigboo3000 ). When installing Armbian to emmc, I have followed instructions in terminal, provided by the `armbian-install` command.

**Comment by 833M0L3** [comment]
@PetrovicGoran Yes, I got that part. But which version of Armbian did you use? Could you specify the kernel version and the exact name of the armbian image you used?

**Comment by PetrovicGoran** [comment]
@833M0L3 sorry, I have misunderstood your question. I am using **Armbian OS 24.5.0 Noble (aarch64)**, kernel: **6.6.28-ophub**. As per armbian image exact name, I cannot find it on my PC (I have probably deleted it already). However, I do remember that i have downloaded it from Releases, for S905X3 CPU (`_amlogic_s905x3_noble_`). I have downloaded it about 2 weeks ago (on a weekend, before my last reply from 25th April).

**Comment by PetrovicGoran** [comment]
And if you are asking for `.img` file, I have used H96 Max X3 one.

**Comment by 833M0L3** [comment]
@PetrovicGoran This was what I wanted. Thanks

> @833M0L3 sorry, I have misunderstood your question. I am using **Armbian OS 24.5.0 Noble (aarch64)**, kernel: **6.6.28-ophub**. As per armbian image exact name, I cannot find it on my PC (I have probably deleted it already). However, I do remember that i have downloaded it from Releases, for S905X3 CPU (`_amlogic_s905x3_noble_`). I have downloaded it about 2 weeks ago (on a weekend, before my last reply from 25th April).

**Comment by petesimon** [comment]
thanks @bigboo3000 and everyone else. i successfully installed Armbian on this tv box after downgrading android firmware to 20220516. ☺
