### ISSUE TITLE
编译指定内核，install modules 步骤版本不对

### ISSUE THREAD

**Issue by ffuqiangg** [ophub/amlogic-s9xxx-armbian#2263]
github actions 编译内核时指定版本 5.15.150，kernel_auto false。编译进行到 install modules 这一步时显示的版本为 5.15.153。后续报错内核无法使用。

![Snipaste_2024-04-22_22-52-12](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34062439/159394c4-0201-471a-b673-0ac83787da27)
![Snipaste_2024-04-22_22-50-25](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34062439/a56c1800-920f-4bac-9798-b0c9b083c1ba)

**Comment by ophub** [comment]
现在编译内核只能自动最新版，已经移除了使用kernel.org编译指定版本的支持。
