### ISSUE TITLE
eaidk610  tf安装后无法启动

### ISSUE THREAD

**Issue by yuyixg** [ophub/amlogic-s9xxx-armbian#2264]
**Device Information | 设备信息**
 - SOC: [e.g. eaidk610]
 - Model [e.g. 4+16]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.84]
 - Release: [e.g. [Armbian_24.5.0_rockchip_eaidk-610_jammy_6.1.84_server_2024.04.08.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_save_2024.04/Armbian_24.5.0_rockchip_eaidk-610_jammy_6.1.84_server_2024.04.08.img.gz)

**Describe the bug | 问题描述**
按照文档中所述将img文件解压后，使用工具写入tf卡，但是系统无法启动，路由也没显示ip，hdmi接入显示器也没任何显示，拔出tf卡后原系统启动正常，ip能够正确获取
1. 写入工具尝试了Rufus&balenaEtcher
2. 也尝试了两个系统版本都是同样的问题，hdmi没输出，网络没有ip显示

**Comment by phcl1998** [comment]
写入emmc应该可以

**Comment by Lemon1151** [comment]
应该是conf这项被注释掉的原因
![5 3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/a418c309-6f6a-4c23-b87a-50807237fe10)
![5 3u](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/6cf94347-e05d-4fa5-8cb4-ef470c5b09ef)

**Comment by yuyixg** [comment]
尝试了写入emmc
1. 替换rootfs.img ，发现无法启动，提示找不到rootfs
2. 使用https://github.com/ophub/u-boot/tree/main/u-boot/rockchip/eaidk-610  中的文件替换掉原有文件，但没有了任何反应
不知道有没有同一个板子是怎么写入的？
