### ISSUE TITLE
创维E900V22E（S905L2-B）网卡RTL8822CS，U盘启动了几个系统都是一样的问题，进入系统后重复循环报错“rtw_8822cs mmc0:xxxx:x: Failed to read xxx byte(s) from SDIO port xxxxx”

### ISSUE THREAD

**Issue by a329453283** [ophub/amlogic-s9xxx-armbian#2265]
**Device Information | 设备信息**
 - SOC: [S905L2-B]
 - Model [创维E900V22E]
 -无线网卡RTL8822CS

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.153/6.1.87]
 - Release: [noble/jammy/bullseye]

**Describe the bug | 问题描述**
报错“rtw_8822cs mmc0:xxxx:x: Failed to read xxx byte(s) from SDIO port xxxxx”

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
一开始不知道这机器还有芯片的坑，看releases有E900V22E这个型号就去小黄鱼弄了一台，下载“Armbian_24.5.0_amlogic_s905l3b-e900v22e_noble_6.1.87_server_2024.04.08.img”，写入U盘，插入机器后开机遥控器按右，成功进入跑码界面。创建密码，选择bash，创建用户和密码，确认用户。到重点了，接入无线wifi信号，确认位置是“亚洲/上海”，语言zh-CN.UTF-8，然后就是“neofetch”查看系统信息都没问题。
突然，蹦出来一个标题最后的报错“rtw_8822cs mmc0:xxxx:x: Failed to read xxx byte(s) from SDIO port xxxxx”，当时没在意，然后紧接着就是无限循环，中间应该还有其他的报错。我想用armbian-config去把网卡停掉，都没办法正常操作。
以为是系统问题，紧接着我又下载/jammy/bullseye的s905l3b-e900v22e型号5.15/6.1.87系统，问题依旧。
后来看Issus里有人说他的这个机器是S905L2，我就把机器也拆了发现和不是L3B，我的是L2-B。又重新下载"Armbian_24.5.0_amlogic_s905l2_bullseye_6.1.84_server_2024.04.08.img"，还是一样的问题。中间也修改过uEnv.txt里的dtb文件，不是不能进到跑码界面，就是问题依旧。

小白一个，还请O大指导一下。感谢！

**Comment by a329453283** [comment]
![Uploading 1.正面S905L2-B.jpg…]()

**Comment by ophub** [comment]
忽略。这是无线网卡驱动，这个是从第三方集成到内核的，有些设备可以驱动，有些无法使用，这个8822cs已经更换过几个版本了都这样挑设备。你在armbian-config里禁用无线即可。

**Comment by a329453283** [comment]
> 忽略。这是无线网卡驱动，这个是从第三方集成到内核的，有些设备可以驱动，有些无法使用，这个8822cs已经更换过几个版本了都这样挑设备。你在armbian-config里禁用无线即可。


--------------
感谢O大，我晚上回家试一下的，有问题我再来反馈。

**Comment by a329453283** [comment]
ARMbian-config进入后如何关闭无线网卡？一直报错看不清，我进去找设置没找到。😂
