### ISSUE TITLE
N1写入硬改32GB EMMC 不启动

### ISSUE THREAD

**Issue by jackcctse** [ophub/amlogic-s9xxx-armbian#2267]
刚好手上有两个 N1, 一个硬改了32G EMMC, 一个没改，是原来的8G。

8G的写入EMMC后正常启动，但32G的不能，停留在启动画面的第一屏。
请问armbian-install不支持硬改 EMMC吗？
已经试了5.15及6.1。

**Comment by ophub** [comment]
n1换emmc你看一下复刻的原盘中的内容。

https://www.znds.com/tv-1145022-1-1.html

**Comment by jackcctse** [comment]
原般的内容有複制到新的EMMC。倒是之知安装过论坛那个5.77版，不知道有没有影响？
本次写入时ROOTFS有个讯息，不知道是不是也有关？

`[ INFO ] Formatting ROOTFS ...`
`/dev/mmcblk2p2 contains a ext4 file system labelled 'ROOTFS_EMMC'`
`	last mounted on /ddbr/install on Wed Apr  3 21:43:12 2024`
`mount: (hint) your fstab has been modified, but systemd still uses`
`       the old version; use 'systemctl daemon-reload' to reload.`

**Comment by ophub** [comment]
这个不影响

**Comment by allonmymind** [comment]
> 刚好手上有两个 N1, 一个硬改了32G EMMC, 一个没改，是原来的8G。
> 
> 8G的写入EMMC后正常启动，但32G的不能，停留在启动画面的第一屏。 请问armbian-install不支持硬改 EMMC吗？ 已经试了5.15及6.1。

大概率你emmc问题，我换了好几个64g的都能刷
