### ISSUE TITLE
ophub大佬，您好，我拉取这个项目的源码本地打包为什么会提示etc/os-release没有那个文件或目录呢？

### ISSUE THREAD

**Issue by Mango1151** [ophub/amlogic-s9xxx-armbian#2268]
![Uploading NTI%]RWXH6NP{(RUJ[X[XDS.png…]()

**Comment by Mango1151** [comment]
![NTI% RWXH6NP{(RUJ X XDS](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/86441c06-827b-4297-a232-0fa71aabcfb2)

**Comment by ophub** [comment]
这个显示你用的原系统不符合要求，你的这个armbian怎么编的？

**Comment by Mango1151** [comment]
> 这个显示你用的原系统不符合要求，你的这个armbian怎么编的？

哦哦，找到原因了，就是原镜像有问题
