### ISSUE TITLE
你好，5.16.18 5.17.1 这个两个版本漏了。

### ISSUE THREAD

**Issue by yonggedebaqi** [ophub/amlogic-s9xxx-armbian#227]
你好，5.16.18 5.17.1 这个两个版本漏了。

**Comment by ophub** [comment]
我只预编了5.4/5.15这两个有几年维护期的内核，5.16/5.17是过度版本，一般只维护两个月就换版了。你如果喜欢可以fork了，点一下actions自己编一个，更多参数里填`-k 5.16.1_5.17.1`即可，会自动使用同系列的最新内核版本

**Comment by yonggedebaqi** [comment]
多谢
