### ISSUE TITLE
安装软件出现如下错误代码如何解决

### ISSUE THREAD

**Issue by baiyang7** [ophub/amlogic-s9xxx-armbian#2272]
root@armbian:~# apt install docker.io
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 docker.io : Depends: containerd (>= 1.2.6-0ubuntu1~) but it is not going to be installed
 libpam-systemd : Depends: systemd (= 255.4-1ubuntu8) but 255.4-1ubuntu7 is to be installed
 systemd : Depends: libsystemd-shared (= 255.4-1ubuntu7) but 255.4-1ubuntu8 is to be installed
           Depends: libsystemd0 (= 255.4-1ubuntu7) but 255.4-1ubuntu8 is to be installed
 systemd-resolved : Depends: systemd (= 255.4-1ubuntu8) but 255.4-1ubuntu7 is to be installed
 systemd-sysv : Depends: systemd (= 255.4-1ubuntu8) but 255.4-1ubuntu7 is to be installed
 udev : Depends: libudev1 (= 255.4-1ubuntu7) but 255.4-1ubuntu8 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

不仅限于docker，所有软件都这样包括armbian-software、apt --fix-broken instal这些都是差不多的提示，应该怎么办？

**Comment by ophub** [comment]
`cat /etc/ophub-release`

**Comment by baiyang7** [comment]
> 哪个版本 `cat /etc/ophub-release`

PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='noble'
MODEL_ID='101'
MODEL_NAME='Phicomm-N1'
SOC='s905d'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
FAMILY='meson-gxl'
BOARD='s905d'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.1.87'
KERNEL_BACKUP='yes'
BOOT_CONF='uEnv.conf'
ROOTFS_TYPE='ext4'
DISK_TYPE='emmc'
AMPART_STATUS='no'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
UBOOT_OVERLOAD='u-boot-n1.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='unifreq'
BUILDER_NAME='ophub'
PACKAGED_DATE='2024-04-20'

今天才安装的

**Comment by ophub** [comment]
```
rm -rf /lib64
apt --fix-broken install
apt-update
```
