### ISSUE TITLE
zxv10 b860av2.1 u 的盒子

### ISSUE THREAD

**Issue by shuzhizhi** [ophub/amlogic-s9xxx-armbian#2273]
zxv10 b860av2.1 u 的盒子
使用s905l3芯片
使用了安卓底包

链接：https://pan.baidu.com/s/1hHr7EYN6x8jC3gVsoiz8gA?pwd=1111 
提取码：1111 
复制这段内容后打开百度网盘手机App，操作更方便哦

固件使用了
Armbian_24.5.0_amlogic_s905l3-cm211_bullseye_6.6.28_server_2024.04.25.img
实拍图片如下
![IMG_20240423_160442](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81603713/e454535b-6a21-42e1-a4de-c653072472c5)
![IMG_20240423_160453](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81603713/79191faf-16b0-47fd-9254-93ebf206eb5c)
![IMG_20240426_115920](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81603713/a40221e0-b998-4407-9d1b-2ef75a9a5e1b)
短接点为r76电阻。

由于是nand闪存，无法写入
使用sd卡会如下循环报错done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... Scanning for Btrfs filesystems
done.
Begin: Waiting for root file system ... [    8.449210] scsi 0:0:0:0: Direct-Access     Generic  STORAGE DEVICE   0272 PQ: 0 ANSI: 0
[    8.453344] sd 0:0:0:0: [sda] Media removed, stopped polling
[    8.459193] sd 0:0:0:0: [sda] Attached SCSI removable disk
[    8.925579] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   10.013537] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   11.101654] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   12.189573] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   13.277533] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   14.369520] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   15.457588] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
[   16.542945] mmc1: error -84 whilst initialising SD card
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
[   17.631503] mmc1: error -84 whilst initialising SD card
使用读卡器则能正常进入系统
![A2GVVQZDT9A41AM1P E1X{6](https://github.com/ophub/amlogic-s9xxx-armbian/assets/81603713/67e895a7-f043-4b00-a8e9-b6e253b7b7a3)
看看o大还有啥办法吧，或者还需要什么数据。

**Comment by ophub** [comment]
SD卡的兼容性问题，你使用读卡器是一个好的解决方法。

**Comment by shuzhizhi** [comment]
换了张tf卡好像可以了，果真是tf不兼容导致的，谢谢o大。这个issue可以close了。

**Comment by ophub** [comment]
好的

**Comment by yangyq117** [comment]
O大你好，经过测试，咪咕盒子mgv2000和中兴zxv10 b863av3.2-m 同为nand闪存，已测试成功刷入，与中兴zxv10 b860av3.2-u的nand芯片一致，我正准备测试

**Comment by cuicanmx** [comment]
O大为什么nand写不了啊手上还有cm201-2说是只有emmc才能刷，这有什么区别吗

**Comment by paopao35988** [comment]
请问安装wireguard缺少kmod-wireguard怎么解决？

**Comment by zeds27** [comment]
无法写入nand我在给b860v2.1烧录armbian的时候也是无法烧录，后来看了一个教程，说是emmc被厂家替换为enand，说是频率不同，让我修改了dtb文件里的emmc那里的最高频率，然后成功识别，然后烧录进了nand
