### ISSUE TITLE
荐片盒子使用armbian-update -k 5.10回退旧版内核后，执行成功，开机失败

### ISSUE THREAD

**Issue by 11642509** [ophub/amlogic-s9xxx-armbian#2277]
Device Information | 设备信息

SOC: [rk3566]
Model [荐片盒子 JPBOX]
Armbian Version | 系统版本

Kernel Version: [Armbian OS 24.5.0 Bullseye with Linux 6.1.86-ophub]
Release: [bullseye]
Describe the bug | 问题描述
armbian-update -k 5.10回退旧版内核后，执行成功，开机失败。想在盒子内使用redroid，所以想使用5.10内核，直接更新后开机黑屏。能否增加5.10的方案？或者新版内核支持modprobe binder_linux模块

**Comment by ophub** [comment]
荐片的5.10要使用rk35xx，不能使用stable，所以你先使用`armbian-update -s`救援恢复吧。
更新内核指定tags使用命令`armbian-update -u rk35xx -k 5.10.160`
或者你先把设置里的tags指定为`rk35xx`，这样更新时就不用每次驶入`-u rk35xx`了，修改页面在`/etc/ophub-release`里，`KERNEL_TAGS='rk35xx'`

**Comment by 11642509** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，感谢您的来信，邮件已经收到，我将尽快给您回复。
