### ISSUE TITLE
Error when install RTL8821CU Wireless Driver

### ISSUE THREAD

**Issue by codez93** [ophub/amlogic-s9xxx-armbian#228]
Hi! first sorry for my english, it not my main language.
I have a TV Box type A95X F3 Air with chipset S905X3 (using firmware: Armbian_22.05.0_Aml_s905x3_focal_5.4.188_2022.03.30.1626.img) and USB Dongle with RTL8821CU inside. When I install the Driver from this link: https://github.com/morrownr/8821cu-20210118, I get the following error:

> Error! Your kernel headers for kernel 5.4.188-flippy-71+o cannot be found.
Please install the linux-headers-5.4.188-flippy-71+o package,
or use the --kernelsourcedir option to tell DKMS where it's located

How can i fix this error and install that driver. Thank for help!

**Comment by ophub** [comment]
headers: /usr/local/include

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/6791828d80ddea6b2727550e2aef7cb5b97c7e00/compile-kernel/tools/config/config-5.4.187#L2821

**Comment by codez93** [comment]
> There is this driver in the kernel, you can change the driver in the configuration file, then compile a kernel containing this driver, and install it.
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/6791828d80ddea6b2727550e2aef7cb5b97c7e00/compile-kernel/tools/config/config-5.4.187#L2821
> 
> change to: `CONFIG_RTL8821CU=m`
> 
> Kernel compilation and usage instructions https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

I'm build success, but i don't known how to install the kernel. i'm in kernel directory, but when i execute armbian-update command, it return this:

> $ sudo armbian-update
Ready to update, please wait...
Already the latest version, no need to update.

**Comment by ophub** [comment]
You can first armbian-update for other versions, and then install your own. Because it will no longer be installed when the kernel version is checked to be the same.

You put your compiled kernel in a directory. When executing armbian-update in the current directory, it is the first to find and install from this directory.

**Comment by codez93** [comment]
> You can first armbian-update for other versions, and then install your own. Because it will no longer be installed when the kernel version is checked to be the same.
> 
> You put your compiled kernel in a directory. When executing armbian-update in the current directory, it is the first to find and install from this directory.

Pls help me to update for other version, i can't find the other version in Release, the latest kernel version for 5.4 could be download is 5.4.188, same as my current kernel.

**Comment by ophub** [comment]
armbian-update 5.10.100
reboot
cd /your-kernel-dir
armbian-update
