### ISSUE TITLE
Command not found armbian-update

### ISSUE THREAD

**Issue by sharicov** [ophub/amlogic-s9xxx-armbian#2280]
Tried to update armbian kernel, getting Command not found: armbian-update
Device: x96 plus

cat /etc/armbian-release                                                                                                                                                                      
# PLEASE DO NOT EDIT THIS FILE                                                                                                                                                                               
BOARD=odroidn2                                                                                                                                                                                               
BOARD_NAME="Aml s905x3"                                                                                                                                                                                      
BOARDFAMILY=meson-g12b                                                                                                                                                                                       
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git                                                                                                                                                    
BUILD_REPOSITORY_COMMIT=c17adec                                                                                                                                                                              
VERSION=22.08.0-trunk                                                                                                                                                                                        
LINUXFAMILY=meson64                                                                                                                                                                                          
ARCH=arm64                                                                                                                                                                                                   
IMAGE_TYPE=stable                                                                                                                                                                                            
BOARD_TYPE=conf                                                                                                                                                                                              
INITRD_ARCH=arm64                                                                                                                                                                                            
KERNEL_IMAGE_TYPE=Image                                                                                                                                                                                      
BRANCH=current       

uname -r                                                                                                                                                                                      
6.1.87-ophub

**Comment by sharicov** [comment]
locate armbian-update                                                                                                                                                                         
/etc/update-motd.d/40-armbian-updates

**Comment by ophub** [comment]
```
chmod +x /usr/sbin/armbian-update
armbian-update
```

**Comment by sharicov** [comment]
Thanks for quick response. it is executable, problem is there is no
/usr/shin in the path now for some reason
