### ISSUE TITLE
A95X F3 Air eMMC install

### ISSUE THREAD

**Issue by Pat-78** [ophub/amlogic-s9xxx-armbian#2282]
Hi. 
I have a A95X Air F3 TvBox (S905X3, 4GB ram, 64GB eMMC).
Armbian_24.5.0_amlogic_s905l3-unt400g1_noble_6.6.28_server_2024.04.25.img.gz on a USB stick and with change of
uEnv.txt with FDT=/dtb/amlogic/meson-sm1-a95xf3-air.dtb
It is OK (minimal test, SSH …).
I would like an install on the eMMC.
With armbian-instal there is no option for meson-sm1-a95xf3-air.dtb (only meson-glx-XXXX).
Is customize option the good way ?
What are the values for : soc name, dtb name, uboot_overload, mainline_uboot, bootloader_img ?

Thx

**Comment by ophub** [comment]
option: 0

**Comment by Pat-78** [comment]
Thx for your help
It was what I tried  (0 : customize) but I need more help !

_Soc Name (such as s9xxx)_ : s905x3 or s905l3 ?
_DTB Name (such as meson-xxx.dtb)_ : meson-sm1-a95xf3-air.dtb   = ok ?
_UBOOT_OVERLOAD Name (such as u-boot-xxx.bin)_ : u-boot-s905x3.bin   = ok ?
_MAINLINE_UBOOT Name (such as xxx-u-boot.bin.sd.bin)_ : no such file in boot folder
_BOOTLOADER_IMG Name (such as xxx-bootloader.img)_ : no such file in boot folder

**Comment by ophub** [comment]
```
meson-sm1-a95xf3-air.dtb
u-boot-s905x3.bin
enter
enter
```

**Comment by Pat-78** [comment]
Super, it's good.
Thx

**Comment by ophub** [comment]
Can you test the feasibility of this plan? If it's possible, I will add it to the list. Can you share a `photo` of your box? Front and back, also share a photo of the motherboard. If you mark the location of the rescue short circuit point on the motherboard photo. If you have this box's `Android system`, share a download link.

**Comment by ophub** [comment]
I see that this device is in the list now, can you give it a try?




https://github.com/ophub/amlogic-s9xxx-armbian/blob/f97ffc434fc52cc20fd64a7130df72b154187585/build-armbian/armbian-files/common-files/etc/model_database.conf#L174

`armbian-install`
option: `523`

**Comment by Pat-78** [comment]
I vill do my best for the pictures.
armbian-install show only options from 101 to 131
how have more ?

By the way , are wifi and display supported ?

**Comment by ophub** [comment]
`armbian-install -l yes`

**Comment by ophub** [comment]
Thanks for sharing!

**Comment by Pat-78** [comment]
I forgot this point : " If you have this box's Android system, share a download link."
Before armbian upgrade , with Android/parameters : 
Version Android 9
Numero build : A95X_F3_AIR_M-9.0.0-202311241535
Security update 5 august 2018
But no link to share

**Comment by Pat-78** [comment]
And the backside picture, the black wire (top right corner) is for wifi antenna
![backside](https://github.com/ophub/amlogic-s9xxx-armbian/assets/56218024/b820cc50-6af3-445b-ae55-509541d9171b)

**Comment by ophub** [comment]
ok, thks
