### ISSUE TITLE
求助帖，我家云刷入bullseye系列，不能进入刷机模式，不能按键开机

### ISSUE THREAD

**Issue by ksi1110** [ophub/amlogic-s9xxx-armbian#2283]
**Device Information | 设备信息**
 - SOC: [rk3328]
 - Model [chainedbox_l1_pro，我家云]

**Armbian Version | 系统版本**
 - Kernel Version: [bullseye_6.1.87、bullseye_6.6.28]，刷了bullseye的4.25-4.27一共4个版本
 - Release: [bullseye]

**Describe the bug | 问题描述**
如标题，刷入nobel后发现一堆bug，之前开issue问O大才知道nobel是测试版，重新刷了bullseye版本，下载刷入了不同的内核版本的系统
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/18417132/4c2ffd98-3105-4cf6-a809-b142a81d1ab4)

暂时发现两个比较让人难受的bug：

1.使用boot是rk3328_loader_v1.14.249.bin，刷入后，无法通过重置按钮进入maskrom进行刷机

2.命令行关机后，无法使用前置开关按钮开机，但可以通过长按按钮关机，不管是通过命令行还是按钮关机后必须重新插入电源才能开机（自动开机）

有一样用我家云的老铁，有遇到上述bug的请教下该怎么修复，打算下载bookworm系列的试一下

**Comment by Clumsy-yuu** [comment]
我也遇到了同样问题，轻微是否已经解决？

**Comment by ksi1110** [comment]
> 我也遇到了同样问题，轻微是否已经解决？

没有，只能通过短接来重写固件，重写后就扔在角落里面挂bt了，还挺稳
