### ISSUE TITLE
linux-headers 缺少文件

### ISSUE THREAD

**Issue by achaoge** [ophub/amlogic-s9xxx-armbian#2285]
今天尝试编译内核模块，提示缺少文件： include/generated/asm-offsets.h

rk3399 平台，6.1 和 6.6 都是这样。

`make -C /usr/src/linux-headers-6.6.28-ophub/ M=/home/chao/tmp/WK2XXX_SPI_v2.4 modules
make[1]: Entering directory '/usr/src/linux-headers-6.6.28-ophub'
awk: cannot open "include/generated/asm-offsets.h" (No such file or directory)`

**Comment by AlanLeeIsGood** [comment]
全盘搜索asm-offsets.h这个名字没有的话试试搜索ams-offsets.h
find / -name "asm-offsets.h"
find / -name "ams-offsets.h"
找到了之后去做个软链接就行了

**Comment by achaoge** [comment]
> 全盘搜索asm-offsets.h这个名字没有的话试试搜索ams-offsets.h find / -name "asm-offsets.h" find / -name "ams-offsets.h" 找到了之后去做个软链接就行了

这样行不通。
查找到文件之后，文件的内容都是指向include/generated/asm-offsets.h，如图1
![Screenshot from 2024-05-06 10-26-29](https://github.com/ophub/amlogic-s9xxx-armbian/assets/168769/5f1e1628-c913-443b-83f9-cba99f73f5b6)


而在内核源代码编译后的目录里面，是存在这个include/generated/asm-offsets.h 文件的，内容如图2
![Screenshot from 2024-05-06 10-33-54](https://github.com/ophub/amlogic-s9xxx-armbian/assets/168769/f2222ee4-a1ad-4811-9aab-e992a7f39733)

**Comment by achaoge** [comment]
> 今天尝试编译内核模块，提示缺少文件： include/generated/asm-offsets.h
> 
> rk3399 平台，6.1 和 6.6 都是这样。
> 
> `make -C /usr/src/linux-headers-6.6.28-ophub/ M=/home/chao/tmp/WK2XXX_SPI_v2.4 modules make[1]: Entering directory '/usr/src/linux-headers-6.6.28-ophub' awk: cannot open "include/generated/asm-offsets.h" (No such file or directory)`

看起来，打包的linux-header 对比系统通过 apt 安装的 linux-header 少了很多文件。
