### ISSUE TITLE
Link dead in amlogic-s9xxx-armbian/blob/main/documents/README.md

### ISSUE THREAD

**Issue by okpapt** [ophub/amlogic-s9xxx-armbian#2286]
Hello,

I find dead link in https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.md#12152-add-system-files about :
- [Amlogic](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/armbian-files/platform-files/amlogic),
- [Rockchip](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/armbian-files/platform-files/rockchip),
- [Allwinner](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/armbian-files/platform-files/allwinner)
 
Maybe others links are dead, but I do not test all links.

**Comment by ophub** [comment]
Thanks for your feedback, the link address error has been fixed

https://github.com/ophub/amlogic-s9xxx-armbian/commit/82dcd92a3798b6fde34b563f7b88c3681d426e9a
