### ISSUE TITLE
云南电信TY1608刷入armbian成功

### ISSUE THREAD

**Issue by AlanLeeIsGood** [ophub/amlogic-s9xxx-armbian#2287]
**Device Information | 设备信息**
 - SOC: [S905L3B]
 - Model [TY1608高安版]
 - 1+8G

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.84]
 - Release: [Armbian OS 24.5.0 Noble]

**Describe the bug | 问题描述**
内存卡启动后在armbian系统下有线网卡、无线网卡、HDMI均不可使用
刷安卓9.0所有线刷包均卡在1%
分析刷机包发现其中有DDR_ENC,UBOOT_ENC字样才发现是高安版本

刷入tools中四川电信高安版android_tv_ty1608_s905l3b.tar.xz后，安卓卡在libcutils.so错误上并不能引导，安卓不断自动重启
此时在armbian下使用meson-gxl-s905l3b-e900v22e.dtb有线网卡可用，猜测是四川电信高安版中的bootloader分区或dtb起到作用

无线网卡型号RTL8822cs
log中报错
[   20.189485] rtw_8822cs mmc0:0001:1: Firmware version 9.9.11, H2C version 15
[   20.198485] rtw_8822cs mmc0:0001:1: WOW Firmware version 9.9.4, H2C version 15
[   20.320776] rtw_8822cs mmc0:0001:1: rfe 255 isn't supported
[   20.321788] rtw_8822cs mmc0:0001:1: failed to setup chip efuse info
[   20.327028] rtw_8822cs mmc0:0001:1: failed to setup chip information
是驱动问题还是dtb问题大佬能否指点个方向

附dtb链接: https://pan.baidu.com/s/15nlT2sxva1ZIOuF3mvZDfw?pwd=rvhf 
来自tools中的android_tv_ty1608_s905l3b.tar.xz 提取 安卓dtb型号是p291_1g

**Comment by ophub** [comment]
首页的设备列表里，搜TY1608，看2个分享者的使用方法。
rtl8822cs驱动随缘吧，f大添加过几个版本，但有的人反馈可以正常使用，有的人不行，无解，不可用就忽略，或者自己找找github上的相关驱动仓库，自己在盒子里添加驱动试试。

**Comment by Triment** [comment]
> **Device Information | 设备信息**
> 
> * SOC: [S905L3B]
> * Model [TY1608高安版]
> * 1+8G
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version: [6.1.84]
> * Release: [Armbian OS 24.5.0 Noble]
> 
> **Describe the bug | 问题描述** 内存卡启动后在armbian系统下有线网卡、无线网卡、HDMI均不可使用 刷安卓9.0所有线刷包均卡在1% 分析刷机包发现其中有DDR_ENC,UBOOT_ENC字样才发现是高安版本
> 
> 刷入tools中四川电信高安版android_tv_ty1608_s905l3b.tar.xz后，安卓卡在libcutils.so错误上并不能引导，安卓不断自动重启 此时在armbian下使用meson-gxl-s905l3b-e900v22e.dtb有线网卡可用，猜测是四川电信高安版中的bootloader分区或dtb起到作用
> 
> 无线网卡型号RTL8822cs log中报错 [ 20.189485] rtw_8822cs mmc0:0001:1: Firmware version 9.9.11, H2C version 15 [ 20.198485] rtw_8822cs mmc0:0001:1: WOW Firmware version 9.9.4, H2C version 15 [ 20.320776] rtw_8822cs mmc0:0001:1: rfe 255 isn't supported [ 20.321788] rtw_8822cs mmc0:0001:1: failed to setup chip efuse info [ 20.327028] rtw_8822cs mmc0:0001:1: failed to setup chip information 是驱动问题还是dtb问题大佬能否指点个方向
> 
> 附dtb链接: https://pan.baidu.com/s/15nlT2sxva1ZIOuF3mvZDfw?pwd=rvhf 来自tools中的android_tv_ty1608_s905l3b.tar.xz 提取 安卓dtb型号是p291_1g

能出个资源列表吗，这机器太不好找资源了，感谢分享

**Comment by Triment** [comment]
> **Device Information | 设备信息**
> 
> * SOC: [S905L3B]
> * Model [TY1608高安版]
> * 1+8G
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version: [6.1.84]
> * Release: [Armbian OS 24.5.0 Noble]
> 
> **Describe the bug | 问题描述** 内存卡启动后在armbian系统下有线网卡、无线网卡、HDMI均不可使用 刷安卓9.0所有线刷包均卡在1% 分析刷机包发现其中有DDR_ENC,UBOOT_ENC字样才发现是高安版本
> 
> 刷入tools中四川电信高安版android_tv_ty1608_s905l3b.tar.xz后，安卓卡在libcutils.so错误上并不能引导，安卓不断自动重启 此时在armbian下使用meson-gxl-s905l3b-e900v22e.dtb有线网卡可用，猜测是四川电信高安版中的bootloader分区或dtb起到作用
> 
> 无线网卡型号RTL8822cs log中报错 [ 20.189485] rtw_8822cs mmc0:0001:1: Firmware version 9.9.11, H2C version 15 [ 20.198485] rtw_8822cs mmc0:0001:1: WOW Firmware version 9.9.4, H2C version 15 [ 20.320776] rtw_8822cs mmc0:0001:1: rfe 255 isn't supported [ 20.321788] rtw_8822cs mmc0:0001:1: failed to setup chip efuse info [ 20.327028] rtw_8822cs mmc0:0001:1: failed to setup chip information 是驱动问题还是dtb问题大佬能否指点个方向
> 
> 附dtb链接: https://pan.baidu.com/s/15nlT2sxva1ZIOuF3mvZDfw?pwd=rvhf 来自tools中的android_tv_ty1608_s905l3b.tar.xz 提取 安卓dtb型号是p291_1g

已经找到了，感谢分享
