### ISSUE TITLE
小宝NAS不能识别SATA就是再次打包的问题

### ISSUE THREAD

**Issue by Lemon1151** [ophub/amlogic-s9xxx-armbian#2293]
ophub您是取armbian官方源码编译一个odroidn2作为基础镜像包，然后再创建一个空img镜像包，把odroidn2和你仓库的build-armbian复制到新的img镜像里再次打包？？

**Comment by Lemon1151** [comment]
我拉取armbian官方源码自己编译出来的小宝nas固件，烧录到sd卡能正常开机，也能使用SATA

**Comment by ophub** [comment]
你用的官方哪个board
