### ISSUE TITLE
B860AV2.1-A2的网卡驱动问题

### ISSUE THREAD

**Issue by FURONGsun** [ophub/amlogic-s9xxx-armbian#2295]
**Device Information | 设备信息**
 - SOC: s905l3b
 - Model b860av2.1 a2

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.100
 - Release: jammy

**Describe the bug | 问题描述**
尝试了所有已经发布的版本和Dtb均不能正常驱动该机子的网卡，用ttl查看能正常出eth0，但是插上网线不认。
从闲鱼某个老哥了解到这款机子需要使用较老的release，约2年以前，并且按照机身mac地址还区分三种不同的固件，我本想找老哥直接花钱消灾，奈何我把盒子的外壳丢了。没有盒子上面标识的mac地址，老哥似乎不是很愿意理我。所以我想开个issue来专门讨论一下这个问题，是什么原因导致的网卡不能正常驱动，老版本的release和新版本的按道理dtb应当是相同的但是为什么后者不能正常驱动网卡。关于以上问题的讨论，非常感谢您如果您能提供相关帮助。

**Comment by ophub** [comment]
刷个安卓试试

**Comment by FURONGsun** [comment]
网口是好的，之前安卓下可用。您说的刷个安卓是指通过安卓获取网口的mac吗

**Comment by ophub** [comment]
去电视盒子论坛下载一个新的安卓刷机

**Comment by AlanLeeIsGood** [comment]
TTL接到盒子上，开机狂按回车进uboot，然后printenv里面有mac就是你盒子的原始mac地址

**Comment by FURONGsun** [comment]
从一个人购买了老版本的armbian固件，问题已解决

**Comment by FURONGsun** [comment]
留下你的邮箱，我会在七个工作日之类分享到你的邮箱

**Comment by Ironmanwu** [comment]
374331302@qq.com 感谢感谢

**Comment by FURONGsun** [comment]
不好意思最近实在是太忙，已经将固件发送到你的邮箱，麻烦尽快下载，文件将于30天后过期
&nbsp;


李家睿
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月17日(星期五) 晚上9:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [ophub/amlogic-s9xxx-armbian] B860AV2.1-A2的网卡驱动问题 (Issue #2295)














 
***@***.*** 感谢感谢

**Comment by FURONGsun** [comment]
> [374331302@qq.com](mailto:374331302@qq.com) 感谢感谢

不好意思最近实在是太忙，已经将固件发送到你的邮箱，麻烦尽快下载，文件将于30天后过期

**Comment by ll929** [comment]
@FURONGsun 可以发一下安卓底包的链接吗🙏🏻

**Comment by wu560130911** [comment]
@FURONGsun 可以发一个包吗？我也是同样的问题，刷了另一个android固件后没法联网了

**Comment by mrsoshining** [comment]
> 从一个人购买了老版本的armbian固件，问题已解决

大佬，看样子你是B860AV2.1-A2这个盒子安装armbian真正成功的人，我怎么都启动不了，试了很多版本，电视开机画面反复重启，就是进不了U盘的系统，如果你能看到，希望能给予帮助，谢谢。343547882@qq.com

**Comment by RoyBen114** [comment]
> 从一个人购买了老版本的armbian固件，问题已解决

@FURONGsun 能否分享一下固件
Roy123ty@hotmail.com
