### ISSUE TITLE
希望能够支持 HK1 RBOX R2，感谢

### ISSUE THREAD

**Issue by CLANNADHH** [ophub/amlogic-s9xxx-armbian#2302]
**Device Information | 设备信息**
 - SOC: Rockchip RK3566 Quad-Core ARM Cortex A55
 - Model HK1 RBOX R2
 - Memory: 8G
 - EMMC: 64G
 
机器详细介绍可以看这里 https://techxreviews.com/hk1-rbox-r2-tv-box-review/
感谢大佬，麻烦做下支持。

自己提取的dtb,   链接: https://pan.baidu.com/s/1b_5Gv5pxVh6xImMFQS-l_g?pwd=ff74 提取码: ff74 
原始安卓镜像   https://cloud.189.cn/web/share?code=3QvuIvEVRJB3（访问码：trg3） 一共有2个版本，我手头的机子是8G运存的。

**Comment by Clannad-Kazusa** [comment]
大佬，请问这是已经完成了吗？
