### ISSUE TITLE
无限重启，卡一屏，驱动不识别

### ISSUE THREAD

**Issue by RUI2580** [ophub/amlogic-s9xxx-armbian#2303]
我刷完安卓之后无限重启了，然后想重新安装但连不上电脑，驱动程序是安装的，设备管理器有显示，但是刷机工具没有，现在不会搞了。
![IMG_20240507_121738](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/8837ebdd-9370-4386-931e-4a7b048df9e5)

**Comment by RUI2580** [comment]
现在卡一屏了
![IMG_20240507_124054](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/194991ff-eb41-449d-99a9-2fb00222293d)

**Comment by ophub** [comment]
短接

**Comment by RUI2580** [comment]
![IMG_20240507_130451](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/c720f454-85ee-4ab7-a177-c0d76fd5b171)
![IMG_20240507_130441](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/f95f44cc-52fe-48a7-ae84-c0d2348a78d9)

接哪个点🫠

**Comment by RUI2580** [comment]
![IMG_20240507_130451](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/c720f454-85ee-4ab7-a177-c0d76fd5b171)
![IMG_20240507_130441](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/f95f44cc-52fe-48a7-ae84-c0d2348a78d9)
接哪个点🫠

**Comment by RUI2580** [comment]
![IMG_20240507_130451](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/c720f454-85ee-4ab7-a177-c0d76fd5b171)
![IMG_20240507_130441](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/f95f44cc-52fe-48a7-ae84-c0d2348a78d9)
接哪个点

**Comment by RUI2580** [comment]
网上找了很多，但没有和我一样的型号🥹

**Comment by RUI2580** [comment]
短接成功了，但是刷的时候报错，说格式化磁盘失败，这怎么搞🤔

**Comment by ophub** [comment]
猜不到你说的具体错误，但是猜测可能你用的是要下调频率的魔百和，调频方法看方档。

**Comment by RUI2580** [comment]
> 猜不到你说的具体错误，但是猜测可能你用的是要下调频率的魔百和，调频方法看方档。

![IMG_20240507_205036](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/0a7df06f-0ff0-4954-bc77-8994278a9205)
就是这样的情况

**Comment by RUI2580** [comment]
![IMG_20240507_205036](https://github.com/ophub/amlogic-s9xxx-armbian/assets/147964054/a8cb36f9-eb34-4460-8007-dfc938c3b7e3)
就是这样的，🫠

**Comment by ophub** [comment]
取消右边的两个擦除的勾选

**Comment by RUI2580** [comment]
取消了也不行，换了固件包也不行，刚刚买了个TTL线，我试试putty，再不行的话就换一个盒子，麻烦大佬您了，问了这么多问题😄😆
