### ISSUE TITLE
E900V21E能不能适配ARMBIAN

### ISSUE THREAD

**Issue by hu-min** [ophub/amlogic-s9xxx-armbian#2305]
S905L3+MT7661RSN
按这个https://github.com/ophub/amlogic-s9xxx-armbian/issues/1277#issuecomment-1505347194
USB可以正常驱动，写入EMMC正常，刷入后无法启动进入系统。

**Comment by gametta** [comment]
如果是启动正常，写入正常，重启后不启动，可能就是你的安装选项不对。就是三位数没选对。
你可以到海鲜市场搜你的盒子型号，有一个人专门刷机的，他那里按照型号的MAC地址提供刷机包。

**Comment by ophub** [comment]
`armbian-install -m yes`
