### ISSUE TITLE
如何恢复出厂设置？已写入emmc，无u盘

### ISSUE THREAD

**Issue by Cxy-2008** [ophub/amlogic-s9xxx-armbian#2307]
**Device Information | 设备信息**
 - SOC: [e.g. S905l3b]
 - Model [e.g. CM311-1A YST]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
没有在armbian-config里找到恢复出厂设置的选项 无u盘

**Comment by ophub** [comment]
买个U盘吧，某团和某东都有超市半小时送到家的服务
