### ISSUE TITLE
M411A S905L3 安装 armbian  有线网络链接不上获取不到ip

### ISSUE THREAD

**Issue by robot-bear** [ophub/amlogic-s9xxx-armbian#2309]
**Device Information | 设备信息**
 - SOC: [ S095L3]
 -Model [M411A]

DTB
meson-gxl-s905l3b-m302a.dtb

Hardware
2GiB ram

**Armbian Version | 系统版本**
 - Release: [Armbian_24.5.0_amlogic_s905l3_bullseye_5.15.156_server_2024.05.03.img]

**Describe the bug | 问题描述**
有线网络链接不上获取不到ip

详细描述问题，并在必要时附上屏幕截图。
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22017125/de58461b-d03e-42fa-b63a-e07e486522c7)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22017125/28600b66-0b2f-45d0-af18-f5b07c462b3d)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/22017125/1455d7ad-0170-49c4-830a-b1d8ce016faf)

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

先刷一下安卓系统

**Comment by robot-bear** [comment]
刷了列表中的安卓系统，系统中的网络和wifi是正常的

**Comment by robot-bear** [comment]
是不是和这个系统版本有关  但是我找不到这个系统了

**Comment by robot-bear** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 先刷一下安卓系统
刷了列表中的安卓系统，系统中的网络和wifi是正常的
