### ISSUE TITLE
tx3 s905x3 openwrt 5.4.188 vfd只显示boot不显示时间

### ISSUE THREAD

**Issue by 13528943945** [ophub/amlogic-s9xxx-armbian#231]
如题。上传openvfd包到openwrt，解压，运行./startled.sh vfd/tx3.conf，提示vfdservice运行错误，没有文件或文件夹，日志如下
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.506016] OpenVFD: Version: V1.4.1
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.508015] OpenVFD: vfd_gpio_clk:    Empty.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.509965] OpenVFD: vfd_gpio_dat:    Empty.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.514187] OpenVFD: vfd_gpio_stb:    Empty.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.518091] OpenVFD: vfd_gpio0:    #0 = 0x00; #1 = 0x00; #2 = 0xFF;
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.524224] OpenVFD: vfd_gpio1:    #0 = 0x00; #1 = 0x00; #2 = 0xFF;
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.530332] OpenVFD: vfd_gpio2:    #0 = 0x00; #1 = 0x00; #2 = 0xFF;
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.536459] OpenVFD: vfd_gpio3:    #0 = 0x00; #1 = 0x00; #2 = 0xFF;
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.542582] OpenVFD: vfd_gpio_protocol:  #0 = 0x00; #1 = 0x00;
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.548362] OpenVFD: vfd_chars:    Empty.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.552155] OpenVFD: vfd_dot_bits:    Empty.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.556207] OpenVFD: vfd_display_type:  Empty.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.560525] OpenVFD: Detected gpio chips:  aobus-banks, periphs-banks.
Tue Mar 15 09:28:36 2022 kern.alert kernel: [  212.566902] OpenVFD: Failed to verify VFD configuration file, attempt using device tree as fallback.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.575961] OpenVFD: openvfd_gpio_clk pin entry not found
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.581306] OpenVFD: openvfd_gpio_dat pin entry not found
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.586655] OpenVFD: openvfd_gpio_stb pin entry not found
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.592004] OpenVFD: openvfd_gpio0 pin entry not found
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.597095] OpenVFD: openvfd_gpio1 pin entry not found
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.602179] OpenVFD: openvfd_gpio2 pin entry not found
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.607269] OpenVFD: openvfd_gpio3 pin entry not found
Tue Mar 15 09:28:36 2022 kern.alert kernel: [  212.612389] OpenVFD: can't find openvfd_chars list, falling back to defaults.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.612392] OpenVFD: chars_prop = 0000000000000000
Tue Mar 15 09:28:36 2022 kern.alert kernel: [  212.624169] OpenVFD: can't find openvfd_dot_bits list, falling back to defaults.
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.624172] OpenVFD: dot_bits_prop = 0000000000000000
Tue Mar 15 09:28:36 2022 kern.debug kernel: [  212.636506] OpenVFD: display.type = 0, display.controller = 0, pdata->dev->dtb_active.display.flags = 0x00
Tue Mar 15 09:28:36 2022 kern.alert kernel: [  212.646081] OpenVFD: can't request gpio of gpio_clk
Tue Mar 15 09:28:36 2022 kern.warn kernel: [  212.646098] openvfd: probe of openvfd failed with error -22

**Comment by 13528943945** [comment]
![Screenshot_20220411_142001_com huawei browser](https://user-images.githubusercontent.com/91015016/162677389-6869fb46-60d5-4e08-bc18-aff0895576a1.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led_screen_display_control.md

`openwrt-led 17`

**Comment by 13528943945** [comment]
是用官方源码openwrt21.02，结合你的yml云编译的。是否自定义的rootfs底包缺少了哪些模块?

**Comment by 13528943945** [comment]
用的是你之前的脚本，之前fork的，难道是脚本不够新？

**Comment by ophub** [comment]
看了下你的仓库，你fork的时候还没这个服务。你需要同步下make这个文件。

**Comment by ophub** [comment]
[router-config](https://github.com/13528943945/amlogic-s9xxx-openwrt/tree/main/router-config)

[.github](https://github.com/13528943945/amlogic-s9xxx-openwrt/tree/main/.github)

你这2个目录里改的东西自己备份下。然后同步源码，再上传你的这个自定义修改文件。

**Comment by 13528943945** [comment]
多谢提醒!我再试下

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/1706004ce7267520a0d3bf9f1bf014d2c9ea1fb3/make#L202

主要是make这个文件改动比较多，你的代码里还没这个同步下载openvfd，你需要整个同步下。

**Comment by 13528943945** [comment]
![图片](https://user-images.githubusercontent.com/91015016/162817207-9b12d2ce-f611-4447-9f97-9c15438a5913.png)

**Comment by 13528943945** [comment]
依然提示 open device failed。no such file or directory

**Comment by ophub** [comment]
问题己修复，同步今天的代码即可
