### ISSUE TITLE
E900v22e 内置网卡不工作，HDMI无显示

### ISSUE THREAD

**Issue by whmzsu** [ophub/amlogic-s9xxx-armbian#2311]
**Device Information | 设备信息**
 - SOC: [e.g. S095L3]
 - Model [E900v22e ]

**Armbian Version | 系统版本**
root@armbian:~# uname -a
Linux armbian 5.15.156-ophub #1 SMP PREEMPT Thu Apr 25 11:22:44 EDT 2024 aarch64 aarch64 aarch64 GNU/Linux

Armbian_24.5.0_amlogic_s905l3b-e900v22e_jammy_5.15.156_server_2024.05.03.img

**Describe the bug | 问题描述**
E900v22e 内置网卡不工作(外接usb网卡获取的信息)，HDMI无显示
root@armbian:~# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr 5ac7:b7d0:64e::
4: eth0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether e6:96:16:81:f9:7d brd ff:ff:ff:ff:ff:ff
    altname end0
5: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:00:4e:12:30:4a brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.6/24 brd 192.168.1.255 scope global dynamic noprefixroute eth1
       valid_lft 85152sec preferred_lft 85152sec
    inet6 fe80::f351:e7ef:2a4b:3a9a/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

Settings for eth0:
        Supported ports: [ TP    MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Speed: Unknown!
        Duplex: Unknown! (255)
        Auto-negotiation: on
        Port: Twisted Pair
        PHYAD: 8
        Transceiver: internal
        MDI-X: Unknown
        Supports Wake-on: ug
        Wake-on: d
        Current message level: 0x0000003f (63)
                               drv probe link timer ifdown ifup
        Link detected: no

**Comment by whmzsu** [comment]
参考 https://github.com/ophub/amlogic-s9xxx-openwrt/issues/577   ，居然网卡可以了，只复制了uboot文件

**Comment by pro-xuchao** [comment]
我跟你一样的机顶盒，也想刷机。看你说刷机后无网卡驱动，是通过外置USB网卡连接上的。可是我虽然有个USB网卡，却没有Linux的驱动，进入死循环了。不进系统无法给网卡装驱动，但是没有网卡无法连接上盒子。有什么好的建议吗？

**Comment by whmzsu** [comment]
你试过了吗，插上usb网卡无法dhcp获取地址？

**Comment by pro-xuchao** [comment]
还没试过。但是看你说没有网卡驱动，我都连不上盒子了，怎么去设置USB网卡连接wifi呢？确实不懂，麻烦指点一下。

**Comment by whmzsu** [comment]
> 还没试过。但是看你说没有网卡驱动，我都连不上盒子了，怎么去设置USB网卡连接wifi呢？确实不懂，麻烦指点一下。

无线网卡不行，我用的有线usb网卡，你先试试拷贝u-boot文件，说不定驱动内置网卡了呢

**Comment by pro-xuchao** [comment]
我打算开整了。请问uboot文件文件替换原来的文件，是直接从u盘cp到盒子吗？

**Comment by ophub** [comment]
`/boot/u-boot*`
在这有了

**Comment by pro-xuchao** [comment]
> `/boot/u-boot*` 在这有了

我是小白用户。再问一下细节，是从/boot目录下将u-boot.emmc复制出来吗？目标目录是哪里呢？这个盒子本身是有有限和无线两个网卡，操作后是否两个网卡的驱动都有了？

**Comment by ophub** [comment]
复制相近的u-boot：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

方法看文档：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
