### ISSUE TITLE
armbian-software 无法使用(apt也是)

### ISSUE THREAD

**Issue by ADolphin-02** [ophub/amlogic-s9xxx-armbian#2314]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1 BOX]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.152-ophub]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
**问题:armbian-software 无法使用(apt也是)**
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/89c0ccdf-0f6d-4ae0-b875-eb7208948bb6)
详细过程:系统在 eMMC, 安装了tailscale, 安装命令如下(贴在最后可以方便复制)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/9bbd1d47-2bd0-4b91-87fb-181c8ea65931)
然后armbian-software和其他的apt 都无法安装了
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/7fff6d13-224e-43fd-963c-b2b9aa72487b)
安装chatgpt的好多方法无法解决(第一步sudo apt update没问题)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/ce637814-4468-498e-9425-df63bb8e671f)
第二部就出错了(sudo apt --fix-broken install)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/1258ac85-c3fd-4b93-a3ff-1ae438f13f70)
已经尝试了armbian-docker ,armbian-config 安装docker,和apt 的方式都安装不了, 不清楚为什么
然后尝试更新内核armbian-sync 成功, armbian-update也卡住
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/68504ab8-5584-41d8-b247-6c0328a3082e)
,所以我该如何解决或者是得重新u盘开始弄吗,还是哪个步骤有问题了

tailscale:命令行:
```
# Add Tailscale's GPG key
sudo mkdir -p --mode=0755 /usr/share/keyrings
curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg | sudo tee /usr/share/keyrings/tailscale-archive-keyring.gpg >/dev/null
# Add the tailscale repository
curl -fsSL https://pkgs.tailscale.com/stable/debian/bullseye.tailscale-keyring.list | sudo tee /etc/apt/sources.list.d/tailscale.list
# Install Tailscale
sudo apt-get update && sudo apt-get install tailscale
# Start Tailscale!
sudo tailscale up
```

**Comment by ADolphin-02** [comment]
armbian-docker的执行结果
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/36e22c2e-d62a-4695-9f82-9c09d26ee427)

**Comment by ophub** [comment]
从banner界面看你用的是noble分支，从你使用的命令看却使用bullseye的三方库，整叉皮了，把软件源整蒙圈了。

**Comment by ADolphin-02** [comment]
> 从banner界面看你用的是noble分支，从你使用的命令看却使用bullseye的三方库，整叉皮了，把软件源整蒙圈了。

那我需要怎么处理呢大佬，我现在没能区分出来

**Comment by ophub** [comment]
你的命令：https://pkgs.tailscale.com/stable/debian/`bullseye`.noarmor.gpg

你的armbian系统: `noble`

要用和系统一致的第三方软件源

**Comment by ADolphin-02** [comment]
> 你的命令`bullseye` ：https://pkgs.tailscale.com/stable/debian/bullseye.noarmor.gpg
> 
> 你的armbian系统: `noble`
> 
> 要用和系统一致的第三方软件源

嗯嗯，我知道了，现在最好的解决方案是重新弄个bullseye的系统是吗

**Comment by ADolphin-02** [comment]
麻烦您了，谢谢
