### ISSUE TITLE
403A  S905L3-B  没法从u盘启动刷入armbian。有没有大佬给点资料。有偿。基本上dtb都试过了

### ISSUE THREAD

**Issue by Wss-20170929** [ophub/amlogic-s9xxx-armbian#2319]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by whmzsu** [comment]
你的问题都没说清楚，到底是没法U盘启动，还是U盘启动刷不了emmc

**Comment by Wss-20170929** [comment]
u盘启动黑屏了 。但是没有获取到ip 交换机上灯也没亮

**Comment by b2522** [comment]
> 你的问题都没说清楚，到底是没法U盘启动，还是U盘启动刷不了emmc

我的没法从U盘启动，用了优盘，会进入到恢复模式，请指点哈。

**Comment by whmzsu** [comment]
> u盘启动黑屏了 。但是没有获取到ip 交换机上灯也没亮

试试 把 boot 分区里面的  u-boot-s905x-s912.bin 复制为 u-boot.ext，然后看看，这个主要问题是网卡的驱动，当前hdmi是无论如何都无法驱动的。

**Comment by b2522** [comment]
> > > 你的问题都没说清楚，到底是没法U盘启动，还是U盘启动刷不了emmc
> > 
> > 
> > 我的没法从U盘启动，用了优盘，会进入到恢复模式，请指点哈。
> 
> 如果 reboot update 无法进入到U盘启动的话，比较难解决，不过有个歪门邪道，用emuelec的启动u盘试试，不管能不能启动，然后再试试armbian的

谢谢指导！后来我解决了这个问题，是插入优盘的时机晚了，应该点完U盘重启之后，就可以插了，不要在出现安卓启动画面之后插入。

**Comment by b2522** [comment]
> > u盘启动黑屏了 。但是没有获取到ip 交换机上灯也没亮
> 
> 试试 把 boot 分区里面的 u-boot-s905x-s912.bin 复制为 u-boot.ext，然后看看，这个主要问题是网卡的驱动，当前hdmi是无论如何都无法驱动的。

大神，再请教一下，我已经成功刷好armbian了，用同样的方法，刷Openwrt，选了好几个l3b的包，也 复制了u-boot-s905x-s912.bin 为 u-boot.ext，就是没法在路由器下看到设备。

**Comment by ophub** [comment]
op默认ip是固定的，192.168.1.1
用户名root
密码password

你把自己的电脑手动改IP到192.168.1.x相同网段，网线直连盒子就可以进入管理界面
这些操作在仓库的文档里有写。

**Comment by b2522** [comment]
> op默认ip是固定的，192.168.1.1 用户名root 密码password
> 
> 你把自己的电脑手动改IP到192.168.1.x相同网段，网线直连盒子就可以进入管理界面 这些操作在仓库的文档里有写。

谢谢大神！我以为是和armbian一样的方法，是我肤浅了。
