### ISSUE TITLE
Seewo sv21 bug

### ISSUE THREAD

**Issue by mudebug77** [ophub/amlogic-s9xxx-armbian#2321]
**Device Information | 设备信息**
Seewo sv21

**Armbian Version | 系统版本**
Armbian_24.5.0_rockchip_seewo-sv21_noble_6.1.87_server_2024.05.03.img

**Describe the bug | 问题描述**
无法识别usb3.0，usb2.0正常，无法双网口联网，会重启

我刷openwrt-05.04.2024-rockchip-armv8-seewo_sv21-rk3568系统如果同时插入2个网线，
大概10秒左右就会重启一次不知道为什么

其他人你的镜像Armbian_23.08.0-trunk_Rk3568-sv_jammy_current_6.1.53_v1.2.img_2
他可以识别到usb3.0 但是不能重启，如果插着usb3.0启动则会自动进入 loader 模式
如果要重启得先把usb3.0拔下来，开机，进入系统后再插usb3.0接口才可以

我下过其他人的openwrt系统，他似乎直接屏蔽了复位键功能，（他无法通过长按复位键进loader模式）
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34656102/874db769-98be-4b14-8e0c-5746d06899d8)

**Comment by ophub** [comment]
你问的2个系统都是别处下的，你到下载的地方问问。
另外你说的2个网卡插着重启也不知道你说的是op还是armbian，op的话去网络-接口里修改，是wan+lan分别选对网卡设置协议

**Comment by mudebug77** [comment]
我是在这里下载的armbian 产生的问题，另外2个也不那么正常的意思
Armbian_24.5.0_rockchip_seewo-sv21_noble_6.1.87_server_2024.05.03.img这个文件是在[Releases](https://github.com/ophub/amlogic-s9xxx-armbian/releases) 下的，

op插2个网线就会重启，插入进去他默认就会一个wan一个lan，但是会重启。

**Comment by itoywh** [comment]
楼主你好，我也是seewo sv21安装armbian和Openwrt也都遇到了一些问题，方便留个v，相互讨论下么。看起来一直是dts文件有问题

**Comment by mudebug77** [comment]
你还是把你v给我，比较适合
