### ISSUE TITLE
armbian-software

### ISSUE THREAD

**Issue by gsjz20** [ophub/amlogic-s9xxx-armbian#2322]
**Armbian Version | cm311-1a**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [[Armbian_24.5.0_amlogic_s905l3a_noble_5.15.156_server_2024.05.03.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.05/Armbian_24.5.0_amlogic_s905l3a_noble_5.15.156_server_2024.05.03.img.gz)]

**Describe the bug | 问题描述**
root@armbian:~# armbian-software
[ STEPS ] Start installing the necessary dependencies...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudoers is owned by uid 1023, should be 0
sudo: error initializing audit plugin sudoers_audit
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudoers is owned by uid 1023, should be 0
sudo: error initializing audit plugin sudoers_audit
[ ERROR ] Dependency installation failed, stop install.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

各位是怎么解决的 安装了好几次都是这样

**Comment by ophub** [comment]
不要把armbian系统U盘插在安卓系统上，插入即废。 U盘中的armbian被安卓系统改了权限废了，重刷U盘，先断电再插U盘。

**Comment by gsjz20** [comment]
> 不要把armbian系统U盘插在安卓系统上，插入即废。 U盘中的armbian被安卓系统改了权限废了，重刷U盘，先断电再插U盘。

断电的时候插入盒子 还是一样的 可能是废了

**Comment by ophub** [comment]
重新刷U盘，之前的已经废了。

**Comment by zhangzhenhu** [comment]
卧槽，还能这样的。。。踩坑了。。。

**Comment by Kalpeny** [comment]
卧槽，居然还有这种坑，辛苦作者提示一下
