### ISSUE TITLE
radxa rock5c(rk3588s) & e20c(rk3528) 交流贴

### ISSUE THREAD

**Issue by ophub** [ophub/amlogic-s9xxx-armbian#2324]
今天从 [unifreq/openwrt_packit](https://github.com/unifreq/openwrt_packit) 的仓库复制了 radxa rock5c(rk3588s) & e20c(rk3528) 设备的u-boot及相关文件。还原有设备的朋友测试反馈。

**Comment by windskyxb** [comment]
> 今天从 [unifreq/openwrt_packit](https://github.com/unifreq/openwrt_packit) 的仓库复制了 radxa rock5c(rk3588s) & e20c(rk3528) 设备的u-boot及相关文件。还原有设备的朋友测试反馈。

radxa rock 5c lite（3582）有考虑支持吗

**Comment by wwzcoolguitar** [comment]
请教大佬，rock5c 3588S2 和rock5c 3588S 通用吗？ 刷了op后，没有vim vi命令，会报错（第二张照片），改不了IP。而且用无线键盘输入命令时，屏幕不显示输入的内容，只能盲打，不知道是哪里的问题，请大佬看看
![Uploading 微信图片_20240702165230.jpg…]()

**Comment by wwzcoolguitar** [comment]
![微信图片_20240702165158](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110992554/f6f01b38-83e4-4924-90e7-21abeadaa719)

**Comment by wwzcoolguitar** [comment]
TF卡安装的系统
![微信图片_20240702165230](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110992554/cb0d615c-491b-4950-95b8-1bf3ae3d4126)

**Comment by yanquan2020** [comment]
e20c(rk3528)的usb2口不识别。

**Comment by ophub** [comment]
多谢反馈，你的问题我转给f大，他刚才已经修好了： https://github.com/unifreq/linux-5.10.y-rk35xx/commit/14403cd8e363f3aaf34ed1bf5b331983544bb192

我启动了在线编译内核的Actions，编译要一个小时。你看ACtions结束后，到rk35xx的tags里下载最新上传的内核，解压dtb-rockchip-xxx.tar.gz这个包，把里面的/rk3528-radxa-e20c.dtb文件覆盖你e20c本地/boot/dtb/rockchip里面的同名文件。

**Comment by ophub** [comment]
@wwzcoolguitar 你用ssh进入，或者在登陆后的ttyd里面执行命令。使用显示屏显示不完整的话不方便看。

**Comment by wwzcoolguitar** [comment]
> @wwzcoolguitar 你用ssh进入，或者在登陆后的ttyd里面执行命令。使用显示屏显示不完整的话不方便看。

大佬，192.168.1.1连接不上。主路由是192.168.1.3  旁路由刷的这个系统用192.168.1.1连接没反应，用网页进不去，ssh也连不上。麻烦大佬给看看

**Comment by zhangenine** [comment]
目前的版本usb用不了

**Comment by ophub** [comment]
你更新下新内核

**Comment by zhangenine** [comment]
E20C是rk3528 我看只有5.10.160的内核

**Comment by zhangenine** [comment]
可以了 感谢

**Comment by jreeybin** [comment]
E20C怎么能改到新的内核6.1.75

**Comment by ophub** [comment]
armbian-update -k 6.1.75

**Comment by jreeybin** [comment]
6.1.75 不是OPENWRT的内核吗？

**Comment by espuppet** [comment]
借地请教下，cpu 温度查不到，需要怎么配置啊？用的 6.1.75 的内核

```
~$ cat /etc/armbianmonitor/datasources/soctemp
cat: /etc/armbianmonitor/datasources/soctemp: No such file or directory
```

**Comment by MrChenhtlss** [comment]
有考虑支持 Radxa2A 吗，SOC是RK3528A

**Comment by JIYangYhs** [comment]
<img width="975" height="698" alt="Image" src="https://github.com/user-attachments/assets/5d28a685-69c3-4bae-bfaf-dbdeaacf66a3" />

文件夹创建总是现实权限不足，重启后仍然不能解决。尝试更新内核也不行

**Comment by ophub** [comment]
fnnas 有 2 个系统功能是依赖（FNOS 内核）的，一个是 (文件回收站)，一个是给多用户的 (文件权限管理)。关于这 2 个问题我已经拿到官方编译好的内核了，我测试好了就替换重新打包。

我在 ophub/fnnas 仓库交流区置顶了这个问题了。

**Comment by 1319107006** [comment]
中兴云电脑W132D 有考虑支持吗
RK3528-2+32G，有个USB3.0可以挂硬盘，感觉比大多数电视盒子合适
