### ISSUE TITLE
申请适配 众云世纪RK3288-ZYBOX08 开发板

### ISSUE THREAD

**Issue by w2xg2022** [ophub/amlogic-s9xxx-armbian#2327]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3] RK3288
 - Model [e.g. HK1] 众云世纪RK3288-ZYBOX08

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100] Armbian_24.5.0_rockchip_renegade-rk3328_noble_6.1.91_server_2024.05.17.img
 - Release: [e.g. jammy/bullseye] Armbian_24.5.0_rockchip_renegade-rk3328_noble_6.1.91_server_2024.05.17.img

**Describe the bug | 问题描述**
![微信图片_20240521104138](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/d75e6d26-1e60-4787-9d06-10b8e07b4710)
![微信图片_20240521104132](https://github.com/ophub/amlogic-s9xxx-armbian/assets/110317133/3b5eb118-9790-4d1d-b738-ad296506125e)
[ZY-RK3288规格说明书.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/15383861/ZY-RK3288.pdf)

众云世纪RK3288-ZYBOX08硬件基本和Firefly-RK3288
https://www.t-firefly.com/doc/download/4.html
一致，手上拿到的是2.3版；Firefly Ubuntu18.04固件
https://pan.baidu.com/s/1OMP9tWEJW1FaAGNzA19pbA?pwd=1234
Ubuntu ->Ubuntu18.04 ->Public，FIREFLY-RK3288-UBUNTU18.04-GPT-20201102-1452.img.7z
也能用RKDevTool写入并正常运行

拿O大编译的Armbian_24.5.0_rockchip_renegade-rk3328_noble_6.1.91_server_2024.05.17.img：
1、写入U盘，原厂安卓7.1 adb reboot sdupdate/adb reboot update，reboot重启后感觉都是不识别U盘然后进了安卓；
2、RKDevTool直接写入上面.img，没有任何开机画面，路由器也找不到IP，直接"没有发现设备“（需要MASKROM模式救砖）。

请教O大，后面如果要适配，需要再提供那些文档或信息，或需要哪些配合。谢谢。

**Comment by w2xg2022** [comment]
补充：
Firefly-RK3288 Ubuntu18.04固件，内核是4.4.194不支持docker，github上有人编译出支持docker的boot.img、kernel.img、resource.img、zboot.img，把zboot改名boot.img重新打包固件（需要配合修改parameter.txt），刷入RK3288-ZYBOX08是可以顺利运行docker的。

https://github.com/Pengunix/firefly_rk3288_docker_kernel

**Comment by w2xg2022** [comment]
再补充：
曾经用https://wiki.t-firefly.com/zh_CN/AIO-3288J/linux_compile.html这里的Firefly_Linux_SDK 源码包，kernel替换为https://github.com/rockchip-linux/kernel/tree/develop-4.4这里的，可以得到和上面类似的结果（可以运行docker）。

https://github.com/rockchip-linux/kernel/tree/develop-4.4
的dts、dtsi应该可以参考

**Comment by baohudan** [comment]
Armbian_21.05.0-trunk_Rk3288_buster_current_5.10.27_xfce_desktop.img 我用的是这个版本，wifi和有线都可以使用，屏幕无显示，usb不能使用。是把映像释放到tf卡上使用的

**Comment by tvp8630** [comment]
众云世纪RK3288-ZYBOX08。RKDevTool直接写入固件后，没有任何开机画面，路由器也找不到IP，直接"没有发现设备“，怎么进入MASKROM模式

**Comment by baohudan** [comment]
按那个按钮发自我的 iPhone在 2025年3月18日，13:40，tvp8630 ***@***.***> 写道：﻿
  众云世纪RK3288-ZYBOX08。RKDevTool直接写入固件后，没有任何开机画面，路由器也找不到IP，直接"没有发现设备“，怎么进入MASKROM模式—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>



tvp8630 left a comment (ophub/amlogic-s9xxx-armbian#2327)
众云世纪RK3288-ZYBOX08。RKDevTool直接写入固件后，没有任何开机画面，路由器也找不到IP，直接"没有发现设备“，怎么进入MASKROM模式

**Comment by use2008qq** [comment]
[    0.000000] Linux version 4.4.189 (rpdzkj@rpdzkj) (gcc version 6.3.1 20170404 (Linaro GCC 6.3-2017.05) ) #16 SMP Wed Aug 4 11:03:52 CST 2021
[    0.000000] CPU: ARMv7 Processor [410fc0d1] revision 1 (ARMv7), cr=10c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] Machine model: rockchip,king-rp3288-act8846
刷荣品的RK3288固件，USB是可以用的，WIFI蓝牙没测试。  这是BUILDROOT固件：通过网盘分享的文件：update-king-rp3288-buildroot-hdmi-20210805-203237.img  （默认是ssh， 账号rpdzkj 密码rpdzkj， 也可以进HDMI后使用键盘修改。）
链接: https://pan.baidu.com/s/1o6Xbgtqp7xm8RcRpARcUEA 提取码: 5566 
这是荣品RK3288的LINUX SDK, 通过网盘分享的文件：linux
链接: https://pan.baidu.com/s/1a0xOWD7oP5KxABwledYF2w?pwd=5566 提取码: 5566    ，需要研究源码的可以查看SDK

**Comment by baohudan** [comment]
多谢分享




包
***@***.***
