### ISSUE TITLE
How to boot armbian on tx3 mini s905W2

### ISSUE THREAD

**Issue by anhkhang2304** [ophub/amlogic-s9xxx-armbian#233]
I use Armbian_22.05.0_Aml_s905w_focal_5.15.26_2022.03.05.1409.img.gz to flash. I think the version I am using is not suitable for the chip s905w2. Can you suggest me a more suitable version? Thank you.
This is a new chip(CPU) manufactured in 2022. I think it needs tweaking to be able to boot with armbiam!

**Comment by ophub** [comment]
Use the s905w firmware of 5.4 for testing, as long as the dtb is suitable, it can be used.
Do not use firmware above 5.10+

**Comment by anhkhang2304** [comment]
Ok, I'll test it. Many thanks

**Comment by jayavanth** [comment]
@anhkhang2304 did it work?

**Comment by anhkhang2304** [comment]
@jayavanth No, It's still not working

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/56d72de37c37875d0cf92beb66e9dccfefce636b/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L28

**Comment by xuantrandev** [comment]
i think you are using the tx3-mini **PLUS**, it use S905W2 chip. did you success to boot it with armbian?
