### ISSUE TITLE
在armbian下面使用sane扫描---不是bug

### ISSUE THREAD

**Issue by jamesbondjava** [ophub/amlogic-s9xxx-armbian#2330]
1.运行`apt-get install sane sane-utils`
2.运行'scanimage -L'  显示有较多设备（办公环境），不知道如何指定打印机
3.运行'scanimage -d hpaio:/usb/HP_LaserJet_Pro_MFP_M126a?serial=CNBRP9KDKL >/tmp/test.pnm'  
然后就会提示：scanimage: open of device hpaio:/usb/HP_LaserJet_Pro_MFP_M126a?serial=CNBRP9KDKL failed: Error during device I/O

想请大佬帮忙解决一下。

**Comment by w2xg2022** [comment]
之前在OP系统中碰到过，百度之后发现打印机（扫描器）不支持sane，这里可以查询。
http://www.sane-project.org/sane-supported-devices.html

**Comment by jamesbondjava** [comment]
@w2xg2022 不过我之前在桌面端的Ubuntu上面尝试过，惠普官方的Linux客户端以及很多基于sane的扫描软件都是可以驱动的（主要是天天开着一个台式机，觉得太浪费），我个人并不是特别确定是sane本身不支持的原因。

**Comment by LondyGhost** [comment]
你安装cups啊

**Comment by jamesbondjava** [comment]
@LondyGhost cups是打印服务相关的，已经安装了。现在需要一体机的扫描功能。
