### ISSUE TITLE
s905l3 cm311-1 无法启动

### ISSUE THREAD

**Issue by lsf343634352** [ophub/amlogic-s9xxx-armbian#2332]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 - Model [CM311-1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.31]
 - Release: [e.g. jammy]

用6.6.31版本刷入armbian,总是启动不起来,错误提示有
done.
Begin: Mounting root file system ... Begin: Running /scripts/local-top ... done.
Begin: Running /scripts/local-premount ... Scanning for Btrfs filesystems
done.
Begin: Waiting for root file system ... [    8.256890] scsi 0:0:0:0: Direct-Access     Mass     Storage Device   1.00 PQ: 0 ANSI: 0 CCS
[    8.266515] sd 0:0:0:0: [sda] 15269888 512-byte logical blocks: (7.82 GB/7.28 GiB)
[    8.268788] sd 0:0:0:0: [sda] Write Protect is off
[    8.273483] sd 0:0:0:0: [sda] No Caching mode page found
[    8.278527] sd 0:0:0:0: [sda] Assuming drive cache: write through
[    8.290795]  sda: sda1 sda2
[    8.292512] sd 0:0:0:0: [sda] Attached SCSI removable disk
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
Begin: Running /scripts/local-block ... done.
done.
Gave up waiting for root file system device.  Common problems:
 - Boot args (cat /proc/cmdline)
   - Check rootdelay= (did the system wait long enough?)
 - Missing modules (cat /proc/modules; ls /dev)
ALERT!  UUID=eacdd80d-75c8-4601-8cb5-b91d65927a0a does not exist.  Dropping to a shell!

搞不懂哪里的问题,经常性报这个错误
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/58645284/eb68a051-3a83-4dd8-8863-2113097d6b17)

**Comment by ophub** [comment]
从仓库首页，点这个设备的链接进去看看之前大家的讨论，就会了
