### ISSUE TITLE
armbian如何安装内核模块？apt install linux-modules-extra-`uname -r`

### ISSUE THREAD

**Issue by 11642509** [ophub/amlogic-s9xxx-armbian#2333]
Device Information | 设备信息

SOC: [rk3566]
Model [荐片盒子 JPBOX]
Armbian Version | 系统版本

Kernel Version: [Armbian OS 24.5.0 Bullseye with Linux 6.1.86-ophub]
Release: [bullseye]

apt install linux-modules-extra-`uname -r`
modprobe binder_linux devices="binder,hwbinder,vndbinder"

Describe the bug |手头盒子性能还行，想通过redroid方案跑android 但是需要安装内核扩展模块，请问有没有方法能安装扩展，或者自己编译的介绍方法之类的

**Comment by ophub** [comment]
内核里有了

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-6.1#L8179-L8185
