### ISSUE TITLE
IPV6异常问题

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2334]
**Device Information | 设备信息**
 - SOC: [e.g. S095w]
 - Model [e.g. TX3 mini]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.31    6.1.191]
 - Release: [e.g. bookworm_6.6.31_server_2024.05.18]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.

IPv6 不能自动更新 

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
我的第一级是OPENWRT路由器，第二级是ARMBIAN盒子，当路由器PPPOE重新拨号后，ARMBIAN 不能访问IPV6网址，armbian的IPV6是自动DHCP的，重新拨号之前是正常的。IPv6 不能自动更新，与时间无关，等多长时间也不能恢复。同一局域中的电脑IPV6始终是正常，说明与路由器无关。ARMBIAN盒子的IPV4是正常的，断线重拨号后没有问题。当我执行dhclient -6 或者 systemctl restart NetworkManager都可以恢复IPV6的访问，但是是什么原因呢？IPV4不受影响

root@armbian:~# ping www.qq.com
PING www.qq.com (111.30.178.240): 56 data bytes
64 bytes from 111.30.178.240: icmp_seq=0 ttl=53 time=27.068 ms
^C--- www.qq.com ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max/stddev = 27.068/27.068/27.068/0.000 ms
root@armbian:~# ping6 www.qq.com
PING www.qq.com (2409:8702:4860:1002::33): 56 data bytes
64 bytes from 2409:8702:4860:1002::33: icmp_seq=0 ttl=54 time=22.354 ms
64 bytes from 2409:8702:4860:1002::33: icmp_seq=1 ttl=54 time=22.959 ms
^C--- www.qq.com ping statistics ---
2 packets transmitted, 2 packets received, 0% packet loss
round-trip min/avg/max/stddev = 22.354/22.657/22.959/0.303 ms
root@armbian:~# ping6 www.qq.com
PING ins-r23tsuuf.ias.tencent-cloud.net (2409:8702:4860:1002::33): 56 data bytes
64 bytes from 2409:8a04:4020:cf70::1: Destination unreachable: No route to destination
64 bytes from 2409:8a04:4020:cf70::1: Destination unreachable: No route to destination

**Comment by goldsoft8888** [comment]
Armbian_24.5.0_amlogic_s905w_noble_6.6.31_server_2024.05.18   这个版本正常

**Comment by goldsoft8888** [comment]
armbian 官方社区版bookworm存在同样问题，

**Comment by goldsoft8888** [comment]
本网站的24.8.0 noble，ping 不通自己的ipv6，奇怪问题很多啊。

**Comment by JackieJK** [comment]
不是 怎么标为completedl了

**Comment by akaet** [comment]
路由器的DHCPv6开了没？
