### ISSUE TITLE
小宝xiaobaonas SATA用不了好像是你dts/dtb设备树的原因

### ISSUE THREAD

**Issue by Lemon1151** [ophub/amlogic-s9xxx-armbian#2335]
你那个dtb执行dmesg | grep pci会提示pcie训练超时，如图：
![{3F28D497-E70B-45ce-9176-9E8A79ABC138}](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/5237d2a9-a0a9-4795-a8f6-df88116c7d8d)
这是另外的dts编译的dtb执行的dmesg | grep pci，如图：
![{C648F923-5657-494c-BC8D-61F4C4D7D15F}](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149338935/1352109c-0031-4a5e-9b9b-b3bb32957409)

**Comment by ophub** [comment]
分享一下你的dts

**Comment by Lemon1151** [comment]
> 分享一下你的dts

[rk3399-xiaobao-nas.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/15440917/rk3399-xiaobao-nas.zip)

**Comment by ophub** [comment]
[rk3399-xiaobao.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/15441282/rk3399-xiaobao.dtb.zip)

感谢你的分享，我把这个dts放在6.1.y和6.6.y的源码里测试了下，都可以正常编译。上面链接里的是6.6.y内核下编译的，我看到你现在使用的就是6.6.y的内核，你再测试下这个dtb是否使用正常。（注意这个名字和你发的不一样，没-nas这个字，你改下/boot/armbianEnv.txt里的名字测试下），反馈下你的测试结果。

你的这个dts文件，我可以提交到f大的内核仓库吗？我的armbian/openwrt都是使用的他的内核，提交到上游使用比较方便。

**Comment by Lemon1151** [comment]
> [rk3399-xiaobao.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/15441282/rk3399-xiaobao.dtb.zip)
> 
> 感谢你的分享，我把这个dts放在6.1.y和6.6.y的源码里测试了下，都可以正常编译。上面链接里的是6.6.y内核下编译的，我看到你现在使用的就是6.6.y的内核，你再测试下这个dtb是否使用正常。（注意这个名字和你发的不一样，没-nas这个字，你改下/boot/armbianEnv.txt里的名字测试下），反馈下你的测试结果。
> 
> 你的这个dts文件，我可以提交到f大的内核仓库 https://github.com/unifreq 吗？我的armbian/openwrt都是使用的他的内核，提交到上游使用比较方便。
测试了没问题，可以正常开机进系统，pcie也能正常启用，可以用SATA。可以提交到内核仓库里

**Comment by ophub** [comment]
3q
