### ISSUE TITLE
seewo sv21 无法启动

### ISSUE THREAD

**Issue by Xueling2077** [ophub/amlogic-s9xxx-armbian#2336]
**Device Information | 设备信息**
 - SOC: rk3568b2
 - Model seewo-sv21

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.91
 - Release: Armbian_24.5.0_rockchip_seewo-sv21_bookworm_6.1.91_server_2024.05.18
**Describe the bug | 问题描述**
archlinux下使用rkdeveloptool刷入loader以及img文件后无法启动

[yuki@archlinux ~]$ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 03f0:194a HP, Inc HP Wireless Slim Keyboard - Skylab
Bus 001 Device 003: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 006: ID 067b:23a3 Prolific Technology, Inc. ATEN Serial Bridge
Bus 001 Device 014: ID 2207:350a Fuzhou Rockchip Electronics Company 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
[yuki@archlinux ~]$ rkdeveloptool db rk356x_spl_loader_ddr1056_v1.12.109_no_check_todly.bin                   Downloading bootloader succeeded.
[yuki@archlinux ~]$ rkdeveloptool wl 0 Armbian_24.5.0_rockchip_seewo-sv21_bookworm_6.1.91_server_2024.05.18.img 
Write LBA from file (100%)

emmc信息
![20240525_143916](https://github.com/ophub/amlogic-s9xxx-armbian/assets/139438669/90e35bab-ee76-4507-b917-afa9dac1c36d)
ttl
[Uploading seewo-sv21-emmcboot.txt…]()

**Comment by Xueling2077** [comment]
[seewo-sv21-emmcboot.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/15442149/seewo-sv21-emmcboot.txt)

**Comment by Xueling2077** [comment]
有时候把镜像DD到u盘可以从usb启动 但是lsblk没有mmc设备

**Comment by Xueling2077** [comment]
另一台可以启动的
[0_seewo-sv21-emmcboot.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/15442297/0_seewo-sv21-emmcboot.txt)

**Comment by Xueling2077** [comment]
无法从emmc启动但是usb可以
[seewo-sv21-usbboot.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/15442369/seewo-sv21-usbboot.txt)

**Comment by ophub** [comment]
loader换个版本再试试

**Comment by Xueling2077** [comment]
> loader换个版本再试试

状况还是一样
