### ISSUE TITLE
cm201-1 s905l3，配置1+8，可用内存794M  

### ISSUE THREAD

**Issue by y80234567** [ophub/amlogic-s9xxx-armbian#2338]
![8b865d0e1110b2192bf7bfa4bbd20c7](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38968720/56cdce37-4b6b-4723-87f5-5fc56bd37f63)
u盘写入Armbian_24.5.0_amlogic_s905l2_bullseye_5.15.156_server_2024.05.03.img
写入正常，网卡正常，内存显示794M  hdmi不显示
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/38968720/673f5980-316f-433e-807d-196d824fa937)
使用op大佬的s905l2和s905l3原包，选择117，ext4写入emmc，选择121号 cm211，ext4写入emmc都可以启动，可用内存都是794M，小白求教，这个是什么问题，

**Comment by ophub** [comment]
根据你的盒子，选择相似的u-boot复制一个，方法看仓库的文档
