### ISSUE TITLE
OP大大，请求帮忙修复下typec无法使用的问题。

### ISSUE THREAD

**Issue by kesry** [ophub/amlogic-s9xxx-armbian#2339]
不是sw799，但是固件刷的ophub上的 Armbian_24.5.0_rockchip_sw799_jammy_5.15.152_server_2024.03.16.img 可以开机，但是typec和pcie无法正常使用，typec插入OTG typec的线之后，不识别插入的设备，甚至设备上的电源灯都不亮。
原固件的dtb和 \sys\firmware\devicetree\base目录已上传到github，小白搞不定这个板子，求帮忙，谢谢。
`[https://github.com/kesry/rk3399_nvme](https://github.com/kesry/rk3399_nvme)`

**Comment by kesry** [comment]
原固件下载地址，https://cloud.189.cn/t/EvYvQbR7vuAf （访问码：oab4）
他这个的boot分区很奇怪，不是正常的linux的boot分区，而是一个android格式的分区，但是rootfs是一个debian 9的rootfs，lib/modules下面没有任何东西

**Comment by kesry** [comment]
boot下载地址 https://cloud.189.cn/t/FfQbiavMnE3q （访问码：il7y）

**Comment by Lemon1151** [comment]
什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz

**Comment by kesry** [comment]
> 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz

设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 
https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb
，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了

**Comment by kesry** [comment]
> > 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz
> 
> 设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 [https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb](https://github.com/kesry/rk3399_nvme%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84rk3399_nvme.dtb%E7%9A%84%E5%B0%B1%E6%98%AF%E5%8E%9Fdtb) ，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了

[https://github.com/kesry/rk3399_nvme](https://github.com/kesry/rk3399_nvme)

**Comment by Lemon1151** [comment]
> > > 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz
> 
> > 
> 
> > 设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 [https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb](https://github.com/kesry/rk3399_nvme%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84rk3399_nvme.dtb%E7%9A%84%E5%B0%B1%E6%98%AF%E5%8E%9Fdtb) ，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了
> 
> 
> 
> [https://github.com/kesry/rk3399_nvme](https://github.com/kesry/rk3399_nvme)

你刷这个fine3399的固件，进入系统执行lspci看看有没有报错

**Comment by kesry** [comment]
> > > > 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz
> > 
> > 
> > > 
> > 
> > 
> > > 设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 [https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb](https://github.com/kesry/rk3399_nvme%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84rk3399_nvme.dtb%E7%9A%84%E5%B0%B1%E6%98%AF%E5%8E%9Fdtb) ，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了
> > 
> > 
> > https://github.com/kesry/rk3399_nvme
> 
> 你刷这个fine3399的固件，进入系统执行lspci看看有没有报错

我的话应该要等到洗个礼拜了，这板子现在不在我旁边，另一个同款板子的人刷的sw799的固件，执行没报错，但是也没输出

**Comment by kesry** [comment]
> 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz


这个链接打不开了

**Comment by kesry** [comment]
> > > > 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz
> > 
> > 
> > > 
> > 
> > 
> > > 设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 [https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb](https://github.com/kesry/rk3399_nvme%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84rk3399_nvme.dtb%E7%9A%84%E5%B0%B1%E6%98%AF%E5%8E%9Fdtb) ，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了
> > 
> > 
> > https://github.com/kesry/rk3399_nvme
> 
> 你刷这个fine3399的固件，进入系统执行lspci看看有没有报错

lspci没有报错，但是typec和nvme的问题依旧，typec没有工作，插上去的设备的电源灯未点亮。

**Comment by kesry** [comment]
> > > > 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz
> > 
> > 
> > > 
> > 
> > 
> > > 设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 [https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb](https://github.com/kesry/rk3399_nvme%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84rk3399_nvme.dtb%E7%9A%84%E5%B0%B1%E6%98%AF%E5%8E%9Fdtb) ，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了
> > 
> > 
> > https://github.com/kesry/rk3399_nvme
> 
> 你刷这个fine3399的固件，进入系统执行lspci看看有没有报错

lspci没有报错，但是typec和nvme的问题依旧，typec没有工作，插上去的设备的电源灯未点亮。

**Comment by kesry** [comment]
> > > > 什么设备？有没有现成的dtb/dts？？你可以试试fine3399的固件https://github.com/Lemon1151/rk3399-armbian/releases/download/Armbian_jammy_save_2024.06/Armbian_24.8.0_rockchip_fine3399_jammy_6.6.32_server_2024.06.01.img.gz
> > 
> > 
> > > 
> > 
> > 
> > > 设备我也不知道是啥，dtb有原dtb，在我上面发的github的链接里面 [https://github.com/kesry/rk3399_nvme，里面的rk3399_nvme.dtb的就是原dtb](https://github.com/kesry/rk3399_nvme%EF%BC%8C%E9%87%8C%E9%9D%A2%E7%9A%84rk3399_nvme.dtb%E7%9A%84%E5%B0%B1%E6%98%AF%E5%8E%9Fdtb) ，但是没config，fine3399的固件也试过了，和sw799的固件一样，外设用不了
> > 
> > 
> > https://github.com/kesry/rk3399_nvme
> 
> 你刷这个fine3399的固件，进入系统执行lspci看看有没有报错

lspci没有报错，但是typec和nvme的问题依旧，typec没有工作，插上去的设备的电源灯未点亮。
