### ISSUE TITLE
江苏移动白色创维E900V21C(S905L)刷写成功，只是U盘启动时显示器无影像，这点折腾我一天，一直以为底包有问题。

### ISSUE THREAD

**Issue by Jstzo2u** [ophub/amlogic-s9xxx-armbian#2341]
**Device Information | 设备信息**
 - SOC: [S905L]
 - Model [E900V21C]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.156-ophub]
 - Release: [Armbian_24.5.0_amlogic_s905l_jammy_5.15.156_server_2024.05.03.img]

**Describe the bug | 问题描述**
此盒子需要用meson-gxl-s905l-venz-v10.dtb来进行引导，U盘卡载启动时显示器会无响应，需要等待很长一段时间。
这点折腾死我了，有带root的线刷包就下载，然后刷，下载刷..........emmc存储，可刷入。
盒子WiFi不知道驱动上没有，有图，不会看。剩下就没什么了，希望对O大有帮助。
在此，给后续想给这款盒子刷机的小伙伴，来进行一下指引。

**附上图片**

![QQ截图20240531214858](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131769500/62184b21-270b-4ac1-95ff-9ee53bb0cb19)

![QQ截图20240531215902](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131769500/931925c4-e738-4120-9e7e-43b4fd2d6fcc)

**盒子正面**

![正面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131769500/7fa9b77f-6900-4dd7-8036-793835f9acc0)

**盒子背面**

![背面](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131769500/d3470568-e8a5-4fa6-9f11-5db7776dc9f4)

**芯片**

![芯片](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131769500/30d7b09b-9f80-4b64-90f3-96735a9b29bf)

----------------------------------------------------------分割线------------------------------------------------------
24/06/01更新
**Device Information | 设备信息**
 - SOC: [S905L]
 - Model [E900V21C]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.91-ophub]
 - Release: [Armbian_24.5.0_amlogic_s905l_jammy_6.1.91_server_2024.05.17.img]

**Describe the bug | 问题描述**
测试用 **meson-gxl-s905x-p212.dtb** 也可以正常引导。更改了extlinux.conf.bak(不知是否有关)其它都不用改了，直接写入emmc

![QQ截图20240601093516](https://github.com/ophub/amlogic-s9xxx-armbian/assets/131769500/8593f6a0-3447-46e3-b0b8-987a7b56be84)

**Comment by ophub** [comment]
恭喜你
你使用的root的安卓系统分享个下载链接，我记录下这个设备，转存下安卓系统下载包。

**Comment by Jstzo2u** [comment]
上传了
链接：https://pan.baidu.com/s/1ybjKYIgATf5PlyC-QxK5uA?pwd=fpkc 
提取码：fpkc

**Comment by Jstzo2u** [comment]
root的安卓系统链接：**https://pan.baidu.com/s/1viqKGsUMem6VkH-doKlcUw?pwd=o8je** 

最后一次安装用的109，不知道和116有没有区别，但感觉109(meson-gxl-s905x-p212.dtb)更稳定。

**Comment by ophub** [comment]
都可以，109是公版配置

**Comment by YuTheGreat-ck** [comment]
![屏幕截图 2024-06-15 214915](https://github.com/ophub/amlogic-s9xxx-armbian/assets/86639242/cd1d8152-9c51-426c-890d-692e64de2e63)
山东联通创维盒子E00v21c 亲测可以刷Bookworm和jammy都可以完美刷入emcc我用的115刷入的的

**Comment by YuTheGreat-ck** [comment]
使用s905l-mg115

**Comment by YuTheGreat-ck** [comment]
E900V21C

**Comment by YuTheGreat-ck** [comment]
meson-gxl-s905L3b-p212.dtb

**Comment by YuTheGreat-ck** [comment]
唯一就是cpu温度一直显示2°C

**Comment by Hx0531** [comment]
![IMG_20240804_205411.jpg](https://github.com/user-attachments/assets/c1b54916-caa7-4b50-b56a-94f2073a4747)

![IMG_20240804_205355.jpg](https://github.com/user-attachments/assets/e64ed5f9-d4ec-4a43-b419-b007ce0b0525)

联通的这款E900V21C 拆机看芯片是s905l

然后刷armbian之后，显示没有网络![Image_1722772760435.jpg](https://github.com/user-attachments/assets/1fff8a5e-f2d5-4c8c-ad35-9b932d28f0df)

**Comment by ophub** [comment]
先换刷贴子里的安卓系统

**Comment by Hx0531** [comment]
好的o大 我试试

**Comment by Hx0531** [comment]
> 先换刷贴子里的安卓系统

![IMG_20240804_212706.jpg](https://github.com/user-attachments/assets/7adf3700-36f0-4786-a448-4c5cbb5e4ce8)

可以了 ,感谢O大，感谢楼主。安卓底包的问题，成功上车！

**Comment by Hx0531** [comment]
> > 先换刷贴子里的安卓系统
> 
> ![IMG_20240804_212706.jpg](https://github.com/user-attachments/assets/7adf3700-36f0-4786-a448-4c5cbb5e4ce8)
> 
> 可以了 ,感谢O大，感谢楼主。安卓底包的问题，成功上车！

我这款，刷入期间hdmi有跑码显示

**Comment by Aunixtoyou** [comment]
我也是进入了后屏幕一直黑屏，原来是正常的啊？？

**Comment by Xuhaoyu98** [comment]
o大帖子里的安卓4.4.5系统怎么u盘启动Armbian？外置启动启动不进去还是会进安卓系统 可以详细说一下吗？

**Comment by Xuhaoyu98** [comment]
o大帖子里的安卓4.4.2系统怎么u盘启动Armbian？外置启动启动不进去还是会进安卓系统 可以详细说一下吗？

**Comment by Xuhaoyu98** [comment]
> 先换刷贴子里的安卓系统

o大帖子里的安卓4.4.2系统怎么u盘启动Armbian？外置启动启动不进去还是会进安卓系统 可以详细说一下吗？

**Comment by hogner586** [comment]
青岛联通E900V21C刷机成功，但是刷openart的时候 晶晨宝盒不知道选择哪个安装 找不到E900V21C的对饮的目录，麻烦安装成功的给一个指示，那个型号是meson-gxl-s905l-venz-v10.dtb
![image](https://github.com/user-attachments/assets/55e4ad93-5418-4fce-8682-c6adf49a0238)

**Comment by kevinzwq** [comment]
> > 先换刷贴子里的安卓系统
> 
> ![IMG_20240804_212706.jpg](https://private-user-images.githubusercontent.com/176487887/354904709-7adf3700-36f0-4786-a448-4c5cbb5e4ce8.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQyNDM1NjQsIm5iZiI6MTczNDI0MzI2NCwicGF0aCI6Ii8xNzY0ODc4ODcvMzU0OTA0NzA5LTdhZGYzNzAwLTM2ZjAtNDc4Ni1hNDQ4LTRjNWNiYjVlNGNlOC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNVQwNjE0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MTZkNWYyZjVmZGIzZGRmYTE5MGJiMDU5MWExYmI5ZGQ2NjMyOTZiOTZjMzhkYmNmZDdmYWRjZTNlNzgyMjU4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.dftAaPhqFeabigBsNldNvWBCbHaPBOs29cyGV8BY6N4)
> 
> 可以了 ,感谢O大，感谢楼主。安卓底包的问题，成功上车！
大佬，我这边联通机顶盒创维E900V21C(S905L)先刷了armbian同样显示无网络，怎么重新刷回来安卓底包啊？

**Comment by hanxuelong321** [comment]
请问镜像烧录完后怎么修改引导？？小白不会弄啊

**Comment by llb608** [comment]
线刷不知道短接哪一个 反正不成功 u盘刷armbian卡到这个第八秒  还需要等吗
![Uploading MVIMG_20250115_235435.jpg…]()
![Uploading MVIMG_20250115_235435.jpg…]()

**Comment by llb608** [comment]
![MVIMG_20250115_235435](https://github.com/user-attachments/assets/ede25785-d756-4e0b-a3aa-9c6e72563c67)
![MVIMG_20250115_235305](https://github.com/user-attachments/assets/f7612d38-1814-4053-b7e1-5899effb340e)

**Comment by llb608** [comment]
原来我这个就S905L2的芯片，但是 进了armbian 识别不到emmc

**Comment by appl3s** [comment]
> ![MVIMG_20250115_235435](https://github.com/user-attachments/assets/ede25785-d756-4e0b-a3aa-9c6e72563c67) ![MVIMG_20250115_235305](https://github.com/user-attachments/assets/f7612d38-1814-4053-b7e1-5899effb340e)

跟你型号一样，不需要短接，直接刷了 android_tv_mgv2000-s905l2-android4.4.2-root.tar.xz 成功了

**Comment by zhanglao10** [comment]
> root的安卓系统链接：**https://pan.baidu.com/s/1viqKGsUMem6VkH-doKlcUw?pwd=o8je**
> 
> 最后一次安装用的109，不知道和116有没有区别，但感觉109(meson-gxl-s905x-p212.dtb)更稳定。

啊哦，来晚了，该分享文件已过期

**Comment by oudi0625** [comment]
请教一下，就是先刷[android_tv_e900v21c_s905l_android4.4.2.tar.gz]这个包，然后刷fnnas_amlogic_s905l-mg101_k6.12.41_2026.02.14.img这个镜像吗？

**Comment by yunos96** [comment]
失败的U盘插 最远的那个口 黑屏正常的

**Comment by yunos96** [comment]
为什么我写入了EMMC 就启动不了 只能U盘启动

**Comment by yunos96** [comment]
<img width="603" height="1311" alt="Image" src="https://github.com/user-attachments/assets/586a11ee-b397-47e8-a0b6-fcc7fbb15c97" />

搞了我几天 我是江西联通的 这玩意接显示器无输出 你们提的 我用了 全都无法启动  用u盘引导的成了 直接写emmc也能开机了  啥都不用改 引导能启动就用引导的 
amlogic,m302aamlogic,s905wamlogic,meson-gxl  固件 随便哪个 要我过两天上传

**Comment by yunos96** [comment]
Armbian_26.05.0_amlogic_s905l_noble_6.18.33_server_2026.06.01 这个固件 不要修改任何东西  就填能U盘启动的那个 设备名 一路安装
