### ISSUE TITLE
请问怎样可以编译 4.xx  内核 ？

### ISSUE THREAD

**Issue by hanguofu** [ophub/amlogic-s9xxx-armbian#2343]
**Device Information | 设备信息**
 - SOC: S905L
 - Model ： R3300L

**Armbian Version | 系统版本**
 - Kernel Version: 4.XX
 - Release: Ubuntu 

 请问哪里可以找到 基于 linux  的 4.xx  的内核的源码？我想编译一个给[R3300L] 盒子用。谢谢！

**Comment by ophub** [comment]
https://kernel.org
