### ISSUE TITLE
tvi3315a启动不了，之前的版本负载高了就死机

### ISSUE THREAD

**Issue by chen1452071129** [ophub/amlogic-s9xxx-armbian#2346]
![屏幕截图 2024-06-02 114911](https://github.com/ophub/amlogic-s9xxx-armbian/assets/114867697/f8b8c005-56ae-41bb-b004-7eee5c20fc94)

**Comment by Enborgrn** [comment]
踏马的，怪不得，没屏幕ssh老是死机。

**Comment by chen1452071129** [comment]
> 踏马的，怪不得，没屏幕ssh老是死机。

刷这个版本Armbian_24.5.0_rockchip_tvi3315a_noble_6.1.82_server_2024.03.16，cpu频率限制在816000-141600之间就不死机了

**Comment by Enborgrn** [comment]
没事，刷了上一个版本的24.5.0的jemmy，就像又还好。24.6.0的jemmy真就离谱。

**Comment by ABNOTF** [comment]
> 没事，刷上了一个版本24.5.0的jemmy，就像还不错一样。24.6.0的jemmy真的就离谱了。

求分享

**Comment by Enborgrn** [comment]
> > 没事，刷上了一个版本24.5.0的jemmy，就像还不错一样。24.6.0的jemmy真的就离谱了。
> 
> 求分享
这个博主的项目里面有

**Comment by l0o0** [comment]
我说怎么刷完进不去，原来问题在这。

**Comment by Enborgrn** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/122714819/eb72647e-0a13-4b65-b04e-7434acec7ae1)
为什么我的tvi3315a刷了Armbian OS 24.5.1 Jammy以后长时间运行后就会python3的进程让cpu占用突然增高。这样都好几次了，我启动过docker以后会有突然的波动，但是正常运行docker程序以后就会立马降下来。这是怎么回事？

**Comment by ABNOTF** [comment]
> > > 没事，刷上了一个版本24.5.0的jemmy，就像还不错一样。24.6.0的jemmy真的就离谱了。
> > 
> > 
> > 求分享
> > 这个博主的项目里面有

没有找到。。。

**Comment by chenshenghao** [comment]
我的也基本跑到网络适配器这块儿就起不动了，之前的rom也找不到地方下载

**Comment by imxara** [comment]
> 我的也基本跑到网络适配器这块儿就起不动了，之前的rom也找不到地方下载

同样的情况，也是在网络适配器这块就死机了，然后又下载了@chen1452071129所提到的`6.1.82`内核与当前的`6.1.94`比较，`rk3399-tvi3315a.dtb`文件并没有发现较大的改动，多的就是加入了HDMI端口的支持，其他的还要等大佬来分析了。

**Comment by imxara** [comment]
> > 我的也基本跑到网络适配器这块儿就起不动了，之前的rom也找不到地方下载
> 
> 我这边使用的 [Armbian_24.8.0_rockchip_tvi3315a_bookworm_6.1.93_server_2024.06.15.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.06/Armbian_24.8.0_rockchip_tvi3315a_bookworm_6.1.93_server_2024.06.15.img.gz) 和 [Armbian_24.8.0_rockchip_tvi3315a_bullseye_6.1.93_server_2024.06.15.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2024.06/Armbian_24.8.0_rockchip_tvi3315a_bullseye_6.1.93_server_2024.06.15.img.gz) 也是在网络适配器这块就死机了，然后又下载了@chen1452071129所提到的`6.1.82`内核与当前的`6.1.93`比较，`rk3399-tvi3315a.dtb`文件并没有发现较大的改动，多的就是加入了HDMI端口的支持，其他的还要等大佬来分析了。

update:
应该是上游Armbian系统的问题，试过TN3399和TVI3315A两块板子刷当前Armbian 24.8.0的都会在18秒左右死机，当前能想到的办法是Fork一份代码，然后采用使用外部的Armbian 24.5.1 的镜像作为底包重新编辑，现在启动正常。
