### ISSUE TITLE
湖南移动 九联UNT402A u盘启动成功，HDMI没有输出，可写emmc，但Armbian-install 不知用哪个ID

### ISSUE THREAD

**Issue by shirakawa-poi** [ophub/amlogic-s9xxx-armbian#2347]
**Device Information | 设备信息**
 - SOC: [e.g. S905L3]
 - Model [e.g. UNT402A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.31-ophub]
 - Release: [e.g. Armbian_24.5.0_amlogic_s905l3_bookworm_6.6.31_server_2024.05.17.img]

**Describe the bug | 问题描述**
此盒子需要使用meson-gxl-s905l3b-m302a.dtb和u-boot-s905x-s912.bin来进行引导，刷的安卓9的底包，有无root均可，用开心电视助手通过连接ADB让盒子从U盘/SD卡启动，最好是用一张8G的SD卡插读卡器启动，我试了一个金士顿16G和爱国者32G的U盘都没有启动成功，启动后HDMI没有信号输出，路由器里可以看到一个名为armbian的设备获取ip，用ssh登录即可，model_database.conf中已存在两个UNT402A的启动参数，但是都不能正常启动，所以我猜想湖南移动的盒子可能跟别的地区的盒子有些差异，armbian-install安装时可以写入emmc，但是我不知道ID填多少，目前测了115，119，120，121，125，128都不能正常启动，希望O大能指点一下

附上图片
<img width="513" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/21a2baad-bb80-4f9a-9431-9da7fc3cb88f">
<img width="444" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/28305965-1210-4cfc-ac7c-877e2c3cecf8">
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/4d7dd6df-e5cd-4c60-9ada-c2bd1165b214)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/451a63c6-d3d1-4813-85b2-7118dfe6aba9)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/8262c83f-6df6-4da1-9c35-97c24a11e457)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/8dc97f39-b120-46ad-ae46-58738bb86d81)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/13598b91-cb52-4121-8794-7433c4da4bc4)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166534763/b2859857-16b0-44e1-9318-1510216d4d59)

**Comment by ophub** [comment]
根据你反馈的信息dtb和u-boot选项，你可以使用`125`对应的固件`s905l3b`固件。具体可以查阅模型配置表： https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

如果写入emmc不能启动，你可以先把盒子刷回安卓系统，然后使用ampart工具看看你的分区，是不是和armbian-install设置的不同，写入了不安全的位置，具体查看仓库的文档。

- 你可以试试启用 `/boot/extlinux/extlinux.conf`
- 你也可以试试`armian-install -m yes`写入一次，选125，试试是不是需要添加u-boot，

**Comment by shirakawa-poi** [comment]
感谢O大，我目前使用Armbian_24.5.0_amlogic_s905l3b_bookworm_6.6.31_server_2024.05.18.img，没做任何更改可以直接启动，armbian-install选125可以写入启动，完美运行

**Comment by ophub** [comment]
恭喜你。你有这个盒子的安卓系统吗？分享一下你刷机使用的安卓系统的下载，我转存一份，方便其他朋友参考你的使用方法。

**Comment by shirakawa-poi** [comment]
链接：https://pan.baidu.com/s/12iuO2IGkpQyYnEFvMwbvWQ?pwd=g7o6 
提取码：g7o6

**Comment by ophub** [comment]
安卓系统已经转存到了： https://github.com/ophub/kernel/releases/tag/tools

**Comment by tinytinycn** [comment]
### 九联 UNT402A 成功刷入 armbian
- 设备型号：UNT402A
- 处理器型号：S905L3 （不是L、不是L2、也不是L3B）
- 地区：湖南
- armbian版本：[Armbian bookworm 2024.08](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_bookworm_save_2024.08)
- 镜像下载：[Armbian_24.8.0_amlogic_s905l3_bookworm_6.6.46_server_2024.08.15.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.08/Armbian_24.8.0_amlogic_s905l3_bookworm_6.6.46_server_2024.08.15.img.gz)
- FDTFILE：meson-gxl-s905l3b-m302a.dtb
- U-boot：u-boot-s905x-s912.bin

![1](https://github.com/user-attachments/assets/f9438572-63f5-44a6-8db6-da5407ce31c9)
![2](https://github.com/user-attachments/assets/563151ae-dc23-48a3-b7d7-05f772ee2ecc)
![3](https://github.com/user-attachments/assets/8883d4fd-ce68-43d0-9dce-34cefc84626c)
![4](https://github.com/user-attachments/assets/68602f51-6a78-45bc-b558-e240671a7841)


### U盘启动armbian
1. 确保已刷入非官方第三方android系统（或者，可开启adb调试以及root权限的android系统）
2. 开启adb 调试
3. adb connect [设备ip]，可正常连接设备，exit退出连接
4. 烧录`Armbian_xx.x.x_amlogic_s905l3_`前缀的镜像文件到U盘，烧录成功，插入U盘到里网口最近的usb口
5. adb shell reboot update 重启，若失败，可使用如下步骤。（步骤4、步骤5 无法成功启动，可尝试步骤6）
6. 将U盘中的u-boot-s905x-s912.bin复制并粘贴为u-boot.ext和u-boot.emmc 这两个文件，断电重启（步骤4、步骤5 成功启动，请忽略此步骤）
7. 确保盒子与路由器有线连接，登陆路由器后台，获取盒子此时的IP地址（检查名为armbian的接入设备）
8. 电脑开启终端，`ssh root@盒子ip`，密码默认1234

### armbian成功启动后，将armbian系统刷入emmc
1. 输入命令 `lsblk` ，检查 `mmcb1k2` 的挂载
2. 请确保U盘系统启动后，成功挂载 `mmcbik2` （不成功，请勿进行接下来的步骤）![emmc挂载成功](https://github.com/user-attachments/assets/f83ceaf0-9aec-44df-9471-81b3d652137c)
3. 输入命令 `armbian-install`
![SCR-20240830-kag](https://github.com/user-attachments/assets/75ac0726-7066-4412-b8c1-6361c911ef71)

4. 选择 ID 124 (**meson-gxl-s905l3b-m302a.dtb**) 
![SCR-20240830-kar](https://github.com/user-attachments/assets/f1e490d4-7f8a-4008-92e8-e3441bdf25c8)

5. 选择 1-ext4 
![SCR-20240830-kbd](https://github.com/user-attachments/assets/a9514cc1-7d8e-49de-a39b-2daa42e7ba9f)
![SCR-20240830-kbq](https://github.com/user-attachments/assets/748c9706-a4b6-4f66-a5b1-8edafc861d8f)

6. 断电、拔掉U盘、上电重启、ssh登陆

**Comment by luohong1** [comment]
U盘启动成功，没有识别挂在emmc怎么办呢  ，想安装到本地emmc
![image](https://github.com/user-attachments/assets/a7b60411-b29a-401e-a2e9-6512a573e200)

**Comment by ophub** [comment]
nand的存储不能写入

**Comment by qw101233** [comment]
> 安卓系统已经转存到了： https://github.com/ophub/kernel/releases/tag/tools

请问文件名称叫什么，搜索显示有两个与402A相关，但线刷都卡2%，不能成功。

**Comment by yaodmin** [comment]
HDMI显示完全没头绪么，没有显示的话，就没折腾的意义了 - -

**Comment by zxas45** [comment]
> nand的存储不能写入

@ophub 这种存储类型只能是外挂U盘吗

**Comment by qq8554650** [comment]
我刚好有这个盒子，linux是有显示的。
用过专门跑P的固件（kernel5），屏幕有显示，能安装到emmc。
现在用的飞牛（kernel 6）+跑P的dtb，屏幕有显示。安装时选的305（s905l3a）后再改的uEnv文件。
如果有需要我再提供下一步

**Comment by qw101233** [comment]
> 我刚好有这个盒子，linux是有显示的。 用过专门跑P的固件（kernel5），屏幕有显示，能安装到emmc。 现在用的飞牛（kernel 6）+跑P的dtb，屏幕有显示。安装时选的305（s905l3a）后再改的uEnv文件。 如果有需要我再提供下一步

求指导@qq8554650

**Comment by qq8554650** [comment]
> > 我刚好有这个盒子，linux是有显示的。 用过专门跑P的固件（kernel5），屏幕有显示，能安装到emmc。 现在用的飞牛（kernel 6）+跑P的dtb，屏幕有显示。安装时选的305（s905l3a）后再改的uEnv文件。 如果有需要我再提供下一步
> 
> 求指导[@qq8554650](https://github.com/qq8554650)

你有什么问题

**Comment by qw101233** [comment]
> > > 我刚好有这个盒子，linux是有显示的。 用过专门跑P的固件（kernel5），屏幕有显示，能安装到emmc。 现在用的飞牛（kernel 6）+跑P的dtb，屏幕有显示。安装时选的305（s905l3a）后再改的uEnv文件。 如果有需要我再提供下一步
> > 
> > 
> > 求指导[@qq8554650](https://github.com/qq8554650)
> 
> 你有什么问题
 我有这个盒子，之前也跑过P（麻雀），P的固件DHMI有显示，我替换dtb，安装的时候有DHMI输出，但是不能安装到 emmc。但是P的固件是可以的。有意思的是，直接安装Armbian 可以安装，但是没有DHIM输出。所以我现在就卡主了，不知道如何有效测试替换什么文件去测试，已达到 飞牛或者Armbian的系统 安装成功与HDMI可以输出。

**Comment by qq8554650** [comment]
> > > > 我刚好有这个盒子，linux是有显示的。 用过专门跑P的固件（kernel5），屏幕有显示，能安装到emmc。 现在用的飞牛（kernel 6）+跑P的dtb，屏幕有显示。安装时选的305（s905l3a）后再改的uEnv文件。 如果有需要我再提供下一步
> > > 
> > > 
> > > 求指导[@qq8554650](https://github.com/qq8554650)
> > 
> > 
> > 你有什么问题
> > 我有这个盒子，之前也跑过P（麻雀），P的固件DHMI有显示，我替换dtb，安装的时候有DHMI输出，但是不能安装到 emmc。但是P的固件是可以的。有意思的是，直接安装Armbian 可以安装，但是没有DHIM输出。所以我现在就卡主了，不知道如何有效测试替换什么文件去测试，已达到 飞牛或者Armbian的系统 安装成功与HDMI可以输出。

刚测试的。
下载  Armbian_26.08.0_amlogic_s905l3a_trixie_6.18.41_server_2026.08.01.iso
U 盘引导文件用 meson-gxl-s905l-venz-v10.dtb
我的芯片拆开看了是S905L

<img width="1279" height="1706" alt="Image" src="https://github.com/user-attachments/assets/61a4ea37-c44d-4d32-9807-49b17cbad69f" />
