### ISSUE TITLE
请求适配华北工控KD-18

### ISSUE THREAD

**Issue by mudebug77** [ophub/amlogic-s9xxx-armbian#2349]
有wiki
http://android1.norco.com.cn:7070/index.php/KD-18

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34656102/39f14b09-4ead-4912-a7ac-81006d16d7e4)

这个板子有2个版本一个是有网口LAN1 
另一个版本是网口变成了type-c 
板子区别->通过插针连接交换机拓展网口(LAN和LAN1两者2选1) 扩展出来是4个网口 都是lan的
板子原本是用4G网络然后分出来4个lan口给监控用的

 
![9C71034012AE8EA0BA262B0924987CA3](https://github.com/ophub/amlogic-s9xxx-armbian/assets/34656102/203a840c-80af-409a-83b0-2db1378d48bd)

我刷了 24.8.0_rockchip_emb3531_noble_6.1.92_server_2024.06.01，
他能正常进入armbian，网口是正常的。hdmi不输出
我刷openwrt 只有lan口没wan 不知道怎么编辑，没有wifi选项。

[firmware.zip](https://github.com/user-attachments/files/15568456/firmware.zip)
这个是原安卓7.1的 firmware 目录。我反编译了dts不知道能不能用

[提取原版固件-uboot.zip](https://github.com/user-attachments/files/15568621/-uboot.zip)

[modules 安卓驱动.zip](https://github.com/user-attachments/files/15569731/modules.zip)

**Comment by he1313** [comment]
你好，你的固件可以分享一下吗

**Comment by he1313** [comment]
> 有 wiki http://android1.norco.com.cn:7070/index.php/KD-18
> 
> ![image](https://private-user-images.githubusercontent.com/34656102/336554267-39f14b09-4ead-4912-a7ac-81006d16d7e4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MDE5NTYsIm5iZiI6MTczNjQwMTY1NiwicGF0aCI6Ii8zNDY1NjEwMi8zMzY1NTQyNjctMzlmMTRiMDktNGVhZC00OTEyLWE3YWMtODEwMDZkMTZkN2U0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDA1NDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJmODBiOWY2ZGRhNDJkMDk3OTBhODM0YWRiMzBkZWUyYWRmZjk2ZTZhMmYyNzBmNzBlYzdlYWM4YzQ5ZDQ5OTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FpXNcCKH1VHCCYEJUlONHB1CEN7Ap1STMjkVamEzZRc)
> 
> 这个板子有2个版本，一个是有网口LAN1 另一个版本是网口变成了type-c 板子区别->通过插针连接交换机拓展网口（LAN和LAN1两者，2选1） 扩展出来是4个网口 都是lan的 板子原本是用4G网络，然后分出来4个lan口给监控用的
> 
> ![9C71034012AE8EA0BA262B0924987CA3](https://private-user-images.githubusercontent.com/34656102/336555565-203a840c-80af-409a-83b0-2db1378d48bd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0MDE5NTYsIm5iZiI6MTczNjQwMTY1NiwicGF0aCI6Ii8zNDY1NjEwMi8zMzY1NTU1NjUtMjAzYTg0MGMtODBhZi00MDlhLTgzYjAtMmRiMTM3OGQ0OGJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTA5VDA1NDczNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdmYmQ3NTllMzE1YmE2NTAxMDYwMmUyZmEwNzFiYzYzZmE4NmRkZjRmODdiNTc5NmI2ZWIyMzE4ODNkZjFhNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.UyA1NeFAYrlKz74XTmqe1gYuJ-V5TWB3qfUPIDd_s3o)
> 
> 我刷了 24.8.0_rockchip_emb3531_noble_6.1.92_server_2024.06.01， 他能正常进入armbian，网口是正常的。hdmi不输出 我刷openwrt 只有lan口没wan 不知道怎么编辑，没有wifi选项。
> 
> [firmware.zip](https://github.com/user-attachments/files/15568456/firmware.zip) 这个是原安卓7.1的 firmware 目录。我反编译了dts不知道能不能用
> 
> [提取原版固件-uboot.zip](https://github.com/user-attachments/files/15568621/-uboot.zip)
> 
> [modules 安卓驱动.zip](https://github.com/user-attachments/files/15569731/modules.zip)

你好，你的固件可以分享一下吗
