### ISSUE TITLE
allwinner_tanix-tx6 does not have network

### ISSUE THREAD

**Issue by zongru666** [ophub/amlogic-s9xxx-armbian#2350]
Device Information | 设备信息

SOC: [allwinner h6 cv200-OS]
Model [TM7PTO]
Armbian Version | 系统版本

Kernel Version: [Armbian_24.5.0_allwinner_tanix-tx6_noble_5.15.156_server_2024.05.02.img]
Release: [ jammy/bullseye]
Describe the bug | 问题描述

![1717574193669](https://github.com/ophub/amlogic-s9xxx-armbian/assets/166798572/fc9868cd-2f8f-4d96-8ab6-50632f7ce4bb)

-天敏TM7PRO机顶盒，将镜像拷录到TF卡，设备会从TF卡启动，但启动无法检测到网卡设备，有线无线的都不行，就是没网络，进入armbian系统后执行ip a命令只有lo是up状态，没有eth0之类的

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_noble_save_2024.06

试试最新的这个

**Comment by zongru666** [comment]
今天试过了，还是一样的问题，网线和WiFi都无法使用，机顶盒启动tf卡里的armbian后只有一个usb口是有用的

**Comment by zongru666** [comment]
机型是天敏的TM7Pro，全志h6 cv200-OS，其他数据就不知道了，它的安卓系统的所有接口都是正常的

**Comment by zongru666** [comment]
tm7pro，tf卡启动armbian，只有一个usb口有用，然后外接usb转网口，再接网线，就可以识别到网络，就可以愉快地上网了
