### ISSUE TITLE
zysj wifi不能用，发现上游内核仓库dts设备树wif没有启用

### ISSUE THREAD

**Issue by Lemon1151** [ophub/amlogic-s9xxx-armbian#2351]
这是打开了打开wifi的dts，您试试能不能正常编译，如果能的话麻烦提交到上游内核仓库6.1和6.6
[rk3399-zysj.zip](https://github.com/user-attachments/files/15584350/rk3399-zysj.zip)

**Comment by ophub** [comment]
[rk3399-zysj.dtb.zip](https://github.com/user-attachments/files/15585297/rk3399-zysj.dtb.zip)

我测试了从5.4.y到6.6.y的全部内核，都编译正常。你试试这个dtb能不能正确激活wifi。

**Comment by Lemon1151** [comment]
> [rk3399-zysj.dtb.zip](https://github.com/user-attachments/files/15585297/rk3399-zysj.dtb.zip)
> 
> 我测试了从5.4.y到6.6.y的全部内核，都编译正常。你试试这个dtb能不能正确激活wifi。

这个dtb卡开机界面，我重新修改了下您试试能不能编译成功
[Uploading rk3399-zysj.zip…]()

**Comment by Lemon1151** [comment]
[rk3399-zysj.zip](https://github.com/user-attachments/files/15604559/rk3399-zysj.zip)

**Comment by ophub** [comment]
[rk3399-zysj.dtb.zip](https://github.com/user-attachments/files/15738994/rk3399-zysj.dtb.zip)

可以正常编译，你试试这个编译好的能不能正常驱动wifi
