### ISSUE TITLE
how to boot on this board? s905x p212

### ISSUE THREAD

**Issue by jg-ribeiro** [ophub/amlogic-s9xxx-armbian#2353]
**Device Information**
 - Name: Super TV
 - SOC: s905x
 - Model: HAM905X1A0-B

**Armbian Version 24.8.0**
 - Kernel Version: 6.6.32
 - Release: jammy

I don’t really know how to boot into Armbian with this device. I’ve tried many tutorials and pieces of information, but none worked. The closest I got was with an aml_autoscript in Android, selecting ‘local update.’ But upon reboot, I get an undescribed error.

Any help will be appreciated.

![BOARD](https://github.com/ophub/amlogic-s9xxx-armbian/assets/144810777/fd75578f-88f3-4815-bce3-f1f8c806a113)

**Comment by thelgvf** [comment]
opa, vc conseguiu? to com o mesmo problema aqui e tenho uma supertb igual a sua

**Comment by jg-ribeiro** [comment]
> opa, vc conseguiu? to com o mesmo problema aqui e tenho uma supertv igual a sua

Até agora, nenhuma novidade.
