### ISSUE TITLE
HK1box不能从tf卡，USB启动

### ISSUE THREAD

**Issue by zhangnick** [ophub/amlogic-s9xxx-armbian#2354]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [HK1]

**Armbian Version | [2024.06]
 - Kernel Version: [6.6.32]
 - Release: [bullseye]

**Describe the bug | 问题描述**
HK1box从tf卡、USB都不能启动，卡在第一屏，后来替换成旧版（Armbian 23.02.0-trunk Bullseye，6.1.1-flippy-80+ ）里的uboot（带uboot.ext），可以启动了，应该是uboot问题

**Comment by qu123xxx** [comment]
现在仍然有这个问题，试了下面这几个仍然无法启动。Armbian 23.02.0-trunk Bullseye，6.1.1-flippy-80+好像找不到了哈哈。
Armbian_24.11.0_amlogic_s905x3_noble_6.6.48_server_2024.09.01.img
Armbian_24.11.0_amlogic_s905x3_noble_6.6.62_server_2024.11.20.img
Armbian_25.02.0_amlogic_s905x3_noble_6.6.74_server_2025.02.01.img

**Comment by qu123xxx** [comment]
刷了2024年2月的一个版本，升级到最新的内核后，apt-get upgrade强制更新了一个uboot包之后重启失败，问题一样，估计确实是uboot的问题。但是并不知道怎么回滚了……
