### ISSUE TITLE
s905lb的版本内存都只能识别到788M。

### ISSUE THREAD

**Issue by x2358473** [ophub/amlogic-s9xxx-armbian#2355]
**Device Information | 设备信息**
 - SOC: [e.g. S095lb、s905mb]
 - Model [ipbs9505、b860av1.1-t]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1]
 - Release: [bullseye]

**Describe the bug | 问题描述**
s905lb的版本内存都只能识别到788M。替换换了u-boot-r3300l.bin与u-boot-s905x-s912.bin这两个为u-boot.sd还是只能识别788M.机子是1+8的。中兴的b860av1.1-t s905mb的机子刷s905lb的固件也只有788.使用s905的5.10.155版本固件有920M。但是目前5.10版本已经不能下载了。想知道是什么原因导致内存识别变少了。或者怎么改可以识别回920M的

**Comment by ophub** [comment]
更新内核到5.10.y

```
armbian-sync
armbian-update -k 5.10
```

**Comment by x2358473** [comment]
> 更新内核到5.10.y
> 
> ```
> armbian-sync
> armbian-update -k 5.10
> ```

非常感谢。把内核降级到5.10后内存变成929M了。

**Comment by x2358473** [comment]
> 更新内核到5.10.y
> 
> ```
> armbian-sync
> armbian-update -k 5.10
> ```

刚发现一个问题。想请问下如何禁用wifi。浪潮的ipbs9505内核降到5.10后就一直报wifi异常。

**Comment by ophub** [comment]
仓库根目录有个文档目录，进去看说明文档写了怎么禁用无线。
