### ISSUE TITLE
jp-tvbox更新6.x内核后无网无HDMI

### ISSUE THREAD

**Issue by SxitDark** [ophub/amlogic-s9xxx-armbian#2356]
**Device Information | 设备信息**
 - SOC: [rk3566]
 - Model [jp-tvbox]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.92/6.6.32]
 - Release: [jammy]

**Describe the bug | 问题描述**
因新固件解决了WiFi无法驱动的问题，故从2023.11更新至2024.06(更新方式不是重点，后期重刷仍然异常)
HDMI无输出，路由器后台显示设备离线
因设备没有TF卡槽无法回退，尝试进maskrom模式重刷2024.06
6.1.92内核前面板LED能正常闪烁，6.6.32内核LED灯不亮
由于条件有限，暂不能提供TTL日志
相似问题#2223
希望只是我的设备有问题（
注：仅添加电容，未焊接限流芯片。2023.11版本镜像已丢失，无法进一步排除问题。

**Comment by ophub** [comment]
这个盒子可以使用rk35xx内核

```
armbian-sync
armbian-update -u rk35xx -k 5.10
```
