### ISSUE TITLE
请问编译时如何自定义这个 ssh登录时显示的横幅 Aml.S905d

### ISSUE THREAD

**Issue by ccyybn** [ophub/amlogic-s9xxx-armbian#2358]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/7237501/080d0de8-c3f4-4a9b-8e5f-76de34870205)

**Comment by ccyybn** [comment]
我想把它改成 `N1`

**Comment by ccyybn** [comment]
https://forum.armbian.com/topic/11893-login-image/

找到了，改这里 `/etc/armbian-release`

**Comment by ophub** [comment]
是的
