### ISSUE TITLE
update kernel: 5.15.33 u-boot is no longer required -- Seeking Clarification

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#236]
Hi @ophub 

This is NOT a issue report. 

I read/saw this on your https://github.com/ophub/kernel/tree/main/pub/stable.  

What does "update kernel: 5.15.33 u-boot is no longer required" refer to?  

Does it means any kernel after kernel 5.15.33 will not longer require u-boot.ext to boot up the TV Box anymore?

**Comment by ophub** [comment]
The kernel after 5.10 needs u-boot before it can be used. At present, the kernel of 5.15 has a TEXT_OFFSET patch, which is the same as 5.4 and can be used without u-boot. The simple understanding is that it is the same as the previous 5.4.
However, other kernels such as 5.10/5.16/5.17 have not applied this patch and need u-boot support.

**Comment by JFLim1** [comment]
Hi @ophub 
Just to clarify if I switch from kernel 5.17.2-flippy-71+ currently in use on Armbian Jammy with:

`sudo armbian-update 5.15.34`

and 

s`udo mv /boot/u-boot.ext /boot/u-boot.ext-backup #basically not using the chainloader
`
Is there anything else need to be done to get it to boot up without u-boot.ext?

**Comment by ophub** [comment]
No, 5.15 is the same as 5.4

**Comment by JFLim1** [comment]
> No, 5.15 is the same as 5.4

So it will still use uInitrd and zImage to boot just like kernel 5.10/5.17 just without u-boot.ext required?

**Comment by ophub** [comment]
In the past, many devices did not have u-boot and could only use the lower version of the 5.4 kernel. Now you can use the latest kernel of 5.15

**Comment by JFLim1** [comment]
> In the past, many devices did not have u-boot and could only use the lower version of the 5.4 kernel. Now you can use the latest kernel of 5.15

Hi @ophub 
Thanks.  Just switched from kernel 5.17.2-flippy-71+ to kernel 5.15.34-flippy-71+o on your Armbian-Jammy firmware (it can boot with u-boot.ext or without u-boot.ext).

When boot with u-boot.ext "HTOP" report available RAM as 3.7GB and boot without u-boot.ext "HTOP" report available RAm as 3.26GB.  

Any reason for the lower RAM report when boot without u-boot.ext the big difference in available RAM ?

**Comment by ophub** [comment]
Some devices do not have u-boot, so only 5.4/5.15 kernels can be used. Currently, only these two kernels have added support for the TEXT_OFFSET patch.

All kernels (5.4/5.10/5/15/5.17...) can add u-boot.ext/u-boot.emmc, but it will be reloaded at boot, adding about less than 10 seconds to boot time. You can add according to actual needs.
