### ISSUE TITLE
 ETHERNET eth0 ERROR s905x2 1GB RAM 8GB ROM

### ISSUE THREAD

**Issue by letsplaysfax** [ophub/amlogic-s9xxx-armbian#2360]
Armbian_24.8.0_amlogic_s905x2_noble_6.1.92_server_2024.06.01.img.gz
![WhatsApp Image 2024-06-09 à 22 39 01_a89fca87](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161867358/cc3a39ad-696c-4ac0-9940-06ee78ce24d8)
![WhatsApp Image 2024-06-09 à 22 39 01_e045b453](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161867358/d3eddd90-badd-477c-b37e-38a5d6b1e6fa)
![WhatsApp Image 2024-06-09 à 22 41 31_86ccc31f](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161867358/5b7b6616-71db-4943-9a4c-4bd7e671451d)
![WhatsApp Image 2024-06-09 à 22 41 37_1d3e71a7](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161867358/a3aab384-e5c1-408d-bdf0-123e77b7dbcc)

**Comment by ophub** [comment]
No support for armv7

**Comment by letsplaysfax** [comment]
> No support for armv7

Armbian not working for this stb ?

**Comment by ophub** [comment]
This repository's kernel does not support armv7

**Comment by letsplaysfax** [comment]
> This repository's kernel does not support armv7

I have another stb
You can help me to install armbian 
![20240607_220154](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161867358/9331b5b1-003a-44a6-9b28-20b47feb751a)
![20240607_220134](https://github.com/ophub/amlogic-s9xxx-armbian/assets/161867358/1f160c9c-122e-414d-95de-b27afbce685a)
