### ISSUE TITLE
可以修改显存vram大小吗？

### ISSUE THREAD

**Issue by guguliu** [ophub/amlogic-s9xxx-armbian#2364]
可以像树莓派那样改vram的大小吗？

**Comment by ophub** [comment]
树莓派(Raspberry Pi)的 VRAM(Video RAM)大小通常是固定的，因为它是系统硬件的一部分。树莓派有不同的模型，每个模型都有不同的 VRAM 大小。例如，树莓派3B+有1GB 的 VRAM,而树莓派4B 有2GB 的 VRAM 。这些信息通常可以在树莓派的官方文档或者硬件规格书中找到。

1.获取所需硬件: 如果你需要更多的 VRAM,你可能需要购买额外的显卡。例如，如果你的树莓派模型支持 GPIO 接口的显卡，你可以购买相应的显卡来增加 VRAM 。

2.安装驱动程序: 将新显卡连接到树莓派后，你可能需要安装适当的驱动程序。这通常可以通过运行树莓派操作系统中的包管理器来完成。

3.修改配置文件: 在某些情况下，你可能需要修改树莓派的配置文件来允许系统识别和使用额外的显卡。这可能涉及到编辑/etc/dmesg.conf文件或其他配置文件。

根据树莓派的文档，你看你的设备可不可以换硬件。

**Comment by guguliu** [comment]
您可能理解错了我的意思。
我的设备是hk1box s905x3的，刷了
Armbian_24.8.0_amlogic_s905x3_bookworm_6.1.92_server_2024.06.01.img.gz这个包并安装了桌面环境。日常使用正常。但是播放视频不是很流畅。我想能不能修改显存大小或者安装驱动得到改善。

有没有类似树莓派raspi-config里面相同的设置，把内存共享一部分给GPU作为显存用。
如图：
![Screenshot_2024-06-11-15-53-18-387_com microsoft emmx-edit](https://github.com/ophub/amlogic-s9xxx-armbian/assets/32637322/3921e787-17f2-4e8e-95b6-010705f51761)

**Comment by ophub** [comment]
没注意到armbian有这个功能，这个可能是树莓派的特有设置吧。
