### ISSUE TITLE
天邑ty1608板载有线网卡不能用，板载无线网卡RTL8822cs也不能用， 怎么处理？请指教，谢谢

### ISSUE THREAD

**Issue by ag598** [ophub/amlogic-s9xxx-armbian#2366]
**Device Information | 设备信息**
 - SOC: 905L3b
 - Model 天邑ty1608

**Armbian Version | 系统版本**
Linux version 6.1.92-ophub (root@fv-az2026-603) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009, GNU ld (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 2.41.0.20231009)

Armbian OS 24.8.0 Noble with Linux 6.1.92-ophub

**Describe the bug | 问题描述**
天邑ty1608板载有线网卡不能用，板载无线网卡RTL8822cs也不能用， 
怎么处理？请指教，谢谢

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
![c4fb53dcda7daa8ef56b249bec87adf](https://github.com/ophub/amlogic-s9xxx-armbian/assets/71054211/ebe957ab-fe8e-4deb-9fa8-8538f3346f1f)

![3e58d2a96c0bea497464022d2c4f820](https://github.com/ophub/amlogic-s9xxx-armbian/assets/71054211/b732976c-ce7f-44db-8ee8-00c2093dc1b6)

root@armbian:~# lsmod
Module                  Size  Used by
veth                   32768  0
xt_nat                 16384  21
xt_tcpudp              20480  0
xt_conntrack           16384  2
nft_chain_nat          16384  13
xt_MASQUERADE          20480  3
nf_nat                 53248  3 xt_nat,nft_chain_nat,xt_MASQUERADE
nf_conntrack_netlink    49152  0
xt_addrtype            16384  2
nft_compat             20480  28
nf_tables             229376  305 nft_compat,nft_chain_nat
br_netfilter           32768  0
bridge                266240  1 br_netfilter
sunrpc                561152  1
zram                   32768  3
binfmt_misc            24576  1
rtw88_8822cs           16384  0
rtw88_8822c           462848  1 rtw88_8822cs
rtw88_sdio             24576  1 rtw88_8822cs
mt7601u               118784  0
rtw88_core            172032  2 rtw88_8822c,rtw88_sdio
mac80211              946176  3 rtw88_sdio,rtw88_core,mt7601u
cfg80211              917504  3 rtw88_core,mt7601u,mac80211
rfkill                 36864  3 cfg80211
libarc4                16384  1 mac80211
snd_soc_meson_gx_sound_card    16384  0
snd_soc_meson_card_utils    16384  1 snd_soc_meson_gx_sound_card
meson_vdec             81920  0
videobuf2_dma_contig    24576  1 meson_vdec
v4l2_mem2mem           45056  1 meson_vdec
snd_soc_meson_t9015    24576  0
meson_gxbb_wdt         16384  0
meson_ir               20480  0
snd_soc_meson_aiu      32768  0
snd_soc_meson_codec_glue    16384  1 snd_soc_meson_aiu
tcp_bbr                20480  30
sch_fq                 20480  2
dm_mod                131072  0
nfnetlink              20480  5 nft_compat,nf_conntrack_netlink,nf_tables
ip_tables              28672  0
x_tables               45056  7 xt_conntrack,nft_compat,xt_tcpudp,xt_addrtype,xt_nat,ip_tables,xt_MASQUERADE
lima                   61440  0
gpu_sched              45056  1 lima
drm_shmem_helper       24576  1 lima
root@armbian:~#

**Comment by ophub** [comment]
在仓库首页，有2个ty1608的设备连接，进去看看

**Comment by sdpyhzj** [comment]
天邑1608能安装armbian，可以稳定运行，

**Comment by ag598** [comment]
经过几天研究，终于解决了。
先刷了tools里的救砖包：
https://github.com/ophub/kernel/releases/download/tools/android_tv_ty1608_s905l3b.tar.xz
按这个压缩包里的说明安装，终于解决了有线网卡的使用。
不过板载rtl8822cs 还没有解决。

**Comment by ophub** [comment]
rtl8822cs换老内核试试，5.4.y, 5.10.y
