### ISSUE TITLE
无法安装docker

### ISSUE THREAD

**Issue by BarenMenQi** [ophub/amlogic-s9xxx-armbian#2367]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [中国移动魔百盒cm311-1a]

**Armbian Version |Armbian OS 24.8.0 Jammy with Linux 6.1.92-ophub**
 - Kernel Version: 6.1.92
 - Release:  jammy

**Describe the bug | 问题描述**
尝试了很多方法，无法安装docker。

**Comment by BarenMenQi** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/57125245/a063d691-be1f-4a36-83bb-1a1e5eb7f299)

**Comment by BarenMenQi** [comment]
root@armbian:~# armbian-docker 
[ INFO ] Welcome to the docker management tool.
[ STEPS ] Initialize the docker installation environment...
[ INFO ] VERSION_CODEID: [ ubuntu ]
[ INFO ] VERSION_CODENAME: [ jammy ]
[ STEPS ] Start selecting docker source...
-----------------------------------------------
  ID  SOURCE
-----------------------------------------------
  1   docker.com (default)
  2   aliyun.com
  3   ustc.edu.cn
  4   tencent.com
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2/3/4): 1
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudosudo: : /etc/sudo.conf is owned by uid 1023, should be 0/etc/sudo.conf is owned by uid 1023, should be 0

sudosudo: : /etc/sudo.conf is owned by uid 1023, should be 0/etc/sudo.conf is owned by uid 1023, should be 0

sudosudo: : error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"

sudosudo: : /usr/libexec/sudo/sudoers.so must be owned by uid 0/usr/libexec/sudo/sudoers.so must be owned by uid 0

sudosudo: : fatal error, unable to load pluginsfatal error, unable to load plugins

sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ STEPS ] Install docker related packages...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ STEPS ] Install docker accelerator...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ SUCCESS ] Docker installed successfully.

↑使用armbian-docker命令，这里显示安装成功

↓但查看docker版本还是有问题

root@armbian:~# docker --version
Command 'docker' not found, but can be installed with:
apt install podman-docker  # version 3.4.4+ds1-1ubuntu1.22.04.2, or
apt install docker.io      # version 24.0.5-0ubuntu1~22.04.1

**Comment by Mgaspher** [comment]
好像docker官网今天中文访问不了，也许换个时间再试试看。

**Comment by ophub** [comment]
看群里有小伙伴反应，国内可能会长期中断docker网站的访问，一些国内的镜像站也发公告停止提供docker的镜像站了。所以，所以，我也不知道怎么回答你了，或许国内还有几个暂时还没关闭的镜像站，拉去了别像以前一样随手删了，或许真的删了就没了。

**Comment by BarenMenQi** [comment]
原来是这样，那我得赶紧再找找了！多谢作者大大！

**Comment by Mgaspher** [comment]
> 看群里有小伙伴反应，国内可能会长期中断docker网站的访问，一些国内的镜像站也发公告停止提供docker的镜像站了。所以，所以，我也不知道怎么回答你了，或许国内还有几个暂时还没关闭的镜像站，拉取了别像以前一样随手删了，或许真的删了就没了。

不是，脱钩断链么，本来不是all for one, one for all的事吗，小民不懂了。

**Comment by ophub** [comment]
我见群里有人发几个国内大学镜像站的停更docker的公告，我也觉得不会是真的，我也不愿意这是真的，但愿这些都是虚假消息，但愿这几天无法拉取docker只是某个网络服务商的技术故障。

**Comment by meiyadudu** [comment]
B站上有视频教怎么拉取其他镜像源的docker
