### ISSUE TITLE
E900V22D，4G+16G，无WIFI，有蓝牙。从U盘启动armbian不能获得DHCP地址的问题

### ISSUE THREAD

**Issue by Mgaspher** [ophub/amlogic-s9xxx-armbian#2368]
**Device Information | 设备信息**
 - SOC: [Amlogic S905L3B]
 - Model [E900V22D，4G+16G，无WIFI，有蓝牙]

**Armbian Version | 系统版本**
 - Kernel Version: [6.6.32]
 - Release: [jammy]

**Describe the bug | 问题描述**
2024年1月出厂的移动高清盒子6pro，型号E900V22D，4G+16G，无WIFI，有蓝牙。卖家刷了乐家桌面。用各种不同的系统U盘都启动不了armbian系统。观察到盒子正常进乐家桌面时可以DHCP获得地址。而从U盘启动时，U盘灯长时间闪烁（似乎是在反复读写U盘），然后熄灭。如此反复多次。但路由器上始终没有盒子获得DHCP地址的记录。因此，推测U盘启动过程始终没有正常识别或驱动盒子的网卡。后来尝试找了个USB转RJ45的外置网卡，插U口转接网线。于是在U盘启动过程中能够获得DHCP地址，进入armbian系统初始化流程。
根据现象，判断不能从U盘启动的根本原因是盒子硬件上的网卡，目前不能被armbian识别。

**Comment by Mgaspher** [comment]
目前暂时外接网卡用。如果可以，期望大佬们能够从内核支持该型号盒子的内置网卡。

**Comment by cjz9032** [comment]
蓝牙可以用吗, 我好像不行

**Comment by Windows55** [comment]
河南移动 E900V22D，4G+16G，无WIFI，有蓝牙，无需外置网卡。
用的是`Armbian_25.02.0_amlogic_s905l3b_bookworm_6.12.13_server_2025.02.12.img`
写入U盘启动，安装`armbian-install -m yes`
uboot选择编号131的
一开始启动、联网、SSH输出都非常慢，以为失败了
能写入EMMC，但ram只能识别2.86G，没有hdmi显示
![Image](https://github.com/user-attachments/assets/06a948af-9549-4200-bda2-1f371b51cbf7)
