### ISSUE TITLE
能否编译一个N1盒子用的desktop版？（s905d desktop）

### ISSUE THREAD

**Issue by vincentNuts** [ophub/amlogic-s9xxx-armbian#2369]
**Device Information | 设备信息**
 - SOC: [e.g. S905d]
 - Model [e.g. N1]

**Describe the bug | 问题描述**
当前用的是bookworm server版，尝试安装xfce4或者lxde，安装后服务总是报异常。能否直接提供一个打包好的desktop版固件。

**Comment by ophub** [comment]
armbian-software
选择201安装桌面

**Comment by vincentNuts** [comment]
谢谢
