### ISSUE TITLE
Enable github discussions

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#237]
I have seen users post questions about this s9xxx armbian fork to the Armbian forums and the forum admins have closed their threads because they say this is not an official fork so I'm suggesting you enable gh discussions.

The main reason I want this is for help getting wifi and bt working. I haven't been able to get the onboard wifi working on any of my x96 air boxes using s9xxx armbian but I have got onboard wifi working (and I also had bt working on the same TV box) under Manjaro, using a mainline (but forked/patched) kernel ie not based on the 4.x amlogic one.

The s9xxx docs currently don't mention anything about wifi but it would be good if we could add a table of WiFi and BT compatibility for the different models and which dtb is known to work for that model etc. gh discussions could help users work together to get their hardware working and discuss other issues and ideas for this fork. 

https://docs.github.com/en/discussions

**Comment by ophub** [comment]
I recommend everyone to use standard equipment officially supported by Armbian and enjoy official support.

We installed the armbian system on the TV box, which made the official very angry. This is not the result that the official wants to see, nor the result that the TV box manufacturer wants to see.

Let's keep a low profile.
