### ISSUE TITLE
想请教关于外接移动硬盘的问题

### ISSUE THREAD

**Issue by x2358473** [ophub/amlogic-s9xxx-armbian#2370]
目前把系统写入报emmc,但是想外接移动更盘挂载时遇到问题，如果在开机前插入usb就会导到无法启动。是usb启动优先级最高吗。导到无法启动emmc中的系统吗。我的移动硬盘是空的ext4盘。如果是开机后插入移动硬盘就正常。有没有什么办法让他不从usb启动。

**Comment by ophub** [comment]
你用分区软件看下移动硬盘，是不是有个boot的隐藏分区，删除了。
