### ISSUE TITLE
山东联通创维E900V21C盒子

### ISSUE THREAD

**Issue by YuTheGreat-ck** [ophub/amlogic-s9xxx-armbian#2375]
![屏幕截图 2024-06-15 214915](https://github.com/ophub/amlogic-s9xxx-armbian/assets/86639242/db45cf37-0495-4d74-a699-a46cb94056b1)
![屏幕截图 2024-06-16 171429](https://github.com/ophub/amlogic-s9xxx-armbian/assets/86639242/df4e721e-fd97-434f-bdb6-399ae804e851)
![屏幕截图 2024-06-16 171529](https://github.com/ophub/amlogic-s9xxx-armbian/assets/86639242/5bd67eff-94fc-4fd9-aee0-2b2ef93faaba)
晶晨s905L
问题是用L3B也就是写入emcc选115可以刷入但是选择116无法刷入

**Comment by YuTheGreat-ck** [comment]
debian和ubuntu都可以刷入emcc都测试过但是唯一问题就是是S905L芯片选s905l3b才能刷入 其余的刷入无法启动

**Comment by ophub** [comment]
我看了几遍都没看懂你的意思，你的盒子究竟是s905l还是s905l3b？
115和116是s905l
魔百和各省定制各自的，变种比较多，自己测试相近的，很多都通用。

**Comment by YuTheGreat-ck** [comment]
是s905L芯片

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

115和116都是s905l，你选择的没错，这两个的区别是dtb不同，u-boot相同，现在e900v21c标记在116里，看来你的适合115，把你的盒子的正面、底部拍个照片分享一下，主板方便的话也分享一下，方便有相同设备的朋友们参考使用。

你给盒子刷过其他安卓系统吗？如果有的话分享一下安卓下载地址，我转存一份，方便其他人使用。

**Comment by ophub** [comment]
好的，多谢分享

**Comment by YuTheGreat-ck** [comment]
感谢O大，给新手小白做的贡献

**Comment by ElonWang8** [comment]
我也是山东联通创维E900V21C盒子，我选115和116都能刷入，但是没有网络。获取不到ip。
![Uploading 截屏2024-06-21 19.26.23.png…]()

**Comment by ophub** [comment]
你先换刷一下上面链接里面的安卓系统

**Comment by ElonWang8** [comment]
> 你先换刷一下上面链接里面的安卓系统

用线刷刷入了上面的安卓系统，但没办法从u盘启动armbian了

**Comment by ElonWang8** [comment]
> 你先换刷一下上面链接里面的安卓系统

搞定了 谢谢大哥

**Comment by ElonWang8** [comment]
> 你先换刷一下上面链接里面的安卓系统

大哥 刷了armbian想再刷会上面的安卓应该怎么办？

**Comment by sau1g0dman** [comment]
![Image](https://github.com/user-attachments/assets/dcaeccbb-2585-47c1-a9c1-8e68237150fc)

![Image](https://github.com/user-attachments/assets/35db9831-4058-4b45-b201-20cd82106e78)

![Image](https://github.com/user-attachments/assets/5137ed33-d311-4bb7-a813-55f84e56f4aa)
我用115和116 都失败了,用的是 https://github.com/ophub/kernel/releases/download/tools/android_tv_e900v21c_s905l_android4.4.2.tar.gz 底包
刷的是https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2025.04/Armbian_25.05.0_amlogic_s905d_noble_6.12.23_server_2025.04.15.img.gz
