### ISSUE TITLE
MAC地址因为TF卡的接入而改变。

### ISSUE THREAD

**Issue by solarflows** [ophub/amlogic-s9xxx-armbian#2376]
**Device Information | 设备信息**
 - SOC: [RK3566]
 - Model [Panther X2]

**Armbian Version | 系统版本**
 - Kernel Version: [6.6.31-ophub]
 - Release: [bookworm]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
写入emmc的固件在接入TF卡当存储时，重启后mac地址会改变，移除TF卡后恢复正常。

**Comment by ophub** [comment]
TF卡的启动优先于EMMC

**Comment by solarflows** [comment]
但是TF卡内没有系统，是不是uboot优先使用TF卡算mac？

**Comment by ophub** [comment]
u-boot在启动过程中，如果读取不到盒子自己的mac地址，就会自动生成一个新的。

**Comment by solarflows** [comment]
rockchip的板子我记得只有极少数内置了挂载在i2c的eeprom，pantherx2我记得没有吧？我现在的情况是插卡和不插卡启动，eth0的mac地址不一样，但是都是固定的，比如插卡是aa:aa:aa:aa:aa:aa,不插卡就是bb:bb:bb:bb:bb:bb，当前版本的armbian是通过machineid生产mac的不是吗？还是uboot传递过来的mac地址？

**Comment by ophub** [comment]
在u-boot的源码里，他会首先获取设备硬件mac地址，如果获取到了就使用，失败了就自己生成一个。

**Comment by solarflows** [comment]
got it.
