### ISSUE TITLE
挂载机械硬盘解挂载后有问题

### ISSUE THREAD

**Issue by ADolphin-02** [ophub/amlogic-s9xxx-armbian#2383]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1 BOX]

**Armbian Version | 系统版本**
 - Release: [e.g. Bullseye with Linux 6.6.30-ophub]

**Describe the bug | 问题描述**
挂载机械硬盘解挂载后， 发现硬盘的smart 日志里面会异常断电次数会+1，（smartctl -a /dev/sda 里面的power-off retract count）
通过umount来解挂载的，然后也试过umount后shutdown也会+1，因为我是用3.5寸 新的绿联硬盘盒子的，然后有外接了稳定电源，解挂载后也确实没看见机械硬盘的文件了， 但是为什么异常断电次数会+1，
这是win系统下查看的
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/55866634/66c10c7e-9158-42bb-8725-9bf00ad1fd65)
iotop下没有程序读写

**Comment by ophub** [comment]
异常断电次数增加的问题可能与硬盘盒的电源管理和硬盘本身的电源管理有关。即使你正确地卸载了硬盘，硬盘盒或者硬盘本身可能在电源管理方面存在一些问题，导致SMART日志中记录了异常断电次数。以下是一些可能的原因和解决方法：

### 可能的原因

1. 硬盘盒的电源管理：一些硬盘盒在接收到系统的卸载命令后，可能立即切断硬盘电源，而不等待硬盘完成所有的内部操作。
2. 硬盘的电源管理：某些硬盘在接收到卸载命令后，可能没有足够的时间完成所有内部操作（如缓存写入），从而记录为异常断电。
3. 系统的电源管理：在某些情况下，系统可能会在卸载硬盘后立即关闭USB端口的电源，导致硬盘无法正常完成其内部操作。

### 解决方法

1. 延迟断电：在卸载硬盘后，等待几秒钟再断开硬盘盒的电源或USB连接，以确保硬盘有足够的时间完成其内部操作。
2. 使用udisksctl命令：尝试使用udisksctl命令来卸载和断电硬盘，这个命令会更好地处理硬盘的电源管理。

```
sudo udisksctl unmount -b /dev/sda1
sudo udisksctl power-off -b /dev/sda
```
    

3. 检查硬盘盒的固件：有些硬盘盒可能有固件更新，更新固件可能会解决电源管理问题。
4. 使用不同的硬盘盒：尝试使用其他品牌或型号的硬盘盒，看看是否会有相同的问题。
