### ISSUE TITLE
请求支持腾讯极光4pro

### ISSUE THREAD

**Issue by simonhust** [ophub/amlogic-s9xxx-armbian#2392]
腾讯极光4pro，4+64的配置，soc是s905x4-j，wifi和蓝牙芯片是ap6275p，接口为pcie。dtb文件地址是https://drive.google.com/file/d/1-QqzJRCpaMxvnNnPYewVPOvqMgemR-Lj/view?usp=drivesdk，
蓝牙和wifi驱动文件在
https://drive.google.com/drive/folders/0B8A7jq4CrJnxdEZIbElwaWFXdDQ?resourcekey=0-z8SE9zN56HevdfsZlo5MaA。
请o大支持

**Comment by ophub** [comment]
晶晨S905X4目前内核不支持。
