### ISSUE TITLE
sw799编译GobiNet驱动 (用于挂载yuga 4G模块 虚拟出网卡) 失败

### ISSUE THREAD

**Issue by ChaoliesTinnu** [ophub/amlogic-s9xxx-armbian#2393]
**Device Information | 设备信息**
 - SOC:  (RK3399)
 - Model sw799

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.93-ophub ，随后通过 armbian-update -u dev 升级到 6.1.95-ophub，两个环境下都试过
 - Release: Armbian_24.8.0_rockchip_sw799_noble_6.1.93_server_2024.06.15.img.gz

**Describe the bug | 问题描述**
- 想在sw799上编译GobiNet驱动，用于挂载yuga 4G模块 虚拟出网卡
- 根据yuga的教程已经把ttyUSBx都挂好了，AT指令也测试过没问题，暂时挂了张销号卡测试。
- 看yuga教程说想要虚拟一个网卡出来，要编译高通的gobinet驱动：
- 驱动编译参考 [yuge-gobinet](https://docs.yuge-info.com/doku.php?id=9x07:linux:gobinet)
- [yuga_gobinet_1808311742](https://docs.yuge-info.com/lib/exe/fetch.php?media=9x07:linux:yuga_gobinet_1808311742.zip)
```shell
tinnu@armbian:~/yuga/yuga$ make
make -C /lib/modules/6.1.95-ophub/build/linux-headers-6.1.95-ophub/ M=/home/tinnu/yuga/yuga modules EXTRA_CFLAGS="-fno-stack-protector"
make[1]: Entering directory '/usr/src/linux-headers-6.1.95-ophub'
awk: cannot open "include/generated/asm-offsets.h" (No such file or directory)
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-elf-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009
  You are using:           gcc (Ubuntu 13.2.0-23ubuntu4) 13.2.0
  CC [M]  /home/tinnu/yuga/yuga/GobiUSBNet.o
gcc: error: missing argument to ‘-mstack-protector-guard-offset=’
make[2]: *** [scripts/Makefile.build:250: /home/tinnu/yuga/yuga/GobiUSBNet.o] Error 1
make[1]: *** [Makefile:2010: /home/tinnu/yuga/yuga] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.95-ophub'
make: *** [Makefile:16: all] Error 2
```

** 参考以前的issue尝试
- https://github.com/ophub/amlogic-s9xxx-armbian/issues/1043
- 我从 https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads 下载了符合的编译链：
- [arm-gnu-toolchain-13.2.rel1-aarch64-aarch64-none-elf.tar.xz](https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/13.2.rel1/binrel/arm-gnu-toolchain-13.2.rel1-aarch64-aarch64-none-elf.tar.xz)
- 修改makefile指定了编译链：

```Makefile
obj-m := GobiNet.o
GobiNet-objs := GobiUSBNet.o QMIDevice.o QMI.o MPQMUX.o 
# KDIR := /lib/modules/$(shell uname -r)/build/
KDIR := /lib/modules/6.1.95-ophub/build/linux-headers-6.1.95-ophub/
PWD := $(shell pwd)
OUTPUTDIR=/lib/modules/`uname -r`/kernel/drivers/net/usb/

PI_KDIR := /lib/modules/6.8.0-1006-raspi/build
FILE = ${KDIR}/drivers/net/usb/usbnet.h
RK_CCPREFIX=/home/tinnu/toolchain/gcc-arm-11.2-2022.02-aarch64-aarch64-none-elf/bin/aarch64-none-elf-

all:
        ifeq ($(FILE), $(wildcard $(FILE)))
	    cp ${KDIR}/drivers/net/usb/usbnet.h ./
        endif
	$(MAKE) -C $(KDIR) M=$(PWD) modules 

pi: 
	$(MAKE) ARCH=arm64 CROSS_COMPILE=${RK_CCPREFIX} -C $(PI_KDIR) M=$(PWD) modules

rk: 
	$(MAKE) ARCH=arm64 CROSS_COMPILE=${RK_CCPREFIX} -C $(KDIR) M=$(PWD) modules

install: all
	mkdir -p $(OUTPUTDIR)
	cp -f GobiNet.ko $(OUTPUTDIR)
	depmod

clean:
	rm -rf *.o *~ core .depend .*.cmd *.ko *.mod.c .tmp_versions Module.* modules.order
```

```shell
tinnu@armbian:~/yuga/yuga$ make rk
make ARCH=arm64 CROSS_COMPILE=/home/tinnu/toolchain/arm-gnu-toolchain-13.2.Rel1-aarch64-aarch64-none-elf/bin/aarch64-none-elf- -C /lib/modules/6.1.95-ophub/build/linux-headers-6.1.95-ophub/ M=/home/tinnu/yuga/yuga modules
make[1]: Entering directory '/usr/src/linux-headers-6.1.95-ophub'
awk: cannot open "include/generated/asm-offsets.h" (No such file or directory)
  CC [M]  /home/tinnu/yuga/yuga/GobiUSBNet.o
aarch64-none-elf-gcc: error: missing argument to '-mstack-protector-guard-offset='
make[2]: *** [scripts/Makefile.build:250: /home/tinnu/yuga/yuga/GobiUSBNet.o] Error 1
make[1]: *** [Makefile:2010: /home/tinnu/yuga/yuga] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-6.1.95-ophub'
make: *** [Makefile:22: rk] Error 2
```

** 探索
- 我感觉应该是编译链相关的问题，内核目前用的是：arm-gnu-toolchain-13.2.Rel1-aarch64-aarch64-none-elf；我也试过 gcc-arm-11.2-2022.02-aarch64-aarch64-none-elf.tar.xz ；都是一样的问题。
- 尝试在编译命令上加堆栈保护相关设置，都没有效果：
  - EXTRA_CFLAGS="-fno-stack-protector" 
  - EXTRA_CFLAGS="-mstack-protector-guard-offset=offset"

- 在PC上直接编译，用的GCC 9.4.0 是可以编译通过的
- 后来试过拉寒芒那个镜像， 23.1 的，不过他的镜像下面没有 /lib/modules/$(shell uname -r)/build ，apt随便拉了个 linux-header 可以编译通过，GCC 版本好像也是 8 9 这样子。

** 猜测
- 是不是要像这个issue一样重新用比较旧的GCC编译内核？
- https://kkgithub.com/ophub/amlogic-s9xxx-armbian/issues/1043
- 另外，我使用armbian-kernal命令时，报错：
```
tinnu@armbian:~/yuga/yuga$ sudo armbian-kernel -u
[ STEPS ] Start updating the compile kernel scripts...
[ INFO ] Start installing update dependencies...
[ INFO ] Start syncing latest scripts...
[ INFO ] Start installing compilation dependencies...
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
注意，选中 'libncurses-dev' 而非 'libncurses5-dev'
注意，选中 'libncurses-dev' 而非 'libncursesw5-dev'
没有可用的软件包 python3-distutils，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

E: 无法定位软件包 libncurses5
E: 软件包 python3-distutils 没有可安装候选
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/4d3b528150041266107ba287cd2424d227002573/recompile#L77-L81

修改这个地址，改为低版本的下载地址。

**Comment by ophub** [comment]
我刚才更新了一下内核编译的脚本，支持选择gcc的版本，你可以for后添加其他版本，地址改到你的下载仓库，我没使用过gcc9，我刚接触的时候他已经gcc-11.3了，未经测试没有添加更多版本，我使用过的历史版本都在仓库备份了编译工具链，可以持续下载使用。

**Comment by ChaoliesTinnu** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/4d3b528150041266107ba287cd2424d227002573/recompile#L77-L81
> 
> 修改这个地址，改为低版本的下载地址。

# RT
- 感谢大佬回复。我fork了一下改了这里到9.2的GCC，但是编译出来的还是13.2的。
- 另外我感觉可能也跟elf编译链应该也有关系，想换gun的编译链，除了改这里还有那里需要改呢？

**Comment by ChaoliesTinnu** [comment]
我上我的nanopc-t4（好像是从armbian官网下的镜像），是可以编译通过（只有部分转换错误，稍微修改即可）
```
tinnu@nanopct4:~/project/yuga$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/aarch64-linux-gnu/12/lto-wrapper
Target: aarch64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 12.2.0-14ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-12/README.Bugs --enable-languages=c,ada,c++,go,d,fortran,objc,obj-c++,m2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-12 --program-prefix=aarch64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-libquadmath --disable-libquadmath-support --enable-plugin --enable-default-pie --with-system-zlib --enable-libphobos-checking=release --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --enable-fix-cortex-a53-843419 --disable-werror --enable-checking=release --build=aarch64-linux-gnu --host=aarch64-linux-gnu --target=aarch64-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 12.2.0 (Ubuntu 12.2.0-14ubuntu1) 
tinnu@nanopct4:~/project/yuga$ uname -a
Linux nanopct4 6.2.0-rc6-media #23.02.1 SMP PREEMPT_DYNAMIC Mon Feb 13 07:49:02 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```
- 用的是 aarch64-linux-gnu ，可能就是 aarch64-none-elf 的问题，明天再看看怎么改这个编译链

**Comment by ChaoliesTinnu** [comment]
目前进度，终于用其他编译链把内核编译出来的了，编译链指定：[arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz](https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz)
编译的log：
```
[ STEPS ] Welcome to compile kernel! 

[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x86_64 ] 

[ STEPS ] Start Initializing Variables...
[ STEPS ] Start checking the toolchain for compiling the kernel...
[ INFO ] Start downloading Armbian rootfs file [ https://github.com/ophub/kernel/releases/download/dev/armbian.tar.xz ]...
[ INFO ] Start downloading the ARM GNU toolchain [ https://armkeil.blob.core.windows.net/developer/Files/downloads/gnu/11.3.rel1/binrel/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu.tar.xz ]...
[ STEPS ] Start querying the latest kernel version...
[ INFO ] (1) Auto query the latest kernel version of the same series for [ 6.1.y ]
[ INFO ] (1) [ 6.1.96 ] is github.com/unifreq/linux-6.1.y/main latest kernel. 

[ INFO ] Kernel compilation toolchain: [ gcc ]
[ INFO ] Kernel from: [ unifreq ]
[ INFO ] Kernel patch: [ false ]
[ INFO ] Kernel arch: [ arm64 ]
[ INFO ] Kernel Package: [ all ]
[ INFO ] kernel signature: [ -yourname ]
[ INFO ] Latest kernel version: [ true ]
[ INFO ] kernel initrd compress: [ xz ]
[ INFO ] Kernel List: [ 6.1.96 ] 
```
查看 vmilinz 版本：
```
Linux version 6.1.96-yourname (root@fv-az881-6) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712, GNU ld (Arm GNU Toolchain 11.3.Rel1) 2.38.20220708) # SMP 
%s version %s (root@fv-az881-6) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712, GNU ld (Arm GNU Toolchain 11.3.Rel1) 2.38.20220708) %s
Linux version 6.1.96-yourname (root@fv-az881-6) (aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712, GNU ld (Arm GNU Toolchain 11.3.Rel1) 2.38.20220708) #1 SMP Tue Jul  2 03:10:37 EDT 2024
pcgcctl
pcgcctl1
```
但是编译驱动（可以编译出armbian镜像，或者不build armbian，直接把kernel拉下来在pc端用交叉编译链，效果时一样的）依然是：
```
make ARCH=arm64 CROSS_COMPILE=/media/tinnu/D_pan/DaydayTech/EmbLinux/rockchip/RK3399/toolchain/arm-gnu-toolchain-11.3.rel1-x86_64-aarch64-none-linux-gnu/bin/aarch64-none-linux-gnu- -C /media/tinnu/D_pan/DaydayTech/EmbLinux/rockchip/RK3399/img/sw799/myself/6.1.96/head-6.1.96-yourname M=/home/tinnu/software/linux_driver/yuge_4G/yuga_driver/yuga_driver modules
make[1]: 进入目录“/media/tinnu/D_pan/DaydayTech/EmbLinux/rockchip/RK3399/img/sw799/myself/6.1.96/head-6.1.96-yourname”
awk: 致命错误： 无法以读模式打开文件“include/generated/asm-offsets.h”(没有那个文件或目录)
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: aarch64-none-elf-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) 13.2.1 20231009
  You are using:           aarch64-none-linux-gnu-gcc (Arm GNU Toolchain 11.3.Rel1) 11.3.1 20220712
  CC [M]  /home/tinnu/software/linux_driver/yuge_4G/yuga_driver/yuga_driver/GobiUSBNet.o
aarch64-none-linux-gnu-gcc: 错误： ‘-mstack-protector-guard-offset=’缺少参数
make[2]: *** [scripts/Makefile.build:250：/home/tinnu/software/linux_driver/yuge_4G/yuga_driver/yuga_driver/GobiUSBNet.o] 错误 1
make[1]: *** [Makefile:2009：/home/tinnu/software/linux_driver/yuge_4G/yuga_driver/yuga_driver] 错误 2
make[1]: 离开目录“/media/tinnu/D_pan/DaydayTech/EmbLinux/rockchip/RK3399/img/sw799/myself/6.1.96/head-6.1.96-yourname”
make: *** [Makefile:23：rk2] 错误 2
```
还是识别成 aarch64-none-elf-gcc (Arm GNU Toolchain 13.2.rel1 (Build arm-13.7)) ，搞不清楚问题在哪。
准备看看用官方的换个dtb看看能不能启动。

**Comment by ChaoliesTinnu** [comment]
# 终于解决

## Gobinet拨号上网的失败尝试

### 成功编译Gobinet驱动
- mstack-protector-guard-offset问题不是编译链版本导致的，编译链那个问题完全可以无视。在header里面Makefile里面注释掉mstack-protector-guard-offset相关选项即可。注释掉之后报了其他一些错误，主要是asm相关头文件缺失。
- 重新观察之前header的头文件，发现asm相关缺了很多文件
  - include/generated
  - arch/arm64/include/generated
- 重新下载最新的内核和系统镜像，发现5.xx的依然有这个问题，但6.1.xx的已经修复（包括修复mstack-protector-guard-offset问题）。sw799 noble系统用的6.1.xx，所以可以直接整。
- 直接编译报了一些错误，按照如下方式修改绕过去：
- 3275 QMIDevice.c
	```C
	int ref = atomic_read( &pDev->mQMIDev.mCdev.kobj.kref.refcount );
	int ref = atomic_read( (const atomic_t *)&pDev->mQMIDev.mCdev.kobj.kref.refcount );
	```
- 667 GobiUSBNet.c
	```C
	random_ether_addr(pDev->net->dev_addr);
	eth_random_addr(pDev->net->dev_addr);
	```
- 672 GobiUSBNet.c
	- 注释掉
	- /usr/src/linux-headers-6.1.109-ophub/include/linux/netdevice.h
		- const unsigned char	*dev_addr;
	- 内核可能发生了改变

### 串口
- `sudo modprobe usbserial vendor=0x05c6 product=0x9025` 命令无法把4G模块的ttyUSB端口弄出来，找了一下，发现需要用`modprobe option`
	- modprobe option
	- echo "05c6 9025" > /sys/bus/usb-serial/drivers/option1/new_id
- minicom -D /dev/ttyUSB3

### 失败的挂载
- lsmod
	- 看到有 usbnet qmi_wwan
	- 没有 usbnet 要加载	`modprobe usbnet`
	- qmi_wwan 要去掉	`rmmod qmi_wwan`
- insmod GobiNet.ko
	- 可以从 lsmod 看到 GobiNet
	- ifconfig -a 有 usb0

- 在 `minicom -D /dev/ttyUSB3`里面设置拨号
  ```
  AT$QCRMCALL=1,1,1,2,1
  AT$QCRMCALL?
  ```
- Gobinet生成的usb0网卡能够正常获取IP，但始终ping不通。而且60s之后usb0网卡准时掉线。分析dmesg和驱动，发现：
  ```shell
  [ 4564.616695] ---[ end trace 0000000000000000 ]---
  [ 4565.555766] IPv6: ADDRCONF(NETDEV_CHANGE): usb0: link becomes ready
  [ 4625.972150] Device unresponsive to QMI
  ```
- Device unresponsive to QMI 意味着Gobinet始终没有连上，驱动设置了60s超时卸载。

## wwan0成功驱动
- 这时候偶然想到wwan0，一开始以为是EC20版本的驱动，后来查了下sw799好像只有YUGA版本，没有移远的，这个wwan0可能是已经适配好的，预测一番测试：
- 参考了树莓派挂载 EC25 的例子： [Test Quectel EC25-A LTE Cat 4 mini PCIe module](https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/344#issuecomment-1012284507)

#### wwan方式
- sudo apt install libqmi-utils udhcpc

- sudo ip link set wwan0 down
- echo 'Y' | sudo tee /sys/class/net/wwan0/qmi/raw_ip
- sudo ip link set wwan0 up

- sudo qmicli -d /dev/cdc-wdm0 --dms-set-operating-mode='online'
- 多执行几次

- sudo qmicli -d /dev/cdc-wdm0 --wda-get-data-format
- sudo qmicli -p -d /dev/cdc-wdm0 --device-open-net='net-raw-ip|net-no-qos-header' --wds-start-network="apn='super',ip-type=4" --client-no-release-cid
- sudo udhcpc -q -f -i wwan0

tinnu@armbian:~$ sudo udhcpc -q -f -i wwan0
udhcpc: started, v1.36.1
Dropped protocol specifier '.udhcpc' from 'wwan0.udhcpc'. Using 'wwan0' (ifindex=5).
udhcpc: broadcasting discover
udhcpc: broadcasting select for 10.***.62.**, server 10.***.62.**
udhcpc: lease of 10.***.62.** obtained from 10.***.62.**, lease time 7200
Dropped protocol specifier '.udhcpc' from 'wwan0.udhcpc'. Using 'wwan0' (ifindex=5).

##### 示例

- 直接ping百度：指定wwan0 ping不通，但指定eth0 ping通
```shell
tinnu@armbian:~$ ping -I wwan0 -c 500 baidu.com
PING baidu.com (39.156.66.10) from 10.10.28.215 wwan0: 56(84) bytes of data.
```
```shell
tinnu@armbian:~$ ping -I eth0 -c 500 baidu.com
PING baidu.com (110.242.68.66) from 192.168.3.31 eth0: 56(84) bytes of data.
64 bytes from 110.242.68.66: icmp_seq=1 ttl=50 time=55.3 ms
64 bytes from 110.242.68.66: icmp_seq=2 ttl=50 time=55.4 ms
```
- 仔细研究会发现baidu的IP其实是110.242.68.66，但自动获取的DNS是39.156.66.10，一旦通过eth0 ping过一次，wwan0的DNS也被刷新了，这时候直接ping百度也能通。

- 或者重启之后，保持DNS是旧的，但直接ping百度的IP也可以。（我特意吧wlan0网卡down掉，eth0网卡外部向上的外网网线拔掉,通层设备PC端的WIFI也全部断开来测试,保证不会是走了某种奇怪的路由）

```shell
tinnu@armbian:~$ ping -I wwan0 -c 500 110.242.68.66
PING 110.242.68.66 (110.242.68.66) from 10.**.28.*** wwan0: 56(84) bytes of data.
64 bytes from 110.242.68.66: icmp_seq=1 ttl=49 time=111 ms
64 bytes from 110.242.68.66: icmp_seq=2 ttl=49 time=85.4 ms
64 bytes from 110.242.68.66: icmp_seq=3 ttl=49 time=99.6 ms
64 bytes from 110.242.68.66: icmp_seq=4 ttl=49 time=83.5 ms
64 bytes from 110.242.68.66: icmp_seq=5 ttl=49 time=103 ms
```

- 显然，DNS有问题，但如果直接ping IPv4地址是通的，说明网络其实是通的。
- 至于这个DNS，应该改改interfaces之类的配置文件可以解决。
