### ISSUE TITLE
Need Tutorial

### ISSUE THREAD

**Issue by tugoes** [ophub/amlogic-s9xxx-armbian#24]
hello

please help me how i can booting the armbian on my device( ZTE B80H), i already burn the images to sd card with balena etcher,after i put the sd card to my device, what sould i do?to make the armbian booting,and after booting what command for instaling/copy the armbian on sd card to emmc

thank you

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-stb


https://github.com/ophub/amlogic-s9xxx-armbian#install-to-emmc-and-update-instructions

**Comment by tugoes** [comment]
Is this same way to booting with armbian buster? Coz i just the want install armbian buster on my tv box,not open wrt

Thx u

**Comment by ophub** [comment]
The same.
