### ISSUE TITLE
Could you support the "Bullseye" option to rebuild Armbian on Github Action?

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#240]
At current, there are many good options  to input when rebuild Armbian on Action. By the way, it is only supported to build Focal. 
That's great if you could support the input option to build Bullseye.
Thank you.
<img width="1330" alt="Screen Shot 2022-04-16 at 17 57 37" src="https://user-images.githubusercontent.com/22479095/163672386-bdf770cf-c1c5-4519-bd77-3864590764b8.png">

**Comment by ophub** [comment]
![Snip20220416_3](https://user-images.githubusercontent.com/68696949/163672776-04fd45f8-054d-4f7f-a689-03547aeed7b3.png)

**Comment by dinhchinh82** [comment]
I got the idea. By the way, if use the link (https://armbian.tnahosting.net/dl/lepotato/archive/Armbian_22.02.1_Lepotato_bullseye_current_5.10.102.img.xz), I will only get the Bullseye 22.02.1 kernel 5.10 , right?

How to to if I want to rebuild bullseye 22.05 kernel 5.15.x?

**Comment by dinhchinh82** [comment]
I can see only 5.10 kernel images are available from the link below:
<img width="547" alt="image" src="https://user-images.githubusercontent.com/22479095/163673195-a0013221-5e65-41ba-8eed-6eb232dacaa0.png">

**Comment by ophub** [comment]
The kernel fills in what you need in the following dialog box, the kernel in the firmware will be deleted, and the kernel will be replaced with the update you specified.

**Comment by dinhchinh82** [comment]
@ophub I understand about the kernel now.

By the way, how to rebuild bullseye 22.05 if the original firmware only support 22.02.1?
One more thing, are there any much difference between 22.05 and 22.02?

Thank you.

**Comment by ophub** [comment]
The build only changes the kernel and bootstrap, and everything else is kept unchanged. It is still 22.02 compiled with 22.02, not 22.05. This is the version number.

**Comment by dinhchinh82** [comment]
> The build only changes the kernel and bootstrap, and everything else is kept unchanged. It is still 22.02 compiled with 22.02, not 22.05. This is the version number.

So if I rebuild armbian based on [Armbian_22.02.1_Lepotato_bullseye_current_5.10.102.img.xz], it will produce the same output as I run the "Build armbian" with bullseye option, right? The version number (22.02 or 22.05) has no meaning, right?

Thank you.

**Comment by ophub** [comment]
rebuild is not the latest, this is an official address that is regularly released, maybe updated once a month?
I also have one that uses the current official source code to compile in real time, which is newer than this.

**Comment by dinhchinh82** [comment]
> rebuild is not the latest, this is an official address that is regularly released, maybe updated once a month? I also have one that uses the current official source code to compile in real time, which is newer than this.

Yes. I know this one and already build successfully but take 2 hours or more. Anyway, I understand all the situation. Thank you very much for your detail explanation.

**Comment by JFLim1** [comment]
Hi @ophub,

Can I make a suggestion.  I understand you do not pre-build Debian Bullseye firmware was to minimize storage space.  

Would it be possible to build Debian Bullseye image once a week or any regular timing you feel is appropriate so that users that prefer Bullseye can download pre-build firmware.

Or have a archive for the latest Bullseye you have pre-build.

Many TV Box users, including me, might not have the knowledge or equipment to build the firmware.

This is just a suggestion.

**Comment by dinhchinh82** [comment]
> Hi @ophub,
> 
> Can I make a suggestion. I understand you do not pre-build Debian Bullseye firmware was to minimize storage space.
> 
> Would it be possible to build Debian Bullseye image once a week or any regular timing you feel is appropriate so that users that prefer Bullseye can download pre-build firmware.
> 
> Or have a archive for the latest Bullseye you have pre-build.
> 
> Many TV Box users, including me, might not have the knowledge or equipment to build the firmware.
> 
> This is just a suggestion.

I also agree with your idea. 
To minimize the space of Github action, there is only need to build Bullseye for the most popular boxes such as S905X3 and S905W.

**Comment by JFLim1** [comment]
Best to build for all the currently supported SOC.  Thnaks.

**Comment by ophub** [comment]
The build is easy to operate, the first step is fork, and the second step starts at the actions point.

The releases provided by github.com have unlimited space and unlimited traffic. But there is only one such good free service provider.

One of my builds will take up 20G of releases storage space. It always feels like a waste of resources.

**Comment by dinhchinh82** [comment]
@ophub I just tried to rebuild armbian using my previous images but got the error as below:
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/22479095/163679503-27766dcc-c28c-4f24-b568-b2ed87b737be.png">

The based image is built after fork your source code since Mar 27, 2022.
https://github.com/dinhchinh82/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_03.27.2030/Armbian_22.05.0_Aml_s905x3_bullseye_5.15.31_2022.03.27.2024.img.gz

Please note I got rebuild successfully this afternoon if if I use the based image below: https://armbian.tnahosting.net/dl/lepotato/archive/Armbian_22.02.1_Lepotato_bullseye_current_5.10.102.img.xz

I just confused what is the main reason. As the log build, the error related to the output of command "cat: etc/os-release".

> (1.1) Start building Armbian [ s905x3 - 5.15.34 ]. Remaining space is 42G.
>  [ s905x3 - 5.15.34 ]  (1/6) Confirm version type.
>  [ s905x3 - 5.15.34 ]  (2/6) Extract old armbian files.
> cat: etc/os-release: No such file or directory
>  [ Error ] The [ etc/os-release: ID ] is invalid.
> Error: Process completed with exit code 1.

**Comment by ophub** [comment]
This original armbian file that records version information needs to be identifiable. It needs to be used when installing docker and other services in the future. Has the official changed? I'll test it.

**Comment by dinhchinh82** [comment]
> This original armbian file that records version information needs to be identifiable. It needs to be used when installing docker and other services in the future. Has the official changed? I'll test it.

I'm not sure there is any changes recently.

By the way, is there any difference from the the output of 2 cases below?

case 1: Armbian 22.05.0 kernel 5.15.29, built from 2022.03.19, then update to kernel 5.15.34.

case 2: Armbian 20.05.0 kernel 5.15.34 built by 2022.04.16.

Both cases above have same kernel but I confused other parts are the same or not? 

Thank you.

**Comment by ophub** [comment]
It's the same after updating to the `latest` using both `apt-update` and `armbian-update`

**Comment by ophub** [comment]
You recompile one, I tested Bullseye normally

https://github.com/ophub/amlogic-s9xxx-armbian/runs/6048710032?check_suite_focus=true

**Comment by JFLim1** [comment]
Hi @ophub 

Thanks for the Bullseye pre-build. Now you see it and now it's gone.
