### ISSUE TITLE
希望大神添加orangepi-5-plus的支持

### ISSUE THREAD

**Issue by yonggedebaqi** [ophub/amlogic-s9xxx-armbian#2400]
希望大神添加orangepi-5-plus的支持，我手动添加rk3588-orangepi-5-plus.dtb 修改uEnv.txt文件到（Armbian_24.8.0_rockchip_rock5b_bookworm_5.10.160_server
）固件，测试了几个月使用rk3588-orangepi-5-plus正常。

[rk3588-orangepi-5-plus.rar.txt](https://github.com/user-attachments/files/16050982/rk3588-orangepi-5-plus.rar.txt)

**Comment by yonggedebaqi** [comment]
rk3588-orangepi-5-plus.rar.txt修改成rk3588-orangepi-5-plus.rar

**Comment by yonggedebaqi** [comment]
![rk3588-orangepi-5-plus](https://github.com/ophub/amlogic-s9xxx-armbian/assets/43800614/6f58774d-90cd-4fb6-a788-f40a2f58315c)

**Comment by ophub** [comment]
[rk3588-orangepi-5-plus.dtb.zip](https://github.com/user-attachments/files/16051300/rk3588-orangepi-5-plus.dtb.zip)

你发的是dtb，我到armbian官方的内核仓库复制了一份dts，在rockchip/5.10.y下编译正常，附件中是我编译的dtb，你把这个dtb替换到你的/boot/dtb/rockchip/目录下，覆盖同名文件，重启试试，如果可以的话我把这个dts源码文件提交到f大的内核仓库里，方便日后升级维护。

除了这个dtb文件外，其他的都使用rock5b默认的配置可以正常使用？

**Comment by yonggedebaqi** [comment]
大神好！测试你发的rk3588-orangepi-5-plus.dtb启动正常。

**Comment by yonggedebaqi** [comment]
rock5b dtb文件我测试启动失败。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases

根据你的测试情况，我添加好了，在今天的4个armbian系列里都打包好了，你再测试下完整固件。

**Comment by yonggedebaqi** [comment]
好的
256G TF卡有文件IMG文件写入U盘启动不了，明天再找张TF卡试试。

**Comment by ophub** [comment]
好的，多谢测试反馈

**Comment by planxx** [comment]
@ophub 大佬，能一起添加orangepi-5-pro的支持吗？我看官方仓库里也有5-pro的dts，手上有设备，可以随时配合测试

**Comment by taikong1988** [comment]
佬 Orange Pi Zero3 能支持吗?

**Comment by lihuabing1** [comment]
最近入手了一个orange pi 5 plus,32G内存，想跑QWNE3-9B模型，但是需要NPU CMA=4G，而默认的CMA只有256M，能麻烦大神编译一个4G的版本吗？
