### ISSUE TITLE
大佬可以帮忙适配一下tpm312吗

### ISSUE THREAD

**Issue by GoldenHuskyDog** [ophub/amlogic-s9xxx-armbian#2401]
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [4+16]

**Armbian Version | 系统版本**
 - Kernel Version: [5.10.60]
 - Release: [focal]
下载链接：http://files.kos.org.cn/rockchip/lx-r3s/

Describe the bug | 问题描述
hdmi无输出

**Comment by ophub** [comment]
你是要添加lx-r3s还是tpm312呢？
你的意思是这里下载的tpm312你测试了可以使用，给添加到编译列表里？

**Comment by robinZhao** [comment]
> 你是要添加lx-r3s还是tpm312呢？ 你的意思是这里下载的tpm312你测试了可以使用，给添加到编译列表里？

这个版本hdmi输出有问题，显示器没反应，用usb的hdmi视频采集器有输出，但是显示混乱

**Comment by ophub** [comment]
设备在另外一个帖子里添加了。

https://github.com/ophub/amlogic-s9xxx-armbian/issues/2403
