### ISSUE TITLE
sysctl -p 报错

### ISSUE THREAD

**Issue by fflrichard** [ophub/amlogic-s9xxx-armbian#2402]
本身设备是hk1box
试了最新的几个版本，都报如下错误：
sysctl: cannot stat /proc/sys/net/netfilter/nf_conntrack_helper: No such file or directory

**Comment by adoyle-h** [comment]
@ophub 我刷的 Armbian_25.11.0_amlogic_a311d_trixie_6.1.155_server_2025.10.10.img.gz  ，但似乎这个内核没有编译 nf_conntrack_helper？

```
sudo modprobe nf_conntrack_helper
modprobe: FATAL: Module nf_conntrack_helper not found in directory /lib/modules/6.12.51-ophub
```

**Comment by adoyle-h** [comment]
从 linux kernel 4.7 起，net.netfilter.nf_conntrack_helper 的默认值就是 0。
在 kernel 5.19 中，尚存在 nf_conntrack_helper  参数。https://www.kernel.org/doc/html/v5.19/networking/nf_conntrack-sysctl.html
自 kernel 6.0 起，nf_conntrack_helper 参数就不存在了。 https://www.kernel.org/doc/html/v6.0/networking/nf_conntrack-sysctl.html

因此对于 kernel 6，需要在  /etc/sysctl.conf 中移除 net.netfilter.nf_conntrack_helper 这行。
