### ISSUE TITLE
请求 增加适配 rk3399-tpm312-main

### ISSUE THREAD

**Issue by wanglixiang90** [ophub/amlogic-s9xxx-armbian#2403]
**Device Information | 设备信息**
 - SOC: rk3399
 - Model tpm312-main

**Armbian Version | 系统版本**
 - Kernel Version: 6.6.33
 - Release:  armbian/bookworm  + Armbian/noble

**Describe the bug | 问题描述**
请求 增加 适配 这个rk3399硬件
dtb 文件下载地址： https://github.com/Lemon1151/rk33xx-armbian/blob/main/build-armbian/armbian-files/platform-files/rockchip/bootfs/dtb/rockchip/rk3399-tpm312.dtb
编译仓库：https://github.com/Lemon1151/rk33xx-armbian

板子照片
![123456](https://github.com/ophub/amlogic-s9xxx-armbian/assets/13639913/bff9f621-d9ac-4837-87df-65b98e617ee6)

问题：
hdmi 无显示输出，需要调整dtb显示输出端口；
minipcie 需要开启使能。

**Comment by ophub** [comment]
```
/dts-v1/;
#include <dt-bindings/pwm/pwm.h>
#include <dt-bindings/input/input.h>
#include <dt-bindings/interrupt-controller/irq.h>
#include "rk3399.dtsi"
#include "rk3399-opp.dtsi"

/ {
	model = "RK3399 TPM312";
	compatible = "rk3399,tpm312", "rockchip,rk3399";

	/delete-node/ display-subsystem;

	aliases {
		ethernet0 = &gmac;
		mmc0 = &sdhci;
		mmc1 = &sdmmc;
		mmc2 = &sdio0;
	};

	chosen {
		bootargs = "earlycon=uart8250,mmio32,0xff1a0000 swiotlb=1 coherent_pool=1m";
		stdout-path = "serial2:1500000n8";
	};

```

在dts里，作者申明删除了显示支持，原因未知：`/delete-node/ display-subsystem;`

**Comment by wanglixiang90** [comment]
有时间的话可以在内核中增加 2.5G 网卡驱动 [e.g.  realtek 8125 8152 8156(usb) . intel i225 i226 ... ]

**Comment by wanglixiang90** [comment]
在你提供的dtb 基础上 修改并开启 fdi / hdmi / vop，设置  status = "okay" 后 可以开启 hdmi 显示，但是显示效果比较差（画面比较浑浊，可能是gpu/hdmi 驱动没有适配好），另外此版本的 wifi 网卡没了，得恢复 wlan0 网卡。
[rk3399-tpm312-new.zip](https://github.com/user-attachments/files/16088372/rk3399-tpm312-new.zip)

**Comment by wanglixiang90** [comment]
[Rockchip RK3399 - Mali-T860 GPU驱动（mesa+Panfrost）](https://www.cnblogs.com/zyly/p/17459196.html)

**Comment by ophub** [comment]
[rk3399-tpm312.dts.zip](https://github.com/user-attachments/files/16091985/rk3399-tpm312.dts.zip)

**Comment by xiaomeng9597** [comment]
> 在你提供的dtb 基础上 修改并开启 fdi / hdmi / vop，设置 status = "okay" 后 可以开启 hdmi 显示，但是显示效果比较差（画面比较浑浊，可能是gpu/hdmi 驱动没有适配好），另外此版本的 wifi 网卡没了，得恢复 wlan0 网卡。 [rk3399-tpm312-new.zip](https://github.com/user-attachments/files/16088372/rk3399-tpm312-new.zip)

请发修改过的原始dts文件出来

**Comment by robinZhao** [comment]
> 在你提供的dtb 基础上 修改并开启 fdi / hdmi / vop，设置 status = "okay" 后 可以开启 hdmi 显示，但是显示效果比较差（画面比较浑浊，可能是gpu/hdmi 驱动没有适配好），另外此版本的 wifi 网卡没了，得恢复 wlan0 网卡。 [rk3399-tpm312-new.zip](https://github.com/user-attachments/files/16088372/rk3399-tpm312-new.zip)
显示器还是不会亮，hdmi采集器可以显示，图像如下
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4110466/b50b68f9-26e9-4a27-a3a7-34512c9815f3)

**Comment by robinZhao** [comment]
> > 在你提供的dtb 基础上 修改并开启 fdi / hdmi / vop，设置 status = "okay" 后 可以开启 hdmi 显示，但是显示效果比较差（画面比较浑浊，可能是gpu/hdmi 驱动没有适配好），另外此版本的 wifi 网卡没了，得恢复 wlan0 网卡。 [rk3399-tpm312-new.zip](https://github.com/user-attachments/files/16088372/rk3399-tpm312-new.zip)
> > 显示器还是不会亮，hdmi采集器可以显示，图像如下
> > ![image](https://private-user-images.githubusercontent.com/4110466/345846263-b50b68f9-26e9-4a27-a3a7-34512c9815f3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwOTk3NzgsIm5iZiI6MTcyMDA5OTQ3OCwicGF0aCI6Ii80MTEwNDY2LzM0NTg0NjI2My1iNTBiNjhmOS0yNmU5LTRhMjctYTNhNy0zNDUxMmM5ODE1ZjMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDRUMTMyNDM4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWQ0NGY1Mzg5ZjQ0NGNlNWIzNjY2Mjc4MGY1MGZkNjk0YmRhNjZiZTUyN2MwMGE0ZWMxZGRhNTc5MDMxOGI1MCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QTNEjBkLOcIsGj2diA_TGiXL_FI_gq7mTnPXXLeEhJo)

另外wifi网卡也在啊

**Comment by robinZhao** [comment]
谁帮忙搞下hdmi显示问题啊

**Comment by robinZhao** [comment]
![tpm312](https://github.com/user-attachments/assets/e261c277-2dd9-4139-ba7e-29188aa2a5a3)
tpm312hdmi显示浑浊的问题已经解决，dtb是通过反编译原始android dtb改造的
有两个问题，一个是dmesg中有如下报错，可能和i2s声音接口有关
[   20.013909] rockchip-i2s: probe of ff880000.i2s failed with error -2
[   20.037244] rockchip-i2s: probe of ff8a0000.i2s failed with error -2
另外一个是每隔几分钟报个无线网卡的错误,估计得更新驱动解决
`[  440.467545] rtw_8821cu 2-1.1:1.2: failed to download firmware
[  440.485324] rtw_8821cu 2-1.1:1.2: leave idle state failed
[  440.509189] rtw_8821cu 2-1.1:1.2: failed to leave ips state
[  440.514908] rtw_8821cu 2-1.1:1.2: failed to leave idle state`
期待有大佬继续优化

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.6.y/blob/main/arch/arm64/boot/dts/rockchip/rk3399-tpm312.dts

在这个源码里，你改动了什么地方，提交到上游f大的这个内核仓库里，每次更新以这里编译的为准。

**Comment by robinZhao** [comment]
> ![tpm312](https://private-user-images.githubusercontent.com/4110466/354180372-e261c277-2dd9-4139-ba7e-29188aa2a5a3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzAwODAsIm5iZiI6MTcyMjU2OTc4MCwicGF0aCI6Ii80MTEwNDY2LzM1NDE4MDM3Mi1lMjYxYzI3Ny0yZGQ5LTQxMzktYmE3ZS0yOTE4OGFhMmE1YTMuanBnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDJUMDMzNjIwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NzI2YWRlZGI5YmJmYTYxYTBjNTkyYWIwNjA1YjE5ZDg0MjJmODMzMWZmYTc5MzZlNjMxOTU0YzgzYWNiN2RkYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YbyaKa3imUtw2_yMXTpgkiRTFtkQ5ONa27VFfI4ax00) tpm312hdmi显示浑浊的问题已经解决，dtb是通过反编译原始android dtb改造的 [https://github.com/ophub/amlogic-s9xxx-armbian/pull/2457](url) 有两个问题，一个是dmesg中有如下报错，可能和i2s声音接口有关 [ 20.013909] rockchip-i2s: probe of ff880000.i2s failed with error -2 [ 20.037244] rockchip-i2s: probe of ff8a0000.i2s failed with error -2 另外一个是每隔几分钟报个无线网卡的错误,估计得更新驱动解决 [ 440.467545] rtw_8821cu 2-1.1:1.2: failed to download firmware [ 440.485324] rtw_8821cu 2-1.1:1.2: leave idle state failed [ 440.509189] rtw_8821cu 2-1.1:1.2: failed to leave ips state [ 440.514908] rtw_8821cu 2-1.1:1.2: failed to leave idle state 期待有大佬继续优化

驱动应该是加载了，wifi功能也正常，就是会一会报一下这个错误，可能和wifi的休眠功能有关

**Comment by ophub** [comment]
无线不使用就关闭了

**Comment by robinZhao** [comment]
> https://github.com/unifreq/linux-6.6.y/blob/main/arch/arm64/boot/dts/rockchip/rk3399-tpm312.dts
> 
> 在这个源码里，你改动了什么地方，提交到上游f大的这个内核仓库里，每次更新以这里编译的为准。
> 
> https://github.com/ophub/kernel/blob/571280fe3e19adba194c737e6fa513b9d79f1a23/kernel-config/release/general/config-6.6#L3284 https://github.com/ophub/firmware/tree/main/firmware/rtw88
> 
> rtw8821cu驱动和固件都有，查查什么原因导致无法加载的

提交了，dtb反编译修改的，不是很易读，用仓库的dts修改不成功，总是花屏闪烁，找不到问题

**Comment by Angel0726** [comment]
> 我在这个仓库找到一个dts源文件，可以在源文件基础上修改，进行编译测试。
> 
> [rk3399-tpm312.dts.zip](https://github.com/user-attachments/files/16091985/rk3399-tpm312.dts.zip)
> 
> https://github.com/xiaomeng9597/iStoreOS-For-RK33XX/blob/main/configfiles/rk3399-tpm312.dts

能够将hdmi等修改好的版本，至今release发布吗

**Comment by Angel0726** [comment]
> [Rockchip RK3399 - Mali-T860 GPU驱动（mesa+Panfrost）](https://www.cnblogs.com/zyly/p/17459196.html)

这个怎么用

**Comment by robinZhao** [comment]
hdmi已经好了吧

**Comment by XjyfJrong** [comment]
一直报错rtw_8821cu 1-1.1:1.2: failed to send h2c command ，各位大神怎么解决的

**Comment by planxx** [comment]
无线蓝牙均异常……
