### ISSUE TITLE
H96MAX M2 RK3528 - New box 

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#2404]
**Device Information | **
 - SOC: RK3528
 - Model H96MAX M2 

**Armbian Version |
 - Kernel Version: tried Linux 6.6.36
 - Release:  Armbian Bookworm

**Describe the bug:
I wanted to add a new box to the armbian/ophub collection. 
It runs Android 13. Chipset Rockchip RK3258. WIFI6 + BT: B-LINK BL-M8800DS1. 1000M LAN: Realtek RTL8211F
Bought it: https://nl.aliexpress.com/item/1005005843644900.html
Info: https://www.h96tvbox.com/product/h96-max-m2-android-tv-box/
Recovery image: https://boxput.notion.site/H96-Series-Frieware-b314bb2353ba4f08979edfca10db54fe 
H96 Max 3528 -> IMG file.

The DTB i extracted from the android image can be found in: [DTB](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/VontarX3Files/01_dtbdump_rockchip%2Crk3528-evb2-ddr3-v10.dtb)

I have issues with the DTB running on Armbian, hopefully you could help me with that, to see if anything needs to be modified. 

Please provide a detailed description of the issue and, if necessary, attach a screenshot.

Photos: 
![Voorkant](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/aa596595-83c5-494d-8dbc-64009859aefa)
![Achterkant](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/0edb108d-4247-42d0-8c0f-f657416d5eec)
![PCB2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/278c8290-641a-467d-bee2-48a322369bf8)
![pcb](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/4f3168cd-373c-42ee-b804-2a4259a3c84c)
![Chip2](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/529c291f-b5fd-4f46-b07a-74ee4e6a8820)
![Chip1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/e5e1905f-7816-42b9-8258-d744a26d0648)
![Portrs](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/985ee6a0-6cd2-4c69-bfaa-a99db9027fbf)

**Comment by d5stick** [comment]
[uboot.img.gz](https://github.com/user-attachments/files/16131333/uboot.img.gz)
The device will not boot from USB. I was trying to get the following done, But am not able to compile the u-boot img.
`CONFIG_ROCKCHIP_USB_BOOT=y`

I tried to follow this [procedure ](https://github.com/ilyakurdyukov/rk3528-tvbox).
I flashed the uboot with the armbian uboot img file, but no hdmi or ethernet connectivity on the box.,

**Comment by d5stick** [comment]
Well it was an adventure; 
I compiled on my Ubuntu laptop a version of Armbian:
`git clone --depth=1 https://github.com/armbian/build armbian-build`

-Used the following patches from [ilyakurdyukov](https://github.com/ilyakurdyukov/rk3528-tvbox) and included them in the armbian-build user patches. 
u-boot: rk3528-tvbox-defconfig.patch
u-boot: no_read_limit.patch
u-boot: gray_square_logo.patch
Kernel: fix_drm_getunique_crash.patch
Kernel: sai_clk_auto_on.patch

`./compile.sh build BOARD=mangopi-m28k BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no KERNEL_GIT=shallow RELEASE=bookworm`

Extract the u-boot img from Armbian to get the value "CONFIG_ROCKCHIP_USB_BOOT=y" in the u-boot.
`dd if=armbian_version_.img bs=1M count=4 skip=8 > uboot.img`

Flash the uboot.img to the device with rkdeveloptool (install with apt install)
Hold the pin in the AV port, connect a USB A to USB A cable and check for connectivity:
`rkdeveloptool list`

When the device  is present and in "loader" mode, flash the uboot file.
`rkdeveloptool write-partition u-boot uboot.img`

Burn the armbian_version_.img with BalenaEtcher on a flashdrive (USB2!)
Boot the device, it will show the boot logo of the box and after a minute it boots Armbian. 
The [DTB ](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/VontarX3Files/rk3528-mangopi-m28k.dtb)used now is from Mangopi M28k, i hoped @ophub  could help me create a DTB for this device. 

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/2bf371e4-9d1f-4af4-9788-d459c74239f4)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/f33567a2-68f5-44f8-819f-dad0de117b5e)

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/ce5c8977-ff93-4290-813b-0960f68c11b4)


What is working on this box?
Ethernet is working. 
HDMI is working 
USB is working, as it boots from there. 

What is not working?
WLAN is not working. 
Ophub's build of Armbian. 
Install to EMMC.

**Comment by ophub** [comment]
Based on your description, you are using the linux-rockchip kernel. You can check if there are wireless drivers available. 
https://github.com/armbian/linux-rockchip/tree/rk-6.1-rkr1/drivers/net/wireless

**Comment by d5stick** [comment]
The u-boot i flashed on the device: [u-boot](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/VontarX3Files/uboot.img)

**Comment by ophub** [comment]
A single u-boot should be 16M, not 4M.
According to armbian's compilation, the u-boot you are using should be in a directory like `/usr/lib/u-boot-m28k-xxx`. Please copy and upload the files in this u-boot directory.
Are you using the default dtb file `https://github.com/armbian/linux-rockchip/blob/rk-6.1-rkr1/arch/arm64/boot/dts/rockchip/rk3528-mangopi-m28k.dts`?

**Comment by ophub** [comment]
Please upload the u-boot from the /usr/lib/u-boot-xxxx directory in the Armbian.img build you created using compile.sh. I need it to rebuild Armbian.

**Comment by d5stick** [comment]
I exported files from usr/lib/u-boot
hinlink_rk3528_defconfig
LICENSE
platform_install.sh

I exported files from usr/lib/linux-u-boot-vendor-mangopi-m28k
u-boot.itb
idbloader.img

[Files](https://github.com/d5stick/amlogic-s9xxx-armbian/tree/main/test)

Let me know if this is sufficient.

**Comment by ophub** [comment]
I compiled the firmware for h96-max-m2 in [releases](https://github.com/ophub/amlogic-s9xxx-armbian/releases). Please test it when you have time.

I have uploaded the u-boot to the following link: https://github.com/ophub/u-boot/tree/main/u-boot/rockchip/h96-max-m2
The `uboot.img` used for USB booting is also in this directory.

I have uploaded the `Android system` to the following link: https://github.com/ophub/kernel/releases/tag/tools

**Comment by d5stick** [comment]
The android image, i do not see in the tag/tools. 

About the testing; 
The u-boot i extracted from my Armbian image that i flashed on the device is using kernel 6.1.
The compiled one you created uses kernel 5.10.160. I flashed it to my usb drive but it will not boot. 

Could it be that the patches i shared from [ilyakurdyukov](https://github.com/ilyakurdyukov) should be applied too? 
Or is the kernel version the issue?

Besides that, could the drivers be included for the wireless? [Radxa-pkg](https://github.com/radxa-pkg/aic8800/tree/main/debian)

To make things easy, i shared the image i have working on the USB drive: [Armbian 6.1](https://drive.google.com/file/d/1AknTYM7j4nDL5zVLGSCC92att8UuwMc0/view)

**Comment by ophub** [comment]
Android System Backup Name:
https://github.com/ophub/kernel/releases/tag/tools
![Snip20240710_1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/a8fd3dea-ff4c-4844-bfaa-f35ba6131275)

Both kernels, `5.10.160` and `6.1.43`, belong to the `linux-rockchip` series and should theoretically work with the rk3528. I'm using the kernel repository maintained by Flippy: https://github.com/unifreq/linux-5.10.y-rk35xx. I tested and successfully compiled this DTS locally yesterday and already submitted it to their repository: https://github.com/unifreq/linux-5.10.y-rk35xx/commit/1af20a7a0aa4a26da13bf69493b23096ae5798e1.

I've updated the boot files. Could you please try this new 5.10.160 build I made and see if it boots?

**Comment by d5stick** [comment]
The H96MAX M2 is able to boot to the new image you compiled; 5.10.160 with the mangopi_m28k DTB.

HDMI does not work at first boot. SSH was working at first boot. 
After a reboot the HDMI starts working. After several reboots HDMI stays working. 

As expected no bt and wifi

Ethernet stops working after first reboot, i tried to activate the connection with nmtui; 
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/a1c56502-3616-42f4-9d46-bff70546d50c)
Removed the connection in nmtui, rebooted, Cleared blocked connections with armbian-config.
Tried to clear possible blocked interfaces and configure static. Seems to be working. 
Reboot again, connection broken again. nmtui does not show a connection to activate anymore.

**Comment by ophub** [comment]
`armbian-update -k 6.1.43-rk35xx-rkr1`

Try this linux-rockchip kernel

**Comment by d5stick** [comment]
The kernel ` 6.1.43-rk35xx-rkr1` works better.  HDMI responds, Ethernet responds even after multiple reboots. 
I have not tried the install emmc methods for Rockchip tho, need to verify that one.

Ethernet info in dmesg:
```
[   38.395281] rk_gmac-dwmac ffbe0000.ethernet end0: PHY [stmmac-0:01] driver [RTL8211F Gigabit Ethernet] (irq=POLL)
[   38.399273] dwmac4: Master AXI performs any burst length
[   38.402374] rk_gmac-dwmac ffbe0000.ethernet end0: No Safety Features support found
[   38.405859] rk_gmac-dwmac ffbe0000.ethernet end0: PTP not supported by HW
[   38.417331] rk_gmac-dwmac ffbe0000.ethernet end0: configuring for phy/rgmii-rxid link mode
[   42.512889] rk_gmac-dwmac ffbe0000.ethernet end0: Link is Up - 1Gbps/Full - flow control off
```

HDMI works, sound works, there is some lag in displaying video but am not sure if this is due to the USB drive being too slow or the codec not working due to driver issues. 

Within dmesg the following error popped up:
```
[   47.846118] dwhdmi-rockchip ff8d0000.hdmi: Rate 85750000 missing; compute N dynamically
[   47.847008] dwhdmi-rockchip ff8d0000.hdmi: Rate 85750000 missing; compute N dynamically
[   47.894030] hdmi-audio-codec hdmi-audio-codec.3.auto: Not able to map channels to speakers (-22)
[   47.894951] hdmi-audio-codec hdmi-audio-codec.3.auto: ASoC: error at snd_soc_dai_hw_params on i2s-hifi: -22
[   47.895850]  ffb70000.sai-i2s-hifi: ASoC: error at __soc_pcm_hw_params on ffb70000.sai-i2s-hifi: -22
[   47.897006] hdmi-audio-codec hdmi-audio-codec.3.auto: Not able to map channels to speakers (-22)
[   47.897831] hdmi-audio-codec hdmi-audio-codec.3.auto: ASoC: error at snd_soc_dai_hw_params on i2s-hifi: -22
[   47.898824]  ffb70000.sai-i2s-hifi: ASoC: error at __soc_pcm_hw_params on ffb70000.sai-i2s-hifi: -22
[   47.899794] hdmi-audio-codec hdmi-audio-codec.3.auto: Not able to map channels to speakers (-22)
```


I checked the dmesg and i saw it tries to open wlan/bluetooth: ap6275s
Is this within the DTB for MangoPi? Is this changeable to the 8800 chip? 
If so, we could have a working DTB specifically for the  M98MAX M2. 

```
[   21.778795] [WLAN_RFKILL]: Enter rfkill_wlan_init
[   21.779388] [WLAN_RFKILL]: Enter rfkill_wlan_probe
[   21.779453] [WLAN_RFKILL]: wlan_platdata_parse_dt: wifi_chip_type = ap6275s
[   21.779460] [WLAN_RFKILL]: wlan_platdata_parse_dt: enable wifi power control.
[   21.779466] [WLAN_RFKILL]: wlan_platdata_parse_dt: wifi power controled by gpio.
[   21.779503] [WLAN_RFKILL]: wlan_platdata_parse_dt: WIFI,host_wake_irq = 39, flags = 0.
[   21.779517] [WLAN_RFKILL]: wlan_platdata_parse_dt: The ref_wifi_clk not found !
[   21.779522] [WLAN_RFKILL]: rfkill_wlan_probe: init gpio
[   21.779529] [WLAN_RFKILL]: rfkill_set_wifi_bt_power: 1
[   21.779536] [WLAN_RFKILL]: Exit rfkill_wlan_probe
[   21.780324] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: uart_rts_gpios = 42.
[   21.780357] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: BT,reset_gpio = 49.
[   21.780372] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: BT,wake_gpio = 44.
[   21.780386] [BT_RFKILL]: bluetooth_platdata_parse_dt: get property: BT,wake_host_irq = 50.
[   21.780396] [BT_RFKILL]: bluetooth_platdata_parse_dt: clk_get failed!!!.
[   21.780455] [BT_RFKILL]: Request irq for bt wakeup host
[   21.780566] [BT_RFKILL]: ** disable irq
```

GPU bus errors:
```
[   21.766890] rockchip,bus gpu-bus: Looking up bus-supply from device tree
[   21.767229] rockchip,bus gpu-bus: bin=0
[   21.767277] rockchip,bus gpu-bus: Failed to get leakage
[   21.767314] rockchip,bus gpu-bus: Looking up pvtm-supply from device tree
[   21.767322] rockchip,bus gpu-bus: Looking up pvtm-supply property in node /gpu-bus failed
[   21.767344] rockchip,bus gpu-bus: error -ENODEV: _opp_set_regulators: no regulator (pvtm) found
[   21.767381] rockchip,bus gpu-bus: failed to set opp config
[   21.767387] rockchip,bus gpu-bus: failed to init opp info
[   21.767392] rockchip,bus gpu-bus: failed to get OPP table
[   21.767397] rockchip,bus gpu-bus: failed to init power control
[   21.770075] rockchip-saradc ffae0000.saradc: Looking up vref-supply from device tree
[   21.770965] SPI driver inv-icm42600-spi has no spi_device_id for invensense,icm42600
[   21.770983] SPI driver inv-icm42600-spi has no spi_device_id for invensense,icm42602
[   21.770988] SPI driver inv-icm42600-spi has no spi_device_id for invensense,icm42605
[   21.770994] SPI driver inv-icm42600-spi has no spi_device_id for invensense,icm42622
[   21.771633] optee: probing for conduit method.
```

**Comment by ophub** [comment]
https://github.com/armbian/linux-rockchip/blob/rk-6.1-rkr1/arch/arm64/boot/dts/rockchip/rk3528-mangopi-m28k.dts

**Comment by d5stick** [comment]
i tried to recompile the DTS i made but it did not work. The bluetooth and wifi will not come up. I have asked the H96MAX manufacturing of the original ROM to extract the DTS from.  The image i originally used was for the H96MAX m1, which uses another WIFI/BT module.

**Comment by d5stick** [comment]
For the DTS part, i failed to get wifi/bt working. 
Original android DTS: [Link](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/test/dtb.dts)
Mangopi DTS: [Link](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/test/mango.dts)
What i tried to do: [Link](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/test/mango_mod.dts)

The correct firmware's i got from the supplier H96MAX got 8800 chipset in the name.
But when i extracted the DTBs from the ZIPs and IMG, it referes to a realtek chipset.. not sure whats going on there. 

The mango_mod.dts compiles and it boots, but wifi and bluetooth do not work.
For the Wireless-LAN, i also tried with the AIC8800 from the mangoPI, but it wont come up. 

Not sure if i missed something in the DTS.. it is not my expertise. 

The kernel you mentioned works; 6.1.43-rk35xx-rkr1, it is stable. I have ran multiple tests including docker. 
Could this be used in future ophub/armbian releases instead of the 5.10? The 5.10 has booting issues with displaying HDMI and the LAN disconnects. 

The android ROM for the H96MAX-M2 is; [Link](https://drive.google.com/file/d/1FvjteJiOypLRFzU8YOmQ8py7CPSNgHir/view?usp=sharing)

**Comment by ophub** [comment]
Have you tried if the latest version 6.1.75 can be used?

armbian-sync
armbian-update -k 6.1.75

**Comment by d5stick** [comment]
![image](https://github.com/user-attachments/assets/256ff6cf-a7a1-4fdc-a680-350ff0e4fc29)
![image](https://github.com/user-attachments/assets/d285da3f-84e4-4474-9212-31f15a7cd246)

**Comment by ophub** [comment]
Was the display normal when you used 6.1.43 before? I removed the 6.1.43 kernel from the kernel repository today. Please send me the backup, and I will re-upload it to the repository. The current rebuild does not support specifying kernel versions for rk35xx/rk3588, only supports selecting stable and other branches. I will think about how to elegantly support this setting.

6.1.43 backup kernel in: `/ddbr`

**Comment by d5stick** [comment]
The files:

Is there a way to use armbian-update to use the backup files to go back to the previous kernel stored locally? 
[LINK](https://drive.google.com/file/d/16wsvwC3wrfvy6fb-N1vhTRV92IV3Z0S7/view?usp=sharing)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents#10-updating-armbian-kernel

```
# Enter the backup kernel directory, such as 6.6.12
cd /ddbr/backup/6.6.12
# Execute the kernel update command, which will automatically install the kernel in the current directory
armbian-update
```

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/kernel_rk35xx

I have uploaded the kernel version 6.1.43 here. You can download it and upload it to Armbian for your use. Follow the method above to update locally. Alternatively, you can also update it online directly.
`armbian-update -k 6.1.43`

**Comment by d5stick** [comment]
![Screenshot_20240727-075908_Termius](https://github.com/user-attachments/assets/89e3e48a-6488-4289-9b73-68aa9f936aed)

I performed the restore of the kernel by local method. 

Sensors are now there.

**Comment by ophub** [comment]
I added some configuration options for temperature sensors in the settings. Can you try compiling 6.1.75 and 6.1.43 that were compiled today to see if they work properly?

armbian-update -k 6.1.75
armbian-update -k 6.1.43

**Comment by d5stick** [comment]
I updated both kernels, didn't see any change:
![Screenshot_20240727-144817_Termius](https://github.com/user-attachments/assets/51dd4d1a-94ea-44cb-82c7-7405f3418109)
![Screenshot_20240727-143727_Termius](https://github.com/user-attachments/assets/8f9e4a29-8e61-41a2-8193-ad7eb934ad5e)

**Comment by ophub** [comment]
`sudo sensors-detect`

**Comment by d5stick** [comment]
![Screenshot_20240727-150904_Termius](https://github.com/user-attachments/assets/07d664e0-3d07-4bf9-9e51-f83c21a81ec2)

**Comment by ophub** [comment]
I compared the config files of 6.1.43 and 6.1.75, but couldn't find any missing options related to sensors.

**Comment by 2ndMessiah** [comment]
Hi folks,

May I know whether h96 max m2 is usable now? Does BT&Wifi work?

Thx!

**Comment by d5stick** [comment]
If you flash my created uboot with the flasher mentioned in this post, you are able to boot from usb. Using the mangopi dtb and rockchip 6.x kernel provided by ophub in the image you can boot. Everything works except wifi and bt.  I couldn't get it working but I dont use these so for my use case thats fine.

I didn't test the install to emmc, that's something to explore if you want.

I used a USB dongle to connect the flash drive and keyboard/mouse as it only has 1 USB. And it works fine.


-------- Oorspronkelijk bericht --------
Van: 2ndMessiah ***@***.***>
Datum: 23-08-2024 16:24 (GMT+01:00)
Aan: ophub/amlogic-s9xxx-armbian ***@***.***>
Cc: d5stick ***@***.***>, Author ***@***.***>
Onderwerp: Re: [ophub/amlogic-s9xxx-armbian] H96MAX M2 RK3528 - New box (Issue #2404)


Hi folks,

May I know whether h96 max m2 is usable now? Does BT&Wifi work?

Thx!

**Comment by myallten** [comment]
大家好，请问H96MAX M2 RK3528 或者芯片是RK3528的盒子是如何把armbian安装到EMMC的

**Comment by ophub** [comment]
用rockchip写固件工具或dd命令，在仓库的文档里有说明

**Comment by myallten** [comment]
用TF卡烧录h28k这个镜像到TF卡，把TF卡插到盒子上，正常启动，然后我把h28k这个镜像解压后上传到armbian系统（TF卡的系统） 然后执行
root@armbian:~# dd if=/root/armbian.img  of=/dev/mmcblk2  bs=1M status=progress
3217031168 bytes (3.2 GB, 3.0 GiB) copied, 88 s, 36.6 MB/s
3088+0 records in
3088+0 records out
3238002688 bytes (3.2 GB, 3.0 GiB) copied, 93.909 s, 34.5 MB/s
root@armbian:~# lsblk 
NAME         MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
mmcblk2      179:0    0 58.2G  0 disk 
├─mmcblk2p1  179:1    0  511M  0 part 
└─mmcblk2p2  179:2    0  2.5G  0 part 
mmcblk2boot0 179:32   0    4M  1 disk 
mmcblk2boot1 179:64   0    4M  1 disk 
mmcblk1      179:96   0 59.5G  0 disk 
├─mmcblk1p1  179:97   0  511M  0 part /boot
└─mmcblk1p2  179:98   0   59G  0 part /
zram0        254:0    0  1.9G  0 disk [SWAP]
zram1        254:1    0   50M  0 disk /var/log
root@armbian:~# poweroff 

执行完之后我用命令 lsblk 查看了一下，其中mmcblk1是TF卡。就是这样，然后关闭，再打开机器的时候 无法进入系统，不知道哪里出问题。还是说直接把 TF卡系统dd到盒子EMMC上 比如这样 dd if=/dev/mmcblk1  of=/dev/mmcblk2  bs=1M status=progress

**Comment by ophub** [comment]
你的操作看不出错误。
你看这个帖子的内容，贡献者是使用的rk工具写入的，你试试这种方法，可以把盒子先还原回安卓系统，再使用rk工具写入。安卓系统在kernel仓库有备份。

**Comment by jhonrn** [comment]
> i tried to recompile the DTS i made but it did not work. The bluetooth and wifi will not come up. I have asked the H96MAX manufacturing of the original ROM to extract the DTS from. The image i originally used was for the H96MAX m1, which uses another WIFI/BT module.

same, i have to ask the vendor but they only give tutor how to update system.. i need stock rom for using kernelsu

**Comment by d5stick** [comment]
> > i tried to recompile the DTS i made but it did not work. The bluetooth and wifi will not come up. I have asked the H96MAX manufacturing of the original ROM to extract the DTS from. The image i originally used was for the H96MAX m1, which uses another WIFI/BT module.
> 
> same, i have to ask the vendor but they only give tutor how to update system.. i need stock rom for using kernelsu

The android ROM for the H96MAX-M2 is; [Link](https://drive.google.com/file/d/1FvjteJiOypLRFzU8YOmQ8py7CPSNgHir/view?usp=sharing)

**Comment by jhonrn** [comment]
i mean i need fw for h96max m1..

**Comment by rudra-patell** [comment]
> Well it was an adventure; I compiled on my Ubuntu laptop a version of Armbian: `git clone --depth=1 https://github.com/armbian/build armbian-build`
> 
> -Used the following patches from [ilyakurdyukov](https://github.com/ilyakurdyukov/rk3528-tvbox) and included them in the armbian-build user patches. u-boot: rk3528-tvbox-defconfig.patch u-boot: no_read_limit.patch u-boot: gray_square_logo.patch Kernel: fix_drm_getunique_crash.patch Kernel: sai_clk_auto_on.patch
> 
> `./compile.sh build BOARD=mangopi-m28k BRANCH=vendor BUILD_DESKTOP=no BUILD_MINIMAL=yes KERNEL_CONFIGURE=no KERNEL_GIT=shallow RELEASE=bookworm`
> 
> Extract the u-boot img from Armbian to get the value "CONFIG_ROCKCHIP_USB_BOOT=y" in the u-boot. `dd if=armbian_version_.img bs=1M count=4 skip=8 > uboot.img`
> 
> Flash the uboot.img to the device with rkdeveloptool (install with apt install) Hold the pin in the AV port, connect a USB A to USB A cable and check for connectivity: `rkdeveloptool list`
> 
> When the device is present and in "loader" mode. Use the following to see which partitions are active on the device, search for uboot or u-boot. `rkdeveloptool list-partitions`
> 
> Fllash the uboot file. `rkdeveloptool write-partition uboot uboot.img`
> 
> Burn the armbian_version_.img with BalenaEtcher on a flashdrive (USB2!) Boot the device, it will show the boot logo of the box and after a minute it boots Armbian. The [DTB ](https://github.com/d5stick/amlogic-s9xxx-armbian/blob/main/VontarX3Files/rk3528-mangopi-m28k.dtb)used now is from Mangopi M28k, i hoped [@ophub](https://github.com/ophub) could help me create a DTB for this device.
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/2bf371e4-9d1f-4af4-9788-d459c74239f4)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/f33567a2-68f5-44f8-819f-dad0de117b5e)
> 
> ![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/53115937/ce5c8977-ff93-4290-813b-0960f68c11b4)
> 
> What is working on this box? Ethernet is working. HDMI is working USB is working, as it boots from there.
> 
> What is not working? WLAN is not working. Ophub's build of Armbian. Install to EMMC.

For installing on emmc you can use multitool.img
- download this from armbian official site
- than flash it on sd card (usb won't work) using balena etcher or rufus
- then copy your armbian image into the img folder in multitool sd card and you are ready to go

**Comment by petesimon** [comment]
> To make things easy, i shared the image i have working on the USB drive: [Armbian 6.1](https://drive.google.com/file/d/1AknTYM7j4nDL5zVLGSCC92att8UuwMc0/view)

@d5stick 
File not found. Can you please share that file again? Thanks

**Comment by d5stick** [comment]
> * download this from armbian official site
> * than flash it on sd card (usb won't work) using balena etcher or rufus
> * then copy your armbian image into the img folder in multitool sd card and you are ready to go
 
@rudra-patell 
Did you try it? I used the multitool on SDCARD in a usb drive but that doesnt work. 
The M2 does not have a SDCARD slot, only 1 USB slot which i have to share with an OTG hub. 

> > To make things easy, i shared the image i have working on the USB drive: [Armbian 6.1](https://drive.google.com/file/d/1AknTYM7j4nDL5zVLGSCC92att8UuwMc0/view)
> 
> [@d5stick](https://github.com/d5stick) File not found. Can you please share that file again? Thanks

@petesimon 
You can use the trixie rom for the H96-MAX which is in the releases. I am able to boot it after a few reboots. 
Probably my mistake for having a bad USB stick.    Make sure you flash my uboot file first before you try to boot from USB with the M2.  USB boot is not enabled by default. 

<img width="2048" height="1536" alt="Image" src="https://github.com/user-attachments/assets/d3360c13-b716-406f-a696-456c20972075" />

**Comment by petesimon** [comment]
> You can use the trixie rom for the H96-MAX which is in the releases. I am able to boot it after a few reboots.
> Probably my mistake for having a bad USB stick. Make sure you flash my uboot file first before you try to boot from USB with the M2. USB boot is not enabled by default.

@d5stick 
Thanks. I don't have this tv box but I was thinking about buying it from Aliexpress to use as a mini server with gigabit ethernet and USB 3.0. But oh I wasn't fully aware until now that i had to use the RK tool to flash your uboot file, AND there is only a single USB port. I'll pass on this and use tv boxes that have two USB ports such as h96 max x3 amlogic s905x3, but don't need a flash tool. Cheers.

**Comment by d5stick** [comment]
> [@d5stick](https://github.com/d5stick) Thanks. I don't have this tv box but I was thinking about buying it from Aliexpress to use as a mini server with gigabit ethernet and USB 3.0. But oh I wasn't fully aware until now that i had to use the RK tool to flash your uboot file, AND there is only a single USB port. I'll pass on this and use tv boxes that have two USB ports such as h96 max x3 amlogic s905x3, but don't need a flash tool. Cheers.

@petesimon  Vontar X3 or HK1 X3 (same hardware, i can highly recommend.  I have one in "production" for years.

**Comment by superromchik1** [comment]
"Hello! I cloned the repository but can't find the build script. The build.sh or compile.sh files are missing. Could you please provide the current build instructions? Thank you!"
my box H96 max RK3528 
https://4pda.to/forum/index.php?showtopic=1076564&ysclid=mflikqpbv2994672621

**Comment by evecus** [comment]
Hello

![Image](https://github.com/user-attachments/assets/5f12aee8-c588-4529-8b1c-12c696bc4398)

, my set-top box is h96max rk3528. I tried to use Armbian_25.11.0_rockchip_h96-max-m2_trixie_6.1.115_server_2025.09.15.img firmware to write into the U disk and use the U disk to start up, but there was an error. What is the reason?

**Comment by bilaltayar** [comment]
AFTER EFFORT AND EFFORT AND RENEWED THE LATEST UPDATE AND FLASH OF THIS H96MAX M2 PLUS RK3528 ANDROID 14

Here is the link to the update: 
⏬⏬⏬⏬⏬⏬⏬⏬

https://wx.mail.qq.com/ftn/download?func=3&k=cc9cb833741612d1feef1b333633373179a1ba45343337311b4c58551b520e5251070007011e0755005718075651061c525b5707190751020557030252060605505235415f0002030b3c5403040168790a556a7e554b687c01337966676c010701521801040102000150041d050305071d0a585420862446bf6c2b96d0d9b4b7510fe8244f3dd2f0691135333433373133&key=cc9cb833741612d1feef1b333633373179a1ba45343337311b4c58551b520e5251070007011e0755005718075651061c525b5707190751020557030252060605505235415f0002030b3c5403040168790a556a7e554b687c01337966676c010701521801040102000150041d050305071d0a585420862446bf6c2b96d0d9b4b7510fe8244f3dd2f0691135333433373133&code=3c534371&from=#/


![Image](https://github.com/user-attachments/assets/f0c4a1a9-5c80-40d7-99d2-a53666f4da7b)

**Comment by jwagnervaz** [comment]
Can you share the android 14 firmware  link again ? 

@bilaltayar
