### ISSUE TITLE
为什么我在tx3-h里建立vlan ,ping不通？

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2406]
为什么我在tx3-h里建立vlan ,ping不通？
eth0.1  192.168.100.2    用电脑ping盒子不行，盒子ping局域网中任何设备也不通
建立vlan的方法应该没有问题，各种方法都试过了。
系统也用了多个版本了，包括最新的版本，Armbian_24.8.0_amlogic_s905x3_noble_6.6.36_server_2024.07.01.img
eth0.1 有发送无接收，有没有人遇到同样问题？

我想实现单网口复用，就像openwrt的lan与wan共用一个网口。现在怀疑是系统或者网卡驱动的问题，另一台tx3-mini （s905w)也是同样问题，也许是我操作有问题，请帮我，谢谢！

**Comment by goldsoft8888** [comment]
在电脑上安装ubuntu x64，也不行，看是不是armbian的问题，也不是驱动的问题，奇怪了，

**Comment by ophub** [comment]
vlan就是独立的子网，即便都是192.168.1.x也是2个网，要能跨2个子网访问需要做路由隐射。

**Comment by goldsoft8888** [comment]
不用跨子网，电脑是192.168.100.3, 这样也不通

**Comment by ophub** [comment]
vlan了就不是一个网了，2个隔离的网，即便ip一样也是2个网
