### ISSUE TITLE
Tx3 4+64盒子，刷5.15.32之后版本的镜像内存显示2G的问题的补充重现观察

### ISSUE THREAD

**Issue by janko888** [ophub/amlogic-s9xxx-armbian#241]
tx3 4+64盒子。
1.使用5.15.32内核的镜像（我这里是Armbian_22.05.0_Aml_s905x3_focal_5.15.32_2022.04.08.1628.img.gz）在sd、u盘和emmc中使用都显示正常内存大小；
2.一旦在emmc写入5.15.32之后的内核镜像后，在u盘或者sd卡写入该版本之后的系统都只显示1.9G的内存。
3.以上情况出现后，在u盘或者sd卡写入5.15.32内核的镜像，显示内存大小正确，写入emmc后，在u盘或sd卡再写入高版本的镜像并从u盘或sd卡启动时，高版本内核的系统显示内存大小正常。

**Comment by ophub** [comment]
5.15.33/34都删了u-boot.emmc了，主线内核识别问题，我想一下是否继续添加吧，明显的感受是添加了启动重载要10秒，好处是内存正常

**Comment by ophub** [comment]
我想了想，用启动延长10秒换4G内存，和启动快10秒只有1G内存比比，还是4G内存可能更有性价比。
所以还是默认有U-BOOT的都自动都添加来保障大内存，没有U-BOOT的设备只能识别到1G内存了。

**Comment by janko888** [comment]
> 我想了想，用启动延长10秒换4G内存，和启动快10秒只有1G内存比比，还是4G内存可能更有性价比。 所以还是默认有U-BOOT的都自动都添加来保障大内存，没有U-BOOT的设备只能识别到1G内存了。 这就改，一会更新。

辛苦了！软件系统的时间效率与空间效率的权衡的确很难取舍！

**Comment by ophub** [comment]
你试一下今天新构建的内存是否正确

**Comment by janko888** [comment]
> 你试一下今天新构建的内存是否正确

在我报告的场景下用新构建的镜像再次测试，内存识别正确，问题已经解决。thx

**Comment by ophub** [comment]
好的，谢谢反馈

**Comment by huapox** [comment]
> 没有U-BOOT的设备只能识别到1G内存了。

hk1box刷最新`Armbian_22.11.0_Aml_s905x3_jammy_5.15.72_server_2022.10.06.img.gz 564 MB`emmc启动只识别到1G, tf引导进去正常（内存4G）

咨询下这个盒子有办法emmc下识别4G内存不？（替换主线uboot或uboot重载？）

**明细：**

- 1）hk1盒子： `s905x3, 4G, 128G`, 今年国庆入手
- 2）之前刷的10.3号固件`debian版 kernel5.10`那个固件只能tf卡启动。emmc进不了系统
- 3）dts：用的`meson-sm1-hk1box-vontar-x3.dtb`识别为千兆(试过换回百兆的，这个好像不影响内存识别？)
- 4）uboot重载：从tf卡BOOT分区，分别拷贝`u-boot.sd/u-boot.ext`到emmc_BOOT分区(改名为u-boot.emmc), 会无法启动。
- 5）换kernel：试着换到了5.4的，内存一样为1G （900多M）， 另换到5.4后 屏幕显示问题复现了

**Comment by huapox** [comment]
> 拷贝u-boot.sd是从什么地方看的别的固件的使用教程？

这个昨天看卡里的u-boot.ext与sd文件一样大小(没细对md5)， 就先自由发挥了 

网卡是千兆的，用的`hk1box-vontar-x3.dtb`，ethtool eth0 显示有千兆

**Comment by huapox** [comment]
> 在5.10内核里脚本自动拷贝，在5.4/5.15里默认没拷贝

了解

**Comment by huapox** [comment]
> 这里下的固件，如果需要测试u-boot，只需要拷贝固件自带的/boot/u-boot-x96maxplus.bin 为 /boot/u-boot.emmc

感谢，我试试

---

另请问下，这里是F大佬网盘`Armbian/52`版本的一段txt说明， 这里提到的u200.bin有啥区别不？

```txt
5.10内核之后，由于取消了text_offset，而所有amlogic盒子都用android版的u-boot 2015(非主线），会导致无法启动，目前的解决方案如下：

1. 如果在u盘、sd卡、tf卡上启动，需要在引导时重载主线u-boot，具体文件名为/boot/u-boot.ext
   如果在emmc上启动，需要在在引导时重载主线u-boot，具体文件名为/boot/u-boot.emmc

2. 具体的方法：
   对于s905x、s905d盒子，例如斐讯N1，需要把 /boot/u-boot-p212.bin 拷贝成 /boot/u-boot.ext及/boot/u-boot.emmc两个文件(已测试)
   对于s912, 例如章鱼星球，需要把 /boot/u-boot-q200.bin 拷贝成 /boot/u-boot.ext及/boot/u-boot.emmc两个文件(未经测试)
   对于s905x2, 例如x96-max，需要把 /boot/u-boot-sei510.bin 拷贝成 /boot/u-boot.ext及/boot/u-boot.emmc两个文件(未经测试)
   对于s905x3, 例如x96-max+、h96 max x3、 hk1 box， 需要把 /boot/u-boot-u200.bin 拷贝成 /boot/u-boot.ext及/boot/u-boot.emmc两个文件(已测试)
   对于s922x， 例如gtking、gtkingpro， 需要把 /boot/u-boot-gtkingpro.bin 拷贝成 /boot/u-boot.ext及/boot/u-boot.emmc两个文件(已测试)

3. 副作用：
   a. 可能导致hdmi无显示，或绿屏，但作为软路由或服务器而言并不影响使用
   b. 可能导致 mac 地址随机变化，介意者请不要使用5.10及以后的内核
   c. 启动时间比以前有所加长
   
```

**Comment by ophub** [comment]
这是历史了，目前5.4和5.15一样使用（都可以不复制u-boot即可启动），因为5.15也添加了text_offset补丁。
除这2个长期内核外，其他5.10---6.0的内核都需要这样复制。

**Comment by huapox** [comment]
进展更新：

**一、uboot重载**

- tf卡下可用
- emmc重载失败，表现为卡在logo界面（手动emmc重载后，当前ubuntu_kernel515故障现象与之前debian_kernel510版一样了）

**二、替换主线uboot**

手动替换主线uboot后，内存正常了（替换后第1次启动显示1.9G, 再次重启后内存3.7G正常了，之后再重启一直为3.7G）

明细记录如下：

- 1）写入前(原安卓uboot)：armbian-install安装脚本安装时会把原安卓uboot备份在`/usr/lib/u-boot/mybox-bootloader.img` (hk1box为4M大小)
- 2）写入前(主线uboot)：hk1box使用`/usr/lib/u-boot/hk1box-u-boot.bin.sd.bin`
- 3）写入后(写入tf卡)：试着把bootloader写入tf卡的前4M, 验证s905x3可否从tf卡进行引导 避免emmc写故障变砖。(经测，似乎cpu不会从tf卡读取bootloader?) @ophub 这请教下它的引导原理
- 4）写入后(写入emmc)：主线uboot下 捅耳机孔不再有效(不会有进uboot相关UI面板)， 发现长按后直接进系统(内存显示回1.9G)，再次重启内存就又正常了。
- 5）同3 进一步验证引导关系：emmc已写入主线uboot后，tf刷安卓uboot插入盒子启动 验证是否cpu加载到tf卡上的安卓uboot（实际上加载，还是用的emmc的主线uboot）

```bash
#ddwrite.sh 手动刷入脚本：(相关文件请手动拷贝到本脚本目录)
img=mybox-bootloader.img                 #原anz备份的uboot
#img=hk1box-bootloader.img               #ophub镜像包内默认备份img
#img=/dev/zero ##!!! count=8192 (bs=512) #清空对应磁盘块
#img=hk1box-u-boot.bin.sd.bin            #主线uboot
dd if=$img of=/dev/mmcblk0 conv=fsync bs=1 count=444 #444--512之的数据块存放了mbr分区信息, 切勿替换！
dd if=$img of=/dev/mmcblk0 conv=fsync bs=512 skip=1 seek=1 #count=8192
```
