### ISSUE TITLE
关于b863av3.1-m2 wifi驱动的问题

### ISSUE THREAD

**Issue by fznan** [ophub/amlogic-s9xxx-armbian#2410]
我现在用的是Armbian_24.5.0_amlogic_s905l3a_noble_6.6.28_server_2024.04.25的系统。盒子是b863av3.1-m2，盒子的wifi 芯片是uwe5621ds。现 在系统是用不了wifi，应该是没有加载驱动，因为在安卓系统时wifi是可用的。在系统的/lib/firmware下有一个uwe5621ds文件夹，里有一些ini文件，和一个bin文件，请问这些是wifi驱动吗？如果是，如何加载？谢谢！

**Comment by ophub** [comment]
没驱动

**Comment by fznan** [comment]
https://github.com/KryptonLee/uwe5621ds-aml。。。这个可能是5621的驱动但不会编译！

**Comment by straint** [comment]
> 没驱动

大佬看下这个是不是
https://github.com/armbian/firmware/tree/master/uwe5621ds

**Comment by ophub** [comment]
是内核4.9的，现在f大仓库没这个了
