### ISSUE TITLE
x96maxplus2千兆在armbian中无法使用蓝牙，但在devmfc的debian on aml中可以使用蓝牙

### ISSUE THREAD

**Issue by 1223710788** [ophub/amlogic-s9xxx-armbian#2411]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [x96max plus2]

**Armbian Version | 系统版本**
 - Kernel Version: [6.6.36]
 - Release: [bookworm]

**Describe the bug | 问题描述**

我已经在armbian-config中install bt了，但是却无法使用，只有remove bt选项。安装桌面后在桌面设置里也找不到有蓝牙适配器。

是因为在armbian项目里缺少蓝牙驱动吗？还是install emmc时我选择的dtb有问题？

**Comment by ophub** [comment]
x96有多个变种，查看你的蓝牙芯片的型号，查看固件中是否包含驱动，或者你选择了启用蓝牙的dtb.

**Comment by 1223710788** [comment]
> x96有多个变种，查看你的蓝牙芯片的型号，查看固件中是否包含驱动，或者你选择了启用蓝牙的dtb.
> 

我可以把Debian on aml项目的蓝牙驱动文件或者dtb替换到armbian项目中使用吗

**Comment by ophub** [comment]
x86和arm64的内核dtb有区别

**Comment by ophub** [comment]
x86和arm64的内核dtb有区别

**Comment by 1223710788** [comment]
> x86和arm64的内核dtb有区别

不是x86，这个是隔壁一个大佬的项目，好像也是针对arm设备的，我使用他里面x96max plus2 的dtb启动（在armbian里我使用的是x96max+ 1g），是可以正常使用蓝牙的。https://github.com/devmfc/debian-on-amlogic

**Comment by ophub** [comment]
可以试一下，看dts或者启动日志，你用的哪个驱动文件

**Comment by 1223710788** [comment]
> 可以试一下，看dts或者启动日志，你用的哪个驱动文件

我试了试把两个dtb替换了一下，发现设备黑屏了。我用您提供的dtb（代号502和503）时，使用 dmesg | grep Bluetooth 命令没有反应，使用 dmesg 命令导出的日志里没有Bluetooth 这一项。我还不知道怎么转换dts，我使用devmfc的dtb时蓝牙是有效的

[（devmfc）meson-sm1-x96maxplus2.zip](https://github.com/user-attachments/files/16120297/devmfc.meson-sm1-x96maxplus2.zip)

[(ophub)dmesg日志.txt](https://github.com/user-attachments/files/16120288/ophub.dmesg.txt)

**Comment by 1223710788** [comment]
> 可以试一下，看dts或者启动日志，你用的哪个驱动文件

大佬你好，我把devmfc大佬提供的dtb转换成dts了，不知道他是怎么实现让x96max+在6.6.34内核上使用蓝牙的。

我查了下unifreq大佬在linux-6.6.y/drivers/bluetooth里也有RTL8822BS。但他提供[的dts](https://github.com/unifreq/linux-6.6.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts)中却没有提到RTL8822BS，而是bcm43438。
会不会是unifreq大佬提供的dtb命名错了呢

[（devmfc）meson-sm1-x96maxplus2.zip](https://github.com/user-attachments/files/16125629/devmfc.meson-sm1-x96maxplus2.zip)

**Comment by 1223710788** [comment]
> 可以试一下，看dts或者启动日志，你用的哪个驱动文件

我刚刚在尝试了meson-sm1-x96-max-plus-2101.dtb这个dtb后，蓝牙成功启动了。
![微信图片_20240708191234](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163143682/42d8fdce-92c1-4dd4-8322-6373d9160fad)

但是根据[4pda网站](https://4pda.to/forum/index.php?showtopic=1002233&view=findpost&p=102780026)上的提示，我不太可能是2101这个型号（因为我的是4g+64g）。千兆网卡能启动也是因为2101这个dtb包含RTL8211F的巧合。
![微信截图_20240708191506](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163143682/de63a8b9-6d06-4a15-b4b2-604da68a0ae9)

不知道以后能不能在[这个页面](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf)把X96-Max+_1GB 这个型号和X96-Max+_2101更改或者做个提示什么的。因为根据4pda上96-Max+_1GB应该叫做X96 Max Plus2，它们两个的安卓固件是不一样的。

**Comment by ophub** [comment]
拍一下你的盒子的照片，正面和反面，主板有图也发一下正反两面。
你有你的盒子的安卓系统的话也分享一下下载链接，我添加到2101列表里。

**Comment by 1223710788** [comment]
> 你的可能是新的变种，x96版本很多。拍一下你的盒子的照片，正面和反面，主板有图也发一下正反两面。 你有你的盒子的安卓系统的话也分享一下下载链接，我添加到2101列表里。

我这个应该不是新变种，我一直使用slimbox的第二个固件，代号是x96maxplus2。
![微信图片_20240708195846](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163143682/1a5b3e22-6836-49b2-adf7-5b645941587f)
![微信图片_20240708195853](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163143682/ef1f07fd-b850-4125-9e24-778237c523ad)
![微信图片_20240708195858](https://github.com/ophub/amlogic-s9xxx-armbian/assets/163143682/fb13efc6-1a71-44f8-822e-d90cd7c8fdb5)

**Comment by ophub** [comment]
x96maxplus2在你的设备上没这个代号，这是怎么确认的？
