### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by fbt9910** [ophub/amlogic-s9xxx-armbian#2412]
版本刷的 Armbian_24.8.0_rockchip_r68s_bookworm_6.1.96_server_2024.07.01.img

systemctl stop NetworkManager
sudo systemctl disable NetworkManager

因为4个网卡使用的eth2
interfaces里添加

# Network is managed by Network manager
auto lo
iface lo inet loopback
auto eth2
iface eth2 inet static
address 192.168.0.102
netmask 255.255.255.0
gateway 192.168.0.1
dns-nameservers 114.114.114.114 8.8.8.8
hwaddress 02:42:b6:22:76:9f

直接没网了

systemctl stop NetworkManager
sudo systemctl disable NetworkManager

interfaces里添加

# Network is managed by Network manager
auto lo
iface lo inet loopback

/etc/network/interfaces.d/*里添加

auto eth2
iface eth2 inet static
address 192.168.0.102
netmask 255.255.255.0
gateway 192.168.0.1
dns-nameservers 114.114.114.114 8.8.8.8
hwaddress 02:42:b6:22:76:9f

改版了吗为记得原来可以

**Comment by fbt9910** [comment]
升级6.6.37内核无法启动了 就重新刷了 不想用NetworkManager 就用老的 启动没网

**Comment by ophub** [comment]
半个月前上游改为了netplan

**Comment by fbt9910** [comment]
> 半个月前上游修改了netplan

感谢 刷了 Armbian_24.8.0_rockchip_r68s_bookworm_6.1.93_server_2024.06.15.img 正常了   

Armbian 构建及使用方法 网络篇 应该改一下了
按debian的套路改直接G

**Comment by Face-Smile** [comment]
armbian 6.6.32-ophub 禁用Network Manager 改用`/etc/network/interfaces`,
网络服务报错`/etc/network/if-up.d/resolved: 71: DNS: not found`
网上找几个解决办法了综合了下
https://unix.stackexchange.com/questions/714901/dns-broken-when-using-ifupdown-and-systemd-resolved-after-upgrade-to-ubuntu-22-0
https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1905240.html
https://bugs.launchpad.net/ubuntu/+source/ifupdown/+bug/1981103

修改`/etc/network/if-up.d/resolved`这个文件
下面是diff文件修改前后的区别
```
46c46
< "$DNS"="$NEW_DNS"
---
> $DNS="$NEW_DNS"
50c50
< "$DOMAINS"="$NEW_DOMAINS"
---
> $DOMAINS="$NEW_DOMAINS"
69c69
<         DNS DNS6 DOMAINS DOMAINS6 DEFAULT_ROUTE
---
>         unset DNS DNS6 DOMAINS DOMAINS6 DEFAULT_ROUTE
```

**Comment by fbt9910** [comment]
> armbian 6.6.32-ophub 禁用网络管理器改用`/etc/network/interfaces`, 网络服务报错`/etc/network/if-up.d/resolved: 71: DNS: not found` 网上找几个解决办法综合了下 [https://unix.stackexchange.com/questions/714901/dns-broken-when-using-ifupdown-and-systemd-resolved-after-upgrade-to-ubuntu-22-0 ](https://unix.stackexchange.com/questions/714901/dns-broken-when-using-ifupdown-and-systemd-resolved-after-upgrade-to-ubuntu-22-0) [https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1905240.html ](https://www.mail-archive.com/debian-bugs-dist@lists.debian.org/msg1905240.html) https://bugs.launchpad.net/ubuntu/+source/ifupdown/+bug/1981103
> 
> 修改`/etc/network/if-up.d/resolved`这个文件 下面是diff文件修改前后的区别
> 
> ```
> 46c46
> < "$DNS"="$NEW_DNS"
> ---
> > $DNS="$NEW_DNS"
> 50c50
> < "$DOMAINS"="$NEW_DOMAINS"
> ---
> > $DOMAINS="$NEW_DOMAINS"
> 69c69
> <         DNS DNS6 DOMAINS DOMAINS6 DEFAULT_ROUTE
> ---
> >         unset DNS DNS6 DOMAINS DOMAINS6 DEFAULT_ROUTE
> ```
你这没用 原来用的Debian的配置网络 现在用的市Ubuntu 的配置网络不是DNS问题就无法连接网关
