### ISSUE TITLE
MGV3000 应该使用哪个镜像包呢？

### ISSUE THREAD

**Issue by erlong233** [ophub/amlogic-s9xxx-armbian#2414]
在以下文章中提到的5.x包，找不到在哪
https://zichen.zone/archives/mgv3000-armbian.html
尝试使用6.x  在外置U盘启动时 黑屏

**Comment by ophub** [comment]
你到路由器里看armbian的ip

**Comment by erlong233** [comment]
感谢解答，我的问题是启动时黑屏，而不是无信源，这意味着从u盘启动失败
目前我已成功刷入armbian
在此我总结一下我遇到的问题
使用的镜像包为
Armbian_24.8.0_amlogic_s905l2_bookworm_6.6.36_server_2024.07.05.img
镜像包烧录完成后不需要进行任何操作
dtb为默认的meson-gxl-s905l2-x7-5g.dtb
如果跟我一样出现黑屏问题，可以尝试DISKGenius将u盘格式化后重新尝试烧录

**Comment by 1273457900** [comment]
是否提供5.15包，我刷了Armbian_24.8.0_amlogic_s905l2_bookworm_6.6.36_server_2024.07.05
还是黑屏
刷了其他包一样的情况，在网络上找到一个5.15的包，可以获取到ip地址。但是包的ssh账号密码不知道，由其他人编译
可否提供5.15包   mgv3000
