### ISSUE TITLE
e900v22c (s905l3a) 改装 rtl8822cs 网卡

### ISSUE THREAD

**Issue by RayPS** [ophub/amlogic-s9xxx-armbian#2415]
e900v22c (s905l3a) 原本自带的网卡型号为 UWE5621DS，它目前为止无法在 Linux 驱动。
我根据一篇恩山无线论坛上的[一则改装指南](https://www.right.com.cn/forum/thread-8309244-1-1.html)成功移植 rtl8822cs 网卡，
且在 Android 系统下验证过硬件可用性，信号、速度、温度等一切正常。
图片：
![IMG_3533](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1941540/0caf2d26-d372-4141-a77f-c94a43d79634)

目前内核仓库中所包含的 SDIO 接口无线网卡驱动并不多，rtl88x2cs 可能是唯一选择
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl88x2cs

因为 5.15.y 有这个驱动，所以我用 rebuild -k 5.15 重新打包并刷写固件，
系统启动后可以在 `/lib/modules/` 下找到 `88x2cs.ko`，
但是 `lsmod` 中默认并没有加载，于是尝试
```
root@odroidn2:~# modprobe 88x2cs
[   93.526751] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   93.625203] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   93.626799] cfg80211: Loaded X.509 cert 'wens: 61c038651aabdcf94bd0ac7ff06c7248db18c600'
root@odroidn2:~# lsmod
Module                  Size  Used by
88x2cs               2265088  0
cfg80211              716800  1 88x2cs
.....
```
但 `nmcli dev` 中依然没有找到 wifi 设备。

请教一下我还有没有什么值得尝试的方法呢

**Comment by ophub** [comment]
rtl8822cs看脸，有的人能用，有些不能。
你编一下dts，添加一下wifi的代码为8822试试。我记得x96max+有，参考添加。

**Comment by RayPS** [comment]
感谢前辈，但是我对设备树并不熟悉，查了一些设备树的资料也看不太明白，
我根据你的提示参考了一下 x96 max plus 的几个 dtb 并做出以下修改，请问这样做是正确的吗？
```diff
__symbols__ {
...
...
-    rtl8822cs = "/soc/sd@ffe03000/wifi@1";
+    wifi = "/soc/sd@ffe03000/wifi@1";
...
...
}
```


```diff
{
    soc {
        ...
	sd@ffe03000 {
            ...
            wifi@1 {
                reg = <0x01>;
-                 compatible = "sprd,unisoc-wifi";
+                 compatible = "realtek,rtl8822cs-wifi";
                phandle = <0x128>;
            }
        }
    }
}
```

**Comment by ophub** [comment]
昨天才发现6.1和6.6都有rtl8822cs

**Comment by ruleechen** [comment]
Mark

**Comment by dumplingwrapper** [comment]
@RayPS 哥们可以分享一下你重新编译的dtb不，我这边改完dts后报错
123.dts:235.15-238.8: ERROR (explicit_phandles): /soc/bus@ff600000/hdmi-tx@0/port@1/endpoint: duplicated phandle 0x55 (seen before at /efuse/bt_mac@6)
123.dts:3424.21-3431.4: ERROR (explicit_phandles): /regulator-main-12v: duplicated phandle 0x56 (seen before at /efuse/wifi_mac@12)
ERROR: Input tree has errors, aborting (use -f to force output)

**Comment by RayPS** [comment]
@dumplingwrapper 不好意思，虽然我这边没有报错，但是我到现在都不知道是不是这么改。我试过也不行，所以我感觉是不对的。

**Comment by dumplingwrapper** [comment]
> 感谢前辈，但是我对设备树并不熟悉，查了一些设备树的资料也看不太明白， 我根据你的提示参考了一下 x96 max plus 的几个 dtb 并做出以下修改，请问这样做是正确的吗？
> 
> __symbols__ {
> ...
> ...
> -    rtl8822cs = "/soc/sd@ffe03000/wifi@1";
> +    wifi = "/soc/sd@ffe03000/wifi@1";
> ...
> ...
> }
> {
>     soc {
>         ...
> 	sd@ffe03000 {
>             ...
>             wifi@1 {
>                 reg = <0x01>;
> -                 compatible = "sprd,unisoc-wifi";
> +                 compatible = "realtek,rtl8822cs-wifi";
>                 phandle = <0x128>;
>             }
>         }
>     }
> }

这个能行么

**Comment by RayPS** [comment]
@dumplingwrapper 试过不行，我目前在这一步没有头绪

**Comment by dumplingwrapper** [comment]
dts-v1/;

/ {
	interrupt-parent = <0x01>;
	#address-cells = <0x02>;
	#size-cells = <0x02>;
	compatible = "amlogic,sm1";
	model = "AMedia X96 Max+";

	aliases {
******************************************************
	};

	chosen {
		*************************************************
	};

	efuse {
*********************************************************

		eth_mac@0 {
			reg = <0x00 0x06>;
			phandle = <0x0a>;
		};

		bt_mac@6 {
			reg = <0x06 0x06>;
			phandle = <0x55>;
		};

		wifi_mac@12 {
			reg = <0x0c 0x06>;
			phandle = <0x56>;
		};

		usid@18 {
			reg = <0x12 0x10>;
			phandle = <0x57>;
		};

------------------------------------------------------------------------------------------

__symbols__ {
                      ************************************
		bt_mac = "/efuse/bt_mac@6";
		wifi_mac = "/efuse/wifi_mac@12";
		usid = "/efuse/usid@18";
                          ********************

@RayPS 看看这个呢，这个是X96 Max+这个些是有WiFi的关键部分，我们探讨一下，我看了一下，你之前弄的那个是照着CM311的改的

**Comment by dumplingwrapper** [comment]
@ophub 大佬有时间帮忙解答一下么，是不是dts中
			wifi@1 {
				reg = <0x01>;
				compatible = "realtek,rtl8822cs";
				phandle = <0x128>;
        status = "okay";
			};

不应该放在		sd@ffe03000 里面，应该放到其他地方，通过什么方式去判断该刚在那，拆开设备看，我觉得不太合理。还是说用一个Android TV adbshell去看WiFi挂在了那个总线下面

**Comment by dumplingwrapper** [comment]
@RayPS @ophub 我已经成功驱动了

![Image](https://github.com/user-attachments/assets/d4df04ba-0419-49fb-a7d6-01d95872900a)

![Image](https://github.com/user-attachments/assets/cab8d84a-3bf2-4a28-8c08-87333461087e)

**Comment by RayPS** [comment]
@dumplingwrapper 恭喜，可不可以分享一下你对设备树的修改

**Comment by dumplingwrapper** [comment]
如果你用github上dts源文件的修改的话是这样

<img width="2089" height="1150" alt="Image" src="https://github.com/user-attachments/assets/bfc9a536-861b-46c6-a3d6-e04dfe102b3e" />

如何是反编译的dts如下图

<img width="1120" height="697" alt="Image" src="https://github.com/user-attachments/assets/ce22103a-d240-4291-8acf-8828835a2882" />

但是我现在遇到一个问题，设备能看见，但是扫描不到信号，不知道是不是因为插着网线的原因，wifi是不是被禁用了

**Comment by dumplingwrapper** [comment]
@RayPS

**Comment by RayPS** [comment]
@dumplingwrapper  感谢分享，但是我要晚一些才能做测试。
你试试在你的基础上按照这个 Commit 添加一处改动看看行不行：https://github.com/unifreq/linux-5.15.y/commit/481c09cd0fc8d86bd56a9e064b1f75f46e15ceb8

**Comment by dumplingwrapper** [comment]
@RayPS @ophub 不好意思，遗漏了一个关键的地方必须添加这部分

<img width="1411" height="1168" alt="Image" src="https://github.com/user-attachments/assets/59c30147-8a9c-44da-85d8-c3bbf6e77724" />完全是一点都不懂，慢慢和deepseek和kimi聊天，把各种dts丢给ai看，和ai一步一步找问题，给解决了

<img width="1371" height="925" alt="Image" src="https://github.com/user-attachments/assets/bd1dcb12-28ca-4d26-8486-30366e476c3b" />

**Comment by RayPS** [comment]
确实可以了，但是我获得的接口跟你有点不一样，多了个 wlan1 和 p2p，但似乎不影响模块工作。
这件困扰我一年多的事情总算有了个好结果。


<img width="1452" height="2244" alt="Image" src="https://github.com/user-attachments/assets/0a9110e5-7053-41ab-84d3-8a033f7b239e" />

<img width="1394" height="1060" alt="Image" src="https://github.com/user-attachments/assets/5a3dd3b3-1b67-452b-8b5d-1cbee2336deb" />

<img width="1394" height="772" alt="Image" src="https://github.com/user-attachments/assets/d7967f9f-2bb9-439a-b5d0-55e64e256403" />

**Comment by RayPS** [comment]
@dumplingwrapper @ophub 接下来将会测试稳定性，目前唯一问题是间歇性地出现这个警告，不知道是什么原因
```
root@armbian:~# [ 1286.974542] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ 1468.378559] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ 1623.213019] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ 1669.272289] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ 1723.268887] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ 1885.671046] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ 1913.032681] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/default/cpufrequtils

这是高频无法正常运行的信号，运行中的 Armbian 系统尝试更改 PLL（锁相环）频率时失败，系统因此 回退到旧频率 6GHz（6000000000 Hz）。魔百和要降低频率使用，你手动把这里的MAX_SPEED，MIN_SPEED写成固定值，不要自动设置。把敏捷调频模式schedutil也改成ondemand

**Comment by dumplingwrapper** [comment]
@RayPS 我用6.1内核各种bug，6.6很完美，但是现在有个问题，WiFi最高速率在4Mbyte/s，WiFi和路由器协商的速率Bit Rate=866.7 Mb/s ，差别太大了。我在安卓tv下是正常的

**Comment by dumplingwrapper** [comment]
@ophub 大佬，这个实际速率和协商速率严重不符是啥情况啊

**Comment by RayPS** [comment]
@ophub 感谢，我通过 `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies`
得出 `1000000 1200000 1398000 1512000 1608000 1704000 1800000 1908000`
因此我设定 `MIN_SPEED = 1000000`， `MAX_SPEED = 1908000`。并且 `GOVERNOR="ondemand"`。
这样是正确的吗？

**Comment by RayPS** [comment]
@dumplingwrapper 我看过好像只有 5.x 有这个驱动。你是把驱动放到 6.6 重新编译了吗？你用什么方法测速？我用相同方法测一次和你做比较

**Comment by dumplingwrapper** [comment]
@RayPS SFTP传大文件，和speedtest-cli测速都试过，不行

**Comment by dumplingwrapper** [comment]
@RayPS 在6.1和6.6里面驱动都不用编译
root@armbian:~# lsmod 
rtw88_8822cs           12288  0
rtw88_8822c           466944  1 rtw88_8822cs
rtw88_sdio             20480  1 rtw88_8822cs
rtw88_core            167936  2 rtw88_8822c,rtw88_sdio
mac80211              966656  2 rtw88_sdio,rtw88_core
cfg80211              942080  2 rtw88_core,mac80211
驱动自动加载这些，我5.1不能正常用

**Comment by dumplingwrapper** [comment]
@ophub 

<img width="1325" height="554" alt="Image" src="https://github.com/user-attachments/assets/d22fe9be-01ea-42e6-b26b-ea38115e665b" />参照他这个手册

<img width="751" height="647" alt="Image" src="https://github.com/user-attachments/assets/6b4d03be-d208-4bd6-8aaa-dc7359253181" />SDIO最大时钟频率是100Mhz（处于那个SDR50工作模式的）所以SDIO速率应该是没啥限制的，但是就是WiFi跑不到理想值，会不会是驱动或配置上的问题啊

**Comment by RayPS** [comment]
@dumplingwrapper 我在 6.6 上用 iperf 试了一下，一样很慢。我们一起研究下怎么解决。我觉得应该还是设备树的问题，因为我在 Android 测试速度是正常的。

```bash
armbian:~:# iperf3 -c 192.168.31.248
Connecting to host 192.168.31.248, port 5201
[  5] local 192.168.31.173 port 61956 connected to 192.168.31.248 port 5201
[  177.317003] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 6000000000
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec   523 KBytes  4.28 Mbits/sec    0   62.2 KBytes       
[  5]   1.00-2.00   sec   255 KBytes  2.08 Mbits/sec    0   74.9 KBytes       
[  5]   2.00-3.00   sec  0.00 Bytes  0.00 bits/sec    0   74.9 KBytes       
[  5]   3.00-4.00   sec  0.00 Bytes  0.00 bits/sec    0   14.1 KBytes       
[  5]   4.00-5.00   sec  0.00 Bytes  0.00 bits/sec    0   17.0 KBytes       
[  5]   5.00-6.00   sec   255 KBytes  2.08 Mbits/sec    0   14.1 KBytes       
[  5]   6.00-7.00   sec  0.00 Bytes  0.00 bits/sec    0   14.1 KBytes       
[  5]   7.00-8.00   sec  0.00 Bytes  0.00 bits/sec    0   14.1 KBytes       
[  5]   8.00-9.00   sec  0.00 Bytes  0.00 bits/sec    0   17.0 KBytes       
[  5]   9.00-10.00  sec   255 KBytes  2.09 Mbits/sec    0   5.66 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  1.26 MBytes  1.05 Mbits/sec    0             sender
[  5]   0.00-10.07  sec   600 KBytes   488 Kbits/sec                  receiver

iperf Done.
```

**Comment by RayPS** [comment]
我把 max-frequncy 改为 0x1312D00 后速度显著提升，而且 PLL 的问题貌似也随之消失了。
这次测试环境是使用 https://github.com/jethome-ru/rtl88x2cs 编译 5.15 内核，而不是 unifreq 本身带的驱动。
我相信同样条件在 6.6.y 应该也可以，我稍后测试。

```
armbian:~:# iperf3 -c 192.168.31.248
Connecting to host 192.168.31.248, port 5201
[  5] local 192.168.31.173 port 41406 connected to 192.168.31.248 port 5201
[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  4.92 MBytes  41.3 Mbits/sec    0    119 KBytes       
[  5]   1.00-2.00   sec  3.54 MBytes  29.7 Mbits/sec    0    136 KBytes       
[  5]   2.00-3.00   sec  4.47 MBytes  37.5 Mbits/sec    0    127 KBytes       
[  5]   3.00-4.00   sec  3.98 MBytes  33.4 Mbits/sec    0    139 KBytes       
[  5]   4.00-5.00   sec  4.41 MBytes  37.0 Mbits/sec    0    136 KBytes       
[  5]   5.00-6.00   sec  4.10 MBytes  34.4 Mbits/sec    0    139 KBytes       
[  5]   6.00-7.00   sec  3.91 MBytes  32.8 Mbits/sec    0    136 KBytes       
[  5]   7.00-8.00   sec  4.04 MBytes  33.9 Mbits/sec    0    144 KBytes       
[  5]   8.00-9.00   sec  4.23 MBytes  35.4 Mbits/sec    0    147 KBytes       
[  5]   9.00-10.00  sec  4.35 MBytes  36.5 Mbits/sec    0    156 KBytes       
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec  42.0 MBytes  35.2 Mbits/sec    0             sender
[  5]   0.00-10.05  sec  40.4 MBytes  33.7 Mbits/sec                  receiver

iperf Done.
```

**Comment by ophub** [comment]
unifreq升级过好几次这个驱动，之前在x96max盒子上，群里有的人能用无线有的不能用，讨论区里对这个驱动的讨论贴有好几个。

根据讨论贴的反馈，大多数魔百和都要降频才能稳定使用，不然会出现emmc读写错误，无法启动等问题，降低到25hz使用。把CPU调频的最大最小都降低到合适的频率就可以稳定使用了。

**Comment by dumplingwrapper** [comment]
@RayPS 目前测速结果（上传能到100mbit/s，下载还是50mbit/s）
root@armbian:~# iperf3 -c 192.168.5.10 -R 1
Connecting to host 192.168.5.10, port 5201
Reverse mode, remote host 192.168.5.10 is sending
[  5] local 192.168.5.16 port 58684 connected to 192.168.5.10 port 5201
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-1.00   sec  2.51 MBytes  21.1 Mbits/sec
[  5]   1.00-2.00   sec  2.67 MBytes  22.4 Mbits/sec
[  5]   2.00-3.00   sec  4.02 MBytes  33.7 Mbits/sec
[  5]   3.00-4.00   sec  4.85 MBytes  40.7 Mbits/sec
[  5]   4.00-5.00   sec  4.68 MBytes  39.3 Mbits/sec
[  5]   5.00-6.00   sec  4.33 MBytes  36.3 Mbits/sec
[  5]   6.00-7.00   sec  4.48 MBytes  37.6 Mbits/sec
[  5]   7.00-8.00   sec  4.07 MBytes  34.2 Mbits/sec
[  5]   8.00-9.00   sec  4.54 MBytes  38.1 Mbits/sec
[  5]   9.00-10.00  sec  5.05 MBytes  42.3 Mbits/sec
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate
[  5]   0.00-10.00  sec  41.4 MBytes  34.7 Mbits/sec                  sender
[  5]   0.00-10.00  sec  41.2 MBytes  34.6 Mbits/sec                  receiver

iperf Done.
root@armbian:~# iperf3 -c 192.168.5.10 -P 1
Connecting to host 192.168.5.10, port 5201
[  5] local 192.168.5.16 port 59566 connected to 192.168.5.10 port 5201

[ ID] Interval           Transfer     Bitrate         Retr  Cwnd
[  5]   0.00-1.00   sec  13.8 MBytes   116 Mbits/sec    0    450 KBytes
[  5]   1.00-2.00   sec  10.0 MBytes  83.9 Mbits/sec    0    436 KBytes
[  5]   2.00-3.00   sec  10.0 MBytes  83.9 Mbits/sec    0    478 KBytes
[  5]   3.00-4.00   sec  11.2 MBytes  94.4 Mbits/sec    0    436 KBytes
[  5]   4.00-5.00   sec  10.0 MBytes  83.9 Mbits/sec    0    413 KBytes
[  5]   5.00-6.00   sec  11.2 MBytes  94.4 Mbits/sec    0    452 KBytes
[  5]   6.00-7.00   sec  10.0 MBytes  83.9 Mbits/sec    0    489 KBytes
[  5]   7.00-8.00   sec  11.2 MBytes  94.4 Mbits/sec    0    430 KBytes
[  5]   8.00-9.00   sec  10.0 MBytes  83.9 Mbits/sec    0    433 KBytes
[  5]   9.00-10.00  sec  10.0 MBytes  83.9 Mbits/sec    0    430 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-10.00  sec   108 MBytes  90.2 Mbits/sec    0             sender
[  5]   0.00-10.00  sec   105 MBytes  88.1 Mbits/sec                  receiver

iperf Done.
配置情况

<img width="1399" height="179" alt="Image" src="https://github.com/user-attachments/assets/684aa704-6dd3-4b58-9bdd-a7548039ac1a" />

<img width="935" height="525" alt="Image" src="https://github.com/user-attachments/assets/396e6269-3a4c-49a2-9720-9e70ea6799a3" />

**Comment by tvro123** [comment]
@ophub  err  log:

 v25.11.0 for Aml.S905l3a running Armbian Linux 6.1.155-ophub

 Packages:     Debian stable (trixie)
 IPv4:         (LAN) 192.168.2.152, 192.168.2.155 (WAN) 117.30.***.*** 

 Performance:  

 Load:         50%               Uptime:       1 min     Local users:  2            
 Memory usage: 13% of 1.87G  
 CPU temp:     41Â°C             Usage of /:   39% of 14G    

 Commands: 

 Configuration : armbian-config
 Monitoring    : htop

root@armbian:~# [  131.110373] skbuff: skb_over_panic: text:ffffffc0024f3350 len:9007 put:9007 head:ffffff800a3f0000 
data:ffffff800a3f0040 tail:0x236f end:0x1ec0 dev:<NULL>
[  131.123406] ------------[ cut here ]------------
[  131.127909] kernel BUG at net/core/skbuff.c:121!
[  131.132482] Internal error: Oops - BUG: 00000000f2000800 [#1] SMP
[  131.138519] Modules linked in: rtw88_8822cs rtw88_sdio rtw88_8822c rtw88_core mac80211 cfg80211 panfrost rfkill
 libarc4 snd_soc_meson_axg_sound_card gpu_sched snd_soc_meson_card_utils drm_shmem_helper snd_soc_meson_g12a_tohdmitx
 meson_vdec(C) snd_soc_meson_codec_glue zram meson_gxbb_wdt videobuf2_dma_contig snd_soc_meson_axg_tdmout snd_soc_me
 son_axg_spdifout v4l2_mem2mem snd_soc_meson_axg_frddr snd_soc_meson_axg_fifo meson_ir snd_soc_meson_axg_tdm_interface 
 snd_soc_meson_axg_tdm_formatter binfmt_misc nfsd auth_rpcgss lockd grace sunrpc nfnetlink ip_tables x_tables

**Comment by ielex** [comment]
![Image](https://github.com/user-attachments/assets/b4b233ae-93e1-42a6-88e5-1ca98188ed2b)这是什么问题呀
nmtui-radio显示enable

**Comment by WorrWu** [comment]
怎么操作哇，大神，我用的CM311-1a也是识别不出来Wi-Fi，咋弄

**Comment by WorrWu** [comment]
> [@RayPS](https://github.com/RayPS) [@ophub](https://github.com/ophub) 我已经成功驱动了
> 
> ![Image](https://github.com/user-attachments/assets/d4df04ba-0419-49fb-a7d6-01d95872900a)
> 
> ![Image](https://github.com/user-attachments/assets/cab8d84a-3bf2-4a28-8c08-87333461087e)

咋弄的大神

**Comment by dumplingwrapper** [comment]
> > [@RayPS](https://github.com/RayPS) [@ophub](https://github.com/ophub) 我已经成功驱动了
> > ![Image](https://github.com/user-attachments/assets/d4df04ba-0419-49fb-a7d6-01d95872900a)
> > ![Image](https://github.com/user-attachments/assets/cab8d84a-3bf2-4a28-8c08-87333461087e)
> 
> 咋弄的大神

这图怎么像是我的呢，你弄通没有哦

**Comment by dumplingwrapper** [comment]
> > [@RayPS](https://github.com/RayPS) [@ophub](https://github.com/ophub) 我已经成功驱动了
> > ![Image](https://github.com/user-attachments/assets/d4df04ba-0419-49fb-a7d6-01d95872900a)
> > ![Image](https://github.com/user-attachments/assets/cab8d84a-3bf2-4a28-8c08-87333461087e)
> 
> 咋弄的大神

你需要去找到源dts去增加配置

<img width="1411" height="1168" alt="Image" src="https://github.com/user-attachments/assets/b068e322-8a44-4594-b3a2-c9fc9ffda38b" />

这张图的这个是最关键的，然后把dts里面紫光信息换成RTL的就行了
