### ISSUE TITLE
s905l2加mt7668，对大佬的仰慕涛涛不绝，

### ISSUE THREAD

**Issue by fhpeerless** [ophub/amlogic-s9xxx-armbian#2416]
**Device Information | 设备信息**
S0905L2
先科 x9

ophup9.1.97

驱动是mt7668

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

没有驱动啊，.......................

**Comment by syhandzp** [comment]
> **Device Information | 设备信息** S0905L2 先科 x9
> 
> ophup9.1.97
> 
> 驱动是mt7668
> 
> **Describe the bug | 问题描述** All issues will only remain open for one week to prioritize resolving them. After that period, they will be closed but can still continue to be discussed in the thread. 所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。
> 
> 没有驱动啊，.......................

看到有人说要自己编译

**Comment by fhpeerless** [comment]
哦哦，那个内核仓库有驱动啊，
