### ISSUE TITLE
试了多个版本cm211-1 905l3 都无法进入U盘启动&905l3 是否有显示输出？

### ISSUE THREAD

**Issue by tj4906** [ophub/amlogic-s9xxx-armbian#2417]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.36]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

刷不了armbian黑屏
211-1 2+8刷了很多211-1的镜像 
ophub 大佬帮忙看看进U盘黑屏没有ip
安卓底包是4.4.2的adb权限包  用的开心助手6.0 u盘启动

![5I1(( %A @6SB@QF@ZC7P6N](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/ac85189c-e955-4dad-8a92-010dbf5b87d9)

![qq_pic_merged_1720587557096](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/c6441706-7b1a-4397-b8e4-a8be30d49eba)
![2IWN5$A6)X8(A3 8 $1)EU5](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/62905b83-6f3b-44c5-b061-ee10eefb4553)

![3PQQPWB%J1KAPRBTW}UYL6Y](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/556963ad-30af-430a-8704-842c60f2a2e0)

**Comment by ophub** [comment]
在首页的设备列表里点对应的设备，进入之前的反馈帖子看用法。

**Comment by tj4906** [comment]
我看过一些了贴纸 但是没有很方便的找到该怎么解决问题！！！麻烦指点一下谢谢！！

**Comment by tj4906** [comment]
FDT=/dtb/amlogic/meson-gxl-s905l2-x7-5g.dtb  ？用这个dtb可以吗?大佬

**Comment by ophub** [comment]
相近的都可测试，参照model表里的组合表。

**Comment by tj4906** [comment]
我想用最新的哈哈
![5PKXT5$(48Q2$H_SZI TJG](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/b4389290-728e-43db-8a00-f0536a58c76a)
![23$P{APT10Z9XQ`1KVK~)}5_tmb](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/575c5175-4a03-44ac-8a17-4b254c5e906e)

**Comment by tj4906** [comment]
UBOOT_OVERLOAD填写：u-boot-p212.bin   这个在烧录好的镜像的哪里没有找到

**Comment by ophub** [comment]
/boot/下看看

**Comment by tj4906** [comment]
通过修改U盘烧录的u-boot-p212.bin为u-boot.ext后路由获取到了armbian 的ip但是在写入emmc遇到无法启动的问题拔掉U盘就不行了  我也补全了修改的u-boot-p212.bin并删除了u-boot.ext后在进行的安装写入
![OAILCK)CSGEE61~2~ VM{)G](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/feee4c14-2084-4385-9aef-126cb206b116)

**Comment by ophub** [comment]
添加u-boot可能改变IP，到路由器看新IP
另外你为什么要手动输入呢？对照model表选择你的这个配置即可，参数`-m yes`就是使用u-boot。看仓库首页的文档。
另外不要把u-boot-xxx.bin给改名了，你改名后这个文件没了，以后在安装、更新内核等时候要使用这个文件结果没了，更新即砖。文档里专门说了不要改名，非要自己手动操作要复制一份。

**Comment by tj4906** [comment]
不改名路由里面没有ip 只有把u-boot-p212.bin改为u-boot.ext后路由获取到了armbian 的ip 然后看到大佬说要把u-boot-p212.bin改回来在写入emmc 我也是这样做的  改好写入emmc后关机拔掉U盘 开机后路由里始终没有出现armbian的ip 应该是没写入进emmc的原因吧大佬分析下看看！！上面有cmmc的品牌图

**Comment by ophub** [comment]
你可以复制一份，但不要改名。
默认安装命令不添加u-boot，看我前面回复的安装时添加u-boot的命令。
是否添加了u-boot在安装日志的上半部分，你截图的是下半部分。

**Comment by tj4906** [comment]
我的目的有没有u-boot无所谓  只要写入后能正常进入系统就行
但是我拔掉U盘后无法获取到ip 没办法使用了！

**Comment by tj4906** [comment]
还有我在烧录好系统的同时在资源管理器里面复制一份改名为u-boot.ext 这样两份文件同时存在的时候也能正常进入U盘启动  但是写入的emmc 系统貌似没有正常工作 无法得到ip

**Comment by ophub** [comment]
本来就是同时存在的，说了半天不要改名，复制并存。在emmc里是u-boot.emmc
由安装脚本的-m选项自动添加。你安装时选了吗？

**Comment by tj4906** [comment]
所以我安装的命令应该armbian-install -m 吗？

**Comment by tj4906** [comment]
![OAILCK)CSGEE61~2~ VM{)G](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/ed2383cc-1985-49d5-b63f-d3aa08a1
![VRP{}I06X{19OMQRJ1MEQSE](https://github.com/ophub/amlogic-s9xxx-armbian/assets/175182377/a21ec79d-b7d8-4aa7-b3d4-f0bec2ce1fc4)
fa1a)

**Comment by tj4906** [comment]
armbian-install -m yes -a no  按照这个命令后关机拔掉U盘还是不能启动emmc里的armbian 请教我该怎么解决呢？

**Comment by tj4906** [comment]
通过不断的摸索 用115序号成功刷入emmc，但是有遇到一个很奇怪的问题不能ssh？ u盘启动状态下ssh可以连接盒子，将armbian刷入emmc后，拔掉u盘，重启盒子可以正常启动，路由器显示已经连接盒子，通过ip电脑上可以ping通盒子，但是就是ssh连接不上

**Comment by tj4906** [comment]
![FZKA7_8~( @732R W2%4PQ](https://github.com/user-attachments/assets/58dc6d8c-e245-437e-aaf6-0805a4c9cac5)
刷入emmc后无法ssh截图

**Comment by tj4906** [comment]
![L@M{`XY33BHT2A`3$9W%9LC](https://github.com/user-attachments/assets/2ee00e91-1d07-4f06-9162-b9a209f9b606)
会有间歇性断网的情况
