### ISSUE TITLE
UNT403A armbian-install失败 EMMC

### ISSUE THREAD

**Issue by knbnaz** [ophub/amlogic-s9xxx-armbian#2418]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - Model [e.g. UNT403A]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 61.96]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
```


    _              _   ____  ___   ___  ____  _ _____
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|| |___ /  __ _
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \| | |_ \ / _` |
 / ___ \| | | | | | |_ ___) \__, | |_| |___) | |___) | (_| |
/_/   \_\_| |_| |_|_(_)____/  /_/ \___/|____/|_|____/ \__,_|

Welcome to Armbian OS 24.8.0 Bullseye with Linux 6.1.96-ophub

System load:   75%              Up time:       2 min
Memory usage:  7% of 1.89G      IP:            192.168.3.143
CPU temp:      49°C             Usage of /:    10% of 15G
storage/:      31% of 510M
RX today:      6.4 KiB

root@armbian:~# armbian-install
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Use ampart tool: [ yes ]
[ INFO ] Show all devices: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------                                                                                                                              ---------------------
ID    SOC        MODEL                                         DTB                                                                                                                                            
--------------------------------------------------------------------------------                                                                                                                              ---------------------
301   s905x2     X96-Max-4GB,Tx5-Max                           meson-g12a-x96-ma                                                                                                                              x.dtb
302   s905x2     X96-Max-2GB,A95X-F2                           meson-g12a-x96-ma                                                                                                                              x-rmii.dtb
303   s905x2     MECOOL-KM3-4G                                 meson-g12a-sei510                                                                                                                              .dtb
304   s905l3a    E900V22C-D,CM311-1a-CH,IP112H,B863AV3.1-M2    meson-g12a-s905l3                                                                                                                              a-e900v22c.dtb
305   s905l3a    CM311-1a-YST                                  meson-g12a-s905l3                                                                                                                              a-cm311.dtb
306   s905l3a    M401A,UNT403A,B863AV3.2-M                     meson-g12a-s905l3                                                                                                                              a-m401a.dtb
0     Other      Customize                                     Enter-custom-dtb-                                                                                                                              name
--------------------------------------------------------------------------------                                                                                                                              ---------------------
[ OPTIONS ] Please Input ID: 306
[ INFO ] Input Box ID: [ 306 ]
[ INFO ] Model Name: [ M401A,UNT403A,B863AV3.2-M ]
[ INFO ] FDTFILE: [ meson-g12a-s905l3a-m401a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-e900v22c.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root?
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 2.01154 s, 2.1 MB/s
[ INFO ] Start create MBR and partittion.
Error: Input/output error during write on /dev/mmcblk2
Error: /dev/mmcblk2: unrecognised disk label
Error: /dev/mmcblk2: unrecognised disk label
[ ERROR ] Failed to partition internal eMMC using [ parted ].


```
Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by knbnaz** [comment]
> **设备信息 |设备信息**
> 
> * SOC：[例如 S095l3a]
> * 型号 [例如 UNT403A]
> 
> **Armbian 版本 |系统版本**
> 
> * 内核版本：[例如 61.96]
> * 发布：[例如靶心]
> 
> **Describe the bug | 问题描述** 


    _              _   ____  ___   ___  ____  _ _____
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|| |___ /  __ _
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \| | |_ \ / _` |
 / ___ \| | | | | | |_ ___) \__, | |_| |___) | |___) | (_| |
/_/   \_\_| |_| |_|_(_)____/  /_/ \___/|____/|_|____/ \__,_|

Welcome to Armbian OS 24.8.0 Bullseye with Linux 6.1.96-ophub

System load:   75%              Up time:       2 min
Memory usage:  7% of 1.89G      IP:            192.168.3.143
CPU temp:      49°C             Usage of /:    10% of 15G
storage/:      31% of 510M
RX today:      6.4 KiB

root@armbian:~# armbian-install
[ STEPS ] Installing Armbian to internal eMMC...
[ STEPS ] Checking dependencies...
[ INFO ] Dependency check completed. Proceeding installation...
[ STEPS ] Initializing the environment...
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Use ampart tool: [ yes ]
[ INFO ] Show all devices: [ no ]
[ INFO ] Internal eMMC : [ /dev/mmcblk2 ]
[ STEPS ] Start selecting device...
--------------------------------------------------------------------------------                                                                                                                              ---------------------
ID    SOC        MODEL                                         DTB                                                                                                                                            
--------------------------------------------------------------------------------                                                                                                                              ---------------------
301   s905x2     X96-Max-4GB,Tx5-Max                           meson-g12a-x96-ma                                                                                                                              x.dtb
302   s905x2     X96-Max-2GB,A95X-F2                           meson-g12a-x96-ma                                                                                                                              x-rmii.dtb
303   s905x2     MECOOL-KM3-4G                                 meson-g12a-sei510                                                                                                                              .dtb
304   s905l3a    E900V22C-D,CM311-1a-CH,IP112H,B863AV3.1-M2    meson-g12a-s905l3                                                                                                                              a-e900v22c.dtb
305   s905l3a    CM311-1a-YST                                  meson-g12a-s905l3                                                                                                                              a-cm311.dtb
306   s905l3a    M401A,UNT403A,B863AV3.2-M                     meson-g12a-s905l3                                                                                                                              a-m401a.dtb
0     Other      Customize                                     Enter-custom-dtb-                                                                                                                              name
--------------------------------------------------------------------------------                                                                                                                              ---------------------
[ OPTIONS ] Please Input ID: 306
[ INFO ] Input Box ID: [ 306 ]
[ INFO ] Model Name: [ M401A,UNT403A,B863AV3.2-M ]
[ INFO ] FDTFILE: [ meson-g12a-s905l3a-m401a.dtb ]
[ INFO ] MAINLINE_UBOOT: [  ]
[ INFO ] BOOTLOADER_IMG:  [  ]
[ INFO ] UBOOT_OVERLOAD: [ u-boot-e900v22c.bin ]
[ INFO ] NEED_OVERLOAD: [ no ]
[ STEPS ] Which type of filesystem do you want for your root?
-----------------------------------------------
  ID   TYPE
-----------------------------------------------
  1    ext4
  2    btrfs
-----------------------------------------------
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 2.01154 s, 2.1 MB/s
[ INFO ] Start create MBR and partittion.
Error: Input/output error during write on /dev/mmcblk2
Error: /dev/mmcblk2: unrecognised disk label
Error: /dev/mmcblk2: unrecognised disk label
[ ERROR ] Failed to partition internal eMMC using [ parted ].

> 
> 请提供问题的详细说明，如有必要，请附上屏幕截图。 详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
降低dtb的频率试试，方法看仓库的文档

**Comment by knbnaz** [comment]
> > 降低dtb的频率试试，方法看仓库的文档
> 
> 文档翻过了，实在没找到在哪里，能指个路吗

换成老版本可以使用了

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md

看12.16

**Comment by knbnaz** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
> 
> 看12.16
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/107289432/ed25a2c7-9d52-471e-985e-88334cc99745)

**Comment by knbnaz** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md
> 
> 看12.16
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/107289432/347a1486-5eb3-491b-8d2a-691a1b8b0f62)
我尝试手动导入文件，但是反编译出错

**Comment by ophub** [comment]
当前目录下有dtb吗？你执行命令是对当前目录下文件的的反编译。

**Comment by knbnaz** [comment]
> 当前目录下有dtb吗？你执行命令是对当前目录下文件的反编译。

如何获取dtb呢

**Comment by ophub** [comment]
dtb在/boot/dtb/amlogic目录下。
你先看看仓库的文档，看了再操作。

**Comment by knbnaz** [comment]
> dtb在/boot/dtb/amlogic目录下。 你先看看仓库的文档，看了再操作。

![QQ_1720678223930](https://github.com/ophub/amlogic-s9xxx-armbian/assets/107289432/8f70bf26-fe9e-4c8a-ba09-b087db216b66)

**Comment by knbnaz** [comment]
> dtb在/boot/dtb/amlogic目录下。 你先看看仓库的文档，看了再操作。

我甚至反编译没有动过文件，也提示数值不对

**Comment by knbnaz** [comment]
> dtb在/boot/dtb/amlogic目录下。 你先看看仓库的文档，看了再操作。

很急

**Comment by knbnaz** [comment]
> dtb在/boot/dtb/amlogic目录下。 你先看看仓库的文档，看了再操作。

![QQ_1720743185335](https://github.com/user-attachments/assets/d58eff71-9229-4cc5-ab82-3b7081a3b918)
O大救命

**Comment by knbnaz** [comment]
> dtb在/boot/dtb/amlogic目录下。 你先看看仓库的文档，看了再操作。

我发现我的错误了，但是我全部的数值都试过了，依旧无法写入

**Comment by ophub** [comment]
一个问题不要开2个帖子重复问。
你测试的时候不要在/boot/dtb/amlogic下进行操作，复制到一个安全的目录编译好了再复制dtb文件回来覆盖。
如果频率都降低到25了还不能用，理论上不会的。除非你的是nand存储，这个现在脚本写入不了，你可以拆开盒子看看主板上的存储芯片的型号。
