### ISSUE TITLE
S905L2 MGV2000  求助问题：emmc不识别、 8822bs无线驱动

### ISSUE THREAD

**Issue by gsjsjg** [ophub/amlogic-s9xxx-armbian#2419]
**Device Information | 设备信息**
 - SOC: [ S905L2 ]
 - Model [ MGV2000 ]
 - 内存1G、EMMC 8G 、无TF
 - DTB  meson-gxl-s905l2-x7-5g.dtb
 - WIFI  rtw_8822bs
**Armbian Version | 系统版本**
 - Kernel Version: [6.6.36-ophub]
 - Release: [Armbian_24.8.0_amlogic_s905l2_noble_6.6.36_server_2024.07.01.img.gz]

https://img.dearjoe.top/file/2525514e2e0461fa69248.jpg

**Describe the bug | 问题描述**
求助问题：emmc不识别、 8822bs无线驱动

dmesg error 

Driver 'optee' was unable to register with bus_type 'arm_ffa' because the bus was not initialized.
mmc2: tuning execution failed: -5
mmc2: error -5 whilst initialising MMC card
lima d00c0000.gpu: error -ENODEV: _opp_set_regulators: no regulator (mali) found
rtw_8822bs mmc0:0001:1: failed to write data to rsvd page
rtw_8822bs mmc0:0001:1: failed to download rsvd page
rtw_8822bs mmc0:0001:1: failed to download firmware
rtw_8822bs mmc0:0001:1: failed to setup chip efuse info
rtw_8822bs mmc0:0001:1: failed to setup chip information

https://img.dearjoe.top/file/2941108976187d9e7059a.jpg

**Comment by gsjsjg** [comment]
![微信截图_20240711175545](https://github.com/ophub/amlogic-s9xxx-armbian/assets/75055570/7c40052c-fe96-4204-a3f4-8c935b5cff1c)
![Uploading S905L2主板.jpg…]()

**Comment by gsjsjg** [comment]
![Uploading S905L2主板.jpg…]()

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.6.y/tree/main/drivers/net/wireless/realtek

内核里没驱动

**Comment by gsjsjg** [comment]
> https://github.com/unifreq/linux-6.6.y/tree/main/drivers/net/wireless/realtek
> 
> 内核里没驱动

谢谢大神解答

**Comment by gsjsjg** [comment]
> > https://github.com/unifreq/linux-6.6.y/tree/main/drivers/net/wireless/realtek
> > 内核里没驱动
> 
> 谢谢大神解答

https://github.com/unifreq/linux-6.6.y/blob/main/drivers/net/wireless/realtek/rtw88/rtw8822bs.c
这个不是驱动？

**Comment by gsjsjg** [comment]
https://github.com/SLAzurin/armbian-aml-arm64-buster/blob/master/Armbian_20.10_Arm-64_buster_current_5.9.0.img.xz.z01

这个固件可以看到wifi 但是报错 不能使用

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.6.y/blob/1d6843318e58c28ca341092417c8758d0f01a567/drivers/net/wireless/realtek/rtw88/Kconfig#L48

真的有了，我记得8822cs和8822bs之前内核默认没有呢，之前F大从第三方加过但是有些x96max+设备不能用，也有人反应能用。

**Comment by gsjsjg** [comment]
> https://github.com/unifreq/linux-6.6.y/blob/1d6843318e58c28ca341092417c8758d0f01a567/drivers/net/wireless/realtek/rtw88/Kconfig#L48
> 
> 真的有了，我记得8822cs和8822bs之前内核默认没有呢，之前F大从第三方加过但是有些x96max+设备不能用，也有人反应能用。
> 
> https://github.com/ophub/kernel/blob/0fff287135791565240d311f7df56ca0e874b2c8/kernel-config/release/general/config-6.6#L3280
> 
> 我看了一下内核里选择了，你手动加载一下试试
> 
> `sudo modprobe rtw88_8822bs`

-------------------------------------------------------------------------------------------
root@armbian:~# lsmod
Module                  Size  Used by
rfkill                 36864  1
sunrpc                561152  1
binfmt_misc            24576  1
zram                   32768  3
meson_vdec             81920  0
snd_soc_meson_gx_sound_card    16384  0
snd_soc_meson_card_utils    16384  1 snd_soc_meson_gx_sound_card
videobuf2_dma_contig    24576  1 meson_vdec
v4l2_mem2mem           45056  1 meson_vdec
meson_ir               20480  0
snd_soc_meson_t9015    24576  1
snd_soc_meson_aiu      32768  3
meson_gxbb_wdt         16384  0
snd_soc_meson_codec_glue    16384  1 snd_soc_meson_aiu
sg                     36864  0
tcp_bbr                20480  8
sch_fq                 20480  2
dm_mod                131072  0
nfnetlink              20480  1
ip_tables              28672  0
x_tables               45056  1 ip_tables
lima                   61440  0
gpu_sched              45056  1 lima
drm_shmem_helper       24576  1 lima
root@armbian:~# lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
sda            8:0    1  14.9G  0 disk
├─sda1         8:1    1   511M  0 part /boot
└─sda2         8:2    1  14.4G  0 part /var/log.hdd
                                       /
mmcblk2      179:0    0   7.3G  0 disk
mmcblk2boot0 179:32   0     4M  1 disk
mmcblk2boot1 179:64   0     4M  1 disk
zram0        253:0    0 394.3M  0 disk [SWAP]
zram1        253:1    0    50M  0 disk /var/log
zram2        253:2    0     0B  0 disk

以上emmc解决，dtb里修改emmc频率为  5后面7个0 即可

-------------------------------------------------------------------------------------------

以下 运行 sudo modprobe rtw88_8822bs 之后 lsmod信息

root@armbian:~# modprobe rtw88_8822bs
root@armbian:~# lsmod
Module                  Size  Used by
rtw88_8822bs           16384  0
rtw88_sdio             24576  1 rtw88_8822bs
rtw88_8822b           225280  1 rtw88_8822bs
rtw88_core            172032  2 rtw88_sdio,rtw88_8822b
mac80211              946176  2 rtw88_sdio,rtw88_core
cfg80211              917504  2 rtw88_core,mac80211
libarc4                16384  1 mac80211
rfkill                 36864  2 cfg80211
sunrpc                561152  1
binfmt_misc            24576  1
zram                   32768  3
meson_vdec             81920  0
snd_soc_meson_gx_sound_card    16384  0
snd_soc_meson_card_utils    16384  1 snd_soc_meson_gx_sound_card
videobuf2_dma_contig    24576  1 meson_vdec
v4l2_mem2mem           45056  1 meson_vdec
meson_ir               20480  0
snd_soc_meson_t9015    24576  1
snd_soc_meson_aiu      32768  3
meson_gxbb_wdt         16384  0
snd_soc_meson_codec_glue    16384  1 snd_soc_meson_aiu
sg                     36864  0
tcp_bbr                20480  8
sch_fq                 20480  2
dm_mod                131072  0
nfnetlink              20480  1
ip_tables              28672  0
x_tables               45056  1 ip_tables
lima                   61440  0
gpu_sched              45056  1 lima
drm_shmem_helper       24576  1 lima

wifi还是没解决。。。

**Comment by xf110** [comment]
我也是同样的盒子，同样的问题。无线不能用

**Comment by mobile-163** [comment]
我也遇到同样的问题。安卓底包下是能用的！  哪位大神给看看啊~~~

**Comment by LeosDing** [comment]
还是没有解决，内核已经升级到最新的6.6.61-ophub了，是不是wifi固件的问题？

**Comment by fox2k25** [comment]
老哥你是怎么刷的 写入U盘就能直接启动吗 我手头是s905l2+8822BS网卡 1+8的mgv2000-k 康佳的

**Comment by gsjsjg** [comment]
> 老哥你是怎么刷的 写入U盘就能直接启动吗 我手头是s905l2+8822BS网卡 1+8的mgv2000-k 康佳的 

把固件写到U盘，盒子刷好对应的安卓固件，设置走U盘启动即可。我的盒子是九联版的，没有 -k 这个参数
