### ISSUE TITLE
Could you suggest the way to build armbian for Rockchip 3318/3328?

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#242]
@ophub 
I can see there are kernel/u-boot for RK3328 from https://github.com/unifreq/openwrt_packit/tree/master/files/rk3328.

So is it able to build Armbian firmware for RK3318/3328 which uses the latest kernel from unifreq like you made for S9xxx?
Thank you.

**Comment by ophub** [comment]
rk3328 does not need u-boot, they use the main line, which is easier and easier to use than amlogic, you can refer to the practice of OpenWrt.

**Comment by dinhchinh82** [comment]
> rk3328 does not need u-boot, they use the mainline kernel, which is easier and easier to use than amlogic, you can refer to the practice of OpenWrt.

Should I download the kernel & uboot file from Flippy then replace the files in your Amlogic build?

**Comment by ophub** [comment]
No, delete u-boot and bootloader related code, ignore this

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/154e13388a7d58fb283471653131bcd47e02d436/rebuild#L479-L485

https://github.com/ophub/amlogic-s9xxx-armbian/blob/154e13388a7d58fb283471653131bcd47e02d436/rebuild#L623-L632

**Comment by dinhchinh82** [comment]
@ophub great. I will remove the code from amlogic-s9xxx-armbian/rebuild file according to your guide and try to build again.

**Comment by dinhchinh82** [comment]
@ophub I've removed 2 parts of code from rebuild script according to your guide.

By the way, I don't understand what I should do with this one:
`https://github.com/ophub/luci-app-amlogic/blob/daef961acf0085c2e732c199d554494ea754341a/luci-app-amlogic/root/usr/sbin/openwrt-kernel#L36`

**Comment by dinhchinh82** [comment]
I'm trying to build as setting below:
<img width="1321" alt="image" src="https://user-images.githubusercontent.com/22479095/163964832-574124ad-c96c-4211-bc8c-64c748df4a1f.png">

**Comment by ophub** [comment]
https://github.com/unifreq/openwrt_packit/blob/master/mk_rk3328_beikeyun.sh

You can learn his packaging script

**Comment by dinhchinh82** [comment]
> https://github.com/unifreq/openwrt_packit/blob/master/mk_rk3328_beikeyun.sh
> 
> You can learn his packaging script

I already read Flippy script but I don't understand how to run that script on Github action.

So I'm thinking that it's better to reuse your script to make it work via Github action. 
That's reason I make this issue.

**Comment by dinhchinh82** [comment]
I just got failed on Github action why trying to rebuild armbian:

<img width="846" alt="image" src="https://user-images.githubusercontent.com/22479095/163975772-f9298b79-b0a3-4228-adfb-b427a90cde91.png">

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/a38714c3c62a0ab3fe1da036100274df6e285009/rebuild#L73


https://github.com/ophub/amlogic-s9xxx-armbian/blob/a38714c3c62a0ab3fe1da036100274df6e285009/rebuild#L359-L364

**Comment by dinhchinh82** [comment]
I already added according to your base:

https://github.com/dinhchinh82/amlogic-s9xxx-armbian/blob/3691188209a7ca49279640e23ab91e666a8655e5/rebuild#L71 

https://github.com/dinhchinh82/amlogic-s9xxx-armbian/blob/3691188209a7ca49279640e23ab91e666a8655e5/rebuild#L370

https://github.com/dinhchinh82/amlogic-s9xxx-armbian/blob/3691188209a7ca49279640e23ab91e666a8655e5/rebuild#L451

**Comment by ophub** [comment]
https://github.com/dinhchinh82/amlogic-s9xxx-armbian/blob/131cf8dc7972b111241cfb5c3e65fa4d3d85da4f/.github/workflows/rebuild-armbian.yml#L88

**Comment by ophub** [comment]
https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L670

https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L1499

https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L1539

**Comment by dinhchinh82** [comment]
> https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L670
> 
> https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L1499
> 
> https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L1539
> 
> https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/mk_rk3328_beikeyun.sh#L132

what should I do with the files above? Should I fork unifreq/openwrt_packit/ and build again from my repo?

**Comment by ophub** [comment]
This has the corresponding code in amlogic. You add judgment in the relevant part, refer to his judgment

**Comment by dinhchinh82** [comment]
> This has the corresponding code in amlogic. You add judgment in the relevant part, refer to his judgment

I just confused which source code file should I modify from your base source code to add the snippet code you mentioned above?

<img width="1268" alt="image" src="https://user-images.githubusercontent.com/22479095/163997467-999f0e3b-e885-412e-b616-39e2f3d9d508.png">

**Comment by ophub** [comment]
My script to compile firmware has only one file： rebuild

**Comment by ophub** [comment]
add: dtb-rockchip-xxx.tar.gz

**Comment by dinhchinh82** [comment]
> My script to compile firmware has only one file： rebuild

So all the snippet code you mentioned about should be updated to your rebuild script, right?

**Comment by ophub** [comment]
Yes, add judgment in the corresponding place to deal with this special SOC: rk3328

**Comment by dinhchinh82** [comment]
> Yes, add judgment in the corresponding place to deal with this special SOC: rk3328

I will try to judge the difference then report you the result. Hope you will support to build it successfully.

**Comment by dinhchinh82** [comment]
@ophub I tried to build Rk3328 again yesterday and got success overall but some detail error.
Can you help me to check how to fix the detail error?

> (1.1) Start building Armbian [ rk3328 - 5.15.34 ]. Remaining space is 29G.
 [ rk3328 - 5.15.34 ]  (1/6) Confirm version type.
 [ rk3328 - 5.15.34 ]  (2/6) Extract old armbian files.
 [ rk3328 - 5.15.34 ]  (3/6) Refactor related files.
tar: /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/tmp_dir/tmp_build/bootfs/dtb/rockchip: Cannot open: No such file or directory

<img width="1110" alt="image" src="https://user-images.githubusercontent.com/22479095/164134212-6dc4559e-7b11-4138-a02f-d807c13b82bb.png">

Detail log build:
https://github.com/dinhchinh82/amlogic-s9xxx-armbian/runs/6078974259?check_suite_focus=true

Thank you.

**Comment by ophub** [comment]
https://github.com/unifreq/openwrt_packit/blob/4e247ba8aeb508f7fc54eec328502eaf5d26caed/public_funcs#L670

**Comment by dinhchinh82** [comment]
@ophub As I think most of your script are enough to build Armbian Rk3328 with some modification any may not need any script from Flippy.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/22479095/164171921-be101cef-a163-4b16-a72d-0c746ddf81b0.png">
As this photo, there is a command to create the rockchip dtb folder

> build_dtb=$(ls ${kernel_path}/${kernel}/dtb-rockchip-${kernel}-*.tar.gz 2>/dev/null | head -n 1)

> tar -xzf ${build_dtb} -C ${tag_bootfs}/dtb/rockchip && sync

**Comment by dinhchinh82** [comment]
@ophub I have another idea to make the RK3328 image manually first as below:

Step 1: build Armbian for S905X3 as usual

Step 2: plug TF card to the computer, create armbianEnv.txt file as you mentioned.

Step 3: extract the rockchip dtb from dtb-rockchip-5.4.188-flippy-71+o.tar.gz the copy to /dtb/rockchip folder and update armbianEnv.txt file.

how do you think about this solution?

Beside the armbianEnv.txt and dtb file, is there any other difference between S905x and RK3328 armbian?

thank you.

**Comment by dinhchinh82** [comment]
@ophub I can build RK3328 successfully as below:
<img width="528" alt="image" src="https://user-images.githubusercontent.com/22479095/164236460-37988bba-47a9-44b2-a104-6c2445317d6c.png">

**Comment by ophub** [comment]
I read flippy's script, and I probably found the 4 differences that you posted above. You can look for others. Do you have this kind of equipment?

**Comment by dinhchinh82** [comment]
> I read flippy's script, and I probably found the 4 differences that you posted above. You can look for others. Do you have this kind of equipment?

I don't use the flippy's script, only change some parts of your script related to dtb file, armbianEnv.txt file. 

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/22479095/164270089-88d11cdf-ef41-4d67-84bb-b8a69807712b.png">

I don't know whether other generated firmware files are different between RK3328 & S905x or not?

<img width="497" alt="image" src="https://user-images.githubusercontent.com/22479095/164269825-a62d914a-1e52-4fbc-8d69-1511fad63bce.png">

<img width="715" alt="image" src="https://user-images.githubusercontent.com/22479095/164269886-55083764-51a7-463d-aec2-9329047291de.png">

<img width="534" alt="image" src="https://user-images.githubusercontent.com/22479095/164269930-86d6587b-f58e-4c2a-85f9-44163acffdfa.png">

**Comment by ophub** [comment]
Remove uEnv.ext when using armbianEnv.txt
Delete amlogic when using rockchip under /boot/dtb
plus soc judgment

**Comment by dinhchinh82** [comment]
> Remove uEnv.ext when using armbianEnv.txt
> Delete amlogic when using rockchip under /boot/dtb
> Add soc judgment

@ophub 
I already deleted these files but still unable to boot. Still going to Android UI.

> If you have a device to test, first manually modify the local file, the test can be used, and then modify the compilation script to achieve the same purpose as manual modification

That's what I want to do first. I want to judge the local file manually to make sure it works before update the compilation script. 

Here are steps I update the local files manually for RK3328:

Step 1: Burn the [Armbian_22.05.0_Aml_s905x3_bullseye_5.4.188_2022.04.17.0035.img.gz] to TF card

Step 2: Plug the TF card to computer.

Step 3: Create  armbianEnv.txt file under the Boot partition as the content below (I use ext4):

> verbosity=7
overlay_prefix=rockchip
rootdev=UUID=0a6174af-7ccd-41b9-a6f5-0ee1e9e4ee70
rootfstype=ext4
rootflags=compress=zstd:6
extraargs=usbcore.autosuspend=-1
extraboardargs=
fdtfile=/dtb/rockchip/rk3328-box.dtb

Step 4: Delete /dtb/amlogic folder

Step 5: Delete uEnv.txt file

Step 6: Boot the T9 box (RK3318 4+32G) from TF card but unable to boot to Armbian.
I also tried both reset method using pushing AV port and adb shell remote update.

**Comment by ophub** [comment]
3328 and 3318 are used the same?
Here is the OpenWrt file of 3328. You can try to change the dtb of armbianEnv.txt and see if it can be started.
If OpenWrt can be started, and then debug armbian, they are basically the same.

**Comment by dinhchinh82** [comment]
> 3328 and 3318 are used the same?

As I know 3318 is similar to 3328 but cheaper. I've ever flashed RK3318 CSC firmware from Jock to both RK3328 and RK3318 box and they work.

>Here is the OpenWrt file of 3328. You can try to change the dtb of armbianEnv.txt and see if it can be started.

I tried to flash your OpenWrt to TF card but later on, there is no way to edit dtb because there is no Boot partition to open like S905x armbian.

I plug the TF card with your OpenWrt to the T9 3318 box but got the error while booting as below:
![IMG_6221](https://user-images.githubusercontent.com/22479095/164474077-07f95728-556b-4023-8c6d-eae11d8f0701.JPG)
![IMG_6224](https://user-images.githubusercontent.com/22479095/164474132-807b4bae-6a8e-435c-955c-071408b06e9e.JPG)

**Comment by dinhchinh82** [comment]
@ophub can you check the manual step to make Armbian for 3318 as this linke?
https://github.com/ophub/amlogic-s9xxx-armbian/issues/242#issuecomment-1104644994

**Comment by dinhchinh82** [comment]
> I don't have the equipment, I don't know

Okay, I will try by myself to test if it work.

>链接：https://pan.baidu.com/s/1kbvtyxpcmniLKN_ziH-kqQ 提取码：jla9
I don't have baidu account so there is no way to download.

Thank you very much for your support.

**Comment by ophub** [comment]
> > I don't have the equipment, I don't know
> 
> Okay, I will try by myself to test if it work.
> 
> > 链接：https://pan.baidu.com/s/1kbvtyxpcmniLKN_ziH-kqQ 提取码：jla9
> > I don't have baidu account so there is no way to download.
> 
> Thank you very much for your support.

Register for a free account and download

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/edit/tools

Armbian_20.10_Beikeyun_buster_5.4.108-flippy-56+o.img.xz

**Comment by dinhchinh82** [comment]
> https://github.com/ophub/kernel/releases/edit/tools
> 
> Armbian_20.10_Beikeyun_buster_5.4.108-flippy-56+o.img.xz

I don' see any images from the link above.

>Register for a free account and download

I tried to register an account but quite difficult. Registered successfully but unable to login to download for users outside China.

**Comment by ophub** [comment]
I uploaded it last night, I thought you had already downloaded it, I deleted it this morning and uploaded it for you just now

**Comment by dinhchinh82** [comment]
> I uploaded it last night, I thought you had already downloaded it, I deleted it this morning and uploaded it for you just now

Sorry I was busy today so I have not checked your reply.

Could you upload again by tomorrow (Saturday) and keep it about 2 hours from 9AM~11AM (Shanghai time)?

Thank you.

**Comment by ophub** [comment]
uploaded

**Comment by dinhchinh82** [comment]
@ophub I can download file Armbian_20.10_Beikeyun_buster_5.4.108-flippy-56+o.img.xz from your link. It's fine to delete it to save your space now. Thank you.

**Comment by dinhchinh82** [comment]
@ophub I've tested the Armbian_20.10_Beikeyun_buster_5.4.108-flippy-56+o.img.xz file but it got same error white booting as the previous build you send some days before:

https://user-images.githubusercontent.com/22479095/164474077-07f95728-556b-4023-8c6d-eae11d8f0701.JPG

Please note that after flashing to the TF card, there is unable to open the /boot partition to change the configuration on armbianEnv.txt as you mentioned before.

**Comment by ophub** [comment]
I don't have such equipment and am not familiar with how they should be set up. Search for relevant tutorials and test yourself.

**Comment by MX10-AC2N** [comment]
Hi @dinhchinh82 
For rk3318 and rk3328 
follow => https://forum.armbian.com/topic/17597-csc-armbian-for-rk3318rk3328-tv-box-boards/
his git => https://github.com/paolosabatino/armbian-build/tree/rk3318
work fine on my MX10-TvBox rk3328..

**Comment by avigrinberg** [comment]
Hi,
i've RK3328 SoC device and i want to install linux on it. can anyone have step by step guide for the whole process?
i don't have sd card. can i use USB DOK instead?


![WhatsApp Image 2023-09-07 at 18 18 54](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74825241/84d8729b-01ea-4238-b827-9de1d1980419)

THX
