### ISSUE TITLE
how to set HDMI resolution for specific resolution

### ISSUE THREAD

**Issue by tjengbudi** [ophub/amlogic-s9xxx-armbian#2425]
hello,
in raspberry pi i can set hdmi resolution for unique lcd. for example i want to set it to 1024x600
as i remember the old armbian (developed by 150balbes long ago) can set it but i not found in this firmware. is there any explanation how to change about this? or might be clue?

thanks

**Comment by 90999** [comment]
在uEnv.txt里 添加video=HDMI-A-1:1920x1080@60 ，传给内核就行了。
