### ISSUE TITLE
UNT402A(S905L) 桌面系统无法进入Xory模式是怎么回事！？

### ISSUE THREAD

**Issue by cao49049** [ophub/amlogic-s9xxx-armbian#2426]
固件是：Armbian OS 24.8.0 Bullseye with Linux 6.6.32-ophub
登录界面选择xory模式输入账号密码后会黑屏，然后又退回到登录界面，如此反复，无法正常进入桌面。
看了下“关于”，“图形”显示未知，是S905L不带GPU还是GPU没有驱动？是这个原因导致xroy模式进不去吗？

**Comment by PJ-568** [comment]
老问题了，可参考 [#1972](https://github.com/ophub/amlogic-s9xxx-armbian/discussions/1972)。

**Comment by cao49049** [comment]
> 老问题了，可参考 [#1972](https://github.com/ophub/amlogic-s9xxx-armbian/discussions/1972)。

按照这个方法操作后桌面可以正常启动，但是键盘鼠标都不起作用了，请问你知道是怎么回事吗？
