### ISSUE TITLE
请求适配mpc1911

### ISSUE THREAD

**Issue by mudebug77** [ophub/amlogic-s9xxx-armbian#2428]
之前看到有其他人适配过mpc1911 后面关闭了
通过修改tn3399的dts可以进入系统，wifi和蓝牙一直无法适配。
我修改了网卡，led 删除了一些不存在的设备，现在启动也不报错了，就只有风扇找不到。这个卡不存在风扇
不知道怎样修改这个。
wifi和蓝牙，实在不知道那里有问题，进入系统没有wlan，也没加载r8723bs
modprobe r8723bs 也没作用，会得到一个警告找不到参数
unknown parameter 'rtw_enusbss' ignored

除了蓝牙和wifi，其他都正常。附件是我修改过的dts，请大佬帮忙看看是哪里问题无法连接wifi。
每天晚上都有时间配合测试

![image](https://github.com/user-attachments/assets/25311582-6090-4739-9d1d-1666f0c7fc15)
![image](https://github.com/user-attachments/assets/21adc75f-9a0b-4fa4-8d4b-eb8ad57a1550)

**Comment by mudebug77** [comment]
[安卓提取的dts.zip](https://github.com/user-attachments/files/16281887/dts.zip)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.6.y/blob/main/arch/arm64/boot/dts/rockchip/rk3399-tn3399-v3.dts

这是dts的源代码，你在源码上修改，不要使用反编译文件。
r8723bs我在源码里没搜索到，内核里没驱动： https://github.com/unifreq/linux-6.6.y/tree/main/drivers/net/wireless

**Comment by mudebug77** [comment]
可以帮忙编译一个固件吗，我不太会编译固件。

**Comment by lfznnzq** [comment]
[mpc1911.zip](https://github.com/user-attachments/files/16443616/mpc1911.zip)
别人给了个改过dtb的armbian固件，提取出dts。
现在能正常启动，8211e千M网卡正常，hdmi没条件测试。
状态灯部分正常，8723bs无线网卡、声卡不识别。
