### ISSUE TITLE
Unable to update new kernel using armbian-update

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#243]
Today I try to update X96max+ (kernel 5.4) using armbian-update command but get error as below:

> armbian-update
Ready to update, please wait...
 [Error] Failed to get the version on the server.

Some days ago, I still could update kernel as usual.

Thank you.

**Comment by ophub** [comment]
The 5.4.y series kernel has been deleted and will be stopped in the future. 5.15.y now replaces 5.4.y, same usage

**Comment by dinhchinh82** [comment]
when will you plan to stop supporting 5.4?

As I tested, kernal 5.4 is still more stable than 5.15.y.

For example, when I test the wifi function on X96 max+ (2+16, WIFI 8189FTV) and X96 air (2+16, WIFI 8189FTV), the box will be crashed (kernel panic error) on 5.15.y if I connect to WIFI via armbian-config. 

But if these boxes connect to WIFI very good and no kernel panic on kernet 5.4.

**Comment by ophub** [comment]
He thinks 5.15 is better than 5.4, and recommends 5.4 users to switch to 5.15. I just removed the 5.4 kernel this morning.

The 5.4 kernel source library is still maintained, but the files are no longer compiled. Inline kernel compilation can be used if desired

**Comment by dinhchinh82** [comment]
> He thinks 5.15 is better than 5.4, and recommends 5.4 users to switch to 5.15. I just removed the 5.4 kernel this morning.
> 
> The 5.4 kernel source library is still maintained, but the files are no longer compiled. Inline kernel compilation can be used if desired

so if I still want to build Armbian 5.4, do I need to change any configuration on Github action as below?
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/22479095/163713639-4762fdeb-ee33-491a-99ed-00aebeead25d.png">

**Comment by ophub** [comment]
-k 5.15.25_5.10.100

**Comment by dinhchinh82** [comment]
> The 5.4 kernel source library is still maintained, but the files are no longer compiled. Inline kernel compilation can be used if desired

How to compile the 5.4 kernel by inline kernel compilation and using to build armbian via Github action?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/4071ff4a6baf4d2cdbda2e3b0beeb3b019b4002f/rebuild#L66

You can build a repo by yourself(such as: https://github.com/ophub/kernel ), put the kernel, and modify the warehouse address to point to your own kernel

**Comment by ophub** [comment]
Abandoning 5.4 and switching to 5.15 is a final result, and it may be better to reluctantly give up love earlier.
I will temporarily restore the 5.4 kernel in my repo, so that you can use it temporarily during the transition period

**Comment by dinhchinh82** [comment]
> Abandoning 5.4 and switching to 5.15 is a final result, and it may be better to reluctantly give up love earlier. I will temporarily restore the 5.4 kernel in my repo, so that you can use it temporarily during the transition period

Thank you so much. I will test more about 5.15 then trying to move to 5.15 soon.

**Comment by ophub** [comment]
5.4 to 5.15 have been upgraded by 10 versions, and more excellent drivers have been integrated. It is a great improvement to replace 5.4.

**Comment by ophub** [comment]
I've been using 5.4 for 2 years, it's a pain to say goodbye to him, but that's what's necessary

**Comment by dinhchinh82** [comment]
> I've been using 5.4 for 2 years, it's a pain to say goodbye to him, but that's what's necessary

Yes, I also have good image with 5.4. As before, I also tried 5.15 with my X96max+ (2+16, 8189FTV wifi) but unable to install to EMMC and kernel panic while connecting to WIFI. Anw, I will to to test 5.15 again and report to you the result.

Please not that the X96 max+ (2+16) is much different from 4+32 or 4+64 version. You will not be able to use ethernet on 2+16 version if using X96 max+ dtb, only could use ethernet if using X96 air dtb.

**Comment by ophub** [comment]
how about you try the 5.17 kernel

**Comment by dinhchinh82** [comment]
> how about you try the 5.17 kernel

As I remember you commented on other issue, 5.4 and 5.15 is long term support so I plan to try 5.4 & 5.15 only. I'm not sure 5.17 is long term support so I have not tried yet.

**Comment by ophub** [comment]
5.17-5.20 are temporary transition versions.
Last week, 5.15 was changed to the same strategy as 5.4, so it can replace 5.4

**Comment by dinhchinh82** [comment]
> 5.4 will be officially maintained until 2025, you can always compile it yourself

yes. I'm trying to build 5.4.189 kernel now. 
https://github.com/dinhchinh82/amlogic-s9xxx-openwrt/actions/runs/2180066581

By the way, I don't know where is the location to find out the output of building 5.4 kernel?

 Then I need to upload the 5.4.189 kernel files to the folder 5.4.189 in my kernel fork below, right?
https://github.com/dinhchinh82/kernel/tree/main/pub/stable

**Comment by ophub** [comment]
such as releases:
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/kernel_5.10.111_5.15.34

**Comment by dinhchinh82** [comment]
https://en.wikipedia.org/wiki/Linux_kernel_version_history

5.10 is supported up to 2026 while 5.15 only supported to 2023. So why Flippy did not fix 5.10 same as 5.15 to fix u-boot is no longer required?

**Comment by ophub** [comment]
will be extended once
