### ISSUE TITLE
TVI3315A emmc启动正常，有线网络正常，WiFi不可用 

### ISSUE THREAD

**Issue by damoshushu** [ophub/amlogic-s9xxx-armbian#2430]
感谢大佬们的无私奉献！已经刷好noble，但是遇到点小问题，请帮忙看看

**Device Information | 设备信息**
 - SOC: [e.g. TVI3315A]
 - Model [e.g. V11]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.98-ophub]
 - Release: [Armbian OS 24.8.0 Noble]

**Describe the bug | 问题描述**
有线正常，无线提示硬件丢失。可能是驱动没对。

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
![image](https://github.com/user-attachments/assets/5a749f1b-0f63-4b71-8805-6ed4f8dd2391)

附上完整日志
[dmesg.log](https://github.com/user-attachments/files/16286605/dmesg.log)

**Comment by why-miss** [comment]
同样的问题，怎么处理？

**Comment by linux-aarch64** [comment]
> 同样的问题，怎么处理？

设备树配置的问题，我这边是可以的（自己修改了下）
