### ISSUE TITLE
CM211-1 系列单独使用一个devicetree 文件

### ISSUE THREAD

**Issue by qinghon** [ophub/amlogic-s9xxx-armbian#2432]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model: Amlogic

**Armbian Version | 系统版本**
 - Kernel Version: 6.6.39
 - Release: jammy

**Describe the bug | 问题描述**

CM211-1 这个类型下变种太多了，我手上几个设备从DDR到EMMC 主板几乎是每个都不一样

单看EMMC， 现在表里使用的m302a dtb 里EMMC 在某次更新后打开了hs200 ，最高频率调到了200M ，这样有些批次的盒子就起不来了，我推荐独立一个dtb 出来使用低频给cm211 系列使用，避免影响s905l3 下其他盒子

这个修改需要上游仓库更新吗？每个系列都需要（5.x,6.1.y,6.6.y）？

note: 这个仓库里dtb 与./rebuild 镜像时下载的dtb 有些不太一致，

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-files/platform-files/amlogic/bootfs/dtb/amlogic

仓库里的是6.1.y为主的，看日期有的一年没更新了，但是上游内核源码更新了不少，这个只是个备用，在rebuild的时候会被解压的内核包覆盖了，所以虽然老旧了但是不影响使用，rebuild使用的都是最新内核。
