### ISSUE TITLE
小米盒子 4C 无线网络驱动编译请教

### ISSUE THREAD

**Issue by PJ-568** [ophub/amlogic-s9xxx-armbian#2433]
**Device Information | 设备信息**
 - SOC: [S905L]
 - Model [MiBox 4C]

**Armbian Version | 系统版本**
 - Image Name: [Armbian_24.8.0_amlogic_s905l_bookworm_6.1.98_server_2024.07.15.img]
 - Kernel Version: [6.1.98]
 - Release: [bookworm]

**Describe the bug | 问题描述**

开机后无法找到并使用 rtl8188ftv 驱动，遂尝试编译。

[kelebek333/rtl8188fu](https://github.com/kelebek333/rtl8188fu)

```shell
sudo apt-get install build-essential git dkms linux-headers-$(uname -r)
git clone https://github.com/kelebek333/rtl8188fu
sudo dkms install ./rtl8188fu
sudo cp ./rtl8188fu/firmware/rtl8188fufw.bin /lib/firmware/rtlwifi/
```

我在执行第一步时无法找到正确的 linux-headers。在执行第三条命令时也出现 linux-headers 相关错误。

请问我应该如何找到相应的 linux-headers？

**Comment by ophub** [comment]
linux-headers-xxx 在 /usr/src/ 目录下，不需要安装。

**Comment by PJ-568** [comment]
我在 `/usr/src/linux-headers-6.1.98-ophub` 下执行 `make scripts` 出现错误：

```
Configuration file ".config" not found!
...
```

**Comment by PJ-568** [comment]
```
git clone https://github.com/kelebek333/rtl8188fu
sudo dkms install ./rtl8188fu

...
'make'all KVER=6.1.98-ophub...(bad exit status: 2)
Error! bad return status for module build on kernel: 6.1.98-ophub (aarch64)
Consult .../log.txt for more info..
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/1043#issuecomment-1432720738
