### ISSUE TITLE
请问最新的关于homeassistant的镜像是什么？怎么使用？

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#2436]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

本人是使用Armbian系统，然后用KVM跑了一个HAOS虚拟机，但是机器不太稳定，过一段时间就会死机，显示故障为kernel panic，内存溢出什么什么的。

**Comment by ophub** [comment]
内核恐慌，换个内核

**Comment by Haaooo** [comment]
我主要就是想使用homeassistant，我能使用release里的关于homeassistant的那个镜像吗？应该怎么使用？

**Comment by ophub** [comment]
可以，和其他的一样。

**Comment by Haaooo** [comment]
请问这个固件和其他固件有什么区别？
里面是已经预装了homeassistant吗？

**Comment by Doboo** [comment]
> 请问这个固件和其他固件有什么区别？ 里面是已经预装了homeassistant吗？

是的。直接烧写到U盘，等待安装完成后就可以写入EMMC了
