### ISSUE TITLE
zram swap异常活跃

### ISSUE THREAD

**Issue by zvzl** [ophub/amlogic-s9xxx-armbian#244]
ram使用量才百分之25，zram非常活跃，导致系统负载高，调整swappiness也没啥效果。我挂了一个pcdn，磁盘读取平均每秒有十多MB，但是之前用的flippy固件没这个问题，今天是第一次用你们的最新固件，不知道有没有关系。
![图片](https://user-images.githubusercontent.com/84430227/163712144-51eb7f88-0a52-48d6-9362-e618123e6a17.png)
![图片](https://user-images.githubusercontent.com/84430227/163712163-8912ea34-c7fd-495b-824c-bc21a55a9902.png)

**Comment by ophub** [comment]
他是专业的，推荐你到他百度盘里下载他的固件使用。我是他的粉丝，但学艺不精，一般不推荐使用。

**Comment by zvzl** [comment]
我只是阐述事实，希望没冒犯到你。第一次碰见这种问题 ，很无奈。

**Comment by zvzl** [comment]
我暂时把swap关了，可以缓解一下。

**Comment by ophub** [comment]
上游官方支持多个分支编译，你可以fork了一键在线编译，看看其他分支的是否好点。当前仓库里的是今天的源码编译的。

**Comment by zvzl** [comment]
> 上游官方支持多个分支编译，你可以fork了一键在线编译，看看其他分支的是否好点。当前仓库里的是今天的源码编译的。

行，谢谢

**Comment by ophub** [comment]
你在进程里看看什么在跑，htop看看占用的哪个进程。如果你什么都没做，系统空载跑这么高太离谱了。

**Comment by zvzl** [comment]
不是空载，而且也不是开机就这样。

**Comment by ophub** [comment]
你是什么盒子，用的什么内核版本的固件，哪天的版本？虚拟内存占用这么多，跑的什么服务？

**Comment by zvzl** [comment]
hk1box,固件是Armbian_22.05.0_Aml_s905x3_focal_5.15.34_2022.04.16.0917.img，跑了网心云，具体看图
![图片](https://user-images.githubusercontent.com/84430227/163713001-65497baf-2599-492c-95e1-29673e84ef2c.png)

**Comment by zvzl** [comment]
虚拟内存占用不多，io很多。下图是占用情况
![图片](https://user-images.githubusercontent.com/84430227/163713039-94b13887-3609-48cb-a9ec-039fb94533e6.png)

**Comment by ophub** [comment]
你用5.15内核，物理内存识别了多少？4G？

**Comment by zvzl** [comment]
4G

**Comment by zvzl** [comment]
还好4g内存够大，不开swap也顶得住。顺便，我的系统是安装在U盘的，用的U盘启动。

**Comment by ophub** [comment]
网心云我在网上搜索了一下，是不是一个网络p2p的应用？占用你本地上行带宽，分发他的共享资源，根据占用你的空间和带宽来给你收益？

**Comment by zvzl** [comment]
是的，那个会持续读取磁盘，平均每秒读10+MB。昨天我是用的，flippy的5.4的内核70+o，没有问题。不是我截的图里，是zram0的io，我没截磁盘的。

**Comment by ophub** [comment]
有没有可能，刚才正在调用你的资源满载运行？是不是占用越多说明你收益会更多？如果不想让他占用太多能不能限制一下这个应用？

**Comment by zvzl** [comment]
我觉得应该不是应用的问题，我觉得是系统控制swap的问题，可能没有设置好。

**Comment by ophub** [comment]
我也是和f大用的一样的lede的上游源码，我刚才学习了一下他的打包脚本，也没有对这块的修改代码，所以理论上都是使用了lede的默认设置。这方面的设置是通用的，太高深的问题需要向他请教，我也一日三问，天天问他，但是我基础为零，萌新一枚，学艺不精。

**Comment by zvzl** [comment]
使用armbian-update升级到5.17.3后，问题消失了。5.15.33，5.15.34均能触发这个问题，开机20+分钟左右，swap读写io非常高。

**Comment by ophub** [comment]
好的，测试5.17好用就使用这个系列吧，其实内核也不用一直升级，如果当前很稳定，你`下载5.17.3备份下这个内核`，以后升级其他内核不好用还可以本地化升级回来，把内核的几个文件上传到某个目录，进入这个目录执行armbian-update就会从当前目录检查文件并更新。

**Comment by zvzl** [comment]
5.17.3也不行，只是触发时间晚一些，我再试试5.4.188

**Comment by zvzl** [comment]
切换到5.4.188解决问题了

**Comment by ophub** [comment]
升5.4.190试试

**Comment by zvzl** [comment]
已经解决了，就不折腾了

**Comment by zvzl** [comment]
5.4.190也完全正常

**Comment by ophub** [comment]
好的
