### ISSUE TITLE
output Segmentation fault when run ldconfig

### ISSUE THREAD

**Issue by nhchmg** [ophub/amlogic-s9xxx-armbian#2440]
**Device Information | 设备信息MDZ-21-AA

SOC: [e.g. s905l]
Model [e.g. Mibox-4]

[[Armbian_24.8.0_amlogic_s905l_bookworm_6.6.41_server_2024.07.20.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_HassIoSupervisor_bookworm_save_2024.07/Armbian_24.8.0_amlogic_s905l_bookworm_6.6.41_server_2024.07.20.img.gz)](url)

   将这个包写入tf卡，启动后，运行 ldconfig，就会报错 Segmentation fault

**Comment by ophub** [comment]
从首页点对应的设备，进去看之前用户分享的使用方法。

**Comment by nhchmg** [comment]
> 从首页点对应的设备，进去看之前用户分享的使用方法。

点首页进去 都是讲怎么刷机，怎么启动的。

我这个情况是己经启动进入armbian系统了， 运行 ldconfig 命令会报 Segmentation fault, 也就是说这个镜像包中的ldconfig  或者ldconfig 依赖的动态库有问题， 而几乎用apt install都会用到这个ldconfig ,导致无法正常apt install。
