### ISSUE TITLE
有没有办法防止USB启动复制固件或软件？

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2444]
有没有办法防止USB启动复制固件或软件？
自己开发一套软件，不想让人复制。目录可以加密，但是如果有人用U盘启动克隆整个EMMC，还是防不住。
看到以前的贴子，如果用MAC地址，好像有的盒子MAC 不固定。CPU id 不知道如何获取

**Comment by qinghon** [comment]
CPU 安全启动，需要用到amlogic SDK

**Comment by goldsoft8888** [comment]
> CPU 安全启动，需要用到amlogic SDK

方法太复杂，搞不来。我用MAC地址进行了加密

**Comment by wnpllrzodiac** [comment]
这个和armbian有啥关系？
