### ISSUE TITLE
Ran armbian-update on s905l3a, now device doesn't boot, any help welcome

### ISSUE THREAD

**Issue by loyukfai** [ophub/amlogic-s9xxx-armbian#2448]
```
    _              _      ____  ___   ___  ____  _ _____
   / \   _ __ ___ | |    / ___|/ _ \ / _ \| ___|| |___ /  __ _
  / _ \ | '_ ` _ \| |____\___ \ (_) | | | |___ \| | |_ \ / _` |
 / ___ \| | | | | | |_____|__) \__, | |_| |___) | |___) | (_| |
/_/   \_\_| |_| |_|_|    |____/  /_/ \___/|____/|_|____/ \__,_|

Welcome to Armbian 23.08.0-trunk Bullseye with Linux 5.15.123-ophub

System load:   3%               Up time:       1:28
Memory usage:  21% of 1.91G
CPU temp:      46°C             Usage of /:    89% of 6.8G
RX today:      60.0 MiB

[ General system configuration (beta): armbian-config ]

root@armbian:~# armbian-update
[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Dependency check completed.

[ STEPS ] Start checking network status...
[ INFO ] You can access [ github.com ] normally.

[ STEPS ] Start initializing parameters...
[ INFO ] Armbian platform: [ amlogic ]
[ INFO ] Kernel download repository: [ ophub/kernel ]
[ INFO ] Kernel download cdn: [  ]
[ INFO ] Kernel tags: [ stable ]
[ INFO ] Kernel version: [  ]
[ INFO ] Armbian is running on: [ /dev/mmcblk2 ]

[ STEPS ] Start querying kernel version...
[ INFO ] Query the latest kernel version of the [ 5.15 ] series within [ kernel_stable ]...
[ INFO ] Current version: [ 5.15.123 ], Latest version: [ 5.15.163 ].

[ STEPS ] Start downloading kernel package...
[ INFO ] Download kernel from: [ https://github.com/ophub/kernel/releases/download/kernel_stable/5.15.163.tar.gz ]
[ INFO ] Download kernel to:   [ /tmp/tmp.HQtQiIjUBF ]

[ STEPS ] Start checking kernel package...
[ INFO ] Kernel name: [ 5.15.163-ophub ]
[ INFO ] Overload is required: [ no ]
[ INFO ] Start performing sha256sum verification...
[ INFO ] (1/4) Verification of [ boot-5.15.163-ophub.tar.gz ] succeeded.
[ INFO ] (2/4) Verification of [ dtb-amlogic-5.15.163-ophub.tar.gz ] succeeded.
[ INFO ] (3/4) Verification of [ header-5.15.163-ophub.tar.gz ] succeeded.
[ INFO ] (4/4) Verification of [ modules-5.15.163-ophub.tar.gz ] succeeded.

[ STEPS ] Start backing up current kernel...
[ INFO ] (1/4) Backup of [ boot-5.15.123-ophub.tar.gz ] succeeded.
[ INFO ] (2/4) Backup of [ dtb-amlogic-5.15.123-ophub.tar.gz ] succeeded.
[ INFO ] (3/4) Backup of [ header-5.15.123-ophub.tar.gz ] succeeded.
[ INFO ] (4/4) Backup of [ modules-5.15.123-ophub.tar.gz ] succeeded.
[ INFO ] [ sha256sums ] file has been generated.
[ INFO ] Current kernel backup path: [ /ddbr/backup/5.15.123 ].

[ STEPS ] Start unpacking kernel...
[ INFO ] (1/4) Unpacking [ boot-5.15.163-ophub.tar.gz ] succeeded.
[ INFO ] (2/4) Unpacking [ dtb-amlogic-5.15.163-ophub.tar.gz ] succeeded.
[ INFO ] (3/4) Unpacking [ header-5.15.163-ophub.tar.gz ] succeeded.
[ INFO ] (4/4) Unpacking [ modules-5.15.163-ophub.tar.gz ] succeeded.

[ STEPS ] Start updating u-boot...

[ SUCCESS ] Kernel update succeeded. Armbian system is restarting...
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/documents#10-updating-armbian-kernel

**Comment by loyukfai** [comment]
Thanks!

Just wondering, is it safe to try another build like https://www.armbian.com/amlogic-s9xx-tv-box/ too? If not, how to revert back to your build?

Cheers.

**Comment by ophub** [comment]
The official version is definitely safe. I also based my rebuild version on the official one, just adding a little bit to what the official version does not support. The flashing method is the same, using USB to flash different Armbian firmware and then conducting tests.

**Comment by loyukfai** [comment]
Thanks! I got it back up running.

Just wondering, what is the recommended way to keep the whole shebang up-to-date?

The whole fiasco for me was hoping to keep it up-to-date, but caused mayhem instead.

FYI, I flashed your latest hassiosupervisor build onto USB, rebooted, and ran armbian-install, it erased everything on the device (which I kind of expected and made backups to important files), and re-setup the whole thing (thankfully a very simple setup).

In future, if I want to update armbian, hassio, how it should be done?

(BTW, what did you add on top of the official one?)

**Comment by ophub** [comment]
```
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get --purge autoremove -y
sudo apt-get autoclean -y

armbian-sync
armbian-update
```

**Comment by loyukfai** [comment]
Thanks! How about Home Assistant?

**Comment by ophub** [comment]
https://www.home-assistant.io/docs/

**Comment by loyukfai** [comment]
@ophub 

When I run the first command (apt-get update), it says the following, is this concerning?

```
The following packages have been kept back:
  armbian-bsp-cli-odroidn2-current initramfs-tools initramfs-tools-core
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/8893ef35004d166ea82286772518ba2b81749b8d/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L77-L85


These are specially locked and cannot be updated. They will replace u-boot and cause failure to boot.

**Comment by loyukfai** [comment]
Got it thanks!

> [amlogic-s9xxx-armbian/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix](https://github.com/ophub/amlogic-s9xxx-armbian/blob/8893ef35004d166ea82286772518ba2b81749b8d/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L77-L85)
> 
> Lines 77 to 85 in [8893ef3](/ophub/amlogic-s9xxx-armbian/commit/8893ef35004d166ea82286772518ba2b81749b8d)
> 
>  # Remove the scripts contained in [ armbian-bsp-cli-odroidn2 ] that will cause the system to fail to start 
>  # [ dpkg -c armbian-bsp-cli-odroidn2_23.02.2_arm64.deb ] : https://paste.armbian.com/aloxuvokol 
>  # Move /usr/share/armbian to armbian.bak. [ dpkg -S boot.cmd ] : [ armbian-bsp-cli-odroidn2: /usr/share/armbian/boot.cmd ] 
>  [[ -d "/usr/share/armbian" ]] && mv -f /usr/share/armbian /usr/share/armbian.bak && tolog "28. Move /usr/share/armbian to .bak" 
>  # Move /usr/lib/nand-sata-install to nand-sata-install.bak. [ Useless bootloader and u-boot ] 
>  [[ -d "/usr/lib/nand-sata-install" ]] && mv -f /usr/lib/nand-sata-install /usr/lib/nand-sata-install.bak && tolog "29. Move /usr/lib/nand-sata-install to .bak" 
>  # Disable update_initramfs 
>  initramfs_conf="/etc/initramfs-tools/update-initramfs.conf" 
>  [[ -f "${initramfs_conf}" ]] && sed -i "s|^update_initramfs=.*|update_initramfs=no|g" ${initramfs_conf} && tolog "30. Set update-initramfs.conf" 
> These are specially locked and cannot be updated. They will replace u-boot and cause failure to boot.

Got it thanks!
