### ISSUE TITLE
Armbian_HassIoSupervisor_bookworm error Homeassistant 

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#2455]
- SOC: [S095x3]
 - Model [HK1]

 - Kernel Version: [ Linux 6.6.42-ophub]
 - Release: [Armbian OS 24.8.0 Bookworm ]

![image](https://github.com/user-attachments/assets/8ce3aafd-2e1f-4b51-838c-0e3bff5095e1)

Hi @ophub , I just installed the Armbian HassIo Supervisor bookworm save 2024.07 version and when I start HA I get these errors!
Do you know how to solve them?

![image](https://github.com/user-attachments/assets/0a3dc216-5f34-46f6-9c69-83f31f91bb2c)

**Comment by dy008** [comment]
may be you can try

修改armbianEnv.txt
nano /boot/armbianEnv.txt
增加一行内容：
extraargs=systemd.unified_cgroup_hierarchy=0 apparmor=1 security=apparmor
重启系统完成

作者：活鱼
链接：https://juejin.cn/post/7387309614793261096
来源：稀土掘金
著作权归作者所有。商业转载请联系作者获得授权，非商业转载请注明出处。
