### ISSUE TITLE
怎么知道armbian对应的ubuntu还是debian版本？

### ISSUE THREAD

**Issue by wnpllrzodiac** [ophub/amlogic-s9xxx-armbian#2456]
Welcome to Armbian 23.11.0-trunk Lunar with Linux 6.1.63-ophub

这个是ubuntu22还是debain12？

**Comment by wnpllrzodiac** [comment]
找到了。
```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Armbian 23.11.0-trunk lunar
Release:        23.04
Codename:       lunar
```

如果想升级到 24.04 能在线升级吗？会变砖吗？

**Comment by ophub** [comment]
不会的，目前armbian系统没有特异功能，尚不能满足盒子变砖头的的质变。

**Comment by wnpllrzodiac** [comment]
> 不会的，目前armbian系统没有特异功能，尚不能满足盒子变砖头的的质变。

还是那个问题，23.04 怎么无痛升级到24.04, 怕过段时间23.04 apt源就失效了

**Comment by wnpllrzodiac** [comment]
不是，我只知道kernel版本可以无痛升级。ubuntu版本怎么在线升级啊？保留原来系统的所有配置

**Comment by ophub** [comment]
可以，比如从jammy升级到noble

**Comment by wnpllrzodiac** [comment]
> 可以，比如从jammy升级到noble

老板，教一下命令啵，或者给个传送门学习下。

**Comment by ophub** [comment]
找个你喜欢的搜索引擎，搜索如何从jammy升级到noble

**Comment by ophub** [comment]
这又没任何问题，提示你选择的这个apt仓库不可用，你就继续换别的源，找个能用的。

**Comment by wnpllrzodiac** [comment]
有空我升级下24.04. 早知道刷个LTS的系统了。
