### ISSUE TITLE
可以支持贝尔S010W AV2A吗

### ISSUE THREAD

**Issue by Cxyofficial** [ophub/amlogic-s9xxx-armbian#2458]
处理器是s905l3b

**Comment by ophub** [comment]
你试一下s905l3b的固件哪个合适

**Comment by Hx0531** [comment]
> 处理器是s905l3b

初心呀，叔和你一起试😺

**Comment by Hx0531** [comment]
> 处理器是s905l3b

![IMG_20241030_174712.jpg](https://github.com/user-attachments/assets/54b664f3-59ef-4351-b99a-f44bfbbfa606)

![IMG_20241030_174733.jpg](https://github.com/user-attachments/assets/130a3ed1-8cca-46b7-a4f5-320f6ac8421a)

![IMG_20241030_174726.jpg](https://github.com/user-attachments/assets/dabcdc3e-9453-4b6b-bd54-ea2bc7500eab)

**Comment by wangjian998** [comment]
> > 处理器是s905l3b
> 
> ![IMG_20241030_174712.jpg](https://github.com/user-attachments/assets/54b664f3-59ef-4351-b99a-f44bfbbfa606)
> 
> ![IMG_20241030_174733.jpg](https://github.com/user-attachments/assets/130a3ed1-8cca-46b7-a4f5-320f6ac8421a)
> 
> ![IMG_20241030_174726.jpg](https://github.com/user-attachments/assets/dabcdc3e-9453-4b6b-bd54-ea2bc7500eab)

 你刷成功了吗 设备和你一样的
