### ISSUE TITLE
机器kernel panic死机了

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#2462]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.100]
 - Release: [bookworm]

**Describe the bug | 问题描述**
HK1刷了armbian系统，连续运行几天后，死机了。
下面是死机界面：
![IMG_8249](https://github.com/user-attachments/assets/c78b08d2-9144-49cd-b8ee-e926fa5b04e9)

**Comment by ophub** [comment]
换个内核

**Comment by Haaooo** [comment]
> 换个内核
输入这个命令吗？
armbian-update -k x.x.xxx
我已经换过一次内核了，请问哪个内核稳定一点？

**Comment by ophub** [comment]
从上游内核更新记录来看，每周都在修复己知问题，所以下一个版本是最好的，下下一个更好…

**Comment by Haaooo** [comment]
> 从上游内核更新记录来看，每周都在修复己知问题，所以下一个版本是最好的，下下一个更好…
> 
> hk1从5.4.y到6.6.y有5个系列可以用，你可以试试你的设备用哪个最合适。

好的我去试试，感谢
