### ISSUE TITLE
tx3 mini 设置LED失败，CPU主频也调节不了。t95z plus 也是调节不了CPU主频，但是有led屏显示。

### ISSUE THREAD

**Issue by goldsoft8888** [ophub/amlogic-s9xxx-armbian#2464]
tx3 mini   主控s905w 
Armbian_24.8.0_amlogic_s905w_noble_6.6.43_server_2024.08.01.img
设置LED失败，换了几个内核也一样，
CPU主频也调节不了

[ OPTIONS ] Please Input ID: 18
[ STEPS ] Start the led screen display...
[ INFO ] Using LED Profiles: /usr/share/openvfd/conf/tx3-mini.conf
[ INFO ] turn led usb on ...
/usr/sbin/armbian-openvfd: line 114: /sys/class/leds/openvfd/led_on: No such file or directory
[ INFO ] turn led colon on ...
/usr/sbin/armbian-openvfd: line 114: /sys/class/leds/openvfd/led_on: No such file or directory
[ INFO ] turn led eth on ...
/usr/sbin/armbian-openvfd: line 114: /sys/class/leds/openvfd/led_on: No such file or directory
Open device failed.
: No such file or directory
[ INFO ] turn led wifi on ...
/usr/sbin/armbian-openvfd: line 114: /sys/class/leds/openvfd/led_on: No such file or directory
[ SUCCESS ] Enable LED display!
root@armbian:~#

**Comment by goldsoft8888** [comment]
t95z plus 也是调节不了CPU主频，但是有led屏显示。

**Comment by tri-pole** [comment]
@goldsoft8888 

I have an old Tanix TX3-mini s905w 2G/16G (mfgd by Oranth) and I got the VFD display working with Ophub kernel 6.6.50 by modifying (decompiling/editing/recompiling with `dtc`) the `dtb` in the following way:

In the `dtb` I removed the entire section `spi {...}` (where e.g. `led-controller@0` is defined) and removed also the entry for `tm1628` in the symbol table (at the end). (The entry for `openvfd {...}` in the `dtb` must remain.) After this, the VFD works with the kernel module `openvfd` present in Ophubs kernels and a openVFD service such as 7Ji's YAopenvfD. The kernel module can be loaded with e.g. `armbian-openvfd 18` (after loading the `openvfd` kernel module the VFD interface is present at `/sys/class/leds/openvfd`).

With this edit to the `dtb` the VFD access is no longer controlled by info in the `dtb` but by the parameters you supply when you load the `openvfd` module (or so I think, at least).

**Comment by goldsoft8888** [comment]
> [@goldsoft8888](https://github.com/goldsoft8888)
> 
> 我有一个旧的 Tanix TX3-mini s905w 2G/16G（由 Oranth 制造），我通过修改（反编译/编辑/重新编译）通过以下方式让 VFD 显示器与 Ophub 内核 6.6.50 一起工作：`dtc``dtb`
> 
> 在 I 删除了整个部分（例如 定义），并删除了 symbol 表中的 for 条目（在末尾）。（必须保留的条目。在此之后，VFD 与 Ophubs 内核中存在的内核模块和 openVFD 服务（如 7Ji 的 YAopenvfD）一起工作。内核模块可以加载例如 （加载内核模块后，VFD 接口位于 ）。`dtb``spi {...}``led-controller@0``tm1628``openvfd {...}``dtb``openvfd``armbian-openvfd 18``openvfd``/sys/class/leds/openvfd`
> 
> 通过对 VFD 的这种编辑，访问不再由中的信息控制，而由您在加载模块时提供的参数控制（或者我认为至少是这样）。`dtb``dtb``openvfd`
> 
> 编辑：我已经附上了我使用的（编辑的）。 [meson-gxl-s905w-tx3-mini-6.6.50-openvfd.dtb.zip](https://github.com/user-attachments/files/17088869/meson-gxl-s905w-tx3-mini-6.6.50-openvfd.dtb.zip)`dtb`

我现在用的是6.6.77,  用你的方法无效，
