### ISSUE TITLE
UUID的问题。

### ISSUE THREAD

**Issue by SycamoreKing** [ophub/amlogic-s9xxx-armbian#2469]
**Device Information | 设备信息**
 - SOC: [S905L3A]
 - Model [ZTE-B863AV3.2-M]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.43]
 - Release: [Armbian_24.8.0_amlogic_s905l3a_bookworm_6.6.43_server_2024.08.01.img.gz ]

**Describe the bug | 问题描述**
o大，你好，有一个中兴 B863AV3.2-M的魔百和，L3A的CPU，由于这个盒子的靠近网口的USB不能用，我从Android 选择从U盘启动，插入远离网口的USB口，可以启动 6.6.43，跑了不到10秒，卡在了initramfs ，上面提示 UUSD does not exist ，估计是不同USB口有不同的UUID，请教O，这个UUID可以修改为远离网口的那个USB口的吗？谢谢O大。
![微信图片_20240807090406](https://github.com/user-attachments/assets/d9d73d3e-122e-486f-808c-7259017480c8)

**Comment by ophub** [comment]
u盘里的固件损坏，找不到rootfs分区，你本地这个镜像坏了，重新下载个，有4个分支的，你可以试试其他分支的。使用 https://rufus.ie/ 刷机，有时候换个u盘重新刷也可以。

**Comment by SycamoreKing** [comment]
U盘固件没损坏，就这个U盘，我拿到另外一个905L3A 的盒子，靠近网口的USB上，可以启动。

**Comment by SycamoreKing** [comment]
O大，请教一下，这个
APPEND=root=UUID=4e12a4b6-58af-4004-adde-a15ab2d038ca
这个UUID是怎么来的？用什么工具才能知道是这一串UUID？

**Comment by SycamoreKing** [comment]
O大，请教一下，这个
APPEND=root=UUID=4e12a4b6-58af-4004-adde-a15ab2d038ca
这个UUID是怎么来的？用什么工具才能知道是这一串UUID？

**Comment by ophub** [comment]
这是rootfs分区的UUID，在制作镜像文件时生成的，在系统里可以通过blkid查看

**Comment by SycamoreKing** [comment]
> 这是rootfs分区的UUID，在制作镜像文件时生成的，在系统里可以通过blkid查看

看来没办法了，我测试我靠近网口的USB口，是有故障。但是他可以从远离网口的USB口启动，就卡在了这里。。。
