### ISSUE TITLE
JL2101 phy (for ethernet) not working in x96max+  with focal_5.15.34

### ISSUE THREAD

**Issue by navigos** [ophub/amlogic-s9xxx-armbian#247]
When booting up x96 max+ with s905x3 5.15.34 version, I get an error that the ethernet cannot be brought up.

Attached image of motherboard and dmesg output.

![1](https://user-images.githubusercontent.com/97533842/164013215-8aaae1e9-45ff-45b8-9e67-887a592be740.jpeg)

![2](https://user-images.githubusercontent.com/97533842/164011587-539e29d7-f2c8-4748-9332-44fb93ab091b.jpeg)

[dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8513221/dmesg.txt)

Thank you very much for your help.

**Comment by ophub** [comment]
meson-sm1-x96-air.dtb
/boot/uEnv.txt

**Comment by navigos** [comment]
Did not work.
Follow logs

[log.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8513634/log.txt)

**Comment by tri-pole** [comment]
It appears that your box has a JL2101 phy (for ethernet) which seems to be problematic under Linux, see e.g. [here](https://www.right.com.cn/FORUM/thread-4076037-1-1.html) (but I might be totally incorrect; I have used Google translate).

**Comment by navigos** [comment]
Thanks @tri-pole for you sugestion, but did not work.
Follow logs.
[dmesg_100mbps.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8514790/dmesg_100mbps.txt)
[ethtool.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8514791/ethtool.txt)

**Comment by tri-pole** [comment]
D'oh. The only last things I would try are; set flow control to off, change cable and try cold booting your box (sometimes this resets some chips better).

**Comment by navigos** [comment]
> D'oh. The only last things I would try are; set flow control to off, change cable and try cold booting your box (sometimes this resets some chips better).

The patch cord is fine. I tested using half and full duplexes and turning flow control on and off.

**Comment by tri-pole** [comment]
Ok, one last, desperate attempt: Over at Manjaro they have been fiddling with different dtb's for this family of boxes, see e.g. [the wiki](https://wiki.manjaro.org/index.php/Amlogic_TV_boxes)

**Comment by ophub** [comment]
The second picture can see that it is a JL2101 network card, which cannot be driven in the mainline kernel at present. If you find a driver that can be used in the mainline kernel on the Internet, please share the link address. (Not for Android). You try 8822cs wireless network card can be used.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/17deb8c7f3175fe3f8feb870fbbe79297e0501e1

This driver was added to unifreq today, then I will compile a version for you to test

**Comment by navigos** [comment]
Right. Thank you for your support.
Waiting for image to perform the tests.

**Comment by navigos** [comment]
I installed the new image 5.15.35. There is no error at startup.
The interface boots to 1000 mbps full duplex, but no IP address. I tried 100mbps, but also to no avail.

[dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8531865/dmesg.txt)
[systemctl.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8531866/systemctl.txt)

However, it can acquire an IP address when running at 10mbps full or half duplex.

**Comment by ophub** [comment]
Go to the router where the device is connected to the Internet to find the ip of the newly connected device

**Comment by navigos** [comment]
There is no communication when you change the connection speed to 100mbps or 1000mbps.
OpenWRT recognizes the speed change, but there is no communication.

In OpenWRT:
root@OpenWRT:~# swconfig dev switch0 port 2 get link
port:2 link:up speed:100baseT full-duplex txflow rxflow auto

Armenian logs:
[10mbps.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8534472/10mbps.txt)
[100mbps.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8534473/100mbps.txt)

**Comment by ophub** [comment]
@navigos 
Run this command to see what is returned: `cat /sys/class/net/eth0/phydev/phy_id`

**Comment by navigos** [comment]
> @navigos @tri-pole Run this command to see what is returned: `cat /sys/class/net/eth0/phydev/phy_id`

Wow that's good. There is still hope.

He follows.
[phy_id.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8584546/phy_id.txt)

**Comment by ophub** [comment]
3q

**Comment by navigos** [comment]
> 3q
> 
> There may be some problems with this driver, unifreq is in contact with the manufacturer, and then we will find you to test with the results.

It was working fine with armbian, kernel 5.4, here from ophub.  Even the eth0 interface was 1Gbps.

**Comment by ophub** [comment]
Unifreq contacted the manufacturer today, and needs to continue to debug the settings of `tx_delay` and `rx_delay`, and will make some .dtb files in a few days, please continue to test to determine the optimal configuration.

**Comment by ophub** [comment]
I'm surprised to see that you are gigabit under the 5.4 kernel. Send a log: `dmesg`
In addition, update 5.10/5.15/5.17 and send a copy of the dmesg information of each kernel.

armbian-update 5.10.113
armbian-update 5.15.36
armbian-update 5.17.5

**Comment by navigos** [comment]
> @navigos I'm surprised to see that you are gigabit under the 5.4 kernel. Send a log: `dmesg` In addition, update 5.10/5.15/5.17 and send a copy of the dmesg information of each kernel.
> 
> https://github.com/ophub/kernel/tree/main/pub/dev/5.15.36 https://github.com/ophub/kernel/tree/main/pub/dev/5.17.5
> 
> `armbian-update 5.15.36 dev` `armbian-update 5.17.5 dev`
> 
> `armbian-update 5.10.113 stable`

Hi!
Forgive me for the delay.
Follow logs.

[dmesg_5.4.191.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8599346/dmesg_5.4.191.txt)
[dmesg_5.15.36.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8599347/dmesg_5.15.36.txt)
[dmesg_5.17.5.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8599350/dmesg_5.17.5.txt)

I follow the procedure described in item 9 (https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs).

**Comment by ophub** [comment]
Hello, I see that your 5.15 kernel is not using the test kernel I modified. You use the following command to update the 5.15.36 kernel and send me dmesg. thanks
`armbian-update 5.15.36 dev`

**Comment by navigos** [comment]
> @navigos
> 
> Did you test your internet speed as gigabit?
> 
> Hello, I see that your 5.15 kernel is not using the test kernel I modified. Test the kernel in the `dev` directory. You use the following command to update the 5.15.36 kernel and send me `dmesg`. thanks `armbian-update 5.15.36 dev`

Hello.

I used iperf3 together with the OpenWRT router with SoC Atheros AR9344, which is the only device with a 1Gbps/s interface that I currently have.

[tcp_iperf3.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8604006/tcp_iperf3.txt)
[udp_iperf3.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8604008/udp_iperf3.txt)

I thing the SoC is limiting throughput.

**Comment by ophub** [comment]
ok. 3q

**Comment by EastWoodYang** [comment]
any update ?

**Comment by ophub** [comment]
@EastWoodYang @navigos 

https://github.com/ophub/kernel/tree/main/pub/stable/5.15.47
Today's new 5.15.47 kernel uses the same settings as 5.4 in the JL2101 driver. After you update the test, this should be able to drive the Gigabit correctly, and feedback your results after the test.

Update command: `armbian-update 5.15.47`

**Comment by EastWoodYang** [comment]
看着报错了，过来一会死机了。。。

![1655338785986](https://user-images.githubusercontent.com/9335046/173963244-b0f3aea2-c100-4fcc-9b6a-41901ec5b24f.png)

**Comment by ophub** [comment]
`armbian-update 5.4.198`
`armbian-update 5.15.47`
两个都测试一下

**Comment by EastWoodYang** [comment]
大哥，还是不行，我看你5.15.47升级到5.15.48了，我直接刷了你打的最新包[Armbian_22.08.0_Aml_s905x_focal_5.15.48_server_2022.06.16.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_server_06.17.0021/Armbian_22.08.0_Aml_s905x_focal_5.15.48_server_2022.06.16.img.gz)，无法获取到IP，然后update 到 5.4.199，能获取到IP了

**Comment by ophub** [comment]
armbian-update 5.10.123
armbian-update 5.18.5
armbian-update 5.15.48
这几个分别都试一下，昨天都改成5.4的方式了，你测试一下哪个有问题，反馈一下你的结果。

**Comment by EastWoodYang** [comment]
最近有点忙，早上刷了最新包，试了下 5.10.y 和 5.16.y，都能用了！感谢！

**Comment by ophub** [comment]
好的

**Comment by navigos** [comment]
> Hello @navigos @ophub
> 
> what dtb and kernel do you use for this version of the box?

New version not working? I tried to install armbian_ophub, but boot won't boot.

@EastWoodYang @ophub Any procedure? new dtb?

I tried this procedure, but not success > https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#124-set-the-box-to-boot-from-usbtfsd

ps: Works fine with emuelec.
