### ISSUE TITLE
关于系统完全启动后执行自己的脚本。

### ISSUE THREAD

**Issue by SycamoreKing** [ophub/amlogic-s9xxx-armbian#2470]
Device Information | 设备信息

    SOC: [S905L3A]
    Model [ZTE-B863AV3.2-M]

Armbian Version | 系统版本

    Kernel Version: [e.g. 6.6.43]
    Release: [Armbian_24.8.0_amlogic_s905l3a_bookworm_6.6.43_server_2024.08.01.img.gz ]

Describe the bug | 问题描述
O大，你好，电视盒刷入armbian后，我自己编写一个 bash的执行脚本以便获得机器IP，想在机器完全启动后，并且DHCP获取到IP后，执行这个 bash的脚本，请问该如何配置？我试过在 /etc/custom_service/start_service.sh 里配置，和 rc.local 里配置，但是都因为DHCP还没获取到IP，我的bash执行了没达到预期。
我的想法是，能否然armbian 完全启动后，5分钟后，再执行我的 bash 脚本呢？感谢O大。

**Comment by ophub** [comment]
您可以使用Linux中的"at"命令来实现在启动5分钟后执行特定指令。您可以按照以下步骤操作：

1. 首先，确保系统中已安装了"at"命令。如果未安装，您可以使用以下命令进行安装：
`sudo apt-get install at`


2. 接下来，使用以下命令来安排执行特定指令：
`echo "your_command" | at now + 5 minutes`

请将"your_command"替换为您想要执行的实际指令。

通过这样的方式，您可以安排在系统启动后的5分钟内执行特定指令。

也可以使用`sleep 3000 && "your_command"`
