### ISSUE TITLE
每次更新内核版本就会变砖

### ISSUE THREAD

**Issue by ksi1110** [ophub/amlogic-s9xxx-armbian#2473]
**Device Information | 设备信息**
 - SOC: [e.g. RK3328]
 - Model [e.g. 我家云-chainedbox-l1-pro]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.1.98]
 - Release: [e.g. bookworm]

**Describe the bug | 问题描述**

之前用的版本号忘记了，刷完系统后一直可以正常更新系统和内核版本，直到有一次更新完内核后不能引导，成砖。只能重新刷固件，
6月份刷了bullseye，内核版本是6.6.32，服务搭建好手残直接armbian-update一下，又成砖了，没办法就一直丢在一边没用了，7月中心血来潮，想做个下载机，重新下载了固件，这次版本是<<Armbian_24.8.0_rockchip_chainedbox_bookworm_6.1.98_server_2024.07.15>>，今天尝试用armbian-update -k 6.6.43更新内核，更完成砖，无言以对……

求问：
1.固件是否支持升级内核版本
2.release中的版本号为什么每个月都不一样，这个月是高版本下个月就是低版本，遵循的规则是什么
3.如果要升级内核版本，版本号应该怎样获取（今天是看了release中的版本号来升级的）

![image](https://github.com/user-attachments/assets/57cdccb8-379c-456c-b0f5-6aa99d82483e)

**Comment by ksi1110** [comment]
今天又看了下文档，chainedbox项支持的内核只有刷机包，应该是只支持刷机升级内核版本？希望作者看到可以回应下，十分感谢~~~

**Comment by ophub** [comment]
内核在这： https://github.com/ophub/kernel/releases
都支持升级内核，包括chainedbox也支持。如果你使用的很久之前的固件，先升级脚本再升级内核
```
armbian-sync
armbian-update
```

**Comment by ksi1110** [comment]
> 内核在这： https://github.com/ophub/kernel/releases 都支持升级内核，包括chainedbox也支持。如果你使用的很久之前的固件，先升级脚本再升级内核
> 
> ```
> armbian-sync
> armbian-update
> ```

感谢作者大大回复，我今天重新刷8月份的固件（Armbian_24.8.0_rockchip_chainedbox_bookworm_6.6.43_server_2024.08.01.img）试下能不能成功升级

**Comment by ksi1110** [comment]
> > 内核在这： https://github.com/ophub/kernel/releases 都支持升级内核，包括chainedbox也支持。如果你使用的很久之前的固件，先升级脚本再升级内核
> > ```
> > armbian-sync
> > armbian-update
> > ```
> 
> 感谢作者大大回复，我今天重新刷8月份的固件（Armbian_24.8.0_rockchip_chainedbox_bookworm_6.6.43_server_2024.08.01.img）试下能不能成功升级

试了下更新成功，感谢作者解惑

**Comment by liyiranlab** [comment]
> 内核在这： https://github.com/ophub/kernel/releases 都支持升级内核，包括chainedbox也支持。如果你使用的很久之前的固件，先升级脚本再升级内核
> 
> ```
> armbian-sync
> armbian-update
> ```

大佬最新发现，升级内核的时候再也起不来的原因可能，rk3328-l1pro-1296mhz.dtb 和 rk3328-l1pro-1512mhz.dtb 的字体可能有区别？因为之前升级内核时候手动改了1296为1512后升级，无法再连上我家云；后来不改，直接升级后成功，再改改超频时去目录下复制rk3328-l1pro-1512mhz.dtb这个文件名修改启动成功。猜测是文件名导致的问题。反复刷机验证是文件名不同导致，如果修改时候采用全名就没问题，希望大佬修复，可能无法使用高内核的固件也是文件名导致。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.12.y/tree/main/arch/arm64/boot/dts/rockchip

我看见文件名没问题

**Comment by liyiranlab** [comment]
> https://github.com/unifreq/linux-6.12.y/tree/main/arch/arm64/boot/dts/rockchip
> 
> 我看见文件名没问题

我看着也没问题，但是之前升级内核前只改1512，6.1内核下可以正常超频cpu，然后升级6.12就起不来了，我不甘心，从刷我家云最新系统，只是改了一下host名，直接升级6.6，成功了。重启前切换1512的dtb，只改了1512，重启后进不了我家云；又刷机，然后我想试试6.12，重新编译6.12内核，编译提示网卡驱动选n，升级我家云6.12内核成功，然后改1512的dtb全名复制到驱动文件，重启成功启动，然后复制1296的dtb全名到启动文件，恢复成功启动，重启后直接修改启动文件1296为1512，重启失败。

我得出结论，之前刷机后都键盘修改启动文件，1296为1512，在6.1原版镜像中可以成功切换，但是升级内核到6.6，6.12，1512的dtb文件名和之前的6.1镜像的文件名不同，则无法找到1512的dtb。

对了这个我家云有ttl对吧！我一会把无法开机ttl log给大佬！

**Comment by liyiranlab** [comment]
我再验证一遍，这次我不用键盘，直接复制1512的dtt文件的“1512”到启动文件看看还会不会砖。

**Comment by liyiranlab** [comment]
> 我再验证一遍，这次我不用键盘，直接复制1512的dtb文件的“1512”到启动文件看看还会不会砖。

刚刚验证，如果复制rk3328-l1pro-1512mhz.dtb文件中的“1512”到启动文件修改1296，重启没有问题。那就是用键盘修改"1512"导致的问题了。看来是我误报了，但是确实存在这个问题，6.1内核镜像不会识别错误键盘修改的“1512”，我修改文件名用的winscp。6.6，6.12不认我用键盘和winscp修改的1512。

**Comment by liyiranlab** [comment]
大佬，那能不能编译一个6.12内核的我家云镜像，我刷看看？然后把ttl上传给你。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-files/platform-files/rockchip/bootfs/dtb/rockchip

因为我的仓库里默认只有 [rk3328-l1pro-1296mhz.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/rockchip/bootfs/dtb/rockchip/rk3328-l1pro-1296mhz.dtb) 这一个，原始固件里没其他频率的另外2个，所以你直接修改肯定是无法启动的，没这个dtb，更新内核可以是因为内核tar包里有。

我一会更新下我的仓库底包，把这几个频率的也放进去。

**Comment by liyiranlab** [comment]
谢谢大佬
