### ISSUE TITLE
B860A S812处理器，期待适配armbian系统

### ISSUE THREAD

**Issue by qfnuzlr** [ophub/amlogic-s9xxx-armbian#2474]
**Device Information | 设备信息**
 - SOC: [e.g. S812]
 - Model [e.g. 中兴B860A]

**Armbian Version | 安卓4.4
 

原系统是安卓4.4 处理器s812与玩客云一样，1G内存 4G闪存  
玩客云能刷armbian系统，这个是不是也可以搞定呢>
大佬来适配一下吧
附原来安卓系统备份 https://cloud.189.cn/web/share?code=a6FRzavAzMvi（访问码：vv08）

**Comment by jamyu-li** [comment]
可以适配的，而且S812在主线运行还比较稳定。需要可以到这里看看。
[https://github.com/jamyu-li/Armbian-on-B860A-S812-TVBOX](url)
