### ISSUE TITLE
魔百盒cm211-1 云南 无法usb启动

### ISSUE THREAD

**Issue by lkber** [ophub/amlogic-s9xxx-armbian#2475]
芯片：S905L3
主板：mc022
Android_system：4.4（root）_（Android9的包没找到）
dtb：gxlx2_p291_2g
armbian_Img：s905l3_jammy_6.6.4_server_2024.8.01
s905l2_jammy_6.6.4_server_2024.8.01

问题：无法通过usb进入启动，内存卡，U盘刷写进入皆是黑屏或HDMI无输出，路由器也没识别网络，img无任何修改。
uEnv.txt里修改成s903b_m302a.dtb（有修改为全称）也不行。
不知道有人在相关机顶盒有进入系统的经验没，求赐教。
![IMG_20240813_004618](https://github.com/user-attachments/assets/a4928ea8-7417-450c-ab5a-78bd0216806a)
![IMG_20240813_004655](https://github.com/user-attachments/assets/ed740ac6-3161-4c8a-8a0a-40358566c648)

**Comment by qinghon** [comment]
连TTL 看看输出日志

**Comment by lkber** [comment]
> 连TTL看看输出日志

没得usb转ttl，搞不了。

**Comment by lkber** [comment]
> 芯片：S905L3主板：mc022Android_system:4.4(root)_(Android9的包没找到)DTB:gxlx2_P291_2garmbian_Img:s905l3_jammy_6.6.4_server_2024.8.01s905l2_jammy_6.6.4_server_2024.8.01_

> 
> 问题：无法通过usb进入启动，内存卡，U盘刷写进入皆是黑屏或HDMI无输出，路由器也没识别网络，img无任何修改.uEnv.txt里修改成s903b_m302a.dtb（有修改为全称）也不行。不知道有人在相关机顶盒有进入系统的经验没，求赐教。 ![IMG_20240813_004618](https://private-user-images.githubusercontent.com/83877221/357132587-a4928ea8-7417-450c-ab5a-78bd0216806a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDU5NzksIm5iZiI6MTcyMzU0NTY3OSwicGF0aCI6Ii84Mzg3NzIyMS8zNTcxMzI1ODctYTQ5MjhlYTgtNzQxNy00NTBjLWFiNWEtNzhiZDAyMTY4MDZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZTMyOTY4YWY4YzMwMjc2MTRhYjgwYzI2NDBiOTY5MGY4NDg0NzZiODVlNWI3YmQyNjZkMTE1ZTYwYjY3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9qkZPQmK8Iay5glpzjQUOfEJf6_GvjJLmAjcMbMecl4) ![IMG_20240813_004655](https://private-user-images.githubusercontent.com/83877221/357132545-ed740ac6-3161-4c8a-8a0a-40358566c648.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDU5NzksIm5iZiI6MTcyMzU0NTY3OSwicGF0aCI6Ii84Mzg3NzIyMS8zNTcxMzI1NDUtZWQ3NDBhYzYtMzE2MS00YzhhLThhMGEtNDAzNTg1NjZjNjQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhN2FiM2EwYjI2MTA4YTQ4YmYyZDFjYTQxODQ3MjU2OWI0M2M5NjI2Njg2ZjgyZmE0ZTFkM2FlMTMwN2E4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K7XLkzjX_a0kGoycnZRm_FvO25Kr2Z9dvnIYXuJDL7s)

1.

**Comment by lkber** [comment]
芯片：S905L3主板：mc022Android_system:4.4(root)_(Android9的包没找到)DTB:gxlx2_P291_2garmbian_Img:s905l3_jammy_6.6.4_server_2024.8.01s905l2_jammy_6.6.4_server_2024.8.01
 问题：无法通过usb进入启动，内存卡，U盘刷写进入皆是黑屏或HDMI无输出，路由器也没识别网络，img无任何修改.uEnv.txt里修改成s903b_m302a.dtb（有修改为全称）也不行。不知道有人在相关机顶盒有进入系统的经验没，求赐教。 ![IMG_20240813_004618](https://private-user-images.githubusercontent.com/83877221/357132587-a4928ea8-7417-450c-ab5a-78bd0216806a.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDU5NzksIm5iZiI6MTcyMzU0NTY3OSwicGF0aCI6Ii84Mzg3NzIyMS8zNTcxMzI1ODctYTQ5MjhlYTgtNzQxNy00NTBjLWFiNWEtNzhiZDAyMTY4MDZhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwZTMyOTY4YWY4YzMwMjc2MTRhYjgwYzI2NDBiOTY5MGY4NDg0NzZiODVlNWI3YmQyNjZkMTE1ZTYwYjY3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9qkZPQmK8Iay5glpzjQUOfEJf6_GvjJLmAjcMbMecl4) ![IMG_20240813_004655](https://private-user-images.githubusercontent.com/83877221/357132545-ed740ac6-3161-4c8a-8a0a-40358566c648.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDU5NzksIm5iZiI6MTcyMzU0NTY3OSwicGF0aCI6Ii84Mzg3NzIyMS8zNTcxMzI1NDUtZWQ3NDBhYzYtMzE2MS00YzhhLThhMGEtNDAzNTg1NjZjNjQ4LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEzVDEwNDExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhN2FiM2EwYjI2MTA4YTQ4YmYyZDFjYTQxODQ3MjU2OWI0M2M5NjI2Njg2ZjgyZmE0ZTFkM2FlMTMwN2E4ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.K7XLkzjX_a0kGoycnZRm_FvO25Kr2Z9dvnIYXuJDL7s)
