### ISSUE TITLE
Can't get into armbian TX3 mini S905W

### ISSUE THREAD

**Issue by fachos** [ophub/amlogic-s9xxx-armbian#2479]
Hi ophub...

i try to boot ophub-armbian to this tx3 but failed.. It's s905w 2gb/16gb... 
using toothpick method or let it boot itself also didnt work...
i burn stock android firmware then try to boot armbian also no luck..
please.... 

thank you

**Comment by fachos** [comment]
hi....

burn this stock firmware [TX3Mini-20181210.img](http://mediafire.com/file/cinmzoabg6w6hbw/TX3Mini-20181210.img/file) to tx3mini
burn this [Armbian_24.8.0_amlogic_s905w_bookworm_6.1.100_server_2024.07.25.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.07/Armbian_24.8.0_amlogic_s905w_bookworm_6.1.100_server_2024.07.25.img.gz) to sdcard
do toothpick method....
problem solved...

thank you

**Comment by ophub** [comment]
Thanks for sharing, I saved it to the Android system: https://github.com/ophub/kernel/releases/tag/tools
