### ISSUE TITLE
M8S Pro Plus cannot install to eMMC

### ISSUE THREAD

**Issue by bennydiamond** [ophub/amlogic-s9xxx-armbian#248]
Device: Mecool M8S Pro Plus 2GB/16GB. 
SoC: s905x
DTB: meson-gxl-s905x-p212.dtb
U-Boot: u-boot-p212.bin

Used to work with old Balbes150's images. Install to eMMC was working on Balbes150 5.9.0-arm64 images.
Trying to use following image: [Armbian_22.05.0_Aml_s905x_focal_5.10.111_2022.04.19.0020.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2022.04.19.0032/Armbian_22.05.0_Aml_s905x_focal_5.10.111_2022.04.19.0020.img.gz)

Device boot to MicroSD and USB drive successfully. 

Install to eMMC using `armbian-install` either with manual profile ID 0 or ID 103 will result in brick on reboot. Black screen, LED on unit stay Solid Red.
Only way to recover is to use USB_Burning_Tool to flash back factory image.

To clarify, my unit will boot and run armbian-install successfully but will then brick afterward. At that point, I need to recover using USB_Burning_Tool.

So is M8S Pro Plus unit supported by these images? Thanks.

**Comment by ophub** [comment]
You test the firmware of 5.15.34
