### ISSUE TITLE
无论使用官方源还是清华源执行apt update时都报错

### ISSUE THREAD

**Issue by Superstorm54188** [ophub/amlogic-s9xxx-armbian#2481]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model UNT403A

**Armbian Version | 系统版本**
 - Kernel Version: 24.8.0
 - Release:Noble

**Describe the bug | 问题描述**
在执行完apt update之后总会爆一条在源中找不到文件的错，在手动访问清华源/官方源时都找不到所请求的文件夹

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by Superstorm54188** [comment]
好像是请求bionic的文件

**Comment by wnpllrzodiac** [comment]
给个出错信息啊。全靠猜。。。

**Comment by Superstorm54188** [comment]
> 给个出错信息啊。全靠猜。。。

![Screenshot_2024_0818_124129](https://github.com/user-attachments/assets/ffc96e0a-c072-4a5f-a943-9e39eaa4c897)
如下

**Comment by ophub** [comment]
你的源改错了，不是这个系统的，源要和你的版本对应。

**Comment by Superstorm54188** [comment]
> 你的源改错了，不是这个系统的，源要和你的版本对应。

那用啥源（给个地址）

**Comment by ophub** [comment]
用你选择的固件的同版的源

**Comment by wnpllrzodiac** [comment]
https://mirrors.tuna.tsinghua.edu.cn/armbian/dists/
