### ISSUE TITLE
电视盒子，从 U 盘启动过 EmuElec 后，还能启动 Armbian 吗？

### ISSUE THREAD

**Issue by wuxunfeng666** [ophub/amlogic-s9xxx-armbian#2482]
1. 我有个 cm311-1a 盒子，做了下列步骤后，无法从 U 盘启动 Armbian：

   1. 下载对应型号的 Armbian 包
   2. 用 rufus 刷进 U 盘
   3. 更改 BOOT 分区下 uEnv.txt 里的内容：
      ```diff
      - FDT=/dtb/amlogic/meson-g12a-s905l3a-e900v22c.dtb
      + FDT=/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb
      ```
   4. 安卓里启动 Reboot to LibreELEU，黑屏后插入 U 盘
   5. 稍等几秒，屏幕上显示：
      ![IMG_20240815_020946](https://github.com/user-attachments/assets/b19b8b82-c37a-409a-a06e-23a8082317fc)

2. 我曾经用另一个 U 盘，刷入过 EmuElec，可以正常通过 U 盘启动。

   刚才在另一个[《CoreELEC启动后无法再启动Armbian？看这里！》](https://www.znds.com/tv-1194265-1-1.html)帖子里看到，

   若曾经启动过 CoreELEC（EmuElec 基于 CoreELEC？），就无法启动 Armbian 了？

3. 是我启动步骤有错吗？还是真的因为 EmuElec 无法启动呢？

**Comment by ophub** [comment]
只要盒子的emmc里是安卓系统即可，如果写入了EmuElec需要先恢复安卓系统。

**Comment by lkber** [comment]
这个问题b站有人做过，可以去看看
