### ISSUE TITLE
荐片盒子刷入armbian固件后无法正常启动

### ISSUE THREAD

**Issue by colinwong92** [ophub/amlogic-s9xxx-armbian#2484]
荐片盒子刷入armbian固件后无法正常启动，盒子是正常的，刷入安卓可以正常开机，刷入Armbian_24.8.0_rockchip_jp-tvbox_jammy_6.6.43_server_2024.08.01.img.gz和Armbian_24.8.0_rockchip_jp-tvbox_bullseye_6.6.43_server_2024.08.01.img.gz  都无法启动。无灯亮，联网路由无IP出现。

**Comment by ophub** [comment]
你试试下载7月份的6.1.y的荐片固件

**Comment by colinwong92** [comment]
> 你试试下载7月份的6.1.y的荐片固件

Jammy和bullseye _6.1.100_seve_2024.07.25也是不行，openwrt的也刷了，也是启动不了，只有安卓正常启动

**Comment by DavidTsou** [comment]
多尝试几个dtb，你会发现惊喜的

**Comment by wuzhen2022** [comment]
哪里可以下载荐片的armbian历史版本？我一直找不到下载列表

**Comment by colinwong92** [comment]
> 多尝试几个dtb，你会发现惊喜的

新手，怎么试dtb？求指点一下
