### ISSUE TITLE
B860AV2.1-M只能用Armbian_23.08.0 ，新固件找不到emmc

### ISSUE THREAD

**Issue by qfnuzlr** [ophub/amlogic-s9xxx-armbian#2485]
**Device Information | 设备信息**
 - SOC: [e.g. S905L3-b
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

 据说是频率问题
只能用旧固件，依然解决不了的是tf卡槽不能用

**Comment by bombjinne** [comment]
改下频率应该就行了，我也有个盒子识别不到，开始玩还以为是nand，拆了确认不是，改了频率就可以了

**Comment by qfnuzlr** [comment]
奥？ 怎么改呢？usb启动到armbian系统了，armbian-install安装时检测不到emmc

**Comment by bombjinne** [comment]
> 奥？ 怎么改呢？usb启动到armbian系统了，armbian-install安装时检测不到emmc

就是u盘启动了改，文档有详细教程
