### ISSUE TITLE
x96mini刷armbian爆出内核崩溃

### ISSUE THREAD

**Issue by BPG-WLCXY** [ophub/amlogic-s9xxx-armbian#2488]
求助一下这是咋回事，我刷如的版本是：Armbian_24.8.0_amlogic_s905w_jammy_6.6.43_server_2024.08.01.img
![FB7C0CB8753A9E12158CB865E81618E0](https://github.com/user-attachments/assets/017363f8-82f0-42fd-a3e7-fced3dd0c134)

**Comment by ophub** [comment]
下6.6.46试试，内核可以更换成其他系列的，例如5.4.y/6.1.y等

**Comment by BPG-WLCXY** [comment]
> 下6.6.46试试，内核可以更换成其他系列的，例如5.4.y/6.1.y等

不行啊，还是爆内核崩溃

**Comment by BPG-WLCXY** [comment]
我在BOOT分区里发现里面只有关于x96max,或maxpro类似的文件没有与x96mini相关的文件是不是这个版本不支持x96mini
这个是在BOOT分区里看到的
![b4471d7b-05dd-49a7-acf9-cb34befa825c](https://github.com/user-attachments/assets/125682cf-e813-4ab1-8982-613cc3fd445b)
然后这是在BOOT/dtb\amlogic里
![e283da62-6641-4de5-be98-46f7dd5577f3](https://github.com/user-attachments/assets/d5af2d6e-5a8a-4878-8559-d0933137b406)
![ffeca3e8-f879-4e37-8d3a-f963d0d528ff](https://github.com/user-attachments/assets/853c282b-53af-43d8-b472-1061a2c48523)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/f727b6c43b52e63968525f4d92cb72bb06ae5d6f/build-armbian/armbian-files/common-files/etc/model_database.conf#L61

**Comment by BPG-WLCXY** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/f727b6c43b52e63968525f4d92cb72bb06ae5d6f/build-armbian/armbian-files/common-files/etc/model_database.conf#L61

x96mini不适用？？？？

**Comment by BPG-WLCXY** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/f727b6c43b52e63968525f4d92cb72bb06ae5d6f/build-armbian/armbian-files/common-files/etc/model_database.conf#L61

如果是可以正常刷入，那恳请大佬帮我纠正一下我问题的所在

**Comment by BPG-WLCXY** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/f727b6c43b52e63968525f4d92cb72bb06ae5d6f/build-armbian/armbian-files/common-files/etc/model_database.conf#L61

刷入前是不是需要编辑一下BOOT分区里的文件或者是修改ROOTFR分区里的某项文件呢

**Comment by ophub** [comment]
/boot/uEnv.txt里的dtb名字改为： `meson-gxl-s905w-x96-mini.dtb`

**Comment by BPG-WLCXY** [comment]
> for仓库自己编译一个这个设备的固件，或者下载一个固件，把 里的dtb名字改为：`/boot/uEnv.txt``meson-gxl-s905w-x96-mini.dtb`

重新编译？我直接在做好的U盘BOOT分区修改没有效果

**Comment by BPG-WLCXY** [comment]
在GitHub上手动编译不了，是不是源码出问题了
![ab5078afecdbcfb867fe9d4d7df1783](https://github.com/user-attachments/assets/d900833b-9a3b-4e5e-99b2-e7b4d386a01e)
![af6e7588da19fdfda25e6016271a134](https://github.com/user-attachments/assets/975be3c0-7668-47d3-ad97-038d33261ea6)

**Comment by ophub** [comment]
在release里搜x96-mini

**Comment by goldsoft8888** [comment]
应该是买到假货了，现外贸盒子x96-mini、tx3-mini 之类的名字一样，但是芯片不一样，还遇到闲鱼上s905w的打磨芯片，用s905lb-2的

**Comment by BPG-WLCXY** [comment]
> 应该是买到假货了，现外贸盒子x96-mini、tx3-mini 之类的名字一样，但是芯片不一样，还遇到闲鱼上s905w的打磨芯片，用s905l2-b的，你需要多试几个固件。一是拆机，二是去阿里巴巴转转，搜x96-mini ，会有不同的芯片

拆过了，芯片是s905w的没有打磨痕迹啊

**Comment by BPG-WLCXY** [comment]
> 应该是买到假货了，现外贸盒子x96-mini、tx3-mini 之类的名字一样，但是芯片不一样，还遇到闲鱼上s905w的打磨芯片，用s905l2-b的，你需要多试几个固件。一是拆机，二是去阿里巴巴转转，搜x96-mini ，会有不同的芯片

![Uploading 微信图片_20240823202426.jpg…]()

**Comment by BPG-WLCXY** [comment]
> release

release在哪里啊

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by BPG-WLCXY** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases
这些固件能不能安装到VMware

**Comment by BPG-WLCXY** [comment]
或者是这个固件对应的是那个版本的nbuntu
