### ISSUE TITLE
请问这个可以直接刷 到章鱼星球吗，可以写到U盘直接启动，后写入EMMC吗

### ISSUE THREAD

**Issue by lanyucomputer** [ophub/amlogic-s9xxx-armbian#249]
请问这个可以直接刷 到章鱼星球吗，可以写到U盘直接启动，后写入EMMC吗？

**Comment by ophub** [comment]
使用方法和OpenWrt相同

**Comment by lanyucomputer** [comment]
要先刷CE改BOOTLOADER吗，麻烦可以上一下链接吗，我看到有的文章说只有安卓可以写入EMMC，还有这个是最新版的armbian吗，我看到这里说要插上U盘才可以启动运行，不能拔掉，是这样的吗，谢谢

**Comment by lanyucomputer** [comment]
http://www.wdmomo.fun:81/doc/web/#/22

**Comment by lanyucomputer** [comment]
能直接写入emmc的系统只有安卓系统，其他linux请勿直接写入

**Comment by ophub** [comment]
我看网上说：
原版是可以U盘启动的，U盘启动失败进入原版系统，是因为按RESET的时间太长了。
插上刷好armbian的U盘--顶住RESET--接上电源--2,3秒后松开RESET--进入U盘OP系统
如果接上电源后按RESET的时间太久，则会进入原版系统初始化界面。

我没这个设备，你试试 https://www.right.com.cn/forum/thread-7386143-1-1.html

**Comment by lanyucomputer** [comment]
插上刷好armbian的U盘--顶住RESET--接上电源--2,3秒后松开RESET--进入U盘OP系统
这个不是插的ARMBIAN系统 的U盘吗，怎么最后进入的是OP系统？？OP系统是指OPENWRT吗？
我买的还在路上，现在做的前期准备，我的想法是刷 一个ARMBIAN,然后其它用DOCKER就可以实现功能了，我现在用的是玩客云刷armbian，用得也挺好的，看到这个配置高一点，也不贵就搞一下折腾一下，论坛的贴子只要关键字是章鱼星球的我都读过了，呵呵

**Comment by ophub** [comment]
你看的帖子写的是op，你把op字样都换成armbian就对了。
op是OpenWrt的简称

**Comment by lanyucomputer** [comment]
https://www.right.com.cn/FORUM/thread-7806483-1-1.html他用的是你的，他说：“另外提醒一下，5.10内核版本的运行时不能拔出优盘，不然启动不了，所以我插了一个SD卡。”，所以我就来问了，我到货了自己来折腾吧，谢谢你耐心的回复

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

这个章鱼星球就是你上面帖子里的精简版安卓TV系统，刷入这个可以usb启动

**Comment by lanyucomputer** [comment]
好的，谢谢
