### ISSUE TITLE
请教能刷机，不能识别USB口的问题

### ISSUE THREAD

**Issue by SycamoreKing** [ophub/amlogic-s9xxx-armbian#2492]
**Device Information | 设备信息**
 - SOC: [e.g. S905L3A]
 - Model [e.g. CM311-1a CH]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.43]
 - Release: [e.g. jammy/bullseye]

**Describe the bug | 问题描述**
手上又得到2个CM311-1a CH 的盒子，第一个完美刷Android9，然后U盘启动刷O大的Armbian，
但是第二个同样的盒子，CM311-1a CH，能短接刷Android9，启动完之后，不能识别USB盘？这是什么毛病？启动SD、USB启动，也不能跑Armbian的代码。但是这个盒子能刷机哦？
请问o大，有没有短接HDMI刷机的方法刷Armbian？

**Comment by ophub** [comment]
在安卓下插入usb能识别吗？
HDMI短接有个amlogic神器，在某多见过，我没用过

**Comment by SycamoreKing** [comment]
> 在安卓下插入usb能识别吗？ HDMI短接有个amlogic神器，在某多见过，我没用过

感谢O大快速解答，找到问题了。5V烧了。加了5V，翻车扶正了。
