### ISSUE TITLE
总结一下几种机顶盒刷完后可用内存大小，大家对比一下

### ISSUE THREAD

**Issue by qfnuzlr** [ophub/amlogic-s9xxx-armbian#2496]
1、天邑TY1608，S905L3-b可刷  tf卡槽可用      804M
2、中兴B60AV2.1-M S905L3-b可刷，tf卡槽不可用，疑似主板上缺少元件   803M
3、创维E900-S可刷ubuntu，tf卡槽不可用   674M
替代另一种mdmo1b的fastboot后卡槽可用，内存从674变成422M

4、中兴B63AV3.2-M S905L3A可刷   2G
5、MGV2000  JL代工，S905L3-b可刷    723M
6、玩客云S805可刷，SD卡槽可用     988M
7、中兴B60AV2.1 S905L，可刷，tf卡槽可用  723M

安卓下显示1G，刷完armbian显示内存均小于安卓。疑问，减少的内存哪里去了？另一种可能安卓下显示不准确，比如E900-S安卓下显示1G，其实bootargs中显示是768M，其他型号的机顶盒是不是也是这样呢？不得而知，大佬指点迷津解疑答惑

**Comment by qinghon** [comment]
不同cpu devicetree 里保留内存大小与内核驱动使用内存大小均有差异，比如GPU 部分是占内存大户
