### ISSUE TITLE
天津联通机顶盒 中兴ZXV10 B860AV2.1 U 成功刷入

### ISSUE THREAD

**Issue by DavidTsou** [ophub/amlogic-s9xxx-armbian#2499]
**Device Information | 设备信息**
 - SOC: [ S905L ]
 - Model [ 中兴ZXV10 B860AV2.1 U 天津联通 ]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [noble/ jammy/bullseye]

**Describe the bug | 问题描述**
      中兴ZXV10 B860AV2.1 U 天津联通 1G+8G 

     机器使用QQ群Sicha思咖大佬的atv9历史固件，新固件因为有第一次启动屏幕变色问题暂未尝试。

安卓底包地址： https://www.123pan.com/s/1Ml8Vv-QipK.html 提取码：`5555`

![image](https://github.com/user-attachments/assets/9d604153-f23b-4f73-885e-7171d0cc303b)

默认使用最新的S905L镜像包，dtb改为meson-gxl-s905l2-x7-5g.dtb ，u-boot使用哪个未知 。 因我手里的这个盒子的字库上写着nand，应该是nand内存吧，所以无法写入emmc。

为什么使用noble版本的，在系统关于里能识别到显卡，jammy和bullseye都显示unknown  ，这对于使用上面来说有什么影响吗 ，尤其是用jellyfin转码的时候。

![image](https://github.com/user-attachments/assets/7f808f5d-a06b-4694-aa59-65a39b95f704)

下面是盒子的主板信息：

![image](https://github.com/user-attachments/assets/d65733f5-9dc4-45b2-885d-65e5c7e0865d)

![image](https://github.com/user-attachments/assets/8b2c4e3c-3c04-4532-b530-8aba2546bbad)

![image](https://github.com/user-attachments/assets/ad32ddba-2e19-4280-b8d6-3e41d7f16cb5)

![image](https://github.com/user-attachments/assets/1ff13f14-dd1d-4f80-87f3-28c7fe15acbb)

**Comment by ophub** [comment]
感谢分享。你把/boot/uEnv.txt里的dtb的名字改成这个试试：`meson-gxl-s905l3b-m302a.dtb`

**Comment by DavidTsou** [comment]
> 感谢分享。你把/boot/uEnv.txt里的dtb的名字改成这个试试：`meson-gxl-s905l3b-m302a.dtb`

如果我没记错的话，镜像默认使用的就是这个dtb，经过测试 上电后一直卡logo，无法启动。然后更换为meson-gxl-s905l2-x7-5g.dtb可以启动。
但是不知道是dtb不太适配还是noble版本 还是盒子的原因，系统进入后system load 经常爆表。

**Comment by ophub** [comment]
如果不稳定就继续换其他相近的测试，在model里有，周边的soc也可以测试

**Comment by DavidTsou** [comment]
> 如果不稳定就继续换其他相近的测试，在model里有，周边的soc也可以测试

hi ，经过几天测试，dtb更改为meson-gxl-s905x-tx9.dtb后， 使用6.1.107内核， 使用流畅，未发现什么其他问题，可以增加到设备支持列表里了 ，谢谢。

**Comment by ophub** [comment]
好的，感谢你分享，我下午添加到支持列表里。

**Comment by ophub** [comment]
你分享的安卓下载地址，输入5555验证码登录不进去，你试试。

**Comment by DavidTsou** [comment]
> 你分享的安卓下载地址，输入5555验证码登录不进去，你试试。

抱歉，我贴错地址了，重新edit了一下，现在可以了。

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

你分享的安卓系统转存到这里了。

**Comment by wunanxu** [comment]
有没有什么u盘/tf卡启动的方案

**Comment by DavidTsou** [comment]
> 有没有什么u盘/tf卡启动的方案

卡7%除了包不对，还一种可能，断开设备链接，断电短接，重新上电刷机，有可能能刷入

**Comment by xingzixia5201314** [comment]
哪个时中兴ZXV10 B860AV2.1 U 的op固件
