### ISSUE TITLE
大佬你好，我的电视盒子使用Armbian_21.11.0_Aml_s905x_buster_5.4.159_2021.11.15.1341.img.gz

### ISSUE THREAD

**Issue by yonggedebaqi** [ophub/amlogic-s9xxx-armbian#25]
不知道用那个dtb文件引导启动。
![微信图片_s905l2a](https://user-images.githubusercontent.com/43800614/141990403-321cca52-1627-419e-a1da-69df39f0524e.jpg)
![微信图片_s905l2b](https://user-images.githubusercontent.com/43800614/141990412-f85988e0-e468-4977-8fb0-631ab07a3a48.jpg)
![微信图片_s905lbc](https://user-images.githubusercontent.com/43800614/141990419-fa2acbce-be2d-44d7-bd38-78d039abff56.jpg)
我用Armbian_5.77_Aml-s905_Debian_stretch_default_5.0.2_20190401.img 
212dtb文件可以启动，新版本用212dtb文件就是不行。不知道哪里出了问题。

**Comment by yonggedebaqi** [comment]
WIFI MT7668芯片

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_buster_2021.11.15.1347/Armbian_21.11.0_Aml_s905x_buster_5.4.159_2021.11.15.1341.img.gz

Try this, what is the name of your box? What is soc?

**Comment by yonggedebaqi** [comment]
SKYWORTH E900V21C

**Comment by ophub** [comment]
Armbian_21.11.0_Aml_s905x_buster_5.4.159_2021.11.15.1341.img.gz
meson-gxl-s905x-p212.dtb
It is recommended to use in usb/tf.
