### ISSUE TITLE
How can I use desktop ?

### ISSUE THREAD

**Issue by tineprogramming** [ophub/amlogic-s9xxx-armbian#250]
When I install desktop on X96 Max plus with armbian-config it killed and I can't install manually.

**Comment by ophub** [comment]
I have installed the desktop on s92xxx-gtk-pro and s905x3-tx3. I have not tested it on other systems. The usage is the same, you can try again.

**Comment by tineprogramming** [comment]
Can you guide me how did you do it ? armbian-config -> system -> Default ? And enable it by system -> enable ?

**Comment by ophub** [comment]
I can't remember the path, you click below one by one, there is an option to install the desktop
