### ISSUE TITLE
原始虚拟内存文件在哪里呀，那部分空间能否利用起来

### ISSUE THREAD

**Issue by Vector-Cross** [ophub/amlogic-s9xxx-armbian#2500]
### Summary
根据readme描述，armbian-install后会默认分配内存的一半，做swap虚拟内存使用。而在使用armbian-swap会在/mnt/.swap/目录下添加swapfile重新分配虚拟内存。现在问题是原来的内存文件在哪里，那部分空间能否利用起来

### Details
由于个人需要，用3台盒子搭了一个kafka集群，为了提高实时性，就释放掉了原始的swap空间，但是没发现磁盘容量变大，就好奇原来的swapfile存在哪里。通过du -h --max-depth=1 / 一直搜都没发现800M的文件，请问原来是挂载在/dev/shm目录吗，为啥使用armbian-swap又挂载在根目录了呀
![image](https://github.com/user-attachments/assets/afd72514-b8de-423a-aed7-37e344e52c7f)

**Comment by ophub** [comment]
swap和tmpfs不是一回事。

swap是磁盘上的一个分区，可以手动配置大小。当物理内存不足时，操作系统会将一部分不常用的数据从内存中交换到磁盘上的一个特殊分区，这个分区就是swap分区。这样可以释放出物理内存，让给更需要内存的进程。

tmpfs是内存中的一个文件系统。是一个完全驻留在内存中的文件系统。它提供了一个快速、高效的存储空间，通常用于存放临时文件，例如浏览器缓存、编译器中间文件等。数据在系统重启或卸载时会丢失。

**Comment by Vector-Cross** [comment]
那我在armbian-swap后怎么才能回到默认配置呢，好像调整不回去了

**Comment by Vector-Cross** [comment]
直接删除后没用，swap回不到原来默认的百分之50。
查了一下官网的内容 **https://docs.armbian.com/User-Guide_Fine-Tuning/#swap-for-experts**
![image](https://github.com/user-attachments/assets/e290b3bb-9574-4294-81a1-0c49015037e8)
然后修改这个配置文件把swap=false注释掉再重启就好了
![image](https://github.com/user-attachments/assets/14a3cfe8-fc11-4f2f-a9a2-248cea298150)

**Comment by ophub** [comment]
好的👌
