### ISSUE TITLE
基于ubuntu 20.04 focal的Armbian版本还能下载吗？

### ISSUE THREAD

**Issue by zs-lisi** [ophub/amlogic-s9xxx-armbian#2501]
**Device Information | 设备信息**
 - SOC: S095l3a]
 - Model [CM311-1a-YST]

我现在需要用CM311-1a-YST的盒子运行ROS NOETIC，但是jammy版本的系统不兼容，需要focal版本。
我记得以前有基于ubuntu 20.04 focal的Armbian版本，现在还能下载吗？在哪里可以下载，如果没有的话，如何自行编译？有高人，大神可以给我指点一条明路，谢谢！

**Comment by Vector-Cross** [comment]
不太懂，但是你可以在这里 **https://github.com/armbian/build/tree/v20.05** 看看

**Comment by qfnuzlr** [comment]
ubuntu 20.04 ? 海思3798mv100 200 300 安装的海纳思就是这系统吧
