### ISSUE TITLE
how the right way to compile kernel and add driver

### ISSUE THREAD

**Issue by tjengbudi** [ophub/amlogic-s9xxx-armbian#2503]
hello,
i trying to compile kernel, the kernel i compile is 6.1 version
i added some wifi driver, rtl8188fu and rtl8189fs
i add it in the config and compile, and it not found in the compiled kernel.

i might got wrong. can i know how to compile kernel and add the driver?

i found some post issue but looks like it different with your newest doc, in the github doc you call ./recompile

**Comment by ophub** [comment]
The driver not included in the kernel needs to be found online, which is compatible with the current driver. Search online for the method to add the driver.

https://github.com/unifreq
