### ISSUE TITLE
使用aria2下载时，总出现tcp:out of memory -- consider tuning tcp_mem

### ISSUE THREAD

**Issue by DavidTsou** [ophub/amlogic-s9xxx-armbian#2504]
**Device Information | 设备信息**
 - SOC: [S905L]
 - Model [B860 AV2.1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [bullseye]

**Describe the bug | 问题描述**

当使用 aria2 发送rpc下载的时候，显示器经常提示 tcp 内存溢出  ，请问一下这个是什么原因 ，有什么方式可以避免

![image](https://github.com/user-attachments/assets/46299a94-206a-42fe-97f0-6fb5b2a5a9f0)

**Comment by ophub** [comment]
"tcp: out of memory -- consider tuning tcp_mem"这个错误信息表示系统已经耗尽了为TCP连接分配的内存。这可能发生在系统处理大量TCP连接时，或者分配给TCP的内存不足时。

要解决这个问题，您可以考虑调整Linux内核中的tcp_mem参数。该参数控制为TCP缓冲区分配的内存量。您可以调整tcp_mem的值以更好地适应系统的需求。

要调整tcp_mem参数，您可以修改/proc/sys/net/ipv4/tcp_mem文件中的值。tcp_mem参数包括三个值：低阈值、压力阈值和高阈值。您可以根据系统的需求调整这些值。

以下是一个修改tcp_mem参数的示例：
`echo "4096 87380 6291456" > /proc/sys/net/ipv4/tcp_mem`


在更改tcp_mem值后，您可以监视系统，查看是否持续出现"tcp: out of memory"错误。根据需要调整这些值，以优化TCP内存使用并在使用aria2下载时避免出现错误。
