### ISSUE TITLE
第一项这个是什么？根文件系统吗

### ISSUE THREAD

**Issue by Loushihao** [ophub/amlogic-s9xxx-armbian#2506]
![image](https://github.com/user-attachments/assets/aafd5a73-df70-459f-b099-582ac0c51e91)
我用RK3588的平台打包烧录后发现能进系统 显示的是debian  用户名密码不对 登不上
![image](https://github.com/user-attachments/assets/ac16b52b-ede9-47f5-9ead-8646f1e66101)

**Comment by ophub** [comment]
用户名：root
密码：1234

**Comment by Loushihao** [comment]
我看了 不对

**Comment by Loushihao** [comment]
> 用户名：root 密码：1234

试过了 不对一直都按得这个

**Comment by Loushihao** [comment]
大神有没有办法用armbian根文件系统+rk的sdk内核方式，不用armbian compile方式弄armbia系统啊

**Comment by Xianleewu** [comment]
> 大神有没有办法用armbian根文件系统+rk的sdk内核方式，不用armbian compile方式弄armbia系统啊

直接把armbian的文件系统(ext4)写到rk的rootfs分区就可以了
