### ISSUE TITLE
X96 mini 1G 8G 100m WIFI wifi没有显示

### ISSUE THREAD

**Issue by lx7741** [ophub/amlogic-s9xxx-armbian#251]
使用Armbian_22.05.0_Aml_s905w_focal_5.15.34_2022.04.19.0022 .img，U盘可以正常启动，无法刷入emmc
U盘启动后没有wifi模块。
执行armbian-install显示no emmc。（替换网上dtb（meson-gxl-s905w-p281.dtb后可以刷入emmc））
网上DTB如下：
[meson-gxl-s905w-p281.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8526707/meson-gxl-s905w-p281.zip)
x96 mini不支持5.4内核了吗 ？
WIFI模块可以支持吗？

**Comment by ophub** [comment]
脚本判断是否有emmc和dtb无关，换不换dtb和是否支持写入emmc无关。
[meson-gxl-s905w-p281.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/bootfs/dtb/amlogic/meson-gxl-s905w-p281.dtb) 这个文件在固件里自带了。
你wifi什么芯片，5.4拟放弃了。

**Comment by lx7741** [comment]
> 脚本判断是否有emmc和dtb无关，换不换dtb和是否支持写入emmc无关。 [meson-gxl-s905w-p281.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/bootfs/dtb/amlogic/meson-gxl-s905w-p281.dtb) 这个文件在固件里自带了。 你wifi什么芯片，5.4拟放弃了。
这个文件在估计里面有自带，但是自带那个找不到emmc，网上有人改了里面内容后找到emmc
地址：https://forum.armbian.com/topic/15665-new-x96mini-hardware-upgraded-but-no-emmc-found/
wifi芯片应该是6051。

**Comment by ophub** [comment]
发一下你的安装日志
芯片在主板上看，不能猜，同名盒子但不同芯片版本的很多

**Comment by lx7741** [comment]
armbian-install 安装日志：
Start install armbian to emmc...
No emmc can be found to install the openwrt system!
这样子。
这盒子没有螺丝不好拆开，等下我暴力拆开看看。。。

**Comment by ophub** [comment]
`lsblk -l -o NAME`
你执行上面的命令看看有没有`mmcblk2boot0`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/76d66bbac786b1ce7357a5df859e3748033f614c/build-armbian/common-files/rootfs/usr/sbin/armbian-install#L39

**Comment by lx7741** [comment]
> `lsblk -l -o NAME` 你执行上面的命令看看有没有`mmcblk2boot0`
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/76d66bbac786b1ce7357a5df859e3748033f614c/build-armbian/common-files/rootfs/usr/sbin/armbian-install#L39
root@armbian:~# lsblk -l -o NAME
NAME
sda
sda1
sda2
zram0
zram1
zram2
用原来的dtb只会显示这几个，没有mmcblk2boot0

**Comment by ophub** [comment]
脚本是通过找boot0来识别emmc的名称。你的盒子是第一个发现不了emmc的设备。

**Comment by lx7741** [comment]
> 脚本是通过找boot0来识别emmc的名称。你的盒子是第一个发现不了emmc的设备。
对的，但是换了网址的dtb就可以找到emmc了，所以应该是dtb有点问题。
wifi芯片是SSV6051P，这个芯片听说不支持高版本内核？

**Comment by ophub** [comment]
![Snip20220421_1](https://user-images.githubusercontent.com/68696949/164364997-ad20aa45-5f33-496e-9fa3-707f022520c8.png)


ls /usr/lib/firmware/ssv6051* -l

**Comment by lx7741** [comment]
> ![Snip20220421_1](https://user-images.githubusercontent.com/68696949/164364997-ad20aa45-5f33-496e-9fa3-707f022520c8.png)
> 
> ls /usr/lib/firmware/ssv6051* -l

root@armbian:~# ls /usr/lib/firmware/ssv6051* -l
-rw-r--r-- 1 root root 81176 Apr 19 00:23 /usr/lib/firmware/ssv6051-sw.bin
-rw-r--r-- 1 root root  2494 Apr 19 00:23 /usr/lib/firmware/ssv6051-wifi.cfg
这个有显示

**Comment by ophub** [comment]
https://forum.armbian.com/topic/12656-csc-armbian-for-rk322x-tv-boxes/page/6/

**Comment by ophub** [comment]
驱动是有，但是dtb里是否启用了就得看你指定的dtb的代码了

**Comment by lx7741** [comment]
> 驱动是有，但是dtb里是否启用了就得看你指定的dtb的代码了

那还是要修改dtb代码了？等下去研究下dts看看，这个wifi芯片有点旧了

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/arch/arm64/boot/dts/amlogic

我使用的是unifreq（民间多以他的另外一个名称flippy大佬称呼他）维护的内核库。你可以直接在dts上修改并编译测试，生成一个单独名称的dtb文件。比如叫`meson-gxl-s905w-x96-mini-xxx.dtb`

**Comment by lx7741** [comment]
> https://github.com/unifreq/linux-5.15.y/tree/main/arch/arm64/boot/dts/amlogic
> 
> 我使用的是unifreq（民间多以他的另外一个名称flippy大佬称呼他）维护的内核库。你可以直接在dts上修改并编译测试，生成一个单独名称的dtb文件。比如叫`meson-gxl-s905w-x96-mini-xxx.dtb`

好的，我试试他的dts文件看看，谢谢！

**Comment by ophub** [comment]
5.15的内核打了textoffset补丁，用法同5.4内核。你先在这个系列上测试吧。

**Comment by lx7741** [comment]
> 5.15的内核打了textoffset补丁，用法同5.4内核。你先在这个系列上测试吧。

好的，我试试看能不能启动wifi。

**Comment by ophub** [comment]
你下载的dtb文件识别有线的百兆正常？这个dtb原来是5.9内核的文件？

**Comment by lx7741** [comment]
> 你下载的dtb文件识别有线的百兆正常？这个dtb原来是5.9内核的文件？

我下载的这个dtb文件，百兆网络正常，可以正常刷入emmc，可以启动5.15内核，这个dtb文件是
https://forum.armbian.com/topic/15665-new-x96mini-hardware-upgraded-but-no-emmc-found/
这个网址下载的，他改了里面查找emmc的地址？
目前这个dtb就是wifi也是用不了

**Comment by ophub** [comment]
好的

**Comment by lx7741** [comment]
查找了一堆资料。
使用了ssv6051的驱动补丁
https://github.com/armbian/build/commit/f3388b9aee0d1564a28fbc661c6e7b0415a6dfd0
将补丁放在f大的5.15内核可以编译通过，但是ssv6051加载不起来。
错误跟
https://forum.libreelec.tv/thread/25151-mecool-m8s-pro-w/
这个网址的人一样。无解了
这个问题应该跟
https://github.com/ophub/amlogic-s9xxx-armbian/issues/208是同一个问题
