### ISSUE TITLE
Ali CT2000 安装Armbian_24.8.0_amlogic_s922x-ct2000_noble_6.6.46_server后内存仅有3.18G

### ISSUE THREAD

**Issue by IhaveAyellowDog** [ophub/amlogic-s9xxx-armbian#2511]
**Device Information | 设备信息**
 - SOC: [S922X]
 - Model [Ali CT2000]

**Armbian Version | 系统版本**
 - Kernel Version: [Linux armbian 6.6.46-ophub]
 - Release: [Armbian_24.8.0_amlogic_s922x-ct2000_noble_6.6.46_server]

**Describe the bug | 问题描述**
板子上4G内存，安装完毕后，仅有3.18G

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
![image](https://github.com/user-attachments/assets/07326727-8b9b-4e51-80f7-b818bd09ddd5)

**Comment by ophub** [comment]
这个设备锁bootloader，不能定制开发专用u-boot，在USB复制u-boot.ext使用可以识别全内存，写入emmc只能3.18g
