### ISSUE TITLE
CM311-1a YST 不识别读卡器，报错

### ISSUE THREAD

**Issue by qfnuzlr** [ophub/amlogic-s9xxx-armbian#2512]
**Device Information | 设备信息**
 - SOC: [e.g. S905L3A]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
Armbian_24.8.0_amlogic_s905l3a_bullseye_6.1.105_server_2024.08.17
 
插tf读卡器，报错如下
root@armbian:~# [  419.051499] usb 1-2: new high-speed USB device number 11 using xhci-hcd
[  424.419574] usb 1-2: device descriptor read/all, error -110
[  424.551502] usb 1-2: new high-speed USB device number 12 using xhci-hcd
[  429.799576] usb 1-2: device descriptor read/all, error -110
[  429.801810] usb usb1-port2: attempt power cycle
[  430.223503] usb 1-2: new high-speed USB device number 13 using xhci-hcd
[  435.431577] usb 1-2: device descriptor read/8, error -110
不断循环跑码，插U盘正常识别。读卡器+tf卡报错，不识别

**Comment by qfnuzlr** [comment]
可能是缺少驱动，换了个读卡器正常读取识别
那么怎么安装驱动呢？

**Comment by ophub** [comment]
挑读卡器不是添驱动的问题，用能正确读取的卡

**Comment by qfnuzlr** [comment]
很奇怪啊  其他几款盒子都没问题 这个盒子配置高 反而报错了

**Comment by qfnuzlr** [comment]
换了读卡器正常读取了，识别为usb硬盘，而不是mmcblk
