### ISSUE TITLE
九联 UNT402A 无法从USB启动 装Armbian，只进入到了Recovery界面

### ISSUE THREAD

**Issue by yanghong265** [ophub/amlogic-s9xxx-armbian#2513]
**Device Information | 设备信息**
 - SOC: [S905L3]
 - Model [九联UNT402A，emmc，无Wifi]

**Armbian Version | 系统版本**
 - Kernel Version: -这里不太懂
 - Release：Armbian_24.8.0_amlogic_s905l3b_bookworm_6.6.43_server_2024.08.01.img.gz，
                   也试了Armbian_24.8.0_amlogic_s905l3_jammy_6.6.43_server_2024.08.01.img，同样无法USB启动

**Describe the bug | 问题描述**
- 安卓底包是从O大Tools下载的 [android_tv_unt402a_s905l3.tar.gz]；之前也试过其他的安卓底包
- 试过了使用balenaEtcher、Rufus_V4.5 软件制作U盘Armbian系统（尝试了3款U盘 ）
- 使用的开心电视助手 工具 从U盘启动，只是进入到了安卓系统的Recovery 界面
- 以上尝试后，均不能从U盘正常进入Armbian系统，只是进入到了安卓Recovery 界面

请教下我的这个是什么问题

![UNT402A 背面](https://github.com/user-attachments/assets/b3f982b4-eb1c-4816-bac5-32030d1dc057)
![UNT402A 盒子正面](https://github.com/user-attachments/assets/6f7f5fe4-34bd-4b75-80d4-03b28760189a)
![UNT402A 正面](https://github.com/user-attachments/assets/f442b02f-2d9e-4020-a148-c2004c705f58)
![开心电视截图](https://github.com/user-attachments/assets/e351e313-d4ce-4015-b59a-9d36ffccbddb)

**Comment by ophub** [comment]
从usb启动的方法在仓库的文档里

**Comment by yanghong265** [comment]
> 从usb启动的方法在仓库的文档里
感谢O大抽空回复。
文档USB启动的方是如下方法吗？   我试了，还是一样的直接进入了Recovery系统
![1234](https://github.com/user-attachments/assets/f9d769ff-ea04-4b09-bdc3-9b8870dc6044)

**Comment by ophub** [comment]
换个U盘试试，闪迪的通用性好

**Comment by tinytinycn** [comment]
[应该或许能帮到你](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2347#issuecomment-2320241987)

**Comment by qfnuzlr** [comment]
亲测其他盒子可行：
ttl，开机中断进入uboot
输入 run update 回车
自动重启引导U盘系统

也遇到几款盒子，用卡刷apk切换或助手切换都无法U盘引导，上法成功，测试一下吧

**Comment by yanghong265** [comment]
> 亲测其他盒子可行： ttl，开机中断进入uboot 输入 run update 回车 自动重启引导U盘系统
> 
> 也遇到几款盒子，用卡刷apk切换或助手切换都无法U盘引导，上法成功，测试一下吧

大佬能详细说明下TTL 的方法吗？

**Comment by yanghong265** [comment]
> 亲测其他盒子可行： ttl，开机中断进入uboot 输入 run update 回车 自动重启引导U盘系统
> 
> 也遇到几款盒子，用卡刷apk切换或助手切换都无法U盘引导，上法成功，测试一下吧

你好，已经通过TTL 跑码了，接下来怎么操作进入中断UBOOT呢？尝试命令RUN UPDATE 提示找不到
![112](https://github.com/user-attachments/assets/796b19b4-f66d-442c-95bf-84919a677969)

**Comment by yanghong265** [comment]
跑码过程中，按Ctrl +Z 进入另外一个命令模式，输入Run update 后，还是进入的Recovery 界面（插着U盘）
。。。已经崩溃了。
![322](https://github.com/user-attachments/assets/c3b59d8e-e4d3-49fa-b8bc-f91679a406f9)
