### ISSUE TITLE
CM211-1安装时的联网问题

### ISSUE THREAD

**Issue by HRJJACK1145** [ophub/amlogic-s9xxx-armbian#2514]
**Device Information | 设备信息**
 - SOC: Amlogic S905l3
 - Model 魔百和CM211-1
 - 代工厂:应该是CH
 - 主板型号:MC016

**Armbian Version | 系统版本**
 - Kernel Version: 最新版
 - Release: 最新版

**Describe the bug | 问题描述**
问题不是很大，就是如果在安装的时候不写启用主线Uboot选项的参数（命令:armband-install)的话就会导致无法联网，网线插入会有TTL输出，但是无法使用网络，无法ping通路由器和任何外网，都会提示Network Unreachable，并且重刷o大提供的安卓系统也没用，问题照旧，启用主线Uboot后才能正常使用，希望o大能考虑一下把这个写进教程里（当时我搞了一个下午非常崩溃）

**Comment by ophub** [comment]
把盒子的正反两面的照片拍一下

**Comment by ophub** [comment]
感谢分享
