### ISSUE TITLE
求助：盒子型号MGV2000，芯片s905l3b，没有WiFi，不识别无线网卡

### ISSUE THREAD

**Issue by a787035097** [ophub/amlogic-s9xxx-armbian#2517]
盒子型号MGV2000，芯片s905l3b，安卓底包刷的烽火，烧录U盘，U盘启动，写入emmc，以上均成功。唯一一点没有wifi，板子上有WiFi芯片（mt7668rsn），不知道为啥不识别无线网卡，是armbian的版本不匹配吗？请大佬明示！
![无标题](https://github.com/user-attachments/assets/3ce76132-2c7f-43c7-9684-88b1ccb0cdb7)

**Comment by w2xg2022** [comment]
@a787035097 可参考：https://github.com/ophub/amlogic-s9xxx-armbian/issues/2616

**Comment by a787035097** [comment]
> @a787035097 可参考：#2616

谢谢大佬，非常感谢！
