### ISSUE TITLE
5.15.35 和5.10.112哪个版本高？

### ISSUE THREAD

**Issue by lanyucomputer** [ophub/amlogic-s9xxx-armbian#252]
5.15.35 和5.10.112哪个版本高？[Armbian_22.05.0_Aml_s912_focal_5.15.35_2022.04.21.0021.img.gz和[Armbian_22.05.0_Aml_s912_focal_5.10.112_2022.04.21.0024.img.gz

**Comment by lanyucomputer** [comment]
Linux Kernel 5.10 将是长期支持版本
主要稳定内核维护者 Greg Kroah-Hartman 在 Linux 基金会欧洲开源峰会的 “Ask the Expert” 环节上发言，确认 Linux 5.10 将是下一个 LTS 版本。

**Comment by lanyucomputer** [comment]
随着我们接近日历年的结束，还有一些不确定因素，即Linux 5.15是否会成为今年的长期支持（LTS）内核，或者是否会是Linux 5.16，尽管它可能要到2022年初才会发布......现在Greg Kroah-Hartman已经决定将Linux 5.15确定为2021年的LTS内核。

确定吗？？

**Comment by ophub** [comment]
从5.5—5.10—5.15—5.16这么演变来的。kernel.org官网可以解惑。
