### ISSUE TITLE
A311D 4+8 SATA桥接芯片（asm1064）不正常，ahci报错内核6.6.48

### ISSUE THREAD

**Issue by hahha52468** [ophub/amlogic-s9xxx-armbian#2524]
**Device Information | 设备信息**
 - SOC: [e.g. A311D]
 - Model [e.g. OES]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.6.48]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
内核初始化过程中，ahci驱动报错，pcie可以识别到桥接芯片，ls-vvv显示如下：
PCI bridge: Synopsys, Inc. DWC_usb3 / PCIe bridge (rev 01) (prog-if 00 [Normal decode])
        Flags: bus master, fast devsel, latency 0, IRQ 26
        Bus: primary=00, secondary=01, subordinate=ff, sec-latency=0
        I/O behind bridge: [disabled] [16-bit]
        Memory behind bridge: [disabled] [32-bit]
        Prefetchable memory behind bridge: [disabled] [32-bit]
        Expansion ROM at fc700000 [virtual] [disabled] [size=64K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [70] Express Root Port (Slot-), MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [148] L1 PM Substates
        Kernel driver in use: pcieport

内核启动dmesg：如下

[    3.898930] dw-pcie fc000000.pcie: error -ENXIO: IRQ index 1 not found
[    3.901918] meson-pcie fc000000.pcie: host bridge /soc/pcie@fc000000 ranges:
[    3.906824] meson-pcie fc000000.pcie:       IO 0x00fc600000..0x00fc6fffff -> 0x0000000000
[    3.915216] meson-pcie fc000000.pcie:      MEM 0x00fc700000..0x00fdffffff -> 0x00fc700000
[    3.923163] meson-pcie fc000000.pcie: iATU unroll: enabled
[    3.928469] meson-pcie fc000000.pcie: iATU regions: 4 ob, 4 ib, align 64K, limit 4G
[    3.977446] meson-pcie fc000000.pcie: error: wait linkup timeout
[    3.979140] meson-pcie fc000000.pcie: PCIe Gen.2 x1 link up
[    3.984050] meson-pcie fc000000.pcie: PCI host bridge to bus 0000:00
[    3.989629] pci_bus 0000:00: root bus resource [bus 00-ff]
[    3.995774] pci_bus 0000:00: root bus resource [io  0x0000-0xfffff]
[    4.001270] pci_bus 0000:00: root bus resource [mem 0xfc700000-0xfdffffff]
[    4.008799] pci 0000:00:00.0: [16c3:abcd] type 01 class 0x060400
[    4.014042] pci 0000:00:00.0: reg 0x38: [mem 0x00000000-0x0000ffff pref]
[    4.021399] pci 0000:00:00.0: supports D1
[    4.024643] pci 0000:00:00.0: PME# supported from D0 D1 D3hot D3cold
[    4.032744] pci 0000:01:00.0: [1b21:1064] type 00 class 0x010601
[    4.774067] pci 0000:01:00.0: Max Payload Size set to 256 (was 128, max 256)
[    4.775462] pci 0000:01:00.0: enabling Extended Tags
[    4.823874] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    4.867735] pci 0000:01:00.0: 4.000 Gb/s available PCIe bandwidth, limited by 5.0 GT/s PCIe x1 link at 0000:00:00.0 (capable of 7.876 Gb/s with 8.0 GT/s PCIe x1 link)
[    4.932549] pci 0000:00:00.0: BAR 6: assigned [mem 0xfc700000-0xfc70ffff pref]
[    4.934114] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    4.939429] pcieport 0000:00:00.0: PME: Signaling with IRQ 21
[    4.988431] ahci: probe of 0000:01:00.0 failed with error -22

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。

**Comment by zhanghua12121** [comment]
SATA controller: ASMedia Technology Inc. Device 1064 (rev 02) (prog-if 01 [AHCI 1.0])
        Subsystem: ZyDAS Technology Corp. Device 2116

**Comment by hahha52468** [comment]
[full-debug.txt](https://github.com/user-attachments/files/16843008/full-debug.txt)
wanzheng完整的dmesg

**Comment by hahha52468** [comment]
root@armbian:~# dmesg|grep pci
[    5.673061] dw-pcie fc000000.pcie: error -ENXIO: IRQ index 1 not found
[    5.676156] meson-pcie fc000000.pcie: host bridge /soc/pcie@fc000000 ranges:
[    5.681014] meson-pcie fc000000.pcie:       IO 0x00fc600000..0x00fc6fffff -> 0x0000000000
[    5.689145] meson-pcie fc000000.pcie:      MEM 0x00fc700000..0x00fdffffff -> 0x00fc700000
[    5.697421] meson-pcie fc000000.pcie: iATU: unroll T, 4 ob, 4 ib, align 64K, limit 4G
[    5.746492] meson-pcie fc000000.pcie: error: wait linkup timeout
[    5.748185] meson-pcie fc000000.pcie: PCIe Gen.2 x1 link up
[    5.752685] meson-pcie fc000000.pcie: PCI host bridge to bus 0000:00
[    5.758735] pci_bus 0000:00: root bus resource [bus 00-ff]
[    5.764191] pci_bus 0000:00: root bus resource [io  0x0000-0xfffff]
[    5.770440] pci_bus 0000:00: root bus resource [mem 0xfc700000-0xfdffffff]
[    5.777313] pci 0000:00:00.0: [16c3:abcd] type 01 class 0x060400
[    5.783276] pci 0000:00:00.0: reg 0x38: [mem 0x00000000-0x0000ffff pref]
[    5.789966] pci 0000:00:00.0: supports D1
[    5.793918] pci 0000:00:00.0: PME# supported from D0 D1 D3hot D3cold
[    5.803852] pci 0000:01:00.0: [1b21:1064] type 00 class 0x010601
[    6.543434] pci 0000:01:00.0: Max Payload Size set to 256 (was 128, max 256)
[    6.544847] pci 0000:01:00.0: enabling Extended Tags
[    6.593288] pci 0000:01:00.0: PME# supported from D0 D3hot D3cold
[    6.637159] pci 0000:01:00.0: 4.000 Gb/s available PCIe bandwidth, limited by 5.0 GT/s PCIe x1 link at 0000:00:00.0 (capable of 7.876 Gb/s with 8.0 GT/s PCIe x1 link)
[    6.708289] pci 0000:00:00.0: BAR 6: assigned [mem 0xfc700000-0xfc70ffff pref]
[    6.718978] pci 0000:00:00.0: PCI bridge to [bus 01-ff]
[    6.719228] pcieport 0000:00:00.0: PME: Signaling with IRQ 22
root@armbian:~# dmesg|grep ahci
[    6.773756] ahci 0000:01:00.0: version 3.0
[    6.777935] ahci: probe of 0000:01:00.0 failed with error -22

**Comment by zed0325** [comment]
大佬能分享下安卓包  网上找的都刷不进去
