### ISSUE TITLE
EMMC安装了armbian，U盘刷了EmuELEC，如何修改引导文件让盒子支持有U盘时启动U盘内的EmuElEC?

### ISSUE THREAD

**Issue by LifeActor** [ophub/amlogic-s9xxx-armbian#2528]
**Device Information | 设备信息**
 - SOC: [S905L3a]
 - Model [M401A]

**Armbian Version | 系统版本**
 - Kernel Version: [6.11]
 - Release: [lastest]

**Describe the bug | 问题描述**
EMMC安装了armbian，U盘刷了EmuELEC，如何修改引导文件让盒子支持有U盘时启动U盘内的EmuElEC?
在将armbian安装进EMMC时，好像备份了安卓的Bootloader放在了U-boot目录下，从U盘启动好像是检测U盘内是否有晶晨的xml文件，然后从xml文件的配置开始加载引导程序，没开发过软硬件项目，老大，有没有修改方案支持有U盘时支持从U盘启动？
EMMC内有armbian时，如果U盘里也是armbian 它可以从U盘启动，我把U盘刷成EmuElEC后，就无法从U盘启动了，这两系统不都是用U-boot进行引导的嘛，为啥会不兼容？

**Comment by LifeActor** [comment]
修改Boot.cmd 能否达到这个目的？

**Comment by ophub** [comment]
这2个系统互斥，emmc里刷了EmuELEC，想刷armbian要先刷回安卓，反之也一样，他俩的启动互斥不兼容。

**Comment by LifeActor** [comment]
@ophub o大，是否可以在emmc的boot分区下的boot.cmd里，将u盘的u-boot镜像加载到0x0800000 然后转移控制权给u盘的u-boot从而启动u盘里的emuelec？

**Comment by ophub** [comment]
这2个系统不能互相启动对方
