### ISSUE TITLE
网络设置出错，已刷入闪存，插网线开机红灯。

### ISSUE THREAD

**Issue by qq664636016** [ophub/amlogic-s9xxx-armbian#2530]
因为想用usb外置wifi，就瞎捣鼓了下，结果重启就不能自动联网了，插网线也没用。这种情况怎么进入系统内部来修改网络这块，里面装了很多东西，不想重装，有没有人经历过。

**Comment by ophub** [comment]
usb启动armbian
`armbian-update -s`

**Comment by qq664636016** [comment]
是做个armbian的u盘，然后插u盘启动后不写入闪存，用ssh链接系统，在u盘里的armbian系统执行这些命令吗？

**Comment by qq664636016** [comment]
这会对闪存里的系统有没有影响？

**Comment by qq664636016** [comment]
> usb启动armbian `armbian-update -s`

感谢大佬解决了，请问我现在看最新版本只有680m，我现在用的是5.15.129的镜像2.75g，怎么相差这么大，有什么区别吗？我有没有必要升？

**Comment by qq664636016** [comment]
> usb启动armbian `armbian-update -s`

感谢大佬解决了，请问我现在看最新版本只有680m，我现在用的是5.15.129的镜像2.75g，怎么相差这么大，有什么区别吗？我有没有必要升？

**Comment by qq664636016** [comment]
> usb启动armbian `armbian-update -s``armbian 更新 -s`

大佬，请问外置wifi可以用吗。

**Comment by ophub** [comment]
> 是做个armbian的u盘，然后插u盘启动后不写入闪存，用ssh链接系统，在u盘里的armbian系统执行这些命令吗？


对，试试恢复内核及启动设置

**Comment by ophub** [comment]
> > usb启动armbian `armbian-update -s`
> 
> 感谢大佬解决了，请问我现在看最新版本只有680m，我现在用的是5.15.129的镜像2.75g，怎么相差这么大，有什么区别吗？我有没有必要升？



忧郁不决说明你不想升，跟着自己的感觉走，不用听别人的建议。

**Comment by qq664636016** [comment]
> > > usb启动armbian `armbian-update -s`usb启动`armbian armbian-update -s`
> > 
> > 
> > 感谢大佬解决了，请问我现在看最新版本只有680m，我现在用的是5.15.129的镜像2.75g，怎么相差这么大，有什么区别吗？我有没有必要升？
> 
> 忧郁不决说明你不想升，跟着自己的感觉走，不用听别人的建议。
> 
> 外置usb有线/无线网卡是否支持，取决于内核里是否有它的驱动： https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless

我这个是免驱的，盒子重启的时候会不会勿判为usb启动。
