### ISSUE TITLE
cm311-1A支持外置wifi吗？

### ISSUE THREAD

**Issue by qq664636016** [ophub/amlogic-s9xxx-armbian#2531]
s905l3a
内核版本:5.15.129-ophub

外置usbwifi是LB-LINK 802.11N

请问下这个装什么驱动，然后怎么设置有线优先wifi。

自己捣鼓了下装了RTL8188EUS芯片的驱动，能读取到适配器，但就是用不了。是不是驱动没装对，网上看是免驱动的。

或者说usb口开机优先读取是不是不能识别外置wifi

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless


内核支持的驱动
