### ISSUE TITLE
armbian-software命令遇到权限问题解决方案

### ISSUE THREAD

**Issue by LifeActor** [ophub/amlogic-s9xxx-armbian#2533]
刷有armbian的U盘插在盒子上，运行安卓系统后，文件权限会被批量修改，这个应该是导致armbian部分命令提示权限不足的主要原因。
但是这应该是不可避免的，reboot命令后运行的系统就回到了安卓，没及时按遥控器是的左键基本就加载安卓系统了。
其次，启动U盘里的armbian需要在安卓系统执行 adb reboot update，或者运行相关app一键重启。
中兴代工的魔百盒没有复位键(主板上的微动键)，短接也只进烧录模式，只能从安卓系统 reboot update，或者刷有root的包从app一键切换系统。
如果按这个issue的解决方案，那岂不是每次重启都要重新刷一次armbian？
https://github.com/ophub/amlogic-s9xxx-armbian/issues/2322#issue-2303822823

或者说第一次启动armbian也是要在安卓内执行adb命令的，那进了安卓系统就要重刷，刷了又要通过安卓系统重启进入，死循环了。这个怎么解？
目前临时使用chown命令重置了所有文件给root用户，可以肯定肯定很多服务并不是root启动的，这样的临时方案肯定有很多隐患。
o大，有完美解决方案吗？

**Comment by ophub** [comment]
adb时不用插，你执行了更新命令就可以U盘启动了，在重启时再插入。

**Comment by github-office** [comment]
各位老铁，x86版本的 armbian是不是没有armbian-software功能？
