### ISSUE TITLE
请求增加支持天猫智慧屏魔盒 主芯片是A311D 谢谢了

### ISSUE THREAD

**Issue by onionscode** [ophub/amlogic-s9xxx-armbian#2534]
**Device Information | 设备信息**
 - SOC: A311D
 -解包固件uboot和dtb如下
[解包uboot和dtb.zip](https://github.com/user-attachments/files/16915052/uboot.dtb.zip)

**Armbian Version | 系统版本**
无

**Describe the bug | 问题描述**
目前只有安卓版本的固件，通过ampack解包得到uboot和dtb，按帮助文档试了提取了acs.bin文件，但是想自己编译问题多多。
试过armbian的编译，卡刷固件都是报错，应该是acs.bin文件配置不对
dmc_version 0001
Check phy result
INFO : ERROR : Training has failed!
Check phy result
INFO : ERROR : Training has failed!
Check phy result
INFO : End of initialization
INFO : ERROR : Training has failed!
1D training failed
Cfg max: 12, cur: 5. Board id: 0. not match..skip..
Cfg max: 12, cur: 6. Board id: 0. not match..skip..
Cfg max: 12, cur: 7. Board id: 0. not match..skip..
Cfg max: 12, cur: 8. Board id: 0. not match..skip..
Cfg max: 12, cur: 9. Board id: 0. not match..skip..
Cfg max: 12, cur: 10. Board id: 0. not match..skip..
Cfg max: 12, cur: 11. Board id: 0. not match..skip..
Cfg max: 12, cur: 12. Board id: 0. not match..skip..
All ddr config failed...
Reset...
boot times 

Please provide a detailed description of the issue and, if necessary, attach a screenshot.
详细描述问题，并在必要时附上屏幕截图。
这个主板内存是4颗三星K4AG16 应该是1G的DDR4 一起4颗
EMMC是64G
但是有线是IP1001M，无线是AP6275SR3 网络这块还是很冷门的芯片，看IP1001M S905有同款芯片支持
![P20240828-213636](https://github.com/user-attachments/assets/b7e74b74-cd9d-47ec-8513-4138db302d93)
![P20240907-140202](https://github.com/user-attachments/assets/dd007f23-563e-4531-9aee-6051a3721af9)
![P20240823-223252](https://github.com/user-attachments/assets/01bcf135-58ff-4fec-8dec-8af8c183b712)
![P20240823-223301](https://github.com/user-attachments/assets/efb0f2cd-a230-4c52-89b5-3f964bb8caca)

**Comment by onionscode** [comment]
gpio如下

gpiochip1: GPIOs 410-495, parent: platform/pinctrl@ff634480, periphs-banks:
 gpio-431 (                    |bl                  ) out hi
 gpio-433 (                    |ffe09080.usb3phy    ) out hi
 gpio-434 (                    |lcd_cpu             ) out hi
 gpio-445 (                    |amlsd               ) out hi
 gpio-458 (                    |amlsd               ) in  hi
 gpio-459 (                    |OTG_SEL             ) out lo
 gpio-466 (                    |lcd_cpu             ) out hi
 gpio-472 (                    |AV_MUTE             ) out hi
 gpio-473 (                    |tas5805m-reset-pin  ) out hi
 gpio-482 (                    |sdio_wifi           ) out hi
 gpio-483 (                    |sdio_wifi           ) in  hi
 gpio-493 (                    |bt_rfkill           ) out hi
 gpio-495 (                    |bt_rfkill           ) out hi

gpiochip0: GPIOs 496-511, parent: platform/pinctrl@ff800014, aobus-banks:
 gpio-502 (                    |aw9523_rst          ) out hi
 gpio-503 (                    |key                 ) in  hi
 gpio-506 (                    |MIC_EN              ) out hi
 gpio-507 (                    |MIC_LED             ) out lo

**Comment by onionscode** [comment]
通过网盘分享的文件：A311D.img
链接: https://pan.baidu.com/s/1zQsPXd9_fTXyeviYrF6y_Q?pwd=dwuj 提取码: dwuj 
--来自百度网盘超级会员v6的分享
可以使用的固件如下，这个是安卓的。
原厂有个厂家测试模式，无法使用，通过ttl输出，感觉应该是原厂魔改的固件，ttl显示uboot输出是一样的

**Comment by 13584452567** [comment]
你这个板子，是不是magic cube 01？
我手里有一个类似的，天猫魔盒测试板。我这个硬件不一样，一直起不来有线网络。

**Comment by onionscode** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by onionscode** [comment]
> 你这个板子，是不是magic cube 01？ 我手里有一个类似的，天猫魔盒测试板。我这个硬件不一样，一直起不来有线网络。

板子号是MagicCube_X1_V01 20210330
我现在自己又重新提取了acs.bin文件，github上也找了icplus.c到u-boot里面，应该还是少id，uboot启动也是找不到网卡。
现在在换思路，尝试用原厂uboot引导tf卡的固件试试看

**Comment by denel23** [comment]
您好，这个板子在哪买？我想要买，请介绍一下。谢谢

**Comment by onionscode** [comment]
鱼上，已经没了
我的后面也卖掉了

**Comment by denel23** [comment]
遗憾，打算买颗芯片嵌入vim3。。成本可高了，您卖的多少钱

**Comment by onionscode** [comment]
200出头，现在玩3588吧这个测试性能比311d强很多

**Comment by 13584452567** [comment]
> 遗憾，打算买颗芯片嵌入vim3。。成本可高了，您卖的多少钱

我那个在吃灰，你要的话可以给你。
不过我更希望有人能够给它适配一个完好的设备树出来。

**Comment by denel23** [comment]
> > 遗憾，打算买颗芯片嵌入vim3。。成本可高了，您卖的多少钱
> 
> 我那个在吃灰，你要的话可以给你。 不过我更希望有人能够给它适配一个完好的设备树出来。

你有上面那个板子带着a311d-k？
