### ISSUE TITLE
如何开启视频硬件加速

### ISSUE THREAD

**Issue by fengdi** [ophub/amlogic-s9xxx-armbian#254]
chromium播放在线视频480p的视频cpu已经跑满了  vainfo发现  VA-API驱动没有正常安装，请问如何解决

设备:  hk1box 4 64g   s905x3
kernel 版本:  5.17.4  stable

**Comment by ophub** [comment]
`sudo snap install --channel=candidate/vaapi chromium`

Ubuntu 使用 VAAPI（硬件加速视频解码）支持测试 Chromium Snap
https://adatiya.com/post/37865.html
