### ISSUE TITLE
N1使用U盘系统每次重启都会变更mac地址

### ISSUE THREAD

**Issue by mengnimen** [ophub/amlogic-s9xxx-armbian#2544]
N1用U盘刷了Armbian_24.11.0_amlogic_s905d_noble_6.6.50_server_2024.09.10，每次重启mac地址变更。根据网络上修改NetworkManager方式，修改/etc/network/interfaces方式，均无法生效。重启mac地址必变。

在系统中使用armbian-config配置固定IP后导致显示设定的IP，但是SSH访问不了。

不知道其他人使用 U盘系统的有没有遇到过这个情况。
这个问题应该修改哪里能固定U盘系统里的mac地址，看了documents文件里的介绍，按照教程操作也是不生效。

**Comment by m986883511** [comment]
```shell
#!/bin/bash
# * * * * * /usr/local/bin/check_ssh.sh
# 检查 SSH 服务状态
if ! systemctl is-active --quiet ssh; then
    # 如果服务未启动，则启动 SSH 服务
    systemctl start ssh
    echo "SSH service was not running. Now started."
else
    echo "SSH service is running."
fi
```

ssh我加了个检查脚本，规避了

**Comment by mengnimen** [comment]
> ```shell
> #!/bin/bash
> # * * * * * /usr/local/bin/check_ssh.sh
> # 检查 SSH 服务状态
> if ! systemctl is-active --quiet ssh; then
>     # 如果服务未启动，则启动 SSH 服务
>     systemctl start ssh
>     echo "SSH service was not running. Now started."
> else
>     echo "SSH service is running."
> fi
> ```
> 
> ssh我加了个检查脚本，规避了

谢谢，你这个是我说的手动在armbian-config里面配置完静态地址后，加入服务后SSH能访问是吗？

**Comment by m986883511** [comment]
> > ```shell
> > #!/bin/bash
> > # * * * * * /usr/local/bin/check_ssh.sh
> > # 检查 SSH 服务状态
> > if ! systemctl is-active --quiet ssh; then
> >     # 如果服务未启动，则启动 SSH 服务
> >     systemctl start ssh
> >     echo "SSH service was not running. Now started."
> > else
> >     echo "SSH service is running."
> > fi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ssh我加了个检查脚本，规避了
> 
> 谢谢，你这个是我说的手动在armbian-config里面配置完静态地址后，加入服务后SSH能访问是吗？

是的，即使配了静态ip，ssh服务我的也不能自启动，加个脚本能解决，记住 使用`crontab -e`

**Comment by mengnimen** [comment]
> > > ```shell
> > > #!/bin/bash
> > > # * * * * * /usr/local/bin/check_ssh.sh
> > > # 检查 SSH 服务状态
> > > if ! systemctl is-active --quiet ssh; then
> > >     # 如果服务未启动，则启动 SSH 服务
> > >     systemctl start ssh
> > >     echo "SSH service was not running. Now started."
> > > else
> > >     echo "SSH service is running."
> > > fi
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ssh我加了个检查脚本，规避了
> > 
> > 
> > 谢谢，你这个是我说的手动在armbian-config里面配置完静态地址后，加入服务后SSH能访问是吗？
> 
> 是的，即使配了静态ip，ssh服务我的也不能自启动，加个脚本能解决，记住 使用`crontab -e`

好我一会试试，这样就可以固定IP了？我配置完SSH确实也不可用，但是本身机器也没有获得IP的，登录成功显示的lanip为空

**Comment by mengnimen** [comment]
> > > ```shell
> > > #!/bin/bash
> > > # * * * * * /usr/local/bin/check_ssh.sh
> > > # 检查 SSH 服务状态
> > > if ! systemctl is-active --quiet ssh; then
> > >     # 如果服务未启动，则启动 SSH 服务
> > >     systemctl start ssh
> > >     echo "SSH service was not running. Now started."
> > > else
> > >     echo "SSH service is running."
> > > fi
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ssh我加了个检查脚本，规避了
> > 
> > 
> > 谢谢，你这个是我说的手动在armbian-config里面配置完静态地址后，加入服务后SSH能访问是吗？
> 
> 是的，即使配了静态ip，ssh服务我的也不能自启动，加个脚本能解决，记住 使用`crontab -e`

我刚试了，还是不行，SSH进不去，虽然页面显示了lan IP地址 SSH也运行了。就是进不去

**Comment by mengnimen** [comment]
解决了
原因是刷入eMMC的系统没固定mac，导致U盘系统里的mac也不能固定。要先刷入eMMC，使用NetworkManager 管理网络固定mac地址，例如:nmcli con mod "Wired connection 1" ethernet.cloned-mac-address 11:22:1d:81:05:55，然后用U盘启动系统，也按照此方式进行mac固定即可。
我最早没有成功也有一个原因是我用的eMMC的系统是比较老的固件（fastnas）它使用的是interfaces 设置网络固定mac。导致我使用NetworkManager 管理网络固定mac地址失败。
有遇到相同问题的可以参考一下。
