### ISSUE TITLE
CM211-1-CH，HDMI接显示器无输出？

### ISSUE THREAD

**Issue by Daniel-Yen** [ophub/amlogic-s9xxx-armbian#2547]
**Device Information | 设备信息**
 - SOC:  S905L3
 - Model：CM211-1-CH

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.110
 - Release: jammy

**Describe the bug | 问题描述**
无线蓝牙模块UWE5621DS不生效，应该没有驱动
接USB无线网卡RTL8188ETV后wifi可以正常使用
现在的问题是，HDMI接显示器没有任何输出
是否需要进行一些设置？或者现在就是不支持HDMI？

**Comment by Daniel-Yen** [comment]
对了，一开始选择了noable版本，写入EMMC失败。
后来改了jammy，然后就可以写入EMMC了。

**Comment by Daniel-Yen** [comment]
找了好久的安卓固件，一直无法从U盘启动，几度想放弃。后来换了U盘重新烧录，一下子就成功了。

**Comment by Daniel-Yen** [comment]
vpu: error: vpu: check dts: FDT_ERR_BADMAGIC, load default parameters
应该是DTS出问题了，所以无法显示。。。

**Comment by Daniel-Yen** [comment]
安卓固件的DTS文件已提取，gxlx2_p291_2g.dts，但是很懵啊，差异太大了。。。
另外好像没看到有HDMI相关的驱动，不知道是不支持还是我没设置好？期待答复。

**Comment by ophub** [comment]
部分魔百和不支持hdmi显示，使用ssh连续管理

**Comment by Daniel-Yen** [comment]
> 部分魔百和不支持hdmi显示，使用ssh连接管理

好的，中秋快乐~
可否提供部分能完美支持armbian的盒子型号列表？谢谢~

**Comment by nomoneynolife** [comment]
> 部分魔百和不支持hdmi显示，使用ssh连接管理

大佬，UNT403A S905L3 支持HDMI吗，目前是黑屏的状态
