### ISSUE TITLE
Firefly_RK3399总是关机后会重启

### ISSUE THREAD

**Issue by A13788899580** [ophub/amlogic-s9xxx-armbian#2548]
**Device Information | 设备信息**
 - SOC: [RK3399]
 - Model [Firefly RK3399]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.110]
 - Release: [Armbian_bookworm_save_2024.09)]

**Describe the bug | 问题描述**
PowerOff后，系统退出，指示灯熄灭，大概3-5秒后，机子会自动重启。
按关机按钮，也是同样的情况。
实际上，以前的版本貌似都是这样。
我又另外一块不知名的RK3399，刷了tn3399_noble的固件，也是同样的问题。

**Comment by 13584452567** [comment]
自动重启一般是rk808电源芯片的配置。有些板子需要拆掉或者加上一个电容

**Comment by A13788899580** [comment]
非常感谢您的回复。
