### ISSUE TITLE
SKYWORTH HP40A

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#255]
Dear @ophub,

I have SKYWORTH HP40A STB, and i think it probably running powered by S905X2

Which DTB i should use?

![IMG_20220422_150408_722.jpg](https://user-images.githubusercontent.com/33513626/164646108-8cd2e67b-6621-4e0d-9f27-dc0c8d595844.jpg)
![IMG_20220422_150410_479.jpg](https://user-images.githubusercontent.com/33513626/164646135-ef7154f1-6a0f-4b69-81cf-44b0a9a1a25a.jpg)

*There is no SD slot
EMMC: SEC 937 B041 KLM8G1GETF

I think it's same like this
https://forum.xda-developers.com/t/skyworth-hp4024-hp40a.4425361/

**Comment by ophub** [comment]
not support
