### ISSUE TITLE
请求支持 H96 Max Rockchip RK3528 8K TV box

### ISSUE THREAD

**Issue by o-baka** [ophub/amlogic-s9xxx-armbian#2554]
**Device Information | 设备信息**
soc rk3528
型号 H96 Max Rockchip RK3528 8K TV box

官网介绍：https://www.h96tvbox.com/product/h96-max-rk3528/

**Armbian Version | 系统版本**
Armbian_24.11.0_rockchip_h96-max-m2_noble_6.1.75_server_2024.09.10.img.gz

买了个新盒子替换之前一直用的N1，发现没有支持，就用同是rk3528芯片的h96-max-M2的最新镜像
刷入SD卡，通电后能进入armbian系统
但是没有识别有线连接和无线网络（自身安卓系统可以识别）
进入armbian-config里也无法设置
是 H96 Max Rockchip RK3528 8K TV box 和 h96-max-M2 硬件有改变的原因吗？
该怎么解决。
![image](https://github.com/user-attachments/assets/46e3af46-753a-4112-addc-0e2e367728fa)
![屏幕截图 2024-09-18 090633](https://github.com/user-attachments/assets/309827ab-58ae-4f64-b004-27759216f166)
![屏幕截图 2024-09-18 090700](https://github.com/user-attachments/assets/21e1fe05-d661-4d16-9c71-52bdb8862333)
![屏幕截图 2024-09-18 090706](https://github.com/user-attachments/assets/f2ab5fd3-c021-49b3-b029-c35327dbdec5)

**Comment by ophub** [comment]
`armbian-update -k 6.1.43`

你换另外一个内核试试

**Comment by o-baka** [comment]
> `armbian-update -k 6.1.43`
> 
> 你换另外一个内核试试

这个操作要盒子连接网络的吧，我现在盒子连不上网，没法用这个命令。
找到一个网线转USB的有线网卡，连上网后试了 armbian-update -k 6.1.43 该命令，更新核心设备自动重启，依旧没有有线和无线。
暂且先用有线网卡。

**Comment by NNdroid** [comment]
我提取了android 系统的dtb和dts.不知如何修改dts编译armbian.

这是PCB.

<img width="883" height="793" alt="Image" src="https://github.com/user-attachments/assets/8d2a5a52-bdf0-4eae-8f1d-f798ad85d35d" />

<img width="923" height="789" alt="Image" src="https://github.com/user-attachments/assets/5ce6f023-cebc-432e-b48a-56c819a9cd1e" />

[rk3528.zip](https://github.com/user-attachments/files/24224444/rk3528.zip)

**Comment by D10DE** [comment]
Hello. Can you tell please, what exactly you did to make it boot? I have the same box, but it doesn't want to boot from SD, just a black screen (monitor gets turned off). I tried to flash the uboot from this repo, tried to extract uboot from the img - they don't boot nor SDcard not USB.
