### ISSUE TITLE
N1的wifi无法使用

### ISSUE THREAD

**Issue by Saintlord77** [ophub/amlogic-s9xxx-armbian#2555]
**Device Information | 设备信息**
 - SOC: [905D]
 - Model [N1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [noble]
安装了Armbian_24.11.0_amlogic_s905d_noble_6.1.109_server_2024.09.10.img之后首次启动wifi可用，但reboot之后wifi再也连接不上了。
内核更新为5.15后问题依旧。
但之前使用5.15内核的各个release 比如jammy bookworm无线驱动都没有问题。使用手中存档的Armbian_24.5.0_amlogic_s905lb-r3300l_noble_5.15.156_server_2024.04.27.img
更改dtb后也是没有问题的。

看之前的issue貌似这个问题由来已久，一直没有修复，但现在没有现成的内核的5.15镜像了，更改内核也不好用，希望大佬能关注一下，或者放出5.15内核的release。
谢谢。

**Comment by Saintlord77** [comment]
更新：最新测试Armbian_24.11.0_amlogic_s905d_noble_6.6.50_server_2024.09.10.img中wifi连接正常

**Comment by xfl12345** [comment]
感谢。但是 release hash `9c8c5b11b58b1cfbfba10809ad7bbd58bac150b8` tag [Armbian_noble_save_2024.10](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_noble_save_2024.10) 又不行了

文件 [Armbian_24.11.0_amlogic_s905l-mg101_noble_6.6.53_server_2024.10.02.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_noble_save_2024.10/Armbian_24.11.0_amlogic_s905l-mg101_noble_6.6.53_server_2024.10.02.img.gz)

**Comment by fettliu** [comment]
Armbian_24.11.0_amlogic_s905d_noble_6.6.63_server_2024.12.01

我的12月份版本也不能连接到Wifi。
但可以列出附近热点。
用wpa_cli能获取到下面这些日志。
国外有人提到这个错误在RP4上与HDMI的配置有关。

<3>CTRL-EVENT-SCAN-STARTED
<3>CTRL-EVENT-SCAN-RESULTS
<3>WPS-AP-AVAILABLE
<3>CTRL-EVENT-SCAN-STARTED
<3>CTRL-EVENT-SCAN-RESULTS
<3>WPS-AP-AVAILABLE
<3>CTRL-EVENT-SCAN-STARTED
<3>CTRL-EVENT-SCAN-RESULTS
<3>WPS-AP-AVAILABLE
<3>CTRL-EVENT-SCAN-STARTED
<3>CTRL-EVENT-SCAN-RESULTS
<3>WPS-AP-AVAILABLE
<3>CTRL-EVENT-SSID-REENABLED id=0 ssid="Fett"
<3>Trying to associate with SSID 'Fett'
<3>CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16
<3>CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="Fett" auth_failures=6 duration=103 reason=CONN_FAILED

**Comment by fettliu** [comment]
我又尝试了jammy版本，失败后。用fdisk删了所有分区，新建一个fat分区（保存）。再重新安装系统，wifi就能用了，神奇。
可能什么版本都可以这样处理。

**Comment by xfl12345** [comment]
> 我又尝试了jammy版本，失败后。用fdisk删了所有分区，新建一个fat分区（保存）。再重新安装系统，wifi就能用了，神奇。 可能什么版本都可以这样处理。

往往第一次能用，重启就寄了

**Comment by fettliu** [comment]
> > 我又尝试了jammy版本，失败后。用fdisk删了所有分区，新建一个fat分区（保存）。再重新安装系统，wifi就能用了，神奇。 可能什么版本都可以这样处理。
> 
> 往往第一次能用，重启就寄了

我的还是比较稳定的，我尝试了reboot，以及断电重连，都没问题了。现在已更新到noble，也可以正常wifi，后续如果坏了，我会再来跟帖，否则就是好了。

**Comment by LmonZero** [comment]
Armbian_24.11.0_amlogic_s905d_noble_6.6.63_server_2024.12.01  这个我是无法开发 wifi ap模式，使用armbian-config ,就会直接断开

**Comment by willsilicon** [comment]
> 直接

现在的版本中用armbianconfig设置AP提示必须是固定ip或dhcp的连接，我不明白这是在讲的什么

**Comment by LmonZero** [comment]
> Armbian_24.11.0_amlogic_s905d_noble_6.6.63_server_2024.12.01 这个我是无法开发 wifi ap模式，使用armbian-config ,就会直接断开
旧手机可以搜索到wifi 信号 但是无法连接

**Comment by karanokk** [comment]
> Armbian_24.11.0_amlogic_s905d_noble_6.6.63_server_2024.12.01
> 
> 我的12月份版本也不能连接到Wifi。 但可以列出附近热点。 用wpa_cli能获取到下面这些日志。 国外有人提到这个错误在RP4上与HDMI的配置有关。
> 
> <3>CTRL-EVENT-SCAN-STARTED <3>CTRL-EVENT-SCAN-RESULTS <3>WPS-AP-AVAILABLE <3>CTRL-EVENT-SCAN-STARTED <3>CTRL-EVENT-SCAN-RESULTS <3>WPS-AP-AVAILABLE <3>CTRL-EVENT-SCAN-STARTED <3>CTRL-EVENT-SCAN-RESULTS <3>WPS-AP-AVAILABLE <3>CTRL-EVENT-SCAN-STARTED <3>CTRL-EVENT-SCAN-RESULTS <3>WPS-AP-AVAILABLE <3>CTRL-EVENT-SSID-REENABLED id=0 ssid="Fett" <3>Trying to associate with SSID 'Fett' <3>CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16 <3>CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="Fett" auth_failures=6 duration=103 reason=CONN_FAILED

如果接HDMI的状态下reboot 100%成功，其实接TTL/短接GND和TX也100%成功,HDMI配置也不知道怎么改

**Comment by nnssz** [comment]
Armbian_24.11.0_amlogic_s905d_noble_6.6.50_server_2024.09.10.img中wifi连接正常
感谢，收藏！

**Comment by allonmymind** [comment]
> Armbian_24.11.0_amlogic_s905d_noble_6.6.50_server_2024.09.10.img

能否分享一份
