### ISSUE TITLE
X96max+ does not boot

### ISSUE THREAD

**Issue by psergeevich** [ophub/amlogic-s9xxx-armbian#256]
Good day. 
A few days ago it successfully booted from SDcard with image Armbian_22.05.0_Aml_s905x3_focal_5.15.34_2022.04.17.2118.img.gz. 
Today I try boot it from last image Armbian_22.05.0_Aml_s905x3_focal_5.15.35_2022.04.21.0001.img.gz , but it impossible. I see only X96max+ logo. 
I find changes in file meson-sm1-x96-max-plus-100m.dtb which I use. Similar changes is in meson-sm1-x96-max-plus.dtb. Can you repair аctual dtb-files?

**Comment by ophub** [comment]
try 5.10.112

**Comment by psergeevich** [comment]
Armbian_22.05.0_Aml_s905x3_focal_5.10.112_2022.04.21.0004.img.gz also does not boot

**Comment by ophub** [comment]
You have USB, try unplugging SD, just start Armbian using USB

**Comment by psergeevich** [comment]
5.10.112 started successfully using USB! Thanks!

**Comment by ophub** [comment]
ok
