### ISSUE TITLE
cm211-1 rtl8822cs WiFi不能识别

### ISSUE THREAD

**Issue by Derrick901101** [ophub/amlogic-s9xxx-armbian#2563]
**Device Information | 设备信息**
 - SOC: [S095l3]
 - Model [cm211-1]

**immortalwrt Version | 系统版本**
 - OpenWrt Kernel: 6.1.109-ophub
 - Release: [openwrt_immortalwrt_amlogic_s905l3-cm211_k6.6.50_2024.09.10.img.gz]

**Describe the bug | 问题描述**
无线芯片是rtl8822cs 看了下是支持linux 但是刷完发现网络那里没有无线功能的

打开wireless配置里面是空的

尝试 wlan0 up 提示 no such device

**Comment by Derrick901101** [comment]
同样的硬件刷Armbian_24.11.0_amlogic_s905l3-cm211_noble_6.6.50_server_2024.09.10.img 这个固件WiFi就能用

**Comment by gantoday** [comment]
@Derrick901101 刷完固件有额外的配置吗，我的 8822cs 也不能用现在。😊

**Comment by seeyoyoa** [comment]
> @Derrick901101 刷完固件有额外的配置吗，我的 8822cs 也不能用现在。😊

你搞定了不，我搞了2天都还是不能用wifi  armbian
