### ISSUE TITLE
Eth0 doesn't work on S905X3 SoC, TVBox Magicsee N5 Max

### ISSUE THREAD

**Issue by HoaPV127** [ophub/amlogic-s9xxx-armbian#2564]
**Device Information**
 - SOC:  S095x3
 - Model TV Box Magicsee N5 Max 

**Armbian Version**
 - Kernel Version: 6.6.50_
 - Release: Armbian_24.11.0_amlogic_s905x3_noble_6.6.50_server_2024.09.10.img.gz

**Describe the bug**
because there's no official supported for Magicsee N5 Max TV box so I choose the default devicetree to boot up, everything ok but the  et0 doesn't work and these error logs below are printed periodly

```
[  940.054029] meson8b-dwmac ff3f0000.ethernet eth0: Register NEM_TYPE_PAGE_POOL RxQ-0
[  940.243622] meson8b-dwmac ff3f0000.ethernet eth0: validation of rgmii with support 00,00000000,00000000,00006280 and advertisement 00,00000000,00000000,00006280 failed: -EINVAL
[  940.339364] meson8b-dwmac ff3f0000.ethernet eth0: __stmac_open: Cannot attach to PHY (error: -22)
```

I tried some others devicetree but it crashed at boot time. 
anyone has the same issue with me? 

thank you

**Comment by duongdt011099** [comment]
If you guys this read comment and also try to install on Magicsee N5 Max X3 here is the solution:
Use this dtb:  /dtb/amlogic/meson-sm1-x96-air.dtb, after booting up in the USB/sd-card use kernel version 5 (version 6 will not work). 
`sudo armbian-update -k 5.4.293 `
Then reboot
`sudo  armbian-install`
This will install to emmc successfully.

**Comment by HoaPV127** [comment]
@duongdt011099 thank bro,
bận bịu mãi giờ mới có thời gian vọc lại. đổi dtb và chuyển về dùng kernel ver5 như b chỉ đúng là đã lên đc eth0.
cho m hỏi chút là b có biết lý do tại sao nó không hoạt động được với kernel v6 ko? 
cảm ơn b lần nữa nhé :D

**Comment by cuong8880-sketch** [comment]
> [@duongdt011099](https://github.com/duongdt011099) thank bro, bận bịu mãi giờ mới có thời gian vọc lại. đổi dtb và chuyển về dùng kernel ver5 như b chỉ đúng là đã lên đc eth0. cho m hỏi chút là b có biết lý do tại sao nó không hoạt động được với kernel v6 ko? cảm ơn b lần nữa nhé :D

cho mình xin link tải bản ver 5 với ..mình tìm toàn bản ver 6 .. gmail cua mình cuong8880@gmail,com ..cảm ơn bạn

**Comment by HoaPV127** [comment]
trong release của repo này có đủ mà bro.

**Comment by HoaPV127** [comment]
> > [@duongdt011099](https://github.com/duongdt011099) thank bro, bận bịu mãi giờ mới có thời gian vọc lại. đổi dtb và chuyển về dùng kernel ver5 như b chỉ đúng là đã lên đc eth0. cho m hỏi chút là b có biết lý do tại sao nó không hoạt động được với kernel v6 ko? cảm ơn b lần nữa nhé :D
> 
> cho mình xin link tải bản ver 5 với ..mình tìm toàn bản ver 6 .. gmail cua mình cuong8880@gmail,com ..cảm ơn bạn

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_arm64_server_2025.11/Armbian_25.11.0_amlogic_s905x3_bookworm_5.15.196_server_2025.11.02.img.gz
