### ISSUE TITLE
U盘安装到armbian应该怎么操作？不是安装到emcc上

### ISSUE THREAD

**Issue by liangxiwei** [ophub/amlogic-s9xxx-armbian#2567]
我看文档都是教如何安装到emcc上，实际上我希望盒子本身还是android TV系统，而armbian系统安装在u盘上。

执行armbian-install只会安装到emcc上，我不执行直接就能用？

**Comment by liangxiwei** [comment]
因为平时安装pc的系统都是无法直接使用的。这个好像刷进去u盘就能直接用，不需要再走安装流程？如果是的话请close掉这个issue

**Comment by ophub** [comment]
对，写镜像img文件到U盘即可
