### ISSUE TITLE
cm311-1a安装桌面后无法识别u盘其他空间

### ISSUE THREAD

**Issue by liangxiwei** [ophub/amlogic-s9xxx-armbian#2568]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [cm311-1a]

**Armbian Version | 系统版本**
 - Kernel Version: [6.6.50]
 - Release: [bullseye]

**Describe the bug | 问题描述**
u盘启动，直接用armbian-software列表的【DESTOP】选项安装的，装完后重启，就无法识别u盘其他空间了。。好像进来的是类似于救援模式的命令行
![image_png (1) (1)](https://github.com/user-attachments/assets/9f31e0d1-4d16-4cdf-bc4c-0af6f4d026a8)

**Comment by liangxiwei** [comment]
df命令下只有/dev和/run

且 /dev下没有sd*的文件，
crtl+l清空console是initramfs开头的提示

**Comment by ophub** [comment]
反编译把dtb频率降低

**Comment by liangxiwei** [comment]
> dtb频率降低

我重新刷了一个jammy，是用armbian-update更新到最新内核重启后又是上面这个报错。。。

**Comment by liangxiwei** [comment]
> 反编译把dtb频率降低

请问是调整哪个字段.
`cpu@3 {
			device_type = "cpu";
			compatible = "arm,cortex-a53";
			reg = <0x00 0x03>;
			enable-method = "psci";
			next-level-cache = <0x4f>;
			#cooling-cells = <0x02>;
			cpu-supply = <0x50>;
			operating-points-v2 = <0x51>;
			clocks = <0x02 0xbb>;
			clock-latency = <0xc350>;
			phandle = <0x43>;
		};`
或者是下面这个？
`xtal-clk {
		compatible = "fixed-clock";
		clock-frequency = <0x16e3600>;
		clock-output-names = "xtal";
		#clock-cells = <0x00>;
		phandle = <0x08>;
	};`

**Comment by liangxiwei** [comment]
我查了下以前的issue，降低频率一般都是刷emmc没刷成功导致的，需要降低emmc的频率。
但我这个没有接触到emmc，全是u盘启动。就是u盘当系统本身在用。

**Comment by ophub** [comment]
无法读取USB磁盘，无法读取设备的EMMC，无法写入，或者不稳定，都是这一个原因。

**Comment by liangxiwei** [comment]
> 取设备的EMMC，无法写入，或者不稳定，

请教一下5.x内核的包在哪里找，我看符合s905l3a的都是6.x版本的，我想看别人用的老版本没问题，试试老版本的行不行

**Comment by liangxiwei** [comment]
改了后还是不行，u盘格式都写错了，插其他电脑上识别不出第二个分区。之前有个8g U盘装了openwrt拔出来插其他电脑是能识别出分区的。。估计就是扩展分区的时候写错地儿导致格式都不对，就识别不了。

拿了个16G的垃圾u盘倒是可以，怀疑是usb3.0的问题？

那个256G的u盘走7天无理由退了，对不起商家，这个issue关了吧我
