### ISSUE TITLE
e900v22d如何实现armbian输入emcc，并且支持从U盘启动emuelec4.6

### ISSUE THREAD

**Issue by shaloushu** [ophub/amlogic-s9xxx-armbian#2570]
**Device Information | 设备信息**
 - SOC: [S095l3a]
 - Model [e900v22d]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.107]
 - Release: [noble]

**Describe the bug | 问题描述**
盒子可以正常启动emuelec4.6，但不知道什么原因，启动armbian需要先安卓开机，通过ADB执行 dd if=/dev/zero of=/dev/block/env

启动armbian之后，基础设置，通过修改dtb频率，实现输入emmc，并且可以直接正常启动，并且U盘写入其他版本的armbian（例如bulleyes），也可以实现优先U盘启动

根据找到的教程（如图），替换aml_aotoscrip文件
![image](https://github.com/user-attachments/assets/38c3d97a-2d6c-410f-b811-16cbefbff6cf)
最后执行 armbian-install no
由于这个教程的内核还是5.x，armbian-install no 这个命令不行，找到下图这个参数，尝试执行了armbian-install -a no ，以及armbian-install -m no ，最后的结果都是变砖，在执行上述命令前，都是替换了aml_autoscrip 和dtb文件，只能通过线刷安卓回来。
![image](https://github.com/user-attachments/assets/80718352-e0de-4746-ad55-ab007f72b153)

想问一下两个问题
第一：是否能够实现我标题说的设想，应该怎么操作
第二：现在是使用两个U盘，但是启动过emuelec之后，换个U盘想要启动armbian，必须通过ADB 执行dd if=/dev/zero of=/dev/block/env ，不然开机就直接到电视系统，打开切换系统APK，也是跳到安卓的re界面。有什么方案可以实现一劳永逸，实现U盘随意换，随意启动？

**Comment by ophub** [comment]
这两个系统互斥，不可相互启动对方，不可共存。

**Comment by shaloushu** [comment]
> 这两个系统互斥，不可相互启动对方，不可共存。

好的，谢谢
