### ISSUE TITLE
腾讯极光盒子4

### ISSUE THREAD

**Issue by ksi1110** [ophub/amlogic-s9xxx-armbian#2573]
翻到一款老盒子，腾讯极光盒子4，CPU是全志的H616，内存2g，EMMC是三星的颗粒，16G，一个网口，一个hdmi，一个usb2.0，应该是双频无线，无线芯片的主控是紫光展讯，想刷个armbian丢在角落里跑docker，结果发现无适配的固件😂

O大你好，能否指点下我怎么折腾来适配这款盒子

![8f0fa1796dcce296b2a79378d8be3db](https://github.com/user-attachments/assets/24d4e9ce-ebaf-40de-88da-78b0183b8f22)
![abbb097cd1070998abd0987054850d9](https://github.com/user-attachments/assets/53516302-d6f4-4ed2-a432-a3dc1bebf490)
![image](https://github.com/user-attachments/assets/caf40122-a39e-4ed5-82ab-b9590f77c869)

![65854ed65e2cf28e0c34e39020eb4e1](https://github.com/user-attachments/assets/3491028b-acc2-4d1a-8aef-d241eab7d63d)
![d2aafce16b1d9255f72660c21830070](https://github.com/user-attachments/assets/ab939c26-eecc-438b-a3aa-3fae1b10e308)
![b9ea94c59fbd3970973c9e8bfacc85f](https://github.com/user-attachments/assets/e1cee839-7130-4288-ac76-df26dd467f56)

**Comment by ophub** [comment]
我这个仓库里没有这个soc的适配固件，你到上游找找，TF卡测试下

**Comment by ksi1110** [comment]
> 我这个仓库里没有这个soc的适配固件，你到上游找找，TF卡测试下

这设备不支持tf卡，倒是可以U盘试下，上游指的是官方？这个SOC貌似和香蕉派zero2是一样的，这个盒子使用量太低了，基本没人折腾😂

**Comment by ophub** [comment]
对，我这的固件是添加了一些官方不支持的一些设备的。官方仓库里还有很多设备支持的固件。

**Comment by ksi1110** [comment]
> 对，我这的固件是添加了一些官方不支持的一些设备的。官方仓库里还有很多设备支持的固件。

好咧，感谢大佬回复指点，我去找找看，祝假期愉快
