### ISSUE TITLE
X96Max+ PHY (IP1001M) support

### ISSUE THREAD

**Issue by psergeevich** [ophub/amlogic-s9xxx-armbian#258]
The ICPLUS IP1001M Ethernet Transceiver installed on TV-box, and it does not supported by Armbian. There are driver sources: https://github.com/torvalds/linux/blob/master/drivers/net/phy/icplus.c 
Can you add IP1001M support to your Armbian image?

**Comment by ophub** [comment]
Thanks for sharing, I will test it

**Comment by ophub** [comment]
do you have this device? Take a photo. You need to take more high-definition pictures. Around the chip, the package of ip1001 is different from that of 8211, and the external network components are different. There are also startup logs.

**Comment by psergeevich** [comment]
![Ether](https://user-images.githubusercontent.com/104202871/164878853-c0d5ab06-386f-412d-9087-1901c6a29bec.jpg)

**Comment by psergeevich** [comment]
![Общий вид](https://user-images.githubusercontent.com/104202871/164878868-4879d80f-f413-48eb-921b-c18f11ac0e63.jpg)

**Comment by psergeevich** [comment]
![общий вид](https://user-images.githubusercontent.com/104202871/164878921-7b95668e-1e5e-4772-b81e-c7eb100bf01a.jpg)

**Comment by psergeevich** [comment]
You can point places, which interest you, and I will take a photo of them. More photos here: https://drive.google.com/drive/folders/1sEZd837fwvmknJ2FtDvdf_i-f9Y1YnNm?usp=sharing

**Comment by ophub** [comment]
Okay, let's share a few days first

**Comment by ophub** [comment]
Take a frontal photo around the ip1001m chip, take a few more photos, and take a look at the surrounding package structure.

**Comment by psergeevich** [comment]
[log.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8547016/log.zip)

**Comment by psergeevich** [comment]
![IMG_20220423_202938](https://user-images.githubusercontent.com/104202871/164909383-1471c5bc-d953-4cbe-91fb-9800b99e8604.jpg)
![IMG_20220423_203017](https://user-images.githubusercontent.com/104202871/164909386-2ef9aff1-ed25-46b5-a7da-e78ee0dd5868.jpg)
![IMG_20220423_203034](https://user-images.githubusercontent.com/104202871/164909387-6e003b5b-7315-4ca3-b095-e5646650695c.jpg)
![IMG_20220423_203044](https://user-images.githubusercontent.com/104202871/164909389-107cdbc1-e527-4f21-8676-83ef06de2937.jpg)
![IMG_20220423_203108](https://user-images.githubusercontent.com/104202871/164909391-9401aa4d-05eb-4f8f-8b1c-2afce10a8ca2.jpg)
![IMG_20220423_203125](https://user-images.githubusercontent.com/104202871/164909392-7f2b5e7f-a11a-4aa2-92a4-22415264c9f5.jpg)
![IMG_20220423_203135](https://user-images.githubusercontent.com/104202871/164909394-e6ed9d46-c1cb-4c18-a051-ab4d24859b71.jpg)
![IMG_20220423_203156](https://user-images.githubusercontent.com/104202871/164909397-b8f0c7d9-686e-46ee-8fe6-7c1dff566a67.jpg)
![IMG_20220423_203356](https://user-images.githubusercontent.com/104202871/164909402-2203d6e3-3d02-4056-bdca-029e5afc1a00.jpg)
![IMG_20220423_203411](https://user-images.githubusercontent.com/104202871/164909405-29735088-2a98-497c-8ee9-3b8d633be27c.jpg)
![IMG_20220423_203423](https://user-images.githubusercontent.com/104202871/164909407-40075f28-d6d3-44e2-9bd8-2183785a3092.jpg)
![IMG_20220423_203448](https://user-images.githubusercontent.com/104202871/164909409-28abe536-723b-4470-ae0a-5c939364b146.jpg)
![IMG_20220423_203548](https://user-images.githubusercontent.com/104202871/164909412-402e22af-980b-4d6b-bb39-51f06b728808.jpg)
![IMG_20220423_203608](https://user-images.githubusercontent.com/104202871/164909413-743e52c3-1b9e-4e1b-a96b-4edcae3ba24a.jpg)
![IMG_20220423_203622](https://user-images.githubusercontent.com/104202871/164909415-79bae6dc-75e4-4000-bf2b-744496a4c19f.jpg)

**Comment by ophub** [comment]
![1](https://user-images.githubusercontent.com/68696949/164950573-ea4188d0-375e-4ef0-bbec-564ff3e0a2aa.jpg)
![2](https://user-images.githubusercontent.com/68696949/164950575-f2c23590-a5ca-434c-9d4a-dbf9fe7de317.jpg)

According to the log, the phy addr is incorrect, so it is necessary to measure the addr, specifically whether the level of the above 5 pins is high or low. The phy addr of RTL8211F is 0, but this value may be other values, there are 32 kinds from 00000-11111, or you can try one by one.

![3](https://user-images.githubusercontent.com/68696949/164950595-abf38005-1aab-440c-955a-e3eca9cc2f58.jpg)

If you have a multimeter, it is very convenient, you can get the correct result once you measure it, otherwise you have to keep changing the dtb

These two feet are also tested, involving the values of rx_delay and tx_delay

[2007171936_IC-Plus-IP1001M_C703552.pdf](https://github.com/ophub/amlogic-s9xxx-armbian/files/8548821/2007171936_IC-Plus-IP1001M_C703552.pdf)

**Comment by psergeevich** [comment]
Pins and voltages:
48 - 3.3v
49 - 3.3v
50 - 0.18v
51 - 0.18v
53 - 0.18v
7  - 1.8v 
8  - 1.8v

**Comment by ophub** [comment]
Received, thanks for the feedback

**Comment by ophub** [comment]
[ip1001m-dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8554333/ip1001m-dtb.zip)

According to your feedback, there are a total of 4 possibilities. You download the file and decompress it, put the `4 dtb files` into the `/boot/dtb/amlogic` directory, modify the dtb file name in `/boot/uEnv.txt`, and see which one It can drive your IP1001M network card normally, and feedback the results after the test, thank you. Restart after each modification to see if the network is normal.

**Comment by psergeevich** [comment]
All 4 dtb-files working normally. After reboot with each of them network is normal. 
I tested download/upload internet speed with "speedtest" python packet, and all results the same (about 50 Mbit/s). 
I tested download speed with wget 50 MB file and found differences:
meson-sm1-x96-max-plus-ip1001m-id - best results. First downloading about 2MB/s, subsequents - 6 MB/s
meson-sm1-x96-max-plus-ip1001m-rxid - all attempts about 2 - 2.5 MB/s
meson-sm1-x96-max-plus-ip1001 - about 800-900 MB/s
meson-sm1-x96-max-plus-ip1001m-txid - about 500 - 600 MB/s

Interface speed was 100 Mbit/s, because I did not have gigabit switch. Boot logs and another info I will send further.

**Comment by psergeevich** [comment]
[results.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8557219/results.zip)

**Comment by ophub** [comment]
@psergeevich 

[IP1001MDTB.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8559350/IP1001MDTB.zip)

```
meson-sm1-x96-max-plus-ip1001 - about 800-900 MB/s
meson-sm1-x96-max-plus-ip1001m-txid - about 500 - 600 MB/s
```

These two are the first choice, but the first one cannot be optimized, and the second one can be further fine-tuned. Attached is the fine-tuned dtb, you can test which one is better.
Need to use `iperf3` test to get more accurate test data, data in both directions of uplink and downlink

**Comment by psergeevich** [comment]
I connected X96Max+ to PC with gigabit ethernet adapter (192.168.5.3) and launched `iperf3 -s` on PC. On X96Max+ I launched 3 times for every .dtb:
```
iperf3 -c 192.168.5.3
iperf3 -c 192.168.5.3 -R
iperf3 -c 192.168.5.3 -u -b 0
iperf3 -c 192.168.5.3 -u -b 0 -R
```
All results are stored in files named `xxxr.y`, where:
`xxx` - last digits in .dtb-file name
`r` - present if reverse mode (-R key) used
`y` - test sequence number (0 - 2)
All files I will send further.

**Comment by psergeevich** [comment]
[results.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8565843/results.zip)

**Comment by ophub** [comment]
Thank you very much for your test. Now the dtb file of 2800 is tentatively used. Please execute the following command and give feedback on the execution result. This should be added to the comments of the dts file.

`cat /sys/class/net/eth0/phydev/phy_id`

**Comment by psergeevich** [comment]
execution result: 0x02430d91

**Comment by ophub** [comment]
Thank you very much for the very detailed test report for x96max plus v5.1 (ip1001m phy), your contribution has been recorded in the contributor list. Now unifreq has added that dtb in his relevant kernel. In the future, more users of this network card can benefit from your contribution.

https://github.com/unifreq/linux-5.15.y/commit/bca00ac86c16105b3f359bcb4e6c5d4011ae26b8

https://github.com/unifreq/linux-5.10.y/commit/2d09c2427633dd647850acbff007851372fe8609

https://github.com/unifreq/linux-5.4.y/commit/172adadaef0fa76cc842c7ef3ccd73fbcc3c1884

https://github.com/unifreq/linux-5.17.y/commit/e983ac4771d264d4add631e87368a7685bf0a729

**Comment by ophub** [comment]
Download today's firmware test

**Comment by harrydou123** [comment]
换成5月9日固件错识依旧。拆了测电压和psergeevich测的数据基本一致，但pin7不同。我测的pin7电压0.17v，与上面的数据电平相反。
我对arm dtb dts转换不是很熟，帮我生成一个dtb文件测试，将不胜感激。

**Comment by ophub** [comment]
> 换成5月9日固件错识依旧。拆了测电压和psergeevich测的数据基本一致，但pin7不同。我测的pin7电压0.17v，与上面的数据电平相反。
> 我对arm dtb dts转换不是很熟，帮我生成一个dtb文件测试，将不胜感激。

把你的测量结果发一下，他反应说现在的dtb在usb使用正常，写入emmc后网络无法使用。
用你的测试结果生成一个dtb试试

**Comment by harrydou123** [comment]
不好意，忙回复晚了。我用dtc工具作了穷举测试USB启动都没成功。万用表笔不趁手，正在网购中，我尽快反馈。
box版本号Q5X3_141 V5.1 21094, 板号D0709 7006 QC PASS GJHY 4+64

**Comment by ophub** [comment]
@psergeevich @harrydou123 

https://github.com/ophub/amlogic-s9xxx-armbian/issues/309

psergeevich重新测试了，结果还是一样的，等你测试完了反馈下

**Comment by harrydou123** [comment]
测了一下最新版本Armbian_Aml_jammy_server_05.18.2024中的Armbian_22.05.0_Aml_s905x3_jammy_5.10.116_2022.05.18.1932.img镜像，出现多个版本都能重现的问题，只是不同版本phandler冲突值不同。

按照5.10内核补丁提示，比较两个设备树。
diff meson-sm1-x96-max-plus-oc.dts meson-sm1-x96-max-plus-ip1001m.dts

```
261c261
<                       rx-internal-delay-ps = <0x320>;
---
>                       rx-internal-delay-ps = <0xaf0>;
1821,1822c1821,1822
<                                       ethernet-phy@0 {
<                                               reg = <0x00>;
---
>                                       ethernet-phy@3 {
>                                               reg = <0x03>;
2699c2699
<                                       compatible = "realtek,rtl8822cs-bt";
---
>                                       compatible = "brcm,bcm43438-bt";
2709c2709
<                                       status = "disabled";
---
>                                       status = "okay";


```

根据上下文，得到meson-sm1-x96-max-plus-ip1001m.dts

```
1807                         mdio-multiplexer@4c000 {
1808                                 compatible = "amlogic,g12a-mdio-mux";
1809                                 reg = <0x00 0x4c000 0x00 0xa4>;
1810                                 clocks = <0x02 0x13 0x1b 0x02 0xb1>;
1811                                 clock-names = "pclk\0clkin0\0clkin1";
1812                                 mdio-parent-bus = <0x1d>;
1813                                 #address-cells = <0x01>;
1814                                 #size-cells = <0x00>;
1815
1816                                 mdio@0 {
1817                                         reg = <0x00>;
1818                                         #address-cells = <0x01>;
1819                                         #size-cells = <0x00>;
1820
1821                                         ethernet-phy@3 {
1822                                                 reg = <0x03>;
1823                                                 max-speed = <0x3e8>;
1824                                                 reset-assert-us = <0x2710>;
1825                                                 reset-deassert-us = <0x13880>;
1826                                                 reset-gpios = <0x1e 0x0f 0x07>;
1827                                                 interrupt-parent = <0x1f>;
1828                                                 interrupts = <0x1a 0x08>;
1829                                                 phandle = <0x13>;
1830                                         };
1831                                 };
1832
1833                                 mdio@1 {
1834                                         reg = <0x01>;
1835                                         #address-cells = <0x01>;
1836                                         #size-cells = <0x00>;
1837
1838                                         ethernet_phy@8 {
1839                                                 compatible = "ethernet-phy-id0180.3301\0ethernet-phy-ieee802.3-c22";
1840                                                 interrupts = <0x00 0x09 0x04>;
1841                                                 reg = <0x08>;
1842                                                 max-speed = <0x64>;
1843                                         };
1844                                 };
1845                         };

```

在系统设置arm中armbian-config中，逐层找到armbian-config--System--Dtc--current.dts，mdio@0中ethernet-phy@3部分未加载。

```
1778                         mdio-multiplexer@4c000 {
1779                                 compatible = "amlogic,g12a-mdio-mux";
1780                                 reg = <0x00 0x4c000 0x00 0xa4>;
1781                                 clocks = <0x02 0x13 0x18 0x02 0xb1>;
1782                                 clock-names = "pclk\0clkin0\0clkin1";
1783                                 mdio-parent-bus = <0x1a>;
1784                                 #address-cells = <0x01>;
1785                                 #size-cells = <0x00>;
1786
1787                                 mdio@0 {
1788                                         reg = <0x00>;
1789                                         #address-cells = <0x01>;
1790                                         #size-cells = <0x00>;
1791                                 };
1792
1793                                 mdio@1 {
1794                                         reg = <0x01>;
1795                                         #address-cells = <0x01>;
1796                                         #size-cells = <0x00>;
1797
1798                                         ethernet_phy@8 {
1799                                                 compatible = "ethernet-phy-id0180.3301\0ethernet-phy-ieee802.3-c22";
1800                                                 interrupts = <0x00 0x09 0x04>;
1801                                                 reg = <0x08>;
1802                                                 max-speed = <0x64>;
1803                                                 phandle = <0x11>;
1804                                         };
1805                                 };
1806                         };
```
将差别部分
```1821                                        ethernet-phy@3 {
1822                                                 reg = <0x03>;
1823                                                 max-speed = <0x3e8>;
1824                                                 reset-assert-us = <0x2710>;
1825                                                 reset-deassert-us = <0x13880>;
1826                                                 reset-gpios = <0x1e 0x0f 0x07>;
1827                                                 interrupt-parent = <0x1f>;
1828                                                 interrupts = <0x1a 0x08>;
1829                                                 phandle = <0x13>;
1830                                         };
```
插入current.dts，由armbian自己生成dtb文件，和hdmi部分的phandle号冲突，报以下错误：
/tmp/tmp.mWkYh9rd2Q/current.dts:1792.56-1801.43: ERROR (explicit_phandles): /soc/bus@ff600000/mdio-multiplexer@4c000/mdio@0/ethernet-phy@3: duplicated phandle 0x13 (seen before at
[diff.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8723285/diff.zip)
 /soc/bus@ff600000/bus@34400/pinctrl@40/hdmitx_ddc)

**Comment by harrydou123** [comment]
补充：
我不懂arm，phandle瞎赋值0xff是可以通过的，但无效。
还有ethernet-phy和ethernet_phy同时出现在上下文是什么情况？
不懂就问:)

**Comment by harrydou123** [comment]
附件是我从网卡可以正常工作的android9系统/proc/device-tree中copy下来的 ethernet@ff3f0000和sdio@ff3f0000目录，不知是否有帮助。
[ethernet@ff3f0000.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8725420/ethernet%40ff3f0000.zip)

**Comment by harrydou123** [comment]
我测的电压
48--3.35
49--3.35
50--0.17
51--0.17
7---0.17
8---3.35

**Comment by harrydou123** [comment]
我测的电压
48--3.35
49--3.35
50--0.17
51--0.17
7---0.17
8---3.35

**Comment by Loncc** [comment]
最新的dtb armbian不会报error-19了，但是连接电脑会一直无法获取ip地址。openwrt也不能刷

**Comment by QQ43935353** [comment]
Android 9 system dts
ethernet@ff3f0000 {
		compatible = "amlogic, g12a-eth-dwmac", "snps,dwmac";
		reg = <0x0 0xff3f0000 0x0 0x10000 0x0 0xff634540 0x0 0x8 0x0 0xff64c000 0x0 0xa0 0x0 0xffd01008 0x0 0x4>;
		reg-names = "eth_base", "eth_cfg", "eth_pll", "eth_reset";
		interrupts = <0x0 0x8 0x1>;
		interrupt-names = "macirq";
		status = "okay";
		clocks = <0x13 0x38>;
		clock-names = "ethclk81";
		pll_val = <0x9c0040a 0x927e0000 0xac5f49e5>;
		analog_val = <0x20200000 0xc000 0x23>;
		pinctrl-names = "external_eth_pins";
		pinctrl-0 = <0x29>;
		mc_val = <0x1609>;
		cali_val = <0x80000>;
		internal_phy = <0x0>;
		phandle = <0xb0>;
	};
