### ISSUE TITLE
N1 wifi 异常

### ISSUE THREAD

**Issue by dmserver** [ophub/amlogic-s9xxx-armbian#2582]
**Device Information | 设备信息**
 - SOC: [e.g. S905D]
 - Model [e.g. N1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g.   6.6.50   6.6.53]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
镜像刻录在U盘时  wifi能够正常扫描 和连接网络
armbian-install安装进N1后  无线可以进行扫描  但始终不能连接

armbian-config 无法连接wifi  反复弹出密码输入提示

nmcli 连接错误如下
Error: Connection activation failed: (7) Secrets were required, but not provided.

无论是使用ssid bssid 还是指定网卡  始终报错
nmcli dev wifi connect "huawei" password "12345678"
但是在U盘里测试 无论怎么连接测试都是可以的   安装到N1就无法连接网络了

这个情况只针对N1自带无线网卡     因为外挂的usb无线网卡测试是正常的2.4G 5G wifi连接都没问题
ip add 和 ifconfig 均能看到N1自带的无线网卡    并且网卡可以进行网络扫描   只是无法连接

![QQ20241003-125447](https://github.com/user-attachments/assets/f76ef1d1-157f-42bc-8724-afa8f939d4cb)

**Comment by ruleechen** [comment]
遇到一样的问题，可以换成bullseye同版本

**Comment by nekoprpr** [comment]
我之前也是连不上
我后面更换了软件源 更新了内核 升级了软件包
后面我用nmtui可以连上
我不知道和这个有没有关系 
你可以试试

**Comment by ruleechen** [comment]
今天试了最新的build [Armbian_24.11.0_amlogic_s905d_bullseye_6.6.57_server_2024.10.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2024.10/Armbian_24.11.0_amlogic_s905d_bullseye_6.6.57_server_2024.10.21.img.gz) 看起来wifi的问题修复了

**Comment by nnssz** [comment]
[Armbian_24.11.0_amlogic_s905d_bullseye_6.6.57_server_2024.10.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_save_2024.10/Armbian_24.11.0_amlogic_s905d_bullseye_6.6.57_server_2024.10.21.img.gz) 收藏，感谢！
