### ISSUE TITLE
Snap install not working

### ISSUE THREAD

**Issue by Kaojedsadakron** [ophub/amlogic-s9xxx-armbian#259]
When I try to install chromium, it show like in the picture
![Screenshot 2022-04-23 003852](https://user-images.githubusercontent.com/83747203/164766216-083bd939-9f4e-4da2-accb-3b844fac6b16.png)

**Comment by ophub** [comment]
Jammy's package cannot be installed, so give upstream feedback

**Comment by JFLim1** [comment]
@ophub 
FYI, I faced the same issue with Jammy.  The snapd in Jammy is not working as expected for now.  From what I gathered Ubuntu knows about it and is going to resolve it.

**Comment by ophub** [comment]
The official version of jammy should be released on April 24th, let's wait a few days before using it, we are all testers now

**Comment by JFLim1** [comment]
> The official version of jammy should be released on April 24th, let's wait a few days before using it, we are all testers now

Haha. Yes.  As far as I can tell, the sudo tasksel still install Debian Desktop/Gnome Desktop instead of Ubuntu Desktop.

**Comment by fengdi** [comment]
@ophub #254   `sudo snap install --channel=candidate/vaapi chromium`    It is also the same failure error
