### ISSUE TITLE
hwclock: ioctl(RTC_SET_TIME) to /dev/rtc0 to set the time failed: Invalid argument

### ISSUE THREAD

**Issue by MATORINET** [ophub/amlogic-s9xxx-armbian#2593]
**Device Information |**
 - SOC: [S905x]
 - Model [HG680P]

I tried to install terminus os on my sbc s905x hg680p with the ubuntu version os 22 but got hit by a problem in the hwclock as below logs

``11Oct` 11:35:52 ntpdate[13682]: step time server 202.65.114.202 offset -0.002831 sec hwclock: ioctl(RTC_SET_TIME) to /dev/rtc0 to set the time failed: Invalid argument 2024-10-11T11:35:53.002Z        matori Failed to exec command: /bin/sh -c /usr/sbin/hwclock -w hwclock: ioctl(RTC_SET_TIME) to /dev/rtc0 to set the time failed: Invalid argument: exit status 1 2024-10-11T11:35:53.002Z        [A] matori: UpdateNtpDate failed (15.726925459s) 2024-10-11T11:35:53.003Z        [Job] [Prepare the System Environment] execute failed `<nil>``

Is there any way to bypass the hwclock -w ? , because my sbc when checking the clock using timedatectl is in accordance with the existing time But the app requires the command hwclock -w to install .

**Comment by trawor** [comment]
+1 here, installing in LXC container of PVE, have no permitted to hwclock
