### ISSUE TITLE
Armbian如何添加网桥

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#2594]
**Device Information | 设备信息**
 - SOC: [S905l3a]
 - Model [unt403a]

**Armbian Version | 系统版本**
 - Kernel Version: [6.6.53]
 - Release: [bookworm]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bookworm_save_2024.10/Armbian_24.11.0_amlogic_s905l3a_bookworm_6.6.53_server_2024.10.02.img.gz

**Describe the bug | 问题描述**
我想给Armbian安装kvm，使用自带的脚本Armbian-software时，安装完成后重启的话，盒子会获取不到ip，无法联网。
然后尝试按照unifreq大佬的教程安装kvm（https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md），但是在配置网桥的步骤时，配置完重启后还是获取不到ip，设备断网。请问是不是现在Armbian的网络配置的方式更改了？

**Comment by ophub** [comment]
是的，默认网络服务不一样了。
