### ISSUE TITLE
apt install时报错

### ISSUE THREAD

**Issue by Cxyofficial** [ophub/amlogic-s9xxx-armbian#2595]
**Device Information | 设备信息**
 - SOC: [S905L3B]
 - Model [CM311-1YST]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.133]
 - Release: [jammy]

**Describe the bug | 问题描述**
在尝试sudo apt install chromium chromium-driver时无法安装
 
输出信息：
正在读取软件包列表... 完成
W: 无法下载 https://download.docker.com/linux/ubuntu/dists/jammy/InRelease  Could not handshake: Error in the pull function. [IP: 18.155.68.17 443]
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/jammy/main/binary-i386/Packages  404  Not Found [IP: 101.6.15.130 443]
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/jammy-updates/main/binary-i386/Packages  404  Not Found [IP: 101.6.15.130 443]
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/jammy-backports/main/binary-i386/Packages  404  Not Found [IP: 101.6.15.130 443]
E: 无法下载 https://mirrors.tuna.tsinghua.edu.cn/ubuntu-ports/dists/jammy-security/main/binary-i386/Packages  404  Not Found [IP: 101.6.15.130 443]
W: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。

**Comment by wnpllrzodiac** [comment]
try `apt update` first

**Comment by Cxyofficial** [comment]
> try `apt update` first

用了

**Comment by ophub** [comment]
你的设备的网络无法访问docker服务器。把你的设备添加到那种网络环境里。

**Comment by wnpllrzodiac** [comment]
那种

**Comment by Cxyofficial** [comment]
额外问一个问题可以吗？
青龙容器咋装selenium啊
整半天了

**Comment by Cxyofficial** [comment]
> 额外问一个问题可以吗？ 青龙容器咋装selenium啊 整半天了

在armbian试着装过一次 但是报错 selenium驱动不起来 百度搜不到
![Screenshot_2024-10-19-22-38-01-170_mark via](https://github.com/user-attachments/assets/60d55cac-261a-4fb1-a37e-739b26076cd0)
