### ISSUE TITLE
新魔百盒M304a增强版 2+16     s905L3  可以吗？

### ISSUE THREAD

**Issue by ruyi951** [ophub/amlogic-s9xxx-armbian#2596]
新魔百盒M304a增强版 2+16     s905L3  可以吗？

**Comment by hsycc** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/2597 应该可以

**Comment by ruyi951** [comment]
> [第2597章](https://github.com/ophub/amlogic-s9xxx-armbian/issues/2597)应该可以

我试试
