### ISSUE TITLE
Kernel Header for 5.10.79-flippy-67+

### ISSUE THREAD

**Issue by sangnpq** [ophub/amlogic-s9xxx-armbian#26]
Hi @ophub,
I appreciate your sharing. I've installed successfully on my X96 Max+ and now it run smoothly on eMMC. 
Just a bit issues when I can't find linux-headers-5.10.79-flippy-67+ anywhere. I found a linux-headers-meson64 when I install followed armbian-config command. So I try to build some driver through linux-headers-meson64 but it can't modprobe into system cause it required linux-headers-5.10.79-flippy-67+.
Could you give me some advices or information to install linux-headers-5.10.79-flippy-67+?
Thanks in advance.

**Comment by ophub** [comment]
https://linuxhint.com/install-kernel-headers-debian/

This flippy is customized, maybe you need to customize one? Compile under your armbian system.

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

**Comment by ophub** [comment]
I asked the [flippy](https://github.com/unifreq/openwrt_packit) boss, the method he introduced: 

`make headers_install ARCH=arm64 INSTALL_HDR_PATH=/usr/header`


I am a beginner, you can ask him for advanced questions.

**Comment by ophub** [comment]
Download the latest [armbian-update](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-update) script: 

In the latest 4 kernels (`5.10.80` / `5.14.20` / `5.15.3` / `5.4.160`), flippy shared the header files, I updated the script to support direct installation of the header files.
```
wget -O /usr/sbin/armbian-update https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/files/usr/sbin/armbian-update && chmod +x /usr/sbin/armbian-update

armbian-update 5.4.160
```
