### ISSUE TITLE
按这个方法 ”章鱼星球刷机方法“，刷机后，可以正常从EMMC启动，但有一个新问题了

### ISSUE THREAD

**Issue by lanyucomputer** [ophub/amlogic-s9xxx-armbian#260]
按这个方法 ”章鱼星球刷机方法“，刷机后，可以正常从EMMC启动，但有一个新问题了，就是不能通过USB BURNING TOOL连接刷安卓包了，软件显示“连接成功”一秒后，就自动断开，从EMMC启动进armbian了，测试版本为5.10.112内核

**Comment by lanyucomputer** [comment]
不能刷安卓包了，是不是bootloader引起的

**Comment by ophub** [comment]
你看的贴子里，他一天刷了十几次。而且是无拆机直接usb burning刷的，所以和bootloader 有关系的话，他怎么刷的？

**Comment by lanyucomputer** [comment]
哈哈，我就是那个昨天测试的人啊，现在用的是昨天5.10.112内核 的，我早上想把所有的重刷一遍的时候，发现的刷好5.10后，就没有办法再次连接USB BURNING TOOL了

**Comment by ophub** [comment]
你昨天不是刷过多次5.10吗

**Comment by lanyucomputer** [comment]
是的，昨天的问题是可以用USB Burning Tools随便刷安卓，不能把armbian写入EMMC，昨天刷好了，因为昨天测试了好几个版本，今天早上起来我想把系统搞纯净一点，就想把所有的流程重新走一遍，就是先刷安卓，再刷armbian,但是发现连上USB Burning Tools一秒就自动从EMMC启动了，意思就是不能连接USB Burning Tools了，不是又来反馈了吗，还有5.10的armbian,进系统后，电脑键盘的数字小键盘不能正常使用，可以用上面的那一排输入数字

**Comment by lanyucomputer** [comment]
> 你昨天不是刷过多次5.10吗。手动dd安装bootloader 也很多次。你再多试几次，UBT工具经常这样，有时走进度条也卡，有时短接无反应，多试直到成功。

昨天很好连USB Burning Tools工具的，连上USB线按RESET键不放，再接电源，每次一次成功，不用多次，今天我试了多次才发现它连上一秒就自动从EMMC启动了，它没有保持和USB Burning Tools的连接状态

**Comment by ophub** [comment]
插U盘能从U盘启动armbian 系统吧？dd别的系统

**Comment by lanyucomputer** [comment]
> 插U盘能从U盘启动armbian 系统吧？dd别的系统

可以U盘启动armbian系统，那以后线刷 怎么办？是什么原因引起的这个问题呢？

**Comment by ophub** [comment]
你dd安卓就是原版了。又和以前一样了。原因未知，你昨天dd了几次bootloader 不也没事吗？后面的线刷不都可以吗？

**Comment by lanyucomputer** [comment]
不能从U盘启动了现在，只能从EMMC启动,我上面以为昨天从U盘启动运行armbian-update 5.17了可以U盘启动，刚实测不能USB启动了，怎么搞都是从EMMC启动了，我想从USB启动要怎么搞？

**Comment by lanyucomputer** [comment]
> 你dd安卓就是原版了。又和以前一样了。原因未知，你昨天dd了几次bootloader 不也没事吗？后面的线刷不都可以吗？

是不是昨天升级5.17的时候写入什么东西改写了导致的？

**Comment by ophub** [comment]
5.17和5.10一样。只是/boot下多复制了一个u-boot.emmc文件。没有写入emmc。
写入的只有bootloader ，这个文件你刷了很多次了。

**Comment by lanyucomputer** [comment]
那就奇怪了啊，昨天刷了不下20次都可以UBT连接，现在只能用armbian 5.10了

**Comment by ophub** [comment]
可以他听说你测了5.15之后还要回到5.10，觉得和你特别投缘，就这样终身相许了吧。

**Comment by lanyucomputer** [comment]
> 可以他听说你测了5.15之后还要回到5.10，觉得和你特别投缘，就这样终身相许了吧。

可不可以，我现在把BOOTLOADER复制进去，用DD命令一次，试试？

**Comment by lanyucomputer** [comment]
> > 可以他听说你测了5.15之后还要回到5.10，觉得和你特别投缘，就这样终身相许了吧。
> 
> 可不可以，我现在把BOOTLOADER复制进去，用DD命令一次，试试？我又不想拆机去短接什么的，但我怕DD之后，现在的系统也启不动，那就惨了，可能就真的要拆机短接了

**Comment by ophub** [comment]
可以，写入脚本已经dd过了。可以多次dd

**Comment by lanyucomputer** [comment]
> 可以，写入脚本已经dd过了。可以多次dd

会不会现在这个系统 也启不动呢？

**Comment by ophub** [comment]
你不dd也不能保证下次还能不能重启，电源烧了，家里没电了，网费忘交了，路由器挂了…惊喜那么多，平常心对待

**Comment by lanyucomputer** [comment]
> 你不dd也不能保证下次还能不能重启，电源烧了，家里没电了，网费忘交了，路由器挂了…惊喜那么多，平常心对待

毕竟这种概率会小得多，哈哈

**Comment by lanyucomputer** [comment]
黑色版应该是开发板
Amlogic Meson GXM (S912) Q200 Development Board

ARMv8 Processor rev 4 x 8

**Comment by lanyucomputer** [comment]
用5.3.0的内核 ，docker openwrt 镜像很多都可以正常，F大的可以，N1盒子的也可以用，昨天那个不显示什么的，会不会是因为armbian的内核是5.10的太新了，现在OPENWRT的镜像不没有匹配？

**Comment by ophub** [comment]
我没用过docker版的op，没见过那个界面。但是我想应该是可以正常显示的，因为我在群里没有看到别人说不显示。

**Comment by lanyucomputer** [comment]
终于可以连UBT再刷安卓了，方法如下，启动UBT把安卓H96包先选好点开始，然后插上双公头USB线和按RESET键，再直接插电源，这样虽然不能稳定连接，但刚连上的时候，UBT就自动开始了，这样就过了，这样就可以用UBT线刷了，又开始了我的折腾之旅，哈哈

**Comment by ophub** [comment]
一般来说都是不要电源的，USB供电就够了。但是昨天那天帖子里，你翻翻看看，有的人不刷H96PRO也可以USB启动，有的人刷了也需要多次尝试，很多评论说供电不足。你今天插电源才能继续，也是供电不足。
不过你只是证明了一点，就是每个你发的帖子，总得来点故事，最后形成一个文档。


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#103-如何恢复原安卓-tv-系统
