### ISSUE TITLE
23号后的镜像Armbian_22.05.0_Aml_s912_focal_5.10.112_2022.04.23.1030.img.gz，还有替换armbian-install吗？

### ISSUE THREAD

**Issue by lanyucomputer** [ophub/amlogic-s9xxx-armbian#261]
23号后的镜像Armbian_22.05.0_Aml_s912_focal_5.10.112_2022.04.23.1030.img.gz，还有替换armbian-install吗？可以直接写入EMMC了吗？直接写入EMMC可以启动了吗？昨天测试的成果放进新的版本了吗？

**Comment by lanyucomputer** [comment]
我试了，可以直接写入了，什么也不用替换，写的时候选（fake)那个202就可以了，这样就更方便了，给你一个大大的赞

**Comment by ophub** [comment]
对，专门为你的设备加的。
https://github.com/ophub/kernel/releases/tag/tools
这里有你章鱼用的h96的下载和两种主板的区别照片

**Comment by lanyucomputer** [comment]
那5.15内核的HDMI显示输出OK了吗？

**Comment by ophub** [comment]
不ok呢，除了5.15，其他的你测试了没？5.10/5.17/5.4是正常的？

**Comment by lanyucomputer** [comment]
没有测试了，现在用的5.10，这个内核比较新，然后又有显示输出，可以了，其它的就没有折腾了，太要时间了，现在DOCKER OPENWRT也可以，用的这个镜像  docker pull xuanaimai/phicomm-n1    和N1的通用，他家的玩客云镜像也很好用，再装一个CUPS打印服务器，其它的慢慢玩，不折腾了

**Comment by lanyucomputer** [comment]
主机名 | OpenWrt
主机型号 | Octopus Planet
架构 | ARMv8 Processor rev 4 x 8
固件版本 | OpenWrt R21.8.6 / LuCI Master (git-21.238.35254-83494a9)
内核版本 | 5.10.112-meson64-dev
本地时间 | 2022-04-24 \| 15:29:43
运行时间 | 1h 29m 34s
CPU状态 | 1.512 Ghz \| 45.0 ℃
平均负载 | 0.39, 0.25, 0.25
CPU 使用率（%） | 2 %

型号，内核，架构那些都为示正常

**Comment by ophub** [comment]
好的

**Comment by janko888** [comment]
> 主机名 | OpenWrt
> 主机型号 | Octopus Planet
> 架构 | ARMv8 Processor rev 4 x 8
> 固件版本 | OpenWrt R21.8.6 / LuCI Master (git-21.238.35254-83494a9)
> 内核版本 | 5.10.112-meson64-dev
> 本地时间 | 2022-04-24 | 15:29:43
> 运行时间 | 1h 29m 34s
> CPU状态 | 1.512 Ghz | 45.0 ℃
> 平均负载 | 0.39, 0.25, 0.25

5.17.4的内核，HDMI输出正常了。

**Comment by janko888** [comment]
> 不ok呢，除了5.15，其他的你测试了没？5.10/5.17/5.4是正常的？ 在USB上`armbian-update xxx`就可以测试

5.17.4的内核的我在fake章鱼上测试HDMI可以正常显示了。妥妥的黑科技！！！
