### ISSUE TITLE
无法使用3.5耳机接口 Unable to use 3.5 headphone connector

### ISSUE THREAD

**Issue by 2468171796** [ophub/amlogic-s9xxx-armbian#265]
I am a novice, I have studied for a long time these days, still can not use 3.5 ears hole, can not use MPD to play music, can not use Homeassistant to play music, I want to use it to do background music server, hope to give a tutorial to help me solve this problem, your project is of great help to me, thank you! Selfless developer!

我是新手，我这几天研究了好久，还是无法使用3.5耳机孔，无法使用MPD 播放音乐，无法使用Homeassistant播放音乐，我想用它做背景音乐服务器，希望可以出个教程，帮助我解决这个问题，你们的项目对我有很大的帮助，谢谢你们！无私的开发者！

**Comment by 2468171796** [comment]
哥，帮帮忙，我就想安装个mpd播放器，让他可以播放声音，用3.5耳机孔，我在armbian-config里面也没找到，我网上找了好多教程，都没解决问题，我网上看香橙派也是armbian  他的armbian-config里面直接有开启3.5耳机输出的选项，我自己还买了USB声卡都没解决，我为这个问题研究好多天了。我自己本身就是小白，都是自学的，目前卡在这里了，我就想实现Homeassistant控制背景音乐这个功能，现在卡住了，希望大佬帮帮我！！！！！感谢！！！！
![image](https://user-images.githubusercontent.com/43125771/164975199-98dae236-631c-4d6f-bcf1-21134082f3b6.png)
![image](https://user-images.githubusercontent.com/43125771/164975232-9b38903b-8cf4-4ea7-802d-eb39f1a8544d.png)

**Comment by ophub** [comment]
我使用苹果蓝牙耳机可以正常看视频听音乐。我没有线耳机。

**Comment by uncle-wong** [comment]
使用mpd要修改、etc/mpd.conf的audio_output设置的。
