### ISSUE TITLE
手贱把armbian-config删除了，请问要怎么恢复呢，在说明文档和网上没找到相应的办法

### ISSUE THREAD

**Issue by Huij1a** [ophub/amlogic-s9xxx-armbian#2653]
![屏幕截图 2024-11-21 032633](https://github.com/user-attachments/assets/c3f7c717-0a57-4da4-bede-2e29e4d3fe0a)
谢谢O大！！

**Comment by mrhuzi** [comment]
安装：
apt install armbian-config
