### ISSUE TITLE
Strange systemd error 

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#266]
Hi @ophub 
I am facing a problem with systemd and CGroup2, searching the net I found this link 
https://unix.stackexchange.com/questions/667937/debian-11-works-fine-but-strange-systemd-error-happen 
which deals with exactly the same problem but their solution goes through Grub, which is not used with armbian, I'm a bit lost so I come and get your expert opinion..
Thank.
Edit: Seems to be systemd issue => https://github.com/systemd/systemd/issues/23164

**Comment by MX10-AC2N** [comment]
Another thing ,I Fork your repository, yesterday I was up to date with your repository but today after your last 2 commits, I find myself with a repository that is 80 commits ahead and 82 commits behind yours.. fetch upstream impossible.. 
Has there been a return to an older version?

**Comment by ophub** [comment]
It is a good way to add and modify the default values of kernel boot parameters through the boot boot file description (/etc/default/grub).

**Comment by ophub** [comment]
In order to reduce the size of git and reduce the capacity of the repo, sometimes I completely remove the files that are not used in the warehouse from git. The examples from sources were cleared yesterday.

`git filter-repo --invert-paths --force --path-glob '*patches/apt-sources*'`

**Comment by MX10-AC2N** [comment]
Hi @ophub
I can use grub on armbian system ?? 
I can boot on my sd-card with u-boot.ext,
 if I try boot without u-boot.ext there is only black screen on my tv and no SSH connection. invisible from my router..
So I need use u-boot.ext for boot kernel 5.15.y on my sd-card.. Can I use grub with u-boot.ext too ?
Thank a lot..

**Comment by ophub** [comment]
Adding kernel parameters in uEnv.txt also works.

u-boot.ext can be added to any version of the kernel. In 5.4/5.15, because the TEXT_OFFSET patch is added, it can be used without u-boot under normal circumstances. But recently, some people have also responded that when using the 5.15 kernel in the s912 system, they should also add

**Comment by MX10-AC2N** [comment]
Adding `systemd.unified_cgroup_hierarchy=0` in /boot/uEnv.txt solve my problem..
Thank again..

**Comment by JFLim1** [comment]
Hi @MX10-AC2N 

Just to seek clarification.

You are able to boot up on SD Card using ophub latest 5.15.35-flippy-72+o with u-boot.ext.

And able to boot up on SD Card without u-boot.ext when you "Adding systemd.unified_cgroup_hierarchy=0 in /boot/uEnv.txt " .

Is this correct?  Thanks.

**Comment by MX10-AC2N** [comment]
> Hi @MX10-AC2N
> 
> Just to seek clarification.
> 
> You are able to boot up on SD Card using ophub latest 5.15.35-flippy-72+o with u-boot.ext.
> 
> And able to boot up on SD Card without u-boot.ext when you "Adding systemd.unified_cgroup_hierarchy=0 in /boot/uEnv.txt " .
> 
> Is this correct? Thanks.

Hi @JFLim1
No I can't boot without u-boot.ext on SD-Card, the kernel 5.15.35-flippy-72+o can't boot (Always lot of I/O error on my sd-card)
So I fork the repository and launch a new actions, compile kernel but with kernel.org.. This kernel can boot on my sd-card but always need u-boot.ext (without u-boot.ext I only got black screen on my tv and no ssh connection) 
I have a problem with signal hdmi my TV stay black but i can connect with SSH and all seems to be fine.. 
The "systemd.unified_cgroup_hierarchy=0" is just for another problem with systemd and yunohost user service.. 

Hi @ophub , 
Is there a command to force the video output to HDMI that we can add in uEnv.txt ?
Thanks, and have a nice day..

**Comment by JFLim1** [comment]
> No I can't boot without u-boot.ext on SD-Card, the kernel 5.15.35-flippy-72+o can't boot (Always lot of I/O error on my sd-card)

Thanks for the clarification.

**Comment by ophub** [comment]
Kernel parameters that can be initialized at startup can be tried in uEnv.txt

**Comment by MX10-AC2N** [comment]
> In order to reduce the size of git and reduce the capacity of the repo, sometimes I completely remove the files that are not used in the repo from git. The examples from sources were cleared yesterday. You still have this commit in your repo, so there is a diff.
> 
> `pip install git-filter-repo` `git filter-repo --invert-paths --force --path-glob '*patches/apt-sources*'`

Hi @ophub 
The command lines you gave me returned directly via the Github site? Or should you connect in SSH to your Count Github?
Sorry I didn't understand how to keep my fork up to date with your repository
Thanks again for everything..
Another small question about "Extlinux/Extlinux.conf" how can I test that .. I saw that the command in Extlinux.conf and in Uenv.txt are very different, are they additional or we Should we use one or the other?
good day..

**Comment by ophub** [comment]
The two files, extlinux.conf and nEnv.txt, can coexist, and extlinux.conf will be used first at startup. At present, this file is only added to the firmware of 5.10. It supports several devices such as t95 that must use this file to start. Other devices do not need this file, but its existence does not affect its use.
