### ISSUE TITLE
b860av2.1a s905l3无法从u盘进入系统

### ISSUE THREAD

**Issue by wu560130911** [ophub/amlogic-s9xxx-armbian#2679]
**Device Information | 设备信息**
 - SOC: S905L3
 - Model 中兴

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy/bullseye]

使用这个包：Armbian_24.11.0_amlogic_s905l3_bullseye_6.6.62_server_2024.11.20

**Describe the bug | 问题描述**
All issues will only remain open for one week to prioritize resolving them.
After that period, they will be closed but can still continue to be discussed in the thread.
所有的问题都只保留一周的开启状态供重点关注解决，超时将关闭，但仍然可以长期继续跟帖讨论。

刷到sd card和u盘都试过，都无法进入u盘里面的armbian系统。

盒子的完整信息如下：（使用开心电视助手获取的信息和点击u盘进入系统）
型号名称：B860AV2.1-A_4_HUNAN
系统版本：Android 4.4.2 B860AV2.1-A_1
Api等级：19
CPU架构： armeabi-v7a 四核2.02GHZ
GPU型号：Mali-450 MP八核
RAM大小：2G
Flash容量：16G
芯片代号：gxlx2_p295_2g，拆开盒子里面显示的是s905l 3
已root，android4

**Comment by cuicanmx** [comment]
同问，我的b860av2.1 u 也是s905l3也是怎么也进不去，用以前issues的安卓底包，一个卡开机，一个死活不能重启到U盘，dtb212,之类的都试了，就是进不去armbian

**Comment by shinyicn** [comment]
这些盒子可能供电问题，比较挑U, 多准备几个U盘试试

**Comment by wu560130911** [comment]
> 这些盒子可能供电问题，比较挑U, 多准备几个U盘试试
@shinyicn 有推荐的嘛？

**Comment by wu560130911** [comment]
盒子启动后在u盘写了启动日志，信息如下，求教如何解决？

--------- beginning of /dev/log/main
01-01 08:00:03.970 I/Netd    ( 3763): Netd 1.0 starting
01-01 08:00:04.140 W/InterfaceController( 3763): Warning (dlopen failed: library "/system/lib/libnetcmdiface.so" not found) while opening the net interface command library
01-01 08:00:04.400 D/appproc ( 3762): data dev ready!
01-01 08:00:04.540 D/appproc ( 3762): so init.svc.servicemanager:running
01-01 08:00:04.540 D/appproc ( 3762): dalvik.vm.heapgrowthlimit:192m
01-01 08:00:04.560 E/DirectVolume( 3864): Vold managed volumes must have auto mount point; ignoring /storage/external_storage/VIRTUAL_CDROM
01-01 08:00:04.560 E/DirectVolume( 3864): Vold managed volumes must have auto mount point; ignoring /storage/external_storage/sdcard1
--------- beginning of /dev/log/system
01-01 08:00:04.560 I/Vold    ( 3864): Vold 2.1 (the revenge) firing up
01-01 08:00:04.560 E/        ( 3864): Create mToDevSocket[7] success.

**Comment by LondyGhost** [comment]
中兴盒子大部分的安卓Bootloader都锁了 boot  from  sd功能。换其他905l3的包刷进去再试

**Comment by wu560130911** [comment]
> 中兴盒子大部分的安卓Bootloader都锁了 boot from sd功能。换其他905l3的包刷进去再试


求教程？我是已经root过了的

**Comment by LondyGhost** [comment]
> > 中兴盒子大部分的安卓Bootloader都锁了 boot from sd功能。换其他905l3的包刷进去再试
> 
> 
> 求教程？我是已经root过了的 @LondyGhost 

没什么教程，就是刷其他型号同款cpu的固件包。root也没用   机顶盒固件都是原厂固件去修改的。中兴原厂就不支持从U盘启动

**Comment by wu560130911** [comment]
找了好久都木有找到类似的包，很多都卡在开机了


| |
***@***.***
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月09日 19:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [ophub/amlogic-s9xxx-armbian] b860av2.1a s905l3无法从u盘进入系统 (Issue #2679) |

中兴盒子大部分的安卓Bootloader都锁了 boot from sd功能。换其他905l3的包刷进去再试

求教程？我是已经root过了的 @LondyGhost

没什么教程，就是刷其他型号同款cpu的固件包。root也没用 机顶盒固件都是原厂固件去修改的。中兴原厂就不支持从U盘启动

**Comment by wu560130911** [comment]
@ophub  已经成功了，可以把机型写进去了，使用cm211的包，u盘配置使用的是121进到系统里面的，安装的时候，选择的是122安装的。

可以加个特别注意：别使用sdcard进入系统，貌似哪里有问题，可以显示ip，但是无法登录，后面插读卡器就马上好了。
