### ISSUE TITLE
A95X Air F3 can't boot from eMMC or MicroSD Card

### ISSUE THREAD

**Issue by codez93** [ophub/amlogic-s9xxx-armbian#269]
Hi. I have a A95X Air F3 Box (S905X3, 4GB ram, 64GB eMMC, 100Mbps Ethernet), when i'm booting armbian (kernel 5.10.111) with USB Stick or SD Card Reader everything is ok, but with eMMC (after using command armbian-install and without USB or SD Card Reader) or MicroSD card only, device won't boot up. Please help me to boot the device with eMMC or MicroSD Card, thank so much.

**Comment by ophub** [comment]
s905x3 firmware with 5.15 kernel, armbian-insall, select 516

**Comment by codez93** [comment]
I'm using s905x3 firmware with 5.10.111 kernel because it has RTL8821CU drivers build-in, but 5.15 kernel don't have config to recompile kernel with RTL8821CU driver inside.

**Comment by ophub** [comment]
First solve the startup problem, then the driver problem. Kernel customization and updates are simple

**Comment by dinhchinh82** [comment]
@ophub as far as I know, it seems the firmware 5.10/5.15 is not compatible with X96max + or A95X F3 only 100Mbps Ethernet. I've seen several issues that users could not boot these boxes from eMMC.

I also have 1 X96 max 4+32 + 100Mb LAN and only could boot from eMMC with 5.4 kernel even it can boot from USB/TF well with 5.10 & 5.15. 

So could you support to fix it?

**Comment by boza111** [comment]
Hello. What are the latest news for Armbian and the A95X F3 Air?
I would like to boot Armbian on the exact same box. Could anyone tell me which image and DTB file I should use for best results? 

Which Armbian version is the best with this box? Does WIFi, Bluetooth and Ethernet work? How about GPU 3D acceleration?
