### ISSUE TITLE
X96MINI S905W+sv6051P

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#274]
X96MINI S905W+sv6051P

WIFI Unable to work。Is there any solution

**Comment by ophub** [comment]
no driver, no support

**Comment by dd2git** [comment]
On Coreelec (CoreELEC-Amlogic-ng.arm-19.5-Matrix_rc2-Generic.img) wifi works without problems.
Has coreelec found any special drivers?
[aus coreelec.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9226516/aus.coreelec.zip)
Can someone please test and implement?

**Comment by ophub** [comment]
CoreELEC is the Android series, which is different from the mainline kernel of armbian and cannot be used.
