### ISSUE TITLE
B860H v5

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#275]
S905x2, 2GB, MT7668RSN

![image](https://user-images.githubusercontent.com/33513626/165923556-d077cc12-a52b-477c-8291-84f0d4046869.png)
![image](https://user-images.githubusercontent.com/33513626/165923581-80d507f0-8476-4cdd-9c97-e6e6396c6743.png)
![image](https://user-images.githubusercontent.com/33513626/165923598-d08e80c4-c58b-49b4-816a-956aae6001bf.png)

U-boot log
[ubootv5.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8589931/ubootv5.txt)

I think this uboot is locked, which one i should use?

Factory u-boot
OS9 & OS10
[B860Hv5 U-Boot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8589955/B860Hv5.U-Boot.zip)

**Comment by ophub** [comment]
The 5.15 kernel does not need u-boot to boot, you first test which dtb is suitable for your device

**Comment by rapdodge** [comment]
> The 5.15 kernel does not need u-boot to boot, you first test which dtb is suitable for your device

Will look into it, but yesterday I'm trying and trying, but, i dont know why it keep loading the android 😅

Maybe this issue i will closing it

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#104-set-the-box-to-boot-from-usbtfsd

**Comment by rapdodge** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#104-set-the-box-to-boot-from-usbtfsd

Already tried it... adb shell reboot update doesn't working 😅

**Comment by ophub** [comment]
Four clicks on the version number to enable usb debugging mode

**Comment by rapdodge** [comment]
> Four clicks on the version number to enable usb debugging mode

i mean, the adb is working, but, when i type `adb shell reboot update` it didnt boot to armbian, but to android...

**Comment by ophub** [comment]
The full name of ADB is Android Debug Bridge, which is a debugging tool developed by Google for their Android system. In theory, this operation can enter the usb boot update mode. you try again…

**Comment by thunder361** [comment]
haha，I have HG680HG-FJ S905X2+2GDDR4,I forced him to upgrade to UNT413A，this one is S905L3A SOC，now armbian and openwrt is OK，maybe B860H V5 can do this one。

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

UNT413

**Comment by rapdodge** [comment]
> haha，I have HG680HG-FJ S905X2+2GDDR4,I forced him to upgrade to UNT413A，this one is S905L3A SOC，now armbian and openwrt is OK，maybe B860H V5 can do this one。

Eh, how? Can you describe that?

**Comment by thunder361** [comment]
I might make a video on YouTube

**Comment by rapdodge** [comment]
> I might make a video on YouTube

Yes please, looking forward into it
