### ISSUE TITLE
A95X F3 Air TVBox can't boot from eMMC with Focal_22.05_5.15.35 firmware

### ISSUE THREAD

**Issue by crkerx** [ophub/amlogic-s9xxx-armbian#279]
I'm using A95X F3 Air Box with Amlogic S905X3 CPU, 64GB eMMC, RAM 4GB, 100Mbps Ethernet and MT7668 Wireless. With Focal_22.05_5.15.35 firmware from USB stick, device booted successfully, but with eMMC built-in (using command armbian-install), i can't boot to device. Please help me boot to device from eMMC, thank so much.
![C22CF488-7C47-40A4-AE05-E6BA8D803A20](https://user-images.githubusercontent.com/104665791/166091673-79db6a65-a904-4a77-aaab-5ea41639da48.jpeg)
![FF0718AD-2B28-43C0-8F1E-C0EBB3BBC413](https://user-images.githubusercontent.com/104665791/166091681-16177178-cd02-4f38-81c2-8e0d8cd49879.jpeg)
![B7058758-F839-4529-9456-8F3E7121B2AA](https://user-images.githubusercontent.com/104665791/166091682-67c0ec9c-b09a-4725-a50a-adf2d6422cb6.jpeg)

**Comment by ophub** [comment]
You try to see if the firmware of the 5.10 kernel can be started, it has one more u-boot.emmc boot file

**Comment by crkerx** [comment]
I was change to Focal_22.05_5.10.112 firmware, but same problems.

**Comment by ophub** [comment]
send log

**Comment by crkerx** [comment]
I don't know how to get log.

**Comment by ophub** [comment]
`dmesg`

**Comment by crkerx** [comment]
it got stuck:
![9FA775B8-3F0E-41A4-8DF4-CD1B020BCD95](https://user-images.githubusercontent.com/104665791/166108752-4e5ef9a6-0373-42c1-bba3-478fb2f5d7bf.jpeg)

**Comment by ophub** [comment]
FDTFILE="meson-sm1-x96-max-plus-100m.dtb
meson-sm1-x96-max-plus.dtb

**Comment by dinhchinh82** [comment]
> im got stuck like this:

Have you boot from eMMC successfully with kernel 5.10 or 5.15 yet?

**Comment by crkerx** [comment]
> @[crkerx](https://github.com/crkerx)
> 
> > im got stuck like this:
> 
> Have you boot from eMMC successfully with kernel 5.10 or 5.15 yet?

not yet, bro.

**Comment by crkerx** [comment]
> `meson-sm1-x96-max-plus-100m.dtb` `meson-sm1-x96-max-plus.dtb`
> 
> The change in writing emmc is to change the dtb. You modify `/boot/uEnv.txt` and use these two dtb to test it separately

i'm tested, it doesn't work.
