### ISSUE TITLE
[Request] Linux Header Current & Linux Image Current

### ISSUE THREAD

**Issue by hostkit** [ophub/amlogic-s9xxx-armbian#28]
Hai dude,

Please build linux-header-current and linux-image-current for your imange, it help for compile driver and another

Thanks

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

**Comment by hostkit** [comment]
so we must do this?

git clone --depth 1 https://github.com/ophub/amlogic-s9xxx-armbian.git
make headers_install ARCH=arm64 INSTALL_HDR_PATH=/usr/header

its big source?
where make file location?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/header
The latest kernel version, flippy shared the header file.

**Comment by ophub** [comment]
untar the kernel.

```
make mrproper
make ARCH=arm64 headers_check
make ARCH=${CLFS_ARCH} INSTALL_HDR_PATH=/usr/header headers_install
```

**Comment by ophub** [comment]
Download the latest [armbian-update](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-update) script: 

In the latest 4 kernels (5.10.80 / 5.14.20 / 5.15.3 / 5.4.160), flippy shared the header files, I updated the script to support direct installation of the header files.
```
wget -P /usr/sbin https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/files/usr/sbin/armbian-update && chmod +x /usr/sbin/armbian-update
armbian-update 5.4.160
```
