### ISSUE TITLE
gt-king-pro.dtb or gt-king-pro-rev_a.dtb

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#280]
Hi @ophub 
I'm coming back towards you,
I forked your repository and so I can compile the kernel with kernel.org as source. https://github.com/MX10-AC2N/amlogic-s9xxx-armbian/releases/tag/kernel_5.15.36_5.17.5
So I manage to boot on my GT-king pro (SN:SA9H...) using u-boot.ext (gtking-pro.bin) from an SD card kernel 5.15.y
I can start with gt-king-pro.dtb but my tv remains black screen after the message "starting kernel", I still have SSH access and the system is stable..
But I can also start with gt-king-pro-rev_a.dtb and with this one I keep my screen active on my tv until login.. but I have some kernel panics or system freezes..
Here is the dmesg with gtking-pro-rev_a.dtb => https://paste.yunohost.org/aburibihaq.md
Here is the dmesg with gtking-pro.dtb => https://paste.yunohost.org/ugapitoquy.md
I tried adding video=HDMI-A-1:1920x1080:32@60 in /boot/uEnv.txt but it doesn't change anything..
If you have any idea thanks again..
A suggestion would it be possible to modify the triggering of the led in order to have a heartbeat rather than default directly in the .dtb file
I can also confirm that kernel 5.15.y compiled from unifreq works fine on USB media and boots fine even without u-boot.ext but not on SD card, that's another matter but that's i use armbian on sd card and android on emmc, and my external drives on usb ports, all usb ports are used 3 external drives and the last usb for remote control or keyboard/mouse..
Last thing I'm looking for a way to be able to launch a command that will allow to restart the box under android without having to remove my sd-card (as is done under coreelec for example "reboot to android") if you have an idea for that too..
Thank you again for everything.

**Comment by ophub** [comment]
Previous users of Octopus Planet devices also reported that ssh is accessible when using the 5.15 kernel, but the screen is black. But in 5.10 and 5.17 kernel the screen display is normal. You try other kernels and choose a suitable one.
unifreq modifies the boot order and name of emmc/usb/sd/tf cards in the kernel. And added some optimization patches for amlogic devices.

**Comment by MX10-AC2N** [comment]
> The sn of my gtk pro is 6B9HH, both dtb can be used normally

Have you tried boot on sd-card ?

**Comment by MX10-AC2N** [comment]
5.17.5 kernel compiled from kernel.org boot fine on sd-card with u-boot.ext but same issue of balck screen after "starting kernel"
with gtking-pro.dtb, 
With gtking-pro-rev_a.dtb screen display is ok after "starting kernel"
I can also use gtking-pro-rev_a-oc.dtb and with this I can config cpufrequtils to 1.99GHz, so nice 2Ghz seems work fine, after I switch to gtking-pro.dtb and 2Ghz work again so we can adjust gtking-pro.dtb to use this 1.99GHz..

**Comment by ophub** [comment]
With the oc logo is the overclocked version.
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/default/cpufrequtils
More CPU call patterns and frequencies can be set in /etc/default/cpufrequtils, you can check the official documentation to see what strategy you like.

**Comment by MX10-AC2N** [comment]
```
/sys/devices/system/cpu/cpufreq$ ls
policy0  policy2  schedutil
/sys/devices/system/cpu/cpufreq/policy2$ cat scaling_available_frequencies
100000 250000 500000 667000 1000000 1200000 1398000 1512000 1608000 1704000 1800000 1908000
/sys/devices/system/cpu/cpufreq/policy0$ cat scaling_available_frequencies
100000 250000 500000 667000 1000000 1200000 1398000 1512000 1608000 1704000 1896000 1992000
```
After starting with the gtking-pro-rev_a-oc.dtb I was able to configure the 2Ghz in max value which is not accessible when I start with gtking-pro.dtb (limited to 1.9Ghz in max value)
After doing that I can go back to gtking-pro.dtb and the max value for the cpu remained at 2Ghz, I can see it running at 1.99GHz in htop, but if I go into armbian-config I can only get 1.9 GHz in max value for the CPU config.. That's why I thought of some modifications directly in the gtking-pro.dtb file
Thanks again @ophub

**Comment by MX10-AC2N** [comment]
Hi @ophub 
Just to share, I managed to get signal on my TV with gtking-pro.dtb by adding in /boot/uEnv.txt `video=card0-HDMI-A-1:D`
but after a reboot command I was again with loss of hdmi signal just at the time of "starting kernel"
I tested the gtking-pro.dtb file taken from linux-image-current-arm64, I can also boot with this one.. The hdmi signal was correct but after a reboot same problem of black screen no hdmi signal on my tv after "starting kernel".. 
I search but I can't really find..
What I did to grab the dtb from linux-image-current-arm64
```
sudo aptitude install linux-image-current-arm64 -d  ==> for download .deb without install
cd /var/cache/apt/archives/   ==> here is the .deb downloaded with apt
dpkg -x linux-image-current-arm64.deb /tmp/linux-arm64   ==> extract .deb to specified directory
cd /tmp/linux-arm64   ==> here there is all of linux-image-current-arm64 
cd /tmp/linux-arm64/usr/lib/linux-image-5.15.25-arm64/amlogic  ==> here there is amlogic's dtb
cp meson-g12b-gtking-pro.dtb /boot/dtb/meson-g12b-gtking-pro-5.15.25-arm64.dtb   ==> save .dtb in /boot/dtb with another name
modify uEnv.txt for this .dtb and reboot..
```

**Comment by ophub** [comment]
5.4/5.10/5.15/5.17 series of kernels have a try
