### ISSUE TITLE
X96Max+ (ip1001m) EMMC boot problem

### ISSUE THREAD

**Issue by psergeevich** [ophub/amlogic-s9xxx-armbian#282]
I have installed Armbian on EMMC, and it's does not boot when some device connected into USB, for example, USB sound card or USB wireless keyboard-mouse dongle. The first message on the screen about problem with ethernet adapter.
![USB_dongle](https://user-images.githubusercontent.com/104202871/166113427-3068c6ca-0691-49e4-9ad5-c068fc457e79.jpg)

If all USB ports empty, device has boot successfully. At the first stage ethernet adapter detected:
![stage1](https://user-images.githubusercontent.com/104202871/166113453-94bad36c-d287-426a-9954-26b215a3c244.jpg)

...but at the next stage it did not detect:
![stage2](https://user-images.githubusercontent.com/104202871/166113459-10451718-3748-4a2f-bfe0-1520eff84656.jpg)

When it boot from microSD, the same problems:
- unable boot when some USB-device (not storage) present
- after boot with empty USB-ports PHY does not work

Boot from USB-storage is normal, PHY works. Could you repair boot from EMMC or microSD?
[boot_logs.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8597346/boot_logs.zip)

**Comment by ophub** [comment]
Which version of the firmware was used, and what serial number did you choose to install?
Inserting the device into the USB (OTG) port will enter the update mode, this port must be empty

**Comment by psergeevich** [comment]
> Which version of the firmware was used, and what serial number did you choose to install?

I have installed X96-Max+-(IP1001M-phy) firmware. No serial number was requested. Here is the install dialog:
```
...
Please Input ID: 503
Input Box ID: [ 503 ]
FDTFILE: [ meson-sm1-x96-max-plus-ip1001m.dtb ]
UBOOT_OVERLOAD: [ u-boot-x96maxplus.bin ]
K510: [ 0 ]
--------------------------------------------
Please select the type of file system:
1. ext4
2. btrfs
--------------------------------------------
Please Input ID: 1
Input Type ID: [ 1 ]
The type of file system: [ ext4 ]
...
```

> Inserting the device into the USB (OTG) port will enter the update mode, this port must be empty

I agree if USB-storage installed. But if installed not bootable device, it is logical to boot from EMMC

**Comment by ophub** [comment]
My device is used for writing emmc. But usb mouse and keyboard I don't have usb interface with OTG function. I can boot normally from emmc and use the mouse and keyboard inside the desktop system.

don't plug usb on the usb port of the OTG

**Comment by psergeevich** [comment]
My X96Max+ has 2 USB-ports (type A). In the description of the device, the OTG function is not declared for them. I connect wireless keybord-mouse dongle to each of this ports, but in both cases it does not boot.
And the next problem: when device boot from emmc, ethernet interface (IP1001M) does not work

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/258
