### ISSUE TITLE
Memory problem on X96 Max+ A100 with kernel-5.15.36-flippy-72+o

### ISSUE THREAD

**Issue by prakai** [ophub/amlogic-s9xxx-armbian#283]
After I upgraded my X96 Max+ (A100) 4GB/64GB with kernel-5.15.36-flippy-72+o/Armbian_22.05.0_Aml_s905x3_focal_5.15.36_2022.04.30.2301, My box only found 1GB of memory. I tried reinstalling the OS and the problem is the same.

I have 2 boxes and encountered the same problem.

With dtb: meson-sm1-sei610.dtb
 - Boot success
 - Ethernet: 100Mbps
 - Wi-Fi works without customization
 - Bluetooth works without customization
 
With dtb: meson-sm1-x96-max-plus*.dtb
 - Not boot
 
# dmesg | more
![image](https://user-images.githubusercontent.com/25915163/166133754-64a3d80b-11f0-4150-a91f-06e169307b25.png)

# htop
![image](https://user-images.githubusercontent.com/25915163/166133775-19425d0c-8187-4d93-a2d4-2db0dc97d2c7.png)

**Comment by ophub** [comment]
`armbian-update 5.10.113`

**Comment by prakai** [comment]
Everything works perfectly. Thank you very much.

![image](https://user-images.githubusercontent.com/25915163/166134703-c9ed4201-dd3f-4916-8c66-e6805bfda344.png)

**Comment by ophub** [comment]
ok

**Comment by dinhchinh82** [comment]
@prakai have you tried to boot from eMMC yet?

I have same hardware as your but unable to boot from eMMC with kernet 5.10/5/15. Only could boot from eMMC if using kernel 5.4.
Thank you.
