### ISSUE TITLE
Add a list of devices and dtbs with working wifi or bluetooth

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#284]
The most common hardware issue on these TV boxes is that the wifi and bluetooth often don't work. It would be good if this project had a list of which TV boxes have working wifi and/or bluetooth and using which dtb file.

Do you know of any TV boxes with wifi/BT that works under this distro @ophub ? I've got a few AMlogic S905X3 TV boxes but wifi doesn't work on any of them under s9xxx Armbian, although I have had working wifi on them using Manjaro. If you don't know of any, please leave this ticket open for a week or so and I bet someone will see it who has got working wifi then we can add their TV box to a compatibility list to get it started.

This info could be added to the readme as a couple extra columns added to the firmware table or maybe it deserves a separate document linked to from the README?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/config_correspondence_of_amlogic_s9xxx_tv_box.md

**Comment by danboid** [comment]
Ah cool! I'd not seen that page but I think the model info needs more details. For example, I've got both an X96 Max+ and two different X96 Air boxes. That table says wifi should work on both but it doesn't work on either but that's because there are literally at least 8 different versions of both the X96 Air and the X96 Max plus, most with different wifi/bluetooth chips.

If I spot any missing details I can add, I'll make a PR.

**Comment by ophub** [comment]
ok
