### ISSUE TITLE
T95 success (except WiFi)

### ISSUE THREAD

**Issue by chris4git** [ophub/amlogic-s9xxx-armbian#285]
Hi @ophub ,

thanks for your work !
If you want to add a new box as supported, here is mine :
Name : Sunvell T95
Soc : S905x
Infos :

- (https://www.gearbest.com/tv-box-mini-pc/pp_268277.html)
- (http://specdevice.com/showspec.php?id=76fa-8e07-0033-c5870033c587)

tested with Armbian_22.05.0_Aml_s905x_focal_5.15.32_2022.03.30.1703.img
Boot :
- u-boot.ext : u-boot-s905x-s912.bin
- replaced uEnv.txt by extlinux/extlinux.conf
- dtb : meson-gxl-s905x-p212.dtb

LED display configuration : t95m-s905x-vfd.conf (or meson-gxl-s905x-t95m.conf)

WiFi not working (chip SCI S9082C, Android module : 9082xs/TLL901x)

Chris

**Comment by ophub** [comment]
Share your t95m-s905x-vfd.conf file and a photo of the LED screen lighting up

**Comment by chris4git** [comment]
HI,

it's not my file but
(https://github.com/arthur-liberman/vfd-configurations/blob/master/t95m-s905x-vfd.conf) or
(https://github.com/LibreELEC/linux_openvfd/blob/master/conf/meson-gxl-s905x-t95m.conf)
Photo with LED display on :
![20220507_081936-01](https://user-images.githubusercontent.com/23280864/167242302-733fef6e-d9a3-4270-9371-cc2e5ee48e00.jpeg)

The image Armbian_22.05.0_Aml_s905x_focal_5.15.32_2022.03.30.1703.img don't boot on USB with uEnv.txt 

Chris

**Comment by ophub** [comment]
Based on your feedback, I have added the t95 device, today's repackaged firmware contains the installation information for this device, you can test the installation and LED display is correct.
Feedback the results after the test. thanks

**Comment by dinhchinh82** [comment]
@chris4git have you tried to install your box into eMMC yet? 
I have 1 S905x box but it only could boot from USB/TF and unable to boot from eMMC (tried all kernel 5.4, 5.10, 5.15).

Thank you.

**Comment by chris4git** [comment]
Hi @dinhchinh82, no I haven't tried to install on eMMC. I'm afraid to brick it ;-)
Only boot from TF or USB till now.
Is WiFi supported on your box ?

**Comment by gsbenjamin** [comment]
Model:       T95N Mini MX+
DTB:           meson-gxl-s905w-tx3-mini
Firmware:   Armbian_24.5.0_amlogic_s905x-t95_bullseye_6.1.87_server_2024.04.20.img
EMMC:       Success. Boots from internal EMMC with no SD card inserted
WiFi:           **NOT** Working
Primary Use:  Octoprint

Device works great. Anything I can do to get the internal WiFi detected?

**Comment by chris4git** [comment]
Hi @gsbenjamin 
it seems the wifi chip (S9082C) is a variant of rtl8189es so is potentially supported !
Cf [(https://github.com/ChalesYu/rtl8822bs-aml?tab=readme-ov-file)]
Let us know if you try...

Chris
