### ISSUE TITLE
4K & UHD HDMI output broken on X96 Max+ with 5.15.36 kernel

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#286]
First, the good news is that it seems wifi is working for my X96 Max+ under Jammy. It didn't work under the older Focal images but 4K HDMI output did work. 4K output isn't working at all with the current jammy image on my X96 Max+.

I've noticed 2 issues with Armbian_22.05.0_Aml_s905x3_jammy_5.15.36_2022.04.30.2044.img. The minor issue is that the login message (the ASCII art text printed after you login) says its the Lepotato image instead of the s905x3 image, but the more pressing issue is that HDMI output is no longer working on my 4K and UHD displays but the X96 Max+ dtb used to work fine @4K under the older focal images.

On my 4K display, I don't see the first (U-boot?)  screen or the systemd init stuff so its unusable. On the UHD display I do see the first screen of text but when it starts booting properly... nothing. On a 1080P display I see both boot screens then on my crappy old VGA/DVI monitor I don't see the first boot screen but I do see the proper systemd boot messages and it otherwise works.

**Comment by ophub** [comment]
Try changing the 5.10 kernel
`armbian-update 5.10.113`

**Comment by danboid** [comment]
Yes, 4K and UHD HDMI output work with the 5.10 kernel thankfully.

**Comment by ophub** [comment]
In the /boot directory of 5.15. Copy the corresponding u-boot as u-boot.ext/u-boot.emmc, it should also work, you try

**Comment by ophub** [comment]
```
cp -f /boot/u-boot-x96maxplus.bin /boot/u-boot.ext
cp -f /boot/u-boot-x96maxplus.bin /boot/u-boot.emmc
chmod +x /boot/u-boot.ext /boot/u-boot.emmc
sync
reboot
```

**Comment by danboid** [comment]
No, running those commands hasn't fixed 4K output for 5.15.36.

**Comment by ophub** [comment]
The armbian-update script will delete the u-boot file. After you `armbian-update 5.15.36` the kernel and `reboot`, `ssh` to execute the above `copy` command, and then `reboot`.

**Comment by danboid** [comment]
That's what I did and it made no difference.
