### ISSUE TITLE
 为什么没有章鱼星球和斐讯N1的armbian系统？

### ISSUE THREAD

**Issue by zzusec** [ophub/amlogic-s9xxx-armbian#288]
小白一个，求一个章鱼的刷机教程

**Comment by ophub** [comment]
章鱼：[Armbian_22.05.0_Aml_s912_focal_5.10.113_2022.04.30.2323.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2022.04.30.2356/Armbian_22.05.0_Aml_s912_focal_5.10.113_2022.04.30.2323.img.gz)

N1：[Armbian_22.05.0_Aml_s905d_focal_5.10.113_2022.04.30.2333.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2022.04.30.2356/Armbian_22.05.0_Aml_s905d_focal_5.10.113_2022.04.30.2333.img.gz)
