### ISSUE TITLE
请问这里发布的镜像和armbian官网发布的镜像有何区别？

### ISSUE THREAD

**Issue by bluehj777** [ophub/amlogic-s9xxx-armbian#289]
比如以khadas vim3为例，armbian官网可以下载
https://redirect.armbian.com/khadas-vim3/Bullseye_current
这里也有针对vim3的镜像发布，请问有何主要区别？

**Comment by ophub** [comment]
khadas vim3是开发板，emmc和bootloader都是开放的，所以这个设备和ODROID-N2开发板官方都支持。
除这2个设备外，其他设备都是官方不支持的。
我改了他们的启动方式和内核。

**Comment by bluehj777** [comment]
> khadas vim3是开发板，emmc和bootloader都是开放的，所以这个设备和ODROID-N2开发板，这2款设备官方都支持，你下载官方的固件也可以使用。 除这2个设备外，其他设备都是官方不支持的。 我改了他们的启动方式和内核，让更多amlogic芯片的设备可以使用armbian。
谢谢，明白了。
如果是khadas vim2的话，是下载你这里的
Armbian_22.05.0_Aml_s912_jammy_5.10.113_2022.04.30.2104.img.gz吧？

**Comment by ophub** [comment]
对
