### ISSUE TITLE
Can't using dkms to builds driver in focal_5.10.113 firmware

### ISSUE THREAD

**Issue by crkerx** [ophub/amlogic-s9xxx-armbian#290]
Hi. i'm using Focal_5.10.113 firmware, when i'm build RTL8821CU driver from [https://github.com/brektrou/rtl8821CU](url) using dkms, it show error like this, pls help me:
`Error! Your kernel headers for kernel 5.10.113-meson64-dev cannot be found.
Please install the linux-headers-5.10.113-meson64-dev package,
or use the --kernelsourcedir option to tell DKMS where it's located
Error! Your kernel headers for kernel 5.10.113-meson64-dev cannot be found.
Please install the linux-headers-5.10.113-meson64-dev package,
or use the --kernelsourcedir option to tell DKMS where it's located
Finished running dkms install steps.
`

**Comment by ophub** [comment]
The headers files in the kernel is installed in the `/use/local/include` directory.

**Comment by crkerx** [comment]
> The headers files in the kernel is installed in the `/use/local/include` directory.

I'm specified kernel source path for dkms using --kernelsourcedir=/use/local/include, but same errors.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/ddb5440c1b2e0b7002753fe51c45db03fa44cc44/compile-kernel/tools/config/config-5.10.112#L2766

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel
