### ISSUE TITLE
S9082C/9083/9088 family WiFi chip support ?

### ISSUE THREAD

**Issue by chris4git** [ophub/amlogic-s9xxx-armbian#291]
Hi,
it seems CoreElec has recently got kernel drivers for these chips : https://github.com/CoreELEC/smartchip (cf https://discourse.coreelec.org/t/wifi-problem-on-tanix-tx3-mini/9547/27).

Any chance to test them on S9xx Armbian ?

Chris

**Comment by ophub** [comment]
Many devices with the same name use different chip solutions. It cannot be said that the devices under a soc are all this wireless chip. Your question cannot be answered.

**Comment by chris4git** [comment]
My box use S9082C which has been used in many boxes.
Is it possible to compile the CoreElec modules in your kernel  ?

**Comment by ophub** [comment]
CoreElec is Android, armbian uses the mainline kernel, not universal
