### ISSUE TITLE
海美迪H7四代提示网络失败

### ISSUE THREAD

**Issue by EVEFans** [ophub/amlogic-s9xxx-armbian#292]
求教，我打算安装在海美迪四代电视盒子上
在使用Armbian_22.05.0_Aml_s912_jammy_5.10.113_2022.04.30.2104.img刷机是提示网络失败，失败信息如下：
meson8b-dwmac c9410000.ethernet  eth0：PHY [0.2009087f:00] driver  [Generic PHY] (irq=POLL)
meson8b-dwmac c9410000.ethernet：Failed to reset the dma
meson8b-dwmac c9410000.ethernet eht0：stmmac_hw_setup：DMA engine initialization failed
meson8b-dwmac c9410000.ethernet eht0：stmmac_open：Hw setup failed
VDDA0_3V3：disabling
Failed to start Raise network interfaces

**Comment by ophub** [comment]
末知设备，默认的dtb不适合你的设备，无法驱动。

你试试同系列的其他dtb

**Comment by EVEFans** [comment]
> 末知设备，默认的dtb不适合你的设备，无法驱动。
> 
> 你试试同系列的其他dtb

好的，我试试其他的

**Comment by EVEFans** [comment]
你好，我手上有官方的卡刷包，但是我无法提取dtb.img，你可以帮忙提取出来吗？
https://pan.baidu.com/s/12Tx2vY-ljCi_TKiiNoDrjw

**Comment by ophub** [comment]
安卓不是使用的主线内核，所以安卓的dtb没法在armbian系统里使用
