### ISSUE TITLE
HK1 box, ethernet not working

### ISSUE THREAD

**Issue by fs30000** [ophub/amlogic-s9xxx-armbian#294]
Hello,

I'm using Armbian_22.05.0_Aml_s905x3_jammy_5.15.36_2022.05.07.1814.img.gz for this HK1 box amlogic S905X3. Ethernet is not working. I also tried the image with the 5.10 kerel and doesn't boot. Any ideas please?

**Comment by ophub** [comment]
What is a network card chip

**Comment by dbilee** [comment]
I met the same problem on HK1 with `Armbian_22.05.0_Aml_s905x3_jammy_5.10.113_2022.04.30.2046.img.gz`.  
I can see the eth0 by ifconfig, but no ip can be auto configured, and use ifconfig down/up the get `SIOCSIFFLAGS: Connection timed out`, ifconfig shows `device interrupt 14`, the dmesg shows:
```
meson8b-dwmac ff3f0000.ethernet eth0: PHY [0.0:00] driver [Generic PHY] (irq=POLL)
meson8b-dwmac ff3f0000.ethernet: Failed to reset the dma
meson8b-dwmac ff3f0000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
meson8b-dwmac ff3f0000.ethernet eth0: stmmac_open: Hw setup failed
```
No ethernet model name can be found by command, but according to some pictures online, it should be RTL8211.
@ophub any help is appreciated, thanks.

**Comment by ophub** [comment]
Take a picture of the network card chip and send it. There are multiple variants of this device.

**Comment by dbilee** [comment]
Thank you, I found it is JL2101(some problem with my camera), the box won't boot with 5.15 kernel ,just repeat flashing the hk1 logo, so I use 5.10, any workaroud?

**Comment by ophub** [comment]
Do as above

**Comment by dbilee** [comment]
I tried and finally it only worked on `5.4.191-meson64-dev` which is the same as #247 , Thanks for your help

**Comment by fs30000** [comment]
Guys, i'll return this board. Too much pain and time consuming to make it work. I just want it for a micro server that i need for other stuff. Cannot afford spending so much time.
