### ISSUE TITLE
请问可以添加对S905L3芯片的支持吗？

### ISSUE THREAD

**Issue by ChenKE404** [ophub/amlogic-s9xxx-armbian#296]
如题，或者已经可以支持？那该用哪个dtb？
手头有一个S905L3芯片的盒子，但苦恼于没有对应芯片的Armbain可用。
谢谢。

**Comment by ophub** [comment]
不支持

**Comment by milosz20222** [comment]
o大，我问的问题也是这个芯片，S905L3，机器是e900v22d，我折腾了半天的dtb，系统就是引导不了。看不到跑马灯和花屏界面，等于是没有引导armbian。
