### ISSUE TITLE
armbian-tf有问

### ISSUE THREAD

**Issue by wrisin** [ophub/amlogic-s9xxx-armbian#297]
root@armbian:~# armbian-tf
-bash: armbian-tf: command not found
第一次执行选择E后，各分区并未扩容，再次执行就是上面的提示了。
用的是Armbian_22.05.0_Aml_s905d_jammy_5.15.38_2022.05.09.2215.img
机器是N1盒子。

**Comment by ophub** [comment]
```
wget -c https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-tf -O /usr/sbin
sudo chmod +x /usr/sbin
```
重新下载下

这个文件执行一次后会自动删除。
执行时需要在线联网安装分区软件包，你在执行前把盒子接入互联网。
