### ISSUE TITLE
hdmi/av sound always busy.

### ISSUE THREAD

**Issue by navigos** [ophub/amlogic-s9xxx-armbian#299]
Hello, 
I'm trying to get audio through the av or hdmi output, but when issuing the speaker-test command, I get the following output:

root@armbian:~# speaker-test
_speaker-test 1.2.2
Playback device is default
Stream parameters are 48000Hz, S16_LE, 1 channels
Using 16 octaves of pink noise
Playback open error: -16,Device or resource busy_

The same goes for using the -c -l or -D options.

[amixer.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8670273/amixer.txt)
[aplay.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8670275/aplay.txt)

I apologize if I missed something trivial.
ps: I'm using the non-desktop version, with hardware #247.

I appreciate all the help.

**Comment by danboid** [comment]
I believe only HDMI audio (and USB audiio) work on the x96 Max+.

If you try:

```
speaker-test -c 6 -t wav
```

You should hear sound coming through HDMI after its tried the (non-working) onboard audio.

**Comment by navigos** [comment]
> I believe only HDMI audio (and USB audiio) work on the x96 Max+.
> 
> If you try:
> 
> ```
> speaker-test -c 6 -t wav
> ```
> 
> You should hear sound coming through HDMI after its tried the (non-working) onboard audio.

It doesn't make any sound on the hdmi output or with the usb speaker.

I tried to get the output for **pacmd list-sinks**, but it returns this error.
_No PulseAudio daemon running, or not running as session daemon._

So I used **pulseaudio -D --system**.

_W: [pulseaudio] main.c: Running in system mode, but --disallow-exit not set._
_W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set._
_N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode._
_N: [pulseaudio] main.c: Running in system mode, forcibly disabling exit idle time._

When running: **speaker-test -c 6 -t wav**

_speaker test 1.2.2_

_Playback device is default_
_Stream parameters are 48000Hz, S16_LE, 6 channels_
_WAV file(s)_
_ALSA lib pulse.c:242:(pulse_connect) PulseAudio: Unable to connect: Access denied_

_Playback open error: -111,Connection refused_


Now **pacmd list-snks** returns:

* 1 sink(s) available.
index: 0
name: <auto_null>
driver: <module-null-sink.c>
flags: DECIBEL_VOLUME LATENCY DYNAMIC_LATENCY
state: SUSPENDED
suspend cause: IDLE
priority: 1000
volume: front-left: 65536 / 100% / 0.00 dB, front-right: 65536 / 100% / 0.00 dB
balance 0.00
base volume: 65536 / 100% / 0.00 dB
volume steps: 65537
muted: no
current latency: 0.00 ms
max request: 375 KiB
max rewind: 375 KiB
monitor source: 0
sample spec: s16le 2ch 48000Hz
channel map: front-left,front-right
stereo
used by: 0
linked by: 0
configured latency: 0.00 ms; range is 0.50 .. 2000.00 ms
module: 10
properties:
device.description = "Dummy Output"
device.class = "abstract"
device.icon_name = "audio-card"

I'm forgetting something?

**Comment by danboid** [comment]
"It doesn't make any sound on the hdmi output or with the usb speaker."

Does your USB speaker work under any other Linux distro, on the PC or RPi etc?

If your USB speaker isn't working on your X96 but it does work on your PC then it sounds like either you've misconfigured ALSA or PA or you have muted channels.
