### ISSUE TITLE
Build an image for s905x2 and s912

### ISSUE THREAD

**Issue by yx93e4drbc3fajim4d7g** [ophub/amlogic-s9xxx-armbian#3]
I guess you removed this two SOC models due to a limit of Github Action. I forked your repo and modified the action file, but failed to run due to time limit. Could you provide the suitable kernel version or build an image for these models if you can?

**Comment by ophub** [comment]
Uploading too many releases at one time will exhaust the machine. Change to the `soc` you want.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/512a46e87c7149d812aa6fab01a54205d87c84fe/.github/workflows/build-armbian.yml#L79

`sudo ./make s912_s905x2`

**Comment by yx93e4drbc3fajim4d7g** [comment]
That means these models support latest kernel version. I will try again. Thanks.
