### ISSUE TITLE
unable change time zone and timedatectl

### ISSUE THREAD

**Issue by hostkit** [ophub/amlogic-s9xxx-armbian#30]
Failed to query server: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms)

**Comment by hostkit** [comment]
i thinks this error same case because when using another armbian not showing error
`Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; omv-salt deploy run --no-color timezone 2>&1' with exit code '1': armbian: ---------- ID: configure_timezone Function: file.managed Name: /etc/timezone Result: True Comment: File /etc/timezone is in the correct state Started: 08:49:18.663243 Duration: 210.077 ms Changes: ---------- ID: set_timezone Function: timezone.system Name: Asia/Jakarta Result: False Comment: An exception occurred in this state: Traceback (most recent call last): File "/usr/lib/python3/dist-packages/salt/state.py", line 2172, in call *cdata["args"], **cdata["kwargs"] File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__ return self.loader.run(run_func, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as return _func_or_method(*args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper return f(*args, **kwargs) File "/usr/lib/python3/dist-packages/salt/states/timezone.py", line 73, in system if __salt__["timezone.get_hwclock"]() == "localtime": File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__ return self.loader.run(run_func, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs) File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as return _func_or_method(*args, **kwargs) File "/usr/lib/python3/dist-packages/salt/modules/timezone.py", line 402, in get_hwclock ret = _timedatectl() File "/usr/lib/python3/dist-packages/salt/modules/timezone.py", line 57, in _timedatectl raise CommandExecutionError(msg) salt.exceptions.CommandExecutionError: timedatectl failed: Failed to query server: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms) Started: 08:49:18.885776 Duration: 25096.375 ms Changes: Summary for armbian ------------ Succeeded: 1 Failed: 1 ------------ Total states run: 2 Total run time: 25.306 s`

**Comment by ophub** [comment]
Changing the Timezone by Creating a Symlink. you can change the timezone by symlinking /etc/localtime to the timezone in the /usr/share/zoneinfo directory. Delete the current /etc/localtime file or symlink:

`sudo rm -f /etc/localtime`

Identify the timezone you want to configure and create a symlink :

`sudo ln -s /usr/share/zoneinfo/Europe/Ljubljana /etc/localtime`

You can confirm the change either by listing the `/etc/localtime` file or issuing the `date` command.

**Comment by hostkit** [comment]
timedatectl list-timezones

Failed to request list of time zones: Failed to activate service 'org.freedesktop.timedate1': timed out (service_start_timeout=25000ms)

i thinks same service has problems

**Comment by ophub** [comment]
![Snip20211121_1](https://user-images.githubusercontent.com/68696949/142760978-eda6abcf-b15c-4d19-880a-2864323f9a91.png)
