### ISSUE TITLE
s905l3a使用5.10内核固件

### ISSUE THREAD

**Issue by cnmyn** [ophub/amlogic-s9xxx-armbian#302]
Armbian_22.05.0_Aml_s905l3a_jammy_5.15.38_2022.05.11.2237.img.gz
Armbian_22.05.0_Aml_s905l3a_bullseye_5.15.38_2022.05.10.1957.img.gz
使用以上两个版本(其他未测)，网卡无法使用，提示如下图显示，路由器上的网卡灯也不亮
![20220512095502](https://user-images.githubusercontent.com/35393836/167976780-fe488147-11ae-4943-b612-49108dcdaf73.jpg)

**Comment by ophub** [comment]
你是什么设备

**Comment by cnmyn** [comment]
> 
E900V22D，默认的安卓系统启动，网卡没问题，正常用

**Comment by ophub** [comment]
只支持我链接里的那一款，不支持其他

**Comment by cnmyn** [comment]
> 只支持我链接里的那一款，不支持其他
我用了你的openwrt正常使用，想换armbian，网卡用不了

**Comment by ophub** [comment]
<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">简要参数</h3>

项目 | 详情
-- | --
SoC | S905L3A-B 和 S905L3A两种CPU S905L3A-B盒子底部标有Dolby Audio杜比音效标志，两种线刷救砖时有区别，卡刷无区别
CPU | 4x Arm Cortex-A53 @ 1.80 GHz
GPU | Mali-G31 MP2 with OpenGL ES 3.2, Vulkan 1.0, and OpenCL 2.0
Video Decoding | H.265(HEVC), VP9, AVS2 up to 4Kp75 10bit, H.264 up to 4Kp30（VP9解码被阉割）
Video Encoding | H264 H265 up to 1080p
RAM | 2G DDR4（Rayson RS512M32LM4 D2BDS）
ROM | 8G eMMC5.1（SGM8000C-S27B8G）
无线蓝牙芯片 | 紫光UWE5621DS，双天线
无线 | 2.4G、5G
蓝牙 | BT5.0
有线网络 | 10/100M
HDMI | 2.0

<h3 dir="auto" style="box-sizing: border-box; margin-top: 24px; margin-bottom: 16px; font-size: 1.25em; font-weight: 600; line-height: 1.25; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a id="user-content-拆机照片" class="anchor" aria-hidden="true" href="https://github.com/Calmact/e900v22c#%E6%8B%86%E6%9C%BA%E7%85%A7%E7%89%87" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color; float: left; padding-right: 4px; margin-left: -20px; line-height: 1;"><svg class="octicon octicon-link" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.775 3.275a.75.75 0 001.06 1.06l1.25-1.25a2 2 0 112.83 2.83l-2.5 2.5a2 2 0 01-2.83 0 .75.75 0 00-1.06 1.06 3.5 3.5 0 004.95 0l2.5-2.5a3.5 3.5 0 00-4.95-4.95l-1.25 1.25zm-4.69 9.64a2 2 0 010-2.83l2.5-2.5a2 2 0 012.83 0 .75.75 0 001.06-1.06 3.5 3.5 0 00-4.95 0l-2.5 2.5a3.5 3.5 0 004.95 4.95l1.25-1.25a.75.75 0 00-1.06-1.06l-1.25 1.25a2 2 0 01-2.83 0z"></path></svg></a>拆机照片</h3><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer" href="https://github.com/Calmact/e900v22c/blob/main/media/b46dbe4fa0c272f863daf96a11e90f9e.png" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><img src="https://github.com/Calmact/e900v22c/raw/main/media/b46dbe4fa0c272f863daf96a11e90f9e.png" alt="descript" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a><a target="_blank" rel="noopener noreferrer" href="https://github.com/Calmact/e900v22c/blob/main/media/58bfe24c3023b9aaac8380aceebbf39f.png" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><img src="https://github.com/Calmact/e900v22c/raw/main/media/58bfe24c3023b9aaac8380aceebbf39f.png" alt="descript" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a></p><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a target="_blank" rel="noopener noreferrer" href="https://github.com/Calmact/e900v22c/blob/main/media/30356596d124546630b303cc27a4ab03.png" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><img src="https://github.com/Calmact/e900v22c/raw/main/media/30356596d124546630b303cc27a4ab03.png" alt="descript" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a><a target="_blank" rel="noopener noreferrer" href="https://github.com/Calmact/e900v22c/blob/main/media/14194644bc4d8ca5fe3e527c56d38564.png" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;"><img src="https://github.com/Calmact/e900v22c/raw/main/media/14194644bc4d8ca5fe3e527c56d38564.png" alt="descript" style="box-sizing: content-box; border-style: none; max-width: 100%; background-color: var(--color-canvas-default);"></a>；</p>

**Comment by ophub** [comment]
你试试5.10内核的版本

**Comment by cnmyn** [comment]
> 你试试5.10内核的版本
好的 我试试

**Comment by cnmyn** [comment]
> 你试试5.10内核的版本

谢谢啦

**Comment by ophub** [comment]
你使用的OpenWrt是哪个系列的内核？按说5.15的应该没问题啊。

**Comment by cnmyn** [comment]
> 你使用的OpenWrt是哪个系列的内核？按说5.15的应该没问题啊。

5.15

**Comment by cnmyn** [comment]
E900V22C和E900V22D，C带无线，D不带无线，其他应该都是一样的

**Comment by ophub** [comment]
内核在上一个版本的时候添加了对这个设备的支持，已经包含了他的网卡驱动及u-boot等，作者测试正常使用。

**Comment by cnmyn** [comment]
> 内核在上一个版本的时候添加了对这个设备的支持，已经包含了他的网卡驱动及u-boot等，作者测试正常使用。

经测试，5.10版本没有问题

**Comment by ophub** [comment]
你测试的是哪个？jammy？

**Comment by cnmyn** [comment]
> 那你以后就保持更新5.10的内核使用吧，你测试的是哪个？jammy？

bullseye，刚刚去刷了最新的openwrt_lede 5.15，好像网卡也不能用了😀
