### ISSUE TITLE
请问一下，N1刷了怎么有两个相邻的IP，而且还来回变，这是怎么回事呢大佬

### ISSUE THREAD

**Issue by andioy** [ophub/amlogic-s9xxx-armbian#305]
刷的是这个版本的Armbian_22.05.0_Aml_s905d_jammy_5.15.36_2022.05.07.2325.img，

**Comment by ophub** [comment]
刚启动时会u-boot重载，间隔几秒种，你等启动10秒后再ssh访问最后的ip

**Comment by jionkitten** [comment]
同样的问题，ifup启动的dhclient与NetworkManager的内置dhcp客户端会竞争dhcp租约。ifup本来是不需要的，但我测试过卸载会导致盒子网络无法连接。我测试通的一个解决方法，就是修改/etc/network/interfaces：
```
iface eth0 inet dhcp
    client no
```
这样dhclient会使用网口的MAC地址作为client id，与NetworkManager一致，dhcp server就不会下发不同的dhcp租约了。

也可以选择直接卸载isc-dhcp-client，直接让dhclient无法启动，但ifup@eth0.service这个服务会启动失败，手动修改service忽略就好。

**Comment by andioy** [comment]
> 刚启动时会u-boot重载，间隔几秒种，你等启动10秒后再ssh访问最后的ip
> 
> 可以在路由器的arp绑定，或者dhcp里面给盒子的mac地址指定一个固定ip，这样以后重启就是固定的唯一的你指定的ip

好的谢谢哈

**Comment by acooler15** [comment]
> 可以在'/etc/network/interfaces'中接注释掉eth0接口的配置，mac地址使用NetworkManager的`nmcli`命令或者修改`/etc/NetworkManager/system-connections/`下的配置文件进行配置。

**Comment by acooler15** [comment]
> 同样的问题，ifup启动的dhclient与NetworkManager的内置dhcp客户端会竞争dhcp租约。ifup本来是不需要的，但我测试过卸载会导致盒子网络无法连接。我测试通的一个解决方法，就是修改/etc/network/interfaces：
> 
> ```
> iface eth0 inet dhcp
>     client no
> ```
> 
> 这样dhclient会使用网口的MAC地址作为client id，与NetworkManager一致，dhcp server就不会下发不同的dhcp租约了。
> 
> 也可以选择直接卸载isc-dhcp-client，直接让dhclient无法启动，但[ifup@eth0.service](mailto:ifup@eth0.service)这个服务会启动失败，手动修改service忽略就好。

可以在'/etc/network/interfaces'中接注释掉eth0接口的配置，mac地址使用NetworkManager的`nmcli`命令或者修改`/etc/NetworkManager/system-connections/`下的配置文件进行配置。如果想使用`netplan`配置NetworkManager，估计得把`/etc/NetworkManager/system-connections/`下的配置文件删掉才行，否则`/etc`下的配置文件会覆盖netplan在`/run`下生成的配置文件。
