### ISSUE TITLE
HK1BOX有线网卡速率只有100

### ISSUE THREAD

**Issue by szcare** [ophub/amlogic-s9xxx-armbian#306]
HK1BOX使用Armbian_22.05.0_Aml_s905x3_bullseye_5.15.38_2022.05.10.1943，网卡速率只有100Mb/s,HK1BOX的有线网卡是千兆网卡。

**Comment by szcare** [comment]
已解决。

**Comment by txlos** [comment]
> 已解决。

你是怎么解决的啊？还有就是你用的哪个dtb?

**Comment by HokaDipe** [comment]
我也有这个问题，请帮帮我

**Comment by HokaDipe** [comment]
> 抱歉，很久没看了，问题解决了吗？有段时间没玩了，具体是哪里修改要回家看看内存卡上的文件才知道是要修改哪个文件了。

我已经解决了这个问题。 但我无法在emmc上安装armbian（我使用命令armbian-install然后选择512）。 请帮我

**Comment by szcare** [comment]
> > 抱歉，很久没看了，问题解决了吗？有段时间没玩了，具体是哪里修改要回家看看内存卡上的文件才知道是要修改哪个文件了。
> 
> 我已经解决了这个问题。 但我无法在emmc上安装armbian（我使用命令armbian-install然后选择512）。 请帮我
安装到emmc,默认只需用命令：armbian-install即可。你的无法安装，你再仔细看看“安装及升级 Armbian 的相关说明”，或者你发个无法安装的图片，看看是什么问题

**Comment by HokaDipe** [comment]
> > > Xin lỗi, đã không nhìn thấy nó trong một thời gian dài, vấn đề đã được giải quyết? Có một thời gian không chơi, cụ thể là nơi để sửa đổi để về nhà để xem các tập tin trên thẻ nhớ để biết những gì tập tin để sửa đổi.
> > 
> > 
> > Tôi đã giải quyết vấn đề này. Nhưng tôi không thể cài đặt armian trên emmc (tôi đã sử dụng lệnh armian-install sau đó chọn 512). Xin vui lòng giúp tôi cài đặt emmc, mặc định chỉ cần sử dụng lệnh: armbian-install. Bạn không thể cài đặt, bạn xem xét kỹ hơn hướng dẫn cài đặt và nâng cấp Armbian hoặc bạn gửi một hình ảnh không thể cài đặt để xem vấn đề là gì

我安装了 jammy 内核版本 6.1，然后我使用命令 armbian-install，所有安装工作都没有错误。 但是当我取出SD卡并插入电源时，hk1盒子没有信号

**Comment by HokaDipe** [comment]
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137959211/f3ccbbe3-d83e-4c27-83cd-405105b9e161)
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/137959211/5eb22326-7c60-4153-937f-3af74d5e856b)
