### ISSUE TITLE
Help with setting up a minimal desktop GUI with native Wayland

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#308]
Hi @ophub 
I'm trying to implement a minimal gui under Wayland. I don't want to install Gnome and I found some info but no longer based on archlinux so I'm struggling a bit..
I try to set up the config found on https://github.com/arcbjorn/arc-arch-linux-installation-guide#for-full-desktop-gui
If you have an idea or better if you manage to create a script to implement this, you would be on top..
Thank you

**Comment by ophub** [comment]
I'm sorry, I can't help you with this

**Comment by MX10-AC2N** [comment]
Ok it does not matter I tried just in case it seemed simple enough to set up.
Thank you  and good day..
