### ISSUE TITLE
HK1BOX将armbian写入到emmc后无法进行卡刷和线刷

### ISSUE THREAD

**Issue by AdviserM** [ophub/amlogic-s9xxx-armbian#310]
HK1BOX新盒子未进行emmc备份,执行armbian-install后,想重新刷回Atv,发现无法使用捅耳机孔的方式进行卡刷,并且也无法使用线刷捅耳机进行刷机的方式,这个是啥原因呢?

**Comment by ophub** [comment]
试试短接点
