### ISSUE TITLE
HK1 box 网线获取不到ip地址

### ISSUE THREAD

**Issue by liurenqiu520** [ophub/amlogic-s9xxx-armbian#311]
不管是U盘启动，还是写入emmc，使用网线都获取不到ip地址。设置静态ip都不管用。网线插上也会识别到。Wi-Fi就没有问题。
刷的Armbian_22.05.0_Aml_s905_focal_5.10.115_2022.05.14.2319.img.gz。

**Comment by ophub** [comment]
网卡芯片是什么，拍个照

**Comment by liurenqiu520** [comment]
@ophub
![IMG_5352](https://user-images.githubusercontent.com/2038316/168468683-4ad35b96-7452-4ceb-acb2-f2f859020d74.jpg)

**Comment by ophub** [comment]
JL2101驱动这个版本刚调试过，应该可以使用。你试一下5.15内核的固件

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/247

**Comment by liurenqiu520** [comment]
直接升级内核好像也不行😭

**Comment by liurenqiu520** [comment]
直接升级内核好像也不行，已经写入emmc了，没有公对公usb，没法刷了😭

**Comment by ophub** [comment]
测试的人反馈可以使用，你下载我发的链接里面的dtb替换一下试试

**Comment by liurenqiu520** [comment]
@ophub 哪个链接？我直接把5.15.39的内核的四个文件按照文档更新的，现在内核已经是5.15.39了。

**Comment by liurenqiu520** [comment]
![image](https://user-images.githubusercontent.com/2038316/168478123-4bfca743-b070-4c6f-8e93-e13415e79f74.jpeg)

刷了5.15.39，还是获取不到ip😭😭😭

**Comment by liurenqiu520** [comment]
![image](https://user-images.githubusercontent.com/2038316/168478580-cb520f36-0b62-44b9-890f-c92a2ae35437.jpeg)

刷了5.15.39还是不行啊，好难😭😭

**Comment by xcray** [comment]
我的盒子用5.4.207、5.18.14内核没这问题，用5.15.58内核就有这问题，估计5.15哪儿不对付
