### ISSUE TITLE
中兴B863AV3.2-M系统刷入EMMC后，只能从EMMC启动，无法从U盘启动

### ISSUE THREAD

**Issue by redfox100100** [ophub/amlogic-s9xxx-armbian#313]
盒子是中兴B863AV3.2-M,CPU是 s905l3a，固件使用的是Armbian_22.05.0_Aml_s905l3a_jammy_5.15.40_2022.05.17.1835.img.gz，从ATV系统使用软件Reboot To libreelec设置U盘启动后可以正常刷入到EMMC，刷完也可以正常从EMMC系统启动并运行，但是无法从U盘启动进入armbian，这样就没办法ddbr备份或者救砖。按照其他地方的教程，修改了boot.cmd内容并生成boot.scr，还是无法从usb启动，望大神解惑
 setenv loadaddr "0x44000000"
setenv l_mmc "0 1 2 3"
usb start
for devtype in "usb mmc" ; do
mkimage -C none -A arm -T script -d /mnt/boot.cmd /mnt/boot.scr

**Comment by ophub** [comment]
线刷回安卓系统（使用双公头USB线）

**Comment by redfox100100** [comment]
无法U盘启动，好的，谢谢

**Comment by mia0x75** [comment]
@redfox100100 请问问题解决了吗？另外eth0工作正常吗？

**Comment by maimaiti52** [comment]
可以分享一下ddbr备份的文件吗
