### ISSUE TITLE
Add the name of GUI in the name of the release file

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#314]
Hi @ophub 

I create a new workflow for building armbian with gui, that's work but the release file name don't precise this gui.
How to add the GUI name in the release filenames ?
my new workflow => https://github.com/MX10-AC2N/amlogic-s9xxx-armbian/blob/main/.github/workflows/build-armbian-desktop.yml
The release filenames :
Armbian_22.05.0-trunk_Odroidn2_bullseye_edge_5.17.5_xfce_desktop.img.gz
Armbian_22.05.0_Aml_s922x_bullseye_5.10.116_2022.05.18.0004.img.gz
Armbian_22.05.0_Aml_s922x_bullseye_5.15.40_2022.05.18.0009.img.gz
Armbian_22.05.0_Aml_s922x_bullseye_5.17.8_2022.05.18.0015.img.gz 
So I try to have Armbian_22.05.0_Aml_s922x_bullseye_5.15.40_xfce_2022.05.18.0009.img.gz

Thanks again and again

**Comment by ophub** [comment]
What words appear on which file name? for example

**Comment by MX10-AC2N** [comment]
Sorry I use google translate.
For now after building Armbian with for example Xfce as GUI I get the file Armbian_22.05.0_Aml_s922x_bullseye_5.15.40_2022.05.18.0009.img.gz
I try modify workflow for add GUI in filename, I would like to have as file name Armbian_22.05.0_Aml_s922x_bullseye_5.15.40_xfce_2022.05.18.0009.img.gz
The GUI can be selected, it's a variable that I set as a trigger in my workflow so I need to add in the name of the created files this variable ${{ env.ARMBIAN_DESKTOP }}

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/.github/workflows/build-armbian.yml

what do you mean? Add edition in tag?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/.github/workflows/build-armbian.yml

Look, I've added `Edition tags` for desktop and server, such as `server` or `gnome_desktop`

**Comment by MX10-AC2N** [comment]
![Capture d’écran (59)](https://user-images.githubusercontent.com/62643837/169001249-cb8bcf8c-c5a1-49a3-96cb-38a06b365044.png)

**Comment by ophub** [comment]
GitHub Actions can only operate the name of the TAG, and the file name of the firmware is determined by the `Rebuild` file



If you want to modify the name of the firmware, you need to add variables to the ATIONS parameter, and receive this variable in Rebuild and add it to the firmware name.

Such as:

https://github.com/ophub/amlogic-s9xxx-armbian/blob/5b08f94129f2b1a15e9fce50bd0402e5b44698b9/.github/workflows/build-armbian.yml#L130

`armbian_edition: ${{ env.ARMBIAN_DESKTOP_OPT }}`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/5b08f94129f2b1a15e9fce50bd0402e5b44698b9/rebuild#L598

```
# Add 
build_image_file="${tmp_outpath}/Armbian_${armbian_rebuild_version}_Aml_${soc}_${release_codename}_${kernel}_${armbian_edition}_$(date +"%Y.%m.%d.%H%M").img"
```

**Comment by MX10-AC2N** [comment]
Yeah, I see that you have update build-armbian.yml for desktop build. 
But I think it's better to separate into several workflows because the available graphics environment differs depending on the choice  focal / bullseye / ..
see https://github.com/armbian/build/tree/master/config/desktop
I test my build-armbian-desktop.yml workflow for Bullseye so the choice of GUI is from https://github.com/armbian/build/tree/master/config/desktop/bullseye/environments

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/5b08f94129f2b1a15e9fce50bd0402e5b44698b9/.github/workflows/build-armbian.yml#L97

I add the URL of the reference document to the code. If you need other desktops, you can view the available options in the Environments directory.
In order to display the ActionS panel and the line, I chose 2 common desktops, and I need to add more ones.

**Comment by MX10-AC2N** [comment]
Always on the top Great @ophub !!

**Comment by MX10-AC2N** [comment]
Maybe also need config
**DESKTOP_APPGROUPS_SELECTED** ( `browsers chat desktop_tools editors email internet multimedia office programming remote_desktop` ): Select what application groups to add to build
see the list available https://github.com/armbian/build/tree/master/config/desktop/bullseye/appgroups 
I use 
```
  sudo ./compile.sh BRANCH=${{ env.ARMBIAN_BRANCH }} RELEASE=${{ env.ARMBIAN_RELEASE }} BOARD=${{ env.ARMBIAN_BOARD }} \
                            BUILD_MINIMAL=no BUILD_DESKTOP=yes EXPERT=yes DESKTOP_ENVIRONMENT=${{ env.ARMBIAN_DESKTOP }} \
                            DESKTOP_ENVIRONMENT_CONFIG_NAME=config_basic DESKTOP_APPGROUPS_SELECTED='browsers 3dsupport chat desktop_tools editors email internet multimedia office' \
                            HOST=armbian KERNEL_ONLY=no KERNEL_CONFIGURE=no \
                            CLEAN_LEVEL=make,debs COMPRESS_OUTPUTIMAGE=sha
```

**Comment by ophub** [comment]
Does this need to be added? The default configuration is officially specified, right?

**Comment by MX10-AC2N** [comment]
My first try I doesn't specify DESKTOP_APPGROUPS_SELECTED but when I flash this relaese on USB stick the first boot wasn't GUI and just have CLI on HDMI just like server release.. 
So I try with this DESKTOP_APPGROUPS_SELECTED='browsers 3dsupport chat desktop_tools editors email internet multimedia office' 
result => 1.3GB I will try flash on USB for test.. 
Thanks a lot @ophub

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/03b3c88630930a4429443a9fb0da893510a6fd77/.github/workflows/build-armbian.yml#L99

You can test it. If you need more parameters, you can add them here. If you have appropriate configuration parameters, please give feedback.

**Comment by MX10-AC2N** [comment]
Oops I grow the ROOTFS size but need more, system start with 98% of / used (3,5G) and cause some service can't start I will expand more and test again..
```
armbian_size:
        description: "Set armbian rootfs size."
        required: false
        default: "3584"
```
I will test with "5584" it will be good for desktop release..

**Comment by ophub** [comment]
When testing, the firmware is set to a larger size, and only the firmware of your soc is packaged, which is also very fast

**Comment by MX10-AC2N** [comment]
Hi,
I try flashed on USB https://github.com/MX10-AC2N/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_budgie_05.19.0025
The first boot was again under CLI, so I try install "lightdm" but the lightdm.service failed and can't start. So I remove "lightdm" and install "sddm" with sddm there is gui display manager after boot but no session is available so impossible to launch budgie. Maybe budgie can't lauch with sddm, i will try another..

Why there is no display manager installed when I build desktop release it's just non sense, maybe the rebuild script need adapt.. or need more configuration in armbian build command..
I will test with other GUI too

**Comment by MX10-AC2N** [comment]
Strange seems that budgie-desktop was not installed ??
```
admin@192.168.1.130's password:
    _              _        ___ ____  ____
   / \   _ __ ___ | |  ___ / _ \___ \|___ \__  __
  / _ \ | '_ ` _ \| | / __| (_) |__) | __) \ \/ /
 / ___ \| | | | | | | \__ \\__, / __/ / __/ >  <
/_/   \_\_| |_| |_|_| |___/  /_/_____|_____/_/\_\

Welcome to Armbian 22.05.0-trunk Bullseye with bleeding edge Linux 5.15.41-flippy-73+o

No end-user support: built from trunk

System load:   2%               Up time:       8 min
Memory usage:  7% of 3.26G      IP:            192.168.1.130
CPU temp:      47°C             Usage of /:    13% of 29G
storage/:      38% of 255M

[ General system configuration (beta): armbian-config ]

Last login: Thu May 19 08:44:12 2022 from 192.168.1.230
admin@armbian:~$ apt show budgie-desktop
Package: budgie-desktop
Version: 10.5.2-4
Priority: optional
Section: x11
Maintainer: David Mohammed <fossfreedom@ubuntu.com>
Installed-Size: 41,0 kB
Depends: budgie-core, gir1.2-budgie-1.0 (>= 10.5), gnome-control-center, gnome-menus, network-manager-gnome, dconf-gsettings-backend | gsettings-backend
Recommends: budgie-desktop-view
Suggests: slick-greeter, nautilus, gnome-terminal
Homepage: https://github.com/solus-project/budgie-desktop
Download-Size: 26,7 kB
APT-Sources: http://deb.debian.org/debian bullseye/main arm64 Packages
Description: Desktop package for budgie-desktop

admin@armbian:~$
```

**Comment by MX10-AC2N** [comment]
So I install budgie-desktop
```admin@armbian:~$ sudo apt install budgie-desktop
[sudo] Mot de passe de admin :
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  liblightdm-gobject-1-0 lightdm-gtk-greeter
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
Les paquets supplémentaires suivants seront installés :
  accountsservice acl apg bubblewrap budgie-core cheese-common colord colord-data dbus-x11 desktop-base desktop-file-utils
  dictionaries-common fonts-quicksand gir1.2-budgie-1.0 gir1.2-peas-1.0 gnome-control-center gnome-control-center-data
  gnome-desktop3-data gnome-menus gnome-screensaver gnome-session-bin gnome-session-common gnome-settings-daemon
  gnome-settings-daemon-common gstreamer1.0-clutter-3.0 gstreamer1.0-x hunspell-en-us libaccountsservice0 libaspell15
  libbudgie-plugin0 libbudgie-private0 libbudgietheme0 libcheese-gtk25 libcheese8 libclutter-1.0-0 libclutter-gst-3.0-0
  libclutter-gtk-1.0-0 libcogl-pango20 libcogl-path20 libcogl20 libcolord-gtk1 libcolorhug2 libenchant-2-2 libgck-1-0
  libgcr-base-3-1 libgeoclue-2-0 libgeocode-glib0 libgnome-bluetooth13 libgnome-desktop-3-19 libgnome-menu-3-0 libgnomekbd-common
  libgnomekbd8 libgoa-1.0-0b libgoa-1.0-common libgoa-backend-1.0-1 libgphoto2-6 libgphoto2-port12 libgraphene-1.0-0 libgsound0
  libgtop-2.0-11 libgtop2-common libgusb2 libgweather-3-16 libgweather-common libhandy-1-0 libibus-1.0-5 libieee1284-3
  libimobiledevice6 libjavascriptcoregtk-4.0-18 libmalcontent-0-0 libmanette-0.2-0 libmutter-7-0 libnma-common libnma0
  libpeas-1.0-0 libpeas-common libpipewire-0.3-0 libplist3 libpulse-mainloop-glib0 libpwquality-common libpwquality1 libraven0
  librsvg2-common libsane-common libsane1 libsecret-1-0 libsecret-common libsnmp-base libsnmp40 libspa-0.2-modules
  libtext-iconv-perl libudisks2-0 libupower-glib3 libusbmuxd6 libwebkit2gtk-4.0-37 libwoff1 libwpe-1.0-1 libwpebackend-fdo-1.0-1
  libxcb-res0 libxkbregistry0 libxtst6 mutter-common network-manager-gnome policykit-1-gnome upower xdg-dbus-proxy xwayland
Paquets suggérés :
  slick-greeter nautilus gnome-terminal gnome | kde-standard | xfce4 | wmaker ispell | aspell | hunspell wordlist gnome-software
  | gnome-packagekit libcanberra-gtk-module libcanberra-gtk3-module x11-xserver-utils usbguard hunspell openoffice.org-hunspell
  | openoffice.org-core aspell libenchant-2-voikko gphoto2 libusbmuxd-tools avahi-daemon hplip snmp-mibs-downloader
  gstreamer1.0-alsa network-manager-openconnect-gnome network-manager-openvpn-gnome network-manager-vpnc-gnome
  network-manager-pptp-gnome
Paquets recommandés :
  budgie-desktop-view plymouth-label cups-pk-helper gnome-online-accounts gnome-user-docs gnome-user-share gkbd-capplet
  libcanberra-pulse rygel | rygel-tracker system-config-printer-common malcontent-gui pulseaudio-module-bluetooth realmd
  gnome-power-manager | xfce4-power-manager libpam-gnome-keyring iio-sensor-proxy pulseaudio x11-xserver-utils aspell-en
  | aspell-dictionary | aspell6a-dictionary libclutter-1.0-common libcogl-common enchant-2 libgphoto2-l10n usb.ids usbmuxd
  pipewire sane-utils ipp-usb gstreamer1.0-gl xdg-desktop-portal-gtk gstreamer1.0-libav notification-daemon gnome-keyring
  mobile-broadband-provider-info
Les NOUVEAUX paquets suivants seront installés :
  accountsservice acl apg bubblewrap budgie-core budgie-desktop cheese-common colord colord-data dbus-x11 desktop-base
  desktop-file-utils dictionaries-common fonts-quicksand gir1.2-budgie-1.0 gir1.2-peas-1.0 gnome-control-center
  gnome-control-center-data gnome-desktop3-data gnome-menus gnome-screensaver gnome-session-bin gnome-session-common
  gnome-settings-daemon gnome-settings-daemon-common gstreamer1.0-clutter-3.0 gstreamer1.0-x hunspell-en-us libaccountsservice0
  libaspell15 libbudgie-plugin0 libbudgie-private0 libbudgietheme0 libcheese-gtk25 libcheese8 libclutter-1.0-0
  libclutter-gst-3.0-0 libclutter-gtk-1.0-0 libcogl-pango20 libcogl-path20 libcogl20 libcolord-gtk1 libcolorhug2 libenchant-2-2
  libgck-1-0 libgcr-base-3-1 libgeoclue-2-0 libgeocode-glib0 libgnome-bluetooth13 libgnome-desktop-3-19 libgnome-menu-3-0
  libgnomekbd-common libgnomekbd8 libgoa-1.0-0b libgoa-1.0-common libgoa-backend-1.0-1 libgphoto2-6 libgphoto2-port12
  libgraphene-1.0-0 libgsound0 libgtop-2.0-11 libgtop2-common libgusb2 libgweather-3-16 libgweather-common libhandy-1-0
  libibus-1.0-5 libieee1284-3 libimobiledevice6 libjavascriptcoregtk-4.0-18 libmalcontent-0-0 libmanette-0.2-0 libmutter-7-0
  libnma-common libnma0 libpeas-1.0-0 libpeas-common libpipewire-0.3-0 libplist3 libpulse-mainloop-glib0 libpwquality-common
  libpwquality1 libraven0 librsvg2-common libsane-common libsane1 libsecret-1-0 libsecret-common libsnmp-base libsnmp40
  libspa-0.2-modules libtext-iconv-perl libudisks2-0 libupower-glib3 libusbmuxd6 libwebkit2gtk-4.0-37 libwoff1 libwpe-1.0-1
  libwpebackend-fdo-1.0-1 libxcb-res0 libxkbregistry0 libxtst6 mutter-common network-manager-gnome policykit-1-gnome upower
  xdg-dbus-proxy xwayland
0 mis à jour, 108 nouvellement installés, 0 à enlever et 0 non mis à jour.
Il est nécessaire de prendre 52,6 Mo dans les archives.
Après cette opération, 230 Mo d'espace disque supplémentaires seront utilisés.
```
and finally can start budgie session, with lot of apps preinstalled..
Why I need install budgie if I build with budgie desktop there is something wrong ..

**Comment by MX10-AC2N** [comment]
Hi @ophub 
https://github.com/armbian/build/blob/master/config/desktop/bullseye/environments/budgie/config_base/packages
here is the build config_base for bugie under bullseye from armbian normally there is lightdm installed and all of budgie desktop
I think something goes wrong with rebuild script for desktop release. Have you tried desktop release on your box ?

**Comment by ophub** [comment]
https://armbian.tnahosting.net/dl/odroidn2/archive/



https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/.github/workflows/rebuild-armbian.yml


Select the desktop version of the firmware, reconfigure online to see if the firmware can be used normally, you can check whether the reconstruction script is suitable for the desktop version system

**Comment by MX10-AC2N** [comment]
Yeah I will test rebuild-armbian.yml with odroin2 focal cinnamon there is no bullseye desktop release from armbian, but I can test with focal cinnamon..
Other thing I check if the config_base are installed on my bullseye budgie release and 380 package was not installed..

**Comment by ophub** [comment]
OK, testing is hard work.

**Comment by MX10-AC2N** [comment]
I install this list of package https://github.com/armbian/build/blob/master/config/desktop/bullseye/environments/budgie/config_base/packages and after all of budgie works fine and lightdm too..
Now I will test the rebuild of odroidn2 focal cinnamon..
https://github.com/armbian/build/blob/master/config/targets-desktop-beta.conf here we can see that DESKTOP_APPGROUPS_SELECTED is use for desktop release

**Comment by MX10-AC2N** [comment]
@ophub 
my new workflow rebuild_armbian failed
```
 [ Error ] Invalid -n parameter [  ]!
Error: Process completed with exit code 1.
```
need add -n parameter in rebuild_armbian.yml 
![Capture d’écran (60)](https://user-images.githubusercontent.com/62643837/169316324-d1aa7d11-de8e-4213-bec0-9b08c81393a8.png)

**Comment by MX10-AC2N** [comment]
oops 2 commits behind ophub:main sorry..

**Comment by ophub** [comment]
bug has been fixed

**Comment by MX10-AC2N** [comment]
So I launch new workflow rebuild_armbian with 8278 for ROOTFS
https://github.com/MX10-AC2N/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_jammy_05.19.2323
The release give 1.93GB but when I use it on BalenaEtcher, Balena indicate 923MB so strange..?
I will flash and try..

**Comment by MX10-AC2N** [comment]
OK so I flash and the first boot give CLI for first user add after this desktop environment start fine..

**Comment by MX10-AC2N** [comment]
Hi @ophub 
I used build_armbian workflow for https://github.com/MX10-AC2N/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_xmonad_desktop_05.20.1525
I then used BalenaEtcher to flash a USB key, first remark the image file is about 600MB but Balena indicates 923MB the same value as for the reconstruction that I made of Odroid N2 jammy Cinnamon which was 1.9GB
Maybe there is a problem at this level, anyway we can still flash successfully..
So first start, I have on my tv screen the creation of the first user in CLI mode and after creating my user no graphical environment is launched..
Xmonad is not installed.. 
Must be missing some config during build
I'm still searching..

**Comment by ophub** [comment]
Hard work, this is a process of countless experiments.
You can see the configuration options of his precompiled files in armbian's github repository

**Comment by MX10-AC2N** [comment]
It seems easier to deploy the graphical environment directly on the base CLI version.
What I do is retrieve the list of packages from the config_base provided by armbian.
For this example under bullseye and xmonad as gui. The github address will be adjusted accordingly (release and gui)
I do
`wget https://raw.githubusercontent.com/armbian/build/master/config/desktop/bullseye/environments/xmonad/config_base/packages`
`apt install $(packages)`
long install process and after reboot 
I have the login page in GUI mode. but I didn't have time to enter my password, my screen suddenly went black. Yet another problem to clear up.. Maybe it's related to the fact that my gt-king_pro is connected to my tv via an HDMI splitter.

**Comment by ophub** [comment]
try https://rufus.ie/

**Comment by MX10-AC2N** [comment]
Alright Rufus is good, it told me a problem with another application that was running on my pc in the background..
So I flashed with Rufus my latest release bullseye xmonad but the same once started no xmonad gui installed.
so i did to install the config_base of xmonad for bullseye
`wget https://raw.githubusercontent.com/armbian/build/master/config/desktop/bullseye/environments/xmonad/config_base/packages`
`sudo apt install $(cat packages)`
And I think it's good but I have this problem again that my tv screen goes black after a while, I get to the login page (lightdm) but no time to log in the screen goes all black, my tv is still connected, the signal is present but black screen.. it's another problem..
In any case the build_armbian.yml workflows that I launched to have a bullseye release with gui did not work, the packages of the chosen config_base were not installed but on the other hand with rebuild_armbian.yml using an odroid n2 image jammy cinnamon it worked fine..
Either bullseye is the problem or something is missing in the armbian build config
armbian does not offer any desktop image based on bullseye .. however the construction seems to work well ..
I continue to discover and learn about armbian
Maybe you can open "discussion" in your repository for this king of exchange.

**Comment by MX10-AC2N** [comment]
Hi @ophub 
This morning I looked a bit at the armbian build logs
This is what jumped out at me
```
[ ok ] Installing the desktop packages for [ Armbian ]
Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
   box64
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
```
it seems to refer to this https://github.com/armbian/build/blob/master/config/optional/architectures/arm64/_config/desktop/jammy/environments/_all_environments/packages

and error for xmonad
```
[ o.k. ] Building desktop package [ armbian-bullseye-desktop-xmonad_22.05.0-trunk_all ]
[ o.k. ] Creating board support package for desktop 
[ o.k. ] Starting rootfs and image building process for [ current odroidn2 bullseye  xmonad no ]
[ o.k. ] Checking local cache [ bullseye-xmonad-arm64.1ce...5c9.tar.lz4 ]
[ .... ] searching on servers 
05/20 14:50:36 [ERROR] CUID#7 - Download aborted. URI=https://xogium.performanceservers.nl/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://xogium.performanceservers.nl/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

05/20 14:50:36 [ERROR] CUID#8 - Download aborted. URI=https://armbian.lv.auroradev.org/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://armbian.lv.auroradev.org/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

05/20 14:50:36 [ERROR] CUID#9 - Download aborted. URI=https://armbian.chi.auroradev.org/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://armbian.chi.auroradev.org/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

05/20 14:50:36 [ERROR] CUID#10 - Download aborted. URI=https://armbian.tnahosting.net/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://armbian.tnahosting.net/dl/_rootfs/bullseye-xmonad-arm64.1ce047b51ec95a1136a36db6750055c9.tar.lz4.asc
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found

aria2 will resume download if the transfer is restarted.
If there are any errors, then see the log file. See '-l' option in help/man page for details.
[ warn ] Failed to download control file 
```
this is why the packages of the config_base of xmonad under bullseye are not installed..

**Comment by MX10-AC2N** [comment]
So to agree with armbian Index of /dl/_rootfs/
bullseye can only build cinnamon and xfce cause there is only this 2 gui present in the Index of /dl/_rootfs/

**Comment by ophub** [comment]
try `gnome` and `xfce`, These two are more commonly used

**Comment by MX10-AC2N** [comment]
Cinnamon failed 
```
[ o.k. ] Checking local cache [ bullseye-cinnamon-arm64.70d...b74.tar.lz4 ]
[ .... ] searching on servers 

05/21 19:57:13 [ERROR] CUID#7 - Download aborted. URI=https://xogium.performanceservers.nl/dl/_rootfs/bullseye-cinnamon-arm64.70d65ac88ef00ced13a3e33d4f1c1b74.tar.lz4.asc
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://xogium.performanceservers.nl/dl/_rootfs/bullseye-cinnamon-arm64.70d65ac88ef00ced13a3e33d4f1c1b74.tar.lz4.asc
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found
```
xfce failed
```
[ warn ] Failed to download control file 
[ .... ] downloading using http(s) network [ bullseye-xfce-arm64.70d65ac88ef00ced13a3e33d4f1c1b74.tar.lz4 ]

05/21 19:53:38 [ERROR] CUID#7 - Download aborted. URI=https://armbian.tnahosting.net/dl/_rootfs/bullseye-xfce-arm64.70d65ac88ef00ced13a3e33d4f1c1b74.tar.lz4
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://armbian.tnahosting.net/dl/_rootfs/bullseye-xfce-arm64.70d65ac88ef00ced13a3e33d4f1c1b74.tar.lz4
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found
```
We can't build any desktop release on Bullseye .. it's curious that the armbian compilation doesn't failed with this download error.

**Comment by MX10-AC2N** [comment]
Hello just for share,
I try build jammy with budgie desktop with same problem
```
[ .... ] Checking out 
[ o.k. ] Building firmware package [ armbian-firmware-full_22.05.0-trunk_all ]
[ o.k. ] Creating board support package for CLI [ armbian-bsp-cli-odroidn2 ]
[ o.k. ] Building desktop package [ armbian-jammy-desktop-budgie_22.05.0-trunk_all ]
[ o.k. ] Creating board support package for desktop 
[ o.k. ] Starting rootfs and image building process for [ current odroidn2 jammy browsers 3dsupport budgie no ]
[ o.k. ] Checking local cache [ jammy-budgie-arm64.90a...c82.tar.lz4 ]
[ .... ] searching on servers 

05/22 00:48:55 [ERROR] CUID#7 - Download aborted. URI=https://xogium.performanceservers.nl/dl/_rootfs/jammy-budgie-arm64.90a7f292265393869caeabcec6039c82.tar.lz4.asc
Exception: [AbstractCommand.cc:351] errorCode=3 URI=https://xogium.performanceservers.nl/dl/_rootfs/jammy-budgie-arm64.90a7f292265393869caeabcec6039c82.tar.lz4.asc
  -> [HttpSkipResponseCommand.cc:218] errorCode=3 Resource not found
```

**Comment by ophub** [comment]
You can consult the official, Or ask others in the armbian forums. if you generate a jammy image with a desktop, what parameters are required.


https://github.com/armbian/build#simply-start-with-the-build-script

```
apt-get -y install git
git clone https://github.com/armbian/build
cd build
./compile.sh
```

**Comment by MX10-AC2N** [comment]
Hi @ophub 
I continue my test for adjust the command line of bullseye desktop compilation..
So I launch with some new add and the process failed, but this seems to be related to the fact of a lack of space under github finally here is what I have in "post check", I do not understand much about it, if for you it is clearer, I will appreciate your tips..
```
Post job cleanup.
/usr/bin/git version
git version 2.36.1
Temporarily overriding HOME='/home/runner/work/_temp/f2dda83f-d340-42eb-be4e-a44ca17a97c0' before making global git config changes
Adding repository directory to the temporary git global config as a safe directory
/usr/bin/git config --global --add safe.directory /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian
/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
http.https://github.com/.extraheader
/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
```
Thank again. ;-)

**Comment by ophub** [comment]
you can delete
`- name: Rebuild Armbian for Amlogic s9xxx`

Only upload official compiled firmware. Open positions separately with another script（use-releases-file-to-build.yml ）.This saves a little space.

**Comment by MX10-AC2N** [comment]
Okay.. It was nice to be able to directly rebuild Armbian.

**Comment by rapdodge** [comment]
I'm building ubuntu jammy xfce, and installed all package are in [this](https://raw.githubusercontent.com/armbian/build/master/config/desktop/jammy/environments/xfce/config_base/packages), and lightdm successful, but, my keyboard and my mouse didnt working, i dont know why
