### ISSUE TITLE
Tanix Tx9 Pro(S912) add Wifi driver

### ISSUE THREAD

**Issue by Smim0** [ophub/amlogic-s9xxx-armbian#315]
Hi,

The image is working just fine for Tanix Tx9 Pro but no wifi at all, I think the driver is missing. I think it is the same issue as in [here](https://github.com/ophub/amlogic-s9xxx-openwrt/issues/64) the devices are also very similar

Thanks

**Comment by ophub** [comment]
What is the NIC chip of this device? Do you have any photos?

https://www.gearbest.com/tv-box/pp_759339.html

https://github.com/ophub/amlogic-s9xxx-armbian/blob/7b0ec303982b5431ada8e2be15c86dadf05b6d77/build-armbian/common-files/rootfs/usr/sbin/armbian-install#L73

Does it support writing to emmc? Which option did you use?

Can the LED screen light up? `armbian-led 19`


```
cat /etc/ophub-release
cat /boot/uEnv.txt
```

**Comment by ophub** [comment]
https://lore.kernel.org/lkml/CAOi56cXKmv_Us1wDcMOYbdjFzZcLVu_t210Yrv891wKi22hV8A@mail.gmail.com/T/

Can the ap6255 wireless driver be used? Let me ask unifreq, and then reply to you

**Comment by ophub** [comment]
Just consulted. This driver is supported, but there is no wireless module in this DTB. When he has time, he will add a dedicated DTB to this device.

**Comment by Smim0** [comment]
Amazing, thanks btw for having these images available

**Comment by ophub** [comment]
[meson-gxm-tx9-pro.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8715826/meson-gxm-tx9-pro.dtb.zip)

**Comment by Smim0** [comment]
IT WORKS!!! Thank you very much, as a workaround I have edited /usr/sbin/armbian-install to include a line with the dtb and I can confim that it installed to emmc succefully

Thank you very much for the quick response

**Comment by rainups** [comment]
我有一个低配的Tanix TX9pro 2G RAM,16G ROM,100Mb Nic 盒子
用的是Armbian_22.11.0_Aml_s912_bullseye_5.10.154_server_2022.11.16.img，配合meson-gxm-tx9-pro.dtb
也存在有线LAN和无线WIFI不工作问题。

它与常规的Tanix TX9pro 3G RAM,16G ROM,1000Mb Nic 很接近，我常试用最接近的meson-gxm-q201.dtb 有线LAN也不能工作，

但它比meson-gxm-tx9-pro.dtb在ifconfig里能看到MAC地址，但没IP地址。

在老版本的 Armbian_20.10_Arm-64_bullseye_current_5.9.0.img 固件里有线是可以工作，无线WIFI另行打补丁也是工作的(用rtl8189es驱动）。


2个硬件PCB版本图片：CS_912_TX92_LP_V1.0 20170810 和 CS_912_TX92_B8_V1.1 20190811
[https://discourse.coreelec.org/uploads/default/original/2X/9/94b02f9dbab4377de9a1458103369790ec75e546.jpeg](https://discourse.coreelec.org/uploads/default/original/2X/9/94b02f9dbab4377de9a1458103369790ec75e546.jpeg)

**Comment by rainups** [comment]
**meson-gxm-tx9-pro.dtb**

 [  OK  ] Finished Permit User Sessions.
         Starting Hostname Service...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Started chrony, an NTP client/server.
[  OK  ] Reached target System Time Synchronized.
[  OK  ] Started Daily apt download activities.
[  OK  ] Started Daily apt upgrade and clean activities.
[  OK  ] Started Periodic ext4 Online Metadata Check for All Filesystems.
[  OK  ] Started Discard unused blocks once a week.
[  OK  ] Started Daily rotation of log files.
[  OK  ] Started Daily man-db regeneration.
[  OK  ] Started Run system activity accounting tool every 10 minutes.
[  OK  ] Started Generate summary of yesterday's process accounting.
[  OK  ] Reached target Timers.
[  OK  ] Started LSB: set CPUFreq kernel parameters.
         Starting LSB: Set sysfs variables from /etc/sysfs.conf...
[  OK  ] Started LSB: Set sysfs variables from /etc/sysfs.conf.
[  OK  ] Started Hostname Service.
         Starting Network Manager Script Dispatcher Service...
[  OK  ] Started Network Manager Script Dispatcher Service.
[   20.107229] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   20.112620] Bluetooth: hci0: Failed to set baudrate
[   20.137498] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   21.893871] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   21.907198] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   21.923262] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  OK  ] Started Dispatcher daemon for systemd-networkd.
[   22.240540] Bluetooth: hci0: command 0x0c03 tx timeout
[   22.260751] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[   24.013886] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   24.013900] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   24.013908] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   24.274106] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[   26.023858] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   26.038432] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   26.055764] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[   26.327527] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   28.077193] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   28.092148] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   28.109825] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[   28.384102] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   30.133893] Bluetooth: hci0: BCM: Reset failed (-110)
[   30.133901] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   30.133922] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   30.182353] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  OK  ] Finished Network Manager Wait Online.
[  OK  ] Reached target Network is Online.
         Starting /etc/rc.local Compatibility...
[   30.516151] rc.local[1700]: irq name:xhci-hcd:usb1, irq:43, affinity: 4
[   30.576311] rc.local[1706]: irq name:xhci-hcd:usb1, irq:43, affinity: 4
[  OK  ] Started /etc/rc.local Compatibility.
         Starting Hold until boot process finishes up...
         Starting Terminate Plymouth Boot Screen...

Armbian 22.11.0-trunk Bullseye ttyAML0

armbian login:
[  330.200705] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  331.947136] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  331.963376] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  331.982389] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  332.250678] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  334.000481] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  334.016945] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  334.036120] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  334.304041] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  336.050477] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  336.066954] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  336.086147] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  336.354019] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  338.103814] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  338.120246] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  338.139424] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed



**meson-gxm-q201.dtb**

[  OK  ] Started Network Manager.
[  OK  ] Reached target Network.
         Starting Network Manager Wait Online...
         Starting chrony, an NTP client/server...
         Starting Access point and authentication server for Wi-Fi and Ethernet...
         Starting OpenVPN service...
         Starting Notify NFS peers of a restart...
         Starting Permit User Sessions...
[  OK  ] Started Unattended Upgrades Shutdown.
[  OK  ] Started vnStat network traffic monitor.
[  OK  ] Finished OpenVPN service.
[  OK  ] Finished Permit User Sessions.
[  OK  ] Started LSB: set CPUFreq kernel parameters.
         Starting LSB: Set sysfs variables from /etc/sysfs.conf...
         Starting Hostname Service...
[  OK  ] Started Notify NFS peers of a restart.
[  OK  ] Started LSB: Set sysfs variables from /etc/sysfs.conf.
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Started chrony, an NTP client/server.
[  OK  ] Reached target System Time Synchronized.
[  OK  ] Started Daily apt download activities.
[  OK  ] Started Daily apt upgrade and clean activities.
[  OK  ] Started Periodic ext4 Online Metadata Check for All Filesystems.
[  OK  ] Started Discard unused blocks once a week.
[  OK  ] Started Daily rotation of log files.
[  OK  ] Started Daily man-db regeneration.
[  OK  ] Started Run system activity accounting tool every 10 minutes.
[  OK  ] Started Generate summary of yesterday's process accounting.
[  OK  ] Reached target Timers.
[  OK  ] Started Hostname Service.
         Starting Network Manager Script Dispatcher Service...
[  OK  ] Started Network Manager Script Dispatcher Service.
[   20.444614] meson8b-dwmac c9410000.ethernet eth0: PHY [0.e40908ff:08] driver [Meson GXL Internal PHY] (irq=43)
[   21.988071] meson8b-dwmac c9410000.ethernet eth0: No Safety Features support found
[   22.001650] meson8b-dwmac c9410000.ethernet eth0: PTP not supported by HW
[   22.015608] meson8b-dwmac c9410000.ethernet eth0: configuring for phy/rmii link mode
[  OK  ] Started Dispatcher daemon for systemd-networkd.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   22.821684] r8712u 1-1:1.0 wlan0: 1 RCR=0x153f00e
[   22.827324] r8712u 1-1:1.0 wlan0: 2 RCR=0x553f00e
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   31.456857] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   31.465249] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   32.234411] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   33.805361] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   34.583056] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   36.153972] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   36.931670] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   38.502647] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   39.280235] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   40.851153] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   41.628814] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   54.963716] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   55.741315] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   57.375147] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   58.152778] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   59.723736] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   60.501417] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   62.072416] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   62.849956] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   64.420921] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   65.198607] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   78.512523] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   79.290108] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[FAILED] Failed to start Network Manager Wait Online.
See 'systemctl status NetworkManager-wait-online.service' for details.
[  OK  ] Reached target Network is Online.
         Starting /etc/rc.local Compatibility...
[   80.053255] rc.local[1744]: irq name:eth0, irq:29, affinity: 8
[   80.054228] rc.local[1744]: irq name:xhci-hcd:usb1, irq:42, affinity: 4
[   80.068569] rc.local[1744]: Set the rps cpu mask of eth0 to 0xf3
[   80.115062] rc.local[1750]: irq name:eth0, irq:29, affinity: 8
[   80.115620] rc.local[1750]: irq name:xhci-hcd:usb1, irq:42, affinity: 4
[   80.116167] rc.local[1750]: Set the rps cpu mask of eth0 to 0xf3
[  OK  ] Started /etc/rc.local Compatibility.
         Starting Hold until boot process finishes up...
         Starting Terminate Plymouth Boot Screen...
[   80.861057] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx

Armbian 22.11.0-trunk Bullseye ttyAML0

armbian login: [   81.638717] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   83.209617] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   83.987226] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   85.558144] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   86.335876] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   87.906740] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   88.684413] meson8b-dwmac c9410000.ethernet eth0: Link is Down

armbian login: root
Password: [  101.998327] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx

[  102.775962] meson8b-dwmac c9410000.ethernet eth0: Link is Down
    _              _   ____  ___  _ ____
   / \   _ __ ___ | | / ___|/ _ \/ |___ \
  / _ \ | '_ ` _ \| | \___ \ (_) | | __) |
 / ___ \| | | | | | |  ___) \__, | |/ __/
/_/   \_\_| |_| |_|_| |____/  /_/|_|_____|

Welcome to Armbian 22.11.0-trunk Bullseye with Linux 5.10.154-ophub

No end-user support: built from trunk

System load:   11%              Up time:       1 min
Memory usage:  7% of 1.88G      IP:
CPU temp:      64°C             Usage of /:    54% of 2.4G
RX today:      n/a

[ General system configuration (beta): armbian-config ]

Last login: Wed Nov 16 13:01:22 HKT 2022 on ttyAML0
root@armbian:~# [  104.346753] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  105.124596] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  106.695449] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  107.473175] meson8b-dwmac c9410000.ethernet eth0: Link is Down
ifconfig
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::ae08:e1fd:16c0:4059  prefixlen 64  scopeid 0x20<link>
        ether de:f1:ae:d4:73:07  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 90  bytes 10647 (10.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 29

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 24  bytes 1944 (1.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24  bytes 1944 (1.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@armbian:~# [  111.392650] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  112.170348] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  125.484312] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  126.261905] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  127.832859] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  128.610458] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  130.181550] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  130.959054] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  132.530086] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  133.307587] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  134.878567] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  135.656247] meson8b-dwmac c9410000.ethernet eth0: Link is Down

**Comment by vickenli** [comment]
你好  Tanix TX9 Pro-B8  sp6330 zx190906无线网卡 安装amlogic_s912.img openwrt 有线网卡无法识别没有连接状态 求帮助

**Comment by alexantao** [comment]
I know it's resolved, but I'd just ike to thank you for this !!!! HElped me a lot !

**Comment by prakashr85** [comment]
I also have tanix tx9 pro same model, installed this image Armbian 24.8.0-trunk.314 Bookworm Gnome Kernel: 6.6.36, Size: 1.3GB, Release date: Jul 4, 2024 .

Used the dtb file mentioned in this issue, wifi, ethernet works, but the bluetooth is not working, anyone got it working, can you please help? @Smim0
