### ISSUE TITLE
Sometimes wifi is disconnected

### ISSUE THREAD

**Issue by spring59** [ophub/amlogic-s9xxx-armbian#317]
Sometimes wifi is disconnected in the middle of the night and will not automatically reconnect. How to set up automatic reconnect?

**Comment by ophub** [comment]
- `sudo vi /etc/pm/sleep.d/10_resume_wifi`
- Copy the following content, add it, save:
```
#!/bin/sh

case "${1}" in
  resume|thaw)
    nmcli r wifi off && nmcli r wifi on ;;
esac
```
- `sudo chmod 755 /etc/pm/sleep.d/10_resume_wifi`
- `sync && reboot`
