### ISSUE TITLE
默认源安装firefox报错，安装firefox-esr无法找到软件，换源安装firefox-esr报错

### ISSUE THREAD

**Issue by redfox100100** [ophub/amlogic-s9xxx-armbian#318]
大神您好，
安装了桌面之后安装浏览器报错，报错信息如下，执行过update和upgrade,重装过snap
apt-get install firefox
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  firefox
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/72.3 kB of archives.
After this operation, 261 kB of additional disk space will be used.
Preconfiguring packages ...
(Reading database ... 62433 files and directories currently installed.)
Preparing to unpack .../firefox_1%3a1snap1-0ubuntu2_arm64.deb ...
=> Installing the firefox snap
==> Checking connectivity with the snap store
==> Installing the firefox snap
error: cannot perform the following tasks:
- Run configure hook of "firefox" snap if present (run hook "configure": cannot perform operation: umount --no-follow /var/lib/snapd/hostfs//tmp/snap.rootfs_ceWCGB: Invalid argument)
dpkg: error processing archive /var/cache/apt/archives/firefox_1%3a1snap1-0ubuntu2_arm64.deb (--unpack):
 new firefox package pre-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/firefox_1%3a1snap1-0ubuntu2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by ophub** [comment]
`sudo apt-get install -y firefox`
我在focal上使用这个命令安装的，使用正常。

`cat /etc/apt/sources.list`

```
deb http://ports.ubuntu.com/ focal main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal main restricted universe multiverse

deb http://ports.ubuntu.com/ focal-security main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal-security main restricted universe multiverse

deb http://ports.ubuntu.com/ focal-updates main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal-updates main restricted universe multiverse

deb http://ports.ubuntu.com/ focal-backports main restricted universe multiverse
#deb-src http://ports.ubuntu.com/ focal-backports main restricted universe multiverse
```
