### ISSUE TITLE
Kernel Panic: Chromium Streaming Youtube Video on Jammy/Bullseye with kernel 5.15.40/41-flippy-73+o

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#319]
Hi @ophub and other users,

I have been experiencing system freeze/kernel panic when streaming Youtube on Chromium on Jammy or Bullseye with kernel 5.15.40-flippy-73+o and kernel 5.15.41-flippy-73+o.

The system freeze can be random in the sense that sometimes after 10 minutes or 20 minutes of streaming Youtube video and other times I can stream for more than 60 minutes without any system freeze/kernel panic.  This happen on both Jammy with kernel 5.15.40-flippy-73+o and kernel 5.15.41-flippy-73+o. and Bullseye with kernel 5.15.40-flippy-73+o.

The last system freeze/kernel panic have happen 30 minutes ago on Jammy-5.15.41-flippy-73+o
```
jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FDTFILE='meson-g12b-gtking-pro.dtb'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
ANDROID_UBOOT='/usr/lib/u-boot/'
SOC='s922x-reva'
PACKAGED_DATE='2022-04-30'
KERNEL_VERSION='5.15.41'
K510='0'
```
I am wondering any other users on kernel 5.15.y experiencing system freeze while streaming video on Chromium?

**Comment by ophub** [comment]
I recently provided the /usr/sbin/armbian-kernel file in the firmware to support compiling the kernel in armbian. You can download this file to use. The kernel's selection configuration is further adjusted and optimized.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/usr/sbin/armbian-kernel

**Comment by JFLim1** [comment]
Hi @ophub,

Just a feedback and also wonder whether other users or yourself had experience this when streaming video using chromium (Bullseye) or chromium-browser (Jammy).

The advantage of using kernel 5.15.y-flippy is that I can boot on any of the USB Port on GT King Pro and it boot even when a HDD is also attached on the GT King Pro.  With kernel 5.10 or 5.17 using u-boot.ext it can only boot on USB OTG Port and NO other drive attached.  The downside with kernel 5.15 (without u-boot.ext) is the reported available RAM is 3.26GB instead of 3.70GB.

This system freeze/kernel panic when streaming video on Chromium is quite random but today it happen 3 times and yet right now I am streaming the same Youtube Video on Jammy-5.15.41-flippy-73+o -- now running for 1hr 22 minutes and still streaming.  

Earlier it system freeze/kernel panic after 15 minutes.

Will test with kernel-5.17.7-flippy-73+ on Bullseye as I have installed this few days ago.

**Comment by ophub** [comment]
Post this log and some of the previous content

**Comment by JFLim1** [comment]
Hi @ophub 

Additional update:
Bullseye-5.15.41-flippy-73+o
Kernel Panic at 81 minutes Chromium streaming video

**Bullseye-5.15.41-flippy-73+o "sudo armbian-update 5.17.9"**
Bullseye=5.17.9-flippy-73+ So far no issue with Chromium streaming the same video over 170 minute.

Looks like there conflict (or cache issue?)between Chromium streaming video and kernel-5.15.y-flippy-73+o

**Comment by ophub** [comment]
Ok, then you can use the 5.17 kernel for the time being. Yesterday, 5.18 was also released. Try it in a few days. In theory, the newer the kernel, the better the performance.

**Comment by JFLim1** [comment]
> Ok, then you can use the 5.17 kernel for the time being. Yesterday, 5.18 was also released. Try it in a few days. In theory, the newer the kernel, the better the performance.

Thanks. Await and looking forward to the new kernel-5.18.  

Looking forward to kernel-5.15.y-flippy being resolved to support Chromium Streaming Video.
