### ISSUE TITLE
Local Compile Steps Not Working

### ISSUE THREAD

**Issue by Wooty-B** [ophub/amlogic-s9xxx-armbian#320]
Le Potato S905X w/ Armbian (Kernel 5.9.14)

When following "Run under Ubuntu system", I get error:
```[ERROR] Supports running on Ubuntu: [ jammy / focal ]```

When following "Run under Armbian system", I get error:
```sudo: armbian-kernel: command not found```

How do I need to proceed in order to compile the kernel locally? Thanks!

**Comment by ophub** [comment]
```
sudo wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-kernel -O /usr/sbin/armbian-kernel
sudo chmod +x /usr/sbin/armbian-kernel
armbian-kernel -update
armbian-kernel -d
```
