### ISSUE TITLE
TX9 pro WIFI 驱动

### ISSUE THREAD

**Issue by wsadzxc23** [ophub/amlogic-s9xxx-armbian#321]
Hi，

     我用了5月20日发布的Armbian_22.05.0_Aml_s912_focal_5.10.117_server_2022.05.20.img，选择了tx9 pro的设备树文件后发现并没有出现新的无线接口，依旧只有eth0没有wlan0。
     我看到之前issue中提到的TX9 pro使用的无线网卡是AP6255，为了验证新增加的无线驱动无效的原因，我把我手上的TX9 pro拆开了，发现TX9 pro使用的是Cdtech 2010230 .
     这是我找到的这款模组的产品介绍地址：
      http://www.cdtech.cn/Product/show/102.html

![626058126945849268](https://user-images.githubusercontent.com/59075221/169636097-6bb7d64d-fa7e-4d6b-bffd-f6599d4500d5.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/315

**Comment by yuhhuy1711** [comment]
> Hi，
> 
> ```
>  我用了5月20日发布的Armbian_22.05.0_Aml_s912_focal_5.10.117_server_2022.05.20.img，选择了tx9 pro的设备树文件后发现并没有出现新的无线接口，依旧只有eth0没有wlan0。
>  我看到之前issue中提到的TX9 pro使用的无线网卡是AP6255，为了验证新增加的无线驱动无效的原因，我把我手上的TX9 pro拆开了，发现TX9 pro使用的是Cdtech 2010230 .
>  这是我找到的这款模组的产品介绍地址：
>   http://www.cdtech.cn/Product/show/102.html
> ```
> 
> ![626058126945849268](https://user-images.githubusercontent.com/59075221/169636097-6bb7d64d-fa7e-4d6b-bffd-f6599d4500d5.jpg)

i have same box and use meson-gxm-tx9-pro.dtb but still panic, use the latest version on [release ](https://github.com/ophub/amlogic-s9xxx-armbian/releases) page
