### ISSUE TITLE
可以定时重启吗

### ISSUE THREAD

**Issue by 3136083906** [ophub/amlogic-s9xxx-armbian#322]
如题，重启之后mac地址会变吗

**Comment by ophub** [comment]
```
# 编辑
crontab -e

# 最后一行添加，保存和vim一样（先按esc  再:wq!）
0 3 * * * /sbin/reboot

# 重新加载服务使配置生效
service cron restart
```

**Comment by 3136083906** [comment]
> ```
> # 编辑
> crontab -e
> 
> # 最后一行添加，保存和vim一样（先按esc  再:wq!）
> 0 3 * * * /sbin/reboot
> 
> # 重新加载服务使配置生效
> service cron restart
> 
> # 通过service查看下是否生效了
> service cron status
> ```
> 
> 
>      
>   
> 
> 想固定IP可以在 `路由器的DHCP设置或者ARP绑定` 里面将盒子的 `Mac地址分配一个固定的IP`

好的谢谢
