### ISSUE TITLE
Kernel Panic on B860H

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#323]
Dear @ophub,
I've try to using wireless on my B860H STB, but i don't know why, kernel panic is happen

I'm using 5.15.y kernel
![IMG_20220523_132125.jpg](https://user-images.githubusercontent.com/33513626/169756611-d6983111-0122-4d76-9ccc-d214c23c944c.jpg)

And if I'm not forgot, HG680P has same issues... Hmmm

**Comment by ophub** [comment]
There is currently no wifi in 5.15.41-flippy-73+o. It was added a few days ago. It is currently available in 5.10.117-ophub. You can use the 5.15 wifi after the next version of the kernel is released.
