### ISSUE TITLE
硬盘使用 NTFS3 挂载后中文文件/目录不能显示

### ISSUE THREAD

**Issue by Quanuanc** [ophub/amlogic-s9xxx-armbian#325]
ntfs 硬盘使用 `mount -t ntfs3 /dev/sda1 /mnt/ext` 命令挂载后，执行 `ls` 中文路径变成了 `_`。

搜索了一番后发现和[这个链接](https://github.com/coolsnowwolf/lede/issues/7072)的情况类似，里边说加上 `-o nls=utf8`挂载参数后就正常了，但是我试了一下并不成功，显示 `mount: /mnt/ext: wrong fs type, bad option, bad superblock on /dev/sda1, missing codepage or helper program, or other error.`错误。

我的机器：HK1 Box，目前刷的是这个系统：[Armbian_22.05.0_Aml_s905x3_jammy_5.15.41_server_2022.05.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_server_05.21.1222/Armbian_22.05.0_Aml_s905x3_jammy_5.15.41_server_2022.05.21.img.gz)

**Comment by ophub** [comment]
如果长期在linux下使用，建议磁盘格式使用exFAT
linux对ntfs支持不是很好

**Comment by Quanuanc** [comment]
看起来是 ntfs3 还不够成熟，再等一段时间好了。

**Comment by YanceyChiew** [comment]
这个问题比较坑，`nls=utf8` 这个选项在ntfs3驱动里面没有，取而代之的是 `iocharset=utf8`，此外好些选项都没有或者无效，比如控制权限的选项，要用另外的选项代替。

例：
```bash
mount -t ntfs3 -o nofail,iocharset=utf8,umask=000,noacsrules,x-systemd.device-timeout=10ms /dev/disk/by-label/storage /meida/storage
```

**Comment by cupid5trick** [comment]
正好我这里也有个类似的问题：把windows系统的一个NTFS格式的数据分区通过ntfs3挂载到Linux，结果分区下面的中文路径全都显示不出来了。

挂载参数是

```bash
/dev/disk/by-uuid/xxxxxx ntfs3 /usr/local/data iocharset=utf8 xxxxxxxxxxx
```
我觉得可能是因为windows系统默认用gbk编码，我就改成了 `iocharset=cp936`，再次挂载以后中文路径变成了一串二进制码：

```bash
ls
''$'\326\330''
```

我想知道这种情况怎么知道应该用什么编码呢？

**Comment by YanceyChiew** [comment]
> 我觉得可能是因为windows系统默认用gbk编码，我就改成了 `iocharset=cp936`

实际ntfs使用的是utf16编码的unicode，驱动很清楚这一点，所以 iocharset 选项的作用只是在读出后和写入前进行一次翻译。

具体来说，驱动内部读出来的文件名编码本来应该是utf16, 而你用 iocharset 指定驱动将这个文件名翻译成了gbk编码，读到这个编码的程序 ls 不认它，于是以16进制转义序列的方式输出。

```bash
 echo $'\326\330'|iconv -f cp936 -t utf8
```
  : 重

如果你确定真实的文件名是以上面这个字开头的，那就应该用utf8编码没错。你要解决的问题是无法显示utf8编码的字符。


```bash
echo 草|iconv -t utf8|cat
```
  :草

或者将 iocharset 设置为当前 `locale` 中实际使用的编码。

**Comment by cupid5trick** [comment]
明白了，iocharset=utf8是没有问题的。驱动本身能够正确解读NTFS分区的编码，只不过需要这个参数来“翻译“为能在终端正确显示的字符。现在问题已解决，又学到新知识了。
——
按照这个思路去检查了一遍，最后发现gnome-terminal和ssh的xterm-256都能正常显示。我在调整fstab的时候进入了救援模式，重启之后挂载出错导致还是进入救援模式，就以为是字符编码的问题。实际上只是救援模式的shell不支持中文字符，mount -a以后进入系统一切正常。
