### ISSUE TITLE
Disable Debug On Console

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#327]
Dear @ophub,

Did you know how to disable debug view from console that directly from STB (from ssh is not showing)

Thanks

![IMG_20220524_170324.jpg](https://user-images.githubusercontent.com/33513626/170006691-f3bd8966-6cb6-4ab0-a21d-d486dc6da984.jpg)

**Comment by ophub** [comment]
do not know
