### ISSUE TITLE
Unstable wifi Tanix TX3 Max rtl8723bs

### ISSUE THREAD

**Issue by Smim0** [ophub/amlogic-s9xxx-armbian#328]
Hi

Wifi is working but extremely unstable in Tv Box Tanix TX3 Max with S905W, during boot there is this weird message

`rtl8723bs: acquire FW from file:rtlwifi/rtl8723bs_nic.bin`

BTW wifi works fine with coreelec for example

**Comment by ophub** [comment]
The wireless module is brought by the mainline kernel. If the use is unstable, turn off the wireless and use the limited network.
