### ISSUE TITLE
Compile and install kernel modules

### ISSUE THREAD

**Issue by NewbieOrange** [ophub/amlogic-s9xxx-armbian#33]
Hi,

I want to install this kernel module: https://github.com/ChalesYu/rtl8822bs-aml

However, it is looking for kernel sources like this structure:

https://stackoverflow.com/questions/16688138/building-lib-modules-uname-r-build-while-compiling-a-kernel

Can we get something like this?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/8ca50e02bb101dff77753faa3b29890875ea075b/rebuild#L185

I deleted it during the rebuild, you can customize the kernel if you need it, don’t delete it.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/recompile#L202

**Comment by ophub** [comment]
You can also unzip and find this file in the kernel package file, E.g:

https://github.com/ophub/kernel/tree/main/pub/stable/5.10.80

`modules-5.10.80-flippy-67+.tar.gz`

**Comment by NewbieOrange** [comment]
Maybe we can keep the build files in future versions? They are not too huge in size, but are very helpful when installing kernel modules (drviers, etc).

**Comment by NewbieOrange** [comment]
> You can also unzip and find this file in the kernel package file, E.g:
> 
> https://github.com/ophub/kernel/tree/main/pub/stable/5.10.80
> 
> `modules-5.10.80-flippy-67+.tar.gz`

I unzipped the package, but there is only `include/`.

![Screenshot](https://user-images.githubusercontent.com/7200314/142870076-ee74b063-a67f-478f-979a-0d116f100ae0.png)

Other directories are also needed for module installation.

**Comment by ophub** [comment]
As can be seen from the above firmware package and kernel compiled code. Nothing was deleted when the kernel was compiled and packaged. Just deleted these 2 soft-link during installation.

**Comment by NewbieOrange** [comment]
I got it working by directly git clone from https://github.com/unifreq/linux-5.4.y! Thanks for you help

**Comment by thanhhieuqb** [comment]
> I got it working by directly git clone from https://github.com/unifreq/linux-5.4.y! Thanks for you help

Can you make me a guide to compile rtl8822bs driver on armbian? Thanks.
