### ISSUE TITLE
Kernel update failed

### ISSUE THREAD

**Issue by snbdot** [ophub/amlogic-s9xxx-armbian#331]
hi

using bullseye armbian downloaded before,   now command "armbian-update"  updating kernel failed.

do the bullseye still supporting?

thinks bro

**Comment by ophub** [comment]
supporting…

send log

**Comment by snbdot** [comment]
update manually, thanks anyway

**Comment by JFLim1** [comment]
Hi @ophub,



> # Download the latest version of the kernel update script
> wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-update -O /usr/sbin/armbian-update

Yesterday, updated the "armbian-update" as per above instruction.  After the updated the new "armbian-update", tried to update to new kernel 5.15.43 with "sudo armbian-update 5.15.43".

It failed 3 times "Error: /usr/sbin/armbian-update..." can't remember the exact wording.  

Then I perform "sudo apt update"  after that "sudo armbian-update 5.15.43" perform successfully.  I notice the new updated "armbian-update" now load/check for dependencies as compared to previous older version.

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/stable

The kernel is downloaded from github.com to keep your network running smoothly.

Various series of kernels can be switched, such as `armbian-update 5.17.11`

You can switch between different series to test what is wrong, and post the screenshots.

**Comment by JFLim1** [comment]
> You can switch between different series to test what is wrong, and post the screenshots.

@ophub 
Noted.  Will update to your newest "armbian-update" and will kernel update.

**Comment by JFLim1** [comment]
Hi @ophub 

Just an updated.  Upgraded GT King Pro Rev A Bullseye to kernel 5.17.12 successfully with armbian-update (dated 16 May)

![image](https://user-images.githubusercontent.com/75384411/171086778-f175500a-37d9-430f-88f1-f9f2fd256794.png)

```
jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
FDTFILE='meson-g12b-gtking-pro.dtb'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
ANDROID_UBOOT='/usr/lib/u-boot/'
SOC='s922x-reva'
PACKAGED_DATE='2022-05-16'
KERNEL_VERSION='5.17.12'
K510='1'
jfl@armbian:~$ cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=odroidn2
BOARD_NAME="Odroid N2"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=03d2395d37
VERSION=22.05.1
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
jfl@armbian:~
```
Just to hightlight that updated Bullseye to Armbian version 22.05.1 causes the Firmware/Image being being able to boot.  The suspected modules that cuases this are:

```
armbian-bsp-cli-odroidn2/bullseye 22.05.1 arm64 [upgradable from: 22.05.0-trunk]
armbian-config/bullseye,bullseye 22.05.1 all [upgradable from: 22.05.0-trunk]
linux-u-boot-odroidn2-current/bullseye 22.05.1 arm64 [upgradable from: 22.05.0-trunk]
```

After the update to Armbian V22.05.1 the following files in /boot are over-written:
```
boot.cmd
boot.scr
```

Which casuses the Updated Image NOT bootable.  With the newly created boot.cmd/boot.scr it basically looks for Odroid-N2 dtb etc to boot which will failed with "Time Out". 

Reverting/restore boot.cmd and boot.scr to your original file (copy) resolve the non-bootable issue.  So advise users to backup boot.cmd and boot.scr

A new file is added:
`armbianEnv.txt`

This "armbianEnv.txt" file doesn't seems to affect GT King Pro Rev A.

**Comment by JFLim1** [comment]
Hi @ophub 

Just performed "sudo apt update and uprade" on Jammy-5.15.43-flippy-73+o image.

```
jfl@armbian:~$ uname -a
Linux armbian 5.15.43-flippy-73+o #125 SMP PREEMPT Wed May 25 21:12:32 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FDTFILE='meson-g12b-gtking-pro.dtb'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
ANDROID_UBOOT='/usr/lib/u-boot/'
SOC='s922x-reva'
PACKAGED_DATE='2022-04-30'
KERNEL_VERSION='5.15.43'
K510='0'
jfl@armbian:~$ cat /etc/armbian-release
# PLEASE DO NOT EDIT THIS FILE
BOARD=lepotato
BOARD_NAME="Le potato"
BOARDFAMILY=meson-gxl
BUILD_REPOSITORY_URL=https://github.com/armbian/build
BUILD_REPOSITORY_COMMIT=03d2395d37
VERSION=22.05.1
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image
jfl@armbian:~$ 
```
Interestingly, uprading armbian-bsp-cli-lepotato linux-u-boot-lepotato-edge does NOT generate new "boot.cmd or boot.scr" like in Bullseye where uprading armbian-bsp-cli-odroidn2 linux-u-boot-odroidn2-edge generated new "boot.cmd and boot.scr" which made the Bullseye image NOT bootable.

**Comment by ophub** [comment]
Armbian 22.05.1 `Focal` with Linux 5.17.12-flippy-73+

![Snip20220531_3](https://user-images.githubusercontent.com/68696949/171139548-469409c3-c0a9-4f81-b90b-ddf6c4edd9fb.png)
![Snip20220531_4](https://user-images.githubusercontent.com/68696949/171139572-7e2f391f-94cc-4966-af59-7295fb2d6ebf.png)
