### ISSUE TITLE
kernel deb package

### ISSUE THREAD

**Issue by LoganScar** [ophub/amlogic-s9xxx-armbian#333]
is it possible too build image for x96maxplus with kernel as a deb package

**Comment by snbdot** [comment]
also,

what's the difference between S905D and S905D-ki ?

did N1 using S905?

thanks alot

**Comment by ophub** [comment]
N1 use s905d

**Comment by ophub** [comment]
> 

In order to share the kernel with Android, the tar format is used, and the function is the same
