### ISSUE TITLE
N1 刷 Armbian_22.05.0_Aml_s905d_jammy_5.15.43_server_2022.05.27.img.gz 用U盘启动，显示器显示无效输入

### ISSUE THREAD

**Issue by jiutianhuanpei** [ophub/amlogic-s9xxx-armbian#336]
rt

**Comment by ophub** [comment]
解压缩成.img，用https://rufus.ie/ 写入U盘，先插入离hdmi近的usb口，再插入电源。
如果是新n1原厂安卓系统，看一下先降级才能从usb启动，百度搜n1降级方法

**Comment by jiutianhuanpei** [comment]
我是Mac 电脑，用的是 balenaEtcher 写的U盘，整个刷机流程应该都是没问题的，因为我刷别的包都是可以的，只有这几个 aml_s905d_* 的包显示不出来

**Comment by ophub** [comment]
我刚试了一下可以。你下5.10的试一下，或者重新下载一下再试。
