### ISSUE TITLE
问下大大，目前s9xxx支持RTL8723BS驱动吗？

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#337]
又搞到了一块板子 s905x3带的rtl8723bs，千兆 4+32，U盘能启动，能扫描到wifi信号，但连不上，一连就死机，所以想问下关于这款驱动目前的支持情况 :-)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/4886512d9df6c54299b7381b4e7617eb22af7ac7/compile-kernel/tools/config/config-5.15.43#L6151

内核里有这个驱动，应该可以使用，更新4个不同系列的内核看哪个支持的好

**Comment by EastWoodYang** [comment]
[5.4.196](https://github.com/ophub/kernel/tree/main/pub/stable/5.4.196) 疯狂输出error
[5.10.119](https://github.com/ophub/kernel/tree/main/pub/stable/5.10.119)  疯狂输出error
[5.15.44](https://github.com/ophub/kernel/tree/main/pub/stable/5.15.44) 无法从U盘启动
[5.17.12](https://github.com/ophub/kernel/tree/main/pub/stable/5.17.12) 稍微正常一些，情况如下：

8723相关日志：
```
root@lepotato:~# dmesg | grep -i 8723
root@lepotato:~# insmod r8723bs.ko 
root@lepotato:~# dmesg | grep -i 8723
[  237.998301] r8723bs: module is from the staging directory, the quality is unknown, you have been warned.
[  238.058675] rtl8723bs mmc0:0001:1 wlan0: rtw_ndev_notifier_call(wlan0) state:5
[  238.131773] rtl8723bs mmc0:0001:1 wlan0: rtw_ndev_notifier_call(wlan0) state:14
[  238.145363] rtl8723bs: acquire FW from file:rtlwifi/rtl8723bs_nic.bin
[  239.397755] rtl8723bs mmc0:0001:1 wlan0: rtw_ndev_notifier_call(wlan0) state:1
[  239.415795] rtl8723bs mmc0:0001:1 wlan0: rtw_ndev_notifier_call(wlan0) state:4
[  239.512760] rtl8723bs mmc0:0001:1 wlan0: rtw_ndev_notifier_call(wlan0) state:4
```
能扫描到wifi，但一连就报错死机Dead：
<img width="873" alt="1653958050(1)" src="https://user-images.githubusercontent.com/9335046/171072155-dfa529d8-4e92-470d-825e-9f65d9fff10c.png">

**Comment by ophub** [comment]
你使用的是今天的固件吗？周末我添加了些固件，不知道有没帮助。

**Comment by EastWoodYang** [comment]
我明早再尝试下看看

**Comment by EastWoodYang** [comment]
早上试了下还是一样，放弃了。。。
