### ISSUE TITLE
Full Firmware Package not installing

### ISSUE THREAD

**Issue by DiogoSilva48** [ophub/amlogic-s9xxx-armbian#338]
Hi. I was using a very old version and formatted the SD Card today with the latest Jammy build 5.15 on my S905X and I was trying to install the full firmware package (needed for my Wifi to work) and doesn't work, switches two times between "Loading full submodule..." and "Please wait..." with a progress bar, always at 0%, after that returns to the same menu with nothing installed. Any idea? thanks

**Comment by ophub** [comment]
What is your wireless chip? It cannot be used without a wireless driver. A wired connection can be used.

**Comment by DiogoSilva48** [comment]
My wireless chip is QCA9377, the driver is there, the only thing missing is the firmware, after adding it wifi works fine, I can add it manually (like we talked here https://github.com/ophub/amlogic-s9xxx-armbian/issues/98 ) but installing the full firmware package was a lot easier and saved some time.

**Comment by ophub** [comment]
Compress a .zip file from your normal debugging directory (/lib/firmware/ath10k/) and upload it here, I will add it to the default firmware.

**Comment by ophub** [comment]
I just added to the default firmware

**Comment by DiogoSilva48** [comment]
Haven't tried it yet. Sorry to ask here but I don't want to open another issue @ophub I have a problem rebuilding an image, if I put 6000 or 6500 on the size, I get an error uploading an image too big, If I put 5000 I get errors with CP command, no space left but completes and uploads. Any idea what's the ideal size for jammy with xfce? Even if I have to build from scratch instead of rebuilding.

**Comment by ophub** [comment]
https://armbian.tnahosting.net/dl/odroidn2/archive/

This is the official download address, you can refer to its size.

github restricts that a single file cannot exceed 2g, and if it exceeds, it cannot be uploaded to releases

**Comment by DiogoSilva48** [comment]
> https://armbian.tnahosting.net/dl/odroidn2/archive/
> 
> This is the official download address, you can refer to its size.
> 
> https://docs.github.com/cn/repositories/working-with-files/managing-large-files/about-large-files-on-github
> 
> github restricts that a single file cannot exceed 2g, and if it exceeds, it cannot be uploaded to releases

Thanks, gonna look into it.
Also, the size we write is in what unit? like mb, gb, etc, etc.

**Comment by ophub** [comment]
You can upload to other network disks and find the interfaces of other service providers yourself.
2Gb

**Comment by DiogoSilva48** [comment]
You didn't understand my question
<img width="313" alt="image" src="https://user-images.githubusercontent.com/38466084/170874590-baf614c3-53a5-4d45-b34c-1f92d9fec986.png">
I meant, the size we write here, it in what unit? doesn't say, just asks for a value.

**Comment by ophub** [comment]
Mb

**Comment by DiogoSilva48** [comment]
> MiB
> 
> [781bcb1](https://github.com/ophub/amlogic-s9xxx-armbian/commit/781bcb127f56f2e0eb634008d6a38461bd2a0a98)
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/6943978fca18c46c097bd49230bef34227da8524/rebuild#L80

Thank you very much. Sorry to bother again, if I wanted to upload to google drive, using this https://github.com/marketplace/actions/google-drive-upload-git-action , to specify the name of the artifact, in this case the "filename" should be with this "${{ env.PACKAGED_OUTPUTPATH }}/*" ??

**Comment by DiogoSilva48** [comment]
Ok, I was able to find an easy way to download the bigger files.
<img width="705" alt="image" src="https://user-images.githubusercontent.com/38466084/170881933-ccf14f6d-0735-4011-87ed-14d78b661364.png">
<img width="1082" alt="image" src="https://user-images.githubusercontent.com/38466084/170881946-01f73341-7edc-4a0b-ae0b-ab1c4ca1ca91.png">
the ending result is like this, the artifact is down there, you just click on it to download.

**Comment by DiogoSilva48** [comment]
Thanks so much, Wifi is now working out of the box.

**Comment by ophub** [comment]
very good
