### ISSUE TITLE
why UBOOT_OVERLOAD seted by default for s905x3 images?

### ISSUE THREAD

**Issue by SajjadSabzkar** [ophub/amlogic-s9xxx-armbian#339]
Hi @ophub 
Why  UBOOT_OVERLOAD setted by default for s905x3 images but for i when use github action for release  UBOOT_OVERLOAD  not setted by default ?

**Comment by ophub** [comment]
5.15/5.4 kernel do not need, 5.10/5.17 kernel need.

**Comment by SajjadSabzkar** [comment]
> Not sure what you mean by asking. It means that there is no problem of using UBOOT_OVERLOAD in 5.15 kernel?
> 
> 5.15/5.4 kernel do not need（TEXT_OFFSET patch added in 5.15/5.4 kernel）, 5.10/5.17 kernel need.
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/060f379ea890cb542f66b0dfc362078541e82bc0/rebuild#L101


Oh sorry i mean s905x3 images that do not need to be UBOOT_OVERLOAD when they are released
Set for them (I mean change the .bin file to u-boot.ext).

**Comment by ophub** [comment]
I don't understand what you mean

**Comment by SajjadSabzkar** [comment]
I noticed that the focal version for s905x3 devices automatically has u-boot.ext and does not need to be changed, just apply the specified dtb in the uENV.txt file. My question was why this is done automatically in your release versions, but not in the images I release. Apparently this does not happen in all versions. One of the versions for which this happens is Armbian_22.05.0_Aml_s905x3_focal_5.15.26_2022.03.04.2221.img.gz
Was. Thank you for your attention

**Comment by ophub** [comment]
see above explanation
