### ISSUE TITLE
BT support

### ISSUE THREAD

**Issue by pulpoff** [ophub/amlogic-s9xxx-armbian#34]
I have seen that BT wasn't working due to missing firmware file.
BCM4362A2.hcd should be put as /lib/firmware/brcm/BCM.hcd
Now BT works fine, tested with bt speaker, also it sees many other devices around.
File is posted at https://vp5.net/king/

**Comment by ophub** [comment]
Is this for a specific device?

**Comment by pulpoff** [comment]
i guess this is general as well, i think only wifi is specific to my board.

**Comment by ophub** [comment]
Thanks for sharing

**Comment by fooy** [comment]
does it work with X96 max/hk1 ?  could you share the detail
