### ISSUE TITLE
cannot access '/dev/dvb': No such file or directory

### ISSUE THREAD

**Issue by Unicorn9x** [ophub/amlogic-s9xxx-armbian#341]
Dear Ophub and all,
I'm using Armbian_22.05.0_Aml_s905x3_jammy_5.10.118_server_2022.05.29 on H96_Max_X3.
I plug in the MyGica-T230C USB for TVHeadend. Mapping /dev/dvb as instructed in Portainer
![image](https://user-images.githubusercontent.com/19651415/170855435-a0c2577e-a104-4680-abbf-9b25439943c0.png)

But TVHeadend couldn't see it in TV adapters
![image](https://user-images.githubusercontent.com/19651415/170855357-5e65c49a-13f2-4506-b859-7636adf58733.png)

On Armbian I tried:

dmesg
![image](https://user-images.githubusercontent.com/19651415/170855592-f7eaf854-d546-4ddf-860f-a5d3044a8194.png)

lsusb
![image](https://user-images.githubusercontent.com/19651415/170855612-fdae8cee-6d69-498f-95a6-c23f482863d3.png)

ls /dev/dvb
![image](https://user-images.githubusercontent.com/19651415/170855632-8d9fc913-6d29-4d93-889b-154a703ea759.png)

I think the driver is not installed? or the module is not loaded?

I found the Linux / raspberry driver here: https://www.mygica.com/support/
Also found a patch file here for armbian: https://github.com/bschwehn/armbian-build/blob/master/patch/kernel/sunxi-dev/v3-2-2-dvbsky-Add-support-for-MyGica-T230C-v2.patch

Could you tell me how I can install the driver or do anything to use this MyGica-T230C USB device? Thank you in advance!

**Comment by ophub** [comment]
The usb you insert is in different devices, and the same device may display different names when inserted, such as sda, sdb, etc., use the `df` command to view your specific name

**Comment by Unicorn9x** [comment]
> df

Hi Ophub,
I tried df
![image](https://user-images.githubusercontent.com/19651415/170881904-fb139803-75b7-4667-8077-6076ed91371f.png)

ls /dev
![image](https://user-images.githubusercontent.com/19651415/170882656-2400e953-44cc-4134-ad5c-ba5db7b4f0ec.png)

still don't know how should I proceed?

**Comment by ophub** [comment]
The system does not recognize your disk format, use the format supported by linux

**Comment by Unicorn9x** [comment]
can somebody help me? :(

**Comment by MX10-AC2N** [comment]
Hi @Unicorn9x 
Have you tried installing the full firmware with armbian-config. Maybe it will add the drivers you are missing..
Good luck

**Comment by Unicorn9x** [comment]
> Hi @Unicorn9x Have you tried installing the full firmware with armbian-config. Maybe it will add the drivers you are missing.. Good luck

Hi bro @MX10-AC2N 
Thanks for your reply
I tried in armbian-config but it run for a few seconds with this screen and back to the selection menu
![image](https://user-images.githubusercontent.com/19651415/171664667-99b76a4d-f159-4d85-9628-4bbb793826aa.png)

I tried in the CLI, it's error: 
![image](https://user-images.githubusercontent.com/19651415/171664283-142177b9-9b52-4574-9e44-ec54a8968083.png)

Do you know how to proceed?

**Comment by MX10-AC2N** [comment]
It's strange
``` sudo apt show armbian-firmware*
Package: armbian-firmware
Version: 22.05.1
Priority: optional
Section: kernel
Maintainer: Igor Pecovnik <igor.pecovnik@****l.com>
Installed-Size: 1 024 B
Replaces: linux-firmware, firmware-brcm80211, firmware-ralink, firmware-samsung, firmware-realtek, armbian-firmware-full
Download-Size: 8 002 kB
APT-Sources: http://apt.armbian.com bullseye/main arm64 Packages
Description: Linux firmware

Package: armbian-firmware-full
Version: 22.05.1
Priority: optional
Section: kernel
Maintainer: Igor Pecovnik <igor.pecovnik@****l.com>
Installed-Size: 1 024 B
Replaces: linux-firmware, firmware-brcm80211, firmware-ralink, firmware-samsung, firmware-realtek, armbian-firmware
Download-Size: 261 MB
APT-Sources: http://apt.armbian.com bullseye/main arm64 Packages
Description: Linux firmware-full
```
```
 cat /etc/apt/sources.list
deb http://deb.debian.org/debian bullseye main contrib non-free
deb-src http://deb.debian.org/debian bullseye main contrib non-free

deb http://deb.debian.org/debian bullseye-updates main contrib non-free
deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free

deb http://deb.debian.org/debian bullseye-backports main contrib non-free
deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free

deb http://security.debian.org/ bullseye-security main contrib non-free
deb-src http://security.debian.org/ bullseye-security main contrib non-free
```
```
cat /etc/apt/sources.list.d/armbian.list
deb http://apt.armbian.com bullseye main bullseye-utils bullseye-desktop
```
You can try armbian-config => Personal => Reconfigure apt

**Comment by Unicorn9x** [comment]
> It's strange
> 
> ```
> sudo apt show armbian-firmware*
> Package: armbian-firmware
> Version: 22.05.1
> Priority: optional
> Section: kernel
> Maintainer: Igor Pecovnik <igor.pecovnik@****l.com>
> Installed-Size: 1 024 B
> Replaces: linux-firmware, firmware-brcm80211, firmware-ralink, firmware-samsung, firmware-realtek, armbian-firmware-full
> Download-Size: 8 002 kB
> APT-Sources: http://apt.armbian.com bullseye/main arm64 Packages
> Description: Linux firmware
> 
> Package: armbian-firmware-full
> Version: 22.05.1
> Priority: optional
> Section: kernel
> Maintainer: Igor Pecovnik <igor.pecovnik@****l.com>
> Installed-Size: 1 024 B
> Replaces: linux-firmware, firmware-brcm80211, firmware-ralink, firmware-samsung, firmware-realtek, armbian-firmware
> Download-Size: 261 MB
> APT-Sources: http://apt.armbian.com bullseye/main arm64 Packages
> Description: Linux firmware-full
> ```
> 
> ```
>  cat /etc/apt/sources.list
> deb http://deb.debian.org/debian bullseye main contrib non-free
> deb-src http://deb.debian.org/debian bullseye main contrib non-free
> 
> deb http://deb.debian.org/debian bullseye-updates main contrib non-free
> deb-src http://deb.debian.org/debian bullseye-updates main contrib non-free
> 
> deb http://deb.debian.org/debian bullseye-backports main contrib non-free
> deb-src http://deb.debian.org/debian bullseye-backports main contrib non-free
> 
> deb http://security.debian.org/ bullseye-security main contrib non-free
> deb-src http://security.debian.org/ bullseye-security main contrib non-free
> ```
> 
> ```
> cat /etc/apt/sources.list.d/armbian.list
> deb http://apt.armbian.com bullseye main bullseye-utils bullseye-desktop
> ```
> 
> You can try armbian-config => Personal => Reconfigure apt

Hi bro, thank you!
I switched from jammy to bullseye and followed your instruction, I'm able to install arm-firmware-full. Sudo reboot => But the ls /dev/dvb still blank.

I found this thread https://tvheadend.org/boards/5/topics/28100
According to https://www.linuxtv.org/wiki/index.php/Geniatech_T230C 
I need the driver dvb_usb_cxusb
I clone the git and use the instruction here to build the driver: https://github.com/crazycat69/media_build
and I stuck with the error. Could you shed some light so I can proceed?
![image](https://user-images.githubusercontent.com/19651415/172020032-290aaa24-b2b3-43f6-85d3-badc9bfaf1d2.png)

**Comment by MX10-AC2N** [comment]
```
Preparing to compile for kernel version 5.10.119
File not found: /lib/modules/5.10.119-ophub/build/.config at ./scripts/make_kconfig.pl line33, <IN> line 4.
```
Search in /lib/modules if there is any folder 5.10.119 .. `file not found` it's the problem..

**Comment by Unicorn9x** [comment]
> /lib/modules

I checked with the modules found here https://github.com/ophub/kernel/tree/main/pub/stable/5.10.119
There is a symbolic link and couldn't located the .config file. Hi @ophub could you help with this? I try to build the driver but it's missing something here.
![image](https://user-images.githubusercontent.com/19651415/172046089-fef1fd55-3c4d-4d11-a604-ec21110299ba.png)

**Comment by ophub** [comment]
/boot/config-*

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/363#issuecomment-1147067790

**Comment by Unicorn9x** [comment]
> `ls /boot/config-$(uname -r)`
![image](https://user-images.githubusercontent.com/19651415/172196695-a9db40a4-eb43-422e-a646-d3cbe691d166.png)

ok, so I understand the basics. 
I put a symbolic link .config to your config file in /boot/ then run the ./build command again, now it's run for a while then I see this, check line 561 couldn't see what is still missing? really appreciate your support! @ophub @MX10-AC2N 
![image](https://user-images.githubusercontent.com/19651415/172196518-607d1f28-e96b-4581-84e7-9924fcb40c2f.png)

**Comment by ophub** [comment]
The V4L-DVB Device Drivers official website has a detailed compilation tutorial, you can ask questions in his Q&A area. I haven't used this and don't know how his error should be fixed.

https://www.linuxtv.org/wiki/index.php/Talk:How_to_Obtain,_Build_and_Install_V4L-DVB_Device_Drivers

**Comment by MX10-AC2N** [comment]
The headers files in the kernel is installed in the `/usr/local/include` directory..
Good luck..

**Comment by Unicorn9x** [comment]
> from https://www.linuxtv.org/wiki/index.php/Talk:How_to_Obtain,_Build_and_Install_V4L-DVB_Device_Drivers `` Finally, let's make sure we have the /lib/modules/`uname -r`/build directory pointing to THE HEADERS... NOT THE KERNEL SOURCE. ``

thank bro!
Took me a few days to understand the issue to try again. So what I did are:

![image](https://user-images.githubusercontent.com/19651415/173220919-60e928f3-5233-4399-aa51-ff6392ce0507.png)
1/ use armbian_config to install the Linux header file

2/ cd /usr/lib/modules/5.10.119-ophub/
![image](https://user-images.githubusercontent.com/19651415/173220998-d05fcb94-f42d-4b1f-9cd5-1f5325efda4f.png)

symlink folder build to the new Linux header downloaded in step 1 => this linux header have the correct file structure
ln -s /usr/src/linux-headers-5.10.110-meson64 build

=> build running for real now (around 10 - 15 mins), but still error at this line:

`  CC [M]  /root/media_build/v4l/mceusb.o
/root/media_build/v4l/mceusb.c: In function 'mceusb_dev_probe':
/root/media_build/v4l/mceusb.c:1731:9: error: too few arguments to function 'usb                    _maxpacket'
 1731 |  maxp = usb_maxpacket(dev, pipe);
      |         ^~~~~~~~~~~~~
In file included from /root/media_build/v4l/mceusb.c:29:
./include/linux/usb.h:1982:1: note: declared here
 1982 | usb_maxpacket(struct usb_device *udev, int pipe, int is_out)
      | ^~~~~~~~~~~~~
make[3]: *** [scripts/Makefile.build:280: /root/media_build/v4l/mceusb.o] Error                     1
make[2]: *** [Makefile:1822: /root/media_build/v4l] Error 2
make[2]: Leaving directory '/usr/src/linux-headers-5.10.110-meson64'
make[1]: *** [Makefile:53: default] Error 2
make[1]: Leaving directory '/root/media_build/v4l'
make: *** [Makefile:26: all] Error 2
build failed at ./build line 533
`

![image](https://user-images.githubusercontent.com/19651415/173220878-dcd22222-4f0c-4e41-a6e8-d32067171456.png)

Man, I just want to plug a DVB USB for tvheadend to use it but so many problems T_T!

**Comment by Unicorn9x** [comment]
Great news! Today I was able to compile the kernel and enable the DVB usb device. Thank you @ophub and @MX10-AC2N !
I followed the guideline here https://github.com/ophub/amlogic-s9xxx-armbian/issues/363#issuecomment-1147067790

1/ Forked the repo. Added a bunch of configs for DVB devices.
https://github.com/Unicorn9x/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.10.122

2/ Compile custom kernel, update then woah laaa \m/ USB device recognized and running smoothly now on TVheadend!

![image](https://user-images.githubusercontent.com/19651415/174489000-5d1ab0e5-85f5-4c27-967b-be1662f439e8.png)

**Comment by Unicorn9x** [comment]
> > Great news! Today I was able to compile the kernel and enable the DVB usb device. Thank you @ophub and @MX10-AC2N ! I followed the guideline here [#363 (comment)](https://github.com/ophub/amlogic-s9xxx-armbian/issues/363#issuecomment-1147067790)
> > 1/ Forked the repo. Added a bunch of configs for DVB devices. https://github.com/Unicorn9x/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.10.122
> > 2/ Compile custom kernel, update then woah laaa \m/ USB device recognized and running smoothly now on TVheadend!
> > ![image](https://user-images.githubusercontent.com/19651415/174489000-5d1ab0e5-85f5-4c27-967b-be1662f439e8.png)
> 
> hello, I want my mygica t230 to work on this armbian as well, did I just need to compile the kernel with your config and then build armbian with the kernel I just compiled?

that's correct, bro

**Comment by piotrekcrash** [comment]
@Unicorn9x @ophub is that possible that DVB will be enabled in Standard Releases?

**Comment by karnadii** [comment]
Agree, support for dvb device like mygica t230c or t230a would be great.

**Comment by piotrekcrash** [comment]
I'm using multiple Panasonic mn8847 (Xbox One USB Tuner) in the current setup it will be great to migrate with this to S905 Box with Armbian.

**Comment by martinlanger90** [comment]
Please enable USB DVB drivers in kernel in standard release @ophub as @piotrekcrash mentioned.

**Comment by Unicorn9x** [comment]
> Please enable USB DVB drivers in kernel in standard release @ophub as @piotrekcrash mentioned.


> @Unicorn9x @ophub is that possible that USB DVB will be enabled in Standard Releases?

I sent pull request but got rejected so I guess we have to do some self service here

**Comment by karnadii** [comment]
> 
> > Please enable USB DVB drivers in kernel in standard release @ophub as @piotrekcrash mentioned.
> 
> 
> > @Unicorn9x @ophub is that possible that USB DVB will be enabled in Standard Releases?
> 
> I sent pull request but got rejected so I guess we have to do some self service here
> 

Could you release the latest kernel on your fork with the dvb enabled config? I try to compile it myself with no luck @Unicorn9x

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/pull/385

@Unicorn9x In this merge, you modified compile-kernel.yml to point to your own repo. I understand that this is your own test. You accidentally clicked the wrong submission.


If you are modifying config-x.y to add a configuration, you only need to modify the config file. You can add dvb to several LTS kernel (5.4/5.10/5.15/6.1) configuration files and resubmit the merge.

**Comment by Unicorn9x** [comment]
> #385
> 
> @Unicorn9x In this merge, you modified compile-kernel.yml to point to your own repo. I understand that this is your own test. You accidentally clicked the wrong submission.
> 
> If you are modifying config-x.y to add a configuration, you only need to modify the config file. You can add dvb to several LTS kernel (5.4/5.10/5.15/6.1) configuration files and resubmit the merge.

Thank you, I resubmit the merge, please check and add. 
![image](https://user-images.githubusercontent.com/19651415/212532431-1e60a133-75f9-4e85-81ed-e289f909db86.png)

**Comment by ophub** [comment]
It has been merged, 5.4 and 6.1 are also added, the family bucket

**Comment by ophub** [comment]
The option you added has not been compiled and tested, right? A bunch of question marks. Make menuconfig must be selected first, and the compilation test is passed before submitting the merge

**Comment by martinlanger90** [comment]
as soon as the next version comes out, ill test on S905d (KI Pro) and see if it detects my DVB-C USB device

**Comment by ophub** [comment]
The kernel repo has been updated, you update the latest kernel test
`armbian-update -k 5.10.163`
or
`armbian-update -k 5.15.88`

**Comment by Unicorn9x** [comment]
> The kernel repo has been updated, you update the latest kernel test `armbian-update -k 5.10.163` or `armbian-update -k 5.15.88`

I reflashed the os to test and can confirm it's working as expected. Tested on Mygica T230C and Newsky DVB-T2 USB TV Receiver => both appeared in ls /dev/dvb 
![image](https://user-images.githubusercontent.com/19651415/212907201-896d9ddb-e76c-4897-90be-bb6e9c0c6780.png)
Thank you, bro! and happy lunar new year!

**Comment by ophub** [comment]
ok

**Comment by piotrekcrash** [comment]
@Unicorn9x @ophub I can also confirm that my tuner: Panasonic MN88472 works properly with the newest version:
![image](https://user-images.githubusercontent.com/8939242/213150063-78ee624e-7ccb-483d-a694-5acfe78e3e09.png)
After configuration in TVHeadend, all work properly. Thanks!

@Unicorn9x do you plan maybe to make the same Pull Request for kernel 6.X.X configuration?

**Comment by Unicorn9x** [comment]
> @Unicorn9x do you plan maybe to make the same Pull Request for kernel 6.X.X configuration?

I don't use that kernel and have no HW to test so I will pass.

**Comment by piotrekcrash** [comment]
@ophub thx - I can see that you already added DVB support to 6.x.x also. Will test it in the next few days.

**Comment by ophub** [comment]
The packaged armbian system uses the unifreq packaged kernel that I dumped in 5.15/6.1, and neither of these two kernels has added dvb support.
You need to use the kernel template to compile it yourself, or download the kernel packaged in [releases](https://github.com/ophub/amlogic-s9xxx-armbian/releases) and update it to armbian.


There is no dvb support added in the kernel warehouse. Add dvb support in releases.

**Comment by piotrekcrash** [comment]
@ophub I already installed the newest release and updated the kernel to 6.1.7 (armbian-update) 
but usb-dvb tuner is not working.  
![image](https://user-images.githubusercontent.com/8939242/214365571-9b0bce1d-7e95-4817-bc25-387833fe70ac.png)

**Comment by ophub** [comment]
see above description

**Comment by piotrekcrash** [comment]
@ophub  Sorry - You have a right and I wrongly understood. When installed kernel from your Releases (6.1.7) USB-DVB is recognized properly:
![image](https://user-images.githubusercontent.com/8939242/214528413-5ef6cbc0-28e8-4893-a389-4c680f30e5af.png)
Thanks for your work and support!

**Comment by intropedro** [comment]
Hello @Unicorn9x @piotrekcrash,

I'm trying to make the dvb of the Mecool KI Pro work but I can't. These are not usb, they are internal (R848, avl6211, and avl6862).

I have been reading this thread and from what I have understood in the end just putting the 5.10, 5.4 or manually the 5.15 or 6.1 kernel (As I describe here https://github.com/ophub/amlogic-s9xxx-armbian/issues/1001 #issuecomment-1417862393) already worked for you. Or did you have to do something else?

Alwais /dev/dvb not exist and in the dmesg there is nothing of dvb

**Comment by Unicorn9x** [comment]
Hello @intropedro , 
Regarding this issue, I suspect you need a driver for your device, you must find a linux driver support your dvb card on google and compile + install to your armbian then the kernel can pick it up to run, which is very troublesome. Buy a separate dvb usb is easier than this to be honest...
