### ISSUE TITLE
LightDM not starting up

### ISSUE THREAD

**Issue by DiogoSilva48** [ophub/amlogic-s9xxx-armbian#342]
LightDM doesn't start, my box is S905X, was happening when I installed the package myself along with a DE, so I rebuilt an image with XFCE in there already and the issues persist, any idea? Thanks.
<img width="585" alt="image" src="https://user-images.githubusercontent.com/38466084/170886964-59e8cf78-7d99-472b-a220-bddea9c89cc7.png">

**Comment by ophub** [comment]
```
sudo apt install ubuntu-desktop
sudo apt install lightdm
```

**Comment by DiogoSilva48** [comment]
> ```
> sudo apt install ubuntu-desktop
> sudo apt install lightdm
> ```
 I did
```
sudo apt install kubuntu-desktop
sudo apt install lightdm
```
before doing the xfce test and ran into the same issue mentioned, I assume it should be the same, right?

**Comment by ophub** [comment]
I failed to install xfce, but the command I sent succeeded. Maybe jammy has just been released, and further adaptation is needed

**Comment by DiogoSilva48** [comment]
> I failed to install xfce, but the command I sent succeeded. Maybe jammy has just been released, and further adaptation is needed

It's a bit late today here but tomorrow I'm gonna test the Ubuntu-Desktop on jammy and also installing desktop on the debian build and let you know. Thanks.

**Comment by ophub** [comment]
```
sudo apt install ubuntu-desktop
sudo apt install lightdm
```

Use this on jammy to install, what I'm using is installed like this.

**Comment by DiogoSilva48** [comment]
> ```
> sudo apt install ubuntu-desktop
> sudo apt install lightdm
> ```
> 
> Use this on jammy to install, what I'm using is installed like this.
> 
> #304
> 
> Others have installed it successfully
> 
> I just got up, why are you going to sleep, what country are you from?

I did the same but with Kubuntu for KDE instead of gnome, should be the same, but no idea.

I'm from Portugal it's 2:30AM right now, same time as in the UK, how about you?

**Comment by ophub** [comment]
I'm at UTC+8, 7 hours ahead of you, take a rest

**Comment by DiogoSilva48** [comment]
> Hi @DiogoSilva48 @ophub If you try install DE over a server release, I think you need install all packages present in config_base from Armbian so for bullseye xfce config_base package see here => https://github.com/armbian/build/blob/master/config/desktop/buster/environments/xfce/config_base/packages and for jammy xfce config_base package see here => https://github.com/armbian/build/blob/master/config/desktop/jammy/environments/xfce/config_base/packages
> 
> You can try for bullseye releases `wget https://raw.githubusercontent.com/armbian/build/master/config/desktop/buster/environments/xfce/config_base/packages` => download all packages list in file "packages" `apt install $(cat packages)` => for install from file "packages"
> 
> Good luck..

Thanks. Did this with gnome and worked, chose gdm3 while configuring lightdm, gonna try now with xfce and other DE's.

**Comment by DiogoSilva48** [comment]
@MX10-AC2N do you use any web browser with this armbian? If so, is it possible to have good hardware acceleration for stuff like videos? thanks.

**Comment by MX10-AC2N** [comment]
Hi @DiogoSilva48 
I don't know if there is any web browser better than other in Armbian, but in the install process for desktop Armbian always install firefox-esr and now for jammy it is a snap install..
For the Hardware acceleration, I'm not sure about how config this..
There is https://github.com/armbian/build/blob/master/config/desktop/buster/appgroups/3dsupport/packages
I think you need install this packages..

**Comment by DiogoSilva48** [comment]
> https://github.com/armbian/build/blob/master/config/desktop/buster/appgroups/3dsupport/packages

Thanks, sucks it's snap though ahah Did some research and videos are apparently just CPU accelerated, unfortunately, so, they will be slow.

**Comment by JFLim1** [comment]
Hi @DiogoSilva48 ,

If you are using Firefox try this settings;

Wayland:
QT_QPA_PLATFORM=wayland GDK_BACKEND=wayland MOZ_ACCELERATED=1 MOZ_ENABLE_WAYLAND=1 MOZ_WEBRENDER=1 firefox

X11:
MOZ_X11_EGL=1 MOZ_ACCELERATED=1 MOZ_WEBRENDER=1 firefox

On Chromium:
chromium --use-gl=desktop

**Comment by ophub** [comment]
@JFLim1  Where does this setting work? What does it do?

**Comment by JFLim1** [comment]
> Where does this setting work? What does it do?

On Terminal: Type:
`QT_QPA_PLATFORM=wayland GDK_BACKEND=wayland MOZ_ACCELERATED=1 MOZ_ENABLE_WAYLAND=1 MOZ_WEBRENDER=1 firefox`
It basically set Firefox to run in Wayland Mode and try to enable Webrender.  Firefox will most likely state that "webrender" is NOT available by Environment. But it helps to reducing the CPU load when streaming Youtube videos on Firefox.  If not mistaken is also use GPU HW Acceleration but NO VPU HW Acceleration that I know of currently.



> Do you know how to set Firefox to support GPU?

If not mistaken by default with Panfrost running and the above commands/flags should enable GPU support in Firefox.



> Support hardware decoding when playing video.

I don't think on Firefox support hardware video decoding on Amlogic devices yet.  But in my experience the above settings will reduce CPU load significantly when stream video on Firefox -- the GPU is assisting.

**Comment by JFLim1** [comment]
Hi @ophub,

For your info, the Jammy default Firefox or Chromium is from Snap and it uses meas-21.0.3 performance wise is not that great on GT King Pro when it comes to WebGL performance.  

Also the Ubuntu default mesa package for Jammy mesa 22.0.1-1ubuntu2 do have visual artifacts on Desktop under certain situation.  Mesa from kisak mesa fresh ppa performs better and seems to resolves visual artifacts issues.

**Comment by ophub** [comment]
https://www.linuxcapable.com/zh-CN/%E5%A6%82%E4%BD%95%E5%9C%A8-ubuntu-22-04-lts-%E4%B8%8A%E5%8D%87%E7%BA%A7-mesa-%E9%A9%B1%E5%8A%A8%E7%A8%8B%E5%BA%8F/

Thank you for sharing, welcome to test and upgrade

**Comment by JFLim1** [comment]
> https://www.linuxcapable.com/zh-CN/%E5%A6%82%E4%BD%95%E5%9C%A8-ubuntu-22-04-lts-%E4%B8%8A%E5%8D%87%E7%BA%A7-mesa-%E9%A9%B1%E5%8A%A8%E7%A8%8B%E5%BA%8F/
> 
> Thank you for sharing, welcome to test and upgrade

@ophub 

Thanks. I have used oibaf mesa drivers for quite a while.  It is a daily build from the current dev master branch if not mistaken. As it is a bleeding edge development branch at time you do encounter some issues.

The kisak mesa fresh ppa https://launchpad.net/~kisak/+archive/ubuntu/kisak-mesa is basically the latest mesa stable point release. Currently mesa 22.1.1.

**Comment by ophub** [comment]
Ok, thank you for sharing, there are deb addition instructions in this link, you are welcome to test and use
