### ISSUE TITLE
remove ifupdown,config files and armbian-config network options for it

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#347]
Networking is a bit of a mess in Armbian. For some unknown reason they decided to include both `ifupdown` and `NetworkManager` when only one is needed and having both installed can lead to config conflicts and it causes confusion. I would recommend we remove `ifupdown` and we just use `NetworkManager`.

Yet, despite including NetworkManager by default and that is the app that seems to be intended to take preference, the Network menu in armbian-config is designed to configure ifupdown. I have never got any of the armbian-config Network options to work except maybe the one that lets you edit /etc/network/interfaces. `nmtui` is a much superior TUI network config tool than what is in armbian-config and it actually works so I'd recommend getting rid of the armbian-config network menu altogether and optionally let users launch `nmtui` from armbian-config instead.

I don't think there is anything that ifupdown can do that NetworkManager can't so why ship both?

**Comment by ophub** [comment]
My firmware only modifies the official boot mode, and uses the official default configuration for other aspects.

Regarding the choice of these two management tools, you can consult the administrators in the official armbian forum to see what suggestions they have.

Sometimes good suggestions may not necessarily be adopted, and officials may have other considerations. If you think this idea is great, you might as well upgrade it yourself and share it with everyone.

**Comment by danboid** [comment]
Hi @ophub 

Yes, I have brought up this same question / proposal on the Armbian forums. No reply yet:

https://forum.armbian.com/topic/21165-why-include-ifupdown-and-networkmanager/

**Comment by danboid** [comment]
Still no reply.

I'll give a good example of this causing a problem. I have a X96 Max+ that only uses wifi. I set the wifi up using `nmtui`  but there is an almost 2 minute boot delay caused by the default Armbian `/etc/network/interfaces` config for eth0. Remove or comment this config and Armbian boots almost 2 minutes faster.

**Comment by danboid** [comment]
Yes that is the the problem but that sed command wouldn't fix it. You have to remove the config I mentioned and/or remove ifupdown completely to stop the delay.

Igor, the main Armbian dev has replied to my post and he agrees that ifupdown should be removed.

**Comment by ophub** [comment]
I saw your post and it's great news that your comments have been taken up by them and I think it will be adjusted soon.

**Comment by JFLim1** [comment]
Hi @ophub and @danboid 

I had similar experience on GT King Pro, with Aml_S922X_Bullseye, setting the Timeout=10sec did the trick in reducing boot up time without Ethernet connected, meaning using wifi alone on boot up.

The same Timeout=10sec does not work on Aml_S922X_Jammy.  Boot up time will be delayed for 1min 35secs (in this case) waiting for network interfaces.

If ifupdaown is disable will Ethernet work?  If yes, could you be specific on how to comment out ifupdown.  Thanks.

**Comment by danboid** [comment]
@JFLim1 

Yes, ethernet will still work without ifupdown being configured or installed so you can just run something like

```
mv /etc/network/interfaces /etc/network/interfaces.old
```

or

```
sudo apt remove ifupdown
```

**Comment by JFLim1** [comment]
> es, ethernet will still work without ifupdown being configured or installed so you can just run something like
> 
> ```
> mv /etc/network/interfaces /etc/network/interfaces.old
> ```

Hi @danboid,

By disabling "interfaces" it speed up Jammy the boot up time.  No more having to wait for "1min 35sec" booting with wifi alone.

Thanks.
