### ISSUE TITLE
老大 移动送的电视盒子是S905L我应该使用哪个固件？

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#348]
老大 移动送的电视盒子是S905L我应该使用哪个固件？

**Comment by 84864797** [comment]
新魔百盒HM201

**Comment by ophub** [comment]
你在usb上测试下，得测试找到适合你盒子的dtb文件才能使用网络。修改/boot/uEnv.txt
如果你在网上看到过他们使用的哪个dtb，就修改下重启试试。

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/common-files/bootfs/dtb/amlogic

这是固件里带的dtb的列表，你可以查看修改。
