### ISSUE TITLE
Is it possible to hybrid-run (sd card+emmc) armbian on S905?

### ISSUE THREAD

**Issue by drafort** [ophub/amlogic-s9xxx-armbian#349]
Firstly, Thank You for great job!

I have S905 TV box Beelink Mini MX 1/8 GB
Armbian "22.08.0_Aml_s905_bullseye_5.15.44_server_2022.05.30.img.gz" is pretty working on sd card/usb stick.

I know that fully working armbian on EMMC currently is not supported at s905.
However I tried to write system to EMMC with custom mode with parameters:
- SoC Name: s905
- DTB Name: meson-gxbb-beelink-mini-mx.dtb
- UBOOT_OVERLOAD Name: u-boot-s905.bin
- MAINLINE/ANDROID_UBOOT Name "-"

All writing processes ended successfully without errors, but after re-switching TV box power it was bricked (recovered successfully by USB Burning Tool), I think problem may be is in erasing android default bootloader/u-boot.

Question: may be possible to organize hybrid: use cd card as a boot loader and store main system on EMMC? - it provide system reliability and speed.

Thank You!

**Comment by ophub** [comment]
Currently `s905` TV Boxes can only be used in TF/SD/USB, other types of TV Boxes also support writing to EMMC.
