### ISSUE TITLE
WiFi support

### ISSUE THREAD

**Issue by pulpoff** [ophub/amlogic-s9xxx-armbian#35]
I am trying to fix the wifi for GT King.
So far I don't see anything in dmesg about it.
I found a good firmware repo here :+1: 
https://github.com/LibreELEC/amlogic-boot-fip/tree/master/beelink-s922x
https://github.com/LibreELEC/brcmfmac_sdio-firmware

Also, the chip itself seems to be AP6356S
There are many fixes for it, will see if they work, links for patches :+1: 
https://github.com/hyphop/khadas-linux-kernel/blob/master/patches/linux-5.4.5/0005-VIM3_wifi_hack.patch
https://github.com/khadas/fenix/issues/33
https://forum.khadas.com/t/wifi-ap6398s-mainline-kernel/4929/52

supposedly patched kernel fork:
https://github.com/chewitt/linux

So far I could not build the patched kernel yet ..
any help would be appreciated.

So, the patch seems to work, at least now I get this in logs :+1: 
[   11.703841] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   11.771352] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   11.796609] brcmfmac: brcmf_sdiod_sgtable_alloc: !!!! WIFI DEBUG azw,gtking:	host->max_segs: 1	host->max_seg_size: 3	host->max_blk_cou
nt: 1536	sdiodev->max_request_size: 1536	sdiodev->max_segment_count: 1	max_blocks: 3	host->max_req_size: 1536
[   11.796825] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43752-sdio for chip BCM43752/2
[   11.827549] usbcore: registered new interface driver brcmfmac
[   11.835915] brcmfmac mmc2:0001:1: Direct firmware load for brcm/brcmfmac43752-sdio.azw,gtking.bin failed with error -2
[   11.835995] brcmfmac mmc2:0001:1: Direct firmware load for brcm/brcmfmac43752-sdio.bin failed with error -2

Not sure where to find this firmware .. any help ??

wifi enabled kernel is here :+1: 
5.15.4-wifi.tar.gz

**Comment by pulpoff** [comment]
5.15.4-chewitt.tar.gz 
is the kernel compiled from https://github.com/chewitt/linux
it tries to load wifi, and has same problem as above (firmware missing) .. otherwise don't see anything special in it..

**Comment by pulpoff** [comment]
After talking to a guy Chewitt, he has found that my device has different wifi chip than other GT King models.
The Beelink guys were very quick and sent a new firmware for it
files uploaded are here :+1: 
https://github.com/chewitt/brcmfmac_sdio-firmware/commit/211cfabf400a7fc2f87714869fa1efa8db656f99

there're are also many other patches, including sound fixes in that tree.
i could not build latest tree from chewitt with armbian-kernel tools, its the linux-5.15.y tree

**Comment by pulpoff** [comment]
the specific device i am using :
![gtking](https://user-images.githubusercontent.com/40654959/143163869-16aadcb8-ceb4-4191-9ef3-ed40fd1bded6.jpg)

**Comment by pulpoff** [comment]
well .. with patched kernel it is almost working now :
![Screenshot from 2021-11-24 04-03-34](https://user-images.githubusercontent.com/40654959/143163992-325c11ea-a5c0-4f8f-b0f6-8ba5d2b30dbc.png)
![Screenshot from 2021-11-24 04-03-21](https://user-images.githubusercontent.com/40654959/143163996-ce4cfcff-5fba-44ff-af01-5d11f47ae503.png)

**Comment by pulpoff** [comment]
it is still not able to find any networks or get connected, as i guess another patch is required, best is to build Chewitt latest tre
![Screenshot from 2021-11-24 04-04-48](https://user-images.githubusercontent.com/40654959/143164184-09c04253-81f6-4440-a826-7277ee73c705.png)
e.

**Comment by pulpoff** [comment]
i have uploaded native compiled chewitt kernel to my cloud storage
file name is 5.15.4-chewitt.tar.gz
it loads the modules and supposed to support sound, but needs more configuration.

**Comment by ophub** [comment]
You try this kernel can drive.

https://github.com/ophub/kernel/tree/main/pub/stable/5.15.3

**Comment by pulpoff** [comment]
what is new there?
with latest chewitt kernel i have sound device, seems to work with his patches..
wifi device with new firmware files exists, but there still are some issues making it work..

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y
The above kernel is compiled from his source code library by the flippy boss. His source code has been upgraded for the second time based on https://github.com/chewitt/linux.

`sudo ./recompile -r flippy -k 5.15.5 -a false`
You try the flippy kernel, or use his source code to personalize the choice and try to compile

**Comment by pulpoff** [comment]
I have compiled above kernel and pushed binary as 5.15.5-new.zip
it does load wifi , and shows wlan0 interface, but still not working..
sound card also seems to exist, but missing config
in my build its 2.4 oc and 2560x1440 support added.
