### ISSUE TITLE
X96 Max Plus & X96 Air Q1000 ath10k working wifi dtb

### ISSUE THREAD

**Issue by danboid** [ophub/amlogic-s9xxx-armbian#351]
I have got 2x X96 Max Plus TVBs, both with different wifi chipsets:

* X96 Max Plus with 4 GB RAM, 32 GB eMMC, AM7256 wifi, no BT

* X96 Max Plus with 4 GB RAM, 64 GB eMMC, ath10k wifi with BT

Using the current s9xxx jammy builds, I can get the internal wifi working with the AM7256, 32 GB X96 Max+ but the onboard wifi for the 64GB model with BT doesn't work with any of the 3 X96 Max+ dtb files that are currently included in this Armbian. However, the dtb included and configured by default in Slackware for the X96 Max+ does have working wifi when I boot it on the 64 GB ath10k X96 Max+.

http://dl.slarm64.org/slackware/images/x96_max_plus/slarm64-current-aarch64-server-x96_max_plus-5.16.18-build-20220328.img.zst

http://dl.slarm64.org/slackware/images/x96_max_plus/README.TXT

[meson-sm1-x96-max-plus.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/8809513/meson-sm1-x96-max-plus.dtb.zip)

**Comment by danboid** [comment]
Extra bonus!

I can also boot this image / dtb on my X96 Air Q1000 and get working wifi. I don't get working wifi when I boot any of the X96 Air dtbs currently included with s9xxx Armbian.

**Comment by danboid** [comment]
I should also note that the slarm 5.16 kernel works with my 4K display whilst the latest Armbian 5.15 kernel doesn't (but 5.10 does)

**Comment by ophub** [comment]
If it is ath10k, it should be `compatible = "qcom,qca9377-bt";`
But the code in the dtb you sent is `compatible = "realtek,rtl8822cs-bt";`

![Snip20220601_1](https://user-images.githubusercontent.com/68696949/171309118-da1228c7-7a46-47ce-b7e2-ad9027163377.png)

**Comment by ophub** [comment]
Take a few high-definition photos of the front and back of your motherboard, the soc chip, and the wireless chip and send them here.

**Comment by danboid** [comment]
I did also test BT on my X96 Air QW1000 and X96 Max+ w/ 64 GB eMMC but BT doesn't work so that is not the correct dts config for my BT but wifi does works.

I have attached heatsinks onto my wifi and SoC chips in my X96 Air so you can't see them but I have this photo of the same board that I found on the net.

![5450811_20210429_110230](https://user-images.githubusercontent.com/1429783/171339224-a405d258-b337-4bc1-bdc6-0e7bde2184e3.jpg)

The wifi chip used in my X96 Air Q1000 is a Cdtech 4761743.

**Comment by danboid** [comment]
I have tried using that dtb with Armbian before but it didn't work. It used to work with the Manjaro linux-aml 5.12 kernel. I should try it again with the latest kernel if the Manjaro linux-aml package still  exists  to see if I can get BT working again too.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/issues/260

I don't know what the value of this chip is

**Comment by danboid** [comment]
I've not tried those two meson-gxm-a95x dtb files in that thread but I can try them with my TVBs later.

**Comment by danboid** [comment]
That's great!

Great work @ophub !

I've got another cool armbian surprise for you later actually :)

**Comment by danboid** [comment]
I have tried doing a fresh install with on my X96 Air Q1000 with one of the latest Armbian builds and using the new q2 kernel and it booted and installed fine.

**Comment by danboid** [comment]
Check this out:

https://github.com/danboid/TVBIRR

**Comment by ophub** [comment]
Great, you've taken the box to a new level

**Comment by Vinsa322** [comment]
http://dl.slarm64.org/slackware/images/x96_max_plus/slarm64-current-aarch64-server-x96_max_plus-5.16.18-build-20220328.img.zst
I cannot download this file. Please can you give another link

**Comment by danboid** [comment]
Check out the dir

http://dl.slarm64.org/slackware/images/x96_max_plus/

**Comment by Vinsa322** [comment]
slarm64-current-aarch64-server-x96_max_plus-6.2.1-build-20230226
i install this version but ethernet not working

**Comment by batserra** [comment]
Hi ,does anybody know a dtb file to work with batocera 37 beta or batocera 38? ,i tryed many dbt files and does not have lan.... has a RTL82211F ,thanks.....

**Comment by myallten** [comment]
还没有解决Fn-Link K255B-SR WiFi问题吗？

**Comment by zys123196** [comment]
<img width="708" height="160" alt="Image" src="https://github.com/user-attachments/assets/afaacac4-131c-4faf-b01c-39bcf7350611" />
<img width="2352" height="2016" alt="Image" src="https://github.com/user-attachments/assets/79be58db-f2a2-445a-92da-987c9456dddf" />
<img width="1260" height="439" alt="Image" src="https://github.com/user-attachments/assets/96990345-10b0-4001-86ce-9f51fc1d095c" />
<img width="2614" height="1440" alt="Image" src="https://github.com/user-attachments/assets/b8988879-25e4-4e53-8472-eeac91f4f523" />
Still can't use the WIFI on my box(X96 Max+ 4GB/64GB) ,I chose the dtb with code 508 because my model sticker says Q2,may I ask whether I should switch to a different dtb?I'm waiting for a reply online在线等：）

**Comment by zys123196** [comment]
already done，I uesd armbian-config and it work
