### ISSUE TITLE
大佬 你好 关于WIFI的问题

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#352]
我安装了Armbian_22.05.0_Aml_s905d_jammy_5.15.44_server_2022.05.30 这个固件  使用nmtui 命令 能看到WIFI的 热点，但是选择热点连接，输入密码后 会死机。 我盒子上的WIFI芯片为8189。   我现在有一个USB 无线网卡 芯片为8188  我想卸载盒子的WIFI驱动  插上USB 无线网卡使用  我应该怎么操作。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/2b3cef6c7b40da07d6831ad247cc42b952eac725/compile-kernel/tools/config/config-5.10.118#L2757

https://github.com/ophub/amlogic-s9xxx-armbian/blob/2b3cef6c7b40da07d6831ad247cc42b952eac725/compile-kernel/tools/config/config-5.10.118#L2768

https://github.com/ophub/amlogic-s9xxx-armbian/blob/2b3cef6c7b40da07d6831ad247cc42b952eac725/compile-kernel/tools/config/config-5.10.118#L2768

你是8188的哪个？如果内核中有你对应的8188的驱动，插上就可以使用。
