### ISSUE TITLE
s905x3的设备内核会被自动升级为lepotato，然后重启就挂了。目前个人遇到了两次

### ISSUE THREAD

**Issue by nicolite** [ophub/amlogic-s9xxx-armbian#353]
<img width="965" alt="屏幕截图 2022-06-01 163527" src="https://user-images.githubusercontent.com/17943586/171363361-c0ce6fb0-596a-496d-8fdc-fe1bd86e19e3.png">
<img width="965" alt="屏幕截图 2022-06-01 163638" src="https://user-images.githubusercontent.com/17943586/171363366-3032b74e-1563-4c5d-b77e-5c39cd2fd0e8.png">

内核变为lepotato后，重启最后停在无法初始化phy以太网

**Comment by nicolite** [comment]
<img width="965" alt="屏幕截图 2022-06-01 163527" src="https://user-images.githubusercontent.com/17943586/171363221-632f0ec7-f294-4951-af27-36d7f5f70e12.png">

**Comment by nicolite** [comment]
基本出故障的流程是这样的，第一次内核更新后重启，登录欢迎语变成lepotato，内核再次更新后就会无法启动了。

**Comment by ophub** [comment]
内核更新？你用的什么命令？

**Comment by nicolite** [comment]
> 
并非使用armbian-update，而是使用apt upgrade更新，或者自动更新了，表现为ssh上去提升内核已更新，请重启系统

**Comment by ophub** [comment]
你是以前的固件？

`cat /etc/ophub-release`

同步这个，删除下官方的images/dtb

```
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-fix -O /usr/sbin/armbian-fix
chmod +x /usr/sbin/armbian-fix
armbian-fix
```
