### ISSUE TITLE
最后一版buster镜像提供一下吧，谢谢

### ISSUE THREAD

**Issue by luoluo888** [ophub/amlogic-s9xxx-armbian#357]
还是说我可以在https://stpete-mirror.armbian.com/archive/lepotato/archive/里下载镜像，然后在“本地化打包”？

**Comment by ophub** [comment]
你说的对，就是这样做。官方现在构建里不推荐了。

https://github.com/armbian/build/blob/9a661d7af979fc21ef4885b7b7e45a012ba3b5ee/config/targets.conf#L114-L119
