### ISSUE TITLE
is possible to support archlinux?

### ISSUE THREAD

**Issue by SajjadSabzkar** [ophub/amlogic-s9xxx-armbian#358]
Hi @ophub  , i recently I just found out archlinux releases for odroid-n2 , then you can support archlinux too for all amlogic devices?

Here this link for review : [link](https://archlinuxarm.org/about/downloads)

thanks

**Comment by ophub** [comment]
sorry, i'm not familiar with

**Comment by SajjadSabzkar** [comment]
> Hi @SajjadSabzkar 
> 
> Here is a guide to install Manjaro on Amlogic TV boxes. Manjaro is based on Arch.
> 
> https://wiki.manjaro.org/index.php/Amlogic_TV_boxes

Thanks, but I love archlinux without any extra-feature.

**Comment by danboid** [comment]
Manjaro has its own installer but otherwise very little is different from Arch.

I do not know of a guide for installing normal Arch on a TV box.

**Comment by SajjadSabzkar** [comment]
> Manjaro has its own installer but otherwise very little is different from Arch.
> 
> I do not know of a guide for installing normal Arch on a TV box.

Thanks
