### ISSUE TITLE
PCM Sound support 

### ISSUE THREAD

**Issue by pulpoff** [ophub/amlogic-s9xxx-armbian#36]
Chewitt has created a few patches to support built in sound and posted config files here
https://github.com/chewitt/LibreELEC.tv/blob/amlogic-upstream/packages/audio/alsa-utils/scripts/soundconfig#L141-L145
https://github.com/chewitt/alsa-lib/blob/34dbf4272c3036a7e8b208ad8dc35a035918af66/src/conf/cards/axg-sound-card.conf
and this one enables the above :
https://github.com/chewitt/linux/commit/b2ed1ca7d92c99d56a8302e287913a53fb732582

copy the axg-sound-card.conf to /usr/share/alsa/cards/

**Comment by ophub** [comment]
`copy the axg-sound-card.conf to /usr/share/alsa/cards/`

Is this a general patch or is it specific to a specific device?

**Comment by pulpoff** [comment]
sound patches are general
specific board is my wifi

**Comment by ophub** [comment]
Thanks for sharing
