### ISSUE TITLE
Build armbian时最最后Upload Armbian image to Release出现错误

### ISSUE THREAD

**Issue by luoluo888** [ophub/amlogic-s9xxx-armbian#360]
Run ncipollo/release-action@main
  with:
    tag: Armbian_Aml_bullseye_gnome_desktop_06.0[2](https://github.com/.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:2).1800
    artifacts: /home/runner/work/_actions/ophub/amlogic-s9xxx-armbian/main/build/output/images/*
    allowUpdates: true
    body: This is Armbian image for Amlogic s9xxx tv box
  * Firmware information
  Default username: root
  Default password: 12[3](https://github.com.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:3)[4](https://github.com/.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:4)
  Install command: armbian-install
  Update command: armbian-update
  Edition: gnome_desktop
  
    generateReleaseNotes: false
    omitBody: false
    omitBodyDuringUpdate: false
    omitDraftDuringUpdate: false
    omitName: false
    omitNameDuringUpdate: false
    omitPrereleaseDuringUpdate: false
    removeArtifacts: false
    replacesArtifacts: true
  env:
    TZ: Asia/Shanghai
    COMPILE_STARTINGTIME: 0[6](https://github.com/.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:6).02.143[8](https://github.com/.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:8)
    ARMBIAN_BRANCH: current
    ARMBIAN_RELEASE: bullseye
    ARMBIAN_BOARD: odroidn2
    ARMBIAN_DESKTOP_STR: BUILD_DESKTOP=yes DESKTOP_ENVIRONMENT=gnome DESKTOP_ENVIRONMENT_CONFIG_NAME=config_basic
    ARMBIAN_DESKTOP_OPT: gnome_desktop
    ARMBIAN_CUSTOM_NAME: _gnome_desktop
    PACKAGED_OUTPUTPATH: /home/runner/work/_actions/ophub/amlogic-s[9](https://github.com/.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:9)xxx-armbian/main/build/output/images
    PACKAGED_OUTPUTDATE: 06.02.[18](https://github.com/.../amlogic-s9xxx-armbian/runs/123?check_suite_focus=true#step:7:18)00
    PACKAGED_STATUS: success
Error: Error undefined: Parameter token or opts.auth is required

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

参照第2、3步设置
