### ISSUE TITLE
open /dev/snd/seq failed: No such file or directory

### ISSUE THREAD

**Issue by JuneJaJa** [ophub/amlogic-s9xxx-armbian#363]
I'm newbie and trying to run program midi player with your linux (5.15.41) running on Ubuntu Mate but I get this error:

> open /dev/snd/seq failed: No such file or directory

Please advise how to fix this problem. 

Thank you very much

**Comment by ophub** [comment]
May require CONFIG_SND_SEQUENCER support in the kernel

https://github.com/ophub/amlogic-s9xxx-armbian/blob/3a0959081dab7f6db3c90adcbaf1e4a2fbdc3c1a/compile-kernel/tools/config/config-5.10.118#L4733

```
# 1. First modify the configuration file of the corresponding kernel
CONFIG_SND_SEQUENCER=m

# 2. Compile custom kernel
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

# 3. Execute "modprobe snd_seq" as root to enable
modprobe snd_seq
```

**Comment by olawalejuwonm** [comment]
How do I modify the configuration file of the corresponding kernel?

**Comment by olawalejuwonm** [comment]
> How do I modify the configuration file of the corresponding kernel?

@ophub
