### ISSUE TITLE
hk1box 千兆口 无法获取ip

### ISSUE THREAD

**Issue by naah69** [ophub/amlogic-s9xxx-armbian#364]

**Comment by naah69** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_server_06.02.1817/Armbian_22.05.0_Aml_s905x3_jammy_5.15.44_server_2022.06.02.img.gz

**Comment by naah69** [comment]
拆机看是JL2101得网卡

**Comment by naah69** [comment]
https://www.znds.com/tv-1217305-1-1.html

**Comment by naah69** [comment]
这种网卡现在刷机后没办法联网是吗

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/247

之前测试可以用

**Comment by naah69** [comment]
我试了 不行

**Comment by naah69** [comment]
> #247
> 
> 之前测试可以用

我看哪个文章里是x96 max+，hk1 box可以使用meson-sm1-x96-air.dtb这个么

**Comment by naah69** [comment]
![image](https://user-images.githubusercontent.com/25682169/172000339-b1c09cc6-fe71-4589-86dd-db2f56a7113f.png)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/516b7fcacb32e004d9199b1f4804a2900cea45c5

在这几个里都可以用

**Comment by naah69** [comment]
> [unifreq/linux-5.15.y@516b7fc](https://github.com/unifreq/linux-5.15.y/commit/516b7fcacb32e004d9199b1f4804a2900cea45c5)
> 
> 在这几个里都可以用

![image](https://user-images.githubusercontent.com/25682169/172003942-3ba76b9f-4bd0-4da7-b05d-09d8475e1a9c.png)
我用的是这个，但是还是不行

**Comment by ophub** [comment]
你用自己对应的，这个不是你的，用x96

**Comment by naah69** [comment]
我得盒子是hk1box，不是用这个么

**Comment by ophub** [comment]
meson-sm1-hk1box-vontar-x3.dtb
这个改了重启了不行？

**Comment by naah69** [comment]
是的 重启也不行

**Comment by ophub** [comment]
dmesg

**Comment by naah69** [comment]
我去看下

**Comment by naah69** [comment]
群怎么联系

**Comment by naah69** [comment]
不知道为啥 我挂载u盘 把log mv进去后，插到windows上，日志就是空得

**Comment by ophub** [comment]
https://github.com/unifreq/openwrt_packit
他仓库有链接。

dmesg >/root/log.txt && sync
到/root下复制

**Comment by naah69** [comment]
[dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/8839599/dmesg.log)

**Comment by naah69** [comment]
> https://github.com/unifreq/openwrt_packit 他仓库有链接。
> 
> dmesg >/root/log.txt && sync 到/root下复制
[dmesg.log](https://github.com/ophub/amlogic-s9xxx-armbian/files/8839603/dmesg.log)

这是日志，我看网上有说需要用千兆网线才行，我家里试了百兆网线和千兆网线都不行

**Comment by naah69** [comment]
有什么进展吗

**Comment by ophub** [comment]
![Snip20220612_3](https://user-images.githubusercontent.com/68696949/173219973-dbb6e958-cd94-483b-9616-d110dc374f6f.png)

看日志，你的有线网卡是新变异的JL2101芯片，这个已经支持了，而且你也识别了。

meson-sm1-x96-max-plus-ip1001m-2.dtb

看下你的/boot/dtb/amlogic目录下有没这个文件，最新的内核里有，换最新版的固件，/boot/uEnv.txt更换这个试试，如果还不行就没辙了。

**Comment by naah69** [comment]
> ![Snip20220612_3](https://user-images.githubusercontent.com/68696949/173219973-dbb6e958-cd94-483b-9616-d110dc374f6f.png)
> 
> 看日志，你的有线网卡是新变异的JL2101芯片，这个已经支持了，而且你也识别了。
 是的  网卡是显示没问题，但是无法获取ip，并且手动设置ip也不行

**Comment by ophub** [comment]
网卡识别正常，剩下的就是配置使用的问题了。
恢复默认配置：
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/network/interfaces

有你接入的路由器自动分配IP。去路由器的DHCP里查看IP，使用SSH连接

**Comment by naah69** [comment]
路由器是自动分配ip得，我自动获取和手动设置都不行，获取不到ip

**Comment by naah69** [comment]
手动设置ip后，ping不通网关
![77f510b3f23b0f1eb96ddc005fc42d1](https://user-images.githubusercontent.com/25682169/173611604-41077095-fe3d-4813-ac78-8b460585e821.jpg)

**Comment by naah69** [comment]
![image](https://user-images.githubusercontent.com/25682169/173615857-e9bdd95b-7d08-4519-83b9-cce6d74a4bc3.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/247#issuecomment-1113285648

**Comment by naah69** [comment]
5.4内核能跑满千兆

![image](https://user-images.githubusercontent.com/25682169/173621083-d3dc0cef-5b79-42cd-b240-a17b2bbf3958.png)

**Comment by ophub** [comment]
好的，那就用这个吧

**Comment by ophub** [comment]
@naah69

https://github.com/ophub/kernel/tree/main/pub/stable/5.15.47
今天新的5.15.47内核在JL2101驱动中采用了和5.4一样的设置，你更新测试下，这个应该可以正确驱动千兆了，测试后反馈下你的结果。

更新命令：`armbian-update 5.15.47`

**Comment by ophub** [comment]
好的👌感谢反馈
