### ISSUE TITLE
 [ERROR] losetup /root/amlogic-s9xxx-armbian/compile-kernel/output/chroot/chroot_armbian.img failed.

### ISSUE THREAD

**Issue by 18712886438** [ophub/amlogic-s9xxx-armbian#365]
大佬，想请教一下，我在wsl 或者docker里跑ubuntu编译内核，每次都是

```
losetup: cannot find an unused loop device
[ERROR] losetup /root/amlogic-s9xxx-armbian/compile-kernel/output/chroot/chroot_armbian.img failed.
```

请问这种一般怎么办呢

**Comment by 18712886438** [comment]
看起来是docker的问题，加了--privileged 之后可以发现loop devices了，但是因为是在Mac下，没办法去加载loop这个内核模块，看来还是应该是搞一个正经的虚拟机

**Comment by ophub** [comment]
在github上用actions挺方便

**Comment by 18712886438** [comment]
> 

我用github action编译，想加入这几个config
```
CONFIG_ASHMEM=y
CONFIG_ANDROID=y
CONFIG_ANDROID_BINDER_IPC=y
CONFIG_ANDROID_BINDERFS=y
CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
```

然后编译出来，刷到盒子里，始终没有，不知道是什么原因，我最开始确实用的action编译，折腾好几天都没成功。。。

**Comment by 18712886438** [comment]
> 在github上用actions挺方便

目前准备在盒子上编译然后试试。。。就是好慢，编一个要好久

**Comment by ophub** [comment]
s905x3盒子里的armbian编译一个内核一个多小时，github40分钟左右一个

**Comment by 18712886438** [comment]
额，再更新一下。。在wsl 20.04里面，以管理员权限运行wsl的话是可以编译成功的

**Comment by w12563789** [comment]
> 理员权限运行wsl的话是可以编译成功的



> > 
> 
> 我用github action编译，想加入这几个config
> 
> ```
> CONFIG_ASHMEM=y
> CONFIG_ANDROID=y
> CONFIG_ANDROID_BINDER_IPC=y
> CONFIG_ANDROID_BINDERFS=y
> CONFIG_ANDROID_BINDER_DEVICES="binder,hwbinder,vndbinder"
> ```
> 
> 然后编译出来，刷到盒子里，始终没有，不知道是什么原因，我最开始确实用的action编译，折腾好几天都没成功。。。

你好，请问问题解决了吗？如何解决了能具体说说如何解决的吗？

**Comment by JackPan0519** [comment]
> 大佬，想请教一下，我在wsl 或者docker里跑ubuntu编译内核，每次都是
> 
> ```
> losetup: cannot find an unused loop device
> [ERROR] losetup /root/amlogic-s9xxx-armbian/compile-kernel/output/chroot/chroot_armbian.img failed.
> ```
> 
> 请问这种一般怎么办呢

![来自WSL1仓库的issue片段](https://github.com/ophub/amlogic-s9xxx-armbian/assets/64576241/be72c003-6edc-4b0c-bda6-e482c67dc615)

如你所见，微软在WSL1上没有实现Loop device的功能，因而我在编译时会遇到同样的报错，切换到WSL2顺利解决。
