### ISSUE TITLE
HG680P Trial tes

### ISSUE THREAD

**Issue by Nabhan87** [ophub/amlogic-s9xxx-armbian#368]
![IMG_20220607_211431191](https://user-images.githubusercontent.com/96574749/172403279-592187b9-398c-42ae-a55e-17395236fda3.jpg)

When you want to create a new password it appears like that. Jammy and bullseye are the same.

![IMG_20220607_212004454](https://user-images.githubusercontent.com/96574749/172404065-67e11ed0-eb50-4c2f-91dc-26821211620b.jpg)

**Comment by ophub** [comment]
After plugging in the power supply, wait for a minute, check the ip in the router, and use the ssh terminal tool to connect
root/1234

**Comment by Nabhan87** [comment]
> After plugging in the power supply, wait for a minute, check the ip in the router, and use the ssh terminal tool to connect root/1234

oh thank you, I remote on the PC without any problems, I think the log will continue to appear if I remote from another device.

**Comment by tangzh007** [comment]
https://github.com/Nabhan87

**Comment by d4l170** [comment]
add this command  :

dmesg -D

to /etc/rc.local
