### ISSUE TITLE
Image for s905w only detects 1GB RAM on TX3 Mini

### ISSUE THREAD

**Issue by robertoenr** [ophub/amlogic-s9xxx-armbian#369]
Hi, first thank you for your project. It's a great iniciative to convert old trash TV Boxes in little servers!
I've tried the image "_Armbian_Aml_jammy_server_06.06.1812/Armbian_22.08.0_Aml_s905w_jammy_5.15.45_server_2022.06.06.img.gz_" on my TX3 Mini (genuine) and it only detects 1GB of RAM.
I suspect the issue is on the DTB. Any way to make it detects the 2GB?
Thank you!

**Comment by ophub** [comment]
replace the kernel：`armbian-update 5.10.120`

**Comment by robertoenr** [comment]
That's it! Using kernel 5.10 it detects the 2GB of RAM. Thank you!
Will work in the future with kernel 5.15?

**Comment by ophub** [comment]
When using 5.15, if the memory display is not correct, copy a u-boot yourself
```
cd /boot
cp -f u-boot-s905x-s912.bin u-boot.ext
cp -f u-boot-s905x-s912.bin u-boot.emmc
sync && reboot
```

**Comment by toywl** [comment]
> That's it! Using kernel 5.10 it detects the 2GB of RAM. Thank you! Will work in the future with kernel 5.15?

I have the same problem as you. The kernel I swipe into 5.10 is still 1GB ram. How did you brush it in.

**Comment by robertoenr** [comment]
> > That's it! Using kernel 5.10 it detects the 2GB of RAM. Thank you! Will work in the future with kernel 5.15?
> 
> I have the same problem as you. The kernel I swipe into 5.10 is still 1GB ram. How did you brush it in.

I only switched to kernel 5.10 and then it detects the 2 GB of RAM (1.8 GB cause VRAM reserve).
