### ISSUE TITLE
更新软件老是出这个  无法找到软件包 linux-image-current-meson64 的文件列表

### ISSUE THREAD

**Issue by qadzhang** [ophub/amlogic-s9xxx-armbian#37]
dpkg: 警告: 无法找到软件包 linux-image-current-meson64 的文件列表，现假定目前该软件包没有任何文件被安装在系统里。

感谢各位大大的努力，但是 这个 提示实在很烦人 
版本是前两天下的5.10.80 的s905d   用在斐讯N1上的

**Comment by ophub** [comment]
The installation command is not `opkg`, but `apt-get`

For example: 
```
apt-get update
apt-get install -y wget curl tar git
```
