### ISSUE TITLE
WiFi on GT King not work

### ISSUE THREAD

**Issue by evzubkov** [ophub/amlogic-s9xxx-armbian#370]
Hello, I installed Armbian_22.08.0_Aml_s922x_bullseye_5.15.45_server_2022.06.08 on Beeline GTKing with an S922X processor. However, my wi-fi is not working. I'm not even into such a device already. Please tell me, is there anything I can do to make the wlan work?

SN: 6B9HH2DG70455

[dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/8869700/dmesg.txt)

![1_1](https://user-images.githubusercontent.com/24616049/172832252-cf91ed92-4642-4537-9eda-3f9606ad0ef9.jpg)

![2](https://user-images.githubusercontent.com/24616049/172824857-17b0bc30-c78a-4f28-a831-0a75a52e5499.jpg)

**Comment by evzubkov** [comment]
As far as I understand, I don't have a driver for wi-fi. Judging by the system logs, there is a BCM4362A2 on my box, and bluetooth loads normally. rfkill only sees bluetooth:
root@armbian:/home/alt# rfkill list
0: hci0: Bluetooth
        Soft blocked: no
        Hard blocked: no

 Do I need another driver to make wi-fi work?

Thank you for your help.

**Comment by ophub** [comment]
There are many solutions, you can operate according to your skilled method

**Comment by evzubkov** [comment]
So, I disassembled my box. If I understood correctly, then the model of my chip is AP6275S.

![photo1655005391 (3)](https://user-images.githubusercontent.com/24616049/173214513-cca984a5-1e3b-40bf-a547-ad89739492cd.jpeg)
![photo1655005391 (2)](https://user-images.githubusercontent.com/24616049/173214516-662bea5c-b403-49c4-8633-b2777c2cbd57.jpeg)
![photo1655005391 (1)](https://user-images.githubusercontent.com/24616049/173214517-9771501f-6adc-4666-a797-ee0f672373e7.jpeg)
![photo1655005391](https://user-images.githubusercontent.com/24616049/173214518-d402bc61-f694-4da2-9d20-b52724db7408.jpeg)

**Comment by ophub** [comment]
![Snip20220612_1](https://user-images.githubusercontent.com/68696949/173219607-2a06bc4b-23a8-4388-a98d-1bd1f76c6731.png)
Take a picture of this wireless chip, what is written on it?

**Comment by evzubkov** [comment]
rtl8121f l1196h1 gl04
![photo_2022-06-12 14 18 41](https://user-images.githubusercontent.com/24616049/173222186-b8c69003-da73-4b28-bb0d-c2089d4151a3.jpeg)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/efc89902ea55508ce19e7fac6bbed16a879ff60d/drivers/net/wireless/broadcom/brcm80211/brcmfmac/sdio.c#L605-L629

The module model is AP6275S, and the chip model is bcm4375. The current driver does not support it. This wireless cannot be used.

**Comment by evzubkov** [comment]
Got it, thanks for your help

**Comment by ophub** [comment]
[brcmfmac43752.tar.gz](https://github.com/ophub/amlogic-s9xxx-armbian/files/8885515/brcmfmac43752.tar.gz)

After decompression, put these files in the /lib/firmware/brcm directory and try

**Comment by evzubkov** [comment]
@nathanredblur 

Hello! This was a long time ago, but it seems I did it in the following sequence.

0) Download the image for your device
1) Check the uEnv.txt file, it should contain uncommented lines that indicate the DTB of your platform.
2) Write the image on USB.
3) Connect the prepared media to the device and turn on the power, boot into Android
4) Open the app "Update&Backup"
5) Click on "Select" local update and chose the file on the removable media aml_autoscript.zip
6) Start "Update"
7) System will reboot twice and start running the system from external media.
