### ISSUE TITLE
hk1box 不能刷固件

### ISSUE THREAD

**Issue by pxshh** [ophub/amlogic-s9xxx-armbian#373]
你好，做好了tf卡，插进去，再怼住耳机孔里面的reset键插电，但开机以后只能进入Android recovery，请问这怎么解决啊
![image](https://user-images.githubusercontent.com/13363795/173228159-cb206567-b92d-4f16-9054-aefc24afff1c.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#114-%E8%AE%BE%E7%BD%AE%E7%9B%92%E5%AD%90%E4%BB%8E-usbtfsd-%E4%B8%AD%E5%90%AF%E5%8A%A8
