### ISSUE TITLE
TX3 led blinking

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#376]
大佬，tx3 dtb 里头有这么一段配置：

```
leds {
      compatible = "gpio-leds";
      
      sys_led {
	      led_name = "sys_led";
                            gpios = <&gpio_ao GPIOAO_11 GPIO_ACTIVE_LOW>;
	      default-state = "on";
      };
};
```

这个是来控制板上的led灯的？问下怎么用，能弄成闪烁不？

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/ca5025ca12c7d9c479b54fd5491ba341c5ca8611/arch/arm64/boot/dts/amlogic/meson-sm1-tx3-qz.dts#L97-L101

led显示屏是这段启用。
```
	openvfd {
		compatible = "open,vfd";
		dev_name = "openvfd";
                status = "okay";
        };
```

openvfd支持的功能有：alarm usb play pause colon lan wlan，但是tx3的显示只支持时间

https://github.com/ophub/amlogic-s9xxx-armbian/blob/dc9a7fb3e975093d28d0d614f84e6120f4b1e675/build-armbian/common-files/rootfs/usr/share/openvfd/conf/tx3.conf#L39

**Comment by EastWoodYang** [comment]
嗯嗯，原来是给这个数显用的，我还以为是给LED灯用的，原先这个板子上有个LED二极管好像

**Comment by ophub** [comment]
![image](https://user-images.githubusercontent.com/68696949/174008708-713c99b7-3009-4962-875e-c4025c208148.png)

tx3只支持这样的一种显示，x96max和hk1支持的样式多

**Comment by EastWoodYang** [comment]
我看官方宣传图上普遍还有个亮着的灯，你看下
![1655362716372](https://user-images.githubusercontent.com/9335046/174010974-82fcb0d2-0ffd-46b5-9de3-662efa03224b.jpg)
