### ISSUE TITLE
大哥，请求5.4.y上支持usb蓝牙rtl8761bu

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#378]
手头有个usb蓝牙rtl8761bu型号，在5.15.y，5.10.y等版本都能正常使用，唯独5.4.y上不行，请求支持下:-)

**Comment by ophub** [comment]
在5.15.y，5.10.y等版本都能正常使用，说明固件里带了这个蓝牙固件了。
5.4.y不能用，有可能是5.4的dtb里设定的蓝牙模块和其他的不同，你是使用的哪个dtb？什么盒子？

**Comment by EastWoodYang** [comment]
大哥看下这个，https://blog.csdn.net/avatar1912/article/details/120851889

5.4.y : https://github.com/unifreq/linux-5.15.y/blob/67ebe60c9eb5ce819a37f231b47707b6beb4d085/drivers/bluetooth/btrtl.c#L127-L146

5.15.y: https://github.com/unifreq/linux-5.4.y/blob/a8bbd21c743f58ff28e0ff873db08ae246c6e793/drivers/bluetooth/btrtl.c#L132-L138

**Comment by ophub** [comment]
你按我发的方法在你的固件里搜下，这个可以单独安装，最新的固件里带了。
