### ISSUE TITLE
Welcome msg after update s905x3 bullseye

### ISSUE THREAD

**Issue by uroh** [ophub/amlogic-s9xxx-armbian#379]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
Welcome message changed after bullseye update (from Amls905x3 to Lepotato). Is there a way to restore the previous welcome message? Where is Zram?

**To Reproduce**
1. Go to update from  Armbian 22.05.0-trunk to  Armbian 22.05.1 Bullseye

**Expected behavior**
Previous welcome message

**Screenshots**

![1](https://user-images.githubusercontent.com/46243951/174239501-a7f62934-e00b-4262-b3d6-08b63a0a5121.jpg)
![2](https://user-images.githubusercontent.com/46243951/174239508-f71b3bcf-828f-4a40-af23-3473b2aa1b2e.jpg)

**Armbian Version**
 - Kernel Version: [5.15.46>48]
 - Release: [bullseye]
 - Edition: [server]

**Device (please complete the following information):**
 - SOC: [S095x3]
 - Brand: [Max plus]
 - Model [4-64]

**Comment by ophub** [comment]
```
    # Custom banner name
    sed -i "s|BOARD_NAME=.*|BOARD_NAME=\"Aml s905x3\"|g" armbian-release
```
