### ISSUE TITLE
boot from sd not defined

### ISSUE THREAD

**Issue by traderpedroso** [ophub/amlogic-s9xxx-armbian#38]
how to define to boot from sd card?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-stb

The operation of armbian is the same as that of openwrt.
Different box methods, interfaces, etc. are very different, but the systems are similar.

**Comment by traderpedroso** [comment]
> https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-stb
> 
> The operation of armbian is the same as that of openwrt. Different box methods, interfaces, etc. are very different, but the systems are similar.

I done I used boot loader from other Armbian compatible with my hardware thank you
