### ISSUE TITLE
如何安装图形桌面环境，应该使用什么命令

### ISSUE THREAD

**Issue by a52391634** [ophub/amlogic-s9xxx-armbian#381]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Armbian Version**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: [e.g. S095x3]
 - Brand: [e.g. Beelink]
 - Model [e.g. mini g1]

**Additional context**

**Comment by ophub** [comment]
Installed the desktop on `jammy`, the following 2 commands can be installed.
```
sudo apt install -y ubuntu-desktop
sudo apt install -y lightdm
```
Select `gdm3` when installing lightdm

**Comment by a52391634** [comment]
你好，系统已经写入进EMMC，还可以从USB启动吗

**Comment by ophub** [comment]
https://github.com/Calmact/e900v22c

这个盒子的配置及使用方法，可以查看这个仓库的详细文档。目前采用的配置也是有他们团队的 [KryptonLee](https://github.com/KryptonLee) 等热心朋友们辛苦研发调试和分享的。

**Comment by huapox** [comment]
装docker后，可用容器来跑桌面：（基于远程RDP/noVNC桌面的），优点：不污染宿主机，可灵活切换不同桌面，直接可远程

`docker run -it --rm --shm-size 1g --net=host infrastlabs/docker-headless`

noVnc 	http://192.168.0.x:10081 	pw: headless
