### ISSUE TITLE
Make the Kernel compatible with Anbox

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#382]
Hi @ophub and all

I am trying to install [Anbox](https://docs.anbox.io/userguide/install.html) but there is need to add 2 modules to the Kernel, see => https://docs.anbox.io/userguide/install_kernel_modules.html 
The source code are on https://github.com/anbox/anbox-modules I tried building as instructed but it didn't work..

In my research I also found this https://github.com/armbian/build/commit/369b0909f6d268375eb17ecec6f0e71975001a33 

I think it might be nice to be able to easily install Anbox and therefore we need to build a Kernel that allows this..

If you have any ideas, you are welcome.
thanks again

**Comment by MX10-AC2N** [comment]
Script to be able to automate compiling procedures. Eg. if you need to add .config options to your kernel sources like android (ASHMEM, BINDER, etc.) =>https://github.com/SoulInfernoDE/compile-kernel-from-source
This could be a starting point.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/2edda1fdb23946067c4064c73dc70254b6d7821c

According to your feedback https://github.com/armbian/build/commit/369b0909f6d268375eb17ecec6f0e71975001a33, I modified the configuration, you can try the newly compiled kernel

**Comment by MX10-AC2N** [comment]
I also ran a kernel build adding config_kprobes=y but also added
https://github.com/MX10-AC2N/amlogic-s9xxx-armbian/commit/1a1e3b1ff93c06f11fefbe965add178b032967fd?diff=unified
Now I need test it.. 
Thank

**Comment by MX10-AC2N** [comment]
Testing failed.. :-(
anbox doesn't seem really updated. 
I will rather try with (Waydroid)[https://github.com/waydroid/waydroid]
Thank

**Comment by ophub** [comment]
Waydroid can be installed and used in armbian?
