### ISSUE TITLE
不理解重新分区时为什么要跳过 700 MB

### ISSUE THREAD

**Issue by whiler** [ophub/amlogic-s9xxx-armbian#39]
`armbian-install` 重新分区，跳过了 `SKIP=700` MB ，为什么要浪费 **700** MB呢？跳过 **68** MB 可以吗？

**Comment by ophub** [comment]
Skip the hard disk partition table information area. Considering the partition size of common boxes.

**Comment by UMU618** [comment]
可以参考这篇：https://www.right.com.cn/forum/thread-3869041-1-1.html
把 BOOT 分区放到 cache（reserved 和 env 之间，不要覆盖他们），把 ROOT 分区放到 env 之后，不要覆盖 env。

**Comment by whiler** [comment]
> 可以参考这篇：https://www.right.com.cn/forum/thread-3869041-1-1.html 把 BOOT 分区放到 cache（reserved 和 env 之间，不要覆盖他们），把 ROOT 分区放到 env 之后，不要覆盖 env。

学习学习

**Comment by UMU618** [comment]
保守的做法：
parted -s "${DEV_EMMC}" mkpart primary fat32 108M 620M
parted -s "${DEV_EMMC}" mkpart primary ext4  724M 100%
即：
boot 分区使用 cache 正好 512M
root 分区从 rsv 开始

激进的做法：
parted -s "${DEV_EMMC}" mkpart primary fat32 100MiB  628MiB
parted -s "${DEV_EMMC}" mkpart primary ext4 636MiB 100%
即：
boot 分区使用 reserved 结尾处到 env 开始处，528M
root 分区从 env 结尾处开始到整个剩余

**Comment by ophub** [comment]
https://github.com/ophub/luci-app-amlogic/blob/bffc2bbd9933cb4100563adc0e1dbedd48a4ed92/luci-app-amlogic/root/usr/sbin/openwrt-install-amlogic#L305-L323

这个也可以参考
