### ISSUE TITLE
System only recognizes 3.26GB RAM

### ISSUE THREAD

**Issue by ngocdungvn** [ophub/amlogic-s9xxx-armbian#393]
I use a Box with **4GB RAM**, but the system only recognizes 3.26GB. **Can you guide the box to receive enough RAM?**

![image](https://user-images.githubusercontent.com/36153803/175459577-ff98d18f-a2ab-44d1-90d9-1d48965a6720.png)

**Comment by ophub** [comment]
armbian-update 5.10.124

**Comment by ngocdungvn** [comment]
Thanks bro

**Comment by ngocdungvn** [comment]
> source /etc/ophub-release
> [[ -n "${UBOOT_OVERLOAD}" ]] && {
>     echo "copy u-boot..."
>     cp -f ${UBOOT_OVERLOAD} u-boot.ext
>     cp -f ${UBOOT_OVERLOAD} u-boot.emmc
> }
> sync && reboot
> ```

I update kernel 5.10 and it doesn't boot. Please guide me in detail step by step. Command not found

**Comment by ophub** [comment]
what box

**Comment by ngocdungvn** [comment]
> what box? What command can't be found?
Mybox is Magicsee N5 Max S905x3
![image](https://user-images.githubusercontent.com/36153803/175797678-371f9bd0-b93c-4952-b323-a4535a97adae.png)

**Comment by ophub** [comment]
source /etc/ophub-release
[[ -n "${UBOOT_OVERLOAD}" ]] && {
    echo "copy u-boot..."
    cd /boot
    cp -f ${UBOOT_OVERLOAD} u-boot.ext
    cp -f ${UBOOT_OVERLOAD} u-boot.emmc
    chmod +x u-boot.ext u-boot.emmc
}
sync && reboot
```

**Comment by ngocdungvn** [comment]
Both ways make my Magicsee N5 Max X3 device unable to boot up :(
