### ISSUE TITLE
Issue with wifi on S905w MXQPro 4k

### ISSUE THREAD

**Issue by sunilsankar** [ophub/amlogic-s9xxx-armbian#395]
Sorry could not post the pictures yesterday   sharing it now .
![WhatsApp Image 2022-06-24 at 9 14 54 AM](https://user-images.githubusercontent.com/2275957/175483538-27b4ba16-7b79-4f37-a108-38dbb7ab5e19.jpeg)

![WhatsApp Image 2022-06-24 at 9 15 03 AM](https://user-images.githubusercontent.com/2275957/175483628-f339fac2-8f95-4666-8c6d-2be9390e653d.jpeg)

**Comment by ophub** [comment]
At present, there is no driver for the SV6051p wifi chip in the mainline kernel, so wireless cannot be used.

**Comment by sunilsankar** [comment]
Thank you @ophub amaing work you are doing keep it up :)

**Comment by ophub** [comment]
```
# you try the following method
echo "options ssv6051 stacfgpath=/usr/lib/firmware/ssv6051-wifi.cfg"  >/etc/modprobe.d/ssv6051.conf
```

**Comment by sunilsankar** [comment]
how do u configure with wpa_supplicant

**Comment by sunilsankar** [comment]
How do you configure with ```wpa_supplicant```

**Comment by ophub** [comment]
https://www.google.com/search?q=Ubuntu+Wpa_supplicant+tutorial&newwindow=1&ved=0ahUKEwjAuZWgw-P4AhWOCYgKHdxUCAEQ4dUDCA4&uact=5&oq=Ubuntu+Wpa_supplicant+tutorial&sclient=gws-wiz


https://askubuntu.com/questions/1242256/how-to-configure-wpa-supplicant-in-ubuntu-server-20-04
