### ISSUE TITLE
Static IP is not set properly

### ISSUE THREAD

**Issue by sunilsankar** [ophub/amlogic-s9xxx-armbian#396]
@ophub I think the issue is with networking service and NetworkManger service running . I stopped networking and also disabled the service and the static ip issue got resolved can this be included in your code

```
systemctl disable networking
systemctl stop networking
```

**Comment by ophub** [comment]
Are you trying to set a fixed IP? Try this method:

`vi /etc/network/interfaces`

```
# Ethernet adapter 0
auto eth0
allow-hotplug eth0
#no-auto-down eth0
iface eth0 inet static
address 192.168.1.100
netmask 255.255.255.0
gateway 192.168.1.1
dns-nameservers 192.168.1.1
#dns-nameservers 1.1.1.1 1.0.0.1
```

**Comment by sunilsankar** [comment]
If you use this to provide the https://github.com/armbian/build/blob/master/packages/bsp/armbian_first_run.txt.template
it uses NetworkManager and this conflicts on subsequent restart. I then have manually run nmtui and deactivate and reactivate everytime I do a restart or else networking service start the ipaddress via dhcp. So I disabled networking service and the issue got resolved :)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/a8bed01234cce77570c855d6a996de83977016f6

I just added a custom startup task script, you can add various command operations you need in the script.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#1272-manually-set-a-static-ip-address

**Comment by sunilsankar** [comment]
Cool @ophub

**Comment by gharbarka** [comment]
@ophub I have been trying to invoke some commands at startup with limited success using services with systemctl. How can I invoke your system startup script? thanks.

**Comment by ophub** [comment]
Write the command you want to execute into the script

**Comment by gharbarka** [comment]
Which script are you referring to? At startup I am not prompted to insert any commands in any script. I am prompted to insert the usual passwords but that is it. Maybe I am missing some help file somewhere!

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/cbe7af045f07bf3865c219dabe74229a3414e895

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#128-how-to-add-startup-tasks

**Comment by gharbarka** [comment]
Thank you very much for your help. your system works in general but not on the operation I need to do. Same thing happened with the systemd service I created.

Basically i need to drive the console uart at /dev/ttyAML0 from python. When i try to drive the port, python generates an error which can be overcome by changing permissions using sudo chmod 660 /dev/ttyAML0 before running the program. Originall permissions stand at 640.
Either the system is not allowing me to do this at startup or the system overrides my command before handing over to the user.
