### ISSUE TITLE
Write kernel version 5.10, I can't boot

### ISSUE THREAD

**Issue by ngocdungvn** [ophub/amlogic-s9xxx-armbian#397]
I use Magicsee N5 Max (S905x3, RAM 4GB) , I only need to write kernel version 5.15 to boot, but when I write version 5.10, I can't boot. Please tell me how to fix it

**Comment by ophub** [comment]
5.4.y and 5.15.y kernels do not require u-boot support. For other needs, your device does not have a corresponding u-boot and cannot use these kernels.
