### ISSUE TITLE
[Question] building error

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#398]
Dear ophub,

I'm trying to building image for my s905x using lepotato board, but there is an error like this

![image](https://user-images.githubusercontent.com/33513626/175806004-9f2dcbb6-4bc1-4996-ab6b-c7a2c993188b.png)

Do you know what problem that happens? I'm using lepotato board because it has same SoC... And i think it would be good...

Thanks

**Comment by ophub** [comment]
The upstream armbian compilation error, just wait for the repair, and then compile it another day.
