### ISSUE TITLE
[S905x3] [X96 max+] Unable to ssh from other machine

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#40]
Thank you for your great work to make armbian working on S095x3.

I've tried to install latest build to my 4/32G X96 max+ (S905x3). Everything seems to run well at the first glance but there is unable to ssh from outside.

The ssh service still running but when I checked it by systemctl status ssh, there is an error:
"Could not load host key: /etc/ssh/root_host_ed25519_key"
Error loading host key: "/etc/ssh/root_host_rsa_key": invalid format.

Please give us the solution to fix if any.

**Comment by ophub** [comment]
My device is also less X96 max+ and can be used normally.

If there is a problem with ssh, ssh access will not be possible when the USB is started for the first time, and the password is reset. You can use it normally, which means it was okay before. Recall what has been changed recently?

![Snip20211130_1](https://user-images.githubusercontent.com/68696949/144065524-282a2f90-92ef-416f-bf35-13247344a6a3.png)

**Comment by dinhchinh82** [comment]
![IMG_4925](https://user-images.githubusercontent.com/22479095/144068297-0bca3aa4-f75c-4361-98d2-7ef089bdfbc7.JPG)
I just install the armbian to eMMC and this is the first boot from eMMC. 

Here is the log when I try to ssh from my Mac:

> chinh@Chinhs-MacBook-Pro ~> ssh root@192.168.4.3
Connection reset by 192.168.4.3 port 22

**Comment by dinhchinh82** [comment]
> If there is a problem with ssh, ssh access will not be possible when the USB is started for the first time, and the password is reset. You can use it normally, which means it was okay before. Recall what has been changed recently?

Yes. I was unable to connect via ssh even at the first time booting from USB.

**Comment by codesnas** [comment]
try 5.10.82

**Comment by dinhchinh82** [comment]
> try 5.10.82

I just tried 5.10.82 and it works well
