### ISSUE TITLE
[Question] Rebuild armbian using lepotato desktop prebuilt image

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#400]
Dear ophub,

Yesterday, i'm using rebuild armbian using lepotato desktop with prebuilt image by armbian official
http://sg-mirror.bret.dk/armbian/dl/lepotato/archive/Armbian_22.05.3_Lepotato_bullseye_current_5.10.123.img.xz

And, i dont know why the s9xxx image didnt uploaded successfully to releases... Can you take a look into that? This is the proof, logs from actions and screenshot of releases

[logs_10.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9015031/logs_10.zip)
https://github.com/rapdodge/amlogic-s9xxx-armbian/runs/7112489558?check_suite_focus=true

![image](https://user-images.githubusercontent.com/33513626/176560217-28d71ae6-2a2c-4dbc-ab57-b42c89aa782e.png)

**Comment by ophub** [comment]
No errors are seen from the log, and the generated firmware is also listed at the end


https://github.com/rapdodge/amlogic-s9xxx-armbian/runs/7112489558?check_suite_focus=true#step:4:237

**Comment by rapdodge** [comment]
Yes, i know it, but i dont know why tha compiled image is not uploaded to releases... just prebuilt image by armbian...

**Comment by ophub** [comment]
you are repeating the test

**Comment by rapdodge** [comment]
![image](https://user-images.githubusercontent.com/33513626/176982118-766108e8-3f35-43a0-acbb-1727a9f59e3f.png)

Aaah, i see its more than 2G...

Do you know to make it works @ophub? Hmmm

**Comment by ophub** [comment]
github is limited and cannot upload a single file larger than 2g.

Reduce the amount of pre-installed software, or upload to third parties.

**Comment by rapdodge** [comment]
> Reduce the amount of pre-installed software, or upload to third parties.

I dont know how to do it... I'm using "baked images" from armbian...

How to upload it to another service, like maybe transfer.sh?

**Comment by ophub** [comment]
https://github.com/Mikubill/transfer

https://github.com/ophub/amlogic-s9xxx-openwrt/tree/main/router-config#63-save-to-a-third-party

**Comment by ophub** [comment]
Use `build armbian` in actions. This server is small in size, and the desktop system can be installed with one-click `armbian-software`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/armbian_software.md
