### ISSUE TITLE
Armbian for Amlogic S905X4

### ISSUE THREAD

**Issue by gharbarka** [ophub/amlogic-s9xxx-armbian#402]
Are there any plans for generating Armbian for this SOC?

I recently purchased a TANIX X4 with 4GB RAM and 32GB ROM to play with.

Thanks and Regards

**Comment by ophub** [comment]
In theory, the firmware of s905x3 can be used, you can try it

**Comment by gharbarka** [comment]
You are right there is not much difference. In fact it seems that I made a rush order here since I thought that an box with an X4 must surely be better than one with an X3 at roughly the same price. I should have researched more.

I will try the firmware as you suggest but what about the device tree file? Here is a picture of the board which really looks well made.

![1656739916377](https://user-images.githubusercontent.com/105628937/176988294-0d4a9f51-d9fb-499b-8ceb-856ba994638d.jpg)

**Comment by ophub** [comment]
You can test the firmware of the s905x3/5.15 kernel, dtb choose the public version of meson-sm1-sei610.dtb

**Comment by gharbarka** [comment]
Ok. Thanks. I am currently on the move so I will test that later, over the weekend.  

I must congratulate you for your speedy and regular response to our queries. Thanks.

**Comment by gharbarka** [comment]
Sorry for the late reply but here I had big issues with the installed software on this so I did not want to touch it before these get resolved. Potential buyers should avoid buying this product at least for the time being and certainly from Aliexpress. the delivered software is shoddy. I could not even upgrade Chrome from the Play store. The original Chrome only half worked. Also the search function of Play Store was unable to even find certain standard apps. Sorry for high jacking this thread but I felt people should be informed about this.
On to the main topic...unfortunately installing your software which I know works on my X96MaxPlus does not work on this one. I tried to hook up the console UART to my PC to try and see where it is blocking but for some reason the  ascii output from this box seems garbled or encoded. Changing the terminal mode to hex display does show that data is being transmitted but is is not ASCII. Monitoring signal levels on the scope show a healthy 3.3v signal level so this is not the issue. Any ideas will be appreciated.

**Comment by gharbarka** [comment]
At least the issue of the uart interface has been resolved. It appears that the baud rate is now 921600 instead of the usual 115200.
There is potentially some useful info related to the s905x4 at https://github.com/hkallweit/linux-amlogic-sc2/tree/sc2. Unfortunately this is all greek to me.
