### ISSUE TITLE
Ophub script

### ISSUE THREAD

**Issue by uroh** [ophub/amlogic-s9xxx-armbian#403]
How can I update all ophub scripts? I have an old version without scripts. For example:

`#!/bin/bash
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-docker -O /usr/sbin/armbian-docker
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-ddbr -O /usr/sbin/armbian-ddbr
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/ armbian-fix -O /usr/sbin/ armbian-fix
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-install -O /usr/sbin/armbian-install
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-kernel -O /usr/sbin/armbian-kernel
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-led -O /usr/sbin/armbian-led
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-swap -O /usr/sbin/armbian-swap
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-tf -O /usr/sbin/armbian-tf
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-update -O /usr/sbin/armbian-update

#add armbian-software
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-software -O /usr/sbin/armbian-software
chmod +x /usr/sbin/armbian-software
mkdir /usr/share/ophub
mkdir /usr/share/ophub/armbian-software
/usr/sbin/armbian-software -u
#upgrade armbian -fix
/usr/sbin/armbian-fix`

**Comment by ophub** [comment]
```
sbin_script="https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/common-files/rootfs/usr/sbin"
sbin_path="/usr/sbin"
svn export ${sbin_script} ${sbin_path} --force
```

**Comment by uroh** [comment]
Perfect! ThankU
![immagine](https://user-images.githubusercontent.com/46243951/176998959-29c77456-8c8c-4b23-92b9-f3e96ca49d12.png)

**Comment by dinhchinh82** [comment]
> ```
> sbin_script="https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/common-files/rootfs/usr/sbin"
> sbin_path="/usr/sbin"
> svn export ${sbin_script} ${sbin_path} --force
> chmod +x ${sbin_path}/armbian-*
> ```

I'm sorry but how to get the original armbian-ophub script?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/394c466cb250a9c185f1b4fd30faff4922dbb383

https://github.com/ophub/amlogic-s9xxx-armbian/commit/91c91a5692c2fd30a7350f487f56d16c0d4de27b

Inspired by you, I developed this script to update the service.

**Comment by uroh** [comment]
U are cool bro!
