### ISSUE TITLE
How to change the default splash screen image of original Android firmware?

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#404]
**Describe the request**
At current, after install the S9xxx firmware to eMMC then boot from eMMC, everything works well but the splash screen (the photo display at the first time of the boot) is still always showing from orignal Android firmware.

Is there a way to change that splash screen image?

**To Reproduce**
1. Install Armbian to eMMC
2. Boot from eMMC
3. You will see the orignal splash screen image from Android firmware

**Expected behavior**
A solution to customize(replace) the original boot image to new one.

**Armbian Version**
 - Kernel Version: any version 5.4.x, 5.10.x, 5.15.x
 - Release: bullseye
 - Edition: [server]

**Device (please complete the following information):**
 - SOC: [S095x3]
 - Model [X96 max plus ]

**Additional context**
N/A

**Comment by ophub** [comment]
The boot part of the Android system is reserved
