### ISSUE TITLE
It crashes after running for a period of time, Hk1box

### ISSUE THREAD

**Issue by jinkun2014** [ophub/amlogic-s9xxx-armbian#405]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
It crashes after running for a period of time, the syslog log is as follows

```
Jul  3 14:31:35 armbian kernel: [ 4437.532537] Unable to handle kernel NULL pointer dereference at virtual address 0000000000000010
Jul  3 14:31:35 armbian kernel: [ 4437.538761] Mem abort info:
Jul  3 14:31:35 armbian kernel: [ 4437.541761]   ESR = 0x96000005
Jul  3 14:31:35 armbian kernel: [ 4437.544711]   EC = 0x25: DABT (current EL), IL = 32 bits
Jul  3 14:31:35 armbian kernel: [ 4437.549807]   SET = 0, FnV = 0
Jul  3 14:31:35 armbian kernel: [ 4437.552825]   EA = 0, S1PTW = 0
Jul  3 14:31:35 armbian kernel: [ 4437.555930] Data abort info:
Jul  3 14:31:35 armbian kernel: [ 4437.558764]   ISV = 0, ISS = 0x00000005
Jul  3 14:31:35 armbian kernel: [ 4437.562586]   CM = 0, WnR = 0
Jul  3 14:31:35 armbian kernel: [ 4437.565488] user pgtable: 4k pages, 39-bit VAs, pgdp=0000000000f8b000
Jul  3 14:31:35 armbian kernel: [ 4437.571894] [0000000000000010] pgd=0000000000000000, p4d=0000000000000000, pud=0000000000000000
```

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/11567175/177028985-441831a5-00d8-49b9-a061-f8d0dd2c15c6.png)

**Armbian Version**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]
 - Edition: [e.g. server]
Armbian_22.08.0_Aml_s905x3_jammy_5.10.127_server_2022.07.01.img.gz

**Device (please complete the following information):**
 - SOC: [e.g. S095x3]
 - Brand: [e.g. Beelink]
 - Model [e.g. mini g1]
Hk1box

**Additional context**

**Comment by ophub** [comment]
https://github.com/ayufan-rock64/linux-build/issues/278

https://forum.armbian.com/topic/10881-infrequent-rockpro64-freeze-kernel-null-pointer/

**Comment by jinkun2014** [comment]
There is no external hard disk, my power adapter is 3A, and I don't have any software running, this error occurs after running for a while

**Comment by uroh** [comment]
high temperature?

**Comment by ophub** [comment]
If you are sure that there is no problem with the power supply, you can try changing the kernel
`armbian-update 5.18.9`
