### ISSUE TITLE
X96mini only has 1G memory

### ISSUE THREAD

**Issue by toywl** [ophub/amlogic-s9xxx-armbian#406]
The x96mini I am using is 2+16g, After installation, it shows that there is only 1G memory. it is only 921m
![QQ截图20220704200946](https://user-images.githubusercontent.com/94053521/177151952-4f9088d2-4f2d-40da-9dc0-6106426b46ac.png)

**Comment by ophub** [comment]
The 5.4/5.15 kernel does not enable u-boot, so some devices will not be fully recognized. You can replace the 5.10/5.18 kernel, or manually copy u-boot yourself

**Comment by toywl** [comment]
![QQ截图20220705102256](https://user-images.githubusercontent.com/94053521/177237034-cc0a4173-1006-4695-9d97-641a28aca48f.png)
It doesn't seem feasible to manually copy u-boot. After I swiped into the 5.10 kernel, I found that there was only 924m memory.

**Comment by ophub** [comment]
```
cat /etc/ophub-release

ls /boot -l
```

**Comment by toywl** [comment]
![QQ截图20220705124621](https://user-images.githubusercontent.com/94053521/177251379-73853edb-cf5d-4a91-b5b6-5e372c39c240.png)

**Comment by ophub** [comment]
All settings are correct. You can try other kernels to see if they can be recognized.

```
armbian-update 5.18.9

armbian-update 5.4.203
```

**Comment by rapdodge** [comment]
x96 mini (2/16) is no issues
![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)

**Comment by toywl** [comment]
> x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)

5.4 is the kernel too old？

**Comment by rapdodge** [comment]
> > x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)
> 
> 5.4 is the kernel too old？

Well, if you take a look on https://kernel.org/category/releases.html, 5.4 is the second longest period of EOL after 5.10

If you're just using for server usages, 5.4 i think still best choice 👍

**Comment by toywl** [comment]
> 

But I don't know how to compile the kernel. There is no version of the relevant kernel in the project.
![QQ截图20220709210606](https://user-images.githubusercontent.com/94053521/178107133-0ef3b02b-ccb8-4bdf-8cda-f2f5c06944b4.png)

**Comment by toywl** [comment]
> > > x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)
> > 
> > 
> > 5.4 is the kernel too old？
> 
> Well, if you take a look on https://kernel.org/category/releases.html, 5.4 is the second longest period of EOL after 5.10
> 
> If you're just using for server usages, 5.4 i think still best choice 👍
> 
> ![IMG_20220709_193324.jpg](https://user-images.githubusercontent.com/33513626/178105970-8d2fef41-6aaf-4a29-a967-c096b1316015.jpg)

But I don't know how to compile the kernel. There is no version of the relevant kernel in the project.
![QQ截图20220709210606](https://user-images.githubusercontent.com/94053521/178107172-6ff6bdce-8e0a-4e27-892d-295db511c81e.png)

**Comment by toywl** [comment]
> x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)

Can you share your system image file.

**Comment by toywl** [comment]
> x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)

Can you share your system image file?

**Comment by rapdodge** [comment]
> > x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)
> 
> Can you share your system image file?

I'm using my own build by forking ophub's repository
https://github.com/rapdodge/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_07.04.2302

I'm using prebuilt images from armbian :)

**Comment by toywl** [comment]
> > > x96 mini (2/16) is no issues ![image](https://user-images.githubusercontent.com/33513626/178098841-331fa8be-1eff-4c23-b2e6-3755a586c03b.png)
> > 
> > 
> > Can you share your system image file?
> 
> I'm using my own build by forking ophub's repository https://github.com/rapdodge/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_07.04.2302
> 
> I'm using prebuilt images from armbian :)

thank you.

**Comment by gcsuri** [comment]
dtc -I dtb -O dts meson-gxl-s905w-p281.dtb |sed -e 's/0x00 0x00 0x00 0x4/0x00 0x00 0x00 0x8/g' | dtc -I dts -O dtb >meson-gxl-s905w2G-p281.dtb
it works for me...

**Comment by toywl** [comment]
> dtc -I dtb -O dts meson-gxl-s905w-p281.dtb |sed -e 's/0x00 0x00 0x00 0x4/0x00 0x00 0x00 0x8/g' | dtc -I dts -O dtb >meson-gxl-s905w2G-p281.dtb
> it works for me...

Thank you. I'll try it later
