### ISSUE TITLE
Hope “armbian-software” can integrate Chinese “Portainer-ce”, thank you

### ISSUE THREAD

**Issue by lisen9065** [ophub/amlogic-s9xxx-armbian#408]
希望 armbian-software 能整合中文Portainer-ce，谢谢

中文Portainer-ce：
https://hub.docker.com/r/6053537/portainer-ce

amlogic-s9xxx-armbian 真是个伟大的工程！赞

**Comment by ophub** [comment]
好的，我在这个docker管理容器安装时添加一个中文选项

**Comment by lisen9065** [comment]
^_^非常感谢，执行armbian-software -u后，我已成功安装中文版portainer。
