### ISSUE TITLE
Software Suggestion：Node-RED ,  MQTT .

### ISSUE THREAD

**Issue by lisen9065** [ophub/amlogic-s9xxx-armbian#409]
期待整合常用软件（docker）：Node-RED ,  MQTT 等等homeassistant常用软件，谢谢。
为ophub/amlogic-s9xxx-armbian点赞~

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/0067a70bf095a94bdf30b40593e68bd627636f83

已经添加

**Comment by lisen9065** [comment]
效率真高~
Thank you very much !
