### ISSUE TITLE
The mac address (eth0) of X96 max + is reset each time rebooting

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#41]
I have X96 max + (4+32G+S905X3) running 5.10.82. 
After installing the Armbian to eMMC, the Mac Address is not correct. 

I've updated manually the mac address in the /etc/network/interfaces file as below but sometimes the mac address is still reset:

> source /etc/network/interfaces.d/*
allow-hotplug eth0
no-auto-down eth0
iface eth0 inet dhcp
hwaddress ether 90:0E:B3:24:31:3B
'# Local loopback
auto lo
iface lo inet loopback

There is an strange message at the first boot screen as below:
![IMG_4930](https://user-images.githubusercontent.com/22479095/144181756-399fa59a-345e-44ab-b16c-d63c8e3a0df1.jpg)

So is there a solution to fix the eth0 address?

Thank you.

**Comment by ophub** [comment]
Reprint flippy's tutorial:
```
armbian网卡设置静态地址的方法:
1. 创建/etc/network/interfaces.d/eth0 文件，内容如下：
auto eth0
# 设置静态IP地址
iface eth0 inet static
        # 自动开启网卡混杂模式
        up ip link set $IFACE promisc on 
        # 给eth0设置固定的mac地址，自己编一个
        hwaddress ether 01:02:03:04:05:06
        # armbian的ip地址
        address 192.168.3.10
        broadcast 192.168.3.255
        netmask 255.255.255.0
        #  主路由的ip地址
        gateway 192.168.3.1
        dns-nameservers 192.168.3.1
        dns-nameservers 114.114.114.114

2. 文件建好后，重启N1即可, 重启命令：
systemctl reboot
```

**Comment by ngocdungvn** [comment]
@dinhchinh82  bác ơi, bác đã cài được chưa, hướng dẫn cho em cài với

**Comment by ngocdungvn** [comment]
> Reprint flippy's tutorial:
> 
> ```
> armbian网卡设置静态地址的方法:
> 1. 创建/etc/network/interfaces.d/eth0 文件，内容如下：
> auto eth0
> # 设置静态IP地址
> iface eth0 inet static
>         # 自动开启网卡混杂模式
>         up ip link set $IFACE promisc on 
>         # 给eth0设置固定的mac地址，自己编一个
>         hwaddress ether 01:02:03:04:05:06
>         # armbian的ip地址
>         address 192.168.3.10
>         broadcast 192.168.3.255
>         netmask 255.255.255.0
>         #  主路由的ip地址
>         gateway 192.168.3.1
>         dns-nameservers 192.168.3.1
>         dns-nameservers 114.114.114.114
> 
> 2. 文件建好后，重启N1即可, 重启命令：
> systemctl reboot
> ```

Please guide video. thank bro

**Comment by dinhchinh82** [comment]
@ophub I've tried to setup according to your guide but still not success.

root@armbian:~# cat /etc/network/interfaces.d/eth0 

> auto eth0
# 设置静态IP地址
iface eth0 inet static
# 自动开启网卡混杂模式
up ip link set $IFACE promisc on 
# 给eth0设置固定的mac地址，自己编一个
hwaddress ether 90:0E:B3:24:31:3B

Please note that I don't want to set the fixed local statis IP address. I just want to fix the Mac address.

Thank you.

**Comment by ophub** [comment]
workaround for classic specification (/etc/network/interfaces)

```
auto eth0
iface eth0 inet dhcp
        hwaddress ether 12:34:56:78:9A:BC
```

or set dhcp-client-identifier 12:34:56:78:9A:BC in dhclient.conf (https://linux.die.net/man/5/dhclient.conf)

**Comment by dinhchinh82** [comment]
> workaround for classic specification (/etc/network/interfaces)
> 
> ```
> auto eth0
> iface eth0 inet dhcp
>         hwaddress ether 12:34:56:78:9A:BC
> ```
> 
> or set dhcp-client-identifier 12:34:56:78:9A:BC in dhclient.conf (https://linux.die.net/man/5/dhclient.conf)

We tried this solution and it seems to work well. Thank you.

**Comment by dinhchinh82** [comment]
> @dinhchinh82 bác ơi, bác đã cài được chưa, hướng dẫn cho em cài với

box của bạn là gì? hình như firm này chỉ nhận ethernet với bản 4G ram. bản 2G hình như không nhận card mạng.
