### ISSUE TITLE
Step-by-step for beelink gt king (not the pro version)

### ISSUE THREAD

**Issue by mkanada** [ophub/amlogic-s9xxx-armbian#410]
I've tried start my beelink gt king with armbian, but without success. Is there any step-by-step anywhere? I know how to install Linux in PC x86 computers. I'm completely lost with any u-boot and/or dtb configuration. And it could be really nice if there was something like RaspberryPi OS: just write to usb and boot the device.

Thanks

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md

**Comment by mkanada** [comment]
Yes. First I tried without any copy/rename that I understand I have to do. Then I tried with all combinations of copy/rename. But to me, a completely idiot in arm boot architecture, it is really likely that I have made many mistakes.

**Comment by ophub** [comment]
Use 5.15 kernel firmware, no need to copy u-boot, just modify the name of dtb in `/boot/uEnv.txt`

**Comment by mkanada** [comment]
It does not work. 

I used 'Armbian_22.08.0_Aml_s922x_jammy_5.15.52_server_2022.07.06.img', edited uEnv.txt to:

`LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-g12b-gtking.dtb
APPEND=root=UUID=75975409-2041-463c-b9ae-57c3e01b858d rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1`

No other modifications/copy/rename.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#124-set-the-box-to-boot-from-usbtfsd

**Comment by mkanada** [comment]
But I boot from SD/USB with CoreElec. Is it really necessary to do this change?
