### ISSUE TITLE
[BUG] N1:   dpkg configure cannot perform operation: umount --no-follow on ubuntu jammy 

### ISSUE THREAD

**Issue by jayagami** [ophub/amlogic-s9xxx-armbian#412]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

can not install packages with snap

```
sudo apt install firefox
or
sudo snap install firefox
```

```
error: cannot perform the following tasks:
- Run config hook of "firefox" snap if ..............
dpkg configure cannot perform operation: umount --no-follow ...................

```

` --no-follow` is not a option of umount, could be problem of snap of dpkg on jammy

**To Reproduce**
1. fresh install system
2. install firefox with command:  sudo apt install firefox

**Expected behavior**

**Screenshots**

**Armbian Version**
 - Kernel Version: 5.15 and 5.10
 - Release: jammy
 - Edition:  server

**Device (please complete the following information):**
 - SOC:  S905d
 - Brand: N1

**Comment by ophub** [comment]
Snap has little support for arm64, use armbian-software to install firefox

**Comment by jayagami** [comment]
> Snap has little support for arm64, use armbian-software to install firefox

Thanks for your advice!
