### ISSUE TITLE
n1刷最新 Armbian_22.08.0_Aml_s905d_jammy_5.15.54_server_2022.07.13 有很多文件权限错误

### ISSUE THREAD

**Issue by nnn149** [ophub/amlogic-s9xxx-armbian#415]
刷这个 Armbian_22.08.0_Aml_s905d_jammy_5.15.54_server_2022.07.13后，如果用ambian-tf 扩展tf卡控件，命令滚动途中就会有很多权限 permission的错误，虽然最后能扩容成功。在u盘或用armbian-install安装到emmc，然后使用armbian-software安装docker之类的，也会有文件权限错误无法安装，全程使用的都是root用户。
重新用 Armbian_22.08.0_Aml_s905d_jammy_5.15.53_server_2022.07.08 这个版本一切正常。

**Comment by ophub** [comment]
你使用root用户安装的还是创建的用户？
