### ISSUE TITLE
x96max刷armbian过一段时间会死机

### ISSUE THREAD

**Issue by lhw56198** [ophub/amlogic-s9xxx-armbian#416]
刷完最新的armbian各个版本，每过一段时间都会死机

**Comment by ophub** [comment]
死机原因是什么

**Comment by lhw56198** [comment]
> 一段时间是指几分钟？死机原因是什么？

大约5-6个小时。原因的话不是很清楚。

**Comment by ophub** [comment]
![Snip20220716_1](https://user-images.githubusercontent.com/68696949/179346116-5c8eec94-7ac2-4ed5-af77-3904e7f3e53e.png)
![Snip20220716_2](https://user-images.githubusercontent.com/68696949/179346118-86a0c8ea-4d55-4a7b-9365-79b90317f162.png)
![Snip20220716_3](https://user-images.githubusercontent.com/68696949/179346119-dec68616-c841-4fbb-868c-22cb184fa446.png)

我的gtk、tx3、n1都是常年开机状态，在每次更新内核测试或者脚本升级测试的时候我人为重启，我没遇到定时死机的现象。如果你不知道原因那就再观察吧。

**Comment by lhw56198** [comment]
我更换下了内核，现在连续运行四天没什么问题啦，感谢大佬

**Comment by sonicno1** [comment]
v25.11.0 for Aml.S905x3 running Armbian Linux 6.1.152-ophub
docker stop 容器   ,  必死机重启

**Comment by forrestsocool** [comment]
> v25.11.0 for Aml.S905x3 running Armbian Linux 6.1.152-ophub docker stop 容器 , 必死机重启

我也是 S905x3 运行的 6.1.152-ophub，每过几个小时在整点会死机。内核日志死机前没有报错，之后会自动重启，但是就ssh失联了
