### ISSUE TITLE
armbian-software  安装软件报错，刷了两遍都是报错

### ISSUE THREAD

**Issue by hs413447685** [ophub/amlogic-s9xxx-armbian#417]
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins

有哪位老哥碰到同样的问题吗

**Comment by ophub** [comment]
armbian-fix
修复一下权限

你安装什么报错，什么用户，截图

**Comment by hs413447685** [comment]
root@armbian:~# armbian-fix
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
13. Fix custom banner name: Aml s905l3a
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
armbian-fix: Loading finished.

![20220717103146](https://user-images.githubusercontent.com/35088021/179381451-0a22a3d5-f78a-4de8-9bad-4d94d1d5842b.png)


感谢您的回复，抱歉不是很会用GitHub，在尝试安装 OMV 的时候报错，其他软件也是同样的错误，通过搜索知道是权限问题，使用的是root 用户，而且没有更改过 相关文件的权限，通过winscp查看，权限都是 0644

**Comment by ophub** [comment]
`cat /etc/ophub-release`

执行这个命令，结果截图发一下

**Comment by ophub** [comment]
![Snip20220717_1](https://user-images.githubusercontent.com/68696949/179385226-670cd8aa-e554-488a-b1e8-3fedeb76ca5f.png)
![Snip20220717_4](https://user-images.githubusercontent.com/68696949/179385234-f16794b8-6419-489a-a055-1213e4a2a803.png)
![Snip20220717_3](https://user-images.githubusercontent.com/68696949/179385239-90f4cc33-58ae-4cac-9f51-a928e5cc7fd9.png)
![Snip20220717_6](https://user-images.githubusercontent.com/68696949/179385245-fc8b436d-af41-4cdd-86dd-7163d743a87e.png)
![Snip20220717_8](https://user-images.githubusercontent.com/68696949/179385248-a268375f-3dce-4c28-be1b-ed61cbb2579a.png)

**Comment by lisen9065** [comment]
安装OMV没有问题，我已安装过两三次。
但是我不会设置网络（查了下好像是说跟armbian网络冲突），导致docker不能连同外网。

**Comment by lisen9065** [comment]
建议楼主重刷armbian试试。

**Comment by ophub** [comment]
docker的网络这么设置：
https://hub.docker.com/r/ophub/openwrt-aarch64

可以拉取其他仓库的openwrt，网络设置方法相同

**Comment by lisen9065** [comment]
O大指的是这个吗？

`# 03. Docker install OpenWrt and communicate with each other
#allow-hotplug eth0
#no-auto-down eth0
#auto eth0
#iface eth0 inet manual
#
#auto macvlan
#iface macvlan inet dhcp
#        hwaddress ether 12:34:56:78:9a:bc
#        pre-up ip link add macvlan link eth0 type macvlan mode bridge
#        post-down ip link del macvlan link eth0 type macvlan mode bridge
#
#auto lo
#iface lo inet loopback`

**Comment by lisen9065** [comment]
我的使用情况是：
刷armbian → 安装docker和portainer → docker下安装homeassistant、openwrt。安装完成后一切正常。

此时再通过armbian-software安装305 OMV后，homeassistant就不能安装新的集成了，已添加的非本地设备也不能工作。

**Comment by ophub** [comment]
https://community.home-assistant.io/t/can-i-install-openmediavault-and-home-assistant-simultaneously-on-my-raspberry-pi/367314/12

根据上面这个帖子中的讨论，需要在armbian上直接安装homeassistant，不要使用docker和vm等

**Comment by snbdot** [comment]
make,主机一直不能和内置op通信

**Comment by ophub** [comment]
docker的op按我发的设置，我测过op可以ping宿主机

**Comment by ophub** [comment]
bullseye可以

**Comment by hs413447685** [comment]
> ![Snip20220717_1](https://user-images.githubusercontent.com/68696949/179385226-670cd8aa-e554-488a-b1e8-3fedeb76ca5f.png) ![Snip20220717_4](https://user-images.githubusercontent.com/68696949/179385234-f16794b8-6419-489a-a055-1213e4a2a803.png) ![Snip20220717_3](https://user-images.githubusercontent.com/68696949/179385239-90f4cc33-58ae-4cac-9f51-a928e5cc7fd9.png) ![Snip20220717_6](https://user-images.githubusercontent.com/68696949/179385245-fc8b436d-af41-4cdd-86dd-7163d743a87e.png)
> 
> ![Snip20220717_8](https://user-images.githubusercontent.com/68696949/179385248-a268375f-3dce-4c28-be1b-ed61cbb2579a.png) ![Snip20220717_11](https://user-images.githubusercontent.com/68696949/179385608-9bc9b173-38d1-47c9-8aaa-a8c3d4cd2759.png) ![Snip20220717_9](https://user-images.githubusercontent.com/68696949/179385535-1bc0ceed-39c7-4576-9a5e-ba3421a96b6a.png)
![20220720165449](https://user-images.githubusercontent.com/35088021/179940997-7de89009-172b-434e-8758-600bd27fb11e.png)

抱歉，前几天出差，Bullseyes 两个 5.10  5.15都试过，我的是移动送的 CM311-la yst，S905l3a，用 jammy 好像无法U盘启动，等我再试试，还有个N1，看看怎么回事

**Comment by ophub** [comment]
先使用 `armbian-sync` 同步更新一下全部脚本，再试 `armbian-software` 软件安装

**Comment by snbdot** [comment]
> 

请问如何运行armbian-sync 和 armbian-software ，我装的bullseye没有啊，环境是zsh

**Comment by ophub** [comment]
这个我是在bash环境下测试的

**Comment by snbdot** [comment]
> 这个我是在 bash 环境下测试的

请问 这两个文件的路径在哪里呀   安装的6月份5.10.21内核版的

**Comment by ophub** [comment]
/usr/share/openwrt/armbian-software

**Comment by snbdot** [comment]
> /usr/share/ophub/armbian-software

感谢  看来是我装的版本没这个目录
