### ISSUE TITLE
Not connected ethernet

### ISSUE THREAD

**Issue by ngocdungvn** [ophub/amlogic-s9xxx-armbian#42]
i using X96max+ (S905x3, RAM 4GB) install Armbian_21.11.0_Aml_s905x3_buster_5.10.82_2021.11.26.2049.img
After booting up, my box can't connect to the network even though Ethernet is plugged in. Please guide me to connect. thanks bro

**Comment by ophub** [comment]
Go to the dhcp list of your router, check the ip of the device named armbian, use ssh to connect to this ip.

**Comment by ngocdungvn** [comment]
> Go to the dhcp list of your router, check the ip of the device named armbian, use ssh to connect to this ip.

Tested on router. My device is not receiving the IP. Can you help me change dtb or env? i'm in trouble

**Comment by ophub** [comment]
What is the version of the motherboard?
What version of the network card chip?

The V5.1 version of X96 Max+ is known as a gigabit network card, but it cannot be driven. After disassembly and inspection, the RTL8211F network card chip was replaced with IP1001M.

Other versions do not need to be modified, you can directly use the s905x3 Armbian firmware.

**Comment by ophub** [comment]
network card chip?
version of the motherboard?

**Comment by ngocdungvn** [comment]
I only know it is the Q1 version. I haven't opened the hardware yet. See if you can fix it here
https://forum.armbian.com/topic/15376-methods-to-fix-x96-max-pluss905x3-gigabit-ethernet-problem/

**Comment by ophub** [comment]
The dtb provided by flippy is used now. There are two different versions of the kernel, 5.10 and 5.4, if none of them can be used, there is no way.

**Comment by dinhchinh82** [comment]
@ophub btw, are you flippy? I'd like to thank you all so much for making more stable armbian to X905X3.

**Comment by ophub** [comment]
I am not `flippy`, I am his fan. I have used the Armbian and OpenWrt provided by him for a year. I have developed a personality for the packaging of these two firmwares through my understanding of his firmware and following his usual standards. Conveniently set up interface for convenient packaging.

This is his website: https://github.com/unifreq
