### ISSUE TITLE
Ethernet/wifi not working on GT1 w/ Armbian

### ISSUE THREAD

**Issue by mholl1983** [ophub/amlogic-s9xxx-armbian#420]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
20.10 build boots fine on my Beelink GT1, but WiFi/ethernet do not work.

**To Reproduce**
1. Turn on GT1 with reset pin pushed in to boot from micro SD card w/ Armbian build. (GT1 hardwired into router.)
2. Log in and boot to desktop.
3. Click all network options on the right. Result is no connection.

**Expected behavior**
Expect at least the ethernet to work so I can continue with setup.

**Screenshots**

**Armbian Version**
 - Kernel Version: [e.g. 5.9]
 - Release: [e.g. Bullseye]
 - Edition: [e.g. Desktop]

**Device (please complete the following information):**
 - SOC: [e.g. S912]
 - Brand: [e.g. Beelink]
 - Model [e.g. GT1 Standard]

**Additional context**
I choose the GT1 specific deb file when preparing the micro SD card.

**Comment by mholl1983** [comment]
Is there a specific Armbian build/kernel you recommend that I try with the Beelink GT1?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_07.16.0515/Armbian_22.08.0_Aml_s912-m8s_jammy_5.10.131_server_2022.07.16.img.gz

Using this firmware, modify the name of dtb in /boot/uEnv.txt to meson-gxm-beelink-gt1.dtb
Restart after saving changes.

**Comment by mholl1983** [comment]
Appreciate it, thanks! Will try tomorrow and report back.

**Comment by mholl1983** [comment]
Followed these steps and I get this error:

`Could not initialize PHY ethernet@c9410000`

**Comment by mholl1983** [comment]
Yes, I updated the dtb entry in /boot/uEnv.txt, but I'll double check the naming tomorrow.

The device has an Amlogic S912. Not sure about the network card chip, but I'll try to take a look directly on the motherboard tomorrow, too, and report back.

**Comment by mholl1983** [comment]
Do I need to do anything with u-boot? I see a lot of different files with that name.

**Comment by ophub** [comment]
The 5.15 kernel does not need u-boot, the 5.10 kernel needs it, and the default s912 firmware is correct.

**Comment by mholl1983** [comment]
Thank you. Really hoping I can get this to work. Did someone test the GT1 recently?

**Comment by ophub** [comment]
you are the first user

**Comment by mholl1983** [comment]
I can't specifically see on the motherboard, but from what I found on Google, the board seems to match what's in the above DTS.

SOC: Amlogic S912
NIC: Realtek RTL8211F

There's apparently a bug with the NIC and I found this workaround (posted in https://discourse.coreelec.org/t/no-lan-on-s912-beelink-gt1/3068/5): 

```
In the beelink forum, the following workaround helped and the lan is working for several weeks now:

Shut down the device, pull the power, hdmi and lan cable off. Plug the lan in, then the power cable…wait a minute to boot the system, before plugin the hdmi cable again. Now it should work. I use a static IP in my router using dhcp. Dynamic works also. Static in the device did not work.

It seems, that there is some interference between lan and hdmi connector. Hardware issue, has nothing to do with coreelec.

Hope this will help u too.
```

**Comment by ophub** [comment]
In the link you sent, they use this effectively, you try
meson-gxm-q200.dtb
meson-gxm-q201.dtb

**Comment by mholl1983** [comment]
Same results for both, unfortunately.

**Comment by ophub** [comment]
If both private and general dtb can't be used, maybe yours is a variant, it is not supported
