### ISSUE TITLE
CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线

### ISSUE THREAD

**Issue by Shiyang-Wang** [ophub/amlogic-s9xxx-armbian#421]
**Describe the bug**
CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线

**Comment by ophub** [comment]
你换一根网线试试

**Comment by Shiyang-Wang** [comment]
没



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: einsqing ***@***.***&gt;
发送时间: 2022年7月18日 22:50
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





  
Describe the bug
 CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线
  
你解决了么？

**Comment by Doboo** [comment]
我这边因为有不少台设备，也经常遇到过这样的问题。特别是系统刚启动的时候，获取不到IP地址，拔插一下网线就可以了

**Comment by ophub** [comment]
这个现象在别的设备上没听说过。

不拔线，用命令重启网络可以激活网络吗？如果可以的话加到启动任务里。

**Comment by luoluo888** [comment]
换个dtb，把版本降到5.4试试

**Comment by Shiyang-Wang** [comment]
对哈，我换个内核版本试试



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: luoluo888 ***@***.***&gt;
发送时间: 2022年7月19日 19:13
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
换个dtb，把版本降到5.4试试

**Comment by luoluo888** [comment]
armbian-update 5.4.206

**Comment by einsqing** [comment]
1不能直接按盒子上的关机键，必须先poweroff，2安装u盘不能在安卓里面拔插。估计可能是以上2个原因，我后面没有遇到这个问题了

**Comment by Shiyang-Wang** [comment]
都不是的，直接reboot，多reboot加次就会断网



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: einsqing ***@***.***&gt;
发送时间: 2022年7月20日 11:27
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
1不能直接按盒子上的关机键，必须先poweroff，2安装u盘不能在安卓里面拔插。估计可能是以上2个原因，我后面没有遇到这个问题了

**Comment by sesame-foxes** [comment]
我也遇到了这个问题，尝试使用命令重启网口，依然没有ip，使用固定ip也没有效果，还是有几率不在路由器上显示。

**Comment by Shiyang-Wang** [comment]
刷最新版本有所缓解



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: sesame-foxes ***@***.***&gt;
发送时间: 2022年7月27日 21:45
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
我也遇到了这个问题，尝试使用命令重启网口，依然没有ip，使用固定ip也没有效果，还是有几率不在路由器上显示。

**Comment by xcray** [comment]
我用5.4的内核没问题，升级到5.15.58内核也出现了这个症状，看来新的不一定比旧的好使

**Comment by Shiyang-Wang** [comment]
5.4内核没问题吗？我似乎5.4也有这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: xcray ***@***.***&gt;
发送时间: 2022年8月3日 10:29
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)

**Comment by einsqing** [comment]
我上一个版本是好的，重装之后又开始了

**Comment by 0x5e** [comment]
+1 这个盒子搞得我都快emo了，用5.15启动黑屏看不了输出，用5.10概率性启动获取不到ip，折腾了一礼拜刷机无数次，我对uboot和内核也比较陌生，下周打算试下如果用脚本重启能解决问题的话就这样凑合用了。。。

**Comment by Shiyang-Wang** [comment]
ifconfig eth0 up
dhclient eth0
这两句话加入/etc/rc-local 可以解决，不过只能自动获取ip，固定ip无线


发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 11:44
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)

**Comment by Shiyang-Wang** [comment]
黑屏五输出的话，安装图形界面或者开机之后再插入hdmi线可以解决



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 11:44
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
+1 这个盒子搞得我都快emo了，用5.15启动黑屏看不了输出，用5.10概率性启动获取不到ip，折腾了一礼拜刷机无数次，我对uboot和内核也比较陌生，下周打算试下如果用脚本重启能解决问题的话就这样凑合用了。。。

**Comment by ophub** [comment]
5.15.61内核有bug，多个型号均收到hdmi无显示输出的报告，换别的版本的内核

**Comment by Shiyang-Wang** [comment]
安装xorg之后就不会无输出了，kodi,xfce都行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ophub ***@***.***&gt;
发送时间: 2022年8月21日 12:16
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
5.15.61内核有bug，多个型号均收到hdmi无显示输出的报告，换别的版本的内核

**Comment by 0x5e** [comment]
@Shiyang-Wang 好的
另外请问一下各位，是否有安装docker，是否有启动(特权模式的)容器，是否创建了macvlan的docker网络，猜测获取不到ip的偶现问题和以上几个因素会不会也有关系？感觉概率时高时低，捉摸不透

**Comment by Shiyang-Wang** [comment]
我是用kvm装的虚拟机，不用docker



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 12:41
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
@Shiyang-Wang 好的
 另外请问一下各位，是否有安装docker，是否有启动(特权模式的)容器，是否创建了macvlan的docker网络，猜测获取不到ip的偶现问题和以上几个因素会不会也有关系？感觉概率时高时低，捉摸不透

**Comment by 0x5e** [comment]
> 我是用kvm装的虚拟机，不用docker
> 
> 
> 
> 
> 
> 
> 
> 发自我的iPhone
> 
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 
> 发件人: gaosen ***@***.***&gt;
> 
> 发送时间: 2022年8月21日 12:41
> 
> 收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
> 
> 抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
> 
> 主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> @Shiyang-Wang 好的
> 
>  另外请问一下各位，是否有安装docker，是否有启动(特权模式的)容器，是否创建了macvlan的docker网络，猜测获取不到ip的偶现问题和以上几个因素会不会也有关系？感觉概率时高时低，捉摸不透
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

我qemu开启kvm报错，提示pmu相关的错误，网上搜了下信息比较少。。还以为这个盒子不支持呢，那可能和内核版本有关系了

**Comment by Shiyang-Wang** [comment]
要手动配置网桥，br0。包要装全，没问题，openwrt,debian虚拟机都能开



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 13:06
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





  
我是用kvm装的虚拟机，不用docker
 
发自我的iPhone
 
------------------ 原始邮件 ------------------
 
发件人: gaosen @.***&gt;
 
发送时间: 2022年8月21日 12:41
 
收件人: ophub/amlogic-s9xxx-armbian @.***&gt;
 
抄送: Shiyang-Wang @.&gt;, Mention @.&gt;
 
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)
 
@Shiyang-Wang 好的
 
另外请问一下各位，是否有安装docker，是否有启动(特权模式的)容器，是否创建了macvlan的docker网络，猜测获取不到ip的偶现问题和以上几个因素会不会也有关系？感觉概率时高时低，捉摸不透
 
—
 
Reply to this email directly, view it on GitHub, or unsubscribe.
 
You are receiving this because you were mentioned.Message ID: @.***&gt;
  
我qemu开启kvm报错，提示pmu相关的错误，网上搜了下信息比较少。。还以为这个盒子不支持呢，那可能和内核版本有关系了

**Comment by 0x5e** [comment]
网桥，镜像，我都没有问题，非kvm模式可以正常启动，就是kvm开起来会报错，回头我换内核再试试

**Comment by Shiyang-Wang** [comment]
实测5.10，5.15都没问题，哪里设置不对



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 13:10
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
网桥，镜像，我都没有问题，非kvm模式可以正常启动，就是kvm开起来会报错，回头我换内核再试试

**Comment by 0x5e** [comment]
先不管kvm了，获取不到网络的这个问题优先级更高一点，期待各位分享下经验

**Comment by Shiyang-Wang** [comment]
在/etc/rc-local里面，添加ifconfig eth0 up
，dhclient eth0这两句



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 17:15
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
先不管kvm了，获取不到网络的这个问题优先级更高一点，期待各位分享下经验

**Comment by 0x5e** [comment]
刚才复现了一次开机无网络，在终端里尝试了`dhclient -v eth0`会一直运行结束不了，`ifdown/ifup --verbose eth0`会报错，相关日志如下（执行顺序我忘记了）：

```shell
# > dhclient -v eth0
Internet Systems Consortium DHCP Client 4.4.1
Copyright 2004-2018 Internet Systems Consortium.
All rights reserved.
For info, please visit https://www.isc.org/software/dhcp/

Listening on LPF/veth3d0bc3c/7a:5a:3b:58:8e:e0
Sending on   LPF/veth3d0bc3c/7a:5a:3b:58:8e:e0
Listening on LPF/docker0/02:42:a1:1a:5e:d1
Sending on   LPF/docker0/02:42:a1:1a:5e:d1
Listening on LPF/eth0/36:8a:38:2b:20:75
Sending on   LPF/eth0/36:8a:38:2b:20:75
Sending on   Socket/fallback
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 3 (xid=0xec0c783d)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 3 (xid=0xf4c0a107)
DHCPREQUEST for 192.168.40.10 on eth0 to 255.255.255.255 port 67 (xid=0x262d5b35)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 5 (xid=0xf4c0a107)
DHCPREQUEST for 192.168.40.10 on eth0 to 255.255.255.255 port 67 (xid=0x262d5b35)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 8 (xid=0xec0c783d)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 13 (xid=0xf4c0a107)
DHCPREQUEST for 192.168.40.10 on eth0 to 255.255.255.255 port 67 (xid=0x262d5b35)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 7 (xid=0xec0c783d)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 9 (xid=0xec0c783d)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 19 (xid=0xf4c0a107)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0xcbbe5d69)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 12 (xid=0xec0c783d)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7 (xid=0xcbbe5d69)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0xcbbe5d69)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 15 (xid=0xec0c783d)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 13 (xid=0xf4c0a107)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14 (xid=0xcbbe5d69)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 21 (xid=0xf4c0a107)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 13 (xid=0xec0c783d)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14 (xid=0xcbbe5d69)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 11 (xid=0xec0c783d)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0xcbbe5d69)
DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 14 (xid=0xf4c0a107)
DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 11 (xid=0xec0c783d)
DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 16 (xid=0xcbbe5d69)
```

```shell
# > ifdown --verbose eth0
ifdown: interface eth0 not configured
```

```shell
# > ifup --verbose eth0
ifup: configuring interface eth0=eth0 (inet)
run-parts --exit-on-error --verbose /etc/network/if-pre-up.d
run-parts: executing /etc/network/if-pre-up.d/bridge
run-parts: executing /etc/network/if-pre-up.d/ethtool
run-parts: executing /etc/network/if-pre-up.d/hostapd
run-parts: executing /etc/network/if-pre-up.d/ifenslave
+ [ inet = meta ]
+ IF_BOND_SLAVES=
+ [  ]
+ [  ]
+ [ -z  ]
+ exit
run-parts: executing /etc/network/if-pre-up.d/vlan
run-parts: executing /etc/network/if-pre-up.d/wireless-tools
run-parts: executing /etc/network/if-pre-up.d/wpasupplicant
ip link set dev eth0 address 36:8A:38:2B:20:75
RTNETLINK answers: Device or resource busy
ifup: failed to bring up eth0
```


并且在这个时候手动给网卡设置ip和路由表之后，无报错，但是网络无法正常通信：
```
ip addr add 192.168.40.10/24 dev eth0
ip route add default via 192.168.40.1 dev eth0;
```

最后用楼上的`ifconfig eth0 up`是ok的，没想到这两者竟然有区别

**Comment by 0x5e** [comment]
另外，我昨天在给docker创建bridge的时候盒子直接失联了，今天复原之后同样的再次创建了一遍却又一切正常，建议只要是对网卡做操作的步骤都要小心，都会有偶现的失联风险，不仅仅是开机的时候。。感觉可以搞个定时任务长期监测一下，遇到问题了就重启网卡，避免人不在家的时候，导致故障发生了影响家人的使用。

**Comment by yzdjd** [comment]
网络问题确实麻烦，有时断网后重启、重插网线都无效只能重刷

**Comment by 0x5e** [comment]
我最后是放弃armbian，直刷op进emmc了，重启过几十次没有复现出网络问题，貌似挺稳定。。

**Comment by Shiyang-Wang** [comment]
op能直接刷去emmc吗？什么命令？



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月31日 18:09
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
我最后是放弃armbian，直刷op进emmc了，重启过几十次没有复现出网络问题，貌似挺稳定。。

**Comment by 0x5e** [comment]
> op能直接刷去emmc吗？什么命令？
> 
> 
> 
> 
> 
> 
> 
> 发自我的iPhone
> 
> 
> 
> 
> 
> ------------------ 原始邮件 ------------------
> 
> 发件人: gaosen ***@***.***&gt;
> 
> 发送时间: 2022年8月31日 18:09
> 
> 收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
> 
> 抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
> 
> 主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
> 
>  
> 
> 我最后是放弃armbian，直刷op进emmc了，重启过几十次没有复现出网络问题，貌似挺稳定。。
> 
>  
> 
> —
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

用o大的那个op仓库编完固件，刷进u盘，启动后用自带的luci-app-amlogic可以刷进emmc

**Comment by yzdjd** [comment]
说到断网问题，我以前用B860AV2.1刷ophub的armbian也出现断网的情况，后来刷其它版本的armbian就从不断网非常稳，感觉这是ophub固件的一个常见问题，原因大佬还没找到……

**Comment by xcray** [comment]
> 说到断网问题，我以前用B860AV2.1刷ophub的armbian也出现断网的情况，后来刷其它版本的armbian就从不断网非常稳，感觉这是ophub固件的一个常见问题，原因大佬还没找到……

哦？能否说说还有什么比较好用的armbian版本？o大心态开放的很，不会介意的~

**Comment by yzdjd** [comment]
我后来刷的是在这里下载的：https://users.armbian.com/balbes150/arm-64/比较老CM311可能不支持

**Comment by yzdjd** [comment]
是这个链接https://users.armbian.com/balbes150/arm-64/

**Comment by ophub** [comment]
150大佬的5.9内核的固件，和咱们现在使用的5.10+的固件的区别，就是从5.10内核起，kernel.org进行了u-boot偏移调整

目前5.15的内核f大打了TEXT_OFFSET补丁，照顾没有u-boot支持的设备使用。5.4和5.9是一样的设置，是长期更新的内核，你可以试试5.4内核是否存在这个问题。

**Comment by 0x5e** [comment]
我用的op也是5.4内核，因为想和op的版本找个比较接近的，怕kmod-*出问题。

**Comment by yzdjd** [comment]
我记得当时刷B860AV2.1的时候把ophub大的所有版本都试了，几乎都会出现断网的情况，典型情况就是会出现两个IP,以为是NetworkManger模块造成的，但删除是NetworkManger模块后有时就会彻底断网无法恢复，必须重刷。后来没办法才换150的，使用方面ophub大的要比150的好用

**Comment by 0x5e** [comment]
两个ip和开机无网络应该是两个问题，前者可以systemctl disable NetworkManger 或者把/etc/network/interface里的eth去掉，后者是开机后有概率在等待网络准备就绪的这步卡到超时，然后进去以后没有获取到ip

**Comment by yzdjd** [comment]
我也认为是两个问题，但这两个问题总是同时出现，只要出现两个IP网络就会不稳，在我的意识里已成连锁反应了

**Comment by yzdjd** [comment]
目前我的经验分享下：U盘armbian启动后systemctl stop NetworkManager.service 再systemctl disable NetworkManager.service，然后再从U盘armbian启动，解决了两个IP问题，然后再写入EMMC，网络就会稍微稳定些。当有两个IP时有些需要新建网络的docker就安装不上，这样操作后就可以装了

**Comment by yzdjd** [comment]
150的config文件：「config-5.9.0-arm-64」https://www.aliyundrive.com/s/KQZCub1sAkY
我也看不懂，分享给懂的大佬研究下

**Comment by lovelylain** [comment]
在rc.local里加了ifconfig eth0 down;ifconfig eth0 up，没发现什么副作用，重试了多次，暂没再遇到网卡不通情况

**Comment by yzdjd** [comment]
以上的方法都不能彻底解决网络问题，
网络问题彻底解决的方法：用ophub大固件里的u-boot和dtb,放入150大的固件，我刷的是Armbian_20.10-buster-b860-5.9.0，更改exlinux.conf ，然后刷入EMMC，网络非常稳。可惜硬盘挂载不上，可能是固件比较老USB驱动支持较少

**Comment by xcray** [comment]
怀疑跟链路协商有关。

manjaro也有这个毛病，把链路协商由自动改为手动（100M全双工）后就好了。

armbian有这问题的不妨也试试。

**Comment by xcray** [comment]
> > 怀疑跟链路协商有关。
> > manjaro也有这个毛病，把链路协商由自动改为手动（100M全双工）后就好了。
> > armbian有这问题的不妨也试试。
> > 估计根子还在dtb上
> 
> 指点下怎么改？

我现在用的是manjaro，armbian没有测试条件，你可以试试：
`auto eth0
iface eth0 inet static
  pre-up /usr/sbin/ethtool -s eth0 autoneg off speed 100 duplex full`

**Comment by yzdjd** [comment]
非常感谢。我在etc/rc.local中加入：
ethtool -s eth0 autoneg off speed 100 duplex full
应该可以吧？

**Comment by 0x5e** [comment]
> 非常感谢。我在etc/rc.local中加入：
> 
> ethtool -s eth0 autoneg off speed 100 duplex full
> 
> 应该可以吧？
> 
> 

rc.local已经是启动末期了，感觉放在这里可能晚了。出问题的话已经是卡了40多秒然后获取不到ip了的状态。

**Comment by xcray** [comment]
> rc.local已经是启动末期了，感觉放在这里可能晚了。出问题的话已经是卡了40多秒然后获取不到ip了的状态。

确实，rc.local已经是登录前的最后阶段了。
治本的方法可能还是dtb，或者其它关闭自动协商的办法

**Comment by Shiyang-Wang** [comment]
我加了这两句就再也没出现开机获取不到IP了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: gaosen ***@***.***&gt;
发送时间: 2022年8月21日 21:51
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





 
刚才复现了一次开机无网络，在终端里尝试了dhclient -v eth0会一直运行结束不了，ifdown/ifup --verbose eth0会报错，相关日志如下（执行顺序我忘记了）：
 # &gt; dhclient -v eth0 Internet Systems Consortium DHCP Client 4.4.1 Copyright 2004-2018 Internet Systems Consortium. All rights reserved. For info, please visit https://www.isc.org/software/dhcp/ Listening on LPF/veth3d0bc3c/7a:5a:3b:58:8e:e0 Sending on   LPF/veth3d0bc3c/7a:5a:3b:58:8e:e0 Listening on LPF/docker0/02:42:a1:1a:5e:d1 Sending on   LPF/docker0/02:42:a1:1a:5e:d1 Listening on LPF/eth0/36:8a:38:2b:20:75 Sending on   LPF/eth0/36:8a:38:2b:20:75 Sending on   Socket/fallback DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 3 (xid=0xec0c783d) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 3 (xid=0xf4c0a107) DHCPREQUEST for 192.168.40.10 on eth0 to 255.255.255.255 port 67 (xid=0x262d5b35) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 5 (xid=0xf4c0a107) DHCPREQUEST for 192.168.40.10 on eth0 to 255.255.255.255 port 67 (xid=0x262d5b35) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 8 (xid=0xec0c783d) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 13 (xid=0xf4c0a107) DHCPREQUEST for 192.168.40.10 on eth0 to 255.255.255.255 port 67 (xid=0x262d5b35) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 7 (xid=0xec0c783d) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 9 (xid=0xec0c783d) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 19 (xid=0xf4c0a107) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 3 (xid=0xcbbe5d69) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 12 (xid=0xec0c783d) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 7 (xid=0xcbbe5d69) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8 (xid=0xcbbe5d69) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 15 (xid=0xec0c783d) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 13 (xid=0xf4c0a107) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14 (xid=0xcbbe5d69) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 21 (xid=0xf4c0a107) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 13 (xid=0xec0c783d) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 14 (xid=0xcbbe5d69) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 11 (xid=0xec0c783d) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 9 (xid=0xcbbe5d69) DHCPDISCOVER on docker0 to 255.255.255.255 port 67 interval 14 (xid=0xf4c0a107) DHCPDISCOVER on veth3d0bc3c to 255.255.255.255 port 67 interval 11 (xid=0xec0c783d) DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 16 (xid=0xcbbe5d69)
 # &gt; ifdown --verbose eth0 ifdown: interface eth0 not configured
 # &gt; ifup --verbose eth0 ifup: configuring interface eth0=eth0 (inet) run-parts --exit-on-error --verbose /etc/network/if-pre-up.d run-parts: executing /etc/network/if-pre-up.d/bridge run-parts: executing /etc/network/if-pre-up.d/ethtool run-parts: executing /etc/network/if-pre-up.d/hostapd run-parts: executing /etc/network/if-pre-up.d/ifenslave + [ inet = meta ] + IF_BOND_SLAVES= + [  ] + [  ] + [ -z  ] + exit run-parts: executing /etc/network/if-pre-up.d/vlan run-parts: executing /etc/network/if-pre-up.d/wireless-tools run-parts: executing /etc/network/if-pre-up.d/wpasupplicant ip link set dev eth0 address 36:8A:38:2B:20:75 RTNETLINK answers: Device or resource busy ifup: failed to bring up eth0
 
并且在这个时候手动给网卡设置ip和路由表之后，无报错，但是网络无法正常通信：
 ip addr add 192.168.40.10/24 dev eth0 ip route add default via 192.168.40.1 dev eth0;  
最后用楼上的ifconfig eth0 up是ok的，没想到这两者竟然有区别

**Comment by Shiyang-Wang** [comment]
你连续reboot10次试试，我估计不行



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: einsqing ***@***.***&gt;
发送时间: 2022年7月20日 20:49
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)





  
都不是的，直接reboot，多reboot加次就会断网
 
发自我的iPhone
 
------------------ 原始邮件 ------------------
 发件人: einsqing @.&gt;
 发送时间: 2022年7月20日 11:27
 收件人: ophub/amlogic-s9xxx-armbian @.&gt;
 抄送: Shiyang-Wang @.&gt;, Author @.&gt;
 主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) 开机后网网络时常不可用，需要拔插网线 (Issue #421)
 
1不能直接按盒子上的关机键，必须先poweroff，2安装u盘不能在安卓里面拔插。估计可能是以上2个原因，我后面没有遇到这个问题了
 
—
 Reply to this email directly, view it on GitHub, or unsubscribe.
 You are receiving this because you authored the thread.Message ID: @.***&gt;
  
我原来reboot也不行，重装了几次就可以了
