### ISSUE TITLE
Debian GNU/Linux 11 (bullseye) install HomeAssistant

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#423]
hi,
I'm running your compilation in box X96max but when I install HomeAssistant I get this error:

![image](https://user-images.githubusercontent.com/83761813/179855353-f4352df1-9670-4cad-8167-7558d065d909.png)

in another box X96max does not appear

![image](https://user-images.githubusercontent.com/83761813/179855526-8bf2f7a4-50ac-413f-a914-d46c687e658c.png)

the only difference I see is that one runs the

host operating system Debian GNU/Linux 11 (bullseye)

and your version appears

host operating system Armbian 22.08.0-trunk Bullseye

it is possible to fix this because HA does run on Debian Linux Debian 11 aka Bullseye (no derivatives) ??

https://github.com/home-assistant/architecture/blob/master/adr/0014-home-assistant-supervised.md

**Comment by ophub** [comment]
The black picture below you is running on bullseye, why does it say that bullseye can't run?

**Comment by ophub** [comment]
![Snip20220720_4](https://user-images.githubusercontent.com/68696949/179886137-1014c484-a69d-4f7d-995c-1328ed8edab1.png)

![Snip20220720_2](https://user-images.githubusercontent.com/68696949/179885966-f0ba1460-9e02-46f8-9e2f-4c9954a14e09.png)

![Snip20220720_3](https://user-images.githubusercontent.com/68696949/179886172-5fb438c4-2445-483b-bc8f-4b4a5c7fbe4e.png)

![IMG_1863](https://user-images.githubusercontent.com/68696949/179886204-c8718c57-df82-40e8-94e4-06f1e53121ab.PNG)

**Comment by tv4you2016** [comment]
Well what you propose to me is an unofficial installation,
Yes in the black image I'm running the bullseye

**Comment by ophub** [comment]
https://hub.docker.com/u/linuxserver

Learn about the repository of linuxserver and see the quality of the images he makes. His docker image is compiled using the official source code, and the configuration instructions are more detailed than the official one

There are many developers, you can pull other docker images
