### ISSUE TITLE
软件中心希望增加软件NPS

### ISSUE THREAD

**Issue by lunfangyu** [ophub/amlogic-s9xxx-armbian#424]
软件中心希望增加软件：[NPS](https://github.com/ehang-io/nps)
**NPS简介：**一款轻量级、高性能、功能强大的内网穿透代理服务器。支持tcp、udp、socks5、http等几乎所有流量转发，可用来访问内网网站、本地支付接口调试、ssh访问、远程桌面，内网dns解析、内网socks5代理等等……，并带有功能强大的web管理端。
虽然软件中心已经有了类似功能的软件FRPS；但个人认为：nps有强大的web管理端，在服务器中部署，比frps更易于使用，因此强烈建议增加此软件

**Comment by ophub** [comment]
![Snip20220721_6](https://user-images.githubusercontent.com/68696949/180121087-5ada7f8a-7723-4162-b9e8-3564ebd4ba8a.png)
![Snip20220721_7](https://user-images.githubusercontent.com/68696949/180121096-089aff02-edbd-40f6-9227-51402dc1e252.png)

我测试了下，这个软件卸载不了，卸载后执行文件和web文件都还在

**Comment by ophub** [comment]
![Snip20220721_8](https://user-images.githubusercontent.com/68696949/180122438-5c7f5f07-c9fe-4dee-b53b-3d42303d3718.png)
![Snip20220721_9](https://user-images.githubusercontent.com/68696949/180122446-37eff692-db39-4d42-a160-57b74d86ca3c.png)

反复测试多次，均无法卸载，卸载命令至少应该把可执行文件/usr/bin/nps自动删除了吧

**Comment by lunfangyu** [comment]
> 

你好，服务通信端口是可以自定义的；可以通过修改/etc/nps/conf/nps.conf配置文件的bridge_port进行自定义，详情请看[服务端配置文件](https://ehang-io.github.io/nps/#/server_config?id=%e6%9c%8d%e5%8a%a1%e7%ab%af%e9%85%8d%e7%bd%ae%e6%96%87%e4%bb%b6)；web界面端口（默认8080）可以通过修改web_port进行自定义
至于软件卸载不干净问题，这点我不是很清楚；我使用过这个软件，但我是在CentOS下用过，而且我使用的时候，我是先解压，然后手工配置好配置文件，就直接执行start启动命令使用的；卸载的时候是停了服务后，手工删除目录。并未用过它的自带命令进行安装和卸载。
armbian最近刚接触，有空我会试试，谢谢

**Comment by ophub** [comment]
```
/etc/nps
/usr/bin/nps
```
这个软件安装后有几个路径写入了新文件？除了上面2个位置还有没？

**Comment by lunfangyu** [comment]
> ```
> /etc/nps
> /usr/bin/nps
> ```
> 
> 这个软件的教程很挺丰富的，你知道nps安装后有几个路径写入了新文件吗？除了上面2个位置还有没？

不知道呢；从未用过这个软件的安装命令；我一般都是解压到某个目录后运行；如果不需要了，停止进程后删除目录即可

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/98809a750055c68419b5b9684b3f194b4a69172f

NPS/NPC添加到软件列表了，我测试了下可以正常使用。
在卸载时，已知的安装目录都已经列入了删除列表。
