### ISSUE TITLE
software 安装 OMV一直提示这个，是我网络问题还是啥？用移动和联通宽带都不行

### ISSUE THREAD

**Issue by da1995** [ophub/amlogic-s9xxx-armbian#425]
[ OPTIONS ] Please Input Software ID: 305
[ INFO ] Software ID: [ 305 ]
[ INFO ] Software Name: [ OpenMediaVault ]
[ STEPS ] Start processing software: [ install OpenMediaVault ]...
[ INFO ] Software Manage: [ 305 / install ]
[ STEPS ] Start checking the installation environment...
[ STEPS ] Start downloading the OpenMediaVault installation script...
[ ERROR ] Software download failed!

**Comment by da1995** [comment]
版本信息

VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
KERNEL_VERSION='5.15.55'
PACKAGED_DATE='2022-07-16'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
UBOOT_OVERLOAD='u-boot-n1.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905d'
K510='0'

**Comment by da1995** [comment]
用移动和联通宽带都不行，如果是因为网络问题，我在想办法，但没有提示，只是提示下载失败，不知道是什么原因

**Comment by ophub** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/installScript

脚本从这里下载，说明你的armbian访问这个网站不正常
