### ISSUE TITLE
关于系统负载

### ISSUE THREAD

**Issue by lunfangyu** [ophub/amlogic-s9xxx-armbian#428]
今晚刚刚给N1刷了 [Armbian_22.08.0_Aml_s905d_jammy_5.10.131_server_2022.07.19.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_07.19.0335/Armbian_22.08.0_Aml_s905d_jammy_5.10.131_server_2022.07.19.img.gz) ；发现系统空闲时，一直负载5%。
想起之前看到的帖子 [Armbian-5.77 on N1](https://www.right.com.cn/forum/thread-510423-1-1.html) ；这个帖子说更换优化后的dtb文件可以解决高负载问题；因此我尝试手动更换，但发现更换后就启动不成功了，只能重刷。
因此冒昧地问一下，此固件是否已对高负载的问题进行过优化的了呢，如已处理，则请忽略此问题，谢谢！

**Comment by ophub** [comment]
5%不是高负载，忽略吧，n1很稳定了
