### ISSUE TITLE
Is there a way to increase the default size of USB boot

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#43]
As current setting, the size of armbian partition after booting is only around 2.5GB even the real size of USB boot storage is 16/32GB. 
Is there away to increase the default size of armbian partition to 4-5GB?
This setting will be better for installing some application/lib before cloning the whole data from USB to eMMC.
Thank you.

**Comment by ophub** [comment]
`sudo ./rebuild -d -s 5000 -k 5.4.160`

Fork repo, custom rootfs size compilation.

https://github.com/ophub/amlogic-s9xxx-armbian#detailed-build-compile-command

**Comment by dinhchinh82** [comment]
Great. thank you so much for very quick support .

**Comment by dinhchinh82** [comment]
@ophub I have used Mac M1. Is able to build your armbian firmware directly under Mac OS M1?

**Comment by ophub** [comment]
My local is built on ubuntu installed on esxi of x64.
Currently the whole process can be implemented on github Actions.
Maybe you are the first builder on M1.

**Comment by dinhchinh82** [comment]
I'm trying to build on the Ubuntu 18.04 on my Oracle cloud first. If it takes much time, I will try to build on M1 later.
Thank you.

**Comment by dinhchinh82** [comment]
I've tried to build on Ubuntu 18.04 and got the error as below

> root@instance-20211005-2237:~/amlogic-s9xxx-armbian# sudo ./rebuild -d -s 5000 -b s905x3 -k 5.10.83
(1) Auto query the latest kernel version of the same series for [ 5.10.83 ]
(1) [ 5.10.83 ] is latest kernel. 

(1) [ 5.10.83 ] Kernel loading from [ https://github.com/ophub/kernel/trunk/pub/stable/5.10.83 ]
./rebuild: line 91: svn: command not found


Welcome to build armbian for amlogic s9xxx STB!
Armbian original file: [ Armbian_21.11.0_Aml_s905x3_buster_5.10.83_2021.12.02.1308.img ], Release: [ 21.11.0 ], Version: [ 2.1308 ]
Armbian SoC List: [ s905x3  ]
Kernel List: [ 5.10.83  ]
Server space usage before starting to compile: 
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sda1      ext4   45G  7.2G   38G  16% / 

(1.1) Start build armbian [ s905x3 - 5.10.83 ]. Remaining space is 38G.
 [ s905x3 - 5.10.83 ]  (1/5) make new armbian image.
 [ s905x3 - 5.10.83 ]  (2/5) extract old armbian files.
 [ s905x3 - 5.10.83 ]  (3/5) replace kernel for armbian.
./rebuild: line 170: cd: /home/ubuntu/amlogic-s9xxx-armbian/tmp_dir/tmp_armbian/boot: No such file or directory
tar (child): -C: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 [ Error ] boot/ 5 files is missing.

**Comment by ophub** [comment]
your error:
./rebuild: line 91: `svn`: command not found
Not downloaded to the kernel file


https://github.com/ophub/amlogic-s9xxx-armbian#local-build-instructions

```
sudo apt-get update -y
sudo apt-get full-upgrade -y
sudo apt-get install -y $(curl -fsSL git.io/ubuntu-2004-server)
```

**Comment by dinhchinh82** [comment]
I've tried to follow your instruction but got stuck here

> root@instance-20211005-2237:/home/ubuntu/amlogic-s9xxx-armbian# sudo apt-get install -y $(curl -fsSL git.io/ubuntu-2004-server)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'gcc' instead of 'gcc-aarch64-linux-gnu'
Note, selecting 'zlib1g-dev' instead of 'libz-dev'
Note, selecting 'git' instead of 'git-core'
Note, selecting 'upx-ucl' instead of 'upx'
E: Unable to locate package gcc-10-aarch64-linux-gnu
root@instance-20211005-2237:/home/ubuntu/amlogic-s9xxx-armbian#

**Comment by ophub** [comment]
The dependencies currently installed on each machine are different. Some have already been installed on your machine, or there are alternative software packages, just ignore them.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#use-github-action-to-build

This project can be compiled directly on github. Same as local compilation.
I heard that Oracle’s free cloud host is free forever, but the account will be blocked somehow. When using Oracle, I’m not sure if I can connect to it next time.

**Comment by dinhchinh82** [comment]
> The dependencies currently installed on each machine are different. Some have already been installed on your machine, or there are alternative software packages, just ignore them.

I guess the reason may be from I'm using Ubuntu for ARM version, not x86.

I will try to use Github action tonight.

It's fine to close this issue now.

**Comment by ophub** [comment]
for ARM:

```
sudo apt-get update -y
sudo apt-get full-upgrade -y
sudo apt-get install -y $(curl -fsSL git.io/armbian-kernel-server)
```

**Comment by dinhchinh82** [comment]
> for ARM:
> 
> ```
> sudo apt-get update -y
> sudo apt-get full-upgrade -y
> sudo apt-get install -y $(curl -fsSL git.io/armbian-kernel-server)
> ```

Let me try. Thank you so much.

**Comment by dinhchinh82** [comment]
>sudo apt-get install -y $(curl -fsSL git.io/armbian-kernel-server)

I've passed the above command for Arm but still got error as below. Please suggest any solution if any. 

> ubuntu@build-armbian-chinh:~/amlogic-s9xxx-armbian$ sudo ./rebuild -d -s 5000 -b s905x3 -k 5.10.83
(1) Auto query the latest kernel version of the same series for [ 5.10.83 ]
(1) [ 5.10.83 ] is latest kernel. 
(1) [ 5.10.83 ] Kernel loading from [ https://github.com/ophub/kernel/trunk/pub/stable/5.10.83 ]
./rebuild: line 91: svn: command not found
Welcome to build armbian for amlogic s9xxx STB!
Armbian original file: [ Armbian_21.11.0_Aml_s905x3_buster_5.10.83_2021.12.02.1308.img ], Release: [ 21.11.0 ], Version: [ 2.1308 ]
Armbian SoC List: [ s905x3  ]
Kernel List: [ 5.10.83  ]
Server space usage before starting to compile: 
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sda1      ext4   45G  7.3G   38G  17% / 

(1.1) Start build armbian [ s905x3 - 5.10.83 ]. Remaining space is 38G.
 [ s905x3 - 5.10.83 ]  (1/5) make new armbian image.
 [ s905x3 - 5.10.83 ]  (2/5) extract old armbian files.
 [ s905x3 - 5.10.83 ]  (3/5) replace kernel for armbian.
./rebuild: line 170: cd: /home/ubuntu/amlogic-s9xxx-armbian/tmp_dir/tmp_armbian/boot: No such file or directory
tar (child): -C: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
 [ Error ] boot/ 5 files is missing.
