### ISSUE TITLE
docker安装失败

### ISSUE THREAD

**Issue by lunfangyu** [ophub/amlogic-s9xxx-armbian#430]
RT，安装docker报错：

`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following additional packages will be installed:
  containerd runc
Suggested packages:
  aufs-tools cgroupfs-mount | cgroup-lite debootstrap docker-doc rinse zfs-fuse | zfsutils
Recommended packages:
  pigz ubuntu-fan apparmor
The following NEW packages will be installed:
  containerd docker.io runc
0 upgraded, 3 newly installed, 0 to remove and 8 not upgraded.
1 not fully installed or removed.
Need to get 0 B/49.5 MB of archives.
After this operation, 241 MB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Preconfiguring packages ...
Setting up libc-bin (2.35-0ubuntu3) ...
Segmentation fault
Segmentation fault
dpkg: error processing package libc-bin (--configure):
 installed libc-bin package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 libc-bin
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
![image_20220723184627](https://user-images.githubusercontent.com/41062458/180601980-b6982d07-d63b-4113-8b79-3ac23f8af7db.png)

**Comment by lunfangyu** [comment]
请忽略，使用软件中心安装docker，已安装成功。不是很了解为什么用命令无法安装成功。
之前刷CentOS用命令安装docker没问题。

**Comment by ophub** [comment]
有些前置操作，需要添加认证，用软件中心的安装，我仔细测试过。

**Comment by lunfangyu** [comment]
软件中心是可以把docker安装成功了。
但是无法使用systemctl start docker 启动docker或者查看docker状态

**Comment by ophub** [comment]
```
sudo systemctl daemon-reload
sudo systemctl restart docker

docker ps
docker images
```

**Comment by lunfangyu** [comment]
> ```
> sudo systemctl daemon-reload
> sudo systemctl restart docker
> 
> docker ps
> docker images
> docker info
> ```

非常感谢！👌🏻

**Comment by lunfangyu** [comment]
![image_20220723221148](https://user-images.githubusercontent.com/41062458/180608751-5a071ffd-eebb-490e-8eb1-496a8a112361.png)
仍然不行，很奇怪。

![image_20220723221307](https://user-images.githubusercontent.com/41062458/180608782-c96eb30a-479f-4e79-865b-8c7ad61b669a.png)
![image_20220723221321](https://user-images.githubusercontent.com/41062458/180608788-a3a35ded-851b-474a-93c8-ce550acdde6c.png)
另外顺带问下，305OpenMediaVault这个软件怎么没了？

**Comment by ophub** [comment]
OpenMediaVault只有bullseye可以使用，jammy不支持
你使用软件中心把docker卸载重装下

**Comment by lunfangyu** [comment]
> OpenMediaVault只有bullseye可以使用，jammy不支持 你使用软件中心把docker卸载重装下

![image_20220723231838](https://user-images.githubusercontent.com/41062458/180611294-8038bfa5-0211-426f-ad1f-ecd4712a6de3.png)
重装了，结果一样。

![image_20220723232004](https://user-images.githubusercontent.com/41062458/180611336-1264f900-b65c-4ad8-91a4-7f1f6cec118e.png)
奇怪的是，已经安装过了，进入软件中心看到状态却是未安装。

这么晚打扰了，明天我再安装 bullseye 版本看看

**Comment by ophub** [comment]
你看你发的安装信息，多个失败，包没有装上。调整一下你的网络，这个是从docker.com官网下载

**Comment by lunfangyu** [comment]
> 你看你发的安装信息，多个失败，包没有装上。调整一下你的网络，这个是从docker.com官网下载

要更改源吗？

**Comment by ophub** [comment]
![Snip20220724_1](https://user-images.githubusercontent.com/68696949/180627828-b896b078-96f2-42c8-8d10-42f011ac5d50.png)
![Snip20220724_2](https://user-images.githubusercontent.com/68696949/180627829-97ac77f8-fc20-4e94-a71c-fffad6e8879a.png)

换你能稳定访问的源

**Comment by lunfangyu** [comment]
![image_20220724100712](https://user-images.githubusercontent.com/41062458/180629220-20e0e61b-795d-46b8-a922-d819562b4b3c.png)

换源后docker 安装好了，也成功运行；安装portainer也没问题；
但是又出现个新问题：在N1重启后，docker就无法启动了；
![image_20220724101543](https://user-images.githubusercontent.com/41062458/180629354-6ae6ac85-1528-4eaf-a620-364c07c0e4dd.png)
然后我尝试重新安装docker ; 从软件中心进行卸载，卸载过程没有报错，显示卸载成功；
![image_20220724101613](https://user-images.githubusercontent.com/41062458/180629367-604a3cf6-a58b-43c0-96a1-ed8afa5677d6.png)
但我再次进入软件中心时，看到还是已安装的状态。

![image_20220724101941](https://user-images.githubusercontent.com/41062458/180629461-cfd420da-3935-45b7-8082-d8b9fea7208d.png)

然后我选择软件升级，升级完成后，仍然无法启动

**Comment by ophub** [comment]
`armbian-docker`

执行这个安装

**Comment by lunfangyu** [comment]
> 我测试了下，是docker-ce没彻底删除了，我更新了，你使用`armbian-sync`命令可以更新本地脚本至最新，然后再运行`armbian-software`命令卸载安装即可

收到，刚才使用armbian-docker命令没问题，我等下再试试这个

**Comment by lunfangyu** [comment]
![OMV](https://user-images.githubusercontent.com/41062458/180633160-c14d5800-3fb5-4229-bcd1-5597b5475247.png)
1、软件中心安装OMV失败。清华源或者中科大源均如此。


``
Install the openmediavault keyring manually:

apt-get install --yes gnupg
wget -O "/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc" https://packages.openmediavault.org/public/archive.key
apt-key add "/etc/apt/trusted.gpg.d/openmediavault-archive-keyring.asc"
Add the package repositories:

cat <<EOF >> /etc/apt/sources.list.d/openmediavault.list
deb https://packages.openmediavault.org/public shaitan main
# deb https://downloads.sourceforge.net/project/openmediavault/packages shaitan main
## Uncomment the following line to add software from the proposed repository.
# deb https://packages.openmediavault.org/public shaitan-proposed main
# deb https://downloads.sourceforge.net/project/openmediavault/packages shaitan-proposed main
## This software is not part of OpenMediaVault, but is offered by third-party
## developers as a service to OpenMediaVault users.
# deb https://packages.openmediavault.org/public shaitan partner
# deb https://downloads.sourceforge.net/project/openmediavault/packages shaitan partner
EOF
``
2、然后我按照 [OMV安装教程](https://openmediavault.readthedocs.io/en/latest/installation/on_debian.html) 教程，提前做好以上配置，然后再用软件中心安装，也安装不成功。


3、之后按照这个 [OMV安装教程](https://openmediavault.readthedocs.io/en/latest/installation/on_debian.html) 的命令进行安装，可以安装成功

**Comment by ophub** [comment]
我集成的这个是官方的脚本，安装文件是从github下载，看来你的网络访问github不通畅。
