### ISSUE TITLE
CM311-1a(s905l3a) usb外接磁盘挂载成功后，随机过一段时间，盘符变更，读写失败

### ISSUE THREAD

**Issue by zhangyz189** [ophub/amlogic-s9xxx-armbian#431]
尝试使用过5.15.55，5.4.207
尝试找了些相关资料，均未成功
使用的dtb选项是302

**Comment by Shiyang-Wang** [comment]
你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？

**Comment by zhangyz189** [comment]
> 你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？



> 你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？

会的，但是这个能忍受，拔了重插就能识别了，盘符变更这个太难受了

**Comment by Shiyang-Wang** [comment]
我304，现在主要是重启网卡识别问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: zhangyz189 ***@***.***&gt;
发送时间: 2022年7月23日 22:51
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) usb外接磁盘挂载成功后，随机过一段时间，盘符变更，读写失败 (Issue #431)





  
你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？
   
你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？
  
会的，但是这个能忍受，拔了重插就能识别了，盘符变更这个太难受了

**Comment by ophub** [comment]
你添加一条挂载到/etc/fstab固定到一个目录

**Comment by zhangyz189** [comment]
> 

你挂载USB磁盘没问题吗？

**Comment by ophub** [comment]
我没这个盒子，但是挂载方法相同

**Comment by zhangyz189** [comment]
> 我304，现在主要是重启网卡识别问题 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: zhangyz189 ***@***.***&gt; 发送时间: 2022年7月23日 22:51 收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt; 抄送: Shiyang-Wang ***@***.***&gt;, Comment ***@***.***&gt; 主题: Re: [ophub/amlogic-s9xxx-armbian] CM311-1a(s905l3a) usb外接磁盘挂载成功后，随机过一段时间，盘符变更，读写失败 (Issue #431) 你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？ 你302的dtb会出现重启或者开机后偶尔连不上网的情况吗？ 会的，但是这个能忍受，拔了重插就能识别了，盘符变更这个太难受了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问你挂载磁盘没问题吗？
用的是5.15.55，dtb选的304 磁盘选的btrfs吗？方便告知下这些信息吗，我按你的重新刷看看

**Comment by Shiyang-Wang** [comment]
我不挂在磁盘使用，所以没测试

**Comment by zhangyz189** [comment]
> 你添加一条挂载到/etc/fstab固定到一个目录

这个我尝试过，通过UUID挂载的，启动的时候一切正常，比如启动时盘符是/dev/sda1，过一会就变更为/dev/sdc1了

**Comment by Shiyang-Wang** [comment]
你这个问题可以试试不通过盘符挂载，通过UUID挂载，看能不能解决。

**Comment by zhangyz189** [comment]
> 你这个问题可以试试不通过盘符挂载，通过UUID挂载，看能不能解决。

这个尝试过，但是最终还是通过设备名挂载的，dmesg有很多usb disconect 的信息
[ 1260.164833] usb 1-2: USB disconnect, device number 24
[ 1261.825813] usb 1-2: USB disconnect, device number 25
[ 1263.427979] usb 1-2: USB disconnect, device number 26
[ 1265.023932] usb 1-2: USB disconnect, device number 27
[ 1287.460699] usb 1-2: USB disconnect, device number 28
[ 1289.077120] usb 1-2: USB disconnect, device number 29
[ 1290.739711] usb 1-2: USB disconnect, device number 30
[ 1292.401112] usb 1-2: USB disconnect, device number 31
[ 1294.129328] usb 1-2: USB disconnect, device number 32
[ 1295.747597] usb 1-2: USB disconnect, device number 33
[ 1297.404208] usb 1-2: USB disconnect, device number 34
[ 1298.997112] usb 1-2: USB disconnect, device number 35
[ 1300.532754] usb 1-2: USB disconnect, device number 36
armbian:~:# ls -lht /dev/disk/by-uuid/1390d3b2-bb56-437d-9b60-6999480a8261
lrwxrwxrwx 1 root root 10 Jul 23 21:39 /dev/disk/by-uuid/1390d3b2-bb56-437d-9b60-6999480a8261 -> ../../sda2

**Comment by ophub** [comment]
u盘去windows下修复一下，或者挂在armbian下重新格式化了

**Comment by zhangyz189** [comment]
收到，我再尝试下

**Comment by ophub** [comment]
如果你长期挂在armbian下使用，建议你的磁盘格式使用linux的，比如ext4或者btrfs等，这样比较文档，你用NTFS等格式可能会出现不稳定现象
