### ISSUE TITLE
B860H v5 Support

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#433]
Dear @ophub,

This day i can booting my B860H v5 that using S905X2 SoC
But, i'm changing boot partition using source from here, but i'm excluding the uEnv
https://www.facebook.com/groups/armarchindo/permalink/438640774824289/

I already repack the boot partition
https://gofile.io/d/pMk7gl <- uploaded here because the filesize is > 25MB

So, looks like the builder is already having dedicated .dtb
[zte-v5.dtb.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9175247/zte-v5.dtb.txt)

Can you investigate it?

**Comment by ophub** [comment]
I don't have a facebook account, so I can't read the content

You mean you made zte-v5.dtb files?
You don't use the uEnv.txt file, what are you using?

**Comment by rapdodge** [comment]
> I don't have a facebook account, so I can't read the content
> 
> You mean you made zte-v5.dtb files? You don't use the uEnv.txt file, what are you using?

![image](https://user-images.githubusercontent.com/33513626/180636368-2a1d37d7-a7f7-4009-b6e2-8583157ff361.png)

I'm still using uEnv.txt, but i'm not replacing it with boot partition that i unpacked... So, i'm just editing it to use zte-v5.dtb...

**Comment by ophub** [comment]
```
        FDTFILE="zte-v5.dtb"
        UBOOT_OVERLOAD="u-boot-x96max.bin"
        MAINLINE_UBOOT="x96max-u-boot.bin.sd.bin"
        ANDROID_UBOOT=""
```

Do you use a combination like this? Have you tested both 5.10 and 5.15 kernels?
If these two are tested, you can share your dts source code

https://github.com/ophub/amlogic-s9xxx-armbian/blob/e02f5e313b2cc824fc37c73c36299821d52c9f3e/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L26

There is a B860H (s912) version here, yours is an s905x2?

**Comment by rapdodge** [comment]
B860H v1 and v2 are using S905X SoC, and S905X v5 are using S905X2

On testing... And i already request for .dts file from the builder

**Comment by rapdodge** [comment]
With x96max dtb -> https://pastebin.com/8h5B941c
With zte-v5.dtb -> https://pastebin.com/Ev2Jmw6n

5.10 kernel, both are not booting to armbian

With x96max dtb -> https://pastebin.com/gJUihGve
With zte-v5.dtb -> https://pastebin.com/vL8uKU6p

5.15 kernel, both are not booting to armbian


Conclusion, it's working when using all boot files from the unpacked images...
Using zte-v5.dtb -> https://pastebin.com/g3jZgTUX

**Comment by ophub** [comment]
Can only be used in SD card, can not be written to EMMC?

**Comment by rapdodge** [comment]
> Can only be used in SD card, can not be written to EMMC?

I think it can be written to emmc, but, when i'm unplug the power and the sdcard, and plug the power again, it's stuck, not booting to the armbian...

**Comment by rapdodge** [comment]
dts file

`// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Maintainer = sibondt
 */

/dts-v1/;

#include "meson-g12a-x96-max.dts"

/ {
 compatible = "amlogic,u200", "amlogic,g12a";
 model = "ZTE B860H V5";

 memory@0 {
 device_type = "memory";
 reg = <0x0 0x0 0x0 0x80000000>;
 };
};

&ext_mdio {
 external_phy: ethernet-phy@0 {
       compatible = "ethernet-phy-id001c.c916", "ethernet-phy-ieee802.3-c22";
       reg = <0>;
       max-speed = <1000>;
       eee-broken-1000t;
 };
};

&ethmac {
        pinctrl-0 = <&eth_pins>;
        pinctrl-names = "default";
        status = "okay";
        phy-mode = "rmii";
        phy-handle = <&internal_ephy>;
};

/* SDIO */
&sd_emmc_a {
 status = "okay";
 pinctrl-0 = <&sdio_pins>;
 pinctrl-1 = <&sdio_clk_gate_pins>;
 pinctrl-names = "default", "clk-gate";
 #address-cells = <1>;
 #size-cells = <0>;

 bus-width = <4>;
 cap-sd-highspeed;
 sd-uhs-sdr50;
 sd-uhs-sdr104;
 min-frequency = <400000>;
 max-frequency = <199999997>;

 non-removable;
 disable-wp;

 /* WiFi firmware requires power to be kept while in suspend */
 keep-power-in-suspend;

 mmc-pwrseq = <&sdio_pwrseq>;

 vmmc-supply = <&vddao_3v3>;
 vqmmc-supply = <&vddao_1v8>;
};`

**Comment by rapdodge** [comment]
An update...
Using FDT=/dtb/amlogic/meson-g12a-x96-max-rmii.dtb is working... But wifi is not working...

So, i assume there is an edit on script, and the maybe u-boot ext, sd, usb...

![image](https://user-images.githubusercontent.com/33513626/180697814-f2e62634-cf8d-40ae-a48f-0a62410ea4f2.png)
5.15.57-flippy-75+o


`LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-g12a-x96-max-rmii.dtb
APPEND=root=UUID=46effec5-88cd-4854-807c-5ec46b6bff1c rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
`

**Comment by rapdodge** [comment]
Some research, u-boot.ext is using u-boot-x96max.bin
Other file is likely same, but, there is difference on aml_autoscript by sibondt...

![image](https://user-images.githubusercontent.com/33513626/180701018-9847c689-2f2f-4b2c-82d2-1e1b617888ab.png)

[aml_autoscript.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9178110/aml_autoscript.txt)

**Comment by ophub** [comment]
> Using FDT=/dtb/amlogic/meson-g12a-x96-max-rmii.dtb is working... But wifi is not working...

`/usr/lib/firmware/mediatek/mt7668pr2h.bin`

There is this file in the firmware, try it. You use the `modprobe mt76` command to load the module, and then look at the `dmesg | grep mt76` log

**Comment by rapdodge** [comment]
> dmesg | grep mt76

Nothing happen
![image](https://user-images.githubusercontent.com/33513626/180702546-be6867db-d102-48e1-b2f7-0446e9022f90.png)

**Comment by ophub** [comment]
`modprobe mt76-sdio`

**Comment by rapdodge** [comment]
![image](https://user-images.githubusercontent.com/33513626/180799630-cf8c8b7c-f25b-4f07-bd5f-944c6b957dba.png)

Still, no response...

**Comment by ophub** [comment]
Can your zte-v5.dtb be used normally? Wired, wifi and bluetooth all normal?

**Comment by rapdodge** [comment]
Already try it before, and it shouldnt work too...

**Comment by ophub** [comment]
Then you use the wired network of meson-g12a-x96-max-rmii.dtb. The MT76 driver in the wireless and bluetooth kernel has been enabled, but it cannot be used. I will talk about it later.

**Comment by rapdodge** [comment]
Okay, no problem...

**Comment by mrnose** [comment]
Any have Firmware Realunix Pro? Please For b860h v5
