### ISSUE TITLE
X96 Max plus ethernet problem

### ISSUE THREAD

**Issue by mat20099** [ophub/amlogic-s9xxx-armbian#434]
HI,

I have problem with dtb file and i haven´t a ethernet. i bought usb hub with ethernet to resolve this problem. I connect lan in eth1.
it is possible disable a error message "meson8b-dmuac ff3f0000.ethernet:failed to reset dma...." and just use the eth1?
if yes, how do configure? 
I want to disable all settings with eth0. 

Sorry for my english.

**Comment by prakai** [comment]
There are several models of "X96 Max Plus".
   - Board with 100Mbps speed using meson-sm1-sei610.dtb. Ethernet, Wi-Fi, Bluetooth work fine.
   - Board with 1000Mbps speed using meson-sm1-x96-max-plus.dtb. Wi-Fi and Bluetooth not work or not stable.

**Comment by mat20099** [comment]
Thanks for the answer.
I've tested them all.  I just wanted to work only with eth1 and the error would disappear.
I've wasted a lot of time testing dtb. it doesn't work.

**Comment by mat20099** [comment]
![IMG_20220724_184244](https://user-images.githubusercontent.com/96350082/180820943-0f3f4878-81fe-4e46-b69d-674c2af54e36.jpg)

**Comment by ophub** [comment]
![Snip20220726_1](https://user-images.githubusercontent.com/68696949/180914668-c0cbebd1-891d-4a6d-86b4-3d9396ef0fcb.png)

try
