### ISSUE TITLE
ERROR rebuild IMG

### ISSUE THREAD

**Issue by gausus2** [ophub/amlogic-s9xxx-armbian#436]
Download Armbian_22.08.0_Aml_s905x3_jammy_5.15.57_server_2022.07.25.img
Copy to folder : $HOME/amlogic-s9xxx-armbian/build/output/images

Unable to rebuild.
`cat: etc/os-release: No such file or directory`

sudo ./rebuild -d -b s905x3 -k 5.10.125
sudo ./rebuild -d -b s905x3 -k 5.18.4
sudo ./rebuild -d -b s905x3 -k 5.15.57

```

[ INFO ] Setting parameters: [ -d -b s905x3 -k 5.15.56 ] 

[ INFO ] Armbian rebuild file: [ Armbian_22.08.0_Aml_s905x3_jammy_5.15.57_server_2022.07.25.img ], Version: [ 22.08.0 ]
[ INFO ] (1) Auto query the latest kernel version of the same series for [ 5.15.56 ]
[ INFO ] (1) [ 5.15.57 ] is latest kernel. 

[ INFO ] (1) [ 5.15.57 ] Kernel is in the local directory.
[ INFO ] Armbian SoC List: [ s905x3  ]
[ INFO ] Kernel List: [ 5.15.57  ]
[ INFO ] ROOTFS Type: [ ext4 ] 

(1.1) Start building Armbian [ s905x3 - 5.15.57 ]. Remaining space is 298G.
 [ s905x3 - 5.15.57 ]  (1/6) Confirm version type.
 [ s905x3 - 5.15.57 ]  (2/6) Extract old armbian files.
cat: etc/os-release: No such file or directory
[ ERROR ] The [ etc/os-release: ID ] is invalid.
```

Can IMG rebuild / build  include desktop like XFCE ?
armbian-config desktop install not working.

Tested on Ubuntu 22.04 LTS
Linux xubuntu 5.15.0-37-generic #39-Ubuntu SMP Wed Jun 1 19:16:45 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#local-build-instructions

**Comment by gausus2** [comment]
Thank you for your amazing work and support !!

Yes need to use the Trunk IMG.
Armbian_22.08.0-trunk_Odroidn2_jammy_current_5.10.133.img

Suggestion to rebuild doc , ONLY trunk Odroidn2 img will work to rebuild.
Have successfully rebuild to kernel 5.18.4

Tested on X96max plus 
Wifi and Ethernet (1 Gb/s) works fine.
 
Some problem setting up XFCE desktop.
Setup from armbian-config not working.

MANUEL install 
sudo apt install xubuntu-desktop

After this able to boot to XFCE , but had install / config things to get it working properly.
Will you make Desktop IMG for download ?

**Comment by ophub** [comment]
Only the server version is provided, the desktop can be installed in `armbian-software`
