### ISSUE TITLE
Ubuntu userspace

### ISSUE THREAD

**Issue by danielkucera** [ophub/amlogic-s9xxx-armbian#44]
Hi,

thanks for the project. 

Is there a way to install Ubuntu userspace instead of Debian?

**Comment by ophub** [comment]
fork and change:

https://github.com/ophub/amlogic-s9xxx-armbian/blob/850e2fdcde4d16022723aebf77d3147cbf1b3164/.github/workflows/build-armbian.yml#L69


`RELEASE=bullseye`

RELEASE ( stretch | buster | bullseye | bionic | focal | hirsute ): set OS release manually to skip dialog prompt; use this option with KERNEL_ONLY=yes to create board support package

https://docs.armbian.com/Developer-Guide_Build-Options/

Finally, change the corresponding software source to `bullseye` yourself.

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/amlogic-s9xxx/common-files/files/etc/apt/sources.list

**Comment by danielkucera** [comment]
Works great. Thank you!
