### ISSUE TITLE
作者大大，我想问一下刷了armbian的，怎么刷到openwrt或者电视盒子？armbian有点高端，玩不转，想刷回去

### ISSUE THREAD

**Issue by da1995** [ophub/amlogic-s9xxx-armbian#440]
想刷回去，做个旁路由算了
刷了armbian，安装docker，安装宝塔，然后就快没存储空间了，所以还是刷回去老实巴交的呆着吧

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

12.3的方法
