### ISSUE TITLE
No wifi on X96max 4gb

### ISSUE THREAD

**Issue by evteevalex** [ophub/amlogic-s9xxx-armbian#441]
wifi chip  Ampack AP6356S
FDT=/dtb/amlogic/meson-g12a-x96-max.dtb

Welcome to Armbian 22.08.0-trunk Bullseye with Linux 5.15.57-flippy-75+o

System load:   87%              Up time:       0 min
Memory usage:  15% of 3.70G     IP:             192.168.1.xxx
CPU temp:      33°C             Usage of /:    47% of 28G
RX today:      158.5 MiB

Last login: Wed Jul 27 19:16:00 2022 from 192.168.1.199
root@armbian:~# iwconfig
lo        no wireless extensions.

sit0      no wireless extensions.

ip6tnl0   no wireless extensions.

eth0      no wireless extensions.

hassio    no wireless extensions.

docker0   no wireless extensions.

veth60bb1bc  no wireless extensions.

veth5642962  no wireless extensions.

vethb837e80  no wireless extensions.

vethd318a20  no wireless extensions.

veth70b50fd  no wireless extensions.

vethd6ab77e  no wireless extensions.

veth2bc7553  no wireless extensions.

veth0e54a78  no wireless extensions.

veth982eda2  no wireless extensions.

vethbc0f21b  no wireless extensions.

root@armbian:~#

**Comment by ophub** [comment]
I checked the AP6356S chip that gpt-pro also uses, and the wifi is also unavailable at present.

Use a wired network

**Comment by thanhhieuqb** [comment]
My X96Max 4GB has the same problem. Wifi module is FN-LINK 6222B-SRB. Wifi chip RTL8222BS. I user meson-g12a-x96-max.dtb file.
