### ISSUE TITLE
SSD attached to USB 3.0 Docking Station using Quirks instead UAS, TRIM is not supported

### ISSUE THREAD

**Issue by Gosokan** [ophub/amlogic-s9xxx-armbian#443]
**Describe the bug**
USB SSD Docking not supported UAS in Armbian HK1-Box. Trim not supported in Quirks mode

**To Reproduce**
Linux ARM64-s905X3 5.18.15-flippy-75+ #16 SMP PREEMPT Sat Jul 30 11:44:47 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

root@ARM64-s905X3:~# dmesg
[    3.188786] usb 2-1: new SuperSpeed USB device number 2 using xhci-hcd
[    3.209680] usb 2-1: New USB device found, idVendor=174c, idProduct=55aa, bcdDevice= 1.00
[    3.209704] usb 2-1: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[    3.209710] usb 2-1: Product: Ugreen Storage Device
[    3.209715] usb 2-1: Manufacturer: Ugreen
[    3.209719] usb 2-1: SerialNumber: 023458F34E69
[    3.210677] usb-storage 2-1:1.0: USB Mass Storage device detected
[    3.211064] usb-storage 2-1:1.0: **Quirks match for vid 174c pid 55aa: 400000**

root@ARM64-s905X3:~# lsusb
Bus 002 Device 002: ID 174c:55aa ASMedia Technology Inc. ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge, ASM1153E SATA 6Gb/s bridge

root@ARM64-s905X3:~# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 5000M
    |__ Port 1: Dev 2, If 0, Class=Mass Storage, Driver=usb-storage, 5000M

root@ARM64-s905X3:~# fstrim -v /
fstrim: /: the discard operation is not supported

**Expected behavior**
USB Docking run on USB 3.0 with UAS driver, just like on the raspberry pi4. So trim can working properly. Example in Raspberry Pi 4:

root@RasPiBuster-ARM:~# lsusb
Bus 002 Device 002: ID 174c:55aa ASMedia Technology Inc. Name: ASM1051E SATA 6Gb/s bridge, ASM1053E SATA 6Gb/s bridge, ASM1153 SATA 3Gb/s bridge, ASM1153E SATA 6Gb/s bridge

root@RasPiBuster-ARM:~# lsusb -t
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
    |__ Port 1: Dev 2, If 0, Class=Mass Storage, Driver=uas, 5000M

**Armbian Version**
Armbian 22.08.0-trunk Jammy with Linux 5.18.15-flippy-75+
 - Kernel Version: 5.18.15-flippy-75+
 - Release: jammy
 - Edition: server

**Device (please complete the following information):**
 - SOC: Amlogic s905x3
 - Brand: HK1 Box

How to enable UAS and TRIM?

**Comment by ophub** [comment]
https://www.jeffgeerling.com/blog/2020/enabling-trim-on-external-ssd-on-raspberry-pi
