### ISSUE TITLE
可以启动的硬盘，换了个SATA-USB转接线就不启动了，难道UUID会变？

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#444]
M401A盒子，用硬盘底座、rufus烧好，插到盒子上正常启动毫无问题。

啥都没变，就换了根SATA-USB的线（底座毕竟大了点），连USB口都没变，就无法启动了，黑屏。

用另一块硬盘插底座启动，SATA-USB线接硬盘插到盒子上，系统也可以正常识别。

难道换了个SATA-USB适配器，系统里分区的UUID也会跟着变？

**Comment by ophub** [comment]
blkid可以看一下uuid

**Comment by xcray** [comment]
感谢！
看了一下，blkid报告的uuid和uEnv.txt文件中使用的是一样的，也就是说更换SATA-USB适配器并没有影响到UUID。看来是这根线的兼容性不太好
