### ISSUE TITLE
搜索发现Calmact与3月1号提交加入了u200的主线uboot，后来这个文件又被去掉了，仔细检查竟然和overload uboot是同一个文件！

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#445]
提交记录：
https://github.com/ophub/amlogic-s9xxx-armbian/commit/8a41a63511031b8d297d357e101455d39fa0e299

经过多个版本反复试验，我发现手上的M401A盒子必须使用u200的dtb和主线uboot才能从emmc启动，少了这个主线uboot，怎么都不行。原来的主线uboot文件我也试过，无法用于启动新版内核/系统，搜了搜uboot相关文档，发现自己的能力远不足以自己编译。。。

能否请求把u200的主线uboot再加回来？

仔细检查了一番，仓库里和镜像中，当初u200的overload uboot和主线uboot是同一个文件，只是文件名不一样。而其它型号的主线uboot文件明显要比overload uboot文件大不少。
而且，我还专门用十六进制编辑工具比较了不同版本镜像里这个文件的内容，发现从来没变过！

也就是说，这个文件作为overload u-boot，可以启动任意版本的内核；但用作主线u-boot，只能引导5.4的内核。

搞得我都怀疑人生了！

**Comment by ophub** [comment]
哪个文件？

https://github.com/zzcand111/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/lib/u-boot/u-boot-u200.bin.sd.bin

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/bootfs/dtb/amlogic/meson-g12a-u200.dtb

这个组合？

后来他们群里开发了专用的主线u-boot，这个就删了，你测试过这个删了的可以用？

**Comment by ophub** [comment]
/etc/amlogic_model_database.conf

你复制304，添加305，改成你说的这个删除的。

下载这个删除的主线u-boot放入 /usr/lib/u-boot 目录下，你写入emmc测试一下。截图反馈一下

**Comment by xcray** [comment]
> 

是的，就是这个组合，写入emmc后可以启动，就是认不出网卡、2G内存也只认出1G。尝试升级内核就又变砖了。
顺便请教一下：uboot版本和内核版本是否也要匹配才行？我试过5.18内核用之前的u200主线uboot，无法启动。
明天打算再焊上TTL好好测试一下

**Comment by xcray** [comment]
> /etc/amlogic_model_database.conf
> 
> 你复制304，添加305，改成你说的这个删除的 u-boot-u200.bin.sd.bin
> 
> 下载这个删除的主线u-boot放入 /usr/lib/u-boot 目录下，你写入emmc测试一下。截图反馈一下

我记得是放在/lib/u-boot/路径下？试过两次，不过我是先选0然后手工输入dtb、overload uboot和主线uboot，第二次还特意用了完整路径，两次结果都是变砖。

**Comment by ophub** [comment]
/usr/lib/u-boot
复制305只改文件名

**Comment by xcray** [comment]
> /usr/lib/u-boot 复制305只改文件名
> 把那个u-boot文件下载，放这个路径

特意检查了一下，发现zzcand111仓库里和镜像里的u200主线和overload其实都是相同的文件，只是文件名和存放路径不同，简直怀疑人生啊！
顺便说一句：看了下/lib/u-boot和/usr/lib/u-boot其实是硬链接，也就是说我之前把文件放到/lib/u-boot下面从结果上是一样的

**Comment by ophub** [comment]
一样的

**Comment by xcray** [comment]
TTL发现还不是uboot的问题，而是写入后启动uboot发现不了emmc，提示：
Card did not respond to voltage select! : -110，看来还得修改dtb
