### ISSUE TITLE
X96  Air Q100  no Ethernet after install to emmc by armbian-install

### ISSUE THREAD

**Issue by zglqaq** [ophub/amlogic-s9xxx-armbian#446]
**Describe the bug**
I use Armbian_20.10_Arm-64_buster_current_5.9.0.img rebuild a new img by run 'sudo ./rebuild -d -b s905x3 -k 5.10.134' in ubuntu-20.04.4-desktop-amd64(focal) . this origin img have two partition, so i  edit the rebuild script to  
-----------------------------------------------------------------------------------
    #397 line
    if ! mount ${loop_old}p2 ${tmp_armbian}; then
        error_msg "mount ${loop_old}p2 failed!"   #this is rootfs partition
    fi

	if ! mount ${loop_old}p1 "${tmp_armbian}/boot"; then
        error_msg "mount ${loop_old}p1 failed!"   # this is boot partition
    fi
-----------------------------------------------------------------------------------
I burn this new img in to USB flash disk, with the  default dtb meson-sm1-x96-max-plus.dtb . Ethernet (eth0) don't work but the wifi work nice .
when I was change meson-sm1-x96-max-plus.dtb to meson-sm1-sei610.dtb . the eth0 and wifi both work nice .
so I custom the /etc/amlogic_model_database.conf add new line
521:A95XF3 Air Q100:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin:/usr/lib/u-boot/hk1box-bootloader.img
I run armbian-install with with follow parameter
-----------------------------------------------------------------------------------
AMLOGIC_SOC="s905x3"
FDTFILE="meson-sm1-sei610.dtb"
UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
MAINLINE_UBOOT="x96maxplus-u-boot.bin.sd.bin"
ANDROID_UBOOT="hk1box-bootloader.img"  # armbian-install script ignore this parameter because use MAINLINE_UBOOT
-----------------------------------------------------------------------------------
this armbian-install script pring successful info and no any error
but when i eject usb and reboot my device, the eth0 don't work , the wifi work nice 
I was check the /boot/uEnv.txt file have no error ( FDT=/dtb/amlogic/meson-sm1-sei610.dtb)
It is strange that the **eth0 don't working even my device boot from usb** after run armbian-install

then I burn X96AIR_Q100_20210126-1140.img into my device use USB_Burning_Tool (include bootloader) . This action recoverthe device to factory Settings

I insert USB flash disk reboot  and boot from usb, the eth0 and wifi  is working again
I guess the MAINLINE_UBOOT="x96maxplus-u-boot.bin.sd.bin" is not compatible with my device
so I custom the /etc/amlogic_model_database.conf add new line
522:A95XF3 Air Q100:s905x3:meson-sm1-sei610.dtb:u-boot-x96maxplus.bin:NA:NA
I run "armbian-install no" with with follow parameter
-----------------------------------------------------------------------------------
AMLOGIC_SOC="s905x3"
FDTFILE="meson-sm1-sei610.dtb"
UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
MAINLINE_UBOOT=""  #armbian-install script ignore this parameter because use MYBOX_UBOOT
ANDROID_UBOOT=""  # armbian-install script ignore this parameter because use MYBOX_UBOOT
-----------------------------------------------------------------------------------
the install script backup MYBOX_UBOOT by
     dd if=${DEV_EMMC} of=${MYBOX_UBOOT} bs=1M count=4 conv=fsync
and write back to device after Re-Partition by  
    dd if=${MYBOX_UBOOT}  of=${DEV_EMMC} conv=fsync bs=1 count=444
    dd if=${MYBOX_UBOOT}  of=${DEV_EMMC} conv=fsync bs=512 skip=1 seek=1
when I was eject the usb disk and poweron. my device can't boot . just show me a black screen 
but eth0 and wifi working when the device boot from usb disk.

conclusion : 
MAINLINE_UBOOT is not completely compatible with x96air Q100 
x96air Q100 default bootloader is not compatible with u-boot-x96maxplus.bin

How can i solve this problem ?

**Comment by ophub** [comment]
5.10 and 5.18 need mainline u-boot support to start

At present, the two kernels 5.4 and 5.15 do not need the support of the mainline u-boot, you can try these two versions.


```
AMLOGIC_SOC="s905x3"
FDTFILE="meson-sm1-sei610.dtb"
UBOOT_OVERLOAD="u-boot-x96maxplus.bin"
MAINLINE_UBOOT=""
ANDROID_UBOOT=""
```

**Comment by zglqaq** [comment]
Thanks for your replay. I try  'sudo ./rebuild -d -b s905x3 -k 5.4.208' to build  a new img. the origin img is Armbian_20.10_Arm-64_focal_current_5.9.0.img
this new img is wonderful. eth0 and wifi working . it able boot from emmc with no error
But i found a new problem that when i was install xfce4 desktop environment my mouse and keyboard will stopped responding. the keyboard no light.
I guess my install process may have fault. so i use Armbian_20.10_Arm-64_focal_current_5.9.0_desktop.img rebuild a desktop.img with same parameters
I burn this desktop.img to usb disk and boot up. in init  stage my keyboard able work. I can input new password and username.
the desktop environment launch after init stage finish. by this time my keyboard and mouse disabled and no light again.

**Comment by ophub** [comment]
`armbian-update 5.15.58`

Try the 5.18 kernel

**Comment by zglqaq** [comment]
I was try the 5.18 kernel.
with released version focal origin img. eth0 and wifi working
with released version buster origin img. wifi can't work
Compatibility problems exist between kernel and released version ?

**Comment by ophub** [comment]
buster is old, it was retired when 5.15 was released
