### ISSUE TITLE
octopus planet bricked 

### ISSUE THREAD

**Issue by nldt** [ophub/amlogic-s9xxx-armbian#449]
i 'm use this image [Armbian_22.08.0_Aml_s912_bullseye_5.15.58_server_2022.07.30.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_07.30.0258/Armbian_22.08.0_Aml_s912_bullseye_5.15.58_server_2022.07.30.img.gz) for upgrade my octopus planet

uboot znxq
meson-gxm-octopus-planet.dtb

boot from sd normal, armbian-install to emmc device cannot boot.
led octopus white. led ethenet flash orange.

**Armbian Version**
 - Kernel Version: 5.15.58
 - Release: bullseye
 - Edition: server

**Device (please complete the following information):**
 - SOC: s912
 - Brand: octopus planet

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/49189a4834d57f1988ddc4f6ef7ac27c2586c997/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L30

There are many counterfeit octopuses on the market. The shells are very similar, but the motherboards are very different from the genuine ones. You try to install with the knockoff option.
