### ISSUE TITLE
How to build Armbian_21.11.0 by Github action

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#45]
I've followed your guide to build the Armbian images via Github action.
By the way, my output is only Armbian_21.08.1_Aml_s905x3_buster_5.10.83_2021.12.04.2126.img.gz. I have not seen Armbian_21.11.0 as your build.

Please check my release:
https://github.com/dinhchinh82/amlogic-s9xxx-armbian/releases

I just only run rebuild action:
https://github.com/dinhchinh82/amlogic-s9xxx-armbian/blob/main/.github/workflows/rebuild-armbian.yml

I've changed only small thing below:

>       - name: Rebuild Armbian for Amlogic s906x3
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_soc: s905x3
          armbian_kernel: 5.10.80

Please give me the suggestion to get Armbian 21.11.0

Thank you.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#use-github-action-to-build

- Use GitHub Action to build
Workflows configuration in .yml files. Set the armbian SOC you want to build in Rebuild Armbian for amlogic s9xxx.

New compilation: Select Build armbian on the Action page. Click the Run workflow button.

Compile again: If there is an Armbian_.*-trunk_.*.img.gz file in Releases, you do not need to compile it completely, you can directly use this file to build armbian of different soc. Select Use Releases file to build armbian on the Action page. Click the Run workflow button.

**Comment by dinhchinh82** [comment]
At current I only use "Only import GitHub Action for Armbian rebuild" to rebuild with the following changes in rebuild-armbian.yaml

>       - name: Rebuild Armbian for Amlogic s906x3
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_soc: s905x3
          armbian_kernel: 5.10.80
          armbian_size: 5000

I also tried to "Use GitHub Action to build" but it takes very long (More than 1 hour but still not finished) and I already cancelled.
I will try to build according to "Use GitHub Action to build" again.

**Comment by ophub** [comment]
Rebuild is to rebuild the firmware provided by official armbian and other service providers. By default, download the currently officially released version from lepotato in https://armbian.tnahosting.net/dl/. You can choose a different version to rebuild.

[build armbian] First build the firmware based on the current source code of armbian, and then rebuild, relatively new.
