### ISSUE TITLE
can't installl software due to the kernel dpendency

### ISSUE THREAD

**Issue by jiderlesi** [ophub/amlogic-s9xxx-armbian#451]
The following packages have unmet dependencies:
 linux-image-rt-arm64 : Depends: linux-image-5.10.0-16-rt-arm64 (= 5.10.127-2) but 5.10.127-1 is installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).

I'm using phicomm N1, and I have updated the kernel to the latest version by running apt update which should be 5.15.58, but seems the package record with apt is still stay in a old version for some reasons.

**Comment by jiderlesi** [comment]
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
PACKAGED_DATE='2022-07-16'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
UBOOT_OVERLOAD='u-boot-n1.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905d'
KERNEL_VERSION='5.15.58'
K510='0'

**Comment by ophub** [comment]
Which package to install?

**Comment by jiderlesi** [comment]
this error was appear when I trying to `apt install tinc` but it appears when I try to install any package depend on kernel beside `apt upgrade`

**Comment by ophub** [comment]
![Snip20220802_1](https://user-images.githubusercontent.com/68696949/182279968-51cdd799-3fa9-4925-8a27-be4ce2589b1d.png)

**Comment by ophub** [comment]
Use `armbian-fix` to fix the permissions and try to install again

**Comment by jiderlesi** [comment]
fixed by manually `apt upgrade linux-image-5.10.0-16-rt-arm64` , thanks for your help !
