### ISSUE TITLE
No wifi with RTL8222BS chip

### ISSUE THREAD

**Issue by thanhhieuqb** [ophub/amlogic-s9xxx-armbian#453]
My X96Max 4GB has no wifi. Wifi module is FN-LINK 6222B-SRB. Wifi chip RTL8222BS. I user meson-g12a-x96-max.dtb file.

**Armbian Version**
 - Kernel Version: 5.15.58
 - Release: jammy
 - Edition:  server

**Device:**
 - SOC: S905X2
 - Model X96Max

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/drivers/net/wireless/realtek/Makefile
