### ISSUE TITLE
[功能请求] 可选使用 FastGit 进行下载

### ISSUE THREAD

**Issue by wordlesswind** [ophub/amlogic-s9xxx-armbian#454]
目前 `armbian-update` 默认通过 `github.com` 下载文件，由于网络原因，时常下载缓慢甚至无法下载，希望能够提供参数，比如 `--fastgit` 以使用 FastGit 进行下载。

https://doc.fastgit.org/zh-cn/node.html

**Comment by ophub** [comment]
https://github.com/FastGitORG/uptime



![Snip20220802_3](https://user-images.githubusercontent.com/68696949/182318016-c221553a-dd97-4759-94e6-c08f5a86c069.png)


服务不可用。如果可以使用的话，你手动下载文件即可，如：

```
wget https://raw.fastgit.org/ophub/kernel/main/pub/stable/5.15.58/boot-5.15.58-flippy-75+o.tar.gz
wget https://raw.fastgit.org/ophub/kernel/main/pub/stable/5.15.58/dtb-amlogic-5.15.58-flippy-75+o.tar.gz
wget https://raw.fastgit.org/ophub/kernel/main/pub/stable/5.15.58/header-5.15.58-flippy-75+o.tar.gz
wget https://raw.fastgit.org/ophub/kernel/main/pub/stable/5.15.58/modules-5.15.58-flippy-75+o.tar.gz
wget https://raw.fastgit.org/ophub/kernel/main/pub/stable/5.15.58/sha256sums
```

**Comment by wordlesswind** [comment]
> 服务不可用。如果可以使用的话，你手动下载文件即可，地址参照：https://github.com/ophub/kernel/tree/main/pub/stable

实际上是可以使用的
![image](https://user-images.githubusercontent.com/9050713/182321742-38c02e02-7078-42a8-b966-b4a49da270a4.png)

**Comment by ophub** [comment]
我电脑套这个CDN反而是用不了，你能访问的话这样下载吧，这几个地址可以做到一个shell文件里，一键下载
