### ISSUE TITLE
“Set user language based on your location”缺少默认值

### ISSUE THREAD

**Issue by wordlesswind** [ophub/amlogic-s9xxx-armbian#455]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
在初始化设置中“Set user language based on your location? [Y/n]”，则理应默认选择“是”，但实则无默认值。

**To Reproduce**
运行初始化设置

**Expected behavior**
回车则默认选择“是”

**Screenshots**
![image](https://user-images.githubusercontent.com/9050713/182320580-b99a072a-e990-48ff-8daa-435a8c8b25e4.png)

**Armbian Version**
 - Kernel Version: 5.15.58
 - Release:  jammy
 - Edition: server

**Device (please complete the following information):**
 - SOC: s905d
 - Brand: Phicomm
 - Model:  N1

**Additional context**
如果不设置默认值，建议将“Y”改为小写。

**Comment by ophub** [comment]
系统交互设计风格是统一的，不止这一处。建议你习惯系统的设计。
