### ISSUE TITLE
T95 S905x : can't boot after install on emmc

### ISSUE THREAD

**Issue by chris4git** [ophub/amlogic-s9xxx-armbian#456]
Hi, thanks again for your work !

I  installed Armbian_22.08.0_Aml_s905x_jammy_5.15.58_server_2022.07.30.img.gz on µSD card then to internal emmc with armbian-install (id 106, fs type btrfs) but the reboot on emmc fails and drop down in recovery menu :

![20220802_162205-2](https://user-images.githubusercontent.com/23280864/182453019-4b4ee3c6-27c3-4a2b-8dae-ab659224188e.jpg)

the box still boot on the µSD.

Any hint ?

Chris

**Comment by ophub** [comment]
In general, just use /boot/uEnv.txt. The /boot/extlinux/extlinux.conf file is required for individual devices, such as T95 (s905x) / T95Z-Plus (s912) etc. If necessary, delete the .bak in the /boot/extlinux/extlinux.conf.bak file name that comes with the firmware to use it. armbian-install automatically checks when writing to eMMC and creates an extlinux.conf file if it exists.

**Comment by chris4git** [comment]
Hi,
it's a T95 so I renamed extlinux.conf.bak as extlinux.conf to boot the SD card.
armbian-install  runs without errors but, maybe, it does something wrong ?
Any way to debug ?

Chris

**Comment by ophub** [comment]
```
cat /boot/extlinux/extlinux.conf
cat /boot/extlinux/uEnv.txt
cat /etc/fstab
cat /etc/ophub-release
```
