### ISSUE TITLE
S905安装Armbian到emmc的方法分享

### ISSUE THREAD

**Issue by xiaofami** [ophub/amlogic-s9xxx-armbian#457]
最近看到一个俄文帖子声称在 S905 GXBB 电视盒子上实现了安装 Armbian 到emmc，详细步骤及具体文件见于 https://github.com/d51x/armbian-s905/blob/main/emmc_install/v2/README.MD

概要：
1. 在uEnv.txt中通过传递 blkdevparts 参数 对emmc 进行分区。这样避免了对emmc写入分区表破坏u-boot。
2. 内核需要支持blkdevparts，[ophub](https://github.com/ophub) [amlogic-s9xxx-armbian](https://github.com/ophub/amlogic-s9xxx-armbian) 中的内核没有打开这个选项所以他自己编译了内核，在config文件中设置 **CONFIG_CMDLINE_PARTITION=Y** 即可。
3. 使用dd将dtb,内核，uEnv.txt,dtb等文件写入emmc分区，通过mmc read命令直接读取地址。注意这里没有对boot进行分区，所以作者称其为 **pseudo-BOOT partition** 
4. emmc分区偏移116MB后的空间格式化成ext4格式，作为rootfs。

希望 ophub/amlogic-s9xxx-armbian 能加入这个功能，这样S905家族最后一块拼图就补全了 :D

**Comment by ophub** [comment]
内核选项在下次更新内核时，我把模板里参照这个开启。

他已经开发了完整的安装和更新内核的脚本，可以很方便使用了，欢迎有s905设备的朋友们测试。

作者在仓库中没有申明适用的 license 版本，也没有说明允许其他项目使用，所以不能随意转载和使用他人的研究成果。感谢d51x又开启了一扇新的窗户，给更多设备提供了支持。

**Comment by zechfox** [comment]
请问目前S905设备可否使用`armbian-install`安装到emmc？还是需要按照@xiaofami推荐的方式安装到emmc？
