### ISSUE TITLE
Wrong repository arch

### ISSUE THREAD

**Issue by sangnpq** [ophub/amlogic-s9xxx-armbian#46]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/bff88e329a877b28153bb477cdc94d6ae2e59878/build-armbian/common-files/files/usr/sbin/armbian-docker#L21
Could you review this line?
[amd64]=> It should be [arm64,armhf]

**Comment by ophub** [comment]
Thanks for the feedback, it has been corrected.
