### ISSUE TITLE
Can you support bluetooth on X96 max + (S950x3 + RTL8822CS WIFI card)

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#460]
I have a X96 max+ (S905X3, 4+32G, WIFI RTL8822CS 2.4+5Ghz, Bluetooth 4.2). This device works well with latest 5.4.208 kernel including WIFI, LAN.

By the way, the bluetooth did not work. I could not see the bluetooth device on the system.
Could you check whether this card support Bluetooth on Armbian or not?

Here are additional information about the WIFI card
https://aliexpress.com/item/4000575572361.html?gatewayAdapt=glo2vnm
![image](https://user-images.githubusercontent.com/22479095/182655770-746333fb-6ac8-4317-be21-b2b3d590ed1b.png)

Thank you.

**cat /etc/ophub-release** 
> VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
PACKAGED_DATE='2022-03-06'
FDTFILE='meson-sm1-x96-air-100.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT=''
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905x3'
KERNEL_VERSION='5.4.208'
K510='0'

**dmesg | grep -i bluetooth**
> [    6.795789] Bluetooth: Core ver 2.22
[    6.798621] Bluetooth: Starting self testing
[    6.822028] Bluetooth: ECDH test passed in 19717 usecs
[    6.838389] Bluetooth: SMP test passed in 15854 usecs
[    6.849859] Bluetooth: Finished self testing
[    6.857234] Bluetooth: HCI device and connection manager initialized
[    6.863628] Bluetooth: HCI socket layer initialized
[    6.877039] Bluetooth: L2CAP socket layer initialized
[    6.894751] Bluetooth: SCO socket layer initialized
[    7.046113] Bluetooth: HCI UART driver ver 2.3
[    7.064600] Bluetooth: HCI UART protocol H4 registered
[    7.064604] Bluetooth: HCI UART protocol BCSP registered
[    7.064682] Bluetooth: HCI UART protocol LL registered
[    7.064684] Bluetooth: HCI UART protocol ATH3K registered
[    7.064711] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    7.065024] Bluetooth: HCI UART protocol Intel registered
[    7.065242] Bluetooth: HCI UART protocol Broadcom registered
[    7.065271] Bluetooth: HCI UART protocol QCA registered
[    7.065273] Bluetooth: HCI UART protocol AG6XX registered
[    7.065301] Bluetooth: HCI UART protocol Marvell registered
[    9.448770] Bluetooth: hci0: command 0xfc18 tx timeout
[   15.593241] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   15.594974] Bluetooth: BNEP filters: protocol multicast
[   15.599880] Bluetooth: BNEP socket layer initialized
[   17.338813] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   17.342214] Bluetooth: hci0: Failed to set baudrate
[   19.472153] Bluetooth: hci0: command 0x0c03 tx timeout

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/df78d7093b265022e5f5d27127a4379bf39b52d0/drivers/net/wireless/realtek/Makefile#L13

Your version is too old, test the new firmware, the driver has been added, you test it

https://github.com/ophub/amlogic-s9xxx-armbian/releases

**Comment by dinhchinh82** [comment]
@ophub my kernel is '5.4.208'. I guess this kernel is still new, right?

My X96max + could not run 5.15 from eMMC so I still must keep the 5.4 version.
Please note that the wifi still works well, only Bluetooth is not recognized.

**Comment by dinhchinh82** [comment]
> 5.15 and 5.4 are the same, how can it fail to start. My gtk with 5.4 kernel bluetooth doesn't work, with 5.15 it works

That's strange point that I already tried several times. 5.15 works well on SD card but unable to boot from eMMC. Anyway, I will try to test with 5.15 again.

**Comment by ophub** [comment]
Download the latest firmware test

**Comment by ophub** [comment]
5.15 kernel:

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts#L186
