### ISSUE TITLE
如何关闭WIFI扫描

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#461]
**Describe the bug**
一直报brcmf_cfg80211_scan:scan error,可以关掉这个扫描吗，如何关闭

**Armbian Version**
 - Kernel Version: 5.18
 - Release: jammy
 - Edition: armbian

**Device (please complete the following information):**
ugoos AM6 plus'

**Additional context**

**Comment by ophub** [comment]
把无线关了
sudo ip link set wlan0 down

**Comment by jsdfhasuh** [comment]
> 把无线关了 sudo ip link set wlan0 down

可以再请问一个问题吗，用上面的armbian系统启动虚拟机总是不成功，总是需要多启动几次
virsh start openwrt
error: Failed to start domain 'openwrt'
error: internal error: qemu unexpectedly closed the monitor: 2022-08-04T10:34:27.769492Z qemu-system-aarch64: kvm_init_vcpu: kvm_arch_init_vcpu failed (0): Invalid argument

我也根据了相关文档绑定了核心，但是自启动还是失败

**Comment by ophub** [comment]
`cat /etc/libvirt/qemu/openwrt.xml`

把你加的这块上下几行都截图

**Comment by jsdfhasuh** [comment]
![Snipaste_2022-08-04_19-26-21](https://user-images.githubusercontent.com/49879362/182836645-f4f6cbac-d7ac-4d8a-a678-143cf1cddd85.png)
![Snipaste_2022-08-04_19-26-38](https://user-images.githubusercontent.com/49879362/182836665-5fadde24-527a-4772-9de0-2d60e583dc83.png)

**Comment by ophub** [comment]
https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md

照6.8改

**Comment by jsdfhasuh** [comment]
> https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md
> 
> 照6.8改一样了，重启再试。
> 
> 我是完全一样的，测过很多次都可以。

大佬是怎么安装kvm的，是通过安装这个文档的依赖来安装吗，还是通过armbian-software来安装

**Comment by ophub** [comment]
通过armbian-software来安装，我参照f大的文档，把相关设置都自动化了。
我在jammy、focal、bullseye三个分支里都测试了。

**Comment by ophub** [comment]
不用重装，你把xml改一下再测。
这是软件使用配置，这也是刚开始用，可能会碰到新问题，多查多试就好了

**Comment by jsdfhasuh** [comment]
<vcpu placement='static' cpuset='0-5'>6</vcpu>
<cputune>
  <vcpupin vcpu='0' cpuset='0'/>
  <vcpupin vcpu='1' cpuset='1'/>
  <vcpupin vcpu='2' cpuset='2'/>
  <vcpupin vcpu='3' cpuset='3'/>
  <vcpupin vcpu='4' cpuset='4'/>
  <vcpupin vcpu='5' cpuset='5'/>
  <emulatorpin cpuset='0-5'/>
</cputune>
现在核心全绑，一直都能重启成功，没有发生报错

**Comment by jsdfhasuh** [comment]
重启12遍了，出现了两次启动失败，那两次失败连在一起,然后我手动启动一次之后就正常了

**Comment by jsdfhasuh** [comment]
改回绑定部分核心就一直启动不起来，要启动多几遍才能成功

**Comment by jsdfhasuh** [comment]
我自己写了一个脚本，循环启动，直到启动成功才停止
