### ISSUE TITLE
江苏M401A盒子，完美方案：u200的u-boot作主线写入bootloader + e900v22c的u-boot作过载 + u200的dtb，支持任意内核

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#462]
基于反复测试的经验，突发奇想，有了这个更加完美的方案！
效果：任意内核都可以正常识别网卡内存并在启动后自动获得IP地址（之前的方案只有5.4内核没问题），并且存储空间多了483MB！其它好处请o大补充。。。

步骤：

1. 写U盘，uEnv.txt里改成u200的dtb（必须）、把e900v22c的u-boot复制为u-boot.ext（建议，否则认不出网卡和全部内存），然后U盘开机。

2. 不管emmc里原来有啥固件，反正都是要覆盖掉的。
2.1   - 可以先编辑/etc/amlogic_model_database.conf文件，加一行：
`305:M401A:s905l3a:meson-g12a-u200.dtb:u-boot-e900v22c.bin:/lib/u-boot/u200-u-boot.bin.sd.bin:NA`
2.2 执行 `cp /boot/u-boot-u200.bin /lib/u-boot/u200-u-boot.bin.sd.bin`
  其实文件名无所谓，和上面一致就行。
2.3 执行 `armbian-install`，这回不加no了！选305，当然，选0手动输入也没问题，只是稍微麻烦些。

完工！

我测试了 5.4.208 和 5.18.15 内核，启动都很完美，其它内核需要的话自己测试吧。

-----------------
以下为之前的方案：

U盘测试，已知必须用u200的dtb才能启动。
用e900v22c的uboot拷贝为u-boot.ext，搭配5.4.207-208内核没问题。其它版本，包括5.15.58、5.10.13x、5.18.15都有开机认网卡但拿不到IP地址的问题。

之前用u200的u-boot使用5.4.207和5.18.14-15都没有这个问题。

怀疑其它机型启动后没有IP也和uboot及内核版本有关。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/49189a4834d57f1988ddc4f6ef7ac27c2586c997/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L44

贴一下你改的，主线内核可以NA

**Comment by xcray** [comment]
> 304:E900V22C-D:s905l3a:meson-g12a-s905l3a-e900v22c.dtb:u-boot-e900v22c.bin:/usr/lib/u-boot/e900v22c-u-boot.bin.sd.bin:NA

`305:M401A:s905l3a:meson-g12a-u200.dtb:u-boot-e900v22c.bin:NA:NA `
我是这么写的

**Comment by ophub** [comment]
有M401A的朋友们可以测试反馈下，如果这个配置方案合适，可以添加一个默认选项。

**Comment by xcray** [comment]
> 有M401A的朋友们可以测试反馈下，如果这个配置方案合适，可以添加一个默认选项。

o大，我这回真的找到了一个完美的方案，不过是拼凑出来的。要是自己直到怎么给这个盒子定制u-boot就更好了，可惜没那个能力。

**Comment by ophub** [comment]
我被你写的标题绕晕了，没有u200主线u-boot吧？

**Comment by xcray** [comment]
> 我被你写的标题绕晕了，没有u200主线u-boot吧？贴一下你的配置信息。

我更新了主贴，就是那个/boot/u-boot-u200.bin，也可以当主线用，之前zzcand111就是这么干的

**Comment by ophub** [comment]
真的假的，这2个文件用法不同

**Comment by xcray** [comment]
> 真的假的，这2个文件用法不同

刚想到这个主意时我自己也觉得有些过分，之前发现zzcand111这么干的时候就挺惊讶的。
不知道u-boot-e900v22c.bin写入bootloader会是啥效果？反正它对应的那个:/usr/lib/u-boot/e900v22c-u-boot.bin.sd.bin我用不了。

这是我这个方案的完整启动记录，也许大佬们可以分析点什么出来：
[u200主线+e900过载写emmc后无U盘重启.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9274207/u200.%2Be900.emmc.U.txt)

**Comment by xcray** [comment]
感觉对“主线”这个词含义的理解有些混乱。

放到内核版本上来说，应该自5.19正式发布那一刻开始，只有5.19.x才能叫主线吧？其它叫什么rc、stable等等。不知道u-boot版本上是否也是这个概念？

感觉和bootloader有些混淆。。。晕，写入bootloader的叫主线、放到boot分区文件系统里的叫过载？还是某个/某些版本的叫主线？

**Comment by yuan6975** [comment]
写入emmc成功后可以试试直接宝盒更新完整固件吗？

**Comment by xcray** [comment]
> 写入emmc成功后可以试试直接宝盒更新完整固件吗？

你说的是openwrt，我说的是armbian，里面没有宝盒

**Comment by yuan6975** [comment]
原理都一样吧  我的401a是老款可以直接写入没有问题

**Comment by PangPei1996** [comment]
为什么我的401A写入不了emmc呢，哪里错了
![QQ图片20221130151917](https://user-images.githubusercontent.com/119482023/204732747-77d0649f-18bb-475b-b3c0-4ce4131e33f9.png)
