### ISSUE TITLE
T95 S905x : bad LED display configuration file (N° 19)

### ISSUE THREAD

**Issue by chris4git** [ophub/amlogic-s9xxx-armbian#463]
Hi @ophub,

the configuration file /usr/share/openvfd/conf/t95.conf for T95 boxes in recent images is not good.
The definitions of gpios are shifted.
As said in issue #285 the good one is 
https://github.com/arthur-liberman/vfd-configurations/blob/master/t95m-s905x-vfd.conf

Have a good day
Chris

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/49189a4834d57f1988ddc4f6ef7ac27c2586c997/build-armbian/common-files/rootfs/usr/share/openvfd/conf/t95.conf#L12
