### ISSUE TITLE
你好，非常感谢你的工作，我的BOX型号是tx9-pro ，主板上写有qca9377字样，在uEnv.txt中修改你提供的meson-gxm-tx9-pro.dtb并且修改u-boot-zyxq.bin为u-boot.ext,这样操作后U盘可以进入系统，但是写入进emmc后开机显示器有背光但是没有任何内容，重新插入制作好的U盘却可以开机并进入到EMMC内部的系统

### ISSUE THREAD

**Issue by a52391634** [ophub/amlogic-s9xxx-armbian#464]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

在打开 ISSUE 之前，请确保您已阅读 Armbian 固件说明和文档
描述 Bug
对 Bug 内容的清晰简洁的描述。

要重现
重现此问题的步骤，请执行以下操作：
好，非常感谢你的工作，我的BOX型号是tx9-pro ，主板上写有qca9377字样，DDR3L 3G+emmc 32G，lan1000,在uEnv.txt中修改你提供的meson-gxm-tx9-pro.dtb并且修改u-boot-zyxq.bin为u-boot.ext，这样操作后U盘可以进入系统，但是写入进emmc后开机显示器有背光但是没有任何内容，重新插入制作好的U盘却可以开机并进入到EMMC内部的系统 ，尝试过使用s905x-s912、p212uboot，结果都是一样开机黑屏，无法脱离USB进入系统。
转到“...”
点击“....”。
向下滚动到“....”。
查看错误
预期行为
清晰简洁地描述您预期发生的事情。

屏幕截图
如果适用，请添加屏幕截图以帮助解释您的问题。

阿姆比亚版

内核版本： [5.15]
发布：[例如果酱]
版本：[例如服务器]
设备（请填写以下信息）：

SOC： [例如 s912]
品牌： [例如 tx]
型号 [tx9-pro]
其他上下文
在此处添加有关问题的任何其他上下文。

**Comment by xcray** [comment]
这个问题我也碰到过，应该还是uboot的问题。
你最好接TTL观察一下，我的分析是u-boot.emmc加载后识别不了emmc，就会尝试从u盘加载内核，然后内核是认识emmc的，所以继续加载emmc上的rootfs。
这样启动好之后看着就像从emmc正常启动的一样，u盘拔掉也不影响系统运行。
继续寻找好用的uboot吧……

**Comment by ophub** [comment]
写标题的时候，必须是把正文全贴上才能发现这里有个帖子？
