### ISSUE TITLE
O大好，我N1刷好系统后，安装软件，碰到权限问题。

### ISSUE THREAD

**Issue by fireworksdancewindsing** [ophub/amlogic-s9xxx-armbian#465]
我在安装软件的时候，会提示有权限问题。
[ OPTIONS ] Please Input Software ID: 306
[ INFO ] Software ID: [ 306 ]
[ INFO ] Software Name: [ NPS ]
[ STEPS ] Start processing software: [ install NPS ]...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins

然后我搜了ISSUES里边的答案，说要用ROOT用户什么的。然后我输入SUDO -I是这样显示的。
root@armbian:~# sudo -i
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins

执行 cat /etc/ophub-release这个命令是这样的。
root@armbian:~# cat /etc/ophub-release
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
KERNEL_VERSION='5.15.58'
PACKAGED_DATE='2022-07-30'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
UBOOT_OVERLOAD='u-boot-n1.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905d'
K510='0'

现在不知道要怎么办……
谢谢。

**Comment by fireworksdancewindsing** [comment]
我就是一开始的时候。提示更新密码吖什么的。用户都是默认的，没有添加过新用户。也没有设置过用户权限什么的。

**Comment by fireworksdancewindsing** [comment]
搜了论坛上，说是U盘被安卓系统污染。我确实写好U盘以后插到电视盒子里了。我再重刷一下试试。

**Comment by fireworksdancewindsing** [comment]
重刷后可以了……

**Comment by ophub** [comment]
好的

**Comment by sesame-foxes** [comment]
chown root:root / -R
这个命令执行一下就好了

**Comment by moli765** [comment]
随便搜了个命令，执行后就不报错了chown -R root /usr/lib/sudo
仅供参考
