### ISSUE TITLE
pl2303 module

### ISSUE THREAD

**Issue by uroh** [ophub/amlogic-s9xxx-armbian#469]
Hello,
I have a problem with the pl2303 module (Usb to Serial Cable adapter) and the kernel 5.4. The module is loaded however it does not detect any devices (X96 max plus 4/64).
In another box (orange pi pc plus) with armbian buster, the module correctly identifies the device. What could be the problem?
![immagine](https://user-images.githubusercontent.com/46243951/183284672-321bf57e-2184-4fd2-b9e8-2d8b94df02de.png)

**Comment by ophub** [comment]
You try other branches of the kernel, such as `armbian-update 5.15.59`
