### ISSUE TITLE
missing environment variable bootfile

### ISSUE THREAD

**Issue by tomjtoth** [ophub/amlogic-s9xxx-armbian#470]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
1st boot stuck, probably missing microSD preparation steps, about 2 months ago I successfully booted up jammy with the newer kernel. I cannot boot either Bullseye/Jammy no matter which kernel I try, I get the same messages on 1st boot

**To Reproduce**
1. burn the image to the microSD
2. mount the image, set `FDT=/dtb/amlogic/meson-gxm-q201.dtb` in `uEnv.txt`
3. copy `u-boot-s905x-s912.bin` as `u-boot.ext`
 **a. and this is where I remember having +1 step a few months ago, having to do something with u-boot.sd**
 **b. I also remember something about usb and quirks and having to look up IDs from approx. `lsusb`**
4. I unmount the microSD safely, insert it into KM8 P
5. connect ethernet, HDMI
6. boot it up and see the errors

**Expected behavior**
boot to login prompt

**Screenshots**
![2022-08-07-191814_selection](https://user-images.githubusercontent.com/49162364/183301838-ce9b5a26-9480-4883-99a5-1e4b31dc3c3e.png)

**Armbian Version**
 - Kernel Version: 5.15.58, 5.15.59
 - Release: jammy, bullseye
 - Edition: server

**Device:**
 - SOC: S912
 - Brand: Mecool
 - Model: KM8 P 1G/8G

**Comment by tomjtoth** [comment]
on the other hand when booting without ethernet plugged in I had time to capture the beginning of the output:
![image](https://user-images.githubusercontent.com/49162364/183306004-4690253f-1552-4d89-87fd-9c68f277c367.png)

`# Error inserting "stdin" variable, errno=22`
...
`"bootfromsd" not defined`

will retry booting from a USB stick

**Comment by tomjtoth** [comment]
using a USB stick I get to this point, after the countdown the box reboots and I get back to the same countdown screen. Attaching the ethernet cable does not make a difference.
![image](https://user-images.githubusercontent.com/49162364/183307577-377eefec-e1ed-41fe-971f-50fa0c6ca99c.png)

**Comment by tomjtoth** [comment]
I think the missing step was appending something on the `APPEND=...` line

**Comment by ophub** [comment]
![Snip20220808_2](https://user-images.githubusercontent.com/68696949/183336359-c6b00aa1-40b9-4bb4-9b7c-4784bc642068.png)

![Snip20220808_3](https://user-images.githubusercontent.com/68696949/183336371-91e8d940-104c-42b5-96c4-a5788b516f24.png)

s912-m8s-pro-l has generated firmware, you use USB to test, do not use SD card

**Comment by tomjtoth** [comment]
I tried `Armbian_22.08.0_Aml_s912-m8s_jammy_5.15.59_server_2022.08.07` via both USB and microSD. USB seems to be more unstable, I was using microSD 2 months ago, too.

via USB the box reboots after this screen and the process repeats forever:
![2022-08-08-202601_selection](https://user-images.githubusercontent.com/49162364/183477806-13cf5552-019d-46d4-94e3-ec33ded7fc58.png)

via microSD I get the same behavior as with the non m8s-specific image:
- before I connect the ethernet:
![2022-08-08-203221_selection](https://user-images.githubusercontent.com/49162364/183478733-ed1e1a09-9964-4432-83a2-5cc61676f80d.png)

- and after I connect ethernet:
![2022-08-08-203332_selection](https://user-images.githubusercontent.com/49162364/183478764-67619ce0-9461-4a2e-bca0-854e48290361.png)

What are the USB/microSD preparation steps exactly? It seems copying the `u-boot.ext` is also missing currently from the [instructions page](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md).

**Comment by ophub** [comment]
The 5.4/5.15 kernel does not need u-boot.ext/.emmc, and the scripts are automatically installed for other kernels.
I found that this introduction has misunderstood many people, and some tutorials also directly teach you to change your name.
First of all, don't change the name. If you change the name, there will be no such file. After updating other kernels such as 5.10/5.18/5.19, it will not be available due to lack of files.
In addition, for unknown devices, copying may lead to failure to start.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/158

**Comment by tomjtoth** [comment]
Without creating the `u-boot.ext` it boots now, I did:
- `dd if=Armbian_22.08.0_Aml_s912_jammy_5.15.59_server_2022.08.07.img of=/dev/sda`
- set `FDT=/dtb/amlogic/meson-gxm-q201.dtb` in `uEnv.txt`
- unmount microSD from the laptop, insert into KM8 P and power it on
- boot process stops at login prompt (wants new pw for root)
- is unreachable via ethernet

And with the suggested m8s image:
- `dd if=Armbian_22.08.0_Aml_s912-m8s_jammy_5.15.59_server_2022.08.07.img of=/dev/sda`
- insert microSD into KM8 P and power it on
- boot process stops at login prompt (wants new pw for root)
- TV box is reachable via ethernet

Thank you very much!

**Comment by ophub** [comment]
Yes, the firmware with `s912-m8s` in the name is your dedicated firmware, you can use it without changing anything

**Comment by ISeeCan** [comment]
> Without creating the `u-boot.ext` it boots now, I did:
> 
> * `dd if=Armbian_22.08.0_Aml_s912_jammy_5.15.59_server_2022.08.07.img of=/dev/sda`
> * set `FDT=/dtb/amlogic/meson-gxm-q201.dtb` in `uEnv.txt`
> * unmount microSD from the laptop, insert into KM8 P and power it on
> * boot process stops at login prompt (wants new pw for root)
> * is unreachable via ethernet
> 
> And with the suggested m8s image:
> 
> * `dd if=Armbian_22.08.0_Aml_s912-m8s_jammy_5.15.59_server_2022.08.07.img of=/dev/sda`
> * insert microSD into KM8 P and power it on
> * boot process stops at login prompt (wants new pw for root)
> * TV box is reachable via ethernet
> 
> Thank you very much!

It works for me and solved my problem after days' of searching! I don't know why it works but it just works.
