### ISSUE TITLE
搞定了一个M401A盒子（使用u200.dtb）和一个311-1a yst (yss) 盒子（使用e900v22c.dtb）的蓝牙，RTL8761BTV芯片，uart界面

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#471]
https://bbs.hassbian.com/thread-17392-1-1.html
简单说：
1. 删掉固件目录里那个config文件
2. 使用我自己修改过的u201.dtb

311-1a yst (yss) 是另一位网友的，使用e900v22c.dtb，蓝牙和我用的M401A一样，解决方法也一样。

**Comment by ophub** [comment]
上传分享一下你的dts，贴一下添加的代码部分。

蓝牙开启后，无线可以使用吗？

**Comment by xcray** [comment]
好的，大部分内容我上一个issue里都有了，这次的改动如下：
 - /etc/amlogic_model_database.conf增加一行：
`305:M401A:s905l3a:meson-g12a-u201.dtb:u-boot-e900v22c.bin:/lib/u-boot/u200-u-boot.bin.sd.bin:NA`
 - dtb、u-boot文件按需拷贝并改名；
 - 每次重启必须先关机断电然后再重新加电，否则蓝牙起不来。
 - 启动后执行：
 `rtk_hciattach -n -s 115200 ttyAML1 rtk_h5 &`
 可以添加到/etc/rc.local里

这是dts/dtb和rtk_hciattach文件：
[meson-g12a-u201.dtbdts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9278194/meson-g12a-u201.dtbdts.zip)
[rtk_hciattach.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9278195/rtk_hciattach.zip)

**Comment by ophub** [comment]
你的dtb是反编译的吧

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-u200.dts

这个是dts的源文件，你在标准文件上修改，可以随内核编译使用。

**Comment by xcray** [comment]
> 你的dtb是反编译的吧
> 
> https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-u200.dts
> 
> 这个是dts的源文件，你在标准文件上修改，可以随内核编译使用。

是的，反编译在本地只需要操作一个文件，简单能理解。

直接在github上修改源码还不会。。。

**Comment by ophub** [comment]
你反编译是改了一个什么值？

**Comment by xcray** [comment]
> 
aliases里添加了一行：
`	aliases {
		serial1 = "/soc/bus@ffd00000/serial@24000";
	};`
serial@24000里的status由“disabled”改成“okay”。

其它受芯片config下载失败问题误导试了几版，应该都没啥关系。

**Comment by xcray** [comment]
今天帮一个网友成功启用了e900v22c的蓝牙，方法一样，也是反编译dtb编辑dts打开串口再编译回去。因为他的盒子蓝牙同样是uart接口的，也是同一个串口，serial@ffd24000。我估计所有蓝牙采用串口的盒子都可以用这个方法把蓝牙用起来。

**Comment by ophub** [comment]
https://github.com/ophub/linux-5.15.y/commit/8559e5b949e84553f3208fafedf0c90dd4f171d6

https://github.com/ophub/amlogic-s9xxx-armbian/issues/476

像这个明确就很好添加蓝牙，你这个的原始代码是什么呢？有同型号的其他dtb可以参照下吗？

**Comment by xcray** [comment]
> 

我上面几个comment已经交待了，您可能事多给忘了，再返回去看看？关键就是uaert_A默认是disabled（在那个g12-common里），修改dts把它打开就行了。也看过其它几个dts文件，realtek芯片需要自己的rtk_hciattach程序attach一下，其它芯片好像直接在dts里加上就行。
