### ISSUE TITLE
make编译不可用

### ISSUE THREAD

**Issue by lemongad** [ophub/amlogic-s9xxx-armbian#472]
提示:no rule to make target modules

**Comment by lemongad** [comment]
5.10.y内核 创维22c盒子

**Comment by lemongad** [comment]
安装rtl8188gu网卡驱动

**Comment by ophub** [comment]
`make munuconfig`
这是显示选择面板的命令

**Comment by lemongad** [comment]
同样提示没有规则

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/stable/5.10.135

我发现header压缩包缺文件，今天试了一下deb包比较全，你试一下
```
armbian-sync
armbian-update 5.10.135
```
先同步一下最新脚本，再更新5.10.135试一下，会安装完整的header文件

如果你使用的其他内核你在线编一下，下载安装测试一下
