### ISSUE TITLE
请问如何不开机启动desktop

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#473]
而是在有需要的时候，通过shell来启动

**Comment by ophub** [comment]
永久关闭
sudo systemctl set-default multi-user.target

永久开启
sudo systemctl set-default graphical.target

临时关闭
sudo service lightdm stop

临时开启
sudo service lightdm start

**Comment by Shiyang-Wang** [comment]
> 永久关闭 sudo systemctl set-default multi-user.target
> 
> 永久开启 sudo systemctl set-default graphical.target
> 
> 临时关闭 sudo service lightdm stop
> 
> 临时开启 sudo service lightdm start

大佬，开机获取不到ip的bug有进展了吗（哭笑）

**Comment by ophub** [comment]
我没遇到过开机没ip的时候

**Comment by jsdfhasuh** [comment]
> 永久关闭 sudo systemctl set-default multi-user.target
> 
> 永久开启 sudo systemctl set-default graphical.target
> 
> 临时关闭 sudo service lightdm stop
> 
> 临时开启 sudo service lightdm start

应该是service gdm3 start，lightdm 安装了启动不了

**Comment by jsdfhasuh** [comment]
lightdm 我安装了启动不了，只能用gdm3

**Comment by ophub** [comment]
安装时有两个选择，根据你选的设置

**Comment by Shiyang-Wang** [comment]
经过大量人测试CM311-1(s905l3a)确实大量存在开机无法过去ip的现象，请问大佬用的那个img?



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ophub ***@***.***&gt;
发送时间: 2022年8月8日 23:03
收件人: ophub/amlogic-s9xxx-armbian ***@***.***&gt;
抄送: Shiyang-Wang ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [ophub/amlogic-s9xxx-armbian] 请问如何不开机启动desktop (Issue #473)





 
我没遇到过开机没ip的时候

**Comment by ophub** [comment]
CM311-1(s905l3a)你看一下别人的贴子吧，有人换u200的dtb使用

**Comment by xcray** [comment]
> 经过大量人测试CM311-1(s905l3a)确实大量存在开机无法过去ip的现象，请问大佬用的那个img? 发自我的iPhone
> […](#)

莫非也是用的e900v22c的u-boot？写入bootloader了吗？内核版本？
看看我之前开的issue，也许有参考作用

**Comment by ophub** [comment]
xcray是个探索者，尝试了很多方案，你可以试试他的dtb和使用方法
