### ISSUE TITLE
有大佬尝试过耳机接口，能不能正常使用吗

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#474]
视频能正常播放，将音响插入到音频接口，但是没反应

**Comment by ophub** [comment]
我在gtk-pro和tx3上使用苹果蓝牙耳机听歌。你是什么盒子

**Comment by jsdfhasuh** [comment]
> 我在gtk-pro和tx3上使用苹果蓝牙耳机听歌。你是什么盒子
有线应该也要装驱动吧
蓝牙安装了驱动就正常了，我的蓝牙鼠标和蓝牙键盘都能正常使用。
设备:ugoos am6b plus

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12b-ugoos-am6b-plus.dts

这是ugoos-am6b-plus的dts文件，一般来说有驱动，而且dts里定义了输入输出，就可以使用。

**Comment by jsdfhasuh** [comment]
> https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12b-ugoos-am6b-plus.dts
> 
> 这是ugoos-am6b-plus的dts文件，有声音的定义。一般来说有驱动，而且dts里定义了输入输出，就可以使用。

不知道在哪里下手，HDMI也没有声音
