### ISSUE TITLE
o大，能否增加个编译dts的action？每次测试dts都要编译内核，费时间、也费github的资源哈

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#475]
对dts好像有了点感觉，试着编译了两边，管用。

但是每次有新的想法，编辑linux内核里的dts之后，回到armbian的actions里，只能重新编译一遍内核，时间至少一个多小时。。。

能否增加一个编译dts的action？单独编译dts的话，估计也就是几秒钟的事情

**Comment by ophub** [comment]
刚更新了，支持仅编译dtbs文件，通过-p参数指定： `-p dtbs`

默认值为 `all` ，将编译 `Image, modules, dtbs` 的全部文件。当设置值为 `dtbs` 时仅编译 3 个 dtbs 文件。

**Comment by xcray** [comment]
感谢大佬！这样方便多了
