### ISSUE TITLE
[Suggestion] deleting apt cache on armbian-fix

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#479]
Dear @ophub,

I wanted to giving some suggestion to adding apt cache deleter on armbian-fix script

All the script have to do it's just

```
rm -rf /var/cache/apt/*
rm -rf /var/lib/apt/*
```

Because i had issues that when i wanted to apt-get update, there is issue

```
E: Release file for http://security.debian.org/dists/bullseye-security/InRelease is expired (invalid since 34d 15h 3min 7s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/bullseye-updates/InRelease is expired (invalid since 34d 7h 38min 14s). Updates for this repository will not be applied.
E: Release file for http://deb.debian.org/debian/dists/bullseye-backports/InRelease is expired (invalid since 34d 7h 38min 15s). Updates for this repository will not be applied.
```

But, after deleting the `/var/cache/apt/*` and `/var/lib/apt/*` the issue is solved

![image](https://user-images.githubusercontent.com/33513626/184284824-c2c3bdf0-1835-4a23-9adc-a8c65d2da84d.png)

Thanks

**Comment by ophub** [comment]
Use the `sudo apt-get clean` command to clean these locally installed packages

**Comment by rapdodge** [comment]
> Use the `sudo apt-get clean` command to clean these locally installed packages

I did, but has no effect... I don't know why...

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/cb07a10c71fa9f0bde3cb3626a9bf525812b3f98

Use the `armbian-sync` command to update local scripts synchronously

**Comment by rapdodge** [comment]
Thank you :)
