### ISSUE TITLE
希望有debian11的n1 armbian

### ISSUE THREAD

**Issue by 5158py** [ophub/amlogic-s9xxx-armbian#48]
有些系统要求比较高

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#use-github-action-to-build

New compilation: Select Build armbian on the Action page, According to the OS version officially supported by Armbian, In RELEASE, you can choose Ubuntu series: `bionic / focal / hirsute`, or Debian series: `bullseye / buster / stretch`, and in BOARD, you can choose lepotato / odroidn2, etc., Click the Run workflow button.
