### ISSUE TITLE
s905x4 stuck on loading kernel

### ISSUE THREAD

**Issue by alealexpro100** [ophub/amlogic-s9xxx-armbian#480]
Does not boot on Vontar X4 (s905x4).
Used image for s905x3 with both kernel versions. Tried various dtb files including `meson-sm1-sei610.dtb`.
According to [uboot.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9315627/uboot.txt) log (grabbed via UART) it stucks on kernel boot.

**Comment by ophub** [comment]
The mainline kernel currently does not support the s905x4 fully, and currently there are only a few firmwares that can use the s905x3, but they are very unstable.
