### ISSUE TITLE
关于“主线 mainline”概念的混乱理解和疑惑，请大佬帮忙澄清

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#481]
前段时间反复折腾刷机，一次次的失败，事后反思，很大程度上是因为对“主线”概念的不正确理解导致的。这几天网上搜了搜，有些收获，但仍无法完全消除疑惑：

对于内核：
 - 可能1：当前版本叫主线，其它版本叫stable、longterm等，prepatch（RC）是没有正式发行的主线。
   主线由Linus Torvalds维护。https://www.kernel.org/category/releases.html 这里是这么说的，应该是很权威了。
 - 可能2：kernel.org官方的叫主线，其它如厂家、网友非官方自己搞的为非主线。猜测，好像有人这么分。
 - 可能3：5.10+为主线（不含5.15）；低于5.10的以及5.15为非主线。

对于U-boot：
 - 可能1：也是按版本分：
     1.1 按是否支持5.10+内核划分：主线支持5.10+内核，非主线（旧版）不支持5.10+内核；
         armbian里说明也有部分内容符合这一点。
     1.2 和内核可能1一样，当前版本叫主线，其它都是非主线；
 - 可能2：能写入emmc的bootloader区域（dd命令1x444+512xN）、可开机由cpu加载运行的叫主线，
          存放在U盘或emmc的boot分区文件系统内的u-boot.ext/u-boot.emmc为“非主线”，又叫overload；
          armbian-install脚本以及/etc/amlogic_model_database.conf是这么分的；
 - 两种划分方法并不严格统一：
   - 比如u200和e900v22c的“非主线”（overload）u-boot改名为u-boot.ext/u-boot.emmc也可以引导5.10+内核，
   - u-200的“非主线”（overload）u-boot也可以用dd命令写入bootloader区域并正常引导，
   - 使用5.9/5.15内核时也可以额外复制u-boot.ext/u-boot.emmc文件，并且有正确识别网卡内存的好处。
 - 《e900v22c教程汇总v1.0.2》中使用“完整版主线u-boot”和“不完整版主线u-boot”的叫法，都是主线。
   - 前者包含初始化设备内存代码、可开机后直接由CPU加载运行，后者则相反。
   - 此外该文档中又说到主线u-boot仅能引导启动4.16+内核（怀疑是5.10+之误）。
 - 如果统一一下理解：
  armbian-install脚本以及说明里的“UBOOT_OVERLOAD”对应教程里的“不完整版主线u-boot”，就是u-boot.ext/u-boot.emmc；
        脚本以及说明里的“MAINLINE_UBOOT”对应教程里的“完整版主线u-boot”、就是存放在/lib/u-boot目录、用dd命令写入emmc的开头bootloader区域的那个文件？？

实践结果：
 - 脚本加no的情况下：
   使用5.10+内核会默认拷贝u-boot.ext/u-boot.emmc（Overload），而5.9/5.15版本内核则默认不拷贝这个文件。
   5.9/5.15版本不使用overload，由原旧版u-boot或主线u-boot直接引导内核，存在不识别网卡及全部内存的问题。
   也可以手动复制该文件强制overload予以解决。
 - 脚本不加no且/lib/u-boot目录存在完整版主线u-boot文件（哪怕是非完整版冒充的）的情况下：
   默认不再需要u-boot.ext/u-boot.emmc（Overload）？
   而我在M401A盒子上试验的结果是u200的u-boot充当“完整版主线u-boot”用dd写入bootloader区域 + e900v22c的uboot_overload复制改名为u-boot.emmc 是最佳组合，没有网卡内存识别错误问题，大多数时候也可以自动获得IP地址。

**Comment by ophub** [comment]
由于我是外行，我对这些专业术语的解释并不专业，为了回答你的问题我专门去请教了f大，但是转述中可能存在解读偏差，有我表述有误的方面请更正，也欢迎大家讨论。

1. 主线内核的范畴

由由Linus Torvalds维护发布的，在kernel.org上公布的内核都叫主线内核。包括stable、longterm等，不仅限于当前的最新版本被标记为 mainline 的一个内核。

大家一般把打过补丁，但是偏离较小的版本也统称为主线内核的范畴。

与之对应的非主线内核是安卓内核，这种由不同厂家做了深度定制，偏离主线较多的，一般叫非主线内核。

以上是大家一般的界定和习惯性叫法，不严谨但比较通用，比如大家在添加目前主线中没有的硬件驱动的时候，网上找到的资料一看是安卓的就放弃了，往使用主线内核的armbian里移植了差异较大。

2. U-BOOT的定义

bootloader分with_fip和without_fip，其中with_fip是bootloader的第1部分，大约是BL2+BL31+BL32；而without_fip的算是第2部分，without_fip是BL33，属于最后一步。

用主线uboot源码编译出来的只是bl33.bin，用来替换原厂的bl33.bin，所有arm的uboot都是这种模式。

由于早前刚创建仓库的时候，我在命令行里切换with_fip和without_fip目录的时候不方便，为了快速输入我就把bootloader下的这两个目录重命名为bootloader和overload了，这个目录名称不够严谨可能造成了你的困惑。

**Comment by xcray** [comment]
感谢o大！好像更明白了一些，我再仔细学习试着慢慢消化消化
