### ISSUE TITLE
How install armbian to emmc X96max+ 4/64 eth1000

### ISSUE THREAD

**Issue by eonegin83** [ophub/amlogic-s9xxx-armbian#486]
Armbian_22.08.0 5.10 and 5.15 set-top box starts only from SD card, starting from emmc no ping
stmmac_open: Cannot atach to PHY error 22

**Comment by eonegin83** [comment]
![photo_5456205975167024847_y](https://user-images.githubusercontent.com/85644681/184472596-80c5e61e-0433-448f-aa64-12ef5e6df313.jpg)
#

**Comment by eonegin83** [comment]
![photo_5456205975167024846_y](https://user-images.githubusercontent.com/85644681/184472718-073fa6fa-8653-4721-89a9-5321b4309c8a.jpg)

**Comment by eonegin83** [comment]
how to install armbian to emmc

**Comment by eonegin83** [comment]
Please Input ID: 503
Input Box ID: [ 503 ]
FDTFILE: [ meson-sm1-x96-max-plus-ip1001m.dtb ]
UBOOT_OVERLOAD: [ u-boot-x96maxplus.bin ]
K510: [ 0 ]
--------------------------------------------
Please select the type of file system:
1. ext4
2. btrfs
--------------------------------------------
Please Input ID: 1
Input Type ID: [ 1 ]
The type of file system: [ ext4 ]

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/common-files/bootfs/dtb/amlogic

![Snip20220813_1](https://user-images.githubusercontent.com/68696949/184475180-d2bfa439-600c-4172-b0d8-c83e1592d3e0.png)

What is your network card chip, choose the correct dtb according to your own chip

**Comment by ophub** [comment]
try 501

**Comment by eonegin83** [comment]
ok, one moment ethernet 1000 mb/s

**Comment by eonegin83** [comment]
its ok, working, Thanks

**Comment by eonegin83** [comment]
Sorry, reboot and error
![photo_5456205975167024907_y (1)](https://user-images.githubusercontent.com/85644681/184476557-3f55aa40-b762-494f-a92c-8a1465def300.jpg)
