### ISSUE TITLE
Tanix TX3 only 2gb of ram

### ISSUE THREAD

**Issue by jovanradin** [ophub/amlogic-s9xxx-armbian#487]
With meson-sm1-tx3-bz.dtb device is working perfectly (wifi, gnome, wayland) but Armbian does not see more than 2gb of ram.

I extracted dtb from android with dd if=/dev/dtb ... if this can help link for file is:

https://drive.google.com/file/d/1JXKED_L6W5kaYCSBrdnb9QcOx-LVHz6U/view?usp=sharing

**Comment by ophub** [comment]
What firmware, what kernel. How much memory does your box have. Is your gigabit NIC or 100M?


cat /etc/ophub-release

**Comment by jovanradin** [comment]
My box has 4gb of ram.

It is 100mb version, with DTB for 1gb ethernet box does not boot.

VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FDTFILE='meson-sm1-x96-max-plus-100m.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
ANDROID_UBOOT='/usr/lib/u-boot/hk1box-bootloader.img'
KERNEL_VERSION='5.15.60'
SOC='s905x3'
K510='0'
PACKAGED_DATE='2022-08-12'

cat uEnv.txt 
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-tx3-bz.dtb
APPEND=root=UUID=a8f04c61-ff18-401c-b4de-124c30ffd658 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/04c40369eb705d398e74f0901b4e91b8ce7678ca/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L70

**Comment by ophub** [comment]
```
cd /boot
cp -f u-boot-tx3-bz.bin u-boot.ext
cp -f u-boot-tx3-bz.bin u-boot.emmc
sync
reboot
```

Are you using emmc or usb? Make a copy of u-boot and try restarting

**Comment by jovanradin** [comment]
Thanks, it is ok now.

It can be installed on internal emmc with correct **u-boot.emmc**?

One offtopic question, is any browser/package which support libwidevinecdm0?

**Comment by ophub** [comment]
`armbian-install`
select `514`

**Comment by ophub** [comment]
The use of software packages is basically the same as Ubuntu/debian, you can install and test by yourself.
