### ISSUE TITLE
cm311-1a yst(s905l3a)蓝牙不可用

### ISSUE THREAD

**Issue by tonywang1201** [ophub/amlogic-s9xxx-armbian#488]
cm311-1a yst(s905l3a)蓝牙不可用

使用的固件是Armbian_22.08.0_5.15.60，我在armbian-config中安装了蓝牙驱动，
重启后使用**bluetoothctl**一直显示“waiting to connect to bluetoothd”；
输入**hcitool dev**显示“Devices:”；
输入**hcitool scan**显示“Device is not available: No such device”

很感谢能使用这个很棒的开源项目，不知道有没有人使用同款的盒子，希望能有人解答一下这个问题。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/471

看看这个帖子
