### ISSUE TITLE
Cant boot sdcard/restoring android after installing to emmc

### ISSUE THREAD

**Issue by SeaSon2002** [ophub/amlogic-s9xxx-armbian#49]
I tried both sdcard with armbian/stock android firmware

Restoring original android firmware using usb burning tool

Nothing work, system boot straight into armbian on emmc

**Comment by ophub** [comment]
I didn't understand what you mean. You are asking how to start the armbian system from tf/usb?

**Comment by SeaSon2002** [comment]
no, i meant i cant restore android/ reinstall armbian 
sd card wont boot

**Comment by ophub** [comment]
Can't understand your question. What system is it now? What system are you going to install? What box?

**Comment by SeaSon2002** [comment]
> Can't understand your question.
> 
> 1. What system is it now?
> 2. What system are you going to install?
> 3. What box?

1. it is running armbian ( installed on emmc)
2. im trying to install android  OR re-install armbian
3. h96 max x3

**Comment by SeaSon2002** [comment]
![first half](https://user-images.githubusercontent.com/61407079/145381142-dcbc0a52-51b5-4559-b513-07377f65b4cd.jpg)
![second half](https://user-images.githubusercontent.com/61407079/145381129-3ee728f1-c824-4d66-a26f-948fc150ed43.jpg)

Here is the boot log

**Comment by ophub** [comment]
1. The https://rufus.ie/ tool must be used to rewrite the usb disk. It cannot be other tools.
2. Choose 5.4 armbian
3. Unzip to .img format
4. Rewrite emmc after booting from usb normally: `armbian-install`

**Comment by SeaSon2002** [comment]
doesnt work
it doesnt boot to usb/tf card

**Comment by ophub** [comment]
Send a screenshot of the four steps I mentioned and the process of your operation.

**Comment by SeaSon2002** [comment]
i unzip the .gz file to get .img file
![image](https://user-images.githubusercontent.com/61407079/145385002-611cc5f4-48d7-49d4-a448-e63ae4a0a4d0.png)

i write the img to my sd card
![image](https://user-images.githubusercontent.com/61407079/145385259-9cb1a788-3acd-4984-8098-9749fac983e7.png)

the box only have sd card and power supply attached

i turn the box on and it doesnt boot the sdcard, it boot emmc

**Comment by SeaSon2002** [comment]
yes i did plug the hdmi cable in after 2 minutes to see what happened

**Comment by ophub** [comment]
try bullseye / buster

**Comment by SeaSon2002** [comment]
update: i repeat the process with an usb stick and seems like armbian is booting from usb now

**Comment by ophub** [comment]
Congratulations.

If you have another SD card, you can try another one. It feels that there is a problem with your card or it is not inserted.

**Comment by SeaSon2002** [comment]
For some reason current bootloader doesnt like my sd card

Sd card with armbian was booting and working fine while android is present on emmc

**Comment by ophub** [comment]
The priority is set in dtb, and the usb/sd card is activated before emmc. It should be a problem with SD. You can try another card. Many people use SD/USB, so there is more space.

**Comment by SeaSon2002** [comment]
the main problem is i can not get back to android

**Comment by ophub** [comment]
use: dd

**Comment by SeaSon2002** [comment]
what does that mean

**Comment by ophub** [comment]
Put the Android firmware into the dd folder of the armbian system in the usb, and use the dd command to write the Android system into emmc.

**Comment by SeaSon2002** [comment]
it is safe to do that? isnt ddbr supposed to restore file that are generated using ddbr command itself?
i only have the img file which is used for  amlogic usb burning tool

**Comment by ophub** [comment]
After entering the system, execute the command ddbr, first enter b (backup), after the progress bar starts, you can press Ctrl+C to cancel. In this way, you can get the name of the file backed up by ddbr (the name of the package backed up by different versions of Armbian is different)

Open winscp and log in with sftp and your ssh login information, enter the /ddbr directory, you can see a file `-emmc.img.gz, copy its file name and delete the file. Upload the original Android system ddbr package to this directory. After uploading, change the file name to the file name you just copied.


Then back to PuTTY, enter the ddbr command, this time type r (restore), it will ask you whether you have used compression (DID YOU USED
COMPRESSION), select y

**Comment by SeaSon2002** [comment]
Will i have trouble with the disk space that i have?
Armbian boot from sd/usb only have 2.6gb usable no matter how big the drive is ( and half of it is used by sysyem if i remebered correctly)

**Comment by ophub** [comment]
That's right. The default is to occupy only this large.

**Comment by SeaSon2002** [comment]
do i need to restart? the disk usage is the same after running the command

**Comment by ophub** [comment]
`df -h`
screenshot

**Comment by SeaSon2002** [comment]
![Uploading IMG_20211209_194244.jpg…]()

**Comment by SeaSon2002** [comment]
What to do if i dont have the android emmc backup

**Comment by SeaSon2002** [comment]
![IMG_20211209_194244](https://user-images.githubusercontent.com/61407079/145398907-574b0f0f-89ee-402e-82a3-29f59b6da463.jpg)

**Comment by ophub** [comment]
`/dev/sd3`
This is a new partition created by your usb free space

**Comment by ophub** [comment]
Your sd is only 4G? Is there anything bigger, after creating sda3, `soft connect to /ddbr`

**Comment by SeaSon2002** [comment]
1. How do i mount /dev/sda?
2. I dont have h96 max x3 original android emmc backup, what do i do?
3. can i backup from another box which have 64gb emmc ( but only 10gb used) and restore it on 32gb emmc?
4. how can i "soft connect to /ddbr"? i can attach another external drive

**Comment by ophub** [comment]
1. Go to the `official` website of the box manufacturer to download the corresponding Android firmware
2. Find a larger `usb` to ensure that the remaining space can hold the Android firmware
3. Use the `armbian-tf` command to create an extended partition: `/dev/sda3`
4. Create a soft connection and map sda3 to `/ddbr`

**Comment by SeaSon2002** [comment]
sudo mount /dev/sda3 /ddbr
is this correct?

**Comment by ophub** [comment]
umount /dev/sda3
mount -t ext4 "/dev/sda3" "/ddbr"

**Comment by SeaSon2002** [comment]
https://www.h96tvbox.com/content/6-Firmware-upgrade
h96 max x3 is listed here, the file is a ".img" file, do i rename it to ".img.gz" ?? ( inside .img there is a big file which cant be opened)
![image](https://user-images.githubusercontent.com/61407079/145401580-149f03a6-832a-4363-afeb-77d6275786e0.png)

**Comment by ophub** [comment]
yes

**Comment by SeaSon2002** [comment]
ok, ddbr create this file

BACKUP-arm-64-emmc.img.gz

so i will rename the original firmware to BACKUP-arm-64-emmc.img.gz

**Comment by ophub** [comment]
gzip *.img , then rename

**Comment by SeaSon2002** [comment]
ok

**Comment by SeaSon2002** [comment]
it doesnt boot up anymore

**Comment by SeaSon2002** [comment]
i think it is in bootloop rn, hdmi keep turning off and on

**Comment by SeaSon2002** [comment]
nvm the box got recognized by the usb burining tool now, all good

**Comment by ophub** [comment]
Congratulations
