### ISSUE TITLE
software安装不可用

### ISSUE THREAD

**Issue by lemongad** [ophub/amlogic-s9xxx-armbian#490]
无论安装哪一个都显示这样
![Screenshot_20220814_105623_com sonelli juicessh](https://user-images.githubusercontent.com/104255899/184520607-6870df7f-4474-4064-ac63-96963ce2b0d3.png)

**Comment by ophub** [comment]
`armbian-sync`

你同步下最新脚本再试

**Comment by lemongad** [comment]
> `armbian-sync`
> 
> 你同步下最新脚本再试

提示没有命令
![Screenshot_20220814_111044_com sonelli juicessh](https://user-images.githubusercontent.com/104255899/184520875-bd314412-a1f1-4f97-be0a-1b5ec4559fd9.png)

**Comment by ophub** [comment]
`cat /etc/ophub-release`

**Comment by ophub** [comment]
```
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync
chmod +x /usr/sbin/armbian-sync
armbian-sync
```

**Comment by ophub** [comment]
![Snip20220814_1](https://user-images.githubusercontent.com/68696949/184521428-882bee4d-71c9-4aa4-9793-7927ea46bfa4.png)
![Snip20220814_2](https://user-images.githubusercontent.com/68696949/184521431-dc641edb-4e6d-4943-8c3e-270c8a864272.png)

在图中输入OpenWrt镜像的地方可以输入任意仓库的镜像，如：unifreq/openwrt-aarch64:latest
默认不输入就是ophub的，里面插件较少，你可以在这个地方输入别的仓库下载任意OpenWrt镜像

**Comment by lemongad** [comment]
> ![Snip20220814_1](https://user-images.githubusercontent.com/68696949/184521428-882bee4d-71c9-4aa4-9793-7927ea46bfa4.png) ![Snip20220814_2](https://user-images.githubusercontent.com/68696949/184521431-dc641edb-4e6d-4943-8c3e-270c8a864272.png)
> 
> 在图中输入OpenWrt镜像的地方可以输入任意仓库的镜像，如：unifreq/openwrt-aarch64:latest 默认不输入就是ophub的，里面插件较少，你可以在这个地方输入别的仓库下载任意OpenWrt镜像

请问默认的openwrt，安装成功如何启动，docker ps没有看见openwrt

**Comment by ophub** [comment]
```
#进入OpenWrt容器
docker exec -it openwrt bash

#修改OpenWrt的IP，把IP改成同网段的未使用的IP
vi /etc/config/network

#改完后保存，退出，重启
esc :wq!
reboot

#过1分钟，浏览器访问你刚才设置的OpenWrt的IP即可
```

**Comment by lemongad** [comment]
感谢大佬细致说明，麻烦你了。

**Comment by ophub** [comment]
你安装好了吧？软件中心docker安装OpenWrt时

在图中提示输入OpenWrt镜像的地方可以输入任意仓库的镜像，如：`unifreq/openwrt-aarch64:latest`
默认不输入就是ophub的，里面插件较少，你可以在这个地方输入别的仓库下载任意OpenWrt镜像

上面的安装就是一个过程，这个镜像不合适你就再运行armbian-software，然后输入118，选择r删除，重新安装其他人的镜像即可。
