### ISSUE TITLE
Increasing /boot partition

### ISSUE THREAD

**Issue by rapdodge** [ophub/amlogic-s9xxx-armbian#492]
Is there any step to increasing /boot partition?

So, after i'm installing wireguard, /boot partition is used 94%

```
root@armbian:/etc/wireguard# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            835M     0  835M   0% /dev
tmpfs           194M  5.6M  189M   3% /run
/dev/mmcblk2p2  6.3G  2.0G  4.4G  31% /
tmpfs           969M     0  969M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/zram2      951M  120K  886M   1% /var/tmp
/dev/mmcblk2p1  159M  148M   11M  94% /boot
/dev/zram1       49M  2.6M   43M   6% /var/log
tmpfs           194M     0  194M   0% /run/user/0
root@armbian:/etc/wireguard#

```

Is there any step to increasing that?

**Comment by ophub** [comment]
what?

**Comment by rapdodge** [comment]
After installing wireguard, /boot partition is used 94%, is there any step to increasing /boot partition?

**Comment by ophub** [comment]
box name

**Comment by rapdodge** [comment]
B860H | s905x

**Comment by ophub** [comment]
/boot/u-boot*
/boot/dtb/amlodic/

**Comment by rapdodge** [comment]
Alright, done

Then, is it possible to include wireguard at a later time when compiling the kernel?

Thanks

**Comment by ophub** [comment]
no

**Comment by rapdodge** [comment]
> You can compile the kernel yourself according to individual needs

It will be nice if coming along with tvboxes kernel, because main kernel of linux is including wireguard :D

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/search?q=wireguard

I took a look at the original kernel, and you can use it directly

**Comment by rapdodge** [comment]
Hmmm, weird... Why when i'm running `apt-get install wireguard` it's installing another kernel...

I have vps instances too, when i'm running the same command, it's just installing like maybe 1MB, and not installing another kernel, hmm

**Comment by ophub** [comment]
you installed the package, not the kernel

**Comment by rapdodge** [comment]
Thank you...
