### ISSUE TITLE
关于armbian固件里部分存在的权限问题

### ISSUE THREAD

**Issue by hyxdz** [ophub/amlogic-s9xxx-armbian#493]
[Armbian_22.08.0_Aml_s905l3a_jammy_5.15.60_server_2022.08.14.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_08.14.0350/Armbian_22.08.0_Aml_s905l3a_jammy_5.15.60_server_2022.08.14.img.gz)
[Armbian_22.08.0_Aml_s905l3a_bullseye_5.15.60_server_2022.08.14.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_08.14.0417/Armbian_22.08.0_Aml_s905l3a_bullseye_5.15.60_server_2022.08.14.img.gz)

用的UNT403A 2+8的盒子 s905l3a芯片 刷的以上固件。

存在问题：
写入emmc后，很多文件夹和文件的用户和用户组为1023，正常情况下应为root。导致很多安装、读写操作因为权限问题无法完成。典型的例子就是写入emmc后，执行armbian-docker install进行docker的安装，报错如下：
root@armbian:~# armbian-docker
[ INFO ] Welcome to the docker management tool.
[ STEPS ] Initialize the docker installation environment... 
[ INFO ] VERSION_CODEID: [ debian ]
[ INFO ] VERSION_CODENAME: [ bullseye ]
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudosudo: : /etc/sudo.conf is owned by uid 1023, should be 0/etc/sudo.conf is owned by uid 1023, should be 0

sudosudo: : /etc/sudo.conf is owned by uid 1023, should be 0/etc/sudo.conf is owned by uid 1023, should be 0

sudosudo: : error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"

sudosudo: : /usr/lib/sudo/sudoers.so must be owned by uid 0/usr/lib/sudo/sudoers.so must be owned by uid 0

sudosudo: : fatal error, unable to load pluginsfatal error, unable to load plugins

sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ STEPS ] Install docker related packages...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ STEPS ] Install docker accelerator...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: error in /etc/sudo.conf, line 0 while loading plugin "sudoers_policy"
sudo: /usr/lib/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins
[ SUCCESS ] Docker installed successfully.

这只是其中一个例子，除以上几个文件外，其他区域还有很多的用户和用户组为1023的文件夹和文件，在执行安装和运行其他程序的时候，都会报错。将相应文件夹和文件的用户和用户组设为root后，问题解决。但是后期要正常使用的话，其他程序涉及到的太多，无法全部一一排查解决，手动全部文件和文件夹都设root的话，又会被禁用ssh，断开后无法再次连接。建议在编译固件时修复此bug。这问题在5.15.50的jammy和5.15.60的bullseye固件上出现，其他的版本没刷过，不清楚有没有这情况。

**Comment by ophub** [comment]
`ls /etc/sudoers -l`

截图发下

**Comment by ophub** [comment]
```
#先改root用户改下密码，可以是原来的，再输入一次
passwd root


# 先执行这2条命令修复权限
chown root:root /etc/sudoers
chmod 440 /etc/sudoers


#执行完上面的命令看下当前的权限，正确的应该是：
#-r--r----- 1 root root 669 Aug  7 13:06 /etc/sudoers
ls /etc/sudoers -l
```

**Comment by xcray** [comment]
这个权限是被安卓修改的吧？不少教程都强调在reboot update那一刻再把U盘插入，避免权限被修改。不过我好像没碰到过这个问题。可能跟原有的安卓固件有关系？

**Comment by ophub** [comment]
你执行了上面的命令可以修复这个权限吧？

你的这个是第一个反馈的，我刚才加入自动修复里面了。

**Comment by hyxdz** [comment]
这文件我自己已经改过权限回来了，目前是这样的
root@armbian:~# ls /etc/sudoers -l
-r--r----- 1 root root 669 Aug 14 16:11 /etc/sudoers
但是光这样还是不够的，其他的文件夹和文件仍然是1023，运行有些程序还是会报错，有日志或者反馈的倒还好，可以逐一改权限，没有日志和反馈的就麻烦了，都不知道该改哪。

**Comment by hyxdz** [comment]
> 这个权限是被安卓修改的吧？不少教程都强调在reboot update那一刻再把U盘插入，避免权限被修改。不过我好像没碰到过这个问题。可能跟原有的安卓固件有关系？

有可能...我安卓没重启就插U盘上去了

**Comment by hyxdz** [comment]
这命令是可以修复的。我是用winscp改的，效果是一样的。密码在U盘启动进系统的时候就改了，写emmc重启以后，我又改了一次。

> 你执行了上面的命令可以修复这个权限吧？
> 
> 你的这个是第一个反馈的，我刚才加入自动修复里面了。
> 
> 系统盘一般不要插入别的系统，特别是sd卡，移动硬盘，经常被别的系统改的无法识别

**Comment by ophub** [comment]
好的，如果安装的应用不多，可以考虑重刷，但是也可以继续，解决问题的过程就是成长，这些问题的解决过程也能增加知识，armbian（linux）有高度的自主性，执腾（问题）就是快乐（成就）

**Comment by hyxdz** [comment]
> 好的，如果安装的应用不多，可以考虑重刷，但是也可以继续，解决问题的过程就是成长，这些问题的解决过程也能增加知识，armbian（linux）有高度的自主性，执腾（问题）就是快乐（成就）

嗯，我重刷了，确实是被安卓改的权限，重启瞬间再插U盘就不会被安卓改权限了。只是这时间窗口有点短，试了几次才成功。能够在固件里实现权限检测和修复那是最好的，容错性更强。玩这个就是奔着折腾去的，开心就好。感谢ophub、xcray两位大佬解惑！


> 这个权限是被安卓修改的吧？不少教程都强调在reboot update那一刻再把U盘插入，避免权限被修改。不过我好像没碰到过这个问题。可能跟原有的安卓固件有关系？
