### ISSUE TITLE
关于固件选则的问题

### ISSUE THREAD

**Issue by satanxts** [ophub/amlogic-s9xxx-armbian#495]
Armbian_22.08.0_Aml_s905d_jammy_5.15.60_server_2022.08.14.img.gz
Armbian_22.08.0_Aml_s905d-ki_jammy_5.15.60_server_2022.08.14.img.gz
请问这两个固件有什么区别，后缀ki代表什么含义？
Phicomm-N1两种固件都可以使用吗？
再次感谢 ophub大佬 的辛勤付出

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#description-of-localized-packaging-parameters

s905d-ki is s912-mecool-ki-pro

n1选s905d

**Comment by satanxts** [comment]
thanks

**Comment by allonmymind** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian#description-of-localized-packaging-parameters
> 
> s905d-ki 是 s905d-mecool-ki-pro 盒子专用
> 
> n1选s905d

请问S905D2应该选哪个固件，看参数和905X2差不多，不知道选905D还是905X2

**Comment by ophub** [comment]
5.15都可以，你改/boot/uEnv.txt里面dtb的值，测试哪个可以正常使用

**Comment by wq133** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian#description-of-localized-packaging-parameters
> > s905d-ki 是 s905d-mecool-ki-pro 盒子专用
> > n1选s905d
> 
> 请问S905D2应该选哪个固件，看参数和905X2差不多，不知道选905D还是905X2

请问老哥最后有成功吗，目前看到有s950d2的盒子，准备下手，看论坛说有部分海力士存储的不行，你的是什么参数呢？用的哪个版本的包呢？
