### ISSUE TITLE
用actions编译buster疑问

### ISSUE THREAD

**Issue by piseun** [ophub/amlogic-s9xxx-armbian#496]
内核只能选5.15可以编译成功 选择5.18和5.19都会失败是因为eol了吗

**Comment by ophub** [comment]
https://github.com/armbian/build/blob/master/config/targets.conf

从上游官方的编译目标来看，buster巳经不够官方支持

**Comment by ophub** [comment]
官方只提供最新的版本。
u-boot重载，启动的时候会有两次分配ip，间隔10秒左右，第二次拿到的ip是稳定的
