### ISSUE TITLE
snapd is broken

### ISSUE THREAD

**Issue by jovanradin** [ophub/amlogic-s9xxx-armbian#497]
Snapd is not working, even if app is installed correctly it can't be started.

example error:
cannot perform operation: umount --no-follow /var/lib/snapd/hostfs//tmp/snap.rootfs_a2WvqD: Invalid argument

tested with apparmor and selinux (different error, but wasn't able to start or even install any app)

Tested app: viber-mtd, chromium-browser (arm64 and armhf), mir-kiosk-kodi

armbian-relese

BOARD=odroidn2
BOARD_NAME="Aml s905x3"
BOARDFAMILY=meson-g12b
BUILD_REPOSITORY_URL=https://github.com/armbian/build.git
BUILD_REPOSITORY_COMMIT=4dffd6e
VERSION=22.08.0-trunk
LINUXFAMILY=meson64
ARCH=arm64
IMAGE_TYPE=stable
BOARD_TYPE=conf
INITRD_ARCH=arm64
KERNEL_IMAGE_TYPE=Image

**Comment by ophub** [comment]
Most arm64 packages do not have snap support, so install them in other ways. Generally, import the official source of related software for installation.

**Comment by yaleh** [comment]
I got the same issue. Then I tried with Ubuntu Focal, which works. So, I'm rebuilding Armbian Focal now.

**Comment by yaleh** [comment]
With a manually merged image (boot partition from this project and root partition from an Armbian Focal image, I can install snapd and lxd. Then, I customized a Focal image with the build process of this project. After install the custom image, "snap install lxd" failed again with the "umount --no-follow" command. I'm trying to figure out the root issue.

**Comment by ophub** [comment]
The current kernel already supports
https://github.com/ophub/amlogic-s9xxx-armbian/issues/511

**Comment by yaleh** [comment]
Cool. I'll try it.

**Comment by yaleh** [comment]
I did find 5.10.137 @ophub  mentioned in #511, so I installed [5.10.152](https://github.com/ophub/kernel/tree/main/pub/stable/5.10.152) instead. ```snap install lxd``` still failed with the same error message:

```
root@odroidc4:~# snap install lxd
error: cannot perform the following tasks:
- Run install hook of "lxd" snap if present (run hook "install":
-----
cmd_run.go:1046: WARNING: cannot create user data directory: failed to verify SELinux context of /root/snap: exit status 1
cannot perform operation: umount --no-follow /var/lib/snapd/hostfs//tmp/snap.rootfs_HbW8vL: Invalid argument
-----)
root@odroidc4:~# uname -a
Linux odroidc4 5.10.152-ophub #1 SMP PREEMPT Mon Oct 31 14:21:50 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by yaleh** [comment]
According to snapd source https://github.com/snapcore/snapd/blob/61b66aaa1beb861f308ea7dd75c2f0c042bf29a3/cmd/libsnap-confine-private/mount-opt.c :

```
void sc_do_umount(const char *target, int flags)
{
	char buf[10000] = { 0 };
	const char *umount_cmd = NULL;

	if (sc_is_debug_enabled()) {
#ifdef SNAP_CONFINE_DEBUG_BUILD
		umount_cmd = sc_umount_cmd(buf, sizeof(buf), target, flags);
#else
		umount_cmd = use_debug_build;
#endif
		debug("performing operation: %s", umount_cmd);
	}
	if (sc_faulty("umount", NULL) || umount2(target, flags) < 0) {
		// Save errno as ensure can clobber it.
		int saved_errno = errno;

		// Drop privileges so that we can compute our nice error message
		// without risking an attack on one of the string functions there.
		sc_privs_drop();

		// Compute the equivalent umount command.
		umount_cmd = sc_umount_cmd(buf, sizeof(buf), target, flags);
		// Restore errno and die.
		errno = saved_errno;
		die("cannot perform operation: %s", umount_cmd);
	}
}
```

```sc_umount_cmd()``` which invoked ```umount --no-follow``` was called on  ```(sc_faulty("umount", NULL) || umount2(target, flags) < 0)``` . I'm going to verify why it's triggered.

**Comment by yaleh** [comment]
In my case, the snap.rootfs was mounted at something like ```/tmp/snap.rootfs_a2WvqD``` instead of ```/var/lib/snapd/hostfs//tmp/snap.rootfs_a2WvqD```. Chances are that it's the cause of the failure.

https://github.com/snapcore/snapd/blob/7de9a575f178bbc1b9d3013177a3ef36e4b47cb5/cmd/snap-confine/mount-support.c
 mounts the folder, call pivot_root and then umount it.

```
	// Make the upcoming "put_old" directory for pivot_root private so that
	// mount events don't propagate to any peer group. In practice pivot root
	// has a number of undocumented requirements and one of them is that the
	// "put_old" directory (the second argument) cannot be shared in any way.
	sc_must_snprintf(dst, sizeof dst, "%s/%s", scratch_dir, SC_HOSTFS_DIR);
	sc_do_mount(dst, dst, NULL, MS_BIND, NULL);
	sc_do_mount("none", dst, NULL, MS_PRIVATE, NULL);
	// On classic mount the nvidia driver. Ideally this would be done in an
	// uniform way after pivot_root but this is good enough and requires less
	// code changes the nvidia code assumes it has access to the existing
	// pre-pivot filesystem.
	if (config->distro == SC_DISTRO_CLASSIC) {
		sc_mount_nvidia_driver(scratch_dir, config->base_snap_name);
	}
	// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	//                    pivot_root
	// XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	// Use pivot_root to "chroot" into the scratch directory.
	//
	// Q: Why are we using something as esoteric as pivot_root(2)?
	// A: Because this makes apparmor handling easy. Using a normal chroot
	// makes all apparmor rules conditional.  We are either running on an
	// all-snap system where this would-be chroot didn't happen and all the
	// rules see / as the root file system _OR_ we are running on top of a
	// classic distribution and this chroot has now moved all paths to
	// /tmp/snap.rootfs_*.
	//
	// Because we are using unshare(2) with CLONE_NEWNS we can essentially use
	// pivot_root just like chroot but this makes apparmor unaware of the old
	// root so everything works okay.
	//
	// HINT: If you are debugging this and are trying to see why pivot_root
	// happens to return EINVAL with any changes you may be making, please
	// consider applying
	// misc/0001-Add-printk-based-debugging-to-pivot_root.patch to your tree
	// kernel.
	debug("performing operation: pivot_root %s %s", scratch_dir, dst);
	if (syscall(SYS_pivot_root, scratch_dir, dst) < 0) {
		die("cannot perform operation: pivot_root %s %s", scratch_dir,
		    dst);
	}
	// Unmount the self-bind mount over the scratch directory created earlier
	// in the original root filesystem (which is now mounted on SC_HOSTFS_DIR).
	// This way we can remove the temporary directory we created and "clean up"
	// after ourselves nicely.
	sc_must_snprintf(dst, sizeof dst, "%s/%s", SC_HOSTFS_DIR, scratch_dir);
	sc_do_umount(dst, UMOUNT_NOFOLLOW);
```

**Comment by yaleh** [comment]
Finally, after I rebuilt quite a number of images with the rebuild script of this project and failed to execute ```snap install lxd```, I merged a image with the boot partition generated with this project and a root partition from raw Armbian (with kernel module and header folders from this project, and modified fstab), just like what I did days ago. And ```snap install lxd``` again.

So, it proved that the ```snap install``` issue was not caused by kernel image or modules, but by modifications to rootfs more likely. I'll go through the changes to rootfs and find the cause.

**Comment by yaleh** [comment]
I will try with https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/rebuild refactor_files(), which I believe related to the issue.

@ophub @jovanradin Let's reopen this bug and get it fixed.

**Comment by ophub** [comment]
ok, you are welcome to debug

**Comment by yaleh** [comment]
Fixed. See PR https://github.com/ophub/amlogic-s9xxx-armbian/pull/665.
