### ISSUE TITLE
mecool m8s pro l

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#498]
@ophub I used the img
Armbian_22.08.0_Aml_s912-m8s_jammy_5.15.60_server_2022.08.14.img.gz

and the boot from the pen does not work

i also know the img Armbian_22.08.0_Aml_s912-m8s_jammy_5.10.136_server_2022.08.14.img.gz

and the boot doesn't work, but using the img
CoreELEC-Amlogic.arm-9.0.2-Generic.img.gz
the boot works.
Can you help me or check what's going on?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/158

Device name?
MECOOL M8S PRO L

soc model?
S912

dtb name?
meson-gxm-q201.dtb

u-boot name?
u-boot-s905x-s912

support for 5.4/5.15 kernel?
yes

support for writing emmc?
yes

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#124-set-the-box-to-boot-from-usbtfsd

**Comment by ophub** [comment]
Set the box to boot from USB/TF/SD
Write the firmware to USB/TF/SD, insert it into the box after writing.
Open the developer mode: Settings → About this machine → Version number (for example: X96max plus...), click on the version number for 5 times in quick succession, See the prompt of Enable Developer Mode displayed by the system.
Turn on USB debugging: System → Advanced options → Developer options again (after entering, confirm that the status is on, and the USB debugging status in the list is also on). Enable ADB debugging.
Install ADB tools: Download [adb](https://github.com/ophub/kernel/releases/tag/tools) and unzip it, copy the three files adb.exe, AdbWinApi.dll, and AdbWinUsbApi.dll to the two files system32 and syswow64 under the directory of c://windows/ Folder, then open the cmd command panel, use adb --version command, if it is displayed, it is ready to use.
Enter the cmd command mode. Enter the adb connect 192.168.1.137 command (the ip is modified according to your box, and you can check it in the router device connected to the box), If the link is successful, it will display connected to 192.168.1.137:5555
Enter the adb shell reboot update command, the box will restart and boot from the USB/TF/SD you inserted, access the firmware IP address from a browser, or SSH to enter the firmware.

**Comment by ophub** [comment]
Open the developer mode: Settings → About this machine → Version number (for example: X96max plus...), click on the version number for 5 times in quick succession, See the prompt of Enable Developer Mode displayed by the system.

**Comment by ophub** [comment]
The firmware written in your usb was decompressed and flashed from the img file, right? Use this software: https://rufus.ie/

**Comment by ophub** [comment]
Use this software: https://rufus.ie/

**Comment by ophub** [comment]
Not universal, he is Android system

**Comment by ophub** [comment]
The first time you start the USB, you can always start from the USB. Some devices choose USB, and some people change several USBs before starting. Change the USB port, or use USB2.0

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/158

You @ him to see how it started.

**Comment by ophub** [comment]
It's not because of the kernel, you're still in Android and haven't entered armbian yet.

If it is a kernel error, the code output on the screen will have related errors instead of being stuck in the Android system

**Comment by parkjw0117** [comment]
My install method when I run into problem.
1. Install stock rom on m8s pro l.
2. Boot and install terminal.
3. Insert USB or SD card into m8s.
4. Enter 'reboot update' and after reboot, it will be boot from USB/SD card.

**Comment by ophub** [comment]
Wrong, you can't insert the armbian system disk into the Android system in advance, which will cause it to be modified and unusable.

To enter reboot update, then quickly insert usb
