### ISSUE TITLE
Magcubic W2 / AMLogic S905W2

### ISSUE THREAD

**Issue by RedFoxy** [ophub/amlogic-s9xxx-armbian#499]
Hi!
I've a Magcubic W2 with cpu AMLogic S905W2, I tryied different armbian version and Armbian_22.08.0_Aml_s905w bullseye/jammy 5.15 and 5.10, I tryied to change different .dtb in uEnv.txt but nothing, always I get or STRIPES or Magcubic static logo, I used two differend SD card and a USB pendrive, but nothing, there is a way to use S905W2 or must I wait a specific dtb?

**Comment by ophub** [comment]
The s905w2 is a new processor from amlogic (the naming choice is confusing as it has nothing to do with the s905x2). Being a new processor, support for it has not been found in mainline linux.

**Comment by RedFoxy** [comment]
Thanks for your answer!
Mainline linux? Do you mean Armbian or Debian?

**Comment by ophub** [comment]
Armbian use mainline linux kernel
