### ISSUE TITLE
can support desktop ?

### ISSUE THREAD

**Issue by fooy** [ophub/amlogic-s9xxx-armbian#50]
hi ,
i tried to build a desktop version using Armbian_21.05.1_Lepotato_focal_current_5.10.34_xfce_desktop.img.xz , the build process seems fine , i changed the ROOT_MB variable so that the image file is large enough to hold all the files copied from armbian img .  
i ended up getting a black screen after the console finish outputing all the services startup messages. 

do i need to compile a new kernel with new options for the desktop environment ?  or anything else should be done

the commands i used: 
cd build/output/images/
wget https://armbian.tnahosting.net/archive/lepotato/archive/Armbian_21.05.1_Lepotato_focal_current_5.10.34_xfce_desktop.img.xz
cd -
./rebuild -d -b s905x3_s905d -k 5.10.80 (  guess i just use the stock kernel file made by flippy)
testing box: N1

btw wonderful project , you are the legend .

**Comment by ophub** [comment]
The `kernel` is universal and can be used in all branches supported by armbian. `Including server version and desktop version`.

If you have special needs, you can use the kernel production script `recompile` in the repo for custom compilation, and the packaged kernel can be installed through the `armbian-update` function in the repo.

**Comment by fooy** [comment]
Thanks for the comment, forgot to mention i did unxz the img.xu file, maybe something wrong with the Armbian distribution ,I will test another version and try to work it out.

**Comment by fooy** [comment]
just for the record ,  it's easy to enable desktop using non-desktop released img .
 run below command and reboot 
$ sudo apt install  lxdm xfce4 xorg

**Comment by huapox** [comment]
try remote desktop(xrdp/noVNC) with docker, ref: https://github.com/ophub/amlogic-s9xxx-armbian/issues/2#issuecomment-1272825195
