### ISSUE TITLE
“1023”用户问题

### ISSUE THREAD

**Issue by dsus4wang** [ophub/amlogic-s9xxx-armbian#501]
刚安装好Armbian_22.08.0_Aml_s905l3a_bullseye_5.15.60_server_2022.08.14,发现系统日志里很多报错,包括sudo cron无法运行,原因是这些可执行文件的owner不是root.
所有的自带可执行文件都属于一个叫1023的用户
请问这个问题怎么解决呢?我目前临时用chown命令改的归属,谢谢!

**Comment by dsus4wang** [comment]
已搜到解决办法,谢谢

**Comment by satanxts** [comment]
文件权限被污染了，保险的方法是把u盘重新烧录一遍再安装

**Comment by 15518332503** [comment]
使用chown命令提示没权限

**Comment by shaobohan917** [comment]
> 已搜到解决办法,谢谢

你好，请问怎么解决的
