### ISSUE TITLE
CM311-1a(s905l3a) 5.15.61黑屏

### ISSUE THREAD

**Issue by Miaoerr** [ophub/amlogic-s9xxx-armbian#502]
- Kernel Version: 5.15.61
 - Release: Bullseye
 - Edition: server
 - SOC: s905l3a
 - Brand: 中国移动魔百盒
 - Model: CM311-1a YST

感谢ophub大佬！这段时间使用CM311-1a YST盒子刷armbian使用了一段时间，遇到一些问题，尝试解决了一下，还是有一些疑问：

1.  从安卓TV系统使用u盘刷入Armbian，u盘刷入的是（ Armbian 22.08.0-trunk Bullseye with Linux 5.15.59-flippy-75+o），直接u盘启动没有什么问题，选择304：E900V22C/D，如果使用armbian-install no刷入EMMC，**第一次重启会黑屏，需要插入u盘启动一次再重启**；如果使用armbian-install刷入EMMC，**启动需要5--30分钟时间才会启动成功**（根据led、ssh、hdmi输出判断的，大部分时候在30分钟左右），这是因为设备问题吗？还是可以通过自定义dtb等来解决一下？

2.   从u盘启动、刷入emmc都会遇到**无法连接网络获取ip的情况（有线连接）**，查看日志及**networking.service**看到有报错：**Failed to start Raise network interfaces**，重新拔插网线可以解决这个问题，这是因为设备问题还是我这边配置不对？因为上级路由器设置的DHCP静态ip每次都无法生效，需要在Armbian里面配置静态ip才可以，而且没有看到其他人遇到这个问题，是否可能是和我的路由器兼容问题？（路由器是刷的Padavan）

3.   之前写入emmc并使用了大概一个多月，从5.15.57一直到5.15.60都可以刷入或升级，最近一次是从5.15.59通过armbian-update升级到5.15.60，盒子正常启动了（仍然需要5~30分钟时间启动），但是8月18日通过armbian-update升级，看到升级的好像是**5.15.61**，这次升级之后**开机就是黑屏**，尝试多次重启仍然黑屏（需要5--30分钟时间启动，led灯亮了，然后hdmi没有输出）；后续重新刷入5.15.59使用armbian-update，仍然会黑屏无法启动；目前重新刷入并停留在5.15.59版本，正常使用中。

  
  非常感谢您的系统，您有时间麻烦帮忙看一下以上问题

**Comment by xcray** [comment]
正好这几天我也折腾过这个盒子，获取不到ip的问题挺常见的，和内核版本有直接关系。黑屏的问题也是。
建议：
不要写bootloader，保持安卓原有bootloader是最好的选择。e900v22c的完整版uboot不适合这个盒子，开机后不认内存无法启动，我没试过等5-30分钟那么久，也接受不了。
可以试试最新的5.19.2内核，很好用。
一个小窍门：emmc起不来的时候，插入U盘重新开机大概率就能起来（u盘里保留写入emmc之前的状态），有些情况下启动的是emmc里的系统，有些情况下是u盘里的系统，跟具体配置文件、内核uboot版本相关。

**Comment by ophub** [comment]
以下这两个问题是常见的，你的方法就是大家的经验，5.15.61内核我在tx3和gtk使用正常，如果你的用不了就跳过这个版本吧。对使用着比较好的某版内核，建议自己保存一下，以便有问题时替换回来。内核更新会解决己知的一些问题，但有时候也会带来问题。

- 使用armbian-install no刷入EMMC，第一次重启会黑屏，需要插入u盘启动一次再重启


- 偶有无法连接网络获取ip的情况（有线连接），查看日志及networking.service看到有报错：Failed to start Raise network interfaces，重新拔插网线可以解决这个问题

**Comment by ophub** [comment]
xcray做过不少组合的测试，你们的经验多交流交流，用着稳定的内核版本，建设你们自建一个内核仓库长期保存一些备用。
更改/usr/sbin/armbian-update文件里面内核下载仓库的地址即可

**Comment by Miaoerr** [comment]
好的 十分感谢两位，目前看来有以下几点：

1. 使用armbian-install no刷入EMMC，不写bootloader，保持安卓原有bootloader
2. 遇到emmc起不来的时候，插入U盘重新开机大概率就能起来
3. 自建内核仓库保留内核版本备用
4. 无法连接网络获取ip目前只能是重新拔插网线

之后我会试一下最新的5.19.2内核，非常感谢两位的提醒

**Comment by xcray** [comment]
我发现有的内核就没有获取不到ip的问题，比如5.19.2；有的是每次启动都拿不到

**Comment by ophub** [comment]
你用5.19.2内核，也没用/usr/lib/u-boot/e900v22c-u-boot.bin.sd.bin吗？

如果可以的话，不如把此处改为NA

**Comment by xcray** [comment]
> 你在emmc里面使用5.19.2内核，也没用/usr/lib/u-boot/e900v22c-u-boot.bin.sd.bin吗？
> 
> 如果可以的话，不如把此处改为NA
> 
> 方便把openwrt也测试一下吗？是不是都可以去掉？只留u-boot-e900v22c.bin也可以使用5.10/5.19

是的，我已经改成NA了。用了/usr/lib/u-boot/e900v22c-u-boot.bin.sd.bin写入bootloader反而起不来，ttl显示内存不认，我没有等30分钟，没那个耐心，看来一直等还是有奇迹的哈。

回头折腾一下openwrt，感觉启动方面会是大同小异

**Comment by ophub** [comment]
CM311-1a和m401a是两个不同的盒子吧？

**Comment by xcray** [comment]
> CM311-1a和m401a是两个不同的盒子吧？

是的，不同型号、两家代工厂、电路板不一样、ram和emmc芯片不一样。确定一样的只有蓝牙，都是rtl8761btv。主芯片疑似一样（话说不拆散热片的话怎么能准确区分s905x2、s905y2、s905l3a呢？）

**Comment by xcray** [comment]
这盒子用5.15.61明显不如5.15.60；5.4.210也非常可靠。
用5.19.2，因为必须有OL uboot，而OL uboot存在概率性开机不识别emmc的问题，所以综合来说，还是5.15.60/5.4.210最好

**Comment by Miaoerr** [comment]
刚试了一下5.19.2，发现死活不认网卡，重新拔插、重启都无效，networking.service显示：ethernet eth0: validation of rmii with support 000,00000000,....后面没记下来，可能还是某些硬件不太一致；
同时也尝试了5.15.61，不写bootloader也是led灯绿色，但黑屏，插上u盘会从U盘启动，但之后仍然无法从emmc启动，最后又退回了5.15.59
另外想问一下，armbian-update从本地内核文件更新的时候，无法控制不写bootloader吗？

**Comment by xcray** [comment]
> 刚试了一下5.19.2，发现死活不认网卡，重新拔插、重启都无效，networking.service显示：ethernet eth0: validation of rmii with support 000,00000000,....后面没记下来，可能还是某些硬件不太一致； 同时也尝试了5.15.61，不写bootloader也是led灯绿色，但黑屏，插上u盘会从U盘启动，但之后仍然无法从emmc启动，最后又退回了5.15.59 另外想问一下，armbian-update从本地内核文件更新的时候，无法控制不写bootloader吗？

我的经历是5.19.1死活不认网卡，5.19.2能认。而5.15.60比5.15.61好用，后者也是启动黑屏拿不到ip等问题。最后我决定先用5.15.60跑一阵子。

至于armbian-update写bootloader的问题，以前向o大反映过，他倾向于维持现状。我的做法是把/usr/sbin/armbian-update脚本中的285-293行注释掉。

另外，也可以编辑/etc/amlogic_model_database.conf文件，新增一行，如：
`306:CM311-1a:s905l3a:meson-g12a-s905l3a-e900v22e.dtb:u-boot-e900v22c.bin:NA:NA`
写emmc的时候选这一行，也可以规避覆盖BL这个风险。

还可以干脆把/lib/u-boot目录下的文件清空，反正也没啥用，白白占空间。

这3个措施同时实施也没问题。

**Comment by xcray** [comment]
我之前5.19.2一出来我就升了，用了一天感觉还不错，昨天U盘启动了一次OpenWRT，就再也起不来了——对不起我之前对它的评价啊。。。

**Comment by Miaoerr** [comment]
好的，十分感谢  准备也先停在5.15.60，的确比较合适

**Comment by janko888** [comment]
> 以下这两个问题是常见的，你的方法就是大家的经验，5.15.61内核我在tx3和gtk使用正常，如果你的用不了就跳过这个版本吧。对使用着比较好的某版内核，建议自己保存一下，以便有问题时替换回来。内核更新会解决己知的一些问题，但有时候也会带来问题。
> 
> * 使用armbian-install no刷入EMMC，第一次重启会黑屏，需要插入u盘启动一次再重启
> * 偶有无法连接网络获取ip的情况（有线连接），查看日志及networking.service看到有报错：Failed to start Raise network interfaces，重新拔插网线可以解决这个问题

我盒子用5.15.53内核，配置了静态ip,开机5次至少1到2次是网络未连上的，现在写了个开机脚本，开机时检查是否ping通得了网关，如果不能，ifdown/ifup一次，网络就可用了，暂时看起来运作良好

**Comment by ophub** [comment]
> 另外想问一下，armbian-update从本地内核文件更新的时候，无法控制不写bootloader吗？
把这个文件： `/etc/ophub-release`  里面主线值改为空： `MAINLINE_UBOOT=''`
这样`armbian-update`更新就不使用主线了

这样你不用改脚本，也能保存脚本同步更新。

**Comment by xcray** [comment]
> 

还得是o大，了如指掌啊。
顺便小建议一下：/usr/share/ophub/armbian-software/command-docker.sh 里108号HomeAssistant启动命令，是否加一个：
`-v /run/dbus:/run/dbus:ro \`
这样HA启动就可以直接使用蓝牙了。我现在是手动改，哪次同步脚本忘了重启ha就没蓝牙了。
现在盒子得蓝牙大多都用起来了，这个月的HA又新加了这个非常有潜力有价值的组件，用的人也越来越多，作为默认应该很合适了。不想在ha里使用蓝牙的话也不影响。
参考：https://www.home-assistant.io/integrations/bluetooth#additional-details-for-container-installs

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/2575dab7493a89fc81e07955de3d006100142fb1

感谢分享，已经添加了`-v /run/dbus:/run/dbus:ro \`

**Comment by ophub** [comment]
现在304现在默认设置已经取消MAINLINE_UBOOT了，以后可以不用额外添加no了

**Comment by ophub** [comment]
黑屏问题不是CM311-1A的专利，据群里反馈，N1、GTK-PRO等用户都在这个5.15.61内核上没有HDMI输出，跳过这个内核吧

**Comment by uvtofu** [comment]
> 这个盒子脾性比m401a还邪，m401上发生的问题，基本都能想明白，而这个盒子有很多不可解的现象。 黑屏但启动、黑屏且不启动、不认网卡、认网卡但拿不到IP等等非常高发（明显不如m401a），并且啥都不改的情况下，重新开机结果可能还不一样。 还有一个诡异的情况：什么都不改动的情况下，这个盒子温度较高时稳定性更好，关机凉到室温后开机不启动的概率更高。 emmc开机黑屏不启动的时候，插入带系统U盘基本上都能起来，并且起来后根系统很可能还是emmc。

我刚收货CM311-1a YST，试了几下。发现这机很挑U盘、读卡器。
我有3个不同型号的川宇读卡器和1个雷克沙的U盘。
其中两个读卡器引导Armbian时会出错，有时是完全黑屏，有时进不了rootfs，有时apt安装软件时报libc-bin错误导致安装失败。
另外一个读卡和雷克沙U盘在引导Armbian时就从来没有错误。
我之前用小米盒子4 (MDZ-21-AA)玩了一个月的Armbian，上面所有这几个读卡器和U盘都完全正常使用。
综合你讲，这盒子的电路好象有问题。
但是如果运行自带的Android又没有这些问题。
所以问题又象是Uboot中涉及电源管理的代码。
