### ISSUE TITLE
请问大佬们是如何配置ntp的。armbian的时间不对，我用ntpdate来同步时间同步不上

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#504]
ntp service statue
 ntp.service - Network Time Service
     Loaded: loaded (/lib/systemd/system/ntp.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2022-08-13 19:39:42 CST; 12min ago
       Docs: man:ntpd(8)
    Process: 6308 ExecStart=/usr/lib/ntp/ntp-systemd-wrapper (code=exited, status=0/SUCCESS)
   Main PID: 6314 (ntpd)
      Tasks: 2 (limit: 3321)
     Memory: 1.3M
        CPU: 234ms
     CGroup: /system.slice/ntp.service
             └─6314 /usr/sbin/ntpd -p /var/run/ntpd.pid -g -u 120:132

Aug 13 19:50:33 armbian ntpd[6314]: Soliciting pool server 139.199.215.251
Aug 13 19:50:34 armbian ntpd[6314]: Soliciting pool server 5.79.108.34
Aug 13 19:50:39 armbian ntpd[6314]: Soliciting pool server 193.182.111.142
Aug 13 19:50:41 armbian ntpd[6314]: Soliciting pool server 185.209.85.222
Aug 13 19:50:43 armbian ntpd[6314]: Soliciting pool server 185.125.190.57
Aug 13 19:51:37 armbian ntpd[6314]: Soliciting pool server 185.209.85.222
Aug 13 19:51:40 armbian ntpd[6314]: Soliciting pool server 78.46.102.180
Aug 13 19:51:44 armbian ntpd[6314]: Soliciting pool server 94.130.49.186
Aug 13 19:51:47 armbian ntpd[6314]: Soliciting pool server 119.28.183.184
Aug 13 19:51:48 armbian ntpd[6314]: Soliciting pool server 185.125.190.56

**Comment by helloyuegang** [comment]
root@armbian:~# apt-get install ntpdate
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following NEW packages will be installed:
  ntpdate
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/51.5 kB of archives.
After this operation, 178 kB of additional disk space will be used.
Selecting previously unselected package ntpdate.
(Reading database ... 36728 files and directories currently installed.)
Preparing to unpack .../ntpdate_1%3a4.2.8p15+dfsg-1ubuntu2_arm64.deb ...
Unpacking ntpdate (1:4.2.8p15+dfsg-1ubuntu2) ...
Setting up ntpdate (1:4.2.8p15+dfsg-1ubuntu2) ...
Processing triggers for man-db (2.10.2-1) ...
root@armbian:~# ntpdate ntp1.aliyun.com
19 Aug 20:56:00 ntpdate[7187]: adjust time server 120.25.115.20 offset +0.000513 sec
root@armbian:~# date
Fri Aug 19 08:56:04 PM CST 2022

**Comment by ophub** [comment]
timedatectl

**Comment by helloyuegang** [comment]
> timedatectl 我是改时区，时区正常了时间就对了。 在armbian-config里面改时区也可以

我也一样，设置时区后时间就是准的，另外我路由DHCP服务设有NTP服务，不知道armbian会不会识别到
![image](https://user-images.githubusercontent.com/104582100/185634184-5b716856-d147-40e1-b9d0-b38ad1b089f7.png)

**Comment by jsdfhasuh** [comment]
root@armbian:~# ntpdate ntp1.aliyun.com
19 Aug 22:10:02 ntpdate[4233]: the NTP socket is in use, exiting
root@armbian:~# ntpdate -u "ntp1.aliyun.com"
19 Aug 22:10:49 ntpdate[4861]: no server suitable for synchronization found
root@armbian:~# timedatectl
               Local time: Fri 2022-08-19 22:11:24 CST
           Universal time: Fri 2022-08-19 14:11:24 UTC
                 RTC time: Thu 1970-01-01 00:02:05
                Time zone: Asia/Shanghai (CST, +0800)
System clock synchronized: no
              NTP service: n/a
          RTC in local TZ: no
root@armbian:~# 
我的时区也是对，但是就是更新不了

**Comment by ophub** [comment]
`tzselect`
选择4，亚洲 `Asia`
选择9，中国 `Chinua`
选择1，`Beijing Time`
选择1，确定
复制下：`cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime`
保存重启：`sync && reboot`

**Comment by ophub** [comment]
好的
