### ISSUE TITLE
各位大佬，求教s905l能用这个系统吗？魔百盒r3300l

### ISSUE THREAD

**Issue by leebook** [ophub/amlogic-s9xxx-armbian#507]

**Comment by ophub** [comment]
S905L3A/S905L3A-B可以

**Comment by a520ass** [comment]
可以用的，同款机器
![B314AB3F-BF90-4788-88B1-235B09B3BA1F](https://user-images.githubusercontent.com/8427401/185751938-8b92a107-8817-4349-8cd8-c751a5d7164e.jpeg)

**Comment by ophub** [comment]
你是使用的s905l3a固件？需要刷其他安卓系统的固件吗？还是原厂系统即可使用？

**Comment by a520ass** [comment]
可以用s905x的armbian，我是以p212当模版做了r3300l的dts。刷个有root的安卓固件

**Comment by ophub** [comment]
能分享一下你的dts源码和刷的安卓系统吗

**Comment by a520ass** [comment]
> 能分享一下你的dts源码和刷的安卓系统吗

有dts源码，安卓系统太大了，传不了
[meson-gxl-s905l-r3300l.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9391762/meson-gxl-s905l-r3300l.zip)

**Comment by ophub** [comment]
谢谢分享，这个盒子是百兆有线网络吧？蓝牙和无线可以使用？
安卓TV系统有没网络上的可以下载地址贴一个？

**Comment by a520ass** [comment]
> 谢谢分享，我可以把你的dts提交到 https://github.com/unifreq 的几个内核仓库吗？这样以后编译的内核就自动都包含了。
> 
> 这个盒子是百兆有线网络吧？无线可以使用？蓝牙不可以使用？ 安卓TV系统有没网络上的可以下载地址贴一个？

dts 可以提交，不过u-boot有点问题，用p212的u-boot作为overload ，只能从usb启动。百兆有线，无线可以使用，硬件不带蓝牙

**Comment by ophub** [comment]
好的，谢谢

**Comment by ophub** [comment]
[Amlogic.u-boot.dtb.docx](https://github.com/ophub/amlogic-s9xxx-armbian/files/9420987/Amlogic.u-boot.dtb.docx)
[default.xlsx](https://github.com/ophub/amlogic-s9xxx-armbian/files/9420989/default.xlsx)

只能USB使用，不能写入EMMC使用？写入后无法启动，是不是因为你写入到了不安全的区域，你可以根据这个文档看看这个盒子的安全分区，调整写入文件的起始结束位置。

**Comment by a520ass** [comment]
已经确定是p212 u-boot的问题，读取不了emmc，现象就是这样https://github.com/ChalesYu/extdrv4openwrt/issues/1#issue-1319125951
