### ISSUE TITLE
Ubuntu Jammy Does Not Boot After Upgrade Kernel-5.15.61-flippy-75+o

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#508]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
Ubuntu Jammy upgrade to kernel 5.15.61 and it no longer boot up.  Just black screen.

**To Reproduce**
Steps to reproduce the behavior: sudo armbian-update 5.15.61.  After that No longer able to boot up.

**Expected behavior**

**Screenshots**

**Armbian Version**
 - Kernel Version: 5.15.56
 - Release: Jammy
 - Edition: Gnome

**Device (please complete the following information):**
 - SOC: S922X
 - Brand: Beelink
 - Model GT King Pro (Revision A)

**Additional context**

Downloaded https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_08.20.0617/Armbian_22.08.0_Aml_s922x-reva_jammy_5.15.61_server_2022.08.20.img.gz and flash to USB.  This image also cannot boot up.

**Comment by ophub** [comment]
After updating to other kernels, 5.15.61 has a bug that hdmi has no signal. In s922x, s905d, s905l3a and other socs, I have received reports that the screen cannot be displayed, but ssh can be used online.

**Comment by JFLim1** [comment]
> After updating to other kernels, 5.15.61 has a bug that hdmi has no signal. In s922x, s905d, s905l3a and other socs, I have received reports that the screen cannot be displayed, but ssh can be used online.

Thanks for the info.  I tried to recover the Ubuntu Jammy image after installing kernel-5.15.61 using "chroot".

```
sudo mount /dev/sdb2 /mnt
cd /mnt
sudo chroot .
sudo armbian-update 5.18.18

or

sudo armbian-update 5.19.2

```
But it return Error not being able to locate the "mounting table" or something like that. 

In future when we face this issue is there a way to recover?

**Comment by ophub** [comment]
unzip, manually overwrite
/boot
/usr/lib/modules

**Comment by JFLim1** [comment]
> unzip, manually overwrite
> /boot
> /usr/lib/modules

Thank you.

I tried to do that.  Was successful on /boot "uInitrd" "zImage" etc but when I open "/usr/lib/modules/" it shows I am in boot up image /usr/lib/modules" in this case "Bullseye" and the kernel used is 5.19.2-flipyy-76+, it does NOT show I have modules-5.15.61-flippy-75+o!

How to rectify this?  Appreciate your guidance.  Thanks.

**Comment by ophub** [comment]
/lib/modules
the same path

**Comment by JFLim1** [comment]
Thanks.  Will take note of this.

**Comment by JFLim1** [comment]
Hi @ophub ,

Just checking whether the newly released kernel-5.15.62-flippy-76+o resolved the:

**"5.15.61 has a bug that hdmi has no signal. In s922x, s905d, s905l3a and other socs,"**?

Thanks.

**Comment by ophub** [comment]
After I update the HDMI shows normally

**Comment by JFLim1** [comment]
Thank you.
