### ISSUE TITLE
CM311-1aYS(M) S905l3a 2+16G有时无法引导系统

### ISSUE THREAD

**Issue by NaZawsze** [ophub/amlogic-s9xxx-armbian#509]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
//第一次反馈，如有不足，请指出，谢谢!
按照操作刷入emmc后，开机能够引导，HDMI画面从乱码变为启动服务跑码，并且盒子里从红灯变为绿灯，随后进入系统。当时无论是执行reboot还是断电开机都是可以正常引导的。但是过了一段时间之后执行reboot就无法引导，HDMI黑屏，盒子里红灯常亮，无法进入系统，再次断电重新开机也无法引导进入系统。

**To Reproduce**
写入命令: armbian-install no
执行完成后，断电重新开机，再次断电拔掉u盘，之后可以自行引导系统。
过段时间执行reboot和断电可以触发，有几个小时之后，也有一天之后，触发时间不固定。

**Expected behavior**
刷入emmc后能够稳定引导进入armbian系统。

Armbian Version
Armbian_22.08.0_Aml_s905l3a_jammy_5.15.61_server_2022.08.20.img

**Device:CM311-1aYS(M)**
 - SOC: S905l3a
 - RAM 2G
 - EMMC 16G

**Comment by xcray** [comment]
断电之前执行poweroff了吧？5.15.61的内核不太推荐，建议60或干脆最新的62。
起不来的时候插上u盘开机基本上都可以起来，u盘保持写入emmc之前的状态。
这个盒子是有些邪性

**Comment by ophub** [comment]
5.15.61内核有问题，hdmi没输出，用5.15.62可以正常显示

**Comment by Arancia0** [comment]
我特地注册来回答我已经解决了这个问题，在我的CM311-1a上，在使用ext4为系统安装格式经常会出现这个问题，但我偶然用btrfs安装后再也没有重启后变砖的问题了，希望你能尝试下这是个例还是可以泛用的方案

**Comment by ParticipateDead** [comment]
> 断电之前执行poweroff了吧？5.15.61的内核不太推荐，建议60或干脆最新的62。 起不来的时候插上u盘开机基本上都可以起来，u盘保持写入emmc之前的状态。 这个盒子是有些邪性

好的，感谢回复。我去试一下。

**Comment by ParticipateDead** [comment]
> 5.15.61内核有问题，hdmi没输出，但ssh可以连接。
> 
> 用5.15.62可以正常显示 更新到最新内核：`armbian-update`

好的，我用新的内核去试试。非常感谢。

**Comment by ParticipateDead** [comment]
> 我特地注册来回答我已经解决了这个问题，在我的CM311-1a上，在使用ext4为系统安装格式经常会出现这个问题，但我偶然用btrfs安装后再也没有重启后变砖的问题了，希望你能尝试下这是个例还是可以泛用的方案

好的，我先使用新的内核试一下，然后再试试您的方法。谢谢特意注册来回答我的问题！！！

**Comment by Doboo** [comment]
写入完成以后，不要断电拔usb。先reboot一下，重启成功以后再断电、拔USB。

**Comment by ParticipateDead** [comment]
> 写入完成以后，不要断电拔usb。先reboot一下，重启成功以后再断电、拔USB。

之前也是这样的，但是过段时间重启就不能引导了

**Comment by ParticipateDead** [comment]
正在使用[Armbian_22.08.0_Aml_s905l3a_jammy_5.15.62_server_2022.08.21.img.gz]
写入armbian-install no
btrfs文件格式
暂时reboot没有出现问题，这几天我观察一下。感谢各位提供的建议！

**Comment by ParticipateDead** [comment]
> 我特地注册来回答我已经解决了这个问题，在我的CM311-1a上，在使用ext4为系统安装格式经常会出现这个问题，但我偶然用btrfs安装后再也没有重启后变砖的问题了，希望你能尝试下这是个例还是可以泛用的方案

62版本btrfs重启后每次都能正常引导，但是有时候网络不通，需要重新插拔网线。

**Comment by ParticipateDead** [comment]
> > 我特地注册来回答我已经解决了这个问题，在我的CM311-1a上，在使用ext4为系统安装格式经常会出现这个问题，但我偶然用btrfs安装后再也没有重启后变砖的问题了，希望你能尝试下这是个例还是可以泛用的方案
> 
> 现在是两难。我原来也一直倾向于用btrfs，但在我的cm311-1a上经常报错，某个文件读取错误之类的，甚至导致无法正常使用，启动倒是不受影响，改成ext4就好了。 但是ext4确实有开机无法启动的情况。和楼主说的还不太一样，我发现短时间断电、reboot都没问题，就是长时间断电不行！凉透了就起不来了，必须再插回u盘启动一次。
> 
> btrfs在启动成功这一点上好像没啥问题。

我是62内核ext4文件系统，短时间内没问题，一段时间后reboot就无法引导，红灯闪烁。u盘也无法引导，必须要重新线刷固件。btrfs文件格式则是正常引导，亮绿灯，但是有时网络不通，插拔网线后恢复正常。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/517
我被大家的反馈整迷糊了，如果这个帖子里分区表是正确的话，应该你用btrfs文件系统会报错，但是你又是正确的，这个盒子还有很多变种？

**Comment by NaZawsze** [comment]
> 

我去看看其他的反馈，我不知道在哪个阶段会报错。

**Comment by NaZawsze** [comment]
> #517 我被大家的反馈整迷糊了，如果这个帖子里分区表是正确的话，应该你用btrfs文件系统会报错，但是你又是正确的，这个盒子还有很多变种？ 你方便还原安卓系统，看看你的盒子的分区表吗？ 这个盒子的安卓系统img文件你有没？方便提供个下载地址吗？我转存下方便以后的人使用



> 

安卓系统img文件我有，我正在尝试上传至阿里云，或者需要我上传至哪个平台?国内国外的都可以。
我晚上会还原安卓系统，我尝试将分区表发上来。

**Comment by NaZawsze** [comment]
CM311-1a线刷安卓img文件
文件夹 https://drive.google.com/drive/folders/1lhJk2N43TSv2R79ezr-TusynAIlmQU5l?usp=sharing
压缩包 https://drive.google.com/file/d/1Nsc9GnNqVO_wmUVfqK1fmoaKlyRClbry/view?usp=sharing

**Comment by NaZawsze** [comment]
> #517 我被大家的反馈整迷糊了，如果这个帖子里分区表是正确的话，应该你用btrfs文件系统会报错，但是你又是正确的，这个盒子还有很多变种？ 你方便还原安卓系统，看看你的盒子的分区表吗？ 这个盒子的安卓系统img文件你有没？方便提供个下载地址吗？我转存下方便以后的人使用

#517 我adb进入安卓系统后，不知道该怎么获取分区表，我也看了这个问题，但是我没能找到相关的命令，f大查看分区表的文档，我没有找到。我看到您在这个问题中已经获得了分区表并已经找到了解决方案，所以我这里应该不用再贴出分区表了吧。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

最后12.10里是怎么制作安卓系统分区表

**Comment by NaZawsze** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md
> 
> 最后12.10里是怎么制作安卓系统分区表
> 
> CM311的已经测试过可以了，你得到的分区表和他的一样吧。

是的，用的都是同一线刷包，昨天尝试了最新的系统。使用的ext4文件系统，目前没有发现问题，一切正常。
