### ISSUE TITLE
Kernel support squashfs

### ISSUE THREAD

**Issue by Gluk41** [ophub/amlogic-s9xxx-armbian#511]
Hello!
I can't use the graphical shell Ubuntu desktop (Gnome3) in builds:
[Armbian_22.08.0_Aml_s905x3_jammy_5.10.137_server_2022.08.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_08.21.2344/Armbian_22.08.0_Aml_s905x3_jammy_5.10.137_server_2022.08.21.img.gz)
[Armbian_22.08.0_Aml_s905x3_jammy_5.15.62_server_2022.08.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_08.21.2344/Armbian_22.08.0_Aml_s905x3_jammy_5.15.62_server_2022.08.21.img.gz)
Device:  x96max plus2
Please add support squashfs and snap!

To reproduce the error, simply type:  sudo apt install firefox
Or: sudo snap install *any_app*

The problem and its solution are described in this letter:

Relevant debug logging from DpkgTerminalLog.txt:

==> Installing the firefox snaperror: system does not fully support snapd: cannot mount squashfs image using "squashfs": mount: /tmp/sanity-mountpoint-438413677: неизвестный тип файловой системы 'squashfs'.

I can't speak Russian, but apparently this means that 'squashfs' is anunknown filesystem type. Is this a custom kernel with squashfs supportdisabled?
** Changed in: firefox (Ubuntu)       
Status: New => Incomplete

-- 
You received this bug notification because you are subscribed to the bugreport.
https://bugs.launchpad.net/bugs/1987296

Title:  
package firefox 103.0+build1-0ubuntu0.20.04.1 failed to  install/upgrade: new firefox package pre-installation script  subprocess returned error exit status 1
Status in firefox package in Ubuntu:  Incomplete

Bug description:  Update  

ProblemType: Package  

DistroRelease: Ubuntu 22.04  
Package: firefox 103.0+build1-0ubuntu0.20.04.1  
Uname: Linux 5.15.60-flippy-75+o aarch64  
AddonCompatCheckDisabled: False  
ApportVersion: 2.20.11-0ubuntu82.1 
Architecture: arm64  
AudioDevicesInUse: Error: command ['fuser', '-v', '/dev/snd/timer'] failed with exit code 1:  
BuildID: 20220718155818  
CasperMD5CheckResult: unknown  
Channel: Unavailable  Date: Mon Aug 22 16:12:32 2022  
ErrorMessage: new firefox package pre-installation script subprocess returned error exit status 1  
ForcedLayersAccel: False  
IpRoute:   
default via 10.42.0.1 dev eth0    
default via 10.42.0.1 dev eth0 proto dhcp metric 100    
10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.141    
10.42.0.0/24 dev eth0 proto kernel scope link src 10.42.0.142 metric 100    
169.254.0.0/16 dev eth0 scope link metric 1000  
Lspci:     

NoProfiles: True  
PciNetwork:     

PulseList: Error: command ['pacmd', 'list'] failed with exit code 1: Нет запущенного демона PulseAudio, либо он не запущен в качестве сеансового демона.  
Python3Details: /usr/bin/python3.10, Python 3.10.4, python3-minimal, 3.10.4-0ubuntu2  
PythonDetails: N/A  RebootRequiredPkgs: Error: path contained symlinks.  
RelatedPackageVersions:   dpkg 1.21.1ubuntu2.1   
apt  2.4.7  
RunningIncompatibleAddons: False  
SourcePackage: firefox  
Title: package firefox 103.0+build1-0ubuntu0.20.04.1 failed to install/upgrade: new firefox package pre-installation script subprocess returned error exit status 1  
UpgradeStatus: Upgraded to jammy on 2022-08-22 (0 days ago)  
mtime.conffile..etc.firefox.syspref.js: 2021-02-15T01:04:48  
mtime.conffile..etc.logrotate.d.apport: 2022-08-21T11:18:31.143342

**Comment by ophub** [comment]
Snap provides good support for x86_64, but very few packages are supported in arm64, and few software can be installed this way.

There is firefox in `armbian-software`, you install it through him

**Comment by Gluk41** [comment]
> Snap provides good support for x86_64, but very few packages are supported in arm64, and few software can be installed this way.
In builds from Balbes Snap and squashfs fully supported. 
> There is firefox in `armbian-software`, you install it through him
I know how to install Firefox. I did this to install ubuntu-desktop.
Unfortunately, the installation is crooked, there are a lot of errors due to the lack of squashfs 
In desktop mode, many built-in utilities do not work, the installation of language support does not work, gnome-remote-desktop does not work, desktop design, fonts, cursors - everything from Gnome. 
Unfortunately, not everything can be fixed by direct installation of packages or through Synaptic. Most utilities, for example, repository manager, driver manager and language manager do not work. 
Too much in Desktop mode is tied to squashfs and snap

**Comment by Gluk41** [comment]
Please add squashfs support!

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/96ac556ad3a88a290a7c11467932f3d926e9362c

I turned on squashfs support by default in all kernels, and then tested the newly compiled kernel

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/stable

I have finished compiling the two kernels 5.4.210 and 5.10.137. You need to update the kernel of the non-current system when you update the test:
```
armbian-update 5.4.210
armbian-update 5.10.137
```

**Comment by Gluk41** [comment]
Thanks! 
Thank you very much!
The installation went without any errors at all!
But there are problems after installation... 
This topic can be closed, everything is fine, thanks again!!!
