### ISSUE TITLE
hk1box

### ISSUE THREAD

**Issue by darescloud** [ophub/amlogic-s9xxx-armbian#512]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Armbian Version**
 - Kernel Version: 最新5.15
 - Release: debian
 - Edition: server

**Device (please complete the following information):**
 - SOC: S905x3
 - Brand: hk1box
 - Model hk1box

**Additional context**
gpu加速不存在导致显示花屏。移动鼠标都会掉帧，出现很多指针。不能正确识别分辨率

**Comment by ophub** [comment]
armbian调用不了gpu加速，但是应该也不会花屏，我日常使用中也很流畅。你换个内核试试
`armbian-update 5.19.3`

**Comment by darescloud** [comment]
> 

你加了f大的电报群吗，我发了实况视频，卡的要死

**Comment by darescloud** [comment]
> armbian调用不了gpu加速，但是应该也不会花屏，我日常使用中也很流畅。你换个内核试试 `armbian-update 5.19.3`

已经升级了还是卡

**Comment by ophub** [comment]
armbian-software
你通过软件中心安装桌面试试，我在tx3上测试也是很流畅的，tx3和hk1性能一样
