### ISSUE TITLE
network服务和NetworkManager服务出现冲突

### ISSUE THREAD

**Issue by MDCY9008** [ophub/amlogic-s9xxx-armbian#515]
开机时会出现2个IP地址。

**Screenshots**
![image](https://user-images.githubusercontent.com/54255527/186887281-4ae8d597-49e1-49e1-9b5e-f384934c4398.png)

**Armbian Version**
 - Kernel Version: 5.15.62
 - Release: jammy  (8.26)
 - Edition: server

**Device**
 - SOC: 905l3a
 - Brand: 魔百盒
 - Model 311-1a yst

**Comment by ophub** [comment]
关闭 NetworkManager.service

```
systemctl stop NetworkManager.service
systemctl disable NetworkManager.service
init 6
```

**Comment by MDCY9008** [comment]
> 关闭 NetworkManager.service
> 
> ```
> systemctl stop NetworkManager.service
> systemctl disable NetworkManager.service
> init 6
> ```

可否在```rebuild```的时候就将此服务去掉，设备ip会在路由器乱跳，经常导致ssh掉线。

**Comment by xcray** [comment]
前段时间有issue说过这个，/etc/network/interfaces里把eth0删掉，或者加上client no

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/custom_service/start_service.sh

预置了一个自定义启动执行命令的统一操作文件，你可以把命令放这

**Comment by ophub** [comment]
kvm启用时，et0会自动失效，会创建br0来使用

**Comment by MDCY9008** [comment]
> kvm启用时，eth0会自动失效，会创建br0来使用

受教了，谢谢大佬，问题解决了
