### ISSUE TITLE
CM311-1a新的问题，在8.26版本 reboot和poweroff无法关机

### ISSUE THREAD

**Issue by Arancia0** [ophub/amlogic-s9xxx-armbian#516]
型号 CM311-1a
版本 Armbian_22.08.0_Aml_s905l3a_jammy_5.15.62_server_2022.08.26
问题 写入emmc后，无法关机，新刷入没有修改任何配置，由于没有显示器，不知道卡在哪里。U盘启动时reboot和poweroff都正常

**Comment by pyrothicc** [comment]
Same problem on s905x3 

x96 max+ (Armbian_22.08.0_Aml_s905x3_jammy_5.10.138_server_2022.08.26.img)

Shutdown + Reboot don't work

**Comment by ophub** [comment]
会不会是数据忙导致的，我一般都是这样操作

```
#先把内存数据强刷会硬盘，确保数据不丢失。然后等几秒后重启。
sync && sleep 3 && reboot

#关机也可以这样
sync && sleep 3 && poweroff
```

**Comment by Arancia0** [comment]
![Uploading QQ图片20220827155452.jpg…]()

确实无法重启，手上两个cm311，在8.26日的版本输入reboot后btrfs报错刷屏，并且无法操作，只能强制断电了

**Comment by Arancia0** [comment]
![image](https://i0.hdslb.com/bfs/album/9657bbe5ea60ba3823adce4756cb930c62ebb025.jpg)

**Comment by ophub** [comment]
重新线刷回安卓系统
usb重新写armbian 系统，把/usr/sbin/armbian-install的这个地方的3个值改一下，再写入。这是cm311的正确分区位置

```
    elif [[ "${AMLOGIC_SOC}" == "s905l3a" ]]; then
        BLANK1="68"
        BOOT="512"
        BLANK2="647"
```
