### ISSUE TITLE
S905x3 reboot not working

### ISSUE THREAD

**Issue by pyrothicc** [ophub/amlogic-s9xxx-armbian#518]
x96 max+ (Armbian_22.08.0_Aml_s905x3_jammy_5.10.138_server_2022.08.26.img)

Shutdown + Reboot don't work

hangs on NFS service.

reboot -f works fine

**Comment by ophub** [comment]
In the last week of upstream updates, armbian did not adjust the nfs service, maybe the kernel changed. Other soc settings also found the same problem, let me find the reason.
