### ISSUE TITLE
请问有大佬尝试安装emby的客户端到armbian里面吗

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#519]
sudo apt-get update
sudo apt-get install cec-utils libasound2 libatomic1 libc6 libegl1 libgcc-s1 libpulse0 libstdc++6
sudo dpkg -i /path/to/deb

安装包链接：https://github.com/MediaBrowser/emby-theater-electron/releases/download/3.0.16/emby-theater-deb_3.0.16_arm64.deb

虽然能安装上，在gnome里面能找到，但是按了没办法启动

**Comment by ophub** [comment]
https://emby.media/linux-server.html

**Comment by jsdfhasuh** [comment]
> https://emby.media/linux-server.html

大佬，这是服务器端，我想安装的是客户端emby_threater

**Comment by jsdfhasuh** [comment]
因为armbian安装emby服务端没办法调用盒子的强大的解码能力，那我通过安装emby的客户端看看能不能调用

**Comment by ophub** [comment]
服务端和客户端功能不同。
但都不能调用硬解
