### ISSUE TITLE
Which dtb to choose for gtking-pro

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#52]
Hi,
And first of all a big thank you for sharing.
So I have a Beelink Gt-King Pro with a serial number starting with SA9H ...
I managed to start the latest Bulleyes flash release on sd card using the gt-king-pro-rev_a.dtb but I had a system freeze and as we find a lot of different dtb with gtking-pro as a header suddenly I'm not sure I'm using the correct one .. Anyway when I use Coreelec on my gtking-pro I also use a dtb marked rev_a that's why I used this one .
![IMG_20211213_193051](https://user-images.githubusercontent.com/62643837/145873792-14c53ad1-bac6-4ec4-84c3-8846fb1167e1.jpg)
.
Thank

**Comment by ophub** [comment]
meson-g12b-gtking-pro-rev_a.dtb for `odroid-n2`

Choose meson-g12b-gtking-pro.dtb for your device.

You can use Armbian_21.11.0_Aml_`s922x`_*.img to boot from a USB/TF card. Its default dtb file is meson-g12b-gtking-pro.dtb, and you can install it to EMMC and select `42`.

**Comment by MX10-AC2N** [comment]
Thank @ophub,
I had first tried with gtking-pro.dtb but had failed to start, I will try again ..
I don't want to install Armbian on the Emmc but kept the system on SD card. I didn't understand what you can select 42 means.
Thanks again for the info, I'll keep you posted on the progress.

**Comment by MX10-AC2N** [comment]
OK, I was able to boot with gtking-pro.dtb.
I regularly have a freeze on restarting just when the USBs should start. I have to electrically unplug the Gt-King Pro and plug it back in for the startup to complete successfully.
Are there a few things in particular that need to be done to boot from the sd card?
Thanks again for sharing, before to run Armbian on my GT-King Pro I used an image built by Balbes150 but it was not really done for this tvbox, now thanks to you, we have some ...
Thank you so much..

**Comment by MX10-AC2N** [comment]
dmesg output => https://paste.yunohost.org/egiteposat.vbs

**Comment by ophub** [comment]
It is a good choice to use armbian on TF/SD/USB card, with larger space and more flexible use.
It is recommended that you use the `armbian-tf` command to activate the remaining space on the TF/SD/USB.
You can also use the `armbian-swap 1` command to create virtual memory, so that the system has more sufficient operating support.

**Comment by MX10-AC2N** [comment]
Thank..
I used armbian-tf and I have a new partition with the remaining space of my sd-card 128G mounted on /mnt/mmcblklp3. But the partition / still at 2G, I prefer extend the partition /

**Comment by ophub** [comment]
Your idea is very good

**Comment by ophub** [comment]
You use a s922x gtking-pro box and a 128g SD card. You are the most beautiful boy in our village.

**Comment by MX10-AC2N** [comment]
Lol, I use armbian for install YUNoHost... https://github.com/YunoHost/yunohost

**Comment by ophub** [comment]
`armbian-tf`: According to your good wishes, you can now choose to `create` a new partition or `expand` the current partition.

According to the prompt, enter `e` to expand the remaining space to the current system partition and file system, and enter `c` to create a new third partition.

**Comment by MX10-AC2N** [comment]
Wow, congratulations @ophub 
You code faster than your shadow, you are the Lucky Luke of computer coding.
I allow myself to add a little more, the best would be to be able to extend the main partition entirely or up to a chosen size and to create a new partition with the remaining space.
Is there a way to undo my previous armbian-tf command or do I need to reflash my sd card ..
Thank you again, and sorry for the formulations I am French and I use google translate for English

**Comment by ophub** [comment]
`df -hT`: View your partition name, such as` /dev/sda`

`fdisk /dev/sda`: Press `m` to view the parameter description, follow the prompts to select `d`, input `3` to delete 3 partitions, select `w` to save, and enter `umount /dev/mnt/sda3` to uninstall

Then `armbian-tf` select `e` extended partition

**Comment by MX10-AC2N** [comment]
I started again from zero, I reflashed a sd card but I again have this freeze problem at startu
![IMG_20211214_191939](https://user-images.githubusercontent.com/62643837/146057855-ba1a8a99-82d3-44b7-8b7d-e5eda80f9a03.jpg)
p

**Comment by MX10-AC2N** [comment]
After having unplugged / re-plugged the box 3 times I was able to go to the next step but this time the startup was not completed correctly .. I will reflash my sd card again ..
However I already had this problem of freeze at startup, could it be the fault of my sd card, which shows no error when I check it under windows10 ..

**Comment by ophub** [comment]
1. The firmware using the `5.4 kernel` does not require u-boot secondary boot, so this phenomenon will not occur.

2. This is a phenomenon that may only occur with `kernels of 5.10 and above`. At present, the boxes listed in the instructions on the homepage have all been adapted, and this phenomenon is gone. But the unknown box may appear this phenomenon due to the `u-boot` file mismatch.
 
3.  By writing the 5.10 armbian firmware into emmc, replacing the Android u-boot of the box with the u-boot that comes with the customized firmware, the booting problem is solved.

4.  Adding a `resistor` to TTL can solve the problem of using the kernel of version `5.10` and above. such as: [Add resistor](https://user-images.githubusercontent.com/68696949/110910162-ec967000-834b-11eb-8fa6-64727ccbe4af.jpg)

```
#######################################################            #####################################################
#                                                     #            #                                                   # 
#   Resistor (pull-down): between TTL's RX and GND    #            #   Resistor (pull-up): between TTL's 3.3V and RX   #
#                                                     #            #                                                   #
#            3.3V   RX       TX       GND             #     OR     #        3.3V               RX     TX     GND       #
#                    ┖————█████████————┚              #            #         ┖————█████████————┚                       #
#                      Resistor (5~10K)               #            #           Resistor (5~10K)                        #
#                                                     #            #                                                   #
#######################################################            #####################################################
```

**Comment by MX10-AC2N** [comment]
> Which box ? => It's again with my Beelink GT-King Pro
> 
> which kernel version of the firmware is used? => I use kernel 5.10.84
> 
> has it ever been written into emmc? =>No
> 
> What system is currently in the emmc of the box? => Android 9 from beelink

Thank again @ophub you're great..

**Comment by MX10-AC2N** [comment]
This morning I downloaded the latest version Armbian_21.11.0_Aml_s922x_bullseye_5.10.85_2021.12.15.1030.img.gz
Flashed to my SD card
Renamed the uboot-gtkingpro.bin file on the /boot partition to uboot.ext
Checked /boot/uEnv.txt to use the correct .dtb file (it was already the correct one, so no modif in uEnv.txt)
On my gtking-pro tvbox I only connected my wireless keyboard receiver to 1 of the USB ports. And I have the impression that depending on the USB port it's plugged into I'm going to have this freeze problem on startup, I'm going to do some reboot tests to verify this ..

**Comment by MX10-AC2N** [comment]
Well finally I had this freeze problem again at startup .. nothing to do with being plugged into a particular USB port ..
I took a screenshot on a successful start. We can see errors
![IMG_20211215_105903](https://user-images.githubusercontent.com/62643837/146166338-7872a18e-1969-42b6-bc3c-bef231bfac95.jpg)
![IMG_20211215_105904](https://user-images.githubusercontent.com/62643837/146166352-533a7858-f79e-48d6-9ede-7148dc1a4be2.jpg)
.

**Comment by ophub** [comment]
You try the 5.4 kernel firmware.

**Comment by MX10-AC2N** [comment]
No, I haven't tried kernel 5.4
I prefer to try to keep 5.10 because I know it works on beelink gtking-pro, there is even a linux-5.14 which is available on the forum http://forum.bee-link.com/forum.php?mod=forumdisplay&fid=196&page=1
When the boot finishes well, the system seems fully operational just the problem probably related to u-boot.ext ..
In the photo I posted to you this morning, we can see an error marking "bootfromsd" not defined. is this normal even though everything is installed on an SD card?

**Comment by ophub** [comment]
ok

**Comment by MX10-AC2N** [comment]
Hi @ophub,
Today I try the kernel 5.4 firmware
Armbian_21.11.0_Aml_s922x_bullseye_5.4.166_2021.12.17.1259.img.gz
But finally I have the same problem of freeze at startup .. I managed to start by removing everything on the USB inputs, perhaps a beginning of response to this problem .. Finally I also believe that my concern is linked the fact that I keep the Beelink Android 9 firmware on the emmc is that suddenly there is a conflict between Uboot legacy and Uboot mainline.
Is it possible to have an armbian construction planned to be installed on an external sd or usb support and especially planned so that we have kept Android on the emmc.
With Android I can still see all the web content protected by DRM rights (netflix, amazon prime video, ..) while under armbian, in particular in arm64, this is not yet possible, one day maybe .. finally I ' hope ..
I will try all this by installing on a USB medium for comparison ..
Thank you again and sorry for this bad news, for the moment difficult to start under Beelink GTKing-Pro no matter which kernel was using ..

**Comment by MX10-AC2N** [comment]
> I started again from zero, I reflashed a sd card but I again have this freeze problem at startup
> 
> ![Snip20211215_1](https://user-images.githubusercontent.com/68696949/146101267-7b0a039e-f88a-446a-9517-c622232d88a3.png)

Same freeze.

**Comment by MX10-AC2N** [comment]
I tried to flash to USB media to see if the problem was not with my sd card but I end up with the same freeze on startup ..
It does not work correctly on my Beelinnk GTKing-Pro .. Sorry @ophub

**Comment by MX10-AC2N** [comment]
@ophub 
Oops, I'm sorry, I didn't configure the /boot partition correctly
I had first done as on the other firmware, i.e. rename u-boot.gtking-pro.bin to u-boot.ext => That was my error there is no need to u-boot.ext so I rename it to u-boot-ext.bak and this time the boot goes smoothly ..
Thanks and sorry again ..

**Comment by MX10-AC2N** [comment]
Beelink GtKing-Pro have 4Gb of RAM but with the firmware 5.4, system have only 3,24Gb and when I boot 5.10 the system have 3,7Gb
Why we can't have the 4Gb of the tvbox ?

**Comment by MX10-AC2N** [comment]
Hi @ophub 
I finally got to boot kernel> 5.10 on my Beelink GT-King_pro but I didn't use your u-boot.ext but this one ..
[u-boot.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/7799217/u-boot.zip)

 If that can help others .
https://paste.yunohost.org/fuwubonube.vbs
![Capture d’écran (10)](https://user-images.githubusercontent.com/62643837/147879506-dbe575ac-3d49-4c6a-9140-a0683fa3a0aa.png)
.
