### ISSUE TITLE
kernel compile script doesn't produce necessary files

### ISSUE THREAD

**Issue by AlexBokhankovich** [ophub/amlogic-s9xxx-armbian#521]
I've forked 5.19.4 kernel, applied patch and tried to build using command 
armbian-kernel -d  -k 5.19.4 -a false -p all -n -etherfix -r AlexBokhankovich/linux-5.19.y
after it successfully compiled I tried to install it and get error:

`root@armbian:/opt/kernel/compile-kernel/output/5.19.4# armbian-update
[ STEPS ] Ready to update, please wait...
[ STEPS ] Start initializing the environment...
[ STEPS ] Use local kernel files: 5.19.4

[ STEPS ] Start checking the kernel...
[ INFO ] Kernel name: [ 5.19.4-etherfix ]
tar: vmlinuz-5.19.4-etherfix: Not found in archive
tar: Exiting with failure status due to previous errors
[ INFO ] K510: [ 1 ]
[ INFO ] Enable sha256sum checking...
[ INFO ] (1/4) [ boot-5.19.4-etherfix.tar.gz ] file sha256sum check same.
[ INFO ] (2/4) [ dtb-amlogic-5.19.4-etherfix.tar.gz ] file sha256sum check same.
[ INFO ] (3/4) [ header-5.19.4-etherfix.tar.gz ] file sha256sum check same.
[ INFO ] (4/4) [ modules-5.19.4-etherfix.tar.gz ] file sha256sum check same.

[ STEPS ] Start unpacking the kernel...
cp: cannot stat 'vmlinuz-5.19.4-etherfix': No such file or directory
sha256sum: vmlinuz-5.19.4-etherfix: No such file or directory
sha256sum: zImage: No such file or directory
[ ERROR ] The /boot files is missing.`

I tried to build using ubuntu 22.04 and gor the same results

**Comment by ophub** [comment]
There is a problem with the patch you applied to the kernel source code and it cannot be compiled normally. Try removing the patch.
