### ISSUE TITLE
excuse me ，Which firmware can phicomm T1 use

### ISSUE THREAD

**Issue by xiaopangzia** [ophub/amlogic-s9xxx-armbian#522]
Armbian_22.08.0_Aml_s912-m8s_jammy_5.15.62_server_2022.08.28.img.gz ？
choice 206？
has desktop version？

**Comment by ophub** [comment]
No firmware for T1

**Comment by birdxs** [comment]
Armbian_22.11.0_Aml_s905d_bullseye_5.10.149_server_2022.10.19.img
I found the firmware for phicomm N1 can be used for phicomm T1 after replace the dtb file. It can also be written to emmc.

**Comment by ophub** [comment]
Which dtb file are you using on the phicomm T1?

**Comment by birdxs** [comment]
T1可用dtb、u-boot下载链接: https://pan.baidu.com/s/1iYKAX8n1ij0vocunoWlEww
本帖隐藏的内容
提取码 x46e
期待大佬更新适配T1的固件，那样就可以直接写入U盘刷机了，不需要替换了。

**Comment by birdxs** [comment]
> Which dtb file are you using on the phicomm T1?

T1可用dtb、u-boot下载链接: https://pan.baidu.com/s/1iYKAX8n1ij0vocunoWlEww
本帖隐藏的内容
提取码 x46e

**Comment by ophub** [comment]
meson-gxm-q201.dtb
u-boot-s905x-s912.bin
这两个文件都是固件里的文件，这个组合在phicomm T1上可以正常使用？
5.10.y/5.15.y两个系列的固件都可以写入emmc使用吗？

**Comment by birdxs** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/bootfs/dtb/amlogic/meson-gxm-q201.dtb
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-u-boot/overload/u-boot-s905x-s912.bin
> 
> meson-gxm-q201.dtb u-boot-s905x-s912.bin 你网盘里的这两个文件都是固件里带来的文件，这个组合在phicomm T1上可以正常使用？ 5.10.y/5.15.y两个系列的固件都可以写入emmc使用吗？

我下载你提供的dtb、bin文件查看HASH值与我使用的不一样。
之前我直接用大佬编译的s912固件用于T1，dtb使用固件内提供的meson-gxm-q201.dtb，发现首次启动后以太网、无线网均无法使用。使用恩山网友提供的固件Armbian_21.08.1_Arm-64_bullseye_current_5.9.0可以用于T1，故提取恩山网友分享的可用于T1的固件内dtb、bin替换到你编译的N1固件（Armbian_22.11.0_Aml_s905d_bullseye_5.10.149_server_2022.10.19），发现可以用于T1，也可以写入emmc，目前只测试了5.10.149内核，还没测试5.15.y内核。

**Comment by ophub** [comment]
你试一下用他的bin，用我固件里的dtb这个组合可以不，判断一下是不是dtb可以用

**Comment by ophub** [comment]
好的👌

**Comment by ophub** [comment]
![Snip20221107_1](https://user-images.githubusercontent.com/68696949/200320650-90de2302-7dca-456a-973a-e751ab2501c5.png)

**Comment by cjh19831115** [comment]
我按照birdx的做法，下载了bullseye中n1的固件，正常运行，有线、Wi-Fi都可正常使用，就是开机一段时间负载有点高
!
![截屏2022-11-11 12 41 30](https://user-images.githubusercontent.com/39998677/201264709-9b2cdc25-a1e0-4c69-a727-ba146fa2f5cb.png)

**Comment by ophub** [comment]
你是N1还是T1？用的哪个配置？

**Comment by cjh19831115** [comment]
我的是T1，下载s905d固件（N1），然后替换你说的2个文件。

**Comment by ophub** [comment]
你是改了/boot/uEnv.txt的值为meson-gxm-q201.dtb，然后复制了u-boot-s905x-s912.bin为u-boot.ext吧？

这两个文件是使用的固件自带的还是从第三方下载后替换的？

**Comment by cjh19831115** [comment]
是改了/boot/uEnv.txt的值为meson-gxm-q201.dtb，然后将下载的u-boot-s905x-s912.bin，直接替换包里的u-boot-s905x-s912.bin，其他没有变动

**Comment by cjh19831115** [comment]
使用@birdx提供的u-boot-s905x-s912.bin和meson-gxm-q201.dtb

**Comment by ophub** [comment]
你下载5.10的s912-m8s固件（不是s912，后面有个-m8s的值），不用改什么，直接使用试一下

https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_jammy_11.11.0828

**Comment by birdxs** [comment]
> @cjh19831115
> 
> 你下载5.10的s912-m8s固件（不是s912，后面有个-m8s的值），不用改什么，直接使用试一下
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_jammy_11.11.0828

买的USB扩展坞终于到了。中午简单测试了下，直接写入u盘，不修改任何配置
Armbian_22.11.0_Aml_s912-m8s_bullseye_5.10.155_server_2022.11.20.img.gz
5.10内核：有线正常，无线连不上，armbian-config提示not found

Armbian_22.11.0_Aml_s912-m8s_bullseye_5.15.79_server_2022.11.20.img.gz
5.15内核：有线连不上，无线正常，armbian-config正常

**Comment by ophub** [comment]
5.15固件里少一个u-boot文件。可以自己添加一下，重启试试
```
cd /boot
cp -f u-boot-s905x-s912.bin u-boot.ext
```

**Comment by ophub** [comment]
在armbian-config里安装蓝牙支持。
T1的蓝牙芯片是什么

**Comment by birdxs** [comment]
> 在armbian-config里安装蓝牙支持。 T1的蓝牙芯片是什么

O大，T1的蓝牙芯片具体型号没找到，没找到拆解相关帖子。
恩山的两个帖子提到了
[https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=356749](url)
说T1无线模块是AW-CM256SM，蓝牙芯片是CYW43455
[https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=8246203&pid=17307047](url)
这个帖子提到了修复思路，不知道如何修改DTB

**Comment by ophub** [comment]
[meson-gxm-phicomm-t1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10095727/meson-gxm-phicomm-t1.dtb.zip)

下载解压缩成dtb后缀，上传到/boot/dtb/amlogic目录下
修改/boot/uEnv.txt里的值为这个名字，保存重启试试

**Comment by birdxs** [comment]
> https://www.right.com.cn/forum/forum.php?mod=redirect&goto=findpost&ptid=8246203&pid=17307047

成功驱动蓝牙，感谢大佬
```
root@armbian:~# hciconfig -a
hci1:   Type: Primary  Bus: SDIO
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:0 acl:0 sco:0 commands:0 errors:0
        Features: 0x00 0x00 0x00 0x00 0x00 0x00 0x00 0x00
        Packet type: DM1 DH1 HV1
        Link policy:
        Link mode: SLAVE ACCEPT

hci0:   Type: Primary  Bus: UART
        BD Address: xx:xx:xx:xx:AF:E2(蓝牙地址正常)  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:3826 acl:0 sco:0 events:346 errors:0
        TX bytes:62497 acl:0 sco:0 commands:346 errors:0
        Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH SNIFF
        Link mode: SLAVE ACCEPT
        Name: 'armbian'
        Class: 0x000000
        Service Classes: Unspecified
        Device Class: Miscellaneous,
        HCI Version: 4.2 (0x8)  Revision: 0xfc
        LMP Version: 4.2 (0x8)  Subversion: 0x6119
        Manufacturer: Broadcom Corporation (15)
```

**Comment by ophub** [comment]
好的，我随后提交到f大的仓库，以后t1使用专用dtb：meson-gxm-phicomm-t1.dtb

目前是有线、无线、蓝牙都可以正常使用了吧？

**Comment by birdxs** [comment]
> 好的，我随后提交到f大的仓库，以后t1使用专用dtb：meson-gxm-phicomm-t1.dtb
> 
> 目前是有线、无线、蓝牙都可以正常使用了吧？

是的，目前我这边测试有线、无线、蓝牙均正常了。

**Comment by tfnhui** [comment]
请问各位大神 T1   5.10内核  直接用 没有网络 应该要替换哪些文件

**Comment by ophub** [comment]
几分钟前刚替换了pr，目前的内核里没有这个文件。你从我仓库下载个上传到你的固件里测试下。

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/common-files/bootfs/dtb/amlogic

**Comment by ophub** [comment]
这个T1网上的文章，有的说是百兆，有的说是千兆，他的有线网卡究竟是千兆还是百兆呢？

**Comment by tfnhui** [comment]
谢谢大佬  
我使用的这个 Armbian_22.11.0_Aml_s912_bullseye_5.10.156
 /boot/uEnv.txt 改成了  meson-gxm-phicomm-t1.dtb
文件也放进去了 但是好像还是没网 
图片链接 i.postimg.cc/P5QKtrx0/IMG-20221126-223608.jpg

**Comment by ophub** [comment]
这个dtb是5.15内核的，你更新到5.15内核试试

**Comment by tfnhui** [comment]
谢谢 5.15   有网了  没替换文件 我只改了 /boot/uEnv.txt 改成了 meson-gxm-phicomm-t1.dtb 

我再试试

**Comment by tfnhui** [comment]
不懂就问  嘿嘿   5.15  和 5.10 有什么区别呢

**Comment by ophub** [comment]
5.10内核必须使用u-boot
5.15内核可以不使用u-boot，是可选项

**Comment by tfnhui** [comment]
奇怪的很。刷了今天的5.10 WIFI正常 有线还是不正常，  

只改了 /boot/uEnv.txt 改成了 meson-gxm-phicomm-t1.dtb

**Comment by tfnhui** [comment]
额。刷了今天的5.10 WIFI正常 有线还是不正常，  请问大佬有群么

只改了 /boot/uEnv.txt 改成了 meson-gxm-phicomm-t1.dtb

**Comment by ophub** [comment]
在USB中测试下5.10的固件，启动后，除了修改uEnv.txt外，再手动复制这个文件
```
cd /boot
cp -f u-boot-p212.bin u-boot.ext
sync && reboot
```
重启后看看是否正常。

**Comment by birdxs** [comment]
> 这个T1网上的文章，有的说是百兆，有的说是千兆，他的有线网卡究竟是千兆还是百兆呢？

T1是百兆，N1是千兆

**Comment by tfnhui** [comment]
请问 大佬  你后期编译的固件  我是不是只要 armbian-update 更新就行？

**Comment by ophub** [comment]
软件包更新：armbian-update
脚本更新：armbian-sync
这2个即可

**Comment by tfnhui** [comment]
反馈一下   我装着东西呢 就经常自动重启了   不知道啥原因呢

**Comment by tfnhui** [comment]
大佬 您好  
![IMG_20221129_144536](https://user-images.githubusercontent.com/95342475/204458192-e65695a0-3141-4f7c-b435-f0b8f9789520.jpg)

5.10的 我有线一直不行  今天的版本也测试了
我除了 改了uEnv.txt 改成了 meson-gxm-phicomm-t1.dtb  其它还需要改吗

**Comment by ophub** [comment]
你下载5.15的试试

**Comment by tfnhui** [comment]
您好 5.15 是OK的  就是有时候会自动重启 ，不知道是不是硬件的问题 我想安装5.10 试试

**Comment by ophub** [comment]
5.10多了u-boot，不一定适合你的盒子。不适配时是副作用。

**Comment by tfnhui** [comment]
请问一下 大佬  bullseye  和 jammy 使用有区别吗 哪个更稳定呢

**Comment by ophub** [comment]
bullseye是基于debian,以稳定为本。
jammy是基于ubuntu，以追新为本。

稳定性一般和执腾的姿势和频率成正比，一会是惊喜，一会是惊吓。

**Comment by QAWEI** [comment]
我刷了5.15  lan没办法法DHCP不知道为啥，我想弄单臂主路由

**Comment by 891921269** [comment]
你好，请问斐讯t1盒子的armbian固件是没有声音么？我刷的是Armbian_23.02.0_amlogic_s912-m8s_jammy_6.1.3_server_2023.01.05.img

**Comment by gfourdx** [comment]
> @cjh19831115
> 
> 你下载5.10的s912-m8s固件（不是s912，后面有个-m8s的值），不用改什么，直接使用试一下
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_jammy_11.11.0828

大佬，s912和s12-m8s有什么区别呢？ 对于T1来说建议用哪个呢？

**Comment by gfourdx** [comment]
> @cjh19831115
> 
> 你下载5.10的s912-m8s固件（不是s912，后面有个-m8s的值），不用改什么，直接使用试一下
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_jammy_11.11.0828

请问大佬， s912和s912-m8s有什么区别，对于T1来说建议用哪个？这个对T1来说有区别吗？

**Comment by ophub** [comment]
s912
214

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

**Comment by gfourdx** [comment]
> s912 214
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

 原来m8s是一个款设备的名称啊， 我还以为是s912的变种呢，多谢大佬答疑解惑

**Comment by wolfit50** [comment]
蓝牙还是没法用，启动几分钟后就不正常了

`root@armbian:~# systemctl status bluetooth
● bluetooth.service - Bluetooth service
     Loaded: loaded (/lib/systemd/system/bluetooth.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-01-28 23:36:34 CST; 2min 0s ago
       Docs: man:bluetoothd(8)
   Main PID: 879 (bluetoothd)
     Status: "Running"
      Tasks: 1 (limit: 1852)
     Memory: 2.9M
        CPU: 121ms
     CGroup: /system.slice/bluetooth.service
             └─879 /usr/libexec/bluetooth/bluetoothd

Jan 28 23:36:32 armbian systemd[1]: Starting Bluetooth service...
Jan 28 23:36:33 armbian bluetoothd[879]: Bluetooth daemon 5.55
Jan 28 23:36:34 armbian systemd[1]: Started Bluetooth service.
Jan 28 23:36:34 armbian bluetoothd[879]: Starting SDP server
Jan 28 23:36:34 armbian bluetoothd[879]: Bluetooth management interface 1.21 initialized
Jan 28 23:36:34 armbian bluetoothd[879]: profiles/sap/server.c:sap_server_register() Sap driver initialization failed.
Jan 28 23:36:34 armbian bluetoothd[879]: sap-server: Operation not permitted (1)`

`root@armbian:~# hciconfig -a
hci0:   Type: Primary  Bus: UART
        BD Address: 40:9F:38:BF:B3:D4  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:4750 acl:0 sco:0 events:441 errors:0
        TX bytes:68938 acl:0 sco:0 commands:442 errors:0
        Features: 0xbf 0xfe 0xcf 0xfe 0xdb 0xff 0x7b 0x87
        Packet type: DM1 DM3 DM5 DH1 DH3 DH5 HV1 HV2 HV3
        Link policy: RSWITCH SNIFF
        Link mode: SLAVE ACCEPT
Can't read local name on hci0: Connection timed out (110)`

**Comment by heham** [comment]
所以最后的版本只有蓝牙不可用其他都正常了？那晚上测试一下

**Comment by kongjun0** [comment]
新版本没有WIFI，6.1的内核也没有，请修复

**Comment by CaryMa** [comment]
大佬，刷新了最新版5.15.108的固件以后T1没有wifi，也没有蓝牙，请问下这个怎么解啊，还有请问下如何从u盘启动，我想重新安装到emmc不知道是不是只能先刷回安卓才可以？

**Comment by hkbase** [comment]
> 这个T1网上的文章，有的说是百兆，有的说是千兆，他的有线网卡究竟是千兆还是百兆呢？

有线网口是百兆的。

**Comment by yytak** [comment]
我刷了所有的T1固件，都有一个统一的问题：
1， 浏览器用不了，我安装了firefox，安装后显示不了网页，完全无法显示文字和图像。
2，用自带的邮件客户端 Thunderbird 打开也是同样的问题，
3，只有 jammy 这个版本是可以安装 chromium，其他版本安装 chromium 都会出错。

**Comment by pcg1234** [comment]
> 大佬，刷新了最新版5.15.108的固件以后T1没有wifi，也没有蓝牙，请问下这个怎么解啊，还有请问下如何从u盘启动，我想重新安装到emmc不知道是不是只能先刷回安卓才可以？

我也是，没有WIFI,怎么弄？我下载的是S912 5.15

**Comment by 123xdxd** [comment]
安装hass蓝牙不可用，无线正常，求教大佬

**Comment by CaryMa** [comment]
您好，我不是大佬，您要不问问楼主大大，我现在好就没有用那个了




CaryMa
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ophub/amlogic-s9xxx-armbian"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月13日(星期一) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ophub/amlogic-s9xxx-armbian] phicomm T1 支持写入emmc，有线、无线和蓝牙都可以正常使用 (Issue #522)





 
安装hass蓝牙不可用，无线正常，求教大佬

**Comment by 123xdxd** [comment]
试了下putty输入apt --fix-broken install，然后在armbian-config里面的Network，BT Install安装一下，homeassistant里面就能找到蓝牙了，感谢各位和楼主大大的分享

**Comment by luodonglong** [comment]
大佬，为什么我u盘启动显示器黑屏捏

**Comment by Brucelaw0327** [comment]
https://vps.la/2023/04/10/%e6%96%90%e8%ae%aft1n1-armbian%e9%95%9c%e5%83%8farmbian_22-08-2_phicomm-n1_bullseye_current_5-15-10620230410%e7%bc%96%e8%af%91/



用这个人的就正常u盘启动

**Comment by happyhaohao65** [comment]
![QQ截图20240102104337](https://github.com/ophub/amlogic-s9xxx-armbian/assets/25346528/312aee38-0800-4a85-ad71-a14753610e76)
这个是什么问题写入失败呢

**Comment by happyhaohao65** [comment]
![QQ截图20240102104501](https://github.com/ophub/amlogic-s9xxx-armbian/assets/25346528/6667af20-d372-47a0-b91d-1d97ced51c2e)
这个是什么问题写入失败呢

**Comment by z969140717** [comment]
大佬扩容32G后写入EMMC就到这不动了，等多久都不行，有解决方法吗？

**Comment by ophub** [comment]
我看别人换存储的时候，都要把原emmc里的一个什么数据复制到这个新盘里。

**Comment by z969140717** [comment]
> 我看别人换存储的时候，都要把原emmc里的一个什么数据复制到这个新盘里。

啊啊啊？大佬研究一下出个教程好不好

**Comment by ophub** [comment]
网上有教程，n1换emmc你看一下复刻的原盘中的内容。

**Comment by alge-cn** [comment]
t1刷老大的飞牛固件，运行一天后发现有线网络有断流的情况。路由器上看t1离线了，请问大佬是什么问题？

**Comment by here179-sketch** [comment]
> t1刷老大的飞牛固件，运行一天后发现有线网络有断流的情况。路由器上看t1离线了，请问大佬是什么问题？

有具体的刷入教程吗，小白菜确实不会搞
