### ISSUE TITLE
cm311-1a-ch移动硬盘不能正常挂载

### ISSUE THREAD

**Issue by zhang-ss1** [ophub/amlogic-s9xxx-armbian#523]
系统已写入emmc，挂载移动硬盘时屏幕滚动打印下图的内容，移动硬盘不能正常挂载，即使挂载后，sftp传输数据会失败然后掉盘，换过硬盘盒，机械硬盘和固态都试过，都会出现问题；但挂载U盘或读卡器+tf卡就不会出现问题
![1](https://user-images.githubusercontent.com/74695580/187189774-63f7492e-fc08-4c1f-bc87-0d4f8fdbb130.png)
Armbian Version
Kernel Version: 5.15.62
Release: jammy (8.28)
Edition: server

Device
SOC: 905l3a
Brand: 魔百盒
Model 311-1a ch

**Comment by xcray** [comment]
供电不足？再加一路供电试试

**Comment by zhang-ss1** [comment]
> 供电不足？ 再加一路供电试试

不会吧？我用coreelec时候挂载移动硬盘都没问题

**Comment by ophub** [comment]
磁盘什么格式的？容量多大？

**Comment by xcray** [comment]
> > 供电不足？ 再加一路供电试试
> 
> 不会吧？我用coreelec时候挂载移动硬盘都没问题

反正我用硬盘底座，只能由独立电源供电的那种，从来没出过问题，也是JMicron。
并且你截图里显示这个设备一直在重启，挺像供电不足的。

**Comment by zhang-ss1** [comment]
> 磁盘什么格式的？容量多大？电源几安？

ext4，2.5寸250g机械、120gssd，2.5a的，感谢大佬回复，用外置供电的硬盘盒就正常了，再次感谢大佬的固件！！

**Comment by zhang-ss1** [comment]
> > > 供电不足？ 再加一路供电试试
> > 
> > 
> > 不会吧？我用coreelec时候挂载移动硬盘都没问题
> 
> 反正我用硬盘底座，只能由独立电源供电的那种，从来没出过问题，也是JMicron。 并且你截图里显示这个设备一直在重启，挺像供电不足的。

感谢大佬！用外置供电的硬盘盒就正常了，之前换了好几个没有外置供电的都不能正常挂载

**Comment by ophub** [comment]
cm311-1a-ch和cm311-1a-YST是不同的盒子？你的armbian 分区格选择的ext4还是btrfs？你看过你的安卓系统分区表吗？

**Comment by MDCY9008** [comment]
> cm311-1a-ch和cm311-1a-YST是不同的盒子？你的armbian 分区格选择的ext4还是btrfs？你看过你的安卓系统分区表吗？

一个是长虹代工，一个是易视腾的。

**Comment by zhang-ss1** [comment]
> cm311-1a-ch和cm311-1a-YST是不同的盒子？你的armbian 分区格选择的ext4还是btrfs？你看过你的安卓系统分区表吗？

区别应该不大吧，我都是刷的yst的固件，armbian选的btrfs，没看过分区表，armbian现在用着没啥问题，除了那个移动硬盘需要外界供电，重启/关机试了多次也正常

**Comment by MDCY9008** [comment]
> 好吧，一会要再更新一下分区大小。这事真愁人，如果更新是正确的，那你现在刷的就应该是错的，那怎么就不给报点错呢？这不科学啊

昨天的版本额外偏移了100MB，理论上貌似只有4MB落在了不安全区域。

**Comment by MDCY9008** [comment]
> 好吧，一会要再更新一下分区大小。这事真愁人，如果更新是正确的，那你现在刷的就应该是错的，那怎么就不给报点错呢？这不科学啊

昨天额外偏移了100MB，按照今天的分区表计算，rootfs我算下来貌似只有44MB在不安全区域。

**Comment by xcray** [comment]
> 好吧，一会要再更新一下分区大小。这事真愁人，如果更新是正确的，那你现在刷的就应该是错的，那怎么就不给报点错呢？这不科学啊

是有这种情况，不看dmesg的话都意识不到有问题。我之前有一次刷完之后各种操作都很顺畅，当然更多的是再之前的几次刷机，apt、armbian-software都会报错。

楼主可以看看dmesg grep -i btrfs有没有错误信息

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/deb3ffbd69891d04d44c301dc54757785e0bc602

刚更新了。

**Comment by zhang-ss1** [comment]
> > 好吧，一会要再更新一下分区大小。这事真愁人，如果更新是正确的，那你现在刷的就应该是错的，那怎么就不给报点错呢？这不科学啊
> 
> 是有这种情况，不看dmesg的话都意识不到有问题。我之前有一次刷完之后各种操作都很顺畅，当然更多的是再之前的几次刷机，apt、armbian-software都会报错。
> 
> 楼主可以看看dmesg grep -i btrfs有没有错误信息

![2](https://user-images.githubusercontent.com/74695580/187221115-825c823b-63b7-4665-8a26-7600d79f0283.png)
![3](https://user-images.githubusercontent.com/74695580/187221128-d9954b83-ec8f-4ce9-9076-1b5c23b26b29.png)
