### ISSUE TITLE
中兴B863AV3.2M获取不了IP

### ISSUE THREAD

**Issue by ngwk1984** [ophub/amlogic-s9xxx-armbian#524]
配置跟900V22C一样，我是先刷ROOT的安卓TV，ADB刷armbian的，也设置不了静态IP

**Comment by cmxjs** [comment]
cm311-1a, unt403a也会出现这个问题。随机性的获取不到ip，需要拔插网线。

**Comment by xcray** [comment]
推荐这个：
https://github.com/ophub/amlogic-s9xxx-armbian/issues/421#issuecomment-1221550664

虽不是除根的方案，但是很实用

**Comment by mia0x75** [comment]
@ngwk1984 请问中兴B863AV3.2M的详细刷机教程哪里有？谢谢。

**Comment by mia0x75** [comment]
@xcray 试了 #557 的好几种办法还是不行。

`no phy at addr -1
stmmac_open Cannot attach to PHY (error: -19)`

搜了issue，好像22C、22D、B863AV3.2都有这个问题。

**Comment by Haaooo** [comment]
> > @xcray 试了 #557 的好几种办法还是不行。
> > `no phy at addr -1 stmmac_open Cannot attach to PHY (error: -19)`
> > 搜了issue，好像22C、22D、B863AV3.2都有这个问题。
> 
> 根本就不是一码事啊！
> 
> 你这是另外一个问题：没认出网卡。我说的是认出网卡但必须拔插网线的问题。
> 
> 认不出网卡，可以通过改dtb、使用overload u-boot解决。

同问有没有教程

**Comment by xcray** [comment]
都不会自己看么？？？
https://github.com/ophub/amlogic-s9xxx-armbian/issues/663
