### ISSUE TITLE
Vontar X92 adds bluetooth, wireless and led support

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#525]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
The X92 S912 3GB 16GB TV box boots with  the meson-gxm-vega-s96 DTB file but i could not get the front LCD working on the front. 

Used configuration file for openVFD: 
https://github.com/LibreELEC/linux_openvfd/blob/master/conf/meson-gxm-x92.conf

Error: 
line 105, cannot open / find file   LED_on. 

Additional information: 
- I add the DTB's that i exported from the original android 7 rom and gave me 2 exports. 
I tried to boot from these DTB's using an working image but it wont boot. 
Could these be modified to be working with Armbian using your methods? 

Model i got:   S912, 3GB RAM, 16GB eMMC, AP6255 BT - WIFI, Realtek 8211f gigabit

[DTB.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9446557/DTB.zip)

**Comment by ophub** [comment]
`meson-gxm-vega-s96.dtb`
You use this file, wired, wireless, bluetooth are normal? Just no led display, right?

**Comment by ophub** [comment]
[meson-gxm-x92.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9448906/meson-gxm-x92.dtb.zip)

**Comment by d5stick** [comment]
Hi Ophub, 

Thanks for the quick reply and your time. 

Box link: https://nl.aliexpress.com/i/32734559342.html
Some other links: https://cheap-sale.outletsale2022.ru/category?name=x92%20smart%20tv%20box

Tested the second DTB with bluetooth. Boots like a charm with Wifi and Ethernet working.  Still need to test bluetooth. 

Kernel  5.15.62 is used for the build, which works. Other kernels will be tested later today. I had no luck with them in the past using the 96 vega DTB. 

FD628 is the chip controlling the led panel 
I updated the LED configuration and armbian LED and it does not generate the errors anymore when executing the commands. 
The LED panel itself stays off.  Is there any log file i can retrieve by this script? 

```

        ┌────────[ Enable LED ]─────────┐
        │                               │
        │    11. x96max (s905x2)        │
        │    12. x96maxplus (s905x3)    │
        │    13. x96air (s905x3)        │
        │    14. h96max-x3 (s905x3)     │
        │    15. hk1-x3 (s905x3)        │
        │    16. hk1box (s905x3)        │
        │    17. tx3 (s905x3)           │
        │    18. tx3-mini (s905w)       │
        │    19. t95 (s905x)            │
        │    20. tx9-pro (s912)         │
        │    99. diy                    │
        │                               │
        ├──────[ Other Operations ]─────┤
        │                               │
        │    -u. update                 │
        │     0. stop                   │
        │     1. quit                   │
        │                               │
        └───────────────────────────────┘

[ OPTIONS ] Please Input ID: 21
[ STEPS ] Start the led screen display...
[ INFO ] Using LED Profiles: /usr/share/openvfd/conf/x92.conf
[ INFO ] turn led alarm on ...
[ INFO ] turn led usb on ...
[ INFO ] turn led play on ...
[ INFO ] turn led pause on ...
[ INFO ] turn led lan on ...
[ INFO ] turn led wlan on ...
[ INFO ] turn led sd on ...
[ INFO ] turn led hdmi on ...
[ INFO ] turn led cvbs on ...
[ SUCCESS ] Enable LED display!
pi@armbian:~$

```

**Comment by ophub** [comment]
This dtb is only applicable to 5.15.62, it may not work properly under the 5.10 kernel, you only need to test 5.15.62, the wired network card, wireless, bluetooth, led display these four can work normally, after the test is passed I will add in other kernels.

You have now determined that the `wired`, `wireless` and `led screens` can be used `normally`?

To turn on bluetooth, you need to `install bluetooth` in `armbian-config` first

**Comment by d5stick** [comment]
Hi, 

The kernel 5.15.62 works with bluetooth(Thanks for the input, installed it), wifi and gigabit.  

The LED is not working, but it does not give me any error message. It just does not light up. 
Is there any log file available to look into? 


Writing to EMMC is not happening: 
`root@armbian:/usr/sbin# armbian-install
[ STEPS ] Start install armbian to emmc...
[ STEPS ] Start initializing the environment...
[ ERROR ] No emmc can be found to install the armbian system!
`

`root@armbian:/boot# armbian-ddbr
[ STEPS ] Welcome to use the EMMC system backup/restore service.
[ INFO ] The device name: [ X92 Smart Box ]
[ ERROR ] No emmc can be found to install the openwrt system!
`

I know i was able with the original S912 build from Armbian 20.10

I am running stock Android 7 on the EMMC at this moment.

**Comment by ophub** [comment]
screenshot the result of this command: `lsblk`

**Comment by d5stick** [comment]
The SDCard is 8GB.

```
root@armbian:~# lsblk
NAME        MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
mmcblk1     179:0    0  7.6G  0 disk
├─mmcblk1p1 179:1    0  255M  0 part /boot
└─mmcblk1p2 179:2    0  6.8G  0 part /var/log.hdd
                                     /
mmcblk2     179:32   0 14.4G  0 disk
zram0       254:0    0  1.4G  0 disk [SWAP]
zram1       254:1    0   50M  0 disk /var/log
zram2       254:2    0  1.4G  0 disk /var/tmp
root@armbian:~#
```

**Comment by ophub** [comment]
![Snip20220830_2](https://user-images.githubusercontent.com/68696949/187396668-70f20bc1-da4c-42ca-b324-c1ad6ed796fb.png)

The script is looking for this installment of `mmcblk2boot0`

**Comment by ophub** [comment]
`armbin-sync`: Synchronize the local script and test the `led`
`armbian-led`: `21`

**Comment by d5stick** [comment]
`root@armbian:~# sudo armbian-sync
[ STEPS ] Start syncing all service scripts...
[ STEPS ] Start syncing operation instruction and service script...
A    /usr/sbin
A    /usr/sbin/armbian-ddbr
A    /usr/sbin/armbian-docker
A    /usr/sbin/armbian-fix
A    /usr/sbin/armbian-install
A    /usr/sbin/armbian-kernel
A    /usr/sbin/armbian-led
A    /usr/sbin/armbian-software
A    /usr/sbin/armbian-swap
A    /usr/sbin/armbian-sync
A    /usr/sbin/armbian-tf
A    /usr/sbin/armbian-update
A    /usr/sbin/balethirq.pl
Exported revision 6011.
[ STEPS ] Start syncing software service script...
A    /usr/share/ophub
A    /usr/share/ophub/armbian-software
A    /usr/share/ophub/armbian-software/201-desktop-chinese-fonts.sh
A    /usr/share/ophub/armbian-software/301-frps.sh
A    /usr/share/ophub/armbian-software/302-frpc.sh
A    /usr/share/ophub/armbian-software/command-desktop.sh
A    /usr/share/ophub/armbian-software/command-docker.sh
A    /usr/share/ophub/armbian-software/command-service.sh
A    /usr/share/ophub/armbian-software/software-command.sh
A    /usr/share/ophub/armbian-software/software-list.conf
Exported revision 6011.
[ STEPS ] Start syncing openvfd service script...
A    /usr/share/openvfd
A    /usr/share/openvfd/conf
A    /usr/share/openvfd/conf/h96max-x3.conf
A    /usr/share/openvfd/conf/hk1-x3.conf
A    /usr/share/openvfd/conf/hk1box.conf
A    /usr/share/openvfd/conf/t95.conf
A    /usr/share/openvfd/conf/tx3-mini.conf
A    /usr/share/openvfd/conf/tx3.conf
A    /usr/share/openvfd/conf/tx9-pro.conf
A    /usr/share/openvfd/conf/x92.conf
A    /usr/share/openvfd/conf/x96air.conf
A    /usr/share/openvfd/conf/x96max.conf
A    /usr/share/openvfd/conf/x96maxplus.conf
A    /usr/share/openvfd/vfdservice
Exported revision 6011.

[ SUCCESS ] All service scripts are synchronized successfully.
`


```

        ┌────────[ Enable LED ]─────────┐
        │                               │
        │    11. x96max (s905x2)        │
        │    12. x96maxplus (s905x3)    │
        │    13. x96air (s905x3)        │
        │    14. h96max-x3 (s905x3)     │
        │    15. hk1-x3 (s905x3)        │
        │    16. hk1box (s905x3)        │
        │    17. tx3 (s905x3)           │
        │    18. tx3-mini (s905w)       │
        │    19. t95 (s905x)            │
        │    20. tx9-pro (s912)         │
        │    21. x92 (s912)             │
        │    99. diy                    │
        │                               │
        ├──────[ Other Operations ]─────┤
        │                               │
        │    -u. update                 │
        │     0. stop                   │
        │     1. quit                   │
        │                               │
        └───────────────────────────────┘

[ OPTIONS ] Please Input ID: 21
[ STEPS ] Start the led screen display...
[ INFO ] Using LED Profiles: /usr/share/openvfd/conf/x92.conf
[ SUCCESS ] Enable LED display!

```
No output on the display.

**Comment by ophub** [comment]
`/usr/share/openvfd/conf/x92.conf`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led_screen_display_control.md


This display requires you to continuously adjust these values according to the document, and the test is correct. I have added the LED display driver to the dtb.

**Comment by d5stick** [comment]
> The script is looking for this installment of `mmcblk2boot0`

What can i do with this, is this a bug in the Android build that i need to reflash or something within the Armbian build?




> `/usr/share/openvfd/conf/x92.conf`
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led_screen_display_control.md
> 
> This display requires you to continuously adjust these values according to the document, and the test is correct. I have added the LED display driver to the dtb.


I checked this, i saw that you updated the files which syncs ok.  Tried to modify the other values as mentioned in your transcript but it does not even light up at this point.

**Comment by ophub** [comment]
Your box is special. There is no corresponding value for this partition. If it is written to emmc, you need to manually change the script and bind the name of the emmc partition.

For the led, look at the instructions carefully, adjust the corresponding value, turn it off, turn it on, and test it repeatedly.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/a8fd732cb75622c75cb7cb2c8c6e5b4abd098031

I found that the function code was written less, it has been added, you use the synchronization function to update the local script: `armbian-sync`

`armbian-led 21`

**Comment by d5stick** [comment]
About the LED: 
Synced the files, shut it down, reopened it and the display does not show anything. Not sure where to look either besides the actions you provided in the readme.  

The only output i see is in the terminal on the HDMI port when shutting down a message pops up:  Brightness 0 with a random number in front of it.  The armbian-led command does not show any errors when being executed. Every try it reports LED enabled, but that is not the case. 

The android variant has the display working, do you know if the config openVFD file is in the build as i could try to extract it from the image to see if some configuration has to be done or if we are way off on how to enable it on the box in armbian. 

About writing to the emmc, the script that was original with armbian 20.10 could write to the emmc. I haven't checked that, will do that tomorrow to see what the difference is with the script armbian-install in accessing the emmc. Is the armbian-install script made by you or is this included by armbian itself? I can dive deeper in the script to see if we can add a value into it if the emmc "mmcblk2boot" is not found, that it could try to search for "mmcblk2".

What i also wanted to ask, is your script/workflow removing the desktop feature during the build? 
I made a fork and modified the compile.sh for armbian to add xfce desktop including some apps but it is not fully installed when deploying it onto the X92.  I have to manually do some tweaks to get it working.

**Comment by ophub** [comment]
I updated the `armbian-install` script to add looking for emmc without the `boot0` partition. You use `armbian-sync` to update the script on the local sd card.

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs

Read `12.3` and `12.10` carefully, make sure your partition location is correct, make sure your box has `xxx.img Android system image`, make sure you can restore Android system by yourself after the test fails. If you're all set, you can test write emmc
