### ISSUE TITLE
重新生成新的machine-id

### ISSUE THREAD

**Issue by MDCY9008** [ophub/amlogic-s9xxx-armbian#526]
目前MAC是随机的了，但是machine-id还都是一样的，而且在我的路由器上虽然U盘和emmc内系统的MAC不一样，但是DHCP分配的IP是一样的，不知道这是不是导致开机获取不到ip的间接原因，所以建议在```armbian-install```里增加这三条命令。

 cp -f /dev/null /etc/machine-id
 cp -f /dev/null /var/lib/dbus/machine-id
 systemd-machine-id-setup

**Comment by ophub** [comment]
/etc/network/interfaces

是模板的作用，为了各种网络设置参考。这个文件可以删除，系统会自动生成。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/052c671f212902d630f17dbac593b6f5ef75a0c7

添加到自动修复了，初次启动时自动执行，也可以手动执行

**Comment by acooler15** [comment]
[https://wiki.debian.org/MachineId](https://wiki.debian.org/MachineId)
```
rm -f /etc/machine-id /var/lib/dbus/machine-id
dbus-uuidgen --ensure=/etc/machine-id
dbus-uuidgen --ensure
```

**Comment by MDCY9008** [comment]
看了wiki，我的发现没错，改了MAC不改设备ID确实可能会导致路由器分配一样的IP，继发出现无法获取IP的问题。
![image](https://user-images.githubusercontent.com/54255527/187809299-9e2ecc75-10b6-479c-9507-cc7162b61329.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/c8a507f114e8fce0262673517bfb392eaffed630

感谢分享，已经按你发的官方文档进行了调整
