### ISSUE TITLE
想资讯一下cm311-1a 怎么刷armbian

### ISSUE THREAD

**Issue by bbhxwl** [ophub/amlogic-s9xxx-armbian#527]
想资讯一下cm311-1a 怎么刷armbian

**Comment by MDCY9008** [comment]
https://wz.wushu.work/

**Comment by ophub** [comment]
祥细说明你在哪一步操作遇到了什么问题

**Comment by loosebao** [comment]
> 祥细说明你在哪一步操作遇到了什么问题

311-1a刷22.11版 挂载不了硬盘是什么原因呢
老是识别不到sda1

**Comment by ophub** [comment]
大硬盘要额外给硬盘盒独立供电，使用UUID挂载，不要使用lable名字，挂载卸载fstab里
