### ISSUE TITLE
CM311-1a CPU 频率调节问题

### ISSUE THREAD

**Issue by yoyocat** [ophub/amlogic-s9xxx-armbian#529]
**Describe the bug**

在盒子里的Android系统，CPU可调节的最小频率是 100MHz，armbian里最小频率只能是 1GHz。用作家庭服务器，大部分时候是空载状态，如果可以用最低100MHz运行，将降低功耗，减少发热量，系统也更稳定。毕竟这个盒子散热不是太好。

实测用Android系统，修改CPU governor 为 schedutil，使其空载状态的频率600MHz左右，CPU温度50°C左右。比armbian的要低大概两三度。室温31°C。

```
# 查看频率范围
cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies

# 查看温度
cat /sys/class/thermal/thermal_zone0/temp
```

**Expected behavior**

空载时能低于 1GHz 运行。

**Armbian Version**
 - Armbian_22.08.0_Aml_s905l3a_bullseye_5.15.62_server_2022.08.30.img

**Device:**
 - CM311-1a 电视盒子

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-e900v22c.dts#L124

频率设置在内核里，你可以自己修改编译。

**Comment by MDCY9008** [comment]
具体修改数值可参考安卓DTS。
[android.dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9458920/android.dts.zip)

**Comment by yoyocat** [comment]
@ophub @MDCY9008 Errrrr, 大佬，这个要怎么改呢？装好的系统还能改吗？

**Comment by yoyocat** [comment]
还有，android.dts 有四千多行，为啥meson-g12a-s905l3a-e900v22c.dts才一百多行？

**Comment by ophub** [comment]
就1个dtb文件，每次更新内核都会替换掉，你自己编译完dtbs（3分钟编译完成），把你的这个文件覆盖下即可。

不用管反编译的安卓文件有多少行。你反编译armbian的dtb结果也是很多行。你看见的链接是源码，他引入的代码在其他文件里，当前文件只写了差异代码。

![Snip20220831_4](https://user-images.githubusercontent.com/68696949/187628140-7712f522-1762-462f-9ed9-a916312dfd10.png)

内核编译的方法见仓库的文档，自己fork内核源码，改完编译自己仓库的内核。
我见人们老想超频不断挑战上限，你是第一个找下限的人。
我不知道你会怎么改，改的是否合适，是否稳定。反正你心中已经种草了，不折腾你也睡不踏实，就放飞你的梦想吧，大不了重刷呗。

**Comment by yoyocat** [comment]
@ophub 谢谢大佬！我研究下。我希望它空闲的时候找下限，干活的时候找上限。😉 毕竟芯片本身支持低频，为啥不用呢？

这里故意禁掉了部分低频，去掉应该就行。只保留1.9GHz的超频就行。
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-e900v22c.dts#L125-L140

**Comment by MDCY9008** [comment]
我试了一下，温度没下降多少。

**Comment by ophub** [comment]
别都删了啊，那不成恒定频率了？
你添加个测试的下限就可以了。

**Comment by xcray** [comment]
1GHz及以下供电电压都是一样的，好像降频并不能减少发热。我设置最低频500、最高1800，温度没啥明显变化，倒是抖动似乎更明显了（变粗了）：
![image](https://user-images.githubusercontent.com/26018728/187639823-1406f934-ff2c-4185-95b9-6d027c810fab.png)
注：我用的是u200的dtb，最低可以设置到100MHz。

**Comment by ophub** [comment]
有折腾的想法，有实践的检验，有理论去解释，很完美

**Comment by yoyocat** [comment]
谢谢各位大佬，我再测试下。

> 温度没啥明显变化

难道是Android的功耗控制好一点。我昨天低频是在Android上测试的。

**Comment by MDCY9008** [comment]
![image](https://user-images.githubusercontent.com/54255527/187642043-374bf5f7-fa94-498d-8171-520ebfb1ae5b.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/default/cpufrequtils

CPU调频有好多种类型，你琢磨琢磨哪个能低功耗运行

**Comment by xcray** [comment]
u200的dtb在这方面和安卓的一样。按说比较节能又可以兼顾性能需求的策略就是conservative了，但是不降电压只降频率效果很不明显。

**Comment by yoyocat** [comment]
嗯，我目前用的 `conservative`，空闲的时候是用的最低频率。

> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/rebuild#L582-L585

> 这里的自启动删除试试，这个是f大开发的，为了追求极致的高性能。你反着来就删除了。

好的。我试试。

@xcray 确实，看来单纯的给CPU降频影响不大。从整个SoC考虑，也许Android的对其他的模块比如 GPU，网络模块的控制更好些，所以温度低些？我找机会还得试试Android。
