### ISSUE TITLE
T95z plus 3G + 32G

### ISSUE THREAD

**Issue by liaojianqiang** [ophub/amlogic-s9xxx-armbian#53]

**Comment by liaojianqiang** [comment]
你好，我的 T95z plus  是3G + 32G试了以下两个固件，网络都使用不了，有线 和wifi都不能正常使用。

Armbian_21.11.0_Aml_s912-t95z_bullseye_5.10.84_2021.12.13.0354.img.gz
 Armbian_21.11.0_Aml_s912-t95z_bullseye_5.4.164_2021.12.13.0356.img.gz

**Comment by ophub** [comment]
The solution for this box is provided by [NewbieOrange](https://github.com/NewbieOrange). You can ask him for advice. He is the only user known to use T95Z.

He provided the [meson-gxm-t95z-plus.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-dtb/meson-gxm-t95z-plus.dtb) file and [usage method](build-armbian/common-files/patches/boot/s912-t95z-plus) of the new device [T95Z-Plus](https://www.tokopedia.com/search?st=product&q=t95z%20plus) in [issues](https://github.com/ophub/amlogic-s9xxx-armbian/issues/22#issuecomment-968260448); Shared the [meson-gxl-s905l2-p281.dtb](build-armbian/amlogic-dtb/meson-gxl-s905l2-p281.dtb) file of s905l2 (p281 board) in [pull](https://github.com/ophub/amlogic-s9xxx-armbian/pull/29).

You can also test more dtb files of the same series of s912 in the [amlogic-dtb](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/amlogic-dtb)
