### ISSUE TITLE
cm 311-1a zg 系统直接烧入2.5寸500G机械硬盘外加易驱线无法启动

### ISSUE THREAD

**Issue by ENEN-YIN** [ophub/amlogic-s9xxx-armbian#530]
易驱线主控ASM225
外接12v 2a电源试过也不启动
但是插到usb2.0+100M网口的usb hub上成功启动，重启关机正常
直接插机顶盒usb跑码：
![TV_CAM_设备_20220831_133809 279](https://user-images.githubusercontent.com/81505595/187603291-98aca652-7a84-4802-96bc-cdd6c4bd27ca.jpg)
插usb2.0 hub跑码：

![TV_CAM_设备_20220831_133909 050](https://user-images.githubusercontent.com/81505595/187603393-b4ce4d7a-16b6-48ff-9e94-9817ead65b4f.jpg)
![TV_CAM_设备_20220831_133914 731](https://user-images.githubusercontent.com/81505595/187603861-341a4c61-7ca7-4a1f-8d05-41bf58110472.jpg)

**Comment by ophub** [comment]
大硬盘要外接硬盘盒电源

**Comment by ENEN-YIN** [comment]
易驱线外接12V 2a电源不能启动
插到usb hub(没外接电源）上启动正常
有点离谱，感觉不是电源的问题，有个群友试了七个硬盘盒/易驱线
能用的主控是：JMS567，NS1066,NS1068,不能用的是jms576，jms578，ASM225

**Comment by ophub** [comment]
缺驱动？

**Comment by ENEN-YIN** [comment]
不清楚 感觉应该不是
试了一个jsm576硬盘盒 amrbian启动后插入读取挂载正常 重启或者断电开机要重新插拔才能识别到 尝试过写入fstb自动挂载 也没用，有时还会无法进入amrbian

**Comment by xcray** [comment]
我之前也发现易驱线不好使，就是不能启动，加一路供电都不行。但启动后挂载读写都没问题。

只是没有试过加hub中转一下。

**Comment by liqiantu** [comment]
我也遇到过直接使用硬盘盒无论是ssd还是机械都引导不起来系统，但是后来使用usb 2.0的hub中转下，就一切正常了。
怀疑是使用硬盘盒在usb 3.0下有兼容性问题。

**Comment by ENEN-YIN** [comment]
选取硬盘盒可以参考这个
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8251847&highlight=cm311-1a
