### ISSUE TITLE
when I compile the code. It show me '[ ERROR ] The [ etc/os-release: ID ] is invalid.'

### ISSUE THREAD

**Issue by wds315** [ophub/amlogic-s9xxx-armbian#531]
When I compile the code in local, It shows me '[etc/release:ID](cat: etc/os-release: No such file or directory)'

This is the command:
sudo ./rebuild -d -b s905l3a -a true

return message:

[ INFO ] Welcome to Rebuild Armbian for Amlogic s9xxx tv box!
[ INFO ] Server running on Ubuntu: [ Release: jammy / Host: x86_64 ]

[ INFO ] Server CPU configuration information:
      4  Intel(R) Xeon(R) CPU E5-2696 v2 @ 2.50GHz

[ INFO ] Server memory usage:
               total        used        free      shared  buff/cache   available
Mem:           7.7Gi       328Mi       127Mi       1.0Mi       7.3Gi       7.1Gi
Swap:          4.0Gi       0.0Ki       4.0Gi

[ INFO ] Server space usage before starting to compile:
Filesystem     Type  Size  Used Avail Use% Mounted on
/dev/sda2      ext4   49G   36G   11G  77% /

[ INFO ] Setting parameters: [ -d -b s905l3a -a true ]

[ INFO ] Armbian rebuild file: [ Armbian_22.08.0_Aml_s905l3a_bullseye_5.15.62_server_2022.08.21.img ], Version: [ 22.08.0 ]
[ INFO ] (1) Auto query the latest kernel version of the same series for [ 5.10.125 ]
[ INFO ] (1) [ 5.10.139 ] is latest kernel.

[ INFO ] (2) Auto query the latest kernel version of the same series for [ 5.15.50 ]
[ INFO ] (2) [ 5.15.62 ] is latest kernel.

[ INFO ] (1) [ 5.10.139 ] Kernel is in the local directory.
[ INFO ] (2) [ 5.15.62 ] Kernel is in the local directory.
[ INFO ] Armbian SoC List: [ s905l3a  ]
[ INFO ] Kernel List: [ 5.10.139 5.15.62  ]
[ INFO ] ROOTFS Type: [ ext4 ]

(1.1) Start building Armbian [ s905l3a - 5.10.139 ]. Remaining space is 11G.
 [ s905l3a - 5.10.139 ]  (1/6) Confirm version type.
 [ s905l3a - 5.10.139 ]  (2/6) Extract old armbian files.
cat: etc/os-release: No such file or directory
[ ERROR ] The [ etc/os-release: ID ] is invalid.

I thought it must lost etc/os-release. But I found the file in my local computer that is ubuntu 22.04 x64 server. I checked the directory ~/amlogic-s9xxx-armbian/build-armbian/common-files/rootfs/etc. I can NOT find os-release. So I copy the file here from my U-disk that works well in my TV-box.  Unfortunately I got the ERROR again. Could you tell how to fix it? Thanks a lot

**Comment by ophub** [comment]
Armbian image ( Eg: Armbian_21.11.0-trunk_Odroidn2_current_5.15.50.img ) 

The file you are using is not the original file
