### ISSUE TITLE
S905L3A，无法识别自带网卡？

### ISSUE THREAD

**Issue by iydme** [ophub/amlogic-s9xxx-armbian#532]
hello大神好，
中兴B863AV3.2M 2+8G，无WiFi，带蓝牙
可以跟e900v22c所有固件都通刷
按照教程先刷了e900v22c,然后用U盘启动了armbian
armbian也成功安装到了emmc
蓝牙正常，自带有线网卡识别不了
网卡功能正常。
有什么办法解决指导一下

**Comment by ophub** [comment]
有线网卡芯片代码发下

**Comment by ngwk1984** [comment]
> hello大神好， 中兴B863AV3.2M 2+8G，无WiFi，带蓝牙 可以跟e900v22c所有固件都通刷 按照教程先刷了e900v22c,然后用U盘启动了armbian armbian也成功安装到了emmc 蓝牙正常，自带有线网卡识别不了 网卡功能正常。 有什么办法解决指导一下

同样情况

**Comment by xcray** [comment]
网卡不识别就写emmc啦？勇士啊！

硬件识别不正确，无非就是dtb、内核、uboot三者组合没选对，建议先用U盘试好了再写入emmc。

首先用5.4或5.15的内核，不需要uboot，先把dtb和内核小版本号找好。

5.10/5.19就需要uboot了，闹不好U盘启动正常写到emmc不启动（不认emmc），只能试了，或者就用5.4/5.15内核。
