### ISSUE TITLE
希望添加迅雷为常用软件

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#533]
https://github.com/cnk3x/xunlei
这个从DSM提取出来的迅雷插件，测试可以在armbian上面跑，速度还不错

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/13fe9a84e65111c64010bc3f5217a8166173bba8

已经添加，使用armbian-sync可以同步更新软件中心脚本，就可以使用了，编号120
