### ISSUE TITLE
关于在“docker 中使用 OpenWrt 建立互通网络” 疑问

### ISSUE THREAD

**Issue by Yxini** [ophub/amlogic-s9xxx-armbian#535]
**Armbian Version**
 - Kernel Version:5.15.62
 - Release:  jammy
 - Edition: server

**Device:CM311-1A
 - SOC: S095L3A

![图片](https://user-images.githubusercontent.com/47093205/188045865-afea83eb-aeef-4e93-90e9-5765c1967834.png)

这里的“其中的 MAC 地址根据自己的需要修改。”请问是修改哪里的MAC地址？

**Comment by ophub** [comment]
12:34:56:78:9a:bc
不会改就保存默认即可

**Comment by Yxini** [comment]
好的 谢谢
