### ISSUE TITLE
Is there any way to install openzfs without recompiling the kernel?

### ISSUE THREAD

**Issue by jiderlesi** [ophub/amlogic-s9xxx-armbian#536]
I'm tryna to install openzfs on my Phicomm N1 by doing `sudo apt install zfsutils-linux`, it return those code:

`zfs-import-scan.service is a disabled or a static unit, not starting it.
Job for zfs-load-module.service failed because the control process exited with error code.
See "systemctl status zfs-load-module.service" and "journalctl -xe" for details.
A dependency job for zfs-import-cache.service failed. See 'journalctl -xe' for details.`

then I trynna to manually load the mod by `sudo /sbin/modprobe zfs`, it show me `modprobe: FATAL: Module zfs not found in directory /lib/modules/5.15.58-flippy-75+o`

Also, the zpool and zfs not work `The ZFS modules are not loaded.`

Is there any easy way to install zfs?

**Comment by ophub** [comment]
I haven't used it and don't know about it
You can check the information to see what support needs to be enabled in the kernel, and compile the kernel that suits him.
