### ISSUE TITLE
魔百盒905L3b Memory Limit:none

### ISSUE THREAD

**Issue by zailaib** [ophub/amlogic-s9xxx-armbian#537]
### 魔百盒905L3b

家里有两台在吃灰，不觉有些浪费
网文不怎么靠谱
没有刷成功

https://users.armbian.com/balbes150/arm-64/
用了这个img
Armbian_20.10_Arm-64_buster_current_5.9.0.img
修改/boot分区中u-boot-s905x-s912为u-boot.ext
用了905xp212的dtb

发生了和 https://forum.armbian.com/topic/18854-armbian-on-b860av21-m-with-s905l3-b/
这里一样的问题

```
[    9.989011]  do_el0_svc+0x24/0x90
[    9.989012]  el0_sync_handler+0x180/0x2f8
[    9.989014]  el0_sync+0x158/0x180
[    9.989038] SMP: stopping secondary CPUs
[    9.989039] Kernel Offset: disabled
[    9.989041] CPU features: 0x0040002,20002004
[    9.989042] Memory Limit: none

```

折腾了几个周末没有什么进展
不知道什么原理
o大时候能b站开课啥的 我来投币呢 哈哈

**Comment by ophub** [comment]
L3A可用，L3B还不支持
暑假作业没写完被老师罚值日一周，再b站看看我连职高也考不是了

**Comment by zailaib** [comment]
天真的我以为你真是要写作业的主子

**Comment by ophub** [comment]
再不写得叫家长了。听老师的话，好好学习天天向上

**Comment by ophub** [comment]
再不写得叫家长了。听老师的话，好好学习天天向上

**Comment by janko888** [comment]
l3b的话，用Armbian_5.97_Aml-g12_Ubuntu_disco_default_5.3.0_20190923.img.xz这个固件，使用p212dtb,看看是否可用，hdmi是没有的，有线网卡默认不能用，外置usb网卡吧

**Comment by ling1042133624** [comment]
我也是S905L3b，刷了一个星期刷不进去。没有dtb。网上的教程，改的dtb用不了

**Comment by allonmymind** [comment]
> l3b的话，用Armbian_5.97_Aml-g12_Ubuntu_disco_default_5.3.0_20190923.img.xz这个固件，使用p212dtb,看看是否可用，hdmi是没有的，有线网卡默认不能用，外置usb网卡吧

我找到个能识别网卡的固件，但是docker运行报错。弄这个型号太折腾了

**Comment by ling1042133624** [comment]
> > l3b的话，用Armbian_5.97_Aml-g12_Ubuntu_disco_default_5.3.0_20190923.img.xz这个固件，使用p212dtb,看看是否可用，hdmi是没有的，有线网卡默认不能用，外置usb网卡吧
> 
> 我找到个能识别网卡的固件，但是docker运行报错。弄这个型号太折腾了

咦，什么固件，分享一下。docker我熟啊

**Comment by zailaib** [comment]
我觉得这个issue可以继续评论， 因为3b的还是不行，更何况有个 o大需要写作业的证明 😄

**Comment by janko888** [comment]
> 我觉得这个issue可以继续评论， 因为3b的还是不行，更何况有个 o大需要写作业的证明 😄

你使用armbian_aml_s905l2_*.img,,dtb选择meson-gxl-s905l3b-m302a试试。
无hdmi显示；
我m302a测试的情况:
安卓9固件加5.15.x\6.0.x内核网卡可以正常使用；
安卓4固件加6.0.x内核，（部分版本盒子）网卡可以正常使用；
