### ISSUE TITLE
Armbian_Aml_bullseye_08.27.0755_s905x3_bullseye安装omv出错记录

### ISSUE THREAD

**Issue by jack338c** [ophub/amlogic-s9xxx-armbian#538]
用armbian software安装方式
安装过程中出现一些错误
Failed to stop ntp.service: Unit ntp.service not loaded.
Unit ntp.service does not exist, proceeding anyway.
Created symlink /etc/systemd/system/ntp.service → /dev/null.
Failed to stop systemd-timesyncd.service: Unit systemd-timesyncd.service not loaded.
Unit systemd-timesyncd.service does not exist, proceeding anyway.

[WARNING ] /usr/lib/python3/dist-packages/salt/utils/files.py:396: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage

Processing triggers for initramfs-tools (0.140) ...
ln: failed to create hard link '/boot/initrd.img-5.10.138-ophub.dpkg-bak' => '/boot/initrd.img-5.10.138-ophub': Operation not permitted
update-initramfs: Generating /boot/initrd.img-5.10.138-ophub

estarting engine daemon ...
Updating workbench configuration files ...
[ERROR   ] Command 'timedatectl' failed with return code: 1
[ERROR   ] stderr: Failed to query server: Connection timed out
[ERROR   ] retcode: 1
Error running 'timezone.get_zone': timedatectl failed: Failed to query server: Connection timed out
Downloading omv-extras.org plugin for openmediavault 6.x ...

Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8; export LANGUAGE=; omv-salt deploy run --no-color samba 2>&1' with exit code '1': armbian:

进omv-web后台点服务-smb/cifs-共享启用后就出现截图错误
![Screen Shot 2022-08-28 at 2 32 04 PM](https://user-images.githubusercontent.com/10782586/188293966-e768e8b5-6794-4e3a-b660-8f349e501052.png)

然后一旦重启后机器就无法再联网
不知道出错的原因在哪里，请大神帮看下

谢了！

**Comment by ophub** [comment]
https://forum.openmediavault.org/index.php?board/16-cifs-smb/

到他的官方论坛咨询下吧，omv的安装使用的是官方一键脚本。

**Comment by jack338c** [comment]
好的，非常感谢！
我等下装和你一样22.080.linx5.10.140-ophub-s905x3这个固件试试

**Comment by ophub** [comment]
https://forum.openmediavault.org/index.php?thread/44277-error-500-internal-server-error/

不需要为了一个错误重装，他的官方论坛分类很细，SMB分区里我看到很多关于使用的问题，这个看似和你的一样？你翻翻论坛的帖子看看大家怎么设置和解决的问题，问问大家

**Comment by jack338c** [comment]
好的，感谢！

**Comment by AlexBokhankovich** [comment]
@ophub Can you please check if timedatectl works properly on your box after OMV is installed and box is rebooted?
I tried many times installing OMV and every install failed with timedatectl errors. Even resonv.conf is broken after reboot. I'm not sure if it is related to aml armbian port but nothing found on amv forum related to this issue makes me think it could be a port related

**Comment by jack338c** [comment]
@AlexBokhankovich 
actually,I tried 22.080.linx5.10.140-ophub-s905x3 for OMV,but it still has same issues.
I now use it only for samba share,it's perfect

**Comment by AlexBokhankovich** [comment]
@AlexBokhankovich thank you for the information. I'll try to ask on OMV forum maybe there is a solution

**Comment by Amychan67899123** [comment]
你好，我也遇上了这个错误。我采用的是09.01的Armbian_Aml_bullseye固件包。
使用omv的官方安装指导文档https://docs.openmediavault.org/en/6.x/installation/on_debian.html，替换了清华源镜像后，安装过程一切顺利，能打开web端的OMV6
登录进入web端后无法应用保存任何设置。提示错误类似，500  internal sever Error。
Failed to execute command 'export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin; export LANG=C.UTF-8;

从omv论坛上反应似乎是内核问题，所以我到这里来反馈了。

**Comment by Amychan67899123** [comment]
> @AlexBokhankovich actually,I tried 22.080.linx5.10.140-ophub-s905x3 for OMV,but it still has same issues. I now use it only for samba share,it's perfect
看来我们的情况一致，现在我也使用samba解决共享问题。但是还是喜欢omv的可视化挂载。我今天跟其他人交流过，应该是引用位置出了差错，我再尝试最后一次，期待我的消息~~~

**Comment by ophub** [comment]
> 从omv论坛上反应似乎是内核问题，所以我到这里来反馈了。

内核里少什么选择？

**Comment by Amychan67899123** [comment]
> https://forum.openmediavault.org/index.php?thread/44277-error-500-internal-server-error/
> 
> 不需要为了一个错误重装，他的官方论坛分类很细，SMB分区里我看到很多关于使用的问题，这个看似和你的一样？你翻翻论坛的帖子看看大家怎么设置和解决的问题，问问大家
> 
> ![Snip20220904_10](https://user-images.githubusercontent.com/68696949/188296975-078f4918-df58-4325-b236-a5a7fb488346.png)
> 
> OMV的服务是使用的官方一键脚本安装的，你碰到的问题不会是唯一的，到论坛多看看。

你好，我已经完全重装了[Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.62_server_2022.09.05.img.gz]此固件，即使全新系统后立刻按照omv6官方指导说明完成安装，一样出现如楼主截图报错。

另：此固件包里的自带的armbian-software：307 OMV，提示not found没能安装。

我没有其他机器来尝试5.10版本，所以还是不知道问题出在哪里。：）

**Comment by ophub** [comment]
好的，如果验证omv的这个官方一键脚本安装有问题，我暂时先移除这个软件吧

**Comment by jack338c** [comment]
@ophub 
大神，方便提供一个Debian 10 (Buster)的固件吗，可以给OMV 5.x 用
或者给个自己搞个这样的固件思路？
多谢！

**Comment by ophub** [comment]
f大百度盘里是buster

**Comment by jack338c** [comment]
@ophub 
我下载了Armbian_20.10_Aml-s9xxx_buster_5.10.26-flippy-56+
按平时刷机方法行不通，不知道是不是操作方法问题
![Screen Shot 2022-09-07 at 5 04 58 PM](https://user-images.githubusercontent.com/10782586/188838648-023860b1-1cd0-4d37-8972-1f17fe90e382.png)

**Comment by jack338c** [comment]
@ophub 
我应该先在网上搜索下f大这个教程的
谢谢你～

**Comment by jack338c** [comment]
@ophub 暂时可以用，接下还不知道会怎么样，感谢！
![Screen Shot 2022-09-08 at 4 18 23 PM](https://user-images.githubusercontent.com/10782586/189072316-f7165ab5-d3f9-46d3-bc03-f71807b1be9b.png)
![Screen Shot 2022-09-08 at 4 17 33 PM](https://user-images.githubusercontent.com/10782586/189072331-bedbb6d7-5ca1-42e7-9fe1-af36563ecf02.png)

**Comment by ophub** [comment]
好的，看来5.0挺成熟

**Comment by jack338c** [comment]
H96 MAX  4+64

**Comment by ophub** [comment]
```
ls /usr/lib/u-boot/
ls /boot
```
把你固件里这2个位置的文件截图发下。

**Comment by jack338c** [comment]
![Screen Shot 2022-09-08 at 4 48 02 PM](https://user-images.githubusercontent.com/10782586/189078515-2c546b8c-649d-49d9-9603-8cf01ff7bbdb.png)

**Comment by ophub** [comment]
如果要升级内核到最新版本的话，需要补充下u-boot文件，就可以使用armbian-update方便更新了，或者你参照他网盘里的教程手动安装内核。

**Comment by jack338c** [comment]
@ophub 好的，多谢！
