### ISSUE TITLE
CM311-1A WIFI问题

### ISSUE THREAD

**Issue by z-xheng** [ophub/amlogic-s9xxx-armbian#539]
你好大佬
我刷入Armbian_22.08.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.01.img.gz 的包，wifi没识别到，原来在安卓系统上能正常使用的
WIFI是RTL8822CS，直接加装在板子上的，不是插的USB。
是驱动不支持吗，我该怎么操作？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.15#L3004

试试：`modprobe 88x2cs`

**Comment by z-xheng** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by z-xheng** [comment]
好的，大佬，我晚上回去试一下

**Comment by lovelylain** [comment]
@ophub openwrt的驱动加载机制，必须启动时就全部加载吗，能不能像armbian一样按需加载？在安卓和armbian上lsmod没多少模块，但是openwrt上有一大堆，有很多是绝大多数时候用不上的驱动。

**Comment by z-xheng** [comment]
![1 (2)](https://user-images.githubusercontent.com/34154531/188450696-15347b78-fe80-4e02-8454-e9c407987bb4.jpg)
我试了下，还是不行

**Comment by ophub** [comment]
那就放弃吧

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/778ee250e6f78f68718100fc211ed337f5d193cb/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts#L186

半年前x96max+里面添加过8822cs的无线驱动，有些人反馈在openwrt的无线里可以正常使用，但也有人反应会卡，有人说启用不了。这个驱动不太稳定，你想折腾可以自己在dtb里添加编译试试。

之前反馈这个盒子的无线是uwe5621ds

**Comment by QGB** [comment]
root@aml:~# find /usr/lib/modules
find: '/usr/lib/modules': No such file or directory

**Comment by z-xheng** [comment]
@ophub 感谢

**Comment by allonmymind** [comment]
> @ophub 感谢

试试5.10的固件，8723ds死活认不到Wi-Fi,换5.10秒认

**Comment by ophub** [comment]
你看一下config里面，难道5.15没选择启用？

**Comment by allonmymind** [comment]
> 你看一下config里面，难道5.15没选择启用？
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config
> 
> 
> 
> 你说的是哪个驱动？

![image](https://user-images.githubusercontent.com/18719713/190614339-70eed495-4e51-4f12-986b-7e5f572c0cf9.png)

我说的是rtl8723ds，配置里都是m

**Comment by ophub** [comment]
m就是预编译上了，用时按需加载

**Comment by allonmymind** [comment]
> m就是预编译上了，用时按需加载

加载不出来，识别不到网卡，昨天看了别人的issue 试了下balbed150的5.9版本秒认，今天换你的5.10也是自动就试别了

**Comment by Jencken-Wang** [comment]
> 你好大佬 我刷入Armbian_22.08.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.01.img.gz 的包，wifi没识别到，原来在安卓系统上能正常使用的 WIFI是RTL8822CS，直接加装在板子上的，不是插的USB。 是驱动不支持吗，我该怎么操作？

你好，后面有找到解决办法了吗

**Comment by allonmymind** [comment]
> > 你好大佬 我刷入Armbian_22.08.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.01.img.gz 的包，wifi没识别到，原来在安卓系统上能正常使用的 WIFI是RTL8822CS，直接加装在板子上的，不是插的USB。 是驱动不支持吗，我该怎么操作？
> 
> 
> 
> 你好，后面有找到解决办法了吗@z-xheng

用5.10内核

**Comment by Jencken-Wang** [comment]
> 

 还是不行，5.10的固件或者命令替换成5.10的内核都检测不到wifi，命令我是按教程执行的armbian-update 5.10.147 stable yes，
iwconfig没有无线信息，armbian-config 的network里面没有无线那一项

**Comment by Jencken-Wang** [comment]
> 用5.10内核

还是不行，5.10的固件或者命令替换成5.10的内核都检测不到wifi，命令我是按教程执行的armbian-update 5.10.147 stable yes，
iwconfig没有无线信息，armbian-config 的network里面没有无线那一项

**Comment by z-xheng** [comment]
> > 你好大佬 我刷入Armbian_22.08.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.01.img.gz 的包，wifi没识别到，原来在安卓系统上能正常使用的 WIFI是RTL8822CS，直接加装在板子上的，不是插的USB。 是驱动不支持吗，我该怎么操作？
> 
> 你好，后面有找到解决办法了吗@z-xheng

没有，我刷coreelec了，这个是能正常用的

**Comment by ruleechen** [comment]
亲测这里的CoreELEC：“4月16日更新21.0-1版”，WIFI和蓝牙都可用
https://www.right.com.cn/forum/thread-8281656-1-1.html

有大佬能继续研究下这个问题吗？或是提供一下思路

**Comment by ophub** [comment]
ce是安卓系统，安卓系统有驱动。

**Comment by ruleechen** [comment]
> ce是安卓系统，安卓系统有驱动。

是不是目前这里的build都是没包含8822cs驱动的？

**Comment by ruleechen** [comment]
看到几个旧的8822cs driver repo都说 ** USE RTW88 NOT THIS DRIVER **，应该是这个 https://github.com/lwfinger/rtw88

**Comment by ruleechen** [comment]
这代表有支持了，对的吧？
<img width="442" alt="image" src="https://github.com/ophub/amlogic-s9xxx-armbian/assets/907369/a0aefacf-a85a-4a21-ab30-7bcc9ae99946">
