### ISSUE TITLE
E900V22D网卡报错，无法联网

### ISSUE THREAD

**Issue by dudefromc** [ophub/amlogic-s9xxx-armbian#540]
设备：E900V22D
系统盘：闪迪CZ430 32g USB3.0
刷写软件：win32disk
刷入固件：
Armbian_22.11.0_Aml_s905l3a_bullseye_5.10.140_server_2022.09.05.img.gz
Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.62_server_2022.09.05.img.gz
Armbian_22.11.0_Aml_s905l3a_jammy_5.10.140_server_2022.09.05.img.gz
Armbian_22.11.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.05.img.gz

你好，我的是E900V22D盒子，使用外置usb启动，u盘插在离电源键最近的那个口。进入Armbian系统后盒子一直无法获取IP地址，但是在安卓系统中可以正常连接有线网。多次尝试刷入以上几个固件均无法解决问题。具体表现为无法获取ip地址，即使设置静态IP也无法连接网络。

盒子收货之后经测试在安卓系统下无任何问题后自行加装了sd卡槽。经测试sd卡槽可正常启动sd卡中的系统，并且在安卓系统下正常识别，各项功能正常使用。但是armbian系统下仍然无法获取ip地址，我考虑是不是加装卡槽造成的无法获取IP，因此我又把加装卡槽时焊接的电容电阻去掉了，发现还是无法解决问题。

报错信息：
eth0: no phy at addr -1
eth0: stmmac_open:can not attach to PHY (error: -19)
eth0: validation of rmii with support......... 
(因为无法获取IP无法使用SSH获取报错信息，具体报错烦请查看这里的截图)
![6d730df1db15dc0fcf54e181914f1af](https://user-images.githubusercontent.com/77156035/188490054-56d1b4b1-41e8-46a0-b755-0a6d4b9a3887.jpg)
![7061c5e88ce5ffa6fb84b7f9279bf30](https://user-images.githubusercontent.com/77156035/188490061-b57b8cb6-a7a2-49b8-b298-28228cf8cef4.jpg)
![92914f2540761af7e6c79c6a528ba64](https://user-images.githubusercontent.com/77156035/188490063-129efdc1-8e58-4332-ba43-50988dac56c5.jpg)
![e4e141cadf3a7abaaa61f180bc71d36](https://user-images.githubusercontent.com/77156035/188490065-a02b27e7-4c11-4b83-9f8a-626434bc4954.jpg)

**Comment by ophub** [comment]
网卡芯片是什么？拔插一下网线试试

**Comment by dudefromc** [comment]
> 插拔网线还是无法解决问题，下面是内部的网卡芯片

![1293dea88960281c4f45380ac4c2ee4](https://user-images.githubusercontent.com/77156035/188541819-18c5fb44-886f-41ca-af41-33553b5115eb.jpg)

**Comment by ophub** [comment]
![image](https://user-images.githubusercontent.com/68696949/188542941-169d0334-d175-4bee-bfa5-48bd95deb27e.png)

![image](https://user-images.githubusercontent.com/68696949/188542989-8095c839-d364-4441-9137-1f3ee352d535.png)

![image](https://user-images.githubusercontent.com/68696949/188543001-92480d89-1d2f-4b00-a5b7-558b661f846a.png)

![image](https://user-images.githubusercontent.com/68696949/188543026-a628665e-a24c-40ea-8318-3fd82e198132.png)

我看了下E900V22D只有这款可以支持：https://docs.qq.com/doc/DWFprWWxZa290VXNk

**Comment by dudefromc** [comment]
我的CPU是S905L3A的没杜比音效标志的，应该是文中的第一种。
（文中的QQ群无法加入，请问还有没有别的交流群可以加入呢？）
![bd7b48adb29a9a267857841d7b6c2f2](https://user-images.githubusercontent.com/77156035/188545483-56e4021c-ed5e-431e-ae1f-2c002e40ce30.jpg)

![1273740f678262060bdc7277ffa853f](https://user-images.githubusercontent.com/77156035/188545475-9c078d37-96e5-4a03-a3bd-8ac506c942ca.jpg)

**Comment by ophub** [comment]
https://github.com/Calmact/e900v22c

这是他的仓库

**Comment by xcray** [comment]
我的想法：
Realtek那个8761BTV芯片是蓝牙；前段时间折腾过一阵子，终于能在armbian系统里愉快的使用了。
至于网卡，amlogic的soc自带MAC和PHY，网口边上的那个好像只是一个变压器/过滤器。

楼主说的现象就是典型的“不认内置网卡”，可以多试几个内核/dtb/uboot组合，说不定就行了。

**Comment by Linmihg** [comment]
我也是unt403a遇到的情况一模一样。
unt403a先是刷好armbian然后关机就没法再启动了，没找到刷机包，用900v22c带MAC的线刷包刷成功，但是没法启动卡在中国移动界面，能再用u盘启动到其他系统，就是网口用不了。
因为两台在同一台路由器下，同时shh配置，然后两台都开不了机了，一台一台搞就没问题。就是浪费两台机器了。好像是uboot  驱动啥的问题，不懂整不来

**Comment by Linmihg** [comment]
> 我也是unt403a遇到的情况一模一样，S905L3A-B，报错一样。
> unt403a先是刷好armbian然后关机就没法再启动了，没找到刷机包，用900v22c带MAC的线刷包刷成功，但是没法启动卡在中国移动界面，能再用u盘启动到armbian，就是网口用不了，报eth0:stmmac_open: Cannot attach to PHY (error:-19)
> 因为两台在同一台路由器下，同时shh配置，然后两台都开不了机了，一台一台装armbian就没问题，都能正常使用。就是浪费两台机器了。好像是uboot 驱动啥的问题？

**Comment by ophub** [comment]
不知道是不是之前说的machine-id相同的问题。现在己经改成不同的了。

因为同一个固件uuid相同，mac相冋，不能同时在usb里面使用，局域网冲突。

你可以选不同内核的两个固件，就不会冲突了，启动后再更新内核即可。

或者写入emmc就都自动更新了。

**Comment by talpachen** [comment]
非完美解决，仅提供思路 

https://github.com/ophub/amlogic-s9xxx-armbian/issues/600#issuecomment-1269444000

**Comment by mia0x75** [comment]
> 不知道是不是之前说的machine-id相同的问题。现在己经改成不同的了。
> 
> 因为同一个固件uuid相同，mac相冋，不能同时在usb里面使用，局域网冲突。
> 
> 你可以选不同内核的两个固件，就不会冲突了，启动后再更新内核即可。
> 
> 或者写入emmc就都自动更新了。

22D盒子
最新固件Bullseye，已经写入eMMC，一样的问题。
`# uname -a
Linux armbian 5.15.72-flippy-77+o #182 SMP PREEMPT Wed Oct 5 20:23:56 CST 2022 aarch64 GNU/Linux`

问题：
`[  315.271405] meson8b-dwmac ff3f0000.ethernet eth0: no phy at addr -1                                          [  315.277384] meson8b-dwmac ff3f0000.ethernet eth0: stmmac_open: Cannot attach to PHY (error: -19)
[  315.368862] meson8b-dwmac ff3f0000.ethernet eth0: validation of rmii with support 0000000,00000000,00006280 and advertisement 0000000,00000000,00006280 failed: -22  [  315.385168] meson8b-dwmac ff3f0000.ethernet eth0: no phy at addr -1                                          [  315.391137] meson8b-dwmac ff3f0000.ethernet eth0: stmmac_open: Cannot attach to PHY (error: -19)`

参考那个改u-boot.ext的方法依然未解决。现在挂USB网卡联网。

启动还有几处问题，不知道是否相关

`[    0.000000] Unknown kernel command line parameters "cgroup_enable=memory cgroup_memory=1 mac=6C:C2:42:0B:6F:12", will be passed to user space.`

`[    4.655950] genirq: Setting trigger mode 3 for irq 37 failed (meson_gpio_irq_set_type+0x0/0x140)`

`[    6.370655] systemd[407]: /usr/lib/systemd/system-generators/netplan failed with exit status 1.`

**Comment by ysuolmai** [comment]
请问这个问题解决了么？我的22d也是一样问题，网卡无法识别，复制u-boot.ext之后启动直接黑屏了。
