### ISSUE TITLE
Armbian 22.11.0 充斥大量hostapd报错

### ISSUE THREAD

**Issue by Arancia0** [ophub/amlogic-s9xxx-armbian#542]
[![1vuKR.png](https://s1.328888.xyz/2022/09/06/1vuKR.png)](https://imgloc.com/i/1vuKR)

**Comment by ophub** [comment]
什么设备，哪个固件

**Comment by Arancia0** [comment]
CM311 Armbian_22.11.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.05.img 手动关闭hostapd自启可解决

**Comment by ophub** [comment]
好的
