### ISSUE TITLE
cm311开机联网要等待1分43秒

### ISSUE THREAD

**Issue by doyoman** [ophub/amlogic-s9xxx-armbian#545]
cm311开机联网要等待1分43秒，但是我插了usb无线网卡，如图，已经识别到usb无线网卡了，但是还是在等待1分43秒，似乎是等有线网络连上网，这个设置可否更改？
![微信图片_20220907175057](https://user-images.githubusercontent.com/63859866/188848940-0786365c-d6e8-4775-b35c-1c1a387fe74c.png)

**Comment by doyoman** [comment]
> 

我不是这个意思，我这是不用有线网卡，只用无线网卡，但是它似乎默认要等有线网卡获取到ip才能继续下一步，那我只使用无线网卡也要一直等，即使无线网卡已经获取到ip了。而且进入系统以后的流量统计功能（RX today:      0 B）不统计无线网卡的流量。

**Comment by ophub** [comment]
```
sudo mkdir -p /etc/systemd/system/networking.service.d/
sudo bash -c 'echo -e "[Service]\nTimeoutStartSec=20sec" > /etc/systemd/system/networking.service.d/timeout.conf'
sudo systemctl daemon-reload

sync && reboot
```
给他改成20秒，你试试，反馈下结果

**Comment by doyoman** [comment]
没有变化，还是老样子
![微信图片_20220907200816](https://user-images.githubusercontent.com/63859866/188874917-16608806-9c00-4f94-973b-2400585e4180.png)

**Comment by ophub** [comment]
sudo mkdir -p /etc/systemd/system/networking.service.d/
sudo bash -c 'echo -e "[Service]\nTimeoutStartSec=20sec" > /etc/systemd/system/networking.service.d/override.conf'
sudo systemctl daemon-reload

sync && reboot

**Comment by doyoman** [comment]
![image](https://user-images.githubusercontent.com/63859866/188878586-654bff7b-c9f3-4a20-bdc8-af83be0b7d26.png)
还是没变

**Comment by ophub** [comment]
```
cat /etc/network/interfaces

ifconfig
```

这2个的结果截图

**Comment by xcray** [comment]
我记得有个很久之前的版本是改这个：
/lib/systemd/system/networking.service
最后一行：
TimeoutStartSec=10sec

**Comment by ophub** [comment]
那是改有线的网口等待，你现在是要把这个删了，改为无线的网口，所以你用ifconfig看看你的无线的名字是什么，留下这个，其他的有线删除了，留着你不用，白等待网络连接了

**Comment by doyoman** [comment]
![image](https://user-images.githubusercontent.com/63859866/188883765-ca390c7c-f4fd-4120-892f-1a52496332d3.jpeg)
![image](https://user-images.githubusercontent.com/63859866/188883809-38ff9084-64c7-4e30-b459-3babc8f424f7.png)

**Comment by ophub** [comment]
```
mv /etc/network/interfaces /etc/network/interfaces.bak
sync && reboot
```

直接弃用了这个文件吧

**Comment by babutree** [comment]
cm311-1a CH版 使用Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.62_server_2022.09.06.img.gz U盘禁用NetworkManager可正常获取到IP
![11](https://user-images.githubusercontent.com/21240045/188894525-44f3f91f-f32d-4997-9f1d-e8b6cfcd5e22.png)

在写入EMMC后 无法使用interfaces获取IP，DHCP、静态IP或新建br0桥接均无法ping通网关，打开NetworkManager后仍不能正常联网，需注释掉interfaces文件方可正常联网
![22](https://user-images.githubusercontent.com/21240045/188896267-2ad0cb2a-cc49-4296-a75b-5090f95b1ff8.png)

**Comment by babutree** [comment]
![33](https://user-images.githubusercontent.com/21240045/188897521-997cc1d7-f70c-4429-aa7f-7b98f43e6019.png)

**Comment by doyoman** [comment]
> 或者添加wlan0
> 
> 
> 
> `vi /etc/network/interfaces.d/wlan0`
> 
> 
> 
> 内容如下：
> 
> ```
> 
> auto wlan0
> 
> allow-hotplug wlan0
> 
> iface wlan0 inet dhcp
> 
> ```
> 
> 里面的内容你可以根据需要改，添加mac地址，或者写成固定ip等

感谢指导，经我测试发现，弃用/etc/network/interfaces之后，能稳定开机不等待，无线网卡顺利联网，如果是添加wlan0配置文件，则概率性要等待，基本上是软重启（reboot）概率性等待，硬重启（断电重启）一定等待。

**Comment by lovelylain** [comment]
> > 
> 
> 我不是这个意思，我这是不用有线网卡，只用无线网卡，但是它似乎默认要等有线网卡获取到ip才能继续下一步，那我只使用无线网卡也要一直等，即使无线网卡已经获取到ip了。而且进入系统以后的流量统计功能（RX today: 0 B）不统计无线网卡的流量。

既然不用内置网卡，可以在dtb里禁用掉，这样就不会出现eth0了

**Comment by ophub** [comment]
好的，搞定就好

**Comment by acooler15** [comment]
> > 或者添加wlan0
> > `vi /etc/network/interfaces.d/wlan0`
> > 内容如下：
> > ```
> > 
> > auto wlan0
> > 
> > allow-hotplug wlan0
> > 
> > iface wlan0 inet dhcp
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 里面的内容你可以根据需要改，添加mac地址，或者写成固定ip等
> 
> 感谢指导，经我测试发现，弃用/etc/network/interfaces之后，能稳定开机不等待，无线网卡顺利联网，如果是添加wlan0配置文件，则概率性要等待，基本上是软重启（reboot）概率性等待，硬重启（断电重启）一定等待。

使用networkmanager管理网络的话，可以使用nmcli或修改networkmanager的配置文件来添加无线配置（当然可以使用netplan来生成）
