### ISSUE TITLE
r8188eu驱动问题

### ISSUE THREAD

**Issue by doyoman** [ophub/amlogic-s9xxx-armbian#546]
r8188eu无线网卡驱动有问题，插入网卡以后能联网，很小的流量没事，比如ping，流量稍微大一点就死机，完全卡死要断电重启，网卡芯片是rtl8188eu

**Comment by doyoman** [comment]
cm311-1a
固件为Armbian_22.11.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.06.img.gz

**Comment by ophub** [comment]
8153/88179 这些USB网卡比较稳定
