### ISSUE TITLE
CM311-1A（YST）docker数据不能映射到外接硬盘

### ISSUE THREAD

**Issue by rxy0924** [ophub/amlogic-s9xxx-armbian#547]
盒子：CM311-1A（YST）
SOC：S905L3A
固件：Armbian_22.11.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.06.img.gz
问题描述：安装casaos后，硬盘挂载到/DATA/WXY，docker数据映射到DATA/WXY报错docker: Error response from daemon: create  /DATA/WXY: "\u00a0/DATA/WXY" includes invalid characters for a local volume name, only "[a-zA-Z0-9][a-zA-Z0-9_.-]" are allowed. If you intended to pass a host directory, use absolute path.
硬盘卸载重新挂载、重新格式化、换路径都试了，一样报错。

**Comment by ophub** [comment]
使用绝对路径，路径名字不要有空格，名字中使用大小写英文字符和数字
