### ISSUE TITLE
请问如何编译wifi驱动，卡在kernel headersd 的安装

### ISSUE THREAD

**Issue by allonmymind** [ophub/amlogic-s9xxx-armbian#548]
想尝试编译wifi驱动，安装kernel headers失败，查看过之前相关issue，表示看不太懂。。。
希望获得您的帮助，谢谢！

以下是找到的大致编译步骤：
Compiling & Building
Dependencies
To compile the driver, you need to have make and a compiler installed. In addition, you must have the kernel headers installed. If you do not understand what this means, consult your distro.

Compiling
make

Installing
sudo make install

Disable CDROM mode and select in WiFi mode. (not for Ubuntu 20.04)
eject /dev/cdrom0

**Comment by ophub** [comment]
headers己经安装了

**Comment by allonmymind** [comment]
> headers己经安装了

之前的issue里您说在/usr/local/include里，
可/usr/local/include里是空的，再就是您说要指定编译路径，请问参照上面的步骤，命令应该是怎样的，能指导下吗

**Comment by allonmymind** [comment]
root@armbian:~/build/rtl8188gu# make
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/5.15.57-flippy-75+o/build M=/root/build/rtl8188gu  modules
make[1]: Entering directory '/usr/src/linux-5.15.y'
make[1]: *** No rule to make target 'modules'.  Stop.
make[1]: Leaving directory '/usr/src/linux-5.15.y'
make: *** [Makefile:1895: modules] Error 2
root@armbian:~/build/rtl8188gu# 
直接编译报错了

**Comment by ophub** [comment]
你发的看不清，文字划个线有什么特殊意义？

**Comment by allonmymind** [comment]
> 你发的看不清，文字划个线有什么特殊意义？

粘贴上去的时候没有划线，发表后自己就带上了横线。
![image](https://user-images.githubusercontent.com/18719713/189280936-6c7b91d3-8960-4054-a38f-d6d507dfd5b1.png)
很少提issue，不懂这个原因，抱歉，我上传了截图

**Comment by hgwfm** [comment]
请您不要再给我错发邮件了


黄卫明的iPhone

**Comment by ophub** [comment]
你看的教程不对。你在armbian里编译不用交叉工具链

**Comment by allonmymind** [comment]
> 你看的教程不对。你在armbian里编译不用交叉工具链

![image](https://user-images.githubusercontent.com/18719713/189281558-6ecec6f6-6a9b-4cad-88df-126ea39d2e06.png)
这张截图应该是官方的教程吧

**Comment by allonmymind** [comment]
> 你看的教程不对。你在armbian里编译不用交叉工具链
> 
> 这是完整编译的方法，单独编驱动可以参考armbian-kernel
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

您发的这个链接没看到如何添加其他驱动的源码进去编译的方法，我没有这方面的基础，也许是我看不懂...
所以都是在网上找教程跟着做才行

**Comment by ophub** [comment]
你看的armbian教程对，第一步安装忽略

**Comment by allonmymind** [comment]
> 你看的armbian教程对，第一步安装忽略。因为你安装不上，我们使用的是自定义名称的内核，官方安装的header对不上名称。

![image](https://user-images.githubusercontent.com/18719713/189283900-2ce9ea79-99c9-4217-a99a-f596f593a523.png)
我去路径/usr/src/linux-5.15.y看了下，这里有headers，
make ARCH=arm CROSS_COMPILE= -C /lib/modules/5.15.57-flippy-75+o/build M=/root/build/rtl8188gu  modules
make[1]: Entering directory '/usr/src/linux-5.15.y'
headers路径也正常找到了，但还是报错了

**Comment by ophub** [comment]
你执行的make命令不对，参数错误，这不是armbian下编译的参数

**Comment by allonmymind** [comment]
> ls /usr/lib/modules/5.15.57-flippy-75+o/build -l

我之前编译python3.9就是这么编译的，没有问题的

**Comment by ophub** [comment]
你是什么设备？32位的？

**Comment by allonmymind** [comment]
> 你是什么设备？32位的？

![image](https://user-images.githubusercontent.com/18719713/189286202-67ea2e37-8da7-4cec-a522-754994dd9530.png)
s905d2,64位的

**Comment by ophub** [comment]
你是给本机编译还是给其他设备编译？
用指定CROSS_COMPILE是要给其他设备交叉编译？
ARCH="arm"是要编译给32位的设备使用吗？

**Comment by allonmymind** [comment]
> 你是给本机编译还是给其他设备编译？ 用指定CROSS_COMPILE是要给其他设备交叉编译？ ARCH="arm"是要编译给32位的设备使用吗？

给本机编译用的，直接make编译是有提示ARCH=arm64,也是上面的报错结果，指定ARCH=arm，报错一样。
![image](https://user-images.githubusercontent.com/18719713/189287233-ef987b83-f3d4-44dd-b242-c73b338071b1.png)
搜索了下有报错一样通过重新安装headers成功编译运行驱动的，您有试过这种方法编译其他驱动的经历吗，这个headers是不是确定可以用来编译驱动的呢

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/script/armbian_compile_kernel_script.sh#L323

**Comment by allonmymind** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/script/armbian_compile_kernel_script.sh#L323

![image](https://user-images.githubusercontent.com/18719713/189287742-f21dd4cb-881e-4b83-9ac5-18781d54a313.png)
一样

**Comment by ophub** [comment]
`ls /usr/src/`

**Comment by allonmymind** [comment]
> ![Snip20220909_2](https://user-images.githubusercontent.com/68696949/189288608-f821f3cb-a261-43d8-b1be-91afc9ebba26.png)
> 
> `ls /usr/src/`

![image](https://user-images.githubusercontent.com/18719713/189288820-ebb75c82-08d2-47dc-8fba-ef007fb66bb2.png)
确实不一样
modules里内核的build指向哪了，改到正确的位置---这个有点不懂改0.0
我重新装一遍试试。

**Comment by allonmymind** [comment]
![image](https://user-images.githubusercontent.com/18719713/189290049-bd6f5200-7272-4e81-9316-e84b941366d3.png)
是这样的，是不是代表不用改？

**Comment by ophub** [comment]
```
armbian-sync
armbian-update
```
执行这2个命令，同步脚本，更新至最新内核，就修复了

**Comment by allonmymind** [comment]
> ```
> armbian-sync
> armbian-update
> ```
> 
> 依次执行这2个命令，同步脚本，更新至最新内核，就修复了

![image](https://user-images.githubusercontent.com/18719713/189299491-3bbcf559-f56e-4a91-8964-5799e0e89625.png)
重新安装还是不行。。。

**Comment by ophub** [comment]
自己改源码吧，下载的编译源码里的路径改下：`arch/arm64/Makefile`
编译中根据错误自己调试

**Comment by allonmymind** [comment]
大佬你好，我用balbed150的5.9内核的固件试了能运行编译驱动，用你的5.10的内核固件一开始就报错，对比了下如下路径的文件夹好像不完整，能帮忙确定下问题是否出在这里吗？
![image](https://user-images.githubusercontent.com/18719713/190661922-07ed0d02-7eae-4fd9-931e-cf6f5c85258d.png)
![image](https://user-images.githubusercontent.com/18719713/190662977-77529788-ed26-49ac-80bb-edac4d76d69f.png)
