### ISSUE TITLE
关于acs.bin的提取

### ISSUE THREAD

**Issue by a520ass** [ophub/amlogic-s9xxx-armbian#549]
大佬，是所有amlogic的acs.bin的提取方法都一样吗？S905L、S905L2、S905L3的bootloader从F200开始截取的话，都是乱码。只有S905L3A的不是乱码。是不是架构不同的原因，S905L、S905L2、S905L3属于GXL，S905L3A属于G12A。有办法提取GXL架构的acs.bin吗？

**Comment by ophub** [comment]
乱码的就是锁了，不乱码的就是可以提取的

**Comment by a520ass** [comment]
> 乱码的就是锁了，不乱码的就是可以提取的

S905L、S905L2、S905L3这几个芯片，看过很多线刷包的bootloader，都是乱码，那就是无解了吧

**Comment by a520ass** [comment]
但是我看了那些开源的开发版的主线u-boot，GXL的从F200开始也是乱码。非GXL的就是正常。是不是GXL的不是从F200开始？

**Comment by ophub** [comment]
你的问题我问了一下f大，这个方法适用于目前f大发布的u-boot的制作。不代表其他soc一定适用。这是f大目前在用的方法，不是amlogic的官方制作方法，你看的其他方法会有不同。

**Comment by a520ass** [comment]
好的，那应该是不同的，先不深入了解了，用主线的意义就是多点空间，目前overload方式一切正常的

**Comment by a520ass** [comment]
好的，那应该是不同的，先不深入了解了，用主线的意义就是多点空间，目前overload方式一切正常的

**Comment by Sarlang123** [comment]
> 乱码的就是锁了，不乱码的就是可以提取的

![Screenshot_20230402-175548](https://user-images.githubusercontent.com/127936622/229346008-0a0bf2dc-3229-49d5-bf5c-03795833d2d3.png)
Is this locked?

**Comment by ophub** [comment]
this is locked

**Comment by a520ass** [comment]
不需要提取acs.bin也可以，使用gxlimg能生成

**Comment by Sarlang123** [comment]
> 不需要提取acs.bin也可以，使用gxlimg能生成

怎么操作？

**Comment by a520ass** [comment]
> > 不需要提取acs.bin也可以，使用gxlimg能生成
> 
> 怎么操作？
参考这个大佬的回复
https://github.com/7Ji/ampart/issues/6#issuecomment-1416924282
