### ISSUE TITLE
希望增加对S905X4芯片盒子的支持

### ISSUE THREAD

**Issue by kerncoola** [ophub/amlogic-s9xxx-armbian#55]
目前S905X4芯片的盒子有A95X F4，HK1 RBOX X4，ugoos x4 pro，KM6等，价格上和S905X3相差不大，本着买新不买旧的原则，S905X4的盒子目前可玩性还不高，希望能适配armbian。

**Comment by ophub** [comment]
https://github.com/armbian/build/search?q=s905x4

At present, the `s905x4` box has not been found in the `official armbian` compiled source code, and it may not be usable without `.dtb file`, so you have to wait. If you have dtb, you can try to use the `5.4 kernel`.

**Comment by Neverends4** [comment]
905x4和X3基本上就是AV1硬解支持，然而armbian对硬解支持又基本为0，所以……
之前在COREELEC论坛看到开发者说amlogic对于X4的codec是闭源，即看中视频解码的CE已经死掉了，支持仅限目前的X3
