### ISSUE TITLE
执行armbian-config提示-bash: armbian-config: command not found

### ISSUE THREAD

**Issue by uifor** [ophub/amlogic-s9xxx-armbian#550]
![image](https://user-images.githubusercontent.com/13254011/189365545-1170fba4-0a8c-46dd-bf94-098ed6397b7b.png)

**Comment by ophub** [comment]
哪个版本的固件？
`cat /etc/ophub-release`

**Comment by uifor** [comment]
> 哪个版本的固件？ `cat /etc/ophub-release`

VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
KERNEL_VERSION='5.15.57'
PACKAGED_DATE='2022-07-28'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
UBOOT_OVERLOAD='u-boot-n1.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905d'
K510='0'

**Comment by ophub** [comment]
系统安装了几个月了？还是刚安装的？

**Comment by uifor** [comment]
> 系统安装了几个月了？还是刚安装的？
八月初左右安装的

**Comment by ophub** [comment]
重启试试

**Comment by uifor** [comment]
> 重启试试
ls: cannot access '/usr/sbin/armbian-config': No such file or directory
有重启过好几次了，本来是像用armbian-config去选择network，BTinstall，安装蓝牙组件，发现那个蓝牙不起作用的

**Comment by ophub** [comment]
文件怎么没了呢？

```
lsblk
ls -l /usr/sbin
```

**Comment by uifor** [comment]
> 文件怎么没了呢？
> 
> ```
> lsblk
> ls -l /usr/sbin/armbian*
> ```
本来就没有的，没有动过呀
-rwxr-xr-x 1 root root    2217 Jul 28 15:26 applygnupgdefaults
-rwxr-xr-x 1 root root    4545 Jul 28 15:26 armbian-ddbr
-rwxr-xr-x 1 root root    5253 Jul 28 15:26 armbian-docker
-rwxr-xr-x 1 root root    3841 Jul 28 15:26 armbian-fix
-rwxr-xr-x 1 root root   16949 Jul 28 15:26 armbian-install
-rwxr-xr-x 1 root root    4834 Jul 28 15:26 armbian-kernel
-rwxr-xr-x 1 root root    6257 Jul 28 15:26 armbian-led
-rwxr-xr-x 1 root root   10650 Jul 28 15:26 armbian-software
-rwxr-xr-x 1 root root    4705 Jul 28 15:26 armbian-swap
-rwxr-xr-x 1 root root    4077 Jul 28 15:26 armbian-sync
-rwxr-xr-x 1 root root   13604 Jul 28 15:26 armbian-update
-rwxr-xr-x 1 root root   58520 Jul 28 15:26 arp
-rwxr-xr-x 1 root root   18552 Jul 28 15:26 arpd
其他的指令都有，唯独armbian-config，这个文件能够通过你那边发送给我嘛

**Comment by uifor** [comment]
> 文件怎么没了呢？
> 
> ```
> lsblk
> ls -l /usr/sbin/armbian*
> ```

之前看到你回到过一个类似的问题
![image](https://user-images.githubusercontent.com/13254011/189464104-6d83f189-3046-469f-aa1d-ac6259c8332e.png)
我尝试者把armbian-sync替换成armbian-config，发现链接打开是404
https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/common-files/rootfs/usr/sbin/armbian-config

**Comment by ophub** [comment]
[armbian-config.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9539371/armbian-config.zip)

解压，上传到/usr/sbin
给执行权限：`chmod +x /usr/sbin/armbian-config`

**Comment by uifor** [comment]
> chmod +x /usr/sbin/armbian-config

![image](https://user-images.githubusercontent.com/13254011/189464271-b4a6c5b0-a9b2-407b-8a8e-2868a037bb96.png)
执行后没有任何反应是怎么回事呢

**Comment by ophub** [comment]
`ls -l /usr/lib/armbian-config`

**Comment by uifor** [comment]
> `ls -l /usr/lib/armbian-config`

root@armbian:~# ls -l /usr/lib/armbian-config
ls: cannot access '/usr/lib/armbian-config': No such file or directory

**Comment by ophub** [comment]
![Snip20220910_1](https://user-images.githubusercontent.com/68696949/189464623-31309008-4c13-4a3a-9535-315b53dc220a.png)

不知道你删除了多少文件，建议你重装吧

**Comment by ophub** [comment]
`df -hT`

**Comment by uifor** [comment]
> df -hT
Filesystem     Type   Size  Used Avail Use% Mounted on
tmpfs          tmpfs  181M  5.3M  176M   3% /run
/dev/mmcblk2p2 ext4   6.4G  2.8G  3.3G  47% /
tmpfs          tmpfs  905M     0  905M   0% /dev/shm
tmpfs          tmpfs  5.0M  4.0K  5.0M   1% /run/lock
tmpfs          tmpfs  905M   16K  905M   1% /var/tmp
/dev/mmcblk2p1 vfat   511M  106M  406M  21% /boot
tmpfs          tmpfs  181M     0  181M   0% /run/user/0

没有删除过东西，只有把python3.10换成3.9，你现在安装的是什么版本，我等会看看

**Comment by ophub** [comment]
挂载也没问题，但是文件你怎么丢了这么多呢，执行过什么操作呢？
我Jammy和Bullseye，Focal这几个版本都在使用

![Snip20220910_2](https://user-images.githubusercontent.com/68696949/189464969-71243446-f406-482a-99b6-00bccaf36657.png)

![Snip20220910_3](https://user-images.githubusercontent.com/68696949/189464971-ae256a01-6ac8-4e43-8024-704ae4c622aa.png)

**Comment by xcray** [comment]
怀疑又是分区布局的问题
