### ISSUE TITLE
Kernel Panic when connecting to WiFi in S-BOX with s905x and rtl8723bs

### ISSUE THREAD

**Issue by robertoenr** [ophub/amlogic-s9xxx-armbian#551]
Hi,

First of all thank you for this awesome distro for our TV Boxes. Hope keep growing!

I want to report about a kernel panic produced when connecting to wifi in this tv box (scan is working). 

**The hardware is the following**:

- TV Box model: S-BOX
- SoC: s905x
- RAM: 1 GB
- EMMC: 16 GB
- WiFi Chipset: rtl8723bs
- No ethernet port

**Armbian versions tested**:

- Armbian_22.11.0_Aml_s905x_bullseye_5.15.62_server_2022.09.09
- Armbian_22.11.0_Aml_s905x_bullseye_5.10.142_server_2022.09.09
- Armbian_22.11.0_Aml_s905x_jammy_5.15.62_server_2022.09.09
- Armbian_22.11.0_Aml_s905x_jammy_5.10.142_server_2022.09.09

On all versions the issue is the same. I've tried to connect wifi from the startup wizard, and also after reboot from armbian-config -> Network -> Wifi. Same issue.

Link to an screenshot about the kernel panic: [https://www.dropbox.com/s/gc7wsrapx40q73u/kernel_panic.jpg?dl=0](url)

Any help is appreciated.
Thanks.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/c3c2c1ab423e8e54c7d7d2e937f2911a4e73863a/compile-kernel/tools/config/config-5.15#L6245

The driver of rtl8723bs comes from the official kernel. Try another version:

```
armbian-update 5.4.212
armbian-update 5.19.8
```

**Comment by robertoenr** [comment]
Thank you for your response.

Tested both kernels. I report the results.

**Result after armbian-update 5.4.212**: 

Wifi chipset now not detected. Also, can't scan wireless networks with nmtui.

**Results after armbian-update 5.19.8**:

Tv Box now not booting (black screen bootloop).

**Comment by robertoenr** [comment]
Hi, do you have any updates to this thread?

I've just tested the following images on the same device:

**Armbian_23.02.0_amlogic_s905x_bullseye_6.1.6_server_2023.01.16.img.gz** -> Does not boot

**Armbian_23.02.0_amlogic_s905x_bullseye_5.15.88_server_2023.01.16.img** -> Boot, but still kernel panic on connect to WiFi.

[https://www.dropbox.com/s/gc7wsrapx40q73u/kernel_panic.jpg?dl=0](https://www.dropbox.com/s/gc7wsrapx40q73u/kernel_panic.jpg?dl=0)

Thanks!
