### ISSUE TITLE
N1刷上固件不能使用已有密钥登录实现免密码登陆SSH

### ISSUE THREAD

**Issue by 2536** [ophub/amlogic-s9xxx-armbian#552]
N1刷上固件Armbian_22.11.0_Aml_s905d_jammy_5.15.62_server_2022.09.09.img.gz不能使用已有密钥登录实现免密码登陆SSH之前刷别的版本的都没有问题，可以通过已有密钥登录实现免密码登陆SSH现在这个版本怎么设置都不行是不是这个固件不支这个功能..通过密钥实现免密登录ssh

**Comment by ophub** [comment]
祥细描述你的操作过程

**Comment by 2536** [comment]
是可以正常通过密码登录ssh但是在设置通过密钥进行免密登录ssh的时候就是失败，提示：Server refused our key

**Comment by ophub** [comment]
1.备份现有密钥
下载原来armbian系统中的密钥，使用winsco、SFTP 等工具将.ssh文件夹整个备份下来：/root/.ssh

2.安装公钥
如果只备份了公钥和私钥两个文件，要安装公钥：
cd /root/.ssh
cat id_rsa.pub >> authorized_keys

3.添加密钥使用权限：
chmod 600 authorized_keys
chmod 700 ~/.ssh

4.设置 SSH，打开密钥登录功能
编辑 /etc/ssh/sshd_config 文件，进行如下设置：
RSAAuthentication yes
PubkeyAuthentication yes
另外，请留意 root 用户能否通过 SSH 登录：
PermitRootLogin yes

5.重启ssh服务开启密钥登陆
service sshd restart

6. 使用id_rsa私钥文件登录
有些软件如SecureCRT可以直接导入私钥使用；有些软件如PuTTY要先转换一下格式，打开PuTTYGen，单击 Actions 中的 Load 按钮，载入你刚才下载到的id_rsa私钥文件。如果你设置了密钥锁码，这时则需要输入。
载入成功后，PuTTYGen 会显示密钥相关的信息。在 Key comment 中键入对密钥的说明信息，然后单击 Save private key 按钮即可将私钥文件存放为 PuTTY 能使用的格式。
今后，当你使用 PuTTY 登录时，可以在左侧的 Connection -> SSH -> Auth 中的 Private key file for authentication: 处选择你的私钥文件，然后即可登录了，过程中只需输入密钥锁码即可。

7.禁用密码登录
当你完成全部设置，并以密钥方式登录成功后，再禁用密码登录：
PasswordAuthentication no
最后，重启 SSH 服务：
service sshd restart

**Comment by 2536** [comment]
密钥都没问题，密钥都是我之前生成的，包括我的路由器openwrt也是用的这个密钥都能正常免密登录

**Comment by ophub** [comment]
我可以用

**Comment by 2536** [comment]
真是奇怪了，现在发现WinSCP可以用密钥实现免密登录，PuTTY不可以用密钥实现免密登录

**Comment by ophub** [comment]
看上面的方法转换

**Comment by 2536** [comment]
真是奇怪了，现在发现WinSCP可以用密钥实现免密登录，PuTTY不可以用密钥实现免密登录
