### ISSUE TITLE
Bulding kernel module failed.

### ISSUE THREAD

**Issue by Phil67ago** [ophub/amlogic-s9xxx-armbian#554]
**Describe the bug**
Can't build kernel modules.

**Setup**
X96Max+
Download: https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_09.09.0858/Armbian_22.11.0_Aml_s905x3_jammy_5.15.62_server_2022.09.09.img.gz

**Prepare**
In BOOT:
cp BOOT/u-boot-x96maxplus.bin  BOOT/u-boot.ext

edit uEnv.txt: 
FDT=/dtb/amlogic/meson-g12a-x96-max.dtb

**To Reproduce**
Copy attached build.sh to armbian: /root/src/test and run bash build.sh

**Armbian Version**
 - Kernel Version: [e.g. 5.15.62]
 - Release: [e.g. jammy]
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: [e.g. S905x3]
 - Brand: [e.g. ??]
 - Model [e.g. X96Max+]

**Problems**
1. Mixed use of compilers clang(kernel) and gcc.
2. After resolving compiler issue: /usr/src/linux-headers-5.15.62-flippy-76+o/scripts/basic/fixdep  is x86-64
file /usr/src/linux-headers-5.15.62-flippy-76+o/scripts/basic/fixdep
3. After fixing fixdep: Kernel configuration is invalid.

I do not have any problems running same build.sh on other platforms (ubuntu(arm),ubuntu(x86),fedora)

[build.sh.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9547993/build.sh.txt)

![Screenshot at 2022-09-12 14-46-16](https://user-images.githubusercontent.com/16326974/189658083-e5e44923-d2a8-43f8-91b8-465e394a2ee1.png)

**Comment by ophub** [comment]
根据你的错误提示操作，上图提示你没.config，让你执行生成命令

**Comment by Phil67ago** [comment]
Yes there are some stuff missing inside your 'dist' (amlogic-s9xxx-armbian) that's why I open this issue.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/recompile#L318-L347

The header is generated by this function, and these files are obtained from the source code of the compiled kernel. look what's missing

**Comment by Phil67ago** [comment]
Ok I will do.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y

the source code of the compiled kernel.

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/dev

```
#The kernel of the same version cannot be updated, so update to another version first
armbian-update 5.15.67

#Then update the test kernel in the `dev` directory
armbian-update 5.15.68 dev
```

**Comment by ophub** [comment]
I updated the header, you try this
https://github.com/ophub/kernel/tree/main/pub/dev

```
#The kernel of the same version cannot be updated, so update to another version first
armbian-update 5.15.67

#Then update the test kernel in the `dev` directory
armbian-update 5.15.68 dev
```

**Comment by Phil67ago** [comment]
Ok,

But I have replace X96max with RPi 4 so I will use native ubuntu instead.
