### ISSUE TITLE
Internal error: Oops: 96000005 [#1] PREEMPT SMP

### ISSUE THREAD

**Issue by ysuolmai** [ophub/amlogic-s9xxx-armbian#555]
M401A硬盘用了最新版的(0909)的bullseye 5.15.62, 跑一段时间就会跳这个出来

Message from syslogd@armbian at Sep 12 21:13:42 ...
 kernel:[  211.361978] Internal error: Oops: 96000005 [#1] PREEMPT SMP

Message from syslogd@armbian at Sep 12 21:13:42 ...
 kernel:[  211.554735] Code: aa0003e8 f9400409 b40000a9 aa0903e0 (f9400929)

不管emmc还是u盘都有，armbian-install的时候304，305都试了都还是这样

**Comment by ysuolmai** [comment]
甚至好几次armbian-install的时候出这个，直接安装失败

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_b863av3.2-m_s905l3a.tar.xz

先刷底包

**Comment by ysuolmai** [comment]
> https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_b863av3.2-m_s905l3a.tar.xz
> 
> 如果安卓系统都不能稳定地运行u盘，你先刷底包

大佬这个底包刷了之后，怎么引导USB启动？reboot to libreelec貌似没用了

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#124-%E8%AE%BE%E7%BD%AE%E7%9B%92%E5%AD%90%E4%BB%8E-usbtfsd-%E4%B8%AD%E5%90%AF%E5%8A%A8

reboot to libreelec是一个app吧，你安装下

**Comment by ysuolmai** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#124-%E8%AE%BE%E7%BD%AE%E7%9B%92%E5%AD%90%E4%BB%8E-usbtfsd-%E4%B8%AD%E5%90%AF%E5%8A%A8
> 
> reboot to libreelec是一个app吧，你安装下

就是没找到办法打开开发者选项，按版本信息没用。没法打开开发者选项就没法打开adb...
对reboot to libreelec是个app，但是在这个固件上没用，这样刷了之后就不知道怎么U盘引导了

**Comment by ysuolmai** [comment]
![IMG_6569](https://user-images.githubusercontent.com/12818757/189842328-48dba061-ee96-43ec-af60-d1210942217a.jpg)

放弃了，动不动出这个错误。

**Comment by ophub** [comment]
不停的提示你的移动硬盘的ext4格式错误。你是不是把硬盘插windows电脑上使用过？我记得群里有人是插到电脑上，在磁盘管理里点修复。

**Comment by ysuolmai** [comment]
> 不停的提示你的移动硬盘的ext4格式错误。你是不是把硬盘插windows电脑上使用过？我记得群里有人是插到电脑上，在磁盘管理里点修复。

还真没有，我试了好几个移动硬盘/U盘，试了好几个线刷固件，试了好几个你的版本，都有问题，我放弃了，弄了一天了，这个M401A一直搞不定，同样操作在CM311-1a上完全没有问题。刷回电视系统看电视用了。
