### ISSUE TITLE
Armbian_22.05.0_Aml_s905x3_focal_5.15.34_2022.04.18.2343这个镜像执行armbian-tf成功后重启无法正常进入系统

### ISSUE THREAD

**Issue by qxa792** [ophub/amlogic-s9xxx-armbian#556]
Armbian_22.05.0_Aml_s905x3_focal_5.15.34_2022.04.18.2343这个镜像执行armbian-tf成功后重启无法正常进入系统

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/usr/sbin/armbian-tf

下载这个最新版，覆盖同路径下的文件：/usr/sbin/armbian-tf
