### ISSUE TITLE
项目主页上M401A链接去的那个固件不能刷，建议删掉

### ISSUE THREAD

**Issue by ysuolmai** [ophub/amlogic-s9xxx-armbian#558]
![IMG_6568](https://user-images.githubusercontent.com/12818757/189838292-f3990e9d-a39b-4fc8-9434-a7ff6dc1ec0d.jpg)

如上图，卡刷包校验没法通过，没法刷，很误导人，建议删除或者换掉。

**Comment by ysuolmai** [comment]
![IMG_6568](https://user-images.githubusercontent.com/12818757/189839190-90f91681-94e1-4573-b1f6-989ea26e15fd.jpg)

**Comment by xcray** [comment]
不懂不要乱说好不好？建议先多看看文档

你说的是卡刷安卓的方法，armbian就不是这么刷的，虽然按照“线刷or卡刷”的划分也算是卡刷。

**Comment by lovelylain** [comment]
姿势不对吧，开机连续按遥控，出现升级界面后立即按电源键关机，再按电源键开机，你试试。

**Comment by xcray** [comment]
有些机型校验可以跳过去，可以试试卡刷进度开始走的时候关电源再打开

**Comment by ophub** [comment]
千万别刷那些网页链接里的固件，也不要去购买相关链接里的产品。
产品链接，都不是让大家刷固件，或者买那个网站的产品。那些链接只是为了让大家看看这个设备长什么样子，以及相关网站对设备相关参数的介绍。

**Comment by ysuolmai** [comment]
> 姿势不对吧，开机连续按遥控，出现升级界面后立即按电源键关机，再按电源键开机，你试试。

就是这样操作的。。。

**Comment by ysuolmai** [comment]
> 千万别刷那些网页链接里的固件，也不要去购买相关链接里的产品。 产品链接，都不是让大家刷固件，或者买那个网站的产品。那些链接只是为了让大家看看这个设备长什么样子，以及相关网站对设备相关参数的介绍。 如果你觉得自己的机器想试试他的安卓固件，需要自己分辨，不能用会自己恢复系统。 如果想购买相关产品，也要自己分辨是否可以购买，这些链接不是推荐，只是方便了解这个产品。

好的大佬。这个可以关了
