### ISSUE TITLE
Could not rebuild with beta kernel 5.7.19

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#56]
I've try to rebuild the armbian with beta kernel 5.7.19 on Github action but got the following error:

This is my config:

>  name: Rebuild Armbian for Amlogic s9xxx
>         uses: ophub/amlogic-s9xxx-armbian@main
>         with:
>           armbian_path: ${{ env.ARMBIAN_URL }}
>           armbian_soc: s905x3
>           armbian_kernel: 5.10.80_5.7.19
>           armbian_size: 6500

This is the error message from Github action

> Welcome to build armbian for amlogic s9xxx STB!
> Armbian original file: [ Armbian_21.08.1_Lepotato_bullseye_current_5.10.60.img ], Version: [ 21.08.1 ], Kernel: [ 5.10.60 ]
> Armbian SoC List: [ s905x3  ]
> Kernel List: [ 5.10.87 5.7.19  ]
> Server space usage before starting to compile: 
> Filesystem     Type  Size  Used Avail Use% Mounted on
> /dev/root      ext4   84G   38G   46G  45% / 
> 
> (1.1) Start build armbian [ s905x3 - 5.10.87 ]. Remaining space is 46G.
>  [ s905x3 - 5.10.87 ]  (1/5) make new armbian image.
>  [ s905x3 - 5.10.87 ]  (2/5) extract old armbian files.
>  [ s905x3 - 5.10.87 ]  (3/5) replace kernel for armbian.
>  [ s905x3 - 5.10.87 ]  (4/5) copy files to new image.
>  [ s905x3 - 5.10.87 ]  (5/5) clear temp files.
> (1.1) Build successfully. 
> 
> (1.2) Start build armbian [ s905x3 - 5.7.19 ]. Remaining space is 46G.
>  [ s905x3 - 5.7.19 ]  (1/5) make new armbian image.
>  [ s905x3 - 5.7.19 ]  (2/5) extract old armbian files.
>  [ s905x3 - 5.7.19 ]  (3/5) replace kernel for armbian.
> tar (child): -C: Cannot open: No such file or directory
> tar (child): Error is not recoverable: exiting now
> tar: Child returned status 2
> tar: Error is not recoverable: exiting now
>  [ Error ] boot/ 5 files is missing.
> Error: Process completed with exit code 1.

**Comment by dinhchinh82** [comment]
This is error screenshot:
<img width="1020" alt="Screen Shot 2021-12-19 at 18 31 40" src="https://user-images.githubusercontent.com/22479095/146673339-66a0e3cf-3323-496d-8d9c-f1444a5ef97a.png">

**Comment by ophub** [comment]
```
- name: Rebuild Armbian for Amlogic s9xxx
  uses: ophub/amlogic-s9xxx-armbian@main
  with:
    armbian_path: build/output/images/*.img
    armbian_soc: s905d_s905x3_s922x_s905x
    armbian_kernel: 5.7.19
    version_branch: beta
```

`version_branch: beta`

5.7.19 in beta

**Comment by dinhchinh82** [comment]
@ophub thank you for your instruction. I can build successfully.
