### ISSUE TITLE
Can't boot s905x3

### ISSUE THREAD

**Issue by inovato-llc** [ophub/amlogic-s9xxx-armbian#560]
**Describe the bug**
Rarely boots from SD card.  Usually goes straight into Android, but after toothpick method, will go into Android Recovery screen.  Out of many dozens of attempts, have only seen it boot once, but even then fails on reboot.

**To Reproduce**
1. Flash Armbian_22.11.0_Aml_s905x3_bullseye_5.10.142_server_2022.09.09.img.gz or Armbian_22.11.0_Aml_s905x3_bullseye_5.15.62_server_2022.09.09.img.gz (I used balena Etcher)
2. insert SD card into slot
3. Power up with toothpick 
4. Goes to Android Recovery screen first time, later builds without toothpick boot to Android

**Expected behavior**
Boot into Armbian

**Screenshots**

**Armbian Version**
 - Kernel Version: both 5.10.y and 5.15.y.  Have been trying this for several weeks with different builds
 - Release: Have tried both Jammy and Bullseye
 - Edition: server

**Device (please complete the following information):**
 - SOC: S095x3
 - Brand: have tried multiple models from various manufacturers.
 - Model X96 Air (desired), but also tried HK1 Box and X96 Max+

**Additional context**
Not sure what I could be missing.  For toothpick, I put it in AV hole until switch clicks.  I wait until boot logo appears.  But have tried longer and shorter times as well.  I hope I am just missing something simple!  Thanks for your help!

**Comment by ysuolmai** [comment]
experienced the same issue with my hk1box. you may want to try another firmware (such as [slimbox tv](https://slimboxtv.ru/) ). 

flash the new firmware, then try the toothpick method again. it worked for me.

**Comment by ysuolmai** [comment]
the original firmware came with my hk1 box could only boot emuelec/coreelec with the toothpick method. However *elec bootloader is not compatible with armbian/openwrt. I guess that's the root cause. so you will need a new and clean firmware.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#124-set-the-box-to-boot-from-usbtfsd
