### ISSUE TITLE
S905X3 Box : Missing Wifi and Ethernet

### ISSUE THREAD

**Issue by xNiux** [ophub/amlogic-s9xxx-armbian#561]
Hi,

I'm trying to install the 22.08 and 22.11 version bullseye on a Magicsee N5+ (S905X3).
System is starting, but I don't have ethernet and wifi. I tried kernel 5.10 and 5.15, but same issue.

Before this installation, I tried the last balbes150 Armbian version (Armbian_20.10_Arm-64_bullseye_current_5.9.0.img) with meson-sm1-x96-air.dtb. Wifi and Ethernet are enabled and operationnal.
Same think with Manjarolinux.

Could you help me please ? What did you need to help me ?
I have the UART debug output available.

**Comment by ophub** [comment]
vi /boot/uEnv.txt
meson-sm1-x96-air.dtb

https://github.com/ophub/amlogic-s9xxx-armbian/blob/c3c2c1ab423e8e54c7d7d2e937f2911a4e73863a/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L76

**Comment by xNiux** [comment]
> ```
> vi /boot/uEnv.txt
> 
> # Modify the value of FTD
> FDT=meson-sm1-x96-air.dtb
> 
> # Save restart test
> sync && reboot
> ```
> 
> If the USB test is normal, `armbian-install` it to emmc option `517`
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/c3c2c1ab423e8e54c7d7d2e937f2911a4e73863a/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L76

You're right ! Thanks a lot !
