### ISSUE TITLE
CM311-1a 网络高负载 死机

### ISSUE THREAD

**Issue by xinshutong** [ophub/amlogic-s9xxx-armbian#562]
Armbian Version
Kernel Version: 5.15.62
Release: jammy (0914)
Edition: server

Device
SOC: 905l3a
Brand: 魔百盒
Model 311-1a yst(2+8G)

使用场景：podman以host模式运行qbittorrent，挂载了一块硬盘。

podman运行qbittorrent，断网情况都发生在网速跑满时，时间不固定，几秒到几个小时不等。
![image](https://user-images.githubusercontent.com/69582651/190526903-164ae548-4b87-4353-b6e9-9bbffaed9671.png)

![IMG_20220916_070433](https://user-images.githubusercontent.com/69582651/190524003-4e09ce67-f787-4c3e-9486-1ec9e7dabfea.jpg)
按动键盘，拔插网线，都无反应,只能断电重启。
以为是2个ip冲突，随将/etc/network/interfaces文件关于eth0全部注释。
ip变为1个，仍会发生断网问题。
此前的几个版本都有这个问题。bullseye jammy 来回刷了好几个固件

这是我另一个相同的设备，运行非常稳定。
![image](https://user-images.githubusercontent.com/69582651/190526694-87e4f4bf-1c31-457c-b808-bce03554ae42.png)

**Comment by ophub** [comment]
不要挑战它的极限，给他留点余地处理其他进程

**Comment by xinshutong** [comment]
![c65719b0718d025f0c61049c0dfd574](https://user-images.githubusercontent.com/69582651/190536809-63bbc6aa-de2d-40c0-be0a-600691eea585.jpg)
采取了你的建议，为其他进程预留了1MB/s左右带宽，工作了一个小时后，又死机了。

**Comment by xinshutong** [comment]
重新插拔网线，网络恢复正常。
![9ac715ceb9d2a7e08e8fb4e984792ca](https://user-images.githubusercontent.com/69582651/190538334-73c4d5a4-bff4-4342-92ae-91bf576e52ec.jpg)

**Comment by xinshutong** [comment]
采取了你的建议，为其他进程预留了1MB/s的带宽，工作一个小时后，网络掉线，重新拔插网线后，网络恢复正常。
日志如下：
[ 6267.299234] ------------[ cut here ]------------
[ 6267.305015] NETDEV WATCHDOG: eth0 (meson8b-dwmac): transmit queue 0 timed out
[ 6267.312395] WARNING: CPU: 0 PID: 0 at net/sched/sch_generic.c:478 dev_watchdog+0x2e4/0x310
[ 6267.320914] Modules linked in: rfkill cpufreq_userspace cpufreq_conservative cpufreq_powersave sunrpc zram sg panfrost gpu_sched snd_soc_meson_axg_sound_card snd_soc_meson_card_utils meson_gxbb_wdt snd_soc_meson_axg_tdmout snd_soc_meson_g12a_tohdmitx snd_soc_meson_codec_glue snd_soc_meson_axg_spdifout snd_soc_meson_axg_frddr meson_vdec(C) videobuf2_dma_contig snd_soc_meson_axg_fifo meson_ir snd_soc_spdif_tx v4l2_mem2mem snd_soc_meson_axg_tdm_interface snd_soc_meson_axg_tdm_formatter tcp_bbr sch_fq ip_tables x_tables
[ 6267.380550] CPU: 0 PID: 0 Comm: swapper/0 Tainted: G         C        5.15.62-flippy-76+o #168
[ 6267.390302] Hardware name: SKYWORTH E900V22C (DT)
[ 6267.397066] pstate: 60000005 (nZCv daif -PAN -UAO -TCO -DIT -SSBS BTYPE=--)
[ 6267.405163] pc : dev_watchdog+0x2e4/0x310
[ 6267.411955] lr : dev_watchdog+0x2e4/0x310
[ 6267.418653] sp : ffffffc008003da0
[ 6267.425263] x29: ffffffc008003da0 x28: 0000000000000001 x27: ffffff807ff36d28
[ 6267.433410] x26: ffffff80008308c0 x25: 00000000ffffffff x24: 0000000000000008
[ 6267.441457] x23: 0000000000000a00 x22: ffffffc00a5f6000 x21: 0000000000000000
[ 6267.449469] x20: ffffff800366041c x19: ffffff8003660000 x18: ffffffffffffffff
[ 6267.457499] x17: 0000000000cdcdcd x16: 00000000ffffe000 x15: 0000000000000004
[ 6267.465555] x14: ffffffc00a6723c0 x13: 0000000000001fff x12: 0000000000000001
[ 6267.473602] x11: 0000000000000000 x10: 0000000000000103 x9 : 6379677ef44e2500
[ 6267.481589] x8 : 6379677ef44e2500 x7 : 0000000000000000 x6 : 0000000000000007
[ 6267.489558] x5 : 0000000000cccccc x4 : 0000000000000001 x3 : 0000000000000000
[ 6267.497459] x2 : ffffff807ff38660 x1 : ffffff807ff368f0 x0 : 0000000000000041
[ 6267.505309] Call trace:
[ 6267.511556]  dev_watchdog+0x2e4/0x310
[ 6267.517746]  run_timer_softirq+0x2d0/0x3f4
[ 6267.523854]  _stext+0xfc/0x2e0
[ 6267.529849]  invoke_softirq+0x78/0xe0
[ 6267.535792]  irq_exit+0x68/0x8c
[ 6267.541687]  handle_domain_irq+0x88/0xe4
[ 6267.547590]  gic_handle_irq+0x68/0xfc
[ 6267.553473]  call_on_irq_stack+0x2c/0x38
[ 6267.559360]  do_interrupt_handler+0x3c/0x50
[ 6267.565261]  el1_interrupt+0x30/0x5c
[ 6267.571125]  el1h_64_irq_handler+0x18/0x24
[ 6267.576949]  el1h_64_irq+0x78/0x7c
[ 6267.582744]  arch_local_irq_enable+0xc/0x2c
[ 6267.588529]  default_idle_call+0x24/0x84
[ 6267.594258]  cpuidle_idle_call+0x68/0x1bc
[ 6267.599917]  do_idle.llvm.11955224262055933116+0x88/0xcc
[ 6267.605611]  cpu_startup_entry+0x24/0x28
[ 6267.611280]  kernel_init+0x0/0x19c
[ 6267.616885]  start_kernel+0x0/0x4bc
[ 6267.622451]  start_kernel+0x39c/0x4bc
[ 6267.627981]  __primary_switched+0xa4/0x7ca4
[ 6267.633489] ---[ end trace cd8303405a3164b5 ]---
[ 6267.639115] meson8b-dwmac ff3f0000.ethernet eth0: Reset adapter.
[ 6280.878504] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 3216000000
[ 6280.966605] meson8b-dwmac ff3f0000.ethernet eth0: PHY [0.1:08] driver [Meson G12A Internal PHY] (irq=38)
[ 6280.975654] meson8b-dwmac ff3f0000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[ 6280.992387] meson8b-dwmac ff3f0000.ethernet eth0: No Safety Features support found
[ 6280.998172] meson8b-dwmac ff3f0000.ethernet eth0: PTP not supported by HW
[ 6281.004957] meson8b-dwmac ff3f0000.ethernet eth0: configuring for phy/rmii link mode
[ 6281.102708] IPv6: ipv6_create_tempaddr: regeneration time exceeded - disabled temporary address support
[ 6282.787968] meson8b-dwmac ff3f0000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[ 6282.795261] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ 6335.646848] [drm] kms: can't enable cloning when we probably wanted to.
[ 6541.193353] [drm] kms: can't enable cloning when we probably wanted to.
[ 6542.266907] [drm] kms: can't enable cloning when we probably wanted to.
[ 6543.624355] [drm] kms: can't enable cloning when we probably wanted to.
[ 7035.385940] meson8b-dwmac ff3f0000.ethernet eth0: Link is Down
[ 7037.983203] meson8b-dwmac ff3f0000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[ 8107.591230] meson_clk_pll_set_rate: pll did not lock, trying to restore old rate 3408000000

**Comment by Yxini** [comment]
我也是发现了QB下载一多就死机，有没有好的方法去限制。

**Comment by xinshutong** [comment]
> 我也是发现了QB下载一多就死机，有没有好的方法去限制。

我另外一台相同设备使用的是 Armbian 22.08.0-trunk Focal with Linux 5.15.48-flippy-74+o
下载非常稳定，没遇到这种问题
可是我找不到旧版镜像了

**Comment by ophub** [comment]
在qb里有网速限制功能，设置个合理值。

**Comment by xinshutong** [comment]
分别尝试添加了cm311专用dtb的和jammy和Bullseye，二者都会发生NETDEV WATCHDOG: eth0 (meson8b-dwmac): transmit queue 0 timed out，但bullseye不会断网，正常使用。

**Comment by xinshutong** [comment]
5.10内核没这个问题，稳定使用两天。

**Comment by wasdqwerdf** [comment]
YST代工也有2+8的配置？我一直以为只有CH代工的才是2+8的

**Comment by xinshutong** [comment]
昨天刷的最新版的5.15.71 jammy  用的docker跑的qbittorrent 感觉还行 cpu负载没有以前离谱了，可以刷了试试
![image](https://user-images.githubusercontent.com/69582651/194682864-5329b997-f503-4b4e-8deb-70cb5763266f.png)

**Comment by uvtofu** [comment]
> YST代工也有2+8的配置？我一直以为只有CH代工的才是2+8的

我猜，题主的机型的定制的。
