### ISSUE TITLE
Can't get it to boot on Beelink GT King

### ISSUE THREAD

**Issue by webepg** [ophub/amlogic-s9xxx-armbian#563]
Hi,

I do have the same problem as this guy [https://github.com/ophub/amlogic-s9xxx-armbian/issues/410](url). I tried several tools (balenaEtcher, Rufus), different USB drives and SD cards. And also different Images. 

I tried the .10 Kernel and replaced the u-boot.bin as well as the text in the uEnv.txt and also tried the .15 Kernel while changing the text in the uEnv.txt file to meson-g12b-gtking.dtb.

After flashing I plug out the power cable put in the SD card or USB drive push and hold the recovery button of the device. The boot Logo stays there for a while and then CoreElec boots. When removing the boot media the boot process is a lot faster so something is going on. I tried the latest jammy images

[https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_09.15.1030/Armbian_22.11.0_Aml_s922x_jammy_5.15.68_server_2022.09.15.img.gz](url)

[https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_09.15.1030/Armbian_22.11.0_Aml_s922x_jammy_5.10.143_server_2022.09.15.img.gz](url)

What am I doing wrong? 

BTW booting CoreElec from a USB device or SD card is working well with the same method

**Comment by ophub** [comment]
The box restores the Android system and enables the usb debugging mode of the Android system.

Download the firmware, flash it into the usb, do not make any modifications by default, you can directly boot from the usb.

**Comment by webepg** [comment]
Ok after a couple of failed installations it worked. I don't know why but it worked. Now I got an ip address but the network manager is not starting. 

thats the error:

 NetworkManager.service - Network Manager
     Loaded: loaded (/lib/systemd/system/NetworkManager.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Fri 2022-09-16 16:53:01 CEST; 2min 47s ago
       Docs: man:NetworkManager(8)
    Process: 1530 ExecStart=/usr/sbin/NetworkManager --no-daemon (code=exited, status=127)
   Main PID: 1530 (code=exited, status=127)
        CPU: 22ms

Sep 16 16:53:01 armbian systemd[1]: NetworkManager.service: Scheduled restart job, restart counter is at 5.
Sep 16 16:53:01 armbian systemd[1]: Stopped Network Manager.
Sep 16 16:53:01 armbian systemd[1]: NetworkManager.service: Start request repeated too quickly.
Sep 16 16:53:01 armbian systemd[1]: NetworkManager.service: Failed with result 'exit-code'.
Sep 16 16:53:01 armbian systemd[1]: Failed to start Network Manager.

I made a couple of reboots but it does not work out. Im not even able to run armbian-config without the internet

**Comment by ophub** [comment]
Does not need to be enabled

**Comment by webepg** [comment]
Yeah but then I can't access the Internet. When booting from USB drive or SD Card it works. I dont know why but everytime I try to install a package via apg-get install it ends in "Segmentation faultsts..."

I just wanted to use the device for OMV but when running this install script for armbian (wget -O - https://github.com/OpenMediaVault-Plugin-Developers/installScript/raw/master/install | sudo bash) it drops out on different postions everytime I run the script. Sometimes it takes 3 secs sometimes 5 min .... I don't get it

**Comment by ophub** [comment]
armbian is like a computer, a mobile phone. As long as the network you connect to is normally assigned an Internet IP to him. By default, you can use the IP assigned by the router to access the Internet without any settings.

**Comment by webepg** [comment]
How can it be installed directly?

**Comment by ophub** [comment]
You go to its official website to see how. Saw it on its website before. I don't know this software.

**Comment by webepg** [comment]
It's not supported. They recommend to install armbian and then run a script that installs OMV. But I think it's not an OMV problem. Even armbian-update gives segmentation faults. Maybe it's my device or the armbian image ..

**Comment by webepg** [comment]
I mean how can apt-get update be an illegal instruction?

**Comment by ophub** [comment]
sudo apt-get update

**Comment by webepg** [comment]
same error

**Comment by ophub** [comment]
Even the `sudo apt-get update` command cannot be executed?

`lsblk`

screenshot

**Comment by webepg** [comment]
<img width="456" alt="Bildschirmfoto 2022-09-17 um 15 03 42" src="https://user-images.githubusercontent.com/75490122/190858332-d99226ee-86f6-4880-9040-fb7c517a9437.png">

as root I cannot run sudo apt-get update. I now used the user I created during the setup there I can run the sudo apt-get update command

**Comment by ophub** [comment]
You are not using emmc now, but usb, and only 2.5 G space can be used.

If you want to use it in usb, expand it: armbian-tf

**Comment by webepg** [comment]
<img width="906" alt="Bildschirmfoto 2022-09-17 um 15 58 32" src="https://user-images.githubusercontent.com/75490122/190860772-2c58edc9-3679-41a3-b499-26e74364d5b3.png">

This command does not work either. Wether with the root user nor with my user and sudo

**Comment by webepg** [comment]
This is how it looks when I boot from eMMC

<img width="394" alt="Bildschirmfoto 2022-09-17 um 16 04 53" src="https://user-images.githubusercontent.com/75490122/190861078-3a112c47-21bb-4189-8d73-2d1085bbac33.png">

**Comment by ophub** [comment]
The error message shows that the usb is full and there is no space. After the first boot, after setting the password, the first thing is to expand the space: armbian-tf

Also you have installed to emmc. Why not remove the usb and restart the system using emmc?

**Comment by ophub** [comment]
Just use emmc

**Comment by webepg** [comment]
armbian-tf gives the same result when running as first command after setting the password. When using emmc the segmentation fault messages appear even during the login process

**Comment by ophub** [comment]
I didn't see your mistake

**Comment by webepg** [comment]
I hope you understand my frustration

**Comment by ophub** [comment]
You re-download the firmware of another kernel version and reinstall it.

Just now, the apt was not allowed to be executed because the usb was not expanded, and the 2.5 G space had been filled.

If you write this crippled usb system to emmc it is also incomplete.

Write emmc for the first time. Do not do other operations on the usb.

**Comment by webepg** [comment]
I tried several times. Either I am not able to login or the install results in a kernel panic. This is soo frustrating ...

**Comment by webepg** [comment]
![photo_2022-09-17_17-19-31](https://user-images.githubusercontent.com/75490122/190864157-c95f15fd-f3ff-4046-965d-4b30b5e8ee73.jpg)

**Comment by webepg** [comment]
This is when I chose btrfs

![photo_2022-09-17_17-22-35](https://user-images.githubusercontent.com/75490122/190864270-ca5f2416-c7c4-4cf7-bfcc-19aafd1f348e.jpg)

It is telling me that it is a success but it's not. After this it does not boot and ends in an kernel panic again

**Comment by webepg** [comment]
![photo_2022-09-17_17-25-23](https://user-images.githubusercontent.com/75490122/190864403-c492156d-1384-48c0-952b-c64ec1435d0f.jpg)

**Comment by webepg** [comment]
I think I found the problem. Even though my device (Orbsmart S86) is a clone of the Beelink GT-King (I also used the gt king dtb during the time I was using CoreElec and it worked) it has its own dtb.img at the CoreElec Project. 

I tried to just copy the file over to my usb drive but I think thats not how it works. 

How can I do that? Here are the SD Card update files: http://www.mediafire.com/file/uxrso5m3syrj152/Orbsmart_S86_907P0_sdcard.zip/file

and here the file Burning Tool update image:
http://www.mediafire.com/file/o80cz04n8ruy8aa/Orbsmart_S86_917P0_WOL.zip
 
Here is the dtb file from the CoreElec Project for the Orbsmart S86 
[g12b_s922x_beelink_gt_king_rev_a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9592683/g12b_s922x_beelink_gt_king_rev_a.dtb.zip)

**Comment by ophub** [comment]
I see from your log that the /usr file was not copied completely. You download today's firmware and try to rewrite the disk

**Comment by webepg** [comment]
It has the same outcome or do you mean the Version that is going to be Build in a couple of hours?
