### ISSUE TITLE
关于JMS578主控硬盘盒挂载不上硬盘问题的解决，大家可以参考下

### ISSUE THREAD

**Issue by colorfullee** [ophub/amlogic-s9xxx-armbian#568]
- 盒子型号：UNT403A
- 镜像：`Armbian_22.11.0_Aml_s905l3a_jammy_5.15.62_server_2022.09.09.img`
- 主控：JMS578硬盘盒
- 硬盘：笔记本机械硬盘，NTFS格式，空磁盘与有数据的磁盘都有试过，Windows中可以正常使用
> 连接上后使用`dmesg`看没有报错，`lsblk`可以看到存储设备路径，`blkid`极少时候可以看到挂载磁盘信息一行，uuid添加到fstab后关机、再开机也无法自动挂载，休眠模式看了下也是关闭的`Unit sleep.target is masked`

> **这边连接上硬盘后仔细看其实是有报错的!**，提示形如`doesn't support dpo or fua`，根据此错误搜索到一个有**参考意义** 的[文档链接](https://zohead.com/archives/linux-usbhdd-err/)，我目前的做法是直接将硬盘使用`DiskGenius` **全盘格式化** 为`ext4`格式，格式完成后接入盒子其中一个USB口后**执行挂载目录命令**即可**正常使用**！

> 目前使用fstab开机自动挂载硬盘还是不行，这个是我的配置 
> `/etc/fstab`
> `UUID=2addb993-edf2-3840-abfd-5acd8175ccbf /mnt/sda1 ext4 defaults,nofail,x-systemd.device-timeout=2,noatime 0 0`

当然现在我已经使用`rc.local`配置文件来实现开机自动挂载目录了

**希望对问题的解决会有所帮助，多谢！**

**Comment by acooler15** [comment]
"doesn't support dpo or fua"这个错误应该不是掉盘的原因。我插U盘上去也会有提示。

**Comment by MDCY9008** [comment]
把usb插一半试试，感觉是接口的问题，还有一个是供电。

**Comment by ophub** [comment]
根据硬盘标示的功率，换盒子的电源，满足盒子、硬盘及其他接入的设备的供电，如12V 5A？

或者使用带独立供电的磁盘盒

**Comment by colorfullee** [comment]
> 根据硬盘标示的功率，换盒子的电源，满足盒子、硬盘及其他接入的设备的供电，如12V 5A？
> 
> 或者使用带独立供电的磁盘盒

目前硬盘用Ext4格式是正常挂载，可以使用的，之前是NTFS格式的时候不行

**Comment by ophub** [comment]
ext4是linux支持的标准格式，这个支持的好
