### ISSUE TITLE
Possible support S905?

### ISSUE THREAD

**Issue by flymike** [ophub/amlogic-s9xxx-armbian#57]
I have got a S905 TV box (Beelink MiniMX 2G/16G) and I tried the closest build (s905x) with the correct dtb file(p200-2G-1Gbit), and copied u-boot-s905.bin to u-boot.ext. The box boots up but stuck at "Starting kernel ..."
Is it possible to make this build work with S905 box? Thx

**Comment by ophub** [comment]
try 5.4 kernel.
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_2021.12.28.0135/Armbian_22.02.0_Aml_s905x_bullseye_5.4.168_2021.12.28.0129.img.gz

**Comment by flymike** [comment]
That is exact build I've tried, boot loop if not copy u-boot-s905.bin to u-boot.ext.

**Comment by ophub** [comment]
`Starting kernel` It is a hint that the dtb file is incorrect.

s905 is `meson-gxbb`, try dtb from: https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/amlogic-dtb

```
meson-gxbb_p201_2G.dtb
meson-gxbb_p200_2G.dtb
meson-gxbb-p200.dtb
meson-gxbb-p201.dtb
```

**Comment by flymike** [comment]
OK, this combination works :)
- Copy u-boot-s905.bin to u-boot.ext
- Using meson-gxbb-vega-s95-telos.dtb in uEnv.txt
Now, question is, can I install to eMMC?
I was using balbes150 build before, sd/usb installation worked fine but "brick" the box after installed to eMMC... yes I will try your build, hope the internal installation works.

**Comment by ophub** [comment]
You try `5.10 kernel` is available. Download the firmware of `the 5.10 kernel of s905d`, and modify `dtb and u-boot` according to yours.

Based on your feedback, I added this box to the support list, and it can be generated directly by default when building armbian next time.

If you can restore the system, you can write emmc without any worries.

**Comment by flymike** [comment]
Thank your very much. I will try 5.10 kernel. Yes I don't mind "brick" the box and I can unbrick it anytime :)
It was an old box I just want make it as pihole server etc., This is where I bought it...
https://www.gearbest.com/tv-box-mini-pc/pp_321409.html?wid=1433363#goodsDetail

**Comment by ophub** [comment]
`/usr/sbin/armbian-install`

When writing emmc test, first add the installation script to this box, the content is as follows:
```
# Amlogic GXBB Family(s905)
61:Beelink MiniMX:s905:meson-gxbb-vega-s95-telos.dtb:u-boot-s905.bin:NA:NA:Beelink Mini MX Ver 1.0
```

**Comment by flymike** [comment]
Good news and bad news :)
Good news:
- 5.10 kernel with s905 u-boot and gxbb-vega-s95-telos.dtb work perfect with SD
- Ethernet and wifi all work

Bad news:
- Install to emmc failed
- ddbr failed
- Probably all because the mmcblk2 io error 
`
[   87.108847] blk_update_request: I/O error, dev mmcblk2, sector 0 op 0x0:(READ
) flags 0x80700 phys_seg 1 prio class 0
[   87.119105] blk_update_request: I/O error, dev mmcblk2, sector 0 op 0x0:(READ
) flags 0x0 phys_seg 1 prio class 0
[   87.127651] Buffer I/O error on dev mmcblk2, logical block 0, async page read
`

The box is "dead" for now... I need time to unbrick it.

**Comment by ophub** [comment]
local file: `/usr/sbin/armbian-install`

There is no corresponding option for this box in the existing [armbian-install](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-install#L74) script, you add a `61`, the content is as follows:

```
# Amlogic GXBB Family(s905)
61:Beelink MiniMX:s905:meson-gxbb-vega-s95-telos.dtb:u-boot-s905.bin:NA:NA:Beelink Mini MX Ver 1.0
```

**Comment by ophub** [comment]
Some boxes are locked to prevent writing, such as [MXQ PRO+](https://www.geekbuying.com/item/MXQ-PRO--Android-7-1-1-Amlogic-S905X-4K-TV-BOX-2GB-16GB-385604.html) of `s905`.

**Comment by flymike** [comment]
Yes I did add the 61 entry to armbian-install script.

I read this forum on Armbian before and tried that trick but couldn't accomplished... maybe you can get some idea from there
https://forum.armbian.com/topic/18902-s905-failed-to-boot-from-emmc/?do=findComment&comment=132455

I can use both build in SD/USB, I just want the internal emmc installation working... I can test if you want to implement but it is OK if it is too complicated (probably no one still using this box...)

**Comment by ophub** [comment]
Several s905 boxes I have seen so far do not support writing emmc.

Generally speaking, I recommend using armbian on TF/SD/USB, because emmc is not written so it will not affect the original system. And you can choose a larger capacity TF card according to your needs.

There is a famous saying that it is my right not to write emmc, but it is your fault not to let me write emmc.

**Comment by ophub** [comment]
According to your feedback, I have already packaged the s905 firmware, which can be used directly in the future without manual modification of dtb and u-boot.

https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_2021.12.28.1621

**Comment by flymike** [comment]
The s905 build works great, thx.
FYI, the wifi seems no longer works in this build? I do not use wifi anyway, just noticed that in the armbian_config...
Still try to find a way to utilize the eMMC for system, 16G is wasted otherwise, also performance would be better than SD.

**Comment by ophub** [comment]
Thanks for reminding, the device description and link have been updated.

**Comment by flymike** [comment]
s905 firmware #2021.12.28.1621
- First boot no IP, reboot fixes it
- Has to set the locale (en_CA in my case) during the first time setup, then WiFi is detected, and works fine

**Comment by ophub** [comment]
u-boot will be reloaded, so the ip obtained at the first boot will be disconnected immediately, and the system will automatically start the second boot and obtain the final ip. This is done to be compatible with kernel above 5.10.y+

**Comment by bangkawarah** [comment]
I have an S905 with the micox brand, I tried installing openwrt to emmc then after that my micox bricked, how can I use it normally again, because I have searched for the micox android box firmware but there is no micox M12 PLUS type on the internet
