### ISSUE TITLE
what bootloader can i used with my box w95 Amlogic S905W

### ISSUE THREAD

**Issue by skysurf** [ophub/amlogic-s9xxx-armbian#570]
i my box is this;   https://pt.gearbest.com/tv-box/pp_736121.html

w95  Amlogic S905W 1.2GHz WiFi Android 7.1 2GB DDR3 + 16GB eMMC

I have done download of Armbian_22.11.0_Aml_s905w_bullseye_5.15.68_server_2022.09.17.img.xz

i use blatcher to flash to sd card

i already use on the past the FDT /dtb/amlogic/meson-gxl-s905w-p281.dtb and it's working.

but now i chage  extlinux.conf.bak to:

label Armbian
    kernel /zImage
    initrd /uInitrd
    fdt /dtb/amlogic/meson-gxl-s905w-p281.dtb
    append root=UUID=6ded43b9-25f0-42ff-9ec5-7c182e05be72 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 loglevel=1 voutmode=hdmi disablehpd=false overscan=100 sdrmode=auto

and i change  boot.ini to:

ODROIDN2-UBOOT-CONFIG

# set load addresses
setenv env_addr 0x10400000
setenv kernel_addr 0x11000000
setenv initrd_addr 0x13000000
setenv dtb_addr 0x1000000

if test "${devtype}" = ""; then setenv devtype "fdt /dtb/amlogic/meson-gxl-s905w-p281.dtb"; fi

# load uEnv.txt
load ${devtype} ${devnum} ${env_addr} uEnv.txt && env import -t ${env_addr} ${filesize}
setenv bootargs ${APPEND}

# Load kernel, dtb
load ${devtype} ${devnum} ${kernel_addr} ${LINUX}
load ${devtype} ${devnum} ${initrd_addr} ${INITRD}
load ${devtype} ${devnum} ${dtb_addr} ${FDT}
fdt addr ${dtb_addr}

# boot
booti ${kernel_addr} ${initrd_addr} ${dtb_addr}

and i change the file name u-boot-s905x-s912.bin to u-boot.ext

**Describe the bug**
the problem is when i select the backup and update on box android software, (update the file) , it reboots mas no longer give pictures, and it seems it freezen.

**To Reproduce**
do reboot update on terminal. 

**Expected behavior**
that armbian begin to appear for then i install on the box

**Screenshots**

**Armbian Version** 22.11
 - Kernel Version: [5.15.68]
 - Release: bullseye
 - Edition: server

**Device (please complete the following information):**
 - SOC: Amlogic S905W
 - Brand: w95
 - Model w95

**Additional context**
thanks for the help

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#126-selection-of-bootstrap-file

**Comment by ophub** [comment]
```
cd /opt
wget https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/kernel_5.10.143_5.15.68/5.10.143.tar.gz
tar -xf 5.10.143.tar.gz
cd 5.10.143/
armbian-update
```

**Comment by skysurf** [comment]
i only need to modify the file name of dtb in /boot/uEnv.txt. and i don't have change anything.
but on my box: backup e restore app, when i select update nothing appears to select the update. white screen
only if i open the .apk  terminal and write: reboot update it show 2 times the 4k (logo of box ) and then blank screen, only says no hdmi, nothig hapen. i'am burning the imagem from a sd card, i already test with other and it's he same thing.



on other distro armbian with the dtb: meson-gxl-s905w-p281.dtb the wireless won't work and blutooth ether, but i don't needed, i plug ethernet cable.


i don't undertand this step:

add a line to /etc/amlogic_model_database.conf

109:W95:s905w:meson-gxl-s905w-p281.dtb:u-boot-s905x-s912.bin:NA:NA

Use armbian-install writing to emcc is to select the 109 number you added

thanks

**Comment by ophub** [comment]
Your device is now not in the install list option, the added line is your configuration information.

**Comment by skysurf** [comment]
what is file system type:
ext4 or
btrfs ?

**Comment by ophub** [comment]
It will be all right

**Comment by skysurf** [comment]
hi, do you know why my syslog is always saying:

Sep 21 22:42:25 armbian hostapd[4787]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Sep 21 22:42:25 armbian hostapd[4787]: Failed to set up interface with /etc/hostapd/hostapd.conf
Sep 21 22:42:25 armbian hostapd[4787]: Failed to initialize interface
Sep 21 22:42:25 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Sep 21 22:42:25 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Sep 21 22:42:25 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Sep 21 22:42:27 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 933.
Sep 21 22:42:27 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Sep 21 22:42:27 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Sep 21 22:42:28 armbian hostapd[4788]: Configuration file: /etc/hostapd/hostapd.conf
Sep 21 22:42:28 armbian hostapd[4788]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.

do you know how to solved ?

thanks

**Comment by ophub** [comment]
/etc/hostapd.conf

**Comment by skysurf** [comment]
thanks i used:
apt remove hostapd

and it solve ...

thanks for your help ... 

you are a spectacle.
I already installed the home assistant on the w95 box, thanks to you, thank you very much.

But I have a problem, my box only has 16 gb of emmc (disk), and with the installation of H.A. , which is Supervisor 2022.09.1
, with the backups and addons I only have 0.7 GB free. do you happen to know of a way to be able to connect an ssd or a pen to the usb, and pass the database and backups, the addons, there for example?

if it helps this is my df 👍 

df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            832M     0  832M   0% /dev
tmpfs           194M   11M  183M   6% /run
/dev/mmcblk2p2   14G   13G  881M  94% /
tmpfs           966M     0  966M   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/zram2      948M  136K  884M   1% /var/tmp
/dev/mmcblk2p1  255M  107M  149M  42% /boot
/dev/zram1       49M   26M   20M  58% /var/log
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/688d83b103da9ee4064a091373eee4e560de85497f0cf4587ad58098c33ac483/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/253fcf2d07a5147f46b8d7f74a906155a6e931b07909220c49a3db3862340862/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/29d17384e57e6a4986fb4e899de1b979a095f5652291980ed9beca1231a0bbf3/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/a4c800a541a01af726a9662329cd3ff6a9a345e99486e6c675450568e7edc837/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/d8425da8e8e1573a6f2857346c9b4a72e20b5620b1046d5dd2ae191b40f01a4c/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/98bf940db1cc178b5a33107ee583d897e2e589935d075683c6444ad35747617c/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/01b40f812dfd793a280a7f2cfde5ade46daf1bbe6e81bbef1ae2f6c134c802e8/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/ade34851ff53b429ebcf381a9c3e2e03200dac88922b7e4c0e66b1fcc0784b77/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/5a1c59909ec5685241842496f0f74730e7eb348039c6e305cfa82a3fe259de23/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/c5f1be5798d539a48654b8e7fb93680c916c73db32a76003e319f8d14a89c329/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/ef1505e1258af548a57e579fcaf642e2cf9c462fc3cd9561f926ad3b8e3dc4bc/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/dc90e38d83d753a6677fc6edd85bd603222f46782b1ead0278987e91ad69ce52/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/758684acff38fa8c20523c57dcc06b668bdf98682a992a78d72fbd68caf24e57/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/db0435426761d09084038ef696cc2029fc0fc0b3f092f95a9dba28bdb939b42e/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/571dc2701592792985b1f53657869f2a90a9e1cef56c80e3b6b9cc7329c0b0bf/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/aabdb5041ee8ba35f46f10d358efd68f8668caf933fa270121d796b95fb5ec39/merged
overlay          14G   13G  881M  94% /var/lib/docker/overlay2/08559bb9db7ba94111787b82e31e17162c966c84936891bcc7c0a7e96ba13619/merged
tmpfs           194M     0  194M   0% /run/user/0

thanks very much... for all the help

you are 5 stars ;)

**Comment by ophub** [comment]
There are two common practices that can be expanded:
1. Plug in a USB or an external hard drive. The hard drive should use a hard drive case that can supply power independently to ensure a stable power supply.

2. Mount the shared storage in the LAN to the Armbian system through protocols such as SMB/CIFS.

**Comment by ophub** [comment]
Send the result of your command:

`cat /etc/ophub-release`

**Comment by skysurf** [comment]
homeassistant:~:# cat /etc/ophub-release
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
FDTFILE='meson-gxl-s905w-p281.dtb'
UBOOT_OVERLOAD='u-boot-s905x-s912.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT=''
KERNEL_VERSION='5.10.144'
SOC='s905w'
K510='1'
DISK_TYPE='emmc'
PACKAGED_DATE='2022-09-17'
homeassistant:~:# 


thanks a lot ...



here are two common practices that can be expanded:

Plug in a USB or an external hard drive. The hard drive should use a hard drive case that can supply power independently to ensure a stable power supply.

Mount the shared storage in the LAN to the Armbian system through protocols such as SMB/CIFS.


But how i tell to home assistant to write the data base, and the other files like addons , and etc  on the new  hard drive ?
do you have any video, tutorial / guide that i can follow for that ?

thanks for all of yours efforts. ;) 

thanks in advance...

**Comment by ophub** [comment]
You are the first person to boot the 5.10 kernel in the s905w box. In the past, only 5.4/5.15 can be used in the s905w series. This is a gratifying discovery, and it can be used normally after you have successfully written to emmc.

**Comment by skysurf** [comment]
hi, i already writen the arbian to the emmc.
my kernel is 5.10 but 5.15 is better right ?  i already done:
armbian-update, but it's says that is already on the newest.

yes my ha is running on docker. but i have low space. 
can you explaine better how i can put a usb ssd hard disk, and write to it, on HA.

 can you tell how i  write the data base, and the other files like addons , and etc on the new hard drive ?
do you have any video, tutorial / guide that i can follow for that ?

thanks for all your help. thanks

**Comment by ophub** [comment]
There are two common practices that can be expanded:

Plug in a USB or an external hard drive. The hard drive should use a hard drive case that can supply power independently to ensure a stable power supply.

Mount the shared storage in the LAN to the Armbian system through protocols such as SMB/CIFS.

**Comment by skysurf** [comment]
But with smb/cifs protocols, will not cause a slow Ethernet speed and a lot of traffic over the lan ? And conflict on my router?

**Comment by skysurf** [comment]
hi, can i use a usb pen drive and use this comand to expand my hard disk space ?

armbian-tf

According to the prompt, enter `e` to expand the remaining space to the current system partition and file system, and enter `c` to create a new third partition.

?

**Comment by ophub** [comment]
armbian-tf is only suitable for emmc, and other usb can be used when plugged in. You mount it to a fixed location and point the docker storage to this location.

**Comment by skysurf** [comment]
sorry i don't understand very well my armbian (and homeassistant)  is running on emmc, so i can use armbian-tf command right ? 
can you tell me (explain or have a toturial to use a usb and how i mount it to a fixed location and point the docker storage to this location ?
do you have a youtube video explain, that or a tutorial ? 

thanks in advanced

**Comment by ophub** [comment]
docker uses the -v parameter to specify the path, pointing to the path of your mounted large storage.

**Comment by skysurf** [comment]
but i must move my docker folder, to the new path (of my mounte point of large storage right ? how i do that ? 
thanks ...

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/37fc83b60c0cd3c6c2d46845b687f43418e8af64/build-armbian/common-files/rootfs/usr/share/ophub/armbian-software/software-command.sh#L36-L40

**Comment by andrecigarro** [comment]
> on other distro armbian with the dtb: meson-gxl-s905w-p281.dtb the wireless won't work and blutooth ether, but i don't needed, i plug ethernet cable.

Hi @ophub! Apologies for reopening this thread. I am testing this exact same box with openwrt, but wireless is indeed not working. If i add a USB WiFi adapter, it works flawless, still I do need the two network interfaces. 

Any tip?

Also, writing to EMMC is not currently working for me. No boot, black screen after install. Even after following @skysurf path.

Thank you in advance!

**Comment by ophub** [comment]
use usb hub
