### ISSUE TITLE
bullseye_5.10.143版本号和bullseye_5.15.68有啥区别，该怎么选择

### ISSUE THREAD

**Issue by elunez** [ophub/amlogic-s9xxx-armbian#571]
Armbian_22.11.0_Aml_s905d_bullseye_5.10.143_server_2022.09.17.img.gz
Armbian_22.11.0_Aml_s905d_bullseye_5.15.68_server_2022.09.17.img.gz

这两个除了内核区别，还有其他区别吗

**Comment by ophub** [comment]
无其他差别

**Comment by lovelylain** [comment]
建议选用5.15内核的，5.10不能直接用原厂bootloader，要套一层boot.ext，兼容性方面可能差一些

**Comment by elunez** [comment]
> 建议选用5.15内核的，5.10不能直接用原厂bootloader，要套一层boot.ext，兼容性方面可能差一些

了解了，谢谢

**Comment by elunez** [comment]
> 无其他差别

稳定性和兼容性方面更推荐使用哪个内核

**Comment by ophub** [comment]
4个孩子，老大老二老三老四，哪个好呢？这无法下定论，天天有调皮的，也有听话的时候。

每个内核都在不断升级中，升级就意味着曾经有BUG被解决了，但还有新BUG正在发现和解决中。看心情使用即可。

**Comment by roseybear098765** [comment]
[jammy_5.15.100_server_2023.03.16.img.gz]
[jammy_6.1.18_server_2023.03.16.img.gz]
这两个版本，不知道要怎么选啊

**Comment by ophub** [comment]
都一样，安装任意一个，内核可以自由换其他的

**Comment by roseybear098765** [comment]
哦，好的呢
