### ISSUE TITLE
你好，请问下怎么删除系统自带的虚拟内存

### ISSUE THREAD

**Issue by elunez** [ophub/amlogic-s9xxx-armbian#572]
Armbian_22.11.0_Aml_s905d_bullseye_5.10.143_server_2022.09.17.img.gz

系统自带了900M多虚拟内存，我如果用 armbian-swap  2 设置2G的虚拟内存，重启后就变成了 2.9G。

有办法删除自带的 900M 虚拟内存吗

**Comment by ophub** [comment]
那个好像删不了，一重启又有了，系统根据内存大小自动创建了一个。

**Comment by xcray** [comment]
![image](https://user-images.githubusercontent.com/26018728/191013387-326fb771-ecf8-4997-aa00-67ac7953214d.png)
这个我比o大回答的对，嘻嘻

**Comment by ophub** [comment]
重启了不会再创建？

我之前调试这个创建虚拟内存的脚本时，脚本会先删除全部，再创建用户指定大小的虚拟内存，但是我发现每次重启了，系统还会创建一个。

**Comment by xcray** [comment]
> 重启了不会再创建？
> 
> 我之前调试这个创建虚拟内存的脚本时，脚本会先删除全部，再创建用户指定大小的虚拟内存，但是我发现每次重启了，系统还会创建一个。

重启还会有，我也不知道怎么让它重启也不创建（rc.local里加上swapoff给它关掉倒勉强算个办法）。

**Comment by elunez** [comment]
我这边测试重启就自动创建了> 重启了不会再创建？
> 
> 
> 
> 我之前调试这个创建虚拟内存的脚本时，脚本会先删除全部，再创建用户指定大小的虚拟内存，但是我发现每次重启了，系统还会还原它自带的虚拟内存。

**Comment by 326652397** [comment]
我照这个方法重启后也不会自动创建了
#删除SWAP分区
在刷新完armbian20.10后发现又462MB的SWAP分区。想着本来8G空间都不够了就删掉swap然后合并到/根分区。但是fdisk -l后发现armbian的分区形式跟正常x86的完全不一样。使用之前的方法：CentOS/Debian/ubuntu删除SWAP分区，扩容/根目录。是不可行的。那么该如何解决呢。目前已知armbian的swap是挂载在内存上的。然后会定时写入emmc。其实我都没有swap需求，原来的1G内存已经足够使用。
现在的需求是删除swap分区。好在使用swap分区的盘符搜到了下面大佬的教程。按教程删掉了swap。因为版本略有不同，所以实际操作过程中也会有一点区别。最主要是盘符会不一样，请按自己的盘符改。下面是教程。
删除zram的swap
查看现有的swap
# cat /proc/swapsFilename Type Size Used Priority/dev/zram1                              partition 922748 0 5
或者
# swapon -sFilename Type Size Used Priority/dev/zram1                             partition 922748 0 5
释放指定的swap
# swapoff /dev/zram1
禁用zram服务
修改文件/etc/default/armbian-zram-config，改为：
ENABLED=false
禁用zram的/var/log
zram的/var/log会每15分钟检查一下使用率，超过75%时会刷入eMMC磁盘。
同样，由于我用的SSD硬盘，可以禁用掉这种机制。
修改 /etc/default/armbian-ramlog，如下：
ENABLED=false
禁用定时截断任务
修改文件 /etc/cron.d/armbian-truncate-logs，如下：
# */15 * * * * root /usr/lib/armbian/armbian-truncate-logs
禁用另一个任务
修改文件 /etc/cron.daily/armbian-ram-logging，如下：
#!/bin/sh# /usr/lib/armbian/armbian-ramlog write >/dev/null 2>&1
重启服务
重启后发现，/var/log.hdd/为空了。
本方案来自于该大佬分享：https://note.abeffect.com/articles/2020/04/03/1585847764766.html
现在遗留的问题就是/boot分区居然有488M。让本不富裕的EMMC只有5.8G可用空间，装完宝塔和软件后只剩3G可用了。能在/boot分区挤点空间出来就好了。

**Comment by ophub** [comment]
有些盒子boot可以挤出一个G，手动按块起始结束位置分一下。

**Comment by elunez** [comment]
找到办法了，成功删除掉了
1、查看现有的swap
```bash
# cat /proc/swaps
Filename				Type		Size	Used	Priority
/dev/zram0                            partition	922748	0	5
```
2、释放掉
```bash
swapoff /dev/zram0
```
3、禁用zram服务

修改文件 `/etc/default/armbian-zram-config` ，改为：
```bash
ENABLED=false
```

重启后，不会再自动创建 zswap

<img width="705" alt="image" src="https://user-images.githubusercontent.com/42142420/191446618-f85dadd8-69bc-43aa-98a3-7d542d3babce.png">

**Comment by xcray** [comment]
zram整个禁用，似乎也不是个好主意。
swap嘛，如果物理内存够用这个确实可以关掉，但临时文件、日志这些，没有了zram会不会就变成了直接写emmc？性能下降不说，寿命多少也是个问题。

**Comment by elunez** [comment]
> zram整个禁用，似乎也不是个好主意。 swap嘛，如果物理内存够用这个确实可以关掉，但临时文件、日志这些，没有了zram会不会就变成了直接写emmc？性能下降不说，寿命多少也是个问题。

那就启用 zram，关闭自动创建 zswap

```bash
# enable the armbian-zram-config service?
ENABLED=true

# Zram swap enabled by default, unless set to disabled
SWAP=false
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/c1ee3c54bc64175318aaab04c1293f751d93a42c

这个方案挺好，不自建swap就使用系统默认值，从内存中自动分配。
如果使用了自建swap就禁用系统自动分配，改为手动分配的大小。

**Comment by elunez** [comment]
> [c1ee3c5](https://github.com/ophub/amlogic-s9xxx-armbian/commit/c1ee3c54bc64175318aaab04c1293f751d93a42c)
> 
> 你的方案已经添加到armbian-swap了 这个方案挺好，不自建swap就使用系统默认值，从内存中自动分配。 如果使用了自建swap就禁用系统自动分配，改为手动分配的大小。

我是不是用 armbian-update 就可以更新这个功能？

**Comment by xcray** [comment]
armbian-update是升级内核，用armbian-sync。显然没好好看o大辛辛苦苦写的文档啊。。。

**Comment by elunez** [comment]
> armbian-update是升级内核，用armbian-sync。显然没好好看o大辛辛苦苦写的文档啊。。。

了解了，谢谢
