### ISSUE TITLE
请问是否支持安装openMediaVault?

### ISSUE THREAD

**Issue by tabcdn** [ophub/amlogic-s9xxx-armbian#574]
请问是否支持安装openMediaVault?

**Comment by ophub** [comment]
支持安装，但之前使用OMV官网的一键安装脚本仍有小bug

**Comment by tabcdn** [comment]
请问OMV官网的一键安装脚本是在哪里，我在OMV官网没有找到，只看到了Download页面下载ISO镜像（USB安装方式）；感谢！https://www.openmediavault.org/download.html

**Comment by ophub** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/installScript

**Comment by tabcdn** [comment]
感谢

**Comment by AlexBokhankovich** [comment]
@tabcdn could you please let me know if your installation of OMV succeeds. I tried installing in on vontar x3 (s905x3) about a month ago and after installation everything time related was broken. Could you please run _**timedatectl**_ after omv installed and box rebooted to see if **_timedatectl_** command executes without any errors?

**Comment by tabcdn** [comment]
> 

I tried to install OMV by using OpenMediaVault-Plugin-Developers installScript today , but not succeed. There is a message that says "Unsupported version.  Only Debian 10 (Buster) and 11 (Bullseye) are supported.  Exiting...", so I guess maybe this editon is not supported.
