### ISSUE TITLE
s905x2 usb3.0不正常工作

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#575]
大神，我有一个外贸盒子，s905x2+2G+8G一个TF和一个usb3.0，用u200的dtb可以启动armbian,但是内存只有1Ｇ，网卡正常，USB3.0不工作，没电流，安卓下正常工作，换s905l3a的dtb，可以启动，显示2G内存，网卡正常，但USB3.0死活不正常工作，看了一下dtb，发现usb3.0是走pice通道，我不知道我这个盒子是不是单独芯片控制，我找到一个原生dts（g12a-unt413a-l3a-gd-u212-2g原生.dts下载地址是：https://wwt.lanzoub.com/iaXtP0c1300h）上面好像是单独一个usb3.0控制，但没办法启动，求大神帮忙把这个和s905l3a的dtb重合一下，感谢

**Comment by ophub** [comment]
重复发贴，这个关闭了。在你重发的另一一个里讨论吧
