### ISSUE TITLE
s905x2 usb3.0不正常工作

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#576]
大神，我有一个外贸盒子，s905x2+2G+8G一个TF和一个usb3.0，用u200的dtb可以启动armbian,但是内存只有1Ｇ，网卡正常，USB3.0不工作，没电流，安卓下正常工作，换s905l3a的dtb，可以启动，显示2G内存，网卡正常，但USB3.0死活不正常工作，看了一下dtb，发现usb3.0是走pice通道，我不知道我这个盒子是不是单独芯片控制，我找到一个原生dts（g12a-unt413a-l3a-gd-u212-2g原生.dts下载地址是：
https://wwt.lanzoub.com/iaXtP0c1300h
上面好像是单独一个usb3.0控制，但没办法启动，求大神帮忙把这个和s905l3a的dtb重合一下，感谢

**Comment by ophub** [comment]
这个我不会，不了解怎么添加pcie，我请教一下f大，随后回复你。

**Comment by ophub** [comment]
f大看了你发的源码，这不是pcie的，s9xxx平台只有1条pcie，pcie与usb3是复用同一个端口，但这个dts里pcie是关闭的。

![image](https://user-images.githubusercontent.com/68696949/191250468-fbbf56a6-2bb1-45b3-96c6-b154f994e5d0.png)

![image](https://user-images.githubusercontent.com/68696949/191250515-3a48fc7e-01b1-4e1f-9c2b-9ce9bb41021f.png)

这里usb3与pcie共用一个时钟。对比了dts,和hk1 x96这些的android版dts没有明显区别。

**Comment by gzxief** [comment]
> f大看了你发的源码，这不是pcie的，s9xxx平台只有1条pcie，pcie与usb3是复用同一个端口，但这个dts里pcie是关闭的。
> 
> ![image](https://user-images.githubusercontent.com/68696949/191250468-fbbf56a6-2bb1-45b3-96c6-b154f994e5d0.png)
> 
> ![image](https://user-images.githubusercontent.com/68696949/191250515-3a48fc7e-01b1-4e1f-9c2b-9ce9bb41021f.png)
> 
> 这里usb3与pcie共用一个时钟。对比了dts,和hk1 x96这些的android版dts没有明显区别。

你没明白我的意思，我用U200.dtb或x96max-rmii.dtb或meson-g12a-s905l3a-cm311.dtb或meson-g12a-s905l3a-e900v22c.dtb可以启动armbian，但是USB3.0不能正常工作，反编译U200.dtb或x96max-rmii.dtb或meson-g12a-s905l3a-cm311.dtb或meson-g12a-s905l3a-e900v22c.dtb这些文件，发现USB3.0和PCIE共用一个时钟（正如你所说），而我发给你的这个dts文件里，是单独运行USB3.0，不走PCIE通道，但把这个DTS编译为dtb，就不能启动armbian

**Comment by gzxief** [comment]
感谢了各位大神，可能我这个盒子不能运行armbian，但是可以运行coreelec（s905x2_2G.dtb），正常wifi和USB3.0
