### ISSUE TITLE
Possibility to add to docker logitechmediaserver

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#579]
hello will it be possible to add to docker the img logitechmediaserver (https://hub.docker.com/r/lmscommunity/logitechmediaserver)

**Comment by ophub** [comment]
![Snip20220922_1](https://user-images.githubusercontent.com/68696949/191686952-3ca56268-6a31-4815-89e1-bba8296ea4f3.png)

I have tested various directories, and neither local music nor network music can be loaded and played. So give up the integration.
