### ISSUE TITLE
开机后会持续输出代码

### ISSUE THREAD

**Issue by kerncoola** [ophub/amlogic-s9xxx-armbian#58]
HK1Box，通过tf卡写入emmc，接入电源后，不进行任何操作，会一直输出代码，请问下这是系统日志还是错误信息，如何关闭？，谢谢。
![image](https://user-images.githubusercontent.com/13283995/147529521-c81c5a46-6f51-4b00-933e-e921176b54f0.png)

**Comment by kerncoola** [comment]
这时已经可以通过SSH连接客户端了，LAN测试能达到600Mbps，WiFi能用，还能搜到5GWiFi，但没连WiFi，网线更稳。

**Comment by kerncoola** [comment]
另外还有个问题，固件会频繁发布releases，如果我已经安装armbian，想要更新，是通过apt update就行还是要重新下载固件刷入。

**Comment by ophub** [comment]
开机后持续输出代码是启动过程的输出，这是必须显示的无法关闭。

安装一个版本后，可以随时升级到最新，不需要重新安装。

软件包更新：通过 `sudo apt-get update && sudo apt-get upgrade -y && sudo apt-get dist-upgrade -y` 将软件包升级到最新。
内核更新：通过 `armbian-update 5.10.xx` 的方式更新最新版内核。

**Comment by kerncoola** [comment]
> 开机后持续输出代码是启动过程的输出，这是必须显示的无法关闭。

开机跑代码这个是正常的，我刚才应该没有表达清楚，就是在开机后，出现登录提示时，还会有代码出来，此时未操作键盘，不知道是不是个bug，理论上出现登录提示后屏幕上除非自己输入内容，一般是不会额外出现其它内容的。

我那张图片也没有拍全，上面其实已经有armbian@:，出现一会后就被滚动的代码淹没了，此时ssh是可以连接了，说明系统已经启动完成，跑代码阶段应该已经过去了吧。

**Comment by ophub** [comment]
那是u-boot重载了，每次启动，你到路由器里看，会发现一个mac地址有2个ip，第一次启动后还会再加载一次，第二次加载完成后得到的ip才是最终的。这是为了支持5.10+的内核，我在5.4里也默认启用了。忽视他吧，这样做除了代码多重跑了点，十几秒的等待是为了更好的兼容高版本的内核。

**Comment by kerncoola** [comment]
明白了，谢谢
