### ISSUE TITLE
N1，外网无法通过外网登录SSH。

### ISSUE THREAD

**Issue by leizhiren** [ophub/amlogic-s9xxx-armbian#580]
正常把版本5.15写入U盘并写入emmc，一切使用都正常。但是发现内网能正常通过ipv4地址和ipv6地址访问登录SSH，但是外网无论使用IPV4地址还是IPV6地址却怎么都无法访问和登录SSH，奇怪的是能ping通。iptables和ip6tables怎么改都没用。求助

**Comment by leizhiren** [comment]
Ipv4地址显示有2个，IPV6地址显示有不止两个。无论用哪个地址，外网都不行。内网却没问题。

**Comment by leizhiren** [comment]
其他的内网设备，在外网使用ipv6访问没有问题，可以排除路由问题。

**Comment by ophub** [comment]
我几个Armbian盒子在不同的地方放着，几个都是远程外网ipv4地址，ssh端口映射访问一年了。

**Comment by leizhiren** [comment]
不是IPV4映射，是IPV6直连啊

**Comment by leizhiren** [comment]
2408:8256:c83:8096:414c:6a0e:c520:262

提示连接被拒绝。

**Comment by leizhiren** [comment]
root
574863304
端口65535

**Comment by leizhiren** [comment]
<img width="567" alt="image" src="https://user-images.githubusercontent.com/24837873/191962079-9a45c14b-7505-474b-9bac-b36708b7ef7c.png">
<img width="629" alt="image" src="https://user-images.githubusercontent.com/24837873/191962106-dc33ea28-cbff-4e90-8c76-4adfa10dfa72.png">

**Comment by leizhiren** [comment]
怎么弄呀？没遇到过这种问题。局域网随便访问，外网就访问不到。

**Comment by xinshutong** [comment]
![image](https://user-images.githubusercontent.com/69582651/193407451-fd0001d3-4395-4e3f-a3e5-87262b066ada.png)
![image](https://user-images.githubusercontent.com/69582651/193407462-1f5bf655-c6ab-4da6-8f5d-1df875082d2c.png)
这是开放所有内网ipv6设备的端口 ，觉得不安全可以自行google掩码怎么设置。
