### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by wukibaka** [ophub/amlogic-s9xxx-armbian#581]
o佬。请问一下，n1的两个dtb有啥区别？如果要在docker上跑openwrt当旁路由的话用哪个dtb会好一点？

**Comment by ophub** [comment]
第一个：meson-gxl-s905d-phicomm-n1.dtb

另外一个是软流控，在某些交换机不支持流控时可以用这个。

**Comment by wukibaka** [comment]
> 第一个：meson-gxl-s905d-phicomm-n1.dtb
> 
> 另外一个是软流控，在某些交换机不支持流控分流时可以用这个。
> 

谢谢o佬
