### ISSUE TITLE
兩個networking問題

### ISSUE THREAD

**Issue by jackcctse** [ophub/amlogic-s9xxx-armbian#582]
1. 开机錯誤failed to start raise network interface。自己增加timeout 到30s解決。預設10s是否太少？
`● networking.service - Raise network interfaces
     Loaded: loaded (/lib/systemd/system/networking.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Sat 2022-09-24 01:17:24 HKT; 1min 38s ago
       Docs: man:interfaces(5)
    Process: 629 ExecStart=/sbin/ifup -a --read-environment (code=exited, status=1/FAILURE)
   Main PID: 629 (code=exited, status=1/FAILURE)
        CPU: 370ms

Sep 24 01:17:19 armbian ifup[720]: Listening on LPF/eth0/fc:7c:02:4d:11:2d
Sep 24 01:17:19 armbian ifup[720]: Sending on   LPF/eth0/fc:7c:02:4d:11:2d
Sep 24 01:17:19 armbian ifup[720]: Sending on   Socket/fallback
Sep 24 01:17:19 armbian ifup[720]: DHCPDISCOVER on eth0 to 255.255.255.255 port 67 interval 8
Sep 24 01:17:24 armbian systemd[1]: networking.service: start operation timed out. Terminating.
Sep 24 01:17:24 armbian ifup[629]: Got signal Terminated, terminating...
Sep 24 01:17:24 armbian ifup[629]: ifup: failed to bring up eth0
Sep 24 01:17:24 armbian systemd[1]: networking.service: Main process exited, code=exited, status=1/FAILURE
Sep 24 01:17:24 armbian systemd[1]: networking.service: Failed with result 'timeout'.
Sep 24 01:17:24 armbian systemd[1]: Failed to start Raise network interfaces.`

2. dhcp取得2个IP，怎样解決？
`4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 9e:61:4e:18:c6:aa brd ff:ff:ff:ff:ff:ff permaddr fc:7c:02:4d:11:2d
    inet 192.168.11.207/24 brd 192.168.11.255 scope global dynamic noprefixroute eth0
       valid_lft 43118sec preferred_lft 43118sec
    inet 192.168.11.208/24 brd 192.168.11.255 scope global secondary dynamic eth0
       valid_lft 43121sec preferred_lft 43121sec
    inet6 fe80::82ad:8874:e86c:b369/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
`

**Comment by jackcctse** [comment]
補充2， 由log發現，一個IP由NetworkManager取得，另一个由dhclient取得。

**Comment by ophub** [comment]
启动时由u-boot重载生成了两个ip，第一个在5秒左右作废，获得第二个ip，只有这个是可以正常使用的。

在上游接入的路由器中可以看到这两个ip的动态分配显示过程。

**Comment by xcray** [comment]
也有个说法：两个IP分别是networking service （dhclient）和NetworkManager各自获取的，解决方法是在/etc/network/interfaces里eth0下面加上一句：client no，只让NM去获取IP。实测有效，不过根据文档，interfaces里配置的网卡NM应该不再管理这个网卡才对。比较干净的做法是interfaces里干脆把eth0的内容彻底删掉或注释掉，只让NM管理。

**Comment by ophub** [comment]
如果NetworkManager.service是启用状态的话，需要关闭 NetworkManager.service

```
systemctl stop NetworkManager.service
systemctl disable NetworkManager.service
init 6
```

**Comment by jackcctse** [comment]
> 启动时由u-boot重载生成了两个ip，第一个在5秒左右作废，获得第二个ip，只有这个是可以正常使用的。
> 
> 在上游接入的路由器中可以看到这两个ip的动态分配显示过程。

實測2個IP都通，是真的重覆了。
現在停用 NetworkManager 是OK的。但這樣就不能用wlan了吧？armbian-config裡面也沒了Network那個選項。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#127-network-settings

**Comment by uvtofu** [comment]
> 我是让networkmanager管理eth0（netplan生成配置文件），把interfaces的eth0注释掉。关于networkmanager读取interfaces，是因为networkmanager的插件ifupdown引起的

我的感觉ifupdown和networking.service是一回事。/etc/network/interfaces这个文件也是ifupdown安装带来的。
NetworkManager和ifupdown (networking.service）是并列且独立的两件事。
我测试的结果，卸载ifupdown。只剩下NetworkManager可以照常启动和管理lan和wifi。

我也是小白，欢迎交流。
