### ISSUE TITLE
当我升级到最新的内核5.19.11时，出现了网卡问题

### ISSUE THREAD

**Issue by imzlh** [ophub/amlogic-s9xxx-armbian#583]
当我尝试升级内核后正常启动，但是网卡似乎出现问题导致获取不到ip
![E1C3466B-1D44-44E6-BAE6-69B69F8C750E](https://user-images.githubusercontent.com/114276136/192080706-26b4f732-258a-4699-830a-b09f0da68cdb.jpeg)

B863AV3.1-M的机器，cpu是S905L3A
之前用内核5.15.55都正常的,仅仅执行了armbian-update 5.19.11就这样了
不知道是不是内核的问题

**Comment by imzlh** [comment]
更糟糕的是现在连磁盘也挂载不了，或者直接input/output error
事实上，我没有碰磁盘和机器
![Uploading CDF03E15-41F6-4807-B998-59D40B93E1E8.jpeg…]()

**Comment by imzlh** [comment]
好吧，我自己解决了这个问题
是dtb的锅，等我换回了x大的蓝牙dtb，问题自动解决
不知道这个dtb到底加了什么奇怪的东西

**Comment by ophub** [comment]
meson-g12a-s905l3a-cm311.dtb
换这个dtb搞定？

**Comment by imzlh** [comment]
不是这个，是u200。这个dtb用着特别舒服，不会启动时花屏，就是频率略低于e900v22c的

**Comment by imzlh** [comment]
还有我很奇怪为为什么你编译的armbian有5.10和5.15的就是没有5.19的

**Comment by ophub** [comment]
上游kernel.org是内核官网。5.19不是长期内核，从发布到结束只有2个月。而5.4/5.10/5.15的更新周期是5年。

只要有任意一个版本的固件，可以用armbian-update更新至其他系列的内核。所以不用生成全部版本。
