### ISSUE TITLE
章鱼星球: dtb没有正确配置三色指示灯

### ISSUE THREAD

**Issue by happyme531** [ophub/amlogic-s9xxx-armbian#584]
如题，默认配置下开机三色指示灯全亮且无法控制 (三色灯封装在一起，看起来亮白灯)
/sys/class/leds下没有设备节点

通过反编译原版固件中指示灯控制程序，找到了GPIO配置:  
绿色: gpio506(GPIOAO_5), 高有效
蓝色: gpio507(GPIOAO_6), 高有效
红色: gpio510(GPIOAO_9), 高有效

希望作者可以稍微改一下dts, 把指示灯配置加上。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/12c78c6a2f70323f240d45872f475fcc4bd136f7

f大在几个内核里添加好了，你下载解压，覆盖同名文件（/boot/dtb/amlogic），反馈下结果。

[meson-gxm-octopus-planet.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9651304/meson-gxm-octopus-planet.dtb.zip)

**Comment by happyme531** [comment]
三色指示灯工作完全正常，感谢大佬。

另外想问一下，在使用这个repo的armbian时，S912 CPU每个核心的最高频率只有1GHz，远远达不到宣传的2.0GHz/之前刷过的另外一个Armbian固件能达到的1.5GHz。我尝试修改dtb,但发现没有cpu的opp表可供修改。这是bug还是某些硬件限制？

**Comment by ophub** [comment]
就像led的添加这样，自己添加代码即可

**Comment by jiuliking** [comment]
> 

你的频率改好了吗
