### ISSUE TITLE
版本更新问题

### ISSUE THREAD

**Issue by haoarthur** [ophub/amlogic-s9xxx-armbian#585]
感谢ophub无私奉献，我观察到几乎是每天或者几天都会有一个版本，Armbian_22.08.0_Aml_s905d_jammy_5.15.62_server_**2022.08.31**.img.gz，以打包日期为名，请问如果我安装某一日期版本后，想更新到最新日期的包，是不是使用“armbian-sync”就可以更新到当前最新日期的包？谢谢

**Comment by ophub** [comment]
```
# 更新脚本至最新
armbian-sync


# 更新软件包至最新
sudo apt-get update
sudo apt-get upgrade -y
sudo apt-get dist-upgrade -y
sudo apt-get --purge  autoremove -y
sudo apt-get autoclean -y
```

**Comment by jackcctse** [comment]
> ```
> # 更新脚本至最新
> armbian-sync
> 
> 
> # 更新软件包至最新
> sudo apt-get update
> sudo apt-get upgrade -y
> sudo apt-get dist-upgrade -y
> sudo apt-get --purge  autoremove -y
> sudo apt-get autoclean -y
> ```
> 
> 这样就和最新版一样了

請問內核會一起升級嗎？還是要再打armbian-update?

**Comment by ophub** [comment]
内核独立更新，使用 armbian-update

**Comment by haoarthur** [comment]
谢谢，受教了
