### ISSUE TITLE
Armbian-config command was missing, the try of retoring it by reinstallation or changing apt source didn't work

### ISSUE THREAD

**Issue by Matrix-Chen** [ophub/amlogic-s9xxx-armbian#586]
**Describe the bug**
Armbian-config command was missing, the try of retoring it by reinstallation or changing apt source didn't work.

**Screenshots**
armbian:~:# sudo apt-get install armbian-config
Reading package lists... Done
Building dependency tree... Done
Package armbian-config is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'armbian-config' has no installation candidate

**Armbian Version**
 - Kernel Version: 5.10.145
 - Release:  jammy
 - Edition: server

**Device (please complete the following information):**
 - SOC: S912
 - Brand: Octopus Planet

**Comment by ophub** [comment]
This file is not a software package and cannot be installed by apt. You need to overwrite it again.
