### ISSUE TITLE
docker-compose的生命周期要结束了，是否需要将docker-compose更换为docker-compose-plugin？

### ISSUE THREAD

**Issue by acooler15** [ophub/amlogic-s9xxx-armbian#589]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/04e24983cbe34a6677c97b2e9992e12a5ba9612e/build-armbian/common-files/rootfs/usr/sbin/armbian-docker#L81

[announcing compose v2 general availability](https://www.docker.com/blog/announcing-compose-v2-general-availability/#proposed-compose-v1-end-of-lie-timeline)中好像是说10月份结束对compose v1的安全更新。
compose v2的安装方法：[https://docs.docker.com/compose/install/linux/](https://docs.docker.com/compose/install/linux/)

不过安装docker-compose-plugin后`docker-compose`命令就不能用了，想用需要自己alias了

**Comment by ophub** [comment]
这两个不能共存吗？都安装会冲突吗？

**Comment by acooler15** [comment]
可以共存，compose v2默认不支持docker-compose命令。所以并不影响



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月27日(周二) 晚上7:22
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] docker-compose的生命周期要结束了，是否需要将docker-compose更换为docker-compose-plugin？ (Issue #589)




 
这两个不能共存吗？都安装会冲突吗？

**Comment by Avtoremgarage** [comment]
Добрый день.

**Comment by Avtoremgarage** [comment]
Please help with installing Arabian on X96MAX 4/64 Wi Fi+BT Lan 1Gb, in EMC.
I do the installation according to the instructions, I tried it via SD and via USB. The installation is going well.
But after installation, the TV BOX can start well from EMMC, but after rebooting via REBOOT or POWER OFF/ON, the TV BOX does not start, on the first screen the error Could not initialize PHY ethernet@ff3f0000, and then it does not start. And this can happen endlessly. But if you let the console stand without power for more than 5 minutes, then the download is good from EMMC, until the next reboot.

**Comment by ophub** [comment]
@Avtoremgarage 
Language packs are installed by themselves via armbian-config

**Comment by ophub** [comment]
@acooler15 
目前安装的docker-compose包在脚本中暂时没有用到，软件中心armbian-software通过docker run拉取的镜像，没有使用yml模板。

如果可以同时安装这两个包，就都安装，或者改为plus都可以

**Comment by Avtoremgarage** [comment]
![2022-09-26 16-48-21](https://user-images.githubusercontent.com/81529562/192561572-56da4053-b5f1-46b0-bfa6-ce30eba5510b.JPG)

**Comment by Avtoremgarage** [comment]
Sorry, I created my own theme.
