### ISSUE TITLE
MECOOL KI Pro EMMC Install

### ISSUE THREAD

**Issue by martinlanger90** [ophub/amlogic-s9xxx-armbian#59]
I have a MECOOL KI Pro with CoreELEC installed onto EMMC.
Can I boot armbian from you from USB/SD/TF and install it onto EMMC right away?

Thank you.

**Comment by ophub** [comment]
https://m.gearbest.com/tv-box-mini-pc/pp_629409.html

Is it this one? You can test the firmware of s905d.
If necessary, you can modify the value of dtb in /boot/uEnv.txt, which is the same as CoreELEC.

**Comment by martinlanger90** [comment]
Yes it is that one. But it doesn't boot from USB/TF (microSD Card). 
Did the same as for CoreELEC. Stops at Mecool logo. CoreELEC is actually installed to EMMC. 
Any advice how to boot armbian? changed uenv.txt to meson-gxl-s905d-mecool-ki-pro.dtb

**Comment by martinlanger90** [comment]
Okay, installed original Android again. Tried to boot from microSD card. Did not work either. Hangs at mecool logo.

**Comment by ophub** [comment]
Download the 5.4 kernel firmware and unzip it. Double-click the .img file, open uEnv.txt, and modify the name of the dtb file. Change it and rewrite it to usb.
First turn on the USB debugging mode of the box in the Android system. Then plug in usb and power to start.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/router-config/README.md#1010-turn-on-the-usb-disk-boot-mode-of-the-amlogic-s9xxx-tv-box

**Comment by martinlanger90** [comment]
Thank you. Exactly that worked. Tried with 5.10 all the time. Didn't work... 5.4 worked via USB stick

**Comment by ophub** [comment]
Try to save u-boot-s905x-s912.bin as u-boot.ext

**Comment by ophub** [comment]
Can the firmware of the 5.4 kernel be booted from usb?

**Comment by martinlanger90** [comment]
Yes. Now I'm using 5.4 with nothing changed besides the dtb in uEnv.txt and works flawlessly now. Trying to install to internal after configuring wifi

**Comment by ophub** [comment]
Use 5.10 kernel, Try to save `u-boot-p201.bin` as `u-boot.ext` and changed besides the dtb in `uEnv.txt `

**Comment by martinlanger90** [comment]
Okay, I'll try that in a second.

**Comment by martinlanger90** [comment]
Okay, works with 5.10 kernel as well. The key was to use USB Stick and remove CoreELEC from NAND as that changes the boot partition on mmcblk as it seems. 
Using USB boot in Android and correct dtb (*ki-pro.dtb) with nothing works as well with 5.10. 
Thank you for the great support.

**Comment by ophub** [comment]
According to my method, the 5.10 kernel can also be used?

**Comment by martinlanger90** [comment]
> Download the `5.4 kernel` firmware and unzip it. Double-click the .img file, open `uEnv.txt`, and modify the name of the dtb file to `meson-gxl-s905d-mecool-ki-pro.dtb`. Change it and rewrite it to usb. First turn on the `USB debugging mode` of the box in the Android system. Then plug in usb and power to start.

Yes. that did it with 5.10.

**Comment by ophub** [comment]
Okay, it's okay to use 5.10 instead of 5.15.

I would like to ask you to try again: Is it possible to use u-boot.ext under the 5.4 kernel, so that `u-boot and dtb can use the same one`

**Comment by martinlanger90** [comment]
yes, it is possible with u-boot.ext under 5.4 kernel.

**Comment by ophub** [comment]
Thank you for your testing and sharing. I will record your contribution on the list of contributors.

**Comment by ophub** [comment]
Is this box a gigabit network card?

**Comment by martinlanger90** [comment]
Yes it is a gigabit nw card :)

**Comment by martinlanger90** [comment]
PHY [0.2009087f:00] driver [RTL8211F Gigabit Ethernet] (irq=51) 
also plugged in and shows gigabit connection, speed is okay, around 25-35 MB/s sometimes more, but never over 50 MB/s

**Comment by ophub** [comment]
Brand Name: Hero Iand
GPU: Quad-core Mali-450
Ethernet: 1000M
Wireless: Yes
Bluetooth: Yes
CPU: Amlogic S905 Quad-core 64-bit
eMMC: 16GB
Memory: 2G DDR3

**Comment by ophub** [comment]
Thank you for sharing. I will add the box you share to the support list and record your contribution at the same time. Thank you.

**Comment by looun** [comment]
hello , i try to boot from SD but not work.
I have following this step:

1. write last image Armbian_24.2.0_amlogic_s905d_jammy_6.1.66_server_2023.12.08.img into microsd
3. on SD i have rename u-boot-p201.bin as u-boot.ext
4. on SD i have changed the dtb in uEnv.txt as meson-gxl-s905d-mecool-ki-pro.dtb.

power on in boot in recovery mode but Hangs at mecool logo and than boot android.

thanks for help.

PS: CoreELEC work without any issue from microSD.

**Comment by nabla44** [comment]
Hello, I have tried to boot from SD or USB key an armbian version in a Mecool KI pro but nothing work.
I have tried different .img by renaming u-boot-p201.bin as u-boot.ext and  changed the dtb in uEnv.txt as meson-gxl-s905d-mecool-ki-pro.dtb.
However, any version is able to boot. 
Thank for your help if someone recently succeed to do it.
Regards,
