### ISSUE TITLE
X96MAX, Could not initialize PHY ethernet@ff3f0000

### ISSUE THREAD

**Issue by Avtoremgarage** [ophub/amlogic-s9xxx-armbian#591]
Please help with installing Armbian on X96MAX 4/64 Wi Fi+BT Lan 1Gb, in EMC.
I do the installation according to the instructions, I tried it via SD and via USB. The installation is going well.
But after installation, the TV BOX can start well from EMMC, but after rebooting via REBOOT or POWER OFF/ON, the TV BOX does not start, on the first screen the error Could not initialize PHY ethernet@ff3f0000, and then it does not start. And this can happen endlessly. But if you let the console stand without power for more than 5 minutes, then the download is good from EMMC, until the next reboot.
![2022-09-26 16-48-21](https://user-images.githubusercontent.com/81529562/192562653-dce8c419-a567-4030-b575-d5bf5e26125f.JPG)

**Comment by ophub** [comment]
What is the chip of the wired network card?

**Comment by Avtoremgarage** [comment]
![2022-09-27 19-38-32](https://user-images.githubusercontent.com/81529562/192563528-58801285-36d7-46c1-acc1-f80572bcff48.JPG)

**Comment by ophub** [comment]
A photo of the motherboard to take a complete

**Comment by Avtoremgarage** [comment]
> A photo of the motherboard to take a complete
![2022-09-27 22-18-33](https://user-images.githubusercontent.com/81529562/192567773-e2c135d5-f8ed-44a6-87a8-38ad7c8015b9.JPG)
![Uploading 2022-09-27 22-19-14.JPG…]()
![2022-09-27 22-19-30](https://user-images.githubusercontent.com/81529562/192567809-20114ab7-087b-4769-aca4-e203ef1df664.JPG)
![Uploading 2022-09-27 22-19-39_1664292043629.JPG…]()

**Comment by Avtoremgarage** [comment]
After a few turns on and off, ARMBIAN booted up
![2022-09-27 22-15-23](https://user-images.githubusercontent.com/81529562/192569633-ea1db8bf-7783-4e6c-85aa-1692ff2b47a2.JPG)
![2022-09-27 22-16-04](https://user-images.githubusercontent.com/81529562/192569641-9b95da98-659e-4c19-8071-c265e496c79c.JPG)

**Comment by Avtoremgarage** [comment]
I understand that the problem is in the driver, I need it for the g5009cg. And in the repositories, the driver is from rtl8211f.

Please help me solve this issue. I'm a beginner in this direction.

**Comment by ophub** [comment]
![image](https://user-images.githubusercontent.com/68696949/192704026-5664ead9-ee0e-4819-8a45-f6ddc6d837eb.png)

this is rtl8211f

**Comment by ophub** [comment]
You can start and use it like this

**Comment by Avtoremgarage** [comment]
Yes, I found a chip on the back, it really is RTL8211F.

That is, the driver in the repository is correct.

But then why does an error pop up when rebooting. However, the error is not permanent. Launches are both successful and not. Nothing to do with anything.
![2022-09-28 13-49-04](https://user-images.githubusercontent.com/81529562/192710167-c4923992-5173-4c45-a838-54c737205824.JPG)

**Comment by Avtoremgarage** [comment]
At the same time, in the mode of operation of the TV BOX with Android. Everything works well, both WI-FI and ETH.

That is, the problem is not in the hardware.

**Comment by ophub** [comment]
From the picture you posted, it seems that the wireless network access failed error. The previous version of x96max used the 8822cs driver, this driver is unstable, just use the wired network.

**Comment by ophub** [comment]
`hdparm  -t /dev/mmcblk2`
Test the speed of your emmc to see if there is a compatibility problem

**Comment by ophub** [comment]
```
MYBOX_UBOOT="/usr/lib/u-boot/mybox-bootloader.img"
DEV_EMMC="/dev/mmcblk2"
dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=1 count=444
dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1
sync && sleep 3
reboot
```

Try restoring the Android bootloader to see if it still reports an error

**Comment by Avtoremgarage** [comment]
> `hdparm -t /dev/mmcblk2` Test the speed of your emmc to see if there is a compatibility problem
> 
> Which kernel version of the firmware are you using?

From the latest releases, I have tried all versions of assemblies, for S905x2

**Comment by Avtoremgarage** [comment]
WI-FI works well. But if you connect the cable to ETH, the download looks like this. 
Everything is interrupted

![2022-09-28 14-09-55](https://user-images.githubusercontent.com/81529562/192742154-73d84376-e4df-4d2f-995e-d8cee90b6ddc.JPG)
![2022-09-28 14-08-08](https://user-images.githubusercontent.com/81529562/192742160-becfe5e3-b1ca-4ad4-bf8d-d4d966b1b0c5.JPG)

**Comment by Avtoremgarage** [comment]
> `hdparm -t /dev/mmcblk2` Test the speed of your emmc to see if there is a compatibility problem
> 
> Which kernel version of the firmware are you using?

![2022-09-28 16-31-21](https://user-images.githubusercontent.com/81529562/192744431-0d27d439-b61d-4e06-a98b-c1fd1264a7f8.JPG)

**Comment by Avtoremgarage** [comment]
> ```
> MYBOX_UBOOT="/usr/lib/u-boot/mybox-bootloader.img"
> DEV_EMMC="/dev/mmcblk2"
> dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=1 count=444
> dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1
> sync && sleep 3
> reboot
> ```
> 
> Try restoring the Android bootloader to see if it still reports an error

Excuse me, but can you explain in a simple way what these commands are,,?

I completed them, and everything started working well for me. Boot from EMMC, both with connected and disconnected ETH.

Only the start window disappeared, before the inscription STARTING KERNEL

**Comment by ophub** [comment]
When you use armbian-install to install the system to emmc, the mainline u-boot is written by default. The above command is to restore the original bootloader of the Android system. These are two different bootstrap files. Trying to fix your long startup time with errors.

Your soc is s905x3, right?

**Comment by Avtoremgarage** [comment]
SoC S905x2.

When installing, I selected the ID:301.

After your additional code, everything worked perfectly, both WI-FI and ETH. And launch with EMMC.

thank you very much!!!

**Comment by ophub** [comment]
You can use the `armbian-install no` command in the future, ignoring the installation of the mainline u-boot
