### ISSUE TITLE
cannot boot armbain from usb flash driver

### ISSUE THREAD

**Issue by zouplus** [ophub/amlogic-s9xxx-armbian#592]
**Describe the bug**
cannot boot armbain from usb flash driver

**To Reproduce**
1. Go to 'Android TV'
2. Click on 'libreelec'
3. Scroll down to 'ok'
4. See error：The TV System doest not boot from usb flash driver（I test many usb flash driver）

**Expected behavior**
Run armbian install user interface，or entry armbian

**Screenshots**
still is android TV System user interface

**Armbian Version**"Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.71_server_2022.09.29.img"

**Device (please complete the following information):**
 - SOC: S905l3a
 - Brand:魔百盒
 - Model 900v22d

-------------------------
thank our geekers，and I wanna boot the armbian with libreelec.apk in TV System (I have many system such as coreelec 、armbian 、emuelec they arm install in different tf card，befromI launch libreelec.apk，I will install tf card or usb flash driver in tv box）

**Comment by zouplus** [comment]
感谢大佬付出。我目前还没有安装完成armbian在魔百盒900v22d上面。另外我在恩山上看到说，armbian系统的引导无法从libreelec中启动。这样我就比较迷茫，是否在刷完系统后每次启动还需要通过adb才能启动armbian，armbian是否可以直接安装在tf卡，并且通过libreelec 可以启动外置的armbian，这样方便像启动coreelec就插入corelec的u盘、启动armbian就放armbian的u盘

**Comment by zouplus** [comment]
我用“balenaEtcher”完成写入armbian的img，插入后无法进入armbian(Armbian_22.11.0_Aml_s905l3. 15.71_server_2022.09.29.img)；重启盒子也没有反应。不知道怎么进行下一步。文档上说用adb连接，最后还需安装在tf中。但是如果我使用了libreelec ，是否还能引导？

**Comment by ophub** [comment]
盒子的系统是安卓系统时，可以从usb启动。引导是适配了安卓系统，其他系统不行。

armbian写入emmc后，也可以从usb启动其他系统。

**Comment by acooler15** [comment]
libreelec.apk好像也是执行的`reboot update`命令。另外更换U盘后可能会需要重新引导，这个需要自己测试下。建议在EMMC中安装一个使用uboot的系统（如果对Android的TV系统没需求）

**Comment by zouplus** [comment]
> 盒子的系统是安卓系统时，可以从usb启动。引导是适配了安卓系统，其他系统不行。
> 
> armbian写入emmc后，也可以从usb启动其他系统。
> 
> 只要从安卓系统运行一次adb即可，以后就可以从usb启动了。也可以安装一个xxx.apk，运行引导从usb启动

——-
那是否可以把armbian安装在tf上呢？我想保留tv系统作为盒子系统

**Comment by zouplus** [comment]
> libreelec.apk好像也是执行的`reboot update`命令。另外更换U盘后可能会需要重新引导，这个需要自己测试下。建议在EMMC中安装一个使用uboot的系统（如果对Android的TV系统没需求）

我用libreelec.apk 启动不了armbian，但是可以启动coreelec

**Comment by zouplus** [comment]
![1BE77E97-AA7F-4E77-83F7-9DA8E4851AF0](https://user-images.githubusercontent.com/100817707/193068262-ede4e881-881e-4862-ab89-83deb2323fb2.jpeg)

**Comment by zouplus** [comment]
![C20E1C83-1E3F-4888-BD11-DEB56C666491](https://user-images.githubusercontent.com/100817707/193068397-37c4814e-24dc-437d-b4fc-430bf13d5abd.jpeg)

**Comment by zouplus** [comment]
------------------
@ophub 我似乎找到了问题。并且肯定复现：
步骤1：安卓恢复出厂设置
步骤2：插入刷好armbian的系统
步骤3：armbian关机
步骤4：插入其他系统：coreelec
步骤5：corele启动
步骤6：关机
步骤7：插上armbian 优盘
问题复现。似乎到了步骤4会设置掉uboot？但是恢复出厂设置后就可以使用armbian了

**Comment by zouplus** [comment]
同时我找到了一个关于本问题的解决方法：但是操作之后发现没有解决...
https://post.smzdm.com/p/ad2vo52k/

**Comment by uvtofu** [comment]
> 同时我找到了一个关于本问题的解决方法：但是操作之后发现没有解决... https://post.smzdm.com/p/ad2vo52k/

我在小米盒子4上的经验，供参考，
1、买到Amlogic刷机神器，插入盒子的HDMI接口
2、运行Linux版的Amlogc线刷工具（命令行），参数指定仅烧录bootloader分区
几秒钟就可以恢复盒子的bootloader分区。

**Comment by zouplus** [comment]
是否有比较好的方法让armbian 也用和corelec一样的启动方法呢？能比较完美的解决启动问题，感谢大佬能回复一下呢

**Comment by xcray** [comment]
早就有文档说过，ce启动后就不能再直接启动armbian了，原因据分析是ce启动过程中会修改env分区

**Comment by zouplus** [comment]
所以是否可以有比较好的适配方案，既能满足对coreelec、emeuelec的启动又能满足对armbian的启动呢？
