### ISSUE TITLE
xt_geoip 

### ISSUE THREAD

**Issue by jackcctse** [ophub/amlogic-s9xxx-armbian#593]
```
# modprobe xt_geoip
modprobe: FATAL: Module xt_geoip not found in directory /lib/modules/5.15.70-flippy-77+o
```

請問怎樣增加這個模組？官方教程是apt install linux-headers-xxx xtables-addons-dkms，但这是自定的kernel，沒有對應的linux-headers。

**Comment by jackcctse** [comment]
linux-headers 似乎已經在/usr/src下面。但直接apt install xtables-addons-dkms不成功。請問是什么原因？

```
Building for 5.15.70-flippy-77+o
Building initial module for 5.15.70-flippy-77+o
Error!  Build of xt_ACCOUNT.ko failed for: 5.15.70-flippy-77+o (aarch64)
Make sure the name of the generated module is correct and at the root of the
build directory, or consult make.log in the build directory
/var/lib/dkms/xtables-addons/3.19/build/ for more information.
dpkg: error processing package xtables-addons-dkms (--configure):
 installed xtables-addons-dkms package post-installation script subprocess returned error exit status 7
Errors were encountered while processing:
 xtables-addons-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by jackcctse** [comment]
gcc: error: unrecognized command-line option '-Qunused-argument
s'
gcc: error: unrecognized command-line option '-Qunused-argument
s'
gcc: error: unrecognized command-line option '-Qunused-argument
s'
gcc: error: unrecognized command-line option '-Qunused-argument
s'
gcc: error: unrecognized command-line option '-mno-global-merge
'
gcc: error: unrecognized command-line option '-mno-global-merge
'
gcc: error: unrecognized command-line option '-mno-global-merge
'
gcc: error: unrecognized command-line option '-mno-global-merge
'
gcc: error: unrecognized command-line option '-fsplit-lto-unit'
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/xtables
-addons/3.19/build/extensions/compat_xtables.o] Error 1
make[1]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command-line option '-fsplit-lto-unit'
make[1]: *** [scripts/Makefile.build:289: /var/lib/dkms/xtables
-addons/3.19/build/extensions/xt_CHAOS.o] Error 1
gcc: error: unrecognized command-line option '-fsplit-lto-unit'
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/xtables
-addons/3.19/build/extensions/pknock/xt_pknock.o] Error 1
make[1]: *** [scripts/Makefile.build:552: /var/lib/dkms/xtables
-addons/3.19/build/extensions/pknock] Error 2
gcc: error: unrecognized command-line option '-fsplit-lto-unit'
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/xtables
-addons/3.19/build/extensions/ACCOUNT/xt_ACCOUNT.o] Error 1
make[1]: *** [scripts/Makefile.build:552: /var/lib/dkms/xtables
-addons/3.19/build/extensions/ACCOUNT] Error 2
make: *** [Makefile:1900: /var/lib/dkms/xtables-addons/3.19/bui
ld/extensions] Error 2
make: Leaving directory '/usr/src/linux-headers-5.15.70-flippy-
77+o'

**Comment by ophub** [comment]
Manually compile a complete custom kernel from the kernel source code and add the configuration you want

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

**Comment by jackcctse** [comment]
搞了一天，實在搞不定... 請問ophub 有什么辦法？

我要編譯的xtables-addons是外部的modules，請問應該怎樣編？

有嘗試先自編kernel，armbian-update安裝，然后 ./configure && make但失敗，錯誤代碼如下。似乎kernel及 modules要用同一編譯器。
```
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: Ubuntu clang version 14.0.0-1ubuntu1
  You are using:           gcc (Ubuntu 11.2.0-19ubuntu1) 11.2.0
  CC [M]  /mnt/sda1/xtables-addons-3.21/extensions/ACCOUNT/xt_ACCOUNT.o
gcc: error: unrecognized command-line option '-Qunused-arguments'
gcc: error: unrecognized command-line option '-mno-global-merge'
gcc: error: unrecognized command-line option '-fsplit-lto-unit'

```

改成./configure && make CC=clang還是失敗。這個log看不懂。
```
Xtables-addons 3.21 - Linux 5.15.71
if [ -n "/lib/modules/5.15.71-geoip/build" ]; then make -C /lib/modules/5.15.71-geoip/build M=/root/xtables-addons-3.21/extensions modules; fi;
make[3]: Entering directory '/usr/src/linux-headers-5.15.71-geoip'
  CC [M]  /root/xtables-addons-3.21/extensions/ACCOUNT/xt_ACCOUNT.o
/bin/sh: 1: scripts/basic/fixdep: Exec format error
make[5]: *** [scripts/Makefile.build:289: /root/xtables-addons-3.21/extensions/ACCOUNT/xt_ACCOUNT.o] Error 126
make[5]: *** Deleting file '/root/xtables-addons-3.21/extensions/ACCOUNT/xt_ACCOUNT.o'
make[4]: *** [scripts/Makefile.build:552: /root/xtables-addons-3.21/extensions/ACCOUNT] Error 2
make[3]: *** [Makefile:1900: /root/xtables-addons-3.21/extensions] Error 2
make[3]: Leaving directory '/usr/src/linux-headers-5.15.71-geoip'
make[2]: *** [Makefile:468: modules] Error 2
make[2]: Leaving directory '/root/xtables-addons-3.21/extensions'
make[1]: *** [Makefile:497: all-recursive] Error 1
make[1]: Leaving directory '/root/xtables-addons-3.21'
make: *** [Makefile:382: all] Error 2

```

**Comment by jackcctse** [comment]
支持到5.17了，估計不是这個原因。我在ubuntu 22.04上也能編譯，是 5.15.0-48-generic。
無論如何我后面也試試5.10， 雖然希望不太。


```
v3.20 (2022-04-10)
==================

* Support for Linux 5.17
```

**Comment by jackcctse** [comment]
換5.10的也不行。放棄了，改用ipset。
