### ISSUE TITLE
network devices not working on X96Max_Plus_ 2101W

### ISSUE THREAD

**Issue by ctonton** [ophub/amlogic-s9xxx-armbian#594]
I am unable to find a functional dtb for the X96Max_Plus_ 2101W device.  It will boot using the meson-sm1-x96-max-plus-q2.dtb but without networking.  The device has a W522A wireless module and JL2101 ethernet chip.  Is there any way to add support for this device?  I have attached the _aml_dtb.PARTITION and the extracted .dts files from the stock android firmware if that will help.
[dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9679457/dtb.zip)

**Comment by ophub** [comment]
meson-sm1-x96-max-plus.dts

**Comment by ophub** [comment]
what soc?

**Comment by ctonton** [comment]
s905x3

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/736e8387f2f90ab4798664753cd243d7d3ea4f5f/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts#L136
