### ISSUE TITLE
openvfd x96maxplus.conf file fix

### ISSUE THREAD

**Issue by nostroff** [ophub/amlogic-s9xxx-armbian#595]
Very minor issue...

File: /usr/share/openvfd/conf/x96maxplus.conf

Please change:
functions='usb apps setup sd hdmi cvbs'

To:
functions='alarm usb play pause colon lan wlan'

**Comment by ophub** [comment]
Have you tested and called these options?

**Comment by nostroff** [comment]
Oops. My mistake. Using h96max-x3.conf is the correct choice (tested by issuing commands like echo alarm > /sys/devices/platform/openvfd/leds/openvfd/led_off).
