### ISSUE TITLE
hk1box的LED灯有大佬点亮了吗

### ISSUE THREAD

**Issue by jsdfhasuh** [ophub/amlogic-s9xxx-armbian#596]

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led_screen_display_control.md

**Comment by huapox** [comment]
`armbian-led 16` LED那些灯可亮。
---
@ophub 另请教下，如何让电源灯点亮(绿色高亮 不在LED板上的那个)？  当前是1小绿+1小红同时亮的。

**明细：**
1）hk1box 4g 128g, armbian应该用的10.2号的 kernel5.10。 
2）刷入了emmc, 当前不能直接从emmc启动 外插tf后再指向mmcbk2p2可进emmc的系统。
3）dtb已切换到votar-x3的， 当前网卡已是千兆。

**Comment by huapox** [comment]
#414 

看到这个了，之后试试
