### ISSUE TITLE
第一次apt upgrade的时候提内核软链失败

### ISSUE THREAD

**Issue by weigeloveu** [ophub/amlogic-s9xxx-armbian#598]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

apt upgrade的时候提内核软链失败
```
ln: failed to create hard link '/boot/initrd.img-5.15.68-flippy-76+o.dpkg-bak' => '/boot/initrd.img-5.15.68-flippy-76+o':               Operation not permitted
update-initramfs: Generating /boot/initrd.img-5.15.68-flippy-76+o
update-initramfs: Converting to u-boot format
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Processing triggers for man-db (2.10.2-1) ...
```

**To Reproduce**

不能复现，第一次upgrade的时候出现

**Device (please complete the following information):**
 - SOC: [e.g. S095d]
 - Model: [n1]

**Comment by ophub** [comment]
可忽略错误，更新内核时出现，我们使用自定义内核，不影响正常使用
