### ISSUE TITLE
U盘启动root密码不正确

### ISSUE THREAD

**Issue by jason-i-vv** [ophub/amlogic-s9xxx-armbian#599]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
下载了Armbian_22.11.0_Aml_s905x3_bullseye_5.15.71_server_2022.09.29.img.gz, 写入U盘之后，额外做了以下操作：

```
cp u-boot-s905x2-s922.bin u-boot.ext

cd extlinux
mv extlinux.conf.bak extlinux.conf
```

之后启动TX3之后，到达登录命令行，安装root/1234无法登录， 请问默认的root密码是什么呢？

**Comment by ophub** [comment]
1234

**Comment by ophub** [comment]
使用tx3，你在哪学习的教程，要做你的这一系列操作呢？

**Comment by jason-i-vv** [comment]
因为直接刷进去的镜像在Tx3引导的时候，没有反应，所以参考了我之前刷机的经验，改了其中的一些文件

**Comment by ophub** [comment]
tx3不使用extlinux.conf.bak
也不使用u-boot-s905x2-s922.bin
所以这2个错误操作会无法启动，不这么操作，使用s905x3的固件默认启动即可。

**Comment by jason-i-vv** [comment]
好的，我再尝试下，多谢
