### ISSUE TITLE
Boot up 

### ISSUE THREAD

**Issue by Cavabanga** [ophub/amlogic-s9xxx-armbian#6]
Boot only when install media plugging up ( micro SD/USB flash)

**Comment by Cavabanga** [comment]
I install Armbian_21.11.0_Aml_s905x3_buster_5.4.152_2021.10.11.1600.img.gz on ugoos x3 from USB flash. when this USB flash is connected, it boots up and works fine.  when i turn it off freezes on black screen without anything

**Comment by ophub** [comment]
This is no problem. You have unplugged the U disk of the armbian system, it must not work. You write to EMMC for use, or always use the USB flash drive.

https://github.com/ophub/amlogic-s9xxx-armbian#install-armbian-to-emmc

**Comment by Cavabanga** [comment]
but I was doing armbian-install.  in this case should work without USB ?

**Comment by Cavabanga** [comment]
when I unplug usb, the system does not boot. the 905x3 logo appears and then a black screen.

**Comment by Cavabanga** [comment]
Now I have firmware version 0.3.7. I heard that encryption since version 0.3.9. Ok, i will try _s905x3 buster5.4.152.
