### ISSUE TITLE
what bootloader can i used with my STB B860H

### ISSUE THREAD

**Issue by yunuslo** [ophub/amlogic-s9xxx-armbian#60]
dear, 

i am already try to modify file boot.ini and uEvn.txt with location DTB, still not running boot from SDcard.
used : Armbian_22.02.0_Aml_s905x_focal_5.4.169_2022.01.03.1355.img.gz

i'm already try used replace the bootloader, with HG680p.

information log before i'm replace the bootloader

>

>  U-Boot 2015.01-ge1b7b3f-dirty (Aug 24 2017 - 23:11:22)
> 
> DRAM:  1 GiB
> Relocation Offset is: 3eeaf000
> 
> Starting uboot
> -----board_version[9]
> gpio: pin GPIOAO_6 (gpio 106) value is 1
> gpio: pin GPIOCLK_1 (gpio 99) value is 1
> gpio: pin GPIOAO_4 (gpio 104) value is 1
> gpio: pin GPIOX_15 (gpio 15) value is 1

>  Multi dtb tool version: v2 .
>       Support 3 dtbs.
>         aml_dt soc: gxl platform: p215 variant: 1g
>         dtb 0 soc: gxl   plat: p212   vari: 1g
>         dtb 1 soc: gxl   plat: p212   vari: 2g
>         dtb 2 soc: gxl   plat: p215   vari: 1g
>       Find match dtb: 2

after i'm replace it the file log information not same.

> -----board_version[9]
      unified board, board id adc = 9
Fiberhome GPIOAO_4 power on!!!!!      Multi dtb tool version: v2 .
      Support 3 dtbs.
        aml_dt soc: gxl platform: p212 variant: 1g
        dtb 0 soc: gxl   plat: p212   vari: 1g
        dtb 1 soc: gxl   plat: p212   vari: 2g
        dtb 2 soc: gxl   plat: p215   vari: 1g
      Find match dtb: 0

please help me what bootloader & dtb can i used ?

**Comment by ophub** [comment]
The s905x firmware `does not need to modify any information`. After decompressing it directly, it can be used after writing into the SD card.

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2022.01.03.1400/Armbian_22.02.0_Aml_s905x_focal_5.4.169_2022.01.03.1355.img.gz

https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_2022.01.03.1740/Armbian_22.02.0_Aml_s905x_bullseye_5.4.169_2022.01.03.1735.img.gz

**Comment by yunuslo** [comment]
dear.  ophub.

i am already reburn to my SDcard without modify the file and trying to run boot to SDcard. my STB still looping reseting/restart.

[log B860H.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/7806770/log.B860H.txt)

**Comment by ophub** [comment]
Wait for a while, it will be reloaded once. The ip obtained for the second boot after 10 seconds is official.

**Comment by yunuslo** [comment]
> Wait a moment and it will reload again. It is ready to use after the second start in 10 seconds.

ok, i will try again with another B860H version, i wish can run

**Comment by ophub** [comment]
Just now I repackaged the latest version of today, you can download and test it.

**Comment by yunuslo** [comment]
dear, ophub.

i'm already trying without modify uEvn.txt and boot.ini the result still looping reset/restart.

but after i'm trying modify file boot.ini at "mmc" change to /dtb/amlogic/xxx same location at uEvn.txt, armbian starting, but at my monitor looping to and not display clear.
![WhatsApp Image 2022-01-04 at 22 08 35](https://user-images.githubusercontent.com/95902888/148080499-51d9c250-0b72-4e53-b4e0-3cd1ca397fc9.jpeg)

[log after modify boot ini.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/7808527/log.after.modify.boot.ini.txt)
the log look, already starting apps, but the display not clear.

**Comment by ophub** [comment]
You re-download the firmware you just updated. Don't modify it. It will automatically reload once at startup. You can see the final ip from the router.
SSH to the box from the local area network. Check in the terminal, the ghost of the display screen may be the cause of the display driver.
The configuration of this firmware has been around for a long time, they can use this default dtb file normally.

**Comment by ophub** [comment]
u-boot.ext will automatically reload once, and it can be used normally after the second boot. Is your box a new variant?

**Comment by ophub** [comment]
dtb: meson-gxl-s905x-p212.dtb
u-boot: u-boot-p212.bin

**Comment by yunuslo** [comment]
> You re-download the firmware you just updated. Don't modify it. It will automatically reload once at startup. You can see the final ip from the router. SSH to the box from the local area network. Check in the terminal, the ghost of the display screen may be the cause of the display driver. The configuration of this firmware has been around for a long time, they can use this default dtb file normally.

on my router not detect mac address my device

> u-boot.ext will automatically reload once, and it can be used normally after the second boot. Is your box a new variant?
i'm not sure what version my board


> try: mod `uEnv.txt` dtb name: `meson-gxl-s905x-zte-b860h.dtb` u-boot: `u-boot-p212.bin` or `u-boot-s905x-s912.bin` copy to `u-boot.ext`

ok wait i will try it.

**Comment by yunuslo** [comment]
> try: mod `uEnv.txt` dtb name: `meson-gxl-s905x-zte-b860h.dtb` u-boot: `u-boot-p212.bin` or `u-boot-s905x-s912.bin` copy to `u-boot.ext`

i already try mod 'uEnv.txt" dtb name 'meson-gxl-s905x-zte-b860h.dtb' and uboot : `u-boot-p212.bin` the result is "loop reset / restart'

if i am mod 'uEnv.txt" dtb name 'meson-gxl-s905x-zte-b860h.dtb' and uboot : u-boot-s905x-s912.bin the result is starting but at my display looping same with the image display my monitor.

**Comment by ophub** [comment]
Which dtb and u-boot file are you using in Armbian_20.10_Arm-64_buster_current_5.9.0.img.xz?
You try to modify the firmware of ophub to the same value. Try it

**Comment by aipmy** [comment]
solved?

**Comment by ophub** [comment]
```
meson-gxl-s905x-p212.dtb
u-boot-p212.bin
```
I consulted the user of this device again. The OpenWrt he used was confirmed to be usable. Armbian and OpenWrt are the same. Yes offcourse, `5.4.xx`, `5.10.xxx`, `5.15.xxx` Support.

![photo_2022-01-06 08 44 47](https://user-images.githubusercontent.com/68696949/148310414-c27f8722-1e17-4984-96bd-ead3f3ae68b4.jpeg)
![photo_2022-01-06 08 45 05](https://user-images.githubusercontent.com/68696949/148310422-4c53572a-1073-4d61-b52f-7c8abbee579f.jpeg)

**Comment by ophub** [comment]
![Snip20220108_4](https://user-images.githubusercontent.com/68696949/148633594-2927884b-a066-40ac-8dcd-ae02bde21eb9.png)
![Snip20220108_5](https://user-images.githubusercontent.com/68696949/148633599-e11bfba3-e224-4f0c-a64d-549546c81b31.png)

**Comment by tbgevin** [comment]
i'm running Armbian_25.05.0_amlogic_s905x_noble_6.1.137_server_2025.05.05.img but can't install on emmc only on sdcard, how to solve this?
