### ISSUE TITLE
e900v22c 网卡无法识别

### ISSUE THREAD

**Issue by TomatoloveTomatos** [ophub/amlogic-s9xxx-armbian#600]
[Armbian_22.08.0_Aml_s905l3a_bullseye_5.15.62_server_2022.09.01镜像稳定跑了一个月，突然没有网卡了。板载和usb网卡都无法识别。 
![log](https://user-images.githubusercontent.com/104878672/193433318-3ca02c5a-b6a3-4beb-99ac-a2591e7b9ae8.jpg)
下载2022.09.01版，可以识别usb网卡，板载网卡仍然无法识别。

**Comment by TomatoloveTomatos** [comment]
![logs](https://user-images.githubusercontent.com/104878672/193433472-94bb84a7-f3ea-401c-a63b-db6206d44c63.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/bootfs/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb

下载这个dtb替换，更改/boot/uEnv.txt里的名称试试

**Comment by TomatoloveTomatos** [comment]
还是不行

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月3日 11:21
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/bootfs/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb

下载这个dtb替换，更改/boot/uEnv.txt里的名称试试

―

**Comment by ophub** [comment]
网卡没坏？

**Comment by TomatoloveTomatos** [comment]
很长时间等待，前台程序（ha和casaos）可以进入了，usb网卡。从显示器看，盒子一直在跑找不到网卡的代码。我也怀疑过网卡可能坏了，但是在电视模式和Coreelec里都正常。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月3日 12:00
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


网卡没坏？

―

**Comment by wangqs1990** [comment]
我也出现了这种问题，看了下安卓和coreelec是用的4.9的内核，不知道是不是和内核有关

**Comment by TomatoloveTomatos** [comment]
奇怪的是开始没问题，突然成这样了。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月4日 10:06
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


我也出现了这种问题，看了下安卓和coreelec是用的4.9的内核，不知道是不是和内核有关

―

**Comment by wangqs1990** [comment]
我换了5.10版本可以了，可能是这两个内核在识别内部网卡上处理不一样

**Comment by TomatoloveTomatos** [comment]
希望有帮助
***@***.***:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ***@***.***: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: ***@***.***: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr 3s5f:5bcf:a03b::
4: eth0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 9c:61:df:88:37:bb brd ff:ff:ff:ff:ff:ff
5: eth1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq state UP group default qlen 1000
    link/ether 00:e0:4b:68:05:8c brd ff:ff:ff:ff:ff:ff
    inet 192.168.**.***/24 brd 192.168.**.255 scope global dynamic noprefixroute eth1
       valid_lft 85465sec preferred_lft 85465sec
    inet6 fdda:4bcf:6023:0:ec87:f681:7da6:5c83/64 scope global noprefixroute
       valid_lft forever preferred_lft forever
    inet6 fe50::e20e:7889:b34c:33a/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月3日 18:25
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


Closed #600<https://github.com/ophub/amlogic-s9xxx-armbian/issues/600> as completed.

―

**Comment by talpachen** [comment]
22D 也是同样的问题

**Comment by ophub** [comment]
你分享的 u-boot 和 u-boot-e900v22c.bin 是同一个文件，你是搭配的哪个版本的内核比较稳定呢？

**Comment by talpachen** [comment]
> 你分享的 u-boot 和 u-boot-e900v22c.bin 是同一个文件，你是搭配的哪个版本的内核比较稳定呢？

测试的是这个：Armbian_22.11.0_Aml_s905l3a_jammy_5.15.71_server_2022.10.04.img.gz

**Comment by ophub** [comment]
好的，感谢你分享测试结果。

**Comment by TomatoloveTomatos** [comment]
目前是09.1版本，加usb网卡用。但是后台一直在跑phy那个代码。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月6日 19:17
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


你分享的 u-boot 和 u-boot-e900v22c.bin 是同一个文件，你是搭配的哪个版本的内核比较稳定呢？

测试的是这个：Armbian_22.11.0_Aml_s905l3a_jammy_5.15.71_server_2022.10.04.img.gz

―

**Comment by mia0x75** [comment]
> 
@talpachen 我也是22D，最新bullseye版本，一毛一样的错误，请问这个uboot文件怎么使用？谢谢

**Comment by talpachen** [comment]
> 我也是22D，最新bullseye版本，一毛一样的错误，请问这个uboot文件怎么使用？谢谢

把TF卡里的u-boot-e900v22c.bin重命名为u-boot.ext，然后试试启动。
如果log中能出现这个u-boot的版本号，我估计就能解决问题。
我这边感觉与dtb是没有任何关系的。

**Comment by mia0x75** [comment]
> > 我也是22D，最新bullseye版本，一毛一样的错误，请问这个uboot文件怎么使用？谢谢
> 
> 把TF卡里的u-boot-e900v22c.bin重命名为u-boot.ext，然后试试启动。 如果log中能出现这个u-boot的版本号，我估计就能解决问题。 我这边感觉与dtb是没有任何关系的。


# cp u-boot-e900v22c.bin u-boot.ext

然后重启，问题还是一样

`[   15.175371] meson8b-dwmac ff3f0000.ethernet eth0: stmmac_open: Cannot attach to PHY (error: -19)
[   15.262102] meson8b-dwmac ff3f0000.ethernet eth0: validation of rmii with support 0000000,00000000,00006280 and advertisement 0000000,00000000,00006280 failed: -22
[   15.279316] meson8b-dwmac ff3f0000.ethernet eth0: no phy at addr -1
[   15.285277] meson8b-dwmac ff3f0000.ethernet eth0: stmmac_open: Cannot attach to PHY (error: -19)`

**Comment by talpachen** [comment]
@mia0x75 给出完整log，看看有没有启动这个U-boot

**Comment by mia0x75** [comment]
> @mia0x75 给出完整log，看看有没有启动这个U-boot

`# demsg` 输出，见附件。

[dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9734738/dmesg.txt)

**Comment by talpachen** [comment]
> > @mia0x75 给出完整log，看看有没有启动这个U-boot
> 
> `# demsg` 输出，见附件。
> 
> [dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9734738/dmesg.txt)

这没用，得看u-boot的log呀

**Comment by mia0x75** [comment]
> > > @mia0x75 给出完整log，看看有没有启动这个U-boot
> > 
> > 
> > `# demsg` 输出，见附件。
> > [dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9734738/dmesg.txt)
> 
> 这没用，得看u-boot的log呀

抱歉，不知道你说的日志具体哪里可以找到。

我的刷机过程：
1、用rufus写镜像到U盘
2、从U盘启动后运行 armbian-install，根据提示完成安装
3、断电、拔U盘、重启

不知道步骤是否正确，还是需要额外的操作？

**Comment by TomatoloveTomatos** [comment]
cm311-1a 插上原U盘正常。

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月6日 19:20
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


好的，感谢你分享测试结果。

―

**Comment by talpachen** [comment]
> > > > @mia0x75 给出完整log，看看有没有启动这个U-boot
> > > 
> > > 
> > > `# demsg` 输出，见附件。
> > > [dmesg.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9734738/dmesg.txt)
> > 
> > 
> > 这没用，得看u-boot的log呀
> 
> 抱歉，不知道你说的日志具体哪里可以找到。
> 
> 我的刷机过程： 1、用rufus写镜像到U盘 2、从U盘启动后运行 armbian-install，根据提示完成安装 3、断电、拔U盘、重启
> 
> 不知道步骤是否正确，还是需要额外的操作？

我这边是这样操作的：
1. 给TF卡烧镜像
2. TF卡启动，armbian-install
3. 从EMMC启动，出现网卡错误
4. 把TF卡里的u-boot-e900v22c.bin重命名为u-boot.ext
5. 【关键】将TF卡插入22D
6. 再次启动22D，TTL log中出现`U-Boot 2022.04-00910-gea5583b90f-dirty (Apr 22 2022 - 23:37:44 +0800) e900v22c`
7. 网卡不再出错

第五步是关键点，主要是要用指定u-boot.ext启动内核，应该也有方法不插TF卡也解决这个问题的。

**Comment by ophub** [comment]
看起来是TF卡负责引导启动了，说明22D的分区大小安排可能存在错误，写入了不合理的位置。

**Comment by mia0x75** [comment]
@talpachen 还真是这样，在eMMC里面放一个u-boot.ext问题依旧，重新插回U盘，在U盘里面放一个u-boot.ext启动即可找回网卡，前提是U盘要一直插在机器上。

> 看起来是TF卡负责引导启动了，说明22D的分区大小安排可能存在错误，写入了不合理的位置。

@ophub 问题应该比较清晰了，需要找找BUG出处。

另外，armbian-install后eMMC上的文件属主大多都是1023:1023，这个好像有问题，应该是root:root吧？

**Comment by uvtofu** [comment]
> _懂了，下面问题运行armbian-fix解决_ 另外，armbian-install后eMMC上的文件属主大多都是1023:1023，这个好像有问题，应该是root:root吧？

你在armbian-install之前，确认USB上的armbian没有被emmc上的android读写过？

**Comment by mia0x75** [comment]
看了一下armbian-install，是否可以尝试调大这个参数来解决这个问题呢？

`BLANK1="570"`

@ophub

**Comment by TomatoloveTomatos** [comment]
可以ftp登录

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月3日 12:00
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


网卡没坏？

―

**Comment by TomatoloveTomatos** [comment]
5.10版本蓝屏转黑屏

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月4日 10:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


我换了5.10版本可以了，可能是这两个内核在识别内部网卡上处理不一样

―

**Comment by TomatoloveTomatos** [comment]
我试试

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2022年10月4日 10:50
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] e900v22c 网卡无法识别 (Issue #600)


我换了5.10版本可以了，可能是这两个内核在识别内部网卡上处理不一样

―

**Comment by mia0x75** [comment]
今天试了EmuELEC 4.5，https://github.com/EmuELEC/EmuELEC/releases，U盘启动可以正常使用网卡，Armbian的最新几个版本盘启动都不能正常驱动，写入eMMC也是驱动不了。

**Comment by ophub** [comment]
只能从安卓系统启动和写入emmc，当盒子安装了EmuELEC等其他系统后，都无法启动，因为分区表被改了，只有刷回原厂安卓系统才可以使用armbian

**Comment by mia0x75** [comment]
我的意思是Android启动EmuELEC网卡正常，Android启动Armbian网卡不工作。

**Comment by uvtofu** [comment]
> 我的意思是Android启动EmuELEC网卡正常，Android启动Armbian网卡不工作。

我的意思是，有些Android固件会污染U盘里的文件权限，你能排除这个可能吗？

**Comment by mia0x75** [comment]
> > 我的意思是Android启动EmuELEC网卡正常，Android启动Armbian网卡不工作。
> 
> 我的意思是，有些Android固件会污染U盘里的文件权限，你能排除这个可能吗？

同一台机器同一个固件，外挂U盘启动EmuELEC网卡正常，外挂U盘启动Armbian启动网卡有问题。

**Comment by ophub** [comment]
安卓使用的非主线内核，而armbian使用的是主线内核，所以驱动不同。

做为安卓电视盒子，它的声卡和网卡都有厂家向安卓提交的驱动。但有些芯片厂家没有向主线内核提交驱动。所以不能说安卓系统可以驱动，armbian就可以驱动。

通过安卓系统可以检测硬件是否损坏，是否正常。但在armbian里是否可以驱动要检查是否添加了驱动、dtb代码是否添加了支持，并调试

**Comment by uvtofu** [comment]
> 安卓使用的非主线内核，而armbian使用的是主线内核，所以驱动不同。

我看很多评论讲，EmuELEC和LibreELEC对硬件的支持比Armbian好很多。会不会EmuELEC和LibreELEC使用的是Android内核，而不是主线内核呢？

**Comment by uvtofu** [comment]
> 同一台机器同一个固件，外挂U盘启动EmuELEC网卡正常，外挂U盘启动Armbian启动网卡有问题。

那是我多虑了，不好意思干扰了讨论。

**Comment by mia0x75** [comment]
> 安卓使用的非主线内核，而armbian使用的是主线内核，所以驱动不同。
> 
> 做为安卓电视盒子，它的声卡和网卡都有厂家向安卓提交的驱动。但有些芯片厂家没有向主线内核提交驱动。所以不能说安卓系统可以驱动，armbian就可以驱动。
> 
> 通过安卓系统可以检测硬件是否损坏，是否正常。但在armbian里是否可以驱动要检查是否添加了驱动、dtb代码是否添加了支持，并调试

问题是现在有临时不完美方案，就是外挂一个带有u-boot.ext的U盘，所以想讨论产生这个问题的根本原因，感觉不是不能驱动，而是哪里差了一点点。这个问题在22c、22d、中兴B863AV3.2M都有issue报告。

**Comment by xcray** [comment]
感觉有些晕的，可以看看https://github.com/ophub/amlogic-s9xxx-armbian/issues/491

**Comment by ophub** [comment]
楼上的是个正经好贴，我之前怎么没注意到这个好贴呢，一会加精标记。
