### ISSUE TITLE
N1:Not able to scan bluetooth devices.

### ISSUE THREAD

**Issue by fefen0** [ophub/amlogic-s9xxx-armbian#601]
**Describe the bug**
No devices found during BLE scan on N1,

**To Reproduce**
1. use 'hcitool scan'
2.  Bluetooth  hci0:command 0x0401 tx timeout

 
`root@armbian-n1:~# hciconfig
hci1:   Type: Primary  Bus: SDIO
        BD Address: 00:00:00:00:00:00  ACL MTU: 0:0  SCO MTU: 0:0
        DOWN
        RX bytes:0 acl:0 sco:0 events:0 errors:0
        TX bytes:0 acl:0 sco:0 commands:0 errors:0

hci0:   Type: Primary  Bus: UART
        BD Address: 43:41:C1:01:11:AC  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING
        RX bytes:4470 acl:0 sco:0 events:438 errors:0
        TX bytes:68940 acl:0 sco:0 commands:440 errors:0
`

**Armbian Version**
 - Kernel Version: [5.10.146]
 - Release: [ jammy]
 - Edition: [  server]

**Device (please complete the following information):**
 - SOC: [ S905d]
 - Brand: PHICOMM]
 - Model [n1]

**Additional context**

**Comment by ophub** [comment]
armbian-config > install BR

**Comment by fefen0** [comment]
BT had been installed just using the armbian-config tool,and I reinstall BT,but it still not work.
pls tell me how to debug it

**Comment by ophub** [comment]
`dmesg | grep Blue*`

**Comment by fefen0** [comment]
ok
This is the output of dmesg:
`dmesg | grep Blue*

[   10.016217] Bluetooth: Core ver 2.22
[   10.024698] Bluetooth: Starting self testing
[   10.053846] Bluetooth: ECDH test passed in 14556 usecs
[   10.057754] Bluetooth: SMP test passed in 3639 usecs
[   10.057780] Bluetooth: Finished self testing
[   10.057861] Bluetooth: HCI device and connection manager initialized
[   10.057871] Bluetooth: HCI socket layer initialized
[   10.057878] Bluetooth: L2CAP socket layer initialized
[   10.057905] Bluetooth: SCO socket layer initialized
[   10.190120] Bluetooth: HCI UART driver ver 2.3
[   10.195476] Bluetooth: HCI UART protocol H4 registered
[   10.207466] Bluetooth: HCI UART protocol BCSP registered
[   10.318405] Bluetooth: HCI UART protocol LL registered
[   10.332827] Bluetooth: HCI UART protocol ATH3K registered
[   10.338237] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   10.346902] Bluetooth: HCI UART protocol Intel registered
[   10.457978] Bluetooth: HCI UART protocol Broadcom registered
[   10.458019] Bluetooth: HCI UART protocol QCA registered
[   10.458023] Bluetooth: HCI UART protocol AG6XX registered
[   10.458057] Bluetooth: HCI UART protocol Marvell registered
[   10.826290] Bluetooth: hci0: BCM: chip id 107
[   10.826703] Bluetooth: hci0: BCM: features 0x2f
[   10.842825] Bluetooth: hci0: BCM4345C0
[   10.842839] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
[   10.844162] Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.hcd' Patch
[   11.770164] Bluetooth: hci0: BCM4345C0 UART 37.4 MHz wlbga_ref_iLNA_iTR_eLG [                                                                                                                                               Baseline: 0143]
[   11.770177] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0230
[   20.211548] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   20.214995] Bluetooth: BNEP filters: protocol multicast
[   20.219846] Bluetooth: BNEP socket layer initialized
[ 1622.240303] Bluetooth: hci0: command 0x0401 tx timeout
`
Please help

**Comment by ophub** [comment]
The log is correct except for the last line that times out.
Try another version of the kernel. Such as 5.19.y or 5.15.y etc.

**Comment by louliangsheng** [comment]
I also have the same issue, both firmware of n1 have such an issue, it works at first, and after a while it is not available.

**Comment by louliangsheng** [comment]
root@armbian:~# hciconfig hci0 down
root@armbian:~# rmmod btusb
rmmod: ERROR: Module btusb is not currently loaded
root@armbian:~# modprobe btusb
root@armbian:~# rmmod btusb
root@armbian:~# hciconfig hci0 up
Can't init device hci0: Connection timed out (110)
root@armbian:~# hciconfig hci0 up
Can't init device hci0: Connection timed out (110)
root@armbian:~# dmesg | grep Blue*
[   14.896380] Bluetooth: Core ver 2.22
[   14.899521] Bluetooth: Starting self testing
[   14.917597] Bluetooth: ECDH test passed in 14578 usecs
[   14.926768] Bluetooth: SMP test passed in 5363 usecs
[   14.929421] Bluetooth: Finished self testing
[   14.938194] Bluetooth: HCI device and connection manager initialized
[   14.944486] Bluetooth: HCI socket layer initialized
[   14.949346] Bluetooth: L2CAP socket layer initialized
[   14.954362] Bluetooth: SCO socket layer initialized
[   15.064032] Bluetooth: HCI UART driver ver 2.3
[   15.075252] Bluetooth: HCI UART protocol H4 registered
[   15.075262] Bluetooth: HCI UART protocol BCSP registered
[   15.075376] Bluetooth: HCI UART protocol LL registered
[   15.090681] Bluetooth: HCI UART protocol ATH3K registered
[   15.090829] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   15.095361] Bluetooth: HCI UART protocol Intel registered
[   15.102558] Bluetooth: HCI UART protocol Broadcom registered
[   15.110638] Bluetooth: HCI UART protocol QCA registered
[   15.145302] Bluetooth: HCI UART protocol AG6XX registered
[   15.145415] Bluetooth: HCI UART protocol Marvell registered
[   15.460252] Bluetooth: hci0: BCM: chip id 107
[   15.462669] Bluetooth: hci0: BCM: features 0x2f
[   15.467093] Bluetooth: hci0: BCM4345C0
[   15.469320] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
[   15.479354] Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.hcd' Patch
[   16.309075] Bluetooth: hci0: BCM: features 0x2f
[   16.311429] Bluetooth: hci0: BCM4345C0 UART 37.4 MHz wlbga_ref_iLNA_iTR_eLG [Baseline: 0143]
[   16.327173] Bluetooth: hci0: BCM4345C0 (003.001.025) build 0230
[   21.811618] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   21.813242] Bluetooth: BNEP filters: protocol multicast
[   21.818179] Bluetooth: BNEP socket layer initialized
[   21.878416] Bluetooth: MGMT ver 1.22
[  214.546357] Bluetooth: hci0: Opcode 0x2005 failed: -110
[  214.546369] Bluetooth: hci0: command 0x2005 tx timeout
[  216.562394] Bluetooth: hci0: Opcode 0x200b failed: -110
[  216.562419] Bluetooth: hci0: command 0x200b tx timeout
[  289.587868] Bluetooth: hci0: Opcode 0x c03 failed: -110
[  577.452836] Bluetooth: hci0: Opcode 0x c03 failed: -110
