### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by urain39** [ophub/amlogic-s9xxx-armbian#603]
1. armbian-config 不能设置静态 IP（理论上动态也不能？）
2. /etc/fstab 倒数的两个规则之间少了一个换行符

使用的版本是10月3日的最新版本。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/network/interfaces

网络在这自定义，在armbian-config里面也可以编辑这个文件

**Comment by urain39** [comment]
好的。

**Comment by urain39** [comment]
第二个问题的原因找到了？是上游的问题？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/cdcd4b75a758a63e16706267e0504ec3cf6a48ae

我的问题，已经修复了

**Comment by urain39** [comment]
好的。
