### ISSUE TITLE
syslog 和daemon.log有异常日志

### ISSUE THREAD

**Issue by Cheyanne-hua** [ophub/amlogic-s9xxx-armbian#605]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
盒子型号是cm311-1a  晶晨am905l3a处理器，盒子已经稳定运行一段时间但是在今天发现系统日志满了查看发现syslog 和daemon.log在频繁循环写入一些错误，不太懂，特来询问。下面是内容：
Oct  7 23:44:29 armbian systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Oct  7 23:44:29 armbian systemd[1]: hostapd.service: Failed with result 'exit-code'.
Oct  7 23:44:29 armbian systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.
Oct  7 23:44:31 armbian systemd[1]: hostapd.service: Scheduled restart job, restart counter is at 571.
Oct  7 23:44:31 armbian systemd[1]: Stopped Access point and authentication server for Wi-Fi and Ethernet.
Oct  7 23:44:31 armbian systemd[1]: Starting Access point and authentication server for Wi-Fi and Ethernet...
Oct  7 23:44:31 armbian hostapd[4495]: Configuration file: /etc/hostapd/hostapd.conf
Oct  7 23:44:31 armbian hostapd[4495]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Oct  7 23:44:31 armbian hostapd[4495]: Failed to set up interface with /etc/hostapd/hostapd.conf
Oct  7 23:44:31 armbian hostapd[4495]: Failed to initialize interface

重启依然是这样，而且/etc/hostapd/hostapd.conf也不存在
**To Reproduce**
重启即可复现
**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/84385761/194594854-46aeddfe-5bc1-467d-b0f6-a48e6f12a2ea.png)

**Armbian Version**
 - Kernel Version: 5.15.62-flippy-76+o
 - Release: bullseye
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: amls905l3a
 - Brand: [e.g. Beelink]
 - Model [e.g. mini g1]

**Comment by ophub** [comment]
把无线，热点服务关了

**Comment by ophub** [comment]
https://www.igiftidea.com/article/14266494324.html

https://blog.csdn.net/u014114152/article/details/87936820

**Comment by ophub** [comment]
这个就是会分2个IP，你如果在上游路由器的DNCP指定了固定IP，或者在armbian的网卡里指定了固定IP，就不会有2个IP了，我习惯关闭NetworkManager.service

**Comment by Cheyanne-hua** [comment]
已经解决了，谢谢各位关了hostapd就行了
