### ISSUE TITLE
能否有通用的U盘启动系统

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-armbian#606]
有两个设备：CM311 M401
刚开始准备插上U盘写入新设备M401的EMMC。
发现用CM311初始化的U盘armbian不能直接在401上用。

**Comment by ophub** [comment]
一个固件在打包的时候会生成一个固定的mac地址，所以1个固件不能写入N个U盘在同一个局域网使用，如果要使用需要先手动把在线的其他U盘里的mac地址改下，或者先把其他的盒子断网，改你现在启动的U盘里的系统的MAC地址。

如果写入EMMC就没问题，安装脚本会重新生成新MAC地址。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/usr/sbin/armbian-install#L412

/etc/network/interfaces
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/network/interfaces

**Comment by ophub** [comment]
你选的哪个序号安装的

**Comment by ophub** [comment]
哪个版本的固件

**Comment by ophub** [comment]
305没有主线U-BOOT，理论上不可能砖了，而且重新插入USB能启动。
[android_tv_m401a_b863av3.2-m_s905l3a.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_b863av3.2-m_s905l3a.tar.xz)

**Comment by ophub** [comment]
我这个是前一段时间从帖子里下载保存的，他们测试了可以使用。
一般情况下你找买盒子的店家要，他们有对应的原厂固件，你保存一份以备恢复使用。

**Comment by ophub** [comment]
这图片发和没法一样，全是棉花糖。
你ssh链接试试，是不是已经启动了。
去路由器里看看IP

**Comment by ophub** [comment]
接键盘，回车看看是不是有登录提示了

**Comment by ophub** [comment]
如果是砖了，你连这个跑码都看不到。全屏幕黑的。
拔电重启试试。
你试试USB刷5.15的固件启动下。

**Comment by ophub** [comment]
sync
reboot

**Comment by ophub** [comment]
另外现在安装脚本里是适配的e900v22c和cm311的安卓分区，不指定m401的分区是多少，如果和这2个不一样，你写入emmc可能会出现问题，覆盖了不安全的区域，你如果你有安卓系统，可以恢复安卓系统后，检查一下安卓分区大小，在这里有一键脚本，你打开脚本复制粘贴几个命令就完成了，在安卓里的操作一键脚本自动完成。

https://github.com/ophub/kernel/releases/tag/tools
最后一个文件
[get_android_system_partition_table_information.tar.xz](https://github.com/ophub/kernel/releases/download/tools/get_android_system_partition_table_information.tar.xz)

**Comment by ophub** [comment]
意思就是说，你无论选择304还是305，你是套用别的盒子的安卓分区。

如果你的m401和这2个盒子不一样，你选择哪个安装也会无法使用。所以最好的办法是看看自己的分区是什么，好量身配置自己的分区大小，这样写入emmc才是稳定的。

**Comment by ophub** [comment]
你是m401，就不用管cm311的事情了，你恢复安卓系统后，自己看看自己的分区，和现在已知的2个中的哪个一样，如果都不一样就要建立一个新的分区大小，你可以把excel发上来，我比一下

**Comment by ophub** [comment]
看看这个帖子： https://github.com/ophub/amlogic-s9xxx-armbian/issues/517

你的盒子目前属于未知状态，不知道他的安卓分区大小，所以你安装至emmc套用的304和305的大小都不一定是对的，最好确认一下。你是对一个反馈使用m401安装emmc的人，如果你测试了，后来的用户就可以享受你的成果。

**Comment by ophub** [comment]
不是说你不会返回去使用安卓，就不必要知道安卓系统分区。
我们的armbian写入安卓盒子的时候，是对照着安卓分区的位置，见缝插针地写入了对应的分区，比如windows的C盘D盘E盘，我们写入的时候会只写D，不写C和E，因为底层的安卓这个区块写着不可覆盖的数据，写入后就无法启动了。

所以要知道底层安卓系统是怎么分区的，各分区的大小是多少块，才能根据安卓写armbian的安装脚本分区起始结束位置。

**Comment by ophub** [comment]
如果是分区不对引起的问题，这类键盘等问题都不是dtb能解决的，会陆续出现各种不可思议的现象。

**Comment by ophub** [comment]
因为没有可用的主线u-boot，所以不能擦除全部分区使用，只能挑着安全的分区位置使用。

**Comment by ophub** [comment]
m401生产的时候也没想到会被人拿来刷armbian，它只想好好地表演电视节目。
你想玩弄它，得先摸清楚它的结构。
你非要给帅哥穿个裙子，它能乐意吗？
终极解决方案就是看看它的安卓分区，把安装脚本改成匹配的分区划分。

**Comment by ophub** [comment]
娶的媳妇是用来彼此适应的，要匹配起来，和谐起来。
而不是用自己的意愿强制改造她，她不是那么完美，因为她独一无二。

**Comment by MDCY9008** [comment]
目前只能用原厂的uboot，原厂是为安卓设计的，安卓很多分区不可写，设备众多主线uboot没有做出来，emmc不能随心所欲的使用，只能写入安卓安全分区。

**Comment by ophub** [comment]
你拿刷机软件把原厂系统刷就去就恢复原来的分区了，不用买新的。软件系统可以反复安装，一会winxp，一会win10，不是安装了一个就要买新机。

**Comment by ophub** [comment]
你刚才不是不能使用？现在能使用了？
本着能用就不折腾原则，如果是能用就继续用吧。

**Comment by ophub** [comment]
我检查了几次新固件，发现networkManger默认是关闭的，可是有好些同学们反应这个服务是启动的，不知道是在什么操作中激活的，这2个服务有人自选关闭其中一个。
如果我直接把其中一个关闭了，不知道会不会导致一些人开机没网络了。
因为都开着的缺点是产生2个IP，似乎没什么不好的结果，所以不如就留着让同学们自选使用哪个服务吧。

**Comment by ophub** [comment]
结论就是m401使用原厂固件，armbian-install写入emmc时使用305序号（cm311盒子分区），目前测试可以使用。
如果有同学想用的踏实点，可以使用一键脚本看一下原厂安卓系统的分区表，是不是一致。
生成的安卓系统分区excel可以发上来，我比较比较，如果有差异就添加独立分区配置。
