### ISSUE TITLE
TX3mini S905W 固件无法正常启动

### ISSUE THREAD

**Issue by CyrilLance** [ophub/amlogic-s9xxx-armbian#61]
![微信图片_20220105110540](https://user-images.githubusercontent.com/13145506/148154455-fb623cdb-f8fb-41fc-b644-56185cee320c.jpg)
![微信图片_20220105110545](https://user-images.githubusercontent.com/13145506/148154461-33874803-59ff-451b-9bc1-738c4d3661ab.jpg)

固件写入存储卡装机后无法正常启动，循环在这一步，但是可以获得IP，SSH连接不上

**Comment by CyrilLance** [comment]
你好，看提示好像是没有找到boot文件，这里是我少了什么步骤吗，之前的armbian固件是需要单独配置dtb和u-boot.ext，这里我看镜像好像已经配置好了，就没有修改这些，写卡后直接使用的

**Comment by ophub** [comment]
这个盒子是可以写入emmc使用的。你试试5.4内核的固件。
