### ISSUE TITLE
选305写入M401A的emmc后进不去linux

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-armbian#610]
从emmc进不去系统
插上优盘后进不去系统
现在发现，插优盘再插一个键盘就能进系统！WTF

**Comment by ophub** [comment]
键盘对引导启动还有特殊加持作用？我解释不了你的发现。这2个应该无关。

**Comment by ophub** [comment]
通用包的安卓分区表是什么，它是和e900v22c通用呢？还是和cm311通用呢？和谁一样呢，拿表比较。

**Comment by lppsuixn** [comment]
我之前刷其他版本的atv也出现过，插上键盘就能输出画面，不插就不行。
