### ISSUE TITLE
M401A all done（personally）

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-armbian#612]
前提：广东版M401A
thanks  for [xcray](https://github.com/xcray) https://github.com/ophub/amlogic-s9xxx-armbian/issues/452)
m401a 选择305刷入emmc，如果发生各种奇怪的问题。
1.请尝试插入U盘+插入键盘，再开机。
2.经过1如果能开机。请nano /boot/uEnv.txt，修改为meson-g12a-s905l3a-e900v22c.dtb 再看issues452
3.armbian-sync
   armbian-update 5.10.146 stable yes

**Comment by ophub** [comment]
这个无线芯片在主线内核里没驱动，你可以插一个有驱动的USB无线使用，或者给盒子换个其他有驱动的无线芯片。这盒子几十块钱，多练练手，发挥你的创造力。
