### ISSUE TITLE
5.10.147使用ufw，被提示/lib文件库权限过高

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-armbian#613]
ufw allow ssh
WARN: uid is 0 but '/lib' is owned by 1000
WARN: /lib is group writable!
ll /lib
lrwxrwxrwx 1 root root   /lib -> /usr/lib

fix
chmod -R 755 /lib
chown root:root /lib

**Comment by ophub** [comment]
3q，谢谢分享
