### ISSUE TITLE
KVM libvirtd报错

### ISSUE THREAD

**Issue by univerioiln233** [ophub/amlogic-s9xxx-armbian#614]
1   ethtool ioctl error on eth0: Device or resource busy
fix
重建网络链接
nmcli con add type bridge-slave ifname eth0 master br0
nmcli con delete eth0
2   
libvirtd[914]: Cannot check dnsmasq binary /usr/sbin/dnsmasq: No such file or directory
libvirtd[914]: Cannot find 'dmidecode' in path: No such file or directory
fix
安装dnsmasq dmidecode
系统默认的是dnsmasq-base

**Comment by ophub** [comment]
感谢分享解决问题的办法
