### ISSUE TITLE
Permanent MAC: 2a:0f:02:92:0b:13，这个默认地址如何彻底修改？

### ISSUE THREAD

**Issue by mia0x75** [ophub/amlogic-s9xxx-armbian#617]
局域网中有多台设备mac地址冲突，尝试修改：

\# nmcli con modify eth0 ethernet.cloned-mac-address 00:11:22:33:44:55

然后查看：

\# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 10.0.0.30  netmask 255.255.255.0  broadcast 10.0.0.255
        inet6 fe80::7119:cbce:7376:46e4  prefixlen 64  scopeid 0x20<link>
        ether 00:11:22:33:44:55  txqueuelen 1000  (Ethernet)
        RX packets 3625  bytes 373596 (364.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 2635  bytes 1255919 (1.1 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 14

用macchanger查看：
\# macchanger -r eth0
Current MAC:   00:11:22:33:44:55 (unknown)
Permanent MAC: 2a:0f:02:92:0b:13 (unknown)
[ERROR] Could not change MAC: interface up or insufficient permissions: Device or resource busy

用macchanger修改：
\# ifconfig eth0 down && macchanger --permanent --mac 00:11:22:33:44:55 eth0
[ERROR] Could not read permanent MAC: Device or resource busy
Current MAC:   00:11:22:33:44:55 (unknown)
Permanent MAC: 00:00:00:00:00:00 (XEROX CORPORATION)
New MAC:       00:11:22:33:44:55 (unknown)
It's the same MAC!!

如果不更改Permanent MAC，eth0会重新启用一次。启动日志会这样（估计是mac地址变化造成的eth0重启）：
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: PHY [0.1:08] driver [Meson G12A Internal PHY] (irq=38)
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: No Safety Features support found
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: PTP not supported by HW
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: configuring for phy/rmii link mode
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[ OK ] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: Link is Down
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: PHY [0.1:08] driver [Meson G12A Internal PHY] (irq=38)
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: Register MEM_TYPE_PAGE_POOL RxQ-0
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: No Safety Features support found
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: PTP not supported by HW
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: configuring for phy/rmii link mode
[ OK ] meson8b-dwmac ff3f0000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[ OK ] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready

**Comment by livelier** [comment]
修改一下mac，重启即可。 详见 [Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#1273-%E5%9C%A8-docker-%E4%B8%AD%E4%BD%BF%E7%94%A8-openwrt-%E5%BB%BA%E7%AB%8B%E4%BA%92%E9%80%9A%E7%BD%91%E7%BB%9C) 希望能够帮到你。

**Comment by mia0x75** [comment]
> 网络配置文件 /etc/network/interfaces 修改一下mac，重启即可。 详见 [Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#127-%E7%BD%91%E7%BB%9C%E8%AE%BE%E7%BD%AE) 12.7.3，希望能够帮到你。

谢谢，我用的NetworkManager，好像这个配置没用。networking.service用这个配置。

**Comment by livelier** [comment]
![image](https://user-images.githubusercontent.com/104582100/195358806-1e4f843e-01f7-4dbf-a153-fc6b64e3f8ab.png)
改你想要的mac，重启即可。

**Comment by mia0x75** [comment]
> 改你想要的mac，然后 /etc/network/interfaces 禁掉，重启即可。我之前用 homeassistant 的时候，是这样做的。 这是克隆 mac。网卡自带 mac 彻底改掉的话，这个我也不清楚。还是有请 o大 吧

2a:0f:02:92:0b:13 这个是系统硬编码的一个mac地址，刷机后所有机器的mac地址都是这个，不清楚为什么要这么做，默认取网卡自己的mac地址不久行了吗？

**Comment by ophub** [comment]
删掉/etc/network/interfaces就没自定义mac地址了，自动取你的硬件。

**Comment by mia0x75** [comment]
> 删掉/etc/network/interfaces就没自定义mac地址了，自动取你的硬件。

实际上我的interfaces已经改成interfaces.bak了，但问题还在。因为networking.service和NetworkManager.service有相同的功能，所以前者我disable了，不知道这个理解对不对。

**Comment by ophub** [comment]
我是禁用NetworkManager，使用/etc/network/interfaces自定义地址，安装emmc也会自动独立分配，没有重复的事情。

这个电视盒子，不是为armbian做的开放主板，所以有些盒子获取不了原mac地址。为了稳妥起见，就直接给自定义了。又不是不能用，不能太强迫自己不能接受自定义。原mac和自定义的都一样用。

**Comment by livelier** [comment]
在之前我有过关于 mac 的分析和研究，据我了解，盒子外壳标注的 mac 及安卓系统下的 mac，大多数也并非 eth 原有 mac，安卓系统一般获取的 mac 与保存在 emmc 安卓分区中 mac 相同，但不同盒子不同安卓版的偏移量位置不同。我手上的 `lb2004-a4901` 1台 `ugoos-x3` 2台，他们都是这样，我已经找到这两款盒子 emmc 安卓系统下保存 mac 偏移量位置。通过修改偏移量位置的 mac 安卓系统下会随之变更。虽然不能100%确定每款盒子都是这样，但我的案例足以说明，部分盒子的 mac 并非 eth 自带 mac ，而是盒子的安卓系统自定义，或者 uboot 自定义的 mac。

**Comment by ophub** [comment]
原厂的mac地址好象是存在env这个分区里的

![image](https://user-images.githubusercontent.com/68696949/195515265-89ae8a25-bd48-4628-9b45-b548a6e7123b.png)

主线uboot可以保证每台设备的mac地址不同

https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/board-common.c#L78

https://github.com/chewitt/u-boot/blob/master/arch/arm/mach-meson/sm.c#L92

可能是通过cpu的序列号来计算的，每个cpu出厂时都有不同的序列号。

**Comment by livelier** [comment]
666，我是用二进制方式找到的 😂😂😂 安卓系统是在这部分获取的 mac。
![image](https://user-images.githubusercontent.com/104582100/195517078-ced63ea3-ecad-453a-8515-53d088380432.png)

而 armbian 获取的 mac 不是安卓的这部分，所以 mac 不同。

**Comment by livelier** [comment]
MAC 地址，没人说他不重要。

打开鸿蒙/安卓，已经连接 wifi 选项里 MAC 地址了解一下。

`NetworkManager` `/etc/network/interfaces`  都能改成想要的 MAC 地址。

网络连接是否稳定不会因为 MAC 地址不是 Permanent MAC 而导致。

2014年发布版本，建议你去作者的仓库逛一逛。
