### ISSUE TITLE
ugoos x3 mainline_uboot 不能启动 emmc

### ISSUE THREAD

**Issue by livelier** [ophub/amlogic-s9xxx-armbian#618]
你好，o大，5.15.y 内核写入 ugoos x3 emmc 使用安卓 u-boot 可以正常启动。发现 u-boot 目录下有他的主线 u-boot 文件 /usr/lib/u-boot/ugoos-x3-u-boot.bin.sd.bin 。尝试使用这个主线 u-boot 写入 emmc 经测试 5.10.y 5.15.y 使用这个主线都不能启动。

这款盒子，目前仅支持 5.15.y 内核 安卓 u-boot 启动 emmc ？

**Comment by ophub** [comment]
```
MYBOX_UBOOT="/usr/lib/u-boot/mybox-bootloader.img"
#lsblk看看你的emmc叫什么，一般是`mmcblk2`
DEV_EMMC="/dev/mmcblk2"
dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=1 count=444
dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1
```

在写入emmc前，脚本备份了一份安卓原系统的bootloader，你还原下重启即可。

**Comment by livelier** [comment]
好的。我有测试过，只有 5.15.y 使用安卓bootloader 可以正常emmc。

**Comment by ophub** [comment]
对，这个盒子只有旧版的可以写入emmc

**Comment by livelier** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/tools/config/config-5.15
CONFIG_LEDS_TCA6507=y
这样修改，编译的时候 会编译 tca6507 吗？和 u-boot 编译的时候相同？

**Comment by ophub** [comment]
对，要的就y

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/led_screen_display_control.md

这个也可以点亮led

**Comment by livelier** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/618#issuecomment-1277666120 有测试过，没有成功，可能我操作的不对。
![image](https://user-images.githubusercontent.com/104582100/195619645-58eeec3f-de49-457b-a6cf-7df04f54d062.png)
![image](https://user-images.githubusercontent.com/104582100/195619921-7a7b7108-9186-4574-b34a-16944ea003b4.png)
![image](https://user-images.githubusercontent.com/104582100/195620604-d443bb60-d1b6-4d18-b81f-afd2cc9b97b7.png)
目测 tca6507 引脚 6 7 8 链接 led 红 白 蓝 导线（应该是分别对应红/黄/蓝LED，这个LED很有意思，可以根据三色配色出其他颜色），黑色导线没有链接 tca6507，我有测电压，他不是地线，有5V电压。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/12c78c6a2f70323f240d45872f475fcc4bd136f7

这是前几天f大给章鱼星球加的led色灯。

**Comment by livelier** [comment]
章鱼星球，这个帖子我有看，代码组合方式 有尝试，不能点亮，所以我怀疑 tca6507 需要被驱动起来才可以。这款盒子LED亮起来，真的就完美啦，可以实现RGB配色不同颜色，安卓下就有橙色，天青色，等显示过很漂亮。我有点较真😂

这种引用方式，是怎么做到的？ https://github.com/ophub/amlogic-s9xxx-armbian/issues/618#issuecomment-1277694670

**Comment by livelier** [comment]
@ophub o大，请教一下，我遇到一个很玄学的问题。😂
主线是我自己制作的，可以写在 有BL锁的 ugoos x3 盒子正常使用。
但写入 mainline_u-boot 后，需要关机断电 1分钟左右，才会生效！😲

另外，我的 A4091 盒子 LED 可以点亮了。
测试发现原厂 bootloader 可以引导 5.10.y 内核，把 5.10.y 内核 tca6507=y 并编译内核。
在调整 dtb。led 点亮了。 支持 R G B 调色，通过调整 R G B 三个led 输出不同的亮度。
可以实现输出很多种颜色，红橙黄绿蓝靛紫棕粉白，都能点亮 🎉🎉🎉

目前必须使用原厂 bootloader 才能点亮。是不是说，这款盒子主线 u-boot 和 内核同时具备点亮条件，
不使用 bootloader 也可以点亮 led？给主线增加 tca6507 的驱动，这个我还不会。
最新 u-boot 源码没有包含这个 tca6507 的驱动相关文件。😰

**Comment by ophub** [comment]
恭喜你，之前ugoos x3高版本的都因为锁了BL而无法写入，你是怎么解决的这个问题呢？
如果主线可以使用，如果忽略灯效，你可以写入主线后使用完整的emmc分区，而不用跳过那1G多的分区。

主线uboot可以取代安卓原厂的bootloader，使用原厂bl是因为没有调试出合适的主线uboot的一种妥协办法。

我去u-boot源码目录找了下也没找到tca6507（我发现在github仓库搜关键字经常是没有，但是目录里实际有，搜索有时不准确，需要到目录里看看）

**Comment by livelier** [comment]
ugoos x3 有BL锁，写入主线使用的方法。等我在多验证几次，然后分享上来。我手上有CUBE,PLUS两个版本。

理想是用主线并点亮LED，哈哈哈哈

我看F大的内核中有这个驱动文件，但是引用了很多文件，编译u-boot时，要把这些引用合并到u-boot源码，这种方式增加这个驱动，可行吗？
https://github.com/unifreq/linux-5.10.y/blob/b3c22527850e5e8d8a9aae3ef31fcaa4a0613613/drivers/leds/leds-tca6507.c#L74-L81

**Comment by livelier** [comment]
ugoos x3 有BL锁，写入主线使用的方法。等我在多验证几次，然后分享上来。我手上有 CUBE, PLUS 两个版本。


理想是A4091用主线并点亮LED，哈哈哈哈
我看F大的内核中有这个驱动文件，但是引用了很多文件，编译 u-boot 时，要把这些引用合并到 u-boot 源码，这种方式增加这个驱动，可行吗？
https://github.com/unifreq/linux-5.10.y/blob/b3c22527850e5e8d8a9aae3ef31fcaa4a0613613/drivers/leds/leds-tca6507.c#L74-L81

**Comment by livelier** [comment]
ugoos x3 有BL锁，写入主线使用的方法。等我在多验证几次，然后分享上来。我手上有 CUBE, PLUS 两个版本。


理想是A4091用主线并点亮LED，哈哈哈哈
我看F大的内核中有这个驱动文件，但是引用了很多文件，编译 u-boot 时，要把这些引用合并到 u-boot 源码，这种方式增加这个驱动，可行吗？
https://github.com/unifreq/linux-5.10.y/blob/b3c22527850e5e8d8a9aae3ef31fcaa4a0613613/drivers/leds/leds-tca6507.c#L74-L81

F大内核仓库
https://github.com/unifreq/linux-5.10.y/tree/main/drivers/leds

u-boot仓库
https://github.com/u-boot/u-boot/tree/v2022.10/drivers/led

**Comment by ophub** [comment]
复制这个kernel的驱动应该不行
