### ISSUE TITLE
Force use wifi

### ISSUE THREAD

**Issue by KGHTW** [ophub/amlogic-s9xxx-armbian#62]
Hi, seems like ethernet port on my old box MXQ Pro 4K (S905X, 1GB RAM/8GB ROM) is not supported.
Tried every dtb and its detected as "Unknown device" all the time.
Its probably PM44-11BP chipset.
WIFI chipset is SciInSX 802.11n NIC 9083xu (I know, probably no chance to make this work).
Got also WIFI USB dongle Ralink MT7601U.

How to force use WIFI on your builds? I tried with "armbian_first_run.txt" file but no luck.
It keeps looking for ethernet port which is not supported.

Tried balbes150 builds https://users.armbian.com/balbes150/arm-64/
ethernet also doesn't work but wifi (Ralink MT7601U) works fine on these builds.
I set everything in "armbian_first_run.txt" and success!

How to do this in your builds?

**Comment by ophub** [comment]
soc: s905

`/boot`

Modify the `uEnv.txt` file
`meson-gxbb-mxq-pro-plus.dtb`


`u-boot-p201.bin` copied as `u-boot.ext`
`chmod +x u-boot.ext`

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/7607625404c2927235329080409169b6f72968ff/compile-kernel/tools/config/config-5.15.13#L2753

**Comment by KGHTW** [comment]
but it's S905X (GXL) version, not S905 (GXBB)

**Comment by ophub** [comment]
Change the configuration file yourself, compile a kernel with the driver you want.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/7607625404c2927235329080409169b6f72968ff/compile-kernel/tools/config/config-5.4.170#L2755

`CONFIG_MT7601U=y`

Old equipment recommends that you try the `5.4 kernel` first, As a test, when choosing the kernel source code, it is recommended that you compile both `unifreq` and `kernel.org`. Multiple `Actions` can be compiled together.

**Comment by KGHTW** [comment]
So, you want me to compile 4 kernels using `Compile the armbian kernel` action?
- 5.15.13 `unifreq`
- 5.15.13 `kernel.org`
- 5.4.170 `unifreq`
- 5.4.170 `kernel.org`

And after that, should I run `Build armbian` action or what?

**Comment by ophub** [comment]
![Snip20220107_3](https://user-images.githubusercontent.com/68696949/148548500-058efd52-d478-4641-b2a9-8780675442b9.png)

I just looked at it, the current kernel already has this driver, you don't need to compile it.

**Comment by KGHTW** [comment]
Ok, so why it doesn't work for me then?

I'm stuck in the same place as this guy: https://github.com/ophub/amlogic-s9xxx-armbian/issues/61#issue-1093934673

**Comment by ophub** [comment]
The s905 device is sure to support it, which is the dtb and u-boot that I sent you above. Others need to test which can be used from dtb.
You can see which dtb you used in the firmware of balbes150 before, and try to modify it to be the same.
The s905 device is sure to support it, which is the dtb and u-boot that I sent you above. Others need to test which can be used from dtb.
You can see which dtb you used in the firmware of balbes150 before, and try to modify it to be the same.

**Comment by KGHTW** [comment]
Ok, I have tried with `meson-gxbb-mxq-pro-plus.dtb` and:
`u-boot-p201` - boot loop
`u-boot-s905` - no signal

In `balbes150` builds I used:
`u-boot-s905x-s912` and `meson-gxl-s905x-p212.dtb` and it worked fine.
But in  your builds it doesn't work at all :/

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/8f62f9bfc24586490ec1e7ccaf73040d8889bea0/rebuild#L234-L239

The default firmware of s905x is the same as you said, try

**Comment by KGHTW** [comment]
Sadly still not working. I can see text on my screen (the same as on s905x firmware).
But it keeps looking for ethernet instead of using wifi...

**Comment by ophub** [comment]
Well, it seems that fate is not here yet, he still wants to show you the TV interface again.
