### ISSUE TITLE
armbian-install, wifi, ethernet not working on x96 mini (s905w)

### ISSUE THREAD

**Issue by box-automation1** [ophub/amlogic-s9xxx-armbian#621]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

- I booted [Armbian_22.11.0_Aml_s905w_jammy_5.15.73_server_2022.10.13.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_10.13.0358/Armbian_22.11.0_Aml_s905w_jammy_5.15.73_server_2022.10.13.img.gz) from SD card by renaming `u-boot-s905x-s912.bin` to `u-boot.ext` and `extlinux.conf.bak` to `extlinux.conf`
- While Loading, it notifies that wifi, ethernet failed to load. ( see screenshot below )
- armbian-install complains that there is no onboard emmc present. ( see screenshot below )

**Expected behavior**

- Wifi, ethernet should load during startup.
- armbian-install should install armbian to x96 mini emmc.

**Screenshots**

**Armbian Version**
![IMG_20221014_004245525](https://user-images.githubusercontent.com/90855245/195693100-4034b2cd-788e-4d6b-b8ad-c872b5f68075.jpg)
![IMG_20221014_004423522](https://user-images.githubusercontent.com/90855245/195693155-1c5ea887-caea-4d8c-ae13-931e82fccfde.jpg)
![IMG_20221014_004448309](https://user-images.githubusercontent.com/90855245/195693179-b487b8d5-19f6-4d56-85a6-3503c1b97239.jpg)

 - Kernel Version: 5.15.73
 - Release: jammy
 - Edition: server

**Device (please complete the following information):**
 - SOC: S095w
 - Brand: none
 - Model: x96 mini

**Additional context**

- Wifi works with external usb adapter [TP Link Archer T3U( mediatek chip )](https://www.tp-link.com/us/home-networking/usb-adapter/archer-t3u/)
- Last rom flashed was [Android 9 Stock Rom](https://firmwarefile-my.sharepoint.com/:u:/p/172/EYKfi99se51Is1Nc0m-8bc4B0Ft22leBf-EQLNC12okqdw?e=kuKXQr)
- Photos of my box below:

![IMG_20221014_011222378](https://user-images.githubusercontent.com/90855245/195695949-33d1a19d-b952-4309-84e9-d75135c0c26f.jpg)
![IMG_20221014_011229616](https://user-images.githubusercontent.com/90855245/195695979-2c22b136-f8be-43e8-8d73-30814af2c72c.jpg)
![IMG_20221014_011536238](https://user-images.githubusercontent.com/90855245/195696007-94330252-1a0e-4079-be07-031f12ccfd37.jpg)
![IMG_20221014_011757508](https://user-images.githubusercontent.com/90855245/195696037-35f5c211-d82a-43aa-a56a-a865904518f6.jpg)

**Comment by Scirese** [comment]
Can you show your /dev folder?

**Comment by ophub** [comment]
Don't rename extlinux.conf.bak, don't rename u-boot, can you send me the tutorial address where you see these 2 operations.

Try to modify the dtb name:
`vi /boot/uEnv.txt`
Modify the name of the dtb file

Test the following 2 files separately
meson-sm1-sei610.dtb
meson-g12a-x96-max-rmii.dtb

sync && reboot

**Comment by box-automation1** [comment]
> Can you show your /dev folder? The Sv6051 wifi chip seems don't have a driver in the kernel, it's normal that wifi don't work.

[ls-output.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9783478/ls-output.txt)

**Comment by box-automation1** [comment]
> Don't rename extlinux.conf.bak, don't rename u-boot, can you send me the tutorial address where you see these 2 operations.

 I realized that renaming `u-boot-s905x-s912.bin` to u-boot.ext` is **not needed** but the system **fails to boot** without renaming `extlinux.conf.bak` to `extlinux.conf` ( check attached photo below )

![ No renaming of any files ](https://user-images.githubusercontent.com/90855245/195789478-77e1aa5b-0ee2-4e0c-bf31-5604be278d58.jpg)

It only boots if I rename `extlinux.conf.bak` to `extlinux.conf`


>Test the following 2 files separately
meson-sm1-sei610.dtb
meson-g12a-x96-max-rmii.dtb

Tried both of them, none work. The system boots, but armbian-install complains that there is no emmc present and wifi doesn't work.

**Comment by Scirese** [comment]
> > Can you show your /dev folder? The Sv6051 wifi chip seems don't have a driver in the kernel, it's normal that wifi don't work.
> 
> [ls-output.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/9783478/ls-output.txt)

I see. There's only one mmcblk under your /dev and it seems like your sd card. Your internal emmc wasn't recognized by the system. Strange 🤔

**Comment by ophub** [comment]
try `meson-gxl-s905w-p281.dtb`

**Comment by ophub** [comment]
![Snip20221014_1](https://user-images.githubusercontent.com/68696949/195792041-b508777b-68be-412e-8932-e3a1311c97f5.png)

**Comment by box-automation1** [comment]
> ![Snip20221014_1](https://user-images.githubusercontent.com/68696949/195792041-b508777b-68be-412e-8932-e3a1311c97f5.png)

The `u-boot.ext` was unnecessary, my fault.


> If you use extlinux.conf, modify dtb in both his and uEnv.txt files.

Will try modifying in both and report.


> u-boot is not needed, you will cause a lot of errors if you add it. For unknown devices, do not add these unwanted files arbitrarily.

Yes, the system boots without u-boot.
But it doesn't boot if I don't rename extlinux.conf.bak

**Comment by ophub** [comment]
meson-gxl-s905x-p212.dtb
meson-gxl-s905w-p281.dtb

Test these public version files to see which one can drive your wired network card.

**Comment by box-automation1** [comment]
> meson-gxl-s905x-p212.dtb meson-gxl-s905w-p281.dtb
> 
> Test these public version files to see which one can drive your wired network card.

Tried both, none worked sadly.

![IMG_20221014_145451851](https://user-images.githubusercontent.com/90855245/195812636-eacb88f7-16b6-4037-8fba-1f8613bdabb5.jpg)

**Comment by ophub** [comment]
There is no independent network card chip on the motherboard, which is integrated by the soc.

Do you know which NIC driver the box needs?

**Comment by box-automation1** [comment]
> There is no independent network card chip on the motherboard, which is integrated by the soc.
> 
> Do you know which NIC driver the box needs?

I'll check if wifi works on bables150's firmware to confirm. On another note, the wifi isn't related with the emmc not being detected right?

**Comment by Scirese** [comment]
yes, they're different problems.

box-automation1 ***@***.***> 于 2022年10月14日周五 下午6:14写道：

**Comment by box-automation1** [comment]
> > There is no independent network card chip on the motherboard, which is integrated by the soc.
> > Do you know which NIC driver the box needs?
> 
> I'll check if wifi works on bables150's firmware to confirm. On another note, the wifi isn't related with the emmc not being detected right?

Yeah, doesn't work on that either, I checked on armbian forums, and more users faced similar with sv6051/sv6051p(ssv6051/ssv6051p) wifi chips. 
There is a driver for sv6051/p, but it's for 3.x kernel and the driver is poorly written and needs to be re-written for 5.x kernel.

So apparently wifi will be completely dead and I'll have to use my wifi adaptor for that. I'm fine with that for now, but is there any solution for the emmc not being detected?

**Comment by TThanhXuan** [comment]
try below instruction for detect internal EMMC:

sudo apt-get install device-tree-compiler

dtc -I dtb -O dts -o meson-gxl-s905w-p281.dts meson-gxl-s905w-p281.dtb

edit this file searching for "mmc@74000" block
max-frequency = <0x5f5e100>;
5f5e100 in hex = 100000000 in dec
edit it to 0x2faf080, 50000000 in dec

dtc -I dts -O dtb -o meson-gxl-s905w-p281.dtb meson-gxl-s905w-p281.dts

**Comment by box-automation1** [comment]
> try below instruction for detect internal EMMC:
> 
> sudo apt-get install device-tree-compiler
> 
> dtc -I dtb -O dts -o meson-gxl-s905w-p281.dts meson-gxl-s905w-p281.dtb
> 
> edit this file searching for "mmc@74000" block max-frequency = <0x5f5e100>; 5f5e100 in hex = 100000000 in dec edit it to 0x2faf080, 50000000 in dec
> 
> dtc -I dts -O dtb -o meson-gxl-s905w-p281.dtb meson-gxl-s905w-p281.dts

Thanks a lot, install to emmc works. 
[meson-gxl-s905w-p281.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9792841/meson-gxl-s905w-p281.zip) 
  @ophub could the above dtb be added in source(for x96 mini) with @TThanhXuan as author ?

**Comment by ophub** [comment]
[meson-gxl-s905w-x96-mini.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9793437/meson-gxl-s905w-x96-mini.dtb.zip)

I compiled it according to the above revisions. After you download it, unzip it, upload it to the /boot/dtb/amlogic directory, change the previous two configuration files, and restart the test to see if it is correct.

**Comment by ophub** [comment]
meson-gxl-s905w-x96-mini.dts

```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2018 Martin Blumenstingl <martin.blumenstingl@googlemail.com>.
 * Based on meson-gxl-s905d-p231.dts:
 * - Copyright (c) 2016 Endless Computers, Inc.
 *   Author: Carlo Caione <carlo@endlessm.com>
 *           github.com/TThanhXuan, github.com/box-automation1, github.com/unifreq
 */

/dts-v1/;

#include "meson-gxl-s905w-p281.dts"

/ {
	compatible = "amlogic,p281", "amlogic,s905w", "amlogic,meson-gxl";
	model = "X96 mini";
};

/* eMMC */
&sd_emmc_c {
	max-frequency = <50000000>;
};

```

**Comment by box-automation1** [comment]
> Did you test that both wired and wireless work?

This only fixes armbian-install
Wifi cannot be fixed due to missing drivers :( [ Need to rewrite drivers from 3.xx kernel to 5.xx )
> [meson-gxl-s905w-x96-mini.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9793437/meson-gxl-s905w-x96-mini.dtb.zip)

Works with armbian-install. `lsblk` also detects `internal emmc`

**Comment by ophub** [comment]
Is the wired network card working?

**Comment by Neverends4** [comment]
Strange, just found this issue, but my old version downloaded here can detect emmc directly.
`uname -a
Linux X96mini 5.4.184-flippy-70+o #395 SMP PREEMPT Fri Mar 11 22:39:41 CST 2022 aarch64 aarch64 aarch64 GNU/Linux`

**Comment by seem-sky** [comment]
x96 mini emmc中已经安装来armbian系统想重装，需要先擦除emmc中都系统才能从U盘中启动吗？

**Comment by ophub** [comment]
如果usb无法启动，把emmc里/boot下的boot.src和boot.cmd改个名字就无法从emmc启动了，也就会从usb启动了

**Comment by seem-sky** [comment]
> 如果usb无法启动，把emmc里/boot下的boot.src和boot.cmd改个名字就无法从emmc启动了，也就会从usb启动了

因为我都系统有点问题。我忘记来root密码导致系统无法正常启动不能访问emmc无法访问emmc下的文件
![20230215201955](https://user-images.githubusercontent.com/6050445/219026519-c21f58a4-3607-4be7-9b19-1db311fda123.jpg)

**Comment by seem-sky** [comment]
> 那你就线刷会安卓吧

好的，感谢回复。

**Comment by e-renna** [comment]
Just installed armbian with kernel version 6.1.34 on a X96-Mini. Setup went smooth following the suggestions on this issue.
However, the system is only recognising 923Mb of RAM instead of the 2Gb the board has.
Do you have any idea why this might be happening @ophub ?

**Comment by ophub** [comment]
armbian-update -k 6.1.33

Try updating other kernels

**Comment by e-renna** [comment]
> armbian-update -k 6.1.33
> 
> Try updating other kernels

Tried it, but it didn't work ai'm afraid

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/kernel_stable

Try updating other kernels

**Comment by evanferrao** [comment]
> Just installed armbian with kernel version 6.1.34 on a X96-Mini. Setup went smooth following the suggestions on this issue. However, the system is only recognising 923Mb of RAM instead of the 2Gb the board has. Do you have any idea why this might be happening @ophub ?

I have this exact same issue. I have 2 x96 mini. One of them shows up as 2gb ram and other shows up as 1gb only. In android, both of them show up as 2gb ram.

I've noticed something weird though. On the 2gb box, the ram utilization is ~600mb and on the box that falsely shows up as 1gb, the ram utilization is **exactly** half, i.e. ~300mb. These observations were made by running both the boxes side-by-side. Ram measurements in both cases are directly after boot.

Another observation is with a desktop environment running with the same video playback on both the boxes. The first box reported 1400mb ram usage and the second box reported exactly half (~700mb) ram usage with the same desktop environment and same video playback.

This makes me believe that the entire ram is being used, but the software reports utlization by a ratio of 0.5

Just to note, to avoid confusion, the account box-automation1 is mine, and the images posted above of the box is the one that works correctly (software reports 2gb ram)

**Comment by adoyle-h** [comment]
Same issue with x96 mini. Wired interface is working, but wireless interface is not existed. It is under the latest kernel version "6.1.34". @ophub 

```sh
$ uname -a
Linux armbian 6.1.34-ophub #1 SMP Thu Jun 15 22:19:25 EDT 2023 aarch64 aarch64 aarch64 GNU/Linux

$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: sit0@NONE: <NOARP> mtu 1480 qdisc noop state DOWN group default qlen 1000
    link/sit 0.0.0.0 brd 0.0.0.0
3: ip6tnl0@NONE: <NOARP> mtu 1452 qdisc noop state DOWN group default qlen 1000
    link/tunnel6 :: brd :: permaddr 5613:86a2:308::
4: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a2:b1:d2:61:69:b1 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.81/24 brd 192.168.1.255 scope global dynamic noprefixroute eth0
       valid_lft 85651sec preferred_lft 85651sec
    inet6 fe80::9d9e:d5f0:9339:a2a5/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
```

**Comment by ophub** [comment]
What version of the kernel did you have before you could use the wireless function normally?

**Comment by adoyle-h** [comment]
> What version of the kernel did you have before you could use the wireless function normally?

It is an Android TV, not Armbian. The keynel version is 3.14.29.

![CleanShot 2023-06-21 at 16 38 49@2x](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1998490/a7a9c71c-fbc6-482a-b57e-ef0e79a283a0)

![CleanShot 2023-06-21 at 16 40 26@2x](https://github.com/ophub/amlogic-s9xxx-armbian/assets/1998490/14e703fd-59b7-4053-8392-1cc8565bc09c)

**Comment by SXMB** [comment]
您好！现在x906mini安装ambian，只需要uenv.rext中指定dtb就可以了，不需要其他多余的操作？

**Comment by ophub** [comment]
对

**Comment by SXMB** [comment]
谢谢您的回复，一会把盒子折腾起来。

**Comment by deenbee** [comment]
I have the same TV BOX, but need a desktop version,

I try this image : Armbian_20.10_Arm-64_bullseye_current_5.9.0_desktop.img

I see this tutorial https://youtu.be/WngZ4ncBQM8?feature=shared

but my TV BOX do not boot nothing, i press my AV buttom from inside for boot but nothing

any idea?

ussing this server version can install desktop ?

**Comment by ophub** [comment]
armbian-software
201

**Comment by deenbee** [comment]
> armbian-software 201

201 ?

**Comment by deenbee** [comment]
> armbian-software 201

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/26863f60-6aa1-4eb2-9232-f61bec962e96)

don't work

**Comment by ophub** [comment]
Your system files are not downloaded here, use the method to check in the downloaded post.

**Comment by deenbee** [comment]
> Your system files are not downloaded here, use the method to check in the downloaded post.

I need the desktop version, 
the link is died:
Give me a real link

![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/4615556/9895c21b-5dd8-43c9-8e63-94a468f2d618)

**Comment by deenbee** [comment]
I will use this links https://mirror-us-phx1.armbian.airframes.io/dl/aml-s9xx-box/archive/?sort=time&order=asc

**Comment by deenbee** [comment]
I open a new topic here:

https://github.com/ophub/amlogic-s9xxx-armbian/issues/1683

**Comment by vanatd-printify** [comment]
Hello @ophub, I need some help!
I'm trying to run boot mode from tf sd card and my x96 mini with two scenarios:
1. Add my `meson-gxl-s905w-x96-mini.dtb` to the uEnv.txt and rename `u-boot-s905x-s912.bin` to `u-boot.ext` - the result continues reloads with x96 logo blinking
2. Add my `meson-gxl-s905w-x96-mini.dtb` to the uEnv.txt - screen goes black and my monitor goes sleep mode as no signal is coming
Please, can u advise what I did wrong? Or what can I do else?

**Comment by timsams** [comment]
For future users that can't achieve an install (no boot with the sd card like other users). 
Check out the chip inside is really S905W. I received a X96mini with a H313 CPU, batch from october 2023.

**Comment by poVoq** [comment]
Trying with USB and SD and various variations but I only get to the Android bootloader on my older X96-mini.

The only difference I can think of is that I previously installed CoreELEC on the emmc, which is still working for normal booting. Is this a known issue with some easy way to get Armbian boot from USB/SD anyways?

**Comment by BPG-WLCXY** [comment]
> > 刚刚在 X96-Mini 上安装了内核版本为 6.1.34 的 armbian。按照有关此问题的建议，设置进展顺利。但是，系统只能识别 923Mb 的 RAM，而不是板子具有的 2Gb。你知道为什么会发生这种情况吗？
> 
> 我有这个完全相同的问题。我有 2 个 x96 mini。其中一个显示为 2gb ram，另一个仅显示为 1gb。在android中，它们都显示为2gb ram。
> 
> 不过，我注意到了一些奇怪的事情。在 2gb 的盒子上，ram 利用率为 ~600mb，而在错误地显示为 1gb 的盒子上，ram 利用率**正好**是一半，即 ~300mb。这些观察结果是通过并排运行两个框来实现的。在这两种情况下，Ram 测量都是在启动后直接进行的。
> 
> 另一个观察结果是，桌面环境在两个盒子上运行相同的视频播放。第一个框报告了 1400mb 的 ram 使用量，第二个框报告了在相同的桌面环境和相同的视频播放下正好是一半 （~700mb） 的 ram 使用量。
> 
> 这让我相信整个 ram 正在被使用，但软件报告的使用率为 0.5
> 
> 请注意，为避免混淆，帐户 box-automation1 是我的，并且该框上方发布的图像是正常工作的（软件报告 2gb ram）

为何我刷入还爆内核崩溃啊，x96mini

**Comment by BPG-WLCXY** [comment]
我使用的固件是最新版Armbian_24.8.0_amlogic_s905l2_jammy_6.6.46_server_2024.08.15.img
使用的盒子是外贸款X96mini,现在出现一个问题就是检测不到无线网卡模块，但是在安卓TV是可以正常使用的，在Ubuntu无法使用，就是检测不到吧 
#无法连接wifi

**Comment by BPG-WLCXY** [comment]
> 我使用的固件是最新版Armbian_24.8.0_amlogic_s905l2_jammy_6.6.46_server_2024.08.15.img 使用的盒子是外贸款X96mini，现在出现一个问题就是检测不到无线网卡模块，但是在安卓TV是可以正常使用的，在Ubuntu无法使用，就是检测不到吧 #无法连接wifi

这个有没有可能是因为没有把固件刷如EMMC导致的，现在应该是Ubuntu启动了，安卓TV也跟一起启动了然后抢wifi了，给安卓TV抢了所以Ubuntu不能使用了

**Comment by haryantoadhtya** [comment]
![Image](https://github.com/user-attachments/assets/d9b41a06-901a-4f95-b2bd-a5a6197a0d95) saya juga mengalami hal yang sama, di hg680p saya ini , apa ada info solusi ya
