### ISSUE TITLE
Bullseye Server on Beelink GT-King

### ISSUE THREAD

**Issue by MuhmdRaouf** [ophub/amlogic-s9xxx-armbian#622]
**Describe the bug**
I am trying to install bullseye-server on Beelink GT-King
I managed to boot both versions [5.10.147, 5.15.73]

 - Version 5.10.147
sd card booted and installation went great but after reboot, it didn't boot up knowing that I have copied the 
`u-boot-gtking.bin` into `u-boot.ext`, `u-boot.emmc`, `u-boot.sd`, and `u-boot.usb` but didn't boot up again.

 - Version 5.15.73
sd card booted but nothing shows up on screen, so I had to inter using ssh to complete the installtion,
after installing the device bootup and didn't show the terminal on the screen too, but everything went well except for WIFI was not detected.

**Armbian Version**
 - Kernel Versions: [5.10.147, 5.15.73]
 - Release: bullseye
 - Edition: server

**Device (please complete the following information):**
 - SOC: S922x
 - Brand: Beelink
 - Model: GT-King

**Comment by ophub** [comment]
I am very confused. In recent problems, all operations will be to copy files such as u-boot. Can you post the URL of the tutorial you saw? I see how he hurts people.

**Comment by MuhmdRaouf** [comment]
Actually, I was reading the instruction from this repo here: https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md

![Screen Shot 2022-10-15 at 3 34 26 AM](https://user-images.githubusercontent.com/10425180/195963429-b6fc0466-70d6-4df4-b803-400e0c7aa42b.png)

and I didn't know about wifi6 as it doesn't mentioned anywhere, I wonder how CoreELEC gets WIFI working well though.

**Comment by ophub** [comment]
This instruction only allows copying when the memory identification is abnormal. Are you copying because the memory is abnormal? Where can I see the copy of u-boot.sd and u-boot.usb? In which document in this repository did you see this description?

**Comment by MuhmdRaouf** [comment]
Oops, well that's on me, I must understand it wrong, I thought I need to copy those files in order to get it working.
and copying the rest of the `u-boot.sd` and `u-boot.usb` was my idea I just went on replace spree where I changed all files with the pattern `u-boot.*`.

Yet Without Wifi, unfortunately, Armbian won't be a good fit for me, I wanted to install Plex Server without installing over CoreELEC which is basically Kodi with its services, so I am gonna stick with the CoreELEC till further notice till WIFI issue gets solved.

Thanks a lot for your work mate appreciate it so much 🙏🏼 🙏🏼

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/476a9b25ff59b0560349a573a86327a902ebc02c

I removed the description here. This operation is limited to memory debugging. All the places that need to be used are automatically completed by scripts, and there is no need for manual operations.
