### ISSUE TITLE
UNT403A 2+16版本写入EMMC写入错误

### ISSUE THREAD

**Issue by xwnas** [ophub/amlogic-s9xxx-armbian#623]
![QQ图片20221015111746](https://user-images.githubusercontent.com/75593151/195966623-dd41c2c9-c52a-4a29-a7d3-6114eef7d8e8.jpg)
大神请教一下
我有台UNT403A 2+16版本的，U盘引导是正常的，写入错误，换了好几个版本都不行，同型号的2+8的机子是可以正常使用的。不过用ddbr恢复是可以正常引导和使用的，请问一下大神，这个是哪里出问题了。非常感谢！

**Comment by by-JohnChen** [comment]
创建不了引导分区

**Comment by xcray** [comment]
mmc的设备名称不是mmcblk2，也许没识别、也许是另一个名称，看下/dev目录、dtb文件，可能需要修改脚本或dtb

**Comment by ophub** [comment]
`lsblk` 看一下

**Comment by xwnas** [comment]
![屏幕截图 2022-10-15 192822](https://user-images.githubusercontent.com/75593151/195984081-6918046c-2baf-4900-85dd-496a3b697e92.jpg)

**Comment by xwnas** [comment]
> mmc的设备名称不是mmcblk2，也许没识别、也许是另一个名称，看下/dev目录、dtb文件，可能需要修改脚本或dtb

用的是311-1a的dtb，用22C的也一样

**Comment by xwnas** [comment]
![微信图片_20221015193240](https://user-images.githubusercontent.com/75593151/195984224-7a7d3a98-a21c-402e-9ca3-2090a1b799e1.jpg)
用盒子接键盘进行armbian-install安装，是这个提示。发的第一张图是用ssh工具连接盒子执行install

**Comment by xwnas** [comment]
![微信图片_20221015194030](https://user-images.githubusercontent.com/75593151/195984556-493ae9d1-00e9-4429-896f-5ae09ff993c4.jpg)

**Comment by ophub** [comment]
从第一步创建分区就失败了，emmc不让操作

**Comment by xwnas** [comment]
> 从第一步创建分区就失败了，emmc不让操作

嗯，那如何解决呢？我用311-1A16G的版本ddbr备份，可以恢复到这里正常使用

**Comment by ophub** [comment]
你可以ddbr恢复emmc的系统，说明emmc是可以写入的。
格式化不了会是什么原因呢，我也是第一次见这个现象。

前几天有个x96 mini（s905w）的盒子，sd卡启动后识别不到emmc无法写入，网络也不工作，高手给指导了下降低emmc的频率后，可以正常写入并使用了。
https://github.com/ophub/amlogic-s9xxx-armbian/issues/621

不知道对你有没借鉴意义，你可以试试调低下频率看看能不能让emmc正常使用。

**Comment by xwnas** [comment]
> 

我的是能够识别的，是否可以寄送一台给你，帮我研究一下，谢谢

**Comment by ophub** [comment]
你的问题我咨询了下f大，也是建议你改下dts，降低emmc的频率。
可能是你的硬件设计问题，可能是emmc的总线速度太高了。

**Comment by xwnas** [comment]
> 你的问题我咨询了下f大，也是建议你改下dts，降低emmc的频率。 可能是你的硬件设计问题，可能是emmc的总线速度太高了。 以下是修改emmc频率的方法，你用在源码里修改编译（倒数第二行），或者反编译都可以，上面发你的链接里有反编译方法。
> 
> meson-gxl-s905w-x96-mini.dts
> 
> ```
> /dts-v1/;
> 
> #include "meson-gxl-s905w-p281.dts"
> 
> / {
> 	compatible = "amlogic,p281", "amlogic,s905w", "amlogic,meson-gxl";
> 	model = "X96 mini";
> };
> 
> /* eMMC */
> &sd_emmc_c {
> 	max-frequency = <50000000>;
> };
> ```

大神，能帮我帮我直接编译一个，我怕我搞错，我用的是meson-g12a-s905l3a-cm311.dtb，谢谢啦

**Comment by ophub** [comment]
[meson-g12a-s905l3a-cm311.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9793566/meson-g12a-s905l3a-cm311.dtb.zip)

/boot/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb
解压，覆盖USB里的同名文件，重启

**Comment by xwnas** [comment]
> [meson-g12a-s905l3a-cm311.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9793566/meson-g12a-s905l3a-cm311.dtb.zip)
> 
> /boot/dtb/amlogic/meson-g12a-s905l3a-cm311.dtb 解压，覆盖USB里的同名文件，重启

已经测试，没有作用，应该不是这个问题

**Comment by ophub** [comment]
你用晶晨的刷机工具写一个新的安卓系统进去试试有没有问题

**Comment by xwnas** [comment]
> 你用晶晨的刷机工具写一个新的安卓系统进去试试有没有问题

已经测试过，我每次写EMMC前，都是用线刷先刷的安卓系统

**Comment by a520ass** [comment]
可以降到25000000试试，这个问题很常见

**Comment by xwnas** [comment]
> 0000

你好，能帮我降一下吗，我不会编译，用的是311的dtb

**Comment by xwnas** [comment]
已经降频到25000000测试，还是一样，应该不是频率问题

**Comment by maimaiti52** [comment]
可以分享一下cm311-1A备份的文件吗
