### ISSUE TITLE
CM311-1a 低负载依然会出现死机

### ISSUE THREAD

**Issue by babutree** [ophub/amlogic-s9xxx-armbian#625]
Armbian Version
Kernel Version: 5.15.73
Release: Armbian_Aml_bullseye_10.13.0700

Device
SOC: 905l3a
Brand: 魔百盒
Model CM311-1a YST YS(M) 2G RAM 16G ROM

故障同：CM311-1a 网络高负载 死机 https://github.com/ophub/amlogic-s9xxx-armbian/issues/562
但是通过netdata查看死机时（18:56）系统负载非常低 却也突然就死机了 这是第2次发现相同故障 怀疑此前另一台只安装HomeAssistant的机器在出远门回来后无响应也是相同问题，因为没接显示器所以当时没截图，那台比较早内核应该是5.15.4x

![3](https://user-images.githubusercontent.com/21240045/195984367-894cc725-8f32-42b7-96a2-94e4bbe224fd.png)

这是几天前安装后第二天死机时使用采集卡时截图，当时也是突然死机

![2](https://user-images.githubusercontent.com/21240045/195984606-ef1bccd3-8a0c-4173-9d85-50c579a81565.png)

通过截图中的代码搜索发现N1也有相同问题：
https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=7803923
![5](https://user-images.githubusercontent.com/21240045/195987302-8a3dedfc-e47b-4228-971b-0cac4f7d31ef.png)

谢谢O大！

**Comment by babutree** [comment]
似乎是F大内核的问题
![6](https://user-images.githubusercontent.com/21240045/195988403-eb5f8dae-9fe0-492e-8107-4fcfff074347.png)

**Comment by ophub** [comment]
你现在有死机的问题的内核是5.15.73？

**Comment by xcray** [comment]
我手上的两个盒子：m401a和cm311-1a对比，同样环境和差不多的负载，cm311的温度一直比m401a高5~6度。
建议：
 - 改进散热，可临时加个风扇观察；
 - 降低主频，使用conservative策略、最低1G；
 - 换内核；

**Comment by babutree** [comment]
> 你现在有死机的问题的内核是5.15.73？

是的 从5.15.71通过armbian-update 升上来的

**Comment by babutree** [comment]
> 我手上的两个盒子：m401a和cm311-1a对比，同样环境和差不多的负载，cm311的温度一直比m401a高5~6度。 建议：
> 
> * 改进散热，可临时加个风扇观察；
> * 降低主频，使用conservative策略、最低1G；
> * 换内核；

温度确实高 低负载也有50多度 估计和散热片没贴合 
我先试试降频、加风扇看看有没有改善

**Comment by jackcctse** [comment]
我也遇到这个问题。最近换到o大的版本, 刚设定好还没几个服务/应用, 也只有我一个人用, 系统负载不高。还没观察到死机的规律, 头2次分别相隔3-4天, 最近一次只有1天,,,, 替换了电源, USB没插东西。目前在用5.15的内核, 后面再死机, 会试试5.10

**Comment by jackcctse** [comment]
![IMG-20221016-WA0004](https://user-images.githubusercontent.com/41234174/196330967-143a20fa-f423-47a3-9589-58c15689ee00.jpg)

**Comment by jackcctse** [comment]
![IMG-20221016-WA0004](https://user-images.githubusercontent.com/41234174/196331113-a22617ae-7fe5-40d2-8fa8-d03bc1e6d142.jpg)
