### ISSUE TITLE
armbian-build: armbian-docs: Desktop builds failing

### ISSUE THREAD

**Issue by box-automation1** [ophub/amlogic-s9xxx-armbian#627]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

Related Commit [Link](https://github.com/box-automation1/amlogic-s9xxx-armbian/commit/82f9bbc99b634d3adf7c845a2b5407a27e697928)

Desktop builds fail, tried with jammy and focal. (tried with xfce)

**To Reproduce**

- Enable BUILD_DESKTOP=yes and build 

**Expected behavior**

Build Should produce a desktop version of jammy/focal.

**Links**

- [Jammy](https://github.com/box-automation1/amlogic-s9xxx-armbian/actions/runs/3260600865/jobs/5354276527)
- [Focal](https://github.com/box-automation1/amlogic-s9xxx-armbian/actions/runs/3260601316/jobs/5354277333)

**Comment by ophub** [comment]
I only tested the build of the server version, the desktop version needs to specify other parameters, you can refer to the official documentation of armbian to configure
