### ISSUE TITLE
Bullseye build test

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#63]
Hi, 
I tried to build Bullseye but ended up with a release marked focal.
How to specify Bullseye during construction?
Thank you.
```
root@rk3328-MX10-TvBox:/home/ju/armbian-s9xxx/amlogic-s9xxx-armbian# ./rebuild -b s922x -v stable -k 5.4.170 -a true -s 2748
(1) Auto query the latest kernel version of the same series for [ 5.4.170 ]
(1) [ 5.4.170 ] is latest kernel.

(1) [ 5.4.170 ] Kernel is in the local directory.


Welcome to build Armbian for Amlogic s9xxx tv box!
Armbian original file: [ Armbian_21.08.1_Odroidn2_bullseye_current_5.10.60.img ], Version: [ 21.08.1 ], Kernel: [ 5.10.60 ]
Armbian SoC List: [ s922x  ]
Kernel List: [ 5.4.170  ]
Server space usage before starting to compile:
Sys. de fichiers Type Taille Utilisé Dispo Uti% Monté sur
/dev/mmcblk0p1   ext4    58G     53G  3,8G  94% /

(1.1) Start build armbian [ s922x - 5.4.170 ]. Remaining space is 3,8G.
 [ s922x - 5.4.170 ]  (1/5) make new armbian image.
 [ s922x - 5.4.170 ]  (2/5) extract old armbian files.
 [ s922x - 5.4.170 ]  (3/5) replace kernel for armbian.
 [ s922x - 5.4.170 ]  (4/5) copy files to new image.
 [ s922x - 5.4.170 ]  (5/5) clear temp files.
(1.1) Build successfully.

Server space usage after compilation:
Sys. de fichiers Type Taille Utilisé Dispo Uti% Monté sur
/dev/mmcblk0p1   ext4    58G     54G  3,3G  95% /

root@rk3328-MX10-TvBox:/home/ju/armbian-s9xxx/amlogic-s9xxx-armbian# cd build/output/images
root@rk3328-MX10-TvBox:/home/ju/armbian-s9xxx/amlogic-s9xxx-armbian/build/output/images# ls
Armbian_21.08.1_Aml_s922x_focal_5.4.170_2022.01.07.1640.img.gz
Armbian_21.08.1_Odroidn2_bullseye_current_5.10.60.img```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#use-github-action-to-build

New compilation: Select Build armbian on the `Actions` page, According to the OS version officially supported by Armbian, In `RELEASE`, you can choose Ubuntu series: focal, or Debian series: `bullseye` / buster, and in BOARD, you can choose lepotato / odroidn2, etc.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/8f62f9bfc24586490ec1e7ccaf73040d8889bea0/rebuild#L361

Check your version from the original file you provided (/etc/armbian-release). Take a look at the content of this place in the original file, copy it and send it.

**Comment by ophub** [comment]
I used the official `bullseye` mirror to rebuild online, and the result was correct

Source File: https://armbian.tnahosting.net/dl/odroidn2/archive/

Actions: https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/1670035435

Releases: https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_2022.01.08.0926

![Snip20220108_3](https://user-images.githubusercontent.com/68696949/148626318-c33b4cd7-f918-4f44-bb28-b93166f8b598.png)

![Snip20220108_2](https://user-images.githubusercontent.com/68696949/148626306-8c380894-12b5-4df5-9759-caadef34b0f2.png)

![Snip20220108_1](https://user-images.githubusercontent.com/68696949/148626310-b0902bfa-918a-417a-85cd-dce85254eed9.png)
