### ISSUE TITLE
Test compile tca6507 module for led

### ISSUE THREAD

**Issue by livelier** [ophub/amlogic-s9xxx-armbian#630]
(https://github.com/livelier/amlogic-s9xxx-armbian/commit/60a67e67ab0fcf959566a45fbdbd17f497327cea) 增加 `CONFIG_LEDS_TCA6507=y` 
编译 5.10.y 固件后，在固件路径 `/lib/modules/5.10.147-ophub/kernel/drivers/leds/` 下没有 tca6507.ko 模块文件。

o大，请教一下，要修改哪里，编译固件可以包含 tca6507.ko 这个模块

**Comment by ophub** [comment]
个别选项有关联的选择，你进linux-5.10.y内核目录下，手动进面板选择上：
make menuconfig
按/输入关键字找目标的路径，看好了按esc退出搜索，按照刚才看到的路径过到，按空格键选择成*
按save保存

**Comment by livelier** [comment]
![image](https://user-images.githubusercontent.com/104582100/196477916-8ca03e82-8f67-420e-901f-d7ac3fd550d6.png)

按 `/` 查找并核对 `LEDS_TCA6507` 所有关联选项，对应 `Symbol` 选项全部都是 `[=y]`。

只有 `NEW_LEDS` 选项，在 `LED Support` 菜单下没有找到。

```
Location:
     -> Device Drivers
(1)   -> LED Support (NEW_LEDS [=y])
```

但 `CONFIG_NEW_LEDS=y` 默认已经是 `=y`。
https://github.com/ophub/amlogic-s9xxx-armbian/blob/b4721679937c11bd883d32cc9a446b35e2290e62/compile-kernel/tools/config/config-5.10#L5676

这里修改为 `CONFIG_LEDS_TCA6507=m`，之后编译 `s905x3-b` 固件。
https://github.com/ophub/amlogic-s9xxx-armbian/blob/b4721679937c11bd883d32cc9a446b35e2290e62/compile-kernel/tools/config/config-5.10#L5709

![image](https://user-images.githubusercontent.com/104582100/196484029-1039bfbd-71d2-4b1b-a6e2-5b2c3b435f66.png)

新编译的固件 `/boot/config-5.10.147-ophub` 第5709行 仍然是 `# CONFIG_LEDS_TCA6507 is not set`。
并且 `/lib/modules/5.10.147-ophub/kernel/drivers/leds/` 路径下没有发现 `tca6507.ko`。

o大，这个情况，是我哪里操作的不正确吗? 😢

**Comment by ophub** [comment]
https://github.com/livelier/amlogic-s9xxx-armbian/blob/11b56b81b251318e11455df0db7903d68e9f7ac2/.github/workflows/compile-kernel.yml#L84

这个改成 uses: `livelier/amlogic-s9xxx-armbian@main`

用你的源码编译。
同理编译固件时如果你fork后修改了，想测试修改结果，编译固件的地方这个源码也是把来源改为你的仓库。

**Comment by livelier** [comment]
o大，是不是内核包里，没有 `tca6507.ko` 的原因。我编译s905x3-b固件，在固件中始终没有 `tca6507.ko` 😂😂😂

https://github.com/ophub/kernel/blob/main/pub/stable/5.10.149/modules-5.10.149-ophub.tar.gz


另外在 `workflow runs` 发现了一些提示，o大，这是否对固件有影响，没看懂 😁😁😁

```
Build armbian #340
https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/3294034541/jobs/5431148771#step:5:229
https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/3294034541/jobs/5431148771#step:5:1100
```

```
Build armbian #339
https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/3294034004/jobs/5431147733#step:5:229
https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/3294034004/jobs/5431147733#step:5:1120
```

**Comment by ophub** [comment]
这个错误可以怱略，没有.aria2文件就会走https方式下载工具链。

你用什么编译内核呢？在Actions里面每次都是全新编译，在ubuntu22.04(x86_64)服务器里交叉编译arm64内核。所以只要kernel源码里有，而且你.config里面选择了，就应该可以编译岀来。
你在armbian里面用find找不到吗？

find /usr/lib/modules/ -name *tca5607*

**Comment by livelier** [comment]
> 你用什么编译内核呢？

或许我少了步骤。每次我只用 Actions 里面的 Build armbian ，并且 uses: 已经修改为我的库。

![image](https://user-images.githubusercontent.com/104582100/197335560-72ca024a-f938-45f1-9dcf-fa61093322b9.png)

等到发布之后，下载下来，不用写入sd。直接使用 7z 就可以查看文件列表。他始终没有 tca6507 

![image](https://user-images.githubusercontent.com/104582100/197335696-b7040bf9-e18f-4661-ae68-a3017e0a6c5f.png)

o大，除了这个 Actions 操作，还需要其他操作吗？

**Comment by livelier** [comment]
o大，我已经找到，我的错误在哪里啦 🤣🤣🤣

添加驱动，要先编译内核，之后再编译固件。

编译好的内核上传到 复刻你的 kernel 仓库里，然后在复刻的 amlogic-s9xxx-armbian 库存里修改 配置文件 uses 以及 kernel 仓库的路径。

**Comment by ophub** [comment]
内核可以直接上传到armbian里面安装，如上传5.15.100到任意目录，如/opt/5.15.xxx里

```
cd /opt/5.15.xxx
armbian-updare
```

**Comment by livelier** [comment]
收到，感谢 o大 指点。

**Comment by livelier** [comment]
@ophub o大，下次更新内核仓库，集成一下 tca6507驱动

https://github.com/ophub/kernel

还有配置文件 CONFIG_LEDS_TCA6507=y

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel/tools/config

led可以点亮了，我在调整调整之后，提交到仓库。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/191addb9d74b27afdd98218fa917c346c451cc7d
启用了
