### ISSUE TITLE
To Highlight A Potential Solution For GT King Pro (Rev_A) To Be Able To Boot On SD Card 

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#631]
Hi @ophub,

I am having issue with booting your Bullesye or Jammy images/firmwares with kernel 5.10, 5.15 or 5.19 on SD Card.  No issue booting on USB Flash.

I happened to see this article https://github.com/armbian/build/pull/4296 which seems to have potentially identify the problem that is preventing some Amlogic Devices from booting on SD Card.

> There is one issue that needs some sort of resolution however. On the s905x2 box I have (H96 Max X2) the armbian build kernel (meson64) can't read the sd card. However an unpatched mainline kernel works on this box. I have tracked down the offending patch to be: general-meson-gx-mmc-set-core-clock-phase-to-270-degres.patch
> Without this patch the box boots fine, with it it fails to boot. I'm not sure how to work around that

The offending patch in the kernel could be "general-meson-gx-mmc-set-core-clock-phase-to-270-degres.patch" according to the author -- [SteeManMI](https://github.com/SteeManMI).

Is there a possibility to address this in your kernels and release firmwares.  Keep up the great work. 

Thank you.

**Comment by ophub** [comment]
Someone mentioned before, I asked unifreq about the SD card booting, the patch is available, but it may be other reasons, such as voltage, etc. This is not a common problem, my gtk-pro uses the SD card to run itself.

**Comment by JFLim1** [comment]
> This is not a common problem, my gtk-pro uses the SD card to run itself.

Hi @ophub,
Apparently it affect certain Amlogic devices only, one of them is my GT King Pro (Rev_A).  I can boot on SD Card with Armbian-UEFI linux-image-current/edge-arm64 so SteeManMi might/could be on the correct path.

I can boot on SD Card with your kernel 5.4 but kernel 5.4 is not suitable for DE on my device.

**Comment by ophub** [comment]
general-meson-gx-mmc-set-core-clock-phase-to-270-degres.patch

I didn't find this patch in armbian, do you have a link to this patch? I'll send it to unifreq to confirm it

**Comment by JFLim1** [comment]
> general-meson-gx-mmc-set-core-clock-phase-to-270-degres.patch
> 
> I didn't find this patch in armbian, do you have a link to this patch? I'll send it to unifreq to confirm it

Hi @ophub,

Unfortunately I don't have any link for the patch.  From what I understand this patch is already in "linux-image-current-meson64" and "linux-image-edge-meson64" which might also mean already in Unifreq kernels.

**Comment by JFLim1** [comment]
Hi @ophub 

For your info, the latest linux-image-edge-meson64 kernel (6.0.8-meson64 and 6.0.9-meson64) had the offending patch remove and now can boot up on SD Card on GT King Pro (Rev A) and also on other Amlogic TV Boxes.

Currently kernel-5.15.79-flippy-78+o cannot boot on SD Card (I/O Error) and cannot recognize SD Card.  Could not test your kernel-6.0.9-flippy-78+ as it kernel panic on Boot Up with the chainloader u-boot.ext (reported https://github.com/ophub/amlogic-s9xxx-armbian/issues/707).

Hope you can look into this.  Thank you.

**Comment by ophub** [comment]
Which patch was removed? Send me a link.

**Comment by JFLim1** [comment]
> Which patch was removed? Send me a link.

Hi @ophub 

The offending patch seems to be: **general-meson-gx-mmc-set-core-clock-phase-to-270-degres.patch**

https://github.com/armbian/build/pull/4408
https://github.com/armbian/build/pull/4408/commits/f094d997d89e01e8b5d60f769eeb37cbe1e93532

With these changes kernel-6.0.8-meson64 and 6.0.9-meson64 can boot up on SD Card eventhough using dtb from your kernel-flippy-78+ not necessarily have to use dtb from kernel-meson64.

**Comment by ophub** [comment]
Thank you for sharing, I have forwarded the patch information to Mr. Unifreq, the maintainer of the kernel

**Comment by JFLim1** [comment]
> Thank you for sharing, I have forwarded the patch information to Mr. [Unifreq](https://github.com/unifreq), the maintainer of the kernel

Thank you for your great support and amazing work.

**Comment by JFLim1** [comment]
Hi @ophub,

The new kernel-5.15.80-flippy-79+o now can recognize SD Card on my GT King Pro (Rev A) but it seems to have an issue.  This kernel does NOT seems to have GPU Hardware Acceleration (Panfrost) activated in Gnome Desktop Environment.  

```
$ uname -a
Linux opbu 5.15.80-flippy-79+o #193 SMP PREEMPT Sat Nov 26 20:38:02 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

$ glmark2-es2-wayland
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     Mesa/X.org
    GL_RENDERER:   llvmpipe (LLVM 15.0.2, 128 bits)
    GL_VERSION:    OpenGL ES 3.2 Mesa 22.2.1
=======================================================
[build] use-vbo=false: FPS: 55 FrameTime: 18.182 ms
[build] use-vbo=true:^C FPS: 51 FrameTime: 19.608 ms
=======================================================
                                  glmark2 Score: 53 
=======================================================
```

**Comment by JFLim1** [comment]
Hi @ophub

Correction. Panfrost in Kernel-5.15.80-flippy-79+o works this morning. Must have done something wrong yesterday.  My apologies.

Thank you.

```
~$ dmesg
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.15.80-flippy-79+o (root@univm25) (Ubuntu clang version 14.0.0-1ubuntu1, Ubuntu LLD 14.0.0) #193 SMP PREEMPT Sat Nov 26 20:38:02 CST 2022
[    0.000000] Machine model: Beelink GT-King Pro


jlf@opbu:~$ glmark2-es2-wayland
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     Panfrost
    GL_RENDERER:   Mali-G52 (Panfrost)
    GL_VERSION:    OpenGL ES 3.1 Mesa 22.2.1
=======================================================
[build] use-vbo=false: FPS: 802 FrameTime: 1.247 ms
[build] use-vbo=true:^C FPS: 1399 FrameTime: 0.715 ms
```
