### ISSUE TITLE
UNT403A跑网心云掉盘

### ISSUE THREAD

**Issue by tingge9527** [ophub/amlogic-s9xxx-armbian#632]
版本：22.11.0-trunk Jammy with Linux 5.15.71-flippy-77+o
这个问题其实一直困扰着我，从22.08到现在22.11，以及再手动升级过一次内核都是一样掉盘，之前以为是我固态硬盘有问题，后来换了一块固态硬盘还是掉盘，由于我对技术部怎么在行，所以也不知道怎么具体去分析问题所在。就简单说下我知道的情况：
每次掉盘都是掉挂载目录，比如我把固态硬盘挂载到了 /mnts，然后跑着跑着就掉盘后，我用lsblk查看，固态硬盘的盘符还在，但是盘符后面没有显示挂载的目录了。
之前一两天就出现掉盘，后来我换升级了内核后，换了固态后，这次是大概9天才出现了掉盘，由于我没有在掉盘时查看，不过根据之前的看网心云跑的速度的时候，猜测大概率是跑起来之后就出现掉盘了。不知道要提供什么信息供O大参考，若有需要我可以提供这个机器的SSH远程访问（因为有动态公网IP）。

**Comment by ophub** [comment]
```
cat /etc/fstab
blkid
lsblk
```
看下这几处的情况

**Comment by tingge9527** [comment]
> ```
> cat /etc/fstab
> blkid
> lsblk
> ```
> 
> 看下这几处的情况

额。我现在已经reboot重启了，重启之后已经正常了。下次再掉盘的时候我查看下吧。现在的我也截图给你
![MC8(7DXNP~J4U2B~PZ7%2PB](https://user-images.githubusercontent.com/116063135/196370680-a09e1083-4a9c-4e21-b09c-0751ba7e81a8.png)

**Comment by tingge9527** [comment]
我在自己找相同问题的时候，在恩山有看到这个帖子：n1刷入armbian后挂载usb硬盘隔夜掉盘
https://www.right.com.cn/FORUM/thread-4007054-1-1.html
(出处: 恩山无线论坛)
由于我出现问题后我reboot了，所以没有注意看细节，但是猜测跟帖子中的一样，有可能是休眠之后sda1变成了sdb1才导致的盘在，但是挂载掉了。目前我自己的打算只能等下一次掉盘的时候好好记录下情况了。感谢O大解答。

**Comment by xinshutong** [comment]
请参考 #543 我觉得不是休眠的问题，我的是刚插上没几分钟，就开始了，sda1 sdb1 跳来跳去，能听到硬盘忽停忽抓。

**Comment by tingge9527** [comment]
> 请参考 #543 我觉得不是休眠的问题，我的是刚插上没几分钟，就开始了，sda1 sdb1 跳来跳去，能听到硬盘忽停忽转。

#543 的我看了，我关闭休眠看看，我的不是插上一两天就掉盘的，而是隔了9天才掉盘的。我先关闭休眠再看看把

**Comment by gametta** [comment]
以前有个帖子说的很明白了，电视盒子有这个问题，我用了四五种易驱线，包括H1的，都存在掉盘的问题，这些易驱线在wky和N1盒子都没问题，那个帖子核心就一句话电视盒子用1153E的易驱线，不会掉，首选绿联20231带电源孔的那种60cm长的。不要用杂牌和山寨的。

**Comment by tingge9527** [comment]
> 帖子#543说的很明白了，电视盒子有这个问题，我用了四五种易驱线，包括H1的，都存在掉盘的问题，这些易驱线在wky和N1盒子都没问题，那个帖子核心就一句话电视盒子用1153E的易驱线，不会掉，首选绿联20231带电源孔的那种60cm长的。不要用杂牌和山寨的。

好的，不过我目前先测试关闭休眠之后看掉盘问题是否还出现，如果再出现我就换个主控1153E的易驱线

**Comment by gametta** [comment]
> > 帖子#543说的很明白了，电视盒子有这个问题，我用了四五种易驱线，包括H1的，都存在掉盘的问题，这些易驱线在wky和N1盒子都没问题，那个帖子核心就一句话电视盒子用1153E的易驱线，不会掉，首选绿联20231带电源孔的那种60cm长的。不要用杂牌和山寨的。
> 
> 好的，不过我目前先测试关闭休眠之后看掉盘问题是否还出现，如果再出现我就换个主控1153E的易驱线

这个你用不测试了，我替你测试过了，现在的版本都关闭了休眠，这个应该是兼容性的问题。只有用1153E易驱线才能完美解决，1153e的易驱线品牌的和山寨的没差多少钱，单根购买不划算，一批买又不一定能退货，直接买品牌省心。

**Comment by tingge9527** [comment]
> > > 帖子#543说的很明白了，电视盒子有这个问题，我用了四五种易驱线，包括H1的，都存在掉盘的问题，这些易驱线在wky和N1盒子都没问题，那个帖子核心就一句话电视盒子用1153E的易驱线，不会掉，首选绿联20231带电源孔的那种60cm长的。不要用杂牌和山寨的。
> > 
> > 
> > 好的，不过我目前先测试关闭休眠之后看掉盘问题是否还出现，如果再出现我就换个主控1153E的易驱线
> 
> 这个你用不测试了，我替你测试过了，现在的版本都关闭了休眠，这个应该是兼容性的问题。只有用1153E易驱线才能完美解决，1153e的易驱线品牌的和山寨的没差多少钱，单根购买不划算，一批买又不一定能退货，直接买品牌省心。

我的版本我看了，没有关闭休眠，所以我这次参照了543关闭了休眠，等下次出现问题再说吧。手里已经有4个移动硬盘盒了。

**Comment by xinshutong** [comment]
我测试过，硬盘休眠是由易驱线主控控制的，改armbian的设置根本没用，我都是刷主控固件改的。你们有用？

**Comment by tingge9527** [comment]
> 我测试过，硬盘休眠是由易驱线主控控制的，改armbian的设置根本没用，我都是刷主控固件改的。你们有用？

今天又掉盘了，这次出现的很快，看了的确是从sda变成了sdb所以没了挂载，系统的自动休眠应该是无用的，我试试改jms578的主控休眠关闭试试

**Comment by wasdqwerdf** [comment]
感觉还是供电原因导致的掉盘
