### ISSUE TITLE
Possible support for A95X F1 (S905W)?

### ISSUE THREAD

**Issue by operamilkmandolinneo12** [ophub/amlogic-s9xxx-armbian#635]
Since I found the previous 2020 version of Armbian (which was not supported since last year), is there a possibility that there's a support for this box?

**Comment by ophub** [comment]
There is the latest firmware of s905w in the download area. You download and test it. Do you know which dtb name your box uses? Modify the name in /boot/uEnv.txt.

**Comment by operamilkmandolinneo12** [comment]
I think it's `/dtb/amlogic/meson-gxl-s905w-p281.dtb` when I installed the previous Armbian in my box.

**Comment by ophub** [comment]
Ok, then you should be able to use the 5.15.y firmware
