### ISSUE TITLE
UNT413a 启动网卡不工作

### ISSUE THREAD

**Issue by alegoho** [ophub/amlogic-s9xxx-armbian#636]
你好！我机器是九联的UNT413a，是S905L3A SOC，我下载OPENWRT和ARMBIAN对应S905L3a的刷包，从U盘启动后两个包网卡都不能工作，一直在WINDOWS上显示是 X 的状态。但原来电视系统有线和无线都能正常工作的。我后来改成S905X2的DTB，启动不了，但网卡有反应，就是显示正在获取IP，但启动不了，IP是获取不到。我换了一台电脑测试，还是一样

**Comment by ophub** [comment]
UNT413A
移动魔百盒UNT413A，无TF卡槽，无线uwe5621，盒子有两种S905L3A芯片的和S905L3芯片的，其中S905L3的测试可以，但是S905L3A能否通刷待测试!

[image](https://user-images.githubusercontent.com/68696949/197130813-3cb8bdd7-f539-4706-83c1-e4701c7aa669.png)

![image](https://user-images.githubusercontent.com/68696949/197130848-1d76648a-1a2f-4192-9537-8c96fb2d1628.png)

**Comment by alegoho** [comment]
> UNT413A 移动魔百盒UNT413A，无TF卡槽，无线uwe5621，盒子有两种S905L3A芯片的和S905L3芯片的，其中S905L3的测试可以，但是S905L3A能否通刷待测试
> 
> ![image](https://user-images.githubusercontent.com/68696949/197130813-3cb8bdd7-f539-4706-83c1-e4701c7aa669.png)
> 
> ![image](https://user-images.githubusercontent.com/68696949/197130848-1d76648a-1a2f-4192-9537-8c96fb2d1628.png)
> 
> https://docs.qq.com/doc/DWFprWWxZa290VXNk
> 
> 这里有相关的说明
> 
> ```
> 304:E900V22C-D:s905l3a:meson-g12a-s905l3a-e900v22c.dtb:u-boot-e900v22c.bin:NA:NA
> 305:CM311-1a-YST:s905l3a:meson-g12a-s905l3a-cm311.dtb:u-boot-e900v22c.bin:NA:NA
> 306:M302A/M304A:s905l3b:meson-gxl-s905l3b-m302a.dtb:u-boot-s905x-s912.bin:NA:NA
> ```
> 
> 默认是304的dtb，你手动把/boot/uEnv.txt改成305和306的试试

感谢回复，我拆机看是S905L3a，那就是没救了？

**Comment by ophub** [comment]
他没测试过，你试试

**Comment by alegoho** [comment]
> 他没测试过，你试试

第一和第二个一样，网卡不工作，第三个直接就不启动了

**Comment by ophub** [comment]
试5.15.y系列的固件

**Comment by sd7890** [comment]
盒子连显示器查看跑码情况才能确定问题

**Comment by Akitlove** [comment]
> 你好！我机器是九联的UNT413a，是S905L3A SOC，我下载OPENWRT和ARMBIAN对应S905L3a的刷包，从U盘启动后两个包网卡都不能工作，一直在WINDOWS上显示是 X 的状态。但原来电视系统有线和无线都能正常工作的。我后来改成S905X2的DTB，启动不了，但网卡有反应，就是显示正在获取IP，但启动不了，IP是获取不到。我换了一台电脑测试，还是一样

这个s905x2是那个设备
