### ISSUE TITLE
咪咕盒子MGV2000，cpu是s905L，能刷吗?

### ISSUE THREAD

**Issue by Wayne8610** [ophub/amlogic-s9xxx-armbian#637]

**Comment by ophub** [comment]
meson-gxl-s905x-p212.dtb
开启USB调试模式，ADB

**Comment by Wayne8610** [comment]
感谢，固件是用s905L3a那个吗？

**Comment by Wayne8610** [comment]
> meson-gxl-s905x-p212.dtb 开启USB调试模式，ADB



> 

感谢，固件是下载s905L3a那个吗？

**Comment by ophub** [comment]
可以

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/648

你看看这个帖子

**Comment by Wayne8610** [comment]
> 

太感谢了，我试一下。

**Comment by Wayne8610** [comment]
> #648
> 
> 你看看这个帖子



> #648
> 
> 你看看这个帖子

非常感谢，我参照试一下。

**Comment by Wayne8610** [comment]
> #648
> 
> 你看看这个帖子

参考帖子运行成功了，可用有线，也是没有WiFi
