### ISSUE TITLE
ssh服务不启动

### ISSUE THREAD

**Issue by nicolite** [ophub/amlogic-s9xxx-armbian#638]
cm311-1a-yst从emmc启动，如果在/etc/fstab中挂载了硬盘，会出现ssh服务不启动，并且移除/etc/fstab中的内容重启也不会启动ssh服务。需要手动添加ssh服务开机启动【systemctl enable ssh】，后续恢复。

总结解决方案（供大家参考）：
1、移除/etc/fstab中添加的内容
2、手动开启ssh服务开机启动命令：systemctl enable ssh

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/953feaeed6e14f23885f4d6184f841bbef4fe465

和硬盘无关
最近一周的固件可能都🈶️这个通病，ssh总是不自启动，我试了一下，把Port 22改为其他端口，如Port 2234
再加一个自动检测sshd目录的任务，就可以了
