### ISSUE TITLE
中兴盒子，cpu s905l，板载无线realtek 8189ftv，有线正常，无线无法使用，请教解决办法

### ISSUE THREAD

**Issue by MRnewUser** [ophub/amlogic-s9xxx-armbian#640]
大佬们好：
盒子：zvx10b860av2.1
dtb : meson-gxl-s905x-p212.dtb
无线 ：realtek 8189ftv
cpu  :amlogic  s905l
刷入armbian后有线工作正常，无线不能使用，请教该怎么解决，
如果需要修改dtb，请教该如何修改。
谢谢~

**Comment by MRnewUser** [comment]
以下是我在从安卓里面提取的gxl-p211-1g.dtb中与wifi有关的内容，不知是否有用，期待大佬的帮助

           wifi_32k_pins {
			              amlogic,setmask = <0x05 0x8000>;
			              amlogic,pins = "GPIOX_16";
			              linux,phandle = <0x22>;
			              phandle = <0x22>;
		              };


wifi {
		compatible = "amlogic, aml_wifi";
		dev_name = "aml_wifi";
		status = "okay";
		interrupt_pin = <0x21 0x56 0x00>;
		interrupts = <0x00 0x44 0x04>;
		irq_trigger_type = "GPIO_IRQ_LOW";
		power_on_pin = <0x21 0x4c 0x00>;
		pinctrl-names = "wifi_32k_pins";
		pinctrl-0 = <0x22>;
	};

**Comment by MRnewUser** [comment]
[安卓dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9846122/dts.zip)
这是安卓里面提取的dtd,不知如何对比修改

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/search?q=8189

目前内核里没搜到8189驱动，暂时不支持。

**Comment by MRnewUser** [comment]
感谢大佬百忙之中的回复，
我找到了一份8189的驱动源码：https://github.com/jwrdegoede/rtl8189ES_linux ，

然后，我发现[Armbian_22.11.0_Aml_s905x_jammy_5.15.74_server_2022.10.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_jammy_10.20.2346/Armbian_22.11.0_Aml_s905x_jammy_5.15.74_server_2022.10.21.img.gz) 这个release里面包含8189的驱动8189fs.ko，在/usr/lib/modules/5.15.74-flippy-78+o/kernel/drivers/net/wireless/realtek/rtl8189fs路径下。

同时，我也发现了一份3.14内核的release（ https://pan.baidu.com/s/1fyZRB-KKH0BbALXICB5X8w 提取码: 2333），可以使wifi正常工作，这是其对应的dtb
[gxl_p212_1g.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9870284/gxl_p212_1g.zip)

但是，在主线内核里面，我不知道该如何修改dts，使wifi工作...

**Comment by MRnewUser** [comment]
当前5.15版本/sys/bus/sdio/devices/下面没有设备
![image](https://user-images.githubusercontent.com/116421350/198059123-09f7fdc2-7eb1-432b-93a6-417dc0134f47.png)


3.14wifi正常的版本下面能看到wifi设备
![image](https://user-images.githubusercontent.com/116421350/198057939-93006db7-54e3-4f8f-ba2f-1f9f64e21d50.png)

**Comment by lppsuixn** [comment]
> 

同样的问题。请问老哥百度网盘里用的哪个镜像？

**Comment by 84864797** [comment]
https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=4053939&page=1   我刷的这个固件  8189能驱动

**Comment by MRnewUser** [comment]
哇，老哥用的固件能分享一份吗~

**Comment by lppsuixn** [comment]
> 芜湖，我只试了了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了cpu温度，，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载 ![image](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)

奇怪，我这个不行。860av1.1t

**Comment by 84864797** [comment]
> 哇，老哥用的固件能分享一份吗~

不是发你网站了吗

**Comment by 84864797** [comment]
> > 芜湖，我只试了了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了cpu温度，，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载 ![image](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)
> 
> 奇怪，我这个不行。860av1.1t

你可以下载我分享的那个包  刷好就可以用WiFi了   我的温度也看不了2°C不会变

**Comment by MRnewUser** [comment]
modprobe 8189fs，手动加载下驱动

**Comment by MRnewUser** [comment]
刚刚试了下那个网站里面百度网盘分享的，我的机器上面好像不行

**Comment by MRnewUser** [comment]
试了这两个

![image](https://user-images.githubusercontent.com/116421350/198286722-b7e6451f-8279-4ba0-b715-5a6639bd988d.png)

**Comment by MRnewUser** [comment]
老哥你用的上面的固件还是下面的那个固件，20.11那个我还没试，有点大，没下完。。

![image](https://user-images.githubusercontent.com/116421350/198286998-cc936f5b-bdbb-406b-9006-258ed198d1f9.png)

**Comment by 84864797** [comment]
> 老哥你用的上面的固件还是下面的那个固件，20.11那个我还没试，有点大，没下完。。
> 
> ![image](https://user-images.githubusercontent.com/116421350/198286998-cc936f5b-bdbb-406b-9006-258ed198d1f9.png)

上面的吧  我刷klipper的  用的应该是P212  这个DTB   新魔百盒201H

**Comment by 84864797** [comment]
> ![1666874462569](https://user-images.githubusercontent.com/116421350/198287253-e51c9a92-5c25-4e6e-a235-774704288f27.png)
> 
> 老哥你用的那个固件，20.09那个我还没试，没下载完

用油猴 呀  百度网盘慢速下载

**Comment by dawei** [comment]
我的x96air也是这个无线网卡，也是不能使用

**Comment by 84864797** [comment]
> 大佬们好： 盒子：zvx10b860av2.1 dtb : meson-gxl-s905x-p212.dtb 无线 ：realtek 8189ftv cpu :amlogic s905l 刷入armbian后有线工作正常，无线不能使用，请教该怎么解决， 如果需要修改dtb，请教该如何修改。 谢谢~

可以用了没有？

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/search?q=8189

内核里没有无线驱动

**Comment by MRnewUser** [comment]
> https://github.com/unifreq/linux-5.15.y/search?q=8189
> 
> 内核里没有无线驱动

好的，那我还是用

> > 大佬们好： 盒子：zvx10b860av2.1 dtb : meson-gxl-s905x-p212.dtb 无线 ：realtek 8189ftv cpu :amlogic s905l 刷入armbian后有线工作正常，无线不能使用，请教该怎么解决， 如果需要修改dtb，请教该如何修改。 谢谢~
> 
> 可以用了没有？

回复晚了，抱歉，
试了下，我这个还是不行，哈哈，莫得办法..
用的meson-gxl-s905x-p212这个

**Comment by MRnewUser** [comment]
> https://github.com/unifreq/linux-5.15.y/search?q=8189
> 
> 内核里没有无线驱动

好的~

**Comment by MRnewUser** [comment]
> > 芜湖，我只试了了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了cpu温度，，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载 ![image](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)
> 
> 奇怪，我这个不行。860av1.1t

modprobe 8189fs 加载下驱动

**Comment by 84864797** [comment]
> > > 芜湖，我只试了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了CPU温度，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载![图像](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)
> > 
> > 
> > 奇怪，我这个不行。860av1.1t
> 
> modprobe 8189fs 加载下驱动

那请问怎么 设置开机自动加载？
modprobe 8189fs  加在哪个文件里 的哪行？

**Comment by MRnewUser** [comment]
> > > > 芜湖，我只试了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了CPU温度，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载![图像](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)
> > > 
> > > 
> > > 奇怪，我这个不行。860av1.1t
> > 
> > 
> > modprobe 8189fs 加载下驱动
> 
> 那请问怎么 设置开机自动加载？ modprobe 8189fs 加在哪个文件里 的哪行？

![image](https://user-images.githubusercontent.com/116421350/198532404-9f24c9f3-4de6-4b58-9c09-75f0ea9c8e20.png)
试试这个，在这个文件里面新加一行8189fs

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl8189fs

![Snip20221028_1](https://user-images.githubusercontent.com/68696949/198533412-b30f9eee-67f0-43b4-bb67-3cfafce23bbf.png)

我去源码里看了下有rtl8189fs的驱动，在固件里也有。为什么在github仓库搜没有结果呢？
`modprobe 8189fs`试试启用了没？

**Comment by 84864797** [comment]
> 

我现在在瞎折腾8822cs WIFI驱动 加载不起来  核心里有82x2cs  驱动 但是modprobe 82x2cs  wifi还是没反应

**Comment by MRnewUser** [comment]
> https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl8189fs
> 
> ![Snip20221028_1](https://user-images.githubusercontent.com/68696949/198533412-b30f9eee-67f0-43b4-bb67-3cfafce23bbf.png)
> 
> 我去源码里看了下有rtl8189fs的驱动，在固件里也有。为什么在github仓库搜没有结果呢？ https://github.com/unifreq/linux-5.15.y/search?q=8189 这搜索好像不准确？ `modprobe 8189fs`试试启用了没？




> https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl8189fs
> 
> ![Snip20221028_1](https://user-images.githubusercontent.com/68696949/198533412-b30f9eee-67f0-43b4-bb67-3cfafce23bbf.png)
> 
> 我去源码里看了下有rtl8189fs的驱动，在固件里也有。为什么在github仓库搜没有结果呢？ https://github.com/unifreq/linux-5.15.y/search?q=8189 这搜索好像不准确？ `modprobe 8189fs`试试启用了没？



![1666944328074](https://user-images.githubusercontent.com/116421350/198538472-d27dd62b-a656-465b-9fb4-3362860ee1aa.png)

一开始是没有加载的，尝试使用modeprobe 8189fs加载，模块初始化返回结果是0（成功？），但是ifconfig里面并没有wlan0

**Comment by MRnewUser** [comment]
> > 
> 
> 我现在在瞎折腾8822cs WIFI驱动 加载不起来 核心里有82x2cs 驱动 但是modprobe 82x2cs wifi还是没反应


哈哈，我现在躺平了，缺乏相关知识，不知该如何修改~

**Comment by ophub** [comment]
armbian-config里看看无线能不能搜到周围的热点

**Comment by MRnewUser** [comment]
> armbian-config里看看无线能不能搜到周围的热点



![1666945876973](https://user-images.githubusercontent.com/116421350/198553735-c879163a-2b42-4470-ba66-6456b81538a7.png)
![1666945928097](https://user-images.githubusercontent.com/116421350/198553759-f104dba5-4ef7-4346-8377-b6b5ec94a0da.png)
armbian-config里面没有wireless选项，我在想，是不是这个mmc或者wifi的dts配置有点问题导致的，
因为通过 ls  /sys/bus/mmc/devices  ，只能看到两个mmc，wifi连接的那个mmc看不到，
当然，这方面我不懂，瞎猜测，哈哈

**Comment by 84864797** [comment]
> > > > > 芜湖，我只试了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了CPU温度，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载![图像](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)
> > > > 
> > > > 
> > > > 奇怪，我这个不行。860av1.1t
> > > 
> > > 
> > > modprobe 8189fs 加载下驱动
> > 
> > 
> > 那请问怎么 设置开机自动加载？ modprobe 8189fs 加在哪个文件里 的哪行？
> 
> ![image](https://user-images.githubusercontent.com/116421350/198532404-9f24c9f3-4de6-4b58-9c09-75f0ea9c8e20.png) 试试这个，在这个文件里面新加一行8189fs

大佬你这个 百度网盘共享下呀

**Comment by MRnewUser** [comment]
> > > > > > 芜湖，我只试了这两个，其他的没试，这两个都可以用wifi，不过，似乎都看不了CPU温度，有兴趣可以试下，进去要手动加载驱动才能用wifi，modprobe 8189fs，长期用可以添加开机自动加载![图像](https://user-images.githubusercontent.com/116421350/198068759-8f82160b-7556-4a39-a0ad-cfca69524a22.png)
> > > > > 
> > > > > 
> > > > > 奇怪，我这个不行。860av1.1t
> > > > 
> > > > 
> > > > modprobe 8189fs 加载下驱动
> > > 
> > > 
> > > 那请问怎么 设置开机自动加载？ modprobe 8189fs 加在哪个文件里 的哪行？
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/116421350/198532404-9f24c9f3-4de6-4b58-9c09-75f0ea9c8e20.png) 试试这个，在这个文件里面新加一行8189fs
> 
> 大佬你这个 百度网盘共享下呀


![1666956686814](https://user-images.githubusercontent.com/116421350/198578010-3cb6dd21-f231-4f7d-8681-07b31dca7d65.png)


老哥，你是说这个吗，（ https://pan.baidu.com/s/1fyZRB-KKH0BbALXICB5X8w 提取码: 2333）
然后，我不是大佬，哈哈，我只是个搬运工~

**Comment by haitian138** [comment]
我的也是中兴盒子，cpu s905mb，板载无线realtek 8189ftv，装了Armbian_25.02.0_amlogic_s905lb-r3300l_bullseye_6.6.68_server_2025.01.01.img，有线正常，无线无法使用。
希望ophub更新固件加上realtek 8189ftv的驱动。

**Comment by S-9527** [comment]
> 我的也是中兴盒子，cpu s905mb，860av1.1t，板载无线realtek 8189ftv，装了Armbian_25.02.0_amlogic_s905lb-r3300l_bullseye_6.6.68_server_2025.01.01.img，有线正常，无线无法使用。 希望ophub更新固件加上realtek 8189ftv的驱动。

自行编译并加载8189fs驱动后,还是没办法使用WiFi的,没有wlan0,估计在更新固件的时候加上也没什么作用

**Comment by overtimer1** [comment]
> 我的也是中兴盒子，cpu s905mb，860av1.1t，板载无线realtek 8189ftv，装了Armbian_25.02.0_amlogic_s905lb-r3300l_bullseye_6.6.68_server_2025.01.01.img，有线正常，无线无法使用。 希望ophub更新固件加上realtek 8189ftv的驱动。

同款设备，同样问题，请ophub大佬支持一下

**Comment by S-9527** [comment]
> > 我的也是中兴盒子，cpu s905mb，860av1.1t，板载无线realtek 8189ftv，装了Armbian_25.02.0_amlogic_s905lb-r3300l_bullseye_6.6.68_server_2025.01.01.img，有线正常，无线无法使用。 希望ophub更新固件加上realtek 8189ftv的驱动。
> 
> 同款设备，同样问题，请ophub大佬支持一下

#3193 已解决,欢迎测试

**Comment by qiaoyiyi** [comment]
ZXV10 B860AV2.1 ，可以确认WiFi没有的原因的是dtb不对，我让ai分析了dtb，最后ai参考已有的dtb写了一个新的 meson-gxl-s905l3b-m302a-wifi-dv27.dtb ，其实可以让ai分析一下dtb给你编写一个正确的dtb。

**Comment by qiaoyiyi** [comment]
<img width="894" height="589" alt="Image" src="https://github.com/user-attachments/assets/b3c7cb7a-e56f-440c-b107-a358e4f41ee9" />

**Comment by qiaoyiyi** [comment]
<img width="630" height="849" alt="Image" src="https://github.com/user-attachments/assets/ff24d2c2-2ab3-4141-9ee7-33aa1c845ac9" />

**Comment by qiaoyiyi** [comment]
[meson-gxl-s905l3b-m302a.zip](https://github.com/user-attachments/files/32376430/meson-gxl-s905l3b-m302a.zip)

**Comment by ophub** [comment]
这个dtb被很多设备共用，上个月刚改为7668，为了解决这个问题，我添加了新的`meson-gxl-s905l3b-m302a-v2.dtb` 这个是对应8189ftv驱动的。
设备的board名字叫：`s905l3b-m302a`，对应的model id是`113`： https://github.com/ophub/amlogic-s9xxx-armbian/commit/37aa91cbd377a5cc9f6d674e33dabf06355af0f8

dts： https://github.com/ophub/linux-6.18.y/commit/f7f44dda24dcadefc03e76726d62db0d0b4dde46
