### ISSUE TITLE
救砖！s905l3a,魔百和cm311-1a，armbian写入了emmc

### ISSUE THREAD

**Issue by Edwardyx** [ophub/amlogic-s9xxx-armbian#641]
刷的是[Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.74_server_2022.10.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_10.20.2320/Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.74_server_2022.10.21.img.gz)
1、刷完输入armbian-config，半天没反应，就去做其他事，然后被就被朋友叫出去爬山。
2、回来以后发现ssh被关了（估计就是小鬼玩游戏了），我就重新打开powershell重新连，但发现连不上，关机开机折腾了半天，发现盒子上的通电指示灯都不亮了，屏幕完全就是黑的。
3、问家里小鬼（初一）就说他玩了下，问了半天，说是有个界面，第一个选项，一路enter，ok下去，见没什么变化，也就关掉了powershell，然后就自己玩了。
4、因为刚刷的系统，我也没见到armbian-config界面，也不知道第一个选项是啥子，他一路enter都不知道干了啥。他印象里说是有SD、USB之类的单词。
现在，只好来求助大神了。这黑砖要咋办？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

12.3.2 里面有方法、安卓系统下载链接、压缩包里有短接点图示。

**Comment by Edwardyx** [comment]
打开Amlogic_USB_Burning_Tool_v3.2.0结果提示如下
> startDetached V2 Usb buring tool failed!./V2/USB_Burning_Tool.exe is not exist.
我去MIK网站下了3.18，3.10，都是提示上面的。
还在恩山论坛下了百度网盘里面的2.2版本，结果又提示少了个什么dll。头疼

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

这可以下载

**Comment by livelier** [comment]
卸载其他版本，在安装这个版本尝试一下。这个版本在 `windows10 21H2 x64` 系统下正常使用。
（`V2` `V3`版本，选可以正常连接到盒子的版本。我的 `S905X3-B` 只能连接到 `V2`。）

[v2.2.4.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/9851300/Amlogic.USB.Burning.Tool.v2.2.4.zip) 

这是成功连接盒子，开始烧录前的设备状态。

![image](https://user-images.githubusercontent.com/104582100/197519308-e5d86e04-36f2-4e3b-8e57-432244fae22b.png)

**Comment by Edwardyx** [comment]
谢谢大佬热心帮忙，我通过https://github.com/ophub/kernel/releases/tag/tools下载的3.2版本中的pdf文件，去下载了2.17版本，是可以正常打开加载img的，同时也按照步骤识别并开始刷机了。我是接了usb线，接了电源线，在短接的同时按下开机通电按钮，线刷就能识别到并开始滚进度条，按照说明，开始读条后我就松了短接。
但是每次都是卡在不同的地方。我甚至试了擦除flash和bootloader刷还是不行。
我有尝试在开始刷机卡住的时候，保持usb连接，重新短接，重新开机通电。
也有尝试拔usb重新来过，反复多次但都提示卡在uboot：
昨晚线刷了1个小时。。。
https://github.com/Edwardyx/Pictures/blob/main/Snipaste_2022-10-24_18-07-00.png
https://github.com/Edwardyx/Pictures/blob/main/Snipaste_2022-10-24_18-11-53.png
https://github.com/Edwardyx/Pictures/blob/main/Snipaste_2022-10-24_18-29-24.png

**Comment by ophub** [comment]
你的安卓系统从哪下的？找你买盒子的店家要个可以适配的系统。
或者在你刚才的kernel下载工具的网址里有cm311的这个系统，你试试。

**Comment by Edwardyx** [comment]
好吧。Android是从你给的链接tools里面下载的[android_tv_cm311-1a-yst_s905l3a.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_cm311-1a-yst_s905l3a.tar.xz)

![Snipaste_2022-10-25_14-23-08](https://user-images.githubusercontent.com/63174337/197697912-c8b71b52-31bf-447b-9f48-ddf31d15269e.png)
那我再继续试试。

**Comment by conaco66** [comment]
依次换PC的USB接口，换线，换烧录软件版本，换镜像版本。大部分时候是烧录线和接口的问题

**Comment by Edwardyx** [comment]
救是救回来了，但是不知道为什么，用开心电视助手连接之后，点击“调试”--从U盘启动，开心电视助手就卡死了。一直没办法重新刷盒子。
我刷入的就是大佬给的[android_tv_cm311-1a-yst_s905l3a.tar.xz](https://github.com/ophub/kernel/releases/download/tools/android_tv_cm311-1a-yst_s905l3a.tar.xz)
