### ISSUE TITLE
大佬你好 我有个M302A盒子  是S905L2B 请问我应该刷哪个包？

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#643]
大佬你好 我有个M302A盒子  是S905L2B 请问我应该刷哪个包？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/pull/615

看看这个和你的一样不一样

**Comment by 84864797** [comment]
我百度了下 有些302A用的S905L3    有些302A好像是用的S905L2B   不知道能否通用这个dtb?

**Comment by ophub** [comment]
你试试吧，可能你是第一个测试者

**Comment by 84864797** [comment]
还有一个问题 大佬我还有一个E900V22C盒子  WIFI无法驱动  芯片是5621DS

**Comment by ophub** [comment]
主线内核里目前没有这个芯片的驱动，安卓的不能用在主线里

**Comment by 84864797** [comment]
M302A的WIFI是8822CS 有驱动吗？

**Comment by ophub** [comment]
添加了第三方的驱动，但有些人反馈可以用，有些反馈不可以。

**Comment by janko888** [comment]
> M302A的WIFI是8822CS 有驱动吗？

应该是支持的，我m302a是这个芯片，默认是可以用wifi

**Comment by 84864797** [comment]
大佬你好 M302A盒子 是S905L2B 用DTB： meson-gxl-s905l2-x7-5g.dtb  能进去 但是网卡和WIFI都不能驱动

**Comment by ophub** [comment]
meson-gxl-s905l3b-m302a.dtb

**Comment by 84864797** [comment]
大佬你好 系统能进去 但是无法驱动8822cs wifi  求问下 怎么安装8822CS的驱动

**Comment by ophub** [comment]
meson-gxl-s905l3b-m302a.dtb有线网卡正常工作吧

**Comment by 84864797** [comment]
没有试验有线网卡  我用了一个USBWIFI 免驱网卡 进行SSH

**Comment by ophub** [comment]
有线网卡不能用，测试不了无线。
8822cs是添加的第三方的，有人可以，有人不行，这个驱动不确定

**Comment by 84864797** [comment]
已试  M302A有线也无法链接 我快哭了  我拿盒子是用于刷klipper 必须用到wifi 。  目前手头2个盒子E900V22C  WIFI芯片5621DS ，这个WiFi 也不能用。M302A  WIFI也无法驱动。哭~~~

**Comment by 84864797** [comment]
手头有个USB转网口拓展坞  没想到插在拓展坞的网口上  有线网络可以用了

**Comment by janko888** [comment]
> 

刷的安卓底包版本是？内核是？
我测试比较稳定的组合是安卓9和5.15.x内核的，有线正常，无线可用
安卓4和6.0.x，有机器可用，比较玄学

**Comment by janko888** [comment]
![2](https://user-images.githubusercontent.com/103774532/197916739-b8843b73-77ce-4c83-9cf0-efe7a17c7183.jpg)
![1](https://user-images.githubusercontent.com/103774532/197916757-e5541cb2-6d01-4316-9a8f-029e80730cef.jpg)
感觉这个代工版本适配性比较好

**Comment by 84864797** [comment]
盒子只带的安卓系统 和在U盘上运行的Armbian也有关系嘛？

**Comment by 84864797** [comment]
> > 
> 
> 刷的安卓底包版本是？内核是？ 我测试比较稳定的组合是安卓9和5.15.x内核的，有线正常，无线可用 安卓4和6.0.x，有机器可用，比较玄学

大佬你的M302A是S905L3B吧？ 我的是S905L2B  这2个MUC 有什么区别嘛？ 可以用同一个DTB?      我5.1 和5.15都试过了

**Comment by janko888** [comment]
> 



> > > 
> > 
> > 
> > 刷的安卓底包版本是？内核是？ 我测试比较稳定的组合是安卓9和5.15.x内核的，有线正常，无线可用 安卓4和6.0.x，有机器可用，比较玄学
> 
> 大佬你的M302A是S905L3B吧？ 我的是S905L2B 这2个MUC 有什么区别嘛？ 可以用同一个DTB? 我5.1 和5.15都试过了

我手头上的302A有l3和l3b两个版本，都可以适用，百度上了解l2b和l3b比较接近吧，与l3a差别有点大，但没有机会测试过。如果你不想刷掉默认的安卓4的话，倒可以试一下5.19.x或6.0.x的内核，看能不能驱动有线网卡。

**Comment by 84864797** [comment]
> 

好的 那哪里找 M302A的 电视盒子 安卓固件呢？ 我刷掉固件看看

**Comment by janko888** [comment]
我手头上的302A有l3和l3b两个版本，都可以适用，百度上了解l2b和l3b比较接近吧，与l3a差别有点大，但没有机会测试过。如果你不想刷掉默认的安卓4的话，倒可以试一下5.19.x或6.0.x的内核，看能不能驱动有线网卡。

> > 
> 
> 好的 那哪里找 M302A的 电视盒子 安卓固件呢？ 我刷掉固件看看

不知道哪里找的话，感觉你对线刷那些不太熟悉哦，有刷砖的风险，请谨慎。
znds论坛有很多，一般s905l3\s905l3b的都可以试一下，m304A等其它的也可以试试。类似下面这种：
https://github.com/ophub/amlogic-s9xxx-armbian/issues/643#issuecomment-1291444024

**Comment by janko888** [comment]
发错连接
https://www.znds.com/tv-1215994-1-1.html

**Comment by 84864797** [comment]
> 发错连接 https://www.znds.com/tv-1215994-1-1
大佬 你的S905L3B 的电视盒子估计按 分享下呀  刷了很多固件  限制太大 各种密码  USB启动都不能

**Comment by 84864797** [comment]
![QQ截图20221026215018](https://user-images.githubusercontent.com/104506675/198044230-506ec3a4-6e61-4841-9c9f-15fb1e50a3f8.png)
他获得的IP 有点奇怪  好像不会自动获得IP

**Comment by janko888** [comment]
> > 发错连接 https://www.znds.com/tv-1215994-1-1
> > 大佬 你的S905L3B 的电视盒子估计按 分享下呀  刷了很多固件  限制太大 各种密码  USB启动都不能

年代久远，不太记得了，随便找了之前开过个帖子里的网盘吧
https://pan.baidu.com/s/1pgO5X_8FQOwg2ili3MXntQ 提取码：w8hk

安卓9的大部分是基于atv修改的，没有什么设置密码，安卓4多基于运营商的原版改，密码一般是10086之类。

**Comment by 84864797** [comment]
大佬 我在网上找到一篇文章  E900V22E 芯片同样是S905L2B 刷armbian 用的是你的固件  用的meson-gxl-s905l2-x7-5g.dtb
 网口一样不用驱动，他替换了一个文件 网卡就能驱动了  。
但是他的文章上没有提供这个文件。
![1](https://user-images.githubusercontent.com/104506675/198482091-0327b075-8e96-4bd8-9712-888d6ac98fa5.png)
![2](https://user-images.githubusercontent.com/104506675/198482128-9db39827-95fb-49bb-bd77-0e87cb6b831d.png)

文章地址：https://www.cnblogs.com/unixcs/p/16685265.html

**Comment by 84864797** [comment]
哈哈哈 驱动起来了  网口驱动起来了  最少网口能用了  
Armbian_22.11.0_Aml_s905x_bullseye_5.10.150_server_2022.10.27.img.gz
dtb:meson-gxl-s905l2-x7-5g.dtb
芯片S902L2B
电视盒子：E900V22E   M302A(S905L2-B)  S905L2-B的都可以用这个固件 和DTB  最少网口能用

**Comment by janko888** [comment]
> 哈哈哈 驱动起来了 网口驱动起来了 最少网口能用了 Armbian_22.11.0_Aml_s905x_bullseye_5.10.150_server_2022.10.27.img.gz dtb:meson-gxl-s905l2-x7-5g.dtb 芯片S905L2B 电视盒子：E900V22E M302A(S905L2-B) S905L2-B的都可以用这个固件 和DTB 最少网口能用

能用就好，他这个应该是提取了bootloader这些自己定制了一个uboot,可以无视安卓底包的差异的吧

**Comment by 84864797** [comment]
> > 哈哈哈 驱动起来了 网口驱动起来了 最少网口能用了 Armbian_22.11.0_Aml_s905x_bullseye_5.10.150_server_2022.10.27.img.gz dtb:meson-gxl-s905l2-x7-5g.dtb 芯片S905L2B 电视盒子：E900V22E M302A(S905L2-B) S905L2-B的都可以用这个固件 和DTB 最少网口能用
> 
> 能用就好，他这个应该是提取了bootloader这些自己定制了一个uboot,可以无视安卓底包的差异的吧

不需要改了uboot    直接刷固件 就可以用了网口了  只有S905X ，内核5.10的可以驱动网口。5.15的不能驱动网口。
DTB:meson-gxl-s905l2-x7-5g.dtb和meson-gxl-s905l3b-m302a.dtb 都能用。

现在的问题是怎么加载8822CS WiFi驱动， 这个驱动大佬说 是有的

**Comment by ophub** [comment]
5.15内核比5.10少一个u-boot，你复制一个重启测试一下

**Comment by CangWeiohh** [comment]
> > > 哈哈哈 驱动起来了 网口驱动起来了 最少网口能用了 Armbian_22.11.0_Aml_s905x_bullseye_5.10.150_server_2022.10.27.img.gz dtb:meson-gxl-s905l2-x7-5g.dtb 芯片S905L2B 电视盒子：E900V22E M302A(S905L2-B) S905L2-B的都可以用这个固件 和DTB 最少网口能用
> > 
> > 
> > 能用就好，他这个应该是提取了bootloader这些自己定制了一个uboot,可以无视安卓底包的差异的吧
> 
> 不需要改了uboot 直接刷固件 就可以用了网口了 只有S905X ，内核5.10的可以驱动网口。5.15的不能驱动网口。 DTB:meson-gxl-s905l2-x7-5g.dtb和meson-gxl-s905l3b-m302a.dtb 都能用。
> 
> 现在的问题是怎么加载8822CS WiFi驱动， 这个驱动大佬说 是有的

您好，我有个M302A-ZN-S905L2-B的移动魔百和，想刷Armbian，能教教我吗大佬？

**Comment by neostfox** [comment]
> ![2](https://user-images.githubusercontent.com/103774532/197916739-b8843b73-77ce-4c83-9cf0-efe7a17c7183.jpg) ![1](https://user-images.githubusercontent.com/103774532/197916757-e5541cb2-6d01-4316-9a8f-029e80730cef.jpg) 感觉这个代工版本适配性比较好

同款盒子，现在还没找到用哪个包

**Comment by guanhangl** [comment]
> 大佬你好 我有个M302A盒子 是S905L2B 请问我应该刷哪个包？

求教具体应该刷入那个包？没太看懂
