### ISSUE TITLE
COMPILE FUNCTIONAL QZ VERSION FOR TX3-H

### ISSUE THREAD

**Issue by deadxd** [ophub/amlogic-s9xxx-armbian#644]
**Describe the bug**
I'm seeing a lot of people with internet problems with the tanix tx3 I'm also having the same problem it's not very clear that the Bz version is for Model: TX3 and the QZ version is for the TX3-H model and that's where the problem is everyone booting with the Bz version with the model: TX3-H and with that it is not possible to obtain an IP with the cable because when we try to boot with the QZ version the bootloader does not load
I don't know why I can't get into the bootloader with the QZ version for TX3-H which would be the correct version and I ask you to compile a working Qz version for TX3-H to get IP I spent more than 12 hours working on it no configuration network worked only when I opened my box I realized that the correct version was QZ.

**Screenshots**
![noip](https://user-images.githubusercontent.com/20803862/197564013-e3e4ec40-cdee-43b8-88fa-14aafeb1fc14.jpg)
![TX3-H](https://user-images.githubusercontent.com/20803862/197564042-6fcb6313-e04f-4c8a-8e7e-d3a7fba6243e.jpg)

**Armbian Version**
 - Kernel Version: [e.g. 5.15.74]
 - Release: [e.g. jammy]
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: [e.g. S095x3]
 - Brand: [e.g. Tanix]
 - Model [e.g. TX3-H]

**Comment by deadxd** [comment]
more pictures showing infinite screen with (meson-sm1-tx3-qz.dtb) and (meson-sm1-tx3-qz-oc.dtb) which should be the correct version for TX3-H which is different from the version MODEL: TX3 = (meson-sm1-tx3-bz.dtb) and (meson-sm1-tx3-bz-oc.dtb) 
![INFINITELOAD](https://user-images.githubusercontent.com/20803862/197572728-8f8a4eed-cdea-4e2d-967e-f65b30513a57.jpg)

and photo of the network card

![fronttx3-h](https://user-images.githubusercontent.com/20803862/197572804-66040735-f82c-4355-bd7d-33239c67e1e0.jpg)

**Comment by ProSteel666PT** [comment]
I have a TX3-H.
I have the same problem and my box is 4G ram and 2G Ram appears.

There is no IP.
![imagem](https://user-images.githubusercontent.com/71602361/197631158-4cd62f4a-f546-46db-a349-d2608cdbf8c7.png)
![imagem](https://user-images.githubusercontent.com/71602361/197631203-bc4cadd2-61a3-447f-a1f4-5f8a70a4486b.png)


This image with an older version of armbian.
![390adf6ca6d028e3c7eda994ed2608e640b428f3](https://user-images.githubusercontent.com/71602361/197630276-18d4a1c3-65da-46c9-95e7-169b6913ece4.png)

It has the latest version.
![1c7fedcf989208d32fb335febe42fd08f6d9855f_2_640x360](https://user-images.githubusercontent.com/71602361/197630788-fae9b768-2d08-4dff-a404-c87b36ef2343.jpeg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#1212-memory-size-recognition-error

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md

512-515

**Comment by deadxd** [comment]
thanks for the memory solution but I still can't boot with version 512-513 on my Tx3-H 1GB

**Comment by ProSteel666PT** [comment]
Thanks  but I still can't boot with version 512-513 on my Tx3-H 4GB ram +64GB rom

**Comment by ProSteel666PT** [comment]
Thanks but I still can't boot with version 512-513 on my Tx3-H 4GB ram + 64GB rom

**Comment by ophub** [comment]
![Snip20221025_3](https://user-images.githubusercontent.com/68696949/197737555-b4b6c417-1630-4cfb-b68c-4de4c2685b83.png)

**Comment by deadxd** [comment]
thanks again, where can i download this img Armbian 22.10.0-trunk jammy with Linux 5.10.149-ophub ? could you give me the link

**Comment by deadxd** [comment]
no need, thanks to be able to boot with the QZ version with the one you passed 
4gb, wifi, ip work 100%

**Comment by deadxd** [comment]
I have a problem again after the ARMBIAN-INSTALL it installed everything right but after turning on the tv box it is in infinite screen "TX3" any solution?

**Comment by ophub** [comment]
`armbian-install yes`

**Comment by deadxd** [comment]
I made it, at boot my memory says 116 instead of 64gb
![armbian4gb](https://user-images.githubusercontent.com/20803862/197773598-22d51b83-a780-45a7-84b2-5f595bcd75b5.jpg)

and after I use the armbian-install command and remove the pen-drive it doesn't load
![afterarmbian-install](https://user-images.githubusercontent.com/20803862/197773871-6beb4a2b-1738-4ae0-a8d6-e2a3e6f4031e.jpg)

**Comment by ophub** [comment]
116 is the space size of the usb you plugged in.
`armbian-install yes`

**Comment by ProSteel666PT** [comment]
Thank you my friend!
![imagem](https://user-images.githubusercontent.com/71602361/197839962-cc2d48aa-72c8-421a-87c9-f1246da0fb1f.png)

**Comment by h3ld3rkid** [comment]
someone have a new tutorial please?

**Comment by cikezlf** [comment]
[Armbian_jammy_save_2025.03](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2025.03)使用目前最新的版本u盘可以启动一切正常，使用armbian-install刷进emmc，无法启动黑屏

**Comment by Doudun6** [comment]
> [Armbian_jammy_save_2025.03](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_save_2025.03)使用目前最新的版本u盘可以启动一切正常，使用armbian-install刷进emmc，无法启动黑屏

Any progress with that, I got the same issue. I used this version: 25.05.0_amlogic_s905x3_noble_6.12.21_server_2025.04.01
有后续吗？我遇到了同样的问题。
