### ISSUE TITLE
你好，请问 s905x3 和 s905x3-b 有什么区别？

### ISSUE THREAD

**Issue by hxulin** [ophub/amlogic-s9xxx-armbian#646]
你好，请问 s905x3 和 s905x3-b 有什么区别？

**HK1-Box** 的盒子应该使用哪一个固件：

- Armbian_22.11.0_Aml_s905x3_bullseye_5.10.149_server_2022.10.20.img.gz
- Armbian_22.11.0_Aml_s905x3_bullseye_5.15.74_server_2022.10.20.img.gz
- Armbian_22.11.0_Aml_s905x3-b_bullseye_5.10.149_server_2022.10.20.img.gz
- Armbian_22.11.0_Aml_s905x3-b_bullseye_5.15.74_server_2022.10.20.img.gz

**Comment by ophub** [comment]
HK1是s905x3

s905x3-b是腾讯极光盒子的SOC
