### ISSUE TITLE
ssh Connection refused

### ISSUE THREAD

**Issue by MDCY9008** [ophub/amlogic-s9xxx-armbian#647]
![image](https://user-images.githubusercontent.com/54255527/197711855-6a7c5c09-3a74-48c8-936f-caf68181d5dd.png)

Armbian_22.11.0_Aml_s905l3a_jammy_5.15.74_server_2022.10.21

**Comment by MDCY9008** [comment]
![image](https://user-images.githubusercontent.com/54255527/197715978-41bdeaa7-ed51-4529-b87c-7124fce40317.png)

把这三行注释了，问题没了。

**Comment by ophub** [comment]
上周我装了一个tx3(s905x3)和rock5b(rk3588)都出现了 错误提示：Failed to start OpenBSD Secure Shell server. 新固件重启安装时ssh服务就停了。我查询了下解决方法新添加的，过几天测试这个问题没有了，就可以注销掉。


https://github.com/ophub/amlogic-s9xxx-armbian/issues/638

**Comment by MDCY9008** [comment]
> 上周我装了一个tx3(s905x3)和rock5b(rk3588)都出现了 错误提示：Failed to start OpenBSD Secure Shell server. 新固件重启安装时ssh服务就停了。我查询了下解决方法新添加的，过几天测试这个问题没有了，就可以注销掉。我目前在用的几个系统里都添加了这个代码，目前我测试重启也ssh访问正常。
> 
> #638
> 
> ![Snip20221025_2](https://user-images.githubusercontent.com/68696949/197732303-1baa2b66-e110-4afc-a6ef-f06218b97fc9.png)
> 
> ![Snip20221025_1](https://user-images.githubusercontent.com/68696949/197732280-2cd6948f-5d75-430d-9f63-8cf926440985.png)

![image](https://user-images.githubusercontent.com/54255527/198862289-e8e8180d-5855-4e7e-bd36-35eaf0ffd67c.png)
去掉了custom.sh的那三行，最新版，ssh正常的

**Comment by ophub** [comment]
好的，一会更新注释掉

**Comment by 9runner** [comment]
老大，这个问题似乎依然存在。

我是在一台M401A上，按xcray的“u200主线 + e900v22c过载 + u200的dtb”方法写入emmc后的系统。习惯性修改ssh的端口并禁用root登录，然后发现重启后ssh就不正常了。一轮翻查，结果是ssh的状态如下：

root@HassOS-248:~# systemctl status ssh
● ssh.service - OpenBSD Secure Shell server
     Loaded: loaded (/lib/systemd/system/ssh.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-11-25 12:21:47 CST; 1min 9s ago
       Docs: man:sshd(8)
             man:sshd_config(5)
    Process: 14064 ExecStartPre=/usr/sbin/sshd -t (code=exited, status=0/SUCCESS)
   Main PID: 14065 (sshd)
      Tasks: 1 (limit: 825)
     Memory: 2.3M
     CGroup: /system.slice/ssh.service
             └─14065 sshd: /usr/sbin/sshd -D [listener] 0 of 10-100 startups

Nov 25 12:21:47 HassOS-248 systemd[1]: Starting OpenBSD Secure Shell server...
Nov 25 12:21:47 HassOS-248 sshd[14065]: Server listening on 0.0.0.0 port 8787.
Nov 25 12:21:47 HassOS-248 sshd[14065]: Server listening on :: port 8787.
Nov 25 12:21:47 HassOS-248 systemd[1]: Started OpenBSD Secure Shell server.
Nov 25 12:22:15 HassOS-248 sshd[14072]: Accepted password for root from 192.168.88.8 port 52026 ssh2
Nov 25 12:22:15 HassOS-248 sshd[14072]: pam_unix(sshd:session): session opened for user root(uid=0) by (uid=0)
Nov 25 12:22:29 HassOS-248 sshd[14287]: fatal: Missing privilege separation directory: /run/sshd


感觉与这个issue是一回事？系统依然会莫名其妙地删除/run/sshd？

目前我的解决方法是在rc.local中添加ssh的重启命令。

**Comment by ophub** [comment]
你是用的最新的固件吗？

**Comment by 9runner** [comment]
> 你是用的最新的固件吗？

是的，最新的5.15.79，bullseye。

**Comment by ophub** [comment]
我重新打开这个默认重启SSH服务了
