### ISSUE TITLE
hk1box：上网或听音乐时经常死机

### ISSUE THREAD

**Issue by skyshore2001** [ophub/amlogic-s9xxx-armbian#649]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
手上两台新购买的hk1box，S905x3, 4G/32G，刷入系统为armbian/debian版本(bullseye_5.15.74_server)，用apt安装了xfce4桌面和firefox浏览器，使用hdmi接安卓电视当显示器。
试过用mpv或kodi听音乐(m4a/mp3格式)，会不定期死机（有时听几十分钟，有时几分钟，时间不定），画面停留不动，没有任何输出，鼠标键盘无效，局域网里ping没有反应更无法ssh上去。
另一种死机更快，用firefox上阿里云网站，购买esc主机网页，选一选很快就死机，现象和听音乐死机一样。

**To Reproduce**

用firefox-esr打开阿里云购买esc主机的网站（aliyun.com先登录，购买地址是 https://ecs-buy.aliyun.com/wizard/?accounttraceid=4f15099b5fb342218309a215a59059d4bkle#/prepay/cn-beijing ），网页中的下拉框各点选一下，操作一会后大概率突然死机不动，只能拨电源重启。

**Expected behavior**
稳定运行不死机。

**Screenshots**

**Armbian Version**
 - Kernel Version: 5.15.100
 - Release: bullseye (之前也装过jammy，存在听音乐死机的情况)
 - Edition: server，但用apt安装了xfce4桌面。

**Device (please complete the following information):**
 - SOC: S095x3
 - Brand: hk1box 4G,32G
 - Model: hk1box 4G,32G

**Additional context**

**Comment by skyshore2001** [comment]
补充：死机前温度并不高（小于60度），可以排除是CPU过热的问题。
这个现象没见过，不知道怎么分析，问问大佬怎样分析这个问题，可能是哪些问题？

**Comment by ophub** [comment]
你听的什么歌曲，是那种`咚呲哒呲咚呲哒呲`的还是`甜蜜蜜`那种？

**Comment by skyshore2001** [comment]
听的歌有闹的有静的，音乐是m4a或mp3格式，纯音频不带视频。
图形界面下看不到报错，这张图是背景开着音乐上网(mpv放音乐，firefox上网)，然后死机卡住的画面，只开音乐cpu温度在50度以内，上网的话温度有上升到近70度，阿里云的网站访问尤其很慢，cpu高负载：
![7f48ea2bce85ee6fd7ea0c461e6672c](https://user-images.githubusercontent.com/16953567/198045724-c866290e-edb5-42bf-9c91-843bc1e2723f.jpg)

这张是只开音乐然后突然死机的图：
![d7924970c8edf29d678e7bd72a0a0a9](https://user-images.githubusercontent.com/16953567/198045975-81d9f94f-3a7d-4941-8565-6c32137ed766.jpg)

为了避免图形界面的影响，我退出xfce桌面，只在字符界面里听音乐（仍然是用mpv只放音乐，找了一个1小时多的演唱会录音来测试），其它什么事也没有操作，48分钟后死机：

![6f8a41153b576c93ab88eeb64ff459b](https://user-images.githubusercontent.com/16953567/198045187-14e3e829-8405-4905-a803-60e0e859c5d3.jpg)

死机后约1-2分钟，出现一些日志，我的字调的比较大，只能看到最后一页了：
![444227fd5547b43f0a9543cdf9f3ae7](https://user-images.githubusercontent.com/16953567/198045624-fa2bff94-0495-48f6-a707-a3859a5f961e.jpg)

**Comment by xcray** [comment]
应该是dtb的锅，我之前在m401a上用别的dtb经常能看到这种死机出错，后来换成u200的dtb就再也没出过问题。
cpu频率激进、电压不够高、频率调度策略激进、其它部件如内存emmc等速率太高等等，都有可能。

盒子这东西稳定是首位，有些dtb/设置/教程片面的追求性能甚至还有人玩超频，有点没必要

**Comment by ophub** [comment]
`cat /etc/ophub-release`
看一下
