### ISSUE TITLE
无法写入EMMC

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#650]
Armbian_22.11.0_Aml_s905x2-km3_jammy_5.15.75_server_2022.10.27

meson-gxl-s905l3b-m302a.dtb

![1Y Q8A1%%MPQ4I(Z}PLYMWI](https://user-images.githubusercontent.com/104506675/198257859-bacb4015-dbbd-4eb5-b5ad-1f1c9dba65ee.png)

**Comment by ophub** [comment]
你是什么盒子？emmc不让写入数据。

**Comment by 84864797** [comment]
> 你是什么盒子？emmc不让写入数据。

M302A  但是 是S905L2B   不是S905L3B

**Comment by ophub** [comment]
以后只问名字也不准确了，同名不同芯，这交流起来都费劲。
emmc不让写入，你试过用晶晨刷机工具刷其他版本的安卓系统？

**Comment by 84864797** [comment]
> 以后只问名字也不准确了，同名不同芯，这交流起来都费劲。 emmc不让写入，你试过用晶晨刷机工具刷其他版本的安卓系统吗？是不是没root，没开启usb调试模式？
> 
> 看看12.4
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

是啊 刷了几个安卓系统   目前刷了一个S905L3B的安卓固件  好像砖了  现在在重新刷固件

**Comment by ophub** [comment]
尽量刷S905L2B能用的，如果网上固件没有明确说明可以通刷的尽量别刷，有些会砖
