### ISSUE TITLE
X96 mini 1G 8G WIFI无法驱动

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#651]
s905w

Armbian_22.11.0_Aml_s905w_jammy_5.15.75_server_2022.10.27

meson-gxl-s905w-x96-mini.dtb

wifi芯片SSV6051

WIFI无法驱动

**Comment by ophub** [comment]
以前试过，没驱动起来，在ROCKCHIP RK3X28 & RK322X里可以使用
