### ISSUE TITLE
armbian-software 安装docker时：sudo: /etc/sudo.conf is owned by uid 1023, should be 0

### ISSUE THREAD

**Issue by Edwardyx** [ophub/amlogic-s9xxx-armbian#652]
**感谢大佬帮忙，终于在刷了3个小时后，成功救砖了。**
重新刷了armbian，在装docker时提示如图，我已经是root账户安装了。结果还是不行
![Snipaste_2022-10-28_00-57-01](https://user-images.githubusercontent.com/63174337/198352754-b110c9d6-0987-4ca9-b7bd-3a89892e1b99.png)

然后用了[linux解决“XXX is not in the sudoers file”错误](https://blog.csdn.net/lydong_/article/details/79812693)
中的方法二，依然不行。
![Snipaste_2022-10-28_01-00-06](https://user-images.githubusercontent.com/63174337/198353329-4d9c940d-6e23-4b09-a6b6-fc3dcf1526a6.png)

**Comment by ophub** [comment]
`armbian-fix`

执行一下

**Comment by Edwardyx** [comment]
我执行了但还是这样

![Snipaste_2022-10-28_18-24-37](https://user-images.githubusercontent.com/63174337/198565715-a656d4cf-b6ba-4aef-83e2-e629ef1b39f6.png)

**Comment by ophub** [comment]
下载今天的固件试试

**Comment by Edwardyx** [comment]
。。。又要短接，线刷atv，再刷armbian？大佬能不能在armbian里面加一个默认如果有引导U盘就从U盘启动。。。我砖了一次，短接线刷已经被搞怕了。

**Comment by Edwardyx** [comment]
有没有可能是我换了清华源造成的？

**Comment by sesame-foxes** [comment]
chown root:root /mnt -R
chown root:root /etc -R
chown root:root /usr -R
chown man:root /var/cache/man -R
chmod g+s /var/cache/man -R

权限问题，修改一下就好，我通常是用这几句

**Comment by Landy173** [comment]
> 这个不需要短接，又没砖，你USB重新刷今天的固件启动，再写入emmc即可。

大神，我的M401A已经刷入了您的armbian，现在想重装恢复到系统初始状态，新镜像写入U盘后，怎么启动U盘里的armbian?我试过插入U盘后断电重新通电，结果 并没有从U盘启动。

**Comment by ophub** [comment]
还原安卓系统后，如何从安卓系统启动u盘的armbian可以查看说明文档

**Comment by iJayscn** [comment]
> chmod g+s /var/cache/man -R

实测有效，感谢！
