### ISSUE TITLE
rebuild script fails to preserve original image's permissions

### ISSUE THREAD

**Issue by thumsl** [ophub/amlogic-s9xxx-armbian#653]
this bug has been reported a few times before,  #356 and #22 for example

I believe the root cause is the rebuild script. I have a modified Armbian image, and I can check by mounting it that the permissions are correct before running the script however the resulting image is different

not sure how this is happening as rootfs files are moved and not copied

I think it might have something to do with the permissions of the root directory?

Opening this so we can discuss it, doing some tests right now

**Comment by thumsl** [comment]
![image](https://user-images.githubusercontent.com/4841803/198417255-b352b8a0-00cb-474c-8727-f7f5c11d69eb.png)

I'm not sure how this is possible, but after the move permissions are messed up already

**Comment by thumsl** [comment]
I can confirm, running the rebuild script again in a different location maintains the correct permissions and ownership information.

`ls -l` of the my clones of amlogic-s9xxx-armbian:
`drwxrwxrwx 1 root root  `     -   creates image with incorrect permissions
`drwxrwxr-x 7 myuser myuser`  - creates image with correct permissions

Not sure if there's something that can be changed in the script to fix this.  If you think that this isn't a bug with the script please close this issue @ophub 

Thanks!

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/f68056e79c0fe56f3c5574465912d232331f406f

```
cp --help
-p    same as --preserve=mode,ownership,timestamps
-a = -pdr
```
According to your prompt, I checked the `cp` command parameters, you can use the `-p` parameter to retain the permissions of the original file.
Now I adjusted it to `cp -af`, you can check whether the permissions of the files after this processing are correct

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/adc580ee52634ac1547759119e5c729dd555fa9c

I adjusted the image creation process, and directly used `cp -af` to retain the permissions to copy the original image files to the newly created image, and other file modifications were directly completed in the new image, which reduced the problem of permission changes that may be caused by the two copying and moving of files. .

You can then compare whether the permissions are retained correctly.

**Comment by thumsl** [comment]
> [adc580e](https://github.com/ophub/amlogic-s9xxx-armbian/commit/adc580ee52634ac1547759119e5c729dd555fa9c)
> 
> I adjusted the image creation process, and directly used `cp -af` to retain the permissions to copy the original image files to the newly created image, and other file modifications were directly completed in the new image, which reduced the problem of permission changes that may be caused by the two copying and moving of files. .
> 
> You can then compare whether the permissions are retained correctly.

I saw, thank you! I can probably test it tomorrow, I still have the scripts setup in the a dir where it used to fail, I'll try running it again there with the updates

**Comment by ophub** [comment]
Ok, thanks for finding and reporting the issue, it's an important improvement.
