### ISSUE TITLE
电视盒子M302A  S905L2B 现在网口可以用了 WIFI无法驱动

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#654]
电视盒子M302A  S905L2B  +WIFI芯片8822CS

固件：
Armbian_22.11.0_Aml_s905x_bullseye_5.10.150_server_2022.10.27.img.gz   
DTB:
meson-gxl-s905l2-x7-5g.dtb
meson-gxl-s905l3b-m302a.dtb 
都可以驱动网口，都不能驱动WIFI驱动

现在 直接刷S905X-5.10的固件 就可以用了网口了 只有内核5.10的可以驱动网口。5.15的不能驱动网口。

大佬，现在的问题是怎么加载8822CS WiFi驱动

**Comment by ophub** [comment]
8822CS 尝试过，只有少部分用户反馈可使用。也有很多用户反馈不可用。暂时没有稳定的驱动。

**Comment by 84864797** [comment]
大佬 有没有办法手动加载啊  或者 自己安装 网上好多自己编译wifi驱动
