### ISSUE TITLE
私家云2代(s905x) 可正常安装启动，wifi 蓝牙和外接USB正常

### ISSUE THREAD

**Issue by shouduzhanshi** [ophub/amlogic-s9xxx-armbian#655]
感谢大佬们为大家提供了干净的，开箱即用的系统。

s905x 
可正常安装启动，wifi 蓝牙 ,外接USB正常

已知问题:
1. 网口灯不亮。
2. led屏无法显示。

**Comment by ophub** [comment]
这个产品的链接发一个。
你用的什么组合，dtb和u-boot是哪个？
在usb上测试的还是写入emmc了？

**Comment by zhouyiamor** [comment]
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bookworm'
MODEL_ID='0'
MODEL_NAME='HG680P'
SOC='s905x'
FDTFILE='meson-gxl-s905x-khadas-vim.dtb'
FAMILY='meson-gxl'
BOARD='s905x'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='dev'
KERNEL_VERSION='6.1.49'
KERNEL_BACKUP='yes'
GITHUB_CDN=''
BOOT_CONF='extlinux.conf'
ROOTFS_TYPE='ext4'
DISK_TYPE='emmc'
AMPART_STATUS='yes'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/s905x-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/s905x-bootloader.img'
UBOOT_OVERLOAD='u-boot-s905x-s912.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='rapdodge'
BUILDER_NAME='angel'
PACKAGED_DATE='2023-08-28'

**Comment by ophub** [comment]
好的，多谢分享

**Comment by hanlihanshaobo** [comment]
> 好的，多谢分享

希望大佬在更新下，目前还是屏幕盒网卡灯不能正常驱动

**Comment by hanlihanshaobo** [comment]
> 好的，多谢分享

大佬可以参考下这个https://github.com/mofeng-git/One-KVM/releases 项目，作者适配了风扇、LED指示灯和显示屏，做一个该机型的专门固件，他这个固件目前拔掉网线后网卡灯会常亮
