### ISSUE TITLE
随机MAC不生效，MAC仍然为安卓系统的

### ISSUE THREAD

**Issue by MDCY9008** [ophub/amlogic-s9xxx-armbian#656]
![image](https://user-images.githubusercontent.com/54255527/198862621-00134c9d-5e13-467b-9dc5-19c412fa4aea.png)
执行armbian-install后，已经正常将MAC写入并编译为boot.scr，但未生效，仍然为安卓系统的MAC。

**Comment by MDCY9008** [comment]
个人猜测是在进入U盘系统时，NetworkManager已将MAC信息写入了配置文件。

**Comment by ophub** [comment]
我也发现没生效。

/etc/network/interfaces 这里指定可以生效。
```
auto eth0
iface eth0 inet dhcp
        hwaddress ether 12:34:56:78:9A:BC
```

**Comment by MDCY9008** [comment]
> 我也发现没生效。
> 
> /etc/network/interfaces 这里指定可以生效。
> 
> ```
> auto eth0
> iface eth0 inet dhcp
>         hwaddress ether 12:34:56:78:9A:BC
> ```
> 
> 现在的设置是前些天改的，有人不喜欢自定义MAC，必须要安卓原厂的。

阿这。。。顺便提个小建议吧
![image](https://user-images.githubusercontent.com/54255527/198866391-62318fb6-9eb7-4e36-bdb4-1b3a247ec9b6.png)
如果系统默认启动了networkmanager还是把network的配置文件保持默认状态比较合理，这样开机的时候不会冲突，出现双IP掉线的情况。

**Comment by ophub** [comment]
你测试好了pr一下修改方案吧。

**Comment by MDCY9008** [comment]
> 你测试好了pr一下修改方案吧。

所以MAC怎么搞，还需要随机吗，如果默认用NetworkManager设置随机MAC比较麻烦需要更换方法，如果要原来的方法就不用修改我注释的这些，rebuild的时候把networkmanager disable掉就行。

**Comment by livelier** [comment]
@ophub @MDCY9008 没有生效的 `MAC`，内核版本都是 5.15.y 吗？

**Comment by livelier** [comment]
@ophub @MDCY9008 没有生效的 `MAC`，内核版本都是 5.15.y 吗？或者说，是怎样操作后，`MAC` 没有生效。

例如：
使用安卓 `bootloader`，没有使用主线u-boot。
使用usb或sd卡，没有写入emmc。
...

在 `boot.csr` 中修改 `MAC` 是我提出的，目的解决某些人，在某种环境下，仅适用 `NetworkManager` 需要所谓的 `Permanent MAC`，而不是 `clone MAC` 的需求。

**Comment by livelier** [comment]
@ophub @MDCY9008 没有生效的 `MAC`，内核版本都是 `5.15.y` 吗？或者说，是怎样操作后，`MAC` 没有生效。

例如：
使用安卓 `bootloader`，没有使用主线 `u-boot`。
使用 `usb` 或 `sd` 卡，没有写入 `emmc`。
...

在 `boot.csr` 中修改 `MAC` 是我提出的，目的解决某些人，在某种环境下，仅使用 `NetworkManager` 需要所谓的 `Permanent MAC`，而不是 `clone MAC` 的需求。

**Comment by MDCY9008** [comment]
> @ophub @MDCY9008 没有生效的 `MAC`，内核版本都是 5.15.y 吗？或者说，是怎样操作后，`MAC` 没有生效。
> 
> 例如： 使用安卓 `bootloader`，没有使用主线u-boot。 使用usb或sd卡，没有写入emmc。 ...
> 
> 在 `boot.csr` 中修改 `MAC` 是我提出的，目的解决某些人，在某种环境下，仅使用 `NetworkManager` 需要所谓的 `Permanent MAC`，而不是 `clone MAC` 的需求。

内核5.15 安卓uboot u盘写入进emmc。

**Comment by livelier** [comment]
写入 `emmc` 后的 `boot.cmd` 如下内如：
```
				setenv bootargs ${bootargs} mac=${mac}
			elif printenv eth_mac; then
				setenv bootargs ${bootargs} mac=${eth_mac}
			elif printenv ethaddr; then
				setenv bootargs ${bootargs} mac=${ethaddr}
```
修改为：
```
				setenv bootargs ${bootargs} mac=${ethaddr}
			elif printenv eth_mac; then
				setenv bootargs ${bootargs} mac=${ethaddr}
			elif printenv ethaddr; then
				setenv bootargs ${bootargs} mac=${ethaddr}
```
然后，重新 `mkimage` 尝试一下。

**Comment by ophub** [comment]
我在n1(s905d)，tx3(s905x3)上都是写入emmc使用的，用的安卓的bootloader ，在usb上启动时我看到的MAC地址也是原厂的。

因为最近测试脚本时刷过几次系统都发现这个boot.cmd的mac无效，所以前天在调整rebuild的时候，把之前在里面添加的在boot.cmd里自定义mac的脚本也先删除了，安装脚本armbian-install里还保留了，但是测试boot.cmd的设定无效。

**Comment by livelier** [comment]
分析了一下没有生效的大体原因。

使用安卓 `bootloader` 时，读取自安卓 `bootloader` 的 `env` 中的 `mac` 或 `eth_mac` 而没有读取 `ethaddr`。而安卓 `env` 中的 `mac` 或 `eth_mac` 被赋予的 `mac` 值是安卓系统默认的 `mac` 。

所以，修改 `env` 中 `mac` `eth_mac` `ethaddr` 这三个，都需要被赋予相同的 `mac` 值。应该可以解决，使用安卓bootloader 或 主线u-boot 没有生效的问题。

**Comment by livelier** [comment]
分析了一下没有生效的大体原因。

安卓 `bootloader` 和主线 `u-boot` 存储 `env` 的偏移量位置不同，读取的逻辑也不同。 

使用安卓 `bootloader` 时，读取自安卓 `bootloader` 的 `env` 中的 `mac` 或 `eth_mac` 而没有读取 `ethaddr`。而安卓 `env` 中的 `mac` 或 `eth_mac` 被赋予的 `mac` 值是安卓系统默认的 `mac` 。

所以，修改 `env` 中 `mac` `eth_mac` `ethaddr` 这三个，都被赋予相同的 `mac` 值时。应该可以解决，使用安卓bootloader 或 主线u-boot 没有生效的问题。

**Comment by livelier** [comment]
分析了一下没有生效的大体原因。

安卓 `bootloader` 和主线 `u-boot` 存储 `env` 的偏移量位置不同，读取的逻辑也不同。 

使用安卓 `bootloader` 时，读取自安卓 `bootloader` 的 `env` 中的 `mac` 或 `eth_mac` 而没有读取 `ethaddr`。而安卓 `env` 中的 `mac` 或 `eth_mac` 被赋予的 `MAC address` 值是安卓系统默认的。

所以，修改 `env` 中 `mac` `eth_mac` `ethaddr` 这三个，都被赋予相同的 `MAC address` 时。应该可以解决，使用安卓 `bootloader` 或 主线 `u-boot` 没有生效的问题。

**Comment by ophub** [comment]
/etc/network/interfaces 这里指定MAC地址可能编缉会更方便一些，注释掉就是安卓原盒子的，启用就是自定义的（可以在文件里默认为#注释了，有需要的自己打开）。这样比mkimage更简单一点。

**Comment by livelier** [comment]
> /etc/network/interfaces 这里指定MAC地址可能编缉会更方便一些，注释掉就是安卓原盒子的，启用就是自定义的（可以在文件里默认为#注释了，有需要的自己打开）。这样比mkimage更简单一点。

是的 o大，这个方式确实方便。但是只有在使用安卓 `bootloader` 时，才会读取到安卓盒子原有 `mac address`，如果使用主线`u-boot`时，`/etc/network/interfaces` 被注释掉，读取到的 `mac address` 并不是安卓盒子原有的。

**Comment by livelier** [comment]
> /etc/network/interfaces 这里指定MAC地址可能编缉会更方便一些，注释掉就是安卓原盒子的，启用就是自定义的（可以在文件里默认为#注释了，有需要的自己打开）。这样比mkimage更简单一点。

是的 o大，这个方式确实方便。但是只有在使用安卓 `bootloader` 时，才会读取到安卓盒子原有 `mac address`，如果使用主线`u-boot`时，`/etc/network/interfaces` 被注释掉，读取到的 `mac address` 并不是安卓盒子原有的。

也没关系了，使用 `NetworkManager` 而注释掉 `/etc/network/interfaces` 时，对 `MAC address` 需要修改的使用 `clone mac` ，
参考 [Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#1277-%E4%BF%AE%E6%94%B9%E4%BB%A5%E5%A4%AA%E7%BD%91%E5%8D%A1-mac-%E5%9C%B0%E5%9D%80) 12.7.7 的方法 。

**Comment by livelier** [comment]
> /etc/network/interfaces 这里指定MAC地址可能编缉会更方便一些，注释掉就是安卓原盒子的，启用就是自定义的（可以在文件里默认为#注释了，有需要的自己打开）。这样比mkimage更简单一点。

是的 o大，这个方式确实方便。但是只有在使用安卓 `bootloader` 时，读取到是安卓盒子原有 `mac address`。
如果使用主线`u-boot`时，且 `/etc/network/interfaces` 被注释掉，读取到的 `mac address` 并不是安卓盒子原有的。

使用 `NetworkManager` 而注释掉 `/etc/network/interfaces` 时，对 `MAC address` 需要修改使用 `clone mac`，
参考 [Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md#1277-%E4%BF%AE%E6%94%B9%E4%BB%A5%E5%A4%AA%E7%BD%91%E5%8D%A1-mac-%E5%9C%B0%E5%9D%80) 12.7.7 的方法 。

“Permanent MAC” 方式修改，使用安卓 bootloader 我抽空再测一下。

**Comment by ophub** [comment]
好的，我先恢复了原来MAC地址的代码，默认注释了，由系统分配。
