### ISSUE TITLE
刷入emmc后，先拔U盘，再关机，开机，盒子黑屏，网络也连不上

### ISSUE THREAD

**Issue by Edwardyx** [ophub/amlogic-s9xxx-armbian#657]
刷的是[Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.75_server_2022.10.28.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_10.28.0245/Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.75_server_2022.10.28.img.gz)
刷入emmc后，先拔U盘，再关机，开机，盒子黑屏，网络也连不上。然后，就没有然后了。

**Comment by ophub** [comment]
然后，你是什么盒子呢，你在usb里面使用正常吗？
然后，你安装选项是什么呢？
然后，你有没试过5.10.y呢？
