### ISSUE TITLE
关于掉盘问题的后续

### ISSUE THREAD

**Issue by tingge9527** [ophub/amlogic-s9xxx-armbian#658]
之前关于掉盘，我再#632 发过帖子，另外的#543 也讨论过，目前我自己搞下来，的确可能是兼容性问题吧，反正应该不是供电问题，我买了双USB供电的数据线给移动硬盘盒使用还是掉盘。目前从反馈来说，一个是1153E主控的易驱线，比如绿联，然后再恩山也有人分享了飚王的移动硬盘盒也没掉盘，再然后就是我跑网心云的群里群友的反馈了，这个反馈的解决方法我有点不懂，因为他们是让系统再U盘上运行就没有出现掉盘的情况了，就是不写入EMMC，不过他们再U盘上运行的是CE系统。我这边目前准备测试让系统再U盘上运行看是否掉盘。因为U盘的主控带4K读写性能，所以先试试。在不行就只能买1153E主控的易驱线或者飚王的那款移动硬盘盒了。

**Comment by ophub** [comment]
你再观察观察
