### ISSUE TITLE
大佬M302A无法写入到EMMC

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#659]
Armbian_22.11.0_Aml_s905x_bullseye_5.15.75_server_2022.10.27

DTB :meson-gxl-s905l3b-m302a
![QQ截图20221030150255](https://user-images.githubusercontent.com/104506675/198866843-415b261a-46f9-4cdb-9a5d-8fb126a93cb0.png)
![2](https://user-images.githubusercontent.com/104506675/198866852-85ec8b2d-8c43-4cc3-9b79-6c7b77103372.png)
![3](https://user-images.githubusercontent.com/104506675/198866855-1f65b956-eaa1-4e05-8f6a-74f2df3a9d84.png)
 大佬 怎么解决呀？

**Comment by ophub** [comment]
m302a序号306

**Comment by 84864797** [comment]
![1111](https://user-images.githubusercontent.com/104506675/198867209-98ece8ba-8a40-42bf-a7b1-ef143b7119f1.png)
一样呀

**Comment by ophub** [comment]
`lsblk`

**Comment by 84864797** [comment]
![222](https://user-images.githubusercontent.com/104506675/198867572-5ffc231f-b6a9-400e-82dd-982ea153c6a1.png)
换了个5.10内核的了

**Comment by ophub** [comment]
emmc不让操作，可以用晶晨刷机工具刷个root了的安卓系统。再安装写入emmc

**Comment by 84864797** [comment]
能不能直接覆盖掉安卓系统？

**Comment by ophub** [comment]
不能

看看这里有没和你的盒子一致的安卓系统
https://github.com/ophub/kernel/releases/tag/tools

**Comment by 84864797** [comment]
![image](https://user-images.githubusercontent.com/104506675/198869767-957d2f78-328f-426d-ba3b-eb01541312ca.png)
试了2个固件 都能开机
android_tv_mgv2000-s905l2-android4.4.2-root.tar.xz
android_tv_m302a_s905l3b.tar.xz
刷了 mgv2000的 只显示1G内存   
2个固件都不能写入EMMC

**Comment by ophub** [comment]
你的m302a是android_tv_m302a_s905l3b.tar.xz

mgv2000不是你的盒子的，不能乱试。

emmc能写入安卓系统，为什么不能写入armbian系统呢？

https://github.com/ophub/amlogic-s9xxx-armbian/blob/f0b76675beedb98dbfe9833d35ab37a6486c3340/build-armbian/common-files/rootfs/usr/sbin/armbian-install#L294

这几有什么问题？

**Comment by 84864797** [comment]
我的M302A 是905L2B 的CPU。  mgv2000是9005L2    android_tv_m302a_s905l3b.tar.xz  应该是S905L3B   好像都能用  我用mgv2000的DTB，也能进入Armbian。

**Comment by ophub** [comment]
你改安装脚本测试了没？

**Comment by 84864797** [comment]
改了呀  还是一样 
![image](https://user-images.githubusercontent.com/104506675/198877768-5adfe818-14b3-4294-86e0-f05f2b755a8a.png)

**Comment by ophub** [comment]
我一时间想不到好办法了，等其他人出招吧

**Comment by imzlh** [comment]
我好像之前也莫名有这种问题，观察是parted出状况了。要看parted出什么状况了，试试看把>/dev/null去掉再试试看错误输出
![A2B8CD07-99FC-48B9-90EE-19B94FCFAC66](https://user-images.githubusercontent.com/114276136/200114647-7dfc915b-53b3-496f-a540-46f33bc5b53c.jpeg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/648#issuecomment-1303118463

这个问题是emmc频率高，在这里有解决方案

**Comment by 84864797** [comment]
今天才看到邮件  试了下 用的5.10内核  DTB:meson-gxl-s905l2-ipbs9505.已经成功写入EMMC
![QQ截图20221106221348](https://user-images.githubusercontent.com/104506675/200175996-94f5b9ba-33e1-4c27-95d8-2fe5d9627f33.png)
感谢大佬
