### ISSUE TITLE
The buring tool informs the image checking failure

### ISSUE THREAD

**Issue by iDea2016su** [ophub/amlogic-s9xxx-armbian#66]

**Comment by ophub** [comment]
https://rufus.ie/

Re-download the firmware, re-download the tool, and retry until it is done.

**Comment by iDea2016su** [comment]
thanks for your advice， i tryed the tools，the system can work in sd card， but when i input armbian-install command，there is no item for my  box a95xf3-air-100. I found the dtb file，but no uboot file in the package. So any suggestion for this box， thanks！
