### ISSUE TITLE
Mecool M8S Pro L  how to?

### ISSUE THREAD

**Issue by apoklyps3** [ophub/amlogic-s9xxx-armbian#660]
Are there any clear instruction on how to get this running from a TF card?
I flashed Armbian_22.11.0_Aml_s912-m8s_jammy_5.15.75_server_2022.10.28.img to a card and plugged it into my Mecool M8S Pro L, but I have no ideea where to go from there.
It doesn't automatically boot.

**Comment by ophub** [comment]
Decompress to. img before writing to TF card

**Comment by apoklyps3** [comment]
I somehow feel that balena etcher already does that for me, as the Boot patition pops up after it is flashed, but I will try.
I'm asking if I have to to something on the box from the Android side or I just have to plug in the card and it should boot...

**Comment by ophub** [comment]
In the Android system, you can start the armian system from TF/USB only when you enable the USB debugging mode

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs#124-set-the-box-to-boot-from-usbtfsd
