### ISSUE TITLE
更新内核获取不到新版本要手动输入

### ISSUE THREAD

**Issue by phgcab59238** [ophub/amlogic-s9xxx-armbian#662]
之前更新没问题的 最近几个版本一直获取不到

![image](https://user-images.githubusercontent.com/117004939/198869879-049966fa-0954-4688-90c8-be70ba0dceee.png)

**Comment by ophub** [comment]
你ping github.com
你访问他的速度肯定很慢。

**Comment by phgcab59238** [comment]
但是直接指定版本号又能获取到并且下载就很迷

**Comment by ophub** [comment]
查询不到，返回不了，不载不动，这都是本机访问github.com服务器网络不好的表现。

**Comment by phgcab59238** [comment]
soga 感谢解惑

**Comment by shineanr** [comment]
@ophub 是不是下面的url拼的不对啊
```

[ STEPS ] Start downloading the kernel from [ https://github.com/ophub/kernel/tree/main/pub/stable/5.15.76 ]...
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ophub/kernel/trunk/pub/stable/5.15.76'
svn: E120108: Error running context: The server unexpectedly closed the connection.
```

**Comment by ophub** [comment]
没错，你的网络访问github.com有问题。

**Comment by allonmymind** [comment]
可否把同步脚本和更新脚本加个代理前缀，例如https://ghproxy.com/，这样就能解决这个问题了

**Comment by shineanr** [comment]
> 没错，你的网络访问github.com有问题。
> 
> ![Snip20221104_1](https://user-images.githubusercontent.com/68696949/199935071-e9ac48ba-837b-44f5-b9d3-ca08c1112969.png)

显示的是这个，Start downloading the kernel from [ https://github.com/ophub/kernel/tree/**main**/pub/stable/5.15.76 ].
为什么无法连接的是trunk？
 Unable to connect to a repository at URL [https://github.com/ophub/kernel/**trunk**/pub/stable/5.15.76]
上面的地址浏览器是可以打开的

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/usr/sbin/armbian-update#L212-L215

[ ${kernel_repo/trunk/tree\/main}/${inputs_kernel} ]
213行：将kernel_repo路径中的trunk替换为了tree/main是为了echo显性输出下载路径，给人类看的，有人会打开这个网址看看里面有什么。trunk是github接口规范格式。tree/main是浏览器访问格式。
214行：svn export ${kernel_repo}/${inputs_kernel}，还是保持使用kernel_repo的接口格式让svn服务下载内核。
