### ISSUE TITLE
E900V22D写入emmc需要复制u-boot

### ISSUE THREAD

**Issue by wangnengjier** [ophub/amlogic-s9xxx-armbian#663]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
第一个问题：安装到内部的Emmc上后， 能运行，但是启动过程中报错， 找不到网卡的PHY。 
有两点， 
1。 用usb stick 启动正常。
2。 即使是从Emmc启动， 如果usb stick插在上面，它也能找到网卡并成功驱动，获得ip地址。
第二个问题：安装到内部Emmc后， 软件安装不了。
运行

**To Reproduce**
第一个问题，
从Emmc启动系统
具体错误提示是：
meson8b-dwmac ff3f0000.ethernet eth0:no phy at addr -1
meson8b-dwmac ff3f0000.ethernet eth0:stmac_open:Cannot attach to PHY(error:-19)
meson8b-dwmac ff3f0000.ethernet eth0:validation of rmii with support 0000000,00000000, 00006280 and adertisement 0000000,00000000,00006280failed: -22
第二个问题具体提示为
从Emmc上启动系统，运行了armbian-software，选择任意一款软件，比如VCL
显示：
Start processing software：【command-desktop.sh install VLC】...
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: /etc/sudo.conf is owned by uid 1023, should be 0
sudo: eooro in /etc/sudo.conf,line 0 while loading plugin "suduers_policy"
sudo: /usr/libexec/sudo/sudoers.so must be owned by uid 0
sudo: fatal error, unable to load plugins

*Expected behavior**

**Screenshots**
传图片有点困难

**Armbian Version**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: [S095La3]
 - Brand: [Skyworth]
 - Model [E900V22D]

**Additional context**

**Comment by ophub** [comment]
你下载刚才编译完的固件再试一下，看第二个权限的问题是否存在，我测试的没问题。

第一个问题我想不清原因，为什么插着usb就可以识别网卡，拔了usb就识别不了了，dts写错了？

**Comment by wangnengjier** [comment]
我开始以为是u-boot的原因（上网查可能是u-boot未传递正确的mac地址给后面的驱动等啥的），试着用了两次安装，
一次是armbian-install yes
另一次不带参数yes， 结果一样的。 

另外，如果我没有把usb 存储设备里的fat32分区u-boot-E900V22C.bin 这个文件重命名成 u-boot.ext，从usb启动也会出现类似错误。

**Comment by ophub** [comment]
问题就是你的重命名的错。你在usb里重命名了，让安装文件去拿什么给你生u-boot.emmc呢？

不要重命名，是复制，不要把原文件整没了

**Comment by wangnengjier** [comment]
我说错了， 是复制了。原来的文件在的。没动。

**Comment by ophub** [comment]
armbian-install yes
这个只对主线uboot有用，对你的u-boot.emmc无效。
你手动usb启动，把emmc的boot挂载到usb某个目录，复制一个u-boot.emmc

**Comment by wangnengjier** [comment]
对了安装到了emmc上后，默认优先从emmc上启动，能不能还是优先从usb上启动？
我还不会手动设置u-boot从usb启动。（捂脸），
挂载我倒是会，只是emmc的boot分区有2个， 一个boot0，一个boot1， 我挂载哪个？

**Comment by ophub** [comment]
只要插着u盘就会从u盘启动。如果你从emmc启动的，直接去/boot复制

```
#从emmc启动
cd /boot
cp -f u-boot-e900v22c.bin u-boot.emmc
chmod +x u-boot*
sync
reboot
```

**Comment by wangnengjier** [comment]
试过了， 
![新建位图图像](https://user-images.githubusercontent.com/114163628/198879157-2735dde6-4307-4c5c-b41e-87e4815c2fef.png)

**Comment by wangnengjier** [comment]
不过我刚才试了一下， 拔了usb stick， 启动能获得ip了，应该是驱动好了。

**Comment by ophub** [comment]
/boot挂在emmc就是从emmc启动的。

https://github.com/ophub/amlogic-s9xxx-armbian/issues/647

这个贴子里反馈ssh问题没有了，我下午刚注释掉了，你如果有这个问题就打开

**Comment by wangnengjier** [comment]
我的问题已经解决，只是install时候脚本是不是漏了啥？比我还小白的家伙下次armbian-install 不会有少u-boot.emmc的问题了吧
我用mount 命令看到了boot挂载在哪里了。 能分出来是从usb启动还是emmc启动了。

**Comment by ophub** [comment]
使用5.4/5.15内核不用复制这个u-boot也可以正常使用，你这是个特例。

不过复制了也没什么坏处（只是启动慢10秒）

**Comment by wangnengjier** [comment]
> 

话说我这个就是今天上午下载的5.15.75，jammy，server，从你这边release下载的啊

**Comment by wangnengjier** [comment]
我刚才ls看了一下， 我文件里多了一个uboot.emmc，所以我猜是脚本里，copy命令弄错了。少打了一个“-”

**Comment by ophub** [comment]
![Snip20221030_2](https://user-images.githubusercontent.com/68696949/198881518-0646dfef-0b74-4470-9d69-af669a53e676.png)

我的系统里没有你说的文件。仓库脚本里也没搜到uboot.emmc

**Comment by xcray** [comment]
插着u盘启动正常、不插着u盘启动就不正常的原因恰恰就是因为u盘上有u-boot.ext文件而emmc里没有u-boot.emmc文件。
部分机型哪怕是用5.4/5.15内核，也需要u-boot.ext/emmc文件，否则的话即使能启动，网卡或内存识别也有问题。
而有的机型，有u-boot.emmc的话反而启动不了，表现是加载u-boot.emmc后不认emmc！
5.4/5.15内核默认是不会复制出u-boot.ext/emmc文件的，需要的话就得手工复制。

**Comment by ophub** [comment]
xcray说的对，同名也有个体差异，要不要得自己试一下

**Comment by wangnengjier** [comment]
> 

泪崩了，折腾了一天，把自己仅有的三个盒子都给弄变砖了。
最后一个啥都好了，因为装了ubuntukylin-desktop，键盘没响应， ssh没启动。 
之前2个都是因为写不同的有问题的armbian进去，但是从emmc上启动不了。 又不从usb启动黑屏了。
等有空看看用线刷能不能救回来了。

**Comment by wangnengjier** [comment]
> xcray说的对，同名也有个体差异，要不要得自己试一下

多问一下，我想换成你新编译过的版本， 然后试图从u盘启动，但是不知道如何操作。能帮忙指点一下么

**Comment by wangnengjier** [comment]
![image](https://user-images.githubusercontent.com/114163628/199538244-0580e750-99db-4522-995a-9d5a6378563c.png)
已经焊上串口的针，通过启动到了uboot的命令行了。但是不知道如何通过usb启动

**Comment by ophub** [comment]
https://docs.qq.com/doc/DWFprWWxZa290VXNk

其他盒子都会优先从usb启动，这个u-boot特殊，写入emmc后设置usb优先启动的方式见文档最后

**Comment by wangnengjier** [comment]
> 启动

这个文档我看了很多遍了， 但是最后只有ttl输出的内容，里面并没有相对应的命令啥的。我自己通过help和各个命令去试，已经发现usbboot命令能行了，但是 usbboot 后面要加地址，不知道这个地址要用啥地址。。。
