### ISSUE TITLE
安装并配置好armbian之后，如何打包备份成img

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#664]
机器是b863av3.2-m，从u盘成功启动Armbian之后，尝试写入emmc失败，所以教程中的备份方法也无法使用，请问有什么方法可以备份当前u盘中使用的Armbian系统？

**Comment by xcray** [comment]
U盘无论保存什么内容，都可以制作成img，估计即使是电脑小白，也能轻易完成这个动作。

这和armbian没有任何关系！

**Comment by ophub** [comment]
可以dd备份到电脑，也可以使用U盘备份工具
