### ISSUE TITLE
v4L2 failed !! exit fatal

### ISSUE THREAD

**Issue by maxcalavera81** [ophub/amlogic-s9xxx-armbian#666]
Hi, I'm using klipper on tanix tx3 and so far so good. But I have a problem related to the webcam. Is it possible to help here?
I have the following error in the log...

```
/usr/local/bin/webcamd: line 219: vcgencmd: command not found
Found video devices:
/dev/video0
config file='/home/homeassistant/klipper_config/webcam.txt':USB device was not set in options, start MJPG-streamer with the first found video device: /dev/video0
/usr/local/bin/webcamd: line 184: printf: 0x: invalid hex number
/usr/local/bin/webcamd: line 184: printf: 0x: invalid hex number
<13>Nov  1 19:18:44 homeassistant: Starting USB webcam
Checking for VL805 (Raspberry Pi 4)...
  - It seems that you don't have VL805 (Raspberry Pi 4).
    There should be no problems with USB (a.k.a. select() timeout)
Running ./mjpg_streamer -o output_http.so -w ./www-mjpgstreamer -n -i input_uvc.so -r 640x480 -f 10 -d /dev/video0
MJPG Streamer Version: git rev: 310b29f4a94c46652b20c4b7b6e5cf24e532af39
 i: Using V4L2 device.: /dev/video0
 i: Desired Resolution: 640 x 480
 i: Frames Per Second.: 10
 i: Format............: JPEG
 i: TV-Norm...........: DEFAULT
Error opening device /dev/video0: video capture not supported.
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed
Done bring up all configured video device

Goodbye...
```

If it were possible to help, it would be very valuable. Thank you very much

**Comment by vMeph** [comment]
having the same problem
`Error opening device /dev/video0: video capture not supported.
Init v4L2 failed !! exit fatal
 i: init_VideoIn failed`

**Comment by ophub** [comment]
`/usr/local/bin/webcamd: line 219: vcgencmd: command not found`

Missing `vcgencmd`, you install this package

**Comment by YanceyChiew** [comment]
> Running ./mjpg_streamer -o output_http.so -w ./www-mjpgstreamer -n -i input_uvc.so -r 640x480 -f 10 -d /dev/video0

I'm not sure, should the parameters shown in this paragraph be specified by you?

Do they match the device information you got from executing the following command?

```
v4l2-ctl --all
```
