### ISSUE TITLE
近期发现armbian-config每次启动都要特别久，足足有两分多钟！而且没有任何提示

### ISSUE THREAD

**Issue by xcray** [ophub/amlogic-s9xxx-armbian#667]
![image](https://user-images.githubusercontent.com/26018728/199360044-964e451c-046c-40e7-9045-3a1582a594a5.png)
难道是github访问不畅的缘故？能否用本地缓存、超时之类的方法优化一下？

**Comment by ophub** [comment]
你执行下试试多久
`wget -q --spider http://github.com`

在/usr/sbin/armbian-config里有几处是要联网的

**Comment by xcray** [comment]
> 你执行下试试多久 `wget -q --spider http://github.com`
> 
> 在/usr/sbin/armbian-config里有几处是要联网的

运行这条命令基本上要2~3分钟。。。

这段时间github访问确实很不顺畅，用浏览器访问也是如此

**Comment by imzlh** [comment]
把github.com换成baidu.com不就OK了？我就这么干

**Comment by xcray** [comment]
> 把github.com换成baidu.com不就OK了？我就这么干

这也行？仅仅是检测有没有互联网的话，用baidu确实比github好得多
