### ISSUE TITLE
T95Z Plus TV Box (S912) NAS dropping out

### ISSUE THREAD

**Issue by JBHudston** [ophub/amlogic-s9xxx-armbian#668]
I have installed Armbian_22.11.0_Aml_s912-m8s_bullseye_5.10.142_server_2022.09.14.img.gz on the T95Z Plus box. Installed Gnome and setup a samba share of a 4TB USB hard drive (formatted NTFS).

The samba share works fine but connection keeps randomly dropping while playing mp3s or videos from windows PC or Kodi/FireTV

I am connected by ethernet and have turn off wifi.

I repeatably get the following error log in syslog:
```
Nov  2 14:32:13 VideoNASty hostapd[130771]: Could not open configuration file '/etc/hostapd/hostapd.conf' for reading.
Nov  2 14:32:13 VideoNASty hostapd[130771]: Failed to set up interface with /etc/hostapd/hostapd.conf
Nov  2 14:32:13 VideoNASty hostapd[130771]: Failed to initialize interface
Nov  2 14:32:13 VideoNASty systemd[1]: hostapd.service: Control process exited, code=exited, status=1/FAILURE
Nov  2 14:32:13 VideoNASty systemd[1]: hostapd.service: Failed with result 'exit-code'.
Nov  2 14:32:13 VideoNASty systemd[1]: Failed to start Access point and authentication server for Wi-Fi and Ethernet.`

and the samba log shows:
`[2022/10/26 22:11:29.576909,  0] ../../source3/smbd/service.c:168(chdir_current_service)
  chdir_current_service: vfs_ChDir(/media/spudgun/4TB USB HD/NAS) failed: Permission denied. Current token: uid=1000, gid=1000, 13 groups: 1000 5 6 20 27 29 44 46 60 100 101 106 111
[2022/10/26 23:02:51.146024,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
[2022/10/26 23:02:51.150871,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
[2022/10/26 23:02:51.545755,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
[2022/10/26 23:02:51.556669,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
[2022/10/26 23:02:51.565281,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
[2022/10/26 23:02:51.575333,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
[2022/10/26 23:03:10.444670,  0] ../../source3/smbd/vfs.c:1081(vfs_GetWd)
  vfs_GetWd: SMB_VFS_GETWD call failed: Input/output error
```

**Comment by ophub** [comment]
sudo systemctl status hostapd
sudo systemctl disable hostapd

**Comment by ophub** [comment]
It is recommended not to use spaces in the directory name, there will be some software incompatibility problems.

`4TB_USB_HD`

**Comment by JBHudston** [comment]
I have renamed the drive without spaces.

The Wi-Fi error has stopped now.

However the share still drops randomly.
Also I don’t get log files for the FireTV boxes that access the share via Kodi. Why would this be?

**Comment by ophub** [comment]
Turn off automatic hibernation for shared hard drives. 
Mount with uuid, not lable. 
Open the log in kodi and save it to a fixed path.

**Comment by ophub** [comment]
`blkid`

write to:
/etc/fstab

**Comment by JBHudston** [comment]
`root@VideoNASty:~# blkid
/dev/mmcblk2p1: SEC_TYPE="msdos" LABEL_FATBOOT="BOOT_EMMC" LABEL="BOOT_EMMC" UUID="7EDD-ED4D" BLOCK_SIZE="512" TYPE="vfat"
/dev/mmcblk2p2: LABEL="ROOTFS_EMMC" UUID="f33e65f2-a814-4397-82c6-6e13f38e3636" BLOCK_SIZE="4096" TYPE="ext4"
/dev/zram0: UUID="312b4f0c-eb8a-4cbd-8fdf-38a7af9f0a34" TYPE="swap"
/dev/zram1: LABEL="log2ram" UUID="291d8bda-354b-407c-984a-fcb759288fa7" BLOCK_SIZE="4096" TYPE="ext4"
/dev/zram2: LABEL="tmp" UUID="63444e5d-0146-4d24-8964-3d26bcc152e0" BLOCK_SIZE="4096" TYPE="ext4"
/dev/sda1: LABEL="4TB" BLOCK_SIZE="512" UUID="46A028775931E054" TYPE="ntfs" PARTUUID="53487fb5-959f-4346-8d82-fdbd68b85e9a"
`

**Comment by JBHudston** [comment]
sudo nano /etc/fstab

```
UUID=f33e65f2-a814-4397-82c6-6e13f38e3636  /        ext4     defaults,noatime,errors=remount-ro     0 1
LABEL=BOOT_EMMC      /boot    vfat                    defaults                  0 2
tmpfs                /tmp     tmpfs                   defaults,nosuid           0 0
UUID=46A028775931E054 /mnt/46A028775931E054 auto nosuid,nodev,nofail,x-gvfs-show 0 0
```

**Comment by ophub** [comment]
The ntfs format is not well supported under linux, ext4 and btrfs are recommended

**Comment by moaasd** [comment]
After installing Feiniu on the T95Z-Plus, it only shows 2GB of memory, while Armbian shows 3GB.

**Comment by xuloy** [comment]
My T95z plus box is the S912 model with 3GB of RAM and 32GB of storage, featuring a red motherboard. The memory consists of 4 chips. The WiFi and Bluetooth module is the AP6255. The TF card is installed with the Armbian 26.04 operating system. The XFCE desktop environment has been installed, but the Bluetooth function is not available. Can it be fixed?
