### ISSUE TITLE
Starting kernel

### ISSUE THREAD

**Issue by maxcalavera81** [ophub/amlogic-s9xxx-armbian#670]
Why does my tx3 always start with this and no matter what I put there it always does this?  Not even Android can reset.  Some help?

![IMG_20221103_151555](https://user-images.githubusercontent.com/43672635/199762738-7e293f45-52d7-4618-a5af-510971dc52ab.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

Download the Android system of tx3, which has the original system and short circuit icon
