### ISSUE TITLE
eth0 (internet) seems to not work 

### ISSUE THREAD

**Issue by operamilkmandolinneo12** [ophub/amlogic-s9xxx-armbian#673]
After reinstalling Armbian 5.15 Jammy (server) for S905W to A95X F1, connected it to the internet using eth0 and did `apt update` But it doesn't seem to work.

![873D4895-7BD2-48FF-BAA1-AB2AE43B5429](https://user-images.githubusercontent.com/116323624/200143945-ea75628f-a2a1-48ce-8403-0c14f819649c.jpeg)

So, I checked it by doing `ping google.com` But it outputs a message that has the lines of "port unreachable."

Then, I checked `systemctl status networking` And I got this.

![29F8CAEC-6D1D-4798-BEAA-A9006FE90685](https://user-images.githubusercontent.com/116323624/200143955-cbf2444f-45a6-4bab-8ba9-79a67c9c7a9e.jpeg)

I did `systemctl restart networking` But doesn't work still.

When I installed Armbian for the first time, the eth0 seems to be working before, but now its unable to connect after reinstalling.

**Comment by livelier** [comment]
建议你尝试，关掉ipv6，仅使用ipv4，设置DHCP获取动态IP地址。

**Comment by operamilkmandolinneo12** [comment]
> 建议你尝试，关掉ipv6，仅使用ipv4，设置DHCP获取动态IP地址。

I translated it to English, but actually. I tried that using `armbian-config` But it didn't work. Setting up DHCP for a dynamic IP won't work too

**Comment by YanceyChiew** [comment]
Just try using `systemd-networkd`.

**Comment by xcray** [comment]
try to disable auto-negotiation

**Comment by operamilkmandolinneo12** [comment]
I'll try these once I have time

**Comment by operamilkmandolinneo12** [comment]
Nope. Any of these fixes don't work, and reinstalling back to the stock Android only works for networking. Was gonna use this for Pi-hole but no chance.

**Comment by jackcctse** [comment]
Hello @operamilkmandolinneo12, 

I had the same issue. For me increasing timeout value of networking script helps, i.e. TimeoutStartSec=10sec to TimeoutStartSec=30sec. This script is here:
`/etc/systemd/system/network-online.target.wants/networking.service`

Other than networking service, you can use NetworkManager to retrieve internet tool. Avoid using both networking service and NetworkManager at the same time, if not you may retrieve two IPs from upstream DHCP server. 

`systemctl enable NetworkManager`
`systemctl start NetworkManager`
