### ISSUE TITLE
S905L +8189 WIFI能看到  但是连接的时候输入密码就死机。

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#674]
S905L +8189 WIFI

Armbian_22.11.0_Aml_s905x_jammy_5.10.152_server_2022.11.04.img.gz

dtb:meson-gxl-s905x-p212

WIFI能看到  但是连接的时候输入密码 确认后就死机。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek


rtl8189fs？

**Comment by 84864797** [comment]
8189etv

**Comment by ophub** [comment]
驱动不匹配，你找找主线内核可以使用的驱动源码，添加编译试试

**Comment by 84864797** [comment]
具体步骤应该怎么做？

**Comment by ophub** [comment]
找到对应的兼容的驱动，参照上面的网址，驱动放相应的目录，添加编译项，进行编译测试

**Comment by 84864797** [comment]
Armbian 20.11 Focal with Linux 5.9.0-arm-64    我用恩山上下载的5.9内核的固件  查了下 驱动也是8189fs   用起来 好像没有问题

**Comment by 84864797** [comment]
https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=4053939&page=1

**Comment by 84864797** [comment]
我在github 找到几个驱动  但是我不知道 添加编译项 该怎么操作?  求大佬指教
