### ISSUE TITLE
X96 mini   S905W

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#675]
插的USB 无线网卡    无线和有线一起连接着好像没有问题   但是单独连接WIFI  就会死机。我路由器的后台看了下 是获取IP后 瞬间 就死机了。

Armbian_22.11.0_Aml_s905w_jammy_5.15.76_server_2022.11.04.img.gz

dtb: X96 Mini

**Comment by 84864797** [comment]
下面那条S905L+ 8189etv 的也是我发的   连接WIFI 死机
手头3个盒子 没有一个能连接上WIFI的= =||
M302A +8822CS 的 更是加载不了WIFI驱动

**Comment by ophub** [comment]
8822cs不稳定，上个月更换过一个新的驱动，也不行，暂时用不了
