### ISSUE TITLE
能编译为64位的armbian吗

### ISSUE THREAD

**Issue by gzxief** [ophub/amlogic-s9xxx-armbian#676]
能编译为64位的armbian吗
好像在armbian/bulid里，修改configuration.sh中的ARCH=ARM64，debootstrap.sh中[[ $ARCH == arm64 ]] && eval 'LC_ALL=C LANG=C chroot $SDCARD /bin/bash -c "dpkg --add-architecture armhf"'修改为[[ $ARCH == arm64 ]] && eval 'LC_ALL=C LANG=C chroot $SDCARD /bin/bash -c "dpkg --add-architecture arm64"'，就可以编译出64位的armbian了，再安装docker就可以拉取arm64的镜像了

**Comment by ophub** [comment]
这里下载的都是64位的
