### ISSUE TITLE
E900V22C，芯片S905L3A-B的盒子现在支持写EMMC了吗

### ISSUE THREAD

**Issue by guugg** [ophub/amlogic-s9xxx-armbian#678]
U盘使用正常，尝试直接`armbian-install`写入貌似失败了（拨开U盘启动armbian显示器是暗黑屏）
其它的没敢再测试，害怕突然砖了

**Comment by ophub** [comment]
`armbian-install yes`

**Comment by guugg** [comment]
> `armbian-install yes`

成功了，原来需要加一个`yes`

**Comment by ophub** [comment]
就这一个盒子比较特殊，大家普遍反馈需要添加/boot/u-boot.emmc才能在emmc使用，在armbian-install后面加yes就是添加主线和u-boot的作用。
