### ISSUE TITLE
手上有两个版本的X96air 的盒子网卡都还是有问题

### ISSUE THREAD

**Issue by dawei** [ophub/amlogic-s9xxx-armbian#679]
一个千兆版本的，有线网卡是JL2101，有线网卡不能工作
一个百兆版本的，无线网卡是RTL8189FTV，无线网卡不能工作

；）大神能解决吗

**Comment by ophub** [comment]
千兆版试试5.10的固件，修改/boot/uEnv.txt里dtb的值为
meson-sm1-x96-air-gbit.dts

**Comment by 84864797** [comment]
https://www.right.com.cn/FORUM/forum.php?mod=viewthread&tid=4053939&page=1   这个固件 你可以试一下  我的是一个盒子是 S905L+8189FTV  WIFI能驱动的起来

**Comment by dawei** [comment]
> 千兆版试试5.10的s905x3固件，修改/boot/uEnv.txt里dtb的值为
> meson-sm1-x96-air-gbit.dts
> 
> RTL8189FTV无线没驱动，在另外一个帖子里已经回复过你的这个问题了。

千兆版本的感觉网卡识别了，获取不到ip，静态设置也没有用

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

看12.7

你把盒子的网线接入路由器的网络里，都会自动分配ip，你在路由器里面找刚上线的名字叫armbian的设备ip
