### ISSUE TITLE
A95XF3-air(S905X3) uboot file

### ISSUE THREAD

**Issue by iDea2016su** [ophub/amlogic-s9xxx-armbian#68]
thanks for your advice， i tryed the tools，the system can work in sd card， but when i input armbian-install command，there is no item for my  box a95xf3-air-100. I found the dtb file，but no uboot file in the package. So any suggestion for this box， thanks！

_Originally posted by @iDea2016su in https://github.com/ophub/amlogic-s9xxx-armbian/issues/66#issuecomment-1008256957_

**Comment by ophub** [comment]
Which firmware are you using on the usb, the kernel number is 5.10? soc is s905x3? Which is the dtb

**Comment by ophub** [comment]
add one line in line 76

https://github.com/ophub/amlogic-s9xxx-armbian/blob/dac1f90483a86aed89492b4d4d6202c7880fe8ea/build-armbian/common-files/files/usr/sbin/armbian-install#L75-L76

59:A95XF3:s905x3: meson-sm1-a95xf3-air-100.dtb:u-boot-x96maxplus.bin:NA:NA:4C@2208Mhz,2(Cube)/4(Pro,Plus)GB Mem,1Gb Net,Wifi

**Comment by iDea2016su** [comment]
Thanks for your suggestion. I tested Armbian_22.02.0_Aml_s905x3__5.10.90_2022.01.10.1223.img.gz  and added the command on line 76. After the installing is finished via the "armbian-install", I rebooted the device, unfortunately, the device can not start and enter any system.

**Comment by ophub** [comment]
What are you using in usb, modify it.

59:A95XF3-air-100:s905x3:`meson-sm1-a95xf3-air-100.dtb`:`u-boot-x96maxplus.bin`:`/lib/u-boot/x96maxplus-u-boot.bin.sd.bin`:NA:4C@2208Mhz,2(Cube)/4(Pro,Plus)GB Mem,1Gb Net,Wifi

**Comment by iDea2016su** [comment]
the firmware is download from the released build version, I think the kernel is 5.10 as the dmg name contains "5.10.90_2022". I modified the uEnv.txt as follows. However, it doesn't work.

`LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-a95xf3-air-100.dtb
APPEND=root=LABEL=ROOTFS rootflags=data=writeback rw console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
`

![IMG_1860](https://user-images.githubusercontent.com/26154792/148737451-b7468e38-59ea-4bc8-b1d7-208f237b2592.JPG)

**Comment by ophub** [comment]
59:A95XF3-air-100:s905x3:meson-sm1-a95xf3-air-100.dtb:u-boot-x96maxplus.bin:/lib/u-boot/x96maxplus-u-boot.bin.sd.bin:NA:4C@2208Mhz,2(Cube)/4(Pro,Plus)GB Mem,1Gb Net,Wifi

**Comment by iDea2016su** [comment]
I used a sd card via a reader on USB

**Comment by ophub** [comment]
![Snip20220110_1](https://user-images.githubusercontent.com/68696949/148742342-66000975-597a-4bd9-95a5-78069860cc3e.png)


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-install#L130

**Comment by iDea2016su** [comment]
When I list the disk via fdisk -l, the Emmc mmcblk2 is recognized even I don't input
`dd  if=/dev/zero  of=/dev/mmcblk2  bs=512  count=1  &&  sync`
So whether you mean that the Emmc need to be cleared before the installing

**Comment by iDea2016su** [comment]
I part the mmcblk2 as the gpt format. And the `unrecognized error` is removed, however, the installing is still failed. That was a sad story
![IMG_1870](https://user-images.githubusercontent.com/26154792/148758445-5395d17f-6a15-4b08-86c9-aa860eb2e335.JPG)

**Comment by ophub** [comment]
The same error is at the end of the picture below. So before I can find a way to solve the problem of emmc, I can only use it on the sd card.

When you have time, you can restore emmc to the original `Android` TV system, and then rewrite it to armbian.

**Comment by iDea2016su** [comment]
thanks a lot
