### ISSUE TITLE
E900V22D无线模块

### ISSUE THREAD

**Issue by lovezp1932** [ophub/amlogic-s9xxx-armbian#680]
希望给盒子更换一个无线网卡模块，目前系统支持哪些模块可以更新，能同时兼容armbian和openwrt的，谢谢

**Comment by 84864797** [comment]
22D不是没有WIFI嘛？  买个黑苹果免驱的USBWIFI 就可以啦

**Comment by lovezp1932** [comment]
想重新焊接一个，我看8822cs支持不好，有没有其他可以支持的模块

**Comment by ophub** [comment]
8822cs驱动50%的概率没法用
