### ISSUE TITLE
大佬 怎么编译WIFI驱动呀

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#681]
看了芯片 是8189ftv  
WIFI能看到 但是连接的时候输入密码 确认后就死机。
github找了下8189ftv ,好像和8189fs一样的驱动。
内核里也是有8189fs的。
我想编译下github上的几个8189的源码看看 
但是
git clone https://github.com/rehsack/rtl8189ES_linux
cd rtl8189ES_linux
make 
这样的步骤  好像是不行的。
求教 应该怎么操作
谢谢大佬

**Comment by lppsuixn** [comment]
你能看到wifi吗？什么机器？用的哪个版本的

**Comment by 84864797** [comment]
> 你能看到wifi吗？什么机器？用的哪个版本的
S905L   
Armbian_22.11.0_Aml_s905x_jammy_5.10.152_server_2022.11.04.img.gz

dtb:meson-gxl-s905x-p212

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/231cff88a4f0c81de51158fefea7c320968c99c7

这个commit就是一个完整的添加无线驱动的标准案例
