### ISSUE TITLE
不好意思，大佬能帮忙看下HK1box 蓝色LED灯如何点亮吗？

### ISSUE THREAD

**Issue by renkoud** [ophub/amlogic-s9xxx-armbian#682]
因为买的是一个改装的盒子，蓝色的指示灯必须修复点亮风扇才会转，因为是个小白只能跟着大佬摸索，试了你回复的这个帖子，讲dtb文件修改后，依然无法点亮蓝灯，无奈只好再做伸手党，打扰大佬万分抱歉https://github.com/ophub/amlogic-s9xxx-armbian/issues/414

**Comment by renkoud** [comment]
原贴地址：https://github.com/ophub/amlogic-s9xxx-armbian/issues/414

**Comment by renkoud** [comment]
原贴地址: https://github.com/ophub/amlogic-s9xxx-armbian/issues/414

**Comment by renkoud** [comment]
安装的是大佬的armbian系统，原贴地址: https://github.com/ophub/amlogic-s9xxx-armbian/issues/414

**Comment by renkoud** [comment]
已可以按照此贴9楼的方法解决，感谢帖子原作者。https://www.znds.com/forum.php?mod=viewthread&tid=1225511&page=1#pid63797966

**Comment by ophub** [comment]
可以把方法复制粘贴到这里，方便其他朋友使用，以免以后论坛贴子打不开了

**Comment by localhosts-A** [comment]
感谢，帖子里面的方法确实有用
