### ISSUE TITLE
打包固件是 BOARD 报错了，不知道啥意思

### ISSUE THREAD

**Issue by vpei** [ophub/amlogic-s9xxx-armbian#683]
最新版，之前都是好的升级了一下就出错了。

(1.1) Start making OpenWrt [ n1 - 5.15.77 ]. Remaining space is 7G.
 [ n1 - 5.15.77 ]  (1/6) Confirm version type.
[ ERROR ] [ n1 ] config is missing!

**Comment by ophub** [comment]
没有n1这个board，叫s905d

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf

BOARD的值看第9列

**Comment by vpei** [comment]
> 没有n1这个board，叫s905d
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf
> 
> BOARD的值看第9列

明白了，之前版本不是也支持设备型号吗，新版本取消了吗？这个错误提示好你是amlogic-s9xxx-openwrt的，发错位置了。

**Comment by ophub** [comment]
两个仓库的使用方法相同。

之前使用case的时候，可以指定多个值，如 `s905d | n1 | phicomm-N1` 等，你可以任意使用其中的某个标签。

但是 rebuild/make 脚本里的这段设置不同固件配置的 case 代码实在太长了，有 100 多行，我就把这段代码删除了，指向了具有更完整的列表的 conf 文件，这样 fork 使用会更自由，可以自己在 conf 里制定各种自己使用的固件方案，打包好后开箱即用（目前我只打包了典型的一些盒子，有一些盒子使用时需要手动改 /boot/uEnv.txt 文件，如果自定义生成可以直接使用。）。
