### ISSUE TITLE
Is KII Pro supported?

### ISSUE THREAD

**Issue by sinancetinkaya** [ophub/amlogic-s9xxx-armbian#685]
Is Mecool KII Pro supported along with dvb AVL6862 ?
```
CoreELEC:~ # cat /proc/cpuinfo
Processor       : AArch64 Processor rev 4 (aarch64)
processor       : 0
processor       : 1
processor       : 2
processor       : 3
Features        : fp asimd evtstrm crc32
CPU implementer : 0x41
CPU architecture: AArch64
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : Amlogic
Serial          : 1f0c13003209a3a13e932786eb086f51
model name      : Amlogic S905H rev c

```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/e98da38a639a6f88a3b91e49d77280af4a07075a/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L27

**Comment by sinancetinkaya** [comment]
KII PRO, not KI PRO

**Comment by ophub** [comment]
Which dtb are you using in CoreELEC? find in armbian

**Comment by sinancetinkaya** [comment]
Mecool KII Pro (S905)  2G ram `gxbb_p200_k2_pro.dtb`

**Comment by ophub** [comment]
meson-gxbb-p200.dtb
meson-gxbb-p201.dtb

**Comment by sinancetinkaya** [comment]
Thanks 👍
Last question: does armbian kernel have drivers for AVL6862 dvb tuner?

**Comment by ophub** [comment]
Which dtb did you test fit the box?

**Comment by sinancetinkaya** [comment]
I haven't tested anything yet. I'm just trying to get information from you but I think you have a language problem. I will try to confirm the compatibility from somewhere else. Thank you anyway.

**Comment by sinancetinkaya** [comment]
> Thanks 👍 Last question: does armbian kernel have drivers for AVL6862 dvb tuner?

There's no dvb support. DVB has nothing to do with dtb files. AVL6862 driver needs to be ported from here https://github.com/afl1/dvb_tv-aml

**Comment by intropedro** [comment]
@sinancetinkaya, did you finally get it to work?

**Comment by sinancetinkaya** [comment]
> 

Armbian kernel doesn't have a driver for AVL6862, so no AVL6862 dvb in Armbian.
