### ISSUE TITLE
烽火HG680-LC 启动不了（S905L3-B)

### ISSUE THREAD

**Issue by sniperpr** [ophub/amlogic-s9xxx-armbian#686]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**
s905l3-b 无法启动

**To Reproduce**

**Expected behavior**

**Screenshots**

**Armbian Version**
 - Kernel Version: [e.g. 5.10.77]
 - Release: Armbian_22.11.0_Aml_s905l3a_jammy_5.15.77_server_2022.11.08.img
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: [e.g. S095l3-b]
 - Brand: [烽火]
 - Model [HG680-LC]

**Additional context**
串口启动信息在这里。

![串口信息](https://user-images.githubusercontent.com/1270268/200825995-43d32cc4-1160-48ae-9dc7-ac3334a34f50.PNG)

我的联系方式是： vx: luelue_ly

**Comment by sniperpr** [comment]
![微信图片_20221109200733](https://user-images.githubusercontent.com/1270268/200826434-0e24d1fe-ef17-4e97-acd8-751ab58047d5.jpg)

串口定义

**Comment by ophub** [comment]
试5.15内核的固件

**Comment by sniperpr** [comment]
> 

是的，我刚刚试了这个，可以启动了，hdmi目前无信号。

**Comment by sniperpr** [comment]
> 

给您写了封邮件（您的web@ 那个邮箱）
能否看看？

**Comment by ophub** [comment]
有问题就发这里交流即可，解决问题的办法也能共享给大家一起看看，我会的都会回答，这里没有需要付费回答的问题。

我只是一个初学者，刚接触不久，很多问题我在网上找不到解决方法了就要请教f大指导。有很多热心的朋友看到了也会给你建议。

**Comment by sniperpr** [comment]
我大概清楚问题了，看你的文档，应该是需要从android 的dts扒hdmi eth 正确定义，然后生成linux下dts

**Comment by ophub** [comment]
在内核源码改dts调试，只编dts几分钟就可以
