### ISSUE TITLE
E900V22D， A problem with installing to emmc occure. 安装到emmc发生问题。

### ISSUE THREAD

**Issue by wangnengjier** [ophub/amlogic-s9xxx-armbian#687]
也许不算一个bug，但是，可能算是个问题。 
Maybe it isn't a bug. but it is a question anyway.

请问大佬， 有没有另外一个版本针对从tf卡启动的安装脚本？
就像另外一个armbian-install.sh 一样。
Do you have the installation script when booting from TF card? 
just another versioin like "armbian-install".

我在板子上焊了TF卡座， 
启动正常，但是运行armbian-install yes 命令是出问题。 提示 you are ruuning in emmc mode， please boot system with usb or TF card。
I sold the TF card adapter on the mainboard. 
it boot well from the TF card.  when i try to install armbian to emmc with "armbian-install yes" command.  it says "you are running in emmc mode, please boot system with usb or tf card!"

事实上我已经不能从USB或者emmc启动了。 所以我才焊这个TF卡座在主板上的。
一下是相关的一些图片。 
in fact there was a problem with booting from emmc or usb.  this is the reason why i sold the TF card on the mainboard. 
the following  are the related pictures
![boot_well](https://user-images.githubusercontent.com/114163628/200837224-d1ba0f9e-d48d-4b12-9d6a-fdcefd83e52c.png)
![install-error](https://user-images.githubusercontent.com/114163628/200837265-586ea459-9e6e-4a9d-ac8a-a1dcab3e0534.png)
![QQ图片20221109205528](https://user-images.githubusercontent.com/114163628/200837269-4a307f81-e3d8-4b06-8dba-4a8f792ec298.jpg)

**Comment by ophub** [comment]
`lsblk`
截图

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/648#issuecomment-1304432821

试试这个dtb
下载解压，放在/boot/dtb/amlogic
改/boot/uEnv.txt里面dtb的名字
保存，重启sync && reboot

**Comment by wangnengjier** [comment]
研究了半天，最后发现发现不了tf卡了。 但是最后能从usb启动了。 然后问题也就不存在了。 

哎， 真是莫名其妙的。 

前几天一直都是黑屏启动不了。 

今天焊了tf卡槽，以为从tf卡槽启动能正常的，结果折腾了几次，发现从usb能启动了。 又发现不了TF卡了。 晕死。
