### ISSUE TITLE
多个N1盒子刷同一个镜像mac地址一样无法上网

### ISSUE THREAD

**Issue by chaodada** [ophub/amlogic-s9xxx-armbian#688]
我手上有两个N1 都刷了同一个镜像mac地址是一样的只能有一个上网

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/54c594eddcb1281fe98a8a8411a8f874d65e8fc5/build-armbian/common-files/rootfs/etc/network/interfaces#L11

自定义MAC地址

**Comment by chaodada** [comment]
感谢解答，不好意思、我刷的是今年八月的版本，现在最新版本已经修复了吗

**Comment by ophub** [comment]
恩
