### ISSUE TITLE
在armbian-software里添加chromium

### ISSUE THREAD

**Issue by xiayang0521** [ophub/amlogic-s9xxx-armbian#690]
**Describe the bug**
通过 apt install chromium安装的打开后不出现界面

**To Reproduce**
1. armbian-software安装desktop
2. apt install chromium安装chromium
3. 打开chromium，任务栏出现chromium，但不出现浏览器界面

**Armbian Version**
 Armbian 22.11.0-trunk Bullseye with Linux 5.10.152-ophub

**Device (please complete the following information):**
 - SOC: [ S905L3A]
 - Model [CM311-A]

**Comment by ophub** [comment]
sudo apt-get install -y chromium
