### ISSUE TITLE
armbian-install option suggests

### ISSUE THREAD

**Issue by livelier** [ophub/amlogic-s9xxx-armbian#691]
Using ampart for eMMC partition table adjustment requires DTB to be in normal format or multiple formats, or the above gzip version.

In application scenarios, the DTB may be a corrupted, incomplete, missing, or encrypted version. whether to use ampart by default?

The armbian-install installation parameters are suggested as follows, should be better than 'yes yes yes'.

```
armbian-install [option]

-m, --mainline       install mainline u-boot
-a, --ampart         change the partition to maximize the use of eMMC space
-s, --show           show a list of all devices
    --help           display this help and exit
```

E.g:

Install mainline u-boot and maximize emmc space usage
`armbian-install -m -a`

View help
`armbian-install --help`

Arrange work again for the great god of ophub 😂😂😂

**Comment by ophub** [comment]
I tested several devices and did nothing when the ampart partition failed, still using the original Android partition table structure, the partition setting policy during installation is the same as before.

Your installation options suggestions are great, upgraded to this mode today.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/6fc519919806fa6538b4199428ceeb0925e97ffc

After that, there is an activity on Double 11, which meets your `armbian-install` script and gives you `armbian-update` scripts as gifts.

**Comment by livelier** [comment]
Your double 11 gift is great 🎉🎉🎉
