### ISSUE TITLE
TX3 百兆网口无法驱动？

### ISSUE THREAD

**Issue by EastWoodYang** [ophub/amlogic-s9xxx-armbian#692]
![image](https://user-images.githubusercontent.com/9335046/201238713-60c5dc36-b8e5-47af-8c39-a095a3bd0aa4.png)
![6be14a11c92935e240c5a679d871274](https://user-images.githubusercontent.com/9335046/201239085-635ab735-8bfa-4000-916d-a3bbeab1fcc0.jpg)
![8a69087262e13a89474d38e4ab4d64c](https://user-images.githubusercontent.com/9335046/201239104-363660e0-57a9-4720-b25e-2d6fd344570b.jpg)
大哥，帮忙给看看

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/97985b163f8ec72cd70bb76e30be3cda97e71577/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L106

**Comment by EastWoodYang** [comment]
我用的就是meson-sm1-tx3-bz.dtb。。。之前记得几个月前是好的，早上刷你打的最新包，晚点回去再检查看看

**Comment by EastWoodYang** [comment]
我用的就是meson-sm1-tx3-bz.dtb。。。之前记得几个月前是好的，早上刷你打的最新包
![image](https://user-images.githubusercontent.com/9335046/201299507-50125a4a-2fbb-4cd8-a469-b85cb1e8f3e2.png)

**Comment by ophub** [comment]
你复制一下/boot/u-boot

**Comment by EastWoodYang** [comment]
好像 还是不行
<img width="464" alt="image" src="https://user-images.githubusercontent.com/9335046/201318958-f718ca88-b522-4a95-a827-314c8f4912f7.png">

**Comment by ophub** [comment]
试试别的系列的内核

**Comment by EastWoodYang** [comment]
试了也不行，我记得你是不是也有一台TX3，百兆还千兆？我之前有台千兆的网口没问题

**Comment by ophub** [comment]
我是千兆的用着挺好的

**Comment by ophub** [comment]
试试5.4的老内核

**Comment by EastWoodYang** [comment]
也试了 都不行

**Comment by franciscofsales** [comment]
I also have this issue. same exact config as @EastWoodYang

**Comment by franciscofsales** [comment]
any idea @ophub ? I've tried multiple kernel versions and multiple dtbs.. couldn't get ethernet to work always the same errors from https://user-images.githubusercontent.com/9335046/201239085-635ab735-8bfa-4000-916d-a3bbeab1fcc0.jpg

**Comment by franciscofsales** [comment]
bumpb
