### ISSUE TITLE
新魔百和M301A-S905L2B,无wifi驱动

### ISSUE THREAD

**Issue by YunCmd** [ophub/amlogic-s9xxx-armbian#693]
大佬你好，我是新魔百和M301A盒子JL代工的，S905L2B的SOC,无线芯片是MT7668，刷的Armbian_22.11.0_Aml_s905l3a_jammy_5.15.77_server，使用DTB： meson-gxl-s905l2-x7-5g.dtb启动的，目前有线网络连接正常，但是armbian-config里面没有无线wifi选项，安装了BT蓝牙驱动之后也没有wifi这个选项，IP里面没有wlan0 这个网口，请问我这个改怎么解决无线驱动的问题呀？

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/mediatek/mt76

https://www.spinics.net/lists/linux-wireless/msg204408.html

https://forum.armbian.com/topic/13903-driver-for-mediatek-mt7668-wanted/

当前内核中没有这个驱动。据说在5.7.y中支持蓝牙但不支持wifi
