### ISSUE TITLE
外接一个硬盘，开机时无法进入系统

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#694]
**Describe the bug**
        我的机器情况是这样的：Armbian系统安装在U盘使用，然后第二个usb口使用绿联的易驱线外接了一个机械硬盘，硬盘的格式为exfat，挂载在/mnt下的一个目录。并且在fastab文件里设置了自动挂载。
        当我不接机械硬盘时，一切使用正常。当Armbian正常运行时，插入硬盘后，可以正常挂载使用。但是，当我在连接硬盘后并且重启时，Armbian系统不能被顺利引导。HDMI画面下重启时没有出现花屏，也完全没有跑码，屏幕一直处于灰屏状态，不能进入系统。拔掉硬盘再次重启就能进入系统。
        据我观察，它似乎是在第二个usb口的机械硬盘里找引导分区，从而导致无法启动。
        麻烦大佬帮我看看是怎么回事。如果需要，我可以提供ttl下的启动日志。

**Armbian Version**
 - Kernel Version: [5.10.149]
 - Release: [bullseye]
 - Edition: [server]

**Device (please complete the following information):**
 - SOC: [s905l3a]
 - Brand: [魔百盒]
 - Model [b863av3.2-m]

**Comment by seacatwu** [comment]
设备usb口有问题，启动时无法识别，必须重新插拔才行。我也遇到差不多的问题

**Comment by Haaooo** [comment]
> 

感觉不是接口问题，因为我的装Armbian的U盘插到这个口，是可以正常启动的

**Comment by allonmymind** [comment]
> > 
> 
> 感觉不是接口问题，因为我的装Armbian的U盘插到这个口，是可以正常启动的

如果你的盒子是5v的，那绝对是供电问题。有些盒子写的5v电压输入，其实需要5.2v的电源才能带动移动硬盘。可以试试

**Comment by Haaooo** [comment]
可是我的硬盘是3.5寸独立供电的

**Comment by allonmymind** [comment]
> 可是我的硬盘是3.5寸独立供电的

你的盒子如果是5v的你就尽管试试，我也用独立供电的硬盘盒试过，没卵用。换5.2v电源立竿见影

**Comment by Haaooo** [comment]
好，我先试试再说，感谢你的建议

**Comment by seacatwu** [comment]
找到一个网贴，说可能是移动硬盘芯片问题。ns芯片可以，我买了个飚王的，启动就可以识别，但是原来斐讯h1就无法识别。

**Comment by allonmymind** [comment]
> 找到一个网贴，说可能是移动硬盘芯片问题。ns芯片可以，我买了个飚王的，启动就可以识别，但是原来斐讯h1就无法识别。

他说的是开机后再接入能识别，显然不是主控问题，jmf asm主控我都试过能识别

**Comment by seacatwu** [comment]
> > 找到一个网贴，说可能是移动硬盘芯片问题。ns芯片可以，我买了个飚王的，启动就可以识别，但是原来斐讯h1就无法识别。
> 
> 他说的是开机后再接入能识别，显然不是主控问题，jmf asm主控我都试过能识别

并不是，我换了飚王的，大概率重启能直接识别。但是斐讯h1，重启完全没法识别，重新插入就可以识别
