### ISSUE TITLE
S905L3  e900v22d应该用l3a的包么，引导不了，请问该如何处理还是没有支持这个芯片

### ISSUE THREAD

**Issue by milosz20222** [ophub/amlogic-s9xxx-armbian#695]
### Before You Open ISSUE, Make Sure You have Read [Armbian Firmware Instructions](https://github.com/ophub/amlogic-s9xxx-armbian#armbian-firmware-instructions) and [Documentation](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Armbian Version**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]
 - Edition: [e.g. server]

**Device (please complete the following information):**
 - SOC: [e.g. S095x3]
 - Brand: [e.g. Beelink]
 - Model [e.g. mini g1]

**Additional context**

**Comment by ophub** [comment]
你贴子正文写的什么

**Comment by milosz20222** [comment]
我的标题就是问题，目前没法引导，或者说我该修改什么，S905L3具体该用那个包，我都没法从安卓进入armbian引导系统，感谢o大这么晚还在工作

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/README.cn.md

看12.4

**Comment by milosz20222** [comment]
这一步我已经做了，但是系统没法从u盘引导，我怀疑是S905L3这个芯片是否不支持

**Comment by ophub** [comment]
https://docs.qq.com/doc/DWFprWWxZa290VXNk

**Comment by milosz20222** [comment]
继续折腾，我在不停的换包和dtb文件，目前的主要问题是安卓下adb命令重启后，不引导armbian，没有花屏没有跑马灯

**Comment by ophub** [comment]
默认不用换。
仔细看看文档，有些人是刷了其他安卓系统
