### ISSUE TITLE
Wrong CPU temp

### ISSUE THREAD

**Issue by kobzzon** [ophub/amlogic-s9xxx-armbian#696]
Device Information |
 - SOC: [e.g. S905]
 - Model [e.g. UHD300]

**Armbian Version | 
 - Kernel Version: [e.g. 5.15.77]
 - Release: [e.g. flippy]

**Describe the bug | 
Showing wrong CPU Temp in terminal and in klipper firmware (-1 degree Celsius is displayed)
![image](https://user-images.githubusercontent.com/95584234/201495656-39f5fa7a-532e-4c40-ab47-5b9537106b06.jpeg)

**Comment by ophub** [comment]
Re-download the firmware and reinstall. There is a problem with your system.

**Comment by kobzzon** [comment]
> Re-download the firmware and reinstall. There is a problem with your system.

the problem is not solved![image](https://user-images.githubusercontent.com/95584234/201507896-229c0897-3f76-43f6-8dd1-aa1a3873a204.png)

**Comment by ophub** [comment]
Does the previous permission issue still exist?

Execute `armbian-fix`

look at the results

**Comment by kobzzon** [comment]
> Does the previous permission issue still exist?
> 
> 
> 
> Execute `armbian-fix`
> 
> 
> 
> look at the results

![image](https://user-images.githubusercontent.com/95584234/201508676-da2558dd-7484-4e0a-83f2-fed47e10d1d2.png)

**Comment by ophub** [comment]
`sudo armbian-fix`

**Comment by ophub** [comment]
```
sensors | grep -Eo '\+[0-9]+.+C' | sed ':a;N;$!ba;s/\n/ /g;s/+//g'

awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/hwmon/hwmon0/temp1_input


awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp
```

**Comment by kobzzon** [comment]
> Non-root users need to add `sudo` when executing system operation commands
> 
> `sudo armbian-fix`
![sudo armbian-fix](https://user-images.githubusercontent.com/95584234/201510818-ccb633bc-b2f7-4054-a5da-dee3e5f690b3.jpg)

**Comment by kobzzon** [comment]
> Execute these 3 commands separately to see which one can be used
> 
> ```
> sensors | grep -Eo '\+[0-9]+.+C' | sed ':a;N;$!ba;s/\n/ /g;s/+//g'
> 
> 
> awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/hwmon/hwmon0/temp1_input
> 
> 
> awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp
> ```

![3 commands](https://user-images.githubusercontent.com/95584234/201510825-95ade9f3-9a93-4891-b061-ead37c6695c3.jpg)

**Comment by ophub** [comment]
add your user to sudo group

**Comment by kobzzon** [comment]
> sensors | grep -Eo '\+[0-9]+.+C' | sed ':a;N;$!ba;s/\n/ /g;s/+//g'

![sensor](https://user-images.githubusercontent.com/95584234/201511931-64ceb6ce-e0e8-4253-bb2a-bbf558f52d65.jpg)

**Comment by ophub** [comment]
Regardless of the temperature issue.
Your basic user permissions are wrong. Unable to use Armbian system normally.

**Comment by ophub** [comment]
/usr/lib/armbian/armbian-allwinner-battery

![Snip20221113_2](https://user-images.githubusercontent.com/68696949/201513369-5b3d1110-f04b-42f2-8b57-86c89582e8a4.png)

**Comment by kobzzon** [comment]
> Regardless of the temperature issue. Your basic user permissions are wrong. Unable to use Armbian system normally.

login as: root
root@192.168.1.3's password:
    _              _   ____  ___   ___  ____
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \
 / ___ \| | | | | | |  ___) \__, | |_| |___) |
/_/   \_\_| |_| |_|_| |____/  /_/ \___/|____/

Welcome to Armbian 22.11.0-trunk Jammy with Linux 5.15.77-flippy-78+o

No end-user support: built from trunk

System load:   27%              Up time:       2 min
Memory usage:  22% of 803M      IP:            192.168.1.243
192.168.1.2 192.168.1.3
CPU temp:      2147483647°C             Usage of /:    48% of 7.0G
RX today:      648.0 KiB

Last login: Sun Nov 13 09:09:19 2022 from 192.168.1.156
root@armbian:~# sudo armbian-fix
01. Fix tmp permissions
02. Fix update-motd.d permissions
03. Fix man permissions
04. Fix man permissions
05. Fix man permissions
06. Fix man permissions
07. Fix sudo permissions
08. Fix sudo permissions
11. Fix polkit-agent-helper-1 permissions
12. Fix sudoers.so permissions
13. Fix sudoers.so permissions
14. Fix polkit-agent-helper-1 permissions
15. Fix custom banner name: Aml Aml S905
19. Clean up local installation packages
20. Delete machine-id
21. Generate /etc/machine-id
22. Generate /var/lib/dbus/machine-id
23. Turn off automatic sleep mode
armbian-fix: Loading finished.
root@armbian:~# ^[[200~sensors | grep -Eo '\+[0-9]+.+C' | sed ':a;N;$!ba;s/\n/ /g;s/+//g'~
-bash: $'\E[200~sensors': command not found
sed: -e expression #1, char 26: unknown option to `s'
root@armbian:~# awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/hwmon/hwmon0/temp1_input
4294967295.0 °Croot@armbian:~# awk '{ printf("%.1f °C", $0 / 1000) }' /sys/class/thermal/thermal_zone0/temp
-1.0 °Croot@armbian:~# sudo -i
root@armbian:~# sudo usermod -aG sudo root
root@armbian:~# sudo usermod -aG sudo klipper
root@armbian:~# sudo apt-get update
Get:1 http://ports.ubuntu.com jammy InRelease [270 kB]
Get:2 http://ports.ubuntu.com jammy-security InRelease [110 kB]
Get:3 http://ports.ubuntu.com jammy-updates InRelease [114 kB]
Get:4 http://ports.ubuntu.com jammy-backports InRelease [99.8 kB]
Get:5 http://ports.ubuntu.com jammy/universe arm64 Packages [17.2 MB]
Get:6 http://ports.ubuntu.com jammy/main arm64 Packages [1,758 kB]
Get:7 http://ports.ubuntu.com jammy/multiverse arm64 Packages [224 kB]
Get:8 http://ports.ubuntu.com jammy/restricted armhf Packages [13.3 kB]
Get:9 http://ports.ubuntu.com jammy/restricted arm64 Packages [24.2 kB]
Get:10 http://ports.ubuntu.com jammy/multiverse armhf Packages [199 kB]
Get:11 http://ports.ubuntu.com jammy/universe armhf Packages [16.8 MB]
Get:12 http://ports.ubuntu.com jammy/main armhf Packages [1,701 kB]
Get:13 http://ports.ubuntu.com jammy-security/restricted armhf Packages [9,365 B]
Get:14 http://ports.ubuntu.com jammy-security/universe armhf Packages [472 kB]
Get:15 http://ports.ubuntu.com jammy-security/main armhf Packages [353 kB]
Get:16 http://ports.ubuntu.com jammy-security/universe arm64 Packages [629 kB]
Get:17 http://ports.ubuntu.com jammy-security/restricted arm64 Packages [189 kB]
Get:18 http://ports.ubuntu.com jammy-security/main arm64 Packages [526 kB]
Get:19 http://ports.ubuntu.com jammy-security/multiverse armhf Packages [594 B]
Get:20 http://ports.ubuntu.com jammy-updates/main arm64 Packages [822 kB]
Ign:20 http://ports.ubuntu.com jammy-updates/main arm64 Packages
Get:21 http://ports.ubuntu.com jammy-updates/universe arm64 Packages [811 kB]
Get:22 http://ports.ubuntu.com jammy-updates/multiverse arm64 Packages [2,308 B]
Get:23 http://ports.ubuntu.com jammy-updates/universe armhf Packages [653 kB]
Get:24 http://ports.ubuntu.com jammy-updates/restricted armhf Packages [9,747 B]
Get:25 http://ports.ubuntu.com jammy-updates/main armhf Packages [620 kB]
Get:26 http://ports.ubuntu.com jammy-updates/restricted arm64 Packages [202 kB]
Get:27 http://ports.ubuntu.com jammy-updates/multiverse armhf Packages [1,334 B]
Get:28 http://ports.ubuntu.com jammy-backports/main armhf Packages [3,169 B]
Get:29 http://ports.ubuntu.com jammy-backports/main arm64 Packages [3,184 B]
Get:30 http://ports.ubuntu.com jammy-backports/universe arm64 Packages [7,261 B]
Get:31 http://ports.ubuntu.com jammy-backports/universe armhf Packages [7,272 B]
Get:20 http://ports.ubuntu.com jammy-updates/main arm64 Packages [822 kB]
Fetched 43.2 MB in 1min 23s (520 kB/s)
Reading package lists... Done
root@armbian:~# sudo apt-get install -y lm-sensors
Reading package lists... Done
Building dependency tree... Done
Suggested packages:
  fancontrol read-edid
The following NEW packages will be installed:
  lm-sensors
0 upgraded, 1 newly installed, 0 to remove and 1 not upgraded.
Need to get 81.8 kB of archives.
After this operation, 366 kB of additional disk space will be used.
Get:1 http://ports.ubuntu.com jammy/universe arm64 lm-sensors arm64 1:3.6.0-7ubuntu1 [81.8 kB]
Fetched 81.8 kB in 1s (60.7 kB/s)
Selecting previously unselected package lm-sensors.
(Reading database ... 62654 files and directories currently installed.)
Preparing to unpack .../lm-sensors_1%3a3.6.0-7ubuntu1_arm64.deb ...
Unpacking lm-sensors (1:3.6.0-7ubuntu1) ...
Setting up lm-sensors (1:3.6.0-7ubuntu1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/lm-sensors.service → /lib/systemd/system/lm-sensors.service.
Processing triggers for man-db (2.10.2-1) ...
root@armbian:~# sensors | grep -Eo '\+[0-9]+.+C' | sed ':a;N;$!ba;s/\n/ /g;s/+//g'
+4294967295.0°C
root@armbian:~#

**Comment by ophub** [comment]
sudo vi /usr/lib/armbian/armbian-allwinner-battery


```
#read raw_temp </etc/armbianmonitor/datasources/soctemp 2>/dev/null
raw_tmmp="$(sensors 2>/dev/null | grep -Eo '\+[0-9]+' | awk '{print $1}' | head -n1 | sed -e 's|+||')"
```

**Comment by kobzzon** [comment]
"/usr/lib/armbian/armbian-allwinner-battery" [readonly]

**Comment by ophub** [comment]
sudo …

**Comment by kobzzon** [comment]
> armbian-allwinner-battery

![CPU temp LOST](https://user-images.githubusercontent.com/95584234/201834649-58e88151-4045-4f76-a4cf-da17b62af1e1.jpg)
![armbian-allwinner-battery](https://user-images.githubusercontent.com/95584234/201834675-8c9407f7-186f-407f-ab68-769ecfeaf0a0.jpg)

**Comment by ophub** [comment]
`sensors`

**Comment by ophub** [comment]
Log in to armbian with ssh, copy and paste the following three lines of commands, and press Enter to fix the temperature display error.

```
temp_file="/usr/lib/armbian/armbian-allwinner-battery"
insert_line="$(cat ${temp_file} | grep -n 'CPU_TEMP_OFFSET' | awk -F':' '{print $1}')"
sed -i "${insert_line}i\        [[ \"\$(echo \${board_temp} | awk -F'.' '{print \$1}' | wc -c)\" -gt \"3\" ]] && board_temp=\${board_temp:0:2}" ${temp_file}
```

**Comment by kobzzon** [comment]
> Use ssh to log in to armbian, copy and paste each line of command separately, and fix the temperature display error.
> 
> ```
> temp_file="/usr/lib/armbian/armbian-allwinner-battery"
> insert_line="$(cat ${temp_file} | grep -n 'CPU_TEMP_OFFSET' | awk -F':' '{print $1}')"
> sed -i "${insert_line}i\        [[ \"\$(echo \${board_temp} | awk -F'.' '{print \$1}' | wc -c)\" -gt \"3\" ]] && board_temp=\${board_temp:0:2}" ${temp_file}
> ```
> 
> ![Snip20221121_2](https://user-images.githubusercontent.com/68696949/203059742-a670db81-57d0-4a9f-a54f-bb3e9c0d1050.png)

It's works! Great! Many thx!!!
![image](https://user-images.githubusercontent.com/95584234/203277632-4c4496da-31d4-46bb-84da-f661de569e7c.png)

**Comment by ophub** [comment]
ok

**Comment by kobzzon** [comment]
> ok

But in Fluidd displaying wrong![image](https://user-images.githubusercontent.com/95584234/203297326-a036b8a1-a1b1-4a74-8ffd-5c667cb20393.jpeg)

**Comment by ophub** [comment]
I don't know about other software

**Comment by kobzzon** [comment]
> I don't know about other software

And didn't work any webcams ![image](https://user-images.githubusercontent.com/95584234/203309309-e006cb1a-13c9-4c57-ab81-8d279234c73b.png)

**Comment by kobzzon** [comment]
> I don't know about other software

From Fluidd issue: "Assuming you are using a sensor_type: temperature_host in your Klipper printer.cfg, you will most likely have to override the sensor_path as Klipper by default will use /sys/class/thermal/thermal_zone0/temp but that doesn't seem to be available in your system.

You can confirm by SSH'ing and then cat /sys/class/thermal/thermal_zone0/temp and checking the result"

**Comment by ophub** [comment]
For the use of third-party software, go to the corresponding website for consultation, I don’t know how to use it

**Comment by kobzzon** [comment]
> For the use of third-party software, go to the corresponding website for consultation, I don’t know how to use it

атв how about permission cameras?
