### ISSUE TITLE
Unable to install v4l2loopback-dkms package

### ISSUE THREAD

**Issue by rarguelloF** [ophub/amlogic-s9xxx-armbian#697]
Hi! I'm trying to install the `v4l2loopback-dkms` package (https://github.com/umlaeute/v4l2loopback), since it's a requirement to install OBS studio (https://obsproject.com/wiki/install-instructions#linux).

The error I'm getting is the following:

```
> apt install v4l2loopback-dkms
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
v4l2loopback-dkms is already the newest version (0.12.5-1ubuntu5).
0 upgraded, 0 newly installed, 0 to remove and 7 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up v4l2loopback-dkms (0.12.5-1ubuntu5) ...
Removing old v4l2loopback-0.12.5 DKMS files...
Deleting module v4l2loopback-0.12.5 completely from the DKMS tree.
Loading new v4l2loopback-0.12.5 DKMS files...
Building for 5.15.77-flippy-78+o
Building initial module for 5.15.77-flippy-78+o
Error! Bad return status for module build on kernel: 5.15.77-flippy-78+o (aarch64)
Consult /var/lib/dkms/v4l2loopback/0.12.5/build/make.log for more information.
dpkg: error processing package v4l2loopback-dkms (--configure):
 installed v4l2loopback-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 v4l2loopback-dkms
```

The contents of `/var/lib/dkms/v4l2loopback/0.12.5/build/make.log` are the following:

```
> cat /var/lib/dkms/v4l2loopback/0.12.5/build/make.log
DKMS make.log for v4l2loopback-0.12.5 for kernel 5.15.77-flippy-78+o (aarch64)
Sun Nov 13 05:44:14 PM JST 2022
Building v4l2-loopback driver...
make -C /lib/modules/5.15.77-flippy-78+o/build M=/var/lib/dkms/v4l2loopback/0.12.5/build modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.77-flippy-78+o'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: Ubuntu clang version 14.0.0-1ubuntu1
  You are using:           gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
  CC [M]  /var/lib/dkms/v4l2loopback/0.12.5/build/v4l2loopback.o
gcc: error: unrecognized command-line option '-Qunused-arguments'
gcc: error: unrecognized command-line option '-mno-global-merge'
gcc: error: unrecognized command-line option '-fsplit-lto-unit'
make[2]: *** [scripts/Makefile.build:289: /var/lib/dkms/v4l2loopback/0.12.5/build/v4l2loopback.o] Error 1
make[1]: *** [Makefile:1902: /var/lib/dkms/v4l2loopback/0.12.5/build] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.77-flippy-78+o'
make: *** [Makefile:43: v4l2loopback.ko] Error 2
```

My device is `A95XF3-Air` and the OS I'm using is `Armbian 22.11.0-trunk Jammy with Linux 5.15.77-flippy-78+o`.

Thanks in advance 🙏

**Comment by 7Ji** [comment]
`-Qunused-arguments`, `-mno-global-merge` and `-fsplit-lto-unit` are all flags that's supported in `clang`, not `gcc`, these flags were set when compiling the kernel, and kept in the source file, then copied as headers to the target system (the one you're running) under `/usr/src/linux-headers-[uname]`, and since the compiler to compile the kernel was `clang` these `clang` flags were carries over.

You can either switch to `clang` as the C compiler, or edit `Makefile` and other corresponding files under `/usr/src/linux-headers-5.15.77-flippy-78+o` to change the options

**Comment by alvaroga91** [comment]
Indeed, compiling v4l2loopback with clang did the trick. 

In an Ubuntu 2204 system the command was `make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC=clang LD=ld.lld LLVM=1 LLVM_IAS=1`

**Comment by rarguelloF** [comment]
@7Ji @alvaroga91 Thanks for your help!

I tried editing the `Makefile` used by `v4l2loopback` to use `clang` as compiler, and ran `make` but got a different error. I don't have the logs here, but I think the error was `error while loading shared libraries: libc.so.6: cannot open shared object file`.

Also, is there any possibility to find a solution for the issue for the `apt install v4l2loopback-dkms` command to work on the device without involving recompiling the kernel modules outside the device? Since other users might also face this issue in the future.

Thanks!
