### ISSUE TITLE
Armbian 刷入 emmc 以后，还能从U盘启动 Emuelec 吗？

### ISSUE THREAD

**Issue by KinShin** [ophub/amlogic-s9xxx-armbian#698]
在安卓系统下可以启动U盘里的 Emuelec。
请问把 Armbian 刷入 emmc 后，还能从U盘启动 Emuelec 吗？

**Comment by ophub** [comment]
不了解Emuelec。
U盘可以启动Armbian

**Comment by 7Ji** [comment]
在不破坏Armbian引导能力的情况下不可以。

EmuELEC/CoreELEC的启动脚本设置的启动流程和Armbian/OpenWrt/ArchLinux/Manajaro等的均不一致，通过`cfgload`等加载配置，并直接加载内核，无二阶段u-boot，无initrd，而不是像其他项目一样用`s905_autoscript`或者`emmc_autoscript`。要在两者之间切换，必须进入升级模式以重新加载另一者的`aml_autosript`来设置启动相关的环境。

或者，你可以自己写一个能让两者并存的`bootcmd`，我的任何设备用的都不是发行版自带的`aml_autoscript`设置的环境变量，相关原理可以在[我的博客](https://7ji.github.io/embedded/2022/11/11/amlogic-booting.html)上了解

**Comment by KinShin** [comment]
> 不了解Emuelec。
> U盘可以启动Armbian

感谢大佬解答 🙏🏻

**Comment by KinShin** [comment]
> 在不破坏Armbian引导能力的情况下不可以。
> 
> EmuELEC/CoreELEC的启动脚本设置的启动流程和Armbian/OpenWrt/ArchLinux/Manajaro等的均不一致，通过`cfgload`等加载配置，并直接加载内核，无二阶段u-boot，无initrd，而不是像其他项目一样用`s905_autoscript`或者`emmc_autoscript`。要在两者之间切换，必须进入升级模式以重新加载另一者的`aml_autosript`来设置启动相关的环境。
> 
> 或者，你可以自己写一个能让两者并存的`bootcmd`，我的任何设备用的都不是发行版自带的`aml_autoscript`设置的环境变量，相关原理可以在[我的博客](https://7ji.github.io/embedded/2022/11/11/amlogic-booting.html)上了解

感谢回复，回去就拜读您的博客。

**Comment by xcray** [comment]
> 在不破坏Armbian引导能力的情况下不可以。
> 
> EmuELEC/CoreELEC的启动脚本设置的启动流程和Armbian/OpenWrt/ArchLinux/Manajaro等的均不一致，通过`cfgload`等加载配置，并直接加载内核，无二阶段u-boot，无initrd，而不是像其他项目一样用`s905_autoscript`或者`emmc_autoscript`。要在两者之间切换，必须进入升级模式以重新加载另一者的`aml_autosript`来设置启动相关的环境。
> 
> 或者，你可以自己写一个能让两者并存的`bootcmd`，我的任何设备用的都不是发行版自带的`aml_autoscript`设置的环境变量，相关原理可以在[我的博客](https://7ji.github.io/embedded/2022/11/11/amlogic-booting.html)上了解

感谢！终于有明白人把启动过程、u-boot等说明白了，虽然我看了一遍还没看太明白，收藏慢慢学习！

**Comment by ophub** [comment]
像这种图文并茂，细致入微，深入浅出地介绍原理和实战操作的文章不多，收藏点赞慢慢理解，多多请教。
