### ISSUE TITLE
缺少dm-cache模块

### ISSUE THREAD

**Issue by zvzl** [ophub/amlogic-s9xxx-armbian#699]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S095x3
 - Model: HK1

**Armbian Version | 系统版本**
 - Kernel Version:  5.4.224
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
使用lvm（详见[此链接](https://wiki.archlinux.org/title/LVM#Create_cache)）用ssd加速机械硬盘时，无法创建，提示缺少dm-cache模块，如下图
![image](https://user-images.githubusercontent.com/84430227/202159435-df991861-9d36-4234-85c4-862c7c84ba46.png)

看网上说可以用`lsmod | grep dm`命令查看是否支持，如果输出中有dm-cache字样则支持.下图是我的输出（没有dm-cache字样）
![image](https://user-images.githubusercontent.com/84430227/202160284-e5d39b3f-6311-43f6-a5ca-ac7cdb9a55be.png)

请问如何自行编译带有dm-cache的内核呢？这个模块挺常用的，可以加入到以后的内核中吗？

**Comment by ophub** [comment]
先创建cachevol卷，才能附加。

**Comment by ophub** [comment]
你执行的是附加命令，你先创建命令看看

**Comment by zvzl** [comment]
![image](https://user-images.githubusercontent.com/84430227/202179990-ce5fa016-2626-4407-954d-204960a1321a.png)
第二步不行。

**Comment by ophub** [comment]
我看看第一行的反应

**Comment by zvzl** [comment]
![image](https://user-images.githubusercontent.com/84430227/202181363-f79ca71f-4157-4afa-a172-d09fdb3c7004.png)

**Comment by 7Ji** [comment]
内核配置里只启用了`DM_WRITECACHE=m`，没有启用`DM_CACHE`，前者不依赖于后者，所以`DM_CACHE`没有被编译。6.0.8里也是这样
```
# zcat /proc/config.gz | grep CONFIG_DM | grep CACHE
# CONFIG_DM_CACHE is not set
CONFIG_DM_WRITECACHE=m
```
```
# uname -a
Linux bestv7Ji 6.0.8-flippy-78+ #31 SMP Fri Nov 11 02:49:04 CST 2022 aarch64 GNU/Linux
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/2a5c35d5953c6661aadaa22b69c9a5029310006b

内核模板里都启用了。
5.4和5.10的以后更新自带。
5.15/6.0我是转存f大编译分享的内核，我刚才给他留言了，添加这2个选项。

**Comment by zvzl** [comment]
@ophub 可以手动触发一次编译吗

**Comment by ophub** [comment]
你fork，随时同步，随时自主编译，你是要哪个系列的内核？

**Comment by zvzl** [comment]
5.4.**

**Comment by ophub** [comment]
开始了，估计得1个小时，我本地给你编译一个吧，10分钟
稍等我上传到这个留言里。

**Comment by zvzl** [comment]
好的，谢谢了

**Comment by ophub** [comment]
https://github.com/ophub/kernel/commit/5188d72758b8e9562d530a2b23bfcede2dc4481a

因为不能同内核版本更新，所以你需要先更新为非5.4.224的其他版本，比如`armbian-update 5.4.223`
然后才可以更新替换为新编译的224的内核（我更新到内核仓库了）
你执行完更新5.4.223重启后，再执行armbian-update就自动更新到最新的224内核了。

**Comment by zvzl** [comment]
我是手动更新，不用armbian-update。可以同内核版本更新吗

**Comment by ophub** [comment]
![Snip20221116_3](https://user-images.githubusercontent.com/68696949/202194989-a0034de6-9252-44e2-8515-e5bf5a90353b.png)

**Comment by zvzl** [comment]
问题解决了

**Comment by zvzl** [comment]
请问我想编译5.4.181左右版本的内核如何操作？已经找到了flippy的历史源码https://github.com/unifreq/linux-5.4.y/tree/6cd333c654e2bb4f9f423487db322d4de96f72be

**Comment by ophub** [comment]
```
git clone https://github.com/unifreq/linux-5.4.y
git reset --hard 目标commit
```

**Comment by zvzl** [comment]
要是这个文件https://github.com/ophub/amlogic-s9xxx-openwrt/blob/main/.github/workflows/compile-kernel.yml
kernel.repo这一行可以填repo地址就好了，现在好像只能在kernel.org和flippy之间选
![image](https://user-images.githubusercontent.com/84430227/202854029-d68f2d4a-e97a-4187-af2d-c17a46fa0653.png)

**Comment by zvzl** [comment]
报错了
![image](https://user-images.githubusercontent.com/84430227/202856186-fd10f13f-0c3a-4515-937e-e8bc4c9deea8.png)

**Comment by zvzl** [comment]
已解决，谢谢帮助
