### ISSUE TITLE
hk1-box用这个镜像为啥网卡都成百兆了

### ISSUE THREAD

**Issue by devilcell** [ophub/amlogic-s9xxx-armbian#7]
hk1-box用这个镜像为啥网卡都成百兆了，网卡驱动有问题吗，能修复吗

**Comment by ophub** [comment]
Write emmc with the `armbian-install` command to gigabit

**Comment by fooy** [comment]
flippy 提到的，安转u-boot可以切换到千兆https://www.right.com.cn/forum/thread-4055451-1-1.html
