### ISSUE TITLE
Sound not working on S905X3 and S905W

### ISSUE THREAD

**Issue by saurabhjn** [ophub/amlogic-s9xxx-armbian#70]
Hi! First of all I want to thank you for this excellent project. After balbes150 stopped working on Armbian for Amlogic TV Box, my life became very hard. I am thankful for the releases you have made. I was able to run kernel 5.15.13 on an S905X3 TV box that I have, and kernel 5.4.170 on an S905W based board.

In both boards, sound is not working. alsamixer shows that there are no sound devices. How can I configure these to work?

Also, in S905W board, mouse and keyboard were not working. Basically no /dev/input/eventX device files are getting created at all, so X is unable to use libinput. Any pointers on how I can fix that? I am using Ubuntu 20.04.03 as the base OS.

Thanks again for the excellent project. Now that I have two boards working, do let me know if there any contribution I can make. If there is something to be tested, I can do it.

**Comment by ophub** [comment]
What device are you on? What chip is the sound card? Do you know which driver is missing? Do you know how to select your sound card driver from compiling the kernel?

There are instructions for compiling the kernel [compile-kernel](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel) in the warehouse. It is recommended that you refer to the instructions of the device, compile the custom kernel according to your model, and integrate the various drivers you need.
After compiling, you can use the kernel update script [armbian-update](https://github.com/ophub/amlogic-s9xxx-armbian#update-armbian-kernel) to replace.

**Comment by eonegin83** [comment]
> Привет! Прежде всего, я хочу поблагодарить вас за этот прекрасный проект. После того, как balbes150 перестал работать над Armbian для Amlogic TV Box, моя жизнь стала очень тяжелой. Я благодарен за выпуски, которые вы сделали. Мне удалось запустить ядро ​​5.15.13 на телевизионной приставке S905X3, которая у меня есть, и ядро ​​5.4.170 на плате на базе S905W.
> 
> В обеих платах не работает звук. alsamixer показывает, что звуковых устройств нет. Как я могу настроить их для работы?
> 
> Также на плате S905W не работали мышь и клавиатура. По сути, файлы устройств /dev/input/eventX вообще не создаются, поэтому X не может использовать libinput. Любые указатели на то, как я могу это исправить? Я использую Ubuntu 20.04.03 в качестве базовой ОС.
> 
> Еще раз спасибо за отличный проект. Теперь, когда у меня работают две доски, дайте мне знать, могу ли я внести какой-то вклад. Если есть что проверить, могу.

Привет, я до этого использую x96max+ с прошивкой balbes150, нет поддержки wifi, Bluetooth  и звуковой карты, как обстоят дела с этой прошивкой, скомпилировали ядро с поддержкой аппаратной части тв бокса? Стоит пробывать переходить на эту прошивку?

**Comment by ophub** [comment]
This firmware contains wireless for x96max+ (s905x3)

**Comment by Evgeniy-18** [comment]
> Эта прошивка имеет беспроводную связь для x96max+ (s905x3)

Спасибо за ответ, какую сборку с каким ядром мне использовать?

**Comment by saurabhjn** [comment]
> What device are you on?

The S905X3 is the Oranth TX3 http://oranth.com/product-3661-40975.html
The S905W is most likely the Elebao TX3 mini https://elebaotec.en.alibaba.com/product/62428264915-805948870/Hot_selling_android_tv_box_TX3_mini_2gb_16gb_S905W_quad_core_android_9_0_smart_TV_box_better_than_X96_mini_set_top_box.html

> What chip is the sound card?

I looked everywhere on the S905X3 board, but did not find a separate audio chip. Looks like sound is integrated into the SoC.

> Do you know which driver is missing? Do you know how to select your sound card driver from compiling the kernel?

I do not know what driver is missing. Yes, I do have experience compiling a custom kernel.

> There are instructions for compiling the kernel [compile-kernel](https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel) in the repo. It is recommended that you refer to the instructions of the device, compile the custom kernel according to your model, and integrate the various drivers you need. After compiling, you can use the kernel update script [armbian-update](https://github.com/ophub/amlogic-s9xxx-armbian#update-armbian-kernel) to replace.

Noted. Let me figure out which audio drivers I need, and then compile a custom kernel.

> PCM Sound support by pulpoff: #36

Thanks. I will add this patch to the kernel when compiling.

**Comment by saurabhjn** [comment]
> Привет, я до этого использую x96max+ с прошивкой balbes150, нет поддержки wifi, Bluetooth и звуковой карты, как обстоят дела с этой прошивкой, скомпилировали ядро с поддержкой аппаратной части тв бокса? Стоит пробывать переходить на эту прошивку?

WiFi definitely works on the S905X3. The chip on my board is the SP6330-X. I did not check Bluetooth - will check when I play with the board next. Sound did not work - that is what this issue was about.

**Comment by eonegin83** [comment]
> > Привет, я до этого использовал x96max+ с прошивкой balbes150, нет поддержки Wi-Fi, Bluetooth и звуковой карты, как обстоят дела с этой прошивкой, скомпилированы ядра с поддержкой аппаратной части тв бокса? Стоит пробывать переходить на эту прошивку?
> 
> WiFi определенно работает на S905X3. Чип на моей плате - SP6330-X. Блютус не проверял - проверю, когда поиграюсь с платой в следующий раз. Звук не работал - об этом и был этот вопрос.

Подскажите как прошить приставку. Прошивку делал по инструкции http://mrbluecoat.blogspot.com/2020/10/install-linux-on-x96-max-x96-max.html, чтобы прошить с этого сайта, такая же последовательность?

**Comment by saurabhjn** [comment]
@ophub I am delighted to let you know that with the latest releases you uploaded on https://github.com/ophub/amlogic-s9xxx-armbian/releases, I was able to resolve sound issues on both my boards. Later I did a build and sound also worked on that. Thank you so much for resolving this issue for me.

**Comment by ophub** [comment]
ok, thanks for the feedback
