### ISSUE TITLE
魔百和M401a 芯片s905L3a 不知道为什么会提示E: The package cache file is corrupted, it has the wrong hash

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#700]
![30c7f76fe7322b9259c6a1bb0e6e41c](https://user-images.githubusercontent.com/96900868/202182710-cec32145-db19-4b13-946c-c21100e558de.png)

**Comment by zvzl** [comment]
什么情况下会出现这个报错？描述详细一些

**Comment by zhuguoqing123** [comment]
![Y@$}36B2W)7IVPRFZFX 4{J](https://user-images.githubusercontent.com/96900868/202227771-4d3a9bfc-e1ee-4014-a39a-b04afec872bd.png)

**Comment by ophub** [comment]
软件包下载不完整。再执行一次

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/202320638-63a91ac9-89e6-4863-9c06-a6df4daa2ac2.png)
更新也不行

**Comment by ophub** [comment]
`sudo rm -rf /var/lib/apt/*`

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/202417617-f239dade-29ec-4807-b6ea-14743ba67c64.png)
换源后新的问题出现了

**Comment by ophub** [comment]
sudo apt-get autoclean
sudo apt-get autoremove

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/202472416-e3fac47a-be53-4315-ab4c-3092c2c74e60.png)
![image](https://user-images.githubusercontent.com/96900868/202472491-0793b19f-b1a8-4138-a53d-4432bb0b7e4f.png)
o大，操作过问题依旧

**Comment by ophub** [comment]
两条命令，依次复制粘贴回车执行，不要自己敲
```
sudo rm -rf /var/lib/apt/lists/*
sudo apt update
```

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/202481756-16d05f54-f60a-41ca-a05d-0731e72c1f10.png)
![image](https://user-images.githubusercontent.com/96900868/202481847-f0f0ec10-9da6-4296-b3b5-a94bc2163cef.png)
是复制粘贴的，问题依旧

**Comment by zhuguoqing123** [comment]
> 推荐使用一键换源脚本。 https://supermanito.github.io/LinuxMirrors/

试了不行

**Comment by janko888** [comment]
基本上网上提供的此问题的处理方案都是O大上面提供，你可以再重复操作一遍，看是否排查是之前操作时服务器\网络端的问题。如果还是不行，建议重新刷一遍最新版的armbian。

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/208422746-c792d406-8a42-4030-9cf9-aebeff012e4a.png)
试了依旧不行，

**Comment by janko888** [comment]
信息太少了，
cat /etc/ophub-release 发出来看看

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/208643840-d5cf09d1-a0a4-4a8a-bb61-d7f5bc475755.png)

**Comment by janko888** [comment]
> ![image](https://user-images.githubusercontent.com/96900868/208643840-d5cf09d1-a0a4-4a8a-bb61-d7f5bc475755.png)

你/etc/ophub-release显示是debian的bulleyes,为何之前上面apt的源都是ubuntu的？

**Comment by zhuguoqing123** [comment]
上面一开始刷的是jammy，我试试Bulleeys行不行，其实都一样问题
