### ISSUE TITLE
新魔百和M301A刷s905L2无法进入系统

### ISSUE THREAD

**Issue by YunCmd** [ophub/amlogic-s9xxx-armbian#701]
**Device Information | 设备信息**
SOC: s905l2
新魔百和M301A

**Armbian Version | 系统版本**
Armbian_22.11.0_Aml_s905l2_jammy_5.10.154_server_2022.11.16
（换了5.15内核也不行）
**Describe the bug | 问题描述**

无法进入系统，一直卡在139行，问题如图

![46942b1160cbf1ccb6b46b4df2ae0a0](https://user-images.githubusercontent.com/35127657/202326594-4ce6e402-220e-4d65-bbb7-4ae83c10d377.jpg)

**Comment by 84864797** [comment]
S905L2  还是S905L2B？  我的M302A 是S905L2B  刷905X的固件  选M302A的 DTB 可以进。

**Comment by YunCmd** [comment]
> S905L2 还是S905L2B？ 我的M302A 是S905L2B 刷905X的固件 选M302A的 DTB 可以进。

s905L2B  之前刷的s905L3a的包 能正常使用。

**Comment by ophub** [comment]
你试试今天新打包的固件，前天的固件弄错一个网络配置，不知道和这个是否有关。

**Comment by YunCmd** [comment]
> 你试试今天新打包的固件，前天的固件弄错一个网络配置，不知道和这个是否有关。

s905L2的固件和s905L3B 有那些区别呀？

**Comment by ophub** [comment]
u-boot、dtb不同
