### ISSUE TITLE
armbian-software 希望大佬能够增加软件OMV

### ISSUE THREAD

**Issue by tt555-1** [ophub/amlogic-s9xxx-armbian#702]
1、armbian-software 软件列表中没有omv软件，希望大佬能够增加，omv 可以做为nas ，webui 可以更方便的管理linux服务器；
2、我按照armbian上安装omv的方式安装，都会报错，并且安装也不成功。（参考了如下帖子https://blog.csdn.net/u011566766/article/details/125361564）
3、按照armbian-config 上面安装第三方软件，上面有OMV，但也是安装不了的。
3、热切的希望，得到大佬的回复；

**Comment by ophub** [comment]
以前有，删了，我用他官网的脚本安装完，smb报错。
短期内没集成打算。
