### ISSUE TITLE
N1 armbian-swap 1 错误

### ISSUE THREAD

**Issue by lisen9065** [ophub/amlogic-s9xxx-armbian#705]
```
root@armbian:~# armbian-swap 1
[ STEPS ] Welcome to use swap management tool.
[ INFO ] Prepare to create [ 1 ] GiB swap in the [ /mnt/.swap ] directory.
[ STEPS ] Start creating a new swap...
[ INFO ] The swap size is [ 1 ] GiB, partition types is [ ext4 ], Please wait...
/usr/sbin/armbian-swap: line 90: 416353 Killed                  dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1G count=${swap_gb} conv=fsync
mkswap: error: swap area needs to be at least 40 KiB
swapon: /mnt/.swap/swapfile: read swap header failed
[ INFO ] Current swap:
Filename                                Type            Size            Used      Priority
[ SUCCESS ] Created successfully!
root@armbian:~#
```

**Comment by ophub** [comment]
![Snip20221118_1](https://user-images.githubusercontent.com/68696949/202592526-7e3916f9-b6d5-4096-8779-3aca36e9aae1.png)

我测试没问题，你先用armbian-sync同步下最新脚本再试试
再试一遍

**Comment by lisen9065** [comment]
Welcome to Armbian 22.11.0-trunk Bullseye with Linux 5.15.78-flippy-78+o
No end-user support: built from trunk
System load:   53%              Up time:       1 day 18:09
Memory usage:  48% of 1.77G     IP:            172.31.0.1 192.168.2.8
CPU temp:      49°C             Usage of /:    24% of 29G
storage/:      44% of 252M
RX today:      537.9 MiB

root@armbian:~# armbian-sync
[ STEPS ] Start syncing all service scripts...
[ STEPS ] Start syncing operation instruction and service script...
A    /usr/sbin
A    /usr/sbin/armbian-ddbr
A    /usr/sbin/armbian-docker
A    /usr/sbin/armbian-fix
A    /usr/sbin/armbian-install
A    /usr/sbin/armbian-kernel
A    /usr/sbin/armbian-led
A    /usr/sbin/armbian-software
A    /usr/sbin/armbian-swap
A    /usr/sbin/armbian-sync
A    /usr/sbin/armbian-tf
A    /usr/sbin/armbian-update
A    /usr/sbin/balethirq.pl
Exported revision 8085.
[ STEPS ] Start syncing software service script...
A    /usr/share/ophub
A    /usr/share/ophub/armbian-software
A    /usr/share/ophub/armbian-software/201-desktop-chinese-fonts.sh
A    /usr/share/ophub/armbian-software/301-frps.sh
A    /usr/share/ophub/armbian-software/302-frpc.sh
A    /usr/share/ophub/armbian-software/command-desktop.sh
A    /usr/share/ophub/armbian-software/command-docker.sh
A    /usr/share/ophub/armbian-software/command-service.sh
A    /usr/share/ophub/armbian-software/software-command.sh
A    /usr/share/ophub/armbian-software/software-list.conf
Exported revision 8085.
[ STEPS ] Start syncing openvfd service script...
A    /usr/share/openvfd
A    /usr/share/openvfd/conf
A    /usr/share/openvfd/conf/h96max-x3.conf
A    /usr/share/openvfd/conf/hk1-x3.conf
A    /usr/share/openvfd/conf/hk1box.conf
A    /usr/share/openvfd/conf/t95.conf
A    /usr/share/openvfd/conf/t95z-plus.conf
A    /usr/share/openvfd/conf/tx3-mini.conf
A    /usr/share/openvfd/conf/tx3.conf
A    /usr/share/openvfd/conf/tx9-pro.conf
A    /usr/share/openvfd/conf/x92.conf
A    /usr/share/openvfd/conf/x96air.conf
A    /usr/share/openvfd/conf/x96max.conf
A    /usr/share/openvfd/conf/x96maxplus.conf
A    /usr/share/openvfd/vfdservice
Exported revision 8085.
[ SUCCESS ] All service scripts are synchronized successfully.

root@armbian:~# armbian-swap 1
[ STEPS ] Welcome to use swap management tool.
[ INFO ] Prepare to create [ 1 ] GiB swap in the [ /mnt/.swap ] directory.
[ STEPS ] Start creating a new swap...
[ INFO ] The swap size is [ 1 ] GiB, partition types is [ ext4 ], Please wait...
/usr/sbin/armbian-swap: line 90: 2531094 Killed                  dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1G count=${swap_gb} conv=fsync
mkswap: error: swap area needs to be at least 40 KiB
swapon: /mnt/.swap/swapfile: read swap header failed
[ INFO ] Current swap:
Filename                                Type            Size            Used      Priority
[ SUCCESS ] Created successfully!
root@armbian:~#

**Comment by lisen9065** [comment]
armbian-sync后还是不行

**Comment by lisen9065** [comment]
Welcome to Armbian 22.11.0-trunk Bullseye with Linux 5.15.79-flippy-78+o

No end-user support: built from trunk

System load:   5%               Up time:       16 min
Memory usage:  44% of 1.77G     IP:            172.31.0.1 192.168.2.8
CPU temp:      49°C             Usage of /:    24% of 29G
storage/:      40% of 252M
RX today:      238.3 MiB

Last login: Sat Nov 19 04:32:16 2022 from 192.168.2.18
root@armbian:~# armbian-update
[ STEPS ] Ready to update, please wait...
[ INFO ] Custom setting parameters: [  ]
[ STEPS ] Start initializing the environment...
[ INFO ] Set the kernel version name: [  ]
[ INFO ] Set the kernel version branch: [ stable ]
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Current version: 5.15.79, Latest version: 5.15.79
[ FINISH ] Already the latest version, no need to update.
root@armbian:~# armbian-swap 1
[ STEPS ] Welcome to use swap management tool.
[ INFO ] Prepare to create [ 1 ] GiB swap in the [ /mnt/.swap ] directory.
[ STEPS ] Start creating a new swap...
[ INFO ] The swap size is [ 1 ] GiB, partition types is [ ext4 ], Please wait...
/usr/sbin/armbian-swap: line 90: 25672 Killed                  dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1G count=${swap_gb} conv=fsync
Setting up swapspace version 1, size = 34.4 MiB (36102144 bytes)
LABEL=SWAP, UUID=9f679ee5-1048-4b84-8dc6-7f7d22bafbcf
[ INFO ] Current swap:
Filename                                Type            Size            Used      Priority
/mnt/.swap/swapfile                     file            35256           0         -2
[ SUCCESS ] Created successfully!
root@armbian:~#

**Comment by lisen9065** [comment]
已解决，执行armbian-update之后好像就可以了（从5.15.78更新到5.15.79），也可能是半夜连接github好些。
