### ISSUE TITLE
掉盘之终章：给CPU为s905l3a建议（E900V22C/D, CM311-1a-YST, M401A, M411A, UNT403A, UNT413A）

### ISSUE THREAD

**Issue by tingge9527** [ophub/amlogic-s9xxx-armbian#706]
最开始折腾UNT403A的时候有幸找到了O大提供的包，但是折腾了一个月发现不管怎样操作，用armbian跑网心云的容器魔方都会掉盘，因为跑网心云要求24小时稳定，所以掉盘会很麻烦。所以最终我根据网心云交流群里建议刷了CoreELEC系统，这个系统主要的作用是来播放影音的，也可以安装docker，我刷了之后尝试在U盘运行CoreELEC或者写入EMMC都能稳定运行，不会出现掉盘等情况，发帖主要给出下反馈，如果你要求稳定，推荐各位可以使用CoreELEC系统官网：([https://coreelec.org])，另外我目前用的是这个稍微编译了包，[https://github.com/KryptonLee/e900v22c-CoreELEC]这个和官方的包区别在于不用修改dtb,以及遥控器的配置文件也有不用添加。各位按需使用，至于安装教程百度搜索cm311安装CoreELEC就有。

**Comment by zhuguoqing123** [comment]
感谢分享

**Comment by DHinh** [comment]
感谢分享

**Comment by liuyongyong6699** [comment]
> https://github.com/KryptonLee/e900v22c-CoreELEC

cm311-1a可以刷这个嘛

**Comment by wishday** [comment]
我也是，盒子通过易驱线挂个3.5 10T硬盘 ，用的12v 2.5A品牌电源独立供电，电源绝对够，但一天掉盘好几次(/dev目录下盘符从sda2变sdb2又变回sda2)，试了N种方法都没解决，包括刷易驱线固件关闭硬盘自动休眠，hdparm -S 0 /dev/sda2 关闭系统硬盘休眠，fstab uuid挂载，通通无效，继续掉盘。😭

同样易驱线接win系统则一切正常。。。
之前盒子用usb口直接挂2.5 512G硬盘(无独立供电)，一切正常。。。

是armbian和易驱线兼容性有问题么？？

**Comment by tingge9527** [comment]
> 

具体的问题我不清楚，不过我掉盘的情况是跟你一样的，反正你想要解决掉盘只能按照我说的换系统，或者用其他的硬盘盒试试

**Comment by tingge9527** [comment]
> > https://github.com/KryptonLee/e900v22c-CoreELEC
> 
> cm311-1a可以刷这个嘛

可以的，标题上的型号都可以

**Comment by wishday** [comment]
> > 
> 
> 具体的问题我不清楚，不过我掉盘的情况是跟你一样的，反正你想要解决掉盘只能按照我说的换系统，或者用其他的硬盘盒试试

请问你刷CoreELEC之后，试过挂用易驱线2.2T以上的3.5寸机械硬盘吗？稳定用很长时间不会掉盘吗？

**Comment by tingge9527** [comment]
> > > 
> > 
> > 
> > 具体的问题我不清楚，不过我掉盘的情况是跟你一样的，反正你想要解决掉盘只能按照我说的换系统，或者用其他的硬盘盒试试
> 
> 请问你刷CoreELEC之后，试过挂用易驱线2.2T以上的3.5寸机械硬盘吗？稳定用很长时间不会掉盘吗？

没有，只是挂2.5的固态，你如果想要挂3.5的机械那肯定需要独立供电的。我预计是没有问题的。

**Comment by wishday** [comment]
我之前挂2.5寸usb2.0 512G机械硬盘盒，不独立供电，也没掉过盘，换了usb3.0线接3.5寸大硬盘(独立供电)才出现掉盘问题，感觉就是armbian和sata转usb3.0的线或硬盘盒不兼容。
