### ISSUE TITLE
GT King Pro (Rev A) Kernel Panic During Booting Process With Kernel-6.0.9-flippy-78+

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#707]
Hi @ophub,

Device: Beelink GT King Pro (Rev A)
Base Image:  Armbian_22.08.0_Aml_s922x-reva_jammy_5.15.54_server_2022.07.15.img.gz
Deskttop Environment: Gnome 
Software Updated/Upgraded Up To Date
kernel: 6.0.9-flippy-78+
u-boot.ext: u-boot-gtkingpro-rev-a.bin

With kernel-6.0.9-flippy-78+ and also previously with kernel-6.0.5-flippy-78+ it will Kernel Panic during booting process.

![image](https://user-images.githubusercontent.com/75384411/202749732-62ba8a03-df4b-44b1-ad0f-da99595b6b00.png)

Switch back to kernel kernel-5.15.76-flippy-78+o and it boot successfully.

It can boot successfully with kernel-5.15.76-flippy-78+o **with or without** u-boot.ext and runs smoothly. Previously it can boot successfully with kernel-5.19.y-flippy.  Currently facing Kernel Panic with the new kernel-6.0.y-flippy.

Edit: kernel-6.0.9-flippy-78+ or previous 6.0.y-flippy always kernel panic during booting process.  Cannot boot up at all.

**Comment by ophub** [comment]
The kernel panic has been reported. Let's wait for upstream repair. At present, switch to other stable kernels for use.

**Comment by JFLim1** [comment]
> The kernel panic has been reported. Let's wait for upstream repair. At present, switch to other stable kernels for use.

Hi @ophub 

Thanks.  For your info, I tested Armbian kernel-6.0.9-meson64 it can boot up with the chainloader u-boot.ext (u-boot-gtkingpro-rev-a.bin) and seems stable.

Looking forward to the newer kernel-6.0.y-flippy being able to run without kernel panic.

Revert/switch to kernel-5.15.76-flippy-78+o.

**Comment by JFLim1** [comment]
Hi @ophub 

Just tried your new kernel-6.0.10-flippy-79+, it still kernel panic during booting process with the chainloader u-boot.ext.

Any idea what is causing the kernel panic with the u-boot.ext?

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/5b636fb61ebcd17a867b010df5e061a0a5f520fa

He read the plan you sent, and now remove the 5.15.y patch first, you can try 5.15.80 to see if it is normal.

**Comment by JFLim1** [comment]
> [unifreq/linux-5.15.y@5b636fb](https://github.com/unifreq/linux-5.15.y/commit/5b636fb61ebcd17a867b010df5e061a0a5f520fa)
> 
> He read the plan you sent, and now remove the 5.15.y patch first, you can try 5.15.80 to see if it is normal.

Hi @ophub 
Ok, will download 5.15.80-flippy-79+o and try it.  Thank you.

**Comment by JFLim1** [comment]
> [unifreq/linux-5.15.y@5b636fb](https://github.com/unifreq/linux-5.15.y/commit/5b636fb61ebcd17a867b010df5e061a0a5f520fa)
> 
> He read the plan you sent, and now remove the 5.15.y patch first, you can try 5.15.80 to see if it is normal.

Hi @ophub & @unifreq,

The removal of patch works.  Kernel-5.15.80-flippy-79+o now can recognizes Samsung Evo Plus SD Cards so it means it will also be able to boot up on SD Card on my GT King Pro (Rev A) and other Amlogic devices.

Wow, impressed with both your support and fast turn around!

**Comment by JFLim1** [comment]
Hi @ophub

The kernel-5.15.80-flippy-79+o does seem to have GPU hardware acceleration activated for whatever reason.  Panfrost not activated at all on Gnome.

```
$ uname -a
Linux opbu 5.15.80-flippy-79+o #193 SMP PREEMPT Sat Nov 26 20:38:02 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

$ glmark2-es2-wayland
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     Mesa/X.org
    GL_RENDERER:   llvmpipe (LLVM 15.0.2, 128 bits)
    GL_VERSION:    OpenGL ES 3.2 Mesa 22.2.1
=======================================================
[build] use-vbo=false: FPS: 55 FrameTime: 18.182 ms
[build] use-vbo=true:^C FPS: 51 FrameTime: 19.608 ms
=======================================================
                                  glmark2 Score: 53 
=======================================================
```

**Comment by ophub** [comment]
ok congratulations

**Comment by JFLim1** [comment]
Hi @ophub 

Correction. Panfrost in Kernel-5.15.80-flippy-79+o works this morning.  Must have done something wrong yesterday.

```
~$ dmesg
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.15.80-flippy-79+o (root@univm25) (Ubuntu clang version 14.0.0-1ubuntu1, Ubuntu LLD 14.0.0) #193 SMP PREEMPT Sat Nov 26 20:38:02 CST 2022
[    0.000000] Machine model: Beelink GT-King Pro


jlf@opbu:~$ glmark2-es2-wayland
=======================================================
    glmark2 2021.02
=======================================================
    OpenGL Information
    GL_VENDOR:     Panfrost
    GL_RENDERER:   Mali-G52 (Panfrost)
    GL_VERSION:    OpenGL ES 3.1 Mesa 22.2.1
=======================================================
[build] use-vbo=false: FPS: 802 FrameTime: 1.247 ms
[build] use-vbo=true:^C FPS: 1399 FrameTime: 0.715 ms

```

**Comment by ophub** [comment]
Maybe it's because the weather is better today

**Comment by ophub** [comment]
How did you install and activate the GPU's hardware acceleration service?

**Comment by JFLim1** [comment]
> How did you install and activate the GPU's hardware acceleration service?

I was test the new kernel-5.15.80-flippy-79+o but forgot to copy the modules-5.15.80-flippy-79+o to /lib/moduls/.  My mistake.

When zImage, uinitrd and modules-5.15.80-flippy-79+o are all in the correct location "GPU Hardware Acceleration -- Panfrost" is activated by default.  Hahaha.  Sorry about giving the wrong info.  Was testing it around 1am in the morning.

I did not install using "sudo armbian-update 5.15.80" as I was just testing this new kernel.  Your kernel-5.15.y series work with and without the chainloader u-boot.ext.  Thank you.

Looking forward to kernel-6.0.y being able to recognize SD Card and also being able to boot with the chainloader u-boot.ext.

**Comment by JFLim1** [comment]
> The kernel panic has been reported. Let's wait for upstream repair. At present, switch to other stable kernels for use.

Hi @ophub 

I tested kernel-6.0.10-arm64 and kernel-6.0.9-meson64 with chainloader u-boot.ext (rev_a) it can boot up and stable so far.  No kernel panic during booting process.

Whereas the earlier kernel-6.0.y-flippy-78+ and the later kernel-6.0.9-flippy-78+ and kernel-6.0.10-flippy-79+.all kernel panic during booting process.  Just wondering what is causing the kernel panic when using kernel=6.0.y-flippy with u-boot.ext?

**Comment by ophub** [comment]
It may be caused by some patches of flippy. He has only canceled the 5.15 patch so far. This should work normally. The life cycle of 6.0.y is coming to an end, wait for 6.1.y to observe this LTS version

**Comment by JFLim1** [comment]
> It may be caused by some patches of flippy. He has only canceled the 5.15 patch so far. This should work normally. The life cycle of 6.0.y is coming to an end, wait for 6.1.y to observe this LTS version

Hi @ophub,

Thanks.  Will look forward to the 6.1.y.

Just to reiterate, Kernel-5.15.80-flippy-79+o is running well and it works with SD Card.  Thanks.

**Comment by ophub** [comment]
OK，3q

**Comment by JFLim1** [comment]
Hi @ophub 

Just a quick update.  Tested the new 6.0.13-flippy-80+, it still **kernel panic** during booting process with u-boot.ext (rev a) on GT King Pro (rev a).
