### ISSUE TITLE
M401刷好最新版的固件No end-user support: built from trunk

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#709]
![SJ}473X`T}WE@TLQPK}VJ%T](https://user-images.githubusercontent.com/96900868/202850917-7292eab4-58e8-45f9-a518-786282281a5c.png)

**Comment by ophub** [comment]
你在github.com/armbian/build可以构建的是官方支持版。

非armbian官方支持的社区版本都会这样显示。

**Comment by HoYin90** [comment]
哥们，求教程，你用的是哪个dtb和uboot
