### ISSUE TITLE
M401A安装armbian花屏，无法进入系统

### ISSUE THREAD

**Issue by HoYin90** [ophub/amlogic-s9xxx-armbian#710]
M401A，搞了好久，不知道为何一直花屏，通过网上零星的帖子，换了dtb,uboot,虽然装上了5.15.79，可是网络和系统都不稳定，不是网络经常断开就是死机。。。无奈只能请求大佬帮助

**Device Information | 设备信息**
 - SOC: s905l3a
 - Model M401A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.79
 - Release: jammy

**Describe the bug | 问题描述**
制作了U盘启动，但启动花屏，无法进入系统安装
切换了几个版本一样的情况

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/462

**Comment by HoYin90** [comment]
> #462

我就是按照他的帖子搞的，用镜像里的u200是不行的。用他提供的u201.dtb是可以安装上，可是板子会莫名奇妙断网和死机。

**Comment by ophub** [comment]
只看盒子的名字是不太准确的。
都叫M401A并不代表是一样的盒子，每个省的运营商都有可能会改配套。有些盒子比如hk1，x96max等不同批次也会有不同的配置。
所以如果默认配置不可以正常使用，就需要结合自己的芯片测试。
