### ISSUE TITLE
m401a无法写入emmc

### ISSUE THREAD

**Issue by style6** [ophub/amlogic-s9xxx-armbian#712]
![IMG_20221120_211740](https://user-images.githubusercontent.com/47061418/202905425-ebd3ab95-b75f-4bed-a843-e2bd8e17509a.jpg)
![IMG_20221120_211821](https://user-images.githubusercontent.com/47061418/202905446-78ce5a81-8e2b-4bbf-b8f4-ec1a0d96ab97.jpg)

**Comment by ophub** [comment]
你用的哪个dtb？
cat /boot/uEnv.txt

**Comment by style6** [comment]
上面的图Armbian_22.11.0_Aml_s905l3a_bullseye_5.10.155_server_2022.11.17这个版本，换了X大的meson-g12a-u212.dtb后写入到usr就出现错误

![IMG_20221120_201253](https://user-images.githubusercontent.com/47061418/202906720-0d096b38-709a-4aea-a664-09f7b60ad330.jpg)
![IMG_20221120_201211](https://user-images.githubusercontent.com/47061418/202906796-c7dc96e3-d4fd-44f8-9469-93cb40c875ec.jpg)

**Comment by ophub** [comment]
你用meson-g12a-u212.dtb有线网络正常吗？

**Comment by style6** [comment]
meson-g12a-u212.dtb这个网络是正常的
meson-g12a-u200.dtb这个没试过

**Comment by ophub** [comment]
你算第一使用u212的，之前的m401用户使用的是u200的这个dtb。你试一下这个。或者得做一个降频的u212测试。

**Comment by style6** [comment]
好像是你们说的安卓分区问题，但是不懂怎么解决
刷的是这个包：https://www.123pan.com/s/6vKDVv-3HiUd

**Comment by style6** [comment]
获取的分区信息在这里  https://www.123pan.com/s/6vKDVv-hHiUd
，但是不懂怎么套入表格
![f1](https://user-images.githubusercontent.com/47061418/202913797-8874c65c-9640-4624-8ab2-6b9dd5bc4139.png)
![f2](https://user-images.githubusercontent.com/47061418/202913812-4e701091-d5ae-435e-9d98-b4bb3f7afa46.png)
![f3](https://user-images.githubusercontent.com/47061418/202913820-693fd885-0e31-4698-9b98-b8e2d9053553.png)

**Comment by ophub** [comment]
修改默认dtb试试meson-g12a-u200.dtb这个可以使用吗？

```
cd /boot
vi uEnv.txt
#把里面的dtb名称改为：meson-g12a-u200.dtb
#然后保存退出。
#按`esc`键， 输入`qw!`回车
sync && reboot
```
