### ISSUE TITLE
刷好armbian进入系统特别慢，密码设置无效

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#713]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - M401、cm311-1a
 - s905l3a

**Armbian Version | 系统版本**
 - Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.76_server_2022.10.30.img.gz
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
M401、cm311-1a,盒子刷好armbian进入系统特别慢，我一度以为是没有刷进去，而且设置的密码也没办法保持，设置过后还是原始密码1234登录进去的。

**Comment by ophub** [comment]
第一次启动别着急，很多服务在初始化，这个盒子性能不强，需要点时间跑完这些服务，等3分钟后再ssh连接，到路由器里看IP，使用时间最新的那个。
