### ISSUE TITLE
通过armbian-config软件列表安装了desktop，但重启后没有自动进入图形化桌面

### ISSUE THREAD

**Issue by tyultra** [ophub/amlogic-s9xxx-armbian#714]
通过Armbian自带的软件列表安装了desktop，但重启后没有自动进入图形化桌面。请问是否还要安装其他软件才可以重启后自动进入图形化桌面？
![image](https://user-images.githubusercontent.com/36122504/202912937-2f618058-0983-4ee8-b2fa-91a8c52ccee7.png)

**Comment by allonmymind** [comment]
![image](https://user-images.githubusercontent.com/18719713/202942624-86a6a189-609b-4e44-9b2d-cbe0f436cf87.png)

**Comment by ophub** [comment]
运行 `armbian-software`
选`201`

**Comment by tyultra** [comment]
> ![image](https://user-images.githubusercontent.com/18719713/202942624-86a6a189-609b-4e44-9b2d-cbe0f436cf87.png)

谢谢，我之前没想到这个点。我已设为graphical，但重启后仍然是命令行模式。
![image](https://user-images.githubusercontent.com/36122504/202962882-46c85013-e20b-4da1-bc1f-772280b61fb1.png)

**Comment by tyultra** [comment]
> 运行 `armbian-software` 选`201`

嗯，我已经是通过这种方法安装desktop的，但重启后没有自动进入桌面。我在安装时选择的是lightdm，刚查了是最新版。运行模式也是graphical。
![image](https://user-images.githubusercontent.com/36122504/202963084-7b0d7046-31af-4b1b-b6f3-b2bcf4d07d22.png)

**Comment by ophub** [comment]
```
systemctl start lightdm.service
systemctl status lightdm.service
```

**Comment by tyultra** [comment]
> jammy的话选gdm3，这是默认支持的。bullseye选lightdm。
> 
> Install ubuntu-desktop(gdm3) on Ubuntu (jammy/focal) Install Xfce(lightdm) on Debian 11 (bullseye)
> 
> ```
> systemctl start lightdm.service
> systemctl status lightdm.service
> 
> #我在rock5b-jammy里选的是gdm3。GNOME 桌面默认使用 GDM3 作为显示管理器
> systemctl status gdm3.service
> ```
> 
> ![Snip20221121_2](https://user-images.githubusercontent.com/68696949/202967212-5d2bbb15-b3d8-482a-89e9-542f760c0e9a.png)
> 
> 我在tx3-Bullseye里选择的是lightdm也可以正常使用。
> 
> ![Snip20221121_3](https://user-images.githubusercontent.com/68696949/202967488-2905d2e2-10c3-4afc-abd2-48a3b9f40242.png)

收到~~我刚才卸载了desktop，然后安装xubuntu-desktop，选择lightdm也欧克。谢谢！

**Comment by ophub** [comment]
jammy的话选gdm3，
bullseye选lightdm。

**Comment by birdxs** [comment]
> jammy的话选gdm3， bullseye选lightdm。

选择编号201自动安装，没出现让选择桌面软件的提示啊
我执行apt-get install lightdm提示已安装最新版，说明lightdm已经安装好了的

**Comment by ophub** [comment]
卸载桌面重装，过程中有选项

**Comment by silkjt** [comment]
不能进入armbian-sofware,错误提示dependency installation faild,怎么办？

**Comment by ophub** [comment]
网络不好，调整网络
