### ISSUE TITLE
[feature request] 建议在6.0以上版本内核配置开启 CONFIG_NTFS3_FS_POSIX_ACL 编译选项

### ISSUE THREAD

**Issue by YanceyChiew** [ophub/amlogic-s9xxx-armbian#718]
该选项默认配置状态为关闭。

NTFS3驱动在6.0之前内核上尚存在一些可能引起系统崩溃的BUG，不过在6.0内核上我已经稳定使用一段时间了。

它的 `noacsrules` 挂载选项存在一些问题，虽然在操作文件时可以如它的文档所言使用不受限制的“777”权限，但 `ls -l` 还是会返回文件创建时指定的权限和所有者，而且因为前面那个挂载选项的关系还无法通过 `chmod` 等命令修改，于是通过samba远程访问时就会遇上权限问题。

如果对该驱动开启了 `CONFIG_NTFS3_FS_POSIX_ACL` 支持，则通过设置父目录的默认权限可以让新创建的文件自动获得与默认值一致的权限，这样就可以不依赖 `noacsrules` 选项来让以不同用户身份运行的服务自由访问NTFS分区上的文件了。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/e23c2acae34d1ece6652d6860b4b46af253a07c3

我也和f大说了你的建议。
ophub/kernel仓库的6.0内核我是转存的f大编译的文件。
模板已经更新，可以在线自定义编译。

**Comment by YanceyChiew** [comment]
非常感谢！
