### ISSUE TITLE
提示-bash: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8) -bash:

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#719]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - cm311-1a
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Armbian_22.11.0_Aml_s905l3a_bullseye_5.15.79_server_2022.11.20.img.gz
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

图上不了

**Comment by YanceyChiew** [comment]
看看 `/etc/default/locale` 是否存在，不存在则创建。

用 `dpkg-reconfigure locales` 命令走整套流程。

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/203055636-7efe23f5-3f49-4d4d-a29b-404fd90bbef4.png)
这是有把

**Comment by YanceyChiew** [comment]
> 这是有把

你这个文件里面已经有 `LC_ALL` 了，正常来说它会生效。

不过我之前遇到过类似的情况，原因是在 `/etc` 下面还有另一个文件在控制locale，可能是 `/etc/locale.conf` ，这导致 `localectl set-locale` 写入的配置文件和实际生效的配置文件不一致，可以用grep在etc下查找一下，删掉多余的配置文件，之后也许还需要重启一次。

此外注意 `/etc/profile.d/armbian-lang.sh` 会 `export LC_ALL=$LANG` 。
