### ISSUE TITLE
SSH 运行一段时间后无法登录

### ISSUE THREAD

**Issue by daseinem** [ophub/amlogic-s9xxx-armbian#721]
**Device Information | 设备信息**
 - SOC: s905d
 - Model: Phicomm-N1

**Armbian Version | 系统版本**
 - Kernel Version: [5.10.155](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_11.20.0732/Armbian_22.11.0_Aml_s905d-ki_bullseye_5.10.155_server_2022.11.20.img.gz)
 - Release: [Armbian_Aml_bullseye_11.20.0732](https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_11.20.0732)

**Describe the bug | 问题描述**
 - `ssh` 在盒子启动后一段时间内可以正常登录
 - 随机一段时间后，`ssh` 尝试登录会收到报错`kex_exchange_identification: read: Connection reset`
 - 开始报错时，通过之前登录保留的会话，查看`sshd.service`状态，报错`fatal: Missing privilege separation directory: /run/sshd`，（此时`sshd.service`依然为`Active: active (running)`，不会触发重启）
 - 手动重启`sshd.service`后，客户端又可以暂时正常登录

**Comment by ophub** [comment]
/etc/custom_service/start_service.sh
把36、37两行前面的#删除，保存重启
```
#[[ -d "/var/run/sshd" ]] || mkdir -p -m0755 /var/run/sshd
#[[ -f "/etc/init.d/ssh" ]] && /etc/init.d/ssh start 2>/dev/null
```

**Comment by daseinem** [comment]
感谢及时回复，已经做了相应更改并且重启，运行10分钟暂时没有复现。
运行较长一段时间后我再来反馈。
