### ISSUE TITLE
卸载了desktop，在armbian-software列表仍显示“update/remove”

### ISSUE THREAD

**Issue by tyultra** [ophub/amlogic-s9xxx-armbian#722]
**Device Information | 设备信息**
 - SOC: [S905x3]
 - Model [HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.79]
 - Release: [jammy]

**Describe the bug | 问题描述**
运行“armbian-software”，显示201 desktop已经安装，输入201，选择remove，重启后再运行“armbian-software”，仍显示"update/remove"。
![image](https://user-images.githubusercontent.com/36122504/203109411-c5429550-279e-4e18-873f-ebb9d70e9e24.png)

**Comment by ophub** [comment]
```
sudo apt-get update
sudo apt-get remove --purge -y lightdm
sudo apt-get --purge autoremove -y
sudo apt-get autoclean -y
```

**Comment by tyultra** [comment]
> ```
> sudo apt-get update
> sudo apt-get remove --purge -y lightdm
> sudo apt-get --purge autoremove -y
> sudo apt-get autoclean -y
> 
> #执行完上面的命令后，看看lightdm这个软件包删除了没
> dpkg -l | grep lightdm
> ```
按你的指引操作了，这样是还有残余吗？armbian-software的desktop仍显示installed.
![image](https://user-images.githubusercontent.com/36122504/203216623-42484297-1e82-4516-8bb9-8bd14722ae29.png)

**Comment by ophub** [comment]
把搜索到的这2个也删除了

**Comment by tyultra** [comment]
> 把搜索到的这2个也删除了

卸载了一个，还有另一个卸载不了。armbian-software的desktop仍显示installed.
![image](https://user-images.githubusercontent.com/36122504/203227102-33dbfdf1-ac10-4493-b397-c7dd0824347f.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/9c9c73e178f0d651c5efbad6ba029b3497394fa8

我升级了下相关脚本，现在精确匹配软件包。你运行`armbian-sync`更新下最新脚本即可。

**Comment by tyultra** [comment]
> [9c9c73e](https://github.com/ophub/amlogic-s9xxx-armbian/commit/9c9c73e178f0d651c5efbad6ba029b3497394fa8)
> 
> 我升级了下相关脚本，现在精确匹配软件包。你运行`armbian-sync`更新下最新脚本即可。

可以了，谢谢！
