### ISSUE TITLE
Is able to support RK3566 android box?

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#723]
It seems rk3566 is getting more popular now. 
At current, RK3568 is supported but is able to support RK3566 box?

Here are some samples of RK3566 boxes:

https://www.alibaba.com/product-detail/Original-Factory-Direct-selling-8K-Video_1600254930459.html?spm=a2700.shop_plgr.41413.3.24e511ceXKx8aP

https://www.firefly.store/goods.php?id=142

Thank you.

**Comment by ophub** [comment]
Each device is different and needs to be individually adapted, and no device cannot be debugged.
