### ISSUE TITLE
M 401 a哈希值错误？

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#725]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - bullseye 5.15.79
 -

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
![J9D`GR347GZ15LZE_S2Z8B8](https://user-images.githubusercontent.com/96900868/203281256-cfdf7c27-eb5d-40df-978e-1401a949c8e7.png)

**Comment by ophub** [comment]
执行什么操作？

**Comment by zhuguoqing123** [comment]
apt-get update

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/203352414-62ede94d-c677-4815-83a5-9c41bc5dcc0c.png)
一样的问题

**Comment by ophub** [comment]
```
sudo rm -rf /var/lib/apt/lists/*
sudo apt update
```

**Comment by zhuguoqing123** [comment]
执行过了，o大，问题依旧
![image](https://user-images.githubusercontent.com/96900868/203578361-119bf460-1a3e-47ad-a01e-2b70f6d4ffc5.png)

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/203590518-75875836-bbca-49c5-b7b0-0061272407f7.png)

**Comment by zhuguoqing123** [comment]
![image](https://user-images.githubusercontent.com/96900868/203592772-3c8f128e-5d89-4735-abdf-3d638002ab86.png)

**Comment by zhuguoqing123** [comment]
同一个机器，反复刷了几次armbian，一直这个问题，M401a
