### ISSUE TITLE
TOX1 Network not working

### ISSUE THREAD

**Issue by arikoza** [ophub/amlogic-s9xxx-armbian#726]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - Amlogic S905X3 (Quad-Core ARM Cortex-A55 до 2.0GHz)
 - TOX1 ( https://trustonx.com/product/tox1-player-4gb-ram-ddr3-32gb-nand-amlogic-s905x2-media-player/ )

**Armbian Version | 系统版本**
 - Armbian_22.11.0_Aml_s905x3_bullseye_5.15.79_server_2022.11.21.img.gz
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Network not working (ethernet and wifi). WiFi module RTL8822BS
When starting from a sd card, it says "Failed to start Raise network interfaces" . In the armbian-config, there are no settings and no Wi-Fi network search at all.

![NPBvfWHrHYg](https://user-images.githubusercontent.com/93445603/203627002-ab5999dd-b356-4952-8863-0d8a88653908.jpg)
![Np_hNXO5dlI](https://user-images.githubusercontent.com/93445603/203627016-93a4ce20-9418-4c3e-99a0-6358334b0ced.jpg)
![Fzl0n_jiN7A](https://user-images.githubusercontent.com/93445603/203627025-d4167be0-2fa6-49d6-bf88-959a773cc2d1.jpg)

**Comment by ophub** [comment]
There is no driver for the wireless network card.
What kind of chip is the wired network card, gigabit or 100 megabit.

**Comment by arikoza** [comment]
> try:
> /boot/uEnv.txt
> meson-sm1-tx3-qz.dtb
I re-recorded the SD card, changed it in /boot/uEnv.txt to FDT=/dtb/amlogic/meson-sm1-tx3-qz.dtb
Doesn't start at all. Hanging on the Android logo

**Comment by ophub** [comment]
use usb

**Comment by arikoza** [comment]
It did not work, it also does not see LAN

![photo_2022-11-24_09-51-23](https://user-images.githubusercontent.com/93445603/203714309-8f61a49c-7e5d-4eb6-8499-0f265bdb0f98.jpg)
![photo_2022-11-24_09-51-27](https://user-images.githubusercontent.com/93445603/203714314-2715c2b2-42ff-4edf-8d7e-e826c1468afc.jpg)
![photo_2022-11-24_09-53-01](https://user-images.githubusercontent.com/93445603/203714326-8ad62f16-fe1d-414f-a9a4-2df7228ec5b2.jpg)
![photo_2022-11-24_09-53-50](https://user-images.githubusercontent.com/93445603/203714334-c050eba3-778f-4982-8465-a51ce7d581d8.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/5071dcac5530b500e4b36ec2648b117bc25a1cdb/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L92-L114

**Comment by arikoza** [comment]
Gigabit  card
None worked. Maybe I'm doing something wrong? I record the USB via balenaEtcher , change it in the uEnv.txt file to the new values that you sent and insert it into the TV box.

**Comment by ophub** [comment]
cat /boot/uEnv.txt
sha256sum /boot/u-boot*

**Comment by arikoza** [comment]
![photo_2022-11-24_13-59-44](https://user-images.githubusercontent.com/93445603/203767925-2ff5c7bf-9bf2-49bc-96a4-757b4abce233.jpg)

**Comment by ophub** [comment]
try 5.15y

**Comment by arikoza** [comment]
When the Android network is loaded, the Internet works via cable.
![111](https://user-images.githubusercontent.com/93445603/203773192-88f04b06-11c8-4db5-a6a1-70c97dc07cd6.jpg)
![photo_2022-11-24_14-26-59](https://user-images.githubusercontent.com/93445603/203773196-8179a6f1-46f4-4449-847a-bf66e352c526.jpg)

**Comment by arikoza** [comment]
![3333](https://user-images.githubusercontent.com/93445603/203774806-7067c396-fce3-4504-89dc-b11220123a0b.jpg)

**Comment by ophub** [comment]
What is a wired network card chip

**Comment by arikoza** [comment]
rtl8211f
5,15 also does not see the network

**Comment by ophub** [comment]
![FD1BA4AB-C3C2-413B-925C-737C86E11F31](https://user-images.githubusercontent.com/68696949/203789152-be71b286-52fd-416d-af0c-b597394c42a6.jpeg)



https://github.com/unifreq/linux-5.15.y/blob/6963c647802a06ad057601d71b7958c9463ea174/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus-ip1001m.dts#L23-L26

**Comment by ophub** [comment]
[test1-7.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10087985/test1-7.zip)

Unzip, put 7 files in the /boot/dtb/amlogic directory, modify the dtb name in /boot/uEnv.txt, from 1 to 7 in sequence, save each modification, and restart the test.

**Comment by arikoza** [comment]
Not all work :(

**Comment by ophub** [comment]
Did you restart the test after modifying all 7?

**Comment by arikoza** [comment]
1. sudo su
2.  nano /boot/uEnv.txt
3.  new name
4. sync && reboot
And so 7 times

**Comment by ophub** [comment]
```
# This is the decompile command
dtc -I dtb -O dts -o /tmp/xxxxx.dts xxxxxx.dtb

# Here is the compile command
dtc -I dts -O dtb -o xxxxxxx .dtb xxxxxxxx.dts
```
0-7 has been tested invalid, continue to test `8-31`, you test one by one
