### ISSUE TITLE
通过armbian-software安装的软件，是会放到Docker的容器里面?

### ISSUE THREAD

**Issue by tyultra** [ophub/amlogic-s9xxx-armbian#727]
我通过armbian-software安装了docker，然后通过armbian-software分别安装了qBittorrent和Transmission，发现这两个软件不是直接安装在系统，而是成了Docker的容器，请问这是正常的吗？如果我要卸载，是否在Docker里面Remove容器就可以？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/armbian_software.md


1xx是docker系列软件。
可以使用armbian-software安装/更新/删除。选择这个软件的序号，选择r就是删除：

也可以在docker界面删，也可以用docker命令删。方法有多种，结果都是相同的。

**Comment by tyultra** [comment]
> 
明白了，谢谢~
