### ISSUE TITLE
m401A江苏版写入emmc执行到copy usr时报错

### ISSUE THREAD

**Issue by bokeylee** [ophub/amlogic-s9xxx-armbian#728]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model: m401a 江苏

**Armbian Version | 系统版本**
 - Kernel Version：5.15.79
 - Release:  jammy

**Describe the bug | 问题描述**
写入u盘使用u200的dtb和uboot，偶尔会莫名panic，但还是有可以顺利启动并登录的时候
![04b449ced509dc60429e4ac80258927](https://user-images.githubusercontent.com/63947149/203822146-8832cfea-2b8d-4d6c-ac0e-12f02f3a00c7.jpg)

但在写入emmc时，每次都会在同一个位置报错并触发kernel panic
![6a5ea44b4d58331e1057427bfe45210](https://user-images.githubusercontent.com/63947149/203822198-55db6c3f-1247-4de3-b458-0ece38dd12e4.jpg)

请问这是dtb的问题还是我的u盘和m401a八字不合呢？

**Comment by ophub** [comment]
[meson-g12a-s905l3a-m401a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10088127/meson-g12a-s905l3a-m401a.dtb.zip)

解压缩，上传到/boot/dtb/amlogic目录下，修改/boot/uEnv.txt里dtb的名字，重启测试

**Comment by Doboo** [comment]
> [meson-g12a-s905l3a-m401a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10088127/meson-g12a-s905l3a-m401a.dtb.zip)
> 
> 解压缩，上传到USB里的/boot/dtb/amlogic目录下，修改/boot/uEnv.txt里dtb的名字，重启再测试USB是否正常，写入EMMC是否正常

专用DTB?我有几个盒子原来也是写入有问题。我测试一下回来反馈

**Comment by bokeylee** [comment]
> [meson-g12a-s905l3a-m401a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10088127/meson-g12a-s905l3a-m401a.dtb.zip)
> 
> 解压缩，上传到USB里的/boot/dtb/amlogic目录下，修改/boot/uEnv.txt里dtb的名字，重启再测试USB是否正常（推荐使用2.0的usb)
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/61b915fd832fa57c40578d8232aa1bf7a4ccd5bc/build-armbian/common-files/rootfs/etc/amlogic_model_database.conf#L71
> 
> 把本机/etc/amlogic_model_database.conf文件中编号305的dtb改成m401a这个名字，写入EMMC时选择305看看是否正常

谢谢大佬，不过……这下子连u盘引导都进不去了……
![54f812534d3f4ada0adcd7b2c15c06b](https://user-images.githubusercontent.com/63947149/203968243-def769a9-d48e-4a84-ad74-f5e28815cdcd.jpg)
我怀疑是我的U盘太老了，回头另找个2.0U盘再试试。手头另外一个3.0的U盘可以亮机，但会在挂载分区时出错

**Comment by ophub** [comment]
你这个内核恐慌也是不正常现象。
图片上一直在调整usb的速度要降速。但是dtb的三项是调tf/sd/emmc速度的，外置usb调不了，碰到极个别挑U盘的情况，只好换U盘（也有人是加电容来稳定电压）

**Comment by bokeylee** [comment]
> 你这个内核恐慌也是不正常现象。
> 图片上一直在调整usb的速度要降速。但是dtb的三项是调tf/sd/emmc速度的，外置usb调不了，碰到极个别挑U盘的情况，只好换U盘（也有人是加电容来稳定电压）

原来如此，确实这个盒子电路板上空了好多焊点，待我再研究研究

**Comment by Doboo** [comment]
![图片](https://user-images.githubusercontent.com/12352436/203993331-79ad9988-36a5-4066-a3c7-2a822b39545a.png)
我这边也是写emmc的时候报错了
![图片](https://user-images.githubusercontent.com/12352436/203993471-a8a8355b-0a53-410f-823e-c69b0aec608e.png)

**Comment by ophub** [comment]
猜不出你的配置
