### ISSUE TITLE
CM311-1a-YST armbian install不加任何参数安装系统到emmc之后无法再次从u盘启动

### ISSUE THREAD

**Issue by lightzhu** [ophub/amlogic-s9xxx-armbian#729]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [CM311-1a-YST]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [Armbian_22.11.0_Aml_s905l3a_jammy_5.10.155_server_2022.11.24.img.gz])

**Describe the bug | 问题描述**

u盘启动后，先执行armbian-ddbr进行备份安卓系统，再执行armbian install不加任何参数，之后无法再从u盘启动，导致之前的备份无法还原，只能emmc启动。
这个https://github.com/ophub/amlogic-s9xxx-armbian/issues/565， issues已经参考，实操无效。
 大佬能解决一下吗，我想还原回安卓系统

**Comment by ophub** [comment]
主板短接点，线刷

**Comment by lightzhu** [comment]
已解决：在u盘的boot文件夹下面找到boot.cmd boot.ini boot.scr（可能是大写字母名称） 以及uEnv.txt这四个文件，直接替换在armbian的boot文件夹里的对应文件，然后插上u盘就可以再次U盘启动了
