### ISSUE TITLE
Armbian writes to EMMC.

### ISSUE THREAD

**Issue by Jay-9527** [ophub/amlogic-s9xxx-armbian#73]
hi @ophub 

After I write Armbian to EMMC, I restart TVbox as prompted, why can't I get into system?
![IMG_20220114_005108](https://user-images.githubusercontent.com/30925620/149377391-f02f675e-3be0-4f0a-a819-16c4fdc125e8.jpg)

**Comment by ophub** [comment]
what box

**Comment by Jay-9527** [comment]
T95Z Plus Sent from my Huawei phone-------- Original message --------From: ophub ***@***.***>Date: Fri, Jan 14, 2022, 11:45 AMTo: ophub/amlogic-s9xxx-armbian ***@***.***>Cc: "Mr.Jay" ***@***.***>, Author ***@***.***>Subject: Re: [ophub/amlogic-s9xxx-armbian] Armbian writes to EMMC. (Issue #73)
what box
