### ISSUE TITLE
本地访问Docker容器的IP地址提示“不安全”，能否不走https？

### ISSUE THREAD

**Issue by tyultra** [ophub/amlogic-s9xxx-armbian#730]
Docker部署了几个容器：Portainer，Transmission，HomaAssistant等，本地网络访问都是走https，浏览器地址栏提示“不安全”。有没有办法不走https？另外，armbian用的是nginx吗？我能否部署自己域名的SSL证书？谢谢！

**Comment by ophub** [comment]
现在的主流的流览器，只要是http就都会提示不安全，这个可以忽视它。
或者你加域名证书，阿里的通配符证书免费，一签有效期一年，这是最佳方案。
免费域名很多，你一搜就知道了。
