### ISSUE TITLE
Wrong resolution

### ISSUE THREAD

**Issue by Supded** [ophub/amlogic-s9xxx-armbian#731]
x96 max plus 2101w 4/64
extlinux.conf
------------------------
```
label Armbian
    kernel /zImage
    initrd /uInitrd
    fdt /dtb/amlogic/meson-sm1-x96-max-plus.dtb
    append root=UUID=82fdd91e-cb6a-4755-9e69-21b9cb7c4c7a rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 loglevel=1 voutmode=hdmi disablehpd=false overscan=100 sdrmode=auto

```

------------------------
I got cutted picture in virtual console, tried Armbian_22.11.0_Aml_s905x3_bullseye_5.10.155_server_2022.11.24.img.gz and Armbian_22.11.0_Aml_s905x3_bullseye_5.15.79_server_2022.11.21.img.gz. Boot from usb, uboot - u-boot-x96maxplus.bin. On logo and in android output is 1080p, but armbian gives me 720 with cutted borders. I saw 1 error, [drm] kms: can't enable cloning when we probably wanted to. Used hdmi with old 1080 tv, maybe 1.4.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs

12.6

**Comment by Supded** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/armbian-docs
> 
> 12.6

Fixed, but all the same.
uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-x96-max-plus.dtb
APPEND=root=UUID=e1c54cfb-2534-4da2-b4e8-80aedbcc7dbc rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

**Comment by ophub** [comment]
Try updating to other kernels, try all 4 series, and see which monitor can support it

**Comment by Supded** [comment]
Can i get img with old kernel? I have no internet on tv box.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#update-armbian-kernel

**Comment by Supded** [comment]
Sorry for wasting your time, solved. I do factory reset on my tv, set eu region and overscan setting was appended. Afted disabling oversan picture was ok! Thanks.
