### ISSUE TITLE
请教如何用asla播放音频

### ISSUE THREAD

**Issue by imzlh** [ophub/amlogic-s9xxx-armbian#733]
感谢大佬的armbian，十分稳定，安装桌面还能有音视频输出，可玩性极高。最近在家中翻出一个hdml转vga带音频输出的，想要试试看用家中的e900v22d播放音乐，网上教程是用alsa播放的，但是我试了好几次都不行，aplay播放不了，alsabat-test全fail了。再拿一台装了桌面和pulseaudio的e900v22c也是这样不过完全可以vlc里播放音乐，的确有声音输出……折腾无果只好请教大佬了

**Comment by ophub** [comment]
我没用过asla,不会弄

**Comment by imzlh** [comment]
那你试过用其他方式播放音频吗

**Comment by ophub** [comment]
我用苹果耳机听歌

**Comment by uncle-wong** [comment]
pulseaudio这个蓝牙音频输出没问题。
