### ISSUE TITLE
armbian安装好OMV 系统,，将新系统备份成img，将新备份系统安装在新电视盒子上吗？

### ISSUE THREAD

**Issue by tt555-1** [ophub/amlogic-s9xxx-armbian#737]
1、盒子为cm311-1a,把armbian系统写入盒子存储；
2、安装 好omv,并且在omva上面安装好docker; 
3、请问盒子OMV系统，是否可以做成系统备份做成img镜像，把备份img写入u盘，然后把这个系统备份新安装到新电视盒子上呢？是否有操作明细，谢谢。

**Comment by ophub** [comment]
armbian-ddbr
b是备份
r是恢复
在a盒子里备份了，把备份的文件上传到usb里，到b盒子用r恢复到这个盒子里，恢复完2台盒子完全一样了会冲突了。

运行armbian-fix更换机器id
在/etc/network/interfaces里更新mac地址
