### ISSUE TITLE
Potential Bug With Kernel-5.15.y On KDE Plasma 5.25/5.26 After Turn Off Display Monitor

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#739]
Hi @ophub,

Desktop Environment: KDE Plasma 5.25.5 or KDE Plasma 5.26.y
Kernel: 5.15.y

Problem/Issue:  When on KDE Plasma 5.25.5 when you turn OFF the Monitor/Display and turn ON again you will loose HDMI Signal to Monitor.  When you Power Cycle to Reboot it will NOT reboot to Desktop Anymore it will go into Desktop Loop but never boot up to KDE Plasma Desktop.  

The solution to regain KDE Plasma Desktop is to delete all the files in ".local/share/kcreen":

```
cd .local/share/kscreen
sudo rm *
cd .local/share/kcreen/outputs
sudo rm *
sudo reboot
```
It will then reboot to KDE Plasma Desktop.  So far i have only face this with kernel-5.15.y.  Kernel-5.19.y-flippy No issue. 

Kernel-5.15.y-flippy does not face this issue on Gnome Desktop Environment so far only on KDE Plasma.

**Comment by ophub** [comment]
KDE is used, and the same phenomenon can be used for reference
