### ISSUE TITLE
Tanix Tx9 Pro 2G_16G (S912)可以使用

### ISSUE THREAD

**Issue by rainups** [ophub/amlogic-s9xxx-armbian#740]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S912]
 - Model [Tanix TX9Pro_2G_16G]

**Armbian Version | 系统版本**
 - Kernel Version: [5.10.154]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

它是个低配的Tanix TX9pro 2G RAM,16G ROM,100Mb Nic 电视盒子
用的是Armbian_22.11.0_Aml_s912_bullseye_5.10.154_server_2022.11.16.img，配合meson-gxm-tx9-pro.dtb
存在有线LAN和无线WIFI不工作问题。

它与常规的Tanix TX9pro 3G RAM,32G ROM,1000Mb Nic 很接近，我尝试用最接近的meson-gxm-q201.dtb 有线LAN也不能工作，

但它比meson-gxm-tx9-pro.dtb在ifconfig里能看到MAC地址，但没IP地址。

在老版本的 Armbian_20.10_Aml-s9xxx_buster_5.4.108-flippy-56+o 固件里有线是可以工作，无线WIFI另行打补丁也是工作的(用rtl8189es驱动）。

2个硬件PCB版本图片：CS_912_TX92_LP_V1.0 20170810 和 CS_912_TX92_B8_V1.1 20190811
https://discourse.coreelec.org/uploads/default/original/2X/9/94b02f9dbab4377de9a1458103369790ec75e546.jpeg

**Comment by rainups** [comment]
**meson-gxm-tx9-pro.dtb**

 [  OK  ] Finished Permit User Sessions.
         Starting Hostname Service...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Started chrony, an NTP client/server.
[  OK  ] Reached target System Time Synchronized.
[  OK  ] Started Daily apt download activities.
[  OK  ] Started Daily apt upgrade and clean activities.
[  OK  ] Started Periodic ext4 Online Metadata Check for All Filesystems.
[  OK  ] Started Discard unused blocks once a week.
[  OK  ] Started Daily rotation of log files.
[  OK  ] Started Daily man-db regeneration.
[  OK  ] Started Run system activity accounting tool every 10 minutes.
[  OK  ] Started Generate summary of yesterday's process accounting.
[  OK  ] Reached target Timers.
[  OK  ] Started LSB: set CPUFreq kernel parameters.
         Starting LSB: Set sysfs variables from /etc/sysfs.conf...
[  OK  ] Started LSB: Set sysfs variables from /etc/sysfs.conf.
[  OK  ] Started Hostname Service.
         Starting Network Manager Script Dispatcher Service...
[  OK  ] Started Network Manager Script Dispatcher Service.
[   20.107229] Bluetooth: hci0: BCM: failed to write update baudrate (-110)
[   20.112620] Bluetooth: hci0: Failed to set baudrate
[   20.137498] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   21.893871] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   21.907198] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   21.923262] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  OK  ] Started Dispatcher daemon for systemd-networkd.
[   22.240540] Bluetooth: hci0: command 0x0c03 tx timeout
[   22.260751] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[   24.013886] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   24.013900] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   24.013908] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   24.274106] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[   26.023858] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   26.038432] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   26.055764] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[   26.327527] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   28.077193] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   28.092148] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   28.109825] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[   28.384102] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   30.133893] Bluetooth: hci0: BCM: Reset failed (-110)
[   30.133901] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[   30.133922] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[   30.182353] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  OK  ] Finished Network Manager Wait Online.
[  OK  ] Reached target Network is Online.
         Starting /etc/rc.local Compatibility...
[   30.516151] rc.local[1700]: irq name:xhci-hcd:usb1, irq:43, affinity: 4
[   30.576311] rc.local[1706]: irq name:xhci-hcd:usb1, irq:43, affinity: 4
[  OK  ] Started /etc/rc.local Compatibility.
         Starting Hold until boot process finishes up...
         Starting Terminate Plymouth Boot Screen...

Armbian 22.11.0-trunk Bullseye ttyAML0

armbian login:
[  330.200705] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  331.947136] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  331.963376] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  331.982389] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  332.250678] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  334.000481] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  334.016945] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  334.036120] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  334.304041] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  336.050477] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  336.066954] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  336.086147] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed
[  336.354019] meson8b-dwmac c9410000.ethernet eth0: PHY [0.2009087f:00] driver [Generic PHY] (irq=POLL)
[  338.103814] meson8b-dwmac c9410000.ethernet: Failed to reset the dma
[  338.120246] meson8b-dwmac c9410000.ethernet eth0: stmmac_hw_setup: DMA engine initialization failed
[  338.139424] meson8b-dwmac c9410000.ethernet eth0: stmmac_open: Hw setup failed



**meson-gxm-q201.dtb**

[  OK  ] Started Network Manager.
[  OK  ] Reached target Network.
         Starting Network Manager Wait Online...
         Starting chrony, an NTP client/server...
         Starting Access point and authentication server for Wi-Fi and Ethernet...
         Starting OpenVPN service...
         Starting Notify NFS peers of a restart...
         Starting Permit User Sessions...
[  OK  ] Started Unattended Upgrades Shutdown.
[  OK  ] Started vnStat network traffic monitor.
[  OK  ] Finished OpenVPN service.
[  OK  ] Finished Permit User Sessions.
[  OK  ] Started LSB: set CPUFreq kernel parameters.
         Starting LSB: Set sysfs variables from /etc/sysfs.conf...
         Starting Hostname Service...
[  OK  ] Started Notify NFS peers of a restart.
[  OK  ] Started LSB: Set sysfs variables from /etc/sysfs.conf.
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Started chrony, an NTP client/server.
[  OK  ] Reached target System Time Synchronized.
[  OK  ] Started Daily apt download activities.
[  OK  ] Started Daily apt upgrade and clean activities.
[  OK  ] Started Periodic ext4 Online Metadata Check for All Filesystems.
[  OK  ] Started Discard unused blocks once a week.
[  OK  ] Started Daily rotation of log files.
[  OK  ] Started Daily man-db regeneration.
[  OK  ] Started Run system activity accounting tool every 10 minutes.
[  OK  ] Started Generate summary of yesterday's process accounting.
[  OK  ] Reached target Timers.
[  OK  ] Started Hostname Service.
         Starting Network Manager Script Dispatcher Service...
[  OK  ] Started Network Manager Script Dispatcher Service.
[   20.444614] meson8b-dwmac c9410000.ethernet eth0: PHY [0.e40908ff:08] driver [Meson GXL Internal PHY] (irq=43)
[   21.988071] meson8b-dwmac c9410000.ethernet eth0: No Safety Features support found
[   22.001650] meson8b-dwmac c9410000.ethernet eth0: PTP not supported by HW
[   22.015608] meson8b-dwmac c9410000.ethernet eth0: configuring for phy/rmii link mode
[  OK  ] Started Dispatcher daemon for systemd-networkd.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   22.821684] r8712u 1-1:1.0 wlan0: 1 RCR=0x153f00e
[   22.827324] r8712u 1-1:1.0 wlan0: 2 RCR=0x553f00e
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   31.456857] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   31.465249] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   32.234411] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   33.805361] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   34.583056] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   36.153972] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   36.931670] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   38.502647] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   39.280235] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   40.851153] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   41.628814] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   54.963716] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   55.741315] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   57.375147] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   58.152778] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   59.723736] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   60.501417] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   62.072416] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   62.849956] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   64.420921] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   65.198607] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[  OK  ] Stopped Access point and authentication server for Wi-Fi and Ethernet.
         Starting Access point and authentication server for Wi-Fi and Ethernet...
[FAILED] Failed to start Access point and authentication server for Wi-Fi and Ethernet.
See 'systemctl status hostapd.service' for details.
[   78.512523] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   79.290108] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[FAILED] Failed to start Network Manager Wait Online.
See 'systemctl status NetworkManager-wait-online.service' for details.
[  OK  ] Reached target Network is Online.
         Starting /etc/rc.local Compatibility...
[   80.053255] rc.local[1744]: irq name:eth0, irq:29, affinity: 8
[   80.054228] rc.local[1744]: irq name:xhci-hcd:usb1, irq:42, affinity: 4
[   80.068569] rc.local[1744]: Set the rps cpu mask of eth0 to 0xf3
[   80.115062] rc.local[1750]: irq name:eth0, irq:29, affinity: 8
[   80.115620] rc.local[1750]: irq name:xhci-hcd:usb1, irq:42, affinity: 4
[   80.116167] rc.local[1750]: Set the rps cpu mask of eth0 to 0xf3
[  OK  ] Started /etc/rc.local Compatibility.
         Starting Hold until boot process finishes up...
         Starting Terminate Plymouth Boot Screen...
[   80.861057] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx

Armbian 22.11.0-trunk Bullseye ttyAML0

armbian login: [   81.638717] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   83.209617] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   83.987226] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   85.558144] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   86.335876] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[   87.906740] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[   88.684413] meson8b-dwmac c9410000.ethernet eth0: Link is Down

armbian login: root
Password: [  101.998327] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx

[  102.775962] meson8b-dwmac c9410000.ethernet eth0: Link is Down
    _              _   ____  ___  _ ____
   / \   _ __ ___ | | / ___|/ _ \/ |___ \
  / _ \ | '_ ` _ \| | \___ \ (_) | | __) |
 / ___ \| | | | | | |  ___) \__, | |/ __/
/_/   \_\_| |_| |_|_| |____/  /_/|_|_____|

Welcome to Armbian 22.11.0-trunk Bullseye with Linux 5.10.154-ophub

No end-user support: built from trunk

System load:   11%              Up time:       1 min
Memory usage:  7% of 1.88G      IP:
CPU temp:      64°C             Usage of /:    54% of 2.4G
RX today:      n/a

[ General system configuration (beta): armbian-config ]

Last login: Wed Nov 16 13:01:22 HKT 2022 on ttyAML0
root@armbian:~# [  104.346753] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  105.124596] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  106.695449] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  107.473175] meson8b-dwmac c9410000.ethernet eth0: Link is Down
ifconfig
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet6 fe80::ae08:e1fd:16c0:4059  prefixlen 64  scopeid 0x20<link>
        ether de:f1:ae:d4:73:07  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 90  bytes 10647 (10.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 29

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 24  bytes 1944 (1.8 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 24  bytes 1944 (1.8 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

root@armbian:~# [  111.392650] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  112.170348] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  125.484312] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  126.261905] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  127.832859] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  128.610458] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  130.181550] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  130.959054] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  132.530086] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  133.307587] meson8b-dwmac c9410000.ethernet eth0: Link is Down
[  134.878567] meson8b-dwmac c9410000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx
[  135.656247] meson8b-dwmac c9410000.ethernet eth0: Link is Down

**Comment by rainups** [comment]
从原厂固件提取的:dts
[TX9Pro_2G_16G_android7.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10100839/TX9Pro_2G_16G_android7.txt)

**Comment by ophub** [comment]
未知设备用5.15的固件试。只要dtb对就能用，你用5.10的试，受u-boot影响

5.10有3个u-boot，你用的是章鱼星球的，试试u-boot-s905x-s912.bin和u-boot-p212.bin

```
cd /boot
cp -f u-boot-s905x-s912.bin u-boot.ext
sync && reboot
```

**Comment by rainups** [comment]
换成5.15好像变化不大：
Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img
u-boot-s905x-s912.bin  复制到 u-boot.ext
uEnv.txt               改为   meson-gxm-tx9-pro.dtb
extlinux.conf          改为   meson-gxm-tx9-pro.dtb

[01_boot.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10101369/01_boot.txt)

同时对比3G_32G的dtb是有点区别，不知有没有关系：
![TX9Pro_3G_2G_dtb](https://user-images.githubusercontent.com/82754232/204218545-d17f4477-8d9d-4aab-b620-63452804ef9d.png)

**Comment by ophub** [comment]
[meson-gxm-tx9-pro-2g.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10102359/meson-gxm-tx9-pro-2g.dtb.zip)

这盒子是百兆的？

**Comment by rainups** [comment]
目前能查到的是：
2G_16G版是100M有线LAN,无线WIFI是RTL8190ETV
3G_32G版是1000M有线LAN,无线WIFI是QCA9377

Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img
u-boot-s905x-s912.bin 复制到 u-boot.ext
uEnv.txt 改为 meson-gxm-tx9-pro-2g.dtb
extlinux.conf 这个文件不需要，删除它或者保持原来的.bak后缀不要改
按你要求附上TTL记录，HDMI显示好像在找tftp服务。
[20221129A_TTL_log.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10109109/20221129A_TTL_log.txt)

![20221129A](https://user-images.githubusercontent.com/82754232/204424303-b594f8ad-1f16-4011-8f1f-1fdfa0c7e63e.jpg)

**Comment by ophub** [comment]
5.15不要复制u-boot.ext，删了，只改dtb重启

**Comment by rainups** [comment]
Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img
u-boot.ext     不需要，删除
uEnv.txt       改为 meson-gxm-tx9-pro-2g.dtb
extlinux.conf  这个文件不需要，删除它或者保持原来的.bak后缀不要改
TTL记录:
[20221129D_TTL_log.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10109486/20221129D_TTL_log.txt)

**Comment by ophub** [comment]
刚才有u-boot的时候还分配到了IP，看来还是需要u-boot引导，你现在是在USB里运行的？
加了u-boot会无法启动吗？

u-boot-p212.bin
u-boot-zyxq.bin
USB复制这2个为u-boot.ext试试能启动不，先在USB测试，不要写入emmc

**Comment by rainups** [comment]
一直是用64G TF卡测试的：

Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img   写入64G TF卡
u-boot-p212.bin  复制到 u-boot.ext
uEnv.txt         改为 meson-gxm-tx9-pro-2g.dtb
extlinux.conf    这个文件不需要，删除它或者保持原来的.bak后缀不要改
[20221129E_TTL_log_u-boot-p212.bin.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10109835/20221129E_TTL_log_u-boot-p212.bin.txt)


Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img   写入64G TF卡
u-boot-zyxq.bin  复制到 u-boot.ext
uEnv.txt         改为 meson-gxm-tx9-pro-2g.dtb
extlinux.conf    这个文件不需要，删除它或者保持原来的.bak后缀不要改
[20221129F_TTL_log_u-boot-zyxq.bin.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10109837/20221129F_TTL_log_u-boot-zyxq.bin.txt)

**Comment by ophub** [comment]
u-boot-p212.bin
meson-gxm-q201.dtb
这2个组合看看

**Comment by rainups** [comment]
图片是进到一个tftp里，把我的路由当服务。不知啥原因；
Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img   写入64G TF卡
u-boot-p212.bin  复制到 u-boot.ext
uEnv.txt         改为 meson-gxm-q201.dtb
extlinux.conf    这个文件不需要，删除它或者保持原来的.bak后缀不要改
这个组合有IP啦，之前在5.10里我也试过这样的组合，没成功，可能是我连extlinux.conf一起改的原因。
十分感谢大佬，辛苦啦！
 
[20221129G_TTL_log_u-boot-p212.bin_meson-gxm-q201.dtb.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10110738/20221129G_TTL_log_u-boot-p212.bin_meson-gxm-q201.dtb.txt)

**Comment by ophub** [comment]
你再试试5.15不要u-boot行不行
删除u-boot.ext，只把uEnv.txt 改为 meson-gxm-q201.dtb
重启试试

**Comment by rainups** [comment]
Armbian_22.11.0_Aml_s912_bullseye_5.15.78_server_2022.11.16.img   写入64G TF卡
u-boot.ext       这个文件不需要，删除它
uEnv.txt         改为 meson-gxm-q201.dtb
extlinux.conf    这个文件不需要，删除它或者保持原来的.bak后缀不要改

也可以，IP变了，它自动识别u-boot里的MAC地址了，再次感谢！

**Comment by ophub** [comment]
每个盒子总是因为有你这样的恭献者，经过不断尝试、不断开发、不断改进，才给后来的使用者打开了一个新世界。

感谢你不厌其烦地测试，终于找出了合适的配置。我一会在配置文件里加一条
meson-gxm-q201.dtb
u-boot-p212.bin

**Comment by sxx1314** [comment]
> meson-gxm-q201.dtb
> u-boot-p212.bin

h96 pro plus
soc: s912  
ram:3GB

测试使用5.15 不要修改任何东西即可启动，但是启动蓝牙需要改成mod.dtb，缺点ram只识别为2GB。
5.10 uboot需要修改为u-boot-p212.bin，ram正常识别为3GB。
6.0 测试的比较早，直接启动失败之后就没有再测试，应该和5.10一样需要修改uboot.

**Comment by ophub** [comment]
好的，感谢分享

**Comment by mclee23** [comment]
我的海美迪H7四代，U盘制作启动，镜像：Armbian_24.8.0_amlogic_s912_bullseye_6.6.46_server_2024.08.17.img
u-boot.ext 这个文件不需要，删除它
uEnv.txt 改为 meson-gxm-q201.dtb
100M自带的网卡自动获取到地址了，wlan也有信号了
