### ISSUE TITLE
中兴B863AV3.2-M(s905l3a)写入emmc测试

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#741]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [中兴B863AV3.2-M]

**Armbian Version | 系统版本**
 - Kernel Version: [5.10.156]
 - Release: [bullseye]

**Describe the bug | 问题描述**
O大你好，
我把固件刷入U盘后，使用一切正常。然后我执行armbian-install，选择ext4格式，然后选择304 e900v22c那个，想要把系统写入EMMC。这些过程都十分顺利，没有出现错误，等写入完成后，它提示我拔掉USB设备，然后重启。

当我重启后，显示器一直处于黑屏状态，无法启动到系统。然后我又尝试插上USB设备，然后再次重启，这一次设备可以正常进入emmc中的系统，因为可以看到总容量已经变成7.1G（我的U盘是16G的），而且开机状态下，拔掉U盘，系统还是在正常运行。所以现在唯一的问题就是想启动到EMMC中的系统的话，必须要把U盘插上来帮助引导进系统。请问大神我是漏掉了什么步骤吗？麻烦指点指点！

固件使用的是未经任何修改的：
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_bullseye_11.27.0938/Armbian_22.11.0_Aml_s905l3a_bullseye_5.10.156_server_2022.11.27.img.gz

**Comment by ophub** [comment]
这个应该是306，和m401a使用一个，它的安卓系统和M401A通用

**Comment by ophub** [comment]
不用
也可以试一下305的meson-g12a-s905l3a-cm311.dtb

我看了一下之前的贴子，cm311也有人刷中兴的做底包。
你先在usb试改了这个dtb能不能启动，网络是否正确。
/boot/uEnv.txt里改名字，重启

**Comment by ophub** [comment]
https://github.com/ophub/kernel/releases/tag/tools

我在很早前就从贴子里保存了一份别人在m401a里把这个盒子的安卓系统当底包用的固件，昨天我新上传了一个M401a的系统，才把这个另改名回中兴，之前一直是名字叫m401a_b863av3.2

**Comment by Haaooo** [comment]
> https://github.com/ophub/kernel/releases/tag/tools
> 
> 我在很早前就从贴子里保存了一份别人在m401a里把这个盒子的安卓系统当底包用的固件，昨天我新上传了一个M401a的系统，才把这个另改名回中兴，之前一直是名字叫m401a_b863av3.2

这真的是太棒了，因为目前EMMC里的安卓已经被armbian替代了，到时候还可以刷这个固件当底包！

目前我遇到一个麻烦hahaha，如果要引导到U盘的系统，需要在开机时按遥控器左键，但是目前身边没有遥控器，所以上面的方法目前试不了，只能明天去找一个遥控器来用了！害，今天晚上估计入睡会有点困难，因为我已经迫不及待想要试试了！

**Comment by ophub** [comment]
那就还按你的方式，插U盘启动，改也一样，这个改了不合适的dtb不会砖了

**Comment by Haaooo** [comment]
> 那就还按你的方式，插U盘启动，改也一样，这个改了不合适的dtb不会砖了

我目前是把EMMC和U盘里的DTB都改为了M401，然后插上U盘开机，然后引导进了EMMC中的系统，过程中没有看到代码的错误提示

**Comment by ophub** [comment]
你改完了，拔了U盘，重新插电，应该可以从emmc启动吧？

**Comment by Haaooo** [comment]
![屏幕截图_20221128_214417](https://user-images.githubusercontent.com/71207318/204293481-a84f5381-31d5-4a3f-90f4-78939689949c.png)
![屏幕截图_20221128_214654](https://user-images.githubusercontent.com/71207318/204293492-9790e3df-d018-4ae3-bcc1-d5376472b17a.png)
![屏幕截图_20221128_214721](https://user-images.githubusercontent.com/71207318/204293495-93e6a47f-7ad3-4791-a16c-9b171c421a87.png)

**Comment by Haaooo** [comment]
刚才试了一下 ，改完DTB之后，还是跟原来的情况一样，开机灰屏

**Comment by ophub** [comment]
你这就是从emmc启动的。你插着usb运行reboot重启，启动了再reboot重启，再启动后拔了U S B，重新插电启动试试

**Comment by Haaooo** [comment]
好的 我正在试验

**Comment by Haaooo** [comment]
O大 ，等了很久了，ssh链接还是failed。好像确实是没有进入系统，因为正常启动时，盒子的灯会由橙色变为绿色，而且我去路由器后台查看，也没有发现armbian

**Comment by ophub** [comment]
那你插U盘启动两次，再试一下拔了U盘，插电启动。

**Comment by Haaooo** [comment]
我已经按照这样重启了三次，然后就是我上面说的情况

**Comment by Haaooo** [comment]
我盒子的安卓系统不是原版的，是我从别处找到的一个安卓包，有没有可能问题出在这？

**Comment by ophub** [comment]
还有一种作法，更新到5.15.80，更新完启动后，手动删了/boot里面的u-boot.ext和u-boot.emmc，不要用u-boot看看。

`armbian-update -k 5.15.80`

**Comment by Haaooo** [comment]
大佬，5.15的版本我安装过，启动的时候好像会找不到网卡，就phy -19类似的代码

**Comment by ophub** [comment]
这两个版本的区别就是这个u-boot。

**Comment by Haaooo** [comment]
> armbian-update -k 5.15.80

好的我已经在运行手动升级的代码了

**Comment by Haaooo** [comment]
大佬 已经更新完成了 ，下一步如何操作

**Comment by ophub** [comment]
更新吧，你在5.10里用的也是5.15的dtb。这个m401a昨晚上刚提交合并的，kernel仓库的5.10内核里还没有，固件里面的dtb是从当前仓库的目录带的（rebuild时会被kernel解压覆盖了，但这个目前没有被替成对应内核的）

**Comment by Haaooo** [comment]
> 更新吧，你在5.10里用的也是5.15的dtb。这个m401a昨晚上刚提交合并的，kernel仓库的5.10内核里还没有，固件里面的dtb是从当前仓库的bootfs目录带的（rebuild时会被kernel解压覆盖了，但这个目前没有被替成对应内核的）

目前已经更新到5.15.80了 ，然后我照着上面做了。表现是：插着u盘能正常启动，而且没有出现以前遇到过的找不到网卡的错误代码了，但是HDMI输出背景变成了红色。拔掉u盘插电启动时，跟以前的症状相同，指示灯一直橙色，输出黑屏，进不去系统

**Comment by ophub** [comment]
试试改meson-g12a-s905l3a-cm311.dtb

**Comment by Haaooo** [comment]
使用的这个安卓包：
通过百度网盘分享的文件：1-b863av....img
链接：https://pan.baidu.com/s/1mY0K5JncQwZzW0mGkbXnlA?pwd=0000 
提取码：0000 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by ophub** [comment]
手动删了/boot里面的u-boot.ext和u-boot.emmc，不要用u-boot再看看启动情况。
删除这两个文件后再reboot重启

**Comment by ophub** [comment]
cm311也能正常启动？

**Comment by janko888** [comment]
是不是之前那个版本启动ssh的问题到导致能连上去？

**Comment by ophub** [comment]
你正常启动后，可以把那两个#删了，这个只有好处，自动检查重启服务

**Comment by Haaooo** [comment]
> 你正常启动后，可以把那两个#删了，这个只有好处，自动检查重启服务

大神 好消息！！ 拔掉u盘后正常进入系统了！
操作为：删除boot文件夹中的u-boot.ext和u-boot.emmc！

**Comment by ophub** [comment]
这个盒子的通用性太强了，三个dtb通用，难怪之前别人拿它的系统做底包呢。

**Comment by Haaooo** [comment]
O大 现在能脱离u盘进入系统了，但是好像网卡又出现问题了
![image](https://user-images.githubusercontent.com/71207318/204311220-780afdfe-8b3b-46eb-8ee9-b83e1995275a.jpg)

**Comment by Haaooo** [comment]
![image](https://user-images.githubusercontent.com/71207318/204311569-28bfa3fc-bf08-4d69-bdbe-ce3f3488786c.jpg)

**Comment by ophub** [comment]
那你改m401a试试

**Comment by Haaooo** [comment]
> 那你改m401a试试

好像不是这个原因，改回m401a还是出现phy   -19的错误

**Comment by Doboo** [comment]
这款盒子我一直用armbian-install  305   2没有问题的

**Comment by ophub** [comment]
@Doboo 你使用305选项，5.15内核，默认是没有u-boot的。
你有没手动添加复制u-boot呢？
你的安卓系统是原系统？还是刷了第三方的？

**Comment by yangzhuang2333** [comment]
我就是这个盒子，一直苦恼这个问题，插着优盘能进入emmc的系统，必须用优盘引导.放了几天拔掉优盘它又能脱离优盘进入系统了。不知道问题出在哪，这个盒子第三方系统都是刷的v22c的底包，跟这个有关系吗

**Comment by yangzhuang2333** [comment]
> 这款盒子我一直用armbian-install 305 2没有问题的。 Armbian_22.11.0_Aml_s905l3a_bullseye_5.15

我用5.15内核会网卡出错 找不到网卡，另外你安卓系统是什么底包，我是刷的v22c 这个盒子刷回安卓很简单，只要点好刷机软件的开始，同时插上USB跟接通盒子供电，就会进入刷机模式，必须刷机软件2.2的版本，我之前2.1就用是失败

**Comment by yangzhuang2333** [comment]
> > 那你改m401a试试
> 
> 好像不是这个原因，改回m401a还是出现phy -19的错误
> 
> 在这种情况下，我插入u盘引导是能正常进入系统的

你成功了记得分享一下，我整了好久都没成~

**Comment by Haaooo** [comment]
@ophub   O大，我把盒子拆开了。我看了一下主板，上面的存储芯片好像是nand，不是emmc。  这是不是问题的所在？？？
![243DD46B-B374-4580-B92A-510AAD0F220D](https://user-images.githubusercontent.com/71207318/204800861-e679f274-28a5-4d1e-bb74-f852e65e7cfb.jpeg)
![5B22EDFA-0D43-47C7-9A89-BCFA7C159484](https://user-images.githubusercontent.com/71207318/204800923-f0541e8f-0215-443e-96ae-507101524a3a.jpeg)
![CA78EC2F-99F5-4D77-AD2F-6A76A8D611C6](https://user-images.githubusercontent.com/71207318/204800983-b860c9ee-62a2-49ef-b69f-86859cd04e88.jpeg)

**Comment by Haaooo** [comment]
> > > 那你改m401a试试
> > 
> > 
> > 好像不是这个原因，改回m401a还是出现phy -19的错误
> > 在这种情况下，我插入u盘引导是能正常进入系统的
> 
> 你成功了记得分享一下，我整了好久都没成~

咱俩情况是一模一样啊！ 我还有个问题，U盘启动时，如果第二个口插得有u盘或者移动硬盘，就会开机启动一直灰屏

**Comment by yangzhuang2333** [comment]
> > > > 那你改m401a试试
> > > 
> > > 
> > > 好像不是这个原因，改回m401a还是出现phy -19的错误
> > > 在这种情况下，我插入u盘引导是能正常进入系统的
> > 
> > 
> > 你成功了记得分享一下，我整了好久都没成~
> 
> 咱俩情况是一模一样啊！ 我还有个问题，U盘启动时，如果第二个口插得有u盘或者移动硬盘，就会开机启动一直灰屏

你这个就是emmc 这盒子供电有问题 USB供电很差劲的

**Comment by ophub** [comment]
emmc也是nand类的闪存， emmc=nand + 内置主控

内核从u盘启动，然后就可以识别emmc，如果从emmc启动，本身无法驱动emmc，或许和缺了主线u-boot有关：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/56d72de37c37875d0cf92beb66e9dccfefce636b/rebuild#L365-L374


在rebuild制作固件时，不分内核都添加了主线，但写入emmc时默认没有使用（用armbian-install -m yes可以添加主线），对于已经列入支持列表的盒子，写入主线是安全可靠的，但对你这个未知设备，写入不匹配的主线u-boot会砖了。

如果你愿意挑战，可以先下载安卓系统，用短接救砖法试试还原，如果可以还原，有了救砖方案兜底，可以试试用主线。

**Comment by ophub** [comment]
还有一种方式是刷不同的安卓系统。上面也有人反馈他用305默认就可以正常使用。

安卓系统主要是使用它的bootloader ，分区前4m，它能正常引导。

**Comment by Haaooo** [comment]
> 还有一种方式是刷合适的安卓系统。上面也有人反馈他用305默认就可以正常使用。说明他的安卓系统的bootloader能正常引导。

O大，现在目前的情况是：使用5.10固件，不做任何更改，写入emmc时选择304，然后格式选择btrfs格式，拔掉u盘可以顺利引导进emmc系统。使用上没有任何问题，但是执行reboot  或者直接断电重启会大概率开不了机（一会可以一会不可以）

**Comment by Haaooo** [comment]
@yangzhuang2333

**Comment by ophub** [comment]
说明你安卓系统的bootloader不匹配。要MAINLINE_UBOOT或者ANDROID_UBOOT有一个可以用的就好了。可以找几个合适的安卓系统刷一下。

之前别的盒子也会用中兴的系统，不知道能不能刷这些盒子，用E900V22C或者cm311的安卓，写emmc时也对应地选择304或者305

你现在刷了304的配置，试试刷304自动备份的mybootloader.img

**Comment by Haaooo** [comment]
> 说明你安卓系统的bootloader不匹配。要MAINLINE_UBOOT或者ANDROID_UBOOT有一个可以用的就好了。可以找几个合适的安卓系统刷一下。
> 
> 之前别的盒子也会用中兴的系统，不知道能不能刷这些盒子，用E900V22C或者cm311的安卓，写emmc时也对应地选择304或者305
> 
> 你现在刷了304的配置，试试刷304自动备份的mybox-bootloader.img

大佬 ，我没有任何相关的专业知识。请问O大能否细说一下操作步骤啊

**Comment by ophub** [comment]
```
#bootloader根据你自己上传的路径和文件名改对了
MYBOX_UBOOT=/root/cm311-bootloader.img

#用lsblk看一下，你的emmc应该是mmcblk2
DEV_EMMC=/dev/mmcblk2

#添好上面的两个值，下面的两条dd命令依次复制粘贴回车执行
dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=1 count=444
dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1

#写完了保存重启
sync && reboot
```

**Comment by yangzhuang2333** [comment]
> ```
> #写安卓bootloader也是有风险的，如果不可用也是会砖了，如果会短接救砖再试。下面4步，依次改好了，复制粘贴回车执行
> 
> #1. 找cm311用户要一个他备份的文件，它自动备份的路径看上一贴，把他的bootloader上传到你的盒子，根据你自己上传的路径和文件名改对了
> MYBOX_UBOOT=/root/cm311-bootloader.img
> 
> #2. 用lsblk看一下，你的emmc应该是mmcblk2
> DEV_EMMC=/dev/mmcblk2
> 
> #3. 添好上面的两个值，下面的两条dd命令依次复制粘贴回车执行
> dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=1 count=444
> dd if=${MYBOX_UBOOT} of="${DEV_EMMC}" conv=fsync bs=512 skip=1 seek=1
> 
> #4. 写完了保存重启
> sync && reboot
> ```

这个就是刷的v22c的安卓包  刷回安卓很简单的 只要准备好刷机软件点开始等待，然后同时接通12v跟USB线。不用拆机

**Comment by Haaooo** [comment]
@ophub O大你好

我按照你的建议刷入了这个安卓固件（刷写时勾选擦除flash和bootloader）
https://github.com/ophub/kernel/releases/download/tools/android_tv_m401a_s905l3a.tar.xz

内核选择5.15  bullseye
dtb选择m401
Armbian-install选择m401的  btrfs格式

使用起来功能没有问题，但是经过测试，连续两个晚上都会报内核恐慌，然后卡死。早上起床发现时只能重启。
![59B3972E-F19E-4773-A82F-47A28F6B42E7](https://user-images.githubusercontent.com/71207318/205418944-8d10977a-46af-4d33-b4da-1c0dc0f21aca.jpeg)

**Comment by ophub** [comment]
最近5.15/6.0内核都收到多个反馈内核恐慌的现象。
tx3用户反馈切换到5.10后稳定运行几天了。

你可以更新内核到5.10/5.4试一试

**Comment by Haaooo** [comment]
> 你的测试可以说明换m401a的安卓系统是可行的，主要是使用了他的bootloader引导。
> 
> 最近5.15/6.0内核最近两周内都收到多个反馈内核恐慌的现象。 tx3用户反馈切换到5.10后稳定运行几天了。
> 
> 你可以更新内核到5.10/5.4试一试

好的 我尝试一下再过来反馈

**Comment by Haaooo** [comment]
> 你的测试可以说明换m401a的安卓系统是可行的，主要是使用了他的bootloader引导。
> 
> 最近5.15/6.0内核最近两周内都收到多个反馈内核恐慌的现象。 tx3用户反馈切换到5.10后稳定运行几天了。
> 
> 你可以更新内核到5.10/5.4试一试

大佬，更换为5.10内核后，又出现写入EMMC后拔u盘灰屏不启动的情况了。。

**Comment by ophub** [comment]
插着U盘能启动，不插U盘无法启动？

**Comment by Haaooo** [comment]
> 插着U盘能启动，不插U盘无法启动？
> 如果U盘插着能启动EMMC的系统，你这样先挂机2天看看，有没有5.15那个一天宕机问题。

好的  好奇怪啊。明明只是更换内核什么都没动。不管是用命令直接更新内核还是u盘重刷5.10的系统然后写入emmc，得到的结果都是拔优盘启动时灰屏

**Comment by yangzhuang2333** [comment]
> > 插着U盘能启动，不插U盘无法启动？
> > 如果U盘插着能启动EMMC的系统，你这样先挂机2天看看，有没有5.15那个一天宕机问题。
> 
> 好的 好奇怪啊。明明只是更换内核什么都没动。不管是用命令直接更新内核还是u盘重刷5.10的系统然后写入emmc，得到的结果都是拔优盘启动时灰屏

我现在刷了上面给的那个401的安卓固件然后下载了最新的5.10内核的镜像写入emmc选的btrfs完成之后重启再关机，现在脱离优盘能开机了，我再多试几次

**Comment by yangzhuang2333** [comment]
现在重启了三次 用reboot重启开机能获取到ip地址但是ssh链接不上，我又硬重启会出现一分半的倒计时，插拔网线以后顺利连接上，出现了获取两个ip的现象

**Comment by ophub** [comment]
/etc/custom_service/start_service.sh


https://github.com/ophub/amlogic-s9xxx-armbian/blob/1c09d2913da4606b67e7e517887c25823288b618/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L26-L27

你复制现在的这2行ssh代码，改下你本地的这个文件对应的2行代码，然后重启测试ssh连接不上的问题。

**Comment by yangzhuang2333** [comment]
这次重启没有提示一分半倒计时但是连接不上ssh 获取的两个ip都不行。
![IMG_20221203_213418](https://user-images.githubusercontent.com/119402649/205443466-d1814f5d-8676-4c4c-9c01-8142dd76a289.jpg)
提示这个屏幕上

**Comment by yangzhuang2333** [comment]
我试了复制执行两行代码重启之后还是连接不上ssh

**Comment by ophub** [comment]
你这截图，正好把最上面的ssh的提示给截取没了。

**Comment by ophub** [comment]
`cat /etc/custom_service/start_service.sh`截个图

**Comment by yangzhuang2333** [comment]
_              _   ____  ___   ___  ____  _ _____
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|| |___ /  __ _
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \| | |_ \ / _` |
 / ___ \| | | | | | |  ___) \__, | |_| |___) | |___) | (_| |
/_/   \_\_| |_| |_|_| |____/  /_/ \___/|____/|_|____/ \__,_|

Welcome to Armbian 23.02.0-trunk Jammy with Linux 5.10.156-ophub

System load:   38%              Up time:       1 min
Memory usage:  6% of 1.91G      IP:            192.168.123.136
192.168.123.37
CPU temp:      28°C             Usage of /:    15% of 6.6G
RX today:      45.1 MiB

[ 0 security updates available, 6 updates total: apt upgrade ]
Last check: 2022-12-03 22:01

[ General system configuration (beta): armbian-config ]

Last login: Sat Dec  3 21:40:32 2022 from 192.168.123.98
root@armbian:~# cat /etc/custom_service/start_service.sh
#!/bin/bash
#========================================================================================
#
# This file is licensed under the terms of the GNU Genera

**Comment by yangzhuang2333** [comment]
![Screenshot_2022-12-03-22-08-51-770_com sonelli juicessh](https://user-images.githubusercontent.com/119402649/205444971-03533ceb-f189-49b6-98e6-877f3839e2b2.jpg)

**Comment by yangzhuang2333** [comment]
谢谢大佬已经用vi命令改了 改了两行  确实可以了  下一步就是插优盘看能不能启动了，这盒子USB供电出奇的差

**Comment by ophub** [comment]
总结起来就是找到了合适的安装使用方法，那我添加一条这个盒子的配置信息和贡献者名单。

**Comment by Haaooo** [comment]
> 我总结一下，刷楼上给的401a安卓固件以后用最新版5.10内核的镜像写入emmc选btrfs分区，写入完成之后重启一遍再关机一遍，拔了优盘就能从emmc启动了。我试了十几遍都能开起来，剩下的就是会启动后报那个一分半的倒计时还有启动后ssh不能用，楼上大佬已经给了解决方案，估计是这几个版本固件的问题 后面可能会修复。有问题我再报告哈。

请问你boot分区做修改了吗？ 写入emmc时是选的m401吗？

**Comment by yangzhuang2333** [comment]
> 

写入优盘后改了那个文本文件把dtb改成了401a 写入的时候选的也是401a的

**Comment by QAWEI** [comment]
有没有哪位大哥刷过中兴b860av2.1-T的盒子，该用哪款dtb啊

**Comment by yangzhuang2333** [comment]
最新汇报，我上次刷的5.10内核系统之后稳定跑网心云之后重启就再也连不上ssh了,连接显示器也跑码，只是报错我看不懂。我就又用优盘刷最新版5.15内核系统从优盘启动黑屏，不得已我又刷回401a的安卓系统 然后从安卓系统用软件切换启动优盘里的armbian,经测试用401a的dtb报错，又用了v22c的成功启动，写入emmc选的401a.现在开机正常。还在稳定测试中，给后面新版固件启动黑屏的一个参考。

**Comment by RtgeTY** [comment]
O大您好
我用的您编译的固件刷好了，但是有些还是不太懂，想问一下有没交流群，我箱请教一些问题。
我用的是中兴B863AV3.2-M盒子，刷机固件，想更新固件，是不是需要从新刷入安卓，然后在刷新固件。我还想在盒子里面安装广告拦截和科学插件，但是我不太会，想向您请教一下。
<img width="1280" alt="微信截图_20230206175518" src="https://user-images.githubusercontent.com/97677494/216943105-d4e6b99c-6fbc-4ab2-b223-2e316cd4ad5a.png">

<img width="1280" alt="微信截图_20230206175534" src="https://user-images.githubusercontent.com/97677494/216943112-41aaee9f-9e73-4516-b9f1-7e04aa5acf9d.png">

**Comment by ophub** [comment]
不用重装安卓，也不用U盘重装了。

想换个系统时，在系统——-晶晨宝盒———手动上传更新（上传img后会显示更新按钮），也可以用————在线下载更新（会从github下载最新打包的系统）

想更新内核也同路径，上传内核文件。

这些使用方法在amlogic-s9xxx-openwrt仓库和luci-app-amlogic仓库里有祥细介绍。


https://github.com/ophub/amlogic-s9xxx-openwrt


https://github.com/ophub/luci-app-amlogic

**Comment by RtgeTY** [comment]
O大，有没有群，我想加个群，好向大家请教

**Comment by ophub** [comment]
我没有群，编译openwrt的方法是一样的，你从任何渠道学习的方法都通用。

**Comment by RtgeTY** [comment]
> 我没有群，使用不同的上游源码编译openwrt的方法是一样的，你从任何渠道学习的方法都通用。

好的，好的，非常感谢O大

**Comment by fbigun** [comment]
中兴B863AV3.1-M2，也能通用这个包吗

**Comment by jugg718** [comment]
> 

我最近也是被开机黑屏这个问题折磨疯了，要是有armbian线刷包就好了，卡刷太不稳定了

**Comment by orchia2000** [comment]
我的盒子是b863av3.1-m2,正在安装，也是没有U盘启动不了。

**Comment by orchia2000** [comment]
U盘里只有s905_autoscript、s905_autoscript.cmd、u-boot.ext这三个文件就可以启动。

**Comment by Alvin1986** [comment]
写入emmc后，拔掉U盘无法进入系统是怎么回事？ U盘是8g  emmc是128g

**Comment by Alvin1986** [comment]
> 我总结一下，刷楼上给的401a安卓固件以后用最新版5.10内核的镜像写入emmc选btrfs分区，写入完成之后重启一遍再关机一遍，拔了优盘就能从emmc启动了。我试了十几遍都能开起来，剩下的就是会启动后报那个一分半的倒计时还有启动后ssh不能用，楼上大佬已经给了解决方案，估计是这几个版本固件的问题 后面可能会修复。有问题我再报告哈。

U盘8g  emmc128g   写入emmc后拔掉U盘 无法引导进入系统  如何把引导改为emmc？

**Comment by Alvin1986** [comment]
> 我的盒子是b863av3.1-m2,正在安装，也是没有U盘启动不了。

拔掉U盘就是无法引导进入系统。一样的情况，该如何修改位emmc引导?

**Comment by yan0255** [comment]
怎么下载的啊 大哥们

**Comment by lingchen-jiager** [comment]
20230804 测试 
移动办宽带送的机顶盒，B863AV3.2-M(s905l3a-b)

和上面一样的问题，拔掉u盘再重启就无法进入系统，但是不拔u盘就可以正常进入。

**Comment by lingchen-jiager** [comment]
经过摸索，成功实现拔掉u盘也能正常进系统。分享两次操作的不同：

**失败：**
文件格式选择的是ext4
dtb选择的是306

**成功：**
文件格式选择的是btrfs
dtb选择的是305

**Comment by mia0x75** [comment]
> 经过摸索，成功实现拔掉u盘也能正常进系统。分享两次操作的不同：
> 
> **失败：** 文件格式选择的是ext4 dtb选择的是306
> 
> **成功：** 文件格式选择的是btrfs dtb选择的是305

请问305/306是什么意思？另外，写入emmc之后，如果想从USB重新刷一次最新版本应该怎么做？感谢。

**Comment by Boofeifan** [comment]
O大太有爱了 支持！

**Comment by cjd6568358** [comment]
2025/07/17 经测试以下组合写入emmc后拔掉U盘重启一切正常
安卓底包：android_tv_m401a_s905l3a
Armbian：Armbian_25.08.0_amlogic_s905l3a_noble_5.15.187_server_2025.07.11.img
armbian-install：
dtb选择的是306
文件格式选择的是ext4

**Comment by cjd6568358** [comment]
2025/07/17 经测试以下组合写入emmc后拔掉U盘重启一切正常
安卓底包：android_tv_m401a_s905l3a
Armbian：Armbian_25.08.0_amlogic_s905l3a_noble_5.15.187_server_2025.07.11.img
armbian-install：
dtb选择的是306
文件格式选择的是ext4

**Comment by justin-xjp** [comment]
> 2025/07/17 经测试以下组合写入emmc后拔掉U盘重启一切正常 安卓底包：android_tv_m401a_s905l3a Armbian：Armbian_25.08.0_amlogic_s905l3a_noble_5.15.187_server_2025.07.11.img armbian-install： dtb选择的是306 文件格式选择的是ext4

这样刷完有HDMI输出吗？

**Comment by riverai** [comment]
> 中兴B863AV3.2M 安装了openwrt系统到EMMC 运行了一个月 死机 不能启动 插U盘也启动不了 线刷安卓固件卡7% 是不是BL坏了 有什么解决办法吗

这个是emmc坏了，我的cm'201盒子有两个都是这个卡7%
