### ISSUE TITLE
有人研究m401a通过耳机孔输出音频吗？

### ISSUE THREAD

**Issue by bokeylee** [ophub/amlogic-s9xxx-armbian#742]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model m401a

**Armbian Version | 系统版本**
 - Kernel Version: e.g. 5.15.80
 - Release: jammy

**Describe the bug | 问题描述**
~~这两天在#732 中已经实现m401a的写入与正常启动，但无意中发现一个怪问题~~
~~相同dtb下，使用U盘启动时，不加任何u-boot.ext，功能正常，HDMI也可以输出声音~~
~~使用EMMC启动时，不加u-boot.emmc，播放音乐时会输出读不到声卡（暂且这么说）的报错，HDMI没办法输出声音~~
```
fe.dai-link-0: ASoc: no backend DAIs enabled for fe.dai-link-0
fe.dai-link-0: ASoc: dpcm_fe_dai_prepare() failed (-22)
```
~~一开始以为是u-boot的问题，尝试把之前u盘测试正常的u200 u-boot改成u-boot.emmc，但启动不了，纯黑屏~~
~~于是现在就百思不得其解了……又是玄学么……~~
**重新刷了一遍居然又正常了**，估计是安装了某个东西导致的……

那么就是第二个问题：有人实现从RCA口（耳机孔）输出音频了吗，u盘启动的状态下，我找了根转接线插到电视，可以通过CVBS输出视频信号，但没有声音，不知道该从什么方向折腾？

**Comment by iamhyde** [comment]
我用5.10.154没问题，不过只能hdmi输出音频，在HA里做TTS，没法用耳机孔，显示声卡就一个u200，也没看到能切换的

**Comment by uncle-wong** [comment]
把0x02这个电平搞一下试试呢
关闭和打开的命令分别为：
gpioset -s 1 -m time 0 2=0
gpioset 0 2=1
其中上面这个2=0对应avout_mute-gpios = <0x70 0x02 0x00>中的0x02，如果不好使，试试减少一位。1=0,试试看呗。

**Comment by uncle-wong** [comment]
安卓的dtb能否发一份？
