### ISSUE TITLE
armbian什么更新那内核到6.0？

### ISSUE THREAD

**Issue by HJYAlive** [ophub/amlogic-s9xxx-armbian#747]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [ S095d]
 - Model [斐讯n1】

**Armbian Version | 系统版本**
 - Kernel Version: [5.15]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
~:# armbian-update -k 6.0.10 -v stable -m yes
[ STEPS ] Ready to update, please wait...
[ INFO ] Custom setting parameters: [ -k 6.0.10 -v stable -m yes ]
[ STEPS ] Start initializing the environment...
[ INFO ] Set the kernel version name: [  ]
[ INFO ] Set the kernel version branch: [ stable ]
[ INFO ] Use mainline u-boot: [ yes ]
[ INFO ] Current version: 5.15.80, Latest version: 5.15.80
[ FINISH ] Already the latest version, no need to update.

**Comment by ophub** [comment]
日志很清楚，6.0.10内核是最新版

可以更新低版本试试
`armbian-update -k 6.0.9`

**Comment by HJYAlive** [comment]
:# armbian-update -k 6.0.9
[ STEPS ] Ready to update, please wait...
[ INFO ] Custom setting parameters: [ -k 6.0.9 ]
[ STEPS ] Start initializing the environment...
[ INFO ] Set the kernel version name: [  ]
[ INFO ] Set the kernel version branch: [ stable ]
[ INFO ] Use mainline u-boot: [ no ]
[ INFO ] Current version: 5.15.80, Latest version: 5.15.80
[ FINISH ] Already the latest version, no need to update.
已经是最新版本，无需更新。
个人理解为支持所有内核，但是日志告诉我已为最新。（设备已是全局互联网）
现在fork长裤。按教程添加koken令牌。然后运行yml编译 jammy。 s905d   6.0.1   预期结果是生成一个包。已经在等待结果。
感谢回复

**Comment by ophub** [comment]
https://github.com/ophub/kernel/tree/main/pub/stable


https://github.com/ophub/amlogic-s9xxx-armbian#update-armbian-kernel

**Comment by HJYAlive** [comment]
github编译成功。n1最新内核包！目前正常使用。感谢大佬回复与支持！
https://github.com/HJYAlive/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_jammy_12.01.0706

**Comment by ophub** [comment]
好的，恭喜你
