### ISSUE TITLE
大佬，这个怎么连接wifi？

### ISSUE THREAD

**Issue by cui8** [ophub/amlogic-s9xxx-armbian#748]
我的机顶盒是cm311-1a，买的无线usb网卡，怎么输入无线网密码，联网

**Comment by ophub** [comment]
armbian-config

**Comment by cui8** [comment]
> armbian-config

大佬，我刷了这个armbian，无线网卡是不是就没有限制了，随便无线usb网卡都支持？

**Comment by cui8** [comment]
> armbian-config

谢谢大佬第一时间回复，我还是用有线吧，方便、简单。
