### ISSUE TITLE
网卡不工作，几秒后就断开

### ISSUE THREAD

**Issue by payzulla0706** [ophub/amlogic-s9xxx-armbian#753]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [e900v22c]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.80]
 - Release: [Armbian_22.11.0_Aml_s905l3a_jammy_5.15.80_server_2022.11.29.img]

**Describe the bug | 问题描述**
我的设备时e900v22c 下载的版本是最新版s905l3a的固件
Armbian_22.11.0_Aml_s905l3a_jammy_5.15.80_server_2022.11.29.img
Armbian_23.02.0_Aml_s905l3a_jammy_5.15.80_server_2022.12.01.img
初次启动时有线网卡不能工作（刚启动时有线网获取IP中，过三四秒后就断开，之后网卡一直显示断开状态）这个设备安装这个固件要对网卡进行别的设置么？
原谅我是个菜鸟

**Comment by ophub** [comment]
启动后，试试手动复制u-boot

```
cd /boot
cp -f u-boot-e900v22c.bin u-boot.ext
sync && reboot
```

**Comment by payzulla0706** [comment]
@ophub 


> 启动后，试试手动复制u-boot
> 
> ```
> cd /boot
> cp -f u-boot-e900v22c.bin u-boot.ext
> sync && reboot
> ```
![微信图片_20221202181729](https://user-images.githubusercontent.com/118226806/205270912-bc3f0d01-952f-4d3a-9bf4-c9c8d0c91610.jpg)
（第一次提问的时候忘记上传报错的图片了）
u-boot-e900v22c.bin u-boot.ext>>>>再次麻烦你，这个操作可以在烧录U盘完成后还没有插入电视盒子之前通过电脑去修改吗？因为我没有USB键盘，想解决网卡问题后用家用电脑通过SSH去安装后续

**Comment by wxjiyc** [comment]
> 

SoC是S905L3A-B吗？

**Comment by payzulla0706** [comment]
> > 
> 
> SoC是S905L3A-B吗？

机顶盒是E900v22C   SoC是S905L3A

**Comment by ophub** [comment]
写入USB，重新在电脑上拔插U盘，会显示出BOOT分区，双击打开可以复制。
这个盒子只看外壳可能不准确，你仔细对比下主板上的SOC等芯片
https://docs.qq.com/doc/DWFprWWxZa290VXNk

**Comment by payzulla0706** [comment]
> 启动后，试试手动复制u-boot
> 
> ```
> cd /boot
> cp -f u-boot-e900v22c.bin u-boot.ext
> sync && reboot
> ```

我好像解决了这个问题
我的做法是U盘烧录完之后 直接在电脑打开U盘ROOT分区 复制了一份u-boot-e900v22c.bin并重命名为u-boot.ext
并把U盘 /booot/extlinux 目录下的extlinux.conf.bak也在这个目录复制一份 重命名为extlinux.conf
然后插上U盘顺利启动之后网卡工作正常 已经连上SSH了  
不知道这样做对不对 但是问题解决了
感谢

**Comment by payzulla0706** [comment]
> 写入USB，重新在电脑上拔插U盘，会显示出BOOT分区，双击打开可以复制。 这个盒子只看外壳可能不准确，你仔细对比下主板上的SOC等芯片 https://docs.qq.com/doc/DWFprWWxZa290VXNk

在这之前刷了别的版本 不用修改就可以正常联网的
[https://github.com/zzcand111/amlogic-s9xxx-armbian/releases](url)
Armbian_22.05.0_Aml_s905x2-E900V22C_focal_5.15.28_2022.03.14.0037.img.gz


不过按照你的帮助 问题已经快速解决了 谢谢你

**Comment by ophub** [comment]
不用extlinux.conf，复制了u-boot.ext即可。
两个月前，固件打包时默认复制了这个文件，现在的只在5.10上默认复制了，其他版本默认没有添加

**Comment by payzulla0706** [comment]
> 不用extlinux.conf，复制了u-boot.ext即可。 两个月前，固件打包时默认复制了这个文件，现在的只在5.10上默认复制了，其他版本默认没有添加
又有了新问题 上次问题解决后 我选择了在U盘使用系统 没有写入emmc 
在软件中心装了docker 和homeassistant 之后重启就一直反复这些代码  在安装docke 之前也是有时候能进系统 有时候启动又不能进系统    是我忘记配置什么了吗？
![1938](https://user-images.githubusercontent.com/118226806/205359781-0ad6d61f-f8da-4532-9d77-e16f5903d185.jpg)

**Comment by payzulla0706** [comment]
@ophub  再次麻烦你···上面的问题解决了  可能是U盘不适合吧 换了一个U盘可以了
但是每次新烧录U盘第一次启动都正常，设置完用户名密码等等之后第一次重启就一直卡在图中的位置 SSH无法连接 但是能ping通，最后的一句是armbian login:    我没USB键盘所以没法手动登录行不行 
最后我想问的是 这个系统每次重启都要用USB键盘登录之后才能SSH登录使用吗？能不能设置自动登录等待SSH登录？
![55555](https://user-images.githubusercontent.com/118226806/205402115-898bd7e3-f57d-45cf-8dc9-6a5367d4d294.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/685f1a0b3ae0391d915d24ba549943f1f3cf0d60/build-armbian/common-files/rootfs/etc/custom_service/start_service.sh#L26-L27

/etc/custom_service/start_service.sh 删除两行的#重启

**Comment by payzulla0706** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/685f1a0b3ae0391d915d24ba549943f1f3cf0d60/build-armbian/common-files/rootfs/etc/custom_service/start_service.sh#L26-L27
> 
> /etc/custom_service/start_service.sh 删除两行的#重启

OK 了 完美~~
