### ISSUE TITLE
请教大佬个问题：已安装到盒子EMMC内的armbian系统怎么备份成镜像文件

### ISSUE THREAD

**Issue by Lamp2017** [ophub/amlogic-s9xxx-armbian#754]
设备:N1
使用的固件：Armbian_22.11.0_Aml_s905d_bullseye_5.15.80_server_2022.11.29.img
armbian已安装到EMMC内存中，并把需要的软件包都安装配置好了，为了以后出问题恢复方便，想请问下大佬，有没有什么办法可以把整个系统备份成镜像文件， 以后使用中有什么问题，直接用这个镜像文件进行恢复。

**Comment by ophub** [comment]
armbian-ddbr

选择b备份生成一个文件，路径在U盘的/ddbr/BACKUP-arm-64-emmc.img.gz

选择r是恢复，用刚才备份的文件可恢复
