### ISSUE TITLE
UNT403A使用"armbian-swap 1"创建交换内存失败

### ISSUE THREAD

**Issue by tt555-1** [ophub/amlogic-s9xxx-armbian#755]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**UNT403A
 - SOC: s905l3a

**Armbian Version | 系统版本**armbian

**Describe the bug | 问题描述**
在使用finalshell过程中，发现系统没有交换内存，然后使用armbian-swap 1命令创建交换内存，过程中有报错，交换内存创建失败
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

![01](https://user-images.githubusercontent.com/95523674/205325261-fbd75e20-1971-486b-b36c-cf8aae563575.png)

**Comment by ophub** [comment]
空间不够吧，你运行在emmc还是U盘

**Comment by Yxini** [comment]
我的我家云L1PRO 也发现了同样的问题，没法扩容SWAP。
![图片](https://user-images.githubusercontent.com/47093205/210030604-92f2b8e4-a742-4ebb-b1be-8a9393da8d08.png)

**Comment by ophub** [comment]
```
lsblk
cat /etc/ophub-release
```

截图发下

**Comment by Yxini** [comment]
lsblk
![图片](https://user-images.githubusercontent.com/47093205/210031618-ae0e2be6-bfc2-4040-b58a-d39f4c7ffc49.png)
cat /etc/ophub-release
![图片](https://user-images.githubusercontent.com/47093205/210031635-00a3512d-eb72-4b07-a519-3d49f4775599.png)

**Comment by ophub** [comment]
`df -hT`
截图，看看p2还剩多少空间

**Comment by Yxini** [comment]
df -hT
![图片](https://user-images.githubusercontent.com/47093205/210032017-0d5cfb53-ef94-44fe-9d42-b45c6337b044.png)

**Comment by ophub** [comment]
`armbian-sync`
你先同步下最新脚本，然后再`armbian-swap 1`创建试试，有错误截图

**Comment by Yxini** [comment]
armbian-sync
![图片](https://user-images.githubusercontent.com/47093205/210032132-ba1fdbd6-d78c-4816-8842-7442d58d5b64.png)
armbian-swap 1
![图片](https://user-images.githubusercontent.com/47093205/210032162-f392f1ed-95d1-4146-833a-1800a2dc8838.png)
依然失败

**Comment by ophub** [comment]
![Snip20221230_5](https://user-images.githubusercontent.com/68696949/210032333-4c9fe0e5-691e-4c5d-9dc2-3e462dc0e49f.png)


我也是ext4格式，创建虚拟内存没问题。

**Comment by Yxini** [comment]
那我重启再试试看

**Comment by Yxini** [comment]
![图片](https://user-images.githubusercontent.com/47093205/210032537-5eae70b2-7e7b-49e2-af58-ca1d06e77370.png)
还是不行，这次好像直接变成0了，之前还有490M的

**Comment by ophub** [comment]
`dd if=/dev/zero of=/root/1g.bin bs=1G count=1  conv=fsync`

你执行这条命令，看看能不能正常执行

**Comment by Yxini** [comment]
![图片](https://user-images.githubusercontent.com/47093205/210032646-226d9ca2-126d-4c39-95bb-cb292469cade.png)
可以正常执行。

**Comment by ophub** [comment]
删除刚才创建的文件吧： `rm -f /root/1g.bin`
再试试这个： `dd if=/dev/zero of=/mnt/.swap/swapfile bs=1G count=1  conv=fsync`

**Comment by Yxini** [comment]
![图片](https://user-images.githubusercontent.com/47093205/210032892-363bad15-1fed-4294-abce-21f8868576f0.png)
好像都能正常执行。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/70ba7bd482386aab80cf750ef179d8f8f0c5ae2b/build-armbian/armbian-files/common-files/usr/sbin/armbian-swap#L101

一模一样的创建命令，这怎么解释呢，我再想想为什么。

**Comment by Yxini** [comment]
已经删除，但是我用glances看，好像还是0
![图片](https://user-images.githubusercontent.com/47093205/210033019-88010328-6306-4e9b-85f4-463d0b0c7b14.png)

**Comment by ophub** [comment]
我更新了下代码，你再试试，截图反馈下结果

01. 执行： `rm -rf /mnt/.swap`
02. 执行： `armbian-sync`
03. 执行： `armbian-swap 1`

**Comment by Yxini** [comment]
成功了
![图片](https://user-images.githubusercontent.com/47093205/210036755-b6813a86-9e5d-4b5e-9b1e-be00da23f54e.png)
![图片](https://user-images.githubusercontent.com/47093205/210036765-8c4b83f4-c65f-4500-8cf3-88eabd2e9d56.png)

**Comment by Yxini** [comment]
感谢o大！

**Comment by ophub** [comment]
在这个更新里： https://github.com/ophub/amlogic-s9xxx-armbian/commit/364cf16dbfaeeb09d8aa179d082543e80e7c58dd
实质上我只改了一句话，我感觉他不认1G这个单位，我改成了byte。按说咱们系统完全相同，我在rock5b上测试也可以，他也是rockchip系列，在其他amlogic上测试也可以。难道我家云的emmc不认1G这个语法？

`dd if=/dev/zero of=${SWAP_PATH}/swapfile bs=1G count=${swap_gb} conv=fsync && sync` 

改为了

`dd if="/dev/zero" of="${SWAP_PATH}/swapfile" bs="1024" count="$((1048576 * ${swap_gb}))" conv="fsync"`

**Comment by Yxini** [comment]
这种太专业的，我也看不懂。不过我也是这几天才注意到swap好小，每天早上打开终端都会连接不上。一看就是这个swap报红，然后才搜这个swap，结果发现报错才反馈这个问题。

**Comment by ophub** [comment]
这个虚拟内存对你很有用，你刚创建就被用上了，我这物理内存都用不完。
感谢你的测试反馈，总算解决了，之前也有人反馈过，我看来看去，测来测去的找不到原因。

**Comment by Yxini** [comment]
因为我家云就1G物理内存真的低的可怜，不用虚拟内存完全就没用。
