### ISSUE TITLE
O大， 写入EMMC后，22端口默认关闭了 是怎么回事呢

### ISSUE THREAD

**Issue by 121592512** [ophub/amlogic-s9xxx-armbian#756]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/685f1a0b3ae0391d915d24ba549943f1f3cf0d60/build-armbian/common-files/rootfs/etc/custom_service/start_service.sh#L26-L27

/etc/custom_service/start_service.sh 删除两行的#重启
