### ISSUE TITLE
hk1 box 执行 armbian-install 后拔掉U盘无法进系统。

### ISSUE THREAD

**Issue by urenai** [ophub/amlogic-s9xxx-armbian#757]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1 box]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.80]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
安装到emmc后，拔掉U盘，重启，不显示。过几分钟，插键盘，键盘没电，切换大小写无效。

**Comment by SudekiMing** [comment]
Device Information | 设备信息

SOC: [e.g. S095x4]（电路板上丝印是：S905X4_4BIT_V11）
Model [e.g. HK1 box]
Armbian Version | 系统版本

Kernel Version: [e.g. 5.10.156]
Release: [e.g. bullseye]
Describe the bug | 问题描述
遇到类似的问题，使用TF卡启动，安装到emmc后，断电拔掉TF卡，重启，无法从emmc启动，屏幕不显示启动任何信息

**Comment by ophub** [comment]
hk1使用5.15不用u-boot.ext

**Comment by SudekiMing** [comment]
我使用5.15的内核从TF卡都启动不了了（5.15的固件中，BOOT分区下本就是没有u-boot.ext）
测试了下面两个版本的固件都是这种情况：
Armbian_23.02.0_Aml_s905x3_bullseye_5.15.80_server_2022.12.01
Armbian_22.11.0_Aml_s905x3_jammy_5.15.80_server_2022.11.29
Armbian_22.08.0_Aml_s905x3_jammy_5.15.57_server_2022.07.28

**Comment by ophub** [comment]
用usb试听

tf/sd有的设备不行，有干扰。

最新的5.15.80移除了一个补丁，gtk-pro用户几天前测试反馈，移除后可以正常从sd卡启动和使用了。

**Comment by SudekiMing** [comment]
大佬威武，用usb，SD卡和emmc启动均正常，成了，多谢

**Comment by SudekiMing** [comment]
大佬威武，用usb，SD卡和emmc启动均正常，成了，多谢

**Comment by urenai** [comment]
昨晚我USB/SD都测试了  jammy【5.15.80】，后来我以为是内核问题，又下载了 jammy【5.10.156】 USB 和 / SD 安装后，都不能从 EMMC 启动。 
----------
测试无u-boot.ext     jammy【5.15.80】 卡开机画面。
----------
[SudekiMing]  ：  你是使用什么版本？ jammy?  bullseye?

**Comment by SudekiMing** [comment]
最新的Armbian_23.02.0_Aml_s905x3_bullseye_5.15.80_server_2022.12.01版本

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/707

你看这个GTK-PRO的用户，上周他反馈内核恐慌后，f大移除了5.15的那个补丁后重新打包了内核，让他看看测试结果，经过他的实测已经可以正常在SD卡使用了，之前也是一直内核恐慌。

但是如果有USB，我还是不建议使用SD/TF卡，比较而言，USB启动更稳定。SD/TF启动的症结问题我之前也请教过f大有没有根治的办法，他建议体质弱的一些盒子中添加或更换几个电容。

**Comment by SudekiMing** [comment]
ok

**Comment by urenai** [comment]
@ophub  你好！
首先，我有一些用户层软件开发的经验和能力。
我只是想声明，我是在用心去解决这个问题。
我反馈一下今天的测试结果。
-------
1//我现在很疑惑，因为盒子的电源接口不是很稳定(已经退货，申请换货。)，我担心是因为接口导致供电不稳，所以无法正确引导。
2//不复制u-boot-x96maxplus.bin 改 u-boot.ext 任然无法启动USB。（ver：bullseye）
ps：今天是使用U盘，非SD卡。
--------
我现在  非常 苦恼，一次不是很满意的网购。。。。。
盒子已换，静等归来。。。。。

**Comment by JFLim1** [comment]
> Look at this GTK-PRO user, after he reported a kernel panic last week, fda removed the 5.15 patch and repackaged the kernel, let him see the test results, after his actual test, it can be used normally on the SD card Yes, it has been a kernel panic before.

Hi @ophub,  

Device: Beelink GT King Pro (Rev A)

Let me clarify, Kernel-5.15.y (before 5.15.80-flippy-79+o) will NOT boot from SD Card. I/O Error -- basically not recognising SD Card at all, NOT Kernel Panic.  With kernel-5.15.80-flippy-79+o it can boot on SD Card or on USB and recognise SD Card.  Thanks for removing the patch.

My experience with the older kernel-5.10.y also does NOT recognise SD Card and cannot boot from SD Card -- I/O Errors NOT recognising the SD Card.  Not sure about the newer 5.10.y (have not tested it).

The kernel panic issue is with kernel-6.0.y-flippy-xx, it will kernel panic during booting process, never actually boot up with u-boot.ext.

Thanks for your great support.
