### ISSUE TITLE
自定义安装 ssh不启动

### ISSUE THREAD

**Issue by ours1505** [ophub/amlogic-s9xxx-armbian#759]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905l3
 - Model cm311-1

**Armbian Version | 系统版本**
 - Kernel Version: 5.10.156
 - Release: jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
SSH服务没有自动开启。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/685f1a0b3ae0391d915d24ba549943f1f3cf0d60/build-armbian/common-files/rootfs/etc/custom_service/start_service.sh#L26-L27

/etc/custom_service/start_service.sh 

这两行，有人是删除两行的#可以工作正常，有人是加上#注释了正常。

你反向修改。我是删除#正常。

这个问题是因为启动时没有生成sshd目录，但各盒子现象不一样。

**Comment by ours1505** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/685f1a0b3ae0391d915d24ba549943f1f3cf0d60/build-armbian/common-files/rootfs/etc/custom_service/start_service.sh#L26-L27
> 
> /etc/custom_service/start_service.sh
> 
> 这两行，有人是删除两行的#可以工作正常，有人是加上#注释了正常。
> 
> 你反向修改。我是删除#正常。
> 
> 这个问题是因为启动时没有生成sshd目录，但各盒子现象不一样。

感谢大佬。当时我就去看了下历史更改，因为我之前是ok的，然后也看到了这个ssh修改，看到是开启，我就没弄明白

**Comment by ophub** [comment]
![Snip20221203_2](https://user-images.githubusercontent.com/68696949/205445526-8202a108-60c0-4662-8ab8-c9db0b53dcb3.png)


-f那行加了sleep延时执行，改了保存重启
这个脚本的作用是在启动的最后一步，会自动重启下ssh服务，确保ssh服务起来。

```

[[ -f "/etc/init.d/ssh" ]] && sleep 5 && /etc/init.d/ssh restart 2>/dev/null 

```
