### ISSUE TITLE
VFD Support

### ISSUE THREAD

**Issue by Zingisa1** [ophub/amlogic-s9xxx-armbian#76]
Dear to all Developers,

Please add 7 Segment VFDs support even if it's just turning on display with BOOT displayed, this will assist in showing that the device is powered.

Kind regards,

**Comment by ophub** [comment]
Post what you know how to add

**Comment by Zingisa1** [comment]
Which platform is for feature request?

**Comment by ophub** [comment]
In which firmware or source code did you use this function? send a link.

**Comment by ophub** [comment]
Based on the information you provided, I feel it should work in the 5.4 kernel. According to the compilation method in the article, You can pull it into the kernel source code and try to compile it.

https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

https://github.com/unifreq/linux-5.4.y
