### ISSUE TITLE
❤️关于12月3日前的Armbian系统同步至最新版本的操作方法（Version update instructions）

### ISSUE THREAD

**Issue by ophub** [ophub/amlogic-s9xxx-armbian#761]
About the operation method of synchronizing the armbian system to the latest version before December 3

为了兼容rockchip固件，仓库中的目录进行了大幅度调整，相关脚本也进行了更新。请fork仓库的朋友们更新仓库至最新，请使用armbian系统的朋友们更新系统脚本至最新。操作方法适用于armbian和rockchip的全部设备。

In order to be compatible with rockchip firmware, the directory in the warehouse has been greatly adjusted, and the relevant scripts have also been updated. Ask friends of fork warehouse to update the warehouse to the latest, and please use friends of armbian system to update the system script to the latest. The operation method is applicable to all devices of armbian and rockchip.

```
# 1.手动下载最新同步脚本（Manually download the latest sync script）
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync

# 2.同步更新全部脚本（Update all scripts）
armbian-sync

# 3.自动调整版本差异（Automatically adjust for version differences）
armbian-fix
```

这样就完成了版本同步。
This completes version synchronization.

**Comment by killfreetime** [comment]
`cat  /etc/ophub-release
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
PACKAGED_DATE='2022-07-19'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
UBOOT_OVERLOAD='u-boot-n1.bin'
MAINLINE_UBOOT=''
ANDROID_UBOOT='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
MYBOX_UBOOT='/usr/lib/u-boot/mybox-bootloader.img'
SOC='s905d'
KERNEL_VERSION='5.15.80'
K510='0'`
旧版本的ophub-release中不包含PLATFORM信息，导致这个脚本运行出错
[ ERROR ] /etc/ophub-release value is missing!

**Comment by ophub** [comment]
自己添加一条
PLATFORM='amlogic'

**Comment by livelier** [comment]
这是双12礼物🎁，提前到了呀，🎉🎉🎉🎉

**Comment by ophub** [comment]
两个仓库的rebuild脚本高度雷同，每次修改都要一起操作一遍，还不如合并了管理比较节约资源。

**Comment by Yxini** [comment]
刚刚发现是不是撤包了

**Comment by ophub** [comment]
点强制同步，有时撤退一下会出现红色的按钮，点那个红色的。没有红色的就是这个绿色的。

![Snip20221206_6](https://user-images.githubusercontent.com/68696949/205844396-3bd1790a-8eeb-4f7d-ac73-ea1b3220ed94.png)

**Comment by Yxini** [comment]
311-1a 用6.0.1的包启动不了U盘，只能用5.15的包。是311-1a不能用6.0.1的包吗

**Comment by ophub** [comment]
不能用先用别的吧，下周就出6.1了，这个是LTS，f大计划添加TEXT_OFFSET补丁，就不用u-boot也可以使用，和5.15/5.4一样

**Comment by JFLim1** [comment]
> If you can’t use it, use something else first, 6.1 will be released next week, this is LTS, f plans to add TEXT_OFFSET patch, you can use it without u-boot, same as 5.15/5.4

Hi @ophub,

Looking forward to your new 6.1.y TEXT_OFFSET kernel.  Appreciate you can look into the new 6.1.y kernel will have the offending patch "general-meson-gx-mmc-set-core-clock-phase-to-270-degres.patch" is being removed so the it can be used on SD Card.  Thanks.

**Comment by ophub** [comment]
ok

**Comment by SoraKasvgano** [comment]
老哥 可否对脚本增加个国内镜像选项emmm 比如https://kgithub.com/，最近github多地被墙，盒子当服务器用没搞科学 同步大概率会失败

**Comment by HJYAlive** [comment]
> 不能用先用别的吧，下周就出6.1了，这个是LTS，f大计划添加TEXT_OFFSET补丁，就不用u-boot也可以使用，和5.15/5.4一样
armbian-update -k 6.1.1
[ STEPS ] Ready to update, please wait...
[ INFO ] Custom setting parameters: [ -k 6.1.1 ]
[ STEPS ] Start initializing the environment...
[ INFO ] Set the kernel version name: [ 6.1.1 ]
[ INFO ] Set the kernel version branch: [ stable ]
[ INFO ] Use mainline u-boot: [ no ]
[ STEPS ] Use local kernel files: 6.0.15
更新不到6.1.1

**Comment by ophub** [comment]
你进入本地的6.0.15目录了，这会优先使用本地内核。你切换到一个没有内核的目录再执行更新命令。

**Comment by HJYAlive** [comment]
> 优先使用本地内核。你切换到一个没有内核的目录再执行更新命令。

感谢

**Comment by ophub** [comment]
使用下面的3个命令依次执行就同步到了，先下载最新脚本，赋予脚本权限，同步
```
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/refs/heads/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync
chmod +x /usr/sbin/armbian-sync
armbian-sync
```
