### ISSUE TITLE
E900v22c bullseye_6.0.10_server_2022.12.03网卡不工作

### ISSUE THREAD

**Issue by payzulla0706** [ophub/amlogic-s9xxx-armbian#762]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3ab]
 - Model [E900v22c]

**Armbian Version | 系统版本**
Armbian_23.02.0_amlogic_s905l3a_bullseye_6.0.10_server_2022.12.03.img

**Describe the bug | 问题描述**
今天看到新版本 尝试了一下，看到固件里面自带u-boot.ext 启动后网卡短暂几秒连接后断开
然后手动cp -f u-boot-e900v22c.bin u-boot.ext之后也还是不行

**Comment by payzulla0706** [comment]
@ophub 
现在尝试了5.15.80 bullseye 网卡正常 但是启动后一些命令不能执行
如下：
root@armbian:/home/pzl# armbian-software
Command 'armbian-software' is available in the following places
 * /sbin/armbian-software
 * /usr/sbin/armbian-software
The command could not be located because '/sbin:/usr/sbin' is not included in th      e PATH environment variable.
This is most likely caused by the lack of administrative privileges associated w      ith your user account.
armbian-software: command not found

这个要修改或者添加上面么？

**Comment by janko888** [comment]
6.0.x内核的话，你试一下用新版本m401a的.dtb能否正常启动网卡

**Comment by ophub** [comment]
如果6.0不行就继续使用5.15/5.10吧，过几天就切换到6.1了。
