### ISSUE TITLE
访问拒绝

### ISSUE THREAD

**Issue by cui8** [ophub/amlogic-s9xxx-armbian#764]
青龙面板显示启动成功
[![zsGrod.png](https://s1.ax1x.com/2022/12/04/zsGrod.png)](https://imgse.com/i/zsGrod)

为什么浏览器打不开页面，是防火墙问题吗？
[![zsGWy8.png](https://s1.ax1x.com/2022/12/04/zsGWy8.png)](https://imgse.com/i/zsGWy8)

设备：CM311-1A
系统：【Armbian_22.11.0_Aml_s905l3a_jammy_5.15.79_server_2022.11.26.img.gz】
无线usb网卡：rtl8188etv

**Comment by ophub** [comment]
我不了解这个，docker在流览器的访问地址是，ip:端口
