### ISSUE TITLE
编译网卡驱动

### ISSUE THREAD

**Issue by cui8** [ophub/amlogic-s9xxx-armbian#766]
大佬，我发现青龙面板打不开是因为无线网卡，每次在浏览器敲面板地址，自动断网了。我百度说编译要头文件，这个怎么下载。百度一堆没有的，不知道怎么搜索，求大佬解答
[![zs0ITf.png](https://s1.ax1x.com/2022/12/04/zs0ITf.png)](https://imgse.com/i/zs0ITf)

**Comment by cui8** [comment]
求大佬说下cm311-1a怎么可以使armbian连接无线网，需要买什么usb网卡（为了这个，已经买了3个网卡了）。

**无法有线原因？**
路由器与以太网交换机在墙里的箱子里面，里面全是线，装不下，而且插头只有两个，一个接交换机，还有一个接我的路由器。插头问题，房东无法解决，也不允许更换。我的cm311-1a如果接路由器，就没有电，只能无线。

**焦虑**
cm311-1a买了快一个月了，因为网络问题无法解决，一直搁置。今天无线网卡刚到，买的专门是cm311-1a这个一插就可以联网的。使用有问题，求大佬解答。

**Comment by cui8** [comment]
求大佬说下cm311-1a怎么可以使armbian连接无线网，需要买什么usb网卡（为了这个，已经买了3个网卡了）。

**无法有线原因？**
路由器与以太网交换机在墙里的箱子里面，里面全是线，装不下，而且插头只有两个，一个接交换机，还有一个接我的路由器。插头问题，房东无法解决，也不允许更换。我的cm311-1a如果接路由器，就没有电，只能无线。

**焦虑**
cm311-1a买了快一个月了，因为网络问题无法解决，一直搁置。今天无线网卡刚到，买的专门是cm311-1a这个一插就可以联网的。使用有问题，求大佬解答。

**Comment by ophub** [comment]
内核使用交叉工具链编译：clang+llvm-13.0.0+

**Comment by ophub** [comment]
mtk或ralink的，mt7601u既便宜也稳定，不过只是单频2.4g的，如果要双频的话可以选mt7610u
