### ISSUE TITLE
请问最近的armbian镜像包越来越大了，是有什么更新吗

### ISSUE THREAD

**Issue by imzlh** [ophub/amlogic-s9xxx-armbian#767]
感谢o大的armbian，一直打不开GitHub导致很久没来看更新。这次的armbian直接飙升到700mb，属实把我吓了一跳，这让只有6GB emmc空间雪上加霜。我很想问问最近是armbian增加了什么内容吗?

**Comment by ophub** [comment]
我没添加什么，还是那几个sh脚本文件。应该是上游的armbian默认添加了更多软件包。

**Comment by imzlh** [comment]
请问是否可以编译最小化版本，我看之前的armbian min版本压缩包甚至只有200MB左右

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/.github/workflows/build-armbian.yml#L126-L127

自己改参数，设置mini，具体看官方文档自己定制个性化版本：

https://docs.armbian.com/Developer-Guide_Build-Options/
