### ISSUE TITLE
M401A 网卡用不了

### ISSUE THREAD

**Issue by georgekcchung** [ophub/amlogic-s9xxx-armbian#769]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model : M401A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.80
 - Release: jammy
 - Image: Armbian_23.02.0_Aml_s905l3a_jammy_5.15.80_server_2022.12.01.img
 - Boot mode: USB drive

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

dtb file:
[meson-g12a-s905l3a-m401a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10148674/meson-g12a-s905l3a-m401a.dtb.zip)

kernel boot error:
![nic-error](https://user-images.githubusercontent.com/55321169/205494633-c593e322-fef1-480a-93cd-6635519ac1f1.jpg)

我用上面的dtb档进系统，发现网卡不能用，错误信息在上图。
我试了很多dtb档都不行，问题都是一样的。

我在M401A的Android下载了dtb档，看对解决问题有没有帮助。在Android下，网卡是好的。

Android version: 9
Kernel : 4.19
Android dtb file:
[m401a.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10148686/m401a.dtb.zip)

Android dtb nic defenition:

        ethernet@ff3f0000 {
                compatible = "amlogic, g12a-eth-dwmac\0snps,dwmac";
                reg = <0xff3f0000 0x10000 0xff634540 0x08 0xff64c000 0xa0 0xffd01008 0x04>;
                reg-names = "eth_base\0eth_cfg\0eth_pll\0eth_reset";
                interrupts = <0x00 0x08 0x01>;
                interrupt-names = "macirq";
                status = "okay";
                clocks = <0x02 0x38>;
                clock-names = "ethclk81";
                pll_val = <0x9c0040a 0x927e0000 0xac5f49e5>;
                analog_val = <0x20200000 0xc000 0x23>;
                pinctrl-names = "internal_eth_pins";
                pinctrl-0 = <0x11>;
                mc_val = <0x4be04>;
                internal_phy = <0x01>;
                phandle = <0xa1>;
        };

Armbian dtb nic definition:

                ethernet@ff3f0000 {
                        compatible = "amlogic,meson-g12a-dwmac\0snps,dwmac-3.70a\0snps,dwmac";
                        reg = <0x00 0xff3f0000 0x00 0x10000 0x00 0xff634540 0x00 0x08>;
                        interrupts = <0x00 0x08 0x04>;
                        interrupt-names = "macirq";
                        clocks = <0x02 0x26 0x02 0x02 0x02 0x0d 0x02 0x02>;
                        clock-names = "stmmaceth\0clkin0\0clkin1\0timing-adjustment";
                        rx-fifo-depth = <0x1000>;
                        tx-fifo-depth = <0x800>;
                        status = "okay";
                        power-domains = <0x03 0x01>;
                        phy-handle = <0x11>;
                        phy-mode = "rmii";
                        phandle = <0x5b>;

                        mdio {
                                #address-cells = <0x01>;
                                #size-cells = <0x00>;
                                compatible = "snps,dwmac-mdio";
                                phandle = <0x1b>;
                        };
                };

请各位大神帮忙看一下。

**Comment by ophub** [comment]
```
cd /boot
# for usb
cp -f u-boot-e900v22c.bin u-boot.ext
# for emmc
cp -f u-boot-e900v22c.bin u-boot.emmc
```

**Comment by georgekcchung** [comment]
cd /boot
# for usb
cp -f u-boot-e900v22c.bin u-boot.ext

这个试过了，没有kernel boot 的画面。

我已经把这里所有的问题都看了一便，尝试了许多都没有成功。最后希望是改dtb。

**Comment by ophub** [comment]
试试5.10的固件

**Comment by georgekcchung** [comment]
现在已经下载不了5.10的固件了。以前试过也不行。
刚刚试了一下Armbian_23.02.0_amlogic_s905l3a_jammy_6.0.11_server_2022.12.04.img， 还是没有kernel boot 的画面，拿走u-boot.ext也一样。

下面是我的M401A

![m401a](https://user-images.githubusercontent.com/55321169/205499563-b0ea4e08-a3cb-46ca-9b83-b36a4f73e45b.jpg)

**Comment by wxc807** [comment]
> 现在已经下载不了5.10的固件了。以前试过也不行。 刚刚试了一下Armbian_23.02.0_amlogic_s905l3a_jammy_6.0.11_server_2022.12.04.img， 还是没有kernel boot 的画面，拿走u-boot.ext也一样。
> 
> 下面是我的M401A
> 
> ![m401a](https://user-images.githubusercontent.com/55321169/205499563-b0ea4e08-a3cb-46ca-9b83-b36a4f73e45b.jpg)

我跟跟你的情况一样，也是M401A。
出现这个异常的时候，关机插上之前烧录的U盘不要拔掉，网卡就可以正常启动。

**Comment by georgekcchung** [comment]
@wxc807 , "关机插上之前烧录的U盘不要拔掉", 请问这是怎么操作的？
关机是拔电源吗？还是"shutdown -h now"?

**Comment by wxc807** [comment]
> @wxc807 , "关机插上之前烧录的U盘不要拔掉", 请问这是怎么操作的？ 关机是拔电源吗？还是"shutdown -h now"?

你插上U盘（之前烧录的），重启机顶盒网卡就是可以用。拔掉U盘再重启，网卡就失效了。我刚接触armbian两天，不专业。这个问题困扰了我两个晚上。

**Comment by wxc807** [comment]
> @wxc807 , "关机插上之前烧录的U盘不要拔掉", 请问这是怎么操作的？ 关机是拔电源吗？还是"shutdown -h now"?

我linux还没入门，我感觉是从U盘加载的DTB，你试一下就知道了。如果有解决思路了，分享一下，困扰我了我两个晚上，机顶盒气的被我送人了。

**Comment by georgekcchung** [comment]
@wxc807 , 请问你是用哪个dtb的？

**Comment by wxc807** [comment]
> @wxc807 , 请问你是用哪个dtb的？
INITRD =/ ulnitrd 
 FDT =/ dtb / amlogic / meson -g12a-s90513a-m401al.dtb

**Comment by georgekcchung** [comment]
"你插上U盘（之前烧录的），重启机顶盒网卡就是可以用"
这个我试了很多遍了，还是不行。
请问重启是拔电源再插电源吗？

**Comment by wxc807** [comment]
> "你插上U盘（之前烧录的），重启机顶盒网卡就是可以用" 这个我试了很多遍了，还是不行。 请问重启是拔电源再插电源吗？

我是用M401A的开关按钮重启
第一次不懂刷的304没有改UENV.TXT
第二次uenv.txt改好后，刷的306。

**Comment by georgekcchung** [comment]
开关按钮重启, 我也试过了，还是不行

**Comment by wxc807** [comment]
> 开关按钮重启, 我也试过了，还是不行

nano /etc/network/interface
改成固定IP，重启再试试，我就做了这么多操作
或者你有TTL的话看下开机流程，你刷机的时候改了uenv了吗？

**Comment by georgekcchung** [comment]
> > 开关按钮重启, 我也试过了，还是不行
> 
> nano /etc/network/interface 改成固定IP，重启再试试，我就做了这么多操作 

改这个没用，eth0是down的状态

> 或者你有TTL的话看下开机流程，你刷机的时候改了uenv了吗？

没有TTL，不是我刷的机

**Comment by georgekcchung** [comment]
> 看了一下，你这附件里meson-g12a-s905l3a-m401a.dtb.zip里的dtb来源不是o大这边发布的img里的？

这个是o大在其他贴子发的，img裏面的dtb也用过，基本都是一样的问题。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

12.13节
你自己反编译修改下测试

**Comment by georgekcchung** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md
> 
> 12.13节 你自己反编译修改下测试

以下就是我反编译的结果，修改了很多次了，都不行。
我估计是reg和interrupts不对。


Android dtb nic defenition:

        ethernet@ff3f0000 {
                compatible = "amlogic, g12a-eth-dwmac\0snps,dwmac";
                reg = <0xff3f0000 0x10000 0xff634540 0x08 0xff64c000 0xa0 0xffd01008 0x04>;
                reg-names = "eth_base\0eth_cfg\0eth_pll\0eth_reset";
                interrupts = <0x00 0x08 0x01>;
                interrupt-names = "macirq";
                status = "okay";
                clocks = <0x02 0x38>;
                clock-names = "ethclk81";
                pll_val = <0x9c0040a 0x927e0000 0xac5f49e5>;
                analog_val = <0x20200000 0xc000 0x23>;
                pinctrl-names = "internal_eth_pins";
                pinctrl-0 = <0x11>;
                mc_val = <0x4be04>;
                internal_phy = <0x01>;
                phandle = <0xa1>;
        };

Armbian dtb nic definition:

                ethernet@ff3f0000 {
                        compatible = "amlogic,meson-g12a-dwmac\0snps,dwmac-3.70a\0snps,dwmac";
                        reg = <0x00 0xff3f0000 0x00 0x10000 0x00 0xff634540 0x00 0x08>;
                        interrupts = <0x00 0x08 0x04>;
                        interrupt-names = "macirq";
                        clocks = <0x02 0x26 0x02 0x02 0x02 0x0d 0x02 0x02>;
                        clock-names = "stmmaceth\0clkin0\0clkin1\0timing-adjustment";
                        rx-fifo-depth = <0x1000>;
                        tx-fifo-depth = <0x800>;
                        status = "okay";
                        power-domains = <0x03 0x01>;
                        phy-handle = <0x11>;
                        phy-mode = "rmii";
                        phandle = <0x5b>;

                        mdio {
                                #address-cells = <0x01>;
                                #size-cells = <0x00>;
                                compatible = "snps,dwmac-mdio";
                                phandle = <0x1b>;
                        };
                };
