### ISSUE TITLE
Add dtb file for Tx3 Mini Plus

### ISSUE THREAD

**Issue by manhdv** [ophub/amlogic-s9xxx-armbian#77]
Could you add new dtb file for [TX3 Mini Plus](http://www.oranth.com/product-3661-55496.html) (4G RAM).

**Comment by ophub** [comment]
try s905w

**Comment by manhdv** [comment]
In file meson-gxl-s905w-tx3-mini.dtb, it support 1G ram only.
`	memory@0 {
		device_type = "memory";
		reg = <0x0 0x0 0x0 0x40000000>;
	};`

**Comment by ophub** [comment]
try edit uEnv.txt: meson-gxl-s905w-p281.dtb

**Comment by manhdv** [comment]
There is no different in memory node.
Can I make new dtb for this box and create a pull request?

**Comment by ophub** [comment]
Welcome 👏
Previous s905w boxes could only use 5.4 kernels. Try yours to see if it supports it.
u-boot-s905x-s912.bin
