### ISSUE TITLE
CM311-1a无线、网络等问题 

### ISSUE THREAD

**Issue by sparkleef** [ophub/amlogic-s9xxx-armbian#772]
**Device Information | 设备信息**
 - SOC: [S905l3a]
 - Model [cm311-1a]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.80]
 - Release: [bullseye]

详细描述问题。

1.想安装usb WiFi 用了这个驱动[BrightX/rtl8192fu](https://github.com/BrightX/rtl8192fu) 在安装驱动的时候 用make -j$(nproc) 命令后，提示*** No rule to make target 'modules'.  Stop.

2.同一盒子昨天用了6.0.10，发现无法驱动有线网络，开机就报错，刷回5.15.80正常，ps 用armbian-update -k 6.0.10 这种方式是否有问题。当然重刷6.0.10也报错，就是想看看以后升级跨版本是不是就是用这种方式就行了。

3.历史版本去哪里能够下载

4.bullseye 和 jammy 对于支持rtl8192fu 会有区别么。还是说不可能支持。

以上，谢谢O大

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtlwifi

内核源码里驱动的都可以支持。
没有驱动的无法支持，需要找对应内核可以使用的驱动。

**Comment by sparkleef** [comment]
感谢O大，WiFi问题我自己再研究一下。这两个问题能给说明一下么，再次感谢。

同一盒子昨天用了6.0.10，发现无法驱动有线网络，开机就报错，刷回5.15.80正常，ps 用armbian-update -k 6.0.10 这种方式是否有问题。当然重刷6.0.10也报错，就是想看看以后升级跨版本是不是就是用这种方式就行了。

.历史版本去哪里能够下载

**Comment by ophub** [comment]
更新方法正确，如果6.0不支持就换5.15/5.10/5.4

各版本只在release存在几天，超不过一周就删了。有新的就删旧的。一个release约20G容量，留着太浪费github资源了。

**Comment by sparkleef** [comment]
感谢，O大，不过5.10 和 5.4 看来是找不到了。如果USB WiFi成功了我再来汇报。谢谢。

**Comment by sparkleef** [comment]
WiFi驱动一开始的症结我找到了，但是执行后又有新的报错，大大看看能否给个提示。是因为编译器版本问题么。

root@armbian:~/rtl8192fu# make -j$(nproc)
make ARCH=aarch64 CROSS_COMPILE= -C /lib/modules/5.15.80-flippy-79+o/build M=/root/rtl8192fu  modules
make[1]: Entering directory '/usr/src/linux-headers-5.15.80-flippy-79+o'
warning: the compiler differs from the one used to build the kernel
  The kernel was built by: Ubuntu clang version 14.0.0-1ubuntu1
  You are using:           gcc (Debian 10.2.1-6) 10.2.1 20210110
  CC [M]  /root/rtl8192fu/core/rtw_cmd.o
  CC [M]  /root/rtl8192fu/core/rtw_security.o
  CC [M]  /root/rtl8192fu/core/rtw_debug.o
  CC [M]  /root/rtl8192fu/core/rtw_io.o
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-Qunused-arguments’
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /root/rtl8192fu/core/rtw_cmd.o] Error 1
make[2]: *** Waiting for unfinished jobs....
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /root/rtl8192fu/core/rtw_security.o] Error 1
gcc: error: unrecognized command-line option ‘-mno-global-merge’
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /root/rtl8192fu/core/rtw_debug.o] Error 1
gcc: error: unrecognized command-line option ‘-fsplit-lto-unit’
make[2]: *** [scripts/Makefile.build:289: /root/rtl8192fu/core/rtw_io.o] Error 1
make[1]: *** [Makefile:1902: /root/rtl8192fu] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.80-flippy-79+o'
make: *** [Makefile:2332: modules] Error 2

**Comment by ophub** [comment]
make参数不对，可以参考

https://github.com/ophub/amlogic-s9xxx-armbian/blob/19c93c5edda8eaea177d684165781e67f5fe50aa/compile-kernel/tools/script/armbian_compile_kernel_script.sh#L366

**Comment by janko888** [comment]
6.0.x内核网卡识别的话，dtb加上下面的试一下。

&ethmac {
	/delete-property/ resets;
	/delete-property/ reset-names;
}；

**Comment by sparkleef** [comment]
> 6.0.x内核网卡识别的话，dtb加上下面的试一下。
> 
> &ethmac { /delete-property/ resets; /delete-property/ reset-names; }；

是指在这个文件uEnv.ini 修改的时候么，是怎么加入呢，另起一行么，谢谢

**Comment by ophub** [comment]
dts里面改

**Comment by cui8** [comment]
> https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtlwifi
> 
> 内核源码里驱动的都可以支持。 没有驱动的无法支持，需要找对应内核可以使用的驱动。

打扰您了，最近我也是CM311-1a无线网络问题。想问下【安装内核头文件】怎么安装？
[![zcMP7d.png](https://s1.ax1x.com/2022/12/06/zcMP7d.png)](https://imgse.com/i/zcMP7d)
我这里有下载的armbian文件，不知道可以帮到您嘛。地址：https://41ws38-my.sharepoint.com/:f:/g/personal/ddf_41ws38_onmicrosoft_com/EsME-_ykxBhGokK5wvni2EkB8KB85cG646Bkpv6K-aXcmQ?e=DQUTra

**Comment by cui8** [comment]
> 感谢O大，WiFi问题我自己再研究一下。这两个问题能给说明一下么，再次感谢。
> 
> 同一盒子昨天用了6.0.10，发现无法驱动有线网络，开机就报错，刷回5.15.80正常，ps 用armbian-update -k 6.0.10 这种方式是否有问题。当然重刷6.0.10也报错，就是想看看以后升级跨版本是不是就是用这种方式就行了。
> 
> .历史版本去哪里能够下载

您可以教我一下怎么安装驱动吗？不会问很多问题的

**Comment by ophub** [comment]
头文件已经随内核自动安装到了/usr/src/目录里了
