### ISSUE TITLE
R68S问题咨询

### ISSUE THREAD

**Issue by huaruitech** [ophub/amlogic-s9xxx-armbian#774]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: RK3568
 - Model R68s

**Armbian Version | 系统版本**
 - Kernel Version: Armbian_23.02.0
 - Release: Armbian_23.02.0_rockchip_r68s_bullseye_6.0.11_server_2022.12.04.img

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
R68s can complete img flashing normally, but cannot enter the system normally, the network card light keeps flashing, and the IP address cannot be obtained, what should I do? Are you also in the same situation as above?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/873bb3425584cc90dfe501e9fbca2b886762539e

https://github.com/ophub/amlogic-s9xxx-armbian/commit/5d3406867e3841c93127372576163b98739612c3


同步最新脚本打包，之前的bootloader路径错误，上午修复了，经用户测试反馈已经可以正常使用了。
刷机方法也更新了。


![image](https://user-images.githubusercontent.com/68696949/205841645-897660ae-b626-4521-a442-679d0738fdaf.png)

**Comment by huaruitech** [comment]
神速啊！请明示下修复bootloader路径最新脚本打包是哪个地址的img文件？
新刷机方法也请指教下，感谢您的善意帮助！

**Comment by ophub** [comment]
[就是上面我刚才这个回复里的2个链接，一个是路径，一个是方法。

**Comment by huaruitech** [comment]
好的，我试下，感谢大神帮助！握手

**Comment by stevenliuit** [comment]
电犀牛R68s刷完后机器能获取到ip，但是无法ssh链接，主要是这个设备没有hdmi接口看不到屏幕，求解

**Comment by by-JohnChen** [comment]
> 电犀牛R68s刷完后机器能获取到ip，但是无法ssh链接，主要是这个设备没有hdmi接口看不到屏幕，求解

拆机TTL

**Comment by USR33K** [comment]
338的版本R68S出现状态灯不显示，绿灯正常、蓝灯不亮，不知是机制还是BUG
