### ISSUE TITLE
能否把这些盒子的镜像合成一个

### ISSUE THREAD

**Issue by luoluo888** [ophub/amlogic-s9xxx-armbian#78]
大神，能不能把这些盒子合成一个镜像。每个芯片一个镜像有点麻烦，不怎么方便。

**Comment by ophub** [comment]
#你如果熟悉怎么改dtb和u-boot的话，你可以闭上眼睛任意点一个随机的固件下载，自己随手改一下即可使用。改/boot下的两处和几个脚本。区别是为了方便不熟的人，给每个人解释怎么改是一件很累的事。

**Comment by xcray** [comment]
> 你如果熟悉怎么改的话，你可以闭上眼睛任意点一个随机的固件下载，自己随手改一下即可使用。改boot下的dtb和uboot和rootfs下的安装、更新、docker等几个脚本和不同分支release的内核、软件源及内容差异等。区别是为了方便不熟的人，给每个人解释怎么改是一件很累的事。

老大的好心，但是在实际操作中经常不管用。大部分盒子好像都需要反复修改尝试dtb和uboot等？即使是同一型号，硬件都几乎不统一。

**Comment by ophub** [comment]
是的，同名同品牌的盒子，芯片好几种，变种太多了
