### ISSUE TITLE
R68S,KVM无法安装

### ISSUE THREAD

**Issue by Dingdingf** [ophub/amlogic-s9xxx-armbian#780]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. RK3568]
 - Model [e.g. R68S]

**Armbian Version | 系统版本**
 - Kernel Version: [Linux armbian 6.0.11-flippy-79+]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
armbian-software KVM无法安装，部分软件版本过高、依赖冲突。导致的无法安装。

![image](https://user-images.githubusercontent.com/32409706/206153238-fbf173e4-6a69-4f98-ab80-b6253ae0a1d5.png)

**Comment by Dingdingf** [comment]
应该不是网络问题吧，软件源换成国内的了。我看提示 系统自带的python3.9 但是依赖是小于3.8 ;你那边的这个python3版本是多少？

**Comment by ophub** [comment]
![Snip20221207_6](https://user-images.githubusercontent.com/68696949/206187962-40515113-d574-464e-b95b-255cf9306b6b.png)

**Comment by Dingdingf** [comment]
我再试试

**Comment by ophub** [comment]
我反复安装/卸载/安装/卸载了很多遍，还顺便发现了一个用户问题，输入不存在的用户会无法添加到KVM组，刚才还修复了下脚本，检查输入用户不存在会先创建再添加。

**Comment by Dingdingf** [comment]
脚本链接404了，改位置了？

**Comment by ophub** [comment]
你截图发一下什么位置提示？

https://github.com/ophub/amlogic-s9xxx-armbian/issues/761

12月3日前的armbian按这个更新一下。

**Comment by Dingdingf** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software
![image](https://user-images.githubusercontent.com/32409706/206204400-76612c7a-1150-4fb5-aae6-1d7ed12e5a21.png)

**Comment by ophub** [comment]
你网络访问github不通

**Comment by Dingdingf** [comment]
好的，我发现是有一个网桥存在，我中间换过上级路由。第一次使用的是192.168.8.x网段 ,现在我使用的是192.168.2.x网段。我并没有主动构造这个网桥，就很奇怪。我192.168.2.x 上挂的有代理，恢复后我再实验一下。
![image](https://user-images.githubusercontent.com/32409706/206209370-dc1112a2-cc82-4a49-ab35-a271466f24b8.png)

**Comment by Dingdingf** [comment]
问题已解决：
![image](https://user-images.githubusercontent.com/32409706/206220854-26c3364e-5a6f-48d9-9dd4-c8a43bf92d56.png)


之前失败原因：系统换国内源无法安装，依赖未下载成功；
换回官方源 + 代理 成功安装。
谢谢耐心回复

上条回复的网桥问题不知是否为正常情况？

**Comment by ophub** [comment]
创建br0就是安装kvm的一步

https://github.com/ophub/amlogic-s9xxx-armbian/blob/0a46cb62c06b96b99d96ce6205857334826648c5/build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software/command-service.sh#L280-L300

kvm的更多使用方法看f大写的这个说明，上面在软件中心一键安装和设置环境，就是和这个教程一致的操作，只是自动完成了。下面的工作就是自己添加op等系统了，多看几遍就会了。

https://github.com/unifreq/openwrt_packit/blob/master/files/qemu-aarch64/qemu-aarch64-readme.md

**Comment by Dingdingf** [comment]
感谢解惑
