### ISSUE TITLE
挂载移动硬盘后无法启动，求解决方法

### ISSUE THREAD

**Issue by payzulla0706** [ophub/amlogic-s9xxx-armbian#783]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3ab]
 - Model [e9000v22c]

**Armbian Version | 系统版本**
Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.80_server_2022.12.03.img

**Describe the bug | 问题描述**
挂载移动硬盘可以正常读取
之后 vim /etc/fstab
最下面写入
UUID=B37D-DB06 /mnt/disk ext4 defaults 0 2
保存重启后报错不能正常启动

![xxx](https://user-images.githubusercontent.com/118226806/206221895-575070d6-2045-4d3c-b1ef-7da101aa1b4a.jpg)

求解决办法
@ophub

**Comment by urenai** [comment]
我第一时间考虑，可能是你电源小了。

**Comment by payzulla0706** [comment]
> 我第一时间考虑，可能是你电源小了。

12V 1A的
是不是应该找个12V  1.5A的？

**Comment by urenai** [comment]
2an，因为移动硬盘耗电也不小。

**Comment by jjwjs** [comment]
我也遇到同样的问题，更换过2a电源，故障依旧，还有的运行一会，sda变成sdb，挂载就消失了，有一个盒子，开机的时候拔掉硬盘，通电3秒后插上硬盘，就可以正常启动获取到IP

**Comment by payzulla0706** [comment]
> 我也遇到同样的问题，更换过2a电源，故障依旧，还有的运行一会，sda变成sdb，挂载就消失了，有一个盒子，开机的时候拔掉硬盘，通电3秒后插上硬盘，就可以正常启动获取到IP

我也试过了 换了电源2安的 移动硬盘外接电源也试了 双USB线也试了 跟你 的情况一样 就是容易掉 一会正常 一会不正常 估计这个盒子不支持机械银盘吧

**Comment by yangzhuang2333** [comment]
> > 我也遇到同样的问题，更换过2a电源，故障依旧，还有的运行一会，sda变成sdb，挂载就消失了，有一个盒子，开机的时候拔掉硬盘，通电3秒后插上硬盘，就可以正常启动获取到IP
> 
> 我也试过了 换了电源2安的 移动硬盘外接电源也试了 双USB线也试了 跟你 的情况一样 就是容易掉 一会正常 一会不正常 估计这个盒子不支持机械银盘吧

是这个盒子的USB供电带不动硬盘，连好点的优盘都带不动，整个带外置供电的hub试试吧，或者把你硬盘线改外置供电 就是断开硬盘通往盒子的的正极 然后正负极另外接一个USB头插个手机充电器试试。我就是这么干的，带3.5硬盘很稳定

**Comment by payzulla0706** [comment]
> > > 我也遇到同样的问题，更换过2a电源，故障依旧，还有的运行一会，sda变成sdb，挂载就消失了，有一个盒子，开机的时候拔掉硬盘，通电3秒后插上硬盘，就可以正常启动获取到IP
> > 
> > 
> > 我也试过了 换了电源2安的 移动硬盘外接电源也试了 双USB线也试了 跟你 的情况一样 就是容易掉 一会正常 一会不正常 估计这个盒子不支持机械银盘吧
> 
> 是这个盒子的USB供电带不动硬盘，连好点的优盘都带不动，整个带外置供电的hub试试吧，或者把你硬盘线改外置供电 就是断开硬盘通往盒子的正极 然后正负极另外接一个USB头插个手机充电器试试。我就是这么干的，带3.5硬盘很稳定

我现在测试的是在原有的数据线上并连了另外的正负极出来 接到手机充电器5V 2A的 然而还是不稳定，难道必须要断开到盒子的那个正极吗？

**Comment by yangzhuang2333** [comment]
必须断开  不然可能反向电流会烧掉盒子的，我的是非常稳定的  开机自动挂载也行，我是没有绑定uuid的 只是普通挂载你可以试试

**Comment by payzulla0706** [comment]
> 必须断开 不然可能反向电流会烧掉盒子的，我的是非常稳定的 开机自动挂载也行，我是没有绑定uuid的 只是普通挂载你可以试试

不绑定uuid也可以开机自动挂载吗？

**Comment by yangzhuang2333** [comment]
我的也不行了  之前5.10内核还好，现在用最新版系统老是掉盘，开机一会就掉，还没找到好办法，明天我接个hub试试

**Comment by ophub** [comment]
armbian-update更新到5.10.y多省事，一分钟回到密月

**Comment by yangzhuang2333** [comment]
> armbian-update更新到5.10.y多省事，一分钟回到密月。有时自己觉得好的版本留几个保存，一套内核几十兆也不占地方。内核周周更新，有时的bug一个问题几周都存在。

就是不知道跟不跟内核有关系，最新版本获取ip很顺畅，就是挂载硬盘要么掉盘要么直接死机。我都蒙了

**Comment by ophub** [comment]
供电不足，使用有独立供电的

**Comment by yangzhuang2333** [comment]
> 供电不足，使用有独立供电的

就是独立供电，12v跟5v都独立供电了，它就是掉盘  ，给我整懵逼了，我加个hub试试

**Comment by shenmo7192** [comment]
> 必须断开 不然可能反向电流会烧掉盒子的，我的是非常稳定的 开机自动挂载也行，我是没有绑定uuid的 只是普通挂载你可以试试

非常神奇，我使用了外部供电5V2A，没有断，然后盒子就不需要插电就能运行了，而且不再掉盘了
