### ISSUE TITLE
X96 Max Plus 100W

### ISSUE THREAD

**Issue by luucasmooreira** [ophub/amlogic-s9xxx-armbian#784]
Hi @ophub, I'm current having the same experience with @jbyu for my X96 Max Plus 100W.

**Device specifications:**
- Name: X96 Max Plus 100W
- CPU: Amlogic S905X3 quad-core ARM Cortex A55
- GPU: ARM Mali-G31MP
- Radio module: W522A
- Memory: DDR3 4GB, FLASH 32GB
- Support 10/100M Ethernet, 2.4 and 5G WiFi, BT4.0;
- USB3.0 x 1, USB2.0 x 1, TF Card
- HDMI, AV, SPDIF

**Software informations:**
- Armbian image: `Armbian_22.11.0_Aml_s905x3_jammy_5.15.62_server_2022.09.13.img`
- Used DTB file: `meson-sm1-x96-air.dtb`

**Descriptions**:
- At first, I used the `meson-sm1-x96-air.dtb` file for the OS Installation as the [Instructions](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md) mentioned, but the system shows only **2GB** instead of **4GB**, and also the **Wifi connection** is unavailable. 

- I've tried extracting the DTB file from the TV Box's Original Firmware (Android 9), with 4 raw DTS files shown in the [drive link](https://drive.google.com/drive/folders/19ZoOEo5c5Ca7U48NtAfFLx2ErqLUA2JB?usp=sharing). After a few trials of modifying the `meson-sm1-x96-air.dtb` file (already converted to DTS) based on the extracted DTS file `sm1-ac213-4g.dts` from the drive link above, I've **successfully** got the whole **4GB** displayed on the Armbian OS as shown in the picture below.

- Unfortunately, after lots of trying on modifying **Wifi** and **PCIE** related fields from the DTB file, the **Wifi** driver is still **not available**.

![image](https://user-images.githubusercontent.com/88963333/190618832-98f75b99-f11e-42b2-9a3b-0f6a80c510ec.png)

Could you please show us any way to fix this problem?

Thank you in advance.

_Originally posted by @trvqhuy in https://github.com/ophub/amlogic-s9xxx-armbian/issues/566#issuecomment-1249203960_

**Comment by luucasmooreira** [comment]
How can I put 4 GB of RAM?

**Comment by luucasmooreira** [comment]
meson-sm1-sei610.dtb works, but it only recognizes 1Gb of Ram, and I have 4 Gb =/

**Comment by luucasmooreira** [comment]
EMMC

**Comment by ophub** [comment]
```
# Replace local configuration file
wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/etc/model_database.conf -O /etc/model_database.conf

# Execute Installation Option 522
armbian-install -m yes
```

**Comment by ophub** [comment]
Is the test working?

**Comment by luucasmooreira** [comment]
yes, it recognizes the 4GB of Ram, but it doesn't get IP Lan :/

**Comment by ophub** [comment]
try `meson-sm1-x96-air.dtb` or `meson-sm1-a95xf3-air.dtb`
copy `u-boot-x96maxplus.bin` to `u-boot.ext` and `u-boot.emmc`

**Comment by luucasmooreira** [comment]
I already copied u-boot-x96maxplus.bin to u-boot.ext and u-boot.emmc in the usb pen driver, that way it works IP Lan and 4GB, the problem is in installing armbian in EMMC, it installs the 4GB, but does not recognize IP Lan.

**Comment by ophub** [comment]
[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10200277/meson-sm1-x96-max-plus-q1.dtb.zip)


 `uzip` the dtb file, upload it to the `/boot/dtb/amlogic` directory, modify the `/boot/uEnv.txt` file, and change the file name to this. `Restart` the test.
