### ISSUE TITLE
N1 安装桌面后报错无法进入桌面

### ISSUE THREAD

**Issue by mimokini** [ophub/amlogic-s9xxx-armbian#785]
**Device Information | 设备信息**
 - SOC：S905D
 - Model：N1

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.81
 - Release: bullseye

**Describe the bug | 问题描述**
        系统是新安装的，使用armbian-software安装了桌面，安装过程中只提示了登录用户和语言包的选项，安装过程没有出现错误等情况，安装成功后系统自动重启，最后没有进入桌面，只卡在了“Failed to start Light Display Manager.”，系统和ssh都正常，lightdm也装好了是最新的。
        期间通过armbian-software卸载又重新安装了一遍，问题依旧，期待大神回复。

#以下是状态信息

```
root@armbian:~# systemctl status lightdm.service
● lightdm.service - Light Display Manager
     Loaded: loaded (/lib/systemd/system/lightdm.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-12-08 18:57:56 CST; 9min ago
       Docs: man:lightdm(1)
    Process: 1607 ExecStart=/usr/sbin/lightdm (code=exited, status=1/FAILURE)
   Main PID: 1607 (code=exited, status=1/FAILURE)
        CPU: 195ms

Dec 08 18:57:56 armbian systemd[1]: lightdm.service: Scheduled restart job, restart counter is at 5.
Dec 08 18:57:56 armbian systemd[1]: Stopped Light Display Manager.
Dec 08 18:57:56 armbian systemd[1]: lightdm.service: Start request repeated too quickly.
Dec 08 18:57:56 armbian systemd[1]: lightdm.service: Failed with result 'exit-code'.
Dec 08 18:57:56 armbian systemd[1]: Failed to start Light Display Manager.
Dec 08 18:57:56 armbian systemd[1]: lightdm.service: Triggering OnFailure= dependencies.
```

**Comment by ophub** [comment]
安装过程中有个选项，jammy选gdm3，bullseye选lightdm

**Comment by ophub** [comment]
![Snip20221208_1](https://user-images.githubusercontent.com/68696949/206444121-938527be-1052-4dc4-a935-0f146a49a06a.png)

**Comment by mimokini** [comment]
还是无法启动桌面，问题依旧，刷了两个N1都是相同的错误，难道我刷机的姿势不对？- -？
今天下载了最新版bullseye固件，同样的错误：Failed to start Light Display Manager.

#以下是lightdm.log日志：

[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.26.0, UID=0 PID=1561
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/01_debian.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
[+0.02s] DEBUG: Monitoring logind for seats
[+0.02s] DEBUG: New seat added from logind: seat0
[+0.02s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.02s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.02s] DEBUG: Seat seat0: Starting
[+0.02s] DEBUG: Seat seat0: Creating greeter session
[+0.02s] DEBUG: Seat seat0: Creating display server of type x
[+0.02s] DEBUG: Using VT 7
[+0.02s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.02s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.02s] DEBUG: XServer 0: Writing X server authority to /var/run/lightdm/root/:0
[+0.02s] DEBUG: XServer 0: Launching X Server
[+0.02s] DEBUG: Launching process 1567: /usr/bin/X :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.02s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.02s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.02s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.03s] WARNING: Error getting user list from org.freedesktop.Accounts: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Accounts was not provided by any .service files
[+0.03s] DEBUG: Loading user config from /etc/lightdm/users.conf
[+0.03s] DEBUG: User mimokini added
[+0.16s] DEBUG: Process 1567 exited with return value 1
[+0.16s] DEBUG: XServer 0: X server stopped
[+0.16s] DEBUG: Releasing VT 7
[+0.16s] DEBUG: XServer 0: Removing X server authority /var/run/lightdm/root/:0
[+0.16s] DEBUG: Seat seat0: Display server stopped
[+0.16s] DEBUG: Seat seat0: Stopping session
[+0.16s] DEBUG: Seat seat0: Session stopped
[+0.16s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+0.16s] DEBUG: Seat seat0: Stopping; greeter display server failed to start
[+0.16s] DEBUG: Seat seat0: Stopping
[+0.16s] DEBUG: Seat seat0: Stopped
[+0.16s] DEBUG: Required seat has stopped
[+0.16s] DEBUG: Stopping display manager
[+0.16s] DEBUG: Display manager stopped
[+0.16s] DEBUG: Stopping daemon
[+0.17s] DEBUG: Exiting with return value 1

#以下是x-0.log日志：

X.Org X Server 1.20.11
X Protocol Version 11, Revision 0
Build Operating System: linux Debian
Current Operating System: Linux armbian 6.0.12-flippy-79+ #41 SMP Thu Dec 8 23:41:34 CST 2022 aarch64
Kernel command line: root=UUID=284a3906-b448-4c7f-8fd0-9539e86e20da rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 mac=1e:0d:56:ef:1b:17
Build Date: 11 November 2022  12:37:52PM
xorg-server 2:1.20.11-1+deb11u3 (https://www.debian.org/support) 
Current version of pixman: 0.40.0
	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(==) Log file: "/var/log/Xorg.0.log", Time: Sat Dec 10 02:13:29 2022
(==) Using config file: "/etc/X11/xorg.conf"
(==) Using config directory: "/etc/X11/xorg.conf.d"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
(EE) 
Fatal server error:
(EE) Cannot run in framebuffer mode. Please specify busIDs        for all framebuffer devices
(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
