### ISSUE TITLE
X96 Max PlusQ1 2GB instead of 4GB

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#788]
Hello @ophub 

my box is an X96 Max PlusQ1

![158602905-419853b1-a240-4de9-b556-47d5be7bdc5c](https://user-images.githubusercontent.com/83761813/206517515-692d1119-cc8d-480b-b0de-062ef4850c86.jpg)

![158602901-19ddc7d1-05ea-4fa6-9c72-08db99e0d844](https://user-images.githubusercontent.com/83761813/206517475-fe1da696-84da-4aa9-8a18-c7cfa24458f3.jpg)

Used DTB file: **meson-sm1-x96-air.dtb**

**Software informations:**

Armbian image: Armbian_23.02.0_amlogic_s905x3_bullseye_5.15.81_server_2022.12.08.img
Used DTB file: meson-sm1-x96-air.dtb

**Problem**:

At first, I used the meson-sm1-x96-air.dtb file for the OS Installation as the [Instructions](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-docs/amlogic_model_database.md) mentioned, but the system shows only 2GB instead of 4GB

I leave here some files extracted from the original android firmware that I think can help

[mybox.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10187731/mybox.zip)

Firmware Original:
https://cloud.mail.ru/public/2MG6/C7Pvdaw49

**Comment by ophub** [comment]
```
cd /boot
cp -f u-boot-x96maxplus.bin u-boot.emmc
cp -f u-boot-x96maxplus.bin u-boot.ext
```

**Comment by ophub** [comment]
What is soc and 100M wired network card?

**Comment by ophub** [comment]
Wait a minute. I'll compile one for you

**Comment by ophub** [comment]
[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10199939/meson-sm1-x96-max-plus-q1.dtb.zip)

Use the firmware of 5.15 kernel to extract the dtb file, upload it to the/boot/dtb/amlogic directory, modify the uEnv.txt file, and change the file name to this. Restart the test.
No need to add u-boot

**Comment by ophub** [comment]
```
ls /boot/dtb/amlogic/meson-sm1-x96-max-plus-q1.dtb
ls /boot/u-boot.ext
ls /boot/u-boot.emmc
```

**Comment by ophub** [comment]
You use meson-sm1-x96-air.dtb wired network is normal, but the memory is 2G?

**Comment by ophub** [comment]
[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10200046/meson-sm1-x96-max-plus-q1.dtb.zip)

Modified it, re-covered it, restarted

**Comment by ophub** [comment]
The dtb you provided in the first post cannot be decompiled. The file is damaged. Please check its memory node settings

**Comment by ophub** [comment]
[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10200168/meson-sm1-x96-max-plus-q1.dtb.zip)

try again

**Comment by ophub** [comment]
on usb

**Comment by ophub** [comment]
During USB testing, it must be ensured that the box is the original Android system.

**Comment by ophub** [comment]
wait 1 minute

**Comment by ophub** [comment]
Only test in USB.

You need to confirm whether the u-boot can be used. You can't start it after adding the test before. Now try again

```
cd /boot
cp -f u-boot-x96maxplus.bin u-boot.ext
chmod +x u-boot.ext
sync && reboot
```

**Comment by ophub** [comment]
Is the `u-boot-x96maxplus.bin` available for this test?

`/etc/model_database.conf`

Modify one line, such as the line corresponding to `516`

https://github.com/ophub/amlogic-s9xxx-armbian/blob/10175b7025b5a64c39d7b058f9d3a2e3e24ae45f/build-armbian/armbian-files/common-files/etc/model_database.conf#L117

Column 2, replace `X96-Air-1Gb` with `X96-Max-Plus-Q1`
Column 4, replace `meson-sm1-x96-air-gbit.dtb` with `meson-sm1-x96-max-plus-q1.dtb`


After modification, `armbian-install` select `516` when writing to emmc

**Comment by ophub** [comment]
Good job. I submit this dtb to the upstream kernel repository, and the kernel compiled later will come with it.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/f0d760b25ab2ff1ceb208c4ab2fdeb8578946134

Later Q1 is 523 serial number

**Comment by ophub** [comment]
Share the Android firmware you use, and take pictures of the appearance of the box, the bottom label, the front and back of the motherboard

**Comment by ophub** [comment]
```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2019 BayLibre SAS. All rights reserved.
 * Copyright (c) 2020 Christian Hewitt <christianshewitt@gmail.com>
 * Copyright (c) 2022 Flippy
 */

/dts-v1/;

#include "meson-sm1-x96-air.dts"

/ {
	compatible = "amediatech,x96-max", "amlogic,sm1";
	model = "X96 Max Plus Q1";

	aliases {
		serial0 = &uart_AO;
		ethernet0 = &ethmac;
	};

	memory@0 {
		device_type = "memory";
		reg = <0x0 0x0 0x0 0xf0800000>;
	};
};

&uart_AO {
	status = "okay";
	pinctrl-0 = <&uart_ao_a_pins>;
	pinctrl-names = "default";
};

&ethmac {
	status = "okay";
	phy-handle = <&internal_ephy>;
	phy-mode = "rmii";
};

&internal_ephy  {
	max-speed = <100>;
};

```

[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10200277/meson-sm1-x96-max-plus-q1.dtb.zip)
[meson-sm1-x96-max-plus-q1.dts.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10200278/meson-sm1-x96-max-plus-q1.dts.zip)

**Comment by avigrinberg** [comment]
can you help me to install the current img and dtb for my x96 max+ please?
![20230831_110502](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74825241/072c19b6-3d91-43ab-8195-354d0fe05859)
![20230831_110446](https://github.com/ophub/amlogic-s9xxx-armbian/assets/74825241/4b8a5757-a8c1-4f53-83d3-092e30c53953)
