### ISSUE TITLE
MECOOL KM3 Works

### ISSUE THREAD

**Issue by flymike** [ophub/amlogic-s9xxx-armbian#79]
This is not a bug, just a report of that my MECOOL KM3 (S905x2, 4G/64G/100M net) work great with `meson-g12a-sei510.dtb`. Ethernet/WiFi/BT all work correctly.
This TV box used to be very popular...

**Comment by ophub** [comment]
Thank you very much for your sharing, I will record it in CONTRIBUTOR.md and support list, have you tested him to support 5.15 kernel?

**Comment by flymike** [comment]
Yes. I'm using the latest 5.15 kernel, booted from USB3 thumb drive. Power led, Reboot and Shutdown also work properly.

**Comment by ophub** [comment]
Are you using this configuration?
```
FDTFILE="meson-g12a-sei510.dtb"
UBOOT_OVERLOAD="u-boot-x96max.bin"
MAINLINE_UBOOT="/lib/u-boot/x96max-u-boot.bin.sd.bin"
ANDROID_UBOOT=""
AMLOGIC_SOC="s905x2"
```

**Comment by citral23** [comment]
Just my 2 cents, on Mecool KM9 PRO 4G/32G/100M (which is just another name for the km3, android images work interchangeably) kernel 6.1 doesn't boot at all, only 5.15 works.

meson-g12a-sei510.dtb is unusable because the sd card keeps resetting 
meson-g12a-u200.dtb has everything working perfectly including eth0, but no wlan (I decompiled the dtb and there's none, so not suprising)
meson-g12a-x96max has wlan working but eth0 crashes on a dma error, which slows the boot process quiet a lot, so not ideal

I'll try to see if I can add the wlan to the u200 dtb at some point, for now this devicetree with a usb wifi dongle seems to be the best compromise

**Comment by bywarmx** [comment]
> Mecool KM9 PRO

bro i have a Mecool KM9 PRO, do you have any openwrt for this device?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-openwrt

**Comment by YicLv** [comment]
Mecool KM9 (Not Pro) is also suitable for meson-g12a-sei510.dtb

**Comment by bywarmx** [comment]
> Mecool KM9 (Not Pro) is also suitable for meson-g12a-sei510.dtb

i have Mecool KM9 Pro Classic

**Comment by mfat** [comment]
I have the Mecool KM9  (4/32/100) and trying to boot this. I renamed u-boot-sei510.bin to u-boot.ext but it boots to Android recovery. What other steps should I take? Thanks.

**Comment by aralvesandrade** [comment]
I have a KM9 PRO Classic 2GB + 16GB. Which image works for it, specifically which Kernel version? Could you share the link? Also, what is the correct installation procedure, which u-boot should I use, and which dtb file?

**Comment by bywarmx** [comment]
REYRE-WRT  work very fine  KM9 PRO Classic

**Comment by davelamorte** [comment]
Hello, I have a MECOOL KM3 (S905x2, 4G/64G/100M net)  and I can't find any version that works on it.
I've downloaded Armbian_26.05.0_amlogic_s905x2_trixie_6.18.26_server_2026.05.01.img and flashed it on a SDcard. I use coreelec on this device without any issue with the same method.
Tried all the dtb and bin mentioned in this topic with no success: it always goes to the Android recovery "no command" page.

Can you advise a version that works? Thank you.

**Comment by ciro-mota** [comment]
> I have a KM9 PRO Classic 2GB + 16GB. Which image works for it, specifically which Kernel version? Could you share the link? Also, what is the correct installation procedure, which u-boot should I use, and which dtb file?

Please, which `.dtb` file is recommended for this model?
