### ISSUE TITLE
armbian系统SSH连接拒绝

### ISSUE THREAD

**Issue by cui8** [ophub/amlogic-s9xxx-armbian#790]
路由器后台有连接，但是ssh连接拒绝。
[![zRsOMV.png](https://s1.ax1x.com/2022/12/09/zRsOMV.png)](https://imgse.com/i/zRsOMV)

ssh拒绝连接
[![zRySIJ.png](https://s1.ax1x.com/2022/12/09/zRySIJ.png)](https://imgse.com/i/zRySIJ)

设备：cm311-1a
armbian：Armbian_22.11.0_Aml_s905l3a_jammy_5.15.79_server_2022.11.26.img

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/custom_service/start_service.sh#L25-L27

复制粘贴，保存重启。
