### ISSUE TITLE
HI!O BIG ! 创维E900V21C怎么选DTB？

### ISSUE THREAD

**Issue by urenai** [ophub/amlogic-s9xxx-armbian#791]
**Device Information | 设备信息**
 - SOC: [e.g. S095L]
 - Model [e.g. E900V21C]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
盒子已使用TTL执行reboot update；
已经可以启动EmuELEC，是使用 gxl_p212_1g_slowemmc.dtb 文件；

请问  O BIG  armbian  我应该选择那个DTB文件？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

**Comment by DHinh** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

这里没有E900V21C。。。900v21c的主控是905L

**Comment by ophub** [comment]
/boot目录的uEnv.txt改dtb名称试试下面的两个

meson-gxl-s905x-p212.dtb
meson-gxl-s905x-nexbox-a95x.dtb

把u-boot-s905x-s912.bin复制为
u-boot.ext

**Comment by urenai** [comment]
O BIG!  
无法正确引导，直接进入安卓。
如果提供TTL 跑码，能否分析？

**Comment by ophub** [comment]
不能U盘启动，测试不了。自行解决这一步，仓库里有文档。
