### ISSUE TITLE
armbian第二天用ssh连接时卡住

### ISSUE THREAD

**Issue by Haaooo** [ophub/amlogic-s9xxx-armbian#794]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [cm311-1a yst]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.81-flippy-79+o]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

armbian配置好以后，第二天用ssh连接时会卡住，无法连接。
![屏幕截图_20221210_134516](https://user-images.githubusercontent.com/71207318/206831562-99673343-6a9b-428d-9cb5-5b4582852c71.png)

此时锡系统应该是正常运行的，因为可以从网页进入portainer，而且可以加端口正常打开别的服务

使用的镜像：Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.81_server_2022.12.08.img

系统已使用305 ext4写入emmc

**Comment by ophub** [comment]
`systemctl status ssh`  
看看什么情况

**Comment by Yxini** [comment]
最近固件的ssh好像有点问题，我的CM311-1A盒子也出现了类似的问题，我的是有IP但是ssh连接不上。

**Comment by Haaooo** [comment]
> `systemctl status ssh`
> 看看什么情况

![image](https://user-images.githubusercontent.com/71207318/207305876-05ed5847-77eb-47f2-b23b-e63cd05e059e.jpg)


系统版本我更换为图中的5.15.68了
还是出现了一样的问题

**Comment by xiaolei0125** [comment]
这个问题修复了吗？
我的是M401A:  Armbian 22.11.0-trunk Jammy with Linux 5.15.78-flippy-78+o;
测试多台M401,   发现每隔几天用ssh就无法连接M401A了，但M401A上的其他网络和服务都正常。
目前设备不在本地，只能让人断电重启后解决。
