### ISSUE TITLE
zigbee2mqtt的软件安装请求

### ISSUE THREAD

**Issue by Trace-star** [ophub/amlogic-s9xxx-armbian#795]
zigbee2mqtt在日常中使用频繁，希望大佬怎家对zigbee2mqtt的 支持

**Comment by ophub** [comment]
https://www.zigbee2mqtt.io/guide/installation/02_docker.html

`--device` is a changing value, which needs to be updated according to your own device. Therefore, it is not convenient to use one key script.

**Comment by Trace-star** [comment]
Can we first not operate --device, just pull and run zigbee2mqtt, and then freely set --device in the generated configuration.yaml file, because this --device can be used with USB/tcp, etc.

**Comment by Trace-star** [comment]
https://www.youtube.com/watch?v=HbkXQErileU&t=340s这个作者的方法就是后面设置--device
