### ISSUE TITLE
e900v22d无法使用有线网

### ISSUE THREAD

**Issue by Eiranya** [ophub/amlogic-s9xxx-armbian#798]
**Device Information | 设备信息**
 - SOC: [S905L3A-B]
 - Model [e900v22d]

**Armbian Version | 系统版本**
 Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.82_server_2022.12.09

**Describe the bug | 问题描述**
启动方式是从cf/usb启动，没有写入emmc

无法驱动有线网卡
`[925.088374]meson8b-dwmac ff3f0000.ethernet eth0: no phy at addr -1`
`[925.094357]meson8b-dwmac ff3f0000.ethernet eth0: stmmac_open: Cannot attach to PHY (error: -19)`
`[925.171345]mesonBb-dumac ff3f0000.ethernt eth0: yalidation of mmi with support 00000,00000,0006280 and adyertisement 0000,0000,006280 failed -22`
![QQ截图20221210234149](https://user-images.githubusercontent.com/34960104/206885549-c89f435f-8c7d-47df-9de7-c192cfe53639.png)

另外，我改了8822cs无线网卡，请问如何添加驱动呢

**Comment by ophub** [comment]
```
cd /boot
cp -f u-boot-e900v22c.bin u-boot.ext
chmod +x u-boot.ext
sync && reboot
```

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/663

看看这个

**Comment by Eiranya** [comment]
> #663
> 
> 看看这个

请问，想要驱动8822cs的话要怎么弄呢？

**Comment by ophub** [comment]
这个驱动从第三方添加的，已经在内核里带了，如果可以用直接可以驱动。之前分享这个驱动的印尼网友测试了没问题，我在x96 max+里也可以用，但是也有人反馈不能用或者不稳定。
