### ISSUE TITLE
restore stock uboot on s905x3

### ISSUE THREAD

**Issue by marohinmark** [ophub/amlogic-s9xxx-armbian#799]
What is the block device for uboot, I found stock uboot but idk where to flash it. s905x3/h96 max x3

**Comment by marohinmark** [comment]
tried flashing in mmcblk2boot0. got no changes

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/rebuild


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/amlogic/rootfs/usr/sbin/armbian-install

**Comment by marohinmark** [comment]
so i have to overwrite the whole mmc block with u-boot? strange.

**Comment by ophub** [comment]
i don't know what you are doing

**Comment by marohinmark** [comment]
trying to restore adrod without testpoint (box wont enter flash mode)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#123-how-to-restore-the-original-android-tv-system

**Comment by marohinmark** [comment]
okay, thx. found the testpoint that should work
