### ISSUE TITLE
Add u-boot.bin for GT1-mini-a

### ISSUE THREAD

**Issue by netdrg** [ophub/amlogic-s9xxx-armbian#80]
Hi can you add please uboot.bin for GT1-mini-a to install on emmc.

**Comment by ophub** [comment]
try u-boot-x96max.bin

**Comment by netdrg** [comment]
> try u-boot-x96max.bin

Thank's for your answer, i have tested but this brick the device

**Comment by ophub** [comment]
5.4 kernel does not need this, you try
