### ISSUE TITLE
Phicomm-n1刷入后lightdm无法正常启动

### ISSUE THREAD

**Issue by OortNebula** [ophub/amlogic-s9xxx-armbian#802]
**Device Information | 设备信息**
 - SOC: [e.g. S905D]
 - Model [e.g. Phicomm-n1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.0.12]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
在刷入最新固件（Armbian_23.02.0_amlogic_s905d_bullseye_6.0.12_server_2022.12.08）后运行armbian-soft安装桌面重启后lightdm无法启动。

复现过程：1.将镜像通过USB-image-tool写入U盘；
                   2.N1通过U盘起动后设置root密码及新建账户连接网络；
                   3.运行armbian-install选择101及ext4刷入EMMC；
                   4.更换国内源：(1)备份修改/etc/apt/sources.list内容为
                                                   deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye main contrib non-free
                                                   deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-updates main contrib non-free
                                                   deb https://mirrors.tuna.tsinghua.edu.cn/debian/ bullseye-backports main contrib non-free
                                                   deb https://mirrors.tuna.tsinghua.edu.cn/debian-security bullseye-security main contrib non-free
                                              (2)在/etc/apt/sources.list.d/目录下新建armbian.list并添加
                                                   deb http://mirrors.tuna.tsinghua.edu.cn/armbian/ bullseye main bullseye-utils bullseye-desktop
                                              (3)运行apt update &&  apt upgrade 进行更新
                     5.运行armbian-software选择201进行桌面环境的安装，期间出现设置登陆用户及中文桌面的选项，安装完成重启后无法 
                         进入登陆界面，具体报错为failed to start lightdm；

进行的尝试：1.通过翻阅其他issues发现有相同的问题，参考大佬回复进行尝试，通过armbian-software卸载桌面进行重新安装，期间
                          并未出现描述中的选择显示管理器的选项，lightdm.conf中开启logind-check-graphical，安装完成后问题依旧，更 
                          换镜像 Armbian_23.02.0_amlogic_s905d_jammy_6.0.11_server_2022.12.07进行尝试，发现该镜像安装桌面过程中出 
                          现了选择gdm3/lightdm的选项，选择gdm3能成功进入桌面，但该桌面N1运行较为吃力，存在卡顿现象，期间安装了 
                          lxde、xfce等桌面，但是均无法正常登陆，再次重新安装桌面选择lightdm后依然无法启动；
                        2.在尝试三个版本的镜像均无法启动lightdm后针对报错日志进行分析，期间通过安装accountsservice解决了lightdm日 
                           志中WARNING: Error getting user list from org.freedesktop.Accounts:的问题，通过lightdm --test-mode --debug
                          观察lightdm似乎已经正常,日志如下：
```

                          root@armbian:~# lightdm --test-mode --debug
[+0.00s] DEBUG: Logging to /var/log/lightdm/lightdm.log
[+0.00s] DEBUG: Starting Light Display Manager 1.26.0, UID=0 PID=1999
[+0.00s] DEBUG: Loading configuration dirs from /usr/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /usr/share/lightdm/lightdm.conf.d/01_debian.conf
[+0.00s] DEBUG: Loading configuration dirs from /usr/local/share/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration dirs from /etc/xdg/lightdm/lightdm.conf.d
[+0.00s] DEBUG: Loading configuration from /etc/lightdm/lightdm.conf
[+0.00s] DEBUG: Registered seat module local
[+0.00s] DEBUG: Registered seat module xremote
[+0.00s] DEBUG: Registered seat module unity
[+0.00s] DEBUG: Using D-Bus name org.freedesktop.DisplayManager
[+0.01s] DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
[+0.01s] DEBUG: Monitoring logind for seats
[+0.01s] DEBUG: New seat added from logind: seat0
[+0.01s] DEBUG: Seat seat0: Loading properties from config section Seat:*
[+0.02s] DEBUG: Seat seat0 has property CanMultiSession=no
[+0.02s] DEBUG: Seat seat0: Starting
[+0.02s] DEBUG: Seat seat0: Creating greeter session
[+0.02s] DEBUG: Seat seat0: Creating display server of type x
[+0.02s] DEBUG: Using VT 7
[+0.02s] DEBUG: Seat seat0: Starting local X display on VT 7
[+0.02s] DEBUG: XServer 0: Logging to /var/log/lightdm/x-0.log
[+0.02s] DEBUG: XServer 0: Writing X server authority to /var/run/lightdm/root/:0
[+0.02s] DEBUG: XServer 0: Launching X Server
[+0.02s] DEBUG: Launching process 2005: /usr/bin/X :0 -seat seat0 -auth /var/run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
[+0.02s] DEBUG: XServer 0: Waiting for ready signal from X server :0
[+0.03s] DEBUG: Acquired bus name org.freedesktop.DisplayManager
[+0.03s] DEBUG: Registering seat with bus path /org/freedesktop/DisplayManager/Seat0
[+0.03s] DEBUG: Loading users from org.freedesktop.Accounts
[+0.03s] DEBUG: User /org/freedesktop/Accounts/User1000 added
[+0.17s] DEBUG: Process 2005 exited with return value 1
[+0.17s] DEBUG: XServer 0: X server stopped
[+0.17s] DEBUG: Releasing VT 7
[+0.17s] DEBUG: XServer 0: Removing X server authority /var/run/lightdm/root/:0
[+0.17s] DEBUG: Seat seat0: Display server stopped
[+0.17s] DEBUG: Seat seat0: Stopping session
[+0.17s] DEBUG: Seat seat0: Session stopped
[+0.17s] DEBUG: Seat seat0: Stopping display server, no sessions require it
[+0.17s] DEBUG: Seat seat0: Stopping; greeter display server failed to start
[+0.17s] DEBUG: Seat seat0: Stopping
[+0.17s] DEBUG: Seat seat0: Stopped
[+0.17s] DEBUG: Required seat has stopped
[+0.17s] DEBUG: Stopping display manager
[+0.17s] DEBUG: Display manager stopped
[+0.17s] DEBUG: Stopping daemon
[+0.18s] DEBUG: Exiting with return value 1
```

                       但是lightdm仍然无法启动，执行startx后Xorg.0.log报错为：
```

root@armbian:~# cat /var/log/Xorg.0.log | grep EE
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  3870.555] (EE) 
[  3870.555] (EE) Cannot run in framebuffer mode. Please specify busIDs        for all framebuffer devices
[  3870.555] (EE) 
[  3870.555] (EE) 
[  3870.555] (EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
[  3870.555] (EE) 
[  3870.619] (EE) Server terminated with error (1). Closing log file.
```
                       
                        通过查阅相关资料似乎该错误并不是造成lightdm无法启动的原因，并无影响；
                     3.排查问题无果的情况下用bullseye尝试不通过software进行安装，但是lightdm安装后仍无法启动，安装gdm3可以启动 
                         到登陆界面但无法登陆，点击登陆黑屏后返回登陆界面，root及普通用户均无法登陆；
                     4.上述尝试中只有jammy版本且选择gdm可以正常登陆桌面，bullseye安装桌面均失败，遂怀疑为软件源的问题,更改清华 
                         源及华为源进行安装问题依旧，依然是lightdm无法启动。

疑问：1.翻阅其它issues中大佬的回复自测安装桌面及使用是无问题的，且安装过程中会有选择gdm3/lightdm的选项，但我在尝试三 
              版镜像十余次重装过程中只有jammy出现该选项，bullseye_5.15.80及bullseye_6.0.12版本均未出现，安装过程中默认选择的 
              lightdm,卸载重装及重刷系统重装均有尝试，且其他issues也有相同的问题表明我遇到的情况不是个例，所以贴出了详细的安 
              装步骤麻烦大佬帮忙看下是不是漏掉了什么过程或者有误造成的安装失败？
           2.重点是否在于安装过程中未出现选择显示管理器的选项，是否bullseye版在安装过程中跳过了一些软件包？
           2.大佬是否可以简单描述下正确的安装过程以供参考？

期待大佬的解惑，感谢！

**Comment by ophub** [comment]
不要还源，默认的源就可以。换了其他源可能有问题。我自己反复装了N遍都没问题。

**Comment by ophub** [comment]
![Snip20221211_1](https://user-images.githubusercontent.com/68696949/206901554-56267688-2c17-4b51-81ab-974b7476bde1.png)
![Snip20221211_2](https://user-images.githubusercontent.com/68696949/206901559-5e257d04-f913-456e-9159-215d8bd08999.png)
![Snip20221211_3](https://user-images.githubusercontent.com/68696949/206901561-bd90482a-13f3-4b1e-b8a0-ef535e34f2ed.png)
![Snip20221211_6](https://user-images.githubusercontent.com/68696949/206901564-440e4e4c-6e70-4cf6-92f8-09877bdad94b.png)
![Snip20221211_8](https://user-images.githubusercontent.com/68696949/206901566-72ffd714-2251-4e4f-bd32-a07f4914566d.png)
![Snip20221211_9](https://user-images.githubusercontent.com/68696949/206901567-490f98ee-7d33-4a05-bd45-c51d3d06c515.png)
![Snip20221211_10](https://user-images.githubusercontent.com/68696949/206901569-11859e0e-8698-45ae-ad9a-8056816e0a83.png)
![Snip20221211_11](https://user-images.githubusercontent.com/68696949/206901570-a727e079-5269-41a5-a836-8bc61e6e15af.png)

**Comment by OortNebula** [comment]
> 不要换源，默认的源就可以。换了其他源可能有问题，之前的帖子里已经有人换源后很多软件包无法安装。我自己反复装了N遍都没问题。我现在弄U盘刷个新的靶心再给你演示一遍我默认源安装桌面的过程，给你截图展示一下。

非常感谢大佬的解答！ 唯一没有尝试过的就是用官方源安装了，因为速度实在是太慢，原来问题出现在这里，我挂个代理重装试试

**Comment by mimokini** [comment]
你如果还是没有成功试试这个吧，我之前用官方源也没有成功，跟你一样。
粘贴回车重启

cat << '_EOF_' > /etc/X11/xorg.conf.d/02-dietpi-aml-s905.conf
Section "OutputClass"
    Identifier "Amlogic"
    MatchDriver "meson"
    Driver "modesetting"
    Option "PrimaryGPU" "true"
EndSection
Section "Screen"
    Identifier "Default Screen"
    Device "Meson"
    Monitor "foo"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
    EndSubSection
EndSection
_EOF_

如果还不行的话：
apt install accountsservice
mkdir /var/lib/lightdm/data
chmod 775 /var/lib/lightdm/data

**Comment by OortNebula** [comment]
> 你如果还是没有成功试试这个吧，我之前用官方源也没有成功，跟你一样。 粘贴回车重启
> 
> ```
> cat << '_EOF_' > /etc/X11/xorg.conf.d/02-dietpi-aml-s905.conf
> Section "OutputClass"
>     Identifier "Amlogic"
>     MatchDriver "meson"
>     Driver "modesetting"
>     Option "PrimaryGPU" "true"
> EndSection
> Section "Screen"
>     Identifier "Default Screen"
>     Device "Meson"
>     Monitor "foo"
>     DefaultDepth 24
>     SubSection "Display"
>         Depth 24
>         Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
>     EndSubSection
> EndSection
> _EOF_
> ```
> 
> 如果还不行的话：
> 
> ```
> apt install accountsservice
> mkdir /var/lib/lightdm/data
> chmod 775 /var/lib/lightdm/data
> ```

非常感谢！你的回答解决了我的问题，祝你生活愉快！

**Comment by Vector-Cross** [comment]
> 你如果还是没有成功试试这个吧，我之前用官方源也没有成功，跟你一样。 粘贴回车重启
> 
> ```
> cat << '_EOF_' > /etc/X11/xorg.conf.d/02-dietpi-aml-s905.conf
> Section "OutputClass"
>     Identifier "Amlogic"
>     MatchDriver "meson"
>     Driver "modesetting"
>     Option "PrimaryGPU" "true"
> EndSection
> Section "Screen"
>     Identifier "Default Screen"
>     Device "Meson"
>     Monitor "foo"
>     DefaultDepth 24
>     SubSection "Display"
>         Depth 24
>         Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
>     EndSubSection
> EndSection
> _EOF_
> ```
> 
> 如果还不行的话：
> 
> ```
> apt install accountsservice
> mkdir /var/lib/lightdm/data
> chmod 775 /var/lib/lightdm/data
> ```

到现在了N1还是有这个问题，找了好久终于解决了，感谢大神。另外，这个可视化界面还是不太流畅，看来大家都没在用了

**Comment by wv1124** [comment]
> 你如果还是没有成功试试这个吧，我之前用官方源也没有成功，跟你一样。 粘贴回车重启
> 
> ```
> cat << '_EOF_' > /etc/X11/xorg.conf.d/02-dietpi-aml-s905.conf
> Section "OutputClass"
>     Identifier "Amlogic"
>     MatchDriver "meson"
>     Driver "modesetting"
>     Option "PrimaryGPU" "true"
> EndSection
> Section "Screen"
>     Identifier "Default Screen"
>     Device "Meson"
>     Monitor "foo"
>     DefaultDepth 24
>     SubSection "Display"
>         Depth 24
>         Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
>     EndSubSection
> EndSection
> _EOF_
> ```
> 
> 如果还不行的话：
> 
> ```
> apt install accountsservice
> mkdir /var/lib/lightdm/data
> chmod 775 /var/lib/lightdm/data
> ```

牛，竟然解决了 s905X 刷 的 Armbian_23.05.0_amlogic_s905x_jammy_5.15.113_server_2023.05.26.img.gz这个版本

**Comment by QAQ-cmd** [comment]
> 你如果还是没有成功试试这个吧，我之前用官方源也没有成功，跟你一样。 粘贴回车重启
> 
> ```
> cat << '_EOF_' > /etc/X11/xorg.conf.d/02-dietpi-aml-s905.conf
> Section "OutputClass"
>     Identifier "Amlogic"
>     MatchDriver "meson"
>     Driver "modesetting"
>     Option "PrimaryGPU" "true"
> EndSection
> Section "Screen"
>     Identifier "Default Screen"
>     Device "Meson"
>     Monitor "foo"
>     DefaultDepth 24
>     SubSection "Display"
>         Depth 24
>         Modes "1920x1080" "1440x900" "1280x720" "1280x1024" "1280x960" "1024x768" "800x600" "640x480" "720x400"
>     EndSubSection
> EndSection
> _EOF_
> ```
> 
> 如果还不行的话：
> 
> ```
> apt install accountsservice
> mkdir /var/lib/lightdm/data
> chmod 775 /var/lib/lightdm/data
> ```

厉害的 ,也解决我的问题了。
