### ISSUE TITLE
M401A 制作了启动盘，但是黑屏无法启动

### ISSUE THREAD

**Issue by halida** [ophub/amlogic-s9xxx-armbian#804]
**Device Information | 设备信息**
 - SOC: s905l3a （问了卖家）
 - Model 魔百和 M401A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.82
 - Release: jammy

**Describe the bug | 问题描述**

下载和烧录以下镜像：
Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.82_server_2022.12.09.img.gz
Armbian_23.02.0_amlogic_s905l3a_jammy_6.0.12_server_2022.12.09.img.gz
用adb connect IP
adb shell reboot update
然后插入优盘，屏幕提示无视频输入，然后一直卡在这里。
如果不插入优盘，会提示update失败和重启菜单。

请问有什么调试和判断方法？

**Comment by halida** [comment]
卖家说还需要改dtb和uEna，不知道怎么改。

**Comment by halida** [comment]
改了uEnv.txt：

FDT=/dtb/amlogic/meson-g12a-s905l3a-m401a.dtb

但是还是不行，设备黑屏，读了一下U盘，就没有反应了。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/732

看这个

**Comment by halida** [comment]
换

> #732
> 
> 看这个

现在是优盘都没有启动起来，插了键盘，numlock也没有反应。要换固件？

**Comment by halida** [comment]
根据这里的教程：
https://bbs.hassbian.com/thread-17263-1-1.html

用了这个 meson-g12a-u200.dtb 启动起来了。

**Comment by ophub** [comment]
好的，那就有u200吧，这些盒子，同名不同芯的很多，不同省份的魔百和也有不一样的，只看名称可能不准确。XCray在这个问答区里也有很多关于M401A的经验分享，你可以多看看往期的帖子。

**Comment by halida** [comment]
看armbian-install，改成304的方法，提示：

```
[ INFO ] Start create MBR and partittion.
[ INFO ] Restore the mybox bootloader: [ /usr/lib/u-boot/mybox-bootloader.img ]
444+0 records in
444+0 records out
444 bytes copied, 0.0114895 s, 38.6 kB/s
dd: fsync failed for '/dev/mmcblk2': Input/output error
8191+0 records in
8191+0 records out
4193792 bytes (4.2 MB, 4.0 MiB) copied, 4.90525 s, 855 kB/s
[ STEPS ] Start processing the bootfs partition...
[ INFO ] Formatting BOOTFS partition.
mkfs.fat 4.2 (2021-01-31)
[ INFO ] Start copy BOOTFS partition data.
cp: error writing '/ddbr/install/vmlinuz-5.15.82-flippy-79+o': Input/output error
cp: cannot create regular file '/ddbr/install/zImage': Read-only file system
[ INFO ] Generate the new [ uEnv.txt ] file.
rm: cannot remove '/ddbr/install/uEnv.txt': Read-only file system
/usr/sbin/armbian-install: line 407: /ddbr/install/uEnv.txt: Read-only file system
rm: cannot remove '/ddbr/install/s905_autoscript': Read-only file system
rm: cannot remove '/ddbr/install/s905_autoscript.cmd': Read-only file system
rm: cannot remove '/ddbr/install/aml_autoscript': Read-only file system
rm: cannot remove '/ddbr/install/aml_autoscript.cmd': Read-only file system
mv: cannot move '/ddbr/install/boot-emmc.ini' to '/ddbr/install/boot.ini': Read-only file system
sed: couldn't open temporary file /ddbr/install/sed4930Hh: Read-only file system
mv: cannot move '/ddbr/install/boot-emmc.scr' to '/ddbr/install/boot.scr': Read-only file system
mv: cannot move '/ddbr/install/boot-emmc.cmd' to '/ddbr/install/boot.cmd': Read-only file system
[ STEPS ] Start processing the rootfs partition...
[ INFO ] Formatting ROOTFS partition.
btrfs-progs v5.16.2
See http://btrfs.wiki.kernel.org for more information.

Performing full device TRIM /dev/mmcblk2p2 (13.75GiB) ...
NOTE: several default settings have changed in version 5.15, please make sure
      this does not affect your deployments:
      - DUP for metadata (-m dup)
      - enabled no-holes (-O no-holes)
      - enabled free-space-tree (-R free-space-tree)

ERROR: error during mkfs: Operation not permitted
mount: /ddbr/install: wrong fs type, bad option, bad superblock on /dev/mmcblk2p2, missing codepage or helper program, or other error.
[ ERROR ] Failed to mount ROOTFS partition

```

**Comment by ophub** [comment]
M401A的那个你不能用，可能是频率高，最高的那个1800之前也有人不能使用，删除这个测试下。

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-m401a.dts#L146-L151

你无法正常使用emmc的问题调频后应该可以解决。

**Comment by halida** [comment]
删除这个是不是还需要重新编译啊？

**Comment by halida** [comment]
@HoYin90 请问你跑起来了吗？烧录成功了不？我现在还是只能u盘跑。

**Comment by zhangbin088** [comment]
[ OPTIONS ] Please Input ID (1/2): 1
[ INFO ] Input Type ID: [ 1 ]
[ INFO ] Type of filesystem: [ ext4 ]
[ STEPS ] Partitioning eMMC...
[ INFO ] Start backing up the default bootloader.
4+0 records in
4+0 records out
4194304 bytes (4.2 MB, 4.0 MiB) copied, 6.53328 s, 642 kB/s
[ INFO ] Start create MBR and partittion.
[ INFO ] 03. Write the mybox bootloader: [ /usr/lib/u-boot/mybox-bootloader.img ]
444+0 records in
444+0 records out
444 bytes copied, 0.00370914 s, 120 kB/s
dd: fsync failed for '/dev/mmcblk2': Input/output error
8191+0 records in
8191+0 records out
4193792 bytes (4.2 MB, 4.0 MiB) copied, 0.785406 s, 5.3 MB/s
[ ERROR ] Failed to write bootloader using [ dd ].

**Comment by univerioiln233** [comment]
> [#732](https://github.com/ophub/amlogic-s9xxx-armbian/issues/732)
> 
> 看这个

cm311 CH，双勾选刷入unt403的安卓包后，使用E900V22C/D, CM311-1a-YST, M401A 三个dtb均不能进入u盘linux系统。

**Comment by univerioiln233** [comment]
> > [#732](https://github.com/ophub/amlogic-s9xxx-armbian/issues/732)
> > 看这个
> 
> cm311 CH，双勾选刷入站内unt403的安卓包后，使用E900V22C/D, CM311-1a-YST, M401A 三个dtb均不能进入u盘linux系统。

这个盒子两年前（默认安卓底包）刷U盘系统时很顺利。无任何操作

**Comment by univerioiln233** [comment]
> > > [#732](https://github.com/ophub/amlogic-s9xxx-armbian/issues/732)
> > > 看这个
> > 
> > 
> > cm311 CH，双勾选刷入站内unt403的安卓包后，使用E900V22C/D, CM311-1a-YST, M401A 三个dtb均不能进入u盘linux系统。
> 
> 这个盒子两年前（默认安卓底包）刷U盘系统时很顺利。无任何操作

建议每个盒子的document都配上相应的安卓底包，尤其是这个安卓的bootloader

**Comment by univerioiln233** [comment]
![Image](https://github.com/user-attachments/assets/7beef241-37be-4095-8a86-afc582f9f31b)

![Image](https://github.com/user-attachments/assets/91085a58-78b6-4644-ab18-0eb75f07e316)
