### ISSUE TITLE
l1pro 不支持usb网卡 ax88179

### ISSUE THREAD

**Issue by dos7lo** [ophub/amlogic-s9xxx-armbian#805]
SOC: [rk3328]
Model [l1pro]
Armbian_bullseye_12.09.0057
Kernel Version: 5.15 6.12
不支持usb网卡 ax88179
查看usb设备显示为存储设备，应该是无驱动，能否添加驱动支持。

**Comment by dos7lo** [comment]
SOC: [rk3328]
Model [l1pro]
Armbian_bullseye_12.09.0057
Kernel Version: 5.15 6.12
不支持usb网卡 ax88179
查看usb设备显示为存储设备，应该是无驱动，能否添加驱动支持。

**Comment by ophub** [comment]
http://www.lulian.cn/download/44-cn.html

在官网下载安装即可

**Comment by dos7lo** [comment]
> http://www.lulian.cn/download/44-cn.html
> 
> 在官网下载安装即可

好的 谢谢大佬 因为之前m401用的rtl就自带了，查的有点迷糊，以为是需要配置编译。

**Comment by dos7lo** [comment]
> http://www.lulian.cn/download/44-cn.html
> 
> 在官网下载安装即可

有点问题因为要下内核源码 armbian-kernel 不支持10gb以下 这一块比较迷糊 所以暂时放弃了  谢谢大佬解答
