### ISSUE TITLE
意外断电后，root密码登录不了了

### ISSUE THREAD

**Issue by fangyishui** [ophub/amlogic-s9xxx-armbian#808]
**Device Information | 设备信息**
魔百盒 cm311-1a

**Armbian Version | 系统版本**
Armbian 23.02.0-trunk Jammy with Linux 5.15.81-flippy-79+o

**Describe the bug | 问题描述**
系统刷入emmc都没问题，手动reboot重启也正常。
但是如果直接断电后再启动，root密码就登录不了了。
奇怪的时一些开机自启动的服务还在正常运行，比如docker，smb这些？
我试了一般账号还可以登录

![image](https://user-images.githubusercontent.com/39973922/207207695-fd5c3f71-0027-4dad-8ee7-bb067c6bbf86.png)

![image](https://user-images.githubusercontent.com/39973922/207207759-c423fcef-cf99-4aee-811e-b5610ad6e081.png)

**Comment by ophub** [comment]
系统在日常工作中，会把大量的读写数据放在缓存里，如果直接拔了电，可能会有丢失。测试方法，用压缩命令打包一个1 G的文件，然后执行sync命令，你会发现要几秒种才能执行完成，这个时间就是数据从内存刷回emmc的时间。所以为了不丢失数据，重启时我一般用命令`sync && reboot`，而不是直接拔电源。

**Comment by fangyishui** [comment]
额，那没有别的办法了吗，总有断电或者移动盒子的时候。
之前已经有过一次这个情况了，重新刷的系统。。。

**Comment by urenai** [comment]
O Big，正解，还是reboot的好。

**Comment by fangyishui** [comment]
@urenai 是reboot好呀，但总有意外情况。要是停电什么的。不是再也登录不了了。。。

**Comment by ophub** [comment]
每次的惊喜不同，也许是别的问题。也可能没有什么问题。

**Comment by janko888** [comment]
使用overlayroot？
似乎从名字看来可以保护root文件系统，没研究过。可以了解一下
![1234](https://user-images.githubusercontent.com/103774532/207221879-d21b9af3-1759-492a-b2f5-86e2b7f832d0.png)

**Comment by fangyishui** [comment]
@ophub @janko888 基本都是默认配置。我研究研究吧
