### ISSUE TITLE
江波龙内存颗粒，物理规格2G，uboot下只能识别出来1G. 

### ISSUE THREAD

**Issue by sniperpr** [ophub/amlogic-s9xxx-armbian#809]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095L3A]
 - Model [B863AV3.2-M] (实际上和e900v22c ，CM311通用固件）

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.55]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

![image](https://user-images.githubusercontent.com/1270268/207292909-616ce14e-2362-4051-a4f6-a711848acb0f.png)

![5795420b1adf0c1a07da424b9062d51](https://user-images.githubusercontent.com/1270268/207292813-d1e98b88-4742-4d02-ae3c-8d25810571e3.jpg)

**Comment by urenai** [comment]
可能没选对文件，
或者 这属于增强型盒子，各种五花八门 O Big 不可能收集全。

**Comment by ophub** [comment]
如果有安卓系统的dtb文件，可以试着改现在的内存注册地址

**Comment by sniperpr** [comment]
> 
这个是解包 能正常识别2G内存的 android rom的 dtb

[_aml_dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10225218/_aml_dtb.zip)

**Comment by sniperpr** [comment]
android 启动，用串口看内存识别是OK的。
![image](https://user-images.githubusercontent.com/1270268/207533601-b74134b3-129b-41b4-ae43-e411c170a5b7.png)

**Comment by ophub** [comment]
你提供的文件无法使用

**Comment by sniperpr** [comment]
我把uboot 给打包传上来。

**Comment by sniperpr** [comment]
我把uboot 给打包传上来。
[DDR.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10233420/DDR.zip)
