### ISSUE TITLE
Taking Long Time To Boot - "start job is running for raise network interfaces"

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#81]
@ophub,

Device: GT KING PRO Revision A
Image: Armbian_22.02.0_Aml_s922x_bullseye_5.15.15_2022.01.16.2138.img.gz with Gnome Desktop Installed
DTB: meson-g12b-gtking-pro.dtb default from the image
u-boot.ext:  u-boot-gtkingpro-rev-a.bin
Boot Device Storage: USB 3.1 Flash

Boot up time can take more than 6 minutes at times.  
Waiting for "start job is running for raise network interfaces" sometimes more than 5 minutes before it continue to boot.

Similar issue with Armbian_22.02.0_Aml_s922x-reva_focal_5.15.14_2022.01.15.0007.img.gz can take more than 6 minutes to boot.

![image](https://user-images.githubusercontent.com/75384411/149876618-7bf51152-2917-48d0-a5a4-3c7cc2187ab0.png)

**Comment by ophub** [comment]
This file `u-boot-gtkingpro-rev-a.bin` is provided by you. Your test feedback said that the previous file `u-boot-gtkingpro.bin` cannot be started. This one can always be started.

I also tested and changed your file on my device yesterday, and I also found that the startup time is long, especially when I just plugged in the power supply, there is no output from the display for `5-10 seconds`, so I thought it could not be started. , but after waiting for 10 seconds, the code began to appear, and it started normally. My box has tested several other aa files, which can be used on usb, but only the one you provide can be used to `write emmc`.

**Comment by JFLim1** [comment]
> This file `u-boot-gtkingpro-rev-a.bin` is provided by you. Your test feedback said that the previous file `u-boot-gtkingpro.bin` cannot be started. This one can always be started.
> 
> I also tested and changed your file on my device yesterday, and I also found that the startup time is long, especially when I just plugged in the power supply, there is no output from the display for `5-10 seconds`, so I thought it could not be started. , but after waiting for 10 seconds, the code began to appear, and it started normally. My box has tested several other u-boot.ext files, which can be used on usb, but only the one you provide can be used to `write emmc`.

For your info, I use this so called u-boot-gtkingpro-rev-a.bin on other Linux distro and does not have this long delay at  in waiting **"start job is running for raise network interfaces"**.

Could it be kernel settings related?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/72#issuecomment-1012127495

This file is provided by you, I downloaded it and renamed it for convenience. It should have nothing to do with the kernel, but with the model of your device.

**Comment by ophub** [comment]
> the screen was unresponsive and completely black. But it starts after 10 seconds.
> Also experience "black screen" after boot up successful to desktop and within 5 minutes later "black screen".

> Resolved this by renaming/disabling hdmi.rules in /etc/udev/rules.d/

Did you rename the file like this so it won't get a black screen? Is this practice common to other devices? Are there any side effects?

**Comment by JFLim1** [comment]
> Did you rename the file like this so it won't get a black screen? Is this practice common to other devices? Are there any side effects?

Example renamed it to hdmi.rules-not-required.  So far after this work around, no more "black screen" issue.

Side effects? Not sure about it.  But so far I don't see any.

**Comment by ophub** [comment]
This is good news.
The new box I bought yesterday arrived, and I tested it on the usb and everything was fine. But after writing emmc, there is a long black screen for 5-10 seconds at the beginning of startup. I thought that writing emmc failed, and I was searching for the short-circuit point of this motherboard, and it turned on. I retried a few times, and each time it required me to wait, and this is the first box I've seen that doesn't show up right away when it starts up.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/fc88785c6ce6e2d7ed4591e5e00034810556146d

I added it to the default settings, thank you for sharing

**Comment by JFLim1** [comment]
> I added it to the default settings, thank you for sharing

Does it work on your device by removing hdmi.rules? 

I have a question, I see new images with the same kernel being build and released, if we have an older image how to we update/upgrade to latest build image?  For example I am currently using "Armbian_22.02.0_Aml_s922x_bullseye_5.15.15_2022.01.16.2138.img.gz" and the new build is "Armbian_22.02.0_Aml_s922x_bullseye_5.15.15_2022.01.18.1656.img.gz", how do we upgrade to this new image without having to re-burn the image?

**Comment by ophub** [comment]
> Does it work on your device by removing hdmi.rules?

I can use

> how do we upgrade to this new image without having to re-burn the image?

The new ones are just fine-tuning some scripts based on your feedback, which can generally be ignored, or refer to and modify the local settings.
