### ISSUE TITLE
我是想使用cm311-1a作为klipper的上位机。在使用can通信的时候遇到了问题。

### ISSUE THREAD

**Issue by Anywherexu** [ophub/amlogic-s9xxx-armbian#817]
Standard chat template, no routine, no chat.
如标题，我按照klipper提示在/etc/network/interfaces.d/can0 创建一个can0的文件，该文件包含以下内容：
_auto can0
iface can0 can static
    bitrate 500000
    up ifconfig $IFACE txqueuelen 128_
但是当我插上usb to can的设备时，使用ifconfig -a无法查看到can0的相关信息。使用ifconfig can0指令反馈为：can0: error fetching interface information: Device not found。
请问我这种情况该如何解决？？？

**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - Model [e.g. CM311-1a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.82]
 - Release: [e.g. jammy]

**Comment by ophub** [comment]
用什么驱动？

**Comment by Anywherexu** [comment]
> 
我发现内核编译的时候没选can功能。我尝试使用actions自己编译遇到问题。编译完后无法上传至release。每一步都是按照教程做的。就是不成功。token都申请3次了。有没有什么别的办法？或者说我该如何解决这个问题？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#2-set-the-privacy-variable-github_token

第2-3的token名称要和说明里面的一样

**Comment by Anywherexu** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#2-set-the-privacy-variable-github_token
> 
> 第2-3的token名称要和说明里面的一样
终于编译成功了。感谢回复

**Comment by Anywherexu** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#2-set-the-privacy-variable-github_token
> 
> 第2-3的token名称要和说明里面的一样

选上了can也不行。ifconfig无法发现。u2c使用的固件是https://github.com/candle-usb/candleLight_fw这个。希望能帮助一下。我看这个固件说的是不需要驱动的。Ubuntu 的x86版是可以识别的。这个就不行，不知道是哪个包没选。

**Comment by ophub** [comment]
我不会用这个，你在他的问题区问一下有没有armbian使用方法
