### ISSUE TITLE
Wifi card not detecting

### ISSUE THREAD

**Issue by sunilsankar** [ophub/amlogic-s9xxx-armbian#819]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S905l2
 - Model : Q96 mini plus

**Armbian Version | 系统版本**
 - Kernel Version: 6.0.12
 - Release: bullseye

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Wifi card is not detecting . I was able to use the emmc install and everything is working . Please find the motherboard details

![WhatsApp Image 2022-12-14 at 2 05 36 PM](https://user-images.githubusercontent.com/2275957/207603233-0e7e7c1f-74b7-4270-8459-05c6ba07eb4b.jpeg)

![WhatsApp Image 2022-12-14 at 2 05 36 PM (1)](https://user-images.githubusercontent.com/2275957/207603273-3edcddc5-556c-44b3-adbe-0af5a5f1ed75.jpeg)

**Comment by ophub** [comment]
Didn't see what it was

**Comment by sunilsankar** [comment]
Sorry @ophub  I didn't understand .Looks like it rtl 8189ES I think.

**Comment by ophub** [comment]
No drive

**Comment by sunilsankar** [comment]
How do I install kernel header

**Comment by ophub** [comment]
The header has been installed in /usr/src
