### ISSUE TITLE
About kernel name

### ISSUE THREAD

**Issue by xtoys** [ophub/amlogic-s9xxx-armbian#82]
已有 `5.15.xx` 表示内核版本
遂建议将内核名 `5.15.xx-flippy-xx+`  中的 `-xx+` 移除掉

**Comment by ophub** [comment]
内核库里的文件有flippy编译分享，我转存使用。在armbian和OpenWrt里使用的统一内核。

这个命名格式是他的习惯，在社群里很多人习惯了叫69+o，69+。

**Comment by JFLim1** [comment]
Hi @ophub 
Out of curiousity is there a difference between kernel 5.15.15-flippy-69+ and kernel-5.15.15-meson64 (which Armbian uses for Amlogic SOCs)? Is linux-image-edge-meson64 (the latest is 5.15.15-meson64) compatible with Armbian_Aml_s922X image?

**Comment by ophub** [comment]
`5.15.15-meson64` is officially compiled by armbian using the standard kernel of kernel.org

`5.15.15-flippy-69+` is [compiled use unifreq/linux-5.15.y](https://github.com/unifreq/linux-5.15.y) and shared by `flippy`, and has done a lot of optimizations for the `amlogic box`.

`5.15.15-meson64-dev` is [compiled use unifreq/linux-5.15.y](https://github.com/unifreq/linux-5.15.y) by me and used for development and testing. I also use the kernel source code of `flippy`. To distinguish, just named differently.
