### ISSUE TITLE
CM311-1a-YST [drm] kms: can't enable cloning when we probably wanted to.

### ISSUE THREAD

**Issue by ruanima** [ophub/amlogic-s9xxx-armbian#820]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [CM311-1a-YST]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.82]
 - Release: [Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.82_server_2022.12.12.img]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.

初始化配置的时候，系统非常卡顿，屏幕显示缩放比例不正常（概率性黑屏），显示器是4k分辨率。

似乎跟显存大小设置有关？参考 https://whycan.com/p_71914.html

错误信息
` ` ` 
[drm] kms: can't enable cloning when we probably wanted to.
` ` `

![image](https://user-images.githubusercontent.com/14031394/207641888-a248efaa-b662-4bce-abaf-a28c8093c9d0.png)

**Comment by ophub** [comment]
调底点

**Comment by ruanima** [comment]
> 调底点

咋调

**Comment by ophub** [comment]
change-display 1
