### ISSUE TITLE
软件库自带的部分软件，比如说Firefox必须在安装desktop的条件下使用吗

### ISSUE THREAD

**Issue by Andy2025** [ophub/amlogic-s9xxx-armbian#821]
软件库自带的部分软件，比如说Firefox必须在安装desktop的条件下使用吗？不知道怎么使用，求解

**Comment by ophub** [comment]
对，软件中心有3类，1xx是docker系列，2xx是桌面软件系列（必须要先201安装桌面），3xx是系统服务系列。

**Comment by Andy2025** [comment]
我安装201，系统自动附带安装了211,215。我卸载掉201之后，然后卸载211，215，多次卸载不掉，求解

**Comment by ophub** [comment]
可以在文件里找到各序号安装的软件包，对应的卸载即可。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/usr/share/ophub/armbian-software/command-desktop.sh

sudo apt-get update
sudo apt-get remove -y evolution gedit

**Comment by Andy2025** [comment]
211   Evolution                 installed       update/remove
212   Gwenview                  not-installed   install     
213   Eog                       not-installed   install     
214   VisualStudioCode          not-installed   install     
215   Gedit                     installed       update/remove


root@armbian:~# sudo apt-get remove -y evolution gedit
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package 'gedit' is not installed, so not removed
Package 'evolution' is not installed, so not removed
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
软件列表里面显示已安装，但是卸载的时候显示未安装

**Comment by ophub** [comment]
`cat /etc/ophub-release`

发一下你上面反回的系统信息

**Comment by Andy2025** [comment]
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905d'
FDTFILE='meson-gxl-s905d-phicomm-n1.dtb'
UBOOT_OVERLOAD='u-boot-n1.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
ANDROID_UBOOT='/usr/lib/u-boot/u-boot-2015-phicomm-n1.bin'
FAMILY='meson-gxl'
BOARD='s905d'
KERNEL_VERSION='5.15.78'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='usb'
AMPART_STATUS='no'
PACKAGED_DATE='2022-11-11'

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/761

你按照这个方法同步到最新版本在看下。

**Comment by Andy2025** [comment]
root@armbian:~# wget https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync -O /usr/sbin/armbian-sync
--2022-12-15 15:42:02--  https://raw.githubusercontent.com/ophub/amlogic-s9xxx-armbian/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-sync
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 0.0.0.0, ::
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|0.0.0.0|:443... failed: Connection refused.
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|::|:443... failed: Connection refused.

**Comment by Andy2025** [comment]
问题同样存在

**Comment by Andy2025** [comment]
cat /etc/ophub-release
出来的信息和上面的一样，不知道是不是没同步更新成功
root@armbian:~# armbian-sync                                [ INFO ] Armbian PLATFORM: [ amlogic ]                      [ STEPS ] Start syncing all service scripts...              [ STEPS ] Start syncing operation instruction and service script...
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/common-files/usr/sbin'
svn: E120108: Error running context: The server unexpectedly closed the connection.
[ STEPS ] Start syncing software service script...
在第2步的时候的时候好像出现问题

**Comment by ophub** [comment]
你的盒子的网络访问github不通

**Comment by Andy2025** [comment]
root@armbian:~# armbian-sync [ INFO ] Armbian PLATFORM: [ amlogic ] [ STEPS ] Start syncing all service scripts... [ STEPS ] Start syncing operation instruction and service script...
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/common-files/usr/sbin'
svn: E120108: Error running context: The server unexpectedly closed the connection.
[ STEPS ] Start syncing software service script...

第1步挂了代理进去了，第2步那上面链接是404啊

**Comment by ophub** [comment]
这是网络不通的问题

**Comment by Andy2025** [comment]
怎么解决？求解，从网络下手机电脑都能够访问gh
