### ISSUE TITLE
Is this wifi card supported

### ISSUE THREAD

**Issue by sunilsankar** [ophub/amlogic-s9xxx-armbian#822]
![WhatsApp Image 2022-12-14 at 3 42 07 PM (1)](https://user-images.githubusercontent.com/2275957/207852722-11060ea6-4575-4104-a112-765f6d3ff1f0.jpeg)

**Comment by ophub** [comment]
no driver

**Comment by sunilsankar** [comment]
Any usb wifi dongle that supports s905l2 box. I can purchase since I running out of ethernet ports and looking for wifi options. Keep up the good work .

**Comment by ophub** [comment]
mt7610u

**Comment by sunilsankar** [comment]
Thanks @ophub
