### ISSUE TITLE
CM311-1a YS 选择305 网卡依然无法自动上网

### ISSUE THREAD

**Issue by jiaxinonly** [ophub/amlogic-s9xxx-armbian#823]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model [CM311-1a YS(M)]

**Armbian Version | 系统版本**
 - Kernel Version: [6.0.12]
 - Release: [jammy]

**Describe the bug | 问题描述**
这是我的机器信息：
![IMG_20221215_221339](https://user-images.githubusercontent.com/57223696/207883466-b25ae7d1-7b1f-44dc-b904-6dff1ae31f46.jpg)

我安装了12月12日最新的jammy
Armbian_23.02.0_amlogic_s905l3a_jammy_6.0.12_server_2022.12.12.img.gz

安装时选择了305，结果无法识别网卡，提示armbain cannot attach tp phy
最后参考了#772

手动上传了meson-g12a-s905l3a-e900v22c-100m.dtb，并修改/boot/uEnv.txt文件才恢复正常，看 #772的回复，安装选择305应该已经自动解决了，并且我在/boot/dtb/amlogic目录下也发现了meson-g12a-s905l3a-cm311.dtb，是否在制作时保存错了文件？
![image](https://user-images.githubusercontent.com/57223696/207885207-81f309c2-fd88-4860-aa37-eb5b2ab1b432.png)

![image](https://user-images.githubusercontent.com/57223696/207885368-7fe34925-ebf9-4da2-be4d-a4b994166c3a.png)

**Comment by janko888** [comment]
新的修复版等待合并发布中。
你可以先用这个dtb替换
https://github.com/ophub/amlogic-s9xxx-armbian/files/10226577/cm311-6.0.zip

**Comment by jiaxinonly** [comment]
多谢，这个dtb也没问题
