### ISSUE TITLE
ipv6 地址模式修改 ipv6.addr-gen-mode stable-privacy or eui64

### ISSUE THREAD

**Issue by DHinh** [ophub/amlogic-s9xxx-armbian#825]
如题，之前用别的开发板直接去/etc/NetworkManager/system-connections/ 目录中对应网卡的文件修改如下
 [ipv6]
#addr-gen-mode=stable-privacy
addr-gen-mode=eui64
dns-search=
然而cm311-1a刷了Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.82_server_2022.12.12 
找不到eth0的文件
nmcli con modify "eth0" ipv6.addr-gen-mode eui64也无法使用。
我自己查看了网络是由 NetworkManager 管理的但是不知道设置文件在哪里

**Comment by DHinh** [comment]
![5`XM K 84BDD_AT}`2GEJH2](https://user-images.githubusercontent.com/105959047/208019373-9b45346e-45a0-4829-a6f6-277433de07fb.png)

**Comment by DHinh** [comment]
有三种解决方案(注意:通常三种里面只有一种有效)
更改sysctl.conf里的内容
net.ipv6.conf.default.addr_gen_mode = 0
net.ipv6.conf.eth0.addr_gen_mode = 0

更改dhcpcd.conf里的内容
slaac hwaddr

从networkmanager中修改
sudo vim /etc/NetworkManager/system-connections/"你的连接名称"
addr-gen-mode=eui64
————————————————
都没有用。不知道咋整了

**Comment by livelier** [comment]
`cat /etc/ophub-release`

发一下返回页面

**Comment by DHinh** [comment]
> `cat /etc/ophub-release`
> 
> 发一下返回页面


root@S905L3A:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905l3a'
MODEL_NAME='E900V22C-D'
FDTFILE='meson-g12a-s905l3a-cm311.dtb'
UBOOT_OVERLOAD='u-boot-e900v22c.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
FAMILY='meson-g12a'
BOARD='s905l3a'
KERNEL_VERSION='5.15.82'
KERNEL_BRANCH='stable'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
MLUBOOT_STATUS='no'
AMPART_STATUS='yes'
PACKAGED_DATE='2022-12-12'

**Comment by livelier** [comment]
`nmcli connection show`
看一下你的网卡名字

**Comment by DHinh** [comment]
> `nmcli connection show` 看一下你的网卡名字

![OZZ3)FVF9K)R4$HAJBH8782](https://user-images.githubusercontent.com/105959047/208023368-5ab3d71d-e029-4ee0-9f80-da711c18047f.png)

**Comment by DHinh** [comment]
> `nmcli connection show` 看一下你的网卡名字

这个Ifupdown根本找不到
find / -name Ifupdown
![GJ}K7}VZ@H8T IVSD%0J)0T](https://user-images.githubusercontent.com/105959047/208023501-3d8f5c10-b4a5-4737-be37-d935d023df2f.png)

**Comment by livelier** [comment]
`ls /etc/NetworkManager/system-connections/ -al`

**Comment by DHinh** [comment]
> `ls /etc/NetworkManager/system-connections/ -al`


> `ls /etc/NetworkManager/system-connections/ -al`

文件夹里是空的
![image](https://user-images.githubusercontent.com/105959047/208024222-a22c6645-5e53-466c-ad33-50fd1ef9f57f.png)

**Comment by livelier** [comment]
了解了，你新建一个就可以了。这个Ifupdown是手动设置前默认的。

**Comment by DHinh** [comment]
> 

新建一个Ifupdown.nmconnection？里面的文本怎么写？用别的现成的行吗？
这是另一个有wifi的配置。cm311没wifi我不知道怎么写eth0的
[connection]
id=Plus-2.4G
uuid=977400fc-dfb4-48e4-affb-e02532758f41
type=wifi
permissions=

[wifi]
mac-address=*********
mac-address-blacklist=
mode=infrastructure
ssid=Plus-2.4G

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=*********

[ipv4]
dns-search=
method=auto

[ipv6]
#addr-gen-mode=stable-privacy
addr-gen-mode=eui64
dns-search=
method=auto

**Comment by DHinh** [comment]
> 了解了，你新建一个就可以了。这个Ifupdown是手动设置前默认的。

新建一个Ifupdown.nmconnection？里面的文本怎么写？用别的现成的行吗？
这是另一个有wifi的配置。cm311没wifi我不知道怎么写eth0的
[connection]
id=Plus-2.4G
uuid=977400fc-dfb4-48e4-affb-e02532758f41
type=wifi
permissions=

[wifi]
mac-address=*********
mac-address-blacklist=
mode=infrastructure
ssid=Plus-2.4G

[wifi-security]
auth-alg=open
key-mgmt=wpa-psk
psk=*********

[ipv4]
dns-search=
method=auto

[ipv6]
#addr-gen-mode=stable-privacy
addr-gen-mode=eui64
dns-search=
method=auto

**Comment by livelier** [comment]
不是这样，你等下午我用电脑发你，这个github的app版我还不太会用。eth是以太网卡，你要定义为无线网卡？

**Comment by DHinh** [comment]
> 不是这样，你等下午我用电脑发你，这个github的app版我还不太会用。eth是以太网卡，你要定义为无线网卡？

不是。上面我是复制的有wifi的那个盒子的文件里的内容，我想改成cm311能用的。cm311没有wifi 我不知道怎么写eth0的内容

**Comment by DHinh** [comment]
> 有思路是好的，但是这个方法，实际 ethx 不存在的时候，理论上是不可以的。

我的目的就只是想把ipv6改成eui-64

**Comment by DHinh** [comment]
> 把已知网卡ipv6地址生成模式改为eui64，知道你的目的。

现在问题就是找不到在哪改这个eth0

**Comment by livelier** [comment]
![image](https://user-images.githubusercontent.com/104582100/208027249-3f51bb2f-8461-46f9-98c0-de566670ab76.png)

**Comment by DHinh** [comment]
> 把已知网卡ipv6地址生成模式改为eui64，知道你的目的。

我试着自己加了eth0 没有用
[connection]
id=eth0
uuid=681b428f-beaf-8932-dce4-687ed5bae28e
type=ethernet
autoconnect=false
interface-name=eth0
permissions=
timestamp=1671173837

[ethernet]
cloned-mac-address=9E:61:E8:DE:C9:AA
mac-address=
mac-address-blacklist=

[ipv4]
address1=192.168.123.108/24,192.168.123.1
dns=192.168.123.1;
dns-priority=100
dns-search=
method=manual

[ipv6]
#addr-gen-mode=stable-privacy
addr-gen-mode=eui64
dns-priority=100
dns-search=
method=auto

![image](https://user-images.githubusercontent.com/105959047/208048620-1ce48395-7d61-4394-96bc-b14463c0c143.png)

**Comment by livelier** [comment]
变量内容根据需要自行修改一下，执行后立即生效。如果 ssh 断开，查看新的 host ip 重新 ssh 连接即可。

新增以太网卡连接设置
新增: `eth0 连接`
ipv6 地址模式: `eui64` 
ipv4 / ipv6 连接模式: `DHCP 获取动态 IP 地址`

```
# Set ENV
MYCONN=eth0         # custom connect name
IPV6AGM=eui64       # gen-mode=stable-privacy or eui64

# Add ETH
nmcli connection add \
con-name $MYCONN \
type ethernet \
ifname eth0 \
autoconnect yes \
ipv6.addr-gen-mode $IPV6AGM
nmcli connection up $MYCONN
```

新增无线网卡连接设置
新增: `wlan0 连接`
ipv6 地址模式: `eui64` 
ipv4 / ipv6 连接模式: `DHCP 获取动态 IP 地址`

```
# Set ENV
MYCONN=wlan0        # custom connect name
MYSSID=ssid         # wifi ssid
MYPSWD=passwd       # wifi password
MYWSKM=wpa-psk      # wpa-wpa2=wpa-psk or wpa3=sae
IPV6AGM=eui64       # gen-mode=stable-privacy or eui64

# Add WLAN
nmcli connection add \
con-name $MYCONN \
type wifi \
ifname wlan0 \
autoconnect yes \
ipv6.addr-gen-mode $IPV6AGM \
wifi.ssid $MYSSID \
wifi-sec.key-mgmt $MYWSKM \
wifi-sec.psk $MYPSWD
nmcli connection up $MYCONN
```

**Comment by livelier** [comment]
把帖子标题修改一下： ipv6 地址模式修改 ipv6.addr-gen-mode stable-privacy or eui64

**Comment by fu-r** [comment]
> 变量内容根据需要自行修改一下，执行后立即生效。如果 ssh 断开，查看新的 host ip 重新 ssh 连接即可。
> 
> 新增以太网卡连接设置 新增: `eth0 连接` ipv6 地址模式: `eui64` ipv4 / ipv6 连接模式: `DHCP 获取动态 IP 地址`
> 
> ```
> # Set ENV
> MYCONN=eth0         # custom connect name
> IPV6AGM=eui64       # gen-mode=stable-privacy or eui64
> 
> # Add ETH
> nmcli connection add \
> con-name $MYCONN \
> type ethernet \
> ifname eth0 \
> autoconnect yes \
> ipv6.addr-gen-mode $IPV6AGM
> nmcli connection up $MYCONN
> ```
> 
> 新增无线网卡连接设置 新增: `wlan0 连接` ipv6 地址模式: `eui64` ipv4 / ipv6 连接模式: `DHCP 获取动态 IP 地址`
> 
> ```
> # Set ENV
> MYCONN=wlan0        # custom connect name
> MYSSID=ssid         # wifi ssid
> MYPSWD=passwd       # wifi password
> MYWSKM=wpa-psk      # wpa-wpa2=wpa-psk or wpa3=sae
> IPV6AGM=eui64       # gen-mode=stable-privacy or eui64
> 
> # Add WLAN
> nmcli connection add \
> con-name $MYCONN \
> type wifi \
> ifname wlan0 \
> autoconnect yes \
> ipv6.addr-gen-mode $IPV6AGM \
> wifi.ssid $MYSSID \
> wifi-sec.key-mgmt $MYWSKM \
> wifi-sec.psk $MYPSWD
> nmcli connection up $MYCONN
> ```

执行后生效，但配置不能保存，reboot重启后失效，如何解决？

**Comment by BakaFT** [comment]
> > 变量内容根据需要自行修改一下，执行后立即生效。如果 ssh 断开，查看新的 host ip 重新 ssh 连接即可。
> > 新增以太网卡连接设置 新增: `eth0 连接` ipv6 地址模式: `eui64` ipv4 / ipv6 连接模式: `DHCP 获取动态 IP 地址`
> > ```
> > # Set ENV
> > MYCONN=eth0         # custom connect name
> > IPV6AGM=eui64       # gen-mode=stable-privacy or eui64
> > 
> > # Add ETH
> > nmcli connection add \
> > con-name $MYCONN \
> > type ethernet \
> > ifname eth0 \
> > autoconnect yes \
> > ipv6.addr-gen-mode $IPV6AGM
> > nmcli connection up $MYCONN
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 新增无线网卡连接设置 新增: `wlan0 连接` ipv6 地址模式: `eui64` ipv4 / ipv6 连接模式: `DHCP 获取动态 IP 地址`
> > ```
> > # Set ENV
> > MYCONN=wlan0        # custom connect name
> > MYSSID=ssid         # wifi ssid
> > MYPSWD=passwd       # wifi password
> > MYWSKM=wpa-psk      # wpa-wpa2=wpa-psk or wpa3=sae
> > IPV6AGM=eui64       # gen-mode=stable-privacy or eui64
> > 
> > # Add WLAN
> > nmcli connection add \
> > con-name $MYCONN \
> > type wifi \
> > ifname wlan0 \
> > autoconnect yes \
> > ipv6.addr-gen-mode $IPV6AGM \
> > wifi.ssid $MYSSID \
> > wifi-sec.key-mgmt $MYWSKM \
> > wifi-sec.psk $MYPSWD
> > nmcli connection up $MYCONN
> > ```
> 
> 执行后生效，但配置不能保存，reboot重启后失效，如何解决？

可以修改已经存在的连接属性

`nmcli con modify "连接名" ipv6.addr-gen-mode eui64`
