### ISSUE TITLE
请问章鱼星球已将CoreElec刷入emmc怎么刷这个armbian？

### ISSUE THREAD

**Issue by tjcfnerd** [ophub/amlogic-s9xxx-armbian#827]
我的是黑色章鱼星球，已经将CoreElec刷入emmc，无法从u盘或者sd卡启动了，尝试过更换bootloader无效，不知能否通过CoreElec的ssh来刷机

**Comment by ophub** [comment]
得刷回原来的安卓系统，才能刷armbian

https://github.com/ophub/kernel/releases/tag/tools 这里可以下章鱼安卓系统
