### ISSUE TITLE
系统打不开armbian-config这个命令

### ISSUE THREAD

**Issue by yangzhuang2333** [ophub/amlogic-s9xxx-armbian#828]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S0905l3a]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

打不开armbian-config这个命令，我现在闹不明白了到底是网络问题，如果网络问题，装软件也没事。

**Comment by yangzhuang2333** [comment]
这是截图

**Comment by yangzhuang2333** [comment]
![Screenshot_2022-12-16-16-08-00-872_com sonelli juicessh](https://user-images.githubusercontent.com/119402649/208053349-979e0064-6fd5-4b48-b253-1cf10ebe1236.jpg)

**Comment by ophub** [comment]
这个功能使用时要访问github.com
打开的速度取决于你访问这个网站的速度。如果你的盒子不能正常访问这个网，其他软件的更新使用也无法正常使用。
换源不能解决问题，清华、阿里云等镜像我都测试过，很多软件包都没有，之前几个问答里也有人反馈过，换回默认源安装软件包才正常。

所以只有一个稳妥的解决办法就是改善网络。

**Comment by yangzhuang2333** [comment]
关键是我用apt命令装软件 装docker也都很快呀，郁闷了

**Comment by ophub** [comment]
apt是从ubuntu/debian下载的，不是github

docker是从docker.com，也不是github

你ping github.com
或者armbian-sync

**Comment by ophub** [comment]
你执行armbian-sync应该会报svn错误

**Comment by yangzhuang2333** [comment]
![Screenshot_2022-12-16-17-04-23-314_com sonelli juicessh](https://user-images.githubusercontent.com/119402649/208062624-7287a01f-a0d1-4bbf-9966-5144ea8e8f97.jpg)

**Comment by yangzhuang2333** [comment]
你说的对，有时候装软件列表里的软件要等很长时间，但是能装，这个armbian-config就不行  我等过很久，也可能是运气问题

**Comment by ophub** [comment]
这个网就是这么飘忽不定，有时极快，有时打不开

**Comment by livelier** [comment]
是的，在国内标准网络环境下，github 上一秒可以正常访问，下一秒请求超时。。。

**Comment by yangzhuang2333** [comment]
一百回总要成功几回呀，我就没成功

**Comment by livelier** [comment]
送你个临时解决方法，但这个方法也有偶发“转羊”的情况。

```
sudo sed -i 's/http:\/\/github.com/https:\/\/www.baidu.com/g' /usr/sbin/armbian-config
```

**Comment by yangzhuang2333** [comment]
我在毕站看见这个了，试了没用

**Comment by yangzhuang2333** [comment]
但是刚刚成功了  我滴神

**Comment by livelier** [comment]
这个方法仅仅是解决打开 armbian-config 响应慢或打不开的问题。

只有返回是 0 或 非0 才会有下一步的响应。是 0 打开 armbian-config, 非0 退出并发出警告。

```
Warning: Configuration cannot work properly without a working internet connection.
Press CTRL C to stop or any key to ignore and continue.
```
测试中发现
baidu 立即返回 0
github 有时立刻返回0 有时卡光标没有返回结果(网络环境不同卡多久不固定)。

![image](https://user-images.githubusercontent.com/104582100/208069934-b6833fa3-b378-495a-8e38-bdfca16ac8f3.png)

**Comment by OPMonday** [comment]
![ooo](https://user-images.githubusercontent.com/105340869/208119764-32a16ca4-7d09-426c-a1be-202a72fc293e.png)
确实，我的github.com所有的请求都用adguard home进行污染过滤后才访问的 IP完全没有问题。但是，我有时候部分GitHub.com请求会被中**动在香港的某数据中心劫持到一个无效域名。
可是有的时候，却不拦截，真搞不明白，这玩意的拦截机制到底是什么
