### ISSUE TITLE
请教一个关于Actions的问题。

### ISSUE THREAD

**Issue by Anywherexu** [ophub/amlogic-s9xxx-armbian#829]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905l3a]
 - Model [e.g. cm311-1a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.80]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
在使用Actions的时候，开始是会有这样的代码
_**[ o.k. ] Create example config file using template [ config-default.conf ]
[ o.k. ] Using config file [ /home/runner/work/amlogic-s9xxx-armbian/amlogic-s9xxx-armbian/build/userpatches/config-example.conf ]**_
请问这个conf是从哪里提取的？？？
是在[amlogic-s9xxx-armbian]/[compile-kernel]/[tools]/config/]这个文件夹下的配置文件吗？？？
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
https://docs.armbian.com/Developer-Guide_Build-Options/#hidden-options-for-advanced-users-default-values-are-marked-bold


这是armbian的标准流程，编译固件时可以自定义配置。如果有个性化定制需求就添加这个目录，用法见上面的文档。我没有添加，使用默认。这个ok表示此步骤已经正常执行完毕。

**Comment by Anywherexu** [comment]
> https://docs.armbian.com/Developer-Guide_Build-Options/#hidden-options-for-advanced-users-default-values-are-marked-bold
> 
> 这是armbian的标准流程，编译固件时可以自定义配置。如果有个性化定制需求就添加这个目录，用法见上面的文档。我没有添加，使用默认。这个ok表示此步骤已经正常执行完毕。

那我在compile-kernel/tools/config里面更改配置文件该如何生效？是我build armbian时就会生效，还是说在compile the kernel时生效？还是说需要在哪个脚本改参数才能生效？
编译了好几次，功能都没有成功。希望可以指导一下。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md

这个是内核的模版，自动根据版本匹配。你看一下编译内核的文档说明。

**Comment by Anywherexu** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md
> 
> 这个是内核的模版，自动根据版本匹配。你看一下编译内核的文档说明。

感谢您的耐心回复。是我阅读不认真。感谢

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md#github-action-输入参数说明


| 参数               | 默认值            | 说明                                                      |
|-------------------|------------------|-----------------------------------------------------------|
| kernel_config     | 无               | 默认使用 [tools/config](tools/config) 目录下的配置模板。你可以设置编译内核的配置文件在你仓库中的存放目录，如 `kernel/config_path` 。该目录下存储的配置模板必须以内核的主版本命名，如`config-5.10`、`config-5.15`等。 |

**Comment by yunzimo** [comment]
> > https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md
> > 这个是内核的模版，自动根据版本匹配。你看一下编译内核的文档说明。
> 
> 感谢您的耐心回复。是我阅读不认真。感谢

请教一下，如果是采用github编译的话，是要fork这个amlogic-s9xxx-armbian库，然后修改`compile-kernel/tools/config`这个里的配置，修改完之后，比如要编译5.10的内核，就相应的改config下的config-5.10，然后在action里编译就行了，是这意思么。

**Comment by yunzimo** [comment]
或者说，我自己新建一个目录，把这些模板文件修改后扔进去，然后kernel_config指向这个目录就行了是吧。

**Comment by ophub** [comment]
也许你看这个仓库迷糊。不如看这个 https://github.com/ophub/kernel
你复制这个，把config覆盖成你的，在线Actions编译即可。可以不用管这个armbian仓库的事情。只要把kernel里的config替换了，就点编译即可。

**Comment by yunzimo** [comment]
> 你上面理解正确，也许你看armbian这个仓库迷糊。不如看这个 https://github.com/ophub/kernel 你fork这个，把config覆盖成你的，在线Actions编译即可。可以不用管这个armbian仓库的事情。只要把kernel里的config替换了，就点编译即可。

感谢指导，我最终成功添加了kernel的配置，并最终编译成功。非常感谢。
但我在复制模板后通过make menuconfig修改保存后，发现与原来的模板相差很多。这让我非常迷惑。
![2023-06-22T21_30_11](https://github.com/ophub/amlogic-s9xxx-armbian/assets/45143713/2ff58ac3-1b70-4244-93b8-2bc2d720fbfa)
如图，我尝试在make menuconfig中load了`.config`文件后还是一样的结果，为了让和模板相近（不知道这些修改会导致什么结果），我直接把应该添加的内容（make menuconfig中选中的部分）添加到了模板当中。放弃了make menuconfig生成的版本。

**Comment by ophub** [comment]
仓库的config是x86_64的，如果在armbian或者其他arm64下使用时有差异，可忽略使用默认。

**Comment by yunzimo** [comment]
> 你的方法可以。
> 
> 你的差异是系统和gcc版本不同的结果，你使用了debian gcc10。而仓库的config是ubuntu22.04(x86_64)的，使用gcc12。可以忽视工具链的差异。
> 
> 你放弃了，编译时也会diff config自动修正了。你可以看一下编译完成的内核打包文件的内容：boot-xxx.tar.gz/config-xxx，这个文件就是最终的模板，把这个复制到tool/config/config-xxx覆盖同名文件，以后就可以直接用了

原来是这样，非常感谢您让我自己也学习了如何编译kernel
