### ISSUE TITLE
[X96 max plus]  2GB instead of 4GB and unable to boot from emmc

### ISSUE THREAD

**Issue by dvinz** [ophub/amlogic-s9xxx-armbian#830]
Hello,

**Device Information
 - SOC: S095x3 or S095x3-B ?
I test s905x3 img but S095x3-B is more stable whit my hardare.
that's why I think it's a S095x3-B
![cpu](https://user-images.githubusercontent.com/13184309/208236666-bdddb892-905f-4069-982d-5fdf2e860513.jpg)

 - Model : X96 max plus, android system info said "X96Max_plus2"
 ![syst_info](https://user-images.githubusercontent.com/13184309/208236581-bf6fa8b6-9d09-4aac-87ad-2720733f7231.jpg)

 - RAM 4Gb
 - LAN : Realtek RTL8211F 
 - WLAN	: Mediatek MT7661RSN
 - emmc : Sandisk chip
![emmc](https://user-images.githubusercontent.com/13184309/208238023-655bd651-9b29-4472-a3c1-6b412ef11847.jpg)

LAN, Wifi work with Armbian_23.02.0_amlogic_s905x3-b_jammy_6.0.13_server_2022.12.16.img.gz 
and meson-sm1-skyworth-lb2004-a4091.dtb

The board :
![IMG_20221216_143339](https://user-images.githubusercontent.com/13184309/208238153-da871cea-753e-4f25-9232-da780d7fc1fd.jpg)
![IMG_20221216_114710](https://user-images.githubusercontent.com/13184309/208238173-a932fbef-e705-4a62-81d2-70dc2db55c5a.jpg)

**Armbian Version 

```Shell
cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905x3'
MODEL_NAME='Tencent-Aurora-3Pro'
FDTFILE='meson-sm1-skyworth-lb2004-a4091.dtb'
UBOOT_OVERLOAD='u-boot-skyworth-lb2004.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/skyworth-lb2004-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/skyworth-lb2004-bootloader.img'
FAMILY='meson-sm1'
BOARD='s905x3-b'
KERNEL_VERSION='6.0.13'
KERNEL_BRANCH='stable'
K510='1'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='usb'
MLUBOOT_STATUS='no'
AMPART_STATUS='no'
PACKAGED_DATE='2022-12-16'
```

**Describe the bug

1. First issue, it show only 2 Gb of RAM instead of 4Gb

```Shell
root@192.168.169.159's password:
    _              _   ____  ___   ___  ____      _____
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|_  _|___ /
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \ \/ / |_ \
 / ___ \| | | | | | |  ___) \__, | |_| |___) >  < ___) |
/_/   \_\_| |_| |_|_| |____/  /_/ \___/|____/_/\_\____/

Welcome to Armbian 23.02.0-trunk Jammy with Linux 6.0.13-flippy-80+

System load:   12%           	Up time:       17 min
Memory usage:  7% of 1.90G  	IP:	       192.168.169.159
CPU temp:      47°C           	Usage of /:    85% of 2.4G
storage/:      49% of 252M   	storage temp:  23°C
RX today:      0 B
```

2. Seconde issue, emmc is recongniezd but after installing, on reboot I can't boot.

```Shell
ls /dev/mmcblk*
/dev/mmcblk2  /dev/mmcblk2boot0  /dev/mmcblk2boot1  /dev/mmcblk2rpmb
```

Thank for your help!

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/41be46f7de59a2ce1cd23000e3ccc011357cc056/build-armbian/armbian-files/common-files/etc/model_database.conf#L100

meson-sm1-x96-max-plus.dtb
u-boot-x96maxplus.bin

**Comment by dvinz** [comment]
With Armbian_23.02.0_amlogic_s905x3_jammy_6.0.13_server_2022.12.16.img.gz
and meson-sm1-x96-max-plus.dtb :

 - only 2 Gb of RAM instead of 4Gb
 - No Wifi
 - Lan OK
![test-IMG_20221217_132634](https://user-images.githubusercontent.com/13184309/208242098-4869f365-cd4b-4774-bc11-9d1a7603a800.jpg)

**Comment by ophub** [comment]
Try writing to emmc

**Comment by dvinz** [comment]
I have a black screen and bootloop while writing to emmc option 502

**Comment by ophub** [comment]
use 5.15 kernel

**Comment by dvinz** [comment]
With 5.15 kernel, it boot on emmc but :

RAM only 1Gb !!!! (821M)
No Wifi

I can solder the UART pins if it can help ?

```Shell
    _              _   ____  ___   ___  ____      _____
   / \   _ __ ___ | | / ___|/ _ \ / _ \| ___|_  _|___ /
  / _ \ | '_ ` _ \| | \___ \ (_) | | | |___ \ \/ / |_ \
 / ___ \| | | | | | |  ___) \__, | |_| |___) >  < ___) |
/_/   \_\_| |_| |_|_| |____/  /_/ \___/|____/_/\_\____/

Welcome to Armbian 23.02.0-trunk Jammy with Linux 5.15.83-flippy-80+o

System load:   13%           	Up time:       18 min
Memory usage:  18% of   821M   	IP:	       192.168.169.156
CPU temp:      49°C           	Usage of /:    7% of 29G
RX today:      33.2 KiB

[ General system configuration (beta): armbian-config ]

Last login: Sat Dec 17 18:22:59 2022
armbian:~:# free -h
               total        used        free      shared  buff/cache   available
Mem:           821Mi       145Mi       528Mi       9.0Mi       147Mi       595Mi
Swap:          410Mi          0B       410Mi
armbian:~:# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905x3'
MODEL_NAME='X96-Max+_100Mb'
FDTFILE='meson-sm1-x96-max-plus.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='5.15.83'
KERNEL_BRANCH='stable'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
MLUBOOT_STATUS='no'
AMPART_STATUS='yes'
PACKAGED_DATE='2022-12-16'
```

**Comment by ophub** [comment]
armbian-update -k 5.10.159
