### ISSUE TITLE
Updating issues on ARMBIAN

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#834]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: s912
 - Model X92

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.83-flippy-80+o
 - Release: Yammy 

**Describe the bug | 问题描述**
BUG 1

root@t1000:~# sudo armbian-sync
[ STEPS ] Start syncing all service scripts...
[ STEPS ] Start syncing operation instruction and service script...
svn: E170000: URL 'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/common-files/root              fs/usr/sbin' doesn't exist
[ STEPS ] Start syncing software service script...
svn: E170000: URL 'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/common-files/root              fs/usr/share/ophub' doesn't exist
[ STEPS ] Start syncing openvfd service script...
svn: E170000: URL 'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/common-files/root              fs/usr/share/openvfd' doesn't exist
[ SUCCESS ] All service scripts are synchronized successfully.

BUG 2
Setting up initramfs-tools (0.140ubuntu13.1) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for initramfs-tools (0.140ubuntu13.1) ...
ln: failed to create hard link '/boot/initrd.img-5.15.83-flippy-80+o.dpkg-bak' => '/boot/initrd.img-5.1              5.83-flippy-80+o': Operation not permitted
update-initramfs: Generating /boot/initrd.img-5.15.83-flippy-80+o

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/761
