### ISSUE TITLE
311-1a除了8822cs可以用其他的吗

### ISSUE THREAD

**Issue by 2020355** [ophub/amlogic-s9xxx-armbian#840]
o大 311-1a除了8822cs还有那些什么型号兼容性比较好 想内置~usb不看好 哈哈哈

**Comment by ophub** [comment]
8822cs兼容性没好过，能用的是运气，在x96max等盒子中，这个驱动有很多反馈不能用，但也有反馈很稳定，如果想试可以更新到老的内核如5.4试试运气，不能用就算了，无法改善

**Comment by 67389906** [comment]
那有没有其他WIFI芯片支持的呢

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/c4ab7329b19ce6f1302f544806eae3a82ab44069/compile-kernel/tools/config/config-5.15#L2992

内核里有驱动的都可以用
