### ISSUE TITLE
无线网络问题

### ISSUE THREAD

**Issue by cui8** [ophub/amlogic-s9xxx-armbian#841]
**感谢大佬**
真的很不好意思在打扰大佬您了，无线网络问题我向大佬请教了很多问题，每次大佬都耐心解答，感激不尽。
第一次玩机顶盒，希望大佬原谅我这个菜鸟，给大佬带来了很多麻烦。真的非常感谢。

**经历**
我第一次入手的机顶盒是cm311-1a，因无线问题买了3个网卡，无法解决，本人太菜了，到现在转转120买了n1，折腾了几天，刷了其支持无线的n1的armbian，但docker安装失败，换源等都不行，我无法解决了。现在重新玩cm311-1a想让他连接无线。

**cm311-1a连无线网**
大佬之前推荐的mt7601u网卡，我在京东，拼多多等无法找到，在转转上找到了360 wifi二代，需要9块钱+12元的运费，觉得不值。
**想问下大佬rtl8192cu的芯片能直接联网吗？**

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/c4ab7329b19ce6f1302f544806eae3a82ab44069/compile-kernel/tools/config/config-5.15#L2992

**Comment by cui8** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/c4ab7329b19ce6f1302f544806eae3a82ab44069/compile-kernel/tools/config/config-5.15#L2992

请大佬明示

**Comment by cui8** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/c4ab7329b19ce6f1302f544806eae3a82ab44069/compile-kernel/tools/config/config-5.15#L2992
> 
> 内核里有驱动的都可以用

太喜欢作者了，大爱作者，谢谢大佬，无以言表，非常感谢，帮了我大忙，如果没有大佬解答，我需要在各个群里询问，而一无所获。
