### ISSUE TITLE
X96 Max Plus Freeze Kernel Panic With "Unable to handle kernel paging request at virtual address" Error.

### ISSUE THREAD

**Issue by bulezas** [ophub/amlogic-s9xxx-armbian#844]
**Device Information**
 - SOC: S095x3
 - Model X96 Max Plus 4/32 GB + 1Gbps Eth.
 - RTL 8822 WIFI chip

**Armbian Version**
 - Kernel Version: 5.10.145 & 5.15.82
 - Release: Jammy

**Describe the bug**

After 1-2 hours of boot, the device completely freezes and goes into kernel panic mode with the error: `Unable to handle kernel paging request at virtual address...`

It was tested on multiple kernel versions with the same result.

Screenshot:

![image](https://i.imgur.com/EZYYEMF.jpg)

**Here's what I know:**

1. The device appears to function normally on boot and everything works fine such as USB ports, Gbps ethernet, WiFi, display, etc.
2. The device operates at normal temperature.
3. The device uses standard SanDisk eMMC & Micron memory chips.
4. Attempting to stress the device using tools such as `stress-ng --all 0` does not replicate the issue. I ran CPU, memory, I/O, and GPU stressors for hours and I couldn't replicate the issue. Oddly enough, the freeze occurred after I stopped the stressors.
5. The thing that accelerates the issue is opening a web browser on the GUI. Though the issue still happens on server-only installations.
6. On average, the freeze occurs in less than 12 hours. And much quicker if a browser such as firefox is launched, even headless `firefox -headless`, usually in 1-2 hours.

**Here's what I plan to do next:**

1. Run memtest to rule out any memory issues.
2. Try kernel 6+ to see if the issue still happens.
3. Run very specific stressors on specific parts of the OS/device to see if I can replicate the issue.

**Comment by ophub** [comment]
cat /etc/ophub-release

**Comment by bulezas** [comment]
Here is it currently running 5.10.145

```VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
FDTFILE='meson-sm1-x96-max-plus.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
ANDROID_UBOOT='/usr/lib/u-boot/hk1box-bootloader.img'
KERNEL_VERSION='5.10.145'
SOC='s905x3'
K510='1'
DISK_TYPE='emmc'
PACKAGED_DATE='2022-09-17'

**Comment by ophub** [comment]
There was a kernel panic phenomenon some time ago. Update to the latest kernel.
