### ISSUE TITLE
hk1的jammy版本 ，会掉IP，正在运行中，路由器后台突然显示已经离线。

### ISSUE THREAD

**Issue by 1520316653** [ophub/amlogic-s9xxx-armbian#845]
hk1的jammy版本 ，会掉IP，试了好几个版本了，正在运行中，路由器后台突然显示已经离线。
而且IP会来回跳，比如上一秒是192.168.68.134.下一秒就可能变成192.168.68.226，来回跳动，一般情况不跳。但是很容易掉ip.
而且docker里面的应用无法开启upnp。

**Comment by ophub** [comment]
路由器里dhcp设置mac地址绑定，分配固定ip

**Comment by 1520316653** [comment]
这个变IP好说，绑定一下就好了，主要是掉IP，运行中路由器后台突然显示已经离线。而且换过路由器，应该不是路由器的问题。

**Comment by ophub** [comment]
我想不到为什么会掉线，换根网线试试

**Comment by livelier** [comment]
网络配置方式，选择其中一种。不要启用两种或两种以上来管理网络， 该注释的注释掉该禁用的禁用掉。
UPnP 没效果的，在路由器上手动映射一下端口就好了。

你看我的docker 已经跑了40几个G的流量

![image](https://user-images.githubusercontent.com/104582100/208887947-1d2b45bf-f003-435d-9d1e-47e089de41c5.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/945471ea616f5c07eaec1923befe9d798d4771ea/rebuild#L694-L698

你屏幕上的黄色的广告可以禁了，最近发现此处多了一个广告，每周定时curl下载armbian的几条信息，随机显示。

**Comment by livelier** [comment]
我更改了禁用方式，已经提交，你看一下，哪一种更适合。

**Comment by 1520316653** [comment]
hk1依旧是在挂载外置硬盘会出现掉ip。换了一台设备hk1，一根网线和路由器都有这个问题。而且系统设置的固定IP和DHCP都尝试过了。
也试过了好几个系统版本了
应该是系统直接崩溃了，因为键盘的大小写灯不亮了。
挂的是240G的固态硬盘，功耗1瓦，用的绿联asm1153E芯片的硬盘盒。

**Comment by 1520316653** [comment]
两台hk1都有这个玄学问题。😭
