### ISSUE TITLE
写入emmc后，文件权限错误

### ISSUE THREAD

**Issue by 1248536814** [ophub/amlogic-s9xxx-armbian#846]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905L3A]
 - Model [M401A]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.83]
 - Release: [bullseye23.02.0]

**Describe the bug | 问题描述**
通过armbian-install写入emmc后，从/目录开始，文件所属为uid1023，/usr/bin下不能执行例如su，sudo，且无sid权限
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
U盘不要提前插入安卓，会被修改权限，在重启时再插入。
重新写U盘

**Comment by 1248536814** [comment]
多谢O大

**Comment by urenai** [comment]
使用各种手段(ttl  or  app  or....)，执行reboot update。
成功后重启，后断电。
插U盘，上电。

**Comment by LiuJiaMing-1024** [comment]
我也遇到这个问题了
chown -R root:root /
root用户执行这个命令可以批量修改所有文件权限
