### ISSUE TITLE
armbian-update

### ISSUE THREAD

**Issue by fachos** [ophub/amlogic-s9xxx-armbian#847]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x]
 - Model [e.g. X95PRO]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.83]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Hi.... 

yesterday i endup from bullseye to jammy for my box.... 
today trying "armbian-update" and  it force kernel update 
from 5.15.83 to 5.15.84.. now the box cant turn on.... even not listed
in my router.... i have copy again from sdcard to eMMC.. 
cant choose not to kernel upgrade?

**Comment by ophub** [comment]
The kernel will not be upgraded without executing this command.

**Comment by fachos** [comment]
hi...

normal type apt update && apt upgrade?
ok fine....

**Comment by ophub** [comment]
yes

**Comment by fachos** [comment]
thank you ophub

**Comment by ophub** [comment]
You should try that kernel update more often to see what happens during the process, it's rarely wrong. Updating the kernel is an important thing.

There is always a solution to a problem.

**Comment by fachos** [comment]
but my box dead after kernel update... what to do? im waiting new img file...

**Comment by ophub** [comment]
Maybe just can't reboot, you plug in the power again to start

**Comment by fachos** [comment]
did that before i start open issue here... turning back to bullseye see what gonna happen... will let you know
