### ISSUE TITLE
[OFF-TOPIC] Who is the maintainer? How can we donate?

### ISSUE THREAD

**Issue by bulezas** [ophub/amlogic-s9xxx-armbian#849]
Hi,

We use your work commercially and we would like to understand who is behind this project? We would also like to donate or find ways to be helpful to you.

Is this project ran by Amlogic? When I spoke to the Armbian team they said they don't know.

Thanks!

**Comment by ophub** [comment]
This project was created by me and maintained by a group of Armbian enthusiasts. We are not official Amlogic. The project can be freely used under the license of GPL-2.0.

What devices do you use the Armbian system on?

**Comment by bulezas** [comment]
I see. Thank you. We use multiple devices, mainly the S905X3-based ones.
