### ISSUE TITLE
创维E900V22c (22d)

### ISSUE THREAD

**Issue by zhupugeng** [ophub/amlogic-s9xxx-armbian#85]
广东爱家TV
CPU:S905L3A+b（实际上是S905x2）
实测U盘用S905x2 2g的dtb可运行EmuELEC、coreELEC，但是支持不太好。
想问问可否直接使用S905x2 的Armbian直接使用？写入EMMC分区表有没有影响

**Comment by zhupugeng** [comment]
> 广东爱家TV CPU:S905L3A+b（实际上是S905x2） 实测U盘用S905x2 2g的dtb可运行EmuELEC、coreELEC，但是支持不太好。 想问问可否直接使用S905x2 的Armbian直接使用？写入EMMC分区表有没有影响

**Comment by ophub** [comment]
如果有成熟的救砖方案，再尝试写入emmc。

**Comment by Calmact** [comment]
最近新上市的一批移动盒子S905L 3A-B、S905L 3A主控的，比如E900V22C/D，性能强悍，是原来S905X2的马甲，性能大概是X3的4/5，能够从u盘启动armbian，ee，ce这些系统，使用u200的dtb。e900v22c的Q群：320724049，诚邀@ophub大神来指导工作。

**Comment by ophub** [comment]
[meson-g12a-u200.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-dtb/meson-g12a-u200.dtb)

能使用5.10的内核吗？使用了哪个u-boot？
UBOOT_OVERLOAD="u-boot-x96max.bin"
MAINLINE_UBOOT="x96max-u-boot.bin.sd.bin"

**Comment by Calmact** [comment]
> 

就是这个[meson-g12a-u200.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/amlogic-dtb/meson-g12a-u200.dtb)，你加群了么大神？群里都等着你呢

**Comment by Calmact** [comment]
最新的几乎所有盒子都是这个配置，但是有些问题解决不了，你有空到群里看看？

**Comment by Calmact** [comment]
https://docs.qq.com/doc/DWFprWWxZa290VXNk
这是我在群上整理的E900V22C/D相关资料，armbian和OpenWRT是参考你的项目。

**Comment by Calmact** [comment]
个人QQ https://netcut.cn/mytemp-github

**Comment by ophub** [comment]
我的QQ登录不上去，很久没用了，等放学了我重新注册个。

**Comment by Calmact** [comment]
@ophub 欢迎欢迎

**Comment by ophub** [comment]
刚看了你的QQ文档，写的挺详细，这帮助了很多朋友熟悉设备和使用系统。
目前的soc列表里还没有S905L，我建议扩增这个分类，把你确定的设备列入，如果将来一些新增设备的用户大的，配置不同的还可以细分如s905l-xx / s905l-bb 等进行更细的针对性配置。

**Comment by Calmact** [comment]
> 

S905L和S905L3A是不一样的，L3A/L3AB根据群里猜测是使用了12nm新工艺的CPU，和S905L，S905L3不一样。目前国内新出的一大批中国移动运营商盒子目前都是采用这个方案，配合uwe5621ds的双频无线蓝牙芯片，性能强悍、市场保有量大，用户基础面广，很适合深入挖掘下，一起来群里讨论吧大佬 320724049

**Comment by ophub** [comment]
uwe5621ds的芯片在安卓TV里有驱动，我在kernel的源码里没找到这个对应的驱动，刚才问了下f大也没有。你如果在github上找到有人提供他的驱动，可以试试能不能和直线内核源码兼容

**Comment by Calmact** [comment]
https://github.com/Stane1983/uwe5621-aml
https://github.com/armbian/firmware/tree/master/uwe5621ds
在@armbian和@Stane1983仓库里有uwe5621ds的源码，群里@zzcand111尝试编译过没有成功，群里还有人将uwe5621模块换成rtl8822模块，可以搜索到wifi信号，查看过u200开发板的dts源码，里面没有wifi和蓝牙相关的部分，这个驱动编译以后，应该是需要对u200的dtb进行一定修改才行，目前进展就是这样。

**Comment by ophub** [comment]
刚才我找回QQ密码了，发现我已经在你们群里了，不知道什么时候加的。我上QQ的时候比较少，我的QQ上面基本上没朋友和我联系，以后我多参与你们群聊。

**Comment by ophub** [comment]
`find / -name *5621*`
/usr/lib/firmware/uwe5621ds

armbian源码里自带的这个，我搜了下找到了，wifi不能用吗？

![Snip20220228_1](https://user-images.githubusercontent.com/68696949/155950792-f7df23ea-c764-4fcc-b315-56fa70d5fe73.png)

**Comment by Calmact** [comment]
@zzcand111是群上的`烟花`，他测试过，你在群上发言问下？

**Comment by Calmact** [comment]
> `find / -name *5621*` /usr/lib/firmware/uwe5621ds
> 
> armbian源码里自带的这个，我搜了下找到了，wifi不能用吗？
> 
> ![Snip20220228_1](https://user-images.githubusercontent.com/68696949/155950792-f7df23ea-c764-4fcc-b315-56fa70d5fe73.png)

你发我个私信？我是群主

**Comment by ophub** [comment]
这个uwe5621-aml的驱动适合安卓，armbian使用不了。

**Comment by Calmact** [comment]
> 这个uwe5621-aml的驱动适合安卓，armbian使用不了。github上搜了下，3个驱动源码都是安卓的。
> 
> armbian的官方源码里带了uwe5621的固件，为什么会没有它的驱动呢？如果没有驱动，放进这个固件有什么用呢？难道这个固件可以使用主线内核里的其他驱动？

可能是其他平台的armbian用到了这个驱动，不一定是amlogic的，比如stm32/全志/海思？不知道

**Comment by Calmact** [comment]
> 这个uwe5621-aml的驱动适合安卓，armbian使用不了。github上搜了下，3个驱动源码都是安卓的。
> 
> armbian的官方源码里带了uwe5621的固件，为什么会没有它的驱动呢？如果没有驱动，放进这个固件有什么用呢？难道这个固件可以使用主线内核里的其他驱动？

如果要编译适配22c的dtb，应该怎么做？群里反编译了几个类似dtb，也找到了u200/x96Max的dts源码对比了下，目前还没人会弄。

**Comment by VMCoud** [comment]
> https://github.com/unifreq/linux-5.10.y/tree/main/arch/arm64/boot/dts/amlogic
> 
> 这是dtb的源码。如果有确切的修改方案，可以请f大在他5.4和5.15的源码里添加专用的dtb，以后直接使用他每周分享的内核即可，测试稳定的配制方案可以在安装脚本里新增一条专用方案，省得每次手工修改各处。我的openwrt和armbian 默认使用的都是他制作的内核。

你好  如何使用这个内核
