### ISSUE TITLE
H96 max x3 kernel panic and not work wifi/ethernet 

### ISSUE THREAD

**Issue by HelferP** [ophub/amlogic-s9xxx-armbian#850]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905x3]
 - Model [H96 max x3]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.84]

 - Release: [jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

The first download is good, but WiFi does not work, Ethernet does not receive the DHCP address. After rebooting, I get Kernel Panic and no longer loads. See Screen. I use boot-u-boot-x96maxplus.bin and dtb-meson-sm1-h96-max-x3.dtb
Armbian_23.02.0_amlogic_s905x3_jammy_5.15.84_server_2022.12.21.img.gz

![IMG_1932](https://user-images.githubusercontent.com/32640817/209173510-dfc604c2-5080-4cb2-8116-2619efad8f4c.jpg)
![IMG_1935](https://user-images.githubusercontent.com/32640817/209173523-7e6c3f6c-403a-4dde-8bab-23c68e55a136.jpg)
![IMG_1937](https://user-images.githubusercontent.com/32640817/209173534-180f21c4-5212-4333-b53e-9acc1cfe416d.jpg)
![IMG_1938](https://user-images.githubusercontent.com/32640817/209173545-04e20267-0024-4479-b081-af79ab1eb168.jpg)
![IMG_1950](https://user-images.githubusercontent.com/32640817/209173554-b62c9763-fcd9-4ae9-af78-7087b3a1cb50.jpg)
![IMG_1952](https://user-images.githubusercontent.com/32640817/209173566-6f9384cc-15bd-42ce-95dc-734b218c7c25.jpg)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-h96-max-x3.dts

jl2101 is support.
Try replacing the kernel with 5.4/5.10

**Comment by HelferP** [comment]
I re-downloaded the image to SD and replaced in two lines in meson-sm1-h96-max-x3.dtb see screenshot. After that, ethernet was able to get an IP from dhcp. Wi-Fi still does not work, it sees access points, but does not connect to them.

Saw this while uploading:
[   35.628811] meson-gx-mmc ffe03000.sd: unaligned sg len 552 blksize 512, disabling descriptor DMA for transfer

Reboot also causes kernel panic

https://paste.armbian.com/xasidukisu
![ff3f0000](https://user-images.githubusercontent.com/32640817/209331800-6b1795b5-2d4c-4a73-a70b-49da891d361c.PNG)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-h96-max-x3.dts

![Snip20221224_3](https://user-images.githubusercontent.com/68696949/209421752-3978544c-730b-4ed9-8fa1-959ddbd2c0fb.png)

You submit the changes to the upstream kernel source code, so that you can use the correct configuration in the future.

**Comment by HelferP** [comment]
![изображение](https://user-images.githubusercontent.com/32640817/209422423-328ac488-8529-4d8e-ab94-cfb939e13fa6.png)
Yes, but you still need to remove the line.
For example, you can take the code from HK1. I copied from there.
![изображение](https://user-images.githubusercontent.com/32640817/209422546-4ddb3178-b8fe-497a-892b-489f2c995785.png)
There are two problems left to solve:
1) kernel panic after reboot.
2) wifi

https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-hk1box-vontar-x3.dts
_>>What chip is your wifi._
HCY6355

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-sm1-h96-max-x3.dts#L274-L281

I see that there is support for your wifi in the source code.

Kernel panics are individual kernels, right? You can test 5.4/5.10/5.15/6.0.

Submit your changes to the upstream kernel source code, and submit all 4 kernel repositories.

**Comment by HelferP** [comment]
_>>I see that there is support for your wifi in the source code._
Yes, but for some reason it does not work correctly. Just like ethernet until I fixed the code.

_>>You can test 5.4/5.10/5.15/6.0._
I can, but I don't know where to get images with these kernels.

_>>Submit your changes to the upstream kernel source code, and submit all 4 kernel repositories._
I'm sorry, but I don't know how to do this.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian#update-armbian-kernel

https://github.com/ophub/kernel/tree/main/pub/stable

`armbian-update -k 5.4.228`

**Comment by ophub** [comment]
[meson-sm1-h96-max-x3-oc.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10298137/meson-sm1-h96-max-x3-oc.dtb.zip)

Download, decompress into dtb, overwrite the file with the same name in the /boot/dtb/amlogic directory, restart the test to see if it can start normally, and whether the wired network is normal.

**Comment by HelferP** [comment]
> meson-sm1-h96-max-x3-oc.dtb.zip

not work, only black screen.

**Comment by ophub** [comment]
No need, just replace dtb
I see that the modification result is the same as your feedback.

![Snip20221224_6](https://user-images.githubusercontent.com/68696949/209425937-5fd720a0-d9de-4c6b-80e9-ee414ae7a80a.png)

**Comment by HelferP** [comment]
> I see that the modification result is the same as your feedback.

Yes, but with this file it doesn't boot

**Comment by ophub** [comment]
this is 5.15.85 kernel dtb

**Comment by HelferP** [comment]
> try this is 5.15.85 kernel dtb

I tried updating the kernel to 5.15.85 and used this file. ethrnet works, wifi still can't connect to access point. After reboot also kernel panic.

Maybe some logs are needed to understand what could be the problem?

**Comment by ophub** [comment]
Update to 5.10/5.4 kernel, and upload this file, try other kernels to see if it works.

**Comment by ophub** [comment]
armbian-update -k 5.4.228

You update this kernel. When I submitted the dts modification just now, I found that this was correct before. Try this to see if there is a kernel panic.

**Comment by HelferP** [comment]
> armbian-update -k 5.4.228
> 
> You update this kernel. When I submitted the dts modification just now, I found that this was correct before. Try this to see if there is a kernel panic.

Yes, I checked, there is no kernel panic on this kernel. At least it has rebooted several times.
WiFi also can't get ip

**Comment by ophub** [comment]
Wired network is normal, use wired

**Comment by HelferP** [comment]
> Wired network is normal, use wired

Bluetooth also finds devices but does not connect to them.

There is no ethernet where I want to use it, only WiFi is possible.

**Comment by ophub** [comment]
You mean bluetooth is not working but wireless is working?

**Comment by HelferP** [comment]
> You mean bluetooth is not working but wireless is working?

WiFi and Bluetooh see other devices, but cannot connect to them.

**Comment by ophub** [comment]
Unable to connect to wireless network in `armbian-config`? Can't connect using commands? Show me what the error log says.

**Comment by ophub** [comment]
dmesg|grep brcm

**Comment by HelferP** [comment]
> Unable to connect to wireless network in `armbian-config`? Can't connect using commands? Show me what the error log says.


Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7434] device (wlan0): Activation: starting connection 'HOMEWIFI' (e077d37d-dbc9-4fda-8c5f-463f7465f536)
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7443] audit: op="connection-add-activate" uuid="e077d37d-dbc9-4fda-8c5f-463f7465f536" name="HOMEWIFI" pid=2255 uid=0 result="success"
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7469] device (wlan0): state change: disconnected -> prepare (reason 'none', sys-iface-state: 'managed')
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7487] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7499] device (wlan0): Activation: (wifi) access point 'HOMEWIFI' has security, but secrets are required.
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7500] device (wlan0): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed')
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7549] device (wlan0): state change: need-auth -> prepare (reason 'none', sys-iface-state: 'managed')
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7561] device (wlan0): state change: prepare -> config (reason 'none', sys-iface-state: 'managed')
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7580] device (wlan0): Activation: (wifi) connection 'HOMEWIFI' has security, and secrets exist.  No new secrets needed.
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7775] Config: added 'ssid' value 'HOMEWIFI'
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7776] Config: added 'scan_ssid' value '1'
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7777] Config: added 'bgscan' value 'simple:30:-70:86400'
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7777] Config: added 'key_mgmt' value 'WPA-PSK WPA-PSK-SHA256 FT-PSK'
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7778] Config: added 'auth_alg' value 'OPEN'
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.7778] Config: added 'psk' value '<hidden>'
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.8618] device (wlan0): supplicant interface state: disconnected -> scanning
Dec 24 20:50:38 armbian NetworkManager[847]: <info>  [1671889838.8620] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> scanning
Dec 24 20:50:41 armbian wpa_supplicant[904]: wlan0: Trying to associate with SSID 'HOMEWIFI'
Dec 24 20:50:41 armbian NetworkManager[847]: <info>  [1671889841.7096] device (wlan0): supplicant interface state: scanning -> associating
Dec 24 20:50:41 armbian NetworkManager[847]: <info>  [1671889841.7097] device (p2p-dev-wlan0): supplicant management interface state: scanning -> associating
Dec 24 20:50:44 armbian wpa_supplicant[904]: wlan0: CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16
Dec 24 20:50:44 armbian NetworkManager[847]: <info>  [1671889844.4310] device (wlan0): supplicant interface state: associating -> disconnected
Dec 24 20:50:44 armbian NetworkManager[847]: <info>  [1671889844.4312] device (p2p-dev-wlan0): supplicant management interface state: associating -> disconnected
Dec 24 20:50:44 armbian NetworkManager[847]: <info>  [1671889844.5357] device (wlan0): supplicant interface state: disconnected -> scanning
Dec 24 20:50:44 armbian NetworkManager[847]: <info>  [1671889844.5358] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> scanning
Dec 24 20:50:47 armbian wpa_supplicant[904]: wlan0: Trying to associate with SSID 'HOMEWIFI'
Dec 24 20:50:47 armbian NetworkManager[847]: <info>  [1671889847.2858] device (wlan0): supplicant interface state: scanning -> associating
Dec 24 20:50:47 armbian NetworkManager[847]: <info>  [1671889847.2860] device (p2p-dev-wlan0): supplicant management interface state: scanning -> associating
Dec 24 20:50:49 armbian wpa_supplicant[904]: wlan0: CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16
Dec 24 20:50:49 armbian NetworkManager[847]: <info>  [1671889849.9508] device (wlan0): supplicant interface state: associating -> disconnected
Dec 24 20:50:49 armbian NetworkManager[847]: <info>  [1671889849.9510] device (p2p-dev-wlan0): supplicant management interface state: associating -> disconnected
Dec 24 20:50:50 armbian NetworkManager[847]: <info>  [1671889850.4456] device (wlan0): supplicant interface state: disconnected -> scanning
Dec 24 20:50:50 armbian NetworkManager[847]: <info>  [1671889850.4457] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> scanning
Dec 24 20:50:53 armbian wpa_supplicant[904]: wlan0: Trying to associate with SSID 'HOMEWIFI'
Dec 24 20:50:53 armbian NetworkManager[847]: <info>  [1671889853.2191] device (wlan0): supplicant interface state: scanning -> associating
Dec 24 20:50:53 armbian NetworkManager[847]: <info>  [1671889853.2193] device (p2p-dev-wlan0): supplicant management interface state: scanning -> associating
Dec 24 20:50:55 armbian wpa_supplicant[904]: wlan0: CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16
Dec 24 20:50:55 armbian NetworkManager[847]: <info>  [1671889855.8909] device (wlan0): supplicant interface state: associating -> disconnected
Dec 24 20:50:55 armbian NetworkManager[847]: <info>  [1671889855.8910] device (p2p-dev-wlan0): supplicant management interface state: associating -> disconnected
Dec 24 20:50:56 armbian NetworkManager[847]: <info>  [1671889856.9488] device (wlan0): supplicant interface state: disconnected -> scanning
Dec 24 20:50:56 armbian NetworkManager[847]: <info>  [1671889856.9489] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> scanning
Dec 24 20:50:59 armbian wpa_supplicant[904]: wlan0: Trying to associate with SSID 'HOMEWIFI'
Dec 24 20:50:59 armbian NetworkManager[847]: <info>  [1671889859.6681] device (wlan0): supplicant interface state: scanning -> associating
Dec 24 20:50:59 armbian NetworkManager[847]: <info>  [1671889859.6682] device (p2p-dev-wlan0): supplicant management interface state: scanning -> associating
Dec 24 20:51:02 armbian wpa_supplicant[904]: wlan0: CTRL-EVENT-ASSOC-REJECT bssid=00:00:00:00:00:00 status_code=16
Dec 24 20:51:02 armbian wpa_supplicant[904]: wlan0: CTRL-EVENT-SSID-TEMP-DISABLED id=0 ssid="HOMEWIFI" auth_failures=1 duration=10 reason=CONN_FAILED
Dec 24 20:51:02 armbian NetworkManager[847]: <info>  [1671889862.3476] device (wlan0): supplicant interface state: associating -> disconnected
Dec 24 20:51:02 armbian NetworkManager[847]: <info>  [1671889862.3478] device (p2p-dev-wlan0): supplicant management interface state: associating -> disconnected
Dec 24 20:51:03 armbian NetworkManager[847]: <warn>  [1671889863.9291] device (wlan0): Activation: (wifi) association took too long
Dec 24 20:51:03 armbian NetworkManager[847]: <info>  [1671889863.9292] device (wlan0): state change: config -> need-auth (reason 'none', sys-iface-state: 'managed')
Dec 24 20:51:03 armbian NetworkManager[847]: <warn>  [1671889863.9308] device (wlan0): Activation: (wifi) asking for new secrets
Dec 24 20:51:03 armbian NetworkManager[847]: <warn>  [1671889863.9320] device (wlan0): no secrets: No agents were available for this request.
Dec 24 20:51:03 armbian NetworkManager[847]: <info>  [1671889863.9322] device (wlan0): state change: need-auth -> failed (reason 'no-secrets', sys-iface-state: 'managed')
Dec 24 20:51:03 armbian NetworkManager[847]: <warn>  [1671889863.9343] device (wlan0): Activation: failed for connection 'HOMEWIFI'
Dec 24 20:51:03 armbian NetworkManager[847]: <info>  [1671889863.9356] device (wlan0): state change: failed -> disconnected (reason 'none', sys-iface-state: 'managed')
Dec 24 20:51:10 armbian NetworkManager[847]: <info>  [1671889870.3403] device (wlan0): supplicant interface state: disconnected -> inactive
Dec 24 20:51:10 armbian NetworkManager[847]: <info>  [1671889870.3404] device (p2p-dev-wlan0): supplicant management interface state: disconnected -> inactive

**Comment by HelferP** [comment]
> dmesg|grep brcm
> dmesg|grep Bluetooth

<img width="929" alt="image" src="https://user-images.githubusercontent.com/32640817/209439184-29b89667-1ebc-4479-ab3a-2e8f3570c2f0.png">

**Comment by HelferP** [comment]
There are still such errors on the boot:


<img width="981" alt="image" src="https://user-images.githubusercontent.com/32640817/209439488-a666b3f6-e5b4-4d4a-8be5-a8a8958ee9d7.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/32640817/209439468-dbe4b099-b9c5-4716-914e-988b8f23b567.png">


<img width="1273" alt="image" src="https://user-images.githubusercontent.com/32640817/209439449-a24a72ba-d4e7-48e5-a9b3-0e66cc4e7acb.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/32640817/209439423-fccd2fea-f33d-4530-a4bf-7e45ccc58ef4.png">

<img width="896" alt="image" src="https://user-images.githubusercontent.com/32640817/209439381-787c3959-2ab2-445b-87bd-42cfdc4f1ad2.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/32640817/209439541-54fe5793-42b5-4d60-b449-30eef6f611b7.png">

<img width="981" alt="image" src="https://user-images.githubusercontent.com/32640817/209439558-426b071b-5442-46a0-88a5-ba0af21285fd.png">

**Comment by ophub** [comment]
From the log, your wireless and bluetooth are normally driven

**Comment by HelferP** [comment]
You're right. I found the wifi issue.
It was in setting my router to openwrt. Because of this setting, the box did not connect, while the rest of the devices, including the Raspberry Pi Zero W, work fine. In the picture is the line that caused the problem.
![изображение](https://user-images.githubusercontent.com/32640817/209475949-5a2530e9-b1b4-41fa-85ab-c29659d1e87f.png)

I also think I solved the kernel panic problem on the 5.15.y kernel. I compared two dts from 5.4.228 and 5.15.85, found a discrepancy, added them in 5.15.85 and now I don't get kernel panic on reboot.
Add in **opp-table** from 5.5.228 dtb

`		opp-100000000 {
			status = "disabled";
		};

		opp-250000000 {
			status = "disabled";
		};

		opp-500000000 {
			status = "disabled";
		};

		opp-750000000 {
			opp-hz = <0x00 0x2cb41780>;
			opp-microvolt = <0xb71b0>;
		};
		`

I'm still testing this and not completely sure.

**Comment by ophub** [comment]
Ok, your tweak feedback has been submitted to the kernel repository

**Comment by janko888** [comment]
> 



> added them in 5.15.85 and now I don't get kernel panic on reboot.

can u show ur box's cpufreq-info here?

**Comment by HelferP** [comment]
> > added them in 5.15.85 and now I don't get kernel panic on reboot.
> 
> can u show ur box's cpufreq-info here?

cpufrequtils 008: cpufreq-info (C) Dominik Brodowski 2004-2009
Report errors and bugs to cpufreq@vger.kernel.org, please.
analyzing CPU 0:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 50.0 us.
  hardware limits: 750 MHz - 1.91 GHz
  available frequency steps: 750 MHz, 1000 MHz, 1.20 GHz, 1.40 GHz, 1.50 GHz, 1.61 GHz, 1.70 GHz, 1.80 GHz, 1.91 GHz
  available cpufreq governors: userspace, conservative, powersave, ondemand, performance, schedutil
  current policy: frequency should be within 1.40 GHz and 1.91 GHz.
                  The governor "schedutil" may decide which speed to use
                  within this range.
  current CPU frequency is 1.91 GHz (asserted by call to hardware).
analyzing CPU 1:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 50.0 us.
  hardware limits: 750 MHz - 1.91 GHz
  available frequency steps: 750 MHz, 1000 MHz, 1.20 GHz, 1.40 GHz, 1.50 GHz, 1.61 GHz, 1.70 GHz, 1.80 GHz, 1.91 GHz
  available cpufreq governors: userspace, conservative, powersave, ondemand, performance, schedutil
  current policy: frequency should be within 1.40 GHz and 1.91 GHz.
                  The governor "schedutil" may decide which speed to use
                  within this range.
  current CPU frequency is 1.40 GHz (asserted by call to hardware).
analyzing CPU 2:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 50.0 us.
  hardware limits: 750 MHz - 1.91 GHz
  available frequency steps: 750 MHz, 1000 MHz, 1.20 GHz, 1.40 GHz, 1.50 GHz, 1.61 GHz, 1.70 GHz, 1.80 GHz, 1.91 GHz
  available cpufreq governors: userspace, conservative, powersave, ondemand, performance, schedutil
  current policy: frequency should be within 1.40 GHz and 1.91 GHz.
                  The governor "schedutil" may decide which speed to use
                  within this range.
  current CPU frequency is 1.40 GHz (asserted by call to hardware).
analyzing CPU 3:
  driver: cpufreq-dt
  CPUs which run at the same hardware frequency: 0 1 2 3
  CPUs which need to have their frequency coordinated by software: 0 1 2 3
  maximum transition latency: 50.0 us.
  hardware limits: 750 MHz - 1.91 GHz
  available frequency steps: 750 MHz, 1000 MHz, 1.20 GHz, 1.40 GHz, 1.50 GHz, 1.61 GHz, 1.70 GHz, 1.80 GHz, 1.91 GHz
  available cpufreq governors: userspace, conservative, powersave, ondemand, performance, schedutil
  current policy: frequency should be within 1.40 GHz and 1.91 GHz.
                  The governor "schedutil" may decide which speed to use
                  within this range.
  current CPU frequency is 1.40 GHz (asserted by call to hardware).

**Comment by HelferP** [comment]
> Ok, your tweak feedback has been submitted to the kernel repository

Tested for several days. After a while, I tried to reboot the device and got the kernel panic again. Now additionally disabled frequencies higher than the maximum specified in the processor specification. I've been testing for a day and have never received a kernel panic yet.

```
		opp-100000000 {
			status = "disabled";
		};

		opp-250000000 {
			status = "disabled";
		};

		opp-500000000 {
			status = "disabled";
		};

		opp-750000000 {
			opp-hz = <0x00 0x2cb41780>;
			opp-microvolt = <0xb71b0>;
		};

		opp-2016000000 {
			status = "disabled";
		};

		opp-2100000000 {
			status = "disabled";
					};
```

**Comment by yssylq** [comment]
ubuntu 18是哪个版本支持的，请问历史版本去哪里下载

**Comment by petesimon** [comment]
I experience a similar issue: ethernet does **not** work at all, but wifi, RAM work okay. Did not check bluetooth. I booted Armbian_24.11.0_amlogic_s905x3_jammy_6.1.112_server_2024.10.02.img.gz and later booted Armbian_24.11.0_amlogic_s905x3_noble_6.6.53_server_2024.10.02.img.gz from this Ophub site. I copied u-boot-s905x3.bin to u-boot.ext and it boots from SD card and USB 2.0 port. In the uEnv.txt file, I tried these dtb files and afterwards quit trying and opened this issue ticket. I did not try the extlinux/extlinux.conf file.

> # FDT=/dtb/amlogic/meson-sm1-h96-max.dtb - NO boot
> # FDT=/dtb/amlogic/meson-sm1-h96-max-x3-oc.dtb - NO boot
> # FDT=/dtb/amlogic/meson-sm1-h96-max-x3.dtb - boots okay, has wifi, but no ethernet
> # FDT=/dtb/amlogic/meson-sm1-x96-max-plus.dtb - boots okay, has wifi, but no ethernet
> # FDT=/dtb/amlogic/meson-sm1-a95xf3-air-gbit.dtb - boots okay, has wifi, but no ethernet
> # FDT=/dtb/amlogic/meson-sm1-hk1box-vontar-x3.dtb - boots okay, has wifi, but no ethernet
> # FDT=/dtb/amlogic/meson-sm1-x88-pro-x3.dtb - boots okay, has wifi, but no ethernet
> # FDT=/dtb/amlogic/meson-sm1-ugoos-x3.dtb - boots okay, has wifi, but no ethernet

What should I do? - Download a newer ophub image file? - Try other dtb? or ...?
