### ISSUE TITLE
A95x-F2 (s905x2) configuration information

### ISSUE THREAD

**Issue by RomanKozyrev** [ophub/amlogic-s9xxx-armbian#851]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S905x2]
 - Model [e.g. a95x f2]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.0.14]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述**
With 5.15.84 i have 100mbit lan working with  g12a-x96max-rmii.dtb, but with kernel 6.0.14 not.
详细描述问题，并在必要时附上屏幕截图。
![IMG_20221222_181330](https://user-images.githubusercontent.com/96186395/209186585-fefd5be3-9c6c-4f0f-875c-cb8914c07888.jpg)
![IMG_20221222_182839](https://user-images.githubusercontent.com/96186395/209186596-7df948d0-455f-4370-a9ce-5663d41d3d3f.jpg)

**Comment by ophub** [comment]
u-boot-x96max.bin

```
cd /boot
cp -f u-boot-x96max.bin u-boot.ext
cp -f u-boot-x96max.bin u-boot.emmc
chmod +x u-boot.ext u-boot.emmc
sync && reboot
```

**Comment by RomanKozyrev** [comment]
Still no luck
![IMG_20221223_133824](https://user-images.githubusercontent.com/96186395/209278057-e2320373-c675-4b8b-86d7-62e5de0fb7f3.jpg)
![IMG_20221223_134003](https://user-images.githubusercontent.com/96186395/209278070-5360d4a3-57c3-4ceb-802a-a79e7a9719ed.jpg)

**Comment by ophub** [comment]
u-boot-s905x2-s9222.bin
u-boot-sei510.bin

**Comment by RomanKozyrev** [comment]
Also did not help(

**Comment by ophub** [comment]
You can try whether these u-boots can be started under the 5.10 kernel.

**Comment by RomanKozyrev** [comment]
I took meson-g12a-x96-max-rmii.dtb from 5.10 kernel and it worked witth 6.0.14.
![IMG_20221224_144629](https://user-images.githubusercontent.com/96186395/209424889-d3f7954e-3006-4eae-98d5-a93128b8a63a.jpg)

**Comment by ophub** [comment]
ls -l /boot/u-boot*

**Comment by RomanKozyrev** [comment]
![IMG_20221224_150139](https://user-images.githubusercontent.com/96186395/209425266-6b31d6df-c1d4-456e-bb07-6dfd364c2b53.jpg)

**Comment by ophub** [comment]
a95x f2(s905x2), 100Mb Nic
u-boot-x96max.bin
meson-g12a-x96-max-rmii.dtb

**Comment by RomanKozyrev** [comment]
I dont see emmc when i use kernel below 6

**Comment by ophub** [comment]
add u-boot

**Comment by RomanVL25** [comment]
можете файлы прекрепить или сылки дать
у меня такая-же приставка 
и нету лана и звука

**Comment by yrksly** [comment]
I'm trying to install Armbian via armbian-install according to the instructions described above, but the following error appears, how can I fix it?
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149792665/527650f6-fecb-4eb7-8ea7-8fa446424946)

**Comment by yrksly** [comment]
> add u-boot
I'm trying to install Armbian via armbian-install according to the instructions described above, but the following error appears, how can I fix it?
![image](https://github.com/ophub/amlogic-s9xxx-armbian/assets/149792665/0fbd7449-c40d-4a70-a79e-9f8e474975c5)

**Comment by ainur-fa** [comment]
@yrksly I have a similar problem, was it solved?

**Comment by yrksly** [comment]
> @yrksly I have a similar problem, was it solved?

Yes. I'm using a different distribution - [devmfc](https://github.com/devmfc/amlogic-bootscripts-Armbian)

**Comment by votarum** [comment]
@yrksly thanks for the tip, I managed to get the boot. But original distribution for amlogic s905 does not have the armbian-install script. How did you manage to install on eMMC then?
