### ISSUE TITLE
Armbian_23.02.0_rockchip_beikeyun_bullseye少rk3318-box.dtb文件

### ISSUE THREAD

**Issue by rainups** [ophub/amlogic-s9xxx-armbian#852]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. RK3328]
 - Model [e.g. H96MaxPlus]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 6.0.14]
 - Release: [e.g.bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
用的是贝壳云img：
Armbian_23.02.0_rockchip_beikeyun_bullseye_6.0.14_server_2022.12.21.img
我在其它近期armbian里看到已有这个文件，但贝壳云img里没有/boot/dtb/rockchip/rk3318-box.dtb
同时在/boot/dtb/rockchip/overlay却有相关的文件。
不知是否遗漏？
![少rk3318-box dtb文件](https://user-images.githubusercontent.com/82754232/209260224-50a463c0-60b0-4511-8a33-89e7e73b13bc.png)

![少rk3318-box dtb文件2](https://user-images.githubusercontent.com/82754232/209260239-d1a54fce-a4ae-45d5-9198-7352c9e4594f.png)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.0.y/tree/main/arch/arm64/boot/dts/rockchip

源码中没有

**Comment by rainups** [comment]
哦，好的，我是看这里的：
https://github.com/armbian/build/tree/master/patch/u-boot/u-boot-rockchip64/board_rk3318-box

**Comment by ophub** [comment]
![photo_2023-09-23_17-21-23](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/cb2b48a6-1d8b-4cb7-9c7e-184b749dd04a)
![photo_2023-09-23_17-38-23](https://github.com/ophub/amlogic-s9xxx-armbian/assets/68696949/d1b92002-dbb9-4c01-bad6-2be6ec6e2e44)

根据doyoman在群里的耗时几个小时的不断测试反馈，贝壳云最终使用了新的u-boot方案和gpt分区格式后（msdos格式也可以顺利启动，两种分区方法均可使用），可以顺利启动使用。再次感谢doyoman的贡献。
