### ISSUE TITLE
Tx3 905x3 doesn't boot from emmc

### ISSUE THREAD

**Issue by fari2000** [ophub/amlogic-s9xxx-armbian#855]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [Tanix tx3]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.80 server]
 - Release: [Armbian_23.02.0_Aml_s905x3_bullseye_5.15.80_server_2022.12.01 ]

**Describe the bug | 问题描述**
The release can boot from sd. Armbian-install work without anomalies, but the device doesn't boot from the mmc. 
I have tried the following options from armbian-install : 501, 506, 511, 512, 513, 514, 517 and 520 . No one boots from mmc.
Does any one know this problem, any solution or a work around?
Thanks for any reply!

**Comment by urenai** [comment]
armbian-install -m yes

**Comment by ophub** [comment]
Gigabit wired, using `512`

![Snip20221224_1](https://user-images.githubusercontent.com/68696949/209421141-67b381d6-6c6c-4a61-a04e-390a9f3ea458.png)

**Comment by fari2000** [comment]
Thanks for your reply!
I have tries option 512. I can boot from SD. after Armbian-install it doesn't boot from emmc, even the installation process went smoothly.  I will try your configuration and feedback

**Comment by fari2000** [comment]
Wow! This worked. Thanks a lot!!!!
few days age I have tried the option 512, but did not boot from emmc. I do not know, what I have done wrong.
Now it is working. Thanks a lot for your great work and support!
