### ISSUE TITLE
HI！O Big！除了OMV以外，还有没有其他可用的NAS系统？

### ISSUE THREAD

**Issue by urenai** [ophub/amlogic-s9xxx-armbian#856]
**Describe the bug | 问题描述**

请问最近有没有修复OMV的计划？
有没有其他nas方案？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/armbian_software.md

nextcloud

**Comment by urenai** [comment]
OK!
只能等o大修复了，加油！
