### ISSUE TITLE
求e900v21c能用的dtb和bin

### ISSUE THREAD

**Issue by polegame** [ophub/amlogic-s9xxx-armbian#860]
**Device Information | 设备信息**
 - SOC: [S905L]
 - Model [e900v21c]

**Describe the bug | 问题描述**
请教一下，e900v21c能用的dtb和bin，我尝试刷[Armbian_23.02.0_amlogic_s905x_bullseye_5.15.84_server_2022.12.21.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_bullseye_12.21.0509/Armbian_23.02.0_amlogic_s905x_bullseye_5.15.84_server_2022.12.21.img.gz)，无任何改动，启动时报错网络服务无法启动，开机后获取不到ip
```
OK J Finished Armbian leds state.
36.534511] Bluetooth: hcio: BCM: failed to write update baudrate (-110)
36.544578] Bluetooth: hcio: Failed to set baudrate
38.355221] system [1]: etc-machine x2did.mount: Succeeded.
38.377676] systemd[1]: Finished Commit a transient machine-id on disk.
] Finished Commit a transient machine-id on disk.
38.543239] ram: Added device: zramo
38.552153] zram: Added device: zram1
38.560989] ram: Added device: zramz
38.667855] Bluetooth: hc10: command Ox0c09 tx timeout
38.697950] zramo: detected capacity change from 0 to 823008
38.760263] Adding 411500k swap on /dev/zramo. Priority:5 extents: 1 across:411500k SSFS
38.927541] meson&b-dumac c9410000.ethernet etho: PHY [O.e40908ff :08] driver [Meson GL Internal PHY] (irq=52)
38.935921] zram1: detected capacity change from 0 to 102400
38.955880] meson8b-dumac c9410000.ethernet etho: Register MEM_TYPE_PAGE_POOL RX0-0
「39.031788] zram2: detected capacity change from 0 to 823008
39.094431] EXT4-fs (zram2): mounted filesystem without journal. Opts: discard. Quota mode: none.
39.105892] ext4 filesystem being mounted at /tmp supports timestamps until 2038 (0x7fffffff)
39.146943] systend [1]: Finished Armbian ZRAM config.
OK ] Finished Armbian ZRAM config.
39.165760] systemd [1]: Starting Armbian memory supported logging...
Starting Armbian memory supported logging..
39.246796] EXT4-fs (zram1): mounted filesystem without journal. Opts: discard. Quota mode: none.
39.258621] ext4 filesystem being mounted at /var/log supports timestamps until 2038 (0x7fffffff)
scord. 208 co04;
39.539275] systend [1]: Finished Wait for network to be configured by ifupdown.
OK 1 Finished Wait for network to be configured by ifupdown.

40.491175] meson8b-dumac C9410000.ethernet etho: No Safety Features support found
40.501729] meson8b-dumac c9410000.ethernet etho: PT not supported by Hw
40.5120161 mesoneb-dumac c9410000 .ethernet etho: configuring for phy/rmii link mode
40.600429] system [1]: networking.service: start operation timed out. Terminating.
40.613898] systemd[1]: networking.service: Main process exited, code-exited, status=1/FAILURE
40.626103] system [1]: networking.service: Killing process 710 (isc-timer) with signal SIGKILL.
40.659087] systemd [1] : networking.service: Failed with result
'timeout
40.670418] systemd [1]: Failed to start Raise network interfaces.
[FAILED] Failed to start Raise network interfaces.
See
'sustenct1 status networking.service' for details.
42.727043] systemd [1]: Finished Armbian memory supported logging.
OK
] Finished Armbian memory supported logging.
42.744622] systemd [1]: Starting Journal Service..
Starting Journal Service...
42.992108] systemd [1]: Started Journal Service.
Ok ] Started Journal Service.
Starting Flush Journal to Persistent Storage...
43.039895] systemd-journald [783]: Received client request to flush runtime Journal.
46.561419] Bluetooth: hcio: BCM: Reset failed (-110)
OK 1 Finished Flush Journal to Persistent Storage.
Starting Create Volatile Files and Directories
DK
0.
1 Finished Create Volatile Files and Directories.
] Started Entropy Daemon based on the HAVEGE algorithm.
```
抱歉日志是图片转文字的，格式有点乱

**Comment by ophub** [comment]
dtb使用这个：meson-gxl-s905x-nexbox-a95x.dtb
u-boot使用这2个测试下：
u-boot-s905x-s912.bin
u-boot-p212.bin

u-boot可以先不添加，使用5.15内核的固件测试下能否启动，有线网络是否正常。如果有问题再分别测试复制u-boot为u-boot.ext并重启。

**Comment by polegame** [comment]
不添加u-boot的时候，可以正常从u盘启动，网络不正常，跟上面的报错一样，添加了u-boot以后，无法从u盘启动，在闪屏阶段不断重启

**Comment by ophub** [comment]
/boot/extlinux/extlinux.conf.bak

这个文件的后缀.bak删除，改名为extlinux.conf后，把里面的dtb也改名为meson-gxl-s905x-nexbox-a95x.dtb，重启试试

**Comment by polegame** [comment]
不行，还是不停重启

**Comment by ophub** [comment]
https://blog.vihor.cn/2020/29.html

我在网上看别人的文章，使用meson-gxl-s905x-nexbox-a95x.dtb可以启动，要不你下载他们分享的固件试试。

**Comment by lragon** [comment]
之前刷过Armbian_5.99_Aml-g12_Debian_buster_default_5.3.0.img.xz，网络也是有问题，不知道这个5.97的行不行，晚上回去试试

**Comment by polegame** [comment]
重启是u盘速率不行，后来换了个u盘不重启了，现在遇到的问题是armbian-install应该选哪个
![22-42-20](https://user-images.githubusercontent.com/4179148/212347019-043254cd-2472-4f38-9c48-2cec584f87a4.png)

**Comment by ophub** [comment]
cat /boot/uEnv.txt
ls -l /boot/u-boot*
截图

**Comment by polegame** [comment]
![23-30-31](https://user-images.githubusercontent.com/4179148/212359391-9bcf8255-1d0f-4d70-8ec8-6e7ddb9a85b1.png)

**Comment by ophub** [comment]
选择106，这个和你截图一样。
写入emmc后反馈一下结果。有线网络是否正常。

**Comment by polegame** [comment]
不好意思，上面的截图有误，重新刷了一下u盘，结果如下
![11-10-32](https://user-images.githubusercontent.com/4179148/212448187-e799387b-a0fe-4723-bf89-97626687c80c.png)

**Comment by ophub** [comment]
你上图怎么截图的呢？能正确启动就行，有误是什么意思？

**Comment by ophub** [comment]
下面的这个图，选择0

Please Input SoC Name填：
s905l

Please Input DTB Name填：
meson-gxl-s905x-nexbox-a95x.dtb

Please Input UBOOT_OVERLOAD填：
u-boot-s905x-s912.bin

其他项回车略过。

**Comment by polegame** [comment]
就是我按照你说的写入到emmc后发现有线网络无法用，我就把dtb改成meson-gxl-s905x-nexbox-a95x.dtb了

**Comment by polegame** [comment]
MAINLINE_UBOOT 填什么

**Comment by ophub** [comment]
改了后在emmc里网络可以使用了？

**Comment by polegame** [comment]
写入emmc网络就不能用了

**Comment by polegame** [comment]
我发现一个现象，如果emmc的u-boot跟u盘的一样，插上u盘启动后就会不停的重启，删掉u-boot就可以启动了

**Comment by ophub** [comment]
写入emmc可以启动了？有线网络正常吗？

**Comment by polegame** [comment]
写入emmc后可以从emmc启动，有线网络不正常，网线指示灯不闪，这个设备支持hdmi的

**Comment by ophub** [comment]
试试另外一个u-boot
cd /boot
cp -f u-boot-s905x-s912.bin u-boot.ext
cp -f u-boot-s905x-s912.bin u-boot.emmc
chmod +x u-boot.ext u-boot.emmc
sync && reboot

**Comment by polegame** [comment]
> 试试另外一个u-boot cd /boot cp -f u-boot-s905x-s912.bin u-boot.ext cp -f u-boot-s905x-s912.bin u-boot.emmc chmod +x u-boot.ext u-boot.emmc sync && reboot

执行完命令后盒子重启，1.屏幕花屏，2.大概3秒后自动重启，然后重复1、2，如果在花屏期间按下回车就会停留在花屏界面，花屏期间，网线灯闪烁，但是路由器设备列表里没有盒子，准备放弃了，不行就一直插usb运行系统或者重新买个设备

**Comment by hotlcc** [comment]
你好，我也是e900v21c，请问一下，你是通过安卓底包引导的还是短接从u盘引导啊？我短接从U盘引导，什么反映都没有，直接进入原先的系统了。

**Comment by LeosDing** [comment]
> 你好，我也是e900v21c，请问一下，你是通过安卓底包引导的还是短接从u盘引导啊？我短接从U盘引导，什么反映都没有，直接进入原先的系统了。

上电按遥控器向右方向键

**Comment by hotlcc** [comment]
> > 你好，我也是e900v21c，请问一下，你是通过安卓底包引导的还是短接从u盘引导啊？我短接从U盘引导，什么反映都没有，直接进入原先的系统了。
> 
> 上电按遥控器向右方向键

好的，我试试

**Comment by LeosDing** [comment]
> > 试试另外一个u-boot cd /boot cp -f u-boot-s905x-s912.bin u-boot.ext cp -f u-boot-s905x-s912.bin u-boot.emmc chmod +x u-boot.ext u-boot.emmc sync && reboot
> 
> 执行完命令后盒子重启，1.屏幕花屏，2.大概3秒后自动重启，然后重复1、2，如果在花屏期间按下回车就会停留在花屏界面，花屏期间，网线灯闪烁，但是路由器设备列表里没有盒子，准备放弃了，不行就一直插usb运行系统或者重新买个设备

Armbian_5.99_Aml-g12_Ubuntu_bionic_default_5.3.0_rtl8189ftv.tar.gz 这个貌似wifi可以用，有线不行。。

**Comment by LeosDing** [comment]
我试了 Armbian_24.5.0_amlogic_s905l_jammy_5.15.153_server_2024.04.01.img.gz ，貌似wifi和有线都可以了，，
修改uEnv.txt，使用 meson-gxl-s905x-nexbox-a95x.dtb
复制/boot/extlinux/extlinux.conf.bak为/boot/extlinux/extlinux.conf，同样使用meson-gxl-s905x-nexbox-a95x.dtb
上电启动进系统，执行armbian-install安装，选择107（就是s905x-nexbox-a95x）那个
安装完成后重启进系统，进/boot，cp u-boot-s905x-s912.bin u-boot.emmc
重启后花屏，默认的联通log不会显示，等一段时间进入系统，，默认有线可以看到自动获取了地址，iwlist wlan0 scanning也能扫到wifi

问题：
RTL871X tty终端不断输出日志，挺烦人啊。。
![1683923496](https://github.com/ophub/amlogic-s9xxx-armbian/assets/10290601/0eb5c0d2-eb4c-4256-8c8d-d0b5b41231a1)

**Comment by LeosDing** [comment]
> 我试了 Armbian_24.5.0_amlogic_s905l_jammy_5.15.153_server_2024.04.01.img.gz ，貌似wifi和有线都可以了，， 修改uEnv.txt，使用 meson-gxl-s905x-nexbox-a95x.dtb 复制/boot/extlinux/extlinux.conf.bak为/boot/extlinux/extlinux.conf，同样使用meson-gxl-s905x-nexbox-a95x.dtb 上电启动进系统，执行armbian-install安装，选择107（就是s905x-nexbox-a95x）那个 安装完成后重启进系统，进/boot，cp u-boot-s905x-s912.bin u-boot.emmc 重启后花屏，默认的联通log不会显示，等一段时间进入系统，，默认有线可以看到自动获取了地址，iwlist wlan0 scanning也能扫到wifi
> 
> 问题： RTL871X tty终端不断输出日志，挺烦人啊。。 ![1683923496](https://private-user-images.githubusercontent.com/10290601/318641278-0eb5c0d2-eb4c-4256-8c8d-d0b5b41231a1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwMzE5MDYsIm5iZiI6MTcxMjAzMTYwNiwicGF0aCI6Ii8xMDI5MDYwMS8zMTg2NDEyNzgtMGViNWMwZDItZWI0Yy00MjU2LThjOGQtZDBiNWI0MTIzMWExLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDA0MjAwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE4YTk1MTQ4MjM3OWM0ZTNiZmZiMzg2NzA2MzIzNmQ0MTFmNzc4ZTZmMzkyMDg2MDg2NmNkOGY2NGMxYzQxMWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r4mDKBb6ySXLJRGpRPfr-qfNCFe8wiBxZu2kMG2ajqo)

![1](https://github.com/ophub/amlogic-s9xxx-armbian/assets/10290601/ec6083d5-d5e0-4ca9-9e61-f4dd48f1fa7f)

**Comment by LeosDing** [comment]
> > 试试另外一个u-boot cd /boot cp -f u-boot-s905x-s912.bin u-boot.ext cp -f u-boot-s905x-s912.bin u-boot.emmc chmod +x u-boot.ext u-boot.emmc sync && reboot
> 
> 执行完命令后盒子重启，1.屏幕花屏，2.大概3秒后自动重启，然后重复1、2，如果在花屏期间按下回车就会停留在花屏界面，花屏期间，网线灯闪烁，但是路由器设备列表里没有盒子，准备放弃了，不行就一直插usb运行系统或者重新买个设备

USB3.0的U盘貌似有问题，，我换了2.0的都正常了。。使用新的版本安装后wifi、有线都可以了，，
