### ISSUE TITLE
s905w+rtl8189FTV  kernel panic

### ISSUE THREAD

**Issue by sinyavskiy-n** [ophub/amlogic-s9xxx-armbian#862]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: s905w
 - Model x96mini 1+8gb

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.84, 5.15.85
 - Release: jammy, bullseye

**Describe the bug | 问题描述**
while connecting to a wi-fi network, a panic kernel appears, while the wi-fi network is visible and the device is working.
I'm not good at linux, and searching the internet failed to solve the problem.

![photo_2022-12-25_19-44-30](https://user-images.githubusercontent.com/61477120/209475900-f66f70ef-b99d-4bd3-898e-f70c755ffd13.jpg)

**Comment by ophub** [comment]
If some version encounters a kernel panic, try updating to a different series first, such as 5.4
