### ISSUE TITLE
Backup EMMC not working - S912 X92 Vontar

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#864]
SOC: S912
Model:  X92 Vontar
Kernel: Linux t1000 5.15.85-flippy-80+o #199 SMP PREEMPT Thu Dec 22 11:27:10 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
Release: Jammy

Tried to use the backup module:
![afbeelding](https://user-images.githubusercontent.com/53115937/209486379-f80883bc-ed8e-4db3-b8e2-08075be24399.png)

Output backup module:
![afbeelding](https://user-images.githubusercontent.com/53115937/209486388-6b014dff-7f62-44a5-a02a-850262d6c3ae.png)

Storage:
![afbeelding](https://user-images.githubusercontent.com/53115937/209486403-07629069-5f4e-45c4-8756-faab5cf07370.png)

**Comment by d5stick** [comment]
UPDATE:   
i tried to updated the kernel to 6.1.1, using the method:
- sudo armbian-update -k 6.1.1 -v stable -m yes. 
Checks completed, kernel was installed, device rebooted but failed to load into Armbian. Errors about storage 2 not found. 

I burned the file "Armbian_23.02.0_amlogic_s912_jammy_6.1.1_server_2022.12.25.img.gz" to SDcard and rebooted the box with the SDcard in it, without resetting the box. Just a normal power off/on.  Untill my suprise the box booted with my old config and i was able to SSH into it with and all looks ok. 

When rebooting without the SD  inserted, it wont boot from EMMC, When rebooting with the SD inserted, it boots just fine from EMMC. 

Kernel: 
Linux t1000 6.1.1-flippy-80+ #6 SMP Sun Dec 25 01:54:50 CST 2022 aarch64 aarch64 aarch64 GNU/Linux
pi@t1000:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           294M  4.8M  289M   2% /run
/dev/mmcblk2p2   14G  5.7G  7.7G  43% /
tmpfs           1.5G     0  1.5G   0% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
/dev/zram2      1.5G  128K  1.4G   1% /var/tmp
/dev/mmcblk2p1  511M  108M  404M  22% /boot
/dev/zram1       47M   31M   14M  70% /var/log
tmpfs           294M   56K  293M   1% /run/user/1000

**Comment by ophub** [comment]
armbian-ddbr needs to be booted from usb and cannot be used in emmc

The firmware of s912 does not have MAINLINE_UBOOT, so it does not matter whether -m is used or not
