### ISSUE TITLE
X92 Vontar - Boot EMMC corrupt

### ISSUE THREAD

**Issue by d5stick** [ophub/amlogic-s9xxx-armbian#867]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S912
 - Model X92
 - 
**Armbian Version | 系统版本**
 - Kernel Version: 6.1.1
 - Release: jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
After updating from kernel 5.15 to 6.1.1, the box did not boot from EMMC. 
Error about wrong DTB. Error showed its loading 905x libretech cc.dtb  and goes into boot loop. 

Burned the Ophub armbian jammy with kernel 6.1.1 S912 IMG to SDcard, it boots the box and picks up the data from the EMMC. 

Found the entry in boot/u-boot.ext and boot/u-boot.emmc. Updated the entry to the X92 DTB. 
Rebooted the box without SDcard, seems to be stuck on the boot logo. 

When inserting the SDcard, and rebooting the box, the box boots again with EMMC data. 
Remoivng the SDcard and rebooting the box results again in bootloop.

Is there a way to repair/rebuild the boot partition and its files so i do not need the SDcard to boot?

**Comment by ophub** [comment]
After booting from the SD card, you can mount the emmc partition to the SD card, and then copy the files in the SD card to emmc to overwrite.
