### ISSUE TITLE
关于S905L3a的CPU频率

### ISSUE THREAD

**Issue by hululu1068** [ophub/amlogic-s9xxx-armbian#868]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905L3a]
 - Model [M401a]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.85-flippy-80+o]
 - Release: [Armbian (23.02.0-trunk) aarch64]

**Describe the bug | 问题描述**
升级到`bullseye_5.15.85_server_2022.12.25`后发现CPU频率最高只能到`1.7GHz`，之前刷`bullseye_5.15.79_server_2022.11.20`能到`1.91GHz`

<img width="486" alt="image" src="https://user-images.githubusercontent.com/68652362/209613120-a850dc6d-3e91-4bc2-9730-e09ca2db507c.png">

<img width="242" alt="image" src="https://user-images.githubusercontent.com/68652362/209612178-d379fa3e-e971-41b2-8603-d99888230d79.png">

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/main/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-m401a.dts

到1800部分机器会开始出现恐慌现象，再高会出现无法正常识别emmc等不稳定现象。

**Comment by janko888** [comment]
m401a和cm311-1a本质上基本相同，之前独立m401a的配置是针对这块板子的内存和emmc的个体差异较大，而做出优先考虑兼容性为主的配置。如果对性能有要求可以自行修改编译一份高频率的dtb,或者直接尝试使用cm311-la的dtb。

**Comment by hululu1068** [comment]
我的盒子体质比较好，能稳定`1908MHz`.防丢，也分享给有需要的...另外，这个dtb启动很快、也很顺畅
[DTB_M401A_1908MHz.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/13650147/DTB_M401A_1908MHz.zip)
