### ISSUE TITLE
enlarge /BOOT ?

### ISSUE THREAD

**Issue by MX10-AC2N** [ophub/amlogic-s9xxx-armbian#87]
Hi @ophub 
I have a little free space problem on the /boot partition would it be possible to enlarge it directly or does it require a new build..?

**Comment by ophub** [comment]
Building a simpler

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/rebuild#L39

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/common-files/files/usr/sbin/armbian-install#L13

**Comment by MX10-AC2N** [comment]
Thank @Ophub
Could it be possible to have /BOOT partition as ext4 and not fat..
