### ISSUE TITLE
X96 Max Plus Q1（s905x3）4G+32G Bluetooth not working

### ISSUE THREAD

**Issue by tv4you2016** [ophub/amlogic-s9xxx-armbian#870]
Hello @ophub

my box is an X96 Max PlusQ1 

Used DTB file: [meson-sm1-x96-max-plus-q1.dtb](https://github.com/ophub/amlogic-s9xxx-armbian/files/10200277/meson-sm1-x96-max-plus-q1.dtb.zip)

https://github.com/ophub/amlogic-s9xxx-armbian/issues/788#issue-1485054003

everything is working so far except the Bluetooth it will be possible to get it working

**Comment by ophub** [comment]
[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10314068/meson-sm1-x96-max-plus-q1.dtb.zip)

Download, unzip, overwrite the file with the same name, install Bluetooth in armbian-config, and restart

![Snip20221228_2](https://user-images.githubusercontent.com/68696949/209808750-c23e0d08-bf04-4073-9b85-c082fed39b25.png)

![Snip20221228_1](https://user-images.githubusercontent.com/68696949/209808771-f921cff0-974c-4b09-a223-8ebf7cb7cd1f.png)

**Comment by ophub** [comment]
What Bluetooth chip? Isn't cdtech 4761743 qca6174-bt?

**Comment by tv4you2016** [comment]
I don't know what my Bluetooth chip is, how can I find out??
cdtech 4761743 is the my wifi chip

**Comment by ophub** [comment]
The result I found on the Internet is this, you can look for information and see what the code of the Bluetooth chip of your box is.

**Comment by tv4you2016** [comment]
![image](https://user-images.githubusercontent.com/83761813/209819924-a989b4d4-3c80-4d97-bbb1-c578b1c4f062.png)

![image](https://user-images.githubusercontent.com/83761813/209819944-e6e87f86-7ba7-43ec-8169-2eed5a63276a.png)

![image](https://user-images.githubusercontent.com/83761813/209819982-2f790955-774b-4c95-bea7-13433890553e.png)

![image](https://user-images.githubusercontent.com/83761813/209819992-0e818504-bff7-4e9d-811d-41a0b075537d.png)


![image](https://user-images.githubusercontent.com/83761813/209820020-9ff3b6a3-ae0d-40d0-b15c-d9e44e45325e.png)



I can't connect to any bt device, I've tried the cell phone, a colona and without success

**Comment by ophub** [comment]
You check the information to find out what your bluetooth chip code is, just modify the code here（`qca6174-bt`） and compile it.

```
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2019 BayLibre SAS. All rights reserved.
 * Copyright (c) 2020 Christian Hewitt <christianshewitt@gmail.com>
 * Copyright (c) 2022 Flippy
 */

/dts-v1/;

#include "meson-sm1-x96-air.dts"

/ {
	compatible = "amediatech,x96-max", "amlogic,sm1";
	model = "X96 Max Plus Q1";

	aliases {
		serial0 = &uart_AO;
		ethernet0 = &ethmac;
	};

	memory@0 {
		device_type = "memory";
		reg = <0x0 0x0 0x0 0xf0800000>;
	};
};

/* This is connected to the Bluetooth module: */
&uart_A {
	status = "okay";
	pinctrl-0 = <&uart_a_pins>, <&uart_a_cts_rts_pins>;
	pinctrl-names = "default";
	uart-has-rtscts;

	bluetooth {
		compatible = "qcom,qca6174-bt";
		enable-gpios = <&gpio GPIOX_17 GPIO_ACTIVE_HIGH>;
		max-speed = <2000000>;
		clocks = <&wifi32k>;
		clock-names = "lpo";
	};
};

&uart_AO {
	status = "okay";
	pinctrl-0 = <&uart_ao_a_pins>;
	pinctrl-names = "default";
};

&ethmac {
	status = "okay";
	phy-handle = <&internal_ephy>;
	phy-mode = "rmii";
};

&internal_ephy  {
	max-speed = <100>;
};

```

**Comment by tv4you2016** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/870#issuecomment-1366656950


it detects the devices but does not connect is that why?

**Comment by ophub** [comment]
[meson-sm1-x96-max-plus-q1.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10317407/meson-sm1-x96-max-plus-q1.dtb.zip)

![image](https://user-images.githubusercontent.com/68696949/209898565-19ba49f9-5e0c-4e42-9ff6-b20be23ab8de.png)

`compatible = "qcom,qca6390-bt";`

**Comment by tv4you2016** [comment]
Hello @ophub 

these days I didn't have time to test but today I will test and give feedback

**Comment by tv4you2016** [comment]
view https://github.com/EmuELEC/EmuELEC/issues/323#issuecomment-791497939

**Comment by ophub** [comment]
![Snip20221230_1](https://user-images.githubusercontent.com/68696949/210057457-0905599b-051f-4b87-9034-dfa29d62ae0f.png)

![image](https://user-images.githubusercontent.com/68696949/210057472-177ff702-f5a5-4583-8415-73a65eedb126.png)

From your `dmesg` log, you are `QCA6390`, and the system is looking for the `qca/rampatch_00440302.bin` driver

According to the official kernel documentation, the available options are the options in the picture above, and I see that there is a version corresponding to the log.

The qca driver is also specially added for you.
https://github.com/ophub/firmware/tree/main/firmware/qca

There is no accurate description of the Bluetooth chip model. Guess is the only way to solve the problem. If not, forget it.
