### ISSUE TITLE
cm311-1a yst 莫名其妙的死机

### ISSUE THREAD

**Issue by zhuguoqing123** [ophub/amlogic-s9xxx-armbian#872]
![image](https://user-images.githubusercontent.com/96900868/209901194-1f82127a-da75-4936-9f33-442cb0e57b43.png)
运行大概15天吧，死机了。。

**Comment by urenai** [comment]
换debian内核试试呢？

**Comment by livelier** [comment]
可能和CPU温度有关，刚开机2分钟55度。盒子可能🐑了。
尝试一下CPU降温，一个物理降温。另一个 cpufreq 把最高频率降低一些。
