### ISSUE TITLE
armbian支持lvm吗

### ISSUE THREAD

**Issue by guugg** [ophub/amlogic-s9xxx-armbian#873]
好像在官网上看到支持？

**Comment by urenai** [comment]
https://blog.csdn.net/qadzhangc/article/details/126863084

善用搜索

**Comment by guugg** [comment]
> https://blog.csdn.net/qadzhangc/article/details/126863084
> 
> 善用搜索

我想了解的是从根目录开始支持的那种，我不是问从硬盘启动啊
