### ISSUE TITLE
CM311-1a YST刷機遇到的問題

### ISSUE THREAD

**Issue by inmi1229** [ophub/amlogic-s9xxx-armbian#875]
我在刷机的时候，用开心电视助手可以连到，一但选调试再按由U盘开机，
就出现Andorid recovery，也不会去载入u盘的
Armbian_23.02.0_amlogic_s905x2_jammy_6.1.1_server_2022.12.28.img.gz
我重式很多次，都一样的结果，是因为我买的机子被刷成别的android 9吗?
我不能开启开发人员模式，但开心电视助手可以连接那台机子，按U盘开机，也会重启，但一直停在recovery 模式
![54f831d8c03aeab2bb419c440f20e36](https://user-images.githubusercontent.com/121610166/209937825-462ed02d-9c5b-4c08-9527-e27f63f1ecb6.jpg)

**Comment by ophub** [comment]
armbian镜像解压成img后缀格式，并用 [Rufus](https://rufus.ie/) or [balenaEtcher](https://www.balena.io/etcher/) 写盘软件写入emmc才行，直接把img.gz放在u盘中不能用。

**Comment by inmi1229** [comment]
> armbian镜像解压成img后缀格式，并用 [Rufus](https://rufus.ie/) or [balenaEtcher](https://www.balena.io/etcher/) 写盘软件写入emmc才行，直接把img.gz放在u盘中不能用。

我已經用[balenaEtcher 写盘软件寫到U盤了，看起來是沒抓到U盤，我可用ADB直接刷嗎?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#124-set-the-box-to-boot-from-usbtfsd
