### ISSUE TITLE
系统负载持续增长至100+，失去主机连接

### ISSUE THREAD

**Issue by livelier** [ophub/amlogic-s9xxx-armbian#876]
**Device Information | 设备信息**
 - SOC: [S095x3,S095x3-B]
 - Model [UGOOS-X3,SKYBOX-LB2004]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.1]
 - Release: [jammy,bullseye]

**Describe the bug | 问题描述**
两款盒子，两个系列的固件都有测试。usb启动或emmc启动，均出现此问题。
10-50分钟，系统负载持续增长至100多，直至主机失去连接，无法SSH连接，开始可以ping通，后面ping不通，空系统没有安装任何软件包。

在北方家里显示器没有HDMI接口，看不到具体信息。

o大，我这个问题也可能是个例，看看我需要提供什么信息，可以分析到具体原因。

**Comment by ophub** [comment]
https://www.linuxprobe.com/monitorin-system-ubuntu.html


sudo apt-get install glances

装个监控看看，哪个进程占用红了。

**Comment by Yxini** [comment]
是SWAP的负载到100%吗

**Comment by livelier** [comment]
@ophub o大 使用top抓到了，vnstatd使用率100%，glances 抓不到就失去连接了。

![image](https://user-images.githubusercontent.com/104582100/210034753-e1cf6bf0-0a84-4e62-b6c5-eaafc63ec316.png)

卸载vnstat 继续测试 sadc 使用率100%
![image](https://user-images.githubusercontent.com/104582100/210036357-dbca5e52-9918-45ba-b314-baee1ee05791.png)

@Yxini 不是SWAP，4G内存空系统基本用不到。是LOAD

**Comment by ophub** [comment]
https://www.cnblogs.com/DataArt/p/9651272.html

这找到点关于sadc的介绍，你是安装了一个什么系统服务，在不停调用这个监控统计，往哪里记录什么？

**Comment by livelier** [comment]
什么都没有安装，下载固件刷入USB启动，然后会出现这个问题。

**Comment by ophub** [comment]
![Snip20221230_8](https://user-images.githubusercontent.com/68696949/210037354-dc7a358d-14da-4a7a-8b54-6d8fe39a8c50.png)
![Snip20221230_6](https://user-images.githubusercontent.com/68696949/210037359-172782a6-ff37-443b-a861-3a4abc253661.png)
![Snip20221230_7](https://user-images.githubusercontent.com/68696949/210037361-dc8bd9a8-748a-4607-8aa8-2c901074662a.png)

我这些很闲，虽然内核都更新到最新了，但是版本跨度有2个月，我只有开机的1分钟内负载高，一会就落下来了，平时很少看到10%以上的现象。

**Comment by livelier** [comment]
好的，o大，我们之间只有 u-boot 和 dtb 不同，其他是一样的，我在研究研究。

**Comment by livelier** [comment]
临时解决办法，停用无线网卡，仅使用有线网卡，即可恢复正常。具体原因目前没有找到。
