### ISSUE TITLE
armbian-software常用软件

### ISSUE THREAD

**Issue by zui-lang** [ophub/amlogic-s9xxx-armbian#878]
1.Navidrome,简单好用的音乐服务，dockerhub地址：https://hub.docker.com/r/deluan/navidrome
2.alist，多种存储文件列表程序，官网地址：https://alist.nn.ci/zh/

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/fe03f7cb02adafb3d55d6707d329cd75f5641364

已添加。

**Comment by zui-lang** [comment]
感谢

**Comment by zui-lang** [comment]
请问应当如何更新software列表

**Comment by ophub** [comment]
armbian-sync
可以一键更新全部的脚本

**Comment by zui-lang** [comment]
更新后还是无法获取![image](https://user-images.githubusercontent.com/77880495/210124245-d506ec52-d7a5-4c4e-9118-f5063bf6c1dc.png)
![image](https://user-images.githubusercontent.com/77880495/210124248-6e9ecebd-1171-4ecd-a5e7-2fdd49dc522b.png)

**Comment by ophub** [comment]
你是什么时候的版本？
`cat /etc/ophub-release`

老版升级方法：
https://github.com/ophub/amlogic-s9xxx-armbian/issues/761

**Comment by zui-lang** [comment]
这一款https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_12.28.0158/Armbian_23.02.0_amlogic_s905_jammy_5.15.85_server_2022.12.28.img.gz

**Comment by ophub** [comment]
再更新一下，截全图我看看

**Comment by zui-lang** [comment]
我好像找到问题了，没法连到GitHub，没有软路由应该怎么弄

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/fe03f7cb02adafb3d55d6707d329cd75f5641364

/usr/share/ophub/armbian-software/software-list.conf

/usr/share/ophub/armbian-software/command-docker.sh

这两个文件，手动下载上传到armbian里面覆盖原来的文件

**Comment by zui-lang** [comment]
反馈一个bug，昨天忘记说了，portainer的中文版无法使用，关闭容器停止容器什么的都不行，不知道是不是中文版的版本太低了，换成英文版的就OK了

**Comment by ophub** [comment]
这个中文版和英文版不是一个仓库。英文版的是 https://hub.docker.com/r/portainer/portainer-ce 官方仓库，中文版的是 https://hub.docker.com/r/6053537/portainer-ce 仓库，我忘了来源了，可能是我当时从网上找到的源。我刚才看了一下，他5天前才更新了，应该是一个长期维护的版本。改天我测试一下。

**Comment by ophub** [comment]
https://ghproxy.com/

以前我想加，但是试了这个加速不支持svn协议，svn可以一下拉取一个目录，比curl方便一点。

**Comment by zui-lang** [comment]
我想问一下，我安装了firefox，但是我应该怎么运行呢

**Comment by ophub** [comment]
桌面，点更多列表，点firefox🔥启动

**Comment by zui-lang** [comment]
安装firefox之后有图形化界面了吗，我自从连上Wi-Fi后用的都是ssh连接

**Comment by ophub** [comment]
接显示器

**Comment by zui-lang** [comment]
之前接显示器都是只有命令行，和ssh连接一样，明天我试试

**Comment by ophub** [comment]
201安装桌面，重启就可以进入图形桌面了。ssh连接还是终端界面，用远程桌面可以像显示器一样访问图形桌面，但我没弄过。

**Comment by zui-lang** [comment]
我在安装desktop后，连接显示器，还是命令行，在安装期间，让我注册了一个新的用户（之前只有root）但是登入那个新用户依旧是命令行

**Comment by ophub** [comment]
什么盒子

**Comment by zui-lang** [comment]
斐讯n1

**Comment by ophub** [comment]
你上面反馈说你使用的s905固件，N1应该使用s905d，你是怎么写入emmc的呢？选择了什么序号？

**Comment by zui-lang** [comment]
阿这(　ﾟ皿ﾟ)有点记不太清了，就正常刷入，选了一个bu什么什么的（记不太清）然后文件格式选了ext4

**Comment by OwnerCM** [comment]
> 这个中文版和英文版不是一个仓库。英文版的是 https://hub.docker.com/r/portainer/portainer-ce 官方仓库，中文版的是 https://hub.docker.com/r/6053537/portainer-ce 仓库，我忘了来源了，可能是我当时从网上找到的源。我刚才看了一下，他的版本是2.16，和官方的一样，他5天前还更新了，应该是一个长期维护的版本。改天我测试一下。

这个问题依旧存在，请问O大是否有解决方案

**Comment by ophub** [comment]
https://hub.docker.com/r/6053537/portainer-ce

我看他一直在更新，作者的说明里面有github仓库的链接，我看了一下问题区没有人反应你说的问题。他的下载量有100万次。
你把你的问题截图祥细一点反馈到他的github问题区。

**Comment by OwnerCM** [comment]
> https://hub.docker.com/r/6053537/portainer-ce
> 
> 我看他一直在更新，作者的说明里面有github仓库的链接，我看了一下问题区没有人反应你说的问题。他的下载量有100万次。 你把你的问题截图祥细一点反馈到他的github问题区。

经测试直接使用作者hub.docker你的命令：docker run -d --restart=always --name="portainer" -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock 6053537/portainer-ce 安装可以正常使用，可能还是系统集成的安装方式有问题。
