### ISSUE TITLE
Armbian外接USB无线网卡

### ISSUE THREAD

**Issue by saenice** [ophub/amlogic-s9xxx-armbian#879]
硬件设备：CM311-1a
系统版本：Armbian 23.02.0-trunk Bullseye with Linux 5.15.85-flippy-80+o
问题描述：使用免驱usb无线网卡设备无法启用40MHz频宽无线！【20MHz正常】
【路由器强制Wifi 40MHz】使用命令：iwconfig wlan0   查询：
Tenda型号W311M（150M）无线网卡链接Bit Rate ≤150M；
Tenda U3 （300M）无线网卡链接Bit Rate 未知。
【此两款USB无线网卡即插即用，链接wifi正常使用没有问题】
使用命令：iw dev wlan0 info  查询发现width只有20MHz
![image](https://user-images.githubusercontent.com/56823170/210069191-65ed5785-acc7-4e58-809b-db4d547d8995.png)
![image](https://user-images.githubusercontent.com/56823170/210069550-22891359-abbe-469c-a9de-d0e51ba12c1c.png)

测试汇总：
![image](https://user-images.githubusercontent.com/56823170/210068541-ebc892ab-a701-4265-870a-562df0460b2b.png)
如上图，Tenda U3 有时候出现1个DataHome无线，有时候出现2个DataHome信号。
排除路由器问题，已替换测试了华为、H3C等多个厂家设备。
单天线 : 20MHz max 65Mbps, 40MHz max 150Mbps
双天线 : 20MHz max 130Mbps, 40MHz max 300Mbps

**Comment by livelier** [comment]
无线连接有很多因素不能满速率连接。特别是2.4G 频道拥挤常常发生，建议你双端都查看一下连接速率，检查环境2.4G是否拥挤，接在Windows也测试一下速率，或者更换Linux驱动尝试。你的单天线130Mbps，双天线270Mbps，看起来已经是40MHz模式，20MHz达不到这个速率。也看一下网卡有没有启动SGI，如果没有SGI速率也会不满。你看我的截图
![image](https://user-images.githubusercontent.com/104582100/210070871-905af887-6b2a-49d3-80a8-6014677f17eb.png)

**Comment by saenice** [comment]
> 无线连接有很多因素不能满速率连接。特别是2.4G 频道拥挤常常发生，建议你双端都查看一下连接速率，检查环境2.4G是否拥挤，接在Windows也测试一下速率，或者更换Linux驱动尝试。你的单天线130Mbps，双天线270Mbps，看起来已经是40MHz模式，20MHz达不到这个速率。也看一下网卡有没有启动SGI，如果没有SGI速率也会不满。你看我的截图，另外你的RTS建议2346 ![image](https://user-images.githubusercontent.com/104582100/210070871-905af887-6b2a-49d3-80a8-6014677f17eb.png) ![image](https://user-images.githubusercontent.com/104582100/210073154-e65d1822-22d0-4094-b195-76da6b403048.png)

感谢回复。
![image](https://user-images.githubusercontent.com/56823170/210074683-9b48b7c6-1436-41bc-9367-ea202a37bd10.png)
#nmcli device wifi list  命令，我理解的是显示wifi信号提供接入速率，并非接入后速率。
上图为M401A 设备使用Tenda W311M (150M) usb 无线网卡状态。
