### ISSUE TITLE
X96MaxPlus Q1 ethernet not working

### ISSUE THREAD

**Issue by chen-xin** [ophub/amlogic-s9xxx-armbian#88]
Thank you for the previous advice,  after flashing ATV system, I can boot my box to armbian, but with no ethernet.

It turns out my box is an X96MaxPlus Q1, which has no 1000M chip on board. ATV and CoreElec can bring up  ethernet and obtain ip address, while armbian(with meson-sm1-x96-max-plus-100m.dtb) complains "Failed to reset the dma", "eth0: stemmac_open: Hw setup failed", etc.
I tried other dtbs, results either same as above or not even able to boot.
Any clue?

**Comment by ophub** [comment]
What are you using in CoreElec? Copy the dtb you used in CoreElec to the armbian system for testing

**Comment by chen-xin** [comment]
Hangs at the starting screen. I looked into the dtbs, suspecting some names in the dtb will be used by bootloader or os, and CoreELEC armbian use different names. Tried to monkey-patch  ethernet node from CoreELEC's dts file and no lucky, cauz I totally have no idea what the settings mean.

**Comment by ophub** [comment]
View FDT=/dtb/amlogic/xxx in the /boot/uEnv.txt file
Copy the dts file of CoreELEC, rename it to this name, put it in this directory, then start it and try it
