### ISSUE TITLE
[Question] Guide to install Armbian on H96 Max+ 4/64

### ISSUE THREAD

**Issue by robertoenr** [ophub/amlogic-s9xxx-armbian#881]
Hi,
I've seen that your proyect has grown and now it supports new devices from Rockchip.
I have a TV Box H96 Max+ with RK3328, 4GB RAM and 64 GB eMMC. 

First of all, can I install your images on this TV Box and will them work?
Second: what steps must I follow?

Thanks in advance.

**Comment by ophub** [comment]
There is currently no firmware for this device.
