### ISSUE TITLE
内核编译问题

### ISSUE THREAD

**Issue by cui8** [ophub/amlogic-s9xxx-armbian#882]
阳了一段时间，今天舒服点了，又继续折腾了。大佬也做好防护。

刚才我想安装编译环境，以前编译网卡驱动编译不成功，可能是环境没安装好。
![image](https://user-images.githubusercontent.com/70044239/210162973-5704d9b9-6e24-43a7-a00c-8047fb6028ca.png)
于是，我参照《内核编译和使用说明》文档。
![image](https://user-images.githubusercontent.com/70044239/210162971-109bf3ce-1b23-4d40-8809-66fc87e90edf.png)
先执行【armbian-kernel -u】，在执行【armbian-kernel -a】，但还是提示错误。
![image](https://user-images.githubusercontent.com/70044239/210162927-5ca94c2e-2ad7-42d0-bf0e-c52a2c87fe63.png)

求大佬说下如何安装交叉编译工具。

**Comment by ophub** [comment]
你的图上全是错误，权力限不对。U盘不要插在安卓系统上，会被修改了权限，在安卓系统重启时再插入。
重要刷一下U盘再操作吧。

**Comment by cui8** [comment]
> 你的图上全是错误，权力限不对。U盘不要插在安卓系统上，会被修改了权限，在安卓系统重启时再插入。 重要刷一下U盘再操作吧。

大佬，想请教一个问题。
每次重新刷armbian系统，我都先线刷回安卓系统，然后在u盘启动armbian，最后写入到闪存。
可以在下次需要重刷armbian系统时，不线刷回安卓系统，直接制作armbian启动盘，u盘启动armbian，最后写入到闪存吗？

**Comment by ophub** [comment]
可以啊，为什么要每次重新刷回安卓系统呢？

只有刷砖了，救砖时才要先刷回安卓系统，平时只要能从U盘启动，直接U盘重刷armbian或者openwrt即可。

**Comment by cui8** [comment]
> 可以啊，为什么要每次重新刷回安卓系统呢？
> 
> 只有刷砖了，救砖时才要先刷回安卓系统，平时只要能从U盘启动，直接U盘重刷armbian或者openwrt即可。

![image](https://user-images.githubusercontent.com/70044239/210165046-88e9331e-aa20-4d63-83a5-5f51d3a21b85.png)
大佬，执行【armbian-kernel -k 5.10.125】命令报错，怎么解决

**Comment by ophub** [comment]
你的盒子访问github.com不通，你`ping github.com`

你上一步的`armbian-kernel -u`更新也没执行成功

**Comment by feicong** [comment]
我也遇到了这个同样的问题

```
[ STEPS ] Start Initializing Variables...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ STEPS ] Start querying the latest kernel version...
[ INFO ] (1) Auto query the latest kernel version of the same series for [ 6.1.3 ]
 [ ERROR ] Failed to query the kernel version in [ github.com/unifreq/linux-6.1.y/main ]
```

`ping github.com`是不通的，但是指定了`export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890`，是可以git clone https://github.com/ophub/amlogic-s9xxx-armbian仓库代码的。

看了一下`armbian-kernel`的代码，主要是`recompile`脚本curl -s读取github仓库时，`https_proxy`没有生效造成的。

我将以下代码加入/opt/kernel/recompile第二行，再运行就可以了。
```
export https_proxy=http://192.168.0.120:7890 http_proxy=http://192.168.0.120:7890 all_proxy=socks5://192.168.0.120:7890
```
