### ISSUE TITLE
Ugoos am6 plus

### ISSUE THREAD

**Issue by Zas09** [ophub/amlogic-s9xxx-armbian#883]
- SOC: s922xj
 - ugoos am6 plus 4gb/32gb

No dtb ,etc for this device .. please make it

**Comment by ophub** [comment]
s922x

/boot/uEnv.txt
meson-g12b-ugoos-am6b-plus.dtb

**Comment by Zas09** [comment]
> s922x
> 
> /boot/uEnv.txt meson-g12b-ugoos-am6b-plus.dtb

Ok thanks, Im about to buy this used box ugoos am6 plus and the owner said its amlogic s922xj not s922x .. i just want to double check .. is it this box really support to boot armbian/openwrt? Sorry if my question is nonsense.
#sorryformybadEnglish

**Comment by ophub** [comment]
Only s922x users have feedback, s922xj is unknown

**Comment by Zas09** [comment]
> Only s922x users have feedback, s922xj is unknown

😭
