### ISSUE TITLE
X96max+ bullseye Wifi is not functioning.

### ISSUE THREAD

**Issue by fari2000** [ophub/amlogic-s9xxx-armbian#885]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: S095x3
 - Model X96max+

**Armbian Version | 系统版本**
KERNEL_VERSION='5.15.80'
PACKAGED_DATE='2022-12-01'

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。
Ethernet connection works fine, but Wifi is not functioning.
Did I choose the wrong dtb?
Thanks for your reply!

more /etc/ophub-release 
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905x3'
FDTFILE='meson-sm1-x96-max-plus-oc.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
ANDROID_UBOOT='/usr/lib/u-boot/hk1box-bootloader.img'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='5.15.80'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
UBOOT_STATUS='no'
AMPART_STATUS='yes'
PACKAGED_DATE='2022-12-01'

**Comment by ophub** [comment]
8822cs在5.15里添加了，但是不一定能用，如果测试不可用就放弃使用无线吧。一直没找到这个驱动的稳定版本。

**Comment by fari2000** [comment]
OK! Thanks for your reply!
