### ISSUE TITLE
Armbian 安装xrdp后 windows10 mstsc 卡屏幕

### ISSUE THREAD

**Issue by saenice** [ophub/amlogic-s9xxx-armbian#886]
![image](https://user-images.githubusercontent.com/56823170/210289860-3b58e4d6-5647-456a-8c42-0d5d03dc018f.png)
armbian-software 安装desktop后，本地使用图形桌面正常。

**Describe the bug | 问题描述**
apt install xrdp 安装xrdp后，windows10 使用mstsc命令访问armbian 输入账号密码后卡在进入系统界面；如下图：
![1672710377251](https://user-images.githubusercontent.com/56823170/210290578-257d0ccc-13a5-4ce7-80ff-187bf7d96d25.jpg)

![1672710347176](https://user-images.githubusercontent.com/56823170/210290549-0e777baf-8d13-41c2-a6f3-4e6eab851cd7.jpg)

![image](https://user-images.githubusercontent.com/56823170/210290689-5b49552a-fd0a-4909-844f-7b4f06f770a5.png)

![21e9b0d8529abf4008c25c39344b7eb](https://user-images.githubusercontent.com/56823170/210291460-c1b12727-903b-45ea-b74c-73b2671dbd8f.png)
如下图：本地armbian系统被mstsc登陆后提示报错。
![image](https://user-images.githubusercontent.com/56823170/210940699-e76aa30d-0d05-401e-8d84-16d2fb292cb5.png)

**Comment by ophub** [comment]
我试了一下远程桌面也没成功，有用过的指导一下

**Comment by wguanwei** [comment]
> 我试了一下远程桌面也没成功，有用过的指导一下

sudo apt install xorgxrdp
安装xorgxrdp后就能正常远程连接了。
我刚开始只安装xrdp后windows下使用远程桌面连接也是一直蓝屏。然后安装xorgxrdp后重启一下xrdp服务就好了。
正常使用amd64处理器的Ubuntu系统安装xrdp时会自动安装xorgxrdp，而现在的使用arm64处理器的armbian系统，只安装xrdp时并不会安装xorgxrdp，导致缺少xorgxrdp。
参考：
如何解决xrdp远程连接ubuntu20.04后黑屏的问题？ - 知乎用户的回答 - 知乎
https://www.zhihu.com/question/404968926/answer/2993457416
