### ISSUE TITLE
大佬6.1版本对WIFI 8822CS 的驱动兼容性 是否有改善

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#888]
大佬6.1版本对WIFI 8822CS 的驱动兼容性 是否有改善？

**Comment by ophub** [comment]
目前6.1内核中没有添加8822cs的驱动，这个驱动来自第三方，以往的内核里也不稳定。

https://github.com/unifreq/linux-6.1.y/blob/main/drivers/net/wireless/realtek/Makefile
