### ISSUE TITLE
ext4-fs error

### ISSUE THREAD

**Issue by ermac500** [ophub/amlogic-s9xxx-armbian#889]
I update regulary to the latest version, but ever since few updates ago, everything dies after some time and I can only see ext4-fs errors.
The box is Mecool m8s pro L
is this a known issue or reflashing is the only hope?

**Comment by ophub** [comment]
I don't understand what you describe.

**Comment by ermac500** [comment]
this:
![1672737857578](https://user-images.githubusercontent.com/7088719/210330047-2f9cf86c-6dc9-4518-adaf-b50d334ac48a.jpg)

Once this starts popping up, nothing works anymore until box reboot.

**Comment by ophub** [comment]
What did you do to get this error?
Now use usb to boot to see if the space is full.

**Comment by ermac500** [comment]
to make it clear armbian is up and running for a a period (could be 5 minutes , could be hours), but then this error apears (without doing anything at all)
the boot media is a SDXC card.

**Comment by ophub** [comment]
You can use the disk scanning tool to check whether the SD card has bad sectors, and repair the damaged blocks.

**Comment by ermac500** [comment]
you mean fdisk ?
I already ran the command with the sdcard attached in a lubunt vm, but it didn't seem to fix anything.
or maybe I didn't to something correct.

**Comment by ophub** [comment]
Check and be reassured. There will be more and more broken blocks if they are not repaired.

**Comment by ermac500** [comment]
can you provide a full command for the check? maybe I didn use the proper command.

**Comment by ophub** [comment]
https://www.helloworld.net/p/4462947362

**Comment by ermac500** [comment]
ok. this resolved my ext4 errors issue, but it seems it messed up something else. 
`root@armbian:~# apt update && apt upgrade
Ign:1 http://ports.ubuntu.com jammy InRelease
Ign:2 https://download.docker.com/linux/ubuntu jammy InRelease
Ign:3 http://ports.ubuntu.com jammy-security InRelease
Ign:4 http://ports.ubuntu.com jammy-updates InRelease
Ign:5 http://ports.ubuntu.com jammy-backports InRelease
Ign:2 https://download.docker.com/linux/ubuntu jammy InRelease
Ign:1 http://ports.ubuntu.com jammy InRelease
Ign:3 http://ports.ubuntu.com jammy-security InRelease
Ign:4 http://ports.ubuntu.com jammy-updates InRelease
Ign:5 http://ports.ubuntu.com jammy-backports InRelease
Ign:2 https://download.docker.com/linux/ubuntu jammy InRelease
Ign:1 http://ports.ubuntu.com jammy InRelease
Ign:3 http://ports.ubuntu.com jammy-security InRelease
Ign:4 http://ports.ubuntu.com jammy-updates InRelease
Ign:5 http://ports.ubuntu.com jammy-backports InRelease
Err:1 http://ports.ubuntu.com jammy InRelease
  Could not resolve 'ports.ubuntu.com'
Err:2 https://download.docker.com/linux/ubuntu jammy InRelease
  Could not resolve 'download.docker.com'
Err:3 http://ports.ubuntu.com jammy-security InRelease
  Could not resolve 'ports.ubuntu.com'
Err:4 http://ports.ubuntu.com jammy-updates InRelease
  Could not resolve 'ports.ubuntu.com'
Err:5 http://ports.ubuntu.com jammy-backports InRelease
  Could not resolve 'ports.ubuntu.com`

**Comment by ophub** [comment]
网络不通

**Comment by ermac500** [comment]
network issue out of the blue?
on the same network I can ping ports.ubuntu.com with no issues. the issue is only in the armbian system.
![image](https://user-images.githubusercontent.com/7088719/210961562-60d53efa-f426-4052-bb23-95b00822fc06.png)

**Comment by ophub** [comment]
```
ping github.com
cat /etc/ophub-release
```

**Comment by ermac500** [comment]
ping github.com
ping: github.com: Name or service not known
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s912'
FDTFILE='meson-gxm-q201.dtb'
UBOOT_OVERLOAD='u-boot-s905x-s912.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
FAMILY='meson-gxm'
BOARD='s912-m8s'
KERNEL_VERSION='5.15.86'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='usb'
PACKAGED_DATE='2022-11-08'
KERNEL_BRANCH='stable'

**Comment by ophub** [comment]
ping: github.com: Name or service not known, Unable to update because the network is unavailable.

**Comment by ermac500** [comment]
as mentioned. pinging from another device connected to the same router works without any issues. 
any way to reset all network related services on armbian?

**Comment by ophub** [comment]
/etc/network/interfaces
