### ISSUE TITLE
X96Maxplus 4/64 audio output not working please help

### ISSUE THREAD

**Issue by Evgeniy-18** [ophub/amlogic-s9xxx-armbian#89]
Привет, установил Armbian_22.02.0_Aml_s905x3_bullseye_5.15.15_2022.01.19.1938.img.gz
aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: X96MAX [X96-MAX], device 0: fe.dai-link-0 (*) []
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: X96MAX [X96-MAX], device 1: fe.dai-link-1 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: X96MAX [X96-MAX], device 2: fe.dai-link-2 (*) []
  Subdevices: 1/1
  Subdevice #0: subdevice #0
аудио не работает, помогите настроить, нужны инструкции как включить звук, спасибо

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/75#issue-1103723451

Он включен по умолчанию, вы можете использовать

**Comment by eonegin83** [comment]
> 

Я полный нуб, подскажите как воспроизвести мелодию.

**Comment by fooy** [comment]
so is it working or not , if yes,  does it also mean hk1 box can have working BT and audio jack .

**Comment by ophub** [comment]
Каждое устройство отличается, а некоторые устройства с одинаковым названием имеют разные чипы.Вы можете войти через armbian-config для просмотра и включения

**Comment by Evgeniy-18** [comment]
> 

Не могли-бы мне помочь, вот моя приставка

![IMG_20220119_194636](https://user-images.githubusercontent.com/82999271/151654345-6b165fa5-a3b0-44a6-9467-32deb5b79acb.jpg)
![IMG_20220119_194631](https://user-images.githubusercontent.com/82999271/151654347-a38b8428-278c-4213-90a4-8f36fa6e9733.jpg)
![IMG_20220119_194656](https://user-images.githubusercontent.com/82999271/151654348-269873e3-e91d-49b7-88fe-947058861560.jpg)
![IMG_20220119_194640](https://user-images.githubusercontent.com/82999271/151654349-8896b51a-db53-4c8c-b239-eb52b98afbed.jpg)

**Comment by Evgeniy-18** [comment]
Armbian-config  - System
![image832](https://user-images.githubusercontent.com/82999271/151655990-234b20b5-eef0-4888-8561-beb2c8702645.png)

**Comment by Evgeniy-18** [comment]
> Каждое устройство отличается, а некоторые устройства с одинаковым названием имеют разные чипы.Вы можете войти через `armbian-config` для просмотра и включения

Подскажите , я не нахожу пункта System

**Comment by ophub** [comment]
Поддерживаемый драйвер включен по умолчанию, если нет, то нет.Попробуйте посмотреть есть ли звук в hdmi.

**Comment by eonegin83** [comment]
> Поддерживаемый драйвер включен по умолчанию, если нет, то нет.Попробуйте посмотреть есть ли звук в hdmi.

Да Вы правы звук присутствует на hdmi, на аналоговому выходе нет, спасибо за помощь.

**Comment by ophub** [comment]
Хорошо, последние два года чипов не хватало, а сетевые карты разных партий x96max-боксов менялись.Некоторые пользователи сети купили версию V5.1 X96 Max+, известную как гигабитная сетевая карта, но загнать не получается.После разборки и осмотра сетевую карту RTL8211F Чип заменили на IP1001M, хотя в системе Android он еще гигабитный, но магистральное ядро ​​в настоящее время не загнать. Так много раз вам приходится проверять чип-тест самостоятельно.
