### ISSUE TITLE
WIFI输入密码死机

### ISSUE THREAD

**Issue by 84864797** [ophub/amlogic-s9xxx-armbian#891]
Armbian_23.02.0_amlogic_s905x_jammy_5.15.85_server_2022.12.28

WIFI芯片RTL8189   

用5.9内核的固件 查看加载的驱动8189fs 能正常使用wifi

用大佬的5.15内核的 查看加载的驱动 也是8189fs  但是输入WIFI密码确认后， 设备就死机了。

这是恩山上大佬的5.9内核的固件
链接:https://pan.baidu.com/s/1ZEwroqDhMjT1_g_DnFY9oQ
密码: pv4o

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek

https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek

我看了下上游内核仓库，这个驱动是从第三方添加的，如果不稳定就放弃使用吧，使用5.9也挺好，还有很多人使用4.x内核的。

**Comment by 84864797** [comment]
> https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek
> 
> https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek
> 
> 我看了下上游内核仓库，这个驱动是从第三方添加的，如果不稳定就放弃使用吧，使用5.9也挺好，还有很多人使用4.x内核的。

大佬 看到报错信息了
Message from syslogd@armbian at Jan  5 13:42:21 ...   │               │             │
 kernel:[   97.692035] Internal error: Oops: 96000021 [#1] PREEMPT SMP

**Comment by livelier** [comment]
@84864797 
你的问题与我相似，我的S905X3 无线mt7663s和ap6255 在近期更新的内核版本使用无线后会失去连接之后load 100+ 直至增长至死机 出现问题的内核系列 5.15.y 6.0.y 6.1.y 在近期更新版本，早些时候的更新没有问题。我的临时解决办法，禁止无线加载驱动即可解决死机问题。这可能是无线驱动与内核有某种“冲突”导致。目前我已经退回使用5.10.y内核，这个内核我的两款盒子目前可以正常使用无线。

@ophub o大，请教一下，在使用 actions 编译内核时，比如5.15.86是最新版本。如果我指定版本号为5.15.60这样编译出来的版本是5.15.60还是最新的5.15.86版本？

**Comment by ophub** [comment]
默认使用最新的内核，使用固定版本kernel_auto: false

**Comment by livelier** [comment]
好的，了解了
