### ISSUE TITLE
armbian-install 脚本优化以支持一个USB设备可以部署不同型号的设备

### ISSUE THREAD

**Issue by SSSSoiphon** [ophub/amlogic-s9xxx-armbian#892]
**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
当不使用Mainline u-boot时，armbian-install会使用备份的uboot重写emmc的uboot分区。
备份脚本里多了判断${MYBOX_UBOOT}是否存在的条件，这导致用同一个USB设备写不同设备时，会存在写入uboot错误的情况。
MYBOX_UBOOT="/usr/lib/u-boot/mybox-bootloader.img"
if [[ ! -f "${MYBOX_UBOOT}" ]]; then
        echo -e "${INFO} Start backup default bootloader."
        dd if="${DEV_EMMC}" of=${MYBOX_UBOOT} bs=1M count=4 conv=fsync
fi

建议：
去掉这个判断操作，或者增加else条件, 重命名现有的文件，并备份当前设备的uboot。

提这个需求的原因：
我用同一个U盘，写M311-1a和ZXV10 B863AV3.2-M的EMMC都没有问题，但是写江苏版M401A的EMMC后（306），就变砖了。
把/usr/lib/u-boot/mybox-bootloader.img这个文件删了，再写江苏版M401A的EMMC后（306）就正常了。

**Comment by ophub** [comment]
说的很对呢，安排。
