### ISSUE TITLE
视频解码是否可以使用ARM Mali 系列的GPU

### ISSUE THREAD

**Issue by intxzt** [ophub/amlogic-s9xxx-armbian#894]
5.x or 6.x的内核是否存在某个模块可以调度ARM Mali 系列的GPU

**Comment by Scirese** [comment]
Panfrost 驱动可以驱动大部分 Amlogic 芯片的 GPU, 但性能不高.
视频解码只有mpv播放器能在某种程度上支持, 其他软件完全不支持, 只能软解.

**Comment by intxzt** [comment]
有没有API支持自行扩展呢

**Comment by Scirese** [comment]
没有
