### ISSUE TITLE
s905L3安装armbian时找不到eMMC

### ISSUE THREAD

**Issue by changebalabala** [ophub/amlogic-s9xxx-armbian#896]
九联unt402a U盘可以启动
报错：[ ERROR ] The eMMC storage not found in this device!

**Comment by ophub** [comment]
lsblk

**Comment by changebalabala** [comment]
@ophub 
![Uploading 6CJ~[AULUQ9PYCM{GDQLL@L.png…]()

**Comment by changebalabala** [comment]
@ophub 
![6CJ~ AULUQ9PYCM{GDQLL@L](https://user-images.githubusercontent.com/42791517/210771359-23100438-adbe-49ff-a180-cede3378e2f9.png)

**Comment by ophub** [comment]
emmc是mmcblk

你的盒子没有，是别的存储介质

**Comment by ophub** [comment]
ls /proc/mtdinfo
ls /proc/mtd

**Comment by changebalabala** [comment]
![TEA5~4 3A)6JR(7I_$ }GV](https://user-images.githubusercontent.com/42791517/210780518-632e403e-76da-4a25-a06a-25b55bf19448.png)

**Comment by ophub** [comment]
cat /proc/mtdinfo

**Comment by changebalabala** [comment]
```
no such file or directory
```

**Comment by ophub** [comment]
你的盒子是什么存储介质呢？

**Comment by changebalabala** [comment]
![XXT)0(M~LC8{}S4OV{SDVQ3](https://user-images.githubusercontent.com/42791517/210784829-be33d7e1-bd29-46ac-8432-32bb44032c96.png)
![IMG_20230105_205347](https://user-images.githubusercontent.com/42791517/210784853-1dbe60db-4e50-41de-a6fe-98dca5766ad9.jpg)
查了一下供应商产品介绍，按理说是emmc，但是就是识别不到

**Comment by changebalabala** [comment]
电视刷入了安卓系统，但是armbian似乎挂载不了emmc

**Comment by livelier** [comment]
看一下安卓dtb存储部分，NAND有没有开启。如果是开启的多半可能是NAND。
康佳的子公司，也可以问问客服😂 https://www.kowin.com.cn/

**Comment by changebalabala** [comment]
> 看一下安卓dtb存储部分，NAND有没有开启。如果是开启的多半可能是NAND。 康佳的子公司，也可以问问客服😂 https://www.kowin.com.cn/ 或者你进入安卓U-BOOT模式查一下，也可以确定，但大多是安卓不能进入U-BOOT模式。

怎么进入呢，小白不是很懂

**Comment by livelier** [comment]
o大仓库里有反编译dtb文件的说明，你看一下 [Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents)

或者把你盒子的安卓dtb文件传上来。

**Comment by changebalabala** [comment]
@livelier 安卓的dtb怎么获取呢，用解包工具解包安卓的img文件吗

**Comment by livelier** [comment]
方法1、[Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md) 第 12.11.1 章节
方法2、解包你盒子可以正常使用的安卓img或zip都可以找到。

**Comment by changebalabala** [comment]
是meson1.dtb这个文件吗 @livelier

**Comment by livelier** [comment]
是的，不同安卓版本，固件中的dtb文件名字有些区别。

**Comment by changebalabala** [comment]
[meson1.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10358372/meson1.zip)
另外我这盒子BootLoader似乎是锁着的，我把bootleader.partition导入hxd看asc是乱码，这有什么影响吗

**Comment by livelier** [comment]
你的盒子可能不是eMMC

![image](https://user-images.githubusercontent.com/104582100/210989889-4bce7b87-51e3-4d35-b832-119b542d36fc.png)

[Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md) o大辛苦为大家写的，你看一次，很多问题就不是问题了。

**Comment by livelier** [comment]
你的盒子可能不是eMMC

![image](https://user-images.githubusercontent.com/104582100/210989889-4bce7b87-51e3-4d35-b832-119b542d36fc.png)

[Armbian 使用文档](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md) 这是o大 @ophub 辛苦为大家写的，你认真看一下，很多问题就不是问题了。

**Comment by yang-yang-NO-1** [comment]
> 九联unt402a U盘可以启动 报错：[ ERROR ] The eMMC storage not found in this device!

@changebalabala 哥们，能不能分享一下这个盒子能启动armbian的安卓固件
