### ISSUE TITLE
ZTE-B863AV3.1-M2支持吗？S905l3a_b

### ISSUE THREAD

**Issue by gxmd** [ophub/amlogic-s9xxx-armbian#897]
这个盒子支持吗？和ZTE-B863AV3.2-M就差几个字目，处理器应该是S905l3a_b

**Comment by ophub** [comment]
tx3和hk1这2个盒子差的也不多，就差3个字，而且还都是s905x3，但是居然不能通用一个dtb和u-boot。

所以你差几个字母，这有没差别从字母上也无法给你答复。
