### ISSUE TITLE
Splash screen And wifi issue on X96 Mini Tv box

### ISSUE THREAD

**Issue by suyog44** [ophub/amlogic-s9xxx-armbian#899]
**Device Information**
 - SOC: S905W 1G Ram 8G Nand Flash
 - Model X96 Mini Tv Boc

**Armbian Version**
 - Kernel Version: 5.15
 - Release: focal 

**unable to boot with splash screen**
I was successfully booted Armbian on my x96 mini tv box , but I wants to enable boot splash instead kernel log messages.
Also wifi sv5016p is not working but driver present in /usr/lib/firmware, any solution to activate it. 

Regards
B suyog

**Comment by ophub** [comment]
does not support wireless

**Comment by grunwald63** [comment]
Anyone figured out the boot splash thing??
I heard something about PLYMOUTH but nothing works....

take care
h
