### ISSUE TITLE
Bullseye on USB Updated to kernel 5.16.3-flippy-69+ from 5.15.15-flippy-69+ Kernel Panic -- Stability Issue

### ISSUE THREAD

**Issue by JFLim1** [ophub/amlogic-s9xxx-armbian#90]
Hi @ophub,

Device: Beelink GT King Pro Revision A
u-boot.ext: u-boot-gtkingpro-rev-a.bin (but ophub-release identify as u-boot-gtkingpro.bin)
dtb: meson-g12-gtking-pro.dtb
Storage: USB SanDisk 3.2Gen

```

jfl@armbian:~$ cat /etc/ophub-release
VERSION_CODENAME='bullseye'
FDTFILE='meson-g12b-gtking-pro.dtb'
U_BOOT_EXT='1'
UBOOT_OVERLOAD='u-boot-gtkingpro.bin'
MAINLINE_UBOOT='/lib/u-boot/gtkingpro-u-boot.bin.sd.bin'
ANDROID_UBOOT=''
SOC='s922x'
PACKAGED_DATE='2022-01-16'
KERNEL_VERSION='5.16.3'
K510='1

```
Just a feedback.  I have been running Armbian_22.02.0_Aml_s922x_bullseye_5.15.15_2022.01.16.2138.img.gz image for a week and it has been very stable.

Today I updated to newly available kernel 5.16.3-flippy-69+ with this command:
`
sudo armbian-update 5.16.3`

And it updated successfully and automatically restarted but did not reboot successfully. Basically Power Off but Power LED still "ON" (light up).

Power Cycle and it tried to boot up but kernel panic during booting process.

Power Cycle again and this time boot up successfully.  But I notice in the "dmesg" there is this unusual message:
```

[    0.000000] OF: fdt: Reserved memory: failed to reserve memory for node 'secmon@5000000': base 0x0000000005000000, size 3 MiB
[    0.000000] OF: fdt: Reserved memory: failed to reserve memory for node 'secmon@5300000': base 0x0000000005300000, size 32 MiB
```
This is the first time I notice this:
`
[    0.000000] OF: fdt: Reserved memory: failed to reserve memory for node 'secmon@5300000': base 0x0000000005300000, size 32 MiB`

After this run "glmark2-es2-wayland" kernel panic - uptime 15:11 minutes

![image](https://user-images.githubusercontent.com/75384411/151546093-0b06b68a-b5e8-4d05-90f9-18e3c91454a6.png)

Looks like kernel 5.16.3-flippy-69+ is NOT stable.  Wonder other users also facing this.

**Comment by ophub** [comment]
Change the values of `UBOOT_OVERLOAD` and `FDTFILE` in `/etc/ophub-release` to the file name of the rea you use. Because when updating the kernel, the corresponding file will be copied according to this record.

**Comment by JFLim1** [comment]
> Change the values of `UBOOT_OVERLOAD` and `FDTFILE` in `/etc/ophub-release` to the file name of the rea you use. Because when updating the kernel, the corresponding file will be copied according to this record.

You mean I edit /etc/ophub-release :

`sudo nano /etc/ophub-release`

to relflect like this:
```

VERSION_CODENAME='bullseye'
FDTFILE='meson-g12b-gtking-pro.dtb'
U_BOOT_EXT='1'
UBOOT_OVERLOAD='u-boot-gtkingpro-rev-a.bin'
MAINLINE_UBOOT='/lib/u-boot/gtkingpro-u-boot.bin.sd.bin'
ANDROID_UBOOT=''
SOC='s922x'
PACKAGED_DATE='2022-01-16'
KERNEL_VERSION='5.16.3'
K510='1'


```



> The new 5.16 version of the kernel will wait for him to update for a while, it may require a lot of feedback at the beginning

Noted.  Hopefully the new kernels will also be stable.

Thank you for your's and flippy's support.

**Wish You and Familly A Happy Properous New Year!**
Stay safe and healthy.

**Comment by ophub** [comment]
Thank you and wish you a happy new year, good health and all the best.

**Comment by JFLim1** [comment]
Hi @ophub,
May I inquire what (uEnv.txt)

`APPEND=.....cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1`

the above are for?  Trying to understand the system better.  Thank you.

**Comment by JFLim1** [comment]
Hi @ophub,

Just an update on Armbian_22.02.0_Aml_s922x_bullseye_5.15.15_2022.01.16.2138.img.gz upgrade from kernel 5.15.15 to kernel 5.16.3.  After the two inital kernel panics as mentioned above, this image had run smoothly seen then without any kernel panic so far.  

Typically operate it for 3 - 5 hours sessions.  But had also run it up to 12 hours session twice.  So far so good.  No idea what causes the initial kernel panic and why now seems stable.  

Current uptime more than 8 hours.  Thanks.

**Comment by ophub** [comment]
OK. If you test the 5.16 kernel series, use this series all the time.

**Comment by JFLim1** [comment]
Hi @ophub,
> Current uptime more than 8 hours. Thanks.

Spoke too fast, system freeze at around 11 hours of uptime.  I left the terminal for 20 minutes and when I turn on the monitor again, a message said "going to suspension soon due to inactivities" or something to this affect but it is a total system freeze, mouse keyboard did not work.  Ctrl+Alt+F1 did not work.  HTOP froze.

Will update to kernel 5.16.4 to see whether it have same stability issue.

**Comment by ophub** [comment]
I haven't seen the locking phenomenon you mentioned, under what circumstances will it appear? Post a `screenshot` of you.

My box is always on, and I test and install a new kernel every week. I have never seen a situation where I can't connect to the Internet.

**Comment by JFLim1** [comment]
> I haven't seen the locking phenomenon you mentioned, under what circumstances will it appear? Post a `screenshot` of you.

Unfortunately, this last system freeze (or 3rd system freeze) forgot to take a screenshot.  It happen according to the message was the system is going into suspension due to inactivity.  The current system setting:

"Power Saving Options: System Blank 15 minutes"

But instead of suspension it looks like total system freeze.  Mouse and keyboard not active/responding and HTOP froze.

The earlier two kernel panic as mentioned above was right after kernel switch to 5.16.3 during first power cycle and kernel panic during booting process and another during running "glmark2-es2-wayland".

Device: Beelink GT King Pro Revision A
Distro: Debian Bullseye
Desktop Environment: Gnome 41 from Unstable Branch
Mesa: 21.3.5
u-boot.ext: u-boot-gtkingpro-rev-a.bin
dtb: meson-g12-gtking-pro.dtb
Storage: USB SanDisk 3.2Gen

In future if and when kernel panic/system freeze strikes, will take screenshot.  Just updated kernel to 5.16.4-flipply-69+ from 5.16.3-flippy-69+ to see whether stability improved.

```
[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd034]
[    0.000000] Linux version 5.16.4-flippy-69+ (root@univm25) (Ubuntu clang version 13.0.0-9, Ubuntu LLD 13.0.0) #28 SMP PREEMPT Sat Jan 29 21:18:12 CST 2022
[    0.000000] Machine model: Beelink GT-King Pro

```

> My box is always on, and I test and install a new kernel every week. I have never seen a situation where I can't connect to the Internet.

Currently using Gnome 41 DE.  So far ethernet or wifi is always available when the system boot up.

What kernel series are you on 5.10.y, 5.15.y or 5.16.y?

**Comment by ophub** [comment]
I use 5.10 kernel

**Comment by JFLim1** [comment]
> I use 5.10 kernel

Thanks.  I suppose 5.10.y and 5.15.y being LTS will be more stable.

Read that Armbian will be switching "Current" to 5.15.y and "Edge" to 5.16.y.

Is Aml_S9xxx_Armbian also switching to 5.15.y-flippy and 5.16.y-flippy?

**Comment by ophub** [comment]
Last month, I set the default firmware to the 5.4/5.15 kernel, but it was reflected that 5.15 was more unstable, so I returned to the 5.10 kernel. Wait for the official to adapt for a while and then switch back to version 5.15.

Several series of kernels can be switched freely through armbian-update, and can be replaced if you use 5.15/5.16 to be more stable.
