### ISSUE TITLE
晶晨S905L2

### ISSUE THREAD

**Issue by IAFWMC** [ophub/amlogic-s9xxx-armbian#900]
咪咕盒子MGV2000JL S905L2 1G+8G

Armbian的镜像文件是Armbian_23.02.0_amlogic_s905l2_jammy_5.15.86_server_2023.01.05.img.gz

U盘启动时和安装至emmc后都无法连接以太网和WiFi

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/648

比较一下

**Comment by IAFWMC** [comment]
> #648
> 
> 比较一下

我这个连了网线但是盒子没有IP地址，而且去网关后台查看也没有连接到有线网络的设备，两个USB口正常,HDMI接口也正常

**Comment by ophub** [comment]
复制uboot试试

**Comment by IAFWMC** [comment]
> 复制uboot试试

啊？我不太懂，可以麻烦您把操作步骤发出来吗？

**Comment by ophub** [comment]
cat /etc/ophub-release

**Comment by IAFWMC** [comment]
输入后提示这个
![QQ图片20230106200830](https://user-images.githubusercontent.com/122092701/211010040-67c92c10-f6b8-4565-92d9-e35a8039a5b9.jpg)

**Comment by IAFWMC** [comment]
我刚刚连着网线输入命令ifconfig显示出来的ip地址是169.254.12.60，不是像Windows这些设备的192.168.xxx.xxx

**Comment by ophub** [comment]
```
cat /etc/ophub-release
cat /boot/uEnv.txt
```

**Comment by IAFWMC** [comment]
> 有空格
> 
> ```
> cat /etc/ophub-release
> cat /boot/uEnv.txt
> ```

好的，我依次输入了，输入完之后需要重启吗？

**Comment by ophub** [comment]
截图发上来，我看一下自己的配置，然后才能知道复制哪个

**Comment by IAFWMC** [comment]
噢噢，好的好的
![1673010549388](https://user-images.githubusercontent.com/122092701/211018718-d3e3c773-6f1a-40dd-83d3-58183ee6b405.jpg)

**Comment by IAFWMC** [comment]
> 这是看你的配置，截图发上来，我看一下自己的配置，然后才能知道复制哪个

找到了吗？

**Comment by ophub** [comment]
```
cd /boot
cp -f u-boot-s905x-s912.bin u-boot.emmc
chmod +x u-boot.emmc
sync && reboot
```

**Comment by IAFWMC** [comment]
> ```
> cd /boot
> cp -f u-boot-s905x-s912.bin u-boot.emmc
> chmod +x u-boot.emmc
> sync && reboot
> ```

我按您的依次输入了，它现在在不断的重启

**Comment by IAFWMC** [comment]
它现在不能正常启动了断电重启还是在不断重启的界面，我刚刚插上U盘进入了U盘的Armbian
一拔掉U盘就又开始不断重启了

**Comment by IAFWMC** [comment]
但是网关的管理界面读取到网线连接的盒子，但是盒子现在在倒计时5秒的界面倒计时结束后就重启又开始倒计时

**Comment by ophub** [comment]
看来你和之前用户的盒子不一样，恢复安卓系统看电视吧。

**Comment by chenhao97** [comment]
> > ```
> > cd /boot
> > cp -f u-boot-s905x-s912.bin u-boot.emmc
> > chmod +x u-boot.emmc
> > sync && reboot
> > ```
> 
> 我按您的依次输入了，它现在在不断的重启

我个人经验觉得你这个问题和盒子的安卓系统有关。我是九州代工的这个盒子，用另外那个人的s905l的安卓固件就有线可用。换成别的安卓固件有线均无法使用

**Comment by ophub** [comment]
你是什么盒子，分享一下你的安卓系统的下载链接。

**Comment by chenhao97** [comment]
> 

是说我的么？我的是mgv2000_jz_iptv_hunan，s905l2芯片。用的就是你kernel里面那个mgv2000安卓固件，只有这个安卓固件有线正常，我试了其他几个安卓固件，都没有办法联网。

**Comment by ophub** [comment]
@IAFWMC
你比较下你的盒子，如何参数一样的话刷这个安卓系统试试

**Comment by chenhao97** [comment]
> 

这个安卓固件会导致安卓下的wifi用不了，虽然armbian那边有线能用了。就很尴尬。

**Comment by ophub** [comment]
wifi刷哪个安卓系统固件也用不了，在主线内核里没那个芯片的驱动，armbian无法使用这个盒子的无线。

**Comment by chenhao97** [comment]
> wifi刷哪个安卓系统固件也用不了，在主线内核里没那个芯片的驱动，armbian无法使用这个盒子的无线。

我是说这个安卓固件，在安卓下也没有无线用

**Comment by chenhao97** [comment]
在4PDA论坛找到一个俄国人修改的固件
就是依旧在安卓系统下没有无线
我个人觉得比别的国产固件好点，界面看起来干净点
https://cloud.mail.ru/public/hXQ4/3sj8Shtb7
本人机型mgv2000_jz_iptv_hunan，s905l2芯片。

**Comment by leitong0418** [comment]
> > 
> 
> 是说我的么？我的是mgv2000_jz_iptv_hunan，s905l2芯片。用的就是你kernel里面那个mgv2000安卓固件，只有这个安卓固件有线正常，我试了其他几个安卓固件，都没有办法联网。

能否发一下固件链接，找了很久没找到，我的也是九洲代工的MGV2000，目前盒子在安卓系统下有线和wifi均正常，U盘启动armbian一切正常，尝试了很多armbian版本和dtb，有线均无法获取到IP，网口灯都不亮，用命令能看到eth0，但是无IP
