### ISSUE TITLE
hg680p

### ISSUE THREAD

**Issue by aoxo2022** [ophub/amlogic-s9xxx-armbian#901]
-Armbian_23.02.0_amlogic_s905x_jammy_5.15.86_server_2023.01.05.img
-hg680p root
-sd card 16gb class 10
-rufus

![Untitled](https://user-images.githubusercontent.com/101029515/211042738-195cd44c-105a-4154-a97f-66b8e63a4d7a.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/0aa2f13e5b88c0a138abbf05c73117703f58060c/build-armbian/armbian-files/common-files/etc/model_database.conf#L27

**Comment by aoxo2022** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/0aa2f13e5b88c0a138abbf05c73117703f58060c/build-armbian/armbian-files/common-files/etc/model_database.conf#L27
> 
> try 5.4 kernel

How to change it?

**Comment by ophub** [comment]
rebuild

**Comment by aoxo2022** [comment]
at armbian-config?

**Comment by ophub** [comment]
If you can log in, replace the kernel directly.
armbian-update 5.4.228

**Comment by aoxo2022** [comment]
i can login
not yet use "armbian update 5.4.228"

always like  this
![2](https://user-images.githubusercontent.com/101029515/211132855-c578c451-56c7-4b45-901d-300095a9eb81.jpg)
![3](https://user-images.githubusercontent.com/101029515/211132868-4ddc7aa8-96c8-4925-81da-19c9742cdf6b.jpg)

**Comment by aoxo2022** [comment]
> If you can log in, replace the kernel directly. armbian-update 5.4.228

Must connet internet?

**Comment by ophub** [comment]
need

**Comment by aoxo2022** [comment]
> need

when connect to wifi (at armbian-config)
always like this sir

![4](https://user-images.githubusercontent.com/101029515/211181148-6282e952-3554-4464-824b-1566648c472c.jpg)

i use internal wifi hg680p
i try usb wifi adapter wn722 v1, still like that

**Comment by ophub** [comment]
You can fork compile a 5.4/5.10

**Comment by tjengbudi** [comment]
hello,
i used downloaded lates image with lunar and 5.15 kernel. and the wifi log like at above always show. how i make it dissappeared?
i try using kernel 5.4 and 5.10 with armbian-update -k 5.4/10 command. after reboot it still show up.

any clue for this?
