### ISSUE TITLE
hi！ O big，日常更新日志在哪里看？

### ISSUE THREAD

**Issue by urenai** [ophub/amlogic-s9xxx-armbian#905]
我一直在关注armbian
我想第一时间知道omv的修复消息。

**Comment by ophub** [comment]
这个可以使用官方提供的一键脚本安装测试，最近我没测试。

**Comment by urenai** [comment]
那有没有更新日志？

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commits/main

更新日志从commits里面可以看到

**Comment by urenai** [comment]
OK
