### ISSUE TITLE
电源指示灯关闭

### ISSUE THREAD

**Issue by OwnerCM** [ophub/amlogic-s9xxx-armbian#906]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model：魔百盒 M401A

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.86
 - Release: bullseye

**Describe the bug | 问题描述**
想请教一下o大或其他大佬，M401A的盒子能否通过系统配置关闭电源指示灯，不得不说，这个大路灯太亮了，晚上都刺眼。

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/commit/12c78c6a2f70323f240d45872f475fcc4bd136f7

这是给章鱼星球加三个不同颜色的灯。不要是把默认状态禁了，你参照修改你用的dtb

**Comment by OwnerCM** [comment]
> https://github.com/unifreq/linux-5.15.y/blob/ef1cd254fc61d8ec9b95eea8967c02e49c156cf2/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-m401a.dts#L29
> 
> 三个不同颜色的灯。不要是把默认状态禁了，你参照修改你用的dtb

leds {
		compatible = "gpio-leds";

		green_led {
			label = "green";
			gpios = <&gpio_ao GPIOAO_5 GPIO_ACTIVE_HIGH>;
			linux,default-trigger = "usb-host";
		};

		blue_led {
			label = "blue";
			gpios = <&gpio_ao GPIOAO_6 GPIO_ACTIVE_HIGH>;
			//linux,default-trigger = "mdio_mux-0.2009087f:00:link";
			linux,default-trigger = "mmc2";
		};

		red_led {
			label = "red";
			gpios = <&gpio_ao GPIOAO_9 GPIO_ACTIVE_HIGH>;
			**default-state = "off";**
		};

	};
感谢O大的回复，直接进入系统修改dtb文件吗？是否需要重新编译？如上代码是否OK？

**Comment by ophub** [comment]
`default-state = "off";`

`sudo ./recompile -p dtbs -k5.15.86`

可以在线actions或者本地编，几分钟


https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

**Comment by OwnerCM** [comment]
> `default-state = "off";`
> 
> `sudo ./recompile -p dtbs -k5.15.86`
> 
> 可以在线actions或者本地编，几分钟
> 
> https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/compile-kernel

好的，谢谢O大，暂时我就不编译了，还是使用您的原版吧！方便后续升级

**Comment by ophub** [comment]
悄悄告诉你一个秘密：口香糖

**Comment by livelier** [comment]
@OwnerCM 也可以这样尝试一下

```
# leds all off
bris=0
cd /sys/class/leds/ && leds=$(ls) 
for rgbs in ${leds}; do echo ${bris} > ${rgbs}/brightness; done
```

**Comment by OwnerCM** [comment]
> 也可以这样尝试一下

感谢回复，我是一个linux小白，说实话你这段代码我都不知道改哪里，见笑了

**Comment by ophub** [comment]
在你的ssh登录的界面里，输入命令的地方，逐行复制粘贴回车，执行完了看看led灯关闭了没。

**Comment by OwnerCM** [comment]
> 在你的ssh登录的界面里，输入命令的地方，逐行复制粘贴回车，执行完了看看led灯关闭了没。
执行结果如下：
Last login: Mon Jan  9 15:36:53 2023 from 192.168.31.115
armbian:~:# # leds all off
armbian:~:# bris=0
armbian:~:# cd /sys/class/leds/ && leds=$(ls)
armbian:leds:# for rgbs in ${leds}; do echo ${bris} > ${rgbs}/brightness; done
zsh: no such file or directory: net_led\npower_led\nremote_led/brightness
armbian:leds:#

**Comment by ophub** [comment]
`ls /sys/class/leds`

看下结果

**Comment by OwnerCM** [comment]
![image](https://user-images.githubusercontent.com/22722811/211292625-eb05efdf-3469-4f4e-b13a-046337ae3476.png)

**Comment by OwnerCM** [comment]
修改后灯变成红色了，下面是修改的结果
![image](https://user-images.githubusercontent.com/22722811/211294189-1fe100cd-0a67-4385-bb74-03542c54489c.png)

**Comment by livelier** [comment]
正常情况执行命令后，路径 /sys/class/leds/ 下关联的led会全部熄灭。

执行命令后有剩余未关闭的led。说明他们没有在这里/sys/class/leds/关联。也可能是“存粹”的通电指示灯，无法在系统下关闭。

如果是“存粹”的通电指示灯他们是无法关闭的，
这种时候可以采纳以下方法之一。
物理遮挡法：遮挡led
焊接移除法：移除或更换弱光led
暴力拆解法：使用老虎钳捏碎led并把其引脚折断。
