### ISSUE TITLE
Request support for X96 Max Plus 100W

### ISSUE THREAD

**Issue by trvqhuy** [ophub/amlogic-s9xxx-armbian#909]
I have the W522A radio module on my X96 Max Plus 100W board.

I found some information.
The W552a is an Fn-Link K255B-SR.
The Fn-Link K255B-SR is an Amlogic W155S1 chip, with the following datasheet:
https://usermanual.wiki/HUNAN-FN-LINK-TECHNOLOGY/K255B-SR.User-Manual-5353157.pdf

I found two github for the sources of this module:
https://github.com/CoreELEC/w1-aml
https://github.com/adeepn/w1-aml

Tutorials for W155S1
https://blog.csdn.net/zhaojy5453/article/details/115484201

I hope it can help you, thanks for your work.

**Comment by ophub** [comment]
/boot
try `meson-sm1-x96-air.dtb` or `meson-sm1-a95xf3-air.dtb`
copy `u-boot-x96maxplus.bin` to `u-boot.ext` and `u-boot.emmc`

**Comment by trvqhuy** [comment]
Hi @ophub , I have tried 2 dtb files above, but none of them works.

I can install and boot normally but when I go to "Network" from "armbian-config" command, the screen always shown as the image below:

![image](https://user-images.githubusercontent.com/88963333/211577758-6dec9a29-9252-4980-a1f9-b2e2776acc38.png)

**Comment by ophub** [comment]
Which dtb are you using? The wired network is not available, and the IP is not obtained, right?

`ifconfig`

**Comment by trvqhuy** [comment]
> try `meson-sm1-x96-air.dtb` or `meson-sm1-a95xf3-air.dtb`

I've test these 2 files as you'd said.

The wired network works fine with available IP on both dtb files above, but cannot do the "Wifi" config

**Comment by trvqhuy** [comment]
> Which dtb are you using? The wired network is not available, and the IP is not obtained, right?
> 
> ```
> ifconfig
> lsblk
> cat /boot/uEnv.txt
> ```

![image](https://user-images.githubusercontent.com/88963333/211581272-c1eef01d-cc68-42cb-820a-11d00cabec0a.png)

**Comment by ophub** [comment]
The user did not reply halfway through the last test of this box, and has not collected available configurations. You can add configurations after you test that the wired box can be used. For wireless, you need to check whether there is a driver, modify the dtb or add a new dtb.

Did you copy u-boot? Execute the following command screenshot:

```
ls /boot/u-boot*
```

**Comment by trvqhuy** [comment]
Yes I've copied the u-boot. Here is the screenshot:

![image](https://user-images.githubusercontent.com/88963333/211582490-cac073d6-0cd2-4083-8a47-2427b1456c7d.png)

**Comment by ophub** [comment]
Your wireless/bluetooth chip is W522A?

**Comment by trvqhuy** [comment]
> Your wireless/bluetooth chip is W522A?

Yes sir, the model is W522A, with the box X96 Max Plus 100W

**Comment by trvqhuy** [comment]
My X96 Max Plus 100W and the 2101W have the same W522A radio module.

I hope I can help you with this link:
https://4pda.to/forum/index.php?showtopic=1013103&st=40#entry102780026

![image](https://user-images.githubusercontent.com/88963333/211586481-062584cc-a16c-4c51-88e6-dfbe409b675b.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/CONTRIBUTORS.md

Thanks for your beta feedback, your contribution has been added to the list of contributors. x96-max+100W has been added to the device list, and the serial number of the installation option is `517`


It's almost 12 o'clock in the middle of the night today, I have to go to bed, and I have to work tomorrow. I will look up the driver information of this wireless tomorrow and reply to you.
Do you have the original android firmware for this box? Share a download link, I will back it up so that other people can restore the system and use it.

**Comment by trvqhuy** [comment]
Yes, I do have the original firmware of this box in the following links:

https://drive.google.com/drive/folders/19ZoOEo5c5Ca7U48NtAfFLx2ErqLUA2JB?usp=share_link
https://cloud.mail.ru/public/xcUu/iJFKXGKBE

Thanks @ophub for your dedicated support for the community.
I'm waiting to hear good news from you!

**Comment by ophub** [comment]
Do you know the short contact position of this box? Mark it on the motherboard picture?

**Comment by trvqhuy** [comment]
Sorry I don't know the location of the short contact for this box.

I have tried flashing the original firmware with the tooth-picking method, thanks to the help of USB-Burning-Tool on Windows.

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y

No driver related to W522A can be found in the source code of the mainline kernel. Have you found his driver?

**Comment by trvqhuy** [comment]
No I cannot find any information on the driver, however I found some related informations as I've mentioned.

I really hope it can help you.

> I found some information.\nThe W552a is an Fn-Link K255B-SR.\nThe Fn-Link K255B-SR is an Amlogic W155S1 chip, with the following datasheet:\nhttps://usermanual.wiki/HUNAN-FN-LINK-TECHNOLOGY/K255B-SR.User-Manual-5353157.pdf\n\nI found two github for the sources of this module:\nhttps://github.com/CoreELEC/w1-aml\nhttps://github.com/adeepn/w1-aml\n\nTutorials for W155S1\nhttps://blog.csdn.net/zhaojy5453/article/details/115484201

**Comment by trvqhuy** [comment]
Yeah, it's a pity that I cannot use the wired connection in my living area

**Comment by trvqhuy** [comment]
But if it's so hard to install the wireless driver of this module, you don't need to waste your time for my box.

I've already seen your dedicated support here, don't bother it.

**Comment by ophub** [comment]
There are drivers in the mainline kernel source, and it's easy to create a dedicated dtb that includes wireless/bluetooth support.

However, the manufacturers of these TV boxes generally only disclose the drivers of the Android system, and rarely support the mainline kernel, so most drivers are hard to find.

**Comment by trvqhuy** [comment]
I'm waiting for your news here.

Please tell me if you need any help, I will check this issue twice a day.

I had purchased 10+ of these TV Box from China for installing the Armbian for my working purpose, so that would be a pitty that this box cannot establish the wifi and bluetooth connection.

However that would be fine if you cannot find the driver for this one, I will try better luck in the future.

**Comment by Orefie** [comment]
Hi [trvqhuy](https://github.com/trvqhuy), [ophub](https://github.com/ophub),
Another thought, the JetHome JetHub D1+ has the same wifi chip and it runs on armbian.
You can check its firmware to extract drivers and dtb files but it has a different processor.
So probably a lot of work to make it compatible.

The pins to shunt for a flash recovery are here.

![reset_pin](https://user-images.githubusercontent.com/115935914/211621078-a5d5b603-1ee6-4ab4-8869-a731b0a26f11.jpg)

**Comment by trvqhuy** [comment]
Thanks @Orefie for the informations, I really hope it can help @ophub

**Comment by ophub** [comment]
Which dtb does the JetHome JetHub D1+ use?

**Comment by trvqhuy** [comment]
Hi @Orefie , can you show use which dtb does it use?

**Comment by trvqhuy** [comment]
I've just figured out that the SlimBoxTV Image from the link below works fine with my 100W.
Both wifi and ethernet connection works normally.

https://disk.yandex.ru/d/tuWOHY20DoI4Ow

**Comment by Orefie** [comment]
You can find all firmware for jethome d1+ here.
https://fw.jethome.ru/devices/jethome/D1P/
The custom rom SlimBoxTV "sbx_x96max_plus_2101w_aosp_15_4_1" works fine but this is an android rom.
This rom is useful to put the emc back in order after crashing the box. (short contact and Amlogic_USB_Burning_Tool)

**Comment by trvqhuy** [comment]
Hi @ophub , is there anything that I can help you?

**Comment by ophub** [comment]
There is no wireless driver, currently cannot support

**Comment by trvqhuy** [comment]
Okay I got it, thank you for your support

**Comment by royan204** [comment]
im in a real confusion right now, how come my x96max+ never boot to linux, what option should i choose when entering android boot menu

**Comment by royan204** [comment]
i did everything correctly 
/boot/uEnv.txt
try meson-sm1-x96-air.dtb or meson-sm1-a95xf3-air.dtb
copy u-boot-x96maxplus.bin to u-boot.ext and u-boot.emmc 

but nothing happens it just boot to android, but if i pressed reset button it boot into android boot menu idk to choose
@trvqhuy can you send me a tutorial link to boot linux with x96max+ 100W,

**Comment by royan204** [comment]
@ophub hi... i need help, my X96max+ 100W wont boot to armbian. i did everything correctly i did change the uEnv.txt to correct dtb, i change the correct u-boot.ext as you mentioned before but nothing seems to work, x96max just keep booting to android and when i long press the reset button it enter boot menu and i chose boot from boatloader the booting screen just stuck forever. is there any step to make x96max to boot to sdcard, i already try to boot with adb and enable usb debugging and the result just the same, pls help i need a tutorial

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents

look at 12.14

**Comment by royan204** [comment]
sorry, i don't understand point number 12.14 which one should i edit

**Comment by ophub** [comment]
look at `12.4`

**Comment by royan204** [comment]
![IMG20230727201049](https://github.com/ophub/amlogic-s9xxx-armbian/assets/139738304/3580e9e9-a675-4fa8-acdf-84ada33298ef)

i did point number 12.4 but after i do #adb shell reboot update# on cmd it just showing this screen after booting

**Comment by royan204** [comment]
![IMG_20230727_21381283](https://github.com/ophub/amlogic-s9xxx-armbian/assets/139738304/1875272e-851b-4479-b989-6377b67a260b)


@ophub please help me with this, i tried to change UUID to LABEL=ROOTFS doesn't 
 work either

**Comment by ophub** [comment]
Why change uuid?

**Comment by royan204** [comment]
that picture is taken before i change the uuid, i try to solve it by change it to ROOTFS after and it doesn't work either
