### ISSUE TITLE
armbian-update 更新失败

### ISSUE THREAD

**Issue by saenice** [ophub/amlogic-s9xxx-armbian#912]
![image](https://user-images.githubusercontent.com/56823170/211709346-0575dacc-607e-4bd6-a02f-dcbca03211f3.png)
如下图更新失败：
![image](https://user-images.githubusercontent.com/56823170/211709508-cb6f1061-1663-47b6-9155-e0546745e143.png)

![image](https://user-images.githubusercontent.com/56823170/211709577-721fefc9-eb80-4bab-ac96-ed6f56e6dcd6.png)
发现内核被污染，需要附加root权限；如下图命令
root@Number60008:~# chmod 4755 /etc/sudoers
root@Number60008:~# chown root:root /etc/sudoers
root@Number60008:~# chown root:root /usr -R
root@Number60008:~# chmod 4755 /usr -R
root@Number60008:~# chown root:root /etc -R
root@Number60008:~# chmod 4755 /etc -R
root@Number60008:~# chown root:root /etc/sudoers.d
root@Number60008:~# chmod 4755 /etc/sudoers.d
root@Number60008:~# chmod 4755 /etc/sudoers.d/README 
root@Number60008:~# chown root:root /etc/sudoers.d/README 
![image](https://user-images.githubusercontent.com/56823170/211709986-73320fab-369b-4d4a-8102-2f32587ca5c0.png)
更新内核成功。
![image](https://user-images.githubusercontent.com/56823170/211710079-e83dc794-51f7-420a-b51b-6bb9ce7cb95c.png)

**Comment by ophub** [comment]
在安卓输入 `adb shell reboot update` 命令重启后再迅速插入U盘，这样就不会被修改了。
如果安卓系统还在运行，你先把U盘插入，然后再执行重启等操作，这段时间U盘被安卓系统加载，会被安卓修改了权限。

**Comment by saenice** [comment]
系统已经写入了eMMC，没有使用U盘或者TF卡启动设备。

**Comment by ophub** [comment]
你安装之前，已经被安卓污染了，所以写入emmc的系统也权限被修改了。你使用armbian-fix修复一下试试是否都修复了。如果一直有权限问题，重新下载固件，写U盘，按照上面的方法，断电后插入U盘，插电启动，写入emmc
