### ISSUE TITLE
关于ddbr备份问题

### ISSUE THREAD

**Issue by dapengg** [ophub/amlogic-s9xxx-armbian#913]
制作了个100多g的u盘想备份EMMC还是提示空间不足
![QQ截图20230111111456](https://user-images.githubusercontent.com/64346391/211710683-b6b9f101-e300-4819-aa26-1dc7da465915.png)
![IMG_5461](https://user-images.githubusercontent.com/64346391/211710701-7cce75ee-bf9e-4b24-8bda-1d766921fef1.JPG)

**Comment by ophub** [comment]
U盘默认只有2G固件那么大的空间占用了。
U盘启动后，第一步先执行`armbian-tf`，选择`e`把U盘剩余空间启用了。再ddbr即可。
