### ISSUE TITLE
hi！O Big！关于ddbr不合理出提意。

### ISSUE THREAD

**Issue by urenai** [ophub/amlogic-s9xxx-armbian#915]
**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]
 - 
**Describe the bug | 问题描述**
   在实际运用中发现，ddbr执行过程会备份整个emmc。这太慢，太不符合逻辑了。
比喻说，一个128GB EMMC 只安装了armbian系统，部署好app后，执行ddbr备份，
本意只是想备份系统，而他实际上把整个emmc给备份了。
希望作出调整。

**Comment by ophub** [comment]
ddbr就是磁盘镜像，不能只复制文件，包括emmc里写入的主线u-boot，分区表等都必须完整备份，这样再ddbr还原才可以使用。

如果只是复制了文件，没分区表，bootloader等，备份无效。

**Comment by urenai** [comment]
貌似无解，磁盘镜像太久了。
