### ISSUE TITLE
求教玩客云pro刷机教程，amlogic s912版本

### ISSUE THREAD

**Issue by jinjd** [ophub/amlogic-s9xxx-armbian#918]
配置amlogic s912+2g+8G，按照章鱼星球刷机方法测试失败。

**Comment by ophub** [comment]
这个设备不支持

**Comment by jinjd** [comment]
> 这个设备这里不支持，你可以使用armbian官方的制作

能否提供帮助?
设备信息：玩客云pro型号ws1710，amlogic s912，2g+8g

**Comment by ophub** [comment]
这个盒子是32位的，仓库里下载的都是64位的，不能通用。
这个盒子在 armbian 官方源码里支持了，你可以直接使用源码编译。

**Comment by jinjd** [comment]
> 这个盒子是32位的，仓库里下载的都是64位的，不能通用。 这个盒子在 armbian 官方源码里支持了，你可以直接使用源码编译。

有点疑问啊这个盒子cpu是s912，晶晨S912是一款八核心64位Cortex-A53处理器,28nm制程工艺。要编译32位的armbian吗？

**Comment by ophub** [comment]
s805,32位soc

**Comment by mysmartha** [comment]
> 是s805, 不是s912，一个 ARMv7 32位的soc

大佬，玩客云是S805 32位的，他说的是玩客云pro，确实是s912 64位的，玩客云和玩客云pro确实是两个不同的设备。

**Comment by jinjd** [comment]
> > 是s805, 不是s912，一个 ARMv7 32位的soc
> 
> 大佬，玩客云是S805 32位的，他说的是玩客云pro，确实是s912 64位的，玩客云和玩客云pro确实是两个不同的设备。

是的，玩客云pro是s912 64位的，有刷机方案吗？找到一篇TTL成功文章 https://www.znds.com/tv-1201895-1-1.html
USB Burning Tool线刷章鱼星球失败，应该是未适配，有办法吗？这款设备好久了，再就是应该被厂商放弃了不再支持

**Comment by 326652397** [comment]
> 是s805, 不是s912，一个 ARMv7 32位的soc

大佬玩客云pro是s912的，配置基本上和章鱼星球是一样的。我有玩客云pro的启动日志不知道有用没有。

**Comment by jinjd** [comment]
> > 是s805, 不是s912，一个 ARMv7 32位的soc
> 
> 大佬玩客云pro是s912的，配置基本上和章鱼星球是一样的。我有玩客云pro的启动日志不知道有用没有。

用章鱼星球的包测试了下不行，主要是章鱼星球是默认u-boot启动吧，玩客云pro需要s912的底包改u-boot启动才行，然后在适配系统刷入emmc

**Comment by LiteCoder** [comment]
请问一下解决了吗 能刷了没

**Comment by 3543776055** [comment]
同求

**Comment by jinjd** [comment]
dd

**Comment by SeaRat** [comment]
怎么样？现在有方法了吗
