### ISSUE TITLE
X96Max Plus wifi not working

### ISSUE THREAD

**Issue by SajjadSabzkar** [ophub/amlogic-s9xxx-armbian#919]
Hi There ! 
I recently installed  Armbian_23.02.0_amlogic_s905x3_jammy_5.15.86_server_2023.01.11.img.gz  on my android box and wifi does not working . but i past installed previous versions on x96 max plus it's working fine.
There is Some log :

Jan 11 22:59:33 armbian kernel: [  100.015379] RTL871X: PowerOnCheck: 0x1B8 test Fail(index: 100).
Jan 11 22:59:33 armbian kernel: [  100.021192] RTL871X: ERROR Dump MAC Page0 register:
Jan 11 22:59:34 armbian kernel: [  100.544535] RTL871X: Failed to init Power On!
Jan 11 22:59:34 armbian kernel: [  100.548865] RTL871X: rtw_hal_init: hal__init fail
Jan 11 22:59:34 armbian kernel: [  100.553520] RTL871X: -871x_drv - drv_open fail, bup=0

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek

have no drivers

**Comment by SajjadSabzkar** [comment]
i open my x96max plus and wifi module  is : Realtek 8189ftv

**Comment by ophub** [comment]
There is no driver, you can check it in the kernel source repository posted above.

**Comment by SajjadSabzkar** [comment]
i look this [repo](https://github.com/myjsqmail/messy) 8189ftv driver in rtl8189ES_linux package but unifreq remove this package at this [commit](https://github.com/unifreq/linux-5.15.y/commit/54d3475d2208a1b7f0f7cef59823f84c7c56aa0b)
Why ?

**Comment by ophub** [comment]
User feedback is unavailable
