### ISSUE TITLE
Proxmox in amlogic with x96max+ 4/64

### ISSUE THREAD

**Issue by navigos** [ophub/amlogic-s9xxx-armbian#92]
Hi, i have x96 max+ 4/64

I want to install Proxmox, which is open source software for managing containers and virtual machines. (pi-hole, nextcloud, netbsd, ...)

I follow this tutorial but the installation hangs at 99%. https://forum.proxmox.com/threads/proxmox-on-arm64.69080/page-2

Can we get something like this?

**Comment by danboid** [comment]
I've not tried it on arm myself yet but I use LXD in work to host several containers and its great. It does everything proxmox does but without a web UI. It supports VMs too.

**Comment by ophub** [comment]
proxmox on arm64 may not be mature, test more

**Comment by MX10-AC2N** [comment]
Hi @navigos 
maybe you can test https://github.com/IceWhaleTech/CasaOS 
but it is relatively recent and therefore still in development.. To try..
have a nice day..
