### ISSUE TITLE
wifi issue of jammy-6.1.4 for N1

### ISSUE THREAD

**Issue by ruleechen** [ophub/amlogic-s9xxx-armbian#925]
**Device Information | 设备信息**
 - SOC: amlogic s905d
 - Model: Phicomm-N1

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.4
 - Release: Jammy

**Describe the bug | 问题描述**
安装了Armbian_23.02.0_amlogic_s905d_jammy_6.1.4_server_2023.01.11.img.gz，刚启动的时候wifi网络可以使用，过一会儿就不能用了

 $ systemctl status NetworkManager.service

<img width="1187" alt="image" src="https://user-images.githubusercontent.com/907369/212372833-1c02eddf-69f9-4220-bd8c-284c0952b21c.png">

**Comment by JFLim1** [comment]
Hi @ophub,

Looks like similar/same issue with GT King Pro on kernel 6.1.y https://github.com/ophub/amlogic-s9xxx-armbian/issues/898 and https://github.com/ophub/amlogic-s9xxx-armbian/issues/861.

**Comment by ruleechen** [comment]
Sth additional

<img width="913" alt="image" src="https://user-images.githubusercontent.com/907369/212390359-504149ee-c6dc-4e13-843d-addc172f4dd8.png">

**Comment by ruleechen** [comment]
I tried reinstall `network-manager` and it is now keep active (running) state. But it doesn't help with wifi issue.
> sudo apt reinstall network-manager

**Comment by livelier** [comment]
@ruleechen 
把网络全权交给网络管理器试试看呢？

/etc/NetworkManager/NetworkManager.conf
配置文件如下部分修改。

```
[ifupdown]
managed=false
```
/etc/network/interfaces
配置文件仅保留如下内容，其他全部注释掉。
```
source /etc/network/interfaces.d/*
# Network is managed by Network manager
auto lo
iface lo inet loopback
```
最后重启系统

**Comment by ruleechen** [comment]
@livelier 感谢，我测试了，wifi网络还是一会儿就挂了。

一旦挂了，就看不到设备信息了
```bash
# nmcli device status
```

**Comment by cjh19831115** [comment]
同样，我的斐讯t1也是这样的情况，开机一段时间还可以，然后wifi就挂了，链接不上，内核是6.1.5

**Comment by ophub** [comment]
其他内核可以使用吗？更新内核为5.15/5.10的试试

**Comment by cjh19831115** [comment]
我的事昨天晚上升级的6.1.5内核，出现状况，之前用6.0.Y没有出现类似现象

**Comment by wordlesswind** [comment]
我装了 OMV，不使用 NetworkManager 也一样挂，甚至系统出现了系统卡死不可用的情况。
一开始我以为是我把 eMMC 刷坏了，现在退回使用 5.15.87 暂时没有遇到任何问题。

**Comment by livelier** [comment]
上游已经修复此问题，等待o大更新内核即可解决。

https://github.com/ophub/amlogic-s9xxx-armbian/issues/898#issuecomment-1382889923

**Comment by wordlesswind** [comment]
> 上游已经修复此问题，等待o大更新内核即可解决。
> 
> [#898 (comment)](https://github.com/ophub/amlogic-s9xxx-armbian/issues/898#issuecomment-1382889923)

感谢提醒，请问如果新内核推出后，我可以直接运行 `armbian-update 6.1.y` 更新内核吗？

**Comment by ophub** [comment]
可以，上面livelier分享的内核，你手动下载，上传到armbian，在内核目录里执行armbian-update就是使用本地当前目录下的内核更新。

我正在编译6.1.6，半个小时后更新到仓库，以后也可以armbian-update 6.1.6在线更新。

**Comment by ophub** [comment]
https://lore.kernel.org/linux-amlogic/52861a84-0fe2-37f0-d66a-145f2ebe1d79@gmail.com/T/#m9c6a0aa6b221bcbf51457e612456c6fff5eeacfa

A description of some wireless issues caused by the interrupt support introduced.

The specific repair content can be viewed in the kernel source code of unifreq.

**Comment by JFLim1** [comment]
> https://lore.kernel.org/linux-amlogic/52861a84-0fe2-37f0-d66a-145f2ebe1d79@gmail.com/T/#m9c6a0aa6b221bcbf51457e612456c6fff5eeacfa
> 
> A description of some wireless issues caused by the interrupt support introduced.
> 
> The specific repair content can be viewed in the kernel source code of unifreq.

Thank you for sharing.

**Comment by ruleechen** [comment]
回家辽，Phicomm-N1迫不及待安装了
Armbian_23.02.0_amlogic_s905d_jammy_6.1.6_server_2023.01.15.img.gz

目前为止运行了1小时，目前看起来
- wifi正常
- 有线网没测试（没有足够长的线）
- 蓝牙正常
- apt update/upgrade 正常

感觉完美！

**Comment by yubina** [comment]
5.15.100还是无法连接上wifi 怎么解决这个问题 @ophub

**Comment by ophub** [comment]
最近的3个版本的内核都有无线无法连接的问题，等kernel.org修复

**Comment by yubina** [comment]
> 最近的3个版本的内核都有无线无法连接的问题，等kernel.org修复

哪里还能下载低的版本

**Comment by ophub** [comment]
可能f大的度盘里有

**Comment by LmissW** [comment]
![1678715463779](https://user-images.githubusercontent.com/94090908/224721755-5d34c1ee-8616-41fd-bb2a-bc87bf138d6b.png)
求各位大神这个怎么选择怎么填写吗？求指教，实在不知道怎么弄了

**Comment by ophub** [comment]
让你输ID，看上表，第一列是ID

**Comment by LmissW** [comment]
> 让你输ID，看上表，第一列是ID

输入id以后，后面的怎么填呀

**Comment by yubina** [comment]
> 可能f大的度盘里有

3月14这个修复了wifi问题吗

**Comment by ophub** [comment]
没更新内核呢，等新内核

**Comment by yangzq6887** [comment]
> 

请问f大的度盘网址是啥

**Comment by ophub** [comment]
链接：https://pan.baidu.com/s/15b1OWLXcmpJjqdaYFKvIlg?pwd=6nc4
提取码：6nc4
链接：https://pan.baidu.com/s/14WCQid4GHB76RLFZKb3VQA?pwd=3jwb
提取码：3jwb
链接：https://pan.baidu.com/s/1j7OTusExLii53ganNHHO0Q?pwd=zq3y
提取码：zq3y

**Comment by yubina** [comment]
#

> 链接：https://pan.baidu.com/s/15b1OWLXcmpJjqdaYFKvIlg?pwd=6nc4 提取码：6nc4 链接：https://pan.baidu.com/s/14WCQid4GHB76RLFZKb3VQA?pwd=3jwb 提取码：3jwb 链接：https://pan.baidu.com/s/1j7OTusExLii53ganNHHO0Q?pwd=zq3y 提取码：zq3y

wifi连接问题修复了吗

**Comment by ucsoom** [comment]
链接：https://pan.baidu.com/s/15b1OWLXcmpJjqdaYFKvIlg?pwd=6nc4
提取码：6nc4
链接：https://pan.baidu.com/s/14WCQid4GHB76RLFZKb3VQA?pwd=3jwb
提取码：3jwb
链接：https://pan.baidu.com/s/1j7OTusExLii53ganNHHO0Q?pwd=zq3y
提取码：zq3y

**Comment by zzh-soft** [comment]
[Armbian_23.08.0_amlogic_s905d_jammy_6.1.35_server_2023.06.21.img.gz]  这个版本的有碰到有线无法自动获取到ip不，设置静态地址也无法连通

**Comment by ty67720639** [comment]
弱弱的问一下大神的系统会自动挂载USB存储设备吗？还是只能通过修改fstab文件来实现自动挂载呢？

**Comment by zzh-soft** [comment]
我没有挂载USB存储，我是直接扩容了。没有遇到你说的问题。

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: ty67720639 ***@***.***>
发送时间: Sunday, August 27, 2023 11:06:49 AM
收件人: ophub/amlogic-s9xxx-armbian ***@***.***>
抄送: zzh-soft ***@***.***>; Comment ***@***.***>
主题: Re: [ophub/amlogic-s9xxx-armbian] wifi issue of jammy-6.1.4 for N1 (Issue #925)


弱弱的问一下大神的系统会自动挂载USB存储设备吗？还是只能通过修改fstab文件来实现自动挂载呢？

―

**Comment by ty67720639** [comment]
我是用的N1作为轻NAS用的，挂了一个移动硬盘作为存储用的

**Comment by ty67720639** [comment]
> 链接：https://pan.baidu.com/s/15b1OWLXcmpJjqdaYFKvIlg?pwd=6nc4 提取码：6nc4 链接：https://pan.baidu.com/s/14WCQid4GHB76RLFZKb3VQA?pwd=3jwb 提取码：3jwb 链接：https://pan.baidu.com/s/1j7OTusExLii53ganNHHO0Q?pwd=zq3y 提取码：zq3y

弱弱的问一下大神的系统会自动挂载USB存储设备吗？还是只能通过修改fstab文件来实现自动挂载呢？我是用的N1作为轻NAS用的，挂了一个移动硬盘作为存储用的

**Comment by CoolLittle** [comment]
安装Desktop后 lightdm无法正常启动，查看/var/log/lightdm日志后发现提示如下异常，该怎么处理呢？
Fatal server error:
(EE) no screens found(EE)

**Comment by Warren888** [comment]
大神们，[Armbian_23.11.0_amlogic_s905d_jammy_6.1.59_server_2023.10.20.img.gz] 这个镜像为啥下载不了，提示 "无法访问此网站objects.githubusercontent.com 意外终止了连接"  换了电脑也不行，是我下载方式不对么，有网盘下载的链接不，谢谢！

**Comment by cherinyy** [comment]
> 意外终止了连接

使用 [https://ghproxy.com/](https://ghproxy.com/)（由 [hunshcn](https://github.com/hunshcn)  提供）等 GitHub 反代下载站来下载文件，或者使用一些海外加速服务，以解决 GitHub 在中国内地被间歇性干扰的问题。

**Comment by zouyong94** [comment]
Armbian_24.2.0_amlogic_s905d_jammy_6.6.13_server_2024.01.25.img我使用这个版本，wifi一会儿就掉了，armbian-config里面也看不到wifi选项了

**Comment by Wait2I3** [comment]
我的wifi断开 甚至没有Wi-Fi的信号 提示错误 这是什么问题？
![Uploading 231cda4e4c9f5ee9cc6e4d323c2f3b1.jpg…]()

**Comment by ljx-00** [comment]
> ![1678715463779](https://user-images.githubusercontent.com/94090908/224721755-5d34c1ee-8616-41fd-bb2a-bc87bf138d6b.png) 求各位大神这个怎么选择怎么填写吗？求指教，实在不知道怎么弄了

请问这个可以实现自动选择吗？想实现插上u盘就自动写入盒子

**Comment by RookieTerry** [comment]
请问这个问题现在解决了吗？
