### ISSUE TITLE
Wifi-support for rtl8188fu

### ISSUE THREAD

**Issue by Paxton77** [ophub/amlogic-s9xxx-armbian#926]
Hello,
I have installed your armbian on a x96 mini with the rtl8189es. 
The wlan chipset isn't supported.
Is it possible to integrate a driver for the rtl8188fu chipset?
This should also work.
I found on github the following source:

https://github.com/unifreq/linux-5.15.y/tree/main/drivers/net/wireless/realtek/rtl8188fu

**Comment by ophub** [comment]
Different, there is no such driver.
