### ISSUE TITLE
M401a盒子emmc写入出错

### ISSUE THREAD

**Issue by henrywang041201** [ophub/amlogic-s9xxx-armbian#927]
**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - Model [e.g. M401a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.85]
 - Release: [Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.85_server_2022.12.25]

**Describe the bug | 问题描述**
按照论坛上xcray大神的方法，使用usb2.0的u盘写盘后在uEnv.txt文件内指定了启动的`meson-g12a-u200.dtb`，在armbian-install时选择了`meson-g12a-u200.dtb`的dtb，`u-boot-e900v22c.bin`的u-boot，安装指令如下图1所示：
![图一](https://user-images.githubusercontent.com/90250692/212472856-ae262b98-0b87-4fd5-942f-b3e7b2d0168a.jpg)

运行安装后出现了如下的问题，见图二图三：
![图二](https://user-images.githubusercontent.com/90250692/212472862-eff64ee4-93e9-48cb-808e-8dd3493012ad.jpg)
![图三](https://user-images.githubusercontent.com/90250692/212472872-489aa399-7c41-4e5c-a591-395b9cc66a4e.jpg)

按照这种在查阅了已有的issue后，了解到这款盒子体质有差异，提到了可能需要在dtb中降低emmc频率实现写入，故想尝试解决这个问题，想知道具体应该怎么操作，如果重新编译固件，或者有没有大佬分享一下已经编译好的固件

**Comment by ophub** [comment]
306

**Comment by henrywang041201** [comment]
好的，我再试一下，那uEnv.txt文件还需要修改吗

> 306

**Comment by ophub** [comment]
不用

**Comment by henrywang041201** [comment]
刚刚重新写盘后没有修改**uEnv.txt**又试了一下，无法启动进入系统。于是在**uEnv.txt**内指定了`meson-g12a-s905l3a-m401a.dtb`成功启动并使用**306**写入emmc，感谢o大提点

**Comment by ophub** [comment]
好的

**Comment by henrywang041201** [comment]
还有一件事情想请教一下，就是这个**M401a**的dtb里面编译了蓝牙的功能吗？因为之前使用xcray编译好带蓝牙的u201或u212的dtb写入emmc有上述错误，想知道现在使用这个`meson-g12a-s905l3a-m401a.dtb`是否还要重新编译，添加蓝牙相关内容。

**Comment by ophub** [comment]
m401a不支持蓝牙

**Comment by henrywang041201** [comment]
好的，谢谢

**Comment by xcray** [comment]
> m401a不支持蓝牙

当初没看到这个帖子，这我得怼一下o大哈哈哈哈，m401a支持蓝牙，并且支持的很好。就是得手工配置一下：https://github.com/ophub/amlogic-s9xxx-armbian/discussions/1546
