### ISSUE TITLE
X96Max+_2101 Bluetooth Not recognized

### ISSUE THREAD

**Issue by salsabilng** [ophub/amlogic-s9xxx-armbian#928]
Hi! Thank you for your hard work, nice!
I'm just wondering, can i enable the RTL8822CS bluetooth? the wifi works, but the bluetooth seems not working properly. The Bluetooth only loaded when i use `modprobe bluetooth` then i can see the loaded bluetooth log in kernel log.

**Device Information | 设备信息**
 - SOC: s905x3 
 - Model X96 Max Plus 2101 

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.87-happy-new-year
 - Release: 22.11.1 Bullseye (Rebuild from odroidn2)
 - using Mainline uboot

**Describe the bug | 问题描述**
So the bluetooh seems loaded, but `hcitool dev` shows empty devices. The bluetooth not loaded automatically on boot, it need `modprobe bluetooth` and no error from the log. Do i missing something?

abil@blackBox:~$ sudo dmesg | grep Bluetooth
[  935.227781] Bluetooth: Core ver 2.22
[  935.230792] Bluetooth: Starting self testing
[  935.244124] Bluetooth: ECDH test passed in 10824 usecs
[  935.249275] Bluetooth: SMP test passed in 2960 usecs
[  935.251372] Bluetooth: Finished self testing
[  935.260151] Bluetooth: HCI device and connection manager initialized
[  935.266461] Bluetooth: HCI socket layer initialized
[  935.271271] Bluetooth: L2CAP socket layer initialized
[  935.276304] Bluetooth: SCO socket layer initialized
[ 1009.661654] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[ 1009.663885] Bluetooth: BNEP filters: protocol multicast
[ 1009.668639] Bluetooth: BNEP socket layer initialized

abil@blackBox:~$ bluetoothctl
Agent registered
[bluetooth]# show
No default controller available
[bluetooth]# devices
No default controller available

abil@blackBox:~$ sudo hcitool dev
Devices:

**Comment by ophub** [comment]
armbian-config
install Bluetooth

**Comment by salsabilng** [comment]
done that

![image](https://user-images.githubusercontent.com/89365187/212474080-4d8a8c46-0de5-4863-b4eb-f281b07c1ee6.png)

**Comment by ophub** [comment]
cat /etc/ophub-release
cat /boot/uEnv.txt
ls -l /boot/u-boot*

**Comment by salsabilng** [comment]
abil@blackBox:~$ cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905x3'
MODEL_NAME='X96-Max+_100Mb'
FDTFILE='meson-sm1-x96-max-plus.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/hk1box-bootloader.img'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='5.15.87'
KERNEL_BRANCH='stable'
K510='0'
ROOTFS_TYPE='btrfs'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
MLUBOOT_STATUS='yes'
AMPART_STATUS='yes'
PACKAGED_DATE='2022-12-30'

abil@blackBox:~$ cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-x96-max-plus.dtb
APPEND=root=UUID=a4eca025-64db-4504-bca6-19787de1f79c rootflags=compress=zstd:6 rootfstype=btrfs console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1

abil@blackBox:~$ ls -l /boot/u-boot*
-rwxr-xr-x 1 root root 704408 Jan 10 19:03 /boot/u-boot-e900v22c.bin
-rwxr-xr-x 1 root root 746678 Jan 10 19:03 /boot/u-boot.emmc
-rwxr-xr-x 1 root root 746678 Jan 10 19:03 /boot/u-boot.ext
-rwxr-xr-x 1 root root 757153 Jan 10 19:03 /boot/u-boot-gtking.bin
-rwxr-xr-x 1 root root 757080 Jan 10 19:03 /boot/u-boot-gtkingpro.bin
-rwxr-xr-x 1 root root 735459 Jan 10 19:03 /boot/u-boot-gtkingpro-rev-a.bin
-rwxr-xr-x 1 root root 702771 Jan 10 19:03 /boot/u-boot-n1.bin
-rwxr-xr-x 1 root root 761012 Jan 10 19:03 /boot/u-boot-odroid-n2.bin
-rwxr-xr-x 1 root root 553489 Jan 10 19:03 /boot/u-boot-p201.bin
-rwxr-xr-x 1 root root 606670 Jan 10 19:03 /boot/u-boot-p212.bin
-rwxr-xr-x 1 root root 609247 Jan 10 19:03 /boot/u-boot-s905.bin
-rwxr-xr-x 1 root root 740080 Jan 10 19:03 /boot/u-boot-s905x2-s922.bin
-rwxr-xr-x 1 root root 650183 Jan 10 19:03 /boot/u-boot-s905x-s912.bin
-rwxr-xr-x 1 root root 709768 Jan 10 19:03 /boot/u-boot.sd
-rwxr-xr-x 1 root root 754378 Jan 10 19:03 /boot/u-boot-sei510.bin
-rwxr-xr-x 1 root root 754384 Jan 10 19:03 /boot/u-boot-sei610.bin
-rwxr-xr-x 1 root root 880672 Jan 10 19:03 /boot/u-boot-skyworth-lb2004.bin
-rwxr-xr-x 1 root root 758664 Jan 10 19:03 /boot/u-boot-tx3-bz.bin
-rwxr-xr-x 1 root root 759112 Jan 10 19:03 /boot/u-boot-tx3-qz.bin
-rwxr-xr-x 1 root root 694755 Jan 10 19:03 /boot/u-boot-u200.bin
-rwxr-xr-x 1 root root 877080 Jan 10 19:03 /boot/u-boot-ugoos-x3.bin
-rwxr-xr-x 1 root root 709768 Jan 10 19:03 /boot/u-boot.usb
-rwxr-xr-x 1 root root 748175 Jan 10 19:03 /boot/u-boot-x96max.bin
-rwxr-xr-x 1 root root 746678 Jan 10 19:03 /boot/u-boot-x96maxplus.bin
-rwxr-xr-x 1 root root 703444 Jan 10 19:03 /boot/u-boot-zyxq.bin

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/97bf67d84b18875b828ee4ae8d743929b025d2c5/arch/arm64/boot/dts/amlogic/meson-sm1-x96-max-plus.dts#L186

I checked that bluetooth has been added in dtb.

This driver comes from a third party and is not included with the mainline kernel.

It is very rare that you can use wireless, and many people report that wireless cannot be used.

**Comment by ophub** [comment]
Is the wired network of this box Gigabit or 100M? I see that your u-boot does not correspond to the installation option, did you manually change the u-boot?

**Comment by salsabilng** [comment]
no, i done nothing. my box is gigabyte with JL2101, im only following the instructions. yes the wlan is on, i can connect but it sometimes disconnect. (not stable). well, looks like indeed RTL8822CS is not good after all, i will use bluetooth dongle anyway. thanks for your help
