### ISSUE TITLE
Request: Add support for X96 Max Plus 2101W 

### ISSUE THREAD

**Issue by Orefie** [ophub/amlogic-s9xxx-armbian#929]
### **TVBox X96 max plus 2101W**

Can you add support for this card?

Board: Q5X3_141 V4.1 20112
Ram: 4GB emmc: 64GB
Soc: S905X3
LAN: 1Gb JL2101
radio module: W522A  (Fn-Link K255B-SR, W155S1),  two antennas.
LED controller: AiP1628

![1673743301856](https://user-images.githubusercontent.com/115935914/212503340-6bd87060-f669-4bd1-a004-9153ab3a2d8e.jpg)

Short pin for recovery (Amlogic_USB_Burning_Tool).

![211621078-a5d5b603-1ee6-4ab4-8869-a731b0a26f11](https://user-images.githubusercontent.com/115935914/212503372-6795432c-73e8-4584-83cb-dabc744c4071.jpg)

Rom android: https://disk.yandex.ru/d/hGbDgwMQjO8BDQ

Works with meson-sm1-x96-max-plus.dtb but no wifi, no led

Thanks for your work.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/928

Rtl8822cs wireless has been added. Some devices can be used, but others cannot. This drive comes from a third party and is not very stable.


See the document for the use of led：

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/led_screen_display_control.md

**Comment by Orefie** [comment]
Hello [@ophub](https://github.com/ophub) ,
Salsabilng talks about Rtl8822cs module, in my board it's a w522a (W150S1) wifi module.
I tried the coreelec firmware.

The wifi works for CoreELEC-20.0-Nexus_rc2
![Capture](https://user-images.githubusercontent.com/115935914/212534328-6d1a34af-6723-441b-94d4-939c31b30d47.JPG)
The driver name is w1-aml. 
https://github.com/CoreELEC/w1-aml
Modules "aml_sdio.ko" and "vlsicomm.ko" are loads.
But no Bluetooth.
See dts file line 2813.

I hope it can help you, thanks for your work.
[sm1_s905x3_4g_1gbit.dts.txt](https://github.com/ophub/amlogic-s9xxx-armbian/files/10419877/sm1_s905x3_4g_1gbit.dts.txt)

**Comment by ophub** [comment]
coreelec is Android, which is different from armbian. Armbian uses the mainline kernel, and Android drivers cannot be used.

**Comment by Orefie** [comment]
Ok, thanks for your answers and thanks again for your work. ;)

**Comment by trvqhuy** [comment]
Hi @Orefie , may I ask if your box with W522A Radio Module can obtain wifi connection?

If so, please tell me which dtb files you used for the setup?

**Comment by Orefie** [comment]
Hi @trvqhuy,
The tests on my TVBox 2101W,
Android aosp Slimbox : Wifi 2.4, 5G **OK**, Bluetooth **NOK**, Eth **OK**.
Coreelec : Wifi 2.4, 5G **OK**, Bluetooth **NOK**, Eth **OK**. (sm1_s905x3_4g_1gbit.dtb)
Armbian : Wifi 2.4, 5G **NOK**, Bluetooth **NOK**, Eth **OK**. (meson-sm1-x96-max-plus.dtb) 
If it helps you. ;)

**Comment by trvqhuy** [comment]
Thanks @Orefie for your information

**Comment by nickolay** [comment]
Curiously, my X96Max_Plus_2101W is very similar, but not identical: the soc, RAM/LAN/radio, board label are the same, but the board is not identical, e.g. the thing before the LAN controller ([ethernet magnetic transformer](https://networkengineering.stackexchange.com/questions/29927/what-is-the-purpose-of-an-ethernet-magnetic-transformer-and-how-are-they-used)?) is different; mine is G2406S.

`meson-sm1-x96-max-plus.dts` does not boot for me at all, while `meson-sm1-x96-max-plus-q1.dtb` does.

Ethernet doesn't work for me (and I can't debug it, as the TV is far from the router:) I used Armbian_23.05.0_amlogic_s905x3_bullseye_5.15.112_server_2023.05.18.img.gz. **@Orefie, care to share which image worked for you?**

![IMG_3128](https://github.com/ophub/amlogic-s9xxx-armbian/assets/247067/56f942c7-934c-49e4-a54d-dd68e2ff7b02)


*(the (lack of) wireless driver for W522A/W150S1 is discussed in #566)*

**Comment by 0ktav1us** [comment]
Hello, Have the same 2101w and trouble with bt/wifi. how i can help add support W522A ?

**Comment by JohnTaylorHK** [comment]
Hi Guys,

Sorry for being late to the party. After getting an old MXQPro TV box to function properly with Armbian, I just got hold of exactly the same box X96Max_Plus_2101W. Would you kindly point me towards a working image for this box. I see above that you mentioned Armbian_23.05.0_amlogic_s905x3_bullseye_5.15.112_server_2023.05.18.img.gz with  meson-sm1-x96-max-plus-q1.dtb. Is this the genral consensus? Are there other images/blobs that "sort of work". I'm looking to get heavily into making the box fully functional and would be more than happy to provide some help with projects once I'm up and running. Best Regards, JT

**Comment by RobotsAreCrazy** [comment]
Does anyone have a copy of the stock firmware  for x96 max plus v2101w on android 8-9 please?
