### ISSUE TITLE
Tanix TX3-H 4GB ram 64GB rom

### ISSUE THREAD

**Issue by bugalaws** [ophub/amlogic-s9xxx-armbian#931]
Standard chat template, no routine, no chat.

**Device Information
 - SOC: S905x3
 - Model TX3-H

**Armbian Version 
 - Kernel Version: 5.15.88
 - Release: Bullseye

**Describe the bug
Hi Guys, i got a problem with the memory on the TX3-H Box, I’m using the meson-sm1-tx3-bz.dtb.

When I boot from the pendrive or sd card the system recognize 4GB of ram normaly

But after the system be instaled into eMMC the system recognize only 2gb of ram, when i run the armbian-install i have selected the meson-sm1-tx3-bz.dtb too…

 Someone can help me?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#1212-memory-size-recognition-error

view: 12.12
