### ISSUE TITLE
稳定的双频USB无线网卡型号

### ISSUE THREAD

**Issue by dapengg** [ophub/amlogic-s9xxx-armbian#936]
大佬们,有什么稳定的双频USB无线网卡型号？自己不会装驱动最好是免驱的

**Comment by ophub** [comment]
mtk或ralink的，mt7601u既便宜也稳定，不过只是单频2.4g的，如果要双频的话可以选mt7610u

**Comment by dapengg** [comment]
某宝输入mt7610u无商品。很多商家也不标注用的什么芯片，有什么推荐的品牌型号吗？
