### ISSUE TITLE
update失败后无法启动

### ISSUE THREAD

**Issue by OwnerCM** [ophub/amlogic-s9xxx-armbian#937]
**Device Information | 设备信息**
 - SOC: s095l3a
 - Model: m401a

**Armbian Version | 系统版本**
 - Kernel Version: 5.15.86
 - Release: bullseye

**Describe the bug | 问题描述**
好奇心驱使的情况下执行了更新，更新失败后重启失败，更新结果如下

armbian:/boot:# armbian-update
[ STEPS ] Ready to update, please wait...
[ STEPS ] Start initializing the environment...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ INFO ] Set the kernel name: [  ]
[ INFO ] Set the kernel directory: [ stable ]
[ INFO ] Current version: 5.15.86, Latest version: 5.15.88
[ STEPS ] Start downloading the kernel from [ https://github.com/ophub/kernel/tree/main/pub/stable/5.15.88 ]...
A    .
A    boot-5.15.88-happy-new-year.tar.gz
A    dtb-allwinner-5.15.88-happy-new-year.tar.gz
A    dtb-amlogic-5.15.88-happy-new-year.tar.gz
A    dtb-rockchip-5.15.88-happy-new-year.tar.gz
A    header-5.15.88-happy-new-year.tar.gz
A    modules-5.15.88-happy-new-year.tar.gz
A    sha256sums
Exported revision 706.

[ STEPS ] Start checking the kernel...
[ INFO ] Kernel name: [ 5.15.88-happy-new-year ]
[ INFO ] K510: [ 0 ]
[ INFO ] Enable sha256sum checking...
[ INFO ] (1/4) [ boot-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.
[ INFO ] (2/4) [ dtb-amlogic-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.
[ INFO ] (3/4) [ header-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.
[ INFO ] (4/4) [ modules-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.

[ STEPS ] Start unpacking the kernel...
[ INFO ] (1/4) Unpacking [ boot-5.15.88-happy-new-year.tar.gz ] done.
tar (child): dtb-amlogic-5.15.88-happy-new-year.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[ ERROR ] /boot/dtb/amlogic files is missing.

**Comment by OwnerCM** [comment]
更新失败的原因会不会是空间不足？
![image](https://user-images.githubusercontent.com/22722811/212628821-a9846ec2-1125-49b1-b93c-0291956dbacc.png)

**Comment by ophub** [comment]
你的boot占用有点不合理，正常没那么大，你存放什么了？

![Snip20230116_3](https://user-images.githubusercontent.com/68696949/212632720-41a79540-0f9e-4ebe-bef4-a225c8a3e299.png)
![Snip20230116_5](https://user-images.githubusercontent.com/68696949/212632727-578e7ef1-e2e1-4002-be55-b2ae5a2db047.png)

**Comment by serrj-sv** [comment]
I have the same issue on freshly installed X96 Max Plus2

```
root@nvr:/boot# uname -a
Linux nvr 5.15.87-happy-new-year #1 SMP PREEMPT Fri Jan 13 13:21:09 CST 2023 aarch64 GNU/Linux
root@nvr:/boot# armbian-update
[ STEPS ] Ready to update, please wait...
[ STEPS ] Start initializing the environment...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ INFO ] Set the kernel name: [  ]
[ INFO ] Set the kernel directory: [ stable ]
[ INFO ] Current version: 5.15.87, Latest version: 5.15.88
[ STEPS ] Start downloading the kernel from [ https://github.com/ophub/kernel/tree/main/pub/stable/5.15.88 ]...
A    .
A    boot-5.15.88-happy-new-year.tar.gz
A    dtb-allwinner-5.15.88-happy-new-year.tar.gz
A    dtb-amlogic-5.15.88-happy-new-year.tar.gz
A    dtb-rockchip-5.15.88-happy-new-year.tar.gz
A    header-5.15.88-happy-new-year.tar.gz
A    modules-5.15.88-happy-new-year.tar.gz
A    sha256sums
Exported revision 706.

[ STEPS ] Start checking the kernel...
[ INFO ] Kernel name: [ 5.15.88-happy-new-year ]
[ INFO ] K510: [ 0 ]
[ INFO ] Enable sha256sum checking...
[ INFO ] (1/4) [ boot-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.
[ INFO ] (2/4) [ dtb-amlogic-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.
[ INFO ] (3/4) [ header-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.
[ INFO ] (4/4) [ modules-5.15.88-happy-new-year.tar.gz ] file sha256sum check same.

[ STEPS ] Start unpacking the kernel...
[ INFO ] (1/4) Unpacking [ boot-5.15.88-happy-new-year.tar.gz ] done.
tar (child): dtb-amlogic-5.15.88-happy-new-year.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
[ ERROR ] /boot/dtb/amlogic files is missing.
```

**Comment by ophub** [comment]
我反复更新了5.15.87 -- 5.15.88几次，都可以正常下载更新。你检查下/boot下多了什么，删除不用的占用。

![Snip20230116_6](https://user-images.githubusercontent.com/68696949/212646973-074c1a36-4be1-42d2-ad96-b81f16bf3bd2.png)
![Snip20230116_7](https://user-images.githubusercontent.com/68696949/212646999-b457c5c1-1c60-48f3-84a3-78cd5e187cd6.png)

**Comment by ophub** [comment]
因为加了md5校验，所以文件是完整的才更新，所以更新失败很少见到。boot基本上是等量替换，占用空间应该不会有大的增长。

我想了想，以后要不要在更新前先备份一下原内核，这样失败了就自动还原。

**Comment by OwnerCM** [comment]
> 你的boot占用有点不合理，正常占用没那么大，你存放什么了？
> 
> ![Snip20230116_3](https://user-images.githubusercontent.com/68696949/212632720-41a79540-0f9e-4ebe-bef4-a225c8a3e299.png) ![Snip20230116_5](https://user-images.githubusercontent.com/68696949/212632727-578e7ef1-e2e1-4002-be55-b2ae5a2db047.png)

一开始只boot占用40%，是更新操作后占用85%的

**Comment by OwnerCM** [comment]
> 因为加了md5校验，所以文件是完整的才更新，所以更新失败很少见到。boot基本上是等量替换，占用空间应该不会有大的增长。
> 
> 我想了想，以后要不要在更新前先备份一下原内核，这样失败了就自动还原。

我现在的问题是重启无法开机了，请问这种情况是不是只能重新刷机？

**Comment by ophub** [comment]
u盘刷系统，从U盘启动后，把emmc挂载到U盘的某个目录，然后手动把内核解压到对应的目录即可修复。

**Comment by ophub** [comment]
-k是可选参数，用于指定固定版本的内核，不使用就是自动更新为最新。


https://github.com/ophub/amlogic-s9xxx-armbian/blob/f864a9826edf1a93f0a36c79d273eec430281c9b/build-armbian/armbian-files/common-files/usr/sbin/armbian-update#L291


看脚本里面的更新方法

**Comment by ophub** [comment]
Yes, usually do not write other files into /boot, this is the boot partition, and some boxes have less space

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/90d3f98b0faa905abcd63262793823c5ba109f5d
我升级了一下内核更新工具，现在使用在线下载时将保存在/tmp/下的临时目录。使用当前目录下的本地内核进行更新前，也会先把内核移动到/tmp/下的临时目录。这样避免了有人可能在/boot下执行内核下载更新时，空间不足的问题。



![Snip20230117_2](https://user-images.githubusercontent.com/68696949/212801183-03200363-0714-46a2-b4f7-e35f836b15a2.png)

![Snip20230117_3](https://user-images.githubusercontent.com/68696949/212801190-91d8caf6-68b8-4091-a461-983a8c7f441d.png)

**Comment by ophub** [comment]
/usr/lib/modules/*
/boot/* (除uEnv.txt)

**Comment by ophub** [comment]
uEnv.txt里面有UUID
你可以从 emmc里的/etc/fstab文件里看一下值，改到emmc的uEnv.txt里。

只要上面两个目录对就可以启动

**Comment by OwnerCM** [comment]
> 



> uEnv.txt里面有UUID 你可以从 emmc里的/etc/fstab文件里看一下值，改到emmc的uEnv.txt里。
> 
> 只要上面两个目录对就可以启动

非常感谢，从上面的报错已经能看到UUID了，我试试这个方法。另外如果不得不重装的情况下，请问是否有方法保留数据的方式重装系统。

**Comment by ophub** [comment]
不用重装，更新内核就是/boot和/usr/lib/modules这两个目录（还有一个header和启动无关，不自定义编译驱动用不到，可忽略）的文件换了一套新的。你手动更换和脚本更换结果是一样的，只要删了原来的，复制新的肯定可以。

**Comment by OwnerCM** [comment]
> 不用重装，更新内核就是/boot和/usr/lib/modules这两个目录（还有一个/usr/src/linux-headers-*和启动无关了，不自定义编译驱动用不到，可忽略）的文件换了一套新的。你手动更换和脚本更换结果是一样的，只要删了原来的，复制新的肯定可以。

OK了，感谢O大春节期间还这么及时的答复，祝O大新年快乐，事业蒸蒸日上！！！

**Comment by ophub** [comment]
恭喜你，力挽狂澜救金砖，新年更上一层楼。
