### ISSUE TITLE
编译内核提示warning

### ISSUE THREAD

**Issue by Anywherexu** [ophub/amlogic-s9xxx-armbian#941]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

Annotations
1 warning
[build](https://github.com/Anywherexu/amlogic-s9xxx-armbian/actions/runs/3923877379/jobs/6707757104#step:4:1)
**_Unexpected input(s) 'kernel_source', valid inputs are ['build_target', 'armbian_path', 'armbian_board', 'armbian_kernel', 'version_branch', 'auto_kernel', 'armbian_size', 'armbian_fstype', 'armbian_sign', 'kernel_version', 'kernel_auto', 'kernel_package', 'kernel_sign', 'kernel_repo', 'kernel_config'_**]
这个应该如何解决？？？

**Comment by ophub** [comment]
同步最新的源码，我看你的很多文件都是老版的，根目录下的action.yml参数名有错的
