### ISSUE TITLE
Reflash Original Bootloader

### ISSUE THREAD

**Issue by bugalaws** [ophub/amlogic-s9xxx-armbian#942]
Standard chat template, no routine, no chat.

**Device Information **
 - SOC: [S095x3
 - Model [TX3-H

**Armbian Version**
 - Kernel Version: 5.15.85
 - Release:Bullseye

**Describe the bug | 问题描述**
Hey Guys I need one more some help, I still have problem with the TX3-H recognizing only 2GB of RAM, I read in some forum to try the follow command to instal armbian:

armbian-install -m yes -a no

After this, Tthe boot are diferent, now I can't restore the android because the PC don't recognize the box anymore, 

I still can boot from pendrive, still boot from emmc but i got annoter errors, now the armbian recognize the 4GB of ram but the network don't work, I want to install the android and reinstal the armbian again, but after i run the "armbian-install -m yes -a no" i can't flash android anymore...

Someone can help me how can i reflash the original boot loader ?

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/documents#123-how-to-restore-the-original-android-tv-system

view 12.3

**Comment by ophub** [comment]
view `12.3.2`
