### ISSUE TITLE
rtl8811cu无线网卡驱动安装

### ISSUE THREAD

**Issue by dapengg** [ophub/amlogic-s9xxx-armbian#943]
![QQ图片20230117140333](https://user-images.githubusercontent.com/64346391/212822009-654e2ef8-3c5c-460d-9ce3-e1f9220dbca8.png)
设备是M401A Armbian 23.02.0-trunk Bullseye with Linux 6.1.4-flippy-81+

**Comment by ophub** [comment]
解决办法如图所示

**Comment by iamhyde** [comment]
> ![QQ图片20230117140333](https://user-images.githubusercontent.com/64346391/212822009-654e2ef8-3c5c-460d-9ce3-e1f9220dbca8.png) 设备是M401A Armbian 23.02.0-trunk Bullseye with Linux 6.1.4-flippy-81+

请教下同样买了这款网卡,插上然后按教程安装好驱动重启后还是没有wifi呢?中途的LOG和你的一样,armbian-config里面还是没有出现wifi选项

**Comment by ophub** [comment]
仔细看日志，日志准确地介绍了你的问题，现在armbian里面用的内核是clang编译的，而你的命令使用gcc，这不一致无法编译。

内核可以用gcc和clang这些不同的编译器，你可以自己编一个gcc版的内核并更新到armbian然后在里面用gcc编你的无线驱动。具体方法看仓库里内核自定义编译的文档。

**Comment by iamhyde** [comment]
> 仔细看日志，日志准确地介绍了你的问题，现在armbian里面用的内核是clang编译的，而你编无线驱动用的命令是使用gcc，这不一致所以无法编译。
> 
> 内核可以用gcc和clang这些不同的编译器，你可以自己编一个gcc版的内核并更新到armbian然后在里面用gcc编你的无线驱动。具体方法看仓库里内核自定义编译的文档。
> 
> 你也可以改git clone到本地的无线驱动的编译代码，把gcc换成clang，方法网络搜索。

O大,我用这个方法改clang还是报错,麻烦看看:
apt install llvm clang dkms bc
git clone https://github.com/fastoe/RTL8811CU.git
cd RTL8811CU
export CC=clang
make
![daacd909c1d0104a64ec9880807daba](https://user-images.githubusercontent.com/63632275/218003985-67197ec1-c4dd-4633-a672-cdaa07f8fde2.png)

**Comment by ophub** [comment]
你看日志提示，gcc无效选项

**Comment by iamhyde** [comment]
> 你看日志提示，gcc无效选项

o大方便指导下吗?后面就不太懂了
