### ISSUE TITLE
MGV2000, 可以U盘启动, armbian-install时候找不到EMMC设备

### ISSUE THREAD

**Issue by hoyzhang** [ophub/amlogic-s9xxx-armbian#946]
**Device Information | 设备信息**
 - SOC: [S905L3]
 - Model [MGV2000]，UWE5621DSWIFI芯片，咪咕盒子爱家TV 2+16G，支持蓝牙语音，支持无线。
 - amlogic-dt-id: gxlx2_p291_2g

**Armbian Version | 系统版本**
Armbian_23.02.0_amlogic_s905l2_jammy_5.15.86_server_2023.01.11.img
uboot.ext 使用 u-boot-p212.bin
dtb 使用 meson-gxl-s905l2-x7-5g.dtb

**Describe the bug | 问题描述**
MVG2000, 可以U盘启动, armbian-install时候找不到EMMC设备。用盒子开关重启，每次都可以从U盘启动。偶尔，很少时候，能发现emmc设备，但是执行armbian-install，也是提示不能写入。

![4444](https://user-images.githubusercontent.com/6406376/212933931-82ccda2e-2bdf-4031-96c3-dc7dac967142.png)

![1111](https://user-images.githubusercontent.com/6406376/212932516-782c698f-c17c-4703-9265-f21cae31ef26.png)

![2222](https://user-images.githubusercontent.com/6406376/212932181-39995b46-b492-4e38-9187-48f14b802445.png)

![3333](https://user-images.githubusercontent.com/6406376/212932335-9b788e33-3ff8-4d62-b49a-dca0836ed438.png)

**Comment by ophub** [comment]
[meson-gxl-s905l2-e900v21e.dtb.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10434100/meson-gxl-s905l2-e900v21e.dtb.zip)

下载这个文件，解压缩成dtb后缀，上传到/boot/dtb/amlogic目录里，修改/boot/uEnv.txt文件里dtb的名字为`meson-gxl-s905l2-e900v21e.dtb`

保存，重启试试lsblk能不能看到emmc了。

**Comment by hoyzhang** [comment]
还是找不到 ...

![5555](https://user-images.githubusercontent.com/6406376/212942553-0d68e787-b3ff-4e09-a3b7-14bd853b50fa.png)

**Comment by ophub** [comment]
cat /boot/uEnv.txt
ls -l /boot/u-boot*

**Comment by hoyzhang** [comment]
![z1](https://user-images.githubusercontent.com/6406376/212944531-2556f397-6c45-44a0-86f6-7ce5c41ee0f5.png)
需要换内核吗？

**Comment by ophub** [comment]
怎么你的u-boot.ext的大小和哪个都不一样大？删除这个文件重启试试

**Comment by hoyzhang** [comment]
是因为我直接重命名了，从这个文件 u-boot-p212.bin

**Comment by hoyzhang** [comment]
> 是因为我直接重命名了，从这个文件 u-boot-p212.bin

正在更新内核，等会试试

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

用错了吧。
你改名就别写emmc了，这文件改名后一写入就砖了。

**Comment by livelier** [comment]
偶尔能发现，估计又是个弱体质颗粒。

**Comment by ophub** [comment]
如果拔插电源还是无法启动，你刷5.15，只改dtb，不添加u-boot看看，如果也能启动，正常识别有线，就一直使用5.15吧。如果不能启动再复制u-boot

**Comment by hoyzhang** [comment]
> 偶尔能发现，可能又是个弱体质颗粒。
> 
> 建议尝试 emmc 降频 至 100Mhz 50Mhz 25Mhz 或者取消 mmc-ddr-1_8v 和 mmc-hs200-1_8v 支持。

DTB 具体哪一项，怎么修改呢？多谢～

**Comment by hoyzhang** [comment]
> 

昨天用这个u-boot-s905x-s912.bin只能启动一次U盘，删除uEnv.txt也无用。只能改重刷U盘，改回去。

**Comment by hoyzhang** [comment]
> 



> 上面的e900v21e就是用meson-gxl-s905l2-x7-5g.dtb降频到100的修改版，如果不行可以再降低试试。
> 
> 你换5.10内核以后，如果拔插电源还是无法启动，你刷5.15，只改dtb，不添加u-boot看看，如果也能启动，正常识别有线，就一直使用5.15吧。如果不能启动再复制u-boot

一会我再试试

**Comment by ophub** [comment]
不能删除uEnv.txt

**Comment by hoyzhang** [comment]
> 不能删除uEnv.txt

打错了，是删除u-boot.ext，也无用。。

**Comment by hoyzhang** [comment]
> 上面的e900v21e就是用meson-gxl-s905l2-x7-5g.dtb降频到100的修改版，如果不行可以再降低试试。
> 
> 你换5.10内核以后，如果拔插电源还是无法启动，你刷5.15，只改dtb，不添加u-boot看看，如果也能启动，正常识别有线，就一直使用5.15吧。如果不能启动再复制u-boot

用原来5.15.86的IMAGE，u-boot-p212.bin复制出成uboot.ext，meson-gxl-s905l2-x7-5g.dtb可以启动
DTB改成 e900v21e无法启动。

**Comment by ophub** [comment]
复制u-boot-s905x-s912.bin为u-boot.ext启动不了？

**Comment by hoyzhang** [comment]
> 复制u-boot-s905x-s912.bin为u-boot.ext启动不了？

是的。现在都是没显示的，路由器看不到IP，ssh也连接不上

**Comment by hoyzhang** [comment]
> 复制u-boot-s905x-s912.bin为u-boot.ext启动不了？

只能启动一次U盘，之后关机重启启动不了

**Comment by hoyzhang** [comment]
DTB取消 mmc-ddr-1_8v 和 mmc-hs200-1_8v 支持， 重新编译回去。然后
armbian-install时候，又出错了，


[ INFO ] Formatting ROOTFS partition.
mkfs.ext4: Input/output error while writing out and closing file system
mount: /ddbr/install: wrong fs type, bad option, bad superblock on /dev/mmcblk2p2, missing codepage or helper program, or other error.
[ ERROR ] Failed to mount ROOTFS partition

**Comment by hoyzhang** [comment]
DTB取消 mmc-ddr-1_8v 和 mmc-hs200-1_8v 支持， 重新编译回去。然后
armbian-install时候，又出错了，


[ INFO ] Formatting ROOTFS partition.
mkfs.ext4: Input/output error while writing out and closing file system
mount: /ddbr/install: wrong fs type, bad option, bad superblock on /dev/mmcblk2p2, missing codepage or helper program, or other error.
[ ERROR ] Failed to mount ROOTFS partition

**Comment by hoyzhang** [comment]
写入到EMMC一半出错。是执行mkfs.ext4时候出错，用fdisk处理了emmc分区，新建了一个分区。然后，重新出来也进去不U盘系统了。
线刷回安卓也不行，变砖了。
![Q1](https://user-images.githubusercontent.com/6406376/213168023-2ba7e876-bb9b-4de2-a7f6-c0959f45a234.png)

**Comment by livelier** [comment]
使用你盒子匹配的安卓固件，线刷恢复安卓系统。之后你需要解决的问题:

1、确定存储芯片是否为emmc
a). 需要提供拆解盒子拍照，照片要可以看清楚芯片上的文字。
b). 在盒子正常使用的安卓系统中提取dtb文件。
    或者提供可以恢复安卓系统的刷机包其中包含dtb文件。

2、是 emmc存储 但不识别，或偶尔识别
根据帖子分享案例，常见原因是芯片弱体质。目前常见解决方法调整emmc时钟频率。

根据第1点你的反馈确认后，我根据你下边这个组合偶尔能识别emmc?的dtb给你修改几个版本。
在使用usb启动后可以稳定的识别emmc之前不要写入emmc。

> Armbian Version | 系统版本
> Armbian_23.02.0_amlogic_s905l2_jammy_5.15.86_server_2023.01.11.img
> uboot.ext 使用 u-boot-p212.bin
> dtb 使用 meson-gxl-s905l2-x7-5g.dtb

3、是 nand 存储
目前o大的发行版 还没有成功案例分享。我的s905w盒子是3d nand存储，目前还在折腾中。

**Comment by hoyzhang** [comment]
> 使用你盒子匹配的安卓固件，线刷恢复安卓系统。之后你需要解决的问题:
> 
> 1、确定存储芯片是否为emmc a). 需要提供拆解盒子拍照，照片要可以看清楚芯片上的文字。 b). 在盒子正常使用的安卓系统中提取dtb文件。 或者提供可以恢复安卓系统的刷机包其中包含dtb文件。
> 
> 2、是 emmc存储 但不识别，或偶尔识别 根据帖子分享案例，常见原因是芯片弱体质。目前常见解决方法调整emmc时钟频率。
> 
> 根据第1点你的反馈确认后，我根据你下边这个组合偶尔能识别emmc?的dtb给你修改几个版本。 在使用usb启动后可以稳定的识别emmc之前不要写入emmc。
> 
> > Armbian Version | 系统版本
> > Armbian_23.02.0_amlogic_s905l2_jammy_5.15.86_server_2023.01.11.img
> > uboot.ext 使用 u-boot-p212.bin
> > dtb 使用 meson-gxl-s905l2-x7-5g.dtb
> 
> 3、是 nand 存储 目前o大的发行版 还没有成功案例分享。我的s905w盒子是3d nand存储，目前还在折腾中 #884

线刷无法恢复，应该是EMMC分区表坏了。然后，拆过机器，芯片是S905L3的。确定是EMMC的。
这是之前在U盘启动的armbian系统下，执行格式化的一个命令。
![Z3](https://user-images.githubusercontent.com/6406376/213191555-90837f0e-8ba2-4878-a42a-ffd60f0aa049.png)

**Comment by hoyzhang** [comment]
![E1](https://user-images.githubusercontent.com/6406376/213204013-33632f73-8915-4b04-9d2d-64df85cfc4eb.png)
![E2](https://user-images.githubusercontent.com/6406376/213204097-757c85c1-633c-4e2b-a97d-2fa5c885718c.png)
![E3](https://user-images.githubusercontent.com/6406376/213204099-e28140ca-6983-4bd6-b20c-ce9bf769c264.png)
![E4](https://user-images.githubusercontent.com/6406376/213204102-c3571082-9316-4bd9-8983-44339810ef32.png)

**Comment by livelier** [comment]
找到你这款盒子支持nand版本的安卓线刷包，分区表在刷机包里有，盒子里的损坏了没关系，线刷可以恢复。

nand armbian 等等吧，目前没有成功案例。

@ophub o大，看来以后不识别emmc，要提供一下照片好对症下药。

**Comment by hoyzhang** [comment]
> 找到你这款盒子支持nand版本的安卓线刷包，分区表在刷机包里有，盒子里的损坏了没关系，线刷可以恢复。
> 
> nand armbian 等等吧，目前没有成功案例。
> 
> @ophub o大，看来以后不识别emmc，要提供一下照片好对症下药。

原版安卓的img我都有备份，并且做成了线刷包。但是仍然无法恢复。提示刷机成功，但是开机就是不行。

**Comment by ophub** [comment]
好的👌以后看图识货。

线刷时U B T工具右侧那两个勾选上试试。

**Comment by hoyzhang** [comment]
> 好的ok_hand以后看图识货。
> 
> 线刷时U B T工具右侧那两个勾选上试试。

试过的。其实，能否做个TV BOX的APK，一打开就显示各种类型，这样都方便些。

**Comment by livelier** [comment]
从截图上看，你这应该是zip卡刷包 解压后的文件。
nand版线刷包制作方法可能与emmc版不同。

比起apk，拆开盒子更简单捏，简单粗暴，包治百病。

**Comment by hoyzhang** [comment]
是安卓4.4.2，
img是我在adb用dd备份的。然后用一工具生成了线刷包，aml_upgrade_package_new.img类似这样的文件名。

**Comment by hoyzhang** [comment]
> 是安卓4.4.2， img是我在adb用dd备份的。然后用一工具生成了线刷包，aml_upgrade_package_new.img类似这样的文件名。
> 
> 当然我也试了之前网上下载的其他线刷包，同样是一开机logo之后就进入了那个维修界面。

线刷包并不会处理emmc分区，是不是？

**Comment by livelier** [comment]
data分区，看你刷机选项而定。

**Comment by hoyzhang** [comment]
> data分区，看你刷机选项而定。

被我在armbian的fdisk搞坏了
