### ISSUE TITLE
(tanix tx3) Alert :UUID= does not exist

### ISSUE THREAD

**Issue by htcheroportugal** [ophub/amlogic-s9xxx-armbian#948]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [Tanix tx3-H]

**Armbian Version | 系统版本**
 - Kernel Version: [???]
 - Release: [Armbian_bullseye_01.16.0109]

**Describe the bug | 问题描述**
I tried all dtb for tanix tx3 bz,qz and sei610 all of them shows up what i show below

https://imgur.com/a/2BLRpmA
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

根据那块银光闪闪的暖气片下盖着的千百兆工程选择配套设施
