### ISSUE TITLE
Problem with building an image

### ISSUE THREAD

**Issue by TimurIT** [ophub/amlogic-s9xxx-armbian#949]
You have some kind of problem with building an image with a newer kernel version for S905X. 
The initial loading of the kernel does not occur. 

For example: 
Now there are two kernel versions 6.1.6 and 5.15.88. 
6.1.6 not run, 
5.15.88 run. 

5.15.52 not run
5.10.128 run

All previous releases of your images over the past year behave the same way. The newer version of the kernel does not start, and the older one starts

**Comment by ophub** [comment]
what device

**Comment by TimurIT** [comment]
Custom operator TVbox (NetUP Android IP STB v.2.0) S905X p212
