### ISSUE TITLE
tanix tx3-h (no phy at addr -1 . cannot attacht to phy

### ISSUE THREAD

**Issue by htcheroportugal** [ophub/amlogic-s9xxx-armbian#951]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

Device Information | 设备信息

SOC: [S095x3]
Model [Tanix tx3-H]
Armbian Version | 系统版本

Kernel Version: [???]
Release: [Armbian_23.02.0_amlogic_s905x_jammy_5.15.88_server_2023.01.16]
Describe the bug | 问题描述
hello i tried install jammie release i tested all dtb for my box tanix tx3-h

tanix tx3-H cs_905x3 _b4_vv1

and i get this issue, show below
https://imgur.com/a/T88gijK
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
what chip is your network card

**Comment by htcheroportugal** [comment]
Do you know were i can find it to say to you?

**Comment by ophub** [comment]
Check if the network card chip on the motherboard is RTL8211F

**Comment by htcheroportugal** [comment]
I am trying to look for this number, can you help where i can find this? i cant find, where it is.
Below you can see two images:

https://imgur.com/a/rvtF0VX

**Comment by ophub** [comment]
![Snip20230119_2](https://user-images.githubusercontent.com/68696949/213365877-c5e6cb0a-ed7f-4208-b712-d268efae99e9.png)

**Comment by partizan4ez** [comment]
Привет, у меня аналогичная проблема, tx3 4/32,  armbian bullseye 15.88, спамит этой ошибкой в логе, а раз в сутки зависает и помогает только перезагрузка электропитания, вчера ставил 6.1.6 так же спамит ошибка. Работает только WiFi, eth0 не работает. До 16 января все работало отлично, обновился и начала зависать. Шил версию 512, на 514 работает не стабильно

**Comment by ophub** [comment]
![Snip20230119_4](https://user-images.githubusercontent.com/68696949/213388800-2b03df2a-6ad6-4f93-9e6b-cf6f12bd1d4f.png)
tx3-H(s905x3) network card chip RTL8211F, I have used it for a year, very stable

**Comment by htcheroportugal** [comment]
My chip card is not RTL8211F, on the chip i see just a lot of numbers

**Comment by htcheroportugal** [comment]
> Hi, I have a similar problem, tx3 4/32, armbian bullseye 15.88, spamming this error in the log, and once a day it freezes and only a power reset helps, yesterday I put 6.1.6 also spamming an error. Only WiFi works, eth0 does not work. Until January 16, everything worked fine, it was updated and started to hang. Sewed version 512, 514 does not work stably

Can you Share with me , your image? My tx3-h os 4/64

**Comment by partizan4ez** [comment]
> 

https://i.imgur.com/oxl9AUl.png
