### ISSUE TITLE
Custom build. Armbian-install process runs without errors, but the system does not boot

### ISSUE THREAD

**Issue by HelferP** [ophub/amlogic-s9xxx-armbian#953]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC:  S095x3
 - Model H96max X3
**Armbian Version | 系统版本**
 - Kernel Version: 5.15.88
 - Release: jammy

**Describe the bug | 问题描述**
Hey!
Help me please figure it out. I build armbian minimal.
With sd everything works fine, there are no problems.
I'm trying to install in emmc. At first I noticed that there is no mkfs.vfat package in the assembly. Installed dosfstools. 
Now the armbian-install process runs without errors, but the system does not boot. Black screen on reboot and nothing happens.
Perhaps there are still dependencies that are not present in the minimal build?

All the fixes I made here https://github.com/ophub/amlogic-s9xxx-armbian/commit/b611edd2670ef66db75be6a810343485675e9ffd
Release here https://github.com/HelferP/amlogic-s9xxx-armbian/releases/tag/Armbian_jammy_01.18.1332

**Comment by HelferP** [comment]
How to find out where the error is?

**Comment by ophub** [comment]
Can the non-mini version be used normally?

**Comment by HelferP** [comment]
> Can the non-mini version be used normally?
Yes, now it work fine.

**Comment by HelferP** [comment]
> I didn't add dependency checks in armbian-install

I found the problem!
The mini-build  missing bsdmainutils and dosfstools packages.
Please add a check when calling [hexdump](https://github.com/ophub/amlogic-s9xxx-armbian/blob/ac589c94adaf8d08291cf5cddd903a0ad0711e0f/build-armbian/armbian-files/platform-files/amlogic/rootfs/usr/sbin/armbian-install#L159) and [mkfs.vfat](https://github.com/ophub/amlogic-s9xxx-armbian/blob/ac589c94adaf8d08291cf5cddd903a0ad0711e0f/build-armbian/armbian-files/platform-files/amlogic/rootfs/usr/sbin/armbian-install#L393) functions

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/661fdd375cc3b0c38b72705902788c039b6a1133
already added
