### ISSUE TITLE
内核编译遇到问题，请教

### ISSUE THREAD

**Issue by Anywherexu** [ophub/amlogic-s9xxx-armbian#955]
编译完成临近结束提示错误
**_ld.lld: error: undefined symbol: cfg80211_del_sta_sinfo
>>> referenced by irqbypass.c
>>>               vmlinux.o:(ap_free_sta)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_sta_disassoc)

ld.lld: error: undefined symbol: ieee80211_freq_khz_to_channel
>>> referenced by irqbypass.c
>>>               vmlinux.o:(p2p_protocol_wk_hdl)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(cfg80211_rtw_remain_on_channel)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(cfg80211_rtw_mgmt_tx)

ld.lld: error: undefined symbol: cfg80211_remain_on_channel_expired
>>> referenced by irqbypass.c
>>>               vmlinux.o:(p2p_protocol_wk_hdl)

ld.lld: error: undefined symbol: wiphy_unregister
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_os_ndev_register)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_os_ndev_unregister)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_wiphy_unregister)

ld.lld: error: undefined symbol: cfg80211_michael_mic_failure
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_handle_tkip_mic_err)

ld.lld: error: undefined symbol: ieee80211_get_channel_khz
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_ch_switch_notify)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_inform_bss)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_check_bss)
>>> referenced 3 more times

ld.lld: error: undefined symbol: cfg80211_ch_switch_notify
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_ch_switch_notify)

ld.lld: error: undefined symbol: cfg80211_inform_bss_frame_data
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_inform_bss)

ld.lld: error: undefined symbol: cfg80211_put_bss
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_inform_bss)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_check_bss)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_unlink_bss)

ld.lld: error: undefined symbol: cfg80211_get_bss
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_check_bss)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_unlink_bss)

ld.lld: error: undefined symbol: cfg80211_ibss_joined
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_ibss_indicate_connect)

ld.lld: error: undefined symbol: cfg80211_roamed
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_connect)

ld.lld: error: undefined symbol: cfg80211_connect_done
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_connect)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_disconnect)

ld.lld: error: undefined symbol: cfg80211_disconnected
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_disconnect)

ld.lld: error: undefined symbol: cfg80211_scan_done
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_scan_done)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_wdev_unregister)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(cfg80211_rtw_scan)
>>> referenced 1 more times

ld.lld: error: undefined symbol: cfg80211_unlink_bss
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_unlink_bss)

ld.lld: error: undefined symbol: cfg80211_new_sta
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_indicate_sta_assoc)

ld.lld: error: undefined symbol: cfg80211_rx_mgmt_khz
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_rx_probe_request)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_rx_action_p2p)
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_rx_p2p_action_public)
>>> referenced 2 more times

ld.lld: error: undefined symbol: cfg80211_external_auth_request
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_cfg80211_external_auth_request)

ld.lld: error: undefined symbol: wiphy_new_nm
>>> referenced by irqbypass.c
>>>               vmlinux.o:(rtw_wiphy_alloc)

```
ld.lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
make: *** [Makefile:1220: vmlinux] Error 1
[ STEPS ] Install modules...
make[1]: *** No rule to make target
/home/runner/work/_actions/Anywherexu/amlogic-s9xxx-armbian/main/compile-kernel/output/modules/lib/modules/5.15.89-Andyxu/kernel/crypto/asymmetric_keys/pkcs7_test_key.ko', needed by '__modinst'.  Stop.
make: *** [Makefile:1830: modules_install] Error 2
[ STEPS ] Install headers...
find: ‘Module.symvers’: No such file or directory
[ SUCCESS ] The headers is installed successfully.
[ STEPS ] Create chroot...
cp: cannot stat /home/runner/work/_actions/Anywherexu/amlogic-s9xxx-armbian/main/compile-kernel/kernel/linux-5.15.y/System.map': No such file or directory
cp: cannot stat /home/runner/work/_actions/Anywherexu/amlogic-s9xxx-armbian/main/compile-kernel/kernel/linux-5.15.y/arch/arm64/boot/Image': No such file or directory
cp: cannot stat /home/runner/work/_actions/Anywherexu/amlogic-s9xxx-armbian/main/compile-kernel/kernel/linux-5.15.y/arch/arm64/boot/Image': No such file or directory
[ INFO ] Enter the chroot armbian system...
[ INFO ] Current system: [ aarch64 ]
[ INFO ] Current path: [ / ]_**

```

已经同步到最新的源码了。请问应该如何解决，我只是想把CAN功能添加进去。在armbian的git库里复制的can相关配置信息。不知道哪里出错了。之前5.15.83和5.15.85都编译成功过。但是再往后的就无法编译成功了。编译出来就只有37.7mb。虽然提示是编译成功，但是实际是无法使用的。

**Comment by ophub** [comment]
内核源码有错，没拉全吧

**Comment by Anywherexu** [comment]
使用make menuconfig是不是需要在本地创建编译环境？？？？云端无法make menuconfig是不？？？

**Comment by ophub** [comment]
在你的armbian先git clone内核，并make menuconfig改好配套，生成.config文件，然后可以本地编也可以actions编

**Comment by Anywherexu** [comment]
我再好好看一下教程。。。。太难了

**Comment by yunzimo** [comment]
> 我再好好看一下教程。。。。太难了

O大说的意思你明白了么，也教教我，clone unifreq的内核，本地改好配置生成.config然后怎么本地编译啊，又是怎么action编译的呢。小白的我是看的一蒙一蒙的。
