### ISSUE TITLE
请问我该如何安装omv

### ISSUE THREAD

**Issue by yx10010** [ophub/amlogic-s9xxx-armbian#957]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095d
 - Model [e.g. N1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
没有可用的软件包 phpapi-20151012，但是它被其它的软件包引用了。
这可能意味着这个缺失的软件包可能已被废弃，
或者只能在其他发布源中找到

**Comment by ophub** [comment]
我不熟悉这个，你在他的github问一下他们有影响没有。
