### ISSUE TITLE
X96Max_Plus2_AI wont boot from EMMC

### ISSUE THREAD

**Issue by whitemankpi** [ophub/amlogic-s9xxx-armbian#958]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model X96Max_Plus2_AI 4G 64G] 

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.6]
 - Release: [Armbian_23.02.0_amlogic_s905x3_jammy_6.1.6_server_2023.01.18.img]

**Describe the bug | 问题描述**
Tried to install system to EMMC by armbian-install -m yes -a no(also trying armbian-install -m yes -a yes with same result)
System
The system doesn't boot from internal memory (errors are shown in the attached screenshot), but loads from usb disk
Model ID 504 (https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md)

![photo_2023-01-19_16-48-12](https://user-images.githubusercontent.com/63373322/213473751-eec80bd3-46ac-4749-bd97-42aa8760bc6a.jpg)

**Comment by ophub** [comment]
先还原为原来的安卓系统，再armbian-install写入时不要加参数，不要使用-m yes

**Comment by whitemankpi** [comment]
> 先还原为原来的安卓系统，再armbian-install写入时不要加参数，不要使用-m yes
I apologize for the late response. I did so - the procedure was  completed successfully, but after removing the USB and resetting the console - just a black screen. And if I put back the bootable USB - the same black screen without a single log

**Comment by ophub** [comment]
try 5.15

**Comment by serrj-sv** [comment]
@whitemankpi did you managed to solve your issues? I also have X96Max_Plus2_AI model and symptoms are the same: unable to boot from emmc, disfunctional ethernet and also occasionally kernel panic

**Comment by whitemankpi** [comment]
> 

this issue helped me
https://github.com/ophub/amlogic-s9xxx-armbian/issues/953
