### ISSUE TITLE
Error when build armbian on Github action

### ISSUE THREAD

**Issue by dinhchinh82** [ophub/amlogic-s9xxx-armbian#96]
I tried to build your armbian on github action and got error below (tried several times):
<img width="1412" alt="Screen Shot 2022-01-30 at 17 47 17" src="https://user-images.githubusercontent.com/22479095/151696696-579cf00d-4d2e-4ad5-8026-bb4738afa724.png">

Every configuration is same as your default setting, I just added the custom size as below:

> sudo ./rebuild -d -b s905x3_s905x -s 6500 -k 5.4.170_5.10.90
          sudo ./rebuild -d -b s905w -s 6500 -k 5.4.170

As before, I already built S905X3 images according to your guide on github action many times.

Thank you.

**Comment by ophub** [comment]
```
LD [M]  drivers/media/dvb-frontends/stv0900.o
12776
  LD [M]  drivers/media/dvb-frontends/cxd2820r.o
12777
  LD [M]  drivers/media/dvb-frontends/drxk.o
12778
[ error ] ERROR in function compile_kernel [ main.sh:574 -> main.sh:479 -> compilation.sh:506 -> general.sh:0 ]
12779
[ error ] Kernel was not built [ @host ]
12780
[ o.k. ] Process terminated 
```

You failed in the previous step (-name: Compile Armbian), the armbian file was not generated, so the next refactoring does not have the original file.
Run it again, I compiled it last night

**Comment by dinhchinh82** [comment]
I'm trying to build again.

By the way, if I tried to re-build using the following configuration:
https://github.com/dinhchinh82/amlogic-s9xxx-armbian/blob/main/.github/workflows/rebuild-armbian-s905x3.yml

But after re-building successfully, I only got some Armbian_21.08.1 images, not the latest Armbian_22.02.0 images?

https://github.com/dinhchinh82/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_focal_2022.01.30.1409

**Comment by ophub** [comment]
You use the officially released version for refactoring, their latest version is this one.

Want to use the latest real-time compilation from source code. It is the program that you failed, and it is the latest after successful compilation.

**Comment by dinhchinh82** [comment]
Yes. What I want to do is reuse your latest build but only change the size of image to 6500.
I only just know the way to follow your guide to update rebuild script as below:

>      - name: Rebuild Armbian for Amlogic s9xxx
        uses: ophub/amlogic-s9xxx-armbian@main
        with:
          armbian_path: ${{ env.ARMBIAN_URL }}
          armbian_soc: s905x3
          armbian_kernel: 5.4.175_5.10.95
          armbian_size: 6500

Please give me your suggestion to reuse your latest images but change the armbian_size as above.

**Comment by ophub** [comment]
That's right, compile it again

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/actions/runs/1768560856

I also tested it, I just compiled this last night

**Comment by dinhchinh82** [comment]
I've just rebuilt again but still got error after 1h30m building:

https://github.com/dinhchinh82/amlogic-s9xxx-armbian/runs/4996311511?check_suite_focus=true

**Comment by ophub** [comment]
![Snip20220130_1](https://user-images.githubusercontent.com/68696949/151700507-1b769d7f-d638-4140-afc8-8103a9b41922.png)

The problem is in the previous step, armbian was not compiled. Mine is also compiling, I will try

**Comment by ophub** [comment]
I tested it just now, and the source code of armbian can't be compiled at present, wait for the upstream to fix it

**Comment by ophub** [comment]
Upstream has been fixed and can be compiled.
