### ISSUE TITLE
release 参数设置反馈

### ISSUE THREAD

**Issue by livelier** [ophub/amlogic-s9xxx-armbian#960]
**Device Information | 设备信息**
 - SOC: S095x3
 - Model ugoos x3

**Armbian Version | 系统版本**
 - Kernel Version: 6.1.7
 - Release: jammy

**Describe the bug | 问题描述**
写入emmc后第5行没有变更内容，o大，这个部分是默认不变的吗？如果是就忽略吧 😂

```
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905x3'
MODEL_NAME='X96-Max+_100Mb'
FDTFILE='meson-sm1-ugoos-x3.dtb'
UBOOT_OVERLOAD='u-boot-ugoos-x3.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/ugoos-x3-u-boot.bin.sd.bin'
BOOTLOADER_IMG='/usr/lib/u-boot/'
FAMILY='meson-sm1'
BOARD='s905x3'
KERNEL_VERSION='6.1.7'
KERNEL_BRANCH='stable'
K510='1'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
MLUBOOT_STATUS='yes'
AMPART_STATUS='no'
PACKAGED_DATE='2023-01-18'
```

**Comment by ophub** [comment]
这个之前是为了rockchip的banner名字添加的，amlogic用不到，留着错误信息有误会，我改改移除吧。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/rebuild#L424

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-fix#L79

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/1de7149a6e9860833ec283f16e9fd754bfc6e5a0

移除了，他和board相同，不再单独标记了。

**Comment by livelier** [comment]
哈哈哈，又给大神安排工作😂 我真棒👍
