### ISSUE TITLE
UNT403A怎么写入emmc

### ISSUE THREAD

**Issue by Aokio** [ophub/amlogic-s9xxx-armbian#961]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | UNT403A 2+8g 
 - SOC: [e.g. S095x3] S905L3A
 - Model [e.g. HK1]广东

**Armbian Version | 系统版本** Armbian_jammy_01.18.0157]
 - Kernel Version: [e.g. 5.15.100] 5.15.88
 - Release: [e.g. jammy] Armbian_23.02.0_amlogic_s905_jammy_6.1.6_server_2023.01.18

**Describe the bug | 问题描述** 
Describe the problem in detail and attach screenshots if necessary.
从u盘启动后写入emmc失败
选项选择302 305 306都试过了 
unt403a是不是没有对应的选项
![image](https://user-images.githubusercontent.com/12807605/213636974-7c4c73dd-39f8-4e7d-b67c-5aec5cadd269.png)

**Comment by ophub** [comment]
```
cat /boot/uEnv.txt
cat /etc/ophub-release
ls -l /boot/u-boot*
```
这个盒子以前还没收到测试反馈，安装列表里没有他的选项，你把以上这3个命令截图发下，我看看和哪个对应

**Comment by Doboo** [comment]
可以使用2022年10月份及以前的固件，选择305   2 写入emmc 但是现在的版本总是报emmc的错误。。。

**Comment by Aokio** [comment]
小黄鱼买的盒子之前刷了一个系统装了太多乱七八糟的东西想重装 询问了卖家说刷的cm311 但是我就是刷不进去 
![Snipaste_2023-01-20_16-19-35](https://user-images.githubusercontent.com/12807605/213649183-f12be714-1a3f-491e-aa4d-09567d87fa53.png)

**Comment by Aokio** [comment]
> 可以使用2022年10月份及以前的固件，选择305 2 写入emmc 但是现在的版本总是报emmc的错误。。。

正在下载 我试试旧版本305

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

你这是304的配置，你可能需要换个安卓9的系统才能正常刷入armbian

**Comment by Aokio** [comment]
目前使用了22年10月份版本的304 可以正常刷入emmc 
可能还是安卓分区的问题 用最新的版本需要先刷一个安卓9的分区

**Comment by Aokio** [comment]
UNT403旧版刷入304 有的时候重启会起不来 hdmi无显示 但是插入upan再启动一次报错后再拔掉U盘就能启动 目前还不知道什么原因  问题重现的时候我补个截图

**Comment by janko888** [comment]
你这个u盘里面/boot/uEnv.txt文件是使用e900v22c的dtb，修改成m401a的，重启后再写入emmc看看。
