### ISSUE TITLE
求助，M201-D应该用那个版本，试了几个无法刷入

### ISSUE THREAD

**Issue by LoveG1g1** [ophub/amlogic-s9xxx-armbian#962]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S0905L p211]
 - Model [M201-D
![a7f39f44db67e36aefd538997e25145](https://user-images.githubusercontent.com/107911879/213670825-1b961ad3-e4a5-4bcb-a71a-82321ef7dd30.jpg)
]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. bullseye]

**Describe the bug | 问题描述：M201-D应该用那个版本，试了几个无法刷入 图片上的情况是什么故障导致的 刷入系统的可行性？我是noob求大佬教一下

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

12.4 如果从U盘启动armbian

**Comment by Aokio** [comment]
刷入u盘的版本错了 按找说明的换一个试试 另外 u盘换一个试试 usb口换一个试试
