### ISSUE TITLE
先还原为原来的安卓系统，再armbian-install写入时不要加参数，不要使用-m yes

### ISSUE THREAD

**Issue by whitemankpi** [ophub/amlogic-s9xxx-armbian#964]
先还原为原来的安卓系统，再armbian-install写入时不要加参数，不要使用-m yes

_Originally posted by @ophub in https://github.com/ophub/amlogic-s9xxx-armbian/issues/958#issuecomment-1397905957_

  I apologize for the late response. I did so - the procedure was completed successfully, but after removing the USB and resetting the console - just a black screen. And if I put back the bootable USB - the same black screen without a single log

**Comment by whitemankpi** [comment]
Also  none of the  DTBs for -ip1001m work
 My router sees the DHCP request from TVBox, gives it the IP, but the box does not set\accept    it   
I also compiled the DTB from my TV Box's Android
Maybe this will help.

(example of ifconfig output on meson-sm1-x96-max-plus-ip1001m-2.dtb):

`root@armbian:~# ifconfig
eth0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 9e:61:74:7f:bc:aa  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
        device interrupt 22  

eth0:avahi: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 169.254.13.97  netmask 255.255.0.0  broadcast 169.254.255.255
        ether 9e:61:74:7f:bc:aa  txqueuelen 1000  (Ethernet)
        device interrupt 22  

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 18  bytes 1260 (1.2 KB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 18  bytes 1260 (1.2 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.81  netmask 255.255.255.0  broadcast 192.168.1.255
        inet6 fe80::d933:4851:5f2e:8df1  prefixlen 64  scopeid 0x20<link>
        ether fc:c2:de:91:b8:98  txqueuelen 1000  (Ethernet)
        RX packets 12705  bytes 18316937 (18.3 MB)
        RX errors 0  dropped 10  overruns 0  frame 0
        TX packets 4512  bytes 365689 (365.6 KB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0`
     
[decrypted_DTB.zip](https://github.com/ophub/amlogic-s9xxx-armbian/files/10473153/decrypted_DTB.zip)

**Comment by whitemankpi** [comment]
same issue, but was closed
https://github.com/ophub/amlogic-s9xxx-armbian/issues/258

**Comment by whitemankpi** [comment]
similar tred in CoreElec forum
https://discourse.coreelec.org/t/x96-max-revision-ai-icplus-ip1001-lan-is-not-working/16885

**Comment by ophub** [comment]
The above ifconfig shows that your mac address is recognized normally. You access the router and restart it. After a minute, look at the ip in the router
