### ISSUE TITLE
Overclocking possibility on X96-mini

### ISSUE THREAD

**Issue by delta-whiplash** [ophub/amlogic-s9xxx-armbian#966]
I managed to successfully install armbian on my x96mini I chose to put in performance mode the cpu scheduler
Now I was wondering if it was possible to do a tiny overclock of my s905w SOC something like 100mhz 
Do you have any experience with that or some usefull links about this

**Comment by ophub** [comment]
Extract dtb from your android, check its frequency settings, adjust according to official settings.
