### ISSUE TITLE
Possible wrong kernel updated

### ISSUE THREAD

**Issue by Delliaf** [ophub/amlogic-s9xxx-armbian#967]
Hi, first of all thanks for your great work. I have a problem. I have Vontar X3 on S905X3 with installed Armbian 22.11.2 Bullseye. Today I decided to update it, I don't remember what I used (apt upgrade/full update/armbian-update), But as a result, the kernel has been updated. I realized this only because I accidentally connected SSH, before reboot. In the terminal it was written instead of the logo "S905X3" - "Odroid N2", and "Kernel was updated, please reboot". Of course I reboot it, and he stopped showing signs of life. I already had this problem, but I can not do anything about it and I had to reinstall the system (I tried to copy the content of /boot but most likely this is not correct, or I did something wrong). Can you help with instructions on how to fix this. I spent too much time setting up the system and it worked perfectly. Maybe I can boot from a flash drive and copy the old kernel? I'm not good at this, and I hope you can help. And can you give me some advice on what to do to make sure this doesn't happen again?
![IMG_20230122_205727_640](https://user-images.githubusercontent.com/34547169/213932833-fe4c0e7e-f643-433a-a388-728bf6a358ce.jpg)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/761


https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-update


The old system can continue to use the previous upgrade method (but I can't remember how to use the parameters)

You can use the above method to update the old version to the new version.

If it fails to start, you can use the USB to install the armbian system, boot from the USB, and mount emmc to a certain directory of the USB (such as /opt/emmc/boot and /opt/emmc/root ). Then copy the corresponding directory in the USB to the emmc system.

/boot/
/lib/usr/modules/

As long as the kernel-related files in these two directories are complete, it can start normally.

**Comment by Delliaf** [comment]
@ophub Turns out I can just boot from a flash drive and copy /boot; /lib/usr/modules to emmc from usb same directories, and it should work?

**Comment by ophub** [comment]
Do not copy/boot/uEnv.txt in USB flash driveThe uuid in it should use the value of emmc.

**Comment by Delliaf** [comment]
For some reason it doesn't work. I copied the content of /boot (except uEnv.txt) and /usr/lib/modules (/lib/usr/modules - doesn't exist). Still no image on HDMI. I compared uuid of emmc in uEnv.txt and blkid and it's same.

**Comment by ophub** [comment]
/usr/lib/modules/*
/boot/*  
#Do not copy /boot/uEnv.txt

**Comment by Delliaf** [comment]
That's exactly what I did

**Comment by ophub** [comment]
lsblk

**Comment by Delliaf** [comment]
Is there any other reason why it might not start?

**Comment by ophub** [comment]
You are only related to these two directories because you update the kernel.

**Comment by Delliaf** [comment]
I'm not 100% sure it's just the kernel, this is just a guess

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/usr/sbin/armbian-update

This is the kernel update script, you can take a closer look at what he did.
header can be ignored.

**Comment by Delliaf** [comment]
Maybe I also need to copy the contents of the folder "/usr/src/linux-headers-*"?

**Comment by ophub** [comment]
No, it has nothing to do with startup. This is the tool that very few people use to compile certain drivers.

**Comment by Delliaf** [comment]
@ophub Can I somehow see why it is not booting via UART?

**Comment by ophub** [comment]
Don't understand UART, you still failed kernel update?

**Comment by Delliaf** [comment]
Yes, all is ok, /usr/lib/modules/*, /boot/* is same as on usb (except uEnv.txt of course), but it stil doesn't boot. If the kernel does not boot, will there be any logs?
![chrome_BXrMY9jfdH](https://user-images.githubusercontent.com/34547169/214775360-4a8d306b-6a73-41da-b4b2-ce6b2511838d.png)

**Comment by ophub** [comment]
1. 系统从usb启动
2. 挂载emmc到usb中的/mnt下
```
mkdir -p /mnt/emmc/bootfs
mkdir -p /mnt/emmc/rootfs

mount /dev/mmcblk2p1 /mnt/emmc/bootfs
mount /dev/mmcblk2p2 /mnt/emmc/rootfs
```
4. 把你的挂载结果截图：
```
ls -l /boot
ls -l /mnt/emmc/bootfs

ls -l /usr/lib/modules
ls -l /mnt/emmc/rootfs/usr/lib/modules

blkid
cat /mnt/emmc/bootfs/uEnv.txt
cat /mnt/emmc/rootfs/etc/fstab
```

**Comment by Delliaf** [comment]
@ophub, sorry for bad quality)
```
mkdir -p /mnt/emmc/bootfs
mkdir -p /mnt/emmc/rootfs
mount /dev/mmcblk2p1 /mnt/emmc/bootfs
mount /dev/mmcblk2p2 /mnt/emmc/rootfs
ls -l /boot
ls -l /mnt/emmc/bootfs
```
![1000003221](https://user-images.githubusercontent.com/34547169/214874356-b8d9d9da-7456-4425-b4c2-f7d5fa77036b.jpg)

```
ls -l /usr/lib/modules
ls -l /mnt/emmc/rootfs/usr/lib/modules

blkid
cat /mnt/emmc/bootfs/uEnv.txt
cat /mnt/emmc/rootfs/etc/fstab
```
![1000003222](https://user-images.githubusercontent.com/34547169/214874552-231d96bd-4c5f-46de-ab4a-7ad1718c3433.jpg)

**Comment by Delliaf** [comment]
> [2a75cbb](https://github.com/ophub/amlogic-s9xxx-armbian/commit/2a75cbbbdefa67a55b404db73e3a01d6074f7c55)
> 
> ```
> armbian-sync
> armbian-update -r
> ```

When booted from USB?

**Comment by ophub** [comment]
Yes, after usb booting the system, run those 2 commands.
The first command is to update the script in your usb to the latest version.
The second command is to update the system kernel currently running on the usb to emmc to achieve the rescue purpose.

**Comment by ophub** [comment]
Then your problem has nothing to do with the kernel, this method has completely repaired the kernel. About 2 minutes after booting, you can find the device named armbian in the connected router, if you can't find it, reinstall the system.

**Comment by Delliaf** [comment]
@ophub No, there is no device on the network. What else can I do? View logs via UART? Or maybe I can somehow copy the old system to a USB flash drive, and then install it on emmc?

**Comment by ophub** [comment]
The files related to startup have been processed in the above rescue operation, so I don't know why it can't start. There is no other way to help you.
