### ISSUE TITLE
章鱼星球卡第一屏

### ISSUE THREAD

**Issue by 3120374740** [ophub/amlogic-s9xxx-armbian#97]
反复第一屏，是需要改什么文件吗？

**Comment by 3120374740** [comment]
启动不起来

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2022.01.30.0148/Armbian_22.02.0_Aml_s912_focal_5.4.175_2022.01.30.0118.img.gz


什么也不用改，换U盘重刷

**Comment by 3120374740** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_Aml_focal_2022.01.30.0148/Armbian_22.02.0_Aml_s912_focal_5.4.175_2022.01.30.0118.img.gz
> 
> 什么也不用改，换U盘重刷

还是反复第一屏，可能是我章鱼星球原版bl的原因吧

**Comment by ophub** [comment]
当前盒子里最什么系统？你是在USB上反复重启？

**Comment by ophub** [comment]
要改什么文件？

**Comment by 3120374740** [comment]
> 要改什么文件？

aml_autoscript文件删除，然后把s905_autoscript重命名aml_autoscript
这样才能正常启动，现在盒子的灯是绿的

**Comment by ophub** [comment]
好吧。那你按之前的习惯修改吧。一般来说是可以直接使用的。

**Comment by Calmact** [comment]
最近新上市的一批移动盒子S905L 3A-B、S905L 3A主控的，比如E900V22C/D，性能强悍，是原来S905X2的马甲，性能大概是X3的4/5，能够从u盘启动armbian，ee，ce这些系统，使用u200的dtb。e900v22c的Q群：320724049，诚邀@ophub大神来指导工作。
