### ISSUE TITLE
cmdline.txt

### ISSUE THREAD

**Issue by uroh** [ophub/amlogic-s9xxx-armbian#971]
**Device Information | 设备信息**
 - SOC: [S095x3]
 - Model [max plus 4/64]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.85]
 - Release: [Armbian 22.11.1 Bullseye]

**Describe the problem | 问题描述**
I have a problem with home assistant supervised, specifically I have to add string "apparmor=1 security=apparmor" and "systemd.unified_cgroup_hierarchy=0" in /boot/cmdline.txt. The problem is that I don't have this file, so I ask you if I have to create it or I have to insert the two strings in another boot file.  Thanks for your help.

**Comment by d5stick** [comment]
Uroh,

Create the file with sudo:
- sudo -i
- cd /boot/
- sudo nano cmdline.txt
Add the stuff you need
- CTRL + S is to save the file and  CTRL + X is close the nano editor.

**Comment by Orefie** [comment]
hI @uroh

For install HA supervised

install
apt-get install \
python3-dev python3-pip\
rauc-service\
apparmor \
jq \
wget \
curl \
udisks2 \
libglib2.0-bin \
network-manager \
dbus \
lsb-release \
systemd-journal-remote -y

apt --fix-broken install
apt-get update && apt-get upgrade -y
reboot

install docker and HA

add in /boot/uenv.txt
apparmor=1 security=apparmor systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=0


![armbian](https://user-images.githubusercontent.com/115935914/214494371-7eb8be44-df89-4486-80a1-e45a49994b11.JPG)

![armbian2](https://user-images.githubusercontent.com/115935914/214494387-9e76d266-c2a3-41ec-a151-178ecca7c0da.JPG)

worl well

**Comment by uroh** [comment]
> hI @uroh
> 
> add in /boot/uenv.txt apparmor=1 security=apparmor systemd.unified_cgroup_hierarchy=0 systemd.legacy_systemd_cgroup_controller=0
> 

Thanks @Orefie 
Now system is supported:
 
## System Information

version | core-2023.1.7
-- | --
installation_type | Home Assistant Supervised
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.10.7
os_name | Linux
os_version | 5.15.85-flippy-80+o
arch | aarch64
timezone | Europe/Rome
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4726
Installed Version | 1.30.0
Stage | running
Available Repositories | 1195
Downloaded Repositories | 43

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Debian GNU/Linux 11 (bullseye)
-- | --
update_channel | stable
supervisor_version | supervisor-2022.12.1
agent_version | 1.4.1
docker_version | 20.10.23
disk_total | 119.2 GB
disk_used | 23.1 GB
healthy | true
supported | true
supervisor_api | ok
version_api | ok
installed_addons | AdGuard Home (4.7.6), Bookstack (1.4.0), Caddy 2 (1.3.1), File editor (5.5.0), Grafana (8.1.0), Home Assistant Google Drive Backup (0.110.1), InfluxDB (4.5.0), Terminal & SSH (9.6.1), WireGuard (0.7.1), Zigbee2MQTT (1.29.2-1), Node-RED (14.0.1), ESPHome (2022.12.6), MariaDB (2.5.1), phpMyAdmin (0.8.3)

</details>

<details><summary>Dashboards</summary>

dashboards | 1
-- | --
resources | 27
views | 7
mode | storage

</details>

<details><summary>NextDNS</summary>

can_reach_server | ok
-- | --

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | 20 gennaio 2023 14:48
-- | --
current_recorder_run | 25 gennaio 2023 20:08
estimated_db_size | 110.55 MiB
database_engine | mysql
database_version | 10.6.8

</details>

<details><summary>Sonoff</summary>

version | 3.3.1 (b20e33c)
-- | --
cloud_online | 0 / 6
local_online | 4 / 4

</details>

<details><summary>Xiaomi Miot Auto</summary>

component_version | 0.7.5
-- | --
can_reach_server | ok
can_reach_spec | ok
logged_accounts | 1
total_devices | 2

</details>

**Comment by Orefie** [comment]
works fine for me.

**Comment by d5stick** [comment]
> Last question: Does Adguard 4.8.0 work for you? In my server it always gives me the message "[fatal] couldn't start forwarding DNS server: listening to udp socket: listen udp [::1]:53: bind: cannot assign requested address "! Executing the command netstat -tulpn | grep ":53 " I get the following results:
> 
> _tcp 0 0 127.0.0.53:53 0.0.0.0:* LISTEN 843/systemd-resolve tcp 0 0 172.30.32.1:53 0.0.0.0:* LISTEN 9959/./AdGuardHome tcp 0 0 192.168.2.51:53 0.0.0.0:* LISTEN 9959/./AdGuardHome udp 0 0 172.30.32.1:53 0.0.0.0:* 9959/./AdGuardHome udp 0 0 192.168.2.51:53 0.0.0.0:* 9959/./AdGuardHome udp 0 0 127.0.0.53:53 0.0.0.0:* 843/systemd-resolve_
> 
> while it should be like the ones below (hassio with adguard 4.8.0 running on an i3 server with debian bullseye distribution):
> 
> _tcp 0 0 127.0.0.1:53 0.0.0.0:* LISTEN 5395/./AdGuardHome tcp 0 0 172.30.32.1:53 0.0.0.0:* LISTEN 5395/./AdGuardHome tcp 0 0 192.168.2.52:53 0.0.0.0:* LISTEN 5395/./AdGuardHome tcp 0 0 127.0.0.53:53 0.0.0.0:* LISTEN 312/systemd-resolve tcp6 0 0 ::1:53 :::* LISTEN 5395/./AdGuardHome udp 0 0 127.0.0.1:53 0.0.0.0:* 5395/./AdGuardHome udp 0 0 172.30.32.1:53 0.0.0.0:* 5395/./AdGuardHome udp 0 0 192.168.2.52:53 0.0.0.0:* 5395/./AdGuardHome udp 0 0 127.0.0.53:53 0.0.0.0:* 312/systemd-resolve udp6 0 0 ::1:53 :::* 5395/./AdGuardHome_


Following should fix the port 53 issue.: 

sudo nano /etc/systemd/resolved.conf
DNSStublistener=no
sudo service systemd-resolved restart

**Comment by uroh** [comment]
No @d5stick!
The solution is to comment out a few lines in the /etc/sysctl.conf file:
`
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1 
`

**Comment by Orefie** [comment]
HI @uroh 
This is the best way for deactivated ipv6 but you are missing one line for debian in the /etc/sysctl.conf file:
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
**net.ipv6.conf.tun0.disable_ipv6 = 1**

**Comment by uroh** [comment]
I don't have this line! In any case to start adguard it is necessary to comment these lines (I added the suggested one):
```
# net.ipv6.conf.all.disable_ipv6 = 1
# net.ipv6.conf.default.disable_ipv6 = 1
# net.ipv6.conf.lo.disable_ipv6 = 1
# net.ipv6.conf.tun0.disable_ipv6 = 1
```
