### ISSUE TITLE
M401A 刷bullseye5.15.88 可以U盘启动，但是刷不进emmc，报错提示无法挂载BOOTFS分区

### ISSUE THREAD

**Issue by Ae01688** [ophub/amlogic-s9xxx-armbian#972]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905L3A]
 - Model [M401A]

**Armbian Version | 系统版本**
 - Kernel Version: [Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.88_server_2023.01.18.img]
 - Release: [bullseye]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
U盘可以正常启动armbian，但是在刷入emmc的时候，一直无法成功。
已替换boot分区中的dtb文件按和修改如下：
*****
![image](https://user-images.githubusercontent.com/123539577/214507715-274d78a8-3668-436c-b441-c7d8f55948e8.png)

*****
且会报错如下：
rm: cannot remove '/etc/machine-id': Device or resource busy
dd: fsync failed for '/dev/mmcblk2': Input/output error
mkfs.fat 4.2 (2021-01-31)
mkfs.vfat: unable to open /dev/mmcblk2p1: No such file or directory
mount: /ddbr/install: special device /dev/mmcblk2p1 does not exist.
[ ERROR ] Failed to mount BOOTFS partition

![image](https://user-images.githubusercontent.com/123539577/214507453-a83ada6d-f59d-4e6c-b14e-ec025f003e90.png)

**Comment by OPMonday** [comment]
fdisk -l
看看有没有/dev/mmcblk2p1

**Comment by ophub** [comment]
lsblk 看一下分区能不能看到。选择btrfs试试

**Comment by Ae01688** [comment]
> lsblk 看一下分区能不能看到。选择btrfs试试

o大你好，首先感谢你抽空回答我的问题~
下面这个是lsblk的返回结果：
![image](https://user-images.githubusercontent.com/123539577/214540984-ce7a2114-c302-404f-9afe-1f82a764191c.png)
下面是尝试了btrfs的结果，还是会报错一样的信息。
我查看了一些以往已关闭的问题，有人说是这个报错是emmc的速度太高，要使用调低频率的dtb文件，请问o大，我的情况也是这样嘛？如果是的话，请问o大我该去哪里能找到低频的dtb文件和uboot文件呀？
![image](https://user-images.githubusercontent.com/123539577/214542035-a2bd3d56-ac49-40c6-9bcf-e08b79569a4e.png)

**Comment by ophub** [comment]
https://github.com/unifreq/linux-5.15.y/blob/6e613a90f4608b4684d24a31690a06420ea77c78/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-m401a.dts#L86


已经是从200调为100了。你试试50

**Comment by Ae01688** [comment]
> https://github.com/unifreq/linux-5.15.y/blob/6e613a90f4608b4684d24a31690a06420ea77c78/arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-m401a.dts#L86
> 
> 已经是从200调为100了。你试试50

感谢o大回复我~
弱弱的问一下，这个文件应该怎么用呀

**Comment by OPMonday** [comment]
编译变成dtb

**Comment by Ae01688** [comment]
> 编译变成dtb,然后替换你现在的dtb

感谢大佬的回答啊，这个可能有点涉及到我目前的知识盲区了，能请教下如何编译嘛

**Comment by OPMonday** [comment]
你可以看看O大
https://github.com/OPMonday/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md

**Comment by Ae01688** [comment]
> 你可以看看O大 https://github.com/OPMonday/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md 我正在想办法超频，我可以帮你试试

感谢大佬！！！！ 我来研究一下

**Comment by OPMonday** [comment]
![image](https://user-images.githubusercontent.com/105340869/214561322-c6c4d0f8-27b8-4eb8-973e-15b38e900fd6.png)
已经开始了，得等一会

**Comment by Ae01688** [comment]
各位大佬，我突然写入成功了，可是我似乎什么都没有做啊...可能是涉及到了我的知识盲区，突然成功的有一些玄学。
我回忆了一下我的操作，供其它不能刷入emmc的小伙伴一些参考吧：
首先尝试之前的已关闭的一个回答，先把红框里的文件换成了【meson-g12a-u200.dtb】说是低频的 M401A可以使用这个dtb，然后使用armbin-install写入emmc，失败，和之前的报错一样。
![image](https://user-images.githubusercontent.com/123539577/214560687-4a14029f-990e-449e-8548-71f6d82166b2.png)
![image](https://user-images.githubusercontent.com/123539577/214563441-922d93bc-028c-4865-92da-3701fd461e71.png)
然后我又把红框里的文件改回了【meson-g12a-s905l3a-m401a.dtb】，尝试armbian-install 写入 emmc，还是失败，这次的报错信息变成了下面这样：
![image](https://user-images.githubusercontent.com/123539577/214562499-52c6777d-fc71-4b11-b06a-2e66690758d7.png)
然后不死心，又重新输入了一遍armbian-install，尝试写入emmc，又失败了，这次的报错信息是下面这样：
![image](https://user-images.githubusercontent.com/123539577/214562919-c0dc47ff-8986-4aef-a8e2-d410bde855b1.png)
然后我寻思重启一下，就**sync && reboot**重启了一下，同步重启之后，尝试写入emmc就成功了...
![image](https://user-images.githubusercontent.com/123539577/214564240-150dd253-d127-4b0e-b687-f3394888d93b.png)

**Comment by Ae01688** [comment]
> ![image](https://user-images.githubusercontent.com/105340869/214561322-c6c4d0f8-27b8-4eb8-973e-15b38e900fd6.png) 已经开始了，得等一会

好的呀，谢谢大佬了！！ 我刚才很莫名奇妙的，十分玄学的就刷入emmc成功了。大佬的dtb文件要是编译完了，可以也先发我一份嘛。我也想复现看看，到底是不是emmc频率太高的缘故。

**Comment by OPMonday** [comment]
好

**Comment by Ae01688** [comment]
> https://github.com/OPMonday/amlogic-s9xxx-armbian/releases/tag/kernel_5.15.90 注意:这个里面的cm311-1a的dtb是超频版的不要用

好的好的 十分感谢大佬你能抽空回答我的问题~ 我下载下来尝试看看

**Comment by Ae01688** [comment]
> https://github.com/OPMonday/amlogic-s9xxx-armbian/releases/tag/kernel_5.15.90 注意:这个里面的cm311-1a的dtb是超频版的不要用
大佬 问一下 现在下面红框里的这个 你设置的emmc频率现在是多少呀啊
![image](https://user-images.githubusercontent.com/123539577/214569170-4563ea93-af40-4e19-92ad-a72b7e275984.png)

**Comment by ophub** [comment]
OPMonday 的方法很正确，就是他这样编译个性化内核（或者只编译dtb）。

fork后改内核源码仓库（并调整dts）、改编译仓库、选择dtbs快速编译dtb

这三个操作方法就是全部。

**Comment by OPMonday** [comment]
![image](https://user-images.githubusercontent.com/105340869/214570197-084d22c7-9def-47f2-987a-5c6b003e98f1.png)
应该是2.Ghz几

**Comment by janko888** [comment]
你修改usb里的uEnv.txt文件后都没有重启就直接armbin-install么？

**Comment by Ae01688** [comment]
> 你修改usb里的uEnv.txt文件后都没有重启就直接armbin-install么？

之前也重启了 但是会报错 后面来回改了几次 重启了一下就好了....

**Comment by Ae01688** [comment]
> ![image](https://user-images.githubusercontent.com/105340869/214572307-45e5702d-0d6f-42e7-9479-2ce20fe659df.png) 100 @Ae01688

好的 好的 谢谢大佬
