### ISSUE TITLE
UNT403A超频成功

### ISSUE THREAD

**Issue by OPMonday** [ophub/amlogic-s9xxx-armbian#974]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [S905L3A]
 - Model [UNT403A]

**Armbian Version | 系统版本**
 - Kernel Version: [5.15.90]
 - Release: [debian]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

![image](https://user-images.githubusercontent.com/105340869/214576679-2d0516d6-7211-4c2d-9c05-8b02f32aa1b2.png)
![image](https://user-images.githubusercontent.com/105340869/214576727-42ac4bfc-4209-4c3f-9a10-9ee11b34fee7.png)
![image](https://user-images.githubusercontent.com/105340869/214576792-3e0ad367-5952-416b-8900-662d54e41348.png)
UNT403A超频成功，测压期间非常稳定，未崩溃，最高温69.5°C

**Comment by OPMonday** [comment]
这是超频所用的dts

#start
// SPDX-License-Identifier: (GPL-2.0+ OR MIT)
/*
 * Copyright (c) 2018 Amlogic, Inc. All rights reserved.
 * Create by flippy
 */

/dts-v1/;

#include "meson-g12a-u200.dts"

/ {
	compatible = "UNT403A", "amlogic,g12a";
	model = "UNT403A";

	aliases {
		serial1 = &uart_A;
	};

	vddgpu: regulator-vddgpu {
		compatible = "regulator-fixed";
		regulator-name = "mali";
		regulator-min-microvolt = <800000>;
		regulator-max-microvolt = <800000>;
		vin-supply = <&main_12v>;
		regulator-boot-on;
		regulator-always-on;
	};

	wifi32k: wifi32k {
		compatible = "pwm-clock";
		#clock-cells = <0>;
		clock-frequency = <32768>;
		pwms = <&pwm_ef 0 30518 0>; /* PWM_E at 32.768KHz */
	};

	sdio_pwrseq: sdio-pwrseq {
		compatible = "mmc-pwrseq-simple";
		reset-gpios = <&gpio GPIOX_6 GPIO_ACTIVE_LOW>;
		clocks = <&wifi32k>;
		clock-names = "ext_clock";
	};

	leds {
		compatible = "gpio-leds";

		power_led {
			led_name = "power_led";
			gpios = <&gpio_ao GPIOAO_11 GPIO_ACTIVE_LOW>;
			default-state = "on";
		};

		net_led {
			led_name = "net_led";
			gpios = <&gpio_ao GPIOAO_9 GPIO_ACTIVE_LOW>;
			default-state = "off";
			linux,default-trigger = "0.0:00:link";
		};

		remote_led {
			led_name = "remote_led";
			gpios = <&gpio_ao GPIOAO_10 GPIO_ACTIVE_LOW>;
			default-state = "off";
			linux,default-trigger = "rc-feedback";
		};
	};

	memory@0 {
		device_type = "memory";
		reg = <0x0 0x0 0x0 0x80000000>;
	};
};

&uart_A {
	status = "okay";
	pinctrl-0 = <&uart_a_pins>, <&uart_a_cts_rts_pins>;
	uart-has-rtscts;
	pinctrl-names = "default";
};

&mali {
	mali-supply=<&vddgpu>;
};

/* SDIO */
&sd_emmc_a {
	status = "okay";
	pinctrl-0 = <&sdio_pins>;
	pinctrl-1 = <&sdio_clk_gate_pins>;
	pinctrl-names = "default", "clk-gate";
	#address-cells = <1>;
	#size-cells = <0>;

	bus-width = <4>;
	cap-sd-highspeed;
	sd-uhs-sdr50;
	max-frequency = <100000000>;

	non-removable;
	disable-wp;

	/* WiFi firmware requires power to be kept while in suspend */
	keep-power-in-suspend;

	mmc-pwrseq = <&sdio_pwrseq>;

	vmmc-supply = <&vddao_3v3>;
	vqmmc-supply = <&vddao_1v8>;

	wifi: wifi@1 {
		reg = <1>;
		compatible = "sprd,unisoc-wifi";
	};
};

/* SD card */
&sd_emmc_b {
	status = "okay";
	bus-width = <4>;
	cap-sd-highspeed;
	max-frequency = <50000000>;
};

/* eMMC */
&sd_emmc_c {
	status = "okay";
	bus-width = <8>;
	cap-mmc-highspeed;
	mmc-ddr-1_8v;
	mmc-hs200-1_8v;
	max-frequency = <200000000>;
};

/* CPU Overclock */
&cpu_opp_table {

	opp-250000000 {
		status = "disabled";
	};

	opp-500000000 {
		status = "disabled";
	};

	opp-667000000 {
		status = "disabled";
	};
	
	opp-1908000000 {
		status = "disabled";
	};
	
	opp-2016000000 {
		opp-hz = /bits/ 64 <2016000000>;
		opp-microvolt = <1021000>;
	};
};

&internal_ephy  {
	max-speed = <100>;
};

#End

**Comment by ophub** [comment]
超的有点太猛了。
