### ISSUE TITLE
无法启动！求解

### ISSUE THREAD

**Issue by grinxxoo** [ophub/amlogic-s9xxx-armbian#977]
芯片: s905l2
设备: mgv2000
版本: armbian 6.1.6 （bullseye）

reboot update后可以进入u-boot，但是无法正常启动 提示card did not respomd to voltage select后循环重启

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/648

比较一下

**Comment by grinxxoo** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/issues/648
> 
> 比较一下

谢谢 已参考并正常从usb启动armbian
