### ISSUE TITLE
使用开心电视助手U盘启动不成功

### ISSUE THREAD

**Issue by 1904688138** [ophub/amlogic-s9xxx-armbian#978]
**Device Information | 设备信息**
 - SOC: S950L3
 - Model CM311-1（HG680-LC）

**Armbian Version | 系统版本**
 - Kernel Version: 
 - Release:使用 Armbian_23.02.0_amlogic_s905l2_jammy_6.1.8_server_2023.01.26.img.gz烧录在U盘启动

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
使用开心电视助手U盘启动后HDMI没有输出，开始怀疑没能启动，后来在路由器后台看到了一个名称是armbian的设备，尝试SSH连接被拒绝
![image](https://user-images.githubusercontent.com/36809290/214849581-1fe87ae2-df99-4903-86fc-22d165702a23.png)
电路板如图
![f35342c80e49dc206dab0e8cba3ea31](https://user-images.githubusercontent.com/36809290/214849879-a4938f30-4e2f-45e6-af43-171fcca121f0.jpg)
![739e52ad9f7d87478d3bdf09917ddd2](https://user-images.githubusercontent.com/36809290/214849907-6e7b75d0-4ec3-487d-a581-f77ad0fda9a0.jpg)
![a08e6b465244323dbeb6ff0d81f68b0](https://user-images.githubusercontent.com/36809290/214849929-5dae6420-b576-4608-9b90-e1f0ed2d629e.jpg)
感谢大佬
萌新求教

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/amlogic_model_database.md

根据说明修改/boot/uEnv.txt

这个盒子的hdmi无输出显示，在路由器里找ip，有2个，其中一个可以ssh

**Comment by 1904688138** [comment]
> 

有些没有理解，我看了一下BUILD 的值是 yes的是打包好的系统，他的FDT 的 dtb 名称和这个没有打包的系统烧录到U盘里的名称是一样的，修改貌似没有意义
另外看了一下路由器后台上只有一个和盒子有关的ip，并没有两个IP

**Comment by ophub** [comment]
cm311默认no没有打包，你下载的固件里的uEnv.txt不会是cm311的吧

**Comment by 1904688138** [comment]
选择的这个系统https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_01.26.1441/Armbian_23.02.0_amlogic_s905l2_jammy_6.1.8_server_2023.01.26.img.gz
![image](https://user-images.githubusercontent.com/36809290/214983512-b5b484ff-4bc5-4656-aa8c-b449591b9a84.png)
uEnv.txt文件里的内容是
![image](https://user-images.githubusercontent.com/36809290/214983839-0934fbdf-48ab-4b1f-b88d-7096b9130ba6.png)
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-gxl-s905l2-x7-5g.dtb
APPEND=root=UUID=19aef94e-5635-47fe-a2f8-8ca62ca601c4 rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1


我是需要下载相同 FAMILY 的打包好的系统然后把这个系统烧录到U盘然后把dtb 名称改成之前的名称吗

**Comment by ophub** [comment]
对，把meson-gxl-s905l2-x7-5g.dtb改成你的cm311的。

有两个cm311，一个是cm311-1a-yst，一个是cm311-1，在首页的说明里有设备链接对应的测试说明，里面有第一个贡献者的使用说明，有些设备还要刷一个链接里面的安卓系统，你仔细阅读相关贴子，根据他们提供的照片和资料对比一下。

**Comment by 1904688138** [comment]
> 对，把meson-gxl-s905l2-x7-5g.dtb改成你的cm311的。
> 
> 有两个cm311，一个是cm311-1a-yst，一个是cm311-1，在首页的说明里有设备链接对应的测试说明，里面有第一个贡献者的使用说明，有些设备还要刷一个链接里面的安卓系统，你仔细阅读相关贴子，根据他们提供的照片和资料对比一下。

貌似现在这个系统已经是在运行的了，这个dtb名称对应的就是meson-gxl-s905l2-x7-5g.dtb这个文件并不需要修改
但是我在路由器里只能找到一个有关盒子的IP地址，HDMI也是不能用
![image](https://user-images.githubusercontent.com/36809290/214991834-ea09e594-aa66-4faa-bd64-2eda43e4cd29.png)
现在这个盒子就是个植物人hh我不能用ssh连接到他

**Comment by ophub** [comment]
你改一下试试

**Comment by 1904688138** [comment]
刚刚试了一下换成旧版本，能正常连接SSH了
之前用的是https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_01.26.1441/Armbian_23.02.0_amlogic_s905l2_jammy_6.1.8_server_2023.01.26.img.gz 这个不能用
应该用https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_01.26.1441/Armbian_23.02.0_amlogic_s905l2_jammy_5.15.90_server_2023.01.26.img.gz才能连接到SSH
顺带换了一个U盘，想的是省了来回烧录，也可能起效果了
感谢大佬的答复了

**Comment by ophub** [comment]
用的默认的s905l2没有改dtb？

**Comment by 1904688138** [comment]
参考了恩山上的帖子 https://www.right.com.cn/forum/forum.php?mod=viewthread&tid=8221671&highlight=hg680
链接：https://pan.baidu.com/s/1uzNp7ZxPDrWkngz0HN3G3g 
提取码：gqgp
上面是转存的刷机包
这个是cpu（s905l3）和旁边短接点图片，没有用到，上面恩山也说到了![932cc87d8454e1d45d6a977e1e6aea7](https://user-images.githubusercontent.com/36809290/215001027-62ef076f-fc88-438b-a158-3e57b7375ac8.jpg)
![image](https://user-images.githubusercontent.com/36809290/215001356-d5b3ed95-b86e-4a67-834c-0ace5511cbdc.png)
直接烧录的5.15版本系统，未作修改
uEnv.txt文件内容是
root@armbian:~# cat /boot/uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-gxl-s905l2-x7-5g.dtb
APPEND=root=UUID=4c648915-a7d5-4940-8e87-58c4deeacb6d rootflags=data=writeback rw rootfstype=ext4 console=ttyAML0,115200n8 console=tty0 no_console_suspend consoleblank=0 fsck.fix=yes fsck.repair=yes net.ifnames=0 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1
root@armbian:~# ^C

ophub-release是
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='ubuntu'
VERSION_CODENAME='jammy'
SOC='s905l3'
FDTFILE='meson-gxl-s905l2-x7-5g.dtb'
UBOOT_OVERLOAD='u-boot-p212.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
FAMILY='meson-gxl'
BOARD='s905l2'
KERNEL_VERSION='5.15.90'
KERNEL_BRANCH='stable'
K510='0'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
MLUBOOT_STATUS='no'
AMPART_STATUS='yes'
PACKAGED_DATE='2023-01-26'
root@armbian:~# 
![image](https://user-images.githubusercontent.com/36809290/215001464-4b3d3162-cd96-4995-a15b-2a00cbd13dc0.png)
顺带问一下大佬有更新HDMI输出的计划吗

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/2a75cbbbdefa67a55b404db73e3a01d6074f7c55/build-armbian/armbian-files/common-files/etc/model_database.conf#L43

你确定一下哪个u-boot可以使用

**Comment by 1904688138** [comment]
> https://github.com/ophub/amlogic-s9xxx-armbian/blob/2a75cbbbdefa67a55b404db73e3a01d6074f7c55/build-armbian/armbian-files/common-files/etc/model_database.conf#L43
> 
> 你选择的是116序号。你确定一下这个s905l3默认的u-boot是否可以使用
> 
> ```
> cd /boot
> 
> cp -f u-boot-p212.bin u-boot.emmc
> chmod +x u-boot.emmc
> 
> sync && reboot
> ```

执行了一下，正常开机
但是这个指令是干什么的有点不清楚

**Comment by ophub** [comment]
在5.4/5.15里默认不使用u-boot，在5.10/6.1里必须添加（安装或者更新内核时脚本自动添加，不用上面这样手动添加）

你在5.15测试可以，在6.1等其他里面使用也一样，说明这个u-boot可以支持你的设备。

**Comment by 1904688138** [comment]
> 在5.4/5.15里默认不使用u-boot就可以启动（添加了也可以），在5.10/6.1里必须添加才能启动（在安装或者更新内核时脚本自动添加，不用上面这样手动添加）
> 
> 你在5.15测试可以，在6.1等其他里面使用也一样，说明这个u-boot可以支持你的设备。
> 
> 我随后更新列表时把这个设备加到名单里，方便其他人使用。

6.1的系统添加之后就可以正常启动吗，之前U盘启动有问题是因为这个吗

**Comment by ophub** [comment]
6.1默认就已经包含了。而且你路由器都看到IP了，说明已经正常启动了。至于不能ssh和这个无关，可能是ssh服务没启动。

**Comment by lyleaf-81** [comment]
你好，O大，我想问一下，关于hdmi信号没有输出，是什么原因引起的呀。我这边有个小项目需要用到视频输出

**Comment by 1904688138** [comment]
貌似回复错人了，大概是设备树没有做适配，不清楚
可以试试用vnc开远程桌面



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年2月4日(周六) 下午3:38
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978)

**Comment by anser999** [comment]
hdmi 没有输出的还没人解决么？

**Comment by DORW-CHEN** [comment]
> **Device Information | 设备信息**
> 
> * SOC: S950L3
> * Model CM311-1（HG680-LC）
> 
> **Armbian Version | 系统版本**
> 
> * Kernel Version:
> * Release:使用 Armbian_23.02.0_amlogic_s905l2_jammy_6.1.8_server_2023.01.26.img.gz烧录在U盘启动
> 
> **Describe the bug | 问题描述** Describe the problem in detail and attach screenshots if necessary. 使用开心电视助手U盘启动后HDMI没有输出，开始怀疑没能启动，后来在路由器后台看到了一个名称是armbian的设备，尝试SSH连接被拒绝 ![image](https://user-images.githubusercontent.com/36809290/214849581-1fe87ae2-df99-4903-86fc-22d165702a23.png) 电路板如图 ![f35342c80e49dc206dab0e8cba3ea31](https://user-images.githubusercontent.com/36809290/214849879-a4938f30-4e2f-45e6-af43-171fcca121f0.jpg) ![739e52ad9f7d87478d3bdf09917ddd2](https://user-images.githubusercontent.com/36809290/214849907-6e7b75d0-4ec3-487d-a581-f77ad0fda9a0.jpg) ![a08e6b465244323dbeb6ff0d81f68b0](https://user-images.githubusercontent.com/36809290/214849929-5dae6420-b576-4608-9b90-e1f0ed2d629e.jpg) 感谢大佬 萌新求教

我也是烽火680 lc刷好了安卓但是怎么都不能从U盘启动，开心助手一点从U盘启动，重启就进了紧急恢复系统那个页面，不知道是哪里的问题，请指教一下！！谢谢

**Comment by Bai-tenser** [comment]
检查一下u盘？有的u盘可能不能作为系统盘，换一个u盘可能就好了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月7日(周日) 凌晨2:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978)

**Comment by DORW-CHEN** [comment]
启动的问题解决了，但是好像armbian包有问题，启动直接黑屏，路由里有没ip，由于你提到的系统包已经无法下载，所以没办法找到问题所在了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月7日(周日) 上午7:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978)




 检查一下u盘？有的u盘可能不能作为系统盘，换一个u盘可能就好了 
 
 
 
 ---原始邮件--- 
 发件人: ***@***.***&amp;gt; 
 发送时间: 2023年5月7日(周日) 凌晨2:26 
 收件人: ***@***.***&amp;gt;; 
 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 
 主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978)

**Comment by daopica** [comment]
> 启动的问题解决了，但是好像armbian包有问题，启动直接黑屏，路由里有没ip，由于你提到的系统包已经无法下载，所以没办法找到问题所在了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年5月7日(周日) 上午7:48 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978) 检查一下u盘？有的u盘可能不能作为系统盘，换一个u盘可能就好了
> ---原始邮件--- 发件人: ***@***.***&amp;gt; 发送时间: 2023年5月7日(周日) 凌晨2:26 收件人: ***@***.***&amp;gt;; 抄送: ***@***.***&amp;gt;;"State ***@***.***&amp;gt;; 主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

请问您这边是怎么解决启动问题的。我目前尝试了多个版本，均无法进入到hg680-lc盒子的armbian系统。每次写录u盘后并且修改了“FDT=/dtb/amlogic/meson-gxl-s905l2-x7-5g.dtb”。 在连接网线后通过开心助手进行u盘启动指令。 无反应或者进入recovery。 也尝试了使用adb shell reboot update命令。也是一样的结果。   反观此前cm311-la的很顺利。哦，对了。现在烽火hg680-lc盒子的第三方安卓固件系统是“130-广州移动烽火HG680-LC_S905L3安卓9.0线刷包.img”

**Comment by Bai-tenser** [comment]
> > 启动的问题解决了，但是好像armbian包有问题，启动直接黑屏，路由里有没ip，由于你提到的系统包已经无法下载，所以没办法找到问题所在了
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2023年5月7日(周日) 上午7:48 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978) 检查一下u盘？有的u盘可能不能作为系统盘，换一个u盘可能就好了
> > ---原始邮件--- 发件人: _**@**_._**&gt; 发送时间: 2023年5月7日(周日) 凌晨2:26 收件人: _**@**_.**_&gt;; 抄送: _**@**_._**&gt;;"State _**@**_.**_&gt;; 主题: Re: [ophub/amlogic-s9xxx-armbian] HG680-LC（s905l3）支持写入emmc使用 (Issue #978) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 请问您这边是怎么解决启动问题的。我目前尝试了多个版本，均无法进入到hg680-lc盒子的armbian系统。每次写录u盘后并且修改了“FDT=/dtb/amlogic/meson-gxl-s905l2-x7-5g.dtb”。 在连接网线后通过开心助手进行u盘启动指令。 无反应或者进入recovery。 也尝试了使用adb shell reboot update命令。也是一样的结果。 反观此前cm311-la的很顺利。哦，对了。现在烽火hg680-lc盒子的第三方安卓固件系统是“130-广州移动烽火HG680-LC_S905L3安卓9.0线刷包.img”

一般来说烧录好系统以后用开心电视设置用u盘启动就可以进armbian了，有可能是镜像有些问题，因为我这当时也是试了几个包才启动起来

**Comment by yiqihongchen** [comment]
同样U盘启动黑屏，或者进恢复界面！目前我也没找到解决办法

**Comment by yiqihongchen** [comment]
我就想问，各位成功的大佬，你们选用的哪个dtb？另外用的哪个ARMBIAN镜像

**Comment by daopica** [comment]
Finally  Got It    空置盒子2周后，偶然想起是否可以试试其他armbian的包，于是在130-广州移动烽火HG680-LC_S905L3安卓9.0线刷包.img的安卓固件下选择Armbian_23.11.0_amlogic_s905l3a_jammy_6.1.57_server_2023.10.13.img.gz。在对deb文件修改meson-gxl-s905l2-x7-5g.dtb。并修改u-boot-p212.bin为u-boot.e..(忘记了可找一下） 重新引导后顺利解决， 希望对朋友们有点帮助。

**Comment by Kissycat** [comment]
>  希望对朋友们有点帮助。

我按你这套操作走一遍，插U盘，进系统，adb reboot update还是进rec（什么紧急恢复系统），
同一个U盘写openelec的镜像插进去会卡一屏反复重启，换成armbian的镜像就会直接进安卓系统，也不知道是为什么..

**Comment by cys1188** [comment]
U盘启动黑屏，就用路由器看看多了哪个ip；ssh正常连这个ip能进去；要注意的是这个ip和你在安卓系统看的是不一样的；

**Comment by cys1188** [comment]
不过正常安装好后，也安装桌面；高清那里还是不能输出画面；还有问问伙伴们，这个680LC的刷了好多安卓9.0的，例如广州移动烽火等，那个ppoe拨号都不能填账号和密码；有谁知道想要ppoe能拨号该怎么弄呢？

**Comment by jsshzw** [comment]
O大 HG680-LC的机顶盒刷机失败经历，前置也是下载了S905L3芯片的包，刷了好几遍都没有刷过去，路由器里面也只有一个armbian的信息，但就是无法连接SSH，后来看了群里的一些讨论，才去找了一些s905l2区安装试试，结果就安装成功了，不过等待IP出来的时间有点长，大约3-4分钟，总算不负所望的刷成功了，
顺便说虾路由器里面如果等不到IP出现，不确定能不能SSH可以利用工具，
![123123](https://github.com/ophub/amlogic-s9xxx-armbian/assets/158823198/a4457796-31c1-4d91-a1f8-5db37025ef9b)
![123123456](https://github.com/ophub/amlogic-s9xxx-armbian/assets/158823198/77d354a1-9f95-40ae-952e-f4f164010320)
工具能看出来那些可以连接SSH，就是说那些IP地址开放了那些端口。小白一个无喷
看了前面的一些讨论，今天用Armbian_23.11.0_amlogic_s905l2-e900v21e_lunar_5.15.138_server_2023.11.12.img包刷机成功了，里面选择的也是116（meson-gxl-s905l2-x7-5g.dtb）这个文件，你们所说的替换本人不会，本人小白一个，哈哈，希望后期能直接把版本更新一下 用s905L3的包就可以直接刷，该多好啊，之前刷CM311-1a都是一把过了，对应版本下载一刷就好了，哈哈，最受提一下HDMI输出这个对我来说无所谓，有肯定是最好咯，
![556644](https://github.com/ophub/amlogic-s9xxx-armbian/assets/158823198/676ef053-4284-4874-bb22-513d3a34d58f)
![55664433](https://github.com/ophub/amlogic-s9xxx-armbian/assets/158823198/a7cfcfb7-4d69-43cd-8be9-f128e0c33cb6)

下面分享我的包地址： 包还在上传中，后期会发布出来

**Comment by ophub** [comment]
感谢分享。
USB第一次启动会慢点，取决于设备和USB的写入速度和磁盘大小，第一次启动要自动扩容分区，会有一些需要调整的设置自动完成，所以会慢点，之后再启动就会快点了。

固件的选择可以参考model表，第14列的BOARD名字就是固件文件名里的关键字。有些设备具有很宽泛的跨soc适用性，不必太拘泥于是s905l3还是s905l3a等，在USB设备里刷入armbian，在设备启动测试这个过程对设备里的系统是无损的，所以多刷刷临近的固件没问题。有些设备我为了和soc一致，把他们放在了对应的model行里了，事实上在首页点击设备名字进去的帖子里，贡献者反馈的时候有些使用的是其他的soc的固件，而不是和设备对应的。

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/common-files/etc/model_database.conf

**Comment by LiukDiihMieu** [comment]
首页提供的S905L3固件直接刷入SSH可以使用，成功安装到emmc，没有HDMI输出。

**Comment by elizabeth-kim** [comment]
`root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
MODEL_ID='120'
MODEL_NAME='CM311-1,HG680-LC,M401A,UNT402A'
SOC='s905l3'
FDTFILE='meson-gxl-s905l2-x7-5g.dtb'
FAMILY='meson-gxl'
BOARD='s905l3'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.6.15'
KERNEL_BACKUP='yes'
BOOT_CONF='uEnv.conf'
ROOTFS_TYPE='ext4'
DISK_TYPE='emmc'
AMPART_STATUS='yes'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-p212.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='ours1505,1904688138,yhxxm,orientzane'
BUILDER_NAME='ophub'`

**Comment by elizabeth-kim** [comment]
> 感谢分享

**Comment by elizabeth-kim** [comment]
root@armbian:~# cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
MODEL_ID='120'
MODEL_NAME='CM311-1,HG680-LC,M401A,UNT402A'
SOC='s905l3'
FDTFILE='meson-gxl-s905l2-x7-5g.dtb'
FAMILY='meson-gxl'
BOARD='s905l3'
KERNEL_REPO='ophub/kernel'
KERNEL_TAGS='stable'
KERNEL_VERSION='6.6.15'
KERNEL_BACKUP='yes'
BOOT_CONF='uEnv.conf'
ROOTFS_TYPE='ext4'
DISK_TYPE='emmc'
AMPART_STATUS='yes'
MLUBOOT_STATUS='no'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
UBOOT_OVERLOAD='u-boot-p212.bin'
BUILD_REPOSITORY='github.com/armbian/build'
REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
CONTRIBUTORS='ours1505,1904688138,yhxxm,orientzane'
BUILDER_NAME='ophub'

**Comment by Kissycat** [comment]
要是能支持HDMI就好了，安卓调不了具体分辨率就很烦..

**Comment by elizabeth-kim** [comment]
evice Information | 设备信息

SOC: S950L3
Model CM311-1（HG680-LC）
Armbian Version | 系统版本

 系统负荷特别高 | 问题描述

Kernel Version:
    root@armbian:/mnt/docker# uptime
    18:40:44 up 1 day, 21:22,  1 user,  load average: 3.90, 4.16, 4.23
    root@armbian:/mnt/docker# cat /etc/ophub-release
    PLATFORM='amlogic'
    VERSION_CODEID='debian'
    VERSION_CODENAME='bullseye'
    MODEL_ID='120'
    MODEL_NAME='CM311-1,HG680-LC,M401A,UNT402A'
    SOC='s905l3'
    FDTFILE='meson-gxl-s905l2-x7-5g.dtb'
    FAMILY='meson-gxl'
    BOARD='s905l3'
    KERNEL_REPO='ophub/kernel'
    KERNEL_TAGS='stable'
    KERNEL_VERSION='6.1.78'
    KERNEL_BACKUP='yes'
    BOOT_CONF='uEnv.conf'
    ROOTFS_TYPE='ext4'
    DISK_TYPE='emmc'
    AMPART_STATUS='yes'
    MLUBOOT_STATUS='no'
    MAINLINE_UBOOT='/usr/lib/u-boot/'
    BOOTLOADER_IMG='/usr/lib/u-boot/'
    UBOOT_OVERLOAD='u-boot-p212.bin'
    BUILD_REPOSITORY='github.com/armbian/build'
    REBUILD_REPOSITORY='github.com/ophub/amlogic-s9xxx-armbian'
    CONTRIBUTORS='ours1505,1904688138,yhxxm,orientzane'
    BUILDER_NAME='ophub'

root@armbian:/mnt/docker# uptime
18:40:44 up 1 day, 21:22,  1 user,  load average: 3.90, 4.16, 4.23

root@armbian:/mnt/docker# vmstat
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 2  3 311552  37996 369784 646512    0    0    31   132   60   49  6  2 43 49  0

只安装了一个casaos，有大神帮忙看看什么问题吗

**Comment by elizabeth-kim** [comment]
找到问题了...
 
%util  88.29

**Comment by wolaiye666** [comment]
> 首页提供的S905L3固件直接刷入SSH可以使用，成功安装到emmc，没有HDMI输出。

请问下 下的哪个版本的 谢谢

**Comment by wolaiye666** [comment]
> > 首页提供的S905L3固件直接刷入SSH可以使用，成功安装到emmc，没有HDMI输出。
> 
> 请问下 下的哪个版本的 谢谢

今天选择 s905l3-cm211 noble 6.1.112 镜像包 直接烧进u.盘 不用设置任何东西 不用改任何东西..开心助手u盘启动后.. 直接运行 armbian-inatsll选择 122  ext4 写入 输入poweroff 拔掉U盘 然后 断电 再启动 直接运行ok.

**Comment by wobuhui666** [comment]
![image](https://github.com/user-attachments/assets/6986e5da-6847-4668-8660-2368600de2c2)
ssh里显示create root password之后就连接断开

**Comment by SunHHB** [comment]
> ![image](https://private-user-images.githubusercontent.com/121330915/395579038-6986e5da-6847-4668-8660-2368600de2c2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NzcxOTIsIm5iZiI6MTczNTk3Njg5MiwicGF0aCI6Ii8xMjEzMzA5MTUvMzk1NTc5MDM4LTY5ODZlNWRhLTY4NDctNDY2OC04NjYwLTIzNjg2MDBkZTJjMi5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMDRUMDc0ODEyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWU1OWE1MTJlYjg5MDgyNTZjY2I5NTc0M2ZhODRkYmY1NjY5NzM3ZjJlZWM5YzM3YThiNjc1NmUwYjc1N2U3NSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.s9QyDz-PwzbMDy7XKAc-ZFuk4gCFHNMcoXiRjCWNHKs) ssh里显示create root password之后就连接断开
第一次要登录修改密码，建议用putty，finalshell就会有你说的问题，第一次连接，下面就直接拒绝。

**Comment by jishumao1** [comment]
大佬，下载连接挂了，有空请重新上一个，感谢大佬分享！
