### ISSUE TITLE
Boot from USB or SD

### ISSUE THREAD

**Issue by Sergio-** [ophub/amlogic-s9xxx-armbian#979]
Hi Folks. Good day. I hope you all are doing good.

I have a M8S Pro L (S912) with Linux M8SPROL 6.1.8-flippy-81+ install and booting from emmc.

I want to boot this device from SD or USB, but, If I flash a USB Drive or SD Card (using balena) and boot the device with it, It continues booting from emmc. 

I also tried turning the device on with the upgrade key pressed... No luck.

How can I boot the device form SD or USB? Thanks for helping.

**Comment by ophub** [comment]
Did you write mainline u-boot while writing emmc（`armbian-install -m yes`）? It should boot from here first when it checks for USB/SD if not used.

If you installed it, you will need to restore the device to Android in order to boot from the USB.
