### ISSUE TITLE
移动硬盘不识别 M401A

### ISSUE THREAD

**Issue by cellistV** [ophub/amlogic-s9xxx-armbian#980]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095l3a]
 - m401A

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.90]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**

u盘可以识别并挂载 ，但是移动硬盘不识别，格式ext4

```
root@armbian:~# modprobe [usb-storage]
modprobe: FATAL: Module [usb-storage] not found in directory /lib/modules/5.15.90-flippy-81+o
root@armbian:~# modprobe [scsi_mod]
modprobe: FATAL: Module [scsi_mod] not found in directory /lib/modules/5.15.90-flippy-81+o

```

Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

**Comment by ophub** [comment]
不需要[]

**Comment by cellistV** [comment]
> 
确实，去掉[]后报错消失，但是我用两个硬盘分别在别的Linux上识别正常，只有它不能识别但可以正常识别U盘。 不知道什么原因

**Comment by ophub** [comment]
基本上是电源的问题。你的盒子1A

你看看硬盘上标的是几A，大硬盘供电不足带不动，严重的一插就过载自动重启保护了

**Comment by cellistV** [comment]
> 基本上是电源的问题。你的盒子的适配器是1A，只留自己用。
> 
> 你看看硬盘上标的是几A，大硬盘供电不足带不动，严重的一插就过载自动重启保护了
好的，谢谢
一块是普通的2.5，一个是msata装在USB盒子里。
