### ISSUE TITLE
请问r3300l设备无法启动如何解决

### ISSUE THREAD

**Issue by zzzop** [ophub/amlogic-s9xxx-armbian#981]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [s905l]
 - Model [r3300l]

**Armbian Version | 系统版本**
 - Kernel Version: [6.1.8]
 - Release: [Armbian_23.02.0_amlogic_s905x_jammy_6.1.8_server_2023.01.26.img.gz](https://github.com/ophub/amlogic-s9xxx-armbian/releases/download/Armbian_jammy_01.26.1441/Armbian_23.02.0_amlogic_s905x_jammy_6.1.8_server_2023.01.26.img.gz)

**Describe the bug | 问题描述**
使用镜像Armbian_5.44_S9xxx_Ubuntu_bionic_3.14.29_server_20180729.img可以正常U盘启动，写入emmc网卡等功能也都正常。此时的dtb是gxl_p212_1g_slowemmc.dtb。
想使用Armbian_23.02.0_amlogic_s905x_jammy_6.1.8_server_2023.01.26.img.gz，最新镜像应该使用哪个dtb以及uboot？尝试默认dtb，meson-gxl-s905x-p212，默认uboot，会反复卡在黑屏及安卓机器人界面。
使用默认dtb，meson-gxl-s905x-p212，换u-boot-s905x-s912.bin会显示如下截图错误。
![IMG_20230128_152218](https://user-images.githubusercontent.com/28821632/215253367-0b255486-fea2-42df-9525-6bbc43ac489b.jpg)

**Comment by ophub** [comment]
meson-gxl-s905x-p212.dtb
u-boot-s905x-s912.bin

**Comment by zzzop** [comment]
> meson-gxl-s905x-p212.dtb u-boot-s905x-s912.bin

这个组合试过了，上面的截图就是。
我尝试5.15.90内核那个版本可以正常使用了

**Comment by ophub** [comment]
5.15.90使用的也是这个组合吧？

meson-gxl-s905x-p212.dtb
u-boot-s905x-s912.bin

这个盒子还没记录过，你方便的话拍一下盒子的主板正反面（知道救砖短接点的话主板上标记一下），盒子背面标签说明。
分享一下他的安卓系统的下载链接。

**Comment by imzlh** [comment]
我的那台r3300l就可以启动，而且有显示，gpu似乎正常甚至可以达到4k60hz
你可以试试看150的s9xx镜像，虽然有些老了但启动完全没有问题，美中不足就是wifi用不了
