### ISSUE TITLE
cm311-1a的usb支持问题（io错误,掉盘）

### ISSUE THREAD

**Issue by zanjie1999** [ophub/amlogic-s9xxx-armbian#982]
**Device Information | 设备信息**
 - SOC: s905l3a
 - Model cm311-1a YST

**Armbian Version | 系统版本**
 - Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.90_server_2023.01.26.img.gz
 - Armbian_22.11.0_Aml_s905l3a_jammy_5.15.72_server_2022.10.06.img.gz
 - 以上为测试过的版本，问题仅存在于cm311-1a的armbian，同一块盘在s905l的armbian工作正常

**Describe the bug | 问题描述**

（今天搜一下发现似乎没有人提到这个问题，于是来提一下）

当使用usb连接硬盘或u盘时，在确认供电充足的情况下，可能会出现usb错误导致usb设备断开连接或是io错误，在使用硬盘时格外明显

测试过JMS567，JMS578和vl716，jms的两款会出现掉盘的现象，vl的会出现io异常，最后文件系统只读，但是重新挂载后仍会在较短的时间内出现io错误，循环reboot大约6次后可正常挂载使用一段时间

使用安国u盘或jms578的固态硬盘也会有偶尔出错的情况导致系统无法启动，断电重启后大概率正常

由于一直在工作的那个cm311-1a yst盒子目前已经在reboot后断网失联，目前暂时无法提供日志，恢复后再补上

这是一个别人的硬盘盒测试帖子 https://www.znds.com/tv-1223684-1-1.html

另外根据b站评论区其他用户反馈，也有其他人出现这种情况，有人说在coreelec下用s905x2的dtb启动硬盘不会掉盘，这个我没有长时间测试过

下面的两张图是在使用jms578硬盘盒子在另一台启动时出现错误的采集卡截图：

![3R2` 2QSV$6 E}0 NWPH~40](https://user-images.githubusercontent.com/16502567/215255032-b53d2d19-4b2a-4b73-9ce4-d42763838621.png)
卡死了，断电重启后是下面这张，也是卡死了
![image](https://user-images.githubusercontent.com/16502567/215255055-4cb4d26b-8bc2-4399-a94b-8f990fad73c9.png)

**Comment by liuyongyong6699** [comment]
这个老问题了，到现在还没有解决，我可以肯定是不是供电问题，用上外置电源供电依旧是重启不识别硬盘

**Comment by 1053265018** [comment]
而且目前cm311的确5.*内核可以引导6.1内核无法u盘引导，只能emmc用update升级内核

**Comment by zanjie1999** [comment]
已使用armbian-update更新至最新系统，并补上dmesg日志
其中多次出现io错误并伴随着reset high-speed USB device

**Comment by ophub** [comment]
https://access.redhat.com/solutions/194273

复制你的日志中的关键信息，搜索引擎中有很多解释及建议。
比如建议降低usb速度的方法。

**Comment by goooooouwa** [comment]
cm311-1a 刷armbian首次进系统依然是以上问题，用的SanDisk 8G USB 2.0的U盘，直接插入靠近网口的USB口，kernel 5.15镜像。

请问是系统问题还是硬件原因？该如何解决？

谢谢。

**Comment by ophub** [comment]
原安卓系统是刷了推荐的那个9.0的系统？

**Comment by goooooouwa** [comment]
盒子是刷的minislimtv的Android TV 9系统，昨天试了用sd卡加读卡器可以正常启动Armbian  22.08 5.16 固件（偶尔启动也会usb reset无限循环），用U盘（2.0/3.0 插任意USB口）还是启动报以上错误无法进入系统。

**Comment by wishday** [comment]
> 已使用armbian-update更新至最新系统，并补上dmesg日志 其中多次出现io错误并伴随着reset high-speed USB device 请大佬看看 @ophub

看样子是armbian本身支持usb3.0 易驱线有问题，我之前用usb2.0线接小容量硬盘很稳，换了3.0接大容量盘就疯狂掉盘了
遗憾的是usb2.0的线最大只能支持到2.2T硬盘，这个不够用

打算换用coreelec试试了

**Comment by zanjie1999** [comment]
@wishday 你有没有usb2的usb hub？试试先插一个hub再插usb3的盘，不知道会不会有好转，这样与s905l3a接触的就是一个usb2设备了

**Comment by ichswarox** [comment]
> 

usb2.0 对硬盘支持的容量也有限制的吗？Usb2.0的hub+usb3.0的易驱线呢

**Comment by SoraKasvgano** [comment]
根据多次试验，usb3.0的u盘多次出现不稳定情况，2.0相对稳定，是否可以让强制让armbian只以2.0的模式驱动u盘/易驱线，屏蔽掉3.0有关的东西？------个人猜测

**Comment by SoraKasvgano** [comment]
参考
https://blog.csdn.net/cuma2369/article/details/107668284

https://www.systutorials.com/how-to-force-a-usb-3-0-port-to-work-in-usb-2-0-mode-in-linux/

**Comment by zanjie1999** [comment]
cm311-1a只有usb2

**Comment by SoraKasvgano** [comment]
> 

是的，当内核发现有usb3.0设备接入的时候总想用xhci去驱动它，此时usb设备发生reset

**Comment by ichswarox** [comment]
> > 
> 
> 是的，当内核发现有usb3.0设备接入的时候总想用xhci去驱动它，此时usb设备发生reset

恍然大悟

**Comment by stkroot** [comment]
> @wishday 你有没有usb2的usb hub？试试先插一个hub再插usb3的盘，不知道会不会有好转，这样与s905l3a接触的就是一个usb2设备了

你试过了没？但是cm311-1a的U口本身就是2.0的吧，按道理换线啥的不是没用吗？因为2.0口本来就没3.0的触点

**Comment by ichswarox** [comment]
> 但是cm311-1a的U口本身就是2.0的吧，按道理换线啥的不是没用吗？因为2.0口本来就没3

解决了 加一个2.0的usb hub

**Comment by zanjie1999** [comment]
> > @wishday你有没有usb2的usb hub？试先插一个hub再插usb3的盘，不知道会不会有好转，这种与s905l3a接触的就是一个usb2设备了
> 
> 你试过没有？但是cm311-1a的U口本身就是2.0的吧，按理换线啥的不是没有用吗？因为2.0口本来就没有3.0的触角

当然没试过，其他设备/系统压根就没这个问题

**Comment by ichswarox** [comment]
> 

我试过了，解决了，加一个2.0的usb hub

**Comment by zanjie1999** [comment]
@ophub 能不能在系统层面把那个usb3.0的root hub屏蔽掉 🤔

**Comment by YanceyChiew** [comment]
我在同款机型上也遇到usb问题，不过并没有io不稳定或掉盘什么的，挂几个月都没问题。就是非常奇葩的如果插着移动硬盘（机械）重启，则重启后无法识别到这个设备，lsusb里都不会出现任何新设备。

这种情况下再重启一次就又能够识别，非常奇葩，当然拔出来再插进去也能识别。

之前我尝试过很多方法想要解决或者定位这个问题，都失败。同样的分区表和文件系统，同样是usb3.0的设备，如果换成U盘就没这问题。移动硬盘外置供电也没有用，之前找到一个用在旧设备上让硬盘有更充足的起转时间的内核参数 usb-storage.delay_use 也没用，毕竟dmesg都没有“new high-speed USB device” event，后面就干脆放弃了。

**Comment by zanjie1999** [comment]
@YanceyChiew 

我这里只要是usb3设备就不行，另外中间串一个usb2的hub可以相对缓解这种问题，但是该掉还是会掉，依然reset，但是概率大概会降低一半吧，一reset就得重启才能修复

**Comment by YanceyChiew** [comment]
> 我这里只要是usb3设备就不行，另外中间串一个usb2的hub可以相对缓解这种问题，但是该掉还是会掉，依然reset，但是概率大概会降低一半吧，一reset就得重启才能修复

我看到你用的内核是5.15，虽然不知道具体有没有影响，但仍可以尝试升级下内核，说不定某次升级就解决了一些造成这种问题的驱动bug。

**Comment by zanjie1999** [comment]
> > 我这里只要是usb3设备就不行，另外中间串一个usb2的hub可以相对缓解这种问题，但是该掉还是会掉，依然reset，但是概率大概会降低一半吧，一reset就得重启才能修复
> 
> 我看到你用的内核是5.15，虽然不知道具体有没有影响，但仍可以尝试升级下内核，说不定某次升级就解决了一些造成这种问题的驱动bug。

我一路升上来的，问题依旧

**Comment by langyxxl** [comment]
我也是cm311-1a yst，用的u盘作为日常armbian系统盘，没写入emmc。

# lsusb -tv
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 5000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/2p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 2: Dev 2, If 0, Class=Mass Storage, Driver=usb-storage, 480M
        ID 21c4:0cd1

发现当io密集时，内核dmesg经常出现
[Aug28 11:49] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 11:51] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 12:05] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 12:10] usb 1-2: reset high-speed USB device number 2 using xhci-hcd

不知道为啥要去reset。所以现在只能自己写个脚本，发现掉盘就强制重启echo b > /proc/sysrq-trigger

**Comment by langyxxl** [comment]
我也是cm311-1a yst，用的u盘作为日常armbian系统盘，没写入emmc。

# lsusb -tv
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/1p, 5000M
    ID 1d6b:0003 Linux Foundation 3.0 root hub
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci-hcd/2p, 480M
    ID 1d6b:0002 Linux Foundation 2.0 root hub
    |__ Port 2: Dev 2, If 0, Class=Mass Storage, Driver=usb-storage, 480M
        ID 21c4:0cd1

发现当io密集时，内核dmesg经常出现
[Aug28 11:49] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 11:51] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 12:05] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 12:10] usb 1-2: reset high-speed USB device number 2 using xhci-hcd

不知道为啥要去reset。所以现在只能自己写个脚本，发现掉盘就强制重启echo b > /proc/sysrq-trigger

**Comment by langyxxl** [comment]
开了一下usb的debug，echo "file drivers/usb/* +p" > /sys/kernel/debug/dynamic_debug/control

谁能看看，完整日志：

[Aug28 11:49] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 11:51] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 12:05] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 12:10] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[Aug28 13:02] xhci-hcd xhci-hcd.3.auto: Cancel URB 0000000070af9627, dev 2, ep 0x1, starting at offset 0xaaecbe0
[  +0.000026] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000021] xhci-hcd xhci-hcd.3.auto: Stopped on Transfer TRB for slot 1 ep 1
[  +0.000015] xhci-hcd xhci-hcd.3.auto: Removing canceled TD starting at 0xaaecbe0 (dma) in stream 0 URB 0000000070af9627
[  +0.000013] xhci-hcd xhci-hcd.3.auto: Set TR Deq ptr 0xaaecc30, cycle 0

[  +0.000007] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000005] xhci-hcd xhci-hcd.3.auto: xhci_giveback_invalidated_tds: Keep cancelled URB 0000000070af9627 TD as cancel_status is 2
[  +0.000012] xhci-hcd xhci-hcd.3.auto: Successful Set TR Deq Ptr cmd, deq = @0aaecc30
[  +0.000008] xhci-hcd xhci-hcd.3.auto: xhci_handle_cmd_set_deq: Giveback cancelled URB 0000000070af9627 TD
[  +0.000007] xhci-hcd xhci-hcd.3.auto: Giveback URB 0000000070af9627, len = 19968, expected = 20480, status = -115
[  +0.000044] xhci-hcd xhci-hcd.3.auto: disable port 2 USB2 hardware LPM
[  +0.000011] xhci-hcd xhci-hcd.3.auto: Set up evaluate context for LPM MEL change.
[  +0.000008] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000017] xhci-hcd xhci-hcd.3.auto: Successful evaluate context command
[  +0.000020] xhci-hcd xhci-hcd.3.auto: set port reset, actual port 1-2 status  = 0xe11
[  +0.050237] xhci-hcd xhci-hcd.3.auto: Port change event, 1-2, id 2, portsc: 0x200e03
[  +0.000020] xhci-hcd xhci-hcd.3.auto: handle_port_status: starting usb1 port polling.
[  +0.017542] xhci-hcd xhci-hcd.3.auto: Get port status 1-2 read: 0x200e03, return 0x100503
[  +0.000048] xhci-hcd xhci-hcd.3.auto: clear port2 reset change, portsc: 0xe03
[  +0.035919] xhci-hcd xhci-hcd.3.auto: xhci_hub_status_data: stopping usb1 port polling
[  +0.024015] xhci-hcd xhci-hcd.3.auto: Resetting device with slot ID 1
[  +0.000022] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000018] xhci-hcd xhci-hcd.3.auto: Completed reset device command.
[  +0.000013] xhci-hcd xhci-hcd.3.auto: Successful reset device command.
[  +0.000089] usb 1-2: reset high-speed USB device number 2 using xhci-hcd
[  +0.003434] xhci-hcd xhci-hcd.3.auto: Slot already in default state
[  +0.087466] xhci-hcd xhci-hcd.3.auto: Waiting for status stage event
[  +0.000096] xhci-hcd xhci-hcd.3.auto: set port reset, actual port 1-2 status  = 0xef1
[  +0.050303] xhci-hcd xhci-hcd.3.auto: Port change event, 1-2, id 2, portsc: 0x200e03
[  +0.000015] xhci-hcd xhci-hcd.3.auto: handle_port_status: starting usb1 port polling.
[  +0.014552] xhci-hcd xhci-hcd.3.auto: Get port status 1-2 read: 0x200e03, return 0x100503
[  +0.000039] xhci-hcd xhci-hcd.3.auto: clear port2 reset change, portsc: 0xe03
[  +0.059952] xhci-hcd xhci-hcd.3.auto: Resetting device with slot ID 1
[  +0.000022] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000017] xhci-hcd xhci-hcd.3.auto: Completed reset device command.
[  +0.000013] xhci-hcd xhci-hcd.3.auto: Can't reset device (slot ID 1) in default state
[  +0.000007] xhci-hcd xhci-hcd.3.auto: Not freeing device rings.
[  +0.000011] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000062] xhci-hcd xhci-hcd.3.auto: Successful setup address command
[  +0.000006] xhci-hcd xhci-hcd.3.auto: Op regs DCBAA ptr = 0x000000079e2000
[  +0.000007] xhci-hcd xhci-hcd.3.auto: Slot ID 1 dcbaa entry @000000009b90dbe9 = 0x0000000aaf3000
[  +0.000009] xhci-hcd xhci-hcd.3.auto: Output Context DMA address = 0xaaf3000
[  +0.000005] xhci-hcd xhci-hcd.3.auto: Internal device address = 1
[  +0.007842] xhci-hcd xhci-hcd.3.auto: xhci_hub_status_data: stopping usb1 port polling
[  +0.012334] xhci-hcd xhci-hcd.3.auto: enable port 2 USB2 hardware LPM
[  +0.000020] xhci-hcd xhci-hcd.3.auto: Set up evaluate context for LPM MEL change.
[  +0.000009] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000018] xhci-hcd xhci-hcd.3.auto: Successful evaluate context command
[  +0.000149] xhci-hcd xhci-hcd.3.auto: Waiting for status stage event
[  +0.000071] xhci-hcd xhci-hcd.3.auto: xhci_drop_endpoint called for udev 000000004e533a20
[  +0.000009] xhci-hcd xhci-hcd.3.auto: xhci_drop_endpoint called for udev 000000004e533a20
[  +0.000016] xhci-hcd xhci-hcd.3.auto: add ep 0x1, slot id 1, new drop flags = 0x0, new add flags = 0x4
[  +0.000013] xhci-hcd xhci-hcd.3.auto: add ep 0x82, slot id 1, new drop flags = 0x0, new add flags = 0x24
[  +0.000008] xhci-hcd xhci-hcd.3.auto: xhci_check_bandwidth called for udev 000000004e533a20
[  +0.000011] xhci-hcd xhci-hcd.3.auto: // Ding dong!
[  +0.000023] xhci-hcd xhci-hcd.3.auto: Successful Endpoint Configure command
[Aug28 13:06] xhci-hcd xhci-hcd.3.auto: Cancel URB 000000005407975f, dev 2, ep 0x1, starting at offset 0xaaec540

**Comment by jqtmviyu** [comment]
`cm311-1a CH` 挂载 exfat 硬盘也出现了 `Input/output error`, 当之前用了一个星期都正常, 突然就开始出错了.
macos openwrt windows虚拟机 上都没问题, 实在没办法, 插路由上算了, smb共享, linux 挂载.

**Comment by wishday** [comment]
早已放弃了 掉盘无解  这种小机顶盒就老老实实挂usb2.0的盘用吧   
挂usb3.0的大硬盘还是太难为它了
也有曲线救国的 说可以刷coreelec系统用没问题

**Comment by langyxxl** [comment]
我也是最后把硬盘插在天翼路由器，开了smb，linux挂载，用了3个月，没问题

**Comment by JackyMao1999** [comment]
魔百盒M401A也有这个问题，USB3.0掉盘严重，多试几次可以长时间用一次

**Comment by smter** [comment]
E900V22D也会遇到这个问题，为此我专门买了个USB2.0的hub，但是没想到问题依旧
我也尝试过在uEnv.txt加参数禁用USB3.0，尝试修改dtb降低USB频率，还是照样掉盘
硬盘盒独立供电，在玩客云上没遇到过掉盘问题的啊，邪了门了

**Comment by zanjie1999** [comment]
> E900V22D也会遇到这个问题，为此我专门买了个USB2.0的hub，但是没想到问题依旧 我也尝试过在uEnv.txt加参数禁用USB3.0，尝试修改dtb降低USB频率，还是照样掉盘 硬盘盒独立供电，在玩客云上没遇到过掉盘问题的啊，邪了门了

说明还是没修呗，用比如coreelec就没有问题，也能跑docker就凑合用吧

**Comment by SoraKasvgano** [comment]
> > E900V22D也会遇到这个问题，为此我专门买了个USB2.0的hub，但是没想到问题依旧 我也尝试过在uEnv.txt加参数禁用USB3.0，尝试修改dtb降低USB频率，还是照样掉盘 硬盘盒独立供电，在玩客云上没遇到过掉盘问题的啊，邪了门了
> 
> 说明这个问题还是没修呗，用比如coreelec就没有问题，也能跑docker就凑合用吧 开发者认为这是用户的问题，不是bug，是用的方式不对，但是事实胜于雄辩，确实有非常多的人遇到了相同的问题，那既然开发者都认为这不是一个bug，那就不用，换别的用就行了呗，项目是别人的，别人爱怎么写就怎么写，这是开发者的自由

哎2333

**Comment by wishday** [comment]
编了个新6.12内核，把XHCI关掉应该能彻底禁用usb3.0，Action编译中将发布在 https://github.com/wishday/kernel

有晶晨盒子的同学可以参考o大帮助文档手动下载更换内核试试
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/documents/README.cn.md#10-%E6%9B%B4%E6%96%B0-armbian-%E5%86%85%E6%A0%B8

**声明：我的盒子已不用，没有测试过，不保证新内核可用，建议先做好数据备份**

**Comment by YanceyChiew** [comment]
> 声明：我的盒子已不用，没有测试过，不保证新内核可用，建议先做好数据备份

今天刚好遇到个硬盘盒USB3突然出问题了，pc上用echi_pci驱动能正常访问，xhci_hcd则会在写入后报io错误，于是在插到电视盒子上时试了下这个内核，发现不识别任何USB设备，看内核配置ehci相关的驱动能开的都开了，唯一那个编译成模块的echi_fsl我也插入试了下，都没效果。
