### ISSUE TITLE
更新一下N1的BCM4345C0.hcd蓝牙驱动

### ISSUE THREAD

**Issue by dy2898** [ophub/amlogic-s9xxx-armbian#984]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]
 - Release: [e.g. jammy]

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

用N1安装homeassistant连接小米蓝牙温湿度计，每3分钟就接收不到蓝牙广播，运行systemctl restart bluetooth
重启服务也不行，后面用rmmod hci_uart && modprobe hci_uart能恢复正常，但是过3分钟故障依，日志显示hci0: command 0x1002 tx timeout
![微信图片_20230129095738](https://user-images.githubusercontent.com/23370460/215300143-12533bf9-3923-4cbe-bcc7-f7d0e3e84d60.png)
https://github.com/RPi-Distro/bluez-firmware/blob/master/broadcom/BCM4345C0.hcd
这个地址更新了驱动，Fix BLE advertising on new phones，更换了就恢复正常了

**Comment by ophub** [comment]
https://github.com/ophub/firmware/commit/fe0c7f6631cc52807e2c599eb6885248066a73e4

更新了

**Comment by louliangsheng** [comment]
I downloaded the latest firmware Armbian_23.02.0_amlogic_s905d_jammy_5.15.90_server_2023.01.28, after sudo apt-get update, armbian-config install bluetooth, bluetooth is still not working, what should I do.

**Comment by ophub** [comment]
下载那个文件覆盖一下

**Comment by louliangsheng** [comment]
大佬，能详细说一下吗，下载https://github.com/RPi-Distro/bluez-firmware/blob/master/broadcom/BCM4345C0.hcd 这个文件吗，复制到N1目录吗，路径是什么
![image](https://user-images.githubusercontent.com/37586254/215321892-5019cb40-7bdb-4589-86bf-2a757937967f.png)

**Comment by louliangsheng** [comment]
![image](https://user-images.githubusercontent.com/37586254/215322784-77af4111-18ac-493c-9da5-a9a8ed2b4ffa.png)

**Comment by ophub** [comment]
/usr/lib/firmware/brcm

**Comment by louliangsheng** [comment]
好的谢谢O大，蓝牙好像已经正常工作二十分钟了，准备写入emmc了。
![image](https://user-images.githubusercontent.com/37586254/215324558-e7d0fd66-b26d-49dd-9f49-a83fdd81d0dd.png)

**Comment by ophub** [comment]
感谢dy2898的分享
