### ISSUE TITLE
driver realtek 8189ftv 

### ISSUE THREAD

**Issue by Aidar4ik-ind** [ophub/amlogic-s9xxx-armbian#987]
due to the fact that the new x 96 mini models are available with a realtek 8189ftv wifi chip that worked on older builds, could you add drivers for it?
**Device Information | 
 - SOC: [S905w]
 - Model [X96 mini]
 - WIFI [rtl8189ftv]

*Armbian Version 23.02.0
*Linux Version 5.10.141
 - Release: [e.g. jammy]

**Describe the bug | 
failed to manually download drivers for Wi-Fi operation. there is no folder "linux-headers-current-sunxi" that is needed to install drivers

**Comment by ophub** [comment]
https://github.com/unifreq/linux-6.1.y/tree/main/drivers/net/wireless/realtek

At present, this driver is not available in the kernel source code and cannot be used.

**Comment by lnrddev** [comment]
Any news about this driver?
