### ISSUE TITLE
魔百盒E900V22D 可以从U盘启动，但执行armbian-install失败

### ISSUE THREAD

**Issue by muxi01** [ophub/amlogic-s9xxx-armbian#989]
Standard chat template, no routine, no chat.
标准聊天模板，无套路不聊天。

**Device Information | 设备信息**
 - SOC: [e.g. S095x3]  S905l3a
 - Model [e.g. HK1]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.100]  5.15.90
 - Release: [e.g. jammy] jammy

**Describe the bug | 问题描述**
Describe the problem in detail and attach screenshots if necessary.
详细描述问题，并在必要时附上屏幕截图。

使用的镜像：Armbian_23.02.0_amlogic_s905l3a_jammy_5.15.90_server_2023.01.30 (4).img.gz
EMMC 型号：
![IMG_20230201_145630](https://user-images.githubusercontent.com/23053634/215982794-e1eea176-0139-4f2e-990f-a5a63fe42a28.jpg)

尝试了，303、304、305 所对应的dtb文件
参考了（#986 魔百盒CM211-1-CH 可以U盘启动，写入EMMC失败  ）中 fsync 改成 sync ，或者 删除conv=sync
安卓系统：9

失败记录：

![IMG_20230201_110325](https://user-images.githubusercontent.com/23053634/215982866-5782b120-288f-47a7-942a-f51c066c85a0.jpg)

**Comment by ophub** [comment]
用304在USB里使用时，有线网络可以正常获得IP使用吧

**Comment by muxi01** [comment]
ifconfig eth0 up ,启动失败，获取不了IP地址。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/compile-kernel/README.cn.md

这是内核从源码编译方法。


或者你看反编译改，找到位置2改1

看12.13

https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/documents/README.cn.md

**Comment by 7Ji** [comment]
> 内核从源码编译

要从内核源码树构建dtb，没有必要编译整个内核。用cpp把c风格的include处理得到符合fdt语法的dts，再用dtc编译成dtb就行了。这个也是Linux编译过程中得到dtb的过程。
```
git clone https://github.com/unifreq/linux-5.15.y.git --single-branch --depth=1
cd linux-5.15.y
vi arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-e900v22c.dts
cpp -nostdinc -I include -I arch -undef -x assembler-with-cpp arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-e900v22c.dts /tmp/e900v22c-low-freq.preprocessed.dts
dtc /tmp/e900v22c-low-freq.preprocessed.dts > /tmp/e900v22c-low-freq.dtb
```
cpp和dtc也可以写在一条，如果不需要无引用的dts的话
```
cpp -nostdinc -I include -I arch -undef -x assembler-with-cpp arch/arm64/boot/dts/amlogic/meson-g12a-s905l3a-e900v22c.dts | dtc > /tmp/e900v22c-low-freq.dtb
```

**Comment by muxi01** [comment]
目前状态：
1.修改了Emmc  的max-frequency = <100000000>;之后，系统安装成功了，并可以从EMMC启动
2.目前有线网卡不通，ifconfig eth0 up. 失败。

**Comment by ophub** [comment]
你刚才改的是meson-g12a-s905l3a-e900v22c.dtb这个吧？

你反编译cm311这个改100
meson-g12a-s905l3a-cm311.dtb
测试这个dtb

这个是在e900v22c上添加了几个和网卡相关的设置，以前cm311用那个时也一样，后来用这个方法解决了。

**Comment by muxi01** [comment]
感谢，问题已经解决：
将 meson-g12a-s905l3a-cm311.dtb 反编译之后修改emmc的max-frequency = <100000000>;再重新编译成dtb,替换原来的meson-g12a-s905l3a-e900v22c.dtb。修改后的dtb稍后上传。

**Comment by muxi01** [comment]
链接: https://pan.baidu.com/s/10Lw8Bv076iyaFwYeoP9w7w?pwd=hy4f 提取码: hy4f 复制这段内容后打开百度网盘手机App，操作更方便哦 
2023-2-3号之前补上，目前网络环境不支持上传网盘

**Comment by ophub** [comment]
我不知道你有没有晕乎了，简单点就是修改/boot/uEnv.txt把dtb名称改为meson-g12a-s905l3a-cm311.dtb

然后上传dtb到/boot/dtb/amlogic即可同名覆盖。

**Comment by muxi01** [comment]
我很确定，昨天晚上改了的cm311.dtb第一次正常工作了，然后重启之后网络又不行了。
目前测试了304，305,306,所对应的dtb都不对。目前仍然无法使用网络
我是已经安装好了，修改的/boot/uEnv.txt文档。

**Comment by hanxuelong321** [comment]
可以把修改后的.dtb分享一下嘛
