### ISSUE TITLE
x96max plus2 100Mbps Ethernet port

### ISSUE THREAD

**Issue by sharicov** [ophub/amlogic-s9xxx-armbian#99]
x96max plus2 (905x3) only connects Ethernet on 100Mbps.
Same setup in Android connects 1Gbps

**Comment by sharicov** [comment]
`ethtool eth0
Settings for eth0:
        Supported ports: [ TP MII ]
        Supported link modes:   10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
        Supported pause frame use: Symmetric Receive-only
        Supports auto-negotiation: Yes
        Supported FEC modes: Not reported
        Advertised link modes:  10baseT/Half 10baseT/Full
                                100baseT/Half 100baseT/Full
        Advertised pause frame use: Symmetric Receive-only
        Advertised auto-negotiation: Yes
        Advertised FEC modes: Not reported
        Link partner advertised link modes:  10baseT/Half 10baseT/Full
                                             100baseT/Half 100baseT/Full
                                             1000baseT/Full
        Link partner advertised pause frame use: No
        Link partner advertised auto-negotiation: Yes
        Link partner advertised FEC modes: Not reported
        Speed: 100Mb/s
        Duplex: Full
        Port: Twisted Pair
        PHYAD: 0
        Transceiver: internal
        Auto-negotiation: on
        MDI-X: Unknown
        Supports Wake-on: ug
        Wake-on: d
        Current message level: 0x0000003f (63)
                               drv probe link timer ifdown ifup
        Link detected: yes`

**Comment by sharicov** [comment]
lshw

*-network:0
       description: Ethernet interface
       physical id: 3
       logical name: eth0
       serial: 9e:61:c5:3d:24:aa
       size: 100Mbit/s
       capacity: 100Mbit/s
       capabilities: ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=st_gmac driverversion=Jan_2016 duplex=full ip=192.168.3.125 link=yes multicast=yes port=twisted pair speed=100Mbit/s

**Comment by sharicov** [comment]
x96max plus 2 
4GB RAM
64GB Flash

**Comment by sharicov** [comment]
Fixed by editing uEnv.txt to look like this:
cat uEnv.txt
LINUX=/zImage
INITRD=/uInitrd
FDT=/dtb/amlogic/meson-sm1-x96-max-plus.dtb

**Comment by ophub** [comment]
In usb, the default is to start with 100m. dtb. When writing emmc, the armbian-install script will be changed to gigabit dtb.

**Comment by sharicov** [comment]
Thanks for quick response, much appreciated.
And if I dont want to install armbian on the emmc? Can i just fix 1Gbps?
Also it appears that ethernet problem is not really fixed. It doea aynv on
1Gbps, but stuck on boot for 5 minutes and loads up without receiving IP
from the router. Also creates eth0:avahi adapter.

**Comment by ophub** [comment]
The x96 max box can only be 100M by default due to its own bootloader. Only when writing emmc and writing the bootloader file copied from hk1 at the same time, can the Gigabit network card be supported.

**Comment by sharicov** [comment]
Can I just change dtb to hk1 in uEnv.txt before the boot?

**Comment by ophub** [comment]
x96max cannot use gigabit dtb without bootloader support

The box of hk1 can be modified

**Comment by sharicov** [comment]
More or less clear, but I still don't understand why I can't install
armbian on microSD with all the scripts, I really don't want to touch the
emmc, at least not yet, and I don't want to break the device.

**Comment by sharicov** [comment]
And also by the way, openwrt and coreelec do boot from microSD with proper
1Gbps support right out of the box.

**Comment by ophub** [comment]
Where did you download the OpenWrt firmware from?

**Comment by sharicov** [comment]
Here: https://github.com/ophub/amlogic-s9xxx-openwrt

**Comment by ophub** [comment]
The same kernel and boot files, this armbian and OpenWrt can actually be understood as a firmware. OpenWrt is refactored by flippy on the basis of armbian.

**Comment by sharicov** [comment]
after some experiments box is no more booting from the microSD.
emmc loads normally to original android, but no more from microSD.
don't know if this is related, but last thing I did with microSD was adding embycore dtb in armbian uEnv.txt
Do you know how can I fix the box?

**Comment by sharicov** [comment]
fixed microSD boot by re-flashing original firmware with  2.2.4 Amlogic USB Burning Tool (latest to work for android 9 devices)
Recreated microSD from your latest release using balena without any changes to the files.
Now it is booting with 5 minutes delay again saying "a start job is running for raise network interfaces" and counting to 5 min 3s" or untill I plag ethernet cable in

**Comment by sharicov** [comment]
After installing armbian to emmc ethernet connecting on 1Gbps (selected ID 52 when installing for x96max-plus-oc
Updated the kernel using armbian-update (don't know if it is necessary for the eth to start acting as 1Gbps).
So huge thanks again for your great project and support!!!

**Comment by ophub** [comment]
52 with -oc is overclocked, 51 without is standard

**Comment by sharicov** [comment]
thanks for clarification.
Could you please assist with a docker question?
I have ran armbian-docker script and selected access with certification during the installation process.
Thank I've seen I am not able to connect and re-ran the script to install it with the local access via port 9000 but now it's not listening on port 9000, cannot connect.


![image](https://user-images.githubusercontent.com/1933626/152341356-b0fa49ba-8990-4a8a-8aab-4f23e70bde0a.png)
![image](https://user-images.githubusercontent.com/1933626/152341453-f0f10959-c771-46f7-bf21-d658de2138df.png)

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/blob/4e67dcaa5cb52afd2a62bf64d09d9edbb03e5337/build-armbian/common-files/files/usr/sbin/armbian-docker#L82

**Comment by ophub** [comment]
If there is no certificate, delete the portainer container and use the container without certificate.

**Comment by sharicov** [comment]
Completely removed docker and re-ran the script armbian-docker
dpkg -l | grep -i docker
apt-get purge -y docker-ce docker-ce-cli docker-compose  python3-docker python3-dockerpty
apt  autoremove -y --purge docker-ce docker-ce-cli docker-compose  python3-docker python3-dockerpty

BTW box performs very well under armbian:
File copy from windows PC (wifi) to x96max_plus2 using huawei wifi 6 router AX3 pro
![image](https://user-images.githubusercontent.com/1933626/152344557-a05d7ba7-3ba0-4ab8-9af6-d9701271b9ca.png)

iperf over ethernet to another linux box (R4S):
![image](https://user-images.githubusercontent.com/1933626/152345258-853eb790-3593-4eaa-8777-62e91e18981e.png)

all devices using SSD

**Comment by ophub** [comment]
Are you using the default dtb and u-boot of the s905x3?

`cat /etc/ophub-release`

**Comment by sharicov** [comment]
armbian:~:# cat /etc/ophub-release
VERSION_CODENAME='focal'
U_BOOT_EXT='1'
PACKAGED_DATE='2022-01-30'
FDTFILE='meson-sm1-x96-max-plus-oc.dtb'
UBOOT_OVERLOAD='u-boot-x96maxplus.bin'
MAINLINE_UBOOT='/lib/u-boot/x96maxplus-u-boot.bin.sd.bin'
ANDROID_UBOOT='/lib/u-boot/hk1box-bootloader.img'
MYBOX_UBOOT='/lib/u-boot/mybox-bootloader.img'
SOC='s905x3'
KERNEL_VERSION='5.10.96'
K510='1'

Same file transfer from same windows PC over LAN
![image](https://user-images.githubusercontent.com/1933626/152346011-65d07aa9-f5f4-4e70-aa22-4da5b168829e.png)

**Comment by ophub** [comment]
very good

**Comment by sharicov** [comment]
is there a specific reason you are installing portainer 1.24.2 in the armbian script?
The latest version is 2.11.0

**Comment by ophub** [comment]
`portainer/portainer:linux-arm64`

Take the latest docker version officially released, maybe they didn't update the docker image in time.

**Comment by sharicov** [comment]
They had abandoned this branch and created ce (community addition): https://hub.docker.com/r/portainer/portainer-ce

**Comment by sharicov** [comment]
armbian-ddbr is not available in your armbian release, how can I do a backup of the installed system on eMMC?

**Comment by ophub** [comment]
Why gave up? I tested portainer-ce and updated the docker script

**Comment by ophub** [comment]
`armbian-ddbr` was only changed today, you are testing the previous firmware, you use the `ddbr` command. In the future, these two commands will be linked, which is actually one.

**Comment by sharicov** [comment]
x96:~:# ddbr
 DO YOU WANT TO BACKUP OR RESTORE ?
 BACKUP=(b) RESTORE=(r) b
 UNABLE TO FIND YOUR EMMC DRIVE OR YOU ALREADY RUN FROM EMMC!!!

So no way to backup eMMC to external disk?

**Comment by sharicov** [comment]
For the portainer, maybe you are right, but version I get with your script is 1.24.2 while the official latest version is 2.11.0.
Changelog here: https://github.com/portainer/portainer/releases/tag/2.11.0https://github.com/portainer/portainer/releases/tag/2.11.0

**Comment by sharicov** [comment]
> b

the output is after I pressed b...

**Comment by sharicov** [comment]
x96:~:# /usr/sbin/armbian-ddbr
you are running in emmc mode, please boot system with usb or tf card!

**Comment by sharicov** [comment]
would love to be able to do a backup from eMMC while running

**Comment by ophub** [comment]
> For the portainer, maybe you are right, but version I get with your script is 1.24.2 while the official latest version is 2.11.0.

The official version submitted to docker is still a year ago and has not been updated

**Comment by ophub** [comment]
You need to boot from usb to backup the emmc partition. Unable to backup itself in emmc partition.

**Comment by sharicov** [comment]
got it, thanks!

**Comment by sharicov** [comment]
Any plans to make a bullseye based armbian? Would like to run yunohost on
it.

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/releases/tag/Armbian_Aml_bullseye_02.04.0302

**Comment by sharicov** [comment]
Thank you very much, didn't scroll ao far to see it. Will try.
BTW whanted to let yiu know that it's non intuitive, when booting from
microSD first time it askes to set root password and creates a regular
user, but after armbian-install script, when booting from eMMC, it doesnt
remember the regular user, and keeps the new root password.
Maybe better to run root password change script after the installation and
not before?

**Comment by ophub** [comment]
When writing emmc, the user created on the SD card and the modified password should be recorded in emmc. I'll test it.

**Comment by ophub** [comment]
I tested it and it's fine

**Comment by sharicov** [comment]
Strange, I am on bullseye now and didn't create any users besides root, but
I definitely couldn't boot with user I created on first boot  (after focal
was installed to eMMC)

**Comment by ophub** [comment]
![Snip20220204_2](https://user-images.githubusercontent.com/68696949/152504185-01a5a2e2-568c-4ae4-a4d4-d25fba762549.png)


I tested today's image, changed the password on the usb, unplugged the usb after writing emmc, and then booted from emmc, I entered with the new modified password.

**Comment by sharicov** [comment]
Root password worked fine (new one), what didn't work was the username I
created when booted from MicroSD

**Comment by ophub** [comment]
![Snip20220204_3](https://user-images.githubusercontent.com/68696949/152510741-922ac25c-0fe3-478e-88e2-e6b0259eb9d8.png)

![Snip20220204_6](https://user-images.githubusercontent.com/68696949/152510779-4780cab0-e1f6-47e7-bc7f-caaa270ef54b.png)

![Snip20220204_4](https://user-images.githubusercontent.com/68696949/152510794-1dd1ab34-4900-464f-9233-f00dab09d469.png)

**Comment by sharicov** [comment]
Strange, maybe I did something wrong

**Comment by ophub** [comment]
I guess, maybe your sd card is too small to carry your great name.

**Comment by sharicov** [comment]
Thanks for the compliment :)
And for doing amazing job with the project!

**Comment by ophub** [comment]
My ability is limited, fortunately to have everyone's help.

**Comment by sharicov** [comment]
Hi, need your help, I tried to install desktop environment using
armbian-config, it did retrieved some 500+ packages and asked to create a
user (I was working only with root this time), wich I did, and after all
was finished nothing got changes, there is still no GUI, no startx, I also
didn't see any error messages, what got wrong? And what should I do?

**Comment by sharicov** [comment]
Figured out, script to be ran several times until really installs the packages, if there is a connection issue to debian servers script just exits without an error. So once I verified visually the packages were actually installed and rebooted, armbian rebooted into GUI right from the start.
No I am straggling to change the resolution from 1920x1080 to actual monitor resolution of 2560x1080 and refresh rate to 75Hz.
Any hints where to look to?

**Comment by ophub** [comment]
I haven't used the desktop, the server mode I've been using

**Comment by sharicov** [comment]
I see, will keep trying

**Comment by ophub** [comment]
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/diff/?id=v5.10.98&id2=v5.10.97&dt=2

Use the latest version of the kernel for desktop testing, there is a problem with the HDMI interface of the previous version, kernel.org urgently fixes it, you need this to use the desktop

**Comment by sharicov** [comment]
Thanks for the hint, will armbian-update do the needful?

**Comment by ophub** [comment]
yes

**Comment by sharicov** [comment]
Done, thanks!

armbian-update
Ready to update, please wait...
current version: 5.10.98, Latest version: 5.10.98
Already the latest version, no need to update.

**Comment by ophub** [comment]
The latest version is ok
