### ISSUE TITLE
如何为仓库添加支持？

### ISSUE THREAD

**Issue by 13584452567** [ophub/amlogic-s9xxx-armbian#990]
我有一块EAIDK-610的开发板，主控为RK3399。我自己为它编译了armbian固件，我想问一问可否提交这块板子的支持到这个仓库里面，可以的话需要提供哪些文件？
目前这块板子在uboot和kernel源码中都得到了支持。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/tree/main/build-armbian/u-boot/rockchip

这是u-boot的目录，你起个目录放比如叫：eaidk610

https://github.com/ophub/amlogic-s9xxx-armbian/blob/184424dab591ac47142aef4c372812b7ee2aeb44/build-armbian/armbian-files/common-files/etc/model_database.conf#L158

这是配置信息，根据你的设备添加一行

**Comment by 13584452567** [comment]
十分感谢！

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/pull/991

感谢13584452567分享，已经合并，欢迎有设备的朋友测试使用。

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/commit/5cc585147a9bee56df938a6564a427894d052fd8

新增设备的方法我更新到了说明文档里了，大家有觉得使用不便或说明不清晰的地方随时反馈意见。

**Comment by ophub** [comment]
鉴于 rockchip 和 allwinner 的 /boot 文件也通用，我把这2个平台的文件也进行了合并管理。

1. 通用文件放在：`build-armbian/armbian-files/common-files` 目录下，各平台通用。

2. 平台文件分别放在 `build-armbian/armbian-files/platform-files/<platform>` 目录下，[Amlogic](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/amlogic)，[Rockchip](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/rockchip) 和 [Allwinner](https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/build-armbian/armbian-files/platform-files/allwinner) 分别共用各自平台的文件，其中 `bootfs` 目录下是 /boot 分区的文件，`rootfs` 目录下的是 Armbian 系统文件。

3. 如果个别设备有特殊差异化设置需求，在 `build-armbian/armbian-files/different-files` 目录下添加以 `BOARD` 命名的独立目录，根据需要建立 `bootfs` 目录添加系统 /boot 分区下的相关文件，建立 `rootfs` 目录添加系统文件，各文件夹命名以 Armbian 系统中的实际路径为准。
