### ISSUE TITLE
你好，我想问下m401a 在已经把armdebian 刷入了EMMC情况下，请问如何从sd或者USB启动。

### ISSUE THREAD

**Issue by Toanlele** [ophub/amlogic-s9xxx-armbian#992]

**Comment by ophub** [comment]
你是使用的什么命令写入的emmc？
`armbian-install` 还是 `armbian-install -m yes`

**Comment by ophub** [comment]
https://github.com/ophub/amlogic-s9xxx-armbian/issues/729

试试

**Comment by yxmyxmyyy** [comment]
我安装到emmc后还是可以从u盘启动重装的，是不是u盘引导没做好，不是优先启动

**Comment by alanfans** [comment]
设备：UNT403A 2+8 S905L3A
我刷5.15的armbian u盘也是5.15 EMMC 也写入了5.15 可以从u盘启动，
但是我U盘写一个CoreELEC，不能启动成功，同一个U盘，
CoreELEC已经换了几个了，g12a_s905x2_2g.dtb也试了好几个
