### ISSUE TITLE
魔百和CM311-1a YST写入emmc之后，无法启动，必须插着刷机u盘才能开机

### ISSUE THREAD

**Issue by langyxxl** [ophub/amlogic-s9xxx-armbian#995]
**Device Information | 设备信息**
cat /etc/ophub-release
PLATFORM='amlogic'
VERSION_CODEID='debian'
VERSION_CODENAME='bullseye'
SOC='s905l3a'
FDTFILE='meson-g12a-s905l3a-cm311.dtb'
UBOOT_OVERLOAD='u-boot-e900v22c.bin'
MAINLINE_UBOOT='/usr/lib/u-boot/'
BOOTLOADER_IMG='/usr/lib/u-boot/'
FAMILY='meson-g12a'
BOARD='s905l3a'
KERNEL_VERSION='6.1.9'
KERNEL_BRANCH='stable'
K510='1'
ROOTFS_TYPE='ext4'
BOOT_CONF='uEnv.txt'
DISK_TYPE='emmc'
MLUBOOT_STATUS='no'
AMPART_STATUS='yes'
PACKAGED_DATE='2023-02-01'

魔百和CM311-1a YST写入emmc之后，无法启动，必须插着刷机u盘才能开机
不插u盘，hdmi就一直黑屏，并且等了10分钟也没有获取到ip地址，我就认为无法启动就关掉了。

插上u盘就能自动从emmc系统启动，奇怪啊
lsblk
NAME         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda            8:0    1   7.5G  0 disk
├─sda1         8:1    1   255M  0 part
└─sda2         8:2    1   2.5G  0 part
mmcblk2      179:0    0  14.6G  0 disk
├─mmcblk2p1  179:1    0   255M  0 part /boot
└─mmcblk2p2  179:2    0  14.2G  0 part /
mmcblk2boot0 179:32   0     4M  1 disk
mmcblk2boot1 179:64   0     4M  1 disk
zram0        254:0    0 974.5M  0 disk [SWAP]
zram1        254:1    0    50M  0 disk /var/log

我记得去年11月份的时候是插着u盘开机是自动进入u盘系统的，但是现在插着u盘是进入emmc系统
不知道是不是问题

另外我现在想进入u盘系统也不知道怎么进入了

**Comment by langyxxl** [comment]
试了一下#729的方法，还是没办法启动到u盘系统

最后抱着死马当活马的心态，把emmc上boot分区里面rm -rf，结果再重启就直接启动到u盘了

**Comment by ophub** [comment]
你太猛了

**Comment by janko888** [comment]
l3a的soc在armbian6.x下都有写入EMMC后无法从U盘启动的问题,在5.15下正常

**Comment by alanfans** [comment]
我是unt403a 2+8 S905L3A刷的Armbian_23.02.0_amlogic_s905l3a_bullseye_6.1.9_server_2023.02.02 写入EMMC，正常EMMC运行，但是无法u盘启动

**Comment by alanfans** [comment]
正在尝试 #https://github.com/ophub/amlogic-s9xxx-armbian/issues/729 的方案

**Comment by alanfans** [comment]
![image](https://user-images.githubusercontent.com/8871739/216519087-ac595b2e-c1b6-4c8f-8dad-07d8ee50dd49.png)

**Comment by alanfans** [comment]
不成功

**Comment by alanfans** [comment]
过会再刷一下安卓，再用Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.91_server_2023.02.02.img.gz 试一下

**Comment by langyxxl** [comment]
有没有可能是cm311-1a yst厂家自带的u-boot无法识别emmc的boot分区上的启动内容
需要借助u盘boot分区上的aml_autoscript脚本来加载emmc，从而插上u盘可以启动emmc上的系统
拔下u盘就无法启动emmc上的系统

**Comment by alanfans** [comment]
我是unt403a 2+8 S905L3A        5.15.91       ok
刚试了一下，Armbian_23.02.0_amlogic_s905l3a_bullseye_5.15.91_server_2023.02.02.img.gz可以，
写入EMMC后，有u盘就从u盘启动了，没有就从EMMC启动
Armbian_23.02.0_amlogic_s905l3a_bullseye_6.1.9_server_2023.02.02不行

**Comment by ophub** [comment]
用5.15吧
