### ISSUE TITLE
部分M401a写入emmc时错误

### ISSUE THREAD

**Issue by tonywang1201** [ophub/amlogic-s9xxx-armbian#998]
**Device Information | 设备信息**
 - SOC: [s905l3a]
 - Model [M401a]

**Armbian Version | 系统版本**
 - Kernel Version: [e.g. 5.15.85]
 - Release: [jammy]

**Describe the bug | 问题描述**
陆续在几台M401a上尝试安装了armbian，所有的机器用*usb2.0u盘*启动都正常，大部分机器用最新版本自带的`meson-g12a-s905l3a-m401a.dtb`加`u-boot-e900v22c.bin`成功写入emmc，但有两台机器在用上文所述配置写入emmc时出错，分别错误截图如下

![IMG_4018](https://user-images.githubusercontent.com/90188630/216364528-8c8be67d-486f-480c-944b-eb49022639bb.jpeg)
![IMG_4023](https://user-images.githubusercontent.com/90188630/216364541-9b5d990f-54f0-4d3d-ac78-2916c7b43457.jpeg)

**Comment by ysuolmai** [comment]
这个盒子，更准确的说是魔百盒+armbian极其挑u盘，有可能会出现你图里的这种问题。用一个靠谱的u盘，再来看是不是能解决，不然真的很浪费时间，试过10几个u盘后的血泪教训。推荐海康星云，狗东20多64g那个。

emuelec/coreelec就没这些问题。issues里讨论好几次了，目前看起来无解。

**Comment by tonywang1201** [comment]
> 这个盒子，更准确的说是魔百盒+armbian极其挑u盘，有可能会出现你图里的这种问题。用一个靠谱的u盘，再来看是不是能解决，不然真的很浪费时间，试过10几个u盘后的血泪教训。推荐海康星云，狗东20多64g那个。
> 
> emuelec/coreelec就没这些问题。issues里讨论好几次了，目前看起来无解。

感谢回复，我去看看

**Comment by tonywang1201** [comment]
> > 这个盒子，更准确的说是魔百盒+armbian极其挑u盘，有可能会出现你图里的这种问题。用一个靠谱的u盘，再来看是不是能解决，不然真的很浪费时间，试过10几个u盘后的血泪教训。推荐海康星云，狗东20多64g那个。
> > emuelec/coreelec就没这些问题。issues里讨论好几次了，目前看起来无解。
> 
> 感谢回复，我去看看

是usb3.1那一款吗

**Comment by ysuolmai** [comment]
> > > 这个盒子，更准确的说是魔百盒+armbian极其挑u盘，有可能会出现你图里的这种问题。用一个靠谱的u盘，再来看是不是能解决，不然真的很浪费时间，试过10几个u盘后的血泪教训。推荐海康星云，狗东20多64g那个。
> > > emuelec/coreelec就没这些问题。issues里讨论好几次了，目前看起来无解。
> > 
> > 
> > 感谢回复，我去看看
> 
> 是usb3.1那一款吗

对的，那款最便宜，目前用来相当靠谱。

**Comment by ysuolmai** [comment]
你手上要是有usb固态硬盘也可以先试试
