### ISSUE TITLE
armbian-update 最近更新不了了

### ISSUE THREAD

**Issue by hjc757** [ophub/amlogic-s9xxx-armbian#999]
STEPS ] Start downloading the kernel from [ https://github.com/ophub/kernel/tree/main/pub/stable/5.15.91 ]...
svn: E170013: Unable to connect to a repository at URL 'https://github.com/ophub/kernel/trunk/pub/stable/5.15.91'
手动负责网址也打不开，似乎路径不对了

**Comment by ophub** [comment]
可以，你的设备访问github.com不通。你ping github.com

**Comment by wishday** [comment]
以前直接运行armbian-update 不指定任何版本信息可以升级到新版本
现在运行armbian-update，出现 错误信息
请问是需要手工指定kernel版本吗？

[STEPS] Ready to update, please wait ...
[STEPS] Start initialing the environment ...
[INFO] Armbian PLATFORM: [ amlogic ]
[INFO] Set the kernel name: [  ]
[INFO] Set the kernel directory: [ stable ]
[ERROR] Failed to get the version on the server.

**Comment by ophub** [comment]
你的盒子ping github.com 肯定不通，调整自己的网络让访问这个网站畅通。

**Comment by wishday** [comment]
应该不是GitHub被墙导致，手工修改hosts文件后可以ping通 GitHub，但是armbian-update同样报错

**Comment by ophub** [comment]
那你wget下载github任意一个文件，你看看你能下载？

**Comment by wishday** [comment]
已确认，下面命令可以下载成功，但armbian-update 还是不行
wget https://github.com/ophub/amlogic-s9xxx-armbian/blob/main/README.cn.md

**Comment by ophub** [comment]
你看看你下载的文件是和这个一样的文件，还是一返回错误的提示页

**Comment by ophub** [comment]
```
cat /etc/ophub-release
armbian-sync
armbian-update
```

**Comment by wishday** [comment]
感谢o大指导，确认wget 是成功下载了源文件，但根因估计还是网络不稳定，因为使用armbian-sync 跑一半会报无法链接[https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/common-files/usr/share/ophub]，有时能跑过前2步又会出现无法链接'https://github.com/ophub/amlogic-s9xxx-armbian/trunk/build-armbian/armbian-files/platform-files/amlogic/rootfs/usr/share/openvfd'，试了好几次都没法完全跑完armbian-sync

打开armbian-update脚本，发现脚本还用了 api.github.com 域名
于是在hosts手动增加域名IP，这次成功出现了Start downloading kernel...，但最后还是失败

[ STEPS ] Welcome to the kernel update tool.
[ STEPS ] Start checking dependencies...
[ INFO ] Dependency check completes, start updating the kernel.

[ STEPS ] Start initializing the environment...
[ INFO ] Armbian PLATFORM: [ amlogic ]
[ INFO ] Kernel branch: [ stable ]
[ INFO ] Kernel download directory: [ stable ]
[ INFO ] Kernel name: [  ]

[ STEPS ] Start downloading kernel...
[ ERROR ] Failed to get the version on the server.

**Comment by ophub** [comment]
如果在线下载不了，可以手动更新，你想办法把内核文件下载了，然后放在某个目录里，在这个目录下执行armbian-update命令，脚本会使用当前目录的内核。

https://github.com/ophub/kernel/tree/main/pub/stable

**Comment by wishday** [comment]
下了4个最新文件，进入目录，执行armbian-update，重启后一直卡在 systemed[1] dev-disk-by\x2dlabel-BOOT_EMMC.device:Job dev-disk-by\x2dlabel-BOOT_EMMC.device/start failed with result 'timeout'，无法进入系统

于是尝试线刷atv救砖，断电按reset接双公头usb，电脑无法发现设备(确定驱动正常，至少用同一电脑刷过同一个包),amlogic usb burning tool 工具无法启动刷机

基本算变转了😂😂

**Comment by wishday** [comment]
ttl可以输入reboot update，系统目前可以从u盘启动coreelec，但无法从u盘启动armbian

请教o大，我执行armbian-update 是在boot dtb modules header四个压缩包的目录操作的，系统能启动u盘coreelec，说明boot应该没坏，没理解为什么不能u盘启动armbian？

如果我能在coreelec系统装上dd命令，用dd命令把安卓救砖img文件写入emmc是不是也可能救砖成功？

**Comment by ophub** [comment]
能启动coreelec就一定不能启动armbian。盒子emmc只有不是coreelec的时候可以从u盘启动，是安卓/ARMBIAN/OPENWRT都可以。

不同系统有不同写入方法，安卓的img线刷包需要用线刷工具写入。

**Comment by wishday** [comment]
盒子emmc是armbian，执行armbian-update本地升级失败了，按reset按键无法进入线刷模式，才拆机用ttl输入reboot update，发现可以启动u盘coreelec(尝试ceemmc -x把coreelec写入emmc，报错没有执行成功，所以emmc里面应该还是armbian)，于是尝试用armbian u盘修复，发现无法启动。

难道第一次ttl reboot update后直接插入armbian u盘是可以启动的，但是插过了coreelec u盘，系统启动项被ce修改了，后续armbian u盘就无法启动了？

我现在ttl reboot update，或者开机按住reset都无法进入线刷模式，感觉这盒子是不是没救了，只能插u盘用coreelec了。。

**Comment by ophub** [comment]
因特殊原因导致的更新不完整等问题，造成系统无法从 eMMC 启动时，可以从 USB 中启动任意内核版本的 Armbian 系统，运行 armbian-update -r 命令可以把 USB 中的系统内核更新至 eMMC 中，实现救援的目的。

如果不能USB启动armbian就重刷吧

**Comment by wishday** [comment]
现在情况就是  usb启动过coreelec，所以导致无法usb启动armbian。
想按住机身背面reset按键重新线刷，无法进入线刷模式。

请问按reset进入线刷模式和emmc里的BootLoader有没有关系，有没有可能是之前把armbian写入emmc时，选择了使用 Mainline u-boot，导致机器原生BootLoader被uboot替换，从而无法通过reset按键进入线刷模式？

其它没有reset按键、要短接进入线刷的机器，使用 Mainline u-boot之后还能通过短接进入线刷吗？

**Comment by ophub** [comment]
写入了主线u-boot，需要拆机短接才能进入线刷模式

**Comment by wishday** [comment]
已尝试短接线刷，电脑有反应，但无法识别usb设备，提示设备描述符请求失败错误。 

短接进入线刷应该是写死在cpu里的吧，难道刷了boot会导致短接进入线刷功能也失效？

如果是建议其他朋友不要随便尝试写入主线boot了。。
